include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-9-1]]

^<<v58-9-1,1>>^ Ora, também o primeiro pacto tinha ordenanças de serviço sagrado, e um santuário terrestre.

[[v58-9-2]]

^<<v58-9-2,2>>^ Pois foi preparada uma tenda, a primeira, na qual estavam o candeeiro, e a mesa, e os pães da proposição; a essa se chama o santo lugar;

[[v58-9-3]]

^<<v58-9-3,3>>^ mas depois do segundo véu estava a tenda que se chama o santo dos santos,

[[v58-9-4]]

^<<v58-9-4,4>>^ que tinha o incensário de ouro, e a arca do pacto, toda coberta de ouro em redor; na qual estava um vaso de ouro, que continha o maná, e a vara de Arão, que tinha brotado, e as tábuas do pacto;

[[v58-9-5]]

^<<v58-9-5,5>>^ e sobre a arca os querubins da glória, que cobriam o propiciatório; das quais coisas não falaremos agora particularmente.

[[v58-9-6]]

^<<v58-9-6,6>>^ Ora, estando estas coisas assim preparadas, entram continuamente na primeira tenda os sacerdotes, celebrando os serviços sagrados;

[[v58-9-7]]

^<<v58-9-7,7>>^ mas na segunda só o sumo sacerdote, uma vez por ano, não sem sangue, o qual ele oferece por si mesmo e pelos erros do povo;

[[v58-9-8]]

^<<v58-9-8,8>>^ dando o Espírito Santo a entender com isso, que o caminho do santuário não está descoberto, enquanto subsiste a primeira tenda,

[[v58-9-9]]

^<<v58-9-9,9>>^ que é uma parábola para o tempo presente, conforme a qual se oferecem tanto dons como sacrifícios que, quanto à consciência, não podem aperfeiçoar aquele que presta o culto;

[[v58-9-10]]

^<<v58-9-10,10>>^ sendo somente, no tocante a comidas, e bebidas, e várias abluções, umas ordenanças da carne, impostas até um tempo de reforma.

[[v58-9-11]]

^<<v58-9-11,11>>^ Mas Cristo, tendo vindo como sumo sacerdote dos bens já realizados, por meio do maior e mais perfeito tabernáculo &#123;não feito por mãos, isto é, não desta criação&#125;,

[[v58-9-12]]

^<<v58-9-12,12>>^ e não pelo sangue de bodes e novilhos, mas por seu próprio sangue, entrou uma vez por todas no santo lugar, havendo obtido uma eterna redenção.

[[v58-9-13]]

^<<v58-9-13,13>>^ Porque, se a aspersão do sangue de bodes e de touros, e das cinzas duma novilha santifica os contaminados, quanto à purificação da carne,

[[v58-9-14]]

^<<v58-9-14,14>>^ quanto mais o sangue de Cristo, que pelo Espírito eterno se ofereceu a si mesmo imaculado a Deus, purificará das obras mortas a vossa consciência, para servirdes ao Deus vivo?

[[v58-9-15]]

^<<v58-9-15,15>>^ E por isso é mediador de um novo pacto, para que, intervindo a morte para remissão das transgressões cometidas debaixo do primeiro pacto, os chamados recebam a promessa da herança eterna.

[[v58-9-16]]

^<<v58-9-16,16>>^ Pois onde há testamento, necessário é que intervenha a morte do testador.

[[v58-9-17]]

^<<v58-9-17,17>>^ Porque um testamento não tem torça senão pela morte, visto que nunca tem valor enquanto o testador vive.

[[v58-9-18]]

^<<v58-9-18,18>>^ Pelo que nem o primeiro pacto foi consagrado sem sangue;

[[v58-9-19]]

^<<v58-9-19,19>>^ porque, havendo Moisés anunciado a todo o povo todos os mandamentos segundo a lei, tomou o sangue dos novilhos e dos bodes, com água, lã purpúrea e hissopo e aspergiu tanto o próprio livro como todo o povo,

[[v58-9-20]]

^<<v58-9-20,20>>^ dizendo: este é o sangue do pacto que Deus ordenou para vós.

[[v58-9-21]]

^<<v58-9-21,21>>^ Semelhantemente aspergiu com sangue também o tabernáculo e todos os vasos do serviço sagrado.

[[v58-9-22]]

^<<v58-9-22,22>>^ E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.

[[v58-9-23]]

^<<v58-9-23,23>>^ Era necessário, portanto, que as figuras das coisas que estão no céu fossem purificadas com tais sacrifícios, mas as próprias coisas celestiais com sacrifícios melhores do que estes.

[[v58-9-24]]

^<<v58-9-24,24>>^ Pois Cristo não entrou num santuário feito por mãos, figura do verdadeiro, mas no próprio céu, para agora comparecer por nós perante a face de Deus;

[[v58-9-25]]

^<<v58-9-25,25>>^ nem também para se oferecer muitas vezes, como o sumo sacerdote de ano em ano entra no santo lugar com sangue alheio;

[[v58-9-26]]

^<<v58-9-26,26>>^ doutra forma, necessário lhe fora padecer muitas vezes desde a fundação do mundo; mas agora, na consumação dos séculos, uma vez por todas se manifestou, para aniquilar o pecado pelo sacrifício de si mesmo.

[[v58-9-27]]

^<<v58-9-27,27>>^ E, como aos homens está ordenado morrerem uma só vez, vindo depois o juízo,

[[v58-9-28]]

^<<v58-9-28,28>>^ assim também Cristo, oferecendo-se uma só vez para levar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para salvação.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]