include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-3-1]]

^<<v58-3-1,1>>^ Pelo que, santos irmãos, participantes da vocação celestial, considerai o Apóstolo e Sumo Sacerdote da nossa confissão, Jesus,

[[v58-3-2]]

^<<v58-3-2,2>>^ como ele foi fiel ao que o constituiu, assim como também o foi Moisés em toda a casa de Deus.

[[v58-3-3]]

^<<v58-3-3,3>>^ Pois ele é tido por digno de tanto maior glória do que Moisés, quanto maior honra do que a casa tem aquele que a edificou.

[[v58-3-4]]

^<<v58-3-4,4>>^ Porque toda casa é edificada por alguém, mas quem edificou todas as coisas é Deus.

[[v58-3-5]]

^<<v58-3-5,5>>^ Moisés, na verdade, foi fiel em toda a casa de Deus, como servo, para testemunho das coisas que se haviam de anunciar;

[[v58-3-6]]

^<<v58-3-6,6>>^ mas Cristo o é como Filho sobre a casa de Deus; a qual casa somos nós, se tão-somente conservarmos firmes até o fim a nossa confiança e a glória da esperança.

[[v58-3-7]]

^<<v58-3-7,7>>^ Pelo que, como diz o Espírito Santo: Hoje, se ouvirdes a sua voz,

[[v58-3-8]]

^<<v58-3-8,8>>^ não endureçais os vossos corações, como na provocação, no dia da tentação no deserto,

[[v58-3-9]]

^<<v58-3-9,9>>^ onde vossos pais me tentaram, pondo-me à prova, e viram por quarenta anos as minhas obras.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por isto me indignei contra essa geração, e disse: Estes sempre erram em seu coração, e não chegaram a conhecer os meus caminhos.

[[v58-3-11]]

^<<v58-3-11,11>>^ Assim jurei na minha ira: Não entrarão no meu descanso.

[[v58-3-12]]

^<<v58-3-12,12>>^ Vede, irmãos, que nunca se ache em qualquer de vós um perverso coração de incredulidade, para se apartar do Deus vivo;

[[v58-3-13]]

^<<v58-3-13,13>>^ antes exortai-vos uns aos outros todos os dias, durante o tempo que se chama Hoje, para que nenhum de vós se endureça pelo engano do pecado;

[[v58-3-14]]

^<<v58-3-14,14>>^ porque nos temos tornado participantes de Cristo, se é que guardamos firme até o fim a nossa confiança inicial;

[[v58-3-15]]

^<<v58-3-15,15>>^ enquanto se diz: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações, como na provocação;

[[v58-3-16]]

^<<v58-3-16,16>>^ pois quais os que, tendo-a ouvido, o provocaram? Não foram, porventura, todos os que saíram do Egito por meio de Moisés?

[[v58-3-17]]

^<<v58-3-17,17>>^ E contra quem se indignou por quarenta anos? Não foi porventura contra os que pecaram, cujos corpos caíram no deserto?

[[v58-3-18]]

^<<v58-3-18,18>>^ E a quem jurou que não entrariam no seu descanso, senão aos que foram desobedientes?

[[v58-3-19]]

^<<v58-3-19,19>>^ E vemos que não puderam entrar por causa da incredulidade.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]