include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-12-1]]

^<<v58-12-1,1>>^ Portanto, nós também, pois estamos rodeados de tão grande nuvem de testemunhas, deixemos todo embaraço, e o pecado que tão de perto nos rodeia, e corramos com perseverança a carreira que nos está proposta,

[[v58-12-2]]

^<<v58-12-2,2>>^ fitando os olhos em Jesus, autor e consumador da nossa fé, o qual, pelo gozo que lhe está proposto, suportou a cruz, desprezando a ignomínia, e está assentado à direita do trono de Deus.

[[v58-12-3]]

^<<v58-12-3,3>>^ Considerai, pois aquele que suportou tal contradição dos pecadores contra si mesmo, para que não vos canseis, desfalecendo em vossas almas.

[[v58-12-4]]

^<<v58-12-4,4>>^ Ainda não resististes até o sangue, combatendo contra o pecado;

[[v58-12-5]]

^<<v58-12-5,5>>^ e já vos esquecestes da exortação que vos admoesta como a filhos: Filho meu, não desprezes a correção do Senhor, nem te desanimes quando por ele és repreendido;

[[v58-12-6]]

^<<v58-12-6,6>>^ pois o Senhor corrige ao que ama, e açoita a todo o que recebe por filho.

[[v58-12-7]]

^<<v58-12-7,7>>^ É para disciplina que sofreis; Deus vos trata como a filhos; pois qual é o filho a quem o pai não corrija?

[[v58-12-8]]

^<<v58-12-8,8>>^ Mas, se estais sem disciplina, da qual todos se têm tornado participantes, sois então bastardos, e não filhos.

[[v58-12-9]]

^<<v58-12-9,9>>^ Além disto, tivemos nossos pais segundo a carne, para nos corrigirem, e os olhávamos com respeito; não nos sujeitaremos muito mais ao Pai dos espíritos, e viveremos?

[[v58-12-10]]

^<<v58-12-10,10>>^ Pois aqueles por pouco tempo nos corrigiam como bem lhes parecia, mas este, para nosso proveito, para sermos participantes da sua santidade.

[[v58-12-11]]

^<<v58-12-11,11>>^ Na verdade, nenhuma correção parece no momento ser motivo de gozo, porém de tristeza; mas depois produz um fruto pacífico de justiça nos que por ele têm sido exercitados.

[[v58-12-12]]

^<<v58-12-12,12>>^ Portanto levantai as mãos cansadas, e os joelhos vacilantes,

[[v58-12-13]]

^<<v58-12-13,13>>^ e fazei veredas direitas para os vossos pés, para que o que é manco não se desvie, antes seja curado.

[[v58-12-14]]

^<<v58-12-14,14>>^ Segui a paz com todos, e a santificação, sem a qual ninguém verá o Senhor,

[[v58-12-15]]

^<<v58-12-15,15>>^ tendo cuidado de que ninguém se prive da graça de Deus, e de que nenhuma raiz de amargura, brotando, vos perturbe, e por ela muitos se contaminem;

[[v58-12-16]]

^<<v58-12-16,16>>^ e ninguém seja devasso, ou profano como Esaú, que por uma simples refeição vendeu o seu direito de primogenitura.

[[v58-12-17]]

^<<v58-12-17,17>>^ Porque bem sabeis que, querendo ele ainda depois herdar a bênção, foi rejeitado; porque não achou lugar de arrependimento, ainda que o buscou diligentemente com lágrimas.

[[v58-12-18]]

^<<v58-12-18,18>>^ Pois não tendes chegado ao monte palpável, aceso em fogo, e à escuridão, e às trevas, e à tempestade,

[[v58-12-19]]

^<<v58-12-19,19>>^ e ao sonido da trombeta, e à voz das palavras, a qual os que a ouviram rogaram que não se lhes falasse mais;

[[v58-12-20]]

^<<v58-12-20,20>>^ porque não podiam suportar o que se lhes mandava: Se até um animal tocar o monte, será apedrejado.

[[v58-12-21]]

^<<v58-12-21,21>>^ E tão terrível era a visão, que Moisés disse: Estou todo aterrorizado e trêmulo.

[[v58-12-22]]

^<<v58-12-22,22>>^ Mas tendes chegado ao Monte Sião, e à cidade do Deus vivo, à Jerusalém celestial, a miríades de anjos;

[[v58-12-23]]

^<<v58-12-23,23>>^ à universal assembléia e igreja dos primogênitos inscritos nos céus, e a Deus, o juiz de todos, e aos espíritos dos justos aperfeiçoados;

[[v58-12-24]]

^<<v58-12-24,24>>^ e a Jesus, o mediador de um novo pacto, e ao sangue da aspersão, que fala melhor do que o de Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Vede que não rejeiteis ao que fala; porque, se não escaparam aqueles quando rejeitaram o que sobre a terra os advertia, muito menos escaparemos nós, se nos desviarmos daquele que nos adverte lá dos céus;

[[v58-12-26]]

^<<v58-12-26,26>>^ a voz do qual abalou então a terra; mas agora tem ele prometido, dizendo: Ainda uma vez hei de abalar não só a terra, mas também o céu.

[[v58-12-27]]

^<<v58-12-27,27>>^ Ora, esta palavra-Ainda uma vez-significa a remoção das coisas abaláveis, como coisas criadas, para que permaneçam as coisas inabaláveis.

[[v58-12-28]]

^<<v58-12-28,28>>^ Pelo que, recebendo nós um reino que não pode ser abalado, retenhamos a graça, pela qual sirvamos a Deus agradavelmente, com reverência e temor;

[[v58-12-29]]

^<<v58-12-29,29>>^ pois o nosso Deus é um fogo consumidor.

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]