include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-7-1]]

^<<v58-7-1,1>>^ Porque este Melquisedeque, rei de Salém, sacerdote do Deus Altíssimo, que saiu ao encontro de Abraão quando este regressava da matança dos reis, e o abençoou,

[[v58-7-2]]

^<<v58-7-2,2>>^ a quem também Abraão separou o dízimo de tudo &#123;sendo primeiramente, por interpretação do seu nome, rei de justiça, e depois também rei de Salém, que é rei de paz;

[[v58-7-3]]

^<<v58-7-3,3>>^ sem pai, sem mãe, sem genealogia, não tendo princípio de dias nem fim de vida, mas feito semelhante ao Filho de Deus&#125;, permanece sacerdote para sempre.

[[v58-7-4]]

^<<v58-7-4,4>>^ Considerai, pois, quão grande era este, a quem até o patriarca Abraão deu o dízimo dentre os melhores despojos.

[[v58-7-5]]

^<<v58-7-5,5>>^ E os que dentre os filhos de Levi recebem o sacerdócio têm ordem, segundo a lei, de tomar os dízimos do povo, isto é, de seus irmãos, ainda que estes também tenham saído dos lombos de Abraão;

[[v58-7-6]]

^<<v58-7-6,6>>^ mas aquele cuja genealogia não é contada entre eles, tomou dízimos de Abraão, e abençoou ao que tinha as promessas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Ora, sem contradição alguma, o menor é abençoado pelo maior.

[[v58-7-8]]

^<<v58-7-8,8>>^ E aqui certamente recebem dízimos homens que morrem; ali, porém, os recebe aquele de quem se testifica que vive.

[[v58-7-9]]

^<<v58-7-9,9>>^ E, por assim dizer, por meio de Abraão, até Levi, que recebe dízimos, pagou dízimos,

[[v58-7-10]]

^<<v58-7-10,10>>^ porquanto ele estava ainda nos lombos de seu pai quando Melquisedeque saiu ao encontro deste.

[[v58-7-11]]

^<<v58-7-11,11>>^ De sorte que, se a perfeição fosse pelo sacerdócio levítico &#123;pois sob este o povo recebeu a lei&#125;, que necessidade havia ainda de que outro sacerdote se levantasse, segundo a ordem de Melquisedeque, e que não fosse contado segundo a ordem de Arão?

[[v58-7-12]]

^<<v58-7-12,12>>^ Pois, mudando-se o sacerdócio, necessariamente se faz também mudança da lei.

[[v58-7-13]]

^<<v58-7-13,13>>^ Porque aquele, de quem estas coisas se dizem, pertence a outra tribo, da qual ninguém ainda serviu ao altar,

[[v58-7-14]]

^<<v58-7-14,14>>^ visto ser manifesto que nosso Senhor procedeu de Judá, tribo da qual Moisés nada falou acerca de sacerdotes.

[[v58-7-15]]

^<<v58-7-15,15>>^ E ainda muito mais manifesto é isto, se à semelhança de Melquisedeque se levanta outro sacerdote,

[[v58-7-16]]

^<<v58-7-16,16>>^ que não foi feito conforme a lei de um mandamento carnal, mas segundo o poder duma vida indissolúvel.

[[v58-7-17]]

^<<v58-7-17,17>>^ Porque dele assim se testifica: Tu és sacerdote para sempre, segundo a ordem de Melquisedeque.

[[v58-7-18]]

^<<v58-7-18,18>>^ Pois, com efeito, o mandamento anterior é ab-rogado por causa da sua fraqueza e inutilidade

[[v58-7-19]]

^<<v58-7-19,19>>^ &#123;pois a lei nenhuma coisa aperfeiçoou&#125;, e desta sorte é introduzida uma melhor esperança, pela qual nos aproximamos de Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ E visto como não foi sem prestar juramento &#123;porque, na verdade, aqueles, sem juramento, foram feitos sacerdotes,

[[v58-7-21]]

^<<v58-7-21,21>>^ mas este com juramento daquele que lhe disse: Jurou o Senhor, e não se arrependerá: Tu és sacerdote para sempre&#125;,

[[v58-7-22]]

^<<v58-7-22,22>>^ de tanto melhor pacto Jesus foi feito fiador.

[[v58-7-23]]

^<<v58-7-23,23>>^ E, na verdade, aqueles foram feitos sacerdotes em grande número, porque pela morte foram impedidos de permanecer,

[[v58-7-24]]

^<<v58-7-24,24>>^ mas este, porque permanece para sempre, tem o seu sacerdócio perpétuo.

[[v58-7-25]]

^<<v58-7-25,25>>^ Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, porquanto vive sempre para interceder por eles.

[[v58-7-26]]

^<<v58-7-26,26>>^ Porque nos convinha tal sumo sacerdote, santo, inocente, imaculado, separado dos pecadores, e feito mais sublime que os céus;

[[v58-7-27]]

^<<v58-7-27,27>>^ que não necessita, como os sumos sacerdotes, de oferecer cada dia sacrifícios, primeiramente por seus próprios pecados, e depois pelos do povo; porque isto fez ele, uma vez por todas, quando se ofereceu a si mesmo.

[[v58-7-28]]

^<<v58-7-28,28>>^ Porque a lei constitui sumos sacerdotes a homens que têm fraquezas, mas a palavra do juramento, que veio depois da lei, constitui ao Filho, para sempre aperfeiçoado.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]