include::./index.adoc[]

[[v58-6-0]]
=== Hebreus, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-6-1]]

^<<v58-6-1,1>>^ Pelo que deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento de arrependimento de obras mortas e de fé em Deus,

[[v58-6-2]]

^<<v58-6-2,2>>^ e o ensino sobre batismos e imposição de mãos, e sobre ressurreição de mortos e juízo eterno.

[[v58-6-3]]

^<<v58-6-3,3>>^ E isso faremos, se Deus o permitir.

[[v58-6-4]]

^<<v58-6-4,4>>^ Porque é impossível que os que uma vez foram iluminados, e provaram o dom celestial, e se fizeram participantes do Espírito Santo,

[[v58-6-5]]

^<<v58-6-5,5>>^ e provaram a boa palavra de Deus, e os poderes do mundo vindouro,

[[v58-6-6]]

^<<v58-6-6,6>>^ e depois caíram, sejam outra vez renovados para arrependimento; visto que, quanto a eles, estão crucificando de novo o Filho de Deus, e o expondo ao vitupério.

[[v58-6-7]]

^<<v58-6-7,7>>^ Pois a terra que embebe a chuva, que cai muitas vezes sobre ela, e produz erva proveitosa para aqueles por quem é lavrada, recebe a bênção da parte de Deus;

[[v58-6-8]]

^<<v58-6-8,8>>^ mas se produz espinhos e abrolhos, é rejeitada, e perto está da maldição; o seu fim é ser queimada.

[[v58-6-9]]

^<<v58-6-9,9>>^ Mas de vós, ó amados, esperamos coisas melhores, e que acompanham a salvação, ainda que assim falamos.

[[v58-6-10]]

^<<v58-6-10,10>>^ Porque Deus não é injusto, para se esquecer da vossa obra, e do amor que para com o seu nome mostrastes, porquanto servistes aos santos, e ainda os servis.

[[v58-6-11]]

^<<v58-6-11,11>>^ E desejamos que cada um de vós mostre o mesmo zelo até o fim, para completa certeza da esperança;

[[v58-6-12]]

^<<v58-6-12,12>>^ para que não vos torneis indolentes, mas sejais imitadores dos que pela fé e paciência herdam as promessas.

[[v58-6-13]]

^<<v58-6-13,13>>^ Porque, quando Deus fez a promessa a Abraão, visto que não tinha outro maior por quem jurar, jurou por si mesmo,

[[v58-6-14]]

^<<v58-6-14,14>>^ dizendo: Certamente te abençoarei, e grandemente te multiplicarei.

[[v58-6-15]]

^<<v58-6-15,15>>^ E assim, tendo Abraão esperado com paciência, alcançou a promessa.

[[v58-6-16]]

^<<v58-6-16,16>>^ Pois os homens juram por quem é maior do que eles, e o juramento para confirmação é, para eles, o fim de toda contenda.

[[v58-6-17]]

^<<v58-6-17,17>>^ assim que, querendo Deus mostrar mais abundantemente aos herdeiros da promessa a imutabilidade do seu conselho, se interpôs com juramento;

[[v58-6-18]]

^<<v58-6-18,18>>^ para que por duas coisas imutáveis, nas quais é impossível que Deus minta, tenhamos poderosa consolação, nós, os que nos refugiamos em lançar mão da esperança proposta;

[[v58-6-19]]

^<<v58-6-19,19>>^ a qual temos como âncora da alma, segura e firme, e que penetra até o interior do véu;

[[v58-6-20]]

^<<v58-6-20,20>>^ aonde Jesus, como precursor, entrou por nós, feito sacerdote para sempre, segundo a ordem de Melquisedeque.

'''

xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[Próximo Capítulo &#62;]