include::./index.adoc[]

[[v58-10-0]]
=== Hebreus, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-10-1]]

^<<v58-10-1,1>>^ Porque a lei, tendo a sombra dos bens futuros, e não a imagem exata das coisas, não pode nunca, pelos mesmos sacrifícios que continuamente se oferecem de ano em ano, aperfeiçoar os que se chegam a Deus.

[[v58-10-2]]

^<<v58-10-2,2>>^ Doutra maneira, não teriam deixado de ser oferecidos? pois tendo sido uma vez purificados os que prestavam o culto, nunca mais teriam consciência de pecado.

[[v58-10-3]]

^<<v58-10-3,3>>^ Mas nesses sacrifícios cada ano se faz recordação dos pecados,

[[v58-10-4]]

^<<v58-10-4,4>>^ porque é impossível que o sangue de touros e de bodes tire pecados.

[[v58-10-5]]

^<<v58-10-5,5>>^ Pelo que, entrando no mundo, diz: Sacrifício e oferta não quiseste, mas um corpo me preparaste;

[[v58-10-6]]

^<<v58-10-6,6>>^ não te deleitaste em holocaustos e oblações pelo pecado.

[[v58-10-7]]

^<<v58-10-7,7>>^ Então eu disse: Eis-me aqui &#123;no rol do livro está escrito de mim&#125; para fazer, ó Deus, a tua vontade.

[[v58-10-8]]

^<<v58-10-8,8>>^ Tendo dito acima: Sacrifício e ofertas e holocaustos e oblações pelo pecado não quiseste, nem neles te deleitaste &#123;os quais se oferecem segundo a lei&#125;;

[[v58-10-9]]

^<<v58-10-9,9>>^ agora disse: Eis-me aqui para fazer a tua vontade. Ele tira o primeiro, para estabelecer o segundo.

[[v58-10-10]]

^<<v58-10-10,10>>^ É nessa vontade dele que temos sido santificados pela oferta do corpo de Jesus Cristo, feita uma vez para sempre.

[[v58-10-11]]

^<<v58-10-11,11>>^ Ora, todo sacerdote se apresenta dia após dia, ministrando e oferecendo muitas vezes os mesmos sacrifícios, que nunca podem tirar pecados;

[[v58-10-12]]

^<<v58-10-12,12>>^ mas este, havendo oferecido um único sacrifício pelos pecados, assentou-se para sempre à direita de Deus,

[[v58-10-13]]

^<<v58-10-13,13>>^ daí por diante esperando, até que os seus inimigos sejam postos por escabelo de seus pés.

[[v58-10-14]]

^<<v58-10-14,14>>^ Pois com uma só oferta tem aperfeiçoado para sempre os que estão sendo santificados.

[[v58-10-15]]

^<<v58-10-15,15>>^ E o Espírito Santo também no-lo testifica, porque depois de haver dito:

[[v58-10-16]]

^<<v58-10-16,16>>^ Este é o pacto que farei com eles depois daqueles dias, diz o Senhor: Porei as minhas leis em seus corações, e as escreverei em seu entendimento; acrescenta:

[[v58-10-17]]

^<<v58-10-17,17>>^ E não me lembrarei mais de seus pecados e de suas iniqüidades.

[[v58-10-18]]

^<<v58-10-18,18>>^ Ora, onde há remissão destes, não há mais oferta pelo pecado.

[[v58-10-19]]

^<<v58-10-19,19>>^ Tendo pois, irmãos, ousadia para entrarmos no santíssimo lugar, pelo sangue de Jesus,

[[v58-10-20]]

^<<v58-10-20,20>>^ pelo caminho que ele nos inaugurou, caminho novo e vivo, através do véu, isto é, da sua carne,

[[v58-10-21]]

^<<v58-10-21,21>>^ e tendo um grande sacerdote sobre a casa de Deus,

[[v58-10-22]]

^<<v58-10-22,22>>^ cheguemo-nos com verdadeiro coração, em inteira certeza de fé; tendo o coração purificado da má consciência, e o corpo lavado com água limpa,

[[v58-10-23]]

^<<v58-10-23,23>>^ retenhamos inabalável a confissão da nossa esperança, porque fiel é aquele que fez a promessa;

[[v58-10-24]]

^<<v58-10-24,24>>^ e consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras,

[[v58-10-25]]

^<<v58-10-25,25>>^ não abandonando a nossa congregação, como é costume de alguns, antes admoestando-nos uns aos outros; e tanto mais, quanto vedes que se vai aproximando aquele dia.

[[v58-10-26]]

^<<v58-10-26,26>>^ Porque se voluntariamente continuarmos no pecado, depois de termos recebido o pleno conhecimento da verdade, já não resta mais sacrifício pelos pecados,

[[v58-10-27]]

^<<v58-10-27,27>>^ mas uma expectação terrível de juízo, e um ardor de fogo que há de devorar os adversários.

[[v58-10-28]]

^<<v58-10-28,28>>^ Havendo alguém rejeitado a lei de Moisés, morre sem misericórdia, pela palavra de duas ou três testemunhas;

[[v58-10-29]]

^<<v58-10-29,29>>^ de quanto maior castigo cuidais vós será julgado merecedor aquele que pisar o Filho de Deus, e tiver por profano o sangue do pacto, com que foi santificado, e ultrajar ao Espírito da graça?

[[v58-10-30]]

^<<v58-10-30,30>>^ Pois conhecemos aquele que disse: Minha é a vingança, eu retribuirei. E outra vez: O Senhor julgará o seu povo.

[[v58-10-31]]

^<<v58-10-31,31>>^ Horrenda coisa é cair nas mãos do Deus vivo.

[[v58-10-32]]

^<<v58-10-32,32>>^ Lembrai-vos, porém, dos dias passados, em que, depois de serdes iluminados, suportastes grande combate de aflições;

[[v58-10-33]]

^<<v58-10-33,33>>^ pois por um lado fostes feitos espetáculo tanto por vitupérios como por tribulações, e por outro vos tornastes companheiros dos que assim foram tratados.

[[v58-10-34]]

^<<v58-10-34,34>>^ Pois não só vos compadecestes dos que estavam nas prisões, mas também com gozo aceitastes a espoliação dos vossos bens, sabendo que vós tendes uma possessão melhor e permanente.

[[v58-10-35]]

^<<v58-10-35,35>>^ Não lanceis fora, pois, a vossa confiança, que tem uma grande recompensa.

[[v58-10-36]]

^<<v58-10-36,36>>^ Porque necessitais de perseverança, para que, depois de haverdes feito a vontade de Deus, alcanceis a promessa.

[[v58-10-37]]

^<<v58-10-37,37>>^ Pois ainda em bem pouco tempo aquele que há de vir virá, e não tardará.

[[v58-10-38]]

^<<v58-10-38,38>>^ Mas o meu justo viverá da fé; e se ele recuar, a minha alma não tem prazer nele.

[[v58-10-39]]

^<<v58-10-39,39>>^ Nós, porém, não somos daqueles que recuam para a perdição, mas daqueles que crêem para a conservação da alma.

'''

xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[Próximo Capítulo &#62;]