include::./index.adoc[]

[[v58-1-0]]
=== Hebreus, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-1-1]]

^<<v58-1-1,1>>^ Havendo Deus antigamente falado muitas vezes, e de muitas maneiras, aos pais, pelos profetas,

[[v58-1-2]]

^<<v58-1-2,2>>^ nestes últimos dias a nós nos falou pelo Filho, a quem constituiu herdeiro de todas as coisas, e por quem fez também o mundo;

[[v58-1-3]]

^<<v58-1-3,3>>^ sendo ele o resplendor da sua glória e a expressa imagem do seu Ser, e sustentando todas as coisas pela palavra do seu poder, havendo ele mesmo feito a purificação dos pecados, assentou-se à direita da Majestade nas alturas,

[[v58-1-4]]

^<<v58-1-4,4>>^ feito tanto mais excelente do que os anjos, quanto herdou mais excelente nome do que eles.

[[v58-1-5]]

^<<v58-1-5,5>>^ Pois a qual dos anjos disse jamais: Tu és meu Filho, hoje te gerei? E outra vez: Eu lhe serei Pai, e ele me será Filho?

[[v58-1-6]]

^<<v58-1-6,6>>^ E outra vez, ao introduzir no mundo o primogênito, diz: E todos os anjos de Deus o adorem.

[[v58-1-7]]

^<<v58-1-7,7>>^ Ora, quanto aos anjos, diz: Quem de seus anjos faz ventos, e de seus ministros labaredas de fogo.

[[v58-1-8]]

^<<v58-1-8,8>>^ Mas do Filho diz: O teu trono, ó Deus, subsiste pelos séculos dos séculos, e cetro de eqüidade é o cetro do teu reino.

[[v58-1-9]]

^<<v58-1-9,9>>^ Amaste a justiça e odiaste a iniqüidade; por isso Deus, o teu Deus, te ungiu com óleo de alegria, mais do que a teus companheiros;

[[v58-1-10]]

^<<v58-1-10,10>>^ e: Tu, Senhor, no princípio fundaste a terra, e os céus são obras de tuas mãos;

[[v58-1-11]]

^<<v58-1-11,11>>^ eles perecerão, mas tu permaneces; e todos eles, como roupa, envelhecerão,

[[v58-1-12]]

^<<v58-1-12,12>>^ e qual um manto os enrolarás, e como roupa se mudarão; mas tu és o mesmo, e os teus anos não acabarão.

[[v58-1-13]]

^<<v58-1-13,13>>^ Mas a qual dos anjos disse jamais: Assenta-te à minha direita até que eu ponha os teus inimigos por escabelo de teus pés?

[[v58-1-14]]

^<<v58-1-14,14>>^ Não são todos eles espíritos ministradores, enviados para servir a favor dos que hão de herdar a salvação?

'''

xref:057-filemom/057-filemom-001.adoc#v57-1-0[&#60; Capítulo Anterior] | <<v58-1-0,Topo>> | xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[Próximo Capítulo &#62;]