include::./index.adoc[]

[[v58-4-0]]
=== Hebreus, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-4-1]]

^<<v58-4-1,1>>^ Portanto, tendo-nos sido deixada a promessa de entrarmos no seu descanso, temamos não haja algum de vós que pareça ter falhado.

[[v58-4-2]]

^<<v58-4-2,2>>^ Porque também a nós foram pregadas as boas novas, assim como a eles; mas a palavra da pregação nada lhes aproveitou, porquanto não chegou a ser unida com a fé, naqueles que a ouviram.

[[v58-4-3]]

^<<v58-4-3,3>>^ Porque nós, os que temos crido, é que entramos no descanso, tal como disse: Assim jurei na minha ira: Não entrarão no meu descanso; embora as suas obras estivessem acabadas desde a fundação do mundo;

[[v58-4-4]]

^<<v58-4-4,4>>^ pois em certo lugar disse ele assim do sétimo dia: E descansou Deus, no sétimo dia, de todas as suas obras;

[[v58-4-5]]

^<<v58-4-5,5>>^ e outra vez, neste lugar: Não entrarão no meu descanso.

[[v58-4-6]]

^<<v58-4-6,6>>^ Visto, pois, restar que alguns entrem nele, e que aqueles a quem anteriormente foram pregadas as boas novas não entraram por causa da desobediência,

[[v58-4-7]]

^<<v58-4-7,7>>^ determina outra vez um certo dia, Hoje, dizendo por Davi, depois de tanto tempo, como antes fora dito: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações.

[[v58-4-8]]

^<<v58-4-8,8>>^ Porque, se Josué lhes houvesse dado descanso, não teria falado depois disso de outro dia.

[[v58-4-9]]

^<<v58-4-9,9>>^ Portanto resta ainda um repouso sabático para o povo de Deus.

[[v58-4-10]]

^<<v58-4-10,10>>^ Pois aquele que entrou no descanso de Deus, esse também descansou de suas obras, assim como Deus das suas.

[[v58-4-11]]

^<<v58-4-11,11>>^ Ora, à vista disso, procuremos diligentemente entrar naquele descanso, para que ninguém caia no mesmo exemplo de desobediência.

[[v58-4-12]]

^<<v58-4-12,12>>^ Porque a palavra de Deus é viva e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até a divisão de alma e espírito, e de juntas e medulas, e é apta para discernir os pensamentos e intenções do coração.

[[v58-4-13]]

^<<v58-4-13,13>>^ E não há criatura alguma encoberta diante dele; antes todas as coisas estão nuas e patentes aos olhos daquele a quem havemos de prestar contas.

[[v58-4-14]]

^<<v58-4-14,14>>^ Tendo, portanto, um grande sumo sacerdote, Jesus, Filho de Deus, que penetrou os céus, retenhamos firmemente a nossa confissão.

[[v58-4-15]]

^<<v58-4-15,15>>^ Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado.

[[v58-4-16]]

^<<v58-4-16,16>>^ Cheguemo-nos, pois, confiadamente ao trono da graça, para que recebamos misericórdia e achemos graça, a fim de sermos socorridos no momento oportuno.

'''

xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[Próximo Capítulo &#62;]