include::./index.adoc[]

[[v58-11-0]]
=== Hebreus, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-11-1]]

^<<v58-11-1,1>>^ Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que não se vêem.

[[v58-11-2]]

^<<v58-11-2,2>>^ Porque por ela os antigos alcançaram bom testemunho.

[[v58-11-3]]

^<<v58-11-3,3>>^ Pela fé entendemos que os mundos foram criados pela palavra de Deus; de modo que o visível não foi feito daquilo que se vê.

[[v58-11-4]]

^<<v58-11-4,4>>^ Pela fé Abel ofereceu a Deus mais excelente sacrifício que Caim, pelo qual alcançou testemunho de que era justo, dando Deus testemunho das suas oferendas, e por meio dela depois de morto, ainda fala.

[[v58-11-5]]

^<<v58-11-5,5>>^ Pela fé Enoque foi trasladado para não ver a morte; e não foi achado, porque Deus o trasladara; pois antes da sua trasladação alcançou testemunho de que agradara a Deus.

[[v58-11-6]]

^<<v58-11-6,6>>^ Ora, sem fé é impossível agradar a Deus; porque é necessário que aquele que se aproxima de Deus creia que ele existe, e que é galardoador dos que o buscam.

[[v58-11-7]]

^<<v58-11-7,7>>^ Pela fé Noé, divinamente avisado das coisas que ainda não se viam, sendo temente a Deus, preparou uma arca para o salvamento da sua família; e por esta fé condenou o mundo, e tornou-se herdeiro da justiça que é segundo a fé.

[[v58-11-8]]

^<<v58-11-8,8>>^ Pela fé Abraão, sendo chamado, obedeceu, saindo para um lugar que havia de receber por herança; e saiu, sem saber para onde ia.

[[v58-11-9]]

^<<v58-11-9,9>>^ Pela fé peregrinou na terra da promessa, como em terra alheia, habitando em tendas com Isaque e Jacó, herdeiros com ele da mesma promessa;

[[v58-11-10]]

^<<v58-11-10,10>>^ porque esperava a cidade que tem os fundamentos, da qual o arquiteto e edificador é Deus.

[[v58-11-11]]

^<<v58-11-11,11>>^ Pela fé, até a própria Sara recebeu a virtude de conceber um filho, mesmo fora da idade, porquanto teve por fiel aquele que lho havia prometido.

[[v58-11-12]]

^<<v58-11-12,12>>^ Pelo que também de um, e esse já amortecido, descenderam tantos, em multidão, como as estrelas do céu, e como a areia inumerável que está na praia do mar.

[[v58-11-13]]

^<<v58-11-13,13>>^ Todos estes morreram na fé, sem terem alcançado as promessas; mas tendo-as visto e saudado, de longe, confessaram que eram estrangeiros e peregrinos na terra.

[[v58-11-14]]

^<<v58-11-14,14>>^ Ora, os que tais coisas dizem, mostram que estão buscando uma pátria.

[[v58-11-15]]

^<<v58-11-15,15>>^ E se, na verdade, se lembrassem daquela donde haviam saído, teriam oportunidade de voltar.

[[v58-11-16]]

^<<v58-11-16,16>>^ Mas agora desejam uma pátria melhor, isto é, a celestial. Pelo que também Deus não se envergonha deles, de ser chamado seu Deus, porque já lhes preparou uma cidade.

[[v58-11-17]]

^<<v58-11-17,17>>^ Pela fé Abraão, sendo provado, ofereceu Isaque; sim, ia oferecendo o seu unigênito aquele que recebera as promessas,

[[v58-11-18]]

^<<v58-11-18,18>>^ e a quem se havia dito: Em Isaque será chamada a tua descendência,

[[v58-11-19]]

^<<v58-11-19,19>>^ julgando que Deus era poderoso para até dos mortos o ressuscitar; e daí também em figura o recobrou.

[[v58-11-20]]

^<<v58-11-20,20>>^ Pela fé Isaque abençoou Jacó e a Esaú, no tocante às coisas futuras.

[[v58-11-21]]

^<<v58-11-21,21>>^ Pela fé Jacó, quando estava para morrer, abençoou cada um dos filhos de José, e adorou, inclinado sobre a extremidade do seu bordão.

[[v58-11-22]]

^<<v58-11-22,22>>^ Pela fé José, estando próximo o seu fim, fez menção da saída dos filhos de Israel, e deu ordem acerca de seus ossos.

[[v58-11-23]]

^<<v58-11-23,23>>^ Pela fé Moisés, logo ao nascer, foi escondido por seus pais durante três meses, porque viram que o menino era formoso; e não temeram o decreto do rei.

[[v58-11-24]]

^<<v58-11-24,24>>^ Pela fé Moisés, sendo já homem, recusou ser chamado filho da filha de Faraó,

[[v58-11-25]]

^<<v58-11-25,25>>^ escolhendo antes ser maltratado com o povo de Deus do que ter por algum tempo o gozo do pecado,

[[v58-11-26]]

^<<v58-11-26,26>>^ tendo por maiores riquezas o opróbrio de Cristo do que os tesouros do Egito; porque tinha em vista a recompensa.

[[v58-11-27]]

^<<v58-11-27,27>>^ Pela fé deixou o Egito, não temendo a ira do rei; porque ficou firme, como quem vê aquele que é invisível.

[[v58-11-28]]

^<<v58-11-28,28>>^ Pela fé celebrou a páscoa e a aspersão do sangue, para que o destruidor dos primogênitos não lhes tocasse.

[[v58-11-29]]

^<<v58-11-29,29>>^ Pela fé os israelitas atravessaram o Mar Vermelho, como por terra seca; e tentando isso os egípcios, foram afogados.

[[v58-11-30]]

^<<v58-11-30,30>>^ Pela fé caíram os muros de Jericó, depois de rodeados por sete dias.

[[v58-11-31]]

^<<v58-11-31,31>>^ Pela fé Raabe, a meretriz, não pereceu com os desobedientes, tendo acolhido em paz os espias.

[[v58-11-32]]

^<<v58-11-32,32>>^ E que mais direi? Pois me faltará o tempo, se eu contar de Gideão, de Baraque, de Sansão, de Jefté, de Davi, de Samuel e dos profetas;

[[v58-11-33]]

^<<v58-11-33,33>>^ os quais por meio da fé venceram reinos, praticaram a justiça, alcançaram promessas, fecharam a boca dos leões,

[[v58-11-34]]

^<<v58-11-34,34>>^ apagaram a força do fogo, escaparam ao fio da espada, da fraqueza tiraram forças, tornaram-se poderosos na guerra, puseram em fuga exércitos estrangeiros.

[[v58-11-35]]

^<<v58-11-35,35>>^ As mulheres receberam pela ressurreição os seus mortos; uns foram torturados, não aceitando o seu livramento, para alcançarem uma melhor ressurreição;

[[v58-11-36]]

^<<v58-11-36,36>>^ e outros experimentaram escárnios e açoites, e ainda cadeias e prisões.

[[v58-11-37]]

^<<v58-11-37,37>>^ Foram apedrejados e tentados; foram serrados ao meio; morreram ao fio da espada; andaram vestidos de peles de ovelhas e de cabras, necessitados, aflitos e maltratados

[[v58-11-38]]

^<<v58-11-38,38>>^ &#123;dos quais o mundo não era digno&#125;, errantes pelos desertos e montes, e pelas covas e cavernas da terra.

[[v58-11-39]]

^<<v58-11-39,39>>^ E todos estes, embora tendo recebido bom testemunho pela fé, contudo não alcançaram a promessa;

[[v58-11-40]]

^<<v58-11-40,40>>^ visto que Deus provera alguma coisa melhor a nosso respeito, para que eles, sem nós, não fossem aperfeiçoados.

'''

xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[&#60; Capítulo Anterior] | <<v58-11-0,Topo>> | xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[Próximo Capítulo &#62;]