include::./index.adoc[]

[[v58-2-0]]
=== Hebreus, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-2-1]]

^<<v58-2-1,1>>^ Por isso convém atentarmos mais diligentemente para as coisas que ouvimos, para que em tempo algum nos desviemos delas.

[[v58-2-2]]

^<<v58-2-2,2>>^ Pois se a palavra falada pelos anjos permaneceu firme, e toda transgressão e desobediência recebeu justa retribuição,

[[v58-2-3]]

^<<v58-2-3,3>>^ como escaparemos nós, se descuidarmos de tão grande salvação? A qual, tendo sido anunciada inicialmente pelo Senhor, foi-nos depois confirmada pelos que a ouviram:

[[v58-2-4]]

^<<v58-2-4,4>>^ testificando Deus juntamente com eles, por sinais e prodígios, e por múltiplos milagres e dons do Espírito Santo, distribuídos segundo a sua vontade.

[[v58-2-5]]

^<<v58-2-5,5>>^ Porque não foi aos anjos que Deus sujeitou o mundo vindouro, de que falamos.

[[v58-2-6]]

^<<v58-2-6,6>>^ Mas em certo lugar testificou alguém dizendo: Que é o homem, para que te lembres dele? ou o filho do homem, para que o visites?

[[v58-2-7]]

^<<v58-2-7,7>>^ Fizeste-o um pouco menor que os anjos, de glória e de honra o coroaste,

[[v58-2-8]]

^<<v58-2-8,8>>^ todas as coisas lhe sujeitaste debaixo dos pés. Ora, visto que lhe sujeitou todas as coisas, nada deixou que não lhe fosse sujeito. Mas agora ainda não vemos todas as coisas sujeitas a ele;

[[v58-2-9]]

^<<v58-2-9,9>>^ vemos, porém, aquele que foi feito um pouco menor que os anjos, Jesus, coroado de glória e honra, por causa da paixão da morte, para que, pela graça de Deus, provasse a morte por todos.

[[v58-2-10]]

^<<v58-2-10,10>>^ Porque convinha que aquele, para quem são todas as coisas, e por meio de quem tudo existe, em trazendo muitos filhos à glória, aperfeiçoasse pelos sofrimentos o autor da salvação deles.

[[v58-2-11]]

^<<v58-2-11,11>>^ Pois tanto o que santifica como os que são santificados, vêm todos de um só; por esta causa ele não se envergonha de lhes chamar irmãos,

[[v58-2-12]]

^<<v58-2-12,12>>^ dizendo: Anunciarei o teu nome a meus irmãos, cantar-te-ei louvores no meio da congregação.

[[v58-2-13]]

^<<v58-2-13,13>>^ E outra vez: Porei nele a minha confiança. E ainda: Eis-me aqui, e os filhos que Deus me deu.

[[v58-2-14]]

^<<v58-2-14,14>>^ Portanto, visto como os filhos são participantes comuns de carne e sangue, também ele semelhantemente participou das mesmas coisas, para que pela morte derrotasse aquele que tinha o poder da morte, isto é, o Diabo;

[[v58-2-15]]

^<<v58-2-15,15>>^ e livrasse todos aqueles que, com medo da morte, estavam por toda a vida sujeitos à escravidão.

[[v58-2-16]]

^<<v58-2-16,16>>^ Pois, na verdade, não presta auxílio aos anjos, mas sim à descendência de Abraão.

[[v58-2-17]]

^<<v58-2-17,17>>^ Pelo que convinha que em tudo fosse feito semelhante a seus irmãos, para se tornar um sumo sacerdote misericordioso e fiel nas coisas concernentes a Deus, a fim de fazer propiciação pelos pecados do povo.

[[v58-2-18]]

^<<v58-2-18,18>>^ Porque naquilo que ele mesmo, sendo tentado, padeceu, pode socorrer aos que são tentados.

'''

xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[Próximo Capítulo &#62;]