include::./index.adoc[]

[[v58-8-0]]
=== Hebreus, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v58-8-1]]

^<<v58-8-1,1>>^ Ora, do que estamos dizendo, o ponto principal é este: Temos um sumo sacerdote tal, que se assentou nos céus à direita do trono da Majestade,

[[v58-8-2]]

^<<v58-8-2,2>>^ ministro do santuário, e do verdadeiro tabernáculo, que o Senhor fundou, e não o homem.

[[v58-8-3]]

^<<v58-8-3,3>>^ Porque todo sumo sacerdote é constituído para oferecer dons e sacrifícios; pelo que era necessário que esse sumo sacerdote também tivesse alguma coisa que oferecer.

[[v58-8-4]]

^<<v58-8-4,4>>^ Ora, se ele estivesse na terra, nem seria sacerdote, havendo já os que oferecem dons segundo a lei,

[[v58-8-5]]

^<<v58-8-5,5>>^ os quais servem àquilo que é figura e sombra das coisas celestiais, como Moisés foi divinamente avisado, quando estava para construir o tabernáculo; porque lhe foi dito: Olha, faze conforme o modelo que no monte se te mostrou.

[[v58-8-6]]

^<<v58-8-6,6>>^ Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador de um melhor pacto, o qual está firmado sobre melhores promessas.

[[v58-8-7]]

^<<v58-8-7,7>>^ Pois, se aquele primeiro fora sem defeito, nunca se teria buscado lugar para o segundo.

[[v58-8-8]]

^<<v58-8-8,8>>^ Porque repreendendo-os, diz: Eis que virão dias, diz o Senhor, em que estabelecerei com a casa de Israel e com a casa de Judá um novo pacto.

[[v58-8-9]]

^<<v58-8-9,9>>^ Não segundo o pacto que fiz com seus pais no dia em que os tomei pela mão, para os tirar da terra do Egito; pois não permaneceram naquele meu pacto, e eu para eles não atentei, diz o Senhor.

[[v58-8-10]]

^<<v58-8-10,10>>^ Ora, este é o pacto que farei com a casa de Israel, depois daqueles dias, diz o Senhor; porei as minhas leis no seu entendimento, e em seu coração as escreverei; eu serei o seu Deus, e eles serão o meu povo;

[[v58-8-11]]

^<<v58-8-11,11>>^ e não ensinará cada um ao seu concidadão, nem cada um ao seu irmão, dizendo: Conhece ao Senhor; porque todos me conhecerão, desde o menor deles até o maior.

[[v58-8-12]]

^<<v58-8-12,12>>^ Porque serei misericordioso para com suas iniquidades, e de seus pecados não me lembrarei mais.

[[v58-8-13]]

^<<v58-8-13,13>>^ Dizendo: Novo pacto, ele tornou antiquado o primeiro. E o que se torna antiquado e envelhece, perto está de desaparecer.

'''

xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[Próximo Capítulo &#62;]