include::./index.adoc[]

[[v63-1-0]]
=== 2 João, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v63-1-1]]

^<<v63-1-1,1>>^ O ancião à senhora eleita, e a seus filhos, aos quais eu amo em verdade, e não somente eu, mas também todos os que conhecem a verdade,

[[v63-1-2]]

^<<v63-1-2,2>>^ por causa da verdade que permanece em nós, e para sempre estará conosco:

[[v63-1-3]]

^<<v63-1-3,3>>^ Graça, misericórdia, paz, da parte de Deus Pai e da parte de Jesus Cristo, o Filho do Pai, serão conosco em verdade e amor.

[[v63-1-4]]

^<<v63-1-4,4>>^ Muito me alegro por ter achado alguns de teus filhos andando na verdade, assim como recebemos mandamento do Pai.

[[v63-1-5]]

^<<v63-1-5,5>>^ E agora, senhora, rogo-te, não como te escrevendo um novo mandamento, mas aquele mesmo que desde o princípio tivemos: que nos amemos uns aos outros.

[[v63-1-6]]

^<<v63-1-6,6>>^ E o amor é este: que andemos segundo os seus mandamentos. Este é o mandamento, como já desde o princípio ouvistes, para que nele andeis.

[[v63-1-7]]

^<<v63-1-7,7>>^ Porque já muitos enganadores saíram pelo mundo, os quais não confessam que Jesus Cristo veio em carne. Tal é o enganador e o anticristo.

[[v63-1-8]]

^<<v63-1-8,8>>^ Olhai por vós mesmos, para que não percais o fruto do nosso trabalho, antes recebeis plena recompensa.

[[v63-1-9]]

^<<v63-1-9,9>>^ Todo aquele que vai além do ensino de Cristo e não permanece nele, não tem a Deus; quem permanece neste ensino, esse tem tanto ao Pai como ao Filho.

[[v63-1-10]]

^<<v63-1-10,10>>^ Se alguém vem ter convosco, e não traz este ensino, não o recebais em casa, nem tampouco o saudeis.

[[v63-1-11]]

^<<v63-1-11,11>>^ Porque quem o saúda participa de suas más obras.

[[v63-1-12]]

^<<v63-1-12,12>>^ Embora tenha eu muitas coisas para vos escrever, não o quis fazer com papel e tinta; mas espero visitar-vos e falar face a face, para que o nosso gozo seja completo.

[[v63-1-13]]

^<<v63-1-13,13>>^ Saúdam-te os filhos de tua irmã, a eleita.

'''

xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[Próximo Capítulo &#62;]