include::./index.adoc[]

[[v53-1-0]]
=== 2 Tessalonicenses, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v53-1-1]]

^<<v53-1-1,1>>^ Paulo, Silvano e Timóteo à igreja dos tessalonicenses, em Deus nosso Pai e no Senhor Jesus Cristo:

[[v53-1-2]]

^<<v53-1-2,2>>^ Graças a vós, e paz da parte de Deus Pai e do Senhor Jesus Cristo.

[[v53-1-3]]

^<<v53-1-3,3>>^ Sempre devemos, irmãos, dar graças a Deus por vós, como é justo, porque a vossa fé cresce muitíssimo e o amor de cada um de vós transborda de uns para com os outros.

[[v53-1-4]]

^<<v53-1-4,4>>^ De maneira que nós mesmos nos gloriamos de vós nas igrejas de Deus por causa da vossa constância e fé em todas as perseguições e aflições que suportais;

[[v53-1-5]]

^<<v53-1-5,5>>^ o que é prova clara do justo juízo de Deus, para que sejais havidos por dignos do reino de Deus, pelo qual também padeceis;

[[v53-1-6]]

^<<v53-1-6,6>>^ se de fato é justo diante de Deus que ele dê em paga tribulação aos que vos atribulam,

[[v53-1-7]]

^<<v53-1-7,7>>^ e a vós, que sois atribulados, alívio juntamente conosco, quando do céu se manifestar o Senhor Jesus com os anjos do seu poder em chama de fogo,

[[v53-1-8]]

^<<v53-1-8,8>>^ e tomar vingança dos que não conhecem a Deus e dos que não conhecem a Deus e dos que não obedecem ao evangelho de nosso Senhor Jesus;

[[v53-1-9]]

^<<v53-1-9,9>>^ os quais sofrerão, como castigo, a perdição eterna, banidos da face do senhor e da glória do seu poder,

[[v53-1-10]]

^<<v53-1-10,10>>^ quando naquele dia ele vier para ser glorificado nos seus santos e para ser admirado em todos os que tiverem crido &#123;porquanto o nosso testemunho foi crido entre vós&#125;.

[[v53-1-11]]

^<<v53-1-11,11>>^ Pelo que também rogamos sempre por vós, para que o nosso Deus vos faça dignos da sua vocação, e cumpra com poder todo desejo de bondade e toda obra de fé.

[[v53-1-12]]

^<<v53-1-12,12>>^ para que o nome de nosso Senhor Jesus seja glorificado em vós, e vós nele, segundo a graça de nosso Deus e do Senhor Jesus Cristo.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[Próximo Capítulo &#62;]