include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v53-3-1]]

^<<v53-3-1,1>>^ Finalmente, irmãos, orai por nós, para que a palavra do Senhor se propague e seja glorificada. como também o é entre vós,

[[v53-3-2]]

^<<v53-3-2,2>>^ e para que sejamos livres de homens perversos e maus; porque a fé não é de todos.

[[v53-3-3]]

^<<v53-3-3,3>>^ Mas fiel é o Senhor, o qual vos confirmará e guardará do maligno.

[[v53-3-4]]

^<<v53-3-4,4>>^ E, quanto a vós, confiamos no Senhor que não só fazeis, mas fareis o que vos mandamos.

[[v53-3-5]]

^<<v53-3-5,5>>^ Ora, o Senhor encaminhe os vossos corações no amor de Deus e na constância de Cristo.

[[v53-3-6]]

^<<v53-3-6,6>>^ mandamo-vos, irmãos, em nome do Senhor Jesus Cristo, que vos aparteis de todo irmão que anda desordenadamente, e não segundo a tradição que de nós recebestes.

[[v53-3-7]]

^<<v53-3-7,7>>^ Porque vós mesmos sabeis como deveis imitar-nos, pois que não nos portamos desordenadamente entre vós,

[[v53-3-8]]

^<<v53-3-8,8>>^ nem comemos de graça o pão de ninguém, antes com labor e fadiga trabalhávamos noite e dia para não sermos pesados a nenhum de vós.

[[v53-3-9]]

^<<v53-3-9,9>>^ Não porque não tivéssemos direito, mas para vos dar nós mesmos exemplo, para nos imitardes.

[[v53-3-10]]

^<<v53-3-10,10>>^ Porque, quando ainda estávamos convosco, isto vos mandamos: se alguém não quer trabalhar, também não coma.

[[v53-3-11]]

^<<v53-3-11,11>>^ Porquanto ouvimos que alguns entre vós andam desordenadamente, não trabalhando, antes intrometendo-se na vida alheia;

[[v53-3-12]]

^<<v53-3-12,12>>^ a esses tais, porém, ordenamos e exortamos por nosso Senhor Jesus Cristo que, trabalhando sossegadamente, comam o seu próprio pão.

[[v53-3-13]]

^<<v53-3-13,13>>^ Vós, porém, irmãos, não vos canseis de fazer o bem.

[[v53-3-14]]

^<<v53-3-14,14>>^ Mas, se alguém não obedecer à nossa palavra por esta carta, notai-o e não tenhais relações com ele, para que se envergonhe;

[[v53-3-15]]

^<<v53-3-15,15>>^ todavia não o considereis como inimigo, mas admoestai-o como irmão.

[[v53-3-16]]

^<<v53-3-16,16>>^ Ora, o próprio Senhor da paz vos dê paz sempre e de toda maneira. O Senhor seja com todos vós.

[[v53-3-17]]

^<<v53-3-17,17>>^ Esta saudação é de próprio punho, de Paulo, o que é o sinal em cada epístola; assim escrevo.

[[v53-3-18]]

^<<v53-3-18,18>>^ A graça de nosso Senhor Jesus Cristo seja com todos vós.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]