include::./index.adoc[]

[[v19-17-0]]
=== Salmos, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-17-1]]

^<<v19-17-1,1>>^ Ouve, Senhor, a justa causa; atende ao meu clamor; dá ouvidos à minha oração, que não procede de lábios enganosos.

[[v19-17-2]]

^<<v19-17-2,2>>^ Venha de ti a minha sentença; atendam os teus olhos à eqüidade.

[[v19-17-3]]

^<<v19-17-3,3>>^ Provas-me o coração, visitas-me de noite; examinas-me e não achas iniqüidade; a minha boca não transgride.

[[v19-17-4]]

^<<v19-17-4,4>>^ Quanto às obras dos homens, pela palavra dos teus lábios eu me tenho guardado dos caminhos do homem violento.

[[v19-17-5]]

^<<v19-17-5,5>>^ Os meus passos apegaram-se às tuas veredas, não resvalaram os meus pés.

[[v19-17-6]]

^<<v19-17-6,6>>^ A ti, ó Deus, eu clamo, pois tu me ouvirás; inclina para mim os teus ouvidos, e ouve as minhas palavras.

[[v19-17-7]]

^<<v19-17-7,7>>^ Faze maravilhosas as tuas beneficências, ó Salvador dos que à tua destra se refugiam daqueles que se levantam contra eles.

[[v19-17-8]]

^<<v19-17-8,8>>^ Guarda-me como à menina do olho; esconde-me, à sombra das tuas asas,

[[v19-17-9]]

^<<v19-17-9,9>>^ dos ímpios que me despojam, dos meus inimigos mortais que me cercam.

[[v19-17-10]]

^<<v19-17-10,10>>^ Eles fecham o seu coração; com a boca falam soberbamente.

[[v19-17-11]]

^<<v19-17-11,11>>^ Andam agora rodeando os meus passos; fixam em mim os seus olhos para me derrubarem por terra.

[[v19-17-12]]

^<<v19-17-12,12>>^ Parecem-se com o leão que deseja arrebatar a sua presa, e com o leãozinho que espreita em esconderijos.

[[v19-17-13]]

^<<v19-17-13,13>>^ Levanta-te, Senhor, detém-nos, derruba-os; livra-me dos ímpios, pela tua espada,

[[v19-17-14]]

^<<v19-17-14,14>>^ dos homens, pela tua mão, Senhor, dos homens do mundo, cujo quinhão está nesta vida. Enche-lhes o ventre da tua ira entesourada. Fartem-se dela os seus filhos, e dêem ainda os sobejos por herança aos seus pequeninos.

[[v19-17-15]]

^<<v19-17-15,15>>^ Quanto a mim, em retidão contemplarei a tua face; eu me satisfarei com a tua semelhança quando acordar.

'''

xref:019-salmos/019-salmos-016.adoc#v19-16-0[&#60; Capítulo Anterior] | <<v19-17-0,Topo>> | xref:019-salmos/019-salmos-018.adoc#v19-18-0[Próximo Capítulo &#62;]