include::./index.adoc[]

[[v19-39-0]]
=== Salmos, 39
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-39-1]]

^<<v19-39-1,1>>^ Disse eu: Guardarei os meus caminhos para não pecar com a minha língua; guardarei a minha boca com uma mordaça, enquanto o ímpio estiver diante de mim.

[[v19-39-2]]

^<<v19-39-2,2>>^ Com silêncio fiquei qual um mundo; calava-me mesmo acerca do bem; mas a minha dor se agravou.

[[v19-39-3]]

^<<v19-39-3,3>>^ Acendeu-se dentro de mim o meu coração; enquanto eu meditava acendeu-se o fogo; então com a minha língua, dizendo;

[[v19-39-4]]

^<<v19-39-4,4>>^ Faze-me conhecer, ó Senhor, o meu fim, e qual a medida dos meus dias, para que eu saiba quão frágil sou.

[[v19-39-5]]

^<<v19-39-5,5>>^ Eis que mediste os meus dias a palmos; o tempo da minha vida é como que nada diante de ti. Na verdade, todo homem, por mais firme que esteja, é totalmente vaidade.

[[v19-39-6]]

^<<v19-39-6,6>>^ Na verdade, todo homem anda qual uma sombra; na verdade, em vão se inquieta, amontoa riquezas, e não sabe quem as levará.

[[v19-39-7]]

^<<v19-39-7,7>>^ Agora, pois, Senhor, que espero eu? a minha esperança está em ti.

[[v19-39-8]]

^<<v19-39-8,8>>^ Livra-me de todas as minhas transgressões; não me faças o opróbrio do insensato.

[[v19-39-9]]

^<<v19-39-9,9>>^ Emudecido estou, não abro a minha boca; pois tu és que agiste,

[[v19-39-10]]

^<<v19-39-10,10>>^ Tira de sobre mim o teu flagelo; estou desfalecido pelo golpe da tua mão.

[[v19-39-11]]

^<<v19-39-11,11>>^ Quando com repreensões castigas o homem por causa da iniquidade, destróis, como traça, o que ele tem de precioso; na verdade todo homem é vaidade.

[[v19-39-12]]

^<<v19-39-12,12>>^ Ouve, Senhor, a minha oração, e inclina os teus ouvidos ao meu clamor; não te cales perante as minhas lágrimas, porque sou para contigo como um estranho, um peregrino como todos os meus pais.

[[v19-39-13]]

^<<v19-39-13,13>>^ Desvia de mim o teu olhar, para que eu tome alento, antes que me vá e não exista mais.

'''

xref:019-salmos/019-salmos-038.adoc#v19-38-0[&#60; Capítulo Anterior] | <<v19-39-0,Topo>> | xref:019-salmos/019-salmos-040.adoc#v19-40-0[Próximo Capítulo &#62;]