include::./index.adoc[]

[[v19-138-0]]
=== Salmos, 138
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-138-1]]

^<<v19-138-1,1>>^ Graças te dou de todo o meu coração; diante dos deuses a ti canto louvores.

[[v19-138-2]]

^<<v19-138-2,2>>^ Inclino-me para o teu santo templo, e louvo o teu nome pela tua benignidade, e pela tua fidelidade; pois engrandeceste acima de tudo o teu nome e a tua palavra.

[[v19-138-3]]

^<<v19-138-3,3>>^ No dia em que eu clamei, atendeste-me; alentaste-me, fortalecendo a minha alma.

[[v19-138-4]]

^<<v19-138-4,4>>^ Todos os reis da terra de louvarão, ó Senhor, quando ouvirem as palavras da tua boca;

[[v19-138-5]]

^<<v19-138-5,5>>^ e cantarão os caminhos do Senhor, pois grande é a glória do Senhor.

[[v19-138-6]]

^<<v19-138-6,6>>^ Ainda que o Senhor é excelso, contudo atenta para o humilde; mas ao soberbo, conhece-o de longe.

[[v19-138-7]]

^<<v19-138-7,7>>^ Embora eu ande no meio da angústia, tu me revivificas; contra a ira dos meus inimigos estendes a tua mão, e a tua destra me salva.

[[v19-138-8]]

^<<v19-138-8,8>>^ O Senhor aperfeiçoará o que me diz respeito. A tua benignidade, ó Senhor, dura para sempre; não abandones as obras das tuas mãos.

'''

xref:019-salmos/019-salmos-137.adoc#v19-137-0[&#60; Capítulo Anterior] | <<v19-138-0,Topo>> | xref:019-salmos/019-salmos-139.adoc#v19-139-0[Próximo Capítulo &#62;]