include::./index.adoc[]

[[v19-113-0]]
=== Salmos, 113
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-113-1]]

^<<v19-113-1,1>>^ Louvai ao Senhor. Louvai, servos do Senhor, louvai o nome do Senhor.

[[v19-113-2]]

^<<v19-113-2,2>>^ Bendito seja o nome do Senhor, desde agora e para sempre.

[[v19-113-3]]

^<<v19-113-3,3>>^ Desde o nascimento do sol até o seu ocaso, há de ser louvado o nome do Senhor.

[[v19-113-4]]

^<<v19-113-4,4>>^ Exaltado está o Senhor acima de todas as nações, e a sua glória acima dos céus.

[[v19-113-5]]

^<<v19-113-5,5>>^ Quem é semelhante ao Senhor nosso Deus, que tem o seu assento nas alturas,

[[v19-113-6]]

^<<v19-113-6,6>>^ que se inclina para ver o que está no céu e na terra?

[[v19-113-7]]

^<<v19-113-7,7>>^ Ele levanta do pó o pobre, e do monturo ergue o necessitado,

[[v19-113-8]]

^<<v19-113-8,8>>^ para o fazer sentar com os príncipes, sim, com os príncipes do seu povo.

[[v19-113-9]]

^<<v19-113-9,9>>^ Ele faz com que a mulher estéril habite em família, e seja alegre mãe de filhos. Louvai ao Senhor.

'''

xref:019-salmos/019-salmos-112.adoc#v19-112-0[&#60; Capítulo Anterior] | <<v19-113-0,Topo>> | xref:019-salmos/019-salmos-114.adoc#v19-114-0[Próximo Capítulo &#62;]