include::./index.adoc[]

[[v19-58-0]]
=== Salmos, 58
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-58-1]]

^<<v19-58-1,1>>^ Falais deveras o que é reto, vós os poderosos? Julgais retamente, ó filhos dos homens?

[[v19-58-2]]

^<<v19-58-2,2>>^ Não, antes no coração forjais iniqüidade; sobre a terra fazeis pesar a violência das vossas mãos.

[[v19-58-3]]

^<<v19-58-3,3>>^ Alienam-se os ímpios desde a madre; andam errados desde que nasceram, proferindo mentiras.

[[v19-58-4]]

^<<v19-58-4,4>>^ Têm veneno semelhante ao veneno da serpente; são como a víbora surda, que tapa os seus ouvidos,

[[v19-58-5]]

^<<v19-58-5,5>>^ de sorte que não ouve a voz dos encantadores, nem mesmo do encantador perito em encantamento.

[[v19-58-6]]

^<<v19-58-6,6>>^ Ó Deus, quebra-lhes os dentes na sua boca; arranca, Senhor, os caninos aos filhos dos leões.

[[v19-58-7]]

^<<v19-58-7,7>>^ Sumam-se como águas que se escoam; sejam pisados e murcham como a relva macia.

[[v19-58-8]]

^<<v19-58-8,8>>^ Sejam como a lesma que se derrete e se vai; como o aborto de mulher, que nunca viu o sol.

[[v19-58-9]]

^<<v19-58-9,9>>^ Que ele arrebate os espinheiros antes que cheguem a aquecer as vossas panelas, assim os verdes, como os que estão ardendo.

[[v19-58-10]]

^<<v19-58-10,10>>^ O justo se alegrará quando vir a vingança; lavará os seus pés no sangue do ímpio.

[[v19-58-11]]

^<<v19-58-11,11>>^ Então dirão os homens: Deveras há uma recompensa para o justo; deveras há um Deus que julga na terra.

'''

xref:019-salmos/019-salmos-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-salmos/019-salmos-059.adoc#v19-59-0[Próximo Capítulo &#62;]