include::./index.adoc[]

[[v19-66-0]]
=== Salmos, 66
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-66-1]]

^<<v19-66-1,1>>^ Louvai a Deus com brados de júbilo, todas as terras.

[[v19-66-2]]

^<<v19-66-2,2>>^ Cantai a glória do seu nome, dai glória em seu louvor.

[[v19-66-3]]

^<<v19-66-3,3>>^ Dizei a Deus: Quão tremendas são as tuas obras! pela grandeza do teu poder te lisonjeiam os teus inimigos.

[[v19-66-4]]

^<<v19-66-4,4>>^ Toda a terra te adorará e te cantará louvores; eles cantarão o teu nome.

[[v19-66-5]]

^<<v19-66-5,5>>^ Vinde, e vede as obras de Deus; ele é tremendo nos seus feitos para com os filhos dos homens.

[[v19-66-6]]

^<<v19-66-6,6>>^ Converteu o mar em terra seca; passaram o rio a pé; ali nos alegramos nele.

[[v19-66-7]]

^<<v19-66-7,7>>^ Ele governa eternamente pelo seu poder; os seus olhos estão sobre as nações; não se exaltem os rebeldes.

[[v19-66-8]]

^<<v19-66-8,8>>^ Bendizei, povos, ao nosso Deus, e fazei ouvir a voz do seu louvor;

[[v19-66-9]]

^<<v19-66-9,9>>^ ao que nos conserva em vida, e não consente que resvalem os nossos pés.

[[v19-66-10]]

^<<v19-66-10,10>>^ Pois tu, ó Deus, nos tens provado; tens nos refinado como se refina a prata.

[[v19-66-11]]

^<<v19-66-11,11>>^ Fizeste-nos entrar no laço; pesada carga puseste sobre os nossos lombos.

[[v19-66-12]]

^<<v19-66-12,12>>^ Fizeste com que os homens cavalgassem sobre as nossas cabeças; passamos pelo fogo e pela água, mas nos trouxeste a um lugar de abundância.

[[v19-66-13]]

^<<v19-66-13,13>>^ Entregarei em tua casa com holocaustos; pagar-te-ei os meus votos,

[[v19-66-14]]

^<<v19-66-14,14>>^ votos que os meus lábios pronunciaram e a minha boca prometeu, quando eu estava na angústia.

[[v19-66-15]]

^<<v19-66-15,15>>^ Oferecer-te-ei holocausto de animais nédios, com incenso de carneiros; prepararei novilhos com cabritos.

[[v19-66-16]]

^<<v19-66-16,16>>^ Vinde, e ouvi, todos os que temeis a Deus, e eu contarei o que ele tem feito por mim.

[[v19-66-17]]

^<<v19-66-17,17>>^ A ele clamei com a minha boca, e ele foi exaltado pela minha língua.

[[v19-66-18]]

^<<v19-66-18,18>>^ Se eu tivesse guardado iniqüidade no meu coração, o Senhor não me teria ouvido;

[[v19-66-19]]

^<<v19-66-19,19>>^ mas, na verdade, Deus me ouviu; tem atendido à voz da minha oração.

[[v19-66-20]]

^<<v19-66-20,20>>^ Bendito seja Deus, que não rejeitou a minha oração, nem retirou de mim a sua benignidade.

'''

xref:019-salmos/019-salmos-065.adoc#v19-65-0[&#60; Capítulo Anterior] | <<v19-66-0,Topo>> | xref:019-salmos/019-salmos-067.adoc#v19-67-0[Próximo Capítulo &#62;]