include::./index.adoc[]

[[v19-81-0]]
=== Salmos, 81
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-81-1]]

^<<v19-81-1,1>>^ Cantai alegremente a Deus, nossa fortaleza; erguei alegres vozes ao Deus de Jacó.

[[v19-81-2]]

^<<v19-81-2,2>>^ Entoai um salmo, e fazei soar o adufe, a suave harpa e o saltério.

[[v19-81-3]]

^<<v19-81-3,3>>^ Tocai a trombeta pela lua nova, pela lua cheia, no dia da nossa festa.

[[v19-81-4]]

^<<v19-81-4,4>>^ Pois isso é um estatuto para Israel, e uma ordenança do Deus de Jacó.

[[v19-81-5]]

^<<v19-81-5,5>>^ Ordenou-o por decreto em José, quando saiu contra a terra do Egito. Ouvi uma voz que não conhecia, dizendo:

[[v19-81-6]]

^<<v19-81-6,6>>^ Livrei da carga o seu ombro; as suas mãos ficaram livres dos cestos.

[[v19-81-7]]

^<<v19-81-7,7>>^ Na angústia clamaste e te livrei; respondi-te no lugar oculto dos trovões; provei-te junto às águas de Meribá.

[[v19-81-8]]

^<<v19-81-8,8>>^ Ouve-me, povo meu, e eu te admoestarei; ó Israel, se me escutasses!

[[v19-81-9]]

^<<v19-81-9,9>>^ não haverá em ti deus estranho, nem te prostrarás ante um deus estrangeiro.

[[v19-81-10]]

^<<v19-81-10,10>>^ Eu sou o Senhor teu Deus, que te tirei da terra do Egito; abre bem a tua boca, e eu a encherei.

[[v19-81-11]]

^<<v19-81-11,11>>^ Mas o meu povo não ouviu a minha voz, e Israel não me quis.

[[v19-81-12]]

^<<v19-81-12,12>>^ Pelo que eu os entreguei à obstinação dos seus corações, para que andassem segundo os seus próprios conselhos.

[[v19-81-13]]

^<<v19-81-13,13>>^ Oxalá me escutasse o meu povo! oxalá Israel andasse nos meus caminhos!

[[v19-81-14]]

^<<v19-81-14,14>>^ Em breve eu abateria os seus inimigos, e voltaria a minha mão contra os seus adversários.

[[v19-81-15]]

^<<v19-81-15,15>>^ Os que odeiam ao Senhor o adulariam, e a sorte deles seria eterna.

[[v19-81-16]]

^<<v19-81-16,16>>^ E eu te sustentaria com o trigo mais fino; e com o mel saído da rocha eu te saciaria.

'''

xref:019-salmos/019-salmos-080.adoc#v19-80-0[&#60; Capítulo Anterior] | <<v19-81-0,Topo>> | xref:019-salmos/019-salmos-082.adoc#v19-82-0[Próximo Capítulo &#62;]