include::./index.adoc[]

[[v19-63-0]]
=== Salmos, 63
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-63-1]]

^<<v19-63-1,1>>^ Ó Deus, tu és o meu Deus; ansiosamente te busco. A minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.

[[v19-63-2]]

^<<v19-63-2,2>>^ Assim no santuário te contemplo, para ver o teu poder e a tua glória.

[[v19-63-3]]

^<<v19-63-3,3>>^ Porquanto a tua benignidade é melhor do que a vida, os meus lábios te louvarão.

[[v19-63-4]]

^<<v19-63-4,4>>^ Assim eu te bendirei enquanto viver; em teu nome levantarei as minhas mãos.

[[v19-63-5]]

^<<v19-63-5,5>>^ A minha alma se farta, como de tutano e de gordura; e a minha boca te louva com alegres lábios.

[[v19-63-6]]

^<<v19-63-6,6>>^ quando me lembro de ti no meu leito, e medito em ti nas vigílias da noite,

[[v19-63-7]]

^<<v19-63-7,7>>^ pois tu tens sido o meu auxílio; de júbilo canto à sombra das tuas asas.

[[v19-63-8]]

^<<v19-63-8,8>>^ A minha alma se apega a ti; a tua destra me sustenta.

[[v19-63-9]]

^<<v19-63-9,9>>^ Mas aqueles que procuram a minha vida para a destruírem, irão para as profundezas da terra.

[[v19-63-10]]

^<<v19-63-10,10>>^ Serão entregues ao poder da espada, servidão de pasto aos chacais.

[[v19-63-11]]

^<<v19-63-11,11>>^ Mas o rei se regozijará em Deus; todo o que por ele jura se gloriará, porque será tapada a boca aos que falam a mentira.

'''

xref:019-salmos/019-salmos-062.adoc#v19-62-0[&#60; Capítulo Anterior] | <<v19-63-0,Topo>> | xref:019-salmos/019-salmos-064.adoc#v19-64-0[Próximo Capítulo &#62;]