include::./index.adoc[]

[[v19-8-0]]
=== Salmos, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-8-1]]

^<<v19-8-1,1>>^ Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra, tu que puseste a tua glória dos céus!

[[v19-8-2]]

^<<v19-8-2,2>>^ Da boca das crianças e dos que mamam tu suscitaste força, por causa dos teus adversários para fazeres calar o inimigo e vingador.

[[v19-8-3]]

^<<v19-8-3,3>>^ Quando contemplo os teus céus, obra dos teus dedos, a lua e as estrelas que estabeleceste,

[[v19-8-4]]

^<<v19-8-4,4>>^ que é o homem, para que te lembres dele? e o filho do homem, para que o visites?

[[v19-8-5]]

^<<v19-8-5,5>>^ Contudo, pouco abaixo de Deus o fizeste; de glória e de honra o coroaste.

[[v19-8-6]]

^<<v19-8-6,6>>^ Deste-lhe domínio sobre as obras das tuas mãos; tudo puseste debaixo de seus pés:

[[v19-8-7]]

^<<v19-8-7,7>>^ todas as ovelhas e bois, assim como os animais do campo,

[[v19-8-8]]

^<<v19-8-8,8>>^ as aves do céu, e os peixes do mar, tudo o que passa pelas veredas dos mares.

[[v19-8-9]]

^<<v19-8-9,9>>^ Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra!

'''

xref:019-salmos/019-salmos-007.adoc#v19-7-0[&#60; Capítulo Anterior] | <<v19-8-0,Topo>> | xref:019-salmos/019-salmos-009.adoc#v19-9-0[Próximo Capítulo &#62;]