include::./index.adoc[]

[[v19-48-0]]
=== Salmos, 48
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-48-1]]

^<<v19-48-1,1>>^ Grande é o Senhor e mui digno de ser louvado, na cidade do nosso Deus, no seu monte santo.

[[v19-48-2]]

^<<v19-48-2,2>>^ De bela e alta situação, alegria de toda terra é o monte Sião aos lados do norte, a cidade do grande Rei.

[[v19-48-3]]

^<<v19-48-3,3>>^ Nos palácios dela Deus se fez conhecer como alto refúgio.

[[v19-48-4]]

^<<v19-48-4,4>>^ Pois eis que os reis conspiraram; juntos vieram chegando.

[[v19-48-5]]

^<<v19-48-5,5>>^ Viram-na, e então ficaram maravilhados; ficaram assombrados e se apressaram em fugir.

[[v19-48-6]]

^<<v19-48-6,6>>^ Aí se apoderou deles o tremor, sentiram dores como as de uma parturiente.

[[v19-48-7]]

^<<v19-48-7,7>>^ Com um vento oriental quebraste as naus de Társis.

[[v19-48-8]]

^<<v19-48-8,8>>^ Como temos ouvido, assim vimos na cidade do Senhor dos exércitos, na cidade do nosso Deus; Deus a estabelece para sempre.

[[v19-48-9]]

^<<v19-48-9,9>>^ Temos meditado, ó Deus, na tua benignidade no meio do teu templo.

[[v19-48-10]]

^<<v19-48-10,10>>^ Como é o teu nome, ó Deus, assim é o teu louvor até os confins da terra; de retidão está cheia a tua destra.

[[v19-48-11]]

^<<v19-48-11,11>>^ Alegre-se o monte Sião, regozijem-se as filhas de Judá, por causa dos teus juízos.

[[v19-48-12]]

^<<v19-48-12,12>>^ Dai voltas a Sião, ide ao redor dela; contai as suas torres.

[[v19-48-13]]

^<<v19-48-13,13>>^ Notai bem os seus antemuros, percorrei os seus palácios, para que tudo narreis à geração seguinte.

[[v19-48-14]]

^<<v19-48-14,14>>^ Porque este Deus é o nosso Deus para todo o sempre; ele será nosso guia até a morte.

'''

xref:019-salmos/019-salmos-047.adoc#v19-47-0[&#60; Capítulo Anterior] | <<v19-48-0,Topo>> | xref:019-salmos/019-salmos-049.adoc#v19-49-0[Próximo Capítulo &#62;]