include::./index.adoc[]

[[v19-32-0]]
=== Salmos, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-32-1]]

^<<v19-32-1,1>>^ Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.

[[v19-32-2]]

^<<v19-32-2,2>>^ Bem-aventurado o homem a quem o Senhor não atribui a iniqüidade, e em cujo espírito não há dolo.

[[v19-32-3]]

^<<v19-32-3,3>>^ Enquanto guardei silêncio, consumiram-se os meus ossos pelo meu bramido durante o dia todo.

[[v19-32-4]]

^<<v19-32-4,4>>^ Porque de dia e de noite a tua mão pesava sobre mim; o meu humor se tornou em sequidão de estio.

[[v19-32-5]]

^<<v19-32-5,5>>^ Confessei-te o meu pecado, e a minha iniqüidade não encobri. Disse eu: Confessarei ao Senhor as minhas transgressões; e tu perdoaste a culpa do meu pecado.

[[v19-32-6]]

^<<v19-32-6,6>>^ Pelo que todo aquele é piedoso ore a ti, a tempo de te poder achar; no trasbordar de muitas águas, estas e ele não chegarão.

[[v19-32-7]]

^<<v19-32-7,7>>^ Tu és o meu esconderijo; preservas-me da angústia; de alegres cânticos de livramento me cercas.

[[v19-32-8]]

^<<v19-32-8,8>>^ Instruir-te-ei, e ensinar-te-ei o caminho que deves seguir; aconselhar-te-ei, tendo-te sob a minha vista.

[[v19-32-9]]

^<<v19-32-9,9>>^ Não sejais como o cavalo, nem como a mula, que não têm entendimento, cuja boca precisa de cabresto e freio; de outra forma não se sujeitarão.

[[v19-32-10]]

^<<v19-32-10,10>>^ O ímpio tem muitas dores, mas aquele que confia no Senhor, a misericórdia o cerca.

[[v19-32-11]]

^<<v19-32-11,11>>^ Alegrai-vos no Senhor, e regozijai-vos, vós justos; e cantai de júbilo, todos vós que sois retos de coração.

'''

xref:019-salmos/019-salmos-031.adoc#v19-31-0[&#60; Capítulo Anterior] | <<v19-32-0,Topo>> | xref:019-salmos/019-salmos-033.adoc#v19-33-0[Próximo Capítulo &#62;]