include::./index.adoc[]

[[v19-4-0]]
=== Salmos, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-4-1]]

^<<v19-4-1,1>>^ Responde-me quando eu clamar, ó Deus da minha justiça! Na angústia me deste largueza; tem misericórdia de mim e ouve a minha oração.

[[v19-4-2]]

^<<v19-4-2,2>>^ Filhos dos homens, até quando convertereis a minha glória em infâmia? Até quando amareis a vaidade e buscareis a mentira?

[[v19-4-3]]

^<<v19-4-3,3>>^ Sabei que o Senhor separou para si aquele que é piedoso; o Senhor me ouve quando eu clamo a ele.

[[v19-4-4]]

^<<v19-4-4,4>>^ Irai-vos e não pequeis; consultai com o vosso coração em vosso leito, e calai-vos.

[[v19-4-5]]

^<<v19-4-5,5>>^ Oferecei sacrifícios de justiça, e confiai no Senhor.

[[v19-4-6]]

^<<v19-4-6,6>>^ Muitos dizem: Quem nos mostrará o bem? Levanta, Senhor, sobre nós a luz do teu rosto.

[[v19-4-7]]

^<<v19-4-7,7>>^ Puseste no meu coração mais alegria do que a deles no tempo em que se lhes multiplicam o trigo e o vinho.

[[v19-4-8]]

^<<v19-4-8,8>>^ Em paz me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.

'''

xref:019-salmos/019-salmos-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-salmos/019-salmos-005.adoc#v19-5-0[Próximo Capítulo &#62;]