include::./index.adoc[]

[[v19-3-0]]
=== Salmos, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-3-1]]

^<<v19-3-1,1>>^ Senhor, como se têm multiplicado os meus adversários! Muitos se levantam contra mim.

[[v19-3-2]]

^<<v19-3-2,2>>^ Muitos são os que dizem de mim: Não há socorro para ele em Deus.

[[v19-3-3]]

^<<v19-3-3,3>>^ Mas tu, Senhor, és um escudo ao redor de mim, a minha glória, e aquele que exulta a minha cabeça.

[[v19-3-4]]

^<<v19-3-4,4>>^ Com a minha voz clamo ao Senhor, e ele do seu santo monte me responde.

[[v19-3-5]]

^<<v19-3-5,5>>^ Eu me deito e durmo; acordo, pois o Senhor me sustenta.

[[v19-3-6]]

^<<v19-3-6,6>>^ Não tenho medo dos dez milhares de pessoas que se puseram contra mim ao meu redor.

[[v19-3-7]]

^<<v19-3-7,7>>^ Levanta-te, Senhor! salva-me, Deus meu! pois tu feres no queixo todos os meus inimigos; quebras os dentes aos ímpios.

[[v19-3-8]]

^<<v19-3-8,8>>^ A salvação vem do Senhor; sobre o teu povo seja a tua bênção.

'''

xref:019-salmos/019-salmos-002.adoc#v19-2-0[&#60; Capítulo Anterior] | <<v19-3-0,Topo>> | xref:019-salmos/019-salmos-004.adoc#v19-4-0[Próximo Capítulo &#62;]