include::./index.adoc[]

[[v19-16-0]]
=== Salmos, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-16-1]]

^<<v19-16-1,1>>^ Guarda-me, ó Deus, porque em ti me refugio.

[[v19-16-2]]

^<<v19-16-2,2>>^ Digo ao Senhor: Tu és o meu Senhor; além de ti não tenho outro bem.

[[v19-16-3]]

^<<v19-16-3,3>>^ Quanto aos santos que estão na terra, eles são os ilustres nos quais está todo o meu prazer.

[[v19-16-4]]

^<<v19-16-4,4>>^ Aqueles que escolhem a outros deuses terão as suas dores multiplicadas; eu não oferecerei as suas libações de sangue, nem tomarei os seus nomes nos meus lábios.

[[v19-16-5]]

^<<v19-16-5,5>>^ Tu, Senhor, és a porção da minha herança e do meu cálice; tu és o sustentáculo do meu quinhão.

[[v19-16-6]]

^<<v19-16-6,6>>^ As sortes me caíram em lugares deliciosos; sim, coube-me uma formosa herança.

[[v19-16-7]]

^<<v19-16-7,7>>^ Bendigo ao Senhor que me aconselha; até os meus rins me ensinam de noite.

[[v19-16-8]]

^<<v19-16-8,8>>^ Tenho posto o Senhor continuamente diante de mim; porquanto ele está à minha mão direita, não serei abalado.

[[v19-16-9]]

^<<v19-16-9,9>>^ Porquanto está alegre o meu coração e se regozija a minha alma; também a minha carne habitará em segurança.

[[v19-16-10]]

^<<v19-16-10,10>>^ Pois não deixarás a minha alma no Seol, nem permitirás que o teu Santo veja corrupção.

[[v19-16-11]]

^<<v19-16-11,11>>^ Tu me farás conhecer a vereda da vida; na tua presença há plenitude de alegria; à tua mão direita há delícias perpetuamente.

'''

xref:019-salmos/019-salmos-015.adoc#v19-15-0[&#60; Capítulo Anterior] | <<v19-16-0,Topo>> | xref:019-salmos/019-salmos-017.adoc#v19-17-0[Próximo Capítulo &#62;]