include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-50-1]]

^<<v19-50-1,1>>^ O Poderoso, o Senhor Deus, fala e convoca a terra desde o nascer do sol até o seu ocaso.

[[v19-50-2]]

^<<v19-50-2,2>>^ Desde Sião, a perfeição da formosura. Deus resplandece.

[[v19-50-3]]

^<<v19-50-3,3>>^ O nosso Deus vem, e não guarda silêncio; diante dele há um fogo devorador, e grande tormenta ao seu redor.

[[v19-50-4]]

^<<v19-50-4,4>>^ Ele intima os altos céus e a terra, para o julgamento do seu povo:

[[v19-50-5]]

^<<v19-50-5,5>>^ Congregai os meus santos, aqueles que fizeram comigo um pacto por meio de sacrifícios.

[[v19-50-6]]

^<<v19-50-6,6>>^ Os céus proclamam a justiça dele, pois Deus mesmo é Juiz.

[[v19-50-7]]

^<<v19-50-7,7>>^ Ouve, povo meu, e eu falarei; ouve, ó Israel, e eu te protestarei: Eu sou Deus, o teu Deus.

[[v19-50-8]]

^<<v19-50-8,8>>^ Não te repreendo pelos teus sacrifícios, pois os teus holocaustos estão de contínuo perante mim.

[[v19-50-9]]

^<<v19-50-9,9>>^ Da tua casa não aceitarei novilho, nem bodes dos teus currais.

[[v19-50-10]]

^<<v19-50-10,10>>^ Porque meu é todo animal da selva, e o gado sobre milhares de outeiros.

[[v19-50-11]]

^<<v19-50-11,11>>^ Conheço todas as aves dos montes, e tudo o que se move no campo é meu.

[[v19-50-12]]

^<<v19-50-12,12>>^ Se eu tivesse fome, não to diria pois meu é o mundo e a sua plenitude.

[[v19-50-13]]

^<<v19-50-13,13>>^ Comerei eu carne de touros? ou beberei sangue de bodes?

[[v19-50-14]]

^<<v19-50-14,14>>^ Oferece a Deus por sacrifício ações de graças, e paga ao Altíssimo os teus votos;

[[v19-50-15]]

^<<v19-50-15,15>>^ e invoca-me no dia da angústia; eu te livrarei, e tu me glorificarás.

[[v19-50-16]]

^<<v19-50-16,16>>^ Mas ao ímpio diz Deus: Que fazes tu em recitares os meus estatutos, e em tomares o meu pacto na tua boca,

[[v19-50-17]]

^<<v19-50-17,17>>^ visto que aborreces a correção, e lanças as minhas palavras para trás de ti?

[[v19-50-18]]

^<<v19-50-18,18>>^ Quando vês um ladrão, tu te comprazes nele; e tens parte com os adúlteros.

[[v19-50-19]]

^<<v19-50-19,19>>^ Soltas a tua boca para o mal, e a tua língua trama enganos.

[[v19-50-20]]

^<<v19-50-20,20>>^ Tu te sentas a falar contra teu irmão; difamas o filho de tua mãe.

[[v19-50-21]]

^<<v19-50-21,21>>^ Estas coisas tens feito, e eu me calei; pensavas que na verdade eu era como tu; mas eu te argüirei, e tudo te porei à vista.

[[v19-50-22]]

^<<v19-50-22,22>>^ Considerai pois isto, vós que vos esqueceis de Deus, para que eu não vos despedace, sem que haja quem vos livre.

[[v19-50-23]]

^<<v19-50-23,23>>^ Aquele que oferece por sacrifício ações de graças me glorifica; e àquele que bem ordena o seu caminho eu mostrarei a salvação de Deus.

'''

xref:019-salmos/019-salmos-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmos/019-salmos-051.adoc#v19-51-0[Próximo Capítulo &#62;]