include::./index.adoc[]

[[v19-41-0]]
=== Salmos, 41
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-41-1]]

^<<v19-41-1,1>>^ Bem-aventurado é aquele que considera o pobre; o Senhor o livrará no dia do mal.

[[v19-41-2]]

^<<v19-41-2,2>>^ O Senhor o guardará, e o conservará em vida; será abençoado na terra; tu, Senhor não o entregarás à vontade dos seus inimigos.

[[v19-41-3]]

^<<v19-41-3,3>>^ O Senhor o sustentará no leito da enfermidade; tu lhe amaciarás a cama na sua doença.

[[v19-41-4]]

^<<v19-41-4,4>>^ Disse eu da minha parte: Senhor, compadece-te de mim, sara a minha alma, pois pequei contra ti.

[[v19-41-5]]

^<<v19-41-5,5>>^ Os meus inimigos falam mal de mim, dizendo: Quando morrerá ele, e perecerá o seu nome?

[[v19-41-6]]

^<<v19-41-6,6>>^ E, se algum deles vem ver-me, diz falsidades; no seu coração amontoa a maldade; e quando ele sai, é disso que fala.

[[v19-41-7]]

^<<v19-41-7,7>>^ Todos os que me odeiam cochicham entre si contra mim; contra mim maquinam o mal, dizendo:

[[v19-41-8]]

^<<v19-41-8,8>>^ Alguma coisa ruim se lhe apega; e agora que está deitado, não se levantará mais.

[[v19-41-9]]

^<<v19-41-9,9>>^ Até o meu próprio amigo íntimo em quem eu tanto confiava, e que comia do meu pão, levantou contra mim o seu calcanhar.

[[v19-41-10]]

^<<v19-41-10,10>>^ Mas tu, Senhor, compadece-te de mim e levanta-me, para que eu lhes retribua.

[[v19-41-11]]

^<<v19-41-11,11>>^ Por isso conheço eu que te deleitas em mim, por não triunfar de mim o meu inimigo

[[v19-41-12]]

^<<v19-41-12,12>>^ Quanto a mim, tu me sustentas na minha integridade, e me colocas diante da tua face para sempre.

[[v19-41-13]]

^<<v19-41-13,13>>^ Bendito seja o Senhor Deus de Israel de eternidade a eternidade. Amém e amém.

'''

xref:019-salmos/019-salmos-040.adoc#v19-40-0[&#60; Capítulo Anterior] | <<v19-41-0,Topo>> | xref:019-salmos/019-salmos-042.adoc#v19-42-0[Próximo Capítulo &#62;]