include::./index.adoc[]

[[v19-94-0]]
=== Salmos, 94
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-94-1]]

^<<v19-94-1,1>>^ Ó Senhor, Deus da vingança, ó Deus da vingança, resplandece!

[[v19-94-2]]

^<<v19-94-2,2>>^ Exalta-te, ó juiz da terra! dá aos soberbos o que merecem.

[[v19-94-3]]

^<<v19-94-3,3>>^ Até quando os ímpios, Senhor, até quando os ímpios exultarão?

[[v19-94-4]]

^<<v19-94-4,4>>^ Até quando falarão, dizendo coisas arrogantes, e se gloriarão todos os que praticam a iniqüidade?

[[v19-94-5]]

^<<v19-94-5,5>>^ Esmagam o teu povo, ó Senhor, e afligem a tua herança.

[[v19-94-6]]

^<<v19-94-6,6>>^ Matam a viúva e o estrangeiro, e tiram a vida ao órfão.

[[v19-94-7]]

^<<v19-94-7,7>>^ E dizem: O Senhor não vê; o Deus de Jacó não o percebe.

[[v19-94-8]]

^<<v19-94-8,8>>^ Atendei, ó néscios, dentre o povo; e vós, insensatos, quando haveis de ser sábios?

[[v19-94-9]]

^<<v19-94-9,9>>^ Aquele que fez ouvido, não ouvirá? ou aquele que formou o olho, não verá?

[[v19-94-10]]

^<<v19-94-10,10>>^ Porventura aquele que disciplina as nações, não corrigirá? Aquele que instrui o homem no conhecimento,

[[v19-94-11]]

^<<v19-94-11,11>>^ o Senhor, conhece os pensamentos do homem, que são vaidade.

[[v19-94-12]]

^<<v19-94-12,12>>^ Bem-aventurado é o homem a quem tu repreendes, ó Senhor, e a quem ensinas a tua lei,

[[v19-94-13]]

^<<v19-94-13,13>>^ para lhe dares descanso dos dias da adversidade, até que se abra uma cova para o ímpio.

[[v19-94-14]]

^<<v19-94-14,14>>^ Pois o Senhor não rejeitará o seu povo, nem desamparará a sua herança.

[[v19-94-15]]

^<<v19-94-15,15>>^ Mas o juízo voltará a ser feito com justiça, e hão de segui-lo todos os retos de coração.

[[v19-94-16]]

^<<v19-94-16,16>>^ Quem se levantará por mim contra os malfeitores? quem se porá ao meu lado contra os que praticam a iniqüidade?

[[v19-94-17]]

^<<v19-94-17,17>>^ Se o Senhor não tivesse sido o meu auxílio, já a minha alma estaria habitando no lugar do silêncio.

[[v19-94-18]]

^<<v19-94-18,18>>^ Quando eu disse: O meu pé resvala; a tua benignidade, Senhor, me susteve.

[[v19-94-19]]

^<<v19-94-19,19>>^ Quando os cuidados do meu coração se multiplicam, as tuas consolações recreiam a minha alma.

[[v19-94-20]]

^<<v19-94-20,20>>^ Pode acaso associar-se contigo o trono de iniqüidade, que forja o mal tendo a lei por pretexto?

[[v19-94-21]]

^<<v19-94-21,21>>^ Acorrem em tropel contra a vida do justo, e condenam o sangue inocente.

[[v19-94-22]]

^<<v19-94-22,22>>^ Mas o Senhor tem sido o meu alto retiro, e o meu Deus a rocha do meu alto retiro, e o meu Deus a rocha do meu refúgio.

[[v19-94-23]]

^<<v19-94-23,23>>^ Ele fará recair sobre eles a sua própria iniqüidade, e os destruirá na sua própria malícia; o Senhor nosso Deus os destruirá.

'''

xref:019-salmos/019-salmos-093.adoc#v19-93-0[&#60; Capítulo Anterior] | <<v19-94-0,Topo>> | xref:019-salmos/019-salmos-095.adoc#v19-95-0[Próximo Capítulo &#62;]