include::./index.adoc[]

[[v19-45-0]]
=== Salmos, 45
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-45-1]]

^<<v19-45-1,1>>^ O meu coração trasborda de boas palavras; dirijo os meus versos ao rei; a minha língua é qual pena de um hábil escriba.

[[v19-45-2]]

^<<v19-45-2,2>>^ Tu és o mais formoso dos filhos dos homens; a graça se derramou nos teus lábios; por isso Deus te abençoou para sempre.

[[v19-45-3]]

^<<v19-45-3,3>>^ Cinge a tua espada à coxa, ó valente, na tua glória e majestade.

[[v19-45-4]]

^<<v19-45-4,4>>^ E em tua majestade cavalga vitoriosamente pela causa da verdade, da mansidão e da justiça, e a tua destra te ensina coisas terríveis.

[[v19-45-5]]

^<<v19-45-5,5>>^ As tuas flechas são agudas no coração dos inimigos do rei; os povos caem debaixo de ti.

[[v19-45-6]]

^<<v19-45-6,6>>^ O teu trono, ó Deus, subsiste pelos séculos dos séculos; cetro de eqüidade é o cetro do teu reino.

[[v19-45-7]]

^<<v19-45-7,7>>^ Amaste a justiça e odiaste a iniqüidade; por isso Deus, o teu Deus, te ungiu com óleo de alegria, mais do que a teus companheiros.

[[v19-45-8]]

^<<v19-45-8,8>>^ Todas as tuas vestes cheiram a mirra a aloés e a cássia; dos palácios de marfim os instrumentos de cordas e te alegram.

[[v19-45-9]]

^<<v19-45-9,9>>^ Filhas de reis estão entre as tuas ilustres donzelas; à tua mão direita está a rainha, ornada de ouro de Ofir.

[[v19-45-10]]

^<<v19-45-10,10>>^ Ouve, filha, e olha, e inclina teus ouvidos; esquece-te do teu povo e da casa de teu pai.

[[v19-45-11]]

^<<v19-45-11,11>>^ Então o rei se afeiçoará à tua formosura. Ele é teu senhor, presta-lhe, pois, homenagem.

[[v19-45-12]]

^<<v19-45-12,12>>^ A filha de Tiro estará ali com presentes; os ricos do povo suplicarão o teu favor.

[[v19-45-13]]

^<<v19-45-13,13>>^ A filha do rei está esplendente lá dentro do palácio; as suas vestes são entretecidas de ouro.

[[v19-45-14]]

^<<v19-45-14,14>>^ Em vestidos de cores brilhantes será conduzida ao rei; as virgens, suas companheiras que a seguem, serão trazidas à tua presença.

[[v19-45-15]]

^<<v19-45-15,15>>^ Com alegria e regozijo serão trazidas; elas entrarão no palácio do rei.

[[v19-45-16]]

^<<v19-45-16,16>>^ Em lugar de teus pais estarão teus filhos; tu os farás príncipes sobre toda a terra.

[[v19-45-17]]

^<<v19-45-17,17>>^ Farei lembrado o teu nome de geração em geração; pelo que os povos te louvarão eternamente.

'''

xref:019-salmos/019-salmos-044.adoc#v19-44-0[&#60; Capítulo Anterior] | <<v19-45-0,Topo>> | xref:019-salmos/019-salmos-046.adoc#v19-46-0[Próximo Capítulo &#62;]