include::./index.adoc[]

[[v19-137-0]]
=== Salmos, 137
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-137-1]]

^<<v19-137-1,1>>^ Junto aos rios de Babilônia, ali nos assentamos e nos pusemos a chorar, recordando-nos de Sião.

[[v19-137-2]]

^<<v19-137-2,2>>^ Nos salgueiros que há no meio dela penduramos as nossas harpas,

[[v19-137-3]]

^<<v19-137-3,3>>^ pois ali aqueles que nos levaram cativos nos pediam canções; e os que nos atormentavam, que os alegrássemos, dizendo: Cantai-nos um dos cânticos de Sião.

[[v19-137-4]]

^<<v19-137-4,4>>^ Mas como entoaremos o cântico do Senhor em terra estrangeira?

[[v19-137-5]]

^<<v19-137-5,5>>^ Se eu me esquecer de ti, ó Jerusalém, esqueça-se a minha destra da sua destreza.

[[v19-137-6]]

^<<v19-137-6,6>>^ Apegue-se-me a língua ao céu da boca, se não me lembrar de ti, se eu não preferir Jerusalém à minha maior alegria.

[[v19-137-7]]

^<<v19-137-7,7>>^ Lembra-te, Senhor, contra os edomitas, do dia de Jerusalém, porque eles diziam: Arrasai-a, arrasai-a até os seus alicerces.

[[v19-137-8]]

^<<v19-137-8,8>>^ Ah! filha de Babilônia, devastadora; feliz aquele que te retribuir consoante nos fizeste a nós;

[[v19-137-9]]

^<<v19-137-9,9>>^ feliz aquele que pegar em teus pequeninos e der com eles nas pedra.

'''

xref:019-salmos/019-salmos-136.adoc#v19-136-0[&#60; Capítulo Anterior] | <<v19-137-0,Topo>> | xref:019-salmos/019-salmos-138.adoc#v19-138-0[Próximo Capítulo &#62;]