include::./index.adoc[]

[[v19-86-0]]
=== Salmos, 86
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-86-1]]

^<<v19-86-1,1>>^ Inclina, Senhor, os teus ouvidos, e ouve-me, porque sou pobre e necessitado.

[[v19-86-2]]

^<<v19-86-2,2>>^ Preserva a minha vida, pois sou piedoso; o Deus meu, salva o teu servo, que em ti confia.

[[v19-86-3]]

^<<v19-86-3,3>>^ Compadece-te de mim, ó Senhor, pois a ti clamo o dia todo.

[[v19-86-4]]

^<<v19-86-4,4>>^ Alegra a alma do teu servo, pois a ti, Senhor, elevo a minha alma.

[[v19-86-5]]

^<<v19-86-5,5>>^ Porque tu, Senhor, és bom, e pronto a perdoar, e abundante em benignidade para com todos os que te invocam.

[[v19-86-6]]

^<<v19-86-6,6>>^ Dá ouvidos, Senhor, à minha oração, e atende à voz das minhas súplicas.

[[v19-86-7]]

^<<v19-86-7,7>>^ No dia da minha angústia clamo a ti, porque tu me respondes.

[[v19-86-8]]

^<<v19-86-8,8>>^ Entre os deuses nenhum há semelhante a ti, Senhor, nem há obras como as tuas.

[[v19-86-9]]

^<<v19-86-9,9>>^ Todas as nações que fizeste virão e se prostrarão diante de ti, Senhor, e glorificarão o teu nome.

[[v19-86-10]]

^<<v19-86-10,10>>^ Ensina-me, Senhor, o teu caminho, e andarei na tua verdade; dispõe o meu coração para temer o teu nome.

[[v19-86-11]]

^<<v19-86-11,11>>^ Louvar-te-ei, Senhor Deus meu, de todo o meu coração, e glorificarei o teu nome para sempre.

[[v19-86-12]]

^<<v19-86-12,12>>^ Pois grande é a tua benignidade para comigo, e livraste a minha alma das profundezas do Seol.

[[v19-86-13]]

^<<v19-86-13,13>>^ Pois grande é a tua benignidade para comigo, e livraste a minha alma das profundezas do Seol.

[[v19-86-14]]

^<<v19-86-14,14>>^ Ó Deus, os soberbos têm-se levantado contra mim, e um bando de homens violentos procura tirar-me a vida; eles não te puseram diante dos seus olhos.

[[v19-86-15]]

^<<v19-86-15,15>>^ Mas tu, Senhor, és um Deus compassivo e benigno, longânimo, e abundante em graça e em fidelidade.

[[v19-86-16]]

^<<v19-86-16,16>>^ Volta-te para mim, e compadece-te de mim; dá a tua força ao teu servo, e a salva o filho da tua serva.

[[v19-86-17]]

^<<v19-86-17,17>>^ Mostra-me um sinal do teu favor, para que o vejam aqueles que me odeiam, e sejam envergonhados, por me haveres tu, Senhor, ajuntado e confortado.

'''

xref:019-salmos/019-salmos-085.adoc#v19-85-0[&#60; Capítulo Anterior] | <<v19-86-0,Topo>> | xref:019-salmos/019-salmos-087.adoc#v19-87-0[Próximo Capítulo &#62;]