include::./index.adoc[]

[[v19-101-0]]
=== Salmos, 101
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-101-1]]

^<<v19-101-1,1>>^ Cantarei a benignidade e o juízo; a ti, Senhor, cantarei.

[[v19-101-2]]

^<<v19-101-2,2>>^ Portar-me-ei sabiamente no caminho reto. Oh, quando virás ter comigo? Andarei em minha casa com integridade de coração.

[[v19-101-3]]

^<<v19-101-3,3>>^ Não porei coisa torpe diante dos meus olhos; aborreço as ações daqueles que se desviam; isso não se apagará a mim.

[[v19-101-4]]

^<<v19-101-4,4>>^ Longe de mim estará o coração perverso; não conhecerei o mal.

[[v19-101-5]]

^<<v19-101-5,5>>^ Aquele que difama o seu próximo às escondidas, eu o destruirei; aquele que tem olhar altivo e coração soberbo, não o tolerarei.

[[v19-101-6]]

^<<v19-101-6,6>>^ Os meus olhos estão sobre os fiéis da terra, para que habitem comigo; o que anda no caminho perfeito, esse me servirá.

[[v19-101-7]]

^<<v19-101-7,7>>^ O que usa de fraude não habitará em minha casa; o que profere mentiras não estará firme perante os meus olhos.

[[v19-101-8]]

^<<v19-101-8,8>>^ De manhã em manhã destruirei todos os ímpios da terra, para desarraigar da cidade do Senhor todos os que praticam a iniqüidade.

'''

xref:019-salmos/019-salmos-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-salmos/019-salmos-102.adoc#v19-102-0[Próximo Capítulo &#62;]