include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-69-1]]

^<<v19-69-1,1>>^ Salva-me, ó Deus, pois as águas me sobem até o pescoço.

[[v19-69-2]]

^<<v19-69-2,2>>^ Atolei-me em profundo lamaçal, onde não se pode firmar o pé; entrei na profundeza das águas, onde a corrente me submerge.

[[v19-69-3]]

^<<v19-69-3,3>>^ Estou cansado de clamar; secou-se-me a garganta; os meus olhos desfalecem de esperar por meu Deus.

[[v19-69-4]]

^<<v19-69-4,4>>^ Aqueles que me odeiam sem causa são mais do que os cabelos da minha cabeça; poderosos são aqueles que procuram destruir-me, que me atacam com mentiras; por isso tenho de restituir o que não extorqui.

[[v19-69-5]]

^<<v19-69-5,5>>^ Tu, ó Deus, bem conheces a minha estultícia, e as minhas culpas não são ocultas.

[[v19-69-6]]

^<<v19-69-6,6>>^ Não sejam envergonhados por minha causa aqueles que esperam em ti, ó Senhor Deus dos exércitos; não sejam confundidos por minha causa aqueles que te buscam, ó Deus de Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ Porque por amor de ti tenho suportado afrontas; a confusão me cobriu o rosto.

[[v19-69-8]]

^<<v19-69-8,8>>^ Tornei-me como um estranho para os meus irmãos, e um desconhecido para os filhos de minha mãe.

[[v19-69-9]]

^<<v19-69-9,9>>^ Pois o zelo da tua casa me devorou, e as afrontas dos que te afrontam caíram sobre mim.

[[v19-69-10]]

^<<v19-69-10,10>>^ Quando chorei e castiguei com jejum a minha alma, isto se me tornou em afrontas.

[[v19-69-11]]

^<<v19-69-11,11>>^ Quando me vesti de cilício, fiz-me para eles um provérbio.

[[v19-69-12]]

^<<v19-69-12,12>>^ Aqueles que se sentem à porta falam de mim; e sou objeto das cantigas dos bêbedos.

[[v19-69-13]]

^<<v19-69-13,13>>^ Eu, porém, faço a minha oração a ti, ó Senhor, em tempo aceitável; ouve-me, ó Deus, segundo a grandeza da tua benignidade, segundo a fidelidade da tua salvação.

[[v19-69-14]]

^<<v19-69-14,14>>^ Tira-me do lamaçal, e não me deixes afundar; seja eu salvo dos meus inimigos, e das profundezas das águas.

[[v19-69-15]]

^<<v19-69-15,15>>^ Não me submerja a corrente das águas e não me trague o abismo, nem cerre a cova a sua boca sobre mim.

[[v19-69-16]]

^<<v19-69-16,16>>^ Ouve-me, Senhor, pois grande é a tua benignidade; volta-te para mim segundo a tua muitíssima compaixão.

[[v19-69-17]]

^<<v19-69-17,17>>^ Não escondas o teu rosto do teu servo; ouve-me depressa, pois estou angustiado.

[[v19-69-18]]

^<<v19-69-18,18>>^ Aproxima-te da minha alma, e redime-a; resgata-me por causa dos meus inimigos.

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu conheces o meu opróbrio, a minha vergonha, e a minha ignomínia; diante de ti estão todos os meus adversários.

[[v19-69-20]]

^<<v19-69-20,20>>^ Afrontas quebrantaram-me o coração, e estou debilitado. Esperei por alguém que tivesse compaixão, mas não houve nenhum; e por consoladores, mas não os achei.

[[v19-69-21]]

^<<v19-69-21,21>>^ Deram-me fel por mantimento, e na minha sede me deram a beber vinagre.

[[v19-69-22]]

^<<v19-69-22,22>>^ Torne-se a sua mesa diante deles em laço, e sejam-lhes as suas ofertas pacíficas uma armadilha.

[[v19-69-23]]

^<<v19-69-23,23>>^ Obscureçam-se-lhes os olhos, para que não vejam, e faze com que os seus lombos tremam constantemente.

[[v19-69-24]]

^<<v19-69-24,24>>^ Derrama sobre eles a tua indignação, e apanhe-os o ardor da tua ira.

[[v19-69-25]]

^<<v19-69-25,25>>^ Fique desolada a sua habitação, e não haja quem habite nas suas tendas.

[[v19-69-26]]

^<<v19-69-26,26>>^ Pois perseguem a quem afligiste, e aumentam a dor daqueles a quem feriste.

[[v19-69-27]]

^<<v19-69-27,27>>^ Acrescenta iniqüidade à iniqüidade deles, e não encontrem eles absolvição na tua justiça.

[[v19-69-28]]

^<<v19-69-28,28>>^ Sejam riscados do livro da vida, e não sejam inscritos com os justos.

[[v19-69-29]]

^<<v19-69-29,29>>^ Eu, porém, estou aflito e triste; a tua salvação, ó Deus, me ponha num alto retiro.

[[v19-69-30]]

^<<v19-69-30,30>>^ Louvarei o nome de Deus com um cântico, e engrandecê-lo-ei com ação de graças.

[[v19-69-31]]

^<<v19-69-31,31>>^ Isto será mais agradável ao Senhor do que um boi, ou um novilho que tem pontas e unhas.

[[v19-69-32]]

^<<v19-69-32,32>>^ Vejam isto os mansos, e se alegrem; vós que buscais a Deus reviva o vosso coração.

[[v19-69-33]]

^<<v19-69-33,33>>^ Porque o Senhor ouve os necessitados, e não despreza os seus, embora sejam prisioneiros.

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem-no os céus e a terra, os mares e tudo quanto neles se move.

[[v19-69-35]]

^<<v19-69-35,35>>^ Porque Deus salvará a Sião, e edificará as cidades de Judá, e ali habitarão os seus servos e a possuirão.

[[v19-69-36]]

^<<v19-69-36,36>>^ E herdá-la-á a descendência de seus servos, e os que amam o seu nome habitarão nela.

'''

xref:019-salmos/019-salmos-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmos/019-salmos-070.adoc#v19-70-0[Próximo Capítulo &#62;]