include::./index.adoc[]

[[v19-141-0]]
=== Salmos, 141
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-141-1]]

^<<v19-141-1,1>>^ Ó Senhor, a ti clamo; dá-te pressa em me acudir! Dá ouvidos à minha voz, quando a ti clamo!

[[v19-141-2]]

^<<v19-141-2,2>>^ Suba a minha oração, como incenso, diante de ti, e seja o levantar das minhas mãos como o sacrifício da tarde!

[[v19-141-3]]

^<<v19-141-3,3>>^ Põe, ó Senhor, uma guarda à minha boca; vigia a porta dos meus lábios!

[[v19-141-4]]

^<<v19-141-4,4>>^ Não inclines o meu coração para o mal, nem para se ocupar de coisas más, com aqueles que praticam a iniqüidade; e não coma eu das suas gulodices!

[[v19-141-5]]

^<<v19-141-5,5>>^ Fira-me o justo, será isso uma benignidade; e repreenda-me, isso será como óleo sobre a minha cabeça; não o recuse a minha cabeça; mas continuarei a orar contra os feitos dos ímpios.

[[v19-141-6]]

^<<v19-141-6,6>>^ Quando os seus juízes forem arremessados duma penha abaixo, saberão que as palavras do Senhor são verdadeiras.

[[v19-141-7]]

^<<v19-141-7,7>>^ Como quando alguém lavra e sulca a terra, são os nossos ossos espalhados à boca do Seol.

[[v19-141-8]]

^<<v19-141-8,8>>^ Mas os meus olhos te contemplam, ó Senhor, meu Senhor; em ti tenho buscado refúgio; não me deixes sem defesa!

[[v19-141-9]]

^<<v19-141-9,9>>^ Guarda-me do laço que me armaram, e das armadilhas dos que praticam a iniqüidade.

[[v19-141-10]]

^<<v19-141-10,10>>^ Caiam os ímpios nas suas próprias redes, até que eu tenha escapado inteiramente.

'''

xref:019-salmos/019-salmos-140.adoc#v19-140-0[&#60; Capítulo Anterior] | <<v19-141-0,Topo>> | xref:019-salmos/019-salmos-142.adoc#v19-142-0[Próximo Capítulo &#62;]