include::./index.adoc[]

[[v19-78-0]]
=== Salmos, 78
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-78-1]]

^<<v19-78-1,1>>^ Escutai o meu ensino, povo meu; inclinai os vossos ouvidos às palavras da minha boca.

[[v19-78-2]]

^<<v19-78-2,2>>^ Abrirei a minha boca numa parábola; proporei enigmas da antigüidade,

[[v19-78-3]]

^<<v19-78-3,3>>^ coisas que temos ouvido e sabido, e que nossos pais nos têm contado.

[[v19-78-4]]

^<<v19-78-4,4>>^ Não os encobriremos aos seus filhos, cantaremos às gerações vindouras os louvores do Senhor, assim como a sua força e as maravilhas que tem feito.

[[v19-78-5]]

^<<v19-78-5,5>>^ Porque ele estabeleceu um testemunho em Jacó, e instituiu uma lei em Israel, as quais coisas ordenou aos nossos pais que as ensinassem a seus filhos;

[[v19-78-6]]

^<<v19-78-6,6>>^ para que as soubesse a geração vindoura, os filhos que houvesse de nascer, os quais se levantassem e as contassem a seus filhos,

[[v19-78-7]]

^<<v19-78-7,7>>^ a fim de que pusessem em Deus a sua esperança, e não se esquecessem das obras de Deus, mas guardassem os seus mandamentos;

[[v19-78-8]]

^<<v19-78-8,8>>^ e que não fossem como seus pais, geração contumaz e rebelde, geração de coração instável, cujo espírito não foi fiel para com Deus.

[[v19-78-9]]

^<<v19-78-9,9>>^ Os filhos de Efraim, armados de arcos, retrocederam no dia da peleja.

[[v19-78-10]]

^<<v19-78-10,10>>^ Não guardaram o pacto de Deus, e recusaram andar na sua lei;

[[v19-78-11]]

^<<v19-78-11,11>>^ esqueceram-se das suas obras e das maravilhas que lhes fizera ver.

[[v19-78-12]]

^<<v19-78-12,12>>^ Maravilhas fez ele à vista de seus pais na terra do Egito, no campo de Zoã.

[[v19-78-13]]

^<<v19-78-13,13>>^ Dividiu o mar, e os fez passar por ele; fez com que as águas parassem como um montão.

[[v19-78-14]]

^<<v19-78-14,14>>^ Também os guiou de dia por uma nuvem, e a noite toda por um clarão de fogo.

[[v19-78-15]]

^<<v19-78-15,15>>^ Fendeu rochas no deserto, e deu-lhes de beber abundantemente como de grandes abismos.

[[v19-78-16]]

^<<v19-78-16,16>>^ Da penha fez sair fontes, e fez correr águas como rios.

[[v19-78-17]]

^<<v19-78-17,17>>^ Todavia ainda prosseguiram em pecar contra ele, rebelando-se contra o Altíssimo no deserto.

[[v19-78-18]]

^<<v19-78-18,18>>^ E tentaram a Deus nos seus corações, pedindo comida segundo o seu apetite.

[[v19-78-19]]

^<<v19-78-19,19>>^ Também falaram contra Deus, dizendo: Poderá Deus porventura preparar uma mesa no deserto? Acaso fornecerá carne para o seu povo?

[[v19-78-20]]

^<<v19-78-20,20>>^ Pelo que o Senhor, quando os ouviu, se indignou; e acendeu um fogo contra Jacó, e a sua ira subiu contra Israel;

[[v19-78-21]]

^<<v19-78-21,21>>^ Pelo que o Senhor, quando os ouviu, se indignou; e acendeu um fogo contra Jacó, e a sua ira subiu contra Israel;

[[v19-78-22]]

^<<v19-78-22,22>>^ porque não creram em Deus nem confiaram na sua salvação.

[[v19-78-23]]

^<<v19-78-23,23>>^ Contudo ele ordenou às nuvens lá em cima, e abriu as portas dos céus;

[[v19-78-24]]

^<<v19-78-24,24>>^ fez chover sobre eles maná para comerem, e deu-lhes do trigo dos céus.

[[v19-78-25]]

^<<v19-78-25,25>>^ Cada um comeu o pão dos poderosos; ele lhes mandou comida em abundância.

[[v19-78-26]]

^<<v19-78-26,26>>^ Fez soprar nos céus o vento do oriente, e pelo seu poder trouxe o vento sul.

[[v19-78-27]]

^<<v19-78-27,27>>^ Sobre eles fez também chover carne como poeira, e aves de asas como a areia do mar;

[[v19-78-28]]

^<<v19-78-28,28>>^ e as fez cair no meio do arraial deles, ao redor de suas habitações.

[[v19-78-29]]

^<<v19-78-29,29>>^ Então comeram e se fartaram bem, pois ele lhes trouxe o que cobiçavam.

[[v19-78-30]]

^<<v19-78-30,30>>^ Não refrearam a sua cobiça. Ainda lhes estava a comida na boca,

[[v19-78-31]]

^<<v19-78-31,31>>^ quando a ira de Deus se levantou contra eles, e matou os mais fortes deles, e prostrou os escolhidos de Israel.

[[v19-78-32]]

^<<v19-78-32,32>>^ Com tudo isso ainda pecaram, e não creram nas suas maravilhas.

[[v19-78-33]]

^<<v19-78-33,33>>^ Pelo que consumiu os seus dias como um sopro, e os seus anos em repentino terror.

[[v19-78-34]]

^<<v19-78-34,34>>^ Quando ele os fazia morrer, então o procuravam; arrependiam-se, e de madrugada buscavam a Deus.

[[v19-78-35]]

^<<v19-78-35,35>>^ Lembravam-se de que Deus era a sua rocha, e o Deus Altíssimo o seu Redentor.

[[v19-78-36]]

^<<v19-78-36,36>>^ Todavia lisonjeavam-no com a boca, e com a língua lhe mentiam.

[[v19-78-37]]

^<<v19-78-37,37>>^ Pois o coração deles não era constante para com ele, nem foram eles fiéis ao seu pacto.

[[v19-78-38]]

^<<v19-78-38,38>>^ Mas ele, sendo compassivo, perdoou a sua iniqüidade, e não os destruiu; antes muitas vezes desviou deles a sua cólera, e não acendeu todo o seu furor.

[[v19-78-39]]

^<<v19-78-39,39>>^ Porque se lembrou de que eram carne, um vento que passa e não volta.

[[v19-78-40]]

^<<v19-78-40,40>>^ Quantas vezes se rebelaram contra ele no deserto, e o ofenderam no ermo!

[[v19-78-41]]

^<<v19-78-41,41>>^ Voltaram atrás, e tentaram a Deus; e provocaram o Santo de Israel.

[[v19-78-42]]

^<<v19-78-42,42>>^ Não se lembraram do seu poder, nem do dia em que os remiu do adversário,

[[v19-78-43]]

^<<v19-78-43,43>>^ nem de como operou os seus sinais no Egito, e as suas maravilhas no campo de Zoã,

[[v19-78-44]]

^<<v19-78-44,44>>^ convertendo em sangue os seus rios, para que não pudessem beber das suas correntes.

[[v19-78-45]]

^<<v19-78-45,45>>^ Também lhes mandou enxames de moscas que os consumiram, e rãs que os destruíram.

[[v19-78-46]]

^<<v19-78-46,46>>^ Entregou às lagartas as novidades deles, e o fruto do seu trabalho aos gafanhotos.

[[v19-78-47]]

^<<v19-78-47,47>>^ Destruiu as suas vinhas com saraiva, e os seus sicômoros com chuva de pedra.

[[v19-78-48]]

^<<v19-78-48,48>>^ Também entregou à saraiva o gado deles, e aos coriscos os seus rebanhos.

[[v19-78-49]]

^<<v19-78-49,49>>^ E atirou sobre eles o ardor da sua ira, o furor, a indignação, e a angústia, qual companhia de anjos destruidores.

[[v19-78-50]]

^<<v19-78-50,50>>^ Deu livre curso à sua ira; não os poupou da morte, mas entregou a vida deles à pestilência.

[[v19-78-51]]

^<<v19-78-51,51>>^ Feriu todo primogênito no Egito, primícias da força deles nas tendas de Cam.

[[v19-78-52]]

^<<v19-78-52,52>>^ Mas fez sair o seu povo como ovelhas, e os guiou pelo deserto como a um rebanho.

[[v19-78-53]]

^<<v19-78-53,53>>^ Guiou-os com segurança, de sorte que eles não temeram; mas aos seus inimigos, o mar os submergiu.

[[v19-78-54]]

^<<v19-78-54,54>>^ Sim, conduziu-os até a sua fronteira santa, até o monte que a sua destra adquirira.

[[v19-78-55]]

^<<v19-78-55,55>>^ Expulsou as nações de diante deles; e dividindo suas terras por herança, fez habitar em suas tendas as tribos de Israel.

[[v19-78-56]]

^<<v19-78-56,56>>^ Contudo tentaram e provocaram o Deus Altíssimo, e não guardaram os seus testemunhos.

[[v19-78-57]]

^<<v19-78-57,57>>^ Mas tornaram atrás, e portaram-se aleivosamente como seus pais; desviaram-se como um arco traiçoeiro.

[[v19-78-58]]

^<<v19-78-58,58>>^ Pois o provocaram à ira com os seus altos, e o incitaram a zelos com as suas imagens esculpidas.

[[v19-78-59]]

^<<v19-78-59,59>>^ Ao ouvir isso, Deus se indignou, e sobremodo abominou a Israel.

[[v19-78-60]]

^<<v19-78-60,60>>^ Pelo que desamparou o tabernáculo em Siló, a tenda da sua morada entre os homens,

[[v19-78-61]]

^<<v19-78-61,61>>^ dando a sua força ao cativeiro, e a sua glória à mão do inimigo.

[[v19-78-62]]

^<<v19-78-62,62>>^ Entregou o seu povo à espada, e encolerizou-se contra a sua herança.

[[v19-78-63]]

^<<v19-78-63,63>>^ Aos seus mancebos o fogo devorou, e suas donzelas não tiveram cântico nupcial.

[[v19-78-64]]

^<<v19-78-64,64>>^ Os seus sacerdotes caíram à espada, e suas viúvas não fizeram pranto.

[[v19-78-65]]

^<<v19-78-65,65>>^ Então o Senhor despertou como dum sono, como um valente que o vinho excitasse.

[[v19-78-66]]

^<<v19-78-66,66>>^ E fez recuar a golpes os seus adversários; infligiu-lhes eterna ignomínia.

[[v19-78-67]]

^<<v19-78-67,67>>^ Além disso, rejeitou a tenda de José, e não escolheu a tribo de Efraim;

[[v19-78-68]]

^<<v19-78-68,68>>^ antes escolheu a tribo de Judá, o monte Sião, que ele amava.

[[v19-78-69]]

^<<v19-78-69,69>>^ Edificou o seu santuário como os lugares elevados, como a terra que fundou para sempre.

[[v19-78-70]]

^<<v19-78-70,70>>^ Também escolheu a Davi, seu servo, e o tirou dos apriscos das ovelhas;

[[v19-78-71]]

^<<v19-78-71,71>>^ de após as ovelhas e suas crias o trouxe, para apascentar a Jacó, seu povo, e a Israel, sua herança.

[[v19-78-72]]

^<<v19-78-72,72>>^ E ele os apascentou, segundo a integridade do seu coração, e os guiou com a perícia de suas mãos.

'''

xref:019-salmos/019-salmos-077.adoc#v19-77-0[&#60; Capítulo Anterior] | <<v19-78-0,Topo>> | xref:019-salmos/019-salmos-079.adoc#v19-79-0[Próximo Capítulo &#62;]