include::./index.adoc[]

[[v19-27-0]]
=== Salmos, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-27-1]]

^<<v19-27-1,1>>^ O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?

[[v19-27-2]]

^<<v19-27-2,2>>^ Quando os malvados investiram contra mim, para comerem as minhas carnes, eles, meus adversários e meus inimigos, tropeçaram e caíram.

[[v19-27-3]]

^<<v19-27-3,3>>^ Ainda que um exército se acampe contra mim, o meu coração não temerá; ainda que a guerra se levante contra mim, conservarei a minha confiança.

[[v19-27-4]]

^<<v19-27-4,4>>^ Uma coisa pedi ao Senhor, e a buscarei: que possa morar na casa do Senhor todos os dias da minha vida, para contemplar a formosura do Senhor, e inquirir no seu templo.

[[v19-27-5]]

^<<v19-27-5,5>>^ Pois no dia da adversidade me esconderá no seu pavilhão; no recôndito do seu tabernáculo me esconderá; sobre uma rocha me elevará.

[[v19-27-6]]

^<<v19-27-6,6>>^ E agora será exaltada a minha cabeça acima dos meus inimigos que estão ao redor de mim; e no seu tabernáculo oferecerei sacrifícios de júbilo; cantarei, sim, cantarei louvores ao Senhor.

[[v19-27-7]]

^<<v19-27-7,7>>^ Ouve, ó Senhor, a minha voz quando clamo; compadece-te de mim e responde-me.

[[v19-27-8]]

^<<v19-27-8,8>>^ Quando disseste: Buscai o meu rosto; o meu coração te disse a ti: O teu rosto, Senhor, buscarei.

[[v19-27-9]]

^<<v19-27-9,9>>^ Não escondas de mim o teu rosto, não rejeites com ira o teu servo, tu que tens sido a minha ajuda. Não me enjeites nem me desampares, ó Deus da minha salvação.

[[v19-27-10]]

^<<v19-27-10,10>>^ Se meu pai e minha mãe me abandonarem, então o Senhor me acolherá.

[[v19-27-11]]

^<<v19-27-11,11>>^ Ensina-me, ó Senhor, o teu caminho, e guia-me por uma vereda plana, por causa dos que me espreitam.

[[v19-27-12]]

^<<v19-27-12,12>>^ Não me entregues à vontade dos meus adversários; pois contra mim se levantaram falsas testemunhas e os que respiram violência.

[[v19-27-13]]

^<<v19-27-13,13>>^ Creio que hei de ver a bondade do Senhor na terra dos viventes.

[[v19-27-14]]

^<<v19-27-14,14>>^ Espera tu pelo Senhor; anima-te, e fortalece o teu coração; espera, pois, pelo Senhor.

'''

xref:019-salmos/019-salmos-026.adoc#v19-26-0[&#60; Capítulo Anterior] | <<v19-27-0,Topo>> | xref:019-salmos/019-salmos-028.adoc#v19-28-0[Próximo Capítulo &#62;]