include::./index.adoc[]

[[v19-108-0]]
=== Salmos, 108
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-108-1]]

^<<v19-108-1,1>>^ Preparado está o meu coração, ó Deus; cantarei, sim, cantarei louvores, com toda a minha alma.

[[v19-108-2]]

^<<v19-108-2,2>>^ Despertai, saltério e harpa; eu mesmo despertarei a aurora.

[[v19-108-3]]

^<<v19-108-3,3>>^ Louvar-te-ei entre os povos, Senhor, cantar-te-ei louvores entre as nações.

[[v19-108-4]]

^<<v19-108-4,4>>^ Pois grande, acima dos céus, é a tua benignidade, e a tua verdade ultrapassa as mais altas nuvens.

[[v19-108-5]]

^<<v19-108-5,5>>^ Sê exaltado, ó Deus, acima dos céus, e seja a tua glória acima de toda a terra!

[[v19-108-6]]

^<<v19-108-6,6>>^ Para que sejam livres os teus amados, salva-nos com a tua destra, e ouve-nos.

[[v19-108-7]]

^<<v19-108-7,7>>^ Deus falou no seu santuário: Eu me regozijarei; repartirei Siquém, e medirei o vale de Sucote.

[[v19-108-8]]

^<<v19-108-8,8>>^ Meu é Gileade, meu é Manassés; também Efraim é o meu capacete; Judá o meu cetro.

[[v19-108-9]]

^<<v19-108-9,9>>^ Moabe a minha bacia de lavar; sobre Edom lançarei o meu sapato; sobre a Filístia bradarei em triunfo.

[[v19-108-10]]

^<<v19-108-10,10>>^ Quem me conduzirá à cidade fortificada? Quem me guiará até Edom?

[[v19-108-11]]

^<<v19-108-11,11>>^ Porventura não nos rejeitaste, ó Deus? Não sais, ó Deus, com os nossos exércitos.

[[v19-108-12]]

^<<v19-108-12,12>>^ Dá-nos auxílio contra o adversário, pois vão é o socorro da parte do homem.

[[v19-108-13]]

^<<v19-108-13,13>>^ Em Deus faremos proezas; porque é ele quem calcará aos pés os nossos inimigos.

'''

xref:019-salmos/019-salmos-107.adoc#v19-107-0[&#60; Capítulo Anterior] | <<v19-108-0,Topo>> | xref:019-salmos/019-salmos-109.adoc#v19-109-0[Próximo Capítulo &#62;]