include::./index.adoc[]

[[v19-111-0]]
=== Salmos, 111
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-111-1]]

^<<v19-111-1,1>>^ Louvai ao Senhor. De todo o coração darei graças ao Senhor, no concílio dos retos e na congregação.

[[v19-111-2]]

^<<v19-111-2,2>>^ Grandes são as obras do Senhor, e para serem estudadas por todos os que nelas se comprazem.

[[v19-111-3]]

^<<v19-111-3,3>>^ Glória e majestade há em sua obra; e a sua justiça permanece para sempre.

[[v19-111-4]]

^<<v19-111-4,4>>^ Ele fez memoráveis as suas maravilhas; compassivo e misericordioso é o Senhor.

[[v19-111-5]]

^<<v19-111-5,5>>^ Dá mantimento aos que o temem; lembra-se sempre do seu pacto.

[[v19-111-6]]

^<<v19-111-6,6>>^ Mostrou ao seu povo o poder das suas obras, dando-lhe a herança das nações.

[[v19-111-7]]

^<<v19-111-7,7>>^ As obras das suas mãos são verdade e justiça; fiéis são todos os seus preceitos;

[[v19-111-8]]

^<<v19-111-8,8>>^ firmados estão para todo o sempre; são feitos em verdade e retidão.

[[v19-111-9]]

^<<v19-111-9,9>>^ Enviou ao seu povo a redenção; ordenou para sempre o seu pacto; santo e tremendo é o seu nome.

[[v19-111-10]]

^<<v19-111-10,10>>^ O temor do Senhor é o princípio da sabedoria; têm bom entendimento todos os que cumprem os seus preceitos; o seu louvor subsiste para sempre.

'''

xref:019-salmos/019-salmos-110.adoc#v19-110-0[&#60; Capítulo Anterior] | <<v19-111-0,Topo>> | xref:019-salmos/019-salmos-112.adoc#v19-112-0[Próximo Capítulo &#62;]