include::./index.adoc[]

[[v19-2-0]]
=== Salmos, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-2-1]]

^<<v19-2-1,1>>^ Por que se amotinam as nações, e os povos tramam em vão?

[[v19-2-2]]

^<<v19-2-2,2>>^ Os reis da terra se levantam, e os príncipes juntos conspiram contra o Senhor e contra o seu ungido, dizendo:

[[v19-2-3]]

^<<v19-2-3,3>>^ Rompamos as suas ataduras, e sacudamos de nós as suas cordas.

[[v19-2-4]]

^<<v19-2-4,4>>^ Aquele que está sentado nos céus se rirá; o Senhor zombará deles.

[[v19-2-5]]

^<<v19-2-5,5>>^ Então lhes falará na sua ira, e no seu furor os confundirá, dizendo:

[[v19-2-6]]

^<<v19-2-6,6>>^ Eu tenho estabelecido o meu Rei sobre Sião, meu santo monte.

[[v19-2-7]]

^<<v19-2-7,7>>^ Falarei do decreto do Senhor; ele me disse: Tu és meu Filho, hoje te gerei.

[[v19-2-8]]

^<<v19-2-8,8>>^ Pede-me, e eu te darei as nações por herança, e as extremidades da terra por possessão.

[[v19-2-9]]

^<<v19-2-9,9>>^ Tu os quebrarás com uma vara de ferro; tu os despedaçarás como a um vaso de oleiro.

[[v19-2-10]]

^<<v19-2-10,10>>^ Agora, pois, ó reis, sede prudentes; deixai-vos instruir, juízes da terra.

[[v19-2-11]]

^<<v19-2-11,11>>^ Servi ao Senhor com temor, e regozijai-vos com tremor.

[[v19-2-12]]

^<<v19-2-12,12>>^ Beijai o Filho, para que não se ire, e pereçais no caminho; porque em breve se inflamará a sua ira. Bem-aventurados todos aqueles que nele confiam.

'''

xref:019-salmos/019-salmos-001.adoc#v19-1-0[&#60; Capítulo Anterior] | <<v19-2-0,Topo>> | xref:019-salmos/019-salmos-003.adoc#v19-3-0[Próximo Capítulo &#62;]