include::./index.adoc[]

[[v19-88-0]]
=== Salmos, 88
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-88-1]]

^<<v19-88-1,1>>^ Ó Senhor, Deus da minha salvação, dia e noite clamo diante de ti.

[[v19-88-2]]

^<<v19-88-2,2>>^ Chegue à tua presença a minha oração, inclina os teus ouvidos ao meu clamor;

[[v19-88-3]]

^<<v19-88-3,3>>^ porque a minha alma está cheia de angústias, e a minha vida se aproxima do Seol.

[[v19-88-4]]

^<<v19-88-4,4>>^ Já estou contado com os que descem à cova; estou como homem sem forças,

[[v19-88-5]]

^<<v19-88-5,5>>^ atirado entre os finados; como os mortos que jazem na sepultura, dos quais já não te lembras, e que são desamparados da tua mão.

[[v19-88-6]]

^<<v19-88-6,6>>^ Puseste-me na cova mais profunda, em lugares escuros, nas profundezas.

[[v19-88-7]]

^<<v19-88-7,7>>^ Sobre mim pesa a tua cólera; tu me esmagaste com todas as tuas ondas.

[[v19-88-8]]

^<<v19-88-8,8>>^ Apartaste de mim os meus conhecidos, fizeste-me abominável para eles; estou encerrado e não posso sair.

[[v19-88-9]]

^<<v19-88-9,9>>^ Os meus olhos desfalecem por causa da aflição. Clamo a ti todo dia, Senhor, estendendo-te as minhas mãos.

[[v19-88-10]]

^<<v19-88-10,10>>^ Mostrarás tu maravilhas aos mortos? ou levantam-se os mortos para te louvar?

[[v19-88-11]]

^<<v19-88-11,11>>^ Será anunciada a tua benignidade na sepultura, ou a tua fidelidade no Abadom?

[[v19-88-12]]

^<<v19-88-12,12>>^ Serão conhecidas nas trevas as tuas maravilhas, e a tua justiça na terra do esquecimento?

[[v19-88-13]]

^<<v19-88-13,13>>^ Eu, porém, Senhor, clamo a ti; de madrugada a minha oração chega à tua presença.

[[v19-88-14]]

^<<v19-88-14,14>>^ Senhor, por que me rejeitas? por que escondes de mim a tua face?

[[v19-88-15]]

^<<v19-88-15,15>>^ Estou aflito, e prestes a morrer desde a minha mocidade; sofro os teus terrores, estou desamparado.

[[v19-88-16]]

^<<v19-88-16,16>>^ Sobre mim tem passado a tua ardente indignação; os teus terrores deram cabo de mim.

[[v19-88-17]]

^<<v19-88-17,17>>^ Como águas me rodeiam todo o dia; cercam-me todos juntos.

[[v19-88-18]]

^<<v19-88-18,18>>^ Aparte de mim amigos e companheiros; os meus conhecidos se acham nas trevas.

'''

xref:019-salmos/019-salmos-087.adoc#v19-87-0[&#60; Capítulo Anterior] | <<v19-88-0,Topo>> | xref:019-salmos/019-salmos-089.adoc#v19-89-0[Próximo Capítulo &#62;]