include::./index.adoc[]

[[v19-73-0]]
=== Salmos, 73
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-73-1]]

^<<v19-73-1,1>>^ Verdadeiramente bom é Deus para com Israel, para com os limpos de coração.

[[v19-73-2]]

^<<v19-73-2,2>>^ Quanto a mim, os meus pés quase resvalaram; pouco faltou para que os meus passos escorregassem.

[[v19-73-3]]

^<<v19-73-3,3>>^ Pois eu tinha inveja dos soberbos, ao ver a prosperidade dos ímpios.

[[v19-73-4]]

^<<v19-73-4,4>>^ Não há apertos na sua morte; o seu corpo é forte e sadio.

[[v19-73-5]]

^<<v19-73-5,5>>^ Não se acham em tribulações como outra gente, nem são afligidos como os demais homens.

[[v19-73-6]]

^<<v19-73-6,6>>^ Pelo que a soberba lhes cinge o pescoço como um colar; a violência os cobre como um vestido.

[[v19-73-7]]

^<<v19-73-7,7>>^ Os olhos deles estão inchados de gordura; trasbordam as fantasias do seu coração.

[[v19-73-8]]

^<<v19-73-8,8>>^ Motejam e falam maliciosamente; falam arrogantemente da opressão.

[[v19-73-9]]

^<<v19-73-9,9>>^ Põem a sua boca contra os céus, e a sua língua percorre a terra.

[[v19-73-10]]

^<<v19-73-10,10>>^ Pelo que o povo volta para eles e não acha neles falta alguma.

[[v19-73-11]]

^<<v19-73-11,11>>^ E dizem: Como o sabe Deus? e: Há conhecimento no Altíssimo?

[[v19-73-12]]

^<<v19-73-12,12>>^ Eis que estes são ímpios; sempre em segurança, aumentam as suas riquezas.

[[v19-73-13]]

^<<v19-73-13,13>>^ Na verdade que em vão tenho purificado o meu coração e lavado as minhas mãos na inocência,

[[v19-73-14]]

^<<v19-73-14,14>>^ pois todo o dia tenho sido afligido, e castigado cada manhã.

[[v19-73-15]]

^<<v19-73-15,15>>^ Se eu tivesse dito: Também falarei assim; eis que me teria havido traiçoeiramente para com a geração de teus filhos.

[[v19-73-16]]

^<<v19-73-16,16>>^ Quando me esforçava para compreender isto, achei que era tarefa difícil para mim,

[[v19-73-17]]

^<<v19-73-17,17>>^ até que entrei no santuário de Deus; então percebi o fim deles.

[[v19-73-18]]

^<<v19-73-18,18>>^ Certamente tu os pões em lugares escorregadios, tu os lanças para a ruína.

[[v19-73-19]]

^<<v19-73-19,19>>^ Como caem na desolação num momento! ficam totalmente consumidos de terrores.

[[v19-73-20]]

^<<v19-73-20,20>>^ Como faz com um sonho o que acorda, assim, ó Senhor, quando acordares, desprezarás as suas fantasias.

[[v19-73-21]]

^<<v19-73-21,21>>^ Quando o meu espírito se amargurava, e sentia picadas no meu coração,

[[v19-73-22]]

^<<v19-73-22,22>>^ estava embrutecido, e nada sabia; era como animal diante de ti.

[[v19-73-23]]

^<<v19-73-23,23>>^ Todavia estou sempre contigo; tu me seguras a mão direita.

[[v19-73-24]]

^<<v19-73-24,24>>^ Tu me guias com o teu conselho, e depois me receberás em glória.

[[v19-73-25]]

^<<v19-73-25,25>>^ A quem tenho eu no céu senão a ti? e na terra não há quem eu deseje além de ti.

[[v19-73-26]]

^<<v19-73-26,26>>^ A minha carne e o meu coração desfalecem; do meu coração, porém, Deus é a fortaleza, e o meu quinhão para sempre.

[[v19-73-27]]

^<<v19-73-27,27>>^ Pois os que estão longe de ti perecerão; tu exterminas todos aqueles que se desviam de ti.

[[v19-73-28]]

^<<v19-73-28,28>>^ Mas para mim, bom é aproximar-me de Deus; ponho a minha confiança no Senhor Deus, para anunciar todas as suas obras.

'''

xref:019-salmos/019-salmos-072.adoc#v19-72-0[&#60; Capítulo Anterior] | <<v19-73-0,Topo>> | xref:019-salmos/019-salmos-074.adoc#v19-74-0[Próximo Capítulo &#62;]