include::./index.adoc[]

[[v19-37-0]]
=== Salmos, 37
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-37-1]]

^<<v19-37-1,1>>^ Não te enfades por causa dos malfeitores, nem tenhas inveja dos que praticam a iniqüidade.

[[v19-37-2]]

^<<v19-37-2,2>>^ Pois em breve murcharão como a relva, e secarão como a erva verde.

[[v19-37-3]]

^<<v19-37-3,3>>^ Confia no Senhor e faze o bem; assim habitarás na terra, e te alimentarás em segurança.

[[v19-37-4]]

^<<v19-37-4,4>>^ Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.

[[v19-37-5]]

^<<v19-37-5,5>>^ Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.

[[v19-37-6]]

^<<v19-37-6,6>>^ E ele fará sobressair a tua justiça como a luz, e o teu direito como o meio-dia.

[[v19-37-7]]

^<<v19-37-7,7>>^ Descansa no Senhor, e espera nele; não te enfades por causa daquele que prospera em seu caminho, por causa do homem que executa maus desígnios.

[[v19-37-8]]

^<<v19-37-8,8>>^ Deixa a ira, e abandona o furor; não te enfades, pois isso só leva à prática do mal.

[[v19-37-9]]

^<<v19-37-9,9>>^ Porque os malfeitores serão exterminados, mas aqueles que esperam no Senhor herdarão a terra.

[[v19-37-10]]

^<<v19-37-10,10>>^ Pois ainda um pouco, e o ímpio não existirá; atentarás para o seu lugar, e ele ali não estará.

[[v19-37-11]]

^<<v19-37-11,11>>^ Mas os mansos herdarão a terra, e se deleitarão na abundância de paz.

[[v19-37-12]]

^<<v19-37-12,12>>^ O ímpio maquina contra o justo, e contra ele range os dentes,

[[v19-37-13]]

^<<v19-37-13,13>>^ mas o Senhor se ri do ímpio, pois vê que vem chegando o seu dia.

[[v19-37-14]]

^<<v19-37-14,14>>^ Os ímpios têm puxado da espada e têm entesado o arco, para derrubarem o poder e necessitado, e para matarem os que são retos no seu caminho.

[[v19-37-15]]

^<<v19-37-15,15>>^ Mas a sua espada lhes entrará no coração, e os seus arcos quebrados.

[[v19-37-16]]

^<<v19-37-16,16>>^ Mais vale o pouco que o justo tem, do que as riquezas de muitos ímpios.

[[v19-37-17]]

^<<v19-37-17,17>>^ Pois os braços dos ímpios serão quebrados, mas o Senhor sustém os justos.

[[v19-37-18]]

^<<v19-37-18,18>>^ O Senhor conhece os dias dos íntegros, e a herança deles permanecerá para sempre.

[[v19-37-19]]

^<<v19-37-19,19>>^ Não serão envergonhados no dia do mal, e nos dias da fome se fartarão.

[[v19-37-20]]

^<<v19-37-20,20>>^ Mas os ímpios perecerão, e os inimigos do Senhor serão como a beleza das pastagens; desaparecerão, em fumaça se desfarão.

[[v19-37-21]]

^<<v19-37-21,21>>^ O ímpio toma emprestado, e não paga; mas o justo se compadece e dá.

[[v19-37-22]]

^<<v19-37-22,22>>^ Pois aqueles que são abençoados pelo Senhor herdarão a terra, mas aqueles que são por ele amaldiçoados serão exterminados.

[[v19-37-23]]

^<<v19-37-23,23>>^ Confirmados pelo Senhor são os passos do homem em cujo caminho ele se deleita;

[[v19-37-24]]

^<<v19-37-24,24>>^ ainda que caia, não ficará prostrado, pois o Senhor lhe segura a mão.

[[v19-37-25]]

^<<v19-37-25,25>>^ Fui moço, e agora sou velho; mas nunca vi desamparado o justo, nem a sua descendência a mendigar o pão.

[[v19-37-26]]

^<<v19-37-26,26>>^ Ele é sempre generoso, e empresta, e a sua descendência é abençoada.

[[v19-37-27]]

^<<v19-37-27,27>>^ Aparta-te do mal e faze o bem; e terás morada permanente.

[[v19-37-28]]

^<<v19-37-28,28>>^ Pois o Senhor ama a justiça e não desampara os seus santos. Eles serão preservados para sempre, mas a descendência dos ímpios será exterminada.

[[v19-37-29]]

^<<v19-37-29,29>>^ Os justos herdarão a terra e nela habitarão para sempre.

[[v19-37-30]]

^<<v19-37-30,30>>^ A boca do justo profere sabedoria; a sua língua fala o que é reto.

[[v19-37-31]]

^<<v19-37-31,31>>^ A lei do seu Deus está em seu coração; não resvalarão os seus passos.

[[v19-37-32]]

^<<v19-37-32,32>>^ O ímpio espreita o justo, e procura matá-lo.

[[v19-37-33]]

^<<v19-37-33,33>>^ O Senhor não o deixará nas mãos dele, nem o condenará quando for julgado.

[[v19-37-34]]

^<<v19-37-34,34>>^ Espera no Senhor, e segue o seu caminho, e ele te exaltará para herdares a terra; tu o verás quando os ímpios forem exterminados.

[[v19-37-35]]

^<<v19-37-35,35>>^ Vi um ímpio cheio de prepotência, e a espalhar-se como a árvore verde na terra natal.

[[v19-37-36]]

^<<v19-37-36,36>>^ Mas eu passei, e ele já não era; procurei-o, mas não pôde ser encontrado.

[[v19-37-37]]

^<<v19-37-37,37>>^ Nota o homem íntegro, e considera o reto, porque há para o homem de paz um porvir feliz.

[[v19-37-38]]

^<<v19-37-38,38>>^ Quanto aos transgressores, serão à uma destruídos, e a posteridade dos ímpios será exterminada.

[[v19-37-39]]

^<<v19-37-39,39>>^ Mas a salvação dos justos vem do Senhor; ele é a sua fortaleza no tempo da angústia.

[[v19-37-40]]

^<<v19-37-40,40>>^ E o Senhor os ajuda e os livra; ele os livra dos ímpios e os salva, porquanto nele se refugiam.

'''

xref:019-salmos/019-salmos-036.adoc#v19-36-0[&#60; Capítulo Anterior] | <<v19-37-0,Topo>> | xref:019-salmos/019-salmos-038.adoc#v19-38-0[Próximo Capítulo &#62;]