include::./index.adoc[]

[[v19-38-0]]
=== Salmos, 38
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-38-1]]

^<<v19-38-1,1>>^ Ó Senhor, não me repreendas na tua ira, nem me castigues no teu furor.

[[v19-38-2]]

^<<v19-38-2,2>>^ Porque as tuas flechas se cravaram em mim, e sobre mim a tua mão pesou.

[[v19-38-3]]

^<<v19-38-3,3>>^ Não há coisa sã na minha carne, por causa da tua cólera; nem há saúde nos meus ossos, por causa do meu pecado.

[[v19-38-4]]

^<<v19-38-4,4>>^ Pois já as minhas iniqüidades submergem a minha cabeça; como carga pesada excedem as minhas forças.

[[v19-38-5]]

^<<v19-38-5,5>>^ As minhas chagas se tornam fétidas e purulentas, por causa da minha loucura.

[[v19-38-6]]

^<<v19-38-6,6>>^ Estou encurvado, estou muito abatido, ando lamentando o dia todo.

[[v19-38-7]]

^<<v19-38-7,7>>^ Pois os meus lombos estão cheios de ardor, e não há coisa sã na minha carne.

[[v19-38-8]]

^<<v19-38-8,8>>^ Estou gasto e muito esmagado; dou rugidos por causa do desassossego do meu coração.

[[v19-38-9]]

^<<v19-38-9,9>>^ Senhor, diante de ti está todo o meu desejo, e o meu suspirar não te é oculto.

[[v19-38-10]]

^<<v19-38-10,10>>^ O meu coração está agitado; a minha força me falta; quanto à luz dos meus olhos, até essa me deixou.

[[v19-38-11]]

^<<v19-38-11,11>>^ Os meus amigos e os meus companheiros afastaram-se da minha chaga; e os meus parentes se põem à distância.

[[v19-38-12]]

^<<v19-38-12,12>>^ Também os que buscam a minha vida me armam laços, e os que procuram o meu mal dizem coisas perniciosas,

[[v19-38-13]]

^<<v19-38-13,13>>^ Mas eu, como um surdo, não ouço; e sou qual um mudo que não abre a boca.

[[v19-38-14]]

^<<v19-38-14,14>>^ Assim eu sou como homem que não ouve, e em cuja boca há com que replicar.

[[v19-38-15]]

^<<v19-38-15,15>>^ Mas por ti, Senhor, espero; tu, Senhor meu Deus, responderás.

[[v19-38-16]]

^<<v19-38-16,16>>^ Rogo, pois: Ouve-me, para que eles não se regozijem sobre mim e não se engrandeçam contra mim quando resvala o meu pé.

[[v19-38-17]]

^<<v19-38-17,17>>^ Pois estou prestes a tropeçar; a minha dor está sempre comigo.

[[v19-38-18]]

^<<v19-38-18,18>>^ Confesso a minha iniqüidade; entristeço-me por causa do meu pecado.

[[v19-38-19]]

^<<v19-38-19,19>>^ Mas os meus inimigos são cheios de vida e são fortes, e muitos são os que sem causa me odeiam.

[[v19-38-20]]

^<<v19-38-20,20>>^ Os que tornam o mal pelo bem são meus adversários, porque eu sigo o que é bom.

[[v19-38-21]]

^<<v19-38-21,21>>^ Não me desampares, ó Senhor; Deus meu, não te alongues de mim.

[[v19-38-22]]

^<<v19-38-22,22>>^ Apressa-te em meu auxílio, Senhor, minha salvação.

'''

xref:019-salmos/019-salmos-037.adoc#v19-37-0[&#60; Capítulo Anterior] | <<v19-38-0,Topo>> | xref:019-salmos/019-salmos-039.adoc#v19-39-0[Próximo Capítulo &#62;]