include::./index.adoc[]

[[v19-99-0]]
=== Salmos, 99
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-99-1]]

^<<v19-99-1,1>>^ O Senhor reina, tremam os povos; ele está entronizado sobre os querubins, estremeça a terra.

[[v19-99-2]]

^<<v19-99-2,2>>^ O Senhor é grande em Sião, e exaltado acima de todos os povos.

[[v19-99-3]]

^<<v19-99-3,3>>^ Louvem o teu nome, grande e tremendo; pois é santo.

[[v19-99-4]]

^<<v19-99-4,4>>^ És Rei poderoso que amas a justiça; estabeleces a eqüidade, executas juízo e justiça em Jacó.

[[v19-99-5]]

^<<v19-99-5,5>>^ Exaltai o Senhor nosso Deus, e prostrai-vos diante do escabelo de seus pés; porque ele é santo.

[[v19-99-6]]

^<<v19-99-6,6>>^ Moisés e Arão entre os seus sacerdotes, e Samuel entre os que invocavam o seu nome, clamavam ao Senhor, e ele os ouvia.

[[v19-99-7]]

^<<v19-99-7,7>>^ Na coluna de nuvem lhes falava; eles guardavam os seus testemunhos, e os estatutos que lhes dera.

[[v19-99-8]]

^<<v19-99-8,8>>^ Tu os ouviste, Senhor nosso Deus; tu foste para eles um Deus perdoador, embora vingador dos seus atos.

[[v19-99-9]]

^<<v19-99-9,9>>^ Exaltai o Senhor nosso Deus e adorai-o no seu santo monte, porque o Senhor nosso Deus é santo.

'''

xref:019-salmos/019-salmos-098.adoc#v19-98-0[&#60; Capítulo Anterior] | <<v19-99-0,Topo>> | xref:019-salmos/019-salmos-100.adoc#v19-100-0[Próximo Capítulo &#62;]