include::./index.adoc[]

[[v19-148-0]]
=== Salmos, 148
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-148-1]]

^<<v19-148-1,1>>^ Louvai ao Senhor! Louvai ao Senhor desde o céu, louvai-o nas alturas!

[[v19-148-2]]

^<<v19-148-2,2>>^ Louvai-o, todos os seus anjos; louvai-o, todas as suas hostes!

[[v19-148-3]]

^<<v19-148-3,3>>^ Louvai-o, sol e lua; louvai-o, todas as estrelas luzentes!

[[v19-148-4]]

^<<v19-148-4,4>>^ Louvai-o, céus dos céus, e as águas que estão sobre os céus!

[[v19-148-5]]

^<<v19-148-5,5>>^ Louvem eles o nome do Senhor; pois ele deu ordem, e logo foram criados.

[[v19-148-6]]

^<<v19-148-6,6>>^ Também ele os estabeleceu para todo sempre; e lhes fixou um limite que nenhum deles ultrapassará.

[[v19-148-7]]

^<<v19-148-7,7>>^ Louvai ao Senhor desde a terra, vós, monstros marinhos e todos os abismos;

[[v19-148-8]]

^<<v19-148-8,8>>^ fogo e saraiva, neve e vapor; vento tempestuoso que escuta a sua palavra;

[[v19-148-9]]

^<<v19-148-9,9>>^ montes e todos os outeiros; árvores frutíferas e todos os cedros;

[[v19-148-10]]

^<<v19-148-10,10>>^ feras e todo o gado; répteis e aves voadoras;

[[v19-148-11]]

^<<v19-148-11,11>>^ reis da terra e todos os povos; príncipes e todos os juízes da terra;

[[v19-148-12]]

^<<v19-148-12,12>>^ mancebos e donzelas; velhos e crianças!

[[v19-148-13]]

^<<v19-148-13,13>>^ Louvem eles o nome do Senhor, pois só o seu nome é excelso; a sua glória é acima da terra e do céu.

[[v19-148-14]]

^<<v19-148-14,14>>^ Ele também exalta o poder do seu povo, o louvor de todos os seus santos, dos filhos de Israel, um povo que lhe é chegado. Louvai ao Senhor!

'''

xref:019-salmos/019-salmos-147.adoc#v19-147-0[&#60; Capítulo Anterior] | <<v19-148-0,Topo>> | xref:019-salmos/019-salmos-149.adoc#v19-149-0[Próximo Capítulo &#62;]