include::./index.adoc[]

[[v19-144-0]]
=== Salmos, 144
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-144-1]]

^<<v19-144-1,1>>^ Bendito seja o Senhor, minha rocha, que adestra as minhas mãos para a peleja e os meus dedos para a guerra;

[[v19-144-2]]

^<<v19-144-2,2>>^ meu refúgio e minha fortaleza, meu alto retiro e meu e meu libertador, escudo meu, em quem me refugio; ele é quem me sujeita o meu povo.

[[v19-144-3]]

^<<v19-144-3,3>>^ Ó Senhor, que é o homem, para que tomes conhecimento dele, e o filho do homem, para que o consideres?

[[v19-144-4]]

^<<v19-144-4,4>>^ O homem é semelhante a um sopro; os seus dias são como a sombra que passa.

[[v19-144-5]]

^<<v19-144-5,5>>^ Abaixa, ó Senhor, o teu céu, e desce! Toca os montes, para que fumeguem!

[[v19-144-6]]

^<<v19-144-6,6>>^ Arremessa os teus raios, e dissipa-os; envia as tuas flechas, e desbarata-os!

[[v19-144-7]]

^<<v19-144-7,7>>^ Estende as tuas mãos desde o alto; livra-me, e arrebata-me das poderosas águas e da mão do estrangeiro,

[[v19-144-8]]

^<<v19-144-8,8>>^ cuja boca fala vaidade, e cuja mão direita é a destra da falsidade.

[[v19-144-9]]

^<<v19-144-9,9>>^ A ti, ó Deus, cantarei um cântico novo; com a harpa de dez cordas te cantarei louvores,

[[v19-144-10]]

^<<v19-144-10,10>>^ sim, a ti que dás a vitória aos reis, e que livras da espada maligna a teu servo Davi.

[[v19-144-11]]

^<<v19-144-11,11>>^ Livra-me, e tira-me da mão do estrangeiro, cuja boca fala mentiras, e cuja mão direita é a destra da falsidade.

[[v19-144-12]]

^<<v19-144-12,12>>^ Sejam os nossos filhos, na sua mocidade, como plantas bem desenvolvidas, e as nossas filhas como pedras angulares lavradas, como as de um palácio.

[[v19-144-13]]

^<<v19-144-13,13>>^ Estejam repletos os nossos celeiros, fornecendo toda sorte de provisões; as nossas ovelhas produzam a milhares e a dezenas de milhares em nossos campos;

[[v19-144-14]]

^<<v19-144-14,14>>^ os nossos bois levem ricas cargas; e não haja assaltos, nem sortidas, nem clamores em nossas ruas!

[[v19-144-15]]

^<<v19-144-15,15>>^ Bem-aventurado o povo a quem assim sucede! Bem-aventurado o povo cujo Deus é o Senhor.

'''

xref:019-salmos/019-salmos-143.adoc#v19-143-0[&#60; Capítulo Anterior] | <<v19-144-0,Topo>> | xref:019-salmos/019-salmos-145.adoc#v19-145-0[Próximo Capítulo &#62;]