include::./index.adoc[]

[[v19-146-0]]
=== Salmos, 146
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-146-1]]

^<<v19-146-1,1>>^ Louvai ao Senhor. Ó minha alma, louva ao Senhor.

[[v19-146-2]]

^<<v19-146-2,2>>^ Louvarei ao Senhor durante a minha vida; cantarei louvores ao meu Deus enquanto viver.

[[v19-146-3]]

^<<v19-146-3,3>>^ Não confieis em príncipes, nem em filho de homem, em quem não há auxílio.

[[v19-146-4]]

^<<v19-146-4,4>>^ Sai-lhe o espírito, e ele volta para a terra; naquele mesmo dia perecem os seus pensamentos.

[[v19-146-5]]

^<<v19-146-5,5>>^ Bem-aventurado aquele que tem o Deus de Jacó por seu auxílio, e cuja esperança está no Senhor seu Deus

[[v19-146-6]]

^<<v19-146-6,6>>^ que fez os céus e a terra, o mar e tudo quanto neles há, e que guarda a verdade para sempre;

[[v19-146-7]]

^<<v19-146-7,7>>^ que faz justiça aos oprimidos, que dá pão aos famintos. O Senhor solta os encarcerados;

[[v19-146-8]]

^<<v19-146-8,8>>^ o Senhor abre os olhos aos cegos; o Senhor levanta os abatidos; o Senhor ama os justos.

[[v19-146-9]]

^<<v19-146-9,9>>^ O Senhor preserva os peregrinos; ampara o órfão e a viúva; mas transtorna o caminho dos ímpios.

[[v19-146-10]]

^<<v19-146-10,10>>^ O Senhor reinará eternamente: o teu Deus, ó Sião, reinará por todas as gerações. Louvai ao Senhor!

'''

xref:019-salmos/019-salmos-145.adoc#v19-145-0[&#60; Capítulo Anterior] | <<v19-146-0,Topo>> | xref:019-salmos/019-salmos-147.adoc#v19-147-0[Próximo Capítulo &#62;]