include::./index.adoc[]

[[v19-31-0]]
=== Salmos, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-31-1]]

^<<v19-31-1,1>>^ Em ti, Senhor, me refugio; nunca seja eu envergonhado; livra-me pela tua justiça!

[[v19-31-2]]

^<<v19-31-2,2>>^ Inclina para mim os teus ouvidos, livra-me depressa! Sê para mim uma rocha de refúgio, uma casa de defesa que me salve!

[[v19-31-3]]

^<<v19-31-3,3>>^ Porque tu és a minha rocha e a minha fortaleza; pelo que, por amor do teu nome, guia-me e encaminha-me.

[[v19-31-4]]

^<<v19-31-4,4>>^ Tira-me do laço que me armaram, pois tu és o meu refúgio.

[[v19-31-5]]

^<<v19-31-5,5>>^ Nas tuas mãos entrego o meu espírito; tu me remiste, ó Senhor, Deus da verdade.

[[v19-31-6]]

^<<v19-31-6,6>>^ Odeias aqueles que atentam para ídolos vãos; eu, porém, confio no Senhor.

[[v19-31-7]]

^<<v19-31-7,7>>^ Eu me alegrarei e regozijarei na tua benignidade, pois tens visto a minha aflição. Tens conhecido as minhas angústias,

[[v19-31-8]]

^<<v19-31-8,8>>^ e não me entregaste nas mãos do inimigo; puseste os meus pés num lugar espaçoso.

[[v19-31-9]]

^<<v19-31-9,9>>^ Tem compaixão de mim, ó Senhor, porque estou angustiado; consumidos estão de tristeza os meus olhos, a minha alma e o meu corpo.

[[v19-31-10]]

^<<v19-31-10,10>>^ Pois a minha vida está gasta de tristeza, e os meus anos de suspiros; a minha força desfalece por causa da minha iniqüidade, e os meus ossos se consomem.

[[v19-31-11]]

^<<v19-31-11,11>>^ Por causa de todos os meus adversários tornei-me em opróbrio, sim, sobremodo o sou para os meus vizinhos, e horror para os meus conhecidos; os que me vêem na rua fogem de mim.

[[v19-31-12]]

^<<v19-31-12,12>>^ Sou esquecido como um morto de quem não há memória; sou como um vaso quebrado.

[[v19-31-13]]

^<<v19-31-13,13>>^ Pois tenho ouvido a difamação de muitos, terror por todos os lados; enquanto juntamente conspiravam contra mim, maquinaram tirar-me a vida.

[[v19-31-14]]

^<<v19-31-14,14>>^ Mas eu confio em ti, ó Senhor; e digo: Tu és o meu Deus.

[[v19-31-15]]

^<<v19-31-15,15>>^ Os meus dias estão nas tuas mãos; livra-me das mãos dos meus inimigos e dos que me perseguem.

[[v19-31-16]]

^<<v19-31-16,16>>^ Faze resplandecer o teu rosto sobre o teu servo; salva-me por tua bondade.

[[v19-31-17]]

^<<v19-31-17,17>>^ Não seja eu envergonhado, ó Senhor, porque te invoco; envergonhados sejam os ímpios, emudeçam no Seol.

[[v19-31-18]]

^<<v19-31-18,18>>^ Emudeçam os lábios mentirosos, que falam insolentemente contra o justo, com arrogância e com desprezo.

[[v19-31-19]]

^<<v19-31-19,19>>^ Oh! quão grande é a tua bondade, que guardaste para os que te temem, a qual na presença dos filhos dos homens preparaste para aqueles que em ti se refugiam!

[[v19-31-20]]

^<<v19-31-20,20>>^ No abrigo da tua presença tu os escondes das intrigas dos homens; em um pavilhão os ocultas da contenda das línguas.

[[v19-31-21]]

^<<v19-31-21,21>>^ Bendito seja o Senhor, pois fez maravilhosa a sua bondade para comigo numa cidade sitiada.

[[v19-31-22]]

^<<v19-31-22,22>>^ Eu dizia no meu espanto: Estou cortado de diante dos teus olhos; não obstante, tu ouviste as minhas súplicas quando eu a ti clamei.

[[v19-31-23]]

^<<v19-31-23,23>>^ Amai ao Senhor, vós todos os que sois seus santos; o Senhor guarda os fiéis, e retribui abundantemente ao que usa de soberba.

[[v19-31-24]]

^<<v19-31-24,24>>^ Esforçai-vos, e fortaleça-se o vosso coração, vós todos os que esperais no Senhor.

'''

xref:019-salmos/019-salmos-030.adoc#v19-30-0[&#60; Capítulo Anterior] | <<v19-31-0,Topo>> | xref:019-salmos/019-salmos-032.adoc#v19-32-0[Próximo Capítulo &#62;]