include::./index.adoc[]

[[v19-106-0]]
=== Salmos, 106
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-106-1]]

^<<v19-106-1,1>>^ Louvai ao Senhor. Louvai ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.

[[v19-106-2]]

^<<v19-106-2,2>>^ Quem pode referir os poderosos feitos do Senhor, ou anunciar todo o seu louvor?

[[v19-106-3]]

^<<v19-106-3,3>>^ Bem-aventurados os que observam o direito, que praticam a justiça em todos os tempos.

[[v19-106-4]]

^<<v19-106-4,4>>^ Lembra-te de mim, Senhor, quando mostrares favor ao teu povo; visita-me com a tua salvação,

[[v19-106-5]]

^<<v19-106-5,5>>^ para que eu veja a prosperidade dos teus escolhidos, para que me alegre com a alegria da tua nação, e me glorie juntamente com a tua herança.

[[v19-106-6]]

^<<v19-106-6,6>>^ Nós pecamos, como nossos pais; cometemos a iniqüidade, andamos perversamente.

[[v19-106-7]]

^<<v19-106-7,7>>^ Nossos pais não atentaram para as tuas maravilhas no Egito, não se lembraram da multidão das tuas benignidades; antes foram rebeldes contra o Altíssimo junto ao Mar Vermelho.

[[v19-106-8]]

^<<v19-106-8,8>>^ Não obstante, ele os salvou por amor do seu nome, para fazer conhecido o seu poder.

[[v19-106-9]]

^<<v19-106-9,9>>^ Pois repreendeu o Mar Vermelho e este se secou; e os fez caminhar pelos abismos como pelo deserto.

[[v19-106-10]]

^<<v19-106-10,10>>^ Salvou-os da mão do adversário, livrou-os do poder do inimigo.

[[v19-106-11]]

^<<v19-106-11,11>>^ As águas, porém, cobriram os seus adversários; nem um só deles ficou.

[[v19-106-12]]

^<<v19-106-12,12>>^ Então creram nas palavras dele e cantaram-lhe louvor.

[[v19-106-13]]

^<<v19-106-13,13>>^ Cedo, porém, se esqueceram das suas obras; não esperaram pelo seu conselho;

[[v19-106-14]]

^<<v19-106-14,14>>^ mas deixaram-se levar pela cobiça no deserto, e tentaram a Deus no ermo.

[[v19-106-15]]

^<<v19-106-15,15>>^ E ele lhes deu o que pediram, mas fê-los definhar de doença.

[[v19-106-16]]

^<<v19-106-16,16>>^ Tiveram inveja de Moisés no acampamento, e de Arão, o santo do Senhor.

[[v19-106-17]]

^<<v19-106-17,17>>^ Abriu-se a terra, e engoliu a Datã, e cobriu a companhia de Abirão;

[[v19-106-18]]

^<<v19-106-18,18>>^ ateou-se um fogo no meio da congregação; e chama abrasou os ímpios.

[[v19-106-19]]

^<<v19-106-19,19>>^ Fizeram um bezerro em Horebe, e adoraram uma imagem de fundição.

[[v19-106-20]]

^<<v19-106-20,20>>^ Assim trocaram a sua glória pela figura de um boi que come erva.

[[v19-106-21]]

^<<v19-106-21,21>>^ Esqueceram-se de Deus seu Salvador, que fizera grandes coisas no Egito,

[[v19-106-22]]

^<<v19-106-22,22>>^ maravilhas na terra de Cam, coisas tremendas junto ao Mar Vermelho.

[[v19-106-23]]

^<<v19-106-23,23>>^ Pelo que os teria destruído, como dissera, se Moisés, seu escolhido, não se tivesse interposto diante dele, para desviar a sua indignação, a fim de que não os destruísse.

[[v19-106-24]]

^<<v19-106-24,24>>^ Também desprezaram a terra aprazível; não confiaram na sua promessa;

[[v19-106-25]]

^<<v19-106-25,25>>^ antes murmuraram em suas tendas e não deram ouvidos à voz do Senhor.

[[v19-106-26]]

^<<v19-106-26,26>>^ Pelo que levantou a sua mão contra eles, afirmando que os faria cair no deserto;

[[v19-106-27]]

^<<v19-106-27,27>>^ que dispersaria também a sua descendência entre as nações, e os espalharia pelas terras.

[[v19-106-28]]

^<<v19-106-28,28>>^ Também se apegaram a Baal-Peor, e comeram sacrifícios oferecidos aos mortos.

[[v19-106-29]]

^<<v19-106-29,29>>^ Assim o provocaram à ira com as suas ações; e uma praga rebentou entre eles.

[[v19-106-30]]

^<<v19-106-30,30>>^ Então se levantou Finéias, que executou o juízo; e cessou aquela praga.

[[v19-106-31]]

^<<v19-106-31,31>>^ E isto lhe foi imputado como justiça, de geração em geração, para sempre.

[[v19-106-32]]

^<<v19-106-32,32>>^ Indignaram-no também junto às águas de Meribá, de sorte que sucedeu mal a Moisés por causa deles;

[[v19-106-33]]

^<<v19-106-33,33>>^ porque amarguraram o seu espírito; e ele falou imprudentemente com seus lábios.

[[v19-106-34]]

^<<v19-106-34,34>>^ Não destruíram os povos, como o Senhor lhes ordenara;

[[v19-106-35]]

^<<v19-106-35,35>>^ antes se misturaram com as nações, e aprenderam as suas obras.

[[v19-106-36]]

^<<v19-106-36,36>>^ Serviram aos seus ídolos, que vieram a ser-lhes um laço;

[[v19-106-37]]

^<<v19-106-37,37>>^ sacrificaram seus filhos e suas filhas aos demônios;

[[v19-106-38]]

^<<v19-106-38,38>>^ e derramaram sangue inocente, o sangue de seus filhos e de suas filhas, que eles sacrificaram aos ídolos de Canaã; e a terra foi manchada com sangue.

[[v19-106-39]]

^<<v19-106-39,39>>^ Assim se contaminaram com as suas obras, e se prostituíram pelos seus feitos.

[[v19-106-40]]

^<<v19-106-40,40>>^ Pelo que se acendeu a ira do Senhor contra o seu povo, de modo que abominou a sua herança;

[[v19-106-41]]

^<<v19-106-41,41>>^ entregou-os nas mãos das nações, e aqueles que os odiavam dominavam sobre eles.

[[v19-106-42]]

^<<v19-106-42,42>>^ Os seus inimigos os oprimiram, e debaixo das mãos destes foram eles humilhados.

[[v19-106-43]]

^<<v19-106-43,43>>^ Muitas vezes os livrou; mas eles foram rebeldes nos seus desígnios, e foram abatidos pela sua iniqüidade.

[[v19-106-44]]

^<<v19-106-44,44>>^ Contudo, atentou para a sua aflição, quando ouviu o seu clamor;

[[v19-106-45]]

^<<v19-106-45,45>>^ e a favor deles lembrou-se do seu pacto, e aplacou-se, segundo a abundância da sua benignidade.

[[v19-106-46]]

^<<v19-106-46,46>>^ Por isso fez com que obtivessem compaixão da parte daqueles que os levaram cativos.

[[v19-106-47]]

^<<v19-106-47,47>>^ Salva-nos, Senhor, nosso Deus, e congrega-nos dentre as nações, para que louvemos o teu santo nome, e nos gloriemos no teu louvor.

[[v19-106-48]]

^<<v19-106-48,48>>^ Bendito seja o Senhor, Deus de Israel, de eternidade em eternidade! E diga todo o povo: Amém. Louvai ao Senhor.

'''

xref:019-salmos/019-salmos-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-salmos/019-salmos-107.adoc#v19-107-0[Próximo Capítulo &#62;]