include::./index.adoc[]

[[v19-19-0]]
=== Salmos, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-19-1]]

^<<v19-19-1,1>>^ Os céus proclamam a glória de Deus e o firmamento anuncia a obra das suas mãos.

[[v19-19-2]]

^<<v19-19-2,2>>^ Um dia faz declaração a outro dia, e uma noite revela conhecimento a outra noite.

[[v19-19-3]]

^<<v19-19-3,3>>^ Não há fala, nem palavras; não se lhes ouve a voz.

[[v19-19-4]]

^<<v19-19-4,4>>^ Por toda a terra estende-se a sua linha, e as suas palavras até os consfins do mundo. Neles pôs uma tenda para o sol,

[[v19-19-5]]

^<<v19-19-5,5>>^ que é qual noivo que sai do seu tálamo, e se alegra, como um herói, a correr a sua carreira.

[[v19-19-6]]

^<<v19-19-6,6>>^ A sua saída é desde uma extremidade dos céus, e o seu curso até a outra extremidade deles; e nada se esconde ao seu calor.

[[v19-19-7]]

^<<v19-19-7,7>>^ A lei do Senhor é perfeita, e refrigera a alma; o testemunho do Senhor é fiel, e dá sabedoria aos simples.

[[v19-19-8]]

^<<v19-19-8,8>>^ Os preceitos do Senhor são retos, e alegram o coração; o mandamento do Senhor é puro, e alumia os olhos.

[[v19-19-9]]

^<<v19-19-9,9>>^ O temor do Senhor é limpo, e permanece para sempre; os juízos do Senhor são verdadeiros e inteiramente justos.

[[v19-19-10]]

^<<v19-19-10,10>>^ Mais desejáveis são do que o ouro, sim, do que muito ouro fino; e mais doces do que o mel e o que goteja dos favos.

[[v19-19-11]]

^<<v19-19-11,11>>^ Também por eles o teu servo é advertido; e em os guardar há grande recompensa.

[[v19-19-12]]

^<<v19-19-12,12>>^ Quem pode discernir os próprios erros? Purifica-me tu dos que me são ocultos.

[[v19-19-13]]

^<<v19-19-13,13>>^ Também de pecados de presunção guarda o teu servo, para que não se assenhoreiem de mim; então serei perfeito, e ficarei limpo de grande transgressão.

[[v19-19-14]]

^<<v19-19-14,14>>^ Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor, Rocha minha e Redentor meu!

'''

xref:019-salmos/019-salmos-018.adoc#v19-18-0[&#60; Capítulo Anterior] | <<v19-19-0,Topo>> | xref:019-salmos/019-salmos-020.adoc#v19-20-0[Próximo Capítulo &#62;]