include::./index.adoc[]

[[v19-49-0]]
=== Salmos, 49
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-49-1]]

^<<v19-49-1,1>>^ Ouvi isto, vós todos os povos; inclinai os ouvidos, todos os habitantes do mundo,

[[v19-49-2]]

^<<v19-49-2,2>>^ quer humildes quer grandes, tanto ricos como pobres.

[[v19-49-3]]

^<<v19-49-3,3>>^ A minha boca falará a sabedoria, e a meditação do meu coração será de entendimento.

[[v19-49-4]]

^<<v19-49-4,4>>^ Inclinarei os meus ouvidos a uma parábola; decifrarei o meu enigma ao som da harpa.

[[v19-49-5]]

^<<v19-49-5,5>>^ Por que temeria eu nos dias da adversidade, ao cercar-me a iniqüidade dos meus perseguidores,

[[v19-49-6]]

^<<v19-49-6,6>>^ dos que confiam nos seus bens e se gloriam na multidão das suas riquezas?

[[v19-49-7]]

^<<v19-49-7,7>>^ Nenhum deles de modo algum pode remir a seu irmão, nem por ele dar um resgate a Deus,

[[v19-49-8]]

^<<v19-49-8,8>>^ &#123;pois a redenção da sua vida é caríssima, de sorte que os seus recursos não dariam;&#125;

[[v19-49-9]]

^<<v19-49-9,9>>^ para que continuasse a viver para sempre, e não visse a cova.

[[v19-49-10]]

^<<v19-49-10,10>>^ Sim, ele verá que até os sábios morrem, que perecem igualmente o néscio e o estúpido, e deixam a outros os seus bens.

[[v19-49-11]]

^<<v19-49-11,11>>^ O pensamento íntimo deles é que as suas casas são perpétuas e as suas habitações de geração em geração; dão às suas terras os seus próprios nomes.

[[v19-49-12]]

^<<v19-49-12,12>>^ Mas o homem, embora esteja em honra, não permanece; antes é como os animais que perecem.

[[v19-49-13]]

^<<v19-49-13,13>>^ Este é o destino dos que confiam em si mesmos; o fim dos que se satisfazem com as suas próprias palavras.

[[v19-49-14]]

^<<v19-49-14,14>>^ Como ovelhas são arrebanhados ao Seol; a morte os pastoreia; ao romper do dia os retos terão domínio sobre eles; e a sua formosura se consumirá no Seol, que lhes será por habitação.

[[v19-49-15]]

^<<v19-49-15,15>>^ Mas Deus remirá a minha alma do poder do Seol, pois me receberá.

[[v19-49-16]]

^<<v19-49-16,16>>^ Não temas quando alguém se enriquece, quando a glória da sua casa aumenta.

[[v19-49-17]]

^<<v19-49-17,17>>^ Pois, quando morrer, nada levará consigo; a sua glória não descerá após ele.

[[v19-49-18]]

^<<v19-49-18,18>>^ Ainda que ele, enquanto vivo, se considera feliz e os homens o louvam quando faz o bem a si mesmo,

[[v19-49-19]]

^<<v19-49-19,19>>^ ele irá ter com a geração de seus pais; eles nunca mais verão a luz

[[v19-49-20]]

^<<v19-49-20,20>>^ Mas o homem, embora esteja em honra, não permanece; antes é como os animais que perecem.

'''

xref:019-salmos/019-salmos-048.adoc#v19-48-0[&#60; Capítulo Anterior] | <<v19-49-0,Topo>> | xref:019-salmos/019-salmos-050.adoc#v19-50-0[Próximo Capítulo &#62;]