include::./index.adoc[]

[[v19-46-0]]
=== Salmos, 46
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-46-1]]

^<<v19-46-1,1>>^ Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.

[[v19-46-2]]

^<<v19-46-2,2>>^ Pelo que não temeremos, ainda que a terra se mude, e ainda que os montes se projetem para o meio dos mares;

[[v19-46-3]]

^<<v19-46-3,3>>^ ainda que as águas rujam e espumem, ainda que os montes se abalem pela sua braveza.

[[v19-46-4]]

^<<v19-46-4,4>>^ Há um rio cujas correntes alegram a cidade de Deus, o lugar santo das moradas do Altíssimo.

[[v19-46-5]]

^<<v19-46-5,5>>^ Deus está no meio dela; não será abalada; Deus a ajudará desde o raiar da alva.

[[v19-46-6]]

^<<v19-46-6,6>>^ Bramam nações, reinos se abalam; ele levanta a sua voz, e a terra se derrete.

[[v19-46-7]]

^<<v19-46-7,7>>^ O Senhor dos exércitos está conosco; o Deus de Jacó é o nosso refúgio.

[[v19-46-8]]

^<<v19-46-8,8>>^ Vinde contemplai as obras do Senhor, as desolações que tem feito na terra.

[[v19-46-9]]

^<<v19-46-9,9>>^ Ele faz cessar as guerras até os confins da terra; quebra o arco e corta a lança; queima os carros no fogo.

[[v19-46-10]]

^<<v19-46-10,10>>^ Aquietai-vos, e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra.

[[v19-46-11]]

^<<v19-46-11,11>>^ O Senhor dos exércitos está conosco; o Deus de Jacó é o nosso refúgio.

'''

xref:019-salmos/019-salmos-045.adoc#v19-45-0[&#60; Capítulo Anterior] | <<v19-46-0,Topo>> | xref:019-salmos/019-salmos-047.adoc#v19-47-0[Próximo Capítulo &#62;]