include::./index.adoc[]

[[v19-80-0]]
=== Salmos, 80
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-80-1]]

^<<v19-80-1,1>>^ Ó pastor de Israel, dá ouvidos; tu, que guias a José como a um rebanho, que estás entronizado sobre os querubins, resplandece.

[[v19-80-2]]

^<<v19-80-2,2>>^ Perante Efraim, Benjamim e Manassés, desperta o teu poder, e vem salvar-nos.

[[v19-80-3]]

^<<v19-80-3,3>>^ Reabilita-nos, ó Deus; faze resplandecer o teu rosto, para que sejamos salvos.

[[v19-80-4]]

^<<v19-80-4,4>>^ Ó Senhor Deus dos exércitos, até quando te indignarás contra a oração do teu povo?

[[v19-80-5]]

^<<v19-80-5,5>>^ Tu os alimentaste com pão de lágrimas, e lhes deste a beber lágrimas em abundância.

[[v19-80-6]]

^<<v19-80-6,6>>^ Tu nos fazes objeto de escárnio entre os nossos vizinhos; e os nossos inimigos zombam de nós entre si.

[[v19-80-7]]

^<<v19-80-7,7>>^ Reabilita-nos, ó Deus dos exércitos; faze resplandecer o teu rosto, para que sejamos salvos.

[[v19-80-8]]

^<<v19-80-8,8>>^ Trouxeste do Egito uma videira; lançaste fora as nações, e a plantaste.

[[v19-80-9]]

^<<v19-80-9,9>>^ Preparaste-lhe lugar; e ela deitou profundas raízes, e encheu a terra.

[[v19-80-10]]

^<<v19-80-10,10>>^ Os montes cobriram-se com a sua sombra, e os cedros de Deus com os seus ramos.

[[v19-80-11]]

^<<v19-80-11,11>>^ Ela estendeu a sua ramagem até o mar, e os seus rebentos até o Rio.

[[v19-80-12]]

^<<v19-80-12,12>>^ Por que lhe derrubaste as cercas, de modo que a vindimam todos os que passam pelo caminho?

[[v19-80-13]]

^<<v19-80-13,13>>^ O javali da selva a devasta, e as feras do campo alimentam-se dela.

[[v19-80-14]]

^<<v19-80-14,14>>^ Ó Deus dos exércitos, volta-te, nós te rogamos; atende do céu, e vê, e visita esta videira,

[[v19-80-15]]

^<<v19-80-15,15>>^ a videira que a tua destra plantou, e o sarmento que fortificaste para ti.

[[v19-80-16]]

^<<v19-80-16,16>>^ Está queimada pelo fogo, está cortada; eles perecem pela repreensão do teu rosto.

[[v19-80-17]]

^<<v19-80-17,17>>^ Seja a tua mão sobre o varão da tua destra, sobre o filho do homem que fortificaste para ti.

[[v19-80-18]]

^<<v19-80-18,18>>^ E não nos afastaremos de ti; vivifica-nos, e nós invocaremos o teu nome.

[[v19-80-19]]

^<<v19-80-19,19>>^ Reabilita-nos, Senhor Deus dos exércitos; faze resplandecer o teu rosto, para que sejamos salvos.

'''

xref:019-salmos/019-salmos-079.adoc#v19-79-0[&#60; Capítulo Anterior] | <<v19-80-0,Topo>> | xref:019-salmos/019-salmos-081.adoc#v19-81-0[Próximo Capítulo &#62;]