include::./index.adoc[]

[[v19-107-0]]
=== Salmos, 107
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-107-1]]

^<<v19-107-1,1>>^ Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre;

[[v19-107-2]]

^<<v19-107-2,2>>^ digam-no os remidos do Senhor, os quais ele remiu da mão do inimigo,

[[v19-107-3]]

^<<v19-107-3,3>>^ e os que congregou dentre as terras, do Oriente e do Ocidente, do Norte e do Sul.

[[v19-107-4]]

^<<v19-107-4,4>>^ Andaram desgarrados pelo deserto, por caminho ermo; não acharam cidade em que habitassem.

[[v19-107-5]]

^<<v19-107-5,5>>^ Andavam famintos e sedentos; desfalecia-lhes a alma.

[[v19-107-6]]

^<<v19-107-6,6>>^ E clamaram ao Senhor na sua tribulação, e ele os livrou das suas angústias;

[[v19-107-7]]

^<<v19-107-7,7>>^ conduziu-os por um caminho direito, para irem a uma cidade em que habitassem.

[[v19-107-8]]

^<<v19-107-8,8>>^ Dêem graças ao Senhor pela sua benignidade, e pelas suas maravilhas para com os filhos dos homens!

[[v19-107-9]]

^<<v19-107-9,9>>^ Pois ele satisfaz a alma sedenta, e enche de bens a alma faminta.

[[v19-107-10]]

^<<v19-107-10,10>>^ Quanto aos que se assentavam nas trevas e sombra da morte, presos em aflição e em ferros,

[[v19-107-11]]

^<<v19-107-11,11>>^ por se haverem rebelado contra as palavras de Deus, e desprezado o conselho do Altíssimo,

[[v19-107-12]]

^<<v19-107-12,12>>^ eis que lhes abateu o coração com trabalho; tropeçaram, e não houve quem os ajudasse.

[[v19-107-13]]

^<<v19-107-13,13>>^ Então clamaram ao Senhor na sua tribulação, e ele os livrou das suas angústias.

[[v19-107-14]]

^<<v19-107-14,14>>^ Tirou-os das trevas e da sombra da morte, e quebrou-lhes as prisões.

[[v19-107-15]]

^<<v19-107-15,15>>^ Dêem graças ao Senhor pela sua benignidade, e pelas suas maravilhas para com os filhos dos homens!

[[v19-107-16]]

^<<v19-107-16,16>>^ Pois quebrou as portas de bronze e despedaçou as trancas de ferro.

[[v19-107-17]]

^<<v19-107-17,17>>^ Os insensatos, por causa do seu caminho de transgressão, e por causa das suas iniqüidades, são afligidos.

[[v19-107-18]]

^<<v19-107-18,18>>^ A sua alma aborreceu toda sorte de comida, e eles chegaram até as portas da morte.

[[v19-107-19]]

^<<v19-107-19,19>>^ Então clamaram ao Senhor na sua tribulação, e ele os livrou das suas angústias.

[[v19-107-20]]

^<<v19-107-20,20>>^ Enviou a sua palavra, e os sarou, e os livrou da destruição.

[[v19-107-21]]

^<<v19-107-21,21>>^ Dêem graças ao Senhor pela sua benignidade, e pelas suas maravilhas para com os filhos dos homens!

[[v19-107-22]]

^<<v19-107-22,22>>^ Ofereçam sacrifícios de louvor, e relatem as suas obras com regozijo!

[[v19-107-23]]

^<<v19-107-23,23>>^ Os que descem ao mar em navios, os que fazem comércio nas grandes águas,

[[v19-107-24]]

^<<v19-107-24,24>>^ esses vêem as obras do Senhor, e as suas maravilhas no abismo.

[[v19-107-25]]

^<<v19-107-25,25>>^ Pois ele manda, e faz levantar o vento tempestuoso, que eleva as ondas do mar.

[[v19-107-26]]

^<<v19-107-26,26>>^ Eles sobem ao céu, descem ao abismo; esvaece-lhes a alma de aflição.

[[v19-107-27]]

^<<v19-107-27,27>>^ Balançam e cambaleiam como ébrios, e perdem todo o tino.

[[v19-107-28]]

^<<v19-107-28,28>>^ Então clamam ao Senhor na sua tribulação, e ele os livra das suas angústias.

[[v19-107-29]]

^<<v19-107-29,29>>^ Faz cessar a tormenta, de modo que se acalmam as ondas.

[[v19-107-30]]

^<<v19-107-30,30>>^ Então eles se alegram com a bonança; e assim ele os leva ao porto desejado.

[[v19-107-31]]

^<<v19-107-31,31>>^ Dêem graças ao Senhor pela sua benignidade, e pelas suas maravilhas para com os filhos dos homens!

[[v19-107-32]]

^<<v19-107-32,32>>^ Exaltem-no na congregação do povo, e louvem-no na assembléia dos anciãos!

[[v19-107-33]]

^<<v19-107-33,33>>^ Ele converte rios em deserto, e nascentes em terra sedenta;

[[v19-107-34]]

^<<v19-107-34,34>>^ a terra frutífera em deserto salgado, por causa da maldade dos que nela habitam.

[[v19-107-35]]

^<<v19-107-35,35>>^ Converte o deserto em lagos, e a terra seca em nascentes.

[[v19-107-36]]

^<<v19-107-36,36>>^ E faz habitar ali os famintos, que edificam uma cidade para sua habitação;

[[v19-107-37]]

^<<v19-107-37,37>>^ semeiam campos e plantam vinhas, que produzem frutos abundantes.

[[v19-107-38]]

^<<v19-107-38,38>>^ Ele os abençoa, de modo que se multiplicam sobremaneira; e não permite que o seu gado diminua.

[[v19-107-39]]

^<<v19-107-39,39>>^ Quando eles decrescem e são abatidos pela opressão, aflição e tristeza,

[[v19-107-40]]

^<<v19-107-40,40>>^ ele lança o desprezo sobre os príncipes, e os faz desgarrados pelo deserto, onde não há caminho.

[[v19-107-41]]

^<<v19-107-41,41>>^ Mas levanta da opressão o necessitado para um alto retiro, e dá-lhe famílias como um rebanho.

[[v19-107-42]]

^<<v19-107-42,42>>^ Os retos o vêem e se regozijam, e toda a iniqüidade tapa a sua própria boca.

[[v19-107-43]]

^<<v19-107-43,43>>^ Quem é sábio observe estas coisas, e considere atentamente as benignidades do Senhor.

'''

xref:019-salmos/019-salmos-106.adoc#v19-106-0[&#60; Capítulo Anterior] | <<v19-107-0,Topo>> | xref:019-salmos/019-salmos-108.adoc#v19-108-0[Próximo Capítulo &#62;]