include::./index.adoc[]

[[v19-25-0]]
=== Salmos, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-25-1]]

^<<v19-25-1,1>>^ A ti, Senhor, elevo a minha alma.

[[v19-25-2]]

^<<v19-25-2,2>>^ Deus meu, em ti confio; não seja eu envergonhado; não triunfem sobre mim os meus inimigos.

[[v19-25-3]]

^<<v19-25-3,3>>^ Não seja envergonhado nenhum dos que em ti esperam; envergonhados sejam os que sem causa procedem traiçoeiramente.

[[v19-25-4]]

^<<v19-25-4,4>>^ Faze-me saber os teus caminhos, Senhor; ensina-me as tuas veredas.

[[v19-25-5]]

^<<v19-25-5,5>>^ Guia-me na tua verdade, e ensina-me; pois tu és o Deus da minha salvação; por ti espero o dia todo.

[[v19-25-6]]

^<<v19-25-6,6>>^ Lembra-te, Senhor, da tua compaixão e da tua benignidade, porque elas são eternas.

[[v19-25-7]]

^<<v19-25-7,7>>^ Não te lembres dos pecado da minha mocidade, nem das minhas transgressões; mas, segundo a tua misericórdia, lembra-te de mim, pela tua bondade, ó Senhor.

[[v19-25-8]]

^<<v19-25-8,8>>^ Bom e reto é o Senhor; pelo que ensina o caminho aos pecadores.

[[v19-25-9]]

^<<v19-25-9,9>>^ Guia os mansos no que é reto, e lhes ensina o seu caminho.

[[v19-25-10]]

^<<v19-25-10,10>>^ Todas as veredas do Senhor são misericórdia e verdade para aqueles que guardam o seu pacto e os seus testemunhos.

[[v19-25-11]]

^<<v19-25-11,11>>^ Por amor do teu nome, Senhor, perdoa a minha iniqüidade, pois é grande.

[[v19-25-12]]

^<<v19-25-12,12>>^ Qual é o homem que teme ao Senhor? Este lhe ensinará o caminho que deve escolher.

[[v19-25-13]]

^<<v19-25-13,13>>^ Ele permanecerá em prosperidade, e a sua descendência herdará a terra.

[[v19-25-14]]

^<<v19-25-14,14>>^ O conselho do Senhor é para aqueles que o temem, e ele lhes faz saber o seu pacto.

[[v19-25-15]]

^<<v19-25-15,15>>^ Os meus olhos estão postos continuamente no Senhor, pois ele tirará do laço os meus pés.

[[v19-25-16]]

^<<v19-25-16,16>>^ Olha para mim, e tem misericórdia de mim, porque estou desamparado e aflito.

[[v19-25-17]]

^<<v19-25-17,17>>^ Alivia as tribulações do meu coração; tira-me das minhas angústias.

[[v19-25-18]]

^<<v19-25-18,18>>^ Olha para a minha aflição e para a minha dor, e perdoa todos os meus pecados.

[[v19-25-19]]

^<<v19-25-19,19>>^ Olha para os meus inimigos, porque são muitos e me odeiam com ódio cruel.

[[v19-25-20]]

^<<v19-25-20,20>>^ Guarda a minha alma, e livra-me; não seja eu envergonhado, porque em ti me refúgio.

[[v19-25-21]]

^<<v19-25-21,21>>^ A integridade e a retidão me protejam, porque em ti espero.

[[v19-25-22]]

^<<v19-25-22,22>>^ Redime, ó Deus, a Israel de todas as suas angústias.

'''

xref:019-salmos/019-salmos-024.adoc#v19-24-0[&#60; Capítulo Anterior] | <<v19-25-0,Topo>> | xref:019-salmos/019-salmos-026.adoc#v19-26-0[Próximo Capítulo &#62;]