include::./index.adoc[]

[[v19-83-0]]
=== Salmos, 83
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-83-1]]

^<<v19-83-1,1>>^ Ó Deus, não guardes silêncio; não te cales nem fiques impassível, ó Deus.

[[v19-83-2]]

^<<v19-83-2,2>>^ Pois eis que teus inimigos se alvoroçam, e os que te odeiam levantam a cabeça.

[[v19-83-3]]

^<<v19-83-3,3>>^ Astutamente formam conselho contra o teu povo, e conspiram contra os teus protegidos.

[[v19-83-4]]

^<<v19-83-4,4>>^ Dizem eles: Vinde, e apaguemo-los para que não sejam nação, nem seja lembrado mais o nome de Israel.

[[v19-83-5]]

^<<v19-83-5,5>>^ Pois à uma se conluiam; aliam-se contra ti

[[v19-83-6]]

^<<v19-83-6,6>>^ as tendas de Edom e os ismaelitas, Moabe e os hagarenos,

[[v19-83-7]]

^<<v19-83-7,7>>^ Gebal, Amom e Amaleque, e a Filístia com os habitantes de tiro.

[[v19-83-8]]

^<<v19-83-8,8>>^ Também a Assíria se ligou a eles; eles são o braço forte dos filhos de Ló.

[[v19-83-9]]

^<<v19-83-9,9>>^ Faze-lhes como fizeste a Midiã, como a Sísera, como a Jabim junto ao rio Quisom,

[[v19-83-10]]

^<<v19-83-10,10>>^ os quais foram destruídos em En-Dor; tornaram-se esterco para a terra.

[[v19-83-11]]

^<<v19-83-11,11>>^ Faze aos seus nobres como a Orebe e a Zeebe; e a todos os seus príncipes como a Zebá e a Zalmuna,

[[v19-83-12]]

^<<v19-83-12,12>>^ que disseram: Tomemos para nós as pastagens de Deus.

[[v19-83-13]]

^<<v19-83-13,13>>^ Deus meu, faze-os como um turbilhão de pó, como a palha diante do vento.

[[v19-83-14]]

^<<v19-83-14,14>>^ Como o fogo queima um bosque, e como a chama incedeia as montanhas,

[[v19-83-15]]

^<<v19-83-15,15>>^ assim persegue-os com a tua tempestade, e assombra-os com o teu furacão.

[[v19-83-16]]

^<<v19-83-16,16>>^ Cobre-lhes o rosto de confusão, de modo que busquem o teu nome, Senhor.

[[v19-83-17]]

^<<v19-83-17,17>>^ Sejam envergonhados e conturbados perpetuamente; sejam confundidos, e pereçam,

[[v19-83-18]]

^<<v19-83-18,18>>^ para que saibam que só tu, cujo nome é o Senhor, és o Altíssimo sobre toda a terra.

'''

xref:019-salmos/019-salmos-082.adoc#v19-82-0[&#60; Capítulo Anterior] | <<v19-83-0,Topo>> | xref:019-salmos/019-salmos-084.adoc#v19-84-0[Próximo Capítulo &#62;]