include::./index.adoc[]

[[v19-109-0]]
=== Salmos, 109
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-109-1]]

^<<v19-109-1,1>>^ Ó Deus do meu louvor, não te cales;

[[v19-109-2]]

^<<v19-109-2,2>>^ pois a boca do ímpio e a boca fraudulenta se abrem contra mim; falam contra mim com uma língua mentirosa.

[[v19-109-3]]

^<<v19-109-3,3>>^ Eles me cercam com palavras de ódio, e pelejam contra mim sem causa.

[[v19-109-4]]

^<<v19-109-4,4>>^ Em paga do meu amor são meus adversários; mas eu me dedico à oração.

[[v19-109-5]]

^<<v19-109-5,5>>^ Retribuem-me o mal pelo bem, e o ódio pelo amor.

[[v19-109-6]]

^<<v19-109-6,6>>^ Põe sobre ele um ímpio, e esteja à sua direita um acusador.

[[v19-109-7]]

^<<v19-109-7,7>>^ Quando ele for julgado, saia condenado; e em pecado se lhe torne a sua oração!

[[v19-109-8]]

^<<v19-109-8,8>>^ Sejam poucos os seus dias, e outro tome o seu ofício!

[[v19-109-9]]

^<<v19-109-9,9>>^ Fiquem órfãos os seus filhos, e viúva a sua mulher!

[[v19-109-10]]

^<<v19-109-10,10>>^ Andem errantes os seus filhos, e mendiguem; esmolem longe das suas habitações assoladas.

[[v19-109-11]]

^<<v19-109-11,11>>^ O credor lance mão de tudo quanto ele tenha, e despojem-no os estranhos do fruto do seu trabalho!

[[v19-109-12]]

^<<v19-109-12,12>>^ Não haja ninguém que se compadeça dele, nem haja quem tenha pena dos seus órfãos!

[[v19-109-13]]

^<<v19-109-13,13>>^ Seja extirpada a sua posteridade; o seu nome seja apagado na geração seguinte!

[[v19-109-14]]

^<<v19-109-14,14>>^ Esteja na memória do Senhor a iniqüidade de seus pais; e não se apague o pecado de sua mãe!

[[v19-109-15]]

^<<v19-109-15,15>>^ Antes estejam sempre perante o Senhor, para que ele faça desaparecer da terra a memória deles!

[[v19-109-16]]

^<<v19-109-16,16>>^ Porquanto não se lembrou de usar de benignidade; antes perseguiu o varão aflito e o necessitado, como também o quebrantado de coração, para o matar.

[[v19-109-17]]

^<<v19-109-17,17>>^ Visto que amou a maldição, que ela lhe sobrevenha! Como não desejou a bênção, que ela se afaste dele!

[[v19-109-18]]

^<<v19-109-18,18>>^ Assim como se vestiu de maldição como dum vestido, assim penetre ela nas suas entranhas como água, e em seus ossos como azeite!

[[v19-109-19]]

^<<v19-109-19,19>>^ Seja para ele como o vestido com que ele se cobre, e como o cinto com que sempre anda cingido!

[[v19-109-20]]

^<<v19-109-20,20>>^ Seja este, da parte do Senhor, o galardão dos meus adversários, e dos que falam mal contra mim!

[[v19-109-21]]

^<<v19-109-21,21>>^ Mas tu, ó Deus, meu Senhor age em meu favor por amor do teu nome; pois que é boa a tua benignidade, livra-me;

[[v19-109-22]]

^<<v19-109-22,22>>^ pois sou pobre e necessitado, e dentro de mim está ferido o meu coração.

[[v19-109-23]]

^<<v19-109-23,23>>^ Eis que me vou como a sombra que declina; sou arrebatado como o gafanhoto.

[[v19-109-24]]

^<<v19-109-24,24>>^ Os meus joelhos estão enfraquecidos pelo jejum, e a minha carne perde a sua gordura.

[[v19-109-25]]

^<<v19-109-25,25>>^ Eu sou para eles objeto de opróbrio; ao me verem, meneiam a cabeça.

[[v19-109-26]]

^<<v19-109-26,26>>^ Ajuda-me, Senhor, Deus meu; salva-me segundo a tua benignidade.

[[v19-109-27]]

^<<v19-109-27,27>>^ Saibam que nisto está a tua mão, e que tu, Senhor, o fizeste.

[[v19-109-28]]

^<<v19-109-28,28>>^ Amaldiçoem eles, mas abençoa tu; fiquem confundidos os meus adversários; mas alegre-se o teu servo!

[[v19-109-29]]

^<<v19-109-29,29>>^ Vistam-se de ignomínia os meus acusadores, e cubram-se da sua própria vergonha como dum manto!

[[v19-109-30]]

^<<v19-109-30,30>>^ Muitas graças darei ao Senhor com a minha boca;

[[v19-109-31]]

^<<v19-109-31,31>>^ Pois ele se coloca à direita do poder, para o salvar dos que o condenam.

'''

xref:019-salmos/019-salmos-108.adoc#v19-108-0[&#60; Capítulo Anterior] | <<v19-109-0,Topo>> | xref:019-salmos/019-salmos-110.adoc#v19-110-0[Próximo Capítulo &#62;]