include::./index.adoc[]

[[v19-65-0]]
=== Salmos, 65
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-65-1]]

^<<v19-65-1,1>>^ A ti, ó Deus, é devido o louvor em Sião; e a ti se pagará o voto.

[[v19-65-2]]

^<<v19-65-2,2>>^ Ó tu que ouves a oração! a ti virá toda a carne.

[[v19-65-3]]

^<<v19-65-3,3>>^ Prevalecem as iniqüidades contra mim; mas as nossas transgressões, tu as perdoarás.

[[v19-65-4]]

^<<v19-65-4,4>>^ Bem-aventurado aquele a quem tu escolhes, e fazes chegar a ti, para habitar em teus átrios! Nós seremos satisfeitos com a bondade da tua casa, do teu santo templo.

[[v19-65-5]]

^<<v19-65-5,5>>^ Com prodígios nos respondes em justiça, ó Deus da nossa salvação, a esperança de todas as extremidades da terra, e do mais remoto mar;

[[v19-65-6]]

^<<v19-65-6,6>>^ tu que pela tua força consolidas os montes, cingido de poder;

[[v19-65-7]]

^<<v19-65-7,7>>^ que aplacas o ruído dos mares, o ruído das suas ondas, e o tumulto dos povos.

[[v19-65-8]]

^<<v19-65-8,8>>^ Os que habitam os confins da terra são tomados de medo à vista dos teus sinais; tu fazes exultar de júbilo as saídas da manhã e da tarde.

[[v19-65-9]]

^<<v19-65-9,9>>^ Tu visitas a terra, e a regas; grandemente e enriqueces; o rio de Deus está cheio d'água; tu lhe dás o trigo quando assim a tens preparado;

[[v19-65-10]]

^<<v19-65-10,10>>^ enches d'água os seus sulcos, aplanando-lhes as leivas, amolecendo-a com a chuva, e abençoando as suas novidades.

[[v19-65-11]]

^<<v19-65-11,11>>^ Coroas o ano com a tua bondade, e as tuas veredas destilam gordura;

[[v19-65-12]]

^<<v19-65-12,12>>^ destilam sobre as pastagens do deserto, e os outeiros se cingem de alegria.

[[v19-65-13]]

^<<v19-65-13,13>>^ As pastagens revestem-se de rebanhos, e os vales se cobrem de trigo; por isso eles se regozijam, por isso eles cantam.

'''

xref:019-salmos/019-salmos-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-salmos/019-salmos-066.adoc#v19-66-0[Próximo Capítulo &#62;]