include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-53-1]]

^<<v19-53-1,1>>^ Diz o néscio no seu coração: Não há Deus. Corromperam-se e cometeram abominável iniqüidade; não há quem faça o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Deus olha lá dos céus para os filhos dos homens, para ver se há algum que tenha entendimento, que busque a Deus.

[[v19-53-3]]

^<<v19-53-3,3>>^ Desviaram-se todos, e juntamente se fizeram imundos; não há quem faça o bem, não há sequer um.

[[v19-53-4]]

^<<v19-53-4,4>>^ Acaso não têm conhecimento os que praticam a iniqüidade, os quais comem o meu povo como se comessem pão, e não invocam a Deus?

[[v19-53-5]]

^<<v19-53-5,5>>^ Eis que eles se acham em grande pavor onde não há motivo de pavor, porque Deus espalhará os ossos daqueles que se acampam contra ti; tu os confundirás, porque Deus os rejeitou.

[[v19-53-6]]

^<<v19-53-6,6>>^ Oxalá que de Sião viesse a salvação de Israel! Quando Deus fizer voltar os cativos do seu povo, então se regozijará Jacó e se alegrará Israel.

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]