include::./index.adoc[]

[[v19-36-0]]
=== Salmos, 36
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-36-1]]

^<<v19-36-1,1>>^ A transgressão fala ao ímpio no íntimo do seu coração; não há temor de Deus perante os seus olhos.

[[v19-36-2]]

^<<v19-36-2,2>>^ Porque em seus próprios olhos se lisonjeia, cuidando que a sua iniqüidade não será descoberta e detestada.

[[v19-36-3]]

^<<v19-36-3,3>>^ As palavras da sua boca são malícia e engano; deixou de ser prudente e de fazer o bem.

[[v19-36-4]]

^<<v19-36-4,4>>^ Maquina o mal na sua cama; põe-se em caminho que não é bom; não odeia o mal.

[[v19-36-5]]

^<<v19-36-5,5>>^ A tua benignidade, Senhor, chega até os céus, e a tua fidelidade até as nuvens.

[[v19-36-6]]

^<<v19-36-6,6>>^ A tua justiça é como os montes de Deus, os teus juízos são como o abismo profundo. Tu, Senhor, preservas os homens e os animais.

[[v19-36-7]]

^<<v19-36-7,7>>^ Quão preciosa é, ó Deus, a tua benignidade! Os filhos dos homens se refugiam à sombra das tuas asas.

[[v19-36-8]]

^<<v19-36-8,8>>^ Eles se fartarão da gordura da tua casa, e os farás beber da corrente das tuas delícias;

[[v19-36-9]]

^<<v19-36-9,9>>^ pois em ti está o manancial da vida; na tua luz vemos a luz.

[[v19-36-10]]

^<<v19-36-10,10>>^ Continua a tua benignidade aos que te conhecem, e a tua justiça aos retos de coração.

[[v19-36-11]]

^<<v19-36-11,11>>^ Não venha sobre mim o pé da soberba, e não me mova a mão dos ímpios.

[[v19-36-12]]

^<<v19-36-12,12>>^ Ali caídos estão os que praticavam a iniqüidade; estão derrubados, e não se podem levantar.

'''

xref:019-salmos/019-salmos-035.adoc#v19-35-0[&#60; Capítulo Anterior] | <<v19-36-0,Topo>> | xref:019-salmos/019-salmos-037.adoc#v19-37-0[Próximo Capítulo &#62;]