include::./index.adoc[]

[[v19-77-0]]
=== Salmos, 77
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-77-1]]

^<<v19-77-1,1>>^ Levanto a Deus a minha voz; a Deus levanto a minha voz, para que ele me ouça.

[[v19-77-2]]

^<<v19-77-2,2>>^ No dia da minha angústia busco ao Senhor; de noite a minha mão fica estendida e não se cansa; a minha alma recusa ser consolada.

[[v19-77-3]]

^<<v19-77-3,3>>^ Lembro-me de Deus, e me lamento; queixo-me, e o meu espírito desfalece.

[[v19-77-4]]

^<<v19-77-4,4>>^ Conservas vigilantes os meus olhos; estou tão perturbado que não posso falar.

[[v19-77-5]]

^<<v19-77-5,5>>^ Considero os dias da antigüidade, os anos dos tempos passados.

[[v19-77-6]]

^<<v19-77-6,6>>^ De noite lembro-me do meu cântico; consulto com o meu coração, e examino o meu espírito.

[[v19-77-7]]

^<<v19-77-7,7>>^ Rejeitará o Senhor para sempre e não tornará a ser favorável?

[[v19-77-8]]

^<<v19-77-8,8>>^ Cessou para sempre a sua benignidade? Acabou-se a sua promessa para todas as gerações

[[v19-77-9]]

^<<v19-77-9,9>>^ Esqueceu-se Deus de ser compassivo? Ou na sua ira encerrou ele as suas ternas misericórdias?

[[v19-77-10]]

^<<v19-77-10,10>>^ E eu digo: Isto é minha enfermidade; acaso se mudou a destra do Altíssimo?

[[v19-77-11]]

^<<v19-77-11,11>>^ Recordarei os feitos do Senhor; sim, me lembrarei das tuas maravilhas da antigüidade.

[[v19-77-12]]

^<<v19-77-12,12>>^ Meditarei também em todas as tuas obras, e ponderarei os teus feitos poderosos

[[v19-77-13]]

^<<v19-77-13,13>>^ O teu caminho, ó Deus, é em santidade; que deus é grande como o nosso Deus?

[[v19-77-14]]

^<<v19-77-14,14>>^ Tu és o Deus que fazes maravilhas; tu tens feito notória a tua força entre os povos.

[[v19-77-15]]

^<<v19-77-15,15>>^ Com o teu braço remiste o teu povo, os filhos de Jacó e de José.

[[v19-77-16]]

^<<v19-77-16,16>>^ As águas te viram, ó Deus, as águas te viram, e tremeram; os abismos também se abalaram.

[[v19-77-17]]

^<<v19-77-17,17>>^ As nuvens desfizeram-se em água; os céus retumbaram; as tuas flechas também correram de uma para outra parte.

[[v19-77-18]]

^<<v19-77-18,18>>^ A voz do teu trovão estava no redemoinho; os relâmpagos alumiaram o mundo; a terra se abalou e tremeu.

[[v19-77-19]]

^<<v19-77-19,19>>^ Pelo mar foi teu caminho, e tuas veredas pelas grandes águas; e as tuas pegadas não foram conhecidas.

[[v19-77-20]]

^<<v19-77-20,20>>^ Guiaste o teu povo, como a um rebanho, pela mão de Moisés e de Arão.

'''

xref:019-salmos/019-salmos-076.adoc#v19-76-0[&#60; Capítulo Anterior] | <<v19-77-0,Topo>> | xref:019-salmos/019-salmos-078.adoc#v19-78-0[Próximo Capítulo &#62;]