include::./index.adoc[]

[[v19-7-0]]
=== Salmos, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-7-1]]

^<<v19-7-1,1>>^ Senhor, Deus meu, confio, salva-me de todo o que me persegue, e livra-me;

[[v19-7-2]]

^<<v19-7-2,2>>^ para que ele não me arrebate, qual leão, despedaçando-me, sem que haja quem acuda.

[[v19-7-3]]

^<<v19-7-3,3>>^ Senhor, Deus meu, se eu fiz isto, se há perversidade nas minhas mãos,

[[v19-7-4]]

^<<v19-7-4,4>>^ se paguei com o mal àquele que tinha paz comigo, ou se despojei o meu inimigo sem causa.

[[v19-7-5]]

^<<v19-7-5,5>>^ persiga-me o inimigo e alcance-me; calque aos pés a minha vida no chão, e deite no pó a minha glória.

[[v19-7-6]]

^<<v19-7-6,6>>^ Ergue-te, Senhor, na tua ira; levanta-te contra o furor dos meus inimigos; desperta-te, meu Deus, pois tens ordenado o juízo.

[[v19-7-7]]

^<<v19-7-7,7>>^ Reúna-se ao redor de ti a assembléia dos povos, e por cima dela remonta-te ao alto.

[[v19-7-8]]

^<<v19-7-8,8>>^ O Senhor julga os povos; julga-me, Senhor, de acordo com a minha justiça e conforme a integridade que há em mim.

[[v19-7-9]]

^<<v19-7-9,9>>^ Cesse a maldade dos ímpios, mas estabeleça-se o justo; pois tu, ó justo Deus, provas o coração e os rins.

[[v19-7-10]]

^<<v19-7-10,10>>^ O meu escudo está em Deus, que salva os retos de coração.

[[v19-7-11]]

^<<v19-7-11,11>>^ Deus é um juiz justo, um Deus que sente indignação todos os dias.

[[v19-7-12]]

^<<v19-7-12,12>>^ Se o homem não se arrepender, Deus afiará a sua espada; armado e teso está o seu arco;

[[v19-7-13]]

^<<v19-7-13,13>>^ já preparou armas mortíferas, fazendo suas setas inflamadas.

[[v19-7-14]]

^<<v19-7-14,14>>^ Eis que o mau está com dores de perversidade; concedeu a malvadez, e dará à luz a falsidade.

[[v19-7-15]]

^<<v19-7-15,15>>^ Abre uma cova, aprofundando-a, e cai na cova que fez.

[[v19-7-16]]

^<<v19-7-16,16>>^ A sua malvadez recairá sobre a sua cabeça, e a sua violência descerá sobre o seu crânio.

[[v19-7-17]]

^<<v19-7-17,17>>^ Eu louvarei ao Senhor segundo a sua justiça, e cantarei louvores ao nome do Senhor, o Altíssimo.

'''

xref:019-salmos/019-salmos-006.adoc#v19-6-0[&#60; Capítulo Anterior] | <<v19-7-0,Topo>> | xref:019-salmos/019-salmos-008.adoc#v19-8-0[Próximo Capítulo &#62;]