include::./index.adoc[]

[[v19-12-0]]
=== Salmos, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-12-1]]

^<<v19-12-1,1>>^ Salva-nos, Senhor, pois não existe mais o piedoso; os fiéis desapareceram dentre os filhos dos homens.

[[v19-12-2]]

^<<v19-12-2,2>>^ Cada um fala com falsidade ao seu próximo; falam com lábios lisonjeiros e coração dobre.

[[v19-12-3]]

^<<v19-12-3,3>>^ Corte o Senhor todos os lábios lisonjeiros e a língua que fala soberbamente,

[[v19-12-4]]

^<<v19-12-4,4>>^ os que dizem: Com a nossa língua prevaleceremos; os nossos lábios a nós nos pertencem; quem sobre nós é senhor?

[[v19-12-5]]

^<<v19-12-5,5>>^ Por causa da opressão dos pobres, e do gemido dos necessitados, levantar-me-ei agora, diz o Senhor; porei em segurança quem por ela suspira.

[[v19-12-6]]

^<<v19-12-6,6>>^ As palavras do Senhor são palavras puras, como prata refinada numa fornalha de barro, purificada sete vezes.

[[v19-12-7]]

^<<v19-12-7,7>>^ Guarda-nos, ó Senhor; desta geração defende-nos para sempre.

[[v19-12-8]]

^<<v19-12-8,8>>^ Os ímpios andam por toda parte, quando a vileza se exalta entre os filhos dos homens.

'''

xref:019-salmos/019-salmos-011.adoc#v19-11-0[&#60; Capítulo Anterior] | <<v19-12-0,Topo>> | xref:019-salmos/019-salmos-013.adoc#v19-13-0[Próximo Capítulo &#62;]