include::./index.adoc[]

[[v19-140-0]]
=== Salmos, 140
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-140-1]]

^<<v19-140-1,1>>^ Livra-me, ó Senhor, dos homens maus; guarda-me dos homens violentos,

[[v19-140-2]]

^<<v19-140-2,2>>^ os quais maquinam maldades no coração; estão sempre projetando guerras.

[[v19-140-3]]

^<<v19-140-3,3>>^ Aguçaram as línguas como a serpente; peçonha de áspides está debaixo dos seus lábios.

[[v19-140-4]]

^<<v19-140-4,4>>^ Guarda-me, ó Senhor, das mãos dos ímpios; preserva-me dos homens violentos, os quais planejaram transtornar os meus passos.

[[v19-140-5]]

^<<v19-140-5,5>>^ Os soberbos armaram-me laços e cordas; estenderam uma rede à beira do caminho; puseram-me armadilhas.

[[v19-140-6]]

^<<v19-140-6,6>>^ Eu disse, ao Senhor: Tu és o meu Deus; dá ouvidos, ó Senhor, à voz das minhas súplicas.

[[v19-140-7]]

^<<v19-140-7,7>>^ Ó Senhor, meu Senhor, meu forte libertador, tu cobriste a minha cabeça no dia da batalha.

[[v19-140-8]]

^<<v19-140-8,8>>^ Não concedas, ó Senhor, aos ímpios os seus desejos; não deixes ir por diante o seu mau propósito.

[[v19-140-9]]

^<<v19-140-9,9>>^ Não levantem a cabeça os que me cercam; cubra-os a maldade dos seus lábios.

[[v19-140-10]]

^<<v19-140-10,10>>^ Caiam sobre eles brasas vivas; sejam lançados em covas profundas, para que não se tornem a levantar!

[[v19-140-11]]

^<<v19-140-11,11>>^ Não se estabeleça na terra o caluniador; o mal persiga o homem violento com golpe sobre golpe.

[[v19-140-12]]

^<<v19-140-12,12>>^ Sei que o Senhor manterá a causa do aflito, e o direito do necessitado.

[[v19-140-13]]

^<<v19-140-13,13>>^ Decerto os justos louvarão o teu nome; os retos habitarão na tua presença.

'''

xref:019-salmos/019-salmos-139.adoc#v19-139-0[&#60; Capítulo Anterior] | <<v19-140-0,Topo>> | xref:019-salmos/019-salmos-141.adoc#v19-141-0[Próximo Capítulo &#62;]