include::./index.adoc[]

[[v19-60-0]]
=== Salmos, 60
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-60-1]]

^<<v19-60-1,1>>^ Ó Deus, tu nos rejeitaste, tu nos esmagaste, tu tens estado indignado; oh, restabelece-nos.

[[v19-60-2]]

^<<v19-60-2,2>>^ Abalaste a terra, e a fendeste; sara as suas fendas, pois ela treme.

[[v19-60-3]]

^<<v19-60-3,3>>^ Ao teu povo fizeste ver duras coisas; fizeste-nos beber o vinho de aturdimento.

[[v19-60-4]]

^<<v19-60-4,4>>^ Deste um estandarte aos que te temem, para o qual possam fugir de diante do arco.

[[v19-60-5]]

^<<v19-60-5,5>>^ Para que os teus amados sejam livres, salva-nos com a tua destra, e responde-nos.

[[v19-60-6]]

^<<v19-60-6,6>>^ Deus falou na sua santidade: Eu exultarei; repartirei Siquém e medirei o vale de Sucote.

[[v19-60-7]]

^<<v19-60-7,7>>^ Meu é Gileade, e meu é Manassés; Efraim é o meu capacete; Judá é o meu cetro.

[[v19-60-8]]

^<<v19-60-8,8>>^ Moabe é a minha bacia de lavar; sobre Edom lançarei o meu sapato; sobre a Filístia darei o brado de vitória.

[[v19-60-9]]

^<<v19-60-9,9>>^ Quem me conduzirá à cidade forte? Quem me guiará até Edom?

[[v19-60-10]]

^<<v19-60-10,10>>^ Não nos rejeitaste, ó Deus? e tu, ó Deus, não deixaste de sair com os nossos exércitos?

[[v19-60-11]]

^<<v19-60-11,11>>^ Dá-nos auxílio contra o adversário, pois vão é o socorro da parte do homem.

[[v19-60-12]]

^<<v19-60-12,12>>^ Em Deus faremos proezas; porque é ele quem calcará aos pés os nossos inimigos.

'''

xref:019-salmos/019-salmos-059.adoc#v19-59-0[&#60; Capítulo Anterior] | <<v19-60-0,Topo>> | xref:019-salmos/019-salmos-061.adoc#v19-61-0[Próximo Capítulo &#62;]