include::./index.adoc[]

[[v19-26-0]]
=== Salmos, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-26-1]]

^<<v19-26-1,1>>^ Julga-me, ó Senhor, pois tenho andado na minha integridade; no Senhor tenho confiado sem vacilar.

[[v19-26-2]]

^<<v19-26-2,2>>^ Examina-me, Senhor, e prova-me; esquadrinha o meu coração e a minha mente.

[[v19-26-3]]

^<<v19-26-3,3>>^ Pois a tua benignidade está diante dos meus olhos, e tenho andado na tua verdade.

[[v19-26-4]]

^<<v19-26-4,4>>^ Não me tenho assentado com homens falsos, nem associo com dissimuladores.

[[v19-26-5]]

^<<v19-26-5,5>>^ Odeio o ajuntamento de malfeitores; não me sentarei com os ímpios.

[[v19-26-6]]

^<<v19-26-6,6>>^ Lavo as minhas mãos na inocência; e assim, ó Senhor, me acerco do teu altar,

[[v19-26-7]]

^<<v19-26-7,7>>^ para fazer ouvir a voz de louvor, e contar todas as tuas maravilhas.

[[v19-26-8]]

^<<v19-26-8,8>>^ Senhor, eu amo o recinto da tua casa e o lugar onde permanece a tua glória.

[[v19-26-9]]

^<<v19-26-9,9>>^ Não colhas a minha alma com a dos pecadores, nem a minha vida a dos homens sanguinolentos,

[[v19-26-10]]

^<<v19-26-10,10>>^ em cujas mãos há malefício, e cuja destra está cheia de subornos.

[[v19-26-11]]

^<<v19-26-11,11>>^ Quanto a mim, porém, ando na minha integridade; resgata-me e tem compaixão de mim.

[[v19-26-12]]

^<<v19-26-12,12>>^ O meu pé está firme em terreno plano; nas congregações bendirei ao Senhor.

'''

xref:019-salmos/019-salmos-025.adoc#v19-25-0[&#60; Capítulo Anterior] | <<v19-26-0,Topo>> | xref:019-salmos/019-salmos-027.adoc#v19-27-0[Próximo Capítulo &#62;]