include::./index.adoc[]

[[v19-47-0]]
=== Salmos, 47
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-47-1]]

^<<v19-47-1,1>>^ Batei palmas, todos os povos; aclamai a Deus com voz de júbilo.

[[v19-47-2]]

^<<v19-47-2,2>>^ Porque o Senhor Altíssimo é tremendo; é grande Rei sobre toda a terra.

[[v19-47-3]]

^<<v19-47-3,3>>^ Ele nos sujeitou povos e nações sob os nossos pés.

[[v19-47-4]]

^<<v19-47-4,4>>^ Escolheu para nós a nossa herança, a glória de Jacó, a quem amou.

[[v19-47-5]]

^<<v19-47-5,5>>^ Deus subiu entre aplausos, o Senhor subiu ao som de trombeta.

[[v19-47-6]]

^<<v19-47-6,6>>^ Cantai louvores a Deus, cantai louvores; cantai louvores ao nosso Rei, cantai louvores.

[[v19-47-7]]

^<<v19-47-7,7>>^ Pois Deus é o Rei de toda a terra; cantai louvores com salmo.

[[v19-47-8]]

^<<v19-47-8,8>>^ Deus reina sobre as nações; Deus está sentado sobre o seu santo trono.

[[v19-47-9]]

^<<v19-47-9,9>>^ Os príncipes dos povos se reúnem como povo do Deus de Abraão, porque a Deus pertencem os escudos da terra; ele é sumamente exaltado.

'''

xref:019-salmos/019-salmos-046.adoc#v19-46-0[&#60; Capítulo Anterior] | <<v19-47-0,Topo>> | xref:019-salmos/019-salmos-048.adoc#v19-48-0[Próximo Capítulo &#62;]