include::./index.adoc[]

[[v19-30-0]]
=== Salmos, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-30-1]]

^<<v19-30-1,1>>^ Exaltar-te-ei, ó Senhor, porque tu me levantaste, e não permitiste que meus inimigos se alegrassem sobre mim.

[[v19-30-2]]

^<<v19-30-2,2>>^ Ó Senhor, Deus meu, a ti clamei, e tu me curaste.

[[v19-30-3]]

^<<v19-30-3,3>>^ Senhor, fizeste subir a minha alma do Seol, conservaste-me a vida, dentre os que descem à cova.

[[v19-30-4]]

^<<v19-30-4,4>>^ Cantai louvores ao Senhor, vós que sois seus santos, e louvai o seu santo nome.

[[v19-30-5]]

^<<v19-30-5,5>>^ Porque a sua ira dura só um momento; no seu favor está a vida. O choro pode durar uma noite; pela manhã, porém, vem o cântico de júbilo.

[[v19-30-6]]

^<<v19-30-6,6>>^ Quanto a mim, dizia eu na minha prosperidade: Jamais serei abalado.

[[v19-30-7]]

^<<v19-30-7,7>>^ Tu, Senhor, pelo teu favor fizeste que a minha montanha permanecesse forte; ocultaste o teu rosto, e fiquei conturbado.

[[v19-30-8]]

^<<v19-30-8,8>>^ A ti, Senhor, clamei, e ao Senhor supliquei:

[[v19-30-9]]

^<<v19-30-9,9>>^ Que proveito haverá no meu sangue, se eu descer à cova? Porventura te louvará o pó? Anunciará ele a tua verdade?

[[v19-30-10]]

^<<v19-30-10,10>>^ Ouve, Senhor, e tem compaixão de mim! O Senhor, sê o meu ajudador!

[[v19-30-11]]

^<<v19-30-11,11>>^ Tornaste o meu pranto em regozijo, tiraste o meu cilício, e me cingiste de alegria;

[[v19-30-12]]

^<<v19-30-12,12>>^ para que a minha alma te cante louvores, e não se cale. Senhor, Deus meu, eu te louvarei para sempre.

'''

xref:019-salmos/019-salmos-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-salmos/019-salmos-031.adoc#v19-31-0[Próximo Capítulo &#62;]