include::./index.adoc[]

[[v19-51-0]]
=== Salmos, 51
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-51-1]]

^<<v19-51-1,1>>^ Compadece-te de mim, ó Deus, segundo a tua benignidade; apaga as minhas tansgressões, segundo a multidão das tuas misericórdias.

[[v19-51-2]]

^<<v19-51-2,2>>^ Lava-me completamente da minha iniqüidade, e purifica-me do meu pecado.

[[v19-51-3]]

^<<v19-51-3,3>>^ Pois eu conheço as minhas transgressões, e o meu pecado está sempre diante de mim.

[[v19-51-4]]

^<<v19-51-4,4>>^ Contra ti, contra ti somente, pequei, e fiz o que é mau diante dos teus olhos; de sorte que és justificado em falares, e inculpável em julgares.

[[v19-51-5]]

^<<v19-51-5,5>>^ Eis que eu nasci em iniqüidade, e em pecado me concedeu minha mãe.

[[v19-51-6]]

^<<v19-51-6,6>>^ Eis que desejas que a verdade esteja no íntimo; faze-me, pois, conhecer a sabedoria no secreto da minha alma.

[[v19-51-7]]

^<<v19-51-7,7>>^ Purifica-me com hissopo, e ficarei limpo; lava-me, e ficarei mais alvo do que a neve.

[[v19-51-8]]

^<<v19-51-8,8>>^ Faze-me ouvir júbilo e alegria, para que se regozijem os ossos que esmagaste.

[[v19-51-9]]

^<<v19-51-9,9>>^ Esconde o teu rosto dos meus pecados, e apaga todas as minhas iniqüidades.

[[v19-51-10]]

^<<v19-51-10,10>>^ Cria em mim, ó Deus, um coração puro, e renova em mim um espírito estável.

[[v19-51-11]]

^<<v19-51-11,11>>^ Não me lances fora da tua presença, e não retire de mim o teu santo Espírito.

[[v19-51-12]]

^<<v19-51-12,12>>^ Restitui-me a alegria da tua salvação, e sustém-me com um espírito voluntário.

[[v19-51-13]]

^<<v19-51-13,13>>^ Então ensinarei aos transgressores os teus caminhos, e pecadores se converterão a ti.

[[v19-51-14]]

^<<v19-51-14,14>>^ Livra-me dos crimes de sangue, ó Deus, Deus da minha salvação, e a minha língua cantará alegremente a tua justiça.

[[v19-51-15]]

^<<v19-51-15,15>>^ Abre, Senhor, os meus lábios, e a minha boca proclamará o teu louvor.

[[v19-51-16]]

^<<v19-51-16,16>>^ Pois tu não te comprazes em sacrifícios; se eu te oferecesse holocaustos, tu não te deleitarias.

[[v19-51-17]]

^<<v19-51-17,17>>^ O sacrifício aceitável a Deus é o espírito quebrantado; ao coração quebrantado e contrito não desprezarás, ó Deus.

[[v19-51-18]]

^<<v19-51-18,18>>^ Faze o bem a Sião, segundo a tua boa vontade; edifica os muros de Jerusalém.

[[v19-51-19]]

^<<v19-51-19,19>>^ Então te agradarás de sacrifícios de justiça dos holocaustos e das ofertas queimadas; então serão oferecidos novilhos sobre o teu altar.

'''

xref:019-salmos/019-salmos-050.adoc#v19-50-0[&#60; Capítulo Anterior] | <<v19-51-0,Topo>> | xref:019-salmos/019-salmos-052.adoc#v19-52-0[Próximo Capítulo &#62;]