include::./index.adoc[]

[[v19-42-0]]
=== Salmos, 42
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-42-1]]

^<<v19-42-1,1>>^ Como o cervo anseia pelas correntes das águas, assim a minha alma anseia por ti, ó Deus!

[[v19-42-2]]

^<<v19-42-2,2>>^ A minha alma tem sede de Deus, do Deus vivo; quando entrarei e verei a face de Deus?

[[v19-42-3]]

^<<v19-42-3,3>>^ As minhas lágrimas têm sido o meu alimento de dia e de noite, porquanto se me diz constantemente: Onde está o teu Deus?

[[v19-42-4]]

^<<v19-42-4,4>>^ Dentro de mim derramo a minha alma ao lembrar-me de como eu ia com a multidão, guiando-a em procissão à casa de Deus, com brados de júbilo e louvor, uma multidão que festejava.

[[v19-42-5]]

^<<v19-42-5,5>>^ Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei pela salvação que há na sua presença.

[[v19-42-6]]

^<<v19-42-6,6>>^ Ó Deus meu, dentro de mim a minha alma está abatida; porquanto me lembrarei de ti desde a terra do Jordão, e desde o Hermom, desde o monte Mizar.

[[v19-42-7]]

^<<v19-42-7,7>>^ Um abismo chama outro abismo ao ruído das tuas catadupas; todas as tuas ondas e vagas têm passado sobre mim.

[[v19-42-8]]

^<<v19-42-8,8>>^ Contudo, de dia o Senhor ordena a sua bondade, e de noite a sua canção está comigo, uma oração ao Deus da minha vida.

[[v19-42-9]]

^<<v19-42-9,9>>^ A Deus, a minha rocha, digo: Por que te esqueceste de mim? por que ando em pranto por causa da opressão do inimigo?

[[v19-42-10]]

^<<v19-42-10,10>>^ Como com ferida mortal nos meus ossos me afrontam os meus adversários, dizendo-me continuamente: Onde está o teu Deus?

[[v19-42-11]]

^<<v19-42-11,11>>^ Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei, a ele que é o meu socorro, e o meu Deus.

'''

xref:019-salmos/019-salmos-041.adoc#v19-41-0[&#60; Capítulo Anterior] | <<v19-42-0,Topo>> | xref:019-salmos/019-salmos-043.adoc#v19-43-0[Próximo Capítulo &#62;]