include::./index.adoc[]

[[v19-97-0]]
=== Salmos, 97
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-97-1]]

^<<v19-97-1,1>>^ O Senhor reina, regozije-se a terra; alegrem-se as numerosas ilhas.

[[v19-97-2]]

^<<v19-97-2,2>>^ Nuvens e escuridão estão ao redor dele; justiça e eqüidade são a base do seu trono.

[[v19-97-3]]

^<<v19-97-3,3>>^ Adiante dele vai um fogo que abrasa os seus inimigos em redor.

[[v19-97-4]]

^<<v19-97-4,4>>^ Os seus relâmpagos alumiam o mundo; a terra os vê e treme.

[[v19-97-5]]

^<<v19-97-5,5>>^ Os montes, como cerca, se derretem na presença do Senhor, na presença do Senhor de toda a terra.

[[v19-97-6]]

^<<v19-97-6,6>>^ Os céus anunciam a sua justiça, e todos os povos vêem a sua glória.

[[v19-97-7]]

^<<v19-97-7,7>>^ Confundidos são todos os que servem imagens esculpidas, que se gloriam de ídolos; prostrai-vos diante dele, todos os deuses.

[[v19-97-8]]

^<<v19-97-8,8>>^ Sião ouve e se alegra, e regozijam-se as filhas de Judá por causa dos teus juízos, Senhor.

[[v19-97-9]]

^<<v19-97-9,9>>^ Pois tu, Senhor, és o Altíssimo sobre toda a terra; tu és sobremodo exaltado acima de todos os deuses.

[[v19-97-10]]

^<<v19-97-10,10>>^ O Senhor ama aos que odeiam o mal; ele preserva as almas dos seus santos, ele os livra das mãos dos ímpios.

[[v19-97-11]]

^<<v19-97-11,11>>^ A luz é semeada para o justo, e a alegria para os retos de coração.

[[v19-97-12]]

^<<v19-97-12,12>>^ Alegrai-vos, ó justos, no Senhor, e rendei graças ao seu santo nome.

'''

xref:019-salmos/019-salmos-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-salmos/019-salmos-098.adoc#v19-98-0[Próximo Capítulo &#62;]