include::./index.adoc[]

[[v19-44-0]]
=== Salmos, 44
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-44-1]]

^<<v19-44-1,1>>^ Ó Deus, nós ouvimos com os nossos ouvidos, nossos pais nos têm contado os feitos que realizaste em seus dias, nos tempos da antigüidade.

[[v19-44-2]]

^<<v19-44-2,2>>^ Tu expeliste as nações com a tua mão, mas a eles plantaste; afligiste os povos, mas a eles estendes-te largamente.

[[v19-44-3]]

^<<v19-44-3,3>>^ Pois não foi pela sua espada que conquistaram a terra, nem foi o seu braço que os salvou, mas a tua destra e o teu braço, e a luz do teu rosto, porquanto te agradaste deles.

[[v19-44-4]]

^<<v19-44-4,4>>^ Tu és o meu Rei, ó Deus; ordena livramento para Jacó.

[[v19-44-5]]

^<<v19-44-5,5>>^ Por ti derrubamos os nossos adversários; pelo teu nome pisamos os que se levantam contra nós.

[[v19-44-6]]

^<<v19-44-6,6>>^ Pois não confio no meu arco, nem a minha espada me pode salvar.

[[v19-44-7]]

^<<v19-44-7,7>>^ Mas tu nos salvaste dos nossos adversários, e confundiste os que nos odeiam.

[[v19-44-8]]

^<<v19-44-8,8>>^ Em Deus é que nos temos gloriado o dia todo, e sempre louvaremos o teu nome.

[[v19-44-9]]

^<<v19-44-9,9>>^ Mas agora nos rejeitaste e nos humilhaste, e não sais com os nossos exércitos.

[[v19-44-10]]

^<<v19-44-10,10>>^ Fizeste-nos voltar as costas ao inimigo e aqueles que nos odeiam nos despojam à vontade.

[[v19-44-11]]

^<<v19-44-11,11>>^ Entregaste-nos como ovelhas para alimento, e nos espalhaste entre as nações.

[[v19-44-12]]

^<<v19-44-12,12>>^ Vendeste por nada o teu povo, e não lucraste com o seu preço.

[[v19-44-13]]

^<<v19-44-13,13>>^ Puseste-nos por opróbrio aos nossos vizinhos, por escárnio e zombaria àqueles que estão à roda de nós.

[[v19-44-14]]

^<<v19-44-14,14>>^ Puseste-nos por provérbio entre as nações, por ludíbrio entre os povos.

[[v19-44-15]]

^<<v19-44-15,15>>^ A minha ignomínia está sempre diante de mim, e a vergonha do meu rosto me cobre,

[[v19-44-16]]

^<<v19-44-16,16>>^ à voz daquele que afronta e blasfema, à vista do inimigo e do vingador.

[[v19-44-17]]

^<<v19-44-17,17>>^ Tudo isto nos sobreveio; todavia não nos esquecemos de ti, nem nos houvemos falsamente contra o teu pacto.

[[v19-44-18]]

^<<v19-44-18,18>>^ O nosso coração não voltou atrás, nem os nossos passos se desviaram das tuas veredas,

[[v19-44-19]]

^<<v19-44-19,19>>^ para nos teres esmagado onde habitam os chacais, e nos teres coberto de trevas profundas.

[[v19-44-20]]

^<<v19-44-20,20>>^ Se nos tivéssemos esquecido do nome do nosso Deus, e estendido as nossas mãos para um deus estranho,

[[v19-44-21]]

^<<v19-44-21,21>>^ porventura Deus não haveria de esquadrinhar isso? pois ele conhece os segredos do coração.

[[v19-44-22]]

^<<v19-44-22,22>>^ Mas por amor de ti somos entregues à morte o dia todo; somos considerados como ovelhas para o matadouro.

[[v19-44-23]]

^<<v19-44-23,23>>^ Desperta! por que dormes, Senhor? Acorda! não nos rejeites para sempre.

[[v19-44-24]]

^<<v19-44-24,24>>^ Por que escondes o teu rosto, e te esqueces da nossa tribulação e da nossa angústia?

[[v19-44-25]]

^<<v19-44-25,25>>^ Pois a nossa alma está abatida até o pó; o nosso corpo pegado ao chão.

[[v19-44-26]]

^<<v19-44-26,26>>^ Levanta-te em nosso auxílio, e resgata-nos por tua benignidade.

'''

xref:019-salmos/019-salmos-043.adoc#v19-43-0[&#60; Capítulo Anterior] | <<v19-44-0,Topo>> | xref:019-salmos/019-salmos-045.adoc#v19-45-0[Próximo Capítulo &#62;]