include::./index.adoc[]

[[v19-28-0]]
=== Salmos, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-28-1]]

^<<v19-28-1,1>>^ A ti clamo, ó Senhor; rocha minha, não emudeças para comigo; não suceda que, calando-te a meu respeito, eu me torne semelhante aos que descem à cova.

[[v19-28-2]]

^<<v19-28-2,2>>^ Ouve a voz das minhas súplicas, quando a ti clamo, quando levanto as minhas mãos para o teu santo templo.

[[v19-28-3]]

^<<v19-28-3,3>>^ Não me arrastes juntamente com os ímpios e com os que praticam a iniqüidade, que falam de paz ao seu próximo, mas têm o mal no seu coração.

[[v19-28-4]]

^<<v19-28-4,4>>^ Retribui-lhes segundo as suas obras e segundo a malícia dos seus feitos; dá-lhes conforme o que fizeram as suas mãos; retribui-lhes o que eles merecem.

[[v19-28-5]]

^<<v19-28-5,5>>^ Porquanto eles não atentam para as obras do Senhor, nem para o que as suas mãos têm feito, ele os derrubará e não os reedificará

[[v19-28-6]]

^<<v19-28-6,6>>^ Bendito seja o Senhor, porque ouviu a voz das minhas súplicas.

[[v19-28-7]]

^<<v19-28-7,7>>^ O Senhor é a minha força e o meu escudo; nele confiou o meu coração, e fui socorrido; pelo que o meu coração salta de prazer, e com o meu cântico o louvarei.

[[v19-28-8]]

^<<v19-28-8,8>>^ O Senhor é a força do seu povo; ele é a fortaleza salvadora para o seu ungido.

[[v19-28-9]]

^<<v19-28-9,9>>^ Salva o teu povo, e abençoa a tua herança; apascenta-os e exalta-os para sempre.

'''

xref:019-salmos/019-salmos-027.adoc#v19-27-0[&#60; Capítulo Anterior] | <<v19-28-0,Topo>> | xref:019-salmos/019-salmos-029.adoc#v19-29-0[Próximo Capítulo &#62;]