include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-136-1]]

^<<v19-136-1,1>>^ Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.

[[v19-136-2]]

^<<v19-136-2,2>>^ Dai graças ao Deus dos deuses, porque a sua benignidade dura para sempre

[[v19-136-3]]

^<<v19-136-3,3>>^ Dai graças ao Senhor dos senhores, porque a sua benignidade dura para sempre;

[[v19-136-4]]

^<<v19-136-4,4>>^ ao único que faz grandes maravilhas, porque a sua benignidade dura para sempre;

[[v19-136-5]]

^<<v19-136-5,5>>^ àquele que com entendimento fez os céus, porque a sua benignidade dura para sempre;

[[v19-136-6]]

^<<v19-136-6,6>>^ àquele que estendeu a terra sobre as águas, porque a sua benignidade dura para sempre;

[[v19-136-7]]

^<<v19-136-7,7>>^ àquele que fez os grandes luminares, porque a sua benignidade dura para sempre;

[[v19-136-8]]

^<<v19-136-8,8>>^ o sol para governar de dia, porque a sua benignidade dura para sempre;

[[v19-136-9]]

^<<v19-136-9,9>>^ a lua e as estrelas para presidirem a noite, porque a sua benignidade dura para sempre;

[[v19-136-10]]

^<<v19-136-10,10>>^ àquele que feriu o Egito nos seus primogênitos, porque a sua benignidade dura para sempre;

[[v19-136-11]]

^<<v19-136-11,11>>^ e que tirou a Israel do meio deles, porque a sua benignidade dura para sempre;

[[v19-136-12]]

^<<v19-136-12,12>>^ com mão forte, e com braço estendido, porque a sua benignidade dura para sempre;

[[v19-136-13]]

^<<v19-136-13,13>>^ àquele que dividiu o Mar Vermelho em duas partes, porque a sua benignidade dura para sempre;

[[v19-136-14]]

^<<v19-136-14,14>>^ e fez passar Israel pelo meio dele, porque a sua benignidade dura para sempre;

[[v19-136-15]]

^<<v19-136-15,15>>^ mas derrubou a Faraó com o seu exército no Mar Vermelho, porque a sua benignidade dura para sempre;

[[v19-136-16]]

^<<v19-136-16,16>>^ àquele que guiou o seu povo pelo deserto, porque a sua benignidade dura para sempre;

[[v19-136-17]]

^<<v19-136-17,17>>^ àquele que feriu os grandes reis, porque a sua benignidade dura para sempre;

[[v19-136-18]]

^<<v19-136-18,18>>^ e deu a morte a reis famosos, porque a sua benignidade dura para sempre.

[[v19-136-19]]

^<<v19-136-19,19>>^ a Siom, rei dos amorreus, porque a sua benignidade dura para sempre;

[[v19-136-20]]

^<<v19-136-20,20>>^ e a Ogue, rei de Basã, porque a sua benignidade dura para sempre;

[[v19-136-21]]

^<<v19-136-21,21>>^ e deu a terra deles em herança, porque a sua benignidade dura para sempre;

[[v19-136-22]]

^<<v19-136-22,22>>^ sim, em herança a Israel, seu servo, porque a sua benignidade dura para sempre;

[[v19-136-23]]

^<<v19-136-23,23>>^ que se lembrou de nós em nossa humilhação, porque a sua benignidade dura para sempre;

[[v19-136-24]]

^<<v19-136-24,24>>^ e nos libertou dos nossos inimigos, porque a sua benignidade dura para sempre;

[[v19-136-25]]

^<<v19-136-25,25>>^ que dá alimento a toda a carne, porque a sua benignidade dura para sempre.

[[v19-136-26]]

^<<v19-136-26,26>>^ Dai graças ao Deus dos céus, porque a sua benignidade dura para sempre.

'''

xref:019-salmos/019-salmos-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmos/019-salmos-137.adoc#v19-137-0[Próximo Capítulo &#62;]