include::./index.adoc[]

[[v19-22-0]]
=== Salmos, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-22-1]]

^<<v19-22-1,1>>^ Deus meu, Deus meu, por que me desamparaste? por que estás afastado de me auxiliar, e das palavras do meu bramido?

[[v19-22-2]]

^<<v19-22-2,2>>^ Deus meu, eu clamo de dia, porém tu não me ouves; também de noite, mas não acho sossego.

[[v19-22-3]]

^<<v19-22-3,3>>^ Contudo tu és santo, entronizado sobre os louvores de Israel.

[[v19-22-4]]

^<<v19-22-4,4>>^ Em ti confiaram nossos pais; confiaram, e tu os livraste.

[[v19-22-5]]

^<<v19-22-5,5>>^ A ti clamaram, e foram salvos; em ti confiaram, e não foram confundidos.

[[v19-22-6]]

^<<v19-22-6,6>>^ Mas eu sou verme, e não homem; opróbrio dos homens e desprezado do povo.

[[v19-22-7]]

^<<v19-22-7,7>>^ Todos os que me vêem zombam de mim, arreganham os beiços e meneiam a cabeça, dizendo:

[[v19-22-8]]

^<<v19-22-8,8>>^ Confiou no Senhor; que ele o livre; que ele o salve, pois que nele tem prazer.

[[v19-22-9]]

^<<v19-22-9,9>>^ Mas tu és o que me tiraste da madre; o que me preservaste, estando eu ainda aos seios de minha mãe.

[[v19-22-10]]

^<<v19-22-10,10>>^ Nos teus braços fui lançado desde a madre; tu és o meu Deus desde o ventre de minha mãe.

[[v19-22-11]]

^<<v19-22-11,11>>^ Não te alongues de mim, pois a angústia está perto, e não há quem acuda.

[[v19-22-12]]

^<<v19-22-12,12>>^ Muitos touros me cercam; fortes touros de Basã me rodeiam.

[[v19-22-13]]

^<<v19-22-13,13>>^ Abrem contra mim sua boca, como um leão que despedaça e que ruge.

[[v19-22-14]]

^<<v19-22-14,14>>^ Como água me derramei, e todos os meus ossos se desconjuntaram; o meu coração é como cera, derreteu-se no meio das minhas entranhas.

[[v19-22-15]]

^<<v19-22-15,15>>^ A minha força secou-se como um caco e a língua se me pega ao paladar; tu me puseste no pó da morte.

[[v19-22-16]]

^<<v19-22-16,16>>^ Pois cães me rodeiam; um ajuntamento de malfeitores me cerca; transpassaram-me as mãos e os pés.

[[v19-22-17]]

^<<v19-22-17,17>>^ Posso contar todos os meus ossos. Eles me olham e ficam a mirar-me.

[[v19-22-18]]

^<<v19-22-18,18>>^ Repartem entre si as minhas vestes, e sobre a minha túnica lançam sortes.

[[v19-22-19]]

^<<v19-22-19,19>>^ Mas tu, Senhor, não te alongues de mim; força minha, apressa-te em socorrer-me.

[[v19-22-20]]

^<<v19-22-20,20>>^ Livra-me da espada, e a minha vida do poder do cão.

[[v19-22-21]]

^<<v19-22-21,21>>^ Salva-me da boca do leão, sim, livra-me dos chifres do boi selvagem.

[[v19-22-22]]

^<<v19-22-22,22>>^ Então anunciarei o teu nome aos meus irmãos; louvar-te-ei no meio da congregação.

[[v19-22-23]]

^<<v19-22-23,23>>^ Vós, que temeis ao Senhor, louvai-o; todos vós, filhos de Jacó, glorificai-o; temei-o todos vós, descendência de Israel.

[[v19-22-24]]

^<<v19-22-24,24>>^ Porque não desprezou nem abominou a aflição do aflito, nem dele escondeu o seu rosto; antes, quando ele clamou, o ouviu.

[[v19-22-25]]

^<<v19-22-25,25>>^ De ti vem o meu louvor na grande congregação; pagarei os meus votos perante os que o temem.

[[v19-22-26]]

^<<v19-22-26,26>>^ Os mansos comerão e se fartarão; louvarão ao Senhor os que o buscam. Que o vosso coração viva eternamente!

[[v19-22-27]]

^<<v19-22-27,27>>^ Todos os limites da terra se lembrarão e se converterão ao Senhor, e diante dele adorarão todas as famílias das nações.

[[v19-22-28]]

^<<v19-22-28,28>>^ Porque o domínio é do Senhor, e ele reina sobre as nações.

[[v19-22-29]]

^<<v19-22-29,29>>^ Todos os grandes da terra comerão e adorarão, e todos os que descem ao pó se prostrarão perante ele, os que não podem reter a sua vida.

[[v19-22-30]]

^<<v19-22-30,30>>^ A posteridade o servirá; falar-se-á do Senhor à geração vindoura.

[[v19-22-31]]

^<<v19-22-31,31>>^ Chegarão e anunciarão a justiça dele; a um povo que há de nascer contarão o que ele fez.

'''

xref:019-salmos/019-salmos-021.adoc#v19-21-0[&#60; Capítulo Anterior] | <<v19-22-0,Topo>> | xref:019-salmos/019-salmos-023.adoc#v19-23-0[Próximo Capítulo &#62;]