include::./index.adoc[]

[[v19-5-0]]
=== Salmos, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-5-1]]

^<<v19-5-1,1>>^ Dá ouvidos às minhas palavras, ó Senhor; atende aos meus gemidos.

[[v19-5-2]]

^<<v19-5-2,2>>^ Atende à voz do meu clamor, Rei meu e Deus meu, pois é a ti que oro.

[[v19-5-3]]

^<<v19-5-3,3>>^ Pela manhã ouves a minha voz, ó Senhor; pela manhã te apresento a minha oração, e vigio.

[[v19-5-4]]

^<<v19-5-4,4>>^ Porque tu não és um Deus que tenha prazer na iniqüidade, nem contigo habitará o mal.

[[v19-5-5]]

^<<v19-5-5,5>>^ Os arrogantes não subsistirão diante dos teus olhos; detestas a todos os que praticam a maldade.

[[v19-5-6]]

^<<v19-5-6,6>>^ Destróis aqueles que proferem a mentira; ao sanguinário e ao fraudulento o Senhor abomina.

[[v19-5-7]]

^<<v19-5-7,7>>^ Mas eu, pela grandeza da tua benignidade, entrarei em tua casa; e em teu temor me inclinarei para o teu santo templo.

[[v19-5-8]]

^<<v19-5-8,8>>^ Guia-me, Senhor, na tua justiça, por causa dos meus inimigos; aplana diante de mim o teu caminho.

[[v19-5-9]]

^<<v19-5-9,9>>^ Porque não há fidelidade na boca deles; as suas entranhas são verdadeiras maldades, a sua garganta é um sepulcro aberto; lisonjeiam com a sua língua.

[[v19-5-10]]

^<<v19-5-10,10>>^ Declara-os culpados, ó Deus; que caiam por seus próprios conselhos; lança-os fora por causa da multidão de suas transgressões, pois se revoltaram contra ti.

[[v19-5-11]]

^<<v19-5-11,11>>^ Mas alegrem-se todos os que confiam em ti; exultem eternamente, porquanto tu os defendes; sim, gloriem-se em ti os que amam o teu nome.

[[v19-5-12]]

^<<v19-5-12,12>>^ Pois tu, Senhor, abençoas o justo; tu o circundas do teu favor como de um escudo.

'''

xref:019-salmos/019-salmos-004.adoc#v19-4-0[&#60; Capítulo Anterior] | <<v19-5-0,Topo>> | xref:019-salmos/019-salmos-006.adoc#v19-6-0[Próximo Capítulo &#62;]