include::./index.adoc[]

[[v19-145-0]]
=== Salmos, 145
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-145-1]]

^<<v19-145-1,1>>^ Eu te exaltarei, ó Deus, rei meu; e bendirei o teu nome pelos séculos dos séculos.

[[v19-145-2]]

^<<v19-145-2,2>>^ Cada dia te bendirei, e louvarei o teu nome pelos séculos dos séculos.

[[v19-145-3]]

^<<v19-145-3,3>>^ Grande é o Senhor, e mui digno de ser louvado; e a sua grandeza é insondável.

[[v19-145-4]]

^<<v19-145-4,4>>^ Uma geração louvará as tuas obras à outra geração, e anunciará os teus atos poderosos.

[[v19-145-5]]

^<<v19-145-5,5>>^ Na magnificência gloriosa da tua majestade e nas tuas obras maravilhosas meditarei;

[[v19-145-6]]

^<<v19-145-6,6>>^ falar-se-á do poder dos teus feitos tremendos, e eu contarei a tua grandeza.

[[v19-145-7]]

^<<v19-145-7,7>>^ Publicarão a memória da tua grande bondade, e com júbilo celebrarão a tua justiça.

[[v19-145-8]]

^<<v19-145-8,8>>^ Bondoso e compassivo é o Senhor, tardio em irar-se, e de grande benignidade.

[[v19-145-9]]

^<<v19-145-9,9>>^ O Senhor é bom para todos, e as suas misericórdias estão sobre todas as suas obras.

[[v19-145-10]]

^<<v19-145-10,10>>^ Todas as tuas obras te louvarão, ó Senhor, e os teus santos te bendirão.

[[v19-145-11]]

^<<v19-145-11,11>>^ Falarão da glória do teu reino, e relatarão o teu poder,

[[v19-145-12]]

^<<v19-145-12,12>>^ para que façam saber aos filhos dos homens os teus feitos poderosos e a glória do esplendor do teu reino.

[[v19-145-13]]

^<<v19-145-13,13>>^ O teu reino é um reino eterno; o teu domínio dura por todas as gerações.

[[v19-145-14]]

^<<v19-145-14,14>>^ O Senhor sustém a todos os que estão a cair, e levanta a todos os que estão abatidos.

[[v19-145-15]]

^<<v19-145-15,15>>^ Os olhos de todos esperam em ti, e tu lhes dás o seu mantimento a seu tempo;

[[v19-145-16]]

^<<v19-145-16,16>>^ abres a mão, e satisfazes o desejo de todos os viventes.

[[v19-145-17]]

^<<v19-145-17,17>>^ Justo é o Senhor em todos os seus caminhos, e benigno em todas as suas obras.

[[v19-145-18]]

^<<v19-145-18,18>>^ Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.

[[v19-145-19]]

^<<v19-145-19,19>>^ Ele cumpre o desejo dos que o temem; ouve o seu clamor, e os salva.

[[v19-145-20]]

^<<v19-145-20,20>>^ O Senhor preserva todos os que o amam, mas a todos os ímpios ele os destrói.

[[v19-145-21]]

^<<v19-145-21,21>>^ Publique a minha boca o louvor do Senhor; e bendiga toda a carne o seu santo nome para todo o sempre.

'''

xref:019-salmos/019-salmos-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-salmos/019-salmos-146.adoc#v19-146-0[Próximo Capítulo &#62;]