include::./index.adoc[]

[[v19-55-0]]
=== Salmos, 55
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-55-1]]

^<<v19-55-1,1>>^ Dá ouvidos, ó Deus, à minha oração, e não te escondas da minha súplica.

[[v19-55-2]]

^<<v19-55-2,2>>^ Atende-me, e ouve-me; agitado estou, e ando perplexo,

[[v19-55-3]]

^<<v19-55-3,3>>^ por causa do clamor do inimigo e da opressão do ímpio; pois lançam sobre mim iniqüidade, e com furor me perseguem.

[[v19-55-4]]

^<<v19-55-4,4>>^ O meu coração confrange-se dentro de mim, e terrores de morte sobre mim caíram.

[[v19-55-5]]

^<<v19-55-5,5>>^ Temor e tremor me sobrevêm, e o horror me envolveu.

[[v19-55-6]]

^<<v19-55-6,6>>^ Pelo que eu disse: Ah! quem me dera asas como de pomba! então voaria, e encontraria descanso.

[[v19-55-7]]

^<<v19-55-7,7>>^ Eis que eu fugiria para longe, e pernoitaria no deserto.

[[v19-55-8]]

^<<v19-55-8,8>>^ Apressar-me-ia a abrigar-me da fúria do vento e da tempestade.

[[v19-55-9]]

^<<v19-55-9,9>>^ Destrói, Senhor, confunde as suas línguas, pois vejo violência e contenda na cidade.

[[v19-55-10]]

^<<v19-55-10,10>>^ Dia e noite andam ao redor dela, sobre os seus muros; também iniqüidade e malícia estão no meio dela.

[[v19-55-11]]

^<<v19-55-11,11>>^ Há destruição lá dentro; opressão e fraude não se apartam das suas ruas.

[[v19-55-12]]

^<<v19-55-12,12>>^ Pois não é um inimigo que me afronta, então eu poderia suportá-lo; nem é um adversário que se exalta contra mim, porque dele poderia esconder-me;

[[v19-55-13]]

^<<v19-55-13,13>>^ mas és tu, homem meu igual, meu companheiro e meu amigo íntimo.

[[v19-55-14]]

^<<v19-55-14,14>>^ Conservávamos juntos tranqüilamente, e em companhia andávamos na casa de Deus.

[[v19-55-15]]

^<<v19-55-15,15>>^ A morte os assalte, e vivos desçam ao Seol; porque há maldade na sua morada, no seu próprio íntimo.

[[v19-55-16]]

^<<v19-55-16,16>>^ Mas eu invocarei a Deus, e o Senhor me salvará.

[[v19-55-17]]

^<<v19-55-17,17>>^ De tarde, de manhã e ao meio-dia me queixarei e me lamentarei; e ele ouvirá a minha voz.

[[v19-55-18]]

^<<v19-55-18,18>>^ Livrará em paz a minha vida, de modo que ninguém se aproxime de mim; pois há muitos que contendem contra mim.

[[v19-55-19]]

^<<v19-55-19,19>>^ Deus ouvirá; e lhes responderá aquele que está entronizado desde a antigüidade; porque não há neles nenhuma mudança, e tampouco temem a Deus.

[[v19-55-20]]

^<<v19-55-20,20>>^ Aquele meu companheiro estendeu a sua mão contra os que tinham paz com ele; violou o seu pacto.

[[v19-55-21]]

^<<v19-55-21,21>>^ A sua fala era macia como manteiga, mas no seu coração havia guerra; as suas palavras eram mais brandas do que o azeite, todavia eram espadas desembainhadas.

[[v19-55-22]]

^<<v19-55-22,22>>^ Lança o teu fardo sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado.

[[v19-55-23]]

^<<v19-55-23,23>>^ Mas tu, ó Deus, os farás descer ao poço da perdição; homens de sangue e de traição não viverão metade dos seus dias; mas eu em ti confiarei.

'''

xref:019-salmos/019-salmos-054.adoc#v19-54-0[&#60; Capítulo Anterior] | <<v19-55-0,Topo>> | xref:019-salmos/019-salmos-056.adoc#v19-56-0[Próximo Capítulo &#62;]