include::./index.adoc[]

[[v19-118-0]]
=== Salmos, 118
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-118-1]]

^<<v19-118-1,1>>^ Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.

[[v19-118-2]]

^<<v19-118-2,2>>^ Diga, pois, Israel: A sua benignidade dura para sempre.

[[v19-118-3]]

^<<v19-118-3,3>>^ Diga, pois, a casa de Arão: A sua benignidade dura para sempre.

[[v19-118-4]]

^<<v19-118-4,4>>^ Digam, pois, os que temem ao Senhor: A sua benignidade dura para sempre.

[[v19-118-5]]

^<<v19-118-5,5>>^ Do meio da angústia invoquei o Senhor; o Senhor me ouviu, e me pôs em um lugar largo.

[[v19-118-6]]

^<<v19-118-6,6>>^ O Senhor é por mim, não recearei; que me pode fazer o homem?

[[v19-118-7]]

^<<v19-118-7,7>>^ O Senhor é por mim entre os que me ajudam; pelo que verei cumprido o meu desejo sobre os que me odeiam.

[[v19-118-8]]

^<<v19-118-8,8>>^ É melhor refugiar-se no Senhor do que confiar no homem.

[[v19-118-9]]

^<<v19-118-9,9>>^ É melhor refugiar-se no Senhor do que confiar nos príncipes.

[[v19-118-10]]

^<<v19-118-10,10>>^ Todas as nações me cercaram, mas em nome do Senhor eu as exterminei.

[[v19-118-11]]

^<<v19-118-11,11>>^ Cercaram-me, sim, cercaram-me; mas em nome do Senhor eu as exterminei.

[[v19-118-12]]

^<<v19-118-12,12>>^ Cercaram-me como abelhas, mas apagaram-se como fogo de espinhos; pois em nome do Senhor as exterminei.

[[v19-118-13]]

^<<v19-118-13,13>>^ Com força me impeliste para me fazeres cair, mas o Senhor me ajudou.

[[v19-118-14]]

^<<v19-118-14,14>>^ O Senhor é a minha força e o meu cântico; tornou-se a minha salvação.

[[v19-118-15]]

^<<v19-118-15,15>>^ Nas tendas dos justos há jubiloso cântico de vitória; a destra do Senhor faz proezas.

[[v19-118-16]]

^<<v19-118-16,16>>^ A destra do Senhor se exalta, a destra do Senhor faz proezas.

[[v19-118-17]]

^<<v19-118-17,17>>^ Não morrerei, mas viverei, e contarei as obras do Senhor.

[[v19-118-18]]

^<<v19-118-18,18>>^ O Senhor castigou-me muito, mas não me entregou à morte.

[[v19-118-19]]

^<<v19-118-19,19>>^ Abre-me as portas da justiça, para que eu entre por elas e dê graças ao Senhor.

[[v19-118-20]]

^<<v19-118-20,20>>^ Esta é a porta do Senhor; por ela os justos entrarão.

[[v19-118-21]]

^<<v19-118-21,21>>^ Graças te dou porque me ouviste, e te tornaste a minha salvação.

[[v19-118-22]]

^<<v19-118-22,22>>^ A pedra que os edificadores rejeitaram, essa foi posta como pedra angular.

[[v19-118-23]]

^<<v19-118-23,23>>^ Foi o Senhor que fez isto e é maravilhoso aos nossos olhos.

[[v19-118-24]]

^<<v19-118-24,24>>^ Este é o dia que o Senhor fez; regozijemo-nos, e alegremo-nos nele.

[[v19-118-25]]

^<<v19-118-25,25>>^ Ó Senhor, salva, nós te pedimos; ó Senhor, nós te pedimos, envia-nos a prosperidade.

[[v19-118-26]]

^<<v19-118-26,26>>^ Bendito aquele que vem em nome do Senhor; da casa do Senhor vos bendizemos.

[[v19-118-27]]

^<<v19-118-27,27>>^ O Senhor é Deus, e nos concede a luz; atai a vítima da festa com cordas às pontas do altar.

[[v19-118-28]]

^<<v19-118-28,28>>^ Tu és o meu Deus, e eu te darei graças; tu és o meu Deus, e eu te exaltarei.

[[v19-118-29]]

^<<v19-118-29,29>>^ Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre. a tua palavra.

'''

xref:019-salmos/019-salmos-117.adoc#v19-117-0[&#60; Capítulo Anterior] | <<v19-118-0,Topo>> | xref:019-salmos/019-salmos-119.adoc#v19-119-0[Próximo Capítulo &#62;]