include::./index.adoc[]

[[v19-61-0]]
=== Salmos, 61
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-61-1]]

^<<v19-61-1,1>>^ Ouve, ó Deus, o meu clamor; atende à minha oração.

[[v19-61-2]]

^<<v19-61-2,2>>^ Desde a extremidade da terra clamo a ti, estando abatido o meu coração; leva-me para a rocha que é mais alta do que eu.

[[v19-61-3]]

^<<v19-61-3,3>>^ Pois tu és o meu refúgio, uma torre forte contra o inimigo.

[[v19-61-4]]

^<<v19-61-4,4>>^ Deixa-me habitar no teu tabernáculo para sempre; dá que me abrigue no esconderijo das tuas asas.

[[v19-61-5]]

^<<v19-61-5,5>>^ Pois tu, ó Deus, ouviste os meus votos; deste-me a herança dos que temem o teu nome.

[[v19-61-6]]

^<<v19-61-6,6>>^ Prolongarás os dias do rei; e os seus anos serão como muitas gerações.

[[v19-61-7]]

^<<v19-61-7,7>>^ Ele permanecerá no trono diante de Deus para sempre; faze que a benignidade e a fidelidade o preservem.

[[v19-61-8]]

^<<v19-61-8,8>>^ Assim cantarei louvores ao teu nome perpetuamente, para pagar os meus votos de dia em dia.

'''

xref:019-salmos/019-salmos-060.adoc#v19-60-0[&#60; Capítulo Anterior] | <<v19-61-0,Topo>> | xref:019-salmos/019-salmos-062.adoc#v19-62-0[Próximo Capítulo &#62;]