include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-62-1]]

^<<v19-62-1,1>>^ Somente em Deus espera silenciosa a minha alma; dele vem a minha salvação.

[[v19-62-2]]

^<<v19-62-2,2>>^ Só ele é a minha rocha e a minha salvação; é ele a minha fortaleza; não serei grandemente abalado.

[[v19-62-3]]

^<<v19-62-3,3>>^ Até quando acometereis um homem, todos vós, para o derrubardes, como a um muro pendido, uma cerca prestes a cair?

[[v19-62-4]]

^<<v19-62-4,4>>^ Eles somente consultam como derrubá-lo da sua alta posição; deleitam-se em mentiras; com a boca bendizem, mas no íntimo maldizem.

[[v19-62-5]]

^<<v19-62-5,5>>^ Ó minha alma, espera silenciosa somente em Deus, porque dele vem a minha esperança.

[[v19-62-6]]

^<<v19-62-6,6>>^ Só ele é a minha rocha e a minha salvação; é a minha fortaleza; não serei abalado.

[[v19-62-7]]

^<<v19-62-7,7>>^ Em Deus está a minha salvação e a minha glória; Deus é o meu forte rochedo e o meu refúgio.

[[v19-62-8]]

^<<v19-62-8,8>>^ Confiai nele, ó povo, em todo o tempo; derramai perante ele o vosso coração; Deus é o nosso refúgio.

[[v19-62-9]]

^<<v19-62-9,9>>^ Certamente que os filhos de Adão são vaidade, e os filhos dos homens são desilusão; postos na balança, subiriam; todos juntos são mais leves do que um sopro.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não confieis na opressão, nem vos vanglorieis na rapina; se as vossas riquezas aumentarem, não ponhais nelas o coração.

[[v19-62-11]]

^<<v19-62-11,11>>^ Uma vez falou Deus, duas vezes tenho ouvido isto: que o poder pertence a Deus.

[[v19-62-12]]

^<<v19-62-12,12>>^ A ti também, Senhor, pertence a benignidade; pois retribuis a cada um segundo a sua obra.

'''

xref:019-salmos/019-salmos-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmos/019-salmos-063.adoc#v19-63-0[Próximo Capítulo &#62;]