include::./index.adoc[]

[[v19-35-0]]
=== Salmos, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-35-1]]

^<<v19-35-1,1>>^ Contende, Senhor, com aqueles que contendem comigo; combate contra os que me combatem.

[[v19-35-2]]

^<<v19-35-2,2>>^ Pega do escudo e do pavês, e levanta-te em meu socorro.

[[v19-35-3]]

^<<v19-35-3,3>>^ Tira da lança e do dardo contra os que me perseguem. Dize à minha alma: Eu sou a tua salvação.

[[v19-35-4]]

^<<v19-35-4,4>>^ Sejam envergonhados e confundidos os que buscam a minha vida; voltem atrás e se confudam os que contra mim intentam o mal.

[[v19-35-5]]

^<<v19-35-5,5>>^ Sejam como a moinha diante do vento, e o anjo do Senhor os faça fugir.

[[v19-35-6]]

^<<v19-35-6,6>>^ Seja o seu caminho tenebroso e escorregadio, e o anjo do Senhor os persiga.

[[v19-35-7]]

^<<v19-35-7,7>>^ Pois sem causa me armaram ocultamente um laço; sem razão cavaram uma cova para a minha vida.

[[v19-35-8]]

^<<v19-35-8,8>>^ Sobrevenha-lhes inesperadamente a destruição, e prenda-os o laço que ocultaram; caiam eles nessa mesma destruição.

[[v19-35-9]]

^<<v19-35-9,9>>^ Então minha alma se regozijará no Senhor; exultará na sua salvação.

[[v19-35-10]]

^<<v19-35-10,10>>^ Todos os meus ossos dirão: Ó Senhor, quem é como tu, que livras o fraco daquele que é mais forte do que ele? sim, o pobre e o necessitado, daquele que o rouba.

[[v19-35-11]]

^<<v19-35-11,11>>^ Levantam-se testemunhas maliciosas; interrogam-me sobre coisas que eu ignoro.

[[v19-35-12]]

^<<v19-35-12,12>>^ Tornam-me o mal pelo bem, causando-me luto na alma.

[[v19-35-13]]

^<<v19-35-13,13>>^ Mas, quanto a mim, estando eles enfermos, vestia-me de cilício, humilhava-me com o jejum, e orava de cabeça sobre o peito.

[[v19-35-14]]

^<<v19-35-14,14>>^ Portava-me como o faria por meu amigo ou meu irmão; eu andava encurvado e lamentando-me, como quem chora por sua mãe.

[[v19-35-15]]

^<<v19-35-15,15>>^ Mas, quando eu tropeçava, eles se alegravam e se congregavam; congregavam-se contra mim, homens miseráveis que eu não conhecia; difamavam-me sem cessar.

[[v19-35-16]]

^<<v19-35-16,16>>^ Como hipócritas zombadores nas festas, rangiam os dentes contra mim.

[[v19-35-17]]

^<<v19-35-17,17>>^ Ó Senhor, até quando contemplarás isto? Livra-me das suas violências; salva a minha vida dos leões!

[[v19-35-18]]

^<<v19-35-18,18>>^ Então te darei graças na grande assembléia; entre muitíssimo povo te louvarei.

[[v19-35-19]]

^<<v19-35-19,19>>^ Não se alegrem sobre mim os que são meus inimigos sem razão, nem pisquem os olhos aqueles que me odeiam sem causa.

[[v19-35-20]]

^<<v19-35-20,20>>^ Pois não falaram de paz, antes inventam contra os quietos da terra palavras enganosas.

[[v19-35-21]]

^<<v19-35-21,21>>^ Escancararam contra mim a sua boca, e dizem: Ah! Ah! os nossos olhos o viram.

[[v19-35-22]]

^<<v19-35-22,22>>^ Tu, Senhor, o viste, não te cales; Senhor, não te alongues de mim.

[[v19-35-23]]

^<<v19-35-23,23>>^ Acorda e desperta para o meu julgamento, para a minha causa, Deus meu, e Senhor meu.

[[v19-35-24]]

^<<v19-35-24,24>>^ Justifica-me segundo a tua justiça, Senhor Deus meu, e não se regozijem eles sobre mim.

[[v19-35-25]]

^<<v19-35-25,25>>^ Não digam em seu coração: Eia! cumpriu-se o nosso desejo! Não digam: Nós o havemos devorado.

[[v19-35-26]]

^<<v19-35-26,26>>^ Envergonhem-se e confundam-se à uma os que se alegram com o meu mal; vistam-se de vergonha e de confusão os que se engrandecem contra mim.

[[v19-35-27]]

^<<v19-35-27,27>>^ Bradem de júbilo e se alegrem os que desejam a minha justificação, e digam a minha justificação, e digam continuamente: Seja engrandecido o Senhor, que se deleita na prosperidade do seu servo.

[[v19-35-28]]

^<<v19-35-28,28>>^ Então a minha língua falará da tua justiça e do teu louvor o dia todo.

'''

xref:019-salmos/019-salmos-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-salmos/019-salmos-036.adoc#v19-36-0[Próximo Capítulo &#62;]