include::./index.adoc[]

[[v19-40-0]]
=== Salmos, 40
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-40-1]]

^<<v19-40-1,1>>^ Esperei com paciência pelo Senhor, e ele se inclinou para mim e ouviu o meu clamor.

[[v19-40-2]]

^<<v19-40-2,2>>^ Também me tirou duma cova de destruição, dum charco de lodo; pôs os meus pés sobre uma rocha, firmou os meus passos.

[[v19-40-3]]

^<<v19-40-3,3>>^ Pôs na minha boca um cântico novo, um hino ao nosso Deus; muitos verão isso e temerão, e confiarão no Senhor.

[[v19-40-4]]

^<<v19-40-4,4>>^ Bem-aventurado o homem que faz do Senhor a sua confiança, e que não atenta para os soberbos nem para os apóstatas mentirosos.

[[v19-40-5]]

^<<v19-40-5,5>>^ Muitas são, Senhor, Deus meu, as maravilhas que tens operado e os teus pensamentos para conosco; ninguém há que se possa comparar a ti; eu quisera anunciá-los, e manifestá-los, mas são mais do que se podem contar.

[[v19-40-6]]

^<<v19-40-6,6>>^ Sacrifício e oferta não desejas; abriste-me os ouvidos; holocausto e oferta de expiação pelo pecado não reclamaste.

[[v19-40-7]]

^<<v19-40-7,7>>^ Então disse eu: Eis aqui venho; no rolo do livro está escrito a meu respeito:

[[v19-40-8]]

^<<v19-40-8,8>>^ Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração.

[[v19-40-9]]

^<<v19-40-9,9>>^ Tenho proclamado boas-novas de justiça na grande congregação; eis que não retive os meus lábios;

[[v19-40-10]]

^<<v19-40-10,10>>^ Não ocultei dentro do meu coração a tua justiça; apregoei a tua fidelidade e a tua salvação; não escondi da grande congregação a tua benignidade e a tua verdade.

[[v19-40-11]]

^<<v19-40-11,11>>^ Não detenhas para comigo, Senhor a tua compaixão; a tua benignidade e a tua fidelidade sempre me guardem.

[[v19-40-12]]

^<<v19-40-12,12>>^ Pois males sem número me têm rodeado; as minhas iniqüidades me têm alcançado, de modo que não posso ver; são mais numerosas do que os cabelos da minha cabeça, pelo que desfalece o meu coração.

[[v19-40-13]]

^<<v19-40-13,13>>^ Digna-te, Senhor, livra-me; Senhor, apressa-te em meu auxílio.

[[v19-40-14]]

^<<v19-40-14,14>>^ Sejam à uma envergonhados e confundidos os que buscam a minha vida para destruí-la; tornem atrás e confundam-se os que me desejam o mal.

[[v19-40-15]]

^<<v19-40-15,15>>^ Desolados sejam em razão da sua afronta os que me dizem: Ah! Ah!

[[v19-40-16]]

^<<v19-40-16,16>>^ Regozijem-se e alegrem-se em ti todos os que te buscam. Digam continuamente os que amam a tua salvação: Engrandecido seja o Senhor.

[[v19-40-17]]

^<<v19-40-17,17>>^ Eu, na verdade, sou pobre e necessitado, mas o Senhor cuida de mim. Tu és o meu auxílio e o meu libertador; não te detenhas, ó Deus meu.

'''

xref:019-salmos/019-salmos-039.adoc#v19-39-0[&#60; Capítulo Anterior] | <<v19-40-0,Topo>> | xref:019-salmos/019-salmos-041.adoc#v19-41-0[Próximo Capítulo &#62;]