include::./index.adoc[]

[[v19-11-0]]
=== Salmos, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-11-1]]

^<<v19-11-1,1>>^ No Senhor confio. Como, pois, me dizeis: Foge para o monte, como um pássaro?

[[v19-11-2]]

^<<v19-11-2,2>>^ Pois eis que os ímpios armam o arco, põem a sua flecha na corda, para atirarem, às ocultas, aos retos de coração.

[[v19-11-3]]

^<<v19-11-3,3>>^ Quando os fundamentos são destruídos, que pode fazer o justo?

[[v19-11-4]]

^<<v19-11-4,4>>^ O Senhor está no seu santo templo, o trono do Senhor está nos céus; os seus olhos contemplam, as suas pálpebras provam os filhos dos homens.

[[v19-11-5]]

^<<v19-11-5,5>>^ O Senhor prova o justo e o ímpio; a sua alma odeia ao que ama a violência.

[[v19-11-6]]

^<<v19-11-6,6>>^ Sobre os ímpios fará chover brasas de fogo e enxofre; um vento abrasador será a porção do seu copo.

[[v19-11-7]]

^<<v19-11-7,7>>^ Porque o Senhor é justo; ele ama a justiça; os retos, pois, verão o seu rosto.

'''

xref:019-salmos/019-salmos-010.adoc#v19-10-0[&#60; Capítulo Anterior] | <<v19-11-0,Topo>> | xref:019-salmos/019-salmos-012.adoc#v19-12-0[Próximo Capítulo &#62;]