include::./index.adoc[]

[[v19-6-0]]
=== Salmos, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-6-1]]

^<<v19-6-1,1>>^ Senhor, não me repreendas na tua ira, nem me castigues no teu furor.

[[v19-6-2]]

^<<v19-6-2,2>>^ Tem compaixão de mim, Senhor, porque sou fraco; sara-me, Senhor, porque os meus ossos estão perturbados.

[[v19-6-3]]

^<<v19-6-3,3>>^ Também a minha alma está muito perturbada; mas tu, Senhor, até quando?...

[[v19-6-4]]

^<<v19-6-4,4>>^ Volta-te, Senhor, livra a minha alma; salva-me por tua misericórdia.

[[v19-6-5]]

^<<v19-6-5,5>>^ Pois na morte não há lembrança de ti; no Seol quem te louvará?

[[v19-6-6]]

^<<v19-6-6,6>>^ Estou cansado do meu gemido; toda noite faço nadar em lágrimas a minha cama, inundo com elas o meu leito.

[[v19-6-7]]

^<<v19-6-7,7>>^ Os meus olhos estão consumidos pela mágoa, e enfraquecem por causa de todos os meus inimigos.

[[v19-6-8]]

^<<v19-6-8,8>>^ Apartai-vos de mim todos os que praticais a iniquidade; porque o Senhor já ouviu a voz do meu pranto.

[[v19-6-9]]

^<<v19-6-9,9>>^ O Senhor já ouviu a minha súplica, o Senhor aceita a minha oração.

[[v19-6-10]]

^<<v19-6-10,10>>^ Serão envergonhados e grandemente perturbados todos os meus inimigos; tornarão atrás e subitamente serão envergonhados.

'''

xref:019-salmos/019-salmos-005.adoc#v19-5-0[&#60; Capítulo Anterior] | <<v19-6-0,Topo>> | xref:019-salmos/019-salmos-007.adoc#v19-7-0[Próximo Capítulo &#62;]