include::./index.adoc[]

[[v19-142-0]]
=== Salmos, 142
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-142-1]]

^<<v19-142-1,1>>^ Com a minha voz clamo ao Senhor; com a minha voz ao Senhor suplico.

[[v19-142-2]]

^<<v19-142-2,2>>^ Derramo perante ele a minha queixa; diante dele exponho a minha tribulação.

[[v19-142-3]]

^<<v19-142-3,3>>^ Quando dentro de mim esmorece o meu espírito, então tu conheces a minha vereda; no caminho em que eu ando ocultaram-me um laço.

[[v19-142-4]]

^<<v19-142-4,4>>^ Olha para a minha mão direita, e vê, pois não há quem me conheça; refúgio me faltou; ninguém se interessa por mim.

[[v19-142-5]]

^<<v19-142-5,5>>^ A ti, ó Senhor, clamei; eu disse: Tu és o meu refúgio, o meu quinhão na terra dos viventes.

[[v19-142-6]]

^<<v19-142-6,6>>^ Atende ao meu clamor, porque estou muito abatido; livra-me dos meus perseguidores, porque são mais fortes do que eu.

[[v19-142-7]]

^<<v19-142-7,7>>^ Tira-me da prisão, para que eu louve o teu nome; os justos me rodearão, pois me farás muito bem.

'''

xref:019-salmos/019-salmos-141.adoc#v19-141-0[&#60; Capítulo Anterior] | <<v19-142-0,Topo>> | xref:019-salmos/019-salmos-143.adoc#v19-143-0[Próximo Capítulo &#62;]