include::./index.adoc[]

[[v19-57-0]]
=== Salmos, 57
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-57-1]]

^<<v19-57-1,1>>^ Compadece-te de mim, ó Deus, compadece-te de mim, pois em ti se refugia a minha alma; à sombra das tuas asas me refugiarei, até que passem as calamidades.

[[v19-57-2]]

^<<v19-57-2,2>>^ Clamarei ao Deus altíssimo, ao Deus que por mim tudo executa.

[[v19-57-3]]

^<<v19-57-3,3>>^ Ele do céu enviará seu auxílio , e me salvará, quando me ultrajar aquele que quer calçar-me aos pés. Deus enviará a sua misericórdia e a sua verdade.

[[v19-57-4]]

^<<v19-57-4,4>>^ Estou deitado no meio de leões; tenho que deitar-me no meio daqueles que respiram chamas, filhos dos homens, cujos dentes são lanças e flechas, e cuja língua é espada afiada.

[[v19-57-5]]

^<<v19-57-5,5>>^ Sê exaltado, ó Deus, acima dos céus; seja a tua glória sobre toda a terra.

[[v19-57-6]]

^<<v19-57-6,6>>^ Armaram um laço para os meus passos, a minha alma ficou abatida; cavaram uma cova diante de mim, mas foram eles que nela caíram.

[[v19-57-7]]

^<<v19-57-7,7>>^ Resoluto está o meu coração, ó Deus, resoluto está o meu coração; cantarei, sim, cantarei louvores.

[[v19-57-8]]

^<<v19-57-8,8>>^ Desperta, minha alma; despertai, alaúde e harpa; eu mesmo despertarei a aurora.

[[v19-57-9]]

^<<v19-57-9,9>>^ Louvar-te-ei, Senhor, entre os povos; cantar-te-ei louvores entre as nações.

[[v19-57-10]]

^<<v19-57-10,10>>^ Pois a tua benignidade é grande até os céus, e a tua verdade até as nuvens.

[[v19-57-11]]

^<<v19-57-11,11>>^ Sê exaltado, ó Deus, acima dos céus; e seja a tua glória sobre a terra.

'''

xref:019-salmos/019-salmos-056.adoc#v19-56-0[&#60; Capítulo Anterior] | <<v19-57-0,Topo>> | xref:019-salmos/019-salmos-058.adoc#v19-58-0[Próximo Capítulo &#62;]