include::./index.adoc[]

[[v19-9-0]]
=== Salmos, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-9-1]]

^<<v19-9-1,1>>^ Eu te louvarei, Senhor, de todo o meu coração; contarei todas as tuas maravilhas.

[[v19-9-2]]

^<<v19-9-2,2>>^ Em ti me alegrarei e exultarei; cantarei louvores ao teu nome, ó Altíssimo;

[[v19-9-3]]

^<<v19-9-3,3>>^ porquanto os meus inimigos retrocedem, caem e perecem diante de ti.

[[v19-9-4]]

^<<v19-9-4,4>>^ Sustentaste o meu direito e a minha causa; tu te assentaste no tribunal, julgando justamente.

[[v19-9-5]]

^<<v19-9-5,5>>^ Repreendeste as nações, destruíste os ímpios; apagaste o seu nome para sempre e eternamente.

[[v19-9-6]]

^<<v19-9-6,6>>^ Os inimigos consumidos estão; perpétuas são as suas ruínas.

[[v19-9-7]]

^<<v19-9-7,7>>^ Mas o Senhor está entronizado para sempre; preparou o seu trono para exercer o juízo.

[[v19-9-8]]

^<<v19-9-8,8>>^ Ele mesmo julga o mundo com justiça; julga os povos com eqüidade.

[[v19-9-9]]

^<<v19-9-9,9>>^ O Senhor é também um alto refúgio para o oprimido, um alto refúgio em tempos de angústia.

[[v19-9-10]]

^<<v19-9-10,10>>^ Em ti confiam os que conhecem o teu nome; porque tu, Senhor, não abandonas aqueles que te buscam.

[[v19-9-11]]

^<<v19-9-11,11>>^ Cantai louvores ao Senhor, que habita em Sião; anunciai entre os povos os seus feitos.

[[v19-9-12]]

^<<v19-9-12,12>>^ Pois ele, o vingador do sangue, se lembra deles; não se esquece do clamor dos aflitos.

[[v19-9-13]]

^<<v19-9-13,13>>^ Tem misericórdia de mim, Senhor; olha a aflição que sofro daqueles que me odeiam, tu que me levantas das portas da morte.

[[v19-9-14]]

^<<v19-9-14,14>>^ para que eu conte todos os teus louvores nas portas da filha de Sião e me alegre na tua salvação.

[[v19-9-15]]

^<<v19-9-15,15>>^ Afundaram-se as nações na cova que abriram; na rede que ocultaram ficou preso o seu pé.

[[v19-9-16]]

^<<v19-9-16,16>>^ O Senhor deu-se a conhecer, executou o juízo; enlaçado ficou o ímpio nos seus próprios feitos.

[[v19-9-17]]

^<<v19-9-17,17>>^ Os ímpios irão para o Seol, sim, todas as nações que se esquecem de Deus.

[[v19-9-18]]

^<<v19-9-18,18>>^ Pois o necessitado não será esquecido para sempre, nem a esperança dos pobres será frustrada perpetuamente.

[[v19-9-19]]

^<<v19-9-19,19>>^ Levanta-te, Senhor! Não prevaleça o homem; sejam julgadas as nações na tua presença!

[[v19-9-20]]

^<<v19-9-20,20>>^ Senhor, incute-lhes temor! Que as nações saibam que não passam de meros homens!

'''

xref:019-salmos/019-salmos-008.adoc#v19-8-0[&#60; Capítulo Anterior] | <<v19-9-0,Topo>> | xref:019-salmos/019-salmos-010.adoc#v19-10-0[Próximo Capítulo &#62;]