include::./index.adoc[]

[[v19-21-0]]
=== Salmos, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-21-1]]

^<<v19-21-1,1>>^ Na tua força, ó Senhor, o rei se alegra; e na tua salvação quão grandemente se regozija!

[[v19-21-2]]

^<<v19-21-2,2>>^ Concedeste-lhe o desejo do seu coração, e não lhe negaste a petição dos seus lábios.

[[v19-21-3]]

^<<v19-21-3,3>>^ Pois o proveste de bênçãos excelentes; puseste-lhe na cabeça uma coroa de ouro fino.

[[v19-21-4]]

^<<v19-21-4,4>>^ Vida te pediu, e lha deste, longura de dias para sempre e eternamente.

[[v19-21-5]]

^<<v19-21-5,5>>^ Grande é a sua glória pelo teu socorro; de honra e de majestade o revestes.

[[v19-21-6]]

^<<v19-21-6,6>>^ Sim, tu o fazes para sempre abençoado; tu o enches de gozo na tua presença.

[[v19-21-7]]

^<<v19-21-7,7>>^ Pois o rei confia no Senhor; e pela bondade do Altíssimo permanecerá inabalável.

[[v19-21-8]]

^<<v19-21-8,8>>^ A tua mão alcançará todos os teus inimigos, a tua destra alcançará todos os que te odeiam.

[[v19-21-9]]

^<<v19-21-9,9>>^ Tu os farás qual fornalha ardente quando vieres; o Senhor os consumirá na sua indignação, e o fogo os devorará.

[[v19-21-10]]

^<<v19-21-10,10>>^ A sua prole destruirás da terra, e a sua descendência dentre os filhos dos homens.

[[v19-21-11]]

^<<v19-21-11,11>>^ Pois intentaram o mal contra ti; maquinaram um ardil, mas não prevalecerão.

[[v19-21-12]]

^<<v19-21-12,12>>^ Porque tu os porás em fuga; contra os seus rostos assestarás o teu arco.

[[v19-21-13]]

^<<v19-21-13,13>>^ Exalta-te, Senhor, na tua força; então cantaremos e louvaremos o teu poder.

'''

xref:019-salmos/019-salmos-020.adoc#v19-20-0[&#60; Capítulo Anterior] | <<v19-21-0,Topo>> | xref:019-salmos/019-salmos-022.adoc#v19-22-0[Próximo Capítulo &#62;]