include::./index.adoc[]

[[v19-91-0]]
=== Salmos, 91
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-91-1]]

^<<v19-91-1,1>>^ Aquele que habita no esconderijo do Altíssimo, à sombra do Todo-Poderoso descansará.

[[v19-91-2]]

^<<v19-91-2,2>>^ Direi do Senhor: Ele é o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.

[[v19-91-3]]

^<<v19-91-3,3>>^ Porque ele te livra do laço do passarinho, e da peste perniciosa.

[[v19-91-4]]

^<<v19-91-4,4>>^ Ele te cobre com as suas penas, e debaixo das suas asas encontras refúgio; a sua verdade é escudo e broquel.

[[v19-91-5]]

^<<v19-91-5,5>>^ Não temerás os terrores da noite, nem a seta que voe de dia,

[[v19-91-6]]

^<<v19-91-6,6>>^ nem peste que anda na escuridão, nem mortandade que assole ao meio-dia.

[[v19-91-7]]

^<<v19-91-7,7>>^ Mil poderão cair ao teu lado, e dez mil à tua direita; mas tu não serás atingido.

[[v19-91-8]]

^<<v19-91-8,8>>^ Somente com os teus olhos contemplarás, e verás a recompensa dos ímpios.

[[v19-91-9]]

^<<v19-91-9,9>>^ Porquanto fizeste do Senhor o teu refúgio, e do Altíssimo a tua habitação,

[[v19-91-10]]

^<<v19-91-10,10>>^ nenhum mal te sucederá, nem praga alguma chegará à tua tenda.

[[v19-91-11]]

^<<v19-91-11,11>>^ Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos.

[[v19-91-12]]

^<<v19-91-12,12>>^ Eles te susterão nas suas mãos, para que não tropeces em alguma pedra.

[[v19-91-13]]

^<<v19-91-13,13>>^ Pisarás o leão e a áspide; calcarás aos pés o filho do leão e a serpente.

[[v19-91-14]]

^<<v19-91-14,14>>^ Pois que tanto me amou, eu o livrarei; pô-lo-ei num alto retiro, porque ele conhece o meu nome.

[[v19-91-15]]

^<<v19-91-15,15>>^ Quando ele me invocar, eu lhe responderei; estarei com ele na angústia, livrá-lo-ei, e o honrarei.

[[v19-91-16]]

^<<v19-91-16,16>>^ Com longura de dias fartá-lo-ei, e lhe mostrarei a minha salvação.

'''

xref:019-salmos/019-salmos-090.adoc#v19-90-0[&#60; Capítulo Anterior] | <<v19-91-0,Topo>> | xref:019-salmos/019-salmos-092.adoc#v19-92-0[Próximo Capítulo &#62;]