include::./index.adoc[]

[[v19-85-0]]
=== Salmos, 85
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-85-1]]

^<<v19-85-1,1>>^ Mostraste favor, Senhor, à tua terra; fizeste regressar os cativos de Jacó.

[[v19-85-2]]

^<<v19-85-2,2>>^ Perdoaste a iniqüidade do teu povo; cobriste todos os seus pecados.

[[v19-85-3]]

^<<v19-85-3,3>>^ Retraíste toda a tua cólera; refreaste o ardor da tua ira.

[[v19-85-4]]

^<<v19-85-4,4>>^ Restabelece-nos, ó Deus da nossa salvação, e faze cessar a tua indignação contra nós.

[[v19-85-5]]

^<<v19-85-5,5>>^ Estarás para sempre irado contra nós? estenderás a tua ira a todas as gerações?

[[v19-85-6]]

^<<v19-85-6,6>>^ Não tornarás a vivificar-nos, para que o teu povo se regozije em ti?

[[v19-85-7]]

^<<v19-85-7,7>>^ Mostra-nos, Senhor, a tua benignidade, e concede-nos a tua salvação.

[[v19-85-8]]

^<<v19-85-8,8>>^ Escutarei o que Deus, o Senhor, disser; porque falará de paz ao seu povo, e aos seus santos, contanto que não voltem à insensatez.

[[v19-85-9]]

^<<v19-85-9,9>>^ Certamente que a sua salvação está perto daqueles que o temem, para que a glória habite em nossa terra.

[[v19-85-10]]

^<<v19-85-10,10>>^ A benignidade e a fidelidade se encontraram; a justiça e a paz se beijaram.

[[v19-85-11]]

^<<v19-85-11,11>>^ A fidelidade brota da terra, e a justiça olha desde o céu.

[[v19-85-12]]

^<<v19-85-12,12>>^ O Senhor dará o que é bom, e a nossa terra produzirá o seu fruto.

[[v19-85-13]]

^<<v19-85-13,13>>^ A justiça irá adiante dele, marcando o caminho com as suas pegadas.

'''

xref:019-salmos/019-salmos-084.adoc#v19-84-0[&#60; Capítulo Anterior] | <<v19-85-0,Topo>> | xref:019-salmos/019-salmos-086.adoc#v19-86-0[Próximo Capítulo &#62;]