include::./index.adoc[]

[[v19-18-0]]
=== Salmos, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-18-1]]

^<<v19-18-1,1>>^ Eu te amo, ó Senhor, força minha.

[[v19-18-2]]

^<<v19-18-2,2>>^ O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus, o meu rochedo, em quem me refúgio; o meu escudo, a força da minha salvação, e o meu alto refúgio.

[[v19-18-3]]

^<<v19-18-3,3>>^ Invoco o Senhor, que é digno de louvor, e sou salvo dos meus inimigos.

[[v19-18-4]]

^<<v19-18-4,4>>^ Cordas de morte me cercaram, e torrentes de perdição me amedrontaram.

[[v19-18-5]]

^<<v19-18-5,5>>^ Cordas de Seol me cingiram, laços de morte me surpreenderam.

[[v19-18-6]]

^<<v19-18-6,6>>^ Na minha angústia invoquei o Senhor, sim, clamei ao meu Deus; do seu templo ouviu ele a minha voz; o clamor que eu lhe fiz chegou aos seus ouvidos.

[[v19-18-7]]

^<<v19-18-7,7>>^ Então a terra se abalou e tremeu, e os fundamentos dos montes também se moveram e se abalaram, porquanto ele se indignou.

[[v19-18-8]]

^<<v19-18-8,8>>^ Das suas narinas subiu fumaça, e da sua boca saiu fogo devorador; dele saíram brasas ardentes.

[[v19-18-9]]

^<<v19-18-9,9>>^ Ele abaixou os céus e desceu; trevas espessas havia debaixo de seus pés.

[[v19-18-10]]

^<<v19-18-10,10>>^ Montou num querubim, e voou; sim, voou sobre as asas do vento.

[[v19-18-11]]

^<<v19-18-11,11>>^ Fez das trevas o seu retiro secreto; o pavilhão que o cercava era a escuridão das águas e as espessas nuvens do céu.

[[v19-18-12]]

^<<v19-18-12,12>>^ Do resplendor da sua presença saíram, pelas suas espessas nuvens, saraiva e brasas de fogo.

[[v19-18-13]]

^<<v19-18-13,13>>^ O Senhor trovejou a sua voz; e havia saraiva e brasas de fogo.

[[v19-18-14]]

^<<v19-18-14,14>>^ Despediu as suas setas, e os espalhou; multiplicou raios, e os perturbou.

[[v19-18-15]]

^<<v19-18-15,15>>^ Então foram vistos os leitos das águas, e foram descobertos os fundamentos do mundo, à tua repreensão, Senhor, ao sopro do vento das tuas narinas.

[[v19-18-16]]

^<<v19-18-16,16>>^ Do alto estendeu o braço e me tomou; tirou-me das muitas águas.

[[v19-18-17]]

^<<v19-18-17,17>>^ Livrou-me do meu inimigo forte e daqueles que me odiavam; pois eram mais poderosos do que eu.

[[v19-18-18]]

^<<v19-18-18,18>>^ Surpreenderam-me eles no dia da minha calamidade, mas o Senhor foi o meu amparo.

[[v19-18-19]]

^<<v19-18-19,19>>^ Trouxe-me para um lugar espaçoso; livrou-me, porque tinha prazer em mim.

[[v19-18-20]]

^<<v19-18-20,20>>^ Recompensou-me o Senhor conforme a minha justiça, retribuiu-me conforme a pureza das minhas mãos.

[[v19-18-21]]

^<<v19-18-21,21>>^ Pois tenho guardado os caminhos do Senhor, e não me apartei impiamente do meu Deus.

[[v19-18-22]]

^<<v19-18-22,22>>^ Porque todas as suas ordenanças estão diante de mim, e nunca afastei de mim os seus estatutos.

[[v19-18-23]]

^<<v19-18-23,23>>^ Também fui irrepreensível diante dele, e me guardei da iniqüidade.

[[v19-18-24]]

^<<v19-18-24,24>>^ Pelo que o Senhor me recompensou conforme a minha justiça, conforme a pureza de minhas mãos perante os seus olhos.

[[v19-18-25]]

^<<v19-18-25,25>>^ Para com o benigno te mostras benigno, e para com o homem perfeito te mostras perfeito.

[[v19-18-26]]

^<<v19-18-26,26>>^ Para com o puro te mostras puro, e para com o perverso te mostras contrário.

[[v19-18-27]]

^<<v19-18-27,27>>^ Porque tu livras o povo aflito, mas os olhos altivos tu os abates.

[[v19-18-28]]

^<<v19-18-28,28>>^ Sim, tu acendes a minha candeia; o Senhor meu Deus alumia as minhas trevas.

[[v19-18-29]]

^<<v19-18-29,29>>^ Com o teu auxílio dou numa tropa; com o meu Deus salto uma muralha.

[[v19-18-30]]

^<<v19-18-30,30>>^ Quanto a Deus, o seu caminho é perfeito; a promessa do Senhor é provada; ele é um escudo para todos os que nele confiam.

[[v19-18-31]]

^<<v19-18-31,31>>^ Pois, quem é Deus senão o Senhor? e quem é rochedo senão o nosso Deus?

[[v19-18-32]]

^<<v19-18-32,32>>^ Ele é o Deus que me cinge de força e torna perfeito o meu caminho;

[[v19-18-33]]

^<<v19-18-33,33>>^ faz os meus pés como os das corças, e me coloca em segurança nos meus lugares altos.

[[v19-18-34]]

^<<v19-18-34,34>>^ Adestra as minhas mãos para a peleja, de sorte que os meus braços vergam um arco de bronze.

[[v19-18-35]]

^<<v19-18-35,35>>^ Também me deste o escudo da tua salvação; a tua mão direita me sustém, e a tua clemência me engrandece.

[[v19-18-36]]

^<<v19-18-36,36>>^ Alargas o caminho diante de mim, e os meus pés não resvalam.

[[v19-18-37]]

^<<v19-18-37,37>>^ Persigo os meus inimigos, e os alcanço; não volto senão depois de os ter consumido.

[[v19-18-38]]

^<<v19-18-38,38>>^ Atravesso-os, de modo que nunca mais se podem levantar; caem debaixo dos meus pés.

[[v19-18-39]]

^<<v19-18-39,39>>^ Pois me cinges de força para a peleja; prostras debaixo de mim aqueles que contra mim se levantam.

[[v19-18-40]]

^<<v19-18-40,40>>^ Fazes também que os meus inimigos me dêem as costas; aos que me odeiam eu os destruo.

[[v19-18-41]]

^<<v19-18-41,41>>^ Clamam, porém não há libertador; clamam ao Senhor, mas ele não lhes responde.

[[v19-18-42]]

^<<v19-18-42,42>>^ Então os esmiuço como o pó diante do vento; lanço-os fora como a lama das ruas.

[[v19-18-43]]

^<<v19-18-43,43>>^ Livras-me das contendas do povo, e me fazes cabeça das nações; um povo que eu não conhecia se me sujeita.

[[v19-18-44]]

^<<v19-18-44,44>>^ Ao ouvirem de mim, logo me obedecem; com lisonja os estrangeiros se me submetem.

[[v19-18-45]]

^<<v19-18-45,45>>^ Os estrangeiros desfalecem e, tremendo, saem dos seus esconderijos.

[[v19-18-46]]

^<<v19-18-46,46>>^ Vive o Senhor; bendita seja a minha rocha, e exaltado seja o Deus da minha salvação,

[[v19-18-47]]

^<<v19-18-47,47>>^ o Deus que me dá vingança, e sujeita os povos debaixo de mim,

[[v19-18-48]]

^<<v19-18-48,48>>^ que me livra de meus inimigos; sim, tu me exaltas sobre os que se levantam contra mim; tu me livras do homem violento.

[[v19-18-49]]

^<<v19-18-49,49>>^ Pelo que, ó Senhor, te louvarei entre as nações, e entoarei louvores ao teu nome.

[[v19-18-50]]

^<<v19-18-50,50>>^ Ele dá grande livramento ao seu rei, e usa de benignidade para com o seu ungido, para com Davi e sua posteridade, para sempre.

'''

xref:019-salmos/019-salmos-017.adoc#v19-17-0[&#60; Capítulo Anterior] | <<v19-18-0,Topo>> | xref:019-salmos/019-salmos-019.adoc#v19-19-0[Próximo Capítulo &#62;]