include::./index.adoc[]

[[v19-14-0]]
=== Salmos, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-14-1]]

^<<v19-14-1,1>>^ Diz o néscio no seu coração: Não há Deus. Os homens têm-se corrompido, fazem-se abomináveis em suas obras; não há quem faça o bem.

[[v19-14-2]]

^<<v19-14-2,2>>^ O Senhor olhou do céu para os filhos dos homens, para ver se havia algum que tivesse entendimento, que buscasse a Deus.

[[v19-14-3]]

^<<v19-14-3,3>>^ Desviaram-se todos e juntamente se fizeram imundos; não há quem faça o bem, não há sequer um.

[[v19-14-4]]

^<<v19-14-4,4>>^ Acaso não tem conhecimento nem sequer um dos que praticam a iniqüidade, que comem o meu povo como se comessem pão, e que não invocam o Senhor?

[[v19-14-5]]

^<<v19-14-5,5>>^ Achar-se-ão ali em grande pavor, porque Deus está na geração dos justos.

[[v19-14-6]]

^<<v19-14-6,6>>^ Vós quereis frustar o conselho dos pobres, mas o Senhor é o seu refúgio.

[[v19-14-7]]

^<<v19-14-7,7>>^ Oxalá que de Sião viesse a salvação de Israel! Quando o Senhor fizer voltar os cativos do seu povo, então se regozijará Jacó e se alegrará Israel.

'''

xref:019-salmos/019-salmos-013.adoc#v19-13-0[&#60; Capítulo Anterior] | <<v19-14-0,Topo>> | xref:019-salmos/019-salmos-015.adoc#v19-15-0[Próximo Capítulo &#62;]