include::./index.adoc[]

[[v19-71-0]]
=== Salmos, 71
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-71-1]]

^<<v19-71-1,1>>^ Em ti, Senhor, me refugio; nunca seja eu confundido.

[[v19-71-2]]

^<<v19-71-2,2>>^ Na tua justiça socorre-me e livra-me; inclina os teus ouvidos para mim, e salva-me.

[[v19-71-3]]

^<<v19-71-3,3>>^ Sê tu para mim uma rocha de refúgio a que sempre me acolha; deste ordem para que eu seja salvo, pois tu és a minha rocha e a minha fortaleza.

[[v19-71-4]]

^<<v19-71-4,4>>^ Livra-me, Deus meu, da mão do ímpio, do poder do homem injusto e cruel,

[[v19-71-5]]

^<<v19-71-5,5>>^ Pois tu és a minha esperança, Senhor Deus; tu és a minha confiança desde a minha mocidade.

[[v19-71-6]]

^<<v19-71-6,6>>^ Em ti me tenho apoiado desde que nasci; tu és aquele que me tiraste das entranhas de minha mãe. O meu louvor será teu constantemente.

[[v19-71-7]]

^<<v19-71-7,7>>^ Sou para muitos um assombro, mas tu és o meu refúgio forte.

[[v19-71-8]]

^<<v19-71-8,8>>^ A minha boca se enche do teu louvor e da tua glória continuamente.

[[v19-71-9]]

^<<v19-71-9,9>>^ Não me enjeites no tempo da velhice; não me desampares, quando se forem acabando as minhas forças.

[[v19-71-10]]

^<<v19-71-10,10>>^ Porque os meus inimigos falam de mim, e os que espreitam a minha vida consultam juntos,

[[v19-71-11]]

^<<v19-71-11,11>>^ dizendo: Deus o desamparou; persegui-o e prendei-o, pois não há quem o livre.

[[v19-71-12]]

^<<v19-71-12,12>>^ Ó Deus, não te alongues de mim; meu Deus, apressa-te em socorrer-me.

[[v19-71-13]]

^<<v19-71-13,13>>^ Sejam envergonhados e consumidos os meus adversários; cubram-se de opróbrio e de confusão aqueles que procuram o meu mal.

[[v19-71-14]]

^<<v19-71-14,14>>^ Mas eu esperarei continuamente, e te louvarei cada vez mais.

[[v19-71-15]]

^<<v19-71-15,15>>^ A minha boca falará da tua justiça e da tua salvação todo o dia, posto que não conheça a sua grandeza.

[[v19-71-16]]

^<<v19-71-16,16>>^ Virei na força do Senhor Deus; farei menção da tua justiça, da tua tão somente.

[[v19-71-17]]

^<<v19-71-17,17>>^ Ensinaste-me, ó Deus, desde a minha mocidade; e até aqui tenho anunciado as tuas maravilhas.

[[v19-71-18]]

^<<v19-71-18,18>>^ Agora, quando estou velho e de cabelos brancos, não me desampares, ó Deus, até que tenha anunciado a tua força a esta geração, e o teu poder a todos os vindouros.

[[v19-71-19]]

^<<v19-71-19,19>>^ A tua justiça, ó Deus, atinge os altos céus; tu tens feito grandes coisas; ó Deus, quem é semelhante a ti?

[[v19-71-20]]

^<<v19-71-20,20>>^ Tu, que me fizeste ver muitas e penosas tribulações, de novo me restituirás a vida, e de novo me tirarás dos abismos da terra.

[[v19-71-21]]

^<<v19-71-21,21>>^ Aumentarás a minha grandeza, e de novo me consolarás.

[[v19-71-22]]

^<<v19-71-22,22>>^ Também eu te louvarei ao som do saltério, pela tua fidelidade, ó meu Deus; cantar-te-ei ao som da harpa, ó Santo de Israel.

[[v19-71-23]]

^<<v19-71-23,23>>^ Os meus lábios exultarão quando eu cantar os teus louvores, assim como a minha alma, que tu remiste.

[[v19-71-24]]

^<<v19-71-24,24>>^ Também a minha língua falará da tua justiça o dia todo; pois estão envergonhados e confundidos aqueles que procuram o meu mal.

'''

xref:019-salmos/019-salmos-070.adoc#v19-70-0[&#60; Capítulo Anterior] | <<v19-71-0,Topo>> | xref:019-salmos/019-salmos-072.adoc#v19-72-0[Próximo Capítulo &#62;]