include::./index.adoc[]

[[v19-74-0]]
=== Salmos, 74
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-74-1]]

^<<v19-74-1,1>>^ Ó Deus, por que nos rejeitaste para sempre? Por que se acende a tua ira contra o rebanho do teu pasto?

[[v19-74-2]]

^<<v19-74-2,2>>^ Lembra-te da tua congregação, que compraste desde a antigüidade, que remiste para ser a tribo da tua herança, e do monte Sião, em que tens habitado.

[[v19-74-3]]

^<<v19-74-3,3>>^ Dirige os teus passos para as perpétuas ruínas, para todo o mal que o inimigo tem feito no santuário.

[[v19-74-4]]

^<<v19-74-4,4>>^ Os teus inimigos bramam no meio da tua assembléia; põem nela as suas insígnias por sinais.

[[v19-74-5]]

^<<v19-74-5,5>>^ A entrada superior cortaram com machados a grade de madeira.

[[v19-74-6]]

^<<v19-74-6,6>>^ Eis que toda obra entalhada, eles a despedaçaram a machados e martelos.

[[v19-74-7]]

^<<v19-74-7,7>>^ Lançaram fogo ao teu santuário; profanaram, derrubando-a até o chão, a morada do teu nome.

[[v19-74-8]]

^<<v19-74-8,8>>^ Disseram no seu coração: Despojemo-la duma vez. Queimaram todas as sinagogas de Deus na terra.

[[v19-74-9]]

^<<v19-74-9,9>>^ Não vemos mais as nossas insígnias, não há mais profeta; nem há entre nós alguém que saiba até quando isto durará.

[[v19-74-10]]

^<<v19-74-10,10>>^ Até quando, ó Deus, o adversário afrontará? O inimigo ultrajará o teu nome para sempre?

[[v19-74-11]]

^<<v19-74-11,11>>^ Por que reténs a tua mão, sim, a tua destra? Tira-a do teu seio, e consome-os.

[[v19-74-12]]

^<<v19-74-12,12>>^ Todavia, Deus é o meu Rei desde a antigüidade, operando a salvação no meio da terra.

[[v19-74-13]]

^<<v19-74-13,13>>^ Tu dividiste o mar pela tua força; esmigalhaste a cabeça dos monstros marinhos sobre as águas.

[[v19-74-14]]

^<<v19-74-14,14>>^ Tu esmagaste as cabeças do leviatã, e o deste por mantimento aos habitantes do deserto.

[[v19-74-15]]

^<<v19-74-15,15>>^ Tu abriste fontes e ribeiros; tu secaste os rios perenes.

[[v19-74-16]]

^<<v19-74-16,16>>^ Teu é o dia e tua é a noite: tu preparaste a luz e o sol.

[[v19-74-17]]

^<<v19-74-17,17>>^ Tu estabeleceste todos os limites da terra; verão e inverno, tu os fizeste.

[[v19-74-18]]

^<<v19-74-18,18>>^ Lembra-te disto: que o inimigo te afrontou, ó Senhor, e que um povo insensato ultrajou o teu nome.

[[v19-74-19]]

^<<v19-74-19,19>>^ Não entregues às feras a alma da tua rola; não te esqueça para sempre da vida dos teus aflitos.

[[v19-74-20]]

^<<v19-74-20,20>>^ Atenta para o teu pacto, pois os lugares tenebrosos da terra estão cheios das moradas de violência.

[[v19-74-21]]

^<<v19-74-21,21>>^ Não volte envergonhado o oprimido; louvem o teu nome o aflito e o necessitado.

[[v19-74-22]]

^<<v19-74-22,22>>^ Levanta-te, ó Deus, pleiteia a tua própria causa; lembra-te da afronta que o insensato te faz continuamente.

[[v19-74-23]]

^<<v19-74-23,23>>^ Não te esqueças da gritaria dos teus adversários; o tumulto daqueles que se levantam contra ti sobe continuamente.

'''

xref:019-salmos/019-salmos-073.adoc#v19-73-0[&#60; Capítulo Anterior] | <<v19-74-0,Topo>> | xref:019-salmos/019-salmos-075.adoc#v19-75-0[Próximo Capítulo &#62;]