include::./index.adoc[]

[[v19-56-0]]
=== Salmos, 56
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-56-1]]

^<<v19-56-1,1>>^ Compadece-te de mim, ó Deus, pois homens me calcam aos pés e, pelejando, me aflingem o dia todo.

[[v19-56-2]]

^<<v19-56-2,2>>^ Os meus inimigos me calcam aos pés o dia todo, pois são muitos os que insolentemente pelejam contra mim.

[[v19-56-3]]

^<<v19-56-3,3>>^ No dia em que eu temer, hei de confiar em ti.

[[v19-56-4]]

^<<v19-56-4,4>>^ Em Deus, cuja palavra eu louvo, em Deus ponho a minha confiança e não terei medo;

[[v19-56-5]]

^<<v19-56-5,5>>^ Todos os dias torcem as minhas palavras; todos os seus pensamentos são contra mim para o mal.

[[v19-56-6]]

^<<v19-56-6,6>>^ Ajuntam-se, escondem-se, espiam os meus passos, como que aguardando a minha morte.

[[v19-56-7]]

^<<v19-56-7,7>>^ Escaparão eles por meio da sua iniqüidade? Ó Deus, derruba os povos na tua ira!

[[v19-56-8]]

^<<v19-56-8,8>>^ Tu contaste as minhas aflições; põe as minhas lágrimas no teu odre; não estão elas no teu livro?

[[v19-56-9]]

^<<v19-56-9,9>>^ No dia em que eu te invocar retrocederão os meus inimigos; isto eu sei, que Deus está comigo.

[[v19-56-10]]

^<<v19-56-10,10>>^ Em Deus, cuja palavra eu louvo, no Senhor, cuja palavra eu louvo,

[[v19-56-11]]

^<<v19-56-11,11>>^ em Deus ponho a minha confiança, e não terei medo; que me pode fazer o homem?

[[v19-56-12]]

^<<v19-56-12,12>>^ Sobre mim estão os votos que te fiz, ó Deus; eu te oferecerei ações de graças;

[[v19-56-13]]

^<<v19-56-13,13>>^ pois tu livraste a minha alma da morte. Não livraste também os meus pés de tropeçarem, para que eu ande diante de Deus na luz da vida?

'''

xref:019-salmos/019-salmos-055.adoc#v19-55-0[&#60; Capítulo Anterior] | <<v19-56-0,Topo>> | xref:019-salmos/019-salmos-057.adoc#v19-57-0[Próximo Capítulo &#62;]