include::./index.adoc[]

[[v19-112-0]]
=== Salmos, 112
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-112-1]]

^<<v19-112-1,1>>^ Louvai ao Senhor. Bem-aventurado o homem que teme ao Senhor, que em seus mandamentos tem grande prazer!

[[v19-112-2]]

^<<v19-112-2,2>>^ A sua descendência será poderosa na terra; a geração dos retos será abençoada.

[[v19-112-3]]

^<<v19-112-3,3>>^ Bens e riquezas há na sua casa; e a sua justiça permanece para sempre.

[[v19-112-4]]

^<<v19-112-4,4>>^ Aos retos nasce luz nas trevas; ele é compassivo, misericordioso e justo.

[[v19-112-5]]

^<<v19-112-5,5>>^ Ditoso é o homem que se compadece, e empresta, que conduz os seus negócios com justiça;

[[v19-112-6]]

^<<v19-112-6,6>>^ pois ele nunca será abalado; o justo ficará em memória eterna.

[[v19-112-7]]

^<<v19-112-7,7>>^ Ele não teme más notícias; o seu coração está firme, confiando no Senhor.

[[v19-112-8]]

^<<v19-112-8,8>>^ O seu coração está bem firmado, ele não terá medo, até que veja cumprido o seu desejo sobre os seus adversários.

[[v19-112-9]]

^<<v19-112-9,9>>^ Espalhou, deu aos necessitados; a sua justiça subsiste para sempre; o seu poder será exaltado em honra.

[[v19-112-10]]

^<<v19-112-10,10>>^ O ímpio vê isto e se enraivece; range os dentes e se consome; o desejo dos ímpios perecerá.

'''

xref:019-salmos/019-salmos-111.adoc#v19-111-0[&#60; Capítulo Anterior] | <<v19-112-0,Topo>> | xref:019-salmos/019-salmos-113.adoc#v19-113-0[Próximo Capítulo &#62;]