include::./index.adoc[]

[[v19-103-0]]
=== Salmos, 103
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-103-1]]

^<<v19-103-1,1>>^ Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome.

[[v19-103-2]]

^<<v19-103-2,2>>^ Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum dos seus benefícios.

[[v19-103-3]]

^<<v19-103-3,3>>^ É ele quem perdoa todas as tuas iniqüidades, quem sara todas as tuas enfermidades,

[[v19-103-4]]

^<<v19-103-4,4>>^ quem redime a tua vida da cova, quem te coroa de benignidade e de misericórdia,

[[v19-103-5]]

^<<v19-103-5,5>>^ quem te supre de todo o bem, de sorte que a tua mocidade se renova como a da águia.

[[v19-103-6]]

^<<v19-103-6,6>>^ O Senhor executa atos de justiça, e juízo a favor de todos os oprimidos.

[[v19-103-7]]

^<<v19-103-7,7>>^ Fez notórios os seus caminhos a Moisés, e os seus feitos aos filhos de Israel.

[[v19-103-8]]

^<<v19-103-8,8>>^ Compassivo e misericordioso é o Senhor; tardio em irar-se e grande em benignidade.

[[v19-103-9]]

^<<v19-103-9,9>>^ Não repreenderá perpetuamente, nem para sempre conservará a sua ira.

[[v19-103-10]]

^<<v19-103-10,10>>^ Não nos trata segundo os nossos pecados, nem nos retribui segundo as nossas iniqüidades.

[[v19-103-11]]

^<<v19-103-11,11>>^ Pois quanto o céu está elevado acima da terra, assim é grande a sua benignidade para com os que o temem.

[[v19-103-12]]

^<<v19-103-12,12>>^ Quanto o oriente está longe do ocidente, tanto tem ele afastado de nós as nossas transgressões.

[[v19-103-13]]

^<<v19-103-13,13>>^ Como um pai se compadece de seus filhos, assim o Senhor se compadece daqueles que o temem.

[[v19-103-14]]

^<<v19-103-14,14>>^ Pois ele conhece a nossa estrutura; lembra-se de que somos pó.

[[v19-103-15]]

^<<v19-103-15,15>>^ Quanto ao homem, os seus dias são como a erva; como a flor do campo, assim ele floresce.

[[v19-103-16]]

^<<v19-103-16,16>>^ Pois, passando por ela o vento, logo se vai, e o seu lugar não a conhece mais.

[[v19-103-17]]

^<<v19-103-17,17>>^ Mas é de eternidade a eternidade a benignidade do Senhor sobre aqueles que o temem, e a sua justiça sobre os filhos dos filhos,

[[v19-103-18]]

^<<v19-103-18,18>>^ sobre aqueles que guardam o seu pacto, e sobre os que se lembram dos seus preceitos para os cumprirem.

[[v19-103-19]]

^<<v19-103-19,19>>^ O Senhor estabeleceu o seu trono nos céus, e o seu reino domina sobre tudo.

[[v19-103-20]]

^<<v19-103-20,20>>^ Bendizei ao Senhor, vós anjos seus, poderosos em força, que cumpris as suas ordens, obedecendo à voz da sua palavra!

[[v19-103-21]]

^<<v19-103-21,21>>^ Bendizei ao Senhor, vós todos os seus exércitos, vós ministros seus, que executais a sua vontade!

[[v19-103-22]]

^<<v19-103-22,22>>^ Bendizei ao Senhor, vós todas as suas obras, em todos os lugares do seu domínio! Bendizei, ó minha alma ao Senhor!

'''

xref:019-salmos/019-salmos-102.adoc#v19-102-0[&#60; Capítulo Anterior] | <<v19-103-0,Topo>> | xref:019-salmos/019-salmos-104.adoc#v19-104-0[Próximo Capítulo &#62;]