include::./index.adoc[]

[[v19-96-0]]
=== Salmos, 96
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-96-1]]

^<<v19-96-1,1>>^ Cantai ao Senhor um cântico novo, cantai ao Senhor, todos os moradores da terra.

[[v19-96-2]]

^<<v19-96-2,2>>^ Cantai ao Senhor, bendizei o seu nome; anunciai de dia em dia a sua salvação.

[[v19-96-3]]

^<<v19-96-3,3>>^ Anunciai entre as nações a sua glória, entre todos os povos as suas maravilhas.

[[v19-96-4]]

^<<v19-96-4,4>>^ Porque grande é o Senhor, e digno de ser louvado; ele é mais temível do que todos os deuses.

[[v19-96-5]]

^<<v19-96-5,5>>^ Porque todos os deuses dos povos são ídolos; mas o Senhor fez os céus.

[[v19-96-6]]

^<<v19-96-6,6>>^ Glória e majestade estão diante dele, força e formosura no seu santuário.

[[v19-96-7]]

^<<v19-96-7,7>>^ Tributai ao Senhor, ó famílias dos povos, tributai ao Senhor glória e força.

[[v19-96-8]]

^<<v19-96-8,8>>^ Tributai ao Senhor a glória devida ao seu nome; trazei oferendas, e entrai nos seus átrios.

[[v19-96-9]]

^<<v19-96-9,9>>^ Adorai ao Senhor vestidos de trajes santos; tremei diante dele, todos os habitantes da terra.

[[v19-96-10]]

^<<v19-96-10,10>>^ Dizei entre as nações: O Senhor reina; ele firmou o mundo, de modo que não pode ser abalado. Ele julgará os povos com retidão.

[[v19-96-11]]

^<<v19-96-11,11>>^ Alegrem-se os céus, e regozije-se a terra; brame o mar e a sua plenitude.

[[v19-96-12]]

^<<v19-96-12,12>>^ Exulte o campo, e tudo o que nele há; então cantarão de júbilo todas as árvores do bosque

[[v19-96-13]]

^<<v19-96-13,13>>^ diante do Senhor, porque ele vem, porque vem julgar a terra: julgará o mundo com justiça e os povos com a sua fidelidade.

'''

xref:019-salmos/019-salmos-095.adoc#v19-95-0[&#60; Capítulo Anterior] | <<v19-96-0,Topo>> | xref:019-salmos/019-salmos-097.adoc#v19-97-0[Próximo Capítulo &#62;]