include::./index.adoc[]

[[v19-139-0]]
=== Salmos, 139
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-139-1]]

^<<v19-139-1,1>>^ Senhor, tu me sondas, e me conheces.

[[v19-139-2]]

^<<v19-139-2,2>>^ Tu conheces o meu sentar e o meu levantar; de longe entendes o meu pensamento.

[[v19-139-3]]

^<<v19-139-3,3>>^ Esquadrinhas o meu andar, e o meu deitar, e conheces todos os meus caminhos.

[[v19-139-4]]

^<<v19-139-4,4>>^ Sem que haja uma palavra na minha língua, eis que, ó Senhor, tudo conheces.

[[v19-139-5]]

^<<v19-139-5,5>>^ Tu me cercaste em volta, e puseste sobre mim a tua mão.

[[v19-139-6]]

^<<v19-139-6,6>>^ Tal conhecimento é maravilhoso demais para mim; elevado é, não o posso atingir.

[[v19-139-7]]

^<<v19-139-7,7>>^ Para onde me irei do teu Espírito, ou para onde fugirei da tua presença?

[[v19-139-8]]

^<<v19-139-8,8>>^ Se subir ao céu, tu aí estás; se fizer no Seol a minha cama, eis que tu ali estás também.

[[v19-139-9]]

^<<v19-139-9,9>>^ Se tomar as asas da alva, se habitar nas extremidades do mar,

[[v19-139-10]]

^<<v19-139-10,10>>^ ainda ali a tua mão me guiará e a tua destra me susterá.

[[v19-139-11]]

^<<v19-139-11,11>>^ Se eu disser: Ocultem-me as trevas; torne-se em noite a luz que me circunda;

[[v19-139-12]]

^<<v19-139-12,12>>^ nem ainda as trevas são escuras para ti, mas a noite resplandece como o dia; as trevas e a luz são para ti a mesma coisa.

[[v19-139-13]]

^<<v19-139-13,13>>^ Pois tu formaste os meus rins; entreteceste-me no ventre de minha mãe.

[[v19-139-14]]

^<<v19-139-14,14>>^ Eu te louvarei, porque de um modo tão admirável e maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.

[[v19-139-15]]

^<<v19-139-15,15>>^ Os meus ossos não te foram encobertos, quando no oculto fui formado, e esmeradamente tecido nas profundezas da terra.

[[v19-139-16]]

^<<v19-139-16,16>>^ Os teus olhos viram a minha substância ainda informe, e no teu livro foram escritos os dias, sim, todos os dias que foram ordenados para mim, quando ainda não havia nem um deles.

[[v19-139-17]]

^<<v19-139-17,17>>^ E quão preciosos me são, ó Deus, os teus pensamentos! Quão grande é a soma deles!

[[v19-139-18]]

^<<v19-139-18,18>>^ Se eu os contasse, seriam mais numerosos do que a areia; quando acordo ainda estou contigo.

[[v19-139-19]]

^<<v19-139-19,19>>^ Oxalá que matasses o perverso, ó Deus, e que os homens sanguinários se apartassem de mim,

[[v19-139-20]]

^<<v19-139-20,20>>^ homens que se rebelam contra ti, e contra ti se levantam para o mal.

[[v19-139-21]]

^<<v19-139-21,21>>^ Não odeio eu, ó Senhor, aqueles que te odeiam? e não me aflijo por causa dos que se levantam contra ti?

[[v19-139-22]]

^<<v19-139-22,22>>^ Odeio-os com ódio completo; tenho-os por inimigos.

[[v19-139-23]]

^<<v19-139-23,23>>^ Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece os meus pensamentos;

[[v19-139-24]]

^<<v19-139-24,24>>^ vê se há em mim algum caminho perverso, e guia-me pelo caminho eterno.

'''

xref:019-salmos/019-salmos-138.adoc#v19-138-0[&#60; Capítulo Anterior] | <<v19-139-0,Topo>> | xref:019-salmos/019-salmos-140.adoc#v19-140-0[Próximo Capítulo &#62;]