include::./index.adoc[]

[[v19-76-0]]
=== Salmos, 76
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-76-1]]

^<<v19-76-1,1>>^ Conhecido é Deus em Judá, grande é o seu nome em Israel.

[[v19-76-2]]

^<<v19-76-2,2>>^ Em Salém está a sua tenda, e a sua morada em Sião.

[[v19-76-3]]

^<<v19-76-3,3>>^ Ali quebrou ele as flechas do arco, o escudo, a espada, e a guerra.

[[v19-76-4]]

^<<v19-76-4,4>>^ Glorioso és tu, mais majestoso do que os montes eternos.

[[v19-76-5]]

^<<v19-76-5,5>>^ Os ousados de coração foram despojados; dormiram o seu último sono; nenhum dos homens de força pôde usar as mãos.

[[v19-76-6]]

^<<v19-76-6,6>>^ À tua repreensão, ó Deus de Jacó, cavaleiros e cavalos ficaram estirados sem sentidos.

[[v19-76-7]]

^<<v19-76-7,7>>^ Tu, sim, tu és tremendo; e quem subsistirá à tua vista, quando te irares?

[[v19-76-8]]

^<<v19-76-8,8>>^ Desde o céu fizeste ouvir o teu juízo; a terra tremeu e se aquietou,

[[v19-76-9]]

^<<v19-76-9,9>>^ quando Deus se levantou para julgar, para salvar a todos os mansos da terra.

[[v19-76-10]]

^<<v19-76-10,10>>^ Na verdade a cólera do homem redundará em teu louvor, e do restante da cólera tu te cingirás.

[[v19-76-11]]

^<<v19-76-11,11>>^ Fazei votos, e pagai-os ao Senhor, vosso Deus; tragam presentes, os que estão em redor dele, àquele que deve ser temido.

[[v19-76-12]]

^<<v19-76-12,12>>^ Ele ceifará o espírito dos príncipes; é tremendo para com os reis da terra.

'''

xref:019-salmos/019-salmos-075.adoc#v19-75-0[&#60; Capítulo Anterior] | <<v19-76-0,Topo>> | xref:019-salmos/019-salmos-077.adoc#v19-77-0[Próximo Capítulo &#62;]