include::./index.adoc[]

[[v19-84-0]]
=== Salmos, 84
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-84-1]]

^<<v19-84-1,1>>^ Quão amável são os teus tabernáculos, ó Senhor dos exércitos!

[[v19-84-2]]

^<<v19-84-2,2>>^ A minha alma suspira! sim, desfalece pelos átrios do Senhor; o meu coração e a minha carne clamam pelo Deus vivo.

[[v19-84-3]]

^<<v19-84-3,3>>^ Até o pardal encontrou casa, e a andorinha ninho para si, onde crie os seus filhotes, junto aos teus altares, ó Senhor dos exércitos, Rei meu e Deus meu.

[[v19-84-4]]

^<<v19-84-4,4>>^ Bem-aventurados os que habitam em tua casa; louvar-te-ão continuamente.

[[v19-84-5]]

^<<v19-84-5,5>>^ Bem-aventurados os homens cuja força está em ti, em cujo coração os caminhos altos.

[[v19-84-6]]

^<<v19-84-6,6>>^ Passando pelo vale de Baca, fazem dele um lugar de fontes; e a primeira chuva o cobre de bênçãos.

[[v19-84-7]]

^<<v19-84-7,7>>^ Vão sempre aumentando de força; cada um deles aparece perante Deus em Sião.

[[v19-84-8]]

^<<v19-84-8,8>>^ Senhor Deus dos exércitos, escuta a minha oração; inclina os ouvidos, ó Deus de Jacó!

[[v19-84-9]]

^<<v19-84-9,9>>^ Olha, ó Deus, escudo nosso, e contempla o rosto do teu ungido.

[[v19-84-10]]

^<<v19-84-10,10>>^ Porque vale mais um dia nos teus átrios do que em outra parte mil. Preferiria estar à porta da casa do meu Deus, a habitar nas tendas da perversidade.

[[v19-84-11]]

^<<v19-84-11,11>>^ Porquanto o Senhor Deus é sol e escudo; o Senhor dará graça e glória; não negará bem algum aos que andam na retidão.

[[v19-84-12]]

^<<v19-84-12,12>>^ Ó Senhor dos exércitos, bem-aventurado o homem que em ti põe a sua confiança.

'''

xref:019-salmos/019-salmos-083.adoc#v19-83-0[&#60; Capítulo Anterior] | <<v19-84-0,Topo>> | xref:019-salmos/019-salmos-085.adoc#v19-85-0[Próximo Capítulo &#62;]