include::./index.adoc[]

[[v19-98-0]]
=== Salmos, 98
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v19-98-1]]

^<<v19-98-1,1>>^ Cantai ao Senhor um cântico novo, porque ele tem feito maravilhas; a sua destra e o seu braço santo lhe alcançaram a vitória.

[[v19-98-2]]

^<<v19-98-2,2>>^ O Senhor fez notória a sua salvação, manifestou a sua justiça perante os olhos das nações.

[[v19-98-3]]

^<<v19-98-3,3>>^ Lembrou-se da sua misericórdia e da sua fidelidade para com a casa de Israel; todas as extremidades da terra viram a salvação do nosso Deus.

[[v19-98-4]]

^<<v19-98-4,4>>^ Celebrai com júbilo ao Senhor, todos os habitantes da terra; dai brados de alegria, regozijai-vos, e cantai louvores.

[[v19-98-5]]

^<<v19-98-5,5>>^ Louvai ao Senhor com a harpa; com a harpa e a voz de canto.

[[v19-98-6]]

^<<v19-98-6,6>>^ Com trombetas, e ao som de buzinas, exultai diante do Rei, o Senhor.

[[v19-98-7]]

^<<v19-98-7,7>>^ Brame o mar e a sua plenitude, o mundo e os que nele habitam;

[[v19-98-8]]

^<<v19-98-8,8>>^ batam palmas os rios; à uma regozijem-se os montes

[[v19-98-9]]

^<<v19-98-9,9>>^ diante do Senhor, porque vem julgar a terra; com justiça julgará o mundo, e os povos com eqüidade.

'''

xref:019-salmos/019-salmos-097.adoc#v19-97-0[&#60; Capítulo Anterior] | <<v19-98-0,Topo>> | xref:019-salmos/019-salmos-099.adoc#v19-99-0[Próximo Capítulo &#62;]