include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v55-3-1]]

^<<v55-3-1,1>>^ Sabe, porém, isto, que nos últimos dias sobrevirão tempos penosos;

[[v55-3-2]]

^<<v55-3-2,2>>^ pois os homens serão amantes de si mesmos, gananciosos, presunçosos, soberbos, blasfemos, desobedientes a seus pais, ingratos, ímpios,

[[v55-3-3]]

^<<v55-3-3,3>>^ sem afeição natural, implacáveis, caluniadores, incontinentes, cruéis, inimigos do bem,

[[v55-3-4]]

^<<v55-3-4,4>>^ traidores, atrevidos, orgulhosos, mais amigos dos deleites do que amigos de Deus,

[[v55-3-5]]

^<<v55-3-5,5>>^ tendo aparência de piedade, mas negando-lhe o poder. Afasta-te também desses.

[[v55-3-6]]

^<<v55-3-6,6>>^ Porque deste número são os que se introduzem pelas casas, e levam cativas mulheres néscias carregadas de pecados, levadas de várias concupiscências;

[[v55-3-7]]

^<<v55-3-7,7>>^ sempre aprendendo, mas nunca podendo chegar ao pleno conhecimento da verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ E assim como Janes e Jambres resistiram a Moisés, assim também estes resistem à verdade, sendo homens corruptos de entendimento e réprobos quanto à fé.

[[v55-3-9]]

^<<v55-3-9,9>>^ Não irão, porém, avante; porque a todos será manifesta a sua insensatez, como também o foi a daqueles.

[[v55-3-10]]

^<<v55-3-10,10>>^ Tu, porém, tens observado a minha doutrina, procedimento, intenção, fé, longanimidade, amor, perseverança,

[[v55-3-11]]

^<<v55-3-11,11>>^ as minhas perseguições e aflições, quais as que sofri em Antioquia, em Icônio, em Listra; quantas perseguições suportei! e de todas o Senhor me livrou.

[[v55-3-12]]

^<<v55-3-12,12>>^ E na verdade todos os que querem viver piamente em Cristo Jesus padecerão perseguições.

[[v55-3-13]]

^<<v55-3-13,13>>^ Mas os homens maus e impostores irão de mal a pior, enganando e sendo enganados.

[[v55-3-14]]

^<<v55-3-14,14>>^ Tu, porém, permanece naquilo que aprendeste, e de que foste inteirado, sabendo de quem o tens aprendido,

[[v55-3-15]]

^<<v55-3-15,15>>^ e que desde a infância sabes as sagradas letras, que podem fazer-te sábio para a salvação, pela que há em Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Toda Escritura é divinamente inspirada e proveitosa para ensinar, para repreender, para corrigir, para instruir em justiça;

[[v55-3-17]]

^<<v55-3-17,17>>^ para que o homem de Deus seja perfeito, e perfeitamente preparado para toda boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]