include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, segundo a promessa da vida que está em Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ a Timóteo, amado filho: Graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus nosso Senhor.

[[v55-1-3]]

^<<v55-1-3,3>>^ Dou graças a Deus, a quem desde os meus antepassados sirvo com uma consciência pura, de que sem cessar faço menção de ti em minhas súplicas de noite e de dia;

[[v55-1-4]]

^<<v55-1-4,4>>^ e, recordando-me das tuas lágrimas, desejo muito ver-te, para me encher de gozo;

[[v55-1-5]]

^<<v55-1-5,5>>^ trazendo à memória a fé não fingida que há em ti, a qual habitou primeiro em tua avó Loide, e em tua mãe Eunice e estou certo de que também habita em ti.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por esta razão te lembro que despertes o dom de Deus, que há em ti pela imposição das minhas mãos.

[[v55-1-7]]

^<<v55-1-7,7>>^ Porque Deus não nos deu o espírito de covardia, mas de poder, de amor e de moderação.

[[v55-1-8]]

^<<v55-1-8,8>>^ Portanto não te envergonhes do testemunho de nosso Senhor, nem de mim, que sou prisioneiro seu; antes participa comigo dos sofrimentos do evangelho segundo o poder de Deus,

[[v55-1-9]]

^<<v55-1-9,9>>^ que nos salvou, e chamou com uma santa vocação, não segundo as nossas obras, mas segundo o seu próprio propósito e a graça que nos foi dada em Cristo Jesus antes dos tempos eternos,

[[v55-1-10]]

^<<v55-1-10,10>>^ e que agora se manifestou pelo aparecimento de nosso Salvador Cristo Jesus, o qual destruiu a morte, e trouxe à luz a vida e a imortalidade pelo evangelho,

[[v55-1-11]]

^<<v55-1-11,11>>^ do qual fui constituído pregador, apóstolo e mestre.

[[v55-1-12]]

^<<v55-1-12,12>>^ Por esta razão sofro também estas coisas, mas não me envergonho; porque eu sei em quem tenho crido, e estou certo de que ele é poderoso para guardar o meu depósito até aquele dia.

[[v55-1-13]]

^<<v55-1-13,13>>^ Conserva o modelo das sãs palavras que de mim tens ouvido na fé e no amor que há em Cristo Jesus;

[[v55-1-14]]

^<<v55-1-14,14>>^ guarda o bom depósito com o auxílio do Espírito Santo, que habita em nós.

[[v55-1-15]]

^<<v55-1-15,15>>^ Bem sabes isto, que me abandonaram todos os que estão na Ásia, entre eles Fígelo e Hermógenes.

[[v55-1-16]]

^<<v55-1-16,16>>^ O Senhor conceda misericórdia à casa de Onesíforo, porque muitas vezes ele me recreou, e não se envergonhou das minhas cadeias;

[[v55-1-17]]

^<<v55-1-17,17>>^ antes quando veio a Roma, diligentemente me procurou e me achou.

[[v55-1-18]]

^<<v55-1-18,18>>^ O Senhor lhe conceda que naquele dia ache misericórdia diante do Senhor. E quantos serviços prestou em Éfeso melhor o sabes tu.

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]