include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v55-4-1]]

^<<v55-4-1,1>>^ Conjuro-te diante de Deus e de Cristo Jesus, que há de julgar os vivos e os mortos, pela sua vinda e pelo seu reino;

[[v55-4-2]]

^<<v55-4-2,2>>^ prega a palavra, insta a tempo e fora de tempo, admoesta, repreende, exorta, com toda longanimidade e ensino.

[[v55-4-3]]

^<<v55-4-3,3>>^ Porque virá tempo em que não suportarão a sã doutrina; mas, tendo grande desejo de ouvir coisas agradáveis, ajuntarão para si mestres segundo os seus próprios desejos,

[[v55-4-4]]

^<<v55-4-4,4>>^ e não só desviarão os ouvidos da verdade, mas se voltarão às fábulas.

[[v55-4-5]]

^<<v55-4-5,5>>^ Tu, porém, sê sóbrio em tudo, sofre as aflições, faze a obra de um evangelista, cumpre o teu ministério.

[[v55-4-6]]

^<<v55-4-6,6>>^ Quanto a mim, já estou sendo derramado como libação, e o tempo da minha partida está próximo.

[[v55-4-7]]

^<<v55-4-7,7>>^ Combati o bom combate, acabei a carreira, guardei a fé.

[[v55-4-8]]

^<<v55-4-8,8>>^ Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele dia; e não somente a mim, mas também a todos os que amarem a sua vinda.

[[v55-4-9]]

^<<v55-4-9,9>>^ Procura vir ter comigo breve;

[[v55-4-10]]

^<<v55-4-10,10>>^ pois Demas me abandonou, tendo amado o mundo presente, e foi para Tessalônica, Crescente para a Galácia, Tito para a Dalmácia;

[[v55-4-11]]

^<<v55-4-11,11>>^ só Lucas está comigo. Toma a Marcos e traze-o contigo, porque me é muito útil para o ministério.

[[v55-4-12]]

^<<v55-4-12,12>>^ Quanto a Tíquico, enviei-o a Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando vieres traze a capa que deixei em Trôade, em casa de Carpo, e os livros, especialmente os pergaminhos.

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o latoeiro, me fez muito mal; o Senhor lhe retribuirá segundo as suas obras.

[[v55-4-15]]

^<<v55-4-15,15>>^ Tu também guarda-te dele; porque resistiu muito às nossas palavras.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na minha primeira defesa ninguém me assistiu, antes todos me desampararam. Que isto não lhes seja imputado.

[[v55-4-17]]

^<<v55-4-17,17>>^ Mas o Senhor esteve ao meu lado e me fortaleceu, para que por mim fosse cumprida a pregação, e a ouvissem todos os gentios; e fiquei livre da boca do leão,

[[v55-4-18]]

^<<v55-4-18,18>>^ E o Senhor me livrará de toda má obra, e me levará salvo para o seu reino celestial; a quem seja glória para todo o sempre. Amém.

[[v55-4-19]]

^<<v55-4-19,19>>^ Saúda a Prisca e a Áquila e à casa de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou em Corinto; a Trófimo deixei doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Apressa-te a vir antes do inverno. Saúdam-te Êubulo, Pudente, Lino, Cláudia, e todos os irmãos.

[[v55-4-22]]

^<<v55-4-22,22>>^ O Senhor seja com o teu espírito. A graça seja convosco. ^Z

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]