include::./index.adoc[]

[[v55-2-0]]
=== 2 Timóteo, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v55-2-1]]

^<<v55-2-1,1>>^ Tu, pois, meu filho, fortifica-te na graça que há em Cristo Jesus;

[[v55-2-2]]

^<<v55-2-2,2>>^ e o que de mim ouviste de muitas testemunhas, transmite-o a homens fiéis, que sejam idôneos para também ensinarem os outros.

[[v55-2-3]]

^<<v55-2-3,3>>^ Sofre comigo como bom soldado de Cristo Jesus.

[[v55-2-4]]

^<<v55-2-4,4>>^ Nenhum soldado em serviço se embaraça com negócios desta vida, a fim de agradar àquele que o alistou para a guerra.

[[v55-2-5]]

^<<v55-2-5,5>>^ E também se um atleta lutar nos jogos públicos, não será coroado se não lutar legitimamente.

[[v55-2-6]]

^<<v55-2-6,6>>^ O lavrador que trabalha deve ser o primeiro a gozar dos frutos.

[[v55-2-7]]

^<<v55-2-7,7>>^ Considera o que digo, porque o Senhor te dará entendimento em tudo.

[[v55-2-8]]

^<<v55-2-8,8>>^ Lembra-te de Jesus Cristo, ressurgido dentre os mortos, descendente de Davi, segundo o meu evangelho,

[[v55-2-9]]

^<<v55-2-9,9>>^ pelo qual sofro a ponto de ser preso como malfeitor; mas a palavra de Deus não está presa.

[[v55-2-10]]

^<<v55-2-10,10>>^ Por isso, tudo suporto por amor dos eleitos, para que também eles alcancem a salvação que há em Cristo Jesus com glória eterna.

[[v55-2-11]]

^<<v55-2-11,11>>^ Fiel é esta palavra: Se, pois, já morremos com ele, também com ele viveremos;

[[v55-2-12]]

^<<v55-2-12,12>>^ se perseveramos, com ele também reinaremos; se o negarmos, também ele nos negará;

[[v55-2-13]]

^<<v55-2-13,13>>^ se somos infiéis, ele permanece fiel; porque não pode negar-se a si mesmo.

[[v55-2-14]]

^<<v55-2-14,14>>^ Lembra-lhes estas coisas, conjurando-os diante de Deus que não tenham contendas de palavras, que para nada aproveitam, senão para subverter os ouvintes.

[[v55-2-15]]

^<<v55-2-15,15>>^ Procura apresentar-te diante de Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.

[[v55-2-16]]

^<<v55-2-16,16>>^ Mas evita as conversas vãs e profanas; porque os que delas usam passarão a impiedade ainda maior,

[[v55-2-17]]

^<<v55-2-17,17>>^ e as suas palavras alastrarão como gangrena; entre os quais estão Himeneu e Fileto,

[[v55-2-18]]

^<<v55-2-18,18>>^ que se desviaram da verdade, dizendo que a ressurreição é já passada, e assim pervertem a fé a alguns.

[[v55-2-19]]

^<<v55-2-19,19>>^ Todavia o firme fundamento de Deus permanece, tendo este selo: O Senhor conhece os seus, e: Aparte-se da injustiça todo aquele que profere o nome do Senhor.

[[v55-2-20]]

^<<v55-2-20,20>>^ Ora, numa grande casa, não somente há vasos de ouro e de prata, mas também de madeira e de barro; e uns, na verdade, para uso honroso, outros, porém, para uso desonroso.

[[v55-2-21]]

^<<v55-2-21,21>>^ Se, pois, alguém se purificar destas coisas, será vaso para honra, santificado e útil ao Senhor, preparado para toda boa obra.

[[v55-2-22]]

^<<v55-2-22,22>>^ Foge também das paixões da mocidade, e segue a justiça, a fé, o amor, a paz com os que, de coração puro, invocam o Senhor.

[[v55-2-23]]

^<<v55-2-23,23>>^ E rejeita as questões tolas e desassisadas, sabendo que geram contendas;

[[v55-2-24]]

^<<v55-2-24,24>>^ e ao servo do Senhor não convém contender, mas sim ser brando para com todos, apto para ensinar, paciente;

[[v55-2-25]]

^<<v55-2-25,25>>^ corrigindo com mansidão os que resistem, na esperança de que Deus lhes conceda o arrependimento para conhecerem plenamente a verdade,

[[v55-2-26]]

^<<v55-2-26,26>>^ e que se desprendam dos laços do Diabo &#123;por quem haviam sido presos&#125;, para cumprirem a vontade de Deus.

'''

xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[&#60; Capítulo Anterior] | <<v55-2-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[Próximo Capítulo &#62;]