include::./index.adoc[]

[[v15-4-0]]
=== Esdras, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-4-1]]

^<<v15-4-1,1>>^ Ora, ouvindo os adversários de Judá e de Benjamim que os que tornaram do cativeiro edificavam o templo ao Senhor, Deus de Israel,

[[v15-4-2]]

^<<v15-4-2,2>>^ chegaram-se a Zorobabel e aos chefes das casas paternas, e disseram-lhes: Deixai-nos edificar convosco; pois, como vós, buscamos o vosso Deus; como também nós lhe temos sacrificado desde os dias de Esar-Hadom, rei da Assíria, que nos fez subir para aqui.

[[v15-4-3]]

^<<v15-4-3,3>>^ Responderam-lhes, porém, Zorobabel e Jesuá e os outros chefes das casas paternas de Israel: Não convém que vós e nós edifiquemos casa a nosso Deus: mas nós sozinhos a edificaremos ao Senhor, Deus de Israel, como nos ordenou o rei Ciro, rei da Pérsia.

[[v15-4-4]]

^<<v15-4-4,4>>^ Então o povo da terra debilitava as mãos do povo de Judá, e os inquietava, impedindo-os de edificar;

[[v15-4-5]]

^<<v15-4-5,5>>^ e assalariaram contra eles conselheiros para frustrarem o seu plano, por todos os dias de Ciro, rei da Pérsia, até o reinado de Dario, rei da Pérsia.

[[v15-4-6]]

^<<v15-4-6,6>>^ No reinado de Assuero, no princípio do seu reino, escreveram uma acusação contra os habitantes de Judá e de Jerusalém.

[[v15-4-7]]

^<<v15-4-7,7>>^ Também nos dias de Artaxerxes escreveram Bislão, Mitredate, Tabeel, e os companheiros destes, a Artaxerxes, rei da Pérsia; e a carta foi escrita em caracteres aramaicos, e traduzida na língua aramaica.

[[v15-4-8]]

^<<v15-4-8,8>>^ Reum, o comandante, e Sinsai, o escrivão, escreveram uma carta contra Jerusalém, ao rei Artaxerxes, do teor seguinte,

[[v15-4-9]]

^<<v15-4-9,9>>^ isto é, escreveram Reum, o comandante, Sinsai, o escrivão, e os seus companheiros, os juízes, os governadores, os oficiais, os persas, os homens de Ereque, os babilônios, os susanquitas, isto é, os elamitas,

[[v15-4-10]]

^<<v15-4-10,10>>^ e as demais nações que o grande e afamado Osnapar transportou, e que fez habitar na cidade de Samária e no restante da província dalém do Rio.

[[v15-4-11]]

^<<v15-4-11,11>>^ Eis, pois, a cópia da carta que mandaram ao rei Artaxerxes: Teus servos, os homens de além do Rio, assim escrevem:

[[v15-4-12]]

^<<v15-4-12,12>>^ Saiba o rei que os judeus que subiram de ti a nós foram a Jerusalém e estão reedificando aquela rebelde e malvada cidade, e vão restaurando os seus muros e reparando os seus fundamentos.

[[v15-4-13]]

^<<v15-4-13,13>>^ Agora saiba o rei que, se aquela cidade for reedificada e os muros forem restaurados, eles não pagarão nem tributo, nem imposto, nem pedágio; e assim se danificará a fazenda dos reis.

[[v15-4-14]]

^<<v15-4-14,14>>^ Agora, visto que comemos do sal do palácio, e não nos convém ver a desonra do rei, por isso mandamos dar aviso ao rei,

[[v15-4-15]]

^<<v15-4-15,15>>^ para que se busque no livro das crônicas de teus pais; e acharás no livro das crônicas e saberás que aquela é uma cidade rebelde, e danosa a reis e províncias, e que nela houve rebelião em tempos antigos; por isso é que ela foi destruída.

[[v15-4-16]]

^<<v15-4-16,16>>^ Nós, pois, estamos avisando ao rei que, se aquela cidade for reedificada e os seus muros forem restaurados, não terás porção alguma a oeste do Rio.

[[v15-4-17]]

^<<v15-4-17,17>>^ Então o rei enviou esta resposta a Reum, o comandante, e a Sinsai, o escrivão, e aos demais seus companheiros, que habitavam em Samária e no restante do país a oeste do Rio: Paz.

[[v15-4-18]]

^<<v15-4-18,18>>^ A carta que nos enviastes foi claramente lida na minha presença.

[[v15-4-19]]

^<<v15-4-19,19>>^ E, ordenando-o eu, buscaram e acharam que desde tempos antigos aquela cidade se tem levantado contra os reis, e que nela se tem feito rebelião e sedição.

[[v15-4-20]]

^<<v15-4-20,20>>^ E tem havido reis poderosos sobre Jerusalém, os quais dominavam igualmente toda a província dalém do Rio; e a eles se pagavam tributos, impostos e pedágio.

[[v15-4-21]]

^<<v15-4-21,21>>^ Agora, pois, dai ordem para que aqueles homens parem, a fim de que não seja edificada aquela cidade até que eu dê ordem.

[[v15-4-22]]

^<<v15-4-22,22>>^ E guardai-vos de serdes remissos nisto; não suceda que o dano cresça em prejuízo dos reis.

[[v15-4-23]]

^<<v15-4-23,23>>^ Então, logo que a cópia da carta do rei Artaxerxes foi lida perante Reum e Sinsai, o escrivão, e seus companheiros, foram eles apressadamente a Jerusalém, aos judeus, e os impediram à força e com violência.

[[v15-4-24]]

^<<v15-4-24,24>>^ Então cessou a obra da casa de Deus, que estava em Jerusalém, ficando interrompida até o segundo ano do reinado de Dario, rei da Pérsia.

'''

xref:015-esdras/015-esdras-003.adoc#v15-3-0[&#60; Capítulo Anterior] | <<v15-4-0,Topo>> | xref:015-esdras/015-esdras-005.adoc#v15-5-0[Próximo Capítulo &#62;]