include::./index.adoc[]

[[v15-7-0]]
=== Esdras, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-7-1]]

^<<v15-7-1,1>>^ Ora, depois destas coisas, no reinado de Artaxerxes, rei da Pérsia, Esdras, filho de Seraías, filho de Azarias, filho de Hilquias,

[[v15-7-2]]

^<<v15-7-2,2>>^ filho de Salum, filho de Zadoque, filho de Aitube,

[[v15-7-3]]

^<<v15-7-3,3>>^ filho de Amarias, filho de Azarias, filho de Meraiote,

[[v15-7-4]]

^<<v15-7-4,4>>^ filho de Zeraías, filho de Uzi, filho de Buqui,

[[v15-7-5]]

^<<v15-7-5,5>>^ filho de Abisua, filho de Finéias, filho de Eleazar, filho de Arão, o sumo sacerdote,

[[v15-7-6]]

^<<v15-7-6,6>>^ este Esdras subiu de Babilônia. E ele era escriba hábil na lei de Moisés, que o Senhor Deus de Israel tinha dado; e segundo a mão de Senhor seu Deus, que estava sobre ele, o rei lhe deu tudo quanto lhe pedira.

[[v15-7-7]]

^<<v15-7-7,7>>^ Também subiram a Jerusalém alguns dos filhos de Israel, dos sacerdotes, dos levitas, dos cantores, dos porteiros e dos netinins, no sétimo ano do rei Artaxerxes.

[[v15-7-8]]

^<<v15-7-8,8>>^ No quinto mês Esdras chegou a Jerusalém, no sétimo ano deste rei.

[[v15-7-9]]

^<<v15-7-9,9>>^ Pois no primeiro dia do primeiro mês ele partiu de Babilônia e no primeiro dia do quinto mês chegou a Jerusalém, graças à mão benéfica do seu Deus sobre ele.

[[v15-7-10]]

^<<v15-7-10,10>>^ Porque Esdras tinha preparado o seu coração para buscar e cumprir a lei do Senhor, e para ensinar em Israel os seus estatutos e as suas ordenanças.

[[v15-7-11]]

^<<v15-7-11,11>>^ Esta é, pois, a cópia da carta que o rei Artaxerxes deu a Esdras, o sacerdote, o escriba instruído nas palavras dos mandamentos do Senhor e dos seus estatutos para Israel:

[[v15-7-12]]

^<<v15-7-12,12>>^ Artaxerxes, rei dos reis, ao sacerdote Esdras, escriba da lei do Deus do céu: Saudações.

[[v15-7-13]]

^<<v15-7-13,13>>^ Por mim se decreta que no meu reino todo aquele do povo de Israel, e dos seus sacerdotes e levitas, que quiser ir a Jerusalém, vá contigo.

[[v15-7-14]]

^<<v15-7-14,14>>^ Porquanto és enviado da parte do rei e dos seus sete conselheiros para indagares a respeito de Judá e de Jerusalém, conforme a lei do teu Deus, a qual está na tua mão;

[[v15-7-15]]

^<<v15-7-15,15>>^ e para levares a prata e o ouro que o rei e os seus conselheiros voluntariamente deram ao Deus de Israel cuja habitação está em Jerusalém,

[[v15-7-16]]

^<<v15-7-16,16>>^ com toda a prata e o ouro que achares em toda a província de Babilônia, e com as ofertas voluntárias do povo e dos sacerdotes, que voluntariamente as oferecerem para a casa do seu Deus, que está em Jerusalém;

[[v15-7-17]]

^<<v15-7-17,17>>^ portanto com toda a diligência comprarás com este dinheiro novilhos, carneiros, e cordeiros, com as suas ofertas de cereais e as suas ofertas de libações, e os oferecerás sobre o altar da casa do vosso Deus, que está em Jerusalém.

[[v15-7-18]]

^<<v15-7-18,18>>^ Também o que a ti e a teus irmãos parecer bem fazerdes do resto da prata e do ouro, o fareis conforme a vontade do vosso Deus.

[[v15-7-19]]

^<<v15-7-19,19>>^ Os vasos que te foram dados para o serviço da casa do teu Deus, entrega-os todos perante ele, o Deus de Jerusalém.

[[v15-7-20]]

^<<v15-7-20,20>>^ E tudo o mais que for necessário para a casa do teu Deus, e que te convenha dar, o darás da casa dos tesouros do rei.

[[v15-7-21]]

^<<v15-7-21,21>>^ E eu, o rei Artaxerxes, decreto a todos os tesoureiros que estão na província dalém do Rio, que tudo quanto vos exigir o sacerdote Esdras, escriba da lei do Deus do céu, prontamente se lhe conceda,

[[v15-7-22]]

^<<v15-7-22,22>>^ até cem talentos de prata cem coros de trigo, cem batos de vinho, cem batos de azeite, e sal à vontade.

[[v15-7-23]]

^<<v15-7-23,23>>^ Tudo quanto for ordenado pelo Deus do céu, isso precisamente se faça para a casa do Deus do céu; pois, por que haveria ira sobre o reino do rei e de seus filhos?

[[v15-7-24]]

^<<v15-7-24,24>>^ Também vos notificamos acerca de todos os sacerdotes e levitas, cantores, porteiros, netinins, e outros servos desta casa de Deus, que não será lícito exigir-lhes nem tributo, nem imposto, nem pedágio.

[[v15-7-25]]

^<<v15-7-25,25>>^ E tu, Esdras, conforme a sabedoria do teu Deus, que possuis, constitui magistrados e juízes, que julguem todo o povo que está na província dalém do Rio, isto é, todos os que conhecem as leis do teu Deus; e ensina-as ao que não as conhece.

[[v15-7-26]]

^<<v15-7-26,26>>^ E todo aquele que não observar a lei do teu Deus e a lei do rei, com zelo se lhe execute a justiça: quer seja morte, quer desterro, quer confiscação de bens, quer prisão.

[[v15-7-27]]

^<<v15-7-27,27>>^ Bendito seja o Senhor Deus de nossos pais, que pôs no coração do rei este desejo de ornar a casa do Senhor, que está em Jerusalém;

[[v15-7-28]]

^<<v15-7-28,28>>^ e que estendeu sobre mim a sua benevolência perante o rei e os seus conselheiros e perante todos os príncipes poderosos do rei. Assim encorajado pela mão do Senhor, meu Deus, que estava sobre mim, ajuntei dentre Israel alguns dos homens principais para subirem comigo.

'''

xref:015-esdras/015-esdras-006.adoc#v15-6-0[&#60; Capítulo Anterior] | <<v15-7-0,Topo>> | xref:015-esdras/015-esdras-008.adoc#v15-8-0[Próximo Capítulo &#62;]