include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-10-1]]

^<<v15-10-1,1>>^ Ora, enquanto Esdras orava e fazia confissão, chorando e prostrando-se diante da casa de Deus, ajuntou-se a ele, de Israel, uma grande congregação de homens, mulheres, e crianças; pois o povo chorava amargamente.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então Seeanias, filho de Jeiel, um dos filhos de Elão, dirigiu-se a Esdras, dizendo: Nós temos sido infiéis para com o nosso Deus, e casamos com mulheres estrangeiras dentre os povos da terra; contudo, no tocante a isto, ainda há esperança para Israel.

[[v15-10-3]]

^<<v15-10-3,3>>^ Agora, pois, façamos um pacto com o nosso Deus, de que despediremos todas as mulheres e os que delas são nascidos, conforme o conselho do meu Senhor, e dos que tremem ao mandamento do nosso Deus; e faça-se conforme a lei.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levanta-te; pois a ti pertence este negócio, e nós somos contigo; tem bom ânimo, e faze-o.

[[v15-10-5]]

^<<v15-10-5,5>>^ Então Esdras se levantou, e ajuramentou os principais dos sacerdotes, os levitas, e todo o Israel, de que fariam conforme esta palavra; e eles juraram.

[[v15-10-6]]

^<<v15-10-6,6>>^ Em seguida Esdras se levantou de diante da casa de Deus, e entrou na câmara de Joanã, filho de Eliasibe; e, chegando lá, não comeu pão, nem bebeu água, porque pranteava por causa da infidelidade dos do cativeiro.

[[v15-10-7]]

^<<v15-10-7,7>>^ E fizeram passar pregão por Judá e Jerusalém, a todos os que vieram do cativeiro, para que se ajuntassem em Jerusalém;

[[v15-10-8]]

^<<v15-10-8,8>>^ e que todo aquele que dentro de três dias não viesse, segundo o conselho dos oficiais e dos anciãos, toda a sua fazenda se pusesse em interdito, e fosse ele excluído da congregação dos que voltaram do cativeiro.

[[v15-10-9]]

^<<v15-10-9,9>>^ Pelo que todos os homens de Judá e de Benjamim dentro de três dias se ajuntaram em Jerusalém. Era o nono mês, aos vinte dias do mês; e todo o povo se assentou na praça diante da casa de Deus, tremendo por causa deste negócio e por causa das grandes chuvas.

[[v15-10-10]]

^<<v15-10-10,10>>^ Então se levantou Esdras, o sacerdote, e disse-lhes: Vós tendes transgredido, e casastes com mulheres estrangeiras, aumentando a culpa de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora, pois, fazei confissão ao Senhor, Deus de vossos pais, e fazei o que é do seu agrado; separai-vos dos povos das terras, e das mulheres estrangeiras.

[[v15-10-12]]

^<<v15-10-12,12>>^ E toda a congregação respondeu em alta voz: Conforme as tuas palavras havemos de fazer.

[[v15-10-13]]

^<<v15-10-13,13>>^ Porém o povo é muito; também é tempo de grandes chuvas, e não se pode estar aqui fora. Isso não é obra de um dia nem de dois, pois somos muitos os que transgredimos neste negócio.

[[v15-10-14]]

^<<v15-10-14,14>>^ Ponham-se os nossos oficiais por toda a congregação, e todos os que em nossas cidades casaram com mulheres estrangeiras venham em tempos apontados, e com eles os anciãos e juízes de cada cidade, até que se desvie de nós o ardor da ira do nosso Deus no tocante a este negócio.

[[v15-10-15]]

^<<v15-10-15,15>>^ &#123;Somente Jônatas, filho de Asael, e, filho de Ticvá, se opuseram a isso; e Mesulão, e Sabetai, o levita, os apoiaram.&#125;

[[v15-10-16]]

^<<v15-10-16,16>>^ Assim o fizeram os que tornaram do cativeiro: foram indicados o sacerdote Esdras e certos homens, cabeças de casas paternas, segundo as suas casas paternas, cada um designado por nome; e assentaram-se no primeiro dia do décimo mês, para averiguar este negócio.

[[v15-10-17]]

^<<v15-10-17,17>>^ E no primeiro dia do primeiro mês acabaram de tratar de todos os homens que tinham casado com mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ Entre os filhos dos sacerdotes acharam-se estes que tinham casado com mulheres estrangeiras: dos filhos de Jesuá, filho de Jozadaque, e seus irmãos, Maaséias, Eliézer, Jaribe e Gedalias.

[[v15-10-19]]

^<<v15-10-19,19>>^ E deram a sua mão, comprometendo-se a despedirem suas mulheres; e, achando-se culpados, ofereceram um carneiro do rebanho pela sua culpa.

[[v15-10-20]]

^<<v15-10-20,20>>^ Dos filhos de Imer: Hanâni e Zebadias.

[[v15-10-21]]

^<<v15-10-21,21>>^ Dos filhos de Harim: Maaséias, Elias, Semaías, Jeiel e Uzias.

[[v15-10-22]]

^<<v15-10-22,22>>^ E dos filhos de Pasur: Elioenai, Maaséias, Ismael, Netanel, Jozabade e Elasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ Dos levitas: Jozabade, Simei, Quelaías &#123;este é Quelita&#125; , Petaías, Judá e Eliézer.

[[v15-10-24]]

^<<v15-10-24,24>>^ Dos cantores: Eliasibe. Dos porteiros: Salum, Telem e îri.

[[v15-10-25]]

^<<v15-10-25,25>>^ E de Israel, dos filhos de Parós: Ramias, Izias, Malquias, Miamim, Eleazar, Hasabias e Benaías.

[[v15-10-26]]

^<<v15-10-26,26>>^ Dos filhos de Elão: Matanias, Zacarias, Jeiel, Abdi, Jerimote e Elias.

[[v15-10-27]]

^<<v15-10-27,27>>^ Dos filhos de Zatu: Elioenai, Eliasibe, Matanias, Jerimote, Zabade e Aziza.

[[v15-10-28]]

^<<v15-10-28,28>>^ Dos filhos de Bebai: Jeoanã, Hananias, Zabai e Atlai.

[[v15-10-29]]

^<<v15-10-29,29>>^ Dos filhos de Bani: Mesulão, Maluque, Adaías, Jasube, Seal e Jerimote.

[[v15-10-30]]

^<<v15-10-30,30>>^ Dos filhos de Paate-Moabe: Adná, Quelal, Benaías, Maaséias, Matanias, Bezaleel, Binuí e Manassés.

[[v15-10-31]]

^<<v15-10-31,31>>^ Dos filhos de Harim: Eliézer, Issijá, Malquias, Semaías, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maluque e Semarias.

[[v15-10-33]]

^<<v15-10-33,33>>^ Dos filhos de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei.

[[v15-10-34]]

^<<v15-10-34,34>>^ Dos filhos de Bani: Maadai, Anrão e Uel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Benaías, Bedéias, Queluí,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremote, Eliasibe,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matenai e Jaasu.

[[v15-10-38]]

^<<v15-10-38,38>>^ Dos filhos de Binuí: Simei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Selemias, Natã, Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Macnadbai, Sasai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azarel, Selemias, Semarias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Salum, Amarias e José.

[[v15-10-43]]

^<<v15-10-43,43>>^ Dos filhos de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaías.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos estes tinham tomado mulheres estrangeiras; e se despediram das mulheres e dos filhos.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]