include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-5-1]]

^<<v15-5-1,1>>^ Ora, os profetas Ageu e Zacarias, filho de Ido, profetizaram aos judeus que estavam em Judá e em Jerusalém; em nome do Deus de Israel lhes profetizaram.

[[v15-5-2]]

^<<v15-5-2,2>>^ Então se levantaram Zorobabel, filho de Sealtiel, e Jesuá, filho de Jozadaque, e começaram a edificar a casa de Deus, que está em Jerusalém; e com eles estavam os profetas de Deus, que os ajudavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Naquele tempo vieram ter com eles Tatenai, o governador da província a oeste do Rio, e Setar-Bozenai, e os seus companheiros, e assim lhes perguntaram: Quem vos deu ordem para edificar esta casa, e completar este muro?

[[v15-5-4]]

^<<v15-5-4,4>>^ Ainda lhes perguntaram: Quais são os nomes dos homens que constróem este edifício?

[[v15-5-5]]

^<<v15-5-5,5>>^ Os olhos do seu Deus, porém, estavam sobre os anciãos dos judeus, de modo que eles não os impediram, até que o negócio se comunicasse a Dario, e então chegasse resposta por carta sobre isso.

[[v15-5-6]]

^<<v15-5-6,6>>^ A cópia da carta que Tatenai, o governador da província a oeste do Rio, e Setar-Bozenai, e os seus companheiros, os governadores, que estavam deste lado do Rio, enviaram ao rei Dario;

[[v15-5-7]]

^<<v15-5-7,7>>^ enviaram-lhe um relatório, no qual estava escrito: Ao rei Dario toda a paz.

[[v15-5-8]]

^<<v15-5-8,8>>^ Saiba o rei que nós fomos à província de Judá, à casa do grande Deus, a qual se edifica com grandes pedras, e já a madeira está sendo posta nas paredes, e esta obra vai-se fazendo com diligência, e se adianta em suas mãos.

[[v15-5-9]]

^<<v15-5-9,9>>^ Então perguntamos àqueles anciãos, falando-lhes assim: Quem vos deu ordem para edificar esta casa, e completar este muro?

[[v15-5-10]]

^<<v15-5-10,10>>^ Além disso lhes perguntamos pelos seus nomes, para tos declararmos, isto é, para te escrevermos os nomes dos homens que entre eles são os chefes.

[[v15-5-11]]

^<<v15-5-11,11>>^ E esta é a resposta que nos deram: Nós somos servos do Deus do céu e da terra, e reedificamos a casa que há muitos anos foi edificada, a qual um grande rei de Israel edificou e acabou.

[[v15-5-12]]

^<<v15-5-12,12>>^ Mas depois que nossos pais provocaram à ira o Deus do céu, ele os entregou na mão de Nabucodonosor, o caldeu, rei de Babilônia, o qual destruiu esta casa, e transportou o povo para Babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ Porém, no primeiro ano de Ciro, rei de Babilônia, o rei Ciro baixou decreto para que esta casa de Deus fosse reedificada.

[[v15-5-14]]

^<<v15-5-14,14>>^ E até os utensílios de ouro e de prata da casa de Deus, que Nabucodonosor tinha tomado do templo que estava em Jerusalém e levado para o templo de Babilônia, o rei Siro os tirou do templo de Babilônia, e eles foram entregues a um homem cujo nome era Sesbazar, a quem ele tinha constituído governador;

[[v15-5-15]]

^<<v15-5-15,15>>^ e disse-lhe: Toma estes utensílios, vai, e leva-os para o templo que está em Jerusalém, e reedifique-se a casa de Deus no seu lugar.

[[v15-5-16]]

^<<v15-5-16,16>>^ Então veio o dito Sesbazar, e lançou os fundamentos da casa de Deus, que está em Jerusalém; de então para cá ela vem sendo edificada, não estando ainda concluída.

[[v15-5-17]]

^<<v15-5-17,17>>^ Agora, pois, se parece bem ao rei, busque-se nos arquivos reais, ali em Babilônia, para ver se é verdade haver um decreto do rei Ciro para se reedificar esta casa de Deus em Jerusalém, e sobre isto nos faça o rei saber a sua vontade.

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]