include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-8-1]]

^<<v15-8-1,1>>^ Estes, pois, são os chefes de suas casas paternas, e esta é a genealogia dos que subiram comigo de Babilônia no reinado do rei Artaxerxes:

[[v15-8-2]]

^<<v15-8-2,2>>^ Dos filhos de Finéias, Gérson; dos filhos de Itamar, Daniel; dos filhos de Davi, Hatus;

[[v15-8-3]]

^<<v15-8-3,3>>^ dos filhos de Secanias, dos filhos de Parós, Zacarias; e com ele, segundo as genealogias dos varões, se contaram cento e cinqüenta;

[[v15-8-4]]

^<<v15-8-4,4>>^ dos filhos de Paate-Moabe, Elioenai, filho de Zeraías, e com ele duzentos homens;

[[v15-8-5]]

^<<v15-8-5,5>>^ dos filhos de Zatu, Secanias, o filho de Jaaziel, e com ele trezentos homens;

[[v15-8-6]]

^<<v15-8-6,6>>^ dos filhos de Adim, Ebede, filho de Jônatas, e com ele cinqüenta homens;

[[v15-8-7]]

^<<v15-8-7,7>>^ dos filhos de Elão, Jesaías, filho de Atalias, e com ele setenta homens;

[[v15-8-8]]

^<<v15-8-8,8>>^ dos filhos de Sefatias, Zebadias, filho de Micael, e com ele oitenta homens; e

[[v15-8-9]]

^<<v15-8-9,9>>^ dos filhos de Joabe, Obadias, filho de Jeiel, e com ele duzentos e dezoito homens;

[[v15-8-10]]

^<<v15-8-10,10>>^ dos filhos de Bani, Selomite, o filho de Josifias, e com ele cento e sessenta homens;

[[v15-8-11]]

^<<v15-8-11,11>>^ dos filhos de Bebai, Zacarias, o filho de Bebai, e com ele vinte e oito homens;

[[v15-8-12]]

^<<v15-8-12,12>>^ dos filhos de Azgade, Joanã, o filho de Hacatã, e com ele cento e dez homens;

[[v15-8-13]]

^<<v15-8-13,13>>^ dos filhos de Adonicão, que eram os últimos, eis os seus nomes: Elifelete, Jeuel e Semaías, e com eles sessenta homens;

[[v15-8-14]]

^<<v15-8-14,14>>^ e dos filhos de Bigvai, Utai e Zabude, e com eles setenta homens.

[[v15-8-15]]

^<<v15-8-15,15>>^ Ajuntei-os à margem do rio que corre para Ava; e ficamos ali acampados três dias. Então passei em revista o povo e os sacerdotes, e não achei ali nenhum dos filhos de Levi.

[[v15-8-16]]

^<<v15-8-16,16>>^ Mandei, pois, chamar Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, os chefes, como também, Joiaribe e Elnatã, que eram mestres.

[[v15-8-17]]

^<<v15-8-17,17>>^ E os enviei a Ido, chefe em Casífia, e lhes pus na boca palavras para dizerem a Ido e aos seus irmãos, os netinins, em Casífia, que nos trouxessem ministros para a casa do nosso Deus.

[[v15-8-18]]

^<<v15-8-18,18>>^ E, pela boa mão de nosso Deus sobre nós, trouxeram-nos um homem entendido, dos filhos de Mali, filho de Levi, filho de Israel; e Serebias, com os seus filhos e irmãos, dezoito;

[[v15-8-19]]

^<<v15-8-19,19>>^ e Hasabias, e com ele Jesaías, dos filhos de Merári, com seus irmãos e os filhos deles, vinte;

[[v15-8-20]]

^<<v15-8-20,20>>^ e dos netinins, que Davi e os príncipes tinham dado para o serviço dos levitas, duzentos e vinte, todos eles mencionados por nome.

[[v15-8-21]]

^<<v15-8-21,21>>^ Então proclamei um jejum ali junto ao rio Ava, para nos humilharmos diante do nosso Deus, a fim de lhe pedirmos caminho seguro para nós, para nossos pequeninos, e para toda a nossa fazenda.

[[v15-8-22]]

^<<v15-8-22,22>>^ Pois tive vergonha de pedir ao rei uma escolta de soldados, e cavaleiros para nos defenderem do inimigo pelo caminho, porquanto havíamos dito ao rei: A mão do nosso Deus é sobre todos os que o buscam, para o bem deles; mas o seu poder e a sua ira estão contra todos os que o deixam.

[[v15-8-23]]

^<<v15-8-23,23>>^ Nós, pois, jejuamos, e pedimos isto ao nosso Deus; e ele atendeu às nossas orações.

[[v15-8-24]]

^<<v15-8-24,24>>^ Então separei doze dos principais dentre os sacerdotes: Serebias e Hasabias, e com eles dez dos seus irmãos;

[[v15-8-25]]

^<<v15-8-25,25>>^ e pesei-lhes a prata, o ouro e os vasos, a oferta para a casa do nosso Deus, que o rei, os seus conselheiros, os seus príncipes e todo o Israel que estava ali haviam oferecido;

[[v15-8-26]]

^<<v15-8-26,26>>^ entreguei-lhes nas mãos seiscentos e cinqüenta talentos de prata, e em vasos de prata cem talentos; e cem talentos de ouro;

[[v15-8-27]]

^<<v15-8-27,27>>^ e vinte taças de ouro no valor de mil dáricos, e dois vasos de bronze claro e brilhante, tão precioso como o ouro.

[[v15-8-28]]

^<<v15-8-28,28>>^ E disse-lhes: Vós sois santos ao Senhor, e santos são estes vasos; como também esta prata e este ouro são ofertas voluntárias, oferecidas ao Senhor, Deus de vossos pais.

[[v15-8-29]]

^<<v15-8-29,29>>^ Vigiai, pois, e guardai-os até que os peseis na presença dos principais dos sacerdotes e dos levitas, e dos príncipes das casas paternas de Israel, em Jerusalém, nas câmaras da casa do Senhor.

[[v15-8-30]]

^<<v15-8-30,30>>^ Então os sacerdotes e os levitas receberam o peso da prata, e do ouro, e dos vasos, a fim de os trazerem para Jerusalém, para a casa do nosso Deus.

[[v15-8-31]]

^<<v15-8-31,31>>^ Então partimos do rio Ava, no dia doze do primeiro mês, a fim de irmos para Jerusalém; e a mão do nosso Deus estava sobre nós, e ele nos livrou da mão dos inimigos, e dos que nos armavam ciladas pelo caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ Chegamos, pois, a Jerusalém, e repousamos ali três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ No quarto dia se pesou a prata, e o ouro, e os vasos, na casa do nosso Deus, para as mãos de Meremote filho do sacerdote Urias; e com ele estava Eleazar, filho de Finéias, e com eles os levitas Jozabade, filho de Jesuá, e Noadias, filho de Binuí.

[[v15-8-34]]

^<<v15-8-34,34>>^ Tudo foi entregue por número e peso; e o peso de tudo foi registrado na ocasião.

[[v15-8-35]]

^<<v15-8-35,35>>^ Os exilados que tinham voltado do cativeiro ofereceram holocaustos ao Deus de Israel: doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros, e doze bodes em oferta pelo pecado; tudo em holocausto ao Senhor.

[[v15-8-36]]

^<<v15-8-36,36>>^ Então entregaram os editos do rei aos sátrapas do rei, e aos governadores a oeste do Rio; e estes ajudaram o povo e a casa de Deus.

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]