include::./index.adoc[]

[[v15-1-0]]
=== Esdras, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-1-1]]

^<<v15-1-1,1>>^ No primeiro ano de Ciro, rei da Pérsia, para que se cumprisse a palavra do Senhor proferida pela boca de Jeremias, despertou o Senhor o espírito de Ciro, rei da Pérsia, de modo que ele fez proclamar por todo o seu reino, de viva voz e também por escrito, este decreto:

[[v15-1-2]]

^<<v15-1-2,2>>^ Assim diz Ciro, rei da Pérsia: O Senhor Deus do céu me deu todos os reinos da terra, e me encarregou de lhe edificar uma casa em Jerusalém, que é em Judá.

[[v15-1-3]]

^<<v15-1-3,3>>^ Quem há entre vós de todo o seu povo &#123;seja seu Deus com ele&#125; suba para Jerusalém, que é em Judá, e edifique a casa do Senhor, Deus de Israel; ele é o Deus que habita em Jerusalém.

[[v15-1-4]]

^<<v15-1-4,4>>^ E todo remanescente, seja qual for o lugar em que é peregrino, seja ajudado pelos homens desse lugar com prata, com ouro, com bens e com animais, afora a oferta voluntária para a casa de Deus, que está em Jerusalém.

[[v15-1-5]]

^<<v15-1-5,5>>^ Então se levantaram os chefes das casas paternas de Judá e Benjamim e os sacerdotes, e os levitas, todos aqueles cujo espírito Deus despertara, para subirem a edificar a casa do Senhor, que está em Jerusalém.

[[v15-1-6]]

^<<v15-1-6,6>>^ E todos os seus vizinhos os ajudaram com utensílios de prata, com ouro, com bens, com animais e com coisas preciosas, afora tudo o que se ofereceu voluntariamente.

[[v15-1-7]]

^<<v15-1-7,7>>^ Também o rei Ciro tirou os utensílios que pertenciam à casa do Senhor e que Nabucodonosor tinha trazido de Jerusalém e posto na casa de seus deuses.

[[v15-1-8]]

^<<v15-1-8,8>>^ Ciro, rei da Pérsia, tirou-os pela mão de Mitredate, o tesoureiro, que os entregou contados a Sesbazar, príncipe de Judá.

[[v15-1-9]]

^<<v15-1-9,9>>^ Este é o número deles: Trinta bacias de ouro, mil bacias de prata, vinte e nove incensários,

[[v15-1-10]]

^<<v15-1-10,10>>^ trinta taças de ouro, quatrocentas e dez taças de prata e mil outros utensílios.

[[v15-1-11]]

^<<v15-1-11,11>>^ Todos os utensílios de ouro e de prata foram cinco mil e quatrocentos; todos estes levou Sesbazar, quando os do cativeiro foram conduzidos de Babilônia para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[&#60; Capítulo Anterior] | <<v15-1-0,Topo>> | xref:015-esdras/015-esdras-002.adoc#v15-2-0[Próximo Capítulo &#62;]