include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-6-1]]

^<<v15-6-1,1>>^ Então o rei Dario o decretou, e foi feita uma busca nos arquivos onde se guardavam os tesouros em Babilônia.

[[v15-6-2]]

^<<v15-6-2,2>>^ E em Ecbatana, a capital, que está na província da Média, se achou um rolo, e nele estava escrito um memorial, que dizia assim:

[[v15-6-3]]

^<<v15-6-3,3>>^ No primeiro ano do rei Ciro, o rei Ciro baixou um decreto com respeito à casa de Deus em Jerusalém: Seja edificada a casa, o lugar em que se oferecem sacrifícios, e sejam os seus fundamentos bem firmes; a sua altura será de sessenta côvados, e a sua largura de sessenta côvados,

[[v15-6-4]]

^<<v15-6-4,4>>^ com três carreiras de grandes pedras, e uma carreira de madeira nova; e a despesa se fará do tesouro do rei.

[[v15-6-5]]

^<<v15-6-5,5>>^ Além disso sejam restituídos os utensílios de ouro e de prata da casa de Deus, que Nabucodonosor tirou do templo em Jerusalém e levou para Babilônia, e que se tornem a levar para o templo em Jerusalém, cada um para o seu lugar, e tu os porás na casa de Deus.

[[v15-6-6]]

^<<v15-6-6,6>>^ Agora, pois, Tatenai, governador de além do Rio, Setar-Bozenai, e os vossos companheiros, os governadores, que estais além do Rio, retirai-vos desse lugar;

[[v15-6-7]]

^<<v15-6-7,7>>^ deixai de impedir a obra desta casa de Deus; edifiquem o governador dos judeus e os seus anciãos esta casa de Deus no seu lugar.

[[v15-6-8]]

^<<v15-6-8,8>>^ Além disso, por mim se decreta o que haveis de fazer para com esses anciãos dos judeus, para a edificação desta casa de Deus, a saber, que da fazenda do rei, dos tributos da província dalém do Rio, se pague prontamente a estes homens toda a despesa.

[[v15-6-9]]

^<<v15-6-9,9>>^ Igualmente o que for necessário, como novilhos, carneiros e cordeiros, para holocaustos ao Deus do céu; também trigo, sal, vinho e azeite, segundo a palavra dos sacerdotes que estão em Jerusalém, dê-se-lhes isso de dia em dia sem falta;

[[v15-6-10]]

^<<v15-6-10,10>>^ para que ofereçam sacrifícios de cheiro suave ao Deus do céu, e orem pela vida do rei e de seus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ Também por mim se decreta que a todo homem que alterar este decreto, se arranque uma viga da sua casa e que ele seja pregado nela; e da sua casa se faça por isso um monturo.

[[v15-6-12]]

^<<v15-6-12,12>>^ O Deus, pois, que fez habitar ali o seu nome derribe todos os reis e povos que estenderem a mão para alterar o decreto e para destruir esta casa de Deus, que está em Jerusalém. Eu, Dario, baixei o decreto. Que com diligência se execute.

[[v15-6-13]]

^<<v15-6-13,13>>^ Então Tatenai, o governador a oeste do Rio, Setar-Bozenai, e os seus companheiros executaram com toda a diligência o que mandara o rei Dario.

[[v15-6-14]]

^<<v15-6-14,14>>^ Assim os anciãos dos judeus iam edificando e prosperando pela profecia de Ageu o profeta e de Zacarias, filho de Ido. Edificaram e acabaram a casa de acordo com o mandado do Deus de Israel, e de acordo com o decreto de Ciro, e de Dario, e de Artaxerxes, rei da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ E acabou-se esta casa no terceiro dia do mês de Adar, no sexto ano do reinado do rei Dario.

[[v15-6-16]]

^<<v15-6-16,16>>^ E os filhos de Israel, os sacerdotes e os levitas, e o resto dos filhos do cativeiro fizeram a dedicação desta casa de Deus com alegria.

[[v15-6-17]]

^<<v15-6-17,17>>^ Ofereceram para a dedicação desta casa de Deus cem novilhos, duzentos carneiros e quatrocentos cordeiros; e como oferta pelo pecado por todo o Israel, doze bodes, segundo o número das tribos de Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ E puseram os sacerdotes nas suas divisões e os levitas nas suas turmas, para o serviço de Deus em Jerusalém, conforme o que está escrito no livro de Moisés.

[[v15-6-19]]

^<<v15-6-19,19>>^ E os que vieram do cativeiro celebraram a páscoa no dia catorze do primeiro mês.

[[v15-6-20]]

^<<v15-6-20,20>>^ Pois os sacerdotes e levitas se tinham purificado como se fossem um só homem; todos estavam limpos. E imolaram o cordeiro da páscoa para todos os filhos do cativeiro, e para seus irmãos, os sacerdotes, e para si mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Assim comeram a páscoa os filhos de Israel que tinham voltado do cativeiro, com todos os que, unindo-se a eles, se apartaram da imundícia das nações da terra para buscarem o Senhor, Deus de Israel;

[[v15-6-22]]

^<<v15-6-22,22>>^ e celebraram a festa dos pães ázimos por sete dias com alegria; porque o Senhor os tinha alegrado, tendo mudado o coração do rei da Assíria a favor deles, para lhes fortalecer as mãos na obra da casa de Deus, o Deus de Israel.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]