include::./index.adoc[]

[[v15-9-0]]
=== Esdras, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v15-9-1]]

^<<v15-9-1,1>>^ Ora, logo que essas coisas foram terminadas, vieram ter comigo os príncipes, dizendo: O povo de Israel, e os sacerdotes, e os levitas, não se têm separado dos povos destas terras, das abominações dos cananeus, dos heteus, dos perizeus, dos jebuseus, dos amonitas, dos moabitas, dos egípcios e dos amorreus;

[[v15-9-2]]

^<<v15-9-2,2>>^ pois tomaram das suas filhas para si e para seus filhos; de maneira que a raça santa se tem misturado com os povos de outras terras; e até os oficiais e magistrados foram os primeiros nesta transgressão.

[[v15-9-3]]

^<<v15-9-3,3>>^ Ouvindo eu isto, rasguei a minha túnica e o meu manto, e arranquei os cabelos da minha cabeça e da minha barba, e me sentei atônito.

[[v15-9-4]]

^<<v15-9-4,4>>^ Então se ajuntaram a mim todos os que tremiam das palavras do Deus de Israel por causa da transgressão dos do cativeiro; porém eu permaneci sentado atônito até a oblação da tarde.

[[v15-9-5]]

^<<v15-9-5,5>>^ A hora da oblação da tarde levantei-me da minha humilhação, e com a túnica e o manto rasgados, pus-me de joelhos, estendi as mãos ao Senhor meu Deus,

[[v15-9-6]]

^<<v15-9-6,6>>^ e disse: Ó meu Deus! Estou confuso e envergonhado, para levantar o meu rosto a ti, meu Deus; porque as nossas iniqüidades se multiplicaram sobre a nossa cabeça, e a nossa culpa tem crescido até o céu.

[[v15-9-7]]

^<<v15-9-7,7>>^ Desde os dias de nossos pais até o dia de hoje temos estado em grande culpa, e por causa das nossas iniqüidades fomos entregues, nós, os nossos reis e os nossos sacerdotes, na mão dos reis das terras, à espada, ao cativeiro, à rapina e à confusão do rosto, como hoje se vê.

[[v15-9-8]]

^<<v15-9-8,8>>^ Agora, por um pequeno momento se manifestou a graça da parte do Senhor, nosso Deus, para nos deixar um restante que escape, e para nos dar estabilidade no seu santo lugar, a fim de que o nosso Deus nos alumie os olhos, e nos dê um pouco de refrigério em nossa escravidão;

[[v15-9-9]]

^<<v15-9-9,9>>^ pois somos escravos; contudo o nosso Deus não nos abandonou em nossa escravidão, mas estendeu sobre nós a sua benevolência perante os reis da Pérsia, para nos dar a vida, a fim de levantarmos a casa do nosso Deus e repararmos as suas assolações, e para nos dar um abrigo em Judá e em Jerusalém.

[[v15-9-10]]

^<<v15-9-10,10>>^ Agora, ó nosso Deus, que diremos depois disto? Pois temos deixado os teus mandamentos,

[[v15-9-11]]

^<<v15-9-11,11>>^ os quais ordenaste por intermédio de teus servos, os profetas, dizendo: A terra em que estais entrando para a possuir, é uma terra imunda pelas imundícias dos povos das terras, pelas abominações com que, na sua corrupção, a encheram duma extremidade à outra.

[[v15-9-12]]

^<<v15-9-12,12>>^ Por isso não deis vossas filhas a seus filhos, e não tomeis suas filhas para vossos filhos, nem procureis jamais a sua paz ou a sua prosperidade; para que sejais fortes e comais o bem da terra, e a deixeis por herança a vossos filhos para sempre.

[[v15-9-13]]

^<<v15-9-13,13>>^ E depois de tudo o que nos tem sucedido por causa das nossas más obras, e da nossa grande culpa, ainda assim tu, ó nosso Deus, nos tens castigado menos do que merecem as nossas iniqüidades, e ainda nos deixaste este remanescente;

[[v15-9-14]]

^<<v15-9-14,14>>^ tornaremos, pois, agora a violar os teus mandamentos, e a aparentar-nos com os povos que cometem estas abominações? Não estarias tu indignado contra nós até de todo nos consumires, de modo que não ficasse restante, nem quem escapasse?

[[v15-9-15]]

^<<v15-9-15,15>>^ Ó Senhor Deus de Israel, justo és, pois ficamos qual um restante que escapou, como hoje se vê. Eis que estamos diante de ti em nossa culpa; e, por causa disto, ninguém há que possa subsistir na tua presença.

'''

xref:015-esdras/015-esdras-008.adoc#v15-8-0[&#60; Capítulo Anterior] | <<v15-9-0,Topo>> | xref:015-esdras/015-esdras-010.adoc#v15-10-0[Próximo Capítulo &#62;]