include::./index.adoc[]

[[v39-1-0]]
=== Malaquias, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v39-1-1]]

^<<v39-1-1,1>>^ A palavra do Senhor a Israel, por intermédio de Malaquias.

[[v39-1-2]]

^<<v39-1-2,2>>^ Eu vos tenho amado, diz o Senhor. Mas vós dizeis: Em que nos tens amado? Acaso não era Esaú irmão de Jacó? diz o Senhor; todavia amei a Jacó,

[[v39-1-3]]

^<<v39-1-3,3>>^ e aborreci a Esaú; e fiz dos seus montes uma desolação, e dei a sua herança aos chacais do deserto.

[[v39-1-4]]

^<<v39-1-4,4>>^ Ainda que Edom diga: Arruinados estamos, porém tornaremos e edificaremos as ruínas; assim diz o Senhor dos exércitos: Eles edificarão, eu, porém, demolirei; e lhes chamarão: Termo de impiedade, e povo contra quem o Senhor está irado para sempre.

[[v39-1-5]]

^<<v39-1-5,5>>^ E os vossos olhos o verão, e direis: Engrandecido é o Senhor ainda além dos termos de Israel.

[[v39-1-6]]

^<<v39-1-6,6>>^ O filho honra o pai, e o servo ao seu amo; se eu, pois, sou pai, onde está a minha honra? e se eu sou amo, onde está o temor de mim? diz o Senhor dos exércitos a vós, ó sacerdotes, que desprezais o meu nome. E vós dizeis: Em que temos nós desprezado o teu nome?

[[v39-1-7]]

^<<v39-1-7,7>>^ Ofereceis sobre o meu altar pão profano, e dizeis: Em que te havemos profanado? Nisto que pensais, que a mesa do Senhor é desprezível.

[[v39-1-8]]

^<<v39-1-8,8>>^ Pois quando ofereceis em sacrifício um animal cego, isso não é mau? E quando ofereceis o coxo ou o doente, isso não é mau? Ora apresenta-o ao teu governador; terá ele agrado em ti? ou aceitará ele a tua pessoa? diz o Senhor dos exércitos.

[[v39-1-9]]

^<<v39-1-9,9>>^ Agora, pois, suplicai o favor de Deus, para que se compadeça de nós. Com tal oferta da vossa mão, aceitará ele a vossa pessoa? diz o Senhor dos exércitos.

[[v39-1-10]]

^<<v39-1-10,10>>^ Oxalá que entre vós houvesse até um que fechasse as portas para que não acendesse debalde o fogo do meu altar. Eu não tenho prazer em vós, diz o Senhor dos exércitos, nem aceitarei oferta da vossa mão.

[[v39-1-11]]

^<<v39-1-11,11>>^ Mas desde o nascente do sol até o poente é grande entre as nações o meu nome; e em todo lugar se oferece ao meu nome incenso, e uma oblação pura; porque o meu nome é grande entre as nações, diz o Senhor dos exércitos.

[[v39-1-12]]

^<<v39-1-12,12>>^ Mas vós o profanais, quando dizeis: A mesa do Senhor é profana, e o seu produto, isto é, a sua comida, é desprezível.

[[v39-1-13]]

^<<v39-1-13,13>>^ Dizeis também: Eis aqui, que canseira! e o lançastes ao desprezo, diz o Senhor dos exércitos; e tendes trazido o que foi roubado, e o coxo e o doente; assim trazeis a oferta. Aceitaria eu isso de vossa mão? diz o Senhor.

[[v39-1-14]]

^<<v39-1-14,14>>^ Mas seja maldito o enganador que, tendo animal macho no seu rebanho, o vota, e sacrifica ao Senhor o que tem mácula; porque eu sou grande Rei, diz o Senhor dos exércitos, e o meu nome é temível entre as nações.

'''

xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[Próximo Capítulo &#62;]