include::./index.adoc[]

[[v25-4-0]]
=== Lamentações, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v25-4-1]]

^<<v25-4-1,1>>^ Como se escureceu o ouro! como se mudou o ouro puríssimo! como estão espalhadas as pedras do santuário pelas esquinas de todas as ruas!

[[v25-4-2]]

^<<v25-4-2,2>>^ Os preciosos filhos de Sião, comparáveis a ouro puro, como são agora reputados por vasos de barro, obra das mãos de oleiro!

[[v25-4-3]]

^<<v25-4-3,3>>^ Até os chacais abaixam o peito, dão de mamar aos seus filhos; mas a filha do meu povo tornou-se cruel como os avestruzes no deserto.

[[v25-4-4]]

^<<v25-4-4,4>>^ A língua do que mama fica pegada pela sede ao seu paladar; os meninos pedem pão, e ninguém lho reparte.

[[v25-4-5]]

^<<v25-4-5,5>>^ Os que comiam iguarias delicadas desfalecem nas ruas; os que se criavam em escarlata abraçam monturos.

[[v25-4-6]]

^<<v25-4-6,6>>^ Pois maior é a iniqüidade da filha do meu povo do que o pecado de Sodoma, a qual foi subvertida como num momento, sem que mão alguma lhe tocasse.

[[v25-4-7]]

^<<v25-4-7,7>>^ Os seus nobres eram mais alvos do que a neve, mais brancos do que o leite, eram mais ruivos de corpo do que o coral, e a sua formosura era como a de safira.

[[v25-4-8]]

^<<v25-4-8,8>>^ Mas agora escureceu-se o seu parecer mais do que o negrume; eles não são reconhecidos nas ruas; a sua pele se lhes pegou aos ossos; secou-se, tornou-se como um pau. .

[[v25-4-9]]

^<<v25-4-9,9>>^ Os mortos à espada eram mais ditosos do que os mortos à fome, pois estes se esgotavam, como traspassados, por falta dos frutos dos campos.

[[v25-4-10]]

^<<v25-4-10,10>>^ As mãos das mulheres compassivas cozeram os próprios filhos; estes lhes serviram de alimento na destruição da filha do meu povo.

[[v25-4-11]]

^<<v25-4-11,11>>^ Deu o Senhor cumprimento ao seu furor, derramou o ardor da sua ira; e acendeu um fogo em Sião, que consumiu os seus fundamentos.

[[v25-4-12]]

^<<v25-4-12,12>>^ Não creram os reis da terra, bem como nenhum dos moradores do mundo, que adversário ou inimigo pudesse entrar pelas portas de Jerusalém.

[[v25-4-13]]

^<<v25-4-13,13>>^ Isso foi por causa dos pecados dos seus profetas e das iniqüidades dos seus sacerdotes, que derramaram no meio dela o sangue dos justos.

[[v25-4-14]]

^<<v25-4-14,14>>^ Vagueiam como cegos pelas ruas; andam contaminados de sangue, de tal sorte que não se lhes pode tocar nas roupas.

[[v25-4-15]]

^<<v25-4-15,15>>^ Desviai-vos! imundo! gritavam-lhes; desviai-vos, desviai-vos, não toqueis! Quando fugiram, e andaram, vagueando, dizia-se entre as nações: Nunca mais morarão aqui.

[[v25-4-16]]

^<<v25-4-16,16>>^ A ira do Senhor os espalhou; ele nunca mais tornará a olhar para eles; não respeitaram a pessoa dos sacerdotes, nem se compadeceram dos velhos.

[[v25-4-17]]

^<<v25-4-17,17>>^ Os nossos olhos desfaleciam, esperando o nosso vão socorro. em vigiando olhávamos para uma nação, que não podia, livrai.

[[v25-4-18]]

^<<v25-4-18,18>>^ Espiaram os nossos passos, de maneira que não podíamos andar pelas nossas ruas; o nosso fim estava perto; estavam contados os nossos dias, porque era chegado o nosso fim.

[[v25-4-19]]

^<<v25-4-19,19>>^ Os nossos perseguidores foram mais ligeiros do que as águias do céu; sobre os montes nos perseguiram, no deserto nos armaram ciladas.

[[v25-4-20]]

^<<v25-4-20,20>>^ O fôlego da nossa vida, o ungido do Senhor, foi preso nas covas deles, o mesmo de quem dizíamos: Debaixo da sua sombra viveremos entre as nações.

[[v25-4-21]]

^<<v25-4-21,21>>^ Regozija-te, e alegra-te, ó filha de Edom, que habitas na terra de Uz; o cálice te passará a ti também; embebedar-te-ás, e te descobrirás.

[[v25-4-22]]

^<<v25-4-22,22>>^ Já se cumpriu o castigo da tua iniqüidade, ó filha de Sião; ele nunca mais te levará para o cativeiro; ele visitará a tua iniqüidade, ó filha de Edom; descobrirá os teus pecados.

'''

xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[Próximo Capítulo &#62;]