include::./index.adoc[]

[[v25-3-0]]
=== Lamentações, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v25-3-1]]

^<<v25-3-1,1>>^ Eu sou o homem que viu a aflição causada pela vara do seu furor.

[[v25-3-2]]

^<<v25-3-2,2>>^ Ele me guiou e me fez andar em trevas e não na luz.

[[v25-3-3]]

^<<v25-3-3,3>>^ Deveras fez virar e revirar a sua mão contra mim o dia todo.

[[v25-3-4]]

^<<v25-3-4,4>>^ Fez envelhecer a minha carne e a minha pele; quebrou-me os ossos.

[[v25-3-5]]

^<<v25-3-5,5>>^ Levantou trincheiras contra mim, e me cercou de fel e trabalho.

[[v25-3-6]]

^<<v25-3-6,6>>^ Fez-me habitar em lugares tenebrosos, como os que estavam mortos há muito.

[[v25-3-7]]

^<<v25-3-7,7>>^ Cercou-me de uma sebe de modo que não posso sair; agravou os meus grilhões.

[[v25-3-8]]

^<<v25-3-8,8>>^ Ainda quando grito e clamo por socorro, ele exclui a minha oração.

[[v25-3-9]]

^<<v25-3-9,9>>^ Fechou os meus caminhos com pedras lavradas, fez tortuosas as minhas veredas.

[[v25-3-10]]

^<<v25-3-10,10>>^ Fez-se-me como urso de emboscada, um leão em esconderijos.

[[v25-3-11]]

^<<v25-3-11,11>>^ Desviou os meus caminhos, e fez-me em pedaços; deixou-me desolado.

[[v25-3-12]]

^<<v25-3-12,12>>^ Armou o seu arco, e me pôs como alvo à flecha.

[[v25-3-13]]

^<<v25-3-13,13>>^ Fez entrar nos meus rins as flechas da sua aljava.

[[v25-3-14]]

^<<v25-3-14,14>>^ Fui feito um objeto de escárnio para todo o meu povo, e a sua canção o dia todo.

[[v25-3-15]]

^<<v25-3-15,15>>^ Encheu-me de amarguras, fartou-me de absinto.

[[v25-3-16]]

^<<v25-3-16,16>>^ Quebrou com pedrinhas de areia os meus dentes, cobriu-me de cinza.

[[v25-3-17]]

^<<v25-3-17,17>>^ Alongaste da paz a minha alma; esqueci-me do que seja a felicidade.

[[v25-3-18]]

^<<v25-3-18,18>>^ Digo, pois: Já pereceu a minha força, como também a minha esperança no Senhor.

[[v25-3-19]]

^<<v25-3-19,19>>^ Lembra-te da minha aflição e amargura, do absinto e do fel.

[[v25-3-20]]

^<<v25-3-20,20>>^ Minha alma ainda os conserva na memória, e se abate dentro de mim.

[[v25-3-21]]

^<<v25-3-21,21>>^ Torno a trazer isso à mente, portanto tenho esperança.

[[v25-3-22]]

^<<v25-3-22,22>>^ A benignidade do Senhor jamais acaba, as suas misericórdias não têm fim;

[[v25-3-23]]

^<<v25-3-23,23>>^ renovam-se cada manhã. Grande é a tua fidelidade.

[[v25-3-24]]

^<<v25-3-24,24>>^ A minha porção é o Senhor, diz a minha alma; portanto esperarei nele.

[[v25-3-25]]

^<<v25-3-25,25>>^ Bom é o Senhor para os que esperam por ele, para a alma que o busca.

[[v25-3-26]]

^<<v25-3-26,26>>^ Bom é ter esperança, e aguardar em silêncio a salvação do Senhor.

[[v25-3-27]]

^<<v25-3-27,27>>^ Bom é para o homem suportar o jugo na sua mocidade.

[[v25-3-28]]

^<<v25-3-28,28>>^ Que se assente ele, sozinho, e fique calado, porquanto Deus o pôs sobre ele.

[[v25-3-29]]

^<<v25-3-29,29>>^ Ponha a sua boca no pó; talvez ainda haja esperança.

[[v25-3-30]]

^<<v25-3-30,30>>^ Dê a sua face ao que o fere; farte-se de afronta.

[[v25-3-31]]

^<<v25-3-31,31>>^ Pois o Senhor não rejeitará para sempre.

[[v25-3-32]]

^<<v25-3-32,32>>^ Embora entristeça a alguém, contudo terá compaixão segundo a grandeza da sua misericórdia.

[[v25-3-33]]

^<<v25-3-33,33>>^ Porque não aflige nem entristece de bom grado os filhos dos homens.

[[v25-3-34]]

^<<v25-3-34,34>>^ Pisar debaixo dos pés a todos os presos da terra,

[[v25-3-35]]

^<<v25-3-35,35>>^ perverter o direito do homem perante a face do Altíssimo,

[[v25-3-36]]

^<<v25-3-36,36>>^ subverter o homem no seu pleito, não são do agrado do senhor.

[[v25-3-37]]

^<<v25-3-37,37>>^ Quem é aquele que manda, e assim acontece, sem que o Senhor o tenha ordenado?

[[v25-3-38]]

^<<v25-3-38,38>>^ Não sai da boca do Altíssimo tanto o mal como o bem?

[[v25-3-39]]

^<<v25-3-39,39>>^ Por que se queixaria o homem vivente, o varão por causa do castigo dos seus pecados?

[[v25-3-40]]

^<<v25-3-40,40>>^ Esquadrinhemos os nossos caminhos, provemo-los, e voltemos para o Senhor.

[[v25-3-41]]

^<<v25-3-41,41>>^ Levantemos os nossos corações com as mãos para Deus no céu dizendo;

[[v25-3-42]]

^<<v25-3-42,42>>^ Nós transgredimos, e fomos rebeldes, e não perdoaste,

[[v25-3-43]]

^<<v25-3-43,43>>^ Cobriste-te de ira, e nos perseguiste; mataste, não te apiedaste.

[[v25-3-44]]

^<<v25-3-44,44>>^ Cobriste-te de nuvens, para que não passe a nossa oração.

[[v25-3-45]]

^<<v25-3-45,45>>^ Como escória e refugo nos puseste no meio dos povos.

[[v25-3-46]]

^<<v25-3-46,46>>^ Todos os nossos inimigos abriram contra nós a sua boca.

[[v25-3-47]]

^<<v25-3-47,47>>^ Temor e cova vieram sobre nós, assolação e destruição.

[[v25-3-48]]

^<<v25-3-48,48>>^ Torrentes de águas correm dos meus olhos, por causa da destruição da filha do meu povo.

[[v25-3-49]]

^<<v25-3-49,49>>^ Os meus olhos derramam lágrimas, e não cessam, sem haver intermissão,

[[v25-3-50]]

^<<v25-3-50,50>>^ até que o Senhor atente e veja desde o céu.

[[v25-3-51]]

^<<v25-3-51,51>>^ Os meus olhos me afligem, por causa de todas as filhas da minha cidade.

[[v25-3-52]]

^<<v25-3-52,52>>^ Como ave me caçaram os que, sem causa, são meus inimigos.

[[v25-3-53]]

^<<v25-3-53,53>>^ Atiraram-me vivo na masmorra, e lançaram pedras sobre mim.

[[v25-3-54]]

^<<v25-3-54,54>>^ Águas correram sobre a minha cabeça; eu disse: Estou cortado.

[[v25-3-55]]

^<<v25-3-55,55>>^ Invoquei o teu nome, Senhor, desde a profundeza da masmorra.

[[v25-3-56]]

^<<v25-3-56,56>>^ Ouviste a minha voz; não escondas o teu ouvido ao meu suspiro, ao meu clamor.

[[v25-3-57]]

^<<v25-3-57,57>>^ Tu te aproximaste no dia em que te invoquei; disseste: Não temas.

[[v25-3-58]]

^<<v25-3-58,58>>^ Pleiteaste, Senhor, a minha causa; remiste a minha vida.

[[v25-3-59]]

^<<v25-3-59,59>>^ Viste, Senhor, a injustiça que sofri; julga tu a minha causa.

[[v25-3-60]]

^<<v25-3-60,60>>^ Viste toda a sua vingança, todos os seus desígnios contra mim.

[[v25-3-61]]

^<<v25-3-61,61>>^ Ouviste as suas afrontas, Senhor, todos os seus desígnios contra mim,

[[v25-3-62]]

^<<v25-3-62,62>>^ os lábios e os pensamentos dos que se levantam contra mim o dia todo.

[[v25-3-63]]

^<<v25-3-63,63>>^ Observa-os ao assentarem-se e ao levantarem-se; eu sou a sua canção.

[[v25-3-64]]

^<<v25-3-64,64>>^ Tu lhes darás a recompensa, Senhor, conforme a obra das suas mãos.

[[v25-3-65]]

^<<v25-3-65,65>>^ Tu lhes darás dureza de coração, maldição tua sobre eles.

[[v25-3-66]]

^<<v25-3-66,66>>^ Na tua ira os perseguirás, e os destruirás de debaixo dos teus céus, ó Senhor.

'''

xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[&#60; Capítulo Anterior] | <<v25-3-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-004.adoc#v25-4-0[Próximo Capítulo &#62;]