include::./index.adoc[]

[[v5-14-0]]
=== Deuteronômio, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-14-1]]

^<<v5-14-1,1>>^ Filhos sois do Senhor vosso Deus; não vos cortareis a vós mesmos, nem abrireis calva entre vossos olhos por causa de algum morto.

[[v5-14-2]]

^<<v5-14-2,2>>^ Porque és povo santo ao Senhor teu Deus, e o Senhor te escolheu para lhe seres o seu próprio povo, acima de todos os povos que há sobre a face da terra.

[[v5-14-3]]

^<<v5-14-3,3>>^ Nenhuma coisa abominável comereis.

[[v5-14-4]]

^<<v5-14-4,4>>^ Estes são os animais que comereis: o boi, a ovelha, a cabra,

[[v5-14-5]]

^<<v5-14-5,5>>^ o veado, a gazela, o cabrito montês, a cabra montesa, o antílope, o órix e a ovelha montesa.

[[v5-14-6]]

^<<v5-14-6,6>>^ Dentre os animais, todo o que tem a unha fendida, dividida em duas, e que rumina, esse podereis comer.

[[v5-14-7]]

^<<v5-14-7,7>>^ Porém, dos que ruminam, ou que têm a unha fendida, não podereis comer os seguintes: o camelo, a lebre e o querogrilo, porque ruminam, mas não têm a unha fendida; imundos vos serão;

[[v5-14-8]]

^<<v5-14-8,8>>^ nem o porco, porque tem unha fendida, mas não rumina; imundo vos será. Não comereis da carne destes, e não tocareis nos seus cadáveres.

[[v5-14-9]]

^<<v5-14-9,9>>^ Isto podereis comer de tudo o que há nas águas: tudo o que tem barbatanas e escamas podereis comer;

[[v5-14-10]]

^<<v5-14-10,10>>^ mas tudo o que não tem barbatanas nem escamas não comereis; imundo vos será.

[[v5-14-11]]

^<<v5-14-11,11>>^ De todas as aves limpas podereis comer.

[[v5-14-12]]

^<<v5-14-12,12>>^ Mas estas são as de que não comereis: a águia, o quebrantosso, o xofrango,

[[v5-14-13]]

^<<v5-14-13,13>>^ o açor, o falcão, o milhafre segundo a sua espécie,

[[v5-14-14]]

^<<v5-14-14,14>>^ todo corvo segundo a sua espécie,

[[v5-14-15]]

^<<v5-14-15,15>>^ o avestruz, o mocho, a gaivota, o gavião segundo a sua espécie,

[[v5-14-16]]

^<<v5-14-16,16>>^ o bufo, a coruja, o porfirião,

[[v5-14-17]]

^<<v5-14-17,17>>^ o pelicano, o abutre, o corvo marinho,

[[v5-14-18]]

^<<v5-14-18,18>>^ a cegonha, a garça segundo a sua espécie, a poupa e o morcego.

[[v5-14-19]]

^<<v5-14-19,19>>^ Também todos os insetos alados vos serão imundos; não se comerão.

[[v5-14-20]]

^<<v5-14-20,20>>^ De todas as aves limpas podereis comer.

[[v5-14-21]]

^<<v5-14-21,21>>^ Não comerás nenhum animal que tenha morrido por si; ao peregrino que está dentro das tuas portas o darás a comer, ou o venderás ao estrangeiro; porquanto és povo santo ao Senhor teu Deus. Não cozerás o cabrito no leite de sua mãe.

[[v5-14-22]]

^<<v5-14-22,22>>^ Certamente darás os dízimos de todo o produto da tua semente que cada ano se recolher do campo.

[[v5-14-23]]

^<<v5-14-23,23>>^ E, perante o Senhor teu Deus, no lugar que escolher para ali fazer habitar o seu nome, comerás os dízimos do teu grão, do teu mosto e do teu azeite, e os primogênitos das tuas vacas e das tuas ovelhas; para que aprendas a temer ao Senhor teu Deus por todos os dias.

[[v5-14-24]]

^<<v5-14-24,24>>^ Mas se o caminho te for tão comprido que não possas levar os dízimos, por estar longe de ti o lugar que Senhor teu Deus escolher para ali por o seu nome, quando o Senhor teu Deus te tiver abençoado;

[[v5-14-25]]

^<<v5-14-25,25>>^ então vende-os, ata o dinheiro na tua mão e vai ao lugar que o Senhor teu Deus escolher.

[[v5-14-26]]

^<<v5-14-26,26>>^ E aquele dinheiro darás por tudo o que desejares, por bois, por ovelhas, por vinho, por bebida forte, e por tudo o que te pedir a tua alma; comerás ali perante o Senhor teu Deus, e te regozijarás, tu e a tua casa.

[[v5-14-27]]

^<<v5-14-27,27>>^ Mas não desampararás o levita que está dentro das tuas portas, pois não tem parte nem herança contigo.

[[v5-14-28]]

^<<v5-14-28,28>>^ Ao fim de cada terceiro ano levarás todos os dízimos da tua colheita do mesmo ano, e os depositarás dentro das tuas portas.

[[v5-14-29]]

^<<v5-14-29,29>>^ Então virá o levita &#123;pois nem parte nem herança tem contigo&#125;, o peregrino, o órfão, e a viúva, que estão dentro das tuas portas, e comerão, e fartar-se-ão; para que o Senhor teu Deus te abençoe em toda obra que as tuas mãos fizerem.

'''

xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[&#60; Capítulo Anterior] | <<v5-14-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[Próximo Capítulo &#62;]