include::./index.adoc[]

[[v5-16-0]]
=== Deuteronômio, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-16-1]]

^<<v5-16-1,1>>^ Guarda o mês de abibe, e celebra a páscoa ao Senhor teu Deus; porque no mês de abibe, de noite, o Senhor teu Deus tirou-te do Egito.

[[v5-16-2]]

^<<v5-16-2,2>>^ Então, das ovelhas e das vacas, sacrificarás a páscoa ao Senhor teu Deus, no lugar que o Senhor escolher para ali fazer habitar o seu nome.

[[v5-16-3]]

^<<v5-16-3,3>>^ Nela não comerás pão levedado; por sete dias comerás pães ázimos, pão de aflição &#123;porquanto apressadamente saíste da terra do Egito&#125;, para que te lembres do dia da tua saída da terra do Egito, todos os dias da tua vida.

[[v5-16-4]]

^<<v5-16-4,4>>^ O fermento não aparecerá contigo por sete dias em todos os teus termos; também da carne que sacrificares à tarde, no primeiro dia, nada ficará até pela manhã.

[[v5-16-5]]

^<<v5-16-5,5>>^ Não poderás sacrificar a páscoa em qualquer uma das tuas cidades que o Senhor teu Deus te dá,

[[v5-16-6]]

^<<v5-16-6,6>>^ mas no lugar que o Senhor teu Deus escolher para ali fazer habitar o seu nome; ali sacrificarás a páscoa à tarde, ao pôr do sol, ao tempo determinado da tua saída do Egito.

[[v5-16-7]]

^<<v5-16-7,7>>^ Então a cozerás, e comerás no lugar que o Senhor teu Deus escolher; depois, pela manhã, voltarás e irás às tuas tendas.

[[v5-16-8]]

^<<v5-16-8,8>>^ Seis dias comerás pães ázimos, e no sétimo dia haverá assembléia solene ao Senhor teu Deus; nele nenhum trabalho farás.

[[v5-16-9]]

^<<v5-16-9,9>>^ Sete semanas contarás; desde o dia em que começares a meter a foice na seara, começarás a contar as sete semanas.

[[v5-16-10]]

^<<v5-16-10,10>>^ Depois celebrarás a festa das semanas ao Senhor teu Deus segundo a medida da oferta voluntária da tua mão, que darás conforme o Senhor teu Deus te houver abençoado.

[[v5-16-11]]

^<<v5-16-11,11>>^ E te regozijarás perante o Senhor teu Deus, tu, teu filho e tua filha, teu servo e tua serva, o levita que está dentro das tuas portas, o peregrino, o órfão e a viúva que estão no meio de ti, no lugar que o Senhor teu Deus escolher para ali fazer habitar o seu nome.

[[v5-16-12]]

^<<v5-16-12,12>>^ Também te lembrarás de que foste servo no Egito, e guardarás estes estatutos, e os cumpriras.

[[v5-16-13]]

^<<v5-16-13,13>>^ A festa dos tabernáculos celebrarás por sete dias, quando tiveres colhido da tua eira e do teu lagar.

[[v5-16-14]]

^<<v5-16-14,14>>^ E na tua festa te regozijarás, tu, teu filho e tua filha, teu servo e tua serva, e o levita, o peregrino, o órfão e a viúva que estão dentro das tuas portas.

[[v5-16-15]]

^<<v5-16-15,15>>^ sete dias celebrarás a festa ao Senhor teu Deus, no lugar que o senhor escolher; porque o Senhor teu Deus te há de abençoar em toda a tua colheita, e em todo trabalho das tuas mãos; pelo que estarás de todo alegre.

[[v5-16-16]]

^<<v5-16-16,16>>^ Três vezes no ano todos os teus homens aparecerão perante o Senhor teu Deus, no lugar que ele escolher: na festa dos pães ázimos, na festa das semanas, e na festa dos tabernáculos. Não aparecerão vazios perante o Senhor;

[[v5-16-17]]

^<<v5-16-17,17>>^ cada qual oferecerá conforme puder, conforme a bênção que o Senhor teu Deus lhe houver dado.

[[v5-16-18]]

^<<v5-16-18,18>>^ Juízes e oficiais porás em todas as tuas cidades que o Senhor teu Deus te dá, segundo as tuas tribos, para que julguem o povo com justiça.

[[v5-16-19]]

^<<v5-16-19,19>>^ Não torcerás o juízo; não farás acepção de pessoas, nem receberás peitas; porque a peita cega os olhos dos sábios, e perverte a causa dos justos.

[[v5-16-20]]

^<<v5-16-20,20>>^ A justiça, somente a justiça seguirás, para que vivas, e possuas em herança a terra que o Senhor teu Deus te dá.

[[v5-16-21]]

^<<v5-16-21,21>>^ Não plantarás nenhuma árvore como asera, ao pé do altar do Senhor teu Deus, que fizeres,

[[v5-16-22]]

^<<v5-16-22,22>>^ nem levantarás para ti coluna, coisas que o Senhor teu Deus detesta.

'''

xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[&#60; Capítulo Anterior] | <<v5-16-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[Próximo Capítulo &#62;]