include::./index.adoc[]

[[v5-29-0]]
=== Deuteronômio, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-29-1]]

^<<v5-29-1,1>>^ Estas são as palavras do pacto que o Senhor ordenou a Moisés que fizesse com os filhos de Israel na terra de Moabe, além do pacto que fizera com eles em Horebe.

[[v5-29-2]]

^<<v5-29-2,2>>^ Chamou, pois, Moisés a todo o Israel, e disse-lhes: Vistes tudo quanto o Senhor fez perante vossos olhos, na terra do Egito, a Faraó, a todos os seus servos e a toda a sua terra;

[[v5-29-3]]

^<<v5-29-3,3>>^ as grandes provas que os teus olhos viram, os sinais e aquelas grandes maravilhas.

[[v5-29-4]]

^<<v5-29-4,4>>^ Mas até hoje o Senhor não vos tem dado um coração para entender, nem olhos para ver, nem ouvidos para ouvir.

[[v5-29-5]]

^<<v5-29-5,5>>^ Quarenta anos vos fiz andar pelo deserto; não se envelheceu sobre vós a vossa roupa, nem o sapato no vosso pé.

[[v5-29-6]]

^<<v5-29-6,6>>^ Pão não comestes, vinho e bebida forte não bebestes; para que soubésseis que eu sou o Senhor vosso Deus.

[[v5-29-7]]

^<<v5-29-7,7>>^ Quando, pois, viemos a este lugar, Siom, rei de Hesbom, e Ogue, rei de Basã, nos saíram ao encontro, à peleja, e nós os ferimos;

[[v5-29-8]]

^<<v5-29-8,8>>^ e lhes tomamos a terra, e a demos por herança aos rubenitas, aos gaditas e à meia tribo dos manassitas.

[[v5-29-9]]

^<<v5-29-9,9>>^ Guardai, pois, as palavras deste pacto e cumpri-as, para que prospereis em tudo quanto fizerdes.

[[v5-29-10]]

^<<v5-29-10,10>>^ Vós todos estais hoje perante o Senhor vosso Deus: os vossos cabeças, as vossas tribos, os vossos anciãos e os vossos oficiais, a saber, todos os homens de Israel,

[[v5-29-11]]

^<<v5-29-11,11>>^ os vossos pequeninos, as vossas mulheres, e o estrangeiro que está no meio do vosso arraial, tanto o rachador da vossa lenha como o tirador da vossa água;

[[v5-29-12]]

^<<v5-29-12,12>>^ para entrardes no pacto do Senhor vosso Deus, e no seu juramento que o Senhor vosso Deus hoje faz convosco;

[[v5-29-13]]

^<<v5-29-13,13>>^ para que hoje vos estabeleça por seu povo, e ele vos seja por Deus, como vos disse e como prometeu com juramento a vossos pais, a Abraão, a Isaque e a Jacó.

[[v5-29-14]]

^<<v5-29-14,14>>^ Ora, não é somente convosco que faço este pacto e este juramento,

[[v5-29-15]]

^<<v5-29-15,15>>^ mas é com aquele que hoje está aqui conosco perante o Senhor nosso Deus, e também com aquele que hoje não está aqui conosco

[[v5-29-16]]

^<<v5-29-16,16>>^ &#123;porque vós sabeis como habitamos na terra do Egito, e como passamos pelo meio das nações, pelas quais passastes;

[[v5-29-17]]

^<<v5-29-17,17>>^ e vistes as suas abominações, os seus ídolos de pau e de pedra, de prata e de ouro, que havia entre elas&#125;;

[[v5-29-18]]

^<<v5-29-18,18>>^ para que entre vós não haja homem, nem mulher, nem família, nem tribo, cujo coração hoje se desvie do Senhor nosso Deus, e vá servir aos deuses dessas nações; para que entre vós não haja raiz que produza veneno e fel,

[[v5-29-19]]

^<<v5-29-19,19>>^ e aconteça que alguém, ouvindo as palavras deste juramento, se abençoe no seu coração, dizendo: Terei paz, ainda que ande na teimosia do meu coração para acrescentar à sede a bebedeira.

[[v5-29-20]]

^<<v5-29-20,20>>^ O Senhor não lhe quererá perdoar, pelo contrário fumegará contra esse homem a ira do Senhor, e o seu zelo, e toda maldição escrita neste livro pousará sobre ele, e o Senhor lhe apagará o nome de debaixo do céu.

[[v5-29-21]]

^<<v5-29-21,21>>^ Assim o Senhor o separará para mal, dentre todas as tribos de Israel, conforme todas as maldições do pacto escrito no livro desta lei.

[[v5-29-22]]

^<<v5-29-22,22>>^ Pelo que a geração vindoura-os vossos filhos que se levantarem depois de vós-e o estrangeiro que vier de terras remotas dirão, ao verem as pragas desta terra, e as suas doenças, com que o Senhor a terá afligido,

[[v5-29-23]]

^<<v5-29-23,23>>^ e que toda a sua terra é enxofre e sal e abrasamento, de sorte que não será semeada, e nada produzirá, nem nela crescerá erva alguma, assim como foi a destruição de Sodoma e de Gomorra, de Admá e de Zeboim, que o Senhor destruiu na sua ira e no seu furor;

[[v5-29-24]]

^<<v5-29-24,24>>^ sim, todas as nações dirão: Por que fez o Senhor assim com esta terra? Que significa o furor de tamanha ira?

[[v5-29-25]]

^<<v5-29-25,25>>^ Então se dirá: Porquanto deixaram o pacto do Senhor, o Deus de seus pais, que tinha feito com eles, quando os tirou da terra do Egito;

[[v5-29-26]]

^<<v5-29-26,26>>^ e se foram e serviram a outros deuses, e os adoraram; deuses que eles não tinham conhecido, e que lhes não foram dados;

[[v5-29-27]]

^<<v5-29-27,27>>^ por isso é que a ira do Senhor se acendeu contra esta terra, para trazer sobre ela toda maldição que está escrita neste livro;

[[v5-29-28]]

^<<v5-29-28,28>>^ e o Senhor os arrancou da sua terra com ira, com furor e com grande indignação, e os lançou em outra terra, como neste dia se vê.

[[v5-29-29]]

^<<v5-29-29,29>>^ As coisas encobertas pertencem ao Senhor nosso Deus, mas as reveladas nos pertencem a nós e a nossos filhos para sempre, para que observemos todas as palavras desta lei.

'''

xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[&#60; Capítulo Anterior] | <<v5-29-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-030.adoc#v5-30-0[Próximo Capítulo &#62;]