include::./index.adoc[]

[[v5-9-0]]
=== Deuteronômio, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-9-1]]

^<<v5-9-1,1>>^ Ouve, ó Israel: hoje tu vais passar o Jordão para entrares para desapossares nações maiores e mais fortes do que tu, cidades grandes e muradas até o céu;

[[v5-9-2]]

^<<v5-9-2,2>>^ um povo grande e alto, filhos dos anaquins, que tu conhecestes, e dos quais tens ouvido dizer: Quem poderá resistir aos filhos de Anaque?

[[v5-9-3]]

^<<v5-9-3,3>>^ Sabe, pois, hoje que o Senhor teu Deus é o que passa adiante de ti como um fogo consumidor; ele os destruirá, e os subjugará diante de ti; e tu os lançarás fora, e cedo os desfarás, como o Senhor te prometeu.

[[v5-9-4]]

^<<v5-9-4,4>>^ Depois que o Senhor teu Deus os tiver lançado fora de diante de ti, não digas no teu coração: por causa da minha justiça é que o Senhor me introduziu nesta terra para a possuir. Porque pela iniqüidade destas nações é que o Senhor as lança fora de diante de ti.

[[v5-9-5]]

^<<v5-9-5,5>>^ Não é por causa da tua justiça, nem pela retidão do teu coração que entras a possuir a sua terra, mas pela iniqüidade destas nações o Senhor teu Deus as lança fora de diante de ti, e para confirmar a palavra que o Senhor teu Deus jurou a teus pais, Abraão, Isaque e Jacó.

[[v5-9-6]]

^<<v5-9-6,6>>^ Sabe, pois, que não é por causa da tua justiça que o Senhor teu Deus te dá esta boa terra para a possuíres, pois tu és povo de dura cerviz.

[[v5-9-7]]

^<<v5-9-7,7>>^ Lembra-te, e não te esqueças, de como provocaste à ira o Senhor teu Deus no deserto; desde o dia em que saíste da terra do Egito, até que chegaste a este lugar, foste rebelde contra o Senhor;

[[v5-9-8]]

^<<v5-9-8,8>>^ também em Horebe provocastes à ira o Senhor, e o Senhor se irou contra vós para vos destruir.

[[v5-9-9]]

^<<v5-9-9,9>>^ Quando subi ao monte a receber as tábuas de pedra, as tábuas do pacto que o Senhor fizera convosco, fiquei no monte quarenta dias e quarenta noites; não comi pão, nem bebi água.

[[v5-9-10]]

^<<v5-9-10,10>>^ E o Senhor me deu as duas tábuas de pedra, escritas com o dedo de Deus; e nelas estavam escritas todas aquelas palavras que o Senhor tinha falado convosco no monte, do meio do fogo, no dia da assembléia.

[[v5-9-11]]

^<<v5-9-11,11>>^ Sucedeu, pois, que ao fim dos quarenta dias e quarenta noites, o Senhor me deu as duas tábuas de pedra, as tábuas do pacto.

[[v5-9-12]]

^<<v5-9-12,12>>^ E o Senhor me disse: Levanta-te, desce logo daqui, porque o teu povo, que tiraste do Egito, já se corrompeu; cedo se desviaram do caminho que eu lhes ordenei; fizeram para si uma imagem de fundição.

[[v5-9-13]]

^<<v5-9-13,13>>^ Disse-me ainda o Senhor: Atentei para este povo, e eis que ele é povo de dura cerviz;

[[v5-9-14]]

^<<v5-9-14,14>>^ deixa-me que o destrua, e apague o seu nome de debaixo do céu; e farei de ti nação mais poderosa e mais numerosa do que esta.

[[v5-9-15]]

^<<v5-9-15,15>>^ Então me virei, e desci do monte, o qual ardia em fogo; e as duas tábuas do pacto estavam nas minhas duas mãos.

[[v5-9-16]]

^<<v5-9-16,16>>^ Olhei, e eis que havíeis pecado contra o Senhor vosso Deus; tínheis feito para vós um bezerro de fundição; depressa vos tínheis desviado do caminho que o Senhor vos ordenara.

[[v5-9-17]]

^<<v5-9-17,17>>^ Peguei então das duas tábuas e, arrojando-as das minhas mãos, quebrei-as diante dos vossos olhos.

[[v5-9-18]]

^<<v5-9-18,18>>^ Prostrei-me perante o Senhor, como antes, quarenta dias e quarenta noites; não comi pão, nem bebi água, por causa de todo o vosso pecado que havíeis cometido, fazendo o que era mau aos olhos do Senhor, para o provocar a ira.

[[v5-9-19]]

^<<v5-9-19,19>>^ Porque temi por causa da ira e do furor com que o Senhor estava irado contra vós para vos destruir; porém ainda essa vez o Senhor me ouviu.

[[v5-9-20]]

^<<v5-9-20,20>>^ O Senhor se irou muito contra Arão para o destruir; mas também orei a favor de Arão ao mesmo tempo.

[[v5-9-21]]

^<<v5-9-21,21>>^ Então eu tomei o vosso pecado, o bezerro que tínheis feito, e o queimei a fogo e o pisei, moendo-o bem, até que se desfez em pó; e o seu pó lancei no ribeiro que descia do monte.

[[v5-9-22]]

^<<v5-9-22,22>>^ Igualmente em Taberá, e em Massá, e em Quibrote-Hataavá provocastes à ira o Senhor.

[[v5-9-23]]

^<<v5-9-23,23>>^ Quando também o Senhor vos enviou de Cades-Barnéia, dizendo: Subi, e possuí a terra que vos dei; vós vos rebelastes contra o mandado do Senhor vosso Deus, e não o crestes, e não obedecestes à sua voz.

[[v5-9-24]]

^<<v5-9-24,24>>^ Tendes sido rebeldes contra o Senhor desde o dia em que vos conheci.

[[v5-9-25]]

^<<v5-9-25,25>>^ Assim me prostrei perante o Senhor; quarenta dias e quarenta noites estive prostrado, porquanto o Senhor ameaçara destruir-vos.

[[v5-9-26]]

^<<v5-9-26,26>>^ Orei ao Senhor, dizendo: ó Senhor Jeová, não destruas o teu povo, a tua herança, que resgataste com a tua grandeza, que tiraste do Egito com mão forte.

[[v5-9-27]]

^<<v5-9-27,27>>^ Lembra-te dos teus servos, Abraão, Isaque e Jacó; não atentes para a dureza deste povo, nem para a sua iniqüidade, nem para o seu pecado;

[[v5-9-28]]

^<<v5-9-28,28>>^ para que o povo da terra de onde nos tiraste não diga: Porquanto o Senhor não pôde introduzi-los na terra que lhes prometera, passou a odiá-los, e os tirou para os matar no deserto.

[[v5-9-29]]

^<<v5-9-29,29>>^ Todavia são eles o teu povo, a sua herança, que tiraste com a sua grande força e com o teu braço estendido.

'''

xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[&#60; Capítulo Anterior] | <<v5-9-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[Próximo Capítulo &#62;]