include::./index.adoc[]

[[v5-11-0]]
=== Deuteronômio, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-11-1]]

^<<v5-11-1,1>>^ Amarás, pois, ao Senhor teu Deus, e guardarás as suas ordenanças, os seus estatutos, os seus preceitos e os seus mandamentos, por todos os dias.

[[v5-11-2]]

^<<v5-11-2,2>>^ Considerai hoje &#123;pois não falo com vossos filhos, que não conheceram, nem viram&#125; a instrução do Senhor vosso Deus, a sua grandeza, a sua mão forte, e o seu braço estendido;

[[v5-11-3]]

^<<v5-11-3,3>>^ os seus sinais, as suas obras, que fez no meio do Egito a Faraó, rei do Egito, e a toda a sua terra;

[[v5-11-4]]

^<<v5-11-4,4>>^ o que fez ao exército dos egípcios, aos seus cavalos e aos seus carros; como fez passar sobre eles as águas do Mar Vermelho, quando vos perseguiam, e como o Senhor os destruiu até o dia de hoje;

[[v5-11-5]]

^<<v5-11-5,5>>^ o que vos fez no deserto, até chegardes a este lugar;

[[v5-11-6]]

^<<v5-11-6,6>>^ e o que fez a Datã e a Abirão, filhos de Eliabe, filho de Rúben; como a terra abriu a sua boca e os tragou com as suas casas e as suas tendas, e bem assim todo ser vivente que lhes pertencia, no meia de todo o Israel;

[[v5-11-7]]

^<<v5-11-7,7>>^ porquanto os vossos olhos são os que viram todas as grandes obras que fez o Senhor.

[[v5-11-8]]

^<<v5-11-8,8>>^ Guardareis, pois, todos os mandamentos que eu vos ordeno hoje, para que sejais fortes, e entreis, e ocupeis a terra a que estais passando para a possuirdes;

[[v5-11-9]]

^<<v5-11-9,9>>^ e para que prolongueis os dias nessa terra que o Senhor, com juramento, prometeu dar a vossos pais e à sua descendência, terra que mana leite e mel.

[[v5-11-10]]

^<<v5-11-10,10>>^ Pois a terra na qual estais entrando para a possuirdes não é como a terra do Egito, de onde saístes, em que semeáveis a vossa semente, e a regáveis com o vosso pé, como a uma horta;

[[v5-11-11]]

^<<v5-11-11,11>>^ mas a terra a que estais passando para a possuirdes é terra de montes e de vales; da chuva do céu bebe as águas;

[[v5-11-12]]

^<<v5-11-12,12>>^ terra de que o Senhor teu Deus toma cuidado; os olhos do Senhor teu Deus estão sobre ela continuamente, desde o princípio até o fim do ano.

[[v5-11-13]]

^<<v5-11-13,13>>^ E há de ser que, se diligentemente obedeceres a meus mandamentos que eu hoje te ordeno, de amar ao Senhor teu Deus, e de o servir de todo o teu coração e de toda a tua alma,

[[v5-11-14]]

^<<v5-11-14,14>>^ darei a chuva da tua terra a seu tempo, a temporã e a serôdia, para que recolhas o teu grão, o teu mosto e o teu azeite;

[[v5-11-15]]

^<<v5-11-15,15>>^ e darei erva no teu campo para o teu gado, e comerás e fartar-te-ás.

[[v5-11-16]]

^<<v5-11-16,16>>^ Guardai-vos para que o vosso coração não se engane, e vos desvieis, e sirvais a outros deuses, e os adoreis;

[[v5-11-17]]

^<<v5-11-17,17>>^ e a ira do Senhor se acenda contra vós, e feche ele o céu, e não caia chuva, e a terra não dê o seu fruto, e cedo pereçais da boa terra que o Senhor vos dá.

[[v5-11-18]]

^<<v5-11-18,18>>^ Ponde, pois, estas minhas palavras no vosso coração e na vossa alma; atá-las-eis por sinal na vossa mão, e elas vos serão por frontais entre os vossos olhos;

[[v5-11-19]]

^<<v5-11-19,19>>^ e ensiná-las-eis a vossos filhos, falando delas sentados em vossas casas e andando pelo caminho, ao deitar-vos e ao levantar-vos;

[[v5-11-20]]

^<<v5-11-20,20>>^ e escrevê-las-eis nos umbrais de vossas casas, e nas vossas portas;

[[v5-11-21]]

^<<v5-11-21,21>>^ para que se multipliquem os vossos dias e os dias de vossos filhos na terra que o Senhor, com juramento, prometeu dar a vossos pais, enquanto o céu cobrir a terra.

[[v5-11-22]]

^<<v5-11-22,22>>^ Porque, se diligentemente guardardes todos estes mandamentos que eu vos ordeno, se amardes ao Senhor vosso Deus, e andardes em todos os seus caminhos, e a ele vos apegardes,

[[v5-11-23]]

^<<v5-11-23,23>>^ também o Senhor lançará fora de diante de vós todas estas nações, e possuireis nações maiores e mais poderosas do que vós.

[[v5-11-24]]

^<<v5-11-24,24>>^ Todo lugar que pisar a planta do vosso pé será vosso; o vosso termo se estenderá do deserto ao Líbano, e do rio, o rio Eufrates, até o mar ocidental.

[[v5-11-25]]

^<<v5-11-25,25>>^ Ninguém vos poderá resistir; o Senhor vosso Deus porá o medo e o terror de vós sobre toda a terra que pisardes, assim como vos disse.

[[v5-11-26]]

^<<v5-11-26,26>>^ Vede que hoje eu ponho diante de vós a bênção e a maldição:

[[v5-11-27]]

^<<v5-11-27,27>>^ A bênção, se obedecerdes aos mandamentos do Senhor vosso Deus, que eu hoje vos ordeno;

[[v5-11-28]]

^<<v5-11-28,28>>^ porém a maldição, se não obedecerdes aos mandamentos do Senhor vosso Deus, mas vos desviardes do caminho que eu hoje vos ordeno, para seguirdes outros deuses que nunca conhecestes.

[[v5-11-29]]

^<<v5-11-29,29>>^ Ora, quando o Senhor teu Deus te introduzir na terra a que vais para possuí-la, pronunciarás a bênção sobre o monte Gerizim, e a maldição sobre o monte Ebal.

[[v5-11-30]]

^<<v5-11-30,30>>^ Porventura não estão eles além do Jordão, atrás do caminho do pôr do sol, na terra dos cananeus, que habitam na Arabá defronte de Gilgal, junto aos carvalhos de Moré?

[[v5-11-31]]

^<<v5-11-31,31>>^ Porque estais a passar o Jordão para entrardes a possuir a terra que o Senhor vosso Deus vos dá; e a possuireis, e nela habitareis.

[[v5-11-32]]

^<<v5-11-32,32>>^ Tende, pois, cuidado em observar todos os estatutos e os preceitos que eu hoje vos proponho.

'''

xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[Próximo Capítulo &#62;]