include::./index.adoc[]

[[v5-33-0]]
=== Deuteronômio, 33
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-33-1]]

^<<v5-33-1,1>>^ Esta é a bênção com que Moisés, homem de Deus, abençoou os filhos de Israel antes da sua morte.

[[v5-33-2]]

^<<v5-33-2,2>>^ Disse ele: O Senhor veio do Sinai, e de Seir raiou sobre nós; resplandeceu desde o monte Parã, e veio das miríades de santos; à sua direita havia para eles o fogo da lei.

[[v5-33-3]]

^<<v5-33-3,3>>^ Na verdade ama o seu povo; todos os seus santos estão na sua mão; postos serão no meio, entre os teus pés, e cada um receberá das tuas palavras.

[[v5-33-4]]

^<<v5-33-4,4>>^ Moisés nos prescreveu uma lei, uma herança para a assembléia de Jacó.

[[v5-33-5]]

^<<v5-33-5,5>>^ E tornou-se rei em Jesurum, quando se congregaram os cabeças do povo juntamente com as tribos de Israel.

[[v5-33-6]]

^<<v5-33-6,6>>^ Viva Rúben, e não morra; e não sejam poucos os seus homens.

[[v5-33-7]]

^<<v5-33-7,7>>^ E isto é o que disse de Judá: Ouve, ó Senhor, a voz de Judá e introduze-o no meio do seu povo; com as suas mãos pelejou por si; sê tu o seu auxílio contra os seus inimigos.

[[v5-33-8]]

^<<v5-33-8,8>>^ De Levi disse: Sejam teu Tumim e teu Urim para o teu homem santo, que provaste em Massá, com quem contendeste junto às águas de Meribá;

[[v5-33-9]]

^<<v5-33-9,9>>^ aquele que disse de seu pai e de sua mãe: Nunca os vi, e não reconheceu a seus irmãos, e não conheceu a seus filhos; pois esses levitas guardaram a tua palavra e observaram o teu pacto.

[[v5-33-10]]

^<<v5-33-10,10>>^ Ensinarão os teus preceitos a Jacó, e a tua lei a Israel; chegarão incenso ao seu nariz, e porão holocausto sobre o teu altar.

[[v5-33-11]]

^<<v5-33-11,11>>^ Abençoa o seu poder, ó Senhor, e aceita a obra das suas mãos; fere os lombos dos que se levantam contra ele e o odeiam, para que nunca mais se levantem.

[[v5-33-12]]

^<<v5-33-12,12>>^ De Benjamim disse: O amado do Senhor habitará seguro junto a ele; e o Senhor o cercará o dia todo, e ele habitará entre os seus ombros.

[[v5-33-13]]

^<<v5-33-13,13>>^ De José disse: Abençoada pelo Senhor seja a sua terra, com os mais excelentes dons do céu, com o orvalho, e com as águas do abismo que jaz abaixo;

[[v5-33-14]]

^<<v5-33-14,14>>^ com os excelentes frutos do sol, e com os excelentes produtos dos meses;

[[v5-33-15]]

^<<v5-33-15,15>>^ com as coisas mais excelentes dos montes antigos, e com as coisas excelentes dos outeiros eternos;

[[v5-33-16]]

^<<v5-33-16,16>>^ com as coisas excelentes da terra, e com a sua plenitude, e com a benevolência daquele que habitava na sarça; venha tudo isso sobre a cabeça de José, sobre o alto da cabeça daquele que é príncipe entre seus irmãos.

[[v5-33-17]]

^<<v5-33-17,17>>^ Eis o seu novilho primogênito; ele tem majestade; e os seus chifres são chifres de boi selvagem; com eles rechaçará todos os povos, sim, todas as extremidades da terra. Tais são as miríades de Efraim, e tais são os milhares de Manassés.

[[v5-33-18]]

^<<v5-33-18,18>>^ De Zebulom disse: Zebulom, alegra-te nas tuas saídas; e tu, Issacar, nas tuas tendas.

[[v5-33-19]]

^<<v5-33-19,19>>^ Eles chamarão os povos ao monte; ali oferecerão sacrifícios de justiça, porque chuparão a abundância dos mares e os tesouros escondidos da areia.

[[v5-33-20]]

^<<v5-33-20,20>>^ De Gade disse: Bendito aquele que faz dilatar a Gade; habita como a leoa, e despedaça o braço, e o alto da cabeça.

[[v5-33-21]]

^<<v5-33-21,21>>^ Ele se proveu da primeira parte, porquanto ali estava reservada a porção do legislador; pelo que veio com os chefes do povo, executou a justiça do Senhor e os seus juízos para com Israel.

[[v5-33-22]]

^<<v5-33-22,22>>^ De Dã disse: Dã é cachorro de leão, que salta de Basã.

[[v5-33-23]]

^<<v5-33-23,23>>^ De Naftali disse: ó Naftali, saciado de favores, e farto da bênção do Senhor, possui o lago e o sul.

[[v5-33-24]]

^<<v5-33-24,24>>^ De Aser disse: Bendito seja Aser dentre os filhos de Israel; seja o favorecido de seus irmãos; e mergulhe em azeite o seu pé;

[[v5-33-25]]

^<<v5-33-25,25>>^ de ferro e de bronze sejam os teus ferrolhos; e como os teus dias, assim seja a tua força.

[[v5-33-26]]

^<<v5-33-26,26>>^ Não há outro, ó Jesurum, semelhante a Deus, que cavalga sobre o céu para a tua ajuda, e na sua majestade sobre as mais altas nuvens.

[[v5-33-27]]

^<<v5-33-27,27>>^ O Deus eterno é a tua habitação, e por baixo estão os braços eternos; ele lançou o inimigo de diante de ti e disse: Destrói-o.

[[v5-33-28]]

^<<v5-33-28,28>>^ Israel pois habitará seguro, a fonte de Jacó a sós, na terra de grão e de mosto; e o seu céu gotejará o orvalho.

[[v5-33-29]]

^<<v5-33-29,29>>^ Feliz és tu, ó Israel! quem é semelhante a ti? um povo salvo pelo Senhor, o escudo do teu socorro, e a espada da tua majestade; pelo que os teus inimigos te serão sujeitos, e tu pisarás sobre as suas alturas.

'''

xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[Próximo Capítulo &#62;]