include::./index.adoc[]

[[v5-7-0]]
=== Deuteronômio, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-7-1]]

^<<v5-7-1,1>>^ Quando o Senhor teu Deus te houver introduzido na terra a que vais a fim de possuí-la, e tiver lançado fora de diante de ti muitas nações, a saber, os heteus, os girgaseus, os amorreus, os cananeus, os perizeus, os heveus e os jebuseus, sete nações mais numerosas e mais poderosas do que tu;

[[v5-7-2]]

^<<v5-7-2,2>>^ e quando o Senhor teu Deus as tiver entregue, e as ferires, totalmente as destruirás; não farás com elas pacto algum, nem terás piedade delas;

[[v5-7-3]]

^<<v5-7-3,3>>^ não contrairás com elas matrimônios; não darás tuas filhas a seus filhos, e não tomarás suas filhas para teus filhos;

[[v5-7-4]]

^<<v5-7-4,4>>^ pois fariam teus filhos desviarem-se de mim, para servirem a outros deuses; e a ira do Senhor se acenderia contra vós, e depressa vos consumiria.

[[v5-7-5]]

^<<v5-7-5,5>>^ Mas assim lhes fareis: Derrubareis os seus altares, quebrareis as suas colunas, cortareis os seus aserins, e queimareis a fogo as suas imagens esculpidas.

[[v5-7-6]]

^<<v5-7-6,6>>^ Porque tu és povo santo ao Senhor teu Deus; o Senhor teu Deus te escolheu, a fim de lhe seres o seu próprio povo, acima de todos os povos que há sobre a terra.

[[v5-7-7]]

^<<v5-7-7,7>>^ O Senhor não tomou prazer em vós nem vos escolheu porque fôsseis mais numerosos do que todos os outros povos, pois éreis menos em número do que qualquer povo;

[[v5-7-8]]

^<<v5-7-8,8>>^ mas, porque o Senhor vos amou, e porque quis guardar o juramento que fizera a vossos pais, foi que vos tirou com mão forte e vos resgatou da casa da servidão, da mão de Faraó, rei do Egito.

[[v5-7-9]]

^<<v5-7-9,9>>^ Saberás, pois, que o Senhor teu Deus é que é Deus, o Deus fiel, que guarda o pacto e a misericórdia, até mil gerações, aos que o amam e guardam os seus mandamentos;

[[v5-7-10]]

^<<v5-7-10,10>>^ e que retribui diretamente aos que o odeiam, para os destruir; não será remisso para quem o odeia, diretamente lhe retribuirá.

[[v5-7-11]]

^<<v5-7-11,11>>^ Guardarás, pois, os mandamentos, os estatutos e os preceitos que eu hoje te ordeno, para os cumprires.

[[v5-7-12]]

^<<v5-7-12,12>>^ Sucederá, pois, que, por ouvirdes estes preceitos, e os guardardes e cumprirdes, o Senhor teu Deus te guardará o pacto e a misericórdia que com juramento prometeu a teus pais;

[[v5-7-13]]

^<<v5-7-13,13>>^ ele te amará, te abençoará e te fará multiplicar; abençoará o fruto do teu ventre, e o fruto da tua terra, o teu grão, o teu mosto e o teu azeite, a criação das tuas vacas, e as crias dos teus rebanhos, na terra que com juramento prometeu a teus pais te daria.

[[v5-7-14]]

^<<v5-7-14,14>>^ Bendito serás mais do que todos os povos; não haverá estéril no meio de ti, seja homem, seja mulher, nem entre os teus animais.

[[v5-7-15]]

^<<v5-7-15,15>>^ E o Senhor desviará de ti toda enfermidade; não porá sobre ti nenhuma das más doenças dos egípcios, que bem conheces; no entanto as porás sobre todos os que te odiarem.

[[v5-7-16]]

^<<v5-7-16,16>>^ Consumirás todos os povos que o Senhor teu Deus te entregar; os teus olhos não terão piedade deles; e não servirás a seus deuses, pois isso te seria por laço.

[[v5-7-17]]

^<<v5-7-17,17>>^ Se disseres no teu coração: Estas nações são mais numerosas do que eu; como as poderei desapossar?

[[v5-7-18]]

^<<v5-7-18,18>>^ delas não terás medo; antes lembrarte-ás do que o Senhor teu Deus fez a Faraó e a todos os egípcios;

[[v5-7-19]]

^<<v5-7-19,19>>^ das grandes provas que os teus olhos viram, e dos sinais, e das maravilhas, e da mão forte, e do braço estendido, com que o Senhor teu Deus te tirou: Assim fará o Senhor teu Deus a todos os povos, diante dos quais tu temes.

[[v5-7-20]]

^<<v5-7-20,20>>^ Além disso o Senhor teu Deus mandará entre eles vespões, até que pereçam os restantes que se tiverem escondido de ti.

[[v5-7-21]]

^<<v5-7-21,21>>^ Não te espantes diante deles, porque o Senhor teu Deus está no meio de ti, Deus grande e terrível.

[[v5-7-22]]

^<<v5-7-22,22>>^ E o Senhor teu Deus lançará fora de diante de ti, pouco a pouco, estas nações; não poderás destruí-las todas de pronto, para que as feras do campo não se multipliquem contra ti.

[[v5-7-23]]

^<<v5-7-23,23>>^ E o Senhor as entregará a ti, e lhes infligirá uma grande derrota, até que sejam destruídas.

[[v5-7-24]]

^<<v5-7-24,24>>^ Também os seus reis te entregará nas tuas mãos, e farás desaparecer o nome deles de debaixo do céu; nenhum te poderá resistir, até que os tenhas destruído.

[[v5-7-25]]

^<<v5-7-25,25>>^ As imagens esculpidas de seus deuses queimarás a fogo; não cobiçarás a prata nem o ouro que estão sobre elas, nem deles te apropriarás, para que não te enlaces neles; pois são abominação ao Senhor teu Deus.

[[v5-7-26]]

^<<v5-7-26,26>>^ Não meterás, pois, uma abominação em tua casa, para que não sejas anátema, semelhante a ela; de todo a detestarás, e de todo a abominarás, pois é anátema.

'''

xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[&#60; Capítulo Anterior] | <<v5-7-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[Próximo Capítulo &#62;]