include::./index.adoc[]

[[v5-1-0]]
=== Deuteronômio, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-1-1]]

^<<v5-1-1,1>>^ Estas são as palavras que Moisés falou a todo Israel além do Jordão, no deserto, na Arabá defronte de Sufe, entre Parã, Tofel, Labã, Hazerote e Di-Zaabe.

[[v5-1-2]]

^<<v5-1-2,2>>^ São onze dias de viagem desde Horebe, pelo caminho da montanha de Seir, até Cades-Barnéia.

[[v5-1-3]]

^<<v5-1-3,3>>^ No ano quadragésimo, no mês undécimo, no primeiro dia do mês, Moisés falou aos filhos de Israel, conforme tudo o que o senhor lhes mandara por seu intermédio,

[[v5-1-4]]

^<<v5-1-4,4>>^ depois que derrotou a Siom, rei dos amorreus, que habitava em Hesbom, e a Ogue, rei de Basã, que habitava em Astarote, em Edrei.

[[v5-1-5]]

^<<v5-1-5,5>>^ Além do Jordão, na terra de Moabe, Moisés se pôs a explicar esta lei, e disse:

[[v5-1-6]]

^<<v5-1-6,6>>^ O Senhor nosso Deus nos falou em Horebe, dizendo: Assaz vos haveis demorado neste monte.

[[v5-1-7]]

^<<v5-1-7,7>>^ Voltai-vos, ponde-vos a caminho, e ide à região montanhosa dos amorreus, e a todos os lugares vizinhos, na Arabá, na região montanhosa, no vale e no sul; à beira do mar, à terra dos cananeus, e ao Líbano, até o grande rio, o rio Eufrates.

[[v5-1-8]]

^<<v5-1-8,8>>^ Eis que tenho posto esta terra diante de vós; entrai e possuí a terra que o Senhor prometeu com juramento dar a vossos pais, Abraão, Isaque, e Jacó, a eles e à sua descendência depois deles.

[[v5-1-9]]

^<<v5-1-9,9>>^ Nesse mesmo tempo eu vos disse: Eu sozinho não posso levar-vos,

[[v5-1-10]]

^<<v5-1-10,10>>^ o Senhor vosso Deus já vos tem multiplicado, e eis que hoje sois tão numerosos como as estrelas do céu.

[[v5-1-11]]

^<<v5-1-11,11>>^ O Senhor Deus de vossos pais vos faça mil vezes mais numerosos do que sois; e vos abençoe, como vos prometeu.

[[v5-1-12]]

^<<v5-1-12,12>>^ Como posso eu sozinho suportar o vosso peso, as vossas cargas e as vossas contendas?

[[v5-1-13]]

^<<v5-1-13,13>>^ Tomai-vos homens sábios, entendidos e experimentados, segundo as vossas tribos, e eu os porei como cabeças sobre vós.

[[v5-1-14]]

^<<v5-1-14,14>>^ Então me respondestes: bom fazermos o que disseste.

[[v5-1-15]]

^<<v5-1-15,15>>^ Tomei, pois, os cabeças de vossas tribos, homens sábios e experimentados, e os constituí por cabeças sobre vós, chefes de mil, chefes de cem, chefes de cinqüenta e chefes de dez, por oficiais, segundo as vossas tribos.

[[v5-1-16]]

^<<v5-1-16,16>>^ E no mesmo tempo ordenei a vossos juízes, dizendo: Ouvi as causas entre vossos irmãos, e julgai com justiça entre o homem e seu irmão, ou o estrangeiro que está com ele.

[[v5-1-17]]

^<<v5-1-17,17>>^ Não fareis acepção de pessoas em juízo; de um mesmo modo ouvireis o pequeno e o grande; não temereis a face de ninguém, porque o juízo é de Deus; e a causa que vos for difícil demais, a trareis a mim, e eu a ouvirei.

[[v5-1-18]]

^<<v5-1-18,18>>^ Assim naquele tempo vos ordenei todas as coisas que devíeis fazer.

[[v5-1-19]]

^<<v5-1-19,19>>^ Então partimos de Horebe, e caminhamos por todo aquele grande e terrível deserto que vistes, pelo caminho das montanhas dos amorreus, como o Senhor nosso Deus nos ordenara; e chegamos a Cades-Barnéia.

[[v5-1-20]]

^<<v5-1-20,20>>^ Então eu vos disse: Chegados sois às montanhas dos amorreus, que o Senhor nosso Deus nos dá.

[[v5-1-21]]

^<<v5-1-21,21>>^ Eis aqui o Senhor teu Deus tem posto esta terra diante de ti; sobe, apodera-te dela, como te falou o Senhor Deus de teus pais; não temas, e não te assustes.

[[v5-1-22]]

^<<v5-1-22,22>>^ Então todos vós vos chegastes a mim, e dissestes: Mandemos homens adiante de nós, para que nos espiem a terra e, de volta, nos ensinem o caminho pelo qual devemos subir, e as cidades a que devemos ir.

[[v5-1-23]]

^<<v5-1-23,23>>^ Isto me pareceu bem; de modo que dentre vós tomei doze homens, de cada tribo um homem;

[[v5-1-24]]

^<<v5-1-24,24>>^ foram-se eles e, subindo as montanhas, chegaram até o vale de Escol e espiaram a terra.

[[v5-1-25]]

^<<v5-1-25,25>>^ Tomaram do fruto da terra nas mãos, e no-lo trouxeram; e nos informaram, dizendo: Boa é a terra que nos dá o Senhor nosso Deus.

[[v5-1-26]]

^<<v5-1-26,26>>^ Todavia, vós não quisestes subir, mas fostes rebeldes ao mandado do Senhor nosso Deus;

[[v5-1-27]]

^<<v5-1-27,27>>^ e murmurastes nas vossas tendas, e dissestes: Porquanto o Senhor nos odeia, tirou-nos da terra do Egito para nos entregar nas mãos dos amorreus, a fim de nos destruir.

[[v5-1-28]]

^<<v5-1-28,28>>^ Para onde estamos nós subindo? nossos irmãos fizeram com que se derretesse o nosso coração, dizendo: Maior e mais alto é o povo do que nós; as cidades são grandes e fortificadas até o céu; e também vimos ali os filhos dos anaquins.

[[v5-1-29]]

^<<v5-1-29,29>>^ Então eu vos disse: Não vos atemorizeis, e não tenhais medo deles.

[[v5-1-30]]

^<<v5-1-30,30>>^ O Senhor vosso Deus, que vai adiante de vós, ele pelejará por vós, conforme tudo o que tem feito por vós diante dos vossos olhos, no Egito,

[[v5-1-31]]

^<<v5-1-31,31>>^ como também no deserto, onde vistes como o Senhor vosso Deus vos levou, como um homem leva seu filho, por todo o caminho que andastes, até chegardes a este lugar.

[[v5-1-32]]

^<<v5-1-32,32>>^ Mas nem ainda assim confiastes no Senhor vosso Deus,

[[v5-1-33]]

^<<v5-1-33,33>>^ que ia adiante de vós no caminho, de noite no fogo e de dia na nuvem, para vos achar o lugar onde devíeis acampar, e para vos mostrar o caminho por onde havíeis de andar.

[[v5-1-34]]

^<<v5-1-34,34>>^ Ouvindo, pois, o Senhor a voz das vossas palavras, indignou-se e jurou, dizendo:

[[v5-1-35]]

^<<v5-1-35,35>>^ Nenhum dos homens desta geração perversa verá a boa terra que prometi com juramento dar a vossos pais,

[[v5-1-36]]

^<<v5-1-36,36>>^ salvo Calebe, filho de Jefoné; ele a verá, e a terra que pisou darei a ele e a seus filhos, porquanto perseverou em seguir ao Senhor.

[[v5-1-37]]

^<<v5-1-37,37>>^ Também contra mim o Senhor se indignou por vossa causa, dizendo: Igualmente tu lá não entrarás.

[[v5-1-38]]

^<<v5-1-38,38>>^ Josué, filho de Num, que te serve, ele ali entrará; anima-o, porque ele fará que Israel a receba por herança.

[[v5-1-39]]

^<<v5-1-39,39>>^ E vossos pequeninos, dos quais dissestes que seriam por presa, e vossos filhos que hoje não conhecem nem o bem nem o mal, esses lá entrarão, a eles a darei e eles a possuirão.

[[v5-1-40]]

^<<v5-1-40,40>>^ Quanto a vós, porém, virai-vos, e parti para o deserto, pelo caminho do Mar Vermelho.

[[v5-1-41]]

^<<v5-1-41,41>>^ Então respondestes, e me dissestes: Pecamos contra o Senhor; nós subiremos e pelejaremos, conforme tudo o que nos ordenou o Senhor nosso Deus. Vós, pois, vos armastes, cada um, dos vossos instrumentos de guerra, e temerariamente propusestes subir a montanha.

[[v5-1-42]]

^<<v5-1-42,42>>^ E disse-me o Senhor: Dize-lhes: Não subais nem pelejeis, pois não estou no meio de vós; para que não sejais feridos diante de vossos inimigos.

[[v5-1-43]]

^<<v5-1-43,43>>^ Assim vos falei, mas não ouvistes; antes fostes rebeldes à ordem do Senhor e, agindo presunçosamente, subistes à montanha.

[[v5-1-44]]

^<<v5-1-44,44>>^ E os amorreus, que habitavam naquela montanha, vos saíram ao encontro e, perseguindo-vos como fazem as abelhas, vos destroçaram desde Seir até Horma.

[[v5-1-45]]

^<<v5-1-45,45>>^ Voltastes, pois, e chorastes perante o Senhor; mas o Senhor não ouviu a vossa voz, nem para vós inclinou os ouvidos.

[[v5-1-46]]

^<<v5-1-46,46>>^ Assim foi grande a vossa demora em Cades, pois ali vos demorastes muitos dias.

'''

xref:004-numeros/004-numeros-036.adoc#v4-36-0[&#60; Capítulo Anterior] | <<v5-1-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[Próximo Capítulo &#62;]