include::./index.adoc[]

[[v5-5-0]]
=== Deuteronômio, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-5-1]]

^<<v5-5-1,1>>^ Chamou, pois, Moisés a todo o Israel, e disse-lhes: Ouve, ó Israel, os estatutos e preceitos que hoje vos falo aos ouvidos, para que os aprendais e cuideis em os cumprir.

[[v5-5-2]]

^<<v5-5-2,2>>^ O Senhor nosso Deus fez um pacto conosco em Horebe.

[[v5-5-3]]

^<<v5-5-3,3>>^ Não com nossos pais fez o Senhor esse pacto, mas conosco, sim, com todos nós que hoje estamos aqui vivos.

[[v5-5-4]]

^<<v5-5-4,4>>^ Face a face falou o Senhor conosco no monte, do meio o fogo

[[v5-5-5]]

^<<v5-5-5,5>>^ &#123;estava eu nesse tempo entre o Senhor e vós, para vos anunciar a palavra do Senhor; porque tivestes medo por causa do fogo, e não subistes ao monte&#125; , dizendo ele:

[[v5-5-6]]

^<<v5-5-6,6>>^ Eu sou o Senhor teu Deus, que te tirei da terra do Egito, da casa da servidão.

[[v5-5-7]]

^<<v5-5-7,7>>^ Não terás outros deuses diante de mim.

[[v5-5-8]]

^<<v5-5-8,8>>^ Não farás para ti imagem esculpida, nem figura alguma do que há em cima no céu, nem embaixo na terra, nem nas águas debaixo da terra;

[[v5-5-9]]

^<<v5-5-9,9>>^ não te encurvarás diante delas, nem as servirás; porque eu, o Senhor teu Deus, sou Deus zeloso, que visito a iniqüidade dos pais nos filhos até a terceira e quarta geração daqueles que me odeiam,

[[v5-5-10]]

^<<v5-5-10,10>>^ e uso de misericórdia com milhares dos que me amam e guardam os meus mandamentos.

[[v5-5-11]]

^<<v5-5-11,11>>^ Não tomarás o nome do Senhor teu Deus em vão; porque o Senhor não terá por inocente aquele que tomar o seu nome em vão.

[[v5-5-12]]

^<<v5-5-12,12>>^ Guarda o dia do sábado, para o santificar, como te ordenou o senhor teu Deus;

[[v5-5-13]]

^<<v5-5-13,13>>^ seis dias trabalharás, e farás todo o teu trabalho;

[[v5-5-14]]

^<<v5-5-14,14>>^ mas o sétimo dia é o sábado do Senhor teu Deus; nesse dia não farás trabalho algum, nem tu, nem teu filho, nem tua filha, nem o teu servo, nem a tua serva, nem o teu boi, nem o teu jumento, nem animal algum teu, nem o estrangeiro que está dentro das tuas portas; para que o teu servo e a tua serva descansem assim como tu.

[[v5-5-15]]

^<<v5-5-15,15>>^ Lembra-te de que foste servo na terra do Egito, e que o Senhor teu Deus te tirou dali com mão forte e braço estendido; pelo que o Senhor teu Deus te ordenou que guardasses o dia do sábado.

[[v5-5-16]]

^<<v5-5-16,16>>^ Honra a teu pai e a tua mãe, como o senhor teu Deus te ordenou, para que se prolonguem os teus dias, e para que te vá bem na terra que o Senhor teu Deus te dá.

[[v5-5-17]]

^<<v5-5-17,17>>^ Não matarás.

[[v5-5-18]]

^<<v5-5-18,18>>^ Não adulterarás.

[[v5-5-19]]

^<<v5-5-19,19>>^ Não furtarás.

[[v5-5-20]]

^<<v5-5-20,20>>^ Não dirás falso testemunho contra o teu próximo.

[[v5-5-21]]

^<<v5-5-21,21>>^ Não cobiçarás a mulher do teu próximo; não desejarás a casa do teu próximo; nem o seu campo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma do teu próximo.

[[v5-5-22]]

^<<v5-5-22,22>>^ Essas palavras falou o senhor a toda a vossa assembléia no monte, do meio do fogo, da nuvem e da escuridão, com grande voz; e nada acrescentou. E escreveu-as em duas tábuas de pedra, que ele me deu.

[[v5-5-23]]

^<<v5-5-23,23>>^ Mas quando ouvistes a voz do meio das trevas, enquanto ardia o monte em fogo, viestes ter comigo, mesmo todos os cabeças das vossas tribos, e vossos anciãos,

[[v5-5-24]]

^<<v5-5-24,24>>^ e dissestes: Eis que o Senhor nosso Deus nos fez ver a sua glória e a sua grandeza, e ouvimos a sua voz do meio do fogo; hoje vimos que Deus fala com o homem, e este ainda continua vivo.

[[v5-5-25]]

^<<v5-5-25,25>>^ Agora, pois, por que havemos de morrer? Este grande fogo nos consumirá; se ainda mais ouvirmos a voz do Senhor nosso Deus, morreremos.

[[v5-5-26]]

^<<v5-5-26,26>>^ Porque, quem há de toda a carne, que tenha ouvido a voz do Deus vivente a falar do meio do fogo, como nós a ouvimos, e ainda continue vivo?

[[v5-5-27]]

^<<v5-5-27,27>>^ Chega-te tu, e ouve tudo o que o Senhor nosso Deus falar; e tu nos dirás tudo o que ele te disser; assim o ouviremos e o cumpriremos.

[[v5-5-28]]

^<<v5-5-28,28>>^ Ouvindo, pois, o Senhor as vossas palavras, quando me faláveis, disse-me: Eu ouvi as palavras deste povo, que eles te disseram; falaram bem em tudo quanto disseram.

[[v5-5-29]]

^<<v5-5-29,29>>^ Quem dera que eles tivessem tal coração que me temessem, e guardassem em todo o tempo todos os meus mandamentos, para que bem lhes fosse a eles, e a seus filhos para sempre!

[[v5-5-30]]

^<<v5-5-30,30>>^ Vai, dize-lhes: Voltai às vossas tendas.

[[v5-5-31]]

^<<v5-5-31,31>>^ Tu, porém, deixa-te ficar aqui comigo, e eu te direi todos os mandamentos, estatutos e preceitos que tu lhes hás de ensinar, para que eles os cumpram na terra que eu lhes dou para a possuírem.

[[v5-5-32]]

^<<v5-5-32,32>>^ Olhai, pois, que façais como vos ordenou o Senhor vosso Deus; não vos desviareis nem para a direita nem para a esquerda.

[[v5-5-33]]

^<<v5-5-33,33>>^ Andareis em todo o caminho que vos ordenou a Senhor vosso Deus, para que vivais e bem vos suceda, e prolongueis os vossos dias na terra que haveis de possuir.

'''

xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[&#60; Capítulo Anterior] | <<v5-5-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[Próximo Capítulo &#62;]