include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-10-1]]

^<<v5-10-1,1>>^ Naquele mesmo tempo me disse o Senhor: Alisa duas tábuas de pedra, como as primeiras, e sobe a mim ao monte, e faze uma arca de madeira.

[[v5-10-2]]

^<<v5-10-2,2>>^ Nessas tábuas escreverei as palavras que estavam nas primeiras tábuas, que quebras-te, e as porás na arca.

[[v5-10-3]]

^<<v5-10-3,3>>^ Assim, fiz ume arca de madeira de acácia, alisei duas tábuas de pedra, como as primeiras, e subi ao monte com as duas tábuas nas mãos.

[[v5-10-4]]

^<<v5-10-4,4>>^ Então o Senhor escreveu nas tábuas, conforme a primeira escritura, os dez mandamentos, que ele vos falara no monte, do meio do fogo, no dia da assembléia; e o Senhor mas deu a mim.

[[v5-10-5]]

^<<v5-10-5,5>>^ Virei-me, pois, desci do monte e pus as tábuas na arca que fizera; e ali estão, como o Senhor me ordenou.

[[v5-10-6]]

^<<v5-10-6,6>>^ &#123;Ora, partiram os filhos de Israel de Beerote-Bene-Jaacã para Mosera. Ali faleceu Arão e foi sepultado; e Eleazar, seu filho, administrou o sacerdócio em seu lugar.

[[v5-10-7]]

^<<v5-10-7,7>>^ Dali partiram para Gudgoda, e de Gudgoda para Jotbatá, terra de ribeiros de águas.

[[v5-10-8]]

^<<v5-10-8,8>>^ Por esse tempo o Senhor separou a tribo de Levi, para levar a arca do pacto do Senhor, para estar diante do Senhor, servindo-o, e para abençoar em seu nome até o dia de hoje.

[[v5-10-9]]

^<<v5-10-9,9>>^ Pelo que Levi não tem parte nem herança com seus irmãos; o Senhor é a sua herança, como o Senhor teu Deus lhe disse.&#125;

[[v5-10-10]]

^<<v5-10-10,10>>^ Também, como antes, eu estive no monte quarenta dias e quarenta noites; e o Senhor me ouviu ainda essa vez; o Senhor não te quis destruir;

[[v5-10-11]]

^<<v5-10-11,11>>^ antes disse-me o Senhor: Levanta-te, põe-te a caminho diante do povo; eles entrarão e possuirão a terra que com juramento prometi a seus pais lhes daria.

[[v5-10-12]]

^<<v5-10-12,12>>^ Agora, pois, ó Israel, que é que o Senhor teu Deus requer de ti, senão que temas o Senhor teu Deus, que andes em todos os seus caminhos, e o ames, e sirvas ao Senhor teu Deus de todo o teu coração e de toda a tua alma,

[[v5-10-13]]

^<<v5-10-13,13>>^ que guardes os mandamentos do Senhor, e os seus estatutos, que eu hoje te ordeno para o teu bem?

[[v5-10-14]]

^<<v5-10-14,14>>^ Eis que do Senhor teu Deus são o céu e o céu dos céus, a terra e tudo o que nela há.

[[v5-10-15]]

^<<v5-10-15,15>>^ Entretanto o Senhor se afeiçoou a teus pais para os amar; e escolheu a sua descendência depois deles, isto é, a vós, dentre todos os povos, como hoje se vê.

[[v5-10-16]]

^<<v5-10-16,16>>^ Circuncidai, pois, o prepúcio do vosso coração, e não mais endureçais a vossa cerviz.

[[v5-10-17]]

^<<v5-10-17,17>>^ Pois o Senhor vosso Deus, é o Deus dos deuses, e o Senhor dos senhores, o Deus grande, poderoso e terrível, que não faz acepção de pessoas, nem recebe peitas;

[[v5-10-18]]

^<<v5-10-18,18>>^ que faz justiça ao órfão e à viúva, e ama o estrangeiro, dando-lhe pão e roupa.

[[v5-10-19]]

^<<v5-10-19,19>>^ Pelo que amareis o estrangeiro, pois fostes estrangeiros na terra do Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ Ao Senhor teu Deus temerás; a ele servirás, e a ele te apegarás, e pelo seu nome; jurarás.

[[v5-10-21]]

^<<v5-10-21,21>>^ Ele é o teu louvor e o teu Deus, que te fez estas grandes e terríveis coisas que os teus olhos têm visto.

[[v5-10-22]]

^<<v5-10-22,22>>^ Com setenta almas teus pais desceram ao Egito; e agora o Senhor teu Deus te fez, em número, como as estrelas do céu.

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]