include::./index.adoc[]

[[v5-21-0]]
=== Deuteronômio, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-21-1]]

^<<v5-21-1,1>>^ Se na terra que o Senhor teu Deus te dá para a possuíres, for encontrado algum morto caído no campo, sem que se saiba quem o matou,

[[v5-21-2]]

^<<v5-21-2,2>>^ sairão os teus anciãos e os teus juízes, e medirão as distâncias dali até as cidades que estiverem em redor do morto;

[[v5-21-3]]

^<<v5-21-3,3>>^ e será que, na cidade mais próxima do morto, os anciãos da mesma tomarão uma novilha da manada, que ainda não tenha trabalhado nem tenha puxado na canga,

[[v5-21-4]]

^<<v5-21-4,4>>^ trarão a novilha a um vale de águas correntes, que nunca tenha sido lavrado nem semeado, e ali, naquele vale, quebrarão o pescoço à novilha.

[[v5-21-5]]

^<<v5-21-5,5>>^ Então se achegarão os sacerdotes, filhos de Levi; pois o Senhor teu Deus os escolheu para o servirem, e para abençoarem em nome do Senhor; e segundo a sua sentença se determinará toda demanda e todo ferimento;

[[v5-21-6]]

^<<v5-21-6,6>>^ e todos os anciãos da mesma cidade, a mais próxima do morto, lavarão as mãos sobre a novilha cujo pescoço foi quebrado no vale,

[[v5-21-7]]

^<<v5-21-7,7>>^ e, protestando, dirão: As nossas mãos não derramaram este sangue, nem os nossos olhos o viram.

[[v5-21-8]]

^<<v5-21-8,8>>^ Perdoa, ó Senhor, ao teu povo Israel, que tu resgataste, e não ponhas o sangue inocente no meio de teu povo Israel. E aquele sangue lhe será perdoado.

[[v5-21-9]]

^<<v5-21-9,9>>^ Assim tirarás do meio de ti o sangue inocente, quando fizeres o que é reto aos olhos do Senhor.

[[v5-21-10]]

^<<v5-21-10,10>>^ Quando saíres à peleja contra os teus inimigos, e o Senhor teu Deus os entregar nas tuas mãos, e os levares cativos,

[[v5-21-11]]

^<<v5-21-11,11>>^ se vires entre os cativas uma mulher formosa à vista e, afeiçoando-te a ela, quiseres tomá-la por mulher,

[[v5-21-12]]

^<<v5-21-12,12>>^ então a trarás para a tua casa; e ela, tendo rapado a cabeça, cortado as unhas,

[[v5-21-13]]

^<<v5-21-13,13>>^ e despido as vestes do seu cativeiro, ficará na tua casa, e chorará a seu pai e a sua mãe um mês inteiro; depois disso estarás com ela, e serás seu marido e ela será tua mulher.

[[v5-21-14]]

^<<v5-21-14,14>>^ E, se te enfadares dela, deixá-la-ás ir à sua vontade; mas de modo nenhum a venderás por dinheiro, nem a tratarás como escrava, porque a humilhaste.

[[v5-21-15]]

^<<v5-21-15,15>>^ Se um homem tiver duas mulheres, uma a quem ama e outra a quem despreza, e ambas lhe tiverem dado filhos, e o filho primogênito for da desprezada,

[[v5-21-16]]

^<<v5-21-16,16>>^ quando fizer herdar a seus filhos o que tiver, não poderá dar a primogenitura ao filho da amada, preferindo-o ao filha da desprezada, que é o primogênito;

[[v5-21-17]]

^<<v5-21-17,17>>^ mas ao filho da aborrecida reconhecerá por primogênito, dando-lhe dobrada porção de tudo quanto tiver, porquanto ele é as primícias da sua força; o direito da primogenitura é dele.

[[v5-21-18]]

^<<v5-21-18,18>>^ Se alguém tiver um filho contumaz e rebelde, que não obedeça à voz de seu pai e à voz de sua mãe, e que, embora o castiguem, não lhes dê ouvidos,

[[v5-21-19]]

^<<v5-21-19,19>>^ seu pai e sua mãe, pegando nele, o levarão aos anciãos da sua cidade, e à porta do seu lugar;

[[v5-21-20]]

^<<v5-21-20,20>>^ e dirão aos anciãos da cidade: Este nosso filho é contumaz e rebelde; não dá ouvidos à nossa voz; é comilão e beberrão.

[[v5-21-21]]

^<<v5-21-21,21>>^ Então todos os homens da sua cidade o apedrejarão, até que morra; assim exterminarás o mal do meio de ti; e todo o Israel, ouvindo isso, temerá.

[[v5-21-22]]

^<<v5-21-22,22>>^ Se um homem tiver cometido um pecado digno de morte, e for morto, e o tiveres pendurado num madeiro,

[[v5-21-23]]

^<<v5-21-23,23>>^ o seu cadáver não permanecerá toda a noite no madeiro, mas certamente o enterrarás no mesmo dia; porquanto aquele que é pendurado é maldito de Deus. Assim não contaminarás a tua terra, que o Senhor teu Deus te dá em herança.

'''

xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[&#60; Capítulo Anterior] | <<v5-21-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[Próximo Capítulo &#62;]