include::./index.adoc[]

[[v5-32-0]]
=== Deuteronômio, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-32-1]]

^<<v5-32-1,1>>^ Inclinai os ouvidos, ó céus, e falarei; e ouça a terra as palavras da minha boca.

[[v5-32-2]]

^<<v5-32-2,2>>^ Caia como a chuva a minha doutrina; destile a minha palavra como o orvalho, como chuvisco sobre a erva e como chuvas sobre a relva.

[[v5-32-3]]

^<<v5-32-3,3>>^ Porque proclamarei o nome do Senhor; engrandecei o nosso Deus.

[[v5-32-4]]

^<<v5-32-4,4>>^ Ele é a Rocha; suas obras são perfeitas, porque todos os seus caminhos são justos; Deus é fiel e sem iniqüidade; justo e reto é ele.

[[v5-32-5]]

^<<v5-32-5,5>>^ Corromperam-se contra ele; não são seus filhos, e isso é a sua mancha; geração perversa e depravada é.

[[v5-32-6]]

^<<v5-32-6,6>>^ É assim que recompensas ao Senhor, povo louco e insensato? não é ele teu pai, que te adquiriu, que te fez e te estabeleceu?

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembra-te dos dias da antigüidade, atenta para os anos, geração por geração; pergunta a teu pai, e ele te informará, aos teus anciãos, e eles to dirão.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo dava às nações a sua herança, quando separava os filhos dos homens, estabeleceu os termos dos povos conforme o número dos filhos de Israel.

[[v5-32-9]]

^<<v5-32-9,9>>^ Porque a porção do Senhor é o seu povo; Jacó é a parte da sua herança.

[[v5-32-10]]

^<<v5-32-10,10>>^ Achou-o numa terra deserta, e num erma de solidão e horrendos uivos; cercou-o de proteção; cuidou dele, guardando-o como a menina do seu olho.

[[v5-32-11]]

^<<v5-32-11,11>>^ Como a águia desperta o seu ninho, adeja sobre os seus filhos e, estendendo as suas asas, toma-os, e os leva sobre as suas asas,

[[v5-32-12]]

^<<v5-32-12,12>>^ assim só o Senhor o guiou, e não havia com ele deus estranho.

[[v5-32-13]]

^<<v5-32-13,13>>^ Ele o fez cavalgar sobre as alturas da terra, e comer os frutos do campo; também o fez chupar mel da rocha e azeite da dura pederneira,

[[v5-32-14]]

^<<v5-32-14,14>>^ coalhada das vacas e leite das ovelhas, com a gordura dos cordeiros, dos carneiros de Basã, e dos bodes, com o mais fino trigo; e por vinho bebeste o sangue das uvas.

[[v5-32-15]]

^<<v5-32-15,15>>^ E Jesurum, engordando, recalcitrou &#123;tu engordaste, tu te engrossaste e te cevaste&#125;; então abandonou a Deus, que o fez, e desprezou a Rocha da sua salvação.

[[v5-32-16]]

^<<v5-32-16,16>>^ Com deuses estranhos o moveram a zelos; com abominações o provocaram à ira:

[[v5-32-17]]

^<<v5-32-17,17>>^ Ofereceram sacrifícios aos demônios, não a Deus, a deuses que não haviam conhecido, deuses novos que apareceram há pouco, aos quais os vossos pais não temeram.

[[v5-32-18]]

^<<v5-32-18,18>>^ Olvidaste a Rocha que te gerou, e te esqueceste do Deus que te formou.

[[v5-32-19]]

^<<v5-32-19,19>>^ Vendo isto, o Senhor os desprezou, por causa da provocação que lhe fizeram seus filhos e suas filhas;

[[v5-32-20]]

^<<v5-32-20,20>>^ e disse: Esconderei deles o meu rosto, verei qual será o seu fim, porque geração perversa são eles, filhos em quem não há fidelidade.

[[v5-32-21]]

^<<v5-32-21,21>>^ A zelos me provocaram cem aquilo que não é Deus, com as suas vaidades me provocaram à ira; portanto eu os provocarei a zelos com aquele que não é povo, com uma nação insensata os despertarei à ira.

[[v5-32-22]]

^<<v5-32-22,22>>^ Porque um fogo se acendeu na minha ira, e arde até o mais profundo do Seol, e devora a terra com o seu fruto, e abrasa os fundamentos dos montes.

[[v5-32-23]]

^<<v5-32-23,23>>^ Males amontoarei sobre eles, esgotarei contra eles as minhas setas.

[[v5-32-24]]

^<<v5-32-24,24>>^ Consumidos serão de fome, devorados de raios e de amarga destruição; e contra eles enviarei dentes de feras, juntamente com o veneno dos que se arrastam no pó.

[[v5-32-25]]

^<<v5-32-25,25>>^ Por fora devastará a espada, e por dentro o pavor, tanto ao mancebo como à virgem, assim à criança de peito como ao homem encanecido.

[[v5-32-26]]

^<<v5-32-26,26>>^ Eu teria dito: Por todos os cantos os espalharei, farei cessar a sua memória dentre os homens,

[[v5-32-27]]

^<<v5-32-27,27>>^ se eu não receasse a vexação da parte do inimigo, para que os seus adversários, iludindo-se, não dissessem: A nossa mão está exaltada; não foi o Senhor quem fez tudo isso.

[[v5-32-28]]

^<<v5-32-28,28>>^ Porque são gente falta de conselhos, e neles não há entendimento.

[[v5-32-29]]

^<<v5-32-29,29>>^ Se eles fossem sábios, entenderiam isso, e atentariam para o seu fim!

[[v5-32-30]]

^<<v5-32-30,30>>^ Como poderia um só perseguir mil, e dois fazer rugir dez mil, se a sua Rocha não os vendera, e o Senhor não os entregara?

[[v5-32-31]]

^<<v5-32-31,31>>^ Porque a sua rocha não é como a nossa Rocha, sendo até os nossos inimigos juízes disso.

[[v5-32-32]]

^<<v5-32-32,32>>^ Porque a sua vinha é da vinha de Sodoma e dos campos de Gomorra; as suas uvas são uvas venenosas, seus cachos são amargos.

[[v5-32-33]]

^<<v5-32-33,33>>^ O seu vinho é veneno de serpentes, e peçonha cruel de víboras.

[[v5-32-34]]

^<<v5-32-34,34>>^ Não está isto encerrado comigo? selado nos meus tesouros?

[[v5-32-35]]

^<<v5-32-35,35>>^ Minha é a vingança e a recompensa, ao tempo em que resvalar o seu pé; porque o dia da sua ruína está próximo, e as coisas que lhes hão de suceder se apressam a chegar.

[[v5-32-36]]

^<<v5-32-36,36>>^ Porque o Senhor vindicará ao seu povo, e se arrependerá no tocante aos seus servos, quando vir que o poder deles já se foi, e que não resta nem escravo nem livre.

[[v5-32-37]]

^<<v5-32-37,37>>^ Então dirá: Onde estão os seus deuses, a rocha em que se refugiavam,

[[v5-32-38]]

^<<v5-32-38,38>>^ os que comiam a gordura dos sacrifícios deles e bebiam o vinho das suas ofertas de libação? Levantem-se eles, e vos ajudem, a fim de que haja agora refúgio para vós.

[[v5-32-39]]

^<<v5-32-39,39>>^ Vede agora que eu, eu o sou, e não há outro deus além de mim; eu faço morrer e eu faço viver; eu firo e eu saro; e não há quem possa livrar da minha mão.

[[v5-32-40]]

^<<v5-32-40,40>>^ Pois levanto a minha mão ao céu, e digo: Como eu vivo para sempre,

[[v5-32-41]]

^<<v5-32-41,41>>^ se eu afiar a minha espada reluzente, e a minha mão travar do juízo, então retribuirei vingança aos meus adversários, e recompensarei aos que me odeiam.

[[v5-32-42]]

^<<v5-32-42,42>>^ De sangue embriagarei as minhas setas, e a minha espada devorará carne; do sangue dos mortes e dos cativos, das cabeças cabeludas dos inimigos

[[v5-32-43]]

^<<v5-32-43,43>>^ Aclamai, ó nações, com alegria, o povo dele, porque ele vingará o sangue dos seus servos; aos seus adversários retribuirá vingança, e fará expiação pela sua terra e pelo seu povo.

[[v5-32-44]]

^<<v5-32-44,44>>^ Veio, pois, Moisés, e proferiu todas as palavras deste cântico na presença do povo, ele e Oséias, filho de Num.

[[v5-32-45]]

^<<v5-32-45,45>>^ E, acabando Moisés de falar todas essas palavras a todo o Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ disse-lhes: Aplicai o vosso coração a todas as palavras que eu hoje vos testifico, as quais haveis de recomendar a vossos filhos, para que tenham cuidado de cumprir todas as palavras desta lei.

[[v5-32-47]]

^<<v5-32-47,47>>^ Porque esta palavra não vos é vã, mas é a vossa vida, e por esta mesma palavra prolongareis os dias na terra à qual ides, passando o Jordão, para a possuir.

[[v5-32-48]]

^<<v5-32-48,48>>^ Naquele mesmo dia falou o Senhor a Moisés, dizendo:

[[v5-32-49]]

^<<v5-32-49,49>>^ Sobe a este monte de Abarim, ao monte Nebo, que está na terra de Moabe, defronte de Jericó, e vê a terra de Canaã, que eu dou aos filhos de Israel por possessão;

[[v5-32-50]]

^<<v5-32-50,50>>^ e morre no monte a que vais subir, e recolhe-te ao teu povo; assim como Arão, teu irmão, morreu no monte Hor, e se recolheu ao seu povo;

[[v5-32-51]]

^<<v5-32-51,51>>^ porquanto pecastes contra mim no meio dos filhos de Israel, junto às águas de Meribá de Cades, no deserto de Zim, pois não me santificastes no meio dos filhos de Israel.

[[v5-32-52]]

^<<v5-32-52,52>>^ Pelo que verás a terra diante de ti, porém lá não entrarás, na terra que eu dou aos filhos de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]