include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-15-1]]

^<<v5-15-1,1>>^ Ao fim de cada sete anos farás remissão.

[[v5-15-2]]

^<<v5-15-2,2>>^ E este é o modo da remissão: todo credor remitirá o que tiver emprestado ao seu próximo; não o exigirá do seu próximo ou do seu irmão, pois a remissão do Senhor é apregoada.

[[v5-15-3]]

^<<v5-15-3,3>>^ Do estrangeiro poderás exigi-lo; mas o que é teu e estiver em poder de teu irmão, a tua mão o remitirá.

[[v5-15-4]]

^<<v5-15-4,4>>^ Contudo não haverá entre ti pobre algum &#123;pois o Senhor certamente te abençoará na terra que o Senhor teu Deus te dá por herança, para a possuíres&#125;,

[[v5-15-5]]

^<<v5-15-5,5>>^ contanto que ouças diligentemente a voz do Senhor teu Deus para cuidares em cumprir todo este mandamento que eu hoje te ordeno.

[[v5-15-6]]

^<<v5-15-6,6>>^ Porque o Senhor teu Deus te abençoará, como te prometeu; assim, emprestarás a muitas nações, mas não tomarás empréstimos; e dominarás sobre muitas nações, porém elas não dominarão sobre ti.

[[v5-15-7]]

^<<v5-15-7,7>>^ Quando no meio de ti houver algum pobre, dentre teus irmãos, em qualquer das tuas cidades na terra que o Senhor teu Deus te dá, não endurecerás o teu coração, nem fecharás a mão a teu irmão pobre;

[[v5-15-8]]

^<<v5-15-8,8>>^ antes lhe abrirás a tua mão, e certamente lhe emprestarás o que lhe falta, quanto baste para a sua necessidade.

[[v5-15-9]]

^<<v5-15-9,9>>^ Guarda-te, que não haja pensamento vil no teu coração e venhas a dizer: Vai-se aproximando o sétimo ano, o ano da remissão; e que o teu olho não seja maligno para com teu irmão pobre, e não lhe dês nada; e que ele clame contra ti ao Senhor, e haja em ti pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Livremente lhe darás, e não fique pesaroso o teu coração quando lhe deres; pois por esta causa te abençoará o Senhor teu Deus em toda a tua obra, e em tudo no que puseres a mão.

[[v5-15-11]]

^<<v5-15-11,11>>^ Pois nunca deixará de haver pobres na terra; pelo que eu te ordeno, dizendo: Livremente abrirás a mão para o teu irmão, para o teu necessitado, e para o teu pobre na tua terra.

[[v5-15-12]]

^<<v5-15-12,12>>^ Se te for vendido um teu irmão hebreu ou irmã hebréia, seis anos te servirá, mas na sétimo ano o libertarás.

[[v5-15-13]]

^<<v5-15-13,13>>^ E, quando o libertares, não o deixarás ir de mãos vazias;

[[v5-15-14]]

^<<v5-15-14,14>>^ liberalmente o fornecerás do teu rebanho, e da tua eira, e do teu lagar; conforme o Senhor teu Deus tiver abençoado te darás.

[[v5-15-15]]

^<<v5-15-15,15>>^ Pois lembrar-te-ás de que foste servo na terra do Egito, e de que o Senhor teu Deus te resgatou; pelo que eu hoje te ordeno isso.

[[v5-15-16]]

^<<v5-15-16,16>>^ Mas se ele te disser: Não sairei de junto de ti; porquanto te ama a ti e a tua casa, por estar bem contigo;

[[v5-15-17]]

^<<v5-15-17,17>>^ então tomarás uma sovela, e lhe furarás a orelha contra a porta, e ele será teu servo para sempre; e também assim farás à tua serva.

[[v5-15-18]]

^<<v5-15-18,18>>^ Não seja duro aos teus olhos de teres de libertá-lo, pois seis anos te prestou serviço equivalente ao dobro do salário dum mercenário; e o Senhor teu Deus te abençoará em tudo o que fizeres.

[[v5-15-19]]

^<<v5-15-19,19>>^ Todo primogênito que nascer das tuas vacas e das tuas ovelhas santificarás ao Senhor teu Deus; com o primogênito do teu boi não trabalharás, nem tosquiarás o primogênito das tuas ovelhas.

[[v5-15-20]]

^<<v5-15-20,20>>^ Perante o Senhor teu Deus os comerás, tu e a tua casa, de ano em ano, no lugar que o Senhor escolher.

[[v5-15-21]]

^<<v5-15-21,21>>^ Mas se nele houver algum defeito, como se for coxo, ou cego, ou tiver qualquer outra deformidade, não o sacrificarás ao Senhor teu Deus.

[[v5-15-22]]

^<<v5-15-22,22>>^ Nas tuas portas o comerás; o imundo e o limpo igualmente o comerão, como da gazela ou do veado.

[[v5-15-23]]

^<<v5-15-23,23>>^ Somente do seu sangue não comerás; sobre a terra o derramarás como água.

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]