include::./index.adoc[]

[[v5-25-0]]
=== Deuteronômio, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-25-1]]

^<<v5-25-1,1>>^ Se houver contenda entre alguns, e vierem a juízo para serem julgados, justificar-se-á ao inocente, e ao culpado condenar-se-á.

[[v5-25-2]]

^<<v5-25-2,2>>^ E se o culpado merecer açoites, o juiz fará que ele se deite e seja açoitado na sua presença, de acordo com a gravidade da sua culpa.

[[v5-25-3]]

^<<v5-25-3,3>>^ Até quarenta açoites lhe poderá dar, não mais; para que, porventura, se lhe der mais açoites do que estes, teu irmão não fique envilecido aos teus olhos.

[[v5-25-4]]

^<<v5-25-4,4>>^ Não atarás a boca ao boi quando estiver debulhando.

[[v5-25-5]]

^<<v5-25-5,5>>^ Se irmãos morarem juntos, e um deles morrer sem deixar filho, a mulher do falecido não se casará com homem estranho, de fora; seu cunhado estará com ela, e a tomará por mulher, fazendo a obrigação de cunhado para com ela.

[[v5-25-6]]

^<<v5-25-6,6>>^ E o primogênito que ela lhe der sucederá ao nome do irmão falecido, para que o nome deste não se apague de Israel.

[[v5-25-7]]

^<<v5-25-7,7>>^ Mas, se o homem não quiser tomar sua cunhada, esta subirá à porta, aos anciãos, e dirá: Meu cunhado recusa suscitar a seu irmão nome em Israel; não quer cumprir para comigo o dever de cunhado.

[[v5-25-8]]

^<<v5-25-8,8>>^ Então os anciãos da sua cidade o chamarão, e falarão com ele. Se ele persistir, e disser: Não quero tomá-la;

[[v5-25-9]]

^<<v5-25-9,9>>^ sua cunhada se chegará a ele, na presença dos anciãos, e lhe descalçará o sapato do pé, e lhe cuspirá ao rosto, e dirá: Assim se fará ao homem que não edificar a casa de seu irmão.

[[v5-25-10]]

^<<v5-25-10,10>>^ E sua casa será chamada em Israel a casa do descalçado.

[[v5-25-11]]

^<<v5-25-11,11>>^ Quando pelejarem dois homens, um contra o outro, e a mulher de um chegar para livrar a seu marido da mão daquele que o fere, e ela, estendendo a mão, lhe pegar pelas suas vergonhas,

[[v5-25-12]]

^<<v5-25-12,12>>^ decepar-lhe-á a mão; o teu olho não terá piedade dela.

[[v5-25-13]]

^<<v5-25-13,13>>^ Não terás na tua bolsa pesos diferentes, um grande e um pequeno.

[[v5-25-14]]

^<<v5-25-14,14>>^ Não terás na tua casa duas efas, uma grande e uma pequena.

[[v5-25-15]]

^<<v5-25-15,15>>^ Terás peso inteiro e justo; terás efa inteira e justa; para que se prolonguem os teus dias na terra que o Senhor teu Deus te dá.

[[v5-25-16]]

^<<v5-25-16,16>>^ Porque é abominável ao Senhor teu Deus todo aquele que faz tais coisas, todo aquele que pratica a injustiça.

[[v5-25-17]]

^<<v5-25-17,17>>^ Lembra-te do que te fez Amaleque no caminho, quando saías do Egito;

[[v5-25-18]]

^<<v5-25-18,18>>^ como te saiu ao encontro no caminho e feriu na tua retaguarda todos os fracos que iam após ti, estando tu cansado e afadigado; e não temeu a Deus.

[[v5-25-19]]

^<<v5-25-19,19>>^ Quando, pois, o Senhor teu Deus te houver dado repouso de todos os teus inimigos em redor, na terra que o Senhor teu Deus te dá por herança para a possuíres, apagarás a memória de Amaleque de debaixo do céu; não te esquecerás.

'''

xref:005-deuteronomio/005-deuteronomio-024.adoc#v5-24-0[&#60; Capítulo Anterior] | <<v5-25-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[Próximo Capítulo &#62;]