include::./index.adoc[]

[[v5-28-0]]
=== Deuteronômio, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-28-1]]

^<<v5-28-1,1>>^ Se ouvires atentamente a voz do Senhor teu Deus, tendo cuidado de guardar todos os seus mandamentos que eu hoje te ordeno, o Senhor teu Deus te exaltará sobre todas as nações da terra;

[[v5-28-2]]

^<<v5-28-2,2>>^ e todas estas bênçãos virão sobre ti e te alcançarão, se ouvires a voz do Senhor teu Deus:

[[v5-28-3]]

^<<v5-28-3,3>>^ Bendito serás na cidade, e bendito serás no campo.

[[v5-28-4]]

^<<v5-28-4,4>>^ Bendito o fruto do teu ventre, e o fruto do teu solo, e o fruto dos teus animais, e as crias das tuas vacas e das tuas ovelhas.

[[v5-28-5]]

^<<v5-28-5,5>>^ Bendito o teu cesto, e a tua amassadeira.

[[v5-28-6]]

^<<v5-28-6,6>>^ Bendito serás quando entrares, e bendito serás quando saíres.

[[v5-28-7]]

^<<v5-28-7,7>>^ O Senhor entregará, feridos diante de ti, os teus inimigos que se levantarem contra ti; por um caminho sairão contra ti, mas por sete caminhos rugirão da tua presença.

[[v5-28-8]]

^<<v5-28-8,8>>^ O Senhor mandará que a bênção esteja contigo nos teus celeiros e em tudo a que puseres a tua mão; e te abençoará na terra que o Senhor teu Deus te dá.

[[v5-28-9]]

^<<v5-28-9,9>>^ O Senhor te confirmará para si por povo santo, como te jurou, se guardares os mandamentos do Senhor teu Deus e andares nos seus caminhos.

[[v5-28-10]]

^<<v5-28-10,10>>^ Assim todos os povos da terra verão que és chamado pelo nome do Senhor, e terão temor de ti.

[[v5-28-11]]

^<<v5-28-11,11>>^ E o Senhor te fará prosperar grandemente no fruto do teu ventre, no fruto dos teus animais e no fruto do teu solo, na terra que o Senhor, com juramento, prometeu a teus pais te dar.

[[v5-28-12]]

^<<v5-28-12,12>>^ O Senhor te abrirá o seu bom tesouro, o céu, para dar à tua terra a chuva no seu tempo, e para abençoar todas as obras das tuas mãos; e emprestarás a muitas nações, porém tu não tomarás emprestado.

[[v5-28-13]]

^<<v5-28-13,13>>^ E o Senhor te porá por cabeça, e não por cauda; e só estarás por cima, e não por baixo; se obedeceres aos mandamentos do Senhor teu Deus, que eu hoje te ordeno, para os guardar e cumprir,

[[v5-28-14]]

^<<v5-28-14,14>>^ não te desviando de nenhuma das palavras que eu hoje te ordeno, nem para a direita nem para a esquerda, e não andando após outros deuses, para os servires.

[[v5-28-15]]

^<<v5-28-15,15>>^ Se, porém, não ouvires a voz do Senhor teu Deus, se não cuidares em cumprir todos os seus mandamentos e os seus estatutos, que eu hoje te ordeno, virão sobre ti todas estas maldições, e te alcançarão:

[[v5-28-16]]

^<<v5-28-16,16>>^ Maldito serás na cidade, e maldito serás no campo.

[[v5-28-17]]

^<<v5-28-17,17>>^ Maldito o teu cesto, e a tua amassadeira.

[[v5-28-18]]

^<<v5-28-18,18>>^ Maldito o fruto do teu ventre, e o fruto do teu solo, e as crias das tuas vacas e das tuas ovelhas.

[[v5-28-19]]

^<<v5-28-19,19>>^ Maldito serás ao entrares, e maldito serás ao saíres.

[[v5-28-20]]

^<<v5-28-20,20>>^ O Senhor mandará sobre ti a maldição, a derrota e o desapontamento, em tudo a que puseres a mão para fazer, até que sejas destruído, e até que repentinamente pereças, por causa da maldade das tuas obras, pelas quais me deixaste.

[[v5-28-21]]

^<<v5-28-21,21>>^ O Senhor fará pegar em ti a peste, até que te consuma da terra na qual estás entrando para a possuíres.

[[v5-28-22]]

^<<v5-28-22,22>>^ O Senhor te ferirá com a tísica e com a febre, com a inflamação, com o calor forte, com a seca, com crestamento e com ferrugem, que te perseguirão até que pereças

[[v5-28-23]]

^<<v5-28-23,23>>^ O céu que está sobre a tua cabeça será de bronze, e a terra que está debaixo de ti será de ferro.

[[v5-28-24]]

^<<v5-28-24,24>>^ O Senhor dará por chuva à tua terra pó; do céu descerá sobre ti a poeira, ate que sejas destruído.

[[v5-28-25]]

^<<v5-28-25,25>>^ O Senhor fará que sejas ferido diante dos teus inimigos; por um caminho sairás contra eles, e por sete caminhos fugirás deles; e serás espetáculo horrendo a todos os reinos da terra.

[[v5-28-26]]

^<<v5-28-26,26>>^ Os teus cadáveres servirão de pasto a todas as aves do céu, e aos animais da terra, e não haverá quem os enxote.

[[v5-28-27]]

^<<v5-28-27,27>>^ O Senhor te ferirá com as úlceras do Egito, com tumores, com sarna e com coceira, de que não possas curar-te;

[[v5-28-28]]

^<<v5-28-28,28>>^ o Senhor te ferirá com loucura, com cegueira, e com pasmo de coração.

[[v5-28-29]]

^<<v5-28-29,29>>^ Apalparás ao meio-dia como o cego apalpa nas trevas, e não prosperarás nos teus caminhos; serás oprimido e roubado todos os dias, e não haverá quem te salve.

[[v5-28-30]]

^<<v5-28-30,30>>^ Desposar-te-ás com uma mulher, porém outro homem dormirá com ela; edificarás uma casa, porém não morarás nela; plantarás uma vinha, porém não a desfrutarás.

[[v5-28-31]]

^<<v5-28-31,31>>^ O teu boi será morto na tua presença, porém dele não comerás; o teu jumento será roubado diante de ti, e não te será restituído a ti; as tuas ovelhas serão dadas aos teus inimigos, e não haverá quem te salve.

[[v5-28-32]]

^<<v5-28-32,32>>^ Teus filhos e tuas filhas serão dados a outro povo, os teus olhos o verão, e desfalecerão de saudades deles todo o dia; porém não haverá poder na tua mão.

[[v5-28-33]]

^<<v5-28-33,33>>^ O fruto da tua terra e todo o teu trabalho comê-los-á um povo que nunca conheceste; e serás oprimido e esmagado todos os dias.

[[v5-28-34]]

^<<v5-28-34,34>>^ E enlouquecerás pelo que hás de ver com os teus olhos.

[[v5-28-35]]

^<<v5-28-35,35>>^ Com úlceras malignas, de que não possas sarar, o Senhor te ferirá nos joelhos e nas pernas, sim, desde a planta do pé até o alto da cabeça.

[[v5-28-36]]

^<<v5-28-36,36>>^ O Senhor te levará a ti e a teu rei, que tiveres posto sobre ti, a uma nação que não conheceste, nem tu nem teus pais; e ali servirás a outros deuses, ao pau e à pedra.

[[v5-28-37]]

^<<v5-28-37,37>>^ E virás a ser por pasmo, provérbio e ludíbrio entre todos os povos a que o Senhor te levar.

[[v5-28-38]]

^<<v5-28-38,38>>^ Levarás muita semente para o teu campo, porem colherás pouco; porque o gafanhoto a consumirá.

[[v5-28-39]]

^<<v5-28-39,39>>^ Plantarás vinhas, e as cultivarás, porém não lhes beberás o vinho, nem colherás as uvas; porque o bicho as devorará.

[[v5-28-40]]

^<<v5-28-40,40>>^ Terás oliveiras em todos os teus termos, porém não te ungirás com azeite; porque a azeitona te cairá da oliveira.

[[v5-28-41]]

^<<v5-28-41,41>>^ Filhos e filhas gerarás, porém não te pertencerão; porque irão em cativeiro.

[[v5-28-42]]

^<<v5-28-42,42>>^ Todo o teu arvoredo e o fruto do teu solo consumi-los-á o gafanhoto.

[[v5-28-43]]

^<<v5-28-43,43>>^ O estrangeiro que está no meio de ti se elevará cada vez mais sobre ti, e tu cada vez mais descerás;

[[v5-28-44]]

^<<v5-28-44,44>>^ ele emprestará a ti, porém tu não emprestarás a ele; ele será a cabeça, e tu serás a cauda.

[[v5-28-45]]

^<<v5-28-45,45>>^ Todas estas maldições virão sobre ti, e te perseguirão, e te alcançarão, até que sejas destruído, por não haveres dado ouvidos à voz do Senhor teu Deus, para guardares os seus mandamentos, e os seus estatutos, que te ordenou.

[[v5-28-46]]

^<<v5-28-46,46>>^ Estarão sobre ti por sinal e por maravilha, como também sobre a tua descendência para sempre.

[[v5-28-47]]

^<<v5-28-47,47>>^ Por não haveres servido ao Senhor teu Deus com gosto e alegria de coração, por causa da abundância de tudo,

[[v5-28-48]]

^<<v5-28-48,48>>^ servirás aos teus inimigos, que o Senhor enviará contra ti, em fome e sede, e em nudez, e em falta de tudo; e ele porá sobre o teu pescoço um jugo de ferro, até que te haja destruído.

[[v5-28-49]]

^<<v5-28-49,49>>^ O Senhor levantará contra ti de longe, da extremidade da terra, uma nação que voa como a águia, nação cuja língua não entenderás;

[[v5-28-50]]

^<<v5-28-50,50>>^ nação de rosto feroz, que não respeitará ao velho, nem se compadecerá do moço;

[[v5-28-51]]

^<<v5-28-51,51>>^ e comerá o fruto dos teus animais e o fruto do teu solo, até que sejas destruído; e não te deixará grão, nem mosto, nem azeite, nem as crias das tuas vacas e das tuas ovelhas, até que te faça perecer;

[[v5-28-52]]

^<<v5-28-52,52>>^ e te sitiará em todas as tuas portas, até que em toda a tua terra venham a cair os teus altos e fortes muros, em que confiavas; sim, te sitiará em todas as tuas portas, em toda a tua terra que o Senhor teu Deus te deu.

[[v5-28-53]]

^<<v5-28-53,53>>^ E, no cerco e no aperto com que os teus inimigos te apertarão, comerás o fruto do teu ventre, a carne de teus filhos e de tuas filhas, que o Senhor teu Deus te houver dado.

[[v5-28-54]]

^<<v5-28-54,54>>^ Quanto ao homem mais mimoso e delicado no meio de ti, o seu olho será mesquinho para com o seu irmão, para com a mulher de seu regaço, e para com os filhos que ainda lhe ficarem de resto;

[[v5-28-55]]

^<<v5-28-55,55>>^ de sorte que não dará a nenhum deles da carne de seus filhos que ele comer, porquanto nada lhe terá ficado de resto no cerco e no aperto com que o teu inimigo te apertará em todas as tuas portas.

[[v5-28-56]]

^<<v5-28-56,56>>^ Igualmente, quanto à mulher mais mimosa e delicada no meio de ti, que de mimo e delicadeza nunca tentou pôr a planta de seu pé sobre a terra, será mesquinho o seu olho para com o homem de seu regaço, para com seu filho, e para com sua filha;

[[v5-28-57]]

^<<v5-28-57,57>>^ também ela será mesquinha para com as suas páreas, que saírem dentre os seus pés, e para com os seus filhos que tiver; porque os comerá às escondidas pela falta de tudo, no cerco e no aperto com que o teu inimigo te apertará nas tuas portas.

[[v5-28-58]]

^<<v5-28-58,58>>^ Se não tiveres cuidado de guardar todas as palavras desta lei, que estão escritas neste livro, para temeres este nome glorioso e temível, o Senhor teu Deus;

[[v5-28-59]]

^<<v5-28-59,59>>^ então o Senhor fará espantosas as tuas pragas, e as pragas da tua descendência, grandes e duradouras pragas, e enfermidades malignas e duradouras;

[[v5-28-60]]

^<<v5-28-60,60>>^ e fará tornar sobre ti todos os males do Egito, de que tiveste temor; e eles se apegarão a ti.

[[v5-28-61]]

^<<v5-28-61,61>>^ Também o Senhor fará vir a ti toda enfermidade, e toda praga que não está escrita no livro desta lei, até que sejas destruído.

[[v5-28-62]]

^<<v5-28-62,62>>^ Assim ficareis poucos em número, depois de haverdes sido em multidão como as estrelas do céu; porquanto não deste ouvidos à voz do Senhor teu Deus.

[[v5-28-63]]

^<<v5-28-63,63>>^ E será que, assim como o Senhor se deleitava em vós, para fazer-vos o bem e multiplicar-vos, assim o Senhor se deleitará em destruir-vos e consumir-vos; e sereis desarraigados da terra na qual estais entrando para a possuirdes.

[[v5-28-64]]

^<<v5-28-64,64>>^ E o Senhor vos espalhará entre todos os povos desde uma extremidade da terra até a outra; e ali servireis a outros deuses que não conhecestes, nem vós nem vossos pais, deuses de pau e de pedra.

[[v5-28-65]]

^<<v5-28-65,65>>^ E nem ainda entre estas nações descansarás, nem a planta de teu pé terá repouso; mas o Senhor ali te dará coração tremente, e desfalecimento de olhos, e desmaio de alma.

[[v5-28-66]]

^<<v5-28-66,66>>^ E a tua vida estará como em suspenso diante de ti; e estremecerás de noite e de dia, e não terás segurança da tua própria vida.

[[v5-28-67]]

^<<v5-28-67,67>>^ Pela manhã dirás: Ah! quem me dera ver a tarde; E à tarde dirás: Ah! quem me dera ver a manhã! pelo pasmo que terás em teu coração, e pelo que verás com os teus olhos.

[[v5-28-68]]

^<<v5-28-68,68>>^ E o Senhor te fará voltar ao Egito em navios, pelo caminho de que te disse: Nunca mais o verás. Ali vos poreis a venda como escravos e escravas aos vossos inimigos, mas não haverá quem vos compre.

'''

xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[&#60; Capítulo Anterior] | <<v5-28-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[Próximo Capítulo &#62;]