include::./index.adoc[]

[[v5-20-0]]
=== Deuteronômio, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-20-1]]

^<<v5-20-1,1>>^ Quando saíres à peleja, contra teus inimigos, e vires cavalos, e carros, e povo mais numeroso do que tu, deles não terás temor, pois contigo está o Senhor teu Deus que te fez subir da terra do Egito.

[[v5-20-2]]

^<<v5-20-2,2>>^ Quando estiveres para entrar na peleja, o sacerdote se chegará e falará ao povo,

[[v5-20-3]]

^<<v5-20-3,3>>^ e lhe dirá: Ouvi, é Israel; vós estais hoje para entrar na peleja contra os vossos inimigos; não se amoleça o vosso coração; não temais nem tremais, nem vos aterrorizeis diante deles;

[[v5-20-4]]

^<<v5-20-4,4>>^ pois e Senhor vosso Deus é o que vai convosco, a pelejar por vós contra os vossos inimigos, para vos salvar.

[[v5-20-5]]

^<<v5-20-5,5>>^ Então os oficiais falarão ao povo, dizendo: Qual é o homem que edificou casa nova e ainda não a dedicou? vá, e torne para casa; não suceda que morra na peleja e outro a dedique.

[[v5-20-6]]

^<<v5-20-6,6>>^ E qual é o homem que plantou uma vinha e ainda não a desfrutou, vá, e torne para casa; não suceda que morra na peleja e outro a desfrute.

[[v5-20-7]]

^<<v5-20-7,7>>^ Também qual é e homem que está desposado com uma mulher e ainda não a recebeu? vá, e torne para casa; não suceda que morra na peleja e outro a receba.

[[v5-20-8]]

^<<v5-20-8,8>>^ Assim continuarão os oficiais a falar ao povo, dizendo: Qual é o homem medroso e de coração tímido? vá, e torne para casa, a fim de que o coração de seus irmãos não se derreta como o seu coração.

[[v5-20-9]]

^<<v5-20-9,9>>^ Então, tendo os oficiais, acabado de falar ao povo, designarão chefes das tropas para estarem à frente do povo.

[[v5-20-10]]

^<<v5-20-10,10>>^ Quando te aproximares duma cidade para combatê-la, apregoar-lhe-ás paz.

[[v5-20-11]]

^<<v5-20-11,11>>^ Se ela te responder em paz, e te abrir as portas, todo o povo que se achar nela será sujeito a trabalhos forçados e te servirá.

[[v5-20-12]]

^<<v5-20-12,12>>^ Se ela, pelo contrário, não fizer paz contigo, mas guerra, então a sitiarás,

[[v5-20-13]]

^<<v5-20-13,13>>^ e logo que o Senhor teu Deus a entregar nas tuas mãos, passarás ao fio da espada todos os homens que nela houver;

[[v5-20-14]]

^<<v5-20-14,14>>^ porém as mulheres, os pequeninos, os animais e tudo o que houver na cidade, todo o seu despojo, tomarás por presa; e comerás o despojo dos teus inimigos, que o Senhor teu Deus te deu.

[[v5-20-15]]

^<<v5-20-15,15>>^ Assim farás a todas as cidades que estiverem mais longe de ti, que não são das cidades destas nações.

[[v5-20-16]]

^<<v5-20-16,16>>^ Mas, das cidades destes povos, que o Senhor teu Deus te dá em herança, nada que tem fôlego deixarás com vida;

[[v5-20-17]]

^<<v5-20-17,17>>^ antes destruí-los-ás totalmente: aos heteus, aos amorreus, aos cananeus, aos perizeus, aos heveus, e aos jebuseus; como Senhor teu Deus te ordenou;

[[v5-20-18]]

^<<v5-20-18,18>>^ para que não vos ensinem a fazer conforme todas as abominações que eles fazem a seus deuses, e assim pequeis contra o Senhor vosso Deus.

[[v5-20-19]]

^<<v5-20-19,19>>^ Quando sitiares uma cidade por muitos dias, pelejando contra ela para a tomar, não destruirás o seu arvoredo, metendo nele o machado, porque dele poderás comer; pelo que não o cortarás; porventura a árvore do campo é homem, para que seja sitiada por ti?

[[v5-20-20]]

^<<v5-20-20,20>>^ Somente as árvores que souberes não serem árvores cujo fruto se pode comer, é que destruirás e cortarás, e contra a cidade que guerrear contra ti edificarás baluartes, até que seja vencida.

'''

xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[&#60; Capítulo Anterior] | <<v5-20-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[Próximo Capítulo &#62;]