include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-8-1]]

^<<v5-8-1,1>>^ Todos os mandamentos que hoje eu vos ordeno cuidareis de observar, para que vivais, e vos multipliqueis, e entreis, e possuais a terra que o Senhor, com juramento, prometeu a vossos pais.

[[v5-8-2]]

^<<v5-8-2,2>>^ E te lembrarás de todo o caminho pelo qual o Senhor teu Deus tem te conduzido durante estes quarenta anos no deserto, a fim de te humilhar e te provar, para saber o que estava no teu coração, se guardarias ou não os seus mandamentos.

[[v5-8-3]]

^<<v5-8-3,3>>^ Sim, ele te humilhou, e te deixou ter fome, e te sustentou com o maná, que nem tu nem teus pais conhecíeis; para te dar a entender que o homem não vive só de pão, mas de tudo o que sai da boca do Senhor, disso vive o homem.

[[v5-8-4]]

^<<v5-8-4,4>>^ Não se envelheceram as tuas vestes sobre ti, nem se inchou o teu pé, nestes quarenta anos.

[[v5-8-5]]

^<<v5-8-5,5>>^ Saberás, pois, no teu coração que, como um homem corrige a seu filho, assim te corrige o Senhor teu Deus.

[[v5-8-6]]

^<<v5-8-6,6>>^ E guardarás os mandamentos de Senhor teu Deus, para andares nos seus caminhos, e para o temeres.

[[v5-8-7]]

^<<v5-8-7,7>>^ Porque o Senhor teu Deus te está introduzindo numa boa terra, terra de ribeiros de águas, de fontes e de nascentes, que brotam nos vales e nos outeiros;

[[v5-8-8]]

^<<v5-8-8,8>>^ terra de trigo e cevada; de vides, figueiras e romeiras; terra de oliveiras, de azeite e de mel;

[[v5-8-9]]

^<<v5-8-9,9>>^ terra em que comerás o pão sem escassez, e onde não te faltará coisa alguma; terra cujas pedras são ferro, e de cujos montes poderás cavar o cobre.

[[v5-8-10]]

^<<v5-8-10,10>>^ Comerás, pois, e te fartarás, e louvarás ao Senhor teu Deus pela boa terra que te deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ Guarda-te, que não te esqueças do Senhor teu Deus, deixando de observar os seus mandamentos, os seus preceitos e os seus estatutos, que eu hoje te ordeno;

[[v5-8-12]]

^<<v5-8-12,12>>^ para não suceder que, depois de teres comido e estares farto, depois de teres edificado boas casas e estares morando nelas,

[[v5-8-13]]

^<<v5-8-13,13>>^ depois de se multiplicarem as tuas manadas e es teus rebanhos, a tua prata e o teu ouro, sim, depois de se multiplicar tudo quanto tens,

[[v5-8-14]]

^<<v5-8-14,14>>^ se exalte e teu coração e te esqueças do Senhor teu Deus, que te tirou da terra o Egito, da casa da servidão;

[[v5-8-15]]

^<<v5-8-15,15>>^ que te conduziu por aquele grande e terrível deserto de serpentes abrasadoras e de escorpiões, e de terra árida em que não havia água, e onde te fez sair água da rocha pederneira;

[[v5-8-16]]

^<<v5-8-16,16>>^ que no deserto te alimentou com o maná, que teus pais não conheciam; a fim de te humilhar e te provar, para nos teus últimos dias te fazer bem;

[[v5-8-17]]

^<<v5-8-17,17>>^ e digas no teu coração: A minha força, e a fortaleza da minha mão me adquiriram estas riquezas.

[[v5-8-18]]

^<<v5-8-18,18>>^ Antes te lembrarás do Senhor teu Deus, porque ele é o que te dá força para adquirires riquezas; a fim de confirmar o seu pacto, que jurou a teus pais, como hoje se vê.

[[v5-8-19]]

^<<v5-8-19,19>>^ Sucederá, porém, que, se de qualquer maneira te esqueceres de Senhor teu Deus, e se seguires após outros deuses, e os servires, e te encurvares perante eles, testifico hoje contra ti que certamente perecerás.

[[v5-8-20]]

^<<v5-8-20,20>>^ Como as nações que o Senhor vem destruindo diante de vós, assim vós perecereis, por não quererdes ouvir a voz do Senhor vosso Deus.

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]