include::./index.adoc[]

[[v5-26-0]]
=== Deuteronômio, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-26-1]]

^<<v5-26-1,1>>^ Também, quando tiveres entrado na terra que o Senhor teu Deus te dá por herança, e a possuíres, e nela habitares,

[[v5-26-2]]

^<<v5-26-2,2>>^ tomarás das primícias de todos os frutos do solo que trouxeres da terra que o senhor teu Deus te dá, e as porás num cesto, e irás ao lugar que o Senhor teu Deus escolher para ali fazer habitar o seu nome.

[[v5-26-3]]

^<<v5-26-3,3>>^ E irás ao sacerdote que naqueles dias estiver de serviço, e lhe dirás: Hoje declaro ao Senhor teu Deus que entrei na terra que o senhor com juramento prometeu a nossos pais que nos daria.

[[v5-26-4]]

^<<v5-26-4,4>>^ O sacerdote, pois, tomará o cesto da tua mão, e o porá diante do altar do Senhor teu Deus.

[[v5-26-5]]

^<<v5-26-5,5>>^ E perante o Senhor teu Deus dirás: Arameu prestes a perecer era meu pai; e desceu ao Egito com pouca gente, para ali morar; e veio a ser ali uma nação grande, forte e numerosa.

[[v5-26-6]]

^<<v5-26-6,6>>^ Mas os egípcios nos maltrataram e nos afligiram, e nos impuseram uma dura servidão.

[[v5-26-7]]

^<<v5-26-7,7>>^ Então clamamos ao Senhor Deus de nossos pais, e o Senhor ouviu a nossa voz, e atentou para a nossa aflição, o nosso trabalho, e a nossa opressão;

[[v5-26-8]]

^<<v5-26-8,8>>^ e o Senhor nos tirou do Egito com mão forte e braço estendido, com grande espanto, e com sinais e maravilhas;

[[v5-26-9]]

^<<v5-26-9,9>>^ e nos trouxe a este lugar, e nos deu esta terra, terra que mana leite e mel.

[[v5-26-10]]

^<<v5-26-10,10>>^ E eis que agora te trago as primícias dos frutos da terra que tu, ó Senhor, me deste. Então as porás perante o Senhor teu Deus, e o adorarás;

[[v5-26-11]]

^<<v5-26-11,11>>^ e te alegrarás por todo o bem que o Senhor teu Deus te tem dado a ti e à tua casa, tu e o levita, e o estrangeiro que está no meio de ti.

[[v5-26-12]]

^<<v5-26-12,12>>^ Quando acabares de separar todos os dízimos da tua colheita do terceiro ano, que é o ano dos dízimos, dá-los-ás ao levita, ao estrangeiro, ao órfão e à viúva, para que comam dentro das tuas portas, e se fartem.

[[v5-26-13]]

^<<v5-26-13,13>>^ E dirás perante o Senhor teu Deus: Tirei da minha casa as coisas consagradas, e as dei ao levita, ao estrangeiro, ao órfão e à viúva, conforme todos os teus mandamentos que me tens ordenado; não transgredi nenhum dos teus mandamentos, nem deles me esqueci.

[[v5-26-14]]

^<<v5-26-14,14>>^ Delas não comi no meu luto, nem delas tirei coisa alguma estando eu imundo, nem delas dei para algum morto; ouvi a voz do senhor meu Deus; conforme tudo o que me ordenaste, tenho feito.

[[v5-26-15]]

^<<v5-26-15,15>>^ Olha desde a tua santa habitação, desde o céu, e abençoa o teu povo de Israel, e a terra que nos deste, como juraste a nossos pais, terra que mana leite e mel.

[[v5-26-16]]

^<<v5-26-16,16>>^ Neste dia o Senhor teu Deus te manda observar estes estatutos e preceitos; portanto os guardarás e os observarás com todo o teu coração e com toda a tua alma.

[[v5-26-17]]

^<<v5-26-17,17>>^ Hoje declaraste ao Senhor que ele te será por Deus, e que andarás nos seus caminhos, e guardarás os seus estatutos, os seus mandamentos e os seus preceitos, e darás ouvidos à sua voz.

[[v5-26-18]]

^<<v5-26-18,18>>^ Outrossim, o Senhor hoje te declarou que lhe serás por seu próprio povo, como te tem dito, e que deverás guardar todos os seus mandamentos;

[[v5-26-19]]

^<<v5-26-19,19>>^ para assim te exaltar em honra, em fama e em glória sobre todas as nações que criou; e para que sejas um povo santo ao Senhor teu Deus, como ele disse.

'''

xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[&#60; Capítulo Anterior] | <<v5-26-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[Próximo Capítulo &#62;]