include::./index.adoc[]

[[v5-24-0]]
=== Deuteronômio, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-24-1]]

^<<v5-24-1,1>>^ Quando um homem tomar uma mulher e se casar com ela, se ela não achar graça aos seus olhos, por haver ele encontrado nela coisa vergonhosa, far-lhe-á uma carta de divórcio e lha dará na mão, e a despedirá de sua casa.

[[v5-24-2]]

^<<v5-24-2,2>>^ Se ela, pois, saindo da casa dele, for e se casar com outro homem,

[[v5-24-3]]

^<<v5-24-3,3>>^ e este também a desprezar e, fazendo-lhe carta de divórcio, lha der na mão, e a despedir de sua casa; ou se este último homem, que a tomou para si por mulher, vier a morrer;

[[v5-24-4]]

^<<v5-24-4,4>>^ então seu primeiro marido que a despedira, não poderá tornar a tomá-la por mulher, depois que foi contaminada; pois isso é abominação perante o Senhor. Não farás pecar a terra que o Senhor teu Deus te dá por herança.

[[v5-24-5]]

^<<v5-24-5,5>>^ Quando um homem for recém-casado não sairá à guerra, nem se lhe imporá cargo público; por um ano inteiro ficará livre na sua casa, para se regozijar com a sua mulher, que tomou.

[[v5-24-6]]

^<<v5-24-6,6>>^ Ninguém tomará em penhor as duas mós, nem mesmo a mó de cima, pois se penhoraria assim a vida.

[[v5-24-7]]

^<<v5-24-7,7>>^ Se for descoberto alguém que, havendo furtado um dentre os seus irmãos, dos filhos de Israel, e tenha escravizado, ou vendido, esse ladrão morrerá. Assim exterminarás o mal do meio de ti.

[[v5-24-8]]

^<<v5-24-8,8>>^ No tocante à praga da lepra, toma cuidado de observar diligentemente tudo o que te ensinarem os levitas sacerdotes; segundo lhes tenho ordenado, assim cuidarás de fazer.

[[v5-24-9]]

^<<v5-24-9,9>>^ Lembra-te do que o Senhor teu Deus fez a Miriã no caminho, quando saíste do Egito.

[[v5-24-10]]

^<<v5-24-10,10>>^ Quando emprestares alguma coisa ao teu próximo, não entrarás em sua casa para lhe tirar o penhor;

[[v5-24-11]]

^<<v5-24-11,11>>^ ficarás do lado de fora, e o homem, a quem fizeste o empréstimo, te trará para fora o penhor.

[[v5-24-12]]

^<<v5-24-12,12>>^ E se ele for pobre, não te deitarás com o seu penhor;

[[v5-24-13]]

^<<v5-24-13,13>>^ ao pôr do sol, sem falta lhe restituirás o penhor, para que durma na sua roupa, e te abençoe; e isso te será justiça diante do Senhor teu Deus.

[[v5-24-14]]

^<<v5-24-14,14>>^ Não oprimirás o trabalhador pobre e necessitado, seja ele de teus irmãos, ou seja dos estrangeiros que estão na tua terra e dentro das tuas portas.

[[v5-24-15]]

^<<v5-24-15,15>>^ No mesmo dia lhe pagarás o seu salário, e isso antes que o sol se ponha; porquanto é pobre e está contando com isso; para que não clame contra ti ao Senhor, e haja em ti pecado.

[[v5-24-16]]

^<<v5-24-16,16>>^ Não se farão morrer os pais pelos filhos, nem os filhos pelos pais; cada qual morrerá pelo seu próprio pecado.

[[v5-24-17]]

^<<v5-24-17,17>>^ Não perverterás o direito do estrangeiro nem do órfão; nem tomarás em penhor o vestido da viúva.

[[v5-24-18]]

^<<v5-24-18,18>>^ Lembrar-te-ás de que foste escravo no Egito, e de que o Senhor teu Deus te resgatou dali; por isso eu te dou este mandamento para o cumprires.

[[v5-24-19]]

^<<v5-24-19,19>>^ Quando no teu campo fizeres a tua sega e esqueceres um molho no campo, não voltarás para tomá-lo; para o estrangeiro para o órfão, e para a viúva será, para que o Senhor teu Deus te abençoe em todas as obras das tuas mãos.

[[v5-24-20]]

^<<v5-24-20,20>>^ Quando bateres a tua oliveira, não voltarás para colher o fruto dos ramos; para o estrangeiro, para o órfão, e para a viúva será.

[[v5-24-21]]

^<<v5-24-21,21>>^ Quando vindimares a tua vinha, não voltarás para rebuscá-la; para o estrangeiro, para o órfão, e para a viúva será.

[[v5-24-22]]

^<<v5-24-22,22>>^ E lembrar-te-ás de que foste escravo na terra do Egito; por isso eu te dou este mandamento para o cumprires.

'''

xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[&#60; Capítulo Anterior] | <<v5-24-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[Próximo Capítulo &#62;]