include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-22-1]]

^<<v5-22-1,1>>^ Se vires extraviado o boi ou a ovelha de teu irmão, não te desviarás deles; sem falta os reconduzirás a teu irmão.

[[v5-22-2]]

^<<v5-22-2,2>>^ E se teu irmão não estiver perto de ti ou não o conheceres, levá-los-ás para tua casa e ficarão contigo até que teu irmão os venha procurar; então lhes restituirás.

[[v5-22-3]]

^<<v5-22-3,3>>^ Assim farás também com o seu jumento, bem como com as suas vestes, e com toda coisa que teu irmão tiver perdido e tu achares; não te poderás desviar deles.

[[v5-22-4]]

^<<v5-22-4,4>>^ Se vires o jumento ou o boi de teu irmão caídos no caminho, não te desviarás deles; sem falta o ajudarás a levantá-los.

[[v5-22-5]]

^<<v5-22-5,5>>^ Não haverá traje de homem na mulher, e não vestirá o homem vestido de mulher, porque qualquer que faz isto é abominação ao Senhor teu Deus.

[[v5-22-6]]

^<<v5-22-6,6>>^ Se encontrares pelo caminho, numa árvore ou no chão, um ninho de ave com passarinhos ou ovos, e a mãe posta sobre os passarinhos, ou sobre os ovos, não temerás a mãe com os filhotes;

[[v5-22-7]]

^<<v5-22-7,7>>^ sem falta deixarás ir a mãe, porém os filhotes poderás tomar; para que te vá bem, e para que prolongues os teus dias.

[[v5-22-8]]

^<<v5-22-8,8>>^ Quando edificares uma casa nova, farás no terraço um parapeito, para que não tragas sangue sobre a tua casa, se alguém dali cair.

[[v5-22-9]]

^<<v5-22-9,9>>^ Não semearás a tua vinha de duas espécies de semente, para que não fique sagrado todo o produto, tanto da semente que semeares como do fruto da vinha.

[[v5-22-10]]

^<<v5-22-10,10>>^ Não lavrarás com boi e jumento juntamente.

[[v5-22-11]]

^<<v5-22-11,11>>^ Não te vestirás de estofo misturado, de lã e linho juntamente.

[[v5-22-12]]

^<<v5-22-12,12>>^ Porás franjas nos quatro cantos da tua manta, com que te cobrires.

[[v5-22-13]]

^<<v5-22-13,13>>^ Se um homem tomar uma mulher por esposa, e, tendo coabitado com ela, vier a desprezá-la,

[[v5-22-14]]

^<<v5-22-14,14>>^ e lhe atribuir coisas escandalosas, e contra ela divulgar má fama, dizendo: Tomei esta mulher e, quando me cheguei a ela, não achei nela os sinais da virgindade;

[[v5-22-15]]

^<<v5-22-15,15>>^ então o pai e a mãe da moça tomarão os sinais da virgindade da moça, e os levarão aos anciãos da cidade, à porta;

[[v5-22-16]]

^<<v5-22-16,16>>^ e o pai da moça dirá aos anciãos: Eu dei minha filha por mulher a este homem, e agora ele a despreza,

[[v5-22-17]]

^<<v5-22-17,17>>^ e eis que lhe atribuiu coisas escandalosas, dizendo: Não achei na tua filha os sinais da virgindade; porém eis aqui os sinais da virgindade de minha filha. E eles estenderão a roupa diante dos anciãos da cidade.

[[v5-22-18]]

^<<v5-22-18,18>>^ Então os anciãos daquela cidade, tomando o homem, o castigarão,

[[v5-22-19]]

^<<v5-22-19,19>>^ e, multando-o em cem siclos de prata, os darão ao pai da moça, porquanto divulgou má fama sobre uma virgem de Israel. Ela ficará sendo sua mulher, e ele por todos os seus dias não poderá repudiá-la.

[[v5-22-20]]

^<<v5-22-20,20>>^ Se, porém, esta acusação for confirmada, não se achando na moça os sinais da virgindade,

[[v5-22-21]]

^<<v5-22-21,21>>^ levarão a moça à porta da casa de seu pai, e os homens da sua cidade a apedrejarão até que morra; porque fez loucura em Israel, prostituindo-se na casa de seu pai. Assim exterminarás o mal do meio de ti.

[[v5-22-22]]

^<<v5-22-22,22>>^ Se um homem for encontrado deitado com mulher que tenha marido, morrerão ambos, o homem que se tiver deitado com a mulher, e a mulher. Assim exterminarás o mal de Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ Se houver moça virgem desposada e um homem a achar na cidade, e se deitar com ela,

[[v5-22-24]]

^<<v5-22-24,24>>^ trareis ambos à porta daquela cidade, e os apedrejareis até que morram: a moça, porquanto não gritou na cidade, e o homem, porquanto humilhou a mulher do seu próximo. Assim exterminarás o mal do meio de ti.

[[v5-22-25]]

^<<v5-22-25,25>>^ Mas se for no campo que o homem achar a moça que é desposada, e o homem a forçar, e se deitar com ela, morrerá somente o homem que se deitou com ela;

[[v5-22-26]]

^<<v5-22-26,26>>^ porém, à moça não farás nada. Não há na moça pecado digno de morte; porque, como no caso de um homem que se levanta contra o seu próximo e lhe tira a vida, assim é este caso;

[[v5-22-27]]

^<<v5-22-27,27>>^ pois ele a achou no campo; a moça desposada gritou, mas não houve quem a livrasse. em juízo, entre sangue

[[v5-22-28]]

^<<v5-22-28,28>>^ Se um homem achar uma moça virgem não desposada e, pegando nela, deitar-se com ela, e forem apanhados,

[[v5-22-29]]

^<<v5-22-29,29>>^ o homem que se deitou com a moça dará ao pai dela cinqüenta siclos de prata, e porquanto a humilhou, ela ficará sendo sua mulher; não a poderá repudiar por todos os seus dias.

[[v5-22-30]]

^<<v5-22-30,30>>^ Nenhum homem tomará a mulher de seu pai, e não levantará a cobertura de seu pai.

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]