include::./index.adoc[]

[[v5-23-0]]
=== Deuteronômio, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-23-1]]

^<<v5-23-1,1>>^ Aquele a quem forem trilhados os testículos, ou for cortado o membro viril, não entrará na assembléia do Senhor.

[[v5-23-2]]

^<<v5-23-2,2>>^ Nenhum bastardo entrará na assembléia do Senhor; nem ainda a sua décima geração entrará na assembléia do Senhor.

[[v5-23-3]]

^<<v5-23-3,3>>^ Nenhum amonita nem moabita entrará na assembléia do Senhor; nem ainda a sua décima geração entrará jamais na assembléia do Senhor;

[[v5-23-4]]

^<<v5-23-4,4>>^ porquanto não saíram com pão e água a receber-vos no caminho, quando saíeis do Egito; e, porquanto alugaram contra ti a Balaão, filho de Beor, de Petor, da Mesopotâmia, para te amaldiçoar.

[[v5-23-5]]

^<<v5-23-5,5>>^ Contudo o Senhor teu Deus não quis ouvir a Balaão, antes trocou-te a maldição em bênção; porquanto o Senhor teu Deus te amava.

[[v5-23-6]]

^<<v5-23-6,6>>^ Não lhes procurarás nem paz nem prosperidade por todos os teus dias para sempre.

[[v5-23-7]]

^<<v5-23-7,7>>^ Não abominarás o edomeu, pois é teu irmão; nem abominarás o egípcio, pois peregrino foste na sua terra.

[[v5-23-8]]

^<<v5-23-8,8>>^ Os filhos que lhes nascerem na terceira geração entrarão na assembléia do Senhor.

[[v5-23-9]]

^<<v5-23-9,9>>^ Quando te acampares contra os teus inimigos, então te guardarás de toda coisa má.

[[v5-23-10]]

^<<v5-23-10,10>>^ Se houver no meio de ti alguém que por algum acidente noturno não estiver limpo, sairá fora do arraial; não entrará no meio dele.

[[v5-23-11]]

^<<v5-23-11,11>>^ Porém, ao cair da tarde, ele se lavará em água; e depois do sol posto, entrará no meio do arraial.

[[v5-23-12]]

^<<v5-23-12,12>>^ Também terás um lugar fora do arraial, para onde sairás.

[[v5-23-13]]

^<<v5-23-13,13>>^ Entre os teus utensílios terás uma pá; e quando te assentares lá fora, então com ela cavarás e, virando-te, cobrirás o teu excremento;

[[v5-23-14]]

^<<v5-23-14,14>>^ porquanto o Senhor teu Deus anda no meio do teu arraial, para te livrar, e para te entregar a ti os teus inimigos; pelo que o teu arraial será santo, para que ele não veja coisa impura em ti, e de ti se aparte.

[[v5-23-15]]

^<<v5-23-15,15>>^ Não entregarás a seu senhor o servo que, fugindo dele, se tiver acolhido a ti;

[[v5-23-16]]

^<<v5-23-16,16>>^ contigo ficará, no meio de ti, no lugar que escolher em alguma das tuas cidades, onde lhe agradar; não o oprimirás.

[[v5-23-17]]

^<<v5-23-17,17>>^ Não haverá dentre as filhas de Israel quem se prostitua no serviço do templo, nem dentre os filhos de Israel haverá quem o faça;

[[v5-23-18]]

^<<v5-23-18,18>>^ não trarás o salário da prostituta nem o aluguel do sodomita para a casa do Senhor teu Deus por qualquer voto, porque uma e outra coisa são igualmente abomináveis ao Senhor teu Deus.

[[v5-23-19]]

^<<v5-23-19,19>>^ Do teu irmão não exigirás juros; nem de dinheiro, nem de comida, nem de qualquer outra coisa que se empresta a juros.

[[v5-23-20]]

^<<v5-23-20,20>>^ Do estrangeiro poderás exigir juros; porém do teu irmão não os exigirás, para que o Senhor teu Deus te abençoe em tudo a que puseres a mão, na terra à qual vais para a possuíres.

[[v5-23-21]]

^<<v5-23-21,21>>^ Quando fizeres algum voto ao Senhor teu Deus, não tardarás em cumpri-lo; porque o Senhor teu Deus certamente o requererá de ti, e em ti haverá pecado.

[[v5-23-22]]

^<<v5-23-22,22>>^ Se, porém, te abstiveres de fazer voto, não haverá pecado em ti.

[[v5-23-23]]

^<<v5-23-23,23>>^ O que tiver saído dos teus lábios guardarás e cumprirás, tal como voluntariamente o votaste ao Senhor teu Deus, prometendo-o pela tua boca.

[[v5-23-24]]

^<<v5-23-24,24>>^ Quando entrares na vinha do teu próximo, poderás comer uvas conforme o teu desejo, até te fartares, porém não as porás no teu alforje.

[[v5-23-25]]

^<<v5-23-25,25>>^ Quando entrares na seara do teu próximo, poderás colher espigas com a mão, porém não meterás a foice na seara do teu próximo.

'''

xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[&#60; Capítulo Anterior] | <<v5-23-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-024.adoc#v5-24-0[Próximo Capítulo &#62;]