include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-13-1]]

^<<v5-13-1,1>>^ Se levantar no meio de vós profeta, ou sonhador de sonhos, e vos anunciar um sinal ou prodígio,

[[v5-13-2]]

^<<v5-13-2,2>>^ e suceder o sinal ou prodígio de que vos houver falado, e ele disser: Vamos após outros deuses que nunca conhecestes, e sirvamo-los,

[[v5-13-3]]

^<<v5-13-3,3>>^ não ouvireis as palavras daquele profeta, ou daquele sonhador; porquanto o Senhor vosso Deus vos está provando, para saber se amais o Senhor vosso Deus de todo o vosso coração e de toda a vossa alma.

[[v5-13-4]]

^<<v5-13-4,4>>^ Após o Senhor vosso Deus andareis, e a ele temereis; os seus mandamentos guardareis, e a sua voz ouvireis; a ele servireis, e a ele vos apegareis.

[[v5-13-5]]

^<<v5-13-5,5>>^ E aquele profeta, ou aquele sonhador, morrerá, pois falou rebeldia contra o Senhor vosso Deus, que vos tirou da terra do Egito e vos resgatou da casa da servidão, para vos desviar do caminho em que o Senhor vosso Deus vos ordenou que andásseis; assim exterminareis o mal do meio vós.

[[v5-13-6]]

^<<v5-13-6,6>>^ Quando teu irmão, filho da tua mãe, ou teu filho, ou tua filha, ou a mulher do teu seio, ou teu amigo que te é como a tua alma, te incitar em segredo, dizendo: Vamos e sirvamos a outros deuses!-deuses que nunca conheceste, nem tu nem teus pais,

[[v5-13-7]]

^<<v5-13-7,7>>^ dentre os deuses dos povos que estão em redor de ti, perto ou longe de ti, desde uma extremidade da terra até a outra-

[[v5-13-8]]

^<<v5-13-8,8>>^ não consentirás com ele, nem o ouvirás, nem o teu olho terá piedade dele, nem o pouparás, nem o esconderás,

[[v5-13-9]]

^<<v5-13-9,9>>^ mas certamente o matarás; a tua mão será a primeira contra ele para o matar, e depois a mão de todo o povo;

[[v5-13-10]]

^<<v5-13-10,10>>^ e o apedrejarás, até que morra, pois procurou apartar-te do Senhor teu Deus, que te tirou da terra do Egito, da casa da servidão.

[[v5-13-11]]

^<<v5-13-11,11>>^ Todo o Israel o ouvirá, e temerá, e não se tornará a praticar semelhante iniqüidade no meio de ti.

[[v5-13-12]]

^<<v5-13-12,12>>^ Se, a respeito de alguma das tuas cidades que o Senhor teu Deus te dá para ali habitares, ouvires dizer:

[[v5-13-13]]

^<<v5-13-13,13>>^ Uns homens, filhos de Belial, saindo do meio de ti, incitaram os moradores da sua cidade, dizendo: Vamos, e sirvamos a outros deuses!-deuses que nunca conheceste-

[[v5-13-14]]

^<<v5-13-14,14>>^ então inquirirás e investigarás, perguntando com diligência; e se for verdade, se for certo que se fez tal abominação no meio de ti,

[[v5-13-15]]

^<<v5-13-15,15>>^ certamente ferirás ao fio da espada os moradores daquela cidade, destruindo a ela e a tudo o que nela houver, até os animais.

[[v5-13-16]]

^<<v5-13-16,16>>^ E ajuntarás todo o seu despojo no meio da sua praça; e a cidade e todo o seu despojo queimarás totalmente para o Senhor teu Deus, e será montão perpétuo; nunca mais será edificada.

[[v5-13-17]]

^<<v5-13-17,17>>^ Não se te pegará às mãos nada do anátema; para que o Senhor se aparte do ardor da sua ira, e te faça misericórdia, e tenha piedade de ti, e te multiplique; como jurou a teus pais,

[[v5-13-18]]

^<<v5-13-18,18>>^ se ouvires a voz do Senhor teu Deus, para guardares todos os seus mandamentos, que eu hoje te ordeno, para fazeres o que é reto aos olhos do Senhor teu Deus.

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]