include::./index.adoc[]

[[v5-3-0]]
=== Deuteronômio, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-3-1]]

^<<v5-3-1,1>>^ Depois nos viramos e subimos pelo caminho de Basã; e Ogue, rei de Basã, nos saiu ao encontro, ele e todo o seu povo, à peleja, em Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ Então o Senhor me disse: Não o temas, porque to entreguei nas mãos, a ele e a todo o seu povo, e a sua terra; e farás a ele como fizeste a Siom, rei dos amorreus, que habitava em Hesbom.

[[v5-3-3]]

^<<v5-3-3,3>>^ Assim o Senhor nosso Deus nos entregou nas mãos também a Ogue, rei de Basã, e a todo o seu povo; de maneira que o ferimos, até que não lhe ficou sobrevivente algum.

[[v5-3-4]]

^<<v5-3-4,4>>^ E naquele tempo tomamos todas as suas cidades; nenhuma cidade houve que não lhes tomássemos: sessenta cidades, toda a região de Argobe, o reino de Ogue em Basã,

[[v5-3-5]]

^<<v5-3-5,5>>^ cidades estas todas fortificadas com altos muros, portas e ferrolhos, além de muitas cidades sem muros.

[[v5-3-6]]

^<<v5-3-6,6>>^ E destruímo-las totalmente, como fizéramos a Siom, rei de Hesbom, fazendo perecer a todos, homens, mulheres e pequeninos.

[[v5-3-7]]

^<<v5-3-7,7>>^ Mas todo o gado e o despojo das cidades, tomamo-los por presa para nós.

[[v5-3-8]]

^<<v5-3-8,8>>^ Assim naquele tempo tomamos a terra da mão daqueles dois reis dos amorreus, que estavam além do Jordão, desde o rio Arnom até o monte Hermom

[[v5-3-9]]

^<<v5-3-9,9>>^ &#123;ao Hermom os sidônios chamam Siriom, e os amorreus chamam-lhe Senir&#125; ,

[[v5-3-10]]

^<<v5-3-10,10>>^ todas as cidades do planalto, e todo o Gileade, e todo o Basã, até Salca e Edrei, cidades do reino de Ogue em Basã.

[[v5-3-11]]

^<<v5-3-11,11>>^ Porque só Ogue, rei de Basã, ficou de resto dos refains; eis que o seu leito, um leito de ferro, não está porventura em Rabá dos amonitas? o seu comprimento é de nove côvados, e de quatro côvados a sua largura, segundo o côvado em uso.

[[v5-3-12]]

^<<v5-3-12,12>>^ Naquele tempo, pois, tomamos essa terra por possessão. Desde Aroer, que está junto do vale do Arnom, e a metade da região montanhosa de Gileade, com as suas cidades, dei aos nibenitas e gaditas;

[[v5-3-13]]

^<<v5-3-13,13>>^ e dei à meia tribo de Manassés o resto de Gileade, como também todo o Basã, o reino de Ogue, isto é, toda a região de Argobe com todo o Basã. &#123;O mesmo se chamava a terra dos refains.

[[v5-3-14]]

^<<v5-3-14,14>>^ Jair, filho de Manassés, tomou toda a região de Argobe, até a fronteira dos resuritas e dos maacatitas, e lhes chamou, inclusive o Basã, pelo seu nome, Havote-Jair, até hoje&#125;.

[[v5-3-15]]

^<<v5-3-15,15>>^ E a Maquir dei Gileade.

[[v5-3-16]]

^<<v5-3-16,16>>^ Mas aos rubenitas e gaditas dei desde Gileade até o vale do Arnom, tanto o meio do vale como a sua borda, e até o ribeiro de Jaboque, o termo dos amonitas;

[[v5-3-17]]

^<<v5-3-17,17>>^ como também a Arabá, com o Jordão por termo, desde Quinerete até o mar da Arabá, o Mar Salgado, pelas faldas de Pisga para o oriente.

[[v5-3-18]]

^<<v5-3-18,18>>^ No mesmo tempo também vos ordenei, dizendo: O Senhor vosso Deus vos deu esta terra, para a possuirdes; vós, todos os homens valentes, passareis armados adiante de vossos irmãos, os filhos de Israel.

[[v5-3-19]]

^<<v5-3-19,19>>^ Tão-somente vossas mulheres, e vossos pequeninos, e vosso gado &#123;porque eu sei que tendes muito gado&#125; ficarão nas cidades que já vos dei;

[[v5-3-20]]

^<<v5-3-20,20>>^ até que o Senhor dê descanso a vossos irmãos como a vós, e eles também possuam a terra que o Senhor vosso Deus lhes dá além do Jordão: Então voltareis cada qual à sua herança que já vos tenho dado.

[[v5-3-21]]

^<<v5-3-21,21>>^ Também dei ordem a Josué no mesmo tempo, dizendo: Os teus olhos viram tudo o que o Senhor vosso Deus tem feito a esses dois reis; assim fará o Senhor a todos os reinos a que tu estás passando.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não tenhais medo deles, porque o Senhor vosso Deus é o que peleja por nós.

[[v5-3-23]]

^<<v5-3-23,23>>^ Também roguei ao Senhor nesse tempo, dizendo:

[[v5-3-24]]

^<<v5-3-24,24>>^ Ó Senhor Jeová, tu já começaste a mostrar ao teu servo a tua grandeza e a tua forte mão; pois, que Deus há no céu ou na terra, que possa fazer segundo as tuas obras, e segundo os teus grandes feitos?

[[v5-3-25]]

^<<v5-3-25,25>>^ Rogo-te que me deixes passar, para que veja essa boa terra que está além do Jordão, essa boa região montanhosa, e o Líbano!

[[v5-3-26]]

^<<v5-3-26,26>>^ Mas o Senhor indignou-se muito contra mim por causa de vós, e não me ouviu; antes me disse: Basta; não me fales mais nisto.

[[v5-3-27]]

^<<v5-3-27,27>>^ sobe ao cume do Pisga, e levanta os olhos para o ocidente, para o norte, para o sul e para o oriente, e contempla com os teus olhos; porque não passarás este Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ Mas dá ordens a Josué, anima-o, e fortalece-o, porque ele passará adiante deste povo, e o levará a possuir a terra que tu verás.

[[v5-3-29]]

^<<v5-3-29,29>>^ Assim ficamos no vale defronte de Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]