include::./index.adoc[]

[[v5-19-0]]
=== Deuteronômio, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-19-1]]

^<<v5-19-1,1>>^ Quando o Senhor teu Deus desarraigar as nações cuja terra ele te dá, e tu as desapossares, e morares nas suas cidades e nas suas casas,

[[v5-19-2]]

^<<v5-19-2,2>>^ designarás para ti no meio da terra que o Senhor teu Deus te dá para a possuíres, três cidades;

[[v5-19-3]]

^<<v5-19-3,3>>^ preparar-lhe-ás caminhos, e partirás em três os termos da tua terra, que o Senhor teu Deus te dará em herança; isto será para que todo homicida se acolha nessas cidades.

[[v5-19-4]]

^<<v5-19-4,4>>^ Este, pois é o caso no tocante ao homicida que se acolher ali para que viva: aquele que involuntariamente matar o seu próximo, a quem dantes não odiava;

[[v5-19-5]]

^<<v5-19-5,5>>^ como, por exemplo, aquele que entrar com o seu próximo no bosque para cortar lenha e, pondo força na sua mão com o machado para cortar a árvore, o ferro saltar do cabo e ferir o seu próximo de sorte que venha a morrer; o tal se acolherá a uma dessas cidades, e viverá;

[[v5-19-6]]

^<<v5-19-6,6>>^ para que o vingador do sangue não persiga o homicida, enquanto estiver abrasado o seu coração, e o alcance, por ser comprido o caminho, e lhe tire a vida, não havendo nele culpa de morte, pois que dantes não odiava o seu próximo.

[[v5-19-7]]

^<<v5-19-7,7>>^ Pelo que eu te deu esta ordem: Três cidades designarás para ti.

[[v5-19-8]]

^<<v5-19-8,8>>^ E, se o Senhor teu Deus dilatar os teus termos, como jurou a teus pais, e te der toda a terra que prometeu dar a teus pais

[[v5-19-9]]

^<<v5-19-9,9>>^ &#123;quando guardares, para o cumprires, todo este mandamento que eu hoje te ordeno, de amar o Senhor teu Deus e de andar sempre nos seus caminhos&#125;, então acrescentarás a estas três, mais três cidades;

[[v5-19-10]]

^<<v5-19-10,10>>^ para que não se derrame sangue inocente no meio da tua terra, que o Senhor teu Deus te dá por herança, e não haja sangue sobre ti.

[[v5-19-11]]

^<<v5-19-11,11>>^ Mas se alguém, odiando a seu próximo e lhe armando ciladas, se levantar contra ele e o ferir de modo que venha a morrer, e se acolher a alguma destas cidades,

[[v5-19-12]]

^<<v5-19-12,12>>^ então os anciãos da sua cidade, mandando tirá-lo dali, o entregarão nas mãos do vingador do sangue, para que morra.

[[v5-19-13]]

^<<v5-19-13,13>>^ O teu olho não terá piedade dele; antes tirarás de Israel o sangue inocente, para que te vá bem.

[[v5-19-14]]

^<<v5-19-14,14>>^ Não removerás os marcos do teu próximo, colocados pelos teus antecessores na tua herança que receberás, na terra que o Senhor teu Deus te dá para a possuíres.

[[v5-19-15]]

^<<v5-19-15,15>>^ uma só testemunha não se levantará contra alguém por qualquer iniqüidade, ou por qualquer pecado, seja qual for o pecado cometido; pela boca de duas ou de três testemunhas se estabelecerá o fato.

[[v5-19-16]]

^<<v5-19-16,16>>^ Se uma testemunha iníqua se levantar contra alguém, para o acusar de transgressão,

[[v5-19-17]]

^<<v5-19-17,17>>^ então aqueles dois homens que tiverem a demanda se apresentarão perante o Senhor, diante dos sacerdotes e dos juízes que houver nesses dias.

[[v5-19-18]]

^<<v5-19-18,18>>^ E os juízes inquirirão cuidadosamente; e eis que, sendo a testemunha falsa, e falso o testemunho que deu contra seu irmão,

[[v5-19-19]]

^<<v5-19-19,19>>^ far-lhe-ás como ele cuidava fazer a seu irmão; e assim exterminarás o mal do meio de ti.

[[v5-19-20]]

^<<v5-19-20,20>>^ Os restantes, ouvindo isso, temerão e nunca mais cometerão semelhante mal no meio de ti.

[[v5-19-21]]

^<<v5-19-21,21>>^ O teu olho não terá piedade dele; vida por vida, olho por olho, dente por dente, mão por mão, pé por pé.

'''

xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[&#60; Capítulo Anterior] | <<v5-19-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[Próximo Capítulo &#62;]