include::./index.adoc[]

[[v5-17-0]]
=== Deuteronômio, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-17-1]]

^<<v5-17-1,1>>^ Ao Senhor teu Deus não sacrificarás boi ou ovelha em que haja defeito ou qualquer deformidade; pois isso é abominação ao senhor teu Deus.

[[v5-17-2]]

^<<v5-17-2,2>>^ Se no meio de ti, em alguma das tuas cidades que te dá o Senhor teu Deus, for encontrado algum homem ou mulher que tenha feito o que é mau aos olhos do Senhor teu Deus, transgredindo o seu pacto,

[[v5-17-3]]

^<<v5-17-3,3>>^ que tenha ido e servido a outros deuses, adorando-os, a eles, ou ao sol, ou à lua, ou a qualquer astro do exército do céu &#123;o que não ordenei&#125;,

[[v5-17-4]]

^<<v5-17-4,4>>^ e isso te for denunciado, e o ouvires, então o inquirirás bem; e eis que, sendo realmente verdade que se fez tal abominação em Israel,

[[v5-17-5]]

^<<v5-17-5,5>>^ então levarás às tuas portas o homem, ou a mulher, que tiver cometido esta maldade, e apedrejarás o tal homem, ou mulher, até que morra.

[[v5-17-6]]

^<<v5-17-6,6>>^ Pela boca de duas ou de três testemunhas, será morto o que houver de morrer; pela boca duma só testemunha não morrerá.

[[v5-17-7]]

^<<v5-17-7,7>>^ A mão das testemunhas será a primeira contra ele, para matá-lo, e depois a mão de todo o povo; assim exterminarás o mal do meio de ti.

[[v5-17-8]]

^<<v5-17-8,8>>^ Se alguma causa te for difícil demais em juízo, entre sangue e sangue, entre demanda e demanda, entre ferida e ferida, tornando-se motivo de controvérsia nas tuas portas, então te levantarás e subirás ao lugar que o Senhor teu Deus escolher;

[[v5-17-9]]

^<<v5-17-9,9>>^ virás aos levitas sacerdotes, e ao juiz que houver nesses dias, e inquirirás; e eles te anunciarão a sentença da juízo.

[[v5-17-10]]

^<<v5-17-10,10>>^ Depois cumprirás fielmente a sentença que te anunciarem no lugar que o Senhor escolher; e terás cuidado de fazer conforme tudo o que te ensinarem.

[[v5-17-11]]

^<<v5-17-11,11>>^ Conforme o teor da lei que te ensinarem, e conforme o juízo que pronunciarem, farás da palavra que te disserem não te desviarás, nem para a direita nem para a esquerda.

[[v5-17-12]]

^<<v5-17-12,12>>^ O homem que se houver soberbamente, não dando ouvidos ao sacerdote, que está ali para servir ao Senhor teu Deus, nem ao juiz, esse homem morrerá; assumirá de Israel o mal.

[[v5-17-13]]

^<<v5-17-13,13>>^ E todo o povo, ouvindo isso, temerá e nunca mais se ensoberbecerá.

[[v5-17-14]]

^<<v5-17-14,14>>^ Quando entrares na terra que o Senhor teu Deus te dá, e a possuíres e, nela habitando, disseres: Porei sobre mim um rei, como o fazem todas as nações que estão em redor de mim;

[[v5-17-15]]

^<<v5-17-15,15>>^ porás certamente sobre ti como rei aquele que o Senhor teu Deus escolher. Porás um dentre teus irmãos como rei sobre ti; não poderás pôr sobre ti um estrangeiro, homem que não seja de teus irmãos.

[[v5-17-16]]

^<<v5-17-16,16>>^ Ele, porém, não multiplicará para si cavalos, nem fará voltar o povo ao Egito, para multiplicar cavalos; pois o Senhor vos tem dito: Nunca mais voltareis por este caminho.

[[v5-17-17]]

^<<v5-17-17,17>>^ Tampouco multiplicará para si mulheres, para que o seu coração não se desvie; nem multiplicará muito para si a prata e o ouro.

[[v5-17-18]]

^<<v5-17-18,18>>^ Será também que, quando se assentar sobre o trono do seu reino, escreverá para si, num livro, uma cópia desta lei, do exemplar que está diante dos levitas sacerdotes.

[[v5-17-19]]

^<<v5-17-19,19>>^ E o terá consigo, e nele lerá todos os dias da sua vida, para que aprenda a temer ao Senhor seu Deus, e a guardar todas as palavras desta lei, e estes estatutos, a fim de os cumprir;

[[v5-17-20]]

^<<v5-17-20,20>>^ para que seu coração não se exalte sobre seus irmãos, e não se aparte do mandamento, nem para a direita nem para a esquerda; a fim de que prolongue os seus dias no seu reino, ele e seus filhos, no meio de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[&#60; Capítulo Anterior] | <<v5-17-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[Próximo Capítulo &#62;]