include::./index.adoc[]

[[v5-12-0]]
=== Deuteronômio, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-12-1]]

^<<v5-12-1,1>>^ São estes os estatutos e os preceitos que tereis cuidado em observar na terra que o Senhor Deus de vossos pais vos deu para a possuirdes por todos os dias que viverdes sobre a terra.

[[v5-12-2]]

^<<v5-12-2,2>>^ Certamente destruireis todos os lugares em que as nações que haveis de subjugar serviram aos seus deuses, sobre as altas montanhas, sobre os outeiros, e debaixo de toda árvore frondosa;

[[v5-12-3]]

^<<v5-12-3,3>>^ e derrubareis os seus altares, quebrareis as suas colunas, queimareis a fogo os seus aserins, abatereis as imagens esculpidas dos seus deuses e apagareis o seu nome daquele lugar.

[[v5-12-4]]

^<<v5-12-4,4>>^ Não fareis assim para com o Senhor vosso Deus;

[[v5-12-5]]

^<<v5-12-5,5>>^ mas recorrereis ao lugar que o Senhor vosso Deus escolher de todas as vossas tribos para ali pôr o seu nome, para sua habitação, e ali vireis.

[[v5-12-6]]

^<<v5-12-6,6>>^ A esse lugar trareis os vossos holocaustos e sacrifícios, e os vossos dízimos e a oferta alçada da vossa mão, e os vossos votos e ofertas voluntárias, e os primogênitos das vossas vacas e ovelhas;

[[v5-12-7]]

^<<v5-12-7,7>>^ e ali comereis perante o Senhor vosso Deus, e vos alegrareis, vós e as vossas casas, em tudo em que puserdes a vossa mão, no que o Senhor vosso Deus vos tiver abençoado.

[[v5-12-8]]

^<<v5-12-8,8>>^ Não fareis conforme tudo o que hoje fazemos aqui, cada qual tudo o que bem lhe parece aos olhos.

[[v5-12-9]]

^<<v5-12-9,9>>^ Porque até agora não entrastes no descanso e na herança que o Senhor vosso Deus vos dá;

[[v5-12-10]]

^<<v5-12-10,10>>^ mas quando passardes o Jordão, e habitardes na terra que o senhor vosso Deus vos faz herdar, ele vos dará repouso de todos os vossos inimigos em redor, e morareis seguros.

[[v5-12-11]]

^<<v5-12-11,11>>^ Então haverá um lugar que o Senhor vosso Deus escolherá para ali fazer habitar o seu nome; a esse lugar trareis tudo o que eu vos ordeno: os vossos holocaustos e sacrifícios, os vossos dízimos, a oferta alçada da vossa mão, e tudo o que de melhor oferecerdes ao Senhor em cumprimento dos votos que fizerdes.

[[v5-12-12]]

^<<v5-12-12,12>>^ E vos alegrareis perante o Senhor vosso Deus, vós, vossos filhos e vossas filhas, vossos servos e vossas servas, bem como o levita que está dentro das vossas portas, pois convosco não tem parte nem herança.

[[v5-12-13]]

^<<v5-12-13,13>>^ Guarda-te de ofereceres os teus holocaustos em qualquer lugar que vires;

[[v5-12-14]]

^<<v5-12-14,14>>^ mas no lugar que o Senhor escolher numa das tuas tribos, ali oferecerás os teus holocaustos, e ali farás tudo o que eu te ordeno.

[[v5-12-15]]

^<<v5-12-15,15>>^ Todavia, conforme todo o teu desejo, poderás degolar, e comer carne dentro das tuas portas, segundo a bênção do Senhor teu Deus que ele te houver dado; tanto o imundo como o limpo comerão dela, como da gazela e do veado;

[[v5-12-16]]

^<<v5-12-16,16>>^ tão-somente não comerás do sangue; sobre a terra o derramarás como água.

[[v5-12-17]]

^<<v5-12-17,17>>^ Dentro das tuas portas não poderás comer o dízimo do teu grão, do teu mosto e do teu azeite, nem os primogênitos das tuas vacas e das tuas ovelhas, nem qualquer das tuas ofertas votivas, nem as tuas ofertas voluntárias, nem a oferta alçada da tua mão;

[[v5-12-18]]

^<<v5-12-18,18>>^ mas os comerás perante o Senhor teu Deus, no lugar que ele escolher, tu, teu filho, tua filha, o teu servo, a tua serva, e bem assim e levita que está dentre das tuas portas; e perante o Senhor teu Deus te alegrarás em tudo em que puseres a mão.

[[v5-12-19]]

^<<v5-12-19,19>>^ Guarda-te, que não desampares o levita por todos os dias que viveres na tua terra.

[[v5-12-20]]

^<<v5-12-20,20>>^ Quando o Senhor teu Deus dilatar os teus termos, como te prometeu, e tu disseres: Comerei carne &#123;porquanto tens desejo de comer carne&#125;; conforme todo o teu desejo poderás comê-la.

[[v5-12-21]]

^<<v5-12-21,21>>^ Se estiver longe de ti o lugar que o Senhor teu Deus escolher para ali pôr o seu nome, então degolarás do teu gado e do teu rebanho, que o Senhor te houver dado, como te ordenei; e poderás comer dentro das tuas portas, conforme todo o teu desejo.

[[v5-12-22]]

^<<v5-12-22,22>>^ Como se come a gazela e o veado, assim comerás dessas carnes; o imundo e o limpo igualmente comerão delas.

[[v5-12-23]]

^<<v5-12-23,23>>^ Tão-somente guarda-te de comeres o sangue; pois o sangue é a vida; pelo que não comerás a vida com a carne.

[[v5-12-24]]

^<<v5-12-24,24>>^ Não o comerás; sobre a terra o derramarás como água.

[[v5-12-25]]

^<<v5-12-25,25>>^ Não o comerás, para que te vá bem a ti, a teus filhos depois de ti, quando fizeres o que é reto aos olhos do Senhor.

[[v5-12-26]]

^<<v5-12-26,26>>^ Somente tomarás as coisas santas que tiveres, e as tuas ofertas votivas, e irás ao lugar que o Senhor escolher;

[[v5-12-27]]

^<<v5-12-27,27>>^ oferecerás os teus holocaustos, a carne e o sangue sobre o altar do Senhor teu Deus; e o sangue dos teus sacrifícios se derramará sobre o altar do Senhor teu Deus, porém a carne comerás.

[[v5-12-28]]

^<<v5-12-28,28>>^ Ouve e guarda todas estas palavras que eu te ordeno, para que te vá bem a ti, e a teus filhos depois de ti, para sempre, se fizeres o que é bom e reto aos olhos do Senhor teu Deus.

[[v5-12-29]]

^<<v5-12-29,29>>^ Quando o Senhor teu Deus exterminar de diante de ti as nações aonde estás entrando para as possuir, e as desapossares e habitares na sua terra,

[[v5-12-30]]

^<<v5-12-30,30>>^ guarda-te para que não te enlaces para as seguires, depois que elas forem destruídas diante de ti; e que não perguntes acerca dos seus deuses, dizendo: De que modo serviam estas nações os seus deuses? pois do mesmo modo também farei eu.

[[v5-12-31]]

^<<v5-12-31,31>>^ Não farás assim para com o Senhor teu Deus; porque tudo o que é abominável ao Senhor, e que ele detesta, fizeram elas para com os seus deuses; pois até seus filhos e suas filhas queimam no fogo aos seus deuses.

[[v5-12-32]]

^<<v5-12-32,32>>^ Tudo o que eu te ordeno, observarás; nada lhe acrescentarás nem diminuirás.

'''

xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[Próximo Capítulo &#62;]