include::./index.adoc[]

[[v5-2-0]]
=== Deuteronômio, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v5-2-1]]

^<<v5-2-1,1>>^ Depois viramo-nos, e caminhamos para o deserto, pelo caminho do Mar Vermelho, como o Senhor me tinha dito, e por muitos dias rodeamos o monte Seir.

[[v5-2-2]]

^<<v5-2-2,2>>^ Então o Senhor me disse:

[[v5-2-3]]

^<<v5-2-3,3>>^ Basta de rodeardes este monte; virai-vos para o norte.

[[v5-2-4]]

^<<v5-2-4,4>>^ Dá ordem ao povo, dizendo: Haveis de passar pelo território de vossos irmãos, os filhos de Esaú, que habitam em Seir; e eles terão medo de vós. Portanto guardai-vos bem;

[[v5-2-5]]

^<<v5-2-5,5>>^ não contendais com eles, porque não vos darei da sua terra nem sequer o que pisar a planta de um pé; porquanto a Esaú dei o monte Seir por herança.

[[v5-2-6]]

^<<v5-2-6,6>>^ Comprareis deles por dinheiro mantimento para comerdes, como também comprareis deles água para beberdes.

[[v5-2-7]]

^<<v5-2-7,7>>^ Pois o Senhor teu Deus te há abençoado em toda obra das tuas mãos; ele tem conhecido o teu caminho por este grande deserto; estes quarenta anos o Senhor teu Deus tem estado contigo; nada te há faltado.

[[v5-2-8]]

^<<v5-2-8,8>>^ Assim, pois, passamos por nossos irmãos, os filhos de Esaú, que habitam em Seir, desde o caminho da Arabá de Elate e de Eziom-Geber: Depois nos viramos e passamos pelo caminho do deserto de Moabe.

[[v5-2-9]]

^<<v5-2-9,9>>^ Então o Senhor me disse: Não molestes aos de Moabe, e não contendas com eles em peleja, porque nada te darei da sua terra por herança; porquanto dei Ar por herança aos filhos de Ló.

[[v5-2-10]]

^<<v5-2-10,10>>^ &#123;Antes haviam habitado nela os emins, povo grande e numeroso, e alto como os anaquins;

[[v5-2-11]]

^<<v5-2-11,11>>^ eles também são considerados refains como os anaquins; mas os moabitas lhes chamam emins.

[[v5-2-12]]

^<<v5-2-12,12>>^ Outrora os horeus também habitaram em Seir; porém os filhos de Esaú os desapossaram, e os destruíram de diante de si, e habitaram no lugar deles, assim come Israel fez à terra da sua herança, que o Senhor lhe deu.&#125;

[[v5-2-13]]

^<<v5-2-13,13>>^ Levantai-vos agora, e passai o ribeiro de Zerede. Passamos, pois, o ribeiro de Zerede.

[[v5-2-14]]

^<<v5-2-14,14>>^ E os dias que caminhamos, desde Cades-Barnéia até passarmos o ribeiro de Zerede, foram trinta e oito anos, até que toda aquela geração dos homens de guerra se consumiu do meio do arraial, como o Senhor lhes jurara.

[[v5-2-15]]

^<<v5-2-15,15>>^ Também foi contra eles a mão do Senhor, para os destruir do meio do arraial, até os haver consumido.

[[v5-2-16]]

^<<v5-2-16,16>>^ Ora, sucedeu que, sendo já consumidos pela morte todos os homens de guerra dentre o povo,

[[v5-2-17]]

^<<v5-2-17,17>>^ o Senhor me disse:

[[v5-2-18]]

^<<v5-2-18,18>>^ Hoje passarás por Ar, o limite de Moabe;

[[v5-2-19]]

^<<v5-2-19,19>>^ e quando chegares defronte dos amonitas, não os molestes, e com eles não contendas, porque nada te darei da terra dos amonitas por herança; porquanto aos filhos de Ló a dei por herança.

[[v5-2-20]]

^<<v5-2-20,20>>^ &#123;Também essa é considerada terra de refains; outrora habitavam nela refains, mas os amonitas lhes chamam zanzumins,

[[v5-2-21]]

^<<v5-2-21,21>>^ povo grande e numeroso, e alto como os anaquins; mas o Senhor os destruiu de diante dos amonitas; e estes, tendo-os desapossado, habitaram no lugar deles;

[[v5-2-22]]

^<<v5-2-22,22>>^ assim como fez pelos filhos de Esaú, que habitam em Seir, quando de diante deles destruiu os horeus; e os filhos de Esaú, havendo-os desapossado, habitaram no lugar deles até hoje.

[[v5-2-23]]

^<<v5-2-23,23>>^ Também os caftorins, que saíram de Caftor, destruíram os aveus, que habitavam em aldeias até Gaza, e habitaram no lugar deles.&#125;

[[v5-2-24]]

^<<v5-2-24,24>>^ Levantai-vos, parti e passai o ribeiro de Arnom; eis que entreguei nas tuas mãos a Siom, o amorreu, rei de Hesbom, e à sua terra; começa a te apoderares dela, contendendo com eles em peleja.

[[v5-2-25]]

^<<v5-2-25,25>>^ Neste dia começarei a meter terror e medo de ti aos povos que estão debaixo de todo o céu; os quais, ao ouvirem a tua fama, tremerão e se angustiarão por causa de ti.

[[v5-2-26]]

^<<v5-2-26,26>>^ Então, do deserto de Quedemote, mandei mensageiros a Siom, rei de Hesbom, com palavras de paz, dizendo:

[[v5-2-27]]

^<<v5-2-27,27>>^ Deixa-me passar pela tua terra; somente pela estrada irei, não me desviando nem para a direita nem para a esquerda.

[[v5-2-28]]

^<<v5-2-28,28>>^ Por dinheiro me venderás mantimento, para que eu coma; e por dinheiro me darás a água, para que eu beba. Tão-somente deixa-me passar a pé,

[[v5-2-29]]

^<<v5-2-29,29>>^ assim como me fizeram os filhos de Esaú, que habitam em Seir, e os moabitas que habitam em Ar; até que eu passe o Jordão para a terra que o Senhor nosso Deus nos dá.

[[v5-2-30]]

^<<v5-2-30,30>>^ Mas Siom, rei de Hesbom, não nos quis deixar passar por sua terra, porquanto o Senhor teu Deus lhe endurecera o espírito, e lhe fizera obstinado o coração, para to entregar nas mãos, como hoje se vê.

[[v5-2-31]]

^<<v5-2-31,31>>^ Disse-me, pois, o Senhor: Eis aqui, comecei a entregar-te Siom e a sua terra; começa, pois, a te apoderares dela, para possuíres a sua terra por herança.

[[v5-2-32]]

^<<v5-2-32,32>>^ Então Siom nos saiu ao encontro, ele e todo o seu povo, à peleja, em Jaza;

[[v5-2-33]]

^<<v5-2-33,33>>^ e o Senhor nosso Deus no-lo entregou, e o ferimos a ele, e a seus filhos, e a todo o seu povo.

[[v5-2-34]]

^<<v5-2-34,34>>^ Também naquele tempo lhe tomamos todas as cidades, e fizemos perecer a todos, homens, mulheres e pequeninos, não deixando sobrevivente algum;

[[v5-2-35]]

^<<v5-2-35,35>>^ somente tomamos por presa o gado para nós, juntamente com o despojo das cidades que havíamos tomado.

[[v5-2-36]]

^<<v5-2-36,36>>^ Desde Aroer, que está à borda do vale do Arnom, e desde a cidade que está no vale, até Gileade, nenhuma cidade houve tão alta que de nós escapasse; tudo o Senhor nosso Deus no-lo entregou.

[[v5-2-37]]

^<<v5-2-37,37>>^ Somente à terra dos amonitas não chegastes, nem a parte alguma da borda do ribeiro de Jaboque, nem a cidade alguma da região montanhosa, nem a coisa alguma que o Senhor nosso Deus proibira.

'''

xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[&#60; Capítulo Anterior] | <<v5-2-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[Próximo Capítulo &#62;]