include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v34-3-1]]

^<<v34-3-1,1>>^ Ai da cidade ensangüentada! Ela está toda cheia de mentiras e de rapina! da presa não há fim!

[[v34-3-2]]

^<<v34-3-2,2>>^ Eis o estrépito do açoite, e o estrondo das rodas, os cavalos que curveteiam e os carros que saltam;

[[v34-3-3]]

^<<v34-3-3,3>>^ o cavaleiro que monta, a espada rutilante, a lança reluzente, a, multidão de mortos, o montão de cadáveres, e defuntos inumeráveis; tropeçam nos cadáveres;

[[v34-3-4]]

^<<v34-3-4,4>>^ tudo isso por causa da multidão dos adultérios, da meretriz formosa, da mestra das feitiçarias, que vende nações por seus deleites, e famílias pelas suas feitiçarias.

[[v34-3-5]]

^<<v34-3-5,5>>^ Eis que eu estou contra ti, diz o Senhor dos exércitos; e levantarei as tuas fraldas sobre a tua face; e às nações mostrarei a tua nudez, e seus reinos a tua vergonha.

[[v34-3-6]]

^<<v34-3-6,6>>^ Lançarei sobre ti imundícias e te tratarei com desprezo, e te porei como espetáculo.

[[v34-3-7]]

^<<v34-3-7,7>>^ E há de ser todos os que te virem fugirão de ti, e dirão: Nínive esta destruída; quem terá compaixão dela? Donde te buscarei consoladores?

[[v34-3-8]]

^<<v34-3-8,8>>^ És tu melhor do que Tebas, que se sentava à beira do Nilo, cercada de águas, tendo por baluarte o mar, e as águas por muralha,

[[v34-3-9]]

^<<v34-3-9,9>>^ Etiópia e Egito eram a sua força, que era inesgotável; Pute e Líbia eram teus aliados.

[[v34-3-10]]

^<<v34-3-10,10>>^ Todavia ela foi levada, foi para o cativeiro; também os seus pequeninos foram despedaçados nas entradas de todas as ruas, e sobre os seus nobres lançaram sortes, e todos os seus grandes foram presos em grilhões.

[[v34-3-11]]

^<<v34-3-11,11>>^ Tu também serás embriagada, e ficarás escondida; e buscarás um refúgio do inimigo.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as tuas fortalezas serão como figueiras com figos temporãos; sendo eles sacudidos, caem na boca do que os há de comer.

[[v34-3-13]]

^<<v34-3-13,13>>^ Eis que as tuas tropas no meio de ti são como mulheres; as portas da tua terra estão de todo abertas aos teus inimigos; o fogo consome os teus ferrolhos.

[[v34-3-14]]

^<<v34-3-14,14>>^ Tira água para o tempo do cerco; reforça as tuas fortalezas; entra no lodo, pisa o barro, pega na forma para os tijolos.

[[v34-3-15]]

^<<v34-3-15,15>>^ O fogo ali te consumirá; a espada te exterminará; ela te devorará como a locusta. Multiplica-te como a locusta, multiplica-te como o gafanhoto.

[[v34-3-16]]

^<<v34-3-16,16>>^ Multiplicaste os teus negociantes mais do que as estrelas do céu; a locusta estende as asas e sai voando.

[[v34-3-17]]

^<<v34-3-17,17>>^ Os teus príncipes são como os gafanhotos, e os teus chefes como enxames de gafanhotos, que se acampam nas sebes nos dias de frio; em subindo o sol voam, e não se sabe o lugar em que estão.

[[v34-3-18]]

^<<v34-3-18,18>>^ Os teus pastores dormitam, ó rei da Assíria; os teus nobres dormem, o teu povo está espalhado pelos montes, sem que haja quem o ajunte.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há cura para a tua ferida; a tua chaga é grave. Todos os que ouvirem a tua fama baterão as palmas sobre ti; porque, sobre quem não tem passado continuamente a tua malícia?

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]