include::./index.adoc[]

[[v34-1-0]]
=== Naum, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v34-1-1]]

^<<v34-1-1,1>>^ Oráculo acerca de Nínive. Livro da visão de Naum, o elcosita.

[[v34-1-2]]

^<<v34-1-2,2>>^ O Senhor é um Deus zeloso e vingador; o Senhor é vingador e cheio de indignação; o Senhor toma vingança contra os seus adversários, e guarda a ira contra os seus inimigos.

[[v34-1-3]]

^<<v34-1-3,3>>^ O Senhor é tardio em irar-se, e de grande poder, e ao culpado de maneira alguma terá por inocente; o Senhor tem o seu caminho no turbilhão e na tempestade, e as nuvens são o pó dos seus pés.

[[v34-1-4]]

^<<v34-1-4,4>>^ Ele repreende o mar, e o faz secar, e esgota todos os rios; desfalecem Basã e Carmelo, e a flor do Líbano murcha.

[[v34-1-5]]

^<<v34-1-5,5>>^ Os montes tremem perante ele, e os outeiros se derretem; e a terra fica devastada diante dele, sim, o mundo, e todos os que nele habitam.

[[v34-1-6]]

^<<v34-1-6,6>>^ Quem pode manter-se diante do seu furor? e quem pode subsistir diante do ardor da sua ira? a sua cólera se derramou como um fogo, e por ele as rochas são fendidas.

[[v34-1-7]]

^<<v34-1-7,7>>^ O Senhor é bom, uma fortaleza no dia da angústia; e conhece os que nele confiam.

[[v34-1-8]]

^<<v34-1-8,8>>^ E com uma inundação transbordante acabará duma vez com o lugar dela; e até para dentro das trevas perseguirá os seus inimigos.

[[v34-1-9]]

^<<v34-1-9,9>>^ Que é o que projetais vós contra o Senhor? Ele destruirá de vez; não se levantará por duas vezes a angústia.

[[v34-1-10]]

^<<v34-1-10,10>>^ Pois ainda que eles se entrelacem como os espinhos, e se saturem de vinho como bêbados, serão inteiramente consumidos como restolho seco.

[[v34-1-11]]

^<<v34-1-11,11>>^ Não saiu de ti um que maquinava o mal contra o Senhor, aconselhando maldade?

[[v34-1-12]]

^<<v34-1-12,12>>^ Assim diz o Senhor: Por mais intatos que sejam, e por mais numerosos, assim mesmo serão exterminados e passarão. Ainda que te afligi, não te afligirei mais.

[[v34-1-13]]

^<<v34-1-13,13>>^ Mas agora quebrarei o seu jugo de sobre ti, e romperei as tuas cadeias.

[[v34-1-14]]

^<<v34-1-14,14>>^ Contra ti, porém, o Senhor deu ordem que não haja mais linhagem do teu nome; da casa dos teus deuses exterminarei as imagens de escultura e as de fundição; farei o teu sepulcro, porque és vil.

[[v34-1-15]]

^<<v34-1-15,15>>^ Eis sobre os montes os pés do que traz boas novas, do que anuncia a paz! Celebra as tuas festas, ó Judá, cumpre os teus votos, porque o ímpio não tornará mais a passar por ti; ele é inteiramente exterminado.

'''

xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[&#60; Capítulo Anterior] | <<v34-1-0,Topo>> | xref:034-naum/034-naum-002.adoc#v34-2-0[Próximo Capítulo &#62;]