include::./index.adoc[]

[[v34-2-0]]
=== Naum, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v34-2-1]]

^<<v34-2-1,1>>^ O destruidor sobe contra ti. Guarda tu a fortaleza, vigia o caminho, robustece os lombos, arregimenta bem as tuas forças.

[[v34-2-2]]

^<<v34-2-2,2>>^ Pois o Senhor restaura a excelência de Jacó, qual a excelência de Israel; porque os saqueadores os despojaram e destruíram os seus sarmentos.

[[v34-2-3]]

^<<v34-2-3,3>>^ Os escudos dos seus valentes estão vermelhos, os homens valorosos estão vestidos de escarlate; os carros resplandecem como o aço no dia da sua preparação, e as lanças são brandidas.

[[v34-2-4]]

^<<v34-2-4,4>>^ Os carros andam furiosamente nas ruas; cruzam as praças em todas as direções; parecem como tochas, e correm como os relâmpagos.

[[v34-2-5]]

^<<v34-2-5,5>>^ Ele se lembra dos seus nobres; eles tropeçam na sua marcha; apressam-se para chegar ao muro de cidade, arma-se a manta.

[[v34-2-6]]

^<<v34-2-6,6>>^ As portas dos rios abrem-se, e o palácio está em confusão.

[[v34-2-7]]

^<<v34-2-7,7>>^ E está decretado: ela é despida , e levada cativa; e as suas servas gemem como pombas, batendo em seus peitos.

[[v34-2-8]]

^<<v34-2-8,8>>^ Nínive desde que existe tem sido como um tanque de águas; elas, porém, fogem agora: parai, parai, clama-se; mas ninguém olhara para trás.

[[v34-2-9]]

^<<v34-2-9,9>>^ Saqueai a prata, saqueai o ouro; pois não ha fim dos tesouros; abastança há de todas as coisas preciosas.

[[v34-2-10]]

^<<v34-2-10,10>>^ Ela está vazia, esgotada e devastada; derrete-se o coração, tremem os joelhos, e em todos os lombos há dor; o rosto de todos eles empalidece.

[[v34-2-11]]

^<<v34-2-11,11>>^ Onde está agora o covil dos leões, e a habitação dos leões novos, onde andavam o leão, e a leoa, e o cachorro do leão, sem haver ninguém que os espantasse?

[[v34-2-12]]

^<<v34-2-12,12>>^ O leão arrebatava o que bastava para os seus cachorros, e estrangulava a presa para as suas leoas, e enchia de presas as suas cavernas, e de rapina os seus covis.

[[v34-2-13]]

^<<v34-2-13,13>>^ Eis que eu estou contra ti, diz o Senhor dos exércitos, e queimarei na fumaça os teus carros, e a espada devorará os teus leões novos; e exterminarei da terra a tua presa; e não se ouvira mais a voz dos teus embaixadores.

'''

xref:034-naum/034-naum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-naum/034-naum-003.adoc#v34-3-0[Próximo Capítulo &#62;]