include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v48-5-1]]

^<<v48-5-1,1>>^ Para a liberdade Cristo nos libertou; permanecei, pois, firmes e não vos dobreis novamente a um jogo de escravidão.

[[v48-5-2]]

^<<v48-5-2,2>>^ Eis que eu, Paulo, vos digo que, se vos deixardes circuncidar, Cristo de nada vos aproveitará.

[[v48-5-3]]

^<<v48-5-3,3>>^ E de novo testifico a todo homem que se deixa circuncidar, que está obrigado a guardar toda a lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Separados estais de Cristo, vós os que vos justificais pela lei; da graça decaístes.

[[v48-5-5]]

^<<v48-5-5,5>>^ Nós, entretanto, pelo Espírito aguardamos a esperança da justiça que provém da fé.

[[v48-5-6]]

^<<v48-5-6,6>>^ Porque em Cristo Jesus nem a circuncisão nem a incircuncisão vale coisa alguma; mas sim a fé que opera pelo amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Corríeis bem; quem vos impediu de obedecer à verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Esta persuasão não vem daquele que vos chama.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento leveda a massa toda.

[[v48-5-10]]

^<<v48-5-10,10>>^ Confio de vós, no Senhor, que de outro modo não haveis de pensar; mas aquele que vos perturba, seja quem for, sofrerá a condenação.

[[v48-5-11]]

^<<v48-5-11,11>>^ Eu, porém, irmãos, se é que prego ainda a circuncisão, por que ainda sou perseguido? Nesse caso o escândalo da cruz estaria aniquilado.

[[v48-5-12]]

^<<v48-5-12,12>>^ Oxalá se mutilassem aqueles que vos andam inquietando.

[[v48-5-13]]

^<<v48-5-13,13>>^ Porque vós, irmãos, fostes chamados à liberdade. Mas não useis da liberdade para dar ocasião à carne, antes pelo amor servi-vos uns aos outros.

[[v48-5-14]]

^<<v48-5-14,14>>^ Pois toda a lei se cumpre numa só palavra, a saber: Amarás ao teu próximo como a ti mesmo.

[[v48-5-15]]

^<<v48-5-15,15>>^ Se vós, porém, vos mordeis e devorais uns aos outros, vede não vos consumais uns aos outros.

[[v48-5-16]]

^<<v48-5-16,16>>^ Digo, porém: Andai pelo Espírito, e não haveis de cumprir a cobiça da carne.

[[v48-5-17]]

^<<v48-5-17,17>>^ Porque a carne luta contra o Espírito, e o Espírito contra a carne; e estes se opõem um ao outro, para que não façais o que quereis.

[[v48-5-18]]

^<<v48-5-18,18>>^ Mas, se sois guiados pelo Espírito, não estais debaixo da lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ Ora, as obras da carne são manifestas, as quais são: a prostituição, a impureza, a lascívia,

[[v48-5-20]]

^<<v48-5-20,20>>^ a idolatria, a feitiçaria, as inimizades, as contendas, os ciúmes, as iras, as facções, as dissensões, os partidos,

[[v48-5-21]]

^<<v48-5-21,21>>^ as invejas, as bebedices, as orgias, e coisas semelhantes a estas, contra as quais vos previno, como já antes vos preveni, que os que tais coisas praticam não herdarão o reino de Deus.

[[v48-5-22]]

^<<v48-5-22,22>>^ Mas o fruto do Espírito é: o amor, o gozo, a paz, a longanimidade, a benignidade, a bondade, a fidelidade.

[[v48-5-23]]

^<<v48-5-23,23>>^ a mansidão, o domínio próprio; contra estas coisas não há lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ E os que são de Cristo Jesus crucificaram a carne com as suas paixões e concupiscências.

[[v48-5-25]]

^<<v48-5-25,25>>^ Se vivemos pelo Espírito, andemos também pelo Espírito.

[[v48-5-26]]

^<<v48-5-26,26>>^ Não nos tornemos vangloriosos, provocando-nos uns aos outros, invejando-nos uns aos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]