include::./index.adoc[]

[[v48-3-0]]
=== Gálatas, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó insensatos gálatas! quem vos fascinou a vós, ante cujos olhos foi representado Jesus Cristo como crucificado?

[[v48-3-2]]

^<<v48-3-2,2>>^ Só isto quero saber de vós: Foi por obras da lei que recebestes o Espírito, ou pelo ouvir com fé?

[[v48-3-3]]

^<<v48-3-3,3>>^ Sois vós tão insensatos? tendo começado pelo Espírito, é pela carne que agora acabareis?

[[v48-3-4]]

^<<v48-3-4,4>>^ Será que padecestes tantas coisas em vão? Se é que isso foi em vão.

[[v48-3-5]]

^<<v48-3-5,5>>^ Aquele pois que vos dá o Espírito, e que opera milagres entre vós, acaso o faz pelas obras da lei, ou pelo ouvir com fé?

[[v48-3-6]]

^<<v48-3-6,6>>^ Assim como Abraão creu a Deus, e isso lhe foi imputado como justiça.

[[v48-3-7]]

^<<v48-3-7,7>>^ Sabei, pois, que os que são da fé, esses são filhos de Abraão.

[[v48-3-8]]

^<<v48-3-8,8>>^ Ora, a Escritura, prevendo que Deus havia de justificar pela fé os gentios, anunciou previamente a boa nova a Abraão, dizendo: Em ti serão abençoadas todas as nações.

[[v48-3-9]]

^<<v48-3-9,9>>^ De modo que os que são da fé são abençoados com o crente Abraão.

[[v48-3-10]]

^<<v48-3-10,10>>^ Pois todos quantos são das obras da lei estão debaixo da maldição; porque escrito está: Maldito todo aquele que não permanece em todas as coisas que estão escritas no livro da lei, para fazê-las.

[[v48-3-11]]

^<<v48-3-11,11>>^ É evidente que pela lei ninguém é justificado diante de Deus, porque: O justo viverá da fé;

[[v48-3-12]]

^<<v48-3-12,12>>^ ora, a lei não é da fé, mas: O que fizer estas coisas, por elas viverá.

[[v48-3-13]]

^<<v48-3-13,13>>^ Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós; porque está escrito: Maldito todo aquele que for pendurado no madeiro;

[[v48-3-14]]

^<<v48-3-14,14>>^ para que aos gentios viesse a bênção de Abraão em Jesus Cristo, a fim de que nós recebêssemos pela fé a promessa do Espírito.

[[v48-3-15]]

^<<v48-3-15,15>>^ Irmãos, como homem falo. Um testamento, embora de homem, uma vez confirmado, ninguém o anula, nem lhe acrescenta coisa alguma.

[[v48-3-16]]

^<<v48-3-16,16>>^ Ora, a Abraão e a seu descendente foram feitas as promessas; não diz: E a seus descendentes, como falando de muitos, mas como de um só: E a teu descendente, que é Cristo.

[[v48-3-17]]

^<<v48-3-17,17>>^ E digo isto: Ao testamento anteriormente confirmado por Deus, a lei, que veio quatrocentos e trinta anos depois, não invalida, de forma a tornar inoperante a promessa.

[[v48-3-18]]

^<<v48-3-18,18>>^ Pois se da lei provém a herança, já não provém mais da promessa; mas Deus, pela promessa, a deu gratuitamente a Abraão.

[[v48-3-19]]

^<<v48-3-19,19>>^ Logo, para que é a lei? Foi acrescentada por causa das transgressões, até que viesse o descendente a quem a promessa tinha sido feita; e foi ordenada por meio de anjos, pela mão de um mediador.

[[v48-3-20]]

^<<v48-3-20,20>>^ Ora, o mediador não o é de um só, mas Deus é um só.

[[v48-3-21]]

^<<v48-3-21,21>>^ É a lei, então, contra as promessas de Deus? De modo nenhum; porque, se fosse dada uma lei que pudesse vivificar, a justiça, na verdade, teria sido pela lei.

[[v48-3-22]]

^<<v48-3-22,22>>^ Mas a Escritura encerrou tudo debaixo do pecado, para que a promessa pela fé em Jesus Cristo fosse dada aos que crêem.

[[v48-3-23]]

^<<v48-3-23,23>>^ Mas, antes que viesse a fé, estávamos guardados debaixo da lei, encerrados para aquela fé que se havia de revelar.

[[v48-3-24]]

^<<v48-3-24,24>>^ De modo que a lei se tornou nosso aio, para nos conduzir a Cristo, a fim de que pela fé fôssemos justificados.

[[v48-3-25]]

^<<v48-3-25,25>>^ Mas, depois que veio a fé, já não estamos debaixo de aio.

[[v48-3-26]]

^<<v48-3-26,26>>^ Pois todos sois filhos de Deus pela fé em Cristo Jesus.

[[v48-3-27]]

^<<v48-3-27,27>>^ Porque todos quantos fostes batizados em Cristo vos revestistes de Cristo.

[[v48-3-28]]

^<<v48-3-28,28>>^ Não há judeu nem grego; não há escravo nem livre; não há homem nem mulher; porque todos vós sois um em Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ E, se sois de Cristo, então sois descendência de Abraão, e herdeiros conforme a promessa.

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]