include::./index.adoc[]

[[v48-4-0]]
=== Gálatas, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v48-4-1]]

^<<v48-4-1,1>>^ Ora, digo que por todo o tempo em que o herdeiro é menino, em nada difere de um servo, ainda que seja senhor de tudo;

[[v48-4-2]]

^<<v48-4-2,2>>^ mas está debaixo de tutores e curadores até o tempo determinado pelo pai.

[[v48-4-3]]

^<<v48-4-3,3>>^ Assim também nós, quando éramos meninos, estávamos reduzidos à servidão debaixo dos rudimentos do mundo;

[[v48-4-4]]

^<<v48-4-4,4>>^ mas, vindo a plenitude dos tempos, Deus enviou seu Filho, nascido de mulher, nascido debaixo de lei,

[[v48-4-5]]

^<<v48-4-5,5>>^ para resgatar os que estavam debaixo de lei, a fim de recebermos a adoção de filhos.

[[v48-4-6]]

^<<v48-4-6,6>>^ E, porque sois filhos, Deus enviou aos nossos corações o Espírito de seu Filho, que clama: Aba, Pai.

[[v48-4-7]]

^<<v48-4-7,7>>^ Portanto já não és mais servo, mas filho; e se és filho, és também herdeiro por Deus.

[[v48-4-8]]

^<<v48-4-8,8>>^ Outrora, quando não conhecíeis a Deus, servíeis aos que por natureza não são deuses;

[[v48-4-9]]

^<<v48-4-9,9>>^ agora, porém, que já conheceis a Deus, ou, melhor, sendo conhecidos por Deus, como tornais outra vez a esses rudimentos fracos e pobres, aos quais de novo quereis servir?

[[v48-4-10]]

^<<v48-4-10,10>>^ Guardais dias, e meses, e tempos, e anos.

[[v48-4-11]]

^<<v48-4-11,11>>^ Temo a vosso respeito não haja eu trabalhado em vão entre vós.

[[v48-4-12]]

^<<v48-4-12,12>>^ Irmãos, rogo-vos que vos torneis como eu, porque também eu me tornei como vós. Nenhum mal me fizestes;

[[v48-4-13]]

^<<v48-4-13,13>>^ e vós sabeis que por causa de uma enfermidade da carne vos anunciei o evangelho a primeira vez,

[[v48-4-14]]

^<<v48-4-14,14>>^ e aquilo que na minha carne era para vós uma tentação, não o desprezastes nem o repelistes, antes me recebestes como a um anjo de Deus, mesmo como a Cristo Jesus.

[[v48-4-15]]

^<<v48-4-15,15>>^ Onde está, pois, aquela vossa satisfação? Porque vos dou testemunho de que, se possível fora, teríeis arrancado os vossos olhos, e mos teríeis dado.

[[v48-4-16]]

^<<v48-4-16,16>>^ Tornei-me acaso vosso inimigo, porque vos disse a verdade?

[[v48-4-17]]

^<<v48-4-17,17>>^ Eles vos procuram zelosamente não com bons motivos, mas querem vos excluir, para que zelosamente os procureis a eles.

[[v48-4-18]]

^<<v48-4-18,18>>^ No que é bom, é bom serdes sempre procurados, e não só quando estou presente convosco.

[[v48-4-19]]

^<<v48-4-19,19>>^ Meus filhinhos, por quem de novo sinto as dores de parto, até que Cristo seja formado em vós;

[[v48-4-20]]

^<<v48-4-20,20>>^ eu bem quisera estar presente convosco agora, e mudar o tom da minha voz; porque estou perplexo a vosso respeito.

[[v48-4-21]]

^<<v48-4-21,21>>^ Dizei-me, os que quereis estar debaixo da lei, não ouvis vós a lei?

[[v48-4-22]]

^<<v48-4-22,22>>^ Porque está escrito que Abraão teve dois filhos, um da escrava, e outro da livre.

[[v48-4-23]]

^<<v48-4-23,23>>^ Todavia o que era da escrava nasceu segundo a carne, mas, o que era da livre, por promessa.

[[v48-4-24]]

^<<v48-4-24,24>>^ O que se entende por alegoria: pois essas mulheres são dois pactos; um do monte Sinai, que dá à luz filhos para a servidão, e que é Agar.

[[v48-4-25]]

^<<v48-4-25,25>>^ Ora, esta Agar é o monte Sinai na Arábia e corresponde à Jerusalém atual, pois é escrava com seus filhos.

[[v48-4-26]]

^<<v48-4-26,26>>^ Mas a Jerusalém que é de cima é livre; a qual é nossa mãe.

[[v48-4-27]]

^<<v48-4-27,27>>^ Pois está escrito: Alegra-te, estéril, que não dás à luz; esforça-te e clama, tu que não estás de parto; porque mais são os filhos da desolada do que os da que tem marido.

[[v48-4-28]]

^<<v48-4-28,28>>^ Ora vós, irmãos, sois filhos da promessa, como Isaque.

[[v48-4-29]]

^<<v48-4-29,29>>^ Mas, como naquele tempo o que nasceu segundo a carne perseguia ao que nasceu segundo o Espírito, assim é também agora.

[[v48-4-30]]

^<<v48-4-30,30>>^ Que diz, porém, a Escritura? Lança fora a escrava e seu filho, porque de modo algum o filho da escrava herdará com o filho da livre.

[[v48-4-31]]

^<<v48-4-31,31>>^ Pelo que, irmãos, não somos filhos da escrava, mas da livre.

'''

xref:048-galatas/048-galatas-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatas/048-galatas-005.adoc#v48-5-0[Próximo Capítulo &#62;]