include::./index.adoc[]

[[v48-1-0]]
=== Gálatas, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v48-1-1]]

^<<v48-1-1,1>>^ Paulo, apóstolo &#123;não da parte dos homens, nem por intermédio de homem algum, mas sim por Jesus Cristo, e por Deus Pai, que o ressuscitou dentre os mortos&#125;,

[[v48-1-2]]

^<<v48-1-2,2>>^ e todos os irmãos que estão comigo, às igrejas da Galácia:

[[v48-1-3]]

^<<v48-1-3,3>>^ Graça a vós, e paz da parte de Deus nosso Pai, e do Senhor Jesus Cristo,

[[v48-1-4]]

^<<v48-1-4,4>>^ o qual se deu a si mesmo por nossos pecados, para nos livrar do presente século mau, segundo a vontade de nosso Deus e Pai,

[[v48-1-5]]

^<<v48-1-5,5>>^ a quem seja a glória para todo o sempre. Amém.

[[v48-1-6]]

^<<v48-1-6,6>>^ Estou admirado de que tão depressa estejais desertando daquele que vos chamou na graça de Cristo, para outro evangelho,

[[v48-1-7]]

^<<v48-1-7,7>>^ o qual não é outro; senão que há alguns que vos perturbam e querem perverter o evangelho de Cristo.

[[v48-1-8]]

^<<v48-1-8,8>>^ Mas, ainda que nós mesmos ou um anjo do céu vos pregasse outro evangelho além do que já vos pregamos, seja anátema.

[[v48-1-9]]

^<<v48-1-9,9>>^ Como antes temos dito, assim agora novamente o digo: Se alguém vos pregar outro evangelho além do que já recebestes, seja anátema.

[[v48-1-10]]

^<<v48-1-10,10>>^ Pois busco eu agora o favor dos homens, ou o favor de Deus? ou procuro agradar aos homens? se estivesse ainda agradando aos homens, não seria servo de Cristo.

[[v48-1-11]]

^<<v48-1-11,11>>^ Mas faço-vos saber, irmãos, que o evangelho que por mim foi anunciado não é segundo os homens;

[[v48-1-12]]

^<<v48-1-12,12>>^ porque não o recebi de homem algum, nem me foi ensinado; mas o recebi por revelação de Jesus Cristo.

[[v48-1-13]]

^<<v48-1-13,13>>^ Pois já ouvistes qual foi outrora o meu procedimento no judaísmo, como sobremaneira perseguia a igreja de Deus e a assolava,

[[v48-1-14]]

^<<v48-1-14,14>>^ e na minha nação excedia em judaísmo a muitos da minha idade, sendo extremamente zeloso das tradições de meus pais.

[[v48-1-15]]

^<<v48-1-15,15>>^ Mas, quando aprouve a Deus, que desde o ventre de minha mãe me separou, e me chamou pela sua graça,

[[v48-1-16]]

^<<v48-1-16,16>>^ revelar seu Filho em mim, para que eu o pregasse entre os gentios, não consultei carne e sangue,

[[v48-1-17]]

^<<v48-1-17,17>>^ nem subi a Jerusalém para estar com os que já antes de mim eram apóstolos, mas parti para a Arábia, e voltei outra vez a Damasco.

[[v48-1-18]]

^<<v48-1-18,18>>^ Depois, passados três anos, subi a Jerusalém para visitar a Cefas, e demorei com ele quinze dias.

[[v48-1-19]]

^<<v48-1-19,19>>^ Mas não vi a nenhum outro dos apóstolos, senão a Tiago, irmão do Senhor.

[[v48-1-20]]

^<<v48-1-20,20>>^ Ora, acerca do que vos escrevo, eis que diante de Deus testifico que não minto.

[[v48-1-21]]

^<<v48-1-21,21>>^ Depois fui para as regiões da Síria e da Cilícia.

[[v48-1-22]]

^<<v48-1-22,22>>^ Não era conhecido de vista das igrejas de Cristo na Judéia;

[[v48-1-23]]

^<<v48-1-23,23>>^ mas somente tinham ouvido dizer: Aquele que outrora nos perseguia agora prega a fé que antes procurava destruir;

[[v48-1-24]]

^<<v48-1-24,24>>^ e glorificavam a Deus a respeito de mim.

'''

xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[&#60; Capítulo Anterior] | <<v48-1-0,Topo>> | xref:048-galatas/048-galatas-002.adoc#v48-2-0[Próximo Capítulo &#62;]