include::./index.adoc[]

[[v21-12-0]]
=== Eclesiastes, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-12-1]]

^<<v21-12-1,1>>^ Lembra-te também do teu Criador nos dias da tua mocidade, antes que venham os maus dias, e cheguem os anos em que dirás: Não tenho prazer neles;

[[v21-12-2]]

^<<v21-12-2,2>>^ antes que se escureçam o sol e a luz, e a lua, e as estrelas, e tornem a vir as nuvens depois da chuva;

[[v21-12-3]]

^<<v21-12-3,3>>^ no dia em que tremerem os guardas da casa, e se curvarem os homens fortes, e cessarem os moedores, por já serem poucos, e se escurecerem os que olham pelas janelas,

[[v21-12-4]]

^<<v21-12-4,4>>^ e as portas da rua se fecharem; quando for baixo o ruído da moedura, e nos levantarmos à voz das aves, e todas as filhas da música ficarem abatidas;

[[v21-12-5]]

^<<v21-12-5,5>>^ como também quando temerem o que é alto, e houver espantos no caminho; e florescer a amendoeira, e o gafanhoto for um peso, e falhar o desejo; porque o homem se vai à sua casa eterna, e os pranteadores andarão rodeando pela praça;

[[v21-12-6]]

^<<v21-12-6,6>>^ antes que se rompa a cadeia de prata, ou se quebre o copo de ouro, ou se despedace o cântaro junto à fonte, ou se desfaça a roda junto à cisterna,

[[v21-12-7]]

^<<v21-12-7,7>>^ e o pó volte para a terra como o era, e o espírito volte a Deus que o deu.

[[v21-12-8]]

^<<v21-12-8,8>>^ Vaidade de vaidades, diz o pregador, tudo é vaidade.

[[v21-12-9]]

^<<v21-12-9,9>>^ Além de ser sábio, o pregador também ensinou ao povo o conhecimento, meditando, e estudando, e pondo em ordem muitos provérbios.

[[v21-12-10]]

^<<v21-12-10,10>>^ Procurou o pregador achar palavras agradáveis, e escreveu com acerto discursos plenos de verdade.

[[v21-12-11]]

^<<v21-12-11,11>>^ As palavras dos sábios são como aguilhões; e como pregos bem fixados são as palavras coligidas dos mestres, as quais foram dadas pelo único pastor.

[[v21-12-12]]

^<<v21-12-12,12>>^ Além disso, filho meu, sê avisado. De fazer muitos livros não há fim; e o muito estudar é enfado da carne.

[[v21-12-13]]

^<<v21-12-13,13>>^ Este é o fim do discurso; tudo já foi ouvido: Teme a Deus, e guarda os seus mandamentos; porque isto é todo o dever do homem.

[[v21-12-14]]

^<<v21-12-14,14>>^ Porque Deus há de trazer a juízo toda obra, e até tudo o que está encoberto, quer seja bom, quer seja mau.

'''

xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[&#60; Capítulo Anterior] | <<v21-12-0,Topo>> | xref:022-canticos/022-canticos-001.adoc#v22-1-0[Próximo Capítulo &#62;]