include::./index.adoc[]

[[v21-3-0]]
=== Eclesiastes, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-3-1]]

^<<v21-3-1,1>>^ Tudo tem a sua ocasião própria, e há tempo para todo propósito debaixo do céu.

[[v21-3-2]]

^<<v21-3-2,2>>^ Há tempo de nascer, e tempo de morrer; tempo de plantar, e tempo de arrancar o que se plantou;

[[v21-3-3]]

^<<v21-3-3,3>>^ tempo de matar, e tempo de curar; tempo de derribar, e tempo de edificar;

[[v21-3-4]]

^<<v21-3-4,4>>^ tempo de chorar, e tempo de rir; tempo de prantear, e tempo de dançar;

[[v21-3-5]]

^<<v21-3-5,5>>^ tempo de espalhar pedras, e tempo de ajuntar pedras; tempo de abraçar, e tempo de abster-se de abraçar;

[[v21-3-6]]

^<<v21-3-6,6>>^ tempo de buscar, e tempo de perder; tempo de guardar, e tempo de deitar fora;

[[v21-3-7]]

^<<v21-3-7,7>>^ tempo de rasgar, e tempo de coser; tempo de estar calado, e tempo de falar;

[[v21-3-8]]

^<<v21-3-8,8>>^ tempo de amar, e tempo de odiar; tempo de guerra, e tempo de paz.

[[v21-3-9]]

^<<v21-3-9,9>>^ Que proveito tem o trabalhador naquilo em que trabalha?

[[v21-3-10]]

^<<v21-3-10,10>>^ Tenho visto o trabalho penoso que Deus deu aos filhos dos homens para nele se exercitarem.

[[v21-3-11]]

^<<v21-3-11,11>>^ Tudo fez formoso em seu tempo; também pôs na mente do homem a idéia da eternidade, se bem que este não possa descobrir a obra que Deus fez desde o princípio até o fim.

[[v21-3-12]]

^<<v21-3-12,12>>^ Sei que não há coisa melhor para eles do que se regozijarem e fazerem o bem enquanto viverem;

[[v21-3-13]]

^<<v21-3-13,13>>^ e também que todo homem coma e beba, e goze do bem de todo o seu trabalho é dom de Deus.

[[v21-3-14]]

^<<v21-3-14,14>>^ Eu sei que tudo quanto Deus faz durará eternamente; nada se lhe pode acrescentar, e nada se lhe pode tirar; e isso Deus faz para que os homens temam diante dele:

[[v21-3-15]]

^<<v21-3-15,15>>^ O que é, já existiu; e o que há de ser, também já existiu; e Deus procura de novo o que já se passou.

[[v21-3-16]]

^<<v21-3-16,16>>^ Vi ainda debaixo do sol que no lugar da retidão estava a impiedade; e que no lugar da justiça estava a impiedade ainda.

[[v21-3-17]]

^<<v21-3-17,17>>^ Eu disse no meu coração: Deus julgará o justo e o ímpio; porque há um tempo para todo propósito e para toda obra.

[[v21-3-18]]

^<<v21-3-18,18>>^ Disse eu no meu coração: Isso é por causa dos filhos dos homens, para que Deus possa prová-los, e eles possam ver que são em si mesmos como os brutos.

[[v21-3-19]]

^<<v21-3-19,19>>^ Pois o que sucede aos filhos dos homens, isso mesmo também sucede aos brutos; uma e a mesma coisa lhes sucede; como morre um, assim morre o outro; todos têm o mesmo fôlego; e o homem não tem vantagem sobre os brutos; porque tudo é vaidade.

[[v21-3-20]]

^<<v21-3-20,20>>^ Todos vão para um lugar; todos são pó, e todos ao pó tornarão.

[[v21-3-21]]

^<<v21-3-21,21>>^ Quem sabe se o espírito dos filhos dos homens vai para cima, e se o espírito dos brutos desce para a terra?

[[v21-3-22]]

^<<v21-3-22,22>>^ Pelo que tenho visto que não há coisa melhor do que alegrar-se o homem nas suas obras; porque esse é o seu quinhão; pois quem o fará voltar para ver o que será depois dele?

'''

xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[&#60; Capítulo Anterior] | <<v21-3-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[Próximo Capítulo &#62;]