include::./index.adoc[]

[[v21-10-0]]
=== Eclesiastes, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-10-1]]

^<<v21-10-1,1>>^ As moscas mortas fazem com que o ungüento do perfumista emita mau cheiro; assim um pouco de estultícia pesa mais do que a sabedoria e a honra.

[[v21-10-2]]

^<<v21-10-2,2>>^ O coração do sábio o inclina para a direita, mas o coração do tolo o inclina para a esquerda.

[[v21-10-3]]

^<<v21-10-3,3>>^ E, até quando o tolo vai pelo caminho, falta-lhe o entendimento, e ele diz a todos que é tolo.

[[v21-10-4]]

^<<v21-10-4,4>>^ Se levantar contra ti o espírito do governador, não deixes o teu lugar; porque a deferência desfaz grandes ofensas.

[[v21-10-5]]

^<<v21-10-5,5>>^ Há um mal que vi debaixo do sol, semelhante a um erro que procede do governador:

[[v21-10-6]]

^<<v21-10-6,6>>^ a estultícia está posta em grande dignidade, e os ricos estão assentados em lugar humilde.

[[v21-10-7]]

^<<v21-10-7,7>>^ Tenho visto servos montados a cavalo, e príncipes andando a pé como servos.

[[v21-10-8]]

^<<v21-10-8,8>>^ Aquele que abrir uma cova, nela cairá; e quem romper um muro, uma cobra o morderá.

[[v21-10-9]]

^<<v21-10-9,9>>^ Aquele que tira pedras é maltratado por elas, e o que racha lenha corre perigo nisso.

[[v21-10-10]]

^<<v21-10-10,10>>^ Se estiver embotado o ferro, e não se afiar o corte, então se deve pôr mais força; mas a sabedoria é proveitosa para dar prosperidade.

[[v21-10-11]]

^<<v21-10-11,11>>^ Se a cobra morder antes de estar encantada, não há vantagem no encantador.

[[v21-10-12]]

^<<v21-10-12,12>>^ As palavras da boca do sábio são cheias de graça, mas os lábios do tolo o devoram.

[[v21-10-13]]

^<<v21-10-13,13>>^ O princípio das palavras da sua boca é estultícia, e o fim do seu discurso é loucura perversa.

[[v21-10-14]]

^<<v21-10-14,14>>^ O tolo multiplica as palavras, todavia nenhum homem sabe o que há de ser; e quem lhe poderá declarar o que será depois dele?

[[v21-10-15]]

^<<v21-10-15,15>>^ O trabalho do tolo o fatiga, de sorte que não sabe ir à cidade.

[[v21-10-16]]

^<<v21-10-16,16>>^ Ai de ti, ó terra, quando o teu rei é criança, e quando os teus príncipes banqueteiam de manhã!

[[v21-10-17]]

^<<v21-10-17,17>>^ Bem-aventurada tu, ó terra, quando o teu rei é filho de nobres, e quando os teus príncipes comem a tempo, para refazerem as forças, e não para bebedice!

[[v21-10-18]]

^<<v21-10-18,18>>^ Pela preguiça se enfraquece o teto, e pela frouxidão das mãos a casa tem goteiras.

[[v21-10-19]]

^<<v21-10-19,19>>^ Para rir é que se dá banquete, e o vinho alegra a vida; e por tudo o dinheiro responde.

[[v21-10-20]]

^<<v21-10-20,20>>^ Nem ainda no teu pensamento amaldições o rei; nem tampouco na tua recâmara amaldiçoes o rico; porque as aves dos céus levarão a voz, e uma criatura alada dará notícia da palavra.

'''

xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[&#60; Capítulo Anterior] | <<v21-10-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[Próximo Capítulo &#62;]