include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-5-1]]

^<<v21-5-1,1>>^ Guarda o teu pé, quando fores à casa de Deus; porque chegar-se para ouvir é melhor do que oferecer sacrifícios de tolos; pois não sabem que fazem mal.

[[v21-5-2]]

^<<v21-5-2,2>>^ Não te precipites com a tua boca, nem o teu coração se apresse a pronunciar palavra alguma na presença de Deus; porque Deus está no céu, e tu estás sobre a terra; portanto sejam poucas as tuas palavras.

[[v21-5-3]]

^<<v21-5-3,3>>^ Porque, da multidão de trabalhos vêm os sonhos, e da multidão de palavras, a voz do tolo.

[[v21-5-4]]

^<<v21-5-4,4>>^ Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos. O que votares, paga-o.

[[v21-5-5]]

^<<v21-5-5,5>>^ Melhor é que não votes do que votares e não pagares.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não consintas que a tua boca faça pecar a tua carne, nem digas na presença do anjo que foi erro; por que razão se iraria Deus contra a tua voz, e destruiria a obra das tuas mãos?

[[v21-5-7]]

^<<v21-5-7,7>>^ Porque na multidão dos sonhos há vaidades e muitas palavras; mas tu teme a Deus.

[[v21-5-8]]

^<<v21-5-8,8>>^ Se vires em alguma província opressão de pobres, e a perversão violenta do direito e da justiça, não te maravilhes de semelhante caso. Pois quem está altamente colocado tem superior que o vigia; e há mais altos ainda sobre eles.

[[v21-5-9]]

^<<v21-5-9,9>>^ O proveito da terra é para todos; até o rei se serve do campo.

[[v21-5-10]]

^<<v21-5-10,10>>^ Quem ama o dinheiro não se fartará de dinheiro; nem o que ama a riqueza se fartará do ganho; também isso é vaidade.

[[v21-5-11]]

^<<v21-5-11,11>>^ Quando se multiplicam os bens, multiplicam-se também os que comem; e que proveito tem o seu dono senão o de vê-los com os seus olhos?

[[v21-5-12]]

^<<v21-5-12,12>>^ Doce é o sono do trabalhador, quer coma pouco quer muito; mas a saciedade do rico não o deixa dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Há um grave mal que vi debaixo do sol: riquezas foram guardadas por seu dono para o seu próprio dano;

[[v21-5-14]]

^<<v21-5-14,14>>^ e as mesmas riquezas se perderam por qualquer má aventura; e havendo algum filho nada fica na sua mão.

[[v21-5-15]]

^<<v21-5-15,15>>^ Como saiu do ventre de sua mãe, assim também se irá, nu como veio; e nada tomará do seu trabalho, que possa levar na mão.

[[v21-5-16]]

^<<v21-5-16,16>>^ Ora isso é um grave mal; porque justamente como veio, assim há de ir; e que proveito lhe vem de ter trabalhado para o vento,

[[v21-5-17]]

^<<v21-5-17,17>>^ e de haver passado todos os seus dias nas trevas, e de haver padecido muito enfado, enfermidades e aborrecimento?

[[v21-5-18]]

^<<v21-5-18,18>>^ Eis aqui o que eu vi, uma boa e bela coisa: alguém comer e beber, e gozar cada um do bem de todo o seu trabalho, com que se afadiga debaixo do sol, todos os dias da vida que Deus lhe deu; pois esse é o seu quinhão.

[[v21-5-19]]

^<<v21-5-19,19>>^ E quanto ao homem a quem Deus deu riquezas e bens, e poder para desfrutá-los, receber o seu quinhão, e se regozijar no seu trabalho, isso é dom de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ Pois não se lembrará muito dos dias da sua vida; porque Deus lhe enche de alegria o coração.

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]