include::./index.adoc[]

[[v21-7-0]]
=== Eclesiastes, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-7-1]]

^<<v21-7-1,1>>^ Melhor é o bom nome do que o melhor ungüento, e o dia da morte do que o dia do nascimento.

[[v21-7-2]]

^<<v21-7-2,2>>^ Melhor é ir à casa onde há luto do que ir a casa onde há banquete; porque naquela se vê o fim de todos os homens, e os vivos o aplicam ao seu coração.

[[v21-7-3]]

^<<v21-7-3,3>>^ Melhor é a mágoa do que o riso, porque a tristeza do rosto torna melhor o coração.

[[v21-7-4]]

^<<v21-7-4,4>>^ O coração dos sábios está na casa do luto, mas o coração dos tolos na casa da alegria.

[[v21-7-5]]

^<<v21-7-5,5>>^ Melhor é ouvir a repreensão do sábio do que ouvir alguém a canção dos tolos.

[[v21-7-6]]

^<<v21-7-6,6>>^ Pois qual o crepitar dos espinhos debaixo da panela, tal é o riso do tolo; também isso é vaidade.

[[v21-7-7]]

^<<v21-7-7,7>>^ Verdadeiramente a opressão faz endoidecer até o sábio, e a peita corrompe o coração.

[[v21-7-8]]

^<<v21-7-8,8>>^ Melhor é o fim duma coisa do que o princípio; melhor é o paciente do que o arrogante.

[[v21-7-9]]

^<<v21-7-9,9>>^ Não te apresses no teu espírito a irar-te, porque a ira abriga-se no seio dos tolos.

[[v21-7-10]]

^<<v21-7-10,10>>^ Não digas: Por que razão foram os dias passados melhores do que estes; porque não provém da sabedoria esta pergunta.

[[v21-7-11]]

^<<v21-7-11,11>>^ Tão boa é a sabedoria como a herança, e mesmo de mais proveito para os que vêem o sol.

[[v21-7-12]]

^<<v21-7-12,12>>^ Porque a sabedoria serve de defesa, como de defesa serve o dinheiro; mas a excelência da sabedoria é que ela preserva a vida de quem a possui.

[[v21-7-13]]

^<<v21-7-13,13>>^ Considera as obras de Deus; porque quem poderá endireitar o que ele fez torto?

[[v21-7-14]]

^<<v21-7-14,14>>^ No dia da prosperidade regozija-te, mas no dia da adversidade considera; porque Deus fez tanto este como aquele, para que o homem nada descubra do que há de vir depois dele.

[[v21-7-15]]

^<<v21-7-15,15>>^ Tudo isto vi nos dias da minha vaidade: há justo que perece na sua justiça, e há ímpio que prolonga os seus dias na sua maldade.

[[v21-7-16]]

^<<v21-7-16,16>>^ Não sejas demasiadamente justo, nem demasiadamente sábio; por que te destruirias a ti mesmo?

[[v21-7-17]]

^<<v21-7-17,17>>^ Não sejas demasiadamente ímpio, nem sejas tolo; por que morrerias antes do teu tempo?

[[v21-7-18]]

^<<v21-7-18,18>>^ Bom é que retenhas isso, e que também daquilo não retires a tua mão; porque quem teme a Deus escapa de tudo isso.

[[v21-7-19]]

^<<v21-7-19,19>>^ A sabedoria fortalece ao sábio mais do que dez governadores que haja na cidade.

[[v21-7-20]]

^<<v21-7-20,20>>^ Pois não há homem justo sobre a terra, que faça o bem, e nunca peque.

[[v21-7-21]]

^<<v21-7-21,21>>^ Não escutes a todas as palavras que se disserem, para que não venhas a ouvir o teu servo amaldiçoar-te;

[[v21-7-22]]

^<<v21-7-22,22>>^ pois tu sabes também que muitas vezes tu amaldiçoaste a outros.

[[v21-7-23]]

^<<v21-7-23,23>>^ Tudo isto provei-o pela sabedoria; e disse: Far-me-ei sábio; porém a sabedoria ainda ficou longe de mim.

[[v21-7-24]]

^<<v21-7-24,24>>^ Longe está o que já se foi, e profundíssimo; quem o poderá achar?

[[v21-7-25]]

^<<v21-7-25,25>>^ Eu me volvi, e apliquei o meu coração para saber, e inquirir, e buscar a sabedoria e a razão de tudo, e para conhecer que a impiedade é insensatez e que a estultícia é loucura.

[[v21-7-26]]

^<<v21-7-26,26>>^ E eu achei uma coisa mais amarga do que a morte, a mulher cujo coração são laços e redes, e cujas mãos são grilhões; quem agradar a Deus escapará dela; mas o pecador virá a ser preso por ela.

[[v21-7-27]]

^<<v21-7-27,27>>^ Vedes aqui, isto achei, diz o pregador, conferindo uma coisa com a outra para achar a causa;

[[v21-7-28]]

^<<v21-7-28,28>>^ causa que ainda busco, mas não a achei; um homem entre mil achei eu, mas uma mulher entre todas, essa não achei.

[[v21-7-29]]

^<<v21-7-29,29>>^ Eis que isto tão-somente achei: que Deus fez o homem reto, mas os homens buscaram muitos artifícios.

'''

xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[&#60; Capítulo Anterior] | <<v21-7-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[Próximo Capítulo &#62;]