include::./index.adoc[]

[[v21-4-0]]
=== Eclesiastes, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-4-1]]

^<<v21-4-1,1>>^ Depois volvi-me, e atentei para todas as opressões que se fazem debaixo do sol; e eis as lágrimas dos oprimidos, e eles não tinham consolador; do lado dos seus opressores havia poder; mas eles não tinham consolador.

[[v21-4-2]]

^<<v21-4-2,2>>^ Pelo que julguei mais felizes os que já morreram, do que os que vivem ainda.

[[v21-4-3]]

^<<v21-4-3,3>>^ E melhor do que uns e outros é aquele que ainda não é, e que não viu as más obras que se fazem debaixo do sol.

[[v21-4-4]]

^<<v21-4-4,4>>^ Também vi eu que todo trabalho e toda destreza em obras provêm da inveja que o homem tem do seu próximo. Também isso é e vaidade e desejo vão.

[[v21-4-5]]

^<<v21-4-5,5>>^ O tolo cruza as mãos, e come a sua; própria carne.

[[v21-4-6]]

^<<v21-4-6,6>>^ Melhor é um punhado com tranqüilidade do que ambas as mãos cheias com trabalho e vão desejo.

[[v21-4-7]]

^<<v21-4-7,7>>^ Outra vez me volvi, e vi vaidade debaixo do sol.

[[v21-4-8]]

^<<v21-4-8,8>>^ Há um que é só, não tendo parente; não tem filho nem irmão e, contudo, de todo o seu trabalho não há fim, nem os seus olhos se fartam de riquezas. E ele não pergunta: Para quem estou trabalhando e privando do bem a minha alma? Também isso é vaidade a e enfadonha ocupação.

[[v21-4-9]]

^<<v21-4-9,9>>^ Melhor é serem dois do que um, porque têm melhor paga do seu trabalho.

[[v21-4-10]]

^<<v21-4-10,10>>^ Pois se caírem, um levantará o seu companheiro; mas ai do que estiver só, pois, caindo, não haverá outro que o levante.

[[v21-4-11]]

^<<v21-4-11,11>>^ Também, se dois dormirem juntos, eles se aquentarão; mas um só como se aquentará?

[[v21-4-12]]

^<<v21-4-12,12>>^ E, se alguém quiser prevalecer contra um, os dois lhe resistirão; e o cordão de três dobras não se quebra tão depressa.

[[v21-4-13]]

^<<v21-4-13,13>>^ Melhor é o mancebo pobre e sábio do que o rei velho e insensato, que não se deixa mais admoestar,

[[v21-4-14]]

^<<v21-4-14,14>>^ embora tenha saído do cárcere para reinar, ou tenha nascido pobre no seu próprio reino.

[[v21-4-15]]

^<<v21-4-15,15>>^ Vi a todos os viventes que andavam debaixo do sol, e eles estavam com o mancebo, o sucessor, que havia de ficar no lugar do rei.

[[v21-4-16]]

^<<v21-4-16,16>>^ Todo o povo, à testa do qual se achava, era inumerável; contudo os que lhe sucederam não se regozijarão a respeito dele. Na verdade também isso é vaidade e desejo vão.

'''

xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[&#60; Capítulo Anterior] | <<v21-4-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[Próximo Capítulo &#62;]