include::./index.adoc[]

[[v21-11-0]]
=== Eclesiastes, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-11-1]]

^<<v21-11-1,1>>^ Lança o teu pão sobre as águas, porque depois de muitos dias o acharás.

[[v21-11-2]]

^<<v21-11-2,2>>^ Reparte com sete, e ainda até com oito; porque não sabes que mal haverá sobre a terra.

[[v21-11-3]]

^<<v21-11-3,3>>^ Estando as nuvens cheias de chuva, derramam-na sobre a terra. Caindo a árvore para o sul, ou para o norte, no lugar em que a árvore cair, ali ficará.

[[v21-11-4]]

^<<v21-11-4,4>>^ Quem observa o vento, não semeará, e o que atenta para as nuvens não segará.

[[v21-11-5]]

^<<v21-11-5,5>>^ Assim como tu não sabes qual o caminho do vento, nem como se formam os ossos no ventre da que está grávida, assim também não sabes as obras de Deus, que faz todas as coisas.

[[v21-11-6]]

^<<v21-11-6,6>>^ Pela manhã semeia a tua semente, e à tarde não retenhas a tua mão; pois tu não sabes qual das duas prosperará, se esta, se aquela, ou se ambas serão, igualmente boas.

[[v21-11-7]]

^<<v21-11-7,7>>^ Doce é a luz, e agradável é aos olhos ver o sol.

[[v21-11-8]]

^<<v21-11-8,8>>^ Se, pois, o homem viver muitos anos, regozije-se em todos eles; contudo lembre-se dos dias das trevas, porque hão de ser muitos. Tudo quanto sucede é vaidade.

[[v21-11-9]]

^<<v21-11-9,9>>^ Alegra-te, mancebo, na tua mocidade, e anime-te o teu coração nos dias da tua mocidade, e anda pelos caminhos do teu coração, e pela vista dos teus olhos; sabe, porém, que por todas estas coisas Deus te trará a juízo.

[[v21-11-10]]

^<<v21-11-10,10>>^ Afasta, pois, do teu coração o desgosto, remove da tua carne o mal; porque a mocidade e a aurora da vida são vaidade.

'''

xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[&#60; Capítulo Anterior] | <<v21-11-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[Próximo Capítulo &#62;]