include::./index.adoc[]

[[v21-8-0]]
=== Eclesiastes, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-8-1]]

^<<v21-8-1,1>>^ Quem é como o sábio? e quem sabe a interpretação das coisas? A sabedoria do homem faz brilhar o seu rosto, e com ela a dureza do seu rosto se transforma.

[[v21-8-2]]

^<<v21-8-2,2>>^ Eu digo: Observa o mandamento do rei, e isso por causa do juramento a Deus.

[[v21-8-3]]

^<<v21-8-3,3>>^ Não te apresses a sair da presença dele; nem persistas em alguma coisa má; porque ele faz tudo o que lhe agrada.

[[v21-8-4]]

^<<v21-8-4,4>>^ Porque a palavra do rei é suprema; e quem lhe dirá: que fazes?

[[v21-8-5]]

^<<v21-8-5,5>>^ Quem guardar o mandamento não experimentará nenhum mal; e o coração do sábio discernirá o tempo e o juízo.

[[v21-8-6]]

^<<v21-8-6,6>>^ Porque para todo propósito há tempo e juízo; porquanto a miséria do homem pesa sobre ele.

[[v21-8-7]]

^<<v21-8-7,7>>^ Porque não sabe o que há de suceder; pois quem lho dará a entender como há de ser?

[[v21-8-8]]

^<<v21-8-8,8>>^ Nenhum homem há que tenha domínio sobre o espírito, para o reter; nem que tenha poder sobre o dia da morte; nem há licença em tempo de guerra; nem tampouco a impiedade livrará aquele que a ela está entregue.

[[v21-8-9]]

^<<v21-8-9,9>>^ Tudo isto tenho observado enquanto aplicava o meu coração a toda obra que se faz debaixo do sol; tempo há em que um homem tem domínio sobre outro homem para o seu próprio dano.

[[v21-8-10]]

^<<v21-8-10,10>>^ Vi também os ímpios sepultados, os que antes entravam e saíam do lugar santo; e foram esquecidos na cidade onde haviam assim procedido; também isso é vaidade.

[[v21-8-11]]

^<<v21-8-11,11>>^ Porquanto não se executa logo o juízo sobre a má obra, o coração dos filhos dos homens está inteiramente disposto para praticar o mal.

[[v21-8-12]]

^<<v21-8-12,12>>^ Ainda que o pecador faça o mal cem vezes, e os dias se lhe prolonguem, contudo eu sei com certeza que bem sucede aos que temem a Deus, porque temem diante dele;

[[v21-8-13]]

^<<v21-8-13,13>>^ ao ímpio, porém, não irá bem, e ele não prolongará os seus dias, que são como a sombra; porque ele não teme diante de Deus.

[[v21-8-14]]

^<<v21-8-14,14>>^ Ainda há outra vaidade que se faz sobre a terra: há justos a quem sucede segundo as obras dos ímpios, e há ímpios a quem sucede segundo as obras dos justos. Eu disse que também isso é vaidade.

[[v21-8-15]]

^<<v21-8-15,15>>^ Exalto, pois, a alegria, porquanto o homem nenhuma coisa melhor tem debaixo do sol do que comer, beber e alegrar-se; porque isso o acompanhará no seu trabalho nos dias da sua vida que Deus lhe dá debaixo do sol.

[[v21-8-16]]

^<<v21-8-16,16>>^ Quando apliquei o meu coração a conhecer a sabedoria, e a ver o trabalho que se faz sobre a terra &#123;pois homens há que nem de dia nem de noite conseguem dar sono aos seus olhos&#125;,

[[v21-8-17]]

^<<v21-8-17,17>>^ então contemplei toda obra de Deus, e vi que o homem não pode compreender a obra que se faz debaixo do sol; pois por mais que o homem trabalhe para a descobrir, não a achará; embora o sábio queira conhecê-la, nem por isso a poderá compreender.

'''

xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[&#60; Capítulo Anterior] | <<v21-8-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[Próximo Capítulo &#62;]