include::./index.adoc[]

[[v21-6-0]]
=== Eclesiastes, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-6-1]]

^<<v21-6-1,1>>^ Há um mal que tenho visto debaixo do sol, e que pesa muito sobre o homem:

[[v21-6-2]]

^<<v21-6-2,2>>^ um homem a quem Deus deu riquezas, bens e honra, de maneira que nada lhe falta de tudo quanto ele deseja, contudo Deus não lhe dá poder para daí comer, antes o estranho lho come; também isso é vaidade e grande mal.

[[v21-6-3]]

^<<v21-6-3,3>>^ Se o homem gerar cem filhos, e viver muitos anos, de modo que os dias da sua vida sejam muitos, porém se a sua alma não se fartar do bem, e além disso não tiver sepultura, digo que um aborto é melhor do que ele;

[[v21-6-4]]

^<<v21-6-4,4>>^ porquanto debalde veio, e em trevas se vai, e de trevas se cobre o seu nome;

[[v21-6-5]]

^<<v21-6-5,5>>^ e ainda que nunca viu o sol, nem o conheceu, mais descanso tem do que o tal;

[[v21-6-6]]

^<<v21-6-6,6>>^ e embora vivesse duas vezes mil anos, mas não gozasse o bem. Não vão todos para um mesmo lugar?

[[v21-6-7]]

^<<v21-6-7,7>>^ Todo o trabalho do homem é para a sua boca, e contudo não se satisfaz o seu apetite.

[[v21-6-8]]

^<<v21-6-8,8>>^ Pois, que vantagem tem o sábio sobre o tolo? e que tem o pobre que sabe andar perante os vivos?

[[v21-6-9]]

^<<v21-6-9,9>>^ Melhor é a vista dos olhos do que o vaguear da cobiça; também isso é vaidade, e desejo vão.

[[v21-6-10]]

^<<v21-6-10,10>>^ Seja qualquer o que for, já há muito foi chamado pelo seu nome; e sabe-se que é homem; e ele não pode contender com o que é mais forte do que ele.

[[v21-6-11]]

^<<v21-6-11,11>>^ Visto que as muitas palavras aumentam a vaidade, que vantagem tira delas o homem?

[[v21-6-12]]

^<<v21-6-12,12>>^ Porque, quem sabe o que é bom nesta vida para o homem, durante os poucos dias da sua vida vã, os quais gasta como sombra? pois quem declarará ao homem o que será depois dele debaixo do sol?

'''

xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[&#60; Capítulo Anterior] | <<v21-6-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[Próximo Capítulo &#62;]