include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v21-1-1]]

^<<v21-1-1,1>>^ Palavras do pregador, filho de Davi, rei em Jerusalém.

[[v21-1-2]]

^<<v21-1-2,2>>^ Vaidade de vaidades, diz o pregador; vaidade de vaidades, tudo é vaidade.

[[v21-1-3]]

^<<v21-1-3,3>>^ Que proveito tem o homem, de todo o seu trabalho, com que se afadiga debaixo do sol?

[[v21-1-4]]

^<<v21-1-4,4>>^ Uma geração vai-se, e outra geração vem, mas a terra permanece para sempre.

[[v21-1-5]]

^<<v21-1-5,5>>^ O sol nasce, e o sol se põe, e corre de volta ao seu lugar donde nasce.

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento vai para o sul, e faz o seu giro vai para o norte; volve-se e revolve-se na sua carreira, e retoma os seus circuitos.

[[v21-1-7]]

^<<v21-1-7,7>>^ Todos os ribeiros vão para o mar, e contudo o mar não se enche; ao lugar para onde os rios correm, para ali continuam a correr.

[[v21-1-8]]

^<<v21-1-8,8>>^ Todas as coisas estão cheias de cansaço; ninguém o pode exprimir: os olhos não se fartam de ver, nem os ouvidos se enchem de ouvir.

[[v21-1-9]]

^<<v21-1-9,9>>^ O que tem sido, isso é o que há de ser; e o que se tem feito, isso se tornará a fazer; nada há que seja novo debaixo do sol.

[[v21-1-10]]

^<<v21-1-10,10>>^ Há alguma coisa de que se possa dizer: Voê, isto é novo? ela já existiu nos séculos que foram antes de nós.

[[v21-1-11]]

^<<v21-1-11,11>>^ Já não há lembrança das gerações passadas; nem das gerações futuras haverá lembrança entre os que virão depois delas.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o pregador, fui rei sobre Israel em Jerusalém.

[[v21-1-13]]

^<<v21-1-13,13>>^ E apliquei o meu coração a inquirir e a investigar com sabedoria a respeito de tudo quanto se faz debaixo do céu; essa enfadonha ocupação deu Deus aos filhos dos homens para nela se exercitarem.

[[v21-1-14]]

^<<v21-1-14,14>>^ Atentei para todas as obras que se e fazem debaixo do sol; e eis que tudo era vaidade e desejo vão.

[[v21-1-15]]

^<<v21-1-15,15>>^ O que é torto não se pode endireitar; o que falta não se pode enumerar.

[[v21-1-16]]

^<<v21-1-16,16>>^ Falei comigo mesmo, dizendo: Eis que eu me engrandeci, e sobrepujei em sabedoria a todos os que houve antes de mim em Jerusalém; na verdade, tenho tido larga experiência da sabedoria e do conhecimento.

[[v21-1-17]]

^<<v21-1-17,17>>^ E apliquei o coração a conhecer a sabedoria e a conhecer os desvarios e as loucuras; e vim a saber que também isso era desejo vão.

[[v21-1-18]]

^<<v21-1-18,18>>^ Porque na muita sabedoria há muito enfado; e o que aumenta o conhecimento aumenta a tristeza.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]