include::./index.adoc[]

[[v6-1-0]]
=== Josué, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-1-1]]

^<<v6-1-1,1>>^ Depois da morte de Moisés, servo do Senhor, falou o Senhor a Josué, filho de Num, servidor de Moisés, dizendo:

[[v6-1-2]]

^<<v6-1-2,2>>^ Moisés, meu servo, é morto; levanta-te pois agora, passa este Jordão, tu e todo este povo, para a terra que eu dou aos filhos de Israel.

[[v6-1-3]]

^<<v6-1-3,3>>^ Todo lugar que pisar a planta do vosso pé, vo-lo dei, como eu disse a Moisés.

[[v6-1-4]]

^<<v6-1-4,4>>^ Desde o deserto e este Líbano, até o grande rio, o rio Eufrates, toda a terra dos heteus, e até o grande mar para o poente do sol, será o vosso termo.

[[v6-1-5]]

^<<v6-1-5,5>>^ Ninguém te poderá resistir todos os dias da tua vida. Como fui com Moisés, assim serei contigo; não te deixarei, nem te desampararei.

[[v6-1-6]]

^<<v6-1-6,6>>^ Esforça-te, e tem bom ânimo, porque tu farás a este povo herdar a terra que jurei a seus pais lhes daria.

[[v6-1-7]]

^<<v6-1-7,7>>^ Tão-somente esforça-te e tem mui bom ânimo, cuidando de fazer conforme toda a lei que meu servo Moisés te ordenou; não te desvies dela, nem para a direita nem para a esquerda, a fim de que sejas bem sucedido por onde quer que andares.

[[v6-1-8]]

^<<v6-1-8,8>>^ Não se aparte da tua boca o livro desta lei, antes medita nele dia e noite, para que tenhas cuidado de fazer conforme tudo quanto nele está escrito; porque então farás prosperar o teu caminho, e serás bem sucedido.

[[v6-1-9]]

^<<v6-1-9,9>>^ Não to mandei eu? Esforça-te, e tem bom ânimo; não te atemorizes, nem te espantes; porque o Senhor teu Deus está contigo, por onde quer que andares.

[[v6-1-10]]

^<<v6-1-10,10>>^ Então Josué deu esta ordem aos oficiais do povo:

[[v6-1-11]]

^<<v6-1-11,11>>^ Passai pelo meio do arraial, e ordenai ao povo, dizendo: Provede-vos de mantimentos, porque dentro de três dias haveis de atravessar este Jordão, a fim de que entreis para tomar posse da terra que o Senhor vosso Deus vos dá para a possuirdes.

[[v6-1-12]]

^<<v6-1-12,12>>^ E disse Josué aos rubenitas, aos gaditas, e à meia tribo de Manassés:

[[v6-1-13]]

^<<v6-1-13,13>>^ Lembrai-vos da palavra que vos mandou Moisés, servo do Senhor, dizendo: O Senhor vosso Deus vos dá descanso, e vos dá esta terra.

[[v6-1-14]]

^<<v6-1-14,14>>^ Vossas mulheres, vossos pequeninos e vosso gado fiquem na terra que Moisés vos deu desta banda do Jordão; porém vós, todos os homens valorosos, passareis armados adiante de vossos irmãos e os ajudareis;

[[v6-1-15]]

^<<v6-1-15,15>>^ até que o Senhor tenha dado descanso: a vossos irmãos, assim como vo-lo deu a vós, e eles também tenham possuído a terra que o Senhor vosso Deus lhes dá; então tornareis para a terra da vossa herança, e a possuireis, terra que Moisés, servo do Senhor, vos deu além do Jordão, para o nascente do sol.

[[v6-1-16]]

^<<v6-1-16,16>>^ Então responderam a Josué, dizendo: Tudo quanto nos ordenaste faremos, e aonde quer que nos enviares iremos.

[[v6-1-17]]

^<<v6-1-17,17>>^ Como em tudo ouvimos a Moisés, assim te ouviremos a ti; tão-somente seja o Senhor teu Deus contigo, como foi com Moisés.

[[v6-1-18]]

^<<v6-1-18,18>>^ Quem quer que se rebelar contra as tuas ordens, e não ouvir as tuas palavras em tudo quanto lhe mandares, será morto. Tão-somente esforça-te, e tem bom ânimo.

'''

xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[&#60; Capítulo Anterior] | <<v6-1-0,Topo>> | xref:006-josue/006-josue-002.adoc#v6-2-0[Próximo Capítulo &#62;]