include::./index.adoc[]

[[v6-5-0]]
=== Josué, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-5-1]]

^<<v6-5-1,1>>^ Quando, pois, todos os reis dos amorreus que estavam ao oeste do Jordão, e todos os reis dos cananeus que estavam ao lado do mar, ouviram que o Senhor tinha secado as águas do Jordão de diante dos filhos de Israel, até que passassem, derreteu-se-lhes o coração, e não houve mais ânimo neles, por causa dos filhos de Israel.

[[v6-5-2]]

^<<v6-5-2,2>>^ Naquele tempo disse o Senhor a Josué: Faze facas de pederneira, e circuncida segunda vez aos filhos de Israel.

[[v6-5-3]]

^<<v6-5-3,3>>^ Então Josué fez facas de pederneira, e circuncidou aos filhos de Israel em Gibeáte-Haaralote.

[[v6-5-4]]

^<<v6-5-4,4>>^ Esta é a razão por que Josué os circuncidou: todo o povo que tinha saído do Egito, os homens, todos os homens de guerra, já haviam morrido no deserto, pelo caminho, depois que saíram do Egito.

[[v6-5-5]]

^<<v6-5-5,5>>^ Todos estes que saíram estavam circuncidados, mas nenhum dos que nasceram no deserto, pelo caminho, depois de terem saído do Egito, havia sido circuncidado.

[[v6-5-6]]

^<<v6-5-6,6>>^ Pois quarenta anos andaram os filhos de Israel pelo deserto, até se acabar toda a nação, isto é, todos os homens de guerra que saíram do Egito, e isso porque não obedeceram à voz do Senhor; aos quais o Senhor tinha jurado que não lhes havia de deixar ver a terra que, com juramento, prometera a seus pais nos daria, terra que mana leite e mel.

[[v6-5-7]]

^<<v6-5-7,7>>^ Mas em lugar deles levantou seus filhos; a estes Josué circuncidou, porquanto estavam incircuncisos, porque não os haviam circuncidado pelo caminho.

[[v6-5-8]]

^<<v6-5-8,8>>^ E depois que foram todos circuncidados, permaneceram no seu lugar no arraial, até que sararam.

[[v6-5-9]]

^<<v6-5-9,9>>^ Disse então o Senhor a Josué: Hoje revolvi de sobre vós o opróbrio do Egito; pelo que se chama aquele lugar: Gilgal, até o dia de hoje.

[[v6-5-10]]

^<<v6-5-10,10>>^ Estando, pois, os filhos de Israel acampados em Gilgal, celebraram a páscoa no dia catorze do mês, à tarde, nas planícies de Jericó.

[[v6-5-11]]

^<<v6-5-11,11>>^ E, ao outro dia depois da páscoa, nesse mesmo dia, comeram, do produto da terra, pães ázimos e espigas tostadas.

[[v6-5-12]]

^<<v6-5-12,12>>^ E no dia depois de terem comido do produto da terra, cessou o maná, e os filhos de Israel não o tiveram mais; porém nesse ano comeram dos produtos da terra de Canaã.

[[v6-5-13]]

^<<v6-5-13,13>>^ Ora, estando Josué perto de Jericó, levantou os olhos, e olhou; e eis que estava em pé diante dele um homem que tinha na mão uma espada nua. Chegou-se Josué a ele, e perguntou-lhe: És tu por nós, ou pelos nossos adversários?

[[v6-5-14]]

^<<v6-5-14,14>>^ Respondeu ele: Não; mas venho agora como príncipe do exército do Senhor. Então Josué, prostrando-se com o rosto em terra, o adorou e perguntou-lhe: Que diz meu Senhor ao seu servo?

[[v6-5-15]]

^<<v6-5-15,15>>^ Então respondeu o príncipe do exército do Senhor a Josué: Tira os sapatos dos pés, porque o lugar em que estás é santo. E Josué assim fez:

'''

xref:006-josue/006-josue-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-josue/006-josue-006.adoc#v6-6-0[Próximo Capítulo &#62;]