include::./index.adoc[]

[[v6-16-0]]
=== Josué, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-16-1]]

^<<v6-16-1,1>>^ Saiu depois a sorte dos filhos de José, a qual, partindo do Jordão, na altura de Jericó, junto às águas de Jericó ao oriente, se estende pelo deserto que sobe de Jericó através da região montanhosa até Betel;

[[v6-16-2]]

^<<v6-16-2,2>>^ de Betel vai para Luz, e passa ao termo dos arquitas, até Atarote;

[[v6-16-3]]

^<<v6-16-3,3>>^ desce para o ocidente até o termo dos jafletitas, até o termo de Bete-Horom de baixo, e daí até Gezer, indo terminar no mar.

[[v6-16-4]]

^<<v6-16-4,4>>^ Assim receberam a sua herança os filhos de José, Manassés e Efraim.

[[v6-16-5]]

^<<v6-16-5,5>>^ Ora, fica o termo dos filhos de Efraim, segundo as suas famílias, como se segue: para o oriente o termo da sua herança é Atarote-Adar até Bete-Horom de cima;

[[v6-16-6]]

^<<v6-16-6,6>>^ sai este termo para o ocidente junto a Micmetá ao norte e vira para o oriente até Taanate-Siló, margeando-a a leste de Janoa;

[[v6-16-7]]

^<<v6-16-7,7>>^ desce de Janoa a Atarote e a Naarate, toca em Jericó e termina no Jordão:

[[v6-16-8]]

^<<v6-16-8,8>>^ De Tapua estende-se para o ocidente até o ribeiro de Caná, e vai terminar no mar. Esta é a herança da tribo dos filhos de Efraim, segundo as suas famílias,

[[v6-16-9]]

^<<v6-16-9,9>>^ juntamente com as cidades que se separaram para os filhos de Efraim no meio da herança dos filhos de Manassés, todas as cidades e suas aldeias.

[[v6-16-10]]

^<<v6-16-10,10>>^ E não expulsaram aos cananeus que habitavam em Gezer; mas os cananeus ficaram habitando no meio dos efraimitas até o dia de hoje, e tornaram-se servos, sujeitos ao trabalho forçado.

'''

xref:006-josue/006-josue-015.adoc#v6-15-0[&#60; Capítulo Anterior] | <<v6-16-0,Topo>> | xref:006-josue/006-josue-017.adoc#v6-17-0[Próximo Capítulo &#62;]