include::./index.adoc[]

[[v6-14-0]]
=== Josué, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-14-1]]

^<<v6-14-1,1>>^ Estas, pois, são as heranças que os filhos de Israel receberam na terra de Canaã, as quais Eleazar, o sacerdote, e Josué, filho de Num, e os cabeças das casas paternas das tribos dos filhos de Israel lhes repartiram.

[[v6-14-2]]

^<<v6-14-2,2>>^ Foi feita por sorte a partilha da herança entre as nove tribos e meia, como o Senhor ordenara por intermédio de Moisés.

[[v6-14-3]]

^<<v6-14-3,3>>^ Porquanto às duas tribos e meia Moisés já dera herança além do Jordão; mas aos levitas não deu herança entre eles.

[[v6-14-4]]

^<<v6-14-4,4>>^ Os filhos de José eram duas tribos, Manassés e Efraim; e aos levitas não se deu porção na terra, senão cidades em que habitassem e os arrabaldes delas para o seu gado e para os seus bens. :

[[v6-14-5]]

^<<v6-14-5,5>>^ Como o Senhor ordenara a Moisés, assim fizeram os filhos de Israel e repartiram a terra.

[[v6-14-6]]

^<<v6-14-6,6>>^ Então os filhos de Judá chegaram a Josué em Gilgal; e Calebe, filho de Jefoné o quenezeu, lhe disse: Tu sabes o que o Senhor falou a Moisés, homem de Deus, em Cades-Barnéia, a respeito de mim e de ti.

[[v6-14-7]]

^<<v6-14-7,7>>^ Quarenta anos tinha eu quando Moisés, servo do Senhor, me enviou de Cades-Barnéia para espiar a terra, e eu lhe trouxe resposta, como sentia no meu coração.

[[v6-14-8]]

^<<v6-14-8,8>>^ Meus irmãos que subiram comigo fizeram derreter o coração o povo; mas eu perseverei em seguir ao Senhor meu Deus.

[[v6-14-9]]

^<<v6-14-9,9>>^ Naquele dia Moisés jurou, dizendo: Certamente a terra em que pisou o teu pé te será por herança a ti e a teus filhos para sempre, porque perseveraste em seguir ao Senhor meu Deus.

[[v6-14-10]]

^<<v6-14-10,10>>^ E agora eis que o Senhor, como falou, me conservou em vida estes quarenta e cinco anos, desde o tempo em que o Senhor falou esta palavra a Moisés, andando Israel ainda no deserto; e eis que hoje tenho já oitenta e cinco anos;

[[v6-14-11]]

^<<v6-14-11,11>>^ ainda hoje me acho tão forte como no dia em que Moisés me enviou; qual era a minha força então, tal é agora a minha força, tanto para a guerra como para sair e entrar.

[[v6-14-12]]

^<<v6-14-12,12>>^ Agora, pois, dá-me este monte de que o Senhor falou naquele dia; porque tu ouviste, naquele dia, que estavam ali os anaquins, bem como cidades grandes e fortificadas. Porventura o Senhor será comigo para os expulsar, como ele disse.

[[v6-14-13]]

^<<v6-14-13,13>>^ Então Josué abençoou a Calebe, filho de Jefoné, e lhe deu Hebrom em herança.

[[v6-14-14]]

^<<v6-14-14,14>>^ Portanto Hebrom ficou sendo herança de Calebe, filho de Jefoné o quenezeu, até o dia de hoje, porquanto perseverara em seguir ao Senhor Deus de Israel.

[[v6-14-15]]

^<<v6-14-15,15>>^ Ora, o nome de Hebrom era outrora Quiriate-Arba, porque Arba era o maior homem entre os anaquins. E a terra repousou da guerra.

'''

xref:006-josue/006-josue-013.adoc#v6-13-0[&#60; Capítulo Anterior] | <<v6-14-0,Topo>> | xref:006-josue/006-josue-015.adoc#v6-15-0[Próximo Capítulo &#62;]