include::./index.adoc[]

[[v6-9-0]]
=== Josué, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-9-1]]

^<<v6-9-1,1>>^ Depois sucedeu que, ouvindo isto todos os reis que estavam além do Jordão, na região montanhosa, na baixada e em toda a costa do grande mar, defronte do Líbano, os heteus, os amorreus, os cananeus, os perizeus, os heveus, e os jebuseus

[[v6-9-2]]

^<<v6-9-2,2>>^ se ajuntaram de comum acordo para pelejar contra Josué e contra Israel.

[[v6-9-3]]

^<<v6-9-3,3>>^ Ora, os moradores de Gibeão, ouvindo o que Josué fizera a Jericó e a Ai.

[[v6-9-4]]

^<<v6-9-4,4>>^ usaram de astúcia: foram e se fingiram embaixadores, tomando sacos velhos sobre os seus jumentos, e odres de vinho velhos, rotos e recosidos,

[[v6-9-5]]

^<<v6-9-5,5>>^ tendo nos seus pés sapatos velhos e remendados, e trajando roupas velhas; e todo o pão que traziam para o caminho era seco e bolorento.

[[v6-9-6]]

^<<v6-9-6,6>>^ E vieram a Josué, ao arraial em Gilgal, e disseram a ele e aos homens de Israel: Somos vindos duma terra longínqua; fazei, pois, agora pacto conosco.

[[v6-9-7]]

^<<v6-9-7,7>>^ Responderam os homens de Israel a estes heveus: Bem pode ser que habiteis no meio de nós; como pois faremos pacto convosco?

[[v6-9-8]]

^<<v6-9-8,8>>^ Então eles disseram a Josué: Nós somos teus servos. Ao que lhes perguntou Josué: Quem sois vós? e donde vindes?

[[v6-9-9]]

^<<v6-9-9,9>>^ Responderam-lhe: Teus servos vieram duma terra mui distante, por causa do nome do Senhor teu Deus, porquanto ouvimos a sua fama, e tudo o que fez no Egito,

[[v6-9-10]]

^<<v6-9-10,10>>^ e tudo o que fez aos dois reis dos amorreus, que estavam além do Jordão, a Siom, rei de Hesbom, e a Ogue, rei de Basã, que estava em Astarote.

[[v6-9-11]]

^<<v6-9-11,11>>^ Pelo que nossos anciãos e todos os moradores da nossa terra nos falaram, dizendo: Tomai nas mãos provisão para o caminho, e ide-lhes ao encontro, e dizei-lhes: Nós somos vossos servos; fazei, pois, agora pacto conosco.

[[v6-9-12]]

^<<v6-9-12,12>>^ Este nosso pão tomamo-lo quente das nossas casas para nossa provisão, no dia em que saímos para vir ter convosco, e ei-lo aqui agora seco e bolorento;

[[v6-9-13]]

^<<v6-9-13,13>>^ estes odres, que enchemos de vinho, eram novos, e ei-los aqui já rotos; e esta nossa roupa e nossos sapatos já envelheceram em razão do mui longo caminho.

[[v6-9-14]]

^<<v6-9-14,14>>^ Então os homens de Israel tomaram da provisão deles, e não pediram conselho ao Senhor.

[[v6-9-15]]

^<<v6-9-15,15>>^ Assim Josué fez paz com eles; também fez um pacto com eles, prometendo poupar-lhes a vida; e os príncipes da congregação lhes prestaram juramento.

[[v6-9-16]]

^<<v6-9-16,16>>^ Três dias depois de terem feito pacto com eles, ouviram que eram vizinhos e que moravam no meio deles.

[[v6-9-17]]

^<<v6-9-17,17>>^ Tendo partido os filhos de Israel, chegaram ao terceiro dia às cidades deles, que eram Gibeom, Cefira, Beerote e Quiriate-Jearir.

[[v6-9-18]]

^<<v6-9-18,18>>^ Mas os filhos de Israel não os mataram, porquanto os príncipes da congregação lhes haviam prestado juramento pelo Senhor, o Deus de Israel; pelo que toda a congregação murmurava contra os príncipes.

[[v6-9-19]]

^<<v6-9-19,19>>^ Mas os príncipes disseram a toda a congregação: Nós lhes prestamos juramento pelo Senhor, o Deus de Israel, e agora não lhes podemos tocar.

[[v6-9-20]]

^<<v6-9-20,20>>^ Isso cumpriremos para com eles, poupando-lhes a vida, para que não haja ira sobre nós, por causa do juramento que lhes fizemos.

[[v6-9-21]]

^<<v6-9-21,21>>^ Disseram, pois, os príncipes: Vivam. Assim se tornaram rachadores de lenha e tiradores de água para toda a congregação, como os príncipes lhes disseram.

[[v6-9-22]]

^<<v6-9-22,22>>^ Então Josué os chamou, e lhes disse: Por que nos enganastes, dizendo: Mui longe de vós habitamos, morando vós no meio de nós?

[[v6-9-23]]

^<<v6-9-23,23>>^ Agora, pois, sois malditos, e dentre vós nunca deixará de haver servos, rachadores de lenha e tiradores de água para a casa do meu Deus.

[[v6-9-24]]

^<<v6-9-24,24>>^ Respondendo a Josué, disseram: Porquanto foi anunciado aos teus servos que o Senhor teu Deus ordenou a Moisés, seu servo, que vos desse toda esta terra, e destruísse todos os seus moradores diante de vós, temíamos muito pelas nossas vidas por causa de vós, e fizemos isso.

[[v6-9-25]]

^<<v6-9-25,25>>^ E eis que agora estamos na tua mão; faze aquilo que te pareça bom e reto que se nos faça.

[[v6-9-26]]

^<<v6-9-26,26>>^ Assim pois ele lhes fez, e livrou-os das mãos dos filhos de Israel, de sorte que estes não os mataram.

[[v6-9-27]]

^<<v6-9-27,27>>^ Mas, naquele dia, Josué os fez rachadores de lenha e tiradores de água para a congregação e para o altar do Senhor, no lugar que ele escolhesse, como ainda o são.

'''

xref:006-josue/006-josue-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-josue/006-josue-010.adoc#v6-10-0[Próximo Capítulo &#62;]