include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-8-1]]

^<<v6-8-1,1>>^ Então disse o Senhor a Josué: Não temas, e não te espantes; toma contigo toda a gente de guerra, levanta-te, e sobe a Ai. Olha que te entreguei na tua mão o rei de Ai, o seu povo, a sua cidade e a sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Farás pois a Ai e a seu rei, como fizeste a Jericó e a seu rei; salvo que para vós tomareis os seus despojos, e o seu gado. Põe emboscadas à cidade, por detrás dela.

[[v6-8-3]]

^<<v6-8-3,3>>^ Então Josué levantou-se, com toda a gente de guerra, para subir contra Ai; e escolheu Josué trinta mil homens valorosos, e enviou-os de noite.

[[v6-8-4]]

^<<v6-8-4,4>>^ E deu-lhes ordem, dizendo: Ponde-vos de emboscada contra a cidade, por detrás dela; não vos distancieis muito da cidade, mas estai todos vós apercebidos.

[[v6-8-5]]

^<<v6-8-5,5>>^ Mas eu e todo o povo que está comigo nos aproximaremos da cidade; e quando eles nos saírem ao encontro, como dantes, fugiremos diante deles.

[[v6-8-6]]

^<<v6-8-6,6>>^ E eles sairão atrás de nós, até que os tenhamos afastado da cidade, pois dirão: Fogem diante de nós como dantes. Assim fugiremos diante deles;

[[v6-8-7]]

^<<v6-8-7,7>>^ e vós saireis da emboscada, e tomareis a cidade, porque o Senhor vosso Deus vo-la entregará nas mãos.

[[v6-8-8]]

^<<v6-8-8,8>>^ Logo que tiverdes tomado a cidade, pôr-lhe-eis fogo, fazendo conforme a palavra do Senhor; olhai que vo-lo tenho mandado.

[[v6-8-9]]

^<<v6-8-9,9>>^ Assim Josué os enviou, e eles se foram à emboscada, colocando-se entre Betel e Ai, ao ocidente de Ai; porém Josué passou aquela noite no meio do povo.

[[v6-8-10]]

^<<v6-8-10,10>>^ Levantando-se Josué de madrugada, passou o povo em revista; então subiu, com os anciãos de Israel, adiante do povo contra Ai.

[[v6-8-11]]

^<<v6-8-11,11>>^ Todos os homens armados que estavam com ele subiram e, aproximando-se pela frente da cidade, acamparam-se ao norte de Ai, havendo um vale entre eles e Ai.

[[v6-8-12]]

^<<v6-8-12,12>>^ Tomou também cerca de cinco mil homens, e pô-los de emboscada entre Betel e Ai, ao ocidente da cidade.

[[v6-8-13]]

^<<v6-8-13,13>>^ Assim dispuseram o povo, todo o arraial ao norte da cidade, e a sua emboscada ao ocidente da cidade. Marchou Josué aquela noite até o meio do vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ Quando o rei de Ai viu isto, ele e todo o seu povo se apressaram, levantando-se de madrugada, e os homens da cidade saíram ao encontro de Israel ao combate, ao lugar determinado, defronte da planície; mas ele não sabia que se achava uma emboscada contra ele atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué, pois, e todo o Israel fingiram-se feridos diante deles, e fugiram pelo caminho do deserto:

[[v6-8-16]]

^<<v6-8-16,16>>^ Portanto, todo o povo que estava na cidade foi convocado para os perseguir; e seguindo eles após Josué, afastaram-se da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Nem um só homem ficou em Ai, nem em Betel, que não saísse após Israel; assim deixaram a cidade aberta, e seguiram a Israel:

[[v6-8-18]]

^<<v6-8-18,18>>^ Então o Senhor disse a Josué: Estende para Ai a lança que tens na mão; porque eu te entregarei. E Josué estendeu para a cidade a lança que estava na sua mão.

[[v6-8-19]]

^<<v6-8-19,19>>^ E, tendo ele estendido a mão, os que estavam de emboscada se levantaram apressadamente do seu lugar e, correndo, entraram na cidade, e a tomaram; e, apressando-se, puseram fogo à cidade.

[[v6-8-20]]

^<<v6-8-20,20>>^ Nisso, olhando os homens de Ai para trás, viram a fumaça da cidade, que subia ao céu, e não puderam fugir nem para uma parte nem para outra, porque o povo que fugia para o deserto se tornou contra eles.

[[v6-8-21]]

^<<v6-8-21,21>>^ E vendo Josué e todo o Israel que a emboscada tomara a cidade, e que a fumaça da cidade subia, voltaram e feriram os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ Também aqueles que estavam na cidade lhes saíram ao encontro, e assim os de Ai ficaram no meio dos israelitas, estando estes de uma e de outra parte; e feriram-nos, de sorte que não deixaram ficar nem escapar nenhum deles.

[[v6-8-23]]

^<<v6-8-23,23>>^ Mas ao rei de Ai tomaram vivo, e o trouxeram a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Quando os israelitas acabaram de matar todos os moradores de Ai no campo, no deserto para onde os tinham seguido, e havendo todos caído ao fio da espada até serem consumidos, então todo o Israel voltou para Ai e a feriu a fio de espada.

[[v6-8-25]]

^<<v6-8-25,25>>^ Ora, todos os que caíram naquele dia, assim homens como mulheres, foram doze mil, isto é, todos os de Ai.

[[v6-8-26]]

^<<v6-8-26,26>>^ Pois Josué não retirou a mão, que estendera com a lança, até destruir totalmente a todos os moradores de Ai.

[[v6-8-27]]

^<<v6-8-27,27>>^ Tão-somente os israelitas tomaram para si o gado e os despojos da cidade, conforme a palavra que o Senhor ordenara a Josué:

[[v6-8-28]]

^<<v6-8-28,28>>^ Queimou pois Josué a Ai, e a tornou num perpétuo montão de ruínas, como o é até o dia de hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ Ao rei de Ai enforcou num madeiro, deixando-o ali até a tarde. Ao pôr do sol, por ordem de Josué, tiraram do madeiro o cadáver, lançaram-no à porta da cidade e levantaram sobre ele um grande montão de pedras, que permanece até o dia de hoje.

[[v6-8-30]]

^<<v6-8-30,30>>^ Então Josué edificou um altar ao Senhor Deus de Israel, no monte Ebal,

[[v6-8-31]]

^<<v6-8-31,31>>^ como Moisés, servo do Senhor, ordenara aos filhos de Israel, conforme o que está escrito no livro da lei de Moisés, a saber: um altar de pedras brutas, sobre as quais não se levantara ferramenta; e ofereceram sobre ele holocaustos ao Senhor, e sacrificaram ofertas pacíficas.

[[v6-8-32]]

^<<v6-8-32,32>>^ Também ali, na presença dos filhos de Israel, escreveu em pedras uma cópia da lei de Moisés, a qual este escrevera.

[[v6-8-33]]

^<<v6-8-33,33>>^ E todo o Israel, tanto o estrangeiro como o natural, com os seus anciãos, oficiais e juízes, estava de um e de outro lado da arca, perante os levitas sacerdotes que levavam a arca do pacto do Senhor; metade deles em frente do monte Gerizim, e a outra metade em frente do monte Ebal, como Moisés, servo do Senhor, dantes ordenara, para que abençoassem o povo de Israel.

[[v6-8-34]]

^<<v6-8-34,34>>^ Depois leu em alta voz todas as palavras da lei, a bênção e a maldição, conforme tudo o que está escrito no livro da lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ Palavra nenhuma houve, de tudo o que Moisés ordenara, que Josué não lesse perante toda a congregação de Israel, e as mulheres, e os pequeninos, e os estrangeiros que andavam no meio deles.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]