include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-11-1]]

^<<v6-11-1,1>>^ Quando Jabim, rei de Hazor, ouviu isso, enviou mensageiros a Jobabe, rei de Madom, e ao rei de Sinrom, e ao rei de Acsafe,

[[v6-11-2]]

^<<v6-11-2,2>>^ e aos reis que estavam ao norte, na região montanhosa, na Arabá ao sul de Quinerote, na baixada, e nos planaltos de Dor ao ocidente;

[[v6-11-3]]

^<<v6-11-3,3>>^ ao cananeu do oriente e do ocidente, ao amorreu, ao heteu, ao perizeu, ao jebuseu na região montanhosa, e ao heveu ao pé de Hermom na terra de Mizpá.

[[v6-11-4]]

^<<v6-11-4,4>>^ Saíram pois eles, com todos os seus exércitos, muito povo, em multidão como a areia que está na praia do mar, e muitíssimos cavalos e carros.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos esses reis, reunindo-se, vieram e juntos se acamparam às águas de Merom, para pelejarem contra Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ Disse o Senhor a Josué: Não os temas, pois amanhã a esta hora eu os entregarei todos mortos diante de Israel. Os seus cavalos jarretarás, e os seus carros queimarás a fogo.

[[v6-11-7]]

^<<v6-11-7,7>>^ Josué, pois, com toda a gente de guerra, sobreveio-lhes de repente às águas de Merom, e deu sobre eles.

[[v6-11-8]]

^<<v6-11-8,8>>^ E o Senhor os entregou na mão dos israelitas, que os feriram e os perseguiram até a grande Sidom, e até Misrefote-Maim, e até o vale de Mizpe ao oriente; e feriram-nos até não lhes deixar nem sequer um.

[[v6-11-9]]

^<<v6-11-9,9>>^ Fez-lhes Josué como o Senhor lhe dissera: os seus cavalos jarretou, e os seus carros queimou a fogo.

[[v6-11-10]]

^<<v6-11-10,10>>^ Naquele tempo Josué voltou e tomou também a Hazor, e feriu à espada ao seu rei, porquanto Hazor dantes era a cabeça de todos estes reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ E passaram ao fio da espada a todos os que nela havia, destruindo-os totalmente; nada restou do que tinha fôlego; e a Hazor ele queimou a fogo.

[[v6-11-12]]

^<<v6-11-12,12>>^ Josué, pois, tomou todas as cidades desses reis, e a eles mesmos, e os passou ao fio da espada, destruindo-os totalmente, como ordenara Moisés, servo do Senhor.

[[v6-11-13]]

^<<v6-11-13,13>>^ Contudo, quanto às cidades que se achavam sobre os seus altos, a nenhuma delas queimou Israel, salvo somente a Hazor; a essa Josué queimou.

[[v6-11-14]]

^<<v6-11-14,14>>^ Mas todos os despojos dessas cidades, e o gado, tomaram-nos os filhos de Israel como presa para si; porém feriram ao fio da espada todos os homens, até os destruírem; nada deixaram do que tinha fôlego de vida.

[[v6-11-15]]

^<<v6-11-15,15>>^ Como o Senhor ordenara a Moisés, seu servo, assim Moisés ordenou a Josué, e assim Josué o fez; não deixou de fazer coisa alguma de tudo o que o Senhor ordenara a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ Assim Josué tomou toda aquela terra, a região montanhosa, todo o Negebe, e toda a terra de Gósem e a baixada, e a Arabá, e a região montanhosa de Israel com a sua baixada,

[[v6-11-17]]

^<<v6-11-17,17>>^ desde o monte Halaque, que sobe a Seir, até Baal-Gade, no vale do Líbano, ao pé do monte Hermom; também tomou todos os seus reis, e os feriu e os matou.

[[v6-11-18]]

^<<v6-11-18,18>>^ Por muito tempo Josué fez guerra contra todos esses reis.

[[v6-11-19]]

^<<v6-11-19,19>>^ Não houve cidade que fizesse paz com os filhos de Israel, senão os heveus, moradores de Gibeão; a todas tomaram à força de armas.

[[v6-11-20]]

^<<v6-11-20,20>>^ Porquanto do Senhor veio o endurecimento dos seus corações para saírem à guerra contra Israel, a fim de que fossem destruídos totalmente, e não achassem piedade alguma, mas fossem exterminados, como o Senhor tinha ordenado a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Naquele tempo veio Josué, e exterminou os anaquins da região montanhosa de Hebrom, de Debir, de Anabe, de toda a região montanhosa de Judá, e de toda a região montanhosa de Israel; Josué os destruiu totalmente com as suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Não foi deixado nem sequer um dos anaquins na terra dos filhos de Israel; somente ficaram alguns em Gaza, em Gate, e em Asdode.

[[v6-11-23]]

^<<v6-11-23,23>>^ Assim Josué tomou toda esta terra conforme tudo o que o Senhor tinha dito a Moisés; e Josué a deu em herança a Israel, pelas suas divisões, segundo as suas tribos; e a terra repousou da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]