include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-15-1]]

^<<v6-15-1,1>>^ A sorte que coube à tribo dos filhos de Judá, segundo as suas famílias, se estende até o termo de Edom, até o deserto de Zim para o sul, na extremidade do lado meridional

[[v6-15-2]]

^<<v6-15-2,2>>^ O seu termo meridional, partindo da extremidade do Mar Salgado, da baía que dá para o sul,

[[v6-15-3]]

^<<v6-15-3,3>>^ estende-se para o sul, até a subida de Acrabim, passa a Zim, sobe pelo sul de Cades-Barnéia, passa por Hezrom, sobe a Adar, e vira para Carca;

[[v6-15-4]]

^<<v6-15-4,4>>^ daí passa a Azmom, chega até o ribeiro do Egito, e por ele vai até o mar. Este será o vosso termo meridional.

[[v6-15-5]]

^<<v6-15-5,5>>^ O termo oriental é o Mar Salgado, até a foz do Jordão. O termo setentrional, partindo da baía do mar na foz do Jordão,

[[v6-15-6]]

^<<v6-15-6,6>>^ sobe até Bete-Hogla, passa ao norte de Bete-Arabá, e sobe até a pedra de Boã, filho de Rúben;

[[v6-15-7]]

^<<v6-15-7,7>>^ sobe mais este termo a Debir, desde o vale de Acor, indo para o norte em direção a Gilgal, a qual está defronte da subida de Adumim, que se acha ao lado meridional do ribeiro; então continua este termo até as águas de En-Semes, e os seus extremos chegam a En-Rogel;

[[v6-15-8]]

^<<v6-15-8,8>>^ sobe ainda pelo vale de Ben-Hinom, até a saliência meridional do monte jebuseu &#123;isto é, Jerusalém&#125;; sobe ao cume do monte que está fronteiro ao vale de Hinom para o ocidente, na extremidade do vale dos refains para o norte;

[[v6-15-9]]

^<<v6-15-9,9>>^ do cume do monte se estende até a fonte das águas de Neftoa e, seguindo até as cidades do monte de Efrom, estende-se ainda até Baalá &#123;esta é Quiriate-Jearim&#125; ;

[[v6-15-10]]

^<<v6-15-10,10>>^ de Baalá este termo volta para o ocidente, até o monte Seir, passa ao lado do monte Jearim da banda do norte &#123;este é Quesalom&#125; , desce a Bete-Semes e passa por Timna;

[[v6-15-11]]

^<<v6-15-11,11>>^ segue mais este termo até o lado de Ecrom para o norte e, indo para Siquerom e passando o monte de Baalá, chega a Jabneel; e assim este termo finda no mar.

[[v6-15-12]]

^<<v6-15-12,12>>^ O termo ocidental é o mar grande. São esses os termos dos filhos de Judá ao redor, segundo as suas famílias.

[[v6-15-13]]

^<<v6-15-13,13>>^ Deu-se, porém, a Calebe, filho de Jefoné, uma porção no meio dos filhos de Judá, conforme a ordem do Senhor a Josué, a saber, Quiriate-Arba, que é Hebrom &#123;Arba era o pai de Anaque&#125;.

[[v6-15-14]]

^<<v6-15-14,14>>^ E Calebe expulsou dali os três filhos de Anaque: Sesai, Aimã e Talmai, descendentes de Anaque.

[[v6-15-15]]

^<<v6-15-15,15>>^ Dali subiu contra os habitantes de Debir. Ora, o nome de Debir era dantes Quiriate-Sefer.

[[v6-15-16]]

^<<v6-15-16,16>>^ Disse então Calebe: A quem atacar Quiriate-Sefer e a tomar, darei a minha filha Acsa por mulher.

[[v6-15-17]]

^<<v6-15-17,17>>^ Tomou-a, pois, Otniel, filho de Quenaz, irmão de Calebe; e este lhe deu a sua filha Acsa por mulher.

[[v6-15-18]]

^<<v6-15-18,18>>^ Estando ela em caminho para a casa de Otniel, persuadiu-o que pedisse um campo ao pai dela. E quando ela saltou do jumento, Calebe lhe perguntou: Que é que tens?

[[v6-15-19]]

^<<v6-15-19,19>>^ Respondeu ela: Dá-me um presente; porquanto me deste terra no Negebe, dá-me também fontes d'água. Então lhe deu as fontes superiores e as fontes inferiores.

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta é a herança da tribo dos filhos de Judá, segundo as suas famílias.

[[v6-15-21]]

^<<v6-15-21,21>>^ As cidades pertencentes à tribo dos filhos de Judá, no extremo sul, para o lado de Edom, são: Cabzeel, Eder, Jagur,

[[v6-15-22]]

^<<v6-15-22,22>>^ Quiná, Dimona, Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ Quedes, Hazor, Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ Zife, Telem, Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ Hazor-Hadada, Queriote-Hezrom &#123;que é Hazor&#125;,

[[v6-15-26]]

^<<v6-15-26,26>>^ Amã, Sema, Molada,

[[v6-15-27]]

^<<v6-15-27,27>>^ Hazar-Gada, Hesmom, Bete-Pelete,

[[v6-15-28]]

^<<v6-15-28,28>>^ Hazar-Sual, Berseba, Biziotiá,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baalá, Iim, Ezem,

[[v6-15-30]]

^<<v6-15-30,30>>^ Eltolade, Quesil, Horma,

[[v6-15-31]]

^<<v6-15-31,31>>^ Ziclague, Madmana, Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ Lebaote, Silim, Aim e Rimom; ao todo, vinte e nove cidades, e as suas aldeias.

[[v6-15-33]]

^<<v6-15-33,33>>^ Na baixada: Estaol, Zorá, Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ Zanoa, En-Ganim, Tapua, Enã,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarmute, Adulão, Socó, Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ Saraim, Aditaim, Gedera e Gederotaim; catorze cidades e as suas aldeias.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zenã, Hadasa, Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ Dileã, Mizpe, Jocteel,

[[v6-15-39]]

^<<v6-15-39,39>>^ Laquis, Bozcate, Erglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ Cabom, Laamás, Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ Gederote, Bete-Dagom, Naamá e Maqueda; dezesseis cidades e as suas aldeias.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libna, Eter, Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ Iftá, Asná, Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ Queila, Aczibe e Maressa; nove cidades e as suas aldeias.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ecrom, com as suas vilas e aldeias;

[[v6-15-46]]

^<<v6-15-46,46>>^ desde Ecrom até o mar, todas as que estão nas adjacências de Asdode, e as suas aldeias;

[[v6-15-47]]

^<<v6-15-47,47>>^ Asdode, com as suas vilas e aldeias; Gaza, com as suas vilas e aldeias, até o rio do Egito, e o mar grande, que serve de termo.

[[v6-15-48]]

^<<v6-15-48,48>>^ E na região montanhosa: Samir, Jatir, Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ Daná, Quiriate-Saná &#123;que é Debir&#125;,

[[v6-15-50]]

^<<v6-15-50,50>>^ Anabe, Estemó, Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ Gósem Holom e Gilo; onze cidades e as suas aldeias.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arabe, Dumá, Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ Janim, Bete-Tapua, Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ Hunta, Quiriate-Arba &#123;que é Hebrom&#125; e Zior; nove cidades e as suas aldeias.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maom, Carmelo, Zife, Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ Jizreel, Jocdeão, Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ Caim, Gibeá e Timna; dez cidades e as suas aldeias.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halul, Bete-Zur, Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ Maarate, Bete-Anote e Eltecom; seis cidades e as suas aldeias.

[[v6-15-60]]

^<<v6-15-60,60>>^ Quiriate-Baal &#123;que é Quiriate-Jearim&#125; e Rabá; duas cidades e as suas aldeias.

[[v6-15-61]]

^<<v6-15-61,61>>^ No deserto: Bete-Arabá, Midim, Secaca,

[[v6-15-62]]

^<<v6-15-62,62>>^ Nibsã, a cidade do Sal e En-Gedi; seis cidades e as suas aldeias.

[[v6-15-63]]

^<<v6-15-63,63>>^ Não puderam, porém, os filhos de Judá expulsar os jebuseus que habitavam em Jerusalém; assim ficaram habitando os jebuseus com os filhos de Judá em Jerusalém, até o dia de hoje.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]