include::./index.adoc[]

[[v6-19-0]]
=== Josué, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-19-1]]

^<<v6-19-1,1>>^ Saiu a segunda sorte a Simeão, isto é, à tribo dos filhos de Simeão, segundo as suas famílias; e foi a sua herança no meio da herança dos filhos de Judá.

[[v6-19-2]]

^<<v6-19-2,2>>^ Tiveram, pois, na sua herança: Berseba, Seba, Molada,

[[v6-19-3]]

^<<v6-19-3,3>>^ Hazar-Sual, Balá, Ezem,

[[v6-19-4]]

^<<v6-19-4,4>>^ Eltolade, Betul, Horma,

[[v6-19-5]]

^<<v6-19-5,5>>^ Ziclague, Bete-Marcabote, Hazar-Susa,

[[v6-19-6]]

^<<v6-19-6,6>>^ Bete-Lebaote e Saruém; treze cidades e as suas aldeias.

[[v6-19-7]]

^<<v6-19-7,7>>^ Aim, Rimom, Eter e Asã; quatro cidades e as suas aldeias;

[[v6-19-8]]

^<<v6-19-8,8>>^ e todas as aldeias que havia em redor dessas cidades, até Baalate-Ber, que é Ramá do sul. Essa é a herança da tribo dos filhos de Simeão, segundo as suas famílias.

[[v6-19-9]]

^<<v6-19-9,9>>^ Ora, do quinhão dos filhos de Judá tirou-se a herança dos filhos de Simeão, porquanto a porção dos filhos de Judá era demasiadamente grande para eles; pelo que os filhos de Simeão receberam herança no meio da herança deles.

[[v6-19-10]]

^<<v6-19-10,10>>^ Surgiu a terceira sorte aos filhos de Zebulom, segundo as suas famílias. Vai o termo da sua herança até Saride;

[[v6-19-11]]

^<<v6-19-11,11>>^ sobe para o ocidente até Marala, estende-se até Dabesete, e chega até o ribeiro que está defronte de Jocneão;

[[v6-19-12]]

^<<v6-19-12,12>>^ de Saride vira para o oriente, para o nascente do sol, até o termo de Quislote-Tabor, estende-se a Daberate, e vai subindo a Jafia;

[[v6-19-13]]

^<<v6-19-13,13>>^ dali passa para o oriente a Gate-Hefer, a Ete-Cazim, chegando a Rimom-Metoar e virando-se para Neá;

[[v6-19-14]]

^<<v6-19-14,14>>^ vira ao norte para Hanatom, e chega ao vale de Iftael;

[[v6-19-15]]

^<<v6-19-15,15>>^ e Catate, Naalal, Sinrom, Idala e Belém; doze cidades e as suas aldeias.

[[v6-19-16]]

^<<v6-19-16,16>>^ Essa é a herança dos filhos de Zebulom, segundo as suas famílias, essas cidades e as suas aldeias.

[[v6-19-17]]

^<<v6-19-17,17>>^ A quarta sorte saiu aos filhos de Issacar, segundo as suas famílias.

[[v6-19-18]]

^<<v6-19-18,18>>^ Vai o seu termo até Jizreel, Quesulote, Suném.

[[v6-19-19]]

^<<v6-19-19,19>>^ Hafaraim, Siom, Anaarate,

[[v6-19-20]]

^<<v6-19-20,20>>^ Rabite, Quisiom, Abes,

[[v6-19-21]]

^<<v6-19-21,21>>^ Remete, En-Ganim, En-Hada e Bete-Pazez,

[[v6-19-22]]

^<<v6-19-22,22>>^ estendendo-se este termo até Tabor, Saazima e Bete-Semes; e vai terminar no Jordão; dezesseis cidades e as suas aldeias.

[[v6-19-23]]

^<<v6-19-23,23>>^ Essa é a herança da tribo dos filhos de Issacar, segundo as suas famílias, essas cidades e as suas aldeias.

[[v6-19-24]]

^<<v6-19-24,24>>^ Saiu a quinta sorte à tribo dos filhos de Aser, segundo as suas famílias.

[[v6-19-25]]

^<<v6-19-25,25>>^ O seu termo inclui Helcate, Hali, Bétem, Acsafe,

[[v6-19-26]]

^<<v6-19-26,26>>^ Alameleque, Amade e Misal; estende-se para o ocidente até Carmelo e Sior-Libnate;

[[v6-19-27]]

^<<v6-19-27,27>>^ vira para o nascente do sol a Bete-Dagom; chega a Zebulom e ao vale de Iftael para o norte, até Bete-Emeque e Neiel; estende-se pela esquerda até Cabul,

[[v6-19-28]]

^<<v6-19-28,28>>^ Ebrom, Reobe, Hamom e Caná, até a grande Sidom;

[[v6-19-29]]

^<<v6-19-29,29>>^ vira para Ramá, e para a cidade fortificada de Tiro, desviando-se então para Hosa, donde vai até o mar; Maalabe, Aczibe,

[[v6-19-30]]

^<<v6-19-30,30>>^ Umá, Afeca e Reobe; ao todo, vinte e duas cidades e as suas aldeias.

[[v6-19-31]]

^<<v6-19-31,31>>^ Essa é a herança da tribo dos filhos de Aser, segundo as suas famílias, essas cidades e as suas aldeias.

[[v6-19-32]]

^<<v6-19-32,32>>^ Saiu a sexta sorte aos filhos de Naftali, segundo as suas famílias.

[[v6-19-33]]

^<<v6-19-33,33>>^ Vai o seu termo desde Helefe e desde o carvalho em Zaananim, e Adâmi-Nequebe e Jabneel, até Lacum, terminando no Jordão;

[[v6-19-34]]

^<<v6-19-34,34>>^ vira para o ocidente até Aznote-Tabor, e dali passa a Hucoque; chega a Zebulom, da banda do sul, e a Aser, da banda do ocidente, e a Judá, à margem do Jordão, para o oriente.

[[v6-19-35]]

^<<v6-19-35,35>>^ E são as cidades fortificadas: Zidim, Zer, Hamate, Racate, Quinerete,

[[v6-19-36]]

^<<v6-19-36,36>>^ Adama, Ramá, Hazor,

[[v6-19-37]]

^<<v6-19-37,37>>^ Quedes, Edrei, En-Hazor,

[[v6-19-38]]

^<<v6-19-38,38>>^ Irom, Migdal-El, Horem, Bete-Anate e Bete-Semes; dezenove cidades e as suas aldeias.

[[v6-19-39]]

^<<v6-19-39,39>>^ Essa é a herança da tribo dos filhos de Naftali, segundo as suas famílias, essas cidades e as suas aldeias.

[[v6-19-40]]

^<<v6-19-40,40>>^ A sétima sorte saiu à tribo dos filhos de Dã, segundo as suas famílias.

[[v6-19-41]]

^<<v6-19-41,41>>^ O termo da sua herança inclui: Zorá, Estaol, Ir-Semes,

[[v6-19-42]]

^<<v6-19-42,42>>^ Saalabim, Aijalom, Itla,

[[v6-19-43]]

^<<v6-19-43,43>>^ Elom, Timnate, Ecrom,

[[v6-19-44]]

^<<v6-19-44,44>>^ Elteque, Gibetom, Baalate,

[[v6-19-45]]

^<<v6-19-45,45>>^ Jeúde, Bene-Beraque, Gate-Rimom,

[[v6-19-46]]

^<<v6-19-46,46>>^ Me-Jarcom e Racom, com o território defronte de Jope.

[[v6-19-47]]

^<<v6-19-47,47>>^ Saiu, porém, pequena o território dos filhos de Dã; pelo que os filhos de Dã subiram, pelejaram contra Lesem e a tomaram; feriram-na ao fio da espada, tomaram posse dela e habitaram-na; e a Lesem chamaram Dã, conforme o nome de Dã, seu pai.

[[v6-19-48]]

^<<v6-19-48,48>>^ Essa é a herança da tribo dos filhos de Dã, segundo as suas famílias, essas cidades e as suas aldeias.

[[v6-19-49]]

^<<v6-19-49,49>>^ Tendo os filhos de Israel acabado de repartir a terra em herança segundo os seus termos, deram a Josué, filho de Num, herança no meio deles.

[[v6-19-50]]

^<<v6-19-50,50>>^ Segundo a ordem do Senhor lhe deram a cidade que pediu, Timnate-Sera, na região montanhosa de Efraim; e ele reedificou a cidade, e habitou nela.

[[v6-19-51]]

^<<v6-19-51,51>>^ Essas são as heranças que Eleazar, o sacerdote, e Josué, filho de Num, e os cabeças das casas paternas nas tribos dos filhos de Israel repartiram em herança por sorte em Siló, perante o Senhor, à porta da tenda da revelação. E assim acabaram de repartir a terra.

'''

xref:006-josue/006-josue-018.adoc#v6-18-0[&#60; Capítulo Anterior] | <<v6-19-0,Topo>> | xref:006-josue/006-josue-020.adoc#v6-20-0[Próximo Capítulo &#62;]