include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-13-1]]

^<<v6-13-1,1>>^ Era Josué já velho e avançado em anos, quando lhe disse o Senhor: Já estás velho e avançado em anos, e ainda fica muitíssima terra para se possuir.

[[v6-13-2]]

^<<v6-13-2,2>>^ A terra que ainda fica é esta: todas as regiões dos filisteus, bem como todas as dos gesureus,

[[v6-13-3]]

^<<v6-13-3,3>>^ desde Sior, que está defronte do Egito, até o termo de Ecrom para o norte, que se tem como pertencente aos cananeus; os cinco chefes dos filisteus; o gazeu, o asdodeu, o asqueloneu, o giteu, e o ecroneu; também os aveus;

[[v6-13-4]]

^<<v6-13-4,4>>^ no sul toda a terra, dos cananeus, e Meara, que pertence aos sidônios, até Afeca, até o termo dos amorreus;

[[v6-13-5]]

^<<v6-13-5,5>>^ como também a terra dos Gebalitas, e todo o Líbano para o nascente do sol, desde Baal-Gade, ao pé do monte Hermom, até a entrada de Hamate;

[[v6-13-6]]

^<<v6-13-6,6>>^ todos os habitantes da região montanhosa desde o Líbano até Misrefote-Maim, a saber, todos os sidônios. Eu os lançarei de diante dos filhos de Israel; tão-somente reparte a terra a Israel por herança, como já te mandei.

[[v6-13-7]]

^<<v6-13-7,7>>^ Reparte, pois, agora esta terra por herança às nove tribos, e à meia tribo de Manassés.

[[v6-13-8]]

^<<v6-13-8,8>>^ Com a outra meia tribo os rubenitas e os gaditas já haviam recebido a sua herança do Jordão para o oriente, a qual Moisés, servo do Senhor, lhes tinha dado:

[[v6-13-9]]

^<<v6-13-9,9>>^ desde Aroer, que está à borda do vale do Arnom, e a cidade que está no meio do vale, e todo o planalto de Medeba até Dibom;

[[v6-13-10]]

^<<v6-13-10,10>>^ e todas as cidades de Siom, rei dos amorreus, que reinou em Hesbom, até o termo dos amonitas;

[[v6-13-11]]

^<<v6-13-11,11>>^ e Gileade, e o território dos gesureus e dos maacateus, e todo o monte Hermom, e toda a Basã até Salca;

[[v6-13-12]]

^<<v6-13-12,12>>^ todo o reino de Ogue em Basã, que reinou em Astarote e em Edrei &#123;ele era dos refains que ficaram&#125;; pois que Moisés os feriu e expulsou.

[[v6-13-13]]

^<<v6-13-13,13>>^ Contudo os filhos de Israel não expulsaram os gesureus nem os maacateus, os quais ficaram habitando no meio de Israel até o dia de hoje.

[[v6-13-14]]

^<<v6-13-14,14>>^ Tão-somente à tribo de Levi não deu herança; as ofertas queimadas ao Senhor, Deus de Israel, são a sua herança, como lhe tinha dito.

[[v6-13-15]]

^<<v6-13-15,15>>^ Assim Moisés deu herança à tribo dos filhos de Rúben conforme as suas famílias.

[[v6-13-16]]

^<<v6-13-16,16>>^ E foi o seu território desde Aroer, que está à borda do vale do _, e a cidade que está no meio do vale, e todo o planalto junto a Medeba;

[[v6-13-17]]

^<<v6-13-17,17>>^ Hesbom, e todas as suas cidades que estão no planalto; Dibom, Bamote-Baal e Bete-Baal-Meom;

[[v6-13-18]]

^<<v6-13-18,18>>^ Jaza, Quedemote e Mefaate;

[[v6-13-19]]

^<<v6-13-19,19>>^ Quiriataim, Sibma e Zerete-Saar, no monte do vale;

[[v6-13-20]]

^<<v6-13-20,20>>^ Bete-Peor, as faldas de Pisga e Bete-Jesimote;

[[v6-13-21]]

^<<v6-13-21,21>>^ todas as cidades do planalto, e todo o reino de Siom, rei dos amorreus, que reinou em Hesbom, a quem Moisés feriu juntamente com os príncipes de Midiã: Evi, Requem, Zur, Hur e Reba, príncipes de Siom, que moravam naquela terra.

[[v6-13-22]]

^<<v6-13-22,22>>^ Também ao adivinho Balaão, filho de Beor, os filhos de Israel mataram à espada, juntamente com os demais que por eles foram mortos.

[[v6-13-23]]

^<<v6-13-23,23>>^ E ficou sendo o Jordão o termo dos filhos de Rúben. Essa região, com as suas cidades e aldeias, foi a herança dos filhos de Rúben, segundo as suas famílias.

[[v6-13-24]]

^<<v6-13-24,24>>^ Também deu Moisés herança à tribo de Gade, aos filhos de Gade, segundo as suas famílias.

[[v6-13-25]]

^<<v6-13-25,25>>^ E foi o seu território Jazer, e todas as cidades de Gileade, e metade da terra dos amonitas, até Aroer, que está defronte de Rabá;

[[v6-13-26]]

^<<v6-13-26,26>>^ e desde Hesbom até Ramá-Mizpe, e Betonim, e desde Maanaim até o termo de Debir;

[[v6-13-27]]

^<<v6-13-27,27>>^ e no vale, Bete-Arã, Bete-Ninra, Sucote e Zafom, resto do reino de Siom, rei de Hesbom, tendo o Jordão por termo, até a extremidade do mar de Quinerete, do Jordão para o oriente.

[[v6-13-28]]

^<<v6-13-28,28>>^ Essa região, com as suas cidades e aldeias, foi a herança dos filhos da Gade, segundo as suas famílias.

[[v6-13-29]]

^<<v6-13-29,29>>^ Também deu Moisés herança à meia tribo de Manassés; a qual foi repartida à meia tribo dos filhos de Manassés segundo as suas famílias.

[[v6-13-30]]

^<<v6-13-30,30>>^ Foi o seu território desde Maanaim; toda a Basã, todo o reino de Ogue, rei de Basã, e todas as aldeias de Jair, que estão em Basã, sessenta ao todo;

[[v6-13-31]]

^<<v6-13-31,31>>^ e metade de Gileade, e Astarote, e Edrei, cidades do reino de Ogue, em Basã, foram para os filhos de Maquir, filho de Manassés, isto é, para a metade dos filhos de Maquir, segundo as suas famílias.

[[v6-13-32]]

^<<v6-13-32,32>>^ Isso é o que Moisés repartiu em herança nas planícies de Moabe, do Jordão para o oriente, na altura de Jericó.

[[v6-13-33]]

^<<v6-13-33,33>>^ Contudo, à tribo de Levi Moisés não deu herança; o Senhor, Deus de Israel, é a sua herança, como lhe tinha dito.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]