include::./index.adoc[]

[[v6-17-0]]
=== Josué, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-17-1]]

^<<v6-17-1,1>>^ Também coube sorte à tribo de Manassés, porquanto era o primogênito de José. Quanto a Maquir, o primogênito de Manassés, pai de Gileade, porquanto era homem de guerra, obtivera Gileade e Basã.

[[v6-17-2]]

^<<v6-17-2,2>>^ Também os outros filhos de Manassés tiveram a sua parte, segundo as suas famílias, a saber: os filhos de Abiezer, os filhos de Heleque, os filhos de Asriel, os filhos de Siquém, os filhos de Hefer, e os filhos de Semida. Esses são os filhos de Manassés, filho de José, segundo as suas famílias.

[[v6-17-3]]

^<<v6-17-3,3>>^ Zelofeade, porém, filho de Hefer, filho de Gileade, filho de Maquir, filho de Manassés, não teve filhos, mas só filhas; e estes são os nomes de suas filhas: Macla, Noa, Hogla, Milca e Tirza.

[[v6-17-4]]

^<<v6-17-4,4>>^ Estas, pois, se apresentaram diante de Eleazar, o sacerdote, e diante de Josué, filho de Num, e diante dos príncipes, dizendo: O Senhor ordenou a Moisés que se nos desse herança no meio de nossos irmãos. Pelo que se lhes deu herança no meio dos irmãos de seu pai, conforme a ordem do Senhor.

[[v6-17-5]]

^<<v6-17-5,5>>^ E couberam a Manassés dez quinhões, afora a terra de Gileade e Basã, que está além do Jordão;

[[v6-17-6]]

^<<v6-17-6,6>>^ porque as filhas de Manassés possuíram herança entre os filhos dele; e a terra de Gileade coube aos outros filhos de Manassés.

[[v6-17-7]]

^<<v6-17-7,7>>^ Ora, o termo de Manassés vai desde Aser até Micmetá, que está defronte de Siquém; e estende-se pela direita até os moradores de En-Tapua.

[[v6-17-8]]

^<<v6-17-8,8>>^ A terra de Tapua ficou pertencendo a Manassés; porém Tapua, junto ao termo de Manassés, pertencia aos filhos de Efraim .

[[v6-17-9]]

^<<v6-17-9,9>>^ Então desce este termo ao ribeiro de Caná; a Efraim couberam as cidades ao sul do ribeiro no meio das cidades de Manassés; o termo de Manassés está ao norte do ribeiro, e vai até o mar.

[[v6-17-10]]

^<<v6-17-10,10>>^ Ao sul a terra é de Efraim, e ao norte de Manassés, sendo o mar o seu termo. Estendem-se ao norte até Aser, e ao oriente até Issacar

[[v6-17-11]]

^<<v6-17-11,11>>^ Porque em Issacar e em Aser couberam a Manassés Bete-Seã e suas vilas, Ibleão e suas vilas, os habitantes de Dor e suas vilas, os habitantes de En-Dor e suas vilas, os habitantes de Taanaque e suas vilas, e os habitantes de Megido e suas vilas, com os seus três outeiros.

[[v6-17-12]]

^<<v6-17-12,12>>^ Contudo os filhos de Manassés não puderam expulsar os habitantes daquelas cidades, porquanto os cananeus persistiram em habitar naquela terra.

[[v6-17-13]]

^<<v6-17-13,13>>^ Mas quando os filhos de Israel se tornaram fortes, sujeitaram os cananeus a trabalhos forçados, porém não os expulsaram de todo.

[[v6-17-14]]

^<<v6-17-14,14>>^ Então os filhos de José falaram a Josué, dizendo: Por que me deste por herança apenas uma sorte e um quinhão, sendo eu um povo numeroso, porquanto o Senhor até aqui me tem abençoado?

[[v6-17-15]]

^<<v6-17-15,15>>^ Respondeu-lhes Josué: Se és povo numeroso, sobe ao bosque, e corta para ti lugar ali na terra dos perizeus e dos refains, desde que a região montanhosa de Efraim te é estreita demais.

[[v6-17-16]]

^<<v6-17-16,16>>^ Tornaram os filhos de José: A região montanhosa não nos bastaria; além disso todos os cananeus que habitam na terra do vale têm carros de ferro, tanto os de Bete-Seã e das suas vilas, como os que estão no vale de Jizreel.

[[v6-17-17]]

^<<v6-17-17,17>>^ Então Josué falou a casa de José, isto é, a Efraim e a Manassés, dizendo: Povo numeroso és tu, e tens grande força; não terás uma sorte apenas;

[[v6-17-18]]

^<<v6-17-18,18>>^ porém a região montanhosa será tua; ainda que é bosque, cortá-lo-ás, e as suas extremidades serão tuas; porque expulsarás os cananeus, não obstante terem eles carros de ferro e serem fortes:

'''

xref:006-josue/006-josue-016.adoc#v6-16-0[&#60; Capítulo Anterior] | <<v6-17-0,Topo>> | xref:006-josue/006-josue-018.adoc#v6-18-0[Próximo Capítulo &#62;]