include::./index.adoc[]

[[v6-2-0]]
=== Josué, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-2-1]]

^<<v6-2-1,1>>^ De Sitim Josué, filho de Num, enviou secretamente dois homens como espias, dizendo-lhes: Ide reconhecer a terra, particularmente a Jericó. Foram pois, e entraram na casa duma prostituta, que se chamava Raabe, e pousaram ali.

[[v6-2-2]]

^<<v6-2-2,2>>^ Então deu-se notícia ao rei de Jericó, dizendo: Eis que esta noite vieram aqui uns homens dos filhos de Israel, para espiar a terra.

[[v6-2-3]]

^<<v6-2-3,3>>^ Pelo que o rei de Jericó mandou dizer a Raabe: Faze sair os homens que vieram a ti e entraram na tua casa, porque vieram espiar toda a terra.

[[v6-2-4]]

^<<v6-2-4,4>>^ Mas aquela mulher, tomando os dois homens, os escondeu, e disse: é verdade que os homens vieram a mim, porém eu não sabia donde eram;

[[v6-2-5]]

^<<v6-2-5,5>>^ e aconteceu que, havendo-se de fechar a porta, sendo já escuro, aqueles homens saíram. Não sei para onde foram; ide após eles depressa, porque os alcançareis.

[[v6-2-6]]

^<<v6-2-6,6>>^ Ela, porém, os tinha feito subir ao eirado, e os tinha escondido entre as canas do linho que pusera em ordem sobre o eirado.

[[v6-2-7]]

^<<v6-2-7,7>>^ Assim foram esses homens após eles pelo caminho do Jordão, até os vaus; e, logo que saíram, fechou-se a porta.

[[v6-2-8]]

^<<v6-2-8,8>>^ E, antes que os espias se deitassem, ela subiu ao eirado a ter com eles,

[[v6-2-9]]

^<<v6-2-9,9>>^ e disse-lhes: Bem sei que o Senhor vos deu esta terra, e que o pavor de vós caiu sobre nós, e que todos os moradores da terra se derretem diante de vós.

[[v6-2-10]]

^<<v6-2-10,10>>^ Porque temos ouvido que o Senhor secou as águas do Mar Vermelho diante de vós, quando saístes do Egito, e também o que fizestes aos dois reis dos amorreus, Siom e Ogue, que estavam além de Jordão, os quais destruístes totalmente.

[[v6-2-11]]

^<<v6-2-11,11>>^ Quando ouvimos isso, derreteram-se os nossos corações, e em ninguém mais há ânimo algum, por causa da vossa presença; porque o Senhor vosso Deus é Deus em cima no céu e embaixo na terra.

[[v6-2-12]]

^<<v6-2-12,12>>^ Agora pois, peço-vos, jurai-me pelo Senhor que, como usei de bondade para convosco, vós também usareis de bondade para com a casa e meu pai; e dai-me um sinal seguro

[[v6-2-13]]

^<<v6-2-13,13>>^ de que conservareis em vida meu pai e minha mãe, como também meus irmãos e minhas irmãs, com todos os que lhes pertencem, e de que livrareis da morte as nossas vidas.

[[v6-2-14]]

^<<v6-2-14,14>>^ Então eles lhe responderam: A nossa vida responderá pela vossa, se não denunciardes este nosso negócio; e, quando o Senhor nos entregar esta terra, usaremos para contigo de bondade e de fidelidade.

[[v6-2-15]]

^<<v6-2-15,15>>^ Ela então os fez descer por uma corda pela janela, porquanto a sua casa estava sobre o muro da cidade, de sorte que morava sobre o muro;

[[v6-2-16]]

^<<v6-2-16,16>>^ e disse-lhes: Ide-vos ao monte, para que não vos encontrem os perseguidores, e escondei-vos lá três dias, até que eles voltem; depois podereis tomar o vosso caminho.

[[v6-2-17]]

^<<v6-2-17,17>>^ Disseram-lhe os homens: Nós seremos inocentes no tocante a este juramento que nos fizeste jurar.

[[v6-2-18]]

^<<v6-2-18,18>>^ Eis que, quando nós entrarmos na terra, atarás este cordão de fio de escarlata à janela pela qual nos fizeste descer; e recolherás em casa contigo teu pai, tua mãe, teus irmãos e toda a família de teu pai.

[[v6-2-19]]

^<<v6-2-19,19>>^ Qualquer que sair fora das portas da tua casa, o seu sangue cairá sobre a sua cabeça, e nós seremos inocentes; mas qualquer que estiver contigo em casa, o seu sangue cairá sobre a nossa cabeça se nele se puser mão.

[[v6-2-20]]

^<<v6-2-20,20>>^ Se, porém, tu denunciares este nosso negócio, seremos desobrigados do juramento que nos fizeste jurar.

[[v6-2-21]]

^<<v6-2-21,21>>^ Ao que ela disse: Conforme as vossas palavras, assim seja. Então os despediu, e eles se foram; e ela atou o cordão de escarlata à janela.

[[v6-2-22]]

^<<v6-2-22,22>>^ Foram-se, pois, e chegaram ao monte, onde ficaram três dias, até que voltaram os perseguidores; pois estes os buscaram por todo o caminho, porém, não os acharam.

[[v6-2-23]]

^<<v6-2-23,23>>^ Então os dois homens, tornando a descer do monte, passaram o rio, chegaram a Josué, filho de Num, e lhe contaram tudo quanto lhes acontecera.

[[v6-2-24]]

^<<v6-2-24,24>>^ E disseram a Josué: Certamente o Senhor nos tem entregue nas mãos toda esta terra, pois todos os moradores se derretem diante de nós.

'''

xref:006-josue/006-josue-001.adoc#v6-1-0[&#60; Capítulo Anterior] | <<v6-2-0,Topo>> | xref:006-josue/006-josue-003.adoc#v6-3-0[Próximo Capítulo &#62;]