include::./index.adoc[]

[[v6-7-0]]
=== Josué, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-7-1]]

^<<v6-7-1,1>>^ Mas os filhos de Israel cometeram uma transgressão no tocante ao anátema, pois Acã, filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá, tomou do anátema; e a ira do Senhor se acendeu contra os filhos de Israel.

[[v6-7-2]]

^<<v6-7-2,2>>^ Josué enviou de Jericó alguns homens a Ai, que está junto a Bete-Áven ao Oriente de Betel, e disse-lhes: Subi, e espiai a terra. Subiram, pois, aqueles homens, e espiaram a Ai.

[[v6-7-3]]

^<<v6-7-3,3>>^ Voltaram a Josué, e disseram-lhe: Não suba todo o povo; subam uns dois ou três mil homens, e destruam a Ai. Não fatigues ali a todo o povo, porque os habitantes são poucos.

[[v6-7-4]]

^<<v6-7-4,4>>^ Assim, subiram lá do povo cerca de três mil homens, os quais fugiram diante dos homens de Ai.

[[v6-7-5]]

^<<v6-7-5,5>>^ E os homens de Ai mataram deles cerca de trinta e seis e, havendo-os perseguido desde a porta até Sebarim, bateram-nos na descida; e o coração do povo se derreteu e se tornou como água.

[[v6-7-6]]

^<<v6-7-6,6>>^ Então Josué rasgou as suas vestes, e se prostrou com o rosto em terra perante a arca do Senhor até a tarde, ele e os anciãos de Israel; e deitaram pó sobre as suas cabeças.

[[v6-7-7]]

^<<v6-7-7,7>>^ E disse Josué: Ah, Senhor Deus! por que fizeste a este povo atravessar o Jordão, para nos entregares nas mãos dos amorreus, para nos fazeres perecer? Oxalá nos tivéssemos contentado em morarmos além do Jordão.

[[v6-7-8]]

^<<v6-7-8,8>>^ Ah, Senhor! que direi, depois que Israel virou as costas diante dos seus inimigos?

[[v6-7-9]]

^<<v6-7-9,9>>^ Pois os cananeus e todos os moradores da terra o ouvirão e, cercando-nos, exterminarão da terra o nosso nome; e então, que farás pelo teu grande nome?

[[v6-7-10]]

^<<v6-7-10,10>>^ Respondeu o Senhor a Josué: Levanta-te! por que estás assim prostrado com o rosto em terra?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel pecou; eles transgrediram o meu pacto que lhes tinha ordenado; tomaram do anátema, furtaram-no e, dissimulando, esconderam-no entre a sua bagagem.

[[v6-7-12]]

^<<v6-7-12,12>>^ Por isso os filhos de Israel não puderam subsistir perante os seus inimigos, viraram as costas diante deles, porquanto se fizeram anátema. Não serei mais convosco, se não destruirdes o anátema do meio de vós.

[[v6-7-13]]

^<<v6-7-13,13>>^ Levanta-te santifica o povo, e dize-lhe: Santificai-vos para amanhã, pois assim diz o Senhor, o Deus de Israel: Anátema há no meio de ti, Israel; não poderás suster-te diante dos teus inimigos, enquanto não tirares do meio de ti o anátema.

[[v6-7-14]]

^<<v6-7-14,14>>^ Amanhã, pois, vos chegareis, segundo as vossas tribos; a tribo que o Senhor tomar se chegará por famílias; a família que o Senhor tomar se chegará por casas; e a casa que o Senhor tomar se chegará homem por homem.

[[v6-7-15]]

^<<v6-7-15,15>>^ E aquele que for tomado com o anátema, será queimado no fogo, ele e tudo quanto tiver, porquanto transgrediu o pacto do Senhor, e fez uma loucura em Israel.

[[v6-7-16]]

^<<v6-7-16,16>>^ Então Josué se levantou de madrugada, e fez chegar Israel segundo as suas tribos, e foi tomada por sorte a tribo de Judá;

[[v6-7-17]]

^<<v6-7-17,17>>^ fez chegar a tribo de Judá, e foi tomada a família dos zeraítas; fez chegar a família dos zeraítas, homem por homem, e foi tomado Zabdi;

[[v6-7-18]]

^<<v6-7-18,18>>^ fez chegar a casa de Zabdi, homem por homem, e foi tomado Acã, filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá.

[[v6-7-19]]

^<<v6-7-19,19>>^ Então disse Josué a Acã: Filho meu, dá, peço-te, glória ao Senhor Deus de Israel, e faze confissão perante ele. Declara-me agora o que fizeste; não mo ocultes.

[[v6-7-20]]

^<<v6-7-20,20>>^ Respondeu Acã a Josué: Verdadeiramente pequei contra o Senhor Deus de Israel, e eis o que fiz:

[[v6-7-21]]

^<<v6-7-21,21>>^ quando vi entre os despojos uma boa capa babilônica, e duzentos siclos de prata, e uma cunha de ouro do peso de cinqüenta siclos, cobicei-os e tomei-os; eis que estão escondidos na terra, no meio da minha tenda, e a prata debaixo da capa.

[[v6-7-22]]

^<<v6-7-22,22>>^ Então Josué enviou mensageiros, que foram correndo à tenda; e eis que tudo estava escondido na sua tenda, estando a prata debaixo da capa.

[[v6-7-23]]

^<<v6-7-23,23>>^ Tomaram, pois, aquelas coisas do meio da tenda, e as trouxeram a Josué e a todos os filhos de Israel; e as puseram perante o Senhor.

[[v6-7-24]]

^<<v6-7-24,24>>^ Então Josué e todo o Israel com ele tomaram Acã, filho de Zerá, e a prata, a capa e a cunha de ouro, e seus filhos e suas filhas, e seus bois, jumentos e ovelhas, e a sua tenda, e tudo quanto tinha, e levaram-nos ao vale de Acor.

[[v6-7-25]]

^<<v6-7-25,25>>^ E disse Josué: Por que nos perturbaste? hoje o Senhor te perturbará a ti: E todo o Israel o apedrejou; queimaram-nos no fogo, e os apedrejaram:

[[v6-7-26]]

^<<v6-7-26,26>>^ E levantaram sobre ele um grande montão de pedras, que permanece até o dia de hoje. E o Senhor se apartou do ardor da sua ira. Por isso se chama aquele lugar até hoje o vale de Acor.

'''

xref:006-josue/006-josue-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-josue/006-josue-008.adoc#v6-8-0[Próximo Capítulo &#62;]