include::./index.adoc[]

[[v6-24-0]]
=== Josué, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-24-1]]

^<<v6-24-1,1>>^ Depois Josué reuniu todas as tribos de Israel em Siquém, e chamou os anciãos de Israel, os seus cabeças, os seus juízes e os seus oficiais; e eles se apresentaram diante de Deus.

[[v6-24-2]]

^<<v6-24-2,2>>^ Disse então Josué a todo o povo: Assim diz o Senhor Deus de Israel: Além do Rio habitaram antigamente vossos pais, Tera, pai de Abraão e de Naor; e serviram a outros deuses.

[[v6-24-3]]

^<<v6-24-3,3>>^ Eu, porém, tomei a vosso pai Abraão dalém do Rio, e o conduzi por toda a terra de Canaã; também multipliquei a sua descendência, e dei-lhe Isaque.

[[v6-24-4]]

^<<v6-24-4,4>>^ A Isaque; dei Jacó e Esaú; a Esaú dei em possessão o monte Seir; mas Jacó e seus filhos desceram para o Egito.

[[v6-24-5]]

^<<v6-24-5,5>>^ Então enviei Moisés e Arão, e feri o Egito com aquilo que fiz no meio dele; e depois vos tirei de lá.

[[v6-24-6]]

^<<v6-24-6,6>>^ Depois que tirei a vossos pais do Egito viestes ao mar; e os egípcios perseguiram a vossos pais, com carros e com cavaleiros, até o Mar Vermelho.

[[v6-24-7]]

^<<v6-24-7,7>>^ Quando clamaram ao Senhor, ele pôs uma escuridão entre vós e os egípcios, e trouxe o mar sobre eles e os cobriu; e os vossos olhos viram o que eu fiz no Egito. Depois habitastes no deserto muitos dias.

[[v6-24-8]]

^<<v6-24-8,8>>^ Então eu vos trouxe à terra dos amorreus, que habitavam além do Jordão, os quais pelejaram contra vós; porém os entreguei na vossa mão, e possuístes a sua terra; assim os destruí de diante de vós.

[[v6-24-9]]

^<<v6-24-9,9>>^ Levantou-se também Balaque, filho de Zipor, rei dos moabitas, e pelejou contra Israel; e mandou chamar a Balaão, filho de Beor, para que vos amaldiçoasse;

[[v6-24-10]]

^<<v6-24-10,10>>^ porém eu não quis ouvir a Balaão; pelo que ele vos abençoou; e eu vos livrei da sua mão.

[[v6-24-11]]

^<<v6-24-11,11>>^ E quando vós, passando o Jordão, viestes a Jericó, pelejaram contra vós os homens de Jericó, e os amorreus, os perizeus, os cananeus, os heteus, os girgaseus, os heveus e os jebuseus; porém os entreguei na vossa mão.

[[v6-24-12]]

^<<v6-24-12,12>>^ Pois enviei vespões adiante de vós, que os expulsaram de diante de vós, como aos dois reis dos amorreus, não com a vossa espada, nem com o vosso arco.

[[v6-24-13]]

^<<v6-24-13,13>>^ E eu vos dei uma terra em que não trabalhastes, e cidades que não edificastes, e habitais nelas; e comeis de vinhas e de olivais que não plantastes.

[[v6-24-14]]

^<<v6-24-14,14>>^ Agora, pois, temei ao Senhor, e servi-o com sinceridade e com verdade; deitai fora os deuses a que serviram vossos pais dalém do Rio, e no Egito, e servi ao Senhor.

[[v6-24-15]]

^<<v6-24-15,15>>^ Mas, se vos parece mal o servirdes ao Senhor, escolhei hoje a quem haveis de servir; se aos deuses a quem serviram vossos pais, que estavam além do Rio, ou aos deuses dos amorreus, em cuja terra habitais. Porém eu e a minha casa serviremos ao Senhor.

[[v6-24-16]]

^<<v6-24-16,16>>^ Então respondeu o povo, e disse: Longe esteja de nós o abandonarmos ao Senhor para servirmos a outros deuses:

[[v6-24-17]]

^<<v6-24-17,17>>^ porque o Senhor é o nosso Deus; ele é quem nos fez subir, a nós e a nossos pais, da terra do Egito, da casa da servidão, e quem fez estes grandes sinais aos nossos olhos, e nos preservou por todo o caminho em que andamos, e entre todos os povos pelo meio dos quais passamos.

[[v6-24-18]]

^<<v6-24-18,18>>^ E o Senhor expulsou de diante de nós a todos esses povos, mesmo os amorreus, que moravam na terra. Nós também serviremos ao Senhor, porquanto ele é nosso Deus.

[[v6-24-19]]

^<<v6-24-19,19>>^ Então Josué disse ao povo: Não podereis servir ao Senhor, porque é Deus santo, é Deus zeloso, que não perdoará a vossa transgressão nem os vossos pecados.

[[v6-24-20]]

^<<v6-24-20,20>>^ Se abandonardes ao Senhor e servirdes a deuses estranhos, então ele se tornará, e vos fará o mal, e vos consumirá, depois de vos ter feito o bem.

[[v6-24-21]]

^<<v6-24-21,21>>^ Disse então o povo a Josué: Não! antes serviremos ao Senhor.

[[v6-24-22]]

^<<v6-24-22,22>>^ Josué, pois, disse ao povo: Sois testemunhas contra vós mesmos e que escolhestes ao Senhor para o servir. Responderam eles: Somos testemunhas.

[[v6-24-23]]

^<<v6-24-23,23>>^ Agora, pois,-disse Josué-deitai fora os deuses estranhos que há no meio de vós, e inclinai o vosso coração ao Senhor Deus de Israel.

[[v6-24-24]]

^<<v6-24-24,24>>^ Disse o povo a Josué: Serviremos ao Senhor nosso Deus, e obedeceremos à sua voz.

[[v6-24-25]]

^<<v6-24-25,25>>^ Assim fez Josué naquele dia um pacto com o povo, e lhe deu leis e ordenanças em Siquém.

[[v6-24-26]]

^<<v6-24-26,26>>^ E Josué escreveu estas palavras no livro da lei de Deus; e, tomando uma grande pedra, a pôs ali debaixo do carvalho que estava junto ao santuário do Senhor,

[[v6-24-27]]

^<<v6-24-27,27>>^ e disse a todo o povo: Eis que esta pedra será por testemunho contra nós, pois ela ouviu todas as palavras que o Senhor nos falou; pelo que será por testemunho contra vós, para que não negueis o vosso Deus.

[[v6-24-28]]

^<<v6-24-28,28>>^ Então Josué despediu o povo, cada um para a sua herança.

[[v6-24-29]]

^<<v6-24-29,29>>^ Depois destas coisas Josué, filho de Num, servo do Senhor, morreu, tendo cento e dez anos de idade;

[[v6-24-30]]

^<<v6-24-30,30>>^ e o sepultaram no território da sua herança, em Timnate-Sera, que está na região montanhosa de Efraim, para o norte do monte Gaás.

[[v6-24-31]]

^<<v6-24-31,31>>^ Serviu, pois, Israel ao Senhor todos os dias de Josué, e todos os dias dos anciãos que sobreviveram a Josué e que sabiam toda a obra que o Senhor tinha feito a favor de Israel.

[[v6-24-32]]

^<<v6-24-32,32>>^ Os ossos de José, que os filhos de Israel trouxeram do Egito, foram enterrados em Siquém, naquela parte do campo que Jacó comprara aos filhos de Hamor, pai de Siquém, por cem peças de prata, e que se tornara herança dos filhos de José.

[[v6-24-33]]

^<<v6-24-33,33>>^ Morreu também Eleazar, filho de Arão, e o sepultaram no outeiro de Finéias, seu filho, que lhe fora dado na região montanhosa de Efraim.

'''

xref:006-josue/006-josue-023.adoc#v6-23-0[&#60; Capítulo Anterior] | <<v6-24-0,Topo>> | xref:007-juizes/007-juizes-001.adoc#v7-1-0[Próximo Capítulo &#62;]