include::./index.adoc[]

[[v6-20-0]]
=== Josué, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-20-1]]

^<<v6-20-1,1>>^ Falou mais o Senhor a Josué:

[[v6-20-2]]

^<<v6-20-2,2>>^ Dize aos filhos de Israel: Designai para vós as cidades de refúgio, de que vos falei por intermédio de Moisés,

[[v6-20-3]]

^<<v6-20-3,3>>^ a fim de que fuja para ali o homicida, que tiver matado alguma pessoa involuntariamente, e não com intento; e elas vos servirão de refúgio contra o vingador do sangue.

[[v6-20-4]]

^<<v6-20-4,4>>^ Fugindo ele para uma dessas cidades, apresentar-se-á à porta da mesma, e exporá a sua causa aos anciãos da tal cidade; então eles o acolherão ali e lhe darão lugar, para que habite com eles.

[[v6-20-5]]

^<<v6-20-5,5>>^ Se, pois, o vingador do sangue o perseguir, não lhe entregarão o homicida, porquanto feriu a seu próximo sem intenção e sem odiá-lo dantes.

[[v6-20-6]]

^<<v6-20-6,6>>^ E habitará nessa cidade até que compareça em juizo perante a congregação, até que morra o sumo sacerdote que houver naqueles dias; então o homicida voltará, e virá à sua cidade e à sua casa, à cidade donde tiver fugido.

[[v6-20-7]]

^<<v6-20-7,7>>^ Então designaram a Quedes na Galiléia, na região montanhosa de Naftali, a Siquém na região montanhosa de Efraim, e a Quiriate-Arba &#123;esta é Hebrom&#125; na região montanhosa de Judá.

[[v6-20-8]]

^<<v6-20-8,8>>^ E, além do Jordão na altura de Jericó para o oriente, designaram a Bezer, no deserto, no planalto da tribo de Rúben a Ramote, em Gileade, da tribo de Gade, e a Golã, em Basã, da tribo de Manassés.

[[v6-20-9]]

^<<v6-20-9,9>>^ Foram estas as cidades designadas para todos os filhos de Israel, e para o estrangeiro que peregrinasse entre eles, para que se acolhesse a elas todo aquele que matasse alguma pessoa involuntariamente, para que não morresse às mãos do vingador do sangue, até se apresentar perante a congregação.

'''

xref:006-josue/006-josue-019.adoc#v6-19-0[&#60; Capítulo Anterior] | <<v6-20-0,Topo>> | xref:006-josue/006-josue-021.adoc#v6-21-0[Próximo Capítulo &#62;]