include::./index.adoc[]

[[v6-4-0]]
=== Josué, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-4-1]]

^<<v6-4-1,1>>^ Quando todo o povo acabara de passar o Jordão, falou o Senhor a Josué, dizendo:

[[v6-4-2]]

^<<v6-4-2,2>>^ Tomai dentre o povo doze homens, de cada tribo um homem;

[[v6-4-3]]

^<<v6-4-3,3>>^ e mandai-lhes, dizendo: Tirai daqui, do meio do Jordão, do lugar em que estiveram parados os pés dos sacerdotes, doze pedras, levai-as convosco para a outra banda e depositai-as no lugar em que haveis de passar esta noite.

[[v6-4-4]]

^<<v6-4-4,4>>^ Chamou, pois, Josué os doze homens que escolhera dos filhos de Israel, de cada tribo um homem;

[[v6-4-5]]

^<<v6-4-5,5>>^ e disse-lhes: Passai adiante da arca do Senhor vosso Deus, ao meio do Jordão, e cada um levante uma pedra sobre o ombro, segundo o número das tribos dos filhos de Israel;

[[v6-4-6]]

^<<v6-4-6,6>>^ para que isto seja por sinal entre vós; e quando vossos filhos no futuro perguntarem: Que significam estas pedras?

[[v6-4-7]]

^<<v6-4-7,7>>^ direis a eles que as águas do Jordão foram cortadas diante da arca do pacto de Senhor; quando ela passou pelo Jordão, as águas foram cortadas; e estas pedras serão para sempre por memorial aos filhos de Israel.

[[v6-4-8]]

^<<v6-4-8,8>>^ Fizeram, pois, os filhos de Israel assim como Josué tinha ordenado, e levantaram doze pedras do meio do Jordão como o Senhor dissera a Josué, segundo o número das tribos dos filhos de Israel; e levaram-nas consigo ao lugar em que pousaram, e as depositaram ali.

[[v6-4-9]]

^<<v6-4-9,9>>^ Amontoou Josué também doze pedras no meio do Jordão, no lugar em que pararam os pés dos sacerdotes que levavam a arca do pacto; e ali estão até o dia de hoje.

[[v6-4-10]]

^<<v6-4-10,10>>^ Pois os sacerdotes que levavam a arca pararam no meio do Jordão, até que se cumpriu tudo quanto o Senhor mandara Josué dizer ao povo, conforme tudo o que Moisés tinha ordenado a Josué. E o povo apressou-se, e passou.

[[v6-4-11]]

^<<v6-4-11,11>>^ Assim que todo o povo acabara de passar, então passaram a arca do Senhor e os sacerdotes, à vista do povo.

[[v6-4-12]]

^<<v6-4-12,12>>^ E passaram os filhos de Rúben e os filhos de Gade, e a meia tribo de Manassés, armados, adiante dos filhos de Israel, como Moisés lhes tinha dito;

[[v6-4-13]]

^<<v6-4-13,13>>^ uns quarenta mil homens em pé de guerra passaram diante do Senhor para a batalha, às planícies de Jericó.

[[v6-4-14]]

^<<v6-4-14,14>>^ Naquele dia e Senhor engrandeceu a Josué aos olhos de todo o Israel; e temiam-no, como haviam temido a Moisés, por todos os dias da sua vida.

[[v6-4-15]]

^<<v6-4-15,15>>^ Depois falou o Senhor a Josué, dizendo:

[[v6-4-16]]

^<<v6-4-16,16>>^ Dá ordem aos sacerdotes que levam a arca do testemunho, que subam do Jordão.

[[v6-4-17]]

^<<v6-4-17,17>>^ Pelo que Josué deu ordem aos sacerdotes, dizendo: Subi do Jordão.

[[v6-4-18]]

^<<v6-4-18,18>>^ E aconteceu que, quando os sacerdotes que levavam a arca do pacto do Senhor subiram do meio do Jordão, e as plantas dos seus pés se puseram em terra seca, as águas do Jordão voltaram ao seu lugar, e trasbordavam todas as suas ribanceiras, como dantes.

[[v6-4-19]]

^<<v6-4-19,19>>^ O povo, pois, subiu do Jordão no dia dez do primeiro mês, e acampou-se em Gilgal, ao oriente de Jericó.

[[v6-4-20]]

^<<v6-4-20,20>>^ E as doze pedras, que tinham tirado do Jordão, levantou-as Josué em Gilgal;

[[v6-4-21]]

^<<v6-4-21,21>>^ e falou aos filhos de Israel, dizendo: Quando no futuro vossos filhos perguntarem a seus pais: Que significam estas pedras?

[[v6-4-22]]

^<<v6-4-22,22>>^ fareis saber a vossos filhos, dizendo: Israel passou a pé enxuto este Jordão.

[[v6-4-23]]

^<<v6-4-23,23>>^ Porque o Senhor vosso Deus fez secar as águas do Jordão diante de vós, até que passásseis, assim como fizera ao Mar Vermelho, ao qual fez secar perante nós, até que passássemos;

[[v6-4-24]]

^<<v6-4-24,24>>^ para que todos os povos da terra conheçam que a mão do Senhor é forte; a fim de que vós também temais ao Senhor vosso Deus para sempre.

'''

xref:006-josue/006-josue-003.adoc#v6-3-0[&#60; Capítulo Anterior] | <<v6-4-0,Topo>> | xref:006-josue/006-josue-005.adoc#v6-5-0[Próximo Capítulo &#62;]