include::./index.adoc[]

[[v6-23-0]]
=== Josué, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-23-1]]

^<<v6-23-1,1>>^ Passados muitos dias, tendo o Senhor dado repouso a Israel de todos os seus inimigos em redor, e sendo Josué já velho, de idade muito avançada,

[[v6-23-2]]

^<<v6-23-2,2>>^ chamou Josué a todo o Israel, aos seus anciãos, aos seus cabeças, aos seus juízes e aos seus oficiais, e disse-lhes: Eu já sou velho, de idade muito avançada;

[[v6-23-3]]

^<<v6-23-3,3>>^ e vós tendes visto tudo quanto o Senhor vosso Deus fez a todas estas nações por causa e vós, porque é o Senhor vosso Deus que tem pelejado por vós.

[[v6-23-4]]

^<<v6-23-4,4>>^ Vede que vos reparti por sorte estas nações que restam, para serem herança das vossas tribos, juntamente com todas as nações que tenho destruído, desde o Jordão até o grande mar para o pôr do sol.

[[v6-23-5]]

^<<v6-23-5,5>>^ E o Senhor vosso Deus as impelirá, e as expulsará de diante de vós; e vós possuireis a sua terra, como vos disse o Senhor vosso Deus.

[[v6-23-6]]

^<<v6-23-6,6>>^ Esforçai-vos, pois, para guardar e cumprir tudo quanto está escrito no livro da lei de Moisés, para que dela não vos desvieis nem para a direita nem para a esquerda;

[[v6-23-7]]

^<<v6-23-7,7>>^ para que não vos mistureis com estas nações que ainda restam entre vós; e dos nomes de seus deuses não façais menção, nem por eles façais jurar, nem os sirvais, nem a eles vos inclineis.

[[v6-23-8]]

^<<v6-23-8,8>>^ Mas ao Senhor vosso Deus vos apegareis, como fizeste até o dia de hoje;

[[v6-23-9]]

^<<v6-23-9,9>>^ pois o Senhor expulsou de diante de vós grandes e fortes nações, e, até o dia de hoje, ninguém vos tem podido resistir.

[[v6-23-10]]

^<<v6-23-10,10>>^ um só homem dentre vós persegue a mil, pois o Senhor vosso Deus é quem peleja por vós, como já vos disse.

[[v6-23-11]]

^<<v6-23-11,11>>^ Portanto, cuidai diligentemente de amar ao Senhor vosso Deus.

[[v6-23-12]]

^<<v6-23-12,12>>^ Porque se de algum modo vos desviardes, e vos apegardes ao resto destas nações que ainda ficam entre vós, e com elas contrairdes matrimônio, e entrardes a elas, e elas a vós,

[[v6-23-13]]

^<<v6-23-13,13>>^ sabei com certeza que o Senhor vosso Deus não continuará a expulsar estas nações de diante de vós; porém elas vos serão por laço e rede, e açoite às vossas ilhargas, e espinhos aos vossos olhos, até que pereçais desta boa terra que o Senhor vosso Deus vos deu.

[[v6-23-14]]

^<<v6-23-14,14>>^ Eis que vou hoje pelo caminho de toda a terra; e vós sabeis em vossos corações e em vossas almas que não tem falhado uma só palavra de todas as boas coisas que a vosso respeito falou o Senhor vosso Deus; nenhuma delas falhou, mas todas se cumpriram.

[[v6-23-15]]

^<<v6-23-15,15>>^ E assim como vos sobrevieram todas estas boas coisas de que o Senhor vosso Deus vos falou, assim trará o Senhor sobre vós todas aquelas más coisas, até vos destruir de sobre esta boa terra que ele vos deu.

[[v6-23-16]]

^<<v6-23-16,16>>^ Quando transgredirdes o pacto do Senhor vosso Deus, que ele vos ordenou, e fordes servir a outros deuses, inclinando-vos a eles, a ira do Senhor se acenderá contra vós, e depressa perecereis de sobre a boa terra que ele vos deu.

'''

xref:006-josue/006-josue-022.adoc#v6-22-0[&#60; Capítulo Anterior] | <<v6-23-0,Topo>> | xref:006-josue/006-josue-024.adoc#v6-24-0[Próximo Capítulo &#62;]