include::./index.adoc[]

[[v6-18-0]]
=== Josué, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v6-18-1]]

^<<v6-18-1,1>>^ Ora, toda a congregação dos filhos de Israel, havendo conquistado a terra, se reuniu em Siló, e ali armou a tenda da revelação.

[[v6-18-2]]

^<<v6-18-2,2>>^ E dentre os filhos de Israel restavam sete tribos que ainda não tinham repartido a sua herança.

[[v6-18-3]]

^<<v6-18-3,3>>^ Disse, pois, Josué aos filhos de Israel: Até quando sereis remissos em entrardes para possuir a terra que o Senhor Deus de vossos pais vos deu?

[[v6-18-4]]

^<<v6-18-4,4>>^ Designai vós a três homens de cada tribo, e eu os enviarei; e eles sairão a percorrer a terra, e a demarcarão segundo as suas heranças, e voltarão a ter comigo.

[[v6-18-5]]

^<<v6-18-5,5>>^ Reparti-la-ão em sete partes; Judá ficará no seu termo da banda do sul; e a casa de José ficará no seu termo da banda do norte.

[[v6-18-6]]

^<<v6-18-6,6>>^ Sim, vós demarcareis a terra em sete partes, e me trareis a mim a sua descrição; eu vos lançarei as sortes aqui perante o Senhor nosso Deus.

[[v6-18-7]]

^<<v6-18-7,7>>^ Porquanto os levitas não têm parte no meio de vós, porque o sacerdócio do Senhor é a sua herança; e Gade, Rúben e a meia tribo de Manassés já receberam a sua herança além do Jordão para o oriente, a qual lhes deu Moisés, servo do Senhor.

[[v6-18-8]]

^<<v6-18-8,8>>^ Então aqueles homens se aprontaram para saírem; e Josué deu ordem a esses que iam demarcar a terra, dizendo: Ide, percorrei a terra, e demarcai-a; então vinde ter comigo; e aqui em Siló vos lançarei as sortes perante o Senhor.

[[v6-18-9]]

^<<v6-18-9,9>>^ Foram, pois, aqueles homens e, passando pela terra, a demarcaram em sete partes segundo as suas cidades, descrevendo-a num livro; e voltaram a Josué, ao arraial em Siló.

[[v6-18-10]]

^<<v6-18-10,10>>^ Então Josué lhes lançou as sortes em Siló, perante o Senhor; e ali repartiu Josué a terra entre os filhos de Israel, conforme as suas divisões.

[[v6-18-11]]

^<<v6-18-11,11>>^ E surgiu a sorte da tribo dos filhos de Benjamim, segundo as suas famílias, e coube-lhe o território da sua sorte entre os filhos de Judá e os filhos de José.

[[v6-18-12]]

^<<v6-18-12,12>>^ O seu termo ao norte, partindo do Jordão, vai até a saliência ao norte de Jericó e, subindo pela região montanhosa para o ocidente, chega até o deserto de Bete-Áven;

[[v6-18-13]]

^<<v6-18-13,13>>^ dali passa até Luz, ao lado de Luz &#123;que é Betel&#125; para o sul; e desce a Atarote-Adar, junto ao monte que está ao sul de Bete-Horom de baixo;

[[v6-18-14]]

^<<v6-18-14,14>>^ e vai este termo virando, pelo lado ocidental, para o sul desde o monte que está defronte de Bete-Horom; e chega a Quiriate-Baal &#123;que é Quiriate-Jearim&#125;, cidade dos filhos de Judá. Esta é a sua fronteira ocidental.

[[v6-18-15]]

^<<v6-18-15,15>>^ A sua fronteira meridional começa desde a extremidade de Quiriate-Jearim, e dali se estende até Efrom, até a fonte das águas de Neftoa;

[[v6-18-16]]

^<<v6-18-16,16>>^ desce à extremidade do monte que está fronteiro ao vale de Ben-Hinom, que está no vale dos refains, para o norte; também desce ao vale de Hinom da banda dos jebuseus para o sul; e desce ainda até En-Rogel;

[[v6-18-17]]

^<<v6-18-17,17>>^ passando para o norte, chega a En-Semes, e dali sai a Gelilote, que está defronte da subida de Adumim; desce à pedra de Boã, filho de Rúben;

[[v6-18-18]]

^<<v6-18-18,18>>^ segue para o norte, margeando a Arabá, e desce ainda até a Arabá;

[[v6-18-19]]

^<<v6-18-19,19>>^ segue dali para o norte, ladeando Bete-Hogla; e os seus extremos chegam à baía setentrional do Mar Salgado, na extremidade meridional do Jordão. Esse é o termo do sul.

[[v6-18-20]]

^<<v6-18-20,20>>^ E o Jordão é o seu termo oriental. Essa é a herança dos filhos de Benjamim, pelos seus termos ao redor, segundo as suas famílias.

[[v6-18-21]]

^<<v6-18-21,21>>^ Ora, as cidades da tribo dos filhos de Benjamim, segundo as suas famílias, são: Jericó, Bete-Hogla, Emeque-Queziz,

[[v6-18-22]]

^<<v6-18-22,22>>^ Bete-Arabá, Zemaraim, Betel,

[[v6-18-23]]

^<<v6-18-23,23>>^ Avim, Pará, Ofra,

[[v6-18-24]]

^<<v6-18-24,24>>^ Quefar-Ha-Amonai. Ofni e Gaba; doze cidades e as suas aldeias.

[[v6-18-25]]

^<<v6-18-25,25>>^ Gibeão, Ramá, Beerote,

[[v6-18-26]]

^<<v6-18-26,26>>^ Mizpe, Cefira, Moza,

[[v6-18-27]]

^<<v6-18-27,27>>^ Requem, Irpeel, Tarala,

[[v6-18-28]]

^<<v6-18-28,28>>^ Zela, Elefe e Jebus &#123;esta é Jerusalém&#125;, Gibeá e Quiriate; catorze cidades e as suas aldeias. Essa é a herança dos filhos de Benjamim, segundo as suas famílias.

'''

xref:006-josue/006-josue-017.adoc#v6-17-0[&#60; Capítulo Anterior] | <<v6-18-0,Topo>> | xref:006-josue/006-josue-019.adoc#v6-19-0[Próximo Capítulo &#62;]