include::./index.adoc[]

[[v50-3-0]]
=== Filipenses, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v50-3-1]]

^<<v50-3-1,1>>^ Quanto ao mais, irmãos meus, regozijai-vos no Senhor. Não me é penoso a mim escrever-vos as mesmas coisas, e a vós vos dá segurança.

[[v50-3-2]]

^<<v50-3-2,2>>^ Acautelai-vos dos cães; acautelai-vos dos maus obreiros; acautelai-vos da falsa circuncisão.

[[v50-3-3]]

^<<v50-3-3,3>>^ Porque a circuncisão somos nós, que servimos a Deus em espírito, e nos gloriamos em Cristo Jesus, e não confiamos na carne.

[[v50-3-4]]

^<<v50-3-4,4>>^ Se bem que eu poderia até confiar na carne. Se algum outro julga poder confiar na carne, ainda mais eu:

[[v50-3-5]]

^<<v50-3-5,5>>^ circuncidado ao oitavo dia, da linhagem de Israel, da tribo de Benjamim, hebreu de hebreus; quanto à lei fui fariseu;

[[v50-3-6]]

^<<v50-3-6,6>>^ quanto ao zelo, persegui a igreja; quanto à justiça que há na lei, fui irrepreensível.

[[v50-3-7]]

^<<v50-3-7,7>>^ Mas o que para mim era lucro passei a considerá-lo como perda por amor de Cristo;

[[v50-3-8]]

^<<v50-3-8,8>>^ sim, na verdade, tenho também como perda todas as coisas pela excelência do conhecimento de Cristo Jesus, meu Senhor; pelo qual sofri a perda de todas estas coisas, e as considero como refugo, para que possa ganhar a Cristo,

[[v50-3-9]]

^<<v50-3-9,9>>^ e seja achado nele, não tendo como minha justiça a que vem da lei, mas a que vem pela fé em Cristo, a saber, a justiça que vem de Deus pela fé;

[[v50-3-10]]

^<<v50-3-10,10>>^ para conhecê-lo, e o poder da sua ressurreição e a e a participação dos seus sofrimentos, conformando-me a ele na sua morte,

[[v50-3-11]]

^<<v50-3-11,11>>^ para ver se de algum modo posso chegar à ressurreição dentre os mortos.

[[v50-3-12]]

^<<v50-3-12,12>>^ Não que já a tenha alcançado, ou que seja perfeito; mas vou prosseguindo, para ver se poderei alcançar aquilo para o que fui também alcançado por Cristo Jesus.

[[v50-3-13]]

^<<v50-3-13,13>>^ Irmãos, quanto a mim, não julgo que o haja alcançado; mas uma coisa faço, e é que, esquecendo-me das coisas que atrás ficam, e avançando para as que estão adiante,

[[v50-3-14]]

^<<v50-3-14,14>>^ prossigo para o alvo pelo prêmio da vocação celestial de Deus em Cristo Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Pelo que todos quantos somos perfeitos tenhamos este sentimento; e, se sentis alguma coisa de modo diverso, Deus também vo-lo revelará.

[[v50-3-16]]

^<<v50-3-16,16>>^ Mas, naquela medida de perfeição a que já chegamos, nela prossigamos.

[[v50-3-17]]

^<<v50-3-17,17>>^ Irmãos, sede meus imitadores, e atentai para aqueles que andam conforme o exemplo que tendes em nós;

[[v50-3-18]]

^<<v50-3-18,18>>^ porque muitos há, dos quais repetidas vezes vos disse, e agora vos digo até chorando, que são inimigos da cruz de Cristo;

[[v50-3-19]]

^<<v50-3-19,19>>^ cujo fim é a perdição; cujo deus é o ventre; e cuja glória assenta no que é vergonhoso; os quais só cuidam das coisas terrenas.

[[v50-3-20]]

^<<v50-3-20,20>>^ Mas a nossa pátria está nos céus, donde também aguardamos um Salvador, o Senhor Jesus Cristo,

[[v50-3-21]]

^<<v50-3-21,21>>^ que transformará o corpo da nossa humilhação, para ser conforme ao corpo da sua glória, segundo o seu eficaz poder de até sujeitar a si todas as coisas.

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]