include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v50-2-1]]

^<<v50-2-1,1>>^ Portanto, se há alguma exortação em Cristo, se alguma consolação de amor, se alguma comunhão do Espírito, se alguns entranháveis afetos e compaixões,

[[v50-2-2]]

^<<v50-2-2,2>>^ completai o meu gozo, para que tenhais o mesmo modo de pensar, tendo o mesmo amor, o mesmo ânimo, pensando a mesma coisa;

[[v50-2-3]]

^<<v50-2-3,3>>^ nada façais por contenda ou por vanglória, mas com humildade cada um considere os outros superiores a si mesmo;

[[v50-2-4]]

^<<v50-2-4,4>>^ não olhe cada um somente para o que é seu, mas cada qual também para o que é dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ Tende em vós aquele sentimento que houve também em Cristo Jesus,

[[v50-2-6]]

^<<v50-2-6,6>>^ o qual, subsistindo em forma de Deus, não considerou o ser igual a Deus coisa a que se devia aferrar,

[[v50-2-7]]

^<<v50-2-7,7>>^ mas esvaziou-se a si mesmo, tomando a forma de servo, tornando-se semelhante aos homens;

[[v50-2-8]]

^<<v50-2-8,8>>^ e, achado na forma de homem, humilhou-se a si mesmo, tornando-se obediente até a morte, e morte de cruz.

[[v50-2-9]]

^<<v50-2-9,9>>^ Pelo que também Deus o exaltou soberanamente, e lhe deu o nome que é sobre todo nome;

[[v50-2-10]]

^<<v50-2-10,10>>^ para que ao nome de Jesus se dobre todo joelho dos que estão nos céus, e na terra, e debaixo da terra,

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda língua confesse que Jesus Cristo é Senhor, para glória de Deus Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ De sorte que, meus amados, do modo como sempre obedecestes, não como na minha presença somente, mas muito mais agora na minha ausência, efetuai a vossa salvação com temor e tremor;

[[v50-2-13]]

^<<v50-2-13,13>>^ porque Deus é o que opera em vós tanto o querer como o efetuar, segundo a sua boa vontade.

[[v50-2-14]]

^<<v50-2-14,14>>^ Fazei todas as coisas sem murmurações nem contendas;

[[v50-2-15]]

^<<v50-2-15,15>>^ para que vos torneis irrepreensíveis e sinceros, filhos de Deus imaculados no meio de uma geração corrupta e perversa, entre a qual resplandeceis como luminares no mundo,

[[v50-2-16]]

^<<v50-2-16,16>>^ retendo a palavra da vida; para que no dia de Cristo eu tenha motivo de gloriar-me de que não foi em vão que corri nem em vão que trabalhei.

[[v50-2-17]]

^<<v50-2-17,17>>^ Contudo, ainda que eu seja derramado como libação sobre o sacrifício e serviço da vossa fé, folgo e me regozijo com todos vós;

[[v50-2-18]]

^<<v50-2-18,18>>^ e pela mesma razão folgai vós também e regozijai-vos comigo.

[[v50-2-19]]

^<<v50-2-19,19>>^ Ora, espero no Senhor Jesus enviar-vos em breve Timóteo, para que também eu esteja de bom ânimo, sabendo as vossas notícias.

[[v50-2-20]]

^<<v50-2-20,20>>^ Porque nenhum outro tenho de igual sentimento, que sinceramente cuide do vosso bem-estar.

[[v50-2-21]]

^<<v50-2-21,21>>^ Pois todos buscam o que é seu, e não o que é de Cristo Jesus.

[[v50-2-22]]

^<<v50-2-22,22>>^ Mas sabeis que provas deu ele de si; que, como filho ao pai, serviu comigo a favor do evangelho.

[[v50-2-23]]

^<<v50-2-23,23>>^ A este, pois, espero enviar logo que eu tenha visto como há de ser o meu caso;

[[v50-2-24]]

^<<v50-2-24,24>>^ confio, porém, no Senhor, que também eu mesmo em breve irei.

[[v50-2-25]]

^<<v50-2-25,25>>^ Julguei, contudo, necessário enviar-vos Epafrodito, meu irmão, e cooperador, e companheiro nas lutas, e vosso enviado para me socorrer nas minhas necessidades;

[[v50-2-26]]

^<<v50-2-26,26>>^ porquanto ele tinha saudades de vós todos, e estava angustiado por terdes ouvido que estivera doente.

[[v50-2-27]]

^<<v50-2-27,27>>^ Pois de fato esteve doente e quase à morte; mas Deus se compadeceu dele, e não somente dele, mas também de mim, para que eu não tivesse tristeza sobre tristeza.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso vo-lo envio com mais urgência, para que, vendo-o outra vez, vos regozijeis, e eu tenha menos tristeza.

[[v50-2-29]]

^<<v50-2-29,29>>^ Recebei-o, pois, no Senhor com todo o gozo, e tende em honra a homens tais como ele;

[[v50-2-30]]

^<<v50-2-30,30>>^ porque pela obra de Cristo chegou até as portas da morte, arriscando a sua vida para suprir-me o que faltava do vosso serviço.

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]