include::./index.adoc[]

[[v50-1-0]]
=== Filipenses, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v50-1-1]]

^<<v50-1-1,1>>^ Paulo e Timóteo, servos de Cristo Jesus, a todos os santos em Cristo Jesus que estão em Filipos, com os bispos e diáconos:

[[v50-1-2]]

^<<v50-1-2,2>>^ Graça a vós, e paz da parte de Deus nosso Pai, e do Senhor Jesus Cristo.

[[v50-1-3]]

^<<v50-1-3,3>>^ Dou graças ao meu Deus todas as vezes que me lembro de vós,

[[v50-1-4]]

^<<v50-1-4,4>>^ fazendo sempre, em todas as minhas orações, súplicas por todos vós com alegria

[[v50-1-5]]

^<<v50-1-5,5>>^ pela vossa cooperação a favor do evangelho desde o primeiro dia até agora;

[[v50-1-6]]

^<<v50-1-6,6>>^ tendo por certo isto mesmo, que aquele que em vós começou a boa obra a aperfeiçoará até o dia de Cristo Jesus,

[[v50-1-7]]

^<<v50-1-7,7>>^ como tenho por justo sentir isto a respeito de vós todos, porque vos retenho em meu coração, pois todos vós sois participantes comigo da graça, tanto nas minhas prisões como na defesa e confirmação do evangelho.

[[v50-1-8]]

^<<v50-1-8,8>>^ Pois Deus me é testemunha de que tenho saudades de todos vós, na terna misericórdia de Cristo Jesus.

[[v50-1-9]]

^<<v50-1-9,9>>^ E isto peço em oração: que o vosso amor aumente mais e mais no pleno conhecimento e em todo o discernimento,

[[v50-1-10]]

^<<v50-1-10,10>>^ para que aproveis as coisas excelentes, a fim de que sejais sinceros, e sem ofensa até o dia de Cristo;

[[v50-1-11]]

^<<v50-1-11,11>>^ cheios do fruto de justiça, que vem por meio de Jesus Cristo, para glória e louvor de Deus.

[[v50-1-12]]

^<<v50-1-12,12>>^ E quero, irmãos, que saibais que as coisas que me aconteceram têm antes contribuído para o progresso do evangelho;

[[v50-1-13]]

^<<v50-1-13,13>>^ de modo que se tem tornado manifesto a toda a guarda pretoriana e a todos os demais, que é por Cristo que estou em prisões;

[[v50-1-14]]

^<<v50-1-14,14>>^ também a maior parte dos irmãos no Senhor, animados pelas minhas prisões, são muito mais corajosos para falar sem temor a palavra de Deus.

[[v50-1-15]]

^<<v50-1-15,15>>^ Verdade é que alguns pregam a Cristo até por inveja e contenda, mas outros o fazem de boa mente;

[[v50-1-16]]

^<<v50-1-16,16>>^ estes por amor, sabendo que fui posto para defesa do evangelho;

[[v50-1-17]]

^<<v50-1-17,17>>^ mas aqueles por contenda anunciam a Cristo, não sinceramente, julgando suscitar aflição às minhas prisões.

[[v50-1-18]]

^<<v50-1-18,18>>^ Mas que importa? contanto que, de toda maneira, ou por pretexto ou de verdade, Cristo seja anunciado, nisto me regozijo, sim, e me regozijarei;

[[v50-1-19]]

^<<v50-1-19,19>>^ porque sei que isto me resultará em salvação, pela vossa súplica e pelo socorro do Espírito de Jesus Cristo,

[[v50-1-20]]

^<<v50-1-20,20>>^ segundo a minha ardente expectativa e esperança, de que em nada serei confundido; antes, com toda a ousadia, Cristo será, tanto agora como sempre, engrandecido no meu corpo, seja pela vida, seja pela morte.

[[v50-1-21]]

^<<v50-1-21,21>>^ Porque para mim o viver é Cristo, e o morrer é lucro.

[[v50-1-22]]

^<<v50-1-22,22>>^ Mas, se o viver na carne resultar para mim em fruto do meu trabalho, não sei então o que hei de escolher.

[[v50-1-23]]

^<<v50-1-23,23>>^ Mas de ambos os lados estou em aperto, tendo desejo de partir e estar com Cristo, porque isto é ainda muito melhor;

[[v50-1-24]]

^<<v50-1-24,24>>^ todavia, por causa de vós, julgo mais necessário permanecer na carne.

[[v50-1-25]]

^<<v50-1-25,25>>^ E, tendo esta confiança, sei que ficarei, e permanecerei com todos vós para vosso progresso e gozo na fé;

[[v50-1-26]]

^<<v50-1-26,26>>^ para que o motivo de vos gloriardes cresça por mim em Cristo Jesus, pela minha presença de novo convosco.

[[v50-1-27]]

^<<v50-1-27,27>>^ Somente portai-vos, dum modo digno do evangelho de Cristo, para que, quer vá e vos veja, quer esteja ausente, ouça acerca de vós que permaneceis firmes num só espírito, combatendo juntamente com uma só alma pela fé do evangelho;

[[v50-1-28]]

^<<v50-1-28,28>>^ e que em nada estais atemorizados pelos adversários, o que para eles é indício de perdição, mas para vós de salvação, e isso da parte de Deus;

[[v50-1-29]]

^<<v50-1-29,29>>^ pois vos foi concedido, por amor de Cristo, não somente o crer nele, mas também o padecer por ele,

[[v50-1-30]]

^<<v50-1-30,30>>^ tendo o mesmo combate que já em mim tendes visto e agora ouvis que está em mim.

'''

xref:049-efesios/049-efesios-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[Próximo Capítulo &#62;]