include::./index.adoc[]

[[v64-1-0]]
=== 3 João, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v64-1-1]]

^<<v64-1-1,1>>^ O ancião ao amado Gaio, a quem eu amo em verdade.

[[v64-1-2]]

^<<v64-1-2,2>>^ Amado, desejo que te vá bem em todas as coisas, e que tenhas saúde, assim como bem vai à tua alma.

[[v64-1-3]]

^<<v64-1-3,3>>^ Porque muito me alegrei quando os irmãos vieram e testificaram da tua verdade, como tu andas na verdade.

[[v64-1-4]]

^<<v64-1-4,4>>^ Não tenho maior gozo do que este: o de ouvir que os meus filhos andam na verdade.

[[v64-1-5]]

^<<v64-1-5,5>>^ Amado, procedes fielmente em tudo o que fazes para com os irmãos, especialmente para com os estranhos,

[[v64-1-6]]

^<<v64-1-6,6>>^ os quais diante da igreja testificaram do teu amor; aos quais, se os encaminhares na sua viagem de um modo digno de Deus, bem farás;

[[v64-1-7]]

^<<v64-1-7,7>>^ porque por amor do Nome saíram, sem nada aceitar dos gentios.

[[v64-1-8]]

^<<v64-1-8,8>>^ Portanto aos tais devemos acolher, para que sejamos cooperadores da verdade.

[[v64-1-9]]

^<<v64-1-9,9>>^ Escrevi alguma coisa à igreja; mas Diótrefes, que gosta de ter entre eles a primazia, não nos recebe.

[[v64-1-10]]

^<<v64-1-10,10>>^ Pelo que, se eu aí for, trarei à memória as obras que ele faz, proferindo contra nós palavras maliciosas; e, não contente com isto, ele não somente deixa de receber os irmãos, mas aos que os querem receber ele proíbe de o fazerem e ainda os exclui da igreja.

[[v64-1-11]]

^<<v64-1-11,11>>^ Amado, não imites o mal, mas o bem. Quem faz o bem é de Deus; mas quem faz o mal não tem visto a Deus.

[[v64-1-12]]

^<<v64-1-12,12>>^ De Demétrio, porém, todos, e até a própria verdade, dão testemunho; e nós também damos testemunho; e sabes que o nosso testemunho é verdadeiro.

[[v64-1-13]]

^<<v64-1-13,13>>^ Tinha eu muitas coisas que te escrever, mas não o quero fazer com tinta e pena.

[[v64-1-14]]

^<<v64-1-14,14>>^ Espero, porém, ver-te brevemente, e falaremos face a face.

[[v64-1-15]]

^<<v64-1-15,15>>^ Paz seja contigo. Os amigos te saúdam. Saúda os amigos nominalmente.

'''

xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-judas/065-judas-001.adoc#v65-1-0[Próximo Capítulo &#62;]