include::./index.adoc[]

[[v26-15-0]]
=== Ezequiel, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-15-1]]

^<<v26-15-1,1>>^ De novo veio a mim a palavra do Senhor, dizendo:

[[v26-15-2]]

^<<v26-15-2,2>>^ Filho do homem, que mais do que qualquer outro pau é o da videira, o sarmento que está entre as árvores do bosque?

[[v26-15-3]]

^<<v26-15-3,3>>^ Tema-se dele madeira para fazer alguma obra? ou toma-se dele alguma estaca, para se lhe pendurar algum traste?

[[v26-15-4]]

^<<v26-15-4,4>>^ Eis que é lançado no fogo, para servir de pasto; o fogo devora ambas as suas extremidades, e o meio dele fica também queimado; serve para alguma obra?

[[v26-15-5]]

^<<v26-15-5,5>>^ Ora, quando estava inteiro, não servia para obra alguma; quanto menos, estando consumido ou carbonizado pelo fogo, se faria dele qualquer obra?

[[v26-15-6]]

^<<v26-15-6,6>>^ Portanto, assim diz o Senhor Deus: Como entre as árvores do bosque é o pau da videira, que entreguei para servir de pasto ao fogo, assim entregarei os habitantes de Jerusalém.

[[v26-15-7]]

^<<v26-15-7,7>>^ E porei a minha face contra eles; eles sairão do fogo, mas o fogo os devorará; e sabereis que eu sou o Senhor, quando tiver posto a minha face contra eles.

[[v26-15-8]]

^<<v26-15-8,8>>^ Farei da terra uma desolação, porquanto eles se houveram traiçoeiramente, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[&#60; Capítulo Anterior] | <<v26-15-0,Topo>> | xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[Próximo Capítulo &#62;]