include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-24-1]]

^<<v26-24-1,1>>^ Demais veio a mim a palavra do Senhor, no ano nono, do décimo mês, aos dez do mês, dizendo:

[[v26-24-2]]

^<<v26-24-2,2>>^ Filho do homem, escreve o nome deste dia, deste mesmo dia; o rei de Babilônia acaba de sitiar Jerusalém neste dia.

[[v26-24-3]]

^<<v26-24-3,3>>^ E propõe à casa rebelde uma alegoria, e dize-lhe: Assim diz o Senhor Deus: Põe a caldeira ao lume, põe-na, e deita-lhe água dentro;

[[v26-24-4]]

^<<v26-24-4,4>>^ mete nela os pedaços de carne, todos os bons pedaços, a coxa e a espádua; enche-a de ossos escolhidos.

[[v26-24-5]]

^<<v26-24-5,5>>^ Escolhe o melhor do rebanho, ajunta um montão de lenha debaixo da caldeira dos ossos; faze-a ferver bem, e cozam-se dentro dela os seus ossos.

[[v26-24-6]]

^<<v26-24-6,6>>^ Portanto, assim diz o Senhor Deus: Ai da cidade sanguinária, da caldeira, que está enferrujada por dentro, e cuja ferrugem não saiu dela! tira dela a carne pedaço por pedaço; não caiu sorte sobre ela;

[[v26-24-7]]

^<<v26-24-7,7>>^ porque o seu sangue está no meio dela; sobre uma penha descalvada ela o pôs; não o derramou sobre o chão, para o cobrir com pó.

[[v26-24-8]]

^<<v26-24-8,8>>^ Foi para fazer subir a minha indignação para tomar vingança, que eu pus o seu sangue numa penha descalvada, para que não fosse coberto.

[[v26-24-9]]

^<<v26-24-9,9>>^ Portanto, assim diz o Senhor Deus: Ai da cidade sanguinária! também eu farei grande a fogueira.

[[v26-24-10]]

^<<v26-24-10,10>>^ Amontoa a lenha, acende o fogo, ferve bem a carne, engrossando o caldo, e sejam queimados os ossos.

[[v26-24-11]]

^<<v26-24-11,11>>^ Então a porás vazia sobre as suas brasas, para que ela aqueça, e se derreta o seu cobre, e se funda a sua imundícia no meio dela, e se consuma a sua ferrugem.

[[v26-24-12]]

^<<v26-24-12,12>>^ Ela tem-se cansado com trabalhos; contudo não sai dela a sua muita ferrugem pelo fogo.

[[v26-24-13]]

^<<v26-24-13,13>>^ A ferrugem é a tua imundícia de luxúria, porquanto te purifiquei, e tu não te purificaste, não serás purificada nunca da tua imundícia, enquanto eu não tenha satisfeito sobre ti a minha indignação.

[[v26-24-14]]

^<<v26-24-14,14>>^ Eu, o Senhor, o disse: será assim, e o farei; não tornarei atrás, e não pouparei, nem me arrependerei; conforme os teus caminhos, e conforme os teus feitos, te julgarei, diz o Senhor Deus.

[[v26-24-15]]

^<<v26-24-15,15>>^ Também veio a mim a palavra do Senhor, dizendo:

[[v26-24-16]]

^<<v26-24-16,16>>^ Filho do homem, eis que dum golpe tirarei de ti o desejo dos teus olhos; todavia não te lamentarás, nem chorarás, nem te correrão as lágrimas.

[[v26-24-17]]

^<<v26-24-17,17>>^ Geme, porém, em silêncio; não faças lamentação pelos mortos; ata na cabeça o teu turbante, e mete nos pés os teus sapatos; não cubras os teus lábios e não comas o pão dos homens.

[[v26-24-18]]

^<<v26-24-18,18>>^ Assim falei ao povo pela manhã, e à tarde morreu minha mulher; e fiz pela manhã como se me deu ordem.

[[v26-24-19]]

^<<v26-24-19,19>>^ E o povo me perguntou: Não nos farás saber o que significam para nós estas coisas que estás fazendo?

[[v26-24-20]]

^<<v26-24-20,20>>^ Então lhes respondi: Veio a mim a palavra do Senhor, dizendo:

[[v26-24-21]]

^<<v26-24-21,21>>^ Dize à casa de Israel: Assim diz o Senhor Deus: Eis que eu profanarei o meu santuário, o orgulho do vosso poder, a delícia dos vossos olhos, e o desejo da vossa alma; e vossos filhos e vossas filhas, que deixastes, cairão à espada.

[[v26-24-22]]

^<<v26-24-22,22>>^ Fareis pois como eu fiz: não vos cobrireis os lábios, e não comereis o pão dos homens;

[[v26-24-23]]

^<<v26-24-23,23>>^ tereis na cabeça os vossos turbantes, e os vossos sapatos nos pés; não vos lamentareis, nem chorareis, mas definhar-vos-eis nas vossas iniqüidades, e gemereis uns com os outros.

[[v26-24-24]]

^<<v26-24-24,24>>^ Assim vos servirá Ezequiel de sinal; conforme tudo quanto ele fez, assim fareis vós; e quando isso suceder, então sabereis que eu sou o Senhor Deus.

[[v26-24-25]]

^<<v26-24-25,25>>^ Também quanto a ti, filho do homem, no dia que eu lhes tirar a sua fortaleza, o gozo do seu ornamento, a delícia dos seus olhos, e o desejo dos seus corações, juntamente com seus filhos e suas filhas,

[[v26-24-26]]

^<<v26-24-26,26>>^ nesse dia virá ter contigo algum fugitivo para te trazer as notícias.

[[v26-24-27]]

^<<v26-24-27,27>>^ Nesse dia abrir-se-á a tua boca para com o fugitivo, e falarás, e por mais tempo não ficarás mudo; assim virás a ser para eles um sinal; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]