include::./index.adoc[]

[[v26-32-0]]
=== Ezequiel, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-32-1]]

^<<v26-32-1,1>>^ Sucedeu que, no ano duodécimo, no mês duodécimo, ao primeiro do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-32-2]]

^<<v26-32-2,2>>^ Filho do homem, faze uma lamentação sobre Faraó, rei do Egito, e dize-lhe: Foste assemelhado a um leão novo entre as nações; contudo tu és como um dragão nos mares; pulavas nos teus rios e os sujavas, turvando com os pés as suas águas.

[[v26-32-3]]

^<<v26-32-3,3>>^ Assim diz o Senhor Deus: Estenderei sobre ti a minha rede por meio duma companhia de muitos povos, e eles te alçarão na minha rede.

[[v26-32-4]]

^<<v26-32-4,4>>^ Então te deixarei em terra; sobre a face do campo te lançarei, e farei pousar sobre ti todas as aves do céu, e fartarei de ti os animais de toda a terra.

[[v26-32-5]]

^<<v26-32-5,5>>^ E porei as tuas carnes sobre os montes, e encherei os vales da tua altura.

[[v26-32-6]]

^<<v26-32-6,6>>^ Também com o teu sangue regarei a terra onde nadas, até os montes; e as correntes se encherão de ti.

[[v26-32-7]]

^<<v26-32-7,7>>^ E, apagando-te eu, cobrirei o céu, e enegrecerei as suas estrelas; ao sol encobrirei com uma nuvem, e a lua não dará a sua luz.

[[v26-32-8]]

^<<v26-32-8,8>>^ Todas as brilhantes luzes do céu, eu as enegrecerei sobre ti, e trarei trevas sobre a tua terra, diz o Senhor Deus.

[[v26-32-9]]

^<<v26-32-9,9>>^ E afligirei o coração de muitos povos, quando eu levar a efeito a tua destruição entre as nações, até as terras que não conheceste.

[[v26-32-10]]

^<<v26-32-10,10>>^ Demais farei com que muitos povos fiquem pasmados a teu respeito, e os seus reis serão sobremaneira amedrontados, quando eu brandir a minha espada diante deles; e estremecerão a cada momento, cada qual pela sua vida, no dia da tua queda.

[[v26-32-11]]

^<<v26-32-11,11>>^ Pois assim diz o Senhor Deus: A espada do rei de Babilônia virá sobre ti.

[[v26-32-12]]

^<<v26-32-12,12>>^ Farei cair a tua multidão pelas espadas dos valentes; terríveis dentre as nações são todos eles; despojarão a soberba do Egito, e toda a sua multidão será destruída.

[[v26-32-13]]

^<<v26-32-13,13>>^ Exterminarei também todos os seus animais de junto às muitas águas; não as turvará mais pé de homem, não as turvarão unhas de animais.

[[v26-32-14]]

^<<v26-32-14,14>>^ Então tornarei claras as suas águas, e farei correr os seus rios como o azeite, diz o Senhor Deus.

[[v26-32-15]]

^<<v26-32-15,15>>^ Quando eu tornar desolada a terra do Egito, e ela for despojada da sua plenitude, e quando eu ferir a todos os que nela habitarem, então saberão que eu sou o Senhor.

[[v26-32-16]]

^<<v26-32-16,16>>^ Esta é a lamentação que se fará; que as filhas das nações farão sobre o Egito e sobre toda a sua multidão, diz o Senhor Deus.

[[v26-32-17]]

^<<v26-32-17,17>>^ Também sucedeu que, no ano duodécimo, aos quinze do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-32-18]]

^<<v26-32-18,18>>^ Filho do homem, pranteia sobre a multidão do Egito, e faze-a descer, a ela e às filhas das nações majestosas, até as partes inferiores da terra, juntamente com os que descem à cova.

[[v26-32-19]]

^<<v26-32-19,19>>^ A quem sobrepujas tu em beleza? Desce, e deita-te com os incircuncisos.

[[v26-32-20]]

^<<v26-32-20,20>>^ No meio daqueles que foram mortos à espada eles cairão; à espada ela está entregue; arrastai-a e a toda a sua multidão.

[[v26-32-21]]

^<<v26-32-21,21>>^ Os poderosos entre os valentes lhe falarão desde o meio do Seol, com os que o socorrem; já desceram, jazem quietos os incircuncisos, mortos a espada.

[[v26-32-22]]

^<<v26-32-22,22>>^ Ali está Assur com toda a sua companhia. Em redor dele estão os seus sepulcros; todos eles foram mortos, caíram à espada.

[[v26-32-23]]

^<<v26-32-23,23>>^ Os seus sepulcros foram postos no mais interior da cova, e a sua companhia está em redor do seu sepulcro; foram mortos, caíram à espada todos esses que tinham causado espanto na terra dos viventes.

[[v26-32-24]]

^<<v26-32-24,24>>^ Ali está Elão com toda a sua multidão em redor do seu sepulcro; foram mortos, cairam a espada, e desceram incircuncisos às partes inferiores da terra, todos esses que causaram terror na terra dos viventes; e levaram a sua vergonha juntamente com os que descem à cova.

[[v26-32-25]]

^<<v26-32-25,25>>^ No meio dos mortos lhe puseram a cama entre toda a sua multidão; ao redor dele estão os seus sepulcros; todos esses incircuncisos foram mortos à espada; porque causaram terror na terra dos viventes; e levaram a sua vergonha com os que descem à cova. Está posto no meio dos mortos.

[[v26-32-26]]

^<<v26-32-26,26>>^ Ali estão Meseque, Tubal e toda a sua multidão; ao redor deles estão os seus sepulcros; todos esses incircuncisos foram mortos à espada; porque causaram terror na terra dos viventes.

[[v26-32-27]]

^<<v26-32-27,27>>^ E não jazem com os valentes que dentre os incircuncisos caíram, os quais desceram ao Seol com as suas armas de guerra e puseram as suas espadas debaixo das suas cabeças, tendo os seus escudos sobre os seus ossos; porque eram o terror dos poderosos na terra dos viventes.

[[v26-32-28]]

^<<v26-32-28,28>>^ Mas tu serás quebrado no meio dos incircuncisos, e jazerás com os que foram mortos a espada.

[[v26-32-29]]

^<<v26-32-29,29>>^ Ali está Edom, os seus reis e todos os seus príncipes, que no seu poder foram postos com os que foram mortos à espada; estes jazerão com os incircuncisos e com os que descem a cova.

[[v26-32-30]]

^<<v26-32-30,30>>^ Ali estão os príncipes do norte, todos eles, e todos os sidônios, que desceram com os mortos; envergonhados são pelo terror causado pelo seu poder; jazem incircuncisos com os que foram mortos à espada, e levam a sua vergonha com os que descem à cova.

[[v26-32-31]]

^<<v26-32-31,31>>^ Faraó os verá, e se consolará sobre toda a sua multidão; sim, o próprio Faraó, e todo o seu exército, traspassados à espada, diz o Senhor Deus.

[[v26-32-32]]

^<<v26-32-32,32>>^ Pois também eu pus o terror dele na terra dos viventes; pelo que jazerá no meio dos incircuncisos, com os mortos à espada, o próprio Faraó e toda a sua multidão, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]