include::./index.adoc[]

[[v26-12-0]]
=== Ezequiel, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-12-1]]

^<<v26-12-1,1>>^ Ainda veio a mim a palavra do Senhor, dizendo:

[[v26-12-2]]

^<<v26-12-2,2>>^ Filho do homem, tu habitas no meio da casa rebelde, que tem olhos para ver e não vê, e tem ouvidos para ouvir e não ouve; porque é casa rebelde.

[[v26-12-3]]

^<<v26-12-3,3>>^ Tu, pois, ó filho do homem, prepara-te os trastes para mudares para o exílio, e de dia muda à vista deles; e do teu lugar mudarás para outro lugar à vista deles; bem pode ser que reparem nisso, ainda que eles são casa rebelde.

[[v26-12-4]]

^<<v26-12-4,4>>^ À vista deles, pois, tirarás para fora, de dia, os teus trastes, como para mudança; então tu sairás de tarde à vista deles, como quem sai para o exílio.

[[v26-12-5]]

^<<v26-12-5,5>>^ Faze para ti, à vista deles, uma abertura na parede, e por ali sairás.

[[v26-12-6]]

^<<v26-12-6,6>>^ À vista deles levarás aos ombros os teus trastes, e às escuras os transportarás, e cobrirás o teu rosto, para que não vejas o chão; porque te pus por sinal à casa de Israel.

[[v26-12-7]]

^<<v26-12-7,7>>^ E fiz assim, como se me deu ordem: os meus trastes tirei para fora de dia, como para o exílio; então à tarde fiz com a mão uma abertura na parede; às escuras saí, carregando-os aos ombros, à vista deles.

[[v26-12-8]]

^<<v26-12-8,8>>^ E veio a mim a palavra do Senhor, pela manhã, dizendo:

[[v26-12-9]]

^<<v26-12-9,9>>^ Filho do homem, não te perguntou a casa de Israel, aquela casa rebelde: Que fazes tu?

[[v26-12-10]]

^<<v26-12-10,10>>^ Dize-lhes: Assim diz o Senhor Deus: Este oráculo se refere ao príncipe em Jerusalém, e a toda a casa de Israel que está no meio dela.

[[v26-12-11]]

^<<v26-12-11,11>>^ Dize: Eu sou o vosso sinal: Assim como eu fiz, assim se lhes fará a eles; irão para o exílio para o cativeiro,

[[v26-12-12]]

^<<v26-12-12,12>>^ E o príncipe que está no meio deles levará aos ombros os trastes, e às escuras sairá; ele fará uma abertura na parede e sairá por ela; ele cobrirá o seu rosto, pois com os seus olhos não verá o chão.

[[v26-12-13]]

^<<v26-12-13,13>>^ Também estenderei a minha rede sobre ele, e ele será apanhado no meu laço; e o levarei para Babilônia, para a terra dos caldeus; contudo não a verá, ainda que ali morrerá.

[[v26-12-14]]

^<<v26-12-14,14>>^ E todos os que estiverem ao redor dele para seu socorro e todas as suas tropas, espalhá-los-ei a todos os ventos; e desembainharei a espada atrás deles.

[[v26-12-15]]

^<<v26-12-15,15>>^ Assim saberão que eu sou o Senhor, quando eu os dispersar entre as nações e os espalhar entre os países.

[[v26-12-16]]

^<<v26-12-16,16>>^ Mas deles deixarei ficar alguns poucos, escapos da espada, da fome, e da peste, para que confessem todas as suas abominações entre as nações para onde forem; e saberão que eu sou o Senhor.

[[v26-12-17]]

^<<v26-12-17,17>>^ Ainda veio a mim a palavra do Senhor, dizendo:

[[v26-12-18]]

^<<v26-12-18,18>>^ Filho do homem, come o teu pão com tremor, e bebe a tua água com estremecimento e com receio.

[[v26-12-19]]

^<<v26-12-19,19>>^ E dirás ao povo da terra: Assim diz o Senhor Deus acerca dos habitantes de Jerusalém, na terra de Israel: O seu pão comerão com receio, e a sua água beberão com susto pois a sua terra será despojada de sua abundância, por causa da violência de todos os que nela habitam.

[[v26-12-20]]

^<<v26-12-20,20>>^ E as cidades habitadas serão devastadas, e a terra se tornará em desolação; e sabereis que eu sou o Senhor.

[[v26-12-21]]

^<<v26-12-21,21>>^ E veio ainda a mim a palavra do Senhor, dizendo:

[[v26-12-22]]

^<<v26-12-22,22>>^ Filho do homem, que provérbio é este que vós tendes na terra de Israel, dizendo: Dilatam-se os dias, e falha toda a visão?

[[v26-12-23]]

^<<v26-12-23,23>>^ Portanto, dize-lhes: Assim diz o Senhor Deus: Farei cessar este provérbio, e não será mais usado em Israel; mas dize-lhes: Estão próximos os dias, e o cumprimento de toda a visão.

[[v26-12-24]]

^<<v26-12-24,24>>^ Pois não haverá mais nenhuma visão vã, nem adivinhação lisonjeira, no meio da casa de Israel.

[[v26-12-25]]

^<<v26-12-25,25>>^ Porque eu sou o Senhor; falarei, e a palavra que eu falar se cumprirá. Não será mais adiada; pois em nossos dias, ó casa rebelde, falarei a palavra e a cumprirei, diz o Senhor Deus.

[[v26-12-26]]

^<<v26-12-26,26>>^ Veio mais a mim a palavra do Senhor, dizendo:

[[v26-12-27]]

^<<v26-12-27,27>>^ Filho do homem, eis que os da casa de Israel dizem: A visão que este vê é para muitos dias no futuro, e ele profetiza de tempos que estão longe.

[[v26-12-28]]

^<<v26-12-28,28>>^ Portanto dize-lhes: Assim diz o Senhor Deus: Não será mais adiada nenhuma das minhas palavras, mas a palavra que falei se cumprirá, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]