include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-28-1]]

^<<v26-28-1,1>>^ De novo veio a mim a palavra do Senhor, dizendo:

[[v26-28-2]]

^<<v26-28-2,2>>^ Filho do homem, dize ao príncipe de Tiro: Assim diz o Senhor Deus: Visto como se elevou o teu coração, e disseste: Eu sou um deus, na cadeira dos deuses me assento, no meio dos mares; todavia tu és homem, e não deus, embora consideres o teu coração como se fora o coração de um deus.

[[v26-28-3]]

^<<v26-28-3,3>>^ com efeito és mais sábio que Daniel; não há segredo algum que se possa esconder de ti.

[[v26-28-4]]

^<<v26-28-4,4>>^ Pela tua sabedoria e pelo teu entendimento alcançaste para ti riquezas, e adquiriste ouro e prata nos teus tesouros.

[[v26-28-5]]

^<<v26-28-5,5>>^ Pela tua grande sabedoria no comércio aumentaste as tuas riquezas, e por causa das tuas riquezas eleva-se o teu coração;

[[v26-28-6]]

^<<v26-28-6,6>>^ portanto, assim diz o Senhor Deus: Pois que consideras o teu coração como se fora o coração de um deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ por isso eis que eu trarei sobre ti estrangeiros, os mais terríveis dentre as nações, os quais desembainharão as suas espadas contra a formosura da tua sabedoria, e mancharão o teu resplendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ Eles te farão descer à cova; e morrerás da morte dos traspassados, no meio dos mares.

[[v26-28-9]]

^<<v26-28-9,9>>^ Acaso dirás ainda diante daquele que te matar: Eu sou um deus? mas tu és um homem, e não um deus, na mão do que te traspassa.

[[v26-28-10]]

^<<v26-28-10,10>>^ Da morte dos incircuncisos morrerás, por mão de estrangeiros; pois eu o falei, diz o Senhor Deus.

[[v26-28-11]]

^<<v26-28-11,11>>^ Veio mais a mim a palavra do Senhor, dizendo:

[[v26-28-12]]

^<<v26-28-12,12>>^ Filho do homem, levanta uma lamentação sobre o rei de Tiro, e dize-te: Assim diz o Senhor Deus: Tu eras o selo da perfeição, cheio de sabedoria e perfeito em formosura.

[[v26-28-13]]

^<<v26-28-13,13>>^ Estiveste no Éden, jardim de Deus; cobrias-te de toda pedra preciosa: a cornalina, o topázio, o ônix, a crisólita, o berilo, o jaspe, a safira, a granada, a esmeralda e o ouro. Em ti se faziam os teus tambores e os teus pífaros; no dia em que foste criado foram preparados.

[[v26-28-14]]

^<<v26-28-14,14>>^ Eu te coloquei com o querubim da guarda; estiveste sobre o monte santo de Deus; andaste no meio das pedras afogueadas.

[[v26-28-15]]

^<<v26-28-15,15>>^ Perfeito eras nos teus caminhos, desde o dia em que foste criado, até que em ti se achou iniqüidade.

[[v26-28-16]]

^<<v26-28-16,16>>^ Pela abundância do teu comércio o teu coração se encheu de violência, e pecaste; pelo que te lancei, profanado, fora do monte de Deus, e o querubim da guarda te expulsou do meio das pedras afogueadas.

[[v26-28-17]]

^<<v26-28-17,17>>^ Elevou-se o teu coração por causa da tua formosura, corrompeste a tua sabedoria por causa do teu resplendor; por terra te lancei; diante dos reis te pus, para que te contemplem.

[[v26-28-18]]

^<<v26-28-18,18>>^ Pela multidão das tuas iniqüidades, na injustiça do teu comércio, profanaste os teus santuários; eu, pois, fiz sair do meio de ti um fogo, que te consumiu a ti, e te tornei em cinza sobre a terra, à vista de todos os que te contemplavam.

[[v26-28-19]]

^<<v26-28-19,19>>^ Todos os que te conhecem entre os povos estão espantados de ti; chegaste a um fim horrível, e não mais existirás, por todo o sempre.

[[v26-28-20]]

^<<v26-28-20,20>>^ Novamente veio a mim a palavra do Senhor, dizendo:

[[v26-28-21]]

^<<v26-28-21,21>>^ Filho do homem, dirige o teu rosto para Sidom, e profetiza contra ela,

[[v26-28-22]]

^<<v26-28-22,22>>^ e dize: Assim diz o Senhor Deus: Eis-me contra ti, ó Sidom, e serei glorificado no meio de ti; e saberão que eu sou o Senhor, quando nela executar juizos e nela me santificar.

[[v26-28-23]]

^<<v26-28-23,23>>^ Pois lhe enviarei peste e sangue nas suas ruas; e os traspassados cairão no meio dela, estando a espada contra ela por todos os lados; e saberão que eu sou o Senhor.

[[v26-28-24]]

^<<v26-28-24,24>>^ E a casa de Israel nunca mais terá espinho que a fira, nem abrolho que lhe cause dor, entre os que se acham ao redor deles e que os desprezam; e saberão que eu sou o Senhor Deus.

[[v26-28-25]]

^<<v26-28-25,25>>^ Assim diz o Senhor Deus: Quando eu congregar a casa de Israel dentre os povos entre os quais estão espalhados, e eu me santificar entre eles, à vista das nações, então habitarão na sua terra que dei a meu servo, a Jacó.

[[v26-28-26]]

^<<v26-28-26,26>>^ E habitarão nela seguros; sim, edificarão casas, e plantarão vinhas, e habitarão seguros, quando eu executar juízos contra todos os que estão ao seu redor e que os desprezam; e saberão que eu sou o Senhor seu Deus.

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]