include::./index.adoc[]

[[v26-16-0]]
=== Ezequiel, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-16-1]]

^<<v26-16-1,1>>^ Ainda veio a mim a palavra do Senhor, dizendo:

[[v26-16-2]]

^<<v26-16-2,2>>^ Filho do homem, faze conhecer a Jerusalém seus atos abomináveis;

[[v26-16-3]]

^<<v26-16-3,3>>^ e dize: Assim diz o Senhor Deus a Jerusalém: A tua origem e o teu nascimento procedem da terra dos cananeus. Teu pai era amorreu, e a tua mãe hetéia.

[[v26-16-4]]

^<<v26-16-4,4>>^ E, quanto ao teu nascimento, no dia em que nasceste não te foi cortado o umbigo, nem foste lavada com água, para te alimpar; nem tampouco foste esfregada com sal, nem envolta em faixas;

[[v26-16-5]]

^<<v26-16-5,5>>^ ninguém se apiedou de ti para te fazer alguma destas coisas, compadecido de ti; porém foste lançada fora no campo, pelo nojo de ti, no dia em que nasceste.

[[v26-16-6]]

^<<v26-16-6,6>>^ E, passando eu por ti, vi-te banhada no teu sangue, e disse-te: Ainda que estás no teu sangue, vive; sim, disse-te: Ainda que estás no teu sangue, vive.

[[v26-16-7]]

^<<v26-16-7,7>>^ Eu te fiz multiplicar como o renovo do campo. E cresceste, e te engrandeceste, e alcançaste grande formosura. Formaram-se os teus seios e cresceu o teu cabelo; contudo estavas nua e descoberta.

[[v26-16-8]]

^<<v26-16-8,8>>^ Então, passando eu por ti, vi-te, e eis que o teu tempo era tempo de amores; e estendi sobre ti a minha aba, e cobri a tua nudez; e dei-te juramento, e entrei num pacto contigo, diz o Senhor Deus, e tu ficaste sendo minha.

[[v26-16-9]]

^<<v26-16-9,9>>^ Então te lavei com água, alimpei-te do teu sangue e te ungi com óleo.

[[v26-16-10]]

^<<v26-16-10,10>>^ Também te vesti de bordados, e te calcei com pele de dugongo, cingi-te de linho fino, e te cobri de seda.

[[v26-16-11]]

^<<v26-16-11,11>>^ Também te ornei de enfeites, e te pus braceletes nas mãos e um colar ao pescoço.

[[v26-16-12]]

^<<v26-16-12,12>>^ E te pus um pendente no nariz, e arrecadas nas orelhas, e uma linda coroa na cabeça.

[[v26-16-13]]

^<<v26-16-13,13>>^ Assim foste ornada de ouro e prata, e o teu vestido foi de linho fino, de seda e de bordados; de flor de farinha te nutriste, e de mel e azeite; e chegaste a ser formosa em extremo, e subiste até a realeza.

[[v26-16-14]]

^<<v26-16-14,14>>^ Correu a tua fama entre as nações, por causa da tua formosura, pois era perfeita, graças ao esplendor que eu tinha posto sobre ti, diz o Senhor Deus.

[[v26-16-15]]

^<<v26-16-15,15>>^ Mas confiaste na tua formosura, e te corrompeste por causa da tua fama; e derramavas as tuas prostituições sobre todo o que passava, para seres dele.

[[v26-16-16]]

^<<v26-16-16,16>>^ E tomaste dos teus vestidos e fizeste lugares altos adornados de diversas cores, e te prostituíste sobre eles, como nunca sucedera, nem sucederá.

[[v26-16-17]]

^<<v26-16-17,17>>^ Também tomaste as tuas belas jóias feitas do meu ouro e da minha prata que eu te havia dado, e te fizeste imagens de homens, e te prostituíste com elas;

[[v26-16-18]]

^<<v26-16-18,18>>^ e tomaste os teus vestidos bordados, e as cobriste; e puseste diante delas o meu azeite e o meu incenso.

[[v26-16-19]]

^<<v26-16-19,19>>^ E o meu pão que te dei, a flor de farinha, e o azeite e o mel, com que eu te sustentava, também puseste diante delas em cheiro suave, diz o Senhor Deus.

[[v26-16-20]]

^<<v26-16-20,20>>^ Além disto, tomaste a teus filhos e tuas filhas, que me geraras, e lhos sacrificaste, para serem devorados pelas chamas. Acaso foi a tua prostituição de tão pouca monta,

[[v26-16-21]]

^<<v26-16-21,21>>^ que havias de matar meus filhos e lhos entregar, fazendo os passar pelo fogo?

[[v26-16-22]]

^<<v26-16-22,22>>^ E em todas as tuas abominações, e nas tuas prostituições, não te lembraste dos dias da tua mocidade, quando tu estavas nua e descoberta, e jazias no teu sangue.

[[v26-16-23]]

^<<v26-16-23,23>>^ E sucedeu, depois de toda a tua maldade &#123;ai, ai de ti! diz o Senhor Deus&#125;,

[[v26-16-24]]

^<<v26-16-24,24>>^ que te edificaste uma câmara abobadada, e fizeste lugares altos em todas as praças.

[[v26-16-25]]

^<<v26-16-25,25>>^ A cada canto do caminho edificaste o teu lugar alto, e fizeste abominável a tua formosura, e alargaste os teus pés a todo o que passava, e multiplicaste as tuas prostituições.

[[v26-16-26]]

^<<v26-16-26,26>>^ Também te prostituíste com os egípcios, teus vizinhos, grandemente carnais; e multiplicaste a tua prostituição, para me provocares à ira.

[[v26-16-27]]

^<<v26-16-27,27>>^ Pelo que estendi a minha mão sobre ti, e diminuí a tua porção; e te entreguei à vontade dos que te odeiam, das filhas dos filisteus, as quais se envergonhavam do teu caminho depravado.

[[v26-16-28]]

^<<v26-16-28,28>>^ Também te prostituíste com os assírios, porquanto eras insaciável; contudo, prostituindo-te com eles, nem ainda assim ficaste farta.

[[v26-16-29]]

^<<v26-16-29,29>>^ Demais multiplicaste as tuas prostituições na terra de tráfico, isto é, até Caldéia, e nem ainda com isso te fartaste.

[[v26-16-30]]

^<<v26-16-30,30>>^ Quão fraco é teu coração, diz o Senhor Deus, fazendo tu todas estas coisas, obra duma meretriz desenfreada,

[[v26-16-31]]

^<<v26-16-31,31>>^ edificando a tua câmara abobadada no canto de cada caminho, e fazendo o teu lugar alto em cada rua! Não foste sequer como a meretriz, pois desprezaste a paga;

[[v26-16-32]]

^<<v26-16-32,32>>^ tens sido como a mulher adúltera que, em lugar de seu marido, recebe os estranhos.

[[v26-16-33]]

^<<v26-16-33,33>>^ A todas as meretrizes se dá a sua paga, mas tu dás presentes a todos es teus amantes; e lhes dás peitas, para que venham a ti de todas as partes, pelas tuas prostituições.

[[v26-16-34]]

^<<v26-16-34,34>>^ Assim és diferente de outras mulheres nas tuas prostituições; pois ninguém te procura para prostituição; pelo contrário tu dás a paga, e não a recebes; assim és diferente.

[[v26-16-35]]

^<<v26-16-35,35>>^ Portanto, ó meretriz, ouve a palavra do Senhor.

[[v26-16-36]]

^<<v26-16-36,36>>^ Assim diz o Senhor Deus: Pois que se derramou a tua lascívia, e se descobriu a tua nudez nas tuas prostituições com os teus amantes; por causa também de todos os ídolos das tuas abominações, e do sangue de teus filhos que lhes deste;

[[v26-16-37]]

^<<v26-16-37,37>>^ portanto eis que ajuntarei todos os teus amantes, com os quais te deleitaste, como também todos os que amaste, juntamente com todos os que odiaste, sim, ajuntá-los-ei contra ti em redor, e descobrirei a tua nudez diante deles, para que vejam toda a tua nudez.

[[v26-16-38]]

^<<v26-16-38,38>>^ E julgar-te-ei como são julgadas as adúlteras e as que derramam sangue; e entregar-te-ei ao sangue de furor e de ciúme.

[[v26-16-39]]

^<<v26-16-39,39>>^ Também te entregarei nas mãos dos teus inimigos, e eles derribarão a tua câmara abobadada, e demolirão os teus altos lugares, e te despirão os teus vestidos, e tomarão as tuas belas jóias, e te deixarão nua e descoberta.

[[v26-16-40]]

^<<v26-16-40,40>>^ Então farão subir uma hoste contra ti, e te apedrejarão, e te traspassarão com as suas espadas.

[[v26-16-41]]

^<<v26-16-41,41>>^ E queimarão as tuas casas a fogo, e executarão juízos contra ti, à vista de muitas mulheres; e te farei cessar de ser meretriz, e paga não darás mais.

[[v26-16-42]]

^<<v26-16-42,42>>^ Assim satisfarei em ti o meu furor, e os meus ciúmes se desviarão de ti; também me aquietarei, e não tornarei mais a me indignar.

[[v26-16-43]]

^<<v26-16-43,43>>^ Porquanto não te lembraste dos dias da tua mocidade, mas me provocaste à ira com todas estas coisas, eis que eu farei recair o teu caminho sobre a tua cabeça diz o Senhor Deus. Pois não acrescentaste a infidelidade a todas as tuas abominações?

[[v26-16-44]]

^<<v26-16-44,44>>^ Eis que todo o que usa de provérbios usará contra ti deste provérbio: Tal mãe, tal filha.

[[v26-16-45]]

^<<v26-16-45,45>>^ Tu és filha de tua mãe, que tinha nojo de seu marido e de seus filhos; e tu és irmã de tuas irmãs, que tinham nojo de seus maridos e de seus filhos. Vossa mãe foi hetéia, e vosso pai amorreu.

[[v26-16-46]]

^<<v26-16-46,46>>^ E tua irmã maior, que habita à tua esquerda, é Samária, ela juntamente com suas filhas; e tua irmã menor, que habita à tua mão direita, é Sodoma e suas filhas.

[[v26-16-47]]

^<<v26-16-47,47>>^ Todavia não andaste nos seus caminhos, nem fizeste conforme as suas abominações; mas, como se isso mui pouco fora, ainda te corrompeste mais do que elas, em todos os teus caminhos.

[[v26-16-48]]

^<<v26-16-48,48>>^ Vivo eu, diz o Senhor Deus, não fez Sodoma, tua irmã, nem ela nem suas filhas, como fizeste tu e tuas filhas.

[[v26-16-49]]

^<<v26-16-49,49>>^ Eis que esta foi a iniqüidade de Sodoma, tua irmã: Soberba, fartura de pão, e próspera ociosidade teve ela e suas filhas; mas nunca fortaleceu a mão do pobre e do necessitado.

[[v26-16-50]]

^<<v26-16-50,50>>^ Também elas se ensoberbeceram, e fizeram abominação diante de mim; pelo que, ao ver isso, as tirei do seu lugar.

[[v26-16-51]]

^<<v26-16-51,51>>^ Demais Samária não cometeu metade de teus pecados; e multiplicaste as tuas abominações mais do que elas, e justificaste a tuas irmãs, com todas as abominações que fizeste.

[[v26-16-52]]

^<<v26-16-52,52>>^ Tu, também, pois que deste sentença favorável a tuas irmãs, leva a tua vergonha; por causa de teus pecados, que fizeste mais abomináveis do que elas, mais justas são elas do que tu; confunde-te logo também, e sofre a tua vergonha, porque justificaste a tuas irmãs.

[[v26-16-53]]

^<<v26-16-53,53>>^ Eu, pois, farei tornar do cativeiro a elas, a Sodoma e suas filhas, a Samária e suas filhas, e aos de vós que são cativos no meio delas;

[[v26-16-54]]

^<<v26-16-54,54>>^ para que sofras a tua vergonha, e sejas envergonhada por causa de tudo o que fizeste, dando-lhes tu consolação.

[[v26-16-55]]

^<<v26-16-55,55>>^ Quanto a tuas irmãs, Sodoma e suas filhas, tornarão ao seu primeiro estado; e Samária e suas filhas tornarão ao seu primeiro estado; também tu e tuas filhas tornareis ao vosso primeiro estado.

[[v26-16-56]]

^<<v26-16-56,56>>^ Não foi Sodoma, tua irmã, um provérbio na tua boca, no dia da tua soberba,

[[v26-16-57]]

^<<v26-16-57,57>>^ antes que fosse descoberta a tua maldade? Agora, de igual modo, te fizeste objeto de opróbrio das filhas da Síria, e de todos os que estão ao redor dela, e para as filhas dos filisteus, que te desprezam em redor.

[[v26-16-58]]

^<<v26-16-58,58>>^ Pela tua perversidade e as tuas abominações estás sofrendo, diz o Senhor.

[[v26-16-59]]

^<<v26-16-59,59>>^ Pois assim diz o Senhor Deus: Eu te farei como fizeste, tu que desprezaste o juramento, quebrantando o pacto.

[[v26-16-60]]

^<<v26-16-60,60>>^ Contudo eu me lembrarei do meu pacto, que fiz contigo nos dias da tua mocidade; e estabelecerei contigo um pacto eterno.

[[v26-16-61]]

^<<v26-16-61,61>>^ Então te lembrarás dos teus caminhos, e ficarás envergonhada, quando receberes tuas irmãs, as mais velhas e as mais novas, e eu tas der por filhas, mas não por causa do pacto contigo.

[[v26-16-62]]

^<<v26-16-62,62>>^ E estabelecerei o meu pacto contigo, e saberás que eu sou o Senhor;

[[v26-16-63]]

^<<v26-16-63,63>>^ para que te lembres, e te envergonhes, e nunca mais abras a tua boca, por causa da tua vergonha, quando eu te perdoar tudo quanto fizeste, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]