include::./index.adoc[]

[[v26-20-0]]
=== Ezequiel, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-20-1]]

^<<v26-20-1,1>>^ Ora aconteceu, no sétimo ano, no mês quinto, aos dez do mês, que vieram alguns dos anciãos de Israel, para consultarem o Senhor; e assentaram-se diante de mim.

[[v26-20-2]]

^<<v26-20-2,2>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v26-20-3]]

^<<v26-20-3,3>>^ Filho do homem, fala aos anciãos de Israel, e dize-lhes: Assim diz o Senhor Deus: Vós vindes consultar-me, Vivo eu, que não me deixarei ser consultado de vós, diz o Senhor Deus.

[[v26-20-4]]

^<<v26-20-4,4>>^ Acaso os julgarás, faze-lhes saber as abominações de seus pais;

[[v26-20-5]]

^<<v26-20-5,5>>^ e dize-lhes: Assim diz o Senhor Deus: No dia em que escolhi a Israel, levantei a minha mão para a descendência da casa de Jacó, e me deu a conhecer a eles na terra do Egito, quando levantei a minha mão para eles, dizendo: Eu sou o Senhor vosso Deus.

[[v26-20-6]]

^<<v26-20-6,6>>^ Naquele dia levantei a minha mão para eles, jurando que os tiraria da terra do Egito para uma terra que lhes tinha espiado, que mana leite e mel, a qual é a glória de todas as terras.

[[v26-20-7]]

^<<v26-20-7,7>>^ Então lhes disse: Lançai de vós, cada um, as coisas abomináveis que encantam os seus olhos, e não vos contamineis com os ídolos do Egito; eu sou o Senhor vosso Deus.

[[v26-20-8]]

^<<v26-20-8,8>>^ Mas rebelaram-se contra mim, e não me quiseram ouvir; não lançaram de si, cada um, as coisas abomináveis que encantavam os seus olhos, nem deixaram os ídolos de Egito; então eu disse que derramaria sobre eles o meu furor, para cumprir a minha ira contra eles no meio da terra do Egito.

[[v26-20-9]]

^<<v26-20-9,9>>^ O que fiz, porém, foi por amor do meu nome, para que não fosse profanado à vista das nações, no meio das quais eles estavam, a cujos olhos eu me dei a conhecer a eles, tirando-os da terra do Egito.

[[v26-20-10]]

^<<v26-20-10,10>>^ Assim os tirei da terra do Egito, e os levei ao deserto.

[[v26-20-11]]

^<<v26-20-11,11>>^ E dei-lhes os meus estatutos, e lhes mostrei as minhas ordenanças, pelas quais o homem viverá, se as cumprir.

[[v26-20-12]]

^<<v26-20-12,12>>^ Demais lhes dei também os meus sábados, para servirem de sinal entre mim e eles; a fim de que soubessem que eu sou o Senhor que os santifica.

[[v26-20-13]]

^<<v26-20-13,13>>^ Mas a casa de Israel se rebelou contra mim no deserto, não andando nos meus estatutos, e rejeitando as minhas ordenanças, pelas quais o homem viverá, se as cumprir; e profanaram grandemente os meus sábados; então eu disse que derramaria sobre eles o meu furor no deserto, para os consumir.

[[v26-20-14]]

^<<v26-20-14,14>>^ O que fiz, porém, foi por amor do meu nome, para que não fosse profanado à vista das nações perante as quais os fiz sair.

[[v26-20-15]]

^<<v26-20-15,15>>^ E, contudo, eu levantei a minha mão para eles no deserto, jurando que não os introduziria na terra que lhes tinha dado, que mana leite e mel, a qual é a glória de todas as terras;

[[v26-20-16]]

^<<v26-20-16,16>>^ porque rejeitaram as minhas ordenanças, e não andaram nos meus estatutos, e profanaram os meus sábados; pois o seu coração andava após os seus ídolos.

[[v26-20-17]]

^<<v26-20-17,17>>^ Não obstante os meus olhos os pouparam e não os destruí nem os consumi de todo no deserto.

[[v26-20-18]]

^<<v26-20-18,18>>^ Mas disse eu a seus filhos no deserto: Não andeis nos estatutos de vossos pais, nem guardeis as suas ordenanças, nem vos contamineis com os seus ídolos.

[[v26-20-19]]

^<<v26-20-19,19>>^ Eu sou o Senhor vosso Deus; andai nos meus estatutos, e guardai as minhas ordenanças, e executai-os

[[v26-20-20]]

^<<v26-20-20,20>>^ E santificai os meus sábados; e eles servirão de sinal entre mim e vós para que saibais que eu sou o Senhor vosso Deus.

[[v26-20-21]]

^<<v26-20-21,21>>^ Mas também os filhos se rebelaram contra mim; não andaram nos meus estatutos nem guardaram as minhas ordenanças para as praticarem, pelas quais o homem viverá, se as cumprir; profanaram eles os meus sábados; por isso eu disse que derramaria sobre eles o meu furor, para cumprir contra eles a minha ira no deserto.

[[v26-20-22]]

^<<v26-20-22,22>>^ Todavia retive a minha mão, e procedi por amor do meu nome, para que não fosse profanado à vista das nações, a cujos olhos os fiz sair.

[[v26-20-23]]

^<<v26-20-23,23>>^ Também levantei a minha mão para eles no deserto, jurando que os espalharia entre as nações, e os dispersaria entre os países;

[[v26-20-24]]

^<<v26-20-24,24>>^ porque não haviam executado as minhas ordenanças, mas rejeitaram os meus estatutos, e profanaram os meus sábados, e os seus olhos se iam após os ídolos de seus pais.

[[v26-20-25]]

^<<v26-20-25,25>>^ Também lhes dei estatutos que não eram bons, e ordenanças pelas quais não poderiam viver;

[[v26-20-26]]

^<<v26-20-26,26>>^ e os deixei contaminar-se em seus próprios dons, nos quais faziam passar pelo fogo todos os que abrem a madre, para os assolar, a fim de que soubessem que eu sou o Senhor.

[[v26-20-27]]

^<<v26-20-27,27>>^ Portanto fala à casa de Israel, ó filho do homem, e dize-lhe: Assim diz o Senhor Deus: Ainda nisto me blasfemaram vossos pais, que procederam traiçoeiramente para comigo;

[[v26-20-28]]

^<<v26-20-28,28>>^ pois quando eu os havia introduzido na terra a respeito da qual eu levantara a minha mão, jurando que lha daria, então olharam para todo outeiro alto, e para toda árvore frondosa, e ofereceram ali os seus sacrifícios, e apresentaram ali a provocação das suas ofertas; puseram ali os seus cheiros suaves, e ali derramaram as suas libações.

[[v26-20-29]]

^<<v26-20-29,29>>^ E eu lhes disse: Que significa o alto a que vós ides? Assim o seu nome ficou sendo Bamá, até o dia de hoje.

[[v26-20-30]]

^<<v26-20-30,30>>^ Portanto dize à casa de Israel: Assim diz o Senhor Deus: Acaso vós vos contaminais a vós mesmos, à maneira de vossos pais? e vos prostituís com as suas abominações?

[[v26-20-31]]

^<<v26-20-31,31>>^ E, ao oferecerdes os vossos dons, quando fazeis passar os vossos filhos pelo fogo, vós vos contaminais com todos os vossos ídolos, até hoje. E eu hei de ser consultado por vós, ó casa de Israel? Vivo eu, diz o Senhor Deus, que não serei consultado de vós.

[[v26-20-32]]

^<<v26-20-32,32>>^ E o que veio ao vosso espírito de maneira alguma sucederá, quando dizeis: Sejamos como as nações, como as tribos dos países, servindo ao madeiro e à pedra.

[[v26-20-33]]

^<<v26-20-33,33>>^ Vivo eu, diz o Senhor Deus, certamente com mão forte, e com braço estendido, e com indignação derramada, hei de reinar sobre vós.

[[v26-20-34]]

^<<v26-20-34,34>>^ E vos tirarei dentre os povos, e vos congregarei dos países nos quais fostes espalhados, com mão forte, e com braço estendido, e com indignação derramada;

[[v26-20-35]]

^<<v26-20-35,35>>^ e vos levarei ao deserto dos povos; e ali face a face entrarei em juízo convosco;

[[v26-20-36]]

^<<v26-20-36,36>>^ como entrei em juízo com vossos pais, no deserto da terra do Egito, assim entrarei em juízo convosco, diz o Senhor Deus.

[[v26-20-37]]

^<<v26-20-37,37>>^ Também vos farei passar debaixo da vara, e vos farei entrar no vínculo do pacto;

[[v26-20-38]]

^<<v26-20-38,38>>^ e separarei dentre vós os rebeldes, e os que transgridem contra mim; da terra das suas peregrinações os tirarei, mas à terra de Israel não voltarão; e sabereis que eu sou o Senhor.

[[v26-20-39]]

^<<v26-20-39,39>>^ Quanto a vós, ó casa de Israel, assim diz o Senhor Deus: Ide, sirva cada um os seus ídolos; contudo mais tarde me ouvireis e não profanareis mais o meu santo nome com as vossas dádivas e com os vossos ídolos.

[[v26-20-40]]

^<<v26-20-40,40>>^ Pois no meu santo monte, no monte alto de Israel, diz o Senhor Deus, ali me servirá toda a casa de Israel, toda ela, na terra; ali vos aceitarei, e ali requererei as vossas ofertas, e as primícias das vossas oblações, com todas as vossas coisas santas.

[[v26-20-41]]

^<<v26-20-41,41>>^ Como cheiro suave vos aceitarei, quando eu vos tirar dentre os povos e vos congregar dos países em que fostes espalhados; e serei santificado em vós à vista das nações.

[[v26-20-42]]

^<<v26-20-42,42>>^ E sabereis que eu sou o Senhor, quando eu vos introduzir na terra de Israel, no país a respeito do qual levantei a minha mão, jurando que o daria a vossos pais.

[[v26-20-43]]

^<<v26-20-43,43>>^ Ali vos lembrareis de vossos caminhos, e de todos os vossos atos com que vos tendes contaminado; e tereis nojo de vós mesmos, por causa de todas as vossas maldades que tendes cometido.

[[v26-20-44]]

^<<v26-20-44,44>>^ E sabereis que eu sou o Senhor, quando eu proceder para convosco por amor do meu nome, não conforme os vossos maus caminhos, nem conforme os vossos atos corruptos, ó casa de Israel, diz o senhor Deus.

[[v26-20-45]]

^<<v26-20-45,45>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-20-46]]

^<<v26-20-46,46>>^ Filho do homem, dirige o teu rosto para o caminho do sul, e derrama as tuas palavras contra o sul, e profetiza contra o bosque do campo do sul.

[[v26-20-47]]

^<<v26-20-47,47>>^ E dize ao bosque do sul: Ouve a palavra do Senhor: Assim diz o Senhor Deus: Eis que acenderei em ti um fogo que em ti consumirá toda árvore verde e toda árvore seca; não se apagará a chama flamejante, antes com ela se queimarão todos os rostos, desde o sul até o norte.

[[v26-20-48]]

^<<v26-20-48,48>>^ E verá toda a carne que eu, o Senhor, o acendi; não se apagará.

[[v26-20-49]]

^<<v26-20-49,49>>^ Então disse eu: Ah Senhor Deus! eles dizem de mim: Não é este um fazedor de alegorias?

'''

xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]