include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-26-1]]

^<<v26-26-1,1>>^ Ora sucedeu no undécimo ano, ao primeiro do mês, que veio a mim a palavra do Senhor, dizendo:

[[v26-26-2]]

^<<v26-26-2,2>>^ Filho do homem, visto como Tiro disse no tocante a Jerusalém: Ah! está quebrada a porta dos povos; está aberta para mim; eu me encherei, agora que ela está assolada;

[[v26-26-3]]

^<<v26-26-3,3>>^ portanto assim diz o Senhor Deus: Eis que eu sou contra ti, ó Tiro, e farei subir contra ti muitas nações, como o mar faz subir as suas ondas.

[[v26-26-4]]

^<<v26-26-4,4>>^ Elas destruirão os muros de Tiro, e derrubarão as suas torres; e eu varrerei o seu solo, e dela farei uma rocha descalvada.

[[v26-26-5]]

^<<v26-26-5,5>>^ Ela virá a ser no meio do mar um enxugadouro de redes; pois eu o falei, diz o Senhor Deus; e ela servirá de despojo para as nações.

[[v26-26-6]]

^<<v26-26-6,6>>^ Também suas filhas que estão no campo serão mortas à espada; e saberão que eu sou o Senhor.

[[v26-26-7]]

^<<v26-26-7,7>>^ Porque assim diz o Senhor Deus: Eis que eu trarei contra Tiro a Nabucodonosor, rei de Babilônia, desde o norte, o rei dos reis, com cavalos, e com carros, e com cavaleiros, sim, companhias e muito povo.

[[v26-26-8]]

^<<v26-26-8,8>>^ As tuas filhas ele matará à espada no campo; e construirá fortes contra ti, levantará contra ti uma tranqueira, e alçará paveses contra ti;

[[v26-26-9]]

^<<v26-26-9,9>>^ dirigirá os golpes dos seus arietes contra os teus muros, e derrubará as tuas torres com os seus machados.

[[v26-26-10]]

^<<v26-26-10,10>>^ Por causa da multidão de seus cavalos te cobrirá o seu pó; os teus muros tremerão com o estrondo dos cavaleiros, e das carroças, e dos carros, quando ele entrar pelas tuas portas, como quem entra numa cidade em que se fez brecha.

[[v26-26-11]]

^<<v26-26-11,11>>^ Com as patas dos seus cavalos pisará todas as tuas ruas; ao teu povo matará à espada, e as tuas fortes colunas cairão por terra.

[[v26-26-12]]

^<<v26-26-12,12>>^ Também eles roubarão as tuas riquezas e saquearão as tuas mercadorias; derrubarão os teus muros e arrasarão as tuas casas agradáveis; e lançarão no meio das águas as tuas pedras, as tuas madeiras, e o teu solo.

[[v26-26-13]]

^<<v26-26-13,13>>^ E eu farei cessar o arruído das tuas cantigas, e o som das tuas harpas não se ouvira mais;

[[v26-26-14]]

^<<v26-26-14,14>>^ e farei de ti uma rocha descalvada; viras a ser um enxugadouro das redes, nunca mais serás edificada; pois eu, o Senhor, o falei, diz o Senhor Deus.

[[v26-26-15]]

^<<v26-26-15,15>>^ Assim diz o Senhor Deus a Tiro: Acaso não tremerão as ilhas com o estrondo da tua queda, quando gemerem os feridos, quando se fizer a matança no meio de ti?

[[v26-26-16]]

^<<v26-26-16,16>>^ Então todos os príncipes do mar descerão dos seus tronos, e porão de lado os seus mantos, e despirão as suas vestes bordadas; de tremores se vestirão; sobre a terra se assentarão; e estremecerão a cada momento, e de ti se espantarão.

[[v26-26-17]]

^<<v26-26-17,17>>^ E farão uma lamentação sobre ti, e te dirão: Como pereceste, ó povoada de navegantes, ó cidade afamada, que foste forte no mar! tu e os teus moradores que atemorizastes a todos os que habitam ao teu redor!

[[v26-26-18]]

^<<v26-26-18,18>>^ Agora estremecerão as ilhas no dia da tua queda; sim, as ilhas, que estão no mar, espantar-se-ão da tua saída.

[[v26-26-19]]

^<<v26-26-19,19>>^ Pois assim diz o Senhor Deus: Quando eu te fizer uma cidade assolada, como as cidades que não se habitam, quando fizer subir sobre ti o abismo, e as muitas águas te cobrirem,

[[v26-26-20]]

^<<v26-26-20,20>>^ então te farei descer com os que descem à cova, ao povo antigo, e te farei habitar nas mais baixas partes da terra, em lugares desertos de há muito, juntamente com os que descem à cova, para que não sejas habitada; e estabelecerei a glória na terra dos viventes.

[[v26-26-21]]

^<<v26-26-21,21>>^ Farei de ti um grande espanto, e não mais existirás; embora te procurem, contudo, nunca serás achada, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]