include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-43-1]]

^<<v26-43-1,1>>^ Então me levou à porta, à porta que dá para o oriente.

[[v26-43-2]]

^<<v26-43-2,2>>^ E eis que a glória do Deus de Israel vinha do caminho do oriente; e a sua voz era como a voz de muitas águas, e a terra resplandecia com a glória dele.

[[v26-43-3]]

^<<v26-43-3,3>>^ E a aparência da visão que tive era como a da visão que eu tivera quando ele veio destruir a cidade; eram as visões como a que tive junto ao rio Quebar; e caí com o rosto em terra.

[[v26-43-4]]

^<<v26-43-4,4>>^ E a glória do Senhor entrou no templo pelo caminho da porta oriental.

[[v26-43-5]]

^<<v26-43-5,5>>^ E levantou-me o Espírito, e me levou ao átrio interior; e eis que a glória do Senhor encheu o templo.

[[v26-43-6]]

^<<v26-43-6,6>>^ Então ouvi uma voz que me foi direita de dentro do templo; e um homem se achava de pé junto de mim.

[[v26-43-7]]

^<<v26-43-7,7>>^ E disse-me: Filho do homem, este é o lugar do meu trono, e o lugar das plantas dos meus pés, onde habitarei no meio dos filhos de Israel para sempre; e os da casa de Israel não contaminarão mais o meu nome santo, nem eles nem os seus reis, com as suas prostituições e com os cadáveres dos seus reis, nos seus altos,

[[v26-43-8]]

^<<v26-43-8,8>>^ pondo o seu limiar ao pé do meu limiar, e os seus umbrais junto aos meus umbrais, e havendo apenas um muro entre mim e eles. Contaminaram o meu santo nome com as abominações que têm cometido; por isso eu os consumi na minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora lancem eles para longe de mim a sua prostituição e os cadáveres dos seus reis; e habitarei no meio deles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ Tu pois, ó filho do homem, mostra aos da casa de Israel o templo, para que se envergonhem das suas iniqüidades; e meçam o modelo.

[[v26-43-11]]

^<<v26-43-11,11>>^ E se eles se envergonharem de tudo quanto têm feito, faze-lhes saber a forma desta casa, a sua figura, as suas saídas e as suas entradas, e todas as suas formas; todas as suas ordenanças e todas as suas leis; escreve isto à vista deles, para que guardem toda a sua forma, e todas as suas ordenanças e as cumpram.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei do templo: Sobre o cume do monte todo o seu contorno em redor será santíssimo. Eis que essa é a lei do templo.

[[v26-43-13]]

^<<v26-43-13,13>>^ São estas as medidas do altar em côvados &#123;o côvado é um côvado e um palmo&#125;: a parte inferior será de um côvado de altura e um côvado de largura, e a sua borda, junto a sua extremidade ao redor, de um palmo; e esta será a base do altar.

[[v26-43-14]]

^<<v26-43-14,14>>^ E do fundo, desde o chão até a saliência de baixo, será de dois côvados, e de largura um côvado; e desde a pequena saliência até a saliência grande será de quatro côvados, e a largura de um côvado.

[[v26-43-15]]

^<<v26-43-15,15>>^ E o altar superior será de quatro côvados; e da lareira do altar para cima se levantarão quatro pontas.

[[v26-43-16]]

^<<v26-43-16,16>>^ E a lareira do altar terá doze côvados de comprimento, e doze de largura, quadrado nos quatro lados.

[[v26-43-17]]

^<<v26-43-17,17>>^ E a saliência terá catorze côvados de comprimento e catorze de largura, nos seus quatro lados; e a borda, ao redor dela, será de meio côvado; e o fundo dela será de um côvado, ao redor; e os seus degraus darão para o oriente.

[[v26-43-18]]

^<<v26-43-18,18>>^ E disse-me: Filho do homem, assim diz o Senhor Deus: São estas as ordenanças para o altar, no dia em que o fizerem, para oferecerem sobre ele holocausto e para espargirem sobre ele sangue.

[[v26-43-19]]

^<<v26-43-19,19>>^ Aos sacerdotes levitas que são da linhagem de Zadoque, os quais se chegam a mim para me servirem, diz o Senhor Deus, darás um bezerro para oferta pelo pecado.

[[v26-43-20]]

^<<v26-43-20,20>>^ E tomarás do seu sangue, e o porás sobre as quatro pontas do altar, sobre os quatro cantos da saliência e sobre a borda ao redor; assim o purificarás e os expiarás.

[[v26-43-21]]

^<<v26-43-21,21>>^ Então tomarás o novilho da oferta pelo pecado, o qual será queimado no lugar da casa para isso ordenado, fora do santuário.

[[v26-43-22]]

^<<v26-43-22,22>>^ E no segundo dia oferecerás um bode, sem mancha, para oferta pelo pecado; e purificarão o altar, como o purificaram com o novilho.

[[v26-43-23]]

^<<v26-43-23,23>>^ Quando acabares de o purificar, oferecerás um bezerro, sem mancha, e um carneiro do rebanho, sem mancha.

[[v26-43-24]]

^<<v26-43-24,24>>^ Trá-los-ás, pois, perante o Senhor; e os sacerdotes deitarão sal sobre eles, e os oferecerão em holocausto ao Senhor.

[[v26-43-25]]

^<<v26-43-25,25>>^ Durante sete dias prepararás cada dia um bode como oferta pelo pecado; também prepararão eles um bezerro, e um carneiro do rebanho, sem mancha.

[[v26-43-26]]

^<<v26-43-26,26>>^ Por sete dias expiarão o altar, e o purificarão; assim o consagrarão.

[[v26-43-27]]

^<<v26-43-27,27>>^ E, cumprindo eles estes dias, será que, ao oitavo dia, e dali em diante, os sacerdotes oferecerão sobre o altar os vossos holocaustos e as vossas ofertas pacíficas; e vos aceitarei, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]