include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-14-1]]

^<<v26-14-1,1>>^ Então vieram a mim alguns homens dos anciãos de Israel, e se assentaram diante de mim.

[[v26-14-2]]

^<<v26-14-2,2>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-14-3]]

^<<v26-14-3,3>>^ Filho do homem, estes homens deram lugar nos seus corações aos seus ídolos, e puseram o tropeço da sua maldade diante da sua face; devo eu de alguma maneira ser interrogado por eles?

[[v26-14-4]]

^<<v26-14-4,4>>^ Portanto fala com eles, e dize-lhes: Assim diz o Senhor Deus: Qualquer homem da casa de Israel que der lugar no seu coração aos seus ídolos, e puser o tropeço da sua maldade diante da sua face, e vier ao profeta, eu, o Senhor, lhe responderei nisso conforme a multidão dos seus ídolos;

[[v26-14-5]]

^<<v26-14-5,5>>^ para que possa apanhar a casa de Israel no seu coração, porquanto todos são alienados de mim pelos seus ídolos.

[[v26-14-6]]

^<<v26-14-6,6>>^ Portanto dize à casa de Israel: Assim diz o Senhor Deus: Convertei-vos, e deixai os vossos ídolos; e desviai os vossos rostos de todas as vossas abominações.

[[v26-14-7]]

^<<v26-14-7,7>>^ Porque qualquer homem da casa de Israel, ou dos estrangeiros que peregrinam em Israel, que se alienar de mim e der lugar no seu coração aos seus ídolos, e puser tropeço da sua maldade diante do seu rosto, e vier ao profeta para me consultar a favor de si mesmo, eu, o Senhor, lhe responderei por mim mesmo;

[[v26-14-8]]

^<<v26-14-8,8>>^ e porei o meu rosto contra o tal homem, e o farei um espanto, um sinal e um provérbio, e exterminá-lo-ei do meio do meu povo; e sabereis que eu sou o Senhor.

[[v26-14-9]]

^<<v26-14-9,9>>^ E se o profeta for enganado, e falar alguma coisa, eu, o Senhor, terei enganado esse profeta; e estenderei a minha mão contra ele, e destruí-lo-ei do meio do meu povo Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ E levarão o seu castigo. O castigo do profeta será como o castigo de quem o consultar;

[[v26-14-11]]

^<<v26-14-11,11>>^ para que a casa de Israel não se desvie mais de mim, nem mais se contamine com todas as suas transgressões; mas que sejam eles o meu povo, e seja eu o seu Deus, diz o Senhor Deus.

[[v26-14-12]]

^<<v26-14-12,12>>^ Veio ainda a mim a palavra do Senhor, dizendo:

[[v26-14-13]]

^<<v26-14-13,13>>^ Filho do homem, quando uma terra pecar contra mim, agindo traiçoeiramente, então estenderei a minha mão contra ela, e lhe quebrarei o báculo do pão, e enviarei contra ela a fome, e dela exterminarei homens e animais;

[[v26-14-14]]

^<<v26-14-14,14>>^ ainda que estivessem no meio dela estes três homens, Noé, Daniel e Jó, eles pela sua justiça, livrariam apenas a sua própria vida, diz o Senhor Deus.

[[v26-14-15]]

^<<v26-14-15,15>>^ Se eu fizer passar pela terra bestas feras, e estas a assolarem, de modo que ela fique desolada, sem que ninguém possa passar por ela por causa das feras;

[[v26-14-16]]

^<<v26-14-16,16>>^ ainda que esses três homens estivessem no meio dela, vivo eu, diz o Senhor Deus, que nem a filhos nem a filhas livrariam; eles só ficariam livres; a terra, porém, seria assolada.

[[v26-14-17]]

^<<v26-14-17,17>>^ Ou, se eu trouxer a espada sobre aquela terra, e disser: Espada, passa pela terra; de modo que eu extermine dela homens e animais;

[[v26-14-18]]

^<<v26-14-18,18>>^ ainda que aqueles três homens estivessem nela, vivo eu, diz o Senhor Deus, eles não livrariam nem filhos nem filhas, mas eles só ficariam livres.

[[v26-14-19]]

^<<v26-14-19,19>>^ Ou, se eu enviar a peste sobre aquela terra, e derramar o meu furor sobre ela com sangue, para exterminar dela homens e animais;

[[v26-14-20]]

^<<v26-14-20,20>>^ ainda que Noé, Daniel e Jó estivessem no meio dela, vivo eu, diz o Senhor Deus, eles não livrariam nem filho nem filha, tão somente livrariam as suas próprias vidas pela sua justiça.

[[v26-14-21]]

^<<v26-14-21,21>>^ Pois assim diz o Senhor Deus: Quanto mais quando eu enviar contra Jerusalém os meus quatro juízos violentos, a espada, a fome, as bestas-feras e a peste, pura exterminar dela homens e animais?

[[v26-14-22]]

^<<v26-14-22,22>>^ Mas, se ainda restarem nela alguns sobreviventes que levem para fora filhos e filhas, quando eles saírem a ter convosco, vereis o seu caminho e os seus feitos, e ficareis consolados do mal que eu trouxe sobre Jerusalém, até de tudo o que trouxe sobre ela.

[[v26-14-23]]

^<<v26-14-23,23>>^ E sereis consolados, quando virdes o seu caminho e os seus feitos; e sabereis que não fiz sem razão tudo quanto nela tenho feito, diz o Senhor.

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]