include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-11-1]]

^<<v26-11-1,1>>^ Então me levantou o Espírito, e me levou à porta oriental da casa do Senhor, a qual olha para o oriente; e eis que estavam à entrada da porta vinte e cinco homens, e no meio deles vi a Jaazanias, filho de Azur, e a Pelatias, filho de Benaías, príncipes do povo.

[[v26-11-2]]

^<<v26-11-2,2>>^ E disse-me: Filho do homem, estes são os homens que maquinam a iniqüidade, e dão ímpio conselho nesta cidade;

[[v26-11-3]]

^<<v26-11-3,3>>^ os quais dizem: Não está próximo o tempo de edificar casas; esta cidade é a caldeira, e nós somos a carne.

[[v26-11-4]]

^<<v26-11-4,4>>^ Portanto, profetiza contra eles; profetiza, ó filho do homem.

[[v26-11-5]]

^<<v26-11-5,5>>^ E caiu sobre mim o Espírito do Senhor, e disse-me: Fala: Assim diz o Senhor: Assim tendes dito, ó casa de Israel; pois eu conheço as coisas que vos entram na mente.

[[v26-11-6]]

^<<v26-11-6,6>>^ Multiplicastes os vossos mortos nesta cidade, e enchestes as suas ruas de mortos.

[[v26-11-7]]

^<<v26-11-7,7>>^ Portanto, assim diz o Senhor Deus: Vossos mortos que deitastes no meio dela, esses são a carne, e ela é a caldeira; a vós, porém, vos tirarei do meio dela.

[[v26-11-8]]

^<<v26-11-8,8>>^ Temestes a espada, e a espada eu a trarei sobre vós, diz o Senhor Deus.

[[v26-11-9]]

^<<v26-11-9,9>>^ E vos farei sair do meio dela, e vos entregarei na mão de estrangeiros, e exercerei juízos entre vós.

[[v26-11-10]]

^<<v26-11-10,10>>^ Caireis à espada; nos confins de Israel vos julgarei; e sabereis que eu sou o Senhor.

[[v26-11-11]]

^<<v26-11-11,11>>^ Esta cidade não vos servirá de caldeira, nem vós servirei de carne no meio dela; nos confins de Israel vos julgarei;

[[v26-11-12]]

^<<v26-11-12,12>>^ e sabereis que eu sou o Senhor; pois não tendes andado nos meus estatutos, nem executado as minhas ordenanças; antes tendes procedido conforme as ordenanças das nações que estão em redor de vós.

[[v26-11-13]]

^<<v26-11-13,13>>^ E aconteceu que, profetizando eu, morreu Pelatias, filho de Benaías. Então caí com o resto em terra, e clamei com grande voz, e disse: Ah Senhor Deus! darás fim cabal ao remanescente de Israel?

[[v26-11-14]]

^<<v26-11-14,14>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v26-11-15]]

^<<v26-11-15,15>>^ Filho do homem, teus irmãos, os teus próprios irmãos, os homens de teu parentesco, e toda a casa de Israel, todos eles, são aqueles a quem os habitantes de Jerusalém disseram: Apartai-vos para longe do Senhor; a nós se nos deu esta terra em possessão.

[[v26-11-16]]

^<<v26-11-16,16>>^ Portanto, dize: Assim diz o Senhor Deus: Ainda que os mandei para longe entre as nações, e ainda que os espalhei pelas terras, todavia lhes servirei de santuário por um pouco de tempo, nas terras para onde foram.

[[v26-11-17]]

^<<v26-11-17,17>>^ Portanto, dize: Assim diz o senhor Deus: Hei de ajuntar-vos do meio dos povos, e vos recolherei do meio das terras para onde fostes espalhados, e vos darei a terra de Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ E virão ali, e tirarão dela todas as suas coisas detestáveis e todas as suas abominações.

[[v26-11-19]]

^<<v26-11-19,19>>^ E lhes darei um só coração, e porei dentro deles um novo espírito; e tirarei da sua carne o coração de pedra, e lhes darei um coração de carne,

[[v26-11-20]]

^<<v26-11-20,20>>^ para que andem nos meus estatutos, e guardem as minhas ordenanças e as cumpram; e eles serão o meu povo, e eu serei o seu Deus.

[[v26-11-21]]

^<<v26-11-21,21>>^ Mas, quanto àqueles cujo coração andar após as suas coisas detestáveis, e das suas abominações, eu farei recair nas suas cabeças o seu caminho, diz o Senhor Deus.

[[v26-11-22]]

^<<v26-11-22,22>>^ Então os querubins elevaram as suas asas, estando as rodas ao lado deles; e a glória do Deus de Israel estava em cima sobre eles.

[[v26-11-23]]

^<<v26-11-23,23>>^ E a glória do Senhor se alçou desde o meio da cidade, e se pôs sobre o monte que está ao oriente da cidade.

[[v26-11-24]]

^<<v26-11-24,24>>^ Então o Espírito me levantou, e me levou na visão pelo Espírito de Deus para a Caldéia, para os exilados. Assim se foi de mim a visão que eu tinha visto.

[[v26-11-25]]

^<<v26-11-25,25>>^ E falei aos do cativeiro todas as coisas que o Senhor me tinha mostrado.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]