include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-4-1]]

^<<v26-4-1,1>>^ Tu pois, ó filho do homem, toma um tijolo, e pô-lo-ás diante de ti, e grava nele uma cidade, a cidade de Jerusalém;

[[v26-4-2]]

^<<v26-4-2,2>>^ e põe contra ela um cerco, e edifica contra ela uma fortificação, e levanta contra ela uma tranqueira; e coloca contra ela arraiais, e põe-lhe aríetes em redor.

[[v26-4-3]]

^<<v26-4-3,3>>^ Toma também uma sertã de ferro, e põe-na por muro de ferro entre ti e a cidade; e olha para a cidade, e ela será cercada, e tu a cercarás; isso servirá de sinal para a casa de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ Tu também deita-te sobre o teu lado esquerdo, e põe sobre ele a iniqüidade da casa de Israel; conforme o número dos dias em que te deitares sobre ele, levarás a sua iniqüidade.

[[v26-4-5]]

^<<v26-4-5,5>>^ Pois eu fixei os anos da sua iniqüidade, para que eles te sejam contados em dias, trezentos e noventa dias; assim levarás a iniqüidade da casa de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ E quando tiveres cumprido estes dias, deitar-te-ás sobre o teu lado direito, e levarás a iniqüidade da casa de Judá; quarenta dias te dei, cada dia por um ano.

[[v26-4-7]]

^<<v26-4-7,7>>^ Dirigirás, pois, o teu rosto para o cerco de Jerusalém, com o teu braço descoberto; e profetizarás contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ E eis que porei sobre ti cordas; assim tu não te voltarás dum lado para o outro, até que tenhas cumprido os dias de teu cerco:

[[v26-4-9]]

^<<v26-4-9,9>>^ E tu toma trigo, e cevada, e favas, e lentilhas, e milho miúdo, e espelta, e mete-os numa só vasilha, e deles faze pão. Conforme o número dos dias que te deitares sobre o teu lado, trezentos e noventa dias, comerás disso.

[[v26-4-10]]

^<<v26-4-10,10>>^ E a tua comida, que hás de comer, será por peso, vinte siclos cada dia; de tempo em tempo a comerás.

[[v26-4-11]]

^<<v26-4-11,11>>^ Também beberás a água por medida, a sexta parte dum him; de tempo em tempo beberás.

[[v26-4-12]]

^<<v26-4-12,12>>^ Tu a comerás como bolos de cevada, e à vista deles a assarás sobre o excremento humano.

[[v26-4-13]]

^<<v26-4-13,13>>^ E disse o Senhor: Assim comerão os filhos de Israel o seu pão imundo, entre as nações, para onde eu os lançarei.

[[v26-4-14]]

^<<v26-4-14,14>>^ Então disse eu: Ah Senhor Deus! eis que a minha alma não foi contaminada: pois desde a minha mocidade até agora jamais comi do animal que morre de si mesmo, ou que é dilacerado por feras; nem carne abominável entrou na minha boca.

[[v26-4-15]]

^<<v26-4-15,15>>^ Então me disse: Vê, eu te dou esterco de bois em lugar de excremento de homem; e sobre ele prepararás o teu pão,

[[v26-4-16]]

^<<v26-4-16,16>>^ Disse-me mais: Filho do homem, eis que quebrarei o báculo de pão em Jerusalém; e comerão o pão por peso, e com ansiedade; e beberão a água por medida, e com espanto;

[[v26-4-17]]

^<<v26-4-17,17>>^ até que lhes falte o pão e a água, e se espantem uns com os outros, e se definhem na sua iniqüidade.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]