include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-7-1]]

^<<v26-7-1,1>>^ Demais veio a palavra do Senhor a mim, dizendo:

[[v26-7-2]]

^<<v26-7-2,2>>^ E tu, ó filho do homem, assim diz o Senhor Deus à terra de Israel: Vem o fim, o fim vem sobre os quatro cantos da terra.

[[v26-7-3]]

^<<v26-7-3,3>>^ Agora vem o fim sobre ti, e enviarei sobre ti a minha ira, e te julgarei conforme os teus caminhos; e trarei sobre ti todas as tuas abominações.

[[v26-7-4]]

^<<v26-7-4,4>>^ E não te pouparei, nem terei piedade de ti; mas eu te punirei por todos os teus caminhos, enquanto as tuas abominações estiverem no meio de ti; e sabereis que eu sou o Senhor.

[[v26-7-5]]

^<<v26-7-5,5>>^ Assim diz o Senhor Deus: Mal sobre mal! eis que vem!

[[v26-7-6]]

^<<v26-7-6,6>>^ Vem o fim, o fim vem, despertou-se contra ti; eis que vem.

[[v26-7-7]]

^<<v26-7-7,7>>^ Vem a tua ruína, ó habitante da terra! Vem o tempo; está perto o dia, o dia de tumulto, e não de gritos alegres, sobre os montes.

[[v26-7-8]]

^<<v26-7-8,8>>^ Agora depressa derramarei o meu furor sobre ti, e cumprirei a minha ira contra ti, e te julgarei conforme os teus caminhos; e te punirei por todas as tuas abominações.

[[v26-7-9]]

^<<v26-7-9,9>>^ E não te pouparei, nem terei piedade; conforme os teus caminhos, assim te punirei, enquanto as tuas abominações estiverem no meio de ti; e sabereis que eu, o Senhor, castigo.

[[v26-7-10]]

^<<v26-7-10,10>>^ Eis o dia! Eis que vem! Veio a tua ruína; já floresceu a vara, já brotou a soberba. :

[[v26-7-11]]

^<<v26-7-11,11>>^ A violência se levantou em vara de iniqüidade. nada restará deles, nem da sua multidão, nem dos seus bens. Não haverá eminência entre eles.

[[v26-7-12]]

^<<v26-7-12,12>>^ Vem o tempo, é chegado o dia; não se alegre o comprador, e não se entristeça o vendedor; pois a ira está sobre toda a multidão deles.

[[v26-7-13]]

^<<v26-7-13,13>>^ Na verdade o vendedor não tornará a possuir o que vendeu, ainda que esteja por longo tempo entre os viventes; pois a visão, no tocante a toda a multidão deles, não voltará atrás; e ninguém prosperará na vida, pela sua iniqüidade.

[[v26-7-14]]

^<<v26-7-14,14>>^ Já tocaram a trombeta, e tudo prepararam, mas não há quem vá à batalha; pois sobre toda a multidão deles está a minha ira.

[[v26-7-15]]

^<<v26-7-15,15>>^ Fora está a espada, e dentro a peste e a fome; o que estiver no campo morrerá à espada; e o que estiver na cidade, a fome e a peste o consumirão.

[[v26-7-16]]

^<<v26-7-16,16>>^ E se escaparem alguns sobreviventes, estarão sobre os montes, como pombas dos vales, todos gemendo, cada um por causa da sua iniqüidade.

[[v26-7-17]]

^<<v26-7-17,17>>^ Todas as mãos se enfraquecerão, e todos os joelhos se tornarão fracos como água.

[[v26-7-18]]

^<<v26-7-18,18>>^ E se cingirão de sacos, e o terror os cobrirá; e sobre todos os rostos haverá vergonha e sobre todas as suas cabeças calva.

[[v26-7-19]]

^<<v26-7-19,19>>^ A sua prata, lançá-la-ão pelas ruas, e o seu ouro será como imundícia; nem a sua prata nem o seu ouro os poderá livrar no dia do furor do Senhor; esses metais não lhes poderão saciar a fome, nem lhes encher o estômago; pois serviram de tropeço da sua iniqüidade.

[[v26-7-20]]

^<<v26-7-20,20>>^ Converteram em soberba a formosura dos seus adornos, e deles fizeram as imagens das suas abominações, e as suas coisas detestáveis; por isso eu a fiz para eles como uma coisa imunda.

[[v26-7-21]]

^<<v26-7-21,21>>^ E entregá-la-ei nas mãos dos estrangeiros por presa, e aos ímpios da terra por despojo; e a profanarão.

[[v26-7-22]]

^<<v26-7-22,22>>^ E desviarei deles o meu rosto, e profanarão o meu lugar oculto; porque entrarão nele saqueadores, e o profanarão.

[[v26-7-23]]

^<<v26-7-23,23>>^ Faze uma cadeia, porque a terra está cheia de crimes de sangue, e a cidade está cheia de violência.

[[v26-7-24]]

^<<v26-7-24,24>>^ Pelo que trarei dentre as nações os piores, que possuirão as suas casas; e farei cessar a soberba dos poderosos; e os seus lugares santos serão profanados.

[[v26-7-25]]

^<<v26-7-25,25>>^ Quando vier a angústia eles buscarão a paz, mas não haverá paz.

[[v26-7-26]]

^<<v26-7-26,26>>^ Miséria sobre miséria virá, e se levantará rumor sobre rumor; e buscarão do profeta uma visão; mas do sacerdote perecerá a lei, e dos anciãos o conselho.

[[v26-7-27]]

^<<v26-7-27,27>>^ O rei pranteará, e o príncipe se vestirá de desolação, e as mãos do povo da terra tremerão de medo. Conforme o seu caminho lhes farei, e conforme os seus merecimentos os julgarei; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]