include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-19-1]]

^<<v26-19-1,1>>^ E tu levanta uma lamentação sobre os príncipes de Israel,

[[v26-19-2]]

^<<v26-19-2,2>>^ e dize: Que de leoa foi tua mãe entre os leões! Deitou-se no meio dos leõezinhos, criou os seus cachorros.

[[v26-19-3]]

^<<v26-19-3,3>>^ Assim criou um dos seus cachorrinhos, o qual, fazendo-se leão novo, aprendeu a apanhar a presa; e devorou homens.

[[v26-19-4]]

^<<v26-19-4,4>>^ Ora as nações ouviram falar dele; foi apanhado na cova delas; e o trouxeram com ganchos à terra do Egito.

[[v26-19-5]]

^<<v26-19-5,5>>^ Vendo, pois, ela que havia esperado, e que a sua esperança era perdida, tomou outro dos seus cachorros, e fê-lo leão novo.

[[v26-19-6]]

^<<v26-19-6,6>>^ E este, rondando no meio dos leões, veio a ser leão novo, e aprendeu a apanhar a presa; e devorou homens.

[[v26-19-7]]

^<<v26-19-7,7>>^ E devastou os seus palácios, e destruiu as suas cidades; e assolou-se a terra, e a sua plenitude, por causa do som do seu rugido.

[[v26-19-8]]

^<<v26-19-8,8>>^ Então se ajuntaram contra ele as gentes das províncias ao redor; estenderam sobre ele a rede; e ele foi apanhado na cova delas.

[[v26-19-9]]

^<<v26-19-9,9>>^ E com ganchos meteram-no numa jaula, e o levaram ao rei de Babilônia; fizeram-no entrar nos lugares fortes, para que se não ouvisse mais a sua voz sobre os montes de Israel.

[[v26-19-10]]

^<<v26-19-10,10>>^ Tua mãe era como uma videira plantada junto às águas; ela frutificou, e encheu-se de ramos, por causa das muitas águas.

[[v26-19-11]]

^<<v26-19-11,11>>^ E tinha uma vara forte para cetro de governador, e elevou-se a sua estatura entre os espessos ramos, e foi vista na sua altura com a multidão dos seus ramos.

[[v26-19-12]]

^<<v26-19-12,12>>^ Mas foi arrancada com furor, e lançada por terra; o vento oriental secou o seu fruto; quebrou-se e secou-se a sua forte vara; o fogo a consumiu.

[[v26-19-13]]

^<<v26-19-13,13>>^ E agora está plantada no deserto, numa terra seca e sedenta.

[[v26-19-14]]

^<<v26-19-14,14>>^ E duma vara dos seus ramos saiu fogo que consumiu o seu fruto, de maneira que não há mais nela nenhuma vara forte para servir de cetro para governar. Essa é a lamentação, e servirá de lamentação.

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]