include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-21-1]]

^<<v26-21-1,1>>^ Ainda veio a mim a palavra do Senhor, dizendo:

[[v26-21-2]]

^<<v26-21-2,2>>^ Filho do homem, dirige o teu rosto para Jerusalém, e derrama as tuas palavras contra os santuários, e profetiza contra a terra de Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ E dize à terra de Israel: Assim diz o Senhor: Eis que estou contra ti, e tirarei a minha espada da bainha, e exterminarei do meio de ti o justo e o ímpio.

[[v26-21-4]]

^<<v26-21-4,4>>^ E, por isso que hei de exterminar do meio de ti o justo e o ímpio, a minha espada sairá da bainha contra toda a carne, desde o sul até o norte.

[[v26-21-5]]

^<<v26-21-5,5>>^ E saberá toda a carne que eu, o Senhor, tirei a minha espada da bainha nunca mais voltará a ela.

[[v26-21-6]]

^<<v26-21-6,6>>^ Suspira, pois, ó filho do homem; suspira à vista deles com quebrantamento dos teus lombos e com amargura.

[[v26-21-7]]

^<<v26-21-7,7>>^ E será que, quando eles te disserem: Por que suspiras tu dirás: por causa das novas, porque vêm; e todo coração desmaiará, e todas as mãos se enfraquecerão, e todo espírito se angustiará, e todos os joelhos se desfarão em águas; eis que vêm, e se realizarão, diz o Senhor Deus.

[[v26-21-8]]

^<<v26-21-8,8>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-21-9]]

^<<v26-21-9,9>>^ Filho do homem, profetiza, e dize: Assim diz o Senhor; dize: A espada, a espada está afiada e polida.

[[v26-21-10]]

^<<v26-21-10,10>>^ Para matar está afiada, para reluzir está polida. Alegrar-nos-emos pois? A vara de meu filho é que despreza todo o madeiro.

[[v26-21-11]]

^<<v26-21-11,11>>^ E foi dada a polir para ser manejada; esta espada está afiada e polida, para ser posta na mão do matador.

[[v26-21-12]]

^<<v26-21-12,12>>^ Grita e uiva, ó filho do homem, porque ela será contra o meu povo, contra todos os príncipes de Israel. Estes juntamente com o meu povo estão entregues à espada; bate pois na tua coxa.

[[v26-21-13]]

^<<v26-21-13,13>>^ Porque se faz uma prova; e que será se não mais existir a vara desprezadora, diz o Senhor Deus.

[[v26-21-14]]

^<<v26-21-14,14>>^ Tu pois, ó filho do homem, profetiza, e bate com as mãos uma na outra; e dobre-se a espada até a terceira vez, a espada dos mortalmente feridos; é a espada para a grande matança, a que os rodeia.

[[v26-21-15]]

^<<v26-21-15,15>>^ Para que se derreta o coração, e se multipliquem os tropeços, é que contra todas as suas portas pus a ponta da espada; ah! ela foi feita como relâmpago, e está aguçada para matar.

[[v26-21-16]]

^<<v26-21-16,16>>^ e espada, une as tuas forças, vira-te para a direita; prepara-te, vira-te para a esquerda, para onde quer que o teu rosto se dirigir.

[[v26-21-17]]

^<<v26-21-17,17>>^ Também eu baterei com as minhas mãos uma na outra, e farei descansar a minha indignação; eu, o Senhor, o disse.

[[v26-21-18]]

^<<v26-21-18,18>>^ De novo veio a mim a palavra de Senhor, dizendo:

[[v26-21-19]]

^<<v26-21-19,19>>^ Tu pois, ó filho do homem, propõe-te dois caminhos, por onde venha a espada do rei de Babilônia. Ambos procederão de uma mesma terra; e grava um marco, grava-o no princípio do caminho da cidade.

[[v26-21-20]]

^<<v26-21-20,20>>^ Um caminho proporás, por onde virá a espada contra Rabá dos filhos de Amom, e contra Judá, em Jerusalém, a fortificada.

[[v26-21-21]]

^<<v26-21-21,21>>^ Pois o rei de Babilônia está parado na encruzilhada, no princípio dos dois caminhos, para fazer adivinhações; ele sacode as flechas, consulta os terafins, atenta para o fígado.

[[v26-21-22]]

^<<v26-21-22,22>>^ Na sua mão direita estava a adivinhação sobre Jerusalém, para dispor os aríetes, para abrir a boca, ordenando a matança, para levantar a voz com júbilo, para pôr os aríetes contra as portas, para levantar tranqueiras, para edificar baluartes.

[[v26-21-23]]

^<<v26-21-23,23>>^ Isso será como adivinhação vã aos olhos daqueles que lhes fizerem juramentos; mas ele se lembrará da iniqüidade, para que sejam apanhados.

[[v26-21-24]]

^<<v26-21-24,24>>^ Portanto assim diz o Senhor Deus: Visto que fizestes ser lembrada a vossa iniqüidade, descobrindo-se as vossas transgressões, aparecendo os vossos pecados em todos os vossos atos; visto que viestes em memória, sereis apanhados com a mão.

[[v26-21-25]]

^<<v26-21-25,25>>^ E tu, ó profano e ímpio príncipe de Israel, cujo dia é chegado no tempo da punição final;

[[v26-21-26]]

^<<v26-21-26,26>>^ assim diz o Senhor Deus: Remove o diadema, e tira a coroa; esta não será a mesma: exalta ao humilde, e humilha ao soberbo.

[[v26-21-27]]

^<<v26-21-27,27>>^ Ao revés, ao revés, ao revés o porei; também o que é não continuará assim, até que venha aquele a quem pertence de direito; e lho darei a ele.

[[v26-21-28]]

^<<v26-21-28,28>>^ E tu, ó filho do homem, profetiza e dize: Assim diz o Senhor Deus acerca dos filhos de Amom, e acerca do opróbrio deles; dize pois: A espada, a espada está desembainhada, polida para a matança, para consumir, para ser como relâmpago.

[[v26-21-29]]

^<<v26-21-29,29>>^ Enquanto eles têm visões vãs a teu respeito, e adivinham mentiras a fim de que seja posta no pescoço dos ímpios, que estão mortalmente feridos, cujo dia é chegado no tempo da punição final.

[[v26-21-30]]

^<<v26-21-30,30>>^ Torne a tua espada à sua bainha. No lugar em que foste criado, na terra do teu nascimento, eu te julgarei.

[[v26-21-31]]

^<<v26-21-31,31>>^ Derramarei sobre ti a minha indignação, assoprarei contra ti o fogo do meu furor; entregar-te-ei nas mãos dos homens brutais, destros para destruírem.

[[v26-21-32]]

^<<v26-21-32,32>>^ Ao fogo servirás de pasto; o teu sangue estará no meio da terra; não serás mais lembrado; porque eu, o Senhor, o disse.

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]