include::./index.adoc[]

[[v26-1-0]]
=== Ezequiel, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-1-1]]

^<<v26-1-1,1>>^ Ora aconteceu no trigésimo ano, no quarto mês, no dia quinto do mês, que estando eu no meio dos cativos, junto ao rio Quebar, se abriram os céus, e eu tive visões de Deus.

[[v26-1-2]]

^<<v26-1-2,2>>^ No quinto dia do mês, já no quinto ano do cativeiro do rei Joaquim,

[[v26-1-3]]

^<<v26-1-3,3>>^ veio expressamente a palavra do Senhor a Ezequiel, filho de Buzi, o sacerdote, na terra dos caldeus, junto ao rio Quebar; e ali esteve sobre ele a mão do Senhor.

[[v26-1-4]]

^<<v26-1-4,4>>^ Olhei, e eis que um vento tempestuoso vinha do norte, uma grande nuvem, com um fogo que emitia de contínuo labaredas, e um resplendor ao redor dela; e do meio do fogo saía uma coisa como o brilho de âmbar.

[[v26-1-5]]

^<<v26-1-5,5>>^ E do meio dela saía a semelhança de quatro seres viventes. E esta era a sua aparência: tinham a semelhança de homem;

[[v26-1-6]]

^<<v26-1-6,6>>^ cada um tinha quatro rostos, como também cada um deles quatro asas.

[[v26-1-7]]

^<<v26-1-7,7>>^ E as suas pernas eram retas; e as plantas dos seus pés como a planta do pé dum bezerro; e luziam como o brilho de bronze polido.

[[v26-1-8]]

^<<v26-1-8,8>>^ E tinham mãos de homem debaixo das suas asas, aos quatro lados; e todos quatro tinham seus rostos e suas asas assim:

[[v26-1-9]]

^<<v26-1-9,9>>^ Uniam-se as suas asas uma à outra; eles não se viravam quando andavam; cada qual andava para adiante de si;

[[v26-1-10]]

^<<v26-1-10,10>>^ e a semelhança dos seus rostos era como o rosto de homem; e à mão direita todos os quatro tinham o rosto de leão, e à mão esquerda todos os quatro tinham o rosto de boi; e também tinham todos os quatro o rosto de águia;

[[v26-1-11]]

^<<v26-1-11,11>>^ assim eram os seus rostos. As suas asas estavam estendidas em cima; cada qual tinha duas asas que tocavam às de outro; e duas cobriam os corpos deles.

[[v26-1-12]]

^<<v26-1-12,12>>^ E cada qual andava para adiante de si; para onde o espírito havia de ir, iam; não se viravam quando andavam.

[[v26-1-13]]

^<<v26-1-13,13>>^ No meio dos seres viventes havia uma coisa semelhante a ardentes brasas de fogo, ou a tochas que se moviam por entre os seres viventes; e o fogo resplandecia, e do fogo saíam relâmpagos.

[[v26-1-14]]

^<<v26-1-14,14>>^ E os seres viventes corriam, saindo e voltando à semelhança dum raio.

[[v26-1-15]]

^<<v26-1-15,15>>^ Ora, eu olhei para os seres viventes, e vi rodas sobre a terra junto aos seres viventes, uma para cada um dos seus quatro rostos.

[[v26-1-16]]

^<<v26-1-16,16>>^ O aspecto das rodas, e a obra delas, era como o brilho de crisólita; e as quatro tinham uma mesma semelhança; e era o seu aspecto, e a sua obra, como se estivera uma roda no meio de outra roda.

[[v26-1-17]]

^<<v26-1-17,17>>^ Andando elas, iam em qualquer das quatro direções sem se virarem quando andavam.

[[v26-1-18]]

^<<v26-1-18,18>>^ Estas rodas eram altas e formidáveis; e as quatro tinham as suas cambotas cheias de olhos ao redor.

[[v26-1-19]]

^<<v26-1-19,19>>^ E quando andavam os seres viventes, andavam as rodas ao lado deles; e quando os seres viventes se elevavam da terra, elevavam-se também as rodas.

[[v26-1-20]]

^<<v26-1-20,20>>^ Para onde o espírito queria ir, iam eles, mesmo para onde o espírito tinha de ir; e as rodas se elevavam ao lado deles; porque o espírito do ser vivente estava nas rodas.

[[v26-1-21]]

^<<v26-1-21,21>>^ Quando aqueles andavam, andavam estas; e quando aqueles paravam, paravam estas; e quando aqueles se elevavam da terra, elevavam-se também as rodas ao lado deles; porque o espírito do ser vivente estava nas rodas.

[[v26-1-22]]

^<<v26-1-22,22>>^ E por cima das cabeças dos seres viventes havia uma semelhança de firmamento, como o brilho de cristal terrível, estendido por cima, sobre a sua cabeça.

[[v26-1-23]]

^<<v26-1-23,23>>^ E debaixo do firmamento estavam as suas asas direitas, uma em direção à outra; cada um tinha duas que lhe cobriam o corpo dum lado, e cada um tinha outras duas que o cobriam doutro lado.

[[v26-1-24]]

^<<v26-1-24,24>>^ E quando eles andavam, eu ouvia o ruído das suas asas, como o ruído de muitas águas, como a voz do Onipotente, o ruído de tumulto como o ruído dum exército; e, parando eles, abaixavam as suas asas.

[[v26-1-25]]

^<<v26-1-25,25>>^ E ouvia-se uma voz por cima do firmamento, que estava por cima das suas cabeças; parando eles, abaixavam as suas asas.

[[v26-1-26]]

^<<v26-1-26,26>>^ E sobre o firmamento, que estava por cima das suas cabeças, havia uma semelhança de trono, como a aparência duma safira; e sobre a semelhança do trono havia como que a semelhança dum homem, no alto, sobre ele.

[[v26-1-27]]

^<<v26-1-27,27>>^ E vi como o brilho de âmbar, como o aspecto do fogo pelo interior dele ao redor desde a semelhança dos seus lombos, e daí para cima; e, desde a semelhança dos seus lombos, e daí para baixo, vi como a semelhança de fogo, e havia um resplendor ao redor dele.

[[v26-1-28]]

^<<v26-1-28,28>>^ Como o aspecto do arco que aparece na nuvem no dia da chuva, assim era o aspecto do resplendor em redor. Este era o aspecto da semelhança da glória do Senhor; e, vendo isso, caí com o rosto em terra, e ouvi uma voz de quem falava.

'''

xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[&#60; Capítulo Anterior] | <<v26-1-0,Topo>> | xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[Próximo Capítulo &#62;]