include::./index.adoc[]

[[v26-17-0]]
=== Ezequiel, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-17-1]]

^<<v26-17-1,1>>^ Ainda veio a mim a palavra do Senhor, dizendo:

[[v26-17-2]]

^<<v26-17-2,2>>^ Filho do homem, propõe um enigma, e profere uma alegoria à casa de Israel;

[[v26-17-3]]

^<<v26-17-3,3>>^ e dize: Assim diz o Senhor Deus: uma grande águia, de grandes asas e de plumagem comprida, cheia de penas de várias cores, veio ao Líbano e tomou o mais alto ramo dum cedro;

[[v26-17-4]]

^<<v26-17-4,4>>^ arrancou a ponta mais alta dos seus, raminhos, e a levou a uma terra de comércio; e a pôs numa cidade de comerciantes.

[[v26-17-5]]

^<<v26-17-5,5>>^ Também tomou da semente da terra, e a lançou num solo frutífero; pô-la junto a muitas águas; e plantou-a como salgueiro.

[[v26-17-6]]

^<<v26-17-6,6>>^ E brotou, e tornou-se numa videira larga, de pouca altura, virando-se para ela os seus ramos, e as suas raízes estavam debaixo dela. Tornou-se numa videira, e produzia sarmentos, e lançava renovos.

[[v26-17-7]]

^<<v26-17-7,7>>^ Houve ainda outra grande águia, de grandes asas, e cheia de penas; e eis que também esta videira lançou para ela as suas raízes, e estendeu para ela os seus ramos desde as auréolas em que estava plantada, para que ela a regasse.

[[v26-17-8]]

^<<v26-17-8,8>>^ Numa boa terra, junto a muitas águas, estava ela plantada, para produzir ramos, e para dar fruto, a fim de que fosse videira excelente.

[[v26-17-9]]

^<<v26-17-9,9>>^ Dize: Assim diz o Senhor Deus: Acaso prosperará ela? Não lhe arrancará a águia as raízes, e não lhe cortará o fruto, para que se seque? para que se sequem todas as folhas de seus renovos? Não será necessário nem braço forte, nem muita gente, para arrancá-la pelas raízes.

[[v26-17-10]]

^<<v26-17-10,10>>^ Mas, estando plantada, prosperará? Não se secará de todo, quando a tocar o vento oriental? Nas auréolas onde cresceu se secará.

[[v26-17-11]]

^<<v26-17-11,11>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v26-17-12]]

^<<v26-17-12,12>>^ Dize, pois, à casa rebelde: Não sabeis o que significam estas coisas? Dize-lhes: Eis que veio o rei de Babilônia a Jerusalém, e tomou o seu rei e os seus príncipes, e os levou consigo para Babilônia;

[[v26-17-13]]

^<<v26-17-13,13>>^ e tomou um da estirpe real, e fez pacto com ele, e o juramentou. E aos poderosos da terra removeu,

[[v26-17-14]]

^<<v26-17-14,14>>^ para que o reino ficasse humilhado, e não se levantasse, embora, guardando o seu pacto, pudesse subsistir.

[[v26-17-15]]

^<<v26-17-15,15>>^ Mas ele se rebelou contra o rei de Babilônia, enviando os seus embaixadores ao Egito, para que se lhe mandassem cavalos e muita gente. Prosperará ou escapará aquele que faz tais coisas? Quebrará o pacto e escapará?

[[v26-17-16]]

^<<v26-17-16,16>>^ Como eu vivo, diz o Senhor Deus, no lugar em que habita o rei que o fez reinar, cujo juramento desprezou, e cujo pacto quebrou, sim, com ele no meio de Babilônia certamente morrerá.

[[v26-17-17]]

^<<v26-17-17,17>>^ Não lhe prestará Faraó ajuda em guerra, nem com seu grande exército, nem com sua companhia numerosa, quando se levantarem tranqueiras e se edificarem baluartes, para destruir muitas vidas.

[[v26-17-18]]

^<<v26-17-18,18>>^ Porquanto desprezou o juramento e quebrou o pacto, porquanto deu a sua mão, e ainda fez todas estas coisas, ele não escapará.

[[v26-17-19]]

^<<v26-17-19,19>>^ Portanto, assim diz o Senhor Deus: Vivo eu, que o meu juramento que desprezou, e o meu pacto que violou, isso farei recair sobre a sua cabeça.

[[v26-17-20]]

^<<v26-17-20,20>>^ E estenderei sobre ele a minha rede, e ficará preso no meu laço; e o levarei a Babilônia, e ali entrarei em juízo com ele por causa da traição que cometeu contra mim.

[[v26-17-21]]

^<<v26-17-21,21>>^ E a fina flor de todas as suas tropas cairá à espada, e os que restarem serão espalhados a todos os ventos; e sabereis que eu, o Senhor, o disse.

[[v26-17-22]]

^<<v26-17-22,22>>^ Assim diz o Senhor Deus: Também eu tomarei um broto do topo do cedro, e o plantarei; do principal dos seus renovos cortarei o mais tenro, e o plantarei sobre um monte alto e sublime.

[[v26-17-23]]

^<<v26-17-23,23>>^ No monte alto de Israel o plantarei; e produzirá ramos, e dará fruto, e se fará um cedro excelente. Habitarão debaixo dele aves de toda a sorte; à sombra dos seus ramos habitarão.

[[v26-17-24]]

^<<v26-17-24,24>>^ Assim saberão todas as árvores do campo que eu, o Senhor, abati a árvore alta, elevei a árvore baixa, sequei a árvore verde, e fiz reverdecer a árvore seca; eu, e Senhor, o disse, e o farei.

'''

xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]