include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-48-1]]

^<<v26-48-1,1>>^ São estes os nomes das tribos: desde o extremo norte, ao longo do caminho de Hetlom, até a entrada de Hamate, até Hazar-Enom, junto ao termo setentrional de Damasco, defronte de Hamate, com as suas fronteiras estendendo-se do oriente ao ocidente, Dã terá uma porção.

[[v26-48-2]]

^<<v26-48-2,2>>^ Junto ao termo de Dã, desde a fronteira oriental até a fronteira ocidental, Aser terá uma porção.

[[v26-48-3]]

^<<v26-48-3,3>>^ Junto ao termo de Aser, desde a fronteira oriental até a fronteira ocidental, Naftali terá uma porção.

[[v26-48-4]]

^<<v26-48-4,4>>^ Junto ao termo de Naftali, desde a fronteira oriental até a fronteira ocidental, Manasses terá uma porção.

[[v26-48-5]]

^<<v26-48-5,5>>^ Junto ao termo de Manassés, desde a fronteira oriental até a fronteira ocidental, Efraim terá uma porção.

[[v26-48-6]]

^<<v26-48-6,6>>^ Junto ao termo de Efraim, desde a fronteira oriental até a fronteira ocidental, Rúben terá uma porção.

[[v26-48-7]]

^<<v26-48-7,7>>^ Junto ao termo de Rúben desde a fronteira oriental até a fronteira ocidental, Judá terá uma porção.

[[v26-48-8]]

^<<v26-48-8,8>>^ Junto ao termo de Judá, desde a fronteira oriental até a fronteira ocidental, será a oferta que haveis de fazer de vinte e cinco mil canas de largura, e do comprimento de cada uma das porções, desde a fronteira oriental até a fronteira ocidental. O santuário estará no meio dela.

[[v26-48-9]]

^<<v26-48-9,9>>^ A oferta que haveis de fazer ao Senhor será do comprimento de vinte e cinco mil canas, e da largura de dez mil.

[[v26-48-10]]

^<<v26-48-10,10>>^ Será para os sacerdotes uma porção desta santa oferta, medindo para o norte vinte e cinco mil canas de comprimento, para o ocidente dez mil de largura, para o oriente dez mil de largura, e para o sul vinte e cinco mil de comprimento; e o santuário do Senhor estará no meio dela.

[[v26-48-11]]

^<<v26-48-11,11>>^ Sim, será para os sacerdotes consagrados dentre os filhos de Zadoque, que guardaram a minha ordenança, e não se desviaram quando os filhos de Israel se extraviaram, como se extraviaram os outros levitas.

[[v26-48-12]]

^<<v26-48-12,12>>^ E o oferecido ser-lhes-á repartido da santa oferta da terra, coisa santíssima, junto ao termo dos levitas.

[[v26-48-13]]

^<<v26-48-13,13>>^ Também os levitas terão, consoante o termo dos sacerdotes, vinte e cinco mil canas de comprimento, e de largura dez mil; todo o comprimento será vinte e cinco mil, e a largura dez mil.

[[v26-48-14]]

^<<v26-48-14,14>>^ E não venderão nada disto nem o trocarão, nem transferirão as primícias da terra, porque é santo ao Senhor.

[[v26-48-15]]

^<<v26-48-15,15>>^ Mas as cinco mil, as que restam da largura, defronte das vinte e cinco mil, ficarão para uso comum, para a cidade, para habitação e para arrabaldes; e a cidade estará no meio.

[[v26-48-16]]

^<<v26-48-16,16>>^ E estas serão as suas medidas: a fronteira setentrional terá quatro mil e quinhentas canas, e a fronteira do sul quatro mil e quinhentas, e a fronteira oriental quatro mil e quinhentas, e a fronteira ocidental quatro mil e quinhentas.

[[v26-48-17]]

^<<v26-48-17,17>>^ Os arrabaldes, que a cidade terá, serão para o norte de duzentas e cinqüenta canas, e para o sul de duzentas e cinqüenta, e para o oriente de duzentas e cinqüenta, e para o ocidente de duzentas e cinqüenta.

[[v26-48-18]]

^<<v26-48-18,18>>^ E, quanto ao que ficou do resto no comprimento, de conformidade com a santa oferta, será de dez mil para o oriente e dez mil para o ocidente; e corresponderá à santa oferta; e a sua novidade será para sustento daqueles que servem a cidade.

[[v26-48-19]]

^<<v26-48-19,19>>^ E os que servem a cidade, dentre todas as tribos de Israel, cultivá-lo-ão.

[[v26-48-20]]

^<<v26-48-20,20>>^ A oferta inteira será de vinte e cinco mil canas por vinte e cinco mil; em quadrado a oferecereis como porção santa, incluindo o que possui a cidade.

[[v26-48-21]]

^<<v26-48-21,21>>^ O que restar será para o príncipe; desta e da outra banda da santa oferta, e da possessão da cidade; defronte das vinte e cinco mil canas da oferta, na direção do termo oriental, e para o ocidente, defronte das vinte e cinco mil, na direção do termo ocidental, correspondente às porções, isso será a parte do príncipe; e a oferta santa e o santuário do templo estarão no meio.

[[v26-48-22]]

^<<v26-48-22,22>>^ A possessão dos levitas, e a possessão da cidade estarão no meio do que pertencer ao príncipe. Entre o termo de Judá e o termo de Benjamim será a porção do príncipe.

[[v26-48-23]]

^<<v26-48-23,23>>^ Ora quanto ao resto das tribos: desde a fronteira oriental até a fronteira ocidental, Benjamim terá uma porção.

[[v26-48-24]]

^<<v26-48-24,24>>^ Junto ao termo de Benjamim, desde a fronteira oriental até a fronteira ocidental, Simeão terá uma porção.

[[v26-48-25]]

^<<v26-48-25,25>>^ Junto ao termo de Simeão, desde a fronteira oriental até a fronteira ocidental, Issacar terá uma porção.

[[v26-48-26]]

^<<v26-48-26,26>>^ Junto ao termo de Issacar, desde a fronteira oriental até a fronteira ocidental, Zebulom terá uma porção.

[[v26-48-27]]

^<<v26-48-27,27>>^ Junto ao termo de Zebulom, desde a fronteira oriental até a fronteira ocidental, Gade terá uma porção.

[[v26-48-28]]

^<<v26-48-28,28>>^ Junto ao termo de Gade, na fronteira sul, para o sul, o termo será desde Tamar até as águas de Meribate-Cades, até o Ribeiro do Egito, e até o Mar Grande.

[[v26-48-29]]

^<<v26-48-29,29>>^ Esta é a terra que sorteareis em herança para as tribos de Israel, e são estas as suas respectivas porções, diz o Senhor Deus.

[[v26-48-30]]

^<<v26-48-30,30>>^ E estas são as saídas da cidade: da banda do norte quatro mil e quinhentos côvados por medida;

[[v26-48-31]]

^<<v26-48-31,31>>^ e as portas da cidade serão conforme os nomes das tribos de Israel; três portas para o norte; a porta de Rúben a porta de Judá, e a porta de Levi.

[[v26-48-32]]

^<<v26-48-32,32>>^ Da banda do oriente quatro mil e quinhentos côvados, e três portas, a saber: a porta de José, a porta de Benjamim, e a porta de Dã.

[[v26-48-33]]

^<<v26-48-33,33>>^ Da banda do sul quatro mil e quinhentos côvados, e três portas: a porta de Simeão, a porta de Issacar, e a porta de Zebulom.

[[v26-48-34]]

^<<v26-48-34,34>>^ Da banda do ocidente quatro mil e quinhentos côvados, e as suas três portas: a porta de Gade, a porta de Aser, e a porta de Naftali.

[[v26-48-35]]

^<<v26-48-35,35>>^ Dezoito mil côvados terá ao redor; e o nome da cidade desde aquele dia será Jeová-Samá.

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]