include::./index.adoc[]

[[v26-42-0]]
=== Ezequiel, 42
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-42-1]]

^<<v26-42-1,1>>^ Depois disto fez-me sair para fora, ao átrio exterior, que dá para o norte; e me levou às câmaras que estavam defronte do largo vazio, e que estavam defronte do edifício, do lado do norte.

[[v26-42-2]]

^<<v26-42-2,2>>^ Do comprimento de cem côvados era esse edifício, e da largura de cinqüenta côvados.

[[v26-42-3]]

^<<v26-42-3,3>>^ Em frente dos vinte côvados, que tinha o átrio interior, e em frente do pavimento que tinha o átrio exterior, havia galeria contra galeria em três andares.

[[v26-42-4]]

^<<v26-42-4,4>>^ E diante das câmaras havia um passeio que dava para o átrio interior, e que tinha dez côvados de largura e cem côvados de comprimento; e as suas portas davam para o norte.

[[v26-42-5]]

^<<v26-42-5,5>>^ Ora, as câmaras superiores eram mais estreitas; porque as galerias tomavam destas mais espaço do que das de baixo e das do meio do edifício.

[[v26-42-6]]

^<<v26-42-6,6>>^ Porque elas eram de três andares e não tinham colunas como as colunas dos átrios; por isso desde o chão se iam estreitando mais do que as de baixo e as do meio.

[[v26-42-7]]

^<<v26-42-7,7>>^ No lado de fora, em paralelo às câmaras e defronte delas no caminho do átrio exterior, havia um muro que tinha cinqüenta côvados de comprimento.

[[v26-42-8]]

^<<v26-42-8,8>>^ Pois o comprimento da série de câmaras que estavam no átrio exterior era de cinqüenta côvados, enquanto o da série que estava defronte do templo era de cem côvados.

[[v26-42-9]]

^<<v26-42-9,9>>^ Por debaixo destas câmaras estava a entrada do lado do oriente, para quem entra nelas do átrio exterior.

[[v26-42-10]]

^<<v26-42-10,10>>^ Na grossura do muro do átrio que dava para o oriente, diante do lugar separado, e diante do edifício, havia também câmaras,

[[v26-42-11]]

^<<v26-42-11,11>>^ com um caminho diante delas, que eram da mesma feição das câmaras que davam para o norte, sendo do mesmo comprimento, e da mesma largura, com as mesmas saídas, disposições e portas.

[[v26-42-12]]

^<<v26-42-12,12>>^ E conforme eram as portas das câmaras que davam para o sul, era também a porta no topo do caminho, isto é, do caminho bem em frente do muro à direita para quem entra.

[[v26-42-13]]

^<<v26-42-13,13>>^ Então me disse: As câmaras do norte, e as câmaras do sul, que estão diante do lugar separado, são câmaras santas, em que os sacerdotes que se chegam ao Senhor comerão as coisas santíssimas. Ali porão as coisas santíssimas, as ofertas de cereais, as ofertas pelo pecado, e as ofertas pela culpa; porque o lugar é santo.

[[v26-42-14]]

^<<v26-42-14,14>>^ Quando os sacerdotes entrarem, não sairão do santuário para o átrio exterior, mas porão ali as suas vestiduras em que ministram, porque elas são santas; e vestir-se-ão doutras vestiduras, e assim se aproximarão do lugar pertencente ao povo.

[[v26-42-15]]

^<<v26-42-15,15>>^ Tendo ele acabado de medir o templo interior, fez-me sair pelo caminho da porta oriental; e o mediu em redor.

[[v26-42-16]]

^<<v26-42-16,16>>^ Mediu o lado oriental com a cana de medir, quinhentas canas de largura.

[[v26-42-17]]

^<<v26-42-17,17>>^ Mediu o lado do norte, quinhentas canas, com a cana de medir.

[[v26-42-18]]

^<<v26-42-18,18>>^ Mediu também o lado do sul, quinhentas canas, com a cana de medir.

[[v26-42-19]]

^<<v26-42-19,19>>^ Deu uma volta para o lado do ocidente, e mediu quinhentas canas, com a cana de medir.

[[v26-42-20]]

^<<v26-42-20,20>>^ Mediu-o pelos quatro lados. Havia um muro em redor, de quinhentas canas de comprimento, e quinhentas de largura, para fazer separação entre o santo e o profano.

'''

xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[&#60; Capítulo Anterior] | <<v26-42-0,Topo>> | xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[Próximo Capítulo &#62;]