include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-22-1]]

^<<v26-22-1,1>>^ Demais veio a mim a palavra do Senhor, dizendo:

[[v26-22-2]]

^<<v26-22-2,2>>^ Tu pois, ó filho do homem, acaso julgarás, julgarás mesmo a cidade sanguinária? Então faze-lhe conhecer todas as suas abominações,

[[v26-22-3]]

^<<v26-22-3,3>>^ e dize: Assim diz o Senhor Deus: A cidade que derrama o sangue dentro de si, para que venha o seu tempo! que faz ídolos contra si mesma, para se contaminar!

[[v26-22-4]]

^<<v26-22-4,4>>^ Pelo teu sangue que derramaste te fizeste culpada, e pelos teus ídolos que fabricaste te contaminaste; e fizeste aproximar-se o teu dia, e é chegado o fim dos teus anos. Por isso eu te fiz o opróbrio das nações e o escárnio de todas as terras.

[[v26-22-5]]

^<<v26-22-5,5>>^ As que estão perto e as que estão longe de ti escarnecerão de ti, infamada, cheia de tumulto.

[[v26-22-6]]

^<<v26-22-6,6>>^ Eis que os príncipes de Israel, que estão em ti, cada um conforme o seu poder, se esforçam para derramarem sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ No meio de ti desprezaram ao pai e à mãe; no meio de ti usaram de opressão para com o estrangeiro; no meio de ti foram injustos para com o órfão e a viúva.

[[v26-22-8]]

^<<v26-22-8,8>>^ As minhas coisas santas desprezaste, e os meus sábados profanaste.

[[v26-22-9]]

^<<v26-22-9,9>>^ Em ti se acham homens que caluniam para derramarem sangue; em ti há os que comem sobre os montes; e cometem perversidade no meio de ti.

[[v26-22-10]]

^<<v26-22-10,10>>^ A vergonha do pai descobrem em ti; no meio de ti humilham a que está impura, na sua separação.

[[v26-22-11]]

^<<v26-22-11,11>>^ Um comete abominação com a mulher do seu próximo, outro contamina abominavelmente a sua nora, e outro humilha no meio de ti a sua irmã, filha de seu pai.

[[v26-22-12]]

^<<v26-22-12,12>>^ Peitas se recebem no meio de ti para se derramar sangue; recebes usura e ganhos ilícitos, e usas de avareza com o teu próximo, oprimindo-o; mas de mim te esqueceste, diz o Senhor Deus.

[[v26-22-13]]

^<<v26-22-13,13>>^ Eis que, portanto, bato as mãos contra o lucro desonesto que ganhaste, e por causa do sangue que houve no meio de ti.

[[v26-22-14]]

^<<v26-22-14,14>>^ Poderá estar firme o teu coração? poderão estar fortes as tuas mãos, nos dias em que eu tratarei contigo? Eu, o Senhor, o disse, e o farei.

[[v26-22-15]]

^<<v26-22-15,15>>^ Espalhar-te-ei entre as nações e dispersar-te-ei pelas terras; e de ti consumirei a tua imundícia.

[[v26-22-16]]

^<<v26-22-16,16>>^ E tu serás profanada em ti mesma, aos olhos das nações, e saberás que eu sou o Senhor.

[[v26-22-17]]

^<<v26-22-17,17>>^ De novo veio a mim a palavra do Senhor, dizendo:

[[v26-22-18]]

^<<v26-22-18,18>>^ Filho do homem, a casa de Israel se tornou para mim em escória; todos eles são bronze, e estanho, e ferro, e chumbo no meio da fornalha; em escória de prata eles se tornaram.

[[v26-22-19]]

^<<v26-22-19,19>>^ Portanto assim diz o Senhor Deus: Pois que todos vós vos tornastes em escória, por isso eis que eu vos ajuntarei no meio de Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Como se ajuntam a prata, e o bronze, e o ferro, e o chumbo, e o estanho, no meio da fornalha, para assoprar o fogo sobre eles, a fim de se fundirem, assim vos ajuntarei na minha ira e no meu furor, e ali vos porei e vos fundirei.

[[v26-22-21]]

^<<v26-22-21,21>>^ Sim, congregar-vos-ei, e assoprarei sobre vós o fogo da minha ira; e sereis fundidos no meio dela.

[[v26-22-22]]

^<<v26-22-22,22>>^ Como se funde a prata no meio da fornalha, assim sereis fundidos no meio dela; e sabereis que eu, o Senhor, derramei o meu furor sobre vós.

[[v26-22-23]]

^<<v26-22-23,23>>^ Também veio a mim a palavra do Senhor, dizendo:

[[v26-22-24]]

^<<v26-22-24,24>>^ Filho do homem, dize-lhe a ela: Tu és uma terra que não está purificada, nem regada de chuvas no dia da indignação.

[[v26-22-25]]

^<<v26-22-25,25>>^ Conspiração dos seus profetas há no meio dela, como um leão que ruge, que arrebata a presa; eles devoram vidas humanas; tomam tesouros e coisas preciosas; multiplicam as suas viúvas no meio dela.

[[v26-22-26]]

^<<v26-22-26,26>>^ Os seus sacerdotes violentam a minha lei, e profanam as minhas coisas santas; não fazem diferença entre o santo e o profano, nem ensinam a discernir entre o impuro e o puro; e de meus sábados escondem os seus olhos, e assim sou profanado no meio deles.

[[v26-22-27]]

^<<v26-22-27,27>>^ Os seus príncipes no meio dela são como lobos que arrebatam a presa: derramando o sangue, e destruindo vidas, para adquirirem lucro desonesto.

[[v26-22-28]]

^<<v26-22-28,28>>^ E os profetas têm feito para eles reboco com argamassa fraca tendo visões falsas, e adivinhando-lhes mentira, dizendo: Assim diz o Senhor Deus; sem que o Senhor tivesse falado.

[[v26-22-29]]

^<<v26-22-29,29>>^ O povo da terra tem usado de opressão, e andado roubando e fazendo violência ao pobre e ao necessitado, e tem oprimido injustamente ao estrangeiro.

[[v26-22-30]]

^<<v26-22-30,30>>^ E busquei dentre eles um homem que levantasse o muro, e se pusesse na brecha perante mim por esta terra, para que eu não a destruísse; porém a ninguém achei.

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso eu derramei sobre eles a minha indignação; com o fogo do meu furor os consumi; fiz que o seu caminho lhes recaísse sobre a cabeça, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]