include::./index.adoc[]

[[v26-6-0]]
=== Ezequiel, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-6-1]]

^<<v26-6-1,1>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-6-2]]

^<<v26-6-2,2>>^ Filho do homem, dirige o teu rosto para os montes de Israel, e profetiza contra eles.

[[v26-6-3]]

^<<v26-6-3,3>>^ E dize: Montes de Israel, ouvi a palavra do Senhor Deus. Assim diz o Senhor Deus aos montes, aos outeiros, às ravinas e aos vales: Eis que eu, sim eu, trarei a espada sobre vós, e destruirei os vossos altos.

[[v26-6-4]]

^<<v26-6-4,4>>^ E serão assolados os vossos altares, e quebrados os vossos altares de incenso; e arrojarei os vossos mortos diante dos vossos ídolos.

[[v26-6-5]]

^<<v26-6-5,5>>^ E porei os cadáveres dos filhos de Israel diante dos seus ídolos, e espalharei os vossos ossos em redor dos vossos altares.

[[v26-6-6]]

^<<v26-6-6,6>>^ Em todos os vossos lugares habitáveis as cidades serão destruídas, e os altos assolados; para que os vossos altares sejam destruídos e assolados, e os vossos ídolos se quebrem e sejam destruídos, e os altares de incenso sejam cortados, e desfeitas as vossas obras.

[[v26-6-7]]

^<<v26-6-7,7>>^ E os traspassados cairão no meio de vós, e sabereis que eu sou o Senhor.

[[v26-6-8]]

^<<v26-6-8,8>>^ Contudo deixarei com vida um restante, visto que tereis alguns que escaparão da espada entre as nações, quando fordes espalhados pelos países.

[[v26-6-9]]

^<<v26-6-9,9>>^ Então os que dentre vós escaparem se lembrarão de mim entre as nações para onde forem levados em cativeiro, quando eu lhes tiver quebrantado o coração corrompido, que se desviou de mim, e cegado os seus olhos, que se vão corrompendo após os seus ídolos; e terão nojo de si mesmos, por causa das maldades que fizeram em todas as suas abominações.

[[v26-6-10]]

^<<v26-6-10,10>>^ E saberão que eu sou o Senhor; não disse debalde que lhes faria este mal.

[[v26-6-11]]

^<<v26-6-11,11>>^ Assim diz o Senhor Deus: Bate com a mão, e bate com o teu pé, e dize: Ah! por causa de todas as péssimas abominações da casa de Israel; pois eles cairão à espada, e de fome, e de peste.

[[v26-6-12]]

^<<v26-6-12,12>>^ O que estiver longe morrerá de peste; e, o que está perto cairá à espada; e o que ficar de resto e cercado morrerá de fome; assim cumprirei o meu furor contra eles.

[[v26-6-13]]

^<<v26-6-13,13>>^ Então sabereis que eu sou o Senhor, quando os seus mortos estiverem estendidos no meio dos seus ídolos, em redor dos seus altares, em todo outeiro alto, em todos os cumes dos montes, e debaixo de toda árvore verde, e debaixo de todo carvalho frondoso, lugares onde ofereciam suave cheiro a todos os seus ídolos.

[[v26-6-14]]

^<<v26-6-14,14>>^ E estenderei a minha mão sobre eles, e farei a terra desolada e erma, em todas as suas habitações; desde o deserto até Dibla; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]