include::./index.adoc[]

[[v26-41-0]]
=== Ezequiel, 41
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-41-1]]

^<<v26-41-1,1>>^ Então me levou ao templo, e mediu as umbreiras, seis côvados de largura de uma banda, e seis côvados de largura da outra, que era a largura do tabernáculo.

[[v26-41-2]]

^<<v26-41-2,2>>^ E a largura da entrada era de dez côvados; e os lados da entrada, cinco côvados de uma banda e cinco côvados da outra; também mediu o seu comprimento, de quarenta côvados, e a largura, de vinte côvados.

[[v26-41-3]]

^<<v26-41-3,3>>^ E entrou dentro, e mediu cada umbral da entrada, dois côvados; e a entrada, seis côvados; e a largura da entrada, sete côvados.

[[v26-41-4]]

^<<v26-41-4,4>>^ Também mediu o seu comprimento, vinte côvados, e a largura, vinte côvados, diante do templo; e disse-me: Este é o lugar santíssimo.

[[v26-41-5]]

^<<v26-41-5,5>>^ Então mediu a parede do templo, seis côvados, e a largura de cada câmara lateral, quatro côvados, por todo o redor do templo.

[[v26-41-6]]

^<<v26-41-6,6>>^ E as câmaras laterais eram de três andares, câmara sobre câmara, e trinta em cada andar; e elas entravam na parede que tocava no templo para essas câmaras laterais em redor, para se susterem nela, porque não travavam da parede do templo.

[[v26-41-7]]

^<<v26-41-7,7>>^ Também as câmaras laterais aumentavam de largura de andar em andar, ao passo que se aprofundava a reentrância da parede de andar em andar em volta do templo; e havia ao lado do templo uma escadaria pela qual se subia do primeiro ao terceiro andar mediante o segundo.

[[v26-41-8]]

^<<v26-41-8,8>>^ Vi também que havia ao redor do templo um pavimento elevado; os fundamentos das câmaras laterais eram da medida de uma cana inteira, seis côvados grandes.

[[v26-41-9]]

^<<v26-41-9,9>>^ A grossura da parede exterior das câmaras laterais era de cinco côvados; e o que sobrava do pavimento fora das câmaras laterais, que estavam junto ao templo, também era de cinco côvados.

[[v26-41-10]]

^<<v26-41-10,10>>^ E por fora das câmaras havia um espaço livre de vinte côvados de largura em toda a volta do templo.

[[v26-41-11]]

^<<v26-41-11,11>>^ E as entradas das câmaras laterais estavam voltadas para a parte do pavimento que sobrava, uma entrada para o lado do norte, e outra entrada para o do sul; e a largura desta parte do pavimento era de cinco côvados em redor.

[[v26-41-12]]

^<<v26-41-12,12>>^ Era também o edifício que estava diante do lugar separado, ao lado que olha para o ocidente, da largura de setenta côvados; e a parede do edifício era de cinco côvados de largura em redor, e o seu comprimento de noventa côvados.

[[v26-41-13]]

^<<v26-41-13,13>>^ Assim mediu o templo, do comprimento de cem côvados, como também o lugar separado, e o edifício, e as suas paredes, cem côvados de comprimento.

[[v26-41-14]]

^<<v26-41-14,14>>^ E a largura da dianteira do templo, e do lugar separado que olha para o oriente, cem côvados.

[[v26-41-15]]

^<<v26-41-15,15>>^ Também mediu o comprimento do edifício, diante do lugar separado, que estava por detrás, e as suas galerias de um e de outro lado, cem côvados. A nave do templo, a câmara interior, e o vestíbulo do átrio eram forrados;

[[v26-41-16]]

^<<v26-41-16,16>>^ e os três tinham janelas gradeadas. As galerias em redor nos três andares, defronte do limiar, eram forradas de madeira em redor, e isto desde o chão até as janelas &#123;ora as janelas estavam cobertas&#125;,

[[v26-41-17]]

^<<v26-41-17,17>>^ até o espaço em cima da porta para a câmara interior, por dentro e por fora. E em todas as paredes em redor, por dentro e por fora, tudo por medida.

[[v26-41-18]]

^<<v26-41-18,18>>^ havia querubins e palmeiras de entalhe; e havia uma palmeira entre querubim e querubim; e cada querubim tinha dois rostos,

[[v26-41-19]]

^<<v26-41-19,19>>^ de modo que o rosto de homem olhava para a palmeira de um lado, e o rosto de leão novo para a palmeira do outro lado; assim era pela casa toda em redor.

[[v26-41-20]]

^<<v26-41-20,20>>^ Desde o chão até acima da entrada estavam entalhados querubins e palmeiras, como também pela parede do templo.

[[v26-41-21]]

^<<v26-41-21,21>>^ As ombreiras das portas do templo eram quadradas; e diante do santuário havia uma coisa semelhante

[[v26-41-22]]

^<<v26-41-22,22>>^ a um altar de madeira, de três côvados de altura, e o seu comprimento era de dois côvados; os seus cantos, o seu fundamento e as suas paredes eram de madeira; e disse-me: Esta é a mesa que está perante a face do Senhor.

[[v26-41-23]]

^<<v26-41-23,23>>^ Ora, a nave e o santuário ambos tinham portas duplas.

[[v26-41-24]]

^<<v26-41-24,24>>^ As portas tinham cada uma duas folhas que viravam, duas para uma porta, e duas para a outra.

[[v26-41-25]]

^<<v26-41-25,25>>^ E havia nas portas da nave querubins e palmeiras de entalhe, como os que estavam nas paredes; e havia um grande toldo de madeira diante do vestíbulo por fora.

[[v26-41-26]]

^<<v26-41-26,26>>^ Também havia janelas fechadas e palmeiras, de uma e de outra banda, pelos lados do vestíbulo.

'''

xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]