include::./index.adoc[]

[[v26-31-0]]
=== Ezequiel, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-31-1]]

^<<v26-31-1,1>>^ Também sucedeu, no ano undécimo, no terceiro mês, ao primeiro do mês, que veio a mim a palavra do Senhor, dizendo:

[[v26-31-2]]

^<<v26-31-2,2>>^ Filho do homem, dize a Faraó, rei do Egito, e à sua multidão: A quem és semelhante na tua grandeza?

[[v26-31-3]]

^<<v26-31-3,3>>^ Eis que o assírio era como um cedro do Líbano, de ramos formosos, de sombrosa ramagem e de alta estatura; e a sua copa estava entre os ramos espessos.

[[v26-31-4]]

^<<v26-31-4,4>>^ As águas nutriram-no, o abismo fê-lo crescer; as suas correntes corriam em torno da sua plantação; assim ele enviava os seus regatos a todas as árvores do campo.

[[v26-31-5]]

^<<v26-31-5,5>>^ Por isso se elevou a sua estatura sobre todas as árvores do campo, e se multiplicaram os seus ramos, e se alongaram as suas varas, por causa das muitas águas nas suas raízes.

[[v26-31-6]]

^<<v26-31-6,6>>^ Todas as aves do céu se aninhavam nos seus ramos; e todos os animais do campo geravam debaixo dos seus ramos; e à sua sombra habitavam todos os grandes povos.

[[v26-31-7]]

^<<v26-31-7,7>>^ Assim era ele formoso na sua grandeza, na extensão dos seus ramos, porque a sua raiz estava junto às muitas águas.

[[v26-31-8]]

^<<v26-31-8,8>>^ Os cedros no jardim de Deus não o podiam esconder; as faias não igualavam os seus ramos, e os plátanos não eram como as suas varas; nenhuma árvore no jardim de Deus se assemelhava a ele na sua formosura.

[[v26-31-9]]

^<<v26-31-9,9>>^ Formoso o fiz pela abundância dos seus ramos; de modo que tiveram inveja dele todas as árvores do Edem que havia no jardim de Deus.

[[v26-31-10]]

^<<v26-31-10,10>>^ Portanto assim diz o Senhor Deus: Como se elevou na sua estatura, e se levantou a sua copa no meio dos espessos ramos, e o seu coração se ufanava da sua altura,

[[v26-31-11]]

^<<v26-31-11,11>>^ eu o entregarei na mão da mais poderosa das nações, que lhe dará o tratamento merecido. Eu já o lancei fora.

[[v26-31-12]]

^<<v26-31-12,12>>^ Estrangeiros, da mais terrível das nações, o cortarão, e o deixarão; cairão os seus ramos sobre os montes e por todos os vales, e os seus renovos serão quebrados junto a todas as correntes da terra; e todos os povos da terra se retirarão da sua sombra, e o deixarão.

[[v26-31-13]]

^<<v26-31-13,13>>^ Todas as aves do céu habitarão sobre a sua ruína, e todos os animais do campo estarão sobre os seus ramos;

[[v26-31-14]]

^<<v26-31-14,14>>^ para que nenhuma de todas as árvores junto às águas se exalte na sua estatura, nem levante a sua copa no meio dos ramos espessos, nem se levantem na sua altura os seus poderosos, sim, todos os que bebem água; porque todos eles estão entregues à morte, até as partes inferiores da terra, no meio dos filhos dos homens, juntamente com os que descem a cova.

[[v26-31-15]]

^<<v26-31-15,15>>^ Assim diz o Senhor Deus: No dia em que ele desceu ao Seol, fiz eu que houvesse luto; cobri o abismo, por sua causa, e retive as suas correntes, e detiveram-se as grandes águas; e fiz que o Líbano o pranteasse; e todas as árvores do campo por causa dele desfaleceram.

[[v26-31-16]]

^<<v26-31-16,16>>^ Farei tremer as nações ao som da sua queda, quando o fizer descer ao Seol juntamente com os que descem à cova; e todas as árvores do Edem a flor e o melhor do Líbano, todas as que bebem águas, se consolarão nas partes inferiores da terra;

[[v26-31-17]]

^<<v26-31-17,17>>^ também juntamente com ele descerão ao Seol, ajuntar-se aos que foram mortos à espada; sim, aos que foram seu braço, e que habitavam à sua sombra no meio das nações.

[[v26-31-18]]

^<<v26-31-18,18>>^ A quem, pois, és semelhante em glória e em grandeza entre as árvores do Eden? Todavia serás precipitado juntamente com as árvores do Eden às partes inferiores da terra; no meio dos incircuncisos jazerás com os que foram mortos à espada: este é Faraó e toda a sua multidão, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]