include::./index.adoc[]

[[v26-37-0]]
=== Ezequiel, 37
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-37-1]]

^<<v26-37-1,1>>^ Veio sobre mim a mão do Senhor; e ele me levou no Espírito do Senhor, e me pôs no meio do vale que estava cheio de ossos;

[[v26-37-2]]

^<<v26-37-2,2>>^ e me fez andar ao redor deles. E eis que eram muito numerosos sobre a face do vale; e eis que estavam sequíssimos.

[[v26-37-3]]

^<<v26-37-3,3>>^ Ele me perguntou: Filho do homem, poderão viver estes ossos? Respondi: Senhor Deus, tu o sabes.

[[v26-37-4]]

^<<v26-37-4,4>>^ Então me disse: Profetiza sobre estes ossos, e dize-lhes: Ossos secos, ouvi a palavra do Senhor.

[[v26-37-5]]

^<<v26-37-5,5>>^ Assim diz o Senhor Deus a estes ossos: Eis que vou fazer entrar em vós o fôlego da vida, e vivereis.

[[v26-37-6]]

^<<v26-37-6,6>>^ E porei nervos sobre vós, e farei crescer carne sobre vós, e sobre vos estenderei pele, e porei em vós o fôlego da vida, e vivereis. Então sabereis que eu sou o Senhor.

[[v26-37-7]]

^<<v26-37-7,7>>^ Profetizei, pois, como se me deu ordem. Ora enquanto eu profetizava, houve um ruído; e eis que se fez um rebuliço, e os ossos se achegaram, osso ao seu osso.

[[v26-37-8]]

^<<v26-37-8,8>>^ E olhei, e eis que vieram nervos sobre eles, e cresceu a carne, e estendeu-se a pele sobre eles por cima; mas não havia neles fôlego.

[[v26-37-9]]

^<<v26-37-9,9>>^ Então ele me disse: Profetiza ao fôlego da vida, profetiza, ó filho do homem, e dize ao fôlego da vida: Assim diz o Senhor Deus: Vem dos quatro ventos, ó fôlego da vida, e assopra sobre estes mortos, para que vivam.

[[v26-37-10]]

^<<v26-37-10,10>>^ Profetizei, pois, como ele me ordenara; então o fôlego da vida entrou neles e viveram, e se puseram em pé, um exército grande em extremo.

[[v26-37-11]]

^<<v26-37-11,11>>^ Então me disse: Filho do homem, estes ossos são toda a casa de Israel. Eis que eles dizem: Os nossos ossos secaram-se, e pereceu a nossa esperança; estamos de todo cortados.

[[v26-37-12]]

^<<v26-37-12,12>>^ Portanto profetiza, e dize-lhes: Assim diz o Senhor Deus: Eis que eu vos abrirei as vossas sepulturas, sim, das vossas sepulturas vos farei sair, ó povo meu, e vos trarei à terra de Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ E quando eu vos abrir as sepulturas, e delas vos fizer sair, ó povo meu, sabereis que eu sou o Senhor.

[[v26-37-14]]

^<<v26-37-14,14>>^ E porei em vós o meu Espírito, e vivereis, e vos porei na vossa terra; e sabereis que eu, o Senhor, o falei e o cumpri, diz o Senhor.

[[v26-37-15]]

^<<v26-37-15,15>>^ A palavra do Senhor veio a mim, dizendo:

[[v26-37-16]]

^<<v26-37-16,16>>^ Tu, pois, ó filho do homem, toma um pau, e escreve nele: Por Judá e pelos filhos de Israel, seus companheiros. Depois toma outro pau, e escreve nele: Por José, vara de Efraim, e por toda a casa de Israel, seus companheiros;

[[v26-37-17]]

^<<v26-37-17,17>>^ e ajunta um ao outro, para que se unam, e se tornem um só na tua mão.

[[v26-37-18]]

^<<v26-37-18,18>>^ E quando te falarem os filhos do teu povo, dizendo: Porventura não nos declararás o que queres dizer com estas coisas?

[[v26-37-19]]

^<<v26-37-19,19>>^ Tu lhes dirás: Assim diz o Senhor Deus: Eis que eu tomarei a vara de José, que esteve na mão de Efraim, e as das tribos de Israel, suas companheiras, e lhes ajuntarei a vara de Judá, e farei delas uma só vara, e elas se farão uma só na minha mão.

[[v26-37-20]]

^<<v26-37-20,20>>^ E os paus, sobre que houveres escrito, estarão na tua mão, perante os olhos deles.

[[v26-37-21]]

^<<v26-37-21,21>>^ Dize-lhes pois: Assim diz o Senhor Deus: Eis que eu tomarei os filhos de Israel dentre as nações para onde eles foram, e os congregarei de todos os lados, e os introduzirei na sua terra;

[[v26-37-22]]

^<<v26-37-22,22>>^ e deles farei uma nação na terra, nos montes de Israel, e um rei será rei de todos eles; e nunca mais serão duas nações, nem de maneira alguma se dividirão para o futuro em dois reinos;

[[v26-37-23]]

^<<v26-37-23,23>>^ nem se contaminarão mais com os seus ídolos, nem com as suas abominações, nem com qualquer uma das suas transgressões; mas eu os livrarei de todas as suas apostasias com que pecaram, e os purificarei. Assim eles serão o meu povo, e eu serei o seu Deus.

[[v26-37-24]]

^<<v26-37-24,24>>^ Também meu servo Davi reinará sobre eles, e todos eles terão um pastor só; andarão nos meus juízos, e guardarão os meus estatutos, e os observarão.

[[v26-37-25]]

^<<v26-37-25,25>>^ Ainda habitarão na terra que dei a meu servo Jacó, na qual habitaram vossos pais; nela habitarão, eles e seus filhos, e os filhos de seus filhos, para sempre; e Davi, meu servo, será seu príncipe eternamente.

[[v26-37-26]]

^<<v26-37-26,26>>^ Farei com eles um pacto de paz, que será um pacto perpétuo. E os estabelecerei, e os multiplicarei, e porei o meu santuário no meio deles para sempre.

[[v26-37-27]]

^<<v26-37-27,27>>^ Meu tabernáculo permanecerá com eles; e eu serei o seu Deus e eles serão o meu povo.

[[v26-37-28]]

^<<v26-37-28,28>>^ E as nações saberão que eu sou o Senhor que santifico a Israel, quando estiver o meu santuário no meio deles para sempre.

'''

xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]