include::./index.adoc[]

[[v26-46-0]]
=== Ezequiel, 46
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-46-1]]

^<<v26-46-1,1>>^ Assim diz o Senhor Deus: A porta do átrio interior, que dá para o oriente, estará fechada durante os seis dias que são de trabalho; mas no dia de sábado ela se abrirá; também no dia da lua nova se abrirá.

[[v26-46-2]]

^<<v26-46-2,2>>^ E o príncipe entrará pelo caminho do vestíbulo da porta, por fora, e ficará parado junto da ombreira da porta, enquanto os sacerdotes ofereçam o holocausto e as ofertas pacíficas dele; e ele adorará junto ao limiar da porta. Então sairá; mas a porta não se fechará até a tarde.

[[v26-46-3]]

^<<v26-46-3,3>>^ E o povo da terra adorará à entrada da mesma porta, nos sábados e nas luas novas, diante do Senhor.

[[v26-46-4]]

^<<v26-46-4,4>>^ E o holocausto que o príncipe oferecer ao Senhor será, no dia de sábado, seis cordeiros sem mancha e um carneiro sem mancha;

[[v26-46-5]]

^<<v26-46-5,5>>^ e a oferta de cereais será uma efa para o carneiro; e para o cordeiro, a oferta de cereais será o que puder dar, com um him de azeite para cada efa.

[[v26-46-6]]

^<<v26-46-6,6>>^ Mas no dia da lua nova será um bezerro sem mancha, e seis cordeiros e um carneiro; eles serão sem mancha.

[[v26-46-7]]

^<<v26-46-7,7>>^ Também ele proverá, por oferta de cereais, uma efa para o novilho e uma efa para o carneiro, e para os cordeiros o que puder, com um him de azeite para cada efa.

[[v26-46-8]]

^<<v26-46-8,8>>^ Quando entrar o príncipe, entrará pelo caminho do vestíbulo da porta, e sairá pelo mesmo caminho.

[[v26-46-9]]

^<<v26-46-9,9>>^ Mas, quando vier o povo da terra perante o Senhor nas festas fixas, aquele que entrar pelo caminho da porta do norte, para adorar, sairá pelo caminho da porta do sul; e aquele que entrar pelo caminho da porta do sul, sairá pelo caminho da porta do norte. Não tornará pelo caminho da porta pela qual entrou, mas sairá seguindo para a sua frente.

[[v26-46-10]]

^<<v26-46-10,10>>^ Ao entrarem eles, o príncipe entrará no meio deles; e, saindo eles, sairão juntos.

[[v26-46-11]]

^<<v26-46-11,11>>^ Nas solenidades, inclusive nas festas fixas, a oferta de cereais será uma efa para um novilho, e uma efa para um carneiro, mas para os cordeiros será o que se puder dar; e de azeite um him para cada efa.

[[v26-46-12]]

^<<v26-46-12,12>>^ Quando o príncipe prover uma oferta voluntária, holocausto, ou ofertas pacíficas, como uma oferta voluntária ao Senhor, abrir-se-lhe-á a porta que dá para o oriente, e oferecerá o seu holocausto e as suas ofertas pacíficas, como houver feito no dia de sábado. Então sairá e, depois de ele ter saído, fechar-se-á a porta.

[[v26-46-13]]

^<<v26-46-13,13>>^ Proverá ele um cordeiro de um ano, sem mancha, em holocausto ao Senhor cada dia; de manhã em manhã o proverá.

[[v26-46-14]]

^<<v26-46-14,14>>^ Juntamente com ele proverá de manhã em manhã uma oferta de cereais, a sexta parte duma efa de flor de farinha, com a terça parte de um him de azeite para umedecê-la, por oferta de cereais ao Senhor, continuamente, por estatuto perpétuo.

[[v26-46-15]]

^<<v26-46-15,15>>^ Assim se proverão o cordeiro, a oferta de cereais, e o azeite, de manhã em manhã, em holocausto contínuo.

[[v26-46-16]]

^<<v26-46-16,16>>^ Assim diz o Senhor Deus: Se o príncipe der um presente a algum de seus filhos, é herança deste, pertencerá a seus filhos; será possessão deles por herança.

[[v26-46-17]]

^<<v26-46-17,17>>^ Se, porém, der um presente da sua herança a algum dos seus servos, será deste até o ano da liberdade; então tornará para o príncipe; pois quanto à herança, será ela para seus filhos.

[[v26-46-18]]

^<<v26-46-18,18>>^ O príncipe não tomará nada da herança do povo para o esbulhar da sua possessão; da sua própria possessão deixará herança a seus filhos, para que o meu povo não seja espalhado, cada um da sua possessão.

[[v26-46-19]]

^<<v26-46-19,19>>^ Então me introduziu pela entrada que estava ao lado da porta nas câmaras santas para os sacerdotes, que olhavam para o norte; e eis que ali havia um lugar por detrás, para a banda do ocidente.

[[v26-46-20]]

^<<v26-46-20,20>>^ E ele me disse: Este é o lugar onde os sacerdotes cozerão a oferta pela culpa, e a oferta pelo pecado, e onde assarão a oferta de cereais, para que não as tragam ao átrio exterior, e assim transmitam a santidade ao povo.

[[v26-46-21]]

^<<v26-46-21,21>>^ Então me levou para fora, para o átrio exterior, e me fez passar pelos quatro cantos do átrio; e eis que em cada canto do átrio havia um átrio.

[[v26-46-22]]

^<<v26-46-22,22>>^ Nos quatro cantos do átrio havia átrios fechados, de quarenta côvados de comprimento e de trinta de largura; estes quatro cantos tinham a mesma medida.

[[v26-46-23]]

^<<v26-46-23,23>>^ E neles havia por dentro uma série de projeções ao redor; e havia lugares para cozer, construídos por baixo delas ao redor.

[[v26-46-24]]

^<<v26-46-24,24>>^ Então me disse: Estas são as cozinhas, onde os ministros da casa cozerão o sacrifício do povo.

'''

xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]