include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-29-1]]

^<<v26-29-1,1>>^ No décimo ano, no décimo mês, no dia doze do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-29-2]]

^<<v26-29-2,2>>^ Filho do homem, dirige o teu rosto contra Faraó, rei do Egito, e profetiza contra ele e contra todo o Egito.

[[v26-29-3]]

^<<v26-29-3,3>>^ Fala, e dize: Assim diz o Senhor Deus: Eis-me contra ti, ó Faraó, rei do Egito, grande dragão, que pousas no meio dos teus rios, e que dizes: O meu rio é meu, e eu o fiz para mim.

[[v26-29-4]]

^<<v26-29-4,4>>^ Mas eu porei anzóis em teus queixos, e farei que os peixes dos teus rios se apeguem às tuas escamas; e tirar-te-ei dos teus rios, juntamente com todos os peixes dos teus nos que se apegarem as tuas escamas.

[[v26-29-5]]

^<<v26-29-5,5>>^ E te lançarei no deserto, a ti e a todos os peixes dos teus rios; sobre a face do campo cairás; não serás recolhido nem ajuntado. Aos animais da terra e às aves do céu te dei por pasto.

[[v26-29-6]]

^<<v26-29-6,6>>^ E saberão todos os moradores do Egito que eu sou o Senhor, porque tu tens sido um bordão de cana para a casa de Israel.

[[v26-29-7]]

^<<v26-29-7,7>>^ Tomando-te eles na mão, tu te quebraste e lhes rasgaste todo o ombro; e quando em ti se apoiaram, tu te quebraste, fazendo estremecer todos os seus lombos.

[[v26-29-8]]

^<<v26-29-8,8>>^ Portanto, assim diz o Senhor Deus: Eis que eu trarei sobre ti a espada, e de ti exterminarei homem e animal.

[[v26-29-9]]

^<<v26-29-9,9>>^ E a terra do Egito se tornará em desolação e deserto; e saberão que eu sou o Senhor. Porquanto disseste: O rio é meu, e eu o fiz;

[[v26-29-10]]

^<<v26-29-10,10>>^ por isso eis que eu estou contra ti e contra os teus rios; e tornarei a terra do Egito em desertas e assoladas solidões, desde Migdol de Sevené até os confins da Etiópia.

[[v26-29-11]]

^<<v26-29-11,11>>^ Não passará por ela pé de homem, nem pé de animal passará por ela, nem será habitada durante quarenta anos.

[[v26-29-12]]

^<<v26-29-12,12>>^ Assim tornarei a terra do Egito em desolação no meio das terras assoladas, e as suas cidades no meio das cidades assoladas ficarão desertas por quarenta anos; e espalharei os egípcios entre as nações, e os dispersarei pelos países.

[[v26-29-13]]

^<<v26-29-13,13>>^ Pois assim diz o Senhor Deus: Ao cabo de quarenta anos ajuntarei os egípcios dentre os povos entre os quais foram espalhados.

[[v26-29-14]]

^<<v26-29-14,14>>^ E restaurarei do cativeiro os egípcios, e os farei voltar à terra de Patros, à sua terra natal; e serão ali um reino humilde;

[[v26-29-15]]

^<<v26-29-15,15>>^ mais humilde se fará do que os outros reinos, e nunca mais se exalçará sobre as nações; e eu os diminuirei, para que não mais dominem sobre as nações.

[[v26-29-16]]

^<<v26-29-16,16>>^ E não será mais a confiança da casa de Israel e a ocasião de ser lembrada a sua iniqüidade, quando se virarem para olhar após eles; antes saberão que eu sou o Senhor Deus.

[[v26-29-17]]

^<<v26-29-17,17>>^ E sucedeu que, no ano vinte e sete, no mês primeiro, no primeiro dia do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-29-18]]

^<<v26-29-18,18>>^ Filho do homem, Nabucodonosor, rei de Babilônia, fez com que o seu exército prestasse um grande serviço contra Tiro. Toda cabeça se tornou calva, e todo ombro se pelou; contudo não houve paga da parte de Tiro para ele, nem para o seu exército, pelo serviço que prestou contra ela.

[[v26-29-19]]

^<<v26-29-19,19>>^ Portanto, assim diz o Senhor Deus: Eis que eu darei a Nabucodonosor, rei de Babilônia, a terra do Egito; assim levará ele a multidão dela, como tomará o seu despojo e roubará a sua presa; e isso será a paga para o seu exército.

[[v26-29-20]]

^<<v26-29-20,20>>^ Como recompensa do serviço que me prestou, pois trabalhou por mim, eu lhe dei a terra do Egito, diz o Senhor Deus.

[[v26-29-21]]

^<<v26-29-21,21>>^ Naquele dia farei brotar um chifre para a casa de Israel; e te concederei que abras a boca no meio deles; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]