include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-39-1]]

^<<v26-39-1,1>>^ Tu, pois, ó filho do homem, profetiza contra Gogue, e dize: Assim diz o Senhor Deus: Eis que eu sou contra ti, ó Gogue, príncipe e chefe de Meseque e Tubal;

[[v26-39-2]]

^<<v26-39-2,2>>^ e te farei virar e, conduzindo-te, far-te-ei subir do extremo norte, e te trarei aos montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ Com um golpe tirarei da tua mão esquerda o teu arco, e farei cair da tua mão direita as tuas flechas.

[[v26-39-4]]

^<<v26-39-4,4>>^ Nos montes de Israel cairás, tu e todas as tuas tropas, e os povos que estão contigo; e às aves de rapina de toda espécie e aos animais do campo te darei, para que te devorem.

[[v26-39-5]]

^<<v26-39-5,5>>^ Sobre a face do campo cairás; porque eu falei, diz o Senhor Deus.

[[v26-39-6]]

^<<v26-39-6,6>>^ E enviarei um fogo sobre Magogue, e entre os que habitam seguros nas ilhas; e saberão que eu sou o Senhor.

[[v26-39-7]]

^<<v26-39-7,7>>^ E farei conhecido o meu santo nome no meio do meu povo Israel, e nunca mais deixarei profanar o meu santo nome; e as nações saberão que eu sou o Senhor, o Santo em Israel.

[[v26-39-8]]

^<<v26-39-8,8>>^ Eis que isso vem, e se cumprirá, diz o Senhor Deus; este é o dia de que tenho falado.

[[v26-39-9]]

^<<v26-39-9,9>>^ E os habitantes das cidades de Israel sairão, e com as armas acenderão o fogo, e queimarão os escudos e os paveses, os arcos e as flechas, os bastões de mão e as lanças; acenderão o fogo com tudo isso por sete anos;

[[v26-39-10]]

^<<v26-39-10,10>>^ e não trarão lenha do campo, nem a cortarão dos bosques, mas com as armas acenderão o fogo; e roubarão aos que os roubaram, e despojarão aos que os despojaram, diz o Senhor Deus.

[[v26-39-11]]

^<<v26-39-11,11>>^ Naquele dia, darei a Gogue como lugar de sepultura em Israel, o vale dos que passam ao oriente do mar, o qual fará parar os que por ele passarem; e ali sepultarão a Gogue, e a toda a sua multidão, e lhe chamarão o Vale de Hamom-Gogue.

[[v26-39-12]]

^<<v26-39-12,12>>^ E a casa de Israel levará sete meses em sepultá-los, para purificar a terra.

[[v26-39-13]]

^<<v26-39-13,13>>^ Sim, todo o povo da terra os enterrará; e isto lhes servirá de fama, no dia em que eu for glorificado, diz o Senhor Deus.

[[v26-39-14]]

^<<v26-39-14,14>>^ Separarão, pois, homens que incessantemente percorrerão a terra, para que sepultem os que tiverem ficado sobre a face da terra, para a purificarem. Depois de passados sete meses, farão a busca;

[[v26-39-15]]

^<<v26-39-15,15>>^ e quando percorrerem a terra, vendo alguém um osso de homem, levantar-lhe-á ao pé um sinal, até que os enterradores o enterrem no Vale de Hamom-Gogue.

[[v26-39-16]]

^<<v26-39-16,16>>^ E também o nome da cidade será Hamona. Assim purificarão a terra.

[[v26-39-17]]

^<<v26-39-17,17>>^ Tu, pois, ó filho do homem, assim diz o Senhor Deus: Dize às aves de toda espécie, e a todos os animais do campo: Ajuntai-vos e vinde; ajuntai-vos de todos os lados para o meu sacrifício, que eu sacrifico por vós, sacrifício grande sobre os montes de Israel, para comerdes carne e beberdes sangue.

[[v26-39-18]]

^<<v26-39-18,18>>^ Comereis as carnes dos poderosos e bebereis o sangue dos príncipes da terra, dos carneiros e dos cordeiros, dos bodes e dos novilhos, todos eles cevados em Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ Comereis da gordura até vos fartardes, e bebereis do sangue até vos embebedardes, da gordura e do sangue do sacrifício que vos estou preparando.

[[v26-39-20]]

^<<v26-39-20,20>>^ E à minha mesa vos fartareis de cavalos e de cavaleiros, de valentes e de todos os homens de guerra, diz o Senhor Deus.

[[v26-39-21]]

^<<v26-39-21,21>>^ Estabelecerei, pois, a minha glória entre as nações, e todas as nações verão o meu juízo, que eu tiver executado, e a minha mão, que sobre elas eu tiver descarregado.

[[v26-39-22]]

^<<v26-39-22,22>>^ E os da casa de Israel saberão desde aquele dia em diante, que eu sou o Senhor Deus.

[[v26-39-23]]

^<<v26-39-23,23>>^ E as nações saberão que os da casa de Israel, por causa da sua iniqüidade, foram levados em cativeiro; porque se houveram traiçoeiramente para comigo, e eu escondi deles o meu rosto; por isso os entreguei nas mãos de seus adversários, e todos caíram à espada.

[[v26-39-24]]

^<<v26-39-24,24>>^ Conforme a sua imundícia e conforme as suas transgressões me houve com eles, e escondi deles o meu rosto.

[[v26-39-25]]

^<<v26-39-25,25>>^ Portanto assim diz o Senhor Deus: Agora tornarei a trazer Jacó, e me compadecerei de toda a casa de Israel; terei zelo pelo meu santo nome.

[[v26-39-26]]

^<<v26-39-26,26>>^ E eles se esquecerão tanto do seu opróbrio, como de todas as suas infidelidades pelas quais transgrediram contra mim, quando eles habitarem seguros na sua terra, sem haver quem os amedronte;

[[v26-39-27]]

^<<v26-39-27,27>>^ quando eu os tornar a trazer de entre os povos, e os houver ajuntado das terras de seus inimigos, e for santificado neles aos olhos de muitas nações.

[[v26-39-28]]

^<<v26-39-28,28>>^ Então saberão que eu sou o Senhor seu Deus, vendo que eu os fiz ir em cativeiro entre as nações, e os tornei a ajuntar para a sua terra. Não deixarei lá nenhum deles;

[[v26-39-29]]

^<<v26-39-29,29>>^ nem lhes esconderei mais o meu rosto; pois derramei o meu Espírito sobre a casa de Israel, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]