include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-25-1]]

^<<v26-25-1,1>>^ De novo veio a mim a palavra do Senhor, dizendo:

[[v26-25-2]]

^<<v26-25-2,2>>^ Filho do homem, dirige o teu rosto contra os filhos de Amom, e profetiza contra eles.

[[v26-25-3]]

^<<v26-25-3,3>>^ E dize aos amonitas: Ouvi a palavra do Senhor Deus: Assim diz o Senhor Deus: Visto que tu disseste: Ah! contra o meu santuário quando foi profanado, e contra a terra de Israel quando foi assolada, e contra a casa de Judá quando foi para o cativeiro;

[[v26-25-4]]

^<<v26-25-4,4>>^ por isso eis que te entregarei em possessão ao povo do Oriente, e em ti estabelecerão os seus acampamentos, e porão em ti as suas moradas. Eles comerão os teus frutos, e beberão o teu leite.

[[v26-25-5]]

^<<v26-25-5,5>>^ E farei de Rabá uma estrebaria de camelos, e dos amonitas um curral de rebanhos; e sabereis que eu sou o Senhor.

[[v26-25-6]]

^<<v26-25-6,6>>^ Porque assim diz o Senhor Deus: Visto como bateste com as mãos, e pateaste com os pés, e te alegraste com todo o despeito do teu coração contra a terra de Israel;

[[v26-25-7]]

^<<v26-25-7,7>>^ portanto eis que eu tenho estendido a minha mão contra ti, e te darei por despojo às nações, e te arrancarei dentre os povos, e te destruirei dentre os países, e de todo acabarei contigo; e saberás que eu sou o Senhor.

[[v26-25-8]]

^<<v26-25-8,8>>^ Assim diz o Senhor Deus: Visto como dizem em Moabe. e Seir: Eis que a casa de Judá é como todas as nações;

[[v26-25-9]]

^<<v26-25-9,9>>^ portanto, eis que eu abrirei o lado de Moabe desde as cidades, desde as suas cidades que estão pela banda das fronteiras, a glória do país, Bete-Jesimote, Baal-Meom, e até Quiriataim,

[[v26-25-10]]

^<<v26-25-10,10>>^ e ao povo do Oriente, juntamente com os filhos de Amom, eu o entregarei em possessão, para que não haja mais memória dos filhos de Amom entre as nações.

[[v26-25-11]]

^<<v26-25-11,11>>^ Também executarei juízos contra Moabe; e saberão que eu sou o Senhor.

[[v26-25-12]]

^<<v26-25-12,12>>^ Assim diz o Senhor Deus: Pois que Edom se houve vingativamente para com a casa de Judá, e se fez culpadíssimo, vingando-se deles.

[[v26-25-13]]

^<<v26-25-13,13>>^ portanto assim diz o Senhor Deus: Também estenderei a minha mão contra Edom, e arrancarei dele homens e animais; e o tornarei em deserto desde Temã; e cairão à espada até Dedã.

[[v26-25-14]]

^<<v26-25-14,14>>^ E exercerei a minha vingança sobre Edom, pela mão do meu povo de Israel; e farão em Edom segundo a minha ira e segundo o meu furor; e conhecerão a minha vingança, diz o Senhor Deus.

[[v26-25-15]]

^<<v26-25-15,15>>^ Assim diz o Senhor Deus: Porquanto os filisteus se houveram vingativamente, e executaram vingança com despeito de coração, para destruírem com perpétua inimizade;

[[v26-25-16]]

^<<v26-25-16,16>>^ portanto assim diz o Senhor Deus: Eis que estendo a minha mão contra os filisteus, e arrancarei os quereteus, e destruirei o resto da costa do mar.

[[v26-25-17]]

^<<v26-25-17,17>>^ E executarei neles grandes vinganças, com furiosos castigos; e saberão que eu sou o Senhor, quando eu tiver exercido a minha vingança sobre eles.

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]