include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-8-1]]

^<<v26-8-1,1>>^ Sucedeu pois, no sexto ano, no mês sexto, no quinto dia do mês, estando eu assentado na minha casa, e os anciãos de Judá assentados diante de mim, que ali a mão do Senhor Deus caiu sobre mim.

[[v26-8-2]]

^<<v26-8-2,2>>^ Então olhei, e eis uma semelhança como aparência de fogo. Desde a aparência dos seus lombos, e para baixo, era fogo; e dos seus lombos, e para cima, como aspecto de resplendor, como e brilho de âmbar.

[[v26-8-3]]

^<<v26-8-3,3>>^ E estendeu a forma duma mão, e me tomou por uma trança da minha cabeça; e o Espírito me levantou entre a terra e o céu, e nas visões de Deus me trouxe a Jerusalém, até a entrada da porta do pátio de dentro, que olha para o norte, onde estava o assento da imagem do ciúme, que provoca ciúme.

[[v26-8-4]]

^<<v26-8-4,4>>^ E eis que a glória do Deus de Israel estava ali, conforme a semelhança que eu tinha visto no vale.

[[v26-8-5]]

^<<v26-8-5,5>>^ Então me disse: Filho do homem, levanta agora os teus olhos para o caminho do norte. Levantei, pois, os meus olhos para o caminho do norte, e eis que ao norte da porta do altar, estava esta imagem do ciúme na entrada.

[[v26-8-6]]

^<<v26-8-6,6>>^ E ele me disse: Filho do homem, vês tu o que eles estão fazendo? as grandes abominações que a casa de Israel faz aqui, para que me afaste do meu santuário; Mas verás ainda outras grandes abominações.

[[v26-8-7]]

^<<v26-8-7,7>>^ E levou-me à porta do átrio; então olhei, e eis que havia um buraco na parede.

[[v26-8-8]]

^<<v26-8-8,8>>^ Então ele me disse: Filho do homem, cava agora na parede. E quando eu tinha cavado na parede, eis que havia uma porta.

[[v26-8-9]]

^<<v26-8-9,9>>^ Disse-me ainda: Entra, e vê as ímpias abominações que eles fazem aqui.

[[v26-8-10]]

^<<v26-8-10,10>>^ Entrei, pois, e olhei: E eis que toda a forma de répteis, e de animais abomináveis, e todos os ídolos da casa de Israel, estavam pintados na parede em todo o redor.

[[v26-8-11]]

^<<v26-8-11,11>>^ E setenta homens dos anciãos da casa de Israel, com Jaazanias, filho de Safã, no meio deles, estavam em pé diante das pinturas, e cada um tinha na mão o seu incensário; e subia o odor de uma nuvem de incenso.

[[v26-8-12]]

^<<v26-8-12,12>>^ Então me disse: Viste, filho do homem, o que os anciãos da casa de Israel fazem nas trevas, cada um nas suas câmaras pintadas de imagens? Pois dizem: O Senhor não nos vê; o Senhor abandonou a terra.

[[v26-8-13]]

^<<v26-8-13,13>>^ Também me disse: Verás ainda maiores abominações que eles fazem.

[[v26-8-14]]

^<<v26-8-14,14>>^ Depois me levou à entrada da porta da casa do Senhor, que olha para o norte; e eis que estavam ali mulheres assentadas chorando por Tamuz.

[[v26-8-15]]

^<<v26-8-15,15>>^ Então me disse: Viste, filho do homem? Verás ainda maiores abominações do que estas.

[[v26-8-16]]

^<<v26-8-16,16>>^ E levou-me para o átrio interior da casa do Senhor; e eis que estavam à entrada do templo do Senhor, entre o pórtico e o altar, cerca de vinte e cinco homens, de costas para o templo do Senhor, e com os rostos para o oriente; e assim, virados para o oriente, adoravam o sol.

[[v26-8-17]]

^<<v26-8-17,17>>^ Então me disse: Viste, filho do homem? Acaso é isto coisa leviana para a casa de Judá, o fazerem eles as abominações que fazem aqui? pois, havendo enchido a terra de violência, tornam a provocar-me à ira; e ei-los a chegar o ramo ao seu nariz.

[[v26-8-18]]

^<<v26-8-18,18>>^ Pelo que também eu procederei com furor; o meu olho não poupará, nem terei piedade. Ainda que me gritem aos ouvidos com grande voz, contudo não os ouvirei.

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]