include::./index.adoc[]

[[v26-27-0]]
=== Ezequiel, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-27-1]]

^<<v26-27-1,1>>^ De novo veio a mim a palavra do Senhor, dizendo:

[[v26-27-2]]

^<<v26-27-2,2>>^ Tu pois, ó filho do homem, levanta uma lamentação sobre Tiro;

[[v26-27-3]]

^<<v26-27-3,3>>^ e dize a Tiro, que habita na entrada do mar, e negocia com os povos em muitas ilhas: Assim diz o Senhor Deus: ó Tiro, tu dizes: Eu sou perfeita em formosura.

[[v26-27-4]]

^<<v26-27-4,4>>^ No coração dos mares estão os teus termos; os que te edificaram aperfeiçoaram a tua formosura.

[[v26-27-5]]

^<<v26-27-5,5>>^ De ciprestes de Senir fizeram todas as tuas tábuas; trouxeram cedros do Líbano para fazerem um mastro para ti.

[[v26-27-6]]

^<<v26-27-6,6>>^ Fizeram os teus remos de carvalhos de Basã; os teus bancos fizeram-nos de marfim engastado em buxo das ilhas de Quitim.

[[v26-27-7]]

^<<v26-27-7,7>>^ Linho fino bordado do Egito era a tua vela, para te servir de estandarte; de azul, e púrpura das ilhas de Elisá era a tua cobertura.

[[v26-27-8]]

^<<v26-27-8,8>>^ Os habitantes de Sidom e de Arvade eram os teus remadores; os teus peritos, ó Tiro, que em ti se achavam, esses eram os teus pilotos.

[[v26-27-9]]

^<<v26-27-9,9>>^ Os anciãos de Gebal e seus peritos eram em ti os teus calafates; todos os navios do mar e os seus marinheiros se achavam em ti, para tratarem dos teus negócios.

[[v26-27-10]]

^<<v26-27-10,10>>^ Os persas, e os lídios, e os de Pute eram no teu exército os teus soldados; penduravam em ti o escudo e o capacete; aumentavam o teu esplendor.

[[v26-27-11]]

^<<v26-27-11,11>>^ Os filhos de Arvade e o teu exército estavam sobre os teus muros em redor, e os gamaditas nas tuas torres; penduravam os seus escudos nos teus muros em redor; aperfeiçoavam a tua formosura.

[[v26-27-12]]

^<<v26-27-12,12>>^ Társis negociava contigo, por causa da abundância de toda a casta de riquezas; seus negociantes trocavam pelas tuas mercadorias prata, ferro, estanho, e chumbo.

[[v26-27-13]]

^<<v26-27-13,13>>^ Javã, Tubál e Meseque eram teus mercadores; pelas tuas mercadorias trocavam as pessoas de homens e vasos de bronze.

[[v26-27-14]]

^<<v26-27-14,14>>^ Os da casa de Togarma trocavam pelas tuas mercadorias cavalos e ginetes e machos;

[[v26-27-15]]

^<<v26-27-15,15>>^ os homens de Dedã eram teus mercadores; muitas ilhas eram o mercado da tua mão; tornavam a trazer-te em troca de dentes de marfim e pau de ébano.

[[v26-27-16]]

^<<v26-27-16,16>>^ A Síria negociava contigo por causa da multidão das tuas manufaturas; pelas tuas mercadorias trocavam granadas, púrpura, obras bordadas, linho fino, corais e rubis.

[[v26-27-17]]

^<<v26-27-17,17>>^ Judá e a terra de Israel eram teus mercadores; pelas tuas mercadorias trocavam o trigo de Minite, cera, mel, azeite e bálsamo.

[[v26-27-18]]

^<<v26-27-18,18>>^ Por causa da multidão das tuas manufaturas, por causa da multidão de toda a sorte de riquezas, Damasco negociava contigo em vinho de Helbom e lã branca.

[[v26-27-19]]

^<<v26-27-19,19>>^ Vedã e Javã de Uzal trocavam lã fiada pelas tuas manufaturas; ferro polido, cássia e cálamo aromático achavam-se entre as tuas mercadorias.

[[v26-27-20]]

^<<v26-27-20,20>>^ Dedã negociava contigo em suadouros para cavalgar.

[[v26-27-21]]

^<<v26-27-21,21>>^ Arábia e todos os príncipes de Quedar também eram os mercadores ao teu serviço; em cordeiros, carneiros e bodes, nestas coisas negociavam contigo.

[[v26-27-22]]

^<<v26-27-22,22>>^ Os mercadores de Sabá e Raamá igualmente negociavam contigo; pelas tuas mercadorias trocavam as melhores de todas as especiarias e toda a pedra preciosa e ouro.

[[v26-27-23]]

^<<v26-27-23,23>>^ Harã, e Cané e Edem os mercadores de Sabá, Assur e Quilmade eram teus mercadores.

[[v26-27-24]]

^<<v26-27-24,24>>^ Estes negociavam contigo em roupas escolhidas, em agasalho de azul e de obra bordada, e em cofres de roupas preciosas, amarrados com cordas e feitos de cedro.

[[v26-27-25]]

^<<v26-27-25,25>>^ Os navios de Társis eram as tuas caravanas para a tua mercadoria; e te encheste, e te glorificaste muito no meio dos mares.

[[v26-27-26]]

^<<v26-27-26,26>>^ Os teus remadores te conduziram sobre grandes águas; o vento oriental te quebrantou no meio dos mares.

[[v26-27-27]]

^<<v26-27-27,27>>^ As tuas riquezas, os teus bens, as tuas mercadorias, os teus marinheiros e os teus pilotos, os teus calafates, e os que faziam os teus negócios, e todos os teus soldados, que estão em ti, juntamente com toda a tua companhia, que está no meio de ti, se submergirão no meio dos mares no dia da tua queda.

[[v26-27-28]]

^<<v26-27-28,28>>^ Ao estrondo da gritaria dos teus pilotos tremerão os arrabaldes.

[[v26-27-29]]

^<<v26-27-29,29>>^ E todos os que pegam no remo, os marinheiros, e todos os pilotos do mar descerão de seus navios, e pararão em terra,

[[v26-27-30]]

^<<v26-27-30,30>>^ e farão ouvir a sua voz sobre ti, e gritarão amargamente; lançarão pó sobre as cabeças, e na cinza se revolverão;

[[v26-27-31]]

^<<v26-27-31,31>>^ e se farão calvos por tua causa, e se cingirão de sacos, e chorarão sobre ti com amargura de alma, com amarga lamentação.

[[v26-27-32]]

^<<v26-27-32,32>>^ No seu pranto farão uma lamentação sobre ti, na qual dirão: Quem foi como Tiro, como a que está reduzida ao silêncio no meio do mar?

[[v26-27-33]]

^<<v26-27-33,33>>^ Quando as tuas mercadorias eram exportadas pelos mares, fartaste a muitos povos; com a multidão das tuas riquezas e das tuas mercadorias, enriqueceste os reis da terra.

[[v26-27-34]]

^<<v26-27-34,34>>^ No tempo em que foste quebrantada pelos mares, nas profundezas das águas, caíram no meio de ti todas as tuas mercadorias e toda a tua companhia.

[[v26-27-35]]

^<<v26-27-35,35>>^ Todos os moradores das ilhas estão a teu respeito cheios de espanto; e os seus reis temem em grande maneira, e estão de semblante perturbado.

[[v26-27-36]]

^<<v26-27-36,36>>^ Os mercadores dentre os povos te dão vaias; tu te tornaste em grande espanto, e não mais existiras.

'''

xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]