include::./index.adoc[]

[[v26-18-0]]
=== Ezequiel, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-18-1]]

^<<v26-18-1,1>>^ De novo veio a mim a palavra do Senhor, dizendo:

[[v26-18-2]]

^<<v26-18-2,2>>^ Que quereis vós dizer, citando na terra de Israel este provérbio: Os pais comeram uvas verdes, e os dentes dos filhos se embotaram?

[[v26-18-3]]

^<<v26-18-3,3>>^ Vivo eu, diz e Senhor Deus, não se vos permite mais usar deste provérbio em Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Eis que todas as almas são minhas; como o é a alma do pai, assim também a alma do filho é minha: a alma que pecar, essa morrerá.

[[v26-18-5]]

^<<v26-18-5,5>>^ Sendo pois o homem justo, e procedendo com retidão e justiça,

[[v26-18-6]]

^<<v26-18-6,6>>^ não comendo sobre os montes, nem levantando os seus olhes para os ídolos da casa de Israel, nem contaminando a mulher do seu próximo, nem se chegando à mulher na sua separação;

[[v26-18-7]]

^<<v26-18-7,7>>^ não oprimindo a ninguém, tornando, porém, ao devedor e seu penhor, e não roubando, repartindo e seu pão com o faminto, e cobrindo ao nu com vestido;

[[v26-18-8]]

^<<v26-18-8,8>>^ não emprestando com usura, e não recebendo mais de que emprestou, desviando a sua mão da injustiça, e fazendo verdadeira justiça entre homem e homem;

[[v26-18-9]]

^<<v26-18-9,9>>^ andando nos meus estatutos, e guardando as minhas ordenanças, para proceder segundo a verdade; esse é justo, certamente viverá, diz o Senhor Deus,

[[v26-18-10]]

^<<v26-18-10,10>>^ E se ele gerar um filho que se torne salteador, que derrame sangue, que faça a seu irmão qualquer dessas coisas;

[[v26-18-11]]

^<<v26-18-11,11>>^ e que não cumpra com nenhum desses deveres, porém coma sobre os montes, e contamine a mulher de seu próximo,

[[v26-18-12]]

^<<v26-18-12,12>>^ oprima ao pobre e necessitado, pratique roubos, não devolva o penhor, levante os seus olhos para os ídolos, cometa abominação,

[[v26-18-13]]

^<<v26-18-13,13>>^ empreste com usura, e receba mais do que emprestou; porventura viverá ele? Não viverá! Todas estas abominações, ele as praticou; certamente morrerá; o seu sangue será sobre ele.

[[v26-18-14]]

^<<v26-18-14,14>>^ Eis que também, se este por sua vez gerar um filho que veja todos os pecados que seu pai fez, tema, e não cometa coisas semelhantes,

[[v26-18-15]]

^<<v26-18-15,15>>^ não coma sobre os montes, nem levante os olhos para os ídolos da casa de Israel, e não contamine a mulher de seu próximo,

[[v26-18-16]]

^<<v26-18-16,16>>^ nem oprima a ninguém, e não empreste sob penhores, nem roube, porém reparta o seu pão com o faminto, e cubra ao nu com vestido;

[[v26-18-17]]

^<<v26-18-17,17>>^ que aparte da iniqüidade a sua mão, que não receba usura nem mais do que emprestou, que observe as minhas ordenanças e ande nos meus estatutos; esse não morrerá por causa da iniqüidade de seu pai; certamente viverá.

[[v26-18-18]]

^<<v26-18-18,18>>^ Quanto ao seu pai, porque praticou extorsão, e roubou os bens do irmão, e fez o que não era bom no meio de seu povo, eis que ele morrerá na sua iniqüidade.

[[v26-18-19]]

^<<v26-18-19,19>>^ contudo dizeis: Por que não levará o filho a iniqüidade do pai? Ora, se o filho proceder com retidão e justiça, e guardar todos os meus estatutos, e os cumprir, certamente viverá.

[[v26-18-20]]

^<<v26-18-20,20>>^ A alma que pecar, essa morrerá; o filho não levará a iniquidade do pai, nem o pai levará a iniquidade do filho, A justiça do justo ficará sobre ele, e a impiedade do ímpio cairá sobre ele.

[[v26-18-21]]

^<<v26-18-21,21>>^ Mas se o ímpio se converter de todos os seus pecados que cometeu, e guardar todos os meus estatutos, e preceder com retidão e justiça, certamente viverá; não morrerá.

[[v26-18-22]]

^<<v26-18-22,22>>^ De todas as suas transgressões que cometeu não haverá lembrança contra ele; pela sua justiça que praticou viverá.

[[v26-18-23]]

^<<v26-18-23,23>>^ Tenho eu algum prazer na morte do ímpio? diz o Senhor Deus. Não desejo antes que se converta dos seus caminhos, e viva?

[[v26-18-24]]

^<<v26-18-24,24>>^ Mas, desviando-se o justo da sua justiça, e cometendo a iniqüidade, fazendo conforme todas as abominações que faz o ímpio, porventura viverá? De todas as suas justiças que tiver feito não se fará memória; pois pela traição que praticou, e pelo pecado que cometeu ele morrerá.

[[v26-18-25]]

^<<v26-18-25,25>>^ Dizeis, porém: O caminho do Senhor não é justo. Ouvi, pois, ó casa de Israel: Acaso não é justo o meu caminho? não são os vossos caminhos que são injustos?

[[v26-18-26]]

^<<v26-18-26,26>>^ Desviando-se o justo da sua justiça, e cometendo iniqüidade, morrerá por ela; na sua iniqüidade que cometeu morrerá.

[[v26-18-27]]

^<<v26-18-27,27>>^ Mas, convertendo-se o ímpio da sua impiedade que cometeu, e procedendo com retidão e justiça, conservará este a sua alma em vida.

[[v26-18-28]]

^<<v26-18-28,28>>^ pois que reconsidera, e se desvia de todas as suas transgressões que cometeu, certamente viverá, não morrerá.

[[v26-18-29]]

^<<v26-18-29,29>>^ Contudo, diz a casa de Israel: O caminho do Senhor não é justo. Acaso não são justos os meus caminhos, ó casa de Israel, Não são antes os vossos caminhos que são injustos?

[[v26-18-30]]

^<<v26-18-30,30>>^ Portanto, eu vos julgarei, a cada um conforme os seus caminhos, ó casa de Israel, diz o Senhor Deus. Vinde, e convertei-vos de todas as vossas transgressões, para que a iniqüidade não vos leve à perdição.

[[v26-18-31]]

^<<v26-18-31,31>>^ Lançai de vós todas as vossas transgressões que cometestes contra mim; e criai em vós um coração novo e um espírito novo; pois, por que morrereis, ó casa de Israel,

[[v26-18-32]]

^<<v26-18-32,32>>^ Porque não tenho prazer na morte de ninguém, diz o Senhor Deus; convertei-vos, pois, e vivei,

'''

xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]