include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-35-1]]

^<<v26-35-1,1>>^ Veio a mim a palavra do Senhor, dizendo:

[[v26-35-2]]

^<<v26-35-2,2>>^ Filho do homem, dirige o teu rosto contra o monte Seir, e profetiza contra ele.

[[v26-35-3]]

^<<v26-35-3,3>>^ E dize-lhe: Assim diz o Senhor Deus: Eis que eu estou contra ti, ó monte Seir, e estenderei a minha mão contra ti, e te tornarei em desolação e espanto.

[[v26-35-4]]

^<<v26-35-4,4>>^ Farei desertas as tuas cidades, e tu serás assolado; e saberás que eu sou o Senhor.

[[v26-35-5]]

^<<v26-35-5,5>>^ Pois que guardaste perpétua inimizade, e entregaste os filhos de Israel ao poder da espada no tempo da sua calamidade, no tempo do castigo final;

[[v26-35-6]]

^<<v26-35-6,6>>^ por isso vivo eu, diz o Senhor Deus, que te prepararei para sangue, e o sangue te perseguirá; visto que não aborreceste o sangue, por isso o sangue te perseguirá.

[[v26-35-7]]

^<<v26-35-7,7>>^ Farei do monte Seir um espanto e uma desolação, e exterminarei dele o que por ele passar, e o que por ele voltar;

[[v26-35-8]]

^<<v26-35-8,8>>^ e encherei os seus montes dos seus mortos; nos teus outeiros, e nos teus vales, e em todas as tuas correntes d'água cairão os mortos à espada.

[[v26-35-9]]

^<<v26-35-9,9>>^ Em desolações perpétuas te porei, e não serão habitadas as tuas cidades. Então sabereis que eu sou o Senhor.

[[v26-35-10]]

^<<v26-35-10,10>>^ Visto como dizes: Estes dois povos e estas duas terras serão meus, e havemos de possuí-los, sendo que o Senhor se achava ali;

[[v26-35-11]]

^<<v26-35-11,11>>^ portanto, vivo eu, diz o Senhor Deus, que procederei conforme a tua ira, e conforme a tua inveja, de que usaste, no teu ódio contra eles; e me darei a conhecer entre eles, quando eu te julgar.

[[v26-35-12]]

^<<v26-35-12,12>>^ E saberás que eu, o Senhor, ouvi todas as tuas blasfêmias, que proferiste contra os montes de Israel, dizendo: Já estão assolados, a nós nos são entregues por pasto.

[[v26-35-13]]

^<<v26-35-13,13>>^ Vós vos engrandecestes contra mim com a vossa boca, e multiplicastes as vossas palavras contra mim. Eu o ouvi.

[[v26-35-14]]

^<<v26-35-14,14>>^ Assim diz o Senhor Deus: Quando a terra toda se alegrar, a ti te farei uma desolação.

[[v26-35-15]]

^<<v26-35-15,15>>^ Como te alegraste com a herança da casa de Israel, porque foi assolada, assim eu te farei a ti: assolado serás, ó monte Seir, e todo o Edom, sim, todo ele; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]