include::./index.adoc[]

[[v26-45-0]]
=== Ezequiel, 45
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-45-1]]

^<<v26-45-1,1>>^ Demais, quando repartirdes a terra por sortes em herança, separareis uma oferta para o Senhor, uma santa porção da terra; o seu comprimento será de vinte e cinco mil canas, e a largura de dez mil. Esta será santa em todo o seu termo ao redor.

[[v26-45-2]]

^<<v26-45-2,2>>^ Desta porção o santuário ocupará quinhentas canas de comprimento, e quinhentas de largura, em quadrado, e terá em redor um espaço vazio de cinqüenta côvados.

[[v26-45-3]]

^<<v26-45-3,3>>^ Desta área santa medirás um comprimento de vinte e cinco mil côvados, e uma largura de dez mil; e ali será o santuário, que é santíssimo.

[[v26-45-4]]

^<<v26-45-4,4>>^ É ela uma porção santa da terra; será para os sacerdotes, ministros do santuário, que se aproximam do Senhor para o servir; e lhes servirá de lugar para suas casas, e de lugar santo para o santuário.

[[v26-45-5]]

^<<v26-45-5,5>>^ Também os levitas, ministros da casa, terão vinte e cinco mil canas de comprimento, e dez mil de largura, para possessão sua, para vinte câmaras.

[[v26-45-6]]

^<<v26-45-6,6>>^ E para possessão da cidade, de largura dareis cinco mil canas, e de comprimento vinte e cinco mil, ao lado da área santa; o que será para toda a casa de Israel.

[[v26-45-7]]

^<<v26-45-7,7>>^ O príncipe, porém, terá a sua parte deste lado e do outro da área santa e da possessão da cidade, defronte da área santa e defronte da possessão da cidade, tanto ao lado ocidental, como ao lado oriental; e de comprimento corresponderá a uma das porções, desde o termo ocidental até o termo oriental.

[[v26-45-8]]

^<<v26-45-8,8>>^ E esta terra será a sua possessão em Israel; e os meus príncipes não oprimirão mais o meu povo; mas distribuirão a terra pela casa de Israel, conforme as suas tribos.

[[v26-45-9]]

^<<v26-45-9,9>>^ Assim diz o Senhor Deus: Baste-vos, ó príncipes de Israel; afastai a violência e a opressão e praticai a retidão e a justiça; aliviai o meu povo das vossas exações, diz o Senhor Deus.

[[v26-45-10]]

^<<v26-45-10,10>>^ Tereis balanças justas, efa justa, e bato justo.

[[v26-45-11]]

^<<v26-45-11,11>>^ A efa e o bato serão duma mesma medida, de maneira que o bato contenha a décima parte do hômer, e a efa a décima parte do hômer; o hômer será a medida padrão.

[[v26-45-12]]

^<<v26-45-12,12>>^ E o siclo será de vinte jeiras; cinco siclos serão cinco siclos, e dez siclos serão dez; a vossa mina será de cinqüenta siclos.

[[v26-45-13]]

^<<v26-45-13,13>>^ Esta será a oferta que haveis de fazer: a sexta parte duma efa de cada hômer de trigo; também dareis a sexta parte duma efa de cada hômer de cevada;

[[v26-45-14]]

^<<v26-45-14,14>>^ quanto à porção fixa do azeite, de cada bato de azeite oferecereis a décima parte do bato tirado dum coro, que é dez batos, a saber, um hômer; pois dez batos fazem um hômer;

[[v26-45-15]]

^<<v26-45-15,15>>^ e um cordeiro do rebanho, de cada duzentos, de todas as famílias de Israel, para oferta de cereais, e para holocausto, e para oferta pacífica, para que façam expiação por eles, diz o Senhor Deus.

[[v26-45-16]]

^<<v26-45-16,16>>^ Todo o povo da terra fará esta contribuição ao príncipe de Israel.

[[v26-45-17]]

^<<v26-45-17,17>>^ Tocará ao príncipe dar os holocaustos, as ofertas de cereais e as libações, nas festas, nas luas novas e nos sábados, em todas as festas fixas da casa de Israel. Ele proverá a oferta pelo pecado, a oferta de cereais, o holocausto e as ofertas pacíficas, para fazer expiação pela casa de Israel.

[[v26-45-18]]

^<<v26-45-18,18>>^ Assim diz o Senhor Deus: No primeiro mês, no primeiro dia do mês, tomarás um bezerro sem mancha, e purificarás o santuário.

[[v26-45-19]]

^<<v26-45-19,19>>^ O sacerdote tomará do sangue da oferta pelo pecado, e pô-lo-á nas ombreiras da casa, e nos quatro cantos da saliência do altar e nas ombreiras da porta do átrio interior.

[[v26-45-20]]

^<<v26-45-20,20>>^ Assim também farás no sétimo dia do mês, pelos errados e pelos insensatos; assim fareis expiação pelo templo.

[[v26-45-21]]

^<<v26-45-21,21>>^ No primeiro mês, no dia catorze de mês, tereis a páscoa, uma festa de sete dias; pão ázimo se comerá.

[[v26-45-22]]

^<<v26-45-22,22>>^ E no mesmo dia o príncipe proverá, por si e por todo o povo da terra, um novilho como oferta pelo pecado.

[[v26-45-23]]

^<<v26-45-23,23>>^ E nos sete dias da festa proverá um holocausto ao Senhor, de sete novilhos e sete carneiros sem mancha, cada dia durante os sete dias; e um bode cada dia como oferta pelo pecado.

[[v26-45-24]]

^<<v26-45-24,24>>^ Também proverá uma oferta de cereais, uma efa para cada novilho, e uma efa para cada carneiro, e um e him de azeite para cada efa.

[[v26-45-25]]

^<<v26-45-25,25>>^ No sétimo mês, no dia quinze do mês, na festa, fará o mesmo por sete dias, segundo a oferta pelo pecado, segundo o holocausto, segundo a oferta de cereais, e segundo o azeite.

'''

xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]