include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-34-1]]

^<<v26-34-1,1>>^ Veio a mim a palavra do Senhor, dizendo:

[[v26-34-2]]

^<<v26-34-2,2>>^ Filho do homem, profetiza contra os pastores de Israel; profetiza, e dize aos pastores: Assim diz o Senhor Deus: Ai dos pastores de Israel que se apascentam a si mesmos! Não devem os pastores apascentar as ovelhas?

[[v26-34-3]]

^<<v26-34-3,3>>^ Comeis a gordura, e vos vestis da lã; matais o cevado; mas não apascentais as ovelhas.

[[v26-34-4]]

^<<v26-34-4,4>>^ A fraca não fortalecestes, a doente não curastes, a quebrada não ligastes, a desgarrada não tornastes a trazer, e a perdida não buscastes; mas dominais sobre elas com rigor e dureza.

[[v26-34-5]]

^<<v26-34-5,5>>^ Assim se espalharam, por não haver pastor; e tornaram-se pasto a todas as feras do campo, porquanto se espalharam.

[[v26-34-6]]

^<<v26-34-6,6>>^ As minhas ovelhas andaram desgarradas por todos os montes, e por todo alto outeiro; sim, as minhas ovelhas andaram espalhadas por toda a face da terra, sem haver quem as procurasse, ou as buscasse.

[[v26-34-7]]

^<<v26-34-7,7>>^ Portanto, ó pastores, ouvi a palavra do Senhor:

[[v26-34-8]]

^<<v26-34-8,8>>^ Vivo eu, diz o Senhor Deus, que porquanto as minhas ovelhas foram entregues à rapina, e as minhas ovelhas vieram a servir de pasto a todas as feras do campo, por falta de pastor, e os meus pastores não procuraram as minhas ovelhas, pois se apascentaram a si mesmos, e não apascentaram as minhas ovelhas;

[[v26-34-9]]

^<<v26-34-9,9>>^ portanto, ó pastores, ouvi a palavra do Senhor:

[[v26-34-10]]

^<<v26-34-10,10>>^ Assim diz o Senhor Deus: Eis que eu estou contra os pastores; das suas mãos requererei as minhas ovelhas, e farei que eles deixem de apascentar as ovelhas, de sorte que não se apascentarão mais a si mesmos. Livrarei as minhas ovelhas da sua boca, para que não lhes sirvam mais de pasto.

[[v26-34-11]]

^<<v26-34-11,11>>^ Porque assim diz o Senhor Deus: Eis que eu, eu mesmo, procurarei as minhas ovelhas, e as buscarei.

[[v26-34-12]]

^<<v26-34-12,12>>^ Como o pastor busca o seu rebanho, no dia em que está no meio das suas ovelhas dispersas, assim buscarei as minhas ovelhas. Livrá-las-ei de todos os lugares por onde foram espalhadas, no dia de nuvens e de escuridão.

[[v26-34-13]]

^<<v26-34-13,13>>^ Sim, tirá-las-ei para fora dos povos, e as congregarei dos países, e as introduzirei na sua terra, e as apascentarei sobre os montes de Israel, junto às correntes d'água, e em todos os lugares habitados da terra.

[[v26-34-14]]

^<<v26-34-14,14>>^ Em bons pastos as apascentarei, e nos altos montes de Israel será o seu curral; deitar-se-ão ali num bom curral, e pastarão em pastos gordos nos montes de Israel.

[[v26-34-15]]

^<<v26-34-15,15>>^ Eu mesmo apascentarei as minhas ovelhas, e eu as farei repousar, diz o Senhor Deus.

[[v26-34-16]]

^<<v26-34-16,16>>^ A perdida buscarei, e a desgarrada tornarei a trazer; a quebrada ligarei, e a enferma fortalecerei; e a gorda e a forte vigiarei. Apascentá-las-ei com justiça.

[[v26-34-17]]

^<<v26-34-17,17>>^ Quanto a vós, ó ovelhas minhas, assim diz o Senhor Deus: Eis que eu julgarei entre ovelhas e ovelhas, entre carneiros e bodes.

[[v26-34-18]]

^<<v26-34-18,18>>^ Acaso não vos basta fartar-vos do bom pasto, senão que pisais o resto de vossos pastos aos vossos pés? e beber as águas limpas, senão que sujais o resto com os vossos pés?

[[v26-34-19]]

^<<v26-34-19,19>>^ E as minhas ovelhas hão de comer o que haveis pisado, e beber o que haveis sujado com os vossos pés.

[[v26-34-20]]

^<<v26-34-20,20>>^ Por isso o Senhor Deus assim lhes diz: Eis que eu, eu mesmo, julgarei entre a ovelha gorda e a ovelha magra.

[[v26-34-21]]

^<<v26-34-21,21>>^ Porquanto com o lado e com o ombro dais empurrões, e com as vossas pontas escorneais todas as fracas, até que as espalhais para fora,

[[v26-34-22]]

^<<v26-34-22,22>>^ portanto salvarei as minhas ovelhas, e não servirão mais de presa; e julgarei entre ovelhas e ovelhas.

[[v26-34-23]]

^<<v26-34-23,23>>^ E suscitarei sobre elas um só pastor para as apascentar, o meu servo Davi. Ele as apascentará, e lhes servirá de pastor.

[[v26-34-24]]

^<<v26-34-24,24>>^ E eu, o Senhor, serei o seu Deus, e o meu servo Davi será príncipe no meio delas; eu, o Senhor, o disse.

[[v26-34-25]]

^<<v26-34-25,25>>^ Farei com elas um pacto de paz; e removerei da terra os animais ruins, de sorte que elas habitarão em segurança no deserto, e dormirão nos bosques.

[[v26-34-26]]

^<<v26-34-26,26>>^ E delas e dos lugares ao redor do meu outeiro farei uma bênção; e farei descer a chuva a seu tempo; chuvas de bênçãos serão.

[[v26-34-27]]

^<<v26-34-27,27>>^ E as árvores do campo darão o seu fruto, e a terra dará a sua novidade, e estarão seguras na sua terra; saberão que eu sou o Senhor, quando eu quebrar os canzis do seu jugo e as livrar da mão dos que se serviam delas.

[[v26-34-28]]

^<<v26-34-28,28>>^ Pois não servirão mais de presa aos gentios, nem as devorarão mais os animais da terra; mas habitarão seguramente, e ninguém haverá que as espante.

[[v26-34-29]]

^<<v26-34-29,29>>^ Também lhes levantarei uma plantação de renome, e nunca mais serão consumidas pela fome na terra, nem mais levarão sobre si o opróbrio das nações.

[[v26-34-30]]

^<<v26-34-30,30>>^ Saberão, porém, que eu, o Senhor seu Deus, estou com elas, e que elas são o meu povo, a casa de Israel, diz o Senhor Deus.

[[v26-34-31]]

^<<v26-34-31,31>>^ Vós, ovelhas minhas, ovelhas do meu pasto, sois homens, e eu sou o vosso Deus, diz o Senhor Deus.

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]