include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-5-1]]

^<<v26-5-1,1>>^ E tu, ó filho do homem, toma uma espada afiada; como navalha de barbeiro a usarás, e a farás passar pela tua cabeça e pela tua barba. Então tomarás uma balança e repartirás os cabelos.

[[v26-5-2]]

^<<v26-5-2,2>>^ A terça parte, queimá-la-ás no fogo, no meio da cidade, quando se cumprirem os dias do cerco; tomarás outra terça parte, e com uma espada feri-la-ás ao redor da cidade; e espalharás a outra terça parte ao vento; e eu desembainharei a espada atrás deles.

[[v26-5-3]]

^<<v26-5-3,3>>^ E tomarás deles um pequeno número, e atá-los-ás nas bordas da tua capa.

[[v26-5-4]]

^<<v26-5-4,4>>^ E ainda destes tomarás alguns e, lançando-os no meio do fogo, os queimarás no fogo; e dali sairá um fogo contra toda a casa de Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ Assim diz o Senhor Deus: Esta é Jerusalém; coloquei-a no meio das nações, estando os países ao seu redor;

[[v26-5-6]]

^<<v26-5-6,6>>^ ela, porém, se rebelou perversamente contra os meus juízos, mais do que as nações, e os meus estatutos mais do que os países que estão ao redor dela; porque rejeitaram as minhas ordenanças, e não andaram nos meus preceitos.

[[v26-5-7]]

^<<v26-5-7,7>>^ Portanto assim diz o Senhor Deus: Porque sois mais turbulentos do que as nações que estão ao redor de vós, e não tendes andado nos meus estatutos, nem guardado os meus juízos, e tendes procedido segundo as ordenanças das nações que estão ao redor de vós;

[[v26-5-8]]

^<<v26-5-8,8>>^ por isso assim diz o Senhor Deus: Eis que eu, sim, eu, estou contra ti; e executarei juízos no meio de ti aos olhos das nações.

[[v26-5-9]]

^<<v26-5-9,9>>^ E por causa de todas as tuas abominações farei sem ti o que nunca fiz, e coisas às quais nunca mais farei semelhantes.

[[v26-5-10]]

^<<v26-5-10,10>>^ portanto os pais comerão a seus filhos no meio de ti, e os filhos comerão a seus pais; e executarei em ti juízos, e todos os que restarem de ti, espalhá-los-ei a todos os ventos.

[[v26-5-11]]

^<<v26-5-11,11>>^ Portanto, tão certo como eu vivo, diz o Senhor Deus, pois que profanaste o meu santuário com todas as tuas coisas detestáveis, e com todas as tuas abominações, também eu te diminuirei; e não te perdoarei, nem terei piedade de ti.

[[v26-5-12]]

^<<v26-5-12,12>>^ uma terça parte de ti morrerá da peste, e se consumirá de fome no meio de ti; e outra terça parte cairá à espada em redor de ti; e a outra terça parte, espalha-la-ei a todos os ventos, e desembainharei a espada atrás deles.

[[v26-5-13]]

^<<v26-5-13,13>>^ Assim se cumprirá a minha ira, e satisfarei neles o meu furor, e me consolarei; e saberão que sou eu, o Senhor, que tenho falado no meu zelo, quando eu cumprir neles o meu furor.

[[v26-5-14]]

^<<v26-5-14,14>>^ Demais te farei uma desolação, e objeto de opróbrio entre as nações que estão em redor de ti, à vista de todos os que passarem.

[[v26-5-15]]

^<<v26-5-15,15>>^ E isso será objeto de opróbrio e ludíbrio, e escarmento e espanto, às nações que estão em redor de ti, quando eu executar em ti juízos com ira, e com furor, e com furiosos castigos. Eu, o Senhor, o disse.

[[v26-5-16]]

^<<v26-5-16,16>>^ Quando eu enviar as malignas flechas da fome contra eles, flechas para a destruição, as quais eu mandarei para vos destruir; e aumentarei a fome sobre vós, e tirar-vos-ei o sustento do pão.

[[v26-5-17]]

^<<v26-5-17,17>>^ E enviarei sobre vós a fome e feras, que te desfilharão; e a peste e o sangue passarão por ti; e trarei a espada sobre ti. Eu, o Senhor, o disse.

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]