include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v26-3-1]]

^<<v26-3-1,1>>^ Depois me disse: Filho do homem, come o que achares; come este rolo, e vai, fala à casa de Israel.

[[v26-3-2]]

^<<v26-3-2,2>>^ Então abri a minha boca, e ele me deu a comer o rolo.

[[v26-3-3]]

^<<v26-3-3,3>>^ E disse-me: Filho do homem, dá de comer ao teu ventre, e enche as tuas entranhas deste rolo que eu te dou. Então o comi, e era na minha boca doce como o mel.

[[v26-3-4]]

^<<v26-3-4,4>>^ Disse-me ainda: Filho do homem, vai, entra na casa de Israel, e dize-lhe as minhas palavras.

[[v26-3-5]]

^<<v26-3-5,5>>^ Pois tu não és enviado a um povo de estranha fala, nem de língua difícil, mas à casa de Israel;

[[v26-3-6]]

^<<v26-3-6,6>>^ nem a muitos povos de estranha fala, e de língua difícil, cujas palavras não possas entender; se eu aos tais te enviara, certamente te dariam ouvidos.

[[v26-3-7]]

^<<v26-3-7,7>>^ Mas a casa de Israel não te quererá ouvir; pois eles não me querem escutar a mim; porque toda a casa de Israel é de fronte obstinada e dura de coração.

[[v26-3-8]]

^<<v26-3-8,8>>^ Eis que fiz duro o teu rosto contra os seus rostos, e dura a tua fronte contra a sua fronte.

[[v26-3-9]]

^<<v26-3-9,9>>^ Fiz como esmeril a tua fronte, mais dura do que a pederneira. Não os temas pois, nem te assustes com os seus semblantes, ainda que são casa rebelde.

[[v26-3-10]]

^<<v26-3-10,10>>^ Disse-me mais: Filho do homem, recebe no teu coração todas as minhas palavras que te hei de dizer; e ouve-as com os teus ouvidos.

[[v26-3-11]]

^<<v26-3-11,11>>^ E vai ter com os do cativeiro, com os filhos do teu povo, e lhes falarás, e tu dirás: Assim diz o Senhor Deus; quer ouçam quer deixem de ouvir.

[[v26-3-12]]

^<<v26-3-12,12>>^ Então o Espírito me levantou, e ouvi por detrás de mim uma voz de grande estrondo, que dizia: Bendita seja a glória do Senhor, desde o seu lugar.

[[v26-3-13]]

^<<v26-3-13,13>>^ E ouvi o ruído das asas dos seres viventes, ao tocarem umas nas outras, e o banilho das rodas ao lado deles, e o sonido dum grande estrondo.

[[v26-3-14]]

^<<v26-3-14,14>>^ Então o Espírito me levantou, e me levou; e eu me fui, amargurado, na indignação do meu espírito; e a mão do Senhor era forte sobre mim.

[[v26-3-15]]

^<<v26-3-15,15>>^ E vim ter com os do cativeiro, a Tel-Abibe, que moravam junto ao rio Quebar, e eu morava onde eles moravam; e por sete dias sentei-me ali, pasmado no meio deles.

[[v26-3-16]]

^<<v26-3-16,16>>^ Ao fim de sete dias, veio a palavra do Senhor a mim, dizendo:

[[v26-3-17]]

^<<v26-3-17,17>>^ Filho do homem, eu te dei por atalaia sobre a casa de Israel; quando ouvires uma palavra da minha boca, avisá-los-ás da minha parte.

[[v26-3-18]]

^<<v26-3-18,18>>^ Quando eu disser ao ímpio: Certamente morrerás; se não o avisares, nem falares para avisar o ímpio acerca do seu mau caminho, a fim de salvares a sua vida, aquele ímpio morrerá na sua iniqüidade; mas o seu sangue, da tua mão o requererei:

[[v26-3-19]]

^<<v26-3-19,19>>^ Contudo se tu avisares o ímpio, e ele não se converter da sua impiedade e do seu mau caminho, ele morrerá na sua iniqüidade; mas tu livraste a tua alma.

[[v26-3-20]]

^<<v26-3-20,20>>^ Semelhantemente, quando o justo se desviar da sua justiça, e praticar a iniqüidade, e eu puser diante dele um tropeço, ele morrerá; porque não o avisaste, no seu pecado morrerá e não serão lembradas as suas ações de justiça que tiver praticado; mas o seu sangue, da tua mão o requererei.

[[v26-3-21]]

^<<v26-3-21,21>>^ Mas se tu avisares o justo, para que o justo não peque, e ele não pecar, certamente viverá, porque recebeu o aviso; e tu livraste a tua alma.

[[v26-3-22]]

^<<v26-3-22,22>>^ E a mão do Senhor estava sobre mim ali, e ele me disse: Levanta-te, e sai ao vale, e ali falarei contigo.

[[v26-3-23]]

^<<v26-3-23,23>>^ Então me levantei, e saí ao vale; e eis que a glória do Senhor estava ali, como a glória que vi junto ao rio Quebar; e caí com o rosto em terra.

[[v26-3-24]]

^<<v26-3-24,24>>^ Então entrou em mim o Espírito, e me pôs em pé; e falou comigo, e me disse: Entra, encerra-te dentro da tua casa.

[[v26-3-25]]

^<<v26-3-25,25>>^ E quanto a ti, ó filho do homem, eis que porão cordas sobre ti, e te ligarão com elas, e tu não sairás por entre eles.

[[v26-3-26]]

^<<v26-3-26,26>>^ E eu farei que a tua língua se pegue ao teu paladar, e ficarás mudo, e não lhes servirás de repreendedor; pois casa rebelde são eles.

[[v26-3-27]]

^<<v26-3-27,27>>^ Mas quando eu falar contigo, abrirei a tua boca, e lhes dirás: Assim diz o Senhor Deus: Quem ouvir, ouça, e quem deixar de ouvir, deixe; pois casa rebelde são eles.

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]