include::./index.adoc[]

[[v61-1-0]]
=== 2 Pedro, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v61-1-1]]

^<<v61-1-1,1>>^ Simão Pedro, servo e apóstolo de Jesus Cristo, aos que conosco alcançaram fé igualmente preciosa na justiça do nosso Deus e Salvador Jesus Cristo:

[[v61-1-2]]

^<<v61-1-2,2>>^ Graça e paz vos sejam multiplicadas no pleno conhecimento de Deus e de Jesus nosso Senhor;

[[v61-1-3]]

^<<v61-1-3,3>>^ visto como o seu divino poder nos tem dado tudo o que diz respeito à vida e à piedade, pelo pleno conhecimento daquele que nos chamou por sua própria glória e virtude;

[[v61-1-4]]

^<<v61-1-4,4>>^ pelas quais ele nos tem dado as suas preciosas e grandíssimas promessas, para que por elas vos torneis participantes da natureza divina, havendo escapado da corrupção, que pela concupiscência há no mundo.

[[v61-1-5]]

^<<v61-1-5,5>>^ E por isso mesmo vós, empregando toda a diligência, acrescentai à vossa fé a virtude, e à virtude a ciência,

[[v61-1-6]]

^<<v61-1-6,6>>^ e à ciência o domínio próprio, e ao domínio próprio a perseverança, e à perseverança a piedade,

[[v61-1-7]]

^<<v61-1-7,7>>^ e à piedade a fraternidade, e à fraternidade o amor.

[[v61-1-8]]

^<<v61-1-8,8>>^ Porque, se em vós houver e abundarem estas coisas, elas não vos deixarão ociosos nem infrutíferos no pleno conhecimento de nosso Senhor Jesus Cristo.

[[v61-1-9]]

^<<v61-1-9,9>>^ Pois aquele em quem não há estas coisas é cego, vendo somente o que está perto, havendo-se esquecido da purificação dos seus antigos pecados.

[[v61-1-10]]

^<<v61-1-10,10>>^ Portanto, irmãos, procurai mais diligentemente fazer firme a vossa vocação e eleição; porque, fazendo isto, nunca jamais tropeçareis.

[[v61-1-11]]

^<<v61-1-11,11>>^ Porque assim vos será amplamente concedida a entrada no reino eterno do nosso Senhor e Salvador Jesus Cristo.

[[v61-1-12]]

^<<v61-1-12,12>>^ Pelo que estarei sempre pronto para vos lembrar estas coisas, ainda que as saibais, e estejais confirmados na verdade que já está convosco.

[[v61-1-13]]

^<<v61-1-13,13>>^ E tendo por justo, enquanto ainda estou neste tabernáculo, despertar-vos com admoestações,

[[v61-1-14]]

^<<v61-1-14,14>>^ sabendo que brevemente hei de deixar este meu tabernáculo, assim como nosso Senhor Jesus Cristo já mo revelou.

[[v61-1-15]]

^<<v61-1-15,15>>^ Mas procurarei diligentemente que também em toda ocasião depois da minha morte tenhais lembrança destas coisas.

[[v61-1-16]]

^<<v61-1-16,16>>^ Porque não seguimos fábulas engenhosas quando vos fizemos conhecer o poder e a vinda de nosso Senhor Jesus Cristo, pois nós fôramos testemunhas oculares da sua majestade.

[[v61-1-17]]

^<<v61-1-17,17>>^ Porquanto ele recebeu de Deus Pai honra e glória, quando pela Glória Magnífica lhe foi dirigida a seguinte voz: Este é o meu Filho amado, em quem me comprazo;

[[v61-1-18]]

^<<v61-1-18,18>>^ e essa voz, dirigida do céu, ouvimo-la nós mesmos, estando com ele no monte santo.

[[v61-1-19]]

^<<v61-1-19,19>>^ E temos ainda mais firme a palavra profética à qual bem fazeis em estar atentos, como a uma candeia que alumia em lugar escuro, até que o dia amanheça e a estrela da alva surja em vossos corações;

[[v61-1-20]]

^<<v61-1-20,20>>^ sabendo primeiramente isto: que nenhuma profecia da Escritura é de particular interpretação.

[[v61-1-21]]

^<<v61-1-21,21>>^ Porque a profecia nunca foi produzida por vontade dos homens, mas os homens da parte de Deus falaram movidos pelo Espírito Santo.

'''

xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[Próximo Capítulo &#62;]