include::./index.adoc[]

[[v61-3-0]]
=== 2 Pedro, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v61-3-1]]

^<<v61-3-1,1>>^ Amados, já é esta a segunda carta que vos escrevo; em ambas as quais desperto com admoestações o vosso ânimo sincero;

[[v61-3-2]]

^<<v61-3-2,2>>^ para que vos lembreis das palavras que dantes foram ditas pelos santos profetas, e do mandamento do Senhor e Salvador, dado mediante os vossos apóstolos;

[[v61-3-3]]

^<<v61-3-3,3>>^ sabendo primeiro isto, que nos últimos dias virão escarnecedores com zombaria andando segundo as suas próprias concupiscências,

[[v61-3-4]]

^<<v61-3-4,4>>^ e dizendo: Onde está a promessa da sua vinda? porque desde que os pais dormiram, todas as coisas permanecem como desde o princípio da criação.

[[v61-3-5]]

^<<v61-3-5,5>>^ Pois eles de propósito ignoram isto, que pela palavra de Deus já desde a antiguidade existiram os céus e a terra, que foi tirada da água e no meio da água subsiste;

[[v61-3-6]]

^<<v61-3-6,6>>^ pelas quais coisas pereceu o mundo de então, afogado em água;

[[v61-3-7]]

^<<v61-3-7,7>>^ mas os céus e a terra de agora, pela mesma palavra, têm sido guardados para o fogo, sendo reservados para o dia do juízo e da perdição dos homens ímpios.

[[v61-3-8]]

^<<v61-3-8,8>>^ Mas vós, amados, não ignoreis uma coisa: que um dia para o Senhor é como mil anos, e mil anos como um dia.

[[v61-3-9]]

^<<v61-3-9,9>>^ O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; porém é longânimo para convosco, não querendo que ninguém se perca, senão que todos venham a arrepender-se.

[[v61-3-10]]

^<<v61-3-10,10>>^ Virá, pois, como ladrão o dia do Senhor, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se dissolverão, e a terra, e as obras que nela há, serão descobertas.

[[v61-3-11]]

^<<v61-3-11,11>>^ Ora, uma vez que todas estas coisas hão de ser assim dissolvidas, que pessoas não deveis ser em santidade e piedade,

[[v61-3-12]]

^<<v61-3-12,12>>^ aguardando, e desejando ardentemente a vinda do dia de Deus, em que os céus, em fogo se dissolverão, e os elementos, ardendo, se fundirão?

[[v61-3-13]]

^<<v61-3-13,13>>^ Nós, porém, segundo a sua promessa, aguardamos novos céus e uma nova terra, nos quais habita a justiça.

[[v61-3-14]]

^<<v61-3-14,14>>^ Pelo que, amados, como estais aguardando estas coisas, procurai diligentemente que por ele sejais achados imaculados e irrepreensível em paz;

[[v61-3-15]]

^<<v61-3-15,15>>^ e tende por salvação a longanimidade de nosso Senhor; como também o nosso amado irmão Paulo vos escreveu, segundo a sabedoria que lhe foi dada;

[[v61-3-16]]

^<<v61-3-16,16>>^ como faz também em todas as suas epístolas, nelas falando acerca destas coisas, mas quais há pontos difíceis de entender, que os indoutos e inconstantes torcem, como o fazem também com as outras Escrituras, para sua própria perdição.

[[v61-3-17]]

^<<v61-3-17,17>>^ Vós, portanto, amados, sabendo isto de antemão, guardai-vos de que pelo engano dos homens perversos sejais juntamente arrebatados, e descaiais da vossa firmeza;

[[v61-3-18]]

^<<v61-3-18,18>>^ antes crescei na graça e no conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja dada a glória, assim agora, como até o dia da eternidade.

'''

xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[Próximo Capítulo &#62;]