include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v61-2-1]]

^<<v61-2-1,1>>^ Mas houve também entre o povo falsos profetas, como entre vós haverá falsos mestres, os quais introduzirão encobertamente heresias destruidoras, negando até o Senhor que os resgatou, trazendo sobre si mesmos repentina destruição.

[[v61-2-2]]

^<<v61-2-2,2>>^ E muitos seguirão as suas dissoluções, e por causa deles será blasfemado o caminho da verdade;

[[v61-2-3]]

^<<v61-2-3,3>>^ também, movidos pela ganância, e com palavras fingidas, eles farão de vós negócio; a condenação dos quais já de largo tempo não tarda e a sua destruição não dormita.

[[v61-2-4]]

^<<v61-2-4,4>>^ Porque se Deus não poupou a anjos quando pecaram, mas lançou-os no inferno, e os entregou aos abismos da escuridão, reservando-os para o juízo;

[[v61-2-5]]

^<<v61-2-5,5>>^ se não poupou ao mundo antigo, embora preservasse a Noé, pregador da justiça, com mais sete pessoas, ao trazer o dilúvio sobre o mundo dos ímpios;

[[v61-2-6]]

^<<v61-2-6,6>>^ se, reduzindo a cinza as cidades de Sodoma e Gomorra, condenou-as à destruição, havendo-as posto para exemplo aos que vivessem impiamente;

[[v61-2-7]]

^<<v61-2-7,7>>^ e se livrou ao justo Ló, atribulado pela vida dissoluta daqueles perversos

[[v61-2-8]]

^<<v61-2-8,8>>^ &#123;porque este justo, habitando entre eles, por ver e ouvir, afligia todos os dias a sua alma justa com as injustas obras deles&#125;;

[[v61-2-9]]

^<<v61-2-9,9>>^ também sabe o Senhor livrar da tentação os piedosos, e reservar para o dia do juízo os injustos, que já estão sendo castigados;

[[v61-2-10]]

^<<v61-2-10,10>>^ especialmente aqueles que, seguindo a carne, andam em imundas concupiscências, e desprezam toda autoridade. Atrevidos, arrogantes, não receiam blasfemar das dignidades,

[[v61-2-11]]

^<<v61-2-11,11>>^ enquanto que os anjos, embora maiores em força e poder, não pronunciam contra eles juízo blasfemo diante do Senhor.

[[v61-2-12]]

^<<v61-2-12,12>>^ Mas estes, como criaturas irracionais, por natureza feitas para serem presas e mortas, blasfemando do que não entendem, perecerão na sua corrupção,

[[v61-2-13]]

^<<v61-2-13,13>>^ recebendo a paga da sua injustiça; pois que tais homens têm prazer em deleites à luz do dia; nódoas são eles e máculas, deleitando-se em suas dissimulações, quando se banqueteiam convosco;

[[v61-2-14]]

^<<v61-2-14,14>>^ tendo os olhos cheios de adultério e insaciáveis no pecar; engodando as almas inconstantes, tendo um coração exercitado na ganância, filhos de maldição;

[[v61-2-15]]

^<<v61-2-15,15>>^ os quais, deixando o caminho direito, desviaram-se, tendo seguido o caminho de Balaão, filho de Beor, que amou o prêmio da injustiça,

[[v61-2-16]]

^<<v61-2-16,16>>^ mas que foi repreendido pela sua própria transgressão: um mudo jumento, falando com voz humana, impediu a loucura do profeta.

[[v61-2-17]]

^<<v61-2-17,17>>^ Estes são fontes sem água, névoas levadas por uma tempestade, para os quais está reservado o negrume das trevas.

[[v61-2-18]]

^<<v61-2-18,18>>^ Porque, falando palavras arrogantes de vaidade, nas concupiscências da carne engodam com dissoluções aqueles que mal estão escapando aos que vivem no erro;

[[v61-2-19]]

^<<v61-2-19,19>>^ prometendo-lhes liberdade, quando eles mesmos são escravos da corrupção; porque de quem um homem é vencido, do mesmo é feito escravo.

[[v61-2-20]]

^<<v61-2-20,20>>^ Porquanto se, depois de terem escapado das corrupções do mundo pelo pleno conhecimento do Senhor e Salvador Jesus Cristo, ficam de novo envolvidos nelas e vencidos, tornou-se-lhes o último estado pior que o primeiro.

[[v61-2-21]]

^<<v61-2-21,21>>^ Porque melhor lhes fora não terem conhecido o caminho da justiça, do que, conhecendo-o, desviarem-se do santo mandamento que lhes fora dado.

[[v61-2-22]]

^<<v61-2-22,22>>^ Deste modo sobreveio-lhes o que diz este provérbio verdadeiro; Volta o cão ao seu vômito, e a porca lavada volta a revolver-se no lamaçal.

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]