include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-5-1]]

^<<v38-5-1,1>>^ Tornei a levantar os meus olhos, e olhei, e eis um rolo voante.

[[v38-5-2]]

^<<v38-5-2,2>>^ Perguntou-me o anjo: Que vês? Eu respondi: Vejo um rolo voante, que tem vinte côvados de comprido e dez côvados de largo.

[[v38-5-3]]

^<<v38-5-3,3>>^ Então disse-me ele: Esta é a maldição que sairá pela face de toda a terra: porque daqui, conforme a maldição, será desarraigado todo o que furtar; assim como daqui será desarraigado conforme a maldição todo o que jurar falsamente.

[[v38-5-4]]

^<<v38-5-4,4>>^ Mandá-la-ei, diz o Senhor dos exércitos, e a farei entrar na casa do ladrão, e na casa do que jurar falsamente pelo meu nome; e permanecerá no meio da sua casa, e a consumirá juntamente com a sua madeira e com as suas pedras.

[[v38-5-5]]

^<<v38-5-5,5>>^ Então saiu o anjo, que falava comigo, e me disse: levanta agora os teus olhos, e vê que é isto que sai.

[[v38-5-6]]

^<<v38-5-6,6>>^ Eu perguntei: Que é isto? Respondeu ele: Isto é uma efa que sai. E disse mais: Esta é a iniqüidade em toda a terra.

[[v38-5-7]]

^<<v38-5-7,7>>^ E eis que foi levantada a tampa de chumbo, e uma mulher estava sentada no meio da efa.

[[v38-5-8]]

^<<v38-5-8,8>>^ Prosseguiu o anjo: Esta é a impiedade. E ele a lançou dentro da efa, e pôs sobre a boca desta o peso de chumbo.

[[v38-5-9]]

^<<v38-5-9,9>>^ Então levantei os meus olhos e olhei, e eis que vinham avançando duas mulheres com o vento nas suas asas, pois tinham asas como as da cegonha; e levantaram a efa entre a terra e o céu.

[[v38-5-10]]

^<<v38-5-10,10>>^ Perguntei ao anjo que falava comigo: Para onde levam elas a efa?

[[v38-5-11]]

^<<v38-5-11,11>>^ Respondeu-me ele: Para lhe edificarem uma casa na terra de Sinar; e, quando a casa for preparada, a efa será colocada ali no seu lugar.

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]