include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-1-1]]

^<<v38-1-1,1>>^ No oitavo mês do segundo ano de Dario veio a palavra do Senhor ao profeta Zacarias, filho de Berequias, filho de Ido, dizendo:

[[v38-1-2]]

^<<v38-1-2,2>>^ O Senhor se irou fortemente contra vossos pais.

[[v38-1-3]]

^<<v38-1-3,3>>^ Portanto dize-lhes: Assim diz o Senhor dos exércitos: Tornai-vos para mim, diz o Senhor dos exércitos, e eu me tornarei para vós, diz o Senhor dos exércitos.

[[v38-1-4]]

^<<v38-1-4,4>>^ Não sejais como vossos pais, aos quais clamavam os profetas antigos, dizendo: Assim diz o Senhor dos exércitos: Convertei-vos agora dos vossos maus caminhos e das vossas más obras; mas não ouviram, nem me atenderam, diz o Senhor.

[[v38-1-5]]

^<<v38-1-5,5>>^ Vossos pais, onde estão eles? E os profetas, viverão eles para sempre?

[[v38-1-6]]

^<<v38-1-6,6>>^ Contudo as minhas palavras e os meus estatutos, que eu ordenei pelos profetas, meus servos, acaso não alcançaram a vossos pais? E eles se arrependeram, e disseram: Assim como o Senhor dos exércitos fez tenção de nos tratar, segundo os nossos caminhos, e segundo as nossas obras, assim ele nos tratou.

[[v38-1-7]]

^<<v38-1-7,7>>^ Aos vinte e quatro dias do mês undécimo, que é o mês de sebate, no segundo ano de Dario, veio a palavra do Senhor ao profeta Zacarias, filho de Berequias, filho de Ido, dizendo:

[[v38-1-8]]

^<<v38-1-8,8>>^ Olhei de noite, e vi um homem montado num cavalo vermelho, e ele estava parado entre as murtas que se achavam no vale; e atrás dele estavam cavalos vermelhos, baios e brancos.

[[v38-1-9]]

^<<v38-1-9,9>>^ Então perguntei: Meu Senhor, quem são estes? Respondeu-me o anjo que falava comigo: Eu te mostrarei o que estes são.

[[v38-1-10]]

^<<v38-1-10,10>>^ Respondeu, pois, o homem que estava parado entre as murtas, e disse: Estes são os que o Senhor tem enviado para percorrerem a terra.

[[v38-1-11]]

^<<v38-1-11,11>>^ E eles responderam ao anjo do Senhor, que estava parado entre as murtas, e disseram: Nós temos percorrido a terra, e eis que a terra toda está tranqüila e em descanso.

[[v38-1-12]]

^<<v38-1-12,12>>^ Então o anjo do Senhor respondeu, e disse: O Senhor dos exércitos, até quando não terás compaixão de Jerusalém, e das cidades de Judá, contra as quais estiveste indignado estes setenta anos?

[[v38-1-13]]

^<<v38-1-13,13>>^ Respondeu o Senhor ao anjo que falava comigo, com palavras boas, palavras consoladoras.

[[v38-1-14]]

^<<v38-1-14,14>>^ O anjo, pois, que falava comigo, disse-me: Clama, dizendo: Assim diz o Senhor dos exércitos: Com grande zelo estou zelando por Jerusalém e por Sião.

[[v38-1-15]]

^<<v38-1-15,15>>^ E estou grandemente indignado contra as nações em descanso; porque eu estava um pouco indignado, mas eles agravaram o mal.

[[v38-1-16]]

^<<v38-1-16,16>>^ Portanto, o Senhor diz assim: Voltei-me, agora, para Jerusalém com misericórdia; nela será edificada a minha casa, diz o Senhor dos exércitos, e o cordel será estendido sobre Jerusalém.

[[v38-1-17]]

^<<v38-1-17,17>>^ Clama outra vez, dizendo: Assim diz o Senhor dos exércitos: As minhas cidades ainda se transbordarão de bens; e o Senhor ainda consolará a Sião, e ainda escolherá a Jerusalém.

[[v38-1-18]]

^<<v38-1-18,18>>^ Levantei os meus olhos, e olhei, e eis quatro chifres.

[[v38-1-19]]

^<<v38-1-19,19>>^ Eu perguntei ao anjo que falava comigo: Que é isto? Ele me respondeu: Estes são os chifres que dispersaram a Judá, a Israel e a Jerusalém.

[[v38-1-20]]

^<<v38-1-20,20>>^ O Senhor mostrou-me também quatro ferreiros.

[[v38-1-21]]

^<<v38-1-21,21>>^ Então perguntei: Que vêm estes a fazer? Ele respondeu, dizendo: Estes são os chifres que dispersaram Judá, de maneira que ninguém levantou a cabeça; mas estes vieram para os amedrontarem, para derrubarem os chifres das nações que levantaram os seus chifres contra a terra de Judá, a fim de a espalharem.

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]