include::./index.adoc[]

[[v38-13-0]]
=== Zacarias, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-13-1]]

^<<v38-13-1,1>>^ Naquele dia haverá uma fonte aberta para a casa de Davi, e para os habitantes de Jerusalém, para remover o pecado e a impureza.

[[v38-13-2]]

^<<v38-13-2,2>>^ Naquele dia, diz o Senhor dos exércitos, cortarei da terra os nomes dos ídolos, e deles não haverá mais memória; e também farei sair da terra os profetas e o espírito da impureza.

[[v38-13-3]]

^<<v38-13-3,3>>^ E se alguém ainda profetizar, seu pai e sua mãe, que o geraram, lhe dirão: Não viverás, porque falas mentiras em o nome do Senhor; e seu pai e sua mãe, que o geraram, o traspassarão quando profetizar.

[[v38-13-4]]

^<<v38-13-4,4>>^ Naquele dia os profetas se sentirão envergonhados, cada um da sua visão, quando profetizarem; nem mais se vestirão de manto de pêlos, para enganarem,

[[v38-13-5]]

^<<v38-13-5,5>>^ mas dirão: Não sou profeta, sou lavrador da terra; porque tenho sido escravo desde a minha mocidade.

[[v38-13-6]]

^<<v38-13-6,6>>^ E se alguém lhe disser: Que feridas são essas entre as tuas mãos? Dirá ele: São as feridas com que fui ferido em casa dos meus amigos.

[[v38-13-7]]

^<<v38-13-7,7>>^ Ó espada, ergue-te contra o meu pastor, e contra o varão que é o meu companheiro, diz o Senhor dos exércitos; fere ao pastor, e espalhar-se-ão as ovelhas; mas volverei a minha mão para os pequenos.

[[v38-13-8]]

^<<v38-13-8,8>>^ Em toda a terra, diz o Senhor, as duas partes dela serão exterminadas, e expirarão; mas a terceira parte restará nela.

[[v38-13-9]]

^<<v38-13-9,9>>^ E farei passar esta terceira parte pelo fogo, e a purificarei, como se purifica a prata, e a provarei, como se prova o ouro. Ela invocará o meu nome, e eu a ouvirei; direi: É meu povo; e ela dirá: O Senhor é meu Deus.

'''

xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[Próximo Capítulo &#62;]