include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-14-1]]

^<<v38-14-1,1>>^ Eis que vem um dia do Senhor, em que os teus despojos se repartirão no meio de ti.

[[v38-14-2]]

^<<v38-14-2,2>>^ Pois eu ajuntarei todas as nações para a peleja contra Jerusalém; e a cidade será tomada, e as casas serão saqueadas, e as mulheres forçadas; e metade da cidade sairá para o cativeiro mas o resto do povo não será exterminado da cidade.

[[v38-14-3]]

^<<v38-14-3,3>>^ Então o Senhor sairá, e pelejará contra estas nações, como quando peleja no dia da batalha.

[[v38-14-4]]

^<<v38-14-4,4>>^ Naquele dia estarão os seus pés sobre o monte das Oliveiras, que está defronte de Jerusalém para o oriente; se o monte das Oliveiras será fendido pelo meio, do oriente para o ocidente e haverá um vale muito grande; e metade do monte se removerá para o norte, e a outra metade dele para o sul.

[[v38-14-5]]

^<<v38-14-5,5>>^ E fugireis pelo vale dos meus montes, pois o vale dos montes chegará até Azel; e fugireis assim como fugistes de diante do terremoto nos dias de Uzias, rei de Judá. Então virá o Senhor meu Deus, e todos os santos com ele.

[[v38-14-6]]

^<<v38-14-6,6>>^ Acontecerá naquele dia, que não haverá calor, nem frio, nem geada;

[[v38-14-7]]

^<<v38-14-7,7>>^ porém será um dia conhecido do Senhor; nem dia nem noite será; mas até na parte da tarde haverá luz.

[[v38-14-8]]

^<<v38-14-8,8>>^ Naquele dia também acontecerá que correrão de Jerusalém águas vivas, metade delas para o mar oriental, e metade delas para o mar ocidental; no verão e no inverno sucederá isso.

[[v38-14-9]]

^<<v38-14-9,9>>^ E o Senhor será rei sobre toda a terra; naquele dia um será o Senhor, e um será o seu nome.

[[v38-14-10]]

^<<v38-14-10,10>>^ Toda a terra em redor se tornará em planície, desde Geba até Rimom, ao sul de Jerusalém; ela será exaltada, e habitará no seu lugar, desde a porta de Benjamim até o lugar da primeira porta, até a porta da esquina, e desde a torre de Hananel até os lagares do rei

[[v38-14-11]]

^<<v38-14-11,11>>^ E habitarão nela, e não haverá mais maldição; mas Jerusalém habitará em segurança.

[[v38-14-12]]

^<<v38-14-12,12>>^ Esta será a praga com que o Senhor ferirá todos os povos que guerrearam contra Jerusalém: apodrecer-se-á a sua carne, estando eles de pé, e se lhes apodrecerão os olhos nas suas órbitas, e a língua se lhes apodrecerá na boca,

[[v38-14-13]]

^<<v38-14-13,13>>^ Naquele dia também haverá da parte do Senhor um grande tumulto entre eles; e pegará cada um na mão do seu próximo, e cada um levantará a mão contra o seu próximo.

[[v38-14-14]]

^<<v38-14-14,14>>^ Também Judá pelejará contra Jerusalém; e se ajuntarão as riquezas de todas as nações circunvizinhas, ouro e prata, e vestidos em grande abundância.

[[v38-14-15]]

^<<v38-14-15,15>>^ Como esta praga, assim será a praga dos cavalos, dos muares, dos camelos e dos jumentos e de todos os animais que estiverem naqueles arraiais.

[[v38-14-16]]

^<<v38-14-16,16>>^ Então todos os que restarem de todas as nações que vieram contra Jerusalém, subirão de ano em ano para adorarem o Rei, o Senhor dos exércitos, e para celebrarem a festa dos tabernáculos.

[[v38-14-17]]

^<<v38-14-17,17>>^ E se alguma das famílias da terra não subir a Jerusalém, para adorar o Rei, o Senhor dos exércitos, não cairá sobre ela a chuva.

[[v38-14-18]]

^<<v38-14-18,18>>^ E, se a família do Egito não subir, nem vier, não virá sobre ela a chuva; virá a praga com que o Senhor ferirá as nações que não subirem a celebrar a festa dos tabernáculos.

[[v38-14-19]]

^<<v38-14-19,19>>^ Esse será o castigo do Egito, e o castigo de todas as nações que não subirem a celebrar a festa dos tabernáculos.

[[v38-14-20]]

^<<v38-14-20,20>>^ Naquele dia se gravará sobre as campainhas dos cavalos. SANTO AO SENHOR; e as panelas na casa do Senhor serão como as bacias diante do altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ E todas as panelas em Jerusalém e Judá serão consagradas ao Senhor dos exércitos; e todos os que sacrificarem virão, e delas tomarão, e nelas cozerão. Naquele dia não haverá mais cananeu na casa do Senhor dos exércitos.

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]