include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-3-1]]

^<<v38-3-1,1>>^ Ele me mostrou o sumo sacerdote Josué, o qual estava diante do anjo do Senhor, e Satanás estava à sua mão direita, para se lhe opor.

[[v38-3-2]]

^<<v38-3-2,2>>^ Mas o anjo do Senhor disse a Satanás: Que o Senhor te repreenda, ó Satanás; sim, o Senhor, que escolheu Jerusalém, te repreenda! Não é este um tição tirado do fogo?

[[v38-3-3]]

^<<v38-3-3,3>>^ Ora Josué, vestido de trajes sujos, estava em pé diante do anjo.

[[v38-3-4]]

^<<v38-3-4,4>>^ Então falando este, ordenou aos que estavam diante dele, dizendo: Tirai-lhe estes trajes sujos. E a Josué disse: Eis que tenho feito com que passe de ti a tua iniqüidade, e te vestirei de trajes festivos.

[[v38-3-5]]

^<<v38-3-5,5>>^ Também disse eu: Ponham-lhe sobre a cabeça uma mitra limpa. Puseram-lhe, pois, sobre a cabeça uma mitra limpa, e vestiram-no; e o anjo do Senhor estava ali de pe.

[[v38-3-6]]

^<<v38-3-6,6>>^ E o anjo do Senhor protestou a Josué, dizendo:

[[v38-3-7]]

^<<v38-3-7,7>>^ Assim diz o Senhor dos exércitos: Se andares nos meus caminhos, e se observares as minhas ordenanças, também tu julgarás a minha casa, e também guardarás os meus átrios, e te darei lugar entre os que estão aqui.

[[v38-3-8]]

^<<v38-3-8,8>>^ Ouve, pois, Josué, sumo sacerdote, tu e os teus companheiros que se assentam diante de ti, porque são homens portentosos; eis que eu farei vir o meu servo, o Renovo.

[[v38-3-9]]

^<<v38-3-9,9>>^ Pois eis aqui a pedra que pus diante de Josué; sobre esta pedra única estão sete olhos. Eis que eu esculpirei a sua escultura, diz o Senhor dos exércitos, e tirarei a iniqüidade desta terra num só dia.

[[v38-3-10]]

^<<v38-3-10,10>>^ Naquele dia, diz o Senhor dos exércitos, cada um de vós convidará o seu vizinho para debaixo da videira e para debaixo da figueira.

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]