include::./index.adoc[]

[[v38-12-0]]
=== Zacarias, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-12-1]]

^<<v38-12-1,1>>^ A palavra do Senhor acerca de Israel: Fala o Senhor, o que estendeu o céu, e que lançou os alicerces da terra e que formou o espírito do homem dentro dele.

[[v38-12-2]]

^<<v38-12-2,2>>^ Eis que eu farei de Jerusalém um copo de atordoamento para todos os povos em redor, e também para Judá, durante o cerco contra Jerusalém.

[[v38-12-3]]

^<<v38-12-3,3>>^ Naquele dia farei de Jerusalém uma pedra pesada para todos os povos; todos os que a erguerem, serão gravemente feridos. E ajuntar-se-ão contra ela todas as nações da terra.

[[v38-12-4]]

^<<v38-12-4,4>>^ Naquele dia, diz o Senhor, ferirei de espanto a todos os cavalos, e de loucura os que montam neles. Mas sobre a casa de Judá abrirei os meus olhos, e ferirei de cegueira todos os cavalos dos povos.

[[v38-12-5]]

^<<v38-12-5,5>>^ Então os chefes de Judá dirão no seu coração: Os habitantes de Jerusalém são a minha força no Senhor dos exércitos, seu Deus.

[[v38-12-6]]

^<<v38-12-6,6>>^ Naquele dia porei os chefes de Judá como um braseiro ardente no meio de lenha, e como um facho entre gavelas; e eles devorarão à direita e à esquerda a todos os povos em redor; e Jerusalém será habitada outra vez no seu próprio lugar, mesmo em Jerusalém.

[[v38-12-7]]

^<<v38-12-7,7>>^ Também o Senhor salvará primeiro as tendas de Judá, para que a glória da casa de Davi e a glória dos habitantes de Jerusalém não se engrandeçam sobre Judá.

[[v38-12-8]]

^<<v38-12-8,8>>^ Naquele dia o Senhor defenderá os habitantes de Jerusalém, de sorte que o mais fraco dentre eles naquele dia será como Davi, e a casa de Davi será como Deus, como o anjo do Senhor diante deles.

[[v38-12-9]]

^<<v38-12-9,9>>^ E naquele dia, tratarei de destruir todas as nações que vierem contra Jerusalém.

[[v38-12-10]]

^<<v38-12-10,10>>^ Mas sobre a casa de Davi, e sobre os habitantes de Jerusalém, derramarei o espírito de graça e de súplicas; e olharão para aquele a quem traspassaram, e o prantearão como quem pranteia por seu filho único; e chorarão amargamente por ele, como se chora pelo primogênito.

[[v38-12-11]]

^<<v38-12-11,11>>^ Naquele dia será grande o pranto em Jerusalém, como o pranto de Hadade-Rimom no vale de Megidom.

[[v38-12-12]]

^<<v38-12-12,12>>^ E a terra pranteará, cada família à parte: a família da casa de Davi à parte, e suas mulheres à parte; e a família da casa de Natã à parte, e suas mulheres à parte;

[[v38-12-13]]

^<<v38-12-13,13>>^ a família da casa de Levi à parte, e suas mulheres à parte; a família de Simei à parte, e suas mulheres à parte;

[[v38-12-14]]

^<<v38-12-14,14>>^ todas as mais famílias, cada família à parte, e suas mulheres à parte.

'''

xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[Próximo Capítulo &#62;]