include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-4-1]]

^<<v38-4-1,1>>^ Ora o anjo que falava comigo voltou, e me despertou, como a um homem que é despertado do seu sono;

[[v38-4-2]]

^<<v38-4-2,2>>^ e me perguntou: Que vês? Respondi: Olho, e eis um castiçal todo de ouro, e um vaso de azeite em cima, com sete lâmpadas, e há sete canudos que se unem às lâmpadas que estão em cima dele;

[[v38-4-3]]

^<<v38-4-3,3>>^ e junto a ele há duas oliveiras, uma à direita do vaso de azeite, e outra à sua esquerda.

[[v38-4-4]]

^<<v38-4-4,4>>^ Então perguntei ao anjo que falava comigo: Meu senhor, que é isso?

[[v38-4-5]]

^<<v38-4-5,5>>^ Respondeu-me o anjo que falava comigo, e me disse: Não sabes tu o que isso é? E eu disse: Não, meu senhor.

[[v38-4-6]]

^<<v38-4-6,6>>^ Ele me respondeu, dizendo: Esta é a palavra do Senhor a Zorobabel, dizendo: Não por força nem por poder, mas pelo meu Espírito, diz o Senhor dos exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ Quem és tu, ó monte grande? Diante de Zorobabel tornar-te-ás uma campina; e ele trará a pedra angular com aclamações: Graça, graça a ela.

[[v38-4-8]]

^<<v38-4-8,8>>^ Ainda me veio a palavra do Senhor, dizendo:

[[v38-4-9]]

^<<v38-4-9,9>>^ As mãos de Zorobabel têm lançado os alicerces desta casa; também as suas mãos a acabarão; e saberás que o Senhor dos exércitos me enviou a vos.

[[v38-4-10]]

^<<v38-4-10,10>>^ Ora, quem despreza o dia das coisas pequenas? pois estes sete se alegrarão, vendo o prumo na mão de Zorobabel. São estes os sete olhos do Senhor, que discorrem por toda a terra.

[[v38-4-11]]

^<<v38-4-11,11>>^ Falei mais, e lhe perguntei: Que são estas duas oliveiras à direita e à esquerda do castiçal?

[[v38-4-12]]

^<<v38-4-12,12>>^ Segunda vez falei-lhe, perguntando: Que são aqueles dois ramos de oliveira, que estão junto aos dois tubos de ouro, e que vertem de si azeite dourado?

[[v38-4-13]]

^<<v38-4-13,13>>^ Ele me respondeu, dizendo: Não sabes o que é isso? E eu disse: Não, meu senhor.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então ele disse: Estes são os dois ungidos, que assistem junto ao Senhor de toda a terra.

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]