include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-7-1]]

^<<v38-7-1,1>>^ Aconteceu no ano quarto do rei Dario, que a palavra do Senhor veio a Zacarias, no dia quarto do nono mês, que é quisleu:

[[v38-7-2]]

^<<v38-7-2,2>>^ Ora, o povo de Betel tinha enviado Sarezer, e Regem-Meleque, e os seus homens, para suplicarem o favor do Senhor,

[[v38-7-3]]

^<<v38-7-3,3>>^ e para dizerem aos sacerdotes, que estavam na casa do Senhor dos exércitos, e aos profetas: Chorarei eu no quinto mês, com jejum, como o tenho feito por tantos anos?

[[v38-7-4]]

^<<v38-7-4,4>>^ Então a palavra do Senhor dos exércitos veio a mim, dizendo:

[[v38-7-5]]

^<<v38-7-5,5>>^ Fala a todo o povo desta terra, e aos sacerdotes, dizendo: Quando jejuastes, e pranteastes, no quinto e no sétimo mês, durante estes setenta anos, acaso foi mesmo para mim que jejuastes?

[[v38-7-6]]

^<<v38-7-6,6>>^ Ou quando comeis e quando bebeis, não é para vós mesmos que comeis e bebeis?

[[v38-7-7]]

^<<v38-7-7,7>>^ Não eram estas as palavras que o Senhor proferiu por intermédio dos profetas antigos, quando Jerusalém estava habitada e próspera, juntamente com as suas cidades ao redor dela, e quando o Sul e a campina eram habitados?

[[v38-7-8]]

^<<v38-7-8,8>>^ E a palavra do Senhor veio a Zacarias, dizendo:

[[v38-7-9]]

^<<v38-7-9,9>>^ Assim falou o Senhor dos exércitos: Executai juízo verdadeiro, mostrai bondade e compaixão cada um para com o seu irmão;

[[v38-7-10]]

^<<v38-7-10,10>>^ e não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre; e nenhum de vós intente no seu coração o mal contra o seu irmão.

[[v38-7-11]]

^<<v38-7-11,11>>^ Eles, porém, não quiseram escutar, e me deram o ombro rebelde, e taparam os ouvidos, para que não ouvissem.

[[v38-7-12]]

^<<v38-7-12,12>>^ Sim, fizeram duro como diamante o seu coração, para não ouvirem a lei, nem as palavras que o Senhor dos exércitos enviara pelo seu Espírito mediante os profetas antigos; por isso veio a grande ira do Senhor dos exércitos.

[[v38-7-13]]

^<<v38-7-13,13>>^ Assim como eu clamei, e eles não ouviram, assim também eles clamaram, e eu não ouvi, diz o Senhor dos exércitos;

[[v38-7-14]]

^<<v38-7-14,14>>^ mas os espalhei com um turbilhão por entre todas as nações, que eles não conheceram. Assim, pois, a terra foi assolada atrás deles, de sorte que ninguém passava por ela, nem voltava; porquanto fizeram da terra desejada uma desolação.

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]