include::./index.adoc[]

[[v38-10-0]]
=== Zacarias, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-10-1]]

^<<v38-10-1,1>>^ Pedi ao Senhor chuva no tempo da chuva serôdia, sim, ao Senhor, que faz os relâmpagos; e ele lhes dará chuvas copiosas, e a cada um erva no campo,

[[v38-10-2]]

^<<v38-10-2,2>>^ Pois os terafins falam vaidade, e os adivinhos vêem mentira e contam sonhos falsos; em vão procuram consolar; por isso seguem o seu caminho como ovelhas; estão aflitos, porque não há pastor.

[[v38-10-3]]

^<<v38-10-3,3>>^ Contra os pastores se acendeu a minha ira, e castigarei os bodes; mas o Senhor dos exércitos visitará o seu rebanho, a casa de Judá, e o fará como o seu majestoso cavalo na peleja.

[[v38-10-4]]

^<<v38-10-4,4>>^ De Judá sairá a pedra angular, dele a estaca da tenda, dele o arco de guerra, dele sairão todos os chefes.

[[v38-10-5]]

^<<v38-10-5,5>>^ Eles serão como valentes que na batalha pisam aos pés os seus inimigos na lama das ruas; pelejarão, porque o Senhor esta com eles; e confundirão os que andam montados em cavalos.

[[v38-10-6]]

^<<v38-10-6,6>>^ Fortalecerei a casa de Judá, e salvarei a casa de José; fá-los-ei voltar, porque me compadeço deles; e serão como se eu não os tivera rejeitado; porque eu sou o Senhor seu Deus, e os ouvirei.

[[v38-10-7]]

^<<v38-10-7,7>>^ Então os de Efraim serão como um valente, e o seu coração se alegrará como pelo vinho; seus filhos o verão, e se alegrarão; o seu coração se regozijará no Senhor.

[[v38-10-8]]

^<<v38-10-8,8>>^ Eu lhes assobiarei, e os ajuntarei, porque os tenho remido; e multiplicar-se-ão como dantes se multiplicavam.

[[v38-10-9]]

^<<v38-10-9,9>>^ Ainda que os espalhei entre os povos, eles se lembrarão de mim em terras remotas; e, com seus filhos, viverão e voltarão.

[[v38-10-10]]

^<<v38-10-10,10>>^ Pois eu os farei voltar da terra do Egito, e os congregarei da Assíria; e os trarei à terra de Gileade e do Líbano; e não se achará lugar bastante para eles.

[[v38-10-11]]

^<<v38-10-11,11>>^ Passarão pelo mar de aflição, e serão feridas as ondas do mar, e todas as profundezas do Nilo se secarão; então será abatida a soberba da Assíria, e o cetro do Egito se retirará.

[[v38-10-12]]

^<<v38-10-12,12>>^ Eu os fortalecerei no Senhor, e andarão no seu nome, diz o Senhor.

'''

xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[Próximo Capítulo &#62;]