include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-2-1]]

^<<v38-2-1,1>>^ Tornei a levantar os meus olhos, e olhei, e eis um homem que tinha na mão um cordel de medir.

[[v38-2-2]]

^<<v38-2-2,2>>^ Então perguntei: Para onde vais tu? Respondeu-me ele: Para medir Jerusalém, a fim de ver qual é a sua largura e qual o seu comprimento.

[[v38-2-3]]

^<<v38-2-3,3>>^ E eis que saiu o anjo que falava comigo, e outro anjo lhe saiu ao encontro,

[[v38-2-4]]

^<<v38-2-4,4>>^ e lhe disse: Corre, fala a este mancebo, dizendo: Jerusalém será habitada como as aldeias sem muros, por causa da multidão, nela, dos homens e dos animais.

[[v38-2-5]]

^<<v38-2-5,5>>^ Pois eu, diz o Senhor, lhe serei um muro de fogo em redor, e eu, no meio dela, lhe serei a glória.

[[v38-2-6]]

^<<v38-2-6,6>>^ Ah, ah! fugi agora da terra do norte, diz o Senhor, porque vos espalhei como os quatro ventos do céu, diz o Senhor.

[[v38-2-7]]

^<<v38-2-7,7>>^ Ah! Escapai para Sião, vós que habitais com a filha de Babilônia.

[[v38-2-8]]

^<<v38-2-8,8>>^ Pois assim diz o Senhor dos exércitos: Para obter a glória ele me enviou às nações que vos despojaram; porque aquele que tocar em vós toca na menina do seu olho.

[[v38-2-9]]

^<<v38-2-9,9>>^ Porque eis aí levantarei a minha mão contra eles, e eles virão a ser a presa daqueles que os serviram; assim sabereis vós que o Senhor dos exércitos me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ Exulta, e alegra-te, ó filha de Sião; pois eis que venho, e habitarei no meio de ti, diz o Senhor.

[[v38-2-11]]

^<<v38-2-11,11>>^ E naquele dia muitas nações se ajuntarão ao Senhor, e serão o meu povo; e habitarei no meio de ti, e saberás que o Senhor dos exércitos me enviou a ti.

[[v38-2-12]]

^<<v38-2-12,12>>^ Então o Senhor possuirá a Judá como sua porção na terra santa, e ainda escolherá a Jerusalém.

[[v38-2-13]]

^<<v38-2-13,13>>^ Cale-se, toda a carne, diante do Senhor; porque ele se levantou da sua santa morada.

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]