include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-11-1]]

^<<v38-11-1,1>>^ Abre, ó Líbano, as tuas portas para que o fogo devore os teus cedros.

[[v38-11-2]]

^<<v38-11-2,2>>^ Geme, ó cipreste, porque caiu o cedro, porque os mais excelentes são destruídos; gemei, ó carvalhos de Basã, porque o bosque forte é derrubado.

[[v38-11-3]]

^<<v38-11-3,3>>^ Voz de uivo dos pastores! porque a sua glória é destruída; voz de bramido de leões novos! porque foi destruída a soberba do Jordão.

[[v38-11-4]]

^<<v38-11-4,4>>^ Assim diz o Senhor meu Deus: Apascenta as ovelhas destinadas para a matança,

[[v38-11-5]]

^<<v38-11-5,5>>^ cujos compradores as matam, e não se têm por culpados; e cujos vendedores dizem: Louvado seja o Senhor, porque hei enriquecido; e os seus pastores não têm piedade delas.

[[v38-11-6]]

^<<v38-11-6,6>>^ Certamente não terei mais piedade dos moradores desta terra, diz o Senhor; mas, eis que entregarei os homens cada um na mão do seu próximo e na mão do seu rei; eles ferirão a terra, e eu não os livrarei da mão deles.

[[v38-11-7]]

^<<v38-11-7,7>>^ Eu pois apascentei as ovelhas destinadas para a matança, as pobres ovelhas do rebanho. E tomei para mim duas varas: a uma chamei Graça, e à outra chamei União; e apascentei as ovelhas.

[[v38-11-8]]

^<<v38-11-8,8>>^ E destruí os três pastores num mês; porque me enfadei deles, e também eles se enfastiaram de mim.

[[v38-11-9]]

^<<v38-11-9,9>>^ Então eu disse: Não vos apascentarei mais; o que morrer morra, e o que for destruído seja destruído; e os que restarem, comam cada um a carne do seu próximo.

[[v38-11-10]]

^<<v38-11-10,10>>^ E tomei a minha vara Graça, e a quebrei, para desfazer o meu pacto, que tinha estabelecido com todos os povos.

[[v38-11-11]]

^<<v38-11-11,11>>^ Foi, pois, anulado naquele dia; assim os pobres do rebanho que me respeitavam, reconheceram que isso era palavra do Senhor.

[[v38-11-12]]

^<<v38-11-12,12>>^ E eu lhes disse: Se parece bem aos vossos olhos, dai-me o que me é devido; e, se não, deixai-o. Pesaram, pois, por meu salário, trinta moedas de prata.

[[v38-11-13]]

^<<v38-11-13,13>>^ Ora o Senhor disse-me: Arroja isso ao oleiro, esse belo preço em que fui avaliado por eles. E tomei as trinta moedas de prata, e as arrojei ao oleiro na casa do Senhor.

[[v38-11-14]]

^<<v38-11-14,14>>^ Então quebrei a minha segunda vara União, para romper a irmandade entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ Então o Senhor me disse: Toma ainda para ti os instrumentos de um pastor insensato.

[[v38-11-16]]

^<<v38-11-16,16>>^ Pois eis que suscitarei um pastor na terra, que não cuidará das que estão perecendo, não procurará as errantes, não curará a ferida, nem apascentará a sã; mas comerá a carne das gordas, e lhes despedaçará as unhas.

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do pastor inútil, que abandona o rebanho! a espada lhe cairá sobre o braço e sobre o olho direito; o seu braço será de todo mirrado, e o seu olho direito será inteiramente escurecido.

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]