include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v38-6-1]]

^<<v38-6-1,1>>^ De novo levantei os meus olhos, e olhei, e eis quatro carros que saíam dentre dois montes, e estes montes eram montes de bronze.

[[v38-6-2]]

^<<v38-6-2,2>>^ No primeiro carro eram cavalos vermelhos, no segundo carro cavalos pretos,

[[v38-6-3]]

^<<v38-6-3,3>>^ no terceiro carro cavalos brancos, e no quarto carro cavalos baios com malhas.

[[v38-6-4]]

^<<v38-6-4,4>>^ Então, dirigindo-me ao anjo que falava comigo, perguntei: Que são estes, meu senhor?

[[v38-6-5]]

^<<v38-6-5,5>>^ Respondeu-me o anjo: Estes estão saindo aos quatro ventos do céu, depois de se apresentarem perante o Senhor de toda a terra.

[[v38-6-6]]

^<<v38-6-6,6>>^ O carro em que estão os cavalos pretos sai para a terra do norte, os brancos são para o oeste, e os malhados para a terra do sul;

[[v38-6-7]]

^<<v38-6-7,7>>^ e os cavalos baios saíam, e procuravam ir por diante, para percorrerem a terra. E ele disse: Ide, percorrei a terra. E eles a percorriam.

[[v38-6-8]]

^<<v38-6-8,8>>^ Então clamou para mim, dizendo: Eis que aqueles que saíram para a terra do norte fazem repousar na terra do norte o meu Espírito.

[[v38-6-9]]

^<<v38-6-9,9>>^ Ainda me veio a palavra do Senhor, dizendo:

[[v38-6-10]]

^<<v38-6-10,10>>^ Recebe dos que foram levados cativos, a saber, de Heldai, de Tobias, e de Jedaías, e vem tu no mesmo dia, e entra na casa de Josias, filho de Sofonias, para a qual vieram de Babilônia;

[[v38-6-11]]

^<<v38-6-11,11>>^ recebe, digo, prata e ouro, e faze coroas, e põe-nas na cabeça do sumo sacerdote Josué, filho de Jeozadaque;

[[v38-6-12]]

^<<v38-6-12,12>>^ e fala-lhe, dizendo: Assim diz o Senhor dos exércitos: Eis aqui o homem cujo nome é Renovo; ele brotará do seu lugar, e edificará o templo do Senhor.

[[v38-6-13]]

^<<v38-6-13,13>>^ Ele mesmo edificará o templo do Senhor; receberá a honra real, assentar-se-á no seu trono, e dominará. E Josué, o sacerdote, ficará à sua direita; e haverá entre os dois o conselho de paz.

[[v38-6-14]]

^<<v38-6-14,14>>^ Essas coroas servirão a Helem, e a Tobias, e a Jedaías, e a Hem, filho de Sofonias, de memorial no templo do Senhor.

[[v38-6-15]]

^<<v38-6-15,15>>^ E aqueles que estão longe virão, e ajudarão a edificar o templo do Senhor; e vós sabereis que o Senhor dos exércitos me tem enviado a vós; e isso sucederá, se diligentemente obedecerdes a voz do Senhor vosso Deus.

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]