include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v27-6-1]]

^<<v27-6-1,1>>^ Pareceu bem a Dario constituir sobre o reino cento e vinte sátrapas, que estivessem por todo o reino;

[[v27-6-2]]

^<<v27-6-2,2>>^ e sobre eles três presidentes, dos quais Daniel era um; a fim de que estes sátrapas lhes dessem conta, e que o rei não sofresse dano.

[[v27-6-3]]

^<<v27-6-3,3>>^ Então o mesmo Daniel sobrepujava a estes presidentes e aos sátrapas; porque nele havia um espírito excelente; e o rei pensava constituí-lo sobre todo o reino:

[[v27-6-4]]

^<<v27-6-4,4>>^ Nisso os presidentes e os sátrapas procuravam achar ocasião contra Daniel a respeito do reino mas não podiam achar ocasião ou falta alguma; porque ele era fiel, e não se achava nele nenhum erro nem falta.

[[v27-6-5]]

^<<v27-6-5,5>>^ Pelo que estes homens disseram: Nunca acharemos ocasião alguma contra este Daniel, a menos que a procuremos no que diz respeito a lei do seu Deus.

[[v27-6-6]]

^<<v27-6-6,6>>^ Então os presidentes e os sátrapas foram juntos ao rei, e disseram-lhe assim: Ó rei Dario, vive para sempre.

[[v27-6-7]]

^<<v27-6-7,7>>^ Todos os presidentes do reino, os prefeitos e os sátrapas, os conselheiros e os governadores, concordaram em que o rei devia baixar um decreto e publicar o respectivo interdito, que qualquer que, por espaço de trinta dias, fizer uma petição a qualquer deus, ou a qualquer homem, exceto a ti, ó rei, seja lançado na cova dos leões.

[[v27-6-8]]

^<<v27-6-8,8>>^ Agora pois, ó rei, estabelece o interdito, e assina o edital, para que não seja mudado, conforme a lei dos medos e dos persas, que não se pode revogar.

[[v27-6-9]]

^<<v27-6-9,9>>^ Em virtude disto o rei Dario assinou o edital e o interdito.

[[v27-6-10]]

^<<v27-6-10,10>>^ Quando Daniel soube que o edital estava assinado, entrou em sua casa, no seu quarto em cima, onde estavam abertas as janelas que davam para o lado de Jerusalém; e três vezes no dia se punha de joelhos e orava, e dava graças diante do seu Deus, como também antes costumava fazer.

[[v27-6-11]]

^<<v27-6-11,11>>^ Então aqueles homens foram juntos, e acharam a Daniel orando e suplicando diante do seu Deus.

[[v27-6-12]]

^<<v27-6-12,12>>^ Depois se foram à presença do rei e lhe perguntaram no tocante ao interdito real: Porventura não assinaste um interdito pelo qual todo homem que fizesse uma petição a qualquer deus, ou a qualquer homem por espaço de trinta dias, exceto a ti, ó rei, fosse lançado na cova dos leões? Respondeu o rei, e disse: Esta palavra é certa, conforme a lei dos medos e dos persas, que não se pode revogar.

[[v27-6-13]]

^<<v27-6-13,13>>^ Então responderam ao rei, dizendo-lhe Esse Daniel, que é dos exilados de Judá, e não tem feito caso de ti, ó rei, nem do interdito que assinaste; antes três vezes por dia faz a sua oração.

[[v27-6-14]]

^<<v27-6-14,14>>^ Ouvindo então o rei a notícia, ficou muito penalizado, e a favor de Daniel propôs dentro do seu coração livrá-lo; e até o pôr do sol trabalhou para o salvar.

[[v27-6-15]]

^<<v27-6-15,15>>^ Nisso aqueles homens foram juntos ao rei, e lhe disseram: Sabe, ó rei, que é lei dos medos e persas que nenhum interdito ou decreto que o rei estabelecer, se pode mudar.

[[v27-6-16]]

^<<v27-6-16,16>>^ Então o rei deu ordem, e trouxeram Daniel, e o lançaram na cova dos leões. Ora, disse o rei a Daniel: O teu Deus, a quem tu continuamente serves, ele te livrará.

[[v27-6-17]]

^<<v27-6-17,17>>^ E uma pedra foi trazida e posta sobre a boca da cova; e o rei a selou com o seu anel e com o anel dos seus grandes, para que no tocante a Daniel nada se mudasse:

[[v27-6-18]]

^<<v27-6-18,18>>^ Depois o rei se dirigiu para o seu palácio, e passou a noite em jejum; e não foram trazidos à sua presença instrumentos de música, e fugiu dele o sono.

[[v27-6-19]]

^<<v27-6-19,19>>^ Então o rei se levantou ao romper do dia, e foi com pressa à cova dos leões.

[[v27-6-20]]

^<<v27-6-20,20>>^ E, chegando-se à cova, chamou por Daniel com voz triste; e disse o rei a Daniel: Ó Daniel, servo do Deus vivo, dar-se-ia o caso que o teu Deus, a quem tu continuamente serves, tenha podido livrar-te dos leões?

[[v27-6-21]]

^<<v27-6-21,21>>^ Então Daniel falou ao rei: Ó rei, vive para sempre.

[[v27-6-22]]

^<<v27-6-22,22>>^ O meu Deus enviou o seu anjo, e fechou a boca dos leões, e eles não me fizeram mal algum; porque foi achada em mim inocência diante dele; e também diante de ti, ó rei, não tenho cometido delito algum.

[[v27-6-23]]

^<<v27-6-23,23>>^ Então o rei muito se alegrou, e mandou tirar a Daniel da cova. Assim foi tirado Daniel da cova, e não se achou nele lesão alguma, porque ele havia confiado em seu Deus.

[[v27-6-24]]

^<<v27-6-24,24>>^ E o rei deu ordem, e foram trazidos aqueles homens que tinham acusado Daniel, e foram lançados na cova dos leões, eles, seus filhos e suas mulheres; e ainda não tinham chegado ao fundo da cova quando os leões se apoderaram deles, e lhes esmigalharam todos os ossos.

[[v27-6-25]]

^<<v27-6-25,25>>^ Então o rei Dario escreveu a todos os povos, nações e línguas que moram em toda a terra: Paz vos seja multiplicada.

[[v27-6-26]]

^<<v27-6-26,26>>^ Com isto faço um decreto, pelo qual em todo o domínio do meu reino os homens tremam e temam perante o Deus de Daniel; porque ele é o Deus vivo, e permanece para sempre; e o seu reino nunca será destruído; o seu domínio durará até o fim.

[[v27-6-27]]

^<<v27-6-27,27>>^ Ele livra e salva, e opera sinais e maravilhas no céu e na terra; foi ele quem livrou Daniel do poder dos leões.

[[v27-6-28]]

^<<v27-6-28,28>>^ Este Daniel, pois, prosperou no reinado de Dario, e no reinado de Ciro, o persa.

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]