include::./index.adoc[]

[[v27-2-0]]
=== Daniel, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v27-2-1]]

^<<v27-2-1,1>>^ Ora no segundo ano do reinado de Nabucodonosor, teve este uns sonhos; e o seu espírito se perturbou, e passou-se-lhe o sono.

[[v27-2-2]]

^<<v27-2-2,2>>^ Então o rei mandou chamar os magos, os encantadores, os adivinhadores, e os caldeus, para que declarassem ao rei os seus sonhos; eles vieram, pois, e se apresentaram diante do rei.

[[v27-2-3]]

^<<v27-2-3,3>>^ E o rei lhes disse: Tive um sonho, e para saber o sonho está perturbado o meu espírito.

[[v27-2-4]]

^<<v27-2-4,4>>^ Os caldeus disseram ao rei em aramaico: Ó rei, vive eternamente; dize o sonho a teus servos, e daremos a interpretação

[[v27-2-5]]

^<<v27-2-5,5>>^ Respondeu o rei, e disse aos caldeus: Esta minha palavra é irrevogável se não me fizerdes saber o sonho e a sua interpretação, sereis despedaçados, e as vossas casas serão feitas um monturo;

[[v27-2-6]]

^<<v27-2-6,6>>^ mas se vós me declarardes o sonho e a sua interpretação, recebereis de mim dádivas, recompensas e grande honra. Portanto declarai-me o sonho e a sua interpretação.

[[v27-2-7]]

^<<v27-2-7,7>>^ Responderam pela segunda vez: Diga o rei o sonho a seus servos, e daremos a interpretação.

[[v27-2-8]]

^<<v27-2-8,8>>^ Respondeu o rei, e disse: Bem sei eu que vós quereis ganhar tempo; porque vedes que a minha palavra é irrevogável.

[[v27-2-9]]

^<<v27-2-9,9>>^ se não me fizerdes saber o sonho, uma só sentença será a vossa; pois vós preparastes palavras mentirosas e perversas para as proferirdes na minha presença, até que se mude o tempo. portanto dizei-me o sonho, para que eu saiba que me podeis dar a sua interpretação.

[[v27-2-10]]

^<<v27-2-10,10>>^ Responderam os caldeus na presença do rei, e disseram: Não há ninguém sobre a terra que possa cumprir a palavra do rei; pois nenhum rei, por grande e poderoso que fosse, tem exigido coisa semelhante de algum mago ou encantador, ou caldeu.

[[v27-2-11]]

^<<v27-2-11,11>>^ A coisa que o rei requer é difícil, e ninguém há que a possa declarar ao rei, senão os deuses, cuja morada não é com a carne mortal.

[[v27-2-12]]

^<<v27-2-12,12>>^ Então o rei muito se irou e enfureceu, e ordenou que matassem a todos os sábios de Babilônia.

[[v27-2-13]]

^<<v27-2-13,13>>^ saiu, pois, o decreto, segundo o qual deviam ser mortos os sábios; e buscaram a Daniel e aos seus companheiros, para que fossem mortos.

[[v27-2-14]]

^<<v27-2-14,14>>^ Então Daniel falou avisada e prudentemente a Arioque, capitão da guarda do rei, que tinha saído para matar os sábios de Babilônia;

[[v27-2-15]]

^<<v27-2-15,15>>^ pois disse a Arioque, capitão do rei: Por que é o decreto do rei tão urgente? Então Arioque explicou o caso a Daniel.

[[v27-2-16]]

^<<v27-2-16,16>>^ Ao que Daniel se apresentou ao rei e pediu que lhe designasse o prazo, para que desse ao rei a interpretação.

[[v27-2-17]]

^<<v27-2-17,17>>^ Então Daniel foi para casa, e fez saber o caso a Hananias, Misael e Azarias, seus companheiros,

[[v27-2-18]]

^<<v27-2-18,18>>^ para que pedissem misericórdia ao Deus do céu sobre este mistério, a fim de que Daniel e seus companheiros não perecessem, juntamente com o resto dos sábios de Babilônia.

[[v27-2-19]]

^<<v27-2-19,19>>^ Então foi revelado o mistério a Daniel numa visão de noite; pelo que Daniel louvou o Deus do céu.

[[v27-2-20]]

^<<v27-2-20,20>>^ Disse Daniel: Seja bendito o nome de Deus para todo o sempre, porque são dele a sabedoria e a força.

[[v27-2-21]]

^<<v27-2-21,21>>^ Ele muda os tempos e as estações; ele remove os reis e estabelece os reis; é ele quem dá a sabedoria aos sábios e o entendimento aos entendidos.

[[v27-2-22]]

^<<v27-2-22,22>>^ Ele revela o profundo e o escondido; conhece o que está em trevas, e com ele mora a luz.

[[v27-2-23]]

^<<v27-2-23,23>>^ Ó Deus de meus pais, a ti dou graças e louvor porque me deste sabedoria e força; e agora me fizeste saber o que te pedimos; pois nos fizeste saber este assunto do rei.

[[v27-2-24]]

^<<v27-2-24,24>>^ Por isso Daniel foi ter com Arioque, ao qual o rei tinha constituído para matar os sábios de Babilônia; entrou, e disse-lhe assim: Não mates os sábios de Babilônia; introduze-me na presença do rei, e lhe darei a interpretação.

[[v27-2-25]]

^<<v27-2-25,25>>^ Então Arioque depressa introduziu Daniel à presença do rei, e disse-lhe assim: Achei dentre os filhos dos cativos de Judá um homem que fará saber ao rei a interpretação.

[[v27-2-26]]

^<<v27-2-26,26>>^ Respondeu o rei e disse a Daniel, cujo nome era Beltessazar: Podes tu fazer-me saber o sonho que tive e a sua interpretação?

[[v27-2-27]]

^<<v27-2-27,27>>^ Respondeu Daniel na presença do rei e disse: O mistério que o rei exigiu, nem sábios, nem encantadores, nem magos, nem adivinhadores lhe podem revelar;

[[v27-2-28]]

^<<v27-2-28,28>>^ mas há um Deus no céu, o qual revela os mistérios; ele, pois, fez saber ao rei Nabucodonosor o que há de suceder nos últimos dias. O teu sonho e as visões que tiveste na tua cama são estas:

[[v27-2-29]]

^<<v27-2-29,29>>^ Estando tu, ó rei, na tua cama, subiram os teus pensamentos sobre o que havia de suceder no futuro. Aquele, pois, que revela os mistérios te fez saber o que há de ser.

[[v27-2-30]]

^<<v27-2-30,30>>^ E a mim me foi revelado este mistério, não por ter eu mais sabedoria que qualquer outro vivente, mas para que a interpretação se fizesse saber ao rei, e para que entendesses os pensamentos do teu coração.

[[v27-2-31]]

^<<v27-2-31,31>>^ Tu, ó rei, na visão olhaste e eis uma grande estátua. Esta estátua, imensa e de excelente esplendor, estava em pé diante de ti; e a sua aparência era terrível.

[[v27-2-32]]

^<<v27-2-32,32>>^ A cabeça dessa estátua era de ouro fino; o peito e os braços de prata; o ventre e as coxas de bronze;

[[v27-2-33]]

^<<v27-2-33,33>>^ as pernas de ferro; e os pés em parte de ferro e em parte de barro.

[[v27-2-34]]

^<<v27-2-34,34>>^ Estavas vendo isto, quando uma pedra foi cortada, sem auxílio de mãos, a qual feriu a estátua nos pés de ferro e de barro, e os esmiuçou.

[[v27-2-35]]

^<<v27-2-35,35>>^ Então foi juntamente esmiuçado o ferro, o barro, o bronze, a prata e o ouro, os quais se fizeram como a pragana das eiras no estio, e o vento os levou, e não se podia achar nenhum vestígio deles; a pedra, porém, que feriu a estátua se tornou uma grande montanha, e encheu toda a terra.

[[v27-2-36]]

^<<v27-2-36,36>>^ Este é o sonho; agora diremos ao rei a sua interpretação.

[[v27-2-37]]

^<<v27-2-37,37>>^ Tu, ó rei, és rei de reis, a quem o Deus do céu tem dado o reino, o poder, a força e a glória;

[[v27-2-38]]

^<<v27-2-38,38>>^ e em cuja mão ele entregou os filhos dos homens, onde quer que habitem, os animais do campo e as aves do céu, e te fez reinar sobre todos eles; tu és a cabeça de ouro.

[[v27-2-39]]

^<<v27-2-39,39>>^ Depois de ti se levantará outro reino, inferior ao teu; e um terceiro reino, de bronze, o qual terá domínio sobre toda a terra.

[[v27-2-40]]

^<<v27-2-40,40>>^ E haverá um quarto reino, forte como ferro, porquanto o ferro esmiúça e quebra tudo; como o ferro quebra todas as coisas, assim ele quebrantará e esmiuçará.

[[v27-2-41]]

^<<v27-2-41,41>>^ Quanto ao que viste dos pés e dos dedos, em parte de barro de oleiro, e em parte de ferro, isso será um reino dividido; contudo haverá nele alguma coisa da firmeza do ferro, pois que viste o ferro misturado com barro de lodo.

[[v27-2-42]]

^<<v27-2-42,42>>^ E como os dedos dos pés eram em parte de ferro e em parte de barro, assim por uma parte o reino será forte, e por outra será frágil.

[[v27-2-43]]

^<<v27-2-43,43>>^ Quanto ao que viste do ferro misturado com barro de lodo, misturar-se-ão pelo casamento; mas não se ligarão um ao outro, assim como o ferro não se mistura com o barro.

[[v27-2-44]]

^<<v27-2-44,44>>^ Mas, nos dias desses reis, o Deus do céu suscitará um reino que não será jamais destruído; nem passará a soberania deste reino a outro povo; mas esmiuçará e consumirá todos esses reinos, e subsistirá para sempre.

[[v27-2-45]]

^<<v27-2-45,45>>^ Porquanto viste que do monte foi cortada uma pedra, sem auxílio de mãos, e ela esmiuçou o ferro, o bronze, o barro, a prata e o ouro, o grande Deus faz saber ao rei o que há de suceder no futuro. Certo é o sonho, e fiel a sua interpretação.

[[v27-2-46]]

^<<v27-2-46,46>>^ Então o rei Nabucodonosor caiu com o rosto em terra, e adorou a Daniel, e ordenou que lhe oferecessem uma oblação e perfumes suaves.

[[v27-2-47]]

^<<v27-2-47,47>>^ Respondeu o rei a Daniel, e disse: Verdadeiramente, o vosso Deus é Deus dos deuses, e o Senhor dos reis, e o revelador dos mistérios, pois pudeste revelar este mistério.

[[v27-2-48]]

^<<v27-2-48,48>>^ Então o rei engrandeceu a Daniel, e lhe deu muitas e grandes dádivas, e o pôs por governador sobre toda a província de Babilônia, como também o fez chefe principal de todos os sábios de Babilônia.

[[v27-2-49]]

^<<v27-2-49,49>>^ A pedido de Daniel, o rei constituiu superintendentes sobre os negócios da província de Babilônia a Sadraque, Mesaque e Abednego; mas Daniel permaneceu na corte do rei.

'''

xref:027-daniel/027-daniel-001.adoc#v27-1-0[&#60; Capítulo Anterior] | <<v27-2-0,Topo>> | xref:027-daniel/027-daniel-003.adoc#v27-3-0[Próximo Capítulo &#62;]