include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v27-8-1]]

^<<v27-8-1,1>>^ No ano terceiro do reinado do rei Belsazar apareceu-me uma visão, a mim, Daniel, depois daquela que me apareceu no princípio.

[[v27-8-2]]

^<<v27-8-2,2>>^ E na visão que tive, parecia-me que eu estava na cidadela de Susã, na província de Elão; e conforme a visão, eu estava junto ao rio Ulai.

[[v27-8-3]]

^<<v27-8-3,3>>^ Levantei os olhos, e olhei, e eis que estava em pé diante do rio um carneiro, que tinha dois chifres; e os dois chifres eram altos; mas um era mais alto do que o outro, e o mais alto subiu por último.

[[v27-8-4]]

^<<v27-8-4,4>>^ Vi que o carneiro dava marradas para o ocidente, e para o norte e para o sul; e nenhum dos animais lhe podia resistir, nem havia quem pudesse livrar-se do seu poder; ele, porém, fazia conforme a sua vontade, e se engrandecia.

[[v27-8-5]]

^<<v27-8-5,5>>^ E, estando eu considerando, eis que um bode vinha do ocidente sobre a face de toda a terra, mas sem tocar no chão; e aquele bode tinha um chifre notável entre os olhos.

[[v27-8-6]]

^<<v27-8-6,6>>^ E dirigiu-se ao carneiro que tinha os dois chifres, ao qual eu tinha visto em pé diante do rio, e correu contra ele no furor da sua força.

[[v27-8-7]]

^<<v27-8-7,7>>^ Vi-o chegar perto do carneiro; e, movido de cólera contra ele, o feriu, e lhe quebrou os dois chifres; não havia força no carneiro para lhe resistir, e o bode o lançou por terra, e o pisou aos pés; também não havia quem pudesse livrar o carneiro do seu poder.

[[v27-8-8]]

^<<v27-8-8,8>>^ O bode, pois, se engrandeceu sobremaneira; e estando ele forte, aquele grande chifre foi quebrado, e no seu lugar outros quatro também notáveis nasceram para os quatro ventos do céu.

[[v27-8-9]]

^<<v27-8-9,9>>^ Ainda de um deles saiu um chifre pequeno, o qual cresceu muito para o sul, e para o oriente, e para a terra formosa;

[[v27-8-10]]

^<<v27-8-10,10>>^ e se engrandeceu até o exército do céu; e lançou por terra algumas das estrelas desse exército, e as pisou.

[[v27-8-11]]

^<<v27-8-11,11>>^ Sim, ele se engrandeceu até o príncipe do exército; e lhe tirou o holocausto contínuo, e o lugar do seu santuário foi deitado abaixo.

[[v27-8-12]]

^<<v27-8-12,12>>^ E o exército lhe foi entregue, juntamente com o holocausto contínuo, por causa da transgressão; lançou a verdade por terra; e fez o que era do seu agrado, e prosperou.

[[v27-8-13]]

^<<v27-8-13,13>>^ Depois ouvi um santo que falava; e disse outro santo àquele que falava: Até quando durará a visão relativamente ao holocausto contínuo e à transgressão assoladora, e à entrega do santuário e do exército, para serem pisados?

[[v27-8-14]]

^<<v27-8-14,14>>^ Ele me respondeu: Até duas mil e trezentas tardes e manhãs; então o santuário será purificado.

[[v27-8-15]]

^<<v27-8-15,15>>^ Havendo eu, Daniel, tido a visão, procurei entendê-la, e eis que se me apresentou como que uma semelhança de homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi uma voz de homem entre as margens do Ulai, a qual gritou, e disse: Gabriel, faze que este homem entenda a visão.

[[v27-8-17]]

^<<v27-8-17,17>>^ Veio, pois, perto de onde eu estava; e vindo ele, fiquei amedrontado, e caí com o rosto em terra. Mas ele me disse: Entende, filho do homem, pois esta visão se refere ao tempo do fim.

[[v27-8-18]]

^<<v27-8-18,18>>^ Ora, enquanto ele falava comigo, caí num profundo sono, com o rosto em terra; ele, porém, me tocou, e me pôs em pé.

[[v27-8-19]]

^<<v27-8-19,19>>^ e disse: Eis que te farei saber o que há de acontecer no último tempo da ira; pois isso pertence ao determinado tempo do fim.

[[v27-8-20]]

^<<v27-8-20,20>>^ Aquele carneiro que viste, o qual tinha dois chifres, são estes os reis da Média e da Pérsia.

[[v27-8-21]]

^<<v27-8-21,21>>^ Mas o bode peludo é o rei da Grécia; e o grande chifre que tinha entre os olhos é o primeiro rei.

[[v27-8-22]]

^<<v27-8-22,22>>^ O ter sido quebrado, levantando-se quatro em lugar dele, significa que quatro reinos se levantarão da mesma nação, porém não com a força dele.

[[v27-8-23]]

^<<v27-8-23,23>>^ Mas, no fim do reinado deles, quando os transgressores tiverem chegado ao cúmulo, levantar-se-á um rei, feroz de semblante e que entende enigmas.

[[v27-8-24]]

^<<v27-8-24,24>>^ Grande será o seu poder, mas não de si mesmo; e destruirá terrivelmente, e prosperará, e fará o que lhe aprouver; e destruirá os poderosos e o povo santo.

[[v27-8-25]]

^<<v27-8-25,25>>^ Pela sua sutileza fará prosperar o engano na sua mão; no seu coração se engrandecerá, e destruirá a muitos que vivem em segurança; e se levantará contra o príncipe dos príncipes; mas será quebrado sem intervir mão de homem.

[[v27-8-26]]

^<<v27-8-26,26>>^ E a visão da tarde e da manhã, que foi dita, é verdadeira. Tu, porém, cerra a visão, porque se refere a dias mui distantes.

[[v27-8-27]]

^<<v27-8-27,27>>^ E eu, Daniel, desmaiei, e estive enfermo alguns dias; então me levantei e tratei dos negócios do rei. E espantei-me acerca da visão, pois não havia quem a entendesse.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]