include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v27-10-1]]

^<<v27-10-1,1>>^ No ano terceiro de Ciro, rei da Pérsia, foi revelada uma palavra a Daniel, cujo nome se chama Beltessazar, uma palavra verdadeira concernente a um grande conflito; e ele entendeu esta palavra, e teve entendimento da visão.

[[v27-10-2]]

^<<v27-10-2,2>>^ Naqueles dias eu, Daniel, estava pranteando por três semanas inteiras.

[[v27-10-3]]

^<<v27-10-3,3>>^ Nenhuma coisa desejável comi, nem carne nem vinho entraram na minha boca, nem me ungi com ungüento, até que se cumpriram as três semanas completas.

[[v27-10-4]]

^<<v27-10-4,4>>^ No dia vinte e quatro do primeiro mês, estava eu à borda do grande rio, o Tigre;

[[v27-10-5]]

^<<v27-10-5,5>>^ levantei os meus olhos, e olhei, e eis um homem vestido de linho e os seus lombos cingidos com ouro fino de Ufaz;

[[v27-10-6]]

^<<v27-10-6,6>>^ o seu corpo era como o berilo, e o seu rosto como um relâmpago; os seus olhos eram como tochas de fogo, e os seus braços e os seus pés como o brilho de bronze polido; e a voz das suas palavras como a voz duma multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ Ora, só eu, Daniel, vi aquela visão; pois os homens que estavam comigo não a viram: não obstante, caiu sobre eles um grande temor, e fugiram para se esconder.

[[v27-10-8]]

^<<v27-10-8,8>>^ Fiquei pois eu só a contemplar a grande visão, e não ficou força em mim; desfigurou-se a feição do meu rosto, e não retive força alguma.

[[v27-10-9]]

^<<v27-10-9,9>>^ Contudo, ouvi a voz das suas palavras; e, ouvindo o som das suas palavras, eu caí num profundo sono, com o rosto em terra.

[[v27-10-10]]

^<<v27-10-10,10>>^ E eis que uma mão me tocou, e fez com que me levantasse, tremendo, sobre os meus joelhos e sobre as palmas das minhas mãos.

[[v27-10-11]]

^<<v27-10-11,11>>^ E me disse: Daniel, homem muito amado, entende as palavras que te vou dizer, e levanta-te sobre os teus pés; pois agora te sou enviado. Ao falar ele comigo esta palavra, pus-me em pé tremendo.

[[v27-10-12]]

^<<v27-10-12,12>>^ Então me disse: Não temas, Daniel; porque desde o primeiro dia em que aplicaste o teu coração a compreender e a humilhar-te perante o teu Deus, são ouvidas as tuas palavras, e por causa das tuas palavras eu vim.

[[v27-10-13]]

^<<v27-10-13,13>>^ Mas o príncipe do reino da Pérsia me resistiu por vinte e um dias; e eis que Miguel, um dos primeiros príncipes, veio para ajudar-me, e eu o deixei ali com os reis da Pérsia.

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora vim, para fazer-te entender o que há de suceder ao teu povo nos derradeiros dias; pois a visão se refere a dias ainda distantes.

[[v27-10-15]]

^<<v27-10-15,15>>^ Ao falar ele comigo estas palavras, abaixei o rosto para a terra e emudeci.

[[v27-10-16]]

^<<v27-10-16,16>>^ E eis que um que tinha a semelhança dos filhos dos homens me tocou os lábios; então abri a boca e falei, e disse àquele que estava em pé diante de mim: Senhor meu, por causa da visão sobrevieram-me dores, e não retenho força alguma.

[[v27-10-17]]

^<<v27-10-17,17>>^ Como, pois, pode o servo do meu Senhor falar com o meu Senhor? pois, quanto a mim, desde agora não resta força em mim, nem fôlego ficou em mim.

[[v27-10-18]]

^<<v27-10-18,18>>^ Então tornou a tocar-me um que tinha a semelhança dum homem, e me consolou.

[[v27-10-19]]

^<<v27-10-19,19>>^ E disse: Não temas, homem muito amado; paz seja contigo; sê forte, e tem bom ânimo. E quando ele falou comigo, fiquei fortalecido, e disse: Fala, meu senhor, pois me fortaleceste.

[[v27-10-20]]

^<<v27-10-20,20>>^ Ainda disse ele: Sabes por que eu vim a ti? Agora tornarei a pelejar contra o príncipe dos persas; e, saindo eu, eis que virá o príncipe da Grécia.

[[v27-10-21]]

^<<v27-10-21,21>>^ Contudo eu te declararei o que está gravado na escritura da verdade; e ninguém há que se esforce comigo contra aqueles, senão Miguel, vosso príncipe.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]