include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v27-7-1]]

^<<v27-7-1,1>>^ No primeiro ano de Belsazar, rei de Babilônia, teve Daniel, na sua cama, um sonho e visões da sua cabeça. Então escreveu o sonho, e relatou a suma das coisas.

[[v27-7-2]]

^<<v27-7-2,2>>^ Falou Daniel, e disse: Eu estava olhando, numa visão noturna, e eis que os quatro ventos do céu agitavam o Mar Grande.

[[v27-7-3]]

^<<v27-7-3,3>>^ E quatro grandes animais, diferentes uns dos outros, subiam do mar.

[[v27-7-4]]

^<<v27-7-4,4>>^ O primeiro era como leão, e tinha asas de águia; enquanto eu olhava, foram-lhe arrancadas as asas, e foi levantado da terra, e posto em dois pés como um homem; e foi-lhe dado um coração de homem.

[[v27-7-5]]

^<<v27-7-5,5>>^ Continuei olhando, e eis aqui o segundo animal, semelhante a um urso, o qual se levantou de um lado, tendo na boca três costelas entre os seus dentes; e foi-lhe dito assim: Levanta-te, devora muita carne.

[[v27-7-6]]

^<<v27-7-6,6>>^ Depois disto, continuei olhando, e eis aqui outro, semelhante a um leopardo, e tinha nas costas quatro asas de ave; tinha também este animal quatro cabeças; e foi-lhe dado domínio.

[[v27-7-7]]

^<<v27-7-7,7>>^ Depois disto, eu continuava olhando, em visões noturnas, e eis aqui o quarto animal, terrível e espantoso, e muito forte, o qual tinha grandes dentes de ferro; ele devorava e fazia em pedaços, e pisava aos pés o que sobejava; era diferente de todos os animais que apareceram antes dele, e tinha dez chifres.

[[v27-7-8]]

^<<v27-7-8,8>>^ Eu considerava os chifres, e eis que entre eles subiu outro chifre, pequeno, diante do qual três dos primeiros chifres foram arrancados; e eis que neste chifre havia olhos, como os de homem, e uma boca que falava grandes coisas.

[[v27-7-9]]

^<<v27-7-9,9>>^ Eu continuei olhando, até que foram postos uns tronos, e um ancião de dias se assentou; o seu vestido era branco como a neve, e o cabelo da sua cabeça como lã puríssima; o seu trono era de chamas de fogo, e as rodas dele eram fogo ardente.

[[v27-7-10]]

^<<v27-7-10,10>>^ Um rio de fogo manava e saía de diante dele; milhares de milhares o serviam, e miríades de miríades assistiam diante dele. Assentou-se para o juízo, e os livros foram abertos.

[[v27-7-11]]

^<<v27-7-11,11>>^ Então estive olhando, por causa da voz das grandes palavras que o chifre proferia; estive olhando até que o animal foi morto, e o seu corpo destruído; pois ele foi entregue para ser queimado pelo fogo.

[[v27-7-12]]

^<<v27-7-12,12>>^ Quanto aos outros animais, foi-lhes tirado o domínio; todavia foi-lhes concedida prolongação de vida por um prazo e mais um tempo.

[[v27-7-13]]

^<<v27-7-13,13>>^ Eu estava olhando nas minhas visões noturnas, e eis que vinha com as nuvens do céu um como filho de homem; e dirigiu-se ao ancião de dias, e foi apresentado diante dele.

[[v27-7-14]]

^<<v27-7-14,14>>^ E foi-lhe dado domínio, e glória, e um reino, para que todos os povos, nações e línguas o servissem; o seu domínio é um domínio eterno, que não passará, e o seu reino tal, que não será destruído.

[[v27-7-15]]

^<<v27-7-15,15>>^ Quanto a mim, Daniel, o meu espírito foi abatido dentro do corpo, e as visões da minha cabeça me perturbavam.

[[v27-7-16]]

^<<v27-7-16,16>>^ Cheguei-me a um dos que estavam perto, e perguntei-lhe a verdadeira significação de tudo isso. Ele me respondeu e me fez saber a interpretação das coisas.

[[v27-7-17]]

^<<v27-7-17,17>>^ Estes grandes animais, que são quatro, são quatro reis, que se levantarão da terra.

[[v27-7-18]]

^<<v27-7-18,18>>^ Mas os santos do Altíssimo receberão o reino e o possuirão para todo o sempre, sim, para todo o sempre.

[[v27-7-19]]

^<<v27-7-19,19>>^ Então tive desejo de conhecer a verdade a respeito do quarto animal, que era diferente de todos os outros, sobremodo terrível, com dentes de ferro e unhas de bronze; o qual devorava, fazia em pedaços, e pisava aos pés o que sobrava;

[[v27-7-20]]

^<<v27-7-20,20>>^ e também a respeito dos dez chifres que ele tinha na cabeça, e do outro que subiu e diante do qual caíram três, isto é, daquele chifre que tinha olhos, e uma boca que falava grandes coisas, e parecia ser mais robusto do que os seus companheiros.

[[v27-7-21]]

^<<v27-7-21,21>>^ Enquanto eu olhava, eis que o mesmo chifre fazia guerra contra os santos, e prevalecia contra eles,

[[v27-7-22]]

^<<v27-7-22,22>>^ até que veio o ancião de dias, e foi executado o juízo a favor dos santos do Altíssimo; e chegou o tempo em que os santos possuíram o reino.

[[v27-7-23]]

^<<v27-7-23,23>>^ Assim me disse ele: O quarto animal será um quarto reino na terra, o qual será diferente de todos os reinos; devorará toda a terra, e a pisará aos pés, e a fará em pedaços.

[[v27-7-24]]

^<<v27-7-24,24>>^ Quanto aos dez chifres, daquele mesmo reino se levantarão dez reis; e depois deles se levantará outro, o qual será diferente dos primeiros, e abaterá a três reis.

[[v27-7-25]]

^<<v27-7-25,25>>^ Proferirá palavras contra o Altíssimo, e consumirá os santos do Altíssimo; cuidará em mudar os tempos e a lei; os santos lhe serão entregues na mão por um tempo, e tempos, e metade de um tempo.

[[v27-7-26]]

^<<v27-7-26,26>>^ Mas o tribunal se assentará em juízo, e lhe tirará o domínio, para o destruir e para o desfazer até o fim.

[[v27-7-27]]

^<<v27-7-27,27>>^ O reino, e o domínio, e a grandeza dos reinos debaixo de todo o céu serão dados ao povo dos santos do Altíssimo. O seu reino será um reino eterno, e todos os domínios o servirão, e lhe obedecerão.

[[v27-7-28]]

^<<v27-7-28,28>>^ Aqui é o fim do assunto. Quanto a mim, Daniel, os meus pensamentos muito me perturbaram e o meu semblante se mudou; mas guardei estas coisas no coração.

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]