include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v27-12-1]]

^<<v27-12-1,1>>^ Naquele tempo se levantará Miguel, o grande príncipe, que se levanta a favor dos filhos do teu povo; e haverá um tempo de tribulação, qual nunca houve, desde que existiu nação até aquele tempo; mas naquele tempo livrar-se-á o teu povo, todo aquele que for achado escrito no livro.

[[v27-12-2]]

^<<v27-12-2,2>>^ E muitos dos que dormem no pó da terra ressuscitarão, uns para a vida eterna, e outros para vergonha e desprezo eterno.

[[v27-12-3]]

^<<v27-12-3,3>>^ Os que forem sábios, pois, resplandecerão como o fulgor do firmamento; e os que converterem a muitos para a justiça, como as estrelas sempre e eternamente.

[[v27-12-4]]

^<<v27-12-4,4>>^ Tu, porém, Daniel, cerra as palavras e sela o livro, até o fim do tempo; muitos correrão de uma parte para outra, e a ciência se multiplicará.

[[v27-12-5]]

^<<v27-12-5,5>>^ Então eu, Daniel, olhei, e eis que estavam em pé outros dois, um de uma banda à beira do rio, e o outro da outra banda à beira do rio.

[[v27-12-6]]

^<<v27-12-6,6>>^ E perguntei ao homem vestido de linho, que estava por cima das águas do rio: Quanto tempo haverá até o fim destas maravilhas?

[[v27-12-7]]

^<<v27-12-7,7>>^ E ouvi o homem vestido de linho, que estava por cima das águas do rio, quando levantou ao céu a mão direita e a mão esquerda, e jurou por aquele que vive eternamente que isso seria para um tempo, dois tempos, e metade de um tempo. E quando tiverem acabado de despedaçar o poder do povo santo, cumprir-se-ão todas estas coisas.

[[v27-12-8]]

^<<v27-12-8,8>>^ Eu, pois, ouvi, mas não entendi; por isso perguntei: Senhor meu, qual será o fim destas coisas?

[[v27-12-9]]

^<<v27-12-9,9>>^ Ele respondeu: Vai-te, Daniel, porque estas palavras estão cerradas e seladas até o tempo do fim.

[[v27-12-10]]

^<<v27-12-10,10>>^ Muitos se purificarão, e se embranquecerão, e serão acrisolados; mas os ímpios procederão impiamente; e nenhum deles entenderá; mas os sábios entenderão.

[[v27-12-11]]

^<<v27-12-11,11>>^ E desde o tempo em que o holocausto contínuo for tirado, e estabelecida a abominação desoladora, haverá mil duzentos e noventa dias.

[[v27-12-12]]

^<<v27-12-12,12>>^ Bem-aventurado é o que espera e chega aos mil trezentos e trinta e cinco dias.

[[v27-12-13]]

^<<v27-12-13,13>>^ Tu, porém, vai-te, até que chegue o fim; pois descansarás, e estarás no teu quinhão ao fim dos dias.

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-oseias/028-oseias-001.adoc#v28-1-0[Próximo Capítulo &#62;]