include::./index.adoc[]

[[v13-12-0]]
=== 1 Crônicas, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-12-1]]

^<<v13-12-1,1>>^ Ora, estes são os que vieram a Davi a Ziclague, estando ele ainda tolhido nos seus movimentos por causa de Saul, filho de Quis; e eram dos valentes que o ajudaram na guerra.

[[v13-12-2]]

^<<v13-12-2,2>>^ Eram archeiros, e usavam tanto da mão direita como da esquerda em atirar pedras com fundas e em disparar flechas com o arco; eram dos irmãos de Saul, benjamitas.

[[v13-12-3]]

^<<v13-12-3,3>>^ Aizer, o chefe, e Joás, filhos de Semaá, o Gibeátita; Jeziel e Pelete, filhos de Azmavete; Beraca e Jeú, o anatotita;

[[v13-12-4]]

^<<v13-12-4,4>>^ Ismaías, o gibeonita, valente entre os trinta, e chefe deles; Jeremias, Jaaziel, Joanã e Jozabade, o gederatita;

[[v13-12-5]]

^<<v13-12-5,5>>^ Eluzai, Jerimote, Bealias, Semarias e Sefatias, o harufita;

[[v13-12-6]]

^<<v13-12-6,6>>^ Elcana, Issias, Azarel, Joezer e Jasobeão, os coraítas;

[[v13-12-7]]

^<<v13-12-7,7>>^ e Joela e Zebadias, filhos de Jeroão de Ged or.

[[v13-12-8]]

^<<v13-12-8,8>>^ Dos gaditas se passaram para Davi, ao lugar forte no deserto, homens valentes adestrados para a guerra, que sabiam manejar escudo e lança; seus rostos eram como rostos de leões, e eles eram tão ligeiros como corças sobre os montes.

[[v13-12-9]]

^<<v13-12-9,9>>^ Ezer era o chefe, Obadias o segundo, Eliabe o terceiro,

[[v13-12-10]]

^<<v13-12-10,10>>^ Mismana o quarto, Jeremias o quinto,

[[v13-12-11]]

^<<v13-12-11,11>>^ Atai o sexto, Eliel o sétimo,

[[v13-12-12]]

^<<v13-12-12,12>>^ Joanã o oitavo, Elzabade o nono,

[[v13-12-13]]

^<<v13-12-13,13>>^ Jeremias o décimo, Macbanai o undécimo.

[[v13-12-14]]

^<<v13-12-14,14>>^ Estes, dos filhos de Gade, foram os chefes do exército; o menor valia por cem, e o maior por mil.

[[v13-12-15]]

^<<v13-12-15,15>>^ Estes são os que passaram o Jordão no mês primeiro, quando ele transbordava por todas as suas ribanceiras, e puseram em fuga todos os dois vales ao oriente e ao ocidente.

[[v13-12-16]]

^<<v13-12-16,16>>^ Igualmente alguns dos filhos de Benjamim e de Judá vieram a Davi, ao lugar forte.

[[v13-12-17]]

^<<v13-12-17,17>>^ Davi saiu-lhes ao encontro e lhes disse: Se viestes a mim pacificamente para me ajudar, o meu coração se unirá convosco; porém se é para me entregar aos meus inimigos, sem que haja mal nas minhas mãos, o Deus de nossos pais o veja e o repreenda.

[[v13-12-18]]

^<<v13-12-18,18>>^ Então veio o espírito sobre Amasai, chefe dos trinta, que disse: Nós somos teus, ó Davi, e contigo estamos, ó filho de Jessé! Paz, paz contigo, e paz com quem te ajuda! pois que teu Deus te ajuda. E Davi os recebeu, e os fez chefes de tropas.

[[v13-12-19]]

^<<v13-12-19,19>>^ Também de Manassés alguns se passaram para Davi; foi quando ele veio com os filisteus para a batalha contra Saul; todavia não os ajudou, pois os chefes dos filisteus tendo feito conselho, o despediram, dizendo: Com perigo de nossas cabeças ele se passará para Saul, seu senhor:

[[v13-12-20]]

^<<v13-12-20,20>>^ Voltando ele, pois, a Ziclague, passaram-se para ele, de Manassés: Adná, Jozabade, Jediael, Micael, Jozabade, Eliú e Ziletai, chefes de milhares dos de Manassés.

[[v13-12-21]]

^<<v13-12-21,21>>^ E estes ajudaram a Davi contra a tropa de saqueadores, pois todos eles eram heróis valentes, e foram chefes no exército.

[[v13-12-22]]

^<<v13-12-22,22>>^ De dia em dia concorriam a Davi para o ajudar, até que se fez um grande exército, como o exército de Deus.

[[v13-12-23]]

^<<v13-12-23,23>>^ Ora, estes são os números dos chefes armados para a peleja, que vieram a Davi em Hebrom, para transferir a ele o reino de Saul, conforme a palavra do Senhor:

[[v13-12-24]]

^<<v13-12-24,24>>^ dos filhos de Judá, que traziam escudo e lança, seis mil e oitocentos, armados para a peleja;

[[v13-12-25]]

^<<v13-12-25,25>>^ dos filhos de Simeão, homens valentes para pelejar, sete mil e cem;

[[v13-12-26]]

^<<v13-12-26,26>>^ dos filhos de Levi quatro mil e seiscentos;

[[v13-12-27]]

^<<v13-12-27,27>>^ Jeoiada, que era o chefe da casa de Arão, e com ele três mil e setecentos;

[[v13-12-28]]

^<<v13-12-28,28>>^ e Zadoque, ainda jovem, homem valente, com vinte e dois príncipes da casa de seu pai;

[[v13-12-29]]

^<<v13-12-29,29>>^ dos filhos de Benjamim, irmãos de Saul, três mil, porque até então a maior parte deles se tinha conservado fiel à casa de Saul;

[[v13-12-30]]

^<<v13-12-30,30>>^ dos filhos de Efraim vinte mil e oitocentos homens valentes, homens de nome nas casas de seus pais;

[[v13-12-31]]

^<<v13-12-31,31>>^ da meia tribo de Manassés dezoito mil, que foram designados por nome para virem fazer Davi rei;

[[v13-12-32]]

^<<v13-12-32,32>>^ dos filhos de Issacar, duzentos de seus chefes, entendidos na ciência dos tempos para saberem o que Israel devia fazer, e todos os seus irmãos sob suas ordens;

[[v13-12-33]]

^<<v13-12-33,33>>^ de Zebulom, dos que podiam sair no exército, cinqüenta mil, ordenados para a peleja com todas as armas de guerra, como também destros para ordenarem a batalha, e não eram de coração dobre;

[[v13-12-34]]

^<<v13-12-34,34>>^ de Naftali, mil chefes, e com eles trinta e sete mil com escudo e lança;

[[v13-12-35]]

^<<v13-12-35,35>>^ dos danitas vinte e oito mil e seiscentos, destros para ordenarem a batalha;

[[v13-12-36]]

^<<v13-12-36,36>>^ de Aser, dos que podiam sair no exército e ordenar a batalha, quarenta mil;

[[v13-12-37]]

^<<v13-12-37,37>>^ da outra banda do Jordão, dos rubenitas e gaditas, e da meia tribo de Manassés, com toda sorte de instrumentos de guerra para pelejar, cento e vinte mil.

[[v13-12-38]]

^<<v13-12-38,38>>^ Todos estes, homens de guerra, que sabiam ordenar a batalha, vieram a Hebrom com inteireza de coração, para constituir Davi rei sobre todo o Israel; e também todo o resto de Israel estava de um só coração para constituir Davi rei.

[[v13-12-39]]

^<<v13-12-39,39>>^ E estiveram ali com Davi três dias, comendo e bebendo, pois seus irmãos lhes tinham preparado as provisões.

[[v13-12-40]]

^<<v13-12-40,40>>^ Também da vizinhança, e mesmo desde Issacar, Zebulom e Naftali, trouxeram sobre jumentos, e camelos, e mulos e bois, pão, provisões de farinha, pastas de figos e cachos de passas, vinho e azeite, bois e gado miúdo em abundância; porque havia alegria em Israel.

'''

xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[&#60; Capítulo Anterior] | <<v13-12-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[Próximo Capítulo &#62;]