include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-26-1]]

^<<v13-26-1,1>>^ Quanto às turmas dos porteiros: Meselemias, filho de Coré, dos filhos de Asafe.

[[v13-26-2]]

^<<v13-26-2,2>>^ E foram os filhos de Meselemias: Zacarias o primogênito, Jediael o segundo, Zebadias o terceiro, Jatniel o quarto,

[[v13-26-3]]

^<<v13-26-3,3>>^ Elão o quinto, Jeoanã o sexto, Elioenai, o sétimo.

[[v13-26-4]]

^<<v13-26-4,4>>^ Os filhos de Obede-Edom foram: Semaías o primogênito, Jeozabade o segundo, Joá o terceiro, Sacar o quarto, Netanel o quinto,

[[v13-26-5]]

^<<v13-26-5,5>>^ Amiel o sexto, Issacar o sétimo, Peuletai o oitavo; porque Deus o tinha abençoado.

[[v13-26-6]]

^<<v13-26-6,6>>^ Também a seu filho Semaías nasceram filhos, que dominaram sobre a casa de seu pai porque foram varões valentes.

[[v13-26-7]]

^<<v13-26-7,7>>^ Os filhos de Semaías: Otni, Rafael, Obede e Elzabade, com seus irmãos, homens valentes, Eliú e Semaquias.

[[v13-26-8]]

^<<v13-26-8,8>>^ Todos estes foram dos filhos de Obede-Edom; eles e seus filhos e irmãos, homens capazes e de força para o serviço, eram sessenta e dois, de Obede-Edom.

[[v13-26-9]]

^<<v13-26-9,9>>^ Os filhos e os irmãos de Meselemias, homens valentes, foram dezoito.

[[v13-26-10]]

^<<v13-26-10,10>>^ De Hosa, dos filhos de Merári, foram filhos: Sínri o chefe &#123;ainda que não era o primogênito, contudo seu pai o constituiu chefe&#125;,

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias o segundo, Tebalias o terceiro, e Zacarias o quarto; todos os filhos e irmãos de Hosa foram treze.

[[v13-26-12]]

^<<v13-26-12,12>>^ Destes se fizeram as turmas dos porteiros, isto é, dos homens principais, tendo cargos como seus irmãos, para ministrarem na casa do Senhor.

[[v13-26-13]]

^<<v13-26-13,13>>^ E lançaram sortes, assim os pequenos como os grandes, segundo as suas casas paternas, para cada porta.

[[v13-26-14]]

^<<v13-26-14,14>>^ E caiu a sorte do oriente a Selemias. Depois se lançou a sorte por seu filho Zacarias, conselheiro entendido, e saiu-lhe a do norte.

[[v13-26-15]]

^<<v13-26-15,15>>^ A Obede-Edom a do sul; e a seus filhos a casa dos depósitos.

[[v13-26-16]]

^<<v13-26-16,16>>^ A Supim e Hosa a do ocidente; perto da porta Salequete, junto ao caminho da subida, uma guarda defronte de outra guarda.

[[v13-26-17]]

^<<v13-26-17,17>>^ Ao oriente estavam seis levitas, ao norte quatro por dia, ao sul quatro por dia, porém para a casa dos depósitos de dois em dois.

[[v13-26-18]]

^<<v13-26-18,18>>^ Para Parbar, ao ocidente, quatro junto ao caminho, e dois junto a Parbar.

[[v13-26-19]]

^<<v13-26-19,19>>^ Essas foram as turmas dos porteiros dentre os filhos dos coraítas, e dentre os filhos de Merári.

[[v13-26-20]]

^<<v13-26-20,20>>^ E dos levitas, Aías tinha cargo dos tesouros da casa de Deus e dos tesouros das ofertas dedicadas.

[[v13-26-21]]

^<<v13-26-21,21>>^ Quanto aos filhos de Ladã, os filhos dos gersonitas que pertencem a Ladã, chefes das casas paternas de Ladã; Jeiéli.

[[v13-26-22]]

^<<v13-26-22,22>>^ Os filhos de Jeiéli: Zetão e Joel, seu irmão; estes tinham cargo dos tesouros da casa do Senhor.

[[v13-26-23]]

^<<v13-26-23,23>>^ Dos anramitas, dos izaritas:, dos hebronitas, dos uzielitas.

[[v13-26-24]]

^<<v13-26-24,24>>^ Sebuel, filho de Gérsom o filho de Moisés, que era chefe dos tesouros.

[[v13-26-25]]

^<<v13-26-25,25>>^ Seus irmãos: de Eliézer foi filho Reabias, de quem foi filho Jesaías, de quem foi filho Jorão, de quem foi filho Zicri, de quem foi filho Selomote.

[[v13-26-26]]

^<<v13-26-26,26>>^ Este Selomote e seus irmãos tinham a seu cargo todos os tesouros das ofertas dedicadas, que o rei Davi e os chefes das casas paternas, chefes de milhares, e de centenas, e chefes do exército tinham dedicado.

[[v13-26-27]]

^<<v13-26-27,27>>^ Dos despojos das guerras dedicaram ofertas para consertarem a casa do Senhor.

[[v13-26-28]]

^<<v13-26-28,28>>^ Também tudo quanto fora dedicado por Samuel, o vidente, Saul, filho de Quis, Abner, filho de Ner, e Joabe, filho de Zeruia, isto é, tudo quanto qualquer havia dedicado estava sob a guarda de Selomote e seus irmãos.

[[v13-26-29]]

^<<v13-26-29,29>>^ Dos izaritas, Quenanias e seus filhos foram postos sobre Israel para os negócios de fora, como oficiais e juízes.

[[v13-26-30]]

^<<v13-26-30,30>>^ Dos hebronitas foram Hasabias e seus irmãos, homens valentes, mil e setecentos, que tinham a seu cargo Israel, ao ocidente do Jordão, em todos os negócios do Senhor e no serviço do rei.

[[v13-26-31]]

^<<v13-26-31,31>>^ Jerias era o chefe dos hebronitas, segundo as suas gerações conforme as casas paternas. No ano quarenta do reino de Davi foram procurados, e acharam-se entre eles varões valentes em Jazer de Gileade.

[[v13-26-32]]

^<<v13-26-32,32>>^ A ele e a seus irmãos, dois mil e setecentos homens valentes, chefes das casas paternas, o rei Davi constituiu sobre os rubenitas e os gaditas, e a meia tribo dos manassitas, para todos os serviços de Deus, e para todos os negócios do rei.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]