include::./index.adoc[]

[[v13-24-0]]
=== 1 Crônicas, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-24-1]]

^<<v13-24-1,1>>^ As turmas dos filhos de Arão foram estas: os filhos de Arão: Nadabe, Abiú, Eleazar e Itamar.

[[v13-24-2]]

^<<v13-24-2,2>>^ Mas Nadabe e Abiú morreram antes de seu pai, e não tiveram filhos; por isso Eleazar e Itamar exerciam o sacerdócio.

[[v13-24-3]]

^<<v13-24-3,3>>^ E Davi, juntamente com Zadoque, dos filhos de Eleazar, e com Aimeleque, dos filhos de Itamar, os distribuiu segundo os deveres do seu serviço.

[[v13-24-4]]

^<<v13-24-4,4>>^ E acharam-se mais chefes dentre os filhos de Eleazar do que dentre os filhos de Itamar; e assim foram distribuídos: dos filhos de Eleazar, chefes das casas paternas, dezesseis; e dos filhos de Itamar, segundo as suas casas paternas, oito.

[[v13-24-5]]

^<<v13-24-5,5>>^ Assim foram distribuídos por sortes, tanto uns como os outros; porque havia príncipes do santuário e príncipes de Deus, tanto dentre os filhos de Eleazar, como dentre os filhos de Itamar.

[[v13-24-6]]

^<<v13-24-6,6>>^ E os registrou Semaías, filho de Netanel, o escrivão dentre os levitas, diante do rei, dos príncipes, de Zadoque, o sacerdote, de Aimeleque, filho de Abiatar, e dos chefes das casas paternas entre os sacerdotes e entre os levitas, tomando-se uma casa paterna para Eleazar, e outra para Itamar.

[[v13-24-7]]

^<<v13-24-7,7>>^ Assim a primeira sorte saiu a Jeoiaribe, a segunda a Jedaías,

[[v13-24-8]]

^<<v13-24-8,8>>^ a terceira a Harim, a quarta a Seorim,

[[v13-24-9]]

^<<v13-24-9,9>>^ a quinta a Malquias, a sexta a Miamim,

[[v13-24-10]]

^<<v13-24-10,10>>^ a sétima a Hacoz, a oitava a Abias,

[[v13-24-11]]

^<<v13-24-11,11>>^ a nona a Jesuá, a décima a Secanias,

[[v13-24-12]]

^<<v13-24-12,12>>^ a undécima a Eliasibe, a duodécima a Jaquim,

[[v13-24-13]]

^<<v13-24-13,13>>^ a décima terceira a Hupá, a décima quarta a Jesebeabe,

[[v13-24-14]]

^<<v13-24-14,14>>^ a décima quinta a Bilga, a décima sexta a Imer,

[[v13-24-15]]

^<<v13-24-15,15>>^ a décima sétima a Hezir, a décima oitava a Hapizes,

[[v13-24-16]]

^<<v13-24-16,16>>^ a décima nona a Petaías, a vigésima a Jeezquel,

[[v13-24-17]]

^<<v13-24-17,17>>^ a vigésima primeira a Jaquim, a vigésima segunda a Gamul,

[[v13-24-18]]

^<<v13-24-18,18>>^ a vigésima terceira a Delaías, a vigésima quarta a Maazias.

[[v13-24-19]]

^<<v13-24-19,19>>^ Esta foi a distribuição deles no seu serviço, para entrarem na casa do Senhor, segundo lhes fora ordenado por Arão, seu pai, como o Senhor Deus de Israel lhe tinha mandado.

[[v13-24-20]]

^<<v13-24-20,20>>^ Do restante dos filhos de Levi: dos filhos de Anrão, Subael; dos filhos de Subael, Jedeías.

[[v13-24-21]]

^<<v13-24-21,21>>^ Quanto a Reabias: dos filhos de Reabias, Issijá o chefe;

[[v13-24-22]]

^<<v13-24-22,22>>^ dos izaritas, Selomote; dos filhos de Selomote, Jaate;

[[v13-24-23]]

^<<v13-24-23,23>>^ dos filhos de Hebrom: Jerias o chefe, Amarias o segundo, Jaaziel o terceiro, Jecameão o quarto;

[[v13-24-24]]

^<<v13-24-24,24>>^ dos filhos de Uziel, Mica; dos filhos de Mica, Samir;

[[v13-24-25]]

^<<v13-24-25,25>>^ o irmão de Mica, Issijá; dos filhos de Issijá, Zacarias.

[[v13-24-26]]

^<<v13-24-26,26>>^ Os filhos de Merári, Mali e Musi; dos filhos de Jaazias, Beno;

[[v13-24-27]]

^<<v13-24-27,27>>^ os filhos de Merári: de Jaazias: Beno, Soão, Zacur e Ibri;

[[v13-24-28]]

^<<v13-24-28,28>>^ de Mali, Eleazar; e este não teve filhos.

[[v13-24-29]]

^<<v13-24-29,29>>^ Quanto a Quis: dos filhos de Quis, Jerameel;

[[v13-24-30]]

^<<v13-24-30,30>>^ e os filhos de Musi: Mali, Eder e Jerimote. Esses foram os filhos dos levitas, segundo as suas casas paternas.

[[v13-24-31]]

^<<v13-24-31,31>>^ Estes também, como seus irmãos, os filhos de Arão, lançaram sortes diante do rei Davi, de Zadoque, de Aimeleque, e dos chefes das casas paternas entre os sacerdotes e entre os levitas; assim fizeram, tanto para o chefe de casa paterna, como para o seu irmão menor.

'''

xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[&#60; Capítulo Anterior] | <<v13-24-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[Próximo Capítulo &#62;]