include::./index.adoc[]

[[v13-2-0]]
=== 1 Crônicas, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-2-1]]

^<<v13-2-1,1>>^ Foram estes os filhos de Israel: Rúben, Simeão, Levi, Judá, Issacar, Zebulom,

[[v13-2-2]]

^<<v13-2-2,2>>^ Dã, José, Benjamim, Naftali, Gade e Aser.

[[v13-2-3]]

^<<v13-2-3,3>>^ Os filhos de Judá: Er, Onã e Selá; estes três lhe nasceram da filha de Suá, a cananéia. E Er, o primogênito de Judá, foi mau aos olhos do Senhor, que o matou:

[[v13-2-4]]

^<<v13-2-4,4>>^ Tamar, nora de Judá, lhe deu à luz Pérez e Zerá. Ao todo os filhos de Judá foram cinco.

[[v13-2-5]]

^<<v13-2-5,5>>^ Os filhos de Perez: Hezrom e Hamul:

[[v13-2-6]]

^<<v13-2-6,6>>^ Os filhos de Zerá: Zinri, Etã, Hemã, Calcol e Dara; cinco ao todo.

[[v13-2-7]]

^<<v13-2-7,7>>^ Os filhos de Carmi: Acar, o perturbador de Israel, que pecou no anátema.

[[v13-2-8]]

^<<v13-2-8,8>>^ De Etã foi filho Azarias.

[[v13-2-9]]

^<<v13-2-9,9>>^ Os filhos que nasceram a Hezrom: Jerameel, Rão e Quelubai.

[[v13-2-10]]

^<<v13-2-10,10>>^ Rão foi pai de Aminadabe, e Aminadabe de Nasom, príncipe dos filhos de Judá;

[[v13-2-11]]

^<<v13-2-11,11>>^ Nason foi pai de Salmom, e Salmom de Boaz;

[[v13-2-12]]

^<<v13-2-12,12>>^ Boaz foi pai de Obede, e Obede de Jessé;

[[v13-2-13]]

^<<v13-2-13,13>>^ a Jessé nasceram Eliabe, seu primogênito, Abinadabe o segundo, Siméia o terceiro,

[[v13-2-14]]

^<<v13-2-14,14>>^ Netanel o quarto, Radai o quinto,

[[v13-2-15]]

^<<v13-2-15,15>>^ Ozen o sexto e Davi o sétimo;

[[v13-2-16]]

^<<v13-2-16,16>>^ e foram suas irmãs Zeruia e Abigail. Os filhos de Zeruia foram: Abisai, Joabe e Asael, três.

[[v13-2-17]]

^<<v13-2-17,17>>^ Abigail deu à luz Amasa; o pai de Amasa foi Jeter, o ismaelita.

[[v13-2-18]]

^<<v13-2-18,18>>^ A Calebe, filho de Hezrom, nasceram filhos de Azuba, sua mulher, e de Jeriote; e os filhos dela foram estes: Jeser, Sobabe e Ardom.

[[v13-2-19]]

^<<v13-2-19,19>>^ Morreu Azuba; e Calebe tomou para si Efrata, da qual lhe nasceu Hur.

[[v13-2-20]]

^<<v13-2-20,20>>^ Hur foi pai de îri, e îri de Bezaleel.

[[v13-2-21]]

^<<v13-2-21,21>>^ Então Hezrom, tendo já sessenta anos, tomou por mulher a filha de Maquir, pai de Gileade; e conheceu-a, e ela lhe deu à luz Segube.

[[v13-2-22]]

^<<v13-2-22,22>>^ Segube foi pai de Jair, o qual veio a ter vinte e três cidades na terra de Gileade.

[[v13-2-23]]

^<<v13-2-23,23>>^ Mas Gesur e Arã tomaram deles Havote-Jair, e Quenate e suas aldeias, sessenta cidades. Todos estes foram filhos de Maquir, pai de Gileade.

[[v13-2-24]]

^<<v13-2-24,24>>^ Depois da morte de Hezrom, em Calebe de Efrata, Abia, mulher de Hezrom, lhe deu Asur, pai de Tecoa.

[[v13-2-25]]

^<<v13-2-25,25>>^ Os filhos de Jerameel, primogênito de Jezrom, foram: Rão, o primogênito, Buna, Orem, Ozem e Aías.

[[v13-2-26]]

^<<v13-2-26,26>>^ Jerameel teve outra mulher, cujo nome era Atara, a qual foi mãe de Onã.

[[v13-2-27]]

^<<v13-2-27,27>>^ Os filhos de Rão, primogênito de Jerameel, foram: Maaz, Jamim e Equer.

[[v13-2-28]]

^<<v13-2-28,28>>^ Os filhos de Onã, foram: Samai e Jada; e os filhos de Samai: Nadabe e Abisur.

[[v13-2-29]]

^<<v13-2-29,29>>^ O nome da mulher de Abisur era Abiail, que lhe deu à luz Abã e Molide.

[[v13-2-30]]

^<<v13-2-30,30>>^ Os filhos de Nadabe: Selede e Apaim; e Selede morreu sem filhos.

[[v13-2-31]]

^<<v13-2-31,31>>^ O filho de Apaim: Isi; o filho de Isi: Sesã; o filho de Sesã: Alai.

[[v13-2-32]]

^<<v13-2-32,32>>^ Os filhos de Jada, irmão de Samai: Jeter e Jônatas; e Jeter morreu sem filhos.

[[v13-2-33]]

^<<v13-2-33,33>>^ Os filhos de Jônatas: Pelete e Zaza. Esses foram os filhos de Jerameel.

[[v13-2-34]]

^<<v13-2-34,34>>^ Sesã não teve filhos, mas filhas. E tinha Sesã um servo egípcio, cujo nome era Jará:

[[v13-2-35]]

^<<v13-2-35,35>>^ Deu, pois, Sesã sua filha por mulher a Jará, seu servo; e ela lhe deu à luz Atai.

[[v13-2-36]]

^<<v13-2-36,36>>^ Atai foi pai de Natã, Natã de Zabade,

[[v13-2-37]]

^<<v13-2-37,37>>^ Zabade de Eflal, Eflal de Obede,

[[v13-2-38]]

^<<v13-2-38,38>>^ Obede de Jeú, Jeú de Azarias,

[[v13-2-39]]

^<<v13-2-39,39>>^ Azarias de Helez, Helez de Eleasá,

[[v13-2-40]]

^<<v13-2-40,40>>^ Eleasá de Sismai, Sismai de Salum,

[[v13-2-41]]

^<<v13-2-41,41>>^ Salum de Jecamias, e Jecamias de Elisama.

[[v13-2-42]]

^<<v13-2-42,42>>^ Os filhos de Calebe, irmão de Jerameel: Messa, seu primogênito, que foi o pai de Zife, e os filhos de Maressa, pai de Hebrom.

[[v13-2-43]]

^<<v13-2-43,43>>^ Os filhos de Hebrom: Corá, Tapua, Requem e Sema.

[[v13-2-44]]

^<<v13-2-44,44>>^ Sema foi pai de Raão, pai de Jorqueão; e Requem foi pai de Samai.

[[v13-2-45]]

^<<v13-2-45,45>>^ O filho de Samai foi Maom; e Maom foi pai de Bete-Zur.

[[v13-2-46]]

^<<v13-2-46,46>>^ Efá, a concubina de Calebe, teve Harã, Moza e Gazez; e Harã foi pai de Gazez.

[[v13-2-47]]

^<<v13-2-47,47>>^ Os filhos de Jadai: Regem, Jotão, Gesã, Pelete, Efá e Saafe.

[[v13-2-48]]

^<<v13-2-48,48>>^ Maacá, concubina de Calebe, deu à luz Seber e Tiraná.

[[v13-2-49]]

^<<v13-2-49,49>>^ Deu à luz também Saafe, pai de Madmana, e Seva, pai de Macbena e de Gibeá; e a filha de Calebe foi Acsa.

[[v13-2-50]]

^<<v13-2-50,50>>^ Estes foram os filhos de Calebe, filho de Hur, o primogênito de Efrata: Sobal, pai de Quiriate-Jearim,

[[v13-2-51]]

^<<v13-2-51,51>>^ Salma, pai de Belém, e Harefe, pai de Bete-Gader.

[[v13-2-52]]

^<<v13-2-52,52>>^ Os filhos de Sobal, pai de Quiriate-Jearim, foram: Haroé e metade dos menuotes.

[[v13-2-53]]

^<<v13-2-53,53>>^ As famílias de Quiriate-Jearim: os itreus, os puteus, os sumateus e os misraeus; destes saíram os zorateus e os estaloeus.

[[v13-2-54]]

^<<v13-2-54,54>>^ Os filhos de Salma: Belém, os netofatitas, Atarote-Bete-Joabe, metade dos manaatitas e os zoritas.

[[v13-2-55]]

^<<v13-2-55,55>>^ As famílias dos escribas que habitavam em Jabes: os tiratitas, os simeatitas e os sucatitas; estes são os queneus que descenderam de Hamate, pai da casa de Recabe.

'''

xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[&#60; Capítulo Anterior] | <<v13-2-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[Próximo Capítulo &#62;]