include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-20-1]]

^<<v13-20-1,1>>^ Aconteceu pois que, na primavera, no tempo em que os reis costumam sair para a guerra, Joabe levou a flor do exército, e devastou a terra dos amonitas, e foi, e pôs cerco a Rabá; porém Davi ficou em Jerusalém. E Joabe bateu Rabá, e a destruiu.

[[v13-20-2]]

^<<v13-20-2,2>>^ Tirando Davi a coroa da cabeça do rei deles, achou nela o peso dum talento de ouro, e havia nela pedras preciosas; e foi posta sobre a cabeça de Davi. E ele levou da cidade mui grande despojo.

[[v13-20-3]]

^<<v13-20-3,3>>^ Também fez sair o povo que estava nela e o fez trabalhar com serras, com trilhos de ferro e com machado, e assim fez Davi a todas as cidades dos amonitas. Então voltou Davi, com todo o povo, para Jerusalém.

[[v13-20-4]]

^<<v13-20-4,4>>^ Depois disso levantou-se guerra em Gezer com os filisteus; então Sibecai, o husatita, matou Sipai, dos filhos do gigante; e eles ficaram subjugados.

[[v13-20-5]]

^<<v13-20-5,5>>^ Tornou a haver guerra com os filisteus; e El-Hanã, filho de Jair, matou Lami, irmão de Golias, o giteu, cuja lança tinha a haste como órgão de tecelão,

[[v13-20-6]]

^<<v13-20-6,6>>^ Houve ainda outra guerra em Gate, onde havia um homem de grande estatura, que tinha vinte e quatro dedos, seis em cada mão e seis em cada pé, e que também era filho do gigante.

[[v13-20-7]]

^<<v13-20-7,7>>^ Tendo ele insultado a Israel, Jônatas, filho de Siméia, irmão de Davi, o matou.

[[v13-20-8]]

^<<v13-20-8,8>>^ Esses nasceram ao gigante em Gate; e caíram pela mão de Davi e pela mão dos seus servos.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]