include::./index.adoc[]

[[v13-15-0]]
=== 1 Crônicas, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-15-1]]

^<<v13-15-1,1>>^ Davi fez para si casas na cidade de Davi; também preparou um lugar para a arca de Deus, e armou-lhe uma tenda:

[[v13-15-2]]

^<<v13-15-2,2>>^ Então disse Davi: Ninguém deve levar a arca de Deus, senão os levitas; porque o Senhor os elegeu para levarem a arca de Deus, e para o servirem para sempre.

[[v13-15-3]]

^<<v13-15-3,3>>^ Convocou, pois, Davi todo o Israel a Jerusalém, para fazer subir a arca do Senhor ao seu lugar, que lhe tinha preparado.

[[v13-15-4]]

^<<v13-15-4,4>>^ E reuniu os filhos de Arão e os levitas.

[[v13-15-5]]

^<<v13-15-5,5>>^ dos filhos de Coate, Uriel, o chefe, e de seus irmãos cento e vinte;

[[v13-15-6]]

^<<v13-15-6,6>>^ dos filhos de Merári, Asaías, o chefe, e de seus irmãos duzentos e vinte;

[[v13-15-7]]

^<<v13-15-7,7>>^ dos filhos de Gérson Joel, o chefe, e de seus irmãos cento e trinta;

[[v13-15-8]]

^<<v13-15-8,8>>^ dos filhos de Elizafã, Semaías, o chefe, e de seus irmãos duzentos;

[[v13-15-9]]

^<<v13-15-9,9>>^ dos filhos de Hebrom, Eliel, o chefe, e de seus irmãos oitenta;

[[v13-15-10]]

^<<v13-15-10,10>>^ dos filhos de Uziel, Aminadabe, o chefe, e de seus irmãos cento e doze.

[[v13-15-11]]

^<<v13-15-11,11>>^ Então chamou Davi os sacerdotes Zadoque e Abiatar, e os levitas Uriel, Asaías, Joel, Semaías, Eliel e Aminadabe,

[[v13-15-12]]

^<<v13-15-12,12>>^ e disse-lhes: Vós sois os chefes das casas paternas entre os levitas; santificai-vos, vós e vossos irmãos, para que façais subir a arca do Senhor Deus de Israel ao lugar que lhe preparei.

[[v13-15-13]]

^<<v13-15-13,13>>^ Porquanto da primeira vez vós não a levastes, o Senhor fez uma brecha em nós, porque não o buscamos segundo a ordenança:

[[v13-15-14]]

^<<v13-15-14,14>>^ Santificaram-se, pois, os sacerdotes e os levitas para fazerem subir a arca do Senhor Deus de Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ E os levitas trouxeram a arca de Deus sobre os seus ombros, pelos varais que nela havia, como Moisés tinha ordenado, conforme a palavra do Senhor.

[[v13-15-16]]

^<<v13-15-16,16>>^ E Davi ordenou aos chefes dos levitas que designassem alguns de seus irmãos como cantores, para tocarem com instrumentos musicais, com alaúdes, harpas e címbalos, e levantarem a voz com alegria.

[[v13-15-17]]

^<<v13-15-17,17>>^ Designaram, pois, os levitas a Hemã, filho de Joel; e dos seus irmãos, a Asafe, filho de Berequias; e dos filhos de Merári, seus irmãos, a Etã, filho de Cusaías;

[[v13-15-18]]

^<<v13-15-18,18>>^ e com eles a seus irmãos da segunda ordem: Zacarias, Bene, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Benaías, Maaséias, Matitias, Elifeleu e Micnéias, e Obede-Edom e Jeiel, os porteiros.

[[v13-15-19]]

^<<v13-15-19,19>>^ Assim os cantores Hemã, Asafe e Etã se faziam ouvir com címbalos de bronze;

[[v13-15-20]]

^<<v13-15-20,20>>^ e Zacarias, Aziel, Semiramote, Jeiel, Uni, Eliabe, Maaséias e Benaías, com alaúdes adaptados ao soprano;

[[v13-15-21]]

^<<v13-15-21,21>>^ e Matitias, Elifeleu, Micnéias, Obede-Edom, Jeiel e Azazias, com harpas adaptadas ao baixo, para dirigirem;

[[v13-15-22]]

^<<v13-15-22,22>>^ e Quenanias, chefe dos levitas, estava encarregado dos cânticos e os dirigia, porque era entendido;

[[v13-15-23]]

^<<v13-15-23,23>>^ e Berequias e Elcana eram porteiros da arca;

[[v13-15-24]]

^<<v13-15-24,24>>^ e Sebanias, Jeosafá, Netanel, Amasai, Zacarias, Benaías e Eliézer, os sacerdotes, tocavam as trombetas perante a arca de Deus; e Obede-Edom e Jeías eram porteiros da arca.

[[v13-15-25]]

^<<v13-15-25,25>>^ Sucedeu pois que Davi, os anciãos de Israel, os capitães dos milhares foram, com alegria, para fazer subir a arca do pacto do Senhor, da casa de Obede-Edem.

[[v13-15-26]]

^<<v13-15-26,26>>^ E sucedeu que, havendo Deus ajudado os levitas que levavam a arca do pacto dó Senhor, sacrificaram sete novilhos e sete carneiros.

[[v13-15-27]]

^<<v13-15-27,27>>^ Davi ia vestido de um manto de linho fino, como também todos os levitas que levavam a arca, e os cantores, e juntamente com eles Quenanias, diretor do canto; Davi levava também sobre si um éfode de linho.

[[v13-15-28]]

^<<v13-15-28,28>>^ Assim todo o Israel fez subir a arca do pacto do Senhor com vozes de júbilo, ao som de buzinas, trombetas e címbalos, juntamente com alaúdes e harpas.

[[v13-15-29]]

^<<v13-15-29,29>>^ E sucedeu que, chegando a arca do pacto do Senhor à cidade de Davi, Mical, a filha de Saul, olhou duma janela e, vendo Davi dançar e saltar, desprezou-o no seu coração.

'''

xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[Próximo Capítulo &#62;]