include::./index.adoc[]

[[v13-6-0]]
=== 1 Crônicas, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-6-1]]

^<<v13-6-1,1>>^ Os filhos de Levi: Gérson, Coate e Merári.

[[v13-6-2]]

^<<v13-6-2,2>>^ Os filhos de Coate: Anrão, Izar, Hebrom e Uziel.

[[v13-6-3]]

^<<v13-6-3,3>>^ Os filhos de Anrão: Arão, Moisés e Miriã; e os filhos de Arão: Nadabe, Abiú, Eleazar e Itamar.

[[v13-6-4]]

^<<v13-6-4,4>>^ Eleazar foi pai de Finéias, Finéias de Abisua,

[[v13-6-5]]

^<<v13-6-5,5>>^ Abisua de Buqui, Buqui de Uzi,

[[v13-6-6]]

^<<v13-6-6,6>>^ Uzi de Zeraías, Zeraías de Meraiote,

[[v13-6-7]]

^<<v13-6-7,7>>^ Meraiote de Amarias, Amarias de Aitube,

[[v13-6-8]]

^<<v13-6-8,8>>^ Aitube de Zadoque, Zadoque de Aimaaz,

[[v13-6-9]]

^<<v13-6-9,9>>^ Aimaaz de Azarias, Azarias de Joanã,

[[v13-6-10]]

^<<v13-6-10,10>>^ Joanã de Azarias, que exerceu o sacerdócio na casa que Salomão edificou em Jerusalém;

[[v13-6-11]]

^<<v13-6-11,11>>^ Azarias foi pai de Amarias, Amarias de Aitube,

[[v13-6-12]]

^<<v13-6-12,12>>^ Aitube de Zadoque, Zadoque de Salum,

[[v13-6-13]]

^<<v13-6-13,13>>^ Salum de Hilquias, Hilquias de Azarias,

[[v13-6-14]]

^<<v13-6-14,14>>^ Azarias de Seraías, Seraías de Jeozadaque;

[[v13-6-15]]

^<<v13-6-15,15>>^ e Jeozadaque foi levado cativo quando o Senhor levou em cativeiro Judá e Jerusalém por intermédio de Nabucodonosor.

[[v13-6-16]]

^<<v13-6-16,16>>^ Os filhos de Levi: Gérson, Coate e Merári.

[[v13-6-17]]

^<<v13-6-17,17>>^ Estes são os nomes dos filhos de Gérson: Líbni e Simei.

[[v13-6-18]]

^<<v13-6-18,18>>^ Os filhos de Coate: Anrão, Izar, Hebrom e Uziel.

[[v13-6-19]]

^<<v13-6-19,19>>^ Os filhos de Merári: Mali e Musi. Estas são as famílias dos levitas, segundo as casas de seus pais.

[[v13-6-20]]

^<<v13-6-20,20>>^ De Gérson: Líbni, de quem foi filho Jaate, de quem foi filho Zima,

[[v13-6-21]]

^<<v13-6-21,21>>^ de quem foi filho Joá, de quem foi filho Ido, de quem foi filho Zerá, de quem foi filho Jeaterai:

[[v13-6-22]]

^<<v13-6-22,22>>^ Os filhos de Coate: Aminadabe, de quem foi filho Corá, de quem foi filho Assir,

[[v13-6-23]]

^<<v13-6-23,23>>^ de quem foi filho Elcana, de quem foi filho Ebiasafe, de quem foi filho Assir,

[[v13-6-24]]

^<<v13-6-24,24>>^ de quem foi filho Taate, de quem foi filho Uriel, de quem foi filho Uzias, de quem foi filho Saul.

[[v13-6-25]]

^<<v13-6-25,25>>^ Os filhos de Elcana: Amasai e Aimote,

[[v13-6-26]]

^<<v13-6-26,26>>^ de quem foi filho Elcana, de quem foi filho Zofai, de quem foi filho Naate,

[[v13-6-27]]

^<<v13-6-27,27>>^ de quem foi filho Eliabe, de quem foi filho Jeroão, de quem foi filho Elcana.

[[v13-6-28]]

^<<v13-6-28,28>>^ E os filhos de Samuel: Joel, seu primogênito, e Abias, o segundo.

[[v13-6-29]]

^<<v13-6-29,29>>^ Os filhos de Merári: Mali, de quem foi filho Líbni, de quem foi filho Simei, de quem foi filho Uzá,

[[v13-6-30]]

^<<v13-6-30,30>>^ de quem foi filho Siméia, de quem foi filho Hagias, de quem foi filho Asaías.

[[v13-6-31]]

^<<v13-6-31,31>>^ Estes são os que Davi constituiu sobre o serviço de canto da casa do Senhor, depois: que a arca teve repouso.

[[v13-6-32]]

^<<v13-6-32,32>>^ Ministravam com cântico diante do tabernáculo da tenda da revelação, até que Salomão edificou a casa do Senhor em Jerusalém; e exerciam o seu ministério segundo a sua ordem.

[[v13-6-33]]

^<<v13-6-33,33>>^ São estes: pois, os que ali estavam com seus filhos: dos filhos dos coatitas, Hemã, o cantor, filho de Joel, filho de Samuel,

[[v13-6-34]]

^<<v13-6-34,34>>^ filho de Elcana, filho de Jeroão, filho de Eliel, filho de Toá,

[[v13-6-35]]

^<<v13-6-35,35>>^ filho de Zufe, filho de Elcana:, filho de Maate, filho de Amasai,

[[v13-6-36]]

^<<v13-6-36,36>>^ filho de Elcana, filho de Joel, filho de Azarias, filho de Sofonias,

[[v13-6-37]]

^<<v13-6-37,37>>^ filho de Taate, filho de Assir, filho de Ebiasafe, filho de Corá,

[[v13-6-38]]

^<<v13-6-38,38>>^ filho de Izar, filho de Coate, filho de Levi, filho de Israel.

[[v13-6-39]]

^<<v13-6-39,39>>^ E seu irmão Asafe estava à sua direita; e era Asafe filho de Berequias, filho de Siméia,

[[v13-6-40]]

^<<v13-6-40,40>>^ filho de Micael, filho de Baaséias, filho de Malquias,

[[v13-6-41]]

^<<v13-6-41,41>>^ filho de Etni, filho de Zerá, filho de Adaías,

[[v13-6-42]]

^<<v13-6-42,42>>^ filho de Etã, filho de Zima, filho de Simei,

[[v13-6-43]]

^<<v13-6-43,43>>^ filho de Jaate, filho de Gérson, filho de Levi.

[[v13-6-44]]

^<<v13-6-44,44>>^ E à esquerda estavam seus irmãos, os filhos de Merári: Etã, filho de Quísi, filho de Abdi, filho de Maluque,

[[v13-6-45]]

^<<v13-6-45,45>>^ filho de Hasabias, filho de Amazias, filho de Hilquias,

[[v13-6-46]]

^<<v13-6-46,46>>^ filho de Anzi, filho de Bani, filho de Semer,

[[v13-6-47]]

^<<v13-6-47,47>>^ filho de Mali, filho de Musi, filho de Merári, filho de Levi.

[[v13-6-48]]

^<<v13-6-48,48>>^ Mas Arão e seus irmãos, os levitas, foram designados para todo o serviço do tabernáculo da casa de Deus.

[[v13-6-49]]

^<<v13-6-49,49>>^ Mas Arão e seus filhos ofereciam os sacrifícios sobre o altar do holocausto e o incenso sobre o altar do incenso, para todo o serviço do lugar santíssimo, e para fazer expiação a favor de Israel, conforme tudo quanto Moisés, servo de Deus, havia ordenado:

[[v13-6-50]]

^<<v13-6-50,50>>^ Estes foram os filhos de Arão: Eleazar, de quem foi filho Finéias, de quem foi filho Abisua,

[[v13-6-51]]

^<<v13-6-51,51>>^ de quem foi filho Buqui, de quem foi filho Uzi, de quem foi filho Zeraías,

[[v13-6-52]]

^<<v13-6-52,52>>^ de quem foi filho Meraiote, de quem foi filho Amarias, de quem foi filho Aitube,

[[v13-6-53]]

^<<v13-6-53,53>>^ de quem foi filho Zadoque, de quem foi filho Aimaaz.

[[v13-6-54]]

^<<v13-6-54,54>>^ Ora, estas foram as suas habitações, segundo os seus acampamentos nos seus termos, a saber: aos filhos de Arão, das famílias dos coatitas &#123;porque lhes caiu a primeira sorte&#125;,

[[v13-6-55]]

^<<v13-6-55,55>>^ deram-lhes Hebrom, na terra de Judá, e os campos que a rodeiam;

[[v13-6-56]]

^<<v13-6-56,56>>^ porém os campos da cidade e as suas aldeias, deram-nos a Calebe, filho de Jefone.

[[v13-6-57]]

^<<v13-6-57,57>>^ E aos filhos de Arão deram as cidades de refúgio: Hebrom, Libna e seus campos, Jatir, Estemoa e seus campos,

[[v13-6-58]]

^<<v13-6-58,58>>^ Hilem e seus campos, Debir e seus campos,

[[v13-6-59]]

^<<v13-6-59,59>>^ Asã e seus campos, Bete-Senues e seus campos;

[[v13-6-60]]

^<<v13-6-60,60>>^ e da tribo de Benjamim: Geba e seus campos, Alemete e seus campos, Anatote e seus campos; todas as suas cidades, pelas suas famílias, foram treze.

[[v13-6-61]]

^<<v13-6-61,61>>^ Mas aos filhos de Coate, aos restantes da família da tribo, por sorte caíram dez cidades da meia tribo, da metade de Manassés;

[[v13-6-62]]

^<<v13-6-62,62>>^ aos filhos de Gérsom segundo as suas famílias, cairam treze cidades das tribos de Issacar, Aser, Naftali e Manassés, em Basã;

[[v13-6-63]]

^<<v13-6-63,63>>^ e aos filhos de Merári, segundo as suas famílias, por sorte caíram doze cidades das tribos de Rúben Gade e Zebulom.

[[v13-6-64]]

^<<v13-6-64,64>>^ Assim os filhos de Israel deram aos levitas estas cidades e seus campos.

[[v13-6-65]]

^<<v13-6-65,65>>^ Deram-lhes por sorte, da tribo dos filhos de Judá, da tribo dos filhos de Simeão, e da tribo dos filhos de Benjamim, estas cidades que são mencionadas nominalmente.

[[v13-6-66]]

^<<v13-6-66,66>>^ Algumas das famílias dos filhos de Coate receberam da tribo de Efraim cidades de seus termos.

[[v13-6-67]]

^<<v13-6-67,67>>^ Deram-lhes as cidades de refúgio: Siquém e seus campos, na região montanhosa de Efraim, como também Gezer e seus campos.

[[v13-6-68]]

^<<v13-6-68,68>>^ Jocmeão e seus campos, Bete-Horom e seus campos,

[[v13-6-69]]

^<<v13-6-69,69>>^ Aijalom e seus campos, e Gate-Rimom e seus campos;

[[v13-6-70]]

^<<v13-6-70,70>>^ e da meia tribo de Manassés, Aner e seus campos, e Bileã e seus campos, deram-nos aos restantes da família dos filhos de Coate.

[[v13-6-71]]

^<<v13-6-71,71>>^ Aos filhos de Gérson deram, da família da meia tribo de Manassés, Golã, em Basã, e seus campos, e Astarote e seus campos;

[[v13-6-72]]

^<<v13-6-72,72>>^ e da tribo de Issacar: Quedes e seus campos, Daberate e seus campos,

[[v13-6-73]]

^<<v13-6-73,73>>^ Ramote e seus campos, e Aném e seus campos;

[[v13-6-74]]

^<<v13-6-74,74>>^ e da tribo de Aser: Masal e seus campos, Abdom e seus campos,

[[v13-6-75]]

^<<v13-6-75,75>>^ Hucoque e seus campos, e Reobe e seus campos;

[[v13-6-76]]

^<<v13-6-76,76>>^ e da tribo de Naftali: Quedes, em Galiléia, e seus campos, Hamom e seus campos, e Quiriataim e seus campos.

[[v13-6-77]]

^<<v13-6-77,77>>^ Aos restantes dos filhos de Merári deram, da tribo de Zebulom, Rimono e seus campos, Tabor e seus campos;

[[v13-6-78]]

^<<v13-6-78,78>>^ e dalém do Jordão, na altura de Jericó, ao oriente do Jordão, deram, da tribo de Rúben Bezer, no deserto, e seus campos, Jaza e seus campos,

[[v13-6-79]]

^<<v13-6-79,79>>^ Quedemote e seus campos, e Mefaate e seus campos;

[[v13-6-80]]

^<<v13-6-80,80>>^ e da tribo de Gade, Ramote, em Gileade, e seus campos, Maanaim e seus campos.

[[v13-6-81]]

^<<v13-6-81,81>>^ Hesbom e seus campos, e Jazer e seus campos.

'''

xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[&#60; Capítulo Anterior] | <<v13-6-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-007.adoc#v13-7-0[Próximo Capítulo &#62;]