include::./index.adoc[]

[[v13-18-0]]
=== 1 Crônicas, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-18-1]]

^<<v13-18-1,1>>^ Depois disto Davi derrotou os filisteus, e os subjugou e tomou das mãos deles Gate e as suas aldeias.

[[v13-18-2]]

^<<v13-18-2,2>>^ Também derrotou os moabitas, e estes lhe ficaram sujeitos, pagando-lhe tributos.

[[v13-18-3]]

^<<v13-18-3,3>>^ Davi derrotou também Hadadézer, rei de Zobá, junto a Hamate, quando foi estabelecer o seu domínio junto ao rio Eufrates.

[[v13-18-4]]

^<<v13-18-4,4>>^ E Davi lhe tomou mil carros, sete mil cavaleiros e vinte mil homens de infantaria; e jarretou todos os cavalos dos carros; porém reservou deles para cem carros.

[[v13-18-5]]

^<<v13-18-5,5>>^ E quando os sírios de Damasco vieram para ajudar a Hadadézer, rei de Zobá, Davi matou deles vinte e dois mil homens.

[[v13-18-6]]

^<<v13-18-6,6>>^ Então Davi pôs guarnições entre os sírios de Damasco, e os sírios lhe ficaram sujeitos, pagando-lhe tributos; e o Senhor dava vitória a Davi, por onde quer que ia.

[[v13-18-7]]

^<<v13-18-7,7>>^ Davi tomou os escudos de ouro que tinham sido dos servos de Hadadézer, e os trouxe a Jerusalém.

[[v13-18-8]]

^<<v13-18-8,8>>^ Também de Tibate, e de Cum, cidades de Hadadézer, Davi tomou muitíssimo bronze, de que Salomão fez o mar de bronze, as colunas, e os utensílios de bronze.

[[v13-18-9]]

^<<v13-18-9,9>>^ Ora, quando Toú, rei de Hamate, ouviu que Davi destruíra todo o exército de Hadadézer, rei de Zobá,

[[v13-18-10]]

^<<v13-18-10,10>>^ mandou seu filho Hadorão ao rei Davi, para o saudar, e para o felicitar por haver pelejado contra Hadadézer e por tê-lo destruído &#123;porque Hadadézer fazia guerra a Toú&#125;. Enviou-lhe também toda sorte de utensílios de ouro, de prata e de bronze. l

[[v13-18-11]]

^<<v13-18-11,11>>^ A estes também o rei Davi consagrou ao Senhor, juntamente com a prata e o ouro que trouxera de todas as nações dos edomeus, dos moabitas, dos amonitas, dos filisteus e dos amalequitas.

[[v13-18-12]]

^<<v13-18-12,12>>^ Além disso Abisai, filho de Zeruia, matou dezoito mil edomeus no Vale do Sal.

[[v13-18-13]]

^<<v13-18-13,13>>^ E pôs guarnições em Edom, e todos os edomeus ficaram sujeitos a Davi; e o Senhor dava vitória a Davi, por onde quer que ia.

[[v13-18-14]]

^<<v13-18-14,14>>^ Dari, pois, reinou sobre todo o Israel; e julgava, e fazia justiça a todo o seu povo.

[[v13-18-15]]

^<<v13-18-15,15>>^ Joabe, filho de Zeruia, tinha o cargo do exército; Jeosafá, filho de Ailude, era cronista;

[[v13-18-16]]

^<<v13-18-16,16>>^ Zadoque, filho de Aiuube, e Abimeleque, filho de Abiatar, eram sacerdotes; Sarsa era escrivão;

[[v13-18-17]]

^<<v13-18-17,17>>^ Benaías, filho de Jeoiada, tinha o cargo dos quereteus e peleteus; e os filhos de Davi eram os primeiros junto ao rei.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]