include::./index.adoc[]

[[v13-14-0]]
=== 1 Crônicas, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-14-1]]

^<<v13-14-1,1>>^ Hirão, rei de Tiro, mandou mensageiros a Davi, e madeira de cedro, pedreiros e carpinteiros para lhe edificarem uma casa.

[[v13-14-2]]

^<<v13-14-2,2>>^ Então percebeu Davi que o Senhor o tinha confirmado rei sobre Israel; porque o seu reino tinha sido muito exaltado por amor do seu povo Israel.

[[v13-14-3]]

^<<v13-14-3,3>>^ Davi tomou em Jerusalém ainda outras mulheres, e teve ainda filhos e filhas.

[[v13-14-4]]

^<<v13-14-4,4>>^ Estes, pois, são os nomes dos filhos que lhe nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v13-14-5]]

^<<v13-14-5,5>>^ Ibar, Elisua, Elpelete,

[[v13-14-6]]

^<<v13-14-6,6>>^ Nogá, Nefegue, Jafia,

[[v13-14-7]]

^<<v13-14-7,7>>^ Elisama, Beeliada e Elifelete.

[[v13-14-8]]

^<<v13-14-8,8>>^ Quando os filisteus ouviram que Davi havia sido ungido rei sobre todo o Israel, subiram todos em busca dele; o que ouvindo Davi, logo saiu contra eles.

[[v13-14-9]]

^<<v13-14-9,9>>^ Ora, os filisteus tinham vindo e feito uma arremetida pelo vale de Refaim.

[[v13-14-10]]

^<<v13-14-10,10>>^ Então Davi consultou a Deus, dizendo: Subirei contra os filisteus, e nas minhas mãos os entregarás?: E o Senhor lhe disse: Sobe, porque os entregarei nas tuas mãos.

[[v13-14-11]]

^<<v13-14-11,11>>^ E subiram os filisteus a Baal-Perazim, onde Davi os derrotou; e disse Davi: por minha mão Deus fez uma brecha nos meus inimigos, como uma brecha feita pelas águas. Pelo que chamaram aquele lugar Baal-Perazim:

[[v13-14-12]]

^<<v13-14-12,12>>^ E deixaram ali os seus deuses, que, por ordem de Davi, foram queimados a fogo.

[[v13-14-13]]

^<<v13-14-13,13>>^ Mas os filisteus tornaram a fazer uma arremetida pelo vale.

[[v13-14-14]]

^<<v13-14-14,14>>^ Tornou Davi a consultar a Deus, que lhe respondeu: Não subirás atrás deles; mas rodeia-os por detrás e vem sobre eles por defronte dos balsameiros;

[[v13-14-15]]

^<<v13-14-15,15>>^ e será que, ouvindo tu um ruído de marcha pelas copas dos balsameiros, sairás à peleja; porque Deus terá saído diante de ti para ferir o exército dos filisteus.

[[v13-14-16]]

^<<v13-14-16,16>>^ E fez Davi como Deus lhe ordenara; e desbarataram o exército dos filisteus desde Gibeão até Gezer:

[[v13-14-17]]

^<<v13-14-17,17>>^ Assim a fama de Davi se espalhou por todas aquelas terras, e o Senhor pôs o temor dele sobre todas aquelas gentes.

'''

xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[Próximo Capítulo &#62;]