include::./index.adoc[]

[[v13-25-0]]
=== 1 Crônicas, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-25-1]]

^<<v13-25-1,1>>^ Também Davi juntamente com os capitães do exército, separou para o serviço alguns dos filhos de Asafe, e de Hemã, e de Jedútum para profetizarem com harpas, com alaúdes, e com címbalos. Este foi o número dos homens que fizeram a obra: segundo o seu serviço:

[[v13-25-2]]

^<<v13-25-2,2>>^ dos filhos de Asafe: Zacur, José, Netanias e Asarela, filhos de Asafe, a cargo de Asafe, que profetizava sob as ordens do rei.

[[v13-25-3]]

^<<v13-25-3,3>>^ De Jedútum os filhos de Jedútun: Gedalias, e Zeri, Jesaías, Hasabias e Matitias, seis, a cargo de seu pai, Jedútum que profetizava com a harpa, louvando ao Senhor e dando-lhe graças.

[[v13-25-4]]

^<<v13-25-4,4>>^ De Hemã, os filhos de Hemã: Buquias, Matanias, Uziel, Sebuel, Jerimote, Hananias, Hanâni, Eliatá, Gidálti, e Românti-Ezer, Josbecasa, Malóti, Hotir e Maaziote.

[[v13-25-5]]

^<<v13-25-5,5>>^ Todos estes foram filhos de Hemã, o vidente do rei, segundo a promessa de Deus de exaltá-lo. Deus dera a Hemã catorze filhos e três filhas.

[[v13-25-6]]

^<<v13-25-6,6>>^ Todos estes estavam sob a direção de seu pai para a música na casa do Senhor, com címbalos, alaúdes e harpas para o serviço da casa de Deus. E Asafe, Jedútun e Hemã estavam sob as ordens do rei.

[[v13-25-7]]

^<<v13-25-7,7>>^ Era o número deles, juntamente com seus irmãos instruídos em cantar ao Senhor, todos eles mestres, duzentos e oitenta e oito.

[[v13-25-8]]

^<<v13-25-8,8>>^ E determinaram os seus cargos por sortes, todos igualmente, tanto o pequeno como o grande, assim o mestre como o discípulo.

[[v13-25-9]]

^<<v13-25-9,9>>^ A primeira sorte, que era de Asafe, saiu a José; a segunda a Gedalias, que com seus irmãos e filhos eram doze;

[[v13-25-10]]

^<<v13-25-10,10>>^ a terceira a Zacur, seus filhos e irmãos, doze;

[[v13-25-11]]

^<<v13-25-11,11>>^ a quarta a Izri, seus filhos e irmãos, doze;

[[v13-25-12]]

^<<v13-25-12,12>>^ a quinta a Netanias, seus filhos e irmãos, doze;

[[v13-25-13]]

^<<v13-25-13,13>>^ a sexta a Buquias, seus filhos e irmãos, doze;

[[v13-25-14]]

^<<v13-25-14,14>>^ a sétima a Jesarela, seus filhos e irmãos, doze;

[[v13-25-15]]

^<<v13-25-15,15>>^ a oitava a Jesaías, seus filhos e irmãos, doze;

[[v13-25-16]]

^<<v13-25-16,16>>^ a nona a Matanias, seus filhos e irmãos, doze;

[[v13-25-17]]

^<<v13-25-17,17>>^ a décima a Simei, seus filhos e irmãos, doze;

[[v13-25-18]]

^<<v13-25-18,18>>^ a undécima a Azarel, seus filhos e irmãos, doze;

[[v13-25-19]]

^<<v13-25-19,19>>^ a duodécima a Hasabias, seus filhos e irmãos, doze;

[[v13-25-20]]

^<<v13-25-20,20>>^ a décima terceira a Subael, seus filhos: e irmãos, doze;

[[v13-25-21]]

^<<v13-25-21,21>>^ a décima quarta a Matitias, seus filhos e irmãos, doze;

[[v13-25-22]]

^<<v13-25-22,22>>^ a décima quinta a Jerimote, seus filhos e irmãos, doze;

[[v13-25-23]]

^<<v13-25-23,23>>^ a décima sexta a Hananias, seus filhos e irmãos, doze;

[[v13-25-24]]

^<<v13-25-24,24>>^ a décima sétima a Josbecasa, seus filhos e irmãos, doze;

[[v13-25-25]]

^<<v13-25-25,25>>^ a décima oitava a Hanâni, seus filhos e irmãos, doze;

[[v13-25-26]]

^<<v13-25-26,26>>^ a décima nona a Malóti, seus filhos e irmãos, doze;

[[v13-25-27]]

^<<v13-25-27,27>>^ a vigésima a Eliatá, seus filhos e irmãos, doze;

[[v13-25-28]]

^<<v13-25-28,28>>^ a vigésima primeira a Hotir, seus filhos e irmãos, doze;

[[v13-25-29]]

^<<v13-25-29,29>>^ a vigésima segunda a Gidálti, seus filhos e irmãos, doze;

[[v13-25-30]]

^<<v13-25-30,30>>^ a vigésima terceira a Maaziote, seus filhos e irmãos, doze;

[[v13-25-31]]

^<<v13-25-31,31>>^ a vigésima quarta a Românti-Ezer, seus filhos e irmãos, doze.

'''

xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[&#60; Capítulo Anterior] | <<v13-25-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[Próximo Capítulo &#62;]