include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-19-1]]

^<<v13-19-1,1>>^ Aconteceu, depois disto, que Naás, rei dos amonitas, morreu; e seu filho reinou em seu lugar.

[[v13-19-2]]

^<<v13-19-2,2>>^ Então disse Davi: usarei de benevolência para com Hanum, filho de Naás, porque seu pai usou de benevolência para comigo. Pelo que Davi enviou mensageiros para o consolarem acerca de seu pai. Mas quando os servos de Davi chegaram à terra dos amonitas, a Hanum, para o consolarem,

[[v13-19-3]]

^<<v13-19-3,3>>^ disseram os príncipes dos amonitas a Hanum: Pensas que Davi quer honrar a teu pai, porque te mandou consoladores? Não vieram ter contigo os seus servos a esquadrinhar, a transtornar e a espiar a terra?

[[v13-19-4]]

^<<v13-19-4,4>>^ Pelo que Hanum tomou os servos de Davi, raspou-lhes a barba, e lhes cortou as vestes pelo meio até o alto das coxas, e os despediu.

[[v13-19-5]]

^<<v13-19-5,5>>^ Então foram alguns e avisaram a Davi acerca desses homens; pelo que ele mandou mensageiros ao seu encontro, pois estavam sobremaneira envergonhados. Disse o rei: Ficai em Jericó até que vos torne a crescer a barba, e então voltai.

[[v13-19-6]]

^<<v13-19-6,6>>^ Vendo os amonitas que se tinham feito odiosos para com Davi, Hanum e os amonitas enviaram mil talentos de prata, para alugarem para si carros e cavaleiros de Mesopotâmia, de Arã-Maacá e de Zobá.

[[v13-19-7]]

^<<v13-19-7,7>>^ E alugaram para si trinta e dois mil carros e o rei de Maacá com a sua gente, os quais vieram e se acamparam diante de Medeba; também os amonitas se ajuntaram das suas cidades e vieram para a guerra.

[[v13-19-8]]

^<<v13-19-8,8>>^ Davi, quando soube disto, enviou Joabe e todo o exército de homens valentes.

[[v13-19-9]]

^<<v13-19-9,9>>^ Os amonitas saíram e ordenaram a batalha à porta da cidade; porém os reis que tinham vindo se puseram à parte no campo.

[[v13-19-10]]

^<<v13-19-10,10>>^ Ora, quando Joabe viu que a batalha estava ordenada contra ele pela frente e pela retaguarda, escolheu os melhores dentre os homens de Israel, e os pôs em ordem contra os sírios;

[[v13-19-11]]

^<<v13-19-11,11>>^ e o resto do povo entregou na mão de Abisai, seu irmão; e eles se puseram em ordem de batalha contra os amonitas.

[[v13-19-12]]

^<<v13-19-12,12>>^ E disse Joabe: Se os sírios forem mais fortes do que eu, tu virás socorrer-me; e, se os amonitas forem mais fortes do que tu, então eu te socorrerei a ti.

[[v13-19-13]]

^<<v13-19-13,13>>^ Esforça-te, e pelejemos varonilmente pelo nosso povo e pelas cidades do nosso Deus; e faça o Senhor o que bem lhe parecer.

[[v13-19-14]]

^<<v13-19-14,14>>^ Então se chegou Joabe, e o povo que estava com ele, diante dos sírios, para a batalha; e estes fugiram de diante dele.

[[v13-19-15]]

^<<v13-19-15,15>>^ Vendo, pois, os amonitas que os sírios tinham fugido, fugiram eles também de diante de Abisai, irmão de Joabe, e entraram na cidade. Então Joabe voltou para Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ Ora, vendo-se os sírios derrotados diante de Israel, enviaram mensageiros, e fizeram sair os sírios que habitavam além do rio; e tinham por comandante Sofaque, chefe do exército de Hadadézer.

[[v13-19-17]]

^<<v13-19-17,17>>^ Avisado disto, Davi ajuntou todo o Israel, passou o Jordão e, indo ao encontro deles, ordenou contra eles a batalha. Tendo Davi ordenado a batalha contra os sírios, pelejaram estes contra ele.

[[v13-19-18]]

^<<v13-19-18,18>>^ Mas os sírios fugiram de diante de Israel; e Davi matou deles os homens de sete mil carros, e quarenta mil homens da infantaria; matou também Sofaque, chefe do exército.

[[v13-19-19]]

^<<v13-19-19,19>>^ Vendo, pois, os servos de Hadadézer que tinham sido derrotados diante de Israel, fizeram paz cem Davi, e serviram; e os sírios nunca mais quiseram socorrer os amonitas.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]