include::./index.adoc[]

[[v13-11-0]]
=== 1 Crônicas, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-11-1]]

^<<v13-11-1,1>>^ Então todo o Israel se ajuntou a Davi em Hebron, dizendo: Eis que somos teus ossos e tua carne.

[[v13-11-2]]

^<<v13-11-2,2>>^ Já dantes, quando Saul ainda era rei, eras tu o que fazias Israel sair, e entrar; também o Senhor teu Deus te disse: Tu apascentaras o meu povo Israel; tu serás príncipe sobre o meu povo Israel.

[[v13-11-3]]

^<<v13-11-3,3>>^ Assim vieram todos os anciãos de Israel ao rei, a Hebrom; e Davi fez com eles um pacto em Hebrom, perante o Senhor; e ungiram a Davi rei sobre Israel, conforme a palavra do Senhor por intermédio de Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ Então Davi, com todo o Israel, partiu para Jerusalém , que é Jebus; e estavam ali os jebuseus, habitantes da terra.

[[v13-11-5]]

^<<v13-11-5,5>>^ E disseram os habitantes de Jebus a Davi: Tu não entrarás aqui. Não obstante isso, Davi tomou a fortaleza de Sião, que é a cidade de Davi.

[[v13-11-6]]

^<<v13-11-6,6>>^ Davi disse: Qualquer que primeiro ferir os jebuseus será chefe e capitão. E Joabe, filho de Zeruia, subiu primeiro, pelo que foi feito chefe.

[[v13-11-7]]

^<<v13-11-7,7>>^ Então Davi habitou na fortaleza, e por isso foi chamada cidade de Davi.

[[v13-11-8]]

^<<v13-11-8,8>>^ E edificou a cidade ao redor, desde Milo em diante; e Joabe reparou o resto da cidade.

[[v13-11-9]]

^<<v13-11-9,9>>^ Davi tornava-se cada vez mais forte; porque o Senhor dos exércitos era com ele.

[[v13-11-10]]

^<<v13-11-10,10>>^ São estes os chefes dos valentes de Davi, que o apoiaram fortemente no seu reino, com todo o Israel, para o fazerem rei, conforme a palavra do Senhor, no tocante a Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ Esta é a relação dos valentes de Davi: Jasobeão, filho dum hacmonita, o chefe dos trinta, o qual, brandindo a sua lança contra trezentos, duma só vez os matou.

[[v13-11-12]]

^<<v13-11-12,12>>^ Depois dele, Eleazar, filho de Dodó, o aoíta; ele estava entre os três valentes.

[[v13-11-13]]

^<<v13-11-13,13>>^ Este esteve com Davi em Pas-Damim, quando os filisteus ali se ajuntaram à peleja, onde havia um pedaço de campo cheio de cevada; e o povo fugia de diante dos filisteus.

[[v13-11-14]]

^<<v13-11-14,14>>^ Mas eles se puseram no meio daquele campo, e o defenderam, e mataram os filisteus; e o Senhor os salvou com uma grande vitória.

[[v13-11-15]]

^<<v13-11-15,15>>^ Três dos trinta chefes desceram à penha; a ter com Davi, na caverna de Adulão; e o exército dos filisteus estará acampado no vale de Refaim.

[[v13-11-16]]

^<<v13-11-16,16>>^ Davi estava então no lugar forte, e a guarnição dos filisteus estava em Belém.

[[v13-11-17]]

^<<v13-11-17,17>>^ E Davi, ofegante, exclamou: Quem me dera beber da água do poço de Belém, que está junto à porta!

[[v13-11-18]]

^<<v13-11-18,18>>^ Então aqueles três romperam pelo arraial dos filisteus, tiraram água do poço de Belém, que estava junto à porta, e a trouxeram a Davi; porém Davi não a quis beber, mas a derramou perante o Senhor,

[[v13-11-19]]

^<<v13-11-19,19>>^ dizendo: Não permita meu Deus que eu faça isso! Beberia eu o sangue da vida destes homens? Pois com perigo das suas vidas a trouxeram. Assim, não a quis beber. Isso fizeram aqueles três valentes.

[[v13-11-20]]

^<<v13-11-20,20>>^ Abisai, irmão de Joabe, era o chefe dos três; o qual, brandindo a sua lança contra trezentos, os matou, e teve nome entre os três.

[[v13-11-21]]

^<<v13-11-21,21>>^ Ele foi mais ilustre do que os outros dois, pelo que foi feito chefe deles; todavia não igualou aos primeiros três.

[[v13-11-22]]

^<<v13-11-22,22>>^ Havia também Benaías, filho de Jeoiada, filho de um homem valente de Cabzeel, autor de grandes feitos; este matou dois filhos de Ariel de Moabe; depois desceu e matou um leão dentro duma cova, no tempo da neve.

[[v13-11-23]]

^<<v13-11-23,23>>^ Matou também um egípcio, homem de grande altura, de cinco côvados. O egípcio tinha na mão uma lança como o órgão de tecelão; mas Benaías desceu contra ele com um cajado, arrancou-lhe da mão a lança e com ela o matou.

[[v13-11-24]]

^<<v13-11-24,24>>^ Estas coisas fez Benaías, filho de Jeoiada, pelo que teve nome entre os três valentes.

[[v13-11-25]]

^<<v13-11-25,25>>^ e o mais ilustre, contudo não igualou aos primeiros três; e Davi o pôs sobre os da sua guarda.

[[v13-11-26]]

^<<v13-11-26,26>>^ Os valentes dos exércitos: Asael, irmão de Joabe; El-Hanã, filho de Dodó, de Belém;

[[v13-11-27]]

^<<v13-11-27,27>>^ Samote, o harorita; Helez, o pelonita;

[[v13-11-28]]

^<<v13-11-28,28>>^ Ira, filho de Iques, o tecoíta; Abiezer, o anatotita;

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibecai, o husatita; Ilai, o aoíta;

[[v13-11-30]]

^<<v13-11-30,30>>^ Maarai, o netofatita; Helede, filho de Baaná, o netofatita;

[[v13-11-31]]

^<<v13-11-31,31>>^ Itai, filho de Ribai, de Gibeá, dos filhos de Benjamim; Benaías, o piratonita;

[[v13-11-32]]

^<<v13-11-32,32>>^ Hurai, dos ribeiros de Gaás; Abiel, o arbatita;

[[v13-11-33]]

^<<v13-11-33,33>>^ Azmavete, o baarumita; Eliabá, o saalbonita;

[[v13-11-34]]

^<<v13-11-34,34>>^ dos filhos de Hasem, o gizonita: Jônatas, filho de Sage, o hararita;

[[v13-11-35]]

^<<v13-11-35,35>>^ Aião, filho de Sacar, o hararita; Elifal, filho de Ur.

[[v13-11-36]]

^<<v13-11-36,36>>^ Hefer, o mequeratita; Aías, o pelonita;

[[v13-11-37]]

^<<v13-11-37,37>>^ Hezro, o carmelita; , Naarai, filho de Ebzai;

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel, irmão de Natã; Mibar, filho de Harri;

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeleque, o amonita; Naarai, o berotita, escudeiro de Joabe, filho de Zeniia;

[[v13-11-40]]

^<<v13-11-40,40>>^ Ira, o itrita; Garebe, o itrita;

[[v13-11-41]]

^<<v13-11-41,41>>^ Urias, o heteu; Zabade, filho de Alai;

[[v13-11-42]]

^<<v13-11-42,42>>^ Adina, filho de Siza, o rubenita, chefe dos rubenitas, e com ele trinta;

[[v13-11-43]]

^<<v13-11-43,43>>^ Hanã, filho de Maacá; Jeosafá, o mitnita;

[[v13-11-44]]

^<<v13-11-44,44>>^ Uzias, o asteratita; Sama e Jeiel, filhos de Hotão, o aroerita;

[[v13-11-45]]

^<<v13-11-45,45>>^ Jediael, filho de Sínri, e Joá, seu irmão, o tizita;

[[v13-11-46]]

^<<v13-11-46,46>>^ Eliel, o maavita; Jeribai e Josavias, filhos de Elnaão; Itma, o moabita;

[[v13-11-47]]

^<<v13-11-47,47>>^ Eliel, Obede e Jaasiel, o mezobaíta

'''

xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[Próximo Capítulo &#62;]