include::./index.adoc[]

[[v13-4-0]]
=== 1 Crônicas, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-4-1]]

^<<v13-4-1,1>>^ Os filhos de Judá: Pérez, Hezrom, Carmi, Hur e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ Reaías, filho de Sobal, foi pai de Jaate, e Jaate de Aümai e Laade; estas são as famílias dos zoratitas.

[[v13-4-3]]

^<<v13-4-3,3>>^ Estes foram os filhos de Etã: Jizreel, Ismá, e Idbás; e o nome da irmã deles era Hazelelponi;

[[v13-4-4]]

^<<v13-4-4,4>>^ e mais Penuel, pai de Gedor, e Ézer, pai de Husá; estes foram os filhos de Hur, o primogênito de Efrata, pai de Belém.

[[v13-4-5]]

^<<v13-4-5,5>>^ Asur, pai de Tecoa, tinha duas mulheres: Helá e Naará.

[[v13-4-6]]

^<<v13-4-6,6>>^ Naará deu-lhe à luz Aüzão, Hefer, Temêni e Haastári; estes foram os filhos de Naará.

[[v13-4-7]]

^<<v13-4-7,7>>^ E os filhos de Helá: Zerete, Izar e Etnã.

[[v13-4-8]]

^<<v13-4-8,8>>^ Coz foi pai de Anube e Zobeba, e das famílias de Acarel, filho de Harum.

[[v13-4-9]]

^<<v13-4-9,9>>^ Jabes foi mais ilustre do que seus irmãos &#123;sua mãe lhe pusera o nome de Jabes, dizendo: Porquanto com dores o dei à luz&#125;..

[[v13-4-10]]

^<<v13-4-10,10>>^ Jabes invocou o Deus de Israel, dizendo: Oxalá que me abençoes, e estendas os meus termos; que a tua mão seja comigo e faças que do mal eu não seja afligido! E Deus lhe concedeu o que lhe pedira.

[[v13-4-11]]

^<<v13-4-11,11>>^ Quelube, irmão de Suá, foi pai de Meir; e este foi pai de Estom.

[[v13-4-12]]

^<<v13-4-12,12>>^ Estom foi pai de Bete-Rafa, Paséia e Teína, que foi pai de Ir-Naás; estes foram os homens, de Reca.

[[v13-4-13]]

^<<v13-4-13,13>>^ Os filhos de Quenaz: Otniel e Seraías; e Otniel foi pai de Hatate

[[v13-4-14]]

^<<v13-4-14,14>>^ e Meonotai, que foi pai de Ofra; Seraías foi pai de Joabe, fundador de Ge-Harasim, cujos habitantes foram artífices.

[[v13-4-15]]

^<<v13-4-15,15>>^ Os filhos de Calebe, filho de Jefoné: Íru, Elá e Naã; e Elá foi pai de Quenaz:

[[v13-4-16]]

^<<v13-4-16,16>>^ Os filhos de Jealelel: Zife, Zifá, Tíria e Asareel.

[[v13-4-17]]

^<<v13-4-17,17>>^ Os filhos de Ezra: Jeter, Merede, Efer e Jalom; e ela deu à luz Miriã, Samai, e Isbá, pai de Estemoa,

[[v13-4-18]]

^<<v13-4-18,18>>^ cuja mulher judia deu à luz Jerede, pai de Gedor, Heber, pai de Socó, e Jecutiel, pai de Zanoa; e estes foram os filhos de Bitia, filha de Faraó, que Merede tomou.

[[v13-4-19]]

^<<v13-4-19,19>>^ Os filhos da mulher de Hodias, irmã de Naã, foram os pais de Queila, o garmita, e Estemoa, o maacatita.

[[v13-4-20]]

^<<v13-4-20,20>>^ Os filhos de Simão: Amnom, Rina, Bene-Hanã e Tilom; e os filhos de Isi: Zoete e Bene-Zoete.

[[v13-4-21]]

^<<v13-4-21,21>>^ Os filhos de Selá, filho de Judá: Er, pai de Leca, Lada, pai de Maressa, e as famílias da casa dos que fabricavam linho, em Bete-Asbéia;

[[v13-4-22]]

^<<v13-4-22,22>>^ como também Joquim, e os homens de Cozeba, e Joás e Sarafe, os quais dominavam sobre Moabe, e Jasúbi-Leém. &#123;Estes registros são antigos.&#125;

[[v13-4-23]]

^<<v13-4-23,23>>^ Estes foram os oleiros, os habitantes de Netaim e de Gedera; e moravam ali com o rei para o seu serviço.

[[v13-4-24]]

^<<v13-4-24,24>>^ Os filhos de Simeão: Nemuel, Jamim, Jaribe, Zerá e Saul,

[[v13-4-25]]

^<<v13-4-25,25>>^ de quem foi filho Salum, de quem foi filho Mibsão, de quem foi filho Misma.

[[v13-4-26]]

^<<v13-4-26,26>>^ Os filhos de Misma: Jamuel, seu filho, de quem foi filho Zacur, de quem foi filho Simei.

[[v13-4-27]]

^<<v13-4-27,27>>^ Simei teve dezesseis filhos e seis filhas; porém seus irmãos não tiveram muitos filhos, nem se multiplicou toda a sua família tanto como as dos filhos de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ Eles habitaram em Berseba, Molada, Hazar-Sual,

[[v13-4-29]]

^<<v13-4-29,29>>^ Bila, Ezem, Tolade,

[[v13-4-30]]

^<<v13-4-30,30>>^ Betuel, Horma, Ziclague,

[[v13-4-31]]

^<<v13-4-31,31>>^ Bete-Marcabote, Hazar-Susim, Bete-Biri e Saraim; essas foram as suas cidades até o reinado de Davi.

[[v13-4-32]]

^<<v13-4-32,32>>^ As suas aldeias foram: Etã, Aim, Rimom, Toquem e Asã, cinco cidades,

[[v13-4-33]]

^<<v13-4-33,33>>^ com todas as suas aldeias, que estavam em redor destas cidades, até Baal. Estas foram as suas habitações e as suas genealogias.

[[v13-4-34]]

^<<v13-4-34,34>>^ Ora, Mesobabe, Jamleque, Josa, filho de Amazias,

[[v13-4-35]]

^<<v13-4-35,35>>^ Joel, Jeú, filho de Josibias, filho de Seraías, filho de Asiel,

[[v13-4-36]]

^<<v13-4-36,36>>^ Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaías,

[[v13-4-37]]

^<<v13-4-37,37>>^ e Ziza, filho de Sifi, filho de Alom, filho de Jedaías, filho de Sínri, filho de Semaías

[[v13-4-38]]

^<<v13-4-38,38>>^ estes, registrados por nome, foram príncipes nas suas famílias; e as famílias de seus pais se multiplicaram grandemente.

[[v13-4-39]]

^<<v13-4-39,39>>^ Chegaram até a entrada de Gedor, ao lado oriental do vale, em busca de pasto para os seus rebanhos;

[[v13-4-40]]

^<<v13-4-40,40>>^ e acharam pasto abundante e bom, e a terra era espaçosa, quieta e pacífica; pois os que antes habitavam ali eram descendentes de Cam.

[[v13-4-41]]

^<<v13-4-41,41>>^ Estes que estão inscritos por nome, vieram nos dias de Ezequias, rei de Judá, e destruíram as tendas e os meunins que se acharam ali, e os exterminaram totalmente até o dia de hoje, e habitaram em lugar deles; porque ali havia pasto para os seus rebanhos.

[[v13-4-42]]

^<<v13-4-42,42>>^ Também deles, isto é, dos filhos de Simeão, quinhentos homens foram ao monte Seir, tendo por capitães Pelatias, Nearias, Refaías e Uziel, filhos de Isi,

[[v13-4-43]]

^<<v13-4-43,43>>^ e, matando o restante dos amalequitas, que havia escapado, ficaram habitando ali até o dia de hoje.

'''

xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]