include::./index.adoc[]

[[v13-23-0]]
=== 1 Crônicas, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-23-1]]

^<<v13-23-1,1>>^ Ora, sendo Davi já velho e cheio de dias, fez Salomão, seu filho, rei sobre Israel.

[[v13-23-2]]

^<<v13-23-2,2>>^ E reuniu todos os chefes de Israel, como também os sacerdotes e levitas.

[[v13-23-3]]

^<<v13-23-3,3>>^ Foram contados os levitas de trinta anos para cima; e foi o número deles, segundo o seu registo, trinta e oito mil homens.

[[v13-23-4]]

^<<v13-23-4,4>>^ Deste número vinte e quatro mil promoverão a obra da casa do Senhor; seis mil servirão como oficiais e juízes;

[[v13-23-5]]

^<<v13-23-5,5>>^ quatro mil como porteiros; e quatro mil para louvarem ao Senhor com os instrumentos, que eu fiz para o louvar, disse Davi.

[[v13-23-6]]

^<<v13-23-6,6>>^ Davi os repartiu por turmas segundo os filhos de Levi: Gérsom, Coate e Merári.

[[v13-23-7]]

^<<v13-23-7,7>>^ Dos gersonitas: Ladã e Simei.

[[v13-23-8]]

^<<v13-23-8,8>>^ Os filhos de Ladã: Jeiel o chefe, Zetão e Joel, três.

[[v13-23-9]]

^<<v13-23-9,9>>^ Os filhos de Simei: Selomite, Haziel e Arã, três; estes foram os chefes das casas paternas de Ladã.

[[v13-23-10]]

^<<v13-23-10,10>>^ Os filhos de Simei: Jaate, Zina, Jeús e Berias; estes foram os filhos de Simei, quatro.

[[v13-23-11]]

^<<v13-23-11,11>>^ Jaate era o chefe, e Ziza o segundo. Mas Jeús e Berias não tiveram muitos filhos; pelo que estes, contados juntos, se tornaram uma só casa paterna.

[[v13-23-12]]

^<<v13-23-12,12>>^ Os filhos de Coate: Anrão, Izar, Hebrom e Uziel, quatro.

[[v13-23-13]]

^<<v13-23-13,13>>^ Os filhos de Anrão: Arão e Moisés. Arão foi separado para consagrar as coisas santíssimas, ele e seus filhos, eternamente para queimarem incenso diante do Senhor, e o servirem, e pronunciarem bênçãos em nome de Deus para sempre.

[[v13-23-14]]

^<<v13-23-14,14>>^ Mas quanto a Moisés, homem de Deus, seus filhos foram contados entre os da tribo de Davi.

[[v13-23-15]]

^<<v13-23-15,15>>^ Os filhos de Moisés: Gerson e Eliézer.

[[v13-23-16]]

^<<v13-23-16,16>>^ De Gérson: Sebuel o chefe.

[[v13-23-17]]

^<<v13-23-17,17>>^ De Eliézer: Reabias o chefe; e Eliézer não teve outros filhos; porém os filhos de Reabias foram muito numerosos.

[[v13-23-18]]

^<<v13-23-18,18>>^ De Izar: Selomite o chefe.

[[v13-23-19]]

^<<v13-23-19,19>>^ Os filhos: de Hebrom: Jerias o chefe, Amarias o segundo, Jaaziel o terceiro, e Jecameão o quarto.

[[v13-23-20]]

^<<v13-23-20,20>>^ Os filhos de Uziel: Mica o chefe. Issias o segundo.

[[v13-23-21]]

^<<v13-23-21,21>>^ Os filhos de Merári: Mali e Musi. Os filhos de Mali: Eleazar e Quis.

[[v13-23-22]]

^<<v13-23-22,22>>^ Eleazar morreu, não tendo filhos, mas tão somente filhas; e os filhos de Quis, seus irmãos, tomaram-nas por mulheres.

[[v13-23-23]]

^<<v13-23-23,23>>^ Os filhos de Musi: Mali, Eder e Jerimote, três.

[[v13-23-24]]

^<<v13-23-24,24>>^ Esses são os filhos de Levi segundo as suas casas paternas, isto é, segundo os chefes das casas paternas, conforme o número dos que foram registrados pelos seus: nomes, individualmente, da idade de vinte anos para cima, os quais trabalhavam no serviço da casa do Senhor.

[[v13-23-25]]

^<<v13-23-25,25>>^ Pois Davi disse: O Senhor Deus de Israel deu repouso ao seu povo; e ele habita em Jerusalém para sempre.

[[v13-23-26]]

^<<v13-23-26,26>>^ Também os levitas não terão mais de levar o tabernáculo e todos os objetos pertencentes ao serviço do mesmo.

[[v13-23-27]]

^<<v13-23-27,27>>^ Eis porque, segundo as ultimas palavras de Davi, foram contados os levitas da idade de vinte anos para cima.

[[v13-23-28]]

^<<v13-23-28,28>>^ Porque o seu cargo seria o de assistirem aos filhos de Arão no serviço da casa do Senhor, nos átrios, e nas câmaras, e na purificação de todas as coisas sagradas, e em qualquer trabalho para o serviço da casa de Deus,

[[v13-23-29]]

^<<v13-23-29,29>>^ cuidando dos pães da proposição, e da flor de farinha para a oferta de cereais, quer seja de bolos ázimos, quer seja do que se assa na panela, quer seja do que é misturado com azeite, e de toda sorte de medidas e pesos;

[[v13-23-30]]

^<<v13-23-30,30>>^ e de estarem cada manhã em pé para render graças e louvor ao Senhor, e semelhantemente à tarde.

[[v13-23-31]]

^<<v13-23-31,31>>^ e oferecerem continuamente perante o Senhor todos os holocaustos, nos sábados, nas luas novas e nas festas fixas, segundo o número ordenado.

[[v13-23-32]]

^<<v13-23-32,32>>^ Também teriam a seu cargo a tenda da revelação, o lugar santo, e os filhos de Arão, seus irmãos, no serviço da casa do Senhor.

'''

xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]