include::./index.adoc[]

[[v13-27-0]]
=== 1 Crônicas, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-27-1]]

^<<v13-27-1,1>>^ Ora, os filhos de Israel segundo o seu número, os chefes das casas paternas, e os chefes dos milhares e das centenas, com os seus oficiais, que serviam ao rei em todos os negócios das turmas que entravam e saíam de mês em mês, em todos os meses do ano, eram em cada turma vinte e quatro mil.

[[v13-27-2]]

^<<v13-27-2,2>>^ sobre a primeira turma, no primeiro mês, estava Jasobeão, filho de Zabdiel; e em sua turma havia vinte e quatro mil.

[[v13-27-3]]

^<<v13-27-3,3>>^ Era ele descendente de Pérez, e chefe de todos os comandantes do exército para o primeiro mês.

[[v13-27-4]]

^<<v13-27-4,4>>^ Sobre a turma do segundo mês estava Dodai, o aoíta, com a sua turma, cujo chefe era Miclote; e em sua turma havia vinte e quatro mil.

[[v13-27-5]]

^<<v13-27-5,5>>^ O terceiro comandante do exército, para o terceiro mês, era o chefe Benaías, filho do sacerdote Jeoiada; e em sua turma havia vinte e quatro mil.

[[v13-27-6]]

^<<v13-27-6,6>>^ Este é aquele Benaías que era o varão valente entre os trinta e comandava os trinta; e da sua turma era seu filho Amizabade.

[[v13-27-7]]

^<<v13-27-7,7>>^ O quarto, do quarto mês, era Asael, irmão de Joabe, e depois dele Zebadia; seu filho; e em sua turma havia vinte e quatro mil.

[[v13-27-8]]

^<<v13-27-8,8>>^ O quinto, do quinto mês:, Samute, o israíta; e em sua turma havia vinte e quatro mil.

[[v13-27-9]]

^<<v13-27-9,9>>^ O sexto, do sexto mês: Ira, filho de Iques, o tecoíta; e em sua turma havia vinte e quatro mil.

[[v13-27-10]]

^<<v13-27-10,10>>^ O sétimo, do sétimo mês:, Helez, o pelonita, descendente de Efraim; e em sua turma havia vinte e quatro mil.

[[v13-27-11]]

^<<v13-27-11,11>>^ O oitavo, do oitavo mês, Sibecai, o husatita, dos zeraítas; e em sua turma havia vinte e quatro mil.

[[v13-27-12]]

^<<v13-27-12,12>>^ O nono, do nono mês, Abiezer, o anatotita, dos benjamitas; e em sua turma havia vinte e quatro mil.

[[v13-27-13]]

^<<v13-27-13,13>>^ O décimo, do décimo mês, Maarai, o netofatita, dos zeraítas; e em sua turma havia vinte e quatro mil.

[[v13-27-14]]

^<<v13-27-14,14>>^ O undécimo, do undécimo mês, Benaías, o piratonita, dos filhos de Efraim; e em sua turma havia vinte e quatro mil.

[[v13-27-15]]

^<<v13-27-15,15>>^ O duodécimo, do duodécimo mês, Heldai, o netofatita, de Otniel; e em sua turma havia vinte e quatro mil.

[[v13-27-16]]

^<<v13-27-16,16>>^ Sobre as tribos de Israel estavam estes: sobre os rubenitas era chefe Eliézer, filho de Zicri; sobre os simeonitas, Sefatias, filho de Maacá;

[[v13-27-17]]

^<<v13-27-17,17>>^ sobre os levitas, Hasabias, filho de Quemuel; sobre os aronitas, Zadoque;

[[v13-27-18]]

^<<v13-27-18,18>>^ sobre Judá, , Eliu:, um dos irmãos de Davi; sobre Issacar, Onri, filho de Micael;

[[v13-27-19]]

^<<v13-27-19,19>>^ sobre Zebulom, Ismaías, filho de Obadias; sobre Naftali, Jerimote, filho de Azrriel;

[[v13-27-20]]

^<<v13-27-20,20>>^ sobre os filhos de Efraim, Oséias, filho de Azazias; sobre a meia tribo de Manassés, Joel, filho de Pedaías;

[[v13-27-21]]

^<<v13-27-21,21>>^ sobre a meia tribo de Manassés em Gileade, Ido, filho de Zacarias; sobre Benjamim, Jaasiel, filho de Abner;

[[v13-27-22]]

^<<v13-27-22,22>>^ sobre Dã, Azarel, filho de Jeroão. Esses eram os chefes das tribos de Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ Não tomou, porém, Davi o número dos de vinte anos para baixo, porquanto o Senhor tinha dito que havia de multiplicar Israel como as estrelas do céu.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joabe, filho de Zeruia, tinha começado a numerá-los, porém não acabou, porquanto viera por isso ira sobre Israel; pelo que o número não foi posto no livro das crônicas do rei Davi.

[[v13-27-25]]

^<<v13-27-25,25>>^ Sobre os tesouros do rei estava Azmavete, filho de Adiel; sobre os tesouros dos campos, das cidades, das aldeias e das torres, Jônatas, filho de Uzias;

[[v13-27-26]]

^<<v13-27-26,26>>^ sobre os que faziam a obra do campo, na lavoura da terra, Ezri, filho de Quelube;

[[v13-27-27]]

^<<v13-27-27,27>>^ sobre as vinhas, Simei, o ramatita; sobre o produto das vides nas adegas do vinho, Zabdi, o sifmita;

[[v13-27-28]]

^<<v13-27-28,28>>^ sobre os olivais e sicômoros que havia nas campinas, Baal-Hanã, o gederita; sobre os armazéns do azeite, Joás;

[[v13-27-29]]

^<<v13-27-29,29>>^ sobre o gado que pastava em Sarom, Sitrai, o saronita; sobre o gado dos vales, Safate, filho de Adlai;

[[v13-27-30]]

^<<v13-27-30,30>>^ sobre os camelos, Obil, o ismaelita; sobre as jumentas, Jedeías, o meronotita;

[[v13-27-31]]

^<<v13-27-31,31>>^ e sobre o gado miúdo, Jaziz, o hagrita. Todos esses eram os intendentes dos bens do rei Davi.

[[v13-27-32]]

^<<v13-27-32,32>>^ Jônatas, tio de Davi, era conselheiro, homem entendido, e escriba; ele e Jeiel, filho de Hacmôni, assistiam os filhos do rei;

[[v13-27-33]]

^<<v13-27-33,33>>^ Aitofel era conselheiro do rei; Husai, o arquita, era amigo o rei;

[[v13-27-34]]

^<<v13-27-34,34>>^ depois de Aitotel, Jeoiada, filho de Benaías, e Abiatar foram conselheiros; e Joabe era chefe do exército do rei.

'''

xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]