include::./index.adoc[]

[[v13-13-0]]
=== 1 Crônicas, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-13-1]]

^<<v13-13-1,1>>^ Ora, Davi consultou os chefes dos milhares, e das centenas, a saber, todos os oficiais.

[[v13-13-2]]

^<<v13-13-2,2>>^ E disse Davi a toda a congregação de Israel: Se bem vos parece, e se isto vem do Senhor nosso Deus, enviemos mensageiros por toda parte aos nossos outros irmãos que estão em todas as terras de Israel, e com eles aos sacerdotes e levitas nas suas cidades, e nos seus campos, para que se reunam conosco,

[[v13-13-3]]

^<<v13-13-3,3>>^ e tornemos a trazer para nós a arca do nosso Deus; porque não a buscamos nos dias de Saul.

[[v13-13-4]]

^<<v13-13-4,4>>^ E toda a congregação concordou em que assim se fizesse; porque isso pareceu reto aos olhos de todo o povo.

[[v13-13-5]]

^<<v13-13-5,5>>^ Convocou, pois, Davi todo o Israel desde Sior, o ribeiro do Egito, até a entrada de Hamate, para trazer de Quiriate-Jearim a arca de Deus.

[[v13-13-6]]

^<<v13-13-6,6>>^ E Davi, com todo o Israel, subiu a Baalá, isto é, a Quiriate-Jearim, que está em Judá, para fazer subir dali a arca de Deus, a qual se chama pelo nome do Senhor, que habita entre os querubins.

[[v13-13-7]]

^<<v13-13-7,7>>^ Levaram a arca de Deus sobre um carro novo, tirando-a da casa de Abinadabe; e Uzá e Aiô guiavam o carro.

[[v13-13-8]]

^<<v13-13-8,8>>^ Davi e todo o Israel alegravam-se perante Deus com todas as suas forças, cantando e tocando harpas, alaúdes, tamboris, címbalos e trombetas.

[[v13-13-9]]

^<<v13-13-9,9>>^ Quando chegaram a eira de Quidom, Uzá estendeu a mão para segurar a arca, porque os bois tropeçavam.

[[v13-13-10]]

^<<v13-13-10,10>>^ Então se acendeu a ira do Senhor contra Uzá, e o Senhor o feriu por ter estendido a mão à arca; e ele morreu ali perante Deus.

[[v13-13-11]]

^<<v13-13-11,11>>^ E Davi se encheu de desgosto porque o Senhor havia irrompido contra Uzá; pelo que chamou aquele lugar Pérez-Uzá, como se chama até o dia de hoje.

[[v13-13-12]]

^<<v13-13-12,12>>^ Temeu Davi a Deus naquele dia, e disse: Como trarei a mim a arca de Deus?

[[v13-13-13]]

^<<v13-13-13,13>>^ Pelo que não trouxe a arca a si para a cidade de Davi, porém a fez retirar para a casa de Obede-Edom, o giteu.

[[v13-13-14]]

^<<v13-13-14,14>>^ Assim ficou a arca de Deus com a família de Obede-Edom, três meses em sua casa; e o Senhor abençoou a casa de Obede-Edom, e tudo o que lhe pertencia.

'''

xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[&#60; Capítulo Anterior] | <<v13-13-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[Próximo Capítulo &#62;]