include::./index.adoc[]

[[v13-28-0]]
=== 1 Crônicas, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-28-1]]

^<<v13-28-1,1>>^ Ora, Davi convocou a Jerusalém todos os chefes de Israel, os chefes das tribos, os chefes das turmas que serviam o rei, os chefes de mil, e os chefes de cem, e os intendentes de todos os bens e possessões do rei e de seus filhos, como também os oficiais e os homens mais valorosos e valentes.

[[v13-28-2]]

^<<v13-28-2,2>>^ Então o rei Davi se pôs em pé, e disse: Ouvi-me, irmãos meus e povo meu. Em meu coração havia eu proposto edificar uma casa de repouso para a arca do pacto de Senhor, e para o escabelo dos pés do nosso Deus, e tinha feito os preparativos para a edificar.

[[v13-28-3]]

^<<v13-28-3,3>>^ Mas Deus me disse: Tu não edificarás casa ao meu nome, porque és homem de guerra, e tens derramado muito sangue.

[[v13-28-4]]

^<<v13-28-4,4>>^ Todavia o Senhor Deus de Israel escolheu-me de toda a casa de meu pai, para ser rei sobre Israel para sempre; porque a Judá escolheu por príncipe, e na casa de Judá a casa de meu pai, e entre os filhos de meu pai se agradou de mim para me fazer rei sobre todo o Israel.

[[v13-28-5]]

^<<v13-28-5,5>>^ E, de todos os meus filhos &#123;porque muitos filhos me deu o Senhor&#125;, escolheu ele o meu filho Salomão para se assentar no trono do reino do Senhor sobre Israel,

[[v13-28-6]]

^<<v13-28-6,6>>^ e me disse: Teu filho Salomão edificará a minha casa e os meus átrios, porque o escolhi para me ser por filho, e eu lhe serei por pai.

[[v13-28-7]]

^<<v13-28-7,7>>^ Estabelecerei o seu reino para sempre, se ele perseverar em cumprir os meus mandamentos e os meus juízos, como o faz no dia de hoje.

[[v13-28-8]]

^<<v13-28-8,8>>^ Agora, pois, à vista de todo o Israel, a congregação do Senhor, e em presença de nosso Deus, que nos ouve, observai e buscai todos os mandamentos do Senhor vosso Deus, para que possuais esta boa terra, e a deixeis por herança a vossos filhos depois de, vos, para sempre.

[[v13-28-9]]

^<<v13-28-9,9>>^ E tu, meu filho Salomão, conhece o Deus de teu pai, e serve-o com coração perfeito e espírito voluntário; porque o Senhor esquadrinha todos os corações, e penetra todos os desígnios e pensamentos. Se o buscares, será achado de ti; porém, se o deixares, rejeitar-te-á para sempre.

[[v13-28-10]]

^<<v13-28-10,10>>^ Agora toma cuidado, porque o Senhor te escolheu para edificares uma casa para o santuário; esforça-te, e faze a obra.

[[v13-28-11]]

^<<v13-28-11,11>>^ Então Davi deu a Salomão, seu filho, o modelo do alpendre com as suas casas, as suas tesourarias, os seus cenáculos e as suas recâmaras interiores, como também da casa do propiciatório;

[[v13-28-12]]

^<<v13-28-12,12>>^ e também o modelo de tudo o que tinha em mente para os átrios da casa do Senhor, para todas as câmaras em redor, para os tesouros da casa de Deus e para os tesouros das coisas sagradas;

[[v13-28-13]]

^<<v13-28-13,13>>^ também para as turmas dos sacerdotes e dos levitas, para toda a obra do serviço da casa do Senhor e para todos os vasos do serviço da casa do Senhor,

[[v13-28-14]]

^<<v13-28-14,14>>^ especificando o peso do ouro para os vasos de ouro, para todos os vasos de cada espécie de serviço, o peso da prata para todos os vasos de prata, para todos os vasos de cada espécie de serviço;

[[v13-28-15]]

^<<v13-28-15,15>>^ o peso para os castiçais de ouro e suas lâmpadas, o peso do ouro para cada castiçal e as suas lâmpadas, e o peso da prata para os castiçais de prata, para cada castiçal e as suas lâmpadas, segundo o uso de cada castiçal;

[[v13-28-16]]

^<<v13-28-16,16>>^ o peso do ouro para as mesas dos pães da proposição, para cada mesa; como também da prata para as mesas de prata;

[[v13-28-17]]

^<<v13-28-17,17>>^ e o ouro puro para os garfos, as bacias e os jarros; para as taças de ouro, o peso para cada taça; como também para as taças de prata, o peso para cada taça,

[[v13-28-18]]

^<<v13-28-18,18>>^ e para o altar do incenso, o peso de ouro refinado; como também o ouro para o modelo do carro dos querubins que, de asas estendidas, cobririam a arca do pacto do Senhor.

[[v13-28-19]]

^<<v13-28-19,19>>^ Tudo isso se me fez entender, disse Davi, por escrito da mão do Senhor, a saber, todas as obras deste modelo.

[[v13-28-20]]

^<<v13-28-20,20>>^ Disse, pois, Davi a seu filho Salomão: Esforça-te e tem bom ânimo, e faze a obra; não temas, nem te desalentes, pois o Senhor Deus, meu Deus, é contigo; não te deixará, nem te desamparará, até que seja acabada toda a obra para o serviço da casa do Senhor.

[[v13-28-21]]

^<<v13-28-21,21>>^ Eis aí as turmas dos sacerdotes e dos levitas para todo o serviço da casa de Deus; e estará contigo para toda a obra todo homem bem disposto e perito em qualquer espécie de serviço; também os chefes e todo o povo estarão inteiramente às tuas ordens.

'''

xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[Próximo Capítulo &#62;]