include::./index.adoc[]

[[v13-21-0]]
=== 1 Crônicas, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-21-1]]

^<<v13-21-1,1>>^ Então Satanás se levantou contra Israel, e incitou Davi a numerar Israel.

[[v13-21-2]]

^<<v13-21-2,2>>^ E disse Davi a Joabe e aos príncipes de povo: Ide, cantai a Israel desde Berseba até Dã; e trazei-me a conta, para que eu saiba o número deles.

[[v13-21-3]]

^<<v13-21-3,3>>^ Então disse Joabe: O Senhor acrescente ao seu povo cem vezes tanto como ele é! Porventura, é rei meu senhor, não são teus os servos de meu senhor? Por que requer isto e meu senhor. Por que traria ele culpa sobre Israel?

[[v13-21-4]]

^<<v13-21-4,4>>^ Todavia a palavra de rei prevaleceu contra Joabe. Pelo que saiu Joabe, e passou por todo o Israel; depois voltou para Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ E Joabe deu a Davi o resultado da numeração do povo. E era todo o Israel um milhão e cem mil homens que arrancavam da espada; e de Judá quatrocentos e setenta mil homens que arrancavam da espada.

[[v13-21-6]]

^<<v13-21-6,6>>^ Mas entre eles Joabe não contou os de Levi e Benjamim, porque a palavra do rei lhe foi abominável.

[[v13-21-7]]

^<<v13-21-7,7>>^ E este negócio desagradou a Deus, pelo que feriu Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ Então disse Davi a Deus: Gravemente pequei em fazer tal coisa; agora porém, peço-te, tira a iniqüidade de teu servo, porque procedi mui loucamente.

[[v13-21-9]]

^<<v13-21-9,9>>^ Falou o Senhor a Gade, o vidente de Davi, dizendo:

[[v13-21-10]]

^<<v13-21-10,10>>^ Vai, e dize a Davi: Assim diz o Senhor: Três coisas te proponho; escolhe uma delas, para que eu te faça.

[[v13-21-11]]

^<<v13-21-11,11>>^ E Gade veio a Davi, e lhe disse: Assim diz o Senhor: Escolhe o que quiseres:

[[v13-21-12]]

^<<v13-21-12,12>>^ ou três anos de fome; ou seres por três meses consumido diante de teus adversários, enquanto a espada de teus inimigos te alcance; ou que por três dias a espada do Senhor, isto é, a peste na terra, e o anjo do Senhor façam destruição por todos os termos de Israel. Vê, pois, agora que resposta hei de levar a quem me enviou.

[[v13-21-13]]

^<<v13-21-13,13>>^ Então disse Davi a Gade: Estou em grande angústia; caia eu, pois, nas mãos do Senhor, porque mui grandes são as suas misericórdias; mas que eu não caia nas mãos dos homens.

[[v13-21-14]]

^<<v13-21-14,14>>^ Mandou, pois, o Senhor a peste a Israel; e caíram de Israel setenta mil homens.

[[v13-21-15]]

^<<v13-21-15,15>>^ E Deus mandou um anjo a Jerusalém para a destruir; e, estando ele prestes a destrui-la, o Senhor olhou e se arrependeu daquele mal, e disse ao anjo destruidor: Basta; agora retira a tua mão. E o anjo do Senhor estava junto à eira de Ornã, o jebuseu.

[[v13-21-16]]

^<<v13-21-16,16>>^ E Davi, levantando os olhos, viu o anjo do Senhor, que estava entre a terra e o céu, tendo na mão uma espada desembainhada estendida sobre Jerusalém. Então Davi e os anciãos, cobertos de sacos, se prostraram sobre os seus rostos.

[[v13-21-17]]

^<<v13-21-17,17>>^ E dissemorreram Saul e seus três filhos; morreu toda a sua o povo? E eu mesmo sou o que pequei, e procedi muito mal; mas estas ovelhas, que fizeram? Seja tua mão, Senhor Deus meu, contra mim e contra a casa de meu pai, porem não contra o teu povo para castigá-lo com peste.

[[v13-21-18]]

^<<v13-21-18,18>>^ Então o anjo do Senhor ordenou a Gade que dissesse a Davi para subir e levantar um altar ao Senhor na eira de Ornã, o jebuseu.

[[v13-21-19]]

^<<v13-21-19,19>>^ Subiu, pois, Davi, conforme a palavra que Gade falara em nome do Senhor.

[[v13-21-20]]

^<<v13-21-20,20>>^ E, virando-se Ornã, viu o anjo; e seus quatro filhos, que estavam com ele, se esconderam. Ora, Ornã estava debulhando trigo.

[[v13-21-21]]

^<<v13-21-21,21>>^ Quando Davi se vinha chegando a Ornã, este olhou e o viu e, saindo da terra, prostrou-se diante dele com o rosto em terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ Então disse Davi a Ornã: Dá-me o lugar da eira pelo seu valor, para eu edificar nele um altar ao Senhor, para que cesse esta praga de sobre o povo.

[[v13-21-23]]

^<<v13-21-23,23>>^ Respondeu Ornã a Davi: Toma-o para ti, e faça o rei meu senhor o que lhe parecer bem. Eis que dou os bois para holocaustos, os trilhos para lenha, e o trigo para oferta de cereais; tudo dou.

[[v13-21-24]]

^<<v13-21-24,24>>^ Mas o rei Davi disse a Ornã: Não, antes quero comprá-lo pelo seu valor; pois não tomarei para o Senhor o que é teu, nem oferecerei holocausto que não me custe nada.

[[v13-21-25]]

^<<v13-21-25,25>>^ E Davi deu a Ornã por aquele lugar o peso de seiscentos siclos de ouro.

[[v13-21-26]]

^<<v13-21-26,26>>^ Então Davi edificou ali um altar ao Senhor, e ofereceu holocaustos e ofertas pacíficas; e invocou o Senhor, o qual lhe respondeu do céu, com fogo sobre o altar de holocausto.

[[v13-21-27]]

^<<v13-21-27,27>>^ E o Senhor deu ordem ao anjo, que tomou a meter a sua espada na bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Nesse mesmo tempo, vendo Davi que o Senhor lhe respondera na eira de Ornã, o jebuseu, ofereceu ali os seus sacrifícios.

[[v13-21-29]]

^<<v13-21-29,29>>^ Pois o tabernáculo do Senhor que Moisés fizera no deserto, e o altar do holocausto, estavam naquele tempo no alto de Gibeão;

[[v13-21-30]]

^<<v13-21-30,30>>^ mas Davi não podia ir perante ele para consultar a Deus, porque estava atemorizado por causa da espada do anjo do Senhor.

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]