include::./index.adoc[]

[[v13-8-0]]
=== 1 Crônicas, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-8-1]]

^<<v13-8-1,1>>^ Benjamim foi pai de Belá, seu primogênito, de Asbel o segundo, e de Aará o terceiro,

[[v13-8-2]]

^<<v13-8-2,2>>^ de Noá o quarto, e de Rafa o quinto.

[[v13-8-3]]

^<<v13-8-3,3>>^ Belá teve estes filhos: Adar, Gêra, Abiúde,

[[v13-8-4]]

^<<v13-8-4,4>>^ Abisua, Naamã, Aoá,

[[v13-8-5]]

^<<v13-8-5,5>>^ Gêra, Sefufã e Hurão.

[[v13-8-6]]

^<<v13-8-6,6>>^ Estes foram os filhos de Eúde, que foram os chefes das casas paternas dos habitantes de Geba, e que foram levados cativos para Manaate;

[[v13-8-7]]

^<<v13-8-7,7>>^ Naamã, Aías e Gêra; este os transportou; foi ele pai de Uzá e Aiúde.

[[v13-8-8]]

^<<v13-8-8,8>>^ Saaraim teve filhos na terra de Moabe, depois que despedira Husim e Baara, suas mulheres.

[[v13-8-9]]

^<<v13-8-9,9>>^ E de Hodes, sua mulher, teve Jobabe, Zíbia, Messa, Malcã,

[[v13-8-10]]

^<<v13-8-10,10>>^ Jeuz, Saquias e Mirma; esses foram seus filhos:, chefes de casas paternas:

[[v13-8-11]]

^<<v13-8-11,11>>^ De Husim teve Abitube e Elpaal.

[[v13-8-12]]

^<<v13-8-12,12>>^ Os filhos de Elpaal: Eber, Misã, Semede &#123;este edificou Ono e Lode e suas aldeias&#125;,

[[v13-8-13]]

^<<v13-8-13,13>>^ Berias e Sema &#123;estes foram chefes de casas paternas dos habitantes de Aijalom, os quais afugentaram os habitantes de Gatel ,

[[v13-8-14]]

^<<v13-8-14,14>>^ Aiô, Sasaque e Jerimote.

[[v13-8-15]]

^<<v13-8-15,15>>^ Zebadias, Arade, Eder,

[[v13-8-16]]

^<<v13-8-16,16>>^ Micael, Ispá e Joá foram filhos de Berias;

[[v13-8-17]]

^<<v13-8-17,17>>^ Zebadias, Mesulão, Hizqui, Heber,

[[v13-8-18]]

^<<v13-8-18,18>>^ Ismerai, Izlias e Jobabe foram filhos de Elpaal;

[[v13-8-19]]

^<<v13-8-19,19>>^ Jaquim, Zicri, Zabdi,

[[v13-8-20]]

^<<v13-8-20,20>>^ Elienai, Ziletai, Eliel,

[[v13-8-21]]

^<<v13-8-21,21>>^ Adaías, Beraías e Sinrate foram filhos de Simei;

[[v13-8-22]]

^<<v13-8-22,22>>^ Ispã, Eber, Eliel,

[[v13-8-23]]

^<<v13-8-23,23>>^ Abdom, Zicri, Hanã,

[[v13-8-24]]

^<<v13-8-24,24>>^ Hananias, Elão, Antotias,

[[v13-8-25]]

^<<v13-8-25,25>>^ Ifdéias e Penuel foram filhos de Sasaque;

[[v13-8-26]]

^<<v13-8-26,26>>^ Sanserai, Searias, Atalias,

[[v13-8-27]]

^<<v13-8-27,27>>^ Jaaresias, Elias e Zicri foram filhos de Jeroão.

[[v13-8-28]]

^<<v13-8-28,28>>^ Estes foram chefes de casas paternas, segundo as suas gerações, homens principais; e habitaram em Jerusalém.

[[v13-8-29]]

^<<v13-8-29,29>>^ E em Gibeão habitaram o pai de Gibeão, cuja mulher se chamava Maacá,

[[v13-8-30]]

^<<v13-8-30,30>>^ e seu filho primogênito Abdom, depois Zur, Quiz, Baal, Nadabe,

[[v13-8-31]]

^<<v13-8-31,31>>^ Gedor, Aiô, Zequer e Miclote.

[[v13-8-32]]

^<<v13-8-32,32>>^ Miclote foi pai de Siméia; também estes habitaram em Jerusalém defronte de seus irmãos.

[[v13-8-33]]

^<<v13-8-33,33>>^ Ner foi pai de Quis, e Quis de Saul; Saul foi pai de Jônatas, Malquisua, Abinadabe e Es-Baal.

[[v13-8-34]]

^<<v13-8-34,34>>^ Filho de Jônatas foi Meribe-Baal; e Meribe-Baal foi pai de Mica.

[[v13-8-35]]

^<<v13-8-35,35>>^ Os filhos de Mica foram: Pitom, Meleque, Tareá e Acaz.

[[v13-8-36]]

^<<v13-8-36,36>>^ Acaz foi pai de Jeoada; Jeoada foi pai de Alemete, Azmavete e Zinri; Zinri foi pai de Moza;

[[v13-8-37]]

^<<v13-8-37,37>>^ Moza foi pai de Bineá, de quem foi filho Rafa, de quem foi filho Eleasá, de quem foi filho Azel.

[[v13-8-38]]

^<<v13-8-38,38>>^ Azel teve seis filhos, cujos nomes foram: Azricão, Bocru, Ismael, Searias, Obadias e Hanã; todos estes foram filhos de Azel.

[[v13-8-39]]

^<<v13-8-39,39>>^ Os filhos de Eseque, seu irmão: Ulão, seu primogênito, Jeús o segundo, e Elifelete o terceiro.

[[v13-8-40]]

^<<v13-8-40,40>>^ Os filhos de Ulão foram homens heróis, valentes, e flecheiros destros; e tiveram muitos filhos, e filhos de filhos, cento e cinqüenta. Todos estes foram dos filhos de Benjamim.

'''

xref:013-1-cronicas/013-1-cronicas-007.adoc#v13-7-0[&#60; Capítulo Anterior] | <<v13-8-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-009.adoc#v13-9-0[Próximo Capítulo &#62;]