include::./index.adoc[]

[[v13-9-0]]
=== 1 Crônicas, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-9-1]]

^<<v13-9-1,1>>^ Todo o Israel, pois, foi arrolado por genealogias, que estão inscritas no livro dos reis de Israel; e Judá foi transportado para Babilônia, por causa da sua infidelidade.

[[v13-9-2]]

^<<v13-9-2,2>>^ Ora, os primeiros a se restabelecerem nas suas possessões e nas suas cidades foram de Israel, os sacerdotes, os levitas, e os netinins.

[[v13-9-3]]

^<<v13-9-3,3>>^ E alguns dos filhos de Judá, de Benjamim, e de Efraim e Manassés, habitaram em Jerusalém:

[[v13-9-4]]

^<<v13-9-4,4>>^ Utai, filho de Amiúde, filho de Onri, filho de Inri, filho de Bari, dos filhos de Pérez, filho de Judá;

[[v13-9-5]]

^<<v13-9-5,5>>^ dos silonitas: Asaías o primogênito, e seus filhos;

[[v13-9-6]]

^<<v13-9-6,6>>^ dos filhos de Zerá: Jeuel e seus irmãos, seiscentos e noventa;

[[v13-9-7]]

^<<v13-9-7,7>>^ dos filhos de Benjamim: Salu, filho de Mesulão, filho de Hodavias, filho de Hassenua;

[[v13-9-8]]

^<<v13-9-8,8>>^ Ibnéias, filho de Jeroão; Elá, filho de Uzi, filho de Mícri; Mesulão, filho de Sefatias, filho de Reuel, filho de Ibnijas;

[[v13-9-9]]

^<<v13-9-9,9>>^ e seus irmãos, segundo as suas gerações, novecentos e cinqüenta e seis. Todos estes homens foram chefes de casas paternas, segundo as casas de seus pais.

[[v13-9-10]]

^<<v13-9-10,10>>^ E dos sacerdotes: Jedaías, Jeoiaribe e Jaquim;

[[v13-9-11]]

^<<v13-9-11,11>>^ Azarias, filho de Hilquias, filho de Mesulão, filho de Zadoque, filho de Meraiote. filho de Aitube, regente da casa de Deus;

[[v13-9-12]]

^<<v13-9-12,12>>^ Adaías, filho de Jeroão, filho de Pasur, filho de Malquias; Maasai, filho de Adiel, filho de Jazera, filho de Mesulão, filho de Mesilemite, filho de Imer;

[[v13-9-13]]

^<<v13-9-13,13>>^ como também seus irmãos, chefes de suas casas paternas, mil setecentos e sessenta, homens capacitados para o serviço a casa de Deus.

[[v13-9-14]]

^<<v13-9-14,14>>^ E dos levitas: Semaías, filho de Hassube, filho de Azricão, filho de Hasabias, dos filhos de Merári:

[[v13-9-15]]

^<<v13-9-15,15>>^ Baquebacar, Heres, Galal, e Matanias, filho de Mica, filho de Zicri, filho de Asafe;

[[v13-9-16]]

^<<v13-9-16,16>>^ Obadias, filho de Semaías, filho de Galal, filho de Jedútun; e Berequias, filho de Asa, filho de Elcana, morador das aldeias dos netofatitas.

[[v13-9-17]]

^<<v13-9-17,17>>^ Foram porteiros: Salum, Acube, Talmom, Aimã, e seus irmãos, sendo Salum o chefe;

[[v13-9-18]]

^<<v13-9-18,18>>^ e até aquele tempo estavam de guarda à porta do rei, que ficava ao oriente. Estes foram os porteiros para os arraiais dos filhos de Levi.

[[v13-9-19]]

^<<v13-9-19,19>>^ Salum, filho de Coré, filho de Ebiasafe, filho de Corá, e seus irmãos da casa de seu pai, os coraítas estavam encarregados do serviço como guardas das entradas do tabernáculo, como seus pais também tinham sido encarregados do arraial do Senhor, sendo guardas da entrada.

[[v13-9-20]]

^<<v13-9-20,20>>^ Finéias, filho de Eleazar, dantes era guia entre eles; e o Senhor era com ele.

[[v13-9-21]]

^<<v13-9-21,21>>^ Zacarias, filho de Meselemias, guardava a porta da tenda da revelação.

[[v13-9-22]]

^<<v13-9-22,22>>^ Todos estes, escolhidos para serem guardas das entradas, foram duzentos e doze; e foram contados por suas genealogias, nas suas aldeias. Davi e Samuel, o vidente, os constituíram nos seus respectivos cargos.

[[v13-9-23]]

^<<v13-9-23,23>>^ Tinham, pois, eles e seus filhos o cargo das portas da casa do Senhor, a saber, da casa da tenda, como guardas.

[[v13-9-24]]

^<<v13-9-24,24>>^ Os porteiros estavam aos quatro lados, ao oriente, ao ocidente, ao norte e ao sul:

[[v13-9-25]]

^<<v13-9-25,25>>^ Seus irmãos, que moravam nas suas aldeias, deviam de tempo em tempo vir por sete dias para servirem com eles.

[[v13-9-26]]

^<<v13-9-26,26>>^ pois os quatro porteiros principais, que eram levitas, estavam encarregados das câmaras e dos tesouros da casa de Deus.

[[v13-9-27]]

^<<v13-9-27,27>>^ E se alojavam à roda da casa de Deus. Porque a sua guarda lhes estava entregue, e tinham o encargo de abri-la cada manhã.

[[v13-9-28]]

^<<v13-9-28,28>>^ Alguns deles estavam encarregados dos utensílios do serviço, pois estes por conta eram trazidos e por conta eram tirados.

[[v13-9-29]]

^<<v13-9-29,29>>^ Outros estavam encarregados dos móveis e de todos os utensílios do santuário, como também da flor de farinha, do vinho, do azeite, do incenso e das especiarias.

[[v13-9-30]]

^<<v13-9-30,30>>^ Os que confeccionavam as especiarias eram dos filhos dos sacerdotes.

[[v13-9-31]]

^<<v13-9-31,31>>^ Matitias, um dos levitas, o primogênito de Salum, o coraíta, estava encarregado de tudo o que se cozia em sertãs.

[[v13-9-32]]

^<<v13-9-32,32>>^ E seus irmãos, dentre os filhos dos coatitas, alguns tinham o cargo dos pães da proposição, para os prepararem de sábado em sábado.

[[v13-9-33]]

^<<v13-9-33,33>>^ Estes são os cantores, chefes de casas paternas dos levitas, que moravam nas câmaras e estavam isentos de outros serviços, porque de dia e de noite se ocupavam naquele serviço.

[[v13-9-34]]

^<<v13-9-34,34>>^ Estes foram chefes de casas paternas dos levitas, em suas gerações; e estes habitaram em Jerusalém.

[[v13-9-35]]

^<<v13-9-35,35>>^ Em Gibeão habitou Jeiel, pai de Hibeão &#123;e era o nome de sua mulher Maacá&#125;;

[[v13-9-36]]

^<<v13-9-36,36>>^ seu filho primogênito foi Abdom; depois Zur, Quis, Baal, Ner, Nadabe,

[[v13-9-37]]

^<<v13-9-37,37>>^ Gedor, Aiô, Zacarias e Miclote.

[[v13-9-38]]

^<<v13-9-38,38>>^ Miclote foi pai de Simeão; também estes habitaram em Jerusalém defronte d‰ seus irmãos.

[[v13-9-39]]

^<<v13-9-39,39>>^ Ner foi pai de Quis; Quis de Saul; e Saul de Jônatas, Malquisua, Abinadabe e Es-Baal.

[[v13-9-40]]

^<<v13-9-40,40>>^ Filho de Jônatas foi Meribe-Baal; Meribe-Baal foi pai de Mica.

[[v13-9-41]]

^<<v13-9-41,41>>^ Os filhos de Mica: Pitom, Meleque, Tareá, e Acaz.

[[v13-9-42]]

^<<v13-9-42,42>>^ Acaz foi pai de Jará; Jará foi pai de Alemete, Azmavete e Zinri; Zinri foi pai de Moza;

[[v13-9-43]]

^<<v13-9-43,43>>^ Moza foi pai de Bineá, de quem foi filho Refaías, de quem foi filho Eleasá, de quem foi filho Azel.

[[v13-9-44]]

^<<v13-9-44,44>>^ Azel teve seis filhos, cujos nomes são: Azricão, Bocru, Ismael, Searias, Obadias e Hanã; estes foram os filhos de Azel.

'''

xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[&#60; Capítulo Anterior] | <<v13-9-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[Próximo Capítulo &#62;]