include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v13-29-1]]

^<<v13-29-1,1>>^ Disse mais o rei Davi a toda a congregação: Salomão, meu filho, o único a quem Deus escolheu, é ainda moço e tenro, e a obra é grande, porque o palácio não é para homem, mas para o Senhor Deus.

[[v13-29-2]]

^<<v13-29-2,2>>^ Eu, pois, com todas as minhas forças tenho preparado para a casa de meu Deus o ouro para as obras de ouro, a prata para as de prata, o bronze para as de bronze, o ferro para as de ferro e a madeira para as de madeira; pedras de oberilo, pedras de engaste, pedras de ornato, pedras de várias cores, toda sorte de pedras preciosas, e mármore em abundância.

[[v13-29-3]]

^<<v13-29-3,3>>^ Além disso, porque pus o meu afeto na casa de meu Deus, o ouro e prata particular que tenho, eu o dou para a casa do meu Deus, afora tudo quanto tenho preparado para a casa do santuário:

[[v13-29-4]]

^<<v13-29-4,4>>^ três mil talentos de ouro, do ouro de Ofir, e sete mil talentos de prata refinada, para cobrir as paredes das casas;

[[v13-29-5]]

^<<v13-29-5,5>>^ ouro para as obras e ouro, e prata para as de prata, para toda a obra a ser feita por mão de artífices. Quem, pois, está disposto a fazer oferta voluntária, consagrando-se hoje ao Senhor?

[[v13-29-6]]

^<<v13-29-6,6>>^ Então os chefes das casas paternas, os chefes das tribos de Israel, e os chefes de mil e de cem, juntamente com os intendentes da obra do rei, fizeram ofertas voluntárias;

[[v13-29-7]]

^<<v13-29-7,7>>^ e deram para o serviço da casa de Deus cinco mil talentos e dez mil , dracmas de ouro, e dez mil talentos de prata, dezoito mil talentos de bronze, e cem mil talentos de ferro.

[[v13-29-8]]

^<<v13-29-8,8>>^ E os que tinham pedras preciosas deram-nas para o tesouro da casa do Senhor, que estava ao cargo de Jeiel, o gersonita.

[[v13-29-9]]

^<<v13-29-9,9>>^ E o povo se alegrou das ofertas voluntárias que estes fizeram, pois de um coração perfeito as haviam oferecido ao Senhor; e também o rei Davi teve grande alegria.

[[v13-29-10]]

^<<v13-29-10,10>>^ Pelo que Davi bendisse ao Senhor na presença de toda a congregação, dizendo: Bendito és tu, ó Senhor, Deus de nosso pai Israel, de eternidade em eternidade.

[[v13-29-11]]

^<<v13-29-11,11>>^ Tua é, ó Senhor, a grandeza, e o poder, e a glória, e a vitória, e a majestade, porque teu é tudo quanto há no céu e na terra; teu é, ó Senhor, o reino, e tu te exaltaste como chefe sobre todos.

[[v13-29-12]]

^<<v13-29-12,12>>^ Tanto riquezas como honra vêm de ti, tu dominas sobre tudo, e na tua mão há força e poder; na tua mão está o engrandecer e o dar força a tudo.

[[v13-29-13]]

^<<v13-29-13,13>>^ Agora, pois, ó nosso Deus, graças te damos, e louvamos o teu glorioso nome.

[[v13-29-14]]

^<<v13-29-14,14>>^ Mas quem sou eu, e quem é o meu povo, para que pudéssemos fazer ofertas tão voluntariamente? Porque tudo vem de ti, e do que é teu to damos.

[[v13-29-15]]

^<<v13-29-15,15>>^ Porque somos estrangeiros diante de ti e peregrinos, como o foram todos os nossos pais; como a sombra são os nossos dias sobre a terra, e não há permanência:

[[v13-29-16]]

^<<v13-29-16,16>>^ Ó Senhor, Deus nosso, toda esta abundância, que preparamos para te edificar uma casa ao teu santo nome, vem da tua mão, e é toda tua.

[[v13-29-17]]

^<<v13-29-17,17>>^ E bem sei, Deus meu, que tu sondas o coração, e que te agradas da retidão. Na sinceridade de meu coração voluntariamente ofereci todas estas coisas; e agora vi com alegria que o teu povo, que se acha aqui, ofereceu voluntariamente.

[[v13-29-18]]

^<<v13-29-18,18>>^ O Senhor, Deus de nossos pais Abraão, Isaque e Israel, conserva para sempre no coração do teu povo estas disposições e estes pensamentos, e encaminha o seu coração para ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ E a Salomão, meu filho, dá um coração perfeito, para guardar os teus mandamentos, os teus testemunhes e os teus estatuto, e para fazer todas estas coisas, e para edificar o palácio para o qual tenha providenciado.

[[v13-29-20]]

^<<v13-29-20,20>>^ Então disse Davi a toda a congregação: Bendizei ao Senhor vosso Deus! E toda a congregação bendisse ao Senhor Deus de seus pais, e inclinaram-se e prostraram-se perante a Senhor e perante o rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ E no dia seguinte imolaram sacrifícios ao Senhor e lhe ofereceram em holocausto mil novilhos, mil carneiros, mil cordeiros, com as suas libações, e sacrifícios em abundância a favor de todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ E comeram e beberam naquele dia perante o Senhor, com grande gozo. E pela segunda vez proclamaram rei a Salomão, filho de Davi, e o ungiram ao Senhor para ser príncipe, e a Zadoque para ser sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ Assim Salomão se assentou no trono do Senhor, como rei em lugar de seu pai Davi, e prosperou; e todo o Israel lhe prestou obediência.

[[v13-29-24]]

^<<v13-29-24,24>>^ E todos os chefes, e os homens poderosos, e também todos os filhos do rei Davi se submeteram ao rei Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ E o Senhor engrandeceu muito a Salomão à vista de todo o Israel, e deu-lhe tal majestade real qual antes dele não teve nenhum rei em Israel.

[[v13-29-26]]

^<<v13-29-26,26>>^ Assim Davi, filho de Jessé, reinou sobre todo o Israel.

[[v13-29-27]]

^<<v13-29-27,27>>^ O tempo que reinou sobre Israel foi quarenta anos; em Hebrom reinou sete anos, e em Jerusalém trinta e três.

[[v13-29-28]]

^<<v13-29-28,28>>^ E morreu numa boa velhice, cheio de dias, riquezas e honra; e Salomão, seu filho, reinou em seu lugar.

[[v13-29-29]]

^<<v13-29-29,29>>^ Ora, os atos do rei Davi, desde os primeiros até os últimos, estão escritos nas crônicas de Samuel, o vidente, e nas crônicas do profeta Natã, e nas crônicas de Gade, o vidente,

[[v13-29-30]]

^<<v13-29-30,30>>^ com todo o seu reinado e o seu poder e os acontecimentos que sobrevieram a ele, a Israel, e a todos os reinos daquelas terras.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]