include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v59-3-1]]

^<<v59-3-1,1>>^ Meus irmãos, não sejais muitos de vós mestres, sabendo que receberemos um juízo mais severo.

[[v59-3-2]]

^<<v59-3-2,2>>^ Todos tropeçamos em muitas coisas. Se alguém não tropeça em palavra, esse é homem perfeito, e capaz de refrear também todo o corpo.

[[v59-3-3]]

^<<v59-3-3,3>>^ Ora, se pomos freios na boca dos cavalos, para que nos obedeçam, então conseguimos dirigir todo o seu corpo.

[[v59-3-4]]

^<<v59-3-4,4>>^ Vede também os navios que, embora tão grandes e levados por impetuosos ventos, com um pequenino leme se voltam para onde quer o impulso do timoneiro.

[[v59-3-5]]

^<<v59-3-5,5>>^ Assim também a língua é um pequeno membro, e se gaba de grandes coisas. Vede quão grande bosque um tão pequeno fogo incendeia.

[[v59-3-6]]

^<<v59-3-6,6>>^ A língua também é um fogo; sim, a língua, qual mundo de iniqüidade, colocada entre os nossos membros, contamina todo o corpo, e inflama o curso da natureza, sendo por sua vez inflamada pelo inferno.

[[v59-3-7]]

^<<v59-3-7,7>>^ Pois toda espécie tanto de feras, como de aves, tanto de répteis como de animais do mar, se doma, e tem sido domada pelo gênero humano,

[[v59-3-8]]

^<<v59-3-8,8>>^ mas a língua, nenhum homem a pode domar. É um mal irrefreável; está cheia de peçonha mortal.

[[v59-3-9]]

^<<v59-3-9,9>>^ Com ela bendizemos ao Senhor e Pai, e com ela amaldiçoamos os homens, feitos à semelhança de Deus.

[[v59-3-10]]

^<<v59-3-10,10>>^ Da mesma boca procede bênção e maldição. Não convém, meus irmãos, que se faça assim.

[[v59-3-11]]

^<<v59-3-11,11>>^ Porventura a fonte deita da mesma abertura água doce e água amargosa?

[[v59-3-12]]

^<<v59-3-12,12>>^ Meus irmãos, pode acaso uma figueira produzir azeitonas, ou uma videira figos? Nem tampouco pode uma fonte de água salgada dar água doce.

[[v59-3-13]]

^<<v59-3-13,13>>^ Quem dentre vós é sábio e entendido? Mostre pelo seu bom procedimento as suas obras em mansidão de sabedoria.

[[v59-3-14]]

^<<v59-3-14,14>>^ Mas, se tendes amargo ciúme e sentimento faccioso em vosso coração, não vos glorieis, nem mintais contra a verdade.

[[v59-3-15]]

^<<v59-3-15,15>>^ Essa não é a sabedoria que vem do alto, mas é terrena, animal e diabólica.

[[v59-3-16]]

^<<v59-3-16,16>>^ Porque onde há ciúme e sentimento faccioso, aí há confusão e toda obra má.

[[v59-3-17]]

^<<v59-3-17,17>>^ Mas a sabedoria que vem do alto é, primeiramente, pura, depois pacífica, moderada, tratável, cheia de misericórdia e de bons frutos, sem parcialidade, e sem hipocrisia.

[[v59-3-18]]

^<<v59-3-18,18>>^ Ora, o fruto da justiça semeia-se em paz para aqueles que promovem a paz.

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]