include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v59-5-1]]

^<<v59-5-1,1>>^ E agora, vós ricos, chorai e pranteai, por causa das desgraças que vos sobrevirão.

[[v59-5-2]]

^<<v59-5-2,2>>^ As vossas riquezas estão apodrecidas, e as vossas vestes estão roídas pela traça.

[[v59-5-3]]

^<<v59-5-3,3>>^ O vosso ouro e a vossa prata estão enferrujados; e a sua ferrugem dará testemunho contra vós, e devorará as vossas carnes como fogo. Entesourastes para os últimos dias.

[[v59-5-4]]

^<<v59-5-4,4>>^ Eis que o salário que fraudulentamente retivestes aos trabalhadores que ceifaram os vossos campos clama, e os clamores dos ceifeiros têm chegado aos ouvidos do Senhor dos exércitos.

[[v59-5-5]]

^<<v59-5-5,5>>^ Deliciosamente vivestes sobre a terra, e vos deleitastes; cevastes os vossos corações no dia da matança.

[[v59-5-6]]

^<<v59-5-6,6>>^ Condenastes e matastes o justo; ele não vos resiste.

[[v59-5-7]]

^<<v59-5-7,7>>^ Portanto, irmãos, sede pacientes até a vinda do Senhor. Eis que o lavrador espera o precioso fruto da terra, aguardando-o com paciência, até que receba as primeiras e as últimas chuvas.

[[v59-5-8]]

^<<v59-5-8,8>>^ Sede vós também pacientes; fortalecei os vossos corações, porque a vinda do Senhor está próxima.

[[v59-5-9]]

^<<v59-5-9,9>>^ Não vos queixeis, irmãos, uns dos outros, para que não sejais julgados. Eis que o juiz está à porta.

[[v59-5-10]]

^<<v59-5-10,10>>^ Irmãos, tomai como exemplo de sofrimento e paciência os profetas que falaram em nome do Senhor.

[[v59-5-11]]

^<<v59-5-11,11>>^ Eis que chamamos bem-aventurados os que suportaram aflições. Ouvistes da paciência de Jó, e vistes o fim que o Senhor lhe deu, porque o Senhor é cheio de misericórdia e compaixão.

[[v59-5-12]]

^<<v59-5-12,12>>^ Mas, sobretudo, meus irmãos, não jureis, nem pelo céu, nem pela terra, nem façais qualquer outro juramento; seja, porém, o vosso sim, sim, e o vosso não, não, para não cairdes em condenação.

[[v59-5-13]]

^<<v59-5-13,13>>^ Está aflito alguém entre vós? Ore. Está alguém contente? Cante louvores.

[[v59-5-14]]

^<<v59-5-14,14>>^ Está doente algum de vós? Chame os anciãos da igreja, e estes orem sobre ele, ungido-o com óleo em nome do Senhor;

[[v59-5-15]]

^<<v59-5-15,15>>^ e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.

[[v59-5-16]]

^<<v59-5-16,16>>^ Confessai, portanto, os vossos pecados uns aos outros, e orai uns pelos outros, para serdes curados. A súplica de um justo pode muito na sua atuação.

[[v59-5-17]]

^<<v59-5-17,17>>^ Elias era homem sujeito às mesmas paixões que nós, e orou com fervor para que não chovesse, e por três anos e seis meses não choveu sobre a terra.

[[v59-5-18]]

^<<v59-5-18,18>>^ E orou outra vez e o céu deu chuva, e a terra produziu o seu fruto.

[[v59-5-19]]

^<<v59-5-19,19>>^ Meus irmãos, se alguém dentre vós se desviar da verdade e alguém o converter,

[[v59-5-20]]

^<<v59-5-20,20>>^ sabei que aquele que fizer converter um pecador do erro do seu caminho salvará da morte uma alma, e cobrirá uma multidão de pecados.

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]