include::./index.adoc[]

[[v59-2-0]]
=== Tiago, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v59-2-1]]

^<<v59-2-1,1>>^ Meus irmãos, não tenhais a fé em nosso Senhor Jesus Cristo, Senhor da glória, em acepção de pessoas.

[[v59-2-2]]

^<<v59-2-2,2>>^ Porque, se entrar na vossa reunião algum homem com anel de ouro no dedo e com traje esplêndido, e entrar também algum pobre com traje sórdido.

[[v59-2-3]]

^<<v59-2-3,3>>^ e atentardes para o que vem com traje esplêndido e lhe disserdes: Senta-te aqui num lugar de honra; e disserdes ao pobre: Fica em pé, ou senta-te abaixo do escabelo dos meus pés,

[[v59-2-4]]

^<<v59-2-4,4>>^ não fazeis, porventura, distinção entre vós mesmos e não vos tornais juizes movidos de maus pensamentos?

[[v59-2-5]]

^<<v59-2-5,5>>^ Ouvi, meus amados irmãos. Não escolheu Deus os que são pobres quanto ao mundo para fazê-los ricos na fé e herdeiros do reino que prometeu aos que o amam?

[[v59-2-6]]

^<<v59-2-6,6>>^ Mas vós desonrastes o pobre. Porventura não são os ricos os que vos oprimem e os que vos arrastam aos tribunais?

[[v59-2-7]]

^<<v59-2-7,7>>^ Não blasfemam eles o bom nome pelo qual sois chamados?

[[v59-2-8]]

^<<v59-2-8,8>>^ Todavia, se estais cumprindo a lei real segundo a escritura: Amarás ao teu próximo como a ti mesmo, fazeis bem.

[[v59-2-9]]

^<<v59-2-9,9>>^ Mas se fazeis acepção de pessoas, cometeis pecado, sendo por isso condenados pela lei como transgressores.

[[v59-2-10]]

^<<v59-2-10,10>>^ Pois qualquer que guardar toda a lei, mas tropeçar em um só ponto, tem-se tornado culpado de todos.

[[v59-2-11]]

^<<v59-2-11,11>>^ Porque o mesmo que disse: Não adulterarás, também disse: Não matarás. Ora, se não cometes adultério, mas és homicida, te hás tornado transgressor da lei.

[[v59-2-12]]

^<<v59-2-12,12>>^ Falai de tal maneira e de tal maneira procedei, como havendo de ser julgados pela lei da liberdade.

[[v59-2-13]]

^<<v59-2-13,13>>^ Porque o juízo será sem misericórdia para aquele que não usou de misericórdia; a misericórdia triunfa sobre o juízo.

[[v59-2-14]]

^<<v59-2-14,14>>^ Que proveito há, meus irmãos se alguém disser que tem fé e não tiver obras? Porventura essa fé pode salvá-lo?

[[v59-2-15]]

^<<v59-2-15,15>>^ Se um irmão ou uma irmã estiverem nus e tiverem falta de mantimento cotidiano,

[[v59-2-16]]

^<<v59-2-16,16>>^ e algum de vós lhes disser: Ide em paz, aquentai-vos e fartai-vos; e não lhes derdes as coisas necessárias para o corpo, que proveito há nisso?

[[v59-2-17]]

^<<v59-2-17,17>>^ Assim também a fé, se não tiver obras, é morta em si mesma.

[[v59-2-18]]

^<<v59-2-18,18>>^ Mas dirá alguém: Tu tens fé, e eu tenho obras; mostra-me a tua fé sem as obras, e eu te mostrarei a minha fé pelas minhas obras.

[[v59-2-19]]

^<<v59-2-19,19>>^ Crês tu que Deus é um só? Fazes bem; os demônios também o crêem, e estremecem.

[[v59-2-20]]

^<<v59-2-20,20>>^ Mas queres saber, ó homem insensato, que a fé sem as obras é inútil?

[[v59-2-21]]

^<<v59-2-21,21>>^ Porventura não foi pelas obras que nosso pai Abraão foi justificado quando ofereceu sobre o altar seu filho Isaque?

[[v59-2-22]]

^<<v59-2-22,22>>^ Vês que a fé cooperou com as suas obras, e que pelas obras a fé foi aperfeiçoada.

[[v59-2-23]]

^<<v59-2-23,23>>^ E se cumpriu a escritura que diz: E creu Abraão em Deus, e isso lhe foi imputado como justiça, e foi chamado amigo de Deus.

[[v59-2-24]]

^<<v59-2-24,24>>^ Vedes então que é pelas obras que o homem é justificado, e não somente pela fé.

[[v59-2-25]]

^<<v59-2-25,25>>^ E de igual modo não foi a meretriz Raabe também justificada pelas obras, quando acolheu os espias, e os fez sair por outro caminho?

[[v59-2-26]]

^<<v59-2-26,26>>^ Porque, assim como o corpo sem o espírito está morto, assim também a fé sem obras é morta.

'''

xref:059-tiago/059-tiago-001.adoc#v59-1-0[&#60; Capítulo Anterior] | <<v59-2-0,Topo>> | xref:059-tiago/059-tiago-003.adoc#v59-3-0[Próximo Capítulo &#62;]