include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v59-4-1]]

^<<v59-4-1,1>>^ Donde vêm as guerras e contendas entre vós? Porventura não vêm disto, dos vossos deleites, que nos vossos membros guerreiam?

[[v59-4-2]]

^<<v59-4-2,2>>^ Cobiçais e nada tendes; logo matais. Invejais, e não podeis alcançar; logo combateis e fazeis guerras. Nada tendes, porque não pedis.

[[v59-4-3]]

^<<v59-4-3,3>>^ Pedis e não recebeis, porque pedis mal, para o gastardes em vossos deleites.

[[v59-4-4]]

^<<v59-4-4,4>>^ Infiéis, não sabeis que a amizade do mundo é inimizade contra Deus? Portanto qualquer que quiser ser amigo do mundo constitui-se inimigo de Deus.

[[v59-4-5]]

^<<v59-4-5,5>>^ Ou pensais que em vão diz a escritura: O Espírito que ele fez habitar em nós anseia por nós até o ciúme?

[[v59-4-6]]

^<<v59-4-6,6>>^ Todavia, dá maior graça. Portanto diz: Deus resiste aos soberbos; dá, porém, graça aos humildes.

[[v59-4-7]]

^<<v59-4-7,7>>^ Sujeitai-vos, pois, a Deus; mas resisti ao Diabo, e ele fugirá de vós.

[[v59-4-8]]

^<<v59-4-8,8>>^ Chegai-vos para Deus, e ele se chegará para vós. Limpai as mãos, pecadores; e, vós de espírito vacilante, purificai os corações.

[[v59-4-9]]

^<<v59-4-9,9>>^ Senti as vossas misérias, lamentai e chorai; torne-se o vosso riso em pranto, e a vossa alegria em tristeza.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhai-vos perante o Senhor, e ele vos exaltará.

[[v59-4-11]]

^<<v59-4-11,11>>^ Irmãos, não faleis mal uns dos outros. Quem fala mal de um irmão, e julga a seu irmão, fala mal da lei, e julga a lei; ora, se julgas a lei, não és observador da lei, mas juiz.

[[v59-4-12]]

^<<v59-4-12,12>>^ Há um só legislador e juiz, aquele que pode salvar e destruir; tu, porém, quem és, que julgas ao próximo?

[[v59-4-13]]

^<<v59-4-13,13>>^ E agora, vós que dizeis: Hoje ou amanhã iremos a tal cidade, lá passaremos um ano, negociaremos e ganharemos.

[[v59-4-14]]

^<<v59-4-14,14>>^ No entanto, não sabeis o que sucederá amanhã. Que é a vossa vida? Sois um vapor que aparece por um pouco, e logo se desvanece.

[[v59-4-15]]

^<<v59-4-15,15>>^ Em lugar disso, devíeis dizer: Se o Senhor quiser, viveremos e faremos isto ou aquilo.

[[v59-4-16]]

^<<v59-4-16,16>>^ Mas agora vos jactais das vossas presunções; toda jactância tal como esta é maligna.

[[v59-4-17]]

^<<v59-4-17,17>>^ Aquele, pois, que sabe fazer o bem e não o faz, comete pecado.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]