include::./index.adoc[]

[[v59-1-0]]
=== Tiago, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v59-1-1]]

^<<v59-1-1,1>>^ Tiago, servo de Deus e do Senhor Jesus Cristo, às doze tribos da Dispersão, saúde.

[[v59-1-2]]

^<<v59-1-2,2>>^ Meus irmãos, tende por motivo de grande gozo o passardes por várias provações,

[[v59-1-3]]

^<<v59-1-3,3>>^ sabendo que a aprovação da vossa fé produz a perseverança;

[[v59-1-4]]

^<<v59-1-4,4>>^ e a perseverança tenha a sua obra perfeita, para que sejais perfeitos e completos, não faltando em coisa alguma.

[[v59-1-5]]

^<<v59-1-5,5>>^ Ora, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não censura, e ser-lhe-á dada.

[[v59-1-6]]

^<<v59-1-6,6>>^ Peça-a, porém, com fé, não duvidando; pois aquele que duvida é semelhante à onda do mar, que é sublevada e agitada pelo vento.

[[v59-1-7]]

^<<v59-1-7,7>>^ Não pense tal homem que receberá do Senhor alguma coisa,

[[v59-1-8]]

^<<v59-1-8,8>>^ homem vacilante que é, e inconstante em todos os seus caminhos.

[[v59-1-9]]

^<<v59-1-9,9>>^ Mas o irmão de condição humilde glorie-se na sua exaltação,

[[v59-1-10]]

^<<v59-1-10,10>>^ e o rico no seu abatimento; porque ele passará como a flor da erva.

[[v59-1-11]]

^<<v59-1-11,11>>^ Pois o sol se levanta em seu ardor e faz secar a erva; a sua flor cai e a beleza do seu aspecto perece; assim murchará também o rico em seus caminhos.

[[v59-1-12]]

^<<v59-1-12,12>>^ Bem-aventurado o homem que suporta a provação; porque, depois de aprovado, receberá a coroa da vida, que o Senhor prometeu aos que o amam.

[[v59-1-13]]

^<<v59-1-13,13>>^ Ninguém, sendo tentado, diga: Sou tentado por Deus; porque Deus não pode ser tentado pelo mal e ele a ninguém tenta.

[[v59-1-14]]

^<<v59-1-14,14>>^ Cada um, porém, é tentado, quando atraído e engodado pela sua própria concupiscência;

[[v59-1-15]]

^<<v59-1-15,15>>^ então a concupiscência, havendo concebido, dá à luz o pecado; e o pecado, sendo consumado, gera a morte.

[[v59-1-16]]

^<<v59-1-16,16>>^ Não vos enganeis, meus amados irmãos.

[[v59-1-17]]

^<<v59-1-17,17>>^ Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança nem sombra de variação.

[[v59-1-18]]

^<<v59-1-18,18>>^ Segundo a sua própria vontade, ele nos gerou pela palavra da verdade, para que fôssemos como que primícias das suas criaturas.

[[v59-1-19]]

^<<v59-1-19,19>>^ Sabei isto, meus amados irmãos: Todo homem seja pronto para ouvir, tardio para falar e tardio para se irar.

[[v59-1-20]]

^<<v59-1-20,20>>^ Porque a ira do homem não opera a justiça de Deus.

[[v59-1-21]]

^<<v59-1-21,21>>^ Pelo que, despojando-vos de toda sorte de imundícia e de todo vestígio do mal, recebei com mansidão a palavra em vós implantada, a qual é poderosa para salvar as vossas almas.

[[v59-1-22]]

^<<v59-1-22,22>>^ E sede cumpridores da palavra e não somente ouvintes, enganando-vos a vós mesmos.

[[v59-1-23]]

^<<v59-1-23,23>>^ Pois se alguém é ouvinte da palavra e não cumpridor, é semelhante a um homem que contempla no espelho o seu rosto natural;

[[v59-1-24]]

^<<v59-1-24,24>>^ porque se contempla a si mesmo e vai-se, e logo se esquece de como era.

[[v59-1-25]]

^<<v59-1-25,25>>^ Entretanto aquele que atenta bem para a lei perfeita, a da liberdade, e nela persevera, não sendo ouvinte esquecido, mas executor da obra, este será bem-aventurado no que fizer.

[[v59-1-26]]

^<<v59-1-26,26>>^ Se alguém cuida ser religioso e não refreia a sua língua, mas engana o seu coração, a sua religião é vã.

[[v59-1-27]]

^<<v59-1-27,27>>^ A religião pura e imaculada diante de nosso Deus e Pai é esta: Visitar os órfãos e as viúvas nas suas aflições e guardar-se isento da corrupção do mundo.

'''

xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-tiago/059-tiago-002.adoc#v59-2-0[Próximo Capítulo &#62;]