include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v56-1-1]]

^<<v56-1-1,1>>^ Paulo, servo de Deus, e apóstolo de Jesus Cristo, segundo a fé dos eleitos de Deus, e o pleno conhecimento da verdade que é segundo a piedade,

[[v56-1-2]]

^<<v56-1-2,2>>^ na esperança da vida eterna, a qual Deus, que não pode mentir, prometeu antes dos tempos eternos,

[[v56-1-3]]

^<<v56-1-3,3>>^ e no tempo próprio manifestou a sua palavra, mediante a pregação que me foi confiada segundo o mandamento de Deus, nosso Salvador;

[[v56-1-4]]

^<<v56-1-4,4>>^ a Tito, meu verdadeiro filho segundo a fé que nos é comum, graça e paz da parte de Deus Pai, e de Cristo Jesus, nosso Salvador.

[[v56-1-5]]

^<<v56-1-5,5>>^ Por esta causa te deixei em Creta, para que pusesses em boa ordem o que ainda não o está, e que em cada cidade estabelecesses anciãos, como já te mandei;

[[v56-1-6]]

^<<v56-1-6,6>>^ alguém que seja irrepreensível, marido de uma só mulher, tendo filhos crentes que não sejam acusados de dissolução, nem sejam desobedientes.

[[v56-1-7]]

^<<v56-1-7,7>>^ Pois é necessário que o bispo seja irrepreensível, como despenseiro de Deus, não soberbo, nem irascível, nem dado ao vinho, nem espancador, nem cobiçoso de torpe ganância;

[[v56-1-8]]

^<<v56-1-8,8>>^ mas hospitaleiro, amigo do bem, sóbrio, justo, piedoso, temperante;

[[v56-1-9]]

^<<v56-1-9,9>>^ retendo firme a palavra fiel, que é conforme a doutrina, para que seja poderoso, tanto para exortar na sã doutrina como para convencer os contradizentes.

[[v56-1-10]]

^<<v56-1-10,10>>^ Porque há muitos insubordinados, faladores vãos, e enganadores, especialmente os da circuncisão,

[[v56-1-11]]

^<<v56-1-11,11>>^ aos quais é preciso tapar a boca; porque transtornam casas inteiras ensinando o que não convém, por torpe ganância.

[[v56-1-12]]

^<<v56-1-12,12>>^ Um dentre eles, seu próprio profeta, disse: Os cretenses são sempre mentirosos, bestas ruins, glutões preguiçosos.

[[v56-1-13]]

^<<v56-1-13,13>>^ Este testemunho é verdadeiro. Portanto repreende-os severamente, para que sejam são na fé,

[[v56-1-14]]

^<<v56-1-14,14>>^ não dando ouvidos a fábulas judaicas, nem a mandamentos de homens que se desviam da verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Tudo é puro para os que são puros, mas para os corrompidos e incrédulos nada é puro; antes tanto a sua mente como a sua consciência estão contaminadas.

[[v56-1-16]]

^<<v56-1-16,16>>^ Afirmam que conhecem a Deus, mas pelas suas obras o negam, sendo abomináveis, e desobedientes, e réprobos para toda boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]