include::./index.adoc[]

[[v56-2-0]]
=== Tito, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v56-2-1]]

^<<v56-2-1,1>>^ Tu, porém, fala o que convém à sã doutrina.

[[v56-2-2]]

^<<v56-2-2,2>>^ Exorta os velhos a que sejam temperantes, sérios, sóbrios, sãos na fé, no amor, e na constância;

[[v56-2-3]]

^<<v56-2-3,3>>^ as mulheres idosas, semelhantemente, que sejam reverentes no seu viver, não caluniadoras, não dadas a muito vinho, mestras do bem,

[[v56-2-4]]

^<<v56-2-4,4>>^ para que ensinem as mulheres novas a amarem aos seus maridos e filhos,

[[v56-2-5]]

^<<v56-2-5,5>>^ a serem moderadas, castas, operosas donas de casa, bondosas, submissas a seus maridos, para que a palavra de Deus não seja blasfemada.

[[v56-2-6]]

^<<v56-2-6,6>>^ Exorta semelhantemente os moços a que sejam moderados.

[[v56-2-7]]

^<<v56-2-7,7>>^ Em tudo te dá por exemplo de boas obras; na doutrina mostra integridade, sobriedade,

[[v56-2-8]]

^<<v56-2-8,8>>^ linguagem sã e irrepreensível, para que o adversário se confunda, não tendo nenhum mal que dizer de nós.

[[v56-2-9]]

^<<v56-2-9,9>>^ Exorta os servos a que sejam submissos a seus senhores em tudo, sendo-lhes agradáveis, não os contradizendo

[[v56-2-10]]

^<<v56-2-10,10>>^ nem defraudando, antes mostrando perfeita lealdade, para que em tudo sejam ornamento da doutrina de Deus nosso Salvador.

[[v56-2-11]]

^<<v56-2-11,11>>^ Porque a graça de Deus se manifestou, trazendo salvação a todos os homens,

[[v56-2-12]]

^<<v56-2-12,12>>^ ensinando-nos, para que, renunciando à impiedade e às paixões mundanas, vivamos no presente mundo sóbria, e justa, e piamente,

[[v56-2-13]]

^<<v56-2-13,13>>^ aguardando a bem-aventurada esperança e o aparecimento da glória do nosso grande Deus e Salvador Cristo Jesus,

[[v56-2-14]]

^<<v56-2-14,14>>^ que se deu a si mesmo por nós para nos remir de toda a iniqüidade, e purificar para si um povo todo seu, zeloso de boas obras.

[[v56-2-15]]

^<<v56-2-15,15>>^ Fala estas coisas, exorta e repreende com toda autoridade. Ninguém te despreze.

'''

xref:056-tito/056-tito-001.adoc#v56-1-0[&#60; Capítulo Anterior] | <<v56-2-0,Topo>> | xref:056-tito/056-tito-003.adoc#v56-3-0[Próximo Capítulo &#62;]