include::./index.adoc[]

[[v62-2-0]]
=== 1 João, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v62-2-1]]

^<<v62-2-1,1>>^ Meus filhinhos, estas coisas vos escrevo, para que não pequeis; mas, se alguém pecar, temos um Advogado para com o Pai, Jesus Cristo, o justo.

[[v62-2-2]]

^<<v62-2-2,2>>^ E ele é a propiciação pelos nossos pecados, e não somente pelos nossos, mas também pelos de todo o mundo.

[[v62-2-3]]

^<<v62-2-3,3>>^ E nisto sabemos que o conhecemos; se guardamos os seus mandamentos.

[[v62-2-4]]

^<<v62-2-4,4>>^ Aquele que diz: Eu o conheço, e não guarda os seus mandamentos, é mentiroso, e nele não está a verdade;

[[v62-2-5]]

^<<v62-2-5,5>>^ mas qualquer que guarda a sua palavra, nele realmente se tem aperfeiçoado o amor de Deus. E nisto sabemos que estamos nele;

[[v62-2-6]]

^<<v62-2-6,6>>^ aquele que diz estar nele, também deve andar como ele andou.

[[v62-2-7]]

^<<v62-2-7,7>>^ Amados, não vos escrevo mandamento novo, mas um mandamento antigo, que tendes desde o princípio. Este mandamento antigo é a palavra que ouvistes.

[[v62-2-8]]

^<<v62-2-8,8>>^ Contudo é um novo mandamento que vos escrevo, o qual é verdadeiro nele e em vós; porque as trevas vão passando, e já brilha a verdadeira luz.

[[v62-2-9]]

^<<v62-2-9,9>>^ Aquele que diz estar na luz, e odeia a seu irmão, até agora está nas trevas.

[[v62-2-10]]

^<<v62-2-10,10>>^ Aquele que ama a seu irmão permanece na luz, e nele não há tropeço.

[[v62-2-11]]

^<<v62-2-11,11>>^ Mas aquele que odeia a seu irmão está nas trevas, e anda nas trevas, e não sabe para onde vai; porque as trevas lhe cegaram os olhos.

[[v62-2-12]]

^<<v62-2-12,12>>^ Filhinhos, eu vos escrevo, porque os vossos pecados são perdoados por amor do seu nome.

[[v62-2-13]]

^<<v62-2-13,13>>^ Pais, eu vos escrevo, porque conheceis aquele que é desde o princípio. Jovens, eu vos escrevo, porque vencestes o Maligno.

[[v62-2-14]]

^<<v62-2-14,14>>^ Eu vos escrevi, meninos, porque conheceis o Pai. Eu vos escrevi, pais, porque conheceis aquele que é desde o princípio. Eu escrevi, jovens, porque sois fortes, e a palavra de Deus permanece em vós, e já vencestes o Maligno.

[[v62-2-15]]

^<<v62-2-15,15>>^ Não ameis o mundo, nem o que há no mundo. Se alguém ama o mundo, o amor do Pai não está nele.

[[v62-2-16]]

^<<v62-2-16,16>>^ Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não vem do Pai, mas sim do mundo.

[[v62-2-17]]

^<<v62-2-17,17>>^ Ora, o mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus, permanece para sempre.

[[v62-2-18]]

^<<v62-2-18,18>>^ Filhinhos, esta é a última hora; e, conforme ouvistes que vem o anticristo, já muitos anticristos se têm levantado; por onde conhecemos que é a última hora.

[[v62-2-19]]

^<<v62-2-19,19>>^ Saíram dentre nós, mas não eram dos nossos; porque, se fossem dos nossos, teriam permanecido conosco; mas todos eles saíram para que se manifestasse que não são dos nossos.

[[v62-2-20]]

^<<v62-2-20,20>>^ Ora, vós tendes a unção da parte do Santo, e todos tendes conhecimento.

[[v62-2-21]]

^<<v62-2-21,21>>^ Não vos escrevi porque não soubésseis a verdade, mas porque a sabeis, e porque nenhuma mentira vem da verdade.

[[v62-2-22]]

^<<v62-2-22,22>>^ Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Esse mesmo é o anticristo, esse que nega o Pai e o Filho.

[[v62-2-23]]

^<<v62-2-23,23>>^ Qualquer que nega o Filho, também não tem o Pai; aquele que confessa o Filho, tem também o Pai.

[[v62-2-24]]

^<<v62-2-24,24>>^ Portanto, o que desde o princípio ouvistes, permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também vós permanecereis no Filho e no Pai.

[[v62-2-25]]

^<<v62-2-25,25>>^ E esta é a promessa que ele nos fez: a vida eterna.

[[v62-2-26]]

^<<v62-2-26,26>>^ Estas coisas vos escrevo a respeito daqueles que vos querem enganar.

[[v62-2-27]]

^<<v62-2-27,27>>^ E quanto a vós, a unção que dele recebestes fica em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina a respeito de todas as coisas, e é verdadeira, e não é mentira, como vos ensinou ela, assim nele permanecei.

[[v62-2-28]]

^<<v62-2-28,28>>^ E agora, filhinhos, permanecei nele; para que, quando ele se manifestar, tenhamos confiança, e não fiquemos confundidos diante dele na sua vinda.

[[v62-2-29]]

^<<v62-2-29,29>>^ Se sabeis que ele é justo, sabeis que todo aquele que pratica a justiça é nascido dele.

'''

xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[&#60; Capítulo Anterior] | <<v62-2-0,Topo>> | xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[Próximo Capítulo &#62;]