include::./index.adoc[]

[[v62-3-0]]
=== 1 João, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v62-3-1]]

^<<v62-3-1,1>>^ Vede que grande amor nos tem concedido o Pai: que fôssemos chamados filhos de Deus; e nós o somos. Por isso o mundo não nos conhece; porque não conheceu a ele.

[[v62-3-2]]

^<<v62-3-2,2>>^ Amados, agora somos filhos de Deus, e ainda não é manifesto o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é, o veremos.

[[v62-3-3]]

^<<v62-3-3,3>>^ E todo o que nele tem esta esperança, purifica-se a si mesmo, assim como ele é puro.

[[v62-3-4]]

^<<v62-3-4,4>>^ Todo aquele que vive habitualmente no pecado também vive na rebeldia, pois o pecado é rebeldia.

[[v62-3-5]]

^<<v62-3-5,5>>^ E bem sabeis que ele se manifestou para tirar os pecados; e nele não há pecado.

[[v62-3-6]]

^<<v62-3-6,6>>^ Todo o que permanece nele não vive pecando; todo o que vive pecando não o viu nem o conhece.

[[v62-3-7]]

^<<v62-3-7,7>>^ Filhinhos, ninguém vos engane; quem pratica a justiça é justo, assim como ele é justo;

[[v62-3-8]]

^<<v62-3-8,8>>^ quem comete pecado é do Diabo; porque o Diabo peca desde o princípio. Para isto o Filho de Deus se manifestou: para destruir as obras do Diabo.

[[v62-3-9]]

^<<v62-3-9,9>>^ Aquele que é nascido de Deus não peca habitualmente; porque a semente de Deus permanece nele, e não pode continuar no pecado, porque é nascido de Deus.

[[v62-3-10]]

^<<v62-3-10,10>>^ Nisto são manifestos os filhos de Deus, e os filhos do Diabo: quem não pratica a justiça não é de Deus, nem o que não ama a seu irmão.

[[v62-3-11]]

^<<v62-3-11,11>>^ Porque esta é a mensagem que ouvistes desde o princípio, que nos amemos uns aos outros,

[[v62-3-12]]

^<<v62-3-12,12>>^ não sendo como Caim, que era do Maligno, e matou a seu irmão. E por que o matou? Porque as suas obras eram más e as de seu irmão justas.

[[v62-3-13]]

^<<v62-3-13,13>>^ Meus irmãos, não vos admireis se o mundo vos odeia.

[[v62-3-14]]

^<<v62-3-14,14>>^ Nós sabemos que já passamos da morte para a vida, porque amamos os irmãos. Quem não ama permanece na morte.

[[v62-3-15]]

^<<v62-3-15,15>>^ Todo o que odeia a seu irmão é homicida; e vós sabeis que nenhum homicida tem a vida eterna permanecendo nele.

[[v62-3-16]]

^<<v62-3-16,16>>^ Nisto conhecemos o amor: que Cristo deu a sua vida por nós; e nós devemos dar a vida pelos irmãos.

[[v62-3-17]]

^<<v62-3-17,17>>^ Quem, pois, tiver bens do mundo, e, vendo o seu irmão necessitando, lhe fechar o seu coração, como permanece nele o amor de Deus?

[[v62-3-18]]

^<<v62-3-18,18>>^ Filhinhos, não amemos de palavra, nem de língua, mas por obras e em verdade.

[[v62-3-19]]

^<<v62-3-19,19>>^ Nisto conheceremos que somos da verdade, e diante dele tranqüilizaremos o nosso coração;

[[v62-3-20]]

^<<v62-3-20,20>>^ porque se o coração nos condena, maior é Deus do que o nosso coração, e conhece todas as coisas.

[[v62-3-21]]

^<<v62-3-21,21>>^ Amados, se o coração não nos condena, temos confiança para com Deus;

[[v62-3-22]]

^<<v62-3-22,22>>^ e qualquer coisa que lhe pedirmos, dele a receberemos, porque guardamos os seus mandamentos, e fazemos o que é agradável à sua vista.

[[v62-3-23]]

^<<v62-3-23,23>>^ Ora, o seu mandamento é este, que creiamos no nome de seu Filho Jesus Cristo, e nos amemos uns aos outros, como ele nos ordenou.

[[v62-3-24]]

^<<v62-3-24,24>>^ Quem guarda os seus mandamentos, em Deus permanece e Deus nele. E nisto conhecemos que ele permanece em nós: pelo Espírito que nos tem dado.

'''

xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[Próximo Capítulo &#62;]