include::./index.adoc[]

[[v62-4-0]]
=== 1 João, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v62-4-1]]

^<<v62-4-1,1>>^ Amados, não creiais a todo espírito, mas provai se os espíritos vêm de Deus; porque muitos falsos profetas têm saído pelo mundo.

[[v62-4-2]]

^<<v62-4-2,2>>^ Nisto conheceis o Espírito de Deus: todo espírito que confessa que Jesus Cristo veio em carne é de Deus;

[[v62-4-3]]

^<<v62-4-3,3>>^ e todo espírito que não confessa a Jesus não é de Deus; mas é o espírito do anticristo, a respeito do qual tendes ouvido que havia de vir; e agora já está no mundo.

[[v62-4-4]]

^<<v62-4-4,4>>^ Filhinhos, vós sois de Deus, e já os tendes vencido; porque maior é aquele que está em vós do que aquele que está no mundo.

[[v62-4-5]]

^<<v62-4-5,5>>^ Eles são do mundo, por isso falam como quem é do mundo, e o mundo os ouve.

[[v62-4-6]]

^<<v62-4-6,6>>^ Nós somos de Deus; quem conhece a Deus nos ouve; quem não é de Deus não nos ouve. assim é que conhecemos o espírito da verdade e o espírito do erro.

[[v62-4-7]]

^<<v62-4-7,7>>^ Amados, amemo-nos uns aos outros, porque o amor é de Deus; e todo o que ama é nascido de Deus e conhece a Deus.

[[v62-4-8]]

^<<v62-4-8,8>>^ Aquele que não ama não conhece a Deus; porque Deus é amor.

[[v62-4-9]]

^<<v62-4-9,9>>^ Nisto se manifestou o amor de Deus para conosco: em que Deus enviou seu Filho unigênito ao mundo, para que por meio dele vivamos.

[[v62-4-10]]

^<<v62-4-10,10>>^ Nisto está o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou a nós, e enviou seu Filho como propiciação pelos nossos pecados.

[[v62-4-11]]

^<<v62-4-11,11>>^ Amados, se Deus assim nos amou, nós também devemos amar-nos uns aos outros.

[[v62-4-12]]

^<<v62-4-12,12>>^ Ninguém jamais viu a Deus; e nos amamos uns aos outros, Deus permanece em nós, e o seu amor é em nós aperfeiçoado.

[[v62-4-13]]

^<<v62-4-13,13>>^ Nisto conhecemos que permanecemos nele, e ele em nós: por ele nos ter dado do seu Espírito.

[[v62-4-14]]

^<<v62-4-14,14>>^ E nós temos visto, e testificamos que o Pai enviou seu Filho como Salvador do mundo.

[[v62-4-15]]

^<<v62-4-15,15>>^ Qualquer que confessar que Jesus é o Filho de Deus, Deus permanece nele, e ele em Deus.

[[v62-4-16]]

^<<v62-4-16,16>>^ E nós conhecemos, e cremos no amor que Deus nos tem. Deus é amor; e quem permanece em amor, permanece em Deus, e Deus nele.

[[v62-4-17]]

^<<v62-4-17,17>>^ Nisto é aperfeiçoado em nós o amor, para que no dia do juízo tenhamos confiança; porque, qual ele é, somos também nós neste mundo.

[[v62-4-18]]

^<<v62-4-18,18>>^ No amor não há medo antes o perfeito amor lança fora o medo; porque o medo envolve castigo; e quem tem medo não está aperfeiçoado no amor.

[[v62-4-19]]

^<<v62-4-19,19>>^ Nós amamos, porque ele nos amou primeiro.

[[v62-4-20]]

^<<v62-4-20,20>>^ Se alguém diz: Eu amo a Deus, e odeia a seu irmão, é mentiroso. Pois quem não ama a seu irmão, ao qual viu, não pode amar a Deus, a quem não viu.

[[v62-4-21]]

^<<v62-4-21,21>>^ E dele temos este mandamento, que quem ama a Deus ame também a seu irmão.

'''

xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[Próximo Capítulo &#62;]