include::./index.adoc[]

[[v16-3-0]]
=== Neemias, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-3-1]]

^<<v16-3-1,1>>^ Então se levantou Eliasibe, o sumo sacerdote, juntamente com os seus irmãos, os sacerdotes, e edificaram a porta das ovelhas, a qual consagraram, e lhe assentaram os batentes. Consagraram-na até a torre dos cem, até a torre de Henanel.

[[v16-3-2]]

^<<v16-3-2,2>>^ E junto a ele edificaram os homens de Jericó; também ao lado destes edificou Zacur, o filho de Inri.

[[v16-3-3]]

^<<v16-3-3,3>>^ Os filhos de Hassenaá edificaram a porta dos peixes, colocaram-lhe as vigas, e lhe assentaram os batentes, com seus ferrolhos e trancas.

[[v16-3-4]]

^<<v16-3-4,4>>^ Ao seu lado fez os reparos Meremote, filho de Urias, filho de Hacoz; ao seu lado Mesulão, filho de Berequias, filho de Mesezabel; ao seu lado Zadoque, filho de Baaná;

[[v16-3-5]]

^<<v16-3-5,5>>^ ao lado destes repararam os tecoítas; porém os seus nobres não meteram o pescoço os serviço do Senhor.

[[v16-3-6]]

^<<v16-3-6,6>>^ Joiada, filho de Paséia, e Mesulão, filho de Besodéias, repararam a porta velha, colocaram-lhe as vigas, e lhe assentaram os batentes com seus ferrolhos e trancas.

[[v16-3-7]]

^<<v16-3-7,7>>^ Junto deles fizeram os reparos Melatias, o gibeonita, e Jadom, o meronotita, homens de Gibeão e de Mizpá, que pertenciam ao domínio do governador dalém do Rio;

[[v16-3-8]]

^<<v16-3-8,8>>^ ao seu lado Uziel, filho de Haraías, um dos ourives; ao lado dele Hananias, um dos perfumistas; e fortificaram Jerusalém até o muro largo.

[[v16-3-9]]

^<<v16-3-9,9>>^ Ao seu lado fez os reparos Refaías, filho de Hur, governador da metade do distrito de Jerusalém;

[[v16-3-10]]

^<<v16-3-10,10>>^ ao seu lado Jedaías, filho de Harumafe, defronte de sua casa; ao seu lado Hatus, filho de Hasabnéias.

[[v16-3-11]]

^<<v16-3-11,11>>^ Malquias, filho de Harim, e Hassube, filho de Paate-Moabe, repararam outra parte, como também a torre dos fornos;

[[v16-3-12]]

^<<v16-3-12,12>>^ e ao seu lado Salum, filho de Haloés, governador da outra metade do distrito de Jerusalém, ele e as suas filhas.

[[v16-3-13]]

^<<v16-3-13,13>>^ A porta do vale, repararam-na Hanum e os moradores de Zanoa; estes a edificaram, e lhe assentaram os batentes, com seus ferrolhos e trancas, como também mil côvados de muro até a porto do monturo.

[[v16-3-14]]

^<<v16-3-14,14>>^ A porta do monturo, reparou-a Malquias, filho de Recabe, governador do distrito Bete-Haquerem; este a edificou, e lhe assentou os batentes com seus ferrolhos e trancas.

[[v16-3-15]]

^<<v16-3-15,15>>^ A porta da fonte, reparou-a Salum, filho de Col-Hoze, governador do distrito de Mizpá; edificou-a e a cobriu, e lhe assentou os batentes, com seus ferrolhos e trancas; edificou também o muro da piscina de Selá, do jardim do rei, até os degraus que descem da cidade de Davi.

[[v16-3-16]]

^<<v16-3-16,16>>^ Depois dele Neemias, filho de Azbuque, governador da metade do distrito de Bete-Zur, fez os reparos até defronte dos sepulcros de Davi, até a piscina artificial, e até a casa dos homens poderosos.

[[v16-3-17]]

^<<v16-3-17,17>>^ Depois dele fizeram os reparos os levitas: Reum, filho de Bani, e ao seu lado, Hasabias, governador da metade do distrito de Queila, por seu distrito;

[[v16-3-18]]

^<<v16-3-18,18>>^ depois dele seus irmãos, Bavai, filho de Henadade, governador da outra metade do distrito de Queila.

[[v16-3-19]]

^<<v16-3-19,19>>^ Ao seu lado Ézer, filho de Jesuá, governador de Mizpá, reparou outra parte, defronte da subida para a casa das armas, no ângulo.

[[v16-3-20]]

^<<v16-3-20,20>>^ Depois dele reparou Baruque, filho de Zabai, outra parte, desde o ângulo até a porta da casa de Eliasibe, o sumo sacerdote.

[[v16-3-21]]

^<<v16-3-21,21>>^ Depois dele reparou Meremote, filho de Urias, filho de Hacoz, outra parte, deste a porta da casa de Eliasibe até a extremidade da mesma.

[[v16-3-22]]

^<<v16-3-22,22>>^ Depois dele fizeram os reparos os sacerdotes que habitavam na campina;

[[v16-3-23]]

^<<v16-3-23,23>>^ depois Benjamim e Hassube, defronte da sua casa; depois deles Azarias, filho de Maaséias, filho de Ananias, junto à sua casa.

[[v16-3-24]]

^<<v16-3-24,24>>^ Depois dele reparou Binuí, filho de Henadade, outra porte, desde a casa de Azarias até o ângulo e até a esquina.

[[v16-3-25]]

^<<v16-3-25,25>>^ Palal, filho de Uzai, reparou defronte do ângulo, e a torre que se projeta da casa real superior, que está junto ao átrio da guarda; depois dele Pedaías, filho de Parós.

[[v16-3-26]]

^<<v16-3-26,26>>^ &#123;Ora, os netinins habitavam em Ofel, até defronte da porta das águas, para o oriente, e até a torre que se projeta.&#125;

[[v16-3-27]]

^<<v16-3-27,27>>^ Depois repararam os tecoítas outra parte, defronte da grande torre que se projeta, e até o muro de Ofel.

[[v16-3-28]]

^<<v16-3-28,28>>^ Para cima da porta dos cavalos fizeram os reparos os sacerdotes, cada um defronte da sua casa;

[[v16-3-29]]

^<<v16-3-29,29>>^ depois dele Zadoque, filho de Imer, defronte de sua casa; e depois dele Semaías, filho de Secanias, guarda da porta oriental.

[[v16-3-30]]

^<<v16-3-30,30>>^ Depois dele repararam outra parte Hananias, filho de Selemias, e Hanum, o sexto filho de Zalafe. Depois dele reparou Mesulão, filho de Berequias, uma parte defronte da sua câmara.

[[v16-3-31]]

^<<v16-3-31,31>>^ Depois dele reparou Malquias, um dos ourives, uma parte até a casa dos netinins e dos mercadores, defronte da porta da guarda, e até a câmara superior da esquina.

[[v16-3-32]]

^<<v16-3-32,32>>^ E entre a câmara da esquina e a porta das ovelhas repararam os ourives e os mercadores.

'''

xref:016-neemias/016-neemias-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-neemias/016-neemias-004.adoc#v16-4-0[Próximo Capítulo &#62;]