include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-6-1]]

^<<v16-6-1,1>>^ Quando Sambalate, Tobias e Gesem, o arábio, e o resto dos nossos inimigos souberam que eu já tinha edificado o muro e que nele já não havia brecha alguma, ainda que até este tempo não tinha posto as portas nos portais,

[[v16-6-2]]

^<<v16-6-2,2>>^ Sambalate e Gesem mandaram dizer-me: Vem, encontremo-nos numa das aldeias da planície de Ono. Eles, porém, intentavam fazer-me mal.

[[v16-6-3]]

^<<v16-6-3,3>>^ E enviei-lhes mensageiros a dizer: Estou fazendo uma grande obra, de modo que não poderei descer. Por que cessaria esta obra, enquanto eu a deixasse e fosse ter convosco?

[[v16-6-4]]

^<<v16-6-4,4>>^ Do mesmo modo mandaram dizer-se quatro vezes; e do mesmo modo lhes respondi.

[[v16-6-5]]

^<<v16-6-5,5>>^ Então Sambalate, ainda pela quinta vez, me enviou o seu moço com uma carta aberta na mão,

[[v16-6-6]]

^<<v16-6-6,6>>^ na qual estava escrito: Entre as nações se ouviu, e Gesem o diz, que tu e os judeus intentais revoltar-vos, e por isso tu estás edificando o muro, e segundo se diz, queres fazer-te rei deles;

[[v16-6-7]]

^<<v16-6-7,7>>^ e que constituíste profetas para proclamarem a respeito de ti em Jerusalém: Há rei em Judá. Ora, estas coisas chegarão aos ouvidos do rei; vem pois, agora e consultemos juntamente.

[[v16-6-8]]

^<<v16-6-8,8>>^ Então mandei dizer-lhe: De tudo o que dizes, coisa nenhuma sucedeu, mas tu mesmo o inventas.

[[v16-6-9]]

^<<v16-6-9,9>>^ Pois todos eles nos procuravam atemorizar, dizendo: As suas mãos hão de largar a obra, e não se efetuará. Mas agora, ó Deus, fortalece as minhas mãos.

[[v16-6-10]]

^<<v16-6-10,10>>^ Fui à casa de Semaías, filho de Delaías, filho de Meetabel, que estava em recolhimento; e disse ele: Ajuntemo-nos na casa de Deus, dentro do templo, e fechemos as suas portas, pois virão matar-te; sim, de noite virão matar-te.

[[v16-6-11]]

^<<v16-6-11,11>>^ Eu, porém, respondi: Um homem como eu fugiria? e quem há que, sendo tal como eu, possa entrar no templo e viver? De maneira nenhuma entrarei.

[[v16-6-12]]

^<<v16-6-12,12>>^ E percebi que não era Deus que o enviara; mas ele pronunciou essa profecia contra mim, porquanto Tobias e Sambalate o haviam subornado.

[[v16-6-13]]

^<<v16-6-13,13>>^ Eles o subornaram para me atemorizar, a fim de que eu assim fizesse, e pecasse, para que tivessem de que me infamar, e assim vituperassem.

[[v16-6-14]]

^<<v16-6-14,14>>^ Lembra-te, meu Deus, de Tobias e de Sambalate, conforme estas suas obras, e também da profetisa Noadias, e dos demais profetas que procuravam atemorizar-me.

[[v16-6-15]]

^<<v16-6-15,15>>^ Acabou-se, pois, o muro aos vinte e cinco do mês de elul, em cinqüenta e dois dias.

[[v16-6-16]]

^<<v16-6-16,16>>^ Quando todos os nosso inimigos souberam disso, todos os povos que havia em redor de nós temeram, e abateram-se muito em seu próprio conceito; pois perceberam que fizemos esta obra com o auxílio do nosso Deus.

[[v16-6-17]]

^<<v16-6-17,17>>^ Além disso, naqueles dias o nobres de Judá enviaram muitas cartas a Tobias, e as cartas de Tobias vinham para eles.

[[v16-6-18]]

^<<v16-6-18,18>>^ Pois muitos em Judá estavam ligados a ele por juramento, por ser ele genro de Secanias, filho de Ará, e por haver seu filho Joanã casado com a filha de Mesulão, filho de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Também as boas ações dele contavam perante mim, e as minhas palavras transmitiam a ele. Tobias, pois, escrevia cartas para me atemorizar.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]