include::./index.adoc[]

[[v16-8-0]]
=== Neemias, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-8-1]]

^<<v16-8-1,1>>^ Então todo o povo se ajuntou como um só homem, na praça diante da porta das águas; e disseram a Esdras, o escriba, que trouxesse o livro da lei de Moisés, que o Senhor tinha ordenado a Israel.

[[v16-8-2]]

^<<v16-8-2,2>>^ E Esdras, o sacerdote, trouxe a lei perante a congregação, tanto de homens como de mulheres, e de todos os que podiam ouvir com entendimento, no primeiro dia do sétimo mês.

[[v16-8-3]]

^<<v16-8-3,3>>^ E leu nela diante da praça que está fronteira à porta das águas, desde a alva até o meio-dia, na presença dos homens e das mulheres, e dos que podiam entender; e os ouvidos de todo o povo estavam atentos ao livro da lei.

[[v16-8-4]]

^<<v16-8-4,4>>^ Esdras, o escriba, ficava em pé sobre um estrado de madeira, que fizeram para esse fim e estavam em pé junto a ele, à sua direita, Matitias, Sema, Ananías, Urias, Hilquias e Maaséias; e à sua esquerda, Pedaías, Misael, Malquias, Hasum, Hasbadana, Zacarias e Mesulão.

[[v16-8-5]]

^<<v16-8-5,5>>^ E Esdras abriu o livro à vista de todo o povo &#123;pois estava acima de todo o povo&#125;; e, abrindo-o ele, todo o povo se pôs em pé.

[[v16-8-6]]

^<<v16-8-6,6>>^ Então Esdras bendisse ao Senhor, o grande Deus; e todo povo, levantando as mãos, respondeu: Amém! amém! E, inclinando-se, adoraram ao Senhor, com os rostos em terra.

[[v16-8-7]]

^<<v16-8-7,7>>^ Também Jesuá, Bani, Serebias, Jamim, Acube; Sabetai, Hodias, Maaséias, Quelita, Azarias, Jozabade, Hanã, Pelaías e os levitas explicavam ao povo a lei; e o povo estava em pé no seu lugar.

[[v16-8-8]]

^<<v16-8-8,8>>^ Assim leram no livro, na lei de Deus, distintamente; e deram o sentido, de modo que se entendesse a leitura.

[[v16-8-9]]

^<<v16-8-9,9>>^ E Neemias, que era o governador, e Esdras, sacerdote e escriba, e os levitas que ensinavam o povo, disseram a todo o povo: Este dia é consagrado ao Senhor vosso Deus; não pranteeis nem choreis. Pois todo o povo chorava, ouvindo as palavras da lei.

[[v16-8-10]]

^<<v16-8-10,10>>^ Disse-lhes mais: Ide, comei as gorduras, e bebei as doçuras, e enviai porções aos que não têm nada preparado para si; porque este dia é consagrado ao nosso Senhor. Portanto não vos entristeçais, pois a alegria do Senhor é a vossa força.

[[v16-8-11]]

^<<v16-8-11,11>>^ Os levitas, pois, fizeram calar todo o povo, dizendo: Calai-vos, porque este dia é santo; por isso não vos entristeçais.

[[v16-8-12]]

^<<v16-8-12,12>>^ Então todo o povo se foi para comer e beber, e para enviar porções, e para fazer grande regozijo, porque tinha entendido as palavras que lhe foram referidas.

[[v16-8-13]]

^<<v16-8-13,13>>^ Ora, no dia seguinte ajuntaram-se os cabeças das casas paternas de todo o povo, os sacerdotes e os levitas, na presença de Esdras, o escriba, para examinarem as palavras da lei;

[[v16-8-14]]

^<<v16-8-14,14>>^ e acharam escrito na lei que o Senhor, por intermédio de Moisés, ordenara que os filhos de Israel habitassem em cabanas durante a festa do sétimo mês;

[[v16-8-15]]

^<<v16-8-15,15>>^ e que publicassem e fizessem passar pregão por todas as suas cidades, e em ramos de oliveiras, de zambujeiros e de murtas, folhas de palmeiras, e ramos de outras árvores frondosas, para fazerdes cabanas, como está escrito.

[[v16-8-16]]

^<<v16-8-16,16>>^ Saiu, pois, o povo e trouxe os ramos; e todos fizeram para si cabanas, cada um no eirado da sua casa, nos seus pátios, nos átrios da casa de Deus, na praça da porta das águas, e na praça da porta de Efraim.

[[v16-8-17]]

^<<v16-8-17,17>>^ E toda a comunidade dos que tinham voltado do cativeiro fez cabanas, e habitaram nelas; pois não tinham feito assim os filhos de Israel desde os dias de Josué, filho de Num, até aquele dia. E houve mui grande regozijo.

[[v16-8-18]]

^<<v16-8-18,18>>^ E Esdras leu no livro da lei de Deus todos os dias, desde o primeiro até o último; e celebraram a festa por sete dias, e no oitavo dia houve uma assembléia solene, segundo a ordenança.

'''

xref:016-neemias/016-neemias-007.adoc#v16-7-0[&#60; Capítulo Anterior] | <<v16-8-0,Topo>> | xref:016-neemias/016-neemias-009.adoc#v16-9-0[Próximo Capítulo &#62;]