include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-2-1]]

^<<v16-2-1,1>>^ Sucedeu, pois, no mês de nisã, no ano vigésimos do rei Artaxerxes, quando o vinho estava posto diante dele, que eu apanhei o vinho e o dei ao rei. Ora, eu nunca estivera triste na sua presença.

[[v16-2-2]]

^<<v16-2-2,2>>^ E o rei me disse: Por que está triste o teu rosto, visto que não estás doente? Não é isto senão tristeza de coração. Então temi sobremaneira.

[[v16-2-3]]

^<<v16-2-3,3>>^ e disse ao rei: Viva o rei para sempre! Como não há de estar triste o meu rosto, estando na cidade, o lugar dos sepulcros de meus pais, assolada, e tendo sido consumidas as suas portas pelo fogo?

[[v16-2-4]]

^<<v16-2-4,4>>^ Então o rei me perguntou: Que me pedes agora? Orei, pois, ao Deus do céu,

[[v16-2-5]]

^<<v16-2-5,5>>^ e disse ao rei: Se for do agrado do rei, e se teu servo tiver achado graça diante de ti, peço-te que me envies a Judá, à cidade dos sepulcros de meus pais, para que eu a reedifique.

[[v16-2-6]]

^<<v16-2-6,6>>^ Então o rei, estando a rainha assentada junto a ele, me disse: Quanto durará a tua viagem, e quando voltarás? E aprouve ao rei enviar-me, apontando-lhe eu certo prazo.

[[v16-2-7]]

^<<v16-2-7,7>>^ Eu disse ainda ao rei: Se for do agrado do rei, dêem-se-me cartas para os governadores dalém do Rio, para que me permitam passar até que eu chegue a Judá;

[[v16-2-8]]

^<<v16-2-8,8>>^ como também uma carta para Asafe, guarda da floresta do rei, a fim de que me dê madeira para as vigas das portas do castelo que pertence à casa, e para o muro da cidade, e para a casa que eu houver de ocupar. E o rei mas deu, graças à mão benéfica do meu Deus sobre mim.

[[v16-2-9]]

^<<v16-2-9,9>>^ Então fui ter com os governadores dalém do Rio, e lhes entreguei as cartas do rei. Ora, o rei tinha enviado comigo oficiais do exército e cavaleiros.

[[v16-2-10]]

^<<v16-2-10,10>>^ O que ouvindo Sambalate, o horonita, e Tobias, o servo amonita, ficaram extremamente agastados de que alguém viesse a procurar o bem dos filhos de Israel.

[[v16-2-11]]

^<<v16-2-11,11>>^ Cheguei, pois, a Jerusalém, e estive ali três dias.

[[v16-2-12]]

^<<v16-2-12,12>>^ Então de noite me levantei, eu e uns poucos homens comigo; e não declarei a ninguém o que o meu deus pusera no coração para fazer por Jerusalém. Não havia comigo animal algum, senão aquele que eu montava.

[[v16-2-13]]

^<<v16-2-13,13>>^ Assim saí de noite pela porta do vale, até a fonte do dragão, e até a porta do monturo, e contemplei os muros de Jerusalém, que estavam demolidos, e as suas portas, que tinham sido consumidas pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ E passei adiante até a porta da fonte, e à piscina do rei; porém não havia lugar por onde pudesse passar o animal que eu montava.

[[v16-2-15]]

^<<v16-2-15,15>>^ Ainda de noite subi pelo ribeiro, e contemplei o muro; e virando, entrei pela porta do vale, e assim voltei.

[[v16-2-16]]

^<<v16-2-16,16>>^ E não souberam os magistrados aonde eu fora nem o que eu fazia; pois até então eu não havia declarado coisa alguma, nem aos judeus, nem aos sacerdotes, nem aos nobres, nem aos magistrados, nem aos demais que faziam a obra.

[[v16-2-17]]

^<<v16-2-17,17>>^ Então eu lhes disse: Bem vedes vós o triste estado em que estamos, como Jerusalém está assolada, e as suas portas queimadas a fogo; vinde, pois, e edifiquemos o muro de Jerusalém, para que não estejamos mais em opróbrio.

[[v16-2-18]]

^<<v16-2-18,18>>^ Então lhes declarei como a mão do meu Deus me fora favorável, e bem assim as palavras que o rei me tinha dito. Eles disseram: Levantemo-nos, e edifiquemos. E fortaleceram as mãos para a boa obra.

[[v16-2-19]]

^<<v16-2-19,19>>^ O que ouvindo Sambalate, o horonita, e Tobias, o servo amonita, e Gesem, o arábio, zombaram de nós, desprezaram-nos e disseram: O que é isso que fazeis? Quereis rebelar-vos contra o rei?

[[v16-2-20]]

^<<v16-2-20,20>>^ Então lhes respondi: O Deus do céu é que nos fará prosperar; e nós, seus servos, nos levantaremos e edificaremos: mas vós não tendes parte, nem direito, nem memorial em Jerusalém.

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]