include::./index.adoc[]

[[v16-12-0]]
=== Neemias, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-12-1]]

^<<v16-12-1,1>>^ Ora, estes são os sacerdotes e os levitas que subiram com Zorobabel, filho de Sealtiel, e com Jesuá: Seraías, Jeremias, Esdras,

[[v16-12-2]]

^<<v16-12-2,2>>^ Amarias, Maluque, Hatus,

[[v16-12-3]]

^<<v16-12-3,3>>^ Ido, Ginetói, Abias,

[[v16-12-4]]

^<<v16-12-4,4>>^ Secanias, Reum, Meremote,

[[v16-12-5]]

^<<v16-12-5,5>>^ Miamim, Maadias, Bilga,

[[v16-12-6]]

^<<v16-12-6,6>>^ Semaías, Joiaribe, Jedaías,

[[v16-12-7]]

^<<v16-12-7,7>>^ Salu, Amoque, Hilquias e Jedaías; estes foram os chefes dos sacerdotes e de seus irmãos, nos dias de Jesuá.

[[v16-12-8]]

^<<v16-12-8,8>>^ E os levitas: Jesuá, Binuí, Cadmiel, Serebias, Judá, Matanias; este e seus irmãos dirigiam os louvores.

[[v16-12-9]]

^<<v16-12-9,9>>^ E Baquebuquias e Uni, seus irmãos, estavam defronte deles segundo os seus cargos.

[[v16-12-10]]

^<<v16-12-10,10>>^ Jesuá foi pai de Joiaquim, Joiaquim de Eliasibe, Eliasibe de Joiada,

[[v16-12-11]]

^<<v16-12-11,11>>^ Joiada de Jonatã, e Jonatã de Jadua.

[[v16-12-12]]

^<<v16-12-12,12>>^ E nos dias de Joiaquim foram sacerdotes, chefes das casas paternas: por Seraías, Meraías; por Jeremias, Hananias;

[[v16-12-13]]

^<<v16-12-13,13>>^ por Esdras, Mesulão; por Amarias, Jeoanã;

[[v16-12-14]]

^<<v16-12-14,14>>^ por Malúqui, Jonatã; por Sebanias, José;

[[v16-12-15]]

^<<v16-12-15,15>>^ por Harim, Adná; por Meraiote, Helcai;

[[v16-12-16]]

^<<v16-12-16,16>>^ por Ido, Zacarias; por Gineton, Mesulão;

[[v16-12-17]]

^<<v16-12-17,17>>^ por Abias, Zicri; por Miniamim, por Moadias, Piltai;

[[v16-12-18]]

^<<v16-12-18,18>>^ por Bilga, Samua; por Semaías, Jeonatã;

[[v16-12-19]]

^<<v16-12-19,19>>^ por Joiaribe, Matenai; por Jedaías, Uzi;

[[v16-12-20]]

^<<v16-12-20,20>>^ por Salai, Calai; por Amoque, Eber;

[[v16-12-21]]

^<<v16-12-21,21>>^ por Hilquias, Hasabias; por Jedaías, Netanel.

[[v16-12-22]]

^<<v16-12-22,22>>^ Nos dias de Eliasibe, Joiada, Joanã e Jadua foram inscritos, dos levitas, os chefes das casas paternas; e assim também os dos sacerdotes, no reinado de Dário, o persa.

[[v16-12-23]]

^<<v16-12-23,23>>^ Os filhos de Levi, chefes de casas paternas, foram inscritos no livro das crônicas, até os dias de Joanã, filho de Eliasibe.

[[v16-12-24]]

^<<v16-12-24,24>>^ Foram, pois, os chefes dos levitas: Hasabias, Serebias, Jesuá, filho de Cadmiel, e seus irmãos que ficavam defronte deles, turma contra turma, para louvarem e darem graças, segundo a ordem de Davi, homem de Deus.

[[v16-12-25]]

^<<v16-12-25,25>>^ Matanias, Baquebuquias, Obadias, Mesulão, Talmom, e Acube eram porteiros, e faziam a guarda junto aos celeiros das portas.

[[v16-12-26]]

^<<v16-12-26,26>>^ Estes viveram nos dias de Joiaquim, filho de Jesuá, filho de Jozadaque, como também nos dias de Neemias, o governador, e do sacerdote Esdras, o escriba.

[[v16-12-27]]

^<<v16-12-27,27>>^ Ora, na dedicação dos muros de Jerusalém buscaram os levitas de todos os lugares, para os trazerem a Jerusalém, a fim de celebrarem a dedicação com alegria e com ações de graças, e com canto, címbalos, alaúdes e harpas.

[[v16-12-28]]

^<<v16-12-28,28>>^ Ajuntaram-se os filhos dos cantores, tanto da campina dos arredores de Jerusalém, como das aldeias do netofatitas;

[[v16-12-29]]

^<<v16-12-29,29>>^ como também de Bete-Gilgal, e dos campos de Geba e Azmavete; pois os cantores tinham edificado para si aldeias ao redor de Jerusalém.

[[v16-12-30]]

^<<v16-12-30,30>>^ E os sacerdotes e os levitas se purificaram, e purificaram o povo, as portas e o muro.

[[v16-12-31]]

^<<v16-12-31,31>>^ Então fiz subir os príncipes de Judá sobre o muro, e constituí duas grandes companhias para darem graças e andarem em procissão, uma das quais foi para a direita sobre o muro, em direção à porta do monturo;

[[v16-12-32]]

^<<v16-12-32,32>>^ e após ela seguiam Hosaías, e a metade dos príncipes de Judá,

[[v16-12-33]]

^<<v16-12-33,33>>^ e Azarias, Esdras, Mesulão,

[[v16-12-34]]

^<<v16-12-34,34>>^ Judá, Benjamim, Semaías, e Jeremias;

[[v16-12-35]]

^<<v16-12-35,35>>^ e dos filhos dos sacerdotes, levando trombetas, Zacarias, filho de Jonatã, filho de Semaías, filho de Matanias, filho de Micaías, filho de Zacur, filho de Asafe.

[[v16-12-36]]

^<<v16-12-36,36>>^ e seus irmãos, Semaías, Azarel, Milalai, Gilalai, Maai, Netanel, Judá e Hanâni, com os instrumento musicais de Davi, homem de Deus; e Esdras, o escriba, ia adiante deles.

[[v16-12-37]]

^<<v16-12-37,37>>^ À entrada da porta da fonte subiram diretamente as escadas da cidade de Davi onde começa a subida do muro, acima da casa de Davi, até a porta das águas a leste.

[[v16-12-38]]

^<<v16-12-38,38>>^ A outra companhia dos que davam graças foi para a esquerda, seguindo-os eu com a metade do povo, sobre o muro, passando pela torre dos fornos até a muralha larga,

[[v16-12-39]]

^<<v16-12-39,39>>^ e seguindo por cima da porta de Efraim, e da porta velha, e da porta dos peixes, e pela torre de Hananel, e a torre dos Cem até a porta das ovelhas; e pararam à porta da guarda.

[[v16-12-40]]

^<<v16-12-40,40>>^ Assim as duas companhias dos que davam graças pararam na casa de Deus, como também eu e a metade dos magistrados que estavam comigo,

[[v16-12-41]]

^<<v16-12-41,41>>^ e os sacerdotes Eliaquim, Maaséias, Miniamim, Micaías, Elioenai, Zacarias e Hananias, com trombetas,

[[v16-12-42]]

^<<v16-12-42,42>>^ com também Maaséias, Semaías, Eleazar, Uzi, Jeoanã, Malquias, Elão, e Ézer; e os cantores cantavam, tendo Jezraías por dirigente.

[[v16-12-43]]

^<<v16-12-43,43>>^ Naquele dia ofereceram grandes sacrifícios, e se alegraram, pois Deus lhes dera motivo de grande alegria; também as mulheres e as crianças se alegraram, de modo que o júbilo de Jerusalém se fez ouvir longe.

[[v16-12-44]]

^<<v16-12-44,44>>^ No mesmo dia foram nomeados homens sobre as câmaras do tesouro para as ofertas alçadas, as primícias e os dízimos, para nelas recolherem, dos campos, das cidades, os quinhões designados pela lei para os sacerdotes e para os levitas; pois Judá se alegrava por estarem os sacerdotes e os levitas no seu posto,

[[v16-12-45]]

^<<v16-12-45,45>>^ observando os preceitos do seu Deus, e os da purificação, como também o fizeram os cantores e porteiros, conforme a ordem de Davi e de seu filho Salomão.

[[v16-12-46]]

^<<v16-12-46,46>>^ Pois desde a antigüidade, já nos dias de Davi e de Asafe, havia um chefe dos cantores, e havia cânticos de louvor e de ação de graça a Deus.

[[v16-12-47]]

^<<v16-12-47,47>>^ Pelo que todo o Israel, nos dias de Zorobabel e nos dias de Neemias, dava aos cantores e aos porteiros as suas porções destinadas aos levitas, e os levitas separavam as porções destinadas aos filhos de Arão.

'''

xref:016-neemias/016-neemias-011.adoc#v16-11-0[&#60; Capítulo Anterior] | <<v16-12-0,Topo>> | xref:016-neemias/016-neemias-013.adoc#v16-13-0[Próximo Capítulo &#62;]