include::./index.adoc[]

[[v16-9-0]]
=== Neemias, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-9-1]]

^<<v16-9-1,1>>^ Ora, no dia vinte e quatro desse mês, se ajuntaram os filhos de Israel em jejum, vestidos de sacos e com terra sobre as cabeças.

[[v16-9-2]]

^<<v16-9-2,2>>^ E os da linhagem de Israel se apartaram de todos os estrangeiros, puseram-se em pé e confessaram os seus pecados e as iniquidades de seus pais.

[[v16-9-3]]

^<<v16-9-3,3>>^ E, levantando-se no seu lugar, leram no livro da lei do Senhor seu Deus, uma quarta parte do dia; e outra quarta parte fizeram confissão, e adoraram ao Senhor seu Deus.

[[v16-9-4]]

^<<v16-9-4,4>>^ Então Jesuá, Bani, Cadmiel, Sebanias, Buni, Serebias, Bani e Quenâni se puseram em pé sobre os degraus dos levitas, e clamaram em alta voz ao Senhor seu Deus.

[[v16-9-5]]

^<<v16-9-5,5>>^ E os levitas Jesuá, Cadmiel, Bani, Hasabnéias, Serebias, Hodias, Sebanias e Petaías disseram: Levantai-vos, bendizei ao Senhor vosso Deus de eternidade em eternidade. Bendito seja o teu glorioso nome, que está exaltado sobre toda benção e louvor.

[[v16-9-6]]

^<<v16-9-6,6>>^ Tu, só tu, és Senhor; tu fizeste o céu e o céu dos céus, juntamente com todo o seu exército, a terra e tudo quanto nela existe, os mares e tudo quanto neles já, e tu os conservas a todos, e o exército do céu te adora.

[[v16-9-7]]

^<<v16-9-7,7>>^ Tu és o Senhor, o Deus que elegeste a Abrão, e o tiraste de Ur dos caldeus, e lhe puseste por nome Abraão;

[[v16-9-8]]

^<<v16-9-8,8>>^ e achaste o seu coração fiel perante ti, e fizeste com ele o pacto de que darias à sua descendência a terra dos cananeus, dos heteus, dos amorreus, dos perizeus, dos jebuseus e dos girgaseus; e tu cumpriste as tuas palavras, pois és justo.

[[v16-9-9]]

^<<v16-9-9,9>>^ Também viste a aflição de nossos pais no Egito, e ouviste o seu clamor junto ao Mar Vermelho;

[[v16-9-10]]

^<<v16-9-10,10>>^ e o operaste sinais e prodígios contra Faraó; e contra todos os seus servos, e contra todo o povo da sua terra; pois sabias com que soberba eles os haviam tratado; e assim adquiriste renome, como hoje se vê.

[[v16-9-11]]

^<<v16-9-11,11>>^ Fendente o mar diante deles, de modo que passaram pelo meio do mar, em seco; e lançaste os seus perseguidores nas profundezas, como uma pedra nas águas impetuosas.

[[v16-9-12]]

^<<v16-9-12,12>>^ Além disso tu os guiaste de dia por uma coluna de nuvem e de noite por uma coluna de fogo, para os alumiares no caminho por onde haviam de ir.

[[v16-9-13]]

^<<v16-9-13,13>>^ Desceste sobre o monte Sinai, do céu falaste com eles, e lhes deste juízos retos e leis verdadeiras, bons estatutos e mandamentos;

[[v16-9-14]]

^<<v16-9-14,14>>^ o teu santo sábado lhes fizeste conhecer; e lhes ordenaste mandamentos e estatutos e uma lei, por intermédio de teu servo Moisés.

[[v16-9-15]]

^<<v16-9-15,15>>^ Do céu lhes deste pão quando tiveram fome, e da rocha fizeste brotar água quando tiveram sede; e lhes ordenaste que entrassem para possuir a terra que com juramento lhes havias prometido dar.

[[v16-9-16]]

^<<v16-9-16,16>>^ Eles, porém, os nossos pais, se houveram soberbamente e endureceram a cerviz, e não deram ouvidos aos teus mandamentos,

[[v16-9-17]]

^<<v16-9-17,17>>^ recusando ouvir-te e não se lembrando das tuas maravilhas, que fizeste no meio deles; antes endureceram a cerviz e, na sua rebeldia, levantaram um chefe, a fim de voltarem para sua servidão. Tu, porém, és um Deus pronto para perdoar, clemente e misericordioso, tardio em irar-te e grande em beneficência, e não os abandonaste.

[[v16-9-18]]

^<<v16-9-18,18>>^ Ainda mesmo quando eles fizeram para si um bezerro de fundição, e disseram: Este é o teu Deus, que te tirou do Egito, e cometeram grandes blasfêmias,

[[v16-9-19]]

^<<v16-9-19,19>>^ todavia tu, pela multidão das tuas misericórdias, não os abandonaste no deserto. A coluna de nuvem não se apartou deles de dia, para os guiar pelo caminho, nem a coluna de fogo de noite, para lhes alumiar o caminho por onde haviam de ir.

[[v16-9-20]]

^<<v16-9-20,20>>^ Também lhes deste o teu bom espírito para os ensinar, e o teu maná não retiraste da tua boca, e água lhes deste quando tiveram sede.

[[v16-9-21]]

^<<v16-9-21,21>>^ Sim, por quarenta anos os sustentaste no deserto; não lhes faltou coisa alguma; a sua roupa não envelheceu, e o seus pés não se incharam.

[[v16-9-22]]

^<<v16-9-22,22>>^ Além disso lhes deste reinos e povos, que lhes repartiste em porções; assim eles possuíram a terra de Siom, a saber; a terra do rei de Hesbom, e a terra de Ogue, rei de Basã.

[[v16-9-23]]

^<<v16-9-23,23>>^ Outrossim mulplicaste os seus filhos como as estrelas do céu, e os introduziste na terra de que tinhas dito a seus pais que nela entrariam para a possuírem.

[[v16-9-24]]

^<<v16-9-24,24>>^ Os filhos, pois, entraram e possuíram a terra; e abateste perante eles, os moradores da terra, os cananeus, e lhos entregaste nas mãos, como também os seus reis, e os povos da terra, para fazerem deles conforme a sua vontade.

[[v16-9-25]]

^<<v16-9-25,25>>^ Tomaram cidades fortificadas e uma terra fértil, e possuíram casas cheias de toda sorte de coisas boas, cisternas cavadas, vinhas e olivais, e árvores frutíferas em abundância; comeram, pois, fartaram-se e engordaram, e viveram em delícias, pela tua grande bondade.

[[v16-9-26]]

^<<v16-9-26,26>>^ Não obstante foram desobedientes, e se rebelaram contra ti; lançaram a tua lei para trás das costas, e mataram os teus profetas que protestavam contra eles para que voltassem a ti; assim cometeram grandes provocações.

[[v16-9-27]]

^<<v16-9-27,27>>^ Pelo que os entregaste nas mãos dos seus adversários, que os afligiram; mas no templo da sua angústia, quando eles clamaram a ti, tu os ouviste do céu; e segundo a multidão das tuas misericórdias lhes deste libertadores que os libertaram das mãos de seus adversários.

[[v16-9-28]]

^<<v16-9-28,28>>^ Mas, tendo alcançado repouso, tornavam a fazer o mal diante de ti,; portanto tu os deixavas nas mãos dos seus inimigos, de modo que estes dominassem sobre eles; todavia quando eles voltavam e clamavam a ti, tu os ouvias do céu, e segundo a tua misericórdia os livraste muitas vezes;

[[v16-9-29]]

^<<v16-9-29,29>>^ e testemunhaste contra eles, para os fazerdes voltar para a tua lei; contudo eles se houveram soberbamente, e não deram ouvidos aos teus mandamentos, mas pecaram contra os teus juízos, pelos quais viverá o homem que os cumprir; viraram o ombro, endureceram a cerviz e não quiseram ouvir.

[[v16-9-30]]

^<<v16-9-30,30>>^ Não obstante, por muitos anos os aturaste, e testemunhaste contra eles pelo teu Espírito, por intermédio dos teus profetas; todavia eles não quiseram dar ouvidos; pelo que os entregaste nas mãos dos povos de outras terras.

[[v16-9-31]]

^<<v16-9-31,31>>^ Contudo pela tua grande misericórdia não os destruíste de todo, nem os abandonaste, porque és um Deus clemente e misericordioso.

[[v16-9-32]]

^<<v16-9-32,32>>^ Agora, pois, ó nosso Deus, Deus grande, poderoso e temível, que guardas o pacto e a beneficência, não tenhas em pouca conta toda a aflição que nos alcançou a nós, a nossos reis, a nossos príncipes, a nossos sacerdotes, a nossos profetas, a nossos pais e a todo o teu povo, desde os dias dos reis da Assíria até o dia de hoje.

[[v16-9-33]]

^<<v16-9-33,33>>^ Tu, porém, és justo em tudo quanto tem vindo sobre nós; pois tu fielmente procedeste, mas nós perversamente.

[[v16-9-34]]

^<<v16-9-34,34>>^ Os nossos reis, os nossos príncipes, os nossos sacerdotes, e os nossos pais não têm guardado a tua lei, nem têm dado ouvidos aos teus mandamentos e aos teus testemunhos, com que testificaste contra eles.

[[v16-9-35]]

^<<v16-9-35,35>>^ Porque eles, no seu reino, na muita abundância de bens que lhes deste, na terra espaçosa e fértil que puseste diante deles, não te serviram, nem se converteram de suas más obras.

[[v16-9-36]]

^<<v16-9-36,36>>^ Eis que hoje somo escravos; e quanto à terra que deste a nossos pais, para comerem o seu fruto e o seu bem, eis que somos escravos nela.

[[v16-9-37]]

^<<v16-9-37,37>>^ E ela multiplica os seus produtos para os reis que puseste sobre nós por causa dos nossos pecados; também eles dominam sobre os nossos corpos e sobre o nosso gado como bem lhes apraz, e estamos em grande angústia.

[[v16-9-38]]

^<<v16-9-38,38>>^ Contudo, por causa de tudo isso firmamos um pacto e o escrevemos; e selam-no os nossos príncipes, os nossos levitas e os nossos sacerdotes.

'''

xref:016-neemias/016-neemias-008.adoc#v16-8-0[&#60; Capítulo Anterior] | <<v16-9-0,Topo>> | xref:016-neemias/016-neemias-010.adoc#v16-10-0[Próximo Capítulo &#62;]