include::./index.adoc[]

[[v16-4-0]]
=== Neemias, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-4-1]]

^<<v16-4-1,1>>^ Ora, quando Sambalate ouviu que edificávamos o muro, ardeu em ira, indignou-se muito e escarneceu dos judeus;

[[v16-4-2]]

^<<v16-4-2,2>>^ e falou na presença de seus irmãos e do exército de Samária, dizendo: Que fazem estes fracos judeus? Fortificar-se-ão? Oferecerão sacrifícios? Acabarão a obra num só dia? Vivificarão dos montões de pó as pedras que foram queimadas?

[[v16-4-3]]

^<<v16-4-3,3>>^ Ora, estava ao lado dele Tobias, o amonita, que disse: Ainda que edifiquem, vindo uma raposa derrubará o seu muro de pedra.

[[v16-4-4]]

^<<v16-4-4,4>>^ Ouve, ó nosso Deus, pois somos tão desprezados; faze recair o opróbrio deles sobre as suas cabaças, e faze com que eles sejam um despojo numa terra de cativeiro.

[[v16-4-5]]

^<<v16-4-5,5>>^ Não cubras a sua iniquidade, e não se risque de diante de ti o seu pecado, pois que te provocaram à ira na presença dos edificadores.

[[v16-4-6]]

^<<v16-4-6,6>>^ Assim edificamos o muro; e todo o muro se completou até a metade da sua altura; porque o coração do povo se inclinava a trabalhar.

[[v16-4-7]]

^<<v16-4-7,7>>^ Mas, ouvindo Sambalate e Tobias, e os arábios, o amonitas e os asdoditas, que ia avante a reparação dos muros de Jerusalém e que já as brechas se começavam a fechar, iraram-se sobremodo;

[[v16-4-8]]

^<<v16-4-8,8>>^ e coligaram-se todos, para virem guerrear contra Jerusalém e fazer confusão ali.

[[v16-4-9]]

^<<v16-4-9,9>>^ Nós, porém, oramos ao nosso Deus, e pusemos guarda contra eles de dia e de noite.

[[v16-4-10]]

^<<v16-4-10,10>>^ Então disse Judá: Desfalecem as forças dos carregadores, e há muito escombro; não poderemos edificar o muro.

[[v16-4-11]]

^<<v16-4-11,11>>^ E os nossos inimigos disseram: Nada saberão nem verão, até que entremos no meio deles, e os matemos, e façamos cessar a obra.

[[v16-4-12]]

^<<v16-4-12,12>>^ Mas sucedeu que, vindo os judeus que habitavam entre eles, dez vezes nos disseram: De todos os lugares de onde moram subirão contra nós.

[[v16-4-13]]

^<<v16-4-13,13>>^ Pelo que nos lugares baixos por detrás do muro e nos lugares abertos, dispus o povo segundo suas famílias com as suas espadas, com as suas lanças, e com os seus arcos.

[[v16-4-14]]

^<<v16-4-14,14>>^ Olhei, levantei-me, e disse aos nobres, aos magistrados e ao resto do povo: Não os temais! Lembrai-vos do Senhor, grande e temível, e pelejai por vossos irmãos, vossos filhos, vossas filhas, vossas mulheres e vossas casas.

[[v16-4-15]]

^<<v16-4-15,15>>^ Quando os nossos inimigos souberam que nós tínhamos sido avisados, e que Deus tinha dissipado o conselho deles, todos voltamos ao muro, cada um para a sua obra.

[[v16-4-16]]

^<<v16-4-16,16>>^ Desde aquele dia metade dos meus moços trabalhavam na obra, e a outra metade empunhava as lanças, os escudos, os arcos, e as couraças; e os chefes estavam por detrás de toda a casa de Judá.

[[v16-4-17]]

^<<v16-4-17,17>>^ Os que estavam edificando o muro, e os carregadores que levavam as cargas, cada um com uma das mãos fazia a obra e com a outra segurava a sua arma;

[[v16-4-18]]

^<<v16-4-18,18>>^ e cada um dos edificadores trazia a sua espada à cinta, e assim edificavam. E o que tocava a trombeta estava no meu lado.

[[v16-4-19]]

^<<v16-4-19,19>>^ Disse eu aos nobres, aos magistrados e ao resto do povo: Grande e extensa é a obra, e nós estamos separados no muro, longe uns dos outros;

[[v16-4-20]]

^<<v16-4-20,20>>^ em qualquer lugar em que ouvirdes o som da trombeta, ali vos ajuntareis conosco. O nosso Deus pelejará por nós.

[[v16-4-21]]

^<<v16-4-21,21>>^ Assim trabalhávamos na obra; e metade deles empunhava as lanças desde a subida da alva até o sair das estrelas.

[[v16-4-22]]

^<<v16-4-22,22>>^ Também nesse tempo eu disse ao povo: Cada um com o seu moço pernoite em Jerusalém, para que de noite nos sirvam de guardas, e de dia trabalhem.

[[v16-4-23]]

^<<v16-4-23,23>>^ Desta maneira nem eu, nem meus irmãos, nem meus moços, nem os homens da guarda que me acompanhavam largávamos as nossas vestes; cada um ia com a arma à sua direita.

'''

xref:016-neemias/016-neemias-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-neemias/016-neemias-005.adoc#v16-5-0[Próximo Capítulo &#62;]