include::./index.adoc[]

[[v16-7-0]]
=== Neemias, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v16-7-1]]

^<<v16-7-1,1>>^ Ora, depois que o muro foi edificado, tendo eu assentado as portas, e havendo sido designados os porteiros, os cantores e os levitas,

[[v16-7-2]]

^<<v16-7-2,2>>^ pus Hanâni, meu irmão, e Hananias, governador do castelo, sobre Jerusalém; pois ele era homem fiel e temente a Deus, mais do que muitos;

[[v16-7-3]]

^<<v16-7-3,3>>^ e eu lhes disse: Não se abram as portas de Jerusalém até que o sol aqueça; e enquanto os guardas estiverem nos postos se fechem e se tranquem as portas; e designei dentre os moradores de Jerusalém guardas, cada um por seu turno, e cada um diante da sua casa.

[[v16-7-4]]

^<<v16-7-4,4>>^ Ora, a cidade era larga e grande, mas o povo dentro dela era pouco, e ainda as casa não estavam edificadas.

[[v16-7-5]]

^<<v16-7-5,5>>^ Então o meu Deus me pôs no coração que ajuntasse os nobres, os magistrados e o povo, para registrar as genealogias. E achei o livro da genealogia dos que tinham subido primeiro e achei escrito nele o seguinte:

[[v16-7-6]]

^<<v16-7-6,6>>^ Este são os filhos da província que subiram do cativeiro dentre os exilados, que Nabucodonosor, rei da Babilônia, transportara e que voltaram para Jerusalém e para Judá, cada um para a sua cidade,

[[v16-7-7]]

^<<v16-7-7,7>>^ os quais vieram com Zorobabel, Jesuá, Neemias, Azarias, Raamias, Naamâni, Mordecai, Bilsã, Misperete, Bigvai, Neum e Baaná. Este é o número dos homens do povo de Israel:

[[v16-7-8]]

^<<v16-7-8,8>>^ foram os filhos de Parós, dois mil cento e setenta e dois;

[[v16-7-9]]

^<<v16-7-9,9>>^ os filhos de Sefatias, trezentos e setenta e dois;

[[v16-7-10]]

^<<v16-7-10,10>>^ os filhos de Ará, seiscentos e cinqüenta e dois;

[[v16-7-11]]

^<<v16-7-11,11>>^ os filhos de Paate-Moabe, dos filhos de Jesuá e de Joabe, dois mil oitocentos e dezoito;

[[v16-7-12]]

^<<v16-7-12,12>>^ os filhos de Elão, mil duzentos e cinqüenta e quatro;

[[v16-7-13]]

^<<v16-7-13,13>>^ os filhos de Zatu, oitocentos e quarenta e cinco;

[[v16-7-14]]

^<<v16-7-14,14>>^ os filhos de Zacai, setecentos e sessenta;

[[v16-7-15]]

^<<v16-7-15,15>>^ os filhos de Binuí, seiscentos e quarenta e oito;

[[v16-7-16]]

^<<v16-7-16,16>>^ os filhos de Bebai, seiscentos e vinte e oito;

[[v16-7-17]]

^<<v16-7-17,17>>^ os filhos de Azgade, dois mil trezentos e vinte e dois;

[[v16-7-18]]

^<<v16-7-18,18>>^ os filhos de Adonicão, seiscentos e sessenta e sete;

[[v16-7-19]]

^<<v16-7-19,19>>^ os filhos de Bigvai, dois mil e sessenta e sete;

[[v16-7-20]]

^<<v16-7-20,20>>^ os filhos de Adim, seiscentos e cinqüenta e cinco;

[[v16-7-21]]

^<<v16-7-21,21>>^ os filhos de Ater, de Ezequias, noventa e oito;

[[v16-7-22]]

^<<v16-7-22,22>>^ os filhos de Hasum, trezentos e vinte e oito;

[[v16-7-23]]

^<<v16-7-23,23>>^ os filhos de Bezai, trezentos e vinte e quatro;

[[v16-7-24]]

^<<v16-7-24,24>>^ os filhos de Harife, cento e doze;

[[v16-7-25]]

^<<v16-7-25,25>>^ os filhos de Gibeão, noventa e cinco;

[[v16-7-26]]

^<<v16-7-26,26>>^ os filhos de Belém e de Netofá, cento e oitenta e oito;

[[v16-7-27]]

^<<v16-7-27,27>>^ os homens de Anatote, cento e vinte e oito;

[[v16-7-28]]

^<<v16-7-28,28>>^ os homens de Bete-Azmavete, quarenta e dois;

[[v16-7-29]]

^<<v16-7-29,29>>^ os homens de Quiriate-Jeriam, de Cefira, e de Beerote, setecentos e quarenta e três;

[[v16-7-30]]

^<<v16-7-30,30>>^ os homens de Ramá e Gaba, seiscentos e vinte e um;

[[v16-7-31]]

^<<v16-7-31,31>>^ os homens de Micmás, cento e vinte e dois;

[[v16-7-32]]

^<<v16-7-32,32>>^ os homens de Betel e Ai, cento e vinte e três;

[[v16-7-33]]

^<<v16-7-33,33>>^ os homens do outro Nebo, cinqüenta e dois;

[[v16-7-34]]

^<<v16-7-34,34>>^ os filhos do outro Elão, mil duzentos e cinqüenta e quatro;

[[v16-7-35]]

^<<v16-7-35,35>>^ os filhos de Harim, trezentos e vinte;

[[v16-7-36]]

^<<v16-7-36,36>>^ os filhos de Jericó, trezentos e quarenta e cinco;

[[v16-7-37]]

^<<v16-7-37,37>>^ os filhos de Lode, de hadide e de Ono, setecentos e vinte e um;

[[v16-7-38]]

^<<v16-7-38,38>>^ os filhos de Senaá, três mil novecentos e trinta.

[[v16-7-39]]

^<<v16-7-39,39>>^ Os sacerdotes: os filhos de Jedaías, da casa de Jesuá, novecentos e setenta e três;

[[v16-7-40]]

^<<v16-7-40,40>>^ os filhos de Imer, mil e cinqüenta e dois;

[[v16-7-41]]

^<<v16-7-41,41>>^ os filhos de Pasur, mil duzentos e quarenta e sete;

[[v16-7-42]]

^<<v16-7-42,42>>^ os filhos de Harim, mil e dezessete;

[[v16-7-43]]

^<<v16-7-43,43>>^ Os levitas: os filhos de Jesuá, de Cadmiel, dos filhos de Hodevá, setenta e quatro.

[[v16-7-44]]

^<<v16-7-44,44>>^ Os cantores: os filhos de Asafe, cento e quarenta e oito.

[[v16-7-45]]

^<<v16-7-45,45>>^ Os porteiros: os filhos de Salum, os filhos de Ater, os filhos de Talmom, os filhos de Acube, os filhos de Hatita, os filhos de Sobai, cento e trinta e oito.

[[v16-7-46]]

^<<v16-7-46,46>>^ Os netinis: os filhos de Ziá, os filhos de Hasufa, os filhos de Tabaote,

[[v16-7-47]]

^<<v16-7-47,47>>^ os filhos de Querós, os filhos de Siá, os filhos de Padom,

[[v16-7-48]]

^<<v16-7-48,48>>^ os filhos de Lebana, os filhos de Hagaba, os filhos de Salmai,

[[v16-7-49]]

^<<v16-7-49,49>>^ os filhos de Hanã, os filhos de Gidel, os filhos de Gaar,

[[v16-7-50]]

^<<v16-7-50,50>>^ os filhos de Recaías, os filhos de Rezim, os filhos de Necoda,

[[v16-7-51]]

^<<v16-7-51,51>>^ os filhos de Gazão, os filhos de Uzá, os filhos de Paséia,

[[v16-7-52]]

^<<v16-7-52,52>>^ os filhos de Besai, os filhos de Meunim, os filhos de Nefusesim,

[[v16-7-53]]

^<<v16-7-53,53>>^ os filhos de Baquebuque, os filhos de Hacufa, os filhos de Hacur,

[[v16-7-54]]

^<<v16-7-54,54>>^ os filhos de Bazlite, os filhos de Meída, os filhos de Harsa,

[[v16-7-55]]

^<<v16-7-55,55>>^ os filhos de Barcos, os filhos de Sísera, os filhos de Tamá,

[[v16-7-56]]

^<<v16-7-56,56>>^ os filhos de Nezias, os filhos de Hatifa,

[[v16-7-57]]

^<<v16-7-57,57>>^ os filhos dos servos de Salomão: os filhos de Sotai, os filhos de Soforete, os filhos de Perida,

[[v16-7-58]]

^<<v16-7-58,58>>^ os filhos de Jaala, os filhos de Darcom, os filhos de Gidel,

[[v16-7-59]]

^<<v16-7-59,59>>^ os filhos de Sefatias, os filhos de Hatil, os filhos de Paquerete-Hazebaim e os filhos de Amom.

[[v16-7-60]]

^<<v16-7-60,60>>^ Todos os netinins e os filhos dos servos de Salomão, eram trezentos e noventa e dois.

[[v16-7-61]]

^<<v16-7-61,61>>^ Estes foram os que subiram de Tel-Mela, Tel-Harsa, Querube, Adom, e Imer; porém não puderam provar que as suas casas paternas e as sua linhagem eram de Israel:

[[v16-7-62]]

^<<v16-7-62,62>>^ os filhos de Dalaías, os filhos de Tobias, os filhos de Necoda, seiscentos e quarenta e dois.

[[v16-7-63]]

^<<v16-7-63,63>>^ E dos sacerdotes: os filhos de Hobaías, os filhos Hacoz, os filhos de Barzilai, que tomara por mulher uma das filhas Barzilai, o gileadita, e que foi chamado do seu nome.

[[v16-7-64]]

^<<v16-7-64,64>>^ Estes buscaram o seu registro entre os arrolados nos registros genealógicos, mas não foi encontrado; pelo que, tidos por imundos, foram excluídos do sacerdócio.

[[v16-7-65]]

^<<v16-7-65,65>>^ E o governador lhes disse que não comesse das coisas sagradas, até que se levantasse um sacerdote com Urim e Tumim.

[[v16-7-66]]

^<<v16-7-66,66>>^ Toda esta congregação junta somava quarenta e dois mil trezentos e sessenta;

[[v16-7-67]]

^<<v16-7-67,67>>^ afora os seus servos e as suas servas, que foram sete mil trezentos e trinta e sete; e tinham duzentos e quarenta e cinco cantores e cantoras.

[[v16-7-68]]

^<<v16-7-68,68>>^ Os seus cavalos foram setecentos e trinta e seis; os seus mulos, duzentos e quarenta e cinco;

[[v16-7-69]]

^<<v16-7-69,69>>^ os seus camelos, quatrocentos e trinta e cinco; e os seus jumentos, seis mil setecentos e vinte.

[[v16-7-70]]

^<<v16-7-70,70>>^ Ora, alguns dos cabeças das casas paternas contribuíram para a obra. O governador deu para a tesouraria mil dários de ouro, cinqüenta bacias, e quinhentas e trinta vestes sacerdotais.

[[v16-7-71]]

^<<v16-7-71,71>>^ E alguns dos cabeças das casas paternas deram para a tesouraria da obra vinte mil dáricos de ouro, e duas mil e duzentas minas de prata.

[[v16-7-72]]

^<<v16-7-72,72>>^ O que o resto do povo deu foram vinte mil dáricos de ouro, duas mil minas de prata, e sessenta e sete vestes sacerdotais.

[[v16-7-73]]

^<<v16-7-73,73>>^ Os sacerdotes, os levitas, os porteiros, os cantores, alguns dentre o povo, os netinins e todo o Israel habitaram nas suas cidades. Quando chegou o sétimo mês, já se achavam os filhos de Israel nas suas cidades.

'''

xref:016-neemias/016-neemias-006.adoc#v16-6-0[&#60; Capítulo Anterior] | <<v16-7-0,Topo>> | xref:016-neemias/016-neemias-008.adoc#v16-8-0[Próximo Capítulo &#62;]