include::./index.adoc[]

[[v4-7-0]]
=== Números, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-7-1]]

^<<v4-7-1,1>>^ No dia em que Moisés acabou de levantar o tabernáculo, tendo-o ungido e santificado juntamente com todos os seus móveis, bem como o altar e todos os seus utensílios, depois de ungi-los e santificá-los,

[[v4-7-2]]

^<<v4-7-2,2>>^ os príncipes de Israel, cabeças das casas de seus pais, fizeram as suas ofertas. Estes eram os príncipes das tribos, os que estavam sobre os que foram contados.

[[v4-7-3]]

^<<v4-7-3,3>>^ Trouxeram eles a sua oferta perante o Senhor: seis carros cobertos, e doze bois; por dois príncipes um carro, e por cada um, um boi; e os apresentaram diante do tabernáculo.

[[v4-7-4]]

^<<v4-7-4,4>>^ Então disse o Senhor a Moisés:

[[v4-7-5]]

^<<v4-7-5,5>>^ Recebe-os deles, para serem utilizados no serviço da tenda da revelação; e os darás aos levitas, a cada qual segundo o seu serviço:

[[v4-7-6]]

^<<v4-7-6,6>>^ Assim Moisés recebeu os carros e os bois, e os deu aos levitas.

[[v4-7-7]]

^<<v4-7-7,7>>^ Dois carros e quatro bois deu aos filhos de Gérson segundo o seu serviço;

[[v4-7-8]]

^<<v4-7-8,8>>^ e quatro carros e oito bois deu aos filhos de Merári, segundo o seu serviço, sob as ordens de Itamar, filho de Arão, o sacerdote.

[[v4-7-9]]

^<<v4-7-9,9>>^ Mas aos filhos de Coate não deu nenhum, porquanto lhes pertencia o serviço de levar o santuário, e o levavam aos ombros.

[[v4-7-10]]

^<<v4-7-10,10>>^ Os príncipes fizeram também oferta para a dedicação do altar, no dia em que foi ungido; e os príncipes apresentaram as suas ofertas perante o altar.

[[v4-7-11]]

^<<v4-7-11,11>>^ E disse o Senhor a Moisés: Cada príncipe oferecerá a sua oferta, cada qual no seu dia, para a dedicação do altar.

[[v4-7-12]]

^<<v4-7-12,12>>^ O que ofereceu a sua oferta no primeiro dia foi Nasom, filho de Aminadabe, da tribo de Judá.

[[v4-7-13]]

^<<v4-7-13,13>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambas cheias de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-14]]

^<<v4-7-14,14>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-15]]

^<<v4-7-15,15>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-16]]

^<<v4-7-16,16>>^ um bode para oferta pelo pecado;

[[v4-7-17]]

^<<v4-7-17,17>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Nasom, filho de Aminadabe.

[[v4-7-18]]

^<<v4-7-18,18>>^ No segundo dia fez a sua oferta Netanel, filho de Zuar, príncipe de Issacar.

[[v4-7-19]]

^<<v4-7-19,19>>^ E como sua oferta ofereceu uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-20]]

^<<v4-7-20,20>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-21]]

^<<v4-7-21,21>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-22]]

^<<v4-7-22,22>>^ um bode para oferta pelo pecado;

[[v4-7-23]]

^<<v4-7-23,23>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Netanel, filho de Zuar.

[[v4-7-24]]

^<<v4-7-24,24>>^ No terceiro dia fez a sua oferta Eliabe, filho de Helom, príncipe dos filhos de Zebulom.

[[v4-7-25]]

^<<v4-7-25,25>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-26]]

^<<v4-7-26,26>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-27]]

^<<v4-7-27,27>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-28]]

^<<v4-7-28,28>>^ um bode para oferta pelo pecado;

[[v4-7-29]]

^<<v4-7-29,29>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Eliabe, filho de Helom.

[[v4-7-30]]

^<<v4-7-30,30>>^ No quarto dia fez a sua oferta Elizur, filho de Sedeur, príncipe dos filhos de Rúben.

[[v4-7-31]]

^<<v4-7-31,31>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-32]]

^<<v4-7-32,32>>^ uma colher de ouro de dez siclos, cheio de incenso;

[[v4-7-33]]

^<<v4-7-33,33>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-34]]

^<<v4-7-34,34>>^ um bode para oferta pelo pecado;

[[v4-7-35]]

^<<v4-7-35,35>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Elizur, filho de Sedeur.

[[v4-7-36]]

^<<v4-7-36,36>>^ No quinto dia fez a sua oferta Selumiel, filho de Zurisadai, príncipe dos filhos de Simeão.

[[v4-7-37]]

^<<v4-7-37,37>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-38]]

^<<v4-7-38,38>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-39]]

^<<v4-7-39,39>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-40]]

^<<v4-7-40,40>>^ um bode para oferta pelo pecado;

[[v4-7-41]]

^<<v4-7-41,41>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Selumiel, filho de Zurisadai.

[[v4-7-42]]

^<<v4-7-42,42>>^ No sexto dia fez a sua oferta Eliasafe, filho de Deuel, príncipe dos filhos de Gade.

[[v4-7-43]]

^<<v4-7-43,43>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-44]]

^<<v4-7-44,44>>^ uma colher de ouro do dez siclos, cheia de incenso;

[[v4-7-45]]

^<<v4-7-45,45>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto; ,

[[v4-7-46]]

^<<v4-7-46,46>>^ um bode para oferta pelo pecado;

[[v4-7-47]]

^<<v4-7-47,47>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Eliasafe, filho de Deuel,

[[v4-7-48]]

^<<v4-7-48,48>>^ No sétimo dia fez a sua oferta Elisama, filho de Amiúde, príncipe dos filhos de Efraim.

[[v4-7-49]]

^<<v4-7-49,49>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassado com azeite, para oferta de cereais;

[[v4-7-50]]

^<<v4-7-50,50>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-51]]

^<<v4-7-51,51>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-52]]

^<<v4-7-52,52>>^ um bode para oferta pelo pecado;

[[v4-7-53]]

^<<v4-7-53,53>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Elisama, filho de Amiúde.

[[v4-7-54]]

^<<v4-7-54,54>>^ No oitavo dia fez a sua oferta Gamaliel, filho de Pedazur, príncipe dos filhos de Manassés.

[[v4-7-55]]

^<<v4-7-55,55>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-56]]

^<<v4-7-56,56>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-57]]

^<<v4-7-57,57>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-58]]

^<<v4-7-58,58>>^ um bode para oferta pelo pecado;

[[v4-7-59]]

^<<v4-7-59,59>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Gamaliel, filho de Pedazur.

[[v4-7-60]]

^<<v4-7-60,60>>^ No dia nono fez a sua oferta Abidã, filho de Gideôni, príncipe dos filhos de Benjamim.

[[v4-7-61]]

^<<v4-7-61,61>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-62]]

^<<v4-7-62,62>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-63]]

^<<v4-7-63,63>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-64]]

^<<v4-7-64,64>>^ um bode para oferta pelo pecado;

[[v4-7-65]]

^<<v4-7-65,65>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Abidã, filho de Gideôni.

[[v4-7-66]]

^<<v4-7-66,66>>^ No décimo dia fez a sua oferta Aiezer, filho de Amisadai, príncipe filhos de Dã.

[[v4-7-67]]

^<<v4-7-67,67>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-68]]

^<<v4-7-68,68>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-69]]

^<<v4-7-69,69>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-70]]

^<<v4-7-70,70>>^ um bode para oferta pelo pecado;

[[v4-7-71]]

^<<v4-7-71,71>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Aiezer, filho de Amisadai.

[[v4-7-72]]

^<<v4-7-72,72>>^ No dia undécimo fez a sua oferta Pagiel, filho de Ocrã, príncipe dos filhos de Aser.

[[v4-7-73]]

^<<v4-7-73,73>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-74]]

^<<v4-7-74,74>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-75]]

^<<v4-7-75,75>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-76]]

^<<v4-7-76,76>>^ um bode para oferta pelo pecado;

[[v4-7-77]]

^<<v4-7-77,77>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta do Pagiel, filho do Ocrã.

[[v4-7-78]]

^<<v4-7-78,78>>^ No duodécimo dia fez a sua oferta Airá, filho de Enã, príncipe dos filhos de Naftali.

[[v4-7-79]]

^<<v4-7-79,79>>^ A sua oferta foi uma salva de prata do peso de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário; ambos cheios de flor de farinha amassada com azeite, para oferta de cereais;

[[v4-7-80]]

^<<v4-7-80,80>>^ uma colher de ouro de dez siclos, cheia de incenso;

[[v4-7-81]]

^<<v4-7-81,81>>^ um novilho, um carneiro, um cordeiro de um ano, para holocausto;

[[v4-7-82]]

^<<v4-7-82,82>>^ um bode para oferta pelo pecado;

[[v4-7-83]]

^<<v4-7-83,83>>^ e para sacrifício de ofertas pacíficas dois bois, cinco carneiros, cinco bodes, cinco cordeiros de um ano; esta foi a oferta de Airá, filho de Enã.

[[v4-7-84]]

^<<v4-7-84,84>>^ Esta foi a oferta dedicatória do altar, feita pelos príncipes de Israel, no dia em que foi ungido: doze salvas de prata, doze bacias de prata, doze colheres de ouro,

[[v4-7-85]]

^<<v4-7-85,85>>^ pesando cada salva de prata cento e trinta siclos, e cada bacia setenta; toda a prata dos vasos foi dois mil e quatrocentos siclos, segundo o siclo do santuário;

[[v4-7-86]]

^<<v4-7-86,86>>^ doze colheres de ouro cheias de incenso, pesando cada colher dez siclos, segundo o siclo do santuário; todo o ouro das colheres foi cento e vinte siclos.

[[v4-7-87]]

^<<v4-7-87,87>>^ Todos os animais para holocausto foram doze novilhos, doze carneiros, e doze cordeiros de um ano, com as respectivas ofertas de cereais; e para oferta pelo pecado, doze bodes;

[[v4-7-88]]

^<<v4-7-88,88>>^ e todos os animais para sacrifício das ofertas pacíficas foram vinte e quatro novilhos, sessenta carneiros, sessenta bodes, e sessenta cordeiros de um ano. Esta foi a oferta dedicatória do altar depois que foi ungido.

[[v4-7-89]]

^<<v4-7-89,89>>^ Quando Moisés entrava na tenda da revelação para falar com o Senhor, ouvia a voz que lhe falava de cima do propiciatório, que está sobre a arca do testemunho entre os dois querubins; assim ele lhe falava.

'''

xref:004-numeros/004-numeros-006.adoc#v4-6-0[&#60; Capítulo Anterior] | <<v4-7-0,Topo>> | xref:004-numeros/004-numeros-008.adoc#v4-8-0[Próximo Capítulo &#62;]