include::./index.adoc[]

[[v4-19-0]]
=== Números, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-19-1]]

^<<v4-19-1,1>>^ Disse mais o Senhor a Moisés e a Arão:

[[v4-19-2]]

^<<v4-19-2,2>>^ Este é o estatuto da lei que o Senhor ordenou, dizendo: Dize aos filhos de Israel que te tragam uma novilha vermelha sem defeito, que não tenha mancha, e sobre a qual não se tenha posto jugo:

[[v4-19-3]]

^<<v4-19-3,3>>^ Entregá-la-eis a Eleazar, o sacerdote; ele a tirará para fora do arraial, e a imolarão diante dele.

[[v4-19-4]]

^<<v4-19-4,4>>^ Eleazar, o sacerdote, tomará do sangue com o dedo, e dele espargirá para a frente da tenda da revelação sete vezes.

[[v4-19-5]]

^<<v4-19-5,5>>^ Então à vista dele se queimará a novilha, tanto o couro e a carne, como o sangue e o excremento;

[[v4-19-6]]

^<<v4-19-6,6>>^ e o sacerdote, tomando pau do cedro, hissopo e carmesim, os lançará no meio do fogo que queima a novilha.

[[v4-19-7]]

^<<v4-19-7,7>>^ Então o sacerdote lavará as suas vestes e banhará o seu corpo em água; depois entrará no arraial; e o sacerdote será imundo até a tarde.

[[v4-19-8]]

^<<v4-19-8,8>>^ Também o que a tiver queimado lavará as suas vestes e banhará o seu corpo em água, e será imundo até a tarde.

[[v4-19-9]]

^<<v4-19-9,9>>^ E um homem limpo recolherá a cinza da novilha, e a depositará fora do arraial, num lugar limpo, e ficará ela guardada para a congregação dos filhos de Israel, para a água de purificação; é oferta pelo pecado.

[[v4-19-10]]

^<<v4-19-10,10>>^ E o que recolher a cinza da novilha lavará as suas vestes e será imundo até a tarde; isto será por estatuto perpétuo aos filhos de Israel e ao estrangeiro que peregrina entre eles.

[[v4-19-11]]

^<<v4-19-11,11>>^ Aquele que tocar o cadáver de algum homem, será imundo sete dias.

[[v4-19-12]]

^<<v4-19-12,12>>^ Ao terceiro dia o mesmo se purificará com aquela água, e ao sétimo dia se tornará limpo; mas, se ao terceiro dia não se purificar, não se tornará limpo ao sétimo dia.

[[v4-19-13]]

^<<v4-19-13,13>>^ Todo aquele que tocar o cadáver de algum homem que tenha morrido, e não se purificar, contamina o tabernáculo do Senhor; e essa alma será extirpada de Israel; porque a água da purificação não foi espargida sobre ele, continua imundo; a sua imundícia está ainda sobre ele.

[[v4-19-14]]

^<<v4-19-14,14>>^ Esta é a lei, quando um homem morrer numa tenda: todo aquele que entrar na tenda, e todo aquele que nela estiver, será imundo sete dias.

[[v4-19-15]]

^<<v4-19-15,15>>^ Também, todo vaso aberto, sobre que não houver pano atado, será imundo.

[[v4-19-16]]

^<<v4-19-16,16>>^ E todo aquele que no campo tocar alguém que tenha sido morto pela espada, ou outro cadáver, ou um osso de algum homem, ou uma sepultura, será imundo sete dias.

[[v4-19-17]]

^<<v4-19-17,17>>^ Para o imundo, pois, tomarão da cinza da queima da oferta pelo pecado, e sobre ela deitarão água viva num vaso;

[[v4-19-18]]

^<<v4-19-18,18>>^ e um homem limpo tomará hissopo, e o molhará na água, e a espargirá sobre a tenda, sobre todos os objetos e sobre as pessoas que ali estiverem, como também sobre aquele que tiver tocado o osso, ou o que foi morto, ou o que faleceu, ou a sepultura.

[[v4-19-19]]

^<<v4-19-19,19>>^ Também o limpo, ao terceiro dia e ao sétimo dia, a espargirá sobre o imundo, e ao sétimo dia o purificará; e o que era imundo lavará as suas vestes, e se banhará em água, e à tarde será limpo.

[[v4-19-20]]

^<<v4-19-20,20>>^ Mas o que estiver imundo e não se purificar, esse será extirpado do meio da assembléia, porquanto contaminou o santuário do Senhor; a água de purificação não foi espargida sobre ele; é imundo.

[[v4-19-21]]

^<<v4-19-21,21>>^ Isto lhes será por estatuto perpétuo: o que espargir a água de purificação lavará as suas vestes; e o que tocar a água de purificação será imundo até a tarde.

[[v4-19-22]]

^<<v4-19-22,22>>^ E tudo quanto o imundo tocar também será imundo; e a pessoa que tocar naquilo será imunda até a tarde.

'''

xref:004-numeros/004-numeros-018.adoc#v4-18-0[&#60; Capítulo Anterior] | <<v4-19-0,Topo>> | xref:004-numeros/004-numeros-020.adoc#v4-20-0[Próximo Capítulo &#62;]