include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-20-1]]

^<<v4-20-1,1>>^ Os filhos de Israel, a congregação toda, chegaram ao deserto de Zim no primeiro mês, e o povo ficou em Cades. Ali morreu Miriã, e ali foi sepultada.

[[v4-20-2]]

^<<v4-20-2,2>>^ Ora, não havia água para a congregação; pelo que se ajuntaram contra Moisés e Arão.

[[v4-20-3]]

^<<v4-20-3,3>>^ E o povo contendeu com Moisés, dizendo: Oxalá tivéssemos perecido quando pereceram nossos irmãos perante o Senhor!

[[v4-20-4]]

^<<v4-20-4,4>>^ Por que trouxestes a congregação do Senhor a este deserto, para que morramos aqui, nós e os nossos animais?

[[v4-20-5]]

^<<v4-20-5,5>>^ E por que nos fizestes subir do Egito, para nos trazer a este mau lugar? lugar onde não há semente, nem figos, nem vides, nem romãs, nem mesmo água para beber.

[[v4-20-6]]

^<<v4-20-6,6>>^ Então Moisés e Arão se foram da presença da assembléia até a porta da tenda da revelação, e se lançaram com o rosto em terra; e a glória do Senhor lhes apareceu.

[[v4-20-7]]

^<<v4-20-7,7>>^ E o Senhor disse a Moisés:

[[v4-20-8]]

^<<v4-20-8,8>>^ Toma a vara, e ajunta a congregação, tu e Arão, teu irmão, e falai à rocha perante os seus olhos, que ela dê as suas águas. Assim lhes tirarás água da rocha, e darás a beber à congregação e aos seus animais.

[[v4-20-9]]

^<<v4-20-9,9>>^ Moisés, pois, tomou a vara de diante do senhor, como este lhe ordenou.

[[v4-20-10]]

^<<v4-20-10,10>>^ Moisés e Arão reuniram a assembléia diante da rocha, e Moisés disse-lhes: Ouvi agora, rebeldes! Porventura tiraremos água desta rocha para vós?

[[v4-20-11]]

^<<v4-20-11,11>>^ Então Moisés levantou a mão, e feriu a rocha duas vezes com a sua vara, e saiu água copiosamente, e a congregação bebeu, e os seus animais.

[[v4-20-12]]

^<<v4-20-12,12>>^ Pelo que o Senhor disse a Moisés e a Arão: Porquanto não me crestes a mim, para me santificardes diante dos filhos de Israel, por isso não introduzireis esta congregação na terra que lhes dei.

[[v4-20-13]]

^<<v4-20-13,13>>^ Estas são as águas de Meribá, porque ali os filhos de Israel contenderam com o Senhor, que neles se santificou.

[[v4-20-14]]

^<<v4-20-14,14>>^ De Cades, Moisés enviou mensageiros ao rei de Edom, dizendo: Assim diz teu irmão Israel: Tu sabes todo o trabalho que nos tem sobrevindo;

[[v4-20-15]]

^<<v4-20-15,15>>^ como nossos pais desceram ao Egito, e nós no Egito habitamos muito tempo; e como os egípcios nos maltrataram, a nós e a nossos pais;

[[v4-20-16]]

^<<v4-20-16,16>>^ e quando clamamos ao Senhor, ele ouviu a nossa voz, e mandou um anjo, e nos tirou do Egito; e eis que estamos em Cades, cidade na extremidade dos teus termos.

[[v4-20-17]]

^<<v4-20-17,17>>^ Deixa-nos, pois, passar pela tua terra; não passaremos pelos campos, nem pelas vinhas, nem beberemos a água dos poços; iremos pela estrada real, não nos desviando para a direita nem para a esquerda, até que tenhamos passado os teus termos.

[[v4-20-18]]

^<<v4-20-18,18>>^ Respondeu-lhe Edom: Não passaras por mim, para que eu não saia com a espada ao teu encontro.

[[v4-20-19]]

^<<v4-20-19,19>>^ Os filhos de Israel lhe replicaram: Subiremos pela estrada real; e se bebermos das tuas águas, eu e o meu gado, darei o preço delas; sob condição de eu nada mais fazer, deixa-me somente passar a pé.

[[v4-20-20]]

^<<v4-20-20,20>>^ Edom, porém, respondeu: Não passarás. E saiu-lhe ao encontro com muita gente e com mão forte.

[[v4-20-21]]

^<<v4-20-21,21>>^ Assim recusou Edom deixar Israel passar pelos seus termos; pelo que Israel se desviou dele.

[[v4-20-22]]

^<<v4-20-22,22>>^ Então partiram de Cades; e os filhos de Israel, a congregação toda, chegaram ao monte Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ E falou o Senhor a Moisés e a Arão no monte Hor, nos termos da terra de Edom, dizendo:

[[v4-20-24]]

^<<v4-20-24,24>>^ Arão será recolhido a seu povo, porque não entrará na terra que dei aos filhos de Israel, porquanto fostes rebeldes contra a minha palavra no tocante às águas de Meribá.

[[v4-20-25]]

^<<v4-20-25,25>>^ Toma a Arão e a Eleazar, seu filho, e faze-os subir ao monte Hor;

[[v4-20-26]]

^<<v4-20-26,26>>^ e despe a Arão as suas vestes, e as veste a Eleazar, seu filho, porque Arão será recolhido, e morrerá ali.

[[v4-20-27]]

^<<v4-20-27,27>>^ Fez, pois, Moisés como o Senhor lhe ordenara; e subiram ao monte Hor perante os olhos de toda a congregação.

[[v4-20-28]]

^<<v4-20-28,28>>^ Moisés despiu a Arão as vestes, e as vestiu a Eleazar, seu filho; e morreu Arão ali sobre o cume do monte; e Moisés e Eleazar desceram do monte.

[[v4-20-29]]

^<<v4-20-29,29>>^ Vendo, pois, toda a congregação que Arão era morto, chorou-o toda a casa de Israel por trinta dias.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]