include::./index.adoc[]

[[v4-1-0]]
=== Números, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-1-1]]

^<<v4-1-1,1>>^ Falou o Senhor a Moisés no deserto de Sinai, na tenda da revelação, no primeiro dia do segundo mês, no segundo ano depois da saída dos filhos de Israel da terra do Egito, dizendo:

[[v4-1-2]]

^<<v4-1-2,2>>^ Tomai a soma de toda a congregação dos filhos de Israel, segundo as suas famílias, segundo as casas de seus pais, conforme o número dos nomes de todo homem, cabeça por cabeça;

[[v4-1-3]]

^<<v4-1-3,3>>^ os da idade de vinte anos para cima, isto é, todos os que em Israel podem sair à guerra, a esses contareis segundo os seus exércitos, tu e Arão.

[[v4-1-4]]

^<<v4-1-4,4>>^ Estará convosco de cada tribo um homem que seja cabeça da casa de seus pais.

[[v4-1-5]]

^<<v4-1-5,5>>^ Estes, pois, são os nomes dos homens que vos assistirão: de Rúben Elizur, filho de Sedeur;

[[v4-1-6]]

^<<v4-1-6,6>>^ de Simeão, Selumiel, filho de Zurisadai;

[[v4-1-7]]

^<<v4-1-7,7>>^ de Judá, Nasom, filho de Aminadabe;

[[v4-1-8]]

^<<v4-1-8,8>>^ de Issacar, Netanel, filho de Zuar;

[[v4-1-9]]

^<<v4-1-9,9>>^ de Zebulom, Eliabe, filho de Helom;

[[v4-1-10]]

^<<v4-1-10,10>>^ dos filhos de José: de Efraim, Elisama, filho de Amiúde; de Manassés, Gamaliel, filho de Pedazur;

[[v4-1-11]]

^<<v4-1-11,11>>^ de Benjamim, Abidã, filho de Gideôni;

[[v4-1-12]]

^<<v4-1-12,12>>^ de Dã, Aizer, filho de Amisadai;

[[v4-1-13]]

^<<v4-1-13,13>>^ de Aser, Pagiel, filho de Ocrã;

[[v4-1-14]]

^<<v4-1-14,14>>^ de Gade, Eliasafe, filho de o Deuel;

[[v4-1-15]]

^<<v4-1-15,15>>^ de Naftali, Airá, Filho de Enã.

[[v4-1-16]]

^<<v4-1-16,16>>^ São esses os que foram chamados da congregação, os príncipes das tribos de seus pais, os cabeças dos milhares de Israel.

[[v4-1-17]]

^<<v4-1-17,17>>^ Então tomaram Moisés e Arão a esses homens que são designados por nome;

[[v4-1-18]]

^<<v4-1-18,18>>^ e, tendo ajuntado toda a congregação no primeiro dia do segundo mês, declararam a linhagem deles segundo as suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, cabeça por cabeça;

[[v4-1-19]]

^<<v4-1-19,19>>^ como o Senhor ordenara a Moisés, assim este os contou no deserto de Sinai.

[[v4-1-20]]

^<<v4-1-20,20>>^ Os filhos de Rúben o primogênito de Israel, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes, cabeça por cabeça, todo homem de vinte anos para cima, todos os que podiam sair à guerra,

[[v4-1-21]]

^<<v4-1-21,21>>^ os que foram contados deles, da tribo de Rúben eram quarenta e seis mil e quinhentos.

[[v4-1-22]]

^<<v4-1-22,22>>^ Dos filhos de Simeão, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes, cabeça por cabeça, todo homem de vinte anos para cima, todos os que podiam sair à guerra,

[[v4-1-23]]

^<<v4-1-23,23>>^ os que foram contados deles, da tribo de Simeão, eram cinqüenta e nove mil e trezentos.

[[v4-1-24]]

^<<v4-1-24,24>>^ Dos filhos de Gade, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair a guerra,

[[v4-1-25]]

^<<v4-1-25,25>>^ os que foram contados deles, da tribo de Gade, eram quarenta e cinco mil seiscentos e cinqüenta.

[[v4-1-26]]

^<<v4-1-26,26>>^ Dos filhos de Judá, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair a guerra,

[[v4-1-27]]

^<<v4-1-27,27>>^ os que foram contados deles, da tribo de Judá, eram setenta e quatro mil e seiscentos.

[[v4-1-28]]

^<<v4-1-28,28>>^ Dos filhos de Issacar, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair a guerra,

[[v4-1-29]]

^<<v4-1-29,29>>^ os que foram contados deles, da tribo de Issacar, eram cinqüenta e quatro mil e quatrocentos.

[[v4-1-30]]

^<<v4-1-30,30>>^ Dos filhos de Zebulom, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair a guerra,

[[v4-1-31]]

^<<v4-1-31,31>>^ os que foram contados deles, da tribo de Zebulom, eram cinqüenta e sete mil e quatrocentos.

[[v4-1-32]]

^<<v4-1-32,32>>^ Dos filhos de José: dos filhos de Efraim, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair à guerra,

[[v4-1-33]]

^<<v4-1-33,33>>^ os que foram contados deles, da tribo de Efraim, eram quarenta mil e quinhentos;

[[v4-1-34]]

^<<v4-1-34,34>>^ e dos filhos de Manassés, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair à guerra,

[[v4-1-35]]

^<<v4-1-35,35>>^ os que foram contados deles, da tribo de Manassés, eram trinta e dois mil e duzentos.

[[v4-1-36]]

^<<v4-1-36,36>>^ Dos filhos de Benjamim, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair à guerra,

[[v4-1-37]]

^<<v4-1-37,37>>^ os que foram contados deles, da tribo de Benjamim, eram trinta e cinco mil e quatrocentos.

[[v4-1-38]]

^<<v4-1-38,38>>^ Dos filhos de Dã, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair à guerra,

[[v4-1-39]]

^<<v4-1-39,39>>^ os que foram contados deles, da tribo de Dã, eram sessenta e dois mil e setecentos.

[[v4-1-40]]

^<<v4-1-40,40>>^ Dos filhos de Aser, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o numero dos nomes dos de vinte anos para cima, todos os que podiam sair à guerra,

[[v4-1-41]]

^<<v4-1-41,41>>^ os que foram contados deles, da tribo de Aser, eram quarenta e um mil e quinhentos.

[[v4-1-42]]

^<<v4-1-42,42>>^ Dos filhos de Naftali, as suas gerações, pelas suas famílias, segundo as casas de seus pais, conforme o número dos nomes dos de vinte anos para cima, todos os que podiam sair a guerra,

[[v4-1-43]]

^<<v4-1-43,43>>^ os que foram contados deles, da tribo de Naftali, eram cinqüenta e três mil e quatrocentos,

[[v4-1-44]]

^<<v4-1-44,44>>^ São esses os que foram contados por Moisés e Arão, e pelos príncipes de Israel, sendo estes doze homens e representando cada um a casa de seus pais.

[[v4-1-45]]

^<<v4-1-45,45>>^ Assim todos os que foram contados dos filhos de Israel, segundo as casas de seus pais, de vinte anos para cima, todos os de Israel que podiam sair à guerra,

[[v4-1-46]]

^<<v4-1-46,46>>^ sim, todos os que foram contados eram : seiscentos e três mil quinhentos e cinqüenta.

[[v4-1-47]]

^<<v4-1-47,47>>^ Mas os levitas, segundo a tribo de e seus pais, não foram contados entre eles;

[[v4-1-48]]

^<<v4-1-48,48>>^ porquanto o Senhor dissera a Moisés:

[[v4-1-49]]

^<<v4-1-49,49>>^ Somente não contarás a tribo de Levi, nem tomarás a soma deles entre os filhos de Israel;

[[v4-1-50]]

^<<v4-1-50,50>>^ mas tu põe os levitas sobre o tabernáculo do testemunho, sobre todos os seus móveis, e sobre tudo o que lhe pertence. Eles levarão o tabernáculo e todos os seus móveis, e o administrarão; e acampar-se-ão ao redor do tabernáculo.

[[v4-1-51]]

^<<v4-1-51,51>>^ Quando o tabernáculo houver de partir, os levitas o desarmarão; e quando o tabernáculo se houver de assentar, os levitas o armarão; e o estranho que se chegar será morto.

[[v4-1-52]]

^<<v4-1-52,52>>^ Os filhos de Israel acampar-se-ão, cada um no seu arraial, e cada um junto ao seu estandarte, segundo os seus exércitos.

[[v4-1-53]]

^<<v4-1-53,53>>^ Mas os levitas acampar-se-ão ao redor do tabernáculo do testemunho, para que não suceda acender-se ira contra a congregação dos filhos de Israel; pelo que os levitas terão o cuidado da guarda do tabernáculo do testemunho.

[[v4-1-54]]

^<<v4-1-54,54>>^ Assim fizeram os filhos de Israel; conforme tudo o que o Senhor ordenara a Moisés, assim o fizeram.

'''

xref:003-levitico/003-levitico-027.adoc#v3-27-0[&#60; Capítulo Anterior] | <<v4-1-0,Topo>> | xref:004-numeros/004-numeros-002.adoc#v4-2-0[Próximo Capítulo &#62;]