include::./index.adoc[]

[[v4-31-0]]
=== Números, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-31-1]]

^<<v4-31-1,1>>^ Disse mais o Senhor a Moisés:

[[v4-31-2]]

^<<v4-31-2,2>>^ Vinga os filhos de Israel dos midianitas; depois serás recolhido ao teu povo.

[[v4-31-3]]

^<<v4-31-3,3>>^ Falou, pois, Moisés ao povo, dizendo: Armai homens dentre vós para a guerra, a fim de que saiam contra Midiã, para executarem a vingança do Senhor sobre Midiã.

[[v4-31-4]]

^<<v4-31-4,4>>^ Enviareis à guerra mil de cada tribo entre todas as tribos de Israel.

[[v4-31-5]]

^<<v4-31-5,5>>^ Assim foram entregues dos milhares de Israel, mil de cada tribo, doze mil armados para a peleja.

[[v4-31-6]]

^<<v4-31-6,6>>^ E Moisés mandou à guerra esses mil de cada tribo, e com eles Finéias, filho de Eleazar, o sacerdote, o qual levava na mão os vasos do santuário e as trombetas para tocarem o alarme.

[[v4-31-7]]

^<<v4-31-7,7>>^ E pelejaram contra Midiã, como o senhor ordenara a Moisés; e mataram a todos os homens.

[[v4-31-8]]

^<<v4-31-8,8>>^ Com eles mataram também os reis de Midiã, a saber, Evi, Requem, Zur, Hur e Reba, cinco reis de Midiã; igualmente mataram à espada a Balaão, filho de Beor.

[[v4-31-9]]

^<<v4-31-9,9>>^ Também os filhos de Israel levaram presas as mulheres dos midianitas e os seus pequeninos; e despojaram-nos de todo o seu gado, e de todos os seus rebanhos, enfim, de todos os seus bens;

[[v4-31-10]]

^<<v4-31-10,10>>^ queimaram a fogo todas as cidades em que eles habitavam e todos os seus acampamentos;

[[v4-31-11]]

^<<v4-31-11,11>>^ tomaram todo o despojo e toda a presa, tanto de homens como de animais;

[[v4-31-12]]

^<<v4-31-12,12>>^ e trouxeram os cativos e a presa e o despojo a Moisés, a Eleazar, o sacerdote, e à congregação dos filhos de Israel, ao arraial, nas planícies de Moabe, que estão junto do Jordão, na altura de Jericó.

[[v4-31-13]]

^<<v4-31-13,13>>^ Saíram, pois, Moisés e Eleazar, o sacerdote, e todos os príncipes da congregação, ao encontro deles fora do arraial.

[[v4-31-14]]

^<<v4-31-14,14>>^ E indignou-se Moisés contra os oficiais do exército, chefes dos milhares e chefes das centenas, que vinham do serviço da guerra,

[[v4-31-15]]

^<<v4-31-15,15>>^ e lhes disse: Deixastes viver todas as mulheres?

[[v4-31-16]]

^<<v4-31-16,16>>^ Eis que estas foram as que, por conselho de Balaão, fizeram que os filhos de Israel pecassem contra o Senhor no caso de Peor, pelo que houve a praga entre a congregação do Senhor.

[[v4-31-17]]

^<<v4-31-17,17>>^ Agora, pois, matai todos os meninos entre as crianças, e todas as mulheres que conheceram homem, deitando-se com ele.

[[v4-31-18]]

^<<v4-31-18,18>>^ Mas todas as meninas, que não conheceram homem, deitando-se com ele, deixai-as viver para vós.

[[v4-31-19]]

^<<v4-31-19,19>>^ Acampai-vos por sete dias fora do arraial; todos vós, tanto o que tiver matado alguma pessoa, como o que tiver tocado algum morto, ao terceiro dia e ao sétimo dia purificai-vos, a vós e aos vossos cativos.

[[v4-31-20]]

^<<v4-31-20,20>>^ Também purificai-vos no tocante a todo vestido, e todo artigo de peles, e toda obra de pelos de cabras, e todo utensílio de madeira.

[[v4-31-21]]

^<<v4-31-21,21>>^ Então Eleazar, o sacerdote, disse aos homens de guerra que tinham saído à peleja: Este é o estatuto da lei que o Senhor ordenou a Moisés:

[[v4-31-22]]

^<<v4-31-22,22>>^ o ouro, a prata, o bronze, o ferro, o estanho, o chumbo,

[[v4-31-23]]

^<<v4-31-23,23>>^ tudo o que pode resistir ao fogo, fálo-eis passar pelo fogo, e ficará limpo; todavia será purificado com a água de purificação; e tudo o que não pode resistir ao fogo, fá-lo-eis passar pela água.

[[v4-31-24]]

^<<v4-31-24,24>>^ Também lavareis as vossas vestes ao sétimo dia, e ficareis limpos, e depois entrareis no arraial.

[[v4-31-25]]

^<<v4-31-25,25>>^ Disse mais o Senhor a Moisés:

[[v4-31-26]]

^<<v4-31-26,26>>^ Faze a soma da presa que foi tomada, tanto de homens como de animais, tu e Eleazar, o sacerdote, e os cabeças das casas paternas da congregação;

[[v4-31-27]]

^<<v4-31-27,27>>^ e divide-a em duas partes iguais, entre os que, hábeis na guerra, saíram à peleja, e toda a congregação.

[[v4-31-28]]

^<<v4-31-28,28>>^ E tomarás para o Senhor um tributo dos homens de guerra, que saíram à peleja; um em quinhentos, assim dos homens, como dos bois, dos jumentos e dos rebanhos;

[[v4-31-29]]

^<<v4-31-29,29>>^ da sua metade o tomareis, e o dareis a Eleazar, o sacerdote, para a oferta alçada do Senhor.

[[v4-31-30]]

^<<v4-31-30,30>>^ Mas da metade que pertence aos filhos de Israel tomarás um de cada cinqüenta, tanto dos homens, como dos bois, dos jumentos, dos rebanhos, enfim, de todos os animais, e os darás aos levitas, que estão encarregados do serviço do tabernáculo do Senhor.

[[v4-31-31]]

^<<v4-31-31,31>>^ Fizeram, pois, Moisés e Eleazar, o sacerdote, como o Senhor ordenara a Moisés.

[[v4-31-32]]

^<<v4-31-32,32>>^ Ora, a presa, o restante do despojo que os homens de guerra tomaram, foi de seiscentas e setenta e cinco mil ovelhas,

[[v4-31-33]]

^<<v4-31-33,33>>^ setenta e dois mil bois,

[[v4-31-34]]

^<<v4-31-34,34>>^ e sessenta e um mil jumentos;

[[v4-31-35]]

^<<v4-31-35,35>>^ e trinta e duas mil pessoas, ao todo, do sexo feminino, que ainda se conservavam virgens.

[[v4-31-36]]

^<<v4-31-36,36>>^ Assim a metade, que era a porção dos que saíram à guerra, foi em número de trezentas e trinta e sete mil e quinhentas ovelhas;

[[v4-31-37]]

^<<v4-31-37,37>>^ e das ovelhas foi o tributo para o Senhor seiscentas e setenta e cinco.

[[v4-31-38]]

^<<v4-31-38,38>>^ E foram os bois trinta e seis mil, dos quais foi o tributo para o Senhor setenta e dois.

[[v4-31-39]]

^<<v4-31-39,39>>^ E foram os jumentos trinta mil e quinhentos, dos quais foi o tributo para o Senhor sessenta e um.

[[v4-31-40]]

^<<v4-31-40,40>>^ E houve de pessoas dezesseis mil, das quais foi o tributo para o Senhor trinta e duas pessoas.

[[v4-31-41]]

^<<v4-31-41,41>>^ Moisés, pois, deu a Eleazar, o sacerdote, o tributo, que era a oferta alçada do Senhor, como o Senhor ordenara a Moisés.

[[v4-31-42]]

^<<v4-31-42,42>>^ E da metade que era dos filhos de Israel, que Moisés separara da que era dos homens que pelejaram

[[v4-31-43]]

^<<v4-31-43,43>>^ &#123;ora, a metade que coube à congregação foi, das ovelhas, trezentas e trinta e sete mil e quinhentas;

[[v4-31-44]]

^<<v4-31-44,44>>^ dos bois trinta e seis mil;

[[v4-31-45]]

^<<v4-31-45,45>>^ dos jumentos trinta mil e quinhentos;

[[v4-31-46]]

^<<v4-31-46,46>>^ e das pessoas dezesseis mil&#125;,

[[v4-31-47]]

^<<v4-31-47,47>>^ isto é, da metade que era dos filhos de Israel, Moisés tomou um de cada cinqüenta, tanto dos homens como dos animais, e os deu aos levitas, que estavam encarregados do serviço do tabernáculo do Senhor; como o Senhor ordenara a Moisés.

[[v4-31-48]]

^<<v4-31-48,48>>^ Então chegaram-se a Moisés os oficiais que estavam sobre os milhares do exército, os chefes de mil e os chefes de cem,

[[v4-31-49]]

^<<v4-31-49,49>>^ e disseram-lhe: Teus servos tomaram a soma dos homens de guerra que estiveram sob o nosso comando; e não falta nenhum de nós.

[[v4-31-50]]

^<<v4-31-50,50>>^ Pelo que trouxemos a oferta do Senhor, cada um o que achou, artigos de ouro, cadeias, braceletes, anéis, arrecadas e colares, para fazer expiação pelas nossas almas perante o Senhor.

[[v4-31-51]]

^<<v4-31-51,51>>^ Assim Moisés e Eleazar, o sacerdote, tomaram deles o ouro, todo feito em jóias.

[[v4-31-52]]

^<<v4-31-52,52>>^ E todo o ouro da oferta alçada que os chefes de mil e os chefes de cem fizeram ao Senhor, foi dezesseis mil setecentos e cinqüenta siclos

[[v4-31-53]]

^<<v4-31-53,53>>^ &#123;pois os homens de guerra haviam tomado despojo, cada um para si&#125;.

[[v4-31-54]]

^<<v4-31-54,54>>^ Assim receberam Moisés e Eleazar, o sacerdote, o ouro dos chefes de mil e dos chefes de cem, e o puseram na tenda da revelação por memorial para os filhos de Israel perante o Senhor.

'''

xref:004-numeros/004-numeros-030.adoc#v4-30-0[&#60; Capítulo Anterior] | <<v4-31-0,Topo>> | xref:004-numeros/004-numeros-032.adoc#v4-32-0[Próximo Capítulo &#62;]