include::./index.adoc[]

[[v4-13-0]]
=== Números, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-13-1]]

^<<v4-13-1,1>>^ Então disse o Senhor a Moisés:

[[v4-13-2]]

^<<v4-13-2,2>>^ Envia homens que espiem a terra de Canaã, que eu hei de dar aos filhos de Israel. De cada tribo de seus pais enviarás um homem, sendo cada qual príncipe entre eles.

[[v4-13-3]]

^<<v4-13-3,3>>^ Moisés, pois, enviou-os do deserto de Parã, segundo a ordem do Senhor; eram todos eles homens principais dentre os filhos de Israel.

[[v4-13-4]]

^<<v4-13-4,4>>^ E estes são os seus nomes: da tribo de Rúben, Samua, filho de Zacur;

[[v4-13-5]]

^<<v4-13-5,5>>^ da tribo de Simeão, Safate, filho de Hori;

[[v4-13-6]]

^<<v4-13-6,6>>^ da tribo de Judá, Calebe, filho de Jefoné;

[[v4-13-7]]

^<<v4-13-7,7>>^ da tribo de Issacar, Ioal, filho de José;

[[v4-13-8]]

^<<v4-13-8,8>>^ da tribo de Efraim, Oséias, filho de Num;

[[v4-13-9]]

^<<v4-13-9,9>>^ da tribo de Benjamim, Palti, filho de Rafu;

[[v4-13-10]]

^<<v4-13-10,10>>^ da tribo de Zebulom, Gadiel, filho de Sódi;

[[v4-13-11]]

^<<v4-13-11,11>>^ da tribo de José, pela tribo de Manassés, Gadi, filho de Susi;

[[v4-13-12]]

^<<v4-13-12,12>>^ da tribo de Dã, Amiel, filho de Gemali;

[[v4-13-13]]

^<<v4-13-13,13>>^ da tribo de Aser, Setur, filho de Micael;

[[v4-13-14]]

^<<v4-13-14,14>>^ da tribo de Naftali, Nabi, filho de Vofsi;

[[v4-13-15]]

^<<v4-13-15,15>>^ da tribo de Gade, Geuel, filho de Maqui.

[[v4-13-16]]

^<<v4-13-16,16>>^ Estes são os nomes dos homens que Moisés enviou a espiar a terra. Ora, a Oséias, filho de Num, Moisés chamou Josué.

[[v4-13-17]]

^<<v4-13-17,17>>^ Enviou-os, pois, Moisés a espiar: a terra de Canaã, e disse-lhes: Subi por aqui para o Negebe, e penetrai nas montanhas;

[[v4-13-18]]

^<<v4-13-18,18>>^ e vede a terra, que tal é; e o povo que nela habita, se é forte ou fraco, se pouco ou muito;

[[v4-13-19]]

^<<v4-13-19,19>>^ que tal é a terra em que habita, se boa ou má; que tais são as cidades em que habita, se arraiais ou fortalezas;

[[v4-13-20]]

^<<v4-13-20,20>>^ e que tal é a terra, se gorda ou magra; se nela há árvores, ou não; e esforçai-vos, e tomai do fruto da terra. Ora, a estação era a das uvas temporãs.

[[v4-13-21]]

^<<v4-13-21,21>>^ Assim subiram, e espiaram a terra desde o deserto de Zim, até Reobe, à entrada de Hamate.

[[v4-13-22]]

^<<v4-13-22,22>>^ E subindo para o Negebe, vieram até Hebrom, onde estavam Aimã, Sesai e Talmai, filhos de Anaque. &#123;Ora, Hebrom foi edificada sete anos antes de Zoã no Egito. &#125;

[[v4-13-23]]

^<<v4-13-23,23>>^ Depois vieram até e vale de Escol, e dali cortaram um ramo de vide com um só cacho, o qual dois homens trouxeram sobre uma verga; trouxeram também romãs e figos.

[[v4-13-24]]

^<<v4-13-24,24>>^ Chamou-se aquele lugar o vale de Escol, por causa do cacho que dali cortaram os filhos de Israel.

[[v4-13-25]]

^<<v4-13-25,25>>^ Ao fim de quarenta dias voltaram de espiar a terra.

[[v4-13-26]]

^<<v4-13-26,26>>^ E, chegando, apresentaram-se a Moisés e a Arão, e a toda a congregação dos filhos de Israel, no deserto de Parã, em Cades; e deram-lhes notícias, a eles e a toda a congregação, e mostraram-lhes o fruto da terra.

[[v4-13-27]]

^<<v4-13-27,27>>^ E, dando conta a Moisés, disseram: Fomos à terra a que nos enviaste. Ela, em verdade, mana leite e mel; e este é o seu fruto.

[[v4-13-28]]

^<<v4-13-28,28>>^ Contudo o povo que habita nessa terra é poderoso, e as cidades são fortificadas e mui grandes. Vimos também ali os filhos de Anaque.

[[v4-13-29]]

^<<v4-13-29,29>>^ Os amalequitas habitam na terra do Negebe; os heteus, os jebuseus e os amorreus habitam nas montanhas; e os cananeus habitam junto do mar, e ao longo do rio Jordão.

[[v4-13-30]]

^<<v4-13-30,30>>^ Então Calebe, fazendo calar o povo perante Moisés, disse: Subamos animosamente, e apoderemo-nos dela; porque bem poderemos prevalecer contra ela.

[[v4-13-31]]

^<<v4-13-31,31>>^ Disseram, porém, os homens que subiram com ele: Não poderemos subir contra aquele povo, porque é mais forte do que nos.

[[v4-13-32]]

^<<v4-13-32,32>>^ Assim, perante os filhos de Israel infamaram a terra que haviam espiado, dizendo: A terra, pela qual passamos para espiá-la, é terra que devora os seus habitantes; e todo o povo que vimos nela são homens de grande estatura.

[[v4-13-33]]

^<<v4-13-33,33>>^ Também vimos ali os nefilins, isto é, os filhos de Anaque, que são descendentes dos nefilins; éramos aos nossos olhos como gafanhotos; e assim também éramos aos seus olhos.

'''

xref:004-numeros/004-numeros-012.adoc#v4-12-0[&#60; Capítulo Anterior] | <<v4-13-0,Topo>> | xref:004-numeros/004-numeros-014.adoc#v4-14-0[Próximo Capítulo &#62;]