include::./index.adoc[]

[[v4-36-0]]
=== Números, 36
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-36-1]]

^<<v4-36-1,1>>^ Chegaram-se então os cabeças das casas paternas da família dos filhos de Gileade, filho de Maquir, filho de Manassés, das famílias dos filhos de José, e falaram diante de Moisés, e diante dos príncipes, cabeças das casas paternas dos filhos de Israel,

[[v4-36-2]]

^<<v4-36-2,2>>^ e disseram: O Senhor mandou a meu senhor que por sortes repartisse a terra em herança aos filhos de Israel; e meu senhor recebeu ordem do senhor de dar a herança do nosso irmão Zelofeade às filhas deste.

[[v4-36-3]]

^<<v4-36-3,3>>^ E, se elas se casarem com os filhos das outras tribos de Israel, então a sua herança será diminuída da herança de nossos pais, e acrescentada à herança da tribo a que vierem a pertencer; assim será tirada da sorte da nossa herança.

[[v4-36-4]]

^<<v4-36-4,4>>^ Vindo também o ano do jubileu dos filhos de Israel, a herança delas será acrescentada à herança da tribo a que pertencerem; assim a sua herança será tirada da herança da tribo de nossos pais.

[[v4-36-5]]

^<<v4-36-5,5>>^ Então Moisés falou aos filhos de Israel, segundo a palavra do senhor, dizendo: A tribo dos filhos de José fala o que é justo.

[[v4-36-6]]

^<<v4-36-6,6>>^ Isto é o que o senhor ordenou acerca das filhas de Zelofeade, dizendo: Casem com quem bem parecer aos seus olhos, contanto que se casem na família da tribo de seu pai.

[[v4-36-7]]

^<<v4-36-7,7>>^ Assim a herança dos filhos de Israel não passará de tribo em tribo, pois os filhos de Israel se apegarão cada um a herança da tribo de seus pais.

[[v4-36-8]]

^<<v4-36-8,8>>^ E toda filha que possuir herança em qualquer tribo dos filhos de Israel se casará com alguém da família da tribo de seu pai, para que os filhos de Israel possuam cada um a herança de seus pais.

[[v4-36-9]]

^<<v4-36-9,9>>^ Assim nenhuma herança passará de uma tribo a outra, pois as tribos dos filhos de Israel se apegarão cada uma à sua herança.

[[v4-36-10]]

^<<v4-36-10,10>>^ Como o Senhor ordenara a Moisés, assim fizeram as filhas de Zelofeade;

[[v4-36-11]]

^<<v4-36-11,11>>^ pois Macla, Tirza, Hogla, Milca e Noa, filhas de Zelofeade, se casaram com os filhos de seus tios paternos.

[[v4-36-12]]

^<<v4-36-12,12>>^ Casaram-se nas famílias dos filhos de Manassés, filho de José; assim a sua herança permaneceu na tribo da família de seu pai.

[[v4-36-13]]

^<<v4-36-13,13>>^ São esses os mandamentos e os preceitos que o Senhor ordenou aos filhos de Israel por intermédio de Moisés nas planícies de Moabe, junto ao Jordão, na altura de Jericó.

'''

xref:004-numeros/004-numeros-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[Próximo Capítulo &#62;]