include::./index.adoc[]

[[v4-12-0]]
=== Números, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-12-1]]

^<<v4-12-1,1>>^ Ora, falaram Miriã e Arão contra Moisés, por causa da mulher cuchita que este tomara; porquanto tinha tomado uma mulher cuchita.

[[v4-12-2]]

^<<v4-12-2,2>>^ E disseram: Porventura falou o Senhor somente por Moisés? Não falou também por nós? E o Senhor o ouviu.

[[v4-12-3]]

^<<v4-12-3,3>>^ Ora, Moisés era homem mui manso, mais do que todos os homens que havia sobre a terra.

[[v4-12-4]]

^<<v4-12-4,4>>^ E logo o Senhor disse a Moisés, a Arão e a Miriã: Saí vos três à tenda da revelação. E saíram eles três.

[[v4-12-5]]

^<<v4-12-5,5>>^ Então o Senhor desceu em uma coluna de nuvem, e se pôs à porta da tenda; depois chamou a Arão e a Miriã, e os dois acudiram.

[[v4-12-6]]

^<<v4-12-6,6>>^ Então disse: Ouvi agora as minhas palavras: se entre vós houver profeta, eu, o Senhor, a ele me farei conhecer em visão, em sonhos falarei com ele.

[[v4-12-7]]

^<<v4-12-7,7>>^ Mas não é assim com o meu servo Moisés, que é fiel em toda a minha casa;

[[v4-12-8]]

^<<v4-12-8,8>>^ boca a boca falo com ele, claramente e não em enigmas; pois ele contempla a forma do Senhor. Por que, pois, não temestes falar contra o meu servo, contra Moisés?

[[v4-12-9]]

^<<v4-12-9,9>>^ Assim se acendeu a ira do Senhor contra eles; e ele se retirou;

[[v4-12-10]]

^<<v4-12-10,10>>^ também a nuvem se retirou de sobre a tenda; e eis que Miriã se tornara leprosa, branca como a neve; e olhou Arão para Miriã e eis que estava leprosa.

[[v4-12-11]]

^<<v4-12-11,11>>^ Pelo que Arão disse a Moisés: Ah, meu senhor! rogo-te não ponhas sobre nós este pecado, porque procedemos loucamente, e pecamos.

[[v4-12-12]]

^<<v4-12-12,12>>^ Não seja ela como um morto que, ao sair do ventre de sua mãe, tenha a sua carne já meio consumida.

[[v4-12-13]]

^<<v4-12-13,13>>^ Clamou, pois, Moisés ao Senhor, dizendo: Ó Deus, rogo-te que a cures.

[[v4-12-14]]

^<<v4-12-14,14>>^ Respondeu o Senhor a Moisés: Se seu pai lhe tivesse cuspido na cara não seria envergonhada por sete dias? Esteja fechada por sete dias fora do arraial, e depois se recolherá outra vez.

[[v4-12-15]]

^<<v4-12-15,15>>^ Assim Miriã esteve fechada fora do arraial por sete dias; e o povo não partiu, enquanto Miriã não se recolheu de novo.

[[v4-12-16]]

^<<v4-12-16,16>>^ Mas depois o povo partiu de Hazerote, e acampou-se no deserto de Parã.

'''

xref:004-numeros/004-numeros-011.adoc#v4-11-0[&#60; Capítulo Anterior] | <<v4-12-0,Topo>> | xref:004-numeros/004-numeros-013.adoc#v4-13-0[Próximo Capítulo &#62;]