include::./index.adoc[]

[[v4-8-0]]
=== Números, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-8-1]]

^<<v4-8-1,1>>^ Disse mais o Senhor a Moisés:

[[v4-8-2]]

^<<v4-8-2,2>>^ Fala a Arão, e dize-lhe: Quando acenderes as lâmpadas, as sete lâmpadas alumiarão o espaço em frente do candelabro.

[[v4-8-3]]

^<<v4-8-3,3>>^ Arão, pois, assim fez; acendeu as lâmpadas do candelabro de modo que alumiassem o espaço em frente do mesmo, como o Senhor ordenara a Moisés.

[[v4-8-4]]

^<<v4-8-4,4>>^ Esta era a obra do candelabro, obra de ouro batido; desde o seu pedestal até as suas corolas, era ele de ouro batido; conforme o modelo que o Senhor mostrara a Moisés, assim ele tinha feito o candelabro.

[[v4-8-5]]

^<<v4-8-5,5>>^ Disse mais o Senhor a Moisés:

[[v4-8-6]]

^<<v4-8-6,6>>^ Toma os levitas do meio dos filhos de Israel, e purifica-os;

[[v4-8-7]]

^<<v4-8-7,7>>^ e assim lhes farás, para os purificar: esparge sobre eles a água da purificação; e eles farão passar a navalha sobre todo o seu corpo, e lavarão os seus vestidos, e se purificarão.

[[v4-8-8]]

^<<v4-8-8,8>>^ Depois tomarão um novilho, com a sua oferta de cereais de flor de farinha amassada com azeite; e tomarás tu outro novilho para oferta pelo pecado.

[[v4-8-9]]

^<<v4-8-9,9>>^ Também farás chegar os levitas perante a tenda da revelação, e ajuntarás toda a congregação dos filhos de Israel.

[[v4-8-10]]

^<<v4-8-10,10>>^ Apresentarás, pois, os levitas perante o Senhor, e os filhos do Israel porão as suas mãos sobre os levitas.

[[v4-8-11]]

^<<v4-8-11,11>>^ E Arão oferecerá os levitas perante o Senhor como oferta de movimento, da parte dos filhos de Israel, para que sirvam no ministério do Senhor.

[[v4-8-12]]

^<<v4-8-12,12>>^ Os levitas porão as suas mãos sobre a cabeça dos novilhos; então tu sacrificarás um como oferta pelo pecado, e o outro como holocausto ao Senhor, para fazeres expiação pelos levitas.

[[v4-8-13]]

^<<v4-8-13,13>>^ E porás os levitas perante Arão, e perante os seus filhos, e os oferecerás como oferta de movimento ao Senhor.

[[v4-8-14]]

^<<v4-8-14,14>>^ Assim separarás os levitas do meio dos filhos de Israel; e os levitas serão meus.

[[v4-8-15]]

^<<v4-8-15,15>>^ Depois disso os levitas entrarão para fazerem o serviço da tenda da revelação, depois de os teres purificado e oferecido como oferta de movimento.

[[v4-8-16]]

^<<v4-8-16,16>>^ Porquanto eles me são dados inteiramente dentre os filhos de Israel; em lugar de todo aquele que abre a madre, isto é, do primogênito de todos os filhos de Israel, para mim os tenho tomado.

[[v4-8-17]]

^<<v4-8-17,17>>^ Porque meu é todo primogênito entre os filhos de Israel, tanto entre os homens como entre os animais; no dia em que, na terra do Egito, feri a todo primogênito, os santifiquei para mim.

[[v4-8-18]]

^<<v4-8-18,18>>^ Mas tomei os levitas em lugar de todos os primogênitos entre os filhos de Israel.

[[v4-8-19]]

^<<v4-8-19,19>>^ Dentre os filhos de Israel tenho dado os levitas a Arão e a seus filhos, para fazerem o serviço dos filhos de Israel na tenda da revelação, e para fazerem expiação por eles, a fim de que não haja praga entre eles, quando se aproximarem do santuário.

[[v4-8-20]]

^<<v4-8-20,20>>^ Assim Moisés e Arão e toda a congregação dos filhos de Israel fizeram aos levitas; conforme tudo o que o Senhor ordenara a Moisés no tocante aos levitas, assim os filhos de Israel lhes fizeram.

[[v4-8-21]]

^<<v4-8-21,21>>^ Os levitas, pois, purificaram-se, e lavaram os seus vestidos; e Arão os ofereceu como oferta de movimento perante o Senhor, e fez expiação por eles, para purificá-los.

[[v4-8-22]]

^<<v4-8-22,22>>^ Depois disso entraram os levitas, para fazerem o seu serviço na tenda da revelação, perante Arão e seus filhos; como o Senhor ordenara a Moisés acerca dos levitas, assim lhes fizeram.

[[v4-8-23]]

^<<v4-8-23,23>>^ Disse mais o Senhor a Moisés:

[[v4-8-24]]

^<<v4-8-24,24>>^ Este será o encargo dos levitas: Da idade de vinte e cinco anos para cima entrarão para se ocuparem no serviço a tenda da revelação;

[[v4-8-25]]

^<<v4-8-25,25>>^ e aos cinqüenta anos de idade sairão desse serviço e não servirão mais.

[[v4-8-26]]

^<<v4-8-26,26>>^ Continuarão a servir, porém, com seus irmãos na tenda da revelação, orientando-os no cumprimento dos seus encargos; mas não farão trabalho. Assim farás para com os levitas no tocante aos seus cargos.

'''

xref:004-numeros/004-numeros-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numeros/004-numeros-009.adoc#v4-9-0[Próximo Capítulo &#62;]