include::./index.adoc[]

[[v4-28-0]]
=== Números, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-28-1]]

^<<v4-28-1,1>>^ Disse mais o Senhor a Moisés:

[[v4-28-2]]

^<<v4-28-2,2>>^ Ordena aos filhos de Israel, e dize-lhes: A minha oferta, o alimento para as minhas ofertas queimadas, de cheiro suave para mim, tereis cuidado para ma oferecer aos seus tempos determinados.

[[v4-28-3]]

^<<v4-28-3,3>>^ Também lhes dirás: Esta é a oferta queimada que oferecereis ao Senhor: dois cordeiros de um ano, sem defeito, cada dia, em contínuo holocausto.

[[v4-28-4]]

^<<v4-28-4,4>>^ Um cordeiro oferecerás pela manhã, e o outro à tardinha,

[[v4-28-5]]

^<<v4-28-5,5>>^ juntamente com a décima parte de uma efa de flor de farinha em oferta de cereais, misturada com a quarta parte de um him de azeite batido.

[[v4-28-6]]

^<<v4-28-6,6>>^ Este é o holocausto contínuo, instituído no monte Sinai, em cheiro suave, oferta queimada ao Senhor.

[[v4-28-7]]

^<<v4-28-7,7>>^ A oferta de libação do mesmo será a quarta parte de um him para um cordeiro; no lugar santo oferecerás a libação de bebida forte ao Senhor.

[[v4-28-8]]

^<<v4-28-8,8>>^ E o outro cordeiro, oferecê-lo-ás à tardinha; com as ofertas de cereais e de libação, como o da manhã, o oferecerás, oferta queimada de cheiro suave ao Senhor.

[[v4-28-9]]

^<<v4-28-9,9>>^ No dia de sábado oferecerás dois cordeiros de um ano, sem defeito, e dois décimos de efa de flor de farinha, misturada com azeite, em oferta de cereais, com a sua oferta de libação;

[[v4-28-10]]

^<<v4-28-10,10>>^ é o holocausto de todos os sábados, além do holocausto contínuo e a sua oferta de libação.

[[v4-28-11]]

^<<v4-28-11,11>>^ Nos princípios dos vossos meses oferecereis em holocausto ao Senhor: dois novilhos, um carneiro e sete cordeiros de um ano, sem defeito;

[[v4-28-12]]

^<<v4-28-12,12>>^ e três décimos de efa de flor de farinha, misturada com azeite, em oferta de cereais, para cada novilho; e dois décimos de efa de flor de farinha, misturada com azeite, em oferta de cereais, para o carneiro;

[[v4-28-13]]

^<<v4-28-13,13>>^ e um décimo de efa de flor de farinha, misturada com azeite, em oferta de cereais, para cada cordeiro; é holocausto de cheiro suave, oferta queimada ao Senhor.

[[v4-28-14]]

^<<v4-28-14,14>>^ As ofertas de libação do mesmo serão a metade de um him de vinho para um novilho, e a terça parte de um him para um carneiro, e a quarta parte de um him para um cordeiro; este é o holocausto de cada mês, por todos os meses do ano.

[[v4-28-15]]

^<<v4-28-15,15>>^ Também oferecerás ao Senhor um bode como oferta pelo pecado; oferecer-se-á esse além do holocausto contínuo, com a sua oferta de libação.

[[v4-28-16]]

^<<v4-28-16,16>>^ No primeiro mês, aos catorze dias do mês, é a páscoa do Senhor.

[[v4-28-17]]

^<<v4-28-17,17>>^ E aos quinze dias do mesmo mês haverá festa; por sete dias se comerão pães ázimos.

[[v4-28-18]]

^<<v4-28-18,18>>^ No primeiro dia haverá santa convocação; nenhum trabalho servil fareis;

[[v4-28-19]]

^<<v4-28-19,19>>^ mas oferecereis oferta queimada em holocausto ao Senhor: dois novilhos, um carneiro e sete cordeiros de um ano, todos eles sem defeito;

[[v4-28-20]]

^<<v4-28-20,20>>^ e a sua oferta de cereais, de flor de farinha misturada com azeite; oferecereis três décimos de efa para cada novilho, dois décimos para o carneiro,

[[v4-28-21]]

^<<v4-28-21,21>>^ e um décimo para cada um dos sete cordeiros;

[[v4-28-22]]

^<<v4-28-22,22>>^ e em oferta pelo pecado oferecereis um bode, para fazer expiação por vos.

[[v4-28-23]]

^<<v4-28-23,23>>^ Essas coisas oferecereis, além do holocausto da manhã, o qual é o holocausto contínuo.

[[v4-28-24]]

^<<v4-28-24,24>>^ Assim, cada dia oferecereis, por sete dias, o alimento da oferta queimada em cheiro suave ao Senhor; oferecer-se-á além do holocausto contínuo com a sua oferta de libação;

[[v4-28-25]]

^<<v4-28-25,25>>^ e no sétimo dia tereis santa convocação; nenhum trabalho servil fareis.

[[v4-28-26]]

^<<v4-28-26,26>>^ Semelhantemente tereis santa convocação no dia das primícias, quando fizerdes ao Senhor oferta nova de cereais na vossa festa de semanas; nenhum trabalho servil fareis.

[[v4-28-27]]

^<<v4-28-27,27>>^ Então oferecereis um holocausto em cheiro suave ao Senhor: dois novilhos, um carneiro e sete cordeiros de um ano;

[[v4-28-28]]

^<<v4-28-28,28>>^ e a sua oferta de cereais, de flor de farinha misturada com azeite, três décimos de efa para cada novilho, dois décimos para o carneiro,

[[v4-28-29]]

^<<v4-28-29,29>>^ e um décimo para cada um dos sete cordeiros;

[[v4-28-30]]

^<<v4-28-30,30>>^ e um bode para fazer expiação por vós.

[[v4-28-31]]

^<<v4-28-31,31>>^ Além do holocausto contínuo e a sua oferta de cereais, os oferecereis, com as suas ofertas de libação; eles serão sem defeito.

'''

xref:004-numeros/004-numeros-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numeros/004-numeros-029.adoc#v4-29-0[Próximo Capítulo &#62;]