include::./index.adoc[]

[[v4-10-0]]
=== Números, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-10-1]]

^<<v4-10-1,1>>^ Disse mais o Senhor a Moisés:

[[v4-10-2]]

^<<v4-10-2,2>>^ Faze-te duas trombetas de prata; de obra batida as farás, e elas te servirão para convocares a congregação, e para ordenares a partida dos arraiais.

[[v4-10-3]]

^<<v4-10-3,3>>^ Quando se tocarem as trombetas, toda a congregação se ajuntará a ti à porta da tenda da revelação.

[[v4-10-4]]

^<<v4-10-4,4>>^ Mas quando se tocar uma só, a ti se congregarão os príncipes, os cabeças dos milhares de Israel.

[[v4-10-5]]

^<<v4-10-5,5>>^ Quando se tocar retinindo, partirão os arraiais que estão acampados da banda do oriente.

[[v4-10-6]]

^<<v4-10-6,6>>^ Mas quando se tocar retinindo, pela segunda, vez, partirão os arraiais que estão acampados da banda do sul; para as partidas dos arraiais se tocará retinindo.

[[v4-10-7]]

^<<v4-10-7,7>>^ Mas quando se houver de reunir a congregação, tocar-se-á sem retinir:

[[v4-10-8]]

^<<v4-10-8,8>>^ Os filhos de Arão, sacerdotes, tocarão as trombetas; e isto vos será por estatuto perpétuo nas vossas gerações.

[[v4-10-9]]

^<<v4-10-9,9>>^ Ora, quando na vossa terra sairdes à guerra contra o inimigo que vos estiver oprimindo, fareis retinir as trombetas; e perante o Senhor vosso Deus sereis tidos em memória, e sereis salvos dos vossos inimigos.

[[v4-10-10]]

^<<v4-10-10,10>>^ Semelhantemente, no dia da vossa alegria, nas vossas festas fixas, e nos princípios dos vossos meses, tocareis as trombetas sobre os vossos holocaustos, e sobre os sacrifícios de vossas ofertas pacíficas; e eles vos serão por memorial perante vosso Deus. Eu sou o Senhor vosso Deus.

[[v4-10-11]]

^<<v4-10-11,11>>^ Ora, aconteceu, no segundo ano, no segundo mês, aos vinte do mês, que a nuvem se alçou de sobre o tabernáculo da congregação.

[[v4-10-12]]

^<<v4-10-12,12>>^ Partiram, pois, os filhos de Israel do deserto de Sinai para as suas jornadas; e a nuvem parou ,no deserto de Parã.

[[v4-10-13]]

^<<v4-10-13,13>>^ Assim iniciaram a primeira caminhada, à ordem do Senhor por intermédio de Moisés:

[[v4-10-14]]

^<<v4-10-14,14>>^ partiu primeiramente o estandarte do arraial dos filhos de Judá segundo os seus exércitos; sobre o seu exército estava Nasom, filho de Aminadabe;

[[v4-10-15]]

^<<v4-10-15,15>>^ sobre o exército da tribo dos filhos de Issacar, Netanel, filho de Zuar;

[[v4-10-16]]

^<<v4-10-16,16>>^ e sobre o exército da tribo dos filhos de Zebulom, Eliabe, filho de Helom.

[[v4-10-17]]

^<<v4-10-17,17>>^ Então o tabernáculo foi desarmado, e os filhos de Gérson e os filhos de Merári partiram, levando o tabernáculo.

[[v4-10-18]]

^<<v4-10-18,18>>^ Depois partiu o estandarte do arraial de Rúben segundo os seus exércitos; sobre o seu exército estava Elizur, filho de Sedeur;

[[v4-10-19]]

^<<v4-10-19,19>>^ sobre o exército da tribo dos filhos de Simeão, Selumiel, filho de Zurisadai;

[[v4-10-20]]

^<<v4-10-20,20>>^ e sobre o exército da tribo dos filhos de Gade, Eliasafe, filho de Deuel.

[[v4-10-21]]

^<<v4-10-21,21>>^ Então partiram os coatitas, levando o santuário; e os outros erigiam o tabernáculo, enquanto estes vinham.

[[v4-10-22]]

^<<v4-10-22,22>>^ Depois partiu o estandarte do arraial dos filhos de Efraim segundo os seus exércitos; sobre o seu exército estava Elisama, filho de Amiúde;

[[v4-10-23]]

^<<v4-10-23,23>>^ sobre o exército da tribo dos filhos de Manassés, Gamaliel, filho de Pedazur;

[[v4-10-24]]

^<<v4-10-24,24>>^ e sobre o exército da tribo dos filhos de Benjamim, Abidã, filho de Gideôni.

[[v4-10-25]]

^<<v4-10-25,25>>^ Então partiu o estandarte do arraial dos filhos de Dã, que era a retaguarda de todos os arraiais, segundo os seus exércitos; sobre o seu exército estava Aiezer, filho de Amisadai;

[[v4-10-26]]

^<<v4-10-26,26>>^ sobre o exército da tribo dos filhos de Aser, Pagiel, filho de Ocrã;

[[v4-10-27]]

^<<v4-10-27,27>>^ e sobre o exército da tribo dos filhos de Naftali, Airá, filho de Enã.

[[v4-10-28]]

^<<v4-10-28,28>>^ Tal era a ordem de partida dos filhos de Israel segundo os seus exércitos, quando partiam.

[[v4-10-29]]

^<<v4-10-29,29>>^ Disse então Moisés a Hobabe, filho de Reuel, o midianita, sogro de Moisés: Nós caminhamos para aquele lugar de que o Senhor disse: Vo-lo darei. Vai conosco, e te faremos bem; porque o Senhor falou bem acerca de Israel.

[[v4-10-30]]

^<<v4-10-30,30>>^ Respondeu ele: Não irei; antes irei à minha terra e à minha parentela.

[[v4-10-31]]

^<<v4-10-31,31>>^ Tornou-lhe Moisés: Ora, não nos deixes, porquanto sabes onde devamos acampar no deserto; de olhos nos serviras.

[[v4-10-32]]

^<<v4-10-32,32>>^ Se, pois, vieres conosco, o bem que o Senhor nos fizer, também nós faremos a ti.

[[v4-10-33]]

^<<v4-10-33,33>>^ Assim partiram do monte do Senhor caminho de três dias; e a arca do pacto do Senhor ia adiante deles, para lhes buscar lugar de descanso.

[[v4-10-34]]

^<<v4-10-34,34>>^ E a nuvem do Senhor ia sobre eles de dia, quando partiam do arraial.

[[v4-10-35]]

^<<v4-10-35,35>>^ Quando, pois, a arca partia, dizia Moisés: Levanta-te, Senhor, e dissipados sejam os teus inimigos, e fujam diante de ti os que te odeiam.

[[v4-10-36]]

^<<v4-10-36,36>>^ E, quando ela pousava, dizia: Volta, ó Senhor, para os muitos milhares de Israel.

'''

xref:004-numeros/004-numeros-009.adoc#v4-9-0[&#60; Capítulo Anterior] | <<v4-10-0,Topo>> | xref:004-numeros/004-numeros-011.adoc#v4-11-0[Próximo Capítulo &#62;]