include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-30-1]]

^<<v4-30-1,1>>^ Depois disse Moisés aos cabeças das tribos dos filhos de Israel: Isto é o que o Senhor ordenou:

[[v4-30-2]]

^<<v4-30-2,2>>^ Quando um homem fizer voto ao Senhor, ou jurar, ligando-se com obrigação, não violará a sua palavra; segundo tudo o que sair da sua boca fará.

[[v4-30-3]]

^<<v4-30-3,3>>^ Também quando uma mulher, na sua mocidade, estando ainda na casa de seu pai, fizer voto ao Senhor, e com obrigação se ligar,

[[v4-30-4]]

^<<v4-30-4,4>>^ e seu pai souber do seu voto e da obrigação com que se ligou, e se calar para com ela, então todos os seus votos serão válidos, e toda a obrigação com que se ligou será válida.

[[v4-30-5]]

^<<v4-30-5,5>>^ Mas se seu pai lho vedar no dia em que o souber, todos os seus votos e as suas obrigações, com que se tiver ligado, deixarão de ser válidos; e o Senhor lhe perdoará, porquanto seu pai lhos vedou.

[[v4-30-6]]

^<<v4-30-6,6>>^ Se ela se casar enquanto ainda estiverem sobre ela os seus votos ou o dito irrefletido dos seus lábios, com que se tiver obrigado,

[[v4-30-7]]

^<<v4-30-7,7>>^ e seu marido o souber e se calar para com ela no dia em que o souber, os votos dela serão válidos; e as obrigações com que se ligou serão válidas.

[[v4-30-8]]

^<<v4-30-8,8>>^ Mas se seu marido lho vedar no dia em que o souber, anulará o voto que estiver sobre ela, como também o dito irrefletido dos seus lábios, com que se tiver obrigado; e o senhor lhe perdoará.

[[v4-30-9]]

^<<v4-30-9,9>>^ No tocante ao voto de uma viúva ou de uma repudiada, tudo com que se obrigar ser-lhe-á válido.

[[v4-30-10]]

^<<v4-30-10,10>>^ Se ela, porém, fez voto na casa de seu marido, ou se obrigou com juramento,

[[v4-30-11]]

^<<v4-30-11,11>>^ e seu marido o soube e se calou para com ela, não lho vedando, todos os seus votos serão válidos; e toda a obrigação com que se ligou será válida.

[[v4-30-12]]

^<<v4-30-12,12>>^ Se, porém, seu marido de todo lhos anulou no dia em que os soube, deixará de ser válido tudo quanto saiu dos lábios dela, quer no tocante aos seus votos, quer no tocante àquilo a que se obrigou; seu marido lhos anulou; e o senhor lhe perdoará.

[[v4-30-13]]

^<<v4-30-13,13>>^ Todo voto, e todo juramento de obrigação, que ela tiver feito para afligir a alma, seu marido pode confirmá-lo, ou pode anulá-lo.

[[v4-30-14]]

^<<v4-30-14,14>>^ Se, porém, seu marido, de dia em dia, se calar inteiramente para com ela, confirma todos os votos e todas as obrigações que estiverem sobre ela; ele lhos confirmou, porquanto se calou para com ela no dia em que os soube.

[[v4-30-15]]

^<<v4-30-15,15>>^ Mas se de todo lhos anular depois de os ter sabido, ele levará sobre si a iniqüidade dela.

[[v4-30-16]]

^<<v4-30-16,16>>^ Esses são os estatutos que o Senhor ordenou a Moisés, entre o marido e sua mulher, entre o pai e sua filha, na sua mocidade, em casa de seu pai.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]