include::./index.adoc[]

[[v4-26-0]]
=== Números, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-26-1]]

^<<v4-26-1,1>>^ Depois daquela praga disse o Senhor a Moisés e a Eleazar, filho do sacerdote Arão:

[[v4-26-2]]

^<<v4-26-2,2>>^ Tomai a soma de toda a congregação dos filhos de Israel, da idade de vinte anos para cima, segundo as casas e seus pais, todos os que em Israel podem sair à guerra.

[[v4-26-3]]

^<<v4-26-3,3>>^ Falaram-lhes, pois, Moisés e Eleazar o sacerdote, nas planícies de Moabe, junto ao Jordão, na altura de Jericó, dizendo:

[[v4-26-4]]

^<<v4-26-4,4>>^ Contai o povo da idade de vinte anos para cima; como o Senhor ordenara a Moisés e aos filhos de Israel que saíram da terra do Egito.

[[v4-26-5]]

^<<v4-26-5,5>>^ Rúben, o primogênito de Israel; os filhos de Rúben: de Hanoque, a família dos hanoquitas; de Palu, a família dos paluítas;

[[v4-26-6]]

^<<v4-26-6,6>>^ de Hezrom, a família dos hezronitas; de Carmi, a família dos carmitas.

[[v4-26-7]]

^<<v4-26-7,7>>^ Estas são as famílias dos rubenitas; os que foram deles contados eram quarenta e três mil setecentos e trinta.

[[v4-26-8]]

^<<v4-26-8,8>>^ E o filho de Palu: Eliabe.

[[v4-26-9]]

^<<v4-26-9,9>>^ Os filhos de Eliabe: Nemuel, Dato e Abirão. Estes são aqueles Datã e Abirão que foram chamados da congregação, os quais contenderam contra Moisés e contra Arão na companhia de Corá, quando contenderam contra o Senhor,

[[v4-26-10]]

^<<v4-26-10,10>>^ e a terra abriu a boca, e os tragou juntamente com Corá, quando pereceu aquela companhia; quando o fogo devorou duzentos e cinqüenta homens, os quais serviram de advertência.

[[v4-26-11]]

^<<v4-26-11,11>>^ Todavia os filhos de Corá não morreram.

[[v4-26-12]]

^<<v4-26-12,12>>^ Os filhos de Simeão, segundo as suas famílias: de Nemuel, a família dos nemuelitas; de Jamim, a família dos jaminitas; de Jaquim, a família dos jaquinitas;

[[v4-26-13]]

^<<v4-26-13,13>>^ de Zerá, a família dos zeraítas; de Saul, a família dos saulitas.

[[v4-26-14]]

^<<v4-26-14,14>>^ Estas são as famílias dos simeonitas, vinte e dois mil e duzentos.

[[v4-26-15]]

^<<v4-26-15,15>>^ Os filhos de Gade, segundo as suas famílias: de Zefom, a família dos zefonitas; de Hagui, a família dos haguitas; de Suni, a família dos sunitas;

[[v4-26-16]]

^<<v4-26-16,16>>^ de Ozni, a família dos oznitas; de Eri, a família dos eritas;

[[v4-26-17]]

^<<v4-26-17,17>>^ de Arode, a família dos aroditas; de Areli, a família dos arelitas.

[[v4-26-18]]

^<<v4-26-18,18>>^ Estas são as famílias dos filhos de Gade, segundo os que foram deles contados, quarenta mil e quinhentos.

[[v4-26-19]]

^<<v4-26-19,19>>^ Os filhos de Judá: Er e Onã; mas Er e Onã morreram na terra de Canaã.

[[v4-26-20]]

^<<v4-26-20,20>>^ Assim os filhos de Judá, segundo as suas famílias, eram: de Selá, a família dos selanitas; de Pérez, a família dos perezitas; de Zerá, a família dos zeraítas.

[[v4-26-21]]

^<<v4-26-21,21>>^ E os filhos de Pérez eram: de Hezrom, a família dos hezronitas; de Hamul, a família dos hamulitas.

[[v4-26-22]]

^<<v4-26-22,22>>^ Estas são as famílias de Judá, segundo os que foram deles contados, setenta e seis mil e quinhentos.

[[v4-26-23]]

^<<v4-26-23,23>>^ Os filhos de Issacar, segundo as suas famílias: de Tola, a família dos tolaítas; de Puva, a família dos puvitas;

[[v4-26-24]]

^<<v4-26-24,24>>^ de Jasube, a família dos jasubitas; de Sinrom, a família dos sinronitas.

[[v4-26-25]]

^<<v4-26-25,25>>^ Estas são as famílias de Issacar, segundo os que foram deles contados, sessenta e quatro mil e trezentos:

[[v4-26-26]]

^<<v4-26-26,26>>^ Os filhos de Zebulom, segundo as suas famílias: de Serede, a família dos sereditas; de Elom, a família dos elonitas; de Jaleel, a família dos jaleelitas.

[[v4-26-27]]

^<<v4-26-27,27>>^ Estas são as famílias dos zebulonitas, segundo os que foram deles contados, sessenta mil e quinhentos.

[[v4-26-28]]

^<<v4-26-28,28>>^ Os filhos de José, segundo as suas famílias: Manassés e Efraim.

[[v4-26-29]]

^<<v4-26-29,29>>^ Os filhos de Manassés: de Maquir, a família dos maquiritas; e Maquir gerou a Gileade; de Gileade, a família dos gileaditas.

[[v4-26-30]]

^<<v4-26-30,30>>^ Estes são os filhos de Gileade: de Iezer, a família dos iezritas; de Heleque, a família dos helequitas;

[[v4-26-31]]

^<<v4-26-31,31>>^ de Asriel, a família dos asrielitas; de Siquém, a família dos siquemitas;

[[v4-26-32]]

^<<v4-26-32,32>>^ e de Semida, a família dos semidaítas; e de Hefer, a família dos heferitas.

[[v4-26-33]]

^<<v4-26-33,33>>^ Ora, Zelofeade, filho de Hefer, não tinha filhos, senão filhas; e as filhas de Zelofeade chamavam-se Macla, Noa, Hogla, Milca e Tirza.

[[v4-26-34]]

^<<v4-26-34,34>>^ Estas são as famílias de Manassés; os que foram deles contados, eram cinqüenta e dois mil e setecentos.

[[v4-26-35]]

^<<v4-26-35,35>>^ Estes são os filhos de Efraim, segundo as suas famílias: de Sutela, a família dos sutelaítas; de Bequer, a família dos bequeritas; de Taã, a família dos taanitas.

[[v4-26-36]]

^<<v4-26-36,36>>^ E estes são os filhos de Sutela: de Erã, a família dos eranitas.

[[v4-26-37]]

^<<v4-26-37,37>>^ Estas são as famílias dos filhos de Efraim, segundo os que foram deles contados, trinta e dois mil e quinhentos. Estes são os filhos de José, segundo as suas famílias.

[[v4-26-38]]

^<<v4-26-38,38>>^ Os filhos de Benjamim, segundo as suas famílias: de Belá, a família dos belaítas; de Asbel, a família dos asbelitas; de Airão, a família dos airamitas;

[[v4-26-39]]

^<<v4-26-39,39>>^ de Sefufã, a família dos sufamitas; de Hufão, a família dos hufamitas.

[[v4-26-40]]

^<<v4-26-40,40>>^ E os filhos de Belá eram Arde e Naamã: de Arde a família dos arditas; de Naamã, a família dos naamitas.

[[v4-26-41]]

^<<v4-26-41,41>>^ Estes são os filhos de Benjamim, segundo as suas famílias; os que foram deles contados, eram quarenta e cinco mil e seiscentos.

[[v4-26-42]]

^<<v4-26-42,42>>^ Estes são os filhos de Dã, segundo as suas famílias: de Suão a família dos suamitas. Estas são as famílias de Dã, segundo as suas famílias.

[[v4-26-43]]

^<<v4-26-43,43>>^ Todas as famílias dos suamitas, segundo os que foram deles contados, eram sessenta e quatro mil e quatrocentos.

[[v4-26-44]]

^<<v4-26-44,44>>^ Os filhos de Aser, segundo as suas famílias: de Imná, a família dos imnitas; de Isvi, a família dos isvitas; de Berias, a família dos beritas.

[[v4-26-45]]

^<<v4-26-45,45>>^ Dos filhos de Berias: de Heber, a família dos heberitas; de Malquiel, a família dos malquielitas.

[[v4-26-46]]

^<<v4-26-46,46>>^ E a filha de Aser chamava-se Sera.

[[v4-26-47]]

^<<v4-26-47,47>>^ Estas são as famílias dos filhos de Aser, segundo os que foram deles contados, cinqüenta e três mil e quatrocentos.

[[v4-26-48]]

^<<v4-26-48,48>>^ Os filhos de Naftali, segundo as suas famílias: de Jazeel, a família dos jazeelitas; de Guni, a família dos gunitas;

[[v4-26-49]]

^<<v4-26-49,49>>^ de Jezer, a família dos jezeritas; de Silém, a família dos silemitas.

[[v4-26-50]]

^<<v4-26-50,50>>^ Estas são as famílias de Naftali, segundo as suas famílias; os que foram deles contados, eram quarenta e cinco mil e quatrocentos.

[[v4-26-51]]

^<<v4-26-51,51>>^ Estes são os que foram contados dos filhos de Israel, seiscentos e um mil setecentos e trinta.

[[v4-26-52]]

^<<v4-26-52,52>>^ Disse mais o senhor a Moisés:

[[v4-26-53]]

^<<v4-26-53,53>>^ A estes se repartirá a terra em herança segundo o número dos nomes.

[[v4-26-54]]

^<<v4-26-54,54>>^ À tribo de muitos darás herança maior, e à de poucos darás herança menor; a cada qual se dará a sua herança segundo os que foram deles contados.

[[v4-26-55]]

^<<v4-26-55,55>>^ Todavia a terra se repartirá por sortes; segundo os nomes das tribos de seus pais a herdarão.

[[v4-26-56]]

^<<v4-26-56,56>>^ Segundo sair a sorte, se repartirá a herança deles entre as tribos de muitos e as de poucos.

[[v4-26-57]]

^<<v4-26-57,57>>^ Também estes são os que foram contados dos levitas, segundo as suas famílias: de Gérson, a família dos gersonitas; de Coate, a família dos coatitas; de Merári, a família os meraritas.

[[v4-26-58]]

^<<v4-26-58,58>>^ Estas são as famílias de Levi: a família dos libnitas, a família dos hebronitas, a família dos malitas, a família dos musitas, a família dos coraítas. Ora, Coate gerou a Anrão.

[[v4-26-59]]

^<<v4-26-59,59>>^ E a mulher de Anrão chamava-se Joquebede, filha de Levi, a qual nasceu a Levi no Egito; e de Anrão ela teve Arão e Moisés, e Miriã, irmã deles.

[[v4-26-60]]

^<<v4-26-60,60>>^ E a Arão nasceram Nadabe e Abiú, Eleazar e Itamar.

[[v4-26-61]]

^<<v4-26-61,61>>^ Mas Nadabe e Abiú morreram quando ofereceram fogo estranho perante o Senhor.

[[v4-26-62]]

^<<v4-26-62,62>>^ E os que foram deles contados eram vinte e três mil, todos os homens da idade de um mês para cima; porque não foram contados entre os filhos de Israel, porquanto não lhes foi dada herança entre os filhos de Israel.

[[v4-26-63]]

^<<v4-26-63,63>>^ Esses são os que foram contados por Moisés e Eleazar, o sacerdote, que contaram os filhos de Israel nas planícies de Moabe, junto ao Jordão, na altura de Jericó.

[[v4-26-64]]

^<<v4-26-64,64>>^ Entre esses, porém, não se achava nenhum daqueles que tinham sido contados por Moisés e Arão, o sacerdote, quando contaram os filhos de Israel no deserto de Sinai.

[[v4-26-65]]

^<<v4-26-65,65>>^ Porque o senhor dissera deles: Certamente morrerão no deserto; pelo que nenhum deles ficou, senão Calebe, filho de Jefoné, e Josué, filho de Num.

'''

xref:004-numeros/004-numeros-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numeros/004-numeros-027.adoc#v4-27-0[Próximo Capítulo &#62;]