include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-16-1]]

^<<v4-16-1,1>>^ Ora, Corá, filho de Izar, filho de Coate, filho de Levi, juntamente com Datã e Abirão, filhos de Eliabe, e Om, filho de Pelete, filhos de Rúben, tomando certos homens,

[[v4-16-2]]

^<<v4-16-2,2>>^ levantaram-se perante Moisés, juntamente com duzentos e cinqüenta homens dos filhos de Israel, príncipes da congregação, chamados à assembléia, varões de renome;

[[v4-16-3]]

^<<v4-16-3,3>>^ e ajuntando-se contra Moisés e contra Arão, disseram-lhes: Demais é o que vos arrogais a vós, visto que toda a congregação e santa, todos eles são santos, e o Senhor está no meio deles; por que, pois, vos elevais sobre a assembléia do Senhor?

[[v4-16-4]]

^<<v4-16-4,4>>^ Quando Moisés ouviu isso, caiu com o rosto em terra;

[[v4-16-5]]

^<<v4-16-5,5>>^ depois falou a Corá e a toda a sua companhia, dizendo: Amanhã pela manhã o Senhor fará saber quem é seu, e quem é o santo, ao qual ele fará chegar a si; e aquele a quem escolher fará chegar a si.

[[v4-16-6]]

^<<v4-16-6,6>>^ Fazei isto: Corá e toda a sua companhia, tomai para vós incensários;

[[v4-16-7]]

^<<v4-16-7,7>>^ e amanhã, pondo fogo neles, sobre eles deitai incenso perante o Senhor; e será que o homem a quem o Senhor escolher, esse será o santo; demais é o que vos arrogais a vós, filhos de Levi.

[[v4-16-8]]

^<<v4-16-8,8>>^ Disse mais Moisés a Corá: Ouvi agora, filhos de Levi!

[[v4-16-9]]

^<<v4-16-9,9>>^ Acaso é pouco para vós que o Deus de Israel vos tenha separado da congregação de Israel, para vos fazer chegar a si, a fim de fazerdes o serviço do tabernáculo do Senhor e estardes perante a congregação para ministrar-lhe,

[[v4-16-10]]

^<<v4-16-10,10>>^ e te fez chegar, e contigo todos os teus irmãos, os filhos de Levi? procurais também o sacerdócio?

[[v4-16-11]]

^<<v4-16-11,11>>^ Pelo que tu e toda a tua companhia estais congregados contra o Senhor; e Arão, quem é ele, para que murmureis contra ele?

[[v4-16-12]]

^<<v4-16-12,12>>^ Então Moisés mandou chamar a Datã e a Abirão, filhos de Eliabe; eles porém responderam: Não subiremos.

[[v4-16-13]]

^<<v4-16-13,13>>^ É pouco, porventura, que nos tenhas feito subir de uma terra que mana leite e mel, para nos matares no deserto, para que queiras ainda fazer-te príncipe sobre nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Ademais, não nos introduziste em uma terra que mana leite e mel, nem nos deste campos e vinhas em herança; porventura cegarás os olhos a estes homens? Não subiremos.

[[v4-16-15]]

^<<v4-16-15,15>>^ Então Moisés irou-se grandemente, e disse ao Senhor: Não atentes para a sua oferta; nem um só jumento tenho tomado deles, nem a nenhum deles tenho feito mal.

[[v4-16-16]]

^<<v4-16-16,16>>^ Disse mais Moisés a Corá: Comparecei amanhã tu e toda a tua companhia perante o Senhor; tu e eles, e Arão.

[[v4-16-17]]

^<<v4-16-17,17>>^ Tome cada um o seu incensário, e ponha nele incenso; cada um traga perante o Senhor o seu incensário, duzentos e cinqüenta incensários; também tu e Arão, cada qual o seu incensário.

[[v4-16-18]]

^<<v4-16-18,18>>^ Tomou, pois, cada qual o seu incensário, e nele pôs fogo, e nele deitou incenso; e se puseram à porta da tenda da revelação com Moisés e Arão.

[[v4-16-19]]

^<<v4-16-19,19>>^ E Corá fez ajuntar contra eles toda o congregação à porta da tenda da revelação; então a glória do Senhor apareceu a toda a congregação.

[[v4-16-20]]

^<<v4-16-20,20>>^ Então disse o senhor a Moisés e a Arão:

[[v4-16-21]]

^<<v4-16-21,21>>^ Apartai-vos do meio desta congregação, para que eu, num momento, os possa consumir.

[[v4-16-22]]

^<<v4-16-22,22>>^ Mas eles caíram com os rostos em terra, e disseram: ó Deus, Deus dos espíritos de toda a carne, pecará um só homem, e indignar-te-ás tu contra toda esta congregação?

[[v4-16-23]]

^<<v4-16-23,23>>^ Respondeu o Senhor a Moisés:

[[v4-16-24]]

^<<v4-16-24,24>>^ Fala a toda esta congregação, dizendo: Subi do derredor da habitação de Corá, Datã e Abirão.

[[v4-16-25]]

^<<v4-16-25,25>>^ Então Moisés levantou-se, e foi ter com Datã e Abirão; e seguiram-nos os anciãos de Israel.

[[v4-16-26]]

^<<v4-16-26,26>>^ E falou à congregação, dizendo: Retirai-vos, peço-vos, das tendas desses homens ímpios, e não toqueis nada do que é seu, para que não pereçais em todos os seus pecados.

[[v4-16-27]]

^<<v4-16-27,27>>^ Subiram, pois, do derredor da habitação de Corá, Datã e Abirão. E Datã e Abirão saíram, e se puseram à porta das suas tendas, juntamente com suas mulheres, e seus filhos e seus pequeninos.

[[v4-16-28]]

^<<v4-16-28,28>>^ Então disse Moisés: Nisto conhecereis que o Senhor me enviou a fazer todas estas obras; pois não as tenho feito de mim mesmo.

[[v4-16-29]]

^<<v4-16-29,29>>^ Se estes morrerem como morrem todos os homens, e se forem visitados como são visitados todos os homens, o Senhor não me enviou.

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se o Senhor criar alguma coisa nova, e a terra abrir a boca e os tragar com tudo o que é deles, e vivos descerem ao Seol, então compreendereis que estes homens têm desprezado o Senhor.

[[v4-16-31]]

^<<v4-16-31,31>>^ E aconteceu que, acabando ele de falar todas estas palavras, a terra que estava debaixo deles se fendeu;

[[v4-16-32]]

^<<v4-16-32,32>>^ e a terra abriu a boca e os tragou com as suas famílias, como também a todos os homens que pertenciam a Corá, e a toda a sua fazenda.

[[v4-16-33]]

^<<v4-16-33,33>>^ Assim eles e tudo o que era seu desceram vivos ao Seol; e a terra os cobriu, e pereceram do meio da congregação,

[[v4-16-34]]

^<<v4-16-34,34>>^ E todo o Israel, que estava ao seu redor, fugiu ao clamor deles, dizendo: não suceda que a terra nos trague também a nós.

[[v4-16-35]]

^<<v4-16-35,35>>^ Então saiu fogo do Senhor, e consumiu os duzentos e cinqüenta homens que ofereciam o incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ Então disse o Senhor a Moisés:

[[v4-16-37]]

^<<v4-16-37,37>>^ Dize a Eleazar, filho de Arão, o sacerdote, que tire os incensários do meio do incêndio; e espalha tu o fogo longe; porque se tornaram santos

[[v4-16-38]]

^<<v4-16-38,38>>^ os incensários daqueles que pecaram contra as suas almas; deles se façam chapas, de obra batida, para cobertura do altar; porquanto os trouxeram perante o Senhor, por isso se tornaram santos; e serão por sinal aos filhos de Israel.

[[v4-16-39]]

^<<v4-16-39,39>>^ Eleazar, pois, o sacerdote, tomou os incensários de bronze, os quais aqueles que foram queimados tinham oferecido; e os converteram em chapas para cobertura do altar,

[[v4-16-40]]

^<<v4-16-40,40>>^ para servir de memória aos filhos de Israel, a fim de que nenhum estranho, ninguém que não seja da descendência de Arão, se chegue para queimar incenso perante o Senhor, para que não seja como Corá e a sua companhia; conforme o Senhor dissera a Eleazar por intermédio de Moisés.

[[v4-16-41]]

^<<v4-16-41,41>>^ Mas no dia seguinte toda a congregação dos filhos de Israel murmurou contra Moisés e Arão, dizendo: Vós matastes o povo do Senhor.

[[v4-16-42]]

^<<v4-16-42,42>>^ E tendo-se sublevado a congregação contra Moisés e Arão, dirigiu-se para a tenda da revelação, e eis que a nuvem a cobriu, e a glória do Senhor apareceu.

[[v4-16-43]]

^<<v4-16-43,43>>^ Vieram, pois, Moisés e Arão à frente da tenda da revelação.

[[v4-16-44]]

^<<v4-16-44,44>>^ Então disse o Senhor a Moisés:

[[v4-16-45]]

^<<v4-16-45,45>>^ Levantai-vos do meio desta congregação, para que eu, num momento, a possa consumir. Então caíram com o rosto em terra.

[[v4-16-46]]

^<<v4-16-46,46>>^ Depois disse Moisés a Arão: Toma o teu incensário, põe nele fogo do altar, deita incenso sobre ele e leva-o depressa à congregação, e faze expiação por eles; porque grande indignação saiu do Senhor; já começou a praga.

[[v4-16-47]]

^<<v4-16-47,47>>^ Tomou-o Arão, como Moisés tinha falado, e correu ao meio da congregação; e eis que já a praga havia começado entre o povo; e deitando o incenso no incensário, fez expiação pelo povo.

[[v4-16-48]]

^<<v4-16-48,48>>^ E pôs-se em pé entre os mortos e os vivos, e a praga cessou.

[[v4-16-49]]

^<<v4-16-49,49>>^ Ora, os que morreram da praga foram catorze mil e setecentos, além dos que morreram no caso de Corá.

[[v4-16-50]]

^<<v4-16-50,50>>^ E voltou Arão a Moisés à porta da tenda da revelação, pois cessara a praga.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]