include::./index.adoc[]

[[v4-27-0]]
=== Números, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-27-1]]

^<<v4-27-1,1>>^ Então vieram as filhas de Zelofeade, filho de Hefer, filho de Gileade, filho de Maquir, filho de Manassés, das famílias de Manassés, filho de José; e os nomes delas são estes: Macla, Noa, Hogla, Milca e Tirza;

[[v4-27-2]]

^<<v4-27-2,2>>^ apresentaram-se diante de Moisés, e de Eleazar, o sacerdote, e diante dos príncipes e de toda a congregação à porta da tenda da revelação, dizendo:

[[v4-27-3]]

^<<v4-27-3,3>>^ Nosso pai morreu no deserto, e não se achou na companhia daqueles que se ajuntaram contra o Senhor, isto é, na companhia de Corá; porém morreu no seu próprio pecado, e não teve filhos.

[[v4-27-4]]

^<<v4-27-4,4>>^ Por que se tiraria o nome de nosso pai dentre a sua família, por não ter tido um filho? Dai-nos possessão entre os irmãos de nosso pai.

[[v4-27-5]]

^<<v4-27-5,5>>^ Moisés, pois, levou a causa delas perante o Senhor.

[[v4-27-6]]

^<<v4-27-6,6>>^ Então disse o Senhor a Moisés:

[[v4-27-7]]

^<<v4-27-7,7>>^ O que as filhas de Zelofeade falam é justo; certamente lhes darás possessão de herança entre os irmãos de seu pai; a herança de seu pai farás passar a elas.

[[v4-27-8]]

^<<v4-27-8,8>>^ E dirás aos filhos de Israel: Se morrer um homem, e não tiver filho, fareis passar a sua herança à sua filha.

[[v4-27-9]]

^<<v4-27-9,9>>^ E, se não tiver filha, dareis a sua herança a seus irmãos.

[[v4-27-10]]

^<<v4-27-10,10>>^ Mas, se não tiver irmãos, dareis a sua herança aos irmãos de seu pai.

[[v4-27-11]]

^<<v4-27-11,11>>^ Se também seu pai não tiver irmãos, então dareis a sua herança a seu parente mais chegado dentre a sua família, para que a possua; isto será para os filhos de Israel estatuto de direito, como o Senhor ordenou a Moisés.

[[v4-27-12]]

^<<v4-27-12,12>>^ Depois disse o Senhor a Moisés: sobe a este monte de Abarim, e vê a terra que tenho dado aos filhos de Israel.

[[v4-27-13]]

^<<v4-27-13,13>>^ E, tendo-a visto, serás tu também recolhido ao teu povo, assim como o foi teu irmão Arão;

[[v4-27-14]]

^<<v4-27-14,14>>^ porquanto no deserto de Zim, na contenda da congregação, fostes rebeldes à minha palavra, não me santificando diante dos seus olhos, no tocante às águas &#123;estas são as águas de Meribá de Cades, no deserto de Zim&#125;.

[[v4-27-15]]

^<<v4-27-15,15>>^ Respondeu Moisés ao Senhor:

[[v4-27-16]]

^<<v4-27-16,16>>^ Que o senhor, Deus dos espíritos de toda a carne, ponha um homem sobre a congregação,

[[v4-27-17]]

^<<v4-27-17,17>>^ o qual saia diante deles e entre diante deles, e os faça sair e os faça entrar; para que a congregação do Senhor não seja como ovelhas que não têm pastor.

[[v4-27-18]]

^<<v4-27-18,18>>^ Então disse o Senhor a Moisés: Toma a Josué, filho de Num, homem em quem há o Espírito, e impõe-lhe a mão;

[[v4-27-19]]

^<<v4-27-19,19>>^ e apresenta-o perante Eleazar, o sacerdote, e perante toda a congregação, e dá-lhe a comissão à vista deles;

[[v4-27-20]]

^<<v4-27-20,20>>^ e sobre ele porás da tua glória, para que lhe obedeça toda a congregação dos filhos de Israel.

[[v4-27-21]]

^<<v4-27-21,21>>^ Ele, pois, se apresentará perante Eleazar, o sacerdote, o qual por ele inquirirá segundo o juízo do Urim, perante o Senhor; segundo a ordem de Eleazar sairão, e segundo a ordem de Eleazar entrarão, ele e todos os filhos de Israel, isto é, toda a congregação.

[[v4-27-22]]

^<<v4-27-22,22>>^ Então Moisés fez como o Senhor lhe ordenara: tomou a Josué, apresentou-o perante Eleazar, o sacerdote, e perante toda a congregação,

[[v4-27-23]]

^<<v4-27-23,23>>^ impôs-lhe as mãos, e lhe deu a comissão; como o Senhor falara por intermédio de Moisés.

'''

xref:004-numeros/004-numeros-026.adoc#v4-26-0[&#60; Capítulo Anterior] | <<v4-27-0,Topo>> | xref:004-numeros/004-numeros-028.adoc#v4-28-0[Próximo Capítulo &#62;]