include::./index.adoc[]

[[v4-6-0]]
=== Números, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-6-1]]

^<<v4-6-1,1>>^ Disse mais o Senhor a Moisés:

[[v4-6-2]]

^<<v4-6-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Quando alguém, seja homem, seja mulher, fizer voto especial de nazireu, a fim de se separar para o Senhor,

[[v4-6-3]]

^<<v4-6-3,3>>^ abster-se-á de vinho e de bebida forte; não beberá, vinagre de vinho, nem vinagre de bebida forte, nem bebida alguma feita de uvas, nem comerá uvas frescas nem secas.

[[v4-6-4]]

^<<v4-6-4,4>>^ Por todos os dias do seu nazireado não comerá de coisa alguma que se faz da uva, desde os caroços até as cascas.

[[v4-6-5]]

^<<v4-6-5,5>>^ Por todos os dias do seu voto de nazireado, navalha não passará sobre a sua cabeça; até que se cumpram os dias pelos quais ele se tenha separado para o Senhor, será santo; deixará crescer as guedelhas do cabelo da sua cabeça.

[[v4-6-6]]

^<<v4-6-6,6>>^ Por todos os dias da sua separação para o Senhor, não se aproximará de cadáver algum.

[[v4-6-7]]

^<<v4-6-7,7>>^ Não se contaminará nem por seu pai, nem por sua mãe, nem por seu irmão, nem por sua irmã, quando estes morrerem; porquanto o nazireado do seu Deus está sobre a sua cabeça:

[[v4-6-8]]

^<<v4-6-8,8>>^ Por todos os dias do seu nazireado será santo ao Senhor.

[[v4-6-9]]

^<<v4-6-9,9>>^ Se alguém morrer subitamente junto dele, contaminando-se assim a cabeça do seu nazireado, rapará a sua cabera no dia da sua purificação, ao sétimo dia a rapará.

[[v4-6-10]]

^<<v4-6-10,10>>^ Ao oitavo dia trará duas rolas ou dois pombinhos, ao sacerdote, à porta da tenda da revelação;

[[v4-6-11]]

^<<v4-6-11,11>>^ e o sacerdote oferecerá um como oferta pelo pecado, e o outro como holocausto, e fará expiação por esse que pecou no tocante ao morto; assim naquele mesmo dia santificará a sua cabeça.

[[v4-6-12]]

^<<v4-6-12,12>>^ Então separará ao Senhor os dias do seu nazireado, e para oferta pela culpa trará um cordeiro de um ano; mas os dias antecedentes serão perdidos, porquanto o seu nazireado foi contaminado.

[[v4-6-13]]

^<<v4-6-13,13>>^ Esta, pois, é a lei do nazireu: no dia em que se cumprirem os dias do seu nazireado ele será trazido à porta da tenda da revelação,

[[v4-6-14]]

^<<v4-6-14,14>>^ e oferecerá a sua oferta ao Senhor: um cordeiro de um ano, sem defeito, como holocausto, e uma cordeira de um ano, sem defeito, como oferta pelo pecado, e um carneiro sem defeito como oferta pacífica;

[[v4-6-15]]

^<<v4-6-15,15>>^ e um cesto de pães ázimos, bolos de flor de farinha amassados com azeite como também as respectivas ofertas de cereais e de libação.

[[v4-6-16]]

^<<v4-6-16,16>>^ E o sacerdote os apresentará perante o Senhor, e oferecerá a oferta pelo pecado, e o holocausto;

[[v4-6-17]]

^<<v4-6-17,17>>^ também oferecerá o carneiro em sacrifício de oferta pacífica ao Senhor, com o cesto de pães ázimos e as respectivas ofertas de cereais e de libação.

[[v4-6-18]]

^<<v4-6-18,18>>^ Então o nazireu, à porta da tenda da revelação, rapará o cabelo do seu nazireado, tomá-lo-á e o porá sobre o fogo que está debaixo do sacrifício das ofertas pacíficas.

[[v4-6-19]]

^<<v4-6-19,19>>^ Depois o sacerdote tomará a espádua cozida do carneiro, e um pão ázimo do cesto, e um coscorão ázimo, e os porá nas mãos do nazireu, depois de haver este rapado o cabelo do seu nazireado;

[[v4-6-20]]

^<<v4-6-20,20>>^ e o sacerdote os moverá como oferta de movimento perante o Senhor; isto é santo para o sacerdote, juntamente com o peito da oferta de movimento, e com a espádua da oferta alçada; e depois o nazireu poderá beber vinho.

[[v4-6-21]]

^<<v4-6-21,21>>^ Esta é a lei do que fizer voto de nazireu, e da sua oferta ao Senhor pelo seu nazireado, afora qualquer outra coisa que as suas posses lhe permitirem oferecer; segundo o seu voto, que fizer, assim fará conforme a lei o seu nazireado.

[[v4-6-22]]

^<<v4-6-22,22>>^ Disse mais o Senhor a Moisés:

[[v4-6-23]]

^<<v4-6-23,23>>^ Fala a Arão, e a seus filhos, dizendo: Assim abençoareis os filhos de Israel; dir-lhes-eis:

[[v4-6-24]]

^<<v4-6-24,24>>^ O Senhor te abençoe e te guarde;

[[v4-6-25]]

^<<v4-6-25,25>>^ o Senhor faça resplandecer o seu rosto sobre ti, e tenha misericórdia de ti;

[[v4-6-26]]

^<<v4-6-26,26>>^ o Senhor levante sobre ti o seu rosto, e te dê a paz.

[[v4-6-27]]

^<<v4-6-27,27>>^ Assim porão o meu nome sobre os filhos de Israel, e eu os abençoarei.

'''

xref:004-numeros/004-numeros-005.adoc#v4-5-0[&#60; Capítulo Anterior] | <<v4-6-0,Topo>> | xref:004-numeros/004-numeros-007.adoc#v4-7-0[Próximo Capítulo &#62;]