include::./index.adoc[]

[[v4-25-0]]
=== Números, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-25-1]]

^<<v4-25-1,1>>^ Ora, Israel demorava-se em Sitim, e o povo começou a prostituir-se com as filhas de Moabe,

[[v4-25-2]]

^<<v4-25-2,2>>^ pois elas convidaram o povo aos sacrifícios dos seus deuses; e o povo comeu, e inclinou-se aos seus deuses.

[[v4-25-3]]

^<<v4-25-3,3>>^ Porquanto Israel se juntou a Baal-Peor, a ira do Senhor acendeu-se contra ele.

[[v4-25-4]]

^<<v4-25-4,4>>^ Disse, pois, o Senhor a Moisés: Toma todos os cabeças do povo, e enforca-os ao senhor diante do sol, para que a grande ira do Senhor se retire de Israel.

[[v4-25-5]]

^<<v4-25-5,5>>^ Então Moisés disse aos juízes de Israel: Mate cada um os seus homens que se juntaram a Baal-Peor.

[[v4-25-6]]

^<<v4-25-6,6>>^ E eis que veio um homem dos filhos de Israel, e trouxe a seus irmãos uma midianita à vista de Moisés e à vista de toda a congregação dos filhos de Israel, enquanto estavam chorando à porta da tenda da revelação.

[[v4-25-7]]

^<<v4-25-7,7>>^ Vendo isso Finéias, filho de Eleazar, filho do sacerdote Arão, levantou-se do meio da congregação, e tomou na mão uma lança;

[[v4-25-8]]

^<<v4-25-8,8>>^ o foi após o israelita, e entrando na sua tenda, os atravessou a ambos, ao israelita e à mulher, pelo ventre. Então a praga cessou de sobre os filhos de Israel.

[[v4-25-9]]

^<<v4-25-9,9>>^ Ora, os que morreram daquela praga foram vinte e quatro mil.

[[v4-25-10]]

^<<v4-25-10,10>>^ Então disse o Senhor a Moisés:

[[v4-25-11]]

^<<v4-25-11,11>>^ Finéias, filho de Eleazar, filho do sacerdote Arão, desviou a minha ira de sobre os filhos de Israel, pois foi zeloso com o meu zelo no meio deles, de modo que no meu zelo não consumi os filhos de Israel.

[[v4-25-12]]

^<<v4-25-12,12>>^ Portanto dize: Eis que lhe dou o meu pacto de paz,

[[v4-25-13]]

^<<v4-25-13,13>>^ e será para ele e para a sua descendência depois dele, o pacto de um sacerdócio perpétuo; porquanto foi zeloso pelo seu Deus, e fez expiação pelos filhos de Israel.

[[v4-25-14]]

^<<v4-25-14,14>>^ O nome do israelita que foi morto com a midianita era Zinri, filho de Salu, príncipe duma casa paterna entre os simeonitas.

[[v4-25-15]]

^<<v4-25-15,15>>^ E o nome da mulher midianita morta era Cozbi, filha de Zur; o qual era cabeça do povo duma casa paterna em Midiã.

[[v4-25-16]]

^<<v4-25-16,16>>^ Disse mais o Senhor a Moisés:

[[v4-25-17]]

^<<v4-25-17,17>>^ Afligi vós os midianitas e feri-os;

[[v4-25-18]]

^<<v4-25-18,18>>^ porque eles vos afligiram a vós com as suas ciladas com que vos enganaram no caso de Peor, e no caso de Cozbi, sua irmã, filha do príncipe de Midiã, a qual foi morta no dia da praga no caso de Peor.

'''

xref:004-numeros/004-numeros-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numeros/004-numeros-026.adoc#v4-26-0[Próximo Capítulo &#62;]