include::./index.adoc[]

[[v4-9-0]]
=== Números, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-9-1]]

^<<v4-9-1,1>>^ Também falou o Senhor a Moisés no deserto de Sinai, no primeiro mês do segundo ano depois que saíram da terra do Egito, dizendo:

[[v4-9-2]]

^<<v4-9-2,2>>^ Celebrem os filhos de Israel a páscoa a seu tempo determinado.

[[v4-9-3]]

^<<v4-9-3,3>>^ No dia catorze deste mês, à tardinha, a seu tempo determinado, a celebrareis; segundo todos os seus estatutos, e segundo todas as suas ordenanças a celebrareis.

[[v4-9-4]]

^<<v4-9-4,4>>^ Disse, pois, Moisés aos filhos de Israel que celebrassem a páscoa.

[[v4-9-5]]

^<<v4-9-5,5>>^ Então celebraram a páscoa no dia catorze do primeiro mês, à tardinha, no deserto de Sinai; conforme tudo o que o Senhor ordenara a Moisés, assim fizeram os filhos de Israel.

[[v4-9-6]]

^<<v4-9-6,6>>^ Ora, havia alguns que se achavam imundos por terem tocado o cadáver de um homem, de modo que não podiam celebrar a páscoa naquele dia; pelo que no mesmo dia se chegaram perante Moisés e Arão;

[[v4-9-7]]

^<<v4-9-7,7>>^ e aqueles homens disseram-lhes: Estamos imundos por havermos tocado o cadáver de um homem; por que seríamos privados de oferecer a oferta do Senhor a seu tempo determinado no meio dos filhos de Israel?

[[v4-9-8]]

^<<v4-9-8,8>>^ Respondeu-lhes Moisés: Esperai, para que eu ouça o que o Senhor há de ordenar acerca de vós.

[[v4-9-9]]

^<<v4-9-9,9>>^ Então disse o Senhor a Moisés:

[[v4-9-10]]

^<<v4-9-10,10>>^ Fala aos filhos de Israel, dizendo: Se alguém dentre vós, ou dentre os vossos descendentes estiver imundo por ter tocado um cadáver, ou achar-se longe, em viagem, contudo ainda celebrará a páscoa ao Senhor.

[[v4-9-11]]

^<<v4-9-11,11>>^ No segundo mês, no dia: catorze, à tardinha, a celebrarão; comê-la-ão com pães ázimos e ervas amargas.

[[v4-9-12]]

^<<v4-9-12,12>>^ Dela não deixarão nada até pela manhã, nem quebrarão dela osso algum; segundo todo o estatuto da páscoa a celebrarão.

[[v4-9-13]]

^<<v4-9-13,13>>^ Mas o homem que, estando limpo e não se achando em viagem, deixar de celebrar a páscoa, essa alma será extirpada do seu povo; porquanto não ofereceu a oferta do Senhor a seu tempo determinado, tal homem levará o seu pecado.

[[v4-9-14]]

^<<v4-9-14,14>>^ Também se um estrangeiro peregrinar entre vós e celebrar a páscoa ao Senhor, segundo o estatuto da páscoa e segundo a sua ordenança a celebrará; haverá um só estatuto, quer para o estrangeiro, quer para o natural da terra.

[[v4-9-15]]

^<<v4-9-15,15>>^ No dia em que foi levantado o tabernáculo, a nuvem cobriu o tabernáculo, isto é, a própria tenda do testemunho; e desde a tarde até pela manhã havia sobre o tabernáculo uma aparência de fogo.

[[v4-9-16]]

^<<v4-9-16,16>>^ Assim acontecia de contínuo: a nuvem o cobria, e de noite havia aparência de fogo.

[[v4-9-17]]

^<<v4-9-17,17>>^ Mas sempre que a nuvem se alçava de sobre a tenda, os filhos de Israel partiam; e no lugar em que a nuvem parava, ali os filhos de Israel se acampavam.

[[v4-9-18]]

^<<v4-9-18,18>>^ À ordem do Senhor os filhos de Israel partiam, e à ordem do Senhor se acampavam; por todos os dias em que a nuvem parava sobre o tabernáculo eles ficavam acampados.

[[v4-9-19]]

^<<v4-9-19,19>>^ E, quando a nuvem se detinha sobre o tabernáculo muitos dias, os filhos de Israel cumpriam o mandado do Senhor, e não partiam.

[[v4-9-20]]

^<<v4-9-20,20>>^ Às vezes a nuvem ficava poucos dias sobre o tabernáculo; então à ordem do Senhor permaneciam acampados, e à ordem do Senhor partiam.

[[v4-9-21]]

^<<v4-9-21,21>>^ Outras vezes ficava a nuvem desde a tarde até pela manhã; e quando pela manhã a nuvem se alçava, eles partiam; ou de dia ou de noite, alçando-se a nuvem, partiam.

[[v4-9-22]]

^<<v4-9-22,22>>^ Quer fosse por dois dias, quer por um mês, quer por mais tempo, que a nuvem se detinha sobre o tabernáculo, enquanto ficava sobre ele os filhos de Israel permaneciam acampados, e não partiam; mas, alçando-se ela, eles partiam.

[[v4-9-23]]

^<<v4-9-23,23>>^ À ordem do Senhor se acampavam, e à ordem do Senhor partiam; cumpriam o mandado do Senhor, que ele lhes dera por intermédio de Moisés.

'''

xref:004-numeros/004-numeros-008.adoc#v4-8-0[&#60; Capítulo Anterior] | <<v4-9-0,Topo>> | xref:004-numeros/004-numeros-010.adoc#v4-10-0[Próximo Capítulo &#62;]