include::./index.adoc[]

[[v4-29-0]]
=== Números, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-29-1]]

^<<v4-29-1,1>>^ No sétimo mês, no primeiro dia do mês, tereis uma santa convocação; nenhum trabalho servil fareis; será para vós dia de sonido de trombetas.

[[v4-29-2]]

^<<v4-29-2,2>>^ Oferecereis um holocausto em cheiro suave ao Senhor: um novilho, um carneiro e sete cordeiros de um ano, todos sem defeito;

[[v4-29-3]]

^<<v4-29-3,3>>^ e a sua oferta de cereais, de flor de farinha misturada com azeite, três décimos de efa para o novilho, dois décimos para o carneiro,

[[v4-29-4]]

^<<v4-29-4,4>>^ e um décimo para cada um dos sete cordeiros;

[[v4-29-5]]

^<<v4-29-5,5>>^ e um bode para oferta pelo pecado, para fazer expiação por vós;

[[v4-29-6]]

^<<v4-29-6,6>>^ além do holocausto do mês e a sua oferta de cereais, e do holocausto contínuo e a sua oferta de cereais, com as suas ofertas de libação, segundo a ordenança, em cheiro suave, oferta queimada ao Senhor.

[[v4-29-7]]

^<<v4-29-7,7>>^ Também no dia dez deste sétimo mês tereis santa convocação, e afligireis as vossas almas; nenhum trabalho fareis;

[[v4-29-8]]

^<<v4-29-8,8>>^ mas oferecereis um holocausto, em cheiro suave ao Senhor: um novilho, um carneiro e sete cordeiros de um ano, todos eles sem defeito;

[[v4-29-9]]

^<<v4-29-9,9>>^ e a sua oferta de cereais, de flor de farinha misturada com azeite, três décimos de efa para o novilho, dois décimos para o carneiro,

[[v4-29-10]]

^<<v4-29-10,10>>^ e um décimo para cada um dos sete cordeiros;

[[v4-29-11]]

^<<v4-29-11,11>>^ e um bode para oferta pelo pecado, além da oferta pelo pecado, com a qual se faz expiação, e do holocausto contínuo com a sua oferta de cereais e as suas ofertas de libação.

[[v4-29-12]]

^<<v4-29-12,12>>^ Semelhantemente, aos quinze dias deste sétimo mês tereis santa convocação; nenhum trabalho servil fareis; mas por sete dias celebrareis festa ao Senhor.

[[v4-29-13]]

^<<v4-29-13,13>>^ Oferecereis um holocausto em oferta queimada, de cheiro suave ao Senhor: treze novilhos, dois carneiros e catorze cordeiros de um ano, todos eles sem defeito;

[[v4-29-14]]

^<<v4-29-14,14>>^ e a sua oferta de cereais, de flor de farinha misturada com azeite, três décimos de efa para cada um dos treze novilhos, dois décimos para cada um dos dois carneiros,

[[v4-29-15]]

^<<v4-29-15,15>>^ e um décimo para cada um dos catorze cordeiros;

[[v4-29-16]]

^<<v4-29-16,16>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e a sua oferta de libação.

[[v4-29-17]]

^<<v4-29-17,17>>^ No segundo dia, doze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-18]]

^<<v4-29-18,18>>^ e a sua oferta de cereais, e as suas ofertas de libação para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo a ordenança;

[[v4-29-19]]

^<<v4-29-19,19>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e as suas ofertas de libação:

[[v4-29-20]]

^<<v4-29-20,20>>^ No terceiro dia, onze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-21]]

^<<v4-29-21,21>>^ e a sua oferta de cereais, e as suas ofertas de libação para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo a ordenança;

[[v4-29-22]]

^<<v4-29-22,22>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e a sua oferta de libação.

[[v4-29-23]]

^<<v4-29-23,23>>^ No quarto dia, dez novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-24]]

^<<v4-29-24,24>>^ e a sua oferta de cereais, e as suas ofertas de libação para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo a ordenança;

[[v4-29-25]]

^<<v4-29-25,25>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e a sua oferta de libação.

[[v4-29-26]]

^<<v4-29-26,26>>^ No quinto dia, nove novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-27]]

^<<v4-29-27,27>>^ e a sua oferta de cereais, e as suas ofertas de libação para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo a ordenança;

[[v4-29-28]]

^<<v4-29-28,28>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e a sua oferta de libação.

[[v4-29-29]]

^<<v4-29-29,29>>^ No sexto dia, oito novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-30]]

^<<v4-29-30,30>>^ e a sua oferta de cereais, e as suas ofertas de libação para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo a ordenança;

[[v4-29-31]]

^<<v4-29-31,31>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e a sua oferta de libação.

[[v4-29-32]]

^<<v4-29-32,32>>^ No sétimo dia, sete novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-33]]

^<<v4-29-33,33>>^ e a sua oferta de cereais, e as suas ofertas de libação para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo a ordenança;

[[v4-29-34]]

^<<v4-29-34,34>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e a sua oferta de libação.

[[v4-29-35]]

^<<v4-29-35,35>>^ No oitavo dia tereis assembléia solene; nenhum trabalho servil fareis;

[[v4-29-36]]

^<<v4-29-36,36>>^ mas oferecereis um holocausto em oferta queimada de cheiro suave ao Senhor: um novilho, um carneiro, sete cordeiros de um ano, sem defeito;

[[v4-29-37]]

^<<v4-29-37,37>>^ e a sua oferta de cereais, e as suas ofertas de libação para o novilho, para o carneiro e para os cordeiros, conforme o seu número, segundo a ordenança;

[[v4-29-38]]

^<<v4-29-38,38>>^ e um bode para oferta pelo pecado, além do holocausto contínuo com a sua oferta de cereais e a sua oferta de libação.

[[v4-29-39]]

^<<v4-29-39,39>>^ Oferecereis essas coisas ao Senhor nas vossas festas fixas, além dos vossos votos, e das vossas ofertas voluntárias, tanto para os vossos holocaustos, como para as vossas ofertas de cereais, as vossas ofertas de libações e os vossos sacrifícios de ofertas pacíficas.

[[v4-29-40]]

^<<v4-29-40,40>>^ Falou, pois, Moisés aos filhos de Israel, conforme tudo o que o Senhor lhe ordenara.

'''

xref:004-numeros/004-numeros-028.adoc#v4-28-0[&#60; Capítulo Anterior] | <<v4-29-0,Topo>> | xref:004-numeros/004-numeros-030.adoc#v4-30-0[Próximo Capítulo &#62;]