include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-4-1]]

^<<v4-4-1,1>>^ Disse mais o Senhor a Moisés e a Arão:

[[v4-4-2]]

^<<v4-4-2,2>>^ Tomai a soma dos filhos de Coate, dentre os filhos de Levi, pelas suas famílias, segundo as casas de seus pais,

[[v4-4-3]]

^<<v4-4-3,3>>^ da idade de trinta anos para cima até os cinqüenta anos, de todos os que entrarem no serviço para fazerem o trabalho na tenda da revelação.

[[v4-4-4]]

^<<v4-4-4,4>>^ Este será o serviço dos filhos de Coate; na tenda da revelação, no tocante as coisas santíssimas:

[[v4-4-5]]

^<<v4-4-5,5>>^ Quando partir o arraial, Arão e seus filhos entrarão e, abaixando o véu do reposteiro, com ele cobrirão a arca do testemunho;

[[v4-4-6]]

^<<v4-4-6,6>>^ por-lhe-ão por cima uma coberta de peles de golfinhos, e sobre ela estenderão um pano todo de azul, e lhe meterão os varais.

[[v4-4-7]]

^<<v4-4-7,7>>^ Sobre a mesa dos pães da proposição estenderão um pano de azul, e sobre ela colocarão os pratos, as colheres, as tigelas e os cântaros para as ofertas de libação; também o pão contínuo estará sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Depois estender-lhe-ão por cima um pano de carmesim, o qual cobrirão com uma coberta de peles de golfinhos, e meterão à mesa os varais.

[[v4-4-9]]

^<<v4-4-9,9>>^ Então tomarão um pano de azul, e cobrirão o candelabro da luminária, as suas lâmpadas, os seus espevitadores, os seus cinzeiros, e todos os seus vasos do azeite, com que o preparam;

[[v4-4-10]]

^<<v4-4-10,10>>^ e o envolverão, juntamente com todos os seus utensílios, em uma coberta de peles de golfinhos, e o colocarão sobre os varais.

[[v4-4-11]]

^<<v4-4-11,11>>^ Sobre o altar de ouro estenderão um pano de azul, e com uma coberta de peles de golfinhos o cobrirão, e lhe meterão os varais.

[[v4-4-12]]

^<<v4-4-12,12>>^ Também tomarão todos os utensílios do ministério, com que servem no santuário, envolvê-los-ão num pano de azul e, cobrindo-os com uma coberta de peles de golfinhos, os colocarão sobre os varais.

[[v4-4-13]]

^<<v4-4-13,13>>^ E, tirando as cinzas do altar, estenderão sobre ele um pano de púrpura;

[[v4-4-14]]

^<<v4-4-14,14>>^ colocarão nele todos os utensílios com que o servem: os seus braseiros, garfos, as pás e as bacias, todos os utensílios do altar; e sobre ele estenderão uma coberta de peles de golfinhos, e lhe meterão os varais.

[[v4-4-15]]

^<<v4-4-15,15>>^ Quando Arão e seus filhos, ao partir o arraial, acabarem de cobrir o santuário e todos os seus móveis, os filhos de Coate virão para levá-lo; mas nas coisas sagradas não tocarão, para que não morram; esse é o cargo dos filhos de Coate na tenda da revelação.

[[v4-4-16]]

^<<v4-4-16,16>>^ Eleazar, filho de Arão, o sacerdote, terá a seu cargo o azeite da luminária, o incenso aromático, a oferta contínua de cereais e o óleo da unção; isto é, terá a seu cargo todo o tabernáculo, e tudo o que nele há, o santuário e os seus móveis.

[[v4-4-17]]

^<<v4-4-17,17>>^ Disse mais o Senhor a Moisés e a Arão:

[[v4-4-18]]

^<<v4-4-18,18>>^ Não cortareis a tribo das famílias dos coatitas do meio dos levitas;

[[v4-4-19]]

^<<v4-4-19,19>>^ mas isto lhes fareis, para que vivam e não morram, quando se aproximarem das coisas santíssimas: Arão e seus filhos entrarão e lhes designarão a cada um o seu serviço e o seu cargo;

[[v4-4-20]]

^<<v4-4-20,20>>^ mas eles não entrarão a ver, nem por um momento, as coisas sagradas, para que não morram.

[[v4-4-21]]

^<<v4-4-21,21>>^ Disse mais o Senhor a Moisés:

[[v4-4-22]]

^<<v4-4-22,22>>^ Toma também a soma dos filhos de Gérsom segundo as casas de seus pais, segundo as suas famílias;

[[v4-4-23]]

^<<v4-4-23,23>>^ da idade de trinta anos para cima até os cinqüenta os contarás, a todos os que entrarem no serviço para fazerem o trabalho na tenda da revelação.

[[v4-4-24]]

^<<v4-4-24,24>>^ Este será o serviço das famílias dos gersonitas, ao servirem e ao levarem as cargas:

[[v4-4-25]]

^<<v4-4-25,25>>^ levarão as cortinas do tabernáculo, a tenda da revelação, a sua coberta, a coberta de peles de golfinhos, que está por cima, o reposteiro da porta da tenda da revelação,

[[v4-4-26]]

^<<v4-4-26,26>>^ as cortinas do átrio, o reposteiro da porta do átrio, que está junto ao tabernáculo e junto ao altar em redor, as suas cordas, e todos os instrumentos do seu serviço; enfim tudo quanto se houver de fazer no tocante a essas coisas, nisso hão de servir.

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o trabalho dos filhos dos gersonitas, em todo o seu cargo, e em todo o seu serviço, será segundo o mandado de Arão e de seus filhos; e lhes designareis os cargos em que deverão servir.

[[v4-4-28]]

^<<v4-4-28,28>>^ Este é o serviço das famílias dos filhos dos gersonitas na tenda da revelação; e o seu trabalho estará sob a direção de Itamar, filho de Arão, o sacerdote.

[[v4-4-29]]

^<<v4-4-29,29>>^ Quanto aos filhos de Merári, contá-los-ás segundo as suas famílias, segundo as casas e seus pais;

[[v4-4-30]]

^<<v4-4-30,30>>^ da idade de trinta anos para cima até os cinqüenta os contarás, a todos os que entrarem no serviço para fazerem o trabalho da tenda da revelação,

[[v4-4-31]]

^<<v4-4-31,31>>^ Este será o seu encargo, segundo todo o seu serviço na tenda da revelação: as armações do tabernáculo e os seus varais, as suas colunas e as suas bases,

[[v4-4-32]]

^<<v4-4-32,32>>^ como também as colunas do átrio em redor e as suas bases, as suas estacas e as suas cordas, com todos os seus objetos, e com todo o seu serviço; e por nome lhes designareis os objetos que ficarão a seu cargo.

[[v4-4-33]]

^<<v4-4-33,33>>^ Este é o serviço das famílias dos filhos de Merári, segundo todo o seu trabalho na tenda da revelação, sob a direção de Itamar, filho de Arão, o sacerdote.

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, pois, e Arão e os príncipes da congregação contaram os filhos dos coatitas, segundo as suas famílias, segundo as casas e seus pais,

[[v4-4-35]]

^<<v4-4-35,35>>^ da idade de trinta anos para cima até os cinqüenta, todos os que entraram no serviço para o trabalho na tenda da revelação;

[[v4-4-36]]

^<<v4-4-36,36>>^ os que deles foram contados, pois, segundo as suas famílias, eram dois mil setecentos e cinqüenta.

[[v4-4-37]]

^<<v4-4-37,37>>^ Esses são os que foram contados das famílias dos coatitas, isto é, todos os que haviam de servir na tenda da revelação, aos quais Moisés e Arão contaram, conforme o mandado do Senhor por intermédio de Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Semelhantemente os que foram contados dos filhos de Gérsom segundo as suas famílias, segundo as casas de seus pais,

[[v4-4-39]]

^<<v4-4-39,39>>^ da idade de trinta anos para cima até os cinqüenta, todos os que entraram no serviço, para o trabalho na tenda da revelação,

[[v4-4-40]]

^<<v4-4-40,40>>^ os que deles foram contados, segundo as suas famílias, segundo as casas de seus pais, eram dois mil seiscentos e trinta.

[[v4-4-41]]

^<<v4-4-41,41>>^ Esses são os que foram contados das famílias dos filhos de Gérsom todos os que haviam de servir na tenda da revelação, aos quais Moisés e Arão contaram, conforme o mandado do Senhor.

[[v4-4-42]]

^<<v4-4-42,42>>^ E os que foram contados das famílias dos filhos de Merári, segundo as suas famílias, segundo as casas de seus pais,

[[v4-4-43]]

^<<v4-4-43,43>>^ da idade de trinta anos para cima até os cinqüenta, todos os que entraram no serviço, para o trabalho na tenda da revelação,

[[v4-4-44]]

^<<v4-4-44,44>>^ os que deles foram contados, segundo as suas famílias, eram três mil e duzentos.

[[v4-4-45]]

^<<v4-4-45,45>>^ Esses são os que foram contados das famílias dos filhos de Merári, aos quais Moisés e Arão contaram, conforme o mandado do Senhor por intermédio de Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Todos os que foram contados dos levitas, aos quais contaram Moisés e Arão e os príncipes de Israel, segundo as suas famílias, segundo as casas de seus pais,

[[v4-4-47]]

^<<v4-4-47,47>>^ da idade de trinta anos para cima até os cinqüenta, todos os que entraram no serviço para trabalharem e para levarem cargas na tenda da revelação,

[[v4-4-48]]

^<<v4-4-48,48>>^ os que deles foram contados eram oito mil quinhentos e oitenta.

[[v4-4-49]]

^<<v4-4-49,49>>^ Conforme o mandado do Senhor foram contados por Moisés, cada qual segundo o seu serviço, e segundo o seu cargo; assim foram contados por ele, como o Senhor lhe ordenara.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]