include::./index.adoc[]

[[v4-17-0]]
=== Números, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-17-1]]

^<<v4-17-1,1>>^ Então disse o Senhor a Moisés:

[[v4-17-2]]

^<<v4-17-2,2>>^ Fala aos filhos de Israel, e toma deles uma vara para cada casa paterna de todos os seus príncipes, segundo as casas de seus pais, doze varas; e escreve o nome de cada um sobre a sua vara.

[[v4-17-3]]

^<<v4-17-3,3>>^ O nome de Arão escreverás sobre a vara de Levi; porque cada cabeça das casas de seus pais terá uma vara.

[[v4-17-4]]

^<<v4-17-4,4>>^ E as porás na tenda da revelação, perante o testemunho, onde venho a vós.

[[v4-17-5]]

^<<v4-17-5,5>>^ Então brotará a vara do homem que eu escolher; assim farei cessar as murmurações dos filhos de Israel contra mim, com que murmuram contra vós.

[[v4-17-6]]

^<<v4-17-6,6>>^ Falou, pois, Moisés aos filhos de Israel, e todos os seus príncipes deram-lhe varas, cada príncipe uma, segundo as casas de seus pais, doze varas; e entre elas estava a vara de Arão.

[[v4-17-7]]

^<<v4-17-7,7>>^ E Moisés depositou as varas perante o Senhor na tenda do testemunho.

[[v4-17-8]]

^<<v4-17-8,8>>^ Sucedeu, pois, no dia seguinte, que Moisés entrou na tenda do testemunho, e eis que a vara de Arão, pela casa de Levi, brotara, produzira gomos, rebentara em flores e dera amêndoas maduras.

[[v4-17-9]]

^<<v4-17-9,9>>^ Então Moisés trouxe todas as varas de diante do Senhor a todos os filhos de Israel; e eles olharam, e tomaram cada um a sua vara.

[[v4-17-10]]

^<<v4-17-10,10>>^ Então o Senhor disse a Moisés: Torna a pôr a vara de Arão perante o testemunho, para se guardar por sinal contra os filhos rebeldes; para que possas fazer acabar as suas murmurações contra mim, a fim de que não morram.

[[v4-17-11]]

^<<v4-17-11,11>>^ Assim fez Moisés; como lhe ordenara o Senhor, assim fez.

[[v4-17-12]]

^<<v4-17-12,12>>^ Então disseram os filhos de Israel a Moisés: Eis aqui, nós expiramos, perecemos, todos nós perecemos.

[[v4-17-13]]

^<<v4-17-13,13>>^ Todo aquele que se aproximar, sim, todo o que se aproximar do tabernáculo do Senhor, morrerá; porventura pereceremos todos?

'''

xref:004-numeros/004-numeros-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numeros/004-numeros-018.adoc#v4-18-0[Próximo Capítulo &#62;]