include::./index.adoc[]

[[v4-34-0]]
=== Números, 34
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-34-1]]

^<<v4-34-1,1>>^ Disse mais o Senhor a Moisés:

[[v4-34-2]]

^<<v4-34-2,2>>^ Dá ordem aos filhos de Israel, e dize-lhes: Quando entrardes na terra de Canaã, terra esta que vos há de cair em herança, por toda a sua extensão,

[[v4-34-3]]

^<<v4-34-3,3>>^ a banda do sul será desde o deserto de Zim, ao longo de Edom; e o limite do sul se estenderá da extremidade do Mar Salgado, para o oriente;

[[v4-34-4]]

^<<v4-34-4,4>>^ e este limite irá rodeando para o sul da subida de Acrabim, e continuará até Zim; e, saindo ao sul de Cades-Barnéia, seguirá para Hazar-Hadar, e continuará até Azmom;

[[v4-34-5]]

^<<v4-34-5,5>>^ e daí irá rodeando até o ribeiro do Egito, e terminará na praia do mar.

[[v4-34-6]]

^<<v4-34-6,6>>^ Para o ocidente, o Mar Grande vos será por limite; o próprio mar será o vosso limite ocidental.

[[v4-34-7]]

^<<v4-34-7,7>>^ Este será o vosso limite setentrional: desde o Mar Grande marcareis para vós até o Monte Hor;

[[v4-34-8]]

^<<v4-34-8,8>>^ desde o monte Hor marcareis até a entrada de Hamate; daí ele se estenderá até Zedade;

[[v4-34-9]]

^<<v4-34-9,9>>^ dali continuará até Zifrom, e irá terminar em Hazar-Enã. Este será o vosso limite setentrional.

[[v4-34-10]]

^<<v4-34-10,10>>^ Marcareis o vosso limite oriental desde Hazar-Enã até Sefã;

[[v4-34-11]]

^<<v4-34-11,11>>^ este limite descerá de Sefã até Ribla, ao oriente de Aim; depois irá descendo ao longo da borda do mar de Quinerete ao oriente;

[[v4-34-12]]

^<<v4-34-12,12>>^ descerá ainda para o Jordão, e irá terminar no Mar Salgado. Esta será a vossa terra, segundo os seus limites em redor.

[[v4-34-13]]

^<<v4-34-13,13>>^ Moisés, pois, deu ordem aos filhos de Israel, dizendo: Esta é a terra que herdareis por sortes, a qual o Senhor mandou que se desse às nove tribos e à meia tribo;

[[v4-34-14]]

^<<v4-34-14,14>>^ porque a tribo dos filhos de Rúben, segundo as casas de seus pais, e a tribo dos filhos de Gade, segundo as casas de seus pais, como também a meia tribo de Manassés, já receberam a sua herança;

[[v4-34-15]]

^<<v4-34-15,15>>^ isto é, duas tribos e meia já receberam a sua herança aquém do Jordão, na altura de Jericó, do lado oriental.

[[v4-34-16]]

^<<v4-34-16,16>>^ Disse mais o Senhor a Moisés:

[[v4-34-17]]

^<<v4-34-17,17>>^ Estes são os nomes dos homens que vos repartirão a terra por herança: Eleazar, o sacerdote, e Josué, filho de Num;

[[v4-34-18]]

^<<v4-34-18,18>>^ também tomareis de cada tribo um príncipe, para repartir a terra em herança.

[[v4-34-19]]

^<<v4-34-19,19>>^ E estes são os nomes dos homens: Da tribo de Judá, Calebe, filho de Jefoné:

[[v4-34-20]]

^<<v4-34-20,20>>^ da tribo dos filhos de Simeão, Semuel, filho de Amiúde;

[[v4-34-21]]

^<<v4-34-21,21>>^ da tribo de Benjamim, Elidá, filho de Quislom;

[[v4-34-22]]

^<<v4-34-22,22>>^ da tribo dos filhos de Dã o príncipe Buqui, filho de Jógli;

[[v4-34-23]]

^<<v4-34-23,23>>^ dos filhos de José: da tribo dos filhos de Manassés o príncipe Haniel, filho de Éfode;

[[v4-34-24]]

^<<v4-34-24,24>>^ da tribo dos filhos de Efraim o príncipe Quemuel, filho de Siftã;

[[v4-34-25]]

^<<v4-34-25,25>>^ da tribo dos filhos de Zebulom o príncipe Elizafã, filho de Parnaque;

[[v4-34-26]]

^<<v4-34-26,26>>^ da tribo dos filhos de Issacar o príncipe Paltiel, filho de Azã;

[[v4-34-27]]

^<<v4-34-27,27>>^ da tribo dos filhos de Aser o príncipe Aiúde, filho de Selômi;

[[v4-34-28]]

^<<v4-34-28,28>>^ da tribo dos filhos de Naftali o príncipe Pedael, filho de Amiúde.

[[v4-34-29]]

^<<v4-34-29,29>>^ Estes são aqueles a quem o Senhor ordenou que repartissem a herança pelos filhos de Israel na terra de Canaã.

'''

xref:004-numeros/004-numeros-033.adoc#v4-33-0[&#60; Capítulo Anterior] | <<v4-34-0,Topo>> | xref:004-numeros/004-numeros-035.adoc#v4-35-0[Próximo Capítulo &#62;]