include::./index.adoc[]

[[v4-35-0]]
=== Números, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-35-1]]

^<<v4-35-1,1>>^ Disse mais o Senhor a Moisés nas planícies de Moabe, junto ao Jordão, na altura de Jericó:

[[v4-35-2]]

^<<v4-35-2,2>>^ Dá ordem aos filhos de Israel que da herança da sua possessão dêem aos levitas cidades em que habitem; também dareis aos levitas arrabaldes ao redor delas.

[[v4-35-3]]

^<<v4-35-3,3>>^ Terão eles estas cidades para habitarem; e os arrabaldes delas serão para os seus gados, e para a sua fazenda, e para todos os seus animais.

[[v4-35-4]]

^<<v4-35-4,4>>^ Os arrabaldes que dareis aos levitas se estenderão, do muro da cidade para fora, mil côvados em redor.

[[v4-35-5]]

^<<v4-35-5,5>>^ E fora da cidade medireis para o lado oriental dois mil côvados, para o lado meridional dois mil côvados, para o lado ocidental dois mil côvados, e para o lado setentrional dois mil côvados; e a cidade estará no meio. Isso terão por arrabaldes das cidades.

[[v4-35-6]]

^<<v4-35-6,6>>^ Entre as cidades que dareis aos levitas haverá seis cidades de refúgio, as quais dareis para que nelas se acolha o homicida; e além destas lhes dareis quarenta e duas cidades.

[[v4-35-7]]

^<<v4-35-7,7>>^ Todas as cidades que dareis aos levitas serão quarenta e oito, juntamente com os seus arrabaldes.

[[v4-35-8]]

^<<v4-35-8,8>>^ Ora, no tocante às cidades que dareis da possessão dos filhos de Israel, da tribo que for grande tomareis muitas, e da que for pequena tomareis poucas; cada uma segundo a herança que receber dará as suas cidades aos levitas.

[[v4-35-9]]

^<<v4-35-9,9>>^ Disse mais o Senhor a Moisés:

[[v4-35-10]]

^<<v4-35-10,10>>^ Fala aos filhos de Israel, e dize-lhes: Quando passardes o Jordão para a terra de Canaã,

[[v4-35-11]]

^<<v4-35-11,11>>^ escolhereis para vós cidades que vos sirvam de cidades de refúgio, para que se refugie ali o homicida que tiver matado alguém involuntariamente.

[[v4-35-12]]

^<<v4-35-12,12>>^ E estas cidades vos serão por refúgio do vingador, para que não morra o homicida antes de ser apresentado perante a congregação para julgamento.

[[v4-35-13]]

^<<v4-35-13,13>>^ Serão seis as cidades que haveis de dar por cidades de refúgio para vós.

[[v4-35-14]]

^<<v4-35-14,14>>^ Dareis três cidades aquém do Jordão, e três na terra de Canaã; cidades de refúgio serão.

[[v4-35-15]]

^<<v4-35-15,15>>^ Estas seis cidades serão por refúgio aos filhos de Israel, ao estrangeiro, e ao peregrino no meio deles, para que se refugie ali todo aquele que tiver matado alguém involuntariamente.

[[v4-35-16]]

^<<v4-35-16,16>>^ Mas se alguém ferir a outrem com instrumento de ferro de modo que venha a morrer, homicida é; e o homicida será morto.

[[v4-35-17]]

^<<v4-35-17,17>>^ Ou se o ferir com uma pedra na mão, que possa causar a morte, e ele morrer, homicida é; e o homicida será morto.

[[v4-35-18]]

^<<v4-35-18,18>>^ Ou se o ferir com instrumento de pau na mão, que possa causar a morte, e ele morrer, homicida é; será morto o homicida.

[[v4-35-19]]

^<<v4-35-19,19>>^ O vingador do sangue matará ao homicida; ao encontrá-lo, o matará.

[[v4-35-20]]

^<<v4-35-20,20>>^ Ou se alguém empurrar a outrem por ódio ou de emboscada lançar contra ele alguma coisa de modo que venha a morrer,

[[v4-35-21]]

^<<v4-35-21,21>>^ ou por inimizade o ferir com a mão de modo que venha a morrer, será morto aquele que o feriu; homicida é. O vingador do sangue, ao encontrá-lo, o matará.

[[v4-35-22]]

^<<v4-35-22,22>>^ Mas se o empurrar acidentalmente, sem inimizade, ou contra ele lançar algum instrumento, sem ser de emboscada,

[[v4-35-23]]

^<<v4-35-23,23>>^ ou sobre ele atirar alguma pedra, não o vendo, e o ferir de modo que venha a morrer, sem que fosse seu inimigo nem procurasse o seu mal,

[[v4-35-24]]

^<<v4-35-24,24>>^ então a congregação julgará entre aquele que feriu e o vingador do sangue, segundo estas leis,

[[v4-35-25]]

^<<v4-35-25,25>>^ e a congregação livrará o homicida da mão do vingador do sangue, fazendo-o voltar à sua cidade de refúgio a que se acolhera; ali ficará ele morando até a morte do sumo sacerdote, que foi ungido com o óleo sagrado.

[[v4-35-26]]

^<<v4-35-26,26>>^ Mas, se de algum modo o homicida sair dos limites da sua cidade de refúgio, onde se acolhera,

[[v4-35-27]]

^<<v4-35-27,27>>^ e o vingador do sangue o achar fora dos limites da sua cidade de refúgio, e o matar, não será culpado de sangue;

[[v4-35-28]]

^<<v4-35-28,28>>^ pois o homicida deverá ficar na sua cidade de refúgio até a morte do sumo sacerdote; mas depois da morte do sumo sacerdote o homicida voltará para a terra da sua possessão.

[[v4-35-29]]

^<<v4-35-29,29>>^ Estas coisas vos serão por estatuto de direito pelas vossas gerações, em todos os lugares da vossa habitação.

[[v4-35-30]]

^<<v4-35-30,30>>^ Todo aquele que matar alguém, será morto conforme o depoimento de testemunhas; mas uma só testemunha não deporá contra alguém, para condená-lo à morte.

[[v4-35-31]]

^<<v4-35-31,31>>^ Não aceitareis resgate pela vida de um homicida que é réu de morte; porém ele certamente será morto.

[[v4-35-32]]

^<<v4-35-32,32>>^ Também não aceitareis resgate por aquele que se tiver acolhido à sua cidade de refúgio, a fim de que ele possa tornar a habitar na terra antes da morte do sumo sacerdote.

[[v4-35-33]]

^<<v4-35-33,33>>^ Assim não profanareis a terra da vossa habitação, porque o sangue profana a terra; e nenhuma expiação se poderá fazer pela terra por causa do sangue que nela for derramado, senão com o sangue daquele que o derramou.

[[v4-35-34]]

^<<v4-35-34,34>>^ Não contaminareis, pois, a terra em que haveis de habitar, no meio da qual eu também habitarei; pois eu, o Senhor, habito no meio dos filhos de Israel.

'''

xref:004-numeros/004-numeros-034.adoc#v4-34-0[&#60; Capítulo Anterior] | <<v4-35-0,Topo>> | xref:004-numeros/004-numeros-036.adoc#v4-36-0[Próximo Capítulo &#62;]