include::./index.adoc[]

[[v4-2-0]]
=== Números, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-2-1]]

^<<v4-2-1,1>>^ Disse o Senhor a Moisés e a Arão:

[[v4-2-2]]

^<<v4-2-2,2>>^ Os filhos de Israel acampar-se-ão, cada um junto ao seu estandarte, com as insígnias das casas de seus pais; ao redor, de frente para a tenda da revelação, se acamparão.

[[v4-2-3]]

^<<v4-2-3,3>>^ Ao lado oriental se acamparão os do estandarte do arraial de Judá, segundo os seus exércitos; e Nasom, filho de Aminadabe, será o príncipe dos filhos de Judá.

[[v4-2-4]]

^<<v4-2-4,4>>^ E o seu exército, os que foram contados deles, era de setenta e quatro mil e seiscentos.

[[v4-2-5]]

^<<v4-2-5,5>>^ Junto a eles se acamparão os da tribo de Issacar; e Netanel, filho de Zuar, será o príncipe dos filhos de Issacar.

[[v4-2-6]]

^<<v4-2-6,6>>^ E o seu exército, os que foram contados deles, era de cinqüenta e quatro mil e quatrocentos.

[[v4-2-7]]

^<<v4-2-7,7>>^ Depois a tribo de Zebulom; e Eliabe, filho de Helom, será o príncipe dos filhos de Zebulom.

[[v4-2-8]]

^<<v4-2-8,8>>^ E o seu exército, os que foram contados deles, era de cinqüenta e sete mil e quatrocentos.

[[v4-2-9]]

^<<v4-2-9,9>>^ Todos os que foram contados do arraial de Judá eram cento e oitenta e seis mil e quatrocentos, segundo os seus exércitos. Esses marcharão primeiro.

[[v4-2-10]]

^<<v4-2-10,10>>^ O estandarte do arraial de Rúben segundo os seus exércitos, estará para a banda do sul; e Elizur, filho de Sedeur, será o príncipe dos filhos de Rúben.

[[v4-2-11]]

^<<v4-2-11,11>>^ E o seu exército, os que foram contados deles, era de quarenta e seis mil e quinhentos.

[[v4-2-12]]

^<<v4-2-12,12>>^ Junto a ele se acamparão os da tribo de Simeão; e Selumiel, filho de Zurisadai, será o príncipe dos filhos de Simeão.

[[v4-2-13]]

^<<v4-2-13,13>>^ E o seu exército, os que foram contados deles, era de cinqüenta e nove mil e trezentos.

[[v4-2-14]]

^<<v4-2-14,14>>^ Depois a tribo de Gade; e Eliasafe, filho de Reuel, será o príncipe dos filhos de Gade.

[[v4-2-15]]

^<<v4-2-15,15>>^ E o seu exército, os que foram contados deles, era de quarenta e cinco mil seiscentos e cinqüenta.

[[v4-2-16]]

^<<v4-2-16,16>>^ Todos os que foram contados do arraial de Rúben eram cento e cinqüenta e um mil quatrocentos e cinqüenta, segundo os seus exércitos. Esses marcharão em segundo lugar.

[[v4-2-17]]

^<<v4-2-17,17>>^ Então partirá a tenda da revelação com o arraial dos levitas no meio dos arraiais; como se acamparem, assim marcharão, cada um no seu lugar, segundo os seus estandartes.

[[v4-2-18]]

^<<v4-2-18,18>>^ Para a banda do ocidente estará o estandarte do arraial de Efraim, segundo os seus exércitos; e Elisama, filho de Amiúde, será o príncipe dos filhos de Efraim.

[[v4-2-19]]

^<<v4-2-19,19>>^ E o seu exército, os que foram contados deles, era de quarenta mil e quinhentos.

[[v4-2-20]]

^<<v4-2-20,20>>^ Junto a eles estará a tribo de Manassés; e Gamaliel, filho de Pedazur, será o príncipe dos filhos de Manassés.

[[v4-2-21]]

^<<v4-2-21,21>>^ E o seu exército, os que foram contados deles, era de trinta e dois mil e duzentos.

[[v4-2-22]]

^<<v4-2-22,22>>^ Depois a tribo de Benjamim; e Abidã, filho de Gideôni, será o príncipe dos filhos de Benjamim.

[[v4-2-23]]

^<<v4-2-23,23>>^ E o seu exército, os que foram contados deles, era de trinta e cinco mil e quatrocentos.

[[v4-2-24]]

^<<v4-2-24,24>>^ Todos os que foram contados o arraial de Efraim eram cento e oito mil e cem, segundo os seus exércitos. Esses marcharão em terceiro lugar.

[[v4-2-25]]

^<<v4-2-25,25>>^ Para a banda do norte estará o estandarte do arraial de Dã, segundo os seus exércitos; e Aiezer, filho de Amisadai, será o príncipe dos filhos de Dã.

[[v4-2-26]]

^<<v4-2-26,26>>^ E o seu exército, os que foram contados deles, era de sessenta e dois mil e setecentos.

[[v4-2-27]]

^<<v4-2-27,27>>^ Junto a eles se acamparão os da tribo de Aser; e Pagiel, filho de Ocrã, será o príncipe dos filhos de Aser.

[[v4-2-28]]

^<<v4-2-28,28>>^ E o seu exército, os que foram contados deles, era de quarenta e um mil e quinhentos.

[[v4-2-29]]

^<<v4-2-29,29>>^ Depois a tribo de Naftali; e Airá, filho de Enã, será o príncipe dos filhos de Naftali.

[[v4-2-30]]

^<<v4-2-30,30>>^ E o seu exército, os que foram contados deles, era de cinqüenta e três mil e quatrocentos.

[[v4-2-31]]

^<<v4-2-31,31>>^ Todos os que foram contados do arraial de Dã eram cento e cinqüenta e sete mil e seiscentos. Esses marcharão em último lugar, segundo os seus estandartes.

[[v4-2-32]]

^<<v4-2-32,32>>^ São esses os que foram contados dos filhos de Israel, segundo as casas de seus pais; todos os que foram contados dos arraiais segundo os seus exércitos, eram seiscentos e três mil quinhentos e cinqüenta.

[[v4-2-33]]

^<<v4-2-33,33>>^ Os levitas, porém, não foram contados entre os filhos de Israel, como o Senhor ordenara a Moisés.

[[v4-2-34]]

^<<v4-2-34,34>>^ Assim fizeram os filhos de Israel, conforme tudo o que o Senhor ordenara a Moisés; acamparam-se segundo os seus estandartes, e marcharam, cada qual segundo as suas famílias, segundo as casas de seus pais.

'''

xref:004-numeros/004-numeros-001.adoc#v4-1-0[&#60; Capítulo Anterior] | <<v4-2-0,Topo>> | xref:004-numeros/004-numeros-003.adoc#v4-3-0[Próximo Capítulo &#62;]