include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-23-1]]

^<<v4-23-1,1>>^ Disse Balaão a Balaque: Edifica-me aqui sete altares e prepara-me aqui sete novilhos e sete carneiros.

[[v4-23-2]]

^<<v4-23-2,2>>^ Fez, pois, Balaque como Balaão dissera; e Balaque e Balaão ofereceram um novilho e um carneiro sobre cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Então Balaão disse a Balaque: Fica aqui em pé junto ao teu holocausto, e eu irei; porventura o Senhor me sairá ao encontro, e o que ele me mostrar, eu to direi. E foi a um lugar alto.

[[v4-23-4]]

^<<v4-23-4,4>>^ E quando Deus se encontrou com Balaão, este lhe disse: Preparei os sete altares, e ofereci um novilho e um carneiro sobre cada altar.

[[v4-23-5]]

^<<v4-23-5,5>>^ Então o senhor pôs uma palavra na boca de Balaão, e disse: Volta para Balaque, e assim falarás.

[[v4-23-6]]

^<<v4-23-6,6>>^ Voltou, pois, para ele, e eis que estava em pé junto ao seu holocausto, ele e todos os príncipes de Moabe.

[[v4-23-7]]

^<<v4-23-7,7>>^ Então proferiu Balaão a sua parábola, dizendo: De Arã me mandou trazer Balaque, o rei de Moabe, desde as montanhas do Oriente, dizendo: Vem, amaldiçoa-me a Jacó; vem, denuncia a Israel.

[[v4-23-8]]

^<<v4-23-8,8>>^ Como amaldiçoarei a quem Deus não amaldiçoou? e como denunciarei a quem o Senhor não denunciou?

[[v4-23-9]]

^<<v4-23-9,9>>^ Pois do cume das penhas o vejo, e dos outeiros o contemplo; eis que é um povo que habita só, e entre as nações não será contado.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem poderá contar o pó de Jacó e o número da quarta parte de Israel? Que eu morra a morte dos justos, e seja o meu fim como o deles.

[[v4-23-11]]

^<<v4-23-11,11>>^ Então disse Balaque a Balaão: Que me fizeste? Chamei-te para amaldiçoares os meus inimigos, e eis que inteiramente os abençoaste.

[[v4-23-12]]

^<<v4-23-12,12>>^ E ele respondeu: Porventura não terei cuidado de falar o que o Senhor me puser na boca?

[[v4-23-13]]

^<<v4-23-13,13>>^ Então Balaque lhe disse: Rogo-te que venhas comigo a outro lugar, donde o poderás ver; verás somente a última parte dele, mas a todo ele não verás; e amaldiçoa-mo dali.

[[v4-23-14]]

^<<v4-23-14,14>>^ Assim o levou ao campo de Zofim, ao cume de Pisga; e edificou sete altares, e ofereceu um novilho e um carneiro sobre cada altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ Disse Balaão a Balaque: Fica aqui em pé junto ao teu holocausto, enquanto eu vou ali ao encontro do Senhor.

[[v4-23-16]]

^<<v4-23-16,16>>^ E, encontrando-se o Senhor com Balaão, pôs-lhe na boca uma palavra, e disse: Volta para Balaque, e assim falarás.

[[v4-23-17]]

^<<v4-23-17,17>>^ Voltou, pois, para ele, e eis que estava em pé junto ao seu holocausto, e os príncipes de Moabe com ele. Perguntou-lhe, pois, Balaque: Que falou o Senhor?

[[v4-23-18]]

^<<v4-23-18,18>>^ Então proferiu Balaão a sua parábola, dizendo: Levanta-te, Balaque, e ouve; escuta-me, filho de Zipor;

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é homem, para que minta; nem filho do homem, para que se arrependa. Porventura, tendo ele dito, não o fará? ou, havendo falado, não o cumprirá?

[[v4-23-20]]

^<<v4-23-20,20>>^ Eis que recebi mandado de abençoar; pois ele tem abençoado, e eu não o posso revogar.

[[v4-23-21]]

^<<v4-23-21,21>>^ Não se observa iniqüidade em Jacó, nem se vê maldade em Israel; o senhor seu Deus é com ele, no meio dele se ouve a aclamação dum rei;

[[v4-23-22]]

^<<v4-23-22,22>>^ É Deus que os vem tirando do Egito; as suas forças são como as do boi selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ Contra Jacó, pois, não há encantamento, nem adivinhação contra Israel. Agora se dirá de Jacó e de Israel: Que coisas Deus tem feito!

[[v4-23-24]]

^<<v4-23-24,24>>^ Eis que o povo se levanta como leoa, e se ergue como leão; não se deitará até que devore a presa, e beba o sangue dos que foram mortos:

[[v4-23-25]]

^<<v4-23-25,25>>^ Então Balaque disse a Balaão: Nem o amaldiçoes, nem tampouco o abençoes:

[[v4-23-26]]

^<<v4-23-26,26>>^ Respondeu, porém, Balaão a Balaque: Não te falei eu, dizendo: Tudo o que o Senhor falar, isso tenho de fazer?

[[v4-23-27]]

^<<v4-23-27,27>>^ Tornou Balaque a Balaão: Vem agora, e te levarei a outro lugar; porventura parecerá bem aos olhos de Deus que dali mo amaldiçoes.

[[v4-23-28]]

^<<v4-23-28,28>>^ Então Balaque levou Balaão ao cume de Peor, que dá para o deserto.

[[v4-23-29]]

^<<v4-23-29,29>>^ E Balaão disse a Balaque: Edifica-me aqui sete altares, e prepara-me aqui sete novilhos e sete carneiros.

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque, pois, fez como dissera Balaão; e ofereceu um novilho e um carneiro sobre cada altar.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]