include::./index.adoc[]

[[v4-32-0]]
=== Números, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-32-1]]

^<<v4-32-1,1>>^ Ora, os filhos de Rúben e os filhos de Gade tinham gado em grande quantidade; e quando viram a terra de Jazer, e a terra de Gileade, e que a região era própria para o gado,

[[v4-32-2]]

^<<v4-32-2,2>>^ vieram os filhos de Gade e os filhos de Rúben a Moisés e a Eleazar, o sacerdote, e aos príncipes da congregação e falaram-lhes, dizendo:

[[v4-32-3]]

^<<v4-32-3,3>>^ Atarote, Dibom, Jazer, Ninra, Hesbom, Eleale, Sebã, Nebo e Beom,

[[v4-32-4]]

^<<v4-32-4,4>>^ a terra que o Senhor feriu diante da congregação de Israel, é terra para gado, e os teus servos têm gado.

[[v4-32-5]]

^<<v4-32-5,5>>^ Disseram mais: Se temos achado graça aos teus olhos, dê-se esta terra em possessão aos teus servos, e não nos faças passar o Jordão.

[[v4-32-6]]

^<<v4-32-6,6>>^ Moisés, porém, respondeu aos filhos de Gade e aos filhos de Rúben: Irão vossos irmãos à peleja, e ficareis vós sentados aqui?

[[v4-32-7]]

^<<v4-32-7,7>>^ Por que, pois, desanimais o coração dos filhos de Israel, para eles não passarem à terra que o Senhor lhes deu?

[[v4-32-8]]

^<<v4-32-8,8>>^ Assim fizeram vossos pais, quando os mandei de Cades-Barnéia a ver a terra.

[[v4-32-9]]

^<<v4-32-9,9>>^ Pois, tendo eles subido até o vale de Escol, e visto a terra, desanimaram o coração dos filhos de Israel, para que não entrassem na terra que o Senhor lhes dera.

[[v4-32-10]]

^<<v4-32-10,10>>^ Então a ira do Senhor se acendeu naquele mesmo dia, e ele jurou, dizendo:

[[v4-32-11]]

^<<v4-32-11,11>>^ De certo os homens que subiram do Egito, de vinte anos para cima, não verão a terra que prometi com juramento a Abraão, a Isaque, e a Jacó! porquanto não perseveraram em seguir-me;

[[v4-32-12]]

^<<v4-32-12,12>>^ exceto Calebe, filho de Jefoné o quenezeu, e Josué, filho de Num, porquanto perseveraram em seguir ao Senhor.

[[v4-32-13]]

^<<v4-32-13,13>>^ Assim se acendeu a ira do Senhor contra Israel, e ele os fez andar errantes no deserto quarenta anos, até que se consumiu toda aquela geração que fizera mal aos olhos do Senhor.

[[v4-32-14]]

^<<v4-32-14,14>>^ E eis que vós, uma geração de homens pecadores, vos levantastes em lugar de vossos pais, para ainda mais aumentardes o furor da ira do Senhor contra Israel.

[[v4-32-15]]

^<<v4-32-15,15>>^ se vós vos virardes de segui-lo, também ele tornará a deixá-los no deserto; assim destruireis a todo este povo:

[[v4-32-16]]

^<<v4-32-16,16>>^ Então chegaram-se a ele, e disseram: Construiremos aqui currais para o nosso gado, e cidades para os nossos pequeninos;

[[v4-32-17]]

^<<v4-32-17,17>>^ nós, porém, nos armaremos, apressando-nos adiante dos filhos de Israel, até os levarmos ao seu lugar; e ficarão os nossos pequeninos nas cidades fortificadas, por causa dos habitantes da terra.

[[v4-32-18]]

^<<v4-32-18,18>>^ Não voltaremos para nossas casas até que os filhos de Israel estejam de posse, cada um, da sua herança.

[[v4-32-19]]

^<<v4-32-19,19>>^ Porque não herdaremos com eles além do Jordão, nem mais adiante; visto que já possuímos a nossa herança aquém do Jordão, ao oriente.

[[v4-32-20]]

^<<v4-32-20,20>>^ Então lhes respondeu Moisés: se isto fizerdes, se vos armardes para a guerra perante o Senhor,

[[v4-32-21]]

^<<v4-32-21,21>>^ e cada um de vós, armado, passar o Jordão perante o Senhor, até que ele haja lançado fora os seus inimigos de diante dele,

[[v4-32-22]]

^<<v4-32-22,22>>^ e a terra esteja subjugada perante o senhor, então, sim, voltareis e sereis inculpáveis perante o Senhor e perante Israel; e esta terra vos será por possessão perante o Senhor.

[[v4-32-23]]

^<<v4-32-23,23>>^ Mas se não fizerdes assim, estareis pecando contra o Senhor; e estai certos de que o vosso pecado vos há de atingir.

[[v4-32-24]]

^<<v4-32-24,24>>^ Edificai cidades para os vossos pequeninos, e currais para as vossas ovelhas; e cumpri o que saiu da vossa boca.

[[v4-32-25]]

^<<v4-32-25,25>>^ Então os filhos de Gade e os filhos de Rúben disseram a Moisés: Como ordena meu senhor, assim farão teus servos.

[[v4-32-26]]

^<<v4-32-26,26>>^ Os nossos pequeninos, as nossas mulheres, os nossos rebanhos e todo o nosso gado ficarão nas cidades de Gileade;

[[v4-32-27]]

^<<v4-32-27,27>>^ mas os teus servos passarão, cada um que está armado para a guerra, a pelejar perante o Senhor, como diz o meu senhor.

[[v4-32-28]]

^<<v4-32-28,28>>^ Então Moisés deu ordem acerca deles a Eleazar, o sacerdote, e a Josué, filho de Num, e aos cabeças das casas paternas nas tribos dos filhos de Israel;

[[v4-32-29]]

^<<v4-32-29,29>>^ e disse-lhes Moisés: Se os filhos de Gade e os filhos de Rúben passarem convosco o Jordão, armado cada um para a guerra perante o Senhor, e a terra for subjugada diante de vós, então lhes dareis a terra de Gileade por possessão;

[[v4-32-30]]

^<<v4-32-30,30>>^ se, porém, não passarem armados convosco, terão possessões entre vós na terra de Canaã.

[[v4-32-31]]

^<<v4-32-31,31>>^ Ao que responderam os filhos de Gade e os filhos de Rúben: Como o senhor disse a teus servos, assim faremos.

[[v4-32-32]]

^<<v4-32-32,32>>^ Nós passaremos armados perante o senhor para a terra de Canaã, e teremos a possessão de nossa herança aquém do Jordão.

[[v4-32-33]]

^<<v4-32-33,33>>^ Assim deu Moisés aos filhos de Gade e aos filhos de Rúben, e à meia tribo de Manassés, filho de José, o reino de Siom, rei dos amorreus, e o reino de Ogue, rei de Basã, a terra com as suas cidades e os respectivos territórios ao redor.

[[v4-32-34]]

^<<v4-32-34,34>>^ Os filhos de Gade, pois, edificaram a Dibom, Atarote, Aroer,

[[v4-32-35]]

^<<v4-32-35,35>>^ Atarote-Sofã, Jazer, Jogbeá,

[[v4-32-36]]

^<<v4-32-36,36>>^ Bete-Ninra e Bete-Harã, cidades fortificadas; e construíram currais de ovelhas.

[[v4-32-37]]

^<<v4-32-37,37>>^ E os filhos de Rúben edificaram a Hesbom, Eleale e Quiriataim;

[[v4-32-38]]

^<<v4-32-38,38>>^ e Nebo e Baal-Meom &#123;mudando-lhes os nomes&#125;, e Sibma; e deram outros nomes às cidades que edificaram.

[[v4-32-39]]

^<<v4-32-39,39>>^ E os filhos de Maquir, filho de Manassés, foram a Gileade e a tomaram, e desapossaram aos amorreus que aí estavam.

[[v4-32-40]]

^<<v4-32-40,40>>^ Deu, pois, Moisés a terra de Gileade a Maquir, filho de Manassés, o qual habitou nela.

[[v4-32-41]]

^<<v4-32-41,41>>^ E foi Jair, filho de Manassés, e tomou as aldeias dela, e chamou-lhes Havote-Jair.

[[v4-32-42]]

^<<v4-32-42,42>>^ Também foi Nobá, e tomou a Quenate com as suas aldeias; e chamou-lhe Nobá, segundo o seu próprio nome.

'''

xref:004-numeros/004-numeros-031.adoc#v4-31-0[&#60; Capítulo Anterior] | <<v4-32-0,Topo>> | xref:004-numeros/004-numeros-033.adoc#v4-33-0[Próximo Capítulo &#62;]