include::./index.adoc[]

[[v4-5-0]]
=== Números, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-5-1]]

^<<v4-5-1,1>>^ Disse mais o Senhor a Moisés:

[[v4-5-2]]

^<<v4-5-2,2>>^ Ordena aos filhos de Israel que lancem para fora do arraial a todo leproso, e a todo o que padece fluxo, e a todo o que está oriundo por ter tocado num morto;

[[v4-5-3]]

^<<v4-5-3,3>>^ tanto homem como mulher os lançareis para fora, sim, para fora do arraial os lançareis; para que não contaminem o seu arraial, no meio do qual eu habito.

[[v4-5-4]]

^<<v4-5-4,4>>^ Assim fizeram os filhos de Israel, lançando-os para fora do arraial; como o Senhor falara a Moisés, assim fizeram os filhos de Israel.

[[v4-5-5]]

^<<v4-5-5,5>>^ Disse mais o Senhor a Moisés:

[[v4-5-6]]

^<<v4-5-6,6>>^ Dize aos filhos de Israel: Quando homem ou mulher pecar contra o seu próximo, transgredindo os mandamentos do Senhor, e tornando-se assim culpado,

[[v4-5-7]]

^<<v4-5-7,7>>^ confessará o pecado que tiver cometido, e pela sua culpa fará plena restituição, e ainda lhe acrescentará a sua quinta parte; e a dará àquele contra quem se fez culpado.

[[v4-5-8]]

^<<v4-5-8,8>>^ Mas, se esse homem não tiver parente chegado, a quem se possa fazer a restituição pela culpa, esta será feita ao Senhor, e será do sacerdote, além do carneiro da expiação com que se fizer expiação por ele.

[[v4-5-9]]

^<<v4-5-9,9>>^ Semelhantemente toda oferta alçada de todas as coisas consagradas dos filhos de Israel, que estes trouxerem ao sacerdote, será dele.

[[v4-5-10]]

^<<v4-5-10,10>>^ Enfim, as coisas consagradas de cada um serão do sacerdote; tudo o que alguém lhe der será dele.

[[v4-5-11]]

^<<v4-5-11,11>>^ Disse mais o Senhor a Moisés:

[[v4-5-12]]

^<<v4-5-12,12>>^ Fala aos filhos de Israel, e dize-lhes: Se a mulher de alguém se desviar pecando contra ele,

[[v4-5-13]]

^<<v4-5-13,13>>^ e algum homem se deitar com ela, sendo isso oculto aos olhos de seu marido e conservado encoberto, se ela se tiver contaminado, e contra ela não houver testemunha, por não ter sido apanhada em flagrante;

[[v4-5-14]]

^<<v4-5-14,14>>^ se o espírito de ciúmes vier sobre ele, e de sua mulher tiver ciúmes, por ela se haver contaminado, ou se sobre ele vier o espírito de ciúmes, e de sua mulher tiver ciúmes, mesmo que ela não se tenha contaminado;

[[v4-5-15]]

^<<v4-5-15,15>>^ o homem trará sua mulher perante o sacerdote, e juntamente trará a sua oferta por ela, a décima parte de uma efa de farinha de cevada, sobre a qual não deitará azeite nem porá incenso; porquanto é oferta de cereais por ciúmes, oferta memorativa, que traz a iniqüidade à memória.

[[v4-5-16]]

^<<v4-5-16,16>>^ O sacerdote fará a mulher chegar, e a porá perante o Senhor.

[[v4-5-17]]

^<<v4-5-17,17>>^ E o sacerdote tomará num vaso de barro água sagrada; também tomará do pó que houver no chão do tabernáculo, e o deitará na água.

[[v4-5-18]]

^<<v4-5-18,18>>^ Então apresentará a mulher perante o Senhor, e descobrirá a cabeça da mulher, e lhe porá na mão a oferta de cereais memorativa, que é a oferta de cereais por ciúmes; e o sacerdote terá na mão a água de amargura, que traz consigo a maldição;

[[v4-5-19]]

^<<v4-5-19,19>>^ e a fará jurar, e dir-lhe-á: Se nenhum homem se deitou contigo, e se não te desviaste para a imundícia, violando o voto conjugal, sejas tu livre desta água de amargura, que traz consigo a maldição;

[[v4-5-20]]

^<<v4-5-20,20>>^ mas se te desviaste, violando o voto conjugal, e te contaminaste, e algum homem que não é teu marido se deitou contigo,-

[[v4-5-21]]

^<<v4-5-21,21>>^ então o sacerdote, fazendo que a mulher tome o juramento de maldição, lhe dirá: O Senhor te ponha por maldição e praga no meio do teu povo, fazendo-te o Senhor consumir-se a tua coxa e inchar o teu ventre;

[[v4-5-22]]

^<<v4-5-22,22>>^ e esta água que traz consigo a maldição entrará nas tuas entranhas, para te fazer inchar o ventre, e te fazer consumir-se a coxa. Então a mulher dirá: Amém, amém.

[[v4-5-23]]

^<<v4-5-23,23>>^ Então o sacerdote escreverá estas maldições num livro, e na água de amargura as apagará;

[[v4-5-24]]

^<<v4-5-24,24>>^ e fará que a mulher beba a água de amargura, que traz consigo a maldição; e a água que traz consigo a maldição entrará nela para se tornar amarga.

[[v4-5-25]]

^<<v4-5-25,25>>^ E o sacerdote tomará da mão da mulher a oferta de cereais por ciúmes, e moverá a oferta de cereais perante o Senhor, e a trará ao altar;

[[v4-5-26]]

^<<v4-5-26,26>>^ também tomará um punhado da oferta de cereais como memorial da oferta, e o queimará sobre o altar, e depois fará que a mulher beba a água.

[[v4-5-27]]

^<<v4-5-27,27>>^ Quando ele tiver feito que ela beba a água, sucederá que, se ela se tiver contaminado, e tiver pecado contra seu marido, a água, que traz consigo a maldição, entrará nela, tornando-se amarga; inchar-lhe-á o ventre e a coxa se lhe consumirá; e a mulher será por maldição no meio do seu povo.

[[v4-5-28]]

^<<v4-5-28,28>>^ E, se a mulher não se tiver contaminado, mas for inocente, então será livre, e conceberá filhos.

[[v4-5-29]]

^<<v4-5-29,29>>^ Esta é a lei dos ciúmes, no tocante à mulher que, violando o voto conjugal, se desviar e for contaminada;

[[v4-5-30]]

^<<v4-5-30,30>>^ ou no tocante ao homem sobre quem vier o espírito de ciúmes, e se enciumar de sua mulher; ele apresentará a mulher perante o Senhor, e o sacerdote cumprirá para com ela toda esta lei.

[[v4-5-31]]

^<<v4-5-31,31>>^ Esse homem será livre da iniqüidade; a mulher, porém, levará sobre si a sua iniqüidade.

'''

xref:004-numeros/004-numeros-004.adoc#v4-4-0[&#60; Capítulo Anterior] | <<v4-5-0,Topo>> | xref:004-numeros/004-numeros-006.adoc#v4-6-0[Próximo Capítulo &#62;]