include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-24-1]]

^<<v4-24-1,1>>^ Vendo Balaão que parecia bem aos olhos do Senhor que abençoasse a Israel, não foi, como era costume, ao encontro dos encantamentos, mas voltou o rosto para o deserto.

[[v4-24-2]]

^<<v4-24-2,2>>^ E, levantando Balaão os olhos, viu a Israel que se achava acampado segundo as suas tribos; e veio sobre ele o Espírito de Deus.

[[v4-24-3]]

^<<v4-24-3,3>>^ Então proferiu Balaão a sua parábola, dizendo: Fala Balaão, filho de Beor; fala o homem que tem os olhos abertos;

[[v4-24-4]]

^<<v4-24-4,4>>^ fala aquele que ouve as palavras de Deus, o que vê a visão do Todo-Poderoso, que cai, e se lhe abrem os olhos:

[[v4-24-5]]

^<<v4-24-5,5>>^ Quão formosas são as tuas tendas, ó Jacó! as tuas moradas, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Como vales, elas se estendem; são como jardins à beira dos rios, como árvores de aloés que o Senhor plantou, como cedros junto às águas.

[[v4-24-7]]

^<<v4-24-7,7>>^ De seus baldes manarão águas, e a sua semente estará em muitas águas; o seu rei se exalçará mais do que Agague, e o seu reino será exaltado.

[[v4-24-8]]

^<<v4-24-8,8>>^ É Deus que os vem tirando do Egito; as suas forças são como as do boi selvagem; ele devorará as nações, seus adversários, lhes quebrará os ossos, e com as suas setas os atravessará.

[[v4-24-9]]

^<<v4-24-9,9>>^ Agachou-se, deitou-se como leão, e como leoa; quem o despertará? Benditos os que te abençoarem, e malditos os que te amaldiçoarem.

[[v4-24-10]]

^<<v4-24-10,10>>^ Pelo que a ira de Balaque se acendeu contra Balaão, e batendo ele as palmas, disse a Balaão: Para amaldiçoares os meus inimigos é que te chamei; e eis que já três vezes os abençoaste.

[[v4-24-11]]

^<<v4-24-11,11>>^ Agora, pois, foge para o teu lugar; eu tinha dito que certamente te honraria, mas eis que o Senhor te privou dessa honra.

[[v4-24-12]]

^<<v4-24-12,12>>^ Então respondeu Balaão a Balaque: Não falei eu também aos teus mensageiros, que me enviaste, dizendo:

[[v4-24-13]]

^<<v4-24-13,13>>^ Ainda que Balaque me quisesse dar a sua casa cheia de prata e de ouro, eu não poderia ir além da ordem do Senhor, para fazer, de mim mesmo, o bem ou o mal; o que o Senhor falar, isso falarei eu?

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora, pois, eis que me vou ao meu povo; vem, avisar-te-ei do que este povo fará ao teu povo nos últimos dias.

[[v4-24-15]]

^<<v4-24-15,15>>^ Então proferiu Balaão a sua parábola, dizendo: Fala Balaão, filho de Beor; fala o homem que tem os olhos abertos;

[[v4-24-16]]

^<<v4-24-16,16>>^ fala aquele que ouve as palavras de Deus e conhece os desígnios do Altíssimo, que vê a visão do Todo-Poderoso, que cai, e se lhe abrem os olhos:

[[v4-24-17]]

^<<v4-24-17,17>>^ Eu o vejo, mas não no presente; eu o contemplo, mas não de perto; de Jacó procederá uma estrela, de Israel se levantará um cetro que ferirá os termos de Moabe, e destruirá todos os filhos de orgulho.

[[v4-24-18]]

^<<v4-24-18,18>>^ E Edom lhe será uma possessão, e assim também Seir, os quais eram os seus inimigos; pois Israel fará proezas.

[[v4-24-19]]

^<<v4-24-19,19>>^ De Jacó um dominará e destruirá os sobreviventes da cidade.

[[v4-24-20]]

^<<v4-24-20,20>>^ Também viu Balaão a Amaleque e proferiu a sua parábola, dizendo: Amaleque era a primeira das nações, mas o seu fim será a destruição.

[[v4-24-21]]

^<<v4-24-21,21>>^ E, vendo os quenitas, proferiu a sua parábola, dizendo: Firme está a tua habitação; e posto na penha está o teu ninho;

[[v4-24-22]]

^<<v4-24-22,22>>^ todavia será o quenita assolado, até que Assur te leve por prisioneiro.

[[v4-24-23]]

^<<v4-24-23,23>>^ Proferiu ainda a sua parábola, dizendo: Ai, quem viverá, quando Deus fizer isto?

[[v4-24-24]]

^<<v4-24-24,24>>^ Naus virão das costas de Quitim, e afligirão a Assur; igualmente afligirão a Eber, que também será para destruição.

[[v4-24-25]]

^<<v4-24-25,25>>^ Então, tendo-se Balaão levantado, partiu e voltou para o seu lugar; e também Balaque se foi pelo seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]