include::./index.adoc[]

[[v4-14-0]]
=== Números, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v4-14-1]]

^<<v4-14-1,1>>^ Então toda a congregação levantou a voz e gritou; e o povo chorou naquela noite.

[[v4-14-2]]

^<<v4-14-2,2>>^ E todos os filhos de Israel murmuraram contra Moisés e Arão; e toda a congregação lhes disse: Antes tivéssemos morrido na terra do Egito, ou tivéssemos morrido neste deserto!

[[v4-14-3]]

^<<v4-14-3,3>>^ Por que nos traz o Senhor a esta terra para cairmos à espada? Nossas mulheres e nossos pequeninos serão por presa. Não nos seria melhor voltarmos para o Egito?

[[v4-14-4]]

^<<v4-14-4,4>>^ E diziam uns aos outros: Constituamos um por chefe o voltemos para o Egito.

[[v4-14-5]]

^<<v4-14-5,5>>^ Então Moisés e Arão caíram com os rostos por terra perante toda a assembléia da congregação dos filhos de Israel.

[[v4-14-6]]

^<<v4-14-6,6>>^ E Josué, filho de Num, e Calebe, filho de Jefoné, que eram dos que espiaram a terra, rasgaram as suas vestes;

[[v4-14-7]]

^<<v4-14-7,7>>^ e falaram a toda a congregação dos filhos de Israel, dizendo: A terra, pela qual passamos para a espiar, é terra muitíssimo boa.

[[v4-14-8]]

^<<v4-14-8,8>>^ Se o Senhor se agradar de nós, então nos introduzirá nesta terra e no-la dará; terra que mana leite e mel.

[[v4-14-9]]

^<<v4-14-9,9>>^ Tão somente não sejais rebeldes contra o Senhor, e não temais o povo desta terra, porquanto são eles nosso pão. Retirou-se deles a sua defesa, e o Senhor está conosco; não os temais.

[[v4-14-10]]

^<<v4-14-10,10>>^ Mas toda a congregação disse que fossem apedrejados. Nisso a glória do Senhor apareceu na tenda da revelação a todos os filhos de Israel.

[[v4-14-11]]

^<<v4-14-11,11>>^ Disse então o Senhor a Moisés: Até quando me desprezará este povo e até quando não crerá em mim, apesar de todos os sinais que tenho feito no meio dele?

[[v4-14-12]]

^<<v4-14-12,12>>^ Com pestilência o ferirei, e o rejeitarei; e farei de ti uma nação maior e mais forte do que ele.

[[v4-14-13]]

^<<v4-14-13,13>>^ Respondeu Moisés ao Senhor: Assim os egípcios o ouvirão, eles, do meio dos quais, com a tua força, fizeste subir este povo,

[[v4-14-14]]

^<<v4-14-14,14>>^ e o dirão aos habitantes desta terra. Eles ouviram que tu, ó Senhor, estás no meio deste povo; pois tu, ó Senhor, és visto face a face, e a tua nuvem permanece sobre eles, e tu vais adiante deles numa coluna de nuvem de dia, e numa coluna de fogo de noite.

[[v4-14-15]]

^<<v4-14-15,15>>^ E se matares este povo como a um só homem, então as nações que têm ouvido da tua fama, dirão:

[[v4-14-16]]

^<<v4-14-16,16>>^ Porquanto o Senhor não podia introduzir este povo na terra que com juramento lhe prometera, por isso os matou no deserto.

[[v4-14-17]]

^<<v4-14-17,17>>^ Agora, pois, rogo-te que o poder do meu Senhor se engrandeça, segundo tens dito:

[[v4-14-18]]

^<<v4-14-18,18>>^ O Senhor é tardio em irar-se, e grande em misericórdia; perdoa a iniqüidade e a transgressão; ao culpado não tem por inocente, mas visita a iniqüidade dos pais nos filhos até a terceira e a quarta geração.

[[v4-14-19]]

^<<v4-14-19,19>>^ Perdoa, rogo-te, a iniqüidade deste povo, segundo a tua grande misericórdia, como o tens perdoado desde o Egito até, aqui.

[[v4-14-20]]

^<<v4-14-20,20>>^ Disse-lhe o Senhor: Conforme a tua palavra lhe perdoei;

[[v4-14-21]]

^<<v4-14-21,21>>^ tão certo, porém, como eu vivo, e como a glória do Senhor encherá toda a terra,

[[v4-14-22]]

^<<v4-14-22,22>>^ nenhum de todos os homens que viram a minha glória e os sinais que fiz no Egito e no deserto, e todavia me tentaram estas dez vezes, não obedecendo à minha voz,

[[v4-14-23]]

^<<v4-14-23,23>>^ nenhum deles verá a terra que com juramento prometi o seus pais; nenhum daqueles que me desprezaram a verá.

[[v4-14-24]]

^<<v4-14-24,24>>^ Mas o meu servo Calebe, porque nele houve outro espírito, e porque perseverou em seguir-me, eu o introduzirei na terra em que entrou, e a sua posteridade a possuirá.

[[v4-14-25]]

^<<v4-14-25,25>>^ Ora, os amalequitas e os cananeus habitam no vale; tornai-vos amanhã, e caminhai para o deserto em direção ao Mar Vermelho.

[[v4-14-26]]

^<<v4-14-26,26>>^ Depois disse o Senhor a Moisés e Arão:

[[v4-14-27]]

^<<v4-14-27,27>>^ Até quando sofrerei esta má congregação, que murmura contra mim? tenho ouvido as murmurações dos filhos de Israel, que eles fazem contra mim.

[[v4-14-28]]

^<<v4-14-28,28>>^ Dize-lhes: Pela minha vida, diz o Senhor, certamente conforme o que vos ouvi falar, assim vos hei de fazer:

[[v4-14-29]]

^<<v4-14-29,29>>^ neste deserto cairão os vossos cadáveres; nenhum de todos vós que fostes contados, segundo toda a vossa conta, de vinte anos para cima, que contra mim murmurastes,

[[v4-14-30]]

^<<v4-14-30,30>>^ certamente nenhum de vós entrará na terra a respeito da qual jurei que vos faria habitar nela, salvo Calebe, filho de Jefoné, e Josué, filho de Num.

[[v4-14-31]]

^<<v4-14-31,31>>^ Mas aos vossos pequeninos, dos quais dissestes que seriam por presa, a estes introduzirei na terra, e eles conhecerão a terra que vós rejeitastes.

[[v4-14-32]]

^<<v4-14-32,32>>^ Quanto a vós, porém, os vossos cadáveres cairão neste deserto;

[[v4-14-33]]

^<<v4-14-33,33>>^ e vossos filhos serão pastores no deserto quarenta anos, e levarão sobre si as vossas infidelidades, até que os vossos cadáveres se consumam neste deserto.

[[v4-14-34]]

^<<v4-14-34,34>>^ Segundo o número dos dias em que espiastes a terra, a saber, quarenta dias, levareis sobre vós as vossas iniqüidades por quarenta anos, um ano por um dia, e conhecereis a minha oposição.

[[v4-14-35]]

^<<v4-14-35,35>>^ Eu, o Senhor, tenho falado; certamente assim o farei a toda esta má congregação, aos que se sublevaram contra mim; neste deserto se consumirão, e aqui morrerão.

[[v4-14-36]]

^<<v4-14-36,36>>^ Ora, quanto aos homens que Moisés mandara a espiar a terra e que, voltando, fizeram murmurar toda a congregação contra ele, infamando a terra,

[[v4-14-37]]

^<<v4-14-37,37>>^ aqueles mesmos homens que infamaram a terra morreram de praga perante o Senhor.

[[v4-14-38]]

^<<v4-14-38,38>>^ Mas Josué, filho de Num, e Calebe, filho de Jefoné, que eram dos homens que foram espiar a terra, ficaram com vida.

[[v4-14-39]]

^<<v4-14-39,39>>^ Então Moisés falou estas palavras a todos os filhos de Israel, pelo que o povo se entristeceu muito.

[[v4-14-40]]

^<<v4-14-40,40>>^ Eles, pois, levantando-se de manhã cedo, subiram ao cume do monte, e disseram: Eis-nos aqui; subiremos ao lugar que o Senhor tem dito; porquanto havemos pecado.

[[v4-14-41]]

^<<v4-14-41,41>>^ Respondeu Moisés: Ora, por que transgredis o mandado do Senhor, visto que isso não prosperará?

[[v4-14-42]]

^<<v4-14-42,42>>^ Não subais, pois o Senhor não está no meio de vós; para que não sejais feridos diante dos vossos inimigos.

[[v4-14-43]]

^<<v4-14-43,43>>^ Porque os amalequitas e os cananeus estão ali diante da vossa face, e caireis à espada; pois, porquanto vos desviastes do Senhor, o Senhor não estará convosco.

[[v4-14-44]]

^<<v4-14-44,44>>^ Contudo, temerariamente subiram eles ao cume do monte; mas a arca do pacto do Senhor, e Moisés, não se apartaram do arraial.

[[v4-14-45]]

^<<v4-14-45,45>>^ Então desceram os amalequitas e os cananeus, que habitavam na montanha, e os feriram, derrotando-os até Horma.

'''

xref:004-numeros/004-numeros-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numeros/004-numeros-015.adoc#v4-15-0[Próximo Capítulo &#62;]