include::./index.adoc[]

[[v11-11-0]]
=== 1 Reis, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-11-1]]

^<<v11-11-1,1>>^ Ora, o rei Salomão amou muitas mulheres estrangeiras, além da filha de Faraó: moabitas, amonitas, edomitas, sidônias e heteias,

[[v11-11-2]]

^<<v11-11-2,2>>^ das nações de que o Senhor dissera aos filhos de Israel: Não ireis para elas, nem elas virão para vós; doutra maneira perverterão o vosso coração para seguirdes os seus deuses. A estas se apegou Salomão, levado pelo amor.

[[v11-11-3]]

^<<v11-11-3,3>>^ Tinha ele setecentas mulheres, princesas, e trezentas concubinas; e suas mulheres lhe perverteram o coração.

[[v11-11-4]]

^<<v11-11-4,4>>^ Pois sucedeu que, no tempo da velhice de Salomão, suas mulheres lhe perverteram o coração para seguir outros deuses; e seu coração já não era perfeito para com o Senhor seu Deus, como fora o de Davi, seu pai;

[[v11-11-5]]

^<<v11-11-5,5>>^ Salomão seguiu a Astarete, deusa dos sidônios, e a Milcom, abominação dos amonitas.

[[v11-11-6]]

^<<v11-11-6,6>>^ Assim fez Salomão o que era mau aos olhos do Senhor, e não perseverou em seguir, como fizera Davi, seu pai.

[[v11-11-7]]

^<<v11-11-7,7>>^ Nesse tempo edificou Salomão um alto a Quemós, abominação dos moabitas, sobre e monte que está diante de Jerusalém, e a Moleque, abominação dos amonitas.

[[v11-11-8]]

^<<v11-11-8,8>>^ E assim fez para todas as suas mulheres estrangeiras, as quais queimavam incenso e ofereciam sacrifícios a seus deuses.

[[v11-11-9]]

^<<v11-11-9,9>>^ Pelo que o Senhor se indignou contra Salomão, porquanto e seu coração se desviara do Senhor Deus de Israel, o qual duas vezes lhe aparecera,

[[v11-11-10]]

^<<v11-11-10,10>>^ e lhe ordenara expressamente que não seguisse a outros deuses. Ele, porém, não guardou o que o Senhor lhe ordenara.

[[v11-11-11]]

^<<v11-11-11,11>>^ Disse, pois, o Senhor a Salomão: Porquanto houve isto em ti, que não guardaste a meu pacto e os meus estatutos que te ordenei, certamente rasgarei de ti este reino, e o darei a teu servo.

[[v11-11-12]]

^<<v11-11-12,12>>^ Contudo não o farei nos teus dias, por amor de Davi, teu pai; da mão de teu filho o rasgarei.

[[v11-11-13]]

^<<v11-11-13,13>>^ Todavia não rasgarei o reino todo; mas uma tribo darei a teu filho, por amor de meu servo Davi, e por amor de Jerusalém, que escolhi.

[[v11-11-14]]

^<<v11-11-14,14>>^ O Senhor levantou contra Salomão um adversário, Hadade, o edomeu; o qual era da estirpe real de Edom.

[[v11-11-15]]

^<<v11-11-15,15>>^ Porque sucedeu que, quando Davi esteve em guerra contra Edom, tendo Jeabe, o chefe do exército, subido a enterrar os mortos, e ferido a todo varão em Edom

[[v11-11-16]]

^<<v11-11-16,16>>^ &#123;porque Joabe ficou ali seis meses com todo o Israel, até que destruiu a todo varão em Edom&#125;,

[[v11-11-17]]

^<<v11-11-17,17>>^ Hadade, que era ainda menino, fugiu para o Egito com alguns edemeus, servos de seu pai.

[[v11-11-18]]

^<<v11-11-18,18>>^ Levantando-se, pois, de Midiã, foram a Parã; e tomando consigo homens de Parã, foram ao Egito ter com Faraó, rei do Egito, o qual deu casa a Hadade, proveu-lhe a subsistência, e lhe deu terras.

[[v11-11-19]]

^<<v11-11-19,19>>^ E Hadade caiu tanto em graça a Faraó, que este lhe deu por mulher a irmã de sua mulher, a irmã da rainha Tafnes.

[[v11-11-20]]

^<<v11-11-20,20>>^ Ora, desta irmã de Tafnes nasceu a Hadade seu filho Genubate, a qual Tafnes criou na casa de Faraó, onde Genubate esteve entre os filhos de rei.

[[v11-11-21]]

^<<v11-11-21,21>>^ Ouvindo, pois, Hadade no Egito que Davi adormecera com seus pais, e que Jeabe, chefe do exército, era morto, disse o Faraó: Deixa-me ir, para que eu volte à minha terra.

[[v11-11-22]]

^<<v11-11-22,22>>^ Perguntou-lhe Faraó: Que te falta em minha companhia, que procuras partir para a tua terra? Respondeu ele: Nada; todavia, peço que me deixes ir.

[[v11-11-23]]

^<<v11-11-23,23>>^ Deus levantou contra Salomão ainda outro adversário, Rezom, filho de Eliadá, que tinha fugido de seu senhor Hadadézer, rei de Zobá.

[[v11-11-24]]

^<<v11-11-24,24>>^ Pois ele ajuntara a si homens, e se fizera capitão de uma tropa, quando Davi matou os de Zebá; e, indo-se para Damasco, habitaram ali; e fizeram-no rei em Damasco.

[[v11-11-25]]

^<<v11-11-25,25>>^ E foi adversário de Israel por todos os dias de Salomão, e isto além do mal que Hadade fazia; detestava a Israel, e reinava sobre a Síria.

[[v11-11-26]]

^<<v11-11-26,26>>^ Também Jeroboão, filho de Nebate, efrateu de Zeredá, servo de Salomão, cuja mãe era viúva, por nome Zeruá, levantou a mão contra o rei.

[[v11-11-27]]

^<<v11-11-27,27>>^ E esta foi a causa por que levantou a mão contra o rei: Salomão tinha edificado a Milo, e cerrado a brecha da cidade de Davi, seu pai.

[[v11-11-28]]

^<<v11-11-28,28>>^ Ora, Jeroboão era homem forte e valente; e vendo Salomão que este mancebo era laborioso, colocou-o sobre toda a carga imposta à casa de José.

[[v11-11-29]]

^<<v11-11-29,29>>^ E sucedeu naquele tempo que, saindo Jeroboão de Jerusalém, o profeta Aías, o silonita, o encontrou no caminho; este se tinha vestido duma capa nova; e os dois estavam sós no campo.

[[v11-11-30]]

^<<v11-11-30,30>>^ Então Aías pegou na capa nova que tinha sobre si, e a rasgou em doze pedaços.

[[v11-11-31]]

^<<v11-11-31,31>>^ E disse a Jeroboão: Toma estes dez pedaços para ti, porque assim diz e Senhor Deus de Israel: Eis que rasgarei o reino da mão de Salomão, e a ti darei dez tribos.

[[v11-11-32]]

^<<v11-11-32,32>>^ Ele, porém, terá uma tribo, por amor de Davi, meu servo, e por amor de Jerusalém, a cidade que escolhi dentre todas as tribos de Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ Porque me deixaram, e se encurvaram a Astarote, deusa dos sidônios, a Quemés, deus dos moabitas, e a Milcom, deus dos amonitas; e não andaram pelos meus caminhos, para fazerem o que parece reto aos meus olhos, e para guardarem os meus estatutos e os meus preceitos, como o fez Davi, seu pai.

[[v11-11-34]]

^<<v11-11-34,34>>^ Todavia não tomarei da sua mão o reino todo; mas deixá-lo-ei governar por todos os dias da sua vida, por amor de Davi, meu servo, a quem escolhi, o qual guardou os meus mandamentos e os meus estatutos.

[[v11-11-35]]

^<<v11-11-35,35>>^ Mas da mão de seu filho tomarei e reino e to darei a ti, isto é, as dez tribos.

[[v11-11-36]]

^<<v11-11-36,36>>^ Todavia a seu filho darei uma tribo, para que Davi, meu servo, sempre tenha uma lâmpada diante de mim em Jerusalém, a cidade que escolhi para ali pôr o meu nome.

[[v11-11-37]]

^<<v11-11-37,37>>^ Então te tomarei, e reinarás sobre tudo o que desejar a tua alma, e serás rei sobre Israel.

[[v11-11-38]]

^<<v11-11-38,38>>^ E há de ser que, se ouvires tudo o que eu te ordenar, e andares pelos meus caminhos, e fizeres o que é reto aos meus olhos, guardando os meus estatutos e os meus mandamentos, como o fez Davi, meu servo, eu serei contigo, e te edificarei uma casa firme, como o fiz para Davi, e te darei Israel.

[[v11-11-39]]

^<<v11-11-39,39>>^ E por isso afligirei a descendência de Davi, todavia não para sempre.

[[v11-11-40]]

^<<v11-11-40,40>>^ Pelo que Salomão procurou matar Jeroboão; porém este se levantou, e fugiu para o Egito, a ter com Sisaque, rei de Egito, onde esteve até a morte de Salomão.

[[v11-11-41]]

^<<v11-11-41,41>>^ Quanto ao restante dos atos de Salomão, e a tudo o que ele fez, e à sua sabedoria, porventura não está escrito no livro dos atos de Salomão?

[[v11-11-42]]

^<<v11-11-42,42>>^ O tempo que Salomão reinou em Jerusalém sobre todo o Israel foi quarenta anos.

[[v11-11-43]]

^<<v11-11-43,43>>^ E Salomão dormiu com seus pais, e foi sepultado na cidade de Davi, seu pai; e Roboão, seu filho, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[Próximo Capítulo &#62;]