include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquele tempo adoeceu Abias, filho de Jeroboão.

[[v11-14-2]]

^<<v11-14-2,2>>^ E disse Jeroboão a sua mulher: Levanta-te, e disfarça-te, para que não conheçam que és mulher de Jeroboão, e vai a Siló. Eis que lá está o profeta Aías, o qual falou acerca de mim que eu seria rei sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leva contigo dez pães, alguns bolos e uma botija de mel, e vai ter com ele; ele te declarará o que há de suceder a este menino.

[[v11-14-4]]

^<<v11-14-4,4>>^ Assim, pois, fez a mulher de Jeroboão; e, levantando-se, foi a Siló, e entrou na casa de Aías. Este já não podia ver, pois seus olhos haviam cegado por causa da velhice.

[[v11-14-5]]

^<<v11-14-5,5>>^ O Senhor, porém, dissera a Aías: Eis que a mulher de Jeroboão vem consultar-te sobre seu filho, que está doente. Assim e assim lhe falarás; porque há de ser que, entrando ela, fingirá ser outra.

[[v11-14-6]]

^<<v11-14-6,6>>^ Sucedeu que, ouvindo Aías o ruído de seus pés, ao entrar ela pela porta, disse: Entra, mulher de Jeroboão; por que te disfarças assim? Pois eu sou enviado a ti com duras novas.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vai, dize a Jeroboão: Assim diz o Senhor Deus de Israel: Porquanto te exaltei do meio do povo, e te constituí príncipe sobre o meu povo de Israel,

[[v11-14-8]]

^<<v11-14-8,8>>^ e rasguei o reino da casa de Davi, e o dei a ti; todavia não tens sido como o meu servo Davi, que guardou os meus mandamentos e que me seguiu de todo o coração para fazer somente o que era reto aos meus olhos;

[[v11-14-9]]

^<<v11-14-9,9>>^ mas tens praticado o mal, pior do que todos os que foram antes de ti, e foste fizeste para ti outros deuses e imagens de fundição, para provocar-me à ira, e me lançaste para trás das tuas costas;

[[v11-14-10]]

^<<v11-14-10,10>>^ portanto, eis que trarei o mal sobre a casa de Jeroboão, e exterminarei de Jeroboão todo homem, escravo ou livre, em Israel, e lançarei fora os remanescentes da casa de Jeroboão, como se lança fora o esterco, até que de todo se acabe.

[[v11-14-11]]

^<<v11-14-11,11>>^ Quem morrer a Jeroboão na cidade, comê-lo-ão os cães; e o que lhe morrer no campo, comê-lo-ão as aves do céu; porque o Senhor o disse.

[[v11-14-12]]

^<<v11-14-12,12>>^ Levanta-te, pois, e vai-te para tua casa; ao entrarem os teus pés na cidade, o menino morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ E todo o Israel o pranteará, e o sepultará; porque de Jeroboão só este entrará em sepultura, porquanto, dos da casa de Jeroboão, só nele se achou alguma coisa boa para com o Senhor Deus de Israel.

[[v11-14-14]]

^<<v11-14-14,14>>^ O Senhor, porém, levantará para si um rei sobre Israel, que destruirá a casa de Jeroboão. Este é o dia! Sim desde agora.

[[v11-14-15]]

^<<v11-14-15,15>>^ Ferirá o Senhor a Israel, como se agita a cana nas águas; e arrancará a Israel desta boa terra que tinha dado a seus pais, e o espalhará para além do rio, porquanto fizeram os seus aserins, provocando o Senhor à ira.

[[v11-14-16]]

^<<v11-14-16,16>>^ E entregará Israel por causa dos pecados de Jeroboão, o qual pecou e fez pecar a Israel.

[[v11-14-17]]

^<<v11-14-17,17>>^ Então a mulher de Jeroboão se levantou e partiu, e veio para Tirza; chegando ela ao limiar da casa, o menino morreu.

[[v11-14-18]]

^<<v11-14-18,18>>^ E todo o Israel o sepultou e o pranteou, conforme a palavra do Senhor, que ele falara por intermédio de seu servo Aías, o profeta.

[[v11-14-19]]

^<<v11-14-19,19>>^ Quanto ao restante dos atos de Jeroboão, como guerreou, e como reinou, eis que está escrito no livro das crônicas dos reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ E o tempo que Jeroboão reinou foi vinte e dois anos. E dormiu com seus pais; e Nadabe, seu filho, reinou em seu lugar.

[[v11-14-21]]

^<<v11-14-21,21>>^ Reinou em Judá Roboão, filho de Salomão. Tinha quarenta e um anos quando começou a reinar, e reinou dezessete anos em Jerusalém, a cidade que o Senhor escolhera dentre todas as tribos de Israel para pôr ali o seu nome. E era o nome de sua mãe Naamá, a amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ E fez Judá o que era mau aos olhos do Senhor; e, com os seus pecados que cometeram, provocaram-no a zelos, mais do que o fizeram os seus pais.

[[v11-14-23]]

^<<v11-14-23,23>>^ Porque também eles edificaram altos, e colunas, e aserins sobre todo alto outeiro e debaixo de toda árvore frondosa;

[[v11-14-24]]

^<<v11-14-24,24>>^ e havia também sodomitas na terra: fizeram conforme todas as abominações dos povos que o Senhor tinha expulsado de diante dos filhos de Israel.

[[v11-14-25]]

^<<v11-14-25,25>>^ Ora, sucedeu que, no quinto ano do rei Roboão, Sisaque, rei do Egito, subiu contra Jerusalém,

[[v11-14-26]]

^<<v11-14-26,26>>^ e tomou os tesouros da casa de Senhor e os tesouros da casa do rei; levou tudo. Também tomou todos os escudos de ouro que Salomão tinha feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Em lugar deles, fez o rei Roboão escudos de bronze, e os entregou nas mãos dos capitães da guarda, que guardavam a porta da casa do rei.

[[v11-14-28]]

^<<v11-14-28,28>>^ E todas as vezes que o rei entrava na casa do Senhor os da guarda levavam os escudos, e depois tornavam a pô-los na câmara da guarda.

[[v11-14-29]]

^<<v11-14-29,29>>^ Quanto ao restante dos atos de Reboão, e a tudo quanto fez, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v11-14-30]]

^<<v11-14-30,30>>^ Houve guerra continuamente entre Roboão e Jeroboão.

[[v11-14-31]]

^<<v11-14-31,31>>^ E Roboão dormiu com seus pais, e foi sepultado com eles na cidade de Davi. Era o nome de sua mãe Naamá, a amonita. E Abião, seu filho, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]