include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-13-1]]

^<<v11-13-1,1>>^ Eis que, por ordem do Senhor, veio de Judá a Betel um homem de Deus; e Jeroboão estava junto ao altar, para queimar incenso.

[[v11-13-2]]

^<<v11-13-2,2>>^ E o homem clamou contra o altar, por ordem do Senhor, dizendo: Altar, altar! assim diz o Senhor: Eis que um filho nascerá à casa de Davi, cujo nome será Josias; e qual sacrificará sobre ti os sacerdotes dos altos que sobre ti queimam incenso, e ossos de homens se queimarão sobre ti.

[[v11-13-3]]

^<<v11-13-3,3>>^ E deu naquele mesmo dia um sinal, dizendo: Este é o sinal de que o Senhor falou; Eis que o altar se fenderá, e a cinza que está sobre ele se derramará.

[[v11-13-4]]

^<<v11-13-4,4>>^ Sucedeu pois que, ouvindo o rei Jeroboão a palavra que o homem de Deus clamara contra o altar de Betel, estendeu a mão de sobre o altar, dizendo: Pegai-o! E logo, a mão que estendera contra ele secou-se, de modo que não podia tornar a trazê-la a si.

[[v11-13-5]]

^<<v11-13-5,5>>^ E o altar se fendeu, e a cinza se derramou do altar, conforme o sinal que o homem de Deus, por ordem do Senhor, havia dado.

[[v11-13-6]]

^<<v11-13-6,6>>^ Então respondeu o rei, e disse ao homem de Deus: Suplica ao Senhor teu Deus, e roga por mim, para que se me restitua a minha mão. Pelo que o homem de Deus suplicou ao Senhor, e a mão do rei se lhe restituiu, e ficou como dantes.

[[v11-13-7]]

^<<v11-13-7,7>>^ Disse então o rei ao homem de Deus: Vem comigo a minha casa, e conforta-te, e dar-te-ei uma recompensa.

[[v11-13-8]]

^<<v11-13-8,8>>^ Mas o homem de Deus respondeu ao rei: Ainda que me desses metade da tua casa, não iria contigo, nem comeria pão, nem beberia água neste lugar.

[[v11-13-9]]

^<<v11-13-9,9>>^ Porque assim me ordenou o Senhor pela sua palavra, dizendo: Não comas pão, nem bebas água, nem voltes pelo caminho por onde vieste.

[[v11-13-10]]

^<<v11-13-10,10>>^ Ele, pois, se foi por outro caminho, e não voltou pelo caminho por onde viera a Betel.

[[v11-13-11]]

^<<v11-13-11,11>>^ Ora, morava em Betel um velho profeta. Seus filhos vieram contar-lhe tudo o que o homem de Deus fizera aquele dia em Betel; e as palavras que ele dissera ao rei, contaram-nas também a seu pai.

[[v11-13-12]]

^<<v11-13-12,12>>^ Perguntou-lhes seu pai: Por que caminho se foi? pois seus filhos tinham visto o caminho por onde fora o homem de Deus que viera de Judá.

[[v11-13-13]]

^<<v11-13-13,13>>^ Então disse a seus filhos: Albardai-me o jumento. E albardaram-lhe o jumento, no qual ele montou.

[[v11-13-14]]

^<<v11-13-14,14>>^ E tendo ido após o homem de Deus, achou-o sentado debaixo de um carvalho, e perguntou-lhe: És tu o homem de Deus que vieste de Judá? Respondeu ele: Sou.

[[v11-13-15]]

^<<v11-13-15,15>>^ Então lhe disse: Vem comigo a casa, e come pão.

[[v11-13-16]]

^<<v11-13-16,16>>^ Mas ele tornou: Não posso voltar contigo, nem entrar em tua casa; nem tampouco comerei pão, nem beberei água contigo neste lugar;

[[v11-13-17]]

^<<v11-13-17,17>>^ porque me foi mandado pela palavra de Senhor: Ali não comas pão, nem bebas água, nem voltes pelo caminho por onde vieste.

[[v11-13-18]]

^<<v11-13-18,18>>^ Respondeu-lhe o outro: Eu também sou profeta como tu, e um anjo me falou por ordem do Senhor, dizendo: Faze-o voltar contigo a tua casa, para que coma pão e beba água. Mas mentia-lhe.

[[v11-13-19]]

^<<v11-13-19,19>>^ Assim o homem voltou com ele, comeu pão em sua casa, e bebeu água.

[[v11-13-20]]

^<<v11-13-20,20>>^ Estando eles à mesa, a palavra do Senhor veio ao profeta que o tinha feito voltar;

[[v11-13-21]]

^<<v11-13-21,21>>^ e ele clamou ao homem de Deus que viera de Judá, dizendo: Assim diz o Senhor: Porquanto foste rebelde à ordem do Senhor, e não guardaste o mandamento que o Senhor teu Deus te mandara,

[[v11-13-22]]

^<<v11-13-22,22>>^ mas voltaste, e comeste pão e bebeste água no lugar de que te dissera: Não comas pão, nem bebas água; o teu cadáver não entrará no sepulcro de teus pais.

[[v11-13-23]]

^<<v11-13-23,23>>^ E, havendo eles comido e bebido, albardou o jumento para o profeta que fizera voltar.

[[v11-13-24]]

^<<v11-13-24,24>>^ Este, pois, se foi, e um leão o encontrou no caminho, e o matou; o seu cadáver ficou estendido no caminho, e o jumento estava parado junto a ele, e também o leão estava junto ao cadáver.

[[v11-13-25]]

^<<v11-13-25,25>>^ E, passando por ali alguns homens, viram o cadáver estendido no caminho, e o leão ao lado dele. Foram, pois, e o disseram na cidade onde o velho profeta habitava.

[[v11-13-26]]

^<<v11-13-26,26>>^ Quando o profeta que o fizera voltar do caminho ouviu isto, disse: É o homem de Deus, que foi rebelde à palavra do Senhor; por isso o Senhor o entregou ao leão, que o despedaçou e matou, segundo a palavra que o Senhor lhe dissera.

[[v11-13-27]]

^<<v11-13-27,27>>^ E disse a seus filhos: Albardai-me e jumento. Eles lho albardaram.

[[v11-13-28]]

^<<v11-13-28,28>>^ Então foi e achou o cadáver estendido no caminho, e o jumento e o leão, que estavam parados junto ao cadáver; o leão não o havia devorado, nem havia despedaçado o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ Então e profeta levantou o cadáver do homem de Deus e, pondo-o em cima do jumento, levou-o consigo; assim veio o velho profeta à cidade para o chorar e o sepultar.

[[v11-13-30]]

^<<v11-13-30,30>>^ E colocou o cadáver no seu próprio sepulcro; e prantearam-no, dizendo: Ah, irmão meu!

[[v11-13-31]]

^<<v11-13-31,31>>^ Depois de o haver sepultado, disse a seus filhos. Quando eu morrer, sepultai-me no sepulcro em que o homem de Deus está sepultado; ponde os meus ossos junto aos ossos dele.

[[v11-13-32]]

^<<v11-13-32,32>>^ Porque certamente se cumprirá o que, pela palavra de Senhor, clamou, contra o altar que está em Betel, como também contra todas as casas dos altos que estão nas cidades de Samária.

[[v11-13-33]]

^<<v11-13-33,33>>^ Nem depois destas coisas deixou Jeroboão e seu mau caminho, porém tornou a fazer dentre todo o povo sacerdotes dos lugares altos; e a qualquer que o queria consagrava sacerdote dos lugares altos.

[[v11-13-34]]

^<<v11-13-34,34>>^ E isso foi causa de pecado à casa de Jeroboão, para destruí-la e extingui-la da face da terra.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]