include::./index.adoc[]

[[v11-4-0]]
=== 1 Reis, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-4-1]]

^<<v11-4-1,1>>^ Assim foi Salomão rei sobre todo o Israel.

[[v11-4-2]]

^<<v11-4-2,2>>^ E estes eram os príncipes que tinha: Azarias, filho de Zadoque, era sacerdote;

[[v11-4-3]]

^<<v11-4-3,3>>^ Eliorefe e Aías, filhos de Sisa, secretários; Jeosafá, filho de Ailude, cronista;

[[v11-4-4]]

^<<v11-4-4,4>>^ Benaías, filho de Jeoiada, estava sobre o exército; Zadoque e Abiatar eram sacerdotes;

[[v11-4-5]]

^<<v11-4-5,5>>^ Azarias, filho de Natã, estava sobre os intendentes; Zabude, filho de Natã, era o oficial-mor, amigo do rei;

[[v11-4-6]]

^<<v11-4-6,6>>^ Aisar, o mordomo; e Adonirão, filho de Abda, estava sobre a gente de trabalhos forçados.

[[v11-4-7]]

^<<v11-4-7,7>>^ Salomão tinha doze intendentes sobre todo o Israel, que proviam de mantimentos ao rei e à sua casa; e cada um tinha que prover mantimentos para um mês no ano.

[[v11-4-8]]

^<<v11-4-8,8>>^ São estes os seus nomes: Ben-Hur, na região montanhosa de Efraim.

[[v11-4-9]]

^<<v11-4-9,9>>^ Ben-Dequer, em Macaz, Saalabim, Bete-Semes e Elom-Bete-Hanã;

[[v11-4-10]]

^<<v11-4-10,10>>^ Ben-Hesede, em Arubote; também este tinha Socó e toda a terra de Jefer;

[[v11-4-11]]

^<<v11-4-11,11>>^ Ben-Abinadabe, em toda a região alta de Dor; tinha este a Tafate, filha de Salomão, por mulher;

[[v11-4-12]]

^<<v11-4-12,12>>^ Baaná, filho de Ailude, em Taanaque e Megido, e em toda a Bete-Seã, que está junto a Zaretã, abaixo de Jizreel, desde Bete-Seã até Abel-Meolá, para além de Jocmeão;

[[v11-4-13]]

^<<v11-4-13,13>>^ o filho de Geber, em Ramote-Gileade; tinha este as aldeias de Jair, filho de Manassés, as quais estão em Gileade; também tinha a região de Argobe, o qual está em Basã, sessenta grandes cidades com muros e ferrolhos de bronze:

[[v11-4-14]]

^<<v11-4-14,14>>^ Ainadabe, filho de Ido, em Maanaim;

[[v11-4-15]]

^<<v11-4-15,15>>^ Aimaaz, em Naftali; também este tomou a Basemate, filha de Salomão, por mulher;

[[v11-4-16]]

^<<v11-4-16,16>>^ Baaná, filho de Hasai, em Aser e em Alote;

[[v11-4-17]]

^<<v11-4-17,17>>^ Jeosafá, filho de Paruá, em Issacar;

[[v11-4-18]]

^<<v11-4-18,18>>^ Simei, filho de Elá, em Benjamim;

[[v11-4-19]]

^<<v11-4-19,19>>^ Geber, filho de Uri, na terra de Gileade, a terra de Siom, rei dos amorreus, e de Ogue, rei de Basã; havia um só intendente naquela terra.

[[v11-4-20]]

^<<v11-4-20,20>>^ Eram, pois, os de Judá e Israel numerosos, como a areia que está à beira do mar; e, comendo e bebendo, se alegravam.

[[v11-4-21]]

^<<v11-4-21,21>>^ E dominava Salomão sobre todos os reinos, desde o rio até a terra dos filisteus e até o termo do Egito; eles pagavam tributo, e serviram a Salomão todos os dias da sua vida.

[[v11-4-22]]

^<<v11-4-22,22>>^ O provimento diário de Salomão era de trinta coros de flor de farinha, e sessenta coros e farinha;

[[v11-4-23]]

^<<v11-4-23,23>>^ dez bois cevados, vinte bois de pasto e cem ovelhas, afora os veados, gazelas, cabras montesas e aves cevadas.

[[v11-4-24]]

^<<v11-4-24,24>>^ Pois dominava ele sobre toda a região e sobre todos os reis daquém do rio, desde Tifsa até Gaza; e tinha paz por todos os lados em redor.

[[v11-4-25]]

^<<v11-4-25,25>>^ Judá e Israel habitavam seguros, desde Dã até Berseba, cada um debaixo da sua videira, e debaixo da sua figueira, por todos os dias de Salomão.

[[v11-4-26]]

^<<v11-4-26,26>>^ Salomão tinha também quarenta mil manjedouras para os cavalos dos seus carros, e doze mil cavaleiros.

[[v11-4-27]]

^<<v11-4-27,27>>^ Aqueles intendentes, pois, cada um no seu mês, proviam de mantimentos o rei Salomão e todos quantos se chegavam à sua mesa; coisa nenhuma deixavam faltar.

[[v11-4-28]]

^<<v11-4-28,28>>^ Também traziam, cada um segundo seu cargo, a cevada e a palha para os cavalos e os ginetes, para o lugar em que estivessem.

[[v11-4-29]]

^<<v11-4-29,29>>^ Ora, Deus deu a Salomão sabedoria, e muitíssimo entendimento, e conhecimentos múltiplos, como a areia que está na praia do mar.

[[v11-4-30]]

^<<v11-4-30,30>>^ A sabedoria de Salomão era maior do que a de todos os do Oriente e do que toda a sabedoria dos egípcios.

[[v11-4-31]]

^<<v11-4-31,31>>^ Era ele ainda mais sábio do que todos os homens, mais sábio do que Etã, o ezraíta, e do que Hemã, Calcol e Darda, filhos de Maol; e a sua fama correu por todas as nações em redor.

[[v11-4-32]]

^<<v11-4-32,32>>^ Proferiu ele três mil provérbios, e foram os seus cânticos mil e cinco.

[[v11-4-33]]

^<<v11-4-33,33>>^ Dissertou a respeito das árvores, desde o cedro que está no Líbano até o hissopo que brota da parede; também dissertou sobre os animais, as aves, os répteis e os peixes.

[[v11-4-34]]

^<<v11-4-34,34>>^ De todos os povos vinha gente para ouvir a sabedoria de Salomão, e da parte de todos os reis da terra que tinham ouvido da sua sabedoria.

'''

xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[&#60; Capítulo Anterior] | <<v11-4-0,Topo>> | xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[Próximo Capítulo &#62;]