include::./index.adoc[]

[[v11-16-0]]
=== 1 Reis, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-16-1]]

^<<v11-16-1,1>>^ Então veio a palavra do Senhor a Jeú, filho de Hanâni, contra Baasa, dizendo:

[[v11-16-2]]

^<<v11-16-2,2>>^ Porquanto te exaltei do pó, e te constituí chefe sobre o meu povo Israel, e tu tens andado no caminho de Jeroboão, e tens feito o meu povo Israel pecar, provocando-me à ira com os seus pecados,

[[v11-16-3]]

^<<v11-16-3,3>>^ eis que exterminarei os descendentes de Baasa, e os descendentes da casa dele; sim, tornarei a tua casa como a casa de Jeroboão, filho de Nebate.

[[v11-16-4]]

^<<v11-16-4,4>>^ Quem morrer a Baasa na cidade, comê-lo-ão os cães; e o que lhe morrer no campo, comê-lo-ão as aves do céu.

[[v11-16-5]]

^<<v11-16-5,5>>^ Quanto ao restante dos atos de Baasa, e ao que fez, e ao seu poder, porventura não estão escritos no livro das crônicas dos reis de Israel?

[[v11-16-6]]

^<<v11-16-6,6>>^ E Baasa dormiu com seus pais, e foi sepultado em Tirza. Então Elá, seu filho, reinou em seu lugar.

[[v11-16-7]]

^<<v11-16-7,7>>^ Assim veio também a palavra do Senhor, por intermédio do profeta Jeú, filho de Hanâni, contra Baasa e contra a casa dele, não somente por causa de todo o mal que fizera aos olhos do Senhor, de modo a provocá-lo à ira com a obra de suas mãos, tornando-se como a casa de Jeroboão, mas também porque exterminara a casa de Jeroboão.

[[v11-16-8]]

^<<v11-16-8,8>>^ No ano vinte e seis de Asa, rei de Judá, Elá, filho de Baasa, começou a reinar em Tirza sobre Israel, e reinou dois anos.

[[v11-16-9]]

^<<v11-16-9,9>>^ E Zinri, seu servo, chefe de metade dos carros, conspirou contra ele. Ora, Elá achava-se em Tirza bebendo e embriagando-se em casa de Arza, que era o seu mordomo em Tirza.

[[v11-16-10]]

^<<v11-16-10,10>>^ Entrou, pois, Zinri e o feriu, e o matou, no ano vigésimo sétimo de Asa, rei de Judá, e reinou em seu lugar.

[[v11-16-11]]

^<<v11-16-11,11>>^ Quando ele começou a reinar, logo que se assentou no seu trono, feriu toda a casa de Baasa; não lhe deixou homem algum, nem de seus parentes, nem de seus amigos.

[[v11-16-12]]

^<<v11-16-12,12>>^ Assim destruiu Zinri toda a casa de Baasa, conforme a palavra do Senhor, que ele falara contra Baasa por intermédio do profeta Jeú,

[[v11-16-13]]

^<<v11-16-13,13>>^ por causa de todos os pecados de Baasa, e dos pecados de Elá, seu filho, com que pecaram, e com que fizeram Israel pecar, provocando à ira, com as suas vaidades, o Senhor Deus de Israel.

[[v11-16-14]]

^<<v11-16-14,14>>^ Quanto ao restante dos atos de Elá, e a tudo quanto fez, porventura não estão escritos no livro das crônicas dos reis de Israel?

[[v11-16-15]]

^<<v11-16-15,15>>^ No ano vigésimo sétimo de Asa, rei de Judá, reinou Zinri sete dias em Tirza. Estava o povo acampado contra Gibetom, que pertencia aos filisteus.

[[v11-16-16]]

^<<v11-16-16,16>>^ E o povo que estava acampado ouviu dizer: Zinri conspirou, e matou o rei; pelo que no mesmo dia, no arraial, todo o Israel constituiu rei sobre Israel a Onri, chefe do exercito.

[[v11-16-17]]

^<<v11-16-17,17>>^ Então Onri subiu de Gibetom com todo o Israel, e cercaram Tirza.

[[v11-16-18]]

^<<v11-16-18,18>>^ Vendo Zinri que a cidade era tomada, entrou no castelo da casa do rei, e queimou-a sobre si; e morreu,

[[v11-16-19]]

^<<v11-16-19,19>>^ por causa dos pecados que cometera, fazendo o que era mau aos olhos do Senhor, andando no caminho de Jeroboão, e no pecado que este cometera, fazendo Israel pecar.

[[v11-16-20]]

^<<v11-16-20,20>>^ Quanto ao restante dos atos de Zinri, e à conspiração que fez, porventura não estão escritos no livro das crônicas dos reis de Israel?

[[v11-16-21]]

^<<v11-16-21,21>>^ Então o povo de Israel se dividiu em dois partidos: metade do povo seguia a Tíbni, filho de Ginate, para fazê-lo rei, e a outra metade seguia a Onri.

[[v11-16-22]]

^<<v11-16-22,22>>^ Mas o povo que seguia a Onri prevaleceu contra o que seguia a Tíbni, filho de Ginate; de sorte que Tíbni morreu, e Onri reinou.

[[v11-16-23]]

^<<v11-16-23,23>>^ No trigésimo primeiro ano de Asa, rei de Judá, Onri começou a reinar sobre Israel, e reinou doze anos. Reinou seis anos em Tirza.

[[v11-16-24]]

^<<v11-16-24,24>>^ E de Semer comprou o outeiro de Samária por dois talentos de prata, e edificou nele; e chamou a cidade que edificou Samária, do nome de Semer, dono do outeiro.

[[v11-16-25]]

^<<v11-16-25,25>>^ E fez Onri o que era mau aos olhos do Senhor; pior mesmo do que todos os que o antecederam.

[[v11-16-26]]

^<<v11-16-26,26>>^ Pois ele andou em todos os caminhos de Jeroboão, filho de Nebate, como também nos pecados com que este fizera Israel pecar, provocando à ira, com as suas vaidades, o Senhor Deus de Israel.

[[v11-16-27]]

^<<v11-16-27,27>>^ Quanto ao restante dos atos que Onri fez, e ao poder que manifestou, porventura não estão escritos no livro das crônicas dos reis de Israel?

[[v11-16-28]]

^<<v11-16-28,28>>^ Onri dormiu com seus pais, e foi sepultado em Samária. E Acabe, seu filho, reinou em seu lugar.

[[v11-16-29]]

^<<v11-16-29,29>>^ No trigésimo oitavo ano de Asa, rei de Judá, começou Acabe, filho de Onri, a reinar sobre Israel; e reinou sobre Israel em Samária vinte e dois anos.

[[v11-16-30]]

^<<v11-16-30,30>>^ E fez Acabe, filho de Onri, o que era mau aos olhos do Senhor, mais do que todos os que o antecederam.

[[v11-16-31]]

^<<v11-16-31,31>>^ E, como se fosse pouco andar nos pecados de Jeroboão, filho de Nebate, ainda tomou por mulher a Jezabel, filha de Etbaal, rei dos sidônios, e foi e serviu a Baal, e o adorou;

[[v11-16-32]]

^<<v11-16-32,32>>^ e levantou um altar a Baal na casa de Baal que ele edificara em Samária;

[[v11-16-33]]

^<<v11-16-33,33>>^ também fez uma asera. De maneira que Acabe fez muito mais para provocar à ira o Senhor Deus de Israel do que todos os reis de Israel que o antecederam.

[[v11-16-34]]

^<<v11-16-34,34>>^ Em seus dias Hiel, o betelita, edificou Jericó. Quando lançou os seus alicerces, morreu-lhe Abirão, seu primogênito; e quando colocou as suas portas, morreu-lhe Segube, seu filho mais moço; conforme a palavra do Senhor, que ele falara por intermédio de Josué, filho de Num.

'''

xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[Próximo Capítulo &#62;]