include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-20-1]]

^<<v11-20-1,1>>^ Ora, Ben-Hadade, rei da Síria, ajuntou todo o seu exército; e havia com ele trinta e dois reis, e cavalos e carros. Então subiu, cercou a Samária, e pelejou contra ela.

[[v11-20-2]]

^<<v11-20-2,2>>^ E enviou à cidade mensageiros a Acabe, rei de Israel, a dizer-lhe: Assim diz: Ben-Hadade:

[[v11-20-3]]

^<<v11-20-3,3>>^ A tua prata e o teu ouro são meus; e também, das tuas mulheres e dos teus filhos, os melhores são meus.

[[v11-20-4]]

^<<v11-20-4,4>>^ Ao que respondeu o rei de Israel, dizendo: Conforme a tua palavra, ó rei meu senhor, sou teu, com tudo quanto tenho.

[[v11-20-5]]

^<<v11-20-5,5>>^ Tornaram a vir os mensageiros, e disseram: Assim fala Ben-Hadade, dizendo: Enviei-te, na verdade, mensageiros que dissessem: Tu me hás de entregar a tua prata e o teu ouro, as tuas mulheres e os teus filhos;

[[v11-20-6]]

^<<v11-20-6,6>>^ todavia amanhã a estas horas te enviarei os meus servos, os quais esquadrinharão a tua casa, e as casas dos teus servos; e há de ser que tudo o que de precioso tiveres, eles tomarão consigo e o levarão.

[[v11-20-7]]

^<<v11-20-7,7>>^ Então o rei de Israel chamou todos os anciãos da terra, e disse: Notai agora, e vede como esse homem procura o mal; pois mandou pedir-me as minhas mulheres, os meus filhos, a minha prata e o meu ouro, e não os neguei.

[[v11-20-8]]

^<<v11-20-8,8>>^ Responderam-lhe todos os anciãos e todo o povo: Não lhe dês ouvidos, nem consintas.

[[v11-20-9]]

^<<v11-20-9,9>>^ Pelo que disse aos mensageiros de Ben-Hadade: Dizei ao rei, meu senhor: Tudo o que a princípio mandaste pedir a teu servo, farei; porém isto não posso fazer. Voltaram os mensageiros, e lhe levaram a resposta.

[[v11-20-10]]

^<<v11-20-10,10>>^ Tornou Ben-Hadade a enviar-lhe mensageiros, e disse: Assim me façam os deuses, e outro tanto, se o pó de Samária bastar para encher as mãos de todo o povo que me segue.

[[v11-20-11]]

^<<v11-20-11,11>>^ O rei de Israel, porém, respondeu: Dizei-lhe: Não se gabe quem se cinge das armas como aquele que as depõe.

[[v11-20-12]]

^<<v11-20-12,12>>^ E sucedeu que, ouvindo ele esta palavra, estando a beber com os reis nas tendas, disse aos seus servos: Ponde-vos em ordem. E eles se puseram em ordem contra a cidade.

[[v11-20-13]]

^<<v11-20-13,13>>^ E eis que um profeta, chegando-se a Acabe, rei de Israel, lhe disse: Assim diz o Senhor: Viste toda esta grande multidão eis que hoje te entregarei nas mãos, e saberás que eu sou o Senhor.

[[v11-20-14]]

^<<v11-20-14,14>>^ Perguntou Acabe: Por quem? Respondeu ele: Assim diz o Senhor: Pelos moços dos chefes das províncias. Ainda perguntou Acabe: Quem começará a peleja? Respondeu ele: Tu.

[[v11-20-15]]

^<<v11-20-15,15>>^ Então contou os moços dos chefes das províncias, e eram duzentos e trinta e dois; e depois deles contou todo o povo, a saber, todos os filhos de Israel, e eram sete mil.

[[v11-20-16]]

^<<v11-20-16,16>>^ Saíram, pois, ao meio-dia. Ben-Hadade, porém, estava bebendo e se embriagando nas tendas, com os reis, os trinta e dois reis que o ajudavam.

[[v11-20-17]]

^<<v11-20-17,17>>^ E os moços dos chefes das províncias saíram primeiro; e Ben-Hadade enviou espias, que lhe deram aviso, dizendo: Saíram de Samária uns homens.

[[v11-20-18]]

^<<v11-20-18,18>>^ Ao que ele disse: Quer venham eles tratar de paz, quer venham à peleja, tomai-os vivos.

[[v11-20-19]]

^<<v11-20-19,19>>^ Saíram, pois, da cidade os moços dos chefes das províncias, e o exército que os seguia.

[[v11-20-20]]

^<<v11-20-20,20>>^ E eles mataram cada um o seu adversário. Então os sírios fugiram, e Israel os perseguiu; mas Ben-Hadade, rei da Síria, escapou a cavalo, com alguns cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ E saindo o rei de Israel, destruiu os cavalos e os carros, e infligiu aos sírios grande derrota.

[[v11-20-22]]

^<<v11-20-22,22>>^ Então o profeta chegou-se ao rei de Israel e lhe disse: Vai, fortalece-te; atenta bem para o que hás de fazer; porque decorrido um ano, o rei da Síria subirá contra ti.

[[v11-20-23]]

^<<v11-20-23,23>>^ Os servos do rei da Síria lhe disseram: Seus deuses são deuses dos montes, por isso eles foram mais fortes do que nós; mas pelejemos com eles na planície, e por certo prevaleceremos contra eles.

[[v11-20-24]]

^<<v11-20-24,24>>^ Faze, pois, isto: tira os reis, cada um do seu lugar, e substitui-os por capitães;

[[v11-20-25]]

^<<v11-20-25,25>>^ arregimenta outro exército, igual ao exército que perdeste, cavalo por cavalo, e carro por carro; pelejemos com eles na planície, e por certo prevaleceremos contra eles. Ele deu ouvidos ao que disseram, e assim fez.

[[v11-20-26]]

^<<v11-20-26,26>>^ Passado um ano, Ben-Hadade arregimentou os sírios, e subiu a Afeque, para pelejar contra Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ Também os filhos de Israel foram arregimentados e, providos de víveres, marcharam contra eles. E os filhos de Israel acamparam-se defronte deles, como dois pequenos rebanhos de cabras; mas os sírios enchiam a terra.

[[v11-20-28]]

^<<v11-20-28,28>>^ Nisso chegou o homem de Deus, e disse ao rei de Israel: Assim diz o Senhor: Porquanto os sírios disseram: O Senhor é Deus dos montes, e não Deus dos vales, entregarei nas tuas mãos toda esta grande multidão, e saberás que eu sou o Senhor.

[[v11-20-29]]

^<<v11-20-29,29>>^ Assim, pois, estiveram acampados sete dias, uns defronte dos outros. Ao sétimo dia a peleja começou, e num só dia os filhos de Israel mataram dos sírios cem mil homens da infantaria.

[[v11-20-30]]

^<<v11-20-30,30>>^ E os restantes fugiram para Afeque, e entraram na cidade; e caiu o muro sobre vinte e sete mil homens que restavam. Ben-Hadade, porém, fugiu, e veio à cidade, onde se meteu numa câmara interior.

[[v11-20-31]]

^<<v11-20-31,31>>^ Disseram-lhe os seus servos: Eis que temos ouvido dizer que os reis da casa de Israel são reis clementes; ponhamos, pois, sacos aos lombos, e cordas aos pescoços, e saiamos ao rei de Israel; pode ser que ele te poupe a vida.

[[v11-20-32]]

^<<v11-20-32,32>>^ Então cingiram sacos aos lombos e cordas aos pescoços e, indo ter com o rei de Israel, disseram-lhe: Diz o teu servo Ben-Hadade: Deixa-me viver, rogo-te. Ao que disse Acabe: Pois ainda vive? É meu irmão.

[[v11-20-33]]

^<<v11-20-33,33>>^ Aqueles homens, tomando isto por bom presságio, apressaram-se em apanhar a sua palavra, e disseram: Ben-Hadade é teu irmão! Respondeu-lhes ele: Ide, trazei-me. Veio, pois, Ben-Hadade à presença de Acabe; e este o fez subir ao carro.

[[v11-20-34]]

^<<v11-20-34,34>>^ Então lhe disse Ben-Hadade: Eu te restituirei as cidades que meu pai tomou a teu pai; e farás para ti praças em Damasco, como meu pai as fez em Samária. E eu, respondeu Acabe, com esta aliança te deixarei ir. E fez com ele aliança e o deixou ir.

[[v11-20-35]]

^<<v11-20-35,35>>^ Ora, certo homem dentre os filhos dos profetas disse ao seu companheiro, pela palavra do Senhor: Fere-me, peço-te. Mas o homem recusou feri-lo.

[[v11-20-36]]

^<<v11-20-36,36>>^ Pelo que ele lhe disse: Porquanto não obedeceste à voz do Senhor, eis que, em te apartando de mim, um leão te matará. E logo que se apartou dele um leão o encontrou e o matou.

[[v11-20-37]]

^<<v11-20-37,37>>^ Depois o profeta encontrou outro homem, e disse-lhe: Fere-me, peço-te. E aquele homem deu nele e o feriu.

[[v11-20-38]]

^<<v11-20-38,38>>^ Então foi o profeta, pôs-se a esperar e rei no caminho, e disfarçou-se, cobrindo os olhos com o seu turbante.

[[v11-20-39]]

^<<v11-20-39,39>>^ E passando o rei, clamou ele ao rei, dizendo: Teu servo estava no meio da peleja; e eis que um homem, voltando-se, me trouxe um outro, e disse: Guarda-me este homem; se ele de qualquer maneira vier a faltar, a tua vida responderá pela vida dele, ou então pagarás um talento de prata.

[[v11-20-40]]

^<<v11-20-40,40>>^ E estando o teu servo ocupado de uma e de outra parte, eis que o homem desapareceu. Ao que lhe respondeu o rei de Israel: Esta é a tua sentença; tu mesmo a pronunciaste.

[[v11-20-41]]

^<<v11-20-41,41>>^ Então ele se apressou, e tirou o turbante de sobre os seus olhos; e o rei de Israel o reconheceu, que era um dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ E disse ele ao rei: Assim diz o Senhor: Porquanto deixaste escapar da mão o homem que eu havia posto para destruição, a tua vida responderá pela sua vida, e o teu povo pelo seu povo.

[[v11-20-43]]

^<<v11-20-43,43>>^ E o rei de Israel seguiu para sua casa, desgostoso e indignado, e veio a Samária.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]