include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-21-1]]

^<<v11-21-1,1>>^ Sucedeu depois destas coisas que, tendo Nabote, o jizreelita, uma vinha em Jizrreel, junto ao palácio de Acabe, rei de Samária,

[[v11-21-2]]

^<<v11-21-2,2>>^ falou este a Nabote, dizendo: Dá-me a tua vinha, para que me sirva de horta, porque está vizinha, ao pé da minha casa; e te darei por ela outra vinha melhor; ou, se desejares, dar-te-ei o seu valor em dinheiro.

[[v11-21-3]]

^<<v11-21-3,3>>^ Respondeu, porém, Nabote a Acabe: Guarde-me o Senhor de que eu te dê a herança de meus pais.

[[v11-21-4]]

^<<v11-21-4,4>>^ Então Acabe veio para sua casa, desgostoso e indignado, por causa da palavra que Nabote, o jizreelita, lhe falara; pois este lhe dissera: Não te darei a herança de meus pais. Tendo-se deitado na sua cama, virou a rosto, e não quis comer.

[[v11-21-5]]

^<<v11-21-5,5>>^ Mas, vindo a ele Jezabel, sua mulher, lhe disse: Por que está o teu espírito tão desgostoso que não queres comer?

[[v11-21-6]]

^<<v11-21-6,6>>^ Ele lhe respondeu: Porque falei a Nabote, o jizreelita, e lhe disse: Dá-me a tua vinha por dinheiro; ou, se te apraz, te darei outra vinha em seu lugar. Ele, porém, disse: Não te darei a minha vinha.

[[v11-21-7]]

^<<v11-21-7,7>>^ Ao que Jezabel, sua mulher, lhe disse: Governas tu agora no reino de Israel? Levanta-te, come, e alegre-se o teu coração; eu te darei a vinha de Nabote, o jizreelita.

[[v11-21-8]]

^<<v11-21-8,8>>^ Então escreveu cartas em nome de Acabe e, selando-as com o sinete dele, mandou-as aos anciãos e aos nobres que habitavam com Nabote na sua cidade.

[[v11-21-9]]

^<<v11-21-9,9>>^ Assim escreveu nas cartas: Apregoai um jejum, e ponde Nabote diante do povo.

[[v11-21-10]]

^<<v11-21-10,10>>^ E ponde defronte dele dois homens, filhos de Belial, que testemunhem contra ele, dizendo: Blasfemaste contra Deus e contra o rei. Depois conduzi-o para fora, e apedrejai-o até que morra.

[[v11-21-11]]

^<<v11-21-11,11>>^ Pelo que os homens da cidade dele, isto é, os anciãos e os nobres que habitavam na sua cidade, fizeram como Jezabel lhes ordenara, conforme estava escrito nas cartas que ela lhes mandara.

[[v11-21-12]]

^<<v11-21-12,12>>^ Apregoaram um jejum, e puseram Nabote diante do povo.

[[v11-21-13]]

^<<v11-21-13,13>>^ Também vieram dois homens, filhos de Belial, e sentaram-se defronte dele; e estes filhos de Belial testemunharam contra Nabote perante o povo, dizendo: Nabote blasfemou contra Deus e contra o rei. Então o conduziram para fora da cidade e o apedrejaram, de sorte que morreu.

[[v11-21-14]]

^<<v11-21-14,14>>^ Depois mandaram dizer a Jezabel : Nabote foi apedrejado e morreu.

[[v11-21-15]]

^<<v11-21-15,15>>^ Ora, ouvindo Jezabel que Nabote fora apedrejado e morrera, disse a Acabe: Levanta-te e toma posse da vinha de Nabote, e jizreelita, a qual ele recusou dar-te por dinheiro; porque Nabote já não vive, mas é morto.

[[v11-21-16]]

^<<v11-21-16,16>>^ Quando Acabe ouviu que Nabote já era morto, levantou-se para descer à vinha de Nabote, o jizreelita, a fim de tomar posse dela.

[[v11-21-17]]

^<<v11-21-17,17>>^ Então veio a palavra do Senhor a Elias, o tisbita, dizendo:

[[v11-21-18]]

^<<v11-21-18,18>>^ Levanta-te, desce para encontrar-te com Acabe, rei de Israel, que está em Samária. Eis que está na vinha de Nabote, aonde desceu a fim de tomar posse dela.

[[v11-21-19]]

^<<v11-21-19,19>>^ E falar-lhe-ás, dizendo: Assim diz o Senhor: Porventura não mataste e tomaste a herança? Falar-lhe-ás mais, dizendo: Assim diz o Senhor: No lugar em que os cães lamberam o sangue de Nabote, lamberão também o teu próprio sangue.

[[v11-21-20]]

^<<v11-21-20,20>>^ Ao que disse Acabe a Elias: Já me achaste, ó inimigo meu? Respondeu ele: Achei-te; porque te vendeste para fazeres o que é mau aos olhos do Senhor.

[[v11-21-21]]

^<<v11-21-21,21>>^ Eis que trarei o mal sobre ti; lançarei fora a tua posteridade, e arrancarei de Acabe todo homem, escravo ou livre, em Israel;

[[v11-21-22]]

^<<v11-21-22,22>>^ e farei a tua casa como a casa de Jeroboão, filho de Nebate, e como a casa de Baasa, filho de Aías, por causa da provocação com que me provocaste à ira, fazendo Israel pecar.

[[v11-21-23]]

^<<v11-21-23,23>>^ Também acerca de Jezabel falou o Senhor, dizendo: Os cães comerão Jezabel junto ao antemuro de Jizreel.

[[v11-21-24]]

^<<v11-21-24,24>>^ Quem morrer a Acabe na cidade, os cães o comerão; e o que lhe morrer no campo, as aves do céu o comerão.

[[v11-21-25]]

^<<v11-21-25,25>>^ &#123;Não houve, porém, ninguém como Acabe, que se vendeu para fazer o que era mau aos olhos do Senhor, sendo instigado por Jezabel, sua mulher.

[[v11-21-26]]

^<<v11-21-26,26>>^ E fez grandes abominações, seguindo os ídolos, conforme tudo o que fizeram os amorreus, os quais o Senhor lançou fora da sua possessão, de diante dos filhos de Israel.&#125;

[[v11-21-27]]

^<<v11-21-27,27>>^ Sucedeu, pois, que Acabe, ouvindo estas palavras, rasgou as suas vestes, cobriu de saco a sua carne, e jejuou; e jazia em saco, e andava humildemente.

[[v11-21-28]]

^<<v11-21-28,28>>^ Então veio a palavra do Senhor a Elias, o tisbita, dizendo:

[[v11-21-29]]

^<<v11-21-29,29>>^ Não viste que Acabe se humilha perante mim? Por isso, porquanto se humilha perante mim, não trarei o mal enquanto ele viver, mas nos dias de seu filho trarei o mal sobre a sua casa.

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]