include::./index.adoc[]

[[v11-5-0]]
=== 1 Reis, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-5-1]]

^<<v11-5-1,1>>^ Hirão, rei de Tiro, enviou os seus servos a Salomão, quando ouviu que o haviam ungido rei em lugar de seu pai; porquanto Hirão fora sempre muito amigo de Davi.

[[v11-5-2]]

^<<v11-5-2,2>>^ Salomão, pois, mandou dizer a Hirão.

[[v11-5-3]]

^<<v11-5-3,3>>^ Bem sabes tu que Davi, meu pai, não pôde edificar uma casa ao nome do Senhor seu Deus, por causa das guerras com que o cercaram, até que o Senhor lhe pôs os inimigos debaixo dos seus pés.

[[v11-5-4]]

^<<v11-5-4,4>>^ Agora, porém, o Senhor meu Deus me tem dado descanso de todos os lados: adversário não há, nem calamidade alguma.

[[v11-5-5]]

^<<v11-5-5,5>>^ Pretendo, pois, edificar uma casa ao nome do Senhor meu Deus, como falou o senhor a Davi, meu pai, dizendo: Teu filho, que porei em teu lugar no teu trono, ele edificará uma casa ao meu nome.

[[v11-5-6]]

^<<v11-5-6,6>>^ Portanto, dá ordem agora que do Líbano me cortem cedros; os meus servos estarão com os teus servos; eu te pagarei o salário dos teus servos, conforme tudo o que disseres; porque tu sabes que entre nós ninguém há que saiba cortar madeira como os sidônios.

[[v11-5-7]]

^<<v11-5-7,7>>^ Quando Hirão ouviu as palavras de Salomão, muito se alegrou, e disse: Bendito seja hoje o Senhor, que deu a Davi um filho sábio sobre este tão grande povo.

[[v11-5-8]]

^<<v11-5-8,8>>^ E Hirão mandou dizer a Salomão: Ouvi o que me mandaste dizer. Eu farei tudo quanto desejas acerca das madeiras de cedro e de cipreste.

[[v11-5-9]]

^<<v11-5-9,9>>^ Os meus servos as levarão do Líbano até o mar, e farei conduzi-las em jangadas pelo mar até o lugar que me designares; ali as desamarrarei, e tu as receberás; também farás o meu desejo, dando sustento à minha casa.

[[v11-5-10]]

^<<v11-5-10,10>>^ Assim dava Hirão a Salomão madeira de cedro e madeira de cipreste, conforme todo o seu desejo.

[[v11-5-11]]

^<<v11-5-11,11>>^ E Salomão dava a Hirão vinte mil coros de trigo, para sustento da sua casa, e vinte , coros de azeite batido; isso fazia anualmente.

[[v11-5-12]]

^<<v11-5-12,12>>^ Deu, pois, o Senhor a Salomão sabedoria, como lhe tinha prometido. E houve paz entre Hirão e Salomão; e fizeram aliança entre si.

[[v11-5-13]]

^<<v11-5-13,13>>^ Também e rei Salomão fez, dentre todo o Israel, uma leva de gente para trabalho forçado; e a leva se compunha de trinta mil homens.

[[v11-5-14]]

^<<v11-5-14,14>>^ E os enviava ao Líbano por turnos, cada mês dez mil; um mês estavam no Líbano, e dois meses cada um em sua casa; e Adonirão estava sobre a leva.

[[v11-5-15]]

^<<v11-5-15,15>>^ Tinha também Salomão setenta mil que levavam as cargas, e oitenta mil que talhavam pedras nas montanhas,

[[v11-5-16]]

^<<v11-5-16,16>>^ afora os mestres de obra que estavam sobre aquele serviço, três mil e trezentos, os quais davam as ordens aos trabalhadores.

[[v11-5-17]]

^<<v11-5-17,17>>^ Por ordem do rei eles cortaram grandes pedras, de grande preço, para fundarem a casa em pedras lavradas.

[[v11-5-18]]

^<<v11-5-18,18>>^ Lavraram-nas, pois, os edificadores de Salomão, e os de Hirão, e os gebalitas, e prepararam as madeiras e as pedras para edificar a casa.

'''

xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[&#60; Capítulo Anterior] | <<v11-5-0,Topo>> | xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[Próximo Capítulo &#62;]