include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-9-1]]

^<<v11-9-1,1>>^ Sucedera pois que, tendo Salomão acabado de edificar a casa do Senhor, e a casa do rei, e tudo quanto lhe aprouve fazer,

[[v11-9-2]]

^<<v11-9-2,2>>^ apareceu-lhe o Senhor segunda vez, como lhe tinha aparecido em Gibeão.

[[v11-9-3]]

^<<v11-9-3,3>>^ E o Senhor lhe disse: Ouvi a tua oração e a tua súplica, que fizeste perante mim; santifiquei esta casa que edificaste, a fim de pôr ali o meu nome para sempre; e os meus olhos e o meu coração estarão ali todos os dias.

[[v11-9-4]]

^<<v11-9-4,4>>^ Ora, se tu andares perante mim como andou Davi, teu pai, com inteireza de coração e com eqüidade, fazendo conforme tudo o que te ordenei, e guardando os meus estatutos e as minhas ordenanças,

[[v11-9-5]]

^<<v11-9-5,5>>^ então confirmarei o trono de teu reino sobre Israel para sempre, como prometi a teu pai Davi, dizendo: Não te faltará varão sobre o trono de Israel.

[[v11-9-6]]

^<<v11-9-6,6>>^ Se, porém, vós e vossos filhos de qualquer maneira vos desviardes e não me seguirdes, nem guardardes os meus mandamentos e os meus estatutos, que vos tenho proposto, mas fordes, e servirdes a outros deuses, curvando-vos perante eles,

[[v11-9-7]]

^<<v11-9-7,7>>^ então exterminarei a Israel da terra que lhe dei; e a esta casa, que santifiquei a meu nome, lançarei longe da minha presença, e Israel será por provérbio e motejo entre todos os povos.

[[v11-9-8]]

^<<v11-9-8,8>>^ E desta casa, que é tão exaltada, todo aquele que por ela passar pasmará e assobiará, e dirá: Por que fez o Senhor assim a esta terra e a esta casa?

[[v11-9-9]]

^<<v11-9-9,9>>^ E lhe responderão: E porque deixaram ao Senhor seu Deus, que tirou da terra do Egito a seus pais, e se apegaram a deuses alheios, e perante eles se encurvaram, e os serviram; por isso o Senhor trouxe sobre eles todo este mal.

[[v11-9-10]]

^<<v11-9-10,10>>^ Ao fim dos vinte anos em que Salomão edificara as duas casas, a casa do Senhor e a casa do rei,

[[v11-9-11]]

^<<v11-9-11,11>>^ como Hirão, rei de Tiro, trouxera a Salomão madeira de cedro e de cipreste, e ouro segundo todo o seu desejo, deu o rei Salomão a Hirão vinte cidades na terra da Galiléia.

[[v11-9-12]]

^<<v11-9-12,12>>^ Hirão, pois, saiu de Tiro para ver as cidades que Salomão lhe dera; porém não lhe agradaram.

[[v11-9-13]]

^<<v11-9-13,13>>^ Pelo que disse: Que cidades são estas que me deste, irmão meu? De sorte que são chamadas até hoje terra de Cabul.

[[v11-9-14]]

^<<v11-9-14,14>>^ Hirão enviara ao rei cento e vinte talentos de ouro.

[[v11-9-15]]

^<<v11-9-15,15>>^ A razão da leva de gente para trabalho forçado que o rei Salomão fez é esta: edificar a casa do Senhor e a sua própria casa, e Milo, e o muro de Jerusalém, como também Hazor, e Megido, e Gezer.

[[v11-9-16]]

^<<v11-9-16,16>>^ Pois Faraó, rei do Egito, tendo subido, tomara a Gezer e a queimara a fogo, e matando os cananeus que moravam na cidade, dera-a em dote a sua filha, mulher de Salomão.

[[v11-9-17]]

^<<v11-9-17,17>>^ Salomão edificou Gezer, Bete-Horom a baixa,

[[v11-9-18]]

^<<v11-9-18,18>>^ Baalate, Tamar no deserto daquela terra,

[[v11-9-19]]

^<<v11-9-19,19>>^ como também todas as cidades-armazéns que Salomão tinha, as cidades dos carros as cidades dos cavaleiros, e tudo o que Salomão quis edificar em Jerusalém, no Líbano, e em toda a terra de seu domínio.

[[v11-9-20]]

^<<v11-9-20,20>>^ Quanto a todo o povo que restou dos amorreus, dos heteus, dos perizeus, dos heveus e dos jebuseus, que não eram dos filhos de Israel,

[[v11-9-21]]

^<<v11-9-21,21>>^ a seus filhos, que restaram depois deles na terra, os quais os filhos de Israel não puderam destruir totalmente, Salomão lhes impôs tributo de trabalho forçado, até hoje.

[[v11-9-22]]

^<<v11-9-22,22>>^ Mas dos filhos de Israel não fez Salomão escravo algum; porém eram homens de guerra, e seus servos, e seus príncipes, e seus capitães, e chefes dos seus carros e dos seus cavaleiros.

[[v11-9-23]]

^<<v11-9-23,23>>^ Estes eram os chefes dos oficiais que estavam sobre a obra de Salomão, quinhentos e cinqüenta, que davam ordens ao povo que trabalhava na obra.

[[v11-9-24]]

^<<v11-9-24,24>>^ Subiu, porém, a filha de Faraó da cidade de Davi à sua casa, que Salomão lhe edificara; então ele edificou Milo.

[[v11-9-25]]

^<<v11-9-25,25>>^ E Salomão oferecia três vezes por ano holocaustos e ofertas pacíficas sobre a altar que edificara ao Senhor, queimando com eles incenso sobre o altar que estava perante o Senhor, depois que acabou de edificar a casa.

[[v11-9-26]]

^<<v11-9-26,26>>^ Também o rei Salomão fez uma frota em Eziom-Geber, que está junto a Elote, na praia do Mar Vermelho, na terra de Edom.

[[v11-9-27]]

^<<v11-9-27,27>>^ Hirão mandou com aquela frota, em companhia dos servos de Salomão, os seus próprios servos, marinheiros que conheciam o mar;

[[v11-9-28]]

^<<v11-9-28,28>>^ os quais foram a Ofir, e tomaram de lá quatrocentos e vinte talentos de ouro, que trouxeram ao rei Salomão.

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]