include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-18-1]]

^<<v11-18-1,1>>^ Depois de muitos dias veio a Elias a palavra do Senhor, no terceiro ano, dizendo: Vai, apresenta-te a Acabe; e eu mandarei chuva sobre a terra.

[[v11-18-2]]

^<<v11-18-2,2>>^ Então Elias foi apresentar-se a Acabe. E a fome era extrema em Samária.

[[v11-18-3]]

^<<v11-18-3,3>>^ Acabe chamou a Obadias, o mordomo &#123;ora, Obadias temia muito ao Senhor;

[[v11-18-4]]

^<<v11-18-4,4>>^ pois sucedeu que, destruindo Jezabel os profetas do Senhor, Obadias tomou cem profetas e os escondeu, cinqüenta numa cova e cinqüenta noutra, e os sustentou com pão e água&#125;;

[[v11-18-5]]

^<<v11-18-5,5>>^ e disse Acabe a Obadias: Vai pela terra a todas as fontes de água, e a todos os rios. Pode ser que achemos erva para salvar a vida dos cavalos e mulas, de maneira que não percamos todos os animais.

[[v11-18-6]]

^<<v11-18-6,6>>^ E repartiram entre si a terra, para a percorrerem; e foram a sós, Acabe por um caminho, e Obadias por outro.

[[v11-18-7]]

^<<v11-18-7,7>>^ Quando, pois, Obadias já estava em caminho, eis que Elias se encontrou com ele; e Obadias, reconhecendo-o, prostrou-se com o rosto em terra e disse: És tu, meu senhor Elias?

[[v11-18-8]]

^<<v11-18-8,8>>^ Respondeu-lhe ele: Sou eu. Vai, dize a teu senhor: Eis que Elias está aqui.

[[v11-18-9]]

^<<v11-18-9,9>>^ Ele, porém, disse: Em que pequei, para que entregues teu servo na mão de Acabe, para ele me matar?

[[v11-18-10]]

^<<v11-18-10,10>>^ Vive o Senhor teu Deus, que não há nação nem reino aonde o meu senhor não tenha mandado em busca de ti; e dizendo eles: Aqui não está; então fazia-os jurar que não te haviam achado.

[[v11-18-11]]

^<<v11-18-11,11>>^ Agora tu dizes: Vai, dize a teu senhor: Eis que Elias está aqui.

[[v11-18-12]]

^<<v11-18-12,12>>^ E será que, apartando-me eu de ti, o Espírito do Senhor te levará não sei para onde; e, vindo eu dar as novas a Acabe, e não te achando ele, matar-me-á. Todavia eu, teu servo, temo ao Senhor desde a minha mocidade.

[[v11-18-13]]

^<<v11-18-13,13>>^ Porventura não disseram a meu senhor o que fiz, quando Jezabel matava os profetas do Senhor, como escondi cem dos profetas do Senhor, cinqüenta numa cova e cinqüenta noutra, e os sustentei com pão e água:

[[v11-18-14]]

^<<v11-18-14,14>>^ E agora tu dizes: Vai, dize a teu senhor: Eis que Elias está aqui! Ele me matará.

[[v11-18-15]]

^<<v11-18-15,15>>^ E disse Elias: Vive o Senhor dos exércitos, em cuja presença estou, que deveras hoje hei de apresentar-me a ele.

[[v11-18-16]]

^<<v11-18-16,16>>^ Então foi Obadias encontrar-se com Acabe, e lho anunciou; e Acabe foi encontrar-se com Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ E sucedeu que, vendo Acabe a Elias, disse-lhe: És tu, perturbador de Israel?

[[v11-18-18]]

^<<v11-18-18,18>>^ Respondeu Elias: Não sou eu que tenho perturbado a Israel, mas és tu e a casa de teu pai, por terdes deixado os mandamentos do Senhor, e por teres tu seguido os baalins.

[[v11-18-19]]

^<<v11-18-19,19>>^ Agora pois manda reunir-se a mim todo o Israel no monte Carmelo, como também os quatrocentos e cinqüenta profetas de Baal, e os quatrocentos profetas de Asera, que comem da mesa de Jezabel.

[[v11-18-20]]

^<<v11-18-20,20>>^ Então Acabe convocou todos os filhos de Israel, e reuniu os profetas no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ E Elias se chegou a todo o povo, e disse: Até quando coxeareis entre dois pensamentos? Se o Senhor é Deus, segui-o; mas se Baal, segui-o. O povo, porém, não lhe respondeu nada.

[[v11-18-22]]

^<<v11-18-22,22>>^ Então disse Elias ao povo: Só eu fiquei dos profetas do Senhor; mas os profetas de Baal são quatrocentos e cinqüenta homens.

[[v11-18-23]]

^<<v11-18-23,23>>^ Dêem-se-nos, pois, dois novilhos; e eles escolham para si um dos novilhos, e o dividam em pedaços, e o ponham sobre a lenha, porém não lhe metam fogo; e eu prepararei o outro novilho, e o porei sobre a lenha, e não lhe meterei fogo.

[[v11-18-24]]

^<<v11-18-24,24>>^ Então invocai o nome do vosso deus, e eu invocarei o nome do Senhor; e há de ser que o deus que responder por meio de fogo, esse será Deus. E todo o povo respondeu, dizendo: É boa esta palavra.

[[v11-18-25]]

^<<v11-18-25,25>>^ Disse, pois, Elias aos profetas de Baal: Escolhei para vós: um dos novilhos, e preparai-o primeiro, porque sois muitos, e invocai o nome do Senhor, vosso deus, mas não metais fogo ao sacrifício.

[[v11-18-26]]

^<<v11-18-26,26>>^ E, tomando o novilho que se lhes dera, prepararam-no, e invocaram o nome de Baal, desde a manhã até o meio-dia, dizendo: Ah Baal, responde-nos! Porém não houve voz; ninguém respondeu. E saltavam em volta do altar que tinham feito.

[[v11-18-27]]

^<<v11-18-27,27>>^ Sucedeu que, ao meio-dia, Elias zombava deles, dizendo: Clamai em altas vozes, porque ele é um deus; pode ser que esteja falando, ou que tenha alguma coisa que fazer, ou que intente alguma viagem; talvez esteja dormindo, e necessite de que o acordem.

[[v11-18-28]]

^<<v11-18-28,28>>^ E eles clamavam em altas vozes e, conforme o seu costume, se retalhavam com facas e com lancetas, até correr o sangue sobre eles.

[[v11-18-29]]

^<<v11-18-29,29>>^ Também sucedeu que, passado o meio dia, profetizaram eles até a hora de se oferecer o sacrifício da tarde. Porém não houve voz; ninguém respondeu, nem atendeu.

[[v11-18-30]]

^<<v11-18-30,30>>^ Então Elias disse a todo o povo: chegai-vos a mim. E todo o povo se chegou a ele. E Elias reparou o altar do Senhor, que havia sido derrubado.

[[v11-18-31]]

^<<v11-18-31,31>>^ Tomou doze pedras, conforme o número das tribos dos filhos de Jacó, ao qual viera a palavra do Senhor, dizendo: Israel será o teu nome;

[[v11-18-32]]

^<<v11-18-32,32>>^ e com as pedras edificou o altar em nome do Senhor; depois fez em redor do altar um rego, em que podiam caber duas medidas de semente.

[[v11-18-33]]

^<<v11-18-33,33>>^ Então armou a lenha, e dividiu o novilho em pedaços, e o pôs sobre a lenha, e disse: Enchei de água quatro cântaros, e derramai-a sobre o holocausto e sobre a lenha.

[[v11-18-34]]

^<<v11-18-34,34>>^ Disse ainda: fazei-o segunda vez; e o fizeram segunda vez. De novo disse: Fazei-o terceira vez; e o fizeram terceira vez.

[[v11-18-35]]

^<<v11-18-35,35>>^ De maneira que a água corria ao redor do altar; e ele encheu de água também o rego.

[[v11-18-36]]

^<<v11-18-36,36>>^ Sucedeu pois que, sendo já hora de se oferecer o sacrifício da tarde, o profeta Elias se chegou, e disse: Ó Senhor, Deus de Abraão, de Isaque, e de Israel, seja manifestado hoje que tu és Deus em Israel, e que eu sou teu servo, e que conforme a tua palavra tenho feito todas estas coisas.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, ó Senhor, responde-me para que este povo conheça que tu, ó Senhor, és Deus, e que tu fizeste voltar o seu coração.

[[v11-18-38]]

^<<v11-18-38,38>>^ Então caiu fogo do Senhor, e consumiu o holocausto, a lenha, as pedras, e o pó, e ainda lambeu a água que estava no rego.

[[v11-18-39]]

^<<v11-18-39,39>>^ Quando o povo viu isto, prostraram-se todos com o rosto em terra e disseram: O senhor é Deus! O Senhor é Deus!

[[v11-18-40]]

^<<v11-18-40,40>>^ Disse-lhes Elias: Agarrai os profetas de Baal! que nenhum deles escape: Agarraram-nos; e Elias os fez descer ao ribeiro de Quisom, onde os matou.

[[v11-18-41]]

^<<v11-18-41,41>>^ Então disse Elias a Acabe: Sobe, come e bebe, porque há ruído de abundante chuva.

[[v11-18-42]]

^<<v11-18-42,42>>^ Acabe, pois, subiu para comer e beber; mas Elias subiu ao cume do Carmelo e, inclinando-se por terra, meteu o rosto entre os joelhos.

[[v11-18-43]]

^<<v11-18-43,43>>^ E disse ao seu moço: Sobe agora, e olha para a banda do mar. E ele subiu, olhou, e disse: Não há nada. Então disse Elias: Volta lá sete vezes.

[[v11-18-44]]

^<<v11-18-44,44>>^ Sucedeu que, à sétima vez, disse: Eis que se levanta do mar uma nuvem, do tamanho da mão dum homem: Então disse Elias: Sobe, e dize a Acabe: Aparelha o teu carro, e desce, para que a chuva não te impeça.

[[v11-18-45]]

^<<v11-18-45,45>>^ E sucedeu que em pouco tempo o céu se enegreceu de nuvens e vento, e caiu uma grande chuva. Acabe, subindo ao carro, foi para Jizreel:

[[v11-18-46]]

^<<v11-18-46,46>>^ E a mão do Senhor estava sobre Elias, o qual cingiu os lombos, e veio correndo perante Acabe, até a entrada de Jizreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]