include::./index.adoc[]

[[v11-2-0]]
=== 1 Reis, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-2-1]]

^<<v11-2-1,1>>^ Ora, aproximando-se o dia da morte de Davi, deu ele ordem a Salomão, seu filho, dizendo:

[[v11-2-2]]

^<<v11-2-2,2>>^ Eu vou pelo caminho de toda a terra; sê forte, pois, e porta-te como homem.

[[v11-2-3]]

^<<v11-2-3,3>>^ Guarda as ordenanças do Senhor teu Deus, andando nos seus caminhos, e observando os seus estatutos, os seus mandamentos, os seus preceitos e os seus testemunhos, como está escrito na lei de Moisés, para que prosperes em tudo quanto fizeres e por onde quer que fores,

[[v11-2-4]]

^<<v11-2-4,4>>^ e para que o Senhor confirme a palavra que falou acerca de mim, dizendo: Se teus filhos guardarem os seus caminhos, andando perante a minha face fielmente, com todo o seu coração e com toda a sua alma, nunca te faltará sucessor ao trono de Israel.

[[v11-2-5]]

^<<v11-2-5,5>>^ Tu sabes também o que me fez Joabe, filho de Zeruia, a saber, o que fez aos dois chefes do exército de Israel, a Abner, filho de Ner, e a Amasa, filho de Jeter, os quais ele matou, e em tempo de paz derramou o sangue de guerra, manchando com ele o cinto que tinha nos lombos, e os sapatos que trazia nos pés.

[[v11-2-6]]

^<<v11-2-6,6>>^ Faze, pois, segundo a tua sabedoria, e não permitas que suas cãs desçam à sepultura em paz.

[[v11-2-7]]

^<<v11-2-7,7>>^ Mas para com os filhos de Barzilai, o gileadita, usa de benevolência, e estejam eles entre os que comem à tua mesa; porque assim se houveram comigo, quando eu fugia por causa de teu irmão Absalão.

[[v11-2-8]]

^<<v11-2-8,8>>^ E eis que também contigo está Simei, filho de Gêra, benjamita, de Baurim, que me lançou atroz maldição, no dia em que eu ia a Maanaim; porém ele saiu a encontrar-se comigo junto ao Jordão, e eu lhe jurei pelo Senhor, dizendo: Não te matarei à espada.

[[v11-2-9]]

^<<v11-2-9,9>>^ Agora, porém, não o tenhas por inocente; pois és homem sábio, e bem saberás o que lhe hás de fazer; farás com que as suas cãs desçam à sepultura com sangue.

[[v11-2-10]]

^<<v11-2-10,10>>^ Depois Davi dormiu com seus pais, e foi sepultado na cidade de Davi.

[[v11-2-11]]

^<<v11-2-11,11>>^ E foi o tempo que Davi reinou sobre Israel quarenta anos: sete anos reinou em Hebrom, e em Jerusalém reinou trinta e três anos.

[[v11-2-12]]

^<<v11-2-12,12>>^ Salomão, pois, assentou-se no trono de Davi, seu pai; e o seu reino se fortificou sobremaneira.

[[v11-2-13]]

^<<v11-2-13,13>>^ Então Adonias, filho de Hagite, veio a Bate-Seba, mãe de Salomão; e perguntou ela: De paz é a tua vinda? Respondeu ele: É de paz.

[[v11-2-14]]

^<<v11-2-14,14>>^ E acrescentou: Uma palavra tenho que dizer-te. Respondeu ela: Fala.

[[v11-2-15]]

^<<v11-2-15,15>>^ Disse, pois, ele: Bem sabes que o reino era meu, e que todo o Israel tinha posto a vista em mim para que eu viesse a reinar; contudo o reino se transferiu e veio a ser de meu irmão, porque foi feito seu pelo Senhor.

[[v11-2-16]]

^<<v11-2-16,16>>^ Agora uma só coisa te peço; não ma recuses. Ela lhe disse: Fala.

[[v11-2-17]]

^<<v11-2-17,17>>^ E ele disse: Peço-te que fales ao rei Salomão &#123;porque ele não to recusará&#125; , que me dê por mulher a Abisague, a sunamita.

[[v11-2-18]]

^<<v11-2-18,18>>^ Respondeu Bate-Seba: Pois bem; eu falarei por ti ao rei.

[[v11-2-19]]

^<<v11-2-19,19>>^ Foi, pois, Bate-Seba ter com o rei Salomão, para falar-lhe por Adonias. E o rei se levantou a encontrar-se com ela, e se inclinou diante dela; então, assentando-se no seu trono, mandou que pusessem um trono para a rainha-mãe; e ela se assentou à sua direita.

[[v11-2-20]]

^<<v11-2-20,20>>^ Então disse ela: Só uma pequena coisa te peço; não ma recuses. Respondeu-lhe o rei: Pede, minha mãe, porque não te recusarei.

[[v11-2-21]]

^<<v11-2-21,21>>^ E ela disse: Dê-se Abisague, a sunamita, por mulher a teu irmão Adonias.

[[v11-2-22]]

^<<v11-2-22,22>>^ Então respondeu o rei Salomão, e disse a sua mãe: E por que pedes Abisague, a sunamita, para Adonias? Pede também para ele o reino &#123;porque é meu irmão mais velho&#125;; sim, para ele, e também para Abiatar, o sacerdote, e para Joabe, filho de Zeruia.

[[v11-2-23]]

^<<v11-2-23,23>>^ E jurou o rei Salomão pelo Senhor, dizendo: Assim Deus me faça, e outro tanto, se não falou Adonias esta palavra contra a sua vida.

[[v11-2-24]]

^<<v11-2-24,24>>^ Agora, pois, vive o Senhor, que me confirmou e me fez assentar no trono de Davi, meu pai, e que me estabeleceu casa, como tinha dito, que hoje será morto Adonias.

[[v11-2-25]]

^<<v11-2-25,25>>^ E o rei Salomão deu ordem a Benaías, filho de Jeoiada, o qual feriu a Adonias, de modo que morreu.

[[v11-2-26]]

^<<v11-2-26,26>>^ Também a Abiatar, o sacerdote, disse o rei: Vai para Anatote, para os teus campos, porque és homem digno de morte; porém hoje não te matarei, porquanto levaste a arca do Senhor Deus diante de Davi, meu pai, e porquanto participaste de todas as aflições de meu pai.

[[v11-2-27]]

^<<v11-2-27,27>>^ Salomão, pois, expulsou Abiatar, para que não fosse sacerdote do Senhor, assim cumprindo a palavra que o Senhor tinha dito acerca da casa de Eli em Siló.

[[v11-2-28]]

^<<v11-2-28,28>>^ Ora, veio esta notícia a Joabe &#123;pois Joabe se desviara após Adonias, ainda que não se tinha desviado após Absalão&#125; ; pelo que Joabe fugiu para o tabernáculo do Senhor, e apegou-se as pontas do altar.

[[v11-2-29]]

^<<v11-2-29,29>>^ E disseram ao rei Salomão: Joabe fugiu para o tabernáculo do Senhor; e eis que está junto ao altar. Então Salomão enviou Benaías, filho de Jeoiada, dizendo: Vai, mata-o.

[[v11-2-30]]

^<<v11-2-30,30>>^ Foi, pois, Benaías ao tabernáculo do Senhor, e disse a Joabe: Assim diz o rei: Sai daí. Respondeu Joabe: Não! porém aqui morrerei. E Benaías tornou com a resposta ao rei, dizendo: Assim falou Joabe, e assim me respondeu.

[[v11-2-31]]

^<<v11-2-31,31>>^ Ao que lhe disse o rei: Faze como ele disse; mata-o, e sepulta-o, para que tires de sobre mim e de sobre a casa de meu pai o sangue que Joabe sem causa derramou.

[[v11-2-32]]

^<<v11-2-32,32>>^ Assim o Senhor fará recair o sangue dele sobre a sua cabeça, porque deu sobre dois homens mais justos e melhores do que ele, e os matou à espada, sem que meu pai Davi o soubesse, a saber: a Abner, filho de Ner, chefe do exército de Israel, e a Amasa, filho de Jeter, chefe do exército de Judá.

[[v11-2-33]]

^<<v11-2-33,33>>^ Assim recairá o sangue destes sobre a cabeça de Joabe e sobre a cabeça da sua descendência para sempre; mas a Davi, e à sua descendência, e à sua casa, e ao seu trono, o Senhor dará paz para sempre.

[[v11-2-34]]

^<<v11-2-34,34>>^ Então Benaías, filho de Jeoiada, subiu e, arremetendo contra Joabe, o matou. E foi sepultado em sua casa, no deserto.

[[v11-2-35]]

^<<v11-2-35,35>>^ Em lugar dele o rei pôs a Benaías, filho de Jeoiada, sobre o exército; e a Zadoque, o sacerdote, pôs em lugar de Abiatar.

[[v11-2-36]]

^<<v11-2-36,36>>^ Depois o rei mandou chamar a Simei e lhe disse: Edifica para ti uma casa em Jerusalém, habita aí, e daí não saias, nem para uma nem para outra parte.

[[v11-2-37]]

^<<v11-2-37,37>>^ E fica sabendo que, no dia em que saíres e passares o ribeiro de Cedrom, de certo hás de morrer. O teu sangue será sobre a tua cabeça.

[[v11-2-38]]

^<<v11-2-38,38>>^ Respondeu Simei ao rei: Boa é essa palavra; como tem dito o rei meu senhor, assim fará o teu servo. E Simei habitou em Jerusalém muitos dias.

[[v11-2-39]]

^<<v11-2-39,39>>^ Sucedeu porém que, ao cabo de três anos, dois servos de Simei fugiram para Aquis, filho de Maacá, rei de Gate. E deram parte a Simei, dizendo: Eis que teus servos estão em Gate.

[[v11-2-40]]

^<<v11-2-40,40>>^ Então Simei se levantou, albardou o seu jumento e foi a Gate ter com Aquis, em busca dos seus servos; assim foi Simei, e os trouxe de Gate.

[[v11-2-41]]

^<<v11-2-41,41>>^ Disseram a Salomão que Simei fora de Jerusalém a Gate, e já havia voltado.

[[v11-2-42]]

^<<v11-2-42,42>>^ Então o rei mandou chamar a Simei e lhe disse: Não te conjurei pelo Senhor e não te protestei, dizendo: No dia em que saíres para qualquer parte, sabe de certo que hás de morrer? E tu me disseste: Boa é essa palavra que ouvi.

[[v11-2-43]]

^<<v11-2-43,43>>^ Por que, então, não guardaste o juramento do Senhor, e a ordem que te dei?

[[v11-2-44]]

^<<v11-2-44,44>>^ Disse-lhe mais: Bem sabes tu, e o teu coração reconhece toda a maldade que fizeste a Davi, meu pai; pelo que o Senhor fará recair a tua maldade sobre a tua cabeça.

[[v11-2-45]]

^<<v11-2-45,45>>^ Mas o rei Salomão será abençoado, e o trono de Davi será confirmado perante o Senhor para sempre:

[[v11-2-46]]

^<<v11-2-46,46>>^ E o rei deu ordem a Benaías, filho de Jeoiada, o qual saiu, e feriu a Simei, de modo que morreu. Assim foi confirmado o reino na mão de Salomão.

'''

xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[Próximo Capítulo &#62;]