include::./index.adoc[]

[[v11-8-0]]
=== 1 Reis, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-8-1]]

^<<v11-8-1,1>>^ Então congregou Salomão diante de si em Jerusalém os anciãos de Israel, e todos os cabeças das tribos, os chefes das casas paternas, dentre os filhos de Israel, para fazerem subir da cidade de Davi, que é Sião, a arca do pacto do Senhor:

[[v11-8-2]]

^<<v11-8-2,2>>^ De maneira que todos os homens de Israel se congregaram ao rei Salomão, na ocasião da festa, no mês de etanim, que é o sétimo mês.

[[v11-8-3]]

^<<v11-8-3,3>>^ E tendo chegado todos os anciãos de Israel, os sacerdotes alçaram a arca;

[[v11-8-4]]

^<<v11-8-4,4>>^ e trouxeram para cima a arca do Senhor, e a tenda da revelação, juntamente com todos os utensílios sagrados que havia na tenda; foram os sacerdotes e os levitas que os trouxeram para cima.

[[v11-8-5]]

^<<v11-8-5,5>>^ E o rei Salomão, e toda a congregação de Israel, que se ajuntara diante dele, estavam diante da arca, imolando ovelhas e bois, os quais não se podiam contar nem numerar, pela sua multidão.

[[v11-8-6]]

^<<v11-8-6,6>>^ E os sacerdotes introduziram a arca do pacto do Senhor no seu lugar, no oráculo da casa, no lugar santíssimo, debaixo das asas dos querubins.

[[v11-8-7]]

^<<v11-8-7,7>>^ Pois os querubins estendiam ambas as asas sobre o lugar da arca, e cobriam por cima a arca e os seus varais.

[[v11-8-8]]

^<<v11-8-8,8>>^ Os varais sobressaíam tanto que as suas pontas se viam desde o santuário diante do oráculo, porém de fora não se viam; e ali estão até o dia de hoje.

[[v11-8-9]]

^<<v11-8-9,9>>^ Nada havia na arca, senão as duas tábuas de pedra, que Moisés ali pusera, junto a Horebe, quando o Senhor, fez u pacto com os filhos de Israel, ao sairem eles da terra do Egito.

[[v11-8-10]]

^<<v11-8-10,10>>^ E sucedeu que, saindo os sacerdotes do santuário, uma nuvem encheu a casa do Senhor;

[[v11-8-11]]

^<<v11-8-11,11>>^ de modo que os sacerdotes não podiam ter-se em pé para ministrarem, por causa da nuvem; porque a glória do Senhor enchera a casa do Senhor.

[[v11-8-12]]

^<<v11-8-12,12>>^ Então falou Salomão: O Senhor disse que habitaria na escuridão.

[[v11-8-13]]

^<<v11-8-13,13>>^ Certamente te edifiquei uma casa para morada, assento para a tua eterna habitação.

[[v11-8-14]]

^<<v11-8-14,14>>^ Então o rei virou o rosto, e abençoou toda a congregação de Israel; e toda a congregação ficou em pe.

[[v11-8-15]]

^<<v11-8-15,15>>^ E disse Salomão: Bendito seja e Senhor, Deus de Israel, que falou pela sua boca a Davi, meu pai, e pela sua mão cumpriu a palavra que disse:

[[v11-8-16]]

^<<v11-8-16,16>>^ Desde o dia em que eu tirei do Egito o meu povo Israel, não escolhi cidade alguma de todas as tribos de Israel para se edificar ali uma casa em que estivesse o meu nome; porém escolhi a Davi, para que presidisse sobre o meu povo Israel.

[[v11-8-17]]

^<<v11-8-17,17>>^ Ora, Davi, meu pai, propusera em seu coração edificar uma casa ao nome de Senhor, Deus de Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ Mas o Senhor disse a Davi, meu pai: Quanto ao teres proposto no teu coração o edificar casa ao meu nome, bem fizeste em o propor no teu coração.

[[v11-8-19]]

^<<v11-8-19,19>>^ Todavia, tu não edificarás a casa; porém teu filho, que sair de teus lombos, esse edificará a casa ao meu nome.

[[v11-8-20]]

^<<v11-8-20,20>>^ E o Senhor cumpriu a palavra que falou; porque me levantei em lugar de Davi, meu pai, e me assentei no trono de Israel, como falou o Senhor, e edifiquei uma casa, ao nome do Senhor, Deus de Israel.

[[v11-8-21]]

^<<v11-8-21,21>>^ E ali constituí lugar para a arca em que está o pacto do Senhor, que ele fez com nossos pais quando os tirou da terra de Egito.

[[v11-8-22]]

^<<v11-8-22,22>>^ Depois Salomão se pôs diante do altar do Senhor, em frente de toda a congregação de Israel e, estendendo as mãos para os céus,

[[v11-8-23]]

^<<v11-8-23,23>>^ disse: Ó Senhor, Deus de Israel, não há Deus como tu, em cima no céu nem em baixo na terra, que guardas o pacto e a benevolência para com os teus servos que andam diante de ti com inteireza de coração;

[[v11-8-24]]

^<<v11-8-24,24>>^ que cumpriste com teu servo Davi, meu pai, o que lhe prometeste; porque com a tua boca o disseste, e com a tua mão o cumpriste, como neste dia se vê.

[[v11-8-25]]

^<<v11-8-25,25>>^ Agora, pois, ó Senhor, Deus de Israel, faz a teu servo Davi, meu pai, o que lhe prometeste ao dizeres: Não te faltará diante de mim sucessor, que se assente no trono de Israel; contanto que teus filhos guardem o seu caminho, para andarem diante e mim como tu andaste.

[[v11-8-26]]

^<<v11-8-26,26>>^ Agora também, ó Deus de Israel, cumpra-se a tua palavra, que disseste a teu servo Davi, meu pai.

[[v11-8-27]]

^<<v11-8-27,27>>^ Mas, na verdade, habitaria Deus na terra? Eis que o céu, e até o céu dos céus, não te podem conter; quanto menos esta casa que edifiquei!

[[v11-8-28]]

^<<v11-8-28,28>>^ Contudo atende à oração de teu servo, e à sua súplica, ó Senhor meu Deus, para ouvires o clamor e a oração que o teu servo hoje faz diante de ti;

[[v11-8-29]]

^<<v11-8-29,29>>^ para que os teus olhos estejam abertos noite e dia sobre esta casa, sobre este lugar, do qual disseste: O meu nome estará ali; para ouvires a oração que o teu servo fizer, voltado para este lugar.

[[v11-8-30]]

^<<v11-8-30,30>>^ Ouve, pois, a súplica do teu servo, e do teu povo Israel, quando orarem voltados para este lugar. Sim, ouve tu do lugar da tua habitação no céu; ouve, e perdoa.

[[v11-8-31]]

^<<v11-8-31,31>>^ Se alguém pecar contra o seu próximo e lhe for exigido que jure, e ele vier jurar diante do teu altar nesta casa,

[[v11-8-32]]

^<<v11-8-32,32>>^ ouve então do céu, age, e julga os teus servos; condena ao culpado, fazendo recair sobre a sua cabeça e seu proceder, e justifica ao reto, retribuindo-lhe segundo a sua retidão.

[[v11-8-33]]

^<<v11-8-33,33>>^ Quando o teu povo Israel for derrotado diante do inimigo, por ter pecado contra ti; se eles voltarem a ti, e confessarem o teu nome, e orarem e fizerem súplicas a ti nesta casa,

[[v11-8-34]]

^<<v11-8-34,34>>^ ouve então do céu, e perdoa a pecado do teu povo Israel, e torna a levá-lo à terra que deste a seus pais.

[[v11-8-35]]

^<<v11-8-35,35>>^ Quando o céu se fechar e não houver chuva, por terem pecado contra ti, e orarem, voltados para este lugar, e confessarem o teu nome, e se converterem dos seus pecados, quando tu os afligires,

[[v11-8-36]]

^<<v11-8-36,36>>^ ouve então do céu, e perdoa o pecado dos teus servos e do teu povo Israel, ensinando-lhes o bom caminho em que devem andar; e envia chuva sobre a tua terra que deste ao teu povo em herança.

[[v11-8-37]]

^<<v11-8-37,37>>^ Se houver na terra fome ou peste, se houver crestamento ou ferrugem, gafanhotos ou lagarta; se o seu inimigo os cercar na terra das suas cidades; seja qual for a praga ou doença que houver;

[[v11-8-38]]

^<<v11-8-38,38>>^ toda oração, toda súplica que qualquer homem ou todo o teu povo Israel fizer, conhecendo cada um a chaga do seu coração, e estendendo as suas mãos para esta casa,

[[v11-8-39]]

^<<v11-8-39,39>>^ ouve então do céu, lugar da tua habitação, perdoa, e age, retribuindo a cada um conforme todos os seus caminhos, segundo vires o seu coração &#123;pois tu, só tu conheces o coração de todos os filhos dos homens&#125;;

[[v11-8-40]]

^<<v11-8-40,40>>^ para que te temam todos os dias que viverem na terra que deste a nossos pais.

[[v11-8-41]]

^<<v11-8-41,41>>^ Também quando o estrangeiro, que não é do teu povo Israel, vier de terras remotas por amor do teu nome

[[v11-8-42]]

^<<v11-8-42,42>>^ &#123;porque ouvirão do teu grande nome, e da tua forte mão, e do teu braço estendido&#125;, quando vier orar voltado para esta casa,

[[v11-8-43]]

^<<v11-8-43,43>>^ ouve do céu, lugar da tua habitação, e faze conforme tudo o que o estrangeiro a ti clamar, a fim de que todos os povos da terra conheçam o teu nome, e te temam como o teu povo Israel, e saibam que pelo teu nome é chamada esta casa que edifiquei.

[[v11-8-44]]

^<<v11-8-44,44>>^ Quando o teu povo sair à guerra contra os seus inimigos, seja qual for o caminho por que os enviares, e orarem ao Senhor, voltados para a cidade que escolheste, e para a casa que edifiquei ao teu nome,

[[v11-8-45]]

^<<v11-8-45,45>>^ ouve então do céu a sua oração e a sua súplica, e defende a sua causa.

[[v11-8-46]]

^<<v11-8-46,46>>^ Quando pecarem contra ti &#123;pois não há homem que não peque&#125;, e tu te indignares contra eles, e os entregares ao inimigo, de modo que os levem em cativeiro para a terra inimiga, longínqua ou próxima;

[[v11-8-47]]

^<<v11-8-47,47>>^ se na terra aonde forem levados em cativeiro caírem em si, e se converterem, e na terra do seu cativeiro te suplicarem, dizendo: Pecamos e procedemos perversamente, cometemos iniqüidade;

[[v11-8-48]]

^<<v11-8-48,48>>^ se voltarem a ti de todo o seu coração e de toda a sua alma, na terra de seus inimigos que os tenham levado em cativeiro, e orarem a ti, voltados para a sua terra, que deste a seus pais, para a cidade que escolheste, e para a casa que edifiquei ao teu nome,

[[v11-8-49]]

^<<v11-8-49,49>>^ ouve então do céu, lugar da tua habitação, a sua oração e a sua súplica, e defende a sua causa;

[[v11-8-50]]

^<<v11-8-50,50>>^ perdoa ao teu povo que houver pecado contra ti, perdoa todas as transgressões que houverem cometido contra ti, e dá-lhes alcançar misericórdia da parte dos que os levarem cativos, para que se compadeçam deles;

[[v11-8-51]]

^<<v11-8-51,51>>^ porque são o teu povo e a tua herança, que tiraste da terra do Egito, do meio da fornalha de ferro.

[[v11-8-52]]

^<<v11-8-52,52>>^ Estejam abertos os teus olhos à súplica do teu servo e à súplica do teu povo Israel, a fim de os ouvires sempre que clamarem a ti.

[[v11-8-53]]

^<<v11-8-53,53>>^ Pois tu, ó Senhor Jeová, os separaste dentre todos os povos da terra, para serem a tua herança como falaste por intermédio de Moisés, teu servo, quando tiraste do Egito nossos pais.

[[v11-8-54]]

^<<v11-8-54,54>>^ Sucedeu pois que, acabando Salomão de fazer ao Senhor esta oração e esta súplica, estando de joelhos e com as mãos estendidas para o céu, se levantou de diante do altar do Senhor,

[[v11-8-55]]

^<<v11-8-55,55>>^ pôs-se em pé, e abençoou em alta voz a toda a congregação de Israel, dizendo:

[[v11-8-56]]

^<<v11-8-56,56>>^ Bendito seja o Senhor, que deu repouso ao seu povo Israel, segundo tudo o que disse; não falhou nem sequer uma de todas as boas palavras que falou por intermédio de Moisés, seu servo.

[[v11-8-57]]

^<<v11-8-57,57>>^ O Senhor nosso Deus seja conosco, como foi com nossos pais; não nos deixe, nem nos abandone;

[[v11-8-58]]

^<<v11-8-58,58>>^ mas incline a si os nossos corações, a fim de andarmos em todos os seus caminhos, e guardarmos os seus mandamentos, e os seus estatutos, e os seus preceitos, que ordenou a nossos pais.

[[v11-8-59]]

^<<v11-8-59,59>>^ E que estas minhas palavras, com que supliquei perante o Senhor, estejam perto, diante do Senhor nosso Deus, de dia e de noite, para que defenda ele a causa do seu servo e a causa do seu povo Israel, como cada dia o exigir,

[[v11-8-60]]

^<<v11-8-60,60>>^ para que todos os povos da terra, saibam que o Senhor é Deus, e que não há outro.

[[v11-8-61]]

^<<v11-8-61,61>>^ E seja o vosso coração perfeito para com o Senhor nosso Deus, para andardes nos seus estatutos, e guardardes os seus mandamentos, como hoje o fazeis.

[[v11-8-62]]

^<<v11-8-62,62>>^ Então o rei e todo o Israel com ele ofereceram sacrifícios perante o Senhor.

[[v11-8-63]]

^<<v11-8-63,63>>^ Ora, Salomão deu, para o sacrifício pacífico que ofereceu ao Senhor, vinte e dois mil bois e cento e vinte mil ovelhas. Assim o rei e todos os filhos de Israel consagraram a casa do Senhor.

[[v11-8-64]]

^<<v11-8-64,64>>^ No mesmo dia o rei santificou o meio do átrio que estava diante da casa do Senhor; porquanto ali ofereceu o holocausto, a oferta de cereais e a gordura das ofertas pacíficas, porque o altar de bronze que está diante do Senhor era muito pequeno para nele caberem o holocausto, a oferta de cereais, e a gordura das ofertas pacíficas.

[[v11-8-65]]

^<<v11-8-65,65>>^ No mesmo tempo celebrou Salomão a festa, e todo o Israel com ele, uma grande congregação, vinda desde a entrada de Hamate e desde o rio do Egito, perante a face do Senhor nosso Deus, por sete dias, e mais sete dias &#123;catorze dias ao todo&#125;.

[[v11-8-66]]

^<<v11-8-66,66>>^ E no oitavo dia despediu o povo, e todos bendisseram ao rei; então se foram às suas tendas, alegres e de coração contente, por causa de todo o bem que o Senhor fizera a Davi seu servo, e a Israel seu povo.

'''

xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[Próximo Capítulo &#62;]