include::./index.adoc[]

[[v11-17-0]]
=== 1 Reis, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-17-1]]

^<<v11-17-1,1>>^ Então Elias, o tisbita, que habitava em Gileade, disse a Acabe: Vive o Senhor, Deus de Israel, em cuja presença estou, que nestes anos não haverá orvalho nem chuva, senão segundo a minha palavra.

[[v11-17-2]]

^<<v11-17-2,2>>^ Depois veio a Elias a palavra do Senhor, dizendo:

[[v11-17-3]]

^<<v11-17-3,3>>^ Retira-te daqui, vai para a banda de oriente, e esconde-te junto ao ribeiro de Querite, que está ao oriente do Jordão.

[[v11-17-4]]

^<<v11-17-4,4>>^ Beberás do ribeiro; e eu tenho ordenado aos corvos que ali te sustentem.

[[v11-17-5]]

^<<v11-17-5,5>>^ Partiu, pois, e fez conforme a palavra do Senhor; foi habitar junto ao ribeiro de Querite, que está ao oriente do Jordão.

[[v11-17-6]]

^<<v11-17-6,6>>^ E os corvos lhe traziam pão e carne pela manhã, como também pão e carne à tarde; e ele bebia do ribeiro.

[[v11-17-7]]

^<<v11-17-7,7>>^ Mas, decorridos alguns dias, o ribeiro secou, porque não tinha havido chuva na terra.

[[v11-17-8]]

^<<v11-17-8,8>>^ Veio-lhe então a palavra do Senhor, dizendo:

[[v11-17-9]]

^<<v11-17-9,9>>^ Levanta-te, vai para Sarepta, que pertence a Sidom, e habita ali; eis que eu ordenei a uma mulher viúva ali que te sustente.

[[v11-17-10]]

^<<v11-17-10,10>>^ Levantou-se, pois, e foi para Sarepta. Chegando ele à porta da cidade, eis que estava ali uma mulher viúva apanhando lenha; ele a chamou e lhe disse: Traze-me, peço-te, num vaso um pouco d'água, para eu beber.

[[v11-17-11]]

^<<v11-17-11,11>>^ Quando ela ia buscá-la, ele a chamou e lhe disse: Traze-me também um bocado de pão contigo.

[[v11-17-12]]

^<<v11-17-12,12>>^ Ela, porém, respondeu: Vive o Senhor teu Deus, que não tenho nem um bolo, senão somente um punhado de farinha na vasilha, e um pouco de azeite na botija; e eis que estou apanhando uns dois gravetos, para ir prepará-lo para mim e para meu filho, a fim de que o comamos, e morramos.

[[v11-17-13]]

^<<v11-17-13,13>>^ Ao que lhe disse Elias: Não temas; vai, faze como disseste; porém, faze disso primeiro para mim um bolo pequeno, e traze-mo aqui; depois o farás para ti e para teu filho.

[[v11-17-14]]

^<<v11-17-14,14>>^ Pois assim diz o Senhor Deus de Israel: A farinha da vasilha não se acabará, e o azeite da botija não faltará, até o dia em que o Senhor dê chuva sobre a terra.

[[v11-17-15]]

^<<v11-17-15,15>>^ Ela foi e fez conforme a palavra de Elias; e assim comeram, ele, e ela e a sua casa, durante muitos dias.

[[v11-17-16]]

^<<v11-17-16,16>>^ Da vasilha a farinha não se acabou, e da botija o azeite não faltou, conforme a palavra do Senhor, que ele falara por intermédio de Elias.

[[v11-17-17]]

^<<v11-17-17,17>>^ Depois destas coisas aconteceu adoecer o filho desta mulher, dona da casa; e a sua doença se agravou tanto, que nele não ficou mais fôlego.

[[v11-17-18]]

^<<v11-17-18,18>>^ Então disse ela a Elias: Que tenho eu contigo, ó homem de Deus? Vieste tu a mim para trazeres à memória a minha iniqüidade, e matares meu filho?

[[v11-17-19]]

^<<v11-17-19,19>>^ Respondeu-lhe ele: Dá-me o teu filho. E ele o tomou do seu regaço, e o levou para cima, ao quarto onde ele mesmo habitava, e o deitou em sua cama.

[[v11-17-20]]

^<<v11-17-20,20>>^ E, clamando ao Senhor, disse: Ó Senhor meu Deus, até sobre esta viúva, que me hospeda, trouxeste o mal, matando-lhe o filho?

[[v11-17-21]]

^<<v11-17-21,21>>^ Então se estendeu sobre o menino três vezes, e clamou ao Senhor, dizendo: Ó Senhor meu Deus, faze que a vida deste menino torne a entrar nele.

[[v11-17-22]]

^<<v11-17-22,22>>^ O Senhor ouviu a voz de Elias, e a vida do menino tornou a entrar nele, e ele reviveu.

[[v11-17-23]]

^<<v11-17-23,23>>^ E Elias tomou o menino, trouxe-o do quarto à casa, e o entregou a sua mãe; e disse Elias: Vês aí, teu filho vive:

[[v11-17-24]]

^<<v11-17-24,24>>^ Então a mulher disse a Elias: Agora sei que tu és homem de Deus, e que a palavra do Senhor na tua boca é verdade.

'''

xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[&#60; Capítulo Anterior] | <<v11-17-0,Topo>> | xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[Próximo Capítulo &#62;]