include::./index.adoc[]

[[v11-22-0]]
=== 1 Reis, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-22-1]]

^<<v11-22-1,1>>^ Passaram-se três anos sem haver guerra entre a Síria e Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ No terceiro ano, porém, desceu Jeosafá, rei de Judá, a ter com o rei de Israel.

[[v11-22-3]]

^<<v11-22-3,3>>^ E o rei de Israel disse aos seus servos: Não sabeis vós que Ramote-Gileade é nossa, e nós estamos quietos, sem a tomar da mão do rei da Síria?

[[v11-22-4]]

^<<v11-22-4,4>>^ Então perguntou a Jeosafá: Irás tu comigo à peleja, a Ramote-Gileade? Respondeu Jeosafá ao rei de Israel: Como tu és sou eu, o meu povo como o teu povo, e os meus cavalos como os teus cavalos.

[[v11-22-5]]

^<<v11-22-5,5>>^ Disse mais Jeosafá ao rei de Israel: Rogo-te, porém, que primeiro consultes a palavra do Senhor.

[[v11-22-6]]

^<<v11-22-6,6>>^ Então o rei de Israel ajuntou os profetas, cerca de quatrocentos homens, e perguntou-lhes: Irei à peleja contra Ramote-Gileade, ou deixarei de ir? Responderam eles: Sobe, porque o Senhor a entregará nas mãos do rei.

[[v11-22-7]]

^<<v11-22-7,7>>^ Disse, porém, Jeosafá: Não há aqui ainda algum profeta do Senhor, ao qual possamos consultar?

[[v11-22-8]]

^<<v11-22-8,8>>^ Então disse o rei de Israel a Jeosafá: Ainda há um homem por quem podemos consultar ao Senhor-Micaías, filho de Inlá; porém eu o odeio, porque nunca profetiza o bem a meu respeito, mas somente o mal. Ao que disse Jeosafá: Não fale o rei assim.

[[v11-22-9]]

^<<v11-22-9,9>>^ Então o rei de Israel chamou um eunuco, e disse: Traze-me depressa Micaías, filho de Inlá.

[[v11-22-10]]

^<<v11-22-10,10>>^ Ora, o rei de Israel e Jeosafá, rei de Judá, vestidos de seus trajes reais, estavam assentados cada um no seu trono, na praça à entrada da porta de Samária; e todos os profetas profetizavam diante deles.

[[v11-22-11]]

^<<v11-22-11,11>>^ E Zedequias, filho de Quenaaná, fez para si uns chifres de ferro, e disse: Assim diz o Senhor: Com estes ferirás os sírios, até que sejam consumidos.

[[v11-22-12]]

^<<v11-22-12,12>>^ Do mesmo modo também profetizavam todos os profetas, dizendo: Sobe a Ramote-Gileade, e serás bem sucedido; porque o Senhor a entregará nas mãos do rei.

[[v11-22-13]]

^<<v11-22-13,13>>^ O mensageiro que fora chamar Micaías falou-lhe, dizendo: Eis que as palavras dos profetas, a uma voz, são favoráveis ao rei; seja, pois, a tua palavra como a de um deles, e fala o que é bom.

[[v11-22-14]]

^<<v11-22-14,14>>^ Micaías, porém, disse: Vive o Senhor, que o que o Senhor me disser, isso falarei.

[[v11-22-15]]

^<<v11-22-15,15>>^ Quando ele chegou à presença do rei, este lhe disse: Micaías, iremos a Ramote-Gileade à peleja, ou deixaremos de ir? Respondeu-lhe ele: Sobe, e serás bem sucedido, porque o Senhor a entregará nas mãos do rei.

[[v11-22-16]]

^<<v11-22-16,16>>^ E o rei lhe disse: Quantas vezes hei de conjurar-te que não me fales senão a verdade em nome do Senhor?

[[v11-22-17]]

^<<v11-22-17,17>>^ Então disse ele: Vi todo o Israel disperso pelos montes, como ovelhas que não têm pastor; e disse o Senhor: Estes não têm senhor; torne cada um em paz para sua casa.

[[v11-22-18]]

^<<v11-22-18,18>>^ Disse o rei de Israel a Jeosafá: Não te disse eu que ele não profetizaria o bem a meu respeito, mas somente o mal?

[[v11-22-19]]

^<<v11-22-19,19>>^ Micaías prosseguiu: Ouve, pois, a palavra do Senhor! Vi o Senhor assentado no seu trono, e todo o exército celestial em pé junto a ele, à sua direita e à sua esquerda.

[[v11-22-20]]

^<<v11-22-20,20>>^ E o Senhor perguntou: Quem induzirá Acabe a subir, para que caia em Ramote-Gileade? E um respondia de um modo, e outro de outro.

[[v11-22-21]]

^<<v11-22-21,21>>^ Então saiu um espírito, apresentou-se diante do Senhor, e disse: Eu o induzirei. E o Senhor lhe perguntou: De que modo?

[[v11-22-22]]

^<<v11-22-22,22>>^ Respondeu ele: Eu sairei, e serei um espírito mentiroso na boca de todos os seus profetas. Ao que disse o Senhor: Tu o induzirás, e prevalecerás; sai, e faze assim.

[[v11-22-23]]

^<<v11-22-23,23>>^ Agora, pois, eis que o Senhor pôs um espírito mentiroso na boca dentes da casa dele; sim, tornarei a tua casa como a casa de respeito de ti.

[[v11-22-24]]

^<<v11-22-24,24>>^ Então Zedequias, filho de Quenaaná, chegando-se, feriu a Micaías na face e disse: Por onde passou de mim o Espírito do Senhor para falar a ti?

[[v11-22-25]]

^<<v11-22-25,25>>^ Respondeu Micaías: Eis que tu o verás naquele dia, quando entrares numa câmara interior, para te esconderes.

[[v11-22-26]]

^<<v11-22-26,26>>^ Então disse o rei de Israel: Tomai Micaías, e tornai a levá-lo a Amom, o governador da cidade, e a Joás, filho do rei,

[[v11-22-27]]

^<<v11-22-27,27>>^ dizendo-lhes: Assim diz o rei: Metei este homem no cárcere, e sustentai-o a pão e água, até que eu volte em paz.

[[v11-22-28]]

^<<v11-22-28,28>>^ Replicou Micaías: Se tu voltares em paz, o senhor não tem falado por mim. Disse mais: Ouvi, povos todos!

[[v11-22-29]]

^<<v11-22-29,29>>^ Assim o rei de Israel e Jeosafá, rei de Judá, subiram a Ramote-Gileade.

[[v11-22-30]]

^<<v11-22-30,30>>^ E disse o rei de Israel a Jeosafá: Eu me disfarçarei, e entrarei na peleja; tu, porém, veste os teus trajes reais. Disfarçou-se, pois, o rei de Israel, e entrou na peleja.

[[v11-22-31]]

^<<v11-22-31,31>>^ Ora, o rei da Síria tinha ordenado aos capitães dos carros, que eram trinta e dois, dizendo: Não pelejeis nem contra pequeno nem contra grande, senão só contra o rei de Israel.

[[v11-22-32]]

^<<v11-22-32,32>>^ E sucedeu que, vendo os capitães dos carros a Jeosafá, disseram: Certamente este é o rei de Israel. Viraram-se, pois, para pelejar com ele, e Jeosafá gritou.

[[v11-22-33]]

^<<v11-22-33,33>>^ Vendo os capitães dos carros que não era o rei de Israel, deixaram de segui-lo.

[[v11-22-34]]

^<<v11-22-34,34>>^ Então um homem entesou o seu arco, e atirando a esmo, feriu o rei de Israel por entre a couraça e a armadura abdominal. Pelo que ele disse ao seu carreteiro: Dá volta, e tira-me do exército, porque estou gravemente ferido.

[[v11-22-35]]

^<<v11-22-35,35>>^ E a peleja tornou-se renhida naquele dia; contudo o rei foi sustentado no carro contra os sírios; porém à tarde ele morreu; e o sangue da ferida corria para o fundo do carro.

[[v11-22-36]]

^<<v11-22-36,36>>^ Ao pôr do sol passou pelo exército a palavra: Cada um para a sua cidade, e cada um para a sua terra!

[[v11-22-37]]

^<<v11-22-37,37>>^ Morreu, pois, o rei, e o levaram para Samária, e ali o sepultaram.

[[v11-22-38]]

^<<v11-22-38,38>>^ E lavaram o seu carro junto ao tanque de Samária, e os cães lamberam-lhe o sangue, conforme a palavra que o Senhor tinha dito; ora, as prostitutas se banhavam ali.

[[v11-22-39]]

^<<v11-22-39,39>>^ Quanto ao restante dos atos de Acabe, e a tudo quanto fez, e à casa de marfim que construiu, e a todas as cidades que edificou, porventura não estão escritos no livro das crônicas dos reis de Israel?

[[v11-22-40]]

^<<v11-22-40,40>>^ Assim dormiu Acabe com seus pais. E Acazias, seu filho, reinou em seu lugar.

[[v11-22-41]]

^<<v11-22-41,41>>^ Ora, Jeosafá, filho de Asa, começou a reinar sobre Judá no quarto ano de Acabe, rei de Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ Era Jeosafá da idade de trinta e cinco anos quando começou a reinar, e reinou vinte e cinco anos em Jerusalém. Era o nome de sua mãe Azuba, filha de Sili.

[[v11-22-43]]

^<<v11-22-43,43>>^ E andou em todos os caminhos de seu pai Asa; não se desviou deles, mas fez o que era reto aos olhos do Senhor.

[[v11-22-44]]

^<<v11-22-44,44>>^ Todavia os altos não foram tirados e o povo ainda sacrificava e queimava incenso nos altos.

[[v11-22-45]]

^<<v11-22-45,45>>^ E Jeosafá teve paz com o rei de Israel.

[[v11-22-46]]

^<<v11-22-46,46>>^ Quanto ao restante dos atos de Jeosafá, e ao poder que mostrou, e como guerreou, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v11-22-47]]

^<<v11-22-47,47>>^ Também expulsou da terra o restante dos sodomitas, que ficaram nos dias de seu pai Asa

[[v11-22-48]]

^<<v11-22-48,48>>^ Nesse tempo não havia rei em Edom; um vice-rei governava.

[[v11-22-49]]

^<<v11-22-49,49>>^ E Jeosafá construiu navios de Társis para irem a Ofir em busca de ouro; porém não foram, porque os navios se quebraram em Eziom-Geber.

[[v11-22-50]]

^<<v11-22-50,50>>^ Então Acazias, filho de Acabe, disse a Jeosafá: Vão os meus servos com os teus servos nos navios. Jeosafá, porém, não quis.

[[v11-22-51]]

^<<v11-22-51,51>>^ Depois Jeosafá dormiu com seus pais, e foi sepultado junto a eles na cidade de Davi, seu pai. E em seu lugar reinou seu filho Jeorão.

[[v11-22-52]]

^<<v11-22-52,52>>^ Ora, Acazias, filho de Acabe, começou a reinar em Samaria no ano dezessete de Jeosafá, rei de Judá, e reinou dois anos sobre Israel.

[[v11-22-53]]

^<<v11-22-53,53>>^ E fez o que era mau aos olhos do Senhor; porque andou no caminho de seu pai, como também no caminho de sua mãe, e no caminho de Jeroboão, filho de Nebate, que fez Israel pecar.

[[v11-22-54]]

^<<v11-22-54,54>>^ Serviu a Baal, e o adorou, provocando à ira o Senhor Deus de Israel, conforme tudo quanto seu pai fizera.

'''

xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[Próximo Capítulo &#62;]