include::./index.adoc[]

[[v11-3-0]]
=== 1 Reis, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-3-1]]

^<<v11-3-1,1>>^ Ora, Salomão aparentou-se com Faraó, rei do Egito, pois tomou por mulher a filha dele; e a trouxe à cidade de Davi, até que acabasse de edificar a sua casa, e a casa do Senhor, e a muralha de Jerusalém em redor.

[[v11-3-2]]

^<<v11-3-2,2>>^ Entretanto o povo oferecia sacrifícios sobre os altos, porque até aqueles dias ainda não se havia edificado casa ao nome do Senhor.

[[v11-3-3]]

^<<v11-3-3,3>>^ E Salomão amava ao Senhor, andando nos estatutos de Davi, seu pai; exceto que nos altos oferecia sacrifícios e queimava incenso.

[[v11-3-4]]

^<<v11-3-4,4>>^ Foi, pois, o rei a Gibeão para oferecer sacrifícios ali, porque aquele era o principal dentre os altos; mil holocaustos sacrificou Salomão naquele altar.

[[v11-3-5]]

^<<v11-3-5,5>>^ Em Gibeão apareceu o Senhor a Salomão de noite em sonhos, e disse-lhe: Pede o que queres que eu te dê.

[[v11-3-6]]

^<<v11-3-6,6>>^ Respondeu Salomão: De grande benevolência usaste para com teu servo Dai, meu pai, porquanto ele andou diante de ti em verdade, em justiça, e em retidão de coração para contigo; e guardaste-lhe esta grande benevolência, e lhe deste um filho, que se assentasse no seu trono, como se vê neste dia.

[[v11-3-7]]

^<<v11-3-7,7>>^ Agora, pois, ó Senhor meu Deus, tu fizeste reinar teu servo em lugar de Davi, meu pai. E eu sou apenas um menino pequeno; não sei como sair, nem como entrar.

[[v11-3-8]]

^<<v11-3-8,8>>^ Teu servo está no meio do teu povo que elegeste, povo grande, que nem se pode contar, nem numerar, pela sua multidão.

[[v11-3-9]]

^<<v11-3-9,9>>^ Dá, pois, a teu servo um coração entendido para julgar o teu povo, para que prudentemente discirna entre o bem e o mal; porque, quem poderia julgar a este teu tão grande povo?

[[v11-3-10]]

^<<v11-3-10,10>>^ E pareceu bem aos olhos do Senhor o ter Salomão pedido tal coisa.

[[v11-3-11]]

^<<v11-3-11,11>>^ Pelo que Deus lhe disse: Porquanto pediste isso, e não pediste para ti muitos dias, nem riquezas, nem a vida de teus inimigos, mas pediste entendimento para discernires o que é justo,

[[v11-3-12]]

^<<v11-3-12,12>>^ eis que faço segundo as tuas palavras. Eis que te dou um coração tão sábio e entendido, que antes de ti teu igual não houve, e depois de ti teu igual não se levantará.

[[v11-3-13]]

^<<v11-3-13,13>>^ Também te dou o que não pediste, assim riquezas como glória; de modo que não haverá teu igual entre os reis, por todos os teus dias.

[[v11-3-14]]

^<<v11-3-14,14>>^ E ainda, se andares nos meus caminhos, guardando os meus estatutos e os meus mandamentos, como andou Davi,

[[v11-3-15]]

^<<v11-3-15,15>>^ Então Salomão acordou, e eis que era sonho. E, voltando ele a Jerusalém, pôs-se diante da arca do pacto do Senhor, sacrificou holocaustos e preparou sacrifícios pacíficos, e deu um banquete a todos os seus servos.

[[v11-3-16]]

^<<v11-3-16,16>>^ Então vieram duas mulheres prostitutas ter com o rei, e se puseram diante dele.

[[v11-3-17]]

^<<v11-3-17,17>>^ E disse-lhe uma das mulheres: Ah, meu senhor! eu e esta mulher moramos na mesma casa; e tive um filho, estando com ela naquela casa.

[[v11-3-18]]

^<<v11-3-18,18>>^ E sucedeu que, no terceiro dia depois de meu parto, também esta mulher teve um filho. Estávamos juntas; nenhuma pessoa estranha estava conosco na casa; somente nós duas estávamos ali.

[[v11-3-19]]

^<<v11-3-19,19>>^ Ora, durante a noite morreu o filho desta mulher, porquanto se deitara sobre ele.

[[v11-3-20]]

^<<v11-3-20,20>>^ E ela se levantou no decorrer da noite, tirou do meu lado o meu filho, enquanto a tua serva dormia, e o deitou no seu seio, e a seu filho morto deitou-o no meu seio.

[[v11-3-21]]

^<<v11-3-21,21>>^ Quando me levantei pela manhã, para dar de mamar a meu filho, eis que estava morto; mas, atentando eu para ele à luz do dia, eis que não era o filho que me nascera.

[[v11-3-22]]

^<<v11-3-22,22>>^ Então disse a outra mulher: Não, mas o vivo é meu filho, e teu filho o morto. Replicou a primeira: Não; o morto é teu filho, e meu filho o vivo. Assim falaram perante o rei.

[[v11-3-23]]

^<<v11-3-23,23>>^ Então disse o rei: Esta diz : Este que vive é meu filho, e teu filho o morto; e esta outra diz: Não; o morto é teu filho, e meu filho o vivo.

[[v11-3-24]]

^<<v11-3-24,24>>^ Disse mais o rei: Trazei-me uma espada. E trouxeram uma espada diante dele.

[[v11-3-25]]

^<<v11-3-25,25>>^ E disse o rei: Dividi em duas partes o menino vivo, e dai a metade a uma, e metade a outra.

[[v11-3-26]]

^<<v11-3-26,26>>^ Mas a mulher cujo filho em suas entranhas se lhe enterneceram por seu filho&#125;, e disse: Ah, meu senhor! dai-lhe o menino vivo, e de modo nenhum o mateis. A outra, porém, disse: Não será meu, nem teu; dividi-o.

[[v11-3-27]]

^<<v11-3-27,27>>^ Respondeu, então, o rei: Dai à primeira o menino vivo, e de modo nenhum o mateis; ela é sua mãe.

[[v11-3-28]]

^<<v11-3-28,28>>^ E todo o Israel ouviu a sentença que o rei proferira, e temeu ao rei; porque viu que havia nele a sabedoria de Deus para fazer justiça.

'''

xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[Próximo Capítulo &#62;]