include::./index.adoc[]

[[v11-7-0]]
=== 1 Reis, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-7-1]]

^<<v11-7-1,1>>^ Salomão edificou também a sua casa, levando treze anos para acabá-la.

[[v11-7-2]]

^<<v11-7-2,2>>^ Edificou ainda a casa do bosque de Líbano, de cem côvados de comprimento, cinqüenta de largura e trinta de altura, sobre quatro ordens de colunas de cedros, e vigas de cedro sobre as colunas.

[[v11-7-3]]

^<<v11-7-3,3>>^ E por cima estava coberta de cedro sobre as câmaras, que estavam sobre quarenta e cinco colunas, quinze em cada ordem.

[[v11-7-4]]

^<<v11-7-4,4>>^ E havia três ordens de janelas, e uma janela estava defronte da outra janela, em três fileiras.

[[v11-7-5]]

^<<v11-7-5,5>>^ Todas as portas e esquadrias eram quadradas; e uma janela estava defronte da outra, em três fileiras.

[[v11-7-6]]

^<<v11-7-6,6>>^ Depois fez um pórtico de colunas, de cinqüenta côvados de comprimento e trinta de largura; e defronte dele outro pórtico, com suas respectivas colunas e degraus.

[[v11-7-7]]

^<<v11-7-7,7>>^ Também fez o pórtico para o trono onde julgava, isto é, o pórtico do juízo, o qual era coberto de cedro desde o soalho até o teto.

[[v11-7-8]]

^<<v11-7-8,8>>^ E em sua casa, em que morava, havia outro átrio por dentro do pórtico, de obra semelhante à deste; também para a filha de Faraó, que ele tomara por mulher, fez uma casa semelhante àquele pórtico.

[[v11-7-9]]

^<<v11-7-9,9>>^ Todas estas casas eram de pedras de grande preço, cortadas sob medida, tendo as suas faces por dentro e por fora serradas à serra; e isto desde o fundamento até as beiras do teto, e por fora até o grande átrio.

[[v11-7-10]]

^<<v11-7-10,10>>^ Os fundamentos eram de pedras de grande preço, pedras grandes, de dez e de oito côvados,

[[v11-7-11]]

^<<v11-7-11,11>>^ e por cima delas havia pedras de grande preço, lavradas sob medida, e madeira de cedro.

[[v11-7-12]]

^<<v11-7-12,12>>^ O átrio grande tinha em redor três ordens de pedras lavradas, com uma ordem de vigas de cedro; assim era também o átrio interior da casa do Senhor e o pórtico da casa.

[[v11-7-13]]

^<<v11-7-13,13>>^ O rei Salomão mandou trazer de Tiro a Hirão.

[[v11-7-14]]

^<<v11-7-14,14>>^ Era ele filho de uma viúva, da tribo de Naftali, e fora seu pai um homem de Tiro, que trabalhava em bronze; ele era cheio de sabedoria, de entendimento e de ciência para fazer toda sorte de obras de bronze. Este veio ter com o rei Salomão, e executou todas as suas obras.

[[v11-7-15]]

^<<v11-7-15,15>>^ Formou as duas colunas de bronze; a altura de cada coluna era de dezoito côvados; e um fio de doze côvados era a medida da circunferência de cada uma das colunas;

[[v11-7-16]]

^<<v11-7-16,16>>^ também fez dois capitéis de bronze fundido para pôr sobre o alto das colunas; de cinco côvados era a altura dum capitel, e de cinco côvados também a altura do outro.

[[v11-7-17]]

^<<v11-7-17,17>>^ Havia redes de malha, e grinaldas entrelaçadas, para os capitéis que estavam sobre o alto das colunas: sete para um capitel e sete para o outro.

[[v11-7-18]]

^<<v11-7-18,18>>^ Assim fez as colunas; e havia duas fileiras de romãs em redor sobre uma rede, para cobrir os capitéis que estavam sobre o alto das colunas; assim fez com um e outro capitel.

[[v11-7-19]]

^<<v11-7-19,19>>^ Os capitéis que estavam sobre o alto das colunas, no pórtico, figuravam lírios, e eram de quatro côvados.

[[v11-7-20]]

^<<v11-7-20,20>>^ Os capitéis, pois, sobre as duas colunas estavam também justamente em cima do bojo que estava junto à rede; e havia duzentas romãs, em fileiras em redor, sobre um e outro capitel.

[[v11-7-21]]

^<<v11-7-21,21>>^ Depois levantou as colunas no pórtico do templo; levantando a coluna direita, pôs-lhe o nome de Jaquim; e levantando a coluna esquerda, pôs-lhe o nome de Boaz.

[[v11-7-22]]

^<<v11-7-22,22>>^ Sobre o alto das colunas estava a obra de lírios. E assim se acabou a obra das colunas.

[[v11-7-23]]

^<<v11-7-23,23>>^ Fez também o mar de fundição; era redondo e media dez côvados duma borda à outra, cinco côvados de altura e trinta de circunferência.

[[v11-7-24]]

^<<v11-7-24,24>>^ Por baixo da sua borda em redor havia betões que o cingiam, dez em cada côvado, cercando aquele mar em redor; duas eram as fileiras destes botões, fundidas juntamente com o mar.

[[v11-7-25]]

^<<v11-7-25,25>>^ E firmava-se sobre doze bois, três dos quais olhavam para o norte, três para o ocidente, três para o sul e três para o oriente; e o mar descansava sobre eles, e as partes posteriores deles estavam para a banda de dentro.

[[v11-7-26]]

^<<v11-7-26,26>>^ A sua grossura era de três polegadas, e a borda era como a de um copo, como flor de lírio; ele levava dois mil batos.

[[v11-7-27]]

^<<v11-7-27,27>>^ Fez também as dez bases de bronze; cada uma tinha quatro côvados de comprimento, quatro de largura e três de altura.

[[v11-7-28]]

^<<v11-7-28,28>>^ E a estrutura das bases era esta: tinham elas almofadas, as quais estavam entre as junturas;

[[v11-7-29]]

^<<v11-7-29,29>>^ e sobre as almofadas que estavam entre as junturas havia leões, bois, e querubins, bem como os havia sobre as junturas em cima; e debaixo dos leões e dos bois havia grinaldas pendentes.

[[v11-7-30]]

^<<v11-7-30,30>>^ Cada base tinha quatro rodas de bronze, e eixos de bronze; e os seus quatro cantos tinham suportes; debaixo da pia estavam estes suportes de fundição, tendo eles grinaldas de cada lado.

[[v11-7-31]]

^<<v11-7-31,31>>^ A sua boca, dentro da coroa, e em cima, era de um côvado; e era redonda segundo a obra dum pedestal, de côvado e meio; e também sobre a sua boca havia entalhes, e as suas almofadas eram quadradas, não redondas.

[[v11-7-32]]

^<<v11-7-32,32>>^ As quatro rodas estavam debaixo das almofadas, e os seus eixos estavam na base; e era a altura de cada roda de côvado e meio.

[[v11-7-33]]

^<<v11-7-33,33>>^ O feitio das rodas era como o de uma roda de carro; seus eixos, suas cambas, seus raios e seus cubos, todos eram fundidos.

[[v11-7-34]]

^<<v11-7-34,34>>^ Havia quatro suportes aos quatro cantos de cada base, os quais faziam parte da própria base.

[[v11-7-35]]

^<<v11-7-35,35>>^ No alto de cada base havia um cinto redondo, de meio côvado de altura; também sobre o topo de cada base havia esteios e almofadas que faziam parte dela.

[[v11-7-36]]

^<<v11-7-36,36>>^ E nas placas dos seus esteios e nas suas almofadas lavrou querubins, leões e palmas, segundo o espaço que havia em cada uma, com grinaldas em redor.

[[v11-7-37]]

^<<v11-7-37,37>>^ Deste modo fez as dez bases: todas com a mesma fundição, a mesma medida e o mesmo entalhe.

[[v11-7-38]]

^<<v11-7-38,38>>^ Também fez dez pias de bronze; em cada uma cabiam quarenta batos, e cada pia era de quatro côvados; e cada uma delas estava sobre uma das dez bases.

[[v11-7-39]]

^<<v11-7-39,39>>^ E pôs cinco bases à direita da casa, e cinco à esquerda; porém o mar pôs ao lado direito da casa para a banda do oriente, na direção do sul.

[[v11-7-40]]

^<<v11-7-40,40>>^ Hirão fez também as caldeiras, as pás e as bacias; assim acabou de fazer toda a obra que executou para o rei Salomão, para a casa do Senhor,

[[v11-7-41]]

^<<v11-7-41,41>>^ a saber: as duas colunas, os globos dos capitéis que estavam sobre o alto das colunas, e as duas redes para cobrir os dois globos dos capitéis que estavam sobre o alto das colunas,

[[v11-7-42]]

^<<v11-7-42,42>>^ e as quatrocentas romãs para as duas redes, a saber, duas carreiras de romãs para cada rede, para cobrirem os dois globos dos capitéis que estavam em cima das colunas;

[[v11-7-43]]

^<<v11-7-43,43>>^ as dez bases, e as dez pias sobre as bases;

[[v11-7-44]]

^<<v11-7-44,44>>^ o mar, e os doze bois debaixo do mesmo;

[[v11-7-45]]

^<<v11-7-45,45>>^ as caldeiras, as pás e as bacias; todos estes objetos que Hirão fez para o rei Salomão, para a casa do Senhor, eram de bronze polido.

[[v11-7-46]]

^<<v11-7-46,46>>^ O rei os fez fundir na planície do Jordão, num terreno argiloso que havia entre Sucote e Zaretã.

[[v11-7-47]]

^<<v11-7-47,47>>^ E Salomão deixou de pesar esses objetos devido ao seu excessivo número; não se averiguou o peso do bronze.

[[v11-7-48]]

^<<v11-7-48,48>>^ Também fez Salomão todos os utensílios para a casa do Senhor: o altar de ouro, e a mesa de ouro, sobre a qual estavam os pães da proposição;

[[v11-7-49]]

^<<v11-7-49,49>>^ os castiçais, cinco à direita e cinco esquerda, diante do oráculo, de ouro puro; as flores, as lâmpadas e as tenazes, também de ouro;

[[v11-7-50]]

^<<v11-7-50,50>>^ e as taças, as espevitadeiras, as bacias, as colheres e os braseiros, de ouro puro; e os gonzos para as portas da casa interior, para o lugar santíssimo, e os das portas da casa, isto é, do templo, também de ouro.

[[v11-7-51]]

^<<v11-7-51,51>>^ Assim se acabou toda a obra que o rei Salomão fez para a casa do Senhor. Então trouxe Salomão as coisas que seu pai Davi tinha consagrado, a saber, a prata, o ouro e os vasos; e os depositou nos tesouros da casa do senhor.

'''

xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[&#60; Capítulo Anterior] | <<v11-7-0,Topo>> | xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[Próximo Capítulo &#62;]