include::./index.adoc[]

[[v11-1-0]]
=== 1 Reis, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-1-1]]

^<<v11-1-1,1>>^ Ora, o rei Davi era já velho, de idade mui avançada; e por mais que o cobrissem de roupas não se aquecia.

[[v11-1-2]]

^<<v11-1-2,2>>^ Disseram-lhe, pois, os seus servos: Busque-se para o rei meu senhor uma jovem donzela, que esteja perante o rei, e tenha cuidado dele; e durma no seu seio, para que o rei meu senhor se aqueça.

[[v11-1-3]]

^<<v11-1-3,3>>^ Assim buscaram por todos os termos de Israel uma jovem formosa; e acharam Abisague, a sunamita, e a trouxeram ao rei.

[[v11-1-4]]

^<<v11-1-4,4>>^ Era a jovem sobremaneira formosa; e cuidava do rei, e o servia; porém o rei não a conheceu.

[[v11-1-5]]

^<<v11-1-5,5>>^ Então Adonias, filho de Hagite, se exaltou e disse: Eu reinarei. E preparou para si carros e cavaleiros, e cinqüenta homens que corressem adiante dele.

[[v11-1-6]]

^<<v11-1-6,6>>^ Ora, nunca seu pai o tinha contrariado, dizendo: Por que fizeste assim? Além disso, era ele muito formoso de parecer; e era mais moço do que Absalão.

[[v11-1-7]]

^<<v11-1-7,7>>^ E teve entendimento com Joabe, filho de Zeruia, e com o sacerdote Abiatar, os quais aderiram a ele e o ajudavam.

[[v11-1-8]]

^<<v11-1-8,8>>^ Mas Zadoque, o sacerdote, e Benaías, filho de Jeoiada, e Natã, o profeta, e Simei, e Rei, e os valentes que Davi tinha, não eram por Adonias.

[[v11-1-9]]

^<<v11-1-9,9>>^ Adonias matou ovelhas, bois e animais cevados, junto à pedra de Zoelete, que está perto de En-Rogel; e convidou a todos os seus irmãos, os filhos do rei, e a todos os homens de Judá, servos do rei;

[[v11-1-10]]

^<<v11-1-10,10>>^ porém a Natã, o profeta, e a Benaías, e aos valentes, e a Salomão, seu irmão, não os convidou.

[[v11-1-11]]

^<<v11-1-11,11>>^ Então falou Natã a Bate-Seba, mãe de Salomão, dizendo: Não ouviste que Adonias, filho de Hagite, reina? e que nosso senhor Davi não o sabe?

[[v11-1-12]]

^<<v11-1-12,12>>^ Vem, pois, agora e deixa-me dar-te um conselho, para que salves a tua vida, e a de teu filho Salomão.

[[v11-1-13]]

^<<v11-1-13,13>>^ Vai à presença do rei Davi, e dize-lhe: Não juraste, ó rei meu senhor, à tua serva, dizendo: Certamente teu filho Salomão reinará depois de mim, e se assentará no meu trono? Por que, pois, reina Adonias?

[[v11-1-14]]

^<<v11-1-14,14>>^ Eis que, estando tu ainda a falar com o rei, eu também entrarei depois de ti, e confirmarei as tuas palavras.

[[v11-1-15]]

^<<v11-1-15,15>>^ Foi, pois, Bate-Seba à presença do rei na sua câmara. Ele era mui velho; e Abisague, a sunamita, o servia.

[[v11-1-16]]

^<<v11-1-16,16>>^ Bate-Seba inclinou a cabeça, e se prostrou perante o rei. Então o rei lhe perguntou: Que queres?

[[v11-1-17]]

^<<v11-1-17,17>>^ Respondeu-lhe ela: Senhor meu, tu juraste à tua serva pelo Senhor teu Deus, dizendo: Salomão, teu filho, reinará depois de mim, e se assentará no meu trono.

[[v11-1-18]]

^<<v11-1-18,18>>^ E agora eis que Adonias reina; e tu, ó rei meu senhor, não o sabes.

[[v11-1-19]]

^<<v11-1-19,19>>^ Ele matou bois, animais cevados e ovelhas em abundância, e convidou a todos os filhos do rei, e a Abiatar, o sacerdote, e a Joabe, general do exército; mas a teu servo Salomão não o convidou.

[[v11-1-20]]

^<<v11-1-20,20>>^ Mas, ó rei meu senhor, os olhos de todo o Israel estão sobre ti, para que lhes declares quem há de assentar-se no teu trono depois de ti.

[[v11-1-21]]

^<<v11-1-21,21>>^ Doutro modo sucederá que, quando o rei meu senhor dormir com seus pais, eu e Salomão meu filho seremos tidos por ofensores.

[[v11-1-22]]

^<<v11-1-22,22>>^ Enquanto ela ainda falava com o rei, eis que chegou o profeta Natã.

[[v11-1-23]]

^<<v11-1-23,23>>^ E o fizeram saber ao rei, dizendo: Eis aí está o profeta Natã. Entrou Natã à presença do rei, inclinou-se perante ele com o rosto em terra,

[[v11-1-24]]

^<<v11-1-24,24>>^ e disse: ó rei meu senhor, acaso disseste: Adonias reinará depois de mim, e se assentará no meu trono?

[[v11-1-25]]

^<<v11-1-25,25>>^ Pois ele hoje desceu, e matou bois, animais cevados e ovelhas em abundância, e convidou a todos os filhos do rei, e aos chefes do exército, e ao sacerdote Abiatar; e eis que comem e bebem perante ele, e dizem: Viva o rei Adonias!

[[v11-1-26]]

^<<v11-1-26,26>>^ Porém a mim teu servo, e ao sacerdote Zadoque, e a Benaías, filho de Jeoiada, e ao teu servo Salomão, não convidou.

[[v11-1-27]]

^<<v11-1-27,27>>^ Foi feito isso da parte do rei meu senhor? e não fizeste saber a teu servo quem havia de assentar-se no teu trono depois de ti?

[[v11-1-28]]

^<<v11-1-28,28>>^ Respondeu o rei Davi: Chamai-me a Bate-Seba. E ela entrou à presença do rei, e ficou de pé diante dele.

[[v11-1-29]]

^<<v11-1-29,29>>^ Então o rei jurou, dizendo: Vive o Senhor, o qual remiu a minha alma de toda a angústia,

[[v11-1-30]]

^<<v11-1-30,30>>^ que, assim como te jurei pelo Senhor Deus de Israel, dizendo: Teu filho Salomão há de reinar depois de mim, e ele se assentará no meu trono, em meu lugar; assim mesmo o cumprirei hoje.

[[v11-1-31]]

^<<v11-1-31,31>>^ Então Bate-Seba, inclinando-se com o rosto em terra perante o rei, fez-lhe reverência e disse: Viva para sempre o rei Davi meu senhor!

[[v11-1-32]]

^<<v11-1-32,32>>^ Depois disse o rei Davi: Chamai-me a Zadoque, o sacerdote, e a Natã, o profeta, e a Benaías, filho de Jeoiada. E estes entraram à presença do rei.

[[v11-1-33]]

^<<v11-1-33,33>>^ E o rei lhes disse: Tomai convosco os servos de vosso senhor, fazei montar meu filho Salomão na minha mula, e levai-o a Giom.

[[v11-1-34]]

^<<v11-1-34,34>>^ E Zadoque, o sacerdote, com Natã, o profeta, ali o ungirão rei sobre Israel. E tocareis a trombeta, e direis: Viva o rei Salomão!

[[v11-1-35]]

^<<v11-1-35,35>>^ Então subireis após ele, e ele virá e se assentará no meu trono; pois reinará em meu lugar, porquanto o tenho designado para ser príncipe sobre Israel e sobre Judá.

[[v11-1-36]]

^<<v11-1-36,36>>^ Ao que Benaías, filho de Jeoiada, respondeu ao rei, dizendo: Amém; assim o diga também o Senhor Deus do rei meu senhor.

[[v11-1-37]]

^<<v11-1-37,37>>^ Como o Senhor foi com o rei meu senhor, assim seja ele com Salomão, e faça que o seu trono seja maior do que o trono do rei Davi meu senhor.

[[v11-1-38]]

^<<v11-1-38,38>>^ Pelo que desceram Zadoque, o sacerdote, e Natã, o profeta, e Benaías, filho de Jeoiada, e os quereteus, e os peleteus, e fizeram montar Salomão na mula que era do rei Davi, e o levaram a Giom.

[[v11-1-39]]

^<<v11-1-39,39>>^ Então Zadoque, o sacerdote, tomou do tabernáculo o vaso do azeite e ungiu a Salomão. Então tocaram a trombeta, e todo o povo disse: Viva o rei Salomão!

[[v11-1-40]]

^<<v11-1-40,40>>^ E todo o povo subiu após ele, tocando flauta e alegrando-se sobremaneira, de modo que a terra retiniu com o seu clamor.

[[v11-1-41]]

^<<v11-1-41,41>>^ Adonias e todos os convidados que estavam com ele o ouviram, ao acabarem de comer. E ouvindo Joabe o soar das trombetas, disse: Que quer dizer este alvoroço na cidade?

[[v11-1-42]]

^<<v11-1-42,42>>^ Ele ainda estava falando, quando chegou Jônatas, filho de Abiatar, o sacerdote; e disse Adonias: Entra, porque és homem de bem, e trazes boas novas.

[[v11-1-43]]

^<<v11-1-43,43>>^ Respondeu Jônatas a Adonias: Deveras! O rei Davi, nosso senhor, constituiu rei a Salomão.

[[v11-1-44]]

^<<v11-1-44,44>>^ E o rei enviou com ele Zadoque, o sacerdote, e Natã, o profeta, e Benaías, filho de Jeoiada, os quereteus e os peleteus; e eles o fizeram montar na mula do rei.

[[v11-1-45]]

^<<v11-1-45,45>>^ E Zadoque, o sacerdote, e Natã, o profeta, ungiram-no rei em Giom; e dali subiram cheios de alegria, e a cidade está alvoroçada. Este é o clamor que ouvistes.

[[v11-1-46]]

^<<v11-1-46,46>>^ E Salomão já está assentado no trono do reino.

[[v11-1-47]]

^<<v11-1-47,47>>^ Além disso os servos do rei vieram abençoar o nosso senhor, o rei Davi, dizendo: Faça teu Deus o nome de Salomão mais célebre do que o teu nome, e faça o seu trono maior do que o teu trono. E o rei se inclinou no leito.

[[v11-1-48]]

^<<v11-1-48,48>>^ Também assim falou o rei: Bendito o Senhor Deus de Israel, que hoje tem dado quem se assente no meu trono, e que os meus olhos o vissem.

[[v11-1-49]]

^<<v11-1-49,49>>^ Então, tomados de pavor, levantaram-se todos os convidados que estavam com Adonias, e cada qual se foi seu caminho.

[[v11-1-50]]

^<<v11-1-50,50>>^ Adonias, porém, temeu a Salomão e, levantando-se, foi apegar-se às pontas do altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ E foi dito a Salomão: Eis que Adonias teme ao rei Salomão; pois que se apegou às pontas do altar, dizendo: Jure-me hoje o rei Salomão que não matará o seu servo à espada.

[[v11-1-52]]

^<<v11-1-52,52>>^ Ao que disse Salomão: Se ele se houver como homem de bem, nem um só de seus cabelos cairá em terra; se, porém, se houver dolosamente, morrerá.

[[v11-1-53]]

^<<v11-1-53,53>>^ Então o rei Salomão deu ordem, e tiraram Adonias do altar. E vindo ele, inclinou-se perante o rei Salomão, o qual lhe disse: Vai para tua casa.

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]