include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-10-1]]

^<<v11-10-1,1>>^ Tendo a rainha de Sabá ouvido da fama de Salomão, no que concerne ao nome do Senhor, veio prová-lo por enigmas.

[[v11-10-2]]

^<<v11-10-2,2>>^ E chegou a Jerusalém com uma grande comitiva, com camelos carregados de especiarias, e muitíssimo ouro, e pedras preciosas; e, tendo-se apresentado a Salomão, conversou com ele acerca de tudo o que tinha na coração.

[[v11-10-3]]

^<<v11-10-3,3>>^ E Salomão lhe deu resposta a todas as suas perguntas; não houve nada que o rei não lhe soubesse explicar.

[[v11-10-4]]

^<<v11-10-4,4>>^ Vendo, pois, a rainha de Sabá toda a sabedoria de Salomão, a casa que edificara,

[[v11-10-5]]

^<<v11-10-5,5>>^ as iguarias da sua mesa, o assentar dos seus oficiais, as funções e os trajes dos seus servos, e os seus copeiros, e os holocaustos que ele oferecia na casa do Senhor, ficou estupefata,

[[v11-10-6]]

^<<v11-10-6,6>>^ e disse ao rei: Era verdade o que ouvi na minha terra, acerca dos teus feitos e da tua sabedoria.

[[v11-10-7]]

^<<v11-10-7,7>>^ Contudo eu não o acreditava, até que vim e os meus olhos o viram. Eis que não me disseram metade; sobrepujaste em sabedoria e bens a fama que ouvi.

[[v11-10-8]]

^<<v11-10-8,8>>^ Bem-aventurados os teus homens! Bem-aventuradas estes teus servos, que estão sempre diante de ti, que ouvem a tua sabedoria!

[[v11-10-9]]

^<<v11-10-9,9>>^ Bendito seja o Senhor teu Deus, que se agradou de ti e te colocou no trono de Israel! Porquanto o Senhor amou Israel para sempre, por isso te estabeleceu rei, para executares juízo e justiça.

[[v11-10-10]]

^<<v11-10-10,10>>^ E deu ela ao rei cento e vinte talentos de ouro, especiarias em grande quantidade e pedras preciosas; nunca mais apareceu tamanha abundância de especiarias como a que a rainha de Sabá deu ao rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ Também a frota de Hirão, que de Ofir trazia ouro, trouxe dali madeira de almugue em quantidade, e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ Desta madeira de almugue fez e rei balaústres para a casa do Senhor, e para a casa de rei, como também harpas e alaúdes para os cantores; não se trouxe nem se viu mais tal madeira de almugue, até o dia de hoje.

[[v11-10-13]]

^<<v11-10-13,13>>^ E o rei Salomão deu à rainha de Sabá tudo o que ela desejou, tudo quanto pediu, além de que lhe dera espontaneamente, da sua munificência real. Então voltou e foi para a sua terra, ela e os seus servos.

[[v11-10-14]]

^<<v11-10-14,14>>^ Ora, o peso do ouro que se trazia a Salomão cada ano era de seiscentos e sessenta e seis talentos de ouro,

[[v11-10-15]]

^<<v11-10-15,15>>^ além do que vinha dos vendedores ambulantes, e do tráfico dos negociantes, e de todos as reis da Arábia, e dos governadores do país.

[[v11-10-16]]

^<<v11-10-16,16>>^ Também o rei Salomão fez duzentos paveses de ouro batido; de seiscentos siclos de ouro mandou fazer cada pavês;

[[v11-10-17]]

^<<v11-10-17,17>>^ do mesmo modo fez também trezentos escudos de ouro batido; de três minas de auro mandou fazer cada escudo. Então e rei os pôs na casa do bosque de Líbano.

[[v11-10-18]]

^<<v11-10-18,18>>^ Fez mais o rei um grande trono de marfim, e o revestiu de ouro puríssimo.

[[v11-10-19]]

^<<v11-10-19,19>>^ Tinha o trono seis degraus, e o alto do trono era redondo pelo espaldar; de ambos os lados tinha braços junto ao assento, e dois leões em pé junto aos braços.

[[v11-10-20]]

^<<v11-10-20,20>>^ E sobre os seis degraus havia doze leões de ambos os lados; outro tal não se fizera em reino algum.

[[v11-10-21]]

^<<v11-10-21,21>>^ Também todos os vasos de beber de rei Salomão eram de ouro, e todos os vasos da casa do bosque do Líbano eram de ouro puro; não havia nenhum de prata, porque nos dias de Salomão a prata não tinha estimação alguma.

[[v11-10-22]]

^<<v11-10-22,22>>^ Porque o rei tinha no mar uma frota de Társis, com a de Hirão; de três em três anos a frota de Társis voltava, trazendo ouro e prata, marfim, bugios e pavões.

[[v11-10-23]]

^<<v11-10-23,23>>^ Assim o rei Salomão excedeu a todos os reis da terra, tanto em riquezas como em sabedoria.

[[v11-10-24]]

^<<v11-10-24,24>>^ E toda a terra buscava a presença de Salomão para ouvir a sabedoria que Deus lhe tinha posto no coração.

[[v11-10-25]]

^<<v11-10-25,25>>^ Cada um trazia seu presente, vasos de prata, vasos de ouro, vestidos, armaduras, especiarias, cavalos e mulas; isso faziam cada ano.

[[v11-10-26]]

^<<v11-10-26,26>>^ Também ajuntou Salomão carros e cavaleiros, de sorte que tinha mil e quatrocentos carros e doze mil cavaleiros, e os distribuiu pelas cidades dos carros, e junto ao rei em Jerusalém.

[[v11-10-27]]

^<<v11-10-27,27>>^ E o rei tornou a prata tão comum em Jerusalém como as pedras, e os cedros tantos em abundância como os sicômoros que há pelas campinas.

[[v11-10-28]]

^<<v11-10-28,28>>^ Os cavalos que Salomão tinha eram trazidos do Egito e de Coa; os mercadores do rei os recebiam de Coa por preço determinado.

[[v11-10-29]]

^<<v11-10-29,29>>^ E subia e saía um carro do Egito por seiscentos siclos de prata, e um cavalo por cento e cinqüenta; e assim, por intermédio desses mercadores, eram exportados para todos os reis dos heteus e para os reis da Síria.

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]