include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v11-19-1]]

^<<v11-19-1,1>>^ Ora, Acabe fez saber a Jezabel tudo quanto Elias havia feito, e como matara à espada todos os profetas.

[[v11-19-2]]

^<<v11-19-2,2>>^ Então Jezabel mandou um mensageiro a Elias, a dizer-lhe: Assim me façam os deuses, e outro tanto, se até amanhã a estas horas eu não fizer a tua vida como a de um deles.

[[v11-19-3]]

^<<v11-19-3,3>>^ Quando ele viu isto, levantou-se e, para escapar com vida, se foi. E chegando a Berseba, que pertence a Judá, deixou ali o seu moço.

[[v11-19-4]]

^<<v11-19-4,4>>^ Ele, porém, entrou pelo deserto caminho de um dia, e foi sentar-se debaixo de um zimbro; e pediu para si a morte, dizendo: Já basta, ó Senhor; toma agora a minha vida, pois não sou melhor do que meus pais.

[[v11-19-5]]

^<<v11-19-5,5>>^ E deitando-se debaixo do zimbro, dormiu; e eis que um anjo o tocou, e lhe disse: Levanta-te e come.

[[v11-19-6]]

^<<v11-19-6,6>>^ Ele olhou, e eis que à sua cabeceira estava um pão cozido sobre as brasas, e uma botija de água. Tendo comido e bebido, tornou a deitar-se.

[[v11-19-7]]

^<<v11-19-7,7>>^ O anjo do Senhor veio segunda vez, tocou-o, e lhe disse: Levanta-te e come, porque demasiado longa te será a viagem.

[[v11-19-8]]

^<<v11-19-8,8>>^ Levantou-se, pois, e comeu e bebeu; e com a força desse alimento caminhou quarenta dias e quarenta noites até Horebe, o monte de Deus.

[[v11-19-9]]

^<<v11-19-9,9>>^ Ali entrou numa caverna, onde passou a noite. E eis que lhe veio a palavra do Senhor, dizendo: Que fazes aqui, Elias?

[[v11-19-10]]

^<<v11-19-10,10>>^ Respondeu ele: Tenho sido muito zeloso pelo Senhor Deus dos exércitos; porque os filhos de Israel deixaram o teu pacto, derrubaram os teus altares, e mataram os teus profetas à espada; e eu, somente eu, fiquei, e buscam a minha vida para ma tirarem.

[[v11-19-11]]

^<<v11-19-11,11>>^ Ao que Deus lhe disse: Vem cá fora, e põe-te no monte perante o Senhor: E eis que o Senhor passou; e um grande e forte vento fendia os montes e despedaçava as penhas diante do Senhor, porém o Senhor não estava no vento; e depois do vento um terremoto, porém o Senhor não estava no terremoto;

[[v11-19-12]]

^<<v11-19-12,12>>^ e depois do terremoto um fogo, porém o Senhor não estava no fogo; e ainda depois do fogo uma voz mansa e delicada.

[[v11-19-13]]

^<<v11-19-13,13>>^ E ao ouvi-la, Elias cobriu o rosto com a capa e, saindo, pôs-se à entrada da caverna. E eis que lhe veio uma voz, que dizia: Que fazes aqui, Elias?

[[v11-19-14]]

^<<v11-19-14,14>>^ Respondeu ele: Tenho sido muito zeloso pelo Senhor Deus dos exércitos; porque os filhos de Israel deixaram o teu pacto, derrubaram os teus altares, e mataram os teus profetas à espada; e eu, somente eu, fiquei, e buscam a minha vida para ma tirarem.

[[v11-19-15]]

^<<v11-19-15,15>>^ Então o Senhor lhe disse: Vai, volta pelo teu caminho para o deserto de Damasco; quando lá chegares, ungirás a Hazael para ser rei sobre a Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ E a Jeú, filho de Ninsi, ungirás para ser rei sobre Israel; bem como a Eliseu, filho de Safate de Abel-Meolá, ungirás para ser profeta em teu lugar.

[[v11-19-17]]

^<<v11-19-17,17>>^ E há de ser que o que escapar da espada de Hazael, matá-lo-á Jeú; e o que escapar da espada de Jeú, matá-lo-á Eliseu.

[[v11-19-18]]

^<<v11-19-18,18>>^ Todavia deixarei em Israel sete mil: todos os joelhos que não se dobraram a Baal, e toda boca que não o beijou.

[[v11-19-19]]

^<<v11-19-19,19>>^ Partiu, pois, Elias dali e achou Eliseu, filho de Safate, que andava lavrando com doze juntas de bois adiante dele, estando ele com a duodécima; chegando-se Elias a Eliseu, lançou a sua capa sobre ele.

[[v11-19-20]]

^<<v11-19-20,20>>^ Então, deixando este os bois, correu após Elias, e disse: Deixa-me beijar a meu pai e a minha mãe, e então te seguirei. Respondeu-lhe Elias: Vai, volta; pois, que te fiz eu?

[[v11-19-21]]

^<<v11-19-21,21>>^ Voltou, pois, de o seguir, tomou a junta de bois, e os matou, e com os aparelhos dos bois cozeu a carne, e a deu ao povo, e comeram. Então se levantou e seguiu a Elias, e o servia.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]