include::./index.adoc[]

[[v42-5-0]]
=== Lucas, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-5-1]]

^<<v42-5-1,1>>^ Certa vez, quando a multidão apertava Jesus para ouvir a palavra de Deus, ele estava junto ao lago de Genezaré;

[[v42-5-2]]

^<<v42-5-2,2>>^ e viu dois barcos junto à praia do lago; mas os pescadores haviam descido deles, e estavam lavando as redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Entrando ele num dos barcos, que era o de Simão, pediu-lhe que o afastasse um pouco da terra; e, sentando-se, ensinava do barco as multidões.

[[v42-5-4]]

^<<v42-5-4,4>>^ Quando acabou de falar, disse a Simão: Faze-te ao largo e lançai as vossas redes para a pesca.

[[v42-5-5]]

^<<v42-5-5,5>>^ Ao que disse Simão: Mestre, trabalhamos a noite toda, e nada apanhamos; mas, sobre tua palavra, lançarei as redes.

[[v42-5-6]]

^<<v42-5-6,6>>^ Feito isto, apanharam uma grande quantidade de peixes, de modo que as redes se rompiam.

[[v42-5-7]]

^<<v42-5-7,7>>^ Acenaram então aos companheiros que estavam no outro barco, para virem ajudá-los. Eles, pois, vieram, e encheram ambos os barcos, de maneira tal que quase iam a pique.

[[v42-5-8]]

^<<v42-5-8,8>>^ Vendo isso Simão Pedro, prostrou-se aos pés de Jesus, dizendo: Retira-te de mim, Senhor, porque sou um homem pecador.

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois, à vista da pesca que haviam feito, o espanto se apoderara dele e de todos os que com ele estavam,

[[v42-5-10]]

^<<v42-5-10,10>>^ bem como de Tiago e João, filhos de Zebedeu, que eram sócios de Simão. Disse Jesus a Simão: Não temas; de agora em diante serás pescador de homens.

[[v42-5-11]]

^<<v42-5-11,11>>^ E, levando eles os barcos para a terra, deixaram tudo e o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ Estando ele numa das cidades, apareceu um homem cheio de lepra que, vendo a Jesus, prostrou-se com o rosto em terra e suplicou-lhe: Senhor, se quiseres, bem podes tornar-me limpo.

[[v42-5-13]]

^<<v42-5-13,13>>^ Jesus, pois, estendendo a mão, tocou-lhe, dizendo: Quero; sê limpo. No mesmo instante desapareceu dele a lepra.

[[v42-5-14]]

^<<v42-5-14,14>>^ Ordenou-lhe, então, que a ninguém contasse isto. Mas vai, disse ele, mostra-te ao sacerdote e faze a oferta pela tua purificação, conforme Moisés determinou, para lhes servir de testemunho.

[[v42-5-15]]

^<<v42-5-15,15>>^ A sua fama, porém, se divulgava cada vez mais, e grandes multidões se ajuntavam para ouvi-lo e serem curadas das suas enfermidades.

[[v42-5-16]]

^<<v42-5-16,16>>^ Mas ele se retirava para os desertos, e ali orava.

[[v42-5-17]]

^<<v42-5-17,17>>^ Um dia, quando ele estava ensinando, achavam-se ali sentados fariseus e doutores da lei, que tinham vindo de todas as aldeias da Galiléia e da Judéia, e de Jerusalém; e o poder do Senhor estava com ele para curar.

[[v42-5-18]]

^<<v42-5-18,18>>^ E eis que uns homens, trazendo num leito um paralítico, procuravam introduzi-lo e pô-lo diante dele.

[[v42-5-19]]

^<<v42-5-19,19>>^ Mas, não achando por onde o pudessem introduzir por causa da multidão, subiram ao eirado e, por entre as telhas, o baixaram com o leito, para o meio de todos, diante de Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ E vendo-lhes a fé, disse ele: Homem, são-te perdoados os teus pecados.

[[v42-5-21]]

^<<v42-5-21,21>>^ Então os escribas e os fariseus começaram a arrazoar, dizendo: Quem é este que profere blasfêmias? Quem é este que profere blasfêmias? Quem pode perdoar pecados, senão só Deus?

[[v42-5-22]]

^<<v42-5-22,22>>^ Jesus, porém, percebendo os seus pensamentos, respondeu, e disse-lhes: Por que arrazoais em vossos corações?

[[v42-5-23]]

^<<v42-5-23,23>>^ Qual é mais fácil? dizer: São-te perdoados os teus pecados; ou dizer: Levanta-te, e anda?

[[v42-5-24]]

^<<v42-5-24,24>>^ Ora, para que saibais que o Filho do homem tem sobre a terra autoridade para perdoar pecados &#123;disse ao paralítico&#125;, a ti te digo: Levanta-te, toma o teu leito e vai para tua casa.

[[v42-5-25]]

^<<v42-5-25,25>>^ Imediatamente se levantou diante deles, tomou o leito em que estivera deitado e foi para sua casa, glorificando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ E, tomados de pasmo, todos glorificavam a Deus; e diziam, cheios de temor: Hoje vimos coisas extraordinárias.

[[v42-5-27]]

^<<v42-5-27,27>>^ Depois disso saiu e, vendo um publicano chamado Levi, sentado na coletoria, disse-lhe: Segue-me.

[[v42-5-28]]

^<<v42-5-28,28>>^ Este, deixando tudo, levantou-se e o seguiu.

[[v42-5-29]]

^<<v42-5-29,29>>^ Deu-lhe então Levi um lauto banquete em sua casa; havia ali grande número de publicanos e outros que estavam com eles à mesa.

[[v42-5-30]]

^<<v42-5-30,30>>^ Murmuravam, pois, os fariseus e seus escribas contra os discípulos, perguntando: Por que comeis e bebeis com publicanos e pecadores?

[[v42-5-31]]

^<<v42-5-31,31>>^ Respondeu-lhes Jesus: Não necessitam de médico os sãos, mas sim os enfermos;

[[v42-5-32]]

^<<v42-5-32,32>>^ eu não vim chamar justos, mas pecadores, ao arrependimento.

[[v42-5-33]]

^<<v42-5-33,33>>^ Disseram-lhe eles: Os discípulos de João jejuam freqüentemente e fazem orações, como também os dos fariseus, mas os teus comem e bebem.

[[v42-5-34]]

^<<v42-5-34,34>>^ Respondeu-lhes Jesus: Podeis, porventura, fazer jejuar os convidados às núpcias enquanto o noivo está com eles?

[[v42-5-35]]

^<<v42-5-35,35>>^ Dias virão, porém, em que lhes será tirado o noivo; naqueles dias, sim hão de jejuar.

[[v42-5-36]]

^<<v42-5-36,36>>^ Propôs-lhes também uma parábola: Ninguém tira um pedaço de um vestido novo para o coser em vestido velho; do contrário, não somente rasgará o novo, mas também o pedaço do novo não condirá com o velho.

[[v42-5-37]]

^<<v42-5-37,37>>^ E ninguém deita vinho novo em odres velhos; do contrário, o vinho novo romperá os odres e se derramará, e os odres se perderão;

[[v42-5-38]]

^<<v42-5-38,38>>^ mas vinho novo deve ser deitado em odres novos.

[[v42-5-39]]

^<<v42-5-39,39>>^ E ninguém, tendo bebido o velho, quer o novo; porque diz: O velho é bom.

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]