include::./index.adoc[]

[[v42-7-0]]
=== Lucas, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-7-1]]

^<<v42-7-1,1>>^ Quando acabou de proferir todas estas palavras aos ouvidos do povo, entrou em Cafarnaum.

[[v42-7-2]]

^<<v42-7-2,2>>^ E um servo de certo centurião, de quem era muito estimado, estava doente, quase à morte.

[[v42-7-3]]

^<<v42-7-3,3>>^ O centurião, pois, ouvindo falar de Jesus, enviou-lhes uns anciãos dos judeus, a pedir-lhe que viesse curar o seu servo.

[[v42-7-4]]

^<<v42-7-4,4>>^ E chegando eles junto de Jesus, rogavam-lhe com instância, dizendo: É digno de que lhe concedas isto;

[[v42-7-5]]

^<<v42-7-5,5>>^ porque ama à nossa nação, e ele mesmo nos edificou a sinagoga.

[[v42-7-6]]

^<<v42-7-6,6>>^ Ia, pois, Jesus com eles; mas, quando já estava perto da casa, enviou o centurião uns amigos a dizer-lhe: Senhor, não te incomodes; porque não sou digno de que entres debaixo do meu telhado;

[[v42-7-7]]

^<<v42-7-7,7>>^ por isso nem ainda me julguei digno de ir à tua presença; dize, porém, uma palavra, e seja o meu servo curado.

[[v42-7-8]]

^<<v42-7-8,8>>^ Pois também eu sou homem sujeito à autoridade, e tenho soldados às minhas ordens; e digo a este: Vai, e ele vai; e a outro: Vem, e ele vem; e ao meu servo: Faze isto, e ele o faz.

[[v42-7-9]]

^<<v42-7-9,9>>^ Jesus, ouvindo isso, admirou-se dele e, voltando-se para a multidão que o seguia, disse: Eu vos afirmo que nem mesmo em Israel encontrei tamanha fé.

[[v42-7-10]]

^<<v42-7-10,10>>^ E voltando para casa os que haviam sido enviados, encontraram o servo com saúde.

[[v42-7-11]]

^<<v42-7-11,11>>^ Pouco depois seguiu ele viagem para uma cidade chamada Naim; e iam com ele seus discípulos e uma grande multidão.

[[v42-7-12]]

^<<v42-7-12,12>>^ Quando chegou perto da porta da cidade, eis que levavam para fora um defunto, filho único de sua mãe, que era viúva; e com ela ia uma grande multidão da cidade.

[[v42-7-13]]

^<<v42-7-13,13>>^ Logo que o Senhor a viu, encheu-se de compaixão por ela, e disse-lhe: Não chores.

[[v42-7-14]]

^<<v42-7-14,14>>^ Então, chegando-se, tocou no esquife e, quando pararam os que o levavam, disse: Moço, a ti te digo: Levanta-te.

[[v42-7-15]]

^<<v42-7-15,15>>^ O que estivera morto sentou-se e começou a falar. Então Jesus o entregou à sua mãe.

[[v42-7-16]]

^<<v42-7-16,16>>^ O medo se apoderou de todos, e glorificavam a Deus, dizendo: Um grande profeta se levantou entre nós; e: Deus visitou o seu povo.

[[v42-7-17]]

^<<v42-7-17,17>>^ E correu a notícia disto por toda a Judéia e por toda a região circunvizinha.

[[v42-7-18]]

^<<v42-7-18,18>>^ Ora, os discípulos de João anunciaram-lhe todas estas coisas.

[[v42-7-19]]

^<<v42-7-19,19>>^ E João, chamando a dois deles, enviou-os ao Senhor para perguntar-lhe: És tu aquele que havia de vir, ou havemos de esperar outro?

[[v42-7-20]]

^<<v42-7-20,20>>^ Quando aqueles homens chegaram junto dele, disseram: João, o Batista, enviou-nos a perguntar-te: És tu aquele que havia de vir, ou havemos de esperar outro?

[[v42-7-21]]

^<<v42-7-21,21>>^ Naquela mesma hora, curou a muitos de doenças, de moléstias e de espíritos malignos; e deu vista a muitos cegos.

[[v42-7-22]]

^<<v42-7-22,22>>^ Então lhes respondeu: Ide, e contai a João o que tens visto e ouvido: os cegos vêem, os coxos andam, os leprosos são purificados, e os surdos ouvem; os mortos são ressuscitados, e aos pobres é anunciado o evangelho.

[[v42-7-23]]

^<<v42-7-23,23>>^ E bem-aventurado aquele que não se escandalizar de mim.

[[v42-7-24]]

^<<v42-7-24,24>>^ E, tendo-se retirado os mensageiros de João, Jesus começou a dizer às multidões a respeito de João: Que saístes a ver no deserto? um caniço agitado pelo vento?

[[v42-7-25]]

^<<v42-7-25,25>>^ Mas que saístes a ver? um homem trajado de vestes luxuosas? Eis que aqueles que trajam roupas preciosas, e vivem em delícias, estão nos paços reais.

[[v42-7-26]]

^<<v42-7-26,26>>^ Mas que saístes a ver? um profeta? Sim, vos digo, e muito mais do que profeta.

[[v42-7-27]]

^<<v42-7-27,27>>^ Este é aquele de quem está escrito: Eis aí envio ante a tua face o meu mensageiro, que há de preparar adiante de ti o teu caminho.

[[v42-7-28]]

^<<v42-7-28,28>>^ Pois eu vos digo que, entre os nascidos de mulher, não há nenhum maior do que João; mas aquele que é o menor no reino de Deus é maior do que ele.

[[v42-7-29]]

^<<v42-7-29,29>>^ E todo o povo que o ouviu, e até os publicanos, reconheceram a justiça de Deus, recebendo o batismo de João.

[[v42-7-30]]

^<<v42-7-30,30>>^ Mas os fariseus e os doutores da lei rejeitaram o conselho de Deus quando a si mesmos, não sendo batizados por ele.

[[v42-7-31]]

^<<v42-7-31,31>>^ A que, pois, compararei os homens desta geração, e a que são semelhantes?

[[v42-7-32]]

^<<v42-7-32,32>>^ São semelhantes aos meninos que, sentados nas praças, gritam uns para os outros: Tocamo-vos flauta, e não dançastes; cantamos lamentações, e não chorastes.

[[v42-7-33]]

^<<v42-7-33,33>>^ Porquanto veio João, o Batista, não comendo pão nem bebendo vinho, e dizeis: Tem demônio;

[[v42-7-34]]

^<<v42-7-34,34>>^ veio o Filho do homem, comendo e bebendo, e dizeis: Eis aí um comilão e bebedor de vinho, amigo de publicanos e pecadores.

[[v42-7-35]]

^<<v42-7-35,35>>^ Mas a sabedoria é justificada por todos os seus filhos.

[[v42-7-36]]

^<<v42-7-36,36>>^ Um dos fariseus convidou-o para comer com ele; e entrando em casa do fariseu, reclinou-se à mesa.

[[v42-7-37]]

^<<v42-7-37,37>>^ E eis que uma mulher pecadora que havia na cidade, quando soube que ele estava à mesa em casa do fariseu, trouxe um vaso de alabastro com bálsamo;

[[v42-7-38]]

^<<v42-7-38,38>>^ e estando por detrás, aos seus pés, chorando, começou a regar-lhe os pés com lágrimas e os enxugava com os cabelos da sua cabeça; e beijava-lhe os pés e ungia-os com o bálsamo.

[[v42-7-39]]

^<<v42-7-39,39>>^ Mas, ao ver isso, o fariseu que o convidara falava consigo, dizendo: Se este homem fosse profeta, saberia quem e de que qualidade é essa mulher que o toca, pois é uma pecadora.

[[v42-7-40]]

^<<v42-7-40,40>>^ E respondendo Jesus, disse-lhe: Simão, tenho uma coisa a dizer-te. Respondeu ele: Dize-a, Mestre.

[[v42-7-41]]

^<<v42-7-41,41>>^ Certo credor tinha dois devedores; um lhe devia quinhentos denários, e outro cinqüenta.

[[v42-7-42]]

^<<v42-7-42,42>>^ Não tendo eles com que pagar, perdoou a ambos. Qual deles, pois, o amará mais?

[[v42-7-43]]

^<<v42-7-43,43>>^ Respondeu Simão: Suponho que é aquele a quem mais perdoou. Replicou-lhe Jesus: Julgaste bem.

[[v42-7-44]]

^<<v42-7-44,44>>^ E, voltando-se para a mulher, disse a Simão: Vês tu esta mulher? Entrei em tua casa, e não me deste água para os pés; mas esta com suas lágrimas os regou e com seus cabelos os enxugou.

[[v42-7-45]]

^<<v42-7-45,45>>^ Não me deste ósculo; ela, porém, desde que entrei, não tem cessado de beijar-me os pés.

[[v42-7-46]]

^<<v42-7-46,46>>^ Não me ungiste a cabeça com óleo; mas esta com bálsamo ungiu-me os pés.

[[v42-7-47]]

^<<v42-7-47,47>>^ Por isso te digo: Perdoados lhe são os pecados, que são muitos; porque ela muito amou; mas aquele a quem pouco se perdoa, pouco ama.

[[v42-7-48]]

^<<v42-7-48,48>>^ E disse a ela: Perdoados são os teus pecados.

[[v42-7-49]]

^<<v42-7-49,49>>^ Mas os que estavam com ele à mesa começaram a dizer entre si: Quem é este que até perdoa pecados?

[[v42-7-50]]

^<<v42-7-50,50>>^ Jesus, porém, disse à mulher: A tua fé te salvou; vai-te em paz.

'''

xref:042-lucas/042-lucas-006.adoc#v42-6-0[&#60; Capítulo Anterior] | <<v42-7-0,Topo>> | xref:042-lucas/042-lucas-008.adoc#v42-8-0[Próximo Capítulo &#62;]