include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-24-1]]

^<<v42-24-1,1>>^ Mas já no primeiro dia da semana, bem de madrugada, foram elas ao sepulcro, levando as especiarias que tinham preparado.

[[v42-24-2]]

^<<v42-24-2,2>>^ E acharam a pedra revolvida do sepulcro.

[[v42-24-3]]

^<<v42-24-3,3>>^ Entrando, porém, não acharam o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ E, estando elas perplexas a esse respeito, eis que lhes apareceram dois varões em vestes resplandecentes;

[[v42-24-5]]

^<<v42-24-5,5>>^ e ficando elas atemorizadas e abaixando o rosto para o chão, eles lhes disseram: Por que buscais entre os mortos aquele que vive?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui, mas ressurgiu. Lembrai-vos de como vos falou, estando ainda na Galiléia.

[[v42-24-7]]

^<<v42-24-7,7>>^ dizendo: Importa que o Filho do homem seja entregue nas mãos de homens pecadores, e seja crucificado, e ao terceiro dia ressurja.

[[v42-24-8]]

^<<v42-24-8,8>>^ Lembraram-se, então, das suas palavras;

[[v42-24-9]]

^<<v42-24-9,9>>^ e, voltando do sepulcro, anunciaram todas estas coisas aos onze e a todos os demais.

[[v42-24-10]]

^<<v42-24-10,10>>^ E eram Maria Madalena, e Joana, e Maria, mãe de Tiago; também as outras que estavam com elas relataram estas coisas aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ E pareceram-lhes como um delírio as palavras das mulheres e não lhes deram crédito.

[[v42-24-12]]

^<<v42-24-12,12>>^ Mas Pedro, levantando-se, correu ao sepulcro; e, abaixando-se, viu somente os panos de linho; e retirou-se, admirando consigo o que havia acontecido.

[[v42-24-13]]

^<<v42-24-13,13>>^ Nesse mesmo dia, iam dois deles para uma aldeia chamada Emaús, que distava de Jerusalém sessenta estádios;

[[v42-24-14]]

^<<v42-24-14,14>>^ e iam comentando entre si tudo aquilo que havia sucedido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Enquanto assim comentavam e discutiam, o próprio Jesus se aproximou, e ia com eles;

[[v42-24-16]]

^<<v42-24-16,16>>^ mas os olhos deles estavam como que fechados, de sorte que não o reconheceram.

[[v42-24-17]]

^<<v42-24-17,17>>^ Então ele lhes perguntou: Que palavras são essas que, caminhando, trocais entre vós? Eles então pararam tristes.

[[v42-24-18]]

^<<v42-24-18,18>>^ E um deles, chamado Cleopas, respondeu-lhe: És tu o único peregrino em Jerusalém que não soube das coisas que nela têm sucedido nestes dias?

[[v42-24-19]]

^<<v42-24-19,19>>^ Ao que ele lhes perguntou: Quais? Disseram-lhe: As que dizem respeito a Jesus, o nazareno, que foi profeta, poderoso em obras e palavras diante de Deus e de todo o povo.

[[v42-24-20]]

^<<v42-24-20,20>>^ e como os principais sacerdotes e as nossas autoridades e entregaram para ser condenado à morte, e o crucificaram.

[[v42-24-21]]

^<<v42-24-21,21>>^ Ora, nós esperávamos que fosse ele quem havia de remir Israel; e, além de tudo isso, é já hoje o terceiro dia desde que essas coisas aconteceram.

[[v42-24-22]]

^<<v42-24-22,22>>^ Verdade é, também, que algumas mulheres do nosso meio nos encheram de espanto; pois foram de madrugada ao sepulcro

[[v42-24-23]]

^<<v42-24-23,23>>^ e, não achando o corpo dele voltaram, declarando que tinham tido uma visão de anjos que diziam estar ele vivo.

[[v42-24-24]]

^<<v42-24-24,24>>^ Além disso, alguns dos que estavam conosco foram ao sepulcro, e acharam ser assim como as mulheres haviam dito; a ele, porém, não o viram.

[[v42-24-25]]

^<<v42-24-25,25>>^ Então ele lhes disse: ó néscios, e tardos de coração para crerdes tudo o que os profetas disseram!

[[v42-24-26]]

^<<v42-24-26,26>>^ Porventura não importa que o Cristo padecesse essas coisas e entrasse na sua glória?

[[v42-24-27]]

^<<v42-24-27,27>>^ E, começando por Moisés, e por todos os profetas, explicou-lhes o que dele se achava em todas as Escrituras.

[[v42-24-28]]

^<<v42-24-28,28>>^ Quando se aproximaram da aldeia para onde iam, ele fez como quem ia para mais longe.

[[v42-24-29]]

^<<v42-24-29,29>>^ Eles, porém, o constrangeram, dizendo: Fica conosco; porque é tarde, e já declinou o dia. E entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ Estando com eles à mesa, tomou o pão e o abençoou; e, partindo-o, lho dava.

[[v42-24-31]]

^<<v42-24-31,31>>^ Abriram-se-lhes então os olhos, e o reconheceram; nisto ele desapareceu de diante deles.

[[v42-24-32]]

^<<v42-24-32,32>>^ E disseram um para o outro: Porventura não se nos abrasava o coração, quando pelo caminho nos falava, e quando nos abria as Escrituras?

[[v42-24-33]]

^<<v42-24-33,33>>^ E na mesma hora levantaram-se e voltaram para Jerusalém, e encontraram reunidos os onze e os que estavam com eles,

[[v42-24-34]]

^<<v42-24-34,34>>^ os quais diziam: Realmente o Senhor ressurgiu, e apareceu a Simão.

[[v42-24-35]]

^<<v42-24-35,35>>^ Então os dois contaram o que acontecera no caminho, e como se lhes fizera conhecer no partir do pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Enquanto ainda falavam nisso, o próprio Jesus se apresentou no meio deles, e disse-lhes: Paz seja convosco.

[[v42-24-37]]

^<<v42-24-37,37>>^ Mas eles, espantados e atemorizados, pensavam que viam algum espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ Ele, porém, lhes disse: Por que estais perturbados? e por que surgem dúvidas em vossos corações?

[[v42-24-39]]

^<<v42-24-39,39>>^ Olhai as minhas mãos e os meus pés, que sou eu mesmo; apalpai-me e vede; porque um espírito não tem carne nem ossos, como percebeis que eu tenho.

[[v42-24-40]]

^<<v42-24-40,40>>^ E, dizendo isso, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ Não acreditando eles ainda por causa da alegria, e estando admirados, perguntou-lhes Jesus: Tendes aqui alguma coisa que comer?

[[v42-24-42]]

^<<v42-24-42,42>>^ Então lhe deram um pedaço de peixe assado,

[[v42-24-43]]

^<<v42-24-43,43>>^ o qual ele tomou e comeu diante deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ Depois lhe disse: São estas as palavras que vos falei, estando ainda convosco, que importava que se cumprisse tudo o que de mim estava escrito na Lei de Moisés, nos Profetas e nos Salmos.

[[v42-24-45]]

^<<v42-24-45,45>>^ Então lhes abriu o entendimento para compreenderem as Escrituras;

[[v42-24-46]]

^<<v42-24-46,46>>^ e disse-lhes: Assim está escrito que o Cristo padecesse, e ao terceiro dia ressurgisse dentre os mortos;

[[v42-24-47]]

^<<v42-24-47,47>>^ e que em seu nome se pregasse o arrependimento para remissão dos pecados, a todas as nações, começando por Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vós sois testemunhas destas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ E eis que sobre vós envio a promessa de meu Pai; ficai porém, na cidade, até que do alto sejais revestidos de poder.

[[v42-24-50]]

^<<v42-24-50,50>>^ Então os levou fora, até Betânia; e levantando as mãos, os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ E aconteceu que, enquanto os abençoava, apartou-se deles; e foi elevado ao céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ E, depois de o adorarem, voltaram com grande júbilo para Jerusalém;

[[v42-24-53]]

^<<v42-24-53,53>>^ e estavam continuamente no templo, bendizendo a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]