include::./index.adoc[]

[[v42-23-0]]
=== Lucas, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-23-1]]

^<<v42-23-1,1>>^ E levantando-se toda a multidão deles, conduziram Jesus a Pilatos.

[[v42-23-2]]

^<<v42-23-2,2>>^ E começaram a acusá-lo, dizendo: Achamos este homem pervertendo a nossa nação, proibindo dar o tributo a César, e dizendo ser ele mesmo Cristo, rei.

[[v42-23-3]]

^<<v42-23-3,3>>^ Pilatos, pois, perguntou-lhe: És tu o rei dos judeus? Respondeu-lhe Jesus: É como dizes.

[[v42-23-4]]

^<<v42-23-4,4>>^ Então disse Pilatos aos principais sacerdotes, e às multidões: Não acho culpa alguma neste homem.

[[v42-23-5]]

^<<v42-23-5,5>>^ Eles, porém, insistiam ainda mais, dizendo: Alvoroça o povo ensinando por toda a Judéia, começando desde a Galiléia até aqui.

[[v42-23-6]]

^<<v42-23-6,6>>^ Então Pilatos, ouvindo isso, perguntou se o homem era galileu;

[[v42-23-7]]

^<<v42-23-7,7>>^ e, quando soube que era da jurisdição de Herodes, remeteu-o a Herodes, que também naqueles dias estava em Jerusalém.

[[v42-23-8]]

^<<v42-23-8,8>>^ Ora, quando Herodes viu a Jesus, alegrou-se muito; pois de longo tempo desejava vê-lo, por ter ouvido falar a seu respeito; e esperava ver algum sinal feito por ele;

[[v42-23-9]]

^<<v42-23-9,9>>^ e fazia-lhe muitas perguntas; mas ele nada lhe respondeu.

[[v42-23-10]]

^<<v42-23-10,10>>^ Estavam ali os principais sacerdotes, e os escribas, acusando-o com grande veemência.

[[v42-23-11]]

^<<v42-23-11,11>>^ Herodes, porém, com os seus soldados, desprezou-o e, escarnecendo dele, vestiu-o com uma roupa resplandecente e tornou a enviá-lo a Pilatos.

[[v42-23-12]]

^<<v42-23-12,12>>^ Nesse mesmo dia Pilatos e Herodes tornaram-se amigos; pois antes andavam em inimizade um com o outro.

[[v42-23-13]]

^<<v42-23-13,13>>^ Então Pilatos convocou os principais sacerdotes, as autoridades e o povo,

[[v42-23-14]]

^<<v42-23-14,14>>^ e disse-lhes: Apresentastes-me este homem como pervertedor do povo; e eis que, interrogando-o diante de vós, não achei nele nenhuma culpa, das de que o acusais;

[[v42-23-15]]

^<<v42-23-15,15>>^ nem tampouco Herodes, pois no-lo tornou a enviar; e eis que não tem feito ele coisa alguma digna de morte.

[[v42-23-16]]

^<<v42-23-16,16>>^ Castigá-lo-ei, pois, e o soltarei.

[[v42-23-17]]

^<<v42-23-17,17>>^ &#123;E era-lhe necessário soltar-lhes um pela festa.&#125;

[[v42-23-18]]

^<<v42-23-18,18>>^ Mas todos clamaram à uma, dizendo: Fora com este, e solta-nos Barrabás!

[[v42-23-19]]

^<<v42-23-19,19>>^ Ora, Barrabás fora lançado na prisão por causa de uma sedição feita na cidade, e de um homicídio.

[[v42-23-20]]

^<<v42-23-20,20>>^ Mais uma vez, pois, falou-lhes Pilatos, querendo soltar a Jesus.

[[v42-23-21]]

^<<v42-23-21,21>>^ Eles, porém, bradavam, dizendo: Crucifica-o! crucifica-o!

[[v42-23-22]]

^<<v42-23-22,22>>^ Falou-lhes, então, pela terceira vez: Pois, que mal fez ele? Não achei nele nenhuma culpa digna de morte. Castigá-lo-ei, pois, e o soltarei.

[[v42-23-23]]

^<<v42-23-23,23>>^ Mas eles instavam com grandes brados, pedindo que fosse crucificado. E prevaleceram os seus clamores.

[[v42-23-24]]

^<<v42-23-24,24>>^ Então Pilatos resolveu atender-lhes o pedido;

[[v42-23-25]]

^<<v42-23-25,25>>^ e soltou-lhes o que fora lançado na prisão por causa de sedição e de homicídio, que era o que eles pediam; mas entregou Jesus à vontade deles.

[[v42-23-26]]

^<<v42-23-26,26>>^ Quando o levaram dali tomaram um certo Simão, cireneu, que vinha do campo, e puseram-lhe a cruz às costas, para que a levasse após Jesus.

[[v42-23-27]]

^<<v42-23-27,27>>^ Seguia-o grande multidão de povo e de mulheres, as quais o pranteavam e lamentavam.

[[v42-23-28]]

^<<v42-23-28,28>>^ Jesus, porém, voltando-se para elas, disse: Filhas de Jerusalém, não choreis por mim; chorai antes por vós mesmas, e por vossos filhos.

[[v42-23-29]]

^<<v42-23-29,29>>^ Porque dias hão de vir em que se dirá: Bem-aventuradas as estéreis, e os ventres que não geraram, e os peitos que não amamentaram!

[[v42-23-30]]

^<<v42-23-30,30>>^ Então começarão a dizer aos montes: Caí sobre nós; e aos outeiros: Cobri-nos.

[[v42-23-31]]

^<<v42-23-31,31>>^ Porque, se isto se faz no lenho verde, que se fará no seco?

[[v42-23-32]]

^<<v42-23-32,32>>^ E levavam também com ele outros dois, que eram malfeitores, para serem mortos.

[[v42-23-33]]

^<<v42-23-33,33>>^ Quando chegaram ao lugar chamado Caveira, ali o crucificaram, a ele e também aos malfeitores, um à direita e outro à esquerda.

[[v42-23-34]]

^<<v42-23-34,34>>^ Jesus, porém, dizia: Pai, perdoa-lhes; porque não sabem o que fazem. Então repartiram as vestes dele, deitando sortes sobre elas.

[[v42-23-35]]

^<<v42-23-35,35>>^ E o povo estava ali a olhar. E as próprias autoridades zombavam dele, dizendo: Aos outros salvou; salve-se a si mesmo, se é o Cristo, o escolhido de Deus.

[[v42-23-36]]

^<<v42-23-36,36>>^ Os soldados também o escarneciam, chegando-se a ele, oferecendo-lhe vinagre,

[[v42-23-37]]

^<<v42-23-37,37>>^ e dizendo: Se tu és o rei dos judeus, salva-te a ti mesmo.

[[v42-23-38]]

^<<v42-23-38,38>>^ Por cima dele estava esta inscrição &#123;em letras gregas, romanas e hebraicas:&#125; ESTE É O REI DOS JUDEUS.

[[v42-23-39]]

^<<v42-23-39,39>>^ Então um dos malfeitores que estavam pendurados, blasfemava dele, dizendo: Não és tu o Cristo? salva-te a ti mesmo e a nós.

[[v42-23-40]]

^<<v42-23-40,40>>^ Respondendo, porém, o outro, repreendia-o, dizendo: Nem ao menos temes a Deus, estando na mesma condenação?

[[v42-23-41]]

^<<v42-23-41,41>>^ E nós, na verdade, com justiça; porque recebemos o que os nossos feitos merecem; mas este nenhum mal fez.

[[v42-23-42]]

^<<v42-23-42,42>>^ Então disse: Jesus, lembra-te de mim, quando entrares no teu reino.

[[v42-23-43]]

^<<v42-23-43,43>>^ Respondeu-lhe Jesus: Em verdade te digo que hoje estarás comigo no paraíso.

[[v42-23-44]]

^<<v42-23-44,44>>^ Era já quase a hora sexta, e houve trevas em toda a terra até a hora nona, pois o sol se escurecera;

[[v42-23-45]]

^<<v42-23-45,45>>^ e rasgou-se ao meio o véu do santuário.

[[v42-23-46]]

^<<v42-23-46,46>>^ Jesus, clamando com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.

[[v42-23-47]]

^<<v42-23-47,47>>^ Quando o centurião viu o que acontecera, deu glória a Deus, dizendo: Na verdade, este homem era justo.

[[v42-23-48]]

^<<v42-23-48,48>>^ E todas as multidões que presenciaram este espetáculo, vendo o que havia acontecido, voltaram batendo no peito.

[[v42-23-49]]

^<<v42-23-49,49>>^ Entretanto, todos os conhecidos de Jesus, e as mulheres que o haviam seguido desde a Galiléia, estavam de longe vendo estas coisas.

[[v42-23-50]]

^<<v42-23-50,50>>^ Então um homem chamado José, natural de Arimatéia, cidade dos judeus, membro do sinédrio, homem bom e justo,

[[v42-23-51]]

^<<v42-23-51,51>>^ o qual não tinha consentido no conselho e nos atos dos outros, e que esperava o reino de Deus,

[[v42-23-52]]

^<<v42-23-52,52>>^ chegando a Pilatos, pediu-lhe o corpo de Jesus;

[[v42-23-53]]

^<<v42-23-53,53>>^ e tirando-o da cruz, envolveu-o num pano de linho, e pô-lo num sepulcro escavado em rocha, onde ninguém ainda havia sido posto.

[[v42-23-54]]

^<<v42-23-54,54>>^ Era o dia da preparação, e ia começar o sábado.

[[v42-23-55]]

^<<v42-23-55,55>>^ E as mulheres que tinham vindo com ele da Galiléia, seguindo a José, viram o sepulcro, e como o corpo foi ali depositado.

[[v42-23-56]]

^<<v42-23-56,56>>^ Então voltaram e prepararam especiarias e ungüentos. E no sábado repousaram, conforme o mandamento.

'''

xref:042-lucas/042-lucas-022.adoc#v42-22-0[&#60; Capítulo Anterior] | <<v42-23-0,Topo>> | xref:042-lucas/042-lucas-024.adoc#v42-24-0[Próximo Capítulo &#62;]