include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disso designou o Senhor outros setenta, e os enviou adiante de si, de dois em dois, a todas as cidades e lugares aonde ele havia de ir.

[[v42-10-2]]

^<<v42-10-2,2>>^ E dizia-lhes: Na verdade, a seara é grande, mas os trabalhadores são poucos; rogai, pois, ao Senhor da seara que mande trabalhadores para a sua seara.

[[v42-10-3]]

^<<v42-10-3,3>>^ Ide; eis que vos envio como cordeiros ao meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não leveis bolsa, nem alforge, nem alparcas; e a ninguém saudeis pelo caminho.

[[v42-10-5]]

^<<v42-10-5,5>>^ Em qualquer casa em que entrardes, dizei primeiro: Paz seja com esta casa.

[[v42-10-6]]

^<<v42-10-6,6>>^ E se ali houver um filho da paz, repousará sobre ele a vossa paz; e se não, voltará para vós.

[[v42-10-7]]

^<<v42-10-7,7>>^ Ficai nessa casa, comendo e bebendo do que eles tiverem; pois digno é o trabalhador do seu salário. Não andeis de casa em casa.

[[v42-10-8]]

^<<v42-10-8,8>>^ Também, em qualquer cidade em que entrardes, e vos receberem, comei do que puserem diante de vós.

[[v42-10-9]]

^<<v42-10-9,9>>^ Curai os enfermos que nela houver, e dizer-lhes: É chegado a vós o reino de Deus.

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas em qualquer cidade em que entrardes, e vos não receberem, saindo pelas ruas, dizei:

[[v42-10-11]]

^<<v42-10-11,11>>^ Até o pó da vossa cidade, que se nos pegou aos pés, sacudimos contra vós. Contudo, sabei isto: que o reino de Deus é chegado.

[[v42-10-12]]

^<<v42-10-12,12>>^ Digo-vos que naquele dia haverá menos rigor para Sodoma, do que para aquela cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ Ai de ti, Corazim! ai de ti, Betsaida! Porque, se em Tiro e em Sidom se tivessem operado os milagres que em vós se operaram, há muito, sentadas em cilício e cinza, elas se teriam arrependido.

[[v42-10-14]]

^<<v42-10-14,14>>^ Contudo, para Tiro e Sidom haverá menos rigor no juízo do que para vós.

[[v42-10-15]]

^<<v42-10-15,15>>^ E tu, Cafarnaum, porventura serás elevada até o céu? até o inferno descerás.

[[v42-10-16]]

^<<v42-10-16,16>>^ Quem vos ouve, a mim me ouve; e quem vos rejeita, a mim me rejeita; e quem a mim me rejeita, rejeita aquele que me enviou.

[[v42-10-17]]

^<<v42-10-17,17>>^ Voltaram depois os setenta com alegria, dizendo: Senhor, em teu nome, até os demônios se nos submetem.

[[v42-10-18]]

^<<v42-10-18,18>>^ Respondeu-lhes ele: Eu via Satanás, como raio, cair do céu.

[[v42-10-19]]

^<<v42-10-19,19>>^ Eis que vos dei autoridade para pisar serpentes e escorpiões, e sobre todo o poder do inimigo; e nada vos fará dano algum.

[[v42-10-20]]

^<<v42-10-20,20>>^ Contudo, não vos alegreis porque se vos submetem os espíritos; alegrai-vos antes por estarem os vossos nomes escritos nos céus.

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela mesma hora exultou Jesus no Espírito Santo, e disse: Graças te dou, ó Pai, Senhor do céu e da terra, porque ocultaste estas coisas aos sábios e entendidos, e as revelaste aos pequeninos; sim, ó Pai, porque assim foi do teu agrado.

[[v42-10-22]]

^<<v42-10-22,22>>^ Todas as coisas me foram entregues por meu Pai; e ninguém conhece quem é o Filho senão o Pai, nem quem é o Pai senão o Filho, e aquele a quem o Filho o quiser revelar.

[[v42-10-23]]

^<<v42-10-23,23>>^ E voltando-se para os discípulos, disse-lhes em particular: Bem-aventurados os olhos que vêem o que vós vedes.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois vos digo que muitos profetas e reis desejaram ver o que vós vedes, e não o viram; e ouvir o que ouvis, e não o ouviram.

[[v42-10-25]]

^<<v42-10-25,25>>^ E eis que se levantou certo doutor da lei e, para o experimentar, disse: Mestre, que farei para herdar a vida eterna?

[[v42-10-26]]

^<<v42-10-26,26>>^ Perguntou-lhe Jesus: Que está escrito na lei? Como lês tu?

[[v42-10-27]]

^<<v42-10-27,27>>^ Respondeu-lhe ele: Amarás ao Senhor teu Deus de todo o teu coração, de toda a tua alma, de todas as tuas forças e de todo o teu entendimento, e ao teu próximo como a ti mesmo.

[[v42-10-28]]

^<<v42-10-28,28>>^ Tornou-lhe Jesus: Respondeste bem; faze isso, e viverás.

[[v42-10-29]]

^<<v42-10-29,29>>^ Ele, porém, querendo justificar-se, perguntou a Jesus: E quem é o meu próximo?

[[v42-10-30]]

^<<v42-10-30,30>>^ Jesus, prosseguindo, disse: Um homem descia de Jerusalém a Jericó, e caiu nas mãos de salteadores, os quais o despojaram e espancando-o, se retiraram, deixando-o meio morto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Casualmente, descia pelo mesmo caminho certo sacerdote; e vendo-o, passou de largo.

[[v42-10-32]]

^<<v42-10-32,32>>^ De igual modo também um levita chegou àquele lugar, viu-o, e passou de largo.

[[v42-10-33]]

^<<v42-10-33,33>>^ Mas um samaritano, que ia de viagem, chegou perto dele e, vendo-o, encheu-se de compaixão;

[[v42-10-34]]

^<<v42-10-34,34>>^ e aproximando-se, atou-lhe as feridas, deitando nelas azeite e vinho; e pondo-o sobre a sua cavalgadura, levou-o para uma estalagem e cuidou dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte tirou dois denários, deu-os ao hospedeiro e disse-lhe: Cuida dele; e tudo o que gastares a mais, eu to pagarei quando voltar.

[[v42-10-36]]

^<<v42-10-36,36>>^ Qual, pois, destes três te parece ter sido o próximo daquele que caiu nas mãos dos salteadores?

[[v42-10-37]]

^<<v42-10-37,37>>^ Respondeu o doutor da lei: Aquele que usou de misericórdia para com ele. Disse-lhe, pois, Jesus: Vai, e faze tu o mesmo.

[[v42-10-38]]

^<<v42-10-38,38>>^ Ora, quando iam de caminho, entrou Jesus numa aldeia; e certa mulher, por nome Marta, o recebeu em sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Tinha esta uma irmã chamada Maria, a qual, sentando-se aos pés do Senhor, ouvia a sua palavra.

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, porém, andava preocupada com muito serviço; e aproximando-se, disse: Senhor, não se te dá que minha irmã me tenha deixado a servir sozinha? Dize-lhe, pois, que me ajude.

[[v42-10-41]]

^<<v42-10-41,41>>^ Respondeu-lhe o Senhor: Marta, Marta, estás ansiosa e perturbada com muitas coisas;

[[v42-10-42]]

^<<v42-10-42,42>>^ entretanto poucas são necessárias, ou mesmo uma só; e Maria escolheu a boa parte, a qual não lhe será tirada.

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]