include::./index.adoc[]

[[v42-12-0]]
=== Lucas, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-12-1]]

^<<v42-12-1,1>>^ Ajuntando-se entretanto muitos milhares de pessoas, de sorte que se atropelavam uns aos outros, começou Jesus a dizer primeiro aos seus discípulos: Acautelai-vos do fermento dos fariseus, que é a hipocrisia.

[[v42-12-2]]

^<<v42-12-2,2>>^ Mas nada há encoberto, que não haja de ser descoberto; nem oculto, que não haja de ser conhecido.

[[v42-12-3]]

^<<v42-12-3,3>>^ Porquanto tudo o que em trevas dissestes, à luz será ouvido; e o que falaste ao ouvido no gabinete, dos eirados será apregoado.

[[v42-12-4]]

^<<v42-12-4,4>>^ Digo-vos, amigos meus: Não temais os que matam o corpo, e depois disso nada mais podem fazer.

[[v42-12-5]]

^<<v42-12-5,5>>^ Mas eu vos mostrarei a quem é que deveis temer; temei aquele que, depois de matar, tem poder para lançar no inferno; sim, digo, a esse temei.

[[v42-12-6]]

^<<v42-12-6,6>>^ Não se vendem cinco passarinhos por dois asses? E nenhum deles está esquecido diante de Deus.

[[v42-12-7]]

^<<v42-12-7,7>>^ Mas até os cabelos da vossa cabeça estão todos contados. Não temais, pois mais valeis vós do que muitos passarinhos.

[[v42-12-8]]

^<<v42-12-8,8>>^ E digo-vos que todo aquele que me confessar diante dos homens, também o Filho do homem o confessará diante dos anjos de Deus;

[[v42-12-9]]

^<<v42-12-9,9>>^ mas quem me negar diante dos homens, será negado diante dos anjos de Deus.

[[v42-12-10]]

^<<v42-12-10,10>>^ E a todo aquele que proferir uma palavra contra o Filho do homem, isso lhe será perdoado; mas ao que blasfemar contra o Espírito Santo, não lhe será perdoado.

[[v42-12-11]]

^<<v42-12-11,11>>^ Quando, pois, vos levarem às sinagogas, aos magistrados e às autoridades, não estejais solícitos de como ou do que haveis de responder, nem do que haveis de dizer.

[[v42-12-12]]

^<<v42-12-12,12>>^ Porque o Espírito Santo vos ensinará na mesma hora o que deveis dizer.

[[v42-12-13]]

^<<v42-12-13,13>>^ Disse-lhe alguém dentre a multidão: Mestre, dize a meu irmão que reparte comigo a herança.

[[v42-12-14]]

^<<v42-12-14,14>>^ Mas ele lhe respondeu: Homem, quem me constituiu a mim juiz ou repartidor entre vós?

[[v42-12-15]]

^<<v42-12-15,15>>^ E disse ao povo: Acautelai-vos e guardai-vos de toda espécie de cobiça; porque a vida do homem não consiste na abundância das coisas que possui.

[[v42-12-16]]

^<<v42-12-16,16>>^ Propôs-lhes então uma parábola, dizendo: O campo de um homem rico produzira com abundância;

[[v42-12-17]]

^<<v42-12-17,17>>^ e ele arrazoava consigo, dizendo: Que farei? Pois não tenho onde recolher os meus frutos.

[[v42-12-18]]

^<<v42-12-18,18>>^ Disse então: Farei isto: derribarei os meus celeiros e edificarei outros maiores, e ali recolherei todos os meus cereais e os meus bens;

[[v42-12-19]]

^<<v42-12-19,19>>^ e direi à minha alma: Alma, tens em depósito muitos bens para muitos anos; descansa, come, bebe, regala-te.

[[v42-12-20]]

^<<v42-12-20,20>>^ Mas Deus lhe disse: Insensato, esta noite te pedirão a tua alma; e o que tens preparado, para quem será?

[[v42-12-21]]

^<<v42-12-21,21>>^ Assim é aquele que para si ajunta tesouros, e não é rico para com Deus.

[[v42-12-22]]

^<<v42-12-22,22>>^ E disse aos seus discípulos: Por isso vos digo: Não estejais ansiosos quanto à vossa vida, pelo que haveis de comer, nem quanto ao corpo, pelo que haveis de vestir.

[[v42-12-23]]

^<<v42-12-23,23>>^ Pois a vida é mais do que o alimento, e o corpo mais do que o vestuário.

[[v42-12-24]]

^<<v42-12-24,24>>^ Considerai os corvos, que não semeiam nem ceifam; não têm despensa nem celeiro; contudo, Deus os alimenta. Quanto mais não valeis vós do que as aves!

[[v42-12-25]]

^<<v42-12-25,25>>^ Ora, qual de vós, por mais ansioso que esteja, pode acrescentar um côvado à sua estatura?

[[v42-12-26]]

^<<v42-12-26,26>>^ Porquanto, se não podeis fazer nem as coisas mínimas, por que estais ansiosos pelas outras?

[[v42-12-27]]

^<<v42-12-27,27>>^ Considerai os lírios, como crescem; não trabalham, nem fiam; contudo vos digo que nem mesmo Salomão, em toda a sua glória, se vestiu como um deles.

[[v42-12-28]]

^<<v42-12-28,28>>^ Se, pois, Deus assim veste a erva que hoje está no campo e amanhã é lançada no forno, quanto mais vós, homens de pouca fé?

[[v42-12-29]]

^<<v42-12-29,29>>^ Não procureis, pois, o que haveis de comer, ou o que haveis de beber, e não andeis preocupados.

[[v42-12-30]]

^<<v42-12-30,30>>^ Porque a todas estas coisas os povos do mundo procuram; mas vosso Pai sabe que precisais delas.

[[v42-12-31]]

^<<v42-12-31,31>>^ Buscai antes o seu reino, e estas coisas vos serão acrescentadas.

[[v42-12-32]]

^<<v42-12-32,32>>^ Não temas, ó pequeno rebanho! porque a vosso Pai agradou dar-vos o reino.

[[v42-12-33]]

^<<v42-12-33,33>>^ Vendei o que possuís, e dai esmolas. Fazei para vós bolsas que não envelheçam; tesouro nos céus que jamais acabe, aonde não chega ladrão e a traça não rói.

[[v42-12-34]]

^<<v42-12-34,34>>^ Porque, onde estiver o vosso tesouro, aí estará também o vosso coração.

[[v42-12-35]]

^<<v42-12-35,35>>^ Estejam cingidos os vossos lombos e acesas as vossas candeias;

[[v42-12-36]]

^<<v42-12-36,36>>^ e sede semelhantes a homens que esperam o seu senhor, quando houver de voltar das bodas, para que, quando vier e bater, logo possam abrir-lhe.

[[v42-12-37]]

^<<v42-12-37,37>>^ Bem-aventurados aqueles servos, aos quais o senhor, quando vier, achar vigiando! Em verdade vos digo que se cingirá, e os fará reclinar-se à mesa e, chegando-se, os servirá.

[[v42-12-38]]

^<<v42-12-38,38>>^ Quer venha na segunda vigília, quer na terceira, bem-aventurados serão eles, se assim os achar.

[[v42-12-39]]

^<<v42-12-39,39>>^ Sabei, porém, isto: se o dono da casa soubesse a que hora havia de vir o ladrão, vigiaria e não deixaria minar a sua casa.

[[v42-12-40]]

^<<v42-12-40,40>>^ Estai vós também apercebidos; porque, numa hora em que não penseis, virá o Filho do homem.

[[v42-12-41]]

^<<v42-12-41,41>>^ Então Pedro perguntou: Senhor, dizes essa parábola a nós, ou também a todos?

[[v42-12-42]]

^<<v42-12-42,42>>^ Respondeu o Senhor: Qual é, pois, o mordomo fiel e prudente, que o Senhor porá sobre os seus servos, para lhes dar a tempo a ração?

[[v42-12-43]]

^<<v42-12-43,43>>^ Bem-aventurado aquele servo a quem o seu senhor, quando vier, achar fazendo assim.

[[v42-12-44]]

^<<v42-12-44,44>>^ Em verdade vos digo que o porá sobre todos os seus bens.

[[v42-12-45]]

^<<v42-12-45,45>>^ Mas, se aquele servo disser em teu coração: O meu senhor tarda em vir; e começar a espancar os criados e as criadas, e a comer, a beber e a embriagar-se,

[[v42-12-46]]

^<<v42-12-46,46>>^ virá o senhor desse servo num dia em que não o espera, e numa hora de que não sabe, e cortá-lo-á pelo meio, e lhe dará a sua parte com os infiéis.

[[v42-12-47]]

^<<v42-12-47,47>>^ O servo que soube a vontade do seu senhor, e não se aprontou, nem fez conforme a sua vontade, será castigado com muitos açoites;

[[v42-12-48]]

^<<v42-12-48,48>>^ mas o que não a soube, e fez coisas que mereciam castigo, com poucos açoites será castigado. Daquele a quem muito é dado, muito se lhe requererá; e a quem muito é confiado, mais ainda se lhe pedirá.

[[v42-12-49]]

^<<v42-12-49,49>>^ Vim lançar fogo à terra; e que mais quero, se já está aceso?

[[v42-12-50]]

^<<v42-12-50,50>>^ Há um batismo em que hei de ser batizado; e como me angustio até que venha a cumprir-se!

[[v42-12-51]]

^<<v42-12-51,51>>^ Cuidais vós que vim trazer paz à terra? Não, eu vos digo, mas antes dissensão:

[[v42-12-52]]

^<<v42-12-52,52>>^ pois daqui em diante estarão cinco pessoas numa casa divididas, três contra duas, e duas contra três;

[[v42-12-53]]

^<<v42-12-53,53>>^ estarão divididos: pai contra filho, e filho contra pai; mãe contra filha, e filha contra mãe; sogra contra nora, e nora contra sogra.

[[v42-12-54]]

^<<v42-12-54,54>>^ Dizia também às multidões: Quando vedes subir uma nuvem do ocidente, logo dizeis: Lá vem chuva; e assim sucede;

[[v42-12-55]]

^<<v42-12-55,55>>^ e quando vedes soprar o vento sul dizeis; Haverá calor; e assim sucede.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hipócritas, sabeis discernir a face da terra e do céu; como não sabeis então discernir este tempo?

[[v42-12-57]]

^<<v42-12-57,57>>^ E por que não julgais também por vós mesmos o que é justo?

[[v42-12-58]]

^<<v42-12-58,58>>^ Quando, pois, vais com o teu adversário ao magistrado, procura fazer as pazes com ele no caminho; para que não suceda que ele te arraste ao juiz, e o juiz te entregue ao meirinho, e o meirinho te lance na prisão

[[v42-12-59]]

^<<v42-12-59,59>>^ Digo-te que não sairás dali enquanto não pagares o derradeiro lepto.

'''

xref:042-lucas/042-lucas-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-lucas/042-lucas-013.adoc#v42-13-0[Próximo Capítulo &#62;]