include::./index.adoc[]

[[v42-8-0]]
=== Lucas, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-8-1]]

^<<v42-8-1,1>>^ Logo depois disso, andava Jesus de cidade em cidade, e de aldeia em aldeia, pregando e anunciando o evangelho do reino de Deus; e iam com ele os doze,

[[v42-8-2]]

^<<v42-8-2,2>>^ bem como algumas mulheres que haviam sido curadas de espíritos malignos e de enfermidades: Maria, chamada Madalena, da qual tinham saído sete demônios.

[[v42-8-3]]

^<<v42-8-3,3>>^ Joana, mulher de Cuza, procurador de Herodes, Susana, e muitas outras que os serviam com os seus bens.

[[v42-8-4]]

^<<v42-8-4,4>>^ Ora, ajuntando-se uma grande multidão, e vindo ter com ele gente de todas as cidades, disse Jesus por parábola:

[[v42-8-5]]

^<<v42-8-5,5>>^ Saiu o semeador a semear a sua semente. E quando semeava, uma parte da semente caiu à beira do caminho; e foi pisada, e as aves do céu a comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Outra caiu sobre pedra; e, nascida, secou-se porque não havia umidade.

[[v42-8-7]]

^<<v42-8-7,7>>^ E outra caiu no meio dos espinhos; e crescendo com ela os espinhos, sufocaram-na.

[[v42-8-8]]

^<<v42-8-8,8>>^ Mas outra caiu em boa terra; e, nascida, produziu fruto, cem por um. Dizendo ele estas coisas, clamava: Quem tem ouvidos para ouvir, ouça.

[[v42-8-9]]

^<<v42-8-9,9>>^ Perguntaram-lhe então seus discípulos o que significava essa parábola.

[[v42-8-10]]

^<<v42-8-10,10>>^ Respondeu ele: A vós é dado conhecer os mistérios do reino de Deus; mas aos outros se fala por parábolas; para que vendo, não vejam, e ouvindo, não entendam.

[[v42-8-11]]

^<<v42-8-11,11>>^ É, pois, esta a parábola: A semente é a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ Os que estão à beira do caminho são os que ouvem; mas logo vem o Diabo e tira-lhe do coração a palavra, para que não suceda que, crendo, sejam salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ Os que estão sobre a pedra são os que, ouvindo a palavra, a recebem com alegria; mas estes não têm raiz, apenas crêem por algum tempo, mas na hora da provação se desviam.

[[v42-8-14]]

^<<v42-8-14,14>>^ A parte que caiu entre os espinhos são os que ouviram e, indo seu caminho, são sufocados pelos cuidados, riquezas, e deleites desta vida e não dão fruto com perfeição.

[[v42-8-15]]

^<<v42-8-15,15>>^ Mas a que caiu em boa terra são os que, ouvindo a palavra com coração reto e bom, a retêm e dão fruto com perseverança.

[[v42-8-16]]

^<<v42-8-16,16>>^ Ninguém, pois, acende uma candeia e a cobre com algum vaso, ou a põe debaixo da cama; mas põe-na no velador, para que os que entram vejam a luz.

[[v42-8-17]]

^<<v42-8-17,17>>^ Porque não há coisa encoberta que não haja de manifestar-se, nem coisa secreta que não haja de saber-se e vir à luz.

[[v42-8-18]]

^<<v42-8-18,18>>^ Vede, pois, como ouvis; porque a qualquer que tiver lhe será dado, e a qualquer que não tiver, até o que parece ter lhe será tirado.

[[v42-8-19]]

^<<v42-8-19,19>>^ Vieram, então, ter com ele sua mãe e seus irmãos, e não podiam aproximar-se dele por causa da multidão.

[[v42-8-20]]

^<<v42-8-20,20>>^ Foi-lhe dito: Tua mãe e teus irmãos estão lá fora, e querem ver-te.

[[v42-8-21]]

^<<v42-8-21,21>>^ Ele, porém, lhes respondeu: Minha mãe e meus irmãos são estes que ouvem a palavra de Deus e a observam.

[[v42-8-22]]

^<<v42-8-22,22>>^ Ora, aconteceu certo dia que entrou num barco com seus discípulos, e disse-lhes: Passemos à outra margem do lago. E partiram.

[[v42-8-23]]

^<<v42-8-23,23>>^ Enquanto navegavam, ele adormeceu; e desceu uma tempestade de vento sobre o lago; e o barco se enchia de água, de sorte que perigavam.

[[v42-8-24]]

^<<v42-8-24,24>>^ Chegando-se a ele, o despertaram, dizendo: Mestre, Mestre, estamos perecendo. E ele, levantando-se, repreendeu o vento e a fúria da água; e cessaram, e fez-se bonança.

[[v42-8-25]]

^<<v42-8-25,25>>^ Então lhes perguntou: Onde está a vossa fé? Eles, atemorizados, admiraram-se, dizendo uns aos outros: Quem, pois, é este, que até aos ventos e à água manda, e lhe obedecem?

[[v42-8-26]]

^<<v42-8-26,26>>^ Apontaram à terra dos gerasenos, que está defronte da Galiléia.

[[v42-8-27]]

^<<v42-8-27,27>>^ Logo que saltou em terra, saiu-lhe ao encontro um homem da cidade, possesso de demônios, que havia muito tempo não vestia roupa, nem morava em casa, mas nos sepulcros.

[[v42-8-28]]

^<<v42-8-28,28>>^ Quando ele viu a Jesus, gritou, prostrou-se diante dele, e com grande voz exclamou: Que tenho eu contigo, Jesus, Filho do Deus Altíssimo? Rogo-te que não me atormentes.

[[v42-8-29]]

^<<v42-8-29,29>>^ Porque Jesus ordenara ao espírito imundo que saísse do homem. Pois já havia muito tempo que se apoderara dele; e guardavam-no preso com grilhões e cadeias; mas ele, quebrando as prisões, era impelido pelo demônio para os desertos.

[[v42-8-30]]

^<<v42-8-30,30>>^ Perguntou-lhe Jesus: Qual é o teu nome? Respondeu ele: Legião; porque tinham entrado nele muitos demônios.

[[v42-8-31]]

^<<v42-8-31,31>>^ E rogavam-lhe que não os mandasse para o abismo.

[[v42-8-32]]

^<<v42-8-32,32>>^ Ora, andava ali pastando no monte uma grande manada de porcos; rogaram-lhe, pois que lhes permitisse entrar neles, e lho permitiu.

[[v42-8-33]]

^<<v42-8-33,33>>^ E tendo os demônios saído do homem, entraram nos porcos; e a manada precipitou-se pelo despenhadeiro no lago, e afogou-se.

[[v42-8-34]]

^<<v42-8-34,34>>^ Quando os pastores viram o que acontecera, fugiram, e foram anunciá-lo na cidade e nos campos.

[[v42-8-35]]

^<<v42-8-35,35>>^ Saíram, pois, a ver o que tinha acontecido, e foram ter com Jesus, a cujos pés acharam sentado, vestido e em perfeito juízo, o homem de quem havia saído os demônios; e se atemorizaram.

[[v42-8-36]]

^<<v42-8-36,36>>^ Os que tinham visto aquilo contaram-lhes como fora curado o endemoninhado.

[[v42-8-37]]

^<<v42-8-37,37>>^ Então todo o povo da região dos gerasenos rogou-lhe que se retirasse deles; porque estavam possuídos de grande medo. Pelo que ele entrou no barco, e voltou.

[[v42-8-38]]

^<<v42-8-38,38>>^ Pedia-lhe, porém, o homem de quem haviam saído os demônios que o deixasse estar com ele; mas Jesus o despediu, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ Volta para tua casa, e conta tudo quanto Deus te fez. E ele se retirou, publicando por toda a cidade tudo quanto Jesus lhe fizera.

[[v42-8-40]]

^<<v42-8-40,40>>^ Quando Jesus voltou, a multidão o recebeu; porque todos o estavam esperando.

[[v42-8-41]]

^<<v42-8-41,41>>^ E eis que veio um homem chamado Jairo, que era chefe da sinagoga; e prostrando-se aos pés de Jesus, rogava-lhe que fosse a sua casa;

[[v42-8-42]]

^<<v42-8-42,42>>^ porque tinha uma filha única, de cerca de doze anos, que estava à morte. Enquanto, pois, ele ia, apertavam-no as multidões.

[[v42-8-43]]

^<<v42-8-43,43>>^ E certa mulher, que tinha uma hemorragia havia doze anos &#123;e gastara com os médicos todos os seus haveres&#125; e por ninguém pudera ser curada,

[[v42-8-44]]

^<<v42-8-44,44>>^ chegando-se por detrás, tocou-lhe a orla do manto, e imediatamente cessou a sua hemorragia.

[[v42-8-45]]

^<<v42-8-45,45>>^ Perguntou Jesus: Quem é que me tocou? Como todos negassem, disse-lhe Pedro: Mestre, as multidões te apertam e te oprimem.

[[v42-8-46]]

^<<v42-8-46,46>>^ Mas disse Jesus: Alguém me tocou; pois percebi que de mim saiu poder.

[[v42-8-47]]

^<<v42-8-47,47>>^ Então, vendo a mulher que não passara despercebida, aproximou-se tremendo e, prostrando-se diante dele, declarou-lhe perante todo o povo a causa por que lhe havia tocado, e como fora imediatamente curada.

[[v42-8-48]]

^<<v42-8-48,48>>^ Disse-lhe ele: Filha, a tua fé te salvou; vai-te em paz.

[[v42-8-49]]

^<<v42-8-49,49>>^ Enquanto ainda falava, veio alguém da casa do chefe da sinagoga dizendo: A tua filha já está morta; não incomodes mais o Mestre.

[[v42-8-50]]

^<<v42-8-50,50>>^ Jesus, porém, ouvindo-o, respondeu-lhe: Não temas: crê somente, e será salva.

[[v42-8-51]]

^<<v42-8-51,51>>^ Tendo chegado à casa, a ninguém deixou entrar com ele, senão a Pedro, João, Tiago, e o pai e a mãe da menina.

[[v42-8-52]]

^<<v42-8-52,52>>^ E todos choravam e pranteavam; ele, porém, disse: Não choreis; ela não está morta, mas dorme.

[[v42-8-53]]

^<<v42-8-53,53>>^ E riam-se dele, sabendo que ela estava morta.

[[v42-8-54]]

^<<v42-8-54,54>>^ Então ele, tomando-lhe a mão, exclamou: Menina, levanta-te.

[[v42-8-55]]

^<<v42-8-55,55>>^ E o seu espírito voltou, e ela se levantou imediatamente; e Jesus mandou que lhe desse de comer.

[[v42-8-56]]

^<<v42-8-56,56>>^ E seus pais ficaram maravilhados; e ele mandou-lhes que a ninguém contassem o que havia sucedido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]