include::./index.adoc[]

[[v42-20-0]]
=== Lucas, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-20-1]]

^<<v42-20-1,1>>^ Num desses dias, quando Jesus ensinava o povo no templo, e anunciava o evangelho, sobrevieram os principais sacerdotes e os escribas, com os anciãos.

[[v42-20-2]]

^<<v42-20-2,2>>^ e falaram-lhe deste modo: Dize-nos, com que autoridade fazes tu estas coisas? Ou, quem é o que te deu esta autoridade?

[[v42-20-3]]

^<<v42-20-3,3>>^ Respondeu-lhes ele: Eu também vos farei uma pergunta; dizei-me, pois:

[[v42-20-4]]

^<<v42-20-4,4>>^ O batismo de João era do céu ou dos homens?

[[v42-20-5]]

^<<v42-20-5,5>>^ Ao que eles arrazoavam entre si: Se dissermos: do céu, ele dirá: Por que não crestes?

[[v42-20-6]]

^<<v42-20-6,6>>^ Mas, se dissermos: Dos homens, todo o povo nos apedrejará; pois está convencido de que João era profeta.

[[v42-20-7]]

^<<v42-20-7,7>>^ Responderam, pois, que não sabiam donde era.

[[v42-20-8]]

^<<v42-20-8,8>>^ Replicou-lhes Jesus: Nem eu vos digo com que autoridade faço estas coisas.

[[v42-20-9]]

^<<v42-20-9,9>>^ Começou então a dizer ao povo esta parábola: Um homem plantou uma vinha, arrendou-a a uns lavradores, e ausentou-se do país por muito tempo.

[[v42-20-10]]

^<<v42-20-10,10>>^ No tempo próprio mandou um servo aos lavradores, para que lhe dessem dos frutos da vinha; mas os lavradores, espancando-o, mandaram-no embora de mãos vazias.

[[v42-20-11]]

^<<v42-20-11,11>>^ Tornou a mandar outro servo; mas eles espancaram também a este e, afrontando-o, mandaram-no embora de mãos vazias.

[[v42-20-12]]

^<<v42-20-12,12>>^ E mandou ainda um terceiro; mas feriram também a este e lançaram-no fora.

[[v42-20-13]]

^<<v42-20-13,13>>^ Disse então o senhor da vinha: Que farei? Mandarei o meu filho amado; a ele talvez respeitarão.

[[v42-20-14]]

^<<v42-20-14,14>>^ Mas quando os lavradores o viram, arrazoaram entre si, dizendo: Este é o herdeiro; matemo-lo, para que a herança seja nossa.

[[v42-20-15]]

^<<v42-20-15,15>>^ E lançando-o fora da vinha, o mataram. Que lhes fará, pois, o senhor da vinha?

[[v42-20-16]]

^<<v42-20-16,16>>^ Virá e destruirá esses lavradores, e dará a vinha a outros. Ouvindo eles isso, disseram: Tal não aconteça!

[[v42-20-17]]

^<<v42-20-17,17>>^ Mas Jesus, olhando para eles, disse: Pois, que quer dizer isto que está escrito: A pedra que os edificadores rejeitaram, essa foi posta como pedra angular?

[[v42-20-18]]

^<<v42-20-18,18>>^ Todo o que cair sobre esta pedra será despedaçado; mas aquele sobre quem ela cair será reduzido a pó.

[[v42-20-19]]

^<<v42-20-19,19>>^ Ainda na mesma hora os escribas e os principais sacerdotes, percebendo que contra eles proferira essa parábola, procuraram deitar-lhe as mãos, mas temeram o povo.

[[v42-20-20]]

^<<v42-20-20,20>>^ E, aguardando oportunidade, mandaram espias, os quais se fingiam justos, para o apanharem em alguma palavra, e o entregarem à jurisdição e à autoridade do governador.

[[v42-20-21]]

^<<v42-20-21,21>>^ Estes, pois, o interrogaram, dizendo: Mestre, sabemos que falas e ensinas retamente, e que não consideras a aparência da pessoa, mas ensinas segundo a verdade o caminho de Deus;

[[v42-20-22]]

^<<v42-20-22,22>>^ é-nos lícito dar tributo a César, ou não?

[[v42-20-23]]

^<<v42-20-23,23>>^ Mas Jesus, percebendo a astúcia deles, disse-lhes:

[[v42-20-24]]

^<<v42-20-24,24>>^ Mostrai-me um denário. De quem é a imagem e a inscrição que ele tem? Responderam: De César.

[[v42-20-25]]

^<<v42-20-25,25>>^ Disse-lhes então: Dai, pois, a César o que é de César, e a Deus o que é de Deus.

[[v42-20-26]]

^<<v42-20-26,26>>^ E não puderam apanhá-lo em palavra alguma diante do povo; e admirados da sua resposta, calaram-se.

[[v42-20-27]]

^<<v42-20-27,27>>^ Chegaram então alguns dos saduceus, que dizem não haver ressurreição, e perguntaram-lhe:

[[v42-20-28]]

^<<v42-20-28,28>>^ Mestre, Moisés nos deixou escrito que se morrer alguém, tendo mulher mas não tendo filhos, o irmão dele case com a viúva, e suscite descendência ao irmão.

[[v42-20-29]]

^<<v42-20-29,29>>^ Havia, pois, sete irmãos. O primeiro casou-se e morreu sem filhos;

[[v42-20-30]]

^<<v42-20-30,30>>^ então o segundo, e depois o terceiro, casaram com a viúva;

[[v42-20-31]]

^<<v42-20-31,31>>^ e assim todos os sete, e morreram, sem deixar filhos.

[[v42-20-32]]

^<<v42-20-32,32>>^ Depois morreu também a mulher.

[[v42-20-33]]

^<<v42-20-33,33>>^ Portanto, na ressurreição, de qual deles será ela esposa, pois os sete por esposa a tiveram?

[[v42-20-34]]

^<<v42-20-34,34>>^ Respondeu-lhes Jesus: Os filhos deste mundo casaram-se e dão-se em casamento;

[[v42-20-35]]

^<<v42-20-35,35>>^ mas os que são julgados dignos de alcançar o mundo vindouro, e a ressurreição dentre os mortos, nem se casam nem se dão em casamento;

[[v42-20-36]]

^<<v42-20-36,36>>^ porque já não podem mais morrer; pois são iguais aos anjos, e são filhos de Deus, sendo filhos da ressurreição.

[[v42-20-37]]

^<<v42-20-37,37>>^ Mas que os mortos hão de ressurgir, o próprio Moisés o mostrou, na passagem a respeito da sarça, quando chama ao Senhor; Deus de Abraão, e Deus de Isaque, e Deus de Jacó.

[[v42-20-38]]

^<<v42-20-38,38>>^ Ora, ele não é Deus de mortos, mas de vivos; porque para ele todos vivem.

[[v42-20-39]]

^<<v42-20-39,39>>^ Responderam alguns dos escribas: Mestre, disseste bem.

[[v42-20-40]]

^<<v42-20-40,40>>^ Não ousavam, pois, perguntar-lhe mais coisa alguma.

[[v42-20-41]]

^<<v42-20-41,41>>^ Jesus, porém, lhes perguntou: Como dizem que o Cristo é filho de Davi?

[[v42-20-42]]

^<<v42-20-42,42>>^ Pois o próprio Davi diz no livro dos Salmos: Disse o Senhor ao meu Senhor: Assenta-te à minha direita,

[[v42-20-43]]

^<<v42-20-43,43>>^ até que eu ponha os teus inimigos por escabelo dos teus pés.

[[v42-20-44]]

^<<v42-20-44,44>>^ Logo Davi lhe chama Senhor como, pois, é ele seu filho?

[[v42-20-45]]

^<<v42-20-45,45>>^ Enquanto todo o povo o ouvia, disse Jesus aos seus discípulos:

[[v42-20-46]]

^<<v42-20-46,46>>^ Guardai-vos dos escribas, que querem andar com vestes compridas, e gostam das saudações nas praças, dos primeiros assentos nas sinagogas, e dos primeiros lugares nos banquetes;

[[v42-20-47]]

^<<v42-20-47,47>>^ que devoram as casas das viúvas, fazendo, por pretexto, longas orações; estes hão de receber maior condenação.

'''

xref:042-lucas/042-lucas-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-lucas/042-lucas-021.adoc#v42-21-0[Próximo Capítulo &#62;]