include::./index.adoc[]

[[v42-6-0]]
=== Lucas, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-6-1]]

^<<v42-6-1,1>>^ E sucedeu que, num dia de sábado, passava Jesus pelas searas; e seus discípulos iam colhendo espigas e, debulhando-as com as mãos, as comiam.

[[v42-6-2]]

^<<v42-6-2,2>>^ Alguns dos fariseus, porém, perguntaram; Por que estais fazendo o que não é lícito fazer nos sábados?

[[v42-6-3]]

^<<v42-6-3,3>>^ E Jesus, respondendo-lhes, disse: Nem ao menos tendes lido o que fez Davi quando teve fome, ele e seus companheiros?

[[v42-6-4]]

^<<v42-6-4,4>>^ Como entrou na casa de Deus, tomou os pães da proposição, dos quais não era lícito comer senão só aos sacerdotes, e deles comeu e deu também aos companheiros?

[[v42-6-5]]

^<<v42-6-5,5>>^ Também lhes disse: O Filho do homem é Senhor do sábado.

[[v42-6-6]]

^<<v42-6-6,6>>^ Ainda em outro sábado entrou na sinagoga, e pôs-se a ensinar. Estava ali um homem que tinha a mão direita atrofiada.

[[v42-6-7]]

^<<v42-6-7,7>>^ E os escribas e os fariseus observavam-no, para ver se curaria em dia de sábado, para acharem de que o acusar.

[[v42-6-8]]

^<<v42-6-8,8>>^ Mas ele, conhecendo-lhes os pensamentos, disse ao homem que tinha a mão atrofiada: Levanta-te, e fica em pé aqui no maio. E ele, levantando-se, ficou em pé.

[[v42-6-9]]

^<<v42-6-9,9>>^ Disse-lhes, então, Jesus: Eu vos pergunto: É lícito no sábado fazer bem, ou fazer mal? salvar a vida, ou tirá-la?

[[v42-6-10]]

^<<v42-6-10,10>>^ E olhando para todos em redor, disse ao homem: Estende a tua mão. Ele assim o fez, e a mão lhe foi restabelecida.

[[v42-6-11]]

^<<v42-6-11,11>>^ Mas eles se encheram de furor; e uns com os outros conferenciam sobre o que fariam a Jesus.

[[v42-6-12]]

^<<v42-6-12,12>>^ Naqueles dias retirou-se para o monte a fim de orar; e passou a noite toda em oração a Deus.

[[v42-6-13]]

^<<v42-6-13,13>>^ Depois do amanhecer, chamou seus discípulos, e escolheu doze dentre eles, aos quais deu também o nome de apóstolos:

[[v42-6-14]]

^<<v42-6-14,14>>^ Simão, ao qual também chamou Pedro, e André, seu irmão; Tiago e João; Filipe e Bartolomeu;

[[v42-6-15]]

^<<v42-6-15,15>>^ Mateus e Tomé; Tiago, filho de Alfeu, e Simão, chamado Zelote;

[[v42-6-16]]

^<<v42-6-16,16>>^ Judas, filho de Tiago; e Judas Iscariotes, que veio a ser o traidor.

[[v42-6-17]]

^<<v42-6-17,17>>^ E Jesus, descendo com eles, parou num lugar plano, onde havia não só grande número de seus discípulos, mas também grande multidão do povo, de toda a Judéia e Jerusalém, e do litoral de Tiro e de Sidom, que tinham vindo para ouvi-lo e serem curados das suas doenças;

[[v42-6-18]]

^<<v42-6-18,18>>^ e os que eram atormentados por espíritos imundos ficavam curados.

[[v42-6-19]]

^<<v42-6-19,19>>^ E toda a multidão procurava tocar-lhe; porque saía dele poder que curava a todos.

[[v42-6-20]]

^<<v42-6-20,20>>^ Então, levantando ele os olhos para os seus discípulos, dizia: Bem-aventurados vós, os pobres, porque vosso é o reino de Deus.

[[v42-6-21]]

^<<v42-6-21,21>>^ Bem-aventurados vós, que agora tendes fome, porque sereis fartos. Bem-aventurados vós, que agora chorais, porque haveis de rir.

[[v42-6-22]]

^<<v42-6-22,22>>^ Bem-aventurados sereis quando os homens vos odiarem, e quando vos expulsarem da sua companhia, e vos injuriarem, e rejeitarem o vosso nome como indigno, por causa do Filho do homem.

[[v42-6-23]]

^<<v42-6-23,23>>^ Regozijai-vos nesse dia e exultai, porque eis que é grande o vosso galardão no céu; pois assim faziam os seus pais aos profetas.

[[v42-6-24]]

^<<v42-6-24,24>>^ Mas ai de vós que sois ricos! porque já recebestes a vossa consolação.

[[v42-6-25]]

^<<v42-6-25,25>>^ Ai de vós, os que agora estais fartos! porque tereis fome. Ai de vós, os que agora rides! porque vos lamentareis e chorareis.

[[v42-6-26]]

^<<v42-6-26,26>>^ Ai de vós, quando todos os homens vos louvarem! porque assim faziam os seus pais aos falsos profetas.

[[v42-6-27]]

^<<v42-6-27,27>>^ Mas a vós que ouvis, digo: Amai a vossos inimigos, fazei bem aos que vos odeiam,

[[v42-6-28]]

^<<v42-6-28,28>>^ bendizei aos que vos maldizem, e orai pelos que vos caluniam.

[[v42-6-29]]

^<<v42-6-29,29>>^ Ao que te ferir numa face, oferece-lhe também a outra; e ao que te houver tirado a capa, não lhe negues também a túnica.

[[v42-6-30]]

^<<v42-6-30,30>>^ Dá a todo o que te pedir; e ao que tomar o que é teu, não lho reclames.

[[v42-6-31]]

^<<v42-6-31,31>>^ Assim como quereis que os homens vos façam, do mesmo modo lhes fazei vós também.

[[v42-6-32]]

^<<v42-6-32,32>>^ Se amardes aos que vos amam, que mérito há nisso? Pois também os pecadores amam aos que os amam.

[[v42-6-33]]

^<<v42-6-33,33>>^ E se fizerdes bem aos que vos fazem bem, que mérito há nisso? Também os pecadores fazem o mesmo.

[[v42-6-34]]

^<<v42-6-34,34>>^ E se emprestardes àqueles de quem esperais receber, que mérito há nisso? Também os pecadores emprestam aos pecadores, para receberem outro tanto.

[[v42-6-35]]

^<<v42-6-35,35>>^ Amai, porém a vossos inimigos, fazei bem e emprestai, nunca desanimado; e grande será a vossa recompensa, e sereis filhos do Altíssimo; porque ele é benigno até para com os integrantes e maus.

[[v42-6-36]]

^<<v42-6-36,36>>^ Sede misericordiosos, como também vosso Pai é misericordioso.

[[v42-6-37]]

^<<v42-6-37,37>>^ Não julgueis, e não sereis julgados; não condeneis, e não sereis condenados; perdoai, e sereis perdoados.

[[v42-6-38]]

^<<v42-6-38,38>>^ Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos deitarão no regaço; porque com a mesma medida com que medis, vos medirão a vós.

[[v42-6-39]]

^<<v42-6-39,39>>^ E propôs-lhes também uma parábola: Pode porventura um cego guiar outro cego? não cairão ambos no barranco?

[[v42-6-40]]

^<<v42-6-40,40>>^ Não é o discípulo mais do que o seu mestre; mas todo o que for bem instruído será como o seu mestre.

[[v42-6-41]]

^<<v42-6-41,41>>^ Por que vês o argueiro no olho de teu irmão, e não reparas na trave que está no teu próprio olho?

[[v42-6-42]]

^<<v42-6-42,42>>^ Ou como podes dizer a teu irmão: Irmão, deixa-me tirar o argueiro que está no teu olho, não vendo tu mesmo a trave que está no teu? Hipócrita! tira primeiro a trave do teu olho; e então verás bem para tirar o argueiro que está no olho de teu irmão.

[[v42-6-43]]

^<<v42-6-43,43>>^ Porque não há árvore boa que dê mau fruto nem tampouco árvore má que dê bom fruto.

[[v42-6-44]]

^<<v42-6-44,44>>^ Porque cada árvore se conhece pelo seu próprio fruto; pois dos espinheiros não se colhem figos, nem dos abrolhos se vindimam uvas.

[[v42-6-45]]

^<<v42-6-45,45>>^ O homem bom, do bom tesouro do seu coração tira o bem; e o homem mau, do seu mau tesouro tira o mal; pois do que há em abundância no coração, disso fala a boca.

[[v42-6-46]]

^<<v42-6-46,46>>^ E por que me chamais: Senhor, Senhor, e não fazeis o que eu vos digo?

[[v42-6-47]]

^<<v42-6-47,47>>^ Todo aquele que vem a mim, e ouve as minhas palavras, e as pratica, eu vos mostrarei a quem é semelhante:

[[v42-6-48]]

^<<v42-6-48,48>>^ É semelhante ao homem que, edificando uma casa, cavou, abriu profunda vala, e pôs os alicerces sobre a rocha; e vindo a enchente, bateu com ímpeto a torrente naquela casa, e não a pôde abalar, porque tinha sido bem edificada.

[[v42-6-49]]

^<<v42-6-49,49>>^ Mas o que ouve e não pratica é semelhante a um homem que edificou uma casa sobre terra, sem alicerces, na qual bateu com ímpeto a torrente, e logo caiu; e foi grande a ruína daquela casa.

'''

xref:042-lucas/042-lucas-005.adoc#v42-5-0[&#60; Capítulo Anterior] | <<v42-6-0,Topo>> | xref:042-lucas/042-lucas-007.adoc#v42-7-0[Próximo Capítulo &#62;]