include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-15-1]]

^<<v42-15-1,1>>^ Ora, chegavam-se a ele todos os publicanos e pecadores para o ouvir.

[[v42-15-2]]

^<<v42-15-2,2>>^ E os fariseus e os escribas murmuravam, dizendo: Este recebe pecadores, e come com eles.

[[v42-15-3]]

^<<v42-15-3,3>>^ Então ele lhes propôs esta parábola:

[[v42-15-4]]

^<<v42-15-4,4>>^ Qual de vós é o homem que, possuindo cem ovelhas, e perdendo uma delas, não deixa as noventa e nove no deserto, e não vai após a perdida até que a encontre?

[[v42-15-5]]

^<<v42-15-5,5>>^ E achando-a, põe-na sobre os ombros, cheio de júbilo;

[[v42-15-6]]

^<<v42-15-6,6>>^ e chegando a casa, reúne os amigos e vizinhos e lhes diz: Alegrai-vos comigo, porque achei a minha ovelha que se havia perdido.

[[v42-15-7]]

^<<v42-15-7,7>>^ Digo-vos que assim haverá maior alegria no céu por um pecador que se arrepende, do que por noventa e nove justos que não necessitam de arrependimento.

[[v42-15-8]]

^<<v42-15-8,8>>^ Ou qual é a mulher que, tendo dez dracmas e perdendo uma dracma, não acende a candeia, e não varre a casa, buscando com diligência até encontrá-la?

[[v42-15-9]]

^<<v42-15-9,9>>^ E achando-a, reúne as amigas e vizinhas, dizendo: Alegrai-vos comigo, porque achei a dracma que eu havia perdido.

[[v42-15-10]]

^<<v42-15-10,10>>^ Assim, digo-vos, há alegria na presença dos anjos de Deus por um só pecador que se arrepende.

[[v42-15-11]]

^<<v42-15-11,11>>^ Disse-lhe mais: Certo homem tinha dois filhos.

[[v42-15-12]]

^<<v42-15-12,12>>^ O mais moço deles disse ao pai: Pai, dá-me a parte dos bens que me toca. Repartiu-lhes, pois, os seus haveres.

[[v42-15-13]]

^<<v42-15-13,13>>^ Poucos dias depois, o filho mais moço ajuntando tudo, partiu para um país distante, e ali desperdiçou os seus bens, vivendo dissolutamente.

[[v42-15-14]]

^<<v42-15-14,14>>^ E, havendo ele dissipado tudo, houve naquela terra uma grande fome, e começou a passar necessidades.

[[v42-15-15]]

^<<v42-15-15,15>>^ Então foi encontrar-se a um dos cidadãos daquele país, o qual o mandou para os seus campos a apascentar porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ E desejava encher o estômago com as alfarrobas que os porcos comiam; e ninguém lhe dava nada.

[[v42-15-17]]

^<<v42-15-17,17>>^ Caindo, porém, em si, disse: Quantos empregados de meu pai têm abundância de pão, e eu aqui pereço de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Levantar-me-ei, irei ter com meu pai e dir-lhe-ei: Pai, pequei contra o céu e diante de ti;

[[v42-15-19]]

^<<v42-15-19,19>>^ já não sou digno de ser chamado teu filho; trata-me como um dos teus empregados.

[[v42-15-20]]

^<<v42-15-20,20>>^ Levantou-se, pois, e foi para seu pai. Estando ele ainda longe, seu pai o viu, encheu-se de compaixão e, correndo, lançou-se-lhe ao pescoço e o beijou.

[[v42-15-21]]

^<<v42-15-21,21>>^ Disse-lhe o filho: Pai, pequei conta o céu e diante de ti; já não sou digno de ser chamado teu filho.

[[v42-15-22]]

^<<v42-15-22,22>>^ Mas o pai disse aos seus servos: Trazei depressa a melhor roupa, e vesti-lha, e ponde-lhe um anel no dedo e alparcas nos pés;

[[v42-15-23]]

^<<v42-15-23,23>>^ trazei também o bezerro, cevado e matai-o; comamos, e regozijemo-nos,

[[v42-15-24]]

^<<v42-15-24,24>>^ porque este meu filho estava morto, e reviveu; tinha-se perdido, e foi achado. E começaram a regozijar-se.

[[v42-15-25]]

^<<v42-15-25,25>>^ Ora, o seu filho mais velho estava no campo; e quando voltava, ao aproximar-se de casa, ouviu a música e as danças;

[[v42-15-26]]

^<<v42-15-26,26>>^ e chegando um dos servos, perguntou-lhe que era aquilo.

[[v42-15-27]]

^<<v42-15-27,27>>^ Respondeu-lhe este: Chegou teu irmão; e teu pai matou o bezerro cevado, porque o recebeu são e salvo.

[[v42-15-28]]

^<<v42-15-28,28>>^ Mas ele se indignou e não queria entrar. Saiu então o pai e instava com ele.

[[v42-15-29]]

^<<v42-15-29,29>>^ Ele, porém, respondeu ao pai: Eis que há tantos anos te sirvo, e nunca transgredi um mandamento teu; contudo nunca me deste um cabrito para eu me regozijar com meus amigos;

[[v42-15-30]]

^<<v42-15-30,30>>^ vindo, porém, este teu filho, que desperdiçou os teus bens com as meretrizes, mataste-lhe o bezerro cevado.

[[v42-15-31]]

^<<v42-15-31,31>>^ Replicou-lhe o pai: Filho, tu sempre estás comigo, e tudo o que é meu é teu;

[[v42-15-32]]

^<<v42-15-32,32>>^ era justo, porém, regozijarmo-nos e alegramo-nos, porque este teu irmão estava morto, e reviveu; tinha-se perdido, e foi achado.

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]