include::./index.adoc[]

[[v42-4-0]]
=== Lucas, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-4-1]]

^<<v42-4-1,1>>^ Jesus, pois, cheio do Espírito Santo, voltou do Jordão; e era levado pelo Espírito no deserto,

[[v42-4-2]]

^<<v42-4-2,2>>^ durante quarenta dias, sendo tentado pelo Diabo. E naqueles dias não comeu coisa alguma; e terminados eles, teve fome.

[[v42-4-3]]

^<<v42-4-3,3>>^ Disse-lhe então o Diabo: Se tu és Filho de Deus, manda a esta pedra que se torne em pão.

[[v42-4-4]]

^<<v42-4-4,4>>^ Jesus, porém, lhe respondeu: Está escrito: Nem só de pão viverá o homem.

[[v42-4-5]]

^<<v42-4-5,5>>^ Então o Diabo, levando-o a um lugar elevado, mostrou-lhe num relance todos os reinos do mundo.

[[v42-4-6]]

^<<v42-4-6,6>>^ E disse-lhe: Dar-te-ei toda a autoridade e glória destes reinos, porque me foi entregue, e a dou a quem eu quiser;

[[v42-4-7]]

^<<v42-4-7,7>>^ se tu, me adorares, será toda tua.

[[v42-4-8]]

^<<v42-4-8,8>>^ Respondeu-lhe Jesus: Está escrito: Ao Senhor teu Deus adorarás, e só a ele servirás.

[[v42-4-9]]

^<<v42-4-9,9>>^ Então o levou a Jerusalém e o colocou sobre o pináculo do templo e lhe disse: Se tu és Filho de Deus, lança-te daqui abaixo;

[[v42-4-10]]

^<<v42-4-10,10>>^ porque está escrito: Aos seus anjos ordenará a teu respeito, que te guardem;

[[v42-4-11]]

^<<v42-4-11,11>>^ e: eles te susterão nas mãos, para que nunca tropeces em alguma pedra.

[[v42-4-12]]

^<<v42-4-12,12>>^ Respondeu-lhe Jesus: Dito está: Não tentarás o Senhor teu Deus.

[[v42-4-13]]

^<<v42-4-13,13>>^ Assim, tendo o Diabo acabado toda sorte de tentação, retirou-se dele até ocasião oportuna.

[[v42-4-14]]

^<<v42-4-14,14>>^ Então voltou Jesus para a Galiléia no poder do Espírito; e a sua fama correu por toda a circunvizinhança.

[[v42-4-15]]

^<<v42-4-15,15>>^ Ensinava nas sinagogas deles, e por todos era louvado.

[[v42-4-16]]

^<<v42-4-16,16>>^ Chegando a Nazaré, onde fora criado; entrou na sinagoga no dia de sábado, segundo o seu costume, e levantou-se para ler.

[[v42-4-17]]

^<<v42-4-17,17>>^ Foi-lhe entregue o livro do profeta Isaías; e abrindo-o, achou o lugar em que estava escrito:

[[v42-4-18]]

^<<v42-4-18,18>>^ O Espírito do Senhor está sobre mim, porquanto me ungiu para anunciar boas novas aos pobres; enviou-me para proclamar libertação aos cativos, e restauração da vista aos cegos, para pôr em liberdade os oprimidos,

[[v42-4-19]]

^<<v42-4-19,19>>^ e para proclamar o ano aceitável do Senhor.

[[v42-4-20]]

^<<v42-4-20,20>>^ E fechando o livro, devolveu-o ao assistente e sentou-se; e os olhos de todos na sinagoga estavam fitos nele.

[[v42-4-21]]

^<<v42-4-21,21>>^ Então começou a dizer-lhes: Hoje se cumpriu esta escritura aos vossos ouvidos.

[[v42-4-22]]

^<<v42-4-22,22>>^ E todos lhe davam testemunho, e se admiravam das palavras de graça que saíam da sua boca; e diziam: Este não é filho de José?

[[v42-4-23]]

^<<v42-4-23,23>>^ Disse-lhes Jesus: Sem dúvida me direis este provérbio: Médico, cura-te a ti mesmo; Tudo o que ouvimos teres feito em Cafarnaum, faze-o também aqui na tua terra.

[[v42-4-24]]

^<<v42-4-24,24>>^ E prosseguiu: Em verdade vos digo que nenhum profeta é aceito na sua terra.

[[v42-4-25]]

^<<v42-4-25,25>>^ Em verdade vos digo que muitas viúvas havia em Israel nos dias de Elias, quando céu se fechou por três anos e seis meses, de sorte que houve grande fome por toda a terra;

[[v42-4-26]]

^<<v42-4-26,26>>^ e a nenhuma delas foi enviado Elias, senão a uma viúva em Serepta de Sidom.

[[v42-4-27]]

^<<v42-4-27,27>>^ Também muitos leprosos havia em Israel no tempo do profeta Elizeu, mas nenhum deles foi purificado senão Naamã, o sírio.

[[v42-4-28]]

^<<v42-4-28,28>>^ Todos os que estavam na sinagoga, ao ouvirem estas coisas, ficaram cheios de ira.

[[v42-4-29]]

^<<v42-4-29,29>>^ e, levantando-se, expulsaram-no da cidade e o levaram até o despenhadeiro do monte em que a sua cidade estava edificada, para dali o precipitarem.

[[v42-4-30]]

^<<v42-4-30,30>>^ Ele, porém, passando pelo meio deles, seguiu o seu caminho.

[[v42-4-31]]

^<<v42-4-31,31>>^ Então desceu a Cafarnaum, cidade da Galiléia, e os ensinava no sábado.

[[v42-4-32]]

^<<v42-4-32,32>>^ e maravilharam-se da sua doutrina, porque a sua palavra era com autoridade.

[[v42-4-33]]

^<<v42-4-33,33>>^ Havia na sinagoga um homem que tinha o espírito de um demônio imundo; e gritou em alta voz:

[[v42-4-34]]

^<<v42-4-34,34>>^ Ah! que temos nós contigo, Jesus, nazareno? vieste destruir-nos? Bem sei quem é: o Santo de Deus.

[[v42-4-35]]

^<<v42-4-35,35>>^ Mas Jesus o repreendeu, dizendo: Cala-te, e sai dele. E o demônio, tendo-o lançado por terra no meio do povo, saiu dele sem lhe fazer mal algum.

[[v42-4-36]]

^<<v42-4-36,36>>^ E veio espanto sobre todos, e falavam entre si, perguntando uns aos outros: Que palavra é esta, pois com autoridade e poder ordena aos espíritos imundos, e eles saem?

[[v42-4-37]]

^<<v42-4-37,37>>^ E se divulgava a sua fama por todos os lugares da circunvizinhança.

[[v42-4-38]]

^<<v42-4-38,38>>^ Ora, levantando-se Jesus, saiu da sinagoga e entrou em casa de Simão; e estando a sogra de Simão enferma com muita febre, rogaram-lhe por ela.

[[v42-4-39]]

^<<v42-4-39,39>>^ E ele, inclinando-se para ela, repreendeu a febre, e esta a deixou. Imediatamente ela se levantou e os servia.

[[v42-4-40]]

^<<v42-4-40,40>>^ Ao pôr do sol, todos os que tinham enfermos de várias doenças lhos traziam; e ele punha as mãos sobre cada um deles e os curava.

[[v42-4-41]]

^<<v42-4-41,41>>^ Também de muitos saíam demônios, gritando e dizendo: Tu és o Filho de Deus. Ele, porém, os repreendia, e não os deixava falar; pois sabiam que ele era o Cristo.

[[v42-4-42]]

^<<v42-4-42,42>>^ Ao romper do dia saiu, e foi a um lugar deserto; e as multidões procuravam-no e, vindo a ele, queriam detê-lo, para que não se ausentasse delas.

[[v42-4-43]]

^<<v42-4-43,43>>^ Ele, porém, lhes disse: É necessário que também às outras cidades eu anuncie o evangelho do reino de Deus; porque para isso é que fui enviado.

[[v42-4-44]]

^<<v42-4-44,44>>^ E pregava nas sinagogas da Judéia.

'''

xref:042-lucas/042-lucas-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v42-4-0,Topo>> | xref:042-lucas/042-lucas-005.adoc#v42-5-0[Próximo Capítulo &#62;]