include::./index.adoc[]

[[v42-18-0]]
=== Lucas, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-18-1]]

^<<v42-18-1,1>>^ Contou-lhes também uma parábola sobre o dever de orar sempre, e nunca desfalecer.

[[v42-18-2]]

^<<v42-18-2,2>>^ dizendo: Havia em certa cidade um juiz que não temia a Deus, nem respeitava os homens.

[[v42-18-3]]

^<<v42-18-3,3>>^ Havia também naquela mesma cidade uma viúva que ia ter com ele, dizendo: Faze-me justiça contra o meu adversário.

[[v42-18-4]]

^<<v42-18-4,4>>^ E por algum tempo não quis atendê-la; mas depois disse consigo: Ainda que não temo a Deus, nem respeito os homens,

[[v42-18-5]]

^<<v42-18-5,5>>^ todavia, como esta viúva me incomoda, hei de fazer-lhe justiça, para que ela não continue a vir molestar-me.

[[v42-18-6]]

^<<v42-18-6,6>>^ Prosseguiu o Senhor: Ouvi o que diz esse juiz injusto.

[[v42-18-7]]

^<<v42-18-7,7>>^ E não fará Deus justiça aos seus escolhidos, que dia e noite clamam a ele, já que é longânimo para com eles?

[[v42-18-8]]

^<<v42-18-8,8>>^ Digo-vos que depressa lhes fará justiça. Contudo quando vier o Filho do homem, porventura achará fé na terra?

[[v42-18-9]]

^<<v42-18-9,9>>^ Propôs também esta parábola a uns que confiavam em si mesmos, crendo que eram justos, e desprezavam os outros:

[[v42-18-10]]

^<<v42-18-10,10>>^ Dois homens subiram ao templo para orar; um fariseu, e o outro publicano.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu, de pé, assim orava consigo mesmo: ó Deus, graças te dou que não sou como os demais homens, roubadores, injustos, adúlteros, nem ainda com este publicano.

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes na semana, e dou o dízimo de tudo quanto ganho.

[[v42-18-13]]

^<<v42-18-13,13>>^ Mas o publicano, estando em pé de longe, nem ainda queria levantar os olhos ao céu, mas batia no peito, dizendo: ó Deus, sê propício a mim, o pecador!

[[v42-18-14]]

^<<v42-18-14,14>>^ Digo-vos que este desceu justificado para sua casa, e não aquele; porque todo o que a si mesmo se exaltar será humilhado; mas o que a si mesmo se humilhar será exaltado.

[[v42-18-15]]

^<<v42-18-15,15>>^ Traziam-lhe também as crianças, para que as tocasse; mas os discípulos, vendo isso, os repreendiam.

[[v42-18-16]]

^<<v42-18-16,16>>^ Jesus, porém, chamando-as para si, disse: Deixai vir a mim as crianças, e não as impeçais, porque de tais é o reino de Deus.

[[v42-18-17]]

^<<v42-18-17,17>>^ Em verdade vos digo que, qualquer que não receber o reino de Deus como criança, de modo algum entrará nele.

[[v42-18-18]]

^<<v42-18-18,18>>^ E perguntou-lhe um dos principais: Bom Mestre, que hei de fazer para herdar a vida eterna?

[[v42-18-19]]

^<<v42-18-19,19>>^ Respondeu-lhe Jesus: Por que me chamas bom? Ninguém é bom, senão um, que é Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Sabes os mandamentos: Não adulterarás; não matarás; não furtarás; não dirás falso testemunho; honra a teu pai e a tua mãe.

[[v42-18-21]]

^<<v42-18-21,21>>^ Replicou o homem: Tudo isso tenho guardado desde a minha juventude.

[[v42-18-22]]

^<<v42-18-22,22>>^ Quando Jesus ouviu isso, disse-lhe: Ainda te falta uma coisa; vende tudo quanto tens e reparte-o pelos pobres, e terás um tesouro no céu; e vem, segue-me.

[[v42-18-23]]

^<<v42-18-23,23>>^ Mas, ouvindo ele isso, encheu-se de tristeza; porque era muito rico.

[[v42-18-24]]

^<<v42-18-24,24>>^ E Jesus, vendo-o assim, disse: Quão dificilmente entrarão no reino de Deus os que têm riquezas!

[[v42-18-25]]

^<<v42-18-25,25>>^ Pois é mais fácil um camelo passar pelo fundo duma agulha, do que entrar um rico no reino de Deus.

[[v42-18-26]]

^<<v42-18-26,26>>^ Então os que ouviram isso disseram: Quem pode, então, ser salvo?

[[v42-18-27]]

^<<v42-18-27,27>>^ Respondeu-lhes: As coisas que são impossíveis aos homens são possíveis a Deus.

[[v42-18-28]]

^<<v42-18-28,28>>^ Disse-lhe Pedro: Eis que nós deixamos tudo, e te seguimos.

[[v42-18-29]]

^<<v42-18-29,29>>^ Respondeu-lhes Jesus: Em verdade vos digo que ninguém há que tenha deixado casa, ou mulher, ou irmãos, ou pais, ou filhos, por amor do reino de Deus,

[[v42-18-30]]

^<<v42-18-30,30>>^ que não haja de receber no presente muito mais, e no mundo vindouro a vida eterna.

[[v42-18-31]]

^<<v42-18-31,31>>^ Tomando Jesus consigo os doze, disse-lhes: Eis que subimos a Jerusalém e se cumprirá no filho do homem tudo o que pelos profetas foi escrito;

[[v42-18-32]]

^<<v42-18-32,32>>^ pois será entregue aos gentios, e escarnecido, injuriado e cuspido;

[[v42-18-33]]

^<<v42-18-33,33>>^ e depois de o açoitarem, o matarão; e ao terceiro dia ressurgirá.

[[v42-18-34]]

^<<v42-18-34,34>>^ Mas eles não entenderam nada disso; essas palavras lhes eram obscuras, e não percebiam o que lhes dizia.

[[v42-18-35]]

^<<v42-18-35,35>>^ Ora, quando ele ia chegando a Jericó, estava um cego sentado junto do caminho, mendigando.

[[v42-18-36]]

^<<v42-18-36,36>>^ Este, pois, ouvindo passar a multidão, perguntou que era aquilo.

[[v42-18-37]]

^<<v42-18-37,37>>^ Disseram-lhe que Jesus, o nazareno, ia passando.

[[v42-18-38]]

^<<v42-18-38,38>>^ Então ele se pôs a clamar, dizendo: Jesus, Filho de Davi, tem compaixão de mim!

[[v42-18-39]]

^<<v42-18-39,39>>^ E os que iam à frente repreendiam-no, para que se calasse; ele, porém, clamava ainda mais: Filho de Davi, tem compaixão de mim!

[[v42-18-40]]

^<<v42-18-40,40>>^ Parou, pois, Jesus, e mandou que lho trouxessem. Tendo ele chegado, perguntou-lhe:

[[v42-18-41]]

^<<v42-18-41,41>>^ Que queres que te faça? Respondeu ele: Senhor, que eu veja.

[[v42-18-42]]

^<<v42-18-42,42>>^ Disse-lhe Jesus: Vê; a tua fé te salvou.

[[v42-18-43]]

^<<v42-18-43,43>>^ Imediatamente recuperou a vista, e o foi seguindo, gloficando a Deus. E todo o povo, vendo isso, dava louvores a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]