include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-1-1]]

^<<v42-1-1,1>>^ Visto que muitos têm empreendido fazer uma narração coordenada dos fatos que entre nós se realizaram,

[[v42-1-2]]

^<<v42-1-2,2>>^ segundo no-los transmitiram os que desde o princípio foram testemunhas oculares e ministros da palavra,

[[v42-1-3]]

^<<v42-1-3,3>>^ também a mim, depois de haver investido tudo cuidadosamente desde o começo, pareceu-me bem, ó excelentíssimo Teófilo, escrever-te uma narração em ordem.

[[v42-1-4]]

^<<v42-1-4,4>>^ para que conheças plenamente a verdade das coisas em que foste instruído.

[[v42-1-5]]

^<<v42-1-5,5>>^ Houve nos dias do Rei Herodes, rei da Judéia, um sacerdote chamado Zacarias, da turma de Abias; e sua mulher era descendente de Arão, e chamava-se Isabel.

[[v42-1-6]]

^<<v42-1-6,6>>^ Ambos eram justos diante de Deus, andando irrepreensíveis em todos os mandamentos e preceitos do Senhor.

[[v42-1-7]]

^<<v42-1-7,7>>^ Mas não tinham filhos, porque Isabel era estéril, e ambos avançados em idade.

[[v42-1-8]]

^<<v42-1-8,8>>^ Ora, estando ele a exercer as funções sacerdotais perante Deus, na ordem da sua turma,

[[v42-1-9]]

^<<v42-1-9,9>>^ segundo o costume do sacerdócio, coube-lhe por sorte entrar no santuário do Senhor, para oferecer o incenso;

[[v42-1-10]]

^<<v42-1-10,10>>^ e toda a multidão do povo orava da parte de fora, à hora do incenso.

[[v42-1-11]]

^<<v42-1-11,11>>^ Apareceu-lhe, então, um anjo do Senhor, em pé à direita do altar do incenso.

[[v42-1-12]]

^<<v42-1-12,12>>^ E Zacarias, vendo-o, ficou turbado, e o temor o assaltou.

[[v42-1-13]]

^<<v42-1-13,13>>^ Mas o anjo lhe disse: Não temais, Zacarias; porque a tua oração foi ouvida, e Isabel, tua mulher, te dará à luz um filho, e lhe porás o nome de João;

[[v42-1-14]]

^<<v42-1-14,14>>^ e terás alegria e regozijo, e muitos se alegrarão com o seu nascimento;

[[v42-1-15]]

^<<v42-1-15,15>>^ porque ele será grande diante do Senhor; não beberá vinho, nem bebida forte; e será cheio do Espírito Santo já desde o ventre de sua mãe;

[[v42-1-16]]

^<<v42-1-16,16>>^ converterá muitos dos filhos de Israel ao Senhor seu Deus;

[[v42-1-17]]

^<<v42-1-17,17>>^ irá adiante dele no espírito e poder de Elias, para converter os corações dos pais aos filhos, e os rebeldes à prudência dos justos, a fim de preparar para o Senhor um povo apercebido.

[[v42-1-18]]

^<<v42-1-18,18>>^ Disse então Zacarias ao anjo: Como terei certeza disso? pois eu sou velho, e minha mulher também está avançada em idade.

[[v42-1-19]]

^<<v42-1-19,19>>^ Ao que lhe respondeu o anjo: Eu sou Gabriel, que assisto diante de Deus, e fui enviado para te falar e te dar estas boas novas;

[[v42-1-20]]

^<<v42-1-20,20>>^ e eis que ficarás mudo, e não poderás falar até o dia em que estas coisas aconteçam; porquanto não creste nas minhas palavras, que a seu tempo hão de cumprir-se.

[[v42-1-21]]

^<<v42-1-21,21>>^ O povo estava esperando Zacarias, e se admirava da sua demora no santuário.

[[v42-1-22]]

^<<v42-1-22,22>>^ Quando saiu, porém, não lhes podia falar, e perceberam que tivera uma visão no santuário. E falava-lhes por acenos, mas permanecia mudo.

[[v42-1-23]]

^<<v42-1-23,23>>^ E, terminados os dias do seu ministério, voltou para casa.

[[v42-1-24]]

^<<v42-1-24,24>>^ Depois desses dias Isabel, sua mulher, concebeu, e por cinco meses se ocultou, dizendo:

[[v42-1-25]]

^<<v42-1-25,25>>^ Assim me fez o Senhor nos dias em que atentou para mim, a fim de acabar com o meu opróbrio diante dos homens.

[[v42-1-26]]

^<<v42-1-26,26>>^ Ora, no sexto mês, foi o anjo Gabriel enviado por Deus a uma cidade da Galiléia, chamada Nazaré,

[[v42-1-27]]

^<<v42-1-27,27>>^ a uma virgem desposada com um varão cujo nome era José, da casa de Davi; e o nome da virgem era Maria.

[[v42-1-28]]

^<<v42-1-28,28>>^ E, entrando o anjo onde ela estava disse: Salve, agraciada; o Senhor é contigo.

[[v42-1-29]]

^<<v42-1-29,29>>^ Ela, porém, ao ouvir estas palavras, turbou-se muito e pôs-se a pensar que saudação seria essa.

[[v42-1-30]]

^<<v42-1-30,30>>^ Disse-lhe então o anjo: Não temas, Maria; pois achaste graça diante de Deus.

[[v42-1-31]]

^<<v42-1-31,31>>^ Eis que conceberás e darás à luz um filho, ao qual porás o nome de Jesus.

[[v42-1-32]]

^<<v42-1-32,32>>^ Este será grande e será chamado filho do Altíssimo; o Senhor Deus lhe dará o trono de Davi seu pai;

[[v42-1-33]]

^<<v42-1-33,33>>^ e reinará eternamente sobre a casa de Jacó, e o seu reino não terá fim.

[[v42-1-34]]

^<<v42-1-34,34>>^ Então Maria perguntou ao anjo: Como se fará isso, uma vez que não conheço varão?

[[v42-1-35]]

^<<v42-1-35,35>>^ Respondeu-lhe o anjo: Virá sobre ti o Espírito Santo, e o poder do Altíssimo te cobrirá com a sua sombra; por isso o que há de nascer será chamado santo, Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ Eis que também Isabel, tua parenta concebeu um filho em sua velhice; e é este o sexto mês para aquela que era chamada estéril;

[[v42-1-37]]

^<<v42-1-37,37>>^ porque para Deus nada será impossível.

[[v42-1-38]]

^<<v42-1-38,38>>^ Disse então Maria. Eis aqui a serva do Senhor; cumpra-se em mim segundo a tua palavra. E o anjo ausentou-se dela.

[[v42-1-39]]

^<<v42-1-39,39>>^ Naqueles dias levantou-se Maria, foi apressadamente à região montanhosa, a uma cidade de Judá,

[[v42-1-40]]

^<<v42-1-40,40>>^ entrou em casa de Zacarias e saudou a Isabel.

[[v42-1-41]]

^<<v42-1-41,41>>^ Ao ouvir Isabel a saudação de Maria, saltou a criancinha no seu ventre, e Isabel ficou cheia do Espírito Santo,

[[v42-1-42]]

^<<v42-1-42,42>>^ e exclamou em alta voz: Bendita és tu entre as mulheres, e bendito é o fruto do teu ventre!

[[v42-1-43]]

^<<v42-1-43,43>>^ E donde me provém isto, que venha visitar-me a mãe do meu Senhor?

[[v42-1-44]]

^<<v42-1-44,44>>^ Pois logo que me soou aos ouvidos a voz da tua saudação, a criancinha saltou de alegria dentro de mim.

[[v42-1-45]]

^<<v42-1-45,45>>^ Bem-aventurada aquela que creu que se hão de cumprir as coisas que da parte do Senhor lhe foram ditas.

[[v42-1-46]]

^<<v42-1-46,46>>^ Disse então Maria: A minha alma engrandece ao Senhor,

[[v42-1-47]]

^<<v42-1-47,47>>^ e o meu espírito exulta em Deus meu Salvador;

[[v42-1-48]]

^<<v42-1-48,48>>^ porque atentou na condição humilde de sua serva. Desde agora, pois, todas as gerações me chamarão bem-aventurada,

[[v42-1-49]]

^<<v42-1-49,49>>^ porque o Poderoso me fez grandes coisas; e santo é o seu nome.

[[v42-1-50]]

^<<v42-1-50,50>>^ E a sua misericórdia vai de geração em geração sobre os que o temem.

[[v42-1-51]]

^<<v42-1-51,51>>^ Com o seu braço manifestou poder; dissipou os que eram soberbos nos pensamentos de seus corações;

[[v42-1-52]]

^<<v42-1-52,52>>^ depôs dos tronos os poderosos, e elevou os humildes.

[[v42-1-53]]

^<<v42-1-53,53>>^ Aos famintos encheu de bens, e vazios despediu os ricos.

[[v42-1-54]]

^<<v42-1-54,54>>^ Auxiliou a Isabel, seu servo, lembrando-se de misericórdia

[[v42-1-55]]

^<<v42-1-55,55>>^ &#123;como falou a nossos pais&#125; para com Abraão e a sua descendência para sempre.

[[v42-1-56]]

^<<v42-1-56,56>>^ E Maria ficou com ela cerca de três meses; e depois voltou para sua casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ Ora, completou-se para Isabel o tempo de dar à luz, e teve um filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ Ouviram seus vizinhos e parentes que o Senhor lhe multiplicara a sua misericórdia, e se alegravam com ela.

[[v42-1-59]]

^<<v42-1-59,59>>^ Sucedeu, pois, no oitavo dia, que vieram circuncidar o menino; e queriam dar-lhe o nome de seu pai, Zacarias.

[[v42-1-60]]

^<<v42-1-60,60>>^ Respondeu, porém, sua mãe: De modo nenhum, mas será chamado João.

[[v42-1-61]]

^<<v42-1-61,61>>^ Ao que lhe disseram: Ninguém há na tua parentela que se chame por este nome.

[[v42-1-62]]

^<<v42-1-62,62>>^ E perguntaram por acenos ao pai como queria que se chamasse.

[[v42-1-63]]

^<<v42-1-63,63>>^ E pedindo ele uma tabuinha, escreveu: Seu nome é João. E todos se admiraram.

[[v42-1-64]]

^<<v42-1-64,64>>^ Imediatamente a boca se lhe abriu, e a língua se lhe soltou; louvando a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ Então veio temor sobre todos os seus vizinhos; e em toda a região montanhosa da Judéia foram divulgadas todas estas coisas.

[[v42-1-66]]

^<<v42-1-66,66>>^ E todos os que delas souberam as guardavam no coração, dizendo: Que virá a ser, então, este menino? Pois a mão do Senhor estava com ele.

[[v42-1-67]]

^<<v42-1-67,67>>^ Zacarias, seu pai, ficou cheio do Espírito Santo e profetizou, dizendo:

[[v42-1-68]]

^<<v42-1-68,68>>^ Bendito, seja o Senhor Deus de Israel, porque visitou e remiu o seu povo,

[[v42-1-69]]

^<<v42-1-69,69>>^ e para nós fez surgir uma salvação poderosa na casa de Davi, seu servo;

[[v42-1-70]]

^<<v42-1-70,70>>^ assim como desde os tempos antigos tem anunciado pela boca dos seus santos profetas;

[[v42-1-71]]

^<<v42-1-71,71>>^ para nos livrar dos nossos inimigos e da mão de todos os que nos odeiam;

[[v42-1-72]]

^<<v42-1-72,72>>^ para usar de misericórdia com nossos pais, e lembrar-se do seu santo pacto

[[v42-1-73]]

^<<v42-1-73,73>>^ e do juramento que fez a Abrão, nosso pai,

[[v42-1-74]]

^<<v42-1-74,74>>^ de conceder-nos que, libertados da mão de nossos inimigos, o servíssemos sem temor,

[[v42-1-75]]

^<<v42-1-75,75>>^ em santidade e justiça perante ele, todos os dias da nossa vida.

[[v42-1-76]]

^<<v42-1-76,76>>^ E tu, menino, serás chamado profeta do Altíssimo, porque irás ante a face do Senhor, a preparar os seus caminhos;

[[v42-1-77]]

^<<v42-1-77,77>>^ para dar ao seu povo conhecimento da salvação, na remissão dos seus pecados,

[[v42-1-78]]

^<<v42-1-78,78>>^ graças à entranhável misericórdia do nosso Deus, pela qual nos há de visitar a aurora lá do alto,

[[v42-1-79]]

^<<v42-1-79,79>>^ para alumiar aos que jazem nas trevas e na sombra da morte, a fim de dirigir os nossos pés no caminho da paz.

[[v42-1-80]]

^<<v42-1-80,80>>^ Ora, o menino crescia, e se robustecia em espírito; e habitava nos desertos até o dia da sua manifestação a Israel.

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]