include::./index.adoc[]

[[v42-11-0]]
=== Lucas, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-11-1]]

^<<v42-11-1,1>>^ Estava Jesus em certo lugar orando e, quando acabou, disse-lhe um dos seus discípulos: Senhor, ensina-nos a orar, como também João ensinou aos seus discípulos.

[[v42-11-2]]

^<<v42-11-2,2>>^ Ao que ele lhes disse: Quando orardes, dizei: Pai, santificado seja o teu nome; venha o teu reino;

[[v42-11-3]]

^<<v42-11-3,3>>^ dá-nos cada dia o nosso pão cotidiano;

[[v42-11-4]]

^<<v42-11-4,4>>^ e perdoa-nos os nossos pecados, pois também nós perdoamos a todo aquele que nos deve; e não nos deixes entrar em tentação, &#123;mas livra-nos do mal.&#125;

[[v42-11-5]]

^<<v42-11-5,5>>^ Disse-lhes também: Se um de vós tiver um amigo, e se for procurá-lo à meia-noite e lhe disser: Amigo, empresta-me três pães,

[[v42-11-6]]

^<<v42-11-6,6>>^ pois que um amigo meu, estando em viagem, chegou a minha casa, e não tenho o que lhe oferecer;

[[v42-11-7]]

^<<v42-11-7,7>>^ e se ele, de dentro, responder: Não me incomodes; já está a porta fechada, e os meus filhos estão comigo na cama; não posso levantar-me para te atender;

[[v42-11-8]]

^<<v42-11-8,8>>^ digo-vos que, ainda que se levante para lhos dar por ser seu amigo, todavia, por causa da sua importunação, se levantará e lhe dará quantos pães ele precisar.

[[v42-11-9]]

^<<v42-11-9,9>>^ Pelo que eu vos digo: Pedi, e dar-se-vos-á; buscai e achareis; batei, e abrir-se-vos-á;

[[v42-11-10]]

^<<v42-11-10,10>>^ pois todo o que pede, recebe; e quem busca acha; e ao que bate, abrir-se-lhe-á.

[[v42-11-11]]

^<<v42-11-11,11>>^ E qual o pai dentre vós que, se o filho lhe pedir pão, lhe dará uma pedra? Ou, se lhe pedir peixe, lhe dará por peixe uma serpente?

[[v42-11-12]]

^<<v42-11-12,12>>^ Ou, se pedir um ovo, lhe dará um escorpião?

[[v42-11-13]]

^<<v42-11-13,13>>^ Se vós, pois, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?

[[v42-11-14]]

^<<v42-11-14,14>>^ Estava Jesus expulsando um demônio, que era mudo; e aconteceu que, saindo o demônio, o mudo falou; e as multidões se admiraram.

[[v42-11-15]]

^<<v42-11-15,15>>^ Mas alguns deles disseram: É por Belzebu, o príncipe dos demônios, que ele expulsa os demônios.

[[v42-11-16]]

^<<v42-11-16,16>>^ E outros, experimentando-o, lhe pediam um sinal do céu.

[[v42-11-17]]

^<<v42-11-17,17>>^ Ele, porém, conhecendo-lhes os pensamentos, disse-lhes: Todo reino dividido contra si mesmo será assolado, e casa sobre casa cairá.

[[v42-11-18]]

^<<v42-11-18,18>>^ Ora, pois, se Satanás está dividido contra si mesmo, como subsistirá o seu reino? Pois dizeis que eu expulso dos demônios por Belzebu.

[[v42-11-19]]

^<<v42-11-19,19>>^ E, se eu expulso os demônios por Belzebu, por quem os expulsam os vossos filhos? Por isso eles mesmos serão os vossos juizes.

[[v42-11-20]]

^<<v42-11-20,20>>^ Mas, se é pelo dedo de Deus que eu expulso os demônios, logo é chegado a vós o reino de Deus.

[[v42-11-21]]

^<<v42-11-21,21>>^ Quando o valente guarda, armado, a sua casa, em segurança estão os seus bens;

[[v42-11-22]]

^<<v42-11-22,22>>^ mas, sobrevindo outro mais valente do que ele, e vencendo-o, tira-lhe toda a armadura em que confiava, e reparte os seus despojos.

[[v42-11-23]]

^<<v42-11-23,23>>^ Quem não é comigo, é contra mim; e quem comigo não ajunta, espalha.

[[v42-11-24]]

^<<v42-11-24,24>>^ Ora, havendo o espírito imundo saindo do homem, anda por lugares áridos, buscando repouso; e não o encontrando, diz: Voltarei para minha casa, donde saí.

[[v42-11-25]]

^<<v42-11-25,25>>^ E chegando, acha-a varrida e adornada.

[[v42-11-26]]

^<<v42-11-26,26>>^ Então vai, e leva consigo outros sete espíritos piores do que ele e, entrando, habitam ali; e o último estado desse homem vem a ser pior do que o primeiro.

[[v42-11-27]]

^<<v42-11-27,27>>^ Ora, enquanto ele dizia estas coisas, certa mulher dentre a multidão levantou a voz e lhe disse: Bem-aventurado o ventre que te trouxe e os peitos em que te amamentaste.

[[v42-11-28]]

^<<v42-11-28,28>>^ Mas ele respondeu: Antes bem-aventurados os que ouvem a palavra de Deus, e a observam.

[[v42-11-29]]

^<<v42-11-29,29>>^ Como afluíssem as multidões, começou ele a dizer: Geração perversa é esta; ela pede um sinal; e nenhum sinal se lhe dará, senão o de Jonas;

[[v42-11-30]]

^<<v42-11-30,30>>^ porquanto, assim como Jonas foi sinal para os ninivitas, também o Filho do homem o será para esta geração.

[[v42-11-31]]

^<<v42-11-31,31>>^ A rainha do sul se levantará no juízo com os homens desta geração, e os condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão; e eis, aqui quem é maior do que Salomão.

[[v42-11-32]]

^<<v42-11-32,32>>^ Os homens de Nínive se levantarão no juízo com esta geração, e a condenarão; porque se arrependeram com a pregação de Jonas; e eis aqui quem é maior do que Jonas.

[[v42-11-33]]

^<<v42-11-33,33>>^ Ninguém, depois de acender uma candeia, a põe em lugar oculto, nem debaixo do alqueire, mas no velador, para que os que entram vejam a luz.

[[v42-11-34]]

^<<v42-11-34,34>>^ A candeia do corpo são os olhos. Quando, pois, os teus olhos forem bons, todo o teu corpo será luminoso; mas, quando forem maus, o teu corpo será tenebroso.

[[v42-11-35]]

^<<v42-11-35,35>>^ Vê, então, que a luz que há em ti não sejam trevas.

[[v42-11-36]]

^<<v42-11-36,36>>^ Se, pois, todo o teu corpo estiver iluminado, sem ter parte alguma em trevas, será inteiramente luminoso, como quando a candeia te alumia com o seu resplendor.

[[v42-11-37]]

^<<v42-11-37,37>>^ Acabando Jesus de falar, um fariseu o convidou para almoçar com ele; e havendo Jesus entrado, reclinou-se à mesa.

[[v42-11-38]]

^<<v42-11-38,38>>^ O fariseu admirou-se, vendo que ele não se lavara antes de almoçar.

[[v42-11-39]]

^<<v42-11-39,39>>^ Ao que o Senhor lhe disse: Ora vós, os fariseus, limpais o exterior do corpo e do prato; mas o vosso interior do copo e do prato; mas o vosso interior está cheio de rapina e maldade.

[[v42-11-40]]

^<<v42-11-40,40>>^ Loucos! quem fez o exterior, não fez também o inferior?

[[v42-11-41]]

^<<v42-11-41,41>>^ Dai, porém, de esmola o que está dentro do copo e do prato, e eis que todas as coisas vos serão limpas.

[[v42-11-42]]

^<<v42-11-42,42>>^ Mas ai de vós, fariseus! porque dais o dízimo da hortelã, e da arruda, e de toda hortaliça, e desprezais a justiça e o amor de Deus. Ora, estas coisas importava fazer, sem deixar aquelas.

[[v42-11-43]]

^<<v42-11-43,43>>^ Ai de vós, fariseus! porque gostais dos primeiros assentos nas sinagogas, e das saudações nas praças.

[[v42-11-44]]

^<<v42-11-44,44>>^ Ai de vós! porque sois como as sepulturas que não aparecem, sobre as quais andam os homens sem o saberem.

[[v42-11-45]]

^<<v42-11-45,45>>^ Disse-lhe, então, um dos doutores da lei: Mestre, quando dizes isso, também nos afrontas a nós.

[[v42-11-46]]

^<<v42-11-46,46>>^ Ele, porém, respondeu: Ai de vós também, doutores da lei! porque carregais os homens com fardos difíceis de suportar, e vós mesmos nem ainda com um dos vossos dedos tocais nesses fardos.

[[v42-11-47]]

^<<v42-11-47,47>>^ Ai de vós! porque edificais os túmulos dos profetas, e vossos pais os mataram.

[[v42-11-48]]

^<<v42-11-48,48>>^ Assim sois testemunhas e aprovais as obras de vossos pais; porquanto eles os mataram, e vós lhes edificais os túmulos.

[[v42-11-49]]

^<<v42-11-49,49>>^ Por isso diz também a sabedoria de Deus: Profetas e apóstolos lhes mandarei; e eles matarão uns, e perseguirão outros;

[[v42-11-50]]

^<<v42-11-50,50>>^ para que a esta geração se peçam contas do sangue de todos os profetas que, desde a fundação do mundo, foi derramado;

[[v42-11-51]]

^<<v42-11-51,51>>^ desde o sangue de Abel, até o sangue de Zacarias, que foi morto entre o altar e o santuário; sim, eu vos digo, a esta geração se pedirão contas.

[[v42-11-52]]

^<<v42-11-52,52>>^ Ai de vós, doutores da lei! porque tirastes a chave da ciência; vós mesmos não entrastes, e impedistes aos que entravam.

[[v42-11-53]]

^<<v42-11-53,53>>^ Ao sair ele dali, começaram os escribas e os fariseus a apertá-lo fortemente, e a interrogá-lo acerca de muitas coisas,

[[v42-11-54]]

^<<v42-11-54,54>>^ armando-lhe ciladas, a fim de o apanharem em alguma coisa que dissesse.

'''

xref:042-lucas/042-lucas-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-lucas/042-lucas-012.adoc#v42-12-0[Próximo Capítulo &#62;]