include::./index.adoc[]

[[v42-14-0]]
=== Lucas, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-14-1]]

^<<v42-14-1,1>>^ Tendo Jesus entrado, num sábado, em casa de um dos chefes dos fariseus para comer pão, eles o estavam observando.

[[v42-14-2]]

^<<v42-14-2,2>>^ Achava-se ali diante dele certo homem hidrópico.

[[v42-14-3]]

^<<v42-14-3,3>>^ E Jesus, tomando a palavra, falou aos doutores da lei e aos fariseus, e perguntou: É lícito curar no sábado, ou não?

[[v42-14-4]]

^<<v42-14-4,4>>^ Eles, porém, ficaram calados. E Jesus, pegando no homem, o curou, e o despediu.

[[v42-14-5]]

^<<v42-14-5,5>>^ Então lhes perguntou: Qual de vós, se lhe cair num poço um filho, ou um boi, não o tirará logo, mesmo em dia de sábado?

[[v42-14-6]]

^<<v42-14-6,6>>^ A isto nada puderam responder.

[[v42-14-7]]

^<<v42-14-7,7>>^ Ao notar como os convidados escolhiam os primeiros lugares, propôs-lhes esta parábola:

[[v42-14-8]]

^<<v42-14-8,8>>^ Quando por alguém fores convidado às bodas, não te reclines no primeiro lugar; não aconteça que esteja convidado outro mais digno do que tu;

[[v42-14-9]]

^<<v42-14-9,9>>^ e vindo o que te convidou a ti e a ele, te diga: Dá o lugar a este; e então, com vergonha, tenhas de tomar o último lugar.

[[v42-14-10]]

^<<v42-14-10,10>>^ Mas, quando fores convidado, vai e reclina-te no último lugar, para que, quando vier o que te convidou, te diga: Amigo, sobe mais para cima. Então terás honra diante de todos os que estiverem contigo à mesa.

[[v42-14-11]]

^<<v42-14-11,11>>^ Porque todo o que a si mesmo se exaltar será humilhado, e aquele que a si mesmo se humilhar será exaltado.

[[v42-14-12]]

^<<v42-14-12,12>>^ Disse também ao que o havia convidado: Quando deres um jantar, ou uma ceia, não convides teus amigos, nem teus irmãos, nem teus parentes, nem os vizinhos ricos, para que não suceda que também eles te tornem a convidar, e te seja isso retribuído.

[[v42-14-13]]

^<<v42-14-13,13>>^ Mas quando deres um banquete, convida os pobres, os aleijados, os mancos e os cegos;

[[v42-14-14]]

^<<v42-14-14,14>>^ e serás bem-aventurado; porque eles não têm com que te retribuir; pois retribuído te será na ressurreição dos justos.

[[v42-14-15]]

^<<v42-14-15,15>>^ Ao ouvir isso um dos que estavam com ele à mesa, disse-lhe: Bem-aventurado aquele que comer pão no reino de Deus.

[[v42-14-16]]

^<<v42-14-16,16>>^ Jesus, porém, lhe disse: Certo homem dava uma grande ceia, e convidou a muitos.

[[v42-14-17]]

^<<v42-14-17,17>>^ E à hora da ceia mandou o seu servo dizer aos convidados: vinde, porque tudo já está preparado.

[[v42-14-18]]

^<<v42-14-18,18>>^ Mas todos à uma começaram a escusar-se. Disse-lhe o primeiro: Comprei um campo, e preciso ir vê-lo; rogo-te que me dês por escusado.

[[v42-14-19]]

^<<v42-14-19,19>>^ Outro disse: Comprei cinco juntas de bois, e vou experimentá-los; rogo-te que me dês por escusado.

[[v42-14-20]]

^<<v42-14-20,20>>^ Ainda outro disse: Casei-me e portanto não posso ir.

[[v42-14-21]]

^<<v42-14-21,21>>^ Voltou o servo e contou tudo isto a seu senhor: Então o dono da casa, indignado, disse a seu servo: Sai depressa para as ruas e becos da cidade e traze aqui os pobres, os aleijados, os cegos e os coxos.

[[v42-14-22]]

^<<v42-14-22,22>>^ Depois disse o servo: Senhor, feito está como o ordenaste, e ainda há lugar.

[[v42-14-23]]

^<<v42-14-23,23>>^ Respondeu o senhor ao servo: Sai pelos caminhos e valados, e obriga-os a entrar, para que a minha casa se encha.

[[v42-14-24]]

^<<v42-14-24,24>>^ Pois eu vos digo que nenhum daqueles homens que foram convidados provará a minha ceia.

[[v42-14-25]]

^<<v42-14-25,25>>^ Ora, iam com ele grandes multidões; e, voltando-se, disse-lhes:

[[v42-14-26]]

^<<v42-14-26,26>>^ Se alguém vier a mim, e não aborrecer a pai e mãe, a mulher e filhos, a irmãos e irmãs, e ainda também à própria vida, não pode ser meu discípulo.

[[v42-14-27]]

^<<v42-14-27,27>>^ Quem não leva a sua cruz e não me segue, não pode ser meu discípulo.

[[v42-14-28]]

^<<v42-14-28,28>>^ Pois qual de vós, querendo edificar uma torre, não se senta primeiro a calcular as despesas, para ver se tem com que a acabar?

[[v42-14-29]]

^<<v42-14-29,29>>^ Para não acontecer que, depois de haver posto os alicerces, e não a podendo acabar, todos os que a virem comecem a zombar dele,

[[v42-14-30]]

^<<v42-14-30,30>>^ dizendo: Este homem começou a edificar e não pode acabar.

[[v42-14-31]]

^<<v42-14-31,31>>^ Ou qual é o rei que, indo entrar em guerra contra outro rei, não se senta primeiro a consultar se com dez mil pode sair ao encontro do que vem contra ele com vinte mil?

[[v42-14-32]]

^<<v42-14-32,32>>^ No caso contrário, enquanto o outro ainda está longe, manda embaixadores, e pede condições de paz.

[[v42-14-33]]

^<<v42-14-33,33>>^ Assim, pois, todo aquele dentre vós que não renuncia a tudo quanto possui, não pode ser meu discípulo.

[[v42-14-34]]

^<<v42-14-34,34>>^ Bom é o sal; mas se o sal se tornar insípido, com que se há de restaurar-lhe o sabor?

[[v42-14-35]]

^<<v42-14-35,35>>^ Não presta nem para terra, nem para adubo; lançam-no fora. Quem tem ouvidos para ouvir, ouça.

'''

xref:042-lucas/042-lucas-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-lucas/042-lucas-015.adoc#v42-15-0[Próximo Capítulo &#62;]