include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-9-1]]

^<<v42-9-1,1>>^ Reunindo os doze, deu-lhes poder e autoridade sobre todos os demônios, e para curarem doenças;

[[v42-9-2]]

^<<v42-9-2,2>>^ e enviou-os a pregar o reino de Deus, e fazer curas,

[[v42-9-3]]

^<<v42-9-3,3>>^ dizendo-lhes: Nada leveis para o caminho, nem bordão, nem alforje, nem pão, nem dinheiro; nem tenhais duas túnicas.

[[v42-9-4]]

^<<v42-9-4,4>>^ Em qualquer casa em que entrardes, nela ficai, e dali partireis.

[[v42-9-5]]

^<<v42-9-5,5>>^ Mas, onde quer que não vos receberem, saindo daquela cidade, sacudi o pó dos vossos pés, em testemunho contra eles.

[[v42-9-6]]

^<<v42-9-6,6>>^ Saindo, pois, os discípulos percorreram as aldeias, anunciando o evangelho e fazendo curas por toda parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ Ora, o tetrarca Herodes soube de tudo o que se passava, e ficou muito perplexo, porque diziam uns: João ressuscitou dos mortos;

[[v42-9-8]]

^<<v42-9-8,8>>^ outros: Elias apareceu; e outros: Um dos antigos profetas se levantou.

[[v42-9-9]]

^<<v42-9-9,9>>^ Herodes, porém, disse: A João eu mandei degolar; quem é, pois, este a respeito de quem ouço tais coisas? E procurava vê-lo.

[[v42-9-10]]

^<<v42-9-10,10>>^ Quando os apóstolos voltaram, contaram-lhe tudo o que havia feito. E ele, levando-os consigo, retirou-se à parte para uma cidade chamada Betsaida.

[[v42-9-11]]

^<<v42-9-11,11>>^ Mas as multidões, percebendo isto, seguiram-no; e ele as recebeu, e falava-lhes do reino de Deus, e sarava os que necessitavam de cura.

[[v42-9-12]]

^<<v42-9-12,12>>^ Ora, quando o dia começava a declinar, aproximando-se os doze, disseram-lhe: Despede a multidão, para que, indo às aldeias e aos sítios em redor, se hospedem, e achem o que comer; porque aqui estamos em lugar deserto.

[[v42-9-13]]

^<<v42-9-13,13>>^ Mas ele lhes disse: Dai-lhes vós de comer. Responderam eles: Não temos senão cinco pães e dois peixes; salvo se nós formos comprar comida para todo este povo.

[[v42-9-14]]

^<<v42-9-14,14>>^ Pois eram cerca de cinco mil homens. Então disse a seus discípulos: Fazei-os reclinar-se em grupos de cerca de cinqüenta cada um.

[[v42-9-15]]

^<<v42-9-15,15>>^ Assim o fizeram, mandando que todos se reclinassem.

[[v42-9-16]]

^<<v42-9-16,16>>^ E tomando Jesus os cinco pães e os dois peixes, e olhando para o céu, os abençoou e partiu, e os entregava aos seus discípulos para os porem diante da multidão.

[[v42-9-17]]

^<<v42-9-17,17>>^ Todos, pois, comeram e se fartaram; e foram levantados, do que lhes sobejou, doze cestos de pedaços.

[[v42-9-18]]

^<<v42-9-18,18>>^ Enquanto ele estava orando à parte achavam-se com ele somente seus discípulos; e perguntou-lhes: Quem dizem as multidões que eu sou?

[[v42-9-19]]

^<<v42-9-19,19>>^ Responderam eles: Uns dizem: João, o Batista; outros: Elias; e ainda outros, que um dos antigos profetas se levantou.

[[v42-9-20]]

^<<v42-9-20,20>>^ Então lhes perguntou: Mas vós, quem dizeis que eu sou? Respondendo Pedro, disse: O Cristo de Deus.

[[v42-9-21]]

^<<v42-9-21,21>>^ Jesus, porém, advertindo-os, mandou que não contassem isso a ninguém;

[[v42-9-22]]

^<<v42-9-22,22>>^ e disse-lhes: É necessário que o Filho do homem padeça muitas coisas, que seja rejeitado pelos anciãos, pelos principais sacerdotes e escribas, que seja morto, e que ao terceiro dia ressuscite.

[[v42-9-23]]

^<<v42-9-23,23>>^ Em seguida dizia a todos: Se alguém quer vir após mim, negue-se a si mesmo, tome cada dia a sua cruz, e siga-me.

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois quem quiser salvar a sua vida, perdê-la-á; mas quem perder a sua vida por amor de mim, esse a salvará.

[[v42-9-25]]

^<<v42-9-25,25>>^ Pois, que aproveita ao homem ganhar o mundo inteiro, e perder-se, ou prejudicar-se a si mesmo?

[[v42-9-26]]

^<<v42-9-26,26>>^ Porque, quem se envergonhar de mim e das minhas palavras, dele se envergonhará o Filho do homem, quando vier na sua glória, e na do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Mas em verdade vos digo: Alguns há, dos que estão aqui, que de modo nenhum provarão a morte até que vejam o reino de Deus.

[[v42-9-28]]

^<<v42-9-28,28>>^ Cerca de oito dias depois de ter proferido essas palavras, tomou Jesus consigo a Pedro, a João e a Tiago, e subiu ao monte para orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ Enquanto ele orava, mudou-se a aparência do seu rosto, e a sua roupa tornou-se branca e resplandecente.

[[v42-9-30]]

^<<v42-9-30,30>>^ E eis que estavam falando com ele dois varões, que eram Moisés e Elias,

[[v42-9-31]]

^<<v42-9-31,31>>^ os quais apareceram com glória, e falavam da sua partida que estava para cumprir-se em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Ora, Pedro e os que estavam com ele se haviam deixado vencer pelo sono; despertando, porém, viram a sua glória e os dois varões que estavam com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ E, quando estes se apartavam dele, disse Pedro a Jesus: Mestre, bom é estarmos nós aqui: façamos, pois, três cabanas, uma para ti, uma para Moisés, e uma para Elias, não sabendo o que dizia.

[[v42-9-34]]

^<<v42-9-34,34>>^ Enquanto ele ainda falava, veio uma nuvem que os cobriu; e se atemorizaram ao entrarem na nuvem.

[[v42-9-35]]

^<<v42-9-35,35>>^ E da nuvem saiu uma voz que dizia: Este é o meu Filho, o meu eleito; a ele ouvi.

[[v42-9-36]]

^<<v42-9-36,36>>^ Ao soar esta voz, Jesus foi achado sozinho; e eles calaram-se, e por aqueles dias não contaram a ninguém nada do que tinham visto.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, quando desceram do monte, veio-lhe ao encontro uma grande multidão.

[[v42-9-38]]

^<<v42-9-38,38>>^ E eis que um homem dentre a multidão clamou, dizendo: Mestre, peço-te que olhes para meu filho, porque é o único que tenho;

[[v42-9-39]]

^<<v42-9-39,39>>^ pois um espírito se apodera dele, fazendo-o gritar subitamente, convulsiona-o até escumar e, mesmo depois de o ter quebrantado, dificilmente o larga.

[[v42-9-40]]

^<<v42-9-40,40>>^ E roguei aos teus discípulos que o expulsassem, mas não puderam.

[[v42-9-41]]

^<<v42-9-41,41>>^ Respondeu Jesus: ó geração incrédula e perversa! até quando estarei convosco e vos sofrerei? Traze-me cá o teu filho.

[[v42-9-42]]

^<<v42-9-42,42>>^ Ainda quando ele vinha chegando, o demônio o derribou e o convulsionou; mas Jesus repreendeu o espírito imundo, curou o menino e o entregou a seu pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ E todos se maravilhavam da majestade de Deus. E admirando-se todos de tudo o que Jesus fazia, disse ele a seus discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ Ponde vós estas palavras em vossos ouvidos; pois o Filho do homem está para ser entregue nas mãos dos homens.

[[v42-9-45]]

^<<v42-9-45,45>>^ Eles, porém, não entendiam essa palavra, cujo sentido lhes era encoberto para que não o compreendessem; e temiam interrogá-lo a esse respeito.

[[v42-9-46]]

^<<v42-9-46,46>>^ E suscitou-se entre eles uma discussão sobre qual deles seria o maior.

[[v42-9-47]]

^<<v42-9-47,47>>^ Mas Jesus, percebendo o pensamento de seus corações, tomou uma criança, pô-la junto de si,

[[v42-9-48]]

^<<v42-9-48,48>>^ e disse-lhes: Qualquer que receber esta criança em meu nome, a mim me recebe; e qualquer que me receber a mim, recebe aquele que me enviou; pois aquele que entre vós todos é o menor, esse é grande.

[[v42-9-49]]

^<<v42-9-49,49>>^ Disse-lhe João: Mestre, vimos um homem que em teu nome expulsava demônios; e lho proibimos, porque não segue conosco.

[[v42-9-50]]

^<<v42-9-50,50>>^ Respondeu-lhe Jesus: Não lho proibais; porque quem não é contra vós é por vós.

[[v42-9-51]]

^<<v42-9-51,51>>^ Ora, quando se completavam os dias para a sua assunção, manifestou o firme propósito de ir a Jerusalém.

[[v42-9-52]]

^<<v42-9-52,52>>^ Enviou, pois, mensageiros adiante de si. Indo eles, entraram numa aldeia de samaritanos para lhe prepararem pousada.

[[v42-9-53]]

^<<v42-9-53,53>>^ Mas não o receberam, porque viajava em direção a Jerusalém.

[[v42-9-54]]

^<<v42-9-54,54>>^ Vendo isto os discípulos Tiago e João, disseram: Senhor, queres que mandemos descer fogo do céu para os consumir &#123;como Elias também fez?&#125;

[[v42-9-55]]

^<<v42-9-55,55>>^ Ele porém, voltando-se, repreendeu-os, &#123;e disse: Vós não sabeis de que espírito sois.&#125;

[[v42-9-56]]

^<<v42-9-56,56>>^ &#123;Pois o Filho do Homem não veio para destruir as vidas dos homens, mas para salvá-las.&#125; E foram para outra aldeia.

[[v42-9-57]]

^<<v42-9-57,57>>^ Quando iam pelo caminho, disse-lhe um homem: Seguir-te-ei para onde quer que fores.

[[v42-9-58]]

^<<v42-9-58,58>>^ Respondeu-lhe Jesus: As raposas têm covis, e as aves do céu têm ninhos; mas o Filho do homem não tem onde reclinar a cabeça.

[[v42-9-59]]

^<<v42-9-59,59>>^ E a outro disse: Segue-me. Ao que este respondeu: Permite-me ir primeiro sepultar meu pai.

[[v42-9-60]]

^<<v42-9-60,60>>^ Replicou-lhe Jesus: Deixa os mortos sepultar os seus próprios mortos; tu, porém, vai e anuncia o reino de Deus.

[[v42-9-61]]

^<<v42-9-61,61>>^ Disse também outro: Senhor, eu te seguirei, mas deixa-me despedir primeiro dos que estão em minha casa.

[[v42-9-62]]

^<<v42-9-62,62>>^ Jesus, porém, lhe respondeu: Ninguém que lança mão do arado e olha para trás é apto para o reino de Deus.

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]