include::./index.adoc[]

[[v42-19-0]]
=== Lucas, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-19-1]]

^<<v42-19-1,1>>^ Tendo Jesus entrado em Jericó, ia atravessando a cidade.

[[v42-19-2]]

^<<v42-19-2,2>>^ Havia ali um homem chamado Zaqueu, o qual era chefe de publicanos e era rico.

[[v42-19-3]]

^<<v42-19-3,3>>^ Este procurava ver quem era Jesus, e não podia, por causa da multidão, porque era de pequena estatura.

[[v42-19-4]]

^<<v42-19-4,4>>^ E correndo adiante, subiu a um sicômoro a fim de vê-lo, porque havia de passar por ali.

[[v42-19-5]]

^<<v42-19-5,5>>^ Quando Jesus chegou àquele lugar, olhou para cima e disse-lhe: Zaqueu, desce depressa; porque importa que eu fique hoje em tua casa.

[[v42-19-6]]

^<<v42-19-6,6>>^ Desceu, pois, a toda a pressa, e o recebeu com alegria.

[[v42-19-7]]

^<<v42-19-7,7>>^ Ao verem isso, todos murmuravam, dizendo: Entrou para ser hóspede de um homem pecador.

[[v42-19-8]]

^<<v42-19-8,8>>^ Zaqueu, porém, levantando-se, disse ao Senhor: Eis aqui, Senhor, dou aos pobres metade dos meus bens; e se em alguma coisa tenho defraudado alguém, eu lho restituo quadruplicado.

[[v42-19-9]]

^<<v42-19-9,9>>^ Disse-lhe Jesus: Hoje veio a salvação a esta casa, porquanto também este é filho de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Porque o Filho do homem veio buscar e salvar o que se havia perdido.

[[v42-19-11]]

^<<v42-19-11,11>>^ Ouvindo eles isso, prosseguiu Jesus, e contou uma parábola, visto estar ele perto de Jerusalém, e pensarem eles que o reino de Deus se havia de manifestar imediatamente.

[[v42-19-12]]

^<<v42-19-12,12>>^ Disse pois: Certo homem nobre partiu para uma terra longínqua, a fim de tomar posse de um reino e depois voltar.

[[v42-19-13]]

^<<v42-19-13,13>>^ E chamando dez servos seus, deu-lhes dez minas, e disse-lhes: Negociai até que eu venha.

[[v42-19-14]]

^<<v42-19-14,14>>^ Mas os seus concidadãos odiavam-no, e enviaram após ele uma embaixada, dizendo: Não queremos que este homem reine sobre nós.

[[v42-19-15]]

^<<v42-19-15,15>>^ E sucedeu que, ao voltar ele, depois de ter tomado posse do reino, mandou chamar aqueles servos a quem entregara o dinheiro, a fim de saber como cada um havia negociado.

[[v42-19-16]]

^<<v42-19-16,16>>^ Apresentou-se, pois, o primeiro, e disse: Senhor, a tua mina rendeu dez minas.

[[v42-19-17]]

^<<v42-19-17,17>>^ Respondeu-lhe o senhor: Bem está, servo bom! porque no mínimo foste fiel, sobre dez cidades terás autoridade.

[[v42-19-18]]

^<<v42-19-18,18>>^ Veio o segundo, dizendo: Senhor, a tua mina rendeu cinco minas.

[[v42-19-19]]

^<<v42-19-19,19>>^ A este também respondeu: Sê tu também sobre cinco cidades.

[[v42-19-20]]

^<<v42-19-20,20>>^ E veio outro, dizendo: Senhor, eis aqui a tua mina, que guardei num lenço;

[[v42-19-21]]

^<<v42-19-21,21>>^ pois tinha medo de ti, porque és homem severo; tomas o que não puseste, e ceifas o que não semeaste.

[[v42-19-22]]

^<<v42-19-22,22>>^ Disse-lhe o Senhor: Servo mau! pela tua boca te julgarei; sabias que eu sou homem severo, que tomo o que não pus, e ceifo o que não semeei;

[[v42-19-23]]

^<<v42-19-23,23>>^ por que, pois, não puseste o meu dinheiro no barco? então vindo eu, o teria retirado com os juros.

[[v42-19-24]]

^<<v42-19-24,24>>^ E disse aos que estavam ali: Tirai-lhe a mina, e dai-a ao que tem as dez minas.

[[v42-19-25]]

^<<v42-19-25,25>>^ Responderam-lhe eles: Senhor, ele tem dez minas.

[[v42-19-26]]

^<<v42-19-26,26>>^ Pois eu vos digo que a todo o que tem, dar-se-lhe-á; mas ao que não tem, até aquilo que tem ser-lhe-á tirado.

[[v42-19-27]]

^<<v42-19-27,27>>^ Quanto, porém, àqueles meus inimigos que não quiseram que eu reinasse sobre eles, trazei-os aqui, e matai-os diante de mim.

[[v42-19-28]]

^<<v42-19-28,28>>^ Tendo Jesus assim falado, ia caminhando adiante deles, subindo para Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ Ao aproximar-se de Betfagé e de Betânia, junto do monte que se chama das Oliveiras, enviou dois dos discípulos,

[[v42-19-30]]

^<<v42-19-30,30>>^ dizendo-lhes: Ide à aldeia que está defronte, e aí, ao entrar, achareis preso um jumentinho em que ninguém jamais montou; desprendei-o e trazei-o.

[[v42-19-31]]

^<<v42-19-31,31>>^ Se alguém vos perguntar: Por que o desprendeis? respondereis assim: O Senhor precisa dele.

[[v42-19-32]]

^<<v42-19-32,32>>^ Partiram, pois, os que tinham sido enviados, e acharam conforme lhes dissera.

[[v42-19-33]]

^<<v42-19-33,33>>^ Enquanto desprendiam o jumentinho, os seus donos lhes perguntaram: Por que desprendeis o jumentinho?

[[v42-19-34]]

^<<v42-19-34,34>>^ Responderam eles: O Senhor precisa dele.

[[v42-19-35]]

^<<v42-19-35,35>>^ Trouxeram-no, pois, a Jesus e, lançando os seus mantos sobre o jumentinho, fizeram que Jesus montasse.

[[v42-19-36]]

^<<v42-19-36,36>>^ E, enquanto ele ia passando, outros estendiam no caminho os seus mantos.

[[v42-19-37]]

^<<v42-19-37,37>>^ Quando já ia chegando à descida do Monte das Oliveiras, toda a multidão dos discípulos, regozijando-se, começou a louvar a Deus em alta voz, por todos os milagres que tinha visto,

[[v42-19-38]]

^<<v42-19-38,38>>^ dizendo: Bendito o Rei que vem em nome do Senhor; paz no céu, e glória nas alturas.

[[v42-19-39]]

^<<v42-19-39,39>>^ Nisso, disseram-lhe alguns dos fariseus dentre a multidão: Mestre, repreende os teus discípulos.

[[v42-19-40]]

^<<v42-19-40,40>>^ Ao que ele respondeu: Digo-vos que, se estes se calarem, as pedras clamarão.

[[v42-19-41]]

^<<v42-19-41,41>>^ E quando chegou perto e viu a cidade, chorou sobre ela,

[[v42-19-42]]

^<<v42-19-42,42>>^ dizendo: Ah! se tu conhecesses, ao menos neste dia, o que te poderia trazer a paz! mas agora isso está encoberto aos teus olhos.

[[v42-19-43]]

^<<v42-19-43,43>>^ Porque dias virão sobre ti em que os teus inimigos te cercarão de trincheiras, e te sitiarão, e te apertarão de todos os lados,

[[v42-19-44]]

^<<v42-19-44,44>>^ e te derribarão, a ti e aos teus filhos que dentro de ti estiverem; e não deixarão em ti pedra sobre pedra, porque não conheceste o tempo da tua visitação.

[[v42-19-45]]

^<<v42-19-45,45>>^ Então, entrando ele no templo, começou a expulsar os que ali vendiam,

[[v42-19-46]]

^<<v42-19-46,46>>^ dizendo-lhes: Está escrito: A minha casa será casa de oração; vós, porém, a fizestes covil de salteadores.

[[v42-19-47]]

^<<v42-19-47,47>>^ E todos os dias ensinava no templo; mas os principais sacerdotes, os escribas, e os principais do povo procuravam matá-lo;

[[v42-19-48]]

^<<v42-19-48,48>>^ mas não achavam meio de o fazer; porque todo o povo ficava enlevado ao ouvi-lo.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]