include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-21-1]]

^<<v42-21-1,1>>^ Jesus, levantando os olhos, viu os ricos deitarem as suas ofertas no cofre;

[[v42-21-2]]

^<<v42-21-2,2>>^ viu também uma pobre viúva lançar ali dois leptos;

[[v42-21-3]]

^<<v42-21-3,3>>^ e disse: Em verdade vos digo que esta pobre viúva deu mais do que todos;

[[v42-21-4]]

^<<v42-21-4,4>>^ porque todos aqueles deram daquilo que lhes sobrava; mas esta, da sua pobreza, deu tudo o que tinha para o seu sustento.

[[v42-21-5]]

^<<v42-21-5,5>>^ E falando-lhe alguns a respeito do templo, como estava ornado de formosas pedras e dádivas, disse ele:

[[v42-21-6]]

^<<v42-21-6,6>>^ Quanto a isto que vedes, dias virão em que não se deixará aqui pedra sobre pedra, que não seja derribada.

[[v42-21-7]]

^<<v42-21-7,7>>^ Perguntaram-lhe então: Mestre, quando, pois, sucederão estas coisas? E que sinal haverá, quando elas estiverem para se cumprir?

[[v42-21-8]]

^<<v42-21-8,8>>^ Respondeu então ele: Acautelai-vos; não sejais enganados; porque virão muitos em meu nome, dizendo: Sou eu; e: O tempo é chegado; não vades após eles.

[[v42-21-9]]

^<<v42-21-9,9>>^ Quando ouvirdes de guerras e tumultos, não vos assusteis; pois é necessário que primeiro aconteçam essas coisas; mas o fim não será logo.

[[v42-21-10]]

^<<v42-21-10,10>>^ Então lhes disse: Levantar-se-á nação contra nação, e reino contra reino;

[[v42-21-11]]

^<<v42-21-11,11>>^ e haverá em vários lugares grandes terremotos, e pestes e fomes; haverá também coisas espantosas, e grandes sinais do céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ Mas antes de todas essas coisas vos hão de prender e perseguir, entregando-vos às sinagogas e aos cárceres, e conduzindo-vos à presença de reis e governadores, por causa do meu nome.

[[v42-21-13]]

^<<v42-21-13,13>>^ Isso vos acontecerá para que deis testemunho.

[[v42-21-14]]

^<<v42-21-14,14>>^ Proponde, pois, em vossos corações não premeditar como haveis de fazer a vossa defesa;

[[v42-21-15]]

^<<v42-21-15,15>>^ porque eu vos darei boca e sabedoria, a que nenhum dos vossos adversário poderá resistir nem contradizer.

[[v42-21-16]]

^<<v42-21-16,16>>^ E até pelos pais, e irmãos, e parentes, e amigos sereis entregues; e matarão alguns de vós;

[[v42-21-17]]

^<<v42-21-17,17>>^ e sereis odiados de todos por causa do meu nome.

[[v42-21-18]]

^<<v42-21-18,18>>^ Mas não se perderá um único cabelo da vossa cabeça.

[[v42-21-19]]

^<<v42-21-19,19>>^ Pela vossa perseverança ganhareis as vossas almas.

[[v42-21-20]]

^<<v42-21-20,20>>^ Mas, quando virdes Jerusalém cercada de exércitos, sabei então que é chegada a sua desolação.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então, os que estiverem na Judéia fujam para os montes; os que estiverem dentro da cidade, saiam; e os que estiverem nos campos não entrem nela.

[[v42-21-22]]

^<<v42-21-22,22>>^ Porque dias de vingança são estes, para que se cumpram todas as coisas que estão escritas.

[[v42-21-23]]

^<<v42-21-23,23>>^ Ai das que estiverem grávidas, e das que amamentarem naqueles dias! porque haverá grande angústia sobre a terra, e ira contra este povo.

[[v42-21-24]]

^<<v42-21-24,24>>^ E cairão ao fio da espada, e para todas as nações serão levados cativos; e Jerusalém será pisada pelos gentios, até que os tempos destes se completem.

[[v42-21-25]]

^<<v42-21-25,25>>^ E haverá sinais no sol, na lua e nas estrelas; e sobre a terra haverá angústia das nações em perplexidade pelo bramido do mar e das ondas.

[[v42-21-26]]

^<<v42-21-26,26>>^ os homens desfalecerão de terror, e pela expectação das coisas que sobrevirão ao mundo; porquanto os poderes do céu serão abalados.

[[v42-21-27]]

^<<v42-21-27,27>>^ Então verão vir o Filho do homem em uma nuvem, com poder e grande glória.

[[v42-21-28]]

^<<v42-21-28,28>>^ Ora, quando essas coisas começarem a acontecer, exultai e levantai as vossas cabeças, porque a vossa redenção se aproxima.

[[v42-21-29]]

^<<v42-21-29,29>>^ Propôs-lhes então uma parábola: Olhai para a figueira, e para todas as árvores;

[[v42-21-30]]

^<<v42-21-30,30>>^ quando começam a brotar, sabeis por vós mesmos, ao vê-las, que já está próximo o verão.

[[v42-21-31]]

^<<v42-21-31,31>>^ Assim também vós, quando virdes acontecerem estas coisas, sabei que o reino de Deus está próximo.

[[v42-21-32]]

^<<v42-21-32,32>>^ Em verdade vos digo que não passará esta geração até que tudo isso se cumpra.

[[v42-21-33]]

^<<v42-21-33,33>>^ Passará o céu e a terra, mas as minhas palavras jamais passarão.

[[v42-21-34]]

^<<v42-21-34,34>>^ Olhai por vós mesmos; não aconteça que os vossos corações se carreguem de glutonaria, de embriaguez, e dos cuidados da vida, e aquele dia vos sobrevenha de improviso como um laço.

[[v42-21-35]]

^<<v42-21-35,35>>^ Porque há de vir sobre todos os que habitam na face da terra.

[[v42-21-36]]

^<<v42-21-36,36>>^ Vigiai, pois, em todo o tempo, orando, para que possais escapar de todas estas coisas que hão de acontecer, e estar em pé na presença do Filho do homem.

[[v42-21-37]]

^<<v42-21-37,37>>^ Ora, de dia ensinava no templo, e à noite, saindo, pousava no monte chamado das Oliveiras.

[[v42-21-38]]

^<<v42-21-38,38>>^ E todo o povo ia ter com ele no templo, de manhã cedo, para o ouvir.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]