include::./index.adoc[]

[[v42-16-0]]
=== Lucas, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-16-1]]

^<<v42-16-1,1>>^ Dizia Jesus também aos seus discípulos: Havia certo homem rico, que tinha um mordomo; e este foi acusado perante ele de estar dissipando os seus bens.

[[v42-16-2]]

^<<v42-16-2,2>>^ Chamou-o, então, e lhe disse: Que é isso que ouço dizer de ti? Presta contas da tua mordomia; porque já não podes mais ser meu mordomo.

[[v42-16-3]]

^<<v42-16-3,3>>^ Disse, pois, o mordomo consigo: Que hei de fazer, já que o meu senhor me tira a mordomia? Para cavar, não tenho forças; de mendigar, tenho vergonha.

[[v42-16-4]]

^<<v42-16-4,4>>^ Agora sei o que vou fazer, para que, quando for desapossado da mordomia, me recebam em suas casas.

[[v42-16-5]]

^<<v42-16-5,5>>^ E chamando a si cada um dos devedores do seu senhor, perguntou ao primeiro: Quanto deves ao meu senhor?

[[v42-16-6]]

^<<v42-16-6,6>>^ Respondeu ele: Cem cados de azeite. Disse-lhe então: Toma a tua conta, senta-te depressa e escreve cinqüenta.

[[v42-16-7]]

^<<v42-16-7,7>>^ Perguntou depois a outro: E tu, quanto deves? Respondeu ele: Cem coros de trigo. E disse-lhe: Toma a tua conta e escreve oitenta.

[[v42-16-8]]

^<<v42-16-8,8>>^ E louvou aquele senhor ao injusto mordomo por haver procedido com sagacidade; porque os filhos deste mundo são mais sagazes para com a sua geração do que os filhos da luz.

[[v42-16-9]]

^<<v42-16-9,9>>^ Eu vos digo ainda: Granjeai amigos por meio das riquezas da injustiça; para que, quando estas vos faltarem, vos recebam eles nos tabernáculos eternos.

[[v42-16-10]]

^<<v42-16-10,10>>^ Quem é fiel no pouco, também é fiel no muito; quem é injusto no pouco, também é injusto no muito.

[[v42-16-11]]

^<<v42-16-11,11>>^ Se, pois, nas riquezas injustas não fostes fiéis, quem vos confiará as verdadeiras?

[[v42-16-12]]

^<<v42-16-12,12>>^ E se no alheio não fostes fiéis, quem vos dará o que é vosso?

[[v42-16-13]]

^<<v42-16-13,13>>^ Nenhum servo pode servir dois senhores; porque ou há de odiar a um e amar ao outro, o há de odiar a um e amar ao outro, o há de dedicar-se a um e desprezar o outro. Não podeis servir a Deus e às riquezas.

[[v42-16-14]]

^<<v42-16-14,14>>^ Os fariseus, que eram gananciosos, ouviam todas essas coisas e zombavam dele.

[[v42-16-15]]

^<<v42-16-15,15>>^ E ele lhes disse: Vós sois os que vos justificais a vós mesmos diante dos homens, mas Deus conhece os vossos corações; porque o que entre os homens é elevado, perante Deus é abominação.

[[v42-16-16]]

^<<v42-16-16,16>>^ A lei e os profetas vigoraram até João; desde então é anunciado o evangelho do reino de Deus, e todo homem forceja por entrar nele.

[[v42-16-17]]

^<<v42-16-17,17>>^ É, porém, mais fácil passar o céu e a terra do que cair um til da lei.

[[v42-16-18]]

^<<v42-16-18,18>>^ Todo aquele que repudia sua mulher e casa com outra, comete adultério; e quem casa com a que foi repudiada pelo marido, também comete adultério.

[[v42-16-19]]

^<<v42-16-19,19>>^ Ora, havia um homem rico que se vestia de púrpura e de linho finíssimo, e todos os dias se regalava esplendidamente.

[[v42-16-20]]

^<<v42-16-20,20>>^ Ao seu portão fora deitado um mendigo, chamado Lázaro, todo coberto de úlceras;

[[v42-16-21]]

^<<v42-16-21,21>>^ o qual desejava alimentar-se com as migalhas que caíam da mesa do rico; e os próprios cães vinham lamber-lhe as úlceras.

[[v42-16-22]]

^<<v42-16-22,22>>^ Veio a morrer o mendigo, e foi levado pelos anjos para o seio de Abraão; morreu também o rico, e foi sepultado.

[[v42-16-23]]

^<<v42-16-23,23>>^ No inferno, ergueu os olhos, estando em tormentos, e viu ao longe a Abraão, e a Lázaro no seu seio.

[[v42-16-24]]

^<<v42-16-24,24>>^ E, clamando, disse: Pai Abraão, tem misericórdia de mim, e envia-me Lázaro, para que molhe na água a ponta do dedo e me refresque a língua, porque estou atormentado nesta chama.

[[v42-16-25]]

^<<v42-16-25,25>>^ Disse, porém, Abraão: Filho, lembra-te de que em tua vida recebeste os teus bens, e Lázaro de igual modo os males; agora, porém, ele aqui é consolado, e tu atormentado.

[[v42-16-26]]

^<<v42-16-26,26>>^ E além disso, entre nós e vós está posto um grande abismo, de sorte que os que quisessem passar daqui para vós não poderiam, nem os de lá passar para nós.

[[v42-16-27]]

^<<v42-16-27,27>>^ Disse ele então: Rogo-te, pois, ó pai, que o mandes à casa de meu pai,

[[v42-16-28]]

^<<v42-16-28,28>>^ porque tenho cinco irmãos; para que lhes dê testemunho, a fim de que não venham eles também para este lugar de tormento.

[[v42-16-29]]

^<<v42-16-29,29>>^ Disse-lhe Abraão: Têm Moisés e os profetas; ouçam-nos.

[[v42-16-30]]

^<<v42-16-30,30>>^ Respondeu ele: Não! pai Abraão; mas, se alguém dentre os mortos for ter com eles, hão de se arrepender.

[[v42-16-31]]

^<<v42-16-31,31>>^ Abraão, porém, lhe disse: Se não ouvem a Moisés e aos profetas, tampouco acreditarão, ainda que ressuscite alguém dentre os mortos.

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]