include::./index.adoc[]

[[v42-17-0]]
=== Lucas, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-17-1]]

^<<v42-17-1,1>>^ Disse Jesus a seus discípulos: É impossível que não venham tropeços, mas ai daquele por quem vierem!

[[v42-17-2]]

^<<v42-17-2,2>>^ Melhor lhe fora que se lhe pendurasse ao pescoço uma pedra de moinho e fosse lançado ao mar, do que fazer tropeçar um destes pequeninos.

[[v42-17-3]]

^<<v42-17-3,3>>^ Tende cuidado de vós mesmos; se teu irmão pecar, repreende-o; e se ele se arrepender, perdoa-lhe.

[[v42-17-4]]

^<<v42-17-4,4>>^ Mesmo se pecar contra ti sete vezes no dia, e sete vezes vier ter contigo, dizendo: Arrependo-me; tu lhe perdoarás.

[[v42-17-5]]

^<<v42-17-5,5>>^ Disseram então os apóstolos ao Senhor: Aumenta-nos a fé.

[[v42-17-6]]

^<<v42-17-6,6>>^ Respondeu o Senhor: Se tivésseis fé como um grão de mostarda, diríeis a esta amoreira: Desarraiga-te, e planta-te no mar; e ela vos obedeceria.

[[v42-17-7]]

^<<v42-17-7,7>>^ Qual de vós, tendo um servo a lavrar ou a apascentar gado, lhe dirá, ao voltar ele do campo: chega-te já, e reclina-te à mesa?

[[v42-17-8]]

^<<v42-17-8,8>>^ Não lhe dirá antes: Prepara-me a ceia, e cinge-te, e serve-me, até que eu tenha comido e bebido, e depois comerás tu e beberás?

[[v42-17-9]]

^<<v42-17-9,9>>^ Porventura agradecerá ao servo, porque este fez o que lhe foi mandado?

[[v42-17-10]]

^<<v42-17-10,10>>^ Assim também vós, quando fizerdes tudo o que vos for mandado, dizei: Somos servos inúteis; fizemos somente o que devíamos fazer.

[[v42-17-11]]

^<<v42-17-11,11>>^ E aconteceu que, indo ele a Jerusalém, passava pela divisa entre a Samária e a Galiléia.

[[v42-17-12]]

^<<v42-17-12,12>>^ Ao entrar em certa aldeia, saíram-lhe ao encontro dez leprosos, os quais pararam de longe,

[[v42-17-13]]

^<<v42-17-13,13>>^ e levantaram a voz, dizendo: Jesus, Mestre, tem compaixão de nós!

[[v42-17-14]]

^<<v42-17-14,14>>^ Ele, logo que os viu, disse-lhes: Ide, e mostrai-vos aos sacerdotes. E aconteceu que, enquanto iam, ficaram limpos.

[[v42-17-15]]

^<<v42-17-15,15>>^ Um deles, vendo que fora curado, voltou glorificando a Deus em alta voz;

[[v42-17-16]]

^<<v42-17-16,16>>^ e prostrou-se com o rosto em terra aos pés de Jesus, dando-lhe graças; e este era samaritano.

[[v42-17-17]]

^<<v42-17-17,17>>^ Perguntou, pois, Jesus: Não foram limpos os dez? E os nove, onde estão?

[[v42-17-18]]

^<<v42-17-18,18>>^ Não se achou quem voltasse para dar glória a Deus, senão este estrangeiro?

[[v42-17-19]]

^<<v42-17-19,19>>^ E disse-lhe: Levanta-te, e vai; a tua fé te salvou.

[[v42-17-20]]

^<<v42-17-20,20>>^ Sendo Jesus interrogado pelos fariseus sobre quando viria o reino de Deus, respondeu-lhes: O reino de Deus não vem com aparência exterior;

[[v42-17-21]]

^<<v42-17-21,21>>^ nem dirão: Ei-lo aqui! ou: Ei-lo ali! pois o reino de Deus está dentro de vós.

[[v42-17-22]]

^<<v42-17-22,22>>^ Então disse aos discípulos: Dias virão em que desejareis ver um dos dias do Filho do homem, e não o vereis.

[[v42-17-23]]

^<<v42-17-23,23>>^ Dir-vos-ão: Ei-lo ali! ou: Ei-lo aqui! não vades, nem os sigais;

[[v42-17-24]]

^<<v42-17-24,24>>^ pois, assim como o relâmpago, fuzilando em uma extremidade do céu, ilumina até a outra extremidade, assim será também o Filho do homem no seu dia.

[[v42-17-25]]

^<<v42-17-25,25>>^ Mas primeiro é necessário que ele padeça muitas coisas, e que seja rejeitado por esta geração.

[[v42-17-26]]

^<<v42-17-26,26>>^ Como aconteceu nos dias de Noé, assim também será nos dias do Filho do homem.

[[v42-17-27]]

^<<v42-17-27,27>>^ Comiam, bebiam, casavam e davam-se em casamento, até o dia em que Noé entrou na arca, e veio o dilúvio e os destruiu a todos.

[[v42-17-28]]

^<<v42-17-28,28>>^ Como também da mesma forma aconteceu nos dias de Ló: comiam, bebiam, compravam, vendiam, plantavam e edificavam;

[[v42-17-29]]

^<<v42-17-29,29>>^ mas no dia em que Ló saiu de Sodoma choveu do céu fogo e enxofre, e os destruiu a todos;

[[v42-17-30]]

^<<v42-17-30,30>>^ assim será no dia em que o Filho do homem se há de manifestar.

[[v42-17-31]]

^<<v42-17-31,31>>^ Naquele dia, quem estiver no eirado, tendo os seus bens em casa, não desça para tirá-los; e, da mesma sorte, o que estiver no campo, não volte para trás.

[[v42-17-32]]

^<<v42-17-32,32>>^ Lembrai-vos da mulher de Ló.

[[v42-17-33]]

^<<v42-17-33,33>>^ Qualquer que procurar preservar a sua vida, perdê-la-á, e qualquer que a perder, conservá-la-á.

[[v42-17-34]]

^<<v42-17-34,34>>^ Digo-vos: Naquela noite estarão dois numa cama; um será tomado, e o outro será deixado.

[[v42-17-35]]

^<<v42-17-35,35>>^ Duas mulheres estarão juntas moendo; uma será tomada, e a outra será deixada.

[[v42-17-36]]

^<<v42-17-36,36>>^ &#123;Dois homens estarão no campo; um será tomado, e o outro será deixado.&#125;

[[v42-17-37]]

^<<v42-17-37,37>>^ Perguntaram-lhe: Onde, Senhor? E respondeu-lhes: Onde estiver o corpo, aí se ajuntarão também os abutres.

'''

xref:042-lucas/042-lucas-016.adoc#v42-16-0[&#60; Capítulo Anterior] | <<v42-17-0,Topo>> | xref:042-lucas/042-lucas-018.adoc#v42-18-0[Próximo Capítulo &#62;]