include::./index.adoc[]

[[v42-3-0]]
=== Lucas, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-3-1]]

^<<v42-3-1,1>>^ No décimo quinto ano do reinado de Tibério César, sendo Pôncio Pilatos governador da Judéia, Herodes tetrarca da Galiléia, seu irmão Filipe tetrarca da região da Ituréia e de Traconites, e Lisânias tetrarca de Abilene,

[[v42-3-2]]

^<<v42-3-2,2>>^ sendo Anás e Caifás sumos sacerdotes, veio a palavra de Deus a João, filho de Zacarias, no deserto.

[[v42-3-3]]

^<<v42-3-3,3>>^ E ele percorreu toda a circunvizinhança do Jordão, pregando o batismo de arrependimento para remissão de pecados;

[[v42-3-4]]

^<<v42-3-4,4>>^ como está escrito no livro das palavras do profeta Isaías: Voz do que clama no deserto: Preparai o caminho do Senhor; endireitai as suas veredas.

[[v42-3-5]]

^<<v42-3-5,5>>^ Todo vale se encherá, e se abaixará todo monte e outeiro; o que é tortuoso se endireitará, e os caminhos escabrosos se aplanarão;

[[v42-3-6]]

^<<v42-3-6,6>>^ e toda a carne verá a salvação de Deus.

[[v42-3-7]]

^<<v42-3-7,7>>^ João dizia, pois, às multidões que saíam para ser batizadas por ele: Raça de víboras, quem vos ensina a fugir da ira vindoura?

[[v42-3-8]]

^<<v42-3-8,8>>^ Produzi, pois, frutos dignos de arrependimento; e não comeceis a dizer em vós mesmos: Temos por pai a Abrão; porque eu vos digo que até destas pedras Deus pode suscitar filhos a Abrão.

[[v42-3-9]]

^<<v42-3-9,9>>^ Também já está posto o machado à raiz das árvores; toda árvore, pois, que não produz bom fruto, é cortada e lançada no fogo.

[[v42-3-10]]

^<<v42-3-10,10>>^ Ao que lhe perguntavam as multidões: Que faremos, pois?

[[v42-3-11]]

^<<v42-3-11,11>>^ Respondia-lhes então: Aquele que tem duas túnicas, reparta com o que não tem nenhuma, e aquele que tem alimentos, faça o mesmo.

[[v42-3-12]]

^<<v42-3-12,12>>^ Chegaram também uns publicanos para serem batizados, e perguntaram-lhe: Mestre, que havemos nós de fazer?

[[v42-3-13]]

^<<v42-3-13,13>>^ Respondeu-lhes ele: Não cobreis além daquilo que vos foi prescrito.

[[v42-3-14]]

^<<v42-3-14,14>>^ Interrogaram-no também uns soldados: E nós, que faremos? Disse-lhes: A ninguém queirais extorquir coisa alguma; nem deis denúncia falsa; e contentai-vos com o vosso soldo.

[[v42-3-15]]

^<<v42-3-15,15>>^ Ora, estando o povo em expectativa e arrazoando todos em seus corações a respeito de João, se porventura seria ele o Cristo,

[[v42-3-16]]

^<<v42-3-16,16>>^ respondeu João a todos, dizendo: Eu, na verdade, vos batizo em água, mas vem aquele que é mais poderoso do que eu, de quem não sou digno de desatar a correia das alparcas; ele vos batizará no Espírito Santo e em fogo.

[[v42-3-17]]

^<<v42-3-17,17>>^ A sua pá ele tem na mão para limpar bem a sua eira, e recolher o trigo ao seu celeiro; mas queimará a palha em fogo inextinguível.

[[v42-3-18]]

^<<v42-3-18,18>>^ Assim pois, com muitas outras exortações ainda, anunciava o evangelho ao povo.

[[v42-3-19]]

^<<v42-3-19,19>>^ Mas o tetrarca Herodes, sendo repreendido por ele por causa de Herodias, mulher de seu irmão, e por todas as maldades que havia feito,

[[v42-3-20]]

^<<v42-3-20,20>>^ acrescentou a todas elas ainda esta, a de encerrar João no cárcere.

[[v42-3-21]]

^<<v42-3-21,21>>^ Quando todo o povo fora batizado, tendo sido Jesus também batizado, e estando ele a orar, o céu se abriu;

[[v42-3-22]]

^<<v42-3-22,22>>^ e o Espírito Santo desceu sobre ele em forma corpórea, como uma pomba; e ouviu-se do céu esta voz: Tu és o meu Filho amado; em ti me comprazo.

[[v42-3-23]]

^<<v42-3-23,23>>^ Ora, Jesus, ao começar o seu ministério, tinha cerca de trinta anos; sendo &#123;como se cuidava&#125; filho de José, filho de Eli;

[[v42-3-24]]

^<<v42-3-24,24>>^ Eli de Matate, Matate de Levi, Levi de Melqui, Melqui de Janai, Janai de José,

[[v42-3-25]]

^<<v42-3-25,25>>^ José de Matatias, Matatias de Amós, Amós de Naum, Naum de Esli, Esli de Nagai,

[[v42-3-26]]

^<<v42-3-26,26>>^ Nagai de Maate, Maate de Matatias, Matatias de Semei, Semei de Joseque, Joseque de Jodá,

[[v42-3-27]]

^<<v42-3-27,27>>^ Jodá de Joanã, Joanã de Resa, Resa de Zorobabel, Zorobabel de Salatiel, Salatiel de Neri,

[[v42-3-28]]

^<<v42-3-28,28>>^ Neri de Melqui, Melqui de Adi, Adi de Cosão, Cosão de Elmodã, Elmodão de Er,

[[v42-3-29]]

^<<v42-3-29,29>>^ Er de Josué, Josué de Eliézer, Eliézer de Jorim, Jorim de Matate, Matate de Levi,

[[v42-3-30]]

^<<v42-3-30,30>>^ Levi de Simeão, Simeão de Judá, Judá de José, José de Jonã, Jonã de Eliaquim,

[[v42-3-31]]

^<<v42-3-31,31>>^ Eliaquim de Meleá, Meleá de Mená, Mená de Matatá, Matatá de Natã, Natã de Davi,

[[v42-3-32]]

^<<v42-3-32,32>>^ Davi de Jessé, Jessé de Obede, Obede de Boaz, Boaz de Salá, Salá de Nasom,

[[v42-3-33]]

^<<v42-3-33,33>>^ Nasom de Aminadabe, Aminadabe de Admim, Admim de Arni, Arni de Esrom, Esrom de Farés, Farés de Judá,

[[v42-3-34]]

^<<v42-3-34,34>>^ Judá de Jacó, Jacó de Isaque, Isaque de Abraão, Abraão de Tará, Tará de Naor,

[[v42-3-35]]

^<<v42-3-35,35>>^ Naor de Seruque, Seruque de Ragaú, Ragaú de Faleque, Faleque de Eber, Eber de Salá,

[[v42-3-36]]

^<<v42-3-36,36>>^ Salá de Cainã, Cainã de Arfaxade, Arfaxade de Sem, Sem de Noé, Noé de Lameque,

[[v42-3-37]]

^<<v42-3-37,37>>^ Lameque de Matusalém, Matusalém de Enoque, Enoque de Jarede, Jarede de Maleleel, Maleleel de Cainã,

[[v42-3-38]]

^<<v42-3-38,38>>^ Cainã de Enos, Enos de Sete, Sete de Adão, e Adão de Deus.

'''

xref:042-lucas/042-lucas-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-lucas/042-lucas-004.adoc#v42-4-0[Próximo Capítulo &#62;]