include::./index.adoc[]

[[v42-2-0]]
=== Lucas, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-2-1]]

^<<v42-2-1,1>>^ Naqueles dias saiu um decreto da parte de César Augusto, para que todo o mundo fosse recenseado.

[[v42-2-2]]

^<<v42-2-2,2>>^ Este primeiro recenseamento foi feito quando Quirínio era governador da Síria.

[[v42-2-3]]

^<<v42-2-3,3>>^ E todos iam alistar-se, cada um à sua própria cidade.

[[v42-2-4]]

^<<v42-2-4,4>>^ Subiu também José, da Galiléia, da cidade de Nazaré, à cidade de Davi, chamada Belém, porque era da casa e família de Davi,

[[v42-2-5]]

^<<v42-2-5,5>>^ a fim de alistar-se com Maria, sua esposa, que estava grávida.

[[v42-2-6]]

^<<v42-2-6,6>>^ Enquanto estavam ali, chegou o tempo em que ela havia de dar à luz,

[[v42-2-7]]

^<<v42-2-7,7>>^ e teve a seu filho primogênito; envolveu-o em faixas e o deitou em uma manjedoura, porque não havia lugar para eles na estalagem.

[[v42-2-8]]

^<<v42-2-8,8>>^ Ora, havia naquela mesma região pastores que estavam no campo, e guardavam durante as vigílias da noite o seu rebanho.

[[v42-2-9]]

^<<v42-2-9,9>>^ E um anjo do Senhor apareceu-lhes, e a glória do Senhor os cercou de resplendor; pelo que se encheram de grande temor.

[[v42-2-10]]

^<<v42-2-10,10>>^ O anjo, porém, lhes disse: Não temais, porquanto vos trago novas de grande alegria que o será para todo o povo:

[[v42-2-11]]

^<<v42-2-11,11>>^ É que vos nasceu hoje, na cidade de Davi, o Salvador, que é Cristo, o Senhor.

[[v42-2-12]]

^<<v42-2-12,12>>^ E isto vos será por sinal: Achareis um menino envolto em faixas, e deitado em uma manjedoura.

[[v42-2-13]]

^<<v42-2-13,13>>^ Então, de repente, apareceu junto ao anjo grande multidão da milícia celestial, louvando a Deus e dizendo:

[[v42-2-14]]

^<<v42-2-14,14>>^ Glória a Deus nas maiores alturas, e paz na terra entre os homens de boa vontade.

[[v42-2-15]]

^<<v42-2-15,15>>^ E logo que os anjos se retiraram deles para o céu, diziam os pastores uns aos outros: Vamos já até Belém, e vejamos isso que aconteceu e que o Senhor nos deu a conhecer.

[[v42-2-16]]

^<<v42-2-16,16>>^ Foram, pois, a toda a pressa, e acharam Maria e José, e o menino deitado na manjedoura;

[[v42-2-17]]

^<<v42-2-17,17>>^ e, vendo-o, divulgaram a palavra que acerca do menino lhes fora dita;

[[v42-2-18]]

^<<v42-2-18,18>>^ e todos os que a ouviram se admiravam do que os pastores lhes diziam.

[[v42-2-19]]

^<<v42-2-19,19>>^ Maria, porém, guardava todas estas coisas, meditando-as em seu coração.

[[v42-2-20]]

^<<v42-2-20,20>>^ E voltaram os pastores, glorificando e louvando a Deus por tudo o que tinham ouvido e visto, como lhes fora dito.

[[v42-2-21]]

^<<v42-2-21,21>>^ Quando se completaram os oito dias para ser circuncidado o menino, foi-lhe dado o nome de Jesus, que pelo anjo lhe fora posto antes de ser concebido.

[[v42-2-22]]

^<<v42-2-22,22>>^ Terminados os dias da purificação, segundo a lei de Moisés, levaram-no a Jerusalém, para apresentá-lo ao Senhor

[[v42-2-23]]

^<<v42-2-23,23>>^ &#123;conforme está escrito na lei do Senhor: Todo primogênito será consagrado ao Senhor&#125;,

[[v42-2-24]]

^<<v42-2-24,24>>^ e para oferecerem um sacrifício segundo o disposto na lei do Senhor: um par de rolas, ou dois pombinhos.

[[v42-2-25]]

^<<v42-2-25,25>>^ Ora, havia em Jerusalém um homem cujo nome era Simeão; e este homem, justo e temente a Deus, esperava a consolação de Israel; e o Espírito Santo estava sobre ele.

[[v42-2-26]]

^<<v42-2-26,26>>^ E lhe fora revelado pelo Espírito Santo que ele não morreria antes de ver o Cristo do Senhor.

[[v42-2-27]]

^<<v42-2-27,27>>^ Assim pelo Espírito foi ao templo; e quando os pais trouxeram o menino Jesus, para fazerem por ele segundo o costume da lei,

[[v42-2-28]]

^<<v42-2-28,28>>^ Simeão o tomou em seus braços, e louvou a Deus, e disse:

[[v42-2-29]]

^<<v42-2-29,29>>^ Agora, Senhor, despedes em paz o teu servo, segundo a tua palavra;

[[v42-2-30]]

^<<v42-2-30,30>>^ pois os meus olhos já viram a tua salvação,

[[v42-2-31]]

^<<v42-2-31,31>>^ a qual tu preparaste ante a face de todos os povos;

[[v42-2-32]]

^<<v42-2-32,32>>^ luz para revelação aos gentios, e para glória do teu povo Israel.

[[v42-2-33]]

^<<v42-2-33,33>>^ Enquanto isso, seu pai e sua mãe se admiravam das coisas que deles se diziam.

[[v42-2-34]]

^<<v42-2-34,34>>^ E Simeão os abençoou, e disse a Maria, mãe do menino: Eis que este é posto para queda e para levantamento de muitos em Israel, e para ser alvo de contradição,

[[v42-2-35]]

^<<v42-2-35,35>>^ sim, e uma espada traspassará a tua própria alma, para que se manifestem os pensamentos de muitos corações.

[[v42-2-36]]

^<<v42-2-36,36>>^ Havia também uma profetisa, Ana, filha de Fanuel, da tribo de Aser. Era já avançada em idade, tendo vivido com o marido sete anos desde a sua virgindade;

[[v42-2-37]]

^<<v42-2-37,37>>^ e era viúva, de quase oitenta e quatro anos. Não se afastava do templo, servindo a Deus noite e dia em jejuns e orações.

[[v42-2-38]]

^<<v42-2-38,38>>^ Chegando ela na mesma hora, deu graças a Deus, e falou a respeito do menino a todos os que esperavam a redenção de Jerusalém.

[[v42-2-39]]

^<<v42-2-39,39>>^ Assim que cumpriram tudo segundo a lei do Senhor, voltaram à Galiléia, para sua cidade de Nazaré.

[[v42-2-40]]

^<<v42-2-40,40>>^ E o menino ia crescendo e fortalecendo-se, ficando cheio de sabedoria; e a graça de Deus estava sobre ele.

[[v42-2-41]]

^<<v42-2-41,41>>^ Ora, seus pais iam todos os anos a Jerusalém, à festa da páscoa.

[[v42-2-42]]

^<<v42-2-42,42>>^ Quando Jesus completou doze anos, subiram eles segundo o costume da festa;

[[v42-2-43]]

^<<v42-2-43,43>>^ e, terminados aqueles dias, ao regressarem, ficou o menino Jesus em Jerusalém sem o saberem seus pais;

[[v42-2-44]]

^<<v42-2-44,44>>^ julgando, porém, que estivesse entre os companheiros de viagem, andaram caminho de um dia, e o procuravam entre os parentes e conhecidos;

[[v42-2-45]]

^<<v42-2-45,45>>^ e não o achando, voltaram a Jerusalém em busca dele.

[[v42-2-46]]

^<<v42-2-46,46>>^ E aconteceu que, passados três dias, o acharam no templo, sentado no meio dos doutores, ouvindo-os, e interrogando-os.

[[v42-2-47]]

^<<v42-2-47,47>>^ E todos os que o ouviam se admiravam da sua inteligência e das suas respostas.

[[v42-2-48]]

^<<v42-2-48,48>>^ Quando o viram, ficaram maravilhados, e disse-lhe sua mãe: Filho, por que procedeste assim para conosco? Eis que teu pai e eu ansiosos te procurávamos.

[[v42-2-49]]

^<<v42-2-49,49>>^ Respondeu-lhes ele: Por que me procuráveis? Não sabíeis que eu devia estar na casa de meu Pai?

[[v42-2-50]]

^<<v42-2-50,50>>^ Eles, porém, não entenderam as palavras que lhes dissera.

[[v42-2-51]]

^<<v42-2-51,51>>^ Então, descendo com eles, foi para Nazaré, e era-lhes sujeito. E sua mãe guardava todas estas coisas em seu coração.

[[v42-2-52]]

^<<v42-2-52,52>>^ E crescia Jesus em sabedoria, em estatura e em graça diante de Deus e dos homens.

'''

xref:042-lucas/042-lucas-001.adoc#v42-1-0[&#60; Capítulo Anterior] | <<v42-2-0,Topo>> | xref:042-lucas/042-lucas-003.adoc#v42-3-0[Próximo Capítulo &#62;]