include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v42-22-1]]

^<<v42-22-1,1>>^ Aproximava-se a festa dos pães ázimos, que se chama a páscoa.

[[v42-22-2]]

^<<v42-22-2,2>>^ E os principais sacerdotes e os escribas andavam procurando um modo de o matar; pois temiam o povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Entrou então Satanás em Judas, que tinha por sobrenome Iscariotes, que era um dos doze;

[[v42-22-4]]

^<<v42-22-4,4>>^ e foi ele tratar com os principais sacerdotes e com os capitães de como lho entregaria.

[[v42-22-5]]

^<<v42-22-5,5>>^ Eles se alegraram com isso, e convieram em lhe dar dinheiro.

[[v42-22-6]]

^<<v42-22-6,6>>^ E ele concordou, e buscava ocasião para lho entregar sem alvoroço.

[[v42-22-7]]

^<<v42-22-7,7>>^ Ora, chegou o dia dos pães ázimos, em que se devia imolar a páscoa;

[[v42-22-8]]

^<<v42-22-8,8>>^ e Jesus enviou a Pedro e a João, dizendo: Ide, preparai-nos a páscoa, para que a comamos.

[[v42-22-9]]

^<<v42-22-9,9>>^ Perguntaram-lhe eles: Onde queres que a preparemos?

[[v42-22-10]]

^<<v42-22-10,10>>^ Respondeu-lhes: Quando entrardes na cidade, sair-vos-á ao encontro um homem, levando um cântaro de água; segui-o até a casa em que ele entrar.

[[v42-22-11]]

^<<v42-22-11,11>>^ E direis ao dono da casa: O Mestre manda perguntar-te: Onde está o aposento em que hei de comer a páscoa com os meus discípulos?

[[v42-22-12]]

^<<v42-22-12,12>>^ Então ele vos mostrará um grande cenáculo mobiliado; aí fazei os preparativos.

[[v42-22-13]]

^<<v42-22-13,13>>^ Foram, pois, e acharam tudo como lhes dissera e prepararam a páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ E, chegada a hora, pôs-se Jesus à mesa, e com ele os apóstolos.

[[v42-22-15]]

^<<v42-22-15,15>>^ E disse-lhes: Tenho desejado ardentemente comer convosco esta páscoa, antes da minha paixão;

[[v42-22-16]]

^<<v42-22-16,16>>^ pois vos digo que não a comerei mais até que ela se cumpra no reino de Deus.

[[v42-22-17]]

^<<v42-22-17,17>>^ Então havendo recebido um cálice, e tendo dado graças, disse: Tomai-o, e reparti-o entre vós;

[[v42-22-18]]

^<<v42-22-18,18>>^ porque vos digo que desde agora não mais beberei do fruto da videira, até que venha o reino de Deus.

[[v42-22-19]]

^<<v42-22-19,19>>^ E tomando pão, e havendo dado graças, partiu-o e deu-lho, dizendo: Isto é o meu corpo, que é dado por vós; fazei isto em memória de mim.

[[v42-22-20]]

^<<v42-22-20,20>>^ Semelhantemente, depois da ceia, tomou o cálice, dizendo: Este cálice é o novo pacto em meu sangue, que é derramado por vós.

[[v42-22-21]]

^<<v42-22-21,21>>^ Mas eis que a mão do que me trai está comigo à mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ Porque, na verdade, o Filho do homem vai segundo o que está determinado; mas ai daquele homem por quem é traído!

[[v42-22-23]]

^<<v42-22-23,23>>^ Então eles começaram a perguntar entre si qual deles o que ia fazer isso.

[[v42-22-24]]

^<<v42-22-24,24>>^ Levantou-se também entre eles contenda, sobre qual deles parecia ser o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ Ao que Jesus lhes disse: Os reis dos gentios dominam sobre eles, e os que sobre eles exercem autoridade são chamados benfeitores.

[[v42-22-26]]

^<<v42-22-26,26>>^ Mas vós não sereis assim; antes o maior entre vós seja como o mais novo; e quem governa como quem serve.

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois qual é maior, quem está à mesa, ou quem serve? porventura não é quem está à mesa? Eu, porém, estou entre vós como quem serve.

[[v42-22-28]]

^<<v42-22-28,28>>^ Mas vós sois os que tendes permanecido comigo nas minhas provações;

[[v42-22-29]]

^<<v42-22-29,29>>^ e assim como meu Pai me conferiu domínio, eu vo-lo confiro a vós;

[[v42-22-30]]

^<<v42-22-30,30>>^ para que comais e bebais à minha mesa no meu reino, e vos senteis sobre tronos, julgando as doze tribos de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ Simão, Simão, eis que Satanás vos pediu para vos cirandar como trigo;

[[v42-22-32]]

^<<v42-22-32,32>>^ mas eu roguei por ti, para que a tua fé não desfaleça; e tu, quando te converteres, fortalece teus irmãos.

[[v42-22-33]]

^<<v42-22-33,33>>^ Respondeu-lhe Pedro: Senhor, estou pronto a ir contigo tanto para a prisão como para a morte.

[[v42-22-34]]

^<<v42-22-34,34>>^ Tornou-lhe Jesus: Digo-te, Pedro, que não cantará hoje o galo antes que três vezes tenhas negado que me conheces.

[[v42-22-35]]

^<<v42-22-35,35>>^ E perguntou-lhes: Quando vos mandei sem bolsa, alforje, ou alparcas, faltou-vos porventura alguma coisa? Eles responderam: Nada.

[[v42-22-36]]

^<<v42-22-36,36>>^ Disse-lhes pois: Mas agora, quem tiver bolsa, tome-a, como também o alforje; e quem não tiver espada, venda o seu manto e compre-a.

[[v42-22-37]]

^<<v42-22-37,37>>^ Porquanto vos digo que importa que se cumpra em mim isto que está escrito: E com os malfeitores foi contado. Pois o que me diz respeito tem seu cumprimento.

[[v42-22-38]]

^<<v42-22-38,38>>^ Disseram eles: Senhor, eis aqui duas espadas. Respondeu-lhes: Basta.

[[v42-22-39]]

^<<v42-22-39,39>>^ Então saiu e, segundo o seu costume, foi para o Monte das Oliveiras; e os discípulos o seguiam.

[[v42-22-40]]

^<<v42-22-40,40>>^ Quando chegou àquele lugar, disse-lhes: Orai, para que não entreis em tentação.

[[v42-22-41]]

^<<v42-22-41,41>>^ E apartou-se deles cerca de um tiro de pedra; e pondo-se de joelhos, orava,

[[v42-22-42]]

^<<v42-22-42,42>>^ dizendo: Pai, se queres afasta de mim este cálice; todavia não se faça a minha vontade, mas a tua.

[[v42-22-43]]

^<<v42-22-43,43>>^ Então lhe apareceu um anjo do céu, que o confortava.

[[v42-22-44]]

^<<v42-22-44,44>>^ E, posto em agonia, orava mais intensamente; e o seu suor tornou-se como grandes gotas de sangue, que caíam sobre o chão.

[[v42-22-45]]

^<<v42-22-45,45>>^ Depois, levantando-se da oração, veio para os seus discípulos, e achou-os dormindo de tristeza;

[[v42-22-46]]

^<<v42-22-46,46>>^ e disse-lhes: Por que estais dormindo? Lenvantai-vos, e orai, para que não entreis em tentação.

[[v42-22-47]]

^<<v42-22-47,47>>^ E estando ele ainda a falar, eis que surgiu uma multidão; e aquele que se chamava Judas, um dos doze, ia adiante dela, e chegou-se a Jesus para o beijar.

[[v42-22-48]]

^<<v42-22-48,48>>^ Jesus, porém, lhe disse: Judas, com um beijo trais o Filho do homem?

[[v42-22-49]]

^<<v42-22-49,49>>^ Quando os que estavam com ele viram o que ia suceder, disseram: Senhor, feri-los-emos a espada?

[[v42-22-50]]

^<<v42-22-50,50>>^ Então um deles feriu o servo do sumo sacerdote, e cortou-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus disse: Deixei-os; basta. E tocando-lhe a orelha, o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ Então disse Jesus aos principais sacerdotes, oficiais do templo e anciãos, que tinham ido contra ele: Saístes, como a um salteador, com espadas e varapaus?

[[v42-22-53]]

^<<v42-22-53,53>>^ Todos os dias estava eu convosco no templo, e não estendestes as mãos contra mim; mas esta é a vossa hora e o poder das trevas.

[[v42-22-54]]

^<<v42-22-54,54>>^ Então, prendendo-o, o levaram e o introduziram na casa do sumo sacerdote; e Pedro seguia-o de longe.

[[v42-22-55]]

^<<v42-22-55,55>>^ E tendo eles acendido fogo no meio do pátio e havendo-se sentado à roda, sentou-se Pedro entre eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ 

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas Pedro o negou, dizendo: Mulher, não o conheço.

[[v42-22-58]]

^<<v42-22-58,58>>^ Daí a pouco, outro o viu, e disse: Tu também és um deles. Mas Pedro disse: Homem, não sou.

[[v42-22-59]]

^<<v42-22-59,59>>^ E, tendo passado quase uma hora, outro afirmava, dizendo: Certamente este também estava com ele, pois é galileu.

[[v42-22-60]]

^<<v42-22-60,60>>^ Mas Pedro respondeu: Homem, não sei o que dizes. E imediatamente estando ele ainda a falar, cantou o galo.

[[v42-22-61]]

^<<v42-22-61,61>>^ Virando-se o Senhor, olhou para Pedro; e Pedro lembrou-se da palavra do Senhor, como lhe havia dito: Hoje, antes que o galo cante, três vezes me negarás.

[[v42-22-62]]

^<<v42-22-62,62>>^ E, havendo saído, chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os homens que detinham Jesus zombavam dele, e feriam-no;

[[v42-22-64]]

^<<v42-22-64,64>>^ e, vendando-lhe os olhos, perguntavam, dizendo: Profetiza, quem foi que te bateu?

[[v42-22-65]]

^<<v42-22-65,65>>^ E, blasfemando, diziam muitas outras coisas contra ele.

[[v42-22-66]]

^<<v42-22-66,66>>^ Logo que amanheceu reuniu-se a assembléia dos anciãos do povo, tanto os principais sacerdotes como os escribas, e o conduziam ao sinédrio deles, onde lhe disseram:

[[v42-22-67]]

^<<v42-22-67,67>>^ Se tu és o Cristo, dize-no-lo. Replicou-lhes ele: Se eu vo-lo disser, não o crereis;

[[v42-22-68]]

^<<v42-22-68,68>>^ e se eu vos interrogar, de modo algum me respondereis.

[[v42-22-69]]

^<<v42-22-69,69>>^ Mas desde agora estará assentado o Filho do homem à mão direita do poder de Deus.

[[v42-22-70]]

^<<v42-22-70,70>>^ Ao que perguntaram todos: Logo, tu és o Filho de Deus? Respondeu-lhes: Vós dizeis que eu sou.

[[v42-22-71]]

^<<v42-22-71,71>>^ Então disseram: Por que ainda temos necessidade de testemunho? pois nós mesmos o ouvimos da sua própria boca.

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]