include::./index.adoc[]

[[v20-23-0]]
=== Provérbios, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-23-1]]

^<<v20-23-1,1>>^ Quando te assentares a comer com um governador, atenta bem para aquele que está diante de ti;

[[v20-23-2]]

^<<v20-23-2,2>>^ e põe uma faca à tua garganta, se fores homem de grande apetite.

[[v20-23-3]]

^<<v20-23-3,3>>^ Não cobices os seus manjares gostosos, porque é comida enganadora.

[[v20-23-4]]

^<<v20-23-4,4>>^ Não te fatigues para seres rico; dá de mão à tua própria sabedoria:

[[v20-23-5]]

^<<v20-23-5,5>>^ Fitando tu os olhos nas riquezas, elas se vão; pois fazem para si asas, como a águia, voam para o céu.

[[v20-23-6]]

^<<v20-23-6,6>>^ Não comas o pão do avarento, nem cobices os seus manjares gostosos.

[[v20-23-7]]

^<<v20-23-7,7>>^ Porque, como ele pensa consigo mesmo, assim é; ele te diz: Come e bebe; mas o seu coração não está contigo.

[[v20-23-8]]

^<<v20-23-8,8>>^ Vomitarás o bocado que comeste, e perderás as tuas suaves palavras.

[[v20-23-9]]

^<<v20-23-9,9>>^ Não fales aos ouvidos do tolo; porque desprezará a sabedoria das tuas palavras.

[[v20-23-10]]

^<<v20-23-10,10>>^ Não removas os limites antigos; nem entres nos campos dos órfãos,

[[v20-23-11]]

^<<v20-23-11,11>>^ porque o seu redentor é forte; ele lhes pleiteará a causa contra ti.

[[v20-23-12]]

^<<v20-23-12,12>>^ Aplica o teu coração à instrução, e os teus ouvidos às palavras do conhecimento.

[[v20-23-13]]

^<<v20-23-13,13>>^ Não retires da criança a disciplina; porque, fustigando-a tu com a vara, nem por isso morrerá.

[[v20-23-14]]

^<<v20-23-14,14>>^ Tu a fustigarás com a vara e livrarás a sua alma do Seol.

[[v20-23-15]]

^<<v20-23-15,15>>^ Filho meu, se o teu coração for sábio, alegrar-se-á o meu coração, sim, ó, meu próprio;

[[v20-23-16]]

^<<v20-23-16,16>>^ e exultará o meu coração, quando os teus lábios falarem coisas retas.

[[v20-23-17]]

^<<v20-23-17,17>>^ Não tenhas inveja dos pecadores; antes conserva-te no temor do Senhor todo o dia.

[[v20-23-18]]

^<<v20-23-18,18>>^ Porque deveras terás uma recompensa; não será malograda a tua esperança.

[[v20-23-19]]

^<<v20-23-19,19>>^ Ouve tu, filho meu, e sê sábio; e dirige no caminho o teu coração.

[[v20-23-20]]

^<<v20-23-20,20>>^ Não estejas entre os beberrões de vinho, nem entre os comilões de carne.

[[v20-23-21]]

^<<v20-23-21,21>>^ Porque o beberrão e o comilão caem em pobreza; e a sonolência cobrirá de trapos o homem.

[[v20-23-22]]

^<<v20-23-22,22>>^ Ouve a teu pai, que te gerou; e não desprezes a tua mãe, quando ela envelhecer.

[[v20-23-23]]

^<<v20-23-23,23>>^ Compra a verdade, e não a vendas; sim, a sabedoria, a disciplina, e o entendimento.

[[v20-23-24]]

^<<v20-23-24,24>>^ Grandemente se regozijará o pai do justo; e quem gerar um filho sábio, nele se alegrará.

[[v20-23-25]]

^<<v20-23-25,25>>^ Alegrem-se teu pai e tua mãe, e regozije-se aquela que te deu à luz.

[[v20-23-26]]

^<<v20-23-26,26>>^ Filho meu, dá-me o teu coração; e deleitem-se os teus olhos nos meus caminhos.

[[v20-23-27]]

^<<v20-23-27,27>>^ Porque cova profunda é a prostituta; e poço estreito é a aventureira.

[[v20-23-28]]

^<<v20-23-28,28>>^ Também ela, como o salteador, se põe a espreitar; e multiplica entre os homens os prevaricadores.

[[v20-23-29]]

^<<v20-23-29,29>>^ Para quem são os ais? para quem os pesares? para quem as pelejas, para quem as queixas? para quem as feridas sem causa? e para quem os olhos vermelhos?

[[v20-23-30]]

^<<v20-23-30,30>>^ Para os que se demoram perto do vinho, para os que andam buscando bebida misturada.

[[v20-23-31]]

^<<v20-23-31,31>>^ Não olhes para o vinho quando se mostra vermelho, quando resplandece no copo e se escoa suavemente.

[[v20-23-32]]

^<<v20-23-32,32>>^ No seu fim morderá como a cobra, e como o basilisco picará.

[[v20-23-33]]

^<<v20-23-33,33>>^ Os teus olhos verão coisas estranhas, e tu falarás perversidades.

[[v20-23-34]]

^<<v20-23-34,34>>^ o serás como o que se deita no meio do mar, e como o que dorme no topo do mastro.

[[v20-23-35]]

^<<v20-23-35,35>>^ E dirás: Espancaram-me, e não me doeu; bateram-me, e não o senti; quando virei a despertar? ainda tornarei a buscá-lo outra vez.

'''

xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[&#60; Capítulo Anterior] | <<v20-23-0,Topo>> | xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[Próximo Capítulo &#62;]