include::./index.adoc[]

[[v20-30-0]]
=== Provérbios, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-30-1]]

^<<v20-30-1,1>>^ Palavras de Agur, filho de Jaqué de Massá. Diz o homem a Itiel, e a Ucal:

[[v20-30-2]]

^<<v20-30-2,2>>^ Na verdade que eu sou mais estúpido do que ninguém; não tenho o entendimento do homem;

[[v20-30-3]]

^<<v20-30-3,3>>^ não aprendi a sabedoria, nem tenho o conhecimento do Santo.

[[v20-30-4]]

^<<v20-30-4,4>>^ Quem subiu ao céu e desceu? quem encerrou os ventos nos seus punhos? mas amarrou as águas no seu manto? quem estabeleceu todas as extremidades da terra? qual é o seu nome, e qual é o nome de seu filho? Certamente o sabes!

[[v20-30-5]]

^<<v20-30-5,5>>^ Toda palavra de Deus é pura; ele é um escudo para os que nele confiam.

[[v20-30-6]]

^<<v20-30-6,6>>^ Nada acrescentes às suas palavras, para que ele não te repreenda e tu sejas achado mentiroso.

[[v20-30-7]]

^<<v20-30-7,7>>^ Duas coisas te peço; não mas negues, antes que morra:

[[v20-30-8]]

^<<v20-30-8,8>>^ Alonga de mim a falsidade e a mentira; não me dês nem a pobreza nem a riqueza: dá-me só o pão que me é necessário;

[[v20-30-9]]

^<<v20-30-9,9>>^ para que eu de farto não te negue, e diga: Quem é o Senhor? ou, empobrecendo, não venha a furtar, e profane o nome de Deus.

[[v20-30-10]]

^<<v20-30-10,10>>^ Não calunies o servo diante de seu senhor, para que ele não te amaldiçoe e fiques tu culpado.

[[v20-30-11]]

^<<v20-30-11,11>>^ Há gente que amaldiçoa a seu pai, e que não bendiz a sua mãe.

[[v20-30-12]]

^<<v20-30-12,12>>^ Há gente que é pura aos seus olhos, e contudo nunca foi lavada da sua imundícia.

[[v20-30-13]]

^<<v20-30-13,13>>^ Há gente cujos olhos são altivos, e cujas pálpebras são levantadas para cima.

[[v20-30-14]]

^<<v20-30-14,14>>^ Há gente cujos dentes são como espadas; e cujos queixais são como facas, para devorarem da terra os aflitos, e os necessitados dentre os homens.

[[v20-30-15]]

^<<v20-30-15,15>>^ A sanguessuga tem duas filhas, a saber: Dá, Dá. Há três coisas que nunca se fartam; sim, quatro que nunca dizem: Basta;

[[v20-30-16]]

^<<v20-30-16,16>>^ o Seol, a madre estéril, a terra que não se farta d'água, e o fogo que nunca diz: Basta.

[[v20-30-17]]

^<<v20-30-17,17>>^ Os olhos que zombam do pai, ou desprezam a obediência à mãe, serão arrancados pelos corvos do vale e devorados pelos filhos da águia.

[[v20-30-18]]

^<<v20-30-18,18>>^ Há três coisas que são maravilhosas demais para mim, sim, há quatro que não conheço:

[[v20-30-19]]

^<<v20-30-19,19>>^ o caminho da águia no ar, o caminho da cobra na penha, o caminho do navio no meio do mar, e o caminho do homem com uma virgem.

[[v20-30-20]]

^<<v20-30-20,20>>^ Tal é o caminho da mulher adúltera: ela come, e limpa a sua boca, e diz: não pratiquei iniqüidade.

[[v20-30-21]]

^<<v20-30-21,21>>^ Por três coisas estremece a terra, sim, há quatro que não pode suportar:

[[v20-30-22]]

^<<v20-30-22,22>>^ o escravo quando reina; o tolo quando se farta de comer;

[[v20-30-23]]

^<<v20-30-23,23>>^ a mulher desdenhada quando se casa; e a serva quando fica herdeira da sua senhora.

[[v20-30-24]]

^<<v20-30-24,24>>^ Quatro coisas há na terra que são pequenas, entretanto são extremamente sábias;

[[v20-30-25]]

^<<v20-30-25,25>>^ as formigas são um povo sem força, todavia no verão preparam a sua comida;

[[v20-30-26]]

^<<v20-30-26,26>>^ os querogrilos são um povo débil, contudo fazem a sua casa nas rochas;

[[v20-30-27]]

^<<v20-30-27,27>>^ os gafanhotos não têm rei, contudo marcham todos enfileirados;

[[v20-30-28]]

^<<v20-30-28,28>>^ a lagartixa apanha-se com as mãos, contudo anda nos palácios dos reis.

[[v20-30-29]]

^<<v20-30-29,29>>^ Há três que andam com elegância, sim, quatro que se movem airosamente:

[[v20-30-30]]

^<<v20-30-30,30>>^ o leão, que é o mais forte entre os animais, e que não se desvia diante de ninguém;

[[v20-30-31]]

^<<v20-30-31,31>>^ o galo emproado, o bode, e o rei à frente do seu povo.

[[v20-30-32]]

^<<v20-30-32,32>>^ Se procedeste loucamente em te elevares, ou se maquinaste o mal, põe a mão sobre a boca.

[[v20-30-33]]

^<<v20-30-33,33>>^ Como o espremer do leite produz queijo verde, e o espremer do nariz produz sangue, assim o espremer da ira produz contenda.

'''

xref:020-proverbios/020-proverbios-029.adoc#v20-29-0[&#60; Capítulo Anterior] | <<v20-30-0,Topo>> | xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[Próximo Capítulo &#62;]