include::./index.adoc[]

[[v20-21-0]]
=== Provérbios, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-21-1]]

^<<v20-21-1,1>>^ Como corrente de águas é o coração do rei na mão do Senhor; ele o inclina para onde quer.

[[v20-21-2]]

^<<v20-21-2,2>>^ Todo caminho do homem é reto aos seus olhos; mas o Senhor pesa os corações.

[[v20-21-3]]

^<<v20-21-3,3>>^ Fazer justiça e julgar com retidão é mais aceitável ao Senhor do que oferecer-lhe sacrifício.

[[v20-21-4]]

^<<v20-21-4,4>>^ Olhar altivo e coração orgulhoso, tal lâmpada dos ímpios é pecado.

[[v20-21-5]]

^<<v20-21-5,5>>^ Os planos do diligente conduzem à abundância; mas todo precipitado apressa-se para a penúria.

[[v20-21-6]]

^<<v20-21-6,6>>^ Ajuntar tesouros com língua falsa é uma vaidade fugitiva; aqueles que os buscam, buscam a morte.

[[v20-21-7]]

^<<v20-21-7,7>>^ A violência dos ímpios arrebatá-los-á, porquanto recusam praticar a justiça.

[[v20-21-8]]

^<<v20-21-8,8>>^ O caminho do homem perverso é tortuoso; mas o proceder do puro é reto.

[[v20-21-9]]

^<<v20-21-9,9>>^ Melhor é morar num canto do eirado, do que com a mulher rixosa numa casa ampla.

[[v20-21-10]]

^<<v20-21-10,10>>^ A alma do ímpio deseja o mal; o seu próximo não agrada aos seus olhos.

[[v20-21-11]]

^<<v20-21-11,11>>^ Quando o escarnecedor é castigado, o simples torna-se sábio; e, quando o sábio é instruído, recebe o conhecimento.

[[v20-21-12]]

^<<v20-21-12,12>>^ O justo observa a casa do ímpio; precipitam-se os ímpios na ruína.

[[v20-21-13]]

^<<v20-21-13,13>>^ Quem tapa o seu ouvido ao clamor do pobre, também clamará e não será ouvido.

[[v20-21-14]]

^<<v20-21-14,14>>^ O presente que se dá em segredo aplaca a ira; e a dádiva às escondidas, a forte indignação.

[[v20-21-15]]

^<<v20-21-15,15>>^ A execução da justiça é motivo de alegria para o justo; mas é espanto para os que praticam a iniqüidade.

[[v20-21-16]]

^<<v20-21-16,16>>^ O homem que anda desviado do caminho do entendimento repousará na congregação dos mortos.

[[v20-21-17]]

^<<v20-21-17,17>>^ Quem ama os prazeres empobrecerá; quem ama o vinho e o azeite nunca enriquecera.

[[v20-21-18]]

^<<v20-21-18,18>>^ Resgate para o justo é o ímpio; e em lugar do reto ficará o prevaricador.

[[v20-21-19]]

^<<v20-21-19,19>>^ Melhor é morar numa terra deserta do que com a mulher rixosa e iracunda.

[[v20-21-20]]

^<<v20-21-20,20>>^ Há tesouro precioso e azeite na casa do sábio; mas o homem insensato os devora.

[[v20-21-21]]

^<<v20-21-21,21>>^ Aquele que segue a justiça e a bondade achará a vida, a justiça e a honra.

[[v20-21-22]]

^<<v20-21-22,22>>^ O sábio escala a cidade dos valentes, e derriba a fortaleza em que ela confia.

[[v20-21-23]]

^<<v20-21-23,23>>^ O que guarda a sua boca e a sua língua, guarda das angústias a sua alma.

[[v20-21-24]]

^<<v20-21-24,24>>^ Quanto ao soberbo e presumido, zombador é seu nome; ele procede com insolente orgulho.

[[v20-21-25]]

^<<v20-21-25,25>>^ O desejo do preguiçoso o mata; porque as suas mãos recusam-se a trabalhar.

[[v20-21-26]]

^<<v20-21-26,26>>^ Todo o dia o ímpio cobiça; mas o justo dá, e não retém.

[[v20-21-27]]

^<<v20-21-27,27>>^ O sacrifício dos ímpios é abominação; quanto mais oferecendo-o com intenção maligna!

[[v20-21-28]]

^<<v20-21-28,28>>^ A testemunha mentirosa perecerá; mas o homem que ouve falará sem ser contestado.

[[v20-21-29]]

^<<v20-21-29,29>>^ O homem ímpio endurece o seu rosto; mas o reto considera os seus caminhos.

[[v20-21-30]]

^<<v20-21-30,30>>^ Não há sabedoria, nem entendimento, nem conselho contra o Senhor.

[[v20-21-31]]

^<<v20-21-31,31>>^ O cavalo prepara-se para o dia da batalha; mas do Senhor vem a vitória.

'''

xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[Próximo Capítulo &#62;]