include::./index.adoc[]

[[v20-5-0]]
=== Provérbios, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-5-1]]

^<<v20-5-1,1>>^ Filho meu, atende à minha sabedoria; inclinam teu ouvido à minha prudência;

[[v20-5-2]]

^<<v20-5-2,2>>^ para que observes a discrição, e os teus lábios guardem o conhecimento.

[[v20-5-3]]

^<<v20-5-3,3>>^ Porque os lábios da mulher licenciosa destilam mel, e a sua boca e mais macia do que o azeite;

[[v20-5-4]]

^<<v20-5-4,4>>^ mas o seu fim é amargoso como o absinto, agudo como a espada de dois gumes.

[[v20-5-5]]

^<<v20-5-5,5>>^ Os seus pés descem à morte; os seus passos seguem no caminho do Seol.

[[v20-5-6]]

^<<v20-5-6,6>>^ Ela não pondera a vereda da vida; incertos são os seus caminhos, e ela o ignora.

[[v20-5-7]]

^<<v20-5-7,7>>^ Agora, pois, filhos, dai-me ouvidos, e não vos desvieis das palavras da minha boca.

[[v20-5-8]]

^<<v20-5-8,8>>^ Afasta para longe dela o teu caminho, e não te aproximes da porta da sua casa;

[[v20-5-9]]

^<<v20-5-9,9>>^ para que não dês a outros a tua honra, nem os teus anos a cruéis;

[[v20-5-10]]

^<<v20-5-10,10>>^ para que não se fartem os estranhos dos teus bens, e não entrem os teus trabalhos na casa do estrangeiro,

[[v20-5-11]]

^<<v20-5-11,11>>^ e gemas no teu fim, quando se consumirem a tua carne e o teu corpo,

[[v20-5-12]]

^<<v20-5-12,12>>^ e digas: Como detestei a disciplina! e desprezou o meu coração a repreensão!

[[v20-5-13]]

^<<v20-5-13,13>>^ e não escutei a voz dos que me ensinavam, nem aos que me instruíam inclinei o meu ouvido!

[[v20-5-14]]

^<<v20-5-14,14>>^ Quase cheguei à ruína completa, no meio da congregação e da assembléia.

[[v20-5-15]]

^<<v20-5-15,15>>^ Bebe a água da tua própria cisterna, e das correntes do teu poço.

[[v20-5-16]]

^<<v20-5-16,16>>^ Derramar-se-iam as tuas fontes para fora, e pelas ruas os ribeiros de águas?

[[v20-5-17]]

^<<v20-5-17,17>>^ Sejam para ti só, e não para os estranhos juntamente contigo.

[[v20-5-18]]

^<<v20-5-18,18>>^ Seja bendito o teu manancial; e regozija-te na mulher da tua mocidade.

[[v20-5-19]]

^<<v20-5-19,19>>^ Como corça amorosa, e graciosa cabra montesa saciem-te os seus seios em todo o tempo; e pelo seu amor sê encantado perpetuamente.

[[v20-5-20]]

^<<v20-5-20,20>>^ E por que, filho meu, andarias atraído pela mulher licenciosa, e abraçarias o seio da adúltera?

[[v20-5-21]]

^<<v20-5-21,21>>^ Porque os caminhos do homem estão diante dos olhos do Senhor, o qual observa todas as suas veredas.

[[v20-5-22]]

^<<v20-5-22,22>>^ Quanto ao ímpio, as suas próprias iniqüidades o prenderão, e pelas cordas do seu pecado será detido.

[[v20-5-23]]

^<<v20-5-23,23>>^ Ele morre pela falta de disciplina; e pelo excesso da sua loucura anda errado.

'''

xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[&#60; Capítulo Anterior] | <<v20-5-0,Topo>> | xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[Próximo Capítulo &#62;]