include::./index.adoc[]

[[v20-10-0]]
=== Provérbios, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-10-1]]

^<<v20-10-1,1>>^ Provérbios de Salomão. Um filho sábio alegra a seu pai; mas um filho insensato é a tristeza de sua mãe.

[[v20-10-2]]

^<<v20-10-2,2>>^ Os tesouros da impiedade de nada aproveitam; mas a justiça livra da morte.

[[v20-10-3]]

^<<v20-10-3,3>>^ O Senhor não deixa o justo passar fome; mas o desejo dos ímpios ele rechaça.

[[v20-10-4]]

^<<v20-10-4,4>>^ O que trabalha com mão remissa empobrece; mas a mão do diligente enriquece.

[[v20-10-5]]

^<<v20-10-5,5>>^ O que ajunta no verão é filho prudente; mas o que dorme na sega é filho que envergonha.

[[v20-10-6]]

^<<v20-10-6,6>>^ Bênçãos caem sobre a cabeça do justo; porém a boca dos ímpios esconde a violência.

[[v20-10-7]]

^<<v20-10-7,7>>^ A memória do justo é abençoada; mas o nome dos ímpios apodrecerá.

[[v20-10-8]]

^<<v20-10-8,8>>^ O sábio de coração aceita os mandamentos; mas o insensato palra dor cairá.

[[v20-10-9]]

^<<v20-10-9,9>>^ Quem anda em integridade anda seguro; mas o que perverte os seus caminhos será conhecido.

[[v20-10-10]]

^<<v20-10-10,10>>^ O que acena com os olhos dá dores; e o insensato palrador cairá.

[[v20-10-11]]

^<<v20-10-11,11>>^ A boca do justo é manancial de vida, porém a boca dos ímpios esconde a violência.

[[v20-10-12]]

^<<v20-10-12,12>>^ O ódio excita contendas; mas o amor cobre todas as transgressões.

[[v20-10-13]]

^<<v20-10-13,13>>^ Nos lábios do entendido se acha a sabedoria; mas a vara é para as costas do que é falto de entendimento.

[[v20-10-14]]

^<<v20-10-14,14>>^ Os sábios entesouram o conhecimento; porém a boca do insensato é uma destruição iminente.

[[v20-10-15]]

^<<v20-10-15,15>>^ Os bens do rico são a sua cidade forte; a ruína dos pobres é a sua pobreza.

[[v20-10-16]]

^<<v20-10-16,16>>^ O trabalho do justo conduz à vida; a renda do ímpio, para o pecado.

[[v20-10-17]]

^<<v20-10-17,17>>^ O que atende à instrução está na vereda da vida; mas o que rejeita a repreensão anda errado.

[[v20-10-18]]

^<<v20-10-18,18>>^ O que encobre o ódio tem lábios falsos; e o que espalha a calúnia é um insensato.

[[v20-10-19]]

^<<v20-10-19,19>>^ Na multidão de palavras não falta transgressão; mas o que refreia os seus lábios é prudente.

[[v20-10-20]]

^<<v20-10-20,20>>^ A língua do justo é prata escolhida; o coração dos ímpios é de pouco valor.

[[v20-10-21]]

^<<v20-10-21,21>>^ Os lábios do justo apascentam a muitos; mas os insensatos, por falta de entendimento, morrem.

[[v20-10-22]]

^<<v20-10-22,22>>^ A bênção do Senhor é que enriquece; e ele não a faz seguir de dor alguma.

[[v20-10-23]]

^<<v20-10-23,23>>^ E um divertimento para o insensato o praticar a iniqüidade; mas a conduta sábia é o prazer do homem entendido.

[[v20-10-24]]

^<<v20-10-24,24>>^ O que o ímpio teme, isso virá sobre ele; mas aos justos se lhes concederá o seu desejo.

[[v20-10-25]]

^<<v20-10-25,25>>^ Como passa a tempestade, assim desaparece o ímpio; mas o justo tem fundamentos eternos.

[[v20-10-26]]

^<<v20-10-26,26>>^ Como vinagre para os dentes, como fumaça para os olhos, assim é o preguiçoso para aqueles que o mandam.

[[v20-10-27]]

^<<v20-10-27,27>>^ O temor do Senhor aumenta os dias; mas os anos os ímpios serão abreviados.

[[v20-10-28]]

^<<v20-10-28,28>>^ A esperança dos justos é alegria; mas a expectação dos ímpios perecerá.

[[v20-10-29]]

^<<v20-10-29,29>>^ O caminho do Senhor é fortaleza para os retos; mas é destruição para os que praticam a iniqüidade.

[[v20-10-30]]

^<<v20-10-30,30>>^ O justo nunca será abalado; mas os ímpios não habitarão a terra.

[[v20-10-31]]

^<<v20-10-31,31>>^ A boca do justo produz sabedoria; porém a língua perversa será desarraigada.

[[v20-10-32]]

^<<v20-10-32,32>>^ Os lábios do justo sabem o que agrada; porém a boca dos ímpios fala perversidades.

'''

xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[&#60; Capítulo Anterior] | <<v20-10-0,Topo>> | xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[Próximo Capítulo &#62;]