include::./index.adoc[]

[[v20-8-0]]
=== Provérbios, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-8-1]]

^<<v20-8-1,1>>^ Não clama porventura a sabedoria, e não faz o entendimento soar a sua voz?

[[v20-8-2]]

^<<v20-8-2,2>>^ No cume das alturas, junto ao caminho, nas encruzilhadas das veredas ela se coloca.

[[v20-8-3]]

^<<v20-8-3,3>>^ Junto às portas, à entrada da cidade, e à entrada das portas está clamando:

[[v20-8-4]]

^<<v20-8-4,4>>^ A vós, ó homens, clamo; e a minha voz se dirige aos filhos dos homens.

[[v20-8-5]]

^<<v20-8-5,5>>^ Aprendei, ó simples, a prudência; entendei, ó loucos, a sabedoria.

[[v20-8-6]]

^<<v20-8-6,6>>^ Ouvi vós, porque profiro coisas excelentes; os meus lábios se abrem para a eqüidade.

[[v20-8-7]]

^<<v20-8-7,7>>^ Porque a minha boca profere a verdade, os meus lábios abominam a impiedade.

[[v20-8-8]]

^<<v20-8-8,8>>^ Justas são todas as palavras da minha boca; não há nelas nenhuma coisa tortuosa nem perversa.

[[v20-8-9]]

^<<v20-8-9,9>>^ Todas elas são retas para o que bem as entende, e justas para os que acham o conhecimento.

[[v20-8-10]]

^<<v20-8-10,10>>^ Aceitai antes a minha correção, e não a prata; e o conhecimento, antes do que o ouro escolhido.

[[v20-8-11]]

^<<v20-8-11,11>>^ Porque melhor é a sabedoria do que as jóias; e de tudo o que se deseja nada se pode comparar com ela.

[[v20-8-12]]

^<<v20-8-12,12>>^ Eu, a sabedoria, habito com a prudência, e possuo o conhecimento e a discrição.

[[v20-8-13]]

^<<v20-8-13,13>>^ O temor do Senhor é odiar o mal; a soberba, e a arrogância, e o mau caminho, e a boca perversa, eu os odeio.

[[v20-8-14]]

^<<v20-8-14,14>>^ Meu é o conselho, e a verdadeira sabedoria; eu sou o entendimento; minha é a fortaleza.

[[v20-8-15]]

^<<v20-8-15,15>>^ Por mim reinam os reis, e os príncipes decretam o que justo.

[[v20-8-16]]

^<<v20-8-16,16>>^ Por mim governam os príncipes e os nobres, sim, todos os juízes da terra.

[[v20-8-17]]

^<<v20-8-17,17>>^ Eu amo aos que me amam, e os que diligentemente me buscam me acharão.

[[v20-8-18]]

^<<v20-8-18,18>>^ Riquezas e honra estão comigo; sim, riquezas duráveis e justiça.

[[v20-8-19]]

^<<v20-8-19,19>>^ Melhor é o meu fruto do que o ouro, sim, do que o ouro refinado; e a minha renda melhor do que a prata escolhida.

[[v20-8-20]]

^<<v20-8-20,20>>^ Ando pelo caminho da retidão, no meio das veredas da justiça,

[[v20-8-21]]

^<<v20-8-21,21>>^ dotando de bens permanentes os que me amam, e enchendo os seus tesouros.

[[v20-8-22]]

^<<v20-8-22,22>>^ O Senhor me criou como a primeira das suas obras, o princípio dos seus feitos mais antigos.

[[v20-8-23]]

^<<v20-8-23,23>>^ Desde a eternidade fui constituída, desde o princípio, antes de existir a terra.

[[v20-8-24]]

^<<v20-8-24,24>>^ Antes de haver abismos, fui gerada, e antes ainda de haver fontes cheias d'água.

[[v20-8-25]]

^<<v20-8-25,25>>^ Antes que os montes fossem firmados, antes dos outeiros eu nasci,

[[v20-8-26]]

^<<v20-8-26,26>>^ quando ele ainda não tinha feito a terra com seus campos, nem sequer o princípio do pó do mundo.

[[v20-8-27]]

^<<v20-8-27,27>>^ Quando ele preparava os céus, aí estava eu; quando traçava um círculo sobre a face do abismo,

[[v20-8-28]]

^<<v20-8-28,28>>^ quando estabelecia o firmamento em cima, quando se firmavam as fontes do abismo,

[[v20-8-29]]

^<<v20-8-29,29>>^ quando ele fixava ao mar o seu termo, para que as águas não traspassassem o seu mando, quando traçava os fundamentos da terra,

[[v20-8-30]]

^<<v20-8-30,30>>^ então eu estava ao seu lado como arquiteto; e era cada dia as suas delícias, alegrando-me perante ele em todo o tempo;

[[v20-8-31]]

^<<v20-8-31,31>>^ folgando no seu mundo habitável, e achando as minhas delícias com os filhos dos homens.

[[v20-8-32]]

^<<v20-8-32,32>>^ Agora, pois, filhos, ouvi-me; porque felizes são os que guardam os meus caminhos.

[[v20-8-33]]

^<<v20-8-33,33>>^ Ouvi a correção, e sede sábios; e não a rejeiteis.

[[v20-8-34]]

^<<v20-8-34,34>>^ Feliz é o homem que me dá ouvidos, velando cada dia às minhas entradas, esperando junto às ombreiras da minha porta.

[[v20-8-35]]

^<<v20-8-35,35>>^ Porque o que me achar achará a vida, e alcançará o favor do Senhor.

[[v20-8-36]]

^<<v20-8-36,36>>^ Mas o que pecar contra mim fará mal à sua própria alma; todos os que me odeiam amam a morte.

'''

xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[Próximo Capítulo &#62;]