include::./index.adoc[]

[[v20-2-0]]
=== Provérbios, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-2-1]]

^<<v20-2-1,1>>^ Filho meu, se aceitares as minhas palavras, e entesourares contigo os meus mandamentos,

[[v20-2-2]]

^<<v20-2-2,2>>^ para fazeres atento à sabedoria o teu ouvido, e para inclinares o teu coração ao entendimento;

[[v20-2-3]]

^<<v20-2-3,3>>^ sim, se clamares por discernimento, e por entendimento alçares a tua voz;

[[v20-2-4]]

^<<v20-2-4,4>>^ se o buscares como a prata e o procurares como a tesouros escondidos;

[[v20-2-5]]

^<<v20-2-5,5>>^ então entenderás o temor do Senhor, e acharás o conhecimento de Deus.

[[v20-2-6]]

^<<v20-2-6,6>>^ Porque o Senhor dá a sabedoria; da sua boca procedem o conhecimento e o entendimento;

[[v20-2-7]]

^<<v20-2-7,7>>^ ele reserva a verdadeira sabedoria para os retos; e escudo para os que caminham em integridade,

[[v20-2-8]]

^<<v20-2-8,8>>^ guardando-lhes as veredas da justiça, e preservando o caminho dos seus santos.

[[v20-2-9]]

^<<v20-2-9,9>>^ Então entenderás a retidão, a justiça, a eqüidade, e todas as boas veredas.

[[v20-2-10]]

^<<v20-2-10,10>>^ Pois a sabedoria entrará no teu coração, e o conhecimento será aprazível à tua alma;

[[v20-2-11]]

^<<v20-2-11,11>>^ o bom siso te protegerá, e o discernimento e guardará;

[[v20-2-12]]

^<<v20-2-12,12>>^ para te livrar do mau caminho, e do homem que diz coisas perversas;

[[v20-2-13]]

^<<v20-2-13,13>>^ dos que deixam as veredas da retidão, para andarem pelos caminhos das trevas;

[[v20-2-14]]

^<<v20-2-14,14>>^ que se alegram de fazer o mal, e se deleitam nas perversidades dos maus;

[[v20-2-15]]

^<<v20-2-15,15>>^ dos que são tortuosos nas suas veredas; e iníquos nas suas carreiras;

[[v20-2-16]]

^<<v20-2-16,16>>^ e para te livrar da mulher estranha, da estrangeira que lisonjeia com suas palavras;

[[v20-2-17]]

^<<v20-2-17,17>>^ a qual abandona o companheiro da sua mocidade e se esquece do concerto do seu Deus;

[[v20-2-18]]

^<<v20-2-18,18>>^ pois a sua casa se inclina para a morte, e as suas veredas para as sombras.

[[v20-2-19]]

^<<v20-2-19,19>>^ Nenhum dos que se dirigirem a ela, tornara a sair, nem retomará as veredas da vida.

[[v20-2-20]]

^<<v20-2-20,20>>^ Assim andarás pelo caminho dos bons, e guardarás as veredas dos justos.

[[v20-2-21]]

^<<v20-2-21,21>>^ Porque os retos habitarão a terra, e os íntegros permanecerão nela.

[[v20-2-22]]

^<<v20-2-22,22>>^ Mas os ímpios serão exterminados da terra, e dela os aleivosos serão desarraigados.

'''

xref:020-proverbios/020-proverbios-001.adoc#v20-1-0[&#60; Capítulo Anterior] | <<v20-2-0,Topo>> | xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[Próximo Capítulo &#62;]