include::./index.adoc[]

[[v20-7-0]]
=== Provérbios, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-7-1]]

^<<v20-7-1,1>>^ Filho meu, guarda as minhas palavras, e entesoura contigo os meus mandamentos.

[[v20-7-2]]

^<<v20-7-2,2>>^ Observa os meus mandamentos e vive; guarda a minha lei, como a menina dos teus olhos.

[[v20-7-3]]

^<<v20-7-3,3>>^ Ata-os aos teus dedos, escreve-os na tábua do teu coração.

[[v20-7-4]]

^<<v20-7-4,4>>^ Dize à sabedoria: Tu és minha irmã; e chama ao entendimento teu amigo íntimo,

[[v20-7-5]]

^<<v20-7-5,5>>^ para te guardarem da mulher alheia, da adúltera, que lisonjeia com as suas palavras.

[[v20-7-6]]

^<<v20-7-6,6>>^ Porque da janela da minha casa, por minhas grades olhando eu,

[[v20-7-7]]

^<<v20-7-7,7>>^ vi entre os simples, divisei entre os jovens, um mancebo falto de juízo,

[[v20-7-8]]

^<<v20-7-8,8>>^ que passava pela rua junto à esquina da mulher adúltera e que seguia o caminho da sua casa,

[[v20-7-9]]

^<<v20-7-9,9>>^ no crepúsculo, à tarde do dia, à noite fechada e na escuridão;

[[v20-7-10]]

^<<v20-7-10,10>>^ e eis que uma mulher lhe saiu ao encontro, ornada à moda das prostitutas, e astuta de coração.

[[v20-7-11]]

^<<v20-7-11,11>>^ Ela é turbulenta e obstinada; não param em casa os seus pés;

[[v20-7-12]]

^<<v20-7-12,12>>^ ora está ela pelas ruas, ora pelas praças, espreitando por todos os cantos.

[[v20-7-13]]

^<<v20-7-13,13>>^ Pegou dele, pois, e o beijou; e com semblante impudico lhe disse:

[[v20-7-14]]

^<<v20-7-14,14>>^ Sacrifícios pacíficos tenho comigo; hoje paguei os meus votos.

[[v20-7-15]]

^<<v20-7-15,15>>^ Por isso saí ao teu encontro a buscar-te diligentemente, e te achei.

[[v20-7-16]]

^<<v20-7-16,16>>^ Já cobri a minha cama de cobertas, de colchas de linho do Egito.

[[v20-7-17]]

^<<v20-7-17,17>>^ Já perfumei o meu leito com mirra, aloés e cinamomo.

[[v20-7-18]]

^<<v20-7-18,18>>^ Vem, saciemo-nos de amores até pela manhã; alegremo-nos com amores.

[[v20-7-19]]

^<<v20-7-19,19>>^ Porque meu marido não está em casa; foi fazer uma jornada ao longe;

[[v20-7-20]]

^<<v20-7-20,20>>^ um saquitel de dinheiro levou na mão; só lá para o dia da lua cheia voltará para casa.

[[v20-7-21]]

^<<v20-7-21,21>>^ Ela o faz ceder com a multidão das suas palavras sedutoras, com as lisonjas dos seus lábios o arrasta.

[[v20-7-22]]

^<<v20-7-22,22>>^ Ele a segue logo, como boi que vai ao matadouro, e como o louco ao castigo das prisões;

[[v20-7-23]]

^<<v20-7-23,23>>^ até que uma flecha lhe atravesse o fígado, como a ave que se apressa para o laço, sem saber que está armado contra a sua vida.

[[v20-7-24]]

^<<v20-7-24,24>>^ Agora, pois, filhos, ouvi-me, e estai atentos às palavras da minha boca.

[[v20-7-25]]

^<<v20-7-25,25>>^ Não se desvie para os seus caminhos o teu coração, e não andes perdido nas suas veredas.

[[v20-7-26]]

^<<v20-7-26,26>>^ Porque ela a muitos tem feito cair feridos; e são muitíssimos os que por ela foram mortos.

[[v20-7-27]]

^<<v20-7-27,27>>^ Caminho de Seol é a sua casa, o qual desce às câmaras da morte.

'''

xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[&#60; Capítulo Anterior] | <<v20-7-0,Topo>> | xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[Próximo Capítulo &#62;]