include::./index.adoc[]

[[v20-12-0]]
=== Provérbios, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-12-1]]

^<<v20-12-1,1>>^ O que ama a correção ama o conhecimento; mas o que aborrece a repreensão é insensato.

[[v20-12-2]]

^<<v20-12-2,2>>^ O homem de bem alcançará o favor do Senhor; mas ao homem de perversos desígnios ele condenará.

[[v20-12-3]]

^<<v20-12-3,3>>^ O homem não se estabelece pela impiedade; a raiz dos justos, porém, nunca será, removida.

[[v20-12-4]]

^<<v20-12-4,4>>^ A mulher virtuosa é a coroa do seu marido; porém a que procede vergonhosamente é como apodrecimento nos seus ossos.

[[v20-12-5]]

^<<v20-12-5,5>>^ Os pensamentos do justo são retos; mas os conselhos do ímpio são falsos.

[[v20-12-6]]

^<<v20-12-6,6>>^ As palavras dos ímpios são emboscadas para derramarem sangue; a boca dos retos, porém, os livrará.

[[v20-12-7]]

^<<v20-12-7,7>>^ Transtornados serão os ímpios, e não serão mais; porém a casa dos justos permanecerá.

[[v20-12-8]]

^<<v20-12-8,8>>^ Segundo o seu entendimento é louvado o homem; mas o perverso decoração é desprezado.

[[v20-12-9]]

^<<v20-12-9,9>>^ Melhor é o que é estimado em pouco e tem servo, do que quem se honra a si mesmo e tem falta de pão.

[[v20-12-10]]

^<<v20-12-10,10>>^ O justo olha pela vida dos seus animais; porém as entranhas dos ímpios são cruéis.

[[v20-12-11]]

^<<v20-12-11,11>>^ O que lavra a sua terra se fartará de pão; mas o que segue os ociosos é falto de entendimento.

[[v20-12-12]]

^<<v20-12-12,12>>^ Deseja o ímpio o despojo dos maus; porém a raiz dos justos produz o seu próprio fruto.

[[v20-12-13]]

^<<v20-12-13,13>>^ Pela transgressão dos lábios se enlaça o mau; mas o justo escapa da angústia.

[[v20-12-14]]

^<<v20-12-14,14>>^ Do fruto das suas palavras o homem se farta de bem; e das obras das suas mãos se lhe retribui.

[[v20-12-15]]

^<<v20-12-15,15>>^ O caminho do insensato é reto aos seus olhos; mas o que dá ouvidos ao conselho é sábio.

[[v20-12-16]]

^<<v20-12-16,16>>^ A ira do insensato logo se revela; mas o prudente encobre a afronta.

[[v20-12-17]]

^<<v20-12-17,17>>^ Quem fala a verdade manifesta a justiça; porém a testemunha falsa produz a fraude.

[[v20-12-18]]

^<<v20-12-18,18>>^ Há palrador cujas palavras ferem como espada; porém a língua dos sábios traz saúde.

[[v20-12-19]]

^<<v20-12-19,19>>^ O lábio veraz permanece para sempre; mas a língua mentirosa dura só um momento.

[[v20-12-20]]

^<<v20-12-20,20>>^ Engano há no coração dos que maquinam o mal; mas há gozo para os que aconselham a paz.

[[v20-12-21]]

^<<v20-12-21,21>>^ Nenhuma desgraça sobrevém ao justo; mas os ímpios ficam cheios de males.

[[v20-12-22]]

^<<v20-12-22,22>>^ Os lábios mentirosos são abomináveis ao Senhor; mas os que praticam a verdade são o seu deleite.

[[v20-12-23]]

^<<v20-12-23,23>>^ O homem prudente encobre o conhecimento; mas o coração dos tolos proclama a estultícia.

[[v20-12-24]]

^<<v20-12-24,24>>^ A mão dos diligentes dominará; mas o indolente será tributário servil.

[[v20-12-25]]

^<<v20-12-25,25>>^ A ansiedade no coração do homem o abate; mas uma boa palavra o alegra.

[[v20-12-26]]

^<<v20-12-26,26>>^ O justo é um guia para o seu próximo; mas o caminho dos ímpios os faz errar.

[[v20-12-27]]

^<<v20-12-27,27>>^ O preguiçoso não apanha a sua caça; mas o bem precioso do homem é para o diligente.

[[v20-12-28]]

^<<v20-12-28,28>>^ Na vereda da justiça está a vida; e no seu caminho não há morte.

'''

xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[&#60; Capítulo Anterior] | <<v20-12-0,Topo>> | xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[Próximo Capítulo &#62;]