include::./index.adoc[]

[[v20-16-0]]
=== Provérbios, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-16-1]]

^<<v20-16-1,1>>^ Ao homem pertencem os planos do coração; mas a resposta da língua é do Senhor.

[[v20-16-2]]

^<<v20-16-2,2>>^ Todos os caminhos do homem são limpos aos seus olhos; mas o Senhor pesa os espíritos.

[[v20-16-3]]

^<<v20-16-3,3>>^ Entrega ao Senhor as tuas obras, e teus desígnios serão estabelecidos.

[[v20-16-4]]

^<<v20-16-4,4>>^ O Senhor fez tudo para um fim; sim, até o ímpio para o dia do mal.

[[v20-16-5]]

^<<v20-16-5,5>>^ Todo homem arrogante é abominação ao Senhor; certamente não ficará impune.

[[v20-16-6]]

^<<v20-16-6,6>>^ Pela misericórdia e pela verdade expia-se a iniqüidade; e pelo temor do Senhor os homens se desviam do mal.

[[v20-16-7]]

^<<v20-16-7,7>>^ Quando os caminhos do homem agradam ao Senhor, faz que até os seus inimigos tenham paz com ele.

[[v20-16-8]]

^<<v20-16-8,8>>^ Melhor é o pouco com justiça, do que grandes rendas com injustiça.

[[v20-16-9]]

^<<v20-16-9,9>>^ O coração do homem propõe o seu caminho; mas o Senhor lhe dirige os passos.

[[v20-16-10]]

^<<v20-16-10,10>>^ Nos lábios do rei acham-se oráculos; em juízo a sua boca não prevarica.

[[v20-16-11]]

^<<v20-16-11,11>>^ O peso e a balança justos são do Senhor; obra sua são todos os pesos da bolsa.

[[v20-16-12]]

^<<v20-16-12,12>>^ Abominação é para os reis o praticarem a impiedade; porque com justiça se estabelece o trono.

[[v20-16-13]]

^<<v20-16-13,13>>^ Lábios justos são o prazer dos reis; e eles amam aquele que fala coisas retas.

[[v20-16-14]]

^<<v20-16-14,14>>^ O furor do rei é mensageiro da morte; mas o homem sábio o aplacará.

[[v20-16-15]]

^<<v20-16-15,15>>^ Na luz do semblante do rei está a vida; e o seu favor é como a nuvem de chuva serôdia.

[[v20-16-16]]

^<<v20-16-16,16>>^ Quanto melhor é adquirir a sabedoria do que o ouro! e quanto mais excelente é escolher o entendimento do que a prata!

[[v20-16-17]]

^<<v20-16-17,17>>^ A estrada dos retos desvia-se do mal; o que guarda o seu caminho preserva a sua vida.

[[v20-16-18]]

^<<v20-16-18,18>>^ A soberba precede a destruição, e a altivez do espírito precede a queda.

[[v20-16-19]]

^<<v20-16-19,19>>^ Melhor é ser humilde de espírito com os mansos, do que repartir o despojo com os soberbos.

[[v20-16-20]]

^<<v20-16-20,20>>^ O que atenta prudentemente para a palavra prosperará; e feliz é aquele que confia no Senhor.

[[v20-16-21]]

^<<v20-16-21,21>>^ O sábio de coração será chamado prudente; e a doçura dos lábios aumenta o saber.

[[v20-16-22]]

^<<v20-16-22,22>>^ O entendimento, para aquele que o possui, é uma fonte de vida, porém a estultícia é o castigo dos insensatos.

[[v20-16-23]]

^<<v20-16-23,23>>^ O coração do sábio instrui a sua boca, e aumenta o saber nos seus lábios.

[[v20-16-24]]

^<<v20-16-24,24>>^ Palavras suaves são como favos de mel, doçura para a alma e saúde para o corpo.

[[v20-16-25]]

^<<v20-16-25,25>>^ Há um caminho que ao homem parece direito, mas o fim dele conduz à morte.

[[v20-16-26]]

^<<v20-16-26,26>>^ O apetite do trabalhador trabalha por ele, porque a sua fome o incita a isso.

[[v20-16-27]]

^<<v20-16-27,27>>^ O homem vil suscita o mal; e nos seus lábios há como que um fogo ardente.

[[v20-16-28]]

^<<v20-16-28,28>>^ O homem perverso espalha contendas; e o difamador separa amigos íntimos.

[[v20-16-29]]

^<<v20-16-29,29>>^ O homem violento alicia o seu vizinho, e guia-o por um caminho que não é bom.

[[v20-16-30]]

^<<v20-16-30,30>>^ Quando fecha os olhos fá-lo para maquinar perversidades; quando morde os lábios, efetua o mal.

[[v20-16-31]]

^<<v20-16-31,31>>^ Coroa de honra são as cãs, a qual se obtém no caminho da justiça.

[[v20-16-32]]

^<<v20-16-32,32>>^ Melhor é o longânimo do que o valente; e o que domina o seu espírito do que o que toma uma cidade.

[[v20-16-33]]

^<<v20-16-33,33>>^ A sorte se lança no regaço; mas do Senhor procede toda a disposição dela.

'''

xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[Próximo Capítulo &#62;]