include::./index.adoc[]

[[v20-25-0]]
=== Provérbios, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-25-1]]

^<<v20-25-1,1>>^ Também estes são provérbios de Salomão, os quais transcreveram os homens de Ezequias, rei de Judá.

[[v20-25-2]]

^<<v20-25-2,2>>^ A glória de Deus é encobrir as coisas; mas a glória dos reis é esquadrinhá-las.

[[v20-25-3]]

^<<v20-25-3,3>>^ Como o céu na sua altura, e como a terra na sua profundidade, assim o coração dos reis é inescrutável.

[[v20-25-4]]

^<<v20-25-4,4>>^ Tira da prata a escória, e sairá um vaso para o fundidor.

[[v20-25-5]]

^<<v20-25-5,5>>^ Tira o ímpio da presença do rei, e o seu trono se firmará na justiça.

[[v20-25-6]]

^<<v20-25-6,6>>^ Não reclames para ti honra na presença do rei, nem te ponhas no lugar dos grandes;

[[v20-25-7]]

^<<v20-25-7,7>>^ porque melhor é que te digam: Sobe, para aqui; do que seres humilhado perante o príncipe.

[[v20-25-8]]

^<<v20-25-8,8>>^ O que os teus olhos viram, não te apresses a revelar, para depois, ao fim, não saberes o que hás de fazer, podendo-te confundir o teu próximo.

[[v20-25-9]]

^<<v20-25-9,9>>^ Pleiteia a tua causa com o teu próximo mesmo; e não reveles o segredo de outrem;

[[v20-25-10]]

^<<v20-25-10,10>>^ para que não te desonre aquele que o ouvir, não se apartando de ti a infâmia.

[[v20-25-11]]

^<<v20-25-11,11>>^ Como maçãs de ouro em salvas de prata, assim é a palavra dita a seu tempo.

[[v20-25-12]]

^<<v20-25-12,12>>^ Como pendentes de ouro e gargantilhas de ouro puro, assim é o sábio repreensor para o ouvido obediente.

[[v20-25-13]]

^<<v20-25-13,13>>^ Como o frescor de neve no tempo da sega, assim é o mensageiro fiel para com os que o enviam, porque refrigera o espírito dos seus senhores.

[[v20-25-14]]

^<<v20-25-14,14>>^ como nuvens e ventos que não trazem chuva, assim é o homem que se gaba de dádivas que não fez.

[[v20-25-15]]

^<<v20-25-15,15>>^ Pela longanimidade se persuade o príncipe, e a língua branda quebranta os ossos.

[[v20-25-16]]

^<<v20-25-16,16>>^ Se achaste mel, come somente o que te basta, para que porventura não te fartes dele, e o venhas a vomitar.

[[v20-25-17]]

^<<v20-25-17,17>>^ Põe raramente o teu pé na casa do teu próximo, para que não se enfade de ti, e te aborreça.

[[v20-25-18]]

^<<v20-25-18,18>>^ Malho, e espada, e flecha aguda é o homem que levanta falso testemunho contra o seu próximo.

[[v20-25-19]]

^<<v20-25-19,19>>^ Como dente quebrado, e pé deslocado, é a confiança no homem desleal, no dia da angústia.

[[v20-25-20]]

^<<v20-25-20,20>>^ O que entoa canções ao coração aflito é como aquele que despe uma peça de roupa num dia de frio, e como vinagre sobre a chaga.

[[v20-25-21]]

^<<v20-25-21,21>>^ Se o teu inimigo tiver fome, dá-lhe pão para comer, e se tiver sede, dá-lhe água para beber;

[[v20-25-22]]

^<<v20-25-22,22>>^ porque assim lhe amontoarás brasas sobre a cabeça, e o Senhor te recompensará.

[[v20-25-23]]

^<<v20-25-23,23>>^ O vento norte traz chuva, e a língua caluniadora, o rosto irado.

[[v20-25-24]]

^<<v20-25-24,24>>^ Melhor é morar num canto do eirado, do que com a mulher rixosa numa casa ampla.

[[v20-25-25]]

^<<v20-25-25,25>>^ Como água fresca para o homem sedento, tais são as boas-novas de terra remota.

[[v20-25-26]]

^<<v20-25-26,26>>^ Como fonte turva, e manancial poluído, assim é o justo que cede lugar diante do ímpio.

[[v20-25-27]]

^<<v20-25-27,27>>^ comer muito mel não é bom; não multipliques, pois, as palavras de lisonja.

[[v20-25-28]]

^<<v20-25-28,28>>^ Como a cidade derribada, que não tem muros, assim é o homem que não pode conter o seu espírito.

'''

xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[&#60; Capítulo Anterior] | <<v20-25-0,Topo>> | xref:020-proverbios/020-proverbios-026.adoc#v20-26-0[Próximo Capítulo &#62;]