include::./index.adoc[]

[[v20-28-0]]
=== Provérbios, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-28-1]]

^<<v20-28-1,1>>^ Fogem os ímpios, sem que ninguém os persiga; mas os justos são ousados como o leão.

[[v20-28-2]]

^<<v20-28-2,2>>^ Por causa da transgressão duma terra são muitos os seus príncipes; mas por virtude de homens prudentes e entendidos, ela subsistirá por longo tempo.

[[v20-28-3]]

^<<v20-28-3,3>>^ O homem pobre que oprime os pobres, é como chuva impetuosa, que não deixa trigo nenhum.

[[v20-28-4]]

^<<v20-28-4,4>>^ Os que abandonam a lei louvam os ímpios; mas os que guardam a lei pelejam contra eles.

[[v20-28-5]]

^<<v20-28-5,5>>^ Os homens maus não entendem a justiça; mas os que buscam ao Senhor a entendem plenamente.

[[v20-28-6]]

^<<v20-28-6,6>>^ Melhor é o pobre que anda na sua integridade, do que o rico perverso nos seus caminhos.

[[v20-28-7]]

^<<v20-28-7,7>>^ O que guarda a lei é filho sábio; mas o companheiro dos comilões envergonha a seu pai.

[[v20-28-8]]

^<<v20-28-8,8>>^ O que aumenta a sua riqueza com juros e usura, ajunta-a para o que se compadece do pobre.

[[v20-28-9]]

^<<v20-28-9,9>>^ O que desvia os seus ouvidos de ouvir a lei, até a sua oração é abominável.

[[v20-28-10]]

^<<v20-28-10,10>>^ O que faz com que os retos se desviem para um mau caminho, ele mesmo cairá na cova que abriu; mas os inocentes herdarão o bem.

[[v20-28-11]]

^<<v20-28-11,11>>^ O homem rico é sábio aos seus próprios olhos; mas o pobre que tem entendimento o esquadrinha.

[[v20-28-12]]

^<<v20-28-12,12>>^ Quando os justos triunfam há grande, glória; mas quando os ímpios sobem, escondem-se os homens.

[[v20-28-13]]

^<<v20-28-13,13>>^ O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa, alcançará misericórdia.

[[v20-28-14]]

^<<v20-28-14,14>>^ Feliz é o homem que teme ao Senhor continuamente; mas o que endurece o seu coração virá a cair no mal.

[[v20-28-15]]

^<<v20-28-15,15>>^ Como leão bramidor, e urso faminto, assim é o ímpio que domina sobre um povo pobre.

[[v20-28-16]]

^<<v20-28-16,16>>^ O príncipe falto de entendimento é também opressor cruel; mas o que aborrece a avareza prolongará os seus dias.

[[v20-28-17]]

^<<v20-28-17,17>>^ O homem culpado do sangue de qualquer pessoa será fugitivo até a morte; ninguém o ajude.

[[v20-28-18]]

^<<v20-28-18,18>>^ O que anda retamente salvar-se-á; mas o perverso em seus caminhos cairá de repente.

[[v20-28-19]]

^<<v20-28-19,19>>^ O que lavra a sua terra se fartará de pão; mas o que segue os ociosos se encherá de pobreza.

[[v20-28-20]]

^<<v20-28-20,20>>^ O homem fiel gozará de abundantes bênçãos; mas o que se apressa a enriquecer não ficará impune.

[[v20-28-21]]

^<<v20-28-21,21>>^ Fazer acepção de pessoas não é bom; mas até por um bocado de pão prevaricará o homem.

[[v20-28-22]]

^<<v20-28-22,22>>^ Aquele que é cobiçoso corre atrás das riquezas; e não sabe que há de vir sobre ele a penúria.

[[v20-28-23]]

^<<v20-28-23,23>>^ O que repreende a um homem achará depois mais favor do que aquele que lisonjeia com a língua.

[[v20-28-24]]

^<<v20-28-24,24>>^ O que rouba a seu pai, ou a sua mãe, e diz: Isso não é transgressão; esse é companheiro do destruidor.

[[v20-28-25]]

^<<v20-28-25,25>>^ O cobiçoso levanta contendas; mas o que confia no senhor prosperará.

[[v20-28-26]]

^<<v20-28-26,26>>^ O que confia no seu próprio coração é insensato; mas o que anda sabiamente será livre.

[[v20-28-27]]

^<<v20-28-27,27>>^ O que dá ao pobre não terá falta; mas o que esconde os seus olhos terá muitas maldições.

[[v20-28-28]]

^<<v20-28-28,28>>^ Quando os ímpios sobem, escondem-se os homens; mas quando eles perecem, multiplicam-se os justos.

'''

xref:020-proverbios/020-proverbios-027.adoc#v20-27-0[&#60; Capítulo Anterior] | <<v20-28-0,Topo>> | xref:020-proverbios/020-proverbios-029.adoc#v20-29-0[Próximo Capítulo &#62;]