include::./index.adoc[]

[[v20-24-0]]
=== Provérbios, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-24-1]]

^<<v20-24-1,1>>^ Não tenhas inveja dos homens malignos; nem desejes estar com eles;

[[v20-24-2]]

^<<v20-24-2,2>>^ porque o seu coração medita a violência; e os seus lábios falam maliciosamente.

[[v20-24-3]]

^<<v20-24-3,3>>^ Com a sabedoria se edifica a casa, e com o entendimento ela se estabelece;

[[v20-24-4]]

^<<v20-24-4,4>>^ e pelo conhecimento se encherão as câmaras de todas as riquezas preciosas e deleitáveis.

[[v20-24-5]]

^<<v20-24-5,5>>^ O sábio é mais poderoso do que o forte; e o inteligente do que o que possui a força.

[[v20-24-6]]

^<<v20-24-6,6>>^ Porque com conselhos prudentes tu podes fazer a guerra; e há vitória na multidão dos conselheiros.

[[v20-24-7]]

^<<v20-24-7,7>>^ A sabedoria é alta demais para o insensato; ele não abre a sua boca na porta.

[[v20-24-8]]

^<<v20-24-8,8>>^ Aquele que cuida em fazer o mal, mestre de maus intentos o chamarão.

[[v20-24-9]]

^<<v20-24-9,9>>^ O desígnio do insensato é pecado; e abominável aos homens é o escarnecedor.

[[v20-24-10]]

^<<v20-24-10,10>>^ Se enfraqueces no dia da angústia, a tua força é pequena.

[[v20-24-11]]

^<<v20-24-11,11>>^ Livra os que estão sendo levados à morte, detém os que vão tropeçando para a matança.

[[v20-24-12]]

^<<v20-24-12,12>>^ Se disseres: Eis que não o sabemos; porventura aquele que pesa os corações não o percebe? e aquele que guarda a tua vida não o sabe? e não retribuirá a cada um conforme a sua obra?

[[v20-24-13]]

^<<v20-24-13,13>>^ Come mel, filho meu, porque é bom, e do favo de mel, que é doce ao teu paladar.

[[v20-24-14]]

^<<v20-24-14,14>>^ Sabe que é assim a sabedoria para a tua alma: se a achares, haverá para ti recompensa, e não será malograda a tua esperança.

[[v20-24-15]]

^<<v20-24-15,15>>^ Não te ponhas de emboscada, ó ímpio, contra a habitação do justo; nem assoles a sua pousada.

[[v20-24-16]]

^<<v20-24-16,16>>^ Porque sete vezes cai o justo, e se levanta; mas os ímpios são derribados pela calamidade.

[[v20-24-17]]

^<<v20-24-17,17>>^ Quando cair o teu inimigo, não te alegres, e quando tropeçar, não se regozije o teu coração;

[[v20-24-18]]

^<<v20-24-18,18>>^ para que o Senhor não o veja, e isso seja mau aos seus olhos, e desvie dele, a sua ira.

[[v20-24-19]]

^<<v20-24-19,19>>^ Não te aflijas por causa dos malfeitores; nem tenhas inveja dos ímpios;

[[v20-24-20]]

^<<v20-24-20,20>>^ porque o maligno não tem futuro; e a lâmpada dos ímpios se apagará.

[[v20-24-21]]

^<<v20-24-21,21>>^ Filho meu, teme ao Senhor, e ao rei; e não te entremetas com os que gostam de mudanças.

[[v20-24-22]]

^<<v20-24-22,22>>^ Porque de repente se levantará a sua calamidade; e a ruína deles, quem a conhecerá?

[[v20-24-23]]

^<<v20-24-23,23>>^ Também estes são provérbios dos sábios: Fazer acepção de pessoas no juízo não é bom.

[[v20-24-24]]

^<<v20-24-24,24>>^ Aquele que disser ao ímpio: Justo és; os povos o amaldiçoarão, as nações o detestarão;

[[v20-24-25]]

^<<v20-24-25,25>>^ mas para os que julgam retamente haverá delícias, e sobre eles virá copiosa bênção.

[[v20-24-26]]

^<<v20-24-26,26>>^ O que responde com palavras retas beija os lábios.

[[v20-24-27]]

^<<v20-24-27,27>>^ Prepara os teus trabalhos de fora, apronta bem o teu campo; e depois edifica a tua casa.

[[v20-24-28]]

^<<v20-24-28,28>>^ Não sejas testemunha sem causa contra o teu próximo; e não enganes com os teus lábios.

[[v20-24-29]]

^<<v20-24-29,29>>^ Não digas: Como ele me fez a mim, assim lhe farei a ele; pagarei a cada um segundo a sua obra.

[[v20-24-30]]

^<<v20-24-30,30>>^ Passei junto ao campo do preguiçoso, e junto à vinha do homem falto de entendimento;

[[v20-24-31]]

^<<v20-24-31,31>>^ e eis que tudo estava cheio de cardos, e a sua superfície coberta de urtigas, e o seu muro de pedra estava derrubado.

[[v20-24-32]]

^<<v20-24-32,32>>^ O que tendo eu visto, o considerei; e, vendo-o, recebi instrução.

[[v20-24-33]]

^<<v20-24-33,33>>^ Um pouco para dormir, um pouco para toscanejar, um pouco para cruzar os braços em repouso;

[[v20-24-34]]

^<<v20-24-34,34>>^ assim sobrevirá a tua pobreza como um salteador, e a tua necessidade como um homem armado.

'''

xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[Próximo Capítulo &#62;]