include::./index.adoc[]

[[v20-3-0]]
=== Provérbios, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-3-1]]

^<<v20-3-1,1>>^ Filho meu, não te esqueças da minha instrução, e o teu coração guarde os meus mandamentos;

[[v20-3-2]]

^<<v20-3-2,2>>^ porque eles te darão longura de dias, e anos de vida e paz.

[[v20-3-3]]

^<<v20-3-3,3>>^ Não se afastem de ti a benignidade e a fidelidade; ata-as ao teu pescoço, escreve-as na tábua do teu coração;

[[v20-3-4]]

^<<v20-3-4,4>>^ assim acharás favor e bom entendimento à vista de Deus e dos homens.

[[v20-3-5]]

^<<v20-3-5,5>>^ Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.

[[v20-3-6]]

^<<v20-3-6,6>>^ Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.

[[v20-3-7]]

^<<v20-3-7,7>>^ Não sejas sábio a teus próprios olhos; teme ao Senhor e aparta-te do mal.

[[v20-3-8]]

^<<v20-3-8,8>>^ Isso será saúde para a tua carne; e refrigério para os teus ossos.

[[v20-3-9]]

^<<v20-3-9,9>>^ Honra ao Senhor com os teus bens, e com as primícias de toda a tua renda;

[[v20-3-10]]

^<<v20-3-10,10>>^ assim se encherão de fartura os teus celeiros, e trasbordarão de mosto os teus lagares.

[[v20-3-11]]

^<<v20-3-11,11>>^ Filho meu, não rejeites a disciplina do Senhor, nem te enojes da sua repreensão;

[[v20-3-12]]

^<<v20-3-12,12>>^ porque o Senhor repreende aquele a quem ama, assim como o pai ao filho a quem quer bem.

[[v20-3-13]]

^<<v20-3-13,13>>^ Feliz é o homem que acha sabedoria, e o homem que adquire entendimento;

[[v20-3-14]]

^<<v20-3-14,14>>^ pois melhor é o lucro que ela dá do que o lucro da prata, e a sua renda do que o ouro.

[[v20-3-15]]

^<<v20-3-15,15>>^ Mais preciosa é do que as jóias, e nada do que possas desejar é comparável a ela.

[[v20-3-16]]

^<<v20-3-16,16>>^ Longura de dias há na sua mão direita; na sua esquerda riquezas e honra.

[[v20-3-17]]

^<<v20-3-17,17>>^ Os seus caminhos são caminhos de delícias, e todas as suas veredas são paz.

[[v20-3-18]]

^<<v20-3-18,18>>^ É árvore da vida para os que dela lançam mão, e bem-aventurado é todo aquele que a retém.

[[v20-3-19]]

^<<v20-3-19,19>>^ O Senhor pela sabedoria fundou a terra; pelo entendimento estabeleceu o céu.

[[v20-3-20]]

^<<v20-3-20,20>>^ Pelo seu conhecimento se fendem os abismos, e as nuvens destilam o orvalho.

[[v20-3-21]]

^<<v20-3-21,21>>^ Filho meu, não se apartem estas coisas dos teus olhos: guarda a verdadeira sabedoria e o bom siso;

[[v20-3-22]]

^<<v20-3-22,22>>^ assim serão elas vida para a tua alma, e adorno para o teu pescoço.

[[v20-3-23]]

^<<v20-3-23,23>>^ Então andarás seguro pelo teu caminho, e não tropeçará o teu pé.

[[v20-3-24]]

^<<v20-3-24,24>>^ Quando te deitares, não temerás; sim, tu te deitarás e o teu sono será suave.

[[v20-3-25]]

^<<v20-3-25,25>>^ Não temas o pavor repentino, nem a assolação dos ímpios quando vier.

[[v20-3-26]]

^<<v20-3-26,26>>^ Porque o Senhor será a tua confiança, e guardará os teus pés de serem presos.

[[v20-3-27]]

^<<v20-3-27,27>>^ Não negues o bem a quem de direito, estando no teu poder fazê-lo.

[[v20-3-28]]

^<<v20-3-28,28>>^ Não digas ao teu próximo: Vai, e volta, amanhã to darei; tendo-o tu contigo.

[[v20-3-29]]

^<<v20-3-29,29>>^ Não maquines o mal contra o teu próximo, que habita contigo confiadamente.

[[v20-3-30]]

^<<v20-3-30,30>>^ Não contendas com um homem, sem motivo, não te havendo ele feito o mal.

[[v20-3-31]]

^<<v20-3-31,31>>^ Não tenhas inveja do homem violento, nem escolhas nenhum de seus caminhos.

[[v20-3-32]]

^<<v20-3-32,32>>^ Porque o perverso é abominação para o Senhor, mas com os retos está o seu segredo.

[[v20-3-33]]

^<<v20-3-33,33>>^ A maldição do Senhor habita na casa do ímpio, mas ele abençoa a habitação dos justos.

[[v20-3-34]]

^<<v20-3-34,34>>^ Ele escarnece dos escarnecedores, mas dá graça aos humildes.

[[v20-3-35]]

^<<v20-3-35,35>>^ Os sábios herdarão honra, mas a exaltação dos loucos se converte em ignomínia.

'''

xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[&#60; Capítulo Anterior] | <<v20-3-0,Topo>> | xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[Próximo Capítulo &#62;]