include::./index.adoc[]

[[v20-14-0]]
=== Provérbios, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-14-1]]

^<<v20-14-1,1>>^ Toda mulher sábia edifica a sua casa; a insensata, porém, derruba-a com as suas mãos.

[[v20-14-2]]

^<<v20-14-2,2>>^ Quem anda na sua retidão teme ao Senhor; mas aquele que é perverso nos seus caminhos despreza-o.

[[v20-14-3]]

^<<v20-14-3,3>>^ Na boca do tolo está a vara da soberba, mas os lábios do sábio preservá-lo-ão.

[[v20-14-4]]

^<<v20-14-4,4>>^ Onde não há bois, a manjedoura está vazia; mas pela força do boi há abundância de colheitas.

[[v20-14-5]]

^<<v20-14-5,5>>^ A testemunha verdadeira não mentirá; a testemunha falsa, porém, se desboca em mentiras.

[[v20-14-6]]

^<<v20-14-6,6>>^ O escarnecedor busca sabedoria, e não a encontra; mas para o prudente o conhecimento é fácil.

[[v20-14-7]]

^<<v20-14-7,7>>^ Vai-te da presença do homem insensato, pois nele não acharás palavras de ciência.

[[v20-14-8]]

^<<v20-14-8,8>>^ A sabedoria do prudente é entender o seu caminho; porém a estultícia dos tolos é enganar.

[[v20-14-9]]

^<<v20-14-9,9>>^ A culpa zomba dos insensatos; mas os retos têm o favor de Deus.

[[v20-14-10]]

^<<v20-14-10,10>>^ O coração conhece a sua própria amargura; e o estranho não participa da sua alegria.

[[v20-14-11]]

^<<v20-14-11,11>>^ A casa dos ímpios se desfará; porém a tenda dos retos florescerá.

[[v20-14-12]]

^<<v20-14-12,12>>^ Há um caminho que ao homem parece direito, mas o fim dele conduz à morte.

[[v20-14-13]]

^<<v20-14-13,13>>^ Até no riso terá dor o coração; e o fim da alegria é tristeza.

[[v20-14-14]]

^<<v20-14-14,14>>^ Dos seus próprios caminhos se fartará o infiel de coração, como também o homem bom se contentará dos seus.

[[v20-14-15]]

^<<v20-14-15,15>>^ O simples dá crédito a tudo; mas o prudente atenta para os seus passos.

[[v20-14-16]]

^<<v20-14-16,16>>^ O sábio teme e desvia-se do mal, mas o tolo é arrogante e dá-se por seguro.

[[v20-14-17]]

^<<v20-14-17,17>>^ Quem facilmente se ira fará doidices; mas o homem discreto é paciente;

[[v20-14-18]]

^<<v20-14-18,18>>^ Os simples herdam a estultícia; mas os prudentes se coroam de conhecimento.

[[v20-14-19]]

^<<v20-14-19,19>>^ Os maus inclinam-se perante os bons; e os ímpios diante das portas dos justos.

[[v20-14-20]]

^<<v20-14-20,20>>^ O pobre é odiado até pelo seu vizinho; mas os amigos dos ricos são muitos.

[[v20-14-21]]

^<<v20-14-21,21>>^ O que despreza ao seu vizinho peca; mas feliz é aquele que se compadece dos pobres.

[[v20-14-22]]

^<<v20-14-22,22>>^ Porventura não erram os que maquinam o mal? mas há beneficência e fidelidade para os que planejam o bem.

[[v20-14-23]]

^<<v20-14-23,23>>^ Em todo trabalho há proveito; meras palavras, porém, só encaminham para a penúria.

[[v20-14-24]]

^<<v20-14-24,24>>^ A coroa dos sábios é a sua riqueza; porém a estultícia dos tolos não passa de estultícia.

[[v20-14-25]]

^<<v20-14-25,25>>^ A testemunha verdadeira livra as almas; mas o que fala mentiras é traidor.

[[v20-14-26]]

^<<v20-14-26,26>>^ No temor do Senhor há firme confiança; e os seus filhos terão um lugar de refúgio.

[[v20-14-27]]

^<<v20-14-27,27>>^ O temor do Senhor é uma fonte de vida, para o homem se desviar dos laços da morte.

[[v20-14-28]]

^<<v20-14-28,28>>^ Na multidão do povo está a glória do rei; mas na falta de povo está a ruína do príncipe.

[[v20-14-29]]

^<<v20-14-29,29>>^ Quem é tardio em irar-se é grande em entendimento; mas o que é de ânimo precipitado exalta a loucura.

[[v20-14-30]]

^<<v20-14-30,30>>^ O coração tranqüilo é a vida da carne; a inveja, porém, é a podridão dos ossos.

[[v20-14-31]]

^<<v20-14-31,31>>^ O que oprime ao pobre insulta ao seu Criador; mas honra-o aquele que se compadece do necessitado.

[[v20-14-32]]

^<<v20-14-32,32>>^ O ímpio é derrubado pela sua malícia; mas o justo até na sua morte acha refúgio.

[[v20-14-33]]

^<<v20-14-33,33>>^ No coração do prudente repousa a sabedoria; mas no coração dos tolos não é conhecida.

[[v20-14-34]]

^<<v20-14-34,34>>^ A justiça exalta as nações; mas o pecado é o opróbrio dos povos.

[[v20-14-35]]

^<<v20-14-35,35>>^ O favor do rei é concedido ao servo que procede sabiamente; mas sobre o que procede indignamente cairá o seu furor.

'''

xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[&#60; Capítulo Anterior] | <<v20-14-0,Topo>> | xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[Próximo Capítulo &#62;]