include::./index.adoc[]

[[v20-31-0]]
=== Provérbios, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-31-1]]

^<<v20-31-1,1>>^ As palavras do rei Lemuel, rei de Massá, que lhe ensinou sua mãe.

[[v20-31-2]]

^<<v20-31-2,2>>^ Que te direi, filho meu? e que te direi, ó filho do meu ventre? e que te direi, ó filho dos meus votos?

[[v20-31-3]]

^<<v20-31-3,3>>^ Não dês às mulheres a tua força, nem os teus caminhos às que destroem os reis.

[[v20-31-4]]

^<<v20-31-4,4>>^ Não é dos reis, ó Lemuel, não é dos reis beber vinho, nem dos príncipes desejar bebida forte;

[[v20-31-5]]

^<<v20-31-5,5>>^ para que não bebam, e se esqueçam da lei, e pervertam o direito de quem anda aflito.

[[v20-31-6]]

^<<v20-31-6,6>>^ Dai bebida forte ao que está para perecer, e o vinho ao que está em amargura de espírito.

[[v20-31-7]]

^<<v20-31-7,7>>^ Bebam e se esqueçam da sua pobreza, e da sua miséria não se lembrem mais.

[[v20-31-8]]

^<<v20-31-8,8>>^ Abre a tua boca a favor do mudo, a favor do direito de todos os desamparados.

[[v20-31-9]]

^<<v20-31-9,9>>^ Abre a tua boca; julga retamente, e faze justiça aos pobres e aos necessitados.

[[v20-31-10]]

^<<v20-31-10,10>>^ Álefe. Mulher virtuosa, quem a pode achar? Pois o seu valor muito excede ao de jóias preciosas.

[[v20-31-11]]

^<<v20-31-11,11>>^ Bete. O coração do seu marido confia nela, e não lhe haverá falta de lucro.

[[v20-31-12]]

^<<v20-31-12,12>>^ Guímel. Ela lhe faz bem, e não mal, todos os dias da sua vida.

[[v20-31-13]]

^<<v20-31-13,13>>^ Dálete. Ela busca lã e linho, e trabalha de boa vontade com as mãos.

[[v20-31-14]]

^<<v20-31-14,14>>^ Hê. É como os navios do negociante; de longe traz o seu pão.

[[v20-31-15]]

^<<v20-31-15,15>>^ Vave. E quando ainda está escuro, ela se levanta, e dá mantimento à sua casa, e a tarefa às suas servas.

[[v20-31-16]]

^<<v20-31-16,16>>^ Zaine. Considera um campo, e compra-o; planta uma vinha com o fruto de suas mãos.

[[v20-31-17]]

^<<v20-31-17,17>>^ Hete. Cinge os seus lombos de força, e fortalece os seus braços.

[[v20-31-18]]

^<<v20-31-18,18>>^ Tete. Prova e vê que é boa a sua mercadoria; e a sua lâmpada não se apaga de noite.

[[v20-31-19]]

^<<v20-31-19,19>>^ Iode. Estende as mãos ao fuso, e as suas mãos pegam na roca.

[[v20-31-20]]

^<<v20-31-20,20>>^ Cafe. Abre a mão para o pobre; sim, ao necessitado estende as suas mãos.

[[v20-31-21]]

^<<v20-31-21,21>>^ Lâmede. Não tem medo da neve pela sua família; pois todos os da sua casa estão vestidos de escarlate.

[[v20-31-22]]

^<<v20-31-22,22>>^ Meme. Faz para si cobertas; de linho fino e de púrpura é o seu vestido.

[[v20-31-23]]

^<<v20-31-23,23>>^ Nune. Conhece-se o seu marido nas portas, quando se assenta entre os anciãos da terra.

[[v20-31-24]]

^<<v20-31-24,24>>^ Sâmerue. Faz vestidos de linho, e vende-os, e entrega cintas aos mercadores.

[[v20-31-25]]

^<<v20-31-25,25>>^ Aine. A força e a dignidade são os seus vestidos; e ri-se do tempo vindouro.

[[v20-31-26]]

^<<v20-31-26,26>>^ Pê. Abre a sua boca com sabedoria, e o ensino da benevolência está na sua língua.

[[v20-31-27]]

^<<v20-31-27,27>>^ Tsadê. Olha pelo governo de sua casa, e não come o pão da preguiça.

[[v20-31-28]]

^<<v20-31-28,28>>^ Côfe. Levantam-se seus filhos, e lhe chamam bem-aventurada, como também seu marido, que a louva, dizendo:

[[v20-31-29]]

^<<v20-31-29,29>>^ Reche. Muitas mulheres têm procedido virtuosamente, mas tu a todas sobrepujas.

[[v20-31-30]]

^<<v20-31-30,30>>^ Chine. Enganosa é a graça, e vã é a formosura; mas a mulher que teme ao Senhor, essa será louvada.

[[v20-31-31]]

^<<v20-31-31,31>>^ Tau. Dai-lhe do fruto das suas mãos, e louvem-na nas portas as suas obras.

'''

xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[&#60; Capítulo Anterior] | <<v20-31-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[Próximo Capítulo &#62;]