include::./index.adoc[]

[[v20-18-0]]
=== Provérbios, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-18-1]]

^<<v20-18-1,1>>^ Aquele que vive isolado busca seu próprio desejo; insurge-se contra a verdadeira sabedoria.

[[v20-18-2]]

^<<v20-18-2,2>>^ O tolo não toma prazer no entendimento, mas tão somente em revelar a sua opinião.

[[v20-18-3]]

^<<v20-18-3,3>>^ Quando vem o ímpio, vem também o desprezo; e com a desonra vem o opróbrio.

[[v20-18-4]]

^<<v20-18-4,4>>^ Águas profundas são as palavras da boca do homem; e a fonte da sabedoria é um ribeiro que corre.

[[v20-18-5]]

^<<v20-18-5,5>>^ Não é bom ter respeito à pessoa do ímpio, nem privar o justo do seu direito.

[[v20-18-6]]

^<<v20-18-6,6>>^ Os lábios do tolo entram em contendas, e a sua boca clama por açoites.

[[v20-18-7]]

^<<v20-18-7,7>>^ A boca do tolo é a sua própria destruição, e os seus lábios um laço para a sua alma.

[[v20-18-8]]

^<<v20-18-8,8>>^ As palavras do difamador são como bocados doces, que penetram até o íntimo das entranhas.

[[v20-18-9]]

^<<v20-18-9,9>>^ Aquele que é remisso na sua obra é irmão do que é destruidor.

[[v20-18-10]]

^<<v20-18-10,10>>^ Torre forte é o nome do Senhor; para ela corre o justo, e está seguro.

[[v20-18-11]]

^<<v20-18-11,11>>^ Os bens do rico são a sua cidade forte, e como um muro alto na sua imaginação.

[[v20-18-12]]

^<<v20-18-12,12>>^ Antes da ruína eleva-se o coração do homem; e adiante da honra vai a humildade.

[[v20-18-13]]

^<<v20-18-13,13>>^ Responder antes de ouvir, é estultícia e vergonha.

[[v20-18-14]]

^<<v20-18-14,14>>^ O espírito do homem o sustentará na sua enfermidade; mas ao espírito abatido quem o levantará?

[[v20-18-15]]

^<<v20-18-15,15>>^ O coração do entendido adquire conhecimento; e o ouvido dos sábios busca conhecimento;

[[v20-18-16]]

^<<v20-18-16,16>>^ O presente do homem alarga-lhe o caminho, e leva-o à presença dos grandes.

[[v20-18-17]]

^<<v20-18-17,17>>^ O que primeiro começa o seu pleito parece justo; até que vem o outro e o examina.

[[v20-18-18]]

^<<v20-18-18,18>>^ A sorte faz cessar os pleitos, e decide entre os poderosos.

[[v20-18-19]]

^<<v20-18-19,19>>^ um irmão ajudado pelo irmão é como uma cidade fortificada; é forte como os ferrolhos dum castelo.

[[v20-18-20]]

^<<v20-18-20,20>>^ O homem se fartará do fruto da sua boca; dos renovos dos seus lábios se fartará.

[[v20-18-21]]

^<<v20-18-21,21>>^ A morte e a vida estão no poder da língua; e aquele que a ama comerá do seu fruto.

[[v20-18-22]]

^<<v20-18-22,22>>^ Quem encontra uma esposa acha uma coisa boa; e alcança o favor do Senhor.

[[v20-18-23]]

^<<v20-18-23,23>>^ O pobre fala com rogos; mas o rico responde com durezas.

[[v20-18-24]]

^<<v20-18-24,24>>^ O homem que tem muitos amigos, tem-nos para a sua ruína; mas há um amigo que é mais chegado do que um irmão.

'''

xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[Próximo Capítulo &#62;]