include::./index.adoc[]

[[v20-15-0]]
=== Provérbios, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-15-1]]

^<<v20-15-1,1>>^ A resposta branda desvia o furor, mas a palavra dura suscita a ira.

[[v20-15-2]]

^<<v20-15-2,2>>^ A língua dos sábios destila o conhecimento; porém a boca dos tolos derrama a estultícia.

[[v20-15-3]]

^<<v20-15-3,3>>^ Os olhos do Senhor estão em todo lugar, vigiando os maus e os bons.

[[v20-15-4]]

^<<v20-15-4,4>>^ Uma língua suave é árvore de vida; mas a língua perversa quebranta o espírito.

[[v20-15-5]]

^<<v20-15-5,5>>^ O insensato despreza a correção e seu pai; mas o que atende à admoestação prudentemente se haverá.

[[v20-15-6]]

^<<v20-15-6,6>>^ Na casa do justo há um grande tesouro; mas nos lucros do ímpio há perturbação.

[[v20-15-7]]

^<<v20-15-7,7>>^ Os lábios dos sábios difundem conhecimento; mas não o faz o coração dos tolos.

[[v20-15-8]]

^<<v20-15-8,8>>^ O sacrifício dos ímpios é abominável ao Senhor; mas a oração dos retos lhe é agradável.

[[v20-15-9]]

^<<v20-15-9,9>>^ O caminho do ímpio é abominável ao Senhor; mas ele ama ao que segue a justiça.

[[v20-15-10]]

^<<v20-15-10,10>>^ Há disciplina severa para o que abandona a vereda; e o que aborrece a repreensão morrerá.

[[v20-15-11]]

^<<v20-15-11,11>>^ O Seol e o Abadom estão abertos perante o Senhor; quanto mais o coração dos filhos dos homens!

[[v20-15-12]]

^<<v20-15-12,12>>^ O escarnecedor não gosta daquele que o repreende; não irá ter com os sábios.

[[v20-15-13]]

^<<v20-15-13,13>>^ O coração alegre aformoseia o rosto; mas pela dor do coração o espírito se abate.

[[v20-15-14]]

^<<v20-15-14,14>>^ O coração do inteligente busca o conhecimento; mas a boca dos tolos se apascenta de estultícia.

[[v20-15-15]]

^<<v20-15-15,15>>^ Todos os dias do aflito são maus; mas o coração contente tem um banquete contínuo.

[[v20-15-16]]

^<<v20-15-16,16>>^ Melhor é o pouco com o temor do Senhor, do que um grande tesouro, e com ele a inquietação.

[[v20-15-17]]

^<<v20-15-17,17>>^ Melhor é um prato de hortaliça, onde há amor, do que o boi gordo, e com ele o ódio.

[[v20-15-18]]

^<<v20-15-18,18>>^ O homem iracundo suscita contendas; mas o longânimo apazigua a luta.

[[v20-15-19]]

^<<v20-15-19,19>>^ O caminho do preguiçoso é como a sebe de espinhos; porém a vereda dos justos é uma estrada real.

[[v20-15-20]]

^<<v20-15-20,20>>^ O filho sábio alegra a seu pai; mas o homem insensato despreza a sua mãe.

[[v20-15-21]]

^<<v20-15-21,21>>^ A estultícia é alegria para o insensato; mas o homem de entendimento anda retamente.

[[v20-15-22]]

^<<v20-15-22,22>>^ Onde não há conselho, frustram-se os projetos; mas com a multidão de conselheiros se estabelecem.

[[v20-15-23]]

^<<v20-15-23,23>>^ O homem alegra-se em dar uma resposta adequada; e a palavra a seu tempo quão boa é!

[[v20-15-24]]

^<<v20-15-24,24>>^ Para o sábio o caminho da vida é para cima, a fim de que ele se desvie do Seol que é em baixo.

[[v20-15-25]]

^<<v20-15-25,25>>^ O Senhor desarraiga a casa dos soberbos, mas estabelece a herança da viúva.

[[v20-15-26]]

^<<v20-15-26,26>>^ Os desígnios dos maus são abominação para o Senhor; mas as palavras dos limpos lhe são aprazíveis.

[[v20-15-27]]

^<<v20-15-27,27>>^ O que se dá à cobiça perturba a sua própria casa; mas o que aborrece a peita viverá.

[[v20-15-28]]

^<<v20-15-28,28>>^ O coração do justo medita no que há de responder; mas a boca dos ímpios derrama coisas más.

[[v20-15-29]]

^<<v20-15-29,29>>^ Longe está o Senhor dos ímpios, mas ouve a oração dos justos.

[[v20-15-30]]

^<<v20-15-30,30>>^ A luz dos olhos alegra o coração, e boas-novas engordam os ossos.

[[v20-15-31]]

^<<v20-15-31,31>>^ O ouvido que escuta a advertência da vida terá a sua morada entre os sábios.

[[v20-15-32]]

^<<v20-15-32,32>>^ Quem rejeita a correção menospreza a sua alma; mas aquele que escuta a advertência adquire entendimento.

[[v20-15-33]]

^<<v20-15-33,33>>^ O temor do Senhor é a instrução da sabedoria; e adiante da honra vai a humildade.

'''

xref:020-proverbios/020-proverbios-014.adoc#v20-14-0[&#60; Capítulo Anterior] | <<v20-15-0,Topo>> | xref:020-proverbios/020-proverbios-016.adoc#v20-16-0[Próximo Capítulo &#62;]