include::./index.adoc[]

[[v20-4-0]]
=== Provérbios, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-4-1]]

^<<v20-4-1,1>>^ Ouvi, filhos, a instrução do pai, e estai atentos para conhecerdes o entendimento.

[[v20-4-2]]

^<<v20-4-2,2>>^ Pois eu vos dou boa doutrina; não abandoneis o meu ensino.

[[v20-4-3]]

^<<v20-4-3,3>>^ Quando eu era filho aos pés de meu, pai, tenro e único em estima diante de minha mãe,

[[v20-4-4]]

^<<v20-4-4,4>>^ ele me ensinava, e me dizia: Retenha o teu coração as minhas palavras; guarda os meus mandamentos, e vive.

[[v20-4-5]]

^<<v20-4-5,5>>^ Adquire a sabedoria, adquire o entendimento; não te esqueças nem te desvies das palavras da minha boca.

[[v20-4-6]]

^<<v20-4-6,6>>^ Não a abandones, e ela te guardará; ama-a, e ela te preservará.

[[v20-4-7]]

^<<v20-4-7,7>>^ A sabedoria é a coisa principal; adquire, pois, a sabedoria; sim, com tudo o que possuis adquire o entendimento.

[[v20-4-8]]

^<<v20-4-8,8>>^ Estima-a, e ela te exaltará; se a abraçares, ela te honrará.

[[v20-4-9]]

^<<v20-4-9,9>>^ Ela dará à tua cabeça uma grinalda de graça; e uma coroa de glória te entregará.

[[v20-4-10]]

^<<v20-4-10,10>>^ Ouve, filho meu, e aceita as minhas palavras, para que se multipliquem os anos da tua vida.

[[v20-4-11]]

^<<v20-4-11,11>>^ Eu te ensinei o caminho da sabedoria; guiei-te pelas veredas da retidão.

[[v20-4-12]]

^<<v20-4-12,12>>^ Quando andares, não se embaraçarão os teus passos; e se correres, não tropeçarás.

[[v20-4-13]]

^<<v20-4-13,13>>^ Apega-te à instrução e não a largues; guarda-a, porque ela é a tua vida.

[[v20-4-14]]

^<<v20-4-14,14>>^ Não entres na vereda dos ímpios, nem andes pelo caminho dos maus.

[[v20-4-15]]

^<<v20-4-15,15>>^ Evita-o, não passes por ele; desvia-te dele e passa de largo.

[[v20-4-16]]

^<<v20-4-16,16>>^ Pois não dormem, se não fizerem o mal, e foge deles o sono se não fizerem tropeçar alguém.

[[v20-4-17]]

^<<v20-4-17,17>>^ Porque comem o pão da impiedade, e bebem o vinho da violência.

[[v20-4-18]]

^<<v20-4-18,18>>^ Mas a vereda dos justos é como a luz da aurora que vai brilhando mais e mais até ser dia perfeito.

[[v20-4-19]]

^<<v20-4-19,19>>^ O caminho dos ímpios é como a escuridão: não sabem eles em que tropeçam.

[[v20-4-20]]

^<<v20-4-20,20>>^ Filho meu, atenta para as minhas palavras; inclina o teu ouvido às minhas instruções.

[[v20-4-21]]

^<<v20-4-21,21>>^ Não se apartem elas de diante dos teus olhos; guarda-as dentro do teu coração.

[[v20-4-22]]

^<<v20-4-22,22>>^ Porque são vida para os que as encontram, e saúde para todo o seu corpo.

[[v20-4-23]]

^<<v20-4-23,23>>^ Guarda com toda a diligência o teu coração, porque dele procedem as fontes da vida.

[[v20-4-24]]

^<<v20-4-24,24>>^ Desvia de ti a malignidade da boca, e alonga de ti a perversidade dos lábios.

[[v20-4-25]]

^<<v20-4-25,25>>^ Dirijam-se os teus olhos para a frente, e olhem as tuas pálpebras diretamente diante de ti.

[[v20-4-26]]

^<<v20-4-26,26>>^ Pondera a vereda de teus pés, e serão seguros todos os teus caminhos.

[[v20-4-27]]

^<<v20-4-27,27>>^ Não declines nem para a direita nem para a esquerda; retira o teu pé do mal.

'''

xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[&#60; Capítulo Anterior] | <<v20-4-0,Topo>> | xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[Próximo Capítulo &#62;]