include::./index.adoc[]

[[v20-20-0]]
=== Provérbios, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-20-1]]

^<<v20-20-1,1>>^ O vinho é escarnecedor, e a bebida forte alvoroçadora; e todo aquele que neles errar não e sábio.

[[v20-20-2]]

^<<v20-20-2,2>>^ Como o bramido do leão é o terror do rei; quem o provoca a ira peca contra a sua própria vida.

[[v20-20-3]]

^<<v20-20-3,3>>^ Honroso é para o homem o desviar-se de questões; mas todo insensato se entremete nelas.

[[v20-20-4]]

^<<v20-20-4,4>>^ O preguiçoso não lavra no outono; pelo que mendigará na sega, e nada receberá.

[[v20-20-5]]

^<<v20-20-5,5>>^ Como águas profundas é o propósito no coração do homem; mas o homem inteligente o descobrirá.

[[v20-20-6]]

^<<v20-20-6,6>>^ Muitos há que proclamam a sua própria bondade; mas o homem fiel, quem o achará?

[[v20-20-7]]

^<<v20-20-7,7>>^ O justo anda na sua integridade; bem-aventurados serão os seus filhos depois dele.

[[v20-20-8]]

^<<v20-20-8,8>>^ Assentando-se o rei no trono do juízo, com os seus olhos joeira a todo malfeitor.

[[v20-20-9]]

^<<v20-20-9,9>>^ Quem pode dizer: Purifiquei o meu coração, limpo estou de meu pecado?

[[v20-20-10]]

^<<v20-20-10,10>>^ O peso fraudulento e a medida falsa são abominação ao Senhor, tanto uma como outra coisa.

[[v20-20-11]]

^<<v20-20-11,11>>^ Até a criança se dá a conhecer pelas suas ações, se a sua conduta é pura e reta.

[[v20-20-12]]

^<<v20-20-12,12>>^ O ouvido que ouve, e o olho que vê, o Senhor os fez a ambos.

[[v20-20-13]]

^<<v20-20-13,13>>^ Não ames o sono, para que não empobreças; abre os teus olhos, e te fartarás de pão.

[[v20-20-14]]

^<<v20-20-14,14>>^ Nada vale, nada vale, diz o comprador; mas, depois de retirar-se, então se gaba.

[[v20-20-15]]

^<<v20-20-15,15>>^ Há ouro e abundância de pedras preciosas; mas os lábios do conhecimento são jóia de grande valor.

[[v20-20-16]]

^<<v20-20-16,16>>^ Tira a roupa àquele que fica por fiador do estranho; e toma penhor daquele que se obriga por estrangeiros.

[[v20-20-17]]

^<<v20-20-17,17>>^ Suave é ao homem o pão da mentira; mas depois a sua boca se enche de pedrinhas.

[[v20-20-18]]

^<<v20-20-18,18>>^ Os projetos se confirmam pelos conselhos; assim, pois, com prudência faze a guerra.

[[v20-20-19]]

^<<v20-20-19,19>>^ O que anda mexericando revela segredos; pelo que não te metas com quem muito abre os seus lábios.

[[v20-20-20]]

^<<v20-20-20,20>>^ O que amaldiçoa a seu pai ou a sua mãe, apagar-se-lhe-á a sua lâmpada nas, mais densas trevas.

[[v20-20-21]]

^<<v20-20-21,21>>^ A herança que no princípio é adquirida às pressas, não será abençoada no seu fim.

[[v20-20-22]]

^<<v20-20-22,22>>^ Não digas: vingar-me-ei do mal; espera pelo Senhor e ele te livrará.

[[v20-20-23]]

^<<v20-20-23,23>>^ Pesos fraudulentos são abomináveis ao Senhor; e balanças enganosas não são boas.

[[v20-20-24]]

^<<v20-20-24,24>>^ Os passos do homem são dirigidos pelo Senhor; como, pois, poderá o homem entender o seu caminho?

[[v20-20-25]]

^<<v20-20-25,25>>^ Laço é para o homem dizer precipitadamente: É santo; e, feitos os votos, então refletir.

[[v20-20-26]]

^<<v20-20-26,26>>^ O rei sábio joeira os ímpios e faz girar sobre eles a roda.

[[v20-20-27]]

^<<v20-20-27,27>>^ O espírito do homem é a lâmpada do Senhor, a qual esquadrinha todo o mais íntimo do coração.

[[v20-20-28]]

^<<v20-20-28,28>>^ A benignidade e a verdade guardam o rei; e com a benignidade sustém ele o seu trono.

[[v20-20-29]]

^<<v20-20-29,29>>^ A glória dos jovens é a sua força; e a beleza dos velhos são as cãs.

[[v20-20-30]]

^<<v20-20-30,30>>^ Os açoites que ferem purificam do mal; e as feridas penetram até o mais íntimo do corpo.

'''

xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[&#60; Capítulo Anterior] | <<v20-20-0,Topo>> | xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[Próximo Capítulo &#62;]