include::./index.adoc[]

[[v20-9-0]]
=== Provérbios, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-9-1]]

^<<v20-9-1,1>>^ A sabedoria já edificou a sua casa, já lavrou as suas sete colunas;

[[v20-9-2]]

^<<v20-9-2,2>>^ já imolou as suas vítimas, misturou o seu vinho, e preparou a sua mesa.

[[v20-9-3]]

^<<v20-9-3,3>>^ Já enviou as suas criadas a clamar sobre as alturas da cidade, dizendo:

[[v20-9-4]]

^<<v20-9-4,4>>^ Quem é simples, volte-se para cá. Aos faltos de entendimento diz:

[[v20-9-5]]

^<<v20-9-5,5>>^ Vinde, comei do meu pão, e bebei do vinho que tenho misturado.

[[v20-9-6]]

^<<v20-9-6,6>>^ Deixai a insensatez, e vivei; e andai pelo caminho do entendimento.

[[v20-9-7]]

^<<v20-9-7,7>>^ O que repreende ao escarnecedor, traz afronta sobre si; e o que censura ao ímpio, recebe a sua mancha.

[[v20-9-8]]

^<<v20-9-8,8>>^ Não repreendas ao escarnecedor, para que não te odeie; repreende ao sábio, e amar-te-á.

[[v20-9-9]]

^<<v20-9-9,9>>^ Instrui ao sábio, e ele se fará mais, sábio; ensina ao justo, e ele crescerá em entendimento.

[[v20-9-10]]

^<<v20-9-10,10>>^ O temor do Senhor é o princípio sabedoria; e o conhecimento do Santo é o entendimento.

[[v20-9-11]]

^<<v20-9-11,11>>^ Porque por mim se multiplicam os teus dias, e anos de vida se te acrescentarão.

[[v20-9-12]]

^<<v20-9-12,12>>^ Se fores sábio, para ti mesmo o serás; e, se fores escarnecedor, tu só o suportarás.

[[v20-9-13]]

^<<v20-9-13,13>>^ A mulher tola é alvoroçadora; é insensata, e não conhece o pudor.

[[v20-9-14]]

^<<v20-9-14,14>>^ Senta-se à porta da sua casa ou numa cadeira, nas alturas da cidade,

[[v20-9-15]]

^<<v20-9-15,15>>^ chamando aos que passam e seguem direitos o seu caminho:

[[v20-9-16]]

^<<v20-9-16,16>>^ Quem é simples, volte-se para cá! E aos faltos de entendimento diz:

[[v20-9-17]]

^<<v20-9-17,17>>^ As águas roubadas são doces, e o pão comido às ocultas é agradável.

[[v20-9-18]]

^<<v20-9-18,18>>^ Mas ele não sabe que ali estão os mortos; que os seus convidados estão nas profundezas do Seol.

'''

xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[&#60; Capítulo Anterior] | <<v20-9-0,Topo>> | xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[Próximo Capítulo &#62;]