include::./index.adoc[]

[[v20-11-0]]
=== Provérbios, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-11-1]]

^<<v20-11-1,1>>^ A balança enganosa é abominação para o Senhor; mas o peso justo é o seu prazer.

[[v20-11-2]]

^<<v20-11-2,2>>^ Quando vem a soberba, então vem a desonra; mas com os humildes está a sabedoria.

[[v20-11-3]]

^<<v20-11-3,3>>^ A integridade dos retos os guia; porém a perversidade dos desleais os destrói.

[[v20-11-4]]

^<<v20-11-4,4>>^ De nada aproveitam as riquezas no dia da ira; porém a justiça livra da morte.

[[v20-11-5]]

^<<v20-11-5,5>>^ A justiça dos perfeitos endireita o seu caminho; mas o ímpio cai pela sua impiedade.

[[v20-11-6]]

^<<v20-11-6,6>>^ A justiça dos retos os livra; mas os traiçoeiros são apanhados nas, suas próprias cobiças.

[[v20-11-7]]

^<<v20-11-7,7>>^ Morrendo o ímpio, perece a sua esperança; e a expectativa da iniqüidade.

[[v20-11-8]]

^<<v20-11-8,8>>^ O justo é libertado da angústia; e o ímpio fica em seu lugar.

[[v20-11-9]]

^<<v20-11-9,9>>^ O hipócrita com a boca arruina o seu próximo; mas os justos são libertados pelo conhecimento.

[[v20-11-10]]

^<<v20-11-10,10>>^ Quando os justos prosperam, exulta a cidade; e quando perecem os ímpios, há júbilo.

[[v20-11-11]]

^<<v20-11-11,11>>^ Pela bênção dos retos se exalta a cidade; mas pela boca dos ímpios é derrubada.

[[v20-11-12]]

^<<v20-11-12,12>>^ Quem despreza o seu próximo é falto de senso; mas o homem de entendimento se cala.

[[v20-11-13]]

^<<v20-11-13,13>>^ O que anda mexericando revela segredos; mas o fiel de espírito encobre o negócio.

[[v20-11-14]]

^<<v20-11-14,14>>^ Quando não há sábia direção, o povo cai; mas na multidão de conselheiros há segurança.

[[v20-11-15]]

^<<v20-11-15,15>>^ Decerto sofrerá prejuízo aquele que fica por fiador do estranho; mas o que aborrece a fiança estará seguro.

[[v20-11-16]]

^<<v20-11-16,16>>^ A mulher aprazível obtém honra, e os homens violentos obtêm riquezas.

[[v20-11-17]]

^<<v20-11-17,17>>^ O homem bondoso faz bem à sua, própria alma; mas o cruel faz mal a si mesmo.

[[v20-11-18]]

^<<v20-11-18,18>>^ O ímpio recebe um salário ilusório; mas o que semeia justiça recebe galardão seguro.

[[v20-11-19]]

^<<v20-11-19,19>>^ Quem é fiel na retidão encaminha, para a vida, e aquele que segue o mal encontra a morte.

[[v20-11-20]]

^<<v20-11-20,20>>^ Abominação para o Senhor são os perversos de coração; mas os que são perfeitos em seu caminho são o seu deleite.

[[v20-11-21]]

^<<v20-11-21,21>>^ Decerto o homem mau não ficará sem castigo; porém a descendência dos justos será livre.

[[v20-11-22]]

^<<v20-11-22,22>>^ Como jóia de ouro em focinho de porca, assim é a mulher formosa que se aparta da discrição.

[[v20-11-23]]

^<<v20-11-23,23>>^ O desejo dos justos é somente o bem; porém a expectativa dos ímpios é a ira.

[[v20-11-24]]

^<<v20-11-24,24>>^ Um dá liberalmente, e se torna mais rico; outro retém mais do que é justo, e se empobrece.

[[v20-11-25]]

^<<v20-11-25,25>>^ A alma generosa prosperará, e o que regar também será regado.

[[v20-11-26]]

^<<v20-11-26,26>>^ Ao que retém o trigo o povo o amaldiçoa; mas bênção haverá sobre a cabeça do que o vende.

[[v20-11-27]]

^<<v20-11-27,27>>^ O que busca diligentemente o bem, busca favor; mas ao que procura o mal, este lhe sobrevirá.

[[v20-11-28]]

^<<v20-11-28,28>>^ Aquele que confia nas suas riquezas, cairá; mas os justos reverdecerão como a folhagem.

[[v20-11-29]]

^<<v20-11-29,29>>^ O que perturba a sua casa herdará o vento; e o insensato será servo do entendido de coração.

[[v20-11-30]]

^<<v20-11-30,30>>^ O fruto do justo é árvore de vida; e o que ganha almas sábio é.

[[v20-11-31]]

^<<v20-11-31,31>>^ Eis que o justo é castigado na terra; quanto mais o ímpio e o pecador!

'''

xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[Próximo Capítulo &#62;]