include::./index.adoc[]

[[v20-1-0]]
=== Provérbios, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v20-1-1]]

^<<v20-1-1,1>>^ Provérbios de Salomão, filho de Davi, rei de Israel:

[[v20-1-2]]

^<<v20-1-2,2>>^ Para se conhecer a sabedoria e a instrução; para se entenderem as palavras de inteligência;

[[v20-1-3]]

^<<v20-1-3,3>>^ para se instruir em sábio procedimento, em retidão, justiça e eqüidade;

[[v20-1-4]]

^<<v20-1-4,4>>^ para se dar aos simples prudência, e aos jovens conhecimento e bom siso.

[[v20-1-5]]

^<<v20-1-5,5>>^ Ouça também, o sábio e cresça em ciência, e o entendido adquira habilidade,

[[v20-1-6]]

^<<v20-1-6,6>>^ para entender provérbios e parábolas, as palavras dos sábios, e seus enigmas.

[[v20-1-7]]

^<<v20-1-7,7>>^ O temor do Senhor é o princípio do conhecimento; mas os insensatos desprezam a sabedoria e a instrução.

[[v20-1-8]]

^<<v20-1-8,8>>^ Filho meu, ouve a instrução de teu pai, e não deixes o ensino de tua mãe.

[[v20-1-9]]

^<<v20-1-9,9>>^ Porque eles serão uma grinalda de graça para a tua cabeça, e colares para o teu pescoço.

[[v20-1-10]]

^<<v20-1-10,10>>^ Filho meu, se os pecadores te quiserem seduzir, não consintas.

[[v20-1-11]]

^<<v20-1-11,11>>^ Se disserem: Vem conosco; embosquemo-nos para derramar sangue; espreitemos sem razão o inocente;

[[v20-1-12]]

^<<v20-1-12,12>>^ traguemo-los vivos, como o Seol, e inteiros como os que descem à cova;

[[v20-1-13]]

^<<v20-1-13,13>>^ acharemos toda sorte de bens preciosos; encheremos as nossas casas de despojos;

[[v20-1-14]]

^<<v20-1-14,14>>^ lançarás a tua sorte entre nós; teremos todos uma só bolsa;

[[v20-1-15]]

^<<v20-1-15,15>>^ filho meu, não andes no caminho com eles; guarda da sua vereda o teu pé,

[[v20-1-16]]

^<<v20-1-16,16>>^ porque os seus pés correm para o mal, e eles se apressam a derramar sangue.

[[v20-1-17]]

^<<v20-1-17,17>>^ Pois debalde se estende a rede à vista de qualquer ave.

[[v20-1-18]]

^<<v20-1-18,18>>^ Mas estes se põem em emboscadas contra o seu próprio sangue, e as suas próprias vidas espreitam.

[[v20-1-19]]

^<<v20-1-19,19>>^ Tais são as veredas de todo aquele que se entrega à cobiça; ela tira a vida dos que a possuem.

[[v20-1-20]]

^<<v20-1-20,20>>^ A suprema sabedoria altissonantemente clama nas ruas; nas praças levanta a sua voz.

[[v20-1-21]]

^<<v20-1-21,21>>^ Do alto dos muros clama; às entradas das portas e na cidade profere as suas palavras:

[[v20-1-22]]

^<<v20-1-22,22>>^ Até quando, ó estúpidos, amareis a estupidez? e até quando se deleitarão no escárnio os escarnecedores, e odiarão os insensatos o conhecimento?

[[v20-1-23]]

^<<v20-1-23,23>>^ Convertei-vos pela minha repreensão; eis que derramarei sobre vós o meu; espírito e vos farei saber as minhas palavras.

[[v20-1-24]]

^<<v20-1-24,24>>^ Mas, porque clamei, e vós recusastes; porque estendi a minha mão, e não houve quem desse atenção;

[[v20-1-25]]

^<<v20-1-25,25>>^ antes desprezastes todo o meu conselho, e não fizestes caso da minha repreensão;

[[v20-1-26]]

^<<v20-1-26,26>>^ também eu me rirei no dia da vossa calamidade; zombarei, quando sobrevier o vosso terror,

[[v20-1-27]]

^<<v20-1-27,27>>^ quando o terror vos sobrevier como tempestade, e a vossa calamidade passar como redemoinho, e quando vos sobrevierem aperto e angústia.

[[v20-1-28]]

^<<v20-1-28,28>>^ Então a mim clamarão, mas eu não responderei; diligentemente me buscarão, mas não me acharão.

[[v20-1-29]]

^<<v20-1-29,29>>^ Porquanto aborreceram o conhecimento, e não preferiram o temor do Senhor;

[[v20-1-30]]

^<<v20-1-30,30>>^ não quiseram o meu conselho e desprezaram toda a minha repreensão;

[[v20-1-31]]

^<<v20-1-31,31>>^ portanto comerão do fruto do seu caminho e se fartarão dos seus próprios conselhos.

[[v20-1-32]]

^<<v20-1-32,32>>^ Porque o desvio dos néscios os matará, e a prosperidade dos loucos os destruirá.

[[v20-1-33]]

^<<v20-1-33,33>>^ Mas o que me der ouvidos habitará em segurança, e estará tranqüilo, sem receio do mal.

'''

xref:019-salmos/019-salmos-150.adoc#v19-150-0[&#60; Capítulo Anterior] | <<v20-1-0,Topo>> | xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[Próximo Capítulo &#62;]