include::./index.adoc[]

[[v40-10-0]]
=== Mateus, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-10-1]]

^<<v40-10-1,1>>^ E, chamando a si os seus doze discípulos, deu-lhes autoridade sobre os espíritos imundos, para expulsarem, e para curarem toda sorte de doenças e enfermidades.

[[v40-10-2]]

^<<v40-10-2,2>>^ Ora, os nomes dos doze apóstolos são estes: primeiro, Simão, chamado Pedro, e André, seu irmão; Tiago, filho de Zebedeu, e João, seu irmão;

[[v40-10-3]]

^<<v40-10-3,3>>^ Felipe e Bartolomeu; Tomé e Mateus, o publicano; Tiago, filho de Alfeu, e Tadeu;

[[v40-10-4]]

^<<v40-10-4,4>>^ Simão Cananeu, e Judas Iscariotes, aquele que o traiu.

[[v40-10-5]]

^<<v40-10-5,5>>^ A estes doze enviou Jesus, e ordenou-lhes, dizendo: Não ireis aos gentios, nem entrareis em cidade de samaritanos;

[[v40-10-6]]

^<<v40-10-6,6>>^ mas ide antes às ovelhas perdidas da casa de Israel;

[[v40-10-7]]

^<<v40-10-7,7>>^ e indo, pregai, dizendo: É chegado o reino dos céus.

[[v40-10-8]]

^<<v40-10-8,8>>^ Curai os enfermos, ressuscitai os mortos, limpai os leprosos, expulsai os demônios; de graça recebestes, de graça dai.

[[v40-10-9]]

^<<v40-10-9,9>>^ Não vos provereis de ouro, nem de prata, nem de cobre, em vossos cintos;

[[v40-10-10]]

^<<v40-10-10,10>>^ nem de alforje para o caminho, nem de duas túnicas, nem de alparcas, nem de bordão; porque digno é o trabalhador do seu alimento.

[[v40-10-11]]

^<<v40-10-11,11>>^ Em qualquer cidade ou aldeia em que entrardes, procurai saber quem nela é digno, e hospedai-vos aí até que vos retireis.

[[v40-10-12]]

^<<v40-10-12,12>>^ E, ao entrardes na casa, saudai-a;

[[v40-10-13]]

^<<v40-10-13,13>>^ se a casa for digna, desça sobre ela a vossa paz; mas, se não for digna, torne para vós a vossa paz.

[[v40-10-14]]

^<<v40-10-14,14>>^ E, se ninguém vos receber, nem ouvir as vossas palavras, saindo daquela casa ou daquela cidade, sacudi o pó dos vossos pés.

[[v40-10-15]]

^<<v40-10-15,15>>^ Em verdade vos digo que, no dia do juízo, haverá menos rigor para a terra de Sodoma e Gomorra do que para aquela cidade.

[[v40-10-16]]

^<<v40-10-16,16>>^ Eis que vos envio como ovelhas ao meio de lobos; portanto, sede prudentes como as serpentes e simples como as pombas.

[[v40-10-17]]

^<<v40-10-17,17>>^ Acautelai-vos dos homens; porque eles vos entregarão aos sinédrios, e vos açoitarão nas suas sinagogas;

[[v40-10-18]]

^<<v40-10-18,18>>^ e por minha causa sereis levados à presença dos governadores e dos reis, para lhes servir de testemunho, a eles e aos gentios.

[[v40-10-19]]

^<<v40-10-19,19>>^ Mas, quando vos entregarem, não cuideis de como, ou o que haveis de falar; porque naquela hora vos será dado o que haveis de dizer.

[[v40-10-20]]

^<<v40-10-20,20>>^ Porque não sois vós que falais, mas o Espírito de vosso Pai é que fala em vós.

[[v40-10-21]]

^<<v40-10-21,21>>^ Um irmão entregará à morte a seu irmão, e um pai a seu filho; e filhos se levantarão contra os pais e os matarão.

[[v40-10-22]]

^<<v40-10-22,22>>^ E sereis odiados de todos por causa do meu nome, mas aquele que perseverar até o fim, esse será salvo.

[[v40-10-23]]

^<<v40-10-23,23>>^ Quando, porém, vos perseguirem numa cidade, fugi para outra; porque em verdade vos digo que não acabareis de percorrer as cidades de Israel antes que venha o Filho do homem.

[[v40-10-24]]

^<<v40-10-24,24>>^ Não é o discípulo mais do que o seu mestre, nem o servo mais do que o seu senhor.

[[v40-10-25]]

^<<v40-10-25,25>>^ Basta ao discípulo ser como seu mestre, e ao servo como seu senhor. Se chamaram Belzebu ao dono da casa, quanto mais aos seus domésticos?

[[v40-10-26]]

^<<v40-10-26,26>>^ Portanto, não os temais; porque nada há encoberto que não haja de ser descoberto, nem oculto que não haja de ser conhecido.

[[v40-10-27]]

^<<v40-10-27,27>>^ O que vos digo às escuras, dizei-o às claras; e o que escutais ao ouvido, dos eirados pregai-o.

[[v40-10-28]]

^<<v40-10-28,28>>^ E não temais os que matam o corpo, e não podem matar a alma; temei antes aquele que pode fazer perecer no inferno tanto a alma como o corpo.

[[v40-10-29]]

^<<v40-10-29,29>>^ Não se vendem dois passarinhos por um asse? e nenhum deles cairá em terra sem a vontade de vosso Pai.

[[v40-10-30]]

^<<v40-10-30,30>>^ E até mesmo os cabelos da vossa cabeça estão todos contados.

[[v40-10-31]]

^<<v40-10-31,31>>^ Não temais, pois; mais valeis vós do que muitos passarinhos.

[[v40-10-32]]

^<<v40-10-32,32>>^ Portanto, todo aquele que me confessar diante dos homens, também eu o confessarei diante de meu Pai, que está nos céus.

[[v40-10-33]]

^<<v40-10-33,33>>^ Mas qualquer que me negar diante dos homens, também eu o negarei diante de meu Pai, que está nos céus.

[[v40-10-34]]

^<<v40-10-34,34>>^ Não penseis que vim trazer paz à terra; não vim trazer paz, mas espada.

[[v40-10-35]]

^<<v40-10-35,35>>^ Porque eu vim pôr em dissensão o homem contra seu pai, a filha contra sua mãe, e a nora contra sua sogra;

[[v40-10-36]]

^<<v40-10-36,36>>^ e assim os inimigos do homem serão os da sua própria casa.

[[v40-10-37]]

^<<v40-10-37,37>>^ Quem ama o pai ou a mãe mais do que a mim não é digno de mim; e quem ama o filho ou a filha mais do que a mim não é digno de mim.

[[v40-10-38]]

^<<v40-10-38,38>>^ E quem não toma a sua cruz, e não segue após mim, não é digno de mim.

[[v40-10-39]]

^<<v40-10-39,39>>^ Quem achar a sua vida perdê-la-á, e quem perder a sua vida por amor de mim achá-la-á.

[[v40-10-40]]

^<<v40-10-40,40>>^ Quem vos recebe, a mim me recebe; e quem me recebe a mim, recebe aquele que me enviou.

[[v40-10-41]]

^<<v40-10-41,41>>^ Quem recebe um profeta na qualidade de profeta, receberá a recompensa de profeta; e quem recebe um justo na qualidade de justo, receberá a recompensa de justo.

[[v40-10-42]]

^<<v40-10-42,42>>^ E aquele que der até mesmo um copo de água fresca a um destes pequeninos, na qualidade de discípulo, em verdade vos digo que de modo algum perderá a sua recompensa.

'''

xref:040-mateus/040-mateus-009.adoc#v40-9-0[&#60; Capítulo Anterior] | <<v40-10-0,Topo>> | xref:040-mateus/040-mateus-011.adoc#v40-11-0[Próximo Capítulo &#62;]