include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, tomou Jesus consigo a Pedro, a Tiago e a João, irmão deste, e os conduziu à parte a um alto monte;

[[v40-17-2]]

^<<v40-17-2,2>>^ e foi transfigurado diante deles; o seu rosto resplandeceu como o sol, e as suas vestes tornaram-se brancas como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ E eis que lhes apareceram Moisés e Elias, falando com ele.

[[v40-17-4]]

^<<v40-17-4,4>>^ Pedro, tomando a palavra, disse a Jesus: Senhor, bom é estarmos aqui; se queres, farei aqui três cabanas, uma para ti, outra para Moisés, e outra para Elias.

[[v40-17-5]]

^<<v40-17-5,5>>^ Estando ele ainda a falar, eis que uma nuvem luminosa os cobriu; e dela saiu uma voz que dizia: Este é o meu Filho amado, em quem me comprazo; a ele ouvi.

[[v40-17-6]]

^<<v40-17-6,6>>^ Os discípulos, ouvindo isso, caíram com o rosto em terra, e ficaram grandemente atemorizados.

[[v40-17-7]]

^<<v40-17-7,7>>^ Chegou-se, pois, Jesus e, tocando-os, disse: Levantai-vos e não temais.

[[v40-17-8]]

^<<v40-17-8,8>>^ E, erguendo eles os olhos, não viram a ninguém senão a Jesus somente.

[[v40-17-9]]

^<<v40-17-9,9>>^ Enquanto desciam do monte, Jesus lhes ordenou: A ninguém conteis a visão, até que o Filho do homem seja levantado dentre os mortos.

[[v40-17-10]]

^<<v40-17-10,10>>^ Perguntaram-lhe os discípulos: Por que dizem então os escribas que é necessário que Elias venha primeiro?

[[v40-17-11]]

^<<v40-17-11,11>>^ Respondeu ele: Na verdade Elias havia de vir e restaurar todas as coisas;

[[v40-17-12]]

^<<v40-17-12,12>>^ digo-vos, porém, que Elias já veio, e não o reconheceram; mas fizeram-lhe tudo o que quiseram. Assim também o Filho do homem há de padecer às mãos deles.

[[v40-17-13]]

^<<v40-17-13,13>>^ Então entenderam os discípulos que lhes falava a respeito de João, o Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ Quando chegaram à multidão, aproximou-se de Jesus um homem que, ajoelhando-se diante dele, disse:

[[v40-17-15]]

^<<v40-17-15,15>>^ Senhor, tem compaixão de meu filho, porque é epiléptico e sofre muito; pois muitas vezes cai no fogo, e muitas vezes na água.

[[v40-17-16]]

^<<v40-17-16,16>>^ Eu o trouxe aos teus discípulos, e não o puderam curar.

[[v40-17-17]]

^<<v40-17-17,17>>^ E Jesus, respondendo, disse: ó geração incrédula e perversa! até quando estarei convosco? até quando vos sofrerei? Trazei-mo aqui.

[[v40-17-18]]

^<<v40-17-18,18>>^ Então Jesus repreendeu ao demônio, o qual saiu de menino, que desde aquela hora ficou curado.

[[v40-17-19]]

^<<v40-17-19,19>>^ Depois os discípulos, aproximando-se de Jesus em particular, perguntaram-lhe: Por que não pudemos nós expulsá-lo?

[[v40-17-20]]

^<<v40-17-20,20>>^ Disse-lhes ele: Por causa da vossa pouca fé; pois em verdade vos digo que, se tiverdes fé como um grão de mostarda direis a este monte: Passa daqui para acolá, e ele há de passar; e nada vos será impossível.

[[v40-17-21]]

^<<v40-17-21,21>>^ &#123;mas esta casta de demônios não se expulsa senão à força de oração e de jejum.&#125;

[[v40-17-22]]

^<<v40-17-22,22>>^ Ora, achando-se eles na Galiléia, disse-lhes Jesus: O Filho do homem está para ser entregue nas mãos dos homens;

[[v40-17-23]]

^<<v40-17-23,23>>^ e matá-lo-ão, e ao terceiro dia ressurgirá. E eles se entristeceram grandemente.

[[v40-17-24]]

^<<v40-17-24,24>>^ Tendo eles chegado a Cafarnaum, aproximaram-se de Pedro os que cobravam as didracmas, e lhe perguntaram: O vosso mestre não paga as didracmas?

[[v40-17-25]]

^<<v40-17-25,25>>^ Disse ele: Sim. Ao entrar Pedro em casa, Jesus se lhe antecipou, perguntando: Que te parece, Simão? De quem cobram os reis da terra imposto ou tributo? dos seus filhos, ou dos alheios?

[[v40-17-26]]

^<<v40-17-26,26>>^ Quando ele respondeu: Dos alheios, disse-lhe Jesus: Logo, são isentos os filhos.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, para que não os escandalizemos, vai ao mar, lança o anzol, tira o primeiro peixe que subir e, abrindo-lhe a boca, encontrarás um estáter; toma-o, e dá-lho por mim e por ti.

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]