include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-18-1]]

^<<v40-18-1,1>>^ Naquela hora chegaram-se a Jesus os discípulos e perguntaram: Quem é o maior no reino dos céus?

[[v40-18-2]]

^<<v40-18-2,2>>^ Jesus, chamando uma criança, colocou-a no meio deles,

[[v40-18-3]]

^<<v40-18-3,3>>^ e disse: Em verdade vos digo que se não vos converterdes e não vos fizerdes como crianças, de modo algum entrareis no reino dos céus.

[[v40-18-4]]

^<<v40-18-4,4>>^ Portanto, quem se tornar humilde como esta criança, esse é o maior no reino dos céus.

[[v40-18-5]]

^<<v40-18-5,5>>^ E qualquer que receber em meu nome uma criança tal como esta, a mim me recebe.

[[v40-18-6]]

^<<v40-18-6,6>>^ Mas qualquer que fizer tropeçar um destes pequeninos que crêem em mim, melhor lhe fora que se lhe pendurasse ao pescoço uma pedra de moinho, e se submergisse na profundeza do mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ Ai do mundo, por causa dos tropeços! pois é inevitável que venham; mas ai do homem por quem o tropeço vier!

[[v40-18-8]]

^<<v40-18-8,8>>^ Se, pois, a tua mão ou o teu pé te fizer tropeçar, corta-o, lança-o de ti; melhor te é entrar na vida aleijado, ou coxo, do que, tendo duas mãos ou dois pés, ser lançado no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ E, se teu olho te fizer tropeçar, arranca-o, e lança-o de ti; melhor te é entrar na vida com um só olho, do que tendo dois olhos, ser lançado no inferno de fogo.

[[v40-18-10]]

^<<v40-18-10,10>>^ Vede, não desprezeis a nenhum destes pequeninos; pois eu vos digo que os seus anjos nos céus sempre vêm a face de meu Pai, que está nos céus.

[[v40-18-11]]

^<<v40-18-11,11>>^ &#123;Porque o Filho do homem veio salvar o que se havia perdido.&#125;

[[v40-18-12]]

^<<v40-18-12,12>>^ Que vos parece? Se alguém tiver cem ovelhas, e uma delas se extraviar, não deixará as noventa e nove nos montes para ir buscar a que se extraviou?

[[v40-18-13]]

^<<v40-18-13,13>>^ E, se acontecer achá-la, em verdade vos digo que maior prazer tem por esta do que pelas noventa e nove que não se extraviaram.

[[v40-18-14]]

^<<v40-18-14,14>>^ Assim também não é da vontade de vosso Pai que está nos céus, que venha a perecer um só destes pequeninos.

[[v40-18-15]]

^<<v40-18-15,15>>^ Ora, se teu irmão pecar, vai, e repreende-o entre ti e ele só; se te ouvir, terás ganho teu irmão;

[[v40-18-16]]

^<<v40-18-16,16>>^ mas se não te ouvir, leva ainda contigo um ou dois, para que pela boca de duas ou três testemunhas toda palavra seja confirmada.

[[v40-18-17]]

^<<v40-18-17,17>>^ Se recusar ouvi-los, dize-o à igreja; e, se também recusar ouvir a igreja, considera-o como gentio e publicano.

[[v40-18-18]]

^<<v40-18-18,18>>^ Em verdade vos digo: Tudo quanto ligardes na terra será ligado no céu; e tudo quanto desligardes na terra será desligado no céu.

[[v40-18-19]]

^<<v40-18-19,19>>^ Ainda vos digo mais: Se dois de vós na terra concordarem acerca de qualquer coisa que pedirem, isso lhes será feito por meu Pai, que está nos céus.

[[v40-18-20]]

^<<v40-18-20,20>>^ Pois onde se acham dois ou três reunidos em meu nome, aí estou eu no meio deles.

[[v40-18-21]]

^<<v40-18-21,21>>^ Então Pedro, aproximando-se dele, lhe perguntou: Senhor, até quantas vezes pecará meu irmão contra mim, e eu hei de perdoar? Até sete?

[[v40-18-22]]

^<<v40-18-22,22>>^ Respondeu-lhe Jesus: Não te digo que até sete; mas até setenta vezes sete.

[[v40-18-23]]

^<<v40-18-23,23>>^ Por isso o reino dos céus é comparado a um rei que quis tomar contas a seus servos;

[[v40-18-24]]

^<<v40-18-24,24>>^ e, tendo começado a tomá-las, foi-lhe apresentado um que lhe devia dez mil talentos;

[[v40-18-25]]

^<<v40-18-25,25>>^ mas não tendo ele com que pagar, ordenou seu senhor que fossem vendidos, ele, sua mulher, seus filhos, e tudo o que tinha, e que se pagasse a dívida.

[[v40-18-26]]

^<<v40-18-26,26>>^ Então aquele servo, prostrando-se, o reverenciava, dizendo: Senhor, tem paciência comigo, que tudo te pagarei.

[[v40-18-27]]

^<<v40-18-27,27>>^ O senhor daquele servo, pois, movido de compaixão, soltou-o, e perdoou-lhe a dívida.

[[v40-18-28]]

^<<v40-18-28,28>>^ Saindo, porém, aquele servo, encontrou um dos seus conservos, que lhe devia cem denários; e, segurando-o, o sufocava, dizendo: Paga o que me deves.

[[v40-18-29]]

^<<v40-18-29,29>>^ Então o seu companheiro, caindo-lhe aos pés, rogava-lhe, dizendo: Tem paciência comigo, que te pagarei.

[[v40-18-30]]

^<<v40-18-30,30>>^ Ele, porém, não quis; antes foi encerrá-lo na prisão, até que pagasse a dívida.

[[v40-18-31]]

^<<v40-18-31,31>>^ Vendo, pois, os seus conservos o que acontecera, contristaram-se grandemente, e foram revelar tudo isso ao seu senhor.

[[v40-18-32]]

^<<v40-18-32,32>>^ Então o seu senhor, chamando-o á sua presença, disse-lhe: Servo malvado, perdoei-te toda aquela dívida, porque me suplicaste;

[[v40-18-33]]

^<<v40-18-33,33>>^ não devias tu também ter compaixão do teu companheiro, assim como eu tive compaixão de ti?

[[v40-18-34]]

^<<v40-18-34,34>>^ E, indignado, o seu senhor o entregou aos verdugos, até que pagasse tudo o que lhe devia.

[[v40-18-35]]

^<<v40-18-35,35>>^ Assim vos fará meu Pai celestial, se de coração não perdoardes, cada um a seu irmão.

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]