include::./index.adoc[]

[[v40-8-0]]
=== Mateus, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-8-1]]

^<<v40-8-1,1>>^ Quando Jesus desceu do monte, grandes multidões o seguiam.

[[v40-8-2]]

^<<v40-8-2,2>>^ E eis que veio um leproso e o adorava, dizendo: Senhor, se quiseres, podes tornar-me limpo.

[[v40-8-3]]

^<<v40-8-3,3>>^ Jesus, pois, estendendo a mão, tocou-o, dizendo: Quero; sê limpo. No mesmo instante ficou purificado da sua lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Disse-lhe então Jesus: Olha, não contes isto a ninguém; mas vai, mostra-te ao sacerdote, e apresenta a oferta que Moisés determinou, para lhes servir de testemunho.

[[v40-8-5]]

^<<v40-8-5,5>>^ Tendo Jesus entrado em Cafarnaum, chegou-se a ele um centurião que lhe rogava, dizendo:

[[v40-8-6]]

^<<v40-8-6,6>>^ Senhor, o meu criado jaz em casa paralítico, e horrivelmente atormentado.

[[v40-8-7]]

^<<v40-8-7,7>>^ Respondeu-lhe Jesus: Eu irei, e o curarei.

[[v40-8-8]]

^<<v40-8-8,8>>^ O centurião, porém, replicou-lhe: Senhor, não sou digno de que entres debaixo do meu telhado; mas somente dize uma palavra, e o meu criado há de sarar.

[[v40-8-9]]

^<<v40-8-9,9>>^ Pois também eu sou homem sujeito à autoridade, e tenho soldados às minhas ordens; e digo a este: Vai, e ele vai; e a outro: Vem, e ele vem; e ao meu servo: Faze isto, e ele o faz.

[[v40-8-10]]

^<<v40-8-10,10>>^ Jesus, ouvindo isso, admirou-se, e disse aos que o seguiam: Em verdade vos digo que a ninguém encontrei em Israel com tamanha fé.

[[v40-8-11]]

^<<v40-8-11,11>>^ Também vos digo que muitos virão do oriente e do ocidente, e reclinar-se-ão à mesa de Abraão, Isaque e Jacó, no reino dos céus;

[[v40-8-12]]

^<<v40-8-12,12>>^ mas os filhos do reino serão lançados nas trevas exteriores; ali haverá choro e ranger de dentes.

[[v40-8-13]]

^<<v40-8-13,13>>^ Então disse Jesus ao centurião: Vai-te, e te seja feito assim como creste. E naquela mesma hora o seu criado sarou.

[[v40-8-14]]

^<<v40-8-14,14>>^ Ora, tendo Jesus entrado na casa de Pedro, viu a sogra deste de cama; e com febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ E tocou-lhe a mão, e a febre a deixou; então ela se levantou, e o servia.

[[v40-8-16]]

^<<v40-8-16,16>>^ Caída a tarde, trouxeram-lhe muitos endemoninhados; e ele com a sua palavra expulsou os espíritos, e curou todos os enfermos;

[[v40-8-17]]

^<<v40-8-17,17>>^ para que se cumprisse o que fora dito pelo profeta Isaías: Ele tomou sobre si as nossas enfermidades, e levou as nossas doenças.

[[v40-8-18]]

^<<v40-8-18,18>>^ Vendo Jesus uma multidão ao redor de si, deu ordem de partir para o outro lado do mar.

[[v40-8-19]]

^<<v40-8-19,19>>^ E, aproximando-se um escriba, disse-lhe: Mestre, seguir-te-ei para onde quer que fores.

[[v40-8-20]]

^<<v40-8-20,20>>^ Respondeu-lhe Jesus: As raposas têm covis, e as aves do céu têm ninhos; mas o Filho do homem não tem onde reclinar a cabeça.

[[v40-8-21]]

^<<v40-8-21,21>>^ E outro de seus discípulos lhe disse: Senhor, permite-me ir primeiro sepultar meu pai.

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus, porém, respondeu-lhe: Segue-me, e deixa os mortos sepultar os seus próprios mortos.

[[v40-8-23]]

^<<v40-8-23,23>>^ E, entrando ele no barco, seus discípulos o seguiram.

[[v40-8-24]]

^<<v40-8-24,24>>^ E eis que se levantou no mar tão grande tempestade que o barco era coberto pelas ondas; ele, porém, estava dormindo.

[[v40-8-25]]

^<<v40-8-25,25>>^ Os discípulos, pois, aproximando-se, o despertaram, dizendo: Salva-nos, Senhor, que estamos perecendo.

[[v40-8-26]]

^<<v40-8-26,26>>^ Ele lhes respondeu: Por que temeis, homens de pouca fé? Então, levantando-se repreendeu os ventos e o mar, e seguiu-se grande bonança.

[[v40-8-27]]

^<<v40-8-27,27>>^ E aqueles homens se maravilharam, dizendo: Que homem é este, que até os ventos e o mar lhe obedecem?

[[v40-8-28]]

^<<v40-8-28,28>>^ Tendo ele chegado ao outro lado, à terra dos gadarenos, saíram-lhe ao encontro dois endemoninhados, vindos dos sepulcros; tão ferozes eram que ninguém podia passar por aquele caminho.

[[v40-8-29]]

^<<v40-8-29,29>>^ E eis que gritaram, dizendo: Que temos nós contigo, Filho de Deus? Vieste aqui atormentar-nos antes do tempo?

[[v40-8-30]]

^<<v40-8-30,30>>^ Ora, a alguma distância deles, andava pastando uma grande manada de porcos.

[[v40-8-31]]

^<<v40-8-31,31>>^ E os demônios rogavam-lhe, dizendo: Se nos expulsas, manda-nos entrar naquela manada de porcos.

[[v40-8-32]]

^<<v40-8-32,32>>^ Disse-lhes Jesus: Ide. Então saíram, e entraram nos porcos; e eis que toda a manada se precipitou pelo despenhadeiro no mar, perecendo nas águas.

[[v40-8-33]]

^<<v40-8-33,33>>^ Os pastores fugiram e, chegando à cidade, divulgaram todas estas coisas, e o que acontecera aos endemoninhados.

[[v40-8-34]]

^<<v40-8-34,34>>^ E eis que toda a cidade saiu ao encontro de Jesus; e vendo-o, rogaram-lhe que se retirasse dos seus termos.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]