include::./index.adoc[]

[[v40-28-0]]
=== Mateus, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-28-1]]

^<<v40-28-1,1>>^ No fim do sábado, quando já despontava o primeiro dia da semana, Maria Madalena e a outra Maria foram ver o sepulcro.

[[v40-28-2]]

^<<v40-28-2,2>>^ E eis que houvera um grande terremoto; pois um anjo do Senhor descera do céu e, chegando-se, removera a pedra e estava sentado sobre ela.

[[v40-28-3]]

^<<v40-28-3,3>>^ o seu aspecto era como um relâmpago, e as suas vestes brancas como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ E de medo dele tremeram os guardas, e ficaram como mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ Mas o anjo disse às mulheres: Não temais vós; pois eu sei que buscais a Jesus, que foi crucificado.

[[v40-28-6]]

^<<v40-28-6,6>>^ Não está aqui, porque ressurgiu, como ele disse. Vinde, vede o lugar onde jazia;

[[v40-28-7]]

^<<v40-28-7,7>>^ e ide depressa, e dizei aos seus discípulos que ressurgiu dos mortos; e eis que vai adiante de vós para a Galiléia; ali o vereis. Eis que vo-lo tenho dito.

[[v40-28-8]]

^<<v40-28-8,8>>^ E, partindo elas pressurosamente do sepulcro, com temor e grande alegria, correram a anunciá-lo aos discípulos.

[[v40-28-9]]

^<<v40-28-9,9>>^ E eis que Jesus lhes veio ao encontro, dizendo: Salve. E elas, aproximando-se, abraçaram-lhe os pés, e o adoraram.

[[v40-28-10]]

^<<v40-28-10,10>>^ Então lhes disse Jesus: Não temais; ide dizer a meus irmãos que vão para a Galiléia; ali me verão.

[[v40-28-11]]

^<<v40-28-11,11>>^ Ora, enquanto elas iam, eis que alguns da guarda foram à cidade, e contaram aos principais sacerdotes tudo quanto havia acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ E congregados eles com os anciãos e tendo consultado entre si, deram muito dinheiro aos soldados,

[[v40-28-13]]

^<<v40-28-13,13>>^ e ordenaram-lhes que dissessem: Vieram de noite os seus discípulos e, estando nós dormindo, furtaram-no.

[[v40-28-14]]

^<<v40-28-14,14>>^ E, se isto chegar aos ouvidos do governador, nós o persuadiremos, e vos livraremos de cuidado.

[[v40-28-15]]

^<<v40-28-15,15>>^ Então eles, tendo recebido o dinheiro, fizeram como foram instruídos. E essa história tem-se divulgado entre os judeus até o dia de hoje.

[[v40-28-16]]

^<<v40-28-16,16>>^ Partiram, pois, os onze discípulos para a Galiléia, para o monte onde Jesus lhes designara.

[[v40-28-17]]

^<<v40-28-17,17>>^ Quando o viram, o adoraram; mas alguns duvidaram.

[[v40-28-18]]

^<<v40-28-18,18>>^ E, aproximando-se Jesus, falou-lhes, dizendo: Foi-me dada toda a autoridade no céu e na terra.

[[v40-28-19]]

^<<v40-28-19,19>>^ Portanto ide, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo;

[[v40-28-20]]

^<<v40-28-20,20>>^ ensinando-os a observar todas as coisas que eu vos tenho mandado; e eis que eu estou convosco todos os dias, até a consumação dos séculos.

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]