include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-27-1]]

^<<v40-27-1,1>>^ Ora, chegada a manhã, todos os principais sacerdotes e os anciãos do povo entraram em conselho contra Jesus, para o matarem;

[[v40-27-2]]

^<<v40-27-2,2>>^ e, maniatando-o, levaram-no e o entregaram a Pilatos, o governador.

[[v40-27-3]]

^<<v40-27-3,3>>^ Então Judas, aquele que o traíra, vendo que Jesus fora condenado, devolveu, compungido, as trinta moedas de prata aos anciãos, dizendo:

[[v40-27-4]]

^<<v40-27-4,4>>^ Pequei, traindo o sangue inocente. Responderam eles: Que nos importa? Seja isto lá contigo.

[[v40-27-5]]

^<<v40-27-5,5>>^ E tendo ele atirado para dentro do santuário as moedas de prata, retirou-se, e foi enforcar-se.

[[v40-27-6]]

^<<v40-27-6,6>>^ Os principais sacerdotes, pois, tomaram as moedas de prata, e disseram: Não é lícito metê-las no cofre das ofertas, porque é preço de sangue.

[[v40-27-7]]

^<<v40-27-7,7>>^ E, tendo deliberado em conselho, compraram com elas o campo do oleiro, para servir de cemitério para os estrangeiros.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso tem sido chamado aquele campo, até o dia de hoje, Campo de Sangue.

[[v40-27-9]]

^<<v40-27-9,9>>^ Cumpriu-se, então, o que foi dito pelo profeta Jeremias: Tomaram as trinta moedas de prata, preço do que foi avaliado, a quem certos filhos de Israel avaliaram,

[[v40-27-10]]

^<<v40-27-10,10>>^ e deram-nas pelo campo do oleiro, assim como me ordenou o Senhor.

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus, pois, ficou em pé diante do governador; e este lhe perguntou: És tu o rei dos judeus? Respondeu-lhe Jesus: É como dizes.

[[v40-27-12]]

^<<v40-27-12,12>>^ Mas ao ser acusado pelos principais sacerdotes e pelos anciãos, nada respondeu.

[[v40-27-13]]

^<<v40-27-13,13>>^ Perguntou-lhe então Pilatos: Não ouves quantas coisas testificam contra ti?

[[v40-27-14]]

^<<v40-27-14,14>>^ E Jesus não lhe respondeu a uma pergunta sequer; de modo que o governador muito se admirava.

[[v40-27-15]]

^<<v40-27-15,15>>^ Ora, por ocasião da festa costumava o governador soltar um preso, escolhendo o povo aquele que quisesse.

[[v40-27-16]]

^<<v40-27-16,16>>^ Nesse tempo tinham um preso notório, chamado Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Portanto, estando o povo reunido, perguntou-lhe Pilatos: Qual quereis que vos solte? Barrabás, ou Jesus, chamado o Cristo?

[[v40-27-18]]

^<<v40-27-18,18>>^ Pois sabia que por inveja o haviam entregado.

[[v40-27-19]]

^<<v40-27-19,19>>^ E estando ele assentado no tribunal, sua mulher mandou dizer-lhe: Não te envolvas na questão desse justo, porque muito sofri hoje em sonho por causa dele.

[[v40-27-20]]

^<<v40-27-20,20>>^ Mas os principais sacerdotes e os anciãos persuadiram as multidões a que pedissem Barrabás e fizessem morrer Jesus.

[[v40-27-21]]

^<<v40-27-21,21>>^ O governador, pois, perguntou-lhes: Qual dos dois quereis que eu vos solte? E disseram: Barrabás.

[[v40-27-22]]

^<<v40-27-22,22>>^ Tornou-lhes Pilatos: Que farei então de Jesus, que se chama Cristo? Disseram todos: Seja crucificado.

[[v40-27-23]]

^<<v40-27-23,23>>^ Pilatos, porém, disse: Pois que mal fez ele? Mas eles clamavam ainda mais: Seja crucificado.

[[v40-27-24]]

^<<v40-27-24,24>>^ Ao ver Pilatos que nada conseguia, mas pelo contrário que o tumulto aumentava, mandando trazer água, lavou as mãos diante da multidão, dizendo: Sou inocente do sangue deste homem; seja isso lá convosco.

[[v40-27-25]]

^<<v40-27-25,25>>^ E todo o povo respondeu: O seu sangue caia sobre nós e sobre nossos filhos.

[[v40-27-26]]

^<<v40-27-26,26>>^ 

[[v40-27-27]]

^<<v40-27-27,27>>^ Nisso os soldados do governador levaram Jesus ao pretório, e reuniram em torno dele toda a corte.

[[v40-27-28]]

^<<v40-27-28,28>>^ E, despindo-o, vestiram-lhe um manto escarlate;

[[v40-27-29]]

^<<v40-27-29,29>>^ e tecendo uma coroa de espinhos, puseram-lha na cabeça, e na mão direita uma cana, e ajoelhando-se diante dele, o escarneciam, dizendo: Salve, rei dos judeus!

[[v40-27-30]]

^<<v40-27-30,30>>^ E, cuspindo nele, tiraram-lhe a cana, e davam-lhe com ela na cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Depois de o terem escarnecido, despiram-lhe o manto, puseram-lhe as suas vestes, e levaram-no para ser crucificado.

[[v40-27-32]]

^<<v40-27-32,32>>^ Ao saírem, encontraram um homem cireneu, chamado Simão, a quem obrigaram a levar a cruz de Jesus.

[[v40-27-33]]

^<<v40-27-33,33>>^ Quando chegaram ao lugar chamado Gólgota, que quer dizer, lugar da Caveira,

[[v40-27-34]]

^<<v40-27-34,34>>^ deram-lhe a beber vinho misturado com fel; mas ele, provando-o, não quis beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ Então, depois de o crucificarem, repartiram as vestes dele, lançando sortes, &#123;para que se cumprisse o que foi dito pelo profeta: Repartiram entre si as minhas vestes, e sobre a minha túnica deitaram sortes.&#125;

[[v40-27-36]]

^<<v40-27-36,36>>^ E, sentados, ali o guardavam.

[[v40-27-37]]

^<<v40-27-37,37>>^ Puseram-lhe por cima da cabeça a sua acusação escrita: ESTE É JESUS, O REI DOS JUDEUS.

[[v40-27-38]]

^<<v40-27-38,38>>^ Então foram crucificados com ele dois salteadores, um à direita, e outro à esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ E os que iam passando blasfemavam dele, meneando a cabeça

[[v40-27-40]]

^<<v40-27-40,40>>^ e dizendo: Tu, que destróis o santuário e em três dias o reedificas, salva-te a ti mesmo; se és Filho de Deus, desce da cruz.

[[v40-27-41]]

^<<v40-27-41,41>>^ De igual modo também os principais sacerdotes, com os escribas e anciãos, escarnecendo, diziam:

[[v40-27-42]]

^<<v40-27-42,42>>^ A outros salvou; a si mesmo não pode salvar. Rei de Israel é ele; desça agora da cruz, e creremos nele;

[[v40-27-43]]

^<<v40-27-43,43>>^ confiou em Deus, livre-o ele agora, se lhe quer bem; porque disse: Sou Filho de Deus.

[[v40-27-44]]

^<<v40-27-44,44>>^ O mesmo lhe lançaram em rosto também os salteadores que com ele foram crucificados.

[[v40-27-45]]

^<<v40-27-45,45>>^ E, desde a hora sexta, houve trevas sobre toda a terra, até a hora nona.

[[v40-27-46]]

^<<v40-27-46,46>>^ Cerca da hora nona, bradou Jesus em alta voz, dizendo: Eli, Eli, lamá sabactani; isto é, Deus meu, Deus meu, por que me desamparaste?

[[v40-27-47]]

^<<v40-27-47,47>>^ Alguns dos que ali estavam, ouvindo isso, diziam: Ele chama por Elias.

[[v40-27-48]]

^<<v40-27-48,48>>^ E logo correu um deles, tomou uma esponja, ensopou-a em vinagre e, pondo-a numa cana, dava-lhe de beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Os outros, porém, disseram: Deixa, vejamos se Elias vem salvá-lo.

[[v40-27-50]]

^<<v40-27-50,50>>^ De novo bradou Jesus com grande voz, e entregou o espírito.

[[v40-27-51]]

^<<v40-27-51,51>>^ E eis que o véu do santuário se rasgou em dois, de alto a baixo; a terra tremeu, as pedras se fenderam,

[[v40-27-52]]

^<<v40-27-52,52>>^ os sepulcros se abriram, e muitos corpos de santos que tinham dormido foram ressuscitados;

[[v40-27-53]]

^<<v40-27-53,53>>^ e, saindo dos sepulcros, depois da ressurreição dele, entraram na cidade santa, e apareceram a muitos.

[[v40-27-54]]

^<<v40-27-54,54>>^ ora, o centurião e os que com ele guardavam Jesus, vendo o terremoto e as coisas que aconteciam, tiveram grande temor, e disseram: Verdadeiramente este era filho de Deus.

[[v40-27-55]]

^<<v40-27-55,55>>^ Também estavam ali, olhando de longe, muitas mulheres que tinham seguido Jesus desde a Galiléia para o ouvir;

[[v40-27-56]]

^<<v40-27-56,56>>^ entre as quais se achavam Maria Madalena, Maria, mãe de Tiago e de José, e a mãe dos filhos de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Ao cair da tarde, veio um homem rico de Arimatéia, chamado José, que também era discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Esse foi a Pilatos e pediu o corpo de Jesus. Então Pilatos mandou que lhe fosse entregue.

[[v40-27-59]]

^<<v40-27-59,59>>^ E José, tomando o corpo, envolveu-o num pano limpo, de linho,

[[v40-27-60]]

^<<v40-27-60,60>>^ e depositou-o no seu sepulcro novo, que havia aberto em rocha; e, rodando uma grande pedra para a porta do sepulcro, retirou-se.

[[v40-27-61]]

^<<v40-27-61,61>>^ Mas achavam-se ali Maria Madalena e a outra Maria, sentadas defronte do sepulcro.

[[v40-27-62]]

^<<v40-27-62,62>>^ No dia seguinte, isto é, o dia depois da preparação, reuniram-se os principais sacerdotes e os fariseus perante Pilatos,

[[v40-27-63]]

^<<v40-27-63,63>>^ e disseram: Senhor, lembramo-nos de que aquele embusteiro, quando ainda vivo, afirmou: Depois de três dias ressurgirei.

[[v40-27-64]]

^<<v40-27-64,64>>^ Manda, pois, que o sepulcro seja guardado com segurança até o terceiro dia; para não suceder que, vindo os discípulos, o furtem e digam ao povo: Ressurgiu dos mortos; e assim o último embuste será pior do que o primeiro.

[[v40-27-65]]

^<<v40-27-65,65>>^ Disse-lhes Pilatos: Tendes uma guarda; ide, tornai-o seguro, como entendeis.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]