include::./index.adoc[]

[[v40-13-0]]
=== Mateus, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-13-1]]

^<<v40-13-1,1>>^ No mesmo dia, tendo Jesus saído de casa, sentou-se à beira do mar;

[[v40-13-2]]

^<<v40-13-2,2>>^ e reuniram-se a ele grandes multidões, de modo que entrou num barco, e se sentou; e todo o povo estava em pé na praia.

[[v40-13-3]]

^<<v40-13-3,3>>^ E falou-lhes muitas coisas por parábolas, dizendo: Eis que o semeador saiu a semear.

[[v40-13-4]]

^<<v40-13-4,4>>^ e quando semeava, uma parte da semente caiu à beira do caminho, e vieram as aves e comeram.

[[v40-13-5]]

^<<v40-13-5,5>>^ E outra parte caiu em lugares pedregosos, onde não havia muita terra: e logo nasceu, porque não tinha terra profunda;

[[v40-13-6]]

^<<v40-13-6,6>>^ mas, saindo o sol, queimou-se e, por não ter raiz, secou-se.

[[v40-13-7]]

^<<v40-13-7,7>>^ E outra caiu entre espinhos; e os espinhos cresceram e a sufocaram.

[[v40-13-8]]

^<<v40-13-8,8>>^ Mas outra caiu em boa terra, e dava fruto, um a cem, outro a sessenta e outro a trinta por um.

[[v40-13-9]]

^<<v40-13-9,9>>^ Quem tem ouvidos, ouça.

[[v40-13-10]]

^<<v40-13-10,10>>^ E chegando-se a ele os discípulos, perguntaram-lhe: Por que lhes falas por parábolas?

[[v40-13-11]]

^<<v40-13-11,11>>^ Respondeu-lhes Jesus: Porque a vós é dado conhecer os mistérios do reino dos céus, mas a eles não lhes é dado;

[[v40-13-12]]

^<<v40-13-12,12>>^ pois ao que tem, dar-se-lhe-á, e terá em abundância; mas ao que não tem, até aquilo que tem lhe será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ Por isso lhes falo por parábolas; porque eles, vendo, não vêem; e ouvindo, não ouvem nem entendem.

[[v40-13-14]]

^<<v40-13-14,14>>^ E neles se cumpre a profecia de Isaías, que diz: Ouvindo, ouvireis, e de maneira alguma entendereis; e, vendo, vereis, e de maneira alguma percebereis.

[[v40-13-15]]

^<<v40-13-15,15>>^ Porque o coração deste povo se endureceu, e com os ouvidos ouviram tardiamente, e fecharam os olhos, para que não vejam com os olhos, nem ouçam com os ouvidos, nem entendam com o coração, nem se convertam, e eu os cure.

[[v40-13-16]]

^<<v40-13-16,16>>^ Mas bem-aventurados os vossos olhos, porque vêem, e os vossos ouvidos, porque ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Pois, em verdade vos digo que muitos profetas e justos desejaram ver o que vedes, e não o viram; e ouvir o que ouvis, e não o ouviram.

[[v40-13-18]]

^<<v40-13-18,18>>^ Ouvi, pois, vós a parábola do semeador.

[[v40-13-19]]

^<<v40-13-19,19>>^ A todo o que ouve a palavra do reino e não a entende, vem o Maligno e arrebata o que lhe foi semeado no coração; este é o que foi semeado à beira do caminho.

[[v40-13-20]]

^<<v40-13-20,20>>^ E o que foi semeado nos lugares pedregosos, este é o que ouve a palavra, e logo a recebe com alegria;

[[v40-13-21]]

^<<v40-13-21,21>>^ mas não tem raiz em si mesmo, antes é de pouca duração; e sobrevindo a angústia e a perseguição por causa da palavra, logo se escandaliza.

[[v40-13-22]]

^<<v40-13-22,22>>^ E o que foi semeado entre os espinhos, este é o que ouve a palavra; mas os cuidados deste mundo e a sedução das riquezas sufocam a palavra, e ela fica infrutífera.

[[v40-13-23]]

^<<v40-13-23,23>>^ Mas o que foi semeado em boa terra, este é o que ouve a palavra, e a entende; e dá fruto, e um produz cem, outro sessenta, e outro trinta.

[[v40-13-24]]

^<<v40-13-24,24>>^ Propôs-lhes outra parábola, dizendo: O reino dos céus é semelhante ao homem que semeou boa semente no seu campo;

[[v40-13-25]]

^<<v40-13-25,25>>^ mas, enquanto os homens dormiam, veio o inimigo dele, semeou joio no meio do trigo, e retirou-se.

[[v40-13-26]]

^<<v40-13-26,26>>^ Quando, porém, a erva cresceu e começou a espigar, então apareceu também o joio.

[[v40-13-27]]

^<<v40-13-27,27>>^ Chegaram, pois, os servos do proprietário, e disseram-lhe: Senhor, não semeaste no teu campo boa semente? Donde, pois, vem o joio?

[[v40-13-28]]

^<<v40-13-28,28>>^ Respondeu-lhes: Algum inimigo é quem fez isso. E os servos lhe disseram: Queres, pois, que vamos arrancá-lo?

[[v40-13-29]]

^<<v40-13-29,29>>^ Ele, porém, disse: Não; para que, ao colher o joio, não arranqueis com ele também o trigo.

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixai crescer ambos juntos até a ceifa; e, por ocasião da ceifa, direi aos ceifeiros: Ajuntai primeiro o joio, e atai-o em molhos para o queimar; o trigo, porém, recolhei-o no meu celeiro.

[[v40-13-31]]

^<<v40-13-31,31>>^ Propôs-lhes outra parábola, dizendo: O reino dos céus é semelhante a um grão de mostarda que um homem tomou, e semeou no seu campo;

[[v40-13-32]]

^<<v40-13-32,32>>^ o qual é realmente a menor de todas as sementes; mas, depois de ter crescido, é a maior das hortaliças, e faz-se árvore, de sorte que vêm as aves do céu, e se aninham nos seus ramos.

[[v40-13-33]]

^<<v40-13-33,33>>^ Outra parábola lhes disse: O reino dos céus é semelhante ao fermento que uma mulher tomou e misturou com três medidas de farinha, até ficar tudo levedado.

[[v40-13-34]]

^<<v40-13-34,34>>^ Todas estas coisas falou Jesus às multidões por parábolas, e sem parábolas nada lhes falava;

[[v40-13-35]]

^<<v40-13-35,35>>^ para que se cumprisse o que foi dito pelo profeta: Abrirei em parábolas a minha boca; publicarei coisas ocultas desde a fundação do mundo.

[[v40-13-36]]

^<<v40-13-36,36>>^ Então Jesus, deixando as multidões, entrou em casa. E chegaram-se a ele os seus discípulos, dizendo: Explica-nos a parábola do joio do campo.

[[v40-13-37]]

^<<v40-13-37,37>>^ E ele, respondendo, disse: O que semeia a boa semente é o Filho do homem;

[[v40-13-38]]

^<<v40-13-38,38>>^ o campo é o mundo; a boa semente são os filhos do reino; o joio são os filhos do maligno;

[[v40-13-39]]

^<<v40-13-39,39>>^ o inimigo que o semeou é o Diabo; a ceifa é o fim do mundo, e os celeiros são os anjos.

[[v40-13-40]]

^<<v40-13-40,40>>^ Pois assim como o joio é colhido e queimado no fogo, assim será no fim do mundo.

[[v40-13-41]]

^<<v40-13-41,41>>^ Mandará o Filho do homem os seus anjos, e eles ajuntarão do seu reino todos os que servem de tropeço, e os que praticam a iniqüidade,

[[v40-13-42]]

^<<v40-13-42,42>>^ e lançá-los-ão na fornalha de fogo; ali haverá choro e ranger de dentes.

[[v40-13-43]]

^<<v40-13-43,43>>^ Então os justos resplandecerão como o sol, no reino de seu Pai. Quem tem ouvidos, ouça.

[[v40-13-44]]

^<<v40-13-44,44>>^ O reino dos céus é semelhante a um tesouro escondido no campo, que um homem, ao descobri-lo, esconde; então, movido de gozo, vai, vende tudo quanto tem, e compra aquele campo.

[[v40-13-45]]

^<<v40-13-45,45>>^ Outrossim, o reino dos céus é semelhante a um negociante que buscava boas pérolas;

[[v40-13-46]]

^<<v40-13-46,46>>^ e encontrando uma pérola de grande valor, foi, vendeu tudo quanto tinha, e a comprou.

[[v40-13-47]]

^<<v40-13-47,47>>^ Igualmente, o reino dos céus é semelhante a uma rede lançada ao mar, e que apanhou toda espécie de peixes.

[[v40-13-48]]

^<<v40-13-48,48>>^ E, quando cheia, puxaram-na para a praia; e, sentando-se, puseram os bons em cestos; os ruins, porém, lançaram fora.

[[v40-13-49]]

^<<v40-13-49,49>>^ Assim será no fim do mundo: sairão os anjos, e separarão os maus dentre os justos,

[[v40-13-50]]

^<<v40-13-50,50>>^ e lançá-los-ão na fornalha de fogo; ali haverá choro e ranger de dentes.

[[v40-13-51]]

^<<v40-13-51,51>>^ Entendestes todas estas coisas? Disseram-lhe eles: Entendemos.

[[v40-13-52]]

^<<v40-13-52,52>>^ E disse-lhes: Por isso, todo escriba que se fez discípulo do reino dos céus é semelhante a um homem, proprietário, que tira do seu tesouro coisas novas e velhas.

[[v40-13-53]]

^<<v40-13-53,53>>^ E Jesus, tendo concluído estas parábolas, se retirou dali.

[[v40-13-54]]

^<<v40-13-54,54>>^ E, chegando à sua terra, ensinava o povo na sinagoga, de modo que este se maravilhava e dizia: Donde lhe vem esta sabedoria, e estes poderes milagrosos?

[[v40-13-55]]

^<<v40-13-55,55>>^ Não é este o filho do carpinteiro? e não se chama sua mãe Maria, e seus irmãos Tiago, José, Simão, e Judas?

[[v40-13-56]]

^<<v40-13-56,56>>^ E não estão entre nós todas as suas irmãs? Donde lhe vem, pois, tudo isto?

[[v40-13-57]]

^<<v40-13-57,57>>^ E escandalizavam-se dele. Jesus, porém, lhes disse: Um profeta não fica sem honra senão na sua terra e na sua própria casa.

[[v40-13-58]]

^<<v40-13-58,58>>^ E não fez ali muitos milagres, por causa da incredulidade deles.

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]