include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-21-1]]

^<<v40-21-1,1>>^ Quando se aproximaram de Jerusalém, e chegaram a Betfagé, ao Monte das Oliveiras, enviou Jesus dois discípulos, dizendo-lhes:

[[v40-21-2]]

^<<v40-21-2,2>>^ Ide à aldeia que está defronte de vós, e logo encontrareis uma jumenta presa, e um jumentinho com ela; desprendei-a, e trazei-mos.

[[v40-21-3]]

^<<v40-21-3,3>>^ E, se alguém vos disser alguma coisa, respondei: O Senhor precisa deles; e logo os enviará.

[[v40-21-4]]

^<<v40-21-4,4>>^ Ora, isso aconteceu para que se cumprisse o que foi dito pelo profeta:

[[v40-21-5]]

^<<v40-21-5,5>>^ Dizei à filha de Sião: Eis que aí te vem o teu Rei, manso e montado em um jumento, em um jumentinho, cria de animal de carga.

[[v40-21-6]]

^<<v40-21-6,6>>^ Indo, pois, os discípulos e fazendo como Jesus lhes ordenara,

[[v40-21-7]]

^<<v40-21-7,7>>^ trouxeram a jumenta e o jumentinho, e sobre eles puseram os seus mantos, e Jesus montou.

[[v40-21-8]]

^<<v40-21-8,8>>^ E a maior parte da multidão estendeu os seus mantos pelo caminho; e outros cortavam ramos de árvores, e os espalhavam pelo caminho.

[[v40-21-9]]

^<<v40-21-9,9>>^ E as multidões, tanto as que o precediam como as que o seguiam, clamavam, dizendo: Hosana ao Filho de Davi! bendito o que vem em nome do Senhor! Hosana nas alturas!

[[v40-21-10]]

^<<v40-21-10,10>>^ Ao entrar ele em Jerusalém, agitou-se a cidade toda e perguntava: Quem é este?

[[v40-21-11]]

^<<v40-21-11,11>>^ E as multidões respondiam: Este é o profeta Jesus, de Nazaré da Galiléia.

[[v40-21-12]]

^<<v40-21-12,12>>^ Então Jesus entrou no templo, expulsou todos os que ali vendiam e compravam, e derribou as mesas dos cambistas e as cadeiras dos que vendiam pombas;

[[v40-21-13]]

^<<v40-21-13,13>>^ e disse-lhes: Está escrito: A minha casa será chamada casa de oração; vós, porém, a fazeis covil de salteadores.

[[v40-21-14]]

^<<v40-21-14,14>>^ E chegaram-se a ele no templo cegos e coxos, e ele os curou.

[[v40-21-15]]

^<<v40-21-15,15>>^ Vendo, porém, os principais sacerdotes e os escribas as maravilhas que ele fizera, e os meninos que clamavam no templo: Hosana ao Filho de Davi, indignaram-se,

[[v40-21-16]]

^<<v40-21-16,16>>^ e perguntaram-lhe: Ouves o que estes estão dizendo? Respondeu-lhes Jesus: Sim; nunca lestes: Da boca de pequeninos e de criancinhas de peito tiraste perfeito louvor?

[[v40-21-17]]

^<<v40-21-17,17>>^ E deixando-os, saiu da cidade para Betânia, e ali passou a noite.

[[v40-21-18]]

^<<v40-21-18,18>>^ Ora, de manhã, ao voltar à cidade, teve fome;

[[v40-21-19]]

^<<v40-21-19,19>>^ e, avistando uma figueira à beira do caminho, dela se aproximou, e não achou nela senão folhas somente; e disse-lhe: Nunca mais nasça fruto de ti. E a figueira secou imediatamente.

[[v40-21-20]]

^<<v40-21-20,20>>^ Quando os discípulos viram isso, perguntaram admirados: Como é que imediatamente secou a figueira?

[[v40-21-21]]

^<<v40-21-21,21>>^ Jesus, porém, respondeu-lhes: Em verdade vos digo que, se tiverdes fé e não duvidardes, não só fareis o que foi feito à figueira, mas até, se a este monte disserdes: Ergue-te e lança-te no mar, isso será feito;

[[v40-21-22]]

^<<v40-21-22,22>>^ e tudo o que pedirdes na oração, crendo, recebereis.

[[v40-21-23]]

^<<v40-21-23,23>>^ Tendo Jesus entrado no templo, e estando a ensinar, aproximaram-se dele os principais sacerdotes e os anciãos do povo, e perguntaram: Com que autoridade fazes tu estas coisas? e quem te deu tal autoridade?

[[v40-21-24]]

^<<v40-21-24,24>>^ Respondeu-lhes Jesus: Eu também vos perguntarei uma coisa; se ma disserdes, eu de igual modo vos direi com que autoridade faço estas coisas.

[[v40-21-25]]

^<<v40-21-25,25>>^ O batismo de João, donde era? do céu ou dos homens? Ao que eles arrazoavam entre si: Se dissermos: Do céu, ele nos dirá: Então por que não o crestes?

[[v40-21-26]]

^<<v40-21-26,26>>^ Mas, se dissermos: Dos homens, tememos o povo; porque todos consideram João como profeta.

[[v40-21-27]]

^<<v40-21-27,27>>^ Responderam, pois, a Jesus: Não sabemos. Disse-lhe ele: Nem eu vos digo com que autoridade faço estas coisas.

[[v40-21-28]]

^<<v40-21-28,28>>^ Mas que vos parece? Um homem tinha dois filhos, e, chegando-se ao primeiro, disse: Filho, vai trabalhar hoje na vinha.

[[v40-21-29]]

^<<v40-21-29,29>>^ Ele respondeu: Sim, senhor; mas não foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ Chegando-se, então, ao segundo, falou-lhe de igual modo; respondeu-lhe este: Não quero; mas depois, arrependendo-se, foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ Qual dos dois fez a vontade do pai? Disseram eles: O segundo. Disse-lhes Jesus: Em verdade vos digo que os publicanos e as meretrizes entram adiante de vós no reino de Deus.

[[v40-21-32]]

^<<v40-21-32,32>>^ Pois João veio a vós no caminho da justiça, e não lhe deste crédito, mas os publicanos e as meretrizes lho deram; vós, porém, vendo isto, nem depois vos arrependestes para crerdes nele.

[[v40-21-33]]

^<<v40-21-33,33>>^ Ouvi ainda outra parábola: Havia um homem, proprietário, que plantou uma vinha, cercou-a com uma sebe, cavou nela um lagar, e edificou uma torre; depois arrendou-a a uns lavradores e ausentou-se do país.

[[v40-21-34]]

^<<v40-21-34,34>>^ E quando chegou o tempo dos frutos, enviou os seus servos aos lavradores, para receber os seus frutos.

[[v40-21-35]]

^<<v40-21-35,35>>^ E os lavradores, apoderando-se dos servos, espancaram um, mataram outro, e a outro apedrejaram.

[[v40-21-36]]

^<<v40-21-36,36>>^ Depois enviou ainda outros servos, em maior número do que os primeiros; e fizeram-lhes o mesmo.

[[v40-21-37]]

^<<v40-21-37,37>>^ Por último enviou-lhes seu filho, dizendo: A meu filho terão respeito.

[[v40-21-38]]

^<<v40-21-38,38>>^ Mas os lavradores, vendo o filho, disseram entre si: Este é o herdeiro; vinde, matemo-lo, e apoderemo-nos da sua herança.

[[v40-21-39]]

^<<v40-21-39,39>>^ E, agarrando-o, lançaram-no fora da vinha e o mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ Quando, pois, vier o senhor da vinha, que fará àqueles lavradores?

[[v40-21-41]]

^<<v40-21-41,41>>^ Responderam-lhe eles: Fará perecer miseravelmente a esses maus, e arrendará a vinha a outros lavradores, que a seu tempo lhe entreguem os frutos.

[[v40-21-42]]

^<<v40-21-42,42>>^ Disse-lhes Jesus: Nunca lestes nas Escrituras: A pedra que os edificadores rejeitaram, essa foi posta como pedra angular; pelo Senhor foi feito isso, e é maravilhoso aos nossos olhos?

[[v40-21-43]]

^<<v40-21-43,43>>^ Portanto eu vos digo que vos será tirado o reino de Deus, e será dado a um povo que dê os seus frutos.

[[v40-21-44]]

^<<v40-21-44,44>>^ E quem cair sobre esta pedra será despedaçado; mas aquele sobre quem ela cair será reduzido a pó.

[[v40-21-45]]

^<<v40-21-45,45>>^ Os principais sacerdotes e os fariseus, ouvindo essas parábolas, entenderam que era deles que Jesus falava.

[[v40-21-46]]

^<<v40-21-46,46>>^ E procuravam prendê-lo, mas temeram o povo, porquanto este o tinha por profeta.

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]