include::./index.adoc[]

[[v40-12-0]]
=== Mateus, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-12-1]]

^<<v40-12-1,1>>^ Naquele tempo passou Jesus pelas searas num dia de sábado; e os seus discípulos, sentindo fome, começaram a colher espigas, e a comer.

[[v40-12-2]]

^<<v40-12-2,2>>^ Os fariseus, vendo isso, disseram-lhe: Eis que os teus discípulos estão fazendo o que não é lícito fazer no sábado.

[[v40-12-3]]

^<<v40-12-3,3>>^ Ele, porém, lhes disse: Acaso não lestes o que fez Davi, quando teve fome, ele e seus companheiros?

[[v40-12-4]]

^<<v40-12-4,4>>^ Como entrou na casa de Deus, e como eles comeram os pães da proposição, que não lhe era lícito comer, nem a seus companheiros, mas somente aos sacerdotes?

[[v40-12-5]]

^<<v40-12-5,5>>^ Ou não lestes na lei que, aos sábados, os sacerdotes no templo violam o sábado, e ficam sem culpa?

[[v40-12-6]]

^<<v40-12-6,6>>^ Digo-vos, porém, que aqui está o que é maior do que o templo.

[[v40-12-7]]

^<<v40-12-7,7>>^ Mas, se vós soubésseis o que significa: Misericórdia quero, e não sacrifícios, não condenaríeis os inocentes.

[[v40-12-8]]

^<<v40-12-8,8>>^ Porque o Filho do homem até do sábado é o Senhor.

[[v40-12-9]]

^<<v40-12-9,9>>^ Partindo dali, entrou Jesus na sinagoga deles.

[[v40-12-10]]

^<<v40-12-10,10>>^ E eis que estava ali um homem que tinha uma das mãos atrofiadas; e eles, para poderem acusar a Jesus, o interrogaram, dizendo: É lícito curar nos sábados?

[[v40-12-11]]

^<<v40-12-11,11>>^ E ele lhes disse: Qual dentre vós será o homem que, tendo uma só ovelha, se num sábado ela cair numa cova, não há de lançar mão dela, e tirá-la?

[[v40-12-12]]

^<<v40-12-12,12>>^ Ora, quanto mais vale um homem do que uma ovelha! Portanto, é lícito fazer bem nos sábados.

[[v40-12-13]]

^<<v40-12-13,13>>^ Então disse àquele homem: estende a tua mão. E ele a estendeu, e lhe foi restituída sã como a outra.

[[v40-12-14]]

^<<v40-12-14,14>>^ Os fariseus, porém, saindo dali, tomaram conselho contra ele, para o matarem.

[[v40-12-15]]

^<<v40-12-15,15>>^ Jesus, percebendo isso, retirou-se dali. Acompanharam-no muitos; e ele curou a todos,

[[v40-12-16]]

^<<v40-12-16,16>>^ e advertiu-lhes que não o dessem a conhecer;

[[v40-12-17]]

^<<v40-12-17,17>>^ para que se cumprisse o que foi dito pelo profeta Isaías:

[[v40-12-18]]

^<<v40-12-18,18>>^ Eis aqui o meu servo que escolhi, o meu amado em quem a minha alma se compraz; porei sobre ele o meu espírito, e ele anunciará aos gentios o juízo.

[[v40-12-19]]

^<<v40-12-19,19>>^ Não contenderá, nem clamará, nem se ouvirá pelas ruas a sua voz.

[[v40-12-20]]

^<<v40-12-20,20>>^ Não esmagará a cana quebrada, e não apagará o morrão que fumega, até que faça triunfar o juízo;

[[v40-12-21]]

^<<v40-12-21,21>>^ e no seu nome os gentios esperarão.

[[v40-12-22]]

^<<v40-12-22,22>>^ Trouxeram-lhe então um endemoninhado cego e mudo; e ele o curou, de modo que o mudo falava e via.

[[v40-12-23]]

^<<v40-12-23,23>>^ E toda a multidão, maravilhada, dizia: É este, porventura, o Filho de Davi?

[[v40-12-24]]

^<<v40-12-24,24>>^ Mas os fariseus, ouvindo isto, disseram: Este não expulsa os demônios senão por Belzebu, príncipe dos demônios.

[[v40-12-25]]

^<<v40-12-25,25>>^ Jesus, porém, conhecendo-lhes os pensamentos, disse-lhes: Todo reino dividido contra si mesmo é devastado; e toda cidade, ou casa, dividida contra si mesma não subsistirá.

[[v40-12-26]]

^<<v40-12-26,26>>^ Ora, se Satanás expulsa a Satanás, está dividido contra si mesmo; como subsistirá, pois, o seus reino?

[[v40-12-27]]

^<<v40-12-27,27>>^ E, se eu expulso os demônios por Belzebu, por quem os expulsam os vossos filhos? Por isso, eles mesmos serão os vossos juízes.

[[v40-12-28]]

^<<v40-12-28,28>>^ Mas, se é pelo Espírito de Deus que eu expulso os demônios, logo é chegado a vós o reino de Deus.

[[v40-12-29]]

^<<v40-12-29,29>>^ Ou, como pode alguém entrar na casa do valente, e roubar-lhe os bens, se primeiro não amarrar o valente? e então lhe saquear a casa.

[[v40-12-30]]

^<<v40-12-30,30>>^ Quem não é comigo é contra mim; e quem comigo não ajunta, espalha.

[[v40-12-31]]

^<<v40-12-31,31>>^ Portanto vos digo: Todo pecado e blasfêmia se perdoará aos homens; mas a blasfêmia contra o Espírito não será perdoada.

[[v40-12-32]]

^<<v40-12-32,32>>^ Se alguém disser alguma palavra contra o Filho do homem, isso lhe será perdoado; mas se alguém falar contra o Espírito Santo, não lhe será perdoado, nem neste mundo, nem no vindouro.

[[v40-12-33]]

^<<v40-12-33,33>>^ Ou fazei a árvore boa, e o seu fruto bom; ou fazei a árvore má, e o seu fruto mau; porque pelo fruto se conhece a árvore.

[[v40-12-34]]

^<<v40-12-34,34>>^ Raça de víboras! como podeis vós falar coisas boas, sendo maus? pois do que há em abundância no coração, disso fala a boca.

[[v40-12-35]]

^<<v40-12-35,35>>^ O homem bom, do seu bom tesouro tira coisas boas, e o homem mau do mau tesouro tira coisas más.

[[v40-12-36]]

^<<v40-12-36,36>>^ Digo-vos, pois, que de toda palavra fútil que os homens disserem, hão de dar conta no dia do juízo.

[[v40-12-37]]

^<<v40-12-37,37>>^ Porque pelas tuas palavras serás justificado, e pelas tuas palavras serás condenado.

[[v40-12-38]]

^<<v40-12-38,38>>^ Então alguns dos escribas e dos fariseus, tomando a palavra, disseram: Mestre, queremos ver da tua parte algum sinal.

[[v40-12-39]]

^<<v40-12-39,39>>^ Mas ele lhes respondeu: Uma geração má e adúltera pede um sinal; e nenhum sinal se lhe dará, senão o do profeta Jonas;

[[v40-12-40]]

^<<v40-12-40,40>>^ pois, como Jonas esteve três dias e três noites no ventre do grande peixe, assim estará o Filho do homem três dias e três noites no seio da terra.

[[v40-12-41]]

^<<v40-12-41,41>>^ Os ninivitas se levantarão no juízo com esta geração, e a condenarão; porque se arrependeram com a pregação de Jonas. E eis aqui quem é maior do que Jonas.

[[v40-12-42]]

^<<v40-12-42,42>>^ A rainha do sul se levantará no juízo com esta geração, e a condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão. E eis aqui quem é maior do que Salomão.

[[v40-12-43]]

^<<v40-12-43,43>>^ Ora, havendo o espírito imundo saído do homem, anda por lugares áridos, buscando repouso, e não o encontra.

[[v40-12-44]]

^<<v40-12-44,44>>^ Então diz: Voltarei para minha casa, donde saí. E, chegando, acha-a desocupada, varrida e adornada.

[[v40-12-45]]

^<<v40-12-45,45>>^ Então vai e leva consigo outros sete espíritos piores do que ele e, entretanto, habitam ali; e o último estado desse homem vem a ser pior do que o primeiro. Assim há de acontecer também a esta geração perversa.

[[v40-12-46]]

^<<v40-12-46,46>>^ Enquanto ele ainda falava às multidões, estavam do lado de fora sua mãe e seus irmãos, procurando falar-lhe.

[[v40-12-47]]

^<<v40-12-47,47>>^ Disse-lhe alguém: Eis que estão ali fora tua mãe e teus irmãos, e procuram falar contigo.

[[v40-12-48]]

^<<v40-12-48,48>>^ Ele, porém, respondeu ao que lhe falava: Quem é minha mãe? e quem são meus irmãos?

[[v40-12-49]]

^<<v40-12-49,49>>^ E, estendendo a mão para os seus discípulos disse: Eis aqui minha mãe e meus irmãos.

[[v40-12-50]]

^<<v40-12-50,50>>^ Pois qualquer que fizer a vontade de meu Pai que está nos céus, esse é meu irmão, irmã e mãe.

'''

xref:040-mateus/040-mateus-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-mateus/040-mateus-013.adoc#v40-13-0[Próximo Capítulo &#62;]