include::./index.adoc[]

[[v40-22-0]]
=== Mateus, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-22-1]]

^<<v40-22-1,1>>^ Então Jesus tornou a falar-lhes por parábolas, dizendo:

[[v40-22-2]]

^<<v40-22-2,2>>^ O reino dos céus é semelhante a um rei, que celebrou as bodas de seu filho.

[[v40-22-3]]

^<<v40-22-3,3>>^ Enviou os seus servos a chamar os convidados para a festa, e estes não quiseram vir.

[[v40-22-4]]

^<<v40-22-4,4>>^ Enviou ainda outros servos com este recado: Dizei aos convidados: Tenho já preparado o meu banquete; as minhas reses e os meus cevados estão mortos, e tudo está pronto; vinde às bodas.

[[v40-22-5]]

^<<v40-22-5,5>>^ Mas eles não fizeram caso e foram, um para o seu campo, outro para o seu negócio;

[[v40-22-6]]

^<<v40-22-6,6>>^ e os outros, agarrando os servos, os ultrajaram e mataram.

[[v40-22-7]]

^<<v40-22-7,7>>^ Irou-se o rei, e mandou as suas tropas exterminar aqueles assassinos e incendiar a sua cidade.

[[v40-22-8]]

^<<v40-22-8,8>>^ Então disse aos servos: As bodas estão preparadas, mas os convidados não eram dignos;

[[v40-22-9]]

^<<v40-22-9,9>>^ ide, pois, às encruzilhadas dos caminhos e chamai para as bodas a quantos encontrardes.

[[v40-22-10]]

^<<v40-22-10,10>>^ Indo aqueles servos pelos caminhos, reuniram todos os que encontraram, maus e bons; e a sala nupcial ficou cheia de convivas.

[[v40-22-11]]

^<<v40-22-11,11>>^ Mas entrando o rei para ver os convivas, notou ali um homem que não trajava veste nupcial,

[[v40-22-12]]

^<<v40-22-12,12>>^ e perguntou-lhe: Amigo, como entraste aqui sem veste nupcial? Ele, porém, emudeceu.

[[v40-22-13]]

^<<v40-22-13,13>>^ Então o rei disse aos servos: Atai-o de pés e mãos, e lançai-o nas trevas exteriores; ali haverá o choro e o ranger de dentes.

[[v40-22-14]]

^<<v40-22-14,14>>^ Pois muitos são chamados, mas poucos escolhidos.

[[v40-22-15]]

^<<v40-22-15,15>>^ Então os fariseus se retiraram e consultaram entre si como o apanhariam em alguma palavra;

[[v40-22-16]]

^<<v40-22-16,16>>^ Enviaram os seus discípulos, juntamente com os herodianos, a perguntar: Mestre, sabemos que és verdadeiro e que ensinas o caminho de Deus segundo a verdade, e não se te dá de ninguém, porque não te deixas levar de respeitos humanos;

[[v40-22-17]]

^<<v40-22-17,17>>^ dize-nos, pois, qual é o teu parecer; é lícito ou não pagar o tributo a César?

[[v40-22-18]]

^<<v40-22-18,18>>^ Porém Jesus, tendo percebido a malícia deles, respondeu-lhes: Por que me experimentais, hipócritas?

[[v40-22-19]]

^<<v40-22-19,19>>^ Mostrai-me uma moeda de tributo. Trouxeram-lhe um denário.

[[v40-22-20]]

^<<v40-22-20,20>>^ Ele perguntou: De quem é esta efígie e inscrição?

[[v40-22-21]]

^<<v40-22-21,21>>^ Responderam: De César. Então lhes disse Jesus: Dai, pois, a César o que é de César, e a Deus o que é de Deus.

[[v40-22-22]]

^<<v40-22-22,22>>^ Ao ouvirem isto, admiraram-se e, deixando-o, foram-se.

[[v40-22-23]]

^<<v40-22-23,23>>^ No mesmo dia vieram alguns saduceus, que dizem não haver ressurreição, e o interrogaram, dizendo:

[[v40-22-24]]

^<<v40-22-24,24>>^ Mestre, Moisés disse: Se alguém morrer sem deixar filhos, seu irmão casará com a viúva e dará sucessão ao falecido.

[[v40-22-25]]

^<<v40-22-25,25>>^ Ora havia entre nós sete irmãos: o primeiro, depois de ter casado, morreu e, não havendo sucessão, deixou sua mulher a seu irmão;

[[v40-22-26]]

^<<v40-22-26,26>>^ do mesmo modo também o segundo e o terceiro, até o sétimo.

[[v40-22-27]]

^<<v40-22-27,27>>^ Depois de todos eles morreu a mulher.

[[v40-22-28]]

^<<v40-22-28,28>>^ Na ressurreição, pois, a qual dos sete pertencerá a mulher? porque todos foram casados com ela.

[[v40-22-29]]

^<<v40-22-29,29>>^ Respondeu-lhes Jesus: Errais, não sabendo as Escrituras, nem o poder de Deus.

[[v40-22-30]]

^<<v40-22-30,30>>^ Pois na ressurreição nem os homens casam, nem as mulheres são dadas em casamento porém são como os anjos no céu.

[[v40-22-31]]

^<<v40-22-31,31>>^ E, quanto à ressurreição dos mortos, não lestes o que foi dito por Deus:

[[v40-22-32]]

^<<v40-22-32,32>>^ Eu sou o Deus de Abraão, o Deus de Isaque, e o Deus de Jacó? Ora, ele não é Deus de mortos, mas de vivos.

[[v40-22-33]]

^<<v40-22-33,33>>^ E as multidões, ouvindo isso, se maravilhavam da sua doutrina.

[[v40-22-34]]

^<<v40-22-34,34>>^ Os fariseus, quando souberam, que ele fizera emudecer os saduceus, reuniram-se todos;

[[v40-22-35]]

^<<v40-22-35,35>>^ e um deles, doutor da lei, para o experimentar, interrogou-o, dizendo:

[[v40-22-36]]

^<<v40-22-36,36>>^ Mestre, qual é o grande mandamento na lei?

[[v40-22-37]]

^<<v40-22-37,37>>^ Respondeu-lhe Jesus: Amarás ao Senhor teu Deus de todo o teu coração, de toda a tua alma, e de todo o teu entendimento.

[[v40-22-38]]

^<<v40-22-38,38>>^ Este é o grande e primeiro mandamento.

[[v40-22-39]]

^<<v40-22-39,39>>^ E o segundo, semelhante a este, é: Amarás ao teu próximo como a ti mesmo.

[[v40-22-40]]

^<<v40-22-40,40>>^ Destes dois mandamentos dependem toda a lei e os profetas.

[[v40-22-41]]

^<<v40-22-41,41>>^ Ora, enquanto os fariseus estavam reunidos, interrogou-os Jesus, dizendo:

[[v40-22-42]]

^<<v40-22-42,42>>^ Que pensais vós do Cristo? De quem é filho? Responderam-lhe: De Davi.

[[v40-22-43]]

^<<v40-22-43,43>>^ Replicou-lhes ele: Como é então que Davi, no Espírito, lhe chama Senhor, dizendo:

[[v40-22-44]]

^<<v40-22-44,44>>^ Disse o Senhor ao meu Senhor: Assenta-te à minha direita, até que eu ponha os teus inimigos de baixo dos teus pés?

[[v40-22-45]]

^<<v40-22-45,45>>^ Se Davi, pois, lhe chama Senhor, como é ele seu filho?

[[v40-22-46]]

^<<v40-22-46,46>>^ E ninguém podia responder-lhe palavra; nem desde aquele dia jamais ousou alguém interrogá-lo.

'''

xref:040-mateus/040-mateus-021.adoc#v40-21-0[&#60; Capítulo Anterior] | <<v40-22-0,Topo>> | xref:040-mateus/040-mateus-023.adoc#v40-23-0[Próximo Capítulo &#62;]