include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-16-1]]

^<<v40-16-1,1>>^ Então chegaram a ele os fariseus e os saduceus e, para o experimentarem, pediram-lhe que lhes mostrasse algum sinal do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Mas ele respondeu, e disse-lhes: Ao cair da tarde, dizeis: Haverá bom tempo, porque o céu está rubro.

[[v40-16-3]]

^<<v40-16-3,3>>^ E pela manhã: Hoje haverá tempestade, porque o céu está de um vermelho sombrio. Ora, sabeis discernir o aspecto do céu, e não podeis discernir os sinais dos tempos?

[[v40-16-4]]

^<<v40-16-4,4>>^ Uma geração má e adúltera pede um sinal, e nenhum sinal lhe será dado, senão o de Jonas. E, deixando-os, retirou-se.

[[v40-16-5]]

^<<v40-16-5,5>>^ Quando os discípulos passaram para o outro lado, esqueceram-se de levar pão.

[[v40-16-6]]

^<<v40-16-6,6>>^ E Jesus lhes disse: Olhai, e acautelai-vos do fermento dos fariseus e dos saduceus.

[[v40-16-7]]

^<<v40-16-7,7>>^ Pelo que eles arrazoavam entre si, dizendo: É porque não trouxemos pão.

[[v40-16-8]]

^<<v40-16-8,8>>^ E Jesus, percebendo isso, disse: Por que arrazoais entre vós por não terdes pão, homens de pouca fé?

[[v40-16-9]]

^<<v40-16-9,9>>^ Não compreendeis ainda, nem vos lembrais dos cinco pães para os cinco mil, e de quantos cestos levantastes?

[[v40-16-10]]

^<<v40-16-10,10>>^ Nem dos sete pães para os quatro mil, e de quantas alcofas levantastes?

[[v40-16-11]]

^<<v40-16-11,11>>^ Como não compreendeis que não nos falei a respeito de pães? Mas guardai-vos do fermento dos fariseus e dos saduceus.

[[v40-16-12]]

^<<v40-16-12,12>>^ Então entenderam que não dissera que se guardassem, do fermento dos pães, mas da doutrina dos fariseus e dos saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Tendo Jesus chegado às regiões de Cesaréia de Felipe, interrogou os seus discípulos, dizendo: Quem dizem os homens ser o Filho do homem?

[[v40-16-14]]

^<<v40-16-14,14>>^ Responderam eles: Uns dizem que é João, o Batista; outros, Elias; outros, Jeremias, ou algum dos profetas.

[[v40-16-15]]

^<<v40-16-15,15>>^ Mas vós, perguntou-lhes Jesus, quem dizeis que eu sou?

[[v40-16-16]]

^<<v40-16-16,16>>^ Respondeu-lhe Simão Pedro: Tu és o Cristo, o Filho do Deus vivo.

[[v40-16-17]]

^<<v40-16-17,17>>^ Disse-lhe Jesus: Bem-aventurado és tu, Simão Barjonas, porque não foi carne e sangue que to revelou, mas meu Pai, que está nos céus.

[[v40-16-18]]

^<<v40-16-18,18>>^ Pois também eu te digo que tu és Pedro, e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela;

[[v40-16-19]]

^<<v40-16-19,19>>^ dar-te-ei as chaves do reino dos céus; o que ligares, pois, na terra será ligado nos céus, e o que desligares na terra será desligado nos céus.

[[v40-16-20]]

^<<v40-16-20,20>>^ Então ordenou aos discípulos que a ninguém dissessem que ele era o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Desde então começou Jesus Cristo a mostrar aos seus discípulos que era necessário que ele fosse a Jerusalém, que padecesse muitas coisas dos anciãos, dos principais sacerdotes, e dos escribas, que fosse morto, e que ao terceiro dia ressuscitasse.

[[v40-16-22]]

^<<v40-16-22,22>>^ E Pedro, tomando-o à parte, começou a repreendê-lo, dizendo: Tenha Deus compaixão de ti, Senhor; isso de modo nenhum te acontecerá.

[[v40-16-23]]

^<<v40-16-23,23>>^ Ele, porém, voltando-se, disse a Pedro: Para trás de mim, Satanás, que me serves de escândalo; porque não estás pensando nas coisas que são de Deus, mas sim nas que são dos homens.

[[v40-16-24]]

^<<v40-16-24,24>>^ Então disse Jesus aos seus discípulos: Se alguém quer vir após mim, negue-se a si mesmo, tome a sua cruz, e siga-me;

[[v40-16-25]]

^<<v40-16-25,25>>^ pois, quem quiser salvar a sua vida por amor de mim perdê-la-á; mas quem perder a sua vida por amor de mim, achá-la-á.

[[v40-16-26]]

^<<v40-16-26,26>>^ Pois que aproveita ao homem se ganhar o mundo inteiro e perder a sua vida? ou que dará o homem em troca da sua vida?

[[v40-16-27]]

^<<v40-16-27,27>>^ Porque o Filho do homem há de vir na glória de seu Pai, com os seus anjos; e então retribuirá a cada um segundo as suas obras.

[[v40-16-28]]

^<<v40-16-28,28>>^ Em verdade vos digo, alguns dos que aqui estão de modo nenhum provarão a morte até que vejam vir o Filho do homem no seu reino.

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]