include::./index.adoc[]

[[v40-1-0]]
=== Mateus, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-1-1]]

^<<v40-1-1,1>>^ Livro da genealogia de Jesus Cristo, filho de Davi, filho de Abraão.

[[v40-1-2]]

^<<v40-1-2,2>>^ A Abraão nasceu Isaque; a Isaque nasceu Jacó; a Jacó nasceram Judá e seus irmãos;

[[v40-1-3]]

^<<v40-1-3,3>>^ a Judá nasceram, de Tamar, Farés e Zará; a Farés nasceu Esrom; a Esrom nasceu Arão;

[[v40-1-4]]

^<<v40-1-4,4>>^ a Arão nasceu Aminadabe; a Aminadabe nasceu Nasom; a Nasom nasceu Salmom;

[[v40-1-5]]

^<<v40-1-5,5>>^ a Salmom nasceu, de Raabe, Booz; a Booz nasceu, de Rute, Obede; a Obede nasceu Jessé;

[[v40-1-6]]

^<<v40-1-6,6>>^ e a Jessé nasceu o rei Davi. A Davi nasceu Salomão da que fora mulher de Urias;

[[v40-1-7]]

^<<v40-1-7,7>>^ a Salomão nasceu Roboão; a Roboão nasceu Abias; a nasceu Abias nasceu Asafe;

[[v40-1-8]]

^<<v40-1-8,8>>^ a Asafe nasceu Josafá; a Josafá nasceu Jorão; a Jorão Ozias;

[[v40-1-9]]

^<<v40-1-9,9>>^ a Ozias nasceu Joatão; a Joatão nasceu Acaz; a Acaz nasceu Ezequias;

[[v40-1-10]]

^<<v40-1-10,10>>^ a Ezequias nasceu Manassés; a Manassés nasceu Amom; a Amom nasceu Josias;

[[v40-1-11]]

^<<v40-1-11,11>>^ a Josias nasceram Jeconias e seus irmãos, no tempo da deportação para Babilônia.

[[v40-1-12]]

^<<v40-1-12,12>>^ Depois da deportação para Babilônia nasceu a Jeconias, Salatiel; a Salatiel nasceu Zorobabel;

[[v40-1-13]]

^<<v40-1-13,13>>^ a Zorobabel nasceu Abiúde; a Abiúde nasceu Eliaquim; a Eliaquim nasceu Azor;

[[v40-1-14]]

^<<v40-1-14,14>>^ a Azor nasceu Sadoque; a Sadoque nasceu Aquim; a Aquim nasceu Eliúde;

[[v40-1-15]]

^<<v40-1-15,15>>^ a Eliúde nasceu Eleazar; a Eleazar nasceu Matã; a Matã nasceu Jacó;

[[v40-1-16]]

^<<v40-1-16,16>>^ e a Jacó nasceu José, marido de Maria, da qual nasceu JESUS, que se chama Cristo.

[[v40-1-17]]

^<<v40-1-17,17>>^ De sorte que todas as gerações, desde Abraão até Davi, são catorze gerações; e desde Davi até a deportação para Babilônia, catorze gerações; e desde a deportação para Babilônia até o Cristo, catorze gerações.

[[v40-1-18]]

^<<v40-1-18,18>>^ Ora, o nascimento de Jesus Cristo foi assim: Estando Maria, sua mãe, desposada com José, antes de se ajuntarem, ela se achou ter concebido do Espírito Santo.

[[v40-1-19]]

^<<v40-1-19,19>>^ E como José, seu esposo, era justo, e não a queria infamar, intentou deixá-la secretamente.

[[v40-1-20]]

^<<v40-1-20,20>>^ E, projetando ele isso, eis que em sonho lhe apareceu um anjo do Senhor, dizendo: José, filho de Davi, não temas receber a Maria, tua mulher, pois o que nela se gerou é do Espírito Santo;

[[v40-1-21]]

^<<v40-1-21,21>>^ ela dará à luz um filho, a quem chamarás JESUS; porque ele salvará o seu povo dos seus pecados.

[[v40-1-22]]

^<<v40-1-22,22>>^ Ora, tudo isso aconteceu para que se cumprisse o que fora dito da parte do Senhor pelo profeta:

[[v40-1-23]]

^<<v40-1-23,23>>^ Eis que a virgem conceberá e dará à luz um filho, o qual será chamado EMANUEL, que traduzido é: Deus conosco.

[[v40-1-24]]

^<<v40-1-24,24>>^ E José, tendo despertado do sono, fez como o anjo do Senhor lhe ordenara, e recebeu sua mulher;

[[v40-1-25]]

^<<v40-1-25,25>>^ e não a conheceu enquanto ela não deu à luz um filho; e pôs-lhe o nome de JESUS.

'''

xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[&#60; Capítulo Anterior] | <<v40-1-0,Topo>> | xref:040-mateus/040-mateus-002.adoc#v40-2-0[Próximo Capítulo &#62;]