include::./index.adoc[]

[[v40-24-0]]
=== Mateus, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-24-1]]

^<<v40-24-1,1>>^ Ora, Jesus, tendo saído do templo, ia-se retirando, quando se aproximaram dele os seus discípulos, para lhe mostrarem os edifícios do templo.

[[v40-24-2]]

^<<v40-24-2,2>>^ Mas ele lhes disse: Não vedes tudo isto? Em verdade vos digo que não se deixará aqui pedra sobre pedra que não seja derribada.

[[v40-24-3]]

^<<v40-24-3,3>>^ E estando ele sentado no Monte das Oliveiras, chegaram-se a ele os seus discípulos em particular, dizendo: Declara-nos quando serão essas coisas, e que sinal haverá da tua vinda e do fim do mundo.

[[v40-24-4]]

^<<v40-24-4,4>>^ Respondeu-lhes Jesus: Acautelai-vos, que ninguém vos engane.

[[v40-24-5]]

^<<v40-24-5,5>>^ Porque muitos virão em meu nome, dizendo: Eu sou o Cristo; a muitos enganarão.

[[v40-24-6]]

^<<v40-24-6,6>>^ E ouvireis falar de guerras e rumores de guerras; olhai não vos perturbeis; porque forçoso é que assim aconteça; mas ainda não é o fim.

[[v40-24-7]]

^<<v40-24-7,7>>^ Porquanto se levantará nação contra nação, e reino contra reino; e haverá fomes e terremotos em vários lugares.

[[v40-24-8]]

^<<v40-24-8,8>>^ Mas todas essas coisas são o princípio das dores.

[[v40-24-9]]

^<<v40-24-9,9>>^ Então sereis entregues à tortura, e vos matarão; e sereis odiados de todas as nações por causa do meu nome.

[[v40-24-10]]

^<<v40-24-10,10>>^ Nesse tempo muitos hão de se escandalizar, e trair-se uns aos outros, e mutuamente se odiarão.

[[v40-24-11]]

^<<v40-24-11,11>>^ Igualmente hão de surgir muitos falsos profetas, e enganarão a muitos;

[[v40-24-12]]

^<<v40-24-12,12>>^ e, por se multiplicar a iniqüidade, o amor de muitos esfriará.

[[v40-24-13]]

^<<v40-24-13,13>>^ Mas quem perseverar até o fim, esse será salvo.

[[v40-24-14]]

^<<v40-24-14,14>>^ E este evangelho do reino será pregado no mundo inteiro, em testemunho a todas as nações, e então virá o fim.

[[v40-24-15]]

^<<v40-24-15,15>>^ Quando, pois, virdes estar no lugar santo a abominação de desolação, predita pelo profeta Daniel &#123;quem lê, entenda&#125;,

[[v40-24-16]]

^<<v40-24-16,16>>^ então os que estiverem na Judéia fujam para os montes;

[[v40-24-17]]

^<<v40-24-17,17>>^ quem estiver no eirado não desça para tirar as coisas de sua casa,

[[v40-24-18]]

^<<v40-24-18,18>>^ e quem estiver no campo não volte atrás para apanhar a sua capa.

[[v40-24-19]]

^<<v40-24-19,19>>^ Mas ai das que estiverem grávidas, e das que amamentarem naqueles dias!

[[v40-24-20]]

^<<v40-24-20,20>>^ Orai para que a vossa fuga não suceda no inverno nem no sábado;

[[v40-24-21]]

^<<v40-24-21,21>>^ porque haverá então uma tribulação tão grande, como nunca houve desde o princípio do mundo até agora, nem jamais haverá.

[[v40-24-22]]

^<<v40-24-22,22>>^ E se aqueles dias não fossem abreviados, ninguém se salvaria; mas por causa dos escolhidos serão abreviados aqueles dias.

[[v40-24-23]]

^<<v40-24-23,23>>^ Se, pois, alguém vos disser: Eis aqui o Cristo! ou: Ei-lo aí! não acrediteis;

[[v40-24-24]]

^<<v40-24-24,24>>^ porque hão de surgir falsos cristos e falsos profetas, e farão grandes sinais e prodígios; de modo que, se possível fora, enganariam até os escolhidos.

[[v40-24-25]]

^<<v40-24-25,25>>^ Eis que de antemão vo-lo tenho dito.

[[v40-24-26]]

^<<v40-24-26,26>>^ Portanto, se vos disserem: Eis que ele está no deserto; não saiais; ou: Eis que ele está no interior da casa; não acrediteis.

[[v40-24-27]]

^<<v40-24-27,27>>^ Porque, assim como o relâmpago sai do oriente e se mostra até o ocidente, assim será também a vinda do filho do homem.

[[v40-24-28]]

^<<v40-24-28,28>>^ Pois onde estiver o cadáver, aí se ajuntarão os abutres.

[[v40-24-29]]

^<<v40-24-29,29>>^ Logo depois da tribulação daqueles dias, escurecerá o sol, e a lua não dará a sua luz; as estrelas cairão do céu e os poderes dos céus serão abalados.

[[v40-24-30]]

^<<v40-24-30,30>>^ Então aparecerá no céu o sinal do Filho do homem, e todas as tribos da terra se lamentarão, e verão vir o Filho do homem sobre as nuvens do céu, com poder e grande glória.

[[v40-24-31]]

^<<v40-24-31,31>>^ E ele enviará os seus anjos com grande clangor de trombeta, os quais lhe ajuntarão os escolhidos desde os quatro ventos, de uma à outra extremidade dos céus.

[[v40-24-32]]

^<<v40-24-32,32>>^ Aprendei, pois, da figueira a sua parábola: Quando já o seu ramo se torna tenro e brota folhas, sabeis que está próximo o verão.

[[v40-24-33]]

^<<v40-24-33,33>>^ Igualmente, quando virdes todas essas coisas, sabei que ele está próximo, mesmo às portas.

[[v40-24-34]]

^<<v40-24-34,34>>^ Em verdade vos digo que não passará esta geração sem que todas essas coisas se cumpram.

[[v40-24-35]]

^<<v40-24-35,35>>^ Passará o céu e a terra, mas as minhas palavras jamais passarão.

[[v40-24-36]]

^<<v40-24-36,36>>^ Daquele dia e hora, porém, ninguém sabe, nem os anjos do céu, nem o Filho, senão só o Pai.

[[v40-24-37]]

^<<v40-24-37,37>>^ Pois como foi dito nos dias de Noé, assim será também a vinda do Filho do homem.

[[v40-24-38]]

^<<v40-24-38,38>>^ Porquanto, assim como nos dias anteriores ao dilúvio, comiam, bebiam, casavam e davam-se em casamento, até o dia em que Noé entrou na arca,

[[v40-24-39]]

^<<v40-24-39,39>>^ e não o perceberam, até que veio o dilúvio, e os levou a todos; assim será também a vinda do Filho do homem.

[[v40-24-40]]

^<<v40-24-40,40>>^ Então, estando dois homens no campo, será levado um e deixado outro;

[[v40-24-41]]

^<<v40-24-41,41>>^ estando duas mulheres a trabalhar no moinho, será levada uma e deixada a outra.

[[v40-24-42]]

^<<v40-24-42,42>>^ Vigiai, pois, porque não sabeis em que dia vem o vosso Senhor;

[[v40-24-43]]

^<<v40-24-43,43>>^ sabei, porém, isto: se o dono da casa soubesse a que vigília da noite havia de vir o ladrão, vigiaria e não deixaria minar a sua casa.

[[v40-24-44]]

^<<v40-24-44,44>>^ Por isso ficai também vós apercebidos; porque numa hora em que não penseis, virá o Filho do homem.

[[v40-24-45]]

^<<v40-24-45,45>>^ Quem é, pois, o servo fiel e prudente, que o senhor pôs sobre os seus serviçais, para a tempo dar-lhes o sustento?

[[v40-24-46]]

^<<v40-24-46,46>>^ Bem-aventurado aquele servo a quem o seu senhor, quando vier, achar assim fazendo.

[[v40-24-47]]

^<<v40-24-47,47>>^ Em verdade vos digo que o porá sobre todos os seus bens.

[[v40-24-48]]

^<<v40-24-48,48>>^ Mas se aquele outro, o mau servo, disser no seu coração: Meu senhor tarda em vir,

[[v40-24-49]]

^<<v40-24-49,49>>^ e começar a espancar os seus conservos, e a comer e beber com os ébrios,

[[v40-24-50]]

^<<v40-24-50,50>>^ virá o senhor daquele servo, num dia em que não o espera, e numa hora de que não sabe,

[[v40-24-51]]

^<<v40-24-51,51>>^ e cortá-lo-á pelo meio, e lhe dará a sua parte com os hipócritas; ali haverá choro e ranger de dentes.

'''

xref:040-mateus/040-mateus-023.adoc#v40-23-0[&#60; Capítulo Anterior] | <<v40-24-0,Topo>> | xref:040-mateus/040-mateus-025.adoc#v40-25-0[Próximo Capítulo &#62;]