include::./index.adoc[]

[[v40-5-0]]
=== Mateus, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-5-1]]

^<<v40-5-1,1>>^ Jesus, pois, vendo as multidões, subiu ao monte; e, tendo se assentado, aproximaram-se os seus discípulos,

[[v40-5-2]]

^<<v40-5-2,2>>^ e ele se pôs a ensiná-los, dizendo:

[[v40-5-3]]

^<<v40-5-3,3>>^ Bem-aventurados os humildes de espírito, porque deles é o reino dos céus.

[[v40-5-4]]

^<<v40-5-4,4>>^ Bem-aventurados os que choram, porque eles serão consolados.

[[v40-5-5]]

^<<v40-5-5,5>>^ Bem-aventurados os mansos, porque eles herdarão a terra.

[[v40-5-6]]

^<<v40-5-6,6>>^ Bem-aventurados os que têm fome e sede de justiça porque eles serão fartos.

[[v40-5-7]]

^<<v40-5-7,7>>^ Bem-aventurados os misericordiosos, porque eles alcançarão misericórdia.

[[v40-5-8]]

^<<v40-5-8,8>>^ Bem-aventurados os limpos de coração, porque eles verão a Deus.

[[v40-5-9]]

^<<v40-5-9,9>>^ Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.

[[v40-5-10]]

^<<v40-5-10,10>>^ Bem-aventurados os que são perseguidos por causa da justiça, porque deles é o reino dos céus.

[[v40-5-11]]

^<<v40-5-11,11>>^ Bem-aventurados sois vós, quando vos injuriarem e perseguiram e, mentindo, disserem todo mal contra vós por minha causa.

[[v40-5-12]]

^<<v40-5-12,12>>^ Alegrai-vos e exultai, porque é grande o vosso galardão nos céus; porque assim perseguiram aos profetas que foram antes de vós.

[[v40-5-13]]

^<<v40-5-13,13>>^ Vós sois o sal da terra; mas se o sal se tornar insípido, com que se há de restaurar-lhe o sabor? para nada mais presta, senão para ser lançado fora, e ser pisado pelos homens.

[[v40-5-14]]

^<<v40-5-14,14>>^ Vós sois a luz do mundo. Não se pode esconder uma cidade situada sobre um monte;

[[v40-5-15]]

^<<v40-5-15,15>>^ nem os que acendem uma candeia a colocam debaixo do alqueire, mas no velador, e assim ilumina a todos que estão na casa.

[[v40-5-16]]

^<<v40-5-16,16>>^ Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras, e glorifiquem a vosso Pai, que está nos céus.

[[v40-5-17]]

^<<v40-5-17,17>>^ Não penseis que vim destruir a lei ou os profetas; não vim destruir, mas cumprir.

[[v40-5-18]]

^<<v40-5-18,18>>^ Porque em verdade vos digo que, até que o céu e a terra passem, de modo nenhum passará da lei um só i ou um só til, até que tudo seja cumprido.

[[v40-5-19]]

^<<v40-5-19,19>>^ Qualquer, pois, que violar um destes mandamentos, por menor que seja, e assim ensinar aos homens, será chamado o menor no reino dos céus; aquele, porém, que os cumprir e ensinar será chamado grande no reino dos céus.

[[v40-5-20]]

^<<v40-5-20,20>>^ Pois eu vos digo que, se a vossa justiça não exceder a dos escribas e fariseus, de modo nenhum entrareis no reino dos céus.

[[v40-5-21]]

^<<v40-5-21,21>>^ Ouvistes que foi dito aos antigos: Não matarás; e, Quem matar será réu de juízo.

[[v40-5-22]]

^<<v40-5-22,22>>^ Eu, porém, vos digo que todo aquele que se encolerizar contra seu irmão, será réu de juízo; e quem disser a seu irmão: Raca, será réu diante do sinédrio; e quem lhe disser: Tolo, será réu do fogo do inferno.

[[v40-5-23]]

^<<v40-5-23,23>>^ Portanto, se estiveres apresentando a tua oferta no altar, e aí te lembrares de que teu irmão tem alguma coisa contra ti,

[[v40-5-24]]

^<<v40-5-24,24>>^ deixa ali diante do altar a tua oferta, e vai conciliar-te primeiro com teu irmão, e depois vem apresentar a tua oferta.

[[v40-5-25]]

^<<v40-5-25,25>>^ Concilia-te depressa com o teu adversário, enquanto estás no caminho com ele; para que não aconteça que o adversário te entregue ao guarda, e sejas lançado na prisão.

[[v40-5-26]]

^<<v40-5-26,26>>^ Em verdade te digo que de maneira nenhuma sairás dali enquanto não pagares o último ceitil.

[[v40-5-27]]

^<<v40-5-27,27>>^ Ouvistes que foi dito: Não adulterarás.

[[v40-5-28]]

^<<v40-5-28,28>>^ Eu, porém, vos digo que todo aquele que olhar para uma mulher para a cobiçar, já em seu coração cometeu adultério com ela.

[[v40-5-29]]

^<<v40-5-29,29>>^ Se o teu olho direito te faz tropeçar, arranca-o e lança-o de ti; pois te é melhor que se perca um dos teus membros do que seja todo o teu corpo lançado no inferno.

[[v40-5-30]]

^<<v40-5-30,30>>^ E, se a tua mão direita te faz tropeçar, corta-a e lança-a de ti; pois te é melhor que se perca um dos teus membros do que vá todo o teu corpo para o inferno.

[[v40-5-31]]

^<<v40-5-31,31>>^ Também foi dito: Quem repudiar sua mulher, dê-lhe carta de divórcio.

[[v40-5-32]]

^<<v40-5-32,32>>^ Eu, porém, vos digo que todo aquele que repudia sua mulher, a não ser por causa de infidelidade, a faz adúltera; e quem casar com a repudiada, comete adultério.

[[v40-5-33]]

^<<v40-5-33,33>>^ Outrossim, ouvistes que foi dito aos antigos: Não jurarás falso, mas cumprirás para com o Senhor os teus juramentos.

[[v40-5-34]]

^<<v40-5-34,34>>^ Eu, porém, vos digo que de maneira nenhuma jureis; nem pelo céu, porque é o trono de Deus;

[[v40-5-35]]

^<<v40-5-35,35>>^ nem pela terra, porque é o escabelo de seus pés; nem por Jerusalém, porque é a cidade do grande Rei;

[[v40-5-36]]

^<<v40-5-36,36>>^ nem jures pela tua cabeça, porque não podes tornar um só cabelo branco ou preto.

[[v40-5-37]]

^<<v40-5-37,37>>^ Seja, porém, o vosso falar: Sim, sim; não, não; pois o que passa daí, vem do Maligno.

[[v40-5-38]]

^<<v40-5-38,38>>^ Ouvistes que foi dito: Olho por olho, e dente por dente.

[[v40-5-39]]

^<<v40-5-39,39>>^ Eu, porém, vos digo que não resistais ao homem mau; mas a qualquer que te bater na face direita, oferece-lhe também a outra;

[[v40-5-40]]

^<<v40-5-40,40>>^ e ao que quiser pleitear contigo, e tirar-te a túnica, larga-lhe também a capa;

[[v40-5-41]]

^<<v40-5-41,41>>^ e, se qualquer te obrigar a caminhar mil passos, vai com ele dois mil.

[[v40-5-42]]

^<<v40-5-42,42>>^ Dá a quem te pedir, e não voltes as costas ao que quiser que lhe emprestes.

[[v40-5-43]]

^<<v40-5-43,43>>^ Ouvistes que foi dito: Amarás ao teu próximo, e odiarás ao teu inimigo.

[[v40-5-44]]

^<<v40-5-44,44>>^ Eu, porém, vos digo: Amai aos vossos inimigos, e orai pelos que vos perseguem;

[[v40-5-45]]

^<<v40-5-45,45>>^ para que vos torneis filhos do vosso Pai que está nos céus; porque ele faz nascer o seu sol sobre maus e bons, e faz chover sobre justos e injustos.

[[v40-5-46]]

^<<v40-5-46,46>>^ Pois, se amardes aos que vos amam, que recompensa tereis? não fazem os publicanos também o mesmo?

[[v40-5-47]]

^<<v40-5-47,47>>^ E, se saudardes somente os vossos irmãos, que fazeis demais? não fazem os gentios também o mesmo?

[[v40-5-48]]

^<<v40-5-48,48>>^ Sede vós, pois, perfeitos, como é perfeito o vosso Pai celestial.

'''

xref:040-mateus/040-mateus-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-mateus/040-mateus-006.adoc#v40-6-0[Próximo Capítulo &#62;]