include::./index.adoc[]

[[v40-2-0]]
=== Mateus, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-2-1]]

^<<v40-2-1,1>>^ Tendo, pois, nascido Jesus em Belém da Judéia, no tempo do rei Herodes, eis que vieram do oriente a Jerusalém uns magos que perguntavam:

[[v40-2-2]]

^<<v40-2-2,2>>^ Onde está aquele que é nascido rei dos judeus? pois do oriente vimos a sua estrela e viemos adorá-lo.

[[v40-2-3]]

^<<v40-2-3,3>>^ O rei Herodes, ouvindo isso, perturbou-se, e com ele toda a Jerusalém;

[[v40-2-4]]

^<<v40-2-4,4>>^ e, reunindo todos os principais sacerdotes e os escribas do povo, perguntava-lhes onde havia de nascer o Cristo.

[[v40-2-5]]

^<<v40-2-5,5>>^ Responderam-lhe eles: Em Belém da Judéia; pois assim está escrito pelo profeta:

[[v40-2-6]]

^<<v40-2-6,6>>^ E tu, Belém, terra de Judá, de modo nenhum és a menor entre as principais cidades de Judá; porque de ti sairá o Guia que há de apascentar o meu povo de Israel.

[[v40-2-7]]

^<<v40-2-7,7>>^ Então Herodes chamou secretamente os magos, e deles inquiriu com precisão acerca do tempo em que a estrela aparecera;

[[v40-2-8]]

^<<v40-2-8,8>>^ e enviando-os a Belém, disse-lhes: Ide, e perguntai diligentemente pelo menino; e, quando o achardes, participai-mo, para que também eu vá e o adore.

[[v40-2-9]]

^<<v40-2-9,9>>^ Tendo eles, pois, ouvido o rei, partiram; e eis que a estrela que tinham visto quando no oriente ia adiante deles, até que, chegando, se deteve sobre o lugar onde estava o menino.

[[v40-2-10]]

^<<v40-2-10,10>>^ Ao verem eles a estrela, regozijaram-se com grande alegria.

[[v40-2-11]]

^<<v40-2-11,11>>^ E entrando na casa, viram o menino com Maria sua mãe e, prostrando-se, o adoraram; e abrindo os seus tesouros, ofertaram-lhe dádivas: ouro incenso e mirra.

[[v40-2-12]]

^<<v40-2-12,12>>^ Ora, sendo por divina revelação avisados em sonhos para não voltarem a Herodes, regressaram à sua terra por outro caminho.

[[v40-2-13]]

^<<v40-2-13,13>>^ E, havendo eles se retirado, eis que um anjo do Senhor apareceu a José em sonho, dizendo: Levanta-te, toma o menino e sua mãe, foge para o Egito, e ali fica até que eu te fale; porque Herodes há de procurar o menino para o matar.

[[v40-2-14]]

^<<v40-2-14,14>>^ Levantou-se, pois, tomou de noite o menino e sua mãe, e partiu para o Egito.

[[v40-2-15]]

^<<v40-2-15,15>>^ e lá ficou até a morte de Herodes, para que se cumprisse o que fora dito da parte do Senhor pelo profeta: Do Egito chamei o meu Filho.

[[v40-2-16]]

^<<v40-2-16,16>>^ Cumpriu-se então o que fora dito pelo profeta Jeremias:

[[v40-2-17]]

^<<v40-2-17,17>>^ 

[[v40-2-18]]

^<<v40-2-18,18>>^ Em Ramá se ouviu uma voz, lamentação e grande pranto: Raquel chorando os seus filhos, e não querendo ser consolada, porque eles já não existem.

[[v40-2-19]]

^<<v40-2-19,19>>^ Mas tendo morrido Herodes, eis que um anjo do Senhor apareceu em sonho a José no Egito,

[[v40-2-20]]

^<<v40-2-20,20>>^ dizendo: Levanta-te, toma o menino e sua mãe e vai para a terra de Israel; porque já morreram os que procuravam a morte do menino.

[[v40-2-21]]

^<<v40-2-21,21>>^ Então ele se levantou, tomou o menino e sua mãe e foi para a terra de Israel.

[[v40-2-22]]

^<<v40-2-22,22>>^ Ouvindo, porém, que Arquelau reinava na Judéia em lugar de seu pai Herodes, temeu ir para lá; mas avisado em sonho por divina revelação, retirou-se para as regiões da Galiléia,

'''

xref:040-mateus/040-mateus-001.adoc#v40-1-0[&#60; Capítulo Anterior] | <<v40-2-0,Topo>> | xref:040-mateus/040-mateus-003.adoc#v40-3-0[Próximo Capítulo &#62;]