include::./index.adoc[]

[[v40-14-0]]
=== Mateus, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-14-1]]

^<<v40-14-1,1>>^ Naquele tempo Herodes, o tetrarca, ouviu a fama de Jesus,

[[v40-14-2]]

^<<v40-14-2,2>>^ e disse aos seus cortesãos: Este é João, o Batista; ele ressuscitou dentre os mortos, e por isso estes poderes milagrosos operam nele.

[[v40-14-3]]

^<<v40-14-3,3>>^ Pois Herodes havia prendido a João, e, maniatando-o, o guardara no cárcere, por causa de Herodias, mulher de seu irmão Felipe;

[[v40-14-4]]

^<<v40-14-4,4>>^ porque João lhe dizia: Não te é lícito possuí-la.

[[v40-14-5]]

^<<v40-14-5,5>>^ E queria matá-lo, mas temia o povo; porque o tinham como profeta.

[[v40-14-6]]

^<<v40-14-6,6>>^ Festejando-se, porém, o dia natalício de Herodes, a filha de Herodias dançou no meio dos convivas, e agradou a Herodes,

[[v40-14-7]]

^<<v40-14-7,7>>^ pelo que este prometeu com juramento dar-lhe tudo o que pedisse.

[[v40-14-8]]

^<<v40-14-8,8>>^ E instigada por sua mãe, disse ela: Dá-me aqui num prato a cabeça de João, o Batista.

[[v40-14-9]]

^<<v40-14-9,9>>^ Entristeceu-se, então, o rei; mas, por causa do juramento, e dos que estavam à mesa com ele, ordenou que se lhe desse,

[[v40-14-10]]

^<<v40-14-10,10>>^ e mandou degolar a João no cárcere;

[[v40-14-11]]

^<<v40-14-11,11>>^ e a cabeça foi trazida num prato, e dada à jovem, e ela a levou para a sua mãe.

[[v40-14-12]]

^<<v40-14-12,12>>^ Então vieram os seus discípulos, levaram o corpo e o sepultaram; e foram anunciá-lo a Jesus.

[[v40-14-13]]

^<<v40-14-13,13>>^ Jesus, ouvindo isto, retirou-se dali num barco, para um, lugar deserto, à parte; e quando as multidões o souberam, seguiram-no a pé desde as cidades.

[[v40-14-14]]

^<<v40-14-14,14>>^ E ele, ao desembarcar, viu uma grande multidão; e, compadecendo-se dela, curou os seus enfermos.

[[v40-14-15]]

^<<v40-14-15,15>>^ Chegada a tarde, aproximaram-se dele os discípulos, dizendo: O lugar é deserto, e a hora é já passada; despede as multidões, para que vão às aldeias, e comprem o que comer.

[[v40-14-16]]

^<<v40-14-16,16>>^ Jesus, porém, lhes disse: Não precisam ir embora; dai-lhes vós de comer.

[[v40-14-17]]

^<<v40-14-17,17>>^ Então eles lhe disseram: Não temos aqui senão cinco pães e dois peixes.

[[v40-14-18]]

^<<v40-14-18,18>>^ E ele disse: trazei-mos aqui.

[[v40-14-19]]

^<<v40-14-19,19>>^ Tendo mandado às multidões que se reclinassem sobre a relva, tomou os cinco pães e os dois peixes e, erguendo os olhos ao céu, os abençoou; e partindo os pães, deu-os aos discípulos, e os discípulos às multidões.

[[v40-14-20]]

^<<v40-14-20,20>>^ Todos comeram e se fartaram; e dos pedaços que sobejaram levantaram doze cestos cheios.

[[v40-14-21]]

^<<v40-14-21,21>>^ Ora, os que comeram foram cerca de cinco mil homens, além de mulheres e crianças.

[[v40-14-22]]

^<<v40-14-22,22>>^ Logo em seguida obrigou os seus discípulos a entrar no barco, e passar adiante dele para o outro lado, enquanto ele despedia as multidões.

[[v40-14-23]]

^<<v40-14-23,23>>^ Tendo-as despedido, subiu ao monte para orar à parte. Ao anoitecer, estava ali sozinho.

[[v40-14-24]]

^<<v40-14-24,24>>^ Entrementes, o barco já estava a muitos estádios da terra, açoitado pelas ondas; porque o vento era contrário.

[[v40-14-25]]

^<<v40-14-25,25>>^ À quarta vigília da noite, foi Jesus ter com eles, andando sobre o mar.

[[v40-14-26]]

^<<v40-14-26,26>>^ Os discípulos, porém, ao vê-lo andando sobre o mar, assustaram-se e disseram: É um fantasma. E gritaram de medo.

[[v40-14-27]]

^<<v40-14-27,27>>^ Jesus, porém, imediatamente lhes falou, dizendo: Tende ânimo; sou eu; não temais.

[[v40-14-28]]

^<<v40-14-28,28>>^ Respondeu-lhe Pedro: Senhor! se és tu, manda-me ir ter contigo sobre as águas.

[[v40-14-29]]

^<<v40-14-29,29>>^ Disse-lhe ele: Vem. Pedro, descendo do barco, e andando sobre as águas, foi ao encontro de Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ Mas, sentindo o vento, teve medo; e, começando a submergir, clamou: Senhor, salva-me.

[[v40-14-31]]

^<<v40-14-31,31>>^ Imediatamente estendeu Jesus a mão, segurou-o, e disse-lhe: Homem de pouca fé, por que duvidaste?

[[v40-14-32]]

^<<v40-14-32,32>>^ E logo que subiram para o barco, o vento cessou.

[[v40-14-33]]

^<<v40-14-33,33>>^ Então os que estavam no barco adoraram-no, dizendo: Verdadeiramente tu és Filho de Deus.

[[v40-14-34]]

^<<v40-14-34,34>>^ Ora, terminada a travessia, chegaram à terra em Genezaré.

[[v40-14-35]]

^<<v40-14-35,35>>^ Quando os homens daquele lugar o reconheceram, mandaram por toda aquela circunvizinhança, e trouxeram-lhe todos os enfermos;

[[v40-14-36]]

^<<v40-14-36,36>>^ e rogaram-lhe que apenas os deixasse tocar a orla do seu manto; e todos os que a tocaram ficaram curados.

'''

xref:040-mateus/040-mateus-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-mateus/040-mateus-015.adoc#v40-15-0[Próximo Capítulo &#62;]