include::./index.adoc[]

[[v40-9-0]]
=== Mateus, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-9-1]]

^<<v40-9-1,1>>^ E entrando Jesus num barco, passou para o outro lado, e chegou à sua própria cidade.

[[v40-9-2]]

^<<v40-9-2,2>>^ E eis que lhe trouxeram um paralítico deitado num leito. Jesus, pois, vendo-lhes a fé, disse ao paralítico: Tem ânimo, filho; perdoados são os teus pecados.

[[v40-9-3]]

^<<v40-9-3,3>>^ E alguns dos escribas disseram consigo: Este homem blasfema.

[[v40-9-4]]

^<<v40-9-4,4>>^ Mas Jesus, conhecendo-lhes os pensamentos, disse: Por que pensais o mal em vossos corações?

[[v40-9-5]]

^<<v40-9-5,5>>^ Pois qual é mais fácil? dizer: Perdoados são os teus pecados, ou dizer: Levanta-te e anda?

[[v40-9-6]]

^<<v40-9-6,6>>^ Ora, para que saibais que o Filho do homem tem sobre a terra autoridade para perdoar pecados &#123;disse então ao paralítico&#125;: Levanta-te, toma o teu leito, e vai para tua casa.

[[v40-9-7]]

^<<v40-9-7,7>>^ E este, levantando-se, foi para sua casa.

[[v40-9-8]]

^<<v40-9-8,8>>^ E as multidões, vendo isso, temeram, e glorificaram a Deus, que dera tal autoridade aos homens.

[[v40-9-9]]

^<<v40-9-9,9>>^ Partindo Jesus dali, viu sentado na coletoria um homem chamado Mateus, e disse-lhe: Segue-me. E ele, levantando-se, o seguiu.

[[v40-9-10]]

^<<v40-9-10,10>>^ Ora, estando ele à mesa em casa, eis que chegaram muitos publicanos e pecadores, e se reclinaram à mesa juntamente com Jesus e seus discípulos.

[[v40-9-11]]

^<<v40-9-11,11>>^ E os fariseus, vendo isso, perguntavam aos discípulos: Por que come o vosso Mestre com publicanos e pecadores?

[[v40-9-12]]

^<<v40-9-12,12>>^ Jesus, porém, ouvindo isso, respondeu: Não necessitam de médico os sãos, mas sim os enfermos.

[[v40-9-13]]

^<<v40-9-13,13>>^ Ide, pois, e aprendei o que significa: Misericórdia quero, e não sacrifícios. Porque eu não vim chamar justos, mas pecadores.

[[v40-9-14]]

^<<v40-9-14,14>>^ Então vieram ter com ele os discípulos de João, perguntando: Por que é que nós e os fariseus jejuamos, mas os teus discípulos não jejuam?

[[v40-9-15]]

^<<v40-9-15,15>>^ Respondeu-lhes Jesus: Podem porventura ficar tristes os convidados às núpcias, enquanto o noivo está com eles? Dias virão, porém, em que lhes será tirado o noivo, e então hão de jejuar.

[[v40-9-16]]

^<<v40-9-16,16>>^ Ninguém põe remendo de pano novo em vestido velho; porque semelhante remendo tira parte do vestido, e faz-se maior a rotura.

[[v40-9-17]]

^<<v40-9-17,17>>^ Nem se deita vinho novo em odres velhos; do contrário se rebentam, derrama-se o vinho, e os odres se perdem; mas deita-se vinho novo em odres novos, e assim ambos se conservam.

[[v40-9-18]]

^<<v40-9-18,18>>^ Enquanto ainda lhes dizia essas coisas, eis que chegou um chefe da sinagoga e o adorou, dizendo: Minha filha acaba de falecer; mas vem, impõe-lhe a tua mão, e ela viverá.

[[v40-9-19]]

^<<v40-9-19,19>>^ Levantou-se, pois, Jesus, e o foi seguindo, ele e os seus discípulos.

[[v40-9-20]]

^<<v40-9-20,20>>^ E eis que certa mulher, que havia doze anos padecia de uma hemorragia, chegou por detrás dele e tocou-lhe a orla do manto;

[[v40-9-21]]

^<<v40-9-21,21>>^ porque dizia consigo: Se eu tão-somente tocar-lhe o manto, ficarei sã.

[[v40-9-22]]

^<<v40-9-22,22>>^ Mas Jesus, voltando-se e vendo-a, disse: Tem ânimo, filha, a tua fé te salvou. E desde aquela hora a mulher ficou sã.

[[v40-9-23]]

^<<v40-9-23,23>>^ Quando Jesus chegou à casa daquele chefe, e viu os tocadores de flauta e a multidão em alvoroço,

[[v40-9-24]]

^<<v40-9-24,24>>^ disse; Retirai-vos; porque a menina não está morta, mas dorme. E riam-se dele.

[[v40-9-25]]

^<<v40-9-25,25>>^ Tendo-se feito sair o povo, entrou Jesus, tomou a menina pela mão, e ela se levantou.

[[v40-9-26]]

^<<v40-9-26,26>>^ E espalhou-se a notícia disso por toda aquela terra.

[[v40-9-27]]

^<<v40-9-27,27>>^ Partindo Jesus dali, seguiram-no dois cegos, que clamavam, dizendo: Tem compaixão de nós, Filho de Davi.

[[v40-9-28]]

^<<v40-9-28,28>>^ E, tendo ele entrado em casa, os cegos se aproximaram dele; e Jesus perguntou-lhes: Credes que eu posso fazer isto? Responderam-lhe eles: Sim, Senhor.

[[v40-9-29]]

^<<v40-9-29,29>>^ Então lhes tocou os olhos, dizendo: Seja-vos feito segundo a vossa fé.

[[v40-9-30]]

^<<v40-9-30,30>>^ E os olhos se lhes abriram. Jesus ordenou-lhes terminantemente, dizendo: Vede que ninguém o saiba.

[[v40-9-31]]

^<<v40-9-31,31>>^ Eles, porém, saíram, e divulgaram a sua fama por toda aquela terra.

[[v40-9-32]]

^<<v40-9-32,32>>^ Enquanto esses se retiravam, eis que lhe trouxeram um homem mudo e endemoninhado.

[[v40-9-33]]

^<<v40-9-33,33>>^ E, expulso o demônio, falou o mudo e as multidões se admiraram, dizendo: Nunca tal se viu em Israel.

[[v40-9-34]]

^<<v40-9-34,34>>^ Os fariseus, porém, diziam: É pelo príncipe dos demônios que ele expulsa os demônios.

[[v40-9-35]]

^<<v40-9-35,35>>^ E percorria Jesus todas as cidades e aldeias, ensinando nas sinagogas, pregando o evangelho do reino, e curando toda sorte de doenças e enfermidades.

[[v40-9-36]]

^<<v40-9-36,36>>^ Vendo ele as multidões, compadeceu-se delas, porque andavam desgarradas e errantes, como ovelhas que não têm pastor.

[[v40-9-37]]

^<<v40-9-37,37>>^ Então disse a seus discípulos: Na verdade, a seara é grande, mas os trabalhadores são poucos.

[[v40-9-38]]

^<<v40-9-38,38>>^ Rogai, pois, ao Senhor da seara que mande trabalhadores para a sua seara.

'''

xref:040-mateus/040-mateus-008.adoc#v40-8-0[&#60; Capítulo Anterior] | <<v40-9-0,Topo>> | xref:040-mateus/040-mateus-010.adoc#v40-10-0[Próximo Capítulo &#62;]