include::./index.adoc[]

[[v40-6-0]]
=== Mateus, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-6-1]]

^<<v40-6-1,1>>^ Guardai-vos de fazer as vossas boas obras diante dos homens, para serdes vistos por eles; de outra sorte não tereis recompensa junto de vosso Pai, que está nos céus.

[[v40-6-2]]

^<<v40-6-2,2>>^ Quando, pois, deres esmola, não faças tocar trombeta diante de ti, como fazem os hipócritas nas sinagogas e nas ruas, para serem glorificados pelos homens. Em verdade vos digo que já receberam a sua recompensa.

[[v40-6-3]]

^<<v40-6-3,3>>^ Mas, quando tu deres esmola, não saiba a tua mão esquerda o que faz a direita;

[[v40-6-4]]

^<<v40-6-4,4>>^ para que a tua esmola fique em secreto; e teu Pai, que vê em secreto, te recompensará.

[[v40-6-5]]

^<<v40-6-5,5>>^ E, quando orardes, não sejais como os hipócritas; pois gostam de orar em pé nas sinagogas, e às esquinas das ruas, para serem vistos pelos homens. Em verdade vos digo que já receberam a sua recompensa.

[[v40-6-6]]

^<<v40-6-6,6>>^ Mas tu, quando orares, entra no teu quarto e, fechando a porta, ora a teu Pai que está em secreto; e teu Pai, que vê em secreto, te recompensará.

[[v40-6-7]]

^<<v40-6-7,7>>^ E, orando, não useis de vãs repetições, como os gentios; porque pensam que pelo seu muito falar serão ouvidos.

[[v40-6-8]]

^<<v40-6-8,8>>^ Não vos assemelheis, pois, a eles; porque vosso Pai sabe o que vos é necessário, antes de vós lho pedirdes.

[[v40-6-9]]

^<<v40-6-9,9>>^ Portanto, orai vós deste modo: Pai nosso que estás nos céus, santificado seja o teu nome;

[[v40-6-10]]

^<<v40-6-10,10>>^ venha o teu reino, seja feita a tua vontade, assim na terra como no céu;

[[v40-6-11]]

^<<v40-6-11,11>>^ o pão nosso de cada dia nos dá hoje;

[[v40-6-12]]

^<<v40-6-12,12>>^ e perdoa-nos as nossas dívidas, assim como nós também temos perdoado aos nossos devedores;

[[v40-6-13]]

^<<v40-6-13,13>>^ e não nos deixes entrar em tentação; mas livra-nos do mal. &#123;Porque teu é o reino e o poder, e a glória, para sempre, Amém.&#125;

[[v40-6-14]]

^<<v40-6-14,14>>^ Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós;

[[v40-6-15]]

^<<v40-6-15,15>>^ se, porém, não perdoardes aos homens, tampouco vosso Pai perdoará vossas ofensas.

[[v40-6-16]]

^<<v40-6-16,16>>^ Quando jejuardes, não vos mostreis contristados como os hipócritas; porque eles desfiguram os seus rostos, para que os homens vejam que estão jejuando. Em verdade vos digo que já receberam a sua recompensa.

[[v40-6-17]]

^<<v40-6-17,17>>^ Tu, porém, quando jejuares, unge a tua cabeça, e lava o teu rosto,

[[v40-6-18]]

^<<v40-6-18,18>>^ para não mostrar aos homens que estás jejuando, mas a teu Pai, que está em secreto; e teu Pai, que vê em secreto, te recompensará.

[[v40-6-19]]

^<<v40-6-19,19>>^ Não ajunteis para vós tesouros na terra; onde a traça e a ferrugem os consomem, e onde os ladrões minam e roubam;

[[v40-6-20]]

^<<v40-6-20,20>>^ mas ajuntai para vós tesouros no céu, onde nem a traça nem a ferrugem os consumem, e onde os ladrões não minam nem roubam.

[[v40-6-21]]

^<<v40-6-21,21>>^ Porque onde estiver o teu tesouro, aí estará também o teu coração.

[[v40-6-22]]

^<<v40-6-22,22>>^ A candeia do corpo são os olhos; de sorte que, se os teus olhos forem bons, todo teu corpo terá luz;

[[v40-6-23]]

^<<v40-6-23,23>>^ se, porém, os teus olhos forem maus, o teu corpo será tenebroso. Se, portanto, a luz que em ti há são trevas, quão grandes são tais trevas!

[[v40-6-24]]

^<<v40-6-24,24>>^ Ninguém pode servir a dois senhores; porque ou há de odiar a um e amar o outro, ou há de dedicar-se a um e desprezar o outro. Não podeis servir a Deus e às riquezas.

[[v40-6-25]]

^<<v40-6-25,25>>^ Por isso vos digo: Não estejais ansiosos quanto à vossa vida, pelo que haveis de comer, ou pelo que haveis de beber; nem, quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o alimento, e o corpo mais do que o vestuário?

[[v40-6-26]]

^<<v40-6-26,26>>^ Olhai para as aves do céu, que não semeiam, nem ceifam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não valeis vós muito mais do que elas?

[[v40-6-27]]

^<<v40-6-27,27>>^ Ora, qual de vós, por mais ansioso que esteja, pode acrescentar um côvado à sua estatura?

[[v40-6-28]]

^<<v40-6-28,28>>^ E pelo que haveis de vestir, por que andais ansiosos? Olhai para os lírios do campo, como crescem; não trabalham nem fiam;

[[v40-6-29]]

^<<v40-6-29,29>>^ contudo vos digo que nem mesmo Salomão em toda a sua glória se vestiu como um deles.

[[v40-6-30]]

^<<v40-6-30,30>>^ Pois, se Deus assim veste a erva do campo, que hoje existe e amanhã é lançada no forno, quanto mais a vós, homens de pouca fé?

[[v40-6-31]]

^<<v40-6-31,31>>^ Portanto, não vos inquieteis, dizendo: Que havemos de comer? ou: Que havemos de beber? ou: Com que nos havemos de vestir?

[[v40-6-32]]

^<<v40-6-32,32>>^ &#123;Pois a todas estas coisas os gentios procuram.&#125; Porque vosso Pai celestial sabe que precisais de tudo isso.

[[v40-6-33]]

^<<v40-6-33,33>>^ Mas buscai primeiro o seu reino e a sua justiça, e todas estas coisas vos serão acrescentadas.

[[v40-6-34]]

^<<v40-6-34,34>>^ Não vos inquieteis, pois, pelo dia de amanhã; porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.

'''

xref:040-mateus/040-mateus-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-mateus/040-mateus-007.adoc#v40-7-0[Próximo Capítulo &#62;]