include::./index.adoc[]

[[v40-19-0]]
=== Mateus, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-19-1]]

^<<v40-19-1,1>>^ Tendo Jesus concluído estas palavras, partiu da Galiléia, e foi para os confins da Judéia, além do Jordão;

[[v40-19-2]]

^<<v40-19-2,2>>^ e seguiram-no grandes multidões, e curou-os ali.

[[v40-19-3]]

^<<v40-19-3,3>>^ Aproximaram-se dele alguns fariseus que o experimentavam, dizendo: É lícito ao homem repudiar sua mulher por qualquer motivo?

[[v40-19-4]]

^<<v40-19-4,4>>^ Respondeu-lhe Jesus: Não tendes lido que o Criador os fez desde o princípio homem e mulher,

[[v40-19-5]]

^<<v40-19-5,5>>^ e que ordenou: Por isso deixará o homem pai e mãe, e unir-se-á a sua mulher; e serão os dois uma só carne?

[[v40-19-6]]

^<<v40-19-6,6>>^ Assim já não são mais dois, mas um só carne. Portanto o que Deus ajuntou, não o separe o homem.

[[v40-19-7]]

^<<v40-19-7,7>>^ Responderam-lhe: Então por que mandou Moisés dar-lhe carta de divórcio e repudiá-la?

[[v40-19-8]]

^<<v40-19-8,8>>^ Disse-lhes ele: Pela dureza de vossos corações Moisés vos permitiu repudiar vossas mulheres; mas não foi assim desde o princípio.

[[v40-19-9]]

^<<v40-19-9,9>>^ Eu vos digo porém, que qualquer que repudiar sua mulher, a não ser por causa de infidelidade, e casar com outra, comete adultério; &#123;e o que casar com a repudiada também comete adultério.&#125;

[[v40-19-10]]

^<<v40-19-10,10>>^ Disseram-lhe os discípulos: Se tal é a condição do homem relativamente à mulher, não convém casar.

[[v40-19-11]]

^<<v40-19-11,11>>^ Ele, porém, lhes disse: Nem todos podem aceitar esta palavra, mas somente aqueles a quem é dado.

[[v40-19-12]]

^<<v40-19-12,12>>^ Porque há eunucos que nasceram assim; e há eunucos que pelos homens foram feitos tais; e outros há que a si mesmos se fizeram eunucos por causa do reino dos céus. Quem pode aceitar isso, aceite-o.

[[v40-19-13]]

^<<v40-19-13,13>>^ Então lhe trouxeram algumas crianças para que lhes impusesse as mãos, e orasse; mas os discípulos os repreenderam.

[[v40-19-14]]

^<<v40-19-14,14>>^ Jesus, porém, disse: Deixai as crianças e não as impeçais de virem a mim, porque de tais é o reino dos céus.

[[v40-19-15]]

^<<v40-19-15,15>>^ E, depois de lhes impor as mãos, partiu dali.

[[v40-19-16]]

^<<v40-19-16,16>>^ E eis que se aproximou dele um jovem, e lhe disse: Mestre, que bem farei para conseguir a vida eterna?

[[v40-19-17]]

^<<v40-19-17,17>>^ Respondeu-lhe ele: Por que me perguntas sobre o que é bom? Um só é bom; mas se é que queres entrar na vida, guarda os mandamentos.

[[v40-19-18]]

^<<v40-19-18,18>>^ Perguntou-lhe ele: Quais? Respondeu Jesus: Não matarás; não adulterarás; não furtarás; não dirás falso testemunho;

[[v40-19-19]]

^<<v40-19-19,19>>^ honra a teu pai e a tua mãe; e amarás o teu próximo como a ti mesmo.

[[v40-19-20]]

^<<v40-19-20,20>>^ Disse-lhe o jovem: Tudo isso tenho guardado; que me falta ainda?

[[v40-19-21]]

^<<v40-19-21,21>>^ Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens e dá-o aos pobres, e terás um tesouro no céu; e vem, segue-me.

[[v40-19-22]]

^<<v40-19-22,22>>^ Mas o jovem, ouvindo essa palavra, retirou-se triste; porque possuía muitos bens.

[[v40-19-23]]

^<<v40-19-23,23>>^ Disse então Jesus aos seus discípulos: Em verdade vos digo que um rico dificilmente entrará no reino dos céus.

[[v40-19-24]]

^<<v40-19-24,24>>^ E outra vez vos digo que é mais fácil um camelo passar pelo fundo duma agulha, do que entrar um rico no reino de Deus.

[[v40-19-25]]

^<<v40-19-25,25>>^ Quando os seus discípulos ouviram isso, ficaram grandemente maravilhados, e perguntaram: Quem pode, então, ser salvo?

[[v40-19-26]]

^<<v40-19-26,26>>^ Jesus, fixando neles o olhar, respondeu: Aos homens é isso impossível, mas a Deus tudo é possível.

[[v40-19-27]]

^<<v40-19-27,27>>^ Então Pedro, tomando a palavra, disse-lhe: Eis que nós deixamos tudo, e te seguimos; que recompensa, pois, teremos nós?

[[v40-19-28]]

^<<v40-19-28,28>>^ Ao que lhe disse Jesus: Em verdade vos digo a vós que me seguistes, que na regeneração, quando o Filho do homem se assentar no trono da sua glória, sentar-vos-eis também vós sobre doze tronos, para julgar as doze tribos de Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ E todo o que tiver deixado casas, ou irmãos, ou irmãs, ou pai, ou mãe, ou filhos, ou terras, por amor do meu nome, receberá cem vezes tanto, e herdará a vida eterna.

[[v40-19-30]]

^<<v40-19-30,30>>^ Entretanto, muitos que são primeiros serão últimos; e muitos que são últimos serão primeiros.

'''

xref:040-mateus/040-mateus-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-mateus/040-mateus-020.adoc#v40-20-0[Próximo Capítulo &#62;]