include::./index.adoc[]

[[v40-26-0]]
=== Mateus, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v40-26-1]]

^<<v40-26-1,1>>^ E havendo Jesus concluído todas estas palavras, disse aos seus discípulos:

[[v40-26-2]]

^<<v40-26-2,2>>^ Sabeis que de hoje a dois dias celebrar-se-á a páscoa, e o Filho do homem será entregue para ser crucificado.

[[v40-26-3]]

^<<v40-26-3,3>>^ Depois se reuniram os principais sacerdotes e os anciãos do povo no pátio da casa do sumo sacerdote, chamado Caifás;

[[v40-26-4]]

^<<v40-26-4,4>>^ e deliberaram prender a Jesus à traição e tirar-lhe a vida.

[[v40-26-5]]

^<<v40-26-5,5>>^ Mas diziam: Durante a festa, não; para que não haja tumulto entre o povo.

[[v40-26-6]]

^<<v40-26-6,6>>^ Estando Jesus em Betânia, em casa de Simão, o leproso,

[[v40-26-7]]

^<<v40-26-7,7>>^ chegou-se a ele uma mulher que trazia um vaso de alabastro com precioso perfume, e lho derramou sobre a cabeça, quando ele estava à mesa.

[[v40-26-8]]

^<<v40-26-8,8>>^ Vendo isto, seus discípulos indignaram-se e disseram:

[[v40-26-9]]

^<<v40-26-9,9>>^ Para que este desperdício? Pois o perfume podia ser vendido por muito dinheiro, e ser este dado aos pobres.

[[v40-26-10]]

^<<v40-26-10,10>>^ Mas Jesus, percebendo isto, disse-lhes: Por que molestais essa mulher? ela me fez uma boa obra.

[[v40-26-11]]

^<<v40-26-11,11>>^ Pois os pobres sempre os tendes convosco, mas a mim nem sempre me tendes;

[[v40-26-12]]

^<<v40-26-12,12>>^ derramando ela este perfume sobre o meu corpo, fê-lo para a minha sepultura.

[[v40-26-13]]

^<<v40-26-13,13>>^ Em verdade vos digo que onde quer que for pregado em todo o mundo este Evangelho, será também contado para memória sua o que ela fez.

[[v40-26-14]]

^<<v40-26-14,14>>^ Então um dos doze, chamado Judas Iscariotes, foi ter com os principais sacerdotes,

[[v40-26-15]]

^<<v40-26-15,15>>^ e lhes disse: Que me quereis dar e eu vo-lo entregarei? Eles lhe pesaram trinta moedas de prata.

[[v40-26-16]]

^<<v40-26-16,16>>^ Desde então Judas buscava oportunidade para o entregar.

[[v40-26-17]]

^<<v40-26-17,17>>^ Ora, no primeiro dia dos pães ázimos, vieram os discípulos a Jesus, e perguntaram: Onde queres que façamos os preparativos para comeres a páscoa?

[[v40-26-18]]

^<<v40-26-18,18>>^ Respondeu-lhes: Ide à cidade ter com certo homem, e dizei-lhe que o Mestre diz: O meu tempo está próximo; em tua casa celebrarei a páscoa com meus discípulos.

[[v40-26-19]]

^<<v40-26-19,19>>^ Eles fizeram como Jesus lhes havia ordenado, e prepararam a páscoa.

[[v40-26-20]]

^<<v40-26-20,20>>^ À tarde estava ele sentado à mesa com os doze discípulos.

[[v40-26-21]]

^<<v40-26-21,21>>^ Enquanto comiam, declarou Jesus: Em verdade vos digo que um de vós me trairá.

[[v40-26-22]]

^<<v40-26-22,22>>^ Eles, muitíssimo contristados, começaram um por um a perguntar-lhe: Porventura sou eu, Senhor?

[[v40-26-23]]

^<<v40-26-23,23>>^ Ele respondeu: O que põe comigo a mão no prato, esse é o que me trairá.

[[v40-26-24]]

^<<v40-26-24,24>>^ O Filho do homem vai-se, segundo está escrito a seu respeito, mas ai daquele por quem o Filho do homem é traído! melhor fora para esse homem se não houvesse nascido.

[[v40-26-25]]

^<<v40-26-25,25>>^ Judas, que o traiu, perguntou: Porventura sou eu, Mestre? Respondeu-lhe Jesus: Tu o disseste.

[[v40-26-26]]

^<<v40-26-26,26>>^ Enquanto comiam, Jesus tomou o pão e, abençoando-o, o partiu e o deu aos discípulos, dizendo: Tomai, comei; isto é o meu corpo.

[[v40-26-27]]

^<<v40-26-27,27>>^ Tomando o cálice, rendeu graças e deu-lho, dizendo: Bebei dele todos;

[[v40-26-28]]

^<<v40-26-28,28>>^ porque este é o meu sangue, o sangue da aliança, que é derramado por muitos para remissão de pecados.

[[v40-26-29]]

^<<v40-26-29,29>>^ Mas digo-vos que desta hora em diante não beberei deste fruto da videira, até aquele dia em que o hei de beber novo convosco no reino de meu Pai.

[[v40-26-30]]

^<<v40-26-30,30>>^ E tendo cantado um hino, saíram para o Monte das Oliveiras.

[[v40-26-31]]

^<<v40-26-31,31>>^ Então Jesus lhes disse: Todos vós esta noite vos escandalizareis de mim; pois está escrito: Ferirei o pastor, e as ovelhas do rebanho se dispersarão.

[[v40-26-32]]

^<<v40-26-32,32>>^ Todavia, depois que eu ressurgir, irei adiante de vós para a Galiléia.

[[v40-26-33]]

^<<v40-26-33,33>>^ Mas Pedro, respondendo, disse-lhe: Ainda que todos se escandalizem de ti, eu nunca me escandalizarei.

[[v40-26-34]]

^<<v40-26-34,34>>^ Disse-lhe Jesus: Em verdade te digo que esta noite, antes que o galo cante três vezes me negarás.

[[v40-26-35]]

^<<v40-26-35,35>>^ Respondeu-lhe Pedro: Ainda que me seja necessário morrer contigo, de modo algum te negarei. E o mesmo disseram todos os discípulos.

[[v40-26-36]]

^<<v40-26-36,36>>^ Então foi Jesus com eles a um lugar chamado Getsêmani, e disse aos discípulos: Sentai-vos aqui, enquanto eu vou ali orar.

[[v40-26-37]]

^<<v40-26-37,37>>^ E levando consigo Pedro e os dois filhos de Zebedeu, começou a entristecer-se e a angustiar-se.

[[v40-26-38]]

^<<v40-26-38,38>>^ Então lhes disse: A minha alma está triste até a morte; ficai aqui e vigiai comigo.

[[v40-26-39]]

^<<v40-26-39,39>>^ E adiantando-se um pouco, prostrou-se com o rosto em terra e orou, dizendo: Meu Pai, se é possível, passa de mim este cálice; todavia, não seja como eu quero, mas como tu queres.

[[v40-26-40]]

^<<v40-26-40,40>>^ Voltando para os discípulos, achou-os dormindo; e disse a Pedro: Assim nem uma hora pudestes vigiar comigo?

[[v40-26-41]]

^<<v40-26-41,41>>^ Vigiai e orai, para que não entreis em tentação; o espírito, na verdade, está pronto, mas a carne é fraca.

[[v40-26-42]]

^<<v40-26-42,42>>^ Retirando-se mais uma vez, orou, dizendo: Pai meu, se este cálice não pode passar sem que eu o beba, faça-se a tua vontade.

[[v40-26-43]]

^<<v40-26-43,43>>^ E, voltando outra vez, achou-os dormindo, porque seus olhos estavam carregados.

[[v40-26-44]]

^<<v40-26-44,44>>^ Deixando-os novamente, foi orar terceira vez, repetindo as mesmas palavras.

[[v40-26-45]]

^<<v40-26-45,45>>^ Então voltou para os discípulos e disse-lhes: Dormi agora e descansai. Eis que é chegada a hora, e o Filho do homem está sendo entregue nas mãos dos pecadores.

[[v40-26-46]]

^<<v40-26-46,46>>^ Levantai-vos, vamo-nos; eis que é chegado aquele que me trai.

[[v40-26-47]]

^<<v40-26-47,47>>^ E estando ele ainda a falar, eis que veio Judas, um dos doze, e com ele grande multidão com espadas e varapaus, vinda da parte dos principais sacerdotes e dos anciãos do povo.

[[v40-26-48]]

^<<v40-26-48,48>>^ Ora, o que o traía lhes havia dado um sinal, dizendo: Aquele que eu beijar, esse é: prendei-o.

[[v40-26-49]]

^<<v40-26-49,49>>^ E logo, aproximando-se de Jesus disse: Salve, Rabi. E o beijou.

[[v40-26-50]]

^<<v40-26-50,50>>^ Jesus, porém, lhe disse: Amigo, a que vieste? Nisto, aproximando-se eles, lançaram mão de Jesus, e o prenderam.

[[v40-26-51]]

^<<v40-26-51,51>>^ E eis que um dos que estavam com Jesus, estendendo a mão, puxou da espada e, ferindo o servo do sumo sacerdote, cortou-lhe uma orelha.

[[v40-26-52]]

^<<v40-26-52,52>>^ Então Jesus lhe disse: Mete a tua espada no seu lugar; porque todos os que lançarem mão da espada, à espada morrerão.

[[v40-26-53]]

^<<v40-26-53,53>>^ Ou pensas tu que eu não poderia rogar a meu Pai, e que ele não me mandaria agora mesmo mais de doze legiões de anjos?

[[v40-26-54]]

^<<v40-26-54,54>>^ Como, pois, se cumpririam as Escrituras, que dizem que assim convém que aconteça?

[[v40-26-55]]

^<<v40-26-55,55>>^ Disse Jesus à multidão naquela hora: Saístes com espadas e varapaus para me prender, como a um salteador? Todos os dias estava eu sentado no templo ensinando, e não me prendestes.

[[v40-26-56]]

^<<v40-26-56,56>>^ Mas tudo isso aconteceu para que se cumprissem as Escrituras dos profetas. Então todos os discípulos, deixando-o fugiram.

[[v40-26-57]]

^<<v40-26-57,57>>^ Aqueles que prenderam a Jesus levaram-no à presença do sumo sacerdote Caifás, onde os escribas e os anciãos estavam reunidos.

[[v40-26-58]]

^<<v40-26-58,58>>^ E Pedro o seguia de longe até o pátio do sumo sacerdote; e entrando, sentou-se entre os guardas, para ver o fim.

[[v40-26-59]]

^<<v40-26-59,59>>^ Ora, os principais sacerdotes e todo o sinédrio buscavam falso testemunho contra Jesus, para poderem entregá-lo à morte;

[[v40-26-60]]

^<<v40-26-60,60>>^ e não achavam, apesar de se apresentarem muitas testemunhas falsas. Mas por fim compareceram duas,

[[v40-26-61]]

^<<v40-26-61,61>>^ e disseram: Este disse: Posso destruir o santuário de Deus, e reedificá-lo em três dias.

[[v40-26-62]]

^<<v40-26-62,62>>^ Levantou-se então o sumo sacerdote e perguntou-lhe: Nada respondes? Que é que estes depõem contra ti?

[[v40-26-63]]

^<<v40-26-63,63>>^ Jesus, porém, guardava silêncio. E o sumo sacerdote disse-lhe: Conjuro-te pelo Deus vivo que nos digas se tu és o Cristo, o Filho do Deus.

[[v40-26-64]]

^<<v40-26-64,64>>^ Respondeu-lhe Jesus: É como disseste; contudo vos digo que vereis em breve o Filho do homem assentado à direita do Poder, e vindo sobre as nuvens do céu.

[[v40-26-65]]

^<<v40-26-65,65>>^ Então o sumo sacerdote rasgou as suas vestes, dizendo: Blasfemou; para que precisamos ainda de testemunhas? Eis que agora acabais de ouvir a sua blasfêmia.

[[v40-26-66]]

^<<v40-26-66,66>>^ Que vos parece? Responderam eles: É réu de morte.

[[v40-26-67]]

^<<v40-26-67,67>>^ Então uns lhe cuspiram no rosto e lhe deram socos;

[[v40-26-68]]

^<<v40-26-68,68>>^ e outros o esbofetearam, dizendo: Profetiza-nos, ó Cristo, quem foi que te bateu?

[[v40-26-69]]

^<<v40-26-69,69>>^ Ora, Pedro estava sentado fora, no pátio; e aproximou-se dele uma criada, que disse: Tu também estavas com Jesus, o galileu.

[[v40-26-70]]

^<<v40-26-70,70>>^ Mas ele negou diante de todos, dizendo: Não sei o que dizes.

[[v40-26-71]]

^<<v40-26-71,71>>^ E saindo ele para o vestíbulo, outra criada o viu, e disse aos que ali estavam: Este também estava com Jesus, o nazareno.

[[v40-26-72]]

^<<v40-26-72,72>>^ E ele negou outra vez, e com juramento: Não conheço tal homem.

[[v40-26-73]]

^<<v40-26-73,73>>^ E daí a pouco, aproximando-se os que ali estavam, disseram a Pedro: Certamente tu também és um deles pois a tua fala te denuncia.

[[v40-26-74]]

^<<v40-26-74,74>>^ Então começou ele a praguejar e a jurar, dizendo: Não conheço esse homem. E imediatamente o galo cantou.

[[v40-26-75]]

^<<v40-26-75,75>>^ E Pedro lembrou-se do que dissera Jesus: Antes que o galo cante, três vezes me negarás. E, saindo dali, chorou amargamente.

'''

xref:040-mateus/040-mateus-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-mateus/040-mateus-027.adoc#v40-27-0[Próximo Capítulo &#62;]