include::./index.adoc[]

[[v22-7-0]]
=== Cânticos, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v22-7-1]]

^<<v22-7-1,1>>^ Quão formosos são os teus pés nas sandálias, ó filha de príncipe! Os contornos das tuas coxas são como jóias, obra das mãos de artista.

[[v22-7-2]]

^<<v22-7-2,2>>^ O teu umbigo como uma taça redonda, a que não falta bebida; o teu ventre como montão de trigo, cercado de lírios.

[[v22-7-3]]

^<<v22-7-3,3>>^ Os teus seios são como dois filhos gêmeos da gazela.

[[v22-7-4]]

^<<v22-7-4,4>>^ O teu pescoço como a torre de marfim; os teus olhos como as piscinas de Hesbom, junto à porta de Bate-Rabim; o teu nariz é como torre do Líbano, que olha para Damasco.

[[v22-7-5]]

^<<v22-7-5,5>>^ A tua cabeça sobre ti é como o monte Carmelo, e os cabelos da tua cabeça como a púrpura; o rei está preso pelas tuas tranças.

[[v22-7-6]]

^<<v22-7-6,6>>^ Quão formosa, e quão aprazível és, ó amor em delícias!

[[v22-7-7]]

^<<v22-7-7,7>>^ Essa tua estatura é semelhante à palmeira, e os teus seios aos cachos de uvas.

[[v22-7-8]]

^<<v22-7-8,8>>^ Disse eu: Subirei à palmeira, pegarei em seus ramos; então sejam os teus seios como os cachos da vide, e o cheiro do teu fôlego como o das maçãs,

[[v22-7-9]]

^<<v22-7-9,9>>^ e os teus beijos como o bom vinho para o meu amado, que se bebe suavemente, e se escoa pelos lábios e dentes.

[[v22-7-10]]

^<<v22-7-10,10>>^ Eu sou do meu amado, e o seu amor é por mim.

[[v22-7-11]]

^<<v22-7-11,11>>^ Vem, ó amado meu, saiamos ao campo, passemos as noites nas aldeias.

[[v22-7-12]]

^<<v22-7-12,12>>^ Levantemo-nos de manhã para ir às vinhas, vejamos se florescem as vides, se estão abertas as suas flores, e se as romanzeiras já estão em flor; ali te darei o meu amor.

[[v22-7-13]]

^<<v22-7-13,13>>^ As mandrágoras exalam perfume, e às nossas portas há toda sorte de excelentes frutos, novos e velhos; eu os guardei para ti, ó meu amado.

'''

xref:022-canticos/022-canticos-006.adoc#v22-6-0[&#60; Capítulo Anterior] | <<v22-7-0,Topo>> | xref:022-canticos/022-canticos-008.adoc#v22-8-0[Próximo Capítulo &#62;]