include::./index.adoc[]

[[v22-3-0]]
=== Cânticos, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v22-3-1]]

^<<v22-3-1,1>>^ De noite, em meu leito, busquei aquele a quem ama a minha alma; busquei-o, porém não o achei.

[[v22-3-2]]

^<<v22-3-2,2>>^ Levantar-me-ei, pois, e rodearei a cidade; pelas ruas e pelas praças buscarei aquele a quem ama a minha alma. Busquei-o, porém não o achei.

[[v22-3-3]]

^<<v22-3-3,3>>^ Encontraram-me os guardas que rondavam pela cidade; eu lhes perguntei: Vistes, porventura, aquele a quem ama a minha alma?

[[v22-3-4]]

^<<v22-3-4,4>>^ Apenas me tinha apartado deles, quando achei aquele a quem ama a minha alma; detive-o, e não o deixei ir embora, até que o introduzi na casa de minha mãe, na câmara daquela que me concebeu:

[[v22-3-5]]

^<<v22-3-5,5>>^ Conjuro-vos, ó filhos de Jerusalém, pelas gazelas e cervas do campo, que não acordeis, nem desperteis o amor, até que ele o queira.

[[v22-3-6]]

^<<v22-3-6,6>>^ Que é isso que sobe do deserto, como colunas de fumaça, perfumado de mirra, de incenso, e de toda sorte de pós aromáticos do mercador?

[[v22-3-7]]

^<<v22-3-7,7>>^ Eis que é a liteira de Salomão; estão ao redor dela sessenta valentes, dos valentes de Israel,

[[v22-3-8]]

^<<v22-3-8,8>>^ todos armados de espadas, destros na guerra, cada um com a sua espada a cinta, por causa dos temores noturnos.

[[v22-3-9]]

^<<v22-3-9,9>>^ O rei Salomão fez para si um palanquim de madeira do Líbano.

[[v22-3-10]]

^<<v22-3-10,10>>^ Fez-lhe as colunas de prata, o estrado de ouro, o assento de púrpura, o interior carinhosamente revestido pelas filhas de Jerusalém.

[[v22-3-11]]

^<<v22-3-11,11>>^ Saí, ó filhas de Sião, e contemplai o rei Salomão com a coroa de que sua mãe o coroou no dia do seu desposório, no dia do júbilo do seu coração.

'''

xref:022-canticos/022-canticos-002.adoc#v22-2-0[&#60; Capítulo Anterior] | <<v22-3-0,Topo>> | xref:022-canticos/022-canticos-004.adoc#v22-4-0[Próximo Capítulo &#62;]