include::./index.adoc[]

[[v22-4-0]]
=== Cânticos, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v22-4-1]]

^<<v22-4-1,1>>^ Como és formosa, amada minha, eis que és formosa! os teus olhos são como pombas por detrás do teu véu; o teu cabelo é como o rebanho de cabras que descem pelas colinas de Gileade.

[[v22-4-2]]

^<<v22-4-2,2>>^ Os teus dentes são como o rebanho das ovelhas tosquiadas, que sobem do lavadouro, e das quais cada uma tem gêmeos, e nenhuma delas é desfilhada.

[[v22-4-3]]

^<<v22-4-3,3>>^ Os teus lábios são como um fio de escarlate, e a tua boca e formosa; as tuas faces são como as metades de uma romã por detrás do teu véu.

[[v22-4-4]]

^<<v22-4-4,4>>^ O teu pescoço é como a torre de Davi, edificada para sala de armas; no qual pendem mil broquéis, todos escudos de guerreiros valentes.

[[v22-4-5]]

^<<v22-4-5,5>>^ Os teus seios são como dois filhos gêmeos da gazela, que se apascentam entre os lírios.

[[v22-4-6]]

^<<v22-4-6,6>>^ Antes que refresque o dia e fujam as sombras, irei ao monte da mirra e ao outeiro do incenso.

[[v22-4-7]]

^<<v22-4-7,7>>^ Tu és toda formosa, amada minha, e em ti não há mancha.

[[v22-4-8]]

^<<v22-4-8,8>>^ Vem comigo do Líbano, noiva minha, vem comigo do Líbano. Olha desde o cume de Amana, desde o cume de Senir e de Hermom, desde os covis dos leões, desde os montes dos leopardos.

[[v22-4-9]]

^<<v22-4-9,9>>^ Enlevaste-me o coração, minha irmã, noiva minha; enlevaste-me o coração com um dos teus olhares, com um dos colares do teu pescoço.

[[v22-4-10]]

^<<v22-4-10,10>>^ Quão doce é o teu amor, minha irmã, noiva minha! quanto melhor é o teu amor do que o vinho! e o aroma dos teus ungüentos do que o de toda sorte de especiarias!

[[v22-4-11]]

^<<v22-4-11,11>>^ Os teus lábios destilam o mel, noiva minha; mel e leite estão debaixo da tua língua, e o cheiro dos teus vestidos é como o cheiro do Líbano.

[[v22-4-12]]

^<<v22-4-12,12>>^ Jardim fechado é minha irmã, minha noiva, sim, jardim fechado, fonte selada.

[[v22-4-13]]

^<<v22-4-13,13>>^ Os teus renovos são um pomar de romãs, com frutos excelentes; a hena juntamente com nardo,

[[v22-4-14]]

^<<v22-4-14,14>>^ o nardo, e o açafrão, o cálamo, e o cinamomo, com toda sorte de árvores de incenso; a mirra e o aloés, com todas as principais especiarias.

[[v22-4-15]]

^<<v22-4-15,15>>^ És fonte de jardim, poço de águas vivas, correntes que manam do Líbano!

[[v22-4-16]]

^<<v22-4-16,16>>^ Levanta-te, vento norte, e vem tu, vento sul; assopra no meu jardim, espalha os seus aromas. Entre o meu amado no seu jardim, e coma os seus frutos excelentes!

'''

xref:022-canticos/022-canticos-003.adoc#v22-3-0[&#60; Capítulo Anterior] | <<v22-4-0,Topo>> | xref:022-canticos/022-canticos-005.adoc#v22-5-0[Próximo Capítulo &#62;]