include::./index.adoc[]

[[v22-8-0]]
=== Cânticos, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v22-8-1]]

^<<v22-8-1,1>>^ Ah! quem me dera que foras como meu irmão, que mamou os seios de minha mãe! quando eu te encontrasse lá fora, eu te beijaria; e não me desprezariam!

[[v22-8-2]]

^<<v22-8-2,2>>^ Eu te levaria e te introduziria na casa de minha mãe, e tu me instruirias; eu te daria a beber vinho aromático, o mosto das minhas romãs.

[[v22-8-3]]

^<<v22-8-3,3>>^ A sua mão esquerda estaria debaixo da minha cabeça, e a sua direita me abraçaria.

[[v22-8-4]]

^<<v22-8-4,4>>^ Conjuro-vos, ó filhas de Jerusalém, que não acordeis nem desperteis o amor, até que ele o queira.

[[v22-8-5]]

^<<v22-8-5,5>>^ Quem é esta que sobe do deserto, e vem encostada ao seu amado? Debaixo da macieira te despertei; ali esteve tua mãe com dores; ali esteve com dores aquela que te deu à luz.

[[v22-8-6]]

^<<v22-8-6,6>>^ Põe-me como selo sobre o teu coração, como selo sobre o teu braço; porque o amor é forte como a morte; o ciúme é cruel como o Seol; a sua chama é chama de fogo, verdadeira labareda do Senhor.

[[v22-8-7]]

^<<v22-8-7,7>>^ As muitas águas não podem apagar o amor, nem os rios afogá-lo. Se alguém oferecesse todos os bens de sua casa pelo amor, seria de todo desprezado.

[[v22-8-8]]

^<<v22-8-8,8>>^ Temos uma irmã pequena, que ainda não tem seios; que faremos por nossa irmã, no dia em que ela for pedida em casamento?

[[v22-8-9]]

^<<v22-8-9,9>>^ Se ela for um muro, edificaremos sobre ela uma torrezinha de prata; e, se ela for uma porta, cercá-la-emos com tábuas de cedro.

[[v22-8-10]]

^<<v22-8-10,10>>^ Eu era um muro, e os meus seios eram como as suas torres; então eu era aos seus olhos como aquela que acha paz.

[[v22-8-11]]

^<<v22-8-11,11>>^ Teve Salomão uma vinha em Baal-Hamom; arrendou essa vinha a uns guardas; e cada um lhe devia trazer pelo seu fruto mil peças de prata.

[[v22-8-12]]

^<<v22-8-12,12>>^ A minha vinha que me pertence está diante de mim; tu, ó Salomão, terás as mil peças de prata, e os que guardam o fruto terão duzentas.

[[v22-8-13]]

^<<v22-8-13,13>>^ Ó tu, que habitas nos jardins, os companheiros estão atentos para ouvir a tua voz; faze-me, pois, também ouvi-la:

[[v22-8-14]]

^<<v22-8-14,14>>^ Vem depressa, amado meu, e faze-te semelhante ao gamo ou ao filho da gazela sobre os montes dos aromas.

'''

xref:022-canticos/022-canticos-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaias/023-isaias-001.adoc#v23-1-0[Próximo Capítulo &#62;]