include::./index.adoc[]

[[v17-4-0]]
=== Ester, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-4-1]]

^<<v17-4-1,1>>^ Quando Mordecai soube tudo quanto se havia passado, rasgou as suas vestes, vestiu-se de saco e de cinza, e saiu pelo meio da cidade, clamando com grande e amargo clamor;

[[v17-4-2]]

^<<v17-4-2,2>>^ e chegou até diante da porta do rei, pois ninguém vestido de saco podia entrar elas portas do rei.

[[v17-4-3]]

^<<v17-4-3,3>>^ Em todas as províncias aonde chegava a ordem do rei, e o seu decreto, havia entre os judeus grande pranto, com jejum, e choro, e lamentação; e muitos se deitavam em saco e em cinza.

[[v17-4-4]]

^<<v17-4-4,4>>^ Quando vieram as moças de Ester e os eunucos lho fizeram saber, a rainha muito se entristeceu; e enviou roupa para Mordecai, a fim de que, despindo-lhe o saco, lha vestissem; ele, porém, não a aceitou.

[[v17-4-5]]

^<<v17-4-5,5>>^ Então Ester mandou chamar Hataque, um dos eunucos do rei, que este havia designado para a servir, e o mandou ir ter com Mordecai para saber que era aquilo, e por que era.

[[v17-4-6]]

^<<v17-4-6,6>>^ Hataque, pois, saiu a ter com Mordecai à praça da cidade, diante da porta do rei;

[[v17-4-7]]

^<<v17-4-7,7>>^ e Mordecai lhe fez saber tudo quanto lhe tinha sucedido, como também a soma exata do dinheiro que Hamã prometera pagar ao tesouro do rei pela destruição dos judeus.

[[v17-4-8]]

^<<v17-4-8,8>>^ Também lhe deu a cópia do decreto escrito que se publicara em Susã para os destruir, para que a mostrasse a Ester, e lha explicasse, ordenando-lhe que fosse ter com o rei, e lhe pedisse misericórdia e lhe fizesse súplica ao seu povo.

[[v17-4-9]]

^<<v17-4-9,9>>^ Veio, pois, Hataque, e referiu a Ester as palavras de Mordecai.

[[v17-4-10]]

^<<v17-4-10,10>>^ Então falou Ester a Hataque, mandando-o dizer a Mordecai:

[[v17-4-11]]

^<<v17-4-11,11>>^ Todos os servos do rei, e o povo das províncias do rei, bem sabem que, para todo homem ou mulher que entrar à presença do rei no pátio interior sem ser chamado, não há senão uma sentença, a de morte, a menos que o rei estenda para ele o cetro de ouro, para que viva; mas eu já há trinta dias não sou chamada para entrar a ter com o rei.

[[v17-4-12]]

^<<v17-4-12,12>>^ E referiram a Mordecai as palavras de Ester.

[[v17-4-13]]

^<<v17-4-13,13>>^ Então Mordecai mandou que respondessem a Ester: Não imagines que, por estares no palácio do rei, terás mais sorte para escapar do que todos os outros judeus.

[[v17-4-14]]

^<<v17-4-14,14>>^ Pois, se de todo te calares agora, de outra parte se levantarão socorro e livramento para os judeus, mas tu e a casa de teu pai perecereis; e quem sabe se não foi para tal tempo como este que chegaste ao reino?

[[v17-4-15]]

^<<v17-4-15,15>>^ De novo Ester mandou-os responder a Mordecai:

[[v17-4-16]]

^<<v17-4-16,16>>^ Vai, ajunta todos os judeus que se acham em Susã, e jejuai por mim, e não comais nem bebais por três dias, nem de noite nem de dia; e eu e as minhas moças também assim jejuaremos. Depois irei ter com o rei, ainda que isso não é segundo a lei; e se eu perecer, pereci.

[[v17-4-17]]

^<<v17-4-17,17>>^ Então Mordecai foi e fez conforme tudo quanto Ester lhe ordenara.

'''

xref:017-ester/017-ester-003.adoc#v17-3-0[&#60; Capítulo Anterior] | <<v17-4-0,Topo>> | xref:017-ester/017-ester-005.adoc#v17-5-0[Próximo Capítulo &#62;]