include::./index.adoc[]

[[v17-1-0]]
=== Ester, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-1-1]]

^<<v17-1-1,1>>^ Sucedeu nos dias de Assuero, o Assuero que reinou desde a Índia até a Etiópia, sobre cento e vinte e seis províncias,

[[v17-1-2]]

^<<v17-1-2,2>>^ que, estando o rei Assuero assentado no seu trono do seu reino em Susã, a capital,

[[v17-1-3]]

^<<v17-1-3,3>>^ no terceiro ano de seu reinado, deu um banquete a todos os seus príncipes e seus servos, estando assim perante ele o poder da Pérsia e da Média, os nobres e os oficiais das províncias.

[[v17-1-4]]

^<<v17-1-4,4>>^ Nessa ocasião ostentou as riquezas do seu glorioso reino, e o esplendor da sua excelente grandeza, por muitos dias, a saber cento e oitenta dias.

[[v17-1-5]]

^<<v17-1-5,5>>^ E, acabado aqueles dias, deu o rei um banquete a todo povo que se achava em Susã, a capital, tanto a grandes como a pequenos, por sete dias, no pátio do jardim do palácio real.

[[v17-1-6]]

^<<v17-1-6,6>>^ As cortinas eram de pano branco verde e azul celeste, atadas com cordões de linho fino e de púrpura a argola de prata e a colunas de mármore; os leitos eram de ouro e prata sobre um pavimento mosaico de pórfiro, de mármore, de madrepérola e de pedras preciosas.

[[v17-1-7]]

^<<v17-1-7,7>>^ Dava-se de beber em copos de ouro, os quais eram diferentes uns dos outros; e havia vinho real em abundância, segundo a generosidade do rei.

[[v17-1-8]]

^<<v17-1-8,8>>^ E bebiam como estava prescrito, sem constrangimento; pois o rei tinha ordenado a todos os oficiais do palácio que fizessem conforme a vontade de cada um.

[[v17-1-9]]

^<<v17-1-9,9>>^ Também a rainha Vasti deu um banquete às mulheres no palácio do rei Assuero.

[[v17-1-10]]

^<<v17-1-10,10>>^ Ao sétimo dia, o rei, estando já o seu coração alegre do vinho, mandou a Meumã, Bizta, Harbona, Bigta, Abagta, Zétar e Carcás, os sete eunucos que serviam na presença do rei Assuero,

[[v17-1-11]]

^<<v17-1-11,11>>^ que introduzissem à presença do rei a rainha Vasti, com a coroa real, para mostrar aos povos e aos príncipes a sua formosura, pois era formosíssima.

[[v17-1-12]]

^<<v17-1-12,12>>^ A rainha Vasti, porém, recusou atender à ordem do rei dada por intermédio dos eunucos; pelo que o rei muito se enfureceu, e se inflamou de ira.

[[v17-1-13]]

^<<v17-1-13,13>>^ Então perguntou o rei aos sábios que conheciam os tempos &#123;pois assim se tratavam os negócios do rei, na presença de todos os que sabiam a lei e o direito;

[[v17-1-14]]

^<<v17-1-14,14>>^ e os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena, Memucã, os sete príncipes da Pérsia e da Média, que viam o rosto do rei e ocupavam os primeiros assentos no reino&#125;

[[v17-1-15]]

^<<v17-1-15,15>>^ o que se devia fazer, segundo a lei, à rainha Vasti, por não haver cumprido a ordem do rei Assuero dada por intermédio dos eunucos.

[[v17-1-16]]

^<<v17-1-16,16>>^ Respondeu Memucã na presença do rei e dos príncipes: Não somente contra o rei pecou a rainha Vasti, mas também contra todos os príncipes, e contra todos os povos que há em todas as províncias do rei Assuero.

[[v17-1-17]]

^<<v17-1-17,17>>^ Pois o que a rainha fez chegará ao conhecimento de todas as mulheres, induzindo-as a desprezarem seus maridos quando se disser: O rei Assuero mandou que introduzissem à sua presença a rainha Vasti, e ela não veio.

[[v17-1-18]]

^<<v17-1-18,18>>^ E neste mesmo dia as princesas da Pérsia e da Média, sabendo do que fez a rainha, dirão o mesmo a todos os príncipes do rei; e assim haverá muito desprezo e indignação.

[[v17-1-19]]

^<<v17-1-19,19>>^ Se bem parecer ao rei, saia da sua parte um edito real, e escreva-se entre as leis dos persas e dos medos para que não seja alterado, que Vasti não entre mais na presença do rei Assuero, e dê o rei os seus direitos de rainha a outra que seja melhor do que ela.

[[v17-1-20]]

^<<v17-1-20,20>>^ E quando o decreto que o rei baixar for publicado em todo o seu reino, grande como é, todas as mulheres darão honra a seus maridos, tanto aos nobres como aos humildes.

[[v17-1-21]]

^<<v17-1-21,21>>^ Pareceu bem este conselho ao rei e aos príncipes; e o rei fez conforme a palavra de Memucã,

[[v17-1-22]]

^<<v17-1-22,22>>^ enviando cartas a todas as províncias do rei, a cada província segundo o seu modo de escrever e a cada povo segundo a sua língua, mandando que cada homem fosse senhor em sua casa, e que falasse segundo a língua de seu povo.

'''

xref:016-neemias/016-neemias-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-ester/017-ester-002.adoc#v17-2-0[Próximo Capítulo &#62;]