include::./index.adoc[]

[[v17-6-0]]
=== Ester, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-6-1]]

^<<v17-6-1,1>>^ Naquela mesma noite fugiu do rei o sono; então ele mandou trazer o livro de registro das crônicas, as quais se leram diante do rei.

[[v17-6-2]]

^<<v17-6-2,2>>^ E achou-se escrito que Mordecai tinha denunciado Bigtã e Teres, dois dos eunucos do rei, guardas da porta, que tinham procurado tirar a vida ao rei Assuero.

[[v17-6-3]]

^<<v17-6-3,3>>^ E o rei perguntou: Que honra, ou dignidade, foi conferida a Mordecai por Isso? Responderam os moços do rei que o serviam: Coisa nenhuma se lhe fez.

[[v17-6-4]]

^<<v17-6-4,4>>^ Então disse o rei: Quem está no pátio? Ora, Hamã acabara de entrar no pátio exterior do palácio real para falar com o rei, a fim de que se enforcasse Mordecai na forca que lhe tinha preparado.

[[v17-6-5]]

^<<v17-6-5,5>>^ E os servos do rei lhe responderam: Eis que Hamã está esperando no pátio. E disse o rei que entrasse.

[[v17-6-6]]

^<<v17-6-6,6>>^ Hamã, pois, entrou. Perguntou-lhe o rei: Que se fará ao homem a quem o rei se agrada honrar? Então Hamã disse consigo mesmo: A quem se agradaria o rei honrar mais do que a mim?

[[v17-6-7]]

^<<v17-6-7,7>>^ Pelo que disse Hamã ao rei: Para o homem a quem o rei se agrada honrar,

[[v17-6-8]]

^<<v17-6-8,8>>^ sejam trazidos trajes reais que o rei tenha usado, e o cavalo em que o rei costuma andar, e ponha-se-lhe na cabeça uma coroa real;

[[v17-6-9]]

^<<v17-6-9,9>>^ sejam entregues os trajes e o cavalo à mão dum dos príncipes mais nobres do rei, e vistam deles aquele homem a quem o rei se agrada honrar, e façam-no andar montado pela praça da cidade, e proclamem diante dele: Assim se faz ao homem a quem o rei se agrada honrar!

[[v17-6-10]]

^<<v17-6-10,10>>^ Então disse o rei a Hamã: Apressa-te, toma os trajes e o cavalo como disseste, e faze assim para com o judeu Mordecai, que está sentado à porta do rei; e não deixes falhar coisa alguma de tudo quanto disseste.

[[v17-6-11]]

^<<v17-6-11,11>>^ Hamã, pois, tomou os trajes e o cavalo e vestiu a Mordecai, e o fez andar montado pela praça da cidade, e proclamou diante dele: Assim se faz ao homem a quem o rei se agrada honrar!

[[v17-6-12]]

^<<v17-6-12,12>>^ Depois disto Mordecai voltou para a porta do rei; porém Hamã se recolheu a toda pressa para sua casa, lamentando-se e de cabeça coberta.

[[v17-6-13]]

^<<v17-6-13,13>>^ E contou Hamã a Zerés, sua mulher, e a todos os seus amigos tudo quanto lhe tinha sucedido. Então os seus sábios e Zerés, sua mulher, lhe disseram: Se Mordecai, diante de quem já começaste a cair, é da linhagem dos judeus, não prevalecerás contra ele, antes certamente cairás diante dele.

[[v17-6-14]]

^<<v17-6-14,14>>^ Enquanto estes ainda falavam com ele, chegaram os eunucos do rei, e se apressaram a levar Hamã ao banquete que Ester preparara.

'''

xref:017-ester/017-ester-005.adoc#v17-5-0[&#60; Capítulo Anterior] | <<v17-6-0,Topo>> | xref:017-ester/017-ester-007.adoc#v17-7-0[Próximo Capítulo &#62;]