include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-9-1]]

^<<v17-9-1,1>>^ Ora, no duodécimo mês que é o mês de adar, no dia treze do mês, em que a ordem do rei e o seu decreto estavam para se executar, no dia em que os inimigos dos judeus esperavam assenhorar-se deles, sucedeu o contrário, de modo que os judeus foram os que se assenhorearam do que os odiavam.

[[v17-9-2]]

^<<v17-9-2,2>>^ Ajuntaram-se, pois os judeus nas suas cidades, em todas as províncias do rei Assuero, para pôr as mãos naqueles que procuravam o seu mal; e ninguém podia resistir-lhes, porque o medo deles caíra sobre todos aqueles povos.

[[v17-9-3]]

^<<v17-9-3,3>>^ E todos os príncipes das províncias, os sátrapas, os governadores e os que executavam os negócios do rei auxiliavam aos judeus, porque tinha caído sobre eles o medo de Mordecai.

[[v17-9-4]]

^<<v17-9-4,4>>^ Pois Mordecai era grande na casa do rei, e a sua fama se espalhava por todas as províncias, porque o homem ia se tornando cada vez mais poderoso.

[[v17-9-5]]

^<<v17-9-5,5>>^ Feriram, pois, os judeus a todos os seus inimigos a golpes de espada, matando-os e destruindo-os; e aos que os odiavam trataram como quiseram.

[[v17-9-6]]

^<<v17-9-6,6>>^ E em Susã, a capital, os judeus mataram e destruíram quinhentos homens;

[[v17-9-7]]

^<<v17-9-7,7>>^ como também mataram Parsandata, Dalfom, Aspata,

[[v17-9-8]]

^<<v17-9-8,8>>^ E a Porata, e a Adália, e a Aridata,

[[v17-9-9]]

^<<v17-9-9,9>>^ Parmasta, Arisai, Aridai e Vaizata,

[[v17-9-10]]

^<<v17-9-10,10>>^ os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus; porém ao despojo não estenderam a mão.

[[v17-9-11]]

^<<v17-9-11,11>>^ Nesse mesmo dia veio ao conhecimento do rei o número dos mortos em Susã, a capital.

[[v17-9-12]]

^<<v17-9-12,12>>^ E disse o rei à rainha Ester: Em Susã, a capital, os judeus mataram e destruíram quinhentos homens e os dez filhos de Hamã; que não teriam feito nas demais províncias do rei? Agora, qual é a tua petição? e te será concedida; e qual é ainda o teu rogo? e atender-se-á.

[[v17-9-13]]

^<<v17-9-13,13>>^ Respondeu Ester: Se parecer bem ao rei, conceda aos judeus se acham em Susã que façam ainda amanhã conforme o decreto de hoje; e que os dez filhos de Hamã sejam pendurados na forca.

[[v17-9-14]]

^<<v17-9-14,14>>^ Então o rei mandou que assim se fizesse; e foi publicado em edito em Susã, e os dez filhos de Hamã foram dependurados.

[[v17-9-15]]

^<<v17-9-15,15>>^ Os judeus que se achavam em Susã reuniram-se também no dia catorze do mês de adar, e mataram em Susã trezentos homens; porém ao despojo não estenderam a mão.

[[v17-9-16]]

^<<v17-9-16,16>>^ Da mesma sorte os demais judeus que se achavam nas províncias do rei se reuniram e se dispuseram em defesa das suas vidas, e tiveram repouso dos seus inimigos, matando dos que os odiavam setenta e cinco mil; porém ao despojo não estenderam a mão.

[[v17-9-17]]

^<<v17-9-17,17>>^ Sucedeu isso no dia treze do mês de adar e no dia catorze descansaram, e o fizeram dia de banquetes e de alegria.

[[v17-9-18]]

^<<v17-9-18,18>>^ Mas os judeus que se achavam em Susã se ajuntaram no dia treze como também no dia catorze; e descansaram no dia quinze, fazendo-o dia de banquetes e de alegria.

[[v17-9-19]]

^<<v17-9-19,19>>^ Portanto os judeus das aldeias, que habitam nas cidades não muradas, fazem do dia catorze do mês de adar dia de alegria e de banquetes, e de festas, e dia de mandarem porções escolhidas uns aos outros.

[[v17-9-20]]

^<<v17-9-20,20>>^ Mordecai escreveu estas coisas, e enviou cartas a todos os judeus que se achavam em todas as províncias do rei Assuero, aos de perto e aos de longe,

[[v17-9-21]]

^<<v17-9-21,21>>^ ordenando-lhes que guardassem o dia catorze do mês de adar e o dia quinze do mesmo, todos os anos,

[[v17-9-22]]

^<<v17-9-22,22>>^ como os dias em que os judeus tiveram repouso dos seus inimigos, e o mês em que se lhes mudou a tristeza em alegria, e o pranto em dia de festa, a fim de que os fizessem dias de banquetes e de alegria, e de mandarem porções escolhidas uns aos outros, e dádivas aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ E os judeus se comprometeram a fazer como já tinham começado, e como Mordecai lhes tinha escrito;

[[v17-9-24]]

^<<v17-9-24,24>>^ porque Hamã, filho de Hamedata, o agagita, o inimigo de todos os judeus, tinha intentado destruir os judeus, e tinha lançado Pur, isto é, a sorte, para os assolar e destruir;

[[v17-9-25]]

^<<v17-9-25,25>>^ mas quando isto veio perante o rei, ordenou ele por cartas que o mau intento que Hamã formara contra os judeus recaísse sobre a sua cabeça, e que ele e seus filhos fossem pendurados na forca.

[[v17-9-26]]

^<<v17-9-26,26>>^ Por isso aqueles dias se chamaram Purim, segundo o nome Pur. portanto, por causa de todas as palavras daquela carta, e do que tinham testemunhado nesse sentido, e do que lhes havia sucedido,

[[v17-9-27]]

^<<v17-9-27,27>>^ os judeus concordaram e se comprometeram por si, sua descendência, e por todos os que haviam de unir-se com eles, a não deixarem de guardar estes dois dias, conforme o que se escreveras a respeito deles, e segundo o seu tempo determinado, todos os anos;

[[v17-9-28]]

^<<v17-9-28,28>>^ e a fazerem com que esses dias fossem lembrados e guardados por toda geração, família, província e cidade; e que esses dias de Purim não fossem revogados entre os judeus, e que a memória deles nunca perecesse dentre a sua descendência.

[[v17-9-29]]

^<<v17-9-29,29>>^ Então a rainha Ester, filha de Abiail, e o judeu Mordecai escreveram cartas com toda a autoridade para confirmar esta segunda carta a respeito de Purim,

[[v17-9-30]]

^<<v17-9-30,30>>^ e enviaram-nas a todos os judeus, às cento e vinte e sete províncias do reino de Assuero, com palavras de paz e de verdade,

[[v17-9-31]]

^<<v17-9-31,31>>^ para confirmar esses dias de Purim nos seus tempos determinados, como o judeu Mordecai e a rainha Ester lhes tinham ordenado, e como eles se haviam obrigado por si e pela sua descendência no tocante a seus jejuns e suas lamentações.

[[v17-9-32]]

^<<v17-9-32,32>>^ A ordem de Ester confirmou o que dizia respeito ao Purim; e foi isso registrado nos anais.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]