include::./index.adoc[]

[[v17-5-0]]
=== Ester, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-5-1]]

^<<v17-5-1,1>>^ Ao terceiro dia Ester se vestiu de trajes reais, e se pôs no pátio interior do palácio do rei, defronte da sala do rei; e o rei estava assentado sobre o seu trono, na sala real, defronte da entrada.

[[v17-5-2]]

^<<v17-5-2,2>>^ E sucedeu que, vendo o rei à rainha Ester, que estava em pé no pátio, ela alcançou favor dele; e o rei estendeu para Ester o cetro de ouro que tinha na sua mão. Ester, pois, chegou-se e tocou na ponta do cetro.

[[v17-5-3]]

^<<v17-5-3,3>>^ Então o rei lhe disse: O que é, rainha Ester? qual é a tua petição? Até metade do reino se te dará.

[[v17-5-4]]

^<<v17-5-4,4>>^ Ester respondeu: Se parecer bem ao rei, venha hoje com Hamã ao banquete que tenho preparado para o rei.

[[v17-5-5]]

^<<v17-5-5,5>>^ Então disse o rei: Fazei Hamã apressar-se para que se cumpra a vontade de Ester. Vieram, pois, o rei e Hamã ao banquete que Ester tinha preparado.

[[v17-5-6]]

^<<v17-5-6,6>>^ De novo disse o rei a Ester, no banquete do vinho: Qual é a tua petição? e ser-te-á concedida; e qual é o teu rogo? e se te dará, ainda que seja metade do reino.

[[v17-5-7]]

^<<v17-5-7,7>>^ Ester respondeu, dizendo; Eis a minha petição e o meu rogo:

[[v17-5-8]]

^<<v17-5-8,8>>^ Se tenho alcançado favor do rei, e se parecer bem ao rei concerder-me a minha petição e cumprir o meu rogo, venha o rei com Hamã ao banquete que lhes hei de preparar, e amanhã farei conforme a palavra do rei.

[[v17-5-9]]

^<<v17-5-9,9>>^ Então naquele dia Hamã saiu alegre e de bom ânimo; porém, vendo Mordecai à porta do rei, e que ele não se levantava nem tremia diante dele, Hamã se encheu de furor contra Mordecai.

[[v17-5-10]]

^<<v17-5-10,10>>^ Contudo Hamã se refreou, e foi para casa; enviou e mandou vir os seus amigos, e Zéres, sua mulher.

[[v17-5-11]]

^<<v17-5-11,11>>^ E contou-lhes Hamã a glória de suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido, e como o havia exaltado sobre os príncipes e servos do rei.

[[v17-5-12]]

^<<v17-5-12,12>>^ E acrescentou: Tampouco a rainha Ester a ninguém fez vir com o rei ao banquete que preparou, senão a mim; e também para amanhã estou convidado por ela juntamente com o rei.

[[v17-5-13]]

^<<v17-5-13,13>>^ Todavia tudo isso não me satisfaz, enquanto eu vir o judeu Mordecai sentado à porta do rei.

[[v17-5-14]]

^<<v17-5-14,14>>^ Então lhe disseram Zéres, sua mulher, e todos os seus amigos: Faça-se uma forca de cinqüenta côvados de altura, e pela manhã dize ao rei que nela seja enforcado Mordecai; e então entra alegre com o rei para o banquete. E este conselho agradou a Hamã, que mandou fazer a forca.

'''

xref:017-ester/017-ester-004.adoc#v17-4-0[&#60; Capítulo Anterior] | <<v17-5-0,Topo>> | xref:017-ester/017-ester-006.adoc#v17-6-0[Próximo Capítulo &#62;]