include::./index.adoc[]

[[v17-2-0]]
=== Ester, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-2-1]]

^<<v17-2-1,1>>^ Passadas estas coisas e aplacada a ira do rei Assuero, lembrou-se ele de Vasti, do que ela fizera e do que se decretara a seu respeito.

[[v17-2-2]]

^<<v17-2-2,2>>^ Então disseram os servos do rei que lhe ministravam: Busquem-se para o rei moças virgens e formosas.

[[v17-2-3]]

^<<v17-2-3,3>>^ Ponha o rei em todas as províncias do seu reino oficiais que ajuntem todas as moças virgens e formosas em Susã, a capital, na casa das mulheres, sob a custódia de Hegai, eunuco do rei, guarda das mulheres; e dêem-se-lhes os seus cosméticos.

[[v17-2-4]]

^<<v17-2-4,4>>^ E a donzela que agradar ao rei seja rainha em lugar de Vasti. E isso pareceu bem ao rei; e ele assim fez.

[[v17-2-5]]

^<<v17-2-5,5>>^ Havia então em Susã, a capital, certo judeu, benjamita, cujo nome era Mordecai, filho de Jair, filho de Simei, filho de Quis,

[[v17-2-6]]

^<<v17-2-6,6>>^ que tinha sido levado de Jerusalém com os cativos que foram deportados com Jeconias, rei de Judá, o qual Nabucodonosor, rei de Babilônia, transportara.

[[v17-2-7]]

^<<v17-2-7,7>>^ Criara ele Hadassa, isto é, Ester, filha de seu tio, pois não tinha ela nem pai nem mãe; e era donzela esbelta e formosa; e, morrendo seu pai e sua mãe, Mordecai a tomara por filha.

[[v17-2-8]]

^<<v17-2-8,8>>^ Tendo se divulgado a ordem do rei e o seu edito, e ajuntando-se muitas donzelas em Susã, a capital, sob a custódia de Hegai, levaram também Ester ao palácio do rei, à custódia de Hegai, guarda das mulheres.

[[v17-2-9]]

^<<v17-2-9,9>>^ E a donzela gradou-lhe, e alcançou o favor dele; pelo que ele se apressou em dar-lhe os cosméticos e os devidos alimentos, como também sete donzelas escolhidas do palácio do rei; e a fez passar com as suas donzelas ao melhor lugar na casa das mulheres.

[[v17-2-10]]

^<<v17-2-10,10>>^ Ester, porém, não tinha declarado o seu povo nem a sua parentela, pois Mordecai lhe tinha ordenado que não o declarasse.

[[v17-2-11]]

^<<v17-2-11,11>>^ E cada dia Mordecai passeava diante do pátio da casa das mulheres, para lhe informar como Ester passava e do que lhe sucedia.

[[v17-2-12]]

^<<v17-2-12,12>>^ Ora, quando chegava a vez de cada donzela vir ao Rei Assuero, depois que fora feito a cada uma segundo prescrito para as mulheres, por doze meses &#123;pois assim se cumpriam os dias de seus preparativos, a saber, seis meses com óleo de mirra, e seis meses com especiarias e ungüentos em uso entre as mulheres&#125;;

[[v17-2-13]]

^<<v17-2-13,13>>^ desta maneira vinha a donzela ao rei: dava-lhe tudo quanto ela quisesse para levar consigo da casa das mulheres para o palácio do rei;

[[v17-2-14]]

^<<v17-2-14,14>>^ à tarde ela entrava, e pela manhã voltava para a segunda casa das mulheres, à custódia de Saasgaz, eunuco do rei, guarda das concubinas; ela não tornava mais ao rei, salvo se o rei desejasse, e fosse ela chamada por nome.

[[v17-2-15]]

^<<v17-2-15,15>>^ Ora, quando chegou a vez de Ester, filha de Abiail, tio de Mordecai, que a tomara por sua filha, para ir ao rei, coisa nenhuma pediu senão o que indicou Hegai, eunuco do rei, guarda das mulheres. Mas Ester alcançava graça aos olhos de todos quantos a viam.

[[v17-2-16]]

^<<v17-2-16,16>>^ Ester foi levada ao rei Assuero, ao palácio real, no décimo mês, que é o mês de tebete, no sétimo ano de seu reinado.

[[v17-2-17]]

^<<v17-2-17,17>>^ E o rei amou a Ester mais do que a todas mulheres, e ela alcançou graça e favor diante dele mais do que todas as virgens; de sorte que lhe pôs sobre a cabeça a coroa real, e afez rainha em lugar de Vasti.

[[v17-2-18]]

^<<v17-2-18,18>>^ Então o rei deu um grande banquete a todos os seus príncipes e aos seus servos; era um banquete em honra de Ester; e concedeu alívio às províncias, e fez presentes com régia liberalidade.

[[v17-2-19]]

^<<v17-2-19,19>>^ Quando pela segunda vez se ajuntavam as virgens, Mordecai estava sentado à porta do rei.

[[v17-2-20]]

^<<v17-2-20,20>>^ Ester, porém, como Mordecai lhe ordenara, não tinha declarado a sua parentela nem o seu povo: porque obedecia as ordens de Mordecai como quando estava sendo criada em casa dele.

[[v17-2-21]]

^<<v17-2-21,21>>^ Naqueles dias, estando Mordecai sentado à porta do rei, dois eunucos do rei, os guardas da porta, Bigtã e Teres, se indignaram e procuravam tirar a vida ao rei Assuero.

[[v17-2-22]]

^<<v17-2-22,22>>^ E veio isto ao conhecimento de Mordecai, que revelou à rainha Ester; e Ester o disse ao rei em nome de Mordecai.

[[v17-2-23]]

^<<v17-2-23,23>>^ Quando se investigou o negócio e se achou ser verdade, ambos foram enforcados; e isso foi escrito no livro das crônicas perante o rei.

'''

xref:017-ester/017-ester-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-ester/017-ester-003.adoc#v17-3-0[Próximo Capítulo &#62;]