include::./index.adoc[]

[[v17-7-0]]
=== Ester, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-7-1]]

^<<v17-7-1,1>>^ Entraram, pois, o rei e Hamã para se banquetearem com a rainha Ester.

[[v17-7-2]]

^<<v17-7-2,2>>^ Ainda outra vez disse o rei a Ester, no segundo dia, durante o banquete do vinho: Qual é a tua petição, rainha Ester? e ser-te-á concedida; e qual é o teu rogo? Até metade do reino se te dará.

[[v17-7-3]]

^<<v17-7-3,3>>^ Então respondeu a rainha Ester, e disse: Ó rei! se eu tenho alcançado o teu favor, e se parecer bem ao rei, seja-me concedida a minha vida, eis a minha petição, e o meu povo, eis o meu rogo;

[[v17-7-4]]

^<<v17-7-4,4>>^ porque fomos vendidos, eu e o meu povo, para sermos destruídos, mortos e exterminados; se ainda por servos e por servas nos tivessem vendido, eu teria me calado, ainda que o adversário não poderia ter compensado a perda do rei.

[[v17-7-5]]

^<<v17-7-5,5>>^ Então falou o rei Assuero, e disse à rainha Ester: Quem é e onde está esse, cujo coração o instigou a fazer assim?

[[v17-7-6]]

^<<v17-7-6,6>>^ Respondeu Ester: Um adversário e inimigo, este perverso Hamã! Então Hamã ficou aterrorizado perante o rei e a rainha.

[[v17-7-7]]

^<<v17-7-7,7>>^ E o rei, no seu furor, se levantou do banquete do vinho e entrou no jardim do palácio; Hamã, porém, ficou para rogar à rainha Ester pela sua vida, porque viu que já o mal lhe estava determinado pelo rei.

[[v17-7-8]]

^<<v17-7-8,8>>^ Ora, o rei voltou do jardim do palácio à sala do banquete do vinho; e Hamã havia caído prostrado sobre o leito em que estava Ester. Então disse o rei: Porventura quereria ele também violar a rainha perante mim na minha própria casa? Ao sair essa palavra da boca do rei, cobriram a Hamã o rosto.

[[v17-7-9]]

^<<v17-7-9,9>>^ Então disse Harbona, um dos eunucos que serviam diante do rei: Eis que a forca de cinqüenta côvados de altura que Hamã fizera para Mordecai, que falara em defesa do rei, está junto à casa de Hamã. Então disse o rei: Enforcai-o nela.

[[v17-7-10]]

^<<v17-7-10,10>>^ Enforcaram-no, pois, na forca que ele tinha preparado para Mordecai. Então o furor do rei se aplacou.

'''

xref:017-ester/017-ester-006.adoc#v17-6-0[&#60; Capítulo Anterior] | <<v17-7-0,Topo>> | xref:017-ester/017-ester-008.adoc#v17-8-0[Próximo Capítulo &#62;]