include::./index.adoc[]

[[v17-3-0]]
=== Ester, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v17-3-1]]

^<<v17-3-1,1>>^ Depois destas coisas o rei Assuero engrandeceu a Hamã, filho de Hamedata, o agagita, e o exaltou, pondo-lhe o assento acima dos de todos os príncipes que estavam com ele.

[[v17-3-2]]

^<<v17-3-2,2>>^ E todos os servos do rei que estavam à porta do rei se inclinavam e se prostravam perante Hamã, porque assim ordenara o rei a seu respeito: porém Mordecai não se inclinava nem se prostrava.

[[v17-3-3]]

^<<v17-3-3,3>>^ Então os servos do rei que estavam à porta do rei disseram a Mordecai: Por que transgrides a ordem do rei?

[[v17-3-4]]

^<<v17-3-4,4>>^ E sucedeu que, dizendo-lhe eles isso dia após dia, e não lhes dando ele ouvidos, o fizeram saber a Hamã, para verem se o procedimento de Mordecai seria tolerado; pois ele lhes tinha declarado que era judeu.

[[v17-3-5]]

^<<v17-3-5,5>>^ Vendo, pois, Hamã que Mordecai não se inclinava nem se prostrava diante dele, encheu-se de furor.

[[v17-3-6]]

^<<v17-3-6,6>>^ Mas, achou pouco tirar a vida somente a Mordecai; porque lhe haviam declarado o povo de Mordecai. Por esse motivo Hamã procurou destruir todos os judeus, o povo de Mordecai, que havia em todo o reino de Assuero.

[[v17-3-7]]

^<<v17-3-7,7>>^ No primeiro mês, que é o mês de nisã, no ano duodécimo do rei Assuero, se lançou Pur, isto é, a sorte, perante Hamã, para cada dia e para mês, até o duodécimo, que é o mês de adar.

[[v17-3-8]]

^<<v17-3-8,8>>^ E Hamã disse ao rei Assuero: Existe espalhado e disperso entre os povos em todas as províncias do teu reino um povo, cujas leis são diferentes das leis de todos os povos, e que não cumprem as leis do rei; pelo que não convém ao rei tolerá-lo.

[[v17-3-9]]

^<<v17-3-9,9>>^ Se bem parecer ao rei, decrete-se que seja destruído; e eu pagarei dez mil talentos de prata aos encarregados dos negócios do rei, para os recolherem ao tesouro do rei.

[[v17-3-10]]

^<<v17-3-10,10>>^ Então o rei tirou do seu dedo o anel, e o deu a Hamã, filho de Hamedata, o agagita, o inimigo dos judeus;

[[v17-3-11]]

^<<v17-3-11,11>>^ e disse o rei a Hamã: Essa prata te é dada, como também esse povo, para fazeres dele o que bem parecer aos teus olhos.

[[v17-3-12]]

^<<v17-3-12,12>>^ Então foram chamados os secretários do rei no primeiro mês, no dia treze do mesmo e, conforme tudo, quando Hamã ordenou, se escreveu aos sátrapas do rei, e aos governadores que havia sobre todas as províncias, e aos príncipes de todos os povos; a cada província segundo o seu modo de escrever, e a cada povo segundo a sua língua; em nome do rei Assuero se escreveu, e com o anel do rei se selou.

[[v17-3-13]]

^<<v17-3-13,13>>^ Entiaram-se as cartas pelos correios a todas províncias do rei, para que destruíssem, matassem, e fizessem perecer todos os judeus, moços e velhos, crianças e mulheres, em um mesmo dia, a treze do duodécimo mês, que é o mês de adar, e para que lhes saqueassem os bens.

[[v17-3-14]]

^<<v17-3-14,14>>^ Uma cópia do documento havia de ser publicada como decreto em cada província, para que todos os povos estivessem preparados para aquele dia.

[[v17-3-15]]

^<<v17-3-15,15>>^ Os correios saíram às pressas segundo a ordem do rei, e o decreto foi proclamado em Susã, a capital. Então, o rei e Hamã se assentaram a beber, mas a cidade de Susã estava perplexa.

'''

xref:017-ester/017-ester-002.adoc#v17-2-0[&#60; Capítulo Anterior] | <<v17-3-0,Topo>> | xref:017-ester/017-ester-004.adoc#v17-4-0[Próximo Capítulo &#62;]