include::./index.adoc[]

[[v3-11-0]]
=== Levítico, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-11-1]]

^<<v3-11-1,1>>^ Falou o Senhor a Moisés e a Arão, dizendo-lhes:

[[v3-11-2]]

^<<v3-11-2,2>>^ Dizei aos filhos de Israel: Estes são os animais que podereis comer dentre todos os animais que há sobre a terra:

[[v3-11-3]]

^<<v3-11-3,3>>^ dentre os animais, todo o que tem a unha fendida, de sorte que se divide em duas, o que rumina, esse podereis comer.

[[v3-11-4]]

^<<v3-11-4,4>>^ Os seguintes, contudo, não comereis, dentre os que ruminam e dentre os que têm a unha fendida: o camelo, porque rumina mas não tem a unha fendida, esse vos será imundo;

[[v3-11-5]]

^<<v3-11-5,5>>^ o querogrilo, porque rumina mas não tem a unha fendida, esse vos será imundo;

[[v3-11-6]]

^<<v3-11-6,6>>^ a lebre, porque rumina mas não tem a unha fendida, essa vos será imunda;

[[v3-11-7]]

^<<v3-11-7,7>>^ e o porco, porque tem a unha fendida, de sorte que se divide em duas, mas não rumina, esse vos será imundo.

[[v3-11-8]]

^<<v3-11-8,8>>^ Da sua carne não comereis, nem tocareis nos seus cadáveres; esses vos serão imundos.

[[v3-11-9]]

^<<v3-11-9,9>>^ Estes são os que podereis comer de todos os que há nas águas: todo o que tem barbatanas e escamas, nas águas, nos mares e nos rios, esse podereis comer.

[[v3-11-10]]

^<<v3-11-10,10>>^ Mas todo o que não tem barbatanas, nem escamas, nos mares e nos rios, todo réptil das águas, e todos os animais que vivem nas águas, estes vos serão abomináveis,

[[v3-11-11]]

^<<v3-11-11,11>>^ tê-los-eis em abominação; da sua carne não comereis, e abominareis os seus cadáveres.

[[v3-11-12]]

^<<v3-11-12,12>>^ Tudo o que não tem barbatanas nem escamas, nas águas, será para vós abominável.

[[v3-11-13]]

^<<v3-11-13,13>>^ Dentre as aves, a estas abominareis; não se comerão, serão abomináveis: a águia, o quebrantosso, o xofrango,

[[v3-11-14]]

^<<v3-11-14,14>>^ o açor, o falcão segundo a sua espécie,

[[v3-11-15]]

^<<v3-11-15,15>>^ todo corvo segundo a sua espécie,

[[v3-11-16]]

^<<v3-11-16,16>>^ o avestruz, o mocho, a gaivota, o gavião segundo a sua espécie,

[[v3-11-17]]

^<<v3-11-17,17>>^ o bufo, o corvo marinho, a coruja,

[[v3-11-18]]

^<<v3-11-18,18>>^ o porfirião, o pelicano, o abutre,

[[v3-11-19]]

^<<v3-11-19,19>>^ a cegonha, a garça segundo a sua, espécie, a poupa e o morcego.

[[v3-11-20]]

^<<v3-11-20,20>>^ Todos os insetos alados que andam sobre quatro pés, serão para vós uma abominação.

[[v3-11-21]]

^<<v3-11-21,21>>^ Contudo, estes há que podereis comer de todos os insetos alados que andam sobre quatro pés: os que têm pernas sobre os seus pés, para saltar com elas sobre a terra;

[[v3-11-22]]

^<<v3-11-22,22>>^ isto é, deles podereis comer os seguintes: o gafanhoto segundo a sua espécie, o solham segundo a sua espécie, o hargol segundo a sua espécie e o hagabe segundo a sua espécie.

[[v3-11-23]]

^<<v3-11-23,23>>^ Mas todos os outros insetos alados que têm quatro pés, serão para vós uma abominação.

[[v3-11-24]]

^<<v3-11-24,24>>^ Também por eles vos tornareis imundos; qualquer que tocar nos seus cadáveres, será imundo até a tarde,

[[v3-11-25]]

^<<v3-11-25,25>>^ e quem levar qualquer parte dos seus cadáveres, lavará as suas vestes, e será imundo até a tarde.

[[v3-11-26]]

^<<v3-11-26,26>>^ Todo animal que tem unhas fendidas, mas cuja fenda não as divide em duas, e que não rumina, será para vós imundo; qualquer que tocar neles será imundo.

[[v3-11-27]]

^<<v3-11-27,27>>^ Todos os plantígrados dentre os quadrúpedes, esses vos serão imundos; qualquer que tocar nos seus cadáveres será imundo até a tarde,

[[v3-11-28]]

^<<v3-11-28,28>>^ e o que levar os seus cadáveres lavará as suas vestes, e será imundo até a tarde; eles serão para vós imundos.

[[v3-11-29]]

^<<v3-11-29,29>>^ Estes também vos serão por imundos entre os animais que se arrastam sobre a terra: a doninha, o rato, o crocodilo da terra segundo a sua espécie,

[[v3-11-30]]

^<<v3-11-30,30>>^ o musaranho, o crocodilo da água, a lagartixa, o lagarto e a toupeira.

[[v3-11-31]]

^<<v3-11-31,31>>^ Esses vos serão imundos dentre todos os animais rasteiros; qualquer que os tocar, depois de mortos, será imundo até a tarde;

[[v3-11-32]]

^<<v3-11-32,32>>^ e tudo aquilo sobre o que cair o cadáver de qualquer deles será imundo; seja vaso de madeira, ou vestidura, ou pele, ou saco, seja qualquer instrumento com que se faz alguma obra, será metido na água, e será imundo até a tarde; então será limpo.

[[v3-11-33]]

^<<v3-11-33,33>>^ E quanto a todo vaso de barro dentro do qual cair algum deles, tudo o que houver nele será imundo, e o vaso quebrareis.

[[v3-11-34]]

^<<v3-11-34,34>>^ Todo alimento depositado nele, que se pode comer, sobre o qual vier água, será imundo; e toda bebida que se pode beber, sendo depositada em qualquer destes vasos será imunda.

[[v3-11-35]]

^<<v3-11-35,35>>^ E tudo aquilo sobre o que cair: alguma parte dos cadáveres deles será imundo; seja forno, seja fogão, será quebrado; imundos são, portanto para vós serão imundos.

[[v3-11-36]]

^<<v3-11-36,36>>^ Contudo, uma fonte ou cisterna, em que há depósito de água, será limpa; mas quem tocar no cadáver será imundo.

[[v3-11-37]]

^<<v3-11-37,37>>^ E, se dos seus cadáveres cair alguma coisa sobre alguma semente que se houver de semear, esta será limpa;

[[v3-11-38]]

^<<v3-11-38,38>>^ mas se for deitada água sobre a semente, e se dos cadáveres cair alguma coisa sobre ela, então ela será para vós imunda.

[[v3-11-39]]

^<<v3-11-39,39>>^ E se morrer algum dos animais de que vos é lícito comer, quem tocar no seu cadáver será imundo até a tarde;

[[v3-11-40]]

^<<v3-11-40,40>>^ e quem comer do cadáver dele lavará as suas vestes, e será imundo até a tarde; igualmente quem levar o cadáver dele lavará as suas vestes, e será imundo até a tarde.

[[v3-11-41]]

^<<v3-11-41,41>>^ Também todo animal rasteiro que se move sobre a terra será abominação; não se comerá.

[[v3-11-42]]

^<<v3-11-42,42>>^ Tudo o que anda sobre o ventre, tudo o que anda sobre quatro pés, e tudo o que tem muitos pés, enfim todos os animais rasteiros que se movem sobre a terra, desses não comereis, porquanto são abomináveis.

[[v3-11-43]]

^<<v3-11-43,43>>^ Não vos tomareis abomináveis por nenhum animal rasteiro, nem neles vos contaminareis, para não vos tornardes imundos por eles.

[[v3-11-44]]

^<<v3-11-44,44>>^ Porque eu sou o Senhor vosso Deus; portanto santificai-vos, e sede santos, porque eu sou santo; e não vos contaminareis com nenhum animal rasteiro que se move sobre a terra;

[[v3-11-45]]

^<<v3-11-45,45>>^ porque eu sou o Senhor, que vos fiz subir da terra do Egito, para ser o vosso Deus, sereis pois santos, porque eu sou santo.

[[v3-11-46]]

^<<v3-11-46,46>>^ Esta é a lei sobre os animais e as aves, e sobre toda criatura vivente que se move nas águas e toda criatura que se arrasta sobre a terra;

[[v3-11-47]]

^<<v3-11-47,47>>^ para fazer separação entre o imundo e o limpo, e entre os animais que se podem comer e os animais que não se podem comer.

'''

xref:003-levitico/003-levitico-010.adoc#v3-10-0[&#60; Capítulo Anterior] | <<v3-11-0,Topo>> | xref:003-levitico/003-levitico-012.adoc#v3-12-0[Próximo Capítulo &#62;]