include::./index.adoc[]

[[v3-7-0]]
=== Levítico, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-7-1]]

^<<v3-7-1,1>>^ Esta é a lei da oferta pela culpa: coisa santíssima é.

[[v3-7-2]]

^<<v3-7-2,2>>^ No lugar em que imolam o holocausto, imolarão a oferta pela culpa, e o sangue dela se espargirá sobre o altar em redor.

[[v3-7-3]]

^<<v3-7-3,3>>^ Dela se oferecerá toda a gordura: a cauda gorda, e a gordura que cobre a fressura,

[[v3-7-4]]

^<<v3-7-4,4>>^ os dois rins e a gordura que está sobre eles, e a que está junto aos lombos, e o redenho sobre o fígado, juntamente com os rins, os tirará;

[[v3-7-5]]

^<<v3-7-5,5>>^ e o sacerdote os queimará sobre o altar em oferta queimada ao Senhor; é uma oferta pela culpa.

[[v3-7-6]]

^<<v3-7-6,6>>^ Todo varão entre os sacerdotes comerá dela; num lugar santo se comerá; coisa santíssima é.

[[v3-7-7]]

^<<v3-7-7,7>>^ Como é a oferta pelo pecado, assim será a oferta pela culpa; há uma só lei para elas, a saber, pertencerá ao sacerdote que com ela houver feito expiação.

[[v3-7-8]]

^<<v3-7-8,8>>^ Também o sacerdote que oferecer o holocausto de alguém terá para si o couro do animal que tiver oferecido.

[[v3-7-9]]

^<<v3-7-9,9>>^ Igualmente toda oferta de cereais que se assar ao forno, como tudo o que se preparar na frigideira e na assadeira, pertencerá ao sacerdote que a oferecer.

[[v3-7-10]]

^<<v3-7-10,10>>^ Também toda oferta de cereais, seja ela amassada com azeite, ou seja seca, pertencerá a todos os filhos de Arão, tanto a um como a outro.

[[v3-7-11]]

^<<v3-7-11,11>>^ Esta é a lei do sacrifício das ofertas pacíficas que se oferecerá ao Senhor:

[[v3-7-12]]

^<<v3-7-12,12>>^ Se alguém o oferecer por oferta de ação de graças, com o sacrifício de ação de graças oferecerá bolos ázimos amassados com azeite, e coscorões ázimos untados com azeite, e bolos amassados com azeite, de flor de farinha, bem embebidos.

[[v3-7-13]]

^<<v3-7-13,13>>^ Com os bolos oferecerá pão levedado como sua oferta, com o sacrifício de ofertas pacíficas por ação de graças.

[[v3-7-14]]

^<<v3-7-14,14>>^ E dele oferecerá um de cada oferta por oferta alçada ao Senhor, o qual pertencerá ao sacerdote que espargir o sangue da oferta pacífica.

[[v3-7-15]]

^<<v3-7-15,15>>^ Ora, a carne do sacrifício de ofertas pacíficas por ação de graças se comerá no dia do seu oferecimento; nada se deixará dela até pela manhã.

[[v3-7-16]]

^<<v3-7-16,16>>^ Se, porém, o sacrifício da sua oferta for voto, ou oferta voluntária, no dia em que for oferecido se comerá, e no dia seguinte se comerá o que dele ficar;

[[v3-7-17]]

^<<v3-7-17,17>>^ mas o que ainda ficar da carne do sacrifício até o terceiro dia será queimado no fogo.

[[v3-7-18]]

^<<v3-7-18,18>>^ Se alguma parte da carne do sacrifício da sua oferta pacífica se comer ao terceiro dia, aquele sacrifício não será aceito, nem será imputado àquele que o tiver oferecido; coisa abominável será, e quem dela comer levará a sua iniqüidade.

[[v3-7-19]]

^<<v3-7-19,19>>^ A carne que tocar alguma coisa imunda não se comerá; será queimada no fogo; mas da outra carne, qualquer que estiver limpo comerá dela;

[[v3-7-20]]

^<<v3-7-20,20>>^ todavia, se alguma pessoa, estando imunda, comer a carne do sacrifício da oferta pacífica, que pertence ao Senhor, essa pessoa será extirpada do seu povo.

[[v3-7-21]]

^<<v3-7-21,21>>^ E, se alguma pessoa, tendo tocado alguma coisa imunda, como imundícia de homem, ou gado imundo, ou qualquer abominação imunda, comer da carne do sacrifício da oferta pacífica, que pertence ao Senhor, essa pessoa será extirpada do seu povo.

[[v3-7-22]]

^<<v3-7-22,22>>^ Depois disse o Senhor a Moisés:

[[v3-7-23]]

^<<v3-7-23,23>>^ Fala aos filhos de Israel, dizendo: Nenhuma gordura de boi, nem de carneiro, nem de cabra comereis.

[[v3-7-24]]

^<<v3-7-24,24>>^ Todavia pode-se usar a gordura do animal que morre por si mesmo, e a gordura do que é dilacerado por feras, para qualquer outro fim; mas de maneira alguma comereis dela.

[[v3-7-25]]

^<<v3-7-25,25>>^ Pois quem quer que comer da gordura do animal, do qual se oferecer oferta queimada ao Senhor, sim, a pessoa que dela comer será extirpada do seu povo.

[[v3-7-26]]

^<<v3-7-26,26>>^ E nenhum sangue comereis, quer de aves, quer de gado, em qualquer das vossas habitações.

[[v3-7-27]]

^<<v3-7-27,27>>^ Toda pessoa que comer algum sangue será extirpada do seu povo.

[[v3-7-28]]

^<<v3-7-28,28>>^ Disse mais o Senhor a Moisés:

[[v3-7-29]]

^<<v3-7-29,29>>^ Fala aos filhos de Israel, dizendo: Quem oferecer sacrifício de oferta pacífica ao Senhor trará ao Senhor a respectiva oblação da sua oferta pacífica.

[[v3-7-30]]

^<<v3-7-30,30>>^ Com as próprias mãos trará as ofertas queimadas do Senhor; o peito com a gordura trará, para movê-lo por oferta de movimento perante o Senhor.

[[v3-7-31]]

^<<v3-7-31,31>>^ E o sacerdote queimará a gordura sobre o altar, mas o peito pertencerá a Arão e a seus filhos.

[[v3-7-32]]

^<<v3-7-32,32>>^ E dos sacrifícios das vossas ofertas pacíficas, dareis a coxa direita ao sacerdote por oferta alçada.

[[v3-7-33]]

^<<v3-7-33,33>>^ Aquele dentre os filhos de Arão que oferecer o sangue da oferta pacífica, e a gordura, esse terá a coxa direita por sua porção;

[[v3-7-34]]

^<<v3-7-34,34>>^ porque o peito movido e a coxa alçada tenho tomado dos filhos de Israel, dos sacrifícios das suas ofertas pacíficas, e os tenho dado a Arão, o sacerdote, e a seus filhos, como sua porção, para sempre, da parte dos filhos de Israel.

[[v3-7-35]]

^<<v3-7-35,35>>^ Esta é a porção sagrada de Arão e a porção sagrada de seus filhos, das ofertas queimadas do Senhor, desde o dia em que ele os apresentou para administrar o sacerdócio ao Senhor;

[[v3-7-36]]

^<<v3-7-36,36>>^ a qual o Senhor, no dia em que os ungiu, ordenou que se lhes desse da parte dos filhos de Israel; é a sua porção para sempre, pelas suas gerações.

[[v3-7-37]]

^<<v3-7-37,37>>^ Esta é a lei do holocausto, da oferta de cereais, da oferta pelo pecado, da oferta pela culpa, da oferta das consagrações, e do sacrifício das ofertas pacíficas;

[[v3-7-38]]

^<<v3-7-38,38>>^ a qual o Senhor entregou a Moisés no monte Sinai, no dia em que este estava ordenando aos filhos de Israel que oferecessem as suas ofertas ao Senhor, no deserto de Sinai.

'''

xref:003-levitico/003-levitico-006.adoc#v3-6-0[&#60; Capítulo Anterior] | <<v3-7-0,Topo>> | xref:003-levitico/003-levitico-008.adoc#v3-8-0[Próximo Capítulo &#62;]