include::./index.adoc[]

[[v3-3-0]]
=== Levítico, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-3-1]]

^<<v3-3-1,1>>^ Se a oferta de alguém for sacrifício pacífico: se a fizer de gado vacum, seja macho ou fêmea, oferecê-la-á sem defeito diante do Senhor;

[[v3-3-2]]

^<<v3-3-2,2>>^ porá a mão sobre a cabeça da sua oferta e a imolará à porta da tenda da revelação; e os filhos de Arão, os sacerdotes, espargirão o sangue sobre o altar em redor.

[[v3-3-3]]

^<<v3-3-3,3>>^ Então, do sacrifício de oferta pacífica, fará uma oferta queimada ao Senhor; a gordura que cobre a fressura, sim, toda a gordura que está sobre ela,

[[v3-3-4]]

^<<v3-3-4,4>>^ os dois rins e a gordura que está sobre eles, e a que está junto aos lombos, e o redenho que está sobre o fígado, juntamente com os rins, ele os tirará.

[[v3-3-5]]

^<<v3-3-5,5>>^ E os filhos de Arão queimarão isso sobre o altar, em cima do holocausto que está sobre a lenha no fogo; é oferta queimada, de cheiro suave ao Senhor.

[[v3-3-6]]

^<<v3-3-6,6>>^ E se a sua oferta por sacrifício pacífico ao Senhor for de gado miúdo, seja macho ou fêmea, sem defeito o oferecerá.

[[v3-3-7]]

^<<v3-3-7,7>>^ Se oferecer um cordeiro por sua oferta, oferecê-lo-á perante o Senhor;

[[v3-3-8]]

^<<v3-3-8,8>>^ e porá a mão sobre a cabeça da sua oferta, e a imolará diante da tenda da revelação; e os filhos de Arão espargirão o sangue sobre o altar em redor.

[[v3-3-9]]

^<<v3-3-9,9>>^ Então, do sacrifício de oferta pacífica, fará uma oferta queimada ao Senhor; a gordura da oferta, a cauda gorda inteira, tirá-la-á junto ao espinhaço; e a gordura que cobre a fressura, sim, toda a gordura que está sobre ela,

[[v3-3-10]]

^<<v3-3-10,10>>^ os dois rins e a gordura que está sobre eles, e a que está junto aos lombos, e o redenho que está sobre o fígado, juntamente com os rins, tirá-los-á.

[[v3-3-11]]

^<<v3-3-11,11>>^ E o sacerdote queimará isso sobre o altar; é o alimento da oferta queimada ao Senhor.

[[v3-3-12]]

^<<v3-3-12,12>>^ E se a sua oferta for uma cabra, perante o Senhor a oferecerá;

[[v3-3-13]]

^<<v3-3-13,13>>^ e lhe porá a mão sobre a cabeça, e a imolará diante da tenda da revelação; e os filhos de Arão espargirão o sangue da cabra sobre o altar em redor.

[[v3-3-14]]

^<<v3-3-14,14>>^ Depois oferecerá dela a sua oferta, isto é, uma oferta queimada ao Senhor; a gordura que cobre a fressura, sim, toda a gordura que está sobre ela,

[[v3-3-15]]

^<<v3-3-15,15>>^ os dois rins e a gordura que está sobre eles, e a que está junto aos lombos, e o redenho que está sobre o fígado, juntamente com os rins, tirá-los-á.

[[v3-3-16]]

^<<v3-3-16,16>>^ E o sacerdote queimará isso sobre o altar; é o alimento da oferta queimada, de cheiro suave. Toda a gordura pertencerá ao Senhor.

[[v3-3-17]]

^<<v3-3-17,17>>^ Estatuto perpétuo, pelas vossas gerações, em todas as vossas habitações, será isto: nenhuma gordura nem sangue algum comereis.

'''

xref:003-levitico/003-levitico-002.adoc#v3-2-0[&#60; Capítulo Anterior] | <<v3-3-0,Topo>> | xref:003-levitico/003-levitico-004.adoc#v3-4-0[Próximo Capítulo &#62;]