include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-20-1]]

^<<v3-20-1,1>>^ Disse mais o Senhor a Moisés:

[[v3-20-2]]

^<<v3-20-2,2>>^ Também dirás aos filhos de Israel: Qualquer dos filhos de Israel, ou dos estrangeiros peregrinos em Israel, que der de seus filhos a Moloque, certamente será morto; o povo da terra o apedrejará.

[[v3-20-3]]

^<<v3-20-3,3>>^ Eu porei o meu rosto contra esse homem, e o extirparei do meio do seu povo; porquanto eu de seus filhos a Moloque, assim contaminando o meu santuário e profanando o meu santo nome.

[[v3-20-4]]

^<<v3-20-4,4>>^ E, se o povo da terra de alguma maneira esconder os olhos para não ver esse homem, quando der de seus filhos a Moloque, e não matar,

[[v3-20-5]]

^<<v3-20-5,5>>^ eu porei o meu rosto contra esse homem, e contra a sua família, e o extirparei do meio do seu povo, bem como a todos os que forem após ele, prostituindo-se após Moloque.

[[v3-20-6]]

^<<v3-20-6,6>>^ Quanto àquele que se voltar para os que consultam os mortos e para os feiticeiros, prostituindo-se após eles, porei o meu rosto contra aquele homem, e o extirparei do meio do seu povo.

[[v3-20-7]]

^<<v3-20-7,7>>^ Portanto santificai-vos, e sede santos, pois eu sou o Senhor vosso Deus.

[[v3-20-8]]

^<<v3-20-8,8>>^ Guardai os meus estatutos, e cumpri-os. Eu sou o Senhor, que vos santifico.

[[v3-20-9]]

^<<v3-20-9,9>>^ Qualquer que amaldiçoar a seu pai ou a sua mãe, certamente será morto; amaldiçoou a seu pai ou a sua mãe; o seu sangue será sobre ele.

[[v3-20-10]]

^<<v3-20-10,10>>^ O homem que adulterar com a mulher de outro, sim, aquele que adulterar com a mulher do seu próximo, certamente será morto, tanto o adúltero, como a adúltera.

[[v3-20-11]]

^<<v3-20-11,11>>^ O homem que se deitar com a mulher de seu pai terá descoberto a nudez de seu pai; ambos os adúlteros certamente serão mortos; o seu sangue será sobre eles.

[[v3-20-12]]

^<<v3-20-12,12>>^ Se um homem se deitar com a sua nora, ambos certamente serão mortos; cometeram uma confusão; o seu sangue será sobre eles.

[[v3-20-13]]

^<<v3-20-13,13>>^ Se um homem se deitar com outro homem, como se fosse com mulher, ambos terão praticado abominação; certamente serão mortos; o seu sangue será sobre eles.

[[v3-20-14]]

^<<v3-20-14,14>>^ Se um homem tomar uma mulher e a mãe dela, é maldade; serão queimados no fogo, tanto ele quanto elas, para que não haja maldade no meio de vós.

[[v3-20-15]]

^<<v3-20-15,15>>^ Se um homem se ajuntar com um animal, certamente será morto; também matareis o animal.

[[v3-20-16]]

^<<v3-20-16,16>>^ Se uma mulher se chegar a algum animal, para ajuntar-se com ele, matarás a mulher e bem assim o animal; certamente serão mortos; o seu sangue será sobre eles:

[[v3-20-17]]

^<<v3-20-17,17>>^ Se um homem tomar a sua irmã, por parte de pai, ou por parte de mãe, e vir a nudez dela, e ela a dele, é torpeza; portanto serão extirpados aos olhos dos filhos do seu povo; terá descoberto a nudez de sua irmã; levará sobre si a sua iniqüidade.

[[v3-20-18]]

^<<v3-20-18,18>>^ Se um homem se deitar com uma mulher no tempo da enfermidade dela, e lhe descobrir a nudez, descobrindo-lhe também a fonte, e ela descobrir a fonte do seu sangue, ambos serão extirpados do meio do seu povo.

[[v3-20-19]]

^<<v3-20-19,19>>^ Não descobrirás a nudez da irmã de tua mãe, ou da irmã de teu pai, porquanto isso será descobrir a sua parenta chegada; levarão sobre si a sua iniqüidade.

[[v3-20-20]]

^<<v3-20-20,20>>^ Se um homem se deitar com a sua tia, terá descoberto a nudez de seu tio; levarão sobre si o seu pecado; sem filhos morrerão.

[[v3-20-21]]

^<<v3-20-21,21>>^ Se um homem tomar a mulher de seu irmão, é imundícia; terá descoberto a nudez de seu irmão; sem filhos ficarão.

[[v3-20-22]]

^<<v3-20-22,22>>^ Guardareis, pois, todos os meus estatutos e todos os meus preceitos, e os cumprireis; a fim de que a terra, para a qual eu vos levo, para nela morardes, não vos vomite.

[[v3-20-23]]

^<<v3-20-23,23>>^ E não andareis nos costumes dos povos que eu expulso de diante de vós; porque eles fizeram todas estas coisas, e eu os abominei.

[[v3-20-24]]

^<<v3-20-24,24>>^ Mas a vós vos tenho dito: Herdareis a sua terra, e eu vo-la darei para a possuirdes, terra que mana leite e mel. Eu sou o Senhor vosso Deus, que vos separei dos povos.

[[v3-20-25]]

^<<v3-20-25,25>>^ Fareis, pois, diferença entre os animais limpos e os imundos, e entre as aves imundas e as limpas; e não fareis abomináveis as vossas almas por causa de animais, ou de aves, ou de qualquer coisa de tudo de que está cheia a terra, as quais coisas apartei de vós como imundas.

[[v3-20-26]]

^<<v3-20-26,26>>^ E sereis para mim santos; porque eu, o Senhor, sou santo, e vos separei dos povos, para serdes meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ O homem ou mulher que consultar os mortos ou for feiticeiro, certamente será morto. Serão apedrejados, e o seu sangue será sobre eles.

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]