include::./index.adoc[]

[[v3-13-0]]
=== Levítico, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-13-1]]

^<<v3-13-1,1>>^ Falou mais o Senhor a Moisés e a Arão, dizendo:

[[v3-13-2]]

^<<v3-13-2,2>>^ Quando um homem tiver na pele da sua carne inchação, ou pústula, ou mancha lustrosa, e esta se tornar na sua pele como praga de lepra, então será levado a Arão o sacerdote, ou a um de seus filhos, os sacerdotes,

[[v3-13-3]]

^<<v3-13-3,3>>^ e o sacerdote examinará a praga na pele da carne. Se o pêlo na praga se tiver tornado branco, e a praga parecer mais profunda que a pele, é praga de lepra; o sacerdote, verificando isto, o declarará imundo.

[[v3-13-4]]

^<<v3-13-4,4>>^ Mas, se a mancha lustrosa na sua pele for branca, e não parecer mais profunda que a pele, e o pêlo não se tiver tornado branco, o sacerdote encerrará por sete dias aquele que tem a praga.

[[v3-13-5]]

^<<v3-13-5,5>>^ Ao sétimo dia o sacerdote o examinará; se a praga, na sua opinião, tiver parado e não se tiver estendido na pele, o sacerdote o encerrará por outros sete dias.

[[v3-13-6]]

^<<v3-13-6,6>>^ Ao sétimo dia o sacerdote o examinará outra vez; se a praga tiver escurecido, não se tendo estendido na pele, o sacerdote o declarará limpo; é uma pústula. O homem lavará as suas vestes, e será limpo.

[[v3-13-7]]

^<<v3-13-7,7>>^ Mas se a pústula se estender muito na pele, depois de se ter mostrado ao sacerdote para a sua purificação, mostrar-se-á de novo ao sacerdote,

[[v3-13-8]]

^<<v3-13-8,8>>^ o qual o examinará; se a pústula se tiver estendido na pele, o sacerdote o declarará imundo; é lepra.

[[v3-13-9]]

^<<v3-13-9,9>>^ Quando num homem houver praga de lepra, será ele levado ao sacerdote,

[[v3-13-10]]

^<<v3-13-10,10>>^ o qual o examinará; se houver na pele inchação branca que tenha tornado branco o pêlo, e houver carne viva na inchação,

[[v3-13-11]]

^<<v3-13-11,11>>^ lepra inveterada é na sua pele. Portanto, o sacerdote o declarará imundo; não o encerrará, porque imundo é.

[[v3-13-12]]

^<<v3-13-12,12>>^ Se a lepra se espalhar muito na pele, e cobrir toda a pele do que tem a praga, desde a cabeça até os pés, quanto podem ver os olhos do sacerdote,

[[v3-13-13]]

^<<v3-13-13,13>>^ este o examinará; e, se a lepra tiver coberto a carne toda, declarará limpo o que tem a praga; ela toda se tornou branca; o homem é limpo.

[[v3-13-14]]

^<<v3-13-14,14>>^ Mas no dia em que nele aparecer carne viva será imundo.

[[v3-13-15]]

^<<v3-13-15,15>>^ Examinará, pois, o sacerdote a carne viva, e declarará o homem imundo; a carne viva é imunda; é lepra.

[[v3-13-16]]

^<<v3-13-16,16>>^ Ou, se a carne viva mudar, e ficar de novo branca, ele virá ao sacerdote,

[[v3-13-17]]

^<<v3-13-17,17>>^ e este o examinará; se a praga se tiver tornado branca, o sacerdote declarará limpo o que tem a praga; limpo está.

[[v3-13-18]]

^<<v3-13-18,18>>^ Quando também a carne tiver na sua pele alguma úlcera, se esta sarar,

[[v3-13-19]]

^<<v3-13-19,19>>^ e em seu lugar vier inchação branca ou mancha lustrosa, tirando a vermelho, mostrar-se-á ao sacerdote,

[[v3-13-20]]

^<<v3-13-20,20>>^ e este a examinará; se ela parecer mais profunda que a pele, e o pêlo se tiver tornado branco, o sacerdote declarará imundo o homem; é praga de lepra, que brotou na úlcera.

[[v3-13-21]]

^<<v3-13-21,21>>^ Se, porém, o sacerdote a examinar, e nela não houver pêlo branco e não estiver mais profunda que a pele, mas tiver escurecido, o sacerdote encerrará por sete dias o homem.

[[v3-13-22]]

^<<v3-13-22,22>>^ Se ela se estender na pele, o sacerdote o declarará imundo; é praga.

[[v3-13-23]]

^<<v3-13-23,23>>^ Mas se a mancha lustrosa parar no seu lugar, não se estendendo, é a cicatriz da úlcera; o sacerdote, pois, o declarará limpo.

[[v3-13-24]]

^<<v3-13-24,24>>^ Ou, quando na pele da carne houver queimadura de fogo, e a carne viva da queimadura se tornar em mancha lustrosa, tirando a vermelho ou branco,

[[v3-13-25]]

^<<v3-13-25,25>>^ o sacerdote a examinará, e se o pêlo na mancha lustrosa se tiver tornado branco, e ela parecer mais profunda que a pele, é lepra; brotou na queimadura; portanto o sacerdote o declarará imundo; é praga de lepra.

[[v3-13-26]]

^<<v3-13-26,26>>^ Mas se o sacerdote a examinar, e na mancha lustrosa não houver pêlo branco, nem estiver mais profunda que a pele, mas tiver escurecido, o sacerdote o encerrará por sete dias.

[[v3-13-27]]

^<<v3-13-27,27>>^ Ao sétimo dia o sacerdote o examinará. Se ela se houver estendido na pele, o sacerdote o declarará imundo; é praga de lepra.

[[v3-13-28]]

^<<v3-13-28,28>>^ Mas se a mancha lustrosa tiver parado no seu lugar, não se estendendo na pele, e tiver escurecido, é a inchação da queimadura; portanto o sacerdote o declarará limpo; porque é a cicatriz da queimadura.

[[v3-13-29]]

^<<v3-13-29,29>>^ E quando homem &#123;ou mulher&#125; tiver praga na cabeça ou na barba,

[[v3-13-30]]

^<<v3-13-30,30>>^ o sacerdote examinará a praga, e se ela parecer mais profunda que a pele, e nela houver pêlo fino amarelo, o sacerdote o declarará imundo; é tinha, é lepra da cabeça ou da barba.

[[v3-13-31]]

^<<v3-13-31,31>>^ Mas se o sacerdote examinar a praga da tinha, e ela não parecer mais profunda que a pele, e nela não houver pêlo preto, o sacerdote encerrará por sete dias o que tem a praga da tinha.

[[v3-13-32]]

^<<v3-13-32,32>>^ Ao sétimo dia o sacerdote examinará a praga; se a tinha não se tiver estendido, e nela não houver pêlo amarelo, nem a tinha parecer mais profunda que a pele,

[[v3-13-33]]

^<<v3-13-33,33>>^ o homem se rapará, mas não rapará a tinha; e o sacerdote encerrará por mais sete dias o que tem a tinha.

[[v3-13-34]]

^<<v3-13-34,34>>^ Ao sétimo dia o sacerdote examinará a tinha; se ela não se houver estendido na pele, e não parecer mais profunda que a pele, o sacerdote declarará limpo o homem; o qual lavará as suas vestes, e será limpo.

[[v3-13-35]]

^<<v3-13-35,35>>^ Mas se, depois da sua purificação, a tinha estender na pele,

[[v3-13-36]]

^<<v3-13-36,36>>^ o sacerdote o examinará; se a tinha se tiver estendido na pele, o sacerdote não buscará pêlo amarelo; o homem está imundo.

[[v3-13-37]]

^<<v3-13-37,37>>^ Mas se a tinha, a seu ver, tiver parado, e nela tiver crescido pêlo preto, a tinha terá sarado; limpo está o homem; portanto o sacerdote o declarará limpo.

[[v3-13-38]]

^<<v3-13-38,38>>^ Quando homem &#123;ou mulher&#125; tiver na pele da sua carne manchas lustrosas, isto é, manchas lustrosas brancas,

[[v3-13-39]]

^<<v3-13-39,39>>^ o sacerdote as examinará; se essas manchas lustrosas forem brancas tirando a escuro, é impigem que brotou na pele; o homem é limpo.

[[v3-13-40]]

^<<v3-13-40,40>>^ Quando a cabeça do homem se pelar, ele é calvo; contudo é limpo.

[[v3-13-41]]

^<<v3-13-41,41>>^ E, se a frente da sua cabeça se pelar, ele é meio calvo; contudo é limpo.

[[v3-13-42]]

^<<v3-13-42,42>>^ Mas se na calva, ou na meia calva, houver praga branca tirando a vermelho, é lepra que lhe está brotando na calva ou na meia calva.

[[v3-13-43]]

^<<v3-13-43,43>>^ Então o sacerdote o examinará, e se a inchação da praga na calva ou na meia calva for branca tirando a vermelho, como parece a lepra na pele da carne,

[[v3-13-44]]

^<<v3-13-44,44>>^ leproso é aquele homem, é imundo; o sacerdote certamente o declarará imundo; na sua cabeça está a praga.

[[v3-13-45]]

^<<v3-13-45,45>>^ Também as vestes do leproso, em quem está a praga, serão rasgadas; ele ficará com a cabeça descoberta e de cabelo solto, mas cobrirá o bigode, e clamará: Imundo, imundo.

[[v3-13-46]]

^<<v3-13-46,46>>^ Por todos os dias em que a praga estiver nele, será imundo; imundo é; habitará só; a sua habitação será fora do arraial.

[[v3-13-47]]

^<<v3-13-47,47>>^ Quando também houver praga de lepra em alguma vestidura, seja em vestidura de lã ou em vestidura de linho,

[[v3-13-48]]

^<<v3-13-48,48>>^ quer na urdidura, quer na trama, seja de linho ou seja de lã; ou em pele, ou em qualquer obra de pele;

[[v3-13-49]]

^<<v3-13-49,49>>^ se a praga na vestidura, quer na urdidura, quer na trama, ou na pele, ou em qualquer coisa de pele, for verde ou vermelha, é praga de lepra, pelo que se mostrará ao sacerdote;

[[v3-13-50]]

^<<v3-13-50,50>>^ o sacerdote examinará a praga, e encerrará por sete dias aquilo que tem a praga.

[[v3-13-51]]

^<<v3-13-51,51>>^ Ao sétimo dia examinará a praga; se ela se houver estendido na vestidura, quer na urdidura, quer na trama, ou na pele, seja qual for a obra em que se empregue, a praga é lepra roedora; é imunda.

[[v3-13-52]]

^<<v3-13-52,52>>^ Pelo que se queimará aquela vestidura, seja a urdidura ou a trama, seja de lã ou de linho, ou qualquer obra de pele, em que houver a praga, porque é lepra roedora; queimar-se-á ao fogo.

[[v3-13-53]]

^<<v3-13-53,53>>^ Mas se o sacerdote a examinar, e ela não se tiver estendido na vestidura, seja na urdidura, seja na trama, ou em qualquer obra de pele,

[[v3-13-54]]

^<<v3-13-54,54>>^ o sacerdote ordenará que se lave aquilo, em que está a praga, e o encerrará por mais sete dias.

[[v3-13-55]]

^<<v3-13-55,55>>^ O sacerdote examinará a praga, depois de lavada, e se ela não tiver mudado de cor, nem se tiver estendido, é imunda; no fogo a queimarás; é praga penetrante, seja por dentro, seja por fora.

[[v3-13-56]]

^<<v3-13-56,56>>^ Mas se o sacerdote a examinar, e a praga tiver escurecido, depois de lavada, então a rasgará da vestidura, ou da pele, ou da urdidura, ou da trama;

[[v3-13-57]]

^<<v3-13-57,57>>^ se ela ainda aparecer na vestidura, seja na urdidura, seja na trama, ou em qualquer coisa de pele, é lepra brotante; no fogo queimarás aquilo em que há a praga.

[[v3-13-58]]

^<<v3-13-58,58>>^ Mas a vestidura, quer a urdidura, quer a trama, ou qualquer coisa de pele, que lavares, e de que a praga se retirar, se lavará segunda vez, e será limpa.

[[v3-13-59]]

^<<v3-13-59,59>>^ Esta é a lei da praga da lepra na vestidura de lã, ou de linho, quer na urdidura, quer na rama, ou em qualquer coisa de pele, para declará-la limpa, ou para declará-la imunda.

'''

xref:003-levitico/003-levitico-012.adoc#v3-12-0[&#60; Capítulo Anterior] | <<v3-13-0,Topo>> | xref:003-levitico/003-levitico-014.adoc#v3-14-0[Próximo Capítulo &#62;]