include::./index.adoc[]

[[v3-22-0]]
=== Levítico, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-22-1]]

^<<v3-22-1,1>>^ Depois disse o Senhor a Moisés:

[[v3-22-2]]

^<<v3-22-2,2>>^ Dize a Arão e a seus filhos que se abstenham das coisas sagradas dos filhos de Israel, as quais eles a mim me santificam, e que não profanem o meu santo nome. Eu sou o Senhor.

[[v3-22-3]]

^<<v3-22-3,3>>^ Dize-lhes: Todo homem dentre os vossos descendentes pelas vossas gerações que, tendo sobre si a sua imundícia, se chegar às coisas sagradas que os filhos de Israel santificam ao Senhor, aquela alma será extirpada da minha presença. Eu sou o Senhor.

[[v3-22-4]]

^<<v3-22-4,4>>^ Ninguém dentre os descendentes de Arão que for leproso, ou tiver fluxo, comerá das coisas sagradas, até que seja limpo. Também o que tocar em alguma coisa tornada imunda por causa e um morto, ou aquele de quem sair o sêmen

[[v3-22-5]]

^<<v3-22-5,5>>^ ou qualquer que tocar em algum animal que se arrasta, pelo qual se torne imundo, ou em algum homem, pelo qual se torne imundo, seja qual for a sua imundícia,

[[v3-22-6]]

^<<v3-22-6,6>>^ o homem que tocar em tais coisas será imundo até a tarde, e não comerá das coisas sagradas, mas banhará o seu corpo em água

[[v3-22-7]]

^<<v3-22-7,7>>^ e, posto o sol, então será limpo; depois comerá das coisas sagradas, porque isso é o seu pão.

[[v3-22-8]]

^<<v3-22-8,8>>^ Do animal que morrer por si, ou do que for dilacerado por feras, não comerá o homem, para que não se contamine com ele. Eu sou o Senhor.

[[v3-22-9]]

^<<v3-22-9,9>>^ Guardarão, pois, o meu mandamento, para que, havendo-o profanado, não levem pecado sobre si e morram nele. Eu sou o Senhor que os santifico.

[[v3-22-10]]

^<<v3-22-10,10>>^ Também nenhum estranho comerá das coisas sagradas; nem o hóspede do sacerdote, nem o jornaleiro, comerá delas.

[[v3-22-11]]

^<<v3-22-11,11>>^ Mas aquele que o sacerdote tiver comprado com o seu dinheiro, e o nascido na sua casa, esses comerão do seu pão.

[[v3-22-12]]

^<<v3-22-12,12>>^ Se a filha de um sacerdote se casar com um estranho, ela não comerá da oferta alçada das coisas sagradas.

[[v3-22-13]]

^<<v3-22-13,13>>^ Mas quando a filha do sacerdote for viúva ou repudiada, e não tiver filhos, e houver tornado para a casa de seu pai, como na sua mocidade, do pão de seu pai comerá; mas nenhum estranho comerá dele.

[[v3-22-14]]

^<<v3-22-14,14>>^ Se alguém por engano comer a coisa sagrada, repô-la-á, acrescida da quinta parte, e a dará ao sacerdote como a coisa sagrada.

[[v3-22-15]]

^<<v3-22-15,15>>^ Assim não profanarão as coisas sagradas dos filhos de Israel, que eles oferecem ao Senhor,

[[v3-22-16]]

^<<v3-22-16,16>>^ nem os farão levar sobre si a iniqüidade que envolve culpa, comendo as suas coisas sagradas; pois eu sou o Senhor que as santifico.

[[v3-22-17]]

^<<v3-22-17,17>>^ Disse mais o Senhor a Moisés:

[[v3-22-18]]

^<<v3-22-18,18>>^ Fala a Arão, e a seus filhos, e a todos os filhos de Israel, e dize-lhes: Todo homem da casa de Israel, ou dos estrangeiros em Israel, que oferecer a sua oferta, seja dos seus votos, seja das suas ofertas voluntárias que oferecerem ao Senhor em holocausto,

[[v3-22-19]]

^<<v3-22-19,19>>^ para que sejais aceitos, oferecereis macho sem defeito, ou dos novilhos, ou dos cordeiros, ou das cabras.

[[v3-22-20]]

^<<v3-22-20,20>>^ Nenhuma coisa, porém, que tiver defeito oferecereis, porque não será aceita a vosso favor.

[[v3-22-21]]

^<<v3-22-21,21>>^ E, quando alguém oferecer sacrifício de oferta pacífica ao Senhor para cumprir um voto, ou para oferta voluntária, seja do gado vacum, seja do gado miúdo, o animal será perfeito, para que seja aceito; nenhum defeito haverá nele.

[[v3-22-22]]

^<<v3-22-22,22>>^ O cego, ou quebrado, ou aleijado, ou que tiver úlceras, ou sarna, ou impigens, estes não oferecereis ao Senhor, nem deles poreis oferta queimada ao Senhor sobre o altar.

[[v3-22-23]]

^<<v3-22-23,23>>^ Todavia, um novilho, ou um cordeiro, que tenha algum membro comprido ou curto demais, poderás oferecer por oferta voluntária, mas para cumprir voto não será aceito.

[[v3-22-24]]

^<<v3-22-24,24>>^ Não oferecereis ao Senhor um animal que tiver testículo machucado, ou moído, ou arrancado, ou lacerado; não fareis isso na vossa terra.

[[v3-22-25]]

^<<v3-22-25,25>>^ Nem da mão do estrangeiro oferecereis de alguma dessas coisas o pão do vosso Deus; porque a sua corrupção nelas está; há defeito nelas; não serão aceitas a vosso favor.

[[v3-22-26]]

^<<v3-22-26,26>>^ Disse mais o Senhor a Moisés:

[[v3-22-27]]

^<<v3-22-27,27>>^ Quando nascer um novilho, ou uma ovelha, ou uma cabra, por sete dias ficará debaixo de sua mãe; depois, desde o dia oitavo em diante, será aceito por oferta queimada ao Senhor.

[[v3-22-28]]

^<<v3-22-28,28>>^ Também, seja vaca ou seja ovelha, não a imolareis a ela e à sua cria, ambas no mesmo dia.

[[v3-22-29]]

^<<v3-22-29,29>>^ E, quando oferecerdes ao Senhor sacrifício de ação de graças, oferecê-lo-eis de modo a serdes aceitos.

[[v3-22-30]]

^<<v3-22-30,30>>^ No mesmo dia se comerá; nada deixareis ficar dele até pela manhã. Eu sou o Senhor.

[[v3-22-31]]

^<<v3-22-31,31>>^ Guardareis os meus mandamentos, e os cumprireis. Eu sou o Senhor.

[[v3-22-32]]

^<<v3-22-32,32>>^ Não profanareis o meu santo nome, e serei santificado no meio dos filhos de Israel. Eu sou o Senhor que vos santifico,

[[v3-22-33]]

^<<v3-22-33,33>>^ que vos tirei da terra do Egito para ser o vosso Deus. Eu sou o Senhor.

'''

xref:003-levitico/003-levitico-021.adoc#v3-21-0[&#60; Capítulo Anterior] | <<v3-22-0,Topo>> | xref:003-levitico/003-levitico-023.adoc#v3-23-0[Próximo Capítulo &#62;]