include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-25-1]]

^<<v3-25-1,1>>^ Disse mais o Senhor a Moisés no monte Sinai:

[[v3-25-2]]

^<<v3-25-2,2>>^ Fala aos filhos de Israel e dize-lhes: Quando tiverdes entrado na terra que eu vos dou, a terra guardará um sábado ao Senhor.

[[v3-25-3]]

^<<v3-25-3,3>>^ Seis anos semearás a tua terra, e seis anos podarás a tua vinha, e colherás os seus frutos;

[[v3-25-4]]

^<<v3-25-4,4>>^ mas no sétimo ano haverá sábado de descanso solene para a terra, um sábado ao Senhor; não semearás o teu campo, nem podarás a tua vinha.

[[v3-25-5]]

^<<v3-25-5,5>>^ O que nascer de si mesmo da tua sega não segarás, e as uvas da tua vide não tratada não vindimarás; ano de descanso solene será para a terra.

[[v3-25-6]]

^<<v3-25-6,6>>^ Mas os frutos do sábado da terra vos serão por alimento, a ti, e ao teu servo, e à tua serva, e ao teu jornaleiro, e ao estrangeiro que peregrina contigo,

[[v3-25-7]]

^<<v3-25-7,7>>^ e ao teu gado, e aos animais que estão na tua terra; todo o seu produto será por mantimento.

[[v3-25-8]]

^<<v3-25-8,8>>^ Também contarás sete sábados de anos, sete vezes sete anos; de maneira que os dias dos sete sábados de anos serão quarenta e nove anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Então, no décimo dia do sétimo mês, farás soar fortemente a trombeta; no dia da expiação fareis soar a trombeta por toda a vossa terra.

[[v3-25-10]]

^<<v3-25-10,10>>^ E santificareis o ano qüinquagésimo, e apregoareis liberdade na terra a todos os seus habitantes; ano de jubileu será para vós; pois tornareis, cada um à sua possessão, e cada um à sua família.

[[v3-25-11]]

^<<v3-25-11,11>>^ Esse ano qüinquagésimo será para vós jubileu; não semeareis, nem segareis o que nele nascer de si mesmo, nem nele vindimareis as uvas das vides não tratadas.

[[v3-25-12]]

^<<v3-25-12,12>>^ Porque é jubileu; santo será para vós; diretamente do campo comereis o seu produto.

[[v3-25-13]]

^<<v3-25-13,13>>^ Nesse ano do jubileu tornareis, cada um à sua possessão.

[[v3-25-14]]

^<<v3-25-14,14>>^ Se venderdes alguma coisa ao vosso próximo ou a comprardes da mão do vosso próximo, não vos defraudareis uns aos outros.

[[v3-25-15]]

^<<v3-25-15,15>>^ Conforme o número de anos desde o jubileu é que comprarás ao teu próximo, e conforme o número de anos das colheitas é que ele te venderá.

[[v3-25-16]]

^<<v3-25-16,16>>^ Quanto mais forem os anos, tanto mais aumentarás o preço, e quanto menos forem os anos, tanto mais abaixarás o preço; porque é o número das colheitas que ele te vende.

[[v3-25-17]]

^<<v3-25-17,17>>^ Nenhum de vós oprimirá ao seu próximo; mas temerás o teu Deus; porque eu sou o Senhor vosso Deus.

[[v3-25-18]]

^<<v3-25-18,18>>^ Pelo que observareis os meus estatutos, e guardareis os meus preceitos e os cumprireis; assim habitareis seguros na terra.

[[v3-25-19]]

^<<v3-25-19,19>>^ Ela dará o seu fruto, e comereis a fartar; e nela habitareis seguros.

[[v3-25-20]]

^<<v3-25-20,20>>^ Se disserdes: Que comeremos no sétimo ano, visto que não haveremos de semear, nem fazer a nossa colheita?

[[v3-25-21]]

^<<v3-25-21,21>>^ então eu mandarei a minha bênção sobre vós no sexto ano, e a terra produzirá fruto bastante para os três anos.

[[v3-25-22]]

^<<v3-25-22,22>>^ No oitavo ano semeareis, e comereis da colheita velha; até o ano nono, até que venha a colheita nova, comereis da velha.

[[v3-25-23]]

^<<v3-25-23,23>>^ Também não se venderá a terra em perpetuidade, porque a terra é minha; pois vós estais comigo como estrangeiros e peregrinos:

[[v3-25-24]]

^<<v3-25-24,24>>^ Portanto em toda a terra da vossa possessão concedereis que seja remida a terra.

[[v3-25-25]]

^<<v3-25-25,25>>^ Se teu irmão empobrecer e vender uma parte da sua possessão, virá o seu parente mais chegado e remirá o que seu irmão vendeu.

[[v3-25-26]]

^<<v3-25-26,26>>^ E se alguém não tiver remidor, mas ele mesmo tiver enriquecido e achado o que basta para o seu resgate,

[[v3-25-27]]

^<<v3-25-27,27>>^ contará os anos desde a sua venda, e o que ficar do preço da venda restituirá ao homem a quem a vendeu, e tornará à sua possessão.

[[v3-25-28]]

^<<v3-25-28,28>>^ Mas, se as suas posses não bastarem para reavê-la, aquilo que tiver vendido ficará na mão do comprador até o ano do jubileu; porém no ano do jubileu sairá da posse deste, e aquele que vendeu tornará à sua possessão.

[[v3-25-29]]

^<<v3-25-29,29>>^ Se alguém vender uma casa de moradia em cidade murada, poderá remi-la dentro de um ano inteiro depois da sua venda; durante um ano inteiro terá o direito de a remir.

[[v3-25-30]]

^<<v3-25-30,30>>^ Mas se, passado um ano inteiro, não tiver sido resgatada, essa casa que está na cidade murada ficará, em perpetuidade, pertencendo ao que a comprou, e à sua descendência; não sairá o seu poder no jubileu.

[[v3-25-31]]

^<<v3-25-31,31>>^ Todavia as casas das aldeias que não têm muro ao redor serão consideradas como o campo da terra; poderão ser remidas, e sairão do poder do comprador no jubileu.

[[v3-25-32]]

^<<v3-25-32,32>>^ Também, no tocante às cidades dos levitas, às casas das cidades da sua possessão, terão eles direito perpétuo de remi-las.

[[v3-25-33]]

^<<v3-25-33,33>>^ E se alguém comprar dos levitas uma casa, a casa comprada e a cidade da sua possessão sairão do poder do comprador no jubileu; porque as casas das cidades dos levitas são a sua possessão no meio dos filhos de Israel.

[[v3-25-34]]

^<<v3-25-34,34>>^ Mas o campo do arrabalde das suas cidades não se poderá vender, porque lhes é possessão perpétua.

[[v3-25-35]]

^<<v3-25-35,35>>^ Também, se teu irmão empobrecer ao teu lado, e lhe enfraquecerem as mãos, sustentá-lo-ás; como estrangeiro e peregrino viverá contigo.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não tomarás dele juros nem ganho, mas temerás o teu Deus, para que teu irmão viva contigo.

[[v3-25-37]]

^<<v3-25-37,37>>^ Não lhe darás teu dinheiro a juros, nem os teus víveres por lucro.

[[v3-25-38]]

^<<v3-25-38,38>>^ Eu sou o Senhor vosso Deus, que vos tirei da terra do Egito, para vos dar a terra de Canaã, para ser o vosso Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ Também, se teu irmão empobrecer ao teu lado e vender-se a ti, não o farás servir como escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Como jornaleiro, como peregrino estará ele contigo; até o ano do jubileu te servirá;

[[v3-25-41]]

^<<v3-25-41,41>>^ então sairá do teu serviço, e com ele seus filhos, e tornará à sua família, à possessão de seus pais.

[[v3-25-42]]

^<<v3-25-42,42>>^ Porque são meus servos, que tirei da terra do Egito; não serão vendidos como escravos.

[[v3-25-43]]

^<<v3-25-43,43>>^ Não dominarás sobre ele com rigor, mas temerás o teu Deus.

[[v3-25-44]]

^<<v3-25-44,44>>^ E quanto aos escravos ou às escravas que chegares a possuir, das nações que estiverem ao redor de vós, delas é que os comprareis.

[[v3-25-45]]

^<<v3-25-45,45>>^ Também os comprareis dentre os filhos dos estrangeiros que peregrinarem entre vós, tanto dentre esses como dentre as suas famílias que estiverem convosco, que tiverem eles gerado na vossa terra; e vos serão por possessão.

[[v3-25-46]]

^<<v3-25-46,46>>^ E deixá-los-eis por herança aos vossos filhos depois de vós, para os herdarem como possessão; desses tomareis os vossos escravos para sempre; mas sobre vossos irmãos, os filhos de Israel, não dominareis com rigor, uns sobre os outros.

[[v3-25-47]]

^<<v3-25-47,47>>^ Se um estrangeiro ou peregrino que estiver contigo se tornar rico, e teu irmão, que está com ele, empobrecer e vender-se ao estrangeiro ou peregrino que está contigo, ou à linhagem da família do estrangeiro,

[[v3-25-48]]

^<<v3-25-48,48>>^ depois que se houver vendido, poderá ser remido; um de seus irmãos o poderá remir;

[[v3-25-49]]

^<<v3-25-49,49>>^ ou seu tio, ou o filho de seu tio, ou qualquer parente chegado da sua família poderá remi-lo; ou, se ele se tiver tornado rico, poderá remir-se a si mesmo.

[[v3-25-50]]

^<<v3-25-50,50>>^ E com aquele que o comprou fará a conta desde o ano em que se vendeu a ele até o ano do jubileu; e o preço da sua venda será conforme o número dos anos; conforme os dias de um jornaleiro estará com ele.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se ainda faltarem muitos anos, conforme os mesmos restituirá, do dinheiro pelo qual foi comprado, o preço da sua redenção;

[[v3-25-52]]

^<<v3-25-52,52>>^ e se faltarem poucos anos até o ano do jubileu, fará a conta com ele; segundo o número dos anos restituirá o preço da sua redenção.

[[v3-25-53]]

^<<v3-25-53,53>>^ Como servo contratado de ano em ano, estará com o comprador; o qual não dominará sobre ele com rigor diante dos teus olhos.

[[v3-25-54]]

^<<v3-25-54,54>>^ E, se não for remido por nenhum desses meios, sairá livre no ano do jubileu, e com ele seus filhos.

[[v3-25-55]]

^<<v3-25-55,55>>^ Porque os filhos de Israel são meus servos; eles são os meus servos que tirei da terra do Egito. Eu sou o Senhor vosso Deus.

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]