include::./index.adoc[]

[[v3-10-0]]
=== Levítico, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-10-1]]

^<<v3-10-1,1>>^ Ora, Nadabe, e Abiú, filhos de Arão, tomaram cada um o seu incensário e, pondo neles fogo e sobre ele deitando incenso, ofereceram fogo estranho perante o Senhor, o que ele não lhes ordenara.

[[v3-10-2]]

^<<v3-10-2,2>>^ Então saiu fogo de diante do Senhor, e os devorou; e morreram perante o Senhor.

[[v3-10-3]]

^<<v3-10-3,3>>^ Disse Moisés a Arão: Isto é o que o Senhor falou, dizendo: Serei santificado naqueles que se chegarem a mim, e serei glorificado diante de todo o povo. Mas Arão guardou silêncio.

[[v3-10-4]]

^<<v3-10-4,4>>^ E Moisés chamou a Misael e a Elzafã, filhos de Uziel, tio de Arão, e disse-lhes: Chegai-vos, levai vossos irmãos de diante do santuário, para fora do arraial.

[[v3-10-5]]

^<<v3-10-5,5>>^ Chegaram-se, pois, e levaram-nos como estavam, nas próprias túnicas, para fora do arraial, como Moisés lhes dissera.

[[v3-10-6]]

^<<v3-10-6,6>>^ Então disse Moisés a Arão, e a seus filhos Eleazar e Itamar: Não descubrais as vossas cabeças, nem rasgueis as vossas vestes, para que não morrais, nem venha a ira sobre toda a congregação; mas vossos irmãos, toda a casa de Israel, lamentem este incêndio que o Senhor acendeu.

[[v3-10-7]]

^<<v3-10-7,7>>^ E não saireis da porta da tenda da revelação, para que não morrais; porque está sobre vós o óleo da unção do Senhor. E eles fizeram conforme a palavra de Moisés.

[[v3-10-8]]

^<<v3-10-8,8>>^ Falou também o Senhor a Arão, dizendo:

[[v3-10-9]]

^<<v3-10-9,9>>^ Não bebereis vinho nem bebida forte, nem tu nem teus filhos contigo, quando entrardes na tenda da revelação, para que não morrais; estatuto perpétuo será isso pelas vossas gerações,

[[v3-10-10]]

^<<v3-10-10,10>>^ não somente para fazer separação entre o santo e o profano, e entre o imundo e o limpo,

[[v3-10-11]]

^<<v3-10-11,11>>^ mas também para ensinar aos filhos de Israel todos os estatutos que o Senhor lhes tem dado por intermédio de Moisés.

[[v3-10-12]]

^<<v3-10-12,12>>^ Também disse Moisés a Arão, e a Eleazar e Itamar, seus filhos que lhe ficaram: Tomai a oferta de cereais que resta das ofertas queimadas do Senhor, e comei-a sem levedura junto do altar, porquanto é coisa santíssima.

[[v3-10-13]]

^<<v3-10-13,13>>^ Comê-la-eis em lugar santo, porque isto é a tua porção, e a porção de teus filhos, das ofertas queimadas do Senhor; porque assim me foi ordenado.

[[v3-10-14]]

^<<v3-10-14,14>>^ Também o peito da oferta movida e a coxa da oferta alçada, comê-los-eis em lugar limpo, tu, e teus filhos e tuas filhas contigo; porquanto são eles dados como tua porção, e como porção de teus filhos, dos sacrifícios das ofertas pacíficas dos filhos de Israel.

[[v3-10-15]]

^<<v3-10-15,15>>^ Trarão a coxa da oferta alçada e o peito da oferta movida juntamente com as ofertas queimadas da gordura, para movê-los como oferta movida perante o Senhor; isso te pertencerá como porção, a ti e a teus filhos contigo, para sempre, como o Senhor tem ordenado.

[[v3-10-16]]

^<<v3-10-16,16>>^ E Moisés buscou diligentemente o bode da oferta pelo pecado, e eis que já tinha sido queimado; pelo que se indignou grandemente contra Eleazar e contra Itamar, os filhos que de Arão ficaram, e lhes disse:

[[v3-10-17]]

^<<v3-10-17,17>>^ Por que não comestes a oferta pelo pecado em lugar santo, visto que é coisa santíssima, e o Senhor a deu a vós para levardes a iniqüidade da congregação, para fazerdes expiação por eles diante do Senhor?

[[v3-10-18]]

^<<v3-10-18,18>>^ Eis que não se trouxe o seu sangue para dentro do santuário; certamente a devíeis ter comido em lugar santo, como eu havia ordenado.

[[v3-10-19]]

^<<v3-10-19,19>>^ Então disse Arão a Moisés: Eis que hoje ofereceram a sua oferta pelo pecado e o seu holocausto perante o Senhor, e tais coisas como essas me têm acontecido; se eu tivesse comido hoje a oferta pelo pecado, porventura teria sido isso coisa agradável aos olhos do Senhor?

[[v3-10-20]]

^<<v3-10-20,20>>^ Ouvindo Moisés isto, pareceu-lhe razoável.

'''

xref:003-levitico/003-levitico-009.adoc#v3-9-0[&#60; Capítulo Anterior] | <<v3-10-0,Topo>> | xref:003-levitico/003-levitico-011.adoc#v3-11-0[Próximo Capítulo &#62;]