include::./index.adoc[]

[[v3-27-0]]
=== Levítico, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-27-1]]

^<<v3-27-1,1>>^ Disse mais o Senhor a Moisés:

[[v3-27-2]]

^<<v3-27-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Quando alguém fizer ao Senhor um voto especial que envolve pessoas, o voto será cumprido segundo a tua avaliação das pessoas.

[[v3-27-3]]

^<<v3-27-3,3>>^ Se for de um homem, desde a idade de vinte até sessenta anos, a tua avaliação será de cinqüenta siclos de prata, segundo o siclo do santuário.

[[v3-27-4]]

^<<v3-27-4,4>>^ Se for mulher, a tua avaliação será de trinta siclos.

[[v3-27-5]]

^<<v3-27-5,5>>^ Se for de cinco anos até vinte, a tua avaliação do homem será de vinte siclos, e da mulher dez siclos.

[[v3-27-6]]

^<<v3-27-6,6>>^ Se for de um mês até cinco anos, a tua avaliação do homem será de cinco siclos de prata, e da mulher três siclos de prata.

[[v3-27-7]]

^<<v3-27-7,7>>^ Se for de sessenta anos para cima, a tua avaliação do homem será de quinze siclos, e da mulher dez siclos.

[[v3-27-8]]

^<<v3-27-8,8>>^ Mas, se for mais pobre do que a tua avaliação, será apresentado perante o sacerdote, que o avaliará conforme as posses daquele que tiver feito o voto.

[[v3-27-9]]

^<<v3-27-9,9>>^ Se for animal dos que se oferecem em oferta ao Senhor, tudo quanto der dele ao Senhor será santo.

[[v3-27-10]]

^<<v3-27-10,10>>^ Não o mudará, nem o trocará, bom por mau, ou mau por bom; mas se de qualquer maneira trocar animal por animal, tanto um como o outro será santo.

[[v3-27-11]]

^<<v3-27-11,11>>^ Se for algum animal imundo, dos que não se oferecem em oferta ao Senhor, apresentará o animal diante do sacerdote;

[[v3-27-12]]

^<<v3-27-12,12>>^ e o sacerdote o avaliará, seja bom ou seja mau; segundo tu, sacerdote, o avaliares, assim será.

[[v3-27-13]]

^<<v3-27-13,13>>^ Mas, se o homem, com efeito, quiser remi-lo, acrescentará a quinta parte sobre a tua avaliação.

[[v3-27-14]]

^<<v3-27-14,14>>^ Quando alguém santificar a sua casa para ser santa ao Senhor, o sacerdote a avaliará, seja boa ou seja má; como o sacerdote a avaliar, assim será.

[[v3-27-15]]

^<<v3-27-15,15>>^ Mas, se aquele que a tiver santificado quiser remir a sua casa, então acrescentará a quinta parte do dinheiro sobre a tua avaliação, e terá a casa.

[[v3-27-16]]

^<<v3-27-16,16>>^ Se alguém santificar ao Senhor uma parte do campo da sua possessão, então a tua avaliação será segundo a sua sementeira: um terreno que leva um hômer de semente de cevada será avaliado em cinqüenta siclos de prata.

[[v3-27-17]]

^<<v3-27-17,17>>^ Se ele santificar o seu campo a partir do ano do jubileu, conforme a tua avaliação ficará.

[[v3-27-18]]

^<<v3-27-18,18>>^ Mas se santificar o seu campo depois do ano do jubileu, o sacerdote lhe calculará o dinheiro conforme os anos que restam até o ano do jubileu, e assim será feita a tua avaliação.

[[v3-27-19]]

^<<v3-27-19,19>>^ Se aquele que tiver santificado o campo, com efeito, quiser remi-lo, acrescentará a quinta parte do dinheiro da tua avaliação, e lhe ficará assegurado o campo.

[[v3-27-20]]

^<<v3-27-20,20>>^ Se não o quiser remir, ou se houver vendido o campo a outrem, nunca mais poderá ser remido.

[[v3-27-21]]

^<<v3-27-21,21>>^ Mas o campo, quando sair livre no ano do jubileu, será santo ao Senhor, como campo consagrado; a possessão dele será do sacerdote.

[[v3-27-22]]

^<<v3-27-22,22>>^ Se alguém santificar ao Senhor um campo que tiver comprado, o qual não for parte do campo da sua possessão,

[[v3-27-23]]

^<<v3-27-23,23>>^ o sacerdote lhe contará o valor da tua avaliação até o ano do jubileu; e no mesmo dia dará a tua avaliação, como coisa santa ao Senhor.

[[v3-27-24]]

^<<v3-27-24,24>>^ No ano do jubileu o campo tornará àquele de quem tiver sido comprado, isto é, àquele a quem pertencer a possessão do campo.

[[v3-27-25]]

^<<v3-27-25,25>>^ Ora, toda tua avaliação se fará conforme o siclo do santuário; o siclo será de vinte jeiras.

[[v3-27-26]]

^<<v3-27-26,26>>^ Contudo o primogênito dum animal, que por ser primogênito já pertence ao senhor, ninguém o santificará; seja boi ou gado miúdo, pertence ao Senhor.

[[v3-27-27]]

^<<v3-27-27,27>>^ Mas se o primogênito for dum animal imundo, remir-se-á segundo a tua avaliação, e a esta se acrescentará a quinta parte; e se não for remido, será vendido segundo a tua avaliação.

[[v3-27-28]]

^<<v3-27-28,28>>^ Todavia, nenhuma coisa consagrada ao Senhor por alguém, daquilo que possui, seja homem, ou animal, ou campo da sua possessão, será vendida nem será remida; toda coisa consagrada será santíssima ao Senhor.

[[v3-27-29]]

^<<v3-27-29,29>>^ Nenhuma pessoa que dentre os homens for devotada será resgatada; certamente será morta.

[[v3-27-30]]

^<<v3-27-30,30>>^ Também todos os dízimos da terra, quer dos cereais, quer do fruto das árvores, pertencem ao senhor; santos são ao Senhor.

[[v3-27-31]]

^<<v3-27-31,31>>^ Se alguém quiser remir uma parte dos seus dízimos, acrescentar-lhe-á a quinta parte.

[[v3-27-32]]

^<<v3-27-32,32>>^ Quanto a todo dízimo do gado e do rebanho, de tudo o que passar debaixo da vara, esse dízimo será santo ao Senhor.

[[v3-27-33]]

^<<v3-27-33,33>>^ Não se examinará se é bom ou mau, nem se trocará; mas se, com efeito, se trocar, tanto um como o outro será santo; não serão remidos.

[[v3-27-34]]

^<<v3-27-34,34>>^ são esses os mandamentos que o Senhor ordenou a Moisés, para os filhos de Israel, no monte Sinai.

'''

xref:003-levitico/003-levitico-026.adoc#v3-26-0[&#60; Capítulo Anterior] | <<v3-27-0,Topo>> | xref:004-numeros/004-numeros-001.adoc#v4-1-0[Próximo Capítulo &#62;]