include::./index.adoc[]

[[v3-18-0]]
=== Levítico, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-18-1]]

^<<v3-18-1,1>>^ Disse mais o Senhor a Moisés:

[[v3-18-2]]

^<<v3-18-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Eu sou o Senhor vosso Deus.

[[v3-18-3]]

^<<v3-18-3,3>>^ Não fareis segundo as obras da terra do Egito, em que habitastes; nem fareis segundo as obras da terra de Canaã, para a qual eu vos levo; nem andareis segundo os seus estatutos.

[[v3-18-4]]

^<<v3-18-4,4>>^ Os meus preceitos observareis, e os meus estatutos guardareis, para andardes neles. Eu sou o Senhor vosso Deus.

[[v3-18-5]]

^<<v3-18-5,5>>^ Guardareis, pois, os meus estatutos e as minhas ordenanças, pelas quais o homem, observando-as, viverá. Eu sou o Senhor.

[[v3-18-6]]

^<<v3-18-6,6>>^ Nenhum de vós se chegará àquela que lhe é próxima por sangue, para descobrir a sua nudez. Eu sou o Senhor.

[[v3-18-7]]

^<<v3-18-7,7>>^ Não descobrirás a nudez de teu pai, nem tampouco a de tua mãe; ela é tua mãe, não descobrirás a sua nudez.

[[v3-18-8]]

^<<v3-18-8,8>>^ Não descobrirás a nudez da mulher de teu pai; é nudez de teu pai.

[[v3-18-9]]

^<<v3-18-9,9>>^ A nudez de tua irmã por parte de pai ou por parte de mãe, quer nascida em casa ou fora de casa, não a descobrirás.

[[v3-18-10]]

^<<v3-18-10,10>>^ Nem tampouco descobrirás a nudez da filha de teu filho, ou da filha de tua filha; porque é tua nudez.

[[v3-18-11]]

^<<v3-18-11,11>>^ A nudez da filha da mulher de teu pai, gerada de teu pai, a qual é tua irmã, não a descobrirás.

[[v3-18-12]]

^<<v3-18-12,12>>^ Não descobrirás a nudez da irmã de teu pai; ela é parenta chegada de teu pai.

[[v3-18-13]]

^<<v3-18-13,13>>^ Não descobrirás a nudez da irmã de tua mãe, pois ela é parenta chegada de tua mãe.

[[v3-18-14]]

^<<v3-18-14,14>>^ Não descobrirás a nudez do irmão de teu pai; não te chegarás à sua mulher; ela é tua tia.

[[v3-18-15]]

^<<v3-18-15,15>>^ Não descobrirás a nudez de tua nora; ,ela é mulher de teu filho; não descobrirás a sua nudez.

[[v3-18-16]]

^<<v3-18-16,16>>^ Não descobrirás a nudez da mulher de teu irmão; é a nudez de teu irmão.

[[v3-18-17]]

^<<v3-18-17,17>>^ Não descobrirás a nudez duma mulher e de sua filha. Não tomarás a filha de seu filho, nem a filha de sua filha, para descobrir a sua nudez; são parentas chegadas; é maldade.

[[v3-18-18]]

^<<v3-18-18,18>>^ E não tomarás uma mulher juntamente com sua irmã, durante a vida desta, para tornar-lha rival, descobrindo a sua nudez ao lado da outra.

[[v3-18-19]]

^<<v3-18-19,19>>^ Também não te chegarás a mulher enquanto for impura em virtude da sua imundícia, para lhe descobrir a nudez.

[[v3-18-20]]

^<<v3-18-20,20>>^ Nem te deitarás com a mulher de teu próximo, contaminando-te com ela.

[[v3-18-21]]

^<<v3-18-21,21>>^ Não oferecerás a Moloque nenhum dos teus filhos, fazendo-o passar pelo fogo; nem profanarás o nome de teu Deus. Eu sou o Senhor.

[[v3-18-22]]

^<<v3-18-22,22>>^ Não te deitarás com varão, como se fosse mulher; é abominação.

[[v3-18-23]]

^<<v3-18-23,23>>^ Nem te deitarás com animal algum, contaminando-te com ele; nem a mulher se porá perante um animal, para ajuntar-se com ele; é confusão.

[[v3-18-24]]

^<<v3-18-24,24>>^ Não vos contamineis com nenhuma dessas coisas, porque com todas elas se contaminaram as nações que eu expulso de diante de vós;

[[v3-18-25]]

^<<v3-18-25,25>>^ e, porquanto a terra está contaminada, eu visito sobre ela a sua iniqüidade, e a terra vomita os seus habitantes.

[[v3-18-26]]

^<<v3-18-26,26>>^ Vós, pois, guardareis os meus estatutos e os meus preceitos, e nenhuma dessas abominações fareis, nem o natural, nem o estrangeiro que peregrina entre vós

[[v3-18-27]]

^<<v3-18-27,27>>^ &#123;porque todas essas abominações cometeram os homens da terra, que nela estavam antes de vós, e a terra ficou contaminada&#125;;

[[v3-18-28]]

^<<v3-18-28,28>>^ para que a terra não seja contaminada por vós e não vos vomite também a vós, como vomitou a nação que nela estava antes de vós.

[[v3-18-29]]

^<<v3-18-29,29>>^ Pois qualquer que cometer alguma dessas abominações, sim, aqueles que as cometerem serão extirpados do seu povo.

[[v3-18-30]]

^<<v3-18-30,30>>^ Portanto guardareis o meu mandamento, de modo que não caiais em nenhum desses abomináveis costumes que antes de vós foram seguidos, e para que não vos contamineis com eles. Eu sou o Senhor vosso Deus.

'''

xref:003-levitico/003-levitico-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-levitico/003-levitico-019.adoc#v3-19-0[Próximo Capítulo &#62;]