include::./index.adoc[]

[[v3-12-0]]
=== Levítico, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-12-1]]

^<<v3-12-1,1>>^ Disse mais o Senhor a Moisés:

[[v3-12-2]]

^<<v3-12-2,2>>^ Fala aos filhos de Israel, dizendo: Se uma mulher conceber e tiver um menino, será imunda sete dias; assim como nos dias da impureza da sua enfermidade, será imunda.

[[v3-12-3]]

^<<v3-12-3,3>>^ E no dia oitavo se circuncidará ao menino a carne do seu prepúcio.

[[v3-12-4]]

^<<v3-12-4,4>>^ Depois permanecerá ela trinta e três dias no sangue da sua purificação; em nenhuma coisa sagrada tocará, nem entrará no santuário até que se cumpram os dias da sua purificação.

[[v3-12-5]]

^<<v3-12-5,5>>^ Mas, se tiver uma menina, então será imunda duas semanas, como na sua impureza; depois permanecerá sessenta e seis dias no sangue da sua purificação.

[[v3-12-6]]

^<<v3-12-6,6>>^ E, quando forem cumpridos os dias da sua purificação, seja por filho ou por filha, trará um cordeiro de um ano para holocausto, e um pombinho ou uma rola para oferta pelo pecado, à porta da tenda da revelação, o ao sacerdote,

[[v3-12-7]]

^<<v3-12-7,7>>^ o qual o oferecerá perante o Senhor, e fará, expiação por ela; então ela será limpa do fluxo do seu sangue. Esta é a lei da que der à luz menino ou menina.

[[v3-12-8]]

^<<v3-12-8,8>>^ Mas, se as suas posses não bastarem para um cordeiro, então tomará duas rolas, ou dois pombinhos: um para o holocausto e outro para a oferta pelo pecado; assim o sacerdote fará expiação por ela, e ela será limpa.

'''

xref:003-levitico/003-levitico-011.adoc#v3-11-0[&#60; Capítulo Anterior] | <<v3-12-0,Topo>> | xref:003-levitico/003-levitico-013.adoc#v3-13-0[Próximo Capítulo &#62;]