include::./index.adoc[]

[[v3-15-0]]
=== Levítico, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-15-1]]

^<<v3-15-1,1>>^ Disse ainda o Senhor a Moisés e a Arão:

[[v3-15-2]]

^<<v3-15-2,2>>^ Falai aos filhos de Israel, e dizei-lhes: Qualquer homem que tiver fluxo da sua carne, por causa do seu fluxo será imundo.

[[v3-15-3]]

^<<v3-15-3,3>>^ Esta, pois, será a sua imundícia por causa do seu fluxo: se a sua carne vasa o seu fluxo, ou se a sua carne estanca o seu fluxo, esta é a sua imundícia.

[[v3-15-4]]

^<<v3-15-4,4>>^ Toda cama em que se deitar aquele que tiver fluxo será imunda; e toda coisa sobre o que se sentar, será imunda.

[[v3-15-5]]

^<<v3-15-5,5>>^ E, qualquer que tocar na cama dele lavará as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-6]]

^<<v3-15-6,6>>^ E aquele que se sentar sobre aquilo em que se sentou o que tem o fluxo, lavará as suas vestes, e se banhará em água; e será imundo até a tarde,

[[v3-15-7]]

^<<v3-15-7,7>>^ Também aquele que tocar na carne do que tem o fluxo, lavará as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-8]]

^<<v3-15-8,8>>^ Quando o que tem o fluxo cuspir sobre um limpo, então lavará este as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-9]]

^<<v3-15-9,9>>^ Também toda sela, em que cavalgar o que tem o fluxo, será imunda.

[[v3-15-10]]

^<<v3-15-10,10>>^ E qualquer que tocar em alguma coisa que tiver estado debaixo dele será imundo até a tarde; e aquele que levar alguma dessas coisas, lavará as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-11]]

^<<v3-15-11,11>>^ Também todo aquele em quem tocar o que tiver o fluxo, sem haver antes lavado as mãos em água, lavará as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-12]]

^<<v3-15-12,12>>^ Todo vaso de barro em que tocar o que tiver o fluxo será quebrado; porém todo vaso de madeira será lavado em água.

[[v3-15-13]]

^<<v3-15-13,13>>^ Quando, pois, o que tiver o fluxo e ficar limpo do seu fluxo, contará para si sete dias para a sua purificação, lavará as suas vestes, banhará o seu corpo em águas vivas, e será limpo.

[[v3-15-14]]

^<<v3-15-14,14>>^ Ao oitavo dia tomará para si duas rolas, ou dois pombinhos, e virá perante o Senhor, à porta da tenda da revelação, e os dará ao sacerdote,

[[v3-15-15]]

^<<v3-15-15,15>>^ o qual os oferecerá, um para oferta pelo pecado, e o outro para holocausto; e assim o sacerdote fará por ele expiação perante o Senhor, por causa do seu fluxo.

[[v3-15-16]]

^<<v3-15-16,16>>^ Também se sair de um homem o seu sêmen banhará o seu corpo todo em água, e será imundo até a tarde.

[[v3-15-17]]

^<<v3-15-17,17>>^ E toda vestidura, e toda pele sobre que houver sêmen serão lavadas em água, e serão imundas até a tarde.

[[v3-15-18]]

^<<v3-15-18,18>>^ Igualmente quanto à mulher com quem o homem se deitar com sêmen ambos se banharão em água, e serão imundos até a tarde.

[[v3-15-19]]

^<<v3-15-19,19>>^ Mas a mulher, quando tiver fluxo, e o fluxo na sua carne for sangue, ficará na sua impureza por sete dias, e qualquer que nela tocar será imundo até a tarde.

[[v3-15-20]]

^<<v3-15-20,20>>^ E tudo aquilo sobre o que ela se deitar durante a sua impureza, será imundo; e tudo sobre o que se sentar, será imundo.

[[v3-15-21]]

^<<v3-15-21,21>>^ Também qualquer que tocar na sua cama, lavará as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-22]]

^<<v3-15-22,22>>^ E quem tocar em alguma coisa, sobre o que ela se tiver sentado, lavará as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-23]]

^<<v3-15-23,23>>^ Se o sangue estiver sobre a cama, ou sobre alguma coisa em que ela se sentar, quando alguém tocar nele, será imundo até a tarde.

[[v3-15-24]]

^<<v3-15-24,24>>^ E se, com efeito, qualquer homem se deitar com ela, e a sua imundícia ficar sobre ele, imundo será por sete dias; também toda cama, sobre que ele se deitar, será imunda.

[[v3-15-25]]

^<<v3-15-25,25>>^ Se uma mulher tiver um fluxo de sangue por muitos dias fora do tempo da sua impureza, ou quando tiver fluxo de sangue por mais tempo do que a sua impureza, por todos os dias do fluxo da sua imundícia será como nos dias da sua impureza; imunda será.

[[v3-15-26]]

^<<v3-15-26,26>>^ Toda cama sobre que ela se deitar durante todos os dias do seu fluxo ser-lhe-á como a cama da sua impureza; e toda coisa sobre que se sentar será imunda, conforme a imundícia da sua impureza.

[[v3-15-27]]

^<<v3-15-27,27>>^ E qualquer que tocar nessas coisas será imundo; portanto lavará as suas vestes, e se banhará em água, e será imundo até a tarde.

[[v3-15-28]]

^<<v3-15-28,28>>^ Quando ela ficar limpa do seu fluxo, contará para si sete dias, e depois será limpa.

[[v3-15-29]]

^<<v3-15-29,29>>^ Ao oitavo dia tomará para si duas rolas, ou dois pombinhos, e os trará ao sacerdote, à porta da tenda da revelação.

[[v3-15-30]]

^<<v3-15-30,30>>^ Então o sacerdote oferecerá um deles para oferta pelo pecado, e o outro para holocausto; e o sacerdote fará por ela expiação perante o Senhor, por causa do fluxo da sua imundícia.

[[v3-15-31]]

^<<v3-15-31,31>>^ Assim separareis os filhos de Israel da sua imundícia, para que não morram na sua imundícia, contaminando o meu tabernáculo, que está no meio deles.

[[v3-15-32]]

^<<v3-15-32,32>>^ Esta é a lei daquele que tem o fluxo e daquele de quem sai o sêmen de modo que por eles se torna imundo;

[[v3-15-33]]

^<<v3-15-33,33>>^ como também da mulher enferma com a sua impureza e daquele que tem o fluxo, tanto do homem como da mulher, e do homem que se deita com mulher imunda.

'''

xref:003-levitico/003-levitico-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-levitico/003-levitico-016.adoc#v3-16-0[Próximo Capítulo &#62;]