include::./index.adoc[]

[[v3-26-0]]
=== Levítico, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-26-1]]

^<<v3-26-1,1>>^ Não fareis para vós ídolos, nem para vós levantareis imagem esculpida, nem coluna, nem poreis na vossa terra pedra com figuras, para vos inclinardes a ela; porque eu sou o Senhor vosso Deus.

[[v3-26-2]]

^<<v3-26-2,2>>^ Guardareis os meus sábados, e reverenciareis o meu santuário. Eu sou o Senhor.

[[v3-26-3]]

^<<v3-26-3,3>>^ Se andardes nos meus estatutos, e guardardes os meus mandamentos e os cumprires,

[[v3-26-4]]

^<<v3-26-4,4>>^ eu vos darei as vossas chuvas a seu tempo, e a terra dará o seu produto, e as árvores do campo darão os seus frutos;

[[v3-26-5]]

^<<v3-26-5,5>>^ a debulha vos continuará até a vindima, e a vindima até a semeadura; comereis o vosso pão a fartar, e habitareis seguros na vossa terra.

[[v3-26-6]]

^<<v3-26-6,6>>^ Também darei paz na terra, e vos deitareis, e ninguém vos amedrontará. Farei desaparecer da terra os animais nocivos, e pela vossa terra não passará espada.

[[v3-26-7]]

^<<v3-26-7,7>>^ Perseguireis os vossos inimigos, e eles cairão à espada diante de vós.

[[v3-26-8]]

^<<v3-26-8,8>>^ Cinco de vós perseguirão a um cento deles, e cem de vós perseguirão a dez mil; e os vossos inimigos cairão à espada diante de vos.

[[v3-26-9]]

^<<v3-26-9,9>>^ Outrossim, olharei para vós, e vos farei frutificar, e vos multiplicarei, e confirmarei o meu pacto convosco.

[[v3-26-10]]

^<<v3-26-10,10>>^ E comereis da colheita velha por longo tempo guardada, até afinal a removerdes para dar lugar à nova.

[[v3-26-11]]

^<<v3-26-11,11>>^ Também porei o meu tabernáculo no meio de vós, e a minha alma não vos abominará.

[[v3-26-12]]

^<<v3-26-12,12>>^ Andarei no meio de vós, e serei o vosso Deus, e vós sereis o meu povo.

[[v3-26-13]]

^<<v3-26-13,13>>^ Eu sou o Senhor vosso Deus, que vos tirei da terra dos egípcios, para que não fôsseis seus escravos; e quebrei os canzis do vosso jugo, e vos fiz andar erguidos.

[[v3-26-14]]

^<<v3-26-14,14>>^ Mas, se não me ouvirdes, e não cumprirdes todos estes mandamentos,

[[v3-26-15]]

^<<v3-26-15,15>>^ e se rejeitardes os meus estatutos, e a vossa alma desprezar os meus preceitos, de modo que não cumprais todos os meus mandamentos, mas violeis o meu pacto,

[[v3-26-16]]

^<<v3-26-16,16>>^ então eu, com efeito, vos farei isto: porei sobre vós o terror, a tísica e a febre ardente, que consumirão os olhos e farão definhar a vida; em vão semeareis a vossa semente, pois os vossos inimigos a comerão.

[[v3-26-17]]

^<<v3-26-17,17>>^ Porei o meu rosto contra vós, e sereis feridos diante de vossos inimigos; os que vos odiarem dominarão sobre vós, e fugireis sem que ninguém vos persiga.

[[v3-26-18]]

^<<v3-26-18,18>>^ Se nem ainda com isto me ouvirdes, prosseguirei em castigar-vos sete vezes mais, por causa dos vossos pecados.

[[v3-26-19]]

^<<v3-26-19,19>>^ Pois quebrarei a soberba do vosso poder, e vos farei o céu como ferro e a terra como bronze.

[[v3-26-20]]

^<<v3-26-20,20>>^ Em vão se gastará a vossa força, porquanto a vossa terra não dará o seu produto, nem as árvores da terra darão os seus frutos.

[[v3-26-21]]

^<<v3-26-21,21>>^ Ora, se andardes contrariamente para comigo, e não me quiseres ouvir, trarei sobre vos pragas sete vezes mais, conforme os vossos pecados.

[[v3-26-22]]

^<<v3-26-22,22>>^ Enviarei para o meio de vós as feras do campo, as quais vos desfilharão, e destruirão o vosso gado, e vos reduzirão a pequeno número; e os vossos caminhos se tornarão desertos.

[[v3-26-23]]

^<<v3-26-23,23>>^ Se nem ainda com isto quiserdes voltar a mim, mas continuardes a andar contrariamente para comigo,

[[v3-26-24]]

^<<v3-26-24,24>>^ eu também andarei contrariamente para convosco; e eu, eu mesmo, vos ferirei sete vezes mais, por causa dos vossos pecados.

[[v3-26-25]]

^<<v3-26-25,25>>^ Trarei sobre vós a espada, que executará a vingança do pacto, e vos aglomerareis nas vossas cidades; então enviarei a peste entre vós, e sereis entregues na mão do inimigo.

[[v3-26-26]]

^<<v3-26-26,26>>^ Quando eu vos quebrar o sustento do pão, dez mulheres cozerão o vosso pão num só forno, e de novo vo-lo entregarão por peso; e comereis, mas não vos fartareis.

[[v3-26-27]]

^<<v3-26-27,27>>^ Se nem ainda com isto me ouvirdes, mas continuardes a andar contrariamente para comigo,

[[v3-26-28]]

^<<v3-26-28,28>>^ também eu andarei contrariamente para convosco com furor; e vos castigarei sete vezes mais, por causa dos vossos pecados.

[[v3-26-29]]

^<<v3-26-29,29>>^ E comereis a carne de vossos filhos e a carne de vossas filhas.

[[v3-26-30]]

^<<v3-26-30,30>>^ Destruirei os vossos altos, derrubarei as vossas imagens do sol, e lançarei os vossos cadáveres sobre os destroços dos vossos ídolos; e a minha alma vos abominará.

[[v3-26-31]]

^<<v3-26-31,31>>^ Reduzirei as vossas cidades a deserto, e assolarei os vossos santuários, e não cheirarei o vosso cheiro suave.

[[v3-26-32]]

^<<v3-26-32,32>>^ Assolarei a terra, e sobre ela pasmarão os vossos inimigos que nela habitam.

[[v3-26-33]]

^<<v3-26-33,33>>^ Espalhar-vos-ei por entre as nações e, desembainhando a espada, vos perseguirei; a vossa terra será assolada, e as vossas cidades se tornarão em deserto.

[[v3-26-34]]

^<<v3-26-34,34>>^ Então a terra folgará nos seus sábados, todos os dias da sua assolação, e vós estareis na terra dos vossos inimigos; nesse tempo a terra descansará, e folgará nos seus sábados.

[[v3-26-35]]

^<<v3-26-35,35>>^ Por todos os dias da assolação descansará, pelos dias que não descansou nos vossos sábados, quando nela habitáveis.

[[v3-26-36]]

^<<v3-26-36,36>>^ E, quanto aos que de vós ficarem, eu lhes meterei pavor no coração nas terras dos seus inimigos; e o ruído de uma folha agitada os porá em fuga; fugirão como quem foge da espada, e cairão sem que ninguém os persiga;

[[v3-26-37]]

^<<v3-26-37,37>>^ sim, embora não haja quem os persiga, tropeçarão uns sobre os outros como diante da espada; e não podereis resistir aos vossos inimigos.

[[v3-26-38]]

^<<v3-26-38,38>>^ Assim perecereis entre as nações, e a terra dos vossos inimigos vos devorará;

[[v3-26-39]]

^<<v3-26-39,39>>^ e os que de vós ficarem definharão pela sua iniqüidade nas terras dos vossos inimigos, como também pela iniqüidade de seus pais.

[[v3-26-40]]

^<<v3-26-40,40>>^ Então confessarão a sua iniqüidade, e a iniqüidade de seus pais, com as suas transgressões, com que transgrediram contra mim; igualmente confessarão que, por terem andado contrariamente para comigo,

[[v3-26-41]]

^<<v3-26-41,41>>^ eu também andei contrariamente para com eles, e os trouxe para a terra dos seus inimigos. Se então o seu coração incircunciso se humilhar, e tomarem por bem o castigo da sua iniqüidade,

[[v3-26-42]]

^<<v3-26-42,42>>^ eu me lembrarei do meu pacto com Jacó, do meu pacto com Isaque, e do meu pacto com Abraão; e bem assim da terra me lembrarei.

[[v3-26-43]]

^<<v3-26-43,43>>^ A terra também será deixada por eles e folgará nos seus sábados, sendo assolada por causa deles; e eles tomarão por bem o castigo da sua iniqüidade, em razão mesmo de que rejeitaram os meus preceitos e a sua alma desprezou os meus estatutos.

[[v3-26-44]]

^<<v3-26-44,44>>^ Todavia, ainda assim, quando eles estiverem na terra dos seus inimigos, não os rejeitarei nem os abominarei a ponto de consumi-los totalmente e quebrar o meu pacto com eles; porque eu sou o Senhor seu Deus.

[[v3-26-45]]

^<<v3-26-45,45>>^ Antes por amor deles me lembrarei do pacto com os seus antepassados, que tirei da terra do Egito perante os olhos das nações, para ser o seu Deus. Eu sou o Senhor.

[[v3-26-46]]

^<<v3-26-46,46>>^ São esses os estatutos, os preceitos e as leis que o Senhor firmou entre si e os filhos de Israel, no monte Sinai, por intermédio de Moisés.

'''

xref:003-levitico/003-levitico-025.adoc#v3-25-0[&#60; Capítulo Anterior] | <<v3-26-0,Topo>> | xref:003-levitico/003-levitico-027.adoc#v3-27-0[Próximo Capítulo &#62;]