include::./index.adoc[]

[[v3-9-0]]
=== Levítico, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-9-1]]

^<<v3-9-1,1>>^ Ora, ao dia oitavo, Moisés chamou a Arão e seus filhos, e os anciãos de Israel,

[[v3-9-2]]

^<<v3-9-2,2>>^ e disse a Arão: Toma um bezerro tenro para oferta pelo pecado, e um carneiro para holocausto, ambos sem defeito, e oferece-os perante o Senhor.

[[v3-9-3]]

^<<v3-9-3,3>>^ E falarás aos filhos de Israel, dizendo: Tomai um bode para oferta pelo pecado; e um bezerro e um cordeiro, ambos de um ano, e sem defeito, como holocausto;

[[v3-9-4]]

^<<v3-9-4,4>>^ também um boi e um carneiro para ofertas pacíficas, para sacrificar perante o Senhor e oferta de cereais, amassada com azeite; porquanto hoje o Senhor vos aparecerá.

[[v3-9-5]]

^<<v3-9-5,5>>^ Então trouxeram até a entrada da tenda da revelação o que Moisés ordenara, e chegou-se toda a congregação, e ficou de pé diante do Senhor.

[[v3-9-6]]

^<<v3-9-6,6>>^ E disse Moisés: Esta é a coisa que o Senhor ordenou que fizésseis; e a glória do Senhor vos aparecerá.

[[v3-9-7]]

^<<v3-9-7,7>>^ Depois disse Moisés a Arão: Chega-te ao altar, e apresenta a tua oferta pelo pecado e o teu holocausto, e faze expiação por ti e pelo povo; também apresenta a oferta do povo, e faze expiação por ele, como ordenou o Senhor.

[[v3-9-8]]

^<<v3-9-8,8>>^ Arão, pois, chegou-se ao altar, e imolou o bezerro que era a sua própria oferta pelo pecado.

[[v3-9-9]]

^<<v3-9-9,9>>^ Os filhos de Arão trouxeram-lhe o sangue; e ele molhou o dedo no sangue, e o pôs sobre as pontas do altar, e derramou o sangue à base do altar;

[[v3-9-10]]

^<<v3-9-10,10>>^ mas a gordura, e os rins, e o redenho do fígado, tirados da oferta pelo pecado, queimou-os sobre o altar, como o Senhor ordenara a Moisés.

[[v3-9-11]]

^<<v3-9-11,11>>^ E queimou ao fogo fora do arraial a carne e o couro.

[[v3-9-12]]

^<<v3-9-12,12>>^ Depois imolou o holocausto, e os filhos de Arão lhe entregaram o sangue, e ele o espargiu sobre o altar em redor.

[[v3-9-13]]

^<<v3-9-13,13>>^ Também lhe entregaram o holocausto, pedaço por pedaço, e a cabeça; e ele os queimou sobre o altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ E lavou a fressura e as pernas, e as queimou sobre o holocausto no altar.

[[v3-9-15]]

^<<v3-9-15,15>>^ Então apresentou a oferta do povo e, tomando o bode que era a oferta pelo pecado do povo, imolou-o e o ofereceu pelo pecado, como fizera com o primeiro.

[[v3-9-16]]

^<<v3-9-16,16>>^ Apresentou também o holocausto, e o ofereceu segundo a ordenança.

[[v3-9-17]]

^<<v3-9-17,17>>^ E apresentou a oferta de cereais e, tomando dela um punhado, queimou-o sobre o altar, além do holocausto da manhã.

[[v3-9-18]]

^<<v3-9-18,18>>^ Imolou também o boi e o carneiro em sacrifício de oferta pacífica pelo povo; e os filhos de Arão entregaram-lhe o sangue, que ele espargiu sobre o altar em redor,

[[v3-9-19]]

^<<v3-9-19,19>>^ como também a gordura do boi e do carneiro, a cauda gorda, e o que cobre a fressura, e os rins, e o redenho do fígado;

[[v3-9-20]]

^<<v3-9-20,20>>^ e puseram a gordura sobre os peitos, e ele queimou a gordura sobre o altar;

[[v3-9-21]]

^<<v3-9-21,21>>^ mas os peitos e a coxa direita, ofereceu-os Arão por oferta movida perante o Senhor, como Moisés tinha ordenado.

[[v3-9-22]]

^<<v3-9-22,22>>^ Depois Arão, levantando as mãos para o povo, o abençoou e desceu, tendo acabado de oferecer a oferta pelo pecado, o holocausto e as ofertas pacíficas.

[[v3-9-23]]

^<<v3-9-23,23>>^ E Moisés e Arão entraram na tenda da revelação; depois saíram, e abençoaram o povo; e a glória do Senhor apareceu a todo o povo,

[[v3-9-24]]

^<<v3-9-24,24>>^ pois saiu fogo de diante do Senhor, e consumiu o holocausto e a gordura sobre o altar; o que vendo todo o povo, jubilaram e prostraram-se sobre os seus rostos.

'''

xref:003-levitico/003-levitico-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-levitico/003-levitico-010.adoc#v3-10-0[Próximo Capítulo &#62;]