include::./index.adoc[]

[[v3-4-0]]
=== Levítico, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-4-1]]

^<<v3-4-1,1>>^ Disse mais o Senhor a Moisés:

[[v3-4-2]]

^<<v3-4-2,2>>^ Fala aos filhos de Israel, dizendo: Se alguém pecar por ignorância no tocante a qualquer das coisas que o Senhor ordenou que não se fizessem, fazendo qualquer delas;

[[v3-4-3]]

^<<v3-4-3,3>>^ se for o sacerdote ungido que pecar, assim tornando o povo culpado, oferecerá ao Senhor, pelo pecado que cometeu, um novilho sem defeito como oferta pelo pecado.

[[v3-4-4]]

^<<v3-4-4,4>>^ Trará o novilho à porta da tenda da revelação, perante o Senhor; porá a mão sobre a cabeça do novilho e o imolará perante o Senhor.

[[v3-4-5]]

^<<v3-4-5,5>>^ Então o sacerdote ungido tomará do sangue do novilho, e o trará à tenda da revelação;

[[v3-4-6]]

^<<v3-4-6,6>>^ e, molhando o dedo no sangue, espargirá do sangue sete vezes perante o Senhor, diante do véu do santuário.

[[v3-4-7]]

^<<v3-4-7,7>>^ Também o sacerdote porá daquele sangue perante o Senhor, sobre as pontas do altar do incenso aromático, que está na tenda da revelação; e todo o resto do sangue do novilho derramará à base do altar do holocausto, que está à porta da tenda da revelação.

[[v3-4-8]]

^<<v3-4-8,8>>^ E tirará toda a gordura do novilho da oferta pelo pecado; a gordura que cobre a fressura, sim, toda a gordura que está sobre ela,

[[v3-4-9]]

^<<v3-4-9,9>>^ os dois rins e a gordura que está sobre eles, e a que está junto aos lombos, e o redenho que está sobre o fígado, juntamente com os rins, tirá-los-á,

[[v3-4-10]]

^<<v3-4-10,10>>^ assim como se tira do boi do sacrifício pacífico; e o sacerdote os queimará sobre o altar do holocausto.

[[v3-4-11]]

^<<v3-4-11,11>>^ Mas o couro do novilho, e toda a sua carne, com a cabeça, as pernas, a fressura e o excremento,

[[v3-4-12]]

^<<v3-4-12,12>>^ enfim, o novilho todo, levá-lo-á para fora do arraial a um lugar limpo, em que se lança a cinza, e o queimará sobre a lenha; onde se lança a cinza, aí se queimará.

[[v3-4-13]]

^<<v3-4-13,13>>^ Se toda a congregação de Israel errar, sendo isso oculto aos olhos da assembléia, e eles tiverem feito qualquer de todas as coisas que o Senhor ordenou que não se fizessem, assim tornando-se culpados;

[[v3-4-14]]

^<<v3-4-14,14>>^ quando o pecado que cometeram for conhecido, a assembléia oferecerá um novilho como oferta pelo pecado, e o trará diante da tenda da revelação.

[[v3-4-15]]

^<<v3-4-15,15>>^ Os anciãos da congregação porão as mãos sobre a cabeça do novilho perante o Senhor; e imolar-se-á o novilho perante o Senhor.

[[v3-4-16]]

^<<v3-4-16,16>>^ Então o sacerdote ungido trará do sangue do novilho à tenda da revelação;

[[v3-4-17]]

^<<v3-4-17,17>>^ e o sacerdote molhará o dedo no sangue, e o espargirá sete vezes perante o Senhor, diante do véu.

[[v3-4-18]]

^<<v3-4-18,18>>^ E do sangue porá sobre as pontas do altar, que está perante o Senhor, na tenda da revelação; e todo o resto do sangue derramará à base do altar do holocausto, que está diante da tenda da revelação.

[[v3-4-19]]

^<<v3-4-19,19>>^ E tirará dele toda a sua gordura, e queimá-la-á sobre o altar.

[[v3-4-20]]

^<<v3-4-20,20>>^ Assim fará com o novilho; como fez ao novilho da oferta pelo pecado, assim fará a este; e o sacerdote fará expiação por eles, e eles serão perdoados.

[[v3-4-21]]

^<<v3-4-21,21>>^ Depois levará o novilho para fora do arraial, e o queimará como queimou o primeiro novilho; é oferta pelo pecado da assembléia.

[[v3-4-22]]

^<<v3-4-22,22>>^ Quando um príncipe pecar, fazendo por ignorância qualquer das coisas que o Senhor seu Deus ordenou que não se fizessem, e assim se tornar culpado;

[[v3-4-23]]

^<<v3-4-23,23>>^ se o pecado que cometeu lhe for notificado, então trará por sua oferta um bode, sem defeito;

[[v3-4-24]]

^<<v3-4-24,24>>^ porá a mão sobre a cabeça do bode e o imolará no lugar em que se imola o holocausto, perante o Senhor; é oferta pelo pecado.

[[v3-4-25]]

^<<v3-4-25,25>>^ Depois o sacerdote, com o dedo, tomará do sangue da oferta pelo pecado e pô-lo-á sobre as pontas do altar do holocausto; então o resto do sangue derramará à base do altar do holocausto.

[[v3-4-26]]

^<<v3-4-26,26>>^ Também queimará sobre o altar toda a sua gordura como a gordura do sacrifício da oferta pacífica; assim o sacerdote fará por ele expiação do seu pecado, e ele será perdoado.

[[v3-4-27]]

^<<v3-4-27,27>>^ E se alguém dentre a plebe pecar por ignorância, fazendo qualquer das coisas que o Senhor ordenou que não se fizessem, e assim se tornar culpado;

[[v3-4-28]]

^<<v3-4-28,28>>^ se o pecado que cometeu lhe for notificado, então trará por sua oferta uma cabra, sem defeito, pelo pecado cometido;

[[v3-4-29]]

^<<v3-4-29,29>>^ porá a mão sobre a cabeça da oferta pelo pecado, e a imolará no lugar do holocausto.

[[v3-4-30]]

^<<v3-4-30,30>>^ Depois o sacerdote, com o dedo, tomará do sangue da oferta, e o porá sobre as pontas do altar do holocausto; e todo o resto do sangue derramará à base do altar.

[[v3-4-31]]

^<<v3-4-31,31>>^ Tirará toda a gordura, como se tira a gordura do sacrifício pacífico, e a queimará sobre o altar, por cheiro suave ao Senhor; e o sacerdote fará expiação por ele, e ele será perdoado.

[[v3-4-32]]

^<<v3-4-32,32>>^ Ou, se pela sua oferta trouxer uma cordeira como oferta pelo pecado, sem defeito a trará;

[[v3-4-33]]

^<<v3-4-33,33>>^ porá a mão sobre a cabeça da oferta pelo pecado, e a imolará por oferta pelo pecado, no lugar em que se imola o holocausto.

[[v3-4-34]]

^<<v3-4-34,34>>^ Depois o sacerdote, com o dedo, tomará do sangue da oferta pelo pecado, e o porá sobre as pontas do altar do holocausto; então todo o resto do sangue da oferta derramará à base do altar.

[[v3-4-35]]

^<<v3-4-35,35>>^ Tirará toda a gordura, como se tira a gordura do cordeiro do sacrifício pacífico e a queimará sobre o altar, em cima das ofertas queimadas do Senhor; assim o sacerdote fará por ele expiação do pecado que cometeu, e ele será perdoado.

'''

xref:003-levitico/003-levitico-003.adoc#v3-3-0[&#60; Capítulo Anterior] | <<v3-4-0,Topo>> | xref:003-levitico/003-levitico-005.adoc#v3-5-0[Próximo Capítulo &#62;]