include::./index.adoc[]

[[v3-2-0]]
=== Levítico, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-2-1]]

^<<v3-2-1,1>>^ Quando alguém fizer ao Senhor uma oferta de cereais, a sua oferta será de flor de farinha; deitará nela azeite, e sobre ela porá incenso;

[[v3-2-2]]

^<<v3-2-2,2>>^ e a trará aos filhos de Arão, os sacerdotes, um dos quais lhe tomará um punhado da flor de farinha e do azeite com todo o incenso, e o queimará sobre o altar por oferta memorial, oferta queimada, de cheiro suave ao Senhor.

[[v3-2-3]]

^<<v3-2-3,3>>^ O que restar da oferta de cereais pertencerá a Arão e a seus filhos; é coisa santíssima entre as ofertas queimadas ao Senhor.

[[v3-2-4]]

^<<v3-2-4,4>>^ Quando fizerdes oferta de cereais assada ao forno, será de bolos ázimos de flor de farinha, amassados com azeite, e coscorões ázimos untados com azeite.

[[v3-2-5]]

^<<v3-2-5,5>>^ E se a tua oferta for oferta de cereais assada na assadeira, será de flor de farinha sem fermento, amassada com azeite.

[[v3-2-6]]

^<<v3-2-6,6>>^ Em pedaços a partirás, e sobre ela deitarás azeite; é oferta de cereais.

[[v3-2-7]]

^<<v3-2-7,7>>^ E se a tua oferta for oferta de cereais cozida na frigideira, far-se-á de flor de farinha com azeite.

[[v3-2-8]]

^<<v3-2-8,8>>^ Então trarás ao Senhor a oferta de cereais que for feita destas coisas; e será apresentada ao sacerdote, o qual a levará ao altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ E o sacerdote tomará da oferta de cereais o memorial dela, e o queimará sobre o altar; é oferta queimada, de cheiro suave ao Senhor.

[[v3-2-10]]

^<<v3-2-10,10>>^ E o que restar da oferta de cereais pertencerá a Arão e a seus filhos; é coisa santíssima entre as ofertas queimadas ao Senhor.

[[v3-2-11]]

^<<v3-2-11,11>>^ Nenhuma oferta de cereais, que fizerdes ao Senhor, será preparada com fermento; porque não queimareis fermento algum nem mel algum como oferta queimada ao Senhor.

[[v3-2-12]]

^<<v3-2-12,12>>^ Como oferta de primícias oferecê-los-eis ao Senhor; mas sobre o altar não subirão por cheiro suave.

[[v3-2-13]]

^<<v3-2-13,13>>^ Todas as suas ofertas de cereais temperarás com sal; não deixarás faltar a elas o sal do pacto do teu Deus; em todas as tuas ofertas oferecerás sal.

[[v3-2-14]]

^<<v3-2-14,14>>^ Se fizeres ao Senhor oferta de cereais de primícias, oferecerás, como oferta de cereais das tuas primícias, espigas tostadas ao fogo, isto é, o grão trilhado de espigas verdes.

[[v3-2-15]]

^<<v3-2-15,15>>^ Sobre ela deitarás azeite, e lhe porás por cima incenso; é oferta de cereais.

[[v3-2-16]]

^<<v3-2-16,16>>^ O sacerdote queimará o memorial dela, isto é, parte do grão trilhado e parte do azeite com todo o incenso; é oferta queimada ao Senhor.

'''

xref:003-levitico/003-levitico-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-levitico/003-levitico-003.adoc#v3-3-0[Próximo Capítulo &#62;]