include::./index.adoc[]

[[v3-17-0]]
=== Levítico, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-17-1]]

^<<v3-17-1,1>>^ Disse mais o Senhor a Moisés:

[[v3-17-2]]

^<<v3-17-2,2>>^ Fala a Arão e aos seus filhos, e a s todos os filhos de Israel, e dize-lhes: Isto é o que o Senhor tem ordenado:

[[v3-17-3]]

^<<v3-17-3,3>>^ Qualquer homem da casa de Israel que imolar boi, ou cordeiro, ou cabra, no arraial, ou fora do arraial,

[[v3-17-4]]

^<<v3-17-4,4>>^ e não o trouxer à porta da tenda da revelação, para o oferecer como oferta ao Senhor diante do tabernáculo do Senhor, a esse homem será imputado o sangue; derramou sangue, pelo que será extirpado do seu povo;

[[v3-17-5]]

^<<v3-17-5,5>>^ a fim de que os filhos de Israel tragam os seus sacrifícios, que oferecem no campo, isto é, a fim de que os tragam ao Senhor, à porta da tenda da revelação, ao sacerdote, e os ofereçam por sacrifícios de ofertas, pacíficas ao Senhor.

[[v3-17-6]]

^<<v3-17-6,6>>^ E o sacerdote espargirá o sangue sobre o altar do Senhor, à porta da tenda da revelação, e queimará a gordura por cheiro suave ao Senhor.

[[v3-17-7]]

^<<v3-17-7,7>>^ E nunca mais oferecerão os seus sacrifícios aos sátiros, após os quais eles se prostituem; isso lhes será por estatuto perpétuo pelas suas gerações.

[[v3-17-8]]

^<<v3-17-8,8>>^ Dir-lhes-ás pois: Qualquer homem da casa de Israel, ou dos estrangeiros que entre vós peregrinam, que oferecer holocausto ou sacrifício,

[[v3-17-9]]

^<<v3-17-9,9>>^ e não o trouxer à porta da tenda da revelação, para oferecê-lo ao Senhor, esse homem será extirpado do seu povo.

[[v3-17-10]]

^<<v3-17-10,10>>^ Também, qualquer homem da casa de Israel, ou dos estrangeiros que peregrinam entre eles, que comer algum sangue, contra aquela alma porei o meu rosto, e a extirparei do seu povo.

[[v3-17-11]]

^<<v3-17-11,11>>^ Porque a vida da carne está no sangue; pelo que vo-lo tenho dado sobre o altar, para fazer expiação pelas vossas almas; porquanto é o sangue que faz expiação, em virtude da vida.

[[v3-17-12]]

^<<v3-17-12,12>>^ Portanto tenho dito aos filhos de Israel: Nenhum de vós comerá sangue; nem o estrangeiro que peregrina entre vós comerá sangue.

[[v3-17-13]]

^<<v3-17-13,13>>^ Também, qualquer homem dos filhos de Israel, ou dos estrangeiros que peregrinam entre eles, que apanhar caça de fera ou de ave que se pode comer, derramará o sangue dela e o cobrirá com pó.

[[v3-17-14]]

^<<v3-17-14,14>>^ Pois, quanto à vida de toda a carne, o seu sangue é uma e a mesma coisa com a sua vida; por isso eu disse aos filhos de Israel: Não comereis o sangue de nenhuma carne, porque a vida de toda a carne é o seu sangue; qualquer que o comer será extirpado.

[[v3-17-15]]

^<<v3-17-15,15>>^ E todo homem, quer natural quer estrangeiro, que comer do que morre por si ou do que é dilacerado por feras, lavará as suas vestes, e se banhará em água, e será imundo até a tarde; depois será limpo.

[[v3-17-16]]

^<<v3-17-16,16>>^ Mas, se não as lavar, nem banhar o seu corpo, levará sobre si a sua iniquidade

'''

xref:003-levitico/003-levitico-016.adoc#v3-16-0[&#60; Capítulo Anterior] | <<v3-17-0,Topo>> | xref:003-levitico/003-levitico-018.adoc#v3-18-0[Próximo Capítulo &#62;]