include::./index.adoc[]

[[v3-21-0]]
=== Levítico, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-21-1]]

^<<v3-21-1,1>>^ Depois disse o senhor a Moisés: Fala aos sacerdotes, filhos de Arão, e dize-lhes: O sacerdote não se contaminará por causa dum morto entre o seu povo,

[[v3-21-2]]

^<<v3-21-2,2>>^ salvo por um seu parente mais chegado: por sua mãe ou por seu pai, por seu filho ou por sua filha, por seu irmão,

[[v3-21-3]]

^<<v3-21-3,3>>^ ou por sua irmã virgem, que lhe é chegada, que ainda não tem marido; por ela também pode contaminar-se.

[[v3-21-4]]

^<<v3-21-4,4>>^ O sacerdote, sendo homem principal entre o seu povo, não se profanará, assim contaminando-se.

[[v3-21-5]]

^<<v3-21-5,5>>^ Não farão os sacerdotes calva na cabeça, e não raparão os cantos da barba, nem farão lacerações na sua carne.

[[v3-21-6]]

^<<v3-21-6,6>>^ santos serão para seu Deus, e não profanarão o nome do seu Deus; porque oferecem as ofertas queimadas do senhor, que são o pão do seu Deus; portanto serão santos.

[[v3-21-7]]

^<<v3-21-7,7>>^ Não tomarão mulher prostituta ou desonrada, nem tomarão mulher repudiada de seu marido; pois o sacerdote é santo para seu Deus.

[[v3-21-8]]

^<<v3-21-8,8>>^ Portanto o santificarás; porquanto oferece o pão do teu Deus, santo te será; pois eu, o Senhor, que vos santifico, sou santo.

[[v3-21-9]]

^<<v3-21-9,9>>^ E se a filha dum sacerdote se profanar, tornando-se prostituta, profana a seu pai; no fogo será queimada.

[[v3-21-10]]

^<<v3-21-10,10>>^ Aquele que é sumo sacerdote entre seus irmãos, sobre cuja cabeça foi derramado o óleo da unção, e que foi consagrado para vestir as vestes sagradas, não descobrirá a cabeça nem rasgará a sua vestidura;

[[v3-21-11]]

^<<v3-21-11,11>>^ e não se chegará a cadáver algum; nem sequer por causa de seu pai ou de sua, mãe se contaminará;

[[v3-21-12]]

^<<v3-21-12,12>>^ não sairá do santuário, nem profanará o santuário do seu Deus; pois a coroa do óleo da unção do seu Deus está sobre ele. Eu sou o Senhor.

[[v3-21-13]]

^<<v3-21-13,13>>^ E ele tomará por esposa uma mulher na sua virgindade.

[[v3-21-14]]

^<<v3-21-14,14>>^ Viúva, ou repudiada, ou desonrada, ou prostituta, destas não tomará; mas virgem do seu povo tomará por mulher.

[[v3-21-15]]

^<<v3-21-15,15>>^ E não profanará a sua descendência entre o seu povo; porque eu sou o Senhor que o santifico.

[[v3-21-16]]

^<<v3-21-16,16>>^ Disse mais o Senhor a Moisés:

[[v3-21-17]]

^<<v3-21-17,17>>^ Fala a Arão, dizendo: Ninguém dentre os teus descendentes, por todas as suas gerações, que tiver defeito, se chegará para oferecer o pão do seu Deus.

[[v3-21-18]]

^<<v3-21-18,18>>^ Pois nenhum homem que tiver algum defeito se chegará: como homem cego, ou coxo, ou de nariz chato, ou de membros demasiadamente compridos,

[[v3-21-19]]

^<<v3-21-19,19>>^ ou homem que tiver o pé quebrado, ou a mão quebrada,

[[v3-21-20]]

^<<v3-21-20,20>>^ ou for corcunda, ou anão, ou que tiver belida, ou sarna, ou impigens, ou que tiver testículo lesado;

[[v3-21-21]]

^<<v3-21-21,21>>^ nenhum homem dentre os descendentes de Arão, o sacerdote, que tiver algum defeito, se chegará para oferecer as ofertas queimadas do Senhor; ele tem defeito; não se chegará para oferecer o pão do seu Deus.

[[v3-21-22]]

^<<v3-21-22,22>>^ Comerá do pão do seu Deus, tanto do santíssimo como do santo;

[[v3-21-23]]

^<<v3-21-23,23>>^ contudo, não entrará até o véu, nem se chegará ao altar, porquanto tem defeito; para que não profane os meus santuários; porque eu sou o Senhor que os santifico.

[[v3-21-24]]

^<<v3-21-24,24>>^ Moisés, pois, assim falou a Arão e a seus filhos, e a todos os filhos de Israel.

'''

xref:003-levitico/003-levitico-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-levitico/003-levitico-022.adoc#v3-22-0[Próximo Capítulo &#62;]