include::./index.adoc[]

[[v3-23-0]]
=== Levítico, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v3-23-1]]

^<<v3-23-1,1>>^ Depois disse o Senhor a Moisés:

[[v3-23-2]]

^<<v3-23-2,2>>^ Fala aos filhos de Israel, e dize-lhes: As festas fixas do Senhor, que proclamareis como santas convocações, são estas:

[[v3-23-3]]

^<<v3-23-3,3>>^ Seis dias se fará trabalho, mas o sétimo dia é o sábado do descanso solene, uma santa convocação; nenhum trabalho fareis; é sábado do Senhor em todas as vossas habitações.

[[v3-23-4]]

^<<v3-23-4,4>>^ São estas as festas fixas do Senhor, santas convocações, que proclamareis no seu tempo determinado:

[[v3-23-5]]

^<<v3-23-5,5>>^ No mês primeiro, aos catorze do mês, à tardinha, é a páscoa do Senhor.

[[v3-23-6]]

^<<v3-23-6,6>>^ E aos quinze dias desse mês é a festa dos pães ázimos do Senhor; sete dias comereis pães ázimos.

[[v3-23-7]]

^<<v3-23-7,7>>^ No primeiro dia tereis santa convocação; nenhum trabalho servil fareis.

[[v3-23-8]]

^<<v3-23-8,8>>^ Mas por sete dias oferecereis oferta queimada ao Senhor; ao sétimo dia haverá santa convocação; nenhum trabalho servil fareis.

[[v3-23-9]]

^<<v3-23-9,9>>^ Disse mais o Senhor a Moisés:

[[v3-23-10]]

^<<v3-23-10,10>>^ Fala aos filhos de Israel, e dize-lhes: Quando houverdes entrado na terra que eu vos dou, e segardes a sua sega, então trareis ao sacerdote um molho das primícias da vossa sega;

[[v3-23-11]]

^<<v3-23-11,11>>^ e ele moverá o molho perante o Senhor, para que sejais aceitos. No dia seguinte ao sábado o sacerdote o moverá.

[[v3-23-12]]

^<<v3-23-12,12>>^ E no dia em que moverdes o molho, oferecereis um cordeiro sem defeito, de um ano, em holocausto ao Senhor.

[[v3-23-13]]

^<<v3-23-13,13>>^ Sua oferta de cereais será dois décimos de efa de flor de farinha, amassada com azeite, para oferta queimada em cheiro suave ao Senhor; e a sua oferta de libação será de vinho, um quarto de him.

[[v3-23-14]]

^<<v3-23-14,14>>^ E não comereis pão, nem trigo torrado, nem espigas verdes, até aquele mesmo dia, em que trouxerdes a oferta do vosso Deus; é estatuto perpétuo pelas vossas gerações, em todas as vossas habitações.

[[v3-23-15]]

^<<v3-23-15,15>>^ Contareis para vós, desde o dia depois do sábado, isto é, desde o dia em que houverdes trazido o molho da oferta de movimento, sete semanas inteiras;

[[v3-23-16]]

^<<v3-23-16,16>>^ até o dia seguinte ao sétimo sábado, contareis cinqüenta dias; então oferecereis nova oferta de cereais ao Senhor.

[[v3-23-17]]

^<<v3-23-17,17>>^ Das vossas habitações trareis, para oferta de movimento, dois pães de dois décimos de efa; serão de flor de farinha, e levedados se cozerão; são primícias ao Senhor.

[[v3-23-18]]

^<<v3-23-18,18>>^ Com os pães oferecereis sete cordeiros sem defeito, de um ano, um novilho e dois carneiros; serão holocausto ao Senhor, com as respectivas ofertas de cereais e de libação, por oferta queimada de cheiro suave ao Senhor.

[[v3-23-19]]

^<<v3-23-19,19>>^ Também oferecereis um bode para oferta pelo pecado, e dois cordeiros de um ano para sacrifício de ofertas pacíficas.

[[v3-23-20]]

^<<v3-23-20,20>>^ Então o sacerdote os moverá, juntamente com os pães das primícias, por oferta de movimento perante o Senhor, com os dois cordeiros; santos serão ao Senhor para uso do sacerdote.

[[v3-23-21]]

^<<v3-23-21,21>>^ E fareis proclamação nesse mesmo dia, pois tereis santa convocação; nenhum trabalho servil fareis; é estatuto perpétuo em todas as vossas habitações pelas vossas gerações.

[[v3-23-22]]

^<<v3-23-22,22>>^ Quando fizeres a sega da tua terra, não segarás totalmente os cantos do teu campo, nem colherás as espigas caídas da tua sega; para o pobre e para o estrangeiro as deixarás. Eu sou o Senhor vosso Deus.

[[v3-23-23]]

^<<v3-23-23,23>>^ Disse mais o Senhor a Moisés:

[[v3-23-24]]

^<<v3-23-24,24>>^ Fala aos filhos de Israel: No sétimo mês, no primeiro dia do mês, haverá para vós descanso solene, em memorial, com sonido de trombetas, uma santa convocação.

[[v3-23-25]]

^<<v3-23-25,25>>^ Nenhum trabalho servil fareis, e oferecereis oferta queimada ao Senhor.

[[v3-23-26]]

^<<v3-23-26,26>>^ Disse mais o Senhor a Moisés:

[[v3-23-27]]

^<<v3-23-27,27>>^ Ora, o décimo dia desse sétimo mês será o dia da expiação; tereis santa convocação, e afligireis as vossas almas; e oferecereis oferta queimada ao Senhor.

[[v3-23-28]]

^<<v3-23-28,28>>^ Nesse dia não fareis trabalho algum; porque é o dia da expiação, para nele fazer-se expiação por vós perante o Senhor vosso Deus.

[[v3-23-29]]

^<<v3-23-29,29>>^ Pois toda alma que não se afligir nesse dia, será extirpada do seu povo.

[[v3-23-30]]

^<<v3-23-30,30>>^ Também toda alma que nesse dia fizer algum trabalho, eu a destruirei do meio do seu povo.

[[v3-23-31]]

^<<v3-23-31,31>>^ Não fareis nele trabalho algum; isso será estatuto perpétuo pelas vossas gerações em todas as vossas habitações.

[[v3-23-32]]

^<<v3-23-32,32>>^ Sábado de descanso vos será, e afligireis as vossas almas; desde a tardinha do dia nono do mês até a outra tarde, guardareis o vosso sábado.

[[v3-23-33]]

^<<v3-23-33,33>>^ Disse mais o Senhor a Moisés:

[[v3-23-34]]

^<<v3-23-34,34>>^ Fala aos filhos de Israel, dizendo: Desde o dia quinze desse sétimo mês haverá a festa dos tabernáculos ao Senhor por sete dias.

[[v3-23-35]]

^<<v3-23-35,35>>^ No primeiro dia haverá santa convocação; nenhum trabalho servil fareis.

[[v3-23-36]]

^<<v3-23-36,36>>^ Por sete dias oferecereis ofertas queimadas ao Senhor; ao oitavo dia tereis santa convocação, e oferecereis oferta queimada ao Senhor; será uma assembléia solene; nenhum trabalho servil fareis.

[[v3-23-37]]

^<<v3-23-37,37>>^ Estas são as festas fixas do Senhor, que proclamareis como santas convocações, para oferecer-se ao Senhor oferta queimada, holocausto e oferta de cereais, sacrifícios e ofertas de libação, cada qual em seu dia próprio;

[[v3-23-38]]

^<<v3-23-38,38>>^ além dos sábados do Senhor, e além dos vossos dons, e além de todos os vossos votos, e além de todas as vossas ofertas voluntárias que derdes ao Senhor.

[[v3-23-39]]

^<<v3-23-39,39>>^ Desde o dia quinze do sétimo mês, quando tiverdes colhido os frutos da terra, celebrareis a festa do Senhor por sete dias; no primeiro dia haverá descanso solene, e no oitavo dia haverá descanso solene.

[[v3-23-40]]

^<<v3-23-40,40>>^ No primeiro dia tomareis para vós o fruto de árvores formosas, folhas de palmeiras, ramos de árvores frondosas e salgueiros de ribeiras; e vos alegrareis perante o Senhor vosso Deus por sete dias.

[[v3-23-41]]

^<<v3-23-41,41>>^ E celebrá-la-eis como festa ao Senhor por sete dias cada ano; estatuto perpétuo será pelas vossas gerações; no mês sétimo a celebrareis.

[[v3-23-42]]

^<<v3-23-42,42>>^ Por sete dias habitareis em tendas de ramos; todos os naturais em Israel habitarão em tendas de ramos,

[[v3-23-43]]

^<<v3-23-43,43>>^ para que as vossas gerações saibam que eu fiz habitar em tendas de ramos os filhos de Israel, quando os tirei da terra do Egito. Eu sou o Senhor vosso Deus.

[[v3-23-44]]

^<<v3-23-44,44>>^ Assim declarou Moisés aos filhos de Israel as festas fixas do Senhor.

'''

xref:003-levitico/003-levitico-022.adoc#v3-22-0[&#60; Capítulo Anterior] | <<v3-23-0,Topo>> | xref:003-levitico/003-levitico-024.adoc#v3-24-0[Próximo Capítulo &#62;]