include::./index.adoc[]

[[v28-7-0]]
=== Oséias, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-7-1]]

^<<v28-7-1,1>>^ ao querer eu sarar a Israel, descobrem-se a corrupção de Efraim e as maldades de Samária; porque praticam a falsidade; o ladrão entra, e a horda dos salteadores despoja por fora.

[[v28-7-2]]

^<<v28-7-2,2>>^ Não consideram no seu coração que eu me lembro de toda a sua maldade; agora, pois, os cercam as suas obras; diante da minha face estão.

[[v28-7-3]]

^<<v28-7-3,3>>^ Com a sua malícia alegram ao rei, e com as suas mentiras aos príncipes.

[[v28-7-4]]

^<<v28-7-4,4>>^ Todos eles são adúlteros; são semelhantes ao forno aceso, cujo padeiro cessa de atear o fogo desde o amassar a massa até que seja levedada.

[[v28-7-5]]

^<<v28-7-5,5>>^ E no dia do nosso rei os príncipes se tornaram doentes com a excitação do vinho; o rei estendeu a sua mão com escarnecedores.

[[v28-7-6]]

^<<v28-7-6,6>>^ Pois têm preparado o coração como um forno, enquanto estão de espreita; toda a noite dorme a sua ira; pela manhã arde como fogo de chama.

[[v28-7-7]]

^<<v28-7-7,7>>^ Eles estão todos quentes como um forno, e devoram os seus juízes; todos os seus reis caem; ninguém entre eles há que me invoque.

[[v28-7-8]]

^<<v28-7-8,8>>^ Quanto a Efraim, ele se mistura com os povos; Efraim é um bolo que não foi virado.

[[v28-7-9]]

^<<v28-7-9,9>>^ Estrangeiros lhe devoram a força, e ele não o sabe; também as cãs se espalham sobre ele, e não o sabe.

[[v28-7-10]]

^<<v28-7-10,10>>^ E a soberba de Israel testifica contra ele; todavia, não voltam para o Senhor seu Deus, nem o buscam em tudo isso.

[[v28-7-11]]

^<<v28-7-11,11>>^ Pois Efraim é como uma pomba, insensata, sem entendimento; invocam o Egito, vão para a Assíria.

[[v28-7-12]]

^<<v28-7-12,12>>^ Quando forem, sobre eles estenderei a minha rede, e como aves do céu os farei descer; castigá-los-ei, conforme o que eles têm ouvido na sua congregação.

[[v28-7-13]]

^<<v28-7-13,13>>^ Ai deles! porque se erraram de mim; destruição sobre eles! porque se rebelaram contra mim. Quisera eu remi-los, mas falam mentiras contra mim.

[[v28-7-14]]

^<<v28-7-14,14>>^ Não clamam a mim de coração, mas uivam nas suas camas; para o trigo e para o mosto se ajuntam, mas contra mim se rebelam.

[[v28-7-15]]

^<<v28-7-15,15>>^ Contudo fui eu que os ensinei, e lhes fortaleci os braços; entretanto maquinam o mal contra mim.

[[v28-7-16]]

^<<v28-7-16,16>>^ Eles voltam, mas não para o Altíssimo. Fizeram-se como um arco enganador; caem à espada os seus príncipes, por causa da insolência da sua língua; este será o seu escárnio na terra do Egito.

'''

xref:028-oseias/028-oseias-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-oseias/028-oseias-008.adoc#v28-8-0[Próximo Capítulo &#62;]