include::./index.adoc[]

[[v28-8-0]]
=== Oséias, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-8-1]]

^<<v28-8-1,1>>^ Põe a trombeta à tua boca. Ele vem como águia contra a casa do Senhor; porque eles transgrediram o meu pacto, e se rebelaram contra a minha lei.

[[v28-8-2]]

^<<v28-8-2,2>>^ E a mim clamam: Deus meu, nós, Israel, te conhecemos.

[[v28-8-3]]

^<<v28-8-3,3>>^ Israel desprezou o bem; o inimigo persegui-lo-á.

[[v28-8-4]]

^<<v28-8-4,4>>^ Eles fizeram reis, mas não por mim; constituíram príncipes, mas sem a minha aprovação; da sua prata e do seu ouro fizeram ídolos para si, para serem destruídos.

[[v28-8-5]]

^<<v28-8-5,5>>^ O teu bezerro, ó Samária, é rejeitado; a minha ira se acendeu contra eles; até quando serão eles incapazes da inocência?

[[v28-8-6]]

^<<v28-8-6,6>>^ Pois isso procede de Israel; um artífice o fez, e não é Deus. Será desfeito em pedaços o bezerro de Samária

[[v28-8-7]]

^<<v28-8-7,7>>^ Porquanto semeiam o vento, hão de ceifar o turbilhão; não haverá seara, a erva não dará farinha; se a der, tragá-la-ão os estrangeiros.

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel foi devorado; agora está entre as nações como um vaso em que ninguém tem prazer.

[[v28-8-9]]

^<<v28-8-9,9>>^ Porque subiram à Assíria, qual asno selvagem andando sozinho; mercou Efraim amores.

[[v28-8-10]]

^<<v28-8-10,10>>^ Todavia, ainda que eles merquem entre as nações, eu as congregarei; já começaram a ser diminuídos por causa da carga do rei dos príncipes.

[[v28-8-11]]

^<<v28-8-11,11>>^ Ainda que Efraim tem multiplicado altares, estes se lhe tornaram altares para pecar.

[[v28-8-12]]

^<<v28-8-12,12>>^ Escrevi para ele miríades de coisas da minha lei; mas isso é para ele como coisa estranha.

[[v28-8-13]]

^<<v28-8-13,13>>^ Quanto aos sacrifícios das minhas ofertas, eles sacrificam carne, e a comem; mas o Senhor não os aceita; agora se lembrará da iniqüidade deles, e punirá os seus pecados; eles voltarão para o Egito.

[[v28-8-14]]

^<<v28-8-14,14>>^ Pois Israel se esqueceu do seu Criador, e edificou palácios, e Judá multiplicou cidades fortificadas. Mas eu enviarei sobre as suas cidades um fogo que consumirá os seus castelos.

'''

xref:028-oseias/028-oseias-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-oseias/028-oseias-009.adoc#v28-9-0[Próximo Capítulo &#62;]