include::./index.adoc[]

[[v28-2-0]]
=== Oséias, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-2-1]]

^<<v28-2-1,1>>^ Dizei a vossos irmãos: Ami; e a vossas irmãs: Ruama.

[[v28-2-2]]

^<<v28-2-2,2>>^ Contendei com vossa mãe, contendei; porque ela não é minha mulher, e eu não sou seu marido; para que ela afaste as suas prostituições da sua face e os seus adultérios de entre os seus seios;

[[v28-2-3]]

^<<v28-2-3,3>>^ para que eu não a deixe despida, e a ponha como no dia em que nasceu, e a faça como um deserto, e a torne como uma terra seca, e a mate à sede.

[[v28-2-4]]

^<<v28-2-4,4>>^ Até de seus filhos não me compadecerei; porquanto são filhos de prostituições.

[[v28-2-5]]

^<<v28-2-5,5>>^ porque sua mãe se prostituiu; aquela que os concebeu houve-se torpemente; porque diz: Irei após os meus amantes, que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu óleo e as minhas bebidas.

[[v28-2-6]]

^<<v28-2-6,6>>^ Portanto, eis que lhe cercarei o caminho com espinhos, e contra ela levantarei uma sebe, para que ela não ache as suas veredas.

[[v28-2-7]]

^<<v28-2-7,7>>^ Ela irá em seguimento de seus amantes, mas não os alcançará; buscá-los-á, mas não os achará; então dirá: Irei, e voltarei a meu primeiro marido, porque melhor me ia então do que agora.

[[v28-2-8]]

^<<v28-2-8,8>>^ Ora, ela não reconhece que fui eu o que lhe dei o grão, e o vinho, e o azeite, e que lhe multipliquei a prata e o ouro, que eles usaram para Baal.

[[v28-2-9]]

^<<v28-2-9,9>>^ Portanto, tornarei a tirar o meu grão a seu tempo e o meu vinho no seu tempo determinado; e arrebatarei a minha lã e o meu linho, com que cobriam a sua nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ E agora descobrirei a sua vileza diante dos olhos dos seus amantes, e ninguém a livrará da minha mão.

[[v28-2-11]]

^<<v28-2-11,11>>^ Também farei cessar todo o seu gozo, as suas festas, as suas luas novas, e os seus sábados, e todas as suas assembléias solenes.

[[v28-2-12]]

^<<v28-2-12,12>>^ E devastarei a sua vide e a sua figueira, de que ela diz: É esta a paga que me deram os meus amantes; eu, pois, farei delas um bosque, e as feras do campo as devorarão.

[[v28-2-13]]

^<<v28-2-13,13>>^ Castigá-la-ei pelos dias dos baalins, nos quais elas lhes queimava incenso, e se adornava com as suas arrecadas e as suas jóias, e, indo atrás dos seus amantes, se esquecia de mim, diz o Senhor.

[[v28-2-14]]

^<<v28-2-14,14>>^ Portanto, eis que eu a atrairei, e a levarei para o deserto, e lhe falarei ao coração.

[[v28-2-15]]

^<<v28-2-15,15>>^ E lhe darei as suas vinhas dali, e o vale de Acor por porta de esperança; e ali responderá, como nos dias da sua mocidade, e como no dia em que subiu da terra do Egito.

[[v28-2-16]]

^<<v28-2-16,16>>^ E naquele dia, diz o Senhor, ela me chamará meu marido; e não me chamará mais meu Baal.

[[v28-2-17]]

^<<v28-2-17,17>>^ Pois da sua boca tirarei os nomes dos baalins, e não mais se fará menção desses nomes.

[[v28-2-18]]

^<<v28-2-18,18>>^ Naquele dia farei por eles aliança com as feras do campo, e com as aves do céu, e com os répteis da terra; e da terra tirarei o arco, e a espada, e a guerra, e os farei deitar em segurança.

[[v28-2-19]]

^<<v28-2-19,19>>^ E desposar-te-ei comigo para sempre; sim, desposar-te-ei comigo em justiça, e em juízo, e em amorável benignidade, e em misericórdias;

[[v28-2-20]]

^<<v28-2-20,20>>^ e desposar-te-ei comigo em fidelidade, e conhecerás ao Senhor.

[[v28-2-21]]

^<<v28-2-21,21>>^ Naquele dia responderei, diz o Senhor; responderei aos céus, e estes responderão a terra;

[[v28-2-22]]

^<<v28-2-22,22>>^ a terra responderá ao trigo, e ao vinho, e ao azeite, e estes responderão a Jizreel.

[[v28-2-23]]

^<<v28-2-23,23>>^ E semeá-lo-ei para mim na terra, e compadecer-me-ei de Lo-Ruama; e a e Lo-Ami direi: Tu és meu povo; e ele dirá: Tu és o meu Deus.

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]