include::./index.adoc[]

[[v28-1-0]]
=== Oséias, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-1-1]]

^<<v28-1-1,1>>^ A palavra do Senhor, que veio a Oséias, filho de Beeri, nos dias de Uzias, Jotão, Acaz e Ezequias, reis de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel.

[[v28-1-2]]

^<<v28-1-2,2>>^ Quando o Senhor falou no princípio por Oséias, disse o Senhor a Oséias: Vai, toma por esposa uma mulher de prostituições, e filhos de prostituição; porque a terra se prostituiu, apartando-se do Senhor.

[[v28-1-3]]

^<<v28-1-3,3>>^ Ele se foi, pois, e tomou a Gomer, filha de Diblaim; e ela concebeu, e lhe deu um filho.

[[v28-1-4]]

^<<v28-1-4,4>>^ E disse-lhe o Senhor: Põe-lhe o nome de Jizreel; porque daqui a pouco visitarei o sangue de Jizreel sobre a casa de Jeú, e farei cessar o reino da casa de Israel.

[[v28-1-5]]

^<<v28-1-5,5>>^ E naquele dia quebrarei o arco de Israel no vale de Jizreel.

[[v28-1-6]]

^<<v28-1-6,6>>^ E tornou ela a conceber, e deu à luz uma filha. E o Senhor disse a Oséias: Põe-lhe o nome de Lo-Ruama; porque não tornarei mais a compadecer-me da casa de Israel, nem a perdoar-lhe de maneira alguma.

[[v28-1-7]]

^<<v28-1-7,7>>^ Mas da casa se Judá me compadecerei, e os salvarei pelo Senhor seu Deus, pois não os salvarei pelo arco, nem pela espada, nem pela guerra, nem pelos cavalos, nem pelos cavaleiros.

[[v28-1-8]]

^<<v28-1-8,8>>^ Ora depois de haver desmamado a Lo-Ruama, concebeu e deu à luz um filho.

[[v28-1-9]]

^<<v28-1-9,9>>^ E o Senhor disse: Põe-lhe o nome de Lo-Ami; porque vós não sois meu povo, nem sou eu vosso Deus.

[[v28-1-10]]

^<<v28-1-10,10>>^ Todavia o número dos filhos de Israel será como a areia do mar, que não pode ser medida nem contada; e no lugar onde se lhes dizia: Vós não sois meu povo, se lhes dirá: Vós sois os filhos do Deus vivo.

[[v28-1-11]]

^<<v28-1-11,11>>^ E os filhos de Judá e os filhos de Israel juntos se congregarão, e constituirão sobre si uma só cabeça, e subirão da terra; pois grande será o dia de Jizreel.

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-oseias/028-oseias-002.adoc#v28-2-0[Próximo Capítulo &#62;]