include::./index.adoc[]

[[v28-10-0]]
=== Oséias, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-10-1]]

^<<v28-10-1,1>>^ Israel é vide frondosa que dá o seu fruto; conforme a abundância do seu fruto, assim multiplicou os altares; conforme a prosperidade da terra, assim fizeram belas colunas.

[[v28-10-2]]

^<<v28-10-2,2>>^ O seu coração está dividido, por isso serão culpados; ele derribará os altares deles, e lhes destruirá as colunas.

[[v28-10-3]]

^<<v28-10-3,3>>^ Certamente agora dirão: Não temos rei, porque não tememos ao Senhor; e o rei, que pode ele fazer por nós?

[[v28-10-4]]

^<<v28-10-4,4>>^ Falam palavras vãs; juram falsamente, fazendo pactos; por isso brota o juízo como erva peçonhenta nos sulcos dos campos.

[[v28-10-5]]

^<<v28-10-5,5>>^ Os moradores de Samária serão atemorizados por causa do bezerro de Bete-Áven. O seu povo se lamentará por causa dele, como também prantearão os seus sacerdotes idólatras por causa da sua glória, que se apartou dela.

[[v28-10-6]]

^<<v28-10-6,6>>^ Também será ele levado para Assíria como um presente ao rei Jarebe; Efraim ficará confuso, e Israel se envergonhará por causa do seu próprio conselho.

[[v28-10-7]]

^<<v28-10-7,7>>^ O rei de Samária será desfeito como a espuma sobre a face da água.

[[v28-10-8]]

^<<v28-10-8,8>>^ E os altos de Áven, pecado de Israel, serão destruídos; espinhos e cardos crescerão sobre os seus altares; e dirão aos montes: Cobri-nos! e aos outeiros: Caí sobre nós!

[[v28-10-9]]

^<<v28-10-9,9>>^ Desde os dias de Gibeá tens pecado, ó Israel; ali permaneceram; a peleja contra os filhos da iniqüidade não os alcançará em Gibeá.

[[v28-10-10]]

^<<v28-10-10,10>>^ Quando eu quiser, castigá-los-ei; e os povos se congregarão contra eles, quando forem castigados pela sua dupla transgressão.

[[v28-10-11]]

^<<v28-10-11,11>>^ Porque Efraim era uma novilha domada, que gostava de trilhar; e eu poupava a formosura do seu pescoço; mas porei arreios sobre Efraim; Judá lavrará; Jacó desfará os torrões.

[[v28-10-12]]

^<<v28-10-12,12>>^ Semeai para vós em justiça, colhei segundo a misericórdia; lavrai o campo alqueivado; porque é tempo de buscar ao Senhor, até que venha e chova a justiça sobre vós.

[[v28-10-13]]

^<<v28-10-13,13>>^ Lavrastes a impiedade, segastes a iniqüidade, e comestes o fruto da mentira; porque confiaste no teu caminho, na multidão dos teus valentes.

[[v28-10-14]]

^<<v28-10-14,14>>^ Portanto, entre o teu povo se levantará tumulto de guerra, e todas as tuas fortalezas serão destruídas, como Salmã destruiu a Bete-Arbel no dia da batalha; a mãe ali foi despedaçada juntamente com os filhos.

[[v28-10-15]]

^<<v28-10-15,15>>^ Assim vos fará Betel, por causa da vossa grande malícia; de madrugada será o rei de Israel totalmente destruído.

'''

xref:028-oseias/028-oseias-009.adoc#v28-9-0[&#60; Capítulo Anterior] | <<v28-10-0,Topo>> | xref:028-oseias/028-oseias-011.adoc#v28-11-0[Próximo Capítulo &#62;]