include::./index.adoc[]

[[v28-12-0]]
=== Oséias, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-12-1]]

^<<v28-12-1,1>>^ Efraim apascenta o vento, segue o vento oriental todo o dia; multiplica a mentira e a destruição; e fazem aliança com a Assíria, e o azeite se leva ao Egito

[[v28-12-2]]

^<<v28-12-2,2>>^ O Senhor também com Judá tem contenda, e castigará a Jacó segundo os seus caminhos; segundo as suas obras o recompensará.

[[v28-12-3]]

^<<v28-12-3,3>>^ No ventre pegou do calcanhar de seu irmão; e na sua idade varonil lutou com Deus.

[[v28-12-4]]

^<<v28-12-4,4>>^ Lutou com o anjo, e prevaleceu; chorou, e lhe fez súplicas. Em Betel o achou, e ali falou Deus com ele;

[[v28-12-5]]

^<<v28-12-5,5>>^ sim, o Senhor, o Deus dos exércitos; o Senhor e o seu nome.

[[v28-12-6]]

^<<v28-12-6,6>>^ Tu, pois, converte-te a teu Deus; guarda a benevolência e a justiça, e em teu Deus espera sempre.

[[v28-12-7]]

^<<v28-12-7,7>>^ Quanto a Canaã, tem nas mãos balança enganadora; ama a opressão.

[[v28-12-8]]

^<<v28-12-8,8>>^ Diz Efraim: Certamente eu me tenho enriquecido, tenho adquirido para mim grandes bens; em todo o meu trabalho não acharão em mim iniqüidade alguma que seja pecado.

[[v28-12-9]]

^<<v28-12-9,9>>^ Mas eu sou o Senhor teu Deus, desde a terra do Egito; eu ainda te farei habitar de novo em tendas, como nos dias da festa solene.

[[v28-12-10]]

^<<v28-12-10,10>>^ Também falei aos profetas, e multipliquei as visões; e pelo ministério dos profetas usei de parábolas.

[[v28-12-11]]

^<<v28-12-11,11>>^ Não é Gileade iniqüidade? pura vaidade são eles. Em Gilgal sacrificam bois; os seus altares são como montões de pedras nos sulcos dos campos.

[[v28-12-12]]

^<<v28-12-12,12>>^ Jacó fugiu para o campo de Arã, e Israel serviu por uma mulher, sim, por uma mulher guardou o gado.

[[v28-12-13]]

^<<v28-12-13,13>>^ Mas o Senhor por meio dum profeta fez subir a Israel do Egito, e por um profeta foi ele preservado.

[[v28-12-14]]

^<<v28-12-14,14>>^ Efraim mui amargamente provocou-lhe a ira; portanto sobre ele será deixado o seu sangue, e o seu Senhor fará cair sobre ele o seu opróbrio.

'''

xref:028-oseias/028-oseias-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-oseias/028-oseias-013.adoc#v28-13-0[Próximo Capítulo &#62;]