include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-6-1]]

^<<v28-6-1,1>>^ Vinde, e tornemos para o Senhor, porque ele despedaçou e nos sarará; fez a ferida, e no-la atará.

[[v28-6-2]]

^<<v28-6-2,2>>^ Depois de dois dias nos ressuscitará: ao terceiro dia nos levantará, e viveremos diante dele.

[[v28-6-3]]

^<<v28-6-3,3>>^ Conheçamos, e prossigamos em conhecer ao Senhor; a sua saída, como a alva, é certa; e ele a nós virá como a chuva, como a chuva serôdia que rega a terra.

[[v28-6-4]]

^<<v28-6-4,4>>^ Que te farei, ó Efraim? que te farei, ó Judá? porque o vosso amor é como a nuvem da manhã, e como o orvalho que cedo passa.

[[v28-6-5]]

^<<v28-6-5,5>>^ Por isso os abati pelos profetas; pela palavra da minha boca os matei; e os meus juízos a teu respeito sairão como a luz.

[[v28-6-6]]

^<<v28-6-6,6>>^ Pois misericórdia quero, e não sacrifícios; e o conhecimento de Deus, mais do que os holocaustos.

[[v28-6-7]]

^<<v28-6-7,7>>^ Eles, porém, como Adão, transgrediram o pacto; nisso eles se portaram aleivosamente contra mim.

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é cidade de malfeitores, está manchada de sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ Como hordas de salteadores que espreitam alguém, assim é a companhia dos sacerdotes que matam no caminho para Siquém; sim, cometem a vilania.

[[v28-6-10]]

^<<v28-6-10,10>>^ Vejo uma coisa horrenda na casa de Israel; ali está a prostituição de Efraim; Israel está contaminado.

[[v28-6-11]]

^<<v28-6-11,11>>^ Também para ti, ó Judá, está determinada uma ceifa. Ao querer eu trazer do cativeiro o meu povo,

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]