include::./index.adoc[]

[[v28-3-0]]
=== Oséias, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-3-1]]

^<<v28-3-1,1>>^ Disse-me o Senhor: Vai outra vez, ama uma mulher, amada de seu amigo, e adúltera, como o Senhor ama os filhos de Israel, embora eles se desviem para outros deuses, e amem passas de uvas.

[[v28-3-2]]

^<<v28-3-2,2>>^ Assim eu comprei para mim tal mulher por quinze peças de prata, e um hômer e meio de cevada;

[[v28-3-3]]

^<<v28-3-3,3>>^ e lhe disse: Por muitos dias tu ficarás esperando por mim; não te prostituirás, nem serás mulher de outro homem; assim também eu esperarei por ti.

[[v28-3-4]]

^<<v28-3-4,4>>^ Pois os filhos de Israel ficarão por muitos dias sem rei, sem príncipe, sem sacrifício, sem coluna, e sem éfode ou terafins.

[[v28-3-5]]

^<<v28-3-5,5>>^ Depois tornarão os filhos de Israel, e buscarão ao Senhor, seu Deus, e a Davi, seu rei; e com temor chegarão nos últimos dias ao Senhor, e à sua bondade.

'''

xref:028-oseias/028-oseias-002.adoc#v28-2-0[&#60; Capítulo Anterior] | <<v28-3-0,Topo>> | xref:028-oseias/028-oseias-004.adoc#v28-4-0[Próximo Capítulo &#62;]