include::./index.adoc[]

[[v28-14-0]]
=== Oséias, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-14-1]]

^<<v28-14-1,1>>^ Volta, ó Israel, para o Senhor teu Deus; porque pela tua iniqüidade tens caído.

[[v28-14-2]]

^<<v28-14-2,2>>^ Tomai convosco palavras, e voltai para o Senhor; dizei-lhe: Tira toda a iniqüidade, e aceita o que é bom; e ofereceremos como novilhos os sacrifícios dos nossos lábios.

[[v28-14-3]]

^<<v28-14-3,3>>^ Não nos salvará a Assíria, não iremos montados em cavalos; e à obra das nossas mãos já não diremos: Tu és o nosso Deus; porque em ti o órfão acha a misericórdia.

[[v28-14-4]]

^<<v28-14-4,4>>^ Eu sararei a sua apostasia, eu voluntariamente os amarei; porque a minha ira se apartou deles.

[[v28-14-5]]

^<<v28-14-5,5>>^ Eu serei para Israel como o orvalho; ele florescerá como o lírio, e lançará as suas raízes como o Líbano.

[[v28-14-6]]

^<<v28-14-6,6>>^ Estender-se-ão as suas vergônteas, e a sua formosura será como a da oliveira, a sua fragrância como a do Líbano.

[[v28-14-7]]

^<<v28-14-7,7>>^ Voltarão os que habitam à sua sombra; reverdecerão como o trigo, e florescerão como a vide; o seu renome será como o do vinho do Líbano.

[[v28-14-8]]

^<<v28-14-8,8>>^ Ó Efraim, que tenho eu com os ídolos? Sou eu que respondo, e cuido de ti. Eu sou como a faia verde; de mim é achado o teu fruto.

[[v28-14-9]]

^<<v28-14-9,9>>^ Quem é sábio, para que entenda estas coisas? prudente, para que as saiba? porque os caminhos do Senhor são retos, e os justos andarão neles; mas os transgressores neles cairão.

'''

xref:028-oseias/028-oseias-013.adoc#v28-13-0[&#60; Capítulo Anterior] | <<v28-14-0,Topo>> | xref:029-joel/029-joel-001.adoc#v29-1-0[Próximo Capítulo &#62;]