include::./index.adoc[]

[[v28-11-0]]
=== Oséias, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-11-1]]

^<<v28-11-1,1>>^ Quando Israel era menino, eu o amei, e do Egito chamei a meu filho.

[[v28-11-2]]

^<<v28-11-2,2>>^ Quanto mais eu os chamava, tanto mais se afastavam de mim; sacrificavam aos baalins, e queimavam incenso às imagens esculpidas.

[[v28-11-3]]

^<<v28-11-3,3>>^ Todavia, eu ensinei aos de Efraim a andar; tomei-os nos meus braços; mas não entendiam que eu os curava.

[[v28-11-4]]

^<<v28-11-4,4>>^ Atraí-os com cordas humanas, com laços de amor; e fui para eles como os que tiram o jugo de sobre as suas queixadas, e me inclinei para lhes dar de comer.

[[v28-11-5]]

^<<v28-11-5,5>>^ Não voltarão para a terra do Egito; mas a Assíria será seu rei; porque recusam converter-se.

[[v28-11-6]]

^<<v28-11-6,6>>^ Cairá a espada sobre as suas cidades, e consumirá os seus ferrolhos; e os devorará nas suas fortalezas.

[[v28-11-7]]

^<<v28-11-7,7>>^ Porque o meu povo é inclinado a desviar-se de mim; ainda que clamem ao Altíssimo, nenhum deles o exalta.

[[v28-11-8]]

^<<v28-11-8,8>>^ Como te deixaria, ó Efraim? como te entregaria, ó Israel? como te faria como Admá? ou como Zeboim? Está comovido em mim o meu coração, as minhas compaixões à uma se acendem.

[[v28-11-9]]

^<<v28-11-9,9>>^ Não executarei o furor da minha ira; não voltarei para destruir a Efraim, porque eu sou Deus e não homem, o Santo no meio de ti; eu não virei com ira.

[[v28-11-10]]

^<<v28-11-10,10>>^ Andarão após o Senhor; ele bramará como leão; e, bramando ele, os filhos, tremendo, virão do ocidente.

[[v28-11-11]]

^<<v28-11-11,11>>^ Também, tremendo, virão como um passarinho os do Egito, e como uma pomba os da terra da Assíria; e os farei habitar em suas casas, diz o Senhor.

[[v28-11-12]]

^<<v28-11-12,12>>^ Efraim me cercou com mentira, e a casa de Israel com engano; mas Judá ainda domina com Deus, e com o Santo está fiel.

'''

xref:028-oseias/028-oseias-010.adoc#v28-10-0[&#60; Capítulo Anterior] | <<v28-11-0,Topo>> | xref:028-oseias/028-oseias-012.adoc#v28-12-0[Próximo Capítulo &#62;]