include::./index.adoc[]

[[v28-5-0]]
=== Oséias, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-5-1]]

^<<v28-5-1,1>>^ Ouvi isto, ó sacerdotes, e escutai, ó casa de Israel, e dai ouvidos, ó casa do rei; porque contra vós se dirige este juízo; pois que vos tornastes um laço para Mizpá, e uma rede estendida sobre o Tabor.

[[v28-5-2]]

^<<v28-5-2,2>>^ Os revoltosos se aprofundaram na corrupção; mas eu os castigarei a todos eles.

[[v28-5-3]]

^<<v28-5-3,3>>^ Eu conheço a Efraim, e Israel não se me esconde; porque agora te tens prostituído, ó Efraim, e Israel se contaminou.

[[v28-5-4]]

^<<v28-5-4,4>>^ As suas ações não lhes permitem voltar para o seu Deus; porque o espírito da prostituição está no meio deles, e não conhecem ao Senhor.

[[v28-5-5]]

^<<v28-5-5,5>>^ A soberba de Israel testifica contra eles; e Israel e Efraim cairão pela sua iniqüidade, e Judá cairá juntamente com eles.

[[v28-5-6]]

^<<v28-5-6,6>>^ Eles irão com os seus rebanhos e com as suas manadas, para buscarem ao Senhor, mas não o acharão; ele se retirou deles.

[[v28-5-7]]

^<<v28-5-7,7>>^ Aleivosamente se houveram contra o Senhor, porque geraram filhos estranhos; agora a festa da lua nova os consumirá, juntamente com as suas porções.

[[v28-5-8]]

^<<v28-5-8,8>>^ Tocai a corneta em Gibeá, a trombeta em Ramá; soltai o alarma em Bete-Áven; após ti, ó Benjamim.

[[v28-5-9]]

^<<v28-5-9,9>>^ Efraim será para assolação no dia do castigo: entre as tribos de Israel declaro o que é certo.

[[v28-5-10]]

^<<v28-5-10,10>>^ Os príncipes de Judá são como os que removem os marcos; derramarei, pois, o meu furor sobre eles como água.

[[v28-5-11]]

^<<v28-5-11,11>>^ Efraim está oprimido e quebrantado no juízo, porque foi do seu agrado andar após a vaidade.

[[v28-5-12]]

^<<v28-5-12,12>>^ Portanto para Efraim serei como a traça e para a casa de Judá como a podridão.

[[v28-5-13]]

^<<v28-5-13,13>>^ Quando Efraim viu a sua enfermidade, e Judá a sua chaga, recorreu Efraim à Assíria e enviou ao rei Jarebe; mas ele não pode curar-vos, nem sarar a vossa chaga.

[[v28-5-14]]

^<<v28-5-14,14>>^ Pois para Efraim serei como um leão, e como um leão novo para a casa de Judá; eu, sim eu despedaçarei, e ir-me-ei embora; arrebatarei, e não haverá quem livre.

[[v28-5-15]]

^<<v28-5-15,15>>^ Irei, e voltarei para o meu lugar, até que se reconheçam culpados e busquem a minha face; estando eles aflitos, ansiosamente me buscarão.

'''

xref:028-oseias/028-oseias-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-oseias/028-oseias-006.adoc#v28-6-0[Próximo Capítulo &#62;]