include::./index.adoc[]

[[v28-4-0]]
=== Oséias, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-4-1]]

^<<v28-4-1,1>>^ Ouvi a palavra do Senhor, vós, filhos de Israel; pois o Senhor tem uma contenda com os habitantes da terra; porque na terra não há verdade, nem benignidade, nem conhecimento de Deus.

[[v28-4-2]]

^<<v28-4-2,2>>^ Só prevalecem o perjurar, o mentir, o matar, o furtar, e o adulterar; há violências e homicídios sobre homicídios.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso a terra se lamenta, e todo o que nela mora desfalece, juntamente com os animais do campo e com as aves do céu; e até os peixes do mar perecem.

[[v28-4-4]]

^<<v28-4-4,4>>^ Todavia ninguém contenda, ninguém repreenda; pois é contigo a minha contenda, ó sacerdote.

[[v28-4-5]]

^<<v28-4-5,5>>^ Por isso tu tropeçarás de dia, e o profeta contigo tropeçará de noite; e destruirei a tua mãe.

[[v28-4-6]]

^<<v28-4-6,6>>^ O meu povo está sendo destruído, porque lhe falta o conhecimento. Porquanto rejeitaste o conhecimento, também eu te rejeitarei, para que não sejas sacerdote diante de mim; visto que te esqueceste da lei do teu Deus, também eu me esquecerei de teus filhos.

[[v28-4-7]]

^<<v28-4-7,7>>^ Quanto mais eles se multiplicaram tanto mais contra mim pecaram: eu mudarei a sua honra em vergonha.

[[v28-4-8]]

^<<v28-4-8,8>>^ Alimentavam-se do pecado do meu povo, e de coração desejam a iniqüidade dele.

[[v28-4-9]]

^<<v28-4-9,9>>^ Por isso, como é o povo, assim será o sacerdote; e castigá-lo-ei conforme os seus caminhos, e lhe darei a recompensa das suas obras.

[[v28-4-10]]

^<<v28-4-10,10>>^ Comerão, mas não se fartarão; entregar-se-ão à luxúria, mas não se multiplicarão; porque deixaram de atentar para o Senhor.

[[v28-4-11]]

^<<v28-4-11,11>>^ A incontinência, e o vinho, e o mosto tiram o entendimento.

[[v28-4-12]]

^<<v28-4-12,12>>^ O meu povo consulta ao seu pau, e a sua vara lhe dá respostas, porque o espírito de luxúria os enganou, e eles, prostituindo-se, abandonam o seu Deus.

[[v28-4-13]]

^<<v28-4-13,13>>^ Sacrificam sobre os cumes dos montes; e queimam incenso sobre os outeiros, debaixo do carvalho, do álamo, e do terebinto, porque é boa a sua sombra; por isso vossas filhas se prostituem, e as vossas noras adulteram.

[[v28-4-14]]

^<<v28-4-14,14>>^ Eu não castigarei vossas filhas, quando se prostituem, nem vossas noras, quando adulteram; porque os homens mesmos com as prostitutas se desviam, e com as meretrizes sacrificam; pois o povo que não tem entendimento será transtornado.

[[v28-4-15]]

^<<v28-4-15,15>>^ Ainda que tu, ó Israel, te queiras prostituir contudo não se faça culpado Judá; não venhais a Gilgal, e não subais a Bete-Ávem nem jureis, dizendo: Vive o Senhor.

[[v28-4-16]]

^<<v28-4-16,16>>^ Porque como novilha obstinada se rebelou Israel; agora o Senhor os apascentará como a um cordeiro num lugar espaçoso.

[[v28-4-17]]

^<<v28-4-17,17>>^ Efraim está entregue aos ídolos; deixa-o.

[[v28-4-18]]

^<<v28-4-18,18>>^ Acabando eles de beber, lançam-se à luxúria; certamente os seus príncipes amam a vergonha.

[[v28-4-19]]

^<<v28-4-19,19>>^ Um vento os envolveu nas suas asas; e eles se envergonharão por causa dos seus sacrifícios.

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]