include::./index.adoc[]

[[v28-9-0]]
=== Oséias, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v28-9-1]]

^<<v28-9-1,1>>^ Não te alegres, ó Israel, não exultes como os povos; pois te prostituíste, apartando-te do teu Deus; amaste a paga de meretriz sobre todas as eiras de trigo.

[[v28-9-2]]

^<<v28-9-2,2>>^ A eira e o lagar não os manterão, e o vinho novo lhes faltará.

[[v28-9-3]]

^<<v28-9-3,3>>^ Na terra do Senhor não permanecerão; mas Efraim tornará ao Egito, e na Assíria comerão comida imunda.

[[v28-9-4]]

^<<v28-9-4,4>>^ Não derramarão libações de vinho ao Senhor, nem lhe agradarão com as suas ofertas. O pão deles será como pão de pranteadores; todos os que dele comerem serão imundos; pois o seu pão será somente para o seu apetite; não entrará na casa do Senhor.

[[v28-9-5]]

^<<v28-9-5,5>>^ Que fareis vós no dia da solenidade, e no dia da festa do Senhor?

[[v28-9-6]]

^<<v28-9-6,6>>^ Porque, eis que eles se foram por causa da destruição, mas o Egito os recolherá, Mênfis os sepultará; as suas coisas preciosas de prata as urtigas as possuirão; espinhos crescerão nas suas tendas.

[[v28-9-7]]

^<<v28-9-7,7>>^ Chegaram os dias da punição, chegaram os dias da retribuição; Israel o saberá; o profeta é um insensato, o homem possesso de espírito é um louco; por causa da abundância da tua iniqüidade e do teu grande ódio.

[[v28-9-8]]

^<<v28-9-8,8>>^ O profeta é a sentinela de Efraim, o povo do meu Deus; contudo um laço de caçador de aves se acha em todos os seus caminhos, e inimizade na casa do seu Deus.

[[v28-9-9]]

^<<v28-9-9,9>>^ Muito profundamente se corromperam, como nos dias de Gibeá; ele se lembrará das iniqüidades deles, e punirá os seus pecados.

[[v28-9-10]]

^<<v28-9-10,10>>^ Achei a Israel como uvas no deserto, vi a vossos pais como a fruta temporã da figueira no seu princípio; mas eles foram para Baal-Peor, e se consagraram a essa coisa vergonhosa, e se tornaram abomináveis como aquilo que amaram.

[[v28-9-11]]

^<<v28-9-11,11>>^ Quanto a Efraim, a sua glória como ave voará; não haverá nascimento, nem gravidez, nem concepção.

[[v28-9-12]]

^<<v28-9-12,12>>^ Ainda que venham criar seus filhos, eu os privarei deles, para que não fique nenhum homem. Ai deles, quando deles eu me apartar!

[[v28-9-13]]

^<<v28-9-13,13>>^ Efraim, assim como vi a Tiro, está plantado num lugar aprazível; mas Efraim levará seus filhos ao matador.

[[v28-9-14]]

^<<v28-9-14,14>>^ Dá-lhes, ó Senhor; mas que lhes darás? dá-lhes uma madre que aborte e seios ressecados.

[[v28-9-15]]

^<<v28-9-15,15>>^ Toda a sua malícia se acha em Gilgal; pois ali é que lhes concebi ódio; por causa da maldade das suas obras lançá-los-ei fora de minha casa. Não os amarei mais; todos os seus príncipes são rebeldes.

[[v28-9-16]]

^<<v28-9-16,16>>^ Efraim foi ferido, secou-se a sua raiz; eles não darão fruto; sim, ainda que gerem, eu matarei os frutos desejáveis do seu ventre.

[[v28-9-17]]

^<<v28-9-17,17>>^ O meu Deus os rejeitará, porque não o ouviram; e errantes andarão entre as nações.

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]