include::./index.adoc[]

[[v41-10-0]]
=== Marcos, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-10-1]]

^<<v41-10-1,1>>^ Levantando-se Jesus, partiu dali para os termos da Judéia, e para além do Jordão; e do novo as multidões se reuniram em torno dele; e tornou a ensiná-las, como tinha por costume.

[[v41-10-2]]

^<<v41-10-2,2>>^ Então se aproximaram dele alguns fariseus e, para o experimentarem, lhe perguntaram: É lícito ao homem repudiar sua mulher?

[[v41-10-3]]

^<<v41-10-3,3>>^ Ele, porém, respondeu-lhes: Que vos ordenou Moisés?

[[v41-10-4]]

^<<v41-10-4,4>>^ Replicaram eles: Moisés permitiu escrever carta de divórcio, e repudiar a mulher.

[[v41-10-5]]

^<<v41-10-5,5>>^ Disse-lhes Jesus: Pela dureza dos vossos corações ele vos deixou escrito esse mandamento.

[[v41-10-6]]

^<<v41-10-6,6>>^ Mas desde o princípio da criação, Deus os fez homem e mulher.

[[v41-10-7]]

^<<v41-10-7,7>>^ Por isso deixará o homem a seu pai e a sua mãe, &#123;e unir-se-á à sua mulher,&#125;

[[v41-10-8]]

^<<v41-10-8,8>>^ e serão os dois uma só carne; assim já não são mais dois, mas uma só carne.

[[v41-10-9]]

^<<v41-10-9,9>>^ Porquanto o que Deus ajuntou, não o separe o homem.

[[v41-10-10]]

^<<v41-10-10,10>>^ Em casa os discípulos interrogaram-no de novo sobre isso.

[[v41-10-11]]

^<<v41-10-11,11>>^ Ao que lhes respondeu: Qualquer que repudiar sua mulher e casar com outra comete adultério contra ela;

[[v41-10-12]]

^<<v41-10-12,12>>^ e se ela repudiar seu marido e casar com outro, comete adultério.

[[v41-10-13]]

^<<v41-10-13,13>>^ Então lhe traziam algumas crianças para que as tocasse; mas os discípulos o repreenderam.

[[v41-10-14]]

^<<v41-10-14,14>>^ Jesus, porém, vendo isto, indignou-se e disse-lhes: Deixai vir a mim as crianças, e não as impeçais, porque de tais é o reino de Deus.

[[v41-10-15]]

^<<v41-10-15,15>>^ Em verdade vos digo que qualquer que não receber o reino de Deus como criança, de maneira nenhuma entrará nele.

[[v41-10-16]]

^<<v41-10-16,16>>^ E, tomando-as nos seus braços, as abençoou, pondo as mãos sobre elas.

[[v41-10-17]]

^<<v41-10-17,17>>^ Ora, ao sair para se pôr a caminho, correu para ele um homem, o qual se ajoelhou diante dele e lhe perguntou: Bom Mestre, que hei de fazer para herdar a vida eterna?

[[v41-10-18]]

^<<v41-10-18,18>>^ Respondeu-lhe Jesus: Por que me chamas bom? ninguém é bom, senão um que é Deus.

[[v41-10-19]]

^<<v41-10-19,19>>^ Sabes os mandamentos: Não matarás; não adulterarás; não furtarás; não dirás falso testemunho; a ninguém defraudarás; honra a teu pai e a tua mãe.

[[v41-10-20]]

^<<v41-10-20,20>>^ Ele, porém, lhe replicou: Mestre, tudo isso tenho guardado desde a minha juventude.

[[v41-10-21]]

^<<v41-10-21,21>>^ E Jesus, olhando para ele, o amou e lhe disse: Uma coisa te falta; vai vende tudo quanto tens e dá-o aos pobres, e terás um tesouro no céu; e vem, segue-me.

[[v41-10-22]]

^<<v41-10-22,22>>^ Mas ele, pesaroso desta palavra, retirou-se triste, porque possuía muitos bens.

[[v41-10-23]]

^<<v41-10-23,23>>^ Então Jesus, olhando em redor, disse aos seus discípulos: Quão dificilmente entrarão no reino de Deus os que têm riquezas!

[[v41-10-24]]

^<<v41-10-24,24>>^ E os discípulos se maravilharam destas suas palavras; mas Jesus, tornando a falar, disse-lhes: Filhos, quão difícil é &#123;para os que confiam nas riquezas&#125; entrar no reino de Deus!

[[v41-10-25]]

^<<v41-10-25,25>>^ É mais fácil um camelo passar pelo fundo de uma agulha, do que entrar um rico no reino de Deus.

[[v41-10-26]]

^<<v41-10-26,26>>^ Com isso eles ficaram sobremaneira maravilhados, dizendo entre si: Quem pode, então, ser salvo?

[[v41-10-27]]

^<<v41-10-27,27>>^ Jesus, fixando os olhos neles, respondeu: Para os homens é impossível, mas não para Deus; porque para Deus tudo é possível.

[[v41-10-28]]

^<<v41-10-28,28>>^ Pedro começou a dizer-lhe: Eis que nós deixamos tudo e te seguimos.

[[v41-10-29]]

^<<v41-10-29,29>>^ Respondeu Jesus: Em verdade vos digo que ninguém há, que tenha deixado casa, ou irmãos, ou irmãs, ou mãe, ou pai, ou filhos, ou campos, por amor de mim e do evangelho,

[[v41-10-30]]

^<<v41-10-30,30>>^ que não receba cem vezes tanto, já neste tempo, em casas, e irmãos, e irmãs, e mães, e filhos, e campos, com perseguições; e no mundo vindouro a vida eterna.

[[v41-10-31]]

^<<v41-10-31,31>>^ Mas muitos que são primeiros serão últimos; e muitos que são últimos serão primeiros.

[[v41-10-32]]

^<<v41-10-32,32>>^ Ora, estavam a caminho, subindo para Jerusalém; e Jesus ia adiante deles, e eles se maravilhavam e o seguiam atemorizados. De novo tomou consigo os doze e começou a contar-lhes as coisas que lhe haviam de sobrevir,

[[v41-10-33]]

^<<v41-10-33,33>>^ dizendo: Eis que subimos a Jerusalém, e o Filho do homem será entregue aos principais sacerdotes e aos escribas; e eles o condenarão à morte, e o entregarão aos gentios;

[[v41-10-34]]

^<<v41-10-34,34>>^ e hão de escarnecê-lo e cuspir nele, e açoitá-lo, e matá-lo; e depois de três dias ressurgirá.

[[v41-10-35]]

^<<v41-10-35,35>>^ Nisso aproximaram-se dele Tiago e João, filhos de Zebedeu, dizendo-lhe: Mestre, queremos que nos faças o que te pedirmos.

[[v41-10-36]]

^<<v41-10-36,36>>^ Ele, pois, lhes perguntou: Que quereis que eu vos faça?

[[v41-10-37]]

^<<v41-10-37,37>>^ Responderam-lhe: Concede-nos que na tua glória nos sentemos, um à tua direita, e outro à tua esquerda.

[[v41-10-38]]

^<<v41-10-38,38>>^ Mas Jesus lhes disse: Não sabeis o que pedis; podeis beber o cálice que eu bebo, e ser batizados no batismo em que eu sou batizado?

[[v41-10-39]]

^<<v41-10-39,39>>^ E lhe responderam: Podemos. Mas Jesus lhes disse: O cálice que eu bebo, haveis de bebê-lo, e no batismo em que eu sou batizado, haveis de ser batizados;

[[v41-10-40]]

^<<v41-10-40,40>>^ mas o sentar-se à minha direita, ou à minha esquerda, não me pertence concedê-lo; mas isso é para aqueles a quem está reservado.

[[v41-10-41]]

^<<v41-10-41,41>>^ E ouvindo isso os dez, começaram a indignar-se contra Tiago e João.

[[v41-10-42]]

^<<v41-10-42,42>>^ Então Jesus chamou-os para junto de si e lhes disse: Sabeis que os que são reconhecidos como governadores dos gentios, deles se assenhoreiam, e que sobre eles os seus grandes exercem autoridade.

[[v41-10-43]]

^<<v41-10-43,43>>^ Mas entre vós não será assim; antes, qualquer que entre vós quiser tornar-se grande, será esse o que vos sirva;

[[v41-10-44]]

^<<v41-10-44,44>>^ e qualquer que entre vós quiser ser o primeiro, será servo de todos.

[[v41-10-45]]

^<<v41-10-45,45>>^ Pois também o Filho do homem não veio para ser servido, mas para servir, e para dar a sua vida em resgate de muitos.

[[v41-10-46]]

^<<v41-10-46,46>>^ Depois chegaram a Jericó. E, ao sair ele de Jericó com seus discípulos e uma grande multidão, estava sentado junto do caminho um mendigo cego, Bartimeu filho de Timeu.

[[v41-10-47]]

^<<v41-10-47,47>>^ Este, quando ouviu que era Jesus, o nazareno, começou a clamar, dizendo: Jesus, Filho de Davi, tem compaixão de mim!

[[v41-10-48]]

^<<v41-10-48,48>>^ E muitos o repreendiam, para que se calasse; mas ele clamava ainda mais: Filho de Davi, tem compaixão de mim.

[[v41-10-49]]

^<<v41-10-49,49>>^ Parou, pois, Jesus e disse: Chamai-o. E chamaram o cego, dizendo-lhe: Tem bom ânimo; levanta-te, ele te chama.

[[v41-10-50]]

^<<v41-10-50,50>>^ Nisto, lançando de si a sua capa, de um salto se levantou e foi ter com Jesus.

[[v41-10-51]]

^<<v41-10-51,51>>^ Perguntou-lhe o cego: Que queres que te faça? Respondeu-lhe o cego: Mestre, que eu veja.

[[v41-10-52]]

^<<v41-10-52,52>>^ Disse-lhe Jesus: Vai, a tua fé te salvou. E imediatamente recuperou a vista, e foi seguindo pelo caminho.

'''

xref:041-marcos/041-marcos-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-marcos/041-marcos-011.adoc#v41-11-0[Próximo Capítulo &#62;]