include::./index.adoc[]

[[v41-6-0]]
=== Marcos, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-6-1]]

^<<v41-6-1,1>>^ Saiu Jesus dali, e foi para a sua terra, e os seus discípulos o seguiam.

[[v41-6-2]]

^<<v41-6-2,2>>^ Ora, chegando o sábado, começou a ensinar na sinagoga; e muitos, ao ouvi-lo, se maravilhavam, dizendo: Donde lhe vêm estas coisas? e que sabedoria é esta que lhe é dada? e como se fazem tais milagres por suas mãos?

[[v41-6-3]]

^<<v41-6-3,3>>^ Não é este o carpinteiro, filho de Maria, irmão de Tiago, de José, de Judas e de Simão? e não estão aqui entre nós suas irmãs? E escandalizavam-se dele.

[[v41-6-4]]

^<<v41-6-4,4>>^ Então Jesus lhes dizia: Um profeta não fica sem honra senão na sua terra, entre os seus parentes, e na sua própria casa.

[[v41-6-5]]

^<<v41-6-5,5>>^ E não podia fazer ali nenhum milagre, a não ser curar alguns poucos enfermos, impondo-lhes as mãos.

[[v41-6-6]]

^<<v41-6-6,6>>^ E admirou-se da incredulidade deles. Em seguida percorria as aldeias circunvizinhas, ensinando.

[[v41-6-7]]

^<<v41-6-7,7>>^ E chamou a si os doze, e começou a enviá-los a dois e dois, e dava-lhes poder sobre os espíritos imundos;

[[v41-6-8]]

^<<v41-6-8,8>>^ ordenou-lhes que nada levassem para o caminho, senão apenas um bordão; nem pão, nem alforje, nem dinheiro no cinto;

[[v41-6-9]]

^<<v41-6-9,9>>^ mas que fossem calçados de sandálias, e que não vestissem duas túnicas.

[[v41-6-10]]

^<<v41-6-10,10>>^ Dizia-lhes mais: Onde quer que entrardes numa casa, ficai nela até sairdes daquele lugar.

[[v41-6-11]]

^<<v41-6-11,11>>^ E se qualquer lugar não vos receber, nem os homens vos ouvirem, saindo dali, sacudi o pó que estiver debaixo dos vossos pés, em testemunho conta eles.

[[v41-6-12]]

^<<v41-6-12,12>>^ Então saíram e pregaram que todos se arrependessem;

[[v41-6-13]]

^<<v41-6-13,13>>^ e expulsavam muitos demônios, e ungiam muitos enfermos com óleo, e os curavam.

[[v41-6-14]]

^<<v41-6-14,14>>^ E soube disso o rei Herodes &#123;porque o nome de Jesus se tornara célebre&#125;, e disse: João, o Batista, ressuscitou dos mortos; e por isso estes poderes milagrosos operam nele.

[[v41-6-15]]

^<<v41-6-15,15>>^ Mas outros diziam: É Elias. E ainda outros diziam: É profeta como um dos profetas.

[[v41-6-16]]

^<<v41-6-16,16>>^ Herodes, porém, ouvindo isso, dizia: É João, aquele a quem eu mandei degolar: ele ressuscitou.

[[v41-6-17]]

^<<v41-6-17,17>>^ Porquanto o próprio Herodes mandara prender a João, e encerrá-lo maniatado no cárcere, por causa de Herodias, mulher de seu irmão Filipe; porque ele se havia casado com ela.

[[v41-6-18]]

^<<v41-6-18,18>>^ Pois João dizia a Herodes: Não te é lícito ter a mulher de teu irmão.

[[v41-6-19]]

^<<v41-6-19,19>>^ Por isso Herodias lhe guardava rancor e queria matá-lo, mas não podia;

[[v41-6-20]]

^<<v41-6-20,20>>^ porque Herodes temia a João, sabendo que era varão justo e santo, e o guardava em segurança; e, ao ouvi-lo, ficava muito perplexo, contudo de boa mente o escutava.

[[v41-6-21]]

^<<v41-6-21,21>>^ Chegado, porém, um dia oportuno quando Herodes no seu aniversário natalício ofereceu um banquete aos grandes da sua corte, aos principais da Galiléia,

[[v41-6-22]]

^<<v41-6-22,22>>^ entrou a filha da mesma Herodias e, dançando, agradou a Herodes e aos convivas. Então o rei disse à jovem: Pede-me o que quiseres, e eu to darei.

[[v41-6-23]]

^<<v41-6-23,23>>^ E jurou-lhe, dizendo: Tudo o que me pedires te darei, ainda que seja metade do meu reino.

[[v41-6-24]]

^<<v41-6-24,24>>^ Tendo ela saído, perguntou a sua mãe: Que pedirei? Ela respondeu: A cabeça de João, o Batista.

[[v41-6-25]]

^<<v41-6-25,25>>^ E tornando logo com pressa à presença do rei, pediu, dizendo: Quero que imediatamente me dês num prato a cabeça de João, o Batista.

[[v41-6-26]]

^<<v41-6-26,26>>^ Ora, entristeceu-se muito o rei; todavia, por causa dos seus juramentos e por causa dos que estavam à mesa, não lha quis negar.

[[v41-6-27]]

^<<v41-6-27,27>>^ O rei, pois, enviou logo um soldado da sua guarda com ordem de trazer a cabeça de João. Então ele foi e o degolou no cárcere,

[[v41-6-28]]

^<<v41-6-28,28>>^ e trouxe a cabeça num prato e a deu à jovem, e a jovem a deu à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ Quando os seus discípulos ouviram isso, vieram, tomaram o seu corpo e o puseram num sepulcro.

[[v41-6-30]]

^<<v41-6-30,30>>^ Reuniram-se os apóstolos com Jesus e contaram-lhe tudo o que tinham feito e ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ Ao que ele lhes disse: Vinde vós, à parte, para um lugar deserto, e descansai um pouco. Porque eram muitos os que vinham e iam, e não tinham tempo nem para comer.

[[v41-6-32]]

^<<v41-6-32,32>>^ Retiraram-se, pois, no barco para um lugar deserto, à parte.

[[v41-6-33]]

^<<v41-6-33,33>>^ Muitos, porém, os viram partir, e os reconheceram; e para lá correram a pé de todas as cidades, e ali chegaram primeiro do que eles.

[[v41-6-34]]

^<<v41-6-34,34>>^ E Jesus, ao desembarcar, viu uma grande multidão e compadeceu-se deles, porque eram como ovelhas que não têm pastor; e começou a ensinar-lhes muitas coisas.

[[v41-6-35]]

^<<v41-6-35,35>>^ Estando a hora já muito adiantada, aproximaram-se dele seus discípulos e disseram: O lugar é deserto, e a hora já está muito adiantada;

[[v41-6-36]]

^<<v41-6-36,36>>^ despede-os, para que vão aos sítios e às aldeias, em redor, e comprem para si o que comer.

[[v41-6-37]]

^<<v41-6-37,37>>^ Ele, porém, lhes respondeu: Dai-lhes vós de comer. Então eles lhe perguntaram: Havemos de ir comprar duzentos denários de pão e dar-lhes de comer?

[[v41-6-38]]

^<<v41-6-38,38>>^ Ao que ele lhes disse: Quantos pães tendes? Ide ver. E, tendo-se informado, responderam: Cinco pães e dois peixes.

[[v41-6-39]]

^<<v41-6-39,39>>^ Então lhes ordenou que a todos fizessem reclinar-se, em grupos, sobre a relva verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ E reclinaram-se em grupos de cem e de cinqüenta.

[[v41-6-41]]

^<<v41-6-41,41>>^ E tomando os cinco pães e os dois peixes, e erguendo os olhos ao céu, os abençoou; partiu os pães e os entregava a seus discípulos para lhos servirem; também repartiu os dois peixes por todos.

[[v41-6-42]]

^<<v41-6-42,42>>^ E todos comeram e se fartaram.

[[v41-6-43]]

^<<v41-6-43,43>>^ Em seguida, recolheram doze cestos cheios dos pedaços de pão e de peixe.

[[v41-6-44]]

^<<v41-6-44,44>>^ Ora, os que comeram os pães eram cinco mil homens.

[[v41-6-45]]

^<<v41-6-45,45>>^ Logo em seguida obrigou os seus discípulos a entrar no barco e passar adiante, para o outro lado, a Betsaida, enquanto ele despedia a multidão.

[[v41-6-46]]

^<<v41-6-46,46>>^ E, tendo-a despedido, foi ao monte para orar.

[[v41-6-47]]

^<<v41-6-47,47>>^ Chegada a tardinha, estava o barco no meio do mar, e ele sozinho em terra.

[[v41-6-48]]

^<<v41-6-48,48>>^ E, vendo-os fatigados a remar, porque o vento lhes era contrário, pela quarta vigília da noite, foi ter com eles, andando sobre o mar; e queria passar-lhes adiante;

[[v41-6-49]]

^<<v41-6-49,49>>^ eles, porém, ao vê-lo andando sobre o mar, pensaram que era um fantasma e gritaram;

[[v41-6-50]]

^<<v41-6-50,50>>^ porque todos o viram e se assustaram; mas ele imediatamente falou com eles e disse-lhes: Tende ânimo; sou eu; não temais.

[[v41-6-51]]

^<<v41-6-51,51>>^ E subiu para junto deles no barco, e o vento cessou; e ficaram, no seu íntimo, grandemente pasmados;

[[v41-6-52]]

^<<v41-6-52,52>>^ pois não tinham compreendido o milagre dos pães, antes o seu coração estava endurecido.

[[v41-6-53]]

^<<v41-6-53,53>>^ E, terminada a travessia, chegaram à terra em Genezaré, e ali atracaram.

[[v41-6-54]]

^<<v41-6-54,54>>^ Logo que desembarcaram, o povo reconheceu a Jesus;

[[v41-6-55]]

^<<v41-6-55,55>>^ e correndo eles por toda aquela região, começaram a levar nos leitos os que se achavam enfermos, para onde ouviam dizer que ele estava.

[[v41-6-56]]

^<<v41-6-56,56>>^ Onde quer, pois, que entrava, fosse nas aldeias, nas cidades ou nos campos, apresentavam os enfermos nas praças, e rogavam-lhe que os deixasse tocar ao menos a orla do seu manto; e todos os que a tocavam ficavam curados.

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]