include::./index.adoc[]

[[v41-1-0]]
=== Marcos, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-1-1]]

^<<v41-1-1,1>>^ Princípio do evangelho de Jesus Cristo, Filho de Deus.

[[v41-1-2]]

^<<v41-1-2,2>>^ Conforme está escrito no profeta Isaías: Eis que envio ante a tua face o meu mensageiro, que há de preparar o teu caminho;

[[v41-1-3]]

^<<v41-1-3,3>>^ voz do que clama no deserto: Preparai o caminho do Senhor, endireitai as suas veredas;

[[v41-1-4]]

^<<v41-1-4,4>>^ assim apareceu João, o Batista, no deserto, pregando o batismo de arrependimento para remissão dos pecados.

[[v41-1-5]]

^<<v41-1-5,5>>^ E saíam a ter com ele toda a terra da Judéia, e todos os moradores de Jerusalém; e eram por ele batizados no rio Jordão, confessando os seus pecados.

[[v41-1-6]]

^<<v41-1-6,6>>^ Ora, João usava uma veste de pêlos de camelo, e um cinto de couro em torno de seus lombos, e comia gafanhotos e mel silvestre.

[[v41-1-7]]

^<<v41-1-7,7>>^ E pregava, dizendo: Após mim vem aquele que é mais poderoso do que eu, de quem não sou digno de, inclinando-me, desatar a correia das alparcas.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu vos batizei em água; ele, porém, vos batizará no Espírito Santo.

[[v41-1-9]]

^<<v41-1-9,9>>^ E aconteceu naqueles dias que veio Jesus de Nazaré da Galiléia, e foi batizado por João no Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ E logo, quando saía da água, viu os céus se abrirem, e o Espírito, qual pomba, a descer sobre ele;

[[v41-1-11]]

^<<v41-1-11,11>>^ e ouviu-se dos céus esta voz: Tu és meu Filho amado; em ti me comprazo.

[[v41-1-12]]

^<<v41-1-12,12>>^ Imediatamente o Espírito o impeliu para o deserto.

[[v41-1-13]]

^<<v41-1-13,13>>^ E esteve no deserto quarenta dias sentado tentado por Satanás; estava entre as feras, e os anjos o serviam.

[[v41-1-14]]

^<<v41-1-14,14>>^ Ora, depois que João foi entregue, veio Jesus para a Galiléia pregando o evangelho de Deus

[[v41-1-15]]

^<<v41-1-15,15>>^ e dizendo: O tempo está cumprido, e é chegado o reino de Deus. Arrependei-vos, e crede no evangelho.

[[v41-1-16]]

^<<v41-1-16,16>>^ E, andando junto do mar da Galiléia, viu a Simão, e a André, irmão de Simão, os quais lançavam a rede ao mar, pois eram pescadores.

[[v41-1-17]]

^<<v41-1-17,17>>^ Disse-lhes Jesus: Vinde após mim, e eu farei que vos torneis pescadores de homens.

[[v41-1-18]]

^<<v41-1-18,18>>^ Então eles, deixando imediatamente as suas redes, o seguiram.

[[v41-1-19]]

^<<v41-1-19,19>>^ E ele, passando um pouco adiante, viu Tiago, filho de Zebedeu, e João, seu irmão, que estavam no barco, consertando as redes,

[[v41-1-20]]

^<<v41-1-20,20>>^ e logo os chamou; eles, deixando seu pai Zebedeu no barco com os empregados, o seguiram.

[[v41-1-21]]

^<<v41-1-21,21>>^ Entraram em Cafarnaum; e, logo no sábado, indo ele à sinagoga, pôs-se a ensinar.

[[v41-1-22]]

^<<v41-1-22,22>>^ E maravilhavam-se da sua doutrina, porque os ensinava como tendo autoridade, e não como os escribas.

[[v41-1-23]]

^<<v41-1-23,23>>^ Ora, estava na sinagoga um homem possesso dum espírito imundo, o qual gritou:

[[v41-1-24]]

^<<v41-1-24,24>>^ Que temos nós contigo, Jesus, nazareno? Vieste destruir-nos? Bem sei quem és: o Santo de Deus.

[[v41-1-25]]

^<<v41-1-25,25>>^ Mas Jesus o repreendeu, dizendo: Cala-te, e sai dele.

[[v41-1-26]]

^<<v41-1-26,26>>^ Então o espírito imundo, convulsionando-o e clamando com grande voz, saiu dele.

[[v41-1-27]]

^<<v41-1-27,27>>^ E todos se maravilharam a ponto de perguntarem entre si, dizendo: Que é isto? Uma nova doutrina com autoridade! Pois ele ordena aos espíritos imundos, e eles lhe obedecem!

[[v41-1-28]]

^<<v41-1-28,28>>^ E logo correu a sua fama por toda a região da Galiléia.

[[v41-1-29]]

^<<v41-1-29,29>>^ Em seguida, saiu da sinagoga e foi a casa de Simão e André com Tiago e João.

[[v41-1-30]]

^<<v41-1-30,30>>^ A sogra de Simão estava de cama com febre, e logo lhe falaram a respeito dela.

[[v41-1-31]]

^<<v41-1-31,31>>^ Então Jesus, chegando-se e tomando-a pela mão, a levantou; e a febre a deixou, e ela os servia.

[[v41-1-32]]

^<<v41-1-32,32>>^ Sendo já tarde, tendo-se posto o sol, traziam-lhe todos os enfermos, e os endemoninhados;

[[v41-1-33]]

^<<v41-1-33,33>>^ e toda a cidade estava reunida à porta;

[[v41-1-34]]

^<<v41-1-34,34>>^ e ele curou muitos doentes atacados de diversas moléstias, e expulsou muitos demônios; mas não permitia que os demônios falassem, porque o conheciam.

[[v41-1-35]]

^<<v41-1-35,35>>^ De madrugada, ainda bem escuro, levantou-se, saiu e foi a um lugar deserto, e ali orava.

[[v41-1-36]]

^<<v41-1-36,36>>^ Foram, pois, Simão e seus companheiros procurá-lo;

[[v41-1-37]]

^<<v41-1-37,37>>^ quando o encontraram, disseram-lhe: Todos te buscam.

[[v41-1-38]]

^<<v41-1-38,38>>^ Respondeu-lhes Jesus: Vamos a outras partes, às povoações vizinhas, para que eu pregue ali também; pois para isso é que vim.

[[v41-1-39]]

^<<v41-1-39,39>>^ Foi, então, por toda a Galiléia, pregando nas sinagogas deles e expulsando os demônios.

[[v41-1-40]]

^<<v41-1-40,40>>^ E veio a ele um leproso que, de joelhos, lhe rogava, dizendo: Se quiseres, bem podes tornar-me limpo.

[[v41-1-41]]

^<<v41-1-41,41>>^ Jesus, pois, compadecido dele, estendendo a mão, tocou-o e disse-lhe: Quero; sê limpo.

[[v41-1-42]]

^<<v41-1-42,42>>^ Imediatamente desapareceu dele a lepra e ficou limpo.

[[v41-1-43]]

^<<v41-1-43,43>>^ E Jesus, advertindo-o secretamente, logo o despediu,

[[v41-1-44]]

^<<v41-1-44,44>>^ dizendo-lhe: Olha, não digas nada a ninguém; mas vai, mostra-te ao sacerdote e oferece pela tua purificação o que Moisés determinou, para lhes servir de testemunho.

[[v41-1-45]]

^<<v41-1-45,45>>^ Ele, porém, saindo dali, começou a publicar o caso por toda parte e a divulgá-lo, de modo que Jesus já não podia entrar abertamente numa cidade, mas conservava-se fora em lugares desertos; e de todos os lados iam ter com ele.

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]