include::./index.adoc[]

[[v41-4-0]]
=== Marcos, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-4-1]]

^<<v41-4-1,1>>^ Outra vez começou a ensinar à beira do mar. E reuniu-se a ele tão grande multidão que ele entrou num barco e sentou-se nele, sobre o mar; e todo o povo estava em terra junto do mar.

[[v41-4-2]]

^<<v41-4-2,2>>^ Então lhes ensinava muitas coisas por parábolas, e lhes dizia no seu ensino:

[[v41-4-3]]

^<<v41-4-3,3>>^ Ouvi: Eis que o semeador saiu a semear;

[[v41-4-4]]

^<<v41-4-4,4>>^ e aconteceu que, quando semeava, uma parte da semente caiu à beira do caminho, e vieram as aves e a comeram.

[[v41-4-5]]

^<<v41-4-5,5>>^ Outra caiu no solo pedregoso, onde não havia muita terra: e logo nasceu, porque não tinha terra profunda;

[[v41-4-6]]

^<<v41-4-6,6>>^ mas, saindo o sol, queimou-se; e, porque não tinha raiz, secou-se.

[[v41-4-7]]

^<<v41-4-7,7>>^ E outra caiu entre espinhos; e cresceram os espinhos, e a sufocaram; e não deu fruto.

[[v41-4-8]]

^<<v41-4-8,8>>^ Mas outras caíram em boa terra e, vingando e crescendo, davam fruto; e um grão produzia trinta, outro sessenta, e outro cem.

[[v41-4-9]]

^<<v41-4-9,9>>^ E disse-lhes: Quem tem ouvidos para ouvir, ouça.

[[v41-4-10]]

^<<v41-4-10,10>>^ Quando se achou só, os que estavam ao redor dele, com os doze, interrogaram-no acerca da parábola.

[[v41-4-11]]

^<<v41-4-11,11>>^ E ele lhes disse: A vós é confiado o mistério do reino de Deus, mas aos de fora tudo se lhes diz por parábolas;

[[v41-4-12]]

^<<v41-4-12,12>>^ para que vendo, vejam, e não percebam; e ouvindo, ouçam, e não entendam; para que não se convertam e sejam perdoados.

[[v41-4-13]]

^<<v41-4-13,13>>^ Disse-lhes ainda: Não percebeis esta parábola? como pois entendereis todas as parábolas?

[[v41-4-14]]

^<<v41-4-14,14>>^ O semeador semeia a palavra.

[[v41-4-15]]

^<<v41-4-15,15>>^ E os que estão junto do caminho são aqueles em quem a palavra é semeada; mas, tendo-a eles ouvido, vem logo Satanás e tira a palavra que neles foi semeada.

[[v41-4-16]]

^<<v41-4-16,16>>^ Do mesmo modo, aqueles que foram semeados nos lugares pedregosos são os que, ouvindo a palavra, imediatamente com alegria a recebem;

[[v41-4-17]]

^<<v41-4-17,17>>^ mas não têm raiz em si mesmos, antes são de pouca duração; depois, sobrevindo tribulação ou perseguição por causa da palavra, logo se escandalizam.

[[v41-4-18]]

^<<v41-4-18,18>>^ Outros ainda são aqueles que foram semeados entre os espinhos; estes são os que ouvem a palavra;

[[v41-4-19]]

^<<v41-4-19,19>>^ mas os cuidados do mundo, a sedução das riquezas e a cobiça doutras coisas, entrando, sufocam a palavra, e ela fica infrutífera.

[[v41-4-20]]

^<<v41-4-20,20>>^ Aqueles outros que foram semeados em boa terra são os que ouvem a palavra e a recebem, e dão fruto, a trinta, a sessenta, e a cem, por um.

[[v41-4-21]]

^<<v41-4-21,21>>^ Disse-lhes mais: Vem porventura a candeia para se meter debaixo do alqueire, ou debaixo da cama? não é antes para se colocar no velador?

[[v41-4-22]]

^<<v41-4-22,22>>^ Porque nada está encoberto senão para ser manifesto; e nada foi escondido senão para vir à luz.

[[v41-4-23]]

^<<v41-4-23,23>>^ Se alguém tem ouvidos para ouvir, ouça.

[[v41-4-24]]

^<<v41-4-24,24>>^ Também lhes disse: Atendei ao que ouvis. Com a medida com que medis vos medirão a vós, e ainda se vos acrescentará.

[[v41-4-25]]

^<<v41-4-25,25>>^ Pois ao que tem, ser-lhe-á dado; e ao que não tem, até aquilo que tem ser-lhe-á tirado.

[[v41-4-26]]

^<<v41-4-26,26>>^ Disse também: O reino de Deus é assim como se um homem lançasse semente à terra,

[[v41-4-27]]

^<<v41-4-27,27>>^ e dormisse e se levantasse de noite e de dia, e a semente brotasse e crescesse, sem ele saber como.

[[v41-4-28]]

^<<v41-4-28,28>>^ A terra por si mesma produz fruto, primeiro a erva, depois a espiga, e por último o grão cheio na espiga.

[[v41-4-29]]

^<<v41-4-29,29>>^ Mas assim que o fruto amadurecer, logo lhe mete a foice, porque é chegada a ceifa.

[[v41-4-30]]

^<<v41-4-30,30>>^ Disse ainda: A que assemelharemos o reino de Deus? ou com que parábola o representaremos?

[[v41-4-31]]

^<<v41-4-31,31>>^ É como um grão de mostarda que, quando se semeia, é a menor de todas as sementes que há na terra;

[[v41-4-32]]

^<<v41-4-32,32>>^ mas, tendo sido semeado, cresce e faz-se a maior de todas as hortaliças e cria grandes ramos, de tal modo que as aves do céu podem aninhar-se à sua sombra.

[[v41-4-33]]

^<<v41-4-33,33>>^ E com muitas parábolas tais lhes dirigia a palavra, conforme podiam compreender.

[[v41-4-34]]

^<<v41-4-34,34>>^ E sem parábola não lhes falava; mas em particular explicava tudo a seus discípulos.

[[v41-4-35]]

^<<v41-4-35,35>>^ Naquele dia, quando já era tarde, disse-lhes: Passemos para o outro lado.

[[v41-4-36]]

^<<v41-4-36,36>>^ E eles, deixando a multidão, o levaram consigo, assim como estava, no barco; e havia com ele também outros barcos.

[[v41-4-37]]

^<<v41-4-37,37>>^ E se levantou grande tempestade de vento, e as ondas batiam dentro do barco, de modo que já se enchia.

[[v41-4-38]]

^<<v41-4-38,38>>^ Ele, porém, estava na popa dormindo sobre a almofada; e despertaram-no, e lhe perguntaram: Mestre, não se te dá que pereçamos?

[[v41-4-39]]

^<<v41-4-39,39>>^ E ele, levantando-se, repreendeu o vento, e disse ao mar: Cala-te, aquieta-te. E cessou o vento, e fez-se grande bonança.

[[v41-4-40]]

^<<v41-4-40,40>>^ Então lhes perguntou: Por que sois assim tímidos? Ainda não tendes fé?

[[v41-4-41]]

^<<v41-4-41,41>>^ Encheram-se de grande temor, e diziam uns aos outros: Quem, porventura, é este, que até o vento e o mar lhe obedecem?

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]