include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-9-1]]

^<<v41-9-1,1>>^ Disse-lhes mais: Em verdade vos digo que, dos que aqui estão, alguns há que de modo nenhum provarão a morte até que vejam o reino de Deus já chegando com poder.

[[v41-9-2]]

^<<v41-9-2,2>>^ Seis dias depois tomou Jesus consigo a Pedro, a Tiago, e a João, e os levou à parte sós, a um alto monte; e foi transfigurado diante deles;

[[v41-9-3]]

^<<v41-9-3,3>>^ as suas vestes tornaram-se resplandecentes, extremamente brancas, tais como nenhum lavandeiro sobre a terra as poderia branquear.

[[v41-9-4]]

^<<v41-9-4,4>>^ E apareceu-lhes Elias com Moisés, e falavam com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Pedro, tomando a palavra, disse a Jesus: Mestre, bom é estarmos aqui; façamos, pois, três cabanas, uma para ti, outra para Moisés, e outra para Elias.

[[v41-9-6]]

^<<v41-9-6,6>>^ Pois não sabia o que havia de dizer, porque ficaram atemorizados.

[[v41-9-7]]

^<<v41-9-7,7>>^ Nisto veio uma nuvem que os cobriu, e dela saiu uma voz que dizia: Este é o meu Filho amado; a ele ouvi.

[[v41-9-8]]

^<<v41-9-8,8>>^ De repente, tendo olhado em redor, não viram mais a ninguém consigo, senão só a Jesus.

[[v41-9-9]]

^<<v41-9-9,9>>^ Enquanto desciam do monte, ordenou-lhes que a ninguém contassem o que tinham visto, até que o Filho do homem ressurgisse dentre os mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ E eles guardaram o caso em segredo, indagando entre si o que seria o ressurgir dentre os mortos.

[[v41-9-11]]

^<<v41-9-11,11>>^ Então lhe perguntaram: Por que dizem os escribas que é necessário que Elias venha primeiro?

[[v41-9-12]]

^<<v41-9-12,12>>^ Respondeu-lhes Jesus: Na verdade Elias havia de vir primeiro, a restaurar todas as coisas; e como é que está escrito acerca do Filho do homem que ele deva padecer muito a ser aviltado?

[[v41-9-13]]

^<<v41-9-13,13>>^ Digo-vos, porém, que Elias já veio, e fizeram-lhe tudo quanto quiseram, como dele está escrito.

[[v41-9-14]]

^<<v41-9-14,14>>^ Quando chegaram aonde estavam os discípulos, viram ao redor deles uma grande multidão, e alguns escribas a discutirem com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ E logo toda a multidão, vendo a Jesus, ficou grandemente surpreendida; e correndo todos para ele, o saudavam.

[[v41-9-16]]

^<<v41-9-16,16>>^ Perguntou ele aos escribas: Que é que discutis com eles?

[[v41-9-17]]

^<<v41-9-17,17>>^ Respondeu-lhe um dentre a multidão: Mestre, eu te trouxe meu filho, que tem um espírito mudo;

[[v41-9-18]]

^<<v41-9-18,18>>^ e este, onde quer que o apanha, convulsiona-o, de modo que ele espuma, range os dentes, e vai definhando; e eu pedi aos teus discípulos que o expulsassem, e não puderam.

[[v41-9-19]]

^<<v41-9-19,19>>^ Ao que Jesus lhes respondeu: ó geração incrédula! até quando estarei convosco? até quando vos hei de suportar? Trazei-mo.

[[v41-9-20]]

^<<v41-9-20,20>>^ Então lho trouxeram; e quando ele viu a Jesus, o espírito imediatamente o convulsionou; e o endemoninhado, caindo por terra, revolvia-se espumando.

[[v41-9-21]]

^<<v41-9-21,21>>^ E perguntou Jesus ao pai dele: Há quanto tempo sucede-lhe isto? Respondeu ele: Desde a infância;

[[v41-9-22]]

^<<v41-9-22,22>>^ e muitas vezes o tem lançado no fogo, e na água, para o destruir; mas se podes fazer alguma coisa, tem compaixão de nós e ajuda-nos.

[[v41-9-23]]

^<<v41-9-23,23>>^ Ao que lhe disse Jesus: Se podes!-tudo é possível ao que crê.

[[v41-9-24]]

^<<v41-9-24,24>>^ Imediatamente o pai do menino, clamando, &#123;com lágrimas&#125; disse: Creio! Ajuda a minha incredulidade.

[[v41-9-25]]

^<<v41-9-25,25>>^ E Jesus, vendo que a multidão, correndo, se aglomerava, repreendeu o espírito imundo, dizendo: Espírito mudo e surdo, eu te ordeno: Sai dele, e nunca mais entres nele.

[[v41-9-26]]

^<<v41-9-26,26>>^ E ele, gritando, e agitando-o muito, saiu; e ficou o menino como morto, de modo que a maior parte dizia: Morreu.

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus, tomando-o pela mão, o ergueu; e ele ficou em pé.

[[v41-9-28]]

^<<v41-9-28,28>>^ E quando entrou em casa, seus discípulos lhe perguntaram à parte: Por que não pudemos nós expulsá-lo?

[[v41-9-29]]

^<<v41-9-29,29>>^ Respondeu-lhes: Esta casta não sai de modo algum, salvo à força de oração &#123;e jejum.&#125;

[[v41-9-30]]

^<<v41-9-30,30>>^ Depois, tendo partido dali, passavam pela Galiléia, e ele não queria que ninguém o soubesse;

[[v41-9-31]]

^<<v41-9-31,31>>^ porque ensinava a seus discípulos, e lhes dizia: O Filho do homem será entregue nas mãos dos homens, que o matarão; e morto ele, depois de três dias ressurgirá.

[[v41-9-32]]

^<<v41-9-32,32>>^ Mas eles não entendiam esta palavra, e temiam interrogá-lo.

[[v41-9-33]]

^<<v41-9-33,33>>^ Chegaram a Cafarnaum. E estando ele em casa, perguntou-lhes: Que estáveis discutindo pelo caminho?

[[v41-9-34]]

^<<v41-9-34,34>>^ Mas eles se calaram, porque pelo caminho haviam discutido entre si qual deles era o maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ E ele, sentando-se, chamou os doze e lhes disse: se alguém quiser ser o primeiro, será o derradeiro de todos e o servo de todos.

[[v41-9-36]]

^<<v41-9-36,36>>^ Então tomou uma criança, pô-la no meio deles e, abraçando-a, disse-lhes:

[[v41-9-37]]

^<<v41-9-37,37>>^ Qualquer que em meu nome receber uma destas crianças, a mim me recebe; e qualquer que me recebe a mim, recebe não a mim mas àquele que me enviou.

[[v41-9-38]]

^<<v41-9-38,38>>^ Disse-lhe João: Mestre, vimos um homem que em teu nome expulsava demônios, e nós lho proibimos, porque não nos seguia.

[[v41-9-39]]

^<<v41-9-39,39>>^ Jesus, porém, respondeu: Não lho proibais; porque ninguém há que faça milagre em meu nome e possa logo depois falar mal de mim;

[[v41-9-40]]

^<<v41-9-40,40>>^ pois quem não é contra nós, é por nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ Porquanto qualquer que vos der a beber um copo de água em meu nome, porque sois de Cristo, em verdade vos digo que de modo algum perderá a sua recompensa.

[[v41-9-42]]

^<<v41-9-42,42>>^ Mas qualquer que fizer tropeçar um destes pequeninos que crêem em mim, melhor lhe fora que se lhe pendurasse ao pescoço uma pedra de moinho, e que fosse lançado no mar.

[[v41-9-43]]

^<<v41-9-43,43>>^ E se a tua mão te fizer tropeçar, corta-a; melhor é entrares na vida aleijado, do que, tendo duas mãos, ires para o inferno, para o fogo que nunca se apaga.

[[v41-9-44]]

^<<v41-9-44,44>>^ &#123;onde o seu verme não morre, e o fogo não se apaga.&#125;

[[v41-9-45]]

^<<v41-9-45,45>>^ Ou, se o teu pé te fizer tropeçar, corta-o; melhor é entrares coxo na vida, do que, tendo dois pés, seres lançado no inferno.

[[v41-9-46]]

^<<v41-9-46,46>>^ &#123;onde o seu verme não morre, e o fogo não se apaga.&#125;

[[v41-9-47]]

^<<v41-9-47,47>>^ Ou, se o teu olho te fizer tropeçar, lança-o fora; melhor é entrares no reino de Deus com um só olho, do que, tendo dois olhos, seres lançado no inferno.

[[v41-9-48]]

^<<v41-9-48,48>>^ onde o seu verme não morre, e o fogo não se apaga.

[[v41-9-49]]

^<<v41-9-49,49>>^ Porque cada um será salgado com fogo.

[[v41-9-50]]

^<<v41-9-50,50>>^ Bom é o sal; mas, se o sal se tornar insípido, com que o haveis de temperar? Tende sal em vós mesmos, e guardai a paz uns com os outros.

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]