include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-5-1]]

^<<v41-5-1,1>>^ Chegaram então ao outro lado do mar, à terra dos gerasenos.

[[v41-5-2]]

^<<v41-5-2,2>>^ E, logo que Jesus saíra do barco, lhe veio ao encontro, dos sepulcros, um homem com espírito imundo,

[[v41-5-3]]

^<<v41-5-3,3>>^ o qual tinha a sua morada nos sepulcros; e nem ainda com cadeias podia alguém prendê-lo;

[[v41-5-4]]

^<<v41-5-4,4>>^ porque, tendo sido muitas vezes preso com grilhões e cadeias, as cadeias foram por ele feitas em pedaços, e os grilhões em migalhas; e ninguém o podia domar;

[[v41-5-5]]

^<<v41-5-5,5>>^ e sempre, de dia e de noite, andava pelos sepulcros e pelos montes, gritando, e ferindo-se com pedras,

[[v41-5-6]]

^<<v41-5-6,6>>^ Vendo, pois, de longe a Jesus, correu e adorou-o;

[[v41-5-7]]

^<<v41-5-7,7>>^ e, clamando com grande voz, disse: Que tenho eu contigo, Jesus, Filho do Deus Altíssimo? conjuro-te por Deus que não me atormentes.

[[v41-5-8]]

^<<v41-5-8,8>>^ Pois Jesus lhe dizia: Sai desse homem, espírito imundo.

[[v41-5-9]]

^<<v41-5-9,9>>^ E perguntou-lhe: Qual é o teu nome? Respondeu-lhe ele: Legião é o meu nome, porque somos muitos.

[[v41-5-10]]

^<<v41-5-10,10>>^ E rogava-lhe muito que não os enviasse para fora da região.

[[v41-5-11]]

^<<v41-5-11,11>>^ Ora, andava ali pastando no monte uma grande manada de porcos.

[[v41-5-12]]

^<<v41-5-12,12>>^ Rogaram-lhe, pois, os demônios, dizendo: Manda-nos para aqueles porcos, para que entremos neles.

[[v41-5-13]]

^<<v41-5-13,13>>^ E ele lho permitiu. Saindo, então, os espíritos imundos, entraram nos porcos; e precipitou-se a manada, que era de uns dois mil, pelo despenhadeiro no mar, onde todos se afogaram.

[[v41-5-14]]

^<<v41-5-14,14>>^ Nisso fugiram aqueles que os apascentavam, e o anunciaram na cidade e nos campos; e muitos foram ver o que era aquilo que tinha acontecido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Chegando-se a Jesus, viram o endemoninhado, o que tivera a legião, sentado, vestido, e em perfeito juízo; e temeram.

[[v41-5-16]]

^<<v41-5-16,16>>^ E os que tinham visto aquilo contaram-lhes como havia acontecido ao endemoninhado, e acerca dos porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ Então começaram a rogar-lhe que se retirasse dos seus termos.

[[v41-5-18]]

^<<v41-5-18,18>>^ E, entrando ele no barco, rogava-lhe o que fora endemoninhado que o deixasse estar com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ Jesus, porém, não lho permitiu, mas disse-lhe: Vai para tua casa, para os teus, e anuncia-lhes o quanto o Senhor te fez, e como teve misericórdia de ti.

[[v41-5-20]]

^<<v41-5-20,20>>^ Ele se retirou, pois, e começou a publicar em Decápolis tudo quanto lhe fizera Jesus; e todos se admiravam.

[[v41-5-21]]

^<<v41-5-21,21>>^ Tendo Jesus passado de novo no barco para o outro lado, ajuntou-se a ele uma grande multidão; e ele estava à beira do mar.

[[v41-5-22]]

^<<v41-5-22,22>>^ Chegou um dos chefes da sinagoga, chamado Jairo e, logo que viu a Jesus, lançou-se-lhe aos pés.

[[v41-5-23]]

^<<v41-5-23,23>>^ e lhe rogava com instância, dizendo: Minha filhinha está nas últimas; rogo-te que venhas e lhe imponhas as mãos para que sare e viva.

[[v41-5-24]]

^<<v41-5-24,24>>^ Jesus foi com ele, e seguia-o uma grande multidão, que o apertava.

[[v41-5-25]]

^<<v41-5-25,25>>^ Ora, certa mulher, que havia doze anos padecia de uma hemorragia,

[[v41-5-26]]

^<<v41-5-26,26>>^ e que tinha sofrido bastante às mãos de muitos médicos, e despendido tudo quanto possuía sem nada aproveitar, antes indo a pior,

[[v41-5-27]]

^<<v41-5-27,27>>^ tendo ouvido falar a respeito de Jesus, veio por detrás, entre a multidão, e tocou-lhe o manto;

[[v41-5-28]]

^<<v41-5-28,28>>^ porque dizia: Se tão-somente tocar-lhe as vestes, ficaria curada.

[[v41-5-29]]

^<<v41-5-29,29>>^ E imediatamente cessou a sua hemorragia; e sentiu no corpo estar já curada do seu mal.

[[v41-5-30]]

^<<v41-5-30,30>>^ E logo Jesus, percebendo em si mesmo que saíra dele poder, virou-se no meio da multidão e perguntou: Quem me tocou as vestes?

[[v41-5-31]]

^<<v41-5-31,31>>^ Responderam-lhe os seus discípulos: Vês que a multidão te aperta, e perguntas: Quem me tocou?

[[v41-5-32]]

^<<v41-5-32,32>>^ Mas ele olhava em redor para ver a que isto fizera.

[[v41-5-33]]

^<<v41-5-33,33>>^ Então a mulher, atemorizada e trêmula, cônscia do que nela se havia operado, veio e prostrou-se diante dele, e declarou-lhe toda a verdade.

[[v41-5-34]]

^<<v41-5-34,34>>^ Disse-lhe ele: Filha, a tua fé te salvou; vai-te em paz, e fica livre desse teu mal.

[[v41-5-35]]

^<<v41-5-35,35>>^ Enquanto ele ainda falava, chegaram pessoas da casa do chefe da sinagoga, a quem disseram: A tua filha já morreu; por que ainda incomodas o Mestre?

[[v41-5-36]]

^<<v41-5-36,36>>^ O que percebendo Jesus, disse ao chefe da sinagoga: Não temas, crê somente.

[[v41-5-37]]

^<<v41-5-37,37>>^ E não permitiu que ninguém o acompanhasse, senão Pedro, Tiago, e João, irmão de Tiago.

[[v41-5-38]]

^<<v41-5-38,38>>^ Quando chegaram a casa do chefe da sinagoga, viu Jesus um alvoroço, e os que choravam e faziam grande pranto.

[[v41-5-39]]

^<<v41-5-39,39>>^ E, entrando, disse-lhes: Por que fazeis alvoroço e chorais? a menina não morreu, mas dorme.

[[v41-5-40]]

^<<v41-5-40,40>>^ E riam-se dele; porém ele, tendo feito sair a todos, tomou consigo o pai e a mãe da menina, e os que com ele vieram, e entrou onde a menina estava.

[[v41-5-41]]

^<<v41-5-41,41>>^ E, tomando a mão da menina, disse-lhe: Talita cumi, que, traduzido, é: Menina, a ti te digo, levanta-te.

[[v41-5-42]]

^<<v41-5-42,42>>^ Imediatamente a menina se levantou, e pôs-se a andar, pois tinha doze anos. E logo foram tomados de grande espanto.

[[v41-5-43]]

^<<v41-5-43,43>>^ Então ordenou-lhes expressamente que ninguém o soubesse; e mandou que lhe dessem de comer.

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]