include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-12-1]]

^<<v41-12-1,1>>^ Então começou Jesus a falar-lhes por parábolas. Um homem plantou uma vinha, cercou-a com uma sebe, cavou um lagar, e edificou uma torre; depois arrendou-a a uns lavradores e ausentou-se do país.

[[v41-12-2]]

^<<v41-12-2,2>>^ No tempo próprio, enviou um servo aos lavradores para que deles recebesse do fruto da vinha.

[[v41-12-3]]

^<<v41-12-3,3>>^ Mas estes, apoderando-se dele, o espancaram e o mandaram embora de mãos vazias.

[[v41-12-4]]

^<<v41-12-4,4>>^ E tornou a enviar-lhes outro servo; e a este feriram na cabeça e o ultrajaram.

[[v41-12-5]]

^<<v41-12-5,5>>^ Então enviou ainda outro, e a este mataram; e a outros muitos, dos quais a uns espancaram e a outros mataram.

[[v41-12-6]]

^<<v41-12-6,6>>^ Ora, tinha ele ainda um, o seu filho amado; a este lhes enviou por último, dizendo: A meu filho terão respeito.

[[v41-12-7]]

^<<v41-12-7,7>>^ Mas aqueles lavradores disseram entre si: Este é o herdeiro; vinde, matemo-lo, e a herança será nossa.

[[v41-12-8]]

^<<v41-12-8,8>>^ E, agarrando-o, o mataram, e o lançaram fora da vinha.

[[v41-12-9]]

^<<v41-12-9,9>>^ Que fará, pois, o senhor da vinha? Virá e destruirá os lavradores, e dará a vinha a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Nunca lestes esta escritura: A pedra que os edificadores rejeitaram, essa foi posta como pedra angular;

[[v41-12-11]]

^<<v41-12-11,11>>^ pelo Senhor foi feito isso, e é maravilhoso aos nossos olhos?

[[v41-12-12]]

^<<v41-12-12,12>>^ Procuravam então prendê-lo, mas temeram a multidão, pois perceberam que contra eles proferira essa parábola; e, deixando-o, se retiraram.

[[v41-12-13]]

^<<v41-12-13,13>>^ Enviaram-lhe então alguns dos fariseus e dos herodianos, para que o apanhassem em alguma palavra.

[[v41-12-14]]

^<<v41-12-14,14>>^ Aproximando-se, pois, disseram-lhe: Mestre, sabemos que és verdadeiro, e de ninguém se te dá; porque não olhas à aparência dos homens, mas ensinas segundo a verdade o caminho de Deus; é lícito dar tributo a César, ou não? Daremos, ou não daremos?

[[v41-12-15]]

^<<v41-12-15,15>>^ Mas Jesus, percebendo a hipocrisia deles, respondeu-lhes: Por que me experimentais? trazei-me um denário para que eu o veja.

[[v41-12-16]]

^<<v41-12-16,16>>^ E eles lho trouxeram. Perguntou-lhes Jesus: De quem é esta imagem e inscrição? Responderam-lhe: De César.

[[v41-12-17]]

^<<v41-12-17,17>>^ Disse-lhes Jesus: Dai, pois, a César o que é de César, e a Deus o que é de Deus. E admiravam-se dele.

[[v41-12-18]]

^<<v41-12-18,18>>^ Então se aproximaram dele alguns dos saduceus, que dizem não haver ressurreição, e lhe perguntaram, dizendo:

[[v41-12-19]]

^<<v41-12-19,19>>^ Mestre, Moisés nos deixou escrito que se morrer alguém, deixando mulher sem deixar filhos, o irmão dele case com a mulher, e suscite descendência ao irmão.

[[v41-12-20]]

^<<v41-12-20,20>>^ Ora, havia sete irmãos; o primeiro casou-se e morreu sem deixar descendência;

[[v41-12-21]]

^<<v41-12-21,21>>^ o segundo casou-se com a viúva, e morreu, não deixando descendência; e da mesma forma, o terceiro; e assim os sete, e não deixaram descendência.

[[v41-12-22]]

^<<v41-12-22,22>>^ Depois de todos, morreu também a mulher.

[[v41-12-23]]

^<<v41-12-23,23>>^ Na ressurreição, de qual deles será ela esposa, pois os sete por esposa a tiveram?

[[v41-12-24]]

^<<v41-12-24,24>>^ Respondeu-lhes Jesus: Porventura não errais vós em razão de não compreenderdes as Escrituras nem o poder de Deus?

[[v41-12-25]]

^<<v41-12-25,25>>^ Porquanto, ao ressuscitarem dos mortos, nem se casam, nem se dão em casamento; pelo contrário, são como os anjos nos céus.

[[v41-12-26]]

^<<v41-12-26,26>>^ Quanto aos mortos, porém, serem ressuscitados, não lestes no livro de Moisés, onde se fala da sarça, como Deus lhe disse: Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó?

[[v41-12-27]]

^<<v41-12-27,27>>^ Ora, ele não é Deus de mortos, mas de vivos. Estais em grande erro.

[[v41-12-28]]

^<<v41-12-28,28>>^ Aproximou-se dele um dos escribas que os ouvira discutir e, percebendo que lhes havia respondido bem, perguntou-lhe: Qual é o primeiro de todos os mandamentos?

[[v41-12-29]]

^<<v41-12-29,29>>^ Respondeu Jesus: O primeiro é: Ouve, Israel, o Senhor nosso Deus é o único Senhor.

[[v41-12-30]]

^<<v41-12-30,30>>^ Amarás, pois, ao Senhor teu Deus de todo o teu coração, de toda a tua alma, de todo o teu entendimento e de todas as tuas forças.

[[v41-12-31]]

^<<v41-12-31,31>>^ E o segundo é este: Amarás ao teu próximo como a ti mesmo. Não há outro mandamento maior do que esses.

[[v41-12-32]]

^<<v41-12-32,32>>^ Ao que lhe disse o escriba: Muito bem, Mestre; com verdade disseste que ele é um, e fora dele não há outro;

[[v41-12-33]]

^<<v41-12-33,33>>^ e que amá-lo de todo o coração, de todo o entendimento e de todas as forças, e amar o próximo como a si mesmo, é mais do que todos os holocaustos e sacrifícios.

[[v41-12-34]]

^<<v41-12-34,34>>^ E Jesus, vendo que havia respondido sabiamente, disse-lhe: Não estás longe do reino de Deus. E ninguém ousava mais interrogá-lo.

[[v41-12-35]]

^<<v41-12-35,35>>^ Por sua vez, Jesus, enquanto ensinava no templo, perguntou: Como é que os escribas dizem que o Cristo é filho de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio Davi falou, movido pelo Espírito Santo: Disse o Senhor ao meu Senhor: Assenta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés.

[[v41-12-37]]

^<<v41-12-37,37>>^ Davi mesmo lhe chama Senhor; como é ele seu filho? E a grande multidão o ouvia com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ E prosseguindo ele no seu ensino, disse: Guardai-vos dos escribas, que gostam de andar com vestes compridas, e das saudações nas praças,

[[v41-12-39]]

^<<v41-12-39,39>>^ e dos primeiros assentos nas sinagogas, e dos primeiros lugares nos banquetes,

[[v41-12-40]]

^<<v41-12-40,40>>^ que devoram as casas das viúvas, e por pretexto fazem longas orações; estes hão de receber muito maior condenação.

[[v41-12-41]]

^<<v41-12-41,41>>^ E sentando-se Jesus defronte do cofre das ofertas, observava como a multidão lançava dinheiro no cofre; e muitos ricos deitavam muito.

[[v41-12-42]]

^<<v41-12-42,42>>^ Vindo, porém, uma pobre viúva, lançou dois leptos, que valiam um quadrante.

[[v41-12-43]]

^<<v41-12-43,43>>^ E chamando ele os seus discípulos, disse-lhes: Em verdade vos digo que esta pobre viúva deu mais do que todos os que deitavam ofertas no cofre;

[[v41-12-44]]

^<<v41-12-44,44>>^ porque todos deram daquilo que lhes sobrava; mas esta, da sua pobreza, deu tudo o que tinha, mesmo todo o seu sustento.

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]