include::./index.adoc[]

[[v41-3-0]]
=== Marcos, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-3-1]]

^<<v41-3-1,1>>^ Outra vez entrou numa sinagoga, e estava ali um homem que tinha uma das mãos atrofiada.

[[v41-3-2]]

^<<v41-3-2,2>>^ E observavam-no para ver se no sábado curaria o homem, a fim de o acusarem.

[[v41-3-3]]

^<<v41-3-3,3>>^ E disse Jesus ao homem que tinha a mão atrofiada: Levanta-te e vem para o meio.

[[v41-3-4]]

^<<v41-3-4,4>>^ Então lhes perguntou: É lícito no sábado fazer bem, ou fazer mal? salvar a vida ou matar? Eles, porém, se calaram.

[[v41-3-5]]

^<<v41-3-5,5>>^ E olhando em redor para eles com indignação, condoendo-se da dureza dos seus corações, disse ao homem: Estende a tua mão. Ele estendeu, e lhe foi restabelecida.

[[v41-3-6]]

^<<v41-3-6,6>>^ E os fariseus, saindo dali, entraram logo em conselho com os herodianos contra ele, para o matarem.

[[v41-3-7]]

^<<v41-3-7,7>>^ Jesus, porém, se retirou com os seus discípulos para a beira do mar; e uma grande multidão dos da Galiléia o seguiu; também da Judéia,

[[v41-3-8]]

^<<v41-3-8,8>>^ e de Jerusalém, da Iduméia e de além do Jordão, e das regiões de Tiro e de Sidom, grandes multidões, ouvindo falar de tudo quanto fazia, vieram ter com ele.

[[v41-3-9]]

^<<v41-3-9,9>>^ Recomendou, pois, a seus discípulos que se lhe preparasse um barquinho, por causa da multidão, para que não o apertasse;

[[v41-3-10]]

^<<v41-3-10,10>>^ porque tinha curado a muitos, de modo que todos quantos tinham algum mal arrojavam-se a ele para lhe tocarem.

[[v41-3-11]]

^<<v41-3-11,11>>^ E os espíritos imundos, quando o viam, prostravam-se diante dele e clamavam, dizendo: Tu és o Filho de Deus.

[[v41-3-12]]

^<<v41-3-12,12>>^ E ele lhes advertia com insistência que não o dessem a conhecer.

[[v41-3-13]]

^<<v41-3-13,13>>^ Depois subiu ao monte, e chamou a si os que ele mesmo queria; e vieram a ele.

[[v41-3-14]]

^<<v41-3-14,14>>^ Então designou doze para que estivessem com ele, e os mandasse a pregar;

[[v41-3-15]]

^<<v41-3-15,15>>^ e para que tivessem autoridade de expulsar os demônios.

[[v41-3-16]]

^<<v41-3-16,16>>^ Designou, pois, os doze, a saber: Simão, a quem pôs o nome de Pedro;

[[v41-3-17]]

^<<v41-3-17,17>>^ Tiago, filho de Zebedeu, e João, irmão de Tiago, aos quais pôs o nome de Boanerges, que significa: Filhos do trovão;

[[v41-3-18]]

^<<v41-3-18,18>>^ André, Filipe, Bartolomeu, Mateus, Tomé, Tiago, filho de Alfeu, Tadeu, Simão, o cananeu,

[[v41-3-19]]

^<<v41-3-19,19>>^ e Judas Iscariotes, aquele que o traiu.

[[v41-3-20]]

^<<v41-3-20,20>>^ Depois entrou numa casa. E afluiu outra vez a multidão, de tal modo que nem podiam comer.

[[v41-3-21]]

^<<v41-3-21,21>>^ Quando os seus ouviram isso, saíram para o prender; porque diziam: Ele está fora de si.

[[v41-3-22]]

^<<v41-3-22,22>>^ E os escribas que tinham descido de Jerusalém diziam: Ele está possesso de Belzebu; e: É pelo príncipe dos demônios que expulsa os demônios.

[[v41-3-23]]

^<<v41-3-23,23>>^ Então Jesus os chamou e lhes disse por parábolas: Como pode Satanás expulsar Satanás?

[[v41-3-24]]

^<<v41-3-24,24>>^ Pois, se um reino se dividir contra si mesmo, tal reino não pode subsistir;

[[v41-3-25]]

^<<v41-3-25,25>>^ ou, se uma casa se dividir contra si mesma, tal casa não poderá subsistir;

[[v41-3-26]]

^<<v41-3-26,26>>^ e se Satanás se tem levantado contra si mesmo, e está dividido, tampouco pode ele subsistir; antes tem fim.

[[v41-3-27]]

^<<v41-3-27,27>>^ Pois ninguém pode entrar na casa do valente e roubar-lhe os bens, se primeiro não amarrar o valente; e então lhe saqueará a casa.

[[v41-3-28]]

^<<v41-3-28,28>>^ Em verdade vos digo: Todos os pecados serão perdoados aos filhos dos homens, bem como todas as blasfêmias que proferirem;

[[v41-3-29]]

^<<v41-3-29,29>>^ mas aquele que blasfemar contra o Espírito Santo, nunca mais terá perdão, mas será réu de pecado eterno.

[[v41-3-30]]

^<<v41-3-30,30>>^ Porquanto eles diziam: Está possesso de um espírito imundo.

[[v41-3-31]]

^<<v41-3-31,31>>^ Chegaram então sua mãe e seus irmãos e, ficando da parte de fora, mandaram chamá-lo.

[[v41-3-32]]

^<<v41-3-32,32>>^ E a multidão estava sentada ao redor dele, e disseram-lhe: Eis que tua mãe e teus irmãos estão lá fora e te procuram.

[[v41-3-33]]

^<<v41-3-33,33>>^ Respondeu-lhes Jesus, dizendo: Quem é minha mãe e meus irmãos!

[[v41-3-34]]

^<<v41-3-34,34>>^ E olhando em redor para os que estavam sentados à roda de si, disse: Eis aqui minha mãe e meus irmãos!

[[v41-3-35]]

^<<v41-3-35,35>>^ Pois aquele que fizer a vontade de Deus, esse é meu irmão, irmã e mãe.

'''

xref:041-marcos/041-marcos-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-marcos/041-marcos-004.adoc#v41-4-0[Próximo Capítulo &#62;]