include::./index.adoc[]

[[v41-11-0]]
=== Marcos, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-11-1]]

^<<v41-11-1,1>>^ Ora, quando se aproximavam de Jerusalém, de Betfagé e de Betânia, junto do Monte das Oliveiras, enviou Jesus dois dos seus discípulos

[[v41-11-2]]

^<<v41-11-2,2>>^ e disse-lhes: Ide à aldeia que está defronte de vós; e logo que nela entrardes, encontrareis preso um jumentinho, em que ainda ninguém montou; desprendei-o e trazei-o.

[[v41-11-3]]

^<<v41-11-3,3>>^ E se alguém vos perguntar: Por que fazeis isso? respondei: O Senhor precisa dele, e logo tornará a enviá-lo para aqui.

[[v41-11-4]]

^<<v41-11-4,4>>^ Foram, pois, e acharam o jumentinho preso ao portão do lado de fora na rua, e o desprenderam.

[[v41-11-5]]

^<<v41-11-5,5>>^ E alguns dos que ali estavam lhes perguntaram: Que fazeis, desprendendo o jumentinho?

[[v41-11-6]]

^<<v41-11-6,6>>^ Responderam como Jesus lhes tinha mandado; e lho deixaram levar.

[[v41-11-7]]

^<<v41-11-7,7>>^ Então trouxeram a Jesus o jumentinho e lançaram sobre ele os seus mantos; e Jesus montou nele.

[[v41-11-8]]

^<<v41-11-8,8>>^ Muitos também estenderam pelo caminho os seus mantos, e outros, ramagens que tinham cortado nos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ E tanto os que o precediam como os que o seguiam, clamavam: Hosana! bendito o que vem em nome do Senhor!

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito o reino que vem, o reino de nosso pai Davi! Hosana nas alturas!

[[v41-11-11]]

^<<v41-11-11,11>>^ Tendo Jesus entrado em Jerusalém, foi ao templo; e tendo observado tudo em redor, como já fosse tarde, saiu para Betânia com os doze.

[[v41-11-12]]

^<<v41-11-12,12>>^ No dia seguinte, depois de saírem de Betânia teve fome,

[[v41-11-13]]

^<<v41-11-13,13>>^ e avistando de longe uma figueira que tinha folhas, foi ver se, porventura, acharia nela alguma coisa; e chegando a ela, nada achou senão folhas, porque não era tempo de figos.

[[v41-11-14]]

^<<v41-11-14,14>>^ E Jesus, falando, disse à figueira: Nunca mais coma alguém fruto de ti. E seus discípulos ouviram isso.

[[v41-11-15]]

^<<v41-11-15,15>>^ Chegaram, pois, a Jerusalém. E entrando ele no templo, começou a expulsar os que ali vendiam e compravam; e derribou as mesas dos cambistas, e as cadeiras dos que vendiam pombas;

[[v41-11-16]]

^<<v41-11-16,16>>^ e não consentia que ninguém atravessasse o templo levando qualquer utensílio;

[[v41-11-17]]

^<<v41-11-17,17>>^ e ensinava, dizendo-lhes: Não está escrito: A minha casa será chamada casa de oração para todas as nações? Vós, porém, a tendes feito covil de salteadores.

[[v41-11-18]]

^<<v41-11-18,18>>^ Ora, os principais sacerdotes e os escribas ouviram isto, e procuravam um modo de o matar; pois o temiam, porque toda a multidão se maravilhava da sua doutrina.

[[v41-11-19]]

^<<v41-11-19,19>>^ Ao cair da tarde, saíam da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ Quando passavam na manhã seguinte, viram que a figueira tinha secado desde as raízes.

[[v41-11-21]]

^<<v41-11-21,21>>^ Então Pedro, lembrando-se, disse-lhe: Olha, Mestre, secou-se a figueira que amaldiçoaste.

[[v41-11-22]]

^<<v41-11-22,22>>^ Respondeu-lhes Jesus: Tende fé em Deus.

[[v41-11-23]]

^<<v41-11-23,23>>^ Em verdade vos digo que qualquer que disser a este monte: Ergue-te e lança-te no mar; e não duvidar em seu coração, mas crer que se fará aquilo que diz, assim lhe será feito.

[[v41-11-24]]

^<<v41-11-24,24>>^ Por isso vos digo que tudo o que pedirdes em oração, crede que o recebereis, e tê-lo-eis.

[[v41-11-25]]

^<<v41-11-25,25>>^ Quando estiverdes orando, perdoai, se tendes alguma coisa contra alguém, para que também vosso Pai que está no céu, vos perdoe as vossas ofensas.

[[v41-11-26]]

^<<v41-11-26,26>>^ &#123;Mas, se vós não perdoardes, também vosso Pai, que está no céu, não vos perdoará as vossas ofensas.&#125;

[[v41-11-27]]

^<<v41-11-27,27>>^ Vieram de novo a Jerusalém. E andando Jesus pelo templo, aproximaram-se dele os principais sacerdotes, os escribas e os anciãos,

[[v41-11-28]]

^<<v41-11-28,28>>^ que lhe perguntaram: Com que autoridade fazes tu estas coisas? ou quem te deu autoridade para fazê-las?

[[v41-11-29]]

^<<v41-11-29,29>>^ Respondeu-lhes Jesus: Eu vos perguntarei uma coisa; respondei-me, pois, e eu vos direi com que autoridade faço estas coisas.

[[v41-11-30]]

^<<v41-11-30,30>>^ O batismo de João era do céu, ou dos homens? respondei-me.

[[v41-11-31]]

^<<v41-11-31,31>>^ Ao que eles arrazoavam entre si: Se dissermos: Do céu, ele dirá: Então por que não o crestes?

[[v41-11-32]]

^<<v41-11-32,32>>^ Mas diremos, porventura: Dos homens?-É que temiam o povo; porque todos verdadeiramente tinham a João como profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Responderam, pois, a Jesus: Não sabemos. Replicou-lhes ele: Nem eu vos digo com que autoridade faço estas coisas.

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]