include::./index.adoc[]

[[v41-8-0]]
=== Marcos, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-8-1]]

^<<v41-8-1,1>>^ Naqueles dias, havendo de novo uma grande multidão, e não tendo o que comer, chamou Jesus os discípulos e disse-lhes:

[[v41-8-2]]

^<<v41-8-2,2>>^ Tenho compaixão da multidão, porque já faz três dias que eles estão comigo, e não têm o que comer.

[[v41-8-3]]

^<<v41-8-3,3>>^ Se eu os mandar em jejum para suas casas, desfalecerão no caminho; e alguns deles vieram de longe.

[[v41-8-4]]

^<<v41-8-4,4>>^ E seus discípulos lhe responderam: Donde poderá alguém satisfazê-los de pão aqui no deserto?

[[v41-8-5]]

^<<v41-8-5,5>>^ Perguntou-lhes Jesus: Quantos pães tendes? Responderam: Sete.

[[v41-8-6]]

^<<v41-8-6,6>>^ Logo mandou ao povo que se sentasse no chão; e tomando os sete pães e havendo dado graças, partiu-os e os entregava a seus discípulos para que os distribuíssem; e eles os distribuíram pela multidão.

[[v41-8-7]]

^<<v41-8-7,7>>^ Tinham também alguns peixinhos, os quais ele abençoou, e mandou que estes também fossem distribuídos.

[[v41-8-8]]

^<<v41-8-8,8>>^ Comeram, pois, e se fartaram; e dos pedaços que sobejavam levantaram sete alcofas.

[[v41-8-9]]

^<<v41-8-9,9>>^ Ora, eram cerca de quatro mil homens. E Jesus os despediu.

[[v41-8-10]]

^<<v41-8-10,10>>^ E, entrando logo no barco com seus discípulos, foi para as regiões de Dalmanuta.

[[v41-8-11]]

^<<v41-8-11,11>>^ Saíram os fariseus e começaram a discutir com ele, pedindo-lhe um sinal do céu, para o experimentarem.

[[v41-8-12]]

^<<v41-8-12,12>>^ Ele, suspirando profundamente em seu espírito, disse: Por que pede esta geração um sinal? Em verdade vos digo que a esta geração não será dado sinal algum.

[[v41-8-13]]

^<<v41-8-13,13>>^ E, deixando-os, tornou a embarcar e foi para o outro lado.

[[v41-8-14]]

^<<v41-8-14,14>>^ Ora, eles se esqueceram de levar pão, e no barco não tinham consigo senão um pão.

[[v41-8-15]]

^<<v41-8-15,15>>^ E Jesus ordenou-lhes, dizendo: Olhai, guardai-vos do fermento dos fariseus e do fermento de Herodes.

[[v41-8-16]]

^<<v41-8-16,16>>^ Pelo que eles arrazoavam entre si porque não tinham pão.

[[v41-8-17]]

^<<v41-8-17,17>>^ E Jesus, percebendo isso, disse-lhes: Por que arrazoais por não terdes pão? não compreendeis ainda, nem entendeis? tendes o vosso coração endurecido?

[[v41-8-18]]

^<<v41-8-18,18>>^ Tendo olhos, não vedes? e tendo ouvidos, não ouvis? e não vos lembrais?

[[v41-8-19]]

^<<v41-8-19,19>>^ Quando parti os cinco pães para os cinco mil, quantos cestos cheios de pedaços levantastes? Responderam-lhe: Doze.

[[v41-8-20]]

^<<v41-8-20,20>>^ E quando parti os sete para os quatro mil, quantas alcofas cheias de pedaços levantastes? Responderam-lhe: Sete.

[[v41-8-21]]

^<<v41-8-21,21>>^ E ele lhes disse: Não entendeis ainda?

[[v41-8-22]]

^<<v41-8-22,22>>^ Então chegaram a Betsaída. E trouxeram-lhe um cego, e rogaram-lhe que o tocasse.

[[v41-8-23]]

^<<v41-8-23,23>>^ Jesus, pois, tomou o cego pela mão, e o levou para fora da aldeia; e cuspindo-lhe nos olhos, e impondo-lhe as mãos, perguntou-lhe: Vês alguma coisa?

[[v41-8-24]]

^<<v41-8-24,24>>^ E, levantando ele os olhos, disse: Estou vendo os homens; porque como árvores os vejo andando.

[[v41-8-25]]

^<<v41-8-25,25>>^ Então tornou a pôr-lhe as mãos sobre os olhos; e ele, olhando atentamente, ficou restabelecido, pois já via nitidamente todas as coisas.

[[v41-8-26]]

^<<v41-8-26,26>>^ Depois o mandou para casa, dizendo: Mas não entres na aldeia.

[[v41-8-27]]

^<<v41-8-27,27>>^ E saiu Jesus com os seus discípulos para as aldeias de Cesaréia de Filipe, e no caminho interrogou os discípulos, dizendo: Quem dizem os homens que eu sou?

[[v41-8-28]]

^<<v41-8-28,28>>^ Responderam-lhe eles: Uns dizem: João, o Batista; outros: Elias; e ainda outros: Algum dos profetas.

[[v41-8-29]]

^<<v41-8-29,29>>^ Então lhes perguntou: Mas vós, quem dizeis que eu sou? Respondendo, Pedro lhe disse: Tu és o Cristo.

[[v41-8-30]]

^<<v41-8-30,30>>^ E ordenou-lhes Jesus que a ninguém dissessem aquilo a respeito dele.

[[v41-8-31]]

^<<v41-8-31,31>>^ Começou então a ensinar-lhes que era necessário que o Filho do homem padecesse muitas coisas, que fosse rejeitado pelos anciãos e principais sacerdotes e pelos escribas, que fosse morto, e que depois de três dias ressurgisse.

[[v41-8-32]]

^<<v41-8-32,32>>^ E isso dizia abertamente. Ao que Pedro, tomando-o à parte, começou a repreendê-lo.

[[v41-8-33]]

^<<v41-8-33,33>>^ Mas ele, virando-se olhando para seus discípulos, repreendeu a Pedro, dizendo: Para trás de mim, Satanás; porque não cuidas das coisas que são de Deus, mas sim das que são dos homens.

[[v41-8-34]]

^<<v41-8-34,34>>^ E chamando a si a multidão com os discípulos, disse-lhes: Se alguém quer vir após mim, negue-se a si mesmo, tome a sua cruz, e siga-me.

[[v41-8-35]]

^<<v41-8-35,35>>^ Pois quem quiser salvar a sua vida, perdê-la-á; mas quem perder a sua vida por amor de mim e do evangelho, salvá-la-á.

[[v41-8-36]]

^<<v41-8-36,36>>^ Pois que aproveita ao homem ganhar o mundo inteiro e perder a sua vida?

[[v41-8-37]]

^<<v41-8-37,37>>^ Ou que diria o homem em troca da sua vida?

[[v41-8-38]]

^<<v41-8-38,38>>^ Porquanto, qualquer que, entre esta geração adúltera e pecadora, se envergonhar de mim e das minhas palavras, também dele se envergonhará o Filho do homem quando vier na glória de seu Pai com os santos anjos.

'''

xref:041-marcos/041-marcos-007.adoc#v41-7-0[&#60; Capítulo Anterior] | <<v41-8-0,Topo>> | xref:041-marcos/041-marcos-009.adoc#v41-9-0[Próximo Capítulo &#62;]