include::./index.adoc[]

[[v41-16-0]]
=== Marcos, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-16-1]]

^<<v41-16-1,1>>^ Ora, passado o sábado, Maria Madalena, Maria, mãe de Tiago, e Salomé, compraram aromas para irem ungi-lo.

[[v41-16-2]]

^<<v41-16-2,2>>^ E, no primeiro dia da semana, foram ao sepulcro muito cedo, ao levantar do sol.

[[v41-16-3]]

^<<v41-16-3,3>>^ E diziam umas às outras: Quem nos revolverá a pedra da porta do sepulcro?

[[v41-16-4]]

^<<v41-16-4,4>>^ Mas, levantando os olhos, notaram que a pedra, que era muito grande, já estava revolvida;

[[v41-16-5]]

^<<v41-16-5,5>>^ e entrando no sepulcro, viram um moço sentado à direita, vestido de alvo manto; e ficaram atemorizadas.

[[v41-16-6]]

^<<v41-16-6,6>>^ Ele, porém, lhes disse: Não vos atemorizeis; buscais a Jesus, o nazareno, que foi crucificado; ele ressurgiu; não está aqui; eis o lugar onde o puseram.

[[v41-16-7]]

^<<v41-16-7,7>>^ Mas ide, dizei a seus discípulos, e a Pedro, que ele vai adiante de vós para a Galiléia; ali o vereis, como ele vos disse.

[[v41-16-8]]

^<<v41-16-8,8>>^ E, saindo elas, fugiram do sepulcro, porque estavam possuídas de medo e assombro; e não disseram nada a ninguém, porque temiam.

[[v41-16-9]]

^<<v41-16-9,9>>^ Ora, havendo Jesus ressurgido cedo no primeiro dia da semana, apareceu primeiramente a Maria Madalena, da qual tinha expulsado sete demônios.

[[v41-16-10]]

^<<v41-16-10,10>>^ Foi ela anunciá-lo aos que haviam andado com ele, os quais estavam tristes e chorando;

[[v41-16-11]]

^<<v41-16-11,11>>^ e ouvindo eles que vivia, e que tinha sido visto por ela, não o creram.

[[v41-16-12]]

^<<v41-16-12,12>>^ Depois disso manifestou-se sob outra forma a dois deles que iam de caminho para o campo,

[[v41-16-13]]

^<<v41-16-13,13>>^ os quais foram anunciá-lo aos outros; mas nem a estes deram crédito.

[[v41-16-14]]

^<<v41-16-14,14>>^ Por último, então, apareceu aos onze, estando eles reclinados à mesa, e lançou-lhes em rosto a sua incredulidade e dureza de coração, por não haverem dado crédito aos que o tinham visto já ressurgido.

[[v41-16-15]]

^<<v41-16-15,15>>^ E disse-lhes: Ide por todo o mundo, e pregai o evangelho a toda criatura.

[[v41-16-16]]

^<<v41-16-16,16>>^ Quem crer e for batizado será salvo; mas quem não crer será condenado.

[[v41-16-17]]

^<<v41-16-17,17>>^ E estes sinais acompanharão aos que crerem: em meu nome expulsarão demônios; falarão novas línguas;

[[v41-16-18]]

^<<v41-16-18,18>>^ pegarão em serpentes; e se beberem alguma coisa mortífera, não lhes fará dano algum; e porão as mãos sobre os enfermos, e estes serão curados.

[[v41-16-19]]

^<<v41-16-19,19>>^ Ora, o Senhor, depois de lhes ter falado, foi recebido no céu, e assentou-se à direita de Deus.

[[v41-16-20]]

^<<v41-16-20,20>>^ Eles, pois, saindo, pregaram por toda parte, cooperando com eles o Senhor, e confirmando a palavra com os sinais que os acompanhavam.

'''

xref:041-marcos/041-marcos-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-lucas/042-lucas-001.adoc#v42-1-0[Próximo Capítulo &#62;]