include::./index.adoc[]

[[v41-15-0]]
=== Marcos, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-15-1]]

^<<v41-15-1,1>>^ Logo de manhã tiveram conselho os principais sacerdotes com os anciãos, os escribas e todo o sinédrio; e maniatando a Jesus, o levaram e o entregaram a Pilatos.

[[v41-15-2]]

^<<v41-15-2,2>>^ Pilatos lhe perguntou: És tu o rei dos judeus? Respondeu-lhe Jesus: É como dizes.

[[v41-15-3]]

^<<v41-15-3,3>>^ e os principais dos sacerdotes o acusavam de muitas coisas.

[[v41-15-4]]

^<<v41-15-4,4>>^ Tornou Pilatos a interrogá-lo, dizendo: Não respondes nada? Vê quantas acusações te fazem.

[[v41-15-5]]

^<<v41-15-5,5>>^ Mas Jesus nada mais respondeu, de maneira que Pilatos se admirava.

[[v41-15-6]]

^<<v41-15-6,6>>^ Ora, por ocasião da festa costumava soltar-lhes um preso qualquer que eles pedissem.

[[v41-15-7]]

^<<v41-15-7,7>>^ E havia um, chamado Barrabás, preso com outros sediciosos, os quais num motim haviam cometido um homicídio.

[[v41-15-8]]

^<<v41-15-8,8>>^ E a multidão subiu e começou a pedir o que lhe costumava fazer.

[[v41-15-9]]

^<<v41-15-9,9>>^ Ao que Pilatos lhes perguntou: Quereis que vos solte o rei dos judeus?

[[v41-15-10]]

^<<v41-15-10,10>>^ Pois ele sabia que por inveja os principais sacerdotes lho haviam entregado.

[[v41-15-11]]

^<<v41-15-11,11>>^ Mas os principais sacerdotes incitaram a multidão a pedir que lhes soltasse antes a Barrabás.

[[v41-15-12]]

^<<v41-15-12,12>>^ E Pilatos, tornando a falar, perguntou-lhes: Que farei então daquele a quem chamais reis dos judeus?

[[v41-15-13]]

^<<v41-15-13,13>>^ Novamente clamaram eles: Crucifica-o!

[[v41-15-14]]

^<<v41-15-14,14>>^ Disse-lhes Pilatos: Mas que mal fez ele? Ao que eles clamaram ainda mais: Crucifica-o!

[[v41-15-15]]

^<<v41-15-15,15>>^ Então Pilatos, querendo satisfazer a multidão, soltou-lhe Barrabás; e tendo mandado açoitar a Jesus, o entregou para ser crucificado.

[[v41-15-16]]

^<<v41-15-16,16>>^ Os soldados, pois, levaram-no para dentro, ao pátio, que é o pretório, e convocaram toda a corte;

[[v41-15-17]]

^<<v41-15-17,17>>^ vestiram-no de púrpura e puseram-lhe na cabeça uma coroa de espinhos que haviam tecido;

[[v41-15-18]]

^<<v41-15-18,18>>^ e começaram a saudá-lo: Salve, rei dos judeus!

[[v41-15-19]]

^<<v41-15-19,19>>^ Davam-lhe com uma cana na cabeça, cuspiam nele e, postos de joelhos, o adoravam.

[[v41-15-20]]

^<<v41-15-20,20>>^ Depois de o terem assim escarnecido, despiram-lhe a púrpura, e lhe puseram as vestes. Então o levaram para fora, a fim de o crucificarem.

[[v41-15-21]]

^<<v41-15-21,21>>^ E obrigaram certo Simão, cireneu, pai de Alexandre e de Rufo, que por ali passava, vindo do campo, a carregar-lhe a cruz.

[[v41-15-22]]

^<<v41-15-22,22>>^ Levaram-no, pois, ao lugar do Gólgota, que quer dizer, lugar da Caveira.

[[v41-15-23]]

^<<v41-15-23,23>>^ E ofereciam-lhe vinho misturado com mirra; mas ele não o tomou.

[[v41-15-24]]

^<<v41-15-24,24>>^ Então o crucificaram, e repartiram entre si as vestes dele, lançando sortes sobre elas para ver o que cada um levaria.

[[v41-15-25]]

^<<v41-15-25,25>>^ E era a hora terceira quando o crucificaram.

[[v41-15-26]]

^<<v41-15-26,26>>^ Por cima dele estava escrito o título da sua acusação: O REI DOS JUDEUS.

[[v41-15-27]]

^<<v41-15-27,27>>^ Também, com ele, crucificaram dois salteadores, um à sua direita, e outro à esquerda.

[[v41-15-28]]

^<<v41-15-28,28>>^ &#123;E cumpriu-se a escritura que diz: E com os malfeitores foi contado.&#125;

[[v41-15-29]]

^<<v41-15-29,29>>^ E os que iam passando blasfemavam dele, meneando a cabeça e dizendo: Ah! tu que destróis o santuário e em três dias o reedificas.

[[v41-15-30]]

^<<v41-15-30,30>>^ salva-te a ti mesmo, descendo da cruz.

[[v41-15-31]]

^<<v41-15-31,31>>^ De igual modo também os principais sacerdotes, com os escribas, escarnecendo-o, diziam entre si: A outros salvou; a si mesmo não pode salvar;

[[v41-15-32]]

^<<v41-15-32,32>>^ desça agora da cruz o Cristo, o rei de Israel, para que vejamos e creiamos, Também os que com ele foram crucificados o injuriavam.

[[v41-15-33]]

^<<v41-15-33,33>>^ E, chegada a hora sexta, houve trevas sobre a terra, até a hora nona.

[[v41-15-34]]

^<<v41-15-34,34>>^ E, à hora nona, bradou Jesus em alta voz: Eloí, Eloí, lamá, sabactani? que, traduzido, é: Deus meu, Deus meu, por que me desamparaste?

[[v41-15-35]]

^<<v41-15-35,35>>^ Alguns dos que ali estavam, ouvindo isso, diziam: Eis que chama por Elias.

[[v41-15-36]]

^<<v41-15-36,36>>^ Correu um deles, ensopou uma esponja em vinagre e, pondo-a numa cana, dava-lhe de beber, dizendo: Deixai, vejamos se Elias virá tirá-lo.

[[v41-15-37]]

^<<v41-15-37,37>>^ Mas Jesus, dando um grande brado, expirou.

[[v41-15-38]]

^<<v41-15-38,38>>^ Então o véu do santuário se rasgou em dois, de alto a baixo.

[[v41-15-39]]

^<<v41-15-39,39>>^ Ora, o centurião, que estava defronte dele, vendo-o assim expirar, disse: Verdadeiramente este homem era filho de Deus.

[[v41-15-40]]

^<<v41-15-40,40>>^ Também ali estavam algumas mulheres olhando de longe, entre elas Maria Madalena, Maria, mãe de Tiago o Menor e de José, e Salomé;

[[v41-15-41]]

^<<v41-15-41,41>>^ as quais o seguiam e o serviam quando ele estava na Galiléia; e muitas outras que tinham subido com ele a Jerusalém.

[[v41-15-42]]

^<<v41-15-42,42>>^ Ao cair da tarde, como era o dia da preparação, isto é, a véspera do sábado,

[[v41-15-43]]

^<<v41-15-43,43>>^ José de Arimatéia, ilustre membro do sinédrio, que também esperava o reino de Deus, cobrando ânimo foi Pilatos e pediu o corpo de Jesus.

[[v41-15-44]]

^<<v41-15-44,44>>^ Admirou-se Pilatos de que já tivesse morrido; e chamando o centurião, perguntou-lhe se, de fato, havia morrido.

[[v41-15-45]]

^<<v41-15-45,45>>^ E, depois que o soube do centurião, cedeu o cadáver a José;

[[v41-15-46]]

^<<v41-15-46,46>>^ o qual, tendo comprado um pano de linho, tirou da cruz o corpo, envolveu-o no pano e o depositou num sepulcro aberto em rocha; e rolou uma pedra para a porta do sepulcro.

[[v41-15-47]]

^<<v41-15-47,47>>^ E Maria Madalena e Maria, mãe de José, observavam onde fora posto.

'''

xref:041-marcos/041-marcos-014.adoc#v41-14-0[&#60; Capítulo Anterior] | <<v41-15-0,Topo>> | xref:041-marcos/041-marcos-016.adoc#v41-16-0[Próximo Capítulo &#62;]