include::./index.adoc[]

[[v41-7-0]]
=== Marcos, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v41-7-1]]

^<<v41-7-1,1>>^ Foram ter com Jesus os fariseus, e alguns dos escribas vindos de Jerusalém,

[[v41-7-2]]

^<<v41-7-2,2>>^ e repararam que alguns dos seus discípulos comiam pão com as mãos impuras, isto é, por lavar.

[[v41-7-3]]

^<<v41-7-3,3>>^ Pois os fariseus, e todos os judeus, guardando a tradição dos anciãos, não comem sem lavar as mãos cuidadosamente;

[[v41-7-4]]

^<<v41-7-4,4>>^ e quando voltam do mercado, se não se purificarem, não comem. E muitas outras coisas há que receberam para observar, como a lavagem de copos, de jarros e de vasos de bronze.

[[v41-7-5]]

^<<v41-7-5,5>>^ Perguntaram-lhe, pois, os fariseus e os escribas: Por que não andam os teus discípulos conforme a tradição dos anciãos, mas comem o pão com as mãos por lavar?

[[v41-7-6]]

^<<v41-7-6,6>>^ Respondeu-lhes: Bem profetizou Isaías acerca de vós, hipócritas, como está escrito: Este povo honra-me com os lábios; o seu coração, porém, está longe de mim;

[[v41-7-7]]

^<<v41-7-7,7>>^ mas em vão me adoram, ensinando doutrinas que são preceitos de homens.

[[v41-7-8]]

^<<v41-7-8,8>>^ Vós deixais o mandamento de Deus, e vos apegais à tradição dos homens.

[[v41-7-9]]

^<<v41-7-9,9>>^ Disse-lhes ainda: Bem sabeis rejeitar o mandamento de Deus, para guardardes a vossa tradição.

[[v41-7-10]]

^<<v41-7-10,10>>^ Pois Moisés disse: Honra a teu pai e a tua mãe; e: Quem maldisser ao pai ou à mãe, certamente morrerá.

[[v41-7-11]]

^<<v41-7-11,11>>^ Mas vós dizeis: Se um homem disser a seu pai ou a sua mãe: Aquilo que poderias aproveitar de mim é Corbã, isto é, oferta ao Senhor,

[[v41-7-12]]

^<<v41-7-12,12>>^ não mais lhe permitis fazer coisa alguma por seu pai ou por sua mãe,

[[v41-7-13]]

^<<v41-7-13,13>>^ invalidando assim a palavra de Deus pela vossa tradição que vós transmitistes; também muitas outras coisas semelhantes fazeis.

[[v41-7-14]]

^<<v41-7-14,14>>^ E chamando a si outra vez a multidão, disse-lhes: Ouvi-me vós todos, e entendei.

[[v41-7-15]]

^<<v41-7-15,15>>^ Nada há fora do homem que, entrando nele, possa contaminá-lo; mas o que sai do homem, isso é que o contamina.

[[v41-7-16]]

^<<v41-7-16,16>>^ &#123;Se alguém tem ouvidos para ouvir, ouça.&#125;

[[v41-7-17]]

^<<v41-7-17,17>>^ Depois, quando deixou a multidão e entrou em casa, os seus discípulos o interrogaram acerca da parábola.

[[v41-7-18]]

^<<v41-7-18,18>>^ Respondeu-lhes ele: Assim também vós estais sem entender? Não compreendeis que tudo o que de fora entra no homem não o pode contaminar,

[[v41-7-19]]

^<<v41-7-19,19>>^ porque não lhe entra no coração, mas no ventre, e é lançado fora? Assim declarou puros todos os alimentos.

[[v41-7-20]]

^<<v41-7-20,20>>^ E prosseguiu: O que sai do homem , isso é que o contamina.

[[v41-7-21]]

^<<v41-7-21,21>>^ Pois é do interior, do coração dos homens, que procedem os maus pensamentos, as prostituições, os furtos, os homicídios, os adultérios,

[[v41-7-22]]

^<<v41-7-22,22>>^ a cobiça, as maldades, o dolo, a libertinagem, a inveja, a blasfêmia, a soberba, a insensatez;

[[v41-7-23]]

^<<v41-7-23,23>>^ todas estas más coisas procedem de dentro e contaminam o homem.

[[v41-7-24]]

^<<v41-7-24,24>>^ Levantando-se dali, foi para as regiões de Tiro e Sidom. E entrando numa casa, não queria que ninguém o soubesse, mas não pode ocultar-se;

[[v41-7-25]]

^<<v41-7-25,25>>^ porque logo, certa mulher, cuja filha estava possessa de um espírito imundo, ouvindo falar dele, veio e prostrou-se-lhe aos pés;

[[v41-7-26]]

^<<v41-7-26,26>>^ &#123;ora, a mulher era grega, de origem siro-fenícia&#125; e rogava-lhe que expulsasse de sua filha o demônio.

[[v41-7-27]]

^<<v41-7-27,27>>^ Respondeu-lhes Jesus: Deixa que primeiro se fartem os filhos; porque não é bom tomar o pão dos filhos e lança-lo aos cachorrinhos.

[[v41-7-28]]

^<<v41-7-28,28>>^ Ela, porém, replicou, e disse-lhe: Sim, Senhor; mas também os cachorrinhos debaixo da mesa comem das migalhas dos filhos.

[[v41-7-29]]

^<<v41-7-29,29>>^ Então ele lhe disse: Por essa palavra, vai; o demônio já saiu de tua filha.

[[v41-7-30]]

^<<v41-7-30,30>>^ E, voltando ela para casa, achou a menina deitada sobre a cama, e que o demônio já havia saído.

[[v41-7-31]]

^<<v41-7-31,31>>^ Tendo Jesus partido das regiões de Tiro, foi por Sidom até o mar da Galiléia, passando pelas regiões de Decápolis.

[[v41-7-32]]

^<<v41-7-32,32>>^ E trouxeram-lhe um surdo, que falava dificilmente; e rogaram-lhe que pusesse a mão sobre ele.

[[v41-7-33]]

^<<v41-7-33,33>>^ Jesus, pois, tirou-o de entre a multidão, à parte, meteu-lhe os dedos nos ouvidos e, cuspindo, tocou-lhe na língua;

[[v41-7-34]]

^<<v41-7-34,34>>^ e erguendo os olhos ao céu, suspirou e disse-lhe: Efatá; isto é Abre-te.

[[v41-7-35]]

^<<v41-7-35,35>>^ E abriram-se-lhe os ouvidos, a prisão da língua se desfez, e falava perfeitamente.

[[v41-7-36]]

^<<v41-7-36,36>>^ Então lhes ordenou Jesus que a ninguém o dissessem; mas, quando mais lho proibia, tanto mais o divulgavam.

[[v41-7-37]]

^<<v41-7-37,37>>^ E se maravilhavam sobremaneira, dizendo: Tudo tem feito bem; faz até os surdos ouvir e os mudos falar.

'''

xref:041-marcos/041-marcos-006.adoc#v41-6-0[&#60; Capítulo Anterior] | <<v41-7-0,Topo>> | xref:041-marcos/041-marcos-008.adoc#v41-8-0[Próximo Capítulo &#62;]