include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-15-1]]

^<<v43-15-1,1>>^ Eu sou a videira verdadeira, e meu Pai é o viticultor.

[[v43-15-2]]

^<<v43-15-2,2>>^ Toda vara em mim que não dá fruto, ele a corta; e toda vara que dá fruto, ele a limpa, para que dê mais fruto.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vós já estais limpos pela palavra que vos tenho falado.

[[v43-15-4]]

^<<v43-15-4,4>>^ Permanecei em mim, e eu permanecerei em vós; como a vara de si mesma não pode dar fruto, se não permanecer na videira, assim também vós, se não permanecerdes em mim.

[[v43-15-5]]

^<<v43-15-5,5>>^ Eu sou a videira; vós sois as varas. Quem permanece em mim e eu nele, esse dá muito fruto; porque sem mim nada podeis fazer.

[[v43-15-6]]

^<<v43-15-6,6>>^ Quem não permanece em mim é lançado fora, como a vara, e seca; tais varas são recolhidas, lançadas no fogo e queimadas.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se vós permanecerdes em mim, e as minhas palavras permanecerem em vós, pedi o que quiserdes, e vos será feito.

[[v43-15-8]]

^<<v43-15-8,8>>^ Nisto é glorificado meu Pai, que deis muito fruto; e assim sereis meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ Como o Pai me amou, assim também eu vos amei; permanecei no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se guardardes os meus mandamentos, permanecereis no meu amor; do mesmo modo que eu tenho guardado os mandamentos de meu Pai, e permaneço no seu amor.

[[v43-15-11]]

^<<v43-15-11,11>>^ Estas coisas vos tenho dito, para que o meu gozo permaneça em vós, e o vosso gozo seja completo.

[[v43-15-12]]

^<<v43-15-12,12>>^ O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem maior amor do que este, de dar alguém a sua vida pelos seus amigos.

[[v43-15-14]]

^<<v43-15-14,14>>^ Vós sois meus amigos, se fizerdes o que eu vos mando.

[[v43-15-15]]

^<<v43-15-15,15>>^ Já não vos chamo servos, porque o servo não sabe o que faz o seu senhor; mas chamei-vos amigos, porque tudo quanto ouvi de meu Pai vos dei a conhecer.

[[v43-15-16]]

^<<v43-15-16,16>>^ Vós não me escolhestes a mim mas eu vos escolhi a vós, e vos designei, para que vades e deis frutos, e o vosso fruto permaneça, a fim de que tudo quanto pedirdes ao Pai em meu nome, ele vo-lo conceda.

[[v43-15-17]]

^<<v43-15-17,17>>^ Isto vos mando: que vos ameis uns aos outros.

[[v43-15-18]]

^<<v43-15-18,18>>^ Se o mundo vos odeia, sabei que, primeiro do que a vós, me odiou a mim.

[[v43-15-19]]

^<<v43-15-19,19>>^ Se fôsseis do mundo, o mundo amaria o que era seu; mas, porque não sois do mundo, antes eu vos escolhi do mundo, por isso é que o mundo vos odeia.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrai-vos da palavra que eu vos disse: Não é o servo maior do que o seu senhor. Se a mim me perseguiram, também vos perseguirão a vós; se guardaram a minha palavra, guardarão também a vossa.

[[v43-15-21]]

^<<v43-15-21,21>>^ Mas tudo isto vos farão por causa do meu nome, porque não conhecem aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Se eu não viera e não lhes falara, não teriam pecado; agora, porém, não têm desculpa do seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Aquele que me odeia a mim, odeia também a meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu entre eles não tivesse feito tais obras, quais nenhum outro fez, não teriam pecado; mas agora, não somente viram, mas também odiaram tanto a mim como a meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Mas isto é para que se cumpra a palavra que está escrita na sua lei: Odiaram-me sem causa.

[[v43-15-26]]

^<<v43-15-26,26>>^ Quando vier o Ajudador, que eu vos enviarei da parte do Pai, o Espírito da verdade, que do Pai procede, esse dará testemunho de mim;

[[v43-15-27]]

^<<v43-15-27,27>>^ e também vós dareis testemunho, porque estais comigo desde o princípio.

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]