include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-8-1]]

^<<v43-8-1,1>>^ Mas Jesus foi para o Monte das Oliveiras.

[[v43-8-2]]

^<<v43-8-2,2>>^ Pela manhã cedo voltou ao templo, e todo o povo vinha ter com ele; e Jesus, sentando-se o ensinava.

[[v43-8-3]]

^<<v43-8-3,3>>^ Então os escribas e fariseus trouxeram-lhe uma mulher apanhada em adultério; e pondo-a no meio,

[[v43-8-4]]

^<<v43-8-4,4>>^ disseram-lhe: Mestre, esta mulher foi apanhada em flagrante adultério.

[[v43-8-5]]

^<<v43-8-5,5>>^ Ora, Moisés nos ordena na lei que as tais sejam apedrejadas. Tu, pois, que dizes?

[[v43-8-6]]

^<<v43-8-6,6>>^ Isto diziam eles, tentando-o, para terem de que o acusar. Jesus, porém, inclinando-se, começou a escrever no chão com o dedo.

[[v43-8-7]]

^<<v43-8-7,7>>^ Mas, como insistissem em perguntar-lhe, ergueu-se e disse-lhes: Aquele dentre vós que está sem pecado seja o primeiro que lhe atire uma pedra.

[[v43-8-8]]

^<<v43-8-8,8>>^ E, tornando a inclinar-se, escrevia na terra.

[[v43-8-9]]

^<<v43-8-9,9>>^ Quando ouviram isto foram saindo um a um, a começar pelos mais velhos, até os últimos; ficou só Jesus, e a mulher ali em pé.

[[v43-8-10]]

^<<v43-8-10,10>>^ Então, erguendo-se Jesus e não vendo a ninguém senão a mulher, perguntou-lhe: Mulher, onde estão aqueles teus acusadores? Ninguém te condenou?

[[v43-8-11]]

^<<v43-8-11,11>>^ Respondeu ela: Ninguém, Senhor. E disse-lhe Jesus: Nem eu te condeno; vai-te, e não peques mais.

[[v43-8-12]]

^<<v43-8-12,12>>^ Então Jesus tornou a falar-lhes, dizendo: Eu sou a luz do mundo; quem me segue de modo algum andará em trevas, mas terá a luz da vida.

[[v43-8-13]]

^<<v43-8-13,13>>^ Disseram-lhe, pois, os fariseus: Tu dás testemunho de ti mesmo; o teu testemunho não é verdadeiro.

[[v43-8-14]]

^<<v43-8-14,14>>^ Respondeu-lhes Jesus: Ainda que eu dou testemunho de mim mesmo, o meu testemunho é verdadeiro; porque sei donde vim, e para onde vou; mas vós não sabeis donde venho, nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vós julgais segundo a carne; eu a ninguém julgo.

[[v43-8-16]]

^<<v43-8-16,16>>^ E, mesmo que eu julgue, o meu juízo é verdadeiro; porque não sou eu só, mas eu e o Pai que me enviou.

[[v43-8-17]]

^<<v43-8-17,17>>^ Ora, na vossa lei está escrito que o testemunho de dois homens é verdadeiro.

[[v43-8-18]]

^<<v43-8-18,18>>^ Sou eu que dou testemunho de mim mesmo, e o Pai que me enviou, também dá testemunho de mim.

[[v43-8-19]]

^<<v43-8-19,19>>^ Perguntavam-lhe, pois: Onde está teu pai? Jesus respondeu: Não me conheceis a mim, nem a meu Pai; se vós me conhecêsseis a mim, também conheceríeis a meu Pai.

[[v43-8-20]]

^<<v43-8-20,20>>^ Essas palavras proferiu Jesus no lugar do tesouro, quando ensinava no templo; e ninguém o prendeu, porque ainda não era chegada a sua hora.

[[v43-8-21]]

^<<v43-8-21,21>>^ Disse-lhes, pois, Jesus outra vez: Eu me retiro; buscar-me-eis, e morrereis no vosso pecado. Para onde eu vou, vós não podeis ir.

[[v43-8-22]]

^<<v43-8-22,22>>^ Então diziam os judeus: Será que ele vai suicidar-se, pois diz: Para onde eu vou, vós não podeis ir?

[[v43-8-23]]

^<<v43-8-23,23>>^ Disse-lhes ele: Vós sois de baixo, eu sou de cima; vós sois deste mundo, eu não sou deste mundo.

[[v43-8-24]]

^<<v43-8-24,24>>^ Por isso vos disse que morrereis em vossos pecados; porque, se não crerdes que eu sou, morrereis em vossos pecados.

[[v43-8-25]]

^<<v43-8-25,25>>^ Perguntavam-lhe então: Quem és tu? Respondeu-lhes Jesus: Exatamente o que venho dizendo que sou.

[[v43-8-26]]

^<<v43-8-26,26>>^ Muitas coisas tenho que dizer e julgar acerca de vós; mas aquele que me enviou é verdadeiro; e o que dele ouvi, isso falo ao mundo.

[[v43-8-27]]

^<<v43-8-27,27>>^ Eles não perceberam que lhes falava do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Prosseguiu, pois, Jesus: Quando tiverdes levantado o Filho do homem, então conhecereis que eu sou, e que nada faço de mim mesmo; mas como o Pai me ensinou, assim falo.

[[v43-8-29]]

^<<v43-8-29,29>>^ E aquele que me enviou está comigo; não me tem deixado só; porque faço sempre o que é do seu agrado.

[[v43-8-30]]

^<<v43-8-30,30>>^ Falando ele estas coisas, muitos creram nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Dizia, pois, Jesus aos judeus que nele creram: Se vós permanecerdes na minha palavra, verdadeiramente sois meus discípulos;

[[v43-8-32]]

^<<v43-8-32,32>>^ e conhecereis a verdade, e a verdade vos libertará.

[[v43-8-33]]

^<<v43-8-33,33>>^ Responderam-lhe: Somos descendentes de Abraão, e nunca fomos escravos de ninguém; como dizes tu: Sereis livres?

[[v43-8-34]]

^<<v43-8-34,34>>^ Replicou-lhes Jesus: Em verdade, em verdade vos digo que todo aquele que comete pecado é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ Ora, o escravo não fica para sempre na casa; o filho fica para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Se, pois, o Filho vos libertar, verdadeiramente sereis livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Bem sei que sois descendência de Abraão; contudo, procurais matar-me, porque a minha palavra não encontra lugar em vós.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo do que vi junto de meu Pai; e vós fazeis o que também ouvistes de vosso pai.

[[v43-8-39]]

^<<v43-8-39,39>>^ Responderam-lhe: Nosso pai é Abraão. Disse-lhes Jesus: Se sois filhos de Abraão, fazei as obras de Abraão.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas agora procurais matar-me, a mim que vos falei a verdade que de Deus ouvi; isso Abraão não fez.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vós fazeis as obras de vosso pai. Replicaram-lhe eles: Nós não somos nascidos de prostituição; temos um Pai, que é Deus.

[[v43-8-42]]

^<<v43-8-42,42>>^ Respondeu-lhes Jesus: Se Deus fosse o vosso Pai, vós me amaríeis, porque eu saí e vim de Deus; pois não vim de mim mesmo, mas ele me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que não compreendeis a minha linguagem? é porque não podeis ouvir a minha palavra.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vós tendes por pai o Diabo, e quereis satisfazer os desejos de vosso pai; ele é homicida desde o princípio, e nunca se firmou na verdade, porque nele não há verdade; quando ele profere mentira, fala do que lhe é próprio; porque é mentiroso, e pai da mentira.

[[v43-8-45]]

^<<v43-8-45,45>>^ Mas porque eu digo a verdade, não me credes.

[[v43-8-46]]

^<<v43-8-46,46>>^ Quem dentre vós me convence de pecado? Se digo a verdade, por que não me credes?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem é de Deus ouve as palavras de Deus; por isso vós não as ouvis, porque não sois de Deus.

[[v43-8-48]]

^<<v43-8-48,48>>^ Responderam-lhe os judeus: Não dizemos com razão que és samaritano, e que tens demônio?

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus respondeu: Eu não tenho demônio; antes honro a meu Pai, e vós me desonrais.

[[v43-8-50]]

^<<v43-8-50,50>>^ Eu não busco a minha glória; há quem a busque, e julgue.

[[v43-8-51]]

^<<v43-8-51,51>>^ Em verdade, em verdade vos digo que, se alguém guardar a minha palavra, nunca verá a morte.

[[v43-8-52]]

^<<v43-8-52,52>>^ Disseram-lhe os judeus: Agora sabemos que tens demônios. Abraão morreu, e também os profetas; e tu dizes: Se alguém guardar a minha palavra, nunca provará a morte!

[[v43-8-53]]

^<<v43-8-53,53>>^ Porventura és tu maior do que nosso pai Abraão, que morreu? Também os profetas morreram; quem pretendes tu ser?

[[v43-8-54]]

^<<v43-8-54,54>>^ Respondeu Jesus: Se eu me glorificar a mim mesmo, a minha glória não é nada; quem me glorifica é meu Pai, do qual vós dizeis que é o vosso Deus;

[[v43-8-55]]

^<<v43-8-55,55>>^ e vós não o conheceis; mas eu o conheço; e se disser que não o conheço, serei mentiroso como vós; mas eu o conheço, e guardo a sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, vosso pai, exultou por ver o meu dia; viu-o, e alegrou-se.

[[v43-8-57]]

^<<v43-8-57,57>>^ Disseram-lhe, pois, os judeus: Ainda não tens cinqüenta anos, e viste Abraão?

[[v43-8-58]]

^<<v43-8-58,58>>^ Respondeu-lhes Jesus: Em verdade, em verdade vos digo que antes que Abraão existisse, eu sou.

[[v43-8-59]]

^<<v43-8-59,59>>^ Então pegaram em pedras para lhe atirarem; mas Jesus ocultou-se, e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]