include::./index.adoc[]

[[v43-11-0]]
=== João, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-11-1]]

^<<v43-11-1,1>>^ Ora, estava enfermo um homem chamado Lázaro, de Betânia, aldeia de Maria e de sua irmã Marta.

[[v43-11-2]]

^<<v43-11-2,2>>^ E Maria, cujo irmão Lázaro se achava enfermo, era a mesma que ungiu o Senhor com bálsamo, e lhe enxugou os pés com os seus cabelos.

[[v43-11-3]]

^<<v43-11-3,3>>^ Mandaram, pois, as irmãs dizer a Jesus: Senhor, eis que está enfermo aquele que tu amas.

[[v43-11-4]]

^<<v43-11-4,4>>^ Jesus, porém, ao ouvir isto, disse: Esta enfermidade não é para a morte, mas para glória de Deus, para que o Filho de Deus seja glorificado por ela.

[[v43-11-5]]

^<<v43-11-5,5>>^ Ora, Jesus amava a Marta, e a sua irmã, e a Lázaro.

[[v43-11-6]]

^<<v43-11-6,6>>^ Quando, pois, ouviu que estava enfermo, ficou ainda dois dias no lugar onde se achava.

[[v43-11-7]]

^<<v43-11-7,7>>^ Depois disto, disse a seus discípulos: Vamos outra vez para Judéia.

[[v43-11-8]]

^<<v43-11-8,8>>^ Disseram-lhe eles: Rabi, ainda agora os judeus procuravam apedrejar-te, e voltas para lá?

[[v43-11-9]]

^<<v43-11-9,9>>^ Respondeu Jesus: Não são doze as horas do dia? Se alguém andar de dia, não tropeça, porque vê a luz deste mundo;

[[v43-11-10]]

^<<v43-11-10,10>>^ mas se andar de noite, tropeça, porque nele não há luz.

[[v43-11-11]]

^<<v43-11-11,11>>^ E, tendo assim falado, acrescentou: Lázaro, o nosso amigo, dorme, mas vou despertá-lo do sono.

[[v43-11-12]]

^<<v43-11-12,12>>^ Disseram-lhe, pois, os discípulos: Senhor, se dorme, ficará bom.

[[v43-11-13]]

^<<v43-11-13,13>>^ Mas Jesus falara da sua morte; eles, porém, entenderam que falava do repouso do sono.

[[v43-11-14]]

^<<v43-11-14,14>>^ Então Jesus lhes disse claramente: Lázaro morreu;

[[v43-11-15]]

^<<v43-11-15,15>>^ e, por vossa causa, folgo de que eu lá não estivesse, para que creiais; mas vamos ter com ele.

[[v43-11-16]]

^<<v43-11-16,16>>^ Disse, pois, Tomé, chamado Dídimo, aos seus condiscípulos: Vamos nós também, para morrermos com ele.

[[v43-11-17]]

^<<v43-11-17,17>>^ Chegando pois Jesus, encontrou-o já com quatro dias de sepultura.

[[v43-11-18]]

^<<v43-11-18,18>>^ Ora, Betânia distava de Jerusalém cerca de quinze estádios.

[[v43-11-19]]

^<<v43-11-19,19>>^ E muitos dos judeus tinham vindo visitar Marta e Maria, para as consolar acerca de seu irmão.

[[v43-11-20]]

^<<v43-11-20,20>>^ Marta, pois, ao saber que Jesus chegava, saiu-lhe ao encontro; Maria, porém, ficou sentada em casa.

[[v43-11-21]]

^<<v43-11-21,21>>^ Disse, pois, Marta a Jesus: Senhor, se meu irmão não teria morrido.

[[v43-11-22]]

^<<v43-11-22,22>>^ E mesmo agora sei que tudo quanto pedires a Deus, Deus to concederá.

[[v43-11-23]]

^<<v43-11-23,23>>^ Respondeu-lhe Jesus: Teu irmão há de ressurgir.

[[v43-11-24]]

^<<v43-11-24,24>>^ Disse-lhe Marta: Sei que ele há de ressurgir na ressurreição, no último dia.

[[v43-11-25]]

^<<v43-11-25,25>>^ Declarou-lhe Jesus: Eu sou a ressurreição e a vida; quem crê em mim, ainda que morra, viverá;

[[v43-11-26]]

^<<v43-11-26,26>>^ e todo aquele que vive, e crê em mim, jamais morrerá. Crês isto?

[[v43-11-27]]

^<<v43-11-27,27>>^ Respondeu-lhe Marta: Sim, Senhor, eu creio que tu és o Cristo, o Filho de Deus, que havia de vir ao mundo.

[[v43-11-28]]

^<<v43-11-28,28>>^ Dito isto, retirou-se e foi chamar em segredo a Maria, sua irmã, e lhe disse: O Mestre está aí, e te chama.

[[v43-11-29]]

^<<v43-11-29,29>>^ Ela, ouvindo isto, levantou-se depressa, e foi ter com ele.

[[v43-11-30]]

^<<v43-11-30,30>>^ Pois Jesus ainda não havia entrado na aldeia, mas estava no lugar onde Marta o encontrara.

[[v43-11-31]]

^<<v43-11-31,31>>^ Então os judeus que estavam com Maria em casa e a consolavam, vendo-a levantar-se apressadamente e sair, seguiram-na, pensando que ia ao sepulcro para chorar ali.

[[v43-11-32]]

^<<v43-11-32,32>>^ Tendo, pois, Maria chegado ao lugar onde Jesus estava, e vendo-a, lançou-se-lhe aos pés e disse: Senhor, se tu estiveras aqui, meu irmão não teria morrido.

[[v43-11-33]]

^<<v43-11-33,33>>^ Jesus, pois, quando a viu chorar, e chorarem também os judeus que com ela vinham, comoveu-se em espírito, e perturbou-se,

[[v43-11-34]]

^<<v43-11-34,34>>^ e perguntou: Onde o puseste? Responderam-lhe: Senhor, vem e vê.

[[v43-11-35]]

^<<v43-11-35,35>>^ Jesus chorou.

[[v43-11-36]]

^<<v43-11-36,36>>^ Disseram então os judeus: Vede como o amava.

[[v43-11-37]]

^<<v43-11-37,37>>^ Mas alguns deles disseram: Não podia ele, que abriu os olhos ao cego, fazer também que este não morreste?

[[v43-11-38]]

^<<v43-11-38,38>>^ Jesus, pois, comovendo-se outra vez, profundamente, foi ao sepulcro; era uma gruta, e tinha uma pedra posta sobre ela.

[[v43-11-39]]

^<<v43-11-39,39>>^ Disse Jesus: Tirai a pedra. Marta, irmã do defunto, disse-lhe: Senhor, já cheira mal, porque está morto há quase quatro dias.

[[v43-11-40]]

^<<v43-11-40,40>>^ Respondeu-lhe Jesus: Não te disse que, se creres, verás a glória de Deus?

[[v43-11-41]]

^<<v43-11-41,41>>^ Tiraram então a pedra. E Jesus, levantando os olhos ao céu, disse: Pai, graças te dou, porque me ouviste.

[[v43-11-42]]

^<<v43-11-42,42>>^ Eu sabia que sempre me ouves; mas por causa da multidão que está em redor é que assim falei, para que eles creiam que tu me enviaste.

[[v43-11-43]]

^<<v43-11-43,43>>^ E, tendo dito isso, clamou em alta voz: Lázaro, vem para fora!

[[v43-11-44]]

^<<v43-11-44,44>>^ Saiu o que estivera morto, ligados os pés e as mãos com faixas, e o seu rosto envolto num lenço. Disse-lhes Jesus: Desligai-o e deixai-o ir.

[[v43-11-45]]

^<<v43-11-45,45>>^ Muitos, pois, dentre os judeus que tinham vindo visitar Maria, e que tinham visto o que Jesus fizera, creram nele.

[[v43-11-46]]

^<<v43-11-46,46>>^ Mas alguns deles foram ter com os fariseus e disseram-lhes o que Jesus tinha feito.

[[v43-11-47]]

^<<v43-11-47,47>>^ Então os principais sacerdotes e os fariseus reuniram o sinédrio e diziam: Que faremos? porquanto este homem vem operando muitos sinais.

[[v43-11-48]]

^<<v43-11-48,48>>^ Se o deixarmos assim, todos crerão nele, e virão os romanos, e nos tirarão tanto o nosso lugar como a nossa nação.

[[v43-11-49]]

^<<v43-11-49,49>>^ Um deles, porém, chamado Caifás, que era sumo sacerdote naquele ano, disse-lhes: Vós nada sabeis,

[[v43-11-50]]

^<<v43-11-50,50>>^ nem considerais que vos convém que morra um só homem pelo povo, e que não pereça a nação toda.

[[v43-11-51]]

^<<v43-11-51,51>>^ Ora, isso não disse ele por si mesmo; mas, sendo o sumo sacerdote naquele ano, profetizou que Jesus havia de morrer pela nação,

[[v43-11-52]]

^<<v43-11-52,52>>^ e não somente pela nação, mas também para congregar num só corpo os filhos de Deus que estão dispersos.

[[v43-11-53]]

^<<v43-11-53,53>>^ Desde aquele dia, pois, tomavam conselho para o matarem.

[[v43-11-54]]

^<<v43-11-54,54>>^ De sorte que Jesus já não andava manifestamente entre os judeus, mas retirou-se dali para a região vizinha ao deserto, a uma cidade chamada Efraim; e ali demorou com os seus discípulos.

[[v43-11-55]]

^<<v43-11-55,55>>^ Ora, estava próxima a páscoa dos judeus, e dessa região subiram muitos a Jerusalém, antes da páscoa, para se purificarem.

[[v43-11-56]]

^<<v43-11-56,56>>^ Buscavam, pois, a Jesus e diziam uns aos outros, estando no templo: Que vos parece? Não virá ele à festa?

[[v43-11-57]]

^<<v43-11-57,57>>^ Ora, os principais sacerdotes e os fariseus tinham dado ordem que, se alguém soubesse onde ele estava, o denunciasse, para que o prendessem.

'''

xref:043-joao/043-joao-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-joao/043-joao-012.adoc#v43-12-0[Próximo Capítulo &#62;]