include::./index.adoc[]

[[v43-19-0]]
=== João, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-19-1]]

^<<v43-19-1,1>>^ Nisso, pois, Pilatos tomou a Jesus, e mandou açoitá-lo.

[[v43-19-2]]

^<<v43-19-2,2>>^ E os soldados, tecendo uma coroa de espinhos, puseram-lha sobre a cabeça, e lhe vestiram um manto de púrpura;

[[v43-19-3]]

^<<v43-19-3,3>>^ e chegando-se a ele, diziam: Salve, rei dos judeus! e davam-lhe bofetadas.

[[v43-19-4]]

^<<v43-19-4,4>>^ Então Pilatos saiu outra vez, e disse-lhes: Eis aqui vo-lo trago fora, para que saibais que não acho nele crime algum.

[[v43-19-5]]

^<<v43-19-5,5>>^ Saiu, pois, Jesus, trazendo a coroa de espinhos e o manto de púrpura. E disse-lhes Pilatos: Eis o homem!

[[v43-19-6]]

^<<v43-19-6,6>>^ Quando o viram os principais sacerdotes e os guardas, clamaram, dizendo: Crucifica-o! Crucifica-o! Disse-lhes Pilatos: Tomai-o vós, e crucificai-o; porque nenhum crime acho nele.

[[v43-19-7]]

^<<v43-19-7,7>>^ Responderam-lhe os judeus: Nós temos uma lei, e segundo esta lei ele deve morrer, porque se fez Filho de Deus.

[[v43-19-8]]

^<<v43-19-8,8>>^ Ora, Pilatos, quando ouviu esta palavra, mais atemorizado ficou;

[[v43-19-9]]

^<<v43-19-9,9>>^ e entrando outra vez no pretório, perguntou a Jesus: Donde és tu? Mas Jesus não lhe deu resposta.

[[v43-19-10]]

^<<v43-19-10,10>>^ Disse-lhe, então, Pilatos: Não me respondes? não sabes que tenho autoridade para te soltar, e autoridade para te crucificar?

[[v43-19-11]]

^<<v43-19-11,11>>^ Respondeu-lhe Jesus: Nenhuma autoridade terias sobre mim, se de cima não te fora dado; por isso aquele que me entregou a ti, maior pecado tem.

[[v43-19-12]]

^<<v43-19-12,12>>^ Daí em diante Pilatos procurava soltá-lo; mas os judeus clamaram: Se soltares a este, não és amigo de César; todo aquele que se faz rei é contra César.

[[v43-19-13]]

^<<v43-19-13,13>>^ Pilatos, pois, quando ouviu isto, trouxe Jesus para fora e sentou-se no tribunal, no lugar chamado Pavimento, e em hebraico Gabatá.

[[v43-19-14]]

^<<v43-19-14,14>>^ Ora, era a preparação da páscoa, e cerca da hora sexta. E disse aos judeus: Eis o vosso rei.

[[v43-19-15]]

^<<v43-19-15,15>>^ Mas eles clamaram: Tira-o! tira-o! crucifica-o! Disse-lhes Pilatos: Hei de crucificar o vosso rei? responderam, os principais sacerdotes: Não temos rei, senão César.

[[v43-19-16]]

^<<v43-19-16,16>>^ Então lho entregou para ser crucificado.

[[v43-19-17]]

^<<v43-19-17,17>>^ Tomaram, pois, a Jesus; e ele, carregando a sua própria cruz, saiu para o lugar chamado Caveira, que em hebraico se chama Gólgota,

[[v43-19-18]]

^<<v43-19-18,18>>^ onde o crucificaram, e com ele outros dois, um de cada lado, e Jesus no meio.

[[v43-19-19]]

^<<v43-19-19,19>>^ E Pilatos escreveu também um título, e o colocou sobre a cruz; e nele estava escrito: JESUS O NAZARENO, O REI DOS JUDEUS.

[[v43-19-20]]

^<<v43-19-20,20>>^ Muitos dos judeus, pois, leram este título; porque o lugar onde Jesus foi crucificado era próximo da cidade; e estava escrito em hebraico, latim e grego.

[[v43-19-21]]

^<<v43-19-21,21>>^ Diziam então a Pilatos os principais sacerdotes dos judeus: Não escrevas: O rei dos judeus; mas que ele disse: Sou rei dos judeus.

[[v43-19-22]]

^<<v43-19-22,22>>^ Respondeu Pilatos: O que escrevi, escrevi.

[[v43-19-23]]

^<<v43-19-23,23>>^ Tendo, pois, os soldados crucificado a Jesus, tomaram as suas vestes, e fizeram delas quatro partes, para cada soldado uma parte. Tomaram também a túnica; ora a túnica não tinha costura, sendo toda tecida de alto a baixo.

[[v43-19-24]]

^<<v43-19-24,24>>^ Pelo que disseram uns aos outros: Não a rasguemos, mas lancemos sortes sobre ela, para ver de quem será &#123;para que se cumprisse a escritura que diz: Repartiram entre si as minhas vestes, e lançaram sortes&#125;. E, de fato, os soldados assim fizeram.

[[v43-19-25]]

^<<v43-19-25,25>>^ Estavam em pé, junto à cruz de Jesus, sua mãe, e a irmã de sua mãe, e Maria, mulher de Clôpas, e Maria Madalena.

[[v43-19-26]]

^<<v43-19-26,26>>^ Ora, Jesus, vendo ali sua mãe, e ao lado dela o discípulo a quem ele amava, disse a sua mãe: Mulher, eis aí o teu filho.

[[v43-19-27]]

^<<v43-19-27,27>>^ Então disse ao discípulo: Eis aí tua mãe. E desde aquela hora o discípulo a recebeu em sua casa.

[[v43-19-28]]

^<<v43-19-28,28>>^ Depois, sabendo Jesus que todas as coisas já estavam consumadas, para que se cumprisse a Escritura, disse: Tenho sede.

[[v43-19-29]]

^<<v43-19-29,29>>^ Estava ali um vaso cheio de vinagre. Puseram, pois, numa cana de hissopo uma esponja ensopada de vinagre, e lha chegaram à boca.

[[v43-19-30]]

^<<v43-19-30,30>>^ Então Jesus, depois de ter tomado o vinagre, disse: está consumado. E, inclinando a cabeça, entregou o espírito.

[[v43-19-31]]

^<<v43-19-31,31>>^ Ora, os judeus, como era a preparação, e para que no sábado não ficassem os corpos na cruz, pois era grande aquele dia de sábado, rogaram a Pilatos que se lhes quebrassem as pernas, e fossem tirados dali.

[[v43-19-32]]

^<<v43-19-32,32>>^ Foram então os soldados e, na verdade, quebraram as pernas ao primeiro e ao outro que com ele fora crucificado;

[[v43-19-33]]

^<<v43-19-33,33>>^ mas vindo a Jesus, e vendo que já estava morto, não lhe quebraram as pernas;

[[v43-19-34]]

^<<v43-19-34,34>>^ contudo um dos soldados lhe furou o lado com uma lança, e logo saiu sangue e água.

[[v43-19-35]]

^<<v43-19-35,35>>^ E é quem viu isso que dá testemunho, e o seu testemunho é verdadeiro; e sabe que diz a verdade, para que também vós creiais.

[[v43-19-36]]

^<<v43-19-36,36>>^ Porque isto aconteceu para que se cumprisse a escritura: Nenhum dos seus ossos será quebrado.

[[v43-19-37]]

^<<v43-19-37,37>>^ Também há outra escritura que diz: Olharão para aquele que traspassaram.

[[v43-19-38]]

^<<v43-19-38,38>>^ Depois disto, José de Arimatéia, que era discípulo de Jesus, embora oculto por medo dos judeus, rogou a Pilatos que lhe permitisse tirar o corpo de Jesus; e Pilatos lho permitiu. Então foi e o tirou.

[[v43-19-39]]

^<<v43-19-39,39>>^ E Nicodemos, aquele que anteriormente viera ter com Jesus de noite, foi também, levando cerca de cem libras duma mistura de mirra e aloés.

[[v43-19-40]]

^<<v43-19-40,40>>^ Tomaram, pois, o corpo de Jesus, e o envolveram em panos de linho com as especiarias, como os judeus costumavam fazer na preparação para a sepultura.

[[v43-19-41]]

^<<v43-19-41,41>>^ No lugar onde Jesus foi crucificado havia um jardim, e nesse jardim um sepulcro novo, em que ninguém ainda havia sido posto.

[[v43-19-42]]

^<<v43-19-42,42>>^ Ali, pois, por ser a véspera do sábado dos judeus, e por estar perto aquele sepulcro, puseram a Jesus.

'''

xref:043-joao/043-joao-018.adoc#v43-18-0[&#60; Capítulo Anterior] | <<v43-19-0,Topo>> | xref:043-joao/043-joao-020.adoc#v43-20-0[Próximo Capítulo &#62;]