include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-18-1]]

^<<v43-18-1,1>>^ Tendo Jesus dito isto, saiu com seus discípulos para o outro lado do ribeiro de Cedrom, onde havia um jardim, e com eles ali entrou.

[[v43-18-2]]

^<<v43-18-2,2>>^ Ora, Judas, que o traía, também conhecia aquele lugar, porque muitas vezes Jesus se reunira ali com os discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Tendo, pois, Judas tomado a corte e uns guardas da parte dos principais sacerdotes e fariseus, chegou ali com lanternas archotes e armas.

[[v43-18-4]]

^<<v43-18-4,4>>^ Sabendo, pois, Jesus tudo o que lhe havia de suceder, adiantou-se e perguntou-lhes: A quem buscais?

[[v43-18-5]]

^<<v43-18-5,5>>^ Responderam-lhe: A Jesus, o nazareno. Disse-lhes Jesus: Sou eu. E Judas, que o traía, também estava com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ Quando Jesus lhes disse: Sou eu, recuaram, e caíram por terra.

[[v43-18-7]]

^<<v43-18-7,7>>^ Tornou-lhes então a perguntar: A quem buscais? e responderam: A Jesus, o nazareno.

[[v43-18-8]]

^<<v43-18-8,8>>^ Replicou-lhes Jesus: Já vos disse que sou eu; se, pois, é a mim que buscais, deixai ir estes;

[[v43-18-9]]

^<<v43-18-9,9>>^ para que se cumprisse a palavra que dissera: Dos que me tens dado, nenhum deles perdi.

[[v43-18-10]]

^<<v43-18-10,10>>^ Então Simão Pedro, que tinha uma espada, desembainhou-a e feriu o servo do sumo sacerdote, cortando-lhe a orelha direita. O nome do servo era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Disse, pois, Jesus a Pedro: Mete a tua espada na bainha; não hei de beber o cálice que o Pai me deu?

[[v43-18-12]]

^<<v43-18-12,12>>^ Então a escolta, e o comandante, e os guardas dos judeus prenderam a Jesus, e o maniataram.

[[v43-18-13]]

^<<v43-18-13,13>>^ E conduziram-no primeiramente a Anás; pois era sogro de Caifás, sumo sacerdote naquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ Ora, Caifás era quem aconselhara aos judeus que convinha morrer um homem pelo povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ Simão Pedro e outro discípulo seguiam a Jesus. Este discípulo era conhecido do sumo sacerdote, e entrou com Jesus no pátio do sumo sacerdote,

[[v43-18-16]]

^<<v43-18-16,16>>^ enquanto Pedro ficava da parte de fora, à porta. Saiu, então, o outro discípulo que era conhecido do sumo sacerdote, falou à porteira, e levou Pedro para dentro.

[[v43-18-17]]

^<<v43-18-17,17>>^ Então a porteira perguntou a Pedro: Não és tu também um dos discípulos deste homem? Respondeu ele: Não sou.

[[v43-18-18]]

^<<v43-18-18,18>>^ Ora, estavam ali os servos e os guardas, que tinham acendido um braseiro e se aquentavam, porque fazia frio; e também Pedro estava ali em pé no meio deles, aquentando-se.

[[v43-18-19]]

^<<v43-18-19,19>>^ Então o sumo sacerdote interrogou Jesus acerca dos seus discípulos e da sua doutrina.

[[v43-18-20]]

^<<v43-18-20,20>>^ Respondeu-lhe Jesus: Eu tenho falado abertamente ao mundo; eu sempre ensinei nas sinagogas e no templo, onde todos os judeus se congregam, e nada falei em oculto.

[[v43-18-21]]

^<<v43-18-21,21>>^ Por que me perguntas a mim? pergunta aos que me ouviram o que é que lhes falei; eis que eles sabem o que eu disse.

[[v43-18-22]]

^<<v43-18-22,22>>^ E, havendo ele dito isso, um dos guardas que ali estavam deu uma bofetada em Jesus, dizendo: É assim que respondes ao sumo sacerdote?

[[v43-18-23]]

^<<v43-18-23,23>>^ Respondeu-lhe Jesus: Se falei mal, dá testemunho do mal; mas, se bem, por que me feres?

[[v43-18-24]]

^<<v43-18-24,24>>^ Então Anás o enviou, maniatado, a Caifás, o sumo sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ E Simão Pedro ainda estava ali, aquentando-se. Perguntaram-lhe, pois: Não és também tu um dos seus discípulos? Ele negou, e disse: Não sou.

[[v43-18-26]]

^<<v43-18-26,26>>^ Um dos servos do sumo sacerdote, parente daquele a quem Pedro cortara a orelha, disse: Não te vi eu no jardim com ele?

[[v43-18-27]]

^<<v43-18-27,27>>^ Pedro negou outra vez, e imediatamente o galo cantou.

[[v43-18-28]]

^<<v43-18-28,28>>^ Depois conduziram Jesus da presença de Caifás para o pretório; era de manhã cedo; e eles não entraram no pretório, para não se contaminarem, mas poderem comer a páscoa.

[[v43-18-29]]

^<<v43-18-29,29>>^ Então Pilatos saiu a ter com eles, e perguntou: Que acusação trazeis contra este homem?

[[v43-18-30]]

^<<v43-18-30,30>>^ Responderam-lhe: Se ele não fosse malfeitor, não to entregaríamos.

[[v43-18-31]]

^<<v43-18-31,31>>^ Disse-lhes, então, Pilatos: Tomai-o vós, e julgai-o segundo a vossa lei. Disseram-lhe os judeus: A nós não nos é lícito tirar a vida a ninguém.

[[v43-18-32]]

^<<v43-18-32,32>>^ Isso foi para que se cumprisse a palavra que dissera Jesus, significando de que morte havia de morrer.

[[v43-18-33]]

^<<v43-18-33,33>>^ Pilatos, pois, tornou a entrar no pretório, chamou a Jesus e perguntou-lhe: És tu o rei dos judeus?

[[v43-18-34]]

^<<v43-18-34,34>>^ Respondeu Jesus: Dizes isso de ti mesmo, ou foram outros que to disseram de mim?

[[v43-18-35]]

^<<v43-18-35,35>>^ Replicou Pilatos: Porventura sou eu judeu? O teu povo e os principais sacerdotes entregaram-te a mim; que fizeste?

[[v43-18-36]]

^<<v43-18-36,36>>^ Respondeu Jesus: O meu reino não é deste mundo; se o meu reino fosse deste mundo, pelejariam os meus servos, para que eu não fosse entregue aos judeus; entretanto o meu reino não é daqui.

[[v43-18-37]]

^<<v43-18-37,37>>^ Perguntou-lhe, pois, Pilatos: Logo tu és rei? Respondeu Jesus: Tu dizes que eu sou rei. Eu para isso nasci, e para isso vim ao mundo, a fim de dar testemunho da verdade. Todo aquele que é da verdade ouve a minha voz.

[[v43-18-38]]

^<<v43-18-38,38>>^ Perguntou-lhe Pilatos: Que é a verdade? E dito isto, de novo saiu a ter com os judeus, e disse-lhes: Não acho nele crime algum.

[[v43-18-39]]

^<<v43-18-39,39>>^ Tendes, porém, por costume que eu vos solte alguém por ocasião da páscoa; quereis, pois, que vos solte o rei dos judeus?

[[v43-18-40]]

^<<v43-18-40,40>>^ Então todos tornaram a clamar dizendo: Este não, mas Barrabás. Ora, Barrabás era salteador.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]