include::./index.adoc[]

[[v43-2-0]]
=== João, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-2-1]]

^<<v43-2-1,1>>^ Três dias depois, houve um casamento em Caná da Galiléia, e estava ali a mãe de Jesus;

[[v43-2-2]]

^<<v43-2-2,2>>^ e foi também convidado Jesus com seus discípulos para o casamento.

[[v43-2-3]]

^<<v43-2-3,3>>^ E, tendo acabado o vinho, a mãe de Jesus lhe disse: Eles não têm vinho.

[[v43-2-4]]

^<<v43-2-4,4>>^ Respondeu-lhes Jesus: Mulher, que tenho eu contigo? Ainda não é chegada a minha hora.

[[v43-2-5]]

^<<v43-2-5,5>>^ Disse então sua mãe aos serventes: Fazei tudo quanto ele vos disser.

[[v43-2-6]]

^<<v43-2-6,6>>^ Ora, estavam ali postas seis talhas de pedra, para as purificações dos judeus, e em cada uma cabiam duas ou três metretas.

[[v43-2-7]]

^<<v43-2-7,7>>^ Ordenou-lhe Jesus: Enchei de água essas talhas. E encheram-nas até em cima.

[[v43-2-8]]

^<<v43-2-8,8>>^ Então lhes disse: Tirai agora, e levai ao mestre-sala. E eles o fizeram.

[[v43-2-9]]

^<<v43-2-9,9>>^ Quando o mestre-sala provou a água tornada em vinho, não sabendo donde era, se bem que o sabiam os serventes que tinham tirado a água, chamou o mestre-sala ao noivo

[[v43-2-10]]

^<<v43-2-10,10>>^ e lhe disse: Todo homem põe primeiro o vinho bom e, quando já têm bebido bem, então o inferior; mas tu guardaste até agora o bom vinho.

[[v43-2-11]]

^<<v43-2-11,11>>^ Assim deu Jesus início aos seus sinais em Caná da Galiléia, e manifestou a sua glória; e os seus discípulos creram nele.

[[v43-2-12]]

^<<v43-2-12,12>>^ Depois disso desceu a Cafarnaum, ele, sua mãe, seus irmãos, e seus discípulos; e ficaram ali não muitos dias.

[[v43-2-13]]

^<<v43-2-13,13>>^ Estando próxima a páscoa dos judeus, Jesus subiu a Jerusalém.

[[v43-2-14]]

^<<v43-2-14,14>>^ E achou no templo os que vendiam bois, ovelhas e pombas, e também os cambistas ali sentados;

[[v43-2-15]]

^<<v43-2-15,15>>^ e tendo feito um azorrague de cordas, lançou todos fora do templo, bem como as ovelhas e os bois; e espalhou o dinheiro dos cambistas, e virou-lhes as mesas;

[[v43-2-16]]

^<<v43-2-16,16>>^ e disse aos que vendiam as pombas: Tirai daqui estas coisas; não façais da casa de meu Pai casa de negócio.

[[v43-2-17]]

^<<v43-2-17,17>>^ Lembraram-se então os seus discípulos de que está escrito: O zelo da tua casa me devorará.

[[v43-2-18]]

^<<v43-2-18,18>>^ Protestaram, pois, os judeus, perguntando-lhe: Que sinal de autoridade nos mostras, uma vez que fazes isto?

[[v43-2-19]]

^<<v43-2-19,19>>^ Respondeu-lhes Jesus: Derribai este santuário, e em três dias o levantarei.

[[v43-2-20]]

^<<v43-2-20,20>>^ Disseram, pois, os judeus: Em quarenta e seis anos foi edificado este santuário, e tu o levantarás em três dias?

[[v43-2-21]]

^<<v43-2-21,21>>^ Mas ele falava do santuário do seu corpo.

[[v43-2-22]]

^<<v43-2-22,22>>^ Quando, pois ressurgiu dentre os mortos, seus discípulos se lembraram de que dissera isto, e creram na Escritura, e na palavra que Jesus havia dito.

[[v43-2-23]]

^<<v43-2-23,23>>^ Ora, estando ele em Jerusalém pela festa da páscoa, muitos, vendo os sinais que fazia, creram no seu nome.

[[v43-2-24]]

^<<v43-2-24,24>>^ Mas o próprio Jesus não confiava a eles, porque os conhecia a todos,

[[v43-2-25]]

^<<v43-2-25,25>>^ e não necessitava de que alguém lhe desse testemunho do homem, pois bem sabia o que havia no homem.

'''

xref:043-joao/043-joao-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-joao/043-joao-003.adoc#v43-3-0[Próximo Capítulo &#62;]