include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-10-1]]

^<<v43-10-1,1>>^ Em verdade, em verdade vos digo: quem não entra pela porta no aprisco das ovelhas, mas sobe por outra parte, esse é ladrão e salteador.

[[v43-10-2]]

^<<v43-10-2,2>>^ Mas o que entra pela porta é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ A este o porteiro abre; e as ovelhas ouvem a sua voz; e ele chama pelo nome as suas ovelhas, e as conduz para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de conduzir para fora todas as que lhe pertencem, vai adiante delas, e as ovelhas o seguem, porque conhecem a sua voz;

[[v43-10-5]]

^<<v43-10-5,5>>^ mas de modo algum seguirão o estranho, antes fugirão dele, porque não conhecem a voz dos estranhos.

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus propôs-lhes esta parábola, mas eles não entenderam o que era que lhes dizia.

[[v43-10-7]]

^<<v43-10-7,7>>^ Tornou, pois, Jesus a dizer-lhes: Em verdade, em verdade vos digo: eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos quantos vieram antes de mim são ladrões e salteadores; mas as ovelhas não os ouviram.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta; se alguém entrar a casa; o filho fica entrará e sairá, e achará pastagens.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão não vem senão para roubar, matar e destruir; eu vim para que tenham vida e a tenham em abundância.

[[v43-10-11]]

^<<v43-10-11,11>>^ Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas.

[[v43-10-12]]

^<<v43-10-12,12>>^ Mas o que é mercenário, e não pastor, de quem não são as ovelhas, vendo vir o lobo, deixa as ovelhas e foge; e o lobo as arrebata e dispersa.

[[v43-10-13]]

^<<v43-10-13,13>>^ Ora, o mercenário foge porque é mercenário, e não se importa com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom pastor; conheço as minhas ovelhas, e elas me conhecem,

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como o Pai me conhece e eu conheço o Pai; e dou a minha vida pelas ovelhas.

[[v43-10-16]]

^<<v43-10-16,16>>^ Tenho ainda outras ovelhas que não são deste aprisco; a essas também me importa conduzir, e elas ouvirão a minha voz; e haverá um rebanho e um pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ Por isto o Pai me ama, porque dou a minha vida para a retomar.

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém ma tira de mim, mas eu de mim mesmo a dou; tenho autoridade para a dar, e tenho autoridade para retomá-la. Este mandamento recebi de meu Pai.

[[v43-10-19]]

^<<v43-10-19,19>>^ Por causa dessas palavras, houve outra dissensão entre os judeus.

[[v43-10-20]]

^<<v43-10-20,20>>^ E muitos deles diziam: Tem demônio, e perdeu o juízo; por que o escutais?

[[v43-10-21]]

^<<v43-10-21,21>>^ Diziam outros: Essas palavras não são de quem está endemoninhado; pode porventura um demônio abrir os olhos aos cegos?

[[v43-10-22]]

^<<v43-10-22,22>>^ Celebrava-se então em Jerusalém a festa da dedicação. E era inverno.

[[v43-10-23]]

^<<v43-10-23,23>>^ Andava Jesus passeando no templo, no pórtico de Salomão.

[[v43-10-24]]

^<<v43-10-24,24>>^ Rodearam-no, pois, os judeus e lhe perguntavam: Até quando nos deixarás perplexos? Se tu és o Cristo, dize-no-lo abertamente.

[[v43-10-25]]

^<<v43-10-25,25>>^ Respondeu-lhes Jesus: Já vo-lo disse, e não credes. As obras que eu faço em nome de meu Pai, essas dão testemunho de mim.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vós não credes, porque não sois das minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ As minhas ovelhas ouvem a minha voz, e eu as conheço, e elas me seguem;

[[v43-10-28]]

^<<v43-10-28,28>>^ eu lhes dou a vida eterna, e jamais perecerão; e ninguém as arrebatará da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ Meu Pai, que mas deu, é maior do que todos; e ninguém pode arrebatá-las da mão de meu Pai.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.

[[v43-10-31]]

^<<v43-10-31,31>>^ Os judeus pegaram então outra vez em pedras para o apedrejar.

[[v43-10-32]]

^<<v43-10-32,32>>^ Disse-lhes Jesus: Muitas obras boas da parte de meu Pai vos tenho mostrado; por qual destas obras ides apedrejar-me?

[[v43-10-33]]

^<<v43-10-33,33>>^ Responderam-lhe os judeus: Não é por nenhuma obra boa que vamos apedrejar-te, mas por blasfêmia; e porque, sendo tu homem, te fazes Deus.

[[v43-10-34]]

^<<v43-10-34,34>>^ Tornou-lhes Jesus: Não está escrito na vossa lei: Eu disse: Vós sois deuses?

[[v43-10-35]]

^<<v43-10-35,35>>^ Se a lei chamou deuses àqueles a quem a palavra de Deus foi dirigida &#123;e a Escritura não pode ser anulada&#125;,

[[v43-10-36]]

^<<v43-10-36,36>>^ àquele a quem o Pai santificou, e enviou ao mundo, dizeis vós: Blasfemas; porque eu disse: Sou Filho de Deus?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço as obras de meu Pai, não me acrediteis.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas se as faço, embora não me creiais a mim, crede nas obras; para que entendais e saibais que o Pai está em mim e eu no Pai.

[[v43-10-39]]

^<<v43-10-39,39>>^ Outra vez, pois, procuravam prendê-lo; mas ele lhes escapou das mãos.

[[v43-10-40]]

^<<v43-10-40,40>>^ E retirou-se de novo para além do Jordão, para o lugar onde João batizava no princípio; e ali ficou.

[[v43-10-41]]

^<<v43-10-41,41>>^ Muitos foram ter com ele, e diziam: João, na verdade, não fez sinal algum, mas tudo quanto disse deste homem era verdadeiro.

[[v43-10-42]]

^<<v43-10-42,42>>^ E muitos ali creram nele.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]