include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-20-1]]

^<<v43-20-1,1>>^ No primeiro dia da semana Maria Madalena foi ao sepulcro de madrugada, sendo ainda escuro, e viu que a pedra fora removida do sepulcro.

[[v43-20-2]]

^<<v43-20-2,2>>^ Correu, pois, e foi ter com Simão Pedro, e o outro discípulo, a quem Jesus amava, e disse-lhes: Tiraram do sepulcro o Senhor, e não sabemos onde o puseram.

[[v43-20-3]]

^<<v43-20-3,3>>^ Saíram então Pedro e o outro discípulo e foram ao sepulcro.

[[v43-20-4]]

^<<v43-20-4,4>>^ Corriam os dois juntos, mas o outro discípulo correu mais ligeiro do que Pedro, e chegou primeiro ao sepulcro;

[[v43-20-5]]

^<<v43-20-5,5>>^ e, abaixando-se viu os panos de linho ali deixados, todavia não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ Chegou, pois, Simão Pedro, que o seguia, e entrou no sepulcro e viu os panos de linho ali deixados,

[[v43-20-7]]

^<<v43-20-7,7>>^ e que o lenço, que estivera sobre a cabeça de Jesus, não estava com os panos, mas enrolado num lugar à parte.

[[v43-20-8]]

^<<v43-20-8,8>>^ Então entrou também o outro discípulo, que chegara primeiro ao sepulcro, e viu e creu.

[[v43-20-9]]

^<<v43-20-9,9>>^ Porque ainda não entendiam a escritura, que era necessário que ele ressurgisse dentre os mortos.

[[v43-20-10]]

^<<v43-20-10,10>>^ Tornaram, pois, os discípulos para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria, porém, estava em pé, diante do sepulcro, a chorar. Enquanto chorava, abaixou-se a olhar para dentro do sepulcro,

[[v43-20-12]]

^<<v43-20-12,12>>^ e viu dois anjos vestidos de branco sentados onde jazera o corpo de Jesus, um à cabeceira e outro aos pés.

[[v43-20-13]]

^<<v43-20-13,13>>^ E perguntaram-lhe eles: Mulher, por que choras? Respondeu-lhes: Porque tiraram o meu Senhor, e não sei onde o puseram.

[[v43-20-14]]

^<<v43-20-14,14>>^ Ao dizer isso, voltou-se para trás, e viu a Jesus ali em pé, mas não sabia que era Jesus.

[[v43-20-15]]

^<<v43-20-15,15>>^ Perguntou-lhe Jesus: Mulher, por que choras? A quem procuras? Ela, julgando que fosse o jardineiro, respondeu-lhe: Senhor, se tu o levaste, dize-me onde o puseste, e eu o levarei.

[[v43-20-16]]

^<<v43-20-16,16>>^ Disse-lhe Jesus: Maria! Ela, virando-se, disse-lhe em hebraico: Raboni!-que quer dizer, Mestre.

[[v43-20-17]]

^<<v43-20-17,17>>^ Disse-lhe Jesus: Deixa de me tocar, porque ainda não subi ao Pai; mas vai a meus irmãos e dize-lhes que eu subo para meu Pai e vosso Pai, meu Deus e vosso Deus.

[[v43-20-18]]

^<<v43-20-18,18>>^ E foi Maria Madalena anunciar aos discípulos: Vi o Senhor!-e que ele lhe dissera estas coisas.

[[v43-20-19]]

^<<v43-20-19,19>>^ Chegada, pois, a tarde, naquele dia, o primeiro da semana, e estando os discípulos reunidos com as portas cerradas por medo dos judeus, chegou Jesus, pôs-se no meio e disse-lhes: Paz seja convosco.

[[v43-20-20]]

^<<v43-20-20,20>>^ Dito isto, mostrou-lhes as mãos e o lado. Alegraram-se, pois, os discípulos ao verem o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Disse-lhes, então, Jesus segunda vez: Paz seja convosco; assim como o Pai me enviou, também eu vos envio a vós.

[[v43-20-22]]

^<<v43-20-22,22>>^ E havendo dito isso, assoprou sobre eles, e disse-lhes: Recebei o Espírito Santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Àqueles a quem perdoardes os pecados, são-lhes perdoados; e àqueles a quem os retiverdes, são-lhes retidos.

[[v43-20-24]]

^<<v43-20-24,24>>^ Ora, Tomé, um dos doze, chamado Dídimo, não estava com eles quando veio Jesus.

[[v43-20-25]]

^<<v43-20-25,25>>^ Diziam-lhe, pois, ou outros discípulos: Vimos o Senhor. Ele, porém, lhes respondeu: Se eu não vir o sinal dos cravos nas mãos, e não meter a mão no seu lado, de maneira nenhuma crerei.

[[v43-20-26]]

^<<v43-20-26,26>>^ Oito dias depois estavam os discípulos outra vez ali reunidos, e Tomé com eles. Chegou Jesus, estando as portas fechadas, pôs-se no meio deles e disse: Paz seja convosco.

[[v43-20-27]]

^<<v43-20-27,27>>^ Depois disse a Tomé: Chega aqui o teu dedo, e vê as minhas mãos; chega a tua mão, e mete-a no meu lado; e não mais sejas incrédulo, mas crente.

[[v43-20-28]]

^<<v43-20-28,28>>^ Respondeu-lhe Tomé: Senhor meu, e Deus meu!

[[v43-20-29]]

^<<v43-20-29,29>>^ Disse-lhe Jesus: Porque me viste, creste? Bem-aventurados os que não viram e creram.

[[v43-20-30]]

^<<v43-20-30,30>>^ Jesus, na verdade, operou na presença de seus discípulos ainda muitos outros sinais que não estão escritos neste livro;

[[v43-20-31]]

^<<v43-20-31,31>>^ estes, porém, estão escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais vida em seu nome.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]