include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois disto manifestou-se Jesus outra vez aos discípulos junto do mar de Tiberíades; e manifestou-se deste modo:

[[v43-21-2]]

^<<v43-21-2,2>>^ Estavam juntos Simão Pedro, Tomé, chamado Dídimo, Natanael, que era de Caná da Galiléia, os filhos de Zebedeu, e outros dois dos seus discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Disse-lhes Simão Pedro: Vou pescar. Responderam-lhe: Nós também vamos contigo. Saíram e entraram no barco; e naquela noite nada apanharam.

[[v43-21-4]]

^<<v43-21-4,4>>^ Mas ao romper da manhã, Jesus se apresentou na praia; todavia os discípulos não sabiam que era ele.

[[v43-21-5]]

^<<v43-21-5,5>>^ Disse-lhes, pois, Jesus: Filhos, não tendes nada que comer? Responderam-lhe: Não.

[[v43-21-6]]

^<<v43-21-6,6>>^ Disse-lhes ele: Lançai a rede à direita do barco, e achareis. Lançaram-na, pois, e já não a podiam puxar por causa da grande quantidade de peixes.

[[v43-21-7]]

^<<v43-21-7,7>>^ Então aquele discípulo a quem Jesus amava disse a Pedro: Senhor. Quando, pois, Simão Pedro ouviu que era o Senhor, cingiu-se com a túnica, porque estava despido, e lançou-se ao mar;

[[v43-21-8]]

^<<v43-21-8,8>>^ mas os outros discípulos vieram no barquinho, puxando a rede com os peixes, porque não estavam distantes da terra senão cerca de duzentos côvados.

[[v43-21-9]]

^<<v43-21-9,9>>^ Ora, ao saltarem em terra, viram ali brasas, e um peixe posto em cima delas, e pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Disse-lhes Jesus: Trazei alguns dos peixes que agora apanhastes.

[[v43-21-11]]

^<<v43-21-11,11>>^ Entrou Simão Pedro no barco e puxou a rede para terra, cheia de cento e cinqüenta e três grandes peixes; e, apesar de serem tantos, não se rompeu a rede.

[[v43-21-12]]

^<<v43-21-12,12>>^ Disse-lhes Jesus: Vinde, comei. Nenhum dos discípulos ousava perguntar-lhe: Quem és tu? sabendo que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Chegou Jesus, tomou o pão e deu-lho, e semelhantemente o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ Foi esta a terceira vez que Jesus se manifestou aos seus discípulos, depois de ter ressurgido dentre os mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Depois de terem comido, perguntou Jesus a Simão Pedro: Simão Pedro: Simão, filho de João, amas-me mais do que estes? Respondeu-lhe: Sim, Senhor; tu sabes que te amo. Disse-lhe: Apascenta os meus cordeirinhos.

[[v43-21-16]]

^<<v43-21-16,16>>^ Tornou a perguntar-lhe: Simão, filho de João, amas-me? Respondeu-lhe: Sim, Senhor; tu sabes que te amo. Disse-lhe: Pastoreia as minhas ovelhas.

[[v43-21-17]]

^<<v43-21-17,17>>^ Perguntou-lhe terceira vez: Simão, filho de João, amas-me? Entristeceu-se Pedro por lhe ter perguntado pela terceira vez: Amas-me? E respondeu-lhe: Senhor, tu sabes todas as coisas; tu sabes que te amo. Disse-lhe Jesus: Apascenta as minhas ovelhas.

[[v43-21-18]]

^<<v43-21-18,18>>^ Em verdade, em verdade te digo que, quando eras mais moço, te cingias a ti mesmo, e andavas por onde querias; mas, quando fores velho, estenderás as mãos e outro te cingirá, e te levará para onde tu não queres.

[[v43-21-19]]

^<<v43-21-19,19>>^ Ora, isto ele disse, significando com que morte havia Pedro de glorificar a Deus. E, havendo dito isto, ordenou-lhe: Segue-me.

[[v43-21-20]]

^<<v43-21-20,20>>^ E Pedro, virando-se, viu que o seguia aquele discípulo a quem Jesus amava, o mesmo que na ceia se recostara sobre o peito de Jesus e perguntara: Senhor, quem é o que te trai?

[[v43-21-21]]

^<<v43-21-21,21>>^ Ora, vendo Pedro a este, perguntou a Jesus: Senhor, e deste que será?

[[v43-21-22]]

^<<v43-21-22,22>>^ Respondeu-lhe Jesus: Se eu quiser que ele fique até que eu venha, que tens tu com isso? Segue-me tu.

[[v43-21-23]]

^<<v43-21-23,23>>^ Divulgou-se, pois, entre os irmãos este dito, que aquele discípulo não havia de morrer. Jesus, porém, não disse que não morreria, mas: se eu quiser que ele fique até que eu venha, que tens tu com isso?

[[v43-21-24]]

^<<v43-21-24,24>>^ Este é o discípulo que dá testemunho destas coisas e as escreveu; e sabemos que o seu testemunho é verdadeiro.

[[v43-21-25]]

^<<v43-21-25,25>>^ E ainda muitas outras coisas há que Jesus fez; as quais, se fossem escritas uma por uma, creio que nem ainda no mundo inteiro caberiam os livros que se escrevessem.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]