include::./index.adoc[]

[[v43-9-0]]
=== João, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-9-1]]

^<<v43-9-1,1>>^ E passando Jesus, viu um homem cego de nascença.

[[v43-9-2]]

^<<v43-9-2,2>>^ Perguntaram-lhe os seus discípulos: Rabi, quem pecou, este ou seus pais, para que nascesse cego?

[[v43-9-3]]

^<<v43-9-3,3>>^ Respondeu Jesus: Nem ele pecou nem seus pais; mas foi para que nele se manifestem as obras de Deus.

[[v43-9-4]]

^<<v43-9-4,4>>^ Importa que façamos as obras daquele que me enviou, enquanto é dia; vem a noite, quando ninguém pode trabalhar.

[[v43-9-5]]

^<<v43-9-5,5>>^ Enquanto estou no mundo, sou a luz do mundo.

[[v43-9-6]]

^<<v43-9-6,6>>^ Dito isto, cuspiu no chão e com a saliva fez lodo, e untou com lodo os olhos do cego,

[[v43-9-7]]

^<<v43-9-7,7>>^ e disse-lhe: Vai, lava-te no tanque de Siloé &#123;que significa Enviado&#125;. E ele foi, lavou-se, e voltou vendo.

[[v43-9-8]]

^<<v43-9-8,8>>^ Então os vizinhos e aqueles que antes o tinham visto, quando mendigo, perguntavam: Não é este o mesmo que se sentava a mendigar?

[[v43-9-9]]

^<<v43-9-9,9>>^ Uns diziam: É ele. E outros: Não é, mas se parece com ele. Ele dizia: Sou eu.

[[v43-9-10]]

^<<v43-9-10,10>>^ Perguntaram-lhe, pois: Como se te abriram os olhos?

[[v43-9-11]]

^<<v43-9-11,11>>^ Respondeu ele: O homem que se chama Jesus fez lodo, untou-me os olhos, e disse-me: Vai a Siloé e lava-te. Fui, pois, lavei-me, e fiquei vendo.

[[v43-9-12]]

^<<v43-9-12,12>>^ E perguntaram-lhe: Onde está ele? Respondeu: Não sei.

[[v43-9-13]]

^<<v43-9-13,13>>^ Levaram aos fariseus o que fora cego.

[[v43-9-14]]

^<<v43-9-14,14>>^ Ora, era sábado o dia em que Jesus fez o lodo e lhe abriu os olhos.

[[v43-9-15]]

^<<v43-9-15,15>>^ Então os fariseus também se puseram a perguntar-lhe como recebera a vista. Respondeu-lhes ele: Pôs-me lodo sobre os olhos, lavei-me e vejo.

[[v43-9-16]]

^<<v43-9-16,16>>^ Por isso alguns dos fariseus diziam: Este homem não é de Deus; pois não guarda o sábado. Diziam outros: Como pode um homem pecador fazer tais sinais? E havia dissensão entre eles.

[[v43-9-17]]

^<<v43-9-17,17>>^ Tornaram, pois, a perguntar ao cego: Que dizes tu a respeito dele, visto que te abriu os olhos? E ele respondeu: É profeta.

[[v43-9-18]]

^<<v43-9-18,18>>^ Os judeus, porém, não acreditaram que ele tivesse sido cego e recebido a vista, enquanto não chamaram os pais do que fora curado,

[[v43-9-19]]

^<<v43-9-19,19>>^ e lhes perguntaram: É este o vosso filho, que dizeis ter nascido cego? Como, pois, vê agora?

[[v43-9-20]]

^<<v43-9-20,20>>^ Responderam seus pais: Sabemos que este é o nosso filho, e que nasceu cego;

[[v43-9-21]]

^<<v43-9-21,21>>^ mas como agora vê, não sabemos; ou quem lhe abriu os olhos, nós não sabemos; perguntai a ele mesmo; tem idade; ele falará por si mesmo.

[[v43-9-22]]

^<<v43-9-22,22>>^ Isso disseram seus pais, porque temiam os judeus, porquanto já tinham estes combinado que se alguém confessasse ser Jesus o Cristo, fosse expulso da sinagoga.

[[v43-9-23]]

^<<v43-9-23,23>>^ Por isso é que seus pais disseram: Tem idade, perguntai-lho a ele mesmo.

[[v43-9-24]]

^<<v43-9-24,24>>^ Então chamaram pela segunda vez o homem que fora cego, e lhe disseram: Dá glória a Deus; nós sabemos que esse homem é pecador.

[[v43-9-25]]

^<<v43-9-25,25>>^ Respondeu ele: Se é pecador, não sei; uma coisa sei: eu era cego, e agora vejo.

[[v43-9-26]]

^<<v43-9-26,26>>^ Perguntaram-lhe pois: Que foi que te fez? Como te abriu os olhos?

[[v43-9-27]]

^<<v43-9-27,27>>^ Respondeu-lhes: Já vo-lo disse, e não atendestes; para que o quereis tornar a ouvir? Acaso também vós quereis tornar-vos discípulos dele?

[[v43-9-28]]

^<<v43-9-28,28>>^ Então o injuriaram, e disseram: Discípulo dele és tu; nós porém, somos discípulos de Moisés.

[[v43-9-29]]

^<<v43-9-29,29>>^ Sabemos que Deus falou a Moisés; mas quanto a este, não sabemos donde é.

[[v43-9-30]]

^<<v43-9-30,30>>^ Respondeu-lhes o homem: Nisto, pois, está a maravilha: não sabeis donde ele é, e entretanto ele me abriu os olhos;

[[v43-9-31]]

^<<v43-9-31,31>>^ sabemos que Deus não ouve a pecadores; mas, se alguém for temente a Deus, e fizer a sua vontade, a esse ele ouve.

[[v43-9-32]]

^<<v43-9-32,32>>^ Desde o princípio do mundo nunca se ouviu que alguém abrisse os olhos a um cego de nascença.

[[v43-9-33]]

^<<v43-9-33,33>>^ Se este não fosse de Deus, nada poderia fazer.

[[v43-9-34]]

^<<v43-9-34,34>>^ Replicaram-lhe eles: Tu nasceste todo em pecados, e vens nos ensinar a nós? E expulsaram-no.

[[v43-9-35]]

^<<v43-9-35,35>>^ Soube Jesus que o haviam expulsado; e achando-o perguntou-lhe: Crês tu no Filho do homem?

[[v43-9-36]]

^<<v43-9-36,36>>^ Respondeu ele: Quem é, senhor, para que nele creia?

[[v43-9-37]]

^<<v43-9-37,37>>^ Disse-lhe Jesus: Já o viste, e é ele quem fala contigo.

[[v43-9-38]]

^<<v43-9-38,38>>^ Disse o homem: Creio, Senhor! E o adorou.

[[v43-9-39]]

^<<v43-9-39,39>>^ Prosseguiu então Jesus: Eu vim a este mundo para juízo, a fim de que os que não vêem vejam, e os que vêem se tornem cegos.

[[v43-9-40]]

^<<v43-9-40,40>>^ Alguns fariseus que ali estavam com ele, ouvindo isso, perguntaram-lhe: Porventura somos nós também cegos?

[[v43-9-41]]

^<<v43-9-41,41>>^ Respondeu-lhes Jesus: Se fosseis cegos, não teríeis pecado; mas como agora dizeis: Nós vemos, permanece o vosso pecado.

'''

xref:043-joao/043-joao-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-joao/043-joao-010.adoc#v43-10-0[Próximo Capítulo &#62;]