include::./index.adoc[]

[[v43-16-0]]
=== João, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-16-1]]

^<<v43-16-1,1>>^ Tenho-vos dito estas coisas para que não vos escandalizeis.

[[v43-16-2]]

^<<v43-16-2,2>>^ Expulsar-vos-ão das sinagogas; ainda mais, vem a hora em que qualquer que vos matar julgará prestar um serviço a Deus.

[[v43-16-3]]

^<<v43-16-3,3>>^ E isto vos farão, porque não conheceram ao Pai nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Mas tenho-vos dito estas coisas, a fim de que, quando chegar aquela hora, vos lembreis de que eu vo-las tinha dito. Não vo-las disse desde o princípio, porque estava convosco.

[[v43-16-5]]

^<<v43-16-5,5>>^ Agora, porém, vou para aquele que me enviou; e nenhum de vós me pergunta: Para onde vais?

[[v43-16-6]]

^<<v43-16-6,6>>^ Antes, porque vos disse isto, o vosso coração se encheu de tristeza.

[[v43-16-7]]

^<<v43-16-7,7>>^ Todavia, digo-vos a verdade, convém-vos que eu vá; pois se eu não for, o Ajudador não virá a vós; mas, se eu for, vo-lo enviarei.

[[v43-16-8]]

^<<v43-16-8,8>>^ E quando ele vier, convencerá o mundo do pecado, da justiça e do juízo:

[[v43-16-9]]

^<<v43-16-9,9>>^ do pecado, porque não crêem em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ da justiça, porque vou para meu Pai, e não me vereis mais,

[[v43-16-11]]

^<<v43-16-11,11>>^ e do juízo, porque o príncipe deste mundo já está julgado.

[[v43-16-12]]

^<<v43-16-12,12>>^ Ainda tenho muito que vos dizer; mas vós não o podeis suportar agora.

[[v43-16-13]]

^<<v43-16-13,13>>^ Quando vier, porém, aquele, o Espírito da verdade, ele vos guiará a toda a verdade; porque não falará por si mesmo, mas dirá o que tiver ouvido, e vos anunciará as coisas vindouras.

[[v43-16-14]]

^<<v43-16-14,14>>^ Ele me glorificará, porque receberá do que é meu, e vo-lo anunciará.

[[v43-16-15]]

^<<v43-16-15,15>>^ Tudo quanto o Pai tem é meu; por isso eu vos disse que ele, recebendo do que é meu, vo-lo anunciará.

[[v43-16-16]]

^<<v43-16-16,16>>^ Um pouco, e já não me vereis; e outra vez um pouco, e ver-me-eis.

[[v43-16-17]]

^<<v43-16-17,17>>^ Então alguns dos seus discípulos perguntaram uns para os outros: Que é isto que nos diz? Um pouco, e não me vereis; e outra vez um pouco, e ver-me-eis; e: Porquanto vou para o Pai?

[[v43-16-18]]

^<<v43-16-18,18>>^ Diziam pois: Que quer dizer isto: Um pouco? Não compreendemos o que ele está dizendo.

[[v43-16-19]]

^<<v43-16-19,19>>^ Percebeu Jesus que o queriam interrogar, e disse-lhes: Indagais entre vós acerca disto que disse: Um pouco, e não me vereis; e outra vez um pouco, e ver-me-eis?

[[v43-16-20]]

^<<v43-16-20,20>>^ Em verdade, em verdade, vos digo que vós chorareis e vos lamentareis, mas o mundo se alegrará; vós estareis tristes, porém a vossa tristeza se converterá em alegria.

[[v43-16-21]]

^<<v43-16-21,21>>^ A mulher, quando está para dar à luz, sente tristeza porque é chegada a sua hora; mas, depois de ter dado à luz a criança, já não se lembra da aflição, pelo gozo de haver um homem nascido ao mundo.

[[v43-16-22]]

^<<v43-16-22,22>>^ Assim também vós agora, na verdade, tendes tristeza; mas eu vos tornarei a ver, e alegrar-se-á o vosso coração, e a vossa alegria ninguém vo-la tirará.

[[v43-16-23]]

^<<v43-16-23,23>>^ Naquele dia nada me perguntareis. Em verdade, em verdade vos digo que tudo quanto pedirdes ao Pai, ele vo-lo concederá em meu nome.

[[v43-16-24]]

^<<v43-16-24,24>>^ Até agora nada pedistes em meu nome; pedi, e recebereis, para que o vosso gozo seja completo.

[[v43-16-25]]

^<<v43-16-25,25>>^ Disse-vos estas coisas por figuras; chega, porém, a hora em que vos não falarei mais por figuras, mas abertamente vos falarei acerca do Pai.

[[v43-16-26]]

^<<v43-16-26,26>>^ Naquele dia pedireis em meu nome, e não vos digo que eu rogarei por vós ao Pai;

[[v43-16-27]]

^<<v43-16-27,27>>^ pois o Pai mesmo vos ama; visto que vós me amastes e crestes que eu saí de Deus.

[[v43-16-28]]

^<<v43-16-28,28>>^ Saí do Pai, e vim ao mundo; outra vez deixo o mundo, e vou para o Pai.

[[v43-16-29]]

^<<v43-16-29,29>>^ Disseram os seus discípulos: Eis que agora falas abertamente, e não por figura alguma.

[[v43-16-30]]

^<<v43-16-30,30>>^ Agora conhecemos que sabes todas as coisas, e não necessitas de que alguém te interrogue. Por isso cremos que saíste de Deus.

[[v43-16-31]]

^<<v43-16-31,31>>^ Respondeu-lhes Jesus: Credes agora?

[[v43-16-32]]

^<<v43-16-32,32>>^ Eis que vem a hora, e já é chegada, em que vós sereis dispersos cada um para o seu lado, e me deixareis só; mas não estou só, porque o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Tenho-vos dito estas coisas, para que em mim tenhais paz. No mundo tereis tribulações; mas tende bom ânimo, eu venci o mundo.

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]