include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-4-1]]

^<<v43-4-1,1>>^ Quando, pois, o Senhor soube que os fariseus tinham ouvido dizer que ele, Jesus, fazia e batizava mais discípulos do que João

[[v43-4-2]]

^<<v43-4-2,2>>^ &#123;ainda que Jesus mesmo não batizava, mas os seus discípulos&#125;

[[v43-4-3]]

^<<v43-4-3,3>>^ deixou a Judéia, e foi outra vez para a Galiléia.

[[v43-4-4]]

^<<v43-4-4,4>>^ E era-lhe necessário passar por Samária.

[[v43-4-5]]

^<<v43-4-5,5>>^ Chegou, pois, a uma cidade de Samária, chamada Sicar, junto da herdade que Jacó dera a seu filho José;

[[v43-4-6]]

^<<v43-4-6,6>>^ achava-se ali o poço de Jacó. Jesus, pois, cansado da viagem, sentou-se assim junto do poço; era cerca da hora sexta.

[[v43-4-7]]

^<<v43-4-7,7>>^ Veio uma mulher de Samária tirar água. Disse-lhe Jesus: Dá-me de beber.

[[v43-4-8]]

^<<v43-4-8,8>>^ Pois seus discípulos tinham ido à cidade comprar comida.

[[v43-4-9]]

^<<v43-4-9,9>>^ Disse-lhe então a mulher samaritana: Como, sendo tu judeu, me pedes de beber a mim, que sou mulher samaritana? &#123;Porque os judeus não se comunicavam com os samaritanos.&#125;

[[v43-4-10]]

^<<v43-4-10,10>>^ Respondeu-lhe Jesus: Se tivesses conhecido o dom de Deus e quem é o que te diz: Dá-me de beber, tu lhe terias pedido e ele te haveria dado água viva.

[[v43-4-11]]

^<<v43-4-11,11>>^ Disse-lhe a mulher: Senhor, tu não tens com que tirá-la, e o poço é fundo; donde, pois, tens essa água viva?

[[v43-4-12]]

^<<v43-4-12,12>>^ És tu, porventura, maior do que o nosso pai Jacó, que nos deu o poço, do qual também ele mesmo bebeu, e os filhos, e o seu gado?.

[[v43-4-13]]

^<<v43-4-13,13>>^ Replicou-lhe Jesus: Todo o que beber desta água tornará a ter sede;

[[v43-4-14]]

^<<v43-4-14,14>>^ mas aquele que beber da água que eu lhe der nunca terá sede; pelo contrário, a água que eu lhe der se fará nele uma fonte de água que jorre para a vida eterna.

[[v43-4-15]]

^<<v43-4-15,15>>^ Disse-lhe a mulher: Senhor, dá-me dessa água, para que não mais tenha sede, nem venha aqui tirá-la.

[[v43-4-16]]

^<<v43-4-16,16>>^ Disse-lhe Jesus: Vai, chama o teu marido e vem cá.

[[v43-4-17]]

^<<v43-4-17,17>>^ Respondeu a mulher: Não tenho marido. Disse-lhe Jesus: Disseste bem: Não tenho marido;

[[v43-4-18]]

^<<v43-4-18,18>>^ porque cinco maridos tiveste, e o que agora tens não é teu marido; isso disseste com verdade.

[[v43-4-19]]

^<<v43-4-19,19>>^ Disse-lhe a mulher: Senhor, vejo que és profeta.

[[v43-4-20]]

^<<v43-4-20,20>>^ Nossos pais adoraram neste monte, e vós dizeis que em Jerusalém é o lugar onde se deve adorar.

[[v43-4-21]]

^<<v43-4-21,21>>^ Disse-lhe Jesus: Mulher, crê-me, a hora vem, em que nem neste monte, nem em Jerusalém adorareis o Pai.

[[v43-4-22]]

^<<v43-4-22,22>>^ Vós adorais o que não conheceis; nós adoramos o que conhecemos; porque a salvação vem dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ Mas a hora vem, e agora é, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a tais que assim o adorem.

[[v43-4-24]]

^<<v43-4-24,24>>^ Deus é Espírito, e é necessário que os que o adoram o adorem em espírito e em verdade.

[[v43-4-25]]

^<<v43-4-25,25>>^ Replicou-lhe a mulher: Eu sei que vem o Messias &#123;que se chama o Cristo&#125;; quando ele vier há de nos anunciar todas as coisas.

[[v43-4-26]]

^<<v43-4-26,26>>^ Disse-lhe Jesus: Eu o sou, eu que falo contigo.

[[v43-4-27]]

^<<v43-4-27,27>>^ E nisto vieram os seus discípulos, e se admiravam de que estivesse falando com uma mulher; todavia nenhum lhe perguntou: Que é que procuras? ou: Por que falas com ela?

[[v43-4-28]]

^<<v43-4-28,28>>^ Deixou, pois, a mulher o seu cântaro, foi à cidade e disse àqueles homens:

[[v43-4-29]]

^<<v43-4-29,29>>^ Vinde, vede um homem que me disse tudo quanto eu tenho feito; será este, porventura, o Cristo?

[[v43-4-30]]

^<<v43-4-30,30>>^ Saíram, pois, da cidade e vinham ter com ele.

[[v43-4-31]]

^<<v43-4-31,31>>^ Entrementes os seus discípulos lhe rogavam, dizendo: Rabi, come.

[[v43-4-32]]

^<<v43-4-32,32>>^ Ele, porém, respondeu: Uma comida tenho para comer que vós não conheceis.

[[v43-4-33]]

^<<v43-4-33,33>>^ Então os discípulos diziam uns aos outros: Acaso alguém lhe trouxe de comer?

[[v43-4-34]]

^<<v43-4-34,34>>^ Disse-lhes Jesus: A minha comida é fazer a vontade daquele que me enviou, e completar a sua obra.

[[v43-4-35]]

^<<v43-4-35,35>>^ Não dizeis vós: Ainda há quatro meses até que venha a ceifa? Ora, eu vos digo: levantai os vossos olhos, e vede os campos, que já estão brancos para a ceifa.

[[v43-4-36]]

^<<v43-4-36,36>>^ Quem ceifa já está recebendo recompensa e ajuntando fruto para a vida eterna; para que o que semeia e o que ceifa juntamente se regozijem.

[[v43-4-37]]

^<<v43-4-37,37>>^ Porque nisto é verdadeiro o ditado: Um é o que semeia, e outro o que ceifa.

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu vos enviei a ceifar onde não trabalhaste; outros trabalharam, e vós entrastes no seu trabalho.

[[v43-4-39]]

^<<v43-4-39,39>>^ E muitos samaritanos daquela cidade creram nele, por causa da palavra da mulher, que testificava: Ele me disse tudo quanto tenho feito.

[[v43-4-40]]

^<<v43-4-40,40>>^ Indo, pois, ter com ele os samaritanos, rogaram-lhe que ficasse com eles; e ficou ali dois dias.

[[v43-4-41]]

^<<v43-4-41,41>>^ E muitos mais creram por causa da palavra dele;

[[v43-4-42]]

^<<v43-4-42,42>>^ e diziam à mulher: Já não é pela tua palavra que nós cremos; pois agora nós mesmos temos ouvido e sabemos que este é verdadeiramente o Salvador do mundo.

[[v43-4-43]]

^<<v43-4-43,43>>^ Passados os dois dias partiu dali para a Galiléia.

[[v43-4-44]]

^<<v43-4-44,44>>^ Porque Jesus mesmo testificou que um profeta não recebe honra na sua própria pátria.

[[v43-4-45]]

^<<v43-4-45,45>>^ Assim, pois, que chegou à Galiléia, os galileus o receberam, porque tinham visto todas as coisas que fizera em Jerusalém na ocasião da festa; pois também eles tinham ido à festa.

[[v43-4-46]]

^<<v43-4-46,46>>^ Foi, então, outra vez a Caná da Galiléia, onde da água fizera vinho. Ora, havia um oficial do rei, cujo filho estava enfermo em Cafarnaum.

[[v43-4-47]]

^<<v43-4-47,47>>^ Quando ele soube que Jesus tinha vindo da Judéia para a Galiléia, foi ter com ele, e lhe rogou que descesse e lhe curasse o filho; pois estava à morte.

[[v43-4-48]]

^<<v43-4-48,48>>^ Então Jesus lhe disse: Se não virdes sinais e prodígios, de modo algum crereis.

[[v43-4-49]]

^<<v43-4-49,49>>^ Rogou-lhe o oficial: Senhor, desce antes que meu filho morra.

[[v43-4-50]]

^<<v43-4-50,50>>^ Respondeu-lhe Jesus: Vai, o teu filho vive. E o homem creu na palavra que Jesus lhe dissera, e partiu.

[[v43-4-51]]

^<<v43-4-51,51>>^ Quando ele já ia descendo, saíram-lhe ao encontro os seus servos, e lhe disseram que seu filho vivia.

[[v43-4-52]]

^<<v43-4-52,52>>^ Perguntou-lhes, pois, a que hora começara a melhorar; ao que lhe disseram: Ontem à hora sétima a febre o deixou.

[[v43-4-53]]

^<<v43-4-53,53>>^ Reconheceu, pois, o pai ser aquela hora a mesma em que Jesus lhe dissera: O teu filho vive; e creu ele e toda a sua casa.

[[v43-4-54]]

^<<v43-4-54,54>>^ Foi esta a segunda vez que Jesus, ao voltar da Judéia para a Galiléia, ali operou sinal.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]