include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-1-1]]

^<<v43-1-1,1>>^ No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.

[[v43-1-2]]

^<<v43-1-2,2>>^ Ele estava no princípio com Deus.

[[v43-1-3]]

^<<v43-1-3,3>>^ Todas as coisas foram feitas por intermédio dele, e sem ele nada do que foi feito se fez.

[[v43-1-4]]

^<<v43-1-4,4>>^ Nele estava a vida, e a vida era a luz dos homens;

[[v43-1-5]]

^<<v43-1-5,5>>^ a luz resplandece nas trevas, e as trevas não prevaleceram contra ela.

[[v43-1-6]]

^<<v43-1-6,6>>^ Houve um homem enviado de Deus, cujo nome era João.

[[v43-1-7]]

^<<v43-1-7,7>>^ Este veio como testemunha, a fim de dar testemunho da luz, para que todos cressem por meio dele.

[[v43-1-8]]

^<<v43-1-8,8>>^ Ele não era a luz, mas veio para dar testemunho da luz.

[[v43-1-9]]

^<<v43-1-9,9>>^ Pois a verdadeira luz, que alumia a todo homem, estava chegando ao mundo.

[[v43-1-10]]

^<<v43-1-10,10>>^ Estava ele no mundo, e o mundo foi feito por intermédio dele, e o mundo não o conheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Veio para o que era seu, e os seus não o receberam.

[[v43-1-12]]

^<<v43-1-12,12>>^ Mas, a todos quantos o receberam, aos que crêem no seu nome, deu-lhes o poder de se tornarem filhos de Deus;

[[v43-1-13]]

^<<v43-1-13,13>>^ os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do varão, mas de Deus.

[[v43-1-14]]

^<<v43-1-14,14>>^ E o Verbo se fez carne, e habitou entre nós, cheio de graça e de verdade; e vimos a sua glória, como a glória do unigênito do Pai.

[[v43-1-15]]

^<<v43-1-15,15>>^ João deu testemunho dele, e clamou, dizendo: Este é aquele de quem eu disse: O que vem depois de mim, passou adiante de mim; porque antes de mim ele já existia.

[[v43-1-16]]

^<<v43-1-16,16>>^ Pois todos nós recebemos da sua plenitude, e graça sobre graça.

[[v43-1-17]]

^<<v43-1-17,17>>^ Porque a lei foi dada por meio de Moisés; a graça e a verdade vieram por Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Ninguém jamais viu a Deus. O Deus unigênito, que está no seio do Pai, esse o deu a conhecer.

[[v43-1-19]]

^<<v43-1-19,19>>^ E este foi o testemunho de João, quando os judeus lhe enviaram de Jerusalém sacerdotes e levitas para que lhe perguntassem: Quem és tu?

[[v43-1-20]]

^<<v43-1-20,20>>^ Ele, pois, confessou e não negou; sim, confessou: Eu não sou o Cristo.

[[v43-1-21]]

^<<v43-1-21,21>>^ Ao que lhe perguntaram: Pois que? És tu Elias? Respondeu ele: Não sou. És tu o profeta? E respondeu: Não.

[[v43-1-22]]

^<<v43-1-22,22>>^ Disseram-lhe, pois: Quem és? para podermos dar resposta aos que nos enviaram; que dizes de ti mesmo?

[[v43-1-23]]

^<<v43-1-23,23>>^ Respondeu ele: Eu sou a voz do que clama no deserto: Endireitai o caminho do Senhor, como disse o profeta Isaías.

[[v43-1-24]]

^<<v43-1-24,24>>^ E os que tinham sido enviados eram dos fariseus.

[[v43-1-25]]

^<<v43-1-25,25>>^ Então lhe perguntaram: Por que batizas, pois, se tu não és o Cristo, nem Elias, nem o profeta?

[[v43-1-26]]

^<<v43-1-26,26>>^ Respondeu-lhes João: Eu batizo em água; no meio de vós está um a quem vós não conheceis.

[[v43-1-27]]

^<<v43-1-27,27>>^ aquele que vem depois de mim, de quem eu não sou digno de desatar a correia da alparca.

[[v43-1-28]]

^<<v43-1-28,28>>^ Estas coisas aconteceram em Betânia, além do Jordão, onde João estava batizando.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte João viu a Jesus, que vinha para ele, e disse: Eis o Cordeiro de Deus, que tira o pecado do mundo.

[[v43-1-30]]

^<<v43-1-30,30>>^ este é aquele de quem eu disse: Depois de mim vem um varão que passou adiante de mim, porque antes de mim ele já existia.

[[v43-1-31]]

^<<v43-1-31,31>>^ Eu não o conhecia; mas, para que ele fosse manifestado a Israel, é que vim batizando em água.

[[v43-1-32]]

^<<v43-1-32,32>>^ E João deu testemunho, dizendo: Vi o Espírito descer do céu como pomba, e repousar sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ Eu não o conhecia; mas o que me enviou a batizar em água, esse me disse: Aquele sobre quem vires descer o Espírito, e sobre ele permanecer, esse é o que batiza no Espírito Santo.

[[v43-1-34]]

^<<v43-1-34,34>>^ Eu mesmo vi e já vos dei testemunho de que este é o Filho de Deus.

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte João estava outra vez ali, com dois dos seus discípulos

[[v43-1-36]]

^<<v43-1-36,36>>^ e, olhando para Jesus, que passava, disse: Eis o Cordeiro de Deus!

[[v43-1-37]]

^<<v43-1-37,37>>^ Aqueles dois discípulos ouviram-no dizer isto, e seguiram a Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ Voltando-se Jesus e vendo que o seguiam, perguntou-lhes: Que buscais? Disseram-lhe eles: rabi &#123;que, traduzido, quer dizer Mestre&#125;, onde pousas?

[[v43-1-39]]

^<<v43-1-39,39>>^ Respondeu-lhes: Vinde, e vereis. Foram, pois, e viram onde pousava; e passaram o dia com ele; era cerca da hora décima.

[[v43-1-40]]

^<<v43-1-40,40>>^ André, irmão de Simão Pedro, era um dos dois que ouviram João falar, e que seguiram a Jesus.

[[v43-1-41]]

^<<v43-1-41,41>>^ Ele achou primeiro a seu irmão Simão, e disse-lhe: Havemos achado o Messias &#123;que, traduzido, quer dizer Cristo&#125;.

[[v43-1-42]]

^<<v43-1-42,42>>^ E o levou a Jesus. Jesus, fixando nele o olhar, disse: Tu és Simão, filho de João, tu serás chamado Cefas &#123;que quer dizer Pedro&#125;.

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia seguinte Jesus resolveu partir para a Galiléia, e achando a Felipe disse-lhe: Segue-me.

[[v43-1-44]]

^<<v43-1-44,44>>^ Ora, Felipe era de Betsaida, cidade de André e de Pedro.

[[v43-1-45]]

^<<v43-1-45,45>>^ Felipe achou a Natanael, e disse-lhe: Acabamos de achar aquele de quem escreveram Moisés na lei, e os profetas: Jesus de Nazaré, filho de José.

[[v43-1-46]]

^<<v43-1-46,46>>^ Perguntou-lhe Natanael: Pode haver coisa bem vinda de Nazaré? Disse-lhe Felipe: Vem e vê.

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus, vendo Natanael aproximar-se dele, disse a seu respeito: Eis um verdadeiro israelita, em quem não há dolo!

[[v43-1-48]]

^<<v43-1-48,48>>^ Perguntou-lhe Natanael: Donde me conheces? Respondeu-lhe Jesus: Antes que Felipe te chamasse, eu te vi, quando estavas debaixo da figueira.

[[v43-1-49]]

^<<v43-1-49,49>>^ Respondeu-lhe Natanael: Rabi, tu és o Filho de Deus, tu és rei de Israel.

[[v43-1-50]]

^<<v43-1-50,50>>^ Ao que lhe disse Jesus: Porque te disse: Vi-te debaixo da figueira, crês? coisas maiores do que estas verás.

[[v43-1-51]]

^<<v43-1-51,51>>^ E acrescentou: Em verdade, em verdade vos digo que vereis o céu aberto, e os anjos de Deus subindo e descendo sobre o Filho do homem.

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]