include::./index.adoc[]

[[v43-6-0]]
=== João, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-6-1]]

^<<v43-6-1,1>>^ Depois disto partiu Jesus para o outro lado do mar da Galiléia, também chamado de Tiberíades.

[[v43-6-2]]

^<<v43-6-2,2>>^ E seguia-o uma grande multidão, porque via os sinais que operava sobre os enfermos.

[[v43-6-3]]

^<<v43-6-3,3>>^ Subiu, pois, Jesus ao monte e sentou-se ali com seus discípulos.

[[v43-6-4]]

^<<v43-6-4,4>>^ Ora, a páscoa, a festa dos judeus, estava próxima.

[[v43-6-5]]

^<<v43-6-5,5>>^ Então Jesus, levantando os olhos, e vendo que uma grande multidão vinha ter com ele, disse a Felipe: Onde compraremos pão, para estes comerem?

[[v43-6-6]]

^<<v43-6-6,6>>^ Mas dizia isto para o experimentar; pois ele bem sabia o que ia fazer.

[[v43-6-7]]

^<<v43-6-7,7>>^ Respondeu-lhe Felipe: Duzentos denários de pão não lhes bastam, para que cada um receba um pouco.

[[v43-6-8]]

^<<v43-6-8,8>>^ Ao que lhe disse um dos seus discípulos, André, irmão de Simão Pedro:

[[v43-6-9]]

^<<v43-6-9,9>>^ Está aqui um rapaz que tem cinco pães de cevada e dois peixinhos; mas que é isto para tantos?

[[v43-6-10]]

^<<v43-6-10,10>>^ Disse Jesus: Fazei reclinar-se o povo. Ora, naquele lugar havia muita relva. Reclinaram-se aí, pois, os homens em número de quase cinco mil.

[[v43-6-11]]

^<<v43-6-11,11>>^ Jesus, então, tomou os pães e, havendo dado graças, repartiu-os pelos que estavam reclinados; e de igual modo os peixes, quanto eles queriam.

[[v43-6-12]]

^<<v43-6-12,12>>^ E quando estavam saciados, disse aos seus discípulos: Recolhei os pedaços que sobejaram, para que nada se perca.

[[v43-6-13]]

^<<v43-6-13,13>>^ Recolheram-nos, pois e encheram doze cestos de pedaços dos cinco pães de cevada, que sobejaram aos que haviam comido.

[[v43-6-14]]

^<<v43-6-14,14>>^ Vendo, pois, aqueles homens o sinal que Jesus operara, diziam: este é verdadeiramente o profeta que havia de vir ao mundo.

[[v43-6-15]]

^<<v43-6-15,15>>^ Percebendo, pois, Jesus que estavam prestes a vir e levá-lo à força para o fazerem rei, tornou a retirar-se para o monte, ele sozinho.

[[v43-6-16]]

^<<v43-6-16,16>>^ Ao cair da tarde, desceram os seus discípulos ao mar;

[[v43-6-17]]

^<<v43-6-17,17>>^ e, entrando num barco, atravessavam o mar em direção a Cafarnaum; enquanto isso, escurecera e Jesus ainda não tinha vindo ter com eles;

[[v43-6-18]]

^<<v43-6-18,18>>^ ademais, o mar se empolava, porque soprava forte vento.

[[v43-6-19]]

^<<v43-6-19,19>>^ Tendo, pois, remado uns vinte e cinco ou trinta estádios, viram a Jesus andando sobre o mar e aproximando-se do barco; e ficaram atemorizados.

[[v43-6-20]]

^<<v43-6-20,20>>^ Mas ele lhes disse: Sou eu; não temais.

[[v43-6-21]]

^<<v43-6-21,21>>^ Então eles de boa mente o receberam no barco; e logo o barco chegou à terra para onde iam.

[[v43-6-22]]

^<<v43-6-22,22>>^ No dia seguinte, a multidão que ficara no outro lado do mar, sabendo que não houvera ali senão um barquinho, e que Jesus não embarcara nele com seus discípulos, mas que estes tinham ido sós

[[v43-6-23]]

^<<v43-6-23,23>>^ &#123;contudo, outros barquinhos haviam chegado a Tiberíades para perto do lugar onde comeram o pão, havendo o Senhor dado graças&#125;;

[[v43-6-24]]

^<<v43-6-24,24>>^ quando, pois, viram que Jesus não estava ali nem os seus discípulos, entraram eles também nos barcos, e foram a Cafarnaum, em busca de Jesus.

[[v43-6-25]]

^<<v43-6-25,25>>^ E, achando-o no outro lado do mar, perguntaram-lhe: Rabi, quando chegaste aqui?

[[v43-6-26]]

^<<v43-6-26,26>>^ Respondeu-lhes Jesus: Em verdade, em verdade vos digo que me buscais, não porque vistes sinais, mas porque comestes do pão e vos saciastes.

[[v43-6-27]]

^<<v43-6-27,27>>^ Trabalhai, não pela comida que perece, mas pela comida que permanece para a vida eterna, a qual o Filho do homem vos dará; pois neste, Deus, o Pai, imprimiu o seu selo.

[[v43-6-28]]

^<<v43-6-28,28>>^ Pergutaram-lhe, pois: Que havemos de fazer para praticarmos as obras de Deus?

[[v43-6-29]]

^<<v43-6-29,29>>^ Jesus lhes respondeu: A obra de Deus é esta: Que creiais naquele que ele enviou.

[[v43-6-30]]

^<<v43-6-30,30>>^ Perguntaram-lhe, então: Que sinal, pois, fazes tu, para que o vejamos e te creiamos? Que operas tu?

[[v43-6-31]]

^<<v43-6-31,31>>^ Nossos pais comeram o maná no deserto, como está escrito: Do céu deu-lhes pão a comer.

[[v43-6-32]]

^<<v43-6-32,32>>^ Respondeu-lhes Jesus: Em verdade, em verdade vos digo: Não foi Moisés que vos deu o pão do céu; mas meu Pai vos dá o verdadeiro pão do céu.

[[v43-6-33]]

^<<v43-6-33,33>>^ Porque o pão de Deus é aquele que desce do céu e dá vida ao mundo.

[[v43-6-34]]

^<<v43-6-34,34>>^ Disseram-lhe, pois: Senhor, dá-nos sempre desse pão.

[[v43-6-35]]

^<<v43-6-35,35>>^ Declarou-lhes Jesus. Eu sou o pão da vida; aquele que vem a mim, de modo algum terá fome, e quem crê em mim jamais terá sede.

[[v43-6-36]]

^<<v43-6-36,36>>^ Mas como já vos disse, vós me tendes visto, e contudo não credes.

[[v43-6-37]]

^<<v43-6-37,37>>^ Todo o que o Pai me dá virá a mim; e o que vem a mim de maneira nenhuma o lançarei fora.

[[v43-6-38]]

^<<v43-6-38,38>>^ Porque eu desci do céu, não para fazer a minha vontade, mas a vontade daquele que me enviou.

[[v43-6-39]]

^<<v43-6-39,39>>^ E a vontade do que me enviou é esta: Que eu não perca nenhum de todos aqueles que me deu, mas que eu o ressuscite no último dia.

[[v43-6-40]]

^<<v43-6-40,40>>^ Porquanto esta é a vontade de meu Pai: Que todo aquele que vê o Filho e crê nele, tenha a vida eterna; e eu o ressuscitarei no último dia.

[[v43-6-41]]

^<<v43-6-41,41>>^ Murmuravam, pois, dele os judeus, porque dissera: Eu sou o pão que desceu do céu;

[[v43-6-42]]

^<<v43-6-42,42>>^ e perguntavam: Não é Jesus, o filho de José, cujo pai e mãe nós conhecemos? Como, pois, diz agora: Desci do céu?

[[v43-6-43]]

^<<v43-6-43,43>>^ Respondeu-lhes Jesus: Não murmureis entre vós.

[[v43-6-44]]

^<<v43-6-44,44>>^ Ninguém pode vir a mim, se o Pai que me enviou não o trouxer; e eu o ressuscitarei no último dia.

[[v43-6-45]]

^<<v43-6-45,45>>^ Está escrito nos profetas: E serão todos ensinados por Deus. Portanto todo aquele que do Pai ouviu e aprendeu vem a mim.

[[v43-6-46]]

^<<v43-6-46,46>>^ Não que alguém tenha visto o Pai, senão aquele que é vindo de Deus; só ele tem visto o Pai.

[[v43-6-47]]

^<<v43-6-47,47>>^ Em verdade, em verdade vos digo: Aquele que crê tem a vida eterna.

[[v43-6-48]]

^<<v43-6-48,48>>^ Eu sou o pão da vida.

[[v43-6-49]]

^<<v43-6-49,49>>^ Vossos pais comeram o maná no deserto e morreram.

[[v43-6-50]]

^<<v43-6-50,50>>^ Este é o pão que desce do céu, para que o que dele comer não morra.

[[v43-6-51]]

^<<v43-6-51,51>>^ Eu sou o pão vivo que desceu do céu; se alguém comer deste pão, viverá para sempre; e o pão que eu darei pela vida do mundo é a minha carne.

[[v43-6-52]]

^<<v43-6-52,52>>^ Disputavam, pois, os judeus entre si, dizendo: Como pode este dar-nos a sua carne a comer?

[[v43-6-53]]

^<<v43-6-53,53>>^ Disse-lhes Jesus: Em verdade, em verdade vos digo: Se não comerdes a carne do Filho do homem, e não beberdes o seu sangue, não tereis vida em vós mesmos.

[[v43-6-54]]

^<<v43-6-54,54>>^ Quem come a minha carne e bebe o meu sangue tem a vida eterna; e eu o ressuscitarei no último dia.

[[v43-6-55]]

^<<v43-6-55,55>>^ Porque a minha carne verdadeiramente é comida, e o meu sangue verdadeiramente é bebida.

[[v43-6-56]]

^<<v43-6-56,56>>^ Quem come a minha carne e bebe o meu sangue permanece em mim e eu nele.

[[v43-6-57]]

^<<v43-6-57,57>>^ Assim como o Pai, que vive, me enviou, e eu vivo pelo Pai, assim, quem de mim se alimenta, também viverá por mim.

[[v43-6-58]]

^<<v43-6-58,58>>^ Este é o pão que desceu do céu; não é como o caso de vossos pais, que comeram o maná e morreram; quem comer este pão viverá para sempre.

[[v43-6-59]]

^<<v43-6-59,59>>^ Estas coisas falou Jesus quando ensinava na sinagoga em Cafarnaum.

[[v43-6-60]]

^<<v43-6-60,60>>^ Muitos, pois, dos seus discípulos, ouvindo isto, disseram: Duro é este discurso; quem o pode ouvir?

[[v43-6-61]]

^<<v43-6-61,61>>^ Mas, sabendo Jesus em si mesmo que murmuravam disto os seus discípulos, disse-lhes: Isto vos escandaliza?

[[v43-6-62]]

^<<v43-6-62,62>>^ Que seria, pois, se vísseis subir o Filho do homem para onde primeiro estava?

[[v43-6-63]]

^<<v43-6-63,63>>^ O espírito é o que vivifica, a carne para nada aproveita; as palavras que eu vos tenho dito são espírito e são vida.

[[v43-6-64]]

^<<v43-6-64,64>>^ Mas há alguns de vós que não crêem. Pois Jesus sabia, desde o princípio, quem eram os que não criam, e quem era o que o havia de entregar.

[[v43-6-65]]

^<<v43-6-65,65>>^ E continuou: Por isso vos disse que ninguém pode vir a mim, se pelo Pai lhe não for concedido.

[[v43-6-66]]

^<<v43-6-66,66>>^ Por causa disso muitos dos seus discípulos voltaram para trás e não andaram mais com ele.

[[v43-6-67]]

^<<v43-6-67,67>>^ Perguntou então Jesus aos doze: Quereis vós também retirar-vos?

[[v43-6-68]]

^<<v43-6-68,68>>^ Respondeu-lhe Simão Pedro: Senhor, para quem iremos nós? Tu tens as palavras da vida eterna.

[[v43-6-69]]

^<<v43-6-69,69>>^ E nós já temos crido e bem sabemos que tu és o Santo de Deus.

[[v43-6-70]]

^<<v43-6-70,70>>^ Respondeu-lhes Jesus: Não vos escolhi a vós os doze? Contudo um de vós é o diabo.

[[v43-6-71]]

^<<v43-6-71,71>>^ Referia-se a Judas, filho de Simão Iscariotes; porque era ele o que o havia de entregar, sendo um dos doze.

'''

xref:043-joao/043-joao-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-joao/043-joao-007.adoc#v43-7-0[Próximo Capítulo &#62;]