include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v43-13-1]]

^<<v43-13-1,1>>^ Antes da festa da páscoa, sabendo Jesus que era chegada a sua hora de passar deste mundo para o Pai, e havendo amado os seus que estavam no mundo, amou-os até o fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Enquanto ceavam, tendo já o Diabo posto no coração de Judas, filho de Simão Iscariotes, que o traísse,

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus, sabendo que o Pai lhe entregara tudo nas mãos, e que viera de Deus e para Deus voltava,

[[v43-13-4]]

^<<v43-13-4,4>>^ levantou-se da ceia, tirou o manto e, tomando uma toalha, cingiu-se.

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois deitou água na bacia e começou a lavar os pés aos discípulos, e a enxugar-lhos com a toalha com que estava cingido.

[[v43-13-6]]

^<<v43-13-6,6>>^ Chegou, pois, a Simão Pedro, que lhe disse: Senhor, lavas-me os pés a mim?

[[v43-13-7]]

^<<v43-13-7,7>>^ Respondeu-lhe Jesus: O que eu faço, tu não o sabes agora; mas depois o entenderás.

[[v43-13-8]]

^<<v43-13-8,8>>^ Tornou-lhe Pedro: Nunca me lavarás os pés. Replicou-lhe Jesus: Se eu não te lavar, não tens parte comigo.

[[v43-13-9]]

^<<v43-13-9,9>>^ Disse-lhe Simão Pedro: Senhor, não somente os meus pés, mas também as mãos e a cabeça.

[[v43-13-10]]

^<<v43-13-10,10>>^ Respondeu-lhe Jesus: Aquele que se banhou não necessita de lavar senão os pés, pois no mais está todo limpo; e vós estais limpos, mas não todos.

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois ele sabia quem o estava traindo; por isso disse: Nem todos estais limpos.

[[v43-13-12]]

^<<v43-13-12,12>>^ Ora, depois de lhes ter lavado os pés, tomou o manto, tornou a reclinar-se à mesa e perguntou-lhes: Entendeis o que vos tenho feito?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vós me chamais Mestre e Senhor; e dizeis bem, porque eu o sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ Ora, se eu, o Senhor e Mestre, vos lavei os pés, também vós deveis lavar os pés uns aos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Porque eu vos dei exemplo, para que, como eu vos fiz, façais vós também.

[[v43-13-16]]

^<<v43-13-16,16>>^ Em verdade, em verdade vos digo: Não é o servo maior do que o seu senhor, nem o enviado maior do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Se sabeis estas coisas, bem-aventurados sois se as praticardes.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não falo de todos vós; eu conheço aqueles que escolhi; mas para que se cumprisse a escritura: O que comia do meu pão, levantou contra mim o seu calcanhar.

[[v43-13-19]]

^<<v43-13-19,19>>^ Desde já no-lo digo, antes que suceda, para que, quando suceder, creiais que eu sou.

[[v43-13-20]]

^<<v43-13-20,20>>^ Em verdade, em verdade vos digo: Quem receber aquele que eu enviar, a mim me recebe; e quem me recebe a mim, recebe aquele que me enviou.

[[v43-13-21]]

^<<v43-13-21,21>>^ Tendo Jesus dito isto, turbou-se em espírito, e declarou: Em verdade, em verdade vos digo que um de vós me há de trair.

[[v43-13-22]]

^<<v43-13-22,22>>^ Os discípulos se entreolhavam, perplexos, sem saber de quem ele falava.

[[v43-13-23]]

^<<v43-13-23,23>>^ Ora, achava-se reclinado sobre o peito de Jesus um de seus discípulos, aquele a quem Jesus amava.

[[v43-13-24]]

^<<v43-13-24,24>>^ A esse, pois, fez Simão Pedro sinal, e lhe pediu: Pergunta-lhe de quem é que fala.

[[v43-13-25]]

^<<v43-13-25,25>>^ Aquele discípulo, recostando-se assim ao peito de Jesus, perguntou-lhe: Senhor, quem é?

[[v43-13-26]]

^<<v43-13-26,26>>^ Respondeu Jesus: É aquele a quem eu der o pedaço de pão molhado. Tendo, pois, molhado um bocado de pão, deu-o a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ E, logo após o bocado, entrou nele Satanás. Disse-lhe, pois, Jesus: O que fazes, faze-o depressa.

[[v43-13-28]]

^<<v43-13-28,28>>^ E nenhum dos que estavam à mesa percebeu a que propósito lhe disse isto;

[[v43-13-29]]

^<<v43-13-29,29>>^ pois, como Judas tinha a bolsa, pensavam alguns que Jesus lhe queria dizer: Compra o que nos é necessário para a festa; ou, que desse alguma coisa aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Então ele, tendo recebido o bocado saiu logo. E era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Tendo ele, pois, saído, disse Jesus: Agora é glorificado o Filho do homem, e Deus é glorificado nele;

[[v43-13-32]]

^<<v43-13-32,32>>^ se Deus é glorificado nele, também Deus o glorificará em si mesmo, e logo o há de glorificar.

[[v43-13-33]]

^<<v43-13-33,33>>^ Filhinhos, ainda por um pouco estou convosco. Procurar-me-eis; e, como eu disse aos judeus, também a vós o digo agora: Para onde eu vou, não podeis vós ir.

[[v43-13-34]]

^<<v43-13-34,34>>^ Um novo mandamento vos dou: que vos ameis uns aos outros; assim como eu vos amei a vós, que também vós vos ameis uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Nisto conhecerão todos que sois meus discípulos, se tiverdes amor uns aos outros.

[[v43-13-36]]

^<<v43-13-36,36>>^ Perguntou-lhe Simão Pedro: Senhor, para onde vais? Respondeu Jesus; Para onde eu vou, não podes agora seguir-me; mais tarde, porém, me seguirás.

[[v43-13-37]]

^<<v43-13-37,37>>^ Disse-lhe Pedro: Por que não posso seguir-te agora? Por ti darei a minha vida.

[[v43-13-38]]

^<<v43-13-38,38>>^ Respondeu Jesus: Darás a tua vida por mim? Em verdade, em verdade te digo: Não cantará o galo até que me tenhas negado três vezes.

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]