include::./index.adoc[]

[[v36-1-0]]
=== Sofonias, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v36-1-1]]

^<<v36-1-1,1>>^ A palavra do Senhor que veio a Sofonias, filho de Cuche, filho de Gedalias, filho de Amarias, filho de Ezequias, nos dias de Josias, filho de Amom, rei de Judá.

[[v36-1-2]]

^<<v36-1-2,2>>^ Hei de consumir por completo tudo sobre a face da terra, diz o Senhor.

[[v36-1-3]]

^<<v36-1-3,3>>^ Consumirei os homens e os animais; consumirei as aves do céu, e os peixes do mar, e os tropeços juntamente com os ímpios; e exterminarei os homens de sobre a face da terra, diz o Senhor.

[[v36-1-4]]

^<<v36-1-4,4>>^ E estenderei a minha mão contra Judá, e contra todos os habitantes de Jerusalém; e exterminarei deste lugar o resto de Baal, e os nomes dos sacerdotes de ídolos, juntamente com os sacerdotes;

[[v36-1-5]]

^<<v36-1-5,5>>^ e os que sobre os telhados adoram o exército do céu, e aqueles adoradores que juram ao Senhor, e juram por Milcom;

[[v36-1-6]]

^<<v36-1-6,6>>^ e os que deixam de seguir ao Senhor, e os que não buscam ao Senhor, nem perguntam por ele.

[[v36-1-7]]

^<<v36-1-7,7>>^ Cala-te diante do Senhor Deus, porque o dia do Senhor está perto; pois o Senhor tem preparado um sacrifício, e tem santificado os seus convidados.

[[v36-1-8]]

^<<v36-1-8,8>>^ E no dia do sacrifício do Senhor castigarei os oficiais, e os filhos do rei, e todos os que se vestem de trajes estrangeiros.

[[v36-1-9]]

^<<v36-1-9,9>>^ Castigarei também naquele dia todos aqueles que saltam sobre o umbral, que enchem de violência e de dolo a casa do seu senhor.

[[v36-1-10]]

^<<v36-1-10,10>>^ E naquele dia, diz o Senhor, far-se-á ouvir uma voz de clamor desde a porta dos peixes, e um uivo desde a segunda parte, e grande estrépito desde os outeiros.

[[v36-1-11]]

^<<v36-1-11,11>>^ Uivai vós, moradores de Mactes, porque todo o povo de Canaã está arruinado; todos os que pesam a prata são destruídos.

[[v36-1-12]]

^<<v36-1-12,12>>^ E há de ser que, naquele tempo, esquadrinharei a Jerusalém com lanternas, e castigarei os homens que se embrutecem com as fezes do vinho, que dizem no seu coração: O Senhor não faz o bem nem faz o mal.

[[v36-1-13]]

^<<v36-1-13,13>>^ Por isso as riquezas deles se tornarão em despojo e as suas casas em desolação; e edificarão casas, mas não habitarão nelas; e plantarão vinhas, mas não lhes beberão o vinho.

[[v36-1-14]]

^<<v36-1-14,14>>^ O grande dia do Senhor está perto; sim, está perto, e se apressa muito; ei-la, amarga é a voz do dia do Senhor; clama ali o homem poderoso.

[[v36-1-15]]

^<<v36-1-15,15>>^ Aquele dia é dia de indignação, dia de tribulação e de angústia, dia de alvoroço e de assolação, dia de trevas e de escuridão, dia de nuvens e de densas trevas,

[[v36-1-16]]

^<<v36-1-16,16>>^ dia de trombeta e de alarido contra as cidades fortificadas e contra as torres altas.

[[v36-1-17]]

^<<v36-1-17,17>>^ E angustiarei os homens, e eles andarão como cegos, porque pecaram contra o Senhor; e o seu sangue se derramará como pó, e a sua carne como esterco.

[[v36-1-18]]

^<<v36-1-18,18>>^ Nem a sua prata nem o seu ouro os poderá livrar no dia da indignação do Senhor; mas pelo fogo do seu zelo será devorada toda a terra; porque certamente fará de todos os moradores da terra uma destruição total e apressada.

'''

xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[Próximo Capítulo &#62;]