include::./index.adoc[]

[[v36-2-0]]
=== Sofonias, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v36-2-1]]

^<<v36-2-1,1>>^ Congregai-vos, sim, congregai-vos, ó nação sem pudor;

[[v36-2-2]]

^<<v36-2-2,2>>^ antes que o decreto produza efeito, e o dia passe como a pragana; antes que venha sobre vós o furor da ira do Senhor, sim, antes que venha sobre vós o dia da ira do Senhor.

[[v36-2-3]]

^<<v36-2-3,3>>^ Buscai ao Senhor, vós todos os mansos da terra, que tendes posto por obra o seu juizo; buscai a justiça, buscai a mansidão; porventura sereis escondidos no dia da ira do Senhor.

[[v36-2-4]]

^<<v36-2-4,4>>^ Pois Gaza será desamparada, e Asquelom assolada; Asdode ao meio-dia será expelida, e Ecrom desarraigada.

[[v36-2-5]]

^<<v36-2-5,5>>^ Ai dos habitantes da borda do mar, da nação dos quereteus! A palavra do Senhor é contra vós, ó Canaã, terra dos filisteus; e eu vos destruirei, sem que fique sequer um habitante.

[[v36-2-6]]

^<<v36-2-6,6>>^ E a borda do mar será de pastagens, com cabanas para os pastores, e currais para os rebanhos.

[[v36-2-7]]

^<<v36-2-7,7>>^ E será a costa para o restante da casa de Judá, para que eles se apascentem ali; de tarde se deitarão nas casas de Asquelom; pois o Senhor seu Deus os visitará, e os fará tornar do seu cativeiro.

[[v36-2-8]]

^<<v36-2-8,8>>^ Eu ouvi o escárnio de Moabe, e os ultrajes dos filhos de Amom, com que escarneceram do meu povo, e se engrandeceram contra o seu termo.

[[v36-2-9]]

^<<v36-2-9,9>>^ Portanto diz o Senhor dos exércitos, o Deus de Israel: Tão certo como eu vivo, Moabe será como Sodoma, e os filhos de Amom como Gomorra, campo de urtigas e poços de sal, e desolação perpétua; o restante do meu povo os saqueará, e o restante da minha nação os possuíra.

[[v36-2-10]]

^<<v36-2-10,10>>^ Isso terão em recompensa da sua soberba, porque usaram de escárnios, e se engrandeceram contra o povo do Senhor dos exércitos.

[[v36-2-11]]

^<<v36-2-11,11>>^ O Senhor se mostrará terrível contra eles; pois aniquilará todos os deuses da terra, e adorá-lo-ão, cada uma desde o seu lugar, todas as ilhas das nações.

[[v36-2-12]]

^<<v36-2-12,12>>^ Também vós, ó etíopes, sereis mortos pela minha espada.

[[v36-2-13]]

^<<v36-2-13,13>>^ Ainda ele estenderá a mão contra o Norte, e destruirá a Assíria; e fará de Nínive uma desolação, terra árida como o deserto.

[[v36-2-14]]

^<<v36-2-14,14>>^ E no meio dela se deitarão manadas, todas as feras do campo; e alojar-se-ão nos capitéis dela tanto o pelicano como o ouriço; a voz das aves se ouvirá nas janelas; e haverá desolação nos limiares; pois ele tem posto a descoberto a obra de cedro.

[[v36-2-15]]

^<<v36-2-15,15>>^ Esta é a cidade alegre, que vivia em segurança, que dizia no seu coração: Eu sou, e fora de mim não há outra. Como se tem ela tornado em desolação, em covil de feras! Todo o que passar por ela assobiará, e meneará a mão

'''

xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[Próximo Capítulo &#62;]