include::./index.adoc[]

[[v32-3-0]]
=== Jonas, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v32-3-1]]

^<<v32-3-1,1>>^ Pela segunda vez veio a palavra do Senhor a Jonas, dizendo:

[[v32-3-2]]

^<<v32-3-2,2>>^ Levanta-te, e vai à grande cidade de Nínive, e lhe proclama a mensagem que eu te ordeno.

[[v32-3-3]]

^<<v32-3-3,3>>^ Levantou-se, pois, Jonas, e foi a Nínive, segundo a palavra do Senhor. Ora, Nínive era uma grande cidade, de três dias de jornada.

[[v32-3-4]]

^<<v32-3-4,4>>^ E começou Jonas a entrar pela cidade, fazendo a jornada dum dia, e clamava, dizendo: Ainda quarenta dias, e Nínive será subvertida.

[[v32-3-5]]

^<<v32-3-5,5>>^ E os homens de Nínive creram em Deus; e proclamaram um jejum, e vestiram-se de saco, desde o maior deles até o menor.

[[v32-3-6]]

^<<v32-3-6,6>>^ A notícia chegou também ao rei de Nínive; e ele se levantou do seu trono e, despindo-se do seu manto e cobrindo-se de saco, sentou-se sobre cinzas.

[[v32-3-7]]

^<<v32-3-7,7>>^ E fez uma proclamação, e a publicou em Nínive, por decreto do rei e dos seus nobres, dizendo: Não provem coisa alguma nem homens, nem animais, nem bois, nem ovelhas; não comam, nem bebam água;

[[v32-3-8]]

^<<v32-3-8,8>>^ mas sejam cobertos de saco, tanto os homens como os animais, e clamem fortemente a Deus; e convertam-se, cada um do seu mau caminho, e da violência que há nas suas mãos.

[[v32-3-9]]

^<<v32-3-9,9>>^ Quem sabe se voltará Deus, e se arrependerá, e se apartará do furor da sua ira, de sorte que não pereçamos?

[[v32-3-10]]

^<<v32-3-10,10>>^ Viu Deus o que fizeram, como se converteram do seu mau caminho, e Deus se arrependeu do mal que tinha dito lhes faria, e não o fez.

'''

xref:032-jonas/032-jonas-002.adoc#v32-2-0[&#60; Capítulo Anterior] | <<v32-3-0,Topo>> | xref:032-jonas/032-jonas-004.adoc#v32-4-0[Próximo Capítulo &#62;]