include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-10-1]]

^<<v47-10-1,1>>^ Ora eu mesmo, Paulo, vos rogo pela mansidão e benignidade de Cristo, eu que, na verdade, quando presente entre vós, sou humilde, mas quando ausente, ousado para convosco;

[[v47-10-2]]

^<<v47-10-2,2>>^ sim, eu vos rogo que, quando estiver presente, não me veja obrigado a usar, com confiança, da ousadia que espero ter para com alguns que nos julgam como se andássemos segundo a carne.

[[v47-10-3]]

^<<v47-10-3,3>>^ Porque, embora andando na carne, não militamos segundo a carne,

[[v47-10-4]]

^<<v47-10-4,4>>^ pois as armas da nossa milícia não são carnais, mas poderosas em Deus, para demolição de fortalezas;

[[v47-10-5]]

^<<v47-10-5,5>>^ derribando raciocínios e todo baluarte que se ergue contra o conhecimento de Deus, e levando cativo todo pensamento à obediência a Cristo;

[[v47-10-6]]

^<<v47-10-6,6>>^ e estando prontos para vingar toda desobediência, quando for cumprida a vossa obediência.

[[v47-10-7]]

^<<v47-10-7,7>>^ Olhais para as coisas segundo a aparência. Se alguém confia de si mesmo que é de Cristo, pense outra vez isto consigo, que, assim como ele é de Cristo, também nós o somos.

[[v47-10-8]]

^<<v47-10-8,8>>^ Pois, ainda que eu me glorie um tanto mais da nossa autoridade, a qual o Senhor nos deu para edificação, e não para vossa destruição, não me envergonharei;

[[v47-10-9]]

^<<v47-10-9,9>>^ para que eu não pareça como se quisera intimidar-vos por cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Porque eles dizem: As cartas dele são graves e fortes, mas a sua presença corporal é fraca, e a sua palavra desprezível.

[[v47-10-11]]

^<<v47-10-11,11>>^ Considere o tal isto, que, quais somos no falar por cartas, estando ausentes, tais seremos também no fazer, estando presentes,

[[v47-10-12]]

^<<v47-10-12,12>>^ pois não ousamos contar-nos, ou comparar-nos com alguns, que se louvam a si mesmos; mas estes, medindo-se consigo mesmos e comparando-se consigo mesmos, estão sem entendimento.

[[v47-10-13]]

^<<v47-10-13,13>>^ Nós, porém, não nos gloriaremos além da medida, mas conforme o padrão da medida que Deus nos designou para chegarmos mesmo até vós;

[[v47-10-14]]

^<<v47-10-14,14>>^ porque não nos estendemos além do que convém, como se não chegássemos a vós, pois já chegamos também até vós no evangelho de Cristo,

[[v47-10-15]]

^<<v47-10-15,15>>^ não nos gloriando além da medida em trabalhos alheios; antes tendo esperança de que, à proporção que cresce a vossa fé, seremos nós cada vez mais engrandecidos entre vós, conforme a nossa medida,

[[v47-10-16]]

^<<v47-10-16,16>>^ para anunciar o evangelho nos lugares que estão além de vós, e não em campo de outrem, para não nos gloriarmos no que estava já preparado.

[[v47-10-17]]

^<<v47-10-17,17>>^ Aquele, porém, que se gloria, glorie-se no Senhor.

[[v47-10-18]]

^<<v47-10-18,18>>^ Porque não é aprovado aquele que se recomenda a si mesmo, mas sim aquele a quem o Senhor recomenda.

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]