include::./index.adoc[]

[[v47-4-0]]
=== 2 Coríntios, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-4-1]]

^<<v47-4-1,1>>^ Pelo que, tendo este ministério, assim como já alcançamos misericórdia, não desfalecemos;

[[v47-4-2]]

^<<v47-4-2,2>>^ pelo contrário, rejeitamos as coisas ocultas, que são vergonhosas, não andando com astúcia, nem adulterando a palavra de Deus; mas, pela manifestação da verdade, nós nos recomendamos à consciência de todos os homens diante de Deus.

[[v47-4-3]]

^<<v47-4-3,3>>^ Mas, se ainda o nosso evangelho está encoberto, é naqueles que se perdem que está encoberto,

[[v47-4-4]]

^<<v47-4-4,4>>^ nos quais o deus deste século cegou os entendimentos dos incrédulos, para que lhes não resplandeça a luz do evangelho da glória de Cristo, o qual é a imagem de Deus.

[[v47-4-5]]

^<<v47-4-5,5>>^ Pois não nos pregamos a nós mesmos, mas a Cristo Jesus como Senhor; e a nós mesmos como vossos servos por amor de Jesus.

[[v47-4-6]]

^<<v47-4-6,6>>^ Porque Deus, que disse: Das trevas brilhará a luz, é quem brilhou em nossos corações, para iluminação do conhecimento da glória de Deus na face de Cristo.

[[v47-4-7]]

^<<v47-4-7,7>>^ Temos, porém, este tesouro em vasos de barro, para que a excelência do poder seja de Deus, e não da nossa parte.

[[v47-4-8]]

^<<v47-4-8,8>>^ Em tudo somos atribulados, mas não angustiados; perplexos, mas não desesperados;

[[v47-4-9]]

^<<v47-4-9,9>>^ perseguidos, mas não desamparados; abatidos, mas não destruídos;

[[v47-4-10]]

^<<v47-4-10,10>>^ trazendo sempre no corpo o morrer de Jesus, para que também a vida de Jesus se manifeste em nossos corpos;

[[v47-4-11]]

^<<v47-4-11,11>>^ pois nós, que vivemos, estamos sempre entregues à morte por amor de Jesus, para que também a vida de Jesus se manifeste em nossa carne mortal.

[[v47-4-12]]

^<<v47-4-12,12>>^ De modo que em nós opera a morte, mas em vós a vida.

[[v47-4-13]]

^<<v47-4-13,13>>^ Ora, temos o mesmo espírito de fé, conforme está escrito: Cri, por isso falei; também nós cremos, por isso também falamos,

[[v47-4-14]]

^<<v47-4-14,14>>^ sabendo que aquele que ressuscitou o Senhor Jesus, nos ressuscitará a nós com Jesus, e nos apresentará convosco.

[[v47-4-15]]

^<<v47-4-15,15>>^ Pois tudo é por amor de vós, para que a graça, multiplicada por meio de muitos, faça abundar a ação de graças para glória de Deus.

[[v47-4-16]]

^<<v47-4-16,16>>^ Por isso não desfalecemos; mas ainda que o nosso homem exterior se esteja consumindo, o interior, contudo, se renova de dia em dia.

[[v47-4-17]]

^<<v47-4-17,17>>^ Porque a nossa leve e momentânea tribulação produz para nós cada vez mais abundantemente um eterno peso de glória;

[[v47-4-18]]

^<<v47-4-18,18>>^ não atentando nós nas coisas que se vêem, mas sim nas que se não vêem; porque as que se vêem são temporais, enquanto as que se não vêem são eternas.

'''

xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[Próximo Capítulo &#62;]