include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-12-1]]

^<<v47-12-1,1>>^ É necessário gloriar-me, embora não convenha; mas passarei a visões e revelações do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em Cristo que há catorze anos &#123;se no corpo não sei, se fora do corpo não sei; Deus o sabe&#125; foi arrebatado até o terceiro céu.

[[v47-12-3]]

^<<v47-12-3,3>>^ Sim, conheço o tal homem &#123;se no corpo, se fora do corpo, não sei: Deus o sabe&#125;,

[[v47-12-4]]

^<<v47-12-4,4>>^ que foi arrebatado ao paraíso, e ouviu palavras inefáveis, as quais não é lícito ao homem referir.

[[v47-12-5]]

^<<v47-12-5,5>>^ Desse tal me gloriarei, mas de mim mesmo não me gloriarei, senão nas minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ Pois, se quiser gloriar-me, não serei insensato, porque direi a verdade;

[[v47-12-7]]

^<<v47-12-7,7>>^ E, para que me não exaltasse demais pela excelência das revelações, foi-me dado um espinho na carne, a saber, um mensageiro de Satanás para me esbofetear, a fim de que eu não me exalte demais;

[[v47-12-8]]

^<<v47-12-8,8>>^ acerca do qual três vezes roguei ao Senhor que o afastasse de mim;

[[v47-12-9]]

^<<v47-12-9,9>>^ e ele me disse: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. Por isso, de boa vontade antes me gloriarei nas minhas fraquezas, a fim de que repouse sobre mim o poder de Cristo.

[[v47-12-10]]

^<<v47-12-10,10>>^ Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias por amor de Cristo. Porque quando estou fraco, então é que sou forte.

[[v47-12-11]]

^<<v47-12-11,11>>^ Tornei-me insensato; vós a isso me obrigastes; porque eu devia ser louvado por vós, visto que em nada fui inferior aos demais excelentes apóstolos, ainda que nada sou.

[[v47-12-12]]

^<<v47-12-12,12>>^ Os sinais do meu apostolado foram, de fato, operados entre vós com toda a paciência, por sinais, prodígios e milagres.

[[v47-12-13]]

^<<v47-12-13,13>>^ Pois, em que fostes feitos inferiores às outras igrejas, a não ser nisto, que eu mesmo vos não fui pesado? Perdoai-me esta injustiça.

[[v47-12-14]]

^<<v47-12-14,14>>^ Eis que pela terceira vez estou pronto a ir ter convosco, e não vos serei pesado, porque não busco o que é vosso, mas sim a vós; pois não são os filhos que devem entesourar para os pais, mas os pais para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Eu de muito boa vontade gastarei, e me deixarei gastar pelas vossas almas. Se mais abundantemente vos amo, serei menos amado?

[[v47-12-16]]

^<<v47-12-16,16>>^ Mas seja assim; eu não vos fui pesado; mas, sendo astuto, vos tomei com dolo.

[[v47-12-17]]

^<<v47-12-17,17>>^ Porventura vos explorei por algum daqueles que vos enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Exortei a Tito, e enviei com ele o irmão. Porventura Tito vos explorou? Não andamos porventura no mesmo espírito? Não seguimos as mesmas pegadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Há muito, de certo, pensais que nos estamos desculpando convosco. Perante Deus, falamos em Cristo, e tudo isto, amados, é para vossa edificação.

[[v47-12-20]]

^<<v47-12-20,20>>^ Porque temo que, quando chegar, não vos ache quais eu vos quero, e que eu seja achado por vós qual não me quereis; que de algum modo haja contendas, invejas, iras, porfias, detrações, mexericos, orgulhos, tumultos;

[[v47-12-21]]

^<<v47-12-21,21>>^ e que, quando for outra vez, o meu Deus me humilhe perante vós, e chore eu sobre muitos daqueles que dantes pecaram, e ainda não se arrependeram da impureza, prostituição e lascívia que cometeram.

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]