include::./index.adoc[]

[[v47-7-0]]
=== 2 Coríntios, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-7-1]]

^<<v47-7-1,1>>^ Ora, amados, visto que temos tais promessas, purifiquemo-nos de toda a imundícia da carne e do espírito, aperfeiçoando a santidade no temor de Deus.

[[v47-7-2]]

^<<v47-7-2,2>>^ Recebei-nos em vossos corações; a ninguém fizemos injustiça, a ninguém corrompemos, a ninguém exploramos.

[[v47-7-3]]

^<<v47-7-3,3>>^ Não o digo para vos condenar, pois já tenho declarado que estais em nossos corações para juntos morrermos e juntos vivermos.

[[v47-7-4]]

^<<v47-7-4,4>>^ Grande é a minha franqueza para convosco, e muito me glorio a respeito de vós; estou cheio de consolação, transbordo de gozo em todas as nossas tribulações.

[[v47-7-5]]

^<<v47-7-5,5>>^ Porque, mesmo quando chegamos à Macedônia, a nossa carne não teve repouso algum; antes em tudo fomos atribulados: por fora combates, temores por dentro.

[[v47-7-6]]

^<<v47-7-6,6>>^ Mas Deus, que consola os abatidos, nos consolou com a vinda de Tito;

[[v47-7-7]]

^<<v47-7-7,7>>^ e não somente com a sua vinda, mas também pela consolação com que foi consolado a vosso respeito, enquanto nos referia as vossas saudações, o vosso pranto, o vosso zelo por mim, de modo que ainda mais me regozijei.

[[v47-7-8]]

^<<v47-7-8,8>>^ Porquanto, ainda que vos contristei com a minha carta, não me arrependo; embora antes me tivesse arrependido &#123;pois vejo que aquela carta vos contristou, ainda que por pouco tempo&#125;,

[[v47-7-9]]

^<<v47-7-9,9>>^ agora folgo, não porque fostes contristados, mas porque o fostes para o arrependimento; pois segundo Deus fostes contristados, para que por nós não sofrêsseis dano em coisa alguma.

[[v47-7-10]]

^<<v47-7-10,10>>^ Porque a tristeza segundo Deus opera arrependimento para a salvação, o qual não traz pesar; mas a tristeza do mundo opera a morte.

[[v47-7-11]]

^<<v47-7-11,11>>^ Pois vêde quanto cuidado não produziu em vós isto mesmo, o serdes contristados segundo Deus! sim, que defesa própria, que indignação, que temor, que saudades, que zelo, que vingança! Em tudo provastes estar inocentes nesse negócio.

[[v47-7-12]]

^<<v47-7-12,12>>^ Portanto, ainda que vos escrevi, não foi por causa do que fez o mal, nem por causa do que o sofreu, mas para que fosse manifesto, diante de Deus, o vosso grande cuidado por nós.

[[v47-7-13]]

^<<v47-7-13,13>>^ Por isso temos sido consolados. E em nossa consolação nos alegramos ainda muito mais pela alegria de Tito, porque o seu espírito tem sido recreado por vós todos.

[[v47-7-14]]

^<<v47-7-14,14>>^ Porque, se em alguma coisa me gloriei de vós para com ele, não fiquei envergonhado; mas como vos dissemos tudo com verdade, assim também o louvor que de vós fizemos a Tito se achou verdadeiro.

[[v47-7-15]]

^<<v47-7-15,15>>^ E o seu entranhável afeto para convosco é mais abundante, lembrando-se da obediência de vós todos, e de como o recebestes com temor e tremor.

[[v47-7-16]]

^<<v47-7-16,16>>^ Regozijo-me porque em tudo tenho confiança em vós.

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]