include::./index.adoc[]

[[v47-2-0]]
=== 2 Coríntios, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-2-1]]

^<<v47-2-1,1>>^ Mas deliberei isto comigo mesmo: não ir mais ter convosco em tristeza.

[[v47-2-2]]

^<<v47-2-2,2>>^ Porque, se eu vos entristeço, quem é, pois, o que me alegra, senão aquele que por mim é entristecido?

[[v47-2-3]]

^<<v47-2-3,3>>^ E escrevi isto mesmo, para que, chegando, eu não tenha tristeza da parte dos que deveriam alegrar-me; confiando em vós todos, que a minha alegria é a de todos vós.

[[v47-2-4]]

^<<v47-2-4,4>>^ Porque em muita tribulação e angústia de coração vos escrevi, com muitas lágrimas, não para que vos entristecêsseis, mas para que conhecêsseis o amor que abundantemente vos tenho.

[[v47-2-5]]

^<<v47-2-5,5>>^ Ora, se alguém tem causado tristeza, não me tem contristado a mim, mas em parte &#123;para não ser por demais severo&#125; a todos vós.

[[v47-2-6]]

^<<v47-2-6,6>>^ Basta a esse tal esta repreensão feita pela maioria.

[[v47-2-7]]

^<<v47-2-7,7>>^ De maneira que, pelo contrário, deveis antes perdoar-lhe e consolá-lo, para que ele não seja devorado por excessiva tristeza.

[[v47-2-8]]

^<<v47-2-8,8>>^ Pelo que vos rogo que confirmeis para com ele o vosso amor.

[[v47-2-9]]

^<<v47-2-9,9>>^ É pois para isso também que escrevi, para, por esta prova, saber se sois obedientes em tudo.

[[v47-2-10]]

^<<v47-2-10,10>>^ E a quem perdoardes alguma coisa, também eu; pois, o que eu também perdoei, se é que alguma coisa tenho perdoado, por causa de vós o fiz na presença de Cristo, para que Satanás não leve vantagem sobre nós;

[[v47-2-11]]

^<<v47-2-11,11>>^ porque não ignoramos as suas maquinações.

[[v47-2-12]]

^<<v47-2-12,12>>^ Ora, quando cheguei a Trôade para pregar o evangelho de Cristo, e quando se me abriu uma porta no Senhor,

[[v47-2-13]]

^<<v47-2-13,13>>^ não tive descanso no meu espírito, porque não achei ali irmão Tito; mas, despedindo-me deles, parti para a Macedônia.

[[v47-2-14]]

^<<v47-2-14,14>>^ Graças, porém, a Deus que em Cristo sempre nos conduz em triunfo, e por meio de nós difunde em todo lugar o cheiro do seu conhecimento;

[[v47-2-15]]

^<<v47-2-15,15>>^ porque para Deus somos um aroma de Cristo, nos que se salvam e nos que se perdem.

[[v47-2-16]]

^<<v47-2-16,16>>^ Para uns, na verdade, cheiro de morte para morte; mas para outros cheiro de vida para vida. E para estas coisas quem é idôneo?

[[v47-2-17]]

^<<v47-2-17,17>>^ Porque nós não somos falsificadores da palavra de Deus, como tantos outros; mas é com sinceridade, é da parte de Deus e na presença do próprio Deus que, em Cristo, falamos.

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]