include::./index.adoc[]

[[v47-5-0]]
=== 2 Coríntios, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-5-1]]

^<<v47-5-1,1>>^ Porque sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos de Deus um edifício, uma casa não feita por mãos, eterna, nos céus.

[[v47-5-2]]

^<<v47-5-2,2>>^ Pois neste tabernáculo nós gememos, desejando muito ser revestidos da nossa habitação que é do céu,

[[v47-5-3]]

^<<v47-5-3,3>>^ se é que, estando vestidos, não formos achados nus.

[[v47-5-4]]

^<<v47-5-4,4>>^ Porque, na verdade, nós, os que estamos neste tabernáculo, gememos oprimidos, porque não queremos ser despidos, mas sim revestidos, para que o mortal seja absorvido pela vida.

[[v47-5-5]]

^<<v47-5-5,5>>^ Ora, quem para isto mesmo nos preparou foi Deus, o qual nos deu como penhor o Espírito.

[[v47-5-6]]

^<<v47-5-6,6>>^ Temos, portanto, sempre bom ânimo, sabendo que, enquanto estamos presentes no corpo, estamos ausentes do Senhor

[[v47-5-7]]

^<<v47-5-7,7>>^ &#123;porque andamos por fé, e não por vista&#125;;

[[v47-5-8]]

^<<v47-5-8,8>>^ temos bom ânimo, mas desejamos antes estar ausentes deste corpo, para estarmos presentes com o Senhor.

[[v47-5-9]]

^<<v47-5-9,9>>^ Pelo que também nos esforçamos para ser-lhe agradáveis, quer presentes, quer ausentes.

[[v47-5-10]]

^<<v47-5-10,10>>^ Porque é necessário que todos nós sejamos manifestos diante do tribunal de Cristo, para que cada um receba o que fez por meio do corpo, segundo o que praticou, o bem ou o mal.

[[v47-5-11]]

^<<v47-5-11,11>>^ Portanto, conhecendo o temor do Senhor, procuramos persuadir os homens; mas, a Deus já somos manifestos, e espero que também nas vossas consciências sejamos manifestos.

[[v47-5-12]]

^<<v47-5-12,12>>^ Não nos recomendamos outra vez a vós, mas damo-vos ocasião de vos gloriardes por nossa causa, a fim de que tenhais resposta para os que se gloriam na aparência, e não no coração.

[[v47-5-13]]

^<<v47-5-13,13>>^ Porque, se enlouquecemos, é para Deus; se conservamos o juízo, é para vós.

[[v47-5-14]]

^<<v47-5-14,14>>^ Pois o amor de Cristo nos constrange, porque julgamos assim: se um morreu por todos, logo todos morreram;

[[v47-5-15]]

^<<v47-5-15,15>>^ e ele morreu por todos, para que os que vivem não vivam mais para si, mas para aquele que por eles morreu e ressuscitou.

[[v47-5-16]]

^<<v47-5-16,16>>^ Por isso daqui por diante a ninguém conhecemos segundo a carne; e, ainda que tenhamos conhecido Cristo segundo a carne, contudo agora já não o conhecemos desse modo.

[[v47-5-17]]

^<<v47-5-17,17>>^ Pelo que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo.

[[v47-5-18]]

^<<v47-5-18,18>>^ Mas todas as coisas provêm de Deus, que nos reconciliou consigo mesmo por Cristo, e nos confiou o ministério da reconciliação;

[[v47-5-19]]

^<<v47-5-19,19>>^ pois que Deus estava em Cristo reconciliando consigo o mundo, não imputando aos homens as suas transgressões; e nos encarregou da palavra da reconciliação.

[[v47-5-20]]

^<<v47-5-20,20>>^ De sorte que somos embaixadores por Cristo, como se Deus por nós vos exortasse. Rogamo-vos, pois, por Cristo que vos reconcilieis com Deus.

[[v47-5-21]]

^<<v47-5-21,21>>^ Àquele que não conheceu pecado, Deus o fez pecado por nós; para que nele fôssemos feitos justiça de Deus.

'''

xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[Próximo Capítulo &#62;]