include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-6-1]]

^<<v47-6-1,1>>^ E nós, cooperando com ele, também vos exortamos a que não recebais a graça de Deus em vão;

[[v47-6-2]]

^<<v47-6-2,2>>^ &#123;porque diz: No tempo aceitável te escutei e no dia da salvação te socorri; eis aqui agora o tempo aceitável, eis aqui agora o dia da salvação&#125;;

[[v47-6-3]]

^<<v47-6-3,3>>^ não dando nós nenhum motivo de escândalo em coisa alguma, para que o nosso ministério não seja censurado.

[[v47-6-4]]

^<<v47-6-4,4>>^ Antes em tudo recomendando-nos como ministros de Deus; em muita perseverança, em aflições, em necessidades, em angústias,

[[v47-6-5]]

^<<v47-6-5,5>>^ em açoites, em prisões, em tumultos, em trabalhos, em vigílias, em jejuns,

[[v47-6-6]]

^<<v47-6-6,6>>^ na pureza, na ciência, na longanimidade, na bondade, no Espírito Santo, no amor não fingido,

[[v47-6-7]]

^<<v47-6-7,7>>^ na palavra da verdade, no poder de Deus, pelas armas da justiça à direita e à esquerda,

[[v47-6-8]]

^<<v47-6-8,8>>^ por honra e por desonra, por má fama e por boa fama; como enganadores, porém verdadeiros;

[[v47-6-9]]

^<<v47-6-9,9>>^ como desconhecidos, porém bem conhecidos; como quem morre, e eis que vivemos; como castigados, porém não mortos;

[[v47-6-10]]

^<<v47-6-10,10>>^ como entristecidos, mas sempre nos alegrando; como pobres, mas enriquecendo a muitos; como nada tendo, mas possuindo tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Ó coríntios, a nossa boca está aberta para vós, o nosso coração está dilatado!

[[v47-6-12]]

^<<v47-6-12,12>>^ Não estais estreitados em nós; mas estais estreitados nos vossos próprios afetos.

[[v47-6-13]]

^<<v47-6-13,13>>^ Ora, em recompensa disto &#123;falo como a filhos&#125;, dilatai-vos também vós.

[[v47-6-14]]

^<<v47-6-14,14>>^ Não vos prendais a um jugo desigual com os incrédulos; pois que sociedade tem a justiça com a injustiça? ou que comunhão tem a luz com as trevas?

[[v47-6-15]]

^<<v47-6-15,15>>^ Que harmonia há entre Cristo e Belial? ou que parte tem o crente com o incrédulo?

[[v47-6-16]]

^<<v47-6-16,16>>^ E que consenso tem o santuário de Deus com ídolos? Pois nós somos santuário de Deus vivo, como Deus disse: Neles habitarei, e entre eles andarei; e eu serei o seu Deus e eles serão o meu povo.

[[v47-6-17]]

^<<v47-6-17,17>>^ Pelo que, saí vós do meio deles e separai-vos, diz o Senhor; e não toqueis coisa imunda, e eu vos receberei;

[[v47-6-18]]

^<<v47-6-18,18>>^ e eu serei para vós Pai, e vós sereis para mim filhos e filhas, diz o Senhor Todo-Poderoso.

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]