include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-9-1]]

^<<v47-9-1,1>>^ Pois quanto à ministração que se faz a favor dos santos, não necessito escrever-vos;

[[v47-9-2]]

^<<v47-9-2,2>>^ porque bem sei a vossa prontidão, pela qual me glorio de vós perante os macedônios, dizendo que a Acaia está pronta desde o ano passado; e o vosso zelo tem estimulado muitos.

[[v47-9-3]]

^<<v47-9-3,3>>^ Mas enviei estes irmãos, a fim de que neste particular não se torne vão o nosso louvor a vosso respeito; para que, como eu dizia, estejais preparados,

[[v47-9-4]]

^<<v47-9-4,4>>^ a fim de, se acaso alguns macedônios forem comigo, e vos acharem desaparecidos, não sermos nós envergonhados &#123;para não dizermos vós&#125; nesta confiança.

[[v47-9-5]]

^<<v47-9-5,5>>^ Portanto, julguei necessário exortar estes irmãos que fossem adiante ter convosco, e preparassem de antemão a vossa beneficência, já há tempos prometida, para que a mesma esteja pronta como beneficência e não como por extorsão.

[[v47-9-6]]

^<<v47-9-6,6>>^ Mas digo isto: Aquele que semeia pouco, pouco também ceifará; e aquele que semeia em abundância, em abundância também ceifará,

[[v47-9-7]]

^<<v47-9-7,7>>^ Cada um contribua segundo propôs no seu coração; não com tristeza, nem por constrangimento; porque Deus ama ao que dá com alegria.

[[v47-9-8]]

^<<v47-9-8,8>>^ E Deus é poderoso para fazer abundar em vós toda a graça, a fim de que, tendo sempre, em tudo, toda a suficiência, abundeis em toda boa obra;

[[v47-9-9]]

^<<v47-9-9,9>>^ conforme está escrito: Espalhou, deu aos pobres; a sua justiça permanece para sempre.

[[v47-9-10]]

^<<v47-9-10,10>>^ Ora, aquele que dá a semente ao que semeia, e pão para comer, também dará e multiplicará a vossa sementeira, e aumentará os frutos da vossa justiça.

[[v47-9-11]]

^<<v47-9-11,11>>^ enquanto em tudo enriqueceis para toda a liberalidade, a qual por nós reverte em ações de graças a Deus.

[[v47-9-12]]

^<<v47-9-12,12>>^ Porque a ministração deste serviço não só supre as necessidades dos santos, mas também transborda em muitas ações de graças a Deus;

[[v47-9-13]]

^<<v47-9-13,13>>^ visto como, na prova desta ministração, eles glorificam a Deus pela submissão que confessais quanto ao evangelho de Cristo, e pela liberalidade da vossa contribuição para eles, e para todos;

[[v47-9-14]]

^<<v47-9-14,14>>^ enquanto eles, pela oração por vós, demonstram o ardente afeto que vos têm, por causa da superabundante graça de Deus que há em vós.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças a Deus pelo seu dom inefável.

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]