include::./index.adoc[]

[[v47-1-0]]
=== 2 Coríntios, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-1-1]]

^<<v47-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo, à igreja de Deus que está em Corinto, com todos os santos que estão em toda a Acaia:

[[v47-1-2]]

^<<v47-1-2,2>>^ Graça a vós, e paz da parte de Deus nosso Pai, e do Senhor Jesus Cristo.

[[v47-1-3]]

^<<v47-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e Deus de toda a consolação,

[[v47-1-4]]

^<<v47-1-4,4>>^ que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, pela consolação com que nós mesmos somos consolados por Deus.

[[v47-1-5]]

^<<v47-1-5,5>>^ Porque, como as aflições de Cristo transbordam para conosco, assim também por meio de Cristo transborda a nossa consolação.

[[v47-1-6]]

^<<v47-1-6,6>>^ Mas, se somos atribulados, é para vossa consolação e salvação; ou, se somos consolados, para vossa consolação é a qual se opera suportando com paciência as mesmas aflições que nós também padecemos;

[[v47-1-7]]

^<<v47-1-7,7>>^ e a nossa esperança acerca de vós é firme, sabendo que, como sois participantes das aflições, assim o sereis também da consolação.

[[v47-1-8]]

^<<v47-1-8,8>>^ Porque não queremos, irmãos, que ignoreis a tribulação que nos sobreveio na Ásia, pois que fomos sobremaneira oprimidos acima das nossas forças, de modo tal que até da vida desesperamos;

[[v47-1-9]]

^<<v47-1-9,9>>^ portanto já em nós mesmos tínhamos a sentença de morte, para que não confiássemos em nós, mas em Deus, que ressuscita os mortos;

[[v47-1-10]]

^<<v47-1-10,10>>^ o qual nos livrou de tão horrível morte, e livrará; em quem esperamos que também ainda nos livrará,

[[v47-1-11]]

^<<v47-1-11,11>>^ ajudando-nos também vós com orações por nós, para que, pela mercê que por muitas pessoas nos foi feita, por muitas também sejam dadas graças a nosso respeito.

[[v47-1-12]]

^<<v47-1-12,12>>^ Porque a nossa glória é esta: o testemunho da nossa consciência, de que em santidade e sinceridade de Deus, não em sabedoria carnal, mas na graça de Deus, temos vivido no mundo, e mormente em relação a vós.

[[v47-1-13]]

^<<v47-1-13,13>>^ Pois outra coisa não vos escrevemos, senão as que ledes, ou mesmo reconheceis; e espero que também até o fim as reconhecereis;

[[v47-1-14]]

^<<v47-1-14,14>>^ como também já em parte nos reconhecestes, que somos a vossa glória, assim vós sereis a nossa no dia do Senhor Jesus.

[[v47-1-15]]

^<<v47-1-15,15>>^ E nesta confiança quis primeiro ir ter convosco, para que recebêsseis um segundo benefício;

[[v47-1-16]]

^<<v47-1-16,16>>^ e por vós passar à Macedônia, e da Macedônia voltar a vós, e ser por vosso intermédio encaminhado à Judéia.

[[v47-1-17]]

^<<v47-1-17,17>>^ Ora, deliberando isto, usei porventura de leviandade? ou o que delibero, faço-o segundo a carne, para que haja comigo o sim, sim e o não?

[[v47-1-18]]

^<<v47-1-18,18>>^ Antes, como Deus é fiel, a nossa palavra a vós não é sim e não,

[[v47-1-19]]

^<<v47-1-19,19>>^ porque o Filho de Deus, Cristo Jesus, que entre vós foi pregado por nós, isto é, por mim, Silvano e Timóteo, não foi sim e não; mas nele houve sim.

[[v47-1-20]]

^<<v47-1-20,20>>^ Pois, tantas quantas forem as promessas de Deus, nele está o sim; portanto é por ele o amém, para glória de Deus por nosso intermédio.

[[v47-1-21]]

^<<v47-1-21,21>>^ Mas aquele que nos confirma convosco em Cristo, e nos ungiu, é Deus,

[[v47-1-22]]

^<<v47-1-22,22>>^ o qual também nos selou e nos deu como penhor o Espírito em nossos corações.

[[v47-1-23]]

^<<v47-1-23,23>>^ Ora, tomo a Deus por testemunha sobre a minha alma de que é para vos poupar que não fui mais a Corinto;

[[v47-1-24]]

^<<v47-1-24,24>>^ não que tenhamos domínio sobre a vossa fé, mas somos cooperadores de vosso gozo; pois pela fé estais firmados.

'''

xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[&#60; Capítulo Anterior] | <<v47-1-0,Topo>> | xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[Próximo Capítulo &#62;]