include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v47-11-1]]

^<<v47-11-1,1>>^ Oxalá me suportásseis um pouco na minha insensatez! Sim, suportai-me ainda.

[[v47-11-2]]

^<<v47-11-2,2>>^ Porque estou zeloso de vós com zelo de Deus; pois vos desposei com um só Esposo, Cristo, para vos apresentar a ele como virgem pura.

[[v47-11-3]]

^<<v47-11-3,3>>^ Mas temo que, assim como a serpente enganou a Eva com a sua astúcia, assim também sejam de alguma sorte corrompidos os vossos entendimentos e se apartem da simplicidade e da pureza que há em Cristo.

[[v47-11-4]]

^<<v47-11-4,4>>^ Porque, se alguém vem e vos prega outro Jesus que nós não temos pregado, ou se recebeis outro espírito que não recebestes, ou outro evangelho que não abraçastes, de boa mente o suportais!

[[v47-11-5]]

^<<v47-11-5,5>>^ Ora, julgo que em nada tenho sido inferior aos mais excelentes apóstolos.

[[v47-11-6]]

^<<v47-11-6,6>>^ Pois ainda que seja rude na palavra, não o sou contudo na ciência; antes, por todos os modos, isto vos temos demonstrado em tudo.

[[v47-11-7]]

^<<v47-11-7,7>>^ Pequei porventura, humilhando-me a mim mesmo, para que vós fôsseis exaltados, porque de graça vos anunciei o evangelho de Deus?

[[v47-11-8]]

^<<v47-11-8,8>>^ Outras igrejas despojei, recebendo delas salário, para vos servir;

[[v47-11-9]]

^<<v47-11-9,9>>^ e quando estava presente convosco, e tinha necessidade, a ninguém fui pesado; porque os irmãos, quando vieram da Macedônia, supriram a minha necessidade; e em tudo me guardei, e ainda me guardarei, de vos ser pesado.

[[v47-11-10]]

^<<v47-11-10,10>>^ Como a verdade de Cristo está em mim, não me será tirada glória nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por que? Será porque não vos amo? Deus o sabe.

[[v47-11-12]]

^<<v47-11-12,12>>^ Ora, o que faço e ainda farei, é para cortar ocasião aos que buscam ocasião; a fim de que, naquilo em que se gloriam, sejam achados assim como nós.

[[v47-11-13]]

^<<v47-11-13,13>>^ Pois os tais são falsos apóstolos, obreiros fraudulentos, disfarçando-se em apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E não é de admirar, porquanto o próprio Satanás se disfarça em anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Não é muito, pois, que também os seus ministros se disfarcem em ministros da justiça; o fim dos quais será conforme as suas obras.

[[v47-11-16]]

^<<v47-11-16,16>>^ Outra vez digo: ninguém me julgue insensato; mas se assim pensais, recebei-me como insensato mesmo, para que eu também me glorie um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ O que digo, não o digo segundo o Senhor, mas como por insensatez, nesta confiança de gloriar-me.

[[v47-11-18]]

^<<v47-11-18,18>>^ Desde que muitos se gloriam segundo a carne, eu também me gloriarei.

[[v47-11-19]]

^<<v47-11-19,19>>^ Porque, sendo vós sensatos, de boa mente tolerais os insensatos.

[[v47-11-20]]

^<<v47-11-20,20>>^ Pois se alguém vos escraviza, se alguém vos devora, se alguém vos defrauda, se alguém se ensoberbece, se alguém vos fere no rosto, vós o suportais.

[[v47-11-21]]

^<<v47-11-21,21>>^ Falo com vergonha, como se nós fôssemos fracos; mas naquilo em que alguém se faz ousado, com insensatez falo, também eu sou ousado.

[[v47-11-22]]

^<<v47-11-22,22>>^ São hebreus? também eu; são israelitas? também eu; são descendência de Abraão? também eu;

[[v47-11-23]]

^<<v47-11-23,23>>^ são ministros de Cristo? falo como fora de mim, eu ainda mais; em trabalhos muito mais; em prisões muito mais; em açoites sem medida; em perigo de morte muitas vezes;

[[v47-11-24]]

^<<v47-11-24,24>>^ dos judeus cinco vezes recebi quarenta açoites menos um.

[[v47-11-25]]

^<<v47-11-25,25>>^ Três vezes fui açoitado com varas, uma vez fui apedrejado, três vezes sofri naufrágio, uma noite e um dia passei no abismo;

[[v47-11-26]]

^<<v47-11-26,26>>^ em viagens muitas vezes, em perigos de rios, em perigos de salteadores, em perigos dos da minha raça, em perigos dos gentios, em perigos na cidade, em perigos no deserto, em perigos no mar, em perigos entre falsos irmãos;

[[v47-11-27]]

^<<v47-11-27,27>>^ em trabalhos e fadiga, em vigílias muitas vezes, em fome e sede, em jejuns muitas vezes, em frio e nudez.

[[v47-11-28]]

^<<v47-11-28,28>>^ Além dessas coisas exteriores, há o que diariamente pesa sobre mim, o cuidado de todas as igrejas.

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem enfraquece, que eu também não enfraqueça? Quem se escandaliza, que eu me não abrase?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se é preciso gloriar-me, gloriar-me-ei no que diz respeito à minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, que é eternamente bendito, sabe que não minto.

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o que governava sob o rei Aretas guardava a cidade dos damascenos, para me prender;

[[v47-11-33]]

^<<v47-11-33,33>>^ mas por uma janela desceram-me num cesto, muralha abaixo; e assim escapei das suas mãos.

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]