include::./index.adoc[]

[[v10-17-0]]
=== 2 Samuel, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-17-1]]

^<<v10-17-1,1>>^ Disse mais Aitofel a Absalão: Deixa-me escolher doze mil homens, e me levantarei, e perseguirei a Davi esta noite.

[[v10-17-2]]

^<<v10-17-2,2>>^ Irei sobre ele, enquanto está cansado, e fraco de mãos, e o espantarei: então fugirá todo o povo que está com ele. Ferirei tão-somente o rei;

[[v10-17-3]]

^<<v10-17-3,3>>^ e farei tornar a ti todo o povo, como uma noiva à casa do seu esposo; pois é a vida dum só homem que tu buscas; assim todo o povo estará em paz.

[[v10-17-4]]

^<<v10-17-4,4>>^ E este conselho agradou a Absalão, e a todos os anciãos de Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ Disse, porém, Absalão: Chamai agora a Husai, o arquita, e ouçamos também o que ele diz.

[[v10-17-6]]

^<<v10-17-6,6>>^ Quando Husai chegou a Absalão, este lhe disse: Desta maneira falou Aitofel; faremos conforme a sua palavra? Se não, fala tu.

[[v10-17-7]]

^<<v10-17-7,7>>^ Então disse Husai a Absalão: O conselho que Aitofel deu esta vez não é bom.

[[v10-17-8]]

^<<v10-17-8,8>>^ Acrescentou Husai: Tu bem sabes que teu pai e os seus homens são valentes, e que estão com o espírito amargurado, como a ursa no campo, roubada dos seus cachorros; além disso teu pai é homem de guerra, e não passará a noite com o povo.

[[v10-17-9]]

^<<v10-17-9,9>>^ Eis que agora está ele escondido nalguma cova, ou em qualquer outro lugar; e será que, caindo alguns no primeiro ataque, todo o que o ouvir dirá: Houve morticínio entre o povo que segue a Absalão.

[[v10-17-10]]

^<<v10-17-10,10>>^ Então até o homem valente, cujo coração é como coração de leão, sem dúvida desmaiará; porque todo o Israel sabe que teu pai é valoroso, e que são valentes os que estão com ele.

[[v10-17-11]]

^<<v10-17-11,11>>^ Eu, porém, aconselho que com toda a pressa se ajunte a ti todo o Israel, desde Dã até Berseba, em multidão como a areia do mar; e que tu em pessoa vás à peleja.

[[v10-17-12]]

^<<v10-17-12,12>>^ Então iremos a ele, em qualquer lugar em que se achar, e desceremos sobre ele, como o orvalho cai sobre a terra; e não ficará dele e de todos os homens que estão com ele nem sequer um só.

[[v10-17-13]]

^<<v10-17-13,13>>^ se ele, porém, se retirar para alguma cidade, todo o Israel trará cordas àquela cidade, e arrastá-la-emos até o ribeiro, até que não se ache ali nem uma só pedrinha

[[v10-17-14]]

^<<v10-17-14,14>>^ Então Absalão e todos os homens e Israel disseram: Melhor é o conselho de Husai, o arquita, do que o conselho de Aitofel: Porque assim o Senhor o ordenara, para aniquilar o bom conselho de Aitofel, a fim de trazer o mal sobre Absalão.

[[v10-17-15]]

^<<v10-17-15,15>>^ Também disse Husai a Zadoque e a Abiatar, sacerdotes: Assim e assim aconselhou Aitofel a Absalão e aos anciãos de Israel; porém eu aconselhei assim e assim.

[[v10-17-16]]

^<<v10-17-16,16>>^ Agora, pois, mandai apressadamente avisar a Davi, dizendo: Não passes esta noite nos vaus do deserto; mas passa sem falta à outra banda, para que não seja devorado o rei, e todo o povo que com ele está.

[[v10-17-17]]

^<<v10-17-17,17>>^ Ora, Jônatas e Aimaaz estavam esperando junto a En-Rogel; e foi uma criada, e lhes avisou, para que eles fossem e o dissessem ao rei Davi; pois não deviam ser vistos entrando na cidade.

[[v10-17-18]]

^<<v10-17-18,18>>^ Viu-os todavia um moço, e avisou a Absalão. Ambos, porém, partiram apressadamente, e entraram em casa de um homem, em Baurim, o qual tinha no pátio de sua casa um poço, para o qual eles desceram.

[[v10-17-19]]

^<<v10-17-19,19>>^ E a mulher, tomando a tampa, colocou-a sobre a boca do poço, e espalhou grão triturado sobre ela; assim nada se soube.

[[v10-17-20]]

^<<v10-17-20,20>>^ Chegando, pois, os servos de Absalão àquela casa, perguntaram à mulher: Onde estão Aimaaz e Jônatas? Respondeu-lhes a mulher: Já passaram a corrente das águas. E, havendo-os procurado sem os encontrarem, voltaram para Jerusalém.

[[v10-17-21]]

^<<v10-17-21,21>>^ Depois que eles partiram, Aimaaz e Jônatas, saindo do poço, foram e avisaram a Davi; e disseram-lhe: Levantai-vos, e passai depressa as águas, porque assim e assim aconselhou contra vós Aitofel.

[[v10-17-22]]

^<<v10-17-22,22>>^ Então se levantou Davi e todo o povo que com ele estava, e passaram o Jordão; e ao raiar da manhã não faltava nem um só que não o tivesse passado.

[[v10-17-23]]

^<<v10-17-23,23>>^ Vendo, pois, Aitofel que não se havia seguido o seu conselho, albardou o jumento e, partindo, foi para casa, para a sua cidade; e, tendo posto em ordem a sua casa, se enforcou e morreu; e foi sepultado na sepultura de seu pai.

[[v10-17-24]]

^<<v10-17-24,24>>^ Então Davi veio a Maanaim; e Absalão passou o Jordão, ele e todos os homens de Israel com ele.

[[v10-17-25]]

^<<v10-17-25,25>>^ E Absalão colocou Amasa em lugar de Joabe sobre o exército. Ora, Amasa era filho de um homem que se chamava Itra, o jizreelita, o qual entrara a Abigail, filha de Naás e irmã de Zeruia, mãe de Joabe.

[[v10-17-26]]

^<<v10-17-26,26>>^ Israel e Absalão se acamparam na terra de Gileade.

[[v10-17-27]]

^<<v10-17-27,27>>^ Tendo Davi chegado a Maanaim, Sobi, filho de Naás, de Rabá dos filhos de Amom, e Maquir, filho de Amiel, de Lo-Debar, e Barzilai, o gileadita, de Rogelim,

[[v10-17-28]]

^<<v10-17-28,28>>^ tomaram camas, bacias e vasilhas de barro; trigo, cevada, farinha, grão tostado, favas, lentilhas e torradas;

[[v10-17-29]]

^<<v10-17-29,29>>^ mel, manteiga, ovelhas e queijos de vaca, e os trouxeram a Davi e ao povo que com ele estava, para comerem; pois diziam: O povo está faminto, cansado e sedento, no deserto.

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]