include::./index.adoc[]

[[v10-22-0]]
=== 2 Samuel, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-22-1]]

^<<v10-22-1,1>>^ Davi dirigiu ao Senhor as palavras deste cântico, no dia em que o Senhor o livrou das mãos de todos os seus inimigos e das mãos de Saul, dizendo:

[[v10-22-2]]

^<<v10-22-2,2>>^ O Senhor é o meu rochedo, a minha fortaleza e o meu libertador.

[[v10-22-3]]

^<<v10-22-3,3>>^ É meu Deus, a minha rocha, nele confiarei; é o meu escudo, e a força da minha salvação, o meu alto retiro, e o meu refúgio. O meu Salvador; da violência tu me livras.

[[v10-22-4]]

^<<v10-22-4,4>>^ Ao Senhor invocarei, pois é digno de louvor; assim serei salvo dos meus inimigos.

[[v10-22-5]]

^<<v10-22-5,5>>^ As ondas da morte me cercaram, as torrentes de Belial me atemorizaram.

[[v10-22-6]]

^<<v10-22-6,6>>^ Cordas do Seol me cingiram, laços de morte me envolveram.

[[v10-22-7]]

^<<v10-22-7,7>>^ Na minha angústia invoquei ao Senhor; sim, a meu Deus clamei; do seu templo ouviu ele a minha voz, e o meu clamor chegou aos seus ouvidos.

[[v10-22-8]]

^<<v10-22-8,8>>^ Então se abalou e tremeu a terra, os fundamentos dos céus se moveram; abalaram-se porque ele se irou.

[[v10-22-9]]

^<<v10-22-9,9>>^ Das suas narinas subiu fumaça, e da sua boca um fogo devorador, que pôs carvões em chamas.

[[v10-22-10]]

^<<v10-22-10,10>>^ Ele abaixou os céus, e desceu; e havia escuridão debaixo dos seus pés.

[[v10-22-11]]

^<<v10-22-11,11>>^ Montou num querubim, e voou; apareceu sobre as asas do vento.

[[v10-22-12]]

^<<v10-22-12,12>>^ E por tendas pôs trevas ao redor de si, ajuntamento de águas, espessas nuvens do céu.

[[v10-22-13]]

^<<v10-22-13,13>>^ Pelo resplendor da sua presença acenderam-se brasas de fogo.

[[v10-22-14]]

^<<v10-22-14,14>>^ Do céu trovejou o Senhor, o Altíssimo fez soar a sua voz.

[[v10-22-15]]

^<<v10-22-15,15>>^ Disparou flechas, e os dissipou; raios, e os desbaratou.

[[v10-22-16]]

^<<v10-22-16,16>>^ Então apareceram as profundezas do mar; os fundamentos do mundo se descobriram, pela repreensão do Senhor, pelo assopro do vento das suas narinas.

[[v10-22-17]]

^<<v10-22-17,17>>^ Estendeu do alto a sua mão e tomou-me; tirou-me das muitas águas.

[[v10-22-18]]

^<<v10-22-18,18>>^ Livrou-me do meu possante inimigo, e daqueles que me odiavam; porque eram fortes demais para mim.

[[v10-22-19]]

^<<v10-22-19,19>>^ Encontraram-me no dia da minha calamidade, porém o Senhor se fez o meu esteio.

[[v10-22-20]]

^<<v10-22-20,20>>^ Conduziu-me para um lugar espaçoso; livrou-me, porque tinha prazer em mim.

[[v10-22-21]]

^<<v10-22-21,21>>^ Recompensou-me o Senhor conforme a minha justiça; conforme a pureza e minhas mãos me retribuiu.

[[v10-22-22]]

^<<v10-22-22,22>>^ Porque guardei os caminhos do Senhor, e não me apartei impiamente do meu Deus.

[[v10-22-23]]

^<<v10-22-23,23>>^ Pois todos os seus preceitos estavam diante de mim, e dos seus estatutos não me desviei.

[[v10-22-24]]

^<<v10-22-24,24>>^ Fui perfeito para com ele, e guardei-me da minha iniqüidade.

[[v10-22-25]]

^<<v10-22-25,25>>^ Por isso me retribuiu o Senhor conforme a minha justiça, conforme a minha pureza diante dos meus olhos.

[[v10-22-26]]

^<<v10-22-26,26>>^ Para com o benigno te mostras benigno; para com o perfeito te mostras perfeito,

[[v10-22-27]]

^<<v10-22-27,27>>^ para com o puro te mostras puro, mas para com o perverso te mostras avesso.

[[v10-22-28]]

^<<v10-22-28,28>>^ Livrarás o povo que se humilha, mas teus olhos são contra os altivos, e tu os abaterás.

[[v10-22-29]]

^<<v10-22-29,29>>^ Porque tu, Senhor, és a minha candeia; e o Senhor alumiará as minhas trevas.

[[v10-22-30]]

^<<v10-22-30,30>>^ Pois contigo passarei pelo meio dum esquadrão; com o meu Deus transporei um muro.

[[v10-22-31]]

^<<v10-22-31,31>>^ Quanto a Deus, o seu caminho é perfeito, e a palavra do Senhor é fiel; é ele o escudo de todos os que nele se refugiam.

[[v10-22-32]]

^<<v10-22-32,32>>^ Pois quem é Deus, senão o Senhor? e quem é rocha, senão o nosso Deus?

[[v10-22-33]]

^<<v10-22-33,33>>^ Deus é a minha grande fortaleza; e ele torna perfeito o meu caminho.

[[v10-22-34]]

^<<v10-22-34,34>>^ Faz ele os meus pés como os das gazelas, e me põe sobre as minhas alturas.

[[v10-22-35]]

^<<v10-22-35,35>>^ Ele instrui as minhas mãos para a peleja, de modo que os meus braços podem entesar um arco de bronze.

[[v10-22-36]]

^<<v10-22-36,36>>^ Também me deste o escudo da tua salvação, e tua brandura me engrandece.

[[v10-22-37]]

^<<v10-22-37,37>>^ Alargaste os meus passos debaixo de mim, e não vacilaram os meus artelhos.

[[v10-22-38]]

^<<v10-22-38,38>>^ Persegui os meus inimigos e os destruí, e nunca voltei atrás sem que os consumisse.

[[v10-22-39]]

^<<v10-22-39,39>>^ Eu os consumi, e os atravessei, de modo que nunca mais se levantaram; sim, cairam debaixo dos meus pés.

[[v10-22-40]]

^<<v10-22-40,40>>^ Pois tu me cingiste de força para a peleja; prostraste debaixo de mim os que se levantaram contra mim.

[[v10-22-41]]

^<<v10-22-41,41>>^ Fizeste que me voltassem as costas os meus inimigos, aqueles que me odiavam, para que eu os destruísse.

[[v10-22-42]]

^<<v10-22-42,42>>^ Olharam ao redor, mas não houve quem os salvasse; clamaram ao Senhor, mas ele não lhes respondeu.

[[v10-22-43]]

^<<v10-22-43,43>>^ Então os moí como o pó da terra; como a lama das ruas os trilhei e dissipei.

[[v10-22-44]]

^<<v10-22-44,44>>^ Também me livraste das contendas do meu povo; guardaste-me para ser o cabeça das nações; um povo que eu não conhecia me serviu.

[[v10-22-45]]

^<<v10-22-45,45>>^ Estrangeiros, com adulação, se submeteram a mim; ao ouvirem de mim, me obedeceram.

[[v10-22-46]]

^<<v10-22-46,46>>^ Os estrangeiros desfaleceram e, tremendo, sairam os seus esconderijos.

[[v10-22-47]]

^<<v10-22-47,47>>^ O Senhor vive; bendita seja a minha rocha, e exaltado seja Deus, a rocha da minha salvação,

[[v10-22-48]]

^<<v10-22-48,48>>^ o Deus que me deu vingança, e sujeitou povos debaixo de mim,

[[v10-22-49]]

^<<v10-22-49,49>>^ e me tirou dentre os meus inimigos; porque tu me exaltaste sobre os meus adversários; tu me livraste do homem violento.

[[v10-22-50]]

^<<v10-22-50,50>>^ Por isso, ó Senhor, louvar-te-ei entre as nações, e entoarei louvores ao teu nome.

[[v10-22-51]]

^<<v10-22-51,51>>^ Ele dá grande livramento a seu rei, e usa de benignidade para com o seu ungido, para com Davi e a sua descendência para sempre.

'''

xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[&#60; Capítulo Anterior] | <<v10-22-0,Topo>> | xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[Próximo Capítulo &#62;]