include::./index.adoc[]

[[v10-11-0]]
=== 2 Samuel, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-11-1]]

^<<v10-11-1,1>>^ Tendo decorrido um ano, no tempo em que os reis saem à guerra, Davi enviou Joabe, e com ele os seus servos e todo o Israel; e eles destruíram os amonitas, e sitiaram a Rabá. Porém Davi ficou em Jerusalém.

[[v10-11-2]]

^<<v10-11-2,2>>^ Ora, aconteceu que, numa tarde, Davi se levantou do seu leito e se pôs a passear no terraço da casa real; e do terraço viu uma mulher que se estava lavando; e era esta mulher mui formosa à vista.

[[v10-11-3]]

^<<v10-11-3,3>>^ Tendo Davi enviado a indagar a respeito daquela mulher, disseram-lhe: Porventura não é Bate-Seba, filha de Eliã, mulher de Urias, o heteu?

[[v10-11-4]]

^<<v10-11-4,4>>^ Então Davi mandou mensageiros para trazê-la; e ela veio a ele, e ele se deitou com ela &#123;pois já estava purificada da sua imundícia&#125;; depois ela voltou para sua casa.

[[v10-11-5]]

^<<v10-11-5,5>>^ A mulher concebeu; e mandou dizer a Davi: Estou grávida.

[[v10-11-6]]

^<<v10-11-6,6>>^ Então Davi mandou dizer a Joabe: Envia-me Urias, o heteu. E Joabe o enviou a Davi.

[[v10-11-7]]

^<<v10-11-7,7>>^ Vindo, pois, Urias a Davi, este lhe perguntou como passava Joabe, e como estava o povo, e como ia a guerra.

[[v10-11-8]]

^<<v10-11-8,8>>^ Depois disse Davi a Urias: Desce a tua casa, e lava os teus pés. E, saindo Urias da casa real, logo foi mandado após ele um presente do rei.

[[v10-11-9]]

^<<v10-11-9,9>>^ Mas Urias dormiu à porta da casa real, com todos os servos do seu senhor, e não desceu a sua casa.

[[v10-11-10]]

^<<v10-11-10,10>>^ E o contaram a Davi, dizendo: Urias não desceu a sua casa. Então perguntou Davi a Urias: Não vens tu duma jornada? por que não desceste a tua casa?

[[v10-11-11]]

^<<v10-11-11,11>>^ Respondeu Urias a Davi: A arca, e Israel, e Judá estão em tendas; e Joabe, meu senhor, e os servos de meu senhor estão acampados ao relento; e entrarei eu na minha casa, para comer e beber, e para me deitar com minha mulher? Como vives tu, e como vive a tua alma, não farei tal coisa.

[[v10-11-12]]

^<<v10-11-12,12>>^ Então disse Davi a Urias: Fica ainda hoje aqui, e amanhã te despedirei. Urias, pois, ficou em Jerusalém aquele dia e o seguinte.

[[v10-11-13]]

^<<v10-11-13,13>>^ E Davi o convidou a comer e a beber na sua presença, e o embebedou; e à tarde saiu Urias a deitar-se na sua cama com os servos de seu senhor, porém não desceu a sua casa.

[[v10-11-14]]

^<<v10-11-14,14>>^ Pela manhã Davi escreveu uma carta a Joabe, e mandou-lha por mão de Urias.

[[v10-11-15]]

^<<v10-11-15,15>>^ Escreveu na carta: Ponde Urias na frente onde for mais renhida a peleja, e retirai-vos dele, para que seja ferido e morra.

[[v10-11-16]]

^<<v10-11-16,16>>^ Enquanto Joabe sitiava a cidade, pôs Urias no lugar onde sabia que havia homens valentes.

[[v10-11-17]]

^<<v10-11-17,17>>^ Quando os homens da cidade saíram e pelejaram contra Joabe, caíram alguns do povo, isto é, dos servos de Davi; morreu também Urias, o heteu.

[[v10-11-18]]

^<<v10-11-18,18>>^ Então Joabe mandou dizer a Davi tudo o que sucedera na peleja;

[[v10-11-19]]

^<<v10-11-19,19>>^ e deu ordem ao mensageiro, dizendo: Quando tiveres acabado de contar ao rei tudo o que sucedeu nesta peleja,

[[v10-11-20]]

^<<v10-11-20,20>>^ caso o rei se encolerize, e te diga: Por que vos chegastes tão perto da cidade a pelejar. Não sabíeis vós que haviam de atirar do muro?

[[v10-11-21]]

^<<v10-11-21,21>>^ Quem matou a Abimeleque, filho de Jerubesete? Não foi uma mulher que lançou sobre ele, do alto do muro, a pedra superior dum moinho, de modo que morreu em Tebez? Por que chegastes tão perto do muro? Então dirás: Também morreu teu servo Urias, o heteu.

[[v10-11-22]]

^<<v10-11-22,22>>^ Partiu, pois, o mensageiro e, tendo chegado, referiu a Davi tudo o que Joabe lhe ordenara.

[[v10-11-23]]

^<<v10-11-23,23>>^ Disse o mensageiro a Davi: Os homens ganharam uma vantagem sobre nós, e sairam contra nos ao campo; porém nos os repelimos até a entrada da porta.

[[v10-11-24]]

^<<v10-11-24,24>>^ Então os flecheiros atiraram contra os teus servos desde o alto do muro, e morreram alguns servos do rei; e também morreu o teu servo Urias, o heteu.

[[v10-11-25]]

^<<v10-11-25,25>>^ Disse Davi ao mensageiro: Assim dirás a Joabe: Não te preocupes com isso, pois a espada tanto devora este como aquele; aperta a tua peleja contra a cidade, e a derrota. Encoraja-o tu assim.

[[v10-11-26]]

^<<v10-11-26,26>>^ Ouvindo, pois, a mulher de Urias que seu marido era morto, o chorou.

[[v10-11-27]]

^<<v10-11-27,27>>^ E, passado o tempo do luto, mandou Davi recolhê-la a sua casa: e ela lhe foi por mulher, e lhe deu um filho. Mas isto que Davi fez desagradou ao Senhor.

'''

xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[&#60; Capítulo Anterior] | <<v10-11-0,Topo>> | xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[Próximo Capítulo &#62;]