include::./index.adoc[]

[[v10-8-0]]
=== 2 Samuel, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-8-1]]

^<<v10-8-1,1>>^ Sucedeu depois disso que Davi derrotou os filisteus, e os sujeitou; e Davi tomou a Metegue-Ama das mãos dos filisteus.

[[v10-8-2]]

^<<v10-8-2,2>>^ Também derrotou os moabitas, e os mediu com cordel, fazendo-os deitar por terra; e mediu dois cordéis para os matar, e um cordel inteiro para os deixar com vida. Ficaram assim os moabitas por servos de Davi, pagando-lhe tributos.

[[v10-8-3]]

^<<v10-8-3,3>>^ Davi também derrotou a Hadadézer, filho de Reobe, rei de Zobá, quando este ia estabelecer o seu domínio sobre o rio Eufrates.

[[v10-8-4]]

^<<v10-8-4,4>>^ E tomou-lhe Davi mil e setecentos cavaleiros e vinte mil homens de infantaria; e Davi jarretou a todos os cavalos dos carros, reservando apenas cavalos para cem carros.

[[v10-8-5]]

^<<v10-8-5,5>>^ Os sírios de Damasco vieram socorrer a Hadadézer, rei de Zobá, mas Davi matou deles vinte e dois mil homens.

[[v10-8-6]]

^<<v10-8-6,6>>^ Então Davi pôs guarnições em Síria de Damasco, e os sírios ficaram por servos de Davi, pagando-lhe tributos. E o Senhor lhe dava a vitória por onde quer que ia.

[[v10-8-7]]

^<<v10-8-7,7>>^ E Davi tomou os escudos de ouro que os servos de Hadadézer usavam, e os trouxe para Jerusalém.

[[v10-8-8]]

^<<v10-8-8,8>>^ De Betá e de Berotai, cidades de Hadadézer, o rei Davi tomou grande quantidade de bronze.

[[v10-8-9]]

^<<v10-8-9,9>>^ Quando Toí, rei de Hamate, ouviu que Davi ferira todo o exército de Hadadézer,

[[v10-8-10]]

^<<v10-8-10,10>>^ mandou-lhe seu filho Jorão para saudá-lo, e para felicitá-lo por haver pelejado contra Hadadézer e o haver derrotado; pois Hadadézer de contínuo fazia guerra a Toí. E Jorão trouxe consigo vasos de prata de ouro e de bronze,

[[v10-8-11]]

^<<v10-8-11,11>>^ os quais o rei Davi consagrou ao Senhor, como já havia consagrado a prata e o ouro de todas as nações que sujeitara.

[[v10-8-12]]

^<<v10-8-12,12>>^ da Síria, de Moabe, dos amonitas, dos filisteus, de Amaleque e dos despojos de Hadadézer, filho de Reobe, rei de Zobá.

[[v10-8-13]]

^<<v10-8-13,13>>^ Assim Davi ganhou nome para si. E quando voltou, matou no Vale do Sal a dezoito mil edomitas.

[[v10-8-14]]

^<<v10-8-14,14>>^ E pôs guarnições em Edom; pô-las em todo o Edom, e todos os edomitas tornaram-se servos de Davi. E o Senhor lhe dava a vitória por onde quer que ia.

[[v10-8-15]]

^<<v10-8-15,15>>^ Reinou, pois, Davi sobre todo o Israel, e administrava a justiça e a eqüidade a todo o seu povo.

[[v10-8-16]]

^<<v10-8-16,16>>^ Joabe, filho de Zeruia, estava sobre o exército; Jeosafá, filho de Ailude, era cronista;

[[v10-8-17]]

^<<v10-8-17,17>>^ Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes; Seraías era escrivão;

[[v10-8-18]]

^<<v10-8-18,18>>^ Benaías, filho de Jeoiada, tinha o cargo dos quereteus e peleteus; e os filhos de Davi eram ministros de estado.

'''

xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[&#60; Capítulo Anterior] | <<v10-8-0,Topo>> | xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[Próximo Capítulo &#62;]