include::./index.adoc[]

[[v10-4-0]]
=== 2 Samuel, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-4-1]]

^<<v10-4-1,1>>^ Quando Is-Bosete, filho de Saul, soube que Abner morrera em Hebrom, esvaíram-se-lhe as forças, e todo o Israel ficou perturbado.

[[v10-4-2]]

^<<v10-4-2,2>>^ Tinha Is-Bosete, filho de Saul, dois homens chefes de guerrilheiros; um deles se chamava Baaná, e o outro Recabe, filhos de Rimom, o beerotita, dos filhos de Benjamim &#123;porque também Beerote era contado de Benjamim,

[[v10-4-3]]

^<<v10-4-3,3>>^ tendo os beerotitas fugido para Jitaim, onde têm peregrinado até o dia de hoje&#125;.

[[v10-4-4]]

^<<v10-4-4,4>>^ Ora, Jônatas, filho de Saul, tinha um filho aleijado dos pés. Este era da idade de cinco anos quando chegaram de Jizreel as novas a respeito de Saul e Jônatas; pelo que sua ama o tomou, e fugiu; e sucedeu que, apressando-se ela a fugir, ele caiu, e ficou coxo. O seu nome era Mefibosete.

[[v10-4-5]]

^<<v10-4-5,5>>^ Foram os filhos de Rimom, o beerotita, Recabe e Baanã, no maior calor de dia, e entraram em casa de Is-Bosete, estando ele deitado a dormir a sesta.

[[v10-4-6]]

^<<v10-4-6,6>>^ Entraram ali até o meio da casa, como que vindo apanhar trigo, e o feriram no ventre; e Recabe e Baaná, seu irmão, escaparam.

[[v10-4-7]]

^<<v10-4-7,7>>^ Porque entraram na sua casa, estando ele deitado na cama, no seu quarto de dormir, e o feriram e mataram, e cortando-lhe a cabeça, tomaram-na e andaram a noite toda pelo caminho da Arabá.

[[v10-4-8]]

^<<v10-4-8,8>>^ Assim trouxeram a cabeça de Is-Bosete a Davi em Hebrom, e disseram ao rei: Eis aqui a cabeça de Is-Bosete, filho de Saul, teu inimigo, que procurava a tua morte; assim o Senhor vingou hoje ao rei meu Senhor, de Saul e da sua descendência.

[[v10-4-9]]

^<<v10-4-9,9>>^ Mas Davi, respondendo a Recabe e a Baaná, seu irmão, filhos de Rimom, e beerotita, disse-lhes: Vive o Senhor, que remiu a minha alma de toda a angústia!

[[v10-4-10]]

^<<v10-4-10,10>>^ Se àquele que me trouxe novas, dizendo: Eis que Saul é morto, cuidando que trazia boas novas, eu logo lancei mão dele, e o matei em Ziclague, sendo essa a recompensa que lhe dei pelas novas,

[[v10-4-11]]

^<<v10-4-11,11>>^ quanto mais quando homens cruéis mataram um homem justo em sua casa, sobre a sua cama, não requererei eu e seu sangue de vossas mãos, e não vos exterminarei da terra?

[[v10-4-12]]

^<<v10-4-12,12>>^ E Davi deu ordem aos seus mancebos; e eles os mataram e, cortando-lhes as mãos e os pés, os penduraram junto ao tanque em Hebrom. Tomaram, porém, a cabeça de Is-Bosete, e a sepultaram na sepultura de Abner, em Hebrom.

'''

xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[&#60; Capítulo Anterior] | <<v10-4-0,Topo>> | xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[Próximo Capítulo &#62;]