include::./index.adoc[]

[[v10-21-0]]
=== 2 Samuel, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-21-1]]

^<<v10-21-1,1>>^ Nos dias de Davi houve uma fome de três anos consecutivos; pelo que Davi consultou ao Senhor; e o Senhor lhe disse: E por causa de Saul e da sua casa sanguinária, porque matou os gibeonitas.

[[v10-21-2]]

^<<v10-21-2,2>>^ Então o rei chamou os gibeonitas e falou com eles &#123;ora, os gibeonitas não eram dos filhos de Israel, mas do restante dos amorreus; e os filhos de Israel tinham feito pacto com eles; porém Saul, no seu zelo pelos filhos de Israel e de Judá, procurou feri-los&#125;;

[[v10-21-3]]

^<<v10-21-3,3>>^ perguntou, pois, Davi aos gibeonitas: Que quereis que eu vos faça. e como hei de fazer expiação, para que abençoeis a herança do Senhor?

[[v10-21-4]]

^<<v10-21-4,4>>^ Então os gibeonitas lhe disseram: Não é por prata nem ouro que temos questão com Saul e com a sua casa; nem tampouco cabe a nós matar pessoa alguma em Israel. Disse-lhes Davi: Que quereis que vos faça?

[[v10-21-5]]

^<<v10-21-5,5>>^ Responderam ao rei: Quanto ao homem que nos consumia, e procurava destruir-nos, de modo que não pudéssemos subsistir em termo algum de Israel,

[[v10-21-6]]

^<<v10-21-6,6>>^ de seus filhos se nos dêem sete homens, para que os enforquemos ao Senhor em Gibeá de Saul, o eleito do Senhor. E o rei disse: Eu os darei.

[[v10-21-7]]

^<<v10-21-7,7>>^ O rei, porém, poupou a Mefibosete, filho de Jônatas, filho de Saul, por causa do juramento do Senhor que entre eles houvera, isto é, entre Davi e Jônatas, filho de Saul.

[[v10-21-8]]

^<<v10-21-8,8>>^ Mas o rei tomou os dois filhos de Rizpa, filha de Aías, que ela tivera de Saul, a saber, a Armoni e a Mefibosete, como também os cinco filhos de Merabe, filha de Saul, que ela tivera de Adriel, filho de Barzilai, meolatita,

[[v10-21-9]]

^<<v10-21-9,9>>^ e os entregou na mão dos gibeonitas, os quais os enforcaram no monte, perante o Senhor; e os sete caíram todos juntos. Foi nos primeiros dias da sega que foram mortos, no princípio a sega da cevada.

[[v10-21-10]]

^<<v10-21-10,10>>^ Então Rizpa, filha de Aías, tomando um pano de cilício, estendeu-o para si sobre uma pedra e, desde o princípio da sega até que a água caiu do céu sobre os corpos, não deixou que se aproximassem deles as aves do céu de dia, nem os animais do campo de noite:

[[v10-21-11]]

^<<v10-21-11,11>>^ Quando foi anunciado a Davi o que fizera Rizpa, filha de Aías, concubina de Saul,

[[v10-21-12]]

^<<v10-21-12,12>>^ ele foi e tomou os ossos de Saul e os de Jônatas seu filho, aos homens de Jabes-Gileade, que os haviam furtado da praça de Bete-Seã, onde os filisteus os tinham pendurado quando mataram a Saul em Gilboa;

[[v10-21-13]]

^<<v10-21-13,13>>^ e trouxe dali os ossos de Saul e os de Jônatas seu filho; e ajuntaram a eles também os ossos dos enforcados.

[[v10-21-14]]

^<<v10-21-14,14>>^ Enterraram os ossos de Saul e de Jônatas seu filho, na terra de Benjamim, em Zela, na sepultura de Quis, seu pai; e fizeram tudo o que o rei ordenara. Depois disto Deus se aplacou para com a terra.

[[v10-21-15]]

^<<v10-21-15,15>>^ De novo tiveram os filisteus uma guerra contra Israel. E desceu Davi, e com ele os seus servos; e tanto pelejara contra os filisteus, que Davi se cansou.

[[v10-21-16]]

^<<v10-21-16,16>>^ E Isbi-Benobe, que era dos filhos do gigante, cuja lança tinha o peso de trezentos, siclos de bronze, e que cingia uma espada nova, intentou matar Davi.

[[v10-21-17]]

^<<v10-21-17,17>>^ Porém, Abisai, filho de Zeruia, o socorreu; e, ferindo ao filisteu, o matou. Então os homens de Davi lhe juraram, dizendo: Nunca mais sairás conosco à batalha, para que não apagues a lâmpada de Israel.

[[v10-21-18]]

^<<v10-21-18,18>>^ Aconteceu depois disto que houve em Gobe ainda outra peleja contra os filisteus; então Sibecai, o husatita, matou Safe, que era dos filhos do gigante.

[[v10-21-19]]

^<<v10-21-19,19>>^ Houve mais outra peleja contra os filisteus em Gobe; e El-Hanã, filho de Jaaré-Oregim, o belemita, matou Golias, o giteu, de cuja lança a haste era como órgão de tecelão.

[[v10-21-20]]

^<<v10-21-20,20>>^ Houve ainda também outra peleja em Gate, onde estava um homem de alta estatura, que tinha seis dedos em cada mão, e seis em cada pé, vinte e quatro por todos; também este era descendente do gigante.

[[v10-21-21]]

^<<v10-21-21,21>>^ Tendo ele desafiado a Israel, Jônatas, filho de Simei, irmão de Davi, o matou.

[[v10-21-22]]

^<<v10-21-22,22>>^ Estes quatro nasceram ao gigante em Gate; e caíram pela mão de Davi e pela mão de seus servos.

'''

xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[&#60; Capítulo Anterior] | <<v10-21-0,Topo>> | xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[Próximo Capítulo &#62;]