include::./index.adoc[]

[[v10-2-0]]
=== 2 Samuel, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-2-1]]

^<<v10-2-1,1>>^ Sucedeu depois disto que Davi consultou ao Senhor, dizendo: Subirei a alguma das cidades de Judá? Respondeu-lhe o Senhor: Sobe. Ainda perguntou Davi: Para onde subirei? Respondeu o Senhor: Para Hebrom.

[[v10-2-2]]

^<<v10-2-2,2>>^ Subiu, pois, Davi para lá, e também as suas duas mulheres, Ainoã, a jizreelita, e Abigail, que fora mulher de Nabal, e carmelita.

[[v10-2-3]]

^<<v10-2-3,3>>^ Davi fez subir também os homens que estavam com ele, cada um com sua família; e habitaram nas cidades de Hebrom.

[[v10-2-4]]

^<<v10-2-4,4>>^ Então vieram os homens de Judá, e ali ungiram Davi rei sobre a casa de Judá. Depois informaram a Davi, dizendo: Foram os homens de Jabes-Gileade que sepultaram a Saul.

[[v10-2-5]]

^<<v10-2-5,5>>^ Pelo que Davi enviou mensageiros aos homens de Jabes-Gileade, a dizer-lhes: Benditos do Senhor sejais vós, que fizestes tal benevolência, sepultando a Saul, vosso senhor!

[[v10-2-6]]

^<<v10-2-6,6>>^ Agora, pois, o Senhor use convosco de benevolência e fidelidade; e eu também vos retribuirei esse bem que fizestes.

[[v10-2-7]]

^<<v10-2-7,7>>^ Esforcem-se, pois, agora as vossas mãos, e sede homens valorosos; porque Saul, vosso senhor, é morto, e a casa de Judá me ungiu por seu rei.

[[v10-2-8]]

^<<v10-2-8,8>>^ Ora, Abner, filho de Ner, chefe do exército de Saul, tomou a Is-Bosete, filho de Saul, e o fez passar a Maanaim,

[[v10-2-9]]

^<<v10-2-9,9>>^ e o constituiu rei sobre Gileade, sobre os asuritas, sobre Jizreel, sobre Efraim, sobre Benjamim e sobre todo o Israel.

[[v10-2-10]]

^<<v10-2-10,10>>^ Quarenta anos tinha Is-Bosete, filho de Saul, quando começou a reinar sobre Israel, e reinou dois anos, A casa de Judá, porém, seguia a Davi.

[[v10-2-11]]

^<<v10-2-11,11>>^ E foi o tempo que Davi reinou em Hebrom, sobre a casa de Judá, sete anos e seis meses.

[[v10-2-12]]

^<<v10-2-12,12>>^ Depois Abner, filho de Ner, com os servos de Is-Bosete, filho de Saul, saiu de Maanaim para Gibeão.

[[v10-2-13]]

^<<v10-2-13,13>>^ Saíram também Joabe, filho de Zeruia, e os servos de Davi, e se encontraram com eles perto do tanque de Gibeão; e pararam uns de um lado do tanque, e os outros do outro lado.

[[v10-2-14]]

^<<v10-2-14,14>>^ Então disse Abner a Joabe: Levantem-se os mancebos, e se batam diante de nós. Respondeu Joabe: Levantem-se.

[[v10-2-15]]

^<<v10-2-15,15>>^ Levantaram-se, pois, e passaram, em número de doze por Benjamim e por Is-Bosete, filho de Saul, e doze dos servos de Davi.

[[v10-2-16]]

^<<v10-2-16,16>>^ E cada um lançou mão da cabeça de seu contendor, e meteu-lhe a espada pela ilharga; assim caíram juntos; pelo que se chamou àquele lugar, que está junto a Gibeão, Helcate-Hazurim.

[[v10-2-17]]

^<<v10-2-17,17>>^ Seguiu-se naquele dia uma crua peleja; e Abner e os homens de Israel foram derrotados diante dos servos de Davi.

[[v10-2-18]]

^<<v10-2-18,18>>^ Ora, estavam ali os três filhos de Zeruia: Joabe, Abisai, e Asael; e Asael era ligeiro de pés, como as gazelas do campo.

[[v10-2-19]]

^<<v10-2-19,19>>^ Perseguiu, pois, Asael a Abner, seguindo-o sem se desviar nem para a direita nem para a esquerda.

[[v10-2-20]]

^<<v10-2-20,20>>^ Nisso Abner, olhando para trás, perguntou: És tu Asael? Respondeu ele: Sou eu.

[[v10-2-21]]

^<<v10-2-21,21>>^ Ao que lhe disse Abner: Desvia-te para a direita, ou para a esquerda, e lança mão de um dos mancebos, e toma os seus despojos. Asael, porém , não quis desviar-se de seguí-lo.

[[v10-2-22]]

^<<v10-2-22,22>>^ Então Abner tornou a dizer a Asael: Desvia-te de detrás de mim; porque hei de ferir-te e dar contigo em terra? e como levantaria eu o meu rosto diante de Joabe, teu irmão?

[[v10-2-23]]

^<<v10-2-23,23>>^ Todavia ele recusou desviar-se; pelo que Abner o feriu com o conto da lança pelo ventre, de modo que a lança lhe saiu por detrás; e ele caiu ali, e morreu naquele mesmo lugar. E sucedeu que, todos os que chegavam ao lugar onde Asael caíra morto, paravam.

[[v10-2-24]]

^<<v10-2-24,24>>^ Mas Joabe e Abisai perseguiram a Abner; e pôs-se o sol ao chegarem eles ao outeiro de Amá, que está diante de Giá, junto ao caminho do deserto de Gibeão.

[[v10-2-25]]

^<<v10-2-25,25>>^ E os filhos de Benjamim se ajuntaram atrás de Abner e, formando-se num batalhão, puseram-se no cume dum outeiro.

[[v10-2-26]]

^<<v10-2-26,26>>^ Então Abner gritou a Joabe, e disse: Devorará a espada para sempre? não sabes que por fim haverá amargura? até quando te demorarás em ordenar ao povo que deixe de perseguir a seus irmãos?

[[v10-2-27]]

^<<v10-2-27,27>>^ Respondeu Joabe: Vive Deus, que, se não tivesses falado, só amanhã cedo teria o povo cessado, cada um, de perseguir a seu irmão.

[[v10-2-28]]

^<<v10-2-28,28>>^ Então Joabe tocou a buzina, e todo o povo parou; e não perseguiram mais a Israel, e tampouco pelejaram mais.

[[v10-2-29]]

^<<v10-2-29,29>>^ E caminharam Abner e os seus homens toda aquela noite pela Arabá; e, passando o Jordão, caminharam por todo o Bitrom, e vieram a Maanaim.

[[v10-2-30]]

^<<v10-2-30,30>>^ Voltou, pois, Joabe de seguir a Abner; e quando ajuntou todo o povo, faltavam dos servos de Davi dezenove homens, e Asael.

[[v10-2-31]]

^<<v10-2-31,31>>^ Mas os servos de Davi tinham ferido dentre os de Benjamim, e dentre os homens de Abner, a trezentos e sessenta homens, de tal maneira que morreram.

[[v10-2-32]]

^<<v10-2-32,32>>^ E levantaram a Asael, e o sepultaram no sepulcro de seu pai, que estava em Belém. E Joabe e seus homens caminharam toda aquela noite, e amanheceu-lhes o dia em Hebrom.

'''

xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[&#60; Capítulo Anterior] | <<v10-2-0,Topo>> | xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[Próximo Capítulo &#62;]