include::./index.adoc[]

[[v10-14-0]]
=== 2 Samuel, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-14-1]]

^<<v10-14-1,1>>^ Percebendo Joabe, filho de Zeruia, que o coração do rei estava inclinado para Absalão,

[[v10-14-2]]

^<<v10-14-2,2>>^ mandou a Tecoa trazer de lá uma mulher sagaz, e disse-lhe: Ora, finge que estás de nojo; põe vestidos de luto, não te unjas com óleo, e faze-te como uma mulher que há muitos dias chora algum morto;

[[v10-14-3]]

^<<v10-14-3,3>>^ vai ter com o rei, e fala-lhe desta maneira. Então Joabe lhe pôs as palavras na boca.

[[v10-14-4]]

^<<v10-14-4,4>>^ A mulher tecoíta, pois, indo ter com o rei e prostrando-se com o rosto em terra, fez-lhe uma reverência e disse: Salva-me, o rei.

[[v10-14-5]]

^<<v10-14-5,5>>^ Ao que lhe perguntou o rei: Que tens? Respondeu ela: Na verdade eu sou viúva; morreu meu marido.

[[v10-14-6]]

^<<v10-14-6,6>>^ Tinha a tua serva dois filhos, os quais tiveram uma briga no campo e, não havendo quem os apartasse, um feriu ao outro, e o matou.

[[v10-14-7]]

^<<v10-14-7,7>>^ E eis que toda a parentela se levantou contra a tua serva, dizendo: Dá-nos aquele que matou a seu irmão, para que o matemos pela vida de seu irmão, a quem ele matou, de modo que exterminemos também o herdeiro. Assim apagarão a brasa que me ficou, de sorte a não deixarem a meu marido nem nome, nem remanescente sobre a terra.

[[v10-14-8]]

^<<v10-14-8,8>>^ Então disse o rei à mulher: Vai para tua casa, e eu darei ordem a teu respeito.

[[v10-14-9]]

^<<v10-14-9,9>>^ Respondeu a mulher tecoíta ao rei: A iniqüidade, ó rei meu senhor, venha sobre mim e sobre a casa de meu pai; e fique inculpável o rei e o seu trono.

[[v10-14-10]]

^<<v10-14-10,10>>^ Tornou o rei: Quem falar contra ti, traze-mo a mim, e nunca mais te tocará.

[[v10-14-11]]

^<<v10-14-11,11>>^ Disse ela: Ora, lembre-se o rei do Senhor seu Deus, para que o vingador do sangue não prossiga na destruição, e não extermine a meu filho. Então disse ele: Vive o Senhor, que não há de cair no chão nem um cabelo de teu filho.

[[v10-14-12]]

^<<v10-14-12,12>>^ Então disse a mulher: Permite que a tua serva fale uma palavra ao rei meu senhor. Respondeu ele: Fala.

[[v10-14-13]]

^<<v10-14-13,13>>^ Ao que disse a mulher: Por que, pois, pensas tu tal coisa contra o povo de Deus? Pois, falando o rei esta palavra, fica como culpado, visto que o rei não torna a trazer o seu desterrado.

[[v10-14-14]]

^<<v10-14-14,14>>^ Porque certamente morreremos, e serereos como águas derramadas na terra, que não se podem ajuntar mais; Deus, todavia, não tira a vida, mas cogita meios para que não fique banido dele o seu desterrado.

[[v10-14-15]]

^<<v10-14-15,15>>^ E se eu agora vim falar esta palavra ao rei meu senhor, e porque o povo me atemorizou; pelo que dizia a tua serva: Falarei, pois, ao rei; porventura fará o rei segundo a palavra da sua serva.

[[v10-14-16]]

^<<v10-14-16,16>>^ Porque o rei ouvirá, para livrar a sua serva da mão do homem que intenta exterminar da herança de Deus tanto a mim como a meu filho.

[[v10-14-17]]

^<<v10-14-17,17>>^ Dizia mais a tua serva: Que a palavra do rei meu senhor me dê um descanso; porque como o anjo de Deus é o rei, meu senhor, para discernir o bem e o mal; e o Senhor teu Deus seja contigo.

[[v10-14-18]]

^<<v10-14-18,18>>^ Então respondeu o rei à mulher: Peço-te que não me encubras o que eu te perguntar. Tornou a mulher: Fale agora o rei meu senhor.

[[v10-14-19]]

^<<v10-14-19,19>>^ Perguntou, pois, o rei: Não é verdade que a mão de Joabe está contigo em tudo isso? Respondeu a mulher: Vive a tua alma, ó rei meu senhor, que ninguém se poderá desviar, nem para a direita nem para a esquerda, de tudo quanto diz o rei meu senhor; porque Joabe, teu servo, é quem me deu ordem, e foi ele que pôs na boca da tua serva todas estas palavras;

[[v10-14-20]]

^<<v10-14-20,20>>^ para mudar a feição do negócio é que Joabe, teu servo, fez isso. Sábio, porém, é meu senhor, conforme a sabedoria do anjo de Deus, para entender tudo o que há na terra.

[[v10-14-21]]

^<<v10-14-21,21>>^ Então o rei disse a Joabe: Eis que faço o que pedes; vai, pois, e faze voltar o mancebo Absalão.

[[v10-14-22]]

^<<v10-14-22,22>>^ Então Joabe se prostrou com o rosto em terra e, fazendo uma reverência, abençoou o rei; e disse Joabe: Hoje conhece o teu servo que achei graça aos teus olhos, ó rei meu senhor, porque o rei fez segundo a palavra do teu servo.

[[v10-14-23]]

^<<v10-14-23,23>>^ Levantou-se, pois, Joabe, foi a Gesue e trouxe Absalão para Jerusalém.

[[v10-14-24]]

^<<v10-14-24,24>>^ E disse o rei: Torne ele para sua casa, mas não venha à minha presença. Tornou, pois, Absalão para sua casa, e não foi à presença do rei.

[[v10-14-25]]

^<<v10-14-25,25>>^ Não havia em todo o Israel homem tão admirável pela sua beleza como Absalão; desde a planta do pé até o alto da cabeça não havia nele defeito algum.

[[v10-14-26]]

^<<v10-14-26,26>>^ E, quando ele cortava o cabelo, o que costumava fazer no fim de cada ano, porquanto lhe pesava muito, o peso do cabelo era de duzentos siclos, segundo o peso real.

[[v10-14-27]]

^<<v10-14-27,27>>^ Nasceram a Absalão três filhos, e uma filha cujo nome era Tamar; e esta era mulher formosa à vista.

[[v10-14-28]]

^<<v10-14-28,28>>^ Assim ficou Absalão dois anos inteiros em Jerusalém, sem ver a face do rei.

[[v10-14-29]]

^<<v10-14-29,29>>^ Então Absalão mandou chamar Joabe, para o enviar ao rei; porém Joabe não quis vir a ele. Mandou chamá-lo segunda vez, mas ele não quis vir.

[[v10-14-30]]

^<<v10-14-30,30>>^ Pelo que disse aos seus servos: Vede ali o campo de Joabe pegado ao meu, onde ele tem cevada; ide, e ponde-lhe fogo. E os servos de Absalão puseram fogo ao campo:

[[v10-14-31]]

^<<v10-14-31,31>>^ Então Joabe se levantou, e veio ter com Absalão, em casa, e lhe perguntou: Por que os teus servos puseram fogo ao meu campo.

[[v10-14-32]]

^<<v10-14-32,32>>^ Respondeu Absalão a Joabe: Eis que enviei a ti, dizendo: Vem cá, para que te envie ao rei, a dizer-lhe: Para que vim de Gesur? Melhor me fora estar ainda lá. Agora, pois, veja eu a face do rei; e, se há em mim alguma culpa, que me mate.

[[v10-14-33]]

^<<v10-14-33,33>>^ Foi, pois, Joabe à presença do rei, e lho disse. Então o rei chamou Absalão, e ele entrou à presença do rei, e se prostrou com o rosto em terra diante do rei; e o rei beijou Absalão.

'''

xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[&#60; Capítulo Anterior] | <<v10-14-0,Topo>> | xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[Próximo Capítulo &#62;]