include::./index.adoc[]

[[v10-15-0]]
=== 2 Samuel, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-15-1]]

^<<v10-15-1,1>>^ Aconteceu depois disso que Absalão adquiriu para si um carro e cavalos, e cinqüenta homens que corressem adiante dele.

[[v10-15-2]]

^<<v10-15-2,2>>^ E levantando-se Absalão cedo, parava ao lado do caminho da porta; e quando algum homem tinha uma demanda para, vir ao rei a juízo, Absalão o chamava a si e lhe dizia: De que cidade és tu? E, dizendo ele: De tal tribo de Israel é teu servo;

[[v10-15-3]]

^<<v10-15-3,3>>^ Absalão lhe dizia: Olha, a tua causa é boa e reta, porém não há da parte do rei quem te ouça.

[[v10-15-4]]

^<<v10-15-4,4>>^ Dizia mais Absalão: Ah, quem me dera ser constituído juiz na terra! para que viesse ter comigo todo homem que tivesse demanda ou questão, e eu lhe faria justiça.

[[v10-15-5]]

^<<v10-15-5,5>>^ Sucedia também que, quando alguém se chegava a ele para lhe fazer reverência, ele estendia a mão e, pegando nele o beijava.

[[v10-15-6]]

^<<v10-15-6,6>>^ Assim fazia Absalão a todo o Israel que vinha ao rei para juízo; desse modo Absalão furtava o coração dos homens de Israel.

[[v10-15-7]]

^<<v10-15-7,7>>^ Aconteceu, ao cabo de quatro anos, que Absalão disse ao rei: Deixa-me ir pagar em Hebrom o voto que fiz ao Senhor.

[[v10-15-8]]

^<<v10-15-8,8>>^ Porque, morando eu em Gesur, na Síria, fez o teu servo um voto, dizendo: Se o Senhor, na verdade, me fizer tornar a Jerusalém, servirei ao Senhor.

[[v10-15-9]]

^<<v10-15-9,9>>^ Então lhe disse o rei: Vai em paz. Levantou-se, pois, e foi para Hebrom.

[[v10-15-10]]

^<<v10-15-10,10>>^ Absalão, porém, enviou emissários por todas as tribos de Israel, dizendo: Quando ouvirdes o som da trombeta, direis: Absalão reina em Hebrom.

[[v10-15-11]]

^<<v10-15-11,11>>^ E de Jerusalém foram com Absalão duzentos homens que tinham sido convidados; mas iam na sua simplicidade, pois nada sabiam daquele desígnio.

[[v10-15-12]]

^<<v10-15-12,12>>^ Também Absalão, enquanto oferecia os seus sacrifícios, mandou vir da cidade de Siló, Aitofel, o gilonita, conselheiro de Davi. E a conspiração tornava-se poderosa, crescendo cada vez mais o número do povo que estava com Absalão.

[[v10-15-13]]

^<<v10-15-13,13>>^ Então veio um mensageiro a Davi, dizendo: O coração de todo o Israel vai após Absalão.

[[v10-15-14]]

^<<v10-15-14,14>>^ Disse, pois, Davi a todos os seus servos que estavam com ele em Jerusalém: Levantai-vos, e fujamos, porque doutra forma não poderemos escapar diante de Absalão. Apressai-vos a sair; não seja caso que ele nos apanhe de súbito, e lance sobre nós a ruína, e fira a cidade ao fio da espada.

[[v10-15-15]]

^<<v10-15-15,15>>^ Então os servos do rei lhe disseram: Eis aqui os teus servos para tudo quanto determinar o rei, nosso senhor.

[[v10-15-16]]

^<<v10-15-16,16>>^ Assim saiu o rei, com todos os de sua casa, deixando, porém, dez concubinas para guardarem a casa.

[[v10-15-17]]

^<<v10-15-17,17>>^ Tendo, pois, saído o rei com todo o povo, pararam na última casa:

[[v10-15-18]]

^<<v10-15-18,18>>^ E todos os seus servos iam ao seu lado; mas todos os quereteus, e todos os peleteus, e todos os giteus, seiscentos homens que o seguiram de Gate, caminhavam adiante do rei.

[[v10-15-19]]

^<<v10-15-19,19>>^ Disse o rei a Itai, o giteu: Por que irias tu também conosco? Volta e fica-te com o rei, porque és estrangeiro e exilado; torna a teu lugar.

[[v10-15-20]]

^<<v10-15-20,20>>^ Ontem vieste, e te levaria eu hoje conosco a vaguear? Pois eu vou para onde puder ir; volta, e lei, e contigo teus irmãos; a misericórdia e a fidelidade sejam contigo.

[[v10-15-21]]

^<<v10-15-21,21>>^ Respondeu, porém, Itai ao rei, e disse: Vive o Senhor, e vive o rei meu senhor, que no lugar em que estiver o rei meu senhor, seja para morte, seja para vida, aí estará também o eu servo.

[[v10-15-22]]

^<<v10-15-22,22>>^ Então disse Davi a Itai: Vai, pois, e passa adiante. Assim passou Itai, o giteu, e todos os seus homens, e todos os pequeninos que havia com ele.

[[v10-15-23]]

^<<v10-15-23,23>>^ Toda a terra chorava em alta voz, enquanto todo o povo passava; e o rei atravessou o ribeiro de Cedrom, e todo o povo caminhava na direção do deserto.

[[v10-15-24]]

^<<v10-15-24,24>>^ E chegou Abiatar; e veio também Zadoque, e com ele todos os levitas que levavam a arca do pacto de Deus; e puseram ali a arca de Deus, até que todo o povo acabou de sair da cidade.

[[v10-15-25]]

^<<v10-15-25,25>>^ Então disse o rei a Zadoque: Torna a levar a arca de Deus à cidade; pois, se eu achar graça aos olhos do Senhor, ele me fará voltar para lá, e me deixará ver a arca e a sua habitação.

[[v10-15-26]]

^<<v10-15-26,26>>^ Se ele, porém, disser: Não tenho prazer em ti; eis-me aqui, faça a mim o que bem lhe parecer.

[[v10-15-27]]

^<<v10-15-27,27>>^ Disse mais o rei a Zadoque, o sacerdote: Não és tu porventura vidente? volta, pois, para a cidade em paz, e contigo também teus dois filhos, Aimaaz, teu filho, e Jônatas, filho de Abiatar.

[[v10-15-28]]

^<<v10-15-28,28>>^ Vede eu me demorarei nos vaus do deserto até que tenha notícias da vossa parte.

[[v10-15-29]]

^<<v10-15-29,29>>^ Zadoque, pois, e Abiatar tornaram a levar para Jerusalém a arca de Deus, e ficaram ali.

[[v10-15-30]]

^<<v10-15-30,30>>^ Mas Davi, subindo pela encosta do monte das Oliveiras, ia chorando; tinha a cabeça coberta, e caminhava com os pés descalços. Também todo o povo que ia com ele tinha a cabeça coberta, e subia chorando sem cessar.

[[v10-15-31]]

^<<v10-15-31,31>>^ Então disseram a Davi: Aitofel está entre os que conspiraram com Absalão. Pelo que disse Davi: Ó Senhor, torna o conselho de Aitofel em loucura!

[[v10-15-32]]

^<<v10-15-32,32>>^ Ora, aconteceu que, chegando Davi ao cume, onde se costumava adorar a Deus, Husai, o arquita, veio encontrar-se com ele, com a roupa rasgada e a cabeça coberta de terra.

[[v10-15-33]]

^<<v10-15-33,33>>^ Disse-lhe Davi: Se fores comigo, ser-me-ás pesado;

[[v10-15-34]]

^<<v10-15-34,34>>^ porém se voltares para a cidade, e disseres a Absalão: Eu serei, ó rei, teu servo; como fui dantes servo de teu pai, assim agora serei teu servo; dissipar-me-ás então a conselho de Aitofel.

[[v10-15-35]]

^<<v10-15-35,35>>^ E não estão ali contigo Zadoque e Abiatar, sacerdotes? Portanto, tudo o que ouvires da casa do rei lhes dirás.

[[v10-15-36]]

^<<v10-15-36,36>>^ Eis que estão também ali com eles seus dois filhos, Aimaaz, filho de Zadoque, e Jônatas, filho de Abiatar; por eles me avisareis de tudo o que ouvirdes.

[[v10-15-37]]

^<<v10-15-37,37>>^ Husai, pois, amigo de Davi, voltou para a cidade. E Absalão entrou em Jerusalém.

'''

xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]