include::./index.adoc[]

[[v10-7-0]]
=== 2 Samuel, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-7-1]]

^<<v10-7-1,1>>^ Ora, estando o rei Davi em sua casa e tendo-lhe dado o Senhor descanso de todos os seus inimigos em redor,

[[v10-7-2]]

^<<v10-7-2,2>>^ disse ele ao profeta Natã: Eis que eu moro numa casa de cedro, enquanto que a arca de Deus dentro de uma tenda.

[[v10-7-3]]

^<<v10-7-3,3>>^ Respondeu Natã ao rei: Vai e faze tudo quanto está no teu coração, porque o Senhor é contigo.

[[v10-7-4]]

^<<v10-7-4,4>>^ Mas naquela mesma noite a palavra do Senhor veio a Natã, dizendo:

[[v10-7-5]]

^<<v10-7-5,5>>^ Vai, e dize a meu servo Davi: Assim diz o Senhor: Edificar-me-ás tu uma casa para eu nela habitar?

[[v10-7-6]]

^<<v10-7-6,6>>^ Porque em casa nenhuma habitei, desde o dia em que fiz subir do Egito os filhos de Israel até o dia de hoje, mas tenho andado em tenda e em tabernáculo.

[[v10-7-7]]

^<<v10-7-7,7>>^ E em todo lugar em que tenho andado com todos os filhos de Israel, falei porventura, alguma palavra a qualquer das suas tribos a que mandei apascentar o meu povo de Israel, dizendo: por que não me edificais uma casa de cedro?

[[v10-7-8]]

^<<v10-7-8,8>>^ Agora, pois, assim dirás ao meu servo Davi: Assim diz o Senhor dos exércitos: Eu te tomei da malhada, de detrás das ovelhas, para que fosses príncipe sobre o meu povo, sobre Israel;

[[v10-7-9]]

^<<v10-7-9,9>>^ e fui contigo, por onde quer que foste, e destruí a todos os teus inimigos diante de ti; e te farei um grande nome, como o nome dos grandes que há na terra.

[[v10-7-10]]

^<<v10-7-10,10>>^ Também designarei lugar para o meu povo, para Israel, e o plantarei ali, para que ele habite no seu lugar, e não mais seja perturbado, e nunca mais os filhos da iniqüidade o aflijam, como dantes,

[[v10-7-11]]

^<<v10-7-11,11>>^ e como desde o dia em que ordenei que houvesse juízes sobre o meu povo Israel. A ti, porém, darei descanso de todos os teus inimigos. Também o Senhor te declara que ele te fará casa.

[[v10-7-12]]

^<<v10-7-12,12>>^ Quando teus dias forem completos, e vieres a dormir com teus pais, então farei levantar depois de ti um dentre a tua descendência, que sair das tuas entranhas, e estabelecerei o seu reino.

[[v10-7-13]]

^<<v10-7-13,13>>^ Este edificará uma casa ao meu nome, e eu estabelecerei para sempre o trono do seu reino.

[[v10-7-14]]

^<<v10-7-14,14>>^ Eu lhe serei pai, e ele me será filho. E, se vier a transgredir, castigá-lo-ei com vara de homens, e com açoites de filhos de homens;

[[v10-7-15]]

^<<v10-7-15,15>>^ mas não retirarei dele a minha benignidade como a retirei de Saul, a quem tirei de diante de ti.

[[v10-7-16]]

^<<v10-7-16,16>>^ A tua casa, porém, e o teu reino serão firmados para sempre diante de ti; teu trono será estabelecido para sempre.

[[v10-7-17]]

^<<v10-7-17,17>>^ Conforme todas estas palavras, e conforme toda esta visão, assim falou Natã a Davi.

[[v10-7-18]]

^<<v10-7-18,18>>^ Então entrou o rei Davi, e sentou-se perante o Senhor, e disse: Quem sou eu, Senhor Jeová, e que é a minha casa, para me teres trazido até aqui?

[[v10-7-19]]

^<<v10-7-19,19>>^ E isso ainda foi pouco aos teus olhos, Senhor Jeová, senão que também falaste da casa do teu servo para tempos distantes; e me tens mostrado gerações futuras, ó Senhor Jeová?

[[v10-7-20]]

^<<v10-7-20,20>>^ Que mais te poderá dizer Davi. pois tu conheces bem o teu servo, ó Senhor Jeová.

[[v10-7-21]]

^<<v10-7-21,21>>^ Por causa da tua palavra, e segundo o teu coração, fizeste toda esta grandeza, revelando-a ao teu servo.

[[v10-7-22]]

^<<v10-7-22,22>>^ Portanto és grandioso, ó Senhor Jeová, porque ninguém há semelhante a ti, e não há Deus senão tu só, segundo tudo o que temos ouvido com os nossos ouvidos.

[[v10-7-23]]

^<<v10-7-23,23>>^ Que outra nação na terra é semelhante a teu povo Israel, a quem tu, ó Deus, foste resgatar para te ser povo, para te fazeres um nome, e para fazeres a seu favor estas grandes e terríveis coisas para a tua terra, diante do teu povo, que tu resgataste para ti do Egito, desterrando nações e seus deuses?

[[v10-7-24]]

^<<v10-7-24,24>>^ Assim estabeleceste o teu povo Israel por teu povo para sempre, e tu, Senhor, te fizeste o seu Deus.

[[v10-7-25]]

^<<v10-7-25,25>>^ Agora, pois, o Senhor Jeová, confirma para sempre a palavra que falaste acerca do teu servo e acerca da sua casa, e faze como tens falado,

[[v10-7-26]]

^<<v10-7-26,26>>^ para que seja engrandecido o teu nome para sempre, e se diga: O Senhor dos exércitos é Deus sobre Israel; e a casa do teu servo será estabelecida diante de ti.

[[v10-7-27]]

^<<v10-7-27,27>>^ Pois tu, Senhor dos exércitos, Deus de Israel, fizeste uma revelação ao teu servo, dizendo: Edificar-te-ei uma casa. Por isso o teu servo se animou a fazer-te esta oração.

[[v10-7-28]]

^<<v10-7-28,28>>^ Agora, pois, Senhor Jeová, tu és Deus, e as tuas palavras são verdade, e tens prometido a teu servo este bem.

[[v10-7-29]]

^<<v10-7-29,29>>^ Sê, pois, agora servido de abençoar a casa do teu servo, para que subsista para sempre diante de ti; pois tu, ó Senhor Jeová, o disseste; e com a tua bênção a casa do teu servo será, abençoada para sempre.

'''

xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]