include::./index.adoc[]

[[v10-10-0]]
=== 2 Samuel, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-10-1]]

^<<v10-10-1,1>>^ Depois disto morreu o rei dos amonitas, e seu filho Hanum reinou em seu lugar.

[[v10-10-2]]

^<<v10-10-2,2>>^ Então disse Davi: usarei de benevolência para com Hanum, filho de Naás, como seu pai usou de benevolência para comigo. Davi, pois, enviou os seus servos para o consolar acerca de seu pai; e foram os servos de Davi à terra dos amonitas.

[[v10-10-3]]

^<<v10-10-3,3>>^ Então disseram os príncipes dos amonitas a seu senhor, Hanum: Pensas, porventura, que foi para honrar teu pai que Davi te enviou consoladores? Não te enviou antes os seus servos para reconhecerem esta cidade e para a espiarem, a fim de transtorná-la?

[[v10-10-4]]

^<<v10-10-4,4>>^ Pelo que Hanum tomou os servos de Davi, rapou-lhes metade da barba, cortou-lhes metade dos vestidos, até as nádegas, e os despediu.

[[v10-10-5]]

^<<v10-10-5,5>>^ Quando isso foi dito a Davi, enviou ele mensageiros a encontrá-los, porque aqueles homens estavam sobremaneira envergonhados; e mandou dizer-lhes: Deixai-vos estar em Jericó, até que vos torne a crescer a barba, e então voltai.

[[v10-10-6]]

^<<v10-10-6,6>>^ Vendo, pois, os amonitas que se haviam feito abomináveis para com Davi, enviaram e alugaram dos sírios de Bete-Reobe e dos sírios de Bete-Reobe e dos sírios de Sobá vinte mil homens de infantaria, e do rei de Maacá mil homens, e dos homens de Tobe doze mil.

[[v10-10-7]]

^<<v10-10-7,7>>^ O que ouvindo Davi, enviou contra eles a Joabe com todo o exército dos valentes.

[[v10-10-8]]

^<<v10-10-8,8>>^ E saíram os amonitas, e ordenaram a batalha a entrada da porta; mas os sírios de Zobá e de Reobe, e os homens de Tobe e de Maacá estavam à parte no campo.

[[v10-10-9]]

^<<v10-10-9,9>>^ Vendo, pois, Joabe que a batalha estava preparada contra ele pela frente e pela retaguarda, escolheu alguns homens dentre a flor do exército de Israel, e formou-os em linha contra os sírios;

[[v10-10-10]]

^<<v10-10-10,10>>^ e entregou o resto do povo a seu irmão Abisai, para que o formasse em linha contra os amonitas.

[[v10-10-11]]

^<<v10-10-11,11>>^ E disse-lhe: Se os sírios forem mais fortes do que eu, tu me virás em socorro; e se os amonitas forem mais fortes do que tu, eu irei em teu socorro.

[[v10-10-12]]

^<<v10-10-12,12>>^ Tem bom ânimo, e sejamos corajosos pelo nosso povo, e pelas cidades de nosso Deus; e faça o Senhor o que bem lhe parecer.

[[v10-10-13]]

^<<v10-10-13,13>>^ Então Joabe e o povo que estava com ele travaram a peleja contra os sírios; e estes fugiram diante dele.

[[v10-10-14]]

^<<v10-10-14,14>>^ E, vendo os amonitas que os sírios fugiam, também eles fugiram de diante de Abisai, e entraram na cidade. Então Joabe voltou dos amonitas e veio para Jerusalém.

[[v10-10-15]]

^<<v10-10-15,15>>^ Os sírios, vendo que tinham sido derrotados diante de Israel, trataram de refazer-se.

[[v10-10-16]]

^<<v10-10-16,16>>^ E Hadadézer mandou que viessem os sírios que estavam da outra banda do rio; e eles vieram a Helã, tendo à sua frente Sobaque, chefe do exército de Hadadézer.

[[v10-10-17]]

^<<v10-10-17,17>>^ Davi, informado disto, ajuntou todo o Israel e, passando o Jordão, foi a Helã; e os sírios se puseram em ordem contra Davi, e pelejaram contra ele.

[[v10-10-18]]

^<<v10-10-18,18>>^ Os sírios, porém, fugiram de diante de Israel; e Davi matou deles os homens de setecentos carros, e quarenta mil homens de cavalaria; e feriu a Sobaque, general do exército, de sorte que ele morreu ali.

[[v10-10-19]]

^<<v10-10-19,19>>^ Vendo, pois, todos os reis, servos de Hadadézer, que estavam derrotados diante de Israel, fizeram paz com Israel, e o serviram. E os sírios não ousaram mais socorrer aos amonitas.

'''

xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[&#60; Capítulo Anterior] | <<v10-10-0,Topo>> | xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[Próximo Capítulo &#62;]