include::./index.adoc[]

[[v10-16-0]]
=== 2 Samuel, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-16-1]]

^<<v10-16-1,1>>^ Tendo Davi passado um pouco além do cume, eis que Ziba, o moço de Mefibosete, veio encontrar-se com ele, com um par de jumentos albardados, e sobre eles duzentos pães, cem cachos de passas, e cem de frutas de verão e um odre de vinho.

[[v10-16-2]]

^<<v10-16-2,2>>^ Perguntou, pois, o rei a Ziba: Que pretendes com isso? Respondeu Ziba: Os jumentos são para a casa do rei, para se montarem neles; e o pão e as frutas de verão para os moços comerem; e o vinho para os cansados no deserto beberem.

[[v10-16-3]]

^<<v10-16-3,3>>^ Perguntou ainda o rei: E onde está o filho de teu senhor? Respondeu Ziba ao rei: Eis que permanece em Jerusalém, pois disse: Hoje a casa de Israel me restituirá o reino de meu pai.

[[v10-16-4]]

^<<v10-16-4,4>>^ Então disse o rei a Ziba: Eis que tudo quanto pertencia a Mefibosete é teu. Ao que Ziba, inclinando-se, disse: Que eu ache graça aos teus olhos, ó rei meu senhor.

[[v10-16-5]]

^<<v10-16-5,5>>^ Tendo o rei Davi chegado a Baurim, veio saindo dali um homem da linhagem da casa de Saul, cujo nome era Simei, filho de Gêra; e, adiantando-se, proferia maldições.

[[v10-16-6]]

^<<v10-16-6,6>>^ Também atirava pedras contra Davi e todos os seus servos, ainda que todo o povo e todos os valorosos iam à direita e à esquerda do rei.

[[v10-16-7]]

^<<v10-16-7,7>>^ E, amaldiçoando-o Simei, assim dizia: Sai, sai, homem sanguinário, homem de Belial!

[[v10-16-8]]

^<<v10-16-8,8>>^ O Senhor te deu agora a paga de todo o sangue da casa de Saul, em cujo lugar tens reinado; já entregou o Senhor o reino na mão de Absalão, teu filho; e eis-te agora na desgraça, pois és um homem sanguinário.

[[v10-16-9]]

^<<v10-16-9,9>>^ Então Abisai, filho de Zeruia, disse ao rei: Por que esse cão morto amaldiçoaria ao rei meu senhor? Deixa-me passar e tirar-lhe a cabeça.

[[v10-16-10]]

^<<v10-16-10,10>>^ Disse, porém, o rei: Que tenho eu convosco, filhos de Zeruia? Por ele amaldiçoar e por lhe ter dito o Senhor: Amaldiçoa a Davi; quem dirá: Por que assim fizeste?

[[v10-16-11]]

^<<v10-16-11,11>>^ Disse mais Davi a Abisai, e a todos os seus servos: Eis que meu filho, que saiu das minhas entranhas, procura tirar-me a vida; quanto mais ainda esse benjamita? Deixai-o; deixai que amaldiçoe, porque o Senhor lho ordenou.

[[v10-16-12]]

^<<v10-16-12,12>>^ Porventura o Senhor olhará para a minha aflição, e me pagará com bem a maldição deste dia.

[[v10-16-13]]

^<<v10-16-13,13>>^ Prosseguiam, pois, o seu caminho, Davi e os seus homens, enquanto Simei ia pela encosta do monte, defronte dele, caminhando e amaldiçoando, e atirava pedras contra ele, e levantava poeira.

[[v10-16-14]]

^<<v10-16-14,14>>^ E o rei e todo o povo que ia com ele chegaram cansados ao Jordão; e ali descansaram.

[[v10-16-15]]

^<<v10-16-15,15>>^ Absalão e todo o povo, os homens de Israel, vieram a Jerusalém; e Aitofel estava com ele.

[[v10-16-16]]

^<<v10-16-16,16>>^ E chegando Husai, o arquita, amigo de Davi, a Absalão, disse-lhe: Viva o rei, viva o rei!

[[v10-16-17]]

^<<v10-16-17,17>>^ Absalão, porém, perguntou a Husai: E esta a tua benevolência para com o teu amigo? Por que não foste com o teu amigo?

[[v10-16-18]]

^<<v10-16-18,18>>^ Respondeu-lhe Husai: Não; pois aquele a quem o Senhor, e este povo, e todos os homens de Israel têm escolhido, dele serei e com ele ficarei.

[[v10-16-19]]

^<<v10-16-19,19>>^ E, demais disto, a quem serviria eu? Porventura não seria a seu filho? como servi a teu pai, assim servirei a ti.

[[v10-16-20]]

^<<v10-16-20,20>>^ Então disse Absalão a Aitofel: Dai o vosso conselho sobre o que devemos fazer.

[[v10-16-21]]

^<<v10-16-21,21>>^ Respondeu Aitofel a Absalão: Entra às concubinas de teu pai, que ele deixou para guardarem a casa; e assim todo o Israel ouvirá que te fizeste aborrecível para com teu pai, e se fortalecerão as mãos de todos os que estão contigo.

[[v10-16-22]]

^<<v10-16-22,22>>^ Estenderam, pois, para Absalão uma tenda no terraço; e entrou Absalão às concubinas de seu pai, à vista de todo o Israel.

[[v10-16-23]]

^<<v10-16-23,23>>^ E o conselho que Aitofel dava naqueles dias era como se o oráculo de Deus se consultara; tal era todo o conselho de Aitofel, tanto para com Davi como para Absalão.

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]