include::./index.adoc[]

[[v10-3-0]]
=== 2 Samuel, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-3-1]]

^<<v10-3-1,1>>^ Ora, houve uma longa guerra entre a casa de Saul e a casa de Davi; porém Davi se fortalecia cada vez mais, enquanto a casa de Saul cada vez mais se enfraquecia.

[[v10-3-2]]

^<<v10-3-2,2>>^ Nasceram filhos a Davi em Hebrom. Seu primogênito foi Amnom, de Ainoã, a jizreelita;

[[v10-3-3]]

^<<v10-3-3,3>>^ o segundo Quileabe, de Abigail, que fôra mulher de Nabal, o carmelita; o terceiro Absalão, filho de Maacá, filha de Talmai, rei de Gesur;

[[v10-3-4]]

^<<v10-3-4,4>>^ o quarto Adonias, filho de Hagite, o quinto Sefatias, filho de Abital;

[[v10-3-5]]

^<<v10-3-5,5>>^ e o sexto Itreão, de Eglá, também mulher de Davi; estes nasceram a Davi em Hebrom.

[[v10-3-6]]

^<<v10-3-6,6>>^ Enquanto havia guerra entre a casa de Saul e a casa de Davi, Abner ia se tornando poderoso na casa de Saul:

[[v10-3-7]]

^<<v10-3-7,7>>^ Ora, Saul tivera uma concubina, cujo nome era Rizpa, filha de Aías. Perguntou, pois, Is-Bosete a Abner: Por que entraste à concubina de meu pai?

[[v10-3-8]]

^<<v10-3-8,8>>^ Então Abner, irando-se muito pelas palavras de Is-Bosete, disse: Sou eu cabeça de cão, que pertença a Judá? Ainda hoje uso de benevolência para com a casa de Saul, teu pai, e para com seus irmãos e seus amigos, e não te entreguei nas mãos de Davi; contudo tu hoje queres culpar-me no tocante a essa mulher.

[[v10-3-9]]

^<<v10-3-9,9>>^ Assim faça Deus a Abner, e outro tanto, se, como o Senhor jurou a Davi, assim eu não lhe fizer,

[[v10-3-10]]

^<<v10-3-10,10>>^ transferindo o reino da casa de Saul, e estabelecendo o trono de Davi sobre Israel, e sobre Judá, desde Dã até Berseba.

[[v10-3-11]]

^<<v10-3-11,11>>^ E Is-Bosete não pôde responder a Abner mais uma palavra, porque o temia.

[[v10-3-12]]

^<<v10-3-12,12>>^ Então enviou Abner da sua parte mensageiros a Davi, dizendo: De quem é a terra? Comigo faze a tua aliança, e eis que a minha mão será contigo, para fazer tornar a ti todo o Israel.

[[v10-3-13]]

^<<v10-3-13,13>>^ Respondeu Davi: Está bem; farei aliança contigo; mas uma coisa te exijo; não verás a minha face, se primeiro não me trouxeres Mical, filha de Saul, quando vieres ver a minha face.

[[v10-3-14]]

^<<v10-3-14,14>>^ Também enviou Davi mensageiros a Is-Bosete, filho de Saul, dizendo: Entrega-me minha mulher Mical, que eu desposei por cem prepúcios de filisteus.

[[v10-3-15]]

^<<v10-3-15,15>>^ Enviou, pois, Is-Bosete, e a tirou a seu marido, a Paltiel, filho de Laís,

[[v10-3-16]]

^<<v10-3-16,16>>^ que a seguia, chorando atrás dela até Baurim. Então lhe disse Abner: Vai-te; volta! E ele voltou.

[[v10-3-17]]

^<<v10-3-17,17>>^ Falou Abner com os anciãos de Israel, dizendo: De há muito procurais fazer com que Davi reine sobre vós;

[[v10-3-18]]

^<<v10-3-18,18>>^ fazei-o, pois, agora, porque o Senhor falou de Davi, dizendo: Pela mão do meu servo Davi livrarei o meu povo da mão dos filisteus e da mão de todos os seus inimigos.

[[v10-3-19]]

^<<v10-3-19,19>>^ Do mesmo modo falou Abner a Benjamim, e foi também dizer a Davi, em Hebrom, tudo o que Israel e toda a casa de Benjamim tinham resolvido.

[[v10-3-20]]

^<<v10-3-20,20>>^ Abner foi ter com Davi, em Hebrom, com vinte homens; e Davi fez um banquete a Abner e aos homens que com ele estavam.

[[v10-3-21]]

^<<v10-3-21,21>>^ Então disse Abner a Davi: Eu me levantarei, e irei ajuntar ao rei meu senhor todo o Israel, para que faça aliança contigo; e tu reinarás sobre tudo o que desejar a sua alma: Assim despediu Davi a Abner, e ele se foi em paz.

[[v10-3-22]]

^<<v10-3-22,22>>^ Eis que os servos de Davi e Joabe voltaram de uma sortida, e traziam consigo grande despojo; mas Abner já não estava com Davi em Hebrom, porque este o tinha despedido, e ele se fora em paz.

[[v10-3-23]]

^<<v10-3-23,23>>^ Quando, pois, chegaram Joabe e todo o exército que vinha com ele, disseram-lhe: Abner, filho de Ner, veio ter com o rei; e o rei o despediu, e ele se foi em paz.

[[v10-3-24]]

^<<v10-3-24,24>>^ Então Joabe foi ao rei, e disse: Que fizeste? Eis que Abner veio ter contigo; por que, pois, o despediste, de maneira que se fosse assim livremente?

[[v10-3-25]]

^<<v10-3-25,25>>^ Bem conheces a Abner, filho de Ner; ele te veio enganar, e saber a tua saída e a tua entrada, e conhecer tudo quanto fazes.

[[v10-3-26]]

^<<v10-3-26,26>>^ E Joabe, retirando-se de Davi, enviou mensageiros atrás de Abner, que o fizeram voltar do poço de Sira, sem que Davi o soubesse.

[[v10-3-27]]

^<<v10-3-27,27>>^ Quando Abner voltou a Hebrom, Joabe o tomou à parte, à entrada da porta, para lhe falar em segredo; e ali, por causa do sangue de Asael, seu irmão, o feriu no ventre, de modo que ele morreu.

[[v10-3-28]]

^<<v10-3-28,28>>^ Depois Davi, quando o soube, disse: Inocente para sempre sou eu, e o meu reino, para com o Senhor, no tocante ao sangue de Abner, filho de Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ Caia ele sobre a cabeça de Joabe e sobre toda a casa de seu pai, e nunca falte na casa de Joabe quem tenha fluxo, ou quem seja leproso, ou quem se atenha a bordão, ou quem caia à espada, ou quem necessite de pão.

[[v10-3-30]]

^<<v10-3-30,30>>^ Joabe, pois, e Abisai, seu irmão, mataram Abner, por ter ele morto a Asael, irmão deles, na peleja em Gibeão.

[[v10-3-31]]

^<<v10-3-31,31>>^ Disse Davi a Joabe e a todo o povo que com ele estava: Rasgai as vossas vestes, cingi-vos de sacos e ide pranteando diante de Abner. E o rei Davi ia seguindo o féretro.

[[v10-3-32]]

^<<v10-3-32,32>>^ Sepultaram Abner em Hebrom; e o rei, levantando a sua voz, chorou junto da sepultura de Abner; chorou também todo o povo.

[[v10-3-33]]

^<<v10-3-33,33>>^ Pranteou o rei a Abner, dizendo: Devia Abner, porventura, morrer como morre o vilão?

[[v10-3-34]]

^<<v10-3-34,34>>^ As tuas mãos não estavam atadas, nem os teus pés carregados de grilhões; mas caíste como quem cai diante dos filhos da iniqüidade. Então todo o povo tornou a chorar por ele.

[[v10-3-35]]

^<<v10-3-35,35>>^ Depois todo o povo veio fazer com que Davi comesse pão, sendo ainda dia; porém Davi jurou, dizendo: Assim Deus me faça e outro tanto, se, antes que o sol se ponha, eu provar pão ou qualquer outra coisa.

[[v10-3-36]]

^<<v10-3-36,36>>^ Todo o povo notou isso, e pareceu-lhe bem; assim como tudo quanto o rei fez pareceu bem a todo o povo.

[[v10-3-37]]

^<<v10-3-37,37>>^ Assim todo o povo e todo o Israel entenderam naquele mesmo dia que não fora a vontade do rei que matassem a Abner, filho de Ner.

[[v10-3-38]]

^<<v10-3-38,38>>^ Então disse o rei aos seus servos: Não sabeis que hoje caiu em Israel um príncipe, um grande homem?

[[v10-3-39]]

^<<v10-3-39,39>>^ E quanto a mim, hoje estou fraco, embora ungido rei; estes homens, filhos de Zeruia, são duros demais para mim. Retribua o Senhor ao malfeitor conforme a sua maldade.

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]