include::./index.adoc[]

[[v10-5-0]]
=== 2 Samuel, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v10-5-1]]

^<<v10-5-1,1>>^ Então todas as tribos de Israel vieram a Davi em Hebrom e disseram: Eis-nos aqui, teus ossos e tua carne!

[[v10-5-2]]

^<<v10-5-2,2>>^ Além disso, outrora, quando Saul ainda reinava sobre nós, eras tu o que saías e entravas com Israel; e também o Senhor te disse: Tu apascentarás o meu povo de Israel, e tu serás chefe sobre Israel.

[[v10-5-3]]

^<<v10-5-3,3>>^ Assim, pois, todos os anciãos de Israel vieram ter com o rei em Hebrom; e o rei Davi fez aliança com eles em Hebrom, perante o Senhor; e ungiram a Davi rei sobre Israel.

[[v10-5-4]]

^<<v10-5-4,4>>^ Trinta anos tinha Davi quando começou a reinar, e reinou quarenta anos.

[[v10-5-5]]

^<<v10-5-5,5>>^ Em Hebrom reinou sete anos e seis meses sobre Judá, e em Jerusalém reinou trinta e três anos sobre todo o Israel e Judá.

[[v10-5-6]]

^<<v10-5-6,6>>^ Depois partiu o rei com os seus homens para Jerusalém, contra os jebuseus, que habitavam naquela terra, os quais disseram a Davi: Não entrarás aqui; os cegos e es coxos te repelirão; querendo dizer: Davi de maneira alguma entrará aqui.

[[v10-5-7]]

^<<v10-5-7,7>>^ Todavia Davi tomou a fortaleza de Sião; esta é a cidade de Davi.

[[v10-5-8]]

^<<v10-5-8,8>>^ Ora, Davi disse naquele dia: Todo o que ferir os jebuseus, suba ao canal, e fira a esses coxos e cegos, a quem a alma de Davi aborrece. Por isso se diz: Nem cego nem, coxo entrara na casa.

[[v10-5-9]]

^<<v10-5-9,9>>^ Assim habitou Davi na fortaleza, e chamou-a cidade de Davi; e foi levantando edifícios em redor, desde Milo para dentro.

[[v10-5-10]]

^<<v10-5-10,10>>^ Davi ia-se engrandecendo cada vez mais, porque o Senhor Deus dos exércitos era com ele.

[[v10-5-11]]

^<<v10-5-11,11>>^ Hirão, rei de Tiro, enviou mensageiros a Davi, e madeira de cedro, e carpinteiros e pedreiros, que edificaram para Davi uma casa.

[[v10-5-12]]

^<<v10-5-12,12>>^ Entendeu, pois, Davi que o Senhor o confirmara rei sobre Israel, e que exaltara e reino dele por amar do seu povo Israel.

[[v10-5-13]]

^<<v10-5-13,13>>^ Davi tomou ainda para si concubinas e mulheres de Jerusalém, depois que viera de Hebrom; e nasceram a Davi mais filhos e filhas.

[[v10-5-14]]

^<<v10-5-14,14>>^ São estes os nomes dos que lhe nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v10-5-15]]

^<<v10-5-15,15>>^ Ibar, Elisua, Nefegue, Jafia,

[[v10-5-16]]

^<<v10-5-16,16>>^ Elisama, e Eliadá e Elifelete.

[[v10-5-17]]

^<<v10-5-17,17>>^ Quando os filisteus ouviram que Davi fora ungido rei sobre Israel, subiram todos em busca dele. Ouvindo isto, Davi desceu à fortaleza.

[[v10-5-18]]

^<<v10-5-18,18>>^ Os filisteus vieram, e se estenderam pelo vale de Refaim.

[[v10-5-19]]

^<<v10-5-19,19>>^ Pelo que Davi consultou ao Senhor, dizendo: Subirei contra os filisteus? entregar-mos-ás nas mãos? Respondeu o Senhor a Davi: Sobe, pois eu entregarei os filisteus nas tuas mãos.

[[v10-5-20]]

^<<v10-5-20,20>>^ Então foi Davi a Baal-Perazim, e ali os derrotou; e disse: O Senhor rompeu os meus inimigos diante de mim, como as águas rompem barreiras. Por isso chamou o nome daquele lugar Baal-Perazim.

[[v10-5-21]]

^<<v10-5-21,21>>^ Os filisteus deixaram lá os seus ídolos, e Davi e os seus homens os levaram.

[[v10-5-22]]

^<<v10-5-22,22>>^ Tornaram ainda os filisteus a subir, e se espalharam pelo vale de Refaim.

[[v10-5-23]]

^<<v10-5-23,23>>^ E Davi consultou ao Senhor, que respondeu: Não subirás; mas rodeia-os por detrás, e virás sobre eles por defronte dos balsameiros.

[[v10-5-24]]

^<<v10-5-24,24>>^ E há de ser que, ouvindo tu o ruído de marcha pelas copas dos balsameiros, então te apressarás, porque é o Senhor que sai diante de ti, a ferir o arraial dos filisteus.

[[v10-5-25]]

^<<v10-5-25,25>>^ Fez, pois, Davi como o Senhor lhe havia ordenado; e feriu os filisteus desde Geba, até chegar a Gezer.

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]