include::./index.adoc[]

[[v30-4-0]]
=== Amós, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-4-1]]

^<<v30-4-1,1>>^ Ouvi esta palavra, vós, vacas de Basã, que estais no monte de Samária, que oprimis os pobres, que esmagais os necessitados, que dizeis a vossos maridos: Dai cá, e bebamos.

[[v30-4-2]]

^<<v30-4-2,2>>^ Jurou o Senhor Deus, pela sua santidade, que dias estão para vir sobre vós, em que vos levarão com anzóis, e aos que sairdes por último com anzóis de pesca.

[[v30-4-3]]

^<<v30-4-3,3>>^ E saireis pelas brechas, cada qual em frente de si, e sereis lançadas para Harmom, diz o senhor.

[[v30-4-4]]

^<<v30-4-4,4>>^ Vinde a Betel, e transgredi; a Gilgal, e multiplicai as transgressões; e cada manhã trazei os vossos sacrifícios, e de três em três dias os vossos dízimos.

[[v30-4-5]]

^<<v30-4-5,5>>^ E oferecei sacrifício de louvores do que é levedado, e apregoai ofertas voluntárias, publicai-as; pois disso gostais, ó filhos de Israel, diz o Senhor Deus.

[[v30-4-6]]

^<<v30-4-6,6>>^ Por isso também vos dei limpeza de dentes em todas as vossas cidades, e falta de pão em todos os vossos lugares; contudo não vos convertestes a mim, diz o Senhor.

[[v30-4-7]]

^<<v30-4-7,7>>^ Além disso, retive de vós a chuva, quando ainda faltavam três meses para a ceifa; e fiz que chovesse sobre uma cidade, e que não chovesse sobre outra cidade; sobre um campo choveu, mas o outro, sobre o qual não choveu, secou-se.

[[v30-4-8]]

^<<v30-4-8,8>>^ Andaram errantes duas ou três cidades, indo a outra cidade para beberem água, mas não se saciaram; contudo não vos convertestes a mim, diz o Senhor.

[[v30-4-9]]

^<<v30-4-9,9>>^ Feri-vos com crestamento e ferrugem; a multidão das vossas hortas, e das vossas vinhas, e das vossas figueiras, e das vossas oliveiras, foi devorada pela locusta; contudo não vos convertestes a mim, diz o Senhor.

[[v30-4-10]]

^<<v30-4-10,10>>^ Enviei a peste contra vós, à maneira de Egito; os vossos mancebos matei à espada, e os vossos cavalos deixei levar presos, e o fedor do vosso arraial fiz subir aos vossos narizes; contudo não vos convertestes a mim, diz o Senhor.

[[v30-4-11]]

^<<v30-4-11,11>>^ Subverti alguns dentre vós, como Deus subverteu a Sodoma e Gomorra, e ficastes sendo como um tição arrebatado do incêndio; contudo não vos convertestes a mim, diz o Senhor.

[[v30-4-12]]

^<<v30-4-12,12>>^ Portanto assim te farei, ó Israel, e porque isso te farei, prepara-te, ó Israel, para te encontrares com o teu Deus.

[[v30-4-13]]

^<<v30-4-13,13>>^ Porque é ele o que forma os montes, e cria o vento, e declara ao homem qual seja o seu pensamento, o que faz da manhã trevas, e anda sobre os lugares altos da terra; o Senhor, o Deus dos exércitos é o seu nome.

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]