include::./index.adoc[]

[[v30-9-0]]
=== Amós, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-9-1]]

^<<v30-9-1,1>>^ Vi o Senhor, que estava junto ao altar; e me disse: Fere os capitéis, para que estremeçam os umbrais; e faze tudo em pedaços sobre a cabeça de todos eles; e eu matarei à espada até o último deles; nenhum deles conseguirá fugir, nenhum deles escapará.

[[v30-9-2]]

^<<v30-9-2,2>>^ Ainda que cavem até o Seol, dali os tirará a minha mão; ainda que subam ao céu, dali os farei descer.

[[v30-9-3]]

^<<v30-9-3,3>>^ Ainda que se escondam no cume do Carmelo, buscá-los-ei, e dali os tirarei; e, ainda que se ocultem aos meus olhos no fundo do mar, ali darei ordem à serpente, e ela os morderá.

[[v30-9-4]]

^<<v30-9-4,4>>^ Também ainda que vão para o cativeiro diante de seus inimigos, ali darei ordem à espada, e ela os matará; enfim eu porei os meus olhos sobre eles para o mal, e não para o bem.

[[v30-9-5]]

^<<v30-9-5,5>>^ Pois o Senhor, o Deus dos exércitos, é o que toca a terra, e ela se derrete, e pranteiam todos os que nela habitam; e ela toda se levanta como o Nilo, e diminui como o Nilo do Egito.

[[v30-9-6]]

^<<v30-9-6,6>>^ Ele é o que edifica as suas câmaras no céu, e funda sobre a terra a sua abóbada; que chama as águas do mar, e as derrama sobre a terra; o Senhor é o seu nome.

[[v30-9-7]]

^<<v30-9-7,7>>^ Não sois vós para comigo, ó filhos de Israel, como os filhos dos etíopes? diz o Senhor; não fiz eu subir a Israel da terra do Egito, e aos filisteus de Caftor, e aos sírios de Quir?

[[v30-9-8]]

^<<v30-9-8,8>>^ Eis que os olhos do Senhor Deus estão contra este reino pecador, e eu o destruirei de sobre a face da terra; contudo não destruirei de todo a casa de Jacó, diz o Senhor.

[[v30-9-9]]

^<<v30-9-9,9>>^ Pois eis que darei ordens, e sacudirei a casa de Israel em todas as nações, assim como se sacode grão no crivo; todavia não cairá sobre a terra um só grão.

[[v30-9-10]]

^<<v30-9-10,10>>^ Morrerão à espada todos os pecadores do meu povo, os quais dizem: O mal não nos alcançará, nem nos encontrará.

[[v30-9-11]]

^<<v30-9-11,11>>^ Naquele dia tornarei a levantar o tabernáculo de Davi, que está caído, e repararei as suas brechas, e tornarei a levantar as suas ruínas, e as reedificarei como nos dias antigos;

[[v30-9-12]]

^<<v30-9-12,12>>^ para que eles possuam o resto de Edom, e todas as nações que são chamadas pelo meu nome, diz o Senhor, que faz estas coisas.

[[v30-9-13]]

^<<v30-9-13,13>>^ Eis que vêm os dias, diz o Senhor, em que o que lavra alcançará ao que sega, e o que pisa as uvas ao que lança a semente; :e os montes destilarão mosto, e todos os outeiros se derreterão.

[[v30-9-14]]

^<<v30-9-14,14>>^ Também trarei do cativeiro o meu povo Israel; e eles reedificarão as cidades assoladas, e nelas habitarão; plantarão vinhas, e beberão o seu vinho; e farão pomares, e lhes comerão o fruto.

[[v30-9-15]]

^<<v30-9-15,15>>^ Assim os plantarei na sua terra, e não serão mais arrancados da sua terra que lhes dei, diz o senhor teu Deus.

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadias/031-obadias-001.adoc#v31-1-0[Próximo Capítulo &#62;]