include::./index.adoc[]

[[v30-5-0]]
=== Amós, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-5-1]]

^<<v30-5-1,1>>^ Ouvi esta palavra que levanto como lamentação sobre vós, ó casa de Israel.

[[v30-5-2]]

^<<v30-5-2,2>>^ A virgem de Israel caiu; nunca mais tornará a levantar-se; desamparada jaz na sua terra; não há quem a levante.

[[v30-5-3]]

^<<v30-5-3,3>>^ Porque assim diz o Senhor Deus: A cidade da qual saem mil terá de resto cem, e aquela da qual saem cem terá dez para a casa de Israel.

[[v30-5-4]]

^<<v30-5-4,4>>^ Pois assim diz o Senhor à casa de Israel: Buscai-me, e vivei.

[[v30-5-5]]

^<<v30-5-5,5>>^ Mas não busqueis a Betel, nem entreis em Gilgal, nem passeis a Berseba; porque Gilgal certamente irá ao cativeiro, e Betel será desfeita em nada.

[[v30-5-6]]

^<<v30-5-6,6>>^ Buscai ao Senhor, e vivei; para que ele não irrompa na casa de José como fogo e a consuma, e não haja em Betel quem o apague.

[[v30-5-7]]

^<<v30-5-7,7>>^ Vós que converteis o juízo em alosna, e deitais por terra a justiça,

[[v30-5-8]]

^<<v30-5-8,8>>^ procurai aquele que fez as Plêiades e o Oriom, e torna a sombra da noite em manhã, e transforma o dia em noite; o que chama as águas do mar, e as derrama sobre a terra; o Senhor é o seu nome.

[[v30-5-9]]

^<<v30-5-9,9>>^ O que faz vir súbita destruição sobre o forte, de sorte que vem a ruína sobre a fortaleza.

[[v30-5-10]]

^<<v30-5-10,10>>^ Eles odeiam ao que na porta os repreende, e abominam ao que fala a verdade.

[[v30-5-11]]

^<<v30-5-11,11>>^ Portanto, visto que pisais o pobre, e dele exigis tributo de trigo, embora tenhais edificado casas de pedras lavradas, não habitareis nelas; e embora tenhais plantado vinhas desejáveis, não bebereis do seu vinho.

[[v30-5-12]]

^<<v30-5-12,12>>^ Pois sei que são muitas as vossas transgressões, e graves os vossos pecados; afligis o justo, aceitais peitas, e na porta negais o direito aos necessitados.

[[v30-5-13]]

^<<v30-5-13,13>>^ Portanto, o que for prudente guardará silêncio naquele tempo, porque o tempo será mau.

[[v30-5-14]]

^<<v30-5-14,14>>^ Buscai o bem, e não o mal, para que vivais; e assim o Senhor, o Deus dos exércitos, estará convosco, como dizeis.

[[v30-5-15]]

^<<v30-5-15,15>>^ Aborrecei o mal, e amai o bem, e estabelecei o juízo na porta. Talvez o Senhor, o Deus dos exércitos, tenha piedade do resto de José.

[[v30-5-16]]

^<<v30-5-16,16>>^ Portanto, assim diz o Senhor Deus dos exércitos, o Senhor: Em todas as praças haverá pranto, e em todas as ruas dirão: Ai! ai! E ao lavrador chamarão para choro, e para pranto os que souberem prantear.

[[v30-5-17]]

^<<v30-5-17,17>>^ E em todas as vinhas haverá pranto; porque passarei pelo meio de ti, diz o Senhor.

[[v30-5-18]]

^<<v30-5-18,18>>^ Ai de vós que desejais o dia do Senhor! Para que quereis vós este dia do Senhor? Ele é trevas e não luz.

[[v30-5-19]]

^<<v30-5-19,19>>^ E como se um homem fugisse de diante do leão, e se encontrasse com ele o urso; ou como se, entrando em casa, encostasse a mão à parede, e o mordesse uma cobra.

[[v30-5-20]]

^<<v30-5-20,20>>^ Não será, pois, o dia do Senhor trevas e não luz? não será completa escuridade, sem nenhum resplendor?

[[v30-5-21]]

^<<v30-5-21,21>>^ Aborreço, desprezo as vossas festas, e não me deleito nas vossas assembléias solenes.

[[v30-5-22]]

^<<v30-5-22,22>>^ Ainda que me ofereçais holocaustos, juntamente com as vossas ofertas de cereais, não me agradarei deles; nem atentarei para as ofertas pacíficas de vossos animais cevados.

[[v30-5-23]]

^<<v30-5-23,23>>^ Afasta de mim o estrépito dos teus cânticos, porque não ouvirei as melodias das tuas liras.

[[v30-5-24]]

^<<v30-5-24,24>>^ Corra, porém, a justiça como as águas, e a retidão como o ribeiro perene.

[[v30-5-25]]

^<<v30-5-25,25>>^ Oferecestes-me vós sacrifícios e oblações no deserto por quarenta anos, ó casa de Israel?

[[v30-5-26]]

^<<v30-5-26,26>>^ Sim, levastes Sicute, vosso rei, e Quium, vosso deus-estrela, imagens que fizestes para vos mesmos.

[[v30-5-27]]

^<<v30-5-27,27>>^ Portanto vos levarei cativos para além de Damasco, diz o Senhor, cujo nome é o Deus dos Exércitos.

'''

xref:030-amos/030-amos-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-amos/030-amos-006.adoc#v30-6-0[Próximo Capítulo &#62;]