include::./index.adoc[]

[[v30-1-0]]
=== Amós, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-1-1]]

^<<v30-1-1,1>>^ As palavras de Amós, que estava entre os pastores de Tecoa, o que ele viu a respeito de Israel, nos dias de Uzias, rei de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel, dois anos antes do terremoto.

[[v30-1-2]]

^<<v30-1-2,2>>^ Disse ele: O Senhor brama de Sião, e de Jerusalém faz ouvir a sua voz; os prados dos pastores lamentam, seca-se o cume do Carmelo.

[[v30-1-3]]

^<<v30-1-3,3>>^ Assim diz o senhor: Por três transgressões de Damasco, sim, por quatro, não retirarei o castigo; porque trilharam a Gileade com trilhos de ferro.

[[v30-1-4]]

^<<v30-1-4,4>>^ Por isso porei fogo à casa de Hazael, e ele consumirá os palácios de Ben-Hadade.

[[v30-1-5]]

^<<v30-1-5,5>>^ Quebrarei o ferrolho de Damasco, e exterminarei o morador do vale de Ávem e de Bete-Éden aquele que tem o cetro; e o povo da Síria será levado em cativeiro a Quir, diz o Senhor.

[[v30-1-6]]

^<<v30-1-6,6>>^ Assim diz o Senhor: Por três transgressões de Gaza, sim, por quatro, não retirarei o castigo; porque levaram cativo todo o povo para o entregarem a Edom.

[[v30-1-7]]

^<<v30-1-7,7>>^ Por isso porei fogo ao muro de Gaza, e ele consumirá os seus palácios.

[[v30-1-8]]

^<<v30-1-8,8>>^ De Asdode exterminarei o morador, e de Asquelom aquele que tem o cetro; tornarei a minha mão contra Ecrom; e o resto dos filisteus perecerá, diz o Senhor Deus.

[[v30-1-9]]

^<<v30-1-9,9>>^ Assim diz o Senhor: Por três transgressões de Tiro, sim, por quatro, não retirarei o castigo; porque entregaram todos os cativos a Edom, e não se lembraram da aliança dos irmãos.

[[v30-1-10]]

^<<v30-1-10,10>>^ por isso porei fogo ao muro de Tiro, e ele consumirá os seus palácios.

[[v30-1-11]]

^<<v30-1-11,11>>^ Assim diz o Senhor: Por três transgressões de Edom, sim, por quatro, não retirarei o castigo; porque perseguiu a seu irmão à espada, e baniu toda a compaixão; e a sua ira despedaçou eternamente, e conservou a sua indignação para sempre.

[[v30-1-12]]

^<<v30-1-12,12>>^ Por isso porei fogo a Temã, o qual consumirá os palácios de Bozra.

[[v30-1-13]]

^<<v30-1-13,13>>^ Assim diz o Senhor: Por três transgressões dos filhos de Amom, sim por quatro, não retirarei o castigo; porque fenderam o ventre às grávidas de Gileade, para dilatarem os seus termos.

[[v30-1-14]]

^<<v30-1-14,14>>^ Por isso porei fogo ao muro de Rabá, fogo que lhe consumirá os palácios, com alarido no dia da batalha, com tempestade no dia do turbilhão.

[[v30-1-15]]

^<<v30-1-15,15>>^ E o seu rei irá para o cativeiro, ele e os seus príncipes juntamente, diz o Senhor.

'''

xref:029-joel/029-joel-003.adoc#v29-3-0[&#60; Capítulo Anterior] | <<v30-1-0,Topo>> | xref:030-amos/030-amos-002.adoc#v30-2-0[Próximo Capítulo &#62;]