include::./index.adoc[]

[[v30-8-0]]
=== Amós, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-8-1]]

^<<v30-8-1,1>>^ O Senhor Deus assim me fez ver: e eis aqui um cesto de frutos do verão.

[[v30-8-2]]

^<<v30-8-2,2>>^ E disse: Que vês, Amós? Eu respondi: um cesto de frutos do verão. Então o Senhor me disse: Chegou o fim sobre o meu povo Israel; nunca mais passarei por ele.

[[v30-8-3]]

^<<v30-8-3,3>>^ Mas os cânticos do templo serão gritos de dor naquele dia, diz o Senhor Deus; muitos serão os cadáveres; em todos os lugares serão lançados fora em silêncio.

[[v30-8-4]]

^<<v30-8-4,4>>^ Ouvi isto, vós que pisais os necessitados, e destruís os miseráveis da terra,

[[v30-8-5]]

^<<v30-8-5,5>>^ dizendo: Quando passará a lua nova, para vendermos o grão? e o sábado, para expormos o trigo, diminuindo a medida, e aumentando o preço, e procedendo dolosamente com balanças enganadoras,

[[v30-8-6]]

^<<v30-8-6,6>>^ para comprarmos os pobres por dinheiro, e os necessitados por um par de sapatos, e para vendermos o refugo do trigo?

[[v30-8-7]]

^<<v30-8-7,7>>^ Jurou o Senhor pela glória de Jacó: Certamente nunca me esquecerei de nenhuma das suas obras.

[[v30-8-8]]

^<<v30-8-8,8>>^ Por causa disso não estremecerá a terra? e não chorará todo aquele que nela habita? Certamente se levantará ela toda como o Nilo, e será agitada, e diminuirá como o Nilo do Egito.

[[v30-8-9]]

^<<v30-8-9,9>>^ E sucederá, naquele dia, diz o Senhor Deus, que farei que o sol se ponha ao meio dia, e em pleno dia cobrirei a terra de trevas.

[[v30-8-10]]

^<<v30-8-10,10>>^ E tornarei as vossas festas em luto, e todos os vossos cânticos em lamentações; porei saco sobre todos os lombos, e calva sobre toda cabeça; e farei que isso seja como o luto por um filho único, e o seu fim como dia de amarguras.

[[v30-8-11]]

^<<v30-8-11,11>>^ Eis que vêm os dias, diz o Senhor Deus, em que enviarei fome sobre a terra; não fome de pão, nem sede de água, mas de ouvir as palavras do Senhor.

[[v30-8-12]]

^<<v30-8-12,12>>^ Andarão errantes de mar a mar, e do norte até o oriente; correrão por toda parte, buscando a palavra do Senhor, e não a acharão.

[[v30-8-13]]

^<<v30-8-13,13>>^ Naquele dia as virgens formosas e os mancebos desmaiarão de sede.

[[v30-8-14]]

^<<v30-8-14,14>>^ Os que juram pelo pecado de Samária, dizendo: Pela vida do teu deus, ó Dã; e: Pelo caminho de Berseba; esses mesmos cairão, e não se levantarão mais.

'''

xref:030-amos/030-amos-007.adoc#v30-7-0[&#60; Capítulo Anterior] | <<v30-8-0,Topo>> | xref:030-amos/030-amos-009.adoc#v30-9-0[Próximo Capítulo &#62;]