include::./index.adoc[]

[[v30-2-0]]
=== Amós, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-2-1]]

^<<v30-2-1,1>>^ Assim diz o Senhor: Por três transgressões de Moabe, sim, por quatro, não retirarei o castigo; porque queimou os ossos do rei de Edom, até os reduzir a cal.

[[v30-2-2]]

^<<v30-2-2,2>>^ Por isso porei fogo a Moabe, e ele consumirá os palácios de Queriote; e Moabe morrerá com grande estrondo, com alarido, e som de trombeta.

[[v30-2-3]]

^<<v30-2-3,3>>^ E exterminarei o juiz do meio dele, e matarei com ele todos os seus príncipes, diz o Senhor.

[[v30-2-4]]

^<<v30-2-4,4>>^ Assim diz o Senhor: Por três transgressões de Judá, sim, por quatro, não retirarei o castigo; porque rejeitaram a lei do Senhor, e não guardaram os seus estatutos, antes se deixaram enganar por suas próprias mentiras, após as quais andaram seus pais.

[[v30-2-5]]

^<<v30-2-5,5>>^ Por isso porei fogo a Judá, e ele consumirá os palácios de Jerusalém.

[[v30-2-6]]

^<<v30-2-6,6>>^ Assim diz o Senhor: Por três transgressões de Israel, sim, por quatro, não retirarei o castigo; porque vendem o justo por dinheiro, e o necessitado por um par de sapatos.

[[v30-2-7]]

^<<v30-2-7,7>>^ Pisam a cabeça dos pobres no pó da terra, pervertem o caminho dos mansos; um homem e seu pai entram à mesma moça, assim profanando o meu santo nome.

[[v30-2-8]]

^<<v30-2-8,8>>^ Também se deitam junto a qualquer altar sobre roupas empenhadas, e na casa de seu Deus bebem o vinho dos que têm sido multados.

[[v30-2-9]]

^<<v30-2-9,9>>^ Contudo eu destruí o amorreu diante deles, a altura do qual era como a dos cedros, e cuja força era como a dos carvalhos; mas destruí o seu fruto por cima, e as suas raízes por baixo.

[[v30-2-10]]

^<<v30-2-10,10>>^ Outrossim vos fiz subir da terra do Egito, e quarenta anos vos guiei no deserto, para que possuísseis a terra do amorreu.

[[v30-2-11]]

^<<v30-2-11,11>>^ E dentre vossos filhos suscitei profetas, e dentre os vossos mancebos, nazireus. Acaso não é isso assim, filhos de Israel? diz o Senhor.

[[v30-2-12]]

^<<v30-2-12,12>>^ Mas vós aos nazireus destes vinho a beber, e aos profetas ordenastes, dizendo: Não profetizeis.

[[v30-2-13]]

^<<v30-2-13,13>>^ Eis que eu vos apertarei no vosso lugar como se aperta um carro cheio de feixes.

[[v30-2-14]]

^<<v30-2-14,14>>^ Assim de nada valerá a fuga ao ágil, nem o forte corroborará a sua força, nem o valente salvará a sua vida.

[[v30-2-15]]

^<<v30-2-15,15>>^ E não ficará em pé o que maneja o arco, nem o ligeiro de pés se livrará, nem tampouco se livrara o que vai montado a cavalo;

[[v30-2-16]]

^<<v30-2-16,16>>^ e aquele que é corajoso entre os valentes fugirá nu naquele dia, diz o Senhor.

'''

xref:030-amos/030-amos-001.adoc#v30-1-0[&#60; Capítulo Anterior] | <<v30-2-0,Topo>> | xref:030-amos/030-amos-003.adoc#v30-3-0[Próximo Capítulo &#62;]