include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-7-1]]

^<<v30-7-1,1>>^ O Senhor Deus assim me fez ver: e eis que ele formava gafanhotos no princípio do rebentar da erva serôdia, e eis que era a erva serôdia depois da segada do rei.

[[v30-7-2]]

^<<v30-7-2,2>>^ E quando eles tinham comido completamente a erva da terra, eu disse: Senhor Deus, perdoa, peço-te; como subsistirá Jacó? pois ele é pequeno.

[[v30-7-3]]

^<<v30-7-3,3>>^ Então o Senhor se arrependeu disso. Não acontecerá, disse o Senhor.

[[v30-7-4]]

^<<v30-7-4,4>>^ Assim me mostrou o Senhor Deus: eis que o Senhor Deus ordenava que por meio do fogo se decidisse o pleito; o fogo, pois, consumiu o grande abismo, e também queria consumir a terra.

[[v30-7-5]]

^<<v30-7-5,5>>^ Então eu disse: Senhor Deus, cessa agora; como subsistirá Jacó? pois ele é pequeno.

[[v30-7-6]]

^<<v30-7-6,6>>^ Também disso se arrependeu o Senhor. Nem isso acontecerá, disse o Senhor Deus.

[[v30-7-7]]

^<<v30-7-7,7>>^ Mostrou-me também assim: eis que o senhor estava junto a um muro levantado a prumo, e tinha um prumo na mão.

[[v30-7-8]]

^<<v30-7-8,8>>^ Perguntou-me o Senhor: Que vês tu, Amós? Respondi: Um prumo. Então disse o Senhor: Eis que eu porei o prumo no meio do meu povo Israel; nunca mais passarei por ele.

[[v30-7-9]]

^<<v30-7-9,9>>^ Mas os altos de Isaque serão assolados, e destruídos os santuários de Israel; e levantar-me-ei com a espada contra a casa de Jeroboão.

[[v30-7-10]]

^<<v30-7-10,10>>^ Então Amazias, o sacerdote de Betel, mandou dizer a Jeroboão, rei de Israel: Amós tem conspirado contra ti no meio da casa de Israel; a terra não poderá suportar todas as suas palavras.

[[v30-7-11]]

^<<v30-7-11,11>>^ Pois assim diz Amós: Jeroboão morrerá à espada, e Israel certamente será levado cativo para fora da sua terra.

[[v30-7-12]]

^<<v30-7-12,12>>^ Depois Amazias disse a Amós: Vai-te, ó vidente, foge para a terra de Judá, e ali come o pão, e ali profetiza;

[[v30-7-13]]

^<<v30-7-13,13>>^ mas em Betel daqui por diante não profetizarás mais, porque é o santuário do rei, e é templo do reino.

[[v30-7-14]]

^<<v30-7-14,14>>^ E respondeu Amós, e disse a Amazias: Eu não sou profeta, nem filho de profeta, mas boieiro, e cultivador de sicômoros.

[[v30-7-15]]

^<<v30-7-15,15>>^ Mas o Senhor me tirou de após o gado, e o Senhor me disse: Vai, profetiza ao meu povo Israel.

[[v30-7-16]]

^<<v30-7-16,16>>^ Agora, pois, ouve a palavra do Senhor: Tu dizes: Não profetizes contra Israel, nem fales contra a casa de Isaque.

[[v30-7-17]]

^<<v30-7-17,17>>^ Portanto assim diz o Senhor: Tua mulher se prostituirá na cidade, e teus filhos e tuas filhas cairão à espada, e a tua terra será repartida a cordel; e tu morrerás numa terra imunda, e Israel certamente será levado cativo para fora da sua terra.

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]