include::./index.adoc[]

[[v30-6-0]]
=== Amós, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v30-6-1]]

^<<v30-6-1,1>>^ Ai dos que vivem sossegados em Sião, e dos que estão seguros no monte de Samária, dos homens notáveis da principal das nações, e aos quais vem a casa de Israel!

[[v30-6-2]]

^<<v30-6-2,2>>^ Passai a Calné, e vede; e dali ide à grande Hamate; depois descei a Gate dos filisteus; porventura são melhores que estes reinos? ou são maiores os seus termos do que os vossos termos?

[[v30-6-3]]

^<<v30-6-3,3>>^ ó vós que afastais o dia mau e fazeis que se aproxime o assento da violência.

[[v30-6-4]]

^<<v30-6-4,4>>^ Ai dos que dormem em camas de marfim, e se estendem sobre os seus leitos, e comem os cordeiros tirados do rebanho, e os bezerros do meio do curral;

[[v30-6-5]]

^<<v30-6-5,5>>^ que garganteiam ao som da lira, e inventam para si instrumentos músicos, assim como Davi;

[[v30-6-6]]

^<<v30-6-6,6>>^ que bebem vinho em taças, e se ungem com o mais excelente óleo; mas não se afligem por causa da ruína de José!

[[v30-6-7]]

^<<v30-6-7,7>>^ Portanto agora irão em cativeiro entre os primeiros que forem cativos; e cessarão os festins dos banqueteadores.

[[v30-6-8]]

^<<v30-6-8,8>>^ Jurou o Senhor Deus por si mesmo, diz o Senhor Deus dos exércitos: Abomino a soberba de Jacó, e odeio os seus palácios; por isso entregarei a cidade e tudo o que nela há.

[[v30-6-9]]

^<<v30-6-9,9>>^ E se ficarem de resto dez homens numa casa, morrerão.

[[v30-6-10]]

^<<v30-6-10,10>>^ Quando o parente de alguém, aquele que o queima, o tomar para levar-lhe os ossos para fora da casa, e disser ao que estiver no mais interior da casa: Está ainda alguém contigo? e este responder: Ninguém; então lhe dirá ele: Cala-te, porque não devemos fazer menção do nome do Senhor.

[[v30-6-11]]

^<<v30-6-11,11>>^ Pois eis que o Senhor ordena, e a casa grande será despedaçada, e a casa pequena reduzida a fragmentos.

[[v30-6-12]]

^<<v30-6-12,12>>^ Acaso correrão cavalos pelos rochedos? Lavrar-se-á ali com bois? Mas vós haveis tornado o juízo em fel, e o fruto da justiça em alosna;

[[v30-6-13]]

^<<v30-6-13,13>>^ vós que vos alegrais de nada, vós que dizeis: Não nos temos nós tornado poderosos por nossa própria força?

[[v30-6-14]]

^<<v30-6-14,14>>^ Pois eis que eu levantarei contra vós, ó casa de Israel, uma nação, diz o Senhor Deus dos exércitos, e ela vos oprimirá, desde a entrada de Hamate até o ribeiro da Arabá.

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]