include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-16-1]]

^<<v66-16-1,1>>^ E ouvi, vinda do santuário, uma grande voz, que dizia aos sete anjos: Ide e derramai sobre a terra as sete taças, da ira de Deus.

[[v66-16-2]]

^<<v66-16-2,2>>^ Então foi o primeiro e derramou a sua taça sobre a terra; e apareceu uma chaga ruim e maligna nos homens que tinham o sinal da besta e que adoravam a sua imagem.

[[v66-16-3]]

^<<v66-16-3,3>>^ O segundo anjo derramou a sua taça no mar, que se tornou em sangue como de um morto, e morreu todo ser vivente que estava no mar.

[[v66-16-4]]

^<<v66-16-4,4>>^ O terceiro anjo derramou a sua taça nos rios e nas fontes das águas, e se tornaram em sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ E ouvi o anjo das águas dizer: Justo és tu, que és e que eras, o Santo; porque julgaste estas coisas;

[[v66-16-6]]

^<<v66-16-6,6>>^ porque derramaram o sangue de santos e de profetas, e tu lhes tens dado sangue a beber; eles o merecem.

[[v66-16-7]]

^<<v66-16-7,7>>^ E ouvi uma voz do altar, que dizia: Na verdade, ó Senhor Deus Todo-Poderoso, verdadeiros e justos são os teus juízos.

[[v66-16-8]]

^<<v66-16-8,8>>^ O quarto anjo derramou a sua taça sobre o sol, e foi-lhe permitido que abrasasse os homens com fogo.

[[v66-16-9]]

^<<v66-16-9,9>>^ E os homens foram abrasados com grande calor; e blasfemaram o nome de Deus, que tem poder sobre estas pragas; e não se arrependeram para lhe darem glória.

[[v66-16-10]]

^<<v66-16-10,10>>^ O quinto anjo derramou a sua taça sobre o trono da besta, e o seu reino se fez tenebroso; e os homens mordiam de dor as suas línguas.

[[v66-16-11]]

^<<v66-16-11,11>>^ E por causa das suas dores, e por causa das suas chagas, blasfemaram o Deus do céu; e não se arrependeram das suas obras.

[[v66-16-12]]

^<<v66-16-12,12>>^ O sexto anjo derramou a sua taça sobre o grande rio Eufrates; e a sua água secou-se, para que se preparasse o caminho dos reis que vêm do oriente.

[[v66-16-13]]

^<<v66-16-13,13>>^ E da boca do dragão, e da boca da besta, e da boca do falso profeta, vi saírem três espíritos imundos, semelhantes a rãs.

[[v66-16-14]]

^<<v66-16-14,14>>^ Pois são espíritos de demônios, que operam sinais; os quais vão ao encontro dos reis de todo o mundo, para os congregar para a batalha do grande dia do Deus Todo-Poderoso.

[[v66-16-15]]

^<<v66-16-15,15>>^ &#123;Eis que venho como ladrão. Bem-aventurado aquele que vigia, e guarda as suas vestes, para que não ande nu, e não se veja a sua nudez.&#125;

[[v66-16-16]]

^<<v66-16-16,16>>^ E eles os congregaram no lugar que em hebraico se chama Armagedom.

[[v66-16-17]]

^<<v66-16-17,17>>^ O sétimo anjo derramou a sua taça no ar; e saiu uma grande voz do santuário, da parte do trono, dizendo: Está feito.

[[v66-16-18]]

^<<v66-16-18,18>>^ E houve relâmpagos e vozes e trovões; houve também um grande terremoto, qual nunca houvera desde que há homens sobre a terra, terremoto tão forte quão grande;

[[v66-16-19]]

^<<v66-16-19,19>>^ e a grande cidade fendeu-se em três partes, e as cidades das nações caíram; e Deus lembrou-se da grande Babilônia, para lhe dar o cálice do vinho do furor da sua ira.

[[v66-16-20]]

^<<v66-16-20,20>>^ Todas ilhas fugiram, e os montes não mais se acharam.

[[v66-16-21]]

^<<v66-16-21,21>>^ E sobre os homens caiu do céu uma grande saraivada, pedras quase do peso de um talento; e os homens blasfemaram de Deus por causa da praga da saraivada; porque a sua praga era mui grande.

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]