include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-1-1]]

^<<v66-1-1,1>>^ Revelação de Jesus Cristo, que Deus lhe deu para mostrar aos seus servos as coisas que brevemente devem acontecer; e, enviando-as pelo seu anjo, as notificou a seu servo João;

[[v66-1-2]]

^<<v66-1-2,2>>^ o qual testificou da palavra de Deus, e do testemunho de Jesus Cristo, de tudo quanto viu.

[[v66-1-3]]

^<<v66-1-3,3>>^ Bem-aventurado aquele que lê e bem-aventurados os que ouvem as palavras desta profecia e guardam as coisas que nela estão escritas; porque o tempo está próximo.

[[v66-1-4]]

^<<v66-1-4,4>>^ João, às sete igrejas que estão na Ásia: Graça a vós e paz da parte daquele que é, e que era, e que há de vir, e da dos sete espíritos que estão diante do seu trono;

[[v66-1-5]]

^<<v66-1-5,5>>^ e da parte de Jesus Cristo, que é a fiel testemunha, o primogênito dos mortos e o Príncipe dos reis da terra. Àquele que nos ama, e pelo seu sangue nos libertou dos nossos pecados,

[[v66-1-6]]

^<<v66-1-6,6>>^ e nos fez reino, sacerdotes para Deus, seu Pai, a ele seja glória e domínio pelos séculos dos séculos. Amém.

[[v66-1-7]]

^<<v66-1-7,7>>^ Eis que vem com as nuvens, e todo olho o verá, até mesmo aqueles que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Sim. Amém.

[[v66-1-8]]

^<<v66-1-8,8>>^ Eu sou o Alfa e o Ômega, diz o Senhor Deus, aquele que é, e que era, e que há de vir, o Todo-Poderoso.

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu, João, irmão vosso e companheiro convosco na aflição, no reino, e na perseverança em Jesus, estava na ilha chamada Patmos por causa da palavra de Deus e do testemunho de Jesus.

[[v66-1-10]]

^<<v66-1-10,10>>^ Eu fui arrebatado em espírito no dia do Senhor, e ouvi por detrás de mim uma grande voz, como de trombeta,

[[v66-1-11]]

^<<v66-1-11,11>>^ que dizia: O que vês, escreve-o num livro, e envia-o às sete igrejas: a Éfeso, a Esmirna, a Pérgamo, a Tiatira, a Sardes, a Filadélfia e a Laodicéia.

[[v66-1-12]]

^<<v66-1-12,12>>^ E voltei-me para ver quem falava comigo. E, ao voltar-me, vi sete candeeiros de ouro,

[[v66-1-13]]

^<<v66-1-13,13>>^ e no meio dos candeeiros um semelhante a filho de homem, vestido de uma roupa talar, e cingido à altura do peito com um cinto de ouro;

[[v66-1-14]]

^<<v66-1-14,14>>^ e a sua cabeça e cabelos eram brancos como lã branca, como a neve; e os seus olhos como chama de fogo;

[[v66-1-15]]

^<<v66-1-15,15>>^ e os seus pés, semelhantes a latão reluzente que fora refinado numa fornalha; e a sua voz como a voz de muitas águas.

[[v66-1-16]]

^<<v66-1-16,16>>^ Tinha ele na sua destra sete estrelas; e da sua boca saía uma aguda espada de dois gumes; e o seu rosto era como o sol, quando resplandece na sua força.

[[v66-1-17]]

^<<v66-1-17,17>>^ Quando o vi, caí a seus pés como morto; e ele pôs sobre mim a sua destra, dizendo: Não temas; eu sou o primeiro e o último.

[[v66-1-18]]

^<<v66-1-18,18>>^ Eu sou o que vivo; fui morto, mas eis aqui estou vivo para todo o sempre! e tenho as chaves da morte e do inferno.

[[v66-1-19]]

^<<v66-1-19,19>>^ Escreve, pois, as coisas que tens visto, e as que são, e as que depois destas hão de suceder.

[[v66-1-20]]

^<<v66-1-20,20>>^ Eis o mistério das sete estrelas, que viste na minha destra, e dos sete candeeiros de ouro: as estrelas são os anjos das sete igrejas, e os sete candeeiros são as sete igrejas.

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]