include::./index.adoc[]

[[v66-22-0]]
=== Apocalipse, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-22-1]]

^<<v66-22-1,1>>^ E mostrou-me o rio da água da vida, claro como cristal, que procedia do trono de Deus e do Cordeiro.

[[v66-22-2]]

^<<v66-22-2,2>>^ No meio da sua praça, e de ambos os lados do rio, estava a árvore da vida, que produz doze frutos, dando seu fruto de mês em mês; e as folhas da árvore são para a cura das nações.

[[v66-22-3]]

^<<v66-22-3,3>>^ Ali não haverá jamais maldição. Nela estará o trono de Deus e do Cordeiro, e os seus servos o servirão,

[[v66-22-4]]

^<<v66-22-4,4>>^ e verão a sua face; e nas suas frontes estará o seu nome.

[[v66-22-5]]

^<<v66-22-5,5>>^ E ali não haverá mais noite, e não necessitarão de luz de lâmpada nem de luz do sol, porque o Senhor Deus os alumiará; e reinarão pelos séculos dos séculos.

[[v66-22-6]]

^<<v66-22-6,6>>^ E disse-me: Estas palavras são fiéis e verdadeiras; e o Senhor, o Deus dos espíritos dos profetas, enviou o seu anjo, para mostrar aos seus servos as coisas que em breve hão de acontecer.

[[v66-22-7]]

^<<v66-22-7,7>>^ Eis que cedo venho! Bem-aventurado aquele que guarda as palavras da profecia deste livro.

[[v66-22-8]]

^<<v66-22-8,8>>^ Eu, João, sou o que ouvi e vi estas coisas. E quando as ouvi e vi, prostrei-me aos pés do anjo que mas mostrava, para o adorar.

[[v66-22-9]]

^<<v66-22-9,9>>^ Mas ele me disse: Olha, não faças tal; porque eu sou conservo teu e de teus irmãos, os profetas, e dos que guardam as palavras deste livro. Adora a Deus.

[[v66-22-10]]

^<<v66-22-10,10>>^ Disse-me ainda: Não seles as palavras da profecia deste livro; porque próximo está o tempo.

[[v66-22-11]]

^<<v66-22-11,11>>^ Quem é injusto, faça injustiça ainda: e quem está sujo, suje-se ainda; e quem é justo, faça justiça ainda; e quem é santo, santifique-se ainda.

[[v66-22-12]]

^<<v66-22-12,12>>^ Eis que cedo venho e está comigo a minha recompensa, para retribuir a cada um segundo a sua obra.

[[v66-22-13]]

^<<v66-22-13,13>>^ Eu sou o Alfa e o Ômega, o primeiro e o derradeiro, o princípio e o fim.

[[v66-22-14]]

^<<v66-22-14,14>>^ Bem-aventurados aqueles que lavam as suas vestes &#123;no sangue do Cordeiro&#125; para que tenham direito à arvore da vida, e possam entrar na cidade pelas portas.

[[v66-22-15]]

^<<v66-22-15,15>>^ Ficarão de fora os cães, os feiticeiros, os adúlteros, os homicidas, os idólatras, e todo o que ama e pratica a mentira.

[[v66-22-16]]

^<<v66-22-16,16>>^ Eu, Jesus, enviei o meu anjo para vos testificar estas coisas a favor das igrejas. Eu sou a raiz e a geração de Davi, a resplandecente estrela da manhã.

[[v66-22-17]]

^<<v66-22-17,17>>^ E o Espírito e a noiva dizem: Vem. E quem ouve, diga: Vem. E quem tem sede, venha; e quem quiser, receba de graça a água da vida.

[[v66-22-18]]

^<<v66-22-18,18>>^ Eu testifico a todo aquele que ouvir as palavras da profecia deste livro: Se alguém lhes acrescentar alguma coisa, Deus lhe acrescentará as pragas que estão escritas neste livro;

[[v66-22-19]]

^<<v66-22-19,19>>^ e se alguém tirar qualquer coisa das palavras do livro desta profecia, Deus lhe tirará a sua parte da árvore da vida, e da cidade santa, que estão descritas neste livro.

[[v66-22-20]]

^<<v66-22-20,20>>^ Aquele que testifica estas coisas diz: Certamente cedo venho. Amém; vem, Senhor Jesus.

[[v66-22-21]]

^<<v66-22-21,21>>^ A graça do Senhor Jesus seja com todos.

'''

xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[&#60; Capítulo Anterior] | <<v66-22-0,Topo>> | Próximo Capítulo &#62;