include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-12-1]]

^<<v66-12-1,1>>^ E viu-se um grande sinal no céu: uma mulher vestida do sol, tendo a lua debaixo dos seus pés, e uma coroa de doze estrelas sobre a sua cabeça.

[[v66-12-2]]

^<<v66-12-2,2>>^ E estando grávida, gritava com as dores do parto, sofrendo tormentos para dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ Viu-se também outro sinal no céu: eis um grande dragão vermelho que tinha sete cabeças e dez chifres, e sobre as suas cabeças sete diademas;

[[v66-12-4]]

^<<v66-12-4,4>>^ a sua cauda levava após si a terça parte das estrelas do céu, e lançou-as sobre a terra; e o dragão parou diante da mulher que estava para dar à luz, para que, dando ela à luz, lhe devorasse o filho.

[[v66-12-5]]

^<<v66-12-5,5>>^ E deu à luz um filho, um varão que há de reger todas as nações com vara de ferro; e o seu filho foi arrebatado para Deus e para o seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ E a mulher fugiu para o deserto, onde já tinha lugar preparado por Deus, para que ali fosse alimentada durante mil duzentos e sessenta dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ Então houve guerra no céu: Miguel e os seus anjos batalhavam contra o dragão. E o dragão e os seus anjos batalhavam,

[[v66-12-8]]

^<<v66-12-8,8>>^ mas não prevaleceram, nem mais o seu lugar se achou no céu.

[[v66-12-9]]

^<<v66-12-9,9>>^ E foi precipitado o grande dragão, a antiga serpente, que se chama o Diabo e Satanás, que engana todo o mundo; foi precipitado na terra, e os seus anjos foram precipitados com ele.

[[v66-12-10]]

^<<v66-12-10,10>>^ Então, ouvi uma grande voz no céu, que dizia: Agora é chegada a salvação, e o poder, e o reino do nosso Deus, e a autoridade do seu Cristo; porque já foi lançado fora o acusador de nossos irmãos, o qual diante do nosso Deus os acusava dia e noite.

[[v66-12-11]]

^<<v66-12-11,11>>^ E eles o venceram pelo sangue do Cordeiro e pela palavra do seu testemunho; e não amaram as suas vidas até a morte.

[[v66-12-12]]

^<<v66-12-12,12>>^ Pelo que alegrai-vos, ó céus, e vós que neles habitais. Mas ai da terra e do mar! porque o Diabo desceu a vós com grande ira, sabendo que pouco tempo lhe resta.

[[v66-12-13]]

^<<v66-12-13,13>>^ Quando o dragão se viu precipitado na terra, perseguiu a mulher que dera à luz o filho varão.

[[v66-12-14]]

^<<v66-12-14,14>>^ E foram dadas à mulher as duas asas da grande águia, para que voasse para o deserto, ao seu lugar, onde é sustentada por um tempo, e tempos, e metade de um tempo, fora da vista da serpente.

[[v66-12-15]]

^<<v66-12-15,15>>^ E a serpente lançou da sua boca, atrás da mulher, água como um rio, para fazer que ela fosse arrebatada pela corrente.

[[v66-12-16]]

^<<v66-12-16,16>>^ A terra, porém acudiu à mulher; e a terra abriu a boca, e tragou o rio que o dragão lançara da sua boca.

[[v66-12-17]]

^<<v66-12-17,17>>^ E o dragão irou-se contra a mulher, e foi fazer guerra aos demais filhos dela, os que guardam os mandamentos de Deus, e mantêm o testemunho de Jesus.

[[v66-12-18]]

^<<v66-12-18,18>>^ E o dragão parou sobre a areia do mar.

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]