include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-17-1]]

^<<v66-17-1,1>>^ Veio um dos sete anjos que tinham as sete taças, e falou comigo, dizendo: Vem, mostrar-te-ei a condenação da grande prostituta que está assentada sobre muitas águas;

[[v66-17-2]]

^<<v66-17-2,2>>^ com a qual se prostituíram os reis da terra; e os que habitam sobre a terra se embriagaram com o vinho da sua prostituição.

[[v66-17-3]]

^<<v66-17-3,3>>^ Então ele me levou em espírito a um deserto; e vi uma mulher montada numa besta cor de escarlata, que estava cheia de nomes de blasfêmia, e que tinha sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ A mulher estava vestida de púrpura e de escarlata, e adornada de ouro, pedras preciosas e pérolas; e tinha na mão um cálice de ouro, cheio das abominações, e da imundícia da prostituição;

[[v66-17-5]]

^<<v66-17-5,5>>^ e na sua fronte estava escrito um nome simbólico: A grande Babilônia, a mãe das prostituições e das abominações da terra.

[[v66-17-6]]

^<<v66-17-6,6>>^ E vi que a mulher estava embriagada com o sangue dos santos e com o sangue dos mártires de Jesus. Quando a vi, maravilhei-me com grande admiração.

[[v66-17-7]]

^<<v66-17-7,7>>^ Ao que o anjo me disse: Por que te admiraste? Eu te direi o mistério da mulher, e da besta que a leva, a qual tem sete cabeças e dez chifres.

[[v66-17-8]]

^<<v66-17-8,8>>^ A besta que viste era e já não é; todavia está para subir do abismo, e vai-se para a perdição; e os que habitam sobre a terra e cujos nomes não estão escritos no livro da vida desde a fundação do mundo se admirarão, quando virem a besta que era e já não é, e que tornará a vir.

[[v66-17-9]]

^<<v66-17-9,9>>^ Aqui está a mente que tem sabedoria. As sete cabeças são sete montes, sobre os quais a mulher está assentada;

[[v66-17-10]]

^<<v66-17-10,10>>^ são também sete reis: cinco já caíram; um existe; e o outro ainda não é vindo; e quando vier, deve permanecer pouco tempo.

[[v66-17-11]]

^<<v66-17-11,11>>^ A besta que era e já não é, é também o oitavo rei, e é dos sete, e vai-se para a perdição.

[[v66-17-12]]

^<<v66-17-12,12>>^ Os dez chifres que viste são dez reis, os quais ainda não receberam o reino, mas receberão autoridade, como reis, por uma hora, juntamente com a besta.

[[v66-17-13]]

^<<v66-17-13,13>>^ Estes têm um mesmo intento, e entregarão o seu poder e autoridade à besta.

[[v66-17-14]]

^<<v66-17-14,14>>^ Estes combaterão contra o Cordeiro, e o Cordeiro os vencerá, porque é o Senhor dos senhores e o Rei dos reis; vencerão também os que estão com ele, os chamados, e eleitos, e fiéis.

[[v66-17-15]]

^<<v66-17-15,15>>^ Disse-me ainda: As águas que viste, onde se assenta a prostituta, são povos, multidões, nações e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ E os dez chifres que viste, e a besta, estes odiarão a prostituta e a tornarão desolada e nua, e comerão as suas carnes, e a queimarão no fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Porque Deus lhes pôs nos corações o executarem o intento dele, chegarem a um acordo, e entregarem à besta o seu reino, até que se cumpram as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ E a mulher que viste é a grande cidade que reina sobre os reis da terra.

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]