include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-18-1]]

^<<v66-18-1,1>>^ Depois destas coisas vi descer do céu outro anjo que tinha grande autoridade, e a terra foi iluminada com a sua glória.

[[v66-18-2]]

^<<v66-18-2,2>>^ E ele clamou com voz forte, dizendo: Caiu, caiu a grande Babilônia, e se tornou morada de demônios, e guarida de todo espírito imundo, e guarida de toda ave imunda e detestável.

[[v66-18-3]]

^<<v66-18-3,3>>^ Porque todas as nações têm bebido do vinho da ira da sua prostituição, e os reis da terra se prostituíram com ela; e os mercadores da terra se enriqueceram com a abundância de suas delícias.

[[v66-18-4]]

^<<v66-18-4,4>>^ Ouvi outra voz do céu dizer: Sai dela, povo meu, para que não sejas participante dos sete pecados, e para que não incorras nas suas pragas.

[[v66-18-5]]

^<<v66-18-5,5>>^ Porque os seus pecados se acumularam até o céu, e Deus se lembrou das iniqüidades dela.

[[v66-18-6]]

^<<v66-18-6,6>>^ Tornai a dar-lhe como também ela vos tem dado, e retribuí-lhe em dobro conforme as suas obras; no cálice em que vos deu de beber dai-lhe a ela em dobro.

[[v66-18-7]]

^<<v66-18-7,7>>^ Quanto ela se glorificou, e em delícias esteve, tanto lhe dai de tormento e de pranto; pois que ela diz em seu coração: Estou assentada como rainha, e não sou viúva, e de modo algum verei o pranto.

[[v66-18-8]]

^<<v66-18-8,8>>^ Por isso, num mesmo dia virão as suas pragas, a morte, e o pranto, e a fome; e será consumida no fogo; porque forte é o Senhor Deus que a julga.

[[v66-18-9]]

^<<v66-18-9,9>>^ E os reis da terra, que com ela se prostituíram e viveram em delícias, sobre ela chorarão e prantearão, quando virem a fumaça do seu incêndio;

[[v66-18-10]]

^<<v66-18-10,10>>^ e, estando de longe por medo do tormento dela, dirão: Ai! ai da grande cidade, Babilônia, a cidade forte! pois numa só hora veio o teu julgamento.

[[v66-18-11]]

^<<v66-18-11,11>>^ E sobre ela choram e lamentam os mercadores da terra; porque ninguém compra mais as suas mercadorias:

[[v66-18-12]]

^<<v66-18-12,12>>^ mercadorias de ouro, de prata, de pedras preciosas, de pérolas, de linho fino, de púrpura, de seda e de escarlata; e toda espécie de madeira odorífera, e todo objeto de marfim, de madeira preciosíssima, de bronze, de ferro e de mármore;

[[v66-18-13]]

^<<v66-18-13,13>>^ e canela, especiarias, perfume, mirra e incenso; e vinho, azeite, flor de farinha e trigo; e gado, ovelhas, cavalos e carros; e escravos, e até almas de homens.

[[v66-18-14]]

^<<v66-18-14,14>>^ Também os frutos que a tua alma cobiçava foram-se de ti; e todas as coisas delicadas e suntuosas se foram de ti, e nunca mais se acharão.

[[v66-18-15]]

^<<v66-18-15,15>>^ Os mercadores destas coisas, que por ela se enriqueceram, ficarão de longe por medo do tormento dela, chorando e lamentando,

[[v66-18-16]]

^<<v66-18-16,16>>^ dizendo: Ai! ai da grande cidade, da que estava vestida de linho fino, de púrpura, de escarlata, e adornada com ouro, e pedras preciosas, e pérolas! porque numa só hora foram assoladas tantas riquezas.

[[v66-18-17]]

^<<v66-18-17,17>>^ E todo piloto, e todo o que navega para qualquer porto e todos os marinheiros, e todos os que trabalham no mar se puseram de longe;

[[v66-18-18]]

^<<v66-18-18,18>>^ e, contemplando a fumaça do incêndio dela, clamavam: Que cidade é semelhante a esta grande cidade?

[[v66-18-19]]

^<<v66-18-19,19>>^ E lançaram pó sobre as suas cabeças, e clamavam, chorando e lamentando, dizendo: Ai! ai da grande cidade, na qual todos os que tinham naus no mar se enriqueceram em razão da sua opulência! porque numa só hora foi assolada.

[[v66-18-20]]

^<<v66-18-20,20>>^ Exulta sobre ela, ó céu, e vós, santos e apóstolos e profetas; porque Deus vindicou a vossa causa contra ela.

[[v66-18-21]]

^<<v66-18-21,21>>^ Um forte anjo levantou uma pedra, qual uma grande mó, e lançou-a no mar, dizendo: Com igual ímpeto será lançada Babilônia, a grande cidade, e nunca mais será achada.

[[v66-18-22]]

^<<v66-18-22,22>>^ E em ti não se ouvirá mais o som de harpistas, de músicos, de flautistas e de trombeteiros; e nenhum artífice de arte alguma se achará mais em ti; e em ti não mais se ouvirá ruído de mó;

[[v66-18-23]]

^<<v66-18-23,23>>^ e luz de candeia não mais brilhará em ti, e voz de noivo e de noiva não mais em ti se ouvirá; porque os teus mercadores eram os grandes da terra; porque todas as nações foram enganadas pelas tuas feitiçarias.

[[v66-18-24]]

^<<v66-18-24,24>>^ E nela se achou o sangue dos profetas, e dos santos, e de todos os que foram mortos na terra.

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]