include::./index.adoc[]

[[v66-11-0]]
=== Apocalipse, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-11-1]]

^<<v66-11-1,1>>^ Foi-me dada uma cana semelhante a uma vara; e foi-me dito: Levanta-te, mede o santuário de Deus, e o altar, e os que nele adoram.

[[v66-11-2]]

^<<v66-11-2,2>>^ Mas deixa o átrio que está fora do santuário, e não o meças; porque foi dado aos gentios; e eles pisarão a cidade santa por quarenta e dois meses.

[[v66-11-3]]

^<<v66-11-3,3>>^ E concederei às minhas duas testemunhas que, vestidas de saco, profetizem por mil duzentos e sessenta dias.

[[v66-11-4]]

^<<v66-11-4,4>>^ Estas são as duas oliveiras e os dois candeeiros que estão diante do Senhor da terra.

[[v66-11-5]]

^<<v66-11-5,5>>^ E, se alguém lhes quiser fazer mal, das suas bocas sairá fogo e devorará os seus inimigos; pois se alguém lhes quiser fazer mal, importa que assim seja morto.

[[v66-11-6]]

^<<v66-11-6,6>>^ Elas têm poder para fechar o céu, para que não chova durante os dias da sua profecia; e têm poder sobre as águas para convertê-las em sangue, e para ferir a terra com toda sorte de pragas, quantas vezes quiserem.

[[v66-11-7]]

^<<v66-11-7,7>>^ E, quando acabarem o seu testemunho, a besta que sobe do abismo lhes fará guerra e as vencerá e matará.

[[v66-11-8]]

^<<v66-11-8,8>>^ E jazerão os seus corpos na praça da grande cidade, que espiritualmente se chama Sodoma e Egito, onde também o seu Senhor foi crucificado.

[[v66-11-9]]

^<<v66-11-9,9>>^ Homens de vários povos, e tribos e línguas, e nações verão os seus corpos por três dias e meio, e não permitirão que sejam sepultados.

[[v66-11-10]]

^<<v66-11-10,10>>^ E os que habitam sobre a terra se regozijarão sobre eles, e se alegrarão; e mandarão presentes uns aos outros, porquanto estes dois profetas atormentaram os que habitam sobre a terra.

[[v66-11-11]]

^<<v66-11-11,11>>^ E depois daqueles três dias e meio o espírito de vida, vindo de Deus, entrou neles, e puseram-se sobre seus pés, e caiu grande temor sobre os que os viram.

[[v66-11-12]]

^<<v66-11-12,12>>^ E ouviram uma grande voz do céu, que lhes dizia: Subi para cá. E subiram ao céu em uma nuvem; e os seus inimigos os viram.

[[v66-11-13]]

^<<v66-11-13,13>>^ E naquela hora houve um grande terremoto, e caiu a décima parte da cidade, e no terremoto foram mortos sete mil homens; e os demais ficaram atemorizados, e deram glória ao Deus do céu.

[[v66-11-14]]

^<<v66-11-14,14>>^ É passado o segundo ai; eis que cedo vem o terceiro.

[[v66-11-15]]

^<<v66-11-15,15>>^ E tocou o sétimo anjo a sua trombeta, e houve no céu grandes vozes, que diziam: O reino do mundo passou a ser de nosso Senhor e do seu Cristo, e ele reinará pelos séculos dos séculos.

[[v66-11-16]]

^<<v66-11-16,16>>^ E os vinte e quatro anciãos, que estão assentados em seus tronos diante de Deus, prostraram-se sobre seus rostos e adoraram a Deus,

[[v66-11-17]]

^<<v66-11-17,17>>^ dizendo: Graças te damos, Senhor Deus Todo-Poderoso, que és, e que eras, porque tens tomado o teu grande poder, e começaste a reinar.

[[v66-11-18]]

^<<v66-11-18,18>>^ Iraram-se, na verdade, as nações; então veio a tua ira, e o tempo de serem julgados os mortos, e o tempo de dares recompensa aos teus servos, os profetas, e aos santos, e aos que temem o teu nome, a pequenos e a grandes, e o tempo de destruíres os que destroem a terra.

[[v66-11-19]]

^<<v66-11-19,19>>^ Abriu-se o santuário de Deus que está no céu, e no seu santuário foi vista a arca do seu pacto; e houve relâmpagos, vozes e trovões, e terremoto e grande saraivada.

'''

xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[Próximo Capítulo &#62;]