include::./index.adoc[]

[[v66-8-0]]
=== Apocalipse, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-8-1]]

^<<v66-8-1,1>>^ Quando abriu o sétimo selo, fez-se silêncio no céu, quase por meia hora.

[[v66-8-2]]

^<<v66-8-2,2>>^ E vi os sete anjos que estavam em pé diante de Deus, e lhes foram dadas sete trombetas.

[[v66-8-3]]

^<<v66-8-3,3>>^ Veio outro anjo, e pôs-se junto ao altar, tendo um incensário de ouro; e foi-lhe dado muito incenso, para que o oferecesse com as orações de todos os santos sobre o altar de ouro que está diante do trono.

[[v66-8-4]]

^<<v66-8-4,4>>^ E da mão do anjo subiu diante de Deus a fumaça do incenso com as orações dos santos.

[[v66-8-5]]

^<<v66-8-5,5>>^ Depois do anjo tomou o incensário, encheu-o do fogo do altar e o lançou sobre a terra; e houve trovões, vozes, relâmpagos e terremoto.

[[v66-8-6]]

^<<v66-8-6,6>>^ Então os sete anjos que tinham as sete trombetas prepararam-se para tocar.

[[v66-8-7]]

^<<v66-8-7,7>>^ O primeiro anjo tocou a sua trombeta, e houve saraiva e fogo misturado com sangue, que foram lançados na terra; e foi queimada a terça parte da terra, a terça parte das árvores, e toda a erva verde.

[[v66-8-8]]

^<<v66-8-8,8>>^ O segundo anjo tocou a sua trombeta, e foi lançado no mar como que um grande monte ardendo em fogo, e tornou-se em sangue a terça parte do mar.

[[v66-8-9]]

^<<v66-8-9,9>>^ E morreu a terça parte das criaturas viventes que havia no mar, e foi destruída a terça parte dos navios.

[[v66-8-10]]

^<<v66-8-10,10>>^ O terceiro anjo tocou a sua trombeta, e caiu do céu uma grande estrela, ardendo como uma tocha, e caiu sobre a terça parte dos rios, e sobre as fontes das águas.

[[v66-8-11]]

^<<v66-8-11,11>>^ O nome da estrela era Absinto; e a terça parte das águas tornou-se em absinto, e muitos homens morreram das águas, porque se tornaram amargas.

[[v66-8-12]]

^<<v66-8-12,12>>^ O quarto anjo tocou a sua trombeta, e foi ferida a terça parte do sol, a terça parte da lua, e a terça parte das estrelas; para que a terça parte deles se escurecesse, e a terça parte do dia não brilhante, e semelhantemente a da noite.

[[v66-8-13]]

^<<v66-8-13,13>>^ E olhei, e ouvi uma águia que, voando pelo meio do céu, dizia com grande voz: Ai, ai, ai dos que habitam sobre a terra! por causa dos outros toques de trombeta dos três anjos que ainda vão tocar.

'''

xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[&#60; Capítulo Anterior] | <<v66-8-0,Topo>> | xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[Próximo Capítulo &#62;]