include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-3-1]]

^<<v66-3-1,1>>^ Ao anjo da igreja em Sardes escreve: Isto diz aquele que tem os sete espíritos de Deus, e as estrelas: Conheço as tuas obras; tens nome de que vives, e estás morto.

[[v66-3-2]]

^<<v66-3-2,2>>^ Sê vigilante, e confirma o restante, que estava para morrer; porque não tenho achado as tuas obras perfeitas diante do meu Deus.

[[v66-3-3]]

^<<v66-3-3,3>>^ Lembra-te, portanto, do que tens recebido e ouvido, e guarda-o, e arrepende-te. Pois se não vigiares, virei como um ladrão, e não saberás a que hora sobre ti virei.

[[v66-3-4]]

^<<v66-3-4,4>>^ Mas também tens em Sardes algumas pessoas que não contaminaram as suas vestes e comigo andarão vestidas de branco, porquanto são dignas.

[[v66-3-5]]

^<<v66-3-5,5>>^ O que vencer será assim vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; antes confessarei o seu nome diante de meu Pai e diante dos seus anjos.

[[v66-3-6]]

^<<v66-3-6,6>>^ Quem tem ouvidos, ouça o que o espírito diz às igrejas.

[[v66-3-7]]

^<<v66-3-7,7>>^ Ao anjo da igreja em Filadélfia escreve: Isto diz o que é santo, o que é verdadeiro, o que tem a chave de Davi; o que abre, e ninguém fecha; e fecha, e ninguém abre:

[[v66-3-8]]

^<<v66-3-8,8>>^ Conheço as tuas obras &#123;eis que tenho posto diante de ti uma porta aberta, que ninguém pode fechar&#125;, que tens pouca força, entretanto guardaste a minha palavra e não negaste o meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Eis que farei aos da sinagoga de Satanás, aos que se dizem judeus, e não o são, mas mentem, eis que farei que venham, e adorem prostrados aos teus pés, e saibam que eu te amo.

[[v66-3-10]]

^<<v66-3-10,10>>^ Porquanto guardaste a palavra da minha perseverança, também eu te guardarei da hora da provação que há de vir sobre o mundo inteiro, para pôr à prova os que habitam sobre a terra.

[[v66-3-11]]

^<<v66-3-11,11>>^ Venho sem demora; guarda o que tens, para que ninguém tome a tua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ A quem vencer, eu o farei coluna no templo do meu Deus, donde jamais sairá; e escreverei sobre ele o nome do meu Deus, e o nome da cidade do meu Deus, a nova Jerusalém, que desce do céu, da parte do meu Deus, e também o meu novo nome.

[[v66-3-13]]

^<<v66-3-13,13>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

[[v66-3-14]]

^<<v66-3-14,14>>^ Ao anjo da igreja em Laodicéia escreve: Isto diz o Amém, a testemunha fiel e verdadeira, o princípio da criação de Deus:

[[v66-3-15]]

^<<v66-3-15,15>>^ Conheço as tuas obras, que nem és frio nem quente; oxalá foras frio ou quente!

[[v66-3-16]]

^<<v66-3-16,16>>^ Assim, porque és morno, e não és quente nem frio, vomitar-te-ei da minha boca.

[[v66-3-17]]

^<<v66-3-17,17>>^ Porquanto dizes: Rico sou, e estou enriquecido, e de nada tenho falta; e não sabes que és um coitado, e miserável, e pobre, e cego, e nu;

[[v66-3-18]]

^<<v66-3-18,18>>^ aconselho-te que de mim compres ouro refinado no fogo, para que te enriqueças; e vestes brancas, para que te vistas, e não seja manifesta a vergonha da tua nudez; e colírio, a fim de ungires os teus olhos, para que vejas.

[[v66-3-19]]

^<<v66-3-19,19>>^ Eu repreendo e castigo a todos quantos amo: sê pois zeloso, e arrepende-te.

[[v66-3-20]]

^<<v66-3-20,20>>^ Eis que estou à porta e bato; se alguém ouvir a minha voz, e abrir a porta, entrarei em sua casa, e com ele cearei, e ele comigo.

[[v66-3-21]]

^<<v66-3-21,21>>^ Ao que vencer, eu lhe concederei que se assente comigo no meu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]