include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-5-1]]

^<<v66-5-1,1>>^ Vi na destra do que estava assentado sobre o trono um livro escrito por dentro e por fora, bem selado com sete selos.

[[v66-5-2]]

^<<v66-5-2,2>>^ Vi também um anjo forte, clamando com grande voz: Quem é digno de abrir o livro e de romper os seus selos?

[[v66-5-3]]

^<<v66-5-3,3>>^ E ninguém no céu, nem na terra, nem debaixo da terra, podia abrir o livro, nem olhar para ele.

[[v66-5-4]]

^<<v66-5-4,4>>^ E eu chorava muito, porque não fora achado ninguém digno de abrir o livro nem de olhar para ele.

[[v66-5-5]]

^<<v66-5-5,5>>^ E disse-me um dentre os anciãos: Não chores; eis que o Leão da tribo de Judá, a raiz de Davi, venceu para abrir o livro e romper os sete selos.

[[v66-5-6]]

^<<v66-5-6,6>>^ Nisto vi, entre o trono e os quatro seres viventes, no meio dos anciãos, um Cordeiro em pé, como havendo sido morto, e tinha sete chifres e sete olhos, que são os sete espíritos de Deus, enviados por toda a terra.

[[v66-5-7]]

^<<v66-5-7,7>>^ E veio e tomou o livro da destra do que estava assentado sobre o trono.

[[v66-5-8]]

^<<v66-5-8,8>>^ Logo que tomou o livro, os quatro seres viventes e os vinte e quatro anciãos prostraram-se diante do Cordeiro, tendo cada um deles uma harpa e taças de ouro cheias de incenso, que são as orações dos santos.

[[v66-5-9]]

^<<v66-5-9,9>>^ E cantavam um cântico novo, dizendo: Digno és de tomar o livro, e de abrir os seus selos; porque foste morto, e com o teu sangue compraste para Deus homens de toda tribo, e língua, e povo e nação;

[[v66-5-10]]

^<<v66-5-10,10>>^ e para o nosso Deus os fizeste reino, e sacerdotes; e eles reinarão sobre a terra.

[[v66-5-11]]

^<<v66-5-11,11>>^ E olhei, e vi a voz de muitos anjos ao redor do trono e dos seres viventes e dos anciãos; e o número deles era miríades de miríades; e o número deles era miríades de miríades e milhares de milhares,

[[v66-5-12]]

^<<v66-5-12,12>>^ que com grande voz diziam: Digno é o Cordeiro, que foi morto, de receber o poder, e riqueza, e sabedoria, e força, e honra, e glória, e louvor.

[[v66-5-13]]

^<<v66-5-13,13>>^ Ouvi também a toda criatura que está no céu, e na terra, e debaixo da terra, e no mar, e a todas as coisas que neles há, dizerem: Ao que está assentado sobre o trono, e ao Cordeiro, seja o louvor, e a honra, e a glória, e o domínio pelos séculos dos séculos:

[[v66-5-14]]

^<<v66-5-14,14>>^ e os quatro seres viventes diziam: Amém. E os anciãos prostraram-se e adoraram.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]