include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-20-1]]

^<<v66-20-1,1>>^ E vi descer do céu um anjo, que tinha a chave do abismo e uma grande cadeia na sua mão.

[[v66-20-2]]

^<<v66-20-2,2>>^ Ele prendeu o dragão, a antiga serpente, que é o Diabo e Satanás, e o amarrou por mil anos.

[[v66-20-3]]

^<<v66-20-3,3>>^ Lançou-o no abismo, o qual fechou e selou sobre ele, para que não enganasse mais as nações até que os mil anos se completassem. Depois disto é necessário que ele seja solto por um pouco de tempo.

[[v66-20-4]]

^<<v66-20-4,4>>^ Então vi uns tronos; e aos que se assentaram sobre eles foi dado o poder de julgar; e vi as almas daqueles que foram degolados por causa do testemunho de Jesus e da palavra de Deus, e que não adoraram a besta nem a sua imagem, e não receberam o sinal na fronte nem nas mãos; e reviveram, e reinaram com Cristo durante mil anos.

[[v66-20-5]]

^<<v66-20-5,5>>^ Mas os outros mortos não reviveram, até que os mil anos se completassem. Esta é a primeira ressurreição.

[[v66-20-6]]

^<<v66-20-6,6>>^ Bem-aventurado e santo é aquele que tem parte na primeira ressurreição; sobre estes não tem poder a segunda morte; mas serão sacerdotes de Deus e de Cristo, e reinarão com ele durante os mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ Ora, quando se completarem os mil anos, Satanás será solto da sua prisão,

[[v66-20-8]]

^<<v66-20-8,8>>^ e sairá a enganar as nações que estão nos quatro cantos da terra, Gogue e Magogue, cujo número é como a areia do mar, a fim de ajuntá-las para a batalha.

[[v66-20-9]]

^<<v66-20-9,9>>^ E subiram sobre a largura da terra, e cercaram o arraial dos santos e a cidade querida; mas desceu fogo do céu, e os devorou;

[[v66-20-10]]

^<<v66-20-10,10>>^ e o Diabo, que os enganava, foi lançado no lago de fogo e enxofre, onde estão a besta e o falso profeta; e de dia e de noite serão atormentados pelos séculos dos séculos.

[[v66-20-11]]

^<<v66-20-11,11>>^ E vi um grande trono branco e o que estava assentado sobre ele, de cuja presença fugiram a terra e o céu; e não foi achado lugar para eles.

[[v66-20-12]]

^<<v66-20-12,12>>^ E vi os mortos, grandes e pequenos, em pé diante do trono; e abriram-se uns livros; e abriu-se outro livro, que é o da vida; e os mortos foram julgados pelas coisas que estavam escritas nos livros, segundo as suas obras.

[[v66-20-13]]

^<<v66-20-13,13>>^ O mar entregou os mortos que nele havia; e a morte e o além entregaram os mortos que neles havia; e foram julgados, cada um segundo as suas obras.

[[v66-20-14]]

^<<v66-20-14,14>>^ E a morte e o inferno foram lançados no lago de fogo. Esta é a segunda morte, o lago de fogo.

[[v66-20-15]]

^<<v66-20-15,15>>^ E todo aquele que não foi achado inscrito no livro da vida, foi lançado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]