include::./index.adoc[]

[[v66-10-0]]
=== Apocalipse, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-10-1]]

^<<v66-10-1,1>>^ E vi outro anjo forte que descia do céu, vestido de uma nuvem; por cima da sua cabeça estava o arco-íris; o seu rosto era como o sol, e os seus pés como colunas de fogo,

[[v66-10-2]]

^<<v66-10-2,2>>^ e tinha na mão um livrinho aberto. Pôs o seu pé direito sobre o mar, e o esquerdo sobre a terra,

[[v66-10-3]]

^<<v66-10-3,3>>^ e clamou com grande voz, assim como ruge o leão; e quando clamou, os sete trovões fizeram soar as suas vozes.

[[v66-10-4]]

^<<v66-10-4,4>>^ Quando os sete trovões acabaram de soar eu já ia escrever, mas ouvi uma voz do céu, que dizia: Sela o que os sete trovões falaram, e não o escrevas.

[[v66-10-5]]

^<<v66-10-5,5>>^ O anjo que vi em pé sobre o mar e sobre a terra levantou a mão direita ao céu,

[[v66-10-6]]

^<<v66-10-6,6>>^ e jurou por aquele que vive pelos séculos dos séculos, o qual criou o céu e o que nele há, e a terra e o que nela há, e o mar e o que nele há, que não haveria mais demora,

[[v66-10-7]]

^<<v66-10-7,7>>^ mas que nos dias da voz do sétimo anjo, quando este estivesse para tocar a trombeta, se cumpriria o mistério de Deus, como anunciou aos seus servos, os profetas.

[[v66-10-8]]

^<<v66-10-8,8>>^ A voz que eu do céu tinha ouvido tornou a falar comigo, e disse: Vai, e toma o livro que está aberto na mão do anjo que se acha em pé sobre o mar e sobre a terra.

[[v66-10-9]]

^<<v66-10-9,9>>^ E fui ter com o anjo e lhe pedi que me desse o livrinho. Disse-me ele: Toma-o, e come-o; ele fará amargo o teu ventre, mas na tua boca será doce como mel.

[[v66-10-10]]

^<<v66-10-10,10>>^ Tomei o livrinho da mão do anjo, e o comi; e na minha boca era doce como mel; mas depois que o comi, o meu ventre ficou amargo.

[[v66-10-11]]

^<<v66-10-11,11>>^ Então me disseram: Importa que profetizes outra vez a muitos povos, e nações, e línguas, e reis.

'''

xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[Próximo Capítulo &#62;]