include::./index.adoc[]

[[v66-15-0]]
=== Apocalipse, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-15-1]]

^<<v66-15-1,1>>^ Vi no céu ainda outro sinal, grande e admirável: sete anjos, que tinham as sete últimas pragas; porque nelas é consumada a ira de Deus.

[[v66-15-2]]

^<<v66-15-2,2>>^ E vi como que um mar de vidro misturado com fogo; e os que tinham vencido a besta e a sua imagem e o número do seu nome estavam em pé junto ao mar de vidro, e tinham harpas de Deus.

[[v66-15-3]]

^<<v66-15-3,3>>^ E cantavam o cântico de Moisés, servo de Deus, e o cântico do Cordeiro, dizendo: Grandes e admiráveis são as tuas obras, ó Senhor Deus Todo-Poderoso; justos e verdadeiros são os teus caminhos, ó Rei dos séculos.

[[v66-15-4]]

^<<v66-15-4,4>>^ Quem não te temerá, Senhor, e não glorificará o teu nome? Pois só tu és santo; por isso todas as nações virão e se prostrarão diante de ti, porque os teus juízos são manifestos.

[[v66-15-5]]

^<<v66-15-5,5>>^ Depois disto olhei, e abriu-se o santuário do tabernáculo do testemunho no céu;

[[v66-15-6]]

^<<v66-15-6,6>>^ e saíram do santuário os sete anjos que tinham as sete pragas, vestidos de linho puro e resplandecente, e cingidos, à altura do peito com cintos de ouro.

[[v66-15-7]]

^<<v66-15-7,7>>^ Um dos quatro seres viventes deu aos sete anjos sete taças de ouro, cheias da ira do Deus que vive pelos séculos dos séculos.

[[v66-15-8]]

^<<v66-15-8,8>>^ E o santuário se encheu de fumaça pela glória de Deus e pelo seu poder; e ninguém podia entrar no santuário, enquanto não se consumassem as sete pragas dos sete anjos.

'''

xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[&#60; Capítulo Anterior] | <<v66-15-0,Topo>> | xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[Próximo Capítulo &#62;]