include::./index.adoc[]

[[v66-9-0]]
=== Apocalipse, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-9-1]]

^<<v66-9-1,1>>^ O quinto anjo tocou a sua trombeta, e vi uma estrela que do céu caíra sobre a terra; e foi-lhe dada a chave do poço do abismo.

[[v66-9-2]]

^<<v66-9-2,2>>^ E abriu o poço do abismo, e subiu fumaça do poço, como fumaça de uma grande fornalha; e com a fumaça do poço escureceram-se o sol e o ar.

[[v66-9-3]]

^<<v66-9-3,3>>^ Da fumaça saíram gafanhotos sobre a terra; e foi-lhes dado poder, como o que têm os escorpiões da terra.

[[v66-9-4]]

^<<v66-9-4,4>>^ Foi-lhes dito que não fizessem dano à erva da terra, nem a verdura alguma, nem a árvore alguma, mas somente aos homens que não têm na fronte o selo de Deus.

[[v66-9-5]]

^<<v66-9-5,5>>^ Foi-lhes permitido, não que os matassem, mas que por cinco meses os atormentassem. E o seu tormento era semelhante ao tormento do escorpião, quando fere o homem.

[[v66-9-6]]

^<<v66-9-6,6>>^ Naqueles dias os homens buscarão a morte, e de modo algum a acharão; e desejarão morrer, e a morte fugirá deles.

[[v66-9-7]]

^<<v66-9-7,7>>^ A aparência dos gafanhotos era semelhante à de cavalos aparelhados para a guerra; e sobre as suas cabeças havia como que umas coroas semelhantes ao ouro; e os seus rostos eram como rostos de homens.

[[v66-9-8]]

^<<v66-9-8,8>>^ Tinham cabelos como cabelos de mulheres, e os seus dentes eram como os de leões.

[[v66-9-9]]

^<<v66-9-9,9>>^ Tinham couraças como couraças de ferro; e o ruído das suas asas era como o ruído de carros de muitos cavalos que correm ao combate.

[[v66-9-10]]

^<<v66-9-10,10>>^ Tinham caudas com ferrões, semelhantes às caudas dos escorpiões; e nas suas caudas estava o seu poder para fazer dano aos homens por cinco meses.

[[v66-9-11]]

^<<v66-9-11,11>>^ Tinham sobre si como rei o anjo do abismo, cujo nome em hebraico é Abadom e em grego Apoliom.

[[v66-9-12]]

^<<v66-9-12,12>>^ Passado é já um ai; eis que depois disso vêm ainda dois ais.

[[v66-9-13]]

^<<v66-9-13,13>>^ O sexto anjo tocou a sua trombeta; e ouvi uma voz que vinha das quatro pontas do altar de ouro que estava diante de Deus,

[[v66-9-14]]

^<<v66-9-14,14>>^ a qual dizia ao sexto anjo, que tinha a trombeta: Solta os quatro anjos que se acham presos junto do grande rio Eufrates.

[[v66-9-15]]

^<<v66-9-15,15>>^ E foram soltos os quatro anjos que haviam sido preparados para aquela hora e dia e mês e ano, a fim de matarem a terça parte dos homens.

[[v66-9-16]]

^<<v66-9-16,16>>^ O número dos exércitos dos cavaleiros era de duas miríades de miríades; pois ouvi o número deles.

[[v66-9-17]]

^<<v66-9-17,17>>^ E assim vi os cavalos nesta visão: os que sobre eles estavam montados tinham couraças de fogo, e de jacinto, e de enxofre; e as cabeças dos cavalos eram como cabeças de leões; e de suas bocas saíam fogo, fumaça e enxofre.

[[v66-9-18]]

^<<v66-9-18,18>>^ Por estas três pragas foi morta a terça parte dos homens, isto é, pelo fogo, pela fumaça e pelo enxofre, que saíam das suas bocas.

[[v66-9-19]]

^<<v66-9-19,19>>^ Porque o poder dos cavalos estava nas suas bocas e nas suas caudas. Porquanto as suas caudas eram semelhantes a serpentes, e tinham cabeças, e com elas causavam dano.

[[v66-9-20]]

^<<v66-9-20,20>>^ Os outros homens, que não foram mortos por estas pragas, não se arrependeram das obras das suas mãos, para deixarem de adorar aos demônios, e aos ídolos de ouro, de prata, de bronze, de pedra e de madeira, que nem podem ver, nem ouvir, nem andar.

[[v66-9-21]]

^<<v66-9-21,21>>^ Também não se arrependeram dos seus homicídios, nem das suas feitiçarias, nem da sua prostituição, nem dos seus furtos.

'''

xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[Próximo Capítulo &#62;]