include::./index.adoc[]

[[v66-4-0]]
=== Apocalipse, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v66-4-1]]

^<<v66-4-1,1>>^ Depois destas coisas, olhei, e eis que estava uma porta aberta no céu, e a primeira voz que ouvira, voz como de trombeta, falando comigo, disse: Sobe aqui, e mostrar-te-ei as coisas que depois destas devem acontecer.

[[v66-4-2]]

^<<v66-4-2,2>>^ Imediatamente fui arrebatado em espírito, e eis que um trono estava posto no céu, e um assentado sobre o trono;

[[v66-4-3]]

^<<v66-4-3,3>>^ e aquele que estava assentado era, na aparência, semelhante a uma pedra de jaspe e sárdio; e havia ao redor do trono um arco-íris semelhante, na aparência, à esmeralda.

[[v66-4-4]]

^<<v66-4-4,4>>^ Havia também ao redor do trono vinte e quatro tronos; e sobre os tronos vi assentados vinte e quatro anciãos, vestidos de branco, que tinham nas suas cabeças coroas de ouro.

[[v66-4-5]]

^<<v66-4-5,5>>^ E do trono saíam relâmpagos, e vozes, e trovões; e diante do trono ardiam sete lâmpadas de fogo, as quais são os sete espíritos de Deus;

[[v66-4-6]]

^<<v66-4-6,6>>^ também havia diante do trono como que um mar de vidro, semelhante ao cristal; e ao redor do trono, um ao meio de cada lado, quatro seres viventes cheios de olhos por diante e por detrás;

[[v66-4-7]]

^<<v66-4-7,7>>^ e o primeiro ser era semelhante a um leão; o segundo ser, semelhante a um touro; tinha o terceiro ser o rosto como de homem; e o quarto ser era semelhante a uma águia voando.

[[v66-4-8]]

^<<v66-4-8,8>>^ Os quatro seres viventes tinham, cada um, seis asas, e ao redor e por dentro estavam cheios de olhos; e não têm descanso nem de noite, dizendo: Santo, Santo, Santo é o Senhor Deus, o Todo-Poderoso, aquele que era, e que é, e que há de vir.

[[v66-4-9]]

^<<v66-4-9,9>>^ E, sempre que os seres viventes davam glória e honra e ações de graças ao que estava assentado sobre o trono, ao que vive pelos séculos dos séculos,

[[v66-4-10]]

^<<v66-4-10,10>>^ os vinte e quatro anciãos prostravam-se diante do que estava assentado sobre o trono, e adoravam ao que vive pelos séculos dos séculos; e lançavam as suas coroas diante do trono, dizendo:

[[v66-4-11]]

^<<v66-4-11,11>>^ Digno és, Senhor nosso e Deus nosso, de receber a glória e a honra e o poder; porque tu criaste todas as coisas, e por tua vontade existiram e foram criadas.

'''

xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[Próximo Capítulo &#62;]