include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-14-1]]

^<<v46-14-1,1>>^ Segui o amor; e procurai com zelo os dons espirituais, mas principalmente o de profetizar.

[[v46-14-2]]

^<<v46-14-2,2>>^ Porque o que fala em língua não fala aos homens, mas a Deus; pois ninguém o entende; porque em espírito fala mistérios.

[[v46-14-3]]

^<<v46-14-3,3>>^ Mas o que profetiza fala aos homens para edificação, exortação e consolação.

[[v46-14-4]]

^<<v46-14-4,4>>^ O que fala em língua edifica-se a si mesmo, mas o que profetiza edifica a igreja.

[[v46-14-5]]

^<<v46-14-5,5>>^ Ora, quero que todos vós faleis em línguas, mas muito mais que profetizeis, pois quem profetiza é maior do que aquele que fala em línguas, a não ser que também intercede para que a igreja receba edificação.

[[v46-14-6]]

^<<v46-14-6,6>>^ E agora, irmãos, se eu for ter convosco falando em línguas, de que vos aproveitarei, se vos não falar ou por meio de revelação, ou de ciência, ou de profecia, ou de doutrina?

[[v46-14-7]]

^<<v46-14-7,7>>^ Ora, até as coisas inanimadas, que emitem som, seja flauta, seja cítara, se não formarem sons distintos, como se conhecerá o que se toca na flauta ou na cítara?

[[v46-14-8]]

^<<v46-14-8,8>>^ Porque, se a trombeta der sonido incerto, quem se preparará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Assim também vós, se com a língua não pronunciardes palavras bem inteligíveis, como se entenderá o que se diz? porque estareis como que falando ao ar.

[[v46-14-10]]

^<<v46-14-10,10>>^ Há, por exemplo, tantas espécies de vozes no mundo, e nenhuma delas sem significação.

[[v46-14-11]]

^<<v46-14-11,11>>^ Se, pois, eu não souber o sentido da voz, serei estrangeiro para aquele que fala, e o que fala será estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim também vós, já que estais desejosos de dons espirituais, procurai abundar neles para a edificação da igreja.

[[v46-14-13]]

^<<v46-14-13,13>>^ Por isso, o que fala em língua, ore para que a possa interpretar.

[[v46-14-14]]

^<<v46-14-14,14>>^ Porque se eu orar em língua, o meu espírito ora, sim, mas o meu entendimento fica infrutífero.

[[v46-14-15]]

^<<v46-14-15,15>>^ Que fazer, pois? Orarei com o espírito, mas também orarei com o entendimento; cantarei com o espírito, mas também cantarei com o entendimento.

[[v46-14-16]]

^<<v46-14-16,16>>^ De outra maneira, se tu bendisseres com o espírito, como dirá o amém sobre a tua ação de graças aquele que ocupa o lugar de indouto, visto que não sabe o que dizes?

[[v46-14-17]]

^<<v46-14-17,17>>^ Porque realmente tu dás bem as graças, mas o outro não é edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Dou graças a Deus, que falo em línguas mais do que vós todos.

[[v46-14-19]]

^<<v46-14-19,19>>^ Todavia na igreja eu antes quero falar cinco palavras com o meu entendimento, para que possa também instruir os outros, do que dez mil palavras em língua.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não sejais meninos no entendimento; na malícia, contudo, sede criancinhas, mas adultos no entendimento.

[[v46-14-21]]

^<<v46-14-21,21>>^ Está escrito na lei: Por homens de outras línguas e por lábios de estrangeiros falarei a este povo; e nem assim me ouvirão, diz o Senhor.

[[v46-14-22]]

^<<v46-14-22,22>>^ De modo que as línguas são um sinal, não para os crentes, mas para os incrédulos; a profecia, porém, não é sinal para os incrédulos, mas para os crentes.

[[v46-14-23]]

^<<v46-14-23,23>>^ Se, pois, toda a igreja se reunir num mesmo lugar, e todos falarem em línguas, e entrarem indoutos ou incrédulos, não dirão porventura que estais loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Mas, se todos profetizarem, e algum incrédulo ou indouto entrar, por todos é convencido, por todos é julgado;

[[v46-14-25]]

^<<v46-14-25,25>>^ os segredos do seu coração se tornam manifestos; e assim, prostrando-se sobre o seu rosto, adorará a Deus, declarando que Deus está verdadeiramente entre vós.

[[v46-14-26]]

^<<v46-14-26,26>>^ Que fazer, pois, irmãos? Quando vos congregais, cada um de vós tem salmo, tem doutrina, tem revelação, tem língua, tem interpretação. Faça-se tudo para edificação.

[[v46-14-27]]

^<<v46-14-27,27>>^ Se alguém falar em língua, faça-se isso por dois, ou quando muito três, e cada um por sua vez, e haja um que interprete.

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, se não houver intérprete, esteja calado na igreja, e fale consigo mesmo, e com Deus.

[[v46-14-29]]

^<<v46-14-29,29>>^ E falem os profetas, dois ou três, e os outros julguem.

[[v46-14-30]]

^<<v46-14-30,30>>^ Mas se a outro, que estiver sentado, for revelada alguma coisa, cale-se o primeiro.

[[v46-14-31]]

^<<v46-14-31,31>>^ Porque todos podereis profetizar, cada um por sua vez; para que todos aprendam e todos sejam consolados;

[[v46-14-32]]

^<<v46-14-32,32>>^ pois os espíritos dos profetas estão sujeitos aos profetas;

[[v46-14-33]]

^<<v46-14-33,33>>^ porque Deus não é Deus de confusão, mas sim de paz. Como em todas as igrejas dos santos,

[[v46-14-34]]

^<<v46-14-34,34>>^ as mulheres estejam caladas nas igrejas; porque lhes não é permitido falar; mas estejam submissas como também ordena a lei.

[[v46-14-35]]

^<<v46-14-35,35>>^ E, se querem aprender alguma coisa, perguntem em casa a seus próprios maridos; porque é indecoroso para a mulher o falar na igreja.

[[v46-14-36]]

^<<v46-14-36,36>>^ Porventura foi de vós que partiu a palavra de Deus? Ou veio ela somente para vós?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém se considera profeta, ou espiritual, reconheça que as coisas que vos escrevo são mandamentos do Senhor.

[[v46-14-38]]

^<<v46-14-38,38>>^ Mas, se alguém ignora isto, ele é ignorado.

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, irmãos, procurai com zelo o profetizar, e não proibais o falar em línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Mas faça-se tudo decentemente e com ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]