include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-8-1]]

^<<v46-8-1,1>>^ Ora, no tocante às coisas sacrificadas aos ídolos, sabemos que todos temos ciência. A ciência incha, mas o amor edifica.

[[v46-8-2]]

^<<v46-8-2,2>>^ Se alguém cuida saber alguma coisa, ainda não sabe como convém saber.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas, se alguém ama a Deus, esse é conhecido dele.

[[v46-8-4]]

^<<v46-8-4,4>>^ Quanto, pois, ao comer das coisas sacrificadas aos ídolos, sabemos que o ídolo nada é no mundo, e que não há outro Deus, senão um só.

[[v46-8-5]]

^<<v46-8-5,5>>^ Pois, ainda que haja também alguns que se chamem deuses, quer no céu quer na terra &#123;como há muitos deuses e muitos senhores&#125;,

[[v46-8-6]]

^<<v46-8-6,6>>^ todavia para nós há um só Deus, o Pai, de quem são todas as coisas e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual existem todas as coisas, e por ele nós também.

[[v46-8-7]]

^<<v46-8-7,7>>^ Entretanto, nem em todos há esse conhecimento; pois alguns há que, acostumados até agora com o ídolo, comem como de coisas sacrificadas a um ídolo; e a sua consciência, sendo fraca, contamina-se.

[[v46-8-8]]

^<<v46-8-8,8>>^ Não é, porém, a comida que nos há de recomendar a Deus; pois não somos piores se não comermos, nem melhores se comermos.

[[v46-8-9]]

^<<v46-8-9,9>>^ Mas, vede que essa liberdade vossa não venha a ser motivo de tropeço para os fracos.

[[v46-8-10]]

^<<v46-8-10,10>>^ Porque, se alguém te vir a ti, que tens ciência, reclinado à mesa em templo de ídolos, não será induzido, sendo a sua consciência fraca, a comer das coisas sacrificadas aos ídolos?

[[v46-8-11]]

^<<v46-8-11,11>>^ Pela tua ciência, pois, perece aquele que é fraco, o teu irmão por quem Cristo morreu.

[[v46-8-12]]

^<<v46-8-12,12>>^ Ora, pecando assim contra os irmãos, e ferindo-lhes a consciência quando fraca, pecais contra Cristo.

[[v46-8-13]]

^<<v46-8-13,13>>^ Pelo que, se a comida fizer tropeçar a meu irmão, nunca mais comerei carne, para não servir de tropeço a meu irmão.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]