include::./index.adoc[]

[[v46-3-0]]
=== 1 Coríntios, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-3-1]]

^<<v46-3-1,1>>^ E eu, irmãos não vos pude falar como a espirituais, mas como a carnais, como a criancinhas em Cristo.

[[v46-3-2]]

^<<v46-3-2,2>>^ Leite vos dei por alimento, e não comida sólida, porque não a podíeis suportar; nem ainda agora podeis;

[[v46-3-3]]

^<<v46-3-3,3>>^ porquanto ainda sois carnais; pois, havendo entre vós inveja e contendas, não sois porventura carnais, e não estais andando segundo os homens?

[[v46-3-4]]

^<<v46-3-4,4>>^ Porque, dizendo um: Eu sou de Paulo; e outro: Eu de Apolo; não sois apenas homens?

[[v46-3-5]]

^<<v46-3-5,5>>^ Pois, que é Apolo, e que é Paulo, senão ministros pelos quais crestes, e isso conforme o que o Senhor concedeu a cada um?

[[v46-3-6]]

^<<v46-3-6,6>>^ Eu plantei; Apolo regou; mas Deus deu o crescimento.

[[v46-3-7]]

^<<v46-3-7,7>>^ De modo que, nem o que planta é alguma coisa, nem o que rega, mas Deus, que dá o crescimento.

[[v46-3-8]]

^<<v46-3-8,8>>^ Ora, uma só coisa é o que planta e o que rega; e cada um receberá o seu galardão segundo o seu trabalho.

[[v46-3-9]]

^<<v46-3-9,9>>^ Porque nós somos cooperadores de Deus; vós sois lavoura de Deus e edifício de Deus.

[[v46-3-10]]

^<<v46-3-10,10>>^ Segundo a graça de Deus que me foi dada, lancei eu como sábio construtor, o fundamento, e outro edifica sobre ele; mas veja cada um como edifica sobre ele.

[[v46-3-11]]

^<<v46-3-11,11>>^ Porque ninguém pode lançar outro fundamento, além do que já está posto, o qual é Jesus Cristo.

[[v46-3-12]]

^<<v46-3-12,12>>^ E, se alguém sobre este fundamento levanta um edifício de ouro, prata, pedras preciosas, madeira, feno, palha,

[[v46-3-13]]

^<<v46-3-13,13>>^ a obra de cada um se manifestará; pois aquele dia a demonstrará, porque será revelada no fogo, e o fogo provará qual seja a obra de cada um.

[[v46-3-14]]

^<<v46-3-14,14>>^ Se permanecer a obra que alguém sobre ele edificou, esse receberá galardão.

[[v46-3-15]]

^<<v46-3-15,15>>^ Se a obra de alguém se queimar, sofrerá ele prejuízo; mas o tal será salvo todavia como que pelo fogo.

[[v46-3-16]]

^<<v46-3-16,16>>^ Não sabeis vós que sois santuário de Deus, e que o Espírito de Deus habita em vós?

[[v46-3-17]]

^<<v46-3-17,17>>^ Se alguém destruir o santuário de Deus, Deus o destruirá; porque sagrado é o santuário de Deus, que sois vós.

[[v46-3-18]]

^<<v46-3-18,18>>^ Ninguém se engane a si mesmo; se alguém dentre vós se tem por sábio neste mundo, faça-se louco para se tornar sábio.

[[v46-3-19]]

^<<v46-3-19,19>>^ Porque a sabedoria deste mundo é loucura diante de Deus; pois está escrito: Ele apanha os sábios na sua própria astúcia;

[[v46-3-20]]

^<<v46-3-20,20>>^ e outra vez: O Senhor conhece as cogitações dos sábios, que são vãs.

[[v46-3-21]]

^<<v46-3-21,21>>^ Portanto ninguém se glorie nos homens; porque tudo é vosso;

[[v46-3-22]]

^<<v46-3-22,22>>^ seja Paulo, ou Apolo, ou Cefas; seja o mundo, ou a vida, ou a morte; sejam as coisas presentes, ou as vindouras, tudo é vosso,

[[v46-3-23]]

^<<v46-3-23,23>>^ e vós de Cristo, e Cristo de Deus.

'''

xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[&#60; Capítulo Anterior] | <<v46-3-0,Topo>> | xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[Próximo Capítulo &#62;]