include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-11-1]]

^<<v46-11-1,1>>^ Sede meus imitadores, como também eu o sou de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ Ora, eu vos louvo, porque em tudo vos lembrais de mim, e guardais os preceitos assim como vo-los entreguei.

[[v46-11-3]]

^<<v46-11-3,3>>^ Quero porém, que saibais que Cristo é a cabeça de todo homem, o homem a cabeça da mulher, e Deus a cabeça de Cristo.

[[v46-11-4]]

^<<v46-11-4,4>>^ Todo homem que ora ou profetiza com a cabeça coberta desonra a sua cabeça.

[[v46-11-5]]

^<<v46-11-5,5>>^ Mas toda mulher que ora ou profetiza com a cabeça descoberta desonra a sua cabeça, porque é a mesma coisa como se estivesse rapada.

[[v46-11-6]]

^<<v46-11-6,6>>^ Portanto, se a mulher não se cobre com véu, tosquie-se também; se, porém, para a mulher é vergonhoso ser tosquiada ou rapada, cubra-se com véu.

[[v46-11-7]]

^<<v46-11-7,7>>^ Pois o homem, na verdade, não deve cobrir a cabeça, porque é a imagem e glória de Deus; mas a mulher é a glória do homem.

[[v46-11-8]]

^<<v46-11-8,8>>^ Porque o homem não proveio da mulher, mas a mulher do homem;

[[v46-11-9]]

^<<v46-11-9,9>>^ nem foi o homem criado por causa da mulher, mas sim, a mulher por causa do homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ Portanto, a mulher deve trazer sobre a cabeça um sinal de submissão, por causa dos anjos.

[[v46-11-11]]

^<<v46-11-11,11>>^ Todavia, no Senhor, nem a mulher é independente do homem, nem o homem é independente da mulher.

[[v46-11-12]]

^<<v46-11-12,12>>^ pois, assim como a mulher veio do homem, assim também o homem nasce da mulher, mas tudo vem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ julgai entre vós mesmos: é conveniente que uma mulher com a cabeça descoberta ore a Deus?

[[v46-11-14]]

^<<v46-11-14,14>>^ Não vos ensina a própria natureza que se o homem tiver cabelo comprido, é para ele uma desonra;

[[v46-11-15]]

^<<v46-11-15,15>>^ mas se a mulher tiver o cabelo comprido, é para ela uma glória? Pois a cabeleira lhe foi dada em lugar de véu.

[[v46-11-16]]

^<<v46-11-16,16>>^ Mas, se alguém quiser ser contencioso, nós não temos tal costume, nem tampouco as igrejas de Deus.

[[v46-11-17]]

^<<v46-11-17,17>>^ Nisto, porém, que vou dizer-vos não vos louvo; porquanto vos ajuntais, não para melhor, mas para pior.

[[v46-11-18]]

^<<v46-11-18,18>>^ Porque, antes de tudo, ouço que quando vos ajuntais na igreja há entre vós dissensões; e em parte o creio.

[[v46-11-19]]

^<<v46-11-19,19>>^ E até importa que haja entre vós facções, para que os aprovados se tornem manifestos entre vós.

[[v46-11-20]]

^<<v46-11-20,20>>^ De sorte que, quando vos ajuntais num lugar, não é para comer a ceia do Senhor;

[[v46-11-21]]

^<<v46-11-21,21>>^ porque quando comeis, cada um toma antes de outrem a sua própria ceia; e assim um fica com fome e outro se embriaga.

[[v46-11-22]]

^<<v46-11-22,22>>^ Não tendes porventura casas onde comer e beber? Ou desprezais a igreja de Deus, e envergonhais os que nada têm? Que vos direi? Louvar-vos-ei? Nisto não vos louvo.

[[v46-11-23]]

^<<v46-11-23,23>>^ Porque eu recebi do Senhor o que também vos entreguei: que o Senhor Jesus, na noite em que foi traído, tomou pão;

[[v46-11-24]]

^<<v46-11-24,24>>^ e, havendo dado graças, o partiu e disse: Isto é o meu corpo que é por vós; fazei isto em memória de mim.

[[v46-11-25]]

^<<v46-11-25,25>>^ Semelhantemente também, depois de cear, tomou o cálice, dizendo: Este cálice é o novo pacto no meu sangue; fazei isto, todas as vezes que o beberdes, em memória de mim.

[[v46-11-26]]

^<<v46-11-26,26>>^ Porque todas as vezes que comerdes deste pão e beberdes do cálice estareis anunciando a morte do Senhor, até que ele venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ De modo que qualquer que comer do pão, ou beber do cálice do Senhor indignamente, será culpado do corpo e do sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Examine-se, pois, o homem a si mesmo, e assim coma do pão e beba do cálice.

[[v46-11-29]]

^<<v46-11-29,29>>^ Porque quem come e bebe, come e bebe para sua própria condenação, se não discernir o corpo do Senhor.

[[v46-11-30]]

^<<v46-11-30,30>>^ Por causa disto há entre vós muitos fracos e enfermos, e muitos que dormem.

[[v46-11-31]]

^<<v46-11-31,31>>^ Mas, se nós nos julgássemos a nós mesmos, não seríamos julgados;

[[v46-11-32]]

^<<v46-11-32,32>>^ quando, porém, somos julgados pelo Senhor, somos corrigidos, para não sermos condenados com o mundo.

[[v46-11-33]]

^<<v46-11-33,33>>^ Portanto, meus irmãos, quando vos ajuntais para comer, esperai uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Se algum tiver fome, coma em casa, a fim de que não vos reunais para condenação vossa. E as demais coisas eu as ordenarei quando for.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]