include::./index.adoc[]

[[v46-1-0]]
=== 1 Coríntios, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-1-1]]

^<<v46-1-1,1>>^ Paulo, chamado para ser apóstolo de Jesus Cristo pela vontade de Deus, e o irmão Sóstenes,

[[v46-1-2]]

^<<v46-1-2,2>>^ à igreja de Deus que está em Corinto, aos santificados em Cristo Jesus, chamados para serem santos, com todos os que em todo lugar invocam o nome de nosso Senhor Jesus Cristo, Senhor deles e nosso:

[[v46-1-3]]

^<<v46-1-3,3>>^ Graça seja convosco, e paz, da parte de Deus nosso Pai, e do Senhor Jesus Cristo.

[[v46-1-4]]

^<<v46-1-4,4>>^ Sempre dou graças a Deus por vós, pela graça de Deus que vos foi dada em Cristo Jesus;

[[v46-1-5]]

^<<v46-1-5,5>>^ porque em tudo fostes enriquecidos nele, em toda palavra e em todo o conhecimento,

[[v46-1-6]]

^<<v46-1-6,6>>^ assim como o testemunho de Cristo foi confirmado entre vós;

[[v46-1-7]]

^<<v46-1-7,7>>^ de maneira que nenhum dom vos falta, enquanto aguardais a manifestação de nosso Senhor Jesus Cristo,

[[v46-1-8]]

^<<v46-1-8,8>>^ o qual também vos confirmará até o fim, para serdes irrepreensíveis no dia de nosso Senhor Jesus Cristo.

[[v46-1-9]]

^<<v46-1-9,9>>^ Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo nosso Senhor.

[[v46-1-10]]

^<<v46-1-10,10>>^ Rogo-vos, irmãos, em nome de nosso Senhor Jesus Cristo, que sejais concordes no falar, e que não haja dissensões entre vós; antes sejais unidos no mesmo pensamento e no mesmo parecer.

[[v46-1-11]]

^<<v46-1-11,11>>^ Pois a respeito de vós, irmãos meus, fui informado pelos da família de Cloé que há contendas entre vós.

[[v46-1-12]]

^<<v46-1-12,12>>^ Quero dizer com isto, que cada um de vós diz: Eu sou de Paulo; ou, Eu de Apolo; ou Eu sou de Cefas; ou, Eu de Cristo.

[[v46-1-13]]

^<<v46-1-13,13>>^ será que Cristo está dividido? foi Paulo crucificado por amor de vós? ou fostes vós batizados em nome de Paulo?

[[v46-1-14]]

^<<v46-1-14,14>>^ Dou graças a Deus que a nenhum de vós batizei, senão a Crispo e a Gaio;

[[v46-1-15]]

^<<v46-1-15,15>>^ para que ninguém diga que fostes batizados em meu nome.

[[v46-1-16]]

^<<v46-1-16,16>>^ É verdade, batizei também a família de Estéfanas, além destes, não sei se batizei algum outro.

[[v46-1-17]]

^<<v46-1-17,17>>^ Porque Cristo não me enviou para batizar, mas para pregar o evangelho; não em sabedoria de palavras, para não se tornar vã a cruz de Cristo.

[[v46-1-18]]

^<<v46-1-18,18>>^ Porque a palavra da cruz é deveras loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus.

[[v46-1-19]]

^<<v46-1-19,19>>^ porque está escrito: Destruirei a sabedoria dos sábios, e aniquilarei a sabedoria o entendimento dos entendidos.

[[v46-1-20]]

^<<v46-1-20,20>>^ Onde está o sábio? Onde o escriba? Onde o questionador deste século? Porventura não tornou Deus louca a sabedoria deste mundo?

[[v46-1-21]]

^<<v46-1-21,21>>^ Visto como na sabedoria de Deus o mundo pela sua sabedoria não conheceu a Deus, aprouve a Deus salvar pela loucura da pregação os que crêem.

[[v46-1-22]]

^<<v46-1-22,22>>^ Pois, enquanto os judeus pedem sinal, e os gregos buscam sabedoria,

[[v46-1-23]]

^<<v46-1-23,23>>^ nós pregamos a Cristo crucificado, que é escândalo para os judeus, e loucura para os gregos,

[[v46-1-24]]

^<<v46-1-24,24>>^ mas para os que são chamados, tanto judeus como gregos, Cristo, poder de Deus, e sabedoria de Deus.

[[v46-1-25]]

^<<v46-1-25,25>>^ Porque a loucura de Deus é mais sábia que os homens; e a fraqueza de Deus é mais forte que os homens.

[[v46-1-26]]

^<<v46-1-26,26>>^ Ora, vede, irmãos, a vossa vocação, que não são muitos os sábios segundo a carne, nem muitos os poderosos. nem muitos os nobres que são chamados.

[[v46-1-27]]

^<<v46-1-27,27>>^ Pelo contrário, Deus escolheu as coisas loucas do mundo para confundir os sábios; e Deus escolheu as coisas fracas do mundo para confundir as fortes;

[[v46-1-28]]

^<<v46-1-28,28>>^ e Deus escolheu as coisas ignóbeis do mundo, e as desprezadas, e as que não são, para reduzir a nada as que são;

[[v46-1-29]]

^<<v46-1-29,29>>^ para que nenhum mortal se glorie na presença de Deus.

[[v46-1-30]]

^<<v46-1-30,30>>^ Mas vós sois dele, em Cristo Jesus, o qual para nós foi feito por Deus sabedoria, e justiça, e santificação, e redenção;

[[v46-1-31]]

^<<v46-1-31,31>>^ para que, como está escrito: Aquele que se gloria, glorie-se no Senhor.

'''

xref:045-romanos/045-romanos-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[Próximo Capítulo &#62;]