include::./index.adoc[]

[[v46-4-0]]
=== 1 Coríntios, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-4-1]]

^<<v46-4-1,1>>^ Que os homens nos considerem, pois, como ministros de Cristo, e despenseiros dos mistérios de Deus.

[[v46-4-2]]

^<<v46-4-2,2>>^ Ora, além disso, o que se requer nos despenseiros é que cada um seja encontrado fiel.

[[v46-4-3]]

^<<v46-4-3,3>>^ Todavia, a mim mui pouco se me dá de ser julgado por vós, ou por qualquer tribunal humano; nem eu tampouco a mim mesmo me julgo.

[[v46-4-4]]

^<<v46-4-4,4>>^ Porque, embora em nada me sinta culpado, nem por isso sou justificado; pois quem me julga é o Senhor.

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto nada julgueis antes do tempo, até que venha o Senhor, o qual não só trará à luz as coisas ocultas das trevas, mas também manifestará os desígnios dos corações; e então cada um receberá de Deus o seu louvor.

[[v46-4-6]]

^<<v46-4-6,6>>^ Ora, irmãos, estas coisas eu as apliquei figuradamente a mim e a Apolo, por amor de vós; para que em nós aprendais a não ir além do que está escrito, de modo que nenhum de vós se ensoberbeça a favor de um contra outro.

[[v46-4-7]]

^<<v46-4-7,7>>^ Pois, quem te diferença? E que tens tu que não tenhas recebido? E, se o recebeste, por que te glorias, como se não o houveras recebido?

[[v46-4-8]]

^<<v46-4-8,8>>^ Já estais fartos! já estais ricos! sem nós já chegastes a reinar! e oxalá reinásseis de fato, para que também nós reinássemos convosco!

[[v46-4-9]]

^<<v46-4-9,9>>^ Porque tenho para mim, que Deus a nós, apóstolos, nos pôs por últimos, como condenados à morte; pois somos feitos espetáculo ao mundo, tanto a anjos como a homens.

[[v46-4-10]]

^<<v46-4-10,10>>^ Nós somos loucos por amor de Cristo, e vós sábios em Cristo; nós fracos, e vós fortes; vós ilustres, e nós desprezíveis.

[[v46-4-11]]

^<<v46-4-11,11>>^ Até a presente hora padecemos fome, e sede; estamos nus, e recebemos bofetadas, e não temos pousada certa,

[[v46-4-12]]

^<<v46-4-12,12>>^ e nos afadigamos, trabalhando com nossas próprias mãos; somos injuriados, e bendizemos; somos perseguidos, e o suportamos;

[[v46-4-13]]

^<<v46-4-13,13>>^ somos difamados, e exortamos; até o presente somos considerados como o refugo do mundo, e como a escória de tudo.

[[v46-4-14]]

^<<v46-4-14,14>>^ Não escrevo estas coisas para vos envergonhar, mas para vos admoestar, como a filhos meus amados.

[[v46-4-15]]

^<<v46-4-15,15>>^ Porque ainda que tenhais dez mil aios em Cristo, não tendes contudo muitos pais; pois eu pelo evangelho vos gerei em Cristo Jesus.

[[v46-4-16]]

^<<v46-4-16,16>>^ Rogo-vos, portanto, que sejais meus imitadores.

[[v46-4-17]]

^<<v46-4-17,17>>^ Por isso mesmo vos enviei Timóteo, que é meu filho amado, e fiel no Senhor; o qual vos lembrará os meus caminhos em Cristo, como por toda parte eu ensino em cada igreja.

[[v46-4-18]]

^<<v46-4-18,18>>^ Mas alguns andam inchados, como se eu não houvesse de ir ter convosco.

[[v46-4-19]]

^<<v46-4-19,19>>^ Em breve, porém, irei ter convosco, se o Senhor quiser, e então conhecerei, não as palavras dos que andam inchados, mas o poder.

[[v46-4-20]]

^<<v46-4-20,20>>^ Porque o reino de Deus não consiste em palavras, mas em poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ Que quereis? Irei a vós com vara, ou com amor e espírito de mansidão?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]