include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-9-1]]

^<<v46-9-1,1>>^ Não sou eu livre? Não sou apóstolo? Não vi eu a Jesus nosso Senhor? Não sois vós obra minha no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Se eu não sou apóstolo para os outros, ao menos para vós o sou; porque vós sois o selo do meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ Esta é a minha defesa para com os que me acusam.

[[v46-9-4]]

^<<v46-9-4,4>>^ Não temos nós direito de comer e de beber?

[[v46-9-5]]

^<<v46-9-5,5>>^ Não temos nós direito de levar conosco esposa crente, como também os demais apóstolos, e os irmãos do Senhor, e Cefas?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que só eu e Barnabé não temos direito de deixar de trabalhar?

[[v46-9-7]]

^<<v46-9-7,7>>^ Quem jamais vai à guerra à sua própria custa? Quem planta uma vinha e não come do seu fruto? Ou quem apascenta um rebanho e não se alimenta do leite do rebanho?

[[v46-9-8]]

^<<v46-9-8,8>>^ Porventura digo eu isto como homem? Ou não diz a lei também o mesmo?

[[v46-9-9]]

^<<v46-9-9,9>>^ Pois na lei de Moisés está escrito: Não atarás a boca do boi quando debulha. Porventura está Deus cuidando dos bois?

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou não o diz certamente por nós? Com efeito, é por amor de nós que está escrito; porque o que lavra deve debulhar com esperança de participar do fruto.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se nós semeamos para vós as coisas espirituais, será muito que de vós colhamos as matérias?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros participam deste direito sobre vós, por que não nós com mais justiça? Mas nós nunca usamos deste direito; antes suportamos tudo, para não pormos impedimento algum ao evangelho de Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Não sabeis vós que os que administram o que é sagrado comem do que é do templo? E que os que servem ao altar, participam do altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Assim ordenou também o Senhor aos que anunciam o evangelho, que vivam do evangelho.

[[v46-9-15]]

^<<v46-9-15,15>>^ Mas eu de nenhuma destas coisas tenho usado. Nem escrevo isto para que assim se faça comigo; porque melhor me fora morrer, do que alguém fazer vã esta minha glória.

[[v46-9-16]]

^<<v46-9-16,16>>^ Pois, se anuncio o evangelho, não tenho de que me gloriar, porque me é imposta essa obrigação; e ai de mim, se não anunciar o evangelho!

[[v46-9-17]]

^<<v46-9-17,17>>^ Se, pois, o faço de vontade própria, tenho recompensa; mas, se não é de vontade própria, estou apenas incumbido de uma mordomia.

[[v46-9-18]]

^<<v46-9-18,18>>^ Logo, qual é a minha recompensa? É que, pregando o evangelho, eu o faça gratuitamente, para não usar em absoluto do meu direito no evangelho.

[[v46-9-19]]

^<<v46-9-19,19>>^ Pois, sendo livre de todos, fiz-me escravo de todos para ganhar o maior número possível:

[[v46-9-20]]

^<<v46-9-20,20>>^ Fiz-me como judeu para os judeus, para ganhar os judeus; para os que estão debaixo da lei, como se estivesse eu debaixo da lei &#123;embora debaixo da lei não esteja&#125;, para ganhar os que estão debaixo da lei;

[[v46-9-21]]

^<<v46-9-21,21>>^ para os que estão sem lei, como se estivesse sem lei &#123;não estando sem lei para com Deus, mas debaixo da lei de Cristo&#125;, para ganhar os que estão sem lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Fiz-me como fraco para os fracos, para ganhar os fracos. Fiz-me tudo para todos, para por todos os meios chegar a salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Ora, tudo faço por causa do evangelho, para dele tornar-me co-participante.

[[v46-9-24]]

^<<v46-9-24,24>>^ Não sabeis vós que os que correm no estádio, todos, na verdade, correm, mas um só é que recebe o prêmio? Correi de tal maneira que o alcanceis.

[[v46-9-25]]

^<<v46-9-25,25>>^ E todo aquele que luta, exerce domínio próprio em todas as coisas; ora, eles o fazem para alcançar uma coroa corruptível, nós, porém, uma incorruptível.

[[v46-9-26]]

^<<v46-9-26,26>>^ Pois eu assim corro, não como indeciso; assim combato, não como batendo no ar.

[[v46-9-27]]

^<<v46-9-27,27>>^ Antes subjugo o meu corpo, e o reduzo à submissão, para que, depois de pregar a outros, eu mesmo não venha a ficar reprovado.

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]