include::./index.adoc[]

[[v46-15-0]]
=== 1 Coríntios, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-15-1]]

^<<v46-15-1,1>>^ Ora, eu vos lembro, irmãos, o evangelho que já vos anunciei; o qual também recebestes, e no qual perseverais,

[[v46-15-2]]

^<<v46-15-2,2>>^ pelo qual também sois salvos, se é que o conservais tal como vo-lo anunciei; se não é que crestes em vão.

[[v46-15-3]]

^<<v46-15-3,3>>^ Porque primeiramente vos entreguei o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras;

[[v46-15-4]]

^<<v46-15-4,4>>^ que foi sepultado; que foi ressuscitado ao terceiro dia, segundo as Escrituras;

[[v46-15-5]]

^<<v46-15-5,5>>^ que apareceu a Cefas, e depois aos doze;

[[v46-15-6]]

^<<v46-15-6,6>>^ depois apareceu a mais de quinhentos irmãos duma vez, dos quais vive ainda a maior parte, mas alguns já dormiram;

[[v46-15-7]]

^<<v46-15-7,7>>^ depois apareceu a Tiago, então a todos os apóstolos;

[[v46-15-8]]

^<<v46-15-8,8>>^ e por derradeiro de todos apareceu também a mim, como a um abortivo.

[[v46-15-9]]

^<<v46-15-9,9>>^ Pois eu sou o menor dos apóstolos, que nem sou digno de ser chamado apóstolo, porque persegui a igreja de Deus.

[[v46-15-10]]

^<<v46-15-10,10>>^ Mas pela graça de Deus sou o que sou; e a sua graça para comigo não foi vã, antes trabalhei muito mais do que todos eles; todavia não eu, mas a graça de Deus que está comigo.

[[v46-15-11]]

^<<v46-15-11,11>>^ Então, ou seja eu ou sejam eles, assim pregamos e assim crestes.

[[v46-15-12]]

^<<v46-15-12,12>>^ Ora, se prega que Cristo foi ressuscitado dentre os mortos, como dizem alguns entre vós que não há ressurreição de mortos?

[[v46-15-13]]

^<<v46-15-13,13>>^ Mas se não há ressurreição de mortos, também Cristo não foi ressuscitado.

[[v46-15-14]]

^<<v46-15-14,14>>^ E, se Cristo não foi ressuscitado, logo é vã a nossa pregação, e também é vã a vossa fé.

[[v46-15-15]]

^<<v46-15-15,15>>^ E assim somos também considerados como falsas testemunhas de Deus que ele ressuscitou a Cristo, ao qual, porém, não ressuscitou, se, na verdade, os mortos não são ressuscitados.

[[v46-15-16]]

^<<v46-15-16,16>>^ Porque, se os mortos não são ressuscitados, também Cristo não foi ressuscitado.

[[v46-15-17]]

^<<v46-15-17,17>>^ E, se Cristo não foi ressuscitado, é vã a vossa fé, e ainda estais nos vossos pecados.

[[v46-15-18]]

^<<v46-15-18,18>>^ Logo, também os que dormiram em Cristo estão perdidos.

[[v46-15-19]]

^<<v46-15-19,19>>^ Se é só para esta vida que esperamos em Cristo, somos de todos os homens os mais dignos de lástima.

[[v46-15-20]]

^<<v46-15-20,20>>^ Mas na realidade Cristo foi ressuscitado dentre os mortos, sendo ele as primícias dos que dormem.

[[v46-15-21]]

^<<v46-15-21,21>>^ Porque, assim como por um homem veio a morte, também por um homem veio a ressurreição dos mortos.

[[v46-15-22]]

^<<v46-15-22,22>>^ Pois como em Adão todos morrem, do mesmo modo em Cristo todos serão vivificados.

[[v46-15-23]]

^<<v46-15-23,23>>^ Cada um, porém, na sua ordem: Cristo as primícias, depois os que são de Cristo, na sua vinda.

[[v46-15-24]]

^<<v46-15-24,24>>^ Então virá o fim quando ele entregar o reino a Deus o Pai, quando houver destruído todo domínio, e toda autoridade e todo poder.

[[v46-15-25]]

^<<v46-15-25,25>>^ Pois é necessário que ele reine até que haja posto todos os inimigos debaixo de seus pés.

[[v46-15-26]]

^<<v46-15-26,26>>^ Ora, o último inimigo a ser destruído é a morte.

[[v46-15-27]]

^<<v46-15-27,27>>^ Pois se lê: Todas as coisas sujeitou debaixo de seus pés. Mas, quando diz: Todas as coisas lhe estão sujeitas, claro está que se excetua aquele que lhe sujeitou todas as coisas.

[[v46-15-28]]

^<<v46-15-28,28>>^ E, quando todas as coisas lhe estiverem sujeitas, então também o próprio Filho se sujeitará àquele que todas as coisas lhe sujeitou, para que Deus seja tudo em todos.

[[v46-15-29]]

^<<v46-15-29,29>>^ De outra maneira, que farão os que se batizam pelos mortos? Se absolutamente os mortos não ressuscitam, por que então se batizam por eles?

[[v46-15-30]]

^<<v46-15-30,30>>^ E por que nos expomos também nós a perigos a toda hora?

[[v46-15-31]]

^<<v46-15-31,31>>^ Eu vos declaro, irmãos, pela glória que de vós tenho em Cristo Jesus nosso Senhor, que morro todos os dias.

[[v46-15-32]]

^<<v46-15-32,32>>^ Se, como homem, combati em Éfeso com as feras, que me aproveita isso? Se os mortos não são ressuscitados, comamos e bebamos, porque amanhã morreremos.

[[v46-15-33]]

^<<v46-15-33,33>>^ Não vos enganeis. As más companhias corrompem os bons costumes.

[[v46-15-34]]

^<<v46-15-34,34>>^ Acordai para a justiça e não pequeis mais; porque alguns ainda não têm conhecimento de Deus; digo-o para vergonha vossa.

[[v46-15-35]]

^<<v46-15-35,35>>^ Mas alguém dirá: Como ressuscitam os mortos? e com que qualidade de corpo vêm?

[[v46-15-36]]

^<<v46-15-36,36>>^ Insensato! o que tu semeias não é vivificado, se primeiro não morrer.

[[v46-15-37]]

^<<v46-15-37,37>>^ E, quando semeias, não semeias o corpo que há de nascer, mas o simples grão, como o de trigo, ou o de outra qualquer semente.

[[v46-15-38]]

^<<v46-15-38,38>>^ Mas Deus lhe dá um corpo como lhe aprouve, e a cada uma das sementes um corpo próprio.

[[v46-15-39]]

^<<v46-15-39,39>>^ Nem toda carne é uma mesma carne; mas uma é a carne dos homens, outra a carne dos animais, outra a das aves e outra a dos peixes.

[[v46-15-40]]

^<<v46-15-40,40>>^ Também há corpos celestes e corpos terrestres, mas uma é a glória dos celestes e outra a dos terrestres.

[[v46-15-41]]

^<<v46-15-41,41>>^ Uma é a glória do sol, outra a glória da lua e outra a glória das estrelas; porque uma estrela difere em glória de outra estrela.

[[v46-15-42]]

^<<v46-15-42,42>>^ Assim também é a ressurreição, é ressuscitado em incorrupção.

[[v46-15-43]]

^<<v46-15-43,43>>^ Semeia-se em ignomínia, é ressuscitado em glória. Semeia-se em fraqueza, é ressuscitado em poder.

[[v46-15-44]]

^<<v46-15-44,44>>^ Semeia-se corpo animal, é ressuscitado corpo espiritual. Se há corpo animal, há também corpo espiritual.

[[v46-15-45]]

^<<v46-15-45,45>>^ Assim também está escrito: O primeiro homem, Adão, tornou-se alma vivente; o último Adão, espírito vivificante.

[[v46-15-46]]

^<<v46-15-46,46>>^ Mas não é primeiro o espiritual, senão o animal; depois o espiritual.

[[v46-15-47]]

^<<v46-15-47,47>>^ O primeiro homem, sendo da terra, é terreno; o segundo homem é do céu.

[[v46-15-48]]

^<<v46-15-48,48>>^ Qual o terreno, tais também os terrenos; e, qual o celestial, tais também os celestiais.

[[v46-15-49]]

^<<v46-15-49,49>>^ E, assim como trouxemos a imagem do terreno, traremos também a imagem do celestial.

[[v46-15-50]]

^<<v46-15-50,50>>^ Mas digo isto, irmãos, que carne e sangue não podem herdar o reino de Deus; nem a corrupção herda a incorrupção.

[[v46-15-51]]

^<<v46-15-51,51>>^ Eis aqui vos digo um mistério: Nem todos dormiremos mas todos seremos transformados,

[[v46-15-52]]

^<<v46-15-52,52>>^ num momento, num abrir e fechar de olhos, ao som da última trombeta; porque a trombeta soará, e os mortos serão ressuscitados incorruptíveis, e nós seremos transformados.

[[v46-15-53]]

^<<v46-15-53,53>>^ Porque é necessário que isto que é corruptível se revista da incorruptibilidade e que isto que é mortal se revista da imortalidade.

[[v46-15-54]]

^<<v46-15-54,54>>^ Mas, quando isto que é corruptível se revestir da incorruptibilidade, e isto que é mortal se revestir da imortalidade, então se cumprirá a palavra que está escrito: Tragada foi a morte na vitória.

[[v46-15-55]]

^<<v46-15-55,55>>^ Onde está, ó morte, a tua vitória? Onde está, ó morte, o teu aguilhão?

[[v46-15-56]]

^<<v46-15-56,56>>^ O aguilhão da morte é o pecado, e a força do pecado é a lei.

[[v46-15-57]]

^<<v46-15-57,57>>^ Mas graça a Deus que nos dá a vitória por nosso Senhor Jesus Cristo.

[[v46-15-58]]

^<<v46-15-58,58>>^ Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.

'''

xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[&#60; Capítulo Anterior] | <<v46-15-0,Topo>> | xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[Próximo Capítulo &#62;]