include::./index.adoc[]

[[v46-2-0]]
=== 1 Coríntios, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-2-1]]

^<<v46-2-1,1>>^ E eu, irmãos, quando fui ter convosco, anunciando-vos o testemunho de Deus, não fui com sublimidade de palavras ou de sabedoria.

[[v46-2-2]]

^<<v46-2-2,2>>^ Porque nada me propus saber entre vós, senão a Jesus Cristo, e este crucificado.

[[v46-2-3]]

^<<v46-2-3,3>>^ E eu estive convosco em fraqueza, e em temor, e em grande tremor.

[[v46-2-4]]

^<<v46-2-4,4>>^ A minha linguagem e a minha pregação não consistiram em palavras persuasivas de sabedoria, mas em demonstração do Espírito de poder;

[[v46-2-5]]

^<<v46-2-5,5>>^ para que a vossa fé não se apoiasse na sabedoria dos homens, mas no poder de Deus.

[[v46-2-6]]

^<<v46-2-6,6>>^ Na verdade, entre os perfeitos falamos sabedoria, não porém a sabedoria deste mundo, nem dos príncipes deste mundo, que estão sendo reduzidos a nada;

[[v46-2-7]]

^<<v46-2-7,7>>^ mas falamos a sabedoria de Deus em mistério, que esteve oculta, a qual Deus preordenou antes dos séculos para nossa glória;

[[v46-2-8]]

^<<v46-2-8,8>>^ a qual nenhum dos príncipes deste mundo compreendeu; porque se a tivessem compreendido, não teriam crucificado o Senhor da glória.

[[v46-2-9]]

^<<v46-2-9,9>>^ Mas, como está escrito: As coisas que olhos não viram, nem ouvidos ouviram, nem penetraram o coração do homem, são as que Deus preparou para os que o amam.

[[v46-2-10]]

^<<v46-2-10,10>>^ Porque Deus no-las revelou pelo seu Espírito; pois o Espírito esquadrinha todas as coisas, mesmos as profundezas de Deus.

[[v46-2-11]]

^<<v46-2-11,11>>^ Pois, qual dos homens entende as coisas do homem, senão o espírito do homem que nele está? assim também as coisas de Deus, ninguém as compreendeu, senão o Espírito de Deus.

[[v46-2-12]]

^<<v46-2-12,12>>^ Ora, nós não temos recebido o espírito do mundo, mas sim o Espírito que provém de Deus, a fim de compreendermos as coisas que nos foram dadas gratuitamente por Deus;

[[v46-2-13]]

^<<v46-2-13,13>>^ as quais também falamos, não com palavras ensinadas pela sabedoria humana, mas com palavras ensinadas pelo Espírito Santo, comparando coisas espirituais com espirituais.

[[v46-2-14]]

^<<v46-2-14,14>>^ Ora, o homem natural não aceita as coisas do Espírito de Deus, porque para ele são loucura; e não pode entendê-las, porque elas se discernem espiritualmente.

[[v46-2-15]]

^<<v46-2-15,15>>^ Mas o que é espiritual discerne bem tudo, enquanto ele por ninguém é discernido.

[[v46-2-16]]

^<<v46-2-16,16>>^ Pois, quem jamais conheceu a mente do Senhor, para que possa instruí-lo? Mas nós temos a mente de Cristo.

'''

xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[&#60; Capítulo Anterior] | <<v46-2-0,Topo>> | xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[Próximo Capítulo &#62;]