include::./index.adoc[]

[[v46-6-0]]
=== 1 Coríntios, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v46-6-1]]

^<<v46-6-1,1>>^ Ousa algum de vós, tendo uma queixa contra outro, ir a juízo perante os injustos, e não perante os santos?

[[v46-6-2]]

^<<v46-6-2,2>>^ Ou não sabeis vós que os santos hão de julgar o mundo? Ora, se o mundo há de ser julgado por vós, sois porventura indignos de julgar as coisas mínimas?

[[v46-6-3]]

^<<v46-6-3,3>>^ Não sabeis vós que havemos de julgar os anjos? Quanto mais as coisas pertencentes a esta vida?

[[v46-6-4]]

^<<v46-6-4,4>>^ Então, se tiverdes negócios em juízo, pertencentes a esta vida, constituís como juízes deles os que são de menos estima na igreja?

[[v46-6-5]]

^<<v46-6-5,5>>^ Para vos envergonhar o digo. Será que não há entre vós sequer um sábio, que possa julgar entre seus irmãos?

[[v46-6-6]]

^<<v46-6-6,6>>^ Mas vai um irmão a juízo contra outro irmão, e isto perante incrédulos?

[[v46-6-7]]

^<<v46-6-7,7>>^ Na verdade já é uma completa derrota para vós o terdes demandadas uns contra os outros. Por que não sofreis antes a injustiça? Por que não sofreis antes a fraude?

[[v46-6-8]]

^<<v46-6-8,8>>^ Mas vós mesmos é que fazeis injustiça e defraudais; e isto a irmãos.

[[v46-6-9]]

^<<v46-6-9,9>>^ Não sabeis que os injustos não herdarão o reino de Deus? Não vos enganeis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas,

[[v46-6-10]]

^<<v46-6-10,10>>^ nem os ladrões, nem os avarentos, nem os bêbedos, nem os maldizentes, nem os roubadores herdarão o reino de Deus.

[[v46-6-11]]

^<<v46-6-11,11>>^ E tais fostes alguns de vós; mas fostes lavados, mas fostes santificados, mas fostes justificados em nome do Senhor Jesus Cristo e no Espírito do nosso Deus.

[[v46-6-12]]

^<<v46-6-12,12>>^ Todas as coisas me são lícitas, mas nem todas as coisas convêm. Todas as coisas me são lícitas; mas eu não me deixarei dominar por nenhuma delas.

[[v46-6-13]]

^<<v46-6-13,13>>^ Os alimentos são para o estômago e o estômago para os alimentos; Deus, porém aniquilará, tanto um como os outros. Mas o corpo não é para a prostituição, mas para o Senhor, e o Senhor para o corpo.

[[v46-6-14]]

^<<v46-6-14,14>>^ Ora, Deus não somente ressuscitou ao Senhor, mas também nos ressuscitará a nós pelo seu poder.

[[v46-6-15]]

^<<v46-6-15,15>>^ Não sabeis vós que os vossos corpos são membros de Cristo? Tomarei pois os membros de Cristo, e os farei membros de uma meretriz? De modo nenhum.

[[v46-6-16]]

^<<v46-6-16,16>>^ Ou não sabeis que o que se une à meretriz, faz-se um corpo com ela? Porque, como foi dito, os dois serão uma só carne.

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas, o que se une ao Senhor é um só espírito com ele.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fugi da prostituição. Qualquer outro pecado que o homem comete, é fora do corpo; mas o que se prostitui peca contra o seu próprio corpo.

[[v46-6-19]]

^<<v46-6-19,19>>^ Ou não sabeis que o vosso corpo é santuário do Espírito Santo, que habita em vós, o qual possuís da parte de Deus, e que não sois de vós mesmos?

[[v46-6-20]]

^<<v46-6-20,20>>^ Porque fostes comprados por preço; glorificai pois a Deus no vosso corpo.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]