include::./index.adoc[]

[[v9-19-0]]
=== 1 Samuel, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-19-1]]

^<<v9-19-1,1>>^ Falou, pois, Saul a Jônatas, seu filho, e a todos os seus servos, para que matassem a Davi. Porém Jônatas, filho de Saul, estava muito afeiçoado a Davi.

[[v9-19-2]]

^<<v9-19-2,2>>^ Pelo que Jônatas o anunciou a Davi, dizendo: Saul, meu pai, procura matar-te; portanto, guarda-te amanhã pela manhã, fica num lugar oculto e esconde-te;

[[v9-19-3]]

^<<v9-19-3,3>>^ eu sairei e me porei ao lado de meu pai no campo em que estiveres; falarei acerca de ti a meu pai, verei o que há, e to anunciarei.

[[v9-19-4]]

^<<v9-19-4,4>>^ Então Jônatas falou bem de Davi a Saul, seu pai, e disse-lhe: Não peque o rei contra seu servo Davi, porque ele não pecou contra ti, e porque os seus feitos para contigo têm sido muito bons.

[[v9-19-5]]

^<<v9-19-5,5>>^ Porque expôs a sua vida e matou o filisteu, e o Senhor fez um grande livramento para todo o Israel. Tu mesmo o viste, e te alegraste; por que, pois, pecarias contra o sangue inocente, matando sem causa a Davi?

[[v9-19-6]]

^<<v9-19-6,6>>^ E Saul deu ouvidos à voz de Jônatas, e jurou: Como vive o Senhor, Davi não morrera.

[[v9-19-7]]

^<<v9-19-7,7>>^ Jônatas, pois, chamou a Davi, contou-lhe todas estas palavras, e o levou a Saul; e Davi o assistia como dantes.

[[v9-19-8]]

^<<v9-19-8,8>>^ Depois tornou a haver guerra; e saindo Davi, pelejou contra os filisteus, e os feriu com grande matança, e eles fugiram diante dele.

[[v9-19-9]]

^<<v9-19-9,9>>^ Então o espírito maligno da parte do Senhor veio sobre Saul, estando ele sentado em sua casa, e tendo na mão a sua lança; e Davi estava tocando a harpa.

[[v9-19-10]]

^<<v9-19-10,10>>^ E Saul procurou encravar a Davi na parede, porém ele se desviou de diante de Saul, que fincou a lança na parede. Então Davi fugiu, e escapou naquela mesma noite.

[[v9-19-11]]

^<<v9-19-11,11>>^ Mas Saul mandou mensageiros à casa de Davi, para que o vigiassem, e o matassem pela manhã; porém Mical, mulher de Davi, o avisou, dizendo: Se não salvares a tua vida esta noite, amanhã te matarão.

[[v9-19-12]]

^<<v9-19-12,12>>^ Então Mical desceu Davi por uma janela, e ele se foi e, fugindo, escapou.

[[v9-19-13]]

^<<v9-19-13,13>>^ Mical tomou uma estátua, deitou-a na cama, pôs-lhe à cabeceira uma pele de cabra, e a cobriu com uma capa.

[[v9-19-14]]

^<<v9-19-14,14>>^ Quando Saul enviou mensageiros para prenderem a Davi, ela disse: Está doente.

[[v9-19-15]]

^<<v9-19-15,15>>^ Tornou Saul a enviá-los, para que vissem a Davi, dizendo-lhes: Trazei-mo na cama, para que eu o mate.

[[v9-19-16]]

^<<v9-19-16,16>>^ Vindo, pois, os mensageiros, eis que estava a estátua na cama, e a pele de cabra à sua cabeceira.

[[v9-19-17]]

^<<v9-19-17,17>>^ Então perguntou Saul a Mical: Por que assim me enganaste, e deixaste o meu inimigo ir e escapar? Respondeu Mical a Saul: Porque ele me disse: Deixa-me ir! Por que hei de matar-te?

[[v9-19-18]]

^<<v9-19-18,18>>^ Assim Davi fugiu e escapou; e indo ter com Samuel, em Ramá, contou-lhe tudo quanto Saul lhe fizera; foram, pois, ele e Samuel, e ficaram em Naiote.

[[v9-19-19]]

^<<v9-19-19,19>>^ E foi dito a Saul: Eis que Davi está em Naiote, em Ramá.

[[v9-19-20]]

^<<v9-19-20,20>>^ Então enviou Saul mensageiros para prenderem a Davi; quando eles viram a congregação de profetas profetizando, e Samuel a presidi-los, o Espírito de Deus veio sobre os mensageiros de Saul, e também eles profetizaram.

[[v9-19-21]]

^<<v9-19-21,21>>^ Avisado disso, Saul enviou outros mensageiros, e também estes profetizaram. Ainda terceira vez enviou Saul mensageiros, os quais também profetizaram.

[[v9-19-22]]

^<<v9-19-22,22>>^ Então foi ele mesmo a Rama e, chegando ao poço grande que estava em Sécu, perguntou: Onde estão Samuel e Davi? Responderam-lhe: Eis que estão em Naiote, em Ramá.

[[v9-19-23]]

^<<v9-19-23,23>>^ Foi, pois, para Naiote, em Ramá; e o Espírito de Deus veio também sobre ele, e ele ia caminhando e profetizando, até chegar a Naiote, em Ramá.

[[v9-19-24]]

^<<v9-19-24,24>>^ E despindo as suas vestes, ele também profetizou diante de Samuel; e esteve nu por terra todo aquele dia e toda aquela noite. Pelo que se diz: Está também Saul entre os profetas?

'''

xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[&#60; Capítulo Anterior] | <<v9-19-0,Topo>> | xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[Próximo Capítulo &#62;]