include::./index.adoc[]

[[v9-31-0]]
=== 1 Samuel, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-31-1]]

^<<v9-31-1,1>>^ Ora, os filisteus pelejaram contra Israel; e os homens de Israel fugiram de diante dos filisteus, e caíram mortos no monte Gilboa.

[[v9-31-2]]

^<<v9-31-2,2>>^ E os filisteus apertaram com Saul e seus filhos, e mataram a Jônatas, a Abinadabe e a Malquisua, filhos de Saul.

[[v9-31-3]]

^<<v9-31-3,3>>^ A peleja se agravou contra Saul, e os flecheiros o alcançaram, e o feriram gravemente.

[[v9-31-4]]

^<<v9-31-4,4>>^ Pelo que disse Saul ao seu escudeiro: Arranca a tua espada, e atravessa-me com ela, para que porventura não venham esses incircuncisos, e me atravessem e escarneçam de mim. Mas o seu escudeiro não quis, porque temia muito. Então Saul tomou a espada, e se lançou sobre ela.

[[v9-31-5]]

^<<v9-31-5,5>>^ Vendo, pois, e seu escudeiro que Saul já era morto, também ele se lançou sobre a sua espada, e morreu com ele.

[[v9-31-6]]

^<<v9-31-6,6>>^ Assim morreram juntamente naquele dia Saul, seus três filhos, e seu escudeiro, e todos os seus homens.

[[v9-31-7]]

^<<v9-31-7,7>>^ Quando os israelitas que estavam no outro lado do vale e os que estavam além de Jordão viram que os homens de Israel tinham fugido, e que Saul e seus filhos estavam mortos, abandonaram as suas cidades e fugiram; e vieram os filisteus e habitaram nelas.

[[v9-31-8]]

^<<v9-31-8,8>>^ No dia seguinte, quando os filisteus vieram para despojar os mortos, acharam Saul e seus três filhos estirados no monte Gilboa.

[[v9-31-9]]

^<<v9-31-9,9>>^ Então cortaram a cabeça a Saul e o despejaram das suas armas; e enviaram pela terra dos filisteus, em redor, a anunciá-lo no templo dos seus ídolos e entre e povo,

[[v9-31-10]]

^<<v9-31-10,10>>^ Puseram as armas de Saul no templo de Astarote; e penduraram o seu corpo no muro de Bete-Seã.

[[v9-31-11]]

^<<v9-31-11,11>>^ Quando os moradores de Jabes-Gileade ouviram isso a respeito de Saul, isto é, o que os filisteus lhe tinham feito,

[[v9-31-12]]

^<<v9-31-12,12>>^ todos os homens valorosos se levantaram e, caminhando a noite toda, tiraram e corpo de Saul e os corpos de seus filhos do muro de Bete-Seã; e voltando a Jabes, ali os queimaram.

[[v9-31-13]]

^<<v9-31-13,13>>^ Depois tomaram os seus ossos, e os sepultaram debaixo da tamargueira, em Jabes, e jejuaram sete dias.

'''

xref:009-1-samuel/009-1-samuel-030.adoc#v9-30-0[&#60; Capítulo Anterior] | <<v9-31-0,Topo>> | xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[Próximo Capítulo &#62;]