include::./index.adoc[]

[[v9-26-0]]
=== 1 Samuel, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-26-1]]

^<<v9-26-1,1>>^ Ora, vieram os zifeus a Saul, a Gibeá, dizendo: Não está Davi se escondendo no outeiro de Haquilá, defronte de Jesimom?

[[v9-26-2]]

^<<v9-26-2,2>>^ Então Saul se levantou, e desceu ao deserto de Zife, levando consigo três mil homens escolhidos de Israel, para buscar a Davi no deserto de Zife.

[[v9-26-3]]

^<<v9-26-3,3>>^ E acampou-se Saul no outeiro de Haquilá, defronte de Jesimom, junto ao caminho; porém Davi ficou no deserto, e percebendo que Saul vinha após ele ao deserto,

[[v9-26-4]]

^<<v9-26-4,4>>^ enviou espias, e certificou-se de que Saul tinha chegado.

[[v9-26-5]]

^<<v9-26-5,5>>^ Então Davi levantou-se e foi ao lugar onde Saul se tinha acampado; viu Davi o lugar onde se deitavam Saul e Abner, filho de Ner, chefe do seu exército. E Saul estava deitado dentro do acampamento, e o povo estava acampado ao redor dele.

[[v9-26-6]]

^<<v9-26-6,6>>^ Então Davi, dirigindo-se a Aimeleque, o heteu, e a Abisai, filho de Zeruia, irmão de Joabe, perguntou: Quem descerá comigo a Saul, ao arraial? Respondeu Abisai: Eu descerei contigo.

[[v9-26-7]]

^<<v9-26-7,7>>^ Foram, pois, Davi e Abisai de noite ao povo; e eis que Saul estava deitado, dormindo dentro do acampamento, e a sua lança estava pregada na terra à sua cabeceira; e Abner e o povo estavam deitados ao redor dele.

[[v9-26-8]]

^<<v9-26-8,8>>^ Então disse Abisai a Davi: Deus te entregou hoje nas mãos o teu inimigo; deixa-me, pois, agora encravá-lo na terra, com a lança, de um só golpe; não o ferirei segunda vez.

[[v9-26-9]]

^<<v9-26-9,9>>^ Mas Davi respondeu a Abisai: Não o mates; pois quem pode estender a mão contra o ungido do Senhor, e ficar inocente?

[[v9-26-10]]

^<<v9-26-10,10>>^ Disse mais Davi: Como vive o Senhor, ou o Senhor o ferirá, ou chegará o seu dia e morrerá, ou descerá para a batalha e perecerá;

[[v9-26-11]]

^<<v9-26-11,11>>^ o Senhor, porém, me guarde de que eu estenda a mão contra o ungido do Senhor. Agora, pois, toma a lança que está à sua cabeceira, e a bilha d'água, e vamo-nos.

[[v9-26-12]]

^<<v9-26-12,12>>^ Tomou, pois, Davi a lança e a bilha d'água da cabeceira de Saul, e eles se foram. Ninguém houve que o visse, nem que o soubesse, nem que acordasse; porque todos estavam dormindo, pois da parte do Senhor havia caído sobre eles um profundo sono.

[[v9-26-13]]

^<<v9-26-13,13>>^ Então Davi, passando à outra banda, pôs-se no cume do monte, ao longe, de maneira que havia grande distância entre eles.

[[v9-26-14]]

^<<v9-26-14,14>>^ E Davi bradou ao povo, e a Abner, filho de Ner, dizendo: Não responderás, Abner? Então Abner respondeu e disse: Quem és tu, que bradas ao rei?

[[v9-26-15]]

^<<v9-26-15,15>>^ Ao que disse Davi a Abner: Não és tu um homem? e quem há em Israel como tu? Por que, então, não guardaste o rei, teu senhor? porque um do povo veio para destruir o rei, teu senhor.

[[v9-26-16]]

^<<v9-26-16,16>>^ Não é bom isso que fizeste. Vive o Senhor, que sois dignos de morte, porque não guardastes a vosso senhor, o ungido do Senhor. Vede, pois, agora onde está a lança do rei, e a bilha d'água que estava à sua cabeceira.

[[v9-26-17]]

^<<v9-26-17,17>>^ Saul reconheceu a voz de Davi, e disse: Não é esta a tua voz, meu filho Davi? Respondeu Davi: E minha voz, ó rei, meu senhor.

[[v9-26-18]]

^<<v9-26-18,18>>^ Disse mais: Por que o meu senhor persegue tanto o seu servo? que fiz eu? e que maldade se acha na minha mão?

[[v9-26-19]]

^<<v9-26-19,19>>^ Ouve pois agora, ó rei, meu senhor, as palavras de teu servo: Se é o Senhor quem te incita contra mim, receba ele uma oferta; se, porém, são os filhos dos homens, malditos sejam perante o Senhor, pois eles me expulsaram hoje para que eu não tenha parte na herança do Senhor, dizendo: Vai, serve a outros deuses.

[[v9-26-20]]

^<<v9-26-20,20>>^ Agora, pois, não caia o meu sangue em terra fora da presença do Senhor; pois saiu o rei de Israel em busca duma pulga, como quem persegue uma perdiz nos montes.

[[v9-26-21]]

^<<v9-26-21,21>>^ Então disse Saul: Pequei; volta, meu filho Davi, pois não tornarei a fazer-te mal, porque a minha vida foi hoje preciosa aos teus olhos. Eis que procedi como um louco, e errei grandissimamente.

[[v9-26-22]]

^<<v9-26-22,22>>^ Davi então respondeu, e disse: Eis aqui a lança, ó rei! venha cá um os mancebos, e leve-a.

[[v9-26-23]]

^<<v9-26-23,23>>^ O Senhor, porém, pague a cada um a sua justiça e a sua lealdade; pois o Senhor te entregou hoje na minha mão, mas eu não quis estender a mão contra o ungido do Senhor.

[[v9-26-24]]

^<<v9-26-24,24>>^ E assim como foi a tua vida hoje preciosa aos meus olhos, seja a minha vida preciosa aos olhos do Senhor, e livre-me ele de toda a tribulação.

[[v9-26-25]]

^<<v9-26-25,25>>^ Então Saul disse a Davi: Bendito sejas tu, meu filho Davi, pois grandes coisas farás e também certamente prevalecerás. Então Davi se foi o seu caminho e Saul voltou para o seu lugar.

'''

xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[&#60; Capítulo Anterior] | <<v9-26-0,Topo>> | xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[Próximo Capítulo &#62;]