include::./index.adoc[]

[[v9-6-0]]
=== 1 Samuel, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-6-1]]

^<<v9-6-1,1>>^ A arca do Senhor ficou na terra dos filisteus sete meses.

[[v9-6-2]]

^<<v9-6-2,2>>^ Então os filisteus chamaram os sacerdotes e os adivinhadores para dizer-lhes: Que faremos nós da arca do Senhor? Fazei-nos saber como havemos de enviá-la para o seu lugar.

[[v9-6-3]]

^<<v9-6-3,3>>^ Responderam eles: Se enviardes a arca do Deus de Israel, não a envieis vazia, porém sem falta enviareis a ele uma oferta pela culpa; então sereis curados, e se vos fará saber por que a sua mão não se retira de vós.

[[v9-6-4]]

^<<v9-6-4,4>>^ Então perguntaram: Qual é a oferta pela culpa que lhe havemos de enviar? Eles responderam: Segundo o número dos chefes dos filisteus, cinco tumores de ouro e cinco ratos de ouro, porque a praga é uma e a mesma sobre todos os vossos príncipes.

[[v9-6-5]]

^<<v9-6-5,5>>^ Fazei, pois, imagens, dos vossos tumores, e dos ratos que andam destruindo a terra, e dai glória ao Deus de Israel; porventura aliviará o peso da sua mão de sobre vós, e de sobre vosso deus, e de sobre vossa terra:

[[v9-6-6]]

^<<v9-6-6,6>>^ Por que, pois, endureceríeis os vossos corações, como os egípcios e Faraó endureceram os seus corações? Porventura depois de os haver Deus castigado, não deixaram ir o povo, e este não se foi?

[[v9-6-7]]

^<<v9-6-7,7>>^ Agora, pois, fazei um carro novo, tomai duas vacas que estejam criando, sobre as quais não tenha vindo o jugo, atai-as ao carro e levai os seus bezerros de após elas para casa.

[[v9-6-8]]

^<<v9-6-8,8>>^ Tomai a arca de Senhor, e ponde-a sobre o carro; também metei num cofre, ao seu lado, as jóias de ouro que haveis de oferecer ao Senhor como ofertas pela culpa; e assim a enviareis, para que se vá.

[[v9-6-9]]

^<<v9-6-9,9>>^ Reparai então: se ela subir pelo caminho do seu termo a Bete-Semes, foi ele quem nos fez este grande mal; mas, se não, saberemos que não foi a sua mão que nos feriu, e que isto nos sucedeu por acaso.

[[v9-6-10]]

^<<v9-6-10,10>>^ Assim, pois, fizeram aqueles homens: tomaram duas vacas que criavam, ataram-nas ao carro, e encerraram os bezerros em casa;

[[v9-6-11]]

^<<v9-6-11,11>>^ também puseram a arca do Senhor sobre o carro, bem como e cofre com os ratos de ouro e com as imagens dos seus tumores.

[[v9-6-12]]

^<<v9-6-12,12>>^ Então as vacas foram caminhando diretamente pelo caminho de Bete-Semes, seguindo a estrada, andando e berrando, sem se desviarem nem para a direita nem para a esquerda; e os chefes dos filisteus foram seguindo-as até o termo de Bete-Semes.

[[v9-6-13]]

^<<v9-6-13,13>>^ Ora, andavam os de Bete-Semes fazendo a sega do trigo no vale; e, levantando os olhos, viram a arca e, vendo-a, se alegraram.

[[v9-6-14]]

^<<v9-6-14,14>>^ Tendo chegado o carro ao campo de Josué, o bete-semita, parou ali, onde havia uma grande pedra. Fenderam a madeira do carro, e ofereceram as vacas ao Senhor em holocausto.

[[v9-6-15]]

^<<v9-6-15,15>>^ Nisso os levitas desceram a arca do Senhor, como também o cofre que estava junto a ela, em que se achavam as jóias de ouro, e puseram-nos sobre aquela grande pedra; e no mesmo dia os homens de Bete-Semes ofereceram holocaustos e sacrifícios ao Senhor.

[[v9-6-16]]

^<<v9-6-16,16>>^ E os cinco chefes dos filisteus, tendo visto aquilo, voltaram para Ecrom no mesmo dia.

[[v9-6-17]]

^<<v9-6-17,17>>^ Estes, pois, são os tumores de ouro que os filisteus enviaram ao Senhor como oferta pela culpa: por Asdode um, por Gaza outro, por Asquelom outro, por Gate outro, por Ecrom outro.

[[v9-6-18]]

^<<v9-6-18,18>>^ Como também os ratos de ouro, segundo o número de todas as cidades dos filisteus, pertencentes aos cinco chefes, desde as cidades fortificadas até as aldeias campestres. Disso é testemunha a grande pedra sobre a qual puseram a arca do Senhor, pedra que ainda está até o dia de hoje no campo de Josué, o bete-semita.

[[v9-6-19]]

^<<v9-6-19,19>>^ Ora, o Senhor feriu os homens de Bete-Semes, porquanto olharam para dentro da arca do Senhor; feriu do povo cinqüenta mil e setenta homens; então o povo se entristeceu, porque o Senhor o ferira com tão grande morticínio.

[[v9-6-20]]

^<<v9-6-20,20>>^ Disseram os homens de Bete-Semes: Quem poderia subsistir perante o Senhor, este Deus santo? e para quem subirá de nós?

[[v9-6-21]]

^<<v9-6-21,21>>^ Enviaram, pois, mensageiros aos habitantes de Quiriate-Jearim, para lhes dizerem: Os filisteus remeteram a arca do Senhor; descei, e fazei-a subir para vós.

'''

xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[&#60; Capítulo Anterior] | <<v9-6-0,Topo>> | xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[Próximo Capítulo &#62;]