include::./index.adoc[]

[[v9-3-0]]
=== 1 Samuel, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-3-1]]

^<<v9-3-1,1>>^ Entretanto, o menino Samuel servia ao Senhor perante Eli. E a palavra de Senhor era muito rara naqueles dias; as visões não eram freqüentes.

[[v9-3-2]]

^<<v9-3-2,2>>^ Sucedeu naquele tempo que, estando Eli deitado no seu lugar &#123;ora, os seus olhos começavam já a escurecer, de modo que não podia ver&#125;,

[[v9-3-3]]

^<<v9-3-3,3>>^ e ainda não se havendo apagado a lâmpada de Deus, e estando Samuel também deitado no templo do Senhor, onde estava a arca de Deus,

[[v9-3-4]]

^<<v9-3-4,4>>^ o Senhor chamou: Samuel! Samuel! Ele respondeu: Eis-me aqui.

[[v9-3-5]]

^<<v9-3-5,5>>^ E correndo a Eli, disse-lhe: Eis-me aqui, porque tu me chamaste. Mas ele disse: Eu não te chamei; torna a deitar-te. E ele foi e se deitou.

[[v9-3-6]]

^<<v9-3-6,6>>^ Tornou o Senhor a chamar: Samuel! E Samuel se levantou, foi a Eli e disse: Eis-me aqui, porque tu me chamaste. Mas ele disse: Eu não te chamei, filho meu; torna a deitar-te.

[[v9-3-7]]

^<<v9-3-7,7>>^ Ora, Samuel ainda não conhecia ao Senhor, e a palavra de Senhor ainda não lhe tinha sido revelada.

[[v9-3-8]]

^<<v9-3-8,8>>^ O Senhor, pois, tornou a chamar a Samuel pela terceira vez. E ele, levantando-se, foi a Eli e disse: Eis-me aqui, porque tu me chamaste. Então entendeu Eli que o Senhor chamava o menino.

[[v9-3-9]]

^<<v9-3-9,9>>^ Pelo que Eli disse a Samuel: Vai deitar-te, e há de ser que, se te chamar, dirás: Fala, Senhor, porque o teu servo ouve. Foi, pois, Samuel e deitou-se no seu lugar.

[[v9-3-10]]

^<<v9-3-10,10>>^ Depois veio o Senhor, parou e chamou como das outras vezes: Samuel! Samuel! Ao que respondeu Samuel: Fala, porque o teu servo ouve.

[[v9-3-11]]

^<<v9-3-11,11>>^ Então disse o Senhor a Samuel: Eis que vou fazer uma coisa em Israel, a qual fará tinir ambos os ouvidos a todo o que a ouvir.

[[v9-3-12]]

^<<v9-3-12,12>>^ Naquele mesmo dia cumprirei contra Eli, de princípio a fim, tudo quanto tenho falado a respeito da sua casa.

[[v9-3-13]]

^<<v9-3-13,13>>^ Porque já lhe fiz: saber que hei de julgar a sua casa para sempre, por causa da iniqüidade de que ele bem sabia, pois os seus filhos blasfemavam a Deus, e ele não os repreendeu.

[[v9-3-14]]

^<<v9-3-14,14>>^ Portanto, jurei à casa de Eli que nunca jamais será expiada a sua iniqüidade, nem com sacrifícios, nem com ofertas.

[[v9-3-15]]

^<<v9-3-15,15>>^ Samuel ficou deitado até pela manhã, e então abriu as portas da casa do Senhor; Samuel, porém, temia relatar essa visão a Eli.

[[v9-3-16]]

^<<v9-3-16,16>>^ Mas chamou Eli a Samuel, e disse: Samuel, meu filho! Ao que este respondeu: Eis-me aqui.

[[v9-3-17]]

^<<v9-3-17,17>>^ Eli perguntou-lhe: Que te falou o Senhor? peço-te que não mo encubras; assim Deus te faça, e outro tanto, se me encobrires alguma coisa de tudo o que te falou.

[[v9-3-18]]

^<<v9-3-18,18>>^ Samuel, pois, relatou-lhe tudo, e nada lhe encobriu. Então disse Eli: Ele é o Senhor, faça o que bem parecer aos seus olhos.

[[v9-3-19]]

^<<v9-3-19,19>>^ Samuel crescia, e o Senhor era com ele e não deixou nenhuma de todas as suas palavras cair em terra.

[[v9-3-20]]

^<<v9-3-20,20>>^ E todo o Israel, desde Dã até Berseba, conheceu que Samuel estava confirmado como profeta do Senhor.

[[v9-3-21]]

^<<v9-3-21,21>>^ E voltou o Senhor a aparecer em Siló; porquanto o Senhor se manifestava a Samuel em Siló pela sua palavra. E chegava a palavra de Samuel a todo o Israel.

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]