include::./index.adoc[]

[[v9-20-0]]
=== 1 Samuel, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-20-1]]

^<<v9-20-1,1>>^ Então fugiu Davi de Naiote, em Ramá, veio ter com Jônatas e lhe disse: Que fiz eu? qual é a minha iniqüidade? e qual é o meu pecado diante de teu pai, para que procure tirar-me a vida?

[[v9-20-2]]

^<<v9-20-2,2>>^ E ele lhe disse: Longe disso! não hás de morrer. Meu pai não faz coisa alguma, nem grande nem pequena, sem que primeiro ma participe; por que, pois, meu pai me encobriria este negócio? Não é verdade.

[[v9-20-3]]

^<<v9-20-3,3>>^ Respondeu-lhe Davi, com juramento: Teu pai bem sabe que achei graça aos teus olhos; pelo que disse: Não saiba isto Jônatas, para que não se magoe. Mas, na verdade, como vive o Senhor, e como vive a tua alma, há apenas um passo entre mim e a morte.

[[v9-20-4]]

^<<v9-20-4,4>>^ Disse Jônatas a Davi: O que desejas tu que eu te faça?

[[v9-20-5]]

^<<v9-20-5,5>>^ Respondeu Davi a Jônatas: Eis que amanhã é a lua nova, e eu deveria sentar-me com o rei para comer; porém deixa-me ir, e esconder-me-ei no campo até a tarde do terceiro dia.

[[v9-20-6]]

^<<v9-20-6,6>>^ Se teu pai notar a minha ausência, dirás: Davi me pediu muito que o deixasse ir correndo a Belém, sua cidade, porquanto se faz lá o sacrifício anual para toda a parentela.

[[v9-20-7]]

^<<v9-20-7,7>>^ Se ele disser: Está bem; então teu servo tem paz; porém se ele muito se indignar, fica sabendo que ele já está resolvido a praticar o mal.

[[v9-20-8]]

^<<v9-20-8,8>>^ Usa, pois, de misericórdia para com o teu servo, porque o fizeste entrar contigo em aliança do Senhor; se, porém, há culpa em mim, mata-me tu mesmo; por que me levarias a teu pai?

[[v9-20-9]]

^<<v9-20-9,9>>^ Ao que respondeu Jônatas: Longe de ti tal coisa! Se eu soubesse que meu pai estava resolvido a trazer o mal sobre ti, não to descobriria eu?

[[v9-20-10]]

^<<v9-20-10,10>>^ Perguntou, pois, Davi a Jônatas: Quem me fará saber, se por acaso teu pai te responder asperamente?

[[v9-20-11]]

^<<v9-20-11,11>>^ Então disse Jônatas a Davi: Vem, e saiamos ao campo. E saíram ambos ao campo.

[[v9-20-12]]

^<<v9-20-12,12>>^ E disse Jônatas a Davi: O Senhor, Deus de Israel, seja testemunha! Sondando eu a meu pai amanhã a estas horas, ou depois de amanhã, se houver coisa favorável para Davi, eu não enviarei a ti e não to farei saber?

[[v9-20-13]]

^<<v9-20-13,13>>^ O Senhor faça assim a Jônatas, e outro tanto, se, querendo meu pai fazer-te mal, eu não te fizer saber, e não te deixar partir, para ires em paz; e o Senhor seja contigo, assim como foi com meu pai.

[[v9-20-14]]

^<<v9-20-14,14>>^ E não somente usarás para comigo, enquanto viver, da benevolência do Senhor, para que não morra,

[[v9-20-15]]

^<<v9-20-15,15>>^ como também não cortarás nunca da minha casa a tua benevolência, nem ainda quando o Senhor tiver desarraigado da terra a cada um dos inimigos de Davi.

[[v9-20-16]]

^<<v9-20-16,16>>^ Assim fez Jônatas aliança com a casa de Davi, dizendo: O Senhor se vingue dos inimigos de Davi.

[[v9-20-17]]

^<<v9-20-17,17>>^ Então Jônatas fez Davi jurar de novo, porquanto o amava; porque o amava com todo o amor da sua alma.

[[v9-20-18]]

^<<v9-20-18,18>>^ Disse-lhe ainda Jônatas: Amanhã é a lua nova, e notar-se-á a tua ausência, pois o teu lugar estará vazio.

[[v9-20-19]]

^<<v9-20-19,19>>^ Ao terceiro dia descerás apressadamente, e irás àquele lugar onde te escondeste no dia do negócio, e te sentarás junto à pedra de Ezel.

[[v9-20-20]]

^<<v9-20-20,20>>^ E eu atirarei três flechas para aquela banda, como se atirasse ao alvo.

[[v9-20-21]]

^<<v9-20-21,21>>^ Então mandarei o moço, dizendo: Anda, busca as flechas. Se eu expressamente disser ao moço: Olha que as flechas estão para cá de ti, apanha-as; então vem, porque, como vive o Senhor, há paz para ti, e não há nada a temer.

[[v9-20-22]]

^<<v9-20-22,22>>^ Mas se eu disser ao moço assim: Olha que as flechas estão para lá de ti; vai-te embora, porque o Senhor te manda ir.

[[v9-20-23]]

^<<v9-20-23,23>>^ E quanto ao negócio de que eu e tu falamos, o Senhor é testemunha entre mim e ti para sempre.

[[v9-20-24]]

^<<v9-20-24,24>>^ Escondeu-se, pois, Davi no campo; e, sendo a lua nova, sentou-se o rei para comer.

[[v9-20-25]]

^<<v9-20-25,25>>^ E, sentando-se o rei, como de costume, no seu assento junto à parede, Jônatas sentou-se defronte dele, e Abner sentou-se ao lado de Saul; e o lugar de Davi ficou vazio.

[[v9-20-26]]

^<<v9-20-26,26>>^ Entretanto Saul não disse nada naquele dia, pois dizia consigo: Aconteceu-lhe alguma coisa pela qual não está limpo; certamente não está limpo.

[[v9-20-27]]

^<<v9-20-27,27>>^ Sucedeu também no dia seguinte, o segundo da lua nova, que o lugar de Davi ficou vazio. Perguntou, pois, Saul a Jônatas, seu filho: Por que o filho de Jessé não veio comer nem ontem nem hoje?

[[v9-20-28]]

^<<v9-20-28,28>>^ Respondeu Jônatas a Saul: Davi pediu-me encarecidamente licença para ir a Belém,

[[v9-20-29]]

^<<v9-20-29,29>>^ dizendo: Peço-te que me deixes ir, porquanto a nossa parentela tem um sacrifício na cidade, e meu irmão ordenou que eu fosse; se, pois, agora tenho achado graça aos teus olhos, peço-te que me deixes ir, para ver a meus irmãos. Por isso não veio à mesa do rei.

[[v9-20-30]]

^<<v9-20-30,30>>^ Então se acendeu a ira de Saul contra Jônatas, e ele lhe disse: Filho da perversa e rebelde! Não sei eu que tens escolhido a filho de Jessé para vergonha tua, e para vergonha de tua mãe?

[[v9-20-31]]

^<<v9-20-31,31>>^ Pois por todo o tempo em que o filho de Jessé viver sobre a terra, nem tu estarás seguro, nem o teu reino; pelo que envia agora, e traze-mo, porque ele há de morrer.

[[v9-20-32]]

^<<v9-20-32,32>>^ Ao que respondeu Jônatas a Saul, seu pai, e lhe disse: Por que há de morrer. que fez ele?

[[v9-20-33]]

^<<v9-20-33,33>>^ Então Saul levantou a lança, para o ferir; assim entendeu Jônatas que seu pai tinha determinado matar a Davi.

[[v9-20-34]]

^<<v9-20-34,34>>^ Pelo que Jônatas, todo encolerizado, se levantou da mesa, e no segundo dia do mês não comeu; pois se magoava por causa de Davi, porque seu pai o tinha ultrajado.

[[v9-20-35]]

^<<v9-20-35,35>>^ Jônatas, pois, saiu ao campo, pela manhã, ao tempo que tinha ajustado com Davi, levando consigo um rapazinho.

[[v9-20-36]]

^<<v9-20-36,36>>^ Então disse ao moço: Corre a buscar as flechas que eu atirar. Correu, pois, o moço; e Jônatas atirou uma flecha, que fez passar além dele.

[[v9-20-37]]

^<<v9-20-37,37>>^ Quando o moço chegou ao lugar onde estava a flecha que Jônatas atirara, gritou-lhe este, dizendo: Não está porventura a flecha para lá de ti?

[[v9-20-38]]

^<<v9-20-38,38>>^ E tornou a gritar ao moço: Apressa-te, anda, não te demores! E o servo de Jônatas apanhou as flechas, e as trouxe a seu senhor.

[[v9-20-39]]

^<<v9-20-39,39>>^ O moço, porém, nada percebeu; só Jônatas e Davi sabiam do negócio.

[[v9-20-40]]

^<<v9-20-40,40>>^ Então Jônatas deu as suas armas ao moço, e lhe disse: Vai, leva-as à cidade.

[[v9-20-41]]

^<<v9-20-41,41>>^ Logo que o moço se foi, levantou-se Davi da banda do sul, e lançou-se sobre o seu rosto em terra, e inclinou-se três vezes; e beijaram-se um ao outro, e choraram ambos, mas Davi chorou muito mais.

[[v9-20-42]]

^<<v9-20-42,42>>^ E disse Jônatas a Davi: Vai-te em paz, porquanto nós temos jurado ambos em nome do Senhor, dizendo: O Senhor seja entre mim e ti, e entre a minha descendência e a tua descendência perpetuamente.

[[v9-20-43]]

^<<v9-20-43,43>>^ Então Davi se levantou e partiu; e Jônatas entrou na cidade.

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]