include::./index.adoc[]

[[v9-8-0]]
=== 1 Samuel, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-8-1]]

^<<v9-8-1,1>>^ Ora, havendo Samuel envelhecido, constituiu a seus filhos por juízes sobre Israel.

[[v9-8-2]]

^<<v9-8-2,2>>^ O seu filho primogênito chamava-se Joel, e o segundo Abias; e julgavam em Berseba.

[[v9-8-3]]

^<<v9-8-3,3>>^ Seus filhos, porém, não andaram nos caminhos dele, mas desviaram-se após o lucro e, recebendo peitas, perverteram a justiça.

[[v9-8-4]]

^<<v9-8-4,4>>^ Então todos os anciãos de Israel se congregaram, e vieram ter com Samuel, a Ramá,

[[v9-8-5]]

^<<v9-8-5,5>>^ e lhe disseram: Eis que já estás velho, e teus filhos não andam nos teus caminhos. Constitui-nos, pois, agora um rei para nos julgar, como o têm todas as nações.

[[v9-8-6]]

^<<v9-8-6,6>>^ Mas pareceu mal aos olhos de Samuel, quando disseram: Dá-nos um rei para nos julgar. Então Samuel orou ao Senhor.

[[v9-8-7]]

^<<v9-8-7,7>>^ Disse o Senhor a Samuel: Ouve a voz do povo em tudo quanto te dizem, pois não é a ti que têm rejeitado, porém a mim, para que eu não reine sobre eles.

[[v9-8-8]]

^<<v9-8-8,8>>^ Conforme todas as obras que fizeram desde o dia em que os tirei do Egito até o dia de hoje, deixando-me a mim e servindo a outros deuses, assim também fazem a ti.

[[v9-8-9]]

^<<v9-8-9,9>>^ Agora, pois, ouve a sua voz, contudo lhes protestarás solenemente, e lhes declararás qual será o modo de agir do rei que houver de reinar sobre eles.

[[v9-8-10]]

^<<v9-8-10,10>>^ Referiu, pois, Samuel todas as palavras do Senhor ao povo, que lhe havia pedido um rei,

[[v9-8-11]]

^<<v9-8-11,11>>^ e disse: Este será o modo de agir do rei que houver de reinar sobre vós: tomará os vossos filhos, e os porá sobre os seus carros, e para serem seus cavaleiros, e para correrem adiante dos seus carros;

[[v9-8-12]]

^<<v9-8-12,12>>^ e os porá por chefes de mil e chefes de cinqüenta, para lavrarem os seus campos, fazerem as suas colheitas e fabricarem as suas armas de guerra e os petrechos de seus carros.

[[v9-8-13]]

^<<v9-8-13,13>>^ Tomará as vossas filhas para perfumistas, cozinheiras e padeiras.

[[v9-8-14]]

^<<v9-8-14,14>>^ Tomará o melhor das vossas terras, das vossas vinhas e dos vossos elivais, e o dará aos seus servos.

[[v9-8-15]]

^<<v9-8-15,15>>^ Tomará e dízimo das vossas sementes e das vossas vinhas, para dar aos seus oficiais e aos seus servos.

[[v9-8-16]]

^<<v9-8-16,16>>^ Também os vossos servos e as vossas servas, e os vossos melhores mancebos, e os vossos jumentos tomará, e os empregará no seu trabalho.

[[v9-8-17]]

^<<v9-8-17,17>>^ Tomará o dízimo do vosso rebanho; e vós lhe servireis de escravos.

[[v9-8-18]]

^<<v9-8-18,18>>^ Então naquele dia clamareis por causa de vosso rei, que vós mesmos houverdes escolhido; mas o Senhor não vos ouvira.

[[v9-8-19]]

^<<v9-8-19,19>>^ O povo, porém, não quis ouvir a voz de Samuel; e disseram: Não, mas haverá sobre nós um rei,

[[v9-8-20]]

^<<v9-8-20,20>>^ para que nós também sejamos como todas as outras nações, e para que o nosso rei nos julgue, e saia adiante de nós, e peleje as nossas batalhas.

[[v9-8-21]]

^<<v9-8-21,21>>^ Ouviu, pois, Samuel todas as palavras do povo, e as repetiu aos ouvidos do Senhor.

[[v9-8-22]]

^<<v9-8-22,22>>^ Disse o Senhor a Samuel: Dá ouvidos à sua voz, e constitui-lhes rei. Então Samuel disse aos homens de Israel: Volte cada um para a sua cidade.

'''

xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[&#60; Capítulo Anterior] | <<v9-8-0,Topo>> | xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[Próximo Capítulo &#62;]