include::./index.adoc[]

[[v9-30-0]]
=== 1 Samuel, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-30-1]]

^<<v9-30-1,1>>^ Sucedeu, pois, que, chegando Davi e os seus homens ao terceiro dia a Ziclague, os amalequitas tinham feito uma incursão sobre o Negebe, e sobre Ziclague, e tinham ferido a Ziclague e a tinham queimado a fogo;

[[v9-30-2]]

^<<v9-30-2,2>>^ e tinham levado cativas as mulheres, e todos os que estavam nela, tanto pequenos como grandes; a ninguém, porém, mataram, tão-somente os levaram consigo, e foram o seu caminho.

[[v9-30-3]]

^<<v9-30-3,3>>^ Quando Davi e os seus homens chegaram à cidade, eis que estava queimada a fogo, e suas mulheres, seus filhos e suas filhas tinham sido levados cativos.

[[v9-30-4]]

^<<v9-30-4,4>>^ Então Davi e o povo que se achava com ele alçaram a sua voz, e choraram, até que não ouve neles mais forças para chorar.

[[v9-30-5]]

^<<v9-30-5,5>>^ Também as duas mulheres de Davi foram levadas cativas: Ainoã, a jizreelita, e Abigail, que fora mulher de Nabal, o carmelita.

[[v9-30-6]]

^<<v9-30-6,6>>^ Também Davi se angustiou; pois o povo falava em apedrejá-lo, porquanto a alma de todo o povo estava amargurada por causa de seus filhos e de suas filhas. Mas Davi se fortaleceu no Senhor seu Deus.

[[v9-30-7]]

^<<v9-30-7,7>>^ Disse Davi a Abiatar, o sacerdote, filho de Aimeleque: Traze-me aqui o éfode. E Abiatar trouxe o éfode a Davi.

[[v9-30-8]]

^<<v9-30-8,8>>^ Então consultou Davi ao Senhor, dizendo: Perseguirei eu a esta tropa? alcançá-la-ei? Respondeu-lhe o Senhor: Persegue-a; porque de certo a alcançarás e tudo recobrarás.

[[v9-30-9]]

^<<v9-30-9,9>>^ Ao que partiu Davi, ele e os seiscentos homens que com ele se achavam, e chegaram ao ribeiro de Besor, onde pararam os que tinham ficado para trás.

[[v9-30-10]]

^<<v9-30-10,10>>^ Mas Davi ainda os perseguia, com quatrocentos homens, enquanto que duzentos ficaram atrás, por não poderem, de cansados que estavam, passar o ribeiro de Besor.

[[v9-30-11]]

^<<v9-30-11,11>>^ Ora, acharam no campo um egípcio, e o trouxeram a Davi; deram-lhe pão a comer, e água a beber;

[[v9-30-12]]

^<<v9-30-12,12>>^ deram-lhe também um pedaço de massa de figos secos e dois cachos de passas. Tendo ele comido, voltou-lhe o ânimo; pois havia três dias e três noites que não tinha comido pão nem bebido água.

[[v9-30-13]]

^<<v9-30-13,13>>^ Então Davi lhe perguntou: De quem és tu, e donde vens? Respondeu ele: Sou um moço egípcio, servo dum amalequita; e o meu senhor me abandonou, porque adoeci há três dias.

[[v9-30-14]]

^<<v9-30-14,14>>^ Nós fizemos uma incursão sobre o Negebe dos queretitas, sobre o de Judá e sobre o de Calebe, e pusemos fogo a Ziclague.

[[v9-30-15]]

^<<v9-30-15,15>>^ Perguntou-lhe Davi: Poderias descer e guiar-me a essa tropa? Respondeu ele: Jura-me tu por Deus que não me matarás, nem me entregarás na mão de meu senhor, e eu descerei e te guiarei a essa tropa.

[[v9-30-16]]

^<<v9-30-16,16>>^ Desceu, pois, e o guiou; e eis que eles estavam espalhados sobre a face de toda a terra, comendo, bebendo e dançando, por causa de todo aquele grande despojo que haviam tomado da terra dos filisteus e a terra de Judá.

[[v9-30-17]]

^<<v9-30-17,17>>^ Então Davi os feriu, desde o crepúsculo até a tarde do dia seguinte, e nenhum deles escapou, senão só quatrocentos mancebos que, montados sobre camelos, fugiram.

[[v9-30-18]]

^<<v9-30-18,18>>^ Assim recobrou Davi tudo quanto os amalequitas haviam tomado; também libertou as suas duas mulheres.

[[v9-30-19]]

^<<v9-30-19,19>>^ De modo que não lhes faltou coisa alguma, nem pequena nem grande, nem filhos nem filhas, nem qualquer coisa de tudo quanto os amalequitas lhes haviam tomado; tudo Davi tornou a trazer.

[[v9-30-20]]

^<<v9-30-20,20>>^ Davi lhes tomou também todos os seus rebanhos e manadas; e o povo os levava adiante do outro gado, e dizia: Este é o despojo de Davi.

[[v9-30-21]]

^<<v9-30-21,21>>^ Quando Davi chegou aos duzentos homens que, de cansados que estavam, não tinham podido segui-los, e que foram obrigados a ficar ao pé do ribeiro de Besor, estes saíram ao encontro de Davi e do povo que com ele vinha; e Davi, aproximando-se deles, os saudou em paz.

[[v9-30-22]]

^<<v9-30-22,22>>^ Então todos os malvados e perversos, dentre os homens que tinham ido com Davi, disseram: Visto que não foram conosco, nada lhes daremos do despojo que recobramos, senão a cada um sua mulher e seus filhos, para que os levem e se retirem.

[[v9-30-23]]

^<<v9-30-23,23>>^ Mas Davi disse: Não fareis assim, irmãos meus, com o que nos deu o Senhor, que nos guardou e entregou nas nossas mãos a tropa que vinha contra nós.

[[v9-30-24]]

^<<v9-30-24,24>>^ E quem vos daria ouvidos nisso? pois qual é a parte dos que desceram à batalha, tal será também a parte dos que ficaram com a bagagem; receberão partes.

[[v9-30-25]]

^<<v9-30-25,25>>^ E assim foi daquele dia em diante, ficando estabelecido por estatuto e direito em Israel até o dia de hoje.

[[v9-30-26]]

^<<v9-30-26,26>>^ Quando Davi chegou a Ziclague, enviou do despojo presente aos anciãos de Judá, seus amigos, dizendo: Eis aí para vós um presente do despojo dos inimigos do Senhor;

[[v9-30-27]]

^<<v9-30-27,27>>^ aos de Betel, aos de Ramote do Sul, e aos de Jatir;

[[v9-30-28]]

^<<v9-30-28,28>>^ aos de Aroer, aos de Sifmote, e aos de Estemoa;

[[v9-30-29]]

^<<v9-30-29,29>>^ aos de Racal, aos das cidades dos jerameelitas, e aos das cidades dos queneus;

[[v9-30-30]]

^<<v9-30-30,30>>^ aos de Horma, aos de Corasã, e aos de Atace;

[[v9-30-31]]

^<<v9-30-31,31>>^ e aos de Hebrom, e aos de todos os lugares que Davi e os seus homens costumavam freqüentar.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]