include::./index.adoc[]

[[v9-5-0]]
=== 1 Samuel, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-5-1]]

^<<v9-5-1,1>>^ Os filisteus, pois, tomaram a arca de Deus, e a levaram de Ebenézer a Asdode.

[[v9-5-2]]

^<<v9-5-2,2>>^ Então os filisteus tomaram a arca de Deus e a introduziram na casa de Dagom, e a puseram junto a Dagom.

[[v9-5-3]]

^<<v9-5-3,3>>^ Levantando-se, porém, de madrugada no dia seguinte os de Asdode, eis que Dagom estava caído com o rosto em terra diante da arca do Senhor; e tomaram a Dagom, e tornaram a pô-lo no seu lugar.

[[v9-5-4]]

^<<v9-5-4,4>>^ E, levantando-se eles de madrugada no dia seguinte, eis que Dagom estava caído com o rosto em terra diante da arca do Senhor; e a cabeça de Dagom e ambas as suas mãos estavam cortadas sobre o limiar; somente o tronco ficou a Dagom.

[[v9-5-5]]

^<<v9-5-5,5>>^ Pelo que nem os sacerdotes de Dagom, nem nenhum de todos os que entram na casa de Dagom, pisam o limiar de Dagom em Asdode, até o dia de hoje.

[[v9-5-6]]

^<<v9-5-6,6>>^ Entretanto a mão do Senhor se agravou sobre os de Asdode, e os assolou, e os feriu com tumores, a Asdode e aos seus termos.

[[v9-5-7]]

^<<v9-5-7,7>>^ O que tendo visto os homens de Asdode, disseram: Não fique conosco a arca do Deus de Israel, pois a sua mão é dura sobre nós, e sobre Dagom, nosso deus.

[[v9-5-8]]

^<<v9-5-8,8>>^ Pelo que enviaram mensageiros e congregaram a si todos os chefes dos filisteus, e disseram: Que faremos nós da arca do Deus de Israel? Responderam: Seja levada para Gate. Assim levaram para lá a arca do Deus de Israel.

[[v9-5-9]]

^<<v9-5-9,9>>^ E desde que a levaram para lá, a mão do Senhor veio contra aquela cidade, causando grande pânico; pois feriu aos homens daquela cidade, desde o pequeno até o grande, e nasceram-lhes tumores.

[[v9-5-10]]

^<<v9-5-10,10>>^ Então enviaram a arca de Deus a Ecrom. Sucedeu porém que, vindo a arca de Deus a Ecrom, os de Ecrom exclamaram, dizendo: Transportaram para nós a arca de Deus de Israel, para nos matar a nós e ao nosso povo.

[[v9-5-11]]

^<<v9-5-11,11>>^ Enviaram, pois, mensageiros, e congregaram a todos os chefes dos filisteus, e disseram: Enviai daqui a arca do Deus de Israel, e volte ela para o seu lugar, para que não nos mate a nós e ao nosso povo. Porque havia pânico mortal em toda a cidade, e a mão de Deus muito se agravara sobre ela.

[[v9-5-12]]

^<<v9-5-12,12>>^ Pois os homens que não morriam eram feridos com tumores; de modo que o clamor da cidade subia até o céu.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]