include::./index.adoc[]

[[v9-4-0]]
=== 1 Samuel, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-4-1]]

^<<v9-4-1,1>>^ Ora, saiu Israel à batalha contra os filisteus, e acampou-se perto de Ebenézer; e os filisteus se acamparam junto a Afeque.

[[v9-4-2]]

^<<v9-4-2,2>>^ E os filisteus se dispuseram em ordem de batalha contra Israel; e, travada a peleja, Israel foi ferido diante dos filisteus, que mataram no campo cerca de quatro mil homens do exército.

[[v9-4-3]]

^<<v9-4-3,3>>^ Quando o povo voltou ao arraial, disseram os anciãos de Israel: Por que nos feriu o Senhor hoje diante dos filisteus? Tragamos para nós de Siló a arca do pacto do Senhor, para que ela venha para o meio de nós, e nos livre da mão de nossos inimigos.

[[v9-4-4]]

^<<v9-4-4,4>>^ Enviou, pois, o povo a Siló, e trouxeram de lá a arca do pacto do Senhor dos exércitos, que se assenta sobre os querubins; e os dois filhos de Eli, Hofni e Finéias, estavam ali com a arca do pacto de Deus.

[[v9-4-5]]

^<<v9-4-5,5>>^ Quando a arca do pacto do Senhor chegou ao arraial, prorrompeu todo o Israel em grandes gritos, de modo que a terra vibrou.

[[v9-4-6]]

^<<v9-4-6,6>>^ E os filisteus, ouvindo o som da gritaria, disseram: Que quer dizer esta grande vozearia no arraial dos hebreus? Quando souberam que a arca do Senhor havia chegado ao arraial,

[[v9-4-7]]

^<<v9-4-7,7>>^ os filisteus se atemorizaram; e diziam: Os deuses vieram ao arraial. Diziam mais: Ai de nós! porque nunca antes sucedeu tal coisa.

[[v9-4-8]]

^<<v9-4-8,8>>^ Ai de nós! quem nos livrará da mão destes deuses possantes? Estes são os deuses que feriram aos egípcios com toda sorte de pragas no deserto.

[[v9-4-9]]

^<<v9-4-9,9>>^ Esforçai-vos, e portai-vos varonilmente, ó filisteus, para que porventura não venhais a ser escravos dos hebreus, como eles o foram vossos; portai-vos varonilmente e pelejai.

[[v9-4-10]]

^<<v9-4-10,10>>^ Então pelejaram os filisteus, e Israel foi derrotado, fugindo cada um para a sua tenda; e houve mui grande matança, pois caíram de Israel trinta mil homens de infantaria.

[[v9-4-11]]

^<<v9-4-11,11>>^ Também foi tomada a arca de Deus, e os dois filhos de Eli, Hofni e Finéias, foram mortos.

[[v9-4-12]]

^<<v9-4-12,12>>^ Então um homem de Benjamim, correndo do campo de batalha chegou no mesmo dia a Siló, com as vestes rasgadas e terra sobre a cabeça.

[[v9-4-13]]

^<<v9-4-13,13>>^ Ao chegar ele, estava Eli sentado numa cadeira ao pé do caminho vigiando, porquanto o seu coração estava tremendo pela arca de Deus. E quando aquele homem chegou e anunciou isto na cidade, a cidade toda prorrompeu em lamentações.

[[v9-4-14]]

^<<v9-4-14,14>>^ E Eli, ouvindo a voz do lamento, perguntou: Que quer dizer este alvoroço? Então o homem, apressando-se, chegou e o anunciou a Eli.

[[v9-4-15]]

^<<v9-4-15,15>>^ Ora, Eli tinha noventa e oito anos; e os seus olhos haviam cegado, de modo que já não podia ver.

[[v9-4-16]]

^<<v9-4-16,16>>^ E disse aquele homem a Eli: Estou vindo do campo de batalha, donde fugi hoje mesmo. Perguntou Eli: Que foi que sucedeu, meu filho?

[[v9-4-17]]

^<<v9-4-17,17>>^ Então respondeu o que trazia as novas, e disse: Israel fugiu de diante dos filisteus, e houve grande matança entre o povo; além disto, também teus dois filhos, Hofni e Finéias, são mortos, e a arca de Deus é tomada.

[[v9-4-18]]

^<<v9-4-18,18>>^ Quando ele fez menção da arca de Deus, Eli caiu da cadeira para trás, junto à porta, e quebrou-se-lhe o pescoço, e morreu, porquanto era homem velho e pesado. Ele tinha julgado a Israel quarenta anos.

[[v9-4-19]]

^<<v9-4-19,19>>^ E estando sua nora, a mulher de Finéias, grávida e próxima ao parto, e ouvindo estas novas, de que a arca de Deus era tomada, e de que seu sogro e seu marido eram mortos, encurvou-se e deu à luz, porquanto as dores lhe sobrevieram.

[[v9-4-20]]

^<<v9-4-20,20>>^ E, na hora em que ia morrendo, disseram as mulheres que estavam com ela: Não temas, pois tiveste um filho. Ela, porém, não respondeu, nem deu atenção a isto.

[[v9-4-21]]

^<<v9-4-21,21>>^ E chamou ao menino de Icabô, dizendo: De Israel se foi a glória! Porque fora tomada a arca de Deus, e por causa de seu sogro e de seu marido.

[[v9-4-22]]

^<<v9-4-22,22>>^ E disse: De Israel se foi a glória, pois é tomada a arca de Deus.

'''

xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[&#60; Capítulo Anterior] | <<v9-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[Próximo Capítulo &#62;]