include::./index.adoc[]

[[v9-24-0]]
=== 1 Samuel, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-24-1]]

^<<v9-24-1,1>>^ Ora, quando Saul voltou de perseguir os filisteus, foi-lhe dito: Eis que Davi está no deserto de En-Gedi.

[[v9-24-2]]

^<<v9-24-2,2>>^ Então tomou Saul três mil homens, escolhidos dentre todo o Israel, e foi em busca de Davi e dos seus homens, até sobre as penhas das cabras montesas.

[[v9-24-3]]

^<<v9-24-3,3>>^ E chegou no caminho a uns currais de ovelhas, onde havia uma caverna; e Saul entrou nela para aliviar o ventre. Ora Davi e os seus homens estavam sentados na parte interior da caverna.

[[v9-24-4]]

^<<v9-24-4,4>>^ Então os homens de Davi lhe disseram: Eis aqui o dia do qual o Senhor te disse: Eis que entrego o teu inimigo nas tuas mãos; far-lhe-ás como parecer bem aos teus olhos. Então Davi se levantou, e de mansinho cortou a orla do manto de Saul.

[[v9-24-5]]

^<<v9-24-5,5>>^ Sucedeu, porém, que depois doeu o coração de Davi, por ter cortado a orla do manto de Saul.

[[v9-24-6]]

^<<v9-24-6,6>>^ E disse aos seus homens: O Senhor me guarde de que eu faça tal coisa ao meu senhor, ao ungido do Senhor, que eu estenda a minha mão contra ele, pois é o ungido do Senhor.

[[v9-24-7]]

^<<v9-24-7,7>>^ com essas palavras Davi conteve os seio chegando para se permitiu que se levantassem contra Saul. E Saul se levantou da caverna, e prosseguiu o seu caminho.

[[v9-24-8]]

^<<v9-24-8,8>>^ Depois também Davi se levantou e, saindo da caverna, gritou por detrás de Saul, dizendo: Ó rei, meu senhor! Quando Saul olhou para trás, Davi se inclinou com o rosto em terra e lhe fez reverência.

[[v9-24-9]]

^<<v9-24-9,9>>^ Então disse Davi a Saul: por que dás ouvidos às palavras dos homens que dizem: Davi procura fazer-te mal?

[[v9-24-10]]

^<<v9-24-10,10>>^ Eis que os teus olhos acabam de ver que o Senhor hoje te pôs em minhas mãos nesta caverna; e alguns disseram que eu te matasse, porém a minha mão te poupou; pois eu disse: Não estenderei a minha mão contra o meu senhor, porque é o ungido do Senhor.

[[v9-24-11]]

^<<v9-24-11,11>>^ Olha, meu pai, vê aqui a orla do teu manto na minha mão, pois cortando-te eu a orla do manto, não te matei. Considera e vê que não há na minha mão nem mal nem transgressão alguma, e que não pequei contra ti, ainda que tu andes à caça da minha vida para ma tirares.

[[v9-24-12]]

^<<v9-24-12,12>>^ Julgue o Senhor entre mim e ti, e vingue-me o Senhor de ti; a minha mão, porém, não será contra ti.

[[v9-24-13]]

^<<v9-24-13,13>>^ Como diz o provérbio dos antigos: Dos ímpios procede a impiedade. A minha mão, porém, não será contra ti.

[[v9-24-14]]

^<<v9-24-14,14>>^ Após quem saiu o rei de Israel? a quem persegues tu? A um cão morto, a uma pulga!

[[v9-24-15]]

^<<v9-24-15,15>>^ Seja, pois, o Senhor juiz, e julgue entre mim e ti; e veja, e advogue a minha causa, e me livre da tua mão.

[[v9-24-16]]

^<<v9-24-16,16>>^ Acabando Davi de falar a Saul todas estas palavras, perguntou Saul: E esta a tua voz, meu filho Davi? Então Saul levantou a voz e chorou.

[[v9-24-17]]

^<<v9-24-17,17>>^ E disse a Davi: Tu és mais justo do que eu, pois me recompensaste com bem, e eu te recompensei com mal.

[[v9-24-18]]

^<<v9-24-18,18>>^ E tu mostraste hoje que procedeste bem para comigo, por isso que, havendo-me o Senhor entregado na tua mão, não me mataste.

[[v9-24-19]]

^<<v9-24-19,19>>^ Pois, quem há que, encontrando o seu inimigo, o deixará ir o seu caminho? O Senhor, pois, te pague com bem, pelo que hoje me fizeste.

[[v9-24-20]]

^<<v9-24-20,20>>^ Agora, pois, sei que certamente hás de reinar, e que o reino de Israel há de se firmar na tua mão.

[[v9-24-21]]

^<<v9-24-21,21>>^ Portanto jura-me pelo Senhor que não desarraigarás a minha descendência depois de mim, nem extinguirás o meu nome da casa de meu pai.

[[v9-24-22]]

^<<v9-24-22,22>>^ Então jurou Davi a Saul. E foi Saul para sua casa, mas Davi e os seus homens subiram ao lugar forte.

'''

xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[&#60; Capítulo Anterior] | <<v9-24-0,Topo>> | xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[Próximo Capítulo &#62;]