include::./index.adoc[]

[[v9-10-0]]
=== 1 Samuel, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-10-1]]

^<<v9-10-1,1>>^ Então Samuel tomou um vaso de azeite, e o derramou sobre a cabeça de Saul, e o beijou, e disse: Porventura não te ungiu o Senhor para ser príncipe sobre a sua herança?

[[v9-10-2]]

^<<v9-10-2,2>>^ Quando te apartares hoje de mim, encontrarás dois homens junto ao sepulcro de Raquel, no termo de Benjamim, em Zelza, os quais te dirão: Acharam-se as jumentas que foste buscar, e eis que já o teu pai deixou de pensar nas jumentas, e anda aflito por causa de ti, dizendo: Que farei eu por meu filho?

[[v9-10-3]]

^<<v9-10-3,3>>^ Então dali passarás mais adiante, e chegarás ao carvalho de Tabor; ali te encontrarão três homens, que vão subindo a Deus, a Betel, levando um três cabritos, outro três formas de pão, e o outro um odre de vinho.

[[v9-10-4]]

^<<v9-10-4,4>>^ Eles te saudarão, e te darão dois pães, que receberás das mãos deles.

[[v9-10-5]]

^<<v9-10-5,5>>^ Depois chegarás ao outeiro de Deus, onde está a guarnição dos filisteus; ao entrares ali na cidade, encontrarás um grupo de profetas descendo do alto, precedido de saltérios, tambores, flautas e harpas, e eles profetizando.

[[v9-10-6]]

^<<v9-10-6,6>>^ E o Espírito do Senhor se apoderará de ti, e profetizarás com eles, e serás transformado em outro homem.

[[v9-10-7]]

^<<v9-10-7,7>>^ Quando estes sinais te vierem, faze o que achar a tua mão para fazer, pois Deus é contigo.

[[v9-10-8]]

^<<v9-10-8,8>>^ Tu, porém, descerás adiante de mim a Gilgal, e eis que eu descerei a ter contigo, para oferecer holocaustos e sacrifícios de ofertas pacíficas. Esperarás sete dias, até que eu vá ter contigo e te declare o que hás de fazer.

[[v9-10-9]]

^<<v9-10-9,9>>^ Ao virar Saul as costas para se apartar de Samuel, Deus lhe mudou o coração em outro; e todos esses sinais aconteceram naquele mesmo dia.

[[v9-10-10]]

^<<v9-10-10,10>>^ Quando eles iam chegando ao outeiro, eis que um grupo de profetas lhes saiu ao encontro; e o Espírito de Deus se apoderou de Saul, e ele profetizou no meio deles.

[[v9-10-11]]

^<<v9-10-11,11>>^ Todos os que o tinham conhecido antes, ao verem que ele profetizava com os profetas, diziam uns aos outros: Que é que sucedeu ao filho de Quis? Está também Saul entre os profetas?

[[v9-10-12]]

^<<v9-10-12,12>>^ Então um homem dali respondeu, e disse: Pois quem é o pai deles? Pelo que se tornou em provérbio: Está também Saul entre os profetas?

[[v9-10-13]]

^<<v9-10-13,13>>^ Tendo ele acabado de profetizar, foi ao alto.

[[v9-10-14]]

^<<v9-10-14,14>>^ Depois o tio de Saul perguntou-lhe, a ele e ao seu moço: Aonde fostes?: Respondeu ele: Procurar as jumentas; e, não as tendo encontrado, fomos ter com Samuel.

[[v9-10-15]]

^<<v9-10-15,15>>^ Disse mais o tio de Saul: Declara-me, peço-te, o que vos disse Samuel.

[[v9-10-16]]

^<<v9-10-16,16>>^ Ao que respondeu Saul a seu tio: Declarou-nos, seguramente, que as jumentas tinham sido encontradas. Mas quanto ao assunto do reino, de que Samuel falara, nada lhe declarou.

[[v9-10-17]]

^<<v9-10-17,17>>^ Então Samuel convocou o povo ao Senhor em Mizpá;

[[v9-10-18]]

^<<v9-10-18,18>>^ e disse aos filhos de Israel: Assim diz o Senhor Deus de Israel: Eu fiz subir a Israel do Egito, e vos livrei da mão dos egípcios e da mão de todos os reinos que vos oprimiam.

[[v9-10-19]]

^<<v9-10-19,19>>^ Mas vós hoje rejeitastes a vosso Deus, àquele que vos livrou de todos os vossos males e angústias, e lhe dissestes: Põe um rei sobre nós. Agora, pois, ponde-vos perante o Senhor, segundo as vossas tribos e segundo os vossos milhares.

[[v9-10-20]]

^<<v9-10-20,20>>^ Tendo, pois, Samuel feito chegar todas as tribos de Israel, foi tomada por sorte a tribo de Benjamim.

[[v9-10-21]]

^<<v9-10-21,21>>^ E, quando fez chegar a tribo de Benjamim segundo as suas famílias, foi tomada a família de Matri, e dela foi tomado Saul, filho de Quis; e o procuraram, mas não foi encontrado.

[[v9-10-22]]

^<<v9-10-22,22>>^ Pelo que tornaram a perguntar ao Senhor: Não veio o homem ainda para cá? E respondeu o Senhor: Eis que se escondeu por entre a bagagem:

[[v9-10-23]]

^<<v9-10-23,23>>^ Correram, pois, e o trouxeram dali; e estando ele no meio do povo, sobressaía em altura a todo o povo desde os ombros para cima.

[[v9-10-24]]

^<<v9-10-24,24>>^ Então disse Samuel a todo o povo: Vedes já a quem o Senhor escolheu: Não há entre o povo nenhum semelhante a ele. Então todo o povo o aclamou, dizendo: Viva o rei;

[[v9-10-25]]

^<<v9-10-25,25>>^ Também declarou Samuel ao povo a lei do reino, e a escreveu num livro, e pô-lo perante o Senhor. Então Samuel despediu todo o povo, cada um para sua casa.

[[v9-10-26]]

^<<v9-10-26,26>>^ E foi também Saul para sua casa em Gibeá; e foram com ele homens de valor, aqueles cujo coração Deus tocara.

[[v9-10-27]]

^<<v9-10-27,27>>^ Mas alguns homens ímpios disseram: Como pode este homem nos livrar? E o desprezaram, e não lhe trouxeram presentes; porém ele se fez como surdo.

'''

xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[&#60; Capítulo Anterior] | <<v9-10-0,Topo>> | xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[Próximo Capítulo &#62;]