include::./index.adoc[]

[[v9-23-0]]
=== 1 Samuel, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-23-1]]

^<<v9-23-1,1>>^ Ora, foi anunciado a Davi: Eis que os filisteus pelejam contra Queila e saqueiam as eiras.

[[v9-23-2]]

^<<v9-23-2,2>>^ Pelo que consultou Davi ao Senhor, dizendo: Irei eu, e ferirei a esses filisteus? Respondeu o Senhor a Davi: Vai, fere aos filisteus e salva a Queila.

[[v9-23-3]]

^<<v9-23-3,3>>^ Mas os homens de Davi lhe disseram: Eis que tememos aqui em Judá, quanta mais se formos a Queila, contra o exército dos filisteus!

[[v9-23-4]]

^<<v9-23-4,4>>^ Davi, pois, tornou a consultar ao Senhor, e o Senhor lhe respondeu: Levanta-te, desce a Queila, porque eu hei de entregar os filisteus na tua mão.

[[v9-23-5]]

^<<v9-23-5,5>>^ Então Davi partiu com os seus homens para Queila, pelejou contra os filisteus, levou-lhes o gado, e fez grande matança entre eles; assim Davi salvou os moradores de Queila.

[[v9-23-6]]

^<<v9-23-6,6>>^ Ora, quando Abiatar, filho de Aimeleque, fugiu para Davi, a Queila, desceu com um éfode na mão.

[[v9-23-7]]

^<<v9-23-7,7>>^ Então foi anunciado a Saul que Davi tinha ido a Queila; e disse Saul: Deus o entregou nas minhas mãos; pois está encerrado, porque entrou numa cidade que tem portas e ferrolhos.

[[v9-23-8]]

^<<v9-23-8,8>>^ E convocou todo o povo à peleja, para descerem a Queila, e cercar a Davi e os seus homens.

[[v9-23-9]]

^<<v9-23-9,9>>^ Sabendo, pois, Davi que Saul maquinava este mal contra ele, disse a Abiatar, sacerdote: Traze aqui o éfode.

[[v9-23-10]]

^<<v9-23-10,10>>^ E disse Davi: Ó Senhor, Deus de Israel, teu servo acaba de ouvir que Saul procura vir a Queila, para destruir a cidade por causa de mim.

[[v9-23-11]]

^<<v9-23-11,11>>^ Entregar-me-ão os cidadãos de Queila na mão dele? descerá Saul, como o teu servo tem ouvido? Ah, Senhor Deus de Israel! faze-o saber ao teu servo. Respondeu o Senhor: Descerá.

[[v9-23-12]]

^<<v9-23-12,12>>^ Disse mais Davi: Entregar-me-ão os cidadãos de Queila, a mim e aos meus homens, nas mãos de Saul? E respondeu o Senhor: Entregarão.

[[v9-23-13]]

^<<v9-23-13,13>>^ Levantou-se, então, Davi com os seus homens, cerca de seiscentos, e saíram de Queila, e foram-se aonde puderam. Saul, quando lhe foi anunciado que Davi escapara de Queila, deixou de sair contra ele.

[[v9-23-14]]

^<<v9-23-14,14>>^ E Davi ficou no deserto, em lugares fortes, permanecendo na região montanhosa no deserto de Zife. Saul o buscava todos os dias, porém Deus não o entregou na sua mão.

[[v9-23-15]]

^<<v9-23-15,15>>^ Vendo, pois, Davi que Saul saíra à busca da sua vida, esteve no deserto de Zife, em Hores.

[[v9-23-16]]

^<<v9-23-16,16>>^ Então se levantou Jônatas, filho de Saul, e foi ter com Davi em Hores, e o confortou em Deus;

[[v9-23-17]]

^<<v9-23-17,17>>^ e disse-lhe: Não temas; porque não te achará a mão de Saul, meu pai; porém tu reinarás sobre Israel, e eu serei contigo o segundo; o que também Saul, meu pai, bem sabe.

[[v9-23-18]]

^<<v9-23-18,18>>^ E ambos fizeram aliança perante o Senhor; Davi ficou em Hores, e Jônatas, voltou para sua casa.

[[v9-23-19]]

^<<v9-23-19,19>>^ Então subiram os zifeus a Saul, a Gibeá, dizendo: Não se escondeu Davi entre nós, nos lugares fortes em Hores, no outeiro de Haquilá, que está à mão direita de Jesimom?

[[v9-23-20]]

^<<v9-23-20,20>>^ Agora, pois, ó rei, desce apressadamente, conforme todo o desejo da tua alma; a nós nos cumpre entregá-lo nas mãos do rei.

[[v9-23-21]]

^<<v9-23-21,21>>^ Então disse Saul: Benditos sejais vós do Senhor, porque vos compadecestes de mim:

[[v9-23-22]]

^<<v9-23-22,22>>^ Ide, pois, informai-vos ainda melhor; sabei e notai o lugar que ele freqüenta, e quem o tenha visto ali; porque me foi dito que é muito astuto.

[[v9-23-23]]

^<<v9-23-23,23>>^ Pelo que atentai bem, e informai-vos acerca de todos os esconderijos em que ele se oculta; e então voltai para mim com notícias exatas, e eu irei convosco. E há de ser que, se estiver naquela terra, eu o buscarei entre todos os milhares de Judá.

[[v9-23-24]]

^<<v9-23-24,24>>^ Eles, pois, se levantaram e foram a Zife adiante de Saul; Davi, porém, e os seus homens estavam no deserto de Maom, na campina ao sul de Jesimom.

[[v9-23-25]]

^<<v9-23-25,25>>^ E Saul e os seus homens foram em busca dele. Sendo isso anunciado a Davi, desceu ele à penha que está no deserto de Maom. Ouvindo-o Saul, foi ao deserto de Maom, a perseguir Davi.

[[v9-23-26]]

^<<v9-23-26,26>>^ Saul ia de uma banda do monte, e Davi e os seus homens da outra banda. E Davi se apressava para escapar, por medo de Saul, porquanto Saul e os seus homens iam cercando a Davi e aos seus homens, para os prender.

[[v9-23-27]]

^<<v9-23-27,27>>^ Nisso veio um mensageiro a Saul, dizendo: Apressa-te, e vem, porque os filisteus acabam de invadir a terra.

[[v9-23-28]]

^<<v9-23-28,28>>^ Pelo que Saul voltou de perseguir a Davi, e se foi ao encontro dos filisteus. Por esta razão aquele lugar se chamou Selá-Hamalecote.

[[v9-23-29]]

^<<v9-23-29,29>>^ Depois disto, Davi subiu e ficou nos lugares fortes de En-Gedi.

'''

xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]