include::./index.adoc[]

[[v9-2-0]]
=== 1 Samuel, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-2-1]]

^<<v9-2-1,1>>^ Então Ana orou, dizendo: O meu coração exulta no Senhor; o meu poder está exaltado no Senhor; a minha boca dilata-se contra os meus inimigos, porquanto me regozijo na tua salvação.

[[v9-2-2]]

^<<v9-2-2,2>>^ Ninguém há santo como o Senhor; não há outro fora de ti; não há rocha como a nosso Deus.

[[v9-2-3]]

^<<v9-2-3,3>>^ Não faleis mais palavras tão altivas, nem saia da vossa boca a arrogância; porque o Senhor é o Deus da sabedoria, e por ele são pesadas as ações.

[[v9-2-4]]

^<<v9-2-4,4>>^ Os arcos dos fortes estão quebrados, e os fracos são cingidos de força.

[[v9-2-5]]

^<<v9-2-5,5>>^ Os que eram fartos se alugam por pão, e deixam de ter fome os que eram famintos; até a estéril teve sete filhos, e a que tinha muitos filhos enfraquece.

[[v9-2-6]]

^<<v9-2-6,6>>^ O Senhor é o que tira a vida e a dá; faz descer ao Seol e faz subir dali.

[[v9-2-7]]

^<<v9-2-7,7>>^ O Senhor empobrece e enriquece; abate e também exalta.

[[v9-2-8]]

^<<v9-2-8,8>>^ Levanta do pó o pobre, do monturo eleva o necessitado, para os fazer sentar entre os príncipes, para os fazer herdar um trono de glória; porque do Senhor são as colunas da terra, sobre elas pôs ele o mundo.

[[v9-2-9]]

^<<v9-2-9,9>>^ Ele guardará os pés dos seus santos, porém os ímpios ficarão mudos nas trevas, porque o homem não prevalecerá pela força.

[[v9-2-10]]

^<<v9-2-10,10>>^ Os que contendem com o Senhor serão quebrantados; desde os céus trovejará contra eles. O Senhor julgará as extremidades da terra; dará força ao seu rei, e exaltará o poder do seu ungido.

[[v9-2-11]]

^<<v9-2-11,11>>^ Então Elcana se retirou a Ramá, à sua casa. O menino, porém, ficou servindo ao Senhor perante e sacerdote Eli.

[[v9-2-12]]

^<<v9-2-12,12>>^ Ora, os filhos de Eli eram homens ímpios; não conheciam ao Senhor.

[[v9-2-13]]

^<<v9-2-13,13>>^ Porquanto o costume desses sacerdotes para com o povo era que, oferecendo alguém um sacrifício, e estando-se a cozer a carne, vinha o servo do sacerdote, tendo na mão um garfo de três dentes,

[[v9-2-14]]

^<<v9-2-14,14>>^ e o metia na panela, ou no tacho, ou no caldeirão, ou na marmita; e tudo quanto a garfo tirava, o sacerdote tomava para si. Assim faziam a todos os de Israel que chegavam ali em Siló.

[[v9-2-15]]

^<<v9-2-15,15>>^ Também, antes de queimarem a gordura, vinha o servo do sacerdote e dizia ao homem que sacrificava: Dá carne de assar para o sacerdote; porque não receberá de ti carne cozida, mas crua.

[[v9-2-16]]

^<<v9-2-16,16>>^ se lhe respondia o homem: Sem dúvida, logo há de ser queimada a gordura e depois toma quanto desejar a tua alma; então ele lhe dizia: Não hás de dá-la agora; se não, à força a tomarei.

[[v9-2-17]]

^<<v9-2-17,17>>^ Era, pois, muito grande o pecado destes mancebos perante o Senhor, porquanto os homens vieram a desprezar a oferta do Senhor.

[[v9-2-18]]

^<<v9-2-18,18>>^ Samuel, porém, ministrava perante o Senhor, sendo ainda menino, vestido de um éfode de linho.

[[v9-2-19]]

^<<v9-2-19,19>>^ E sua mãe lhe fazia de ano em ano uma túnica pequena, e lha trazia quando com seu marido subia para oferecer o sacrifício anual.

[[v9-2-20]]

^<<v9-2-20,20>>^ Então Eli abençoava a Elcana e a sua mulher, e dizia: O Senhor te dê desta mulher descendência, pelo empréstimo que fez ao Senhor. E voltavam para o seu lugar.

[[v9-2-21]]

^<<v9-2-21,21>>^ Visitou, pois, o Senhor a Ana, que concebeu, e teve três filhos e duas filhas. Entrementes, o menino Samuel crescia diante do Senhor.

[[v9-2-22]]

^<<v9-2-22,22>>^ Eli era já muito velho; e ouvia tudo quanto seus filhos faziam a todo o Israel, e como se deitavam com as mulheres que ministravam à porta da tenda da revelação.

[[v9-2-23]]

^<<v9-2-23,23>>^ E disse-lhes: Por que fazeis tais coisas? pois ouço de todo este povo os vossos malefícios.

[[v9-2-24]]

^<<v9-2-24,24>>^ Não, filhos meus, não é boa fama esta que ouço. Fazeis transgredir o povo do Senhor.

[[v9-2-25]]

^<<v9-2-25,25>>^ Se um homem pecar contra outro, Deus o julgará; mas se um homem pecar contra o Senhor, quem intercederá por ele? Todavia eles não ouviram a voz de seu pai, porque o Senhor os queria destruir.

[[v9-2-26]]

^<<v9-2-26,26>>^ E o menino Samuel ia crescendo em estatura e em graça diante do Senhor, como também diante dos homens.

[[v9-2-27]]

^<<v9-2-27,27>>^ Veio um homem de Deus a Eli, e lhe disse: Assim diz o Senhor: Não me revelei, na verdade, à casa de teu pai, estando eles ainda no Egito, sujeitos à casa de Faraó?

[[v9-2-28]]

^<<v9-2-28,28>>^ E eu o escolhi dentre todas as tribos de Israel para ser o meu sacerdote, para subir ao meu altar, para queimar o incenso, e para trazer o éfode perante mim; e dei à casa de teu pai todas as ofertas queimadas dos filhos de Israel.

[[v9-2-29]]

^<<v9-2-29,29>>^ Por que desprezais o meu sacrifício e a minha oferta, que ordenei se fizessem na minha morada, e por que honras a teus filhos mais de que a mim, de modo a vos engordardes do principal de todas as ofertas do meu povo Israel?

[[v9-2-30]]

^<<v9-2-30,30>>^ Portanto, diz o Senhor Deus de Israel: Na verdade eu tinha dito que a tua casa e a casa de teu pai andariam diante de mim perpetuamente. Mas agora o Senhor diz: Longe de mim tal coisa, porque honrarei aos que me honram, mas os que me desprezam serão desprezados.

[[v9-2-31]]

^<<v9-2-31,31>>^ Eis que vêm dias em que cortarei o teu braço e o braço da casa de teu pai, para que não haja mais ancião algum em tua casa.

[[v9-2-32]]

^<<v9-2-32,32>>^ E tu, na angústia, olharás com inveja toda a prosperidade que hei de trazer sobre Israel; e não haverá por todos os dias ancião algum em tua casa.

[[v9-2-33]]

^<<v9-2-33,33>>^ O homem da tua linhagem a quem eu não desarraigar do meu altar será para consumir-te os olhos e para entristecer-te a alma; e todos es descendentes da tua casa morrerão pela espada dos homens.

[[v9-2-34]]

^<<v9-2-34,34>>^ E te será por sinal o que sobrevirá a teus dois filhos, a Hofni e a Finéias; ambos morrerão no mesmo dia.

[[v9-2-35]]

^<<v9-2-35,35>>^ E eu suscitarei para mim um sacerdote fiel, que fará segundo o que está no meu coração e na minha mente. Edificar-lhe-ei uma casa duradoura, e ele andará sempre diante de meu ungido.

[[v9-2-36]]

^<<v9-2-36,36>>^ Também todo aquele que ficar de resto da tua casa virá a inclinar-se diante dele por uma moeda de prata e por um pedaço de pão, e dirá: Rogo-te que me admitas a algum cargo sacerdotal, para que possa comer um bocado de pão.

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]