include::./index.adoc[]

[[v9-15-0]]
=== 1 Samuel, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-15-1]]

^<<v9-15-1,1>>^ Disse Samuel a Saul: Enviou-me o Senhor a ungir-te rei sobre o seu povo, sobre Israel; ouve, pois, agora as palavras do Senhor.

[[v9-15-2]]

^<<v9-15-2,2>>^ Assim diz o Senhor dos exércitos: Castigarei a Amaleque por aquilo que fez a Israel quando se lhe opôs no caminho, ao subir ele do Egito.

[[v9-15-3]]

^<<v9-15-3,3>>^ Vai, pois, agora e fere a Amaleque, e o destrói totalmente com tudo o que tiver; não o poupes, porém matarás homens e mulheres, meninos e crianças de peito, bois e ovelhas, camelos e jumentos.

[[v9-15-4]]

^<<v9-15-4,4>>^ Então Saul convocou o povo, e os contou em Telaim, duzentos mil homens de infantaria, e mais dez mil dos de Judá.

[[v9-15-5]]

^<<v9-15-5,5>>^ Chegando, pois, Saul à cidade de Amaleque, pôs uma emboscada no vale.

[[v9-15-6]]

^<<v9-15-6,6>>^ E disse Saul aos queneus: Ide, retirai-vos, saí do meio dos amalequitas, para que eu não vos destrua juntamente com eles; porque vós usastes de misericórdia com todos os filhos de Israel, quando subiram do Egito. Retiraram-se, pois, os queneus do meio dos amalequitas.

[[v9-15-7]]

^<<v9-15-7,7>>^ Depois Saul feriu os amalequitas desde Havilá até chegar a Sur, que está defronte do Egito.

[[v9-15-8]]

^<<v9-15-8,8>>^ E tomou vivo a Agague, rei dos amalequitas, porém a todo o povo destruiu ao fio da espada.

[[v9-15-9]]

^<<v9-15-9,9>>^ Mas Saul e o povo pouparam a Agague, como também ao melhor das ovelhas, dos bois, e dos animais engordados, e aos cordeiros, e a tudo o que era bom, e não os quiseram destruir totalmente; porém a tudo o que era vil e desprezível destruíram totalmente.

[[v9-15-10]]

^<<v9-15-10,10>>^ Então veio a palavra do Senhor a Samuel, dizendo:

[[v9-15-11]]

^<<v9-15-11,11>>^ Arrependo-me de haver posto a Saul como rei; porquanto deixou de me seguir, e não cumpriu as minhas palavras. Então Samuel se contristou, e clamou ao Senhor a noite toda.

[[v9-15-12]]

^<<v9-15-12,12>>^ E Samuel madrugou para encontrar-se com Saul pela manhã; e foi dito a Samuel: Já chegou Saul ao Carmelo, e eis que levantou para si numa coluna e, voltando, passou e desceu a Gilgal.

[[v9-15-13]]

^<<v9-15-13,13>>^ Veio, pois, Samuel ter com Saul, e Saul lhe disse: Bendito sejas do Senhor; já cumpri a palavra do Senhor.

[[v9-15-14]]

^<<v9-15-14,14>>^ Então perguntou Samuel: Que quer dizer, pois, este balido de ovelhas que chega aos meus ouvidos, e o mugido de bois que ouço?

[[v9-15-15]]

^<<v9-15-15,15>>^ Ao que respondeu Saul: De Amaleque os trouxeram, porque o povo guardou o melhor das ovelhas e dos bois, para os oferecer ao Senhor teu Deus; o resto, porém, destruímo-lo totalmente.

[[v9-15-16]]

^<<v9-15-16,16>>^ Então disse Samuel a Saul: Espera, e te declararei o que o Senhor me disse esta noite. Respondeu-lhe Saul: Fala.

[[v9-15-17]]

^<<v9-15-17,17>>^ Prosseguiu, pois, Samuel: Embora pequeno aos teus próprios olhos, porventura não foste feito o cabeça das tribos de Israel? O Senhor te ungiu rei sobre Israel;

[[v9-15-18]]

^<<v9-15-18,18>>^ e bem assim te enviou o Senhor a este caminho, e disse: Vai, e destrói totalmente a estes pecadores, os amalequitas, e peleja contra eles, até que sejam aniquilados.

[[v9-15-19]]

^<<v9-15-19,19>>^ Por que, pois, não deste ouvidos à voz do Senhor, antes te lançaste ao despojo, e fizeste o que era mau aos olhos do Senhor?

[[v9-15-20]]

^<<v9-15-20,20>>^ Então respondeu Saul a Samuel: Pelo contrário, dei ouvidos à voz do Senhor, e caminhei no caminho pelo qual o Senhor me enviou, e trouxe a Agague, rei de Amaleque, e aos amalequitas destruí totalmente;

[[v9-15-21]]

^<<v9-15-21,21>>^ mas o povo tomou do despojo ovelhas e bois, o melhor do anátema, para o sacrificar ao Senhor teu Deus em Gilgal.

[[v9-15-22]]

^<<v9-15-22,22>>^ Samuel, porém, disse: Tem, porventura, o Senhor tanto prazer em holocaustos e sacrifícios, como em que se obedeça à voz do Senhor? Eis que o obedecer é melhor do que o sacrificar, e o atender, do que a gordura de carneiros

[[v9-15-23]]

^<<v9-15-23,23>>^ Porque a rebelião é como o pecado de adivinhação, e a obstinação é como a iniqüidade de idolatria. Porquanto rejeitaste a palavra do Senhor, ele também te rejeitou, a ti, para que não sejas rei.

[[v9-15-24]]

^<<v9-15-24,24>>^ Então disse Saul a Samuel: Pequei, porquanto transgredi a ordem do Senhor e as tuas palavras; porque temi ao povo, e dei ouvidos a sua voz.

[[v9-15-25]]

^<<v9-15-25,25>>^ Agora, pois, perdoa o meu pecado, e volta comigo, para que eu adore ao Senhor.

[[v9-15-26]]

^<<v9-15-26,26>>^ Samuel porém disse a Saul: Não voltarei contigo; porquanto rejeitaste a palavra do Senhor, e o Senhor te rejeitou a ti, para que não sejas rei sobre Israel:

[[v9-15-27]]

^<<v9-15-27,27>>^ E, virando-se Samuel para se ir, Saul pegou-lhe pela orla da capa, a qual se rasgou.

[[v9-15-28]]

^<<v9-15-28,28>>^ Então Samuel lhe disse: O Senhor rasgou de ti hoje o reino de Israel, e o deu a um teu próximo, que é melhor do que tu.

[[v9-15-29]]

^<<v9-15-29,29>>^ Também aquele que é a Força de Israel não mente nem se arrepende, por quanto não é homem para que se arrependa.

[[v9-15-30]]

^<<v9-15-30,30>>^ Ao que disse Saul: Pequei; honra-me, porém, agora diante dos anciãos do meu povo, e diante de Israel, e volta comigo, para que eu adore ao Senhor teu Deus.

[[v9-15-31]]

^<<v9-15-31,31>>^ Então, voltando Samuel, seguiu a Saul, e Saul adorou ao Senhor.

[[v9-15-32]]

^<<v9-15-32,32>>^ Então disse Samuel: Trazei-me aqui a Agague, rei dos amalequitas. E Agague veio a ele animosamente; e disse: Certamente já passou a amargura da morte.

[[v9-15-33]]

^<<v9-15-33,33>>^ Disse, porém, Samuel: Assim como a tua espada desfilhou a mulheres, assim ficará desfilhada tua mãe entre as mulheres. E Samuel despedaçou a Agague perante o Senhor em Gilgal.

[[v9-15-34]]

^<<v9-15-34,34>>^ Então Samuel se foi a Ramá; e Saul subiu a sua casa, a Gibeá de Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ Ora, Samuel nunca mais viu a Saul até o dia da sua morte, mas Samuel teve dó de Saul. E o Senhor se arrependeu de haver posto a Saul rei sobre Israel.

'''

xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]