include::./index.adoc[]

[[v9-28-0]]
=== 1 Samuel, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-28-1]]

^<<v9-28-1,1>>^ Naqueles dias ajuntaram os filisteus os seus exércitos para a guerra, para pelejarem contra Israel. Disse Áquis a Davi: Sabe de certo que sairás comigo ao arraial, tu e os teus homens.

[[v9-28-2]]

^<<v9-28-2,2>>^ Respondeu Davi a Áquis: Assim saberás o que o teu servo há de fazer. E disse Áquis a Davi: Por isso te farei para sempre guarda da minha pessoa.

[[v9-28-3]]

^<<v9-28-3,3>>^ Ora, Samuel já havia morrido, e todo o Israel o tinha chorado, e o tinha sepultado e em Ramá, que era a sua cidade. E Saul tinha desterrado es necromantes e os adivinhos.

[[v9-28-4]]

^<<v9-28-4,4>>^ Ajuntando-se, pois, os filisteus, vieram acampar-se em Suném; Saul ajuntou também todo o Israel, e se acamparam em Gilboa.

[[v9-28-5]]

^<<v9-28-5,5>>^ Vendo Saul o arraial dos filisteus, temeu e estremeceu muito o seu coração.

[[v9-28-6]]

^<<v9-28-6,6>>^ Pelo que consultou Saul ao Senhor, porém o Senhor não lhe respondeu, nem por sonhos, nem por Urim, nem por profetas.

[[v9-28-7]]

^<<v9-28-7,7>>^ Então disse Saul aos seus servos: Buscai-me uma necromante, para que eu vá a ela e a consulte. Disseram-lhe os seus servos: Eis que em En-Dor há uma mulher que é necromante.

[[v9-28-8]]

^<<v9-28-8,8>>^ Então Saul se disfarçou, vestindo outros trajes; e foi ele com dois homens, e chegaram de noite à casa da mulher. Disse-lhe Saul: Peço-te que me adivinhes pela necromancia, e me faças subir aquele que eu te disser.

[[v9-28-9]]

^<<v9-28-9,9>>^ A mulher lhe respondeu: Tu bem sabes o que Saul fez, como exterminou da terra os necromantes e os adivinhos; por que, então, me armas um laço à minha vida, para me fazeres morrer?

[[v9-28-10]]

^<<v9-28-10,10>>^ Saul, porém, lhe jurou pelo Senhor, dizendo: Como vive o Senhor, nenhum castigo te sobrevirá por isso.

[[v9-28-11]]

^<<v9-28-11,11>>^ A mulher então lhe perguntou: Quem te farei subir? Respondeu ele: Faze-me subir Samuel.

[[v9-28-12]]

^<<v9-28-12,12>>^ Vendo, pois, a mulher a Samuel, gritou em alta voz, e falou a Saul, dizendo: Por que me enganaste? pois tu mesmo és Saul.

[[v9-28-13]]

^<<v9-28-13,13>>^ Ao que o rei lhe disse: Não temas; que é que vês? Então a mulher respondeu a Saul: Vejo um deus que vem subindo de dentro da terra.

[[v9-28-14]]

^<<v9-28-14,14>>^ Perguntou-lhe ele: Como é a sua figura? E disse ela: Vem subindo um ancião, e está envolto numa capa. Entendendo Saul que era Samuel, inclinou-se com o rosto em terra, e lhe fez reverência.

[[v9-28-15]]

^<<v9-28-15,15>>^ Samuel disse a Saul: Por que me inquietaste, fazendo-me subir? Então disse Saul: Estou muito angustiado, porque os filisteus guerreiam contra mim, e Deus se tem desviado de mim, e já não me responde, nem por intermédio dos profetas nem por sonhos; por isso te chamei, para que me faças saber o que hei de fazer.

[[v9-28-16]]

^<<v9-28-16,16>>^ Então disse Samuel: Por que, pois, me perguntas a mim, visto que o Senhor se tem desviado de ti, e se tem feito teu inimigo?

[[v9-28-17]]

^<<v9-28-17,17>>^ O Senhor te fez como por meu intermédio te disse; pois o Senhor rasgou o reino da tua mão, e o deu ao teu próximo, a Davi.

[[v9-28-18]]

^<<v9-28-18,18>>^ Porquanto não deste ouvidos à voz do Senhor, e não executaste e furor da sua ira contra Amaleque, por isso o Senhor te fez hoje isto.

[[v9-28-19]]

^<<v9-28-19,19>>^ E o Senhor entregará também a Israel contigo na mão dos filisteus. Amanhã tu e teus filhos estareis comigo, e o Senhor entregará o arraial de Israel na mão dos filisteus.

[[v9-28-20]]

^<<v9-28-20,20>>^ Imediatamente Saul caiu estendido por terra, tomado de grande medo por causa das palavras de Samuel; e não houve força nele, porque nada havia comido todo aquele dia e toda aquela noite.

[[v9-28-21]]

^<<v9-28-21,21>>^ Então a mulher se aproximou de Saul e, vendo que estava tão perturbado, disse-lhe: Eis que a tua serva deu ouvidos à tua voz; pus a minha vida na minha mão, dando ouvidos às palavras que disseste.

[[v9-28-22]]

^<<v9-28-22,22>>^ Agora, pois, ouve também tu as palavras da tua serva, e permite que eu ponha um bocado de pão diante de ti; come, para que tenhas forças quando te puseres a caminho.

[[v9-28-23]]

^<<v9-28-23,23>>^ Ele, porém, recusou, dizendo: Não comerei. Mas os seus servos e a mulher o constrangeram, e ele deu ouvidos à sua voz; e levantando-se do chão, sentou-se na cama.

[[v9-28-24]]

^<<v9-28-24,24>>^ Ora, a mulher tinha em casa um bezerro cevado; apressou-se, pois, e o degolou; também tomou farinha, e a amassou, e a cozeu em bolos ázimos.

[[v9-28-25]]

^<<v9-28-25,25>>^ Então pôs tudo diante de Saul e de seus servos; e eles comeram. Depois levantaram-se e partiram naquela mesma noite.

'''

xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[&#60; Capítulo Anterior] | <<v9-28-0,Topo>> | xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[Próximo Capítulo &#62;]