include::./index.adoc[]

[[v9-17-0]]
=== 1 Samuel, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-17-1]]

^<<v9-17-1,1>>^ Ora, os filisteus ajuntaram as suas forças para a guerra e congregaram-se em Socó, que pertence a Judá, e acamparam entre Socó e Azeca, em Efes-Damim.

[[v9-17-2]]

^<<v9-17-2,2>>^ Saul, porém, e os homens de Israel se ajuntaram e acamparam no vale de Elá, e ordenaram a batalha contra os filisteus.

[[v9-17-3]]

^<<v9-17-3,3>>^ Os filisteus estavam num monte de um lado, e os israelitas estavam num monte do outro lado; e entre eles o vale.

[[v9-17-4]]

^<<v9-17-4,4>>^ Então saiu do arraial dos filisteus um campeão, cujo nome era Golias, de Gate, que tinha de altura seis côvados e um palmo.

[[v9-17-5]]

^<<v9-17-5,5>>^ Trazia na cabeça um capacete de bronze, e vestia uma couraça escameada, cujo peso era de cinco mil siclos de bronze.

[[v9-17-6]]

^<<v9-17-6,6>>^ Também trazia grevas de bronze nas pernas, e um dardo de bronze entre os ombros.

[[v9-17-7]]

^<<v9-17-7,7>>^ A haste da sua lança era como o órgão de um tear, e a ponta da sua lança pesava seiscentos siclos de ferro; adiante dele ia o seu escudeiro.

[[v9-17-8]]

^<<v9-17-8,8>>^ Ele, pois, de pé, clamava às fileiras de Israel e dizia-lhes: Por que saístes a ordenar a batalha? Não sou eu filisteu, e vós servos de Saul? Escolhei dentre vós um homem que desça a mim.

[[v9-17-9]]

^<<v9-17-9,9>>^ Se ele puder pelejar comigo e matar-me, seremos vossos servos; porem, se eu prevalecer contra ele e o matar, então sereis nossos servos, e nos servireis.

[[v9-17-10]]

^<<v9-17-10,10>>^ Disse mais o filisteu: Desafio hoje as fileiras de Israel; dai-me um homem, para que nós dois pelejemos.

[[v9-17-11]]

^<<v9-17-11,11>>^ Ouvindo, então, Saul e todo o Israel estas palavras do filisteu, desalentaram-se, e temeram muito.

[[v9-17-12]]

^<<v9-17-12,12>>^ Ora, Davi era filho de um homem efrateu, de Belém de Judá, cujo nome era Jessé, que tinha oito filhos; e nos dias de Saul este homem era já velho e avançado em idade entre os homens.

[[v9-17-13]]

^<<v9-17-13,13>>^ Os três filhos mais velhos de Jessé tinham seguido a Saul à guerra; eram os nomes de seus três filhos que foram à guerra: Eliabe, o primogênito, o segundo Abinadabe, e o terceiro Samá:

[[v9-17-14]]

^<<v9-17-14,14>>^ Davi era o mais moço; os três maiores seguiram a Saul,

[[v9-17-15]]

^<<v9-17-15,15>>^ mas Davi ia e voltava de Saul, para apascentar as ovelhas de seu pai em Belém.

[[v9-17-16]]

^<<v9-17-16,16>>^ Chegava-se, pois, o filisteu pela manhã e à tarde; e apresentou-se por quarenta dias.

[[v9-17-17]]

^<<v9-17-17,17>>^ Disse então Jessé a Davi, seu filho: Toma agora para teus irmãos uma refa deste grão tostado e estes dez pães, e corre a levá-los ao arraial, a teus irmãos.

[[v9-17-18]]

^<<v9-17-18,18>>^ Leva, também, estes dez queijos ao seu comandante de mil; e verás como passam teus irmãos, e trarás notícias deles.

[[v9-17-19]]

^<<v9-17-19,19>>^ Ora, estavam Saul, e eles, e todos os homens de Israel no vale de Elá, pelejando contra os filisteus.

[[v9-17-20]]

^<<v9-17-20,20>>^ Davi então se levantou de madrugada e, deixando as ovelhas com um guarda, carregou-se e partiu, como Jessé lhe ordenara; e chegou ao arraial quando o exército estava saindo em ordem de batalha e dava gritos de guerra.

[[v9-17-21]]

^<<v9-17-21,21>>^ Os israelitas e os filisteus se punham em ordem de batalha, fileira contra fileira.

[[v9-17-22]]

^<<v9-17-22,22>>^ E Davi, deixando na mão do guarda da bagagem a carga que trouxera, correu às fileiras; e, chegando, perguntou a seus irmãos se estavam bem.

[[v9-17-23]]

^<<v9-17-23,23>>^ Enquanto ainda falava com eles, eis que veio subindo do exército dos filisteus o campeão, cujo nome era Golias, o filisteu de Gate, e falou conforme aquelas palavras; e Davi as ouviu.

[[v9-17-24]]

^<<v9-17-24,24>>^ E todos os homens de Israel, vendo aquele homem, fugiam, de diante dele, tomados de pavor.

[[v9-17-25]]

^<<v9-17-25,25>>^ Diziam os homens de Israel: Vistes aquele homem que subiu? pois subiu para desafiar a Israel. Ao homem, pois, que o matar, o rei cumulará de grandes riquezas, e lhe dará a sua filha, e fará livre a casa de seu pai em Israel.

[[v9-17-26]]

^<<v9-17-26,26>>^ Então falou Davi aos homens que se achavam perto dele, dizendo: Que se fará ao homem que matar a esse filisteu, e tirar a afronta de sobre Israel? pois quem é esse incircunciso filisteu, para afrontar os exércitos do Deus vivo?

[[v9-17-27]]

^<<v9-17-27,27>>^ E o povo lhe repetiu aquela palavra, dizendo: Assim se fará ao homem que o matar.

[[v9-17-28]]

^<<v9-17-28,28>>^ Eliabe, seu irmão mais velho, ouviu-o quando falava àqueles homens; pelo que se acendeu a sua ira contra Davi, e disse: Por que desceste aqui, e a quem deixaste aquelas poucas ovelhas no deserto? Eu conheço a tua presunção, e a maldade do teu coração; pois desceste para ver a peleja.

[[v9-17-29]]

^<<v9-17-29,29>>^ Respondeu Davi: Que fiz eu agora? porventura não há razão para isso?

[[v9-17-30]]

^<<v9-17-30,30>>^ E virou-se dele para outro, e repetiu as suas perguntas; e o povo lhe respondeu como da primeira vez.

[[v9-17-31]]

^<<v9-17-31,31>>^ Então, ouvidas as palavras que Davi falara, foram elas referidas a Saul, que mandou chamá-lo.

[[v9-17-32]]

^<<v9-17-32,32>>^ E Davi disse a Saul: Não desfaleça o coração de ninguém por causa dele; teu servo irá, e pelejará contra este filisteu.

[[v9-17-33]]

^<<v9-17-33,33>>^ Saul, porém, disse a Davi: Não poderás ir contra esse filisteu para pelejar com ele, pois tu ainda és moço, e ele homem de guerra desde a sua mocidade.

[[v9-17-34]]

^<<v9-17-34,34>>^ Então disse Davi a Saul: Teu servo apascentava as ovelhas de seu pai, e sempre que vinha um leão, ou um urso, e tomava um cordeiro do rebanho,

[[v9-17-35]]

^<<v9-17-35,35>>^ eu saía após ele, e o matava, e lho arrancava da boca; levantando-se ele contra mim, segurava-o pela queixada, e o feria e matava.

[[v9-17-36]]

^<<v9-17-36,36>>^ O teu servo matava tanto ao leão como ao urso; e este incircunciso filisteu será como um deles, porquanto afrontou os exércitos do Deus vivo.

[[v9-17-37]]

^<<v9-17-37,37>>^ Disse mais Davi: O Senhor, que me livrou das garras do leão, e das garras do urso, me livrará da mão deste filisteu. Então disse Saul a Davi: Vai, e o Senhor seja contigo.

[[v9-17-38]]

^<<v9-17-38,38>>^ E vestiu a Davi da sua própria armadura, pôs-lhe sobre a cabeça um capacete de bronze, e o vestiu de uma couraça.

[[v9-17-39]]

^<<v9-17-39,39>>^ Davi cingiu a espada sobre a armadura e procurou em vão andar, pois não estava acostumado àquilo. Então disse Davi a Saul: Não posso andar com isto, pois não estou acostumado. E Davi tirou aquilo de sobre si.

[[v9-17-40]]

^<<v9-17-40,40>>^ Então tomou na mão o seu cajado, escolheu do ribeiro cinco seixos lisos e pô-los no alforje de pastor que trazia, a saber, no surrão, e, tomando na mão a sua funda, foi-se chegando ao filisteu.

[[v9-17-41]]

^<<v9-17-41,41>>^ O filisteu também vinha se aproximando de Davi, tendo a: sua frente o seu escudeiro.

[[v9-17-42]]

^<<v9-17-42,42>>^ Quando o filisteu olhou e viu a Davi, desprezou-o, porquanto era mancebo, ruivo, e de gentil aspecto.

[[v9-17-43]]

^<<v9-17-43,43>>^ Disse o filisteu a Davi: Sou eu algum cão, para tu vires a mim com paus? E o filisteu, pelos seus deuses, amaldiçoou a Davi.

[[v9-17-44]]

^<<v9-17-44,44>>^ Disse mais o filisteu a Davi: Vem a mim, e eu darei a tua carne às aves do céu e às bestas do campo.

[[v9-17-45]]

^<<v9-17-45,45>>^ Davi, porém, lhe respondeu: Tu vens a mim com espada, com lança e com escudo; mas eu venho a ti em nome do Senhor dos exércitos, o Deus dos exércitos de Israel, a quem tens afrontado.

[[v9-17-46]]

^<<v9-17-46,46>>^ Hoje mesmo o Senhor te entregará na minha mão; ferir-te-ei, e tirar-te-ei a cabeça; os cadáveres do arraial dos filisteus darei hoje mesmo às aves do céu e às feras da terra; para que toda a terra saiba que há Deus em Israel;

[[v9-17-47]]

^<<v9-17-47,47>>^ e para que toda esta assembléia saiba que o Senhor salva, não com espada, nem com lança; pois do Senhor é a batalha, e ele vos entregará em nossas mãos.

[[v9-17-48]]

^<<v9-17-48,48>>^ Quando o filisteu se levantou e veio chegando para se defrontar com Davi, este se apressou e correu ao combate, a encontrar-se com o filisteu.

[[v9-17-49]]

^<<v9-17-49,49>>^ E Davi, metendo a mão no alforje, tirou dali uma pedra e com a funda lha atirou, ferindo o filisteu na testa; a pedra se lhe cravou na testa, e ele caiu com o rosto em terra.

[[v9-17-50]]

^<<v9-17-50,50>>^ Assim Davi prevaleceu contra o filisteu com uma funda e com uma pedra; feriu-o e o matou; e não havia espada na mão de Davi.

[[v9-17-51]]

^<<v9-17-51,51>>^ Correu, pois, Davi, pôs-se em pé sobre o filisteu e, tomando a espada dele e tirando-a da bainha, o matou, decepando-lhe com ela a cabeça. Vendo então os filisteus que o seu campeão estava morto, fugiram.

[[v9-17-52]]

^<<v9-17-52,52>>^ Então os homens de Israel e de Judá se levantaram gritando, e perseguiram os filisteus até a entrada de Gai e até as portas de Ecrom; e caíram os feridos dos filisteus pelo caminho de Saraim até Gate e até Ecrom.

[[v9-17-53]]

^<<v9-17-53,53>>^ Depois voltaram os filhos de Israel de perseguirem os filisteus, e despojaram os seus arraiais.

[[v9-17-54]]

^<<v9-17-54,54>>^ Davi tomou a cabeça do filisteu e a trouxe a Jerusalém; porém pôs as armas dele na sua tenda.

[[v9-17-55]]

^<<v9-17-55,55>>^ Quando Saul viu Davi sair e encontrar-se com o filisteu, perguntou a Abner, o chefe do exército: De quem é filho esse jovem, Abner? Respondeu Abner: Vive a tua alma, ó rei, que não sei.

[[v9-17-56]]

^<<v9-17-56,56>>^ Disse então o rei: Pergunta, pois, de quem ele é filho.

[[v9-17-57]]

^<<v9-17-57,57>>^ Voltando, pois, Davi de ferir o filisteu, Abner o tomou consigo, e o trouxe à presença de Saul, trazendo Davi na mão a cabeça do filisteu.

[[v9-17-58]]

^<<v9-17-58,58>>^ E perguntou-lhe Saul: De quem és filho, jovem? Respondeu Davi: Filho de teu servo Jessé, belemita.

'''

xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[&#60; Capítulo Anterior] | <<v9-17-0,Topo>> | xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[Próximo Capítulo &#62;]