include::./index.adoc[]

[[v9-18-0]]
=== 1 Samuel, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-18-1]]

^<<v9-18-1,1>>^ Ora, acabando Davi de falar com Saul, a alma de Jônatas ligou-se com a alma de Davi; e Jônatas o amou como à sua própria alma.

[[v9-18-2]]

^<<v9-18-2,2>>^ E desde aquele dia Saul o reteve, não lhe permitindo voltar para a casa de seu pai.

[[v9-18-3]]

^<<v9-18-3,3>>^ Então Jônatas fez um pacto com Davi, porque o amava como à sua própria vida.

[[v9-18-4]]

^<<v9-18-4,4>>^ E Jônatas se despojou da capa que vestia, e a deu a Davi, como também a sua armadura, e até mesmo a sua espada, o seu arco e o seu cinto.

[[v9-18-5]]

^<<v9-18-5,5>>^ E saía Davi aonde quer que Saul o enviasse, e era sempre bem sucedido; e Saul o pôs sobre a gente de guerra, e isso pareceu bem aos olhos de todo o povo, e até aos olhos dos servos de Saul.

[[v9-18-6]]

^<<v9-18-6,6>>^ Sucedeu porém que, retornando eles, quando Davi voltava de ferir o filisteu, as mulheres de todas as cidades de Israel saíram ao encontro do rei Saul, cantando e dançando alegremente, com tamboris, e com instrumentos de música.

[[v9-18-7]]

^<<v9-18-7,7>>^ E as mulheres, dançando, cantavam umas para as outras, dizendo: Saul feriu os seus milhares, porém Davi os seus dez milhares.

[[v9-18-8]]

^<<v9-18-8,8>>^ Então Saul se indignou muito, pois aquela palavra pareceu mal aos seus olhos, e disse: Dez milhares atribuíram a Davi, e a mim somente milhares; que lhe falta, senão só o reino?

[[v9-18-9]]

^<<v9-18-9,9>>^ Daquele dia em diante, Saul trazia Davi sob suspeita.

[[v9-18-10]]

^<<v9-18-10,10>>^ No dia seguinte o espírito maligno da parte de Deus se apoderou de Saul, que começou a profetizar no meio da casa; e Davi tocava a harpa, como nos outros dias. Saul tinha na mão uma lança.

[[v9-18-11]]

^<<v9-18-11,11>>^ E Saul arremessou a lança, dizendo consigo: Encravarei a Davi na parede. Davi, porém, desviou-se dele por duas vezes.

[[v9-18-12]]

^<<v9-18-12,12>>^ Saul, pois, temia a Davi, porque o Senhor era com Davi e se tinha retirado dele.

[[v9-18-13]]

^<<v9-18-13,13>>^ Pelo que Saul o afastou de si, e o fez comandante de mil; e ele saía e entrava diante do povo.

[[v9-18-14]]

^<<v9-18-14,14>>^ E Davi era bem sucedido em todos os seus caminhos; e o Senhor era com ele.

[[v9-18-15]]

^<<v9-18-15,15>>^ Vendo, então, Saul que ele era tão bem sucedido, tinha receio dele.

[[v9-18-16]]

^<<v9-18-16,16>>^ Mas todo o Israel e Judá amavam a Davi, porquanto saía e entrava diante deles.

[[v9-18-17]]

^<<v9-18-17,17>>^ Pelo que Saul disse a Davi: Eis que Merabe, minha filha mais velha, te darei por mulher, contanto que me sejas filho valoroso, e guerreies as guerras do Senhor. Pois Saul dizia consigo: Não seja contra ele a minha mão, mas sim a dos filisteus.

[[v9-18-18]]

^<<v9-18-18,18>>^ Mas Davi disse a Saul: Quem sou eu, e qual é a minha vida e a família de meu pai em Israel, para eu vir a ser genro do rei?

[[v9-18-19]]

^<<v9-18-19,19>>^ Sucedeu, porém, que ao tempo em que Merabe, filha de Saul, devia ser dada a Davi, foi dada por mulher a Adriel, meolatita.

[[v9-18-20]]

^<<v9-18-20,20>>^ Mas Mical, a outra filha de Saul, amava a Davi; sendo isto anunciado a Saul, pareceu bem aos seus olhos.

[[v9-18-21]]

^<<v9-18-21,21>>^ E Saul disse: Eu lha darei, para que ela lhe sirva de laço, e para que a mão dos filisteus venha a ser contra ele. Pelo que Saul disse a Davi: com a outra serás hoje meu genro.

[[v9-18-22]]

^<<v9-18-22,22>>^ Saul, pois, deu ordem aos seus servos: Falai em segredo a Davi, dizendo: Eis que o rei se agrada de ti, e todos os seus servos te querem bem; agora, pois, consente em ser genro do rei.

[[v9-18-23]]

^<<v9-18-23,23>>^ Assim os servos de Saul falaram todas estas palavras aos ouvidos de Davi. Então disse Davi: Parece-vos pouca coisa ser genro do rei, sendo eu homem pobre e de condição humilde?

[[v9-18-24]]

^<<v9-18-24,24>>^ E os servos de Saul lhe anunciaram isto, dizendo: Assim e assim falou Davi.

[[v9-18-25]]

^<<v9-18-25,25>>^ Então disse Saul: Assim direis a Davi: O rei não deseja dote, senão cem prepúcios de filisteus, para que seja vingado dos seus inimigos. Porquanto Saul tentava fazer Davi cair pela mão dos filisteus.

[[v9-18-26]]

^<<v9-18-26,26>>^ Tendo os servos de Saul anunciado estas palavras a Davi, pareceu bem aos seus olhos tornar-se genro do rei. Ora, ainda os dias não se haviam cumprido,

[[v9-18-27]]

^<<v9-18-27,27>>^ quando Davi se levantou, partiu com os seus homens, e matou dentre os filisteus duzentos homens; e Davi trouxe os prepúcios deles, e os entregou, bem contados, ao rei, para que fosse seu genro. Então Saul lhe deu por mulher sua filha Mical.

[[v9-18-28]]

^<<v9-18-28,28>>^ Mas quando Saul viu e compreendeu que o Senhor era com Davi e que todo o Israel o amava,

[[v9-18-29]]

^<<v9-18-29,29>>^ temeu muito mais a Davi; e Saul se tornava cada vez mais seu inimigo.

[[v9-18-30]]

^<<v9-18-30,30>>^ Então saíram os chefes dos filisteus à campanha; e sempre que eles saíam, Davi era mais bem sucedido do que todos os servos de Saul, pelo que o seu nome era mui estimado.

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]