include::./index.adoc[]

[[v9-14-0]]
=== 1 Samuel, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v9-14-1]]

^<<v9-14-1,1>>^ Sucedeu, pois, um dia, que Jônatas, filho de Saul, disse ao seu escudeiro: Vem, passemos à guarnição dos filisteus, que está do outro lado. Mas não o fez saber a seu pai.

[[v9-14-2]]

^<<v9-14-2,2>>^ Ora Saul estava na extremidade de Gibeá, debaixo da romeira que havia em Migrom; e o povo que estava com ele era cerca de seiscentos homens;

[[v9-14-3]]

^<<v9-14-3,3>>^ e Aíja, filho de Aitube, irmão de Icabô, filho de Finéias, filho de Eli, sacerdote do Senhor em Siló, trazia o éfode. E o povo não sabia que Jônatas tinha ido.

[[v9-14-4]]

^<<v9-14-4,4>>^ Ora, entre os desfiladeiros pelos quais Jônatas procurava chegar à guarnição dos filisteus, havia um penhasco de um e de outro lado; o nome de um era Bozez, e o nome do outro Sené.

[[v9-14-5]]

^<<v9-14-5,5>>^ Um deles estava para o norte defronte de Micmás, e o outro para o sul defronte de Gibeá.

[[v9-14-6]]

^<<v9-14-6,6>>^ Disse, pois, Jônatas ao seu escudeiro: Vem, passemos à guarnição destes incircuncisos; porventura operará o Senhor por nós, porque para o Senhor nenhum impedimento há de livrar com muitos ou com poucos.

[[v9-14-7]]

^<<v9-14-7,7>>^ Ao que o seu escudeiro lhe respondeu: Faze tudo o que te aprouver; segue, eis-me aqui, a tua disposição será a minha.

[[v9-14-8]]

^<<v9-14-8,8>>^ Disse Jônatas: Eis que passaremos àqueles homens, e nos descobriremos a eles.

[[v9-14-9]]

^<<v9-14-9,9>>^ Se nos disserem: Parai até que cheguemos a vós; então ficaremos no nosso lugar, e não subiremos a eles.

[[v9-14-10]]

^<<v9-14-10,10>>^ Se, porém, disserem: Subi a nós; então subiremos, pois o Senhor os entregou em nossas mãos; isso nos será por sinal.

[[v9-14-11]]

^<<v9-14-11,11>>^ Então ambos se descobriram à guarnição dos filisteus, e os filisteus disseram: Eis que já os hebreus estão saindo das cavernas em que se tinham escondido.

[[v9-14-12]]

^<<v9-14-12,12>>^ E os homens da guarnição disseram a Jônatas e ao seu escudeiro: Subi a nós, e vos ensinaremos uma coisa. Disse, pois, Jônatas ao seu escudeiro: Sobe atrás de mim, porque o Senhor os entregou na mão de Israel.

[[v9-14-13]]

^<<v9-14-13,13>>^ Então trepou Jônatas de gatinhas, e o seu escudeiro atrás dele; e os filisteus caíam diante de Jônatas, e o seu escudeiro os matava atrás dele.

[[v9-14-14]]

^<<v9-14-14,14>>^ Esta primeira derrota, em que Jônatas e o seu escudeiro mataram uns vinte homens, deu-se dentro de meia jeira de terra.

[[v9-14-15]]

^<<v9-14-15,15>>^ Pelo que houve tremor no arraial, no campo e em todo o povo; também a própria guarnição e os saqueadores tremeram; e até a terra estremeceu; de modo que houve grande pânico.

[[v9-14-16]]

^<<v9-14-16,16>>^ Olharam, pois, as sentinelas de Saul e Gibeá de Benjamim, e eis que a multidão se derretia, fugindo para cá e para lá.

[[v9-14-17]]

^<<v9-14-17,17>>^ Disse então Saul ao povo que estava com ele: Ora, contai e vede quem é que saiu dentre nós: E contaram, e eis que nem Jônatas nem o seu escudeiro estava ali.

[[v9-14-18]]

^<<v9-14-18,18>>^ Então Saul disse a Aíja: Traze aqui a arca de Deus. Pois naquele dia estava a arca de Deus com os filhos de Israel.

[[v9-14-19]]

^<<v9-14-19,19>>^ E sucedeu que, estando Saul ainda falando com o sacerdote, o alvoroço que havia no arraial dos filisteus ia crescendo muito; pelo que disse Saul ao sacerdote: Retira a tua mão.

[[v9-14-20]]

^<<v9-14-20,20>>^ Então Saul e todo o povo que estava com ele se reuniram e foram à peleja; e eis que dentre os filisteus a espada de um era contra o outro, e houve mui grande derrota.

[[v9-14-21]]

^<<v9-14-21,21>>^ Os hebreus que estavam dantes com os filisteus, e tinham subido com eles ao arraial, também se ajuntaram aos israelitas que estavam com Saul e Jônatas.

[[v9-14-22]]

^<<v9-14-22,22>>^ E todos os homens de Israel que se haviam escondido na região montanhosa de Efraim, ouvindo que os filisteus fugiam, também os perseguiram de perto na peleja.

[[v9-14-23]]

^<<v9-14-23,23>>^ Assim o Senhor livrou a Israel naquele dia, e a batalha passou além de Bete-Aven.

[[v9-14-24]]

^<<v9-14-24,24>>^ Ora, os homens de Israel estavam já exaustos naquele dia, porquanto Saul conjurara o povo, dizendo: Maldito o homem que comer pão antes da tarde, antes que eu me vingue de meus inimigos. Pelo que todo o povo se absteve de comer.

[[v9-14-25]]

^<<v9-14-25,25>>^ Mas todo o povo chegou a um bosque, onde havia mel à flor da terra.

[[v9-14-26]]

^<<v9-14-26,26>>^ Chegando, pois, o povo ao bosque, viu correr o mel; todavia ninguém chegou a mão à boca, porque o povo temia a conjuração.

[[v9-14-27]]

^<<v9-14-27,27>>^ Jônatas, porém, não tinha ouvido quando seu pai conjurara o povo; pelo que estendeu a ponta da vara que tinha na mão, e a molhou no favo de mel; e, ao chegar a mão à boca, aclararam-se-lhe os olhos.

[[v9-14-28]]

^<<v9-14-28,28>>^ Então disse um do povo: Teu pai solenemente conjurou o povo, dizendo: Maldito o homem que comer pão hoje. E o povo ainda desfalecia.

[[v9-14-29]]

^<<v9-14-29,29>>^ Pelo que disse Jônatas: Meu pai tem turbado a terra; ora vede como se me aclararam os olhos por ter provado um pouco deste mel.

[[v9-14-30]]

^<<v9-14-30,30>>^ Quanto maior não teria sido a derrota dos filisteus se o povo hoje tivesse comido livremente do despojo, que achou de seus inimigos?

[[v9-14-31]]

^<<v9-14-31,31>>^ Feriram, contudo, naquele dia aos filisteus, desde Micmás até Aijalom. E o povo desfaleceu em extremo;

[[v9-14-32]]

^<<v9-14-32,32>>^ então o povo se lançou ao despojo, e tomou ovelhas, bois e bezerros e, degolando-os no chão, comeu-os com o sangue.

[[v9-14-33]]

^<<v9-14-33,33>>^ E o anunciaram a Saul, dizendo: Eis que o povo está pecando contra o Senhor, comendo carne com o sangue. Respondeu Saul: Procedestes deslealmente. Trazei-me aqui já uma grande pedra.

[[v9-14-34]]

^<<v9-14-34,34>>^ Disse mais Saul: Dispersai-vos entre e povo, e dizei-lhes: Trazei-me aqui cada um o seu boi, e cada um a sua ovelha e degolai-os aqui, e comei; e não pequeis contra e Senhor, comendo com sangue. Então todo o povo trouxe de noite, cada um o seu boi, e os degolaram ali.

[[v9-14-35]]

^<<v9-14-35,35>>^ Então edificou Saul um altar ao Senhor; este foi o primeiro altar que ele edificou ao Senhor.

[[v9-14-36]]

^<<v9-14-36,36>>^ Depois disse Saul: Desçamos de noite atrás dos filisteus, e despojemo-los, até e amanhecer, e não deixemos deles um só homem. E o povo disse: Faze tudo o que parecer bem aos teus olhos. Disse, porém, o sacerdote: Cheguemo-nos aqui a Deus.

[[v9-14-37]]

^<<v9-14-37,37>>^ Então consultou Saul a Deus, dizendo: Descerei atrás dos filisteus? entregá-los-ás na mão de Israel? Deus, porém, não lhe respondeu naquele dia.

[[v9-14-38]]

^<<v9-14-38,38>>^ Disse, pois, Saul: Chegai-vos para cá, todos os chefes do povo; informai-vos, e vede em que se cometeu hoje este pecado;

[[v9-14-39]]

^<<v9-14-39,39>>^ porque, como vive o Senhor que salva a Israel, ainda que seja em meu filha Jônatas, ele será morto. Mas de todo o povo ninguém lhe respondeu.

[[v9-14-40]]

^<<v9-14-40,40>>^ Disse mais a todo o Israel: Vós estareis dum lado, e eu e meu filho Jônatas estaremos do outro. Então disse o povo a Saul: Faze o que parecer bem aos teus olhos.

[[v9-14-41]]

^<<v9-14-41,41>>^ Falou, pois, Saul ao Senhor Deus de Israel: Mostra o que é justo. E Jônatas e Saul foram tomados por sorte, e o povo saiu livre.

[[v9-14-42]]

^<<v9-14-42,42>>^ Então disse Saul: Lançai a sorte entre mim e Jônatas, meu filho. E foi tomado Jônatas.

[[v9-14-43]]

^<<v9-14-43,43>>^ Disse então Saul a Jônatas: Declara-me o que fizeste. E Jônatas lho declarou, dizendo: Provei, na verdade, um pouco de mel com a ponta da vara que tinha na mão; eis-me pronto a morrer.

[[v9-14-44]]

^<<v9-14-44,44>>^ Ao que disse Saul: Assim me faça Deus, e outro tanto, se tu, certamente, não morreres, Jônatas.

[[v9-14-45]]

^<<v9-14-45,45>>^ Mas o povo disse a Saul: Morrerá, porventura, Jônatas, que operou esta grande salvação em Israel? Tal não suceda! como vive o Senhor, não lhe há de cair no chão um só cabelo da sua cabeça! pois com Deus fez isso hoje. Assim o povo livrou Jônatas, para que não morresse.

[[v9-14-46]]

^<<v9-14-46,46>>^ Então Saul deixou de perseguir os filisteus, e estes foram para o seu lugar.

[[v9-14-47]]

^<<v9-14-47,47>>^ Tendo Saul tomado o reino sobre Israel, pelejou contra todos os seus inimigos em redor: contra Moabe, contra os filhos de Amom, contra Edom, contra os reis de Zobá e contra os filisteus; e, para onde quer que se voltava, saía vitorioso.

[[v9-14-48]]

^<<v9-14-48,48>>^ Houve-se valorosamente, derrotando os amalequitas, e libertando Israel da mão dos que o saqueavam.

[[v9-14-49]]

^<<v9-14-49,49>>^ Ora, os filhos de Saul eram Jônatas, Isvi e Malquisua; os nomes de suas duas filhas eram estes: o da mais velha Merabe, e o da mais nova Mical.

[[v9-14-50]]

^<<v9-14-50,50>>^ O nome da mulher de Saul era Ainoã, filha de Aimaaz; e o nome do chefe do seu exército, Abner, filho de Ner, tio de Saul.

[[v9-14-51]]

^<<v9-14-51,51>>^ Quis, pai de Saul, e Ner, pai de Abner, eram filhos de Abiel.

[[v9-14-52]]

^<<v9-14-52,52>>^ E houve forte guerra contra os filisteus, por todos os dias de Saul; e sempre que Saul via algum homem poderoso e valente, o agregava a si.

'''

xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[&#60; Capítulo Anterior] | <<v9-14-0,Topo>> | xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[Próximo Capítulo &#62;]