include::./index.adoc[]

[[v8-1-0]]
=== Rute, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v8-1-1]]

^<<v8-1-1,1>>^ Nos dias em que os juízes governavam, houve uma fome na terra; pelo que um homem de Belém de Judá saiu a peregrinar no país de Moabe, ele, sua mulher, e seus dois filhos.

[[v8-1-2]]

^<<v8-1-2,2>>^ Chamava-se este homem Elimeleque, e sua mulher Noêmi, e seus dois filhos se chamavam Malom e Quiliom; eram efrateus, de Belém de Judá. Tendo entrado no país de Moabe, ficaram ali.

[[v8-1-3]]

^<<v8-1-3,3>>^ E morreu Elimeleque, marido de Noêmi; e ficou ela com os seus dois filhos,

[[v8-1-4]]

^<<v8-1-4,4>>^ os quais se casaram com mulheres moabitas; uma destas se chamava Orfa, e a outra Rute; e moraram ali quase dez anos.

[[v8-1-5]]

^<<v8-1-5,5>>^ E morreram também os dois, Malom e Quiliom, ficando assim a mulher desamparada de seus dois filhos e de seu marido.

[[v8-1-6]]

^<<v8-1-6,6>>^ Então se levantou ela com as suas noras, para voltar do país de Moabe, porquanto nessa terra tinha ouvido que e Senhor havia visitado o seu povo, dando-lhe pão.

[[v8-1-7]]

^<<v8-1-7,7>>^ Pelo que saiu de lugar onde estava, e com ela as duas noras. Indo elas caminhando para voltarem para a terra de Judá,

[[v8-1-8]]

^<<v8-1-8,8>>^ disse Noêmi às suas noras: Ide, voltai, cada uma para a casa de sua mãe; e o Senhor use convosco de benevolência, como vós o fizestes com os falecidos e comigo.

[[v8-1-9]]

^<<v8-1-9,9>>^ O Senhor vos dê que acheis descanso cada uma em casa de seu marido. Quando as beijou, porém, levantaram a voz e choraram.

[[v8-1-10]]

^<<v8-1-10,10>>^ E disseram-lhe: Certamente voltaremos contigo para o teu povo.

[[v8-1-11]]

^<<v8-1-11,11>>^ Noêmi, porém, respondeu: Voltai, minhas filhas; porque ireis comigo? Tenho eu ainda filhos no meu ventre, para que vos viessem a ser maridos?

[[v8-1-12]]

^<<v8-1-12,12>>^ Voltai, filhas minhas; ide-vos, porque já sou velha demais para me casar. Ainda quando eu dissesse: Tenho esperança; ainda que esta noite tivesse marido e ainda viesse a ter filhos.

[[v8-1-13]]

^<<v8-1-13,13>>^ esperá-los-íeis até que viessem a ser grandes? deter-vos-íeis por eles, sem tomardes marido? Não, filhas minhas, porque mais amargo me é a mim do que a vós mesmas; porquanto a mão do Senhor se descarregou contra mim.

[[v8-1-14]]

^<<v8-1-14,14>>^ Então levantaram a voz, e tornaram a chorar; e Orfa beijou a sua sogra, porém Rute se apegou a ela.

[[v8-1-15]]

^<<v8-1-15,15>>^ Pelo que disse Noêmi: Eis que tua concunhada voltou para o seu povo e para os seus deuses; volta também tu após a tua concunhada.

[[v8-1-16]]

^<<v8-1-16,16>>^ Respondeu, porém, Rute: Não me instes a que te abandone e deixe de seguir-te. Porque aonde quer que tu fores, irei eu; e onde quer que pousares, ali pousarei eu; o teu povo será o meu povo, o teu Deus será o meu Deus.

[[v8-1-17]]

^<<v8-1-17,17>>^ Onde quer que morreres, morrerei eu, e ali serei sepultada. Assim me faça o Senhor, e outro tanto, se outra coisa que não seja a morte me separar de ti.

[[v8-1-18]]

^<<v8-1-18,18>>^ Vendo Noêmi que de todo estava resolvida a ir com ela, deixou de lhe falar nisso.

[[v8-1-19]]

^<<v8-1-19,19>>^ Assim, pois, foram-se ambas, até que chegaram a Belém. E sucedeu que, ao entrarem em Belém, toda a cidade se comoveu por causa delas, e as mulheres perguntavam: É esta, porventura, Noêmi?

[[v8-1-20]]

^<<v8-1-20,20>>^ Ela, porém, lhes respondeu: Não me chameis Noêmi; chamai-me Mara, porque o Todo-Poderoso me encheu de amargura.

[[v8-1-21]]

^<<v8-1-21,21>>^ Cheia parti, porém vazia o Senhor me fez tornar. Por que, pois, me chamais Noêmi, visto que o Senhor testemunhou contra mim, e o Todo-Poderoso me afligiu?

[[v8-1-22]]

^<<v8-1-22,22>>^ Assim Noêmi voltou, e com ela Rute, a moabita, sua nora, que veio do país de Moabe; e chegaram a Belém no principio da sega da cevada.

'''

xref:007-juizes/007-juizes-021.adoc#v7-21-0[&#60; Capítulo Anterior] | <<v8-1-0,Topo>> | xref:008-rute/008-rute-002.adoc#v8-2-0[Próximo Capítulo &#62;]