include::./index.adoc[]

[[v8-3-0]]
=== Rute, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v8-3-1]]

^<<v8-3-1,1>>^ Depois lhe disse Noêmi, sua sogra: Minha filha, não te hei de buscar descanso, para que fiques bem?

[[v8-3-2]]

^<<v8-3-2,2>>^ Ora pois, não é Boaz, com cujas moças estiveste, de nossa parentela. Eis que esta noite ele vai joeirar a cevada na eira.

[[v8-3-3]]

^<<v8-3-3,3>>^ Lava-te pois, unge-te, veste os teus melhores vestidos, e desce à eira; porém não te dês a conhecer ao homem, até que tenha acabado de comer e beber.

[[v8-3-4]]

^<<v8-3-4,4>>^ E quando ele se deitar, notarás o lugar em que se deita; então entrarás, descobrir-lhe-ás os pés e te deitarás, e ele te dirá o que deves fazer.

[[v8-3-5]]

^<<v8-3-5,5>>^ Respondeu-lhe Rute: Tudo quanto me disseres, farei.

[[v8-3-6]]

^<<v8-3-6,6>>^ Então desceu à eira, e fez conforme tudo o que sua sogra lhe tinha ordenado.

[[v8-3-7]]

^<<v8-3-7,7>>^ Havendo, pois, Boaz comido e bebido, e estando já o seu coração alegre, veio deitar-se ao pé de uma meda; e vindo ela de mansinho, descobriu-lhe os pés, e se deitou.

[[v8-3-8]]

^<<v8-3-8,8>>^ Ora, pela meia-noite, o homem estremeceu, voltou-se, e viu uma mulher deitada aos seus pés.

[[v8-3-9]]

^<<v8-3-9,9>>^ E perguntou ele: Quem és tu? Ao que ela respondeu: Sou Rute, tua serva; estende a tua capa sobre a tua serva, porque tu és o remidor.

[[v8-3-10]]

^<<v8-3-10,10>>^ Então disse ele: Bendita sejas tu do Senhor, minha filha; mostraste agora mais bondade do que dantes, visto que após nenhum mancebo foste, quer pobre quer rico.

[[v8-3-11]]

^<<v8-3-11,11>>^ Agora, pois, minha filha, não temas; tudo quanto disseres te farei, pois toda a cidade do meu povo sabe que és mulher virtuosa.

[[v8-3-12]]

^<<v8-3-12,12>>^ Ora, é bem verdade que eu sou remidor, porém há ainda outro mais chegado do que eu.

[[v8-3-13]]

^<<v8-3-13,13>>^ Fica-te aqui esta noite, e será que pela manhã, se ele cumprir para contigo os deveres de remidor, que o faça; mas se não os quiser cumprir, então eu o farei tão certamente como vive o Senhor; deita-te até pela manhã.

[[v8-3-14]]

^<<v8-3-14,14>>^ Ficou, pois, deitada a seus pés até pela manhã, e levantou-se antes que fosse possível a uma pessoa reconhecer outra; porquanto ele disse: Não se saiba que uma mulher veio à eira.

[[v8-3-15]]

^<<v8-3-15,15>>^ Disse mais: Traze aqui a capa com que te cobres, e segura-a. Segurou-a, pois, e ele as mediu seis medidas de cevada, e lhas pôs no ombro. Então ela foi para a cidade.

[[v8-3-16]]

^<<v8-3-16,16>>^ Quando chegou à sua sogra, esta lhe perguntou: Como te houveste, minha filha? E ela lhe contou tudo quanto aquele homem lhe fizera.

[[v8-3-17]]

^<<v8-3-17,17>>^ Disse mais: Estas seis medidas de cevada ele mas deu, dizendo: Não voltarás vazia para tua sogra.

[[v8-3-18]]

^<<v8-3-18,18>>^ Então disse Noêmi: Espera, minha filha, até que saibas como irá terminar o caso; porque aquele homem não descansará enquanto não tiver concluído hoje este negócio.

'''

xref:008-rute/008-rute-002.adoc#v8-2-0[&#60; Capítulo Anterior] | <<v8-3-0,Topo>> | xref:008-rute/008-rute-004.adoc#v8-4-0[Próximo Capítulo &#62;]