include::./index.adoc[]

[[v8-2-0]]
=== Rute, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v8-2-1]]

^<<v8-2-1,1>>^ Ora, tinha Noêmi um parente de seu marido, homem poderoso e rico, da família de Elimeleque; e ele se chamava Boaz.

[[v8-2-2]]

^<<v8-2-2,2>>^ Rute, a moabita, disse a Noêmi: Deixa-me ir ao campo a apanhar espigas atrás daquele a cujos olhos eu achar graça. E ela lhe respondeu: Vai, minha filha.

[[v8-2-3]]

^<<v8-2-3,3>>^ Foi, pois, e chegando ao campo respigava após os segadores; e caiu-lhe em sorte uma parte do campo de Boaz, que era da família de Elimeleque.

[[v8-2-4]]

^<<v8-2-4,4>>^ E eis que Boaz veio de Belém, e disse aos segadores: O Senhor seja convosco. Responderam-lhe eles: O Senhor te abençoe.

[[v8-2-5]]

^<<v8-2-5,5>>^ Depois perguntou Boaz ao moço que estava posto sobre os segadores: De quem é esta moça?

[[v8-2-6]]

^<<v8-2-6,6>>^ Respondeu-lhe o moço: Esta é a moça moabita que voltou com Noêmi do país de Moabe.

[[v8-2-7]]

^<<v8-2-7,7>>^ Disse-me ela: Deixa-me colher e ajuntar espigas por entre os molhos após os segadores: Assim ela veio, e está aqui desde pela manhã até agora, sem descansar nem sequer um pouco.

[[v8-2-8]]

^<<v8-2-8,8>>^ Então disse Boaz a Rute: Escuta filha minha; não vás colher em outro campo, nem tampouco passes daqui, mas ajunta-te às minhas moças.

[[v8-2-9]]

^<<v8-2-9,9>>^ Os teus olhos estarão atentos no campo que segarem, e irás após elas; não dei eu ordem aos moços, que não te molestem? Quando tiveres sede, vai aos vasos, e bebe do que os moços tiverem tirado.

[[v8-2-10]]

^<<v8-2-10,10>>^ Então ela, inclinando-se e prostrando-se com o rosto em terra, perguntou-lhe: Por que achei eu graça aos teus olhos, para que faças caso de mim, sendo eu estrangeira?

[[v8-2-11]]

^<<v8-2-11,11>>^ Ao que lhe respondeu Boaz: Bem se me contou tudo quanto tens feito para com tua sogra depois da morte de teu marido; como deixaste a teu pai e a tua mãe, e a terra onde nasceste, e vieste para um povo que dantes não conhecias.

[[v8-2-12]]

^<<v8-2-12,12>>^ O Senhor recompense o que fizeste, e te seja concedido pleno galardão da parte do Senhor Deus de Israel, sob cujas asas te vieste abrigar.

[[v8-2-13]]

^<<v8-2-13,13>>^ E disse ela: Ache eu graça aos teus olhos, senhor meu, pois me consolaste, e falaste bondosamente a tua serva, não sendo eu nem mesmo como uma das tuas criadas.

[[v8-2-14]]

^<<v8-2-14,14>>^ Também à hora de comer, disse-lhe Boaz: Achega-te, come do pão e molha o teu bocado no vinagre. E, sentando-se ela ao lado dos segadores, ele lhe ofereceu grão tostado, e ela comeu e ficou satisfeita, e ainda lhe sobejou.

[[v8-2-15]]

^<<v8-2-15,15>>^ Quando ela se levantou para respigar, Boaz deu ordem aos seus moços, dizendo: Até entre os molhos deixai-a respirar, e não a censureis.

[[v8-2-16]]

^<<v8-2-16,16>>^ Também, tirai dos molhos algumas espigas e deixai-as ficar, para que as colha, e não a repreendais.

[[v8-2-17]]

^<<v8-2-17,17>>^ Assim ela respigou naquele campo até a tarde; e debulhou o que havia apanhado e foi quase uma efa de cevada.

[[v8-2-18]]

^<<v8-2-18,18>>^ Então, carregando com a cevada, veio à cidade; e viu sua sogra o que ela havia apanhado. Também Rute tirou e deu-lhe o que lhe sobejara depois de fartar-se.

[[v8-2-19]]

^<<v8-2-19,19>>^ Ao que lhe perguntou sua sogra: Onde respigaste hoje, e onde trabalhaste? Bendito seja aquele que fez caso de ti. E ela relatou à sua sogra com quem tinha trabalhado, e disse: O nome do homem com quem hoje trabalhei é Boaz.

[[v8-2-20]]

^<<v8-2-20,20>>^ Disse Noêmi a sua nora: Bendito seja ele do Senhor, que não tem deixado de misturar a sua beneficência nem para com os vivos nem para com os mortos. Disse-lhe mais Noêmi: Esse homem é parente nosso, um dos nossos remidores.

[[v8-2-21]]

^<<v8-2-21,21>>^ Respondeu Rute, a moabita: Ele me disse ainda: Seguirás de perto os meus moços até que tenham acabado toda a minha sega.

[[v8-2-22]]

^<<v8-2-22,22>>^ Então disse Noêmi a sua nora, Rute: Bom é, filha minha, que saias com as suas moças, e que não te encontrem noutro campo.

[[v8-2-23]]

^<<v8-2-23,23>>^ Assim se ajuntou com as moças de Boaz, para respigar até e fim da sega da cevada e do trigo; e morava com a sua sogra.

'''

xref:008-rute/008-rute-001.adoc#v8-1-0[&#60; Capítulo Anterior] | <<v8-2-0,Topo>> | xref:008-rute/008-rute-003.adoc#v8-3-0[Próximo Capítulo &#62;]