include::./index.adoc[]

[[v12-22-0]]
=== 2 Reis, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-22-1]]

^<<v12-22-1,1>>^ Josias tinha oito anos quando começou a reinar, e reinou trinta e um anos em Jerusalém. O nome de sua mãe era Jedida, filha de Adaías, de Bozcate.

[[v12-22-2]]

^<<v12-22-2,2>>^ Ele fez o que era reto aos olhos do Senhor; e andou em todo o caminho de Davi, seu pai, não se apartando dele nem para a direita nem para a esquerda.

[[v12-22-3]]

^<<v12-22-3,3>>^ No ano décimo oitavo do rei Josias, o rei mandou o escrivão Safã, filho de Azalias, filho de Mesulão, à casa do Senhor, dizendo-lhe:

[[v12-22-4]]

^<<v12-22-4,4>>^ Sobe a Hilquias, o sumo sacerdote, para que faça a soma do dinheiro que se tem trazido para a casa do Senhor, o qual os guardas da entrada têm recebido do povo;

[[v12-22-5]]

^<<v12-22-5,5>>^ e que só entreguem na mão dos mestres de obra que estão encarregados da casa do Senhor; e que estes o dêem aos que fazem a obra, aos que estão na casa do Senhor para repararem os estragos da casa,

[[v12-22-6]]

^<<v12-22-6,6>>^ aos carpinteiros, aos edificadores, e aos pedreiros. e que comprem madeira e pedras lavradas, a fim de repararem a casa.

[[v12-22-7]]

^<<v12-22-7,7>>^ Contudo não se tomava conta a eles do dinheiro que se lhes entregava nas mãos, porquanto se haviam com fidelidade.

[[v12-22-8]]

^<<v12-22-8,8>>^ Então disse o sumo sacerdote Hilquias ao escrivão Safã: Achei o livro da lei na casa do Senhor. E Hilquias entregou o livro a Safã, e ele o leu.

[[v12-22-9]]

^<<v12-22-9,9>>^ Depois o escrivão Safã veio ter com o rei e, dando ao rei o relatório, disse: Teus servos despejaram o dinheiro que se achou na casa, e o entregaram na mão dos mestres de obra que estão encarregados da casa do Senhor.

[[v12-22-10]]

^<<v12-22-10,10>>^ Safã, o escrivão, falou ainda ao rei, dizendo: O sacerdote Hilquias me entregou um livro. E Safã o leu diante do rei.

[[v12-22-11]]

^<<v12-22-11,11>>^ E sucedeu que, tendo o rei ouvido as palavras do livro da lei, rasgou as suas vestes.

[[v12-22-12]]

^<<v12-22-12,12>>^ Então o rei deu ordem a Hilquias, o sacerdote, a Aicão, filho de Safã, a Acbor, filho de Micaías, a Safã, o escrivão, e Asaías, servo do rei, dizendo:

[[v12-22-13]]

^<<v12-22-13,13>>^ Ide, consultai ao Senhor por mim, e pelo povo, e por todo o Judá, acerca das palavras deste livro que se achou; porque grande é o furor do Senhor, que se acendeu contra nós, porquanto nossos pais não deram ouvidos às palavras deste livro, para fazerem conforme tudo quanto acerca de nós está escrito.

[[v12-22-14]]

^<<v12-22-14,14>>^ Então o sacerdote Hilquias, e Aicão, e Acbor, e Safã, e Asaías foram ter com a profetisa Hulda, mulher de Salum, filho de Ticvá, filho de Harás, o guarda das vestiduras &#123;ela habitava então em Jerusalém, na segunda parte&#125;, e lhe falaram.

[[v12-22-15]]

^<<v12-22-15,15>>^ E ela lhes respondeu: Assim diz o Senhor, o Deus de Israel: Dizei ao homem que vos enviou a mim:

[[v12-22-16]]

^<<v12-22-16,16>>^ Assim diz o Senhor: Eis que trarei males sobre este lugar e sobre os seus habitantes, conforme todas as palavras do livro que o rei de Judá leu.

[[v12-22-17]]

^<<v12-22-17,17>>^ Porquanto me deixaram, e queimaram incenso a outros deuses, para me provocarem à ira por todas as obras das suas mãos, o meu furor se acendeu contra este lugar, e não se apagará.

[[v12-22-18]]

^<<v12-22-18,18>>^ Todavia ao rei de Judá, que vos enviou para consultar ao Senhor, assim lhe direis: Assim diz o Senhor, o Deus de Israel: Quanto às palavras que ouviste,

[[v12-22-19]]

^<<v12-22-19,19>>^ porquanto o teu coração se enterneceu, e te humilhaste perante o Senhor, quando ouviste o que falei contra este lugar, e contra os seus habitantes, isto é, que se haviam de tornar em assolação e em maldição, e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi, diz o Senhor.

[[v12-22-20]]

^<<v12-22-20,20>>^ Pelo que eu te recolherei a teus pais, e tu serás recolhido em paz à tua sepultura, e os teus olhos não verão todo o mal que hei de trazer sobre este lugar. Então voltaram, levando a resposta ao rei.

'''

xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[&#60; Capítulo Anterior] | <<v12-22-0,Topo>> | xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[Próximo Capítulo &#62;]