include::./index.adoc[]

[[v12-4-0]]
=== 2 Reis, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-4-1]]

^<<v12-4-1,1>>^ Ora uma dentre as mulheres dos filhos dos profetas clamou a Eliseu, dizendo: Meu marido, teu servo, morreu; e tu sabes que o teu servo temia ao Senhor. Agora acaba de chegar o credor para levar-me os meus dois filhos para serem escravos.

[[v12-4-2]]

^<<v12-4-2,2>>^ Perguntou-lhe Eliseu: Que te hei de fazer? Dize-me o que tens em casa. E ela disse: Tua serva não tem nada em casa, senão uma botija de azeite.

[[v12-4-3]]

^<<v12-4-3,3>>^ Disse-lhe ele: Vai, pede emprestadas vasilhas a todos os teus vizinhos, vasilhas vazias, não poucas.

[[v12-4-4]]

^<<v12-4-4,4>>^ Depois entra, e fecha a porta sobre ti e sobre teus filhos; deita azeite em todas essas vasilhas, e põe à parte a que estiver cheia.

[[v12-4-5]]

^<<v12-4-5,5>>^ Então ela se apartou dele. Depois, fechada a porta sobre si e sobre seus filhos, estes lhe chegavam as vasilhas, e ela as enchia.

[[v12-4-6]]

^<<v12-4-6,6>>^ Cheias que foram as vasilhas, disse a seu filho: Chega-me ainda uma vasilha. Mas ele respondeu: Não há mais vasilha nenhuma. Então o azeite parou.

[[v12-4-7]]

^<<v12-4-7,7>>^ Veio ela, pois, e o fez saber ao homem de Deus. Disse-lhe ele: Vai, vende o azeite, e paga a tua dívida; e tu e teus filhos vivei do resto.

[[v12-4-8]]

^<<v12-4-8,8>>^ Sucedeu também certo dia que Eliseu foi a Suném, onde havia uma mulher rica que o reteve para comer; e todas as vezes que ele passava por ali, lá se dirigia para comer.

[[v12-4-9]]

^<<v12-4-9,9>>^ E ela disse a seu marido: Tenho observado que este que passa sempre por nós é um santo homem de Deus.

[[v12-4-10]]

^<<v12-4-10,10>>^ Façamos-lhe, pois, um pequeno quarto sobre o muro; e ponhamos-lhe ali uma cama, uma mesa, uma cadeira e um candeeiro; e há de ser que, quando ele vier a nós se recolherá ali.

[[v12-4-11]]

^<<v12-4-11,11>>^ Sucedeu que um dia ele chegou ali, recolheu-se àquele quarto e se deitou.

[[v12-4-12]]

^<<v12-4-12,12>>^ Então disse ao seu moço Geazi: Chama esta sunamita. Ele a chamou, e ela se apresentou perante ele.

[[v12-4-13]]

^<<v12-4-13,13>>^ Pois Eliseu havia dito a Geazi: Dize-lhe: Eis que tu nos tens tratado com todo o desvelo; que se há de fazer por ti? Haverá alguma coisa de que se fale por ti ao rei, ou ao chefe do exército? Ao que ela respondera: Eu habito no meio do meu povo.

[[v12-4-14]]

^<<v12-4-14,14>>^ Então dissera ele: Que se há de fazer, pois por ela? E Geazi dissera: Ora, ela não tem filho, e seu marido é velho.

[[v12-4-15]]

^<<v12-4-15,15>>^ Pelo que disse ele: Chama-a. E ele a chamou, e ela se pôs à porta.

[[v12-4-16]]

^<<v12-4-16,16>>^ E Eliseu disse: Por este tempo, no ano próximo, abraçarás um filho. Respondeu ela: Não, meu senhor, homem de Deus, não mintas à tua serva.

[[v12-4-17]]

^<<v12-4-17,17>>^ Mas a mulher concebeu, e deu à luz um filho, no tempo determinado, no ano seguinte como Eliseu lhe dissera.

[[v12-4-18]]

^<<v12-4-18,18>>^ Tendo o menino crescido, saiu um dia a ter com seu pai, que estava com os segadores.

[[v12-4-19]]

^<<v12-4-19,19>>^ Disse a seu pai: Minha cabeça! minha cabeça! Então ele disse a um moço: Leva-o a sua mãe.

[[v12-4-20]]

^<<v12-4-20,20>>^ Este o tomou, e o levou a sua mãe; e o menino esteve sobre os joelhos dela até o meio-dia, e então morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ Ela subiu, deitou-o sobre a cama do homem de Deus e, fechando sobre ele a porta, saiu.

[[v12-4-22]]

^<<v12-4-22,22>>^ Então chamou a seu marido, e disse: Manda-me, peço-te, um dos moços e uma das jumentas, para que eu corra ao homem de Deus e volte.

[[v12-4-23]]

^<<v12-4-23,23>>^ Disse ele: Por que queres ir ter com ele hoje? Não é lua nova nem sábado. E ela disse: Tudo vai bem.

[[v12-4-24]]

^<<v12-4-24,24>>^ Então ela fez albardar a jumenta, e disse ao seu moço: Guia e anda, e não me detenhas no caminhar, senão quando eu to disser.

[[v12-4-25]]

^<<v12-4-25,25>>^ Partiu pois, e foi ter com o homem de Deus, ao monte Carmelo; e sucedeu que, vendo-a de longe o homem de Deus, disse a Geazi, seu moço: Eis aí a sunamita;

[[v12-4-26]]

^<<v12-4-26,26>>^ corre-lhe ao encontro e pergunta-lhe: Vais bem? Vai bem teu marido? Vai bem teu filho? Ela respondeu: Vai bem.

[[v12-4-27]]

^<<v12-4-27,27>>^ Chegando ela ao monte, à presença do homem de Deus, apegou-se-lhe aos pés. Chegou-se Geazi para a retirar, porém, o homem de Deus lhe disse: Deixa-a, porque a sua alma está em amargura, e o Senhor mo encobriu, e não mo manifestou.

[[v12-4-28]]

^<<v12-4-28,28>>^ Então disse ela: Pedi eu a meu senhor algum filho? Não disse eu: Não me enganes?

[[v12-4-29]]

^<<v12-4-29,29>>^ Ao que ele disse a Geazi: Cinge os teus lombos, toma o meu bordão na mão, e vai. Se encontrares alguém, não o saúdes; e se alguém te saudar, não lhe respondas; e põe o meu bordão sobre o rosto do menino.

[[v12-4-30]]

^<<v12-4-30,30>>^ A mãe do menino, porém, disse: Vive o senhor, e vive a tua alma, que não te hei de deixar. Então ele se levantou, e a seguiu.

[[v12-4-31]]

^<<v12-4-31,31>>^ Geazi foi adiante deles, e pôs o bordão sobre o rosto do menino; porém não havia nele voz nem sentidos. Pelo que voltou a encontrar-se com Eliseu, e o informou, dizendo: O menino não despertou.

[[v12-4-32]]

^<<v12-4-32,32>>^ Quando Eliseu chegou à casa, eis que o menino jazia morto sobre a sua cama.

[[v12-4-33]]

^<<v12-4-33,33>>^ Então ele entrou, fechou a porta sobre eles ambos, e orou ao Senhor.

[[v12-4-34]]

^<<v12-4-34,34>>^ Em seguida subiu na cama e deitou-se sobre o menino, pondo a boca sobre a boca do menino, os olhos sobre os seus olhos, e as mãos sobre as suas mãos, e ficou encurvado sobre ele até que a carne do menino aqueceu.

[[v12-4-35]]

^<<v12-4-35,35>>^ Depois desceu, andou pela casa duma parte para outra, tornou a subir, e se encurvou sobre ele; então o menino espirrou sete vezes, e abriu os olhos.

[[v12-4-36]]

^<<v12-4-36,36>>^ Eliseu chamou a Geazi, e disse: Chama essa sunamita. E ele a chamou. Quando ela se lhe apresentou, disse ele: Toma o teu filho.

[[v12-4-37]]

^<<v12-4-37,37>>^ Então ela entrou, e prostrou-se a seus pés, inclinando-se à terra; e tomando seu filho, saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ Eliseu voltou a Gilgal. E havia fome na terra; e os filhos dos profetas estavam sentados na sua presença. E disse ao seu moço: Põe a panela grande ao lume, e faze um caldo de ervas para os filhos dos profetas.

[[v12-4-39]]

^<<v12-4-39,39>>^ Então um deles saiu ao campo a fim de apanhar ervas, e achando uma parra brava, colheu dela a sua capa cheia de colocíntidas e, voltando, cortou-as na panela do caldo, não sabendo o que era.

[[v12-4-40]]

^<<v12-4-40,40>>^ Assim tiraram de comer para os homens. E havendo eles provado o caldo, clamaram, dizendo: Ó homem de Deus, há morte na panela! E não puderam comer.

[[v12-4-41]]

^<<v12-4-41,41>>^ Ele, porém, disse: Trazei farinha. E deitou-a na panela, e disse: Tirai para os homens, a fim de que comam. E já não havia mal nenhum na panela.

[[v12-4-42]]

^<<v12-4-42,42>>^ Um homem veio de Baal-Salisa, trazendo ao homem de Deus pães das primícias, vinte pães de cevada, e espigas verdes no seu alforje. Eliseu disse: Dá ao povo, para que coma.

[[v12-4-43]]

^<<v12-4-43,43>>^ Disse, porém, seu servo: Como hei de pôr isto diante de cem homens? Ao que tornou Eliseu: Dá-o ao povo, para que coma; porque assim diz o Senhor: Comerão e sobejará.

[[v12-4-44]]

^<<v12-4-44,44>>^ Então lhos pôs diante; e comeram, e ainda sobrou, conforme a palavra do Senhor.

'''

xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]