include::./index.adoc[]

[[v12-12-0]]
=== 2 Reis, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-12-1]]

^<<v12-12-1,1>>^ Foi no ano sétimo de Jeú que Joás começou a reinar, e reinou quarenta anos em Jerusalém. O nome de sua mãe era Zíbia, de Berseba.

[[v12-12-2]]

^<<v12-12-2,2>>^ E Joás fez o que era reto aos olhos do Senhor todos os dias em que o sacerdote Jeoiada o instruiu.

[[v12-12-3]]

^<<v12-12-3,3>>^ Contudo os altos não foram tirados; o povo ainda sacrificava e queimava incenso neles.

[[v12-12-4]]

^<<v12-12-4,4>>^ Disse Joás aos sacerdotes: Todo o dinheiro das coisas consagradas que se trouxer à casa do Senhor, o dinheiro daquele que passa o arrolamento, o dinheiro de cada uma das pessoas, segundo a sua avaliação, e todo o dinheiro que cada um trouxer voluntariamente para a casa do Senhor,

[[v12-12-5]]

^<<v12-12-5,5>>^ recebam-no os sacerdotes, cada um dos seus conhecidos, e reparem os estragos da casa, todo estrago que se achar nela.

[[v12-12-6]]

^<<v12-12-6,6>>^ Sucedeu porém que, no vigésimo terceiro ano do rei Joás, os sacerdotes ainda não tinham reparado os estragos da casa.

[[v12-12-7]]

^<<v12-12-7,7>>^ Então o rei Joás chamou o sacerdote Jeoiada e os demais sacerdotes, e lhes disse: Por que não reparais os estragos da casa? Agora, pois, não tomeis mais dinheiro de vossos conhecidos, mas entregai-o para o reparo dos estragos da casa.

[[v12-12-8]]

^<<v12-12-8,8>>^ E consentiram os sacerdotes em não tomarem mais dinheiro do povo, e em não mais serem os encarregados de reparar os estragos da casa.

[[v12-12-9]]

^<<v12-12-9,9>>^ Mas o sacerdote Jeoiada tomou uma arca , fez um buraco na tampa, e a pôs ao pé do altar, à mão direita de quem entrava na casa do Senhor. E os sacerdotes que guardavam a entrada metiam ali todo o dinheiro que se trazia à casa do Senhor.

[[v12-12-10]]

^<<v12-12-10,10>>^ Sucedeu pois que, vendo eles que já havia muito dinheiro na arca, o escrivão do rei e o sumo sacerdote vinham, e ensacavam e contavam o dinheiro que se achava na casa do Senhor.

[[v12-12-11]]

^<<v12-12-11,11>>^ E entregavam o dinheiro, depois de pesado, nas mãos dos que faziam a obra e que tinham a seu cargo a casa do Senhor; e eles o distribuíam aos carpinteiros, e aos edificadores que reparavam a casa do Senhor;

[[v12-12-12]]

^<<v12-12-12,12>>^ como também aos pedreiros e aos cabouqueiros; e para se comprar madeira e pedras de cantaria a fim de repararem os estragos da casa do Senhor, e para tudo quanto exigia despesa para se reparar a casa.

[[v12-12-13]]

^<<v12-12-13,13>>^ Todavia, do dinheiro que se trazia à casa do Senhor, não se faziam nem taças de prata, nem espevitadeiras, nem bacias, nem trombetas, nem vaso algum de ouro ou de prata para a casa do Senhor;

[[v12-12-14]]

^<<v12-12-14,14>>^ porque o davam aos que faziam a obra, os quais reparavam com ele a casa do Senhor.

[[v12-12-15]]

^<<v12-12-15,15>>^ E não se tomavam contas aos homens em cujas mãos entregavam aquele dinheiro para o dar aos que faziam a obra, porque eles se haviam com fidelidade.

[[v12-12-16]]

^<<v12-12-16,16>>^ Mas o dinheiro das ofertas pela culpa, e o dinheiro das ofertas pelo pecado, não se trazia à casa do Senhor; era para os sacerdotes.

[[v12-12-17]]

^<<v12-12-17,17>>^ Então subiu Hazael, rei da Síria, e pelejou contra Gate, e a tomou. Depois Hazael virou o rosto para marchar contra Jerusalém.

[[v12-12-18]]

^<<v12-12-18,18>>^ Pelo que Joás, rei de Judá, tomou todas as coisas consagradas que Jeosafá, Jeorão e Acazias, seus pais, reis de Judá, tinham consagrado, e tudo o que ele mesmo tinha oferecido, como também todo o ouro que se achou nos tesouros da casa do Senhor e na casa do rei, e o mandou a Hazael, rei da Síria, o qual se desviou de Jerusalém.

[[v12-12-19]]

^<<v12-12-19,19>>^ Ora, o restante dos atos de Joás, e tudo quanto fez, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-12-20]]

^<<v12-12-20,20>>^ Levantaram-se os servos de Joás e, conspirando contra ele, o feriram na casa de Milo, junto ao caminho que desce para Sila.

[[v12-12-21]]

^<<v12-12-21,21>>^ Foram Jozacar, filho de Simeate, e Jeozabade, filho de Somer, seus servos que o feriram, e ele morreu. Sepultaram-no com seus pais na cidade de Davi. E Amazias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[Próximo Capítulo &#62;]