include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-9-1]]

^<<v12-9-1,1>>^ Depois o profeta Eliseu chamou um dos filhos dos profetas, e lhe disse: Cinge os teus lombos, toma na mão este vaso de azeite e vai a Ramote-Gileade;

[[v12-9-2]]

^<<v12-9-2,2>>^ quando lá chegares, procura a Jeú, filho de Jeosafá, filho de Ninsi; entra, faze que ele se levante do meio de seus irmãos, e leva-o para uma câmara interior.

[[v12-9-3]]

^<<v12-9-3,3>>^ Toma, então, o vaso de azeite, derrama-o sobre a sua cabeça, e dize: Assim diz o Senhor: Ungi-te rei sobre Israel. Então abre a porta, foge e não te detenhas.

[[v12-9-4]]

^<<v12-9-4,4>>^ Foi, pois, o jovem profeta, a Ramote-Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ E quando chegou, eis que os chefes do exército estavam sentados ali; e ele disse: Chefe, tenho uma palavra para te dizer. E Jeú perguntou: A qual de todos nós? Respondeu ele: A ti, chefe!

[[v12-9-6]]

^<<v12-9-6,6>>^ Então Jeú se levantou, e entrou na casa; e o mancebo derramou-lhe o azeite sobre a cabeça, e lhe disse: Assim diz o Senhor Deus de Israel: Ungi-te rei sobre o povo do Senhor, sobre Israel.

[[v12-9-7]]

^<<v12-9-7,7>>^ Ferirás a casa de Acabe, teu senhor, para que eu vingue da mão de Jezabel o sangue de meus servos, os profetas, e o sangue de todos os servos do Senhor.

[[v12-9-8]]

^<<v12-9-8,8>>^ Pois toda a casa de Acabe perecerá; e destruirei de Acabe todo filho varão, tanto o escravo como o livre em Israel.

[[v12-9-9]]

^<<v12-9-9,9>>^ Porque hei de fazer a casa de Acabe como a casa de Jeroboão, filho de Nebate, e como a casa de Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ Os cães comerão a Jezabel no campo de Jizreel; não haverá quem a enterre. Então o mancebo abriu a porta e fugiu.

[[v12-9-11]]

^<<v12-9-11,11>>^ Saiu então Jeú aos servos de seu senhor; e um lhe perguntou: Vai tudo bem? Por que veio a ti esse louco? E ele lhes respondeu: Bem conheceis o homem e o seu falar.

[[v12-9-12]]

^<<v12-9-12,12>>^ Mas eles replicaram. É mentira; dize-no-lo, pedimos-te. Ao que disse Jeú: Assim e assim ele me falou, dizendo: Assim diz o Senhor: Ungi-te rei sobre Israel.

[[v12-9-13]]

^<<v12-9-13,13>>^ Então se apressaram, e cada um tomou a sua capa e a pôs debaixo dele, no mais alto degrau; e tocaram a buzina, e disseram: Jeú reina!

[[v12-9-14]]

^<<v12-9-14,14>>^ Assim Jeú, filho de Jeosafá, filho de Ninsi, conspirou contra Jorão. &#123;Ora, tinha Jorão cercado a Ramote-Gileade, ele e todo o Israel, por causa de Hazael, rei da Síria;

[[v12-9-15]]

^<<v12-9-15,15>>^ porém o rei Jorão tinha voltado para se curar em Jizreel das feridas que os sírios lhe fizeram, quando pelejou contra Hazael, rei da Síria.&#125; E disse Jeú: Se isto é o vosso parecer, ninguém escape nem saia da cidade para ir dar a nova em Jizreel.

[[v12-9-16]]

^<<v12-9-16,16>>^ Então Jeú subiu a um carro, e foi a Jizreel; porque Jorão estava acamado ali; e também Acazias, rei de Judá, descera para ver Jorão.

[[v12-9-17]]

^<<v12-9-17,17>>^ O atalaia que estava na torre de Jizreel viu a tropa de Jeú, que vinha e disse: Vejo uma tropa. Disse Jorão: Toma um cavaleiro, e envia-o ao seu encontro a perguntar: Há paz?

[[v12-9-18]]

^<<v12-9-18,18>>^ E o cavaleiro lhe foi ao encontro, e disse: Assim diz o rei: Há paz? Respondeu Jeú: Que tens tu que fazer com a paz? Passa para trás de mim. E o atalaia deu aviso, dizendo: Chegou a eles o mensageiro, porém não volta.

[[v12-9-19]]

^<<v12-9-19,19>>^ Então Jorão enviou outro cavaleiro; e, chegando este a eles, disse Assim diz o rei: Há paz? Respondeu Jeú: Que tens tu que fazer com a paz? Passa para trás de mim.

[[v12-9-20]]

^<<v12-9-20,20>>^ E o atalaia deu aviso, dizendo: Também este chegou a eles, porém não volta; e o andar se parece com o andar de Jeú, filho de Ninsi porque anda furiosamente.

[[v12-9-21]]

^<<v12-9-21,21>>^ Disse Jorão: Aparelha-me o carro! E lho aparelharam. Saiu Jorão, rei de Israel, com Acazias, rei de Judá, cada um em seu carro para irem ao encontro de Jeú, e o encontraram no campo de Nabote, o jizreelita.

[[v12-9-22]]

^<<v12-9-22,22>>^ E sucedeu que, vendo Jorão a Jeú, perguntou: Há paz, Jeú? Respondeu ele: Que paz, enquanto as prostituições da tua mãe Jezabel e as suas feitiçarias são tantas?

[[v12-9-23]]

^<<v12-9-23,23>>^ Então Jorão deu volta, e fugiu, dizendo a Acazias: Há traição, Acazias!

[[v12-9-24]]

^<<v12-9-24,24>>^ Mas Jeú, entesando o seu arco com toda a força, feriu Jorão entre as espáduas, e a flecha lhe saiu pelo coração; e ele caiu no seu carro.

[[v12-9-25]]

^<<v12-9-25,25>>^ Disse então Jeú a Bidcar, seu ajudante: Levanta-o, e lança-o no campo da herança de Nabote, o jizreelita; pois lembra-te de indo eu e tu juntos a cavalo após seu pai Acabe, o Senhor pôs sobre ele esta sentença, dizendo:

[[v12-9-26]]

^<<v12-9-26,26>>^ Certamente vi ontem o sangue de Nabote e o sangue de seus filhos, diz o Senhor; e neste mesmo campo te retribuirei, diz o Senhor. Agora, pois, levanta-o, e lança-o neste campo, conforme a palavra do Senhor.

[[v12-9-27]]

^<<v12-9-27,27>>^ Quando Acazias, rei de Judá, viu isto, fugiu pelo caminho da casa do jardim. E Jeú o perseguiu, dizendo: A este também! Matai-o! Então o feriram no carro, à subida de Gur, que está junto a Ibleão; mas ele fugiu para Megido, e ali morreu.

[[v12-9-28]]

^<<v12-9-28,28>>^ E seus servos o levaram num carro a Jerusalém, e o sepultaram na sua sepultura junto a seus pais, na cidade de Davi.

[[v12-9-29]]

^<<v12-9-29,29>>^ Ora, Acazias começara a reinar sobre Judá no ano undécimo de Jorão, filho de Acabe.

[[v12-9-30]]

^<<v12-9-30,30>>^ Depois Jeú veio a Jizreel; o que ouvindo Jezabel, pintou-se em volta dos olhos, e enfeitou a sua cabeça, e olhou pela janela.

[[v12-9-31]]

^<<v12-9-31,31>>^ Quando Jeú entrava pela porta, disse ela: Teve paz Zinri, que matou a seu senhor ?

[[v12-9-32]]

^<<v12-9-32,32>>^ Ao que ele levantou o rosto para a janela e disse: Quem é comigo? quem? E dois ou três eunucos olharam para ele.

[[v12-9-33]]

^<<v12-9-33,33>>^ Então disse ele: Lançai-a daí abaixo. E lançaram-na abaixo; e foram salpicados com o sangue dela a parede e os cavalos; e ele a atropelou.

[[v12-9-34]]

^<<v12-9-34,34>>^ E tendo ele entrado, comeu e bebeu; depois disse: Olhai por aquela maldita, e sepultai-a, porque é filha de rei.

[[v12-9-35]]

^<<v12-9-35,35>>^ Foram, pois, para a sepultar; porém não acharam dela senão a caveira, os pés e as palmas das mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Então voltaram, e lho disseram. Pelo que ele disse: Esta é a palavra do Senhor, que ele falou por intermédio de Elias, o tisbita, seu servo, dizendo: No campo de Jizreel os cães comerão a carne de Jezabel,

[[v12-9-37]]

^<<v12-9-37,37>>^ e o seu cadáver será como esterco sobre o campo, na herdade de Jizreel; de modo que não se poderá dizer: Esta é Jezabel.

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]