include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-3-1]]

^<<v12-3-1,1>>^ Ora, Jorão, filho de Acabe, começou a reinar sobre Israel, em Samária, no décimo oitavo ano de Jeosafá, rei de Judá, e reinou doze anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ Fez o que era mau aos olhos do Senhor, porém não como seu pai, nem como sua mãe; pois tirou a coluna de Baal que seu pai fizera.

[[v12-3-3]]

^<<v12-3-3,3>>^ Contudo aderiu aos pecados de Jeroboão, filho de Nebate, com que este fizera Israel pecar, e deles não se apartou.

[[v12-3-4]]

^<<v12-3-4,4>>^ Ora, Messa, rei dos moabitas, era criador de ovelhas, e pagava de tributo ao rei de Israel cem mil cordeiros, e cem mil carneiros com a sua lã.

[[v12-3-5]]

^<<v12-3-5,5>>^ Sucedeu, porém, que, morrendo Acabe, o rei dos moabitas se rebelou contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Por isso, nesse mesmo tempo Jorão saiu de Samária e fez revista de todo o Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ E, pondo-se em marcha, mandou dizer a Jeosafá, rei de Judá: O rei dos moabitas rebelou-se contra mim; irás tu comigo a guerra contra os moabitas? Respondeu ele: Irei; como tu és sou eu, o meu povo como o teu povo, e os meus cavalos como os teus cavalos.

[[v12-3-8]]

^<<v12-3-8,8>>^ E perguntou: Por que caminho subiremos? Respondeu-lhe Jorão: Pelo caminho do deserto de Edom.

[[v12-3-9]]

^<<v12-3-9,9>>^ Partiram, pois, o rei de Israel, o rei de Judá e o rei de Edom; e andaram rodeando durante sete dias; e não havia água para o exército nem para o gado que os seguia.

[[v12-3-10]]

^<<v12-3-10,10>>^ Disse então o rei de Israel: Ah! o Senhor chamou estes três reis para entregá-los nas mãos dos moabitas.

[[v12-3-11]]

^<<v12-3-11,11>>^ Perguntou, porém, Jeosafá: Não há aqui algum profeta do Senhor por quem consultemos ao Senhor? Então respondeu um dos servos do rei de Israel, e disse: Aqui está Eliseu, filho de Safate, que deitava água sobre as mãos de Elias.

[[v12-3-12]]

^<<v12-3-12,12>>^ Disse Jeosafá: A palavra do Senhor está com ele. Então o rei de Israel, e Jeosafá, e o rei de Edom desceram a ter com ele.

[[v12-3-13]]

^<<v12-3-13,13>>^ Eliseu disse ao rei de Israel: Que tenho eu contigo? Vai ter com os profetas de teu pai, e com os profetas de tua mãe. O rei de Israel, porém, lhe disse: Não; porque o Senhor chamou estes três reis para entregá-los nas mãos dos moabitas.

[[v12-3-14]]

^<<v12-3-14,14>>^ Respondeu Eliseu: Vive o Senhor dos exércitos, em cuja presença estou, que se eu não respeitasse a presença de Jeosafá, rei de Judá, não te contemplaria, nem te veria.

[[v12-3-15]]

^<<v12-3-15,15>>^ Agora, contudo, trazei-me um harpista. E sucedeu que, enquanto o harpista tocava, veio a mão do Senhor sobre Eliseu.

[[v12-3-16]]

^<<v12-3-16,16>>^ E ele disse: Assim diz o Senhor: Fazei neste vale muitos poços.

[[v12-3-17]]

^<<v12-3-17,17>>^ Porque assim diz o Senhor: Não vereis vento, nem vereis chuva; contudo este vale se encherá de água, e bebereis vós, os vossos servos e os vossos animais.

[[v12-3-18]]

^<<v12-3-18,18>>^ E ainda isso é pouco aos olhos do Senhor; também entregará ele os moabitas nas vossas mãos,

[[v12-3-19]]

^<<v12-3-19,19>>^ e ferireis todas as cidades fortes e todas as cidades escolhidas, cortareis todas as boas árvores, tapareis todas as fontes d'água, e cobrireis de pedras todos os bons campos.

[[v12-3-20]]

^<<v12-3-20,20>>^ E sucedeu que, pela manhã, à hora de se oferecer o sacrifício, eis que vinham as águas pelo caminho de Edom, e a terra se encheu d'água:

[[v12-3-21]]

^<<v12-3-21,21>>^ Ouvindo, pois, todos os moabitas que os reis tinham subido para pelejarem contra eles, convocaram-se todos os que estavam em idade de pegar armas, e daí para cima, e puseram-se às fronteiras.

[[v12-3-22]]

^<<v12-3-22,22>>^ Levantaram-se os moabitas de madrugada e, resplandecendo o sol sobre as águas, viram diante de si as águas vermelhas como sangue;

[[v12-3-23]]

^<<v12-3-23,23>>^ e disseram: Isto é sangue; certamente os reis pelejaram entre si e se mataram um ao outro! Agora, pois, à presa, moabitas!

[[v12-3-24]]

^<<v12-3-24,24>>^ Quando, porém, chegaram ao arraial de Israel, os israelitas se levantaram, e bateram os moabitas, os quais fugiram diante deles; e ainda entraram na terra, ferindo ali também os moabitas.

[[v12-3-25]]

^<<v12-3-25,25>>^ E arrasaram as cidades; e cada um deles lançou pedras em todos os bons campos, entulhando-os; taparam todas as fontes d'água, e cortaram todas as boas árvores; somente a Quir-Haresete deixaram ficar as pedras; contudo os fundeiros a cercaram e a feriram.

[[v12-3-26]]

^<<v12-3-26,26>>^ Vendo o rei dos moabitas que a peleja prevalecia contra ele, tomou consigo setecentos homens que arrancavam da espada, para romperem contra o rei de Edom; porém não puderam.

[[v12-3-27]]

^<<v12-3-27,27>>^ Então tomou a seu filho primogênito, que havia de reinar em seu lugar, e o ofereceu em holocausto sobre o muro, pelo que houve grande indignação em Israel; por isso retiraram-se dele, e voltaram para a sua terra.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]