include::./index.adoc[]

[[v12-5-0]]
=== 2 Reis, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-5-1]]

^<<v12-5-1,1>>^ Ora, Naamã, chefe do exército do rei da Síria, era um grande homem diante do seu senhor, e de muito respeito, porque por ele o Senhor dera livramento aos sírios; era homem valente, porém leproso.

[[v12-5-2]]

^<<v12-5-2,2>>^ Os sírios, numa das suas investidas, haviam levado presa, da terra de Israel, uma menina que ficou ao serviço da mulher de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Disse ela a sua senhora: Oxalá que o meu senhor estivesse diante do profeta que está em Samária! Pois este o curaria da sua lepra.

[[v12-5-4]]

^<<v12-5-4,4>>^ Então Naamã foi notificar a seu senhor, dizendo: Assim e assim falou a menina que é da terra de Israel.

[[v12-5-5]]

^<<v12-5-5,5>>^ Respondeu o rei da Síria: Vai, anda, e enviarei uma carta ao rei de Israel. Foi, pois, e levou consigo dez talentos de prata, e seis mil siclos de ouro e dez mudas de roupa.

[[v12-5-6]]

^<<v12-5-6,6>>^ Também levou ao rei de Israel a carta, que dizia: Logo, em chegando a ti esta carta, saberás que eu te enviei Naamã, meu servo, para que o cures da sua lepra.

[[v12-5-7]]

^<<v12-5-7,7>>^ Tendo o rei de Israel lido a carta, rasgou as suas vestes, e disse: Sou eu Deus, que possa matar e vivificar, para que este envie a mim um homem a fim de que eu o cure da sua lepra? Notai, peço-vos, e vede como ele anda buscando ocasião contra mim.

[[v12-5-8]]

^<<v12-5-8,8>>^ Quando Eliseu, o homem de Deus, ouviu que o rei de Israel rasgara as suas vestes, mandou dizer ao rei: Por que rasgaste as tuas vestes? Deixa-o vir ter comigo, e saberá que há profeta em Israel.

[[v12-5-9]]

^<<v12-5-9,9>>^ Veio, pois, Naamã com os seus cavalos, e com o seu carro, e parou à porta da casa de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ Então este lhe mandou um mensageiro, a dizer-lhe: Vai, lava-te sete vezes no Jordão, e a tua carne tornará a ti, e ficarás purificado.

[[v12-5-11]]

^<<v12-5-11,11>>^ Naamã, porém, indignado, retirou-se, dizendo: Eis que pensava eu: Certamente ele sairá a ter comigo, pôr-se-á em pé, invocará o nome do Senhor seu Deus, passará a sua mão sobre o lugar, e curará o leproso.

[[v12-5-12]]

^<<v12-5-12,12>>^ Não são, porventura, Abana e Farpar, rios de Damasco, melhores do que todas as águas de Israel? não poderia eu lavar-me neles, e ficar purificado? Assim se voltou e se retirou com indignação.

[[v12-5-13]]

^<<v12-5-13,13>>^ Os seus servos, porém, chegaram-se a ele e lhe falaram, dizendo: Meu pai, se o profeta te houvesse indicado alguma coisa difícil, porventura não a terias cumprido? Quanto mais, dizendo-te ele: Lava-te, e ficarás purificado.

[[v12-5-14]]

^<<v12-5-14,14>>^ Desceu ele, pois, e mergulhou-se no Jordão sete vezes, conforme a palavra do homem de Deus; e a sua carne tornou-se como a carne dum menino, e ficou purificado.

[[v12-5-15]]

^<<v12-5-15,15>>^ Então voltou ao homem de Deus, ele e toda a sua comitiva; chegando, pôs-se diante dele, e disse: Eis que agora sei que em toda a terra não há Deus senão em Israel; agora, pois, peço-te que do teu servo recebas um presente.

[[v12-5-16]]

^<<v12-5-16,16>>^ Ele, porém, respondeu: Vive o Senhor, em cuja presença estou, que não o receberei. Naamã instou com ele para que o tomasse; mas ele recusou.

[[v12-5-17]]

^<<v12-5-17,17>>^ Ao que disse Naamã: Seja assim; contudo dê-se a este teu servo terra que baste para carregar duas mulas; porque nunca mais oferecerá este teu servo holocausto nem sacrifício a outros deuses, senão ao Senhor.

[[v12-5-18]]

^<<v12-5-18,18>>^ Nisto perdoe o Senhor ao teu servo: Quando meu amo entrar na casa de Rimom para ali adorar, e ele se apoiar na minha mão, e eu também me tenha de encurvar na casa de Rimom; quando assim me encurvar na casa de Rimom, nisto perdoe o Senhor ao teu servo.

[[v12-5-19]]

^<<v12-5-19,19>>^ Eliseu lhe disse: Vai em paz.

[[v12-5-20]]

^<<v12-5-20,20>>^ Quando Naamã já ia a uma pequena distância, Geazi, moço de Eliseu, o homem de Deus, disse: Eis que meu senhor poupou a este sírio Naamã, não recebendo da mão dele coisa alguma do que trazia; vive o Senhor, que hei de correr atrás dele, e receber dele alguma coisa.

[[v12-5-21]]

^<<v12-5-21,21>>^ Foi pois, Geazi em alcance de Naamã. Este, vendo que alguém corria atrás dele, saltou do carro a encontrá-lo, e perguntou: Vai tudo bem?

[[v12-5-22]]

^<<v12-5-22,22>>^ Respondeu ele: Tudo vai bem. Meu senhor me enviou a dizer-te: Eis que agora mesmo vieram a mim dois mancebos dos filhos dos profetas da região montanhosa de Efraim; dá-lhes, pois, um talento de prata e duas mudas de roupa.

[[v12-5-23]]

^<<v12-5-23,23>>^ Disse Naamã: Sê servido de tomar dois talentos. E instou com ele, e amarrou dois talentos de prata em dois sacos, com duas mudas de roupa, e pô-los sobre dois dos seus moços, os quais os levaram adiante de Geazi.

[[v12-5-24]]

^<<v12-5-24,24>>^ Tendo ele chegado ao outeiro, tomou-os das mãos deles e os depositou na casa; e despediu aqueles homens, e eles se foram.

[[v12-5-25]]

^<<v12-5-25,25>>^ Mas ele entrou e pôs-se diante de seu amo. Então lhe perguntou Eliseu: Donde vens, Geazi? Respondeu ele: Teu servo não foi a parte alguma.

[[v12-5-26]]

^<<v12-5-26,26>>^ Eliseu porém, lhe disse: Porventura não foi contigo o meu coração, quando aquele homem voltou do seu carro ao teu encontro? Era isto ocasião para receberes prata e roupa, olivais e vinhas, ovelhas e bois, servos e servas?

[[v12-5-27]]

^<<v12-5-27,27>>^ Portanto a lepra de Naamã se pegará a ti e à tua descendência para sempre. Então Geazi saiu da presença dele leproso, branco como a neve.

'''

xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]