include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-21-1]]

^<<v12-21-1,1>>^ Manassés tinha doze anos quando começou a reinar, e reinou cinqüenta e cinco anos em Jerusalém. O nome de sua mãe era Hefzibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ E fez o que era mau aos olhos do Senhor, conforme as abominações das nações que o Senhor desterrara de diante dos filhos de Israel.

[[v12-21-3]]

^<<v12-21-3,3>>^ Porque tornou a edificar os altos que Ezequias, seu pai, tinha destruído, e levantou altares a Baal, e fez uma Asera como a que fizera Acabe, rei de Israel, e adorou a todo o exército do céu, e os serviu.

[[v12-21-4]]

^<<v12-21-4,4>>^ E edificou altares na casa do Senhor, da qual o Senhor tinha dito: Em Jerusalém porei o meu nome.

[[v12-21-5]]

^<<v12-21-5,5>>^ Também edificou altares a todo o exército do céu em ambos os átrios da casa do Senhor.

[[v12-21-6]]

^<<v12-21-6,6>>^ E até fez passar seu filho pelo fogo, e usou de augúrios e de encantamentos, e instituiu adivinhos e feiticeiros; fez muito mal aos olhos do Senhor, provocando-o à ira.

[[v12-21-7]]

^<<v12-21-7,7>>^ Também pôs a imagem esculpida de Asera, que tinha feito, na casa de que o Senhor dissera a Davi e a Salomão, seu filho: Nesta casa e em Jerusalém, que escolhi dentre todas as tribos de Israel, porei o meu nome para sempre;

[[v12-21-8]]

^<<v12-21-8,8>>^ e não mais farei andar errante o pé de Israel desta terra que tenho dado a seus pais, contanto que somente tenham cuidado de fazer conforme tudo o que lhes tenho ordenado, e conforme toda a lei que Moisés, meu servo, lhes ordenou.

[[v12-21-9]]

^<<v12-21-9,9>>^ Eles, porém, não ouviram; porque Manassés de tal modo os fez errar, que fizeram pior do que as nações que o Senhor tinha destruído de diante dos filhos de Israel.

[[v12-21-10]]

^<<v12-21-10,10>>^ Então o Senhor falou por intermédio de seus servos os profetas, dizendo:

[[v12-21-11]]

^<<v12-21-11,11>>^ Porquanto Manassés, rei de Judá, cometeu estas abominações, fazendo pior do que tudo quanto fizeram os amorreus, que foram antes dele, e com os seus ídolos fez Judá também pecar;

[[v12-21-12]]

^<<v12-21-12,12>>^ por isso assim diz o Senhor Deus de Israel: Eis que trago tais males sobre Jerusalém e Judá, que a qualquer que deles ouvir lhe ficarão retinindo ambos os ouvidos.

[[v12-21-13]]

^<<v12-21-13,13>>^ Estenderei sobre Jerusalém o cordel de Samária e o prumo da casa de Acabe; e limparei Jerusalém como quem limpa a escudela, limpando-a e virando-a sobre a sua face.

[[v12-21-14]]

^<<v12-21-14,14>>^ Desampararei os restantes da minha herança, e os entregarei na mão de seus inimigos. tornar-se-ão presa e despojo para todos os seus inimigos;

[[v12-21-15]]

^<<v12-21-15,15>>^ porquanto fizeram o que era mau aos meus olhos, e me provocaram à ira, desde o dia em que seus pais saíram do Egito até hoje.

[[v12-21-16]]

^<<v12-21-16,16>>^ Além disso, Manassés derramou muitíssimo sangue inocente, até que encheu Jerusalém de um a outro extremo, afora o seu pecado com que fez Judá pecar fazendo o que era mau aos olhos do Senhor.

[[v12-21-17]]

^<<v12-21-17,17>>^ Quanto ao restante dos atos de Manassés, e a tudo quanto fez, e ao pecado que cometeu, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-21-18]]

^<<v12-21-18,18>>^ E Manassés dormiu com seus pais, e foi sepultado no jardim da sua casa, no jardim de Uzá. E Amom, seu filho, reinou em seu lugar.

[[v12-21-19]]

^<<v12-21-19,19>>^ Amom tinha vinte e dois anos quando começou a reinar, e reinou dois anos em Jerusalém. O nome de sua mãe era Mesulemete, filha de Haniz, de Jotba.

[[v12-21-20]]

^<<v12-21-20,20>>^ Ele fez o que era mau aos olhos do Senhor, como fizera Manassés, seu pai;

[[v12-21-21]]

^<<v12-21-21,21>>^ e andou em todo o caminho em que seu pai andara, e serviu os ídolos que ele tinha servido, e os adorou.

[[v12-21-22]]

^<<v12-21-22,22>>^ Assim deixou o Senhor, Deus de seus pais, e não andou no caminho do Senhor.

[[v12-21-23]]

^<<v12-21-23,23>>^ E os servos de Amom conspiraram contra ele, e o mataram em sua casa.

[[v12-21-24]]

^<<v12-21-24,24>>^ O povo da terra, porém, matou a todos os que conspiraram contra o rei Amom, e constituiu Josias, seu filho, rei em seu lugar.

[[v12-21-25]]

^<<v12-21-25,25>>^ Quanto ao restante dos atos de Amom, porventura não está escrito no livro das crônicas dos reis de Judá?

[[v12-21-26]]

^<<v12-21-26,26>>^ E o puseram na sua sepultura, no jardim de Uzá. E Josias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]