include::./index.adoc[]

[[v12-19-0]]
=== 2 Reis, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-19-1]]

^<<v12-19-1,1>>^ Quando o rei Ezequias ouviu isto rasgou as suas vestes, cobriu-se de saco, e entrou na casa do Senhor.

[[v12-19-2]]

^<<v12-19-2,2>>^ Então enviou Eliaquim, o mordomo, e Sebna, o escrivão, e os anciãos dos sacerdotes, cobertos de sacos, ao profeta Isaías, filho de Amoz.

[[v12-19-3]]

^<<v12-19-3,3>>^ Eles lhe disseram: Assim diz Ezequias: Este dia é dia de angústia, de vituperação e de blasfêmia; porque os filhos chegaram ao parto, e não há força para os dar à luz.

[[v12-19-4]]

^<<v12-19-4,4>>^ Bem pode ser que o Senhor teu Deus tenha ouvido todas as palavras de Rabsaque, a quem o seu senhor, o rei da Assiria, enviou para afrontar o Deus vivo, e repreenda as palavras que o senhor teu Deus ouviu. Faze, pois, oração pelo resto que ainda fica.

[[v12-19-5]]

^<<v12-19-5,5>>^ Foram, pois, os servos do rei Ezequias ter com Isaias.

[[v12-19-6]]

^<<v12-19-6,6>>^ E Isaías lhes disse: Assim direis a vosso senhor: Assim diz o Senhor: Não temas as palavras que ouviste, com as quais os servos do rei da Assíria me blasfemaram.

[[v12-19-7]]

^<<v12-19-7,7>>^ Eis que meterei nele um espírito, e ele ouvirá uma nova, e voltará para a sua terra; e à espada o farei cair na sua terra.

[[v12-19-8]]

^<<v12-19-8,8>>^ Voltou, pois, Rabsaqué e achou o rei da Assíria pelejando contra Libna, porque soubera que o rei havia partido de Laquis.

[[v12-19-9]]

^<<v12-19-9,9>>^ E o rei, ouvindo dizer acerca de Tiraca, rei da Etiópia: Eis que saiu para te fazer guerra, tornou a enviar mensageiros a Ezequias, dizendo:

[[v12-19-10]]

^<<v12-19-10,10>>^ Assim falareis a Ezequias, rei de Judá: Não te engane o teu Deus, em quem confias, dizendo: Jerusalém não será entregue na mão do rei da Assíria.

[[v12-19-11]]

^<<v12-19-11,11>>^ Eis que já tens ouvido o que os reis da Assíria fizeram a todas as terras, destruindo-as totalmente; e tu serias poupado?

[[v12-19-12]]

^<<v12-19-12,12>>^ Porventura os deuses das nações a quem meus pais destruíram, puderam livrá-las, a saber, Gozã, Harã, Rezefe, e os filhos de Eden que estavam em Telassar?

[[v12-19-13]]

^<<v12-19-13,13>>^ Que é feito do rei de Hamate, do rei de Arpade, do rei da cidade de Sefarvaim, de Hena e de Iva?

[[v12-19-14]]

^<<v12-19-14,14>>^ Ezequias, pois, tendo recebido a carta das mãos dos mensageiros, e tendo-a lido, subiu à casa do Senhor, e a estendeu perante o Senhor.

[[v12-19-15]]

^<<v12-19-15,15>>^ E Ezequias orou perante o Senhor, dizendo: Ó Senhor Deus de Israel, que estás assentado sobre os querubins, tu mesmo, só tu és Deus de todos os reinos da terra; tu fizeste o céu e a terra.

[[v12-19-16]]

^<<v12-19-16,16>>^ Inclina, ó Senhor, o teu ouvido, e ouve; abre, ó Senhor, os teus olhos, e vê; e ouve as palavras de Senaqueribe, com as quais enviou seu mensageiro para afrontar o Deus vivo.

[[v12-19-17]]

^<<v12-19-17,17>>^ Verdade é, ó Senhor, que os reis da Assíria têm assolado as nações e as suas terras,

[[v12-19-18]]

^<<v12-19-18,18>>^ e lançado os seus deuses no fogo porquanto não eram deuses mas obra de mãos de homens, madeira e pedra; por isso os destruíram.

[[v12-19-19]]

^<<v12-19-19,19>>^ Agora, pois, Senhor nosso Deus, livra-nos da sua mão, para que todos os reinos da terra saibam que só tu, Senhor, és Deus.

[[v12-19-20]]

^<<v12-19-20,20>>^ Então Isaías, filho de Amoz, mandou dizer a Ezequias: Assim diz o Senhor Deus de Israel: Ouvi o que me pediste no tocante a Senaqueribe, rei da Assíria.

[[v12-19-21]]

^<<v12-19-21,21>>^ Esta é a palavra que o Senhor falou a respeito dele: A virgem, a filha de Sião, te despreza e te escarnece; a filha de Jerusalém meneia a cabeça por detrás de ti.

[[v12-19-22]]

^<<v12-19-22,22>>^ A quem afrontaste e blasfemaste? E contra quem alçaste a voz, e ergueste os olhos ao alto? Contra o Santo de Israel!

[[v12-19-23]]

^<<v12-19-23,23>>^ Por meio de teus mensageiros afrontaste o Senhor, e disseste: Com a multidão de meus carros subi ao alto dos montes, aos lados do Líbano; cortei os seus altos cedros, e as suas mais formosas faias, e entrei na sua mais distante pousada, no bosque do seu campo fértil.

[[v12-19-24]]

^<<v12-19-24,24>>^ Eu cavei, e bebi águas estrangeiras; e com as plantas de meus pés sequei todos os rios do Egito.

[[v12-19-25]]

^<<v12-19-25,25>>^ Porventura não ouviste que já há muito tempo determinei isto, e já desde os dias antigos o planejei? Agora, porém, o executei, para que fosses tu que reduzisses as cidades fortificadas a montões desertos.

[[v12-19-26]]

^<<v12-19-26,26>>^ Por isso os moradores delas tiveram pouca força, ficaram pasmados e confundidos; tornaram-se como a erva do campo, como a relva verde, e como o feno dos telhados, que se queimam antes de amadurecer.

[[v12-19-27]]

^<<v12-19-27,27>>^ Eu, porém, conheço o teu assentar, o teu sair e o teu entrar, bem como o teu furor contra mim.

[[v12-19-28]]

^<<v12-19-28,28>>^ Por causa do teu furor contra mim, e porque a tua arrogância subiu aos meus ouvidos, porei o meu anzol no teu nariz e o meu freio na tua boca, e te farei voltar pelo caminho por onde vieste.

[[v12-19-29]]

^<<v12-19-29,29>>^ E isto te será por sinal: Este ano comereis o que nascer por si mesmo, e no ano seguinte que daí proceder; e no terceiro ano semeai e comei, e plantai vinhas, e comei os seus frutos.

[[v12-19-30]]

^<<v12-19-30,30>>^ Pois o que escapou da casa de Judá, e ficou de resto, tornará a lançar raízes para baixo, e dará fruto para cima.

[[v12-19-31]]

^<<v12-19-31,31>>^ Porque de Jerusalém sairá o restante, e do monte Sião os que escaparem; o zelo do Senhor fará isto.

[[v12-19-32]]

^<<v12-19-32,32>>^ Portanto, assim diz o Senhor acerca do rei da Assíria: Não entrará nesta cidade, nem lançará nela flecha alguma; tampouco virá perante ela com escudo, nem contra ela levantará tranqueira.

[[v12-19-33]]

^<<v12-19-33,33>>^ Pelo caminho por onde veio, por esse mesmo voltará, e nesta cidade não entrará, diz o Senhor.

[[v12-19-34]]

^<<v12-19-34,34>>^ Porque eu defenderei esta cidade para livrá-la, por amor de mim e por amor do meu servo Davi.

[[v12-19-35]]

^<<v12-19-35,35>>^ Sucedeu, pois, que naquela mesma noite saiu o anjo do Senhor, e feriu no arraial dos assírios a cento e oitenta e cinco mil deles: e, levantando-se os assírios pela manhã cedo, eis que aqueles eram todos cadáveres.

[[v12-19-36]]

^<<v12-19-36,36>>^ Então Senaqueribe, rei da Assíria, se retirou e, voltando, habitou em Nínive.

[[v12-19-37]]

^<<v12-19-37,37>>^ E quando ele estava adorando na casa de Nisroque, seu deus, Adrameleque e Sarezer, seus filhos, o mataram à espada e fugiram para a terra de Arará. E Esar-Hadom, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[Próximo Capítulo &#62;]