include::./index.adoc[]

[[v12-11-0]]
=== 2 Reis, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-11-1]]

^<<v12-11-1,1>>^ Vendo pois Atalia, mãe de Acazias, que seu filho era morto, levantou-se, e destruiu toda a descendência real.

[[v12-11-2]]

^<<v12-11-2,2>>^ Mas Jeoseba, filha do rei Jorão, irmã de Acazias, tomou a Joás, filho de Acazias, furtando-o dentre os filhos do rei, aos quais matavam na recâmara, e o escondeu de Ataliá, a ele e à sua ama, de sorte que não o mataram.

[[v12-11-3]]

^<<v12-11-3,3>>^ E esteve com ela escondido na casa do Senhor seis anos; e Atalia reinava sobre o país.

[[v12-11-4]]

^<<v12-11-4,4>>^ No sétimo ano, porém, Jeoiada mandou chamar os centuriões dos caritas e os oficiais da guarda, e fê-los entrar consigo na casa do Senhor; e fez com eles um pacto e, ajuramentando-os na casa do Senhor, mostrou-lhes o filho do rei.

[[v12-11-5]]

^<<v12-11-5,5>>^ Então lhes ordenou, dizendo: Eis aqui o que haveis de fazer: uma terça parte de vós, os que entrais no sábado, fará a guarda da casa do rei;

[[v12-11-6]]

^<<v12-11-6,6>>^ outra terça parte estará à porta Sur; e a outra terça parte à porta detrás dos da guarda. Assim fareis a guarda desta casa, afastando a todos.

[[v12-11-7]]

^<<v12-11-7,7>>^ As duas companhias, a saber, todos os que saem no sábado, farão a guarda da casa do Senhor junto ao rei;

[[v12-11-8]]

^<<v12-11-8,8>>^ e rodeareis o rei, cada um com as suas armas na mão, e aquele que entrar dentro das fileiras, seja morto; e estai vós com o rei quando sair e quando entrar.

[[v12-11-9]]

^<<v12-11-9,9>>^ Fizeram, pois, os centuriões conforme tudo quanto ordenara o sacerdote Jeoiada; e tomando cada um os seus homens, tanto os que entravam no sábado como os que saíam no sábado, vieram ter com o sacerdote Jeoiada.

[[v12-11-10]]

^<<v12-11-10,10>>^ O sacerdote entregou aos centuriões as lanças e os escudos que haviam sido do rei Davi, e que estavam na casa do Senhor.

[[v12-11-11]]

^<<v12-11-11,11>>^ E os da guarda, cada um com as armas na mão, se puseram em volta do rei, desde o lado direito da casa até o lado esquerdo, ao longo do altar e da casa.

[[v12-11-12]]

^<<v12-11-12,12>>^ Então Jeoiada lhes apresentou o filho do rei, pôs-lhe a coroa, e lhe deu o testemunho; e o fizeram rei e o ungiram e, batendo palmas, clamaram: Viva o rei!

[[v12-11-13]]

^<<v12-11-13,13>>^ Quando Atalia ouviu o vozerio da guarda e do povo, foi ter com o povo na casa do Senhor;

[[v12-11-14]]

^<<v12-11-14,14>>^ e olhou, e eis que o rei estava junto à coluna, conforme o costume, e os capitães e os trombeteiros junto ao rei; e todo o povo da terra se alegrava e tocava trombetas. Então Atalia rasgou os seus vestidos, e clamou: Traição! Traição!

[[v12-11-15]]

^<<v12-11-15,15>>^ Então Jeoiada, o sacerdote, deu ordem aos centuriões que comandavam as tropas, dizendo-lhes: Tirai-a para fora por entre as fileiras, e a quem a seguir matai-o à espada. Pois o sacerdote dissera: Não seja ela morta na casa do Senhor.

[[v12-11-16]]

^<<v12-11-16,16>>^ E lançaram-lhe as mãos e ela foi pelo caminho da entrada dos cavalos à casa do rei, e ali a mataram.

[[v12-11-17]]

^<<v12-11-17,17>>^ Ora, Jeoiada firmou um pacto entre o Senhor e o rei e o povo, pelo qual este seria o povo do Senhor; como também firmou pacto entre o rei e o povo.

[[v12-11-18]]

^<<v12-11-18,18>>^ Então todo o povo da terra entrou na casa de Baal, e a derrubaram; como também os seus altares, e as suas imagens, totalmente quebraram; e a Matã, sacerdote de Baal, mataram diante dos altares. Também o sacerdote pôs vigias sobre a casa do Senhor.

[[v12-11-19]]

^<<v12-11-19,19>>^ E tomou os centuriões, os caritas, a guarda, e todo o povo da terra; e conduziram da casa do Senhor o rei, e foram pelo caminho da porta da guarda, à casa do rei; e ele se assentou no trono dos reis.

[[v12-11-20]]

^<<v12-11-20,20>>^ E todo o povo da terra se alegrou, e a cidade ficou em paz, depois que mataram Atalia à espada junto à casa do rei.

[[v12-11-21]]

^<<v12-11-21,21>>^ Joás tinha sete anos quando começou a reinar.

'''

xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[Próximo Capítulo &#62;]