include::./index.adoc[]

[[v12-20-0]]
=== 2 Reis, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-20-1]]

^<<v12-20-1,1>>^ Por aquele tempo Ezequias ficou doente, à morte. O profeta Isaías, filho de Amoz, veio ter com ele, e lhe disse: Assim diz, o Senhor: Põe em ordem a tua casa porque morrerás, e não viverás.

[[v12-20-2]]

^<<v12-20-2,2>>^ Então o rei virou o rosto para a parede, e orou ao Senhor, dizendo:

[[v12-20-3]]

^<<v12-20-3,3>>^ Lembra-te agora, ó Senhor, te peço, de como tenho andado diante de ti com fidelidade e integridade de coração, e tenho feito o que era reto aos teus olhos. E Ezequias chorou muitíssimo.

[[v12-20-4]]

^<<v12-20-4,4>>^ E sucedeu que, não havendo Isaías ainda saído do meio do pátio, veio a ele a palavra do Senhor, dizendo:

[[v12-20-5]]

^<<v12-20-5,5>>^ Volta, e dize a Ezequias, príncipe do meu povo: Assim diz o Senhor Deus de teu pai Davi: Ouvi a tua oração, e vi as tuas lágrimas. Eis que eu te sararei; ao terceiro dia subirás à casa do Senhor.

[[v12-20-6]]

^<<v12-20-6,6>>^ Acrescentarei aos teus dias quinze anos; e das mãos do rei da Assíria te livrarei, a ti e a esta cidade; e defenderei esta cidade por amor de mim, e por amor do meu servo Davi.

[[v12-20-7]]

^<<v12-20-7,7>>^ Disse mais Isaías: Tomai uma pasta de figos e ponde-a sobre a úlcera; e ele sarará.

[[v12-20-8]]

^<<v12-20-8,8>>^ Perguntou, pois, Ezequias a Isaías: Qual é o sinal de que o Senhor me sarará, e de que ao terceiro dia subirei à casa do Senhor?

[[v12-20-9]]

^<<v12-20-9,9>>^ Respondeu Isaías: Isto te será sinal, da parte do Senhor, de que o Senhor cumprirá a palavra que disse: Adiantar-se-á a sombra dez graus, ou voltará dez graus atrás?

[[v12-20-10]]

^<<v12-20-10,10>>^ Então disse Ezequias: É fácil que a sombra decline dez graus; não seja assim, antes volte a sombra dez graus atrás.

[[v12-20-11]]

^<<v12-20-11,11>>^ Então o profeta Isaías clamou ao Senhor, que fez voltar a sombra dez graus atrás, pelos graus que já tinha declinado no relógio de sol de Acaz.

[[v12-20-12]]

^<<v12-20-12,12>>^ Naquele tempo Merodaque-Baladã, filho de Baladã, rei de Babilônia, enviou cartas e um presente a Ezequias, porque ouvira que Ezequias tinha estado doente.

[[v12-20-13]]

^<<v12-20-13,13>>^ E Ezequias deu audiência aos mensageiros, e lhes mostrou toda a casa de seu tesouro, a prata e o ouro, as especiarias e os melhores ungüentos, a sua casa de armas e tudo quanto havia nos seus tesouros; coisa nenhuma houve que lhes não mostrasse, nem em sua casa, nem em todo o seu domínio.

[[v12-20-14]]

^<<v12-20-14,14>>^ Então o profeta Isaías veio ao rei Ezequias, e lhe perguntou: Que disseram aqueles homens, e donde vieram a ti? Respondeu Ezequias: Vieram de um país mui remoto, de Babilônia.

[[v12-20-15]]

^<<v12-20-15,15>>^ E disse ele: Que viram em tua casa? E disse Ezequias: Viram tudo quanto há em minha casa; não há coisa nenhuma nos meus tesouros que eu não lhes mostrasse.

[[v12-20-16]]

^<<v12-20-16,16>>^ Então disse Isaías a Ezequias: Ouve a palavra do Senhor:

[[v12-20-17]]

^<<v12-20-17,17>>^ Eis que vêm dias em que será levado para a Babilônia tudo quanto houver em minha casa, bem como o que os teus pais entesouraram até o dia de hoje; não ficará coisa alguma, diz o Senhor.

[[v12-20-18]]

^<<v12-20-18,18>>^ E até mesmo alguns de teus filhos, que procederem de ti, e que tu gerares, levarão; e eles serão eunucos no paço do rei de Babilônia.

[[v12-20-19]]

^<<v12-20-19,19>>^ Então disse Ezequias a Isaías: Boa é a palavra do Senhor que disseste. Disse mais: Pois não é assim, se em meus dias vai haver paz e segurança?

[[v12-20-20]]

^<<v12-20-20,20>>^ Ora, o restante dos atos de Ezequias, e todo o seu poder, e como fez a piscina e o aqueduto, e como fez vir a água para a cidade, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-20-21]]

^<<v12-20-21,21>>^ E Ezequias dormiu com seus pais. E Manassés, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[&#60; Capítulo Anterior] | <<v12-20-0,Topo>> | xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[Próximo Capítulo &#62;]