include::./index.adoc[]

[[v12-15-0]]
=== 2 Reis, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-15-1]]

^<<v12-15-1,1>>^ No ano vinte e sete de Jeroboão, rei de Israel, começou a reinar Azarias, filho de Amazias, rei de Judá.

[[v12-15-2]]

^<<v12-15-2,2>>^ Tinha dezesseis anos quando começou a reinar, e reinou cinqüenta e dois anos, em Jerusalém. O nome de sua mãe era Jecolia, de Jerusalém.

[[v12-15-3]]

^<<v12-15-3,3>>^ E fez o que era reto aos olhos do Senhor, conforme tudo o que fizera Amazias, seu pai.

[[v12-15-4]]

^<<v12-15-4,4>>^ Contudo os altos não foram tirados; o povo ainda sacrificava e queimava incenso neles.

[[v12-15-5]]

^<<v12-15-5,5>>^ E o Senhor feriu o rei, de modo que ficou leproso até o dia da sua morte; e habitou numa casa separada; e Jotão, filho do rei, tinha o cargo da casa, julgando o povo da terra.

[[v12-15-6]]

^<<v12-15-6,6>>^ Ora, o restante dos atos de Azarias, e tudo quanto fez, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-15-7]]

^<<v12-15-7,7>>^ E Azarias dormiu com seus pais, e com eles o sepultaram na cidade de Davi: E Jotão, seu filho, reinou em seu lugar.

[[v12-15-8]]

^<<v12-15-8,8>>^ No ano trinta e oito de Azarias, rei de Judá, reinou Zacarias, filho de Jeroboão, sobre Israel, em Samária, seis meses.

[[v12-15-9]]

^<<v12-15-9,9>>^ E fez o que era mau aos olhos do Senhor, como tinham feito seus pais; nunca se apartou dos pecados de Jeroboão, filho de Nebate, com os quais ele fizera Israel pecar.

[[v12-15-10]]

^<<v12-15-10,10>>^ Salum, filho de Jabes, conspirou contra ele; feriu-o diante do povo, matou-o e reinou em seu lugar.

[[v12-15-11]]

^<<v12-15-11,11>>^ Ora o restante dos atos de Zacarias está escrito no livro das crônicas dos reis de Israel.

[[v12-15-12]]

^<<v12-15-12,12>>^ Esta foi a palavra do Senhor, que ele falara a Jeú, dizendo: Teus filhos, até a quarta geração, se assentarão sobre o trono de Israel. E assim foi.

[[v12-15-13]]

^<<v12-15-13,13>>^ Salum, filho de Jabes, começou a reinar no ano trinta e nove de Uzias, rei de Judá, e reinou um mês em Samária.

[[v12-15-14]]

^<<v12-15-14,14>>^ E Menaém, filho de Gadi, subindo de Tirza, veio a Samária; feriu a Salum, filho de Jabes, em Samária, matou-o e reinou em seu lugar.

[[v12-15-15]]

^<<v12-15-15,15>>^ Ora, o restante dos atos de Salum, e a conspiração que fez, estão escritos no livro das crônicas dos reis de Israel.

[[v12-15-16]]

^<<v12-15-16,16>>^ Então Menaém feriu a Tifsa, e a todos os que nela havia, como também a seus termos desde Tirza; porque não lha tinham aberto, por isso a feriu; e fendeu a todas as mulheres grávidas que nela estavam.

[[v12-15-17]]

^<<v12-15-17,17>>^ No ano trinta e nove de Azarias, rei de Judá, Menaém, filho de Gadi, começou a reinar sobre Israel, e reinou dez anos em Samária.

[[v12-15-18]]

^<<v12-15-18,18>>^ E fez o que era mau aos olhos do Senhor; em todos os seus dias nunca se apartou dos pecados de Jeroboão, filho de Nebate, com os quais ele fizera Israel pecar.

[[v12-15-19]]

^<<v12-15-19,19>>^ Então veio Pul, rei da Assíria, contra a terra; e Menaém deu a Pul mil talentos de prata, para que este o ajudasse a firmar o reino na sua mão.

[[v12-15-20]]

^<<v12-15-20,20>>^ Menaém exigiu este dinheiro de todos os poderosos e ricos em Israel, para o dar ao rei da Assíria, de cada homem cinqüenta siclos de prata; assim voltou o rei da Assíria, e não se demorou ali na terra.

[[v12-15-21]]

^<<v12-15-21,21>>^ Ora, o restante dos atos de Menaém, e tudo quanto fez, porventura não estão escritos no livro das crônicas dos reis de Israel?

[[v12-15-22]]

^<<v12-15-22,22>>^ Menaém dormiu com seus pais. E Pecaías, seu filho, reinou em seu lugar.

[[v12-15-23]]

^<<v12-15-23,23>>^ No ano cinqüenta de Azarias, rei de Judá, Pecaías, filho de Menaém, começou a reinar sobre Israel em Samária, e reinou dois anos.

[[v12-15-24]]

^<<v12-15-24,24>>^ E fez o que era mau aos olhos do Senhor; nunca se apartou dos pecados de Jeroboão, filho de Nebate, com os quais ele fizera Israel pecar.

[[v12-15-25]]

^<<v12-15-25,25>>^ E Peca, chefe das suas tropas, filho de Remalias, conspirou contra ele, e o feriu em Samária, no castelo da casa do rei, juntamente com Argobe e com Arié; e com Peca estavam cinqüenta homens dos filhos dos gileaditas; e o matou, e reinou em seu lugar.

[[v12-15-26]]

^<<v12-15-26,26>>^ Ora, o restante dos atos de Pecaías, e tudo quanto fez, estão escritos no livro das crônicas dos reis de Israel.

[[v12-15-27]]

^<<v12-15-27,27>>^ No ano cinqüenta e dois de Azarias, rei de Judá, Peca, filho de Remalias, começou a reinar sobre Israel, em Samária, e reinou vinte anos.

[[v12-15-28]]

^<<v12-15-28,28>>^ E fez o que era mau aos olhos do Senhor; nunca se apartou dos pecados de Jeroboão, filho de Nebate, com os quais ele fizera Israel pecar.

[[v12-15-29]]

^<<v12-15-29,29>>^ Nos dias de Peca, rei de Israel, veio Tiglate-Pileser rei da Assíria e tomou Ijom, Abel-Bete-Maacá, Janoa, Quedes, Hazor, Gileade e Galiléia, toda a terra de Naftali; e levou cativos os habitantes para a Assiria.

[[v12-15-30]]

^<<v12-15-30,30>>^ E Oséias, filho de Elá, conspirou contra Peca, filho de Remalias, o feriu e matou, e reinou em seu lugar, no vigésimo ano de Jotão, filho de Uzias.

[[v12-15-31]]

^<<v12-15-31,31>>^ Ora, o restante dos atos de Peca, e tudo quanto fez, estão escritos no livro das crônicas dos reis de Israel.

[[v12-15-32]]

^<<v12-15-32,32>>^ No segundo ano de Peca, filho de Remalias, rei de Israel, começou a reinar Jotão, filho de Uzias, rei de Judá.

[[v12-15-33]]

^<<v12-15-33,33>>^ Tinha vinte e cinco anos quando começou a reinar, e reinou dezesseis anos em Jerusalém. O nome de sua mãe era Jenisa, filha de Zadoque.

[[v12-15-34]]

^<<v12-15-34,34>>^ E fez o que era reto aos olhos do Senhor; fez conforme tudo quanto fizera seu pai Uzias.

[[v12-15-35]]

^<<v12-15-35,35>>^ Contudo os altos não foram tirados; o povo ainda sacrificava e queimava incenso neles. Pois ele que edificou a porta alta da casa do Senhor.

[[v12-15-36]]

^<<v12-15-36,36>>^ Ora, o restante dos atos de Jotão, e tudo quanto fez, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-15-37]]

^<<v12-15-37,37>>^ Naqueles dias começou o Senhor a enviar contra Judá Rezim, rei da Síria, e Peca, filho de Remalias.

[[v12-15-38]]

^<<v12-15-38,38>>^ E Jotão dormiu com seus pais, e com eles foi, sepultado na cidade de Davi, seu pai. E Acaz, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[Próximo Capítulo &#62;]