include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-8-1]]

^<<v12-8-1,1>>^ Ora Eliseu havia falado àquela mulher cujo filho ele ressuscitara, dizendo: Levanta-te e vai, tu e a tua família, e peregrina onde puderes peregrinar; porque o Senhor chamou a fome, e ela virá sobre a terra por sete anos.

[[v12-8-2]]

^<<v12-8-2,2>>^ A mulher, pois, levantou-se e fez conforme a palavra do homem de Deus; foi com a sua família, e peregrinou na terra dos filisteus sete anos.

[[v12-8-3]]

^<<v12-8-3,3>>^ Mas ao cabo dos sete anos, a mulher voltou da terra dos filisteus, e saiu a clamar ao rei pela sua casa e pelas suas terras.

[[v12-8-4]]

^<<v12-8-4,4>>^ Ora, o rei falava a Geazi, o moço do homem de Deus, dizendo: Conta-me, peço-te, todas as grandes obras que Eliseu tem feito.

[[v12-8-5]]

^<<v12-8-5,5>>^ E sucedeu que, contando ele ao rei como Eliseu ressuscitara aquele que estava morto, eis que a mulher cujo filho ressuscitara veio clamar ao rei pela sua casa e pelas suas terras. Então disse Geazi: Ó rei meu senhor, esta é a mulher, e este o seu filho a quem Eliseu ressuscitou.

[[v12-8-6]]

^<<v12-8-6,6>>^ O rei interrogou a mulher, e ela lhe contou o caso. Então o rei lhe designou um oficial, ao qual disse: Faze restituir-lhe tudo quanto era seu, e todas as rendas das terras desde o dia em que deixou o país até agora.

[[v12-8-7]]

^<<v12-8-7,7>>^ Depois veio Eliseu a Damasco. E estando Ben-Hadade, rei da Síria, doente, lho anunciaram, dizendo: O homem de Deus chegou aqui.

[[v12-8-8]]

^<<v12-8-8,8>>^ Então o rei disse a Hazael: Toma um presente na tua mão, vai encontrar-te com o homem de Deus e por meio dele consulta ao Senhor, dizendo: Sararei eu desta doença?

[[v12-8-9]]

^<<v12-8-9,9>>^ Foi, pois, Hazael encontrar-se com ele, e levou consigo um presente, a saber, quarenta camelos carregados de tudo o que havia de bom em Damasco. Ao chegar, apresentou-se a ele e disse: Teu filho Ben-Hadade, rei da Síria, enviou-me a ti para perguntar: sararei eu desta doença?

[[v12-8-10]]

^<<v12-8-10,10>>^ Respondeu-lhe Eliseu: Vai e dize-lhe: Hás de sarar. Contudo o Senhor me mostrou que ele morrerá.

[[v12-8-11]]

^<<v12-8-11,11>>^ E olhou para Hazael, fitando nele os olhos até que este ficou confundido; e o homem de Deus chorou.

[[v12-8-12]]

^<<v12-8-12,12>>^ Então disse Hazael: Por que meu senhor está chorando? E ele disse: Porque sei o mal que hás de fazer aos filhos de Israel: Porás fogo às suas fortalezas, matarás à espada os seus mancebos, despedaçarás os seus pequeninos e fenderás as suas mulheres grávidas.

[[v12-8-13]]

^<<v12-8-13,13>>^ Ao que disse Hazael: Que é o teu servo, que não é mais do que um cão, para fazer tão grande coisa? Respondeu Eliseu: O Senhor mostrou-me que tu hás de ser rei da Síria.

[[v12-8-14]]

^<<v12-8-14,14>>^ Então apartou-se de Eliseu, e voltou ao seu senhor, o qual lhe perguntou: Que te disse Eliseu? Respondeu ele: Disse-me que certamente sararás.

[[v12-8-15]]

^<<v12-8-15,15>>^ Ao outro dia Hazael tomou um cobertor, molhou-o na água e o estendeu sobre o rosto do rei, de modo que este morreu. E Hazael reinou em seu lugar.

[[v12-8-16]]

^<<v12-8-16,16>>^ Ora, no ano quinto de Jorão, filho de Acabe, rei de Israel, Jeorão, filho de Jeosafá, rei de Judá, começou a reinar.

[[v12-8-17]]

^<<v12-8-17,17>>^ Tinha trinta e dois anos quando começou a reinar, e reinou oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ E andou no caminho dos reis de Israel, como também fizeram os da casa de Acabe, porque tinha por mulher a filha de Acabe; e fez o que era mau aos olhos do Senhor.

[[v12-8-19]]

^<<v12-8-19,19>>^ Todavia o Senhor não quis destruir a Judá, por causa de Davi, seu servo, porquanto lhe havia prometido que lhe daria uma lâmpada, a ele e a seus filhos, para sempre.

[[v12-8-20]]

^<<v12-8-20,20>>^ Nos seus dias os edomitas se rebelaram contra o domínio de Judá, e constituíram um rei para si.

[[v12-8-21]]

^<<v12-8-21,21>>^ Pelo que Jeorão passou a Zair, com todos os seus carros; e ele se levantou de noite, com os chefes dos carros, e feriu os edomitas que o haviam cercado; mas o povo fugiu para as suas tendas.

[[v12-8-22]]

^<<v12-8-22,22>>^ Assim os edomitas ficaram rebelados contra o domínio de Judá até o dia de hoje. Também Libna se rebelou nesse mesmo tempo.

[[v12-8-23]]

^<<v12-8-23,23>>^ O restante dos atos de Jeorão, e tudo quanto fez, porventura não estão escritos no livro das crônicas de Judá?

[[v12-8-24]]

^<<v12-8-24,24>>^ Jeorão dormiu com seus pais, e foi sepultado junto a eles na cidade de Davi. E Acazias, seu filho, reinou em seu lugar.

[[v12-8-25]]

^<<v12-8-25,25>>^ No ano doze de Jorão, filho de Acabe, rei de Israel, começou a reinar Acazias, filho de Jeorão, rei de Judá.

[[v12-8-26]]

^<<v12-8-26,26>>^ Acazias tinha vinte e dois anos quando começou a reinar, e reinou um ano em Jerusalém. O nome de sua mãe era Atalia; era neta de Onri, rei de Israel.

[[v12-8-27]]

^<<v12-8-27,27>>^ Ele andou no caminho da casa de Acabe, e fez o que era mau aos olhos do Senhor, como a casa de Acabe, porque era genro de Acabe.

[[v12-8-28]]

^<<v12-8-28,28>>^ Ora, ele foi com Jorão, filho de Acabe, a Ramote-Gileade, a pelejar contra Hazael, rei da Síria; e os sírios feriram a Jorão.

[[v12-8-29]]

^<<v12-8-29,29>>^ Então voltou o rei Jorão para se curar em Jizreel das feridas que os sírios lhe fizeram em Ramá, quando pelejou contra Hazael, rei da Síria; e desceu Acazias, filho de Jeorão, rei de Judá, para ver Jorão, filho de Acabe, em Jizreel, porquanto estava doente.

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]