include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-24-1]]

^<<v12-24-1,1>>^ Nos seus dias subiu Nabucodonosor, rei de Babilônia, e Jeoiaquim ficou sendo seu servo por três anos; mas depois se rebelou contra ele.

[[v12-24-2]]

^<<v12-24-2,2>>^ Então o Senhor enviou contra Jeoiaquim tropas dos caldeus, tropas dos sírios, tropas dos moabitas e tropas dos filhos de Amom; e as enviou contra Judá, para o destruírem, conforme a palavra que o Senhor falara por intermédio de seus servos os profetas.

[[v12-24-3]]

^<<v12-24-3,3>>^ Foi, na verdade, por ordem do Senhor que isto veio sobre Judá para removê-lo de diante da sua face, por causa de todos os pecados cometidos por Manassés,

[[v12-24-4]]

^<<v12-24-4,4>>^ bem como por causa do sangue inocente que ele derramou; pois encheu Jerusalém de sangue inocente; e por isso o Senhor não quis perdoar.

[[v12-24-5]]

^<<v12-24-5,5>>^ Ora, o restante dos atos de Jeoiaquim, e tudo quanto fez, porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-24-6]]

^<<v12-24-6,6>>^ Jeoiaquim dormiu com seus pais. E Joaquim, seu filho, reinou em seu lugar.

[[v12-24-7]]

^<<v12-24-7,7>>^ O rei do Egito nunca mais saiu da sua terra, porque o rei de Babilônia tinha tomado tudo quanto era do rei do Egito desde o rio do Egito até o rio Eufrates.

[[v12-24-8]]

^<<v12-24-8,8>>^ Tinha Joaquim dezoito anos quando começou a reinar e reinou três meses em Jerusalém. O nome de sua mãe era Neústa, filha de Elnatã, de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ Ele fez o que era mau aos olhos do Senhor, conforme tudo o que seu pai tinha feito.

[[v12-24-10]]

^<<v12-24-10,10>>^ Naquele tempo os servos de Nabucodonosor, rei de Babilônia, subiram contra Jerusalém, e a cidade foi sitiada.

[[v12-24-11]]

^<<v12-24-11,11>>^ E Nabucodonosor, rei de Babilônia, chegou diante da cidade quando já os seus servos a estavam sitiando.

[[v12-24-12]]

^<<v12-24-12,12>>^ Então saiu Joaquim, rei de Judá, ao rei da Babilônia, ele, e sua mãe, e seus servos, e seus príncipes, e seus oficiais; e, no ano oitavo do seu reinado, o rei de Babilônia o levou preso.

[[v12-24-13]]

^<<v12-24-13,13>>^ E tirou dali todos os tesouros da casa do Senhor, e os tesouros da casa do rei; e despedaçou todos os vasos de ouro que Salomão, rei de Israel, fizera no templo do Senhor, como o Senhor havia dito.

[[v12-24-14]]

^<<v12-24-14,14>>^ E transportou toda a Jerusalém, como também todos os príncipes e todos os homens valentes, deu mil cativos, e todos os artífices e ferreiros; ninguém ficou senão o povo pobre da terra.

[[v12-24-15]]

^<<v12-24-15,15>>^ Assim transportou Joaquim para Babilônia; como também a mãe do rei, as mulheres do rei, os seus oficiais, e os poderosos da terra, ele os levou cativos de Jerusalém para Babilônia.

[[v12-24-16]]

^<<v12-24-16,16>>^ Todos os homens valentes, em número de sete mil, e artífices e ferreiros em número de mil, todos eles robustos e destros na guerra, a estes o rei de Babilônia levou cativos para Babilônia.

[[v12-24-17]]

^<<v12-24-17,17>>^ E o rei de Babilônia constituiu rei em lugar de Joaquim a Matanias, seu tio paterno, e lhe mudou o nome em Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Zedequias tinha vinte e um anos quando começou a reinar, e reinou onze anos em Jerusalém. O nome de sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ Ele fez o que era mau aos olhos do Senhor, conforme tudo quanto fizera Jeoiaquim.

[[v12-24-20]]

^<<v12-24-20,20>>^ Por causa da ira do Senhor, assim sucedeu em Jerusalém, e em Judá, até que ele as lançou da sua presença. E Zedequias se rebelou contra o rei de Babilônia.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]