include::./index.adoc[]

[[v12-17-0]]
=== 2 Reis, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-17-1]]

^<<v12-17-1,1>>^ No ano duodécimo de Acaz, rei de Judá, começou a reinar Oséias, filho de Elá, e reinou sobre Israel, em Samária nove anos.

[[v12-17-2]]

^<<v12-17-2,2>>^ E fez o que era mau aos olhos do Senhor, contudo não como os reis de Israel que foram antes dele.

[[v12-17-3]]

^<<v12-17-3,3>>^ Contra ele subiu Salmanasar, rei da Assiria; e Oséias ficou sendo servo dele e lhe pagava tributos.

[[v12-17-4]]

^<<v12-17-4,4>>^ O rei da Assíria , porém, achou em Oséias conspiração; porque ele enviara mensageiros a Sô, rei do Egito, e não pagava, como dantes, os tributos anuais ao rei da Assíria; então este o encerrou e o pôs em grilhões numa prisão.

[[v12-17-5]]

^<<v12-17-5,5>>^ E o rei da Assíria subiu por toda a terra, e chegando a Samária sitiou-a por três anos.

[[v12-17-6]]

^<<v12-17-6,6>>^ No ano nono de Oséias, o rei da Assíria tomou Samária, e levou Israel cativo para a Assíria; e fê-los habitar em Hala, e junto a Habor, o rio de Gozã, e nas cidades dos medos.

[[v12-17-7]]

^<<v12-17-7,7>>^ Assim sucedeu, porque os filhos de Israel tinham pecado contra o Senhor seu Deus que os fizera subir da terra do Egito, de debaixo da mãe de Faraó, rei do Egito, e porque haviam temido a outros deuses,

[[v12-17-8]]

^<<v12-17-8,8>>^ e andado segundo os costumes das nações que o Senhor lançara fora de diante dos filhos de Israel, e segundo os que os reis de Israel introduziram.

[[v12-17-9]]

^<<v12-17-9,9>>^ Também os filhos de Israel fizeram secretamente contra o Senhor seu Deus coisas que não eram retas. Edificaram para si altos em todas as suas cidades, desde a torre das atalaias até a cidade fortificada;

[[v12-17-10]]

^<<v12-17-10,10>>^ Levantaram para si colunas e aserins em todos os altos outeiros, e debaixo de todas as árvores frondosas;

[[v12-17-11]]

^<<v12-17-11,11>>^ queimaram incenso em todos os altos, como as nações que o Senhor expulsara de diante deles; cometeram ações iníquas, provocando à ira o Senhor,

[[v12-17-12]]

^<<v12-17-12,12>>^ e serviram os ídolos, dos quais o Senhor lhes dissera: Não fareis isso.

[[v12-17-13]]

^<<v12-17-13,13>>^ Todavia o Senhor advertiu a Israel e a Judá pelo ministério de todos os profetas e de todos os videntes, dizendo: Voltai de vossos maus caminhos, e guardai os meus mandamentos e os meus estatutos, conforme toda a lei que ordenei a vossos pais e que vos enviei pelo ministério de meus servos, os profetas.

[[v12-17-14]]

^<<v12-17-14,14>>^ Eles porém, não deram ouvidos; antes endureceram a sua cerviz, como fizeram seus pais, que não creram no Senhor seu Deus;

[[v12-17-15]]

^<<v12-17-15,15>>^ rejeitaram os seus estatutos, e o seu pacto, que fizera com os pais deles, como também as advertências que lhes fizera; seguiram a vaidade e tornaram-se vãos, como também seguiram as nações que estavam ao redor deles, a respeito das quais o Senhor lhes tinha ordenado que não as imitassem.

[[v12-17-16]]

^<<v12-17-16,16>>^ E, deixando todos os mandamentos do Senhor seu Deus, fizeram para si dois bezerros de fundição, e ainda uma Asera; adoraram todo o exército do céu, e serviram a Baal.

[[v12-17-17]]

^<<v12-17-17,17>>^ Fizeram passar pelo fogo seus filhos, suas filhas, e deram-se a adivinhações e encantamentos; e venderam-se para fazer o que era mau aos olhos do Senhor, provocando-o à ira.

[[v12-17-18]]

^<<v12-17-18,18>>^ Pelo que o Senhor muito se indignou contra Israel, e os tirou de diante da sua face; não ficou senão somente a tribo de Judá.

[[v12-17-19]]

^<<v12-17-19,19>>^ Nem mesmo Judá havia guardado os mandamentos do Senhor seu Deus; antes andou nos costumes que Israel introduzira.

[[v12-17-20]]

^<<v12-17-20,20>>^ Pelo que o Senhor rejeitou toda a linhagem de Israel, e os oprimiu, entregando-os nas mãos dos despojadores, até que os expulsou da sua presença.

[[v12-17-21]]

^<<v12-17-21,21>>^ Pois rasgara Israel da casa de Davi; e eles fizeram rei a Jeroboão, filho de Nebate, o qual apartou Israel de seguir o Senhor, e os fez cometer um grande pecado.

[[v12-17-22]]

^<<v12-17-22,22>>^ Assim andaram os filhos de Israel em todos os pecados que Jeroboão tinha cometido; nunca se apartaram deles;

[[v12-17-23]]

^<<v12-17-23,23>>^ até que o Senhor tirou Israel da sua presença, como falara por intermédio de todos os seus servos os profetas. Assim foi Israel transportado da sua terra para a Assíria, onde está até o dia de hoje.

[[v12-17-24]]

^<<v12-17-24,24>>^ Depois o rei da Assíria trouxe gente de Babilônia, de Cuta, de Ava, de Hamate e de Sefarvaim, e a fez habitar nas cidades de Samária em lugar dos filhos de Israel; e eles tomaram Samária em herança, e habitaram nas suas cidades.

[[v12-17-25]]

^<<v12-17-25,25>>^ E sucedeu que, no princípio da sua habitação ali, não temeram ao Senhor; e o Senhor mandou entre eles leões, que mataram alguns deles.

[[v12-17-26]]

^<<v12-17-26,26>>^ Pelo que foi dito ao rei da Assíria: A gente que transportaste, e fizeste habitar nas cidades de Samária, não conhece a lei do deus da terra; por isso ele tem enviado entre ela leões que a matam, porquanto não conhece a lei do deus da terra.

[[v12-17-27]]

^<<v12-17-27,27>>^ Então o rei da Assíria mandou dizer: Levai ali um dos sacerdotes que transportastes de lá para que vá e habite ali, e lhes ensine a lei do deus da terra.

[[v12-17-28]]

^<<v12-17-28,28>>^ Veio, pois, um dos sacerdotes que eles tinham transportado de Samária, e habitou em Betel, e lhes ensinou como deviam temer ao Senhor.

[[v12-17-29]]

^<<v12-17-29,29>>^ Todavia as nações faziam cada uma o seu próprio deus, e os punham nas casas dos altos que os samaritanos tinham feito, cada nação nas cidades que habitava.

[[v12-17-30]]

^<<v12-17-30,30>>^ Os de Babilônia fizeram e Sucote-Benote; os de Cuta fizeram Nergal; os de Hamate fizeram Asima;

[[v12-17-31]]

^<<v12-17-31,31>>^ os aveus fizeram Nibaz e Tartaque: e os sefarvitas queimavam seus filhos no fogo e a adrameleque e a Anameleque, deuses de Sefarvaim.

[[v12-17-32]]

^<<v12-17-32,32>>^ Temiam também ao Senhor, e dentre o povo fizeram para si sacerdotes dos lugares altos, os quais exerciam o ministério nas casas dos lugares altos.

[[v12-17-33]]

^<<v12-17-33,33>>^ Assim temiam ao Senhor, mas também serviam a seus próprios deuses, segundo o costume das nações do meio das quais tinham sido transportados.

[[v12-17-34]]

^<<v12-17-34,34>>^ Até o dia de hoje fazem segundo os antigos costumes: não temem ao Senhor; nem fazem segundo os seus estatutos, nem segundo as suas ordenanças; nem tampouco segundo a lei, nem segundo o mandamento que o Senhor ordenou aos filhos de Jacó, a quem deu o nome de Israel,

[[v12-17-35]]

^<<v12-17-35,35>>^ com os quais o Senhor tinha feito um pacto, e lhes ordenara, dizendo: Não temereis outros deuses, nem vos inclinareis diante deles, nem os servireis, nem lhes oferecereis sacrifícios;

[[v12-17-36]]

^<<v12-17-36,36>>^ mas sim ao Senhor, que vos fez subir da terra do Egito com grande poder e com braço estendido, a ele temereis, a ele vos inclinareis, e a ele oferecereis sacrifícios.

[[v12-17-37]]

^<<v12-17-37,37>>^ Quanto aos estatutos, às ordenanças, à lei, e ao mandamento, que para vós escreveu, a esses tereis cuidado de observar todos os dias; e não temereis outros deuses;

[[v12-17-38]]

^<<v12-17-38,38>>^ e do pacto que fiz convosco não vos esquecereis. Não temereis outros deuses,

[[v12-17-39]]

^<<v12-17-39,39>>^ mas ao Senhor vosso Deus temereis, e ele vos livrará das mãos de todos os vossos inimigos.

[[v12-17-40]]

^<<v12-17-40,40>>^ Contudo eles não ouviram; antes fizeram segundo o seu antigo costume.

[[v12-17-41]]

^<<v12-17-41,41>>^ Assim estas nações temiam ao Senhor, mas serviam também as suas imagens esculpidas; também seus filhos, e os filhos de seus filhos fazem até o dia de hoje como fizeram seus pais.

'''

xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[Próximo Capítulo &#62;]