include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-7-1]]

^<<v12-7-1,1>>^ Então disse Eliseu: Ouvi a palavra do Senhor; assim diz o Senhor: Amanhã, por estas horas, haverá uma medida de farinha por um siclo, e duas medidas de cevada por um siclo, à porta de Samária.

[[v12-7-2]]

^<<v12-7-2,2>>^ porém o capitão em cujo braço o rei se apoiava respondeu ao homem de Deus e disse: Ainda que o Senhor fizesse janelas no céu, poderia isso suceder? Disse Eliseu: Eis que o verás com os teus olhos, porém não comeras.

[[v12-7-3]]

^<<v12-7-3,3>>^ Ora, quatro homens leprosos estavam à entrada da porta; e disseram uns aos outros: Para que ficamos nós sentados aqui até morrermos?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se dissermos: Entremos na cidade; há fome na cidade, e morreremos aí; e se ficarmos sentados aqui, também morreremos. Vamo-nos, pois, agora e passemos para o arraial dos sírios; se eles nos deixarem viver, viveremos; e se nos matarem, tão somente morreremos.

[[v12-7-5]]

^<<v12-7-5,5>>^ Levantaram-se, pois, ao crepúsculo, para irem ao arraial dos sírios; e, chegando eles à entrada do arraial, eis que não havia ali ninguém.

[[v12-7-6]]

^<<v12-7-6,6>>^ Porque o Senhor fizera ouvir no arraial dos sírios um ruído de carros e de cavalos, como de um grande exército; de maneira que disseram uns aos outros: Eis que o rei de Israel alugou contra nós os reis dos heteus e os reis dos egípcios, para virem sobre nós.

[[v12-7-7]]

^<<v12-7-7,7>>^ Pelo que se levantaram e fugiram, ao crepúsculo; deixaram as suas tendas, os seus cavalos e os seus jumentos, isto é, o arraial tal como estava, e fugiram para salvarem as suas vidas.

[[v12-7-8]]

^<<v12-7-8,8>>^ Chegando, pois, estes leprosos à entrada do arraial, entraram numa tenda, comeram e beberam; e tomando dali prata, ouro e vestidos, foram e os esconderam; depois voltaram, entraram em outra tenda, e dali também tomaram alguma coisa e a esconderam.

[[v12-7-9]]

^<<v12-7-9,9>>^ Então disseram uns aos outros: Não fazemos bem; este dia é dia de boas novas, e nós nos calamos. Se esperarmos até a luz da manhã, algum castigo nos sobrevirá; vamos, pois, agora e o anunciemos à casa do rei.

[[v12-7-10]]

^<<v12-7-10,10>>^ Vieram, pois, bradaram aos porteiros da cidade, e lhes anunciaram, dizendo: Fomos ao arraial dos sírios e eis que lá não havia ninguém, nem voz de homem, porém só os cavalos e os jumentos atados, e as tendas como estavam.

[[v12-7-11]]

^<<v12-7-11,11>>^ Assim chamaram os porteiros, e estes o anunciaram dentro da casa do rei.

[[v12-7-12]]

^<<v12-7-12,12>>^ E o rei se levantou de noite, e disse a seus servos: Eu vos direi o que é que os sírios nos fizeram. Bem sabem eles que estamos esfaimados; pelo que saíram do arraial para se esconderem no campo, dizendo: Quando saírem da cidade, então os tomaremos vivos, e entraremos na cidade.

[[v12-7-13]]

^<<v12-7-13,13>>^ Então um dos seus servos respondeu, dizendo: Tomem-se, pois, cinco dos cavalos do resto que ficou aqui dentro &#123;eis que eles estão como toda a multidão dos israelitas que ficaram aqui de resto, e que se vêm extenuando&#125;, e enviemo-los, e vejamos.

[[v12-7-14]]

^<<v12-7-14,14>>^ Tomaram pois dois carros com cavalos; e o rei os enviou com mensageiros após o exército dos sírios, dizendo-lhe: Ide, e vede.

[[v12-7-15]]

^<<v12-7-15,15>>^ E foram após ele até o Jordão; e eis que todo o caminho estava cheio de roupas e de objetos que os sírios, na sua precipitação, tinham lançado fora; e voltaram os mensageiros, e o anunciaram ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ Então saiu o povo, e saqueou o arraial dos sírios. Assim houve uma medida de farinha por um siclo e duas medidas de cevada por um siclo, conforme a palavra do Senhor.

[[v12-7-17]]

^<<v12-7-17,17>>^ O rei pusera à porta o capitão em cujo braço ele se apoiava; e o povo o atropelou na porta, de sorte que morreu, como falara o homem de Deus quando o rei descera a ter com ele.

[[v12-7-18]]

^<<v12-7-18,18>>^ Porque, quando o homem de Deus falara ao rei, dizendo: Amanhã, por estas horas, haverá duas medidas de cevada por um siclo, e uma medida de farinha por um siclo, à porta de Samária,

[[v12-7-19]]

^<<v12-7-19,19>>^ aquele capitão respondera ao homem de Deus: Ainda que o Senhor fizesse janelas no céu poderia isso suceder? e ele dissera: Eis que o verás com os teus olhos, porém não comerás.

[[v12-7-20]]

^<<v12-7-20,20>>^ E assim foi; pois o povo o atropelou à porta, e ele morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]