include::./index.adoc[]

[[v12-18-0]]
=== 2 Reis, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-18-1]]

^<<v12-18-1,1>>^ Ora, sucedeu que, no terceiro ano de Oséias, filho de Elá, rei de Israel, começou a reinar Ezequias, filho de Acaz, rei de Judá.

[[v12-18-2]]

^<<v12-18-2,2>>^ Tinha vinte e cinco anos quando começou a reinar, e reinou vinte e nove anos em Jerusalém. O nome de sua mãe era Abi, filha de Zacarias.

[[v12-18-3]]

^<<v12-18-3,3>>^ Ele fez o que era reto aos olhos do Senhor, conforme tudo o que fizera Davi, seu pai.

[[v12-18-4]]

^<<v12-18-4,4>>^ Tirou os altos, quebrou as colunas, e deitou abaixo a Asera; e despedaçou a serpente de bronze que Moisés fizera &#123;porquanto até aquele dia os filhos de Israel lhe queimavam incenso&#125;, e chamou-lhe Neüstã.

[[v12-18-5]]

^<<v12-18-5,5>>^ Confiou no Senhor Deus de Israel, de modo que depois dele não houve seu semelhante entre todos os reis de Judá, nem entre os que foram antes dele.

[[v12-18-6]]

^<<v12-18-6,6>>^ Porque se apegou ao Senhor; não se apartou de o seguir, e guardou os mandamentos que o Senhor ordenara a Moisés.

[[v12-18-7]]

^<<v12-18-7,7>>^ Assim o Senhor era com ele; para onde quer que saísse prosperava. Rebelou-se contra o rei da Assíria, e recusou servi-lo.

[[v12-18-8]]

^<<v12-18-8,8>>^ Feriu os filisteus até Gaza e os seus termos, desde a torre dos atalaias até a cidade fortificada.

[[v12-18-9]]

^<<v12-18-9,9>>^ No quarto ano do rei Ezequias que era o sétimo ano de Oséias, filho de Elá, rei de Israel, Salmanasar, rei da Assíria, subiu contra Samária, e a cercou

[[v12-18-10]]

^<<v12-18-10,10>>^ e, ao fim de três anos, tomou-a. No ano sexto de Ezequias, que era o ano nono de Oséias, rei de Israel, Samária foi tomada.

[[v12-18-11]]

^<<v12-18-11,11>>^ Depois o rei da Assíria levou Israel cativo para a Assíria, e os colocou em Hala, e junto ao Habor, rio de Gozã, e nas cidades dos medos;

[[v12-18-12]]

^<<v12-18-12,12>>^ porquanto não obedeceram à voz do senhor seu Deus, mas violaram o seu pacto, nada ouvindo nem fazendo de tudo quanto Moisés, servo do Senhor, tinha ordenado.

[[v12-18-13]]

^<<v12-18-13,13>>^ No ano décimo quarto do rei Ezequias, subiu Senaqueribe, rei da Assíria, contra todas as cidades fortificadas de Judá, e as tomou.

[[v12-18-14]]

^<<v12-18-14,14>>^ Pelo que Ezequias, rei de Judá, enviou ao rei da Assíria, a Laquis, dizendo: Pequei; retira-te de mim; tudo o que me impuseres suportarei. Então o rei da Assíria impôs a Ezequias, rei de Judá, trezentos talentos de prata e trinta talentos de ouro.

[[v12-18-15]]

^<<v12-18-15,15>>^ Assim deu Ezequias toda a prata que se achou na casa do Senhor e nos tesouros da casa do rei.

[[v12-18-16]]

^<<v12-18-16,16>>^ Foi nesse tempo que Ezequias, rei de Judá, cortou das portas do templo do Senhor, e dos umbrais, o ouro de que ele mesmo os cobrira, e o deu ao rei da Assíria.

[[v12-18-17]]

^<<v12-18-17,17>>^ Contudo este enviou de Laquis Tartã, Rabe-Sáris e Rabsaqué, com um grande exército, ao rei Ezequias, a Jerusalém; e subiram, e vieram a Jerusalém. E, tendo chegado, pararam ao pé do aqueduto da piscina superior, que está junto ao caminho do campo do lavandeiro.

[[v12-18-18]]

^<<v12-18-18,18>>^ Havendo eles chamado o rei, saíram-lhes ao encontro Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o cronista.

[[v12-18-19]]

^<<v12-18-19,19>>^ E Rabsaqué lhes disse: Dizei a Ezequias: Assim diz o grande rei, o rei da Assíria: Que confiança é essa em que te estribas?

[[v12-18-20]]

^<<v12-18-20,20>>^ Dizes &#123;são, porém, palavras vãs&#125;: Há conselho e poder para a guerra. Em quem, pois, agora confias, que contra mim te revoltas?

[[v12-18-21]]

^<<v12-18-21,21>>^ Estás confiando nesse bordão de cana quebrada, que é o Egito; o qual, se alguém nele se apoiar, entrar-lhe-á pela mão e a traspassará; assim é Faraó, rei do Egito para com todos os que nele confiam.

[[v12-18-22]]

^<<v12-18-22,22>>^ Se, porém, me disserdes: No Senhor nosso Deus confiamos; porventura não é esse aquele cujos altos e altares Ezequias tirou dizendo a Judá e a Jerusalém: Perante, este altar adorareis em Jerusalém?

[[v12-18-23]]

^<<v12-18-23,23>>^ Ora pois faze uma aposta com o meu senhor, o rei da Assíria: dar-te-ei dois mil cavalos, se tu puderes dar cavaleiros para eles.

[[v12-18-24]]

^<<v12-18-24,24>>^ Como, então, poderias repelir um só príncipe dos menores servos de meu senhor, quando estás confiando no Egito para obteres carros e cavaleiros?

[[v12-18-25]]

^<<v12-18-25,25>>^ Porventura teria eu subido sem o Senhor contra este lugar para o destruir? Foi o Senhor que me disse: sobe contra esta terra e a destrói.

[[v12-18-26]]

^<<v12-18-26,26>>^ Então disseram Eliaquim, filho de Hilquias, e Sebna, e Joá, a Rabsaqué: Rogamos-te que fales aos teus servos em aramaico, porque bem o entendemos; e não nos fales na língua judaica, aos ouvidos do povo que está em cima do muro.

[[v12-18-27]]

^<<v12-18-27,27>>^ Rabsaqué, porém, lhes disse: Porventura mandou-me meu senhor para falar estas palavras a teu senhor e a ti, e não aos homens que estão sentados em cima do muro que juntamente convosco hão de comer o seu excremento e beber a sua urina ?

[[v12-18-28]]

^<<v12-18-28,28>>^ Então pondo-se em pé, Rabsaqué clamou em alta voz, na língua judaica, dizendo: Ouvi a palavra do grande rei, do rei da Assíria.

[[v12-18-29]]

^<<v12-18-29,29>>^ Assim diz o rei: Não vos engane Ezequias; porque não vos poderá livrar da minha mão;

[[v12-18-30]]

^<<v12-18-30,30>>^ nem tampouco vos faça Ezequias confiar no Senhor, dizendo: Certamente nos livrará o Senhor, e esta cidade não será entregue na mão do rei da Assíria.

[[v12-18-31]]

^<<v12-18-31,31>>^ Não deis ouvidos a Ezequias; pois assim diz o rei da Assíria: Fazei paz comigo, e saí a mim; e coma cada um da sua vide e da sua figueira, e beba cada um a água da sua cisterna;

[[v12-18-32]]

^<<v12-18-32,32>>^ até que eu venha, e vos leve para uma terra semelhante à vossa, terra de trigo e de mosto, terra de pão e de vinhas, terra de azeite de oliveiras e de mel; para que vivais e não morrais. Não deis ouvidos a Ezequias, quando vos envenena, dizendo: O Senhor nos livrará.

[[v12-18-33]]

^<<v12-18-33,33>>^ Porventura os deuses das nações puderam livrar, cada um a sua terra, das mãos do rei da Assíria?

[[v12-18-34]]

^<<v12-18-34,34>>^ Que é feito dos deuses de Hamate e de Arpade? Que é feito dos deuses de Sefarvaim, de Hena e de Iva? porventura livraram Samária da minha mão?

[[v12-18-35]]

^<<v12-18-35,35>>^ Dentre todos os deuses das terras, quais são os que livraram a sua terra da minha mão, para que o Senhor livre Jerusalém da minha mão?

[[v12-18-36]]

^<<v12-18-36,36>>^ O povo, porém, ficou calado, e não lhe respondeu uma só palavra, porque o rei ordenara, dizendo: Não lhe respondais.

[[v12-18-37]]

^<<v12-18-37,37>>^ Então Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o cronista, vieram a Ezequias com as vestes rasgadas, e lhe fizeram saber as palavras de Rabsaqué.

'''

xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[Próximo Capítulo &#62;]