include::./index.adoc[]

[[v12-16-0]]
=== 2 Reis, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-16-1]]

^<<v12-16-1,1>>^ No ano dezessete de Peca, filho de Remalia começou a reinar Acaz, filho de Jotão, rei de Judá.

[[v12-16-2]]

^<<v12-16-2,2>>^ Tinha Acaz vinte anos quando começou a reinar, e reinou dezesseis anos em Jerusalém; e não fez o que era reto aos olhos do Senhor seu Deus, como tinha feito Davi, seu pai,

[[v12-16-3]]

^<<v12-16-3,3>>^ mas andou no caminho dos reis de Israel, e até fez passar pelo fogo o seu filho, segundo as abominações dos gentios que o Senhor lançara fora de diante dos filhos de Israel.

[[v12-16-4]]

^<<v12-16-4,4>>^ Também oferecia sacrifícios e queimava incenso nos altos e nos outeiros, como também debaixo de toda árvore frondosa.

[[v12-16-5]]

^<<v12-16-5,5>>^ Então subiu Rezim, rei da Síria, com Peca, filho de Remalias, rei de Israel, contra Jerusalém, para lhe fazer guerra; e cercaram a Acaz, porém não puderam vencê-lo.

[[v12-16-6]]

^<<v12-16-6,6>>^ Nesse mesmo tempo Rezim, rei da Síria, restituiu Elate a Síria, lançando fora dela os judeus; e os sírios vieram a Elate, e ficaram habitando ali até o dia de hoje.

[[v12-16-7]]

^<<v12-16-7,7>>^ Então Acaz enviou mensageiros a Tiglate-Pileser, rei da Assíria, dizendo: Eu sou teu servo e teu filho; sobe, e livra-me das mãos do rei da Síria, e das mãos do rei de Israel, os quais se levantaram contra mim.

[[v12-16-8]]

^<<v12-16-8,8>>^ E tomou Acaz a prata e o ouro que se achou na casa do Senhor e nos tesouros da casa do rei, e mandou um presente ao rei da Assíria.

[[v12-16-9]]

^<<v12-16-9,9>>^ E o rei da Assíria lhe deu ouvidos e, subindo contra Damasco, tomou-a, levou cativo o povo para Quir, e matou Rezim.

[[v12-16-10]]

^<<v12-16-10,10>>^ Então o rei Acaz foi a Damasco para se encontrar com Tiglate-Pileser, rei da Assíria; e, vendo o altar que estava em Damasco, enviou ao sacerdote Urias a figura do altar, e o modelo exato de toda a sua obra.

[[v12-16-11]]

^<<v12-16-11,11>>^ E Urias, o sacerdote, edificou o altar; conforme tudo o que o rei Acaz lhe tinha enviado de Damasco, assim o fez o sacerdote Urias, antes que o rei Acaz viesse de Damasco.

[[v12-16-12]]

^<<v12-16-12,12>>^ Tendo o rei vindo de Damasco, viu o altar; e, acercando-se do altar, ofereceu sacrifício sobre ele;

[[v12-16-13]]

^<<v12-16-13,13>>^ queimou o seu holocausto e a sua oferta de cereais, derramou a sua libação, e espargiu o sangue dos seus sacrifícios pacíficos sobre o altar.

[[v12-16-14]]

^<<v12-16-14,14>>^ E o altar de bronze, que estava perante o Senhor, ele o tirou da parte fronteira da casa, de entre o seu altar e a casa do Senhor, e o colocou ao lado setentrional do seu altar.

[[v12-16-15]]

^<<v12-16-15,15>>^ E o rei Acaz ordenou a Urias, o sacerdote, dizendo: No grande altar queima o holocausto da manhã, como também a oferta de cereais da noite, o holocausto do rei e a sua oferta de cereais, o holocausto de todo o povo da terra, a sua oferta de cereais e as suas libações; e todo o sangue dos holocaustos, e todo o sangue dos sacrifícios espargirás nele; porém o altar de bronze ficará ao meu dispor para nele inquirir.

[[v12-16-16]]

^<<v12-16-16,16>>^ Assim fez Urias, o sacerdote, conforme tudo quanto o rei Acaz lhe ordenara.

[[v12-16-17]]

^<<v12-16-17,17>>^ Também o rei Acaz cortou as almofadas das bases, e de cima delas removeu a pia; tirou o mar de sobre os bois de bronze, que estavam debaixo dele, e o colocou sobre um pavimento de pedra.

[[v12-16-18]]

^<<v12-16-18,18>>^ Também o passadiço coberto para uso no sábado, que tinham construído na casa, e a entrada real externa, retirou da casa do Senhor, por causa do rei da Assíria.

[[v12-16-19]]

^<<v12-16-19,19>>^ Ora, o restante dos atos de Acaz, e o que fez porventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-16-20]]

^<<v12-16-20,20>>^ E dormiu Acaz com seus pais, e com eles foi sepultado na cidade de Davi. E Ezequias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[&#60; Capítulo Anterior] | <<v12-16-0,Topo>> | xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[Próximo Capítulo &#62;]