include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-2-1]]

^<<v12-2-1,1>>^ Quando o Senhor estava para tomar Elias ao céu num redemoinho, Elias partiu de Gilgal com Eliseu.

[[v12-2-2]]

^<<v12-2-2,2>>^ Disse Elias a Eliseu: Fica-te aqui, porque o Senhor me envia a Betel. Eliseu, porém disse: Vive o Senhor, e vive a tua alma, que não te deixarei. E assim desceram a Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Então os filhos dos profetas que estavam em Betel saíram ao encontro de Eliseu, e lhe disseram: Sabes que o Senhor hoje tomará o teu senhor por sobre a tua cabeça? E ele disse: Sim, eu o sei; calai-vos.

[[v12-2-4]]

^<<v12-2-4,4>>^ E Elias lhe disse: Eliseu, fica-te aqui, porque o Senhor me envia a Jericó. Ele, porém, disse: Vive o Senhor, e vive a tua alma, que não te deixarei. E assim vieram a Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ Então os filhos dos profetas que estavam em Jericó se chegaram a Eliseu, e lhe disseram: Sabes que o Senhor hoje tomará o teu senhor por sobre a tua cabeça? E ele disse: Sim, eu o sei; calai-vos.

[[v12-2-6]]

^<<v12-2-6,6>>^ E Elias lhe disse: Fica-te aqui, porque o senhor me envia ao Jordão. Mas ele disse: Vive o Senhor, e vive a tua alma, que não te deixarei. E assim ambos foram juntos.

[[v12-2-7]]

^<<v12-2-7,7>>^ E foram cinqüenta homens dentre os filhos dos profetas, e pararam defronte deles, de longe; e eles dois pararam junto ao Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ Então Elias tomou a sua capa e, dobrando-a, feriu as águas, as quais se dividiram de uma à outra banda; e passaram ambos a pé enxuto.

[[v12-2-9]]

^<<v12-2-9,9>>^ Havendo eles passado, Elias disse a Eliseu: Pede-me o que queres que eu te faça, antes que seja tomado de ti. E disse Eliseu: Peço-te que haja sobre mim dobrada porção de teu espírito.

[[v12-2-10]]

^<<v12-2-10,10>>^ Respondeu Elias: Coisa difícil pediste. Todavia, se me vires quando for tomado de ti, assim se te fará; porém, se não, não se fará.

[[v12-2-11]]

^<<v12-2-11,11>>^ E, indo eles caminhando e conversando, eis que um carro de fogo, com cavalos de fogo, os separou um do outro; e Elias subiu ao céu num redemoinho.

[[v12-2-12]]

^<<v12-2-12,12>>^ O que vendo Eliseu, clamou: Meu pai, meu pai! o carro de Israel, e seus cavaleiros! E não o viu mais. Pegou então nas suas vestes e as rasgou em duas partes;

[[v12-2-13]]

^<<v12-2-13,13>>^ tomou a capa de Elias, que dele caíra, voltou e parou à beira do Jordão.

[[v12-2-14]]

^<<v12-2-14,14>>^ Então, pegando da capa de Elias, que dele caíra, feriu as águas e disse: Onde está o Senhor, o Deus de Elias? Quando feriu as águas, estas se dividiram de uma à outra banda, e Eliseu passou.

[[v12-2-15]]

^<<v12-2-15,15>>^ Vendo-o, pois, os filhos dos profetas que estavam defronte dele em Jericó, disseram: O espírito de Elias repousa sobre Eliseu. E vindo ao seu encontro, inclinaram-se em terra diante dele.

[[v12-2-16]]

^<<v12-2-16,16>>^ E disseram-lhe: Eis que entre os teus servos há cinqüenta homens valentes. Deixa-os ir, pedimos-te, em busca do teu senhor; pode ser que o Espírito do Senhor o tenha arrebatado e lançado nalgum monte, ou nalgum vale. Ele, porém, disse: Não os envieis.

[[v12-2-17]]

^<<v12-2-17,17>>^ Mas insistiram com ele, até que se envergonhou; e disse-lhes: Enviai. E enviaram cinqüenta homens, que o buscaram três dias, porém não o acharam.

[[v12-2-18]]

^<<v12-2-18,18>>^ Então voltaram para Eliseu, que ficara em Jericó; e ele lhes disse: Não vos disse eu que não fôsseis?

[[v12-2-19]]

^<<v12-2-19,19>>^ Os homens da cidade disseram a Eliseu: Eis que a situação desta cidade é agradável, como vê o meu senhor; porém as águas são péssimas, e a terra é estéril.

[[v12-2-20]]

^<<v12-2-20,20>>^ E ele disse: Trazei-me um jarro novo, e ponde nele sal. E lho trouxeram.

[[v12-2-21]]

^<<v12-2-21,21>>^ Então saiu ele ao manancial das águas e, deitando sal nele, disse: Assim diz o Senhor: Sarei estas águas; não mais sairá delas morte nem esterilidade.

[[v12-2-22]]

^<<v12-2-22,22>>^ E aquelas águas ficaram sãs, até o dia de hoje, conforme a palavra que Eliseu disse.

[[v12-2-23]]

^<<v12-2-23,23>>^ Então subiu dali a Betel; e, subindo ele pelo caminho, uns meninos saíram da cidade, e zombavam dele, dizendo: Sobe, calvo; sobe, calvo!

[[v12-2-24]]

^<<v12-2-24,24>>^ E, virando-se ele para trás, os viu, e os amaldiçoou em nome do Senhor. Então duas ursas saíram do bosque, e despedaçaram quarenta e dois daqueles meninos.

[[v12-2-25]]

^<<v12-2-25,25>>^ E dali foi para o monte Carmelo, de onde voltou para Samária.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]