include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-1-1]]

^<<v12-1-1,1>>^ Depois da morte de Acabe, Moabe se rebelou contra Israel.

[[v12-1-2]]

^<<v12-1-2,2>>^ Ora, Acazias caiu pela grade do seu quarto alto em Samária, e adoeceu; e enviou mensageiros, dizendo-lhes: Ide, e perguntai a Baal-Zebube, deus de Ecrom, se sararei desta doença.

[[v12-1-3]]

^<<v12-1-3,3>>^ O anjo do Senhor, porém, disse a Elias, o tisbita: Levanta-te, sobe para te encontrares com os mensageiros do rei de Samária, e dize-lhes: Porventura não há Deus em Israel, para irdes consultar a Baal-Zebube, deus de Ecrom?

[[v12-1-4]]

^<<v12-1-4,4>>^ Agora, pois, assim diz o Senhor: Da cama a que subiste não descerás, mas certamente morrerás. E Elias se foi.

[[v12-1-5]]

^<<v12-1-5,5>>^ Os mensageiros voltaram para Acazias, que lhes perguntou: Que há, que voltastes?

[[v12-1-6]]

^<<v12-1-6,6>>^ Responderam-lhe eles: Um homem subiu ao nosso encontro, e nos disse: Ide, voltai para o rei que vos mandou, e dizei-lhe: Assim diz o Senhor: Porventura não há Deus em Israel, para que mandes consultar a Baal-Zebube, deus de Ecrom? Portanto, da cama a que subiste não descerás, mas certamente morrerás.

[[v12-1-7]]

^<<v12-1-7,7>>^ Pelo que ele lhes indagou: Qual era a aparência do homem que subiu ao vosso encontro e vos falou estas palavras?

[[v12-1-8]]

^<<v12-1-8,8>>^ Responderam-lhe eles: Era um homem vestido de pelos, e com os lombos cingidos dum cinto de couro. Então disse ele: É Elias, o tisbita.

[[v12-1-9]]

^<<v12-1-9,9>>^ Então o rei lhe enviou um chefe de cinqüenta, com os seus cinqüenta. Este subiu a ter com Elias que estava sentado no cume do monte, e disse-lhe: Ó homem de Deus, o rei diz: Desce.

[[v12-1-10]]

^<<v12-1-10,10>>^ Mas Elias respondeu ao chefe de cinqüenta, dizendo-lhe: Se eu, pois, sou homem de Deus, desça fogo do céu, e te consuma a ti e aos teus cinqüenta. Então desceu fogo do céu, e consumiu a ele e aos seus cinqüenta.

[[v12-1-11]]

^<<v12-1-11,11>>^ Tornou o rei a enviar-lhe outro chefe de cinqüenta com os seus cinqüenta. Este lhe falou, dizendo: Ó homem de Deus, assim diz o rei: Desce depressa.

[[v12-1-12]]

^<<v12-1-12,12>>^ Também a este respondeu Elias: Se eu sou homem de Deus, desça fogo do céu, e te consuma a ti e aos teus cinqüenta. Então o fogo de Deus desceu do céu, e consumiu a ele e aos seus cinqüenta.

[[v12-1-13]]

^<<v12-1-13,13>>^ Ainda tornou o rei a enviar terceira vez um chefe de cinqüenta com os seus cinqüenta. E o terceiro chefe de cinqüenta, subindo, veio e pôs-se de joelhos diante de Elias e suplicou-lhe, dizendo: ó homem de Deus, peço-te que seja preciosa aos teus olhos a minha vida, e a vida destes cinqüenta teus servos.

[[v12-1-14]]

^<<v12-1-14,14>>^ Eis que desceu fogo do céu, e consumiu aqueles dois primeiros chefes de cinqüenta, com os seus cinqüenta; agora, porém, seja preciosa aos teus olhos a minha vida.

[[v12-1-15]]

^<<v12-1-15,15>>^ Então o anjo do Senhor disse a Elias: Desce com este; não tenhas medo dele. Levantou-se, pois, e desceu com ele ao rei.

[[v12-1-16]]

^<<v12-1-16,16>>^ E disse-lhe: Assim diz o Senhor: Por que enviaste mensageiros a consultar a Baal-Zebube, deus de Ecrom? Porventura é porque não há Deus em Israel, para consultares a sua palavra? Portanto, desta cama a que subiste não descerás, mas certamente morrerás.

[[v12-1-17]]

^<<v12-1-17,17>>^ Assim, pois, morreu conforme a palavra do Senhor que Elias falara. E Jorão começou a reinar em seu lugar no ano segundo de Jeorão, filho de Jeosafá, rei de Judá; porquanto Acazias não tinha filho.

[[v12-1-18]]

^<<v12-1-18,18>>^ Ora, o restante dos feitos de Acazias, porventura não está escrito no livro das crônicas dos reis de Israel?

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]