include::./index.adoc[]

[[v12-23-0]]
=== 2 Reis, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v12-23-1]]

^<<v12-23-1,1>>^ Então o rei deu ordem, e todos os anciãos de Judá e de Jerusalém se ajuntaram a ele.

[[v12-23-2]]

^<<v12-23-2,2>>^ Subiu o rei à casa do Senhor, e com ele todos os homens de Judá, todos os habitantes de Jerusalém, os sacerdotes, os profetas, e todo o povo, desde o menor até o maior; e leu aos ouvidos deles todas as palavras do livro do pacto, que fora encontrado na casa do Senhor.

[[v12-23-3]]

^<<v12-23-3,3>>^ Então o rei, pondo-se em pé junto à coluna, fez um pacto perante o Senhor, de andar com o Senhor, e guardar os seus mandamentos, os seus testemunhos e os seus estatutos, de todo o coração e de toda a alma, confirmando as palavras deste pacto, que estavam escritas naquele livro; e todo o povo esteve por este pacto.

[[v12-23-4]]

^<<v12-23-4,4>>^ Também o rei mandou ao sumo sacerdote Hilquias, e aos sacerdotes da segunda ordem, e aos guardas da entrada, que tirassem do templo do Senhor todos os vasos que tinham sido feitos para Baal, e para a Asera, e para todo o exército do céu; e os queimou fora de Jerusalém, nos campos de Cedrom, e levou as cinzas deles para Betel.

[[v12-23-5]]

^<<v12-23-5,5>>^ Destituiu os sacerdotes idólatras que os reis de Judá haviam constituído para queimarem incenso sobre os altos nas cidades de Judá, e ao redor de Jerusalém, como também os que queimavam incenso a Baal, ao sol, à lua, aos planetas, e a todo o exército do céu.

[[v12-23-6]]

^<<v12-23-6,6>>^ Tirou da casa do Senhor a Asera e, levando-a para fora de Jerusalém até o ribeiro de Cedrom, ali a queimou e a reduziu a pó, e lançou o pó sobre as sepulturas dos filhos do povo.

[[v12-23-7]]

^<<v12-23-7,7>>^ Derrubou as casas dos sodomitas que estavam na casa do Senhor, em que as mulheres teciam cortinas para a Asera.

[[v12-23-8]]

^<<v12-23-8,8>>^ Tirou das cidades de Judá todos os sacerdotes, e profanou os altos em que os sacerdotes queimavam incenso desde Geba até Berseba; e derrubou os altos que estavam às portas junto à entrada da porta de Josué, o chefe da cidade, à esquerda daquele que entrava pela porta da cidade.

[[v12-23-9]]

^<<v12-23-9,9>>^ Todavia os sacerdotes dos altos não sacrificavam sobre o altar do Senhor em Jerusalém, porém comiam pães ázimos no meio de seus irmãos.

[[v12-23-10]]

^<<v12-23-10,10>>^ Profanou a Tofete, que está no vale dos filhos de Hinom, para que ninguém fosse passar seu filho ou sua filha pelo fogo a Moloque.

[[v12-23-11]]

^<<v12-23-11,11>>^ Tirou os cavalos que os reis de Judá tinham consagrado ao sol, à entrada da casa do Senhor, perto da câmara do camareiro Natã-Meleque, a qual estava no recinto; e os carros do sol queimou a fogo.

[[v12-23-12]]

^<<v12-23-12,12>>^ Também o rei derrubou os altares que estavam sobre o terraço do cenáculo de Acaz, os quais os reis de Judá tinham feito, como também os altares que Manassés fizera nos dois átrios da casa do Senhor; e, tendo-os esmigalhado, os tirou dali e lançou o pó deles no ribeiro de Cedrom.

[[v12-23-13]]

^<<v12-23-13,13>>^ O rei profanou também os altos que estavam ao oriente de Jerusalém, à direita do Monte de Corrupção, os quais Salomão, rei de Israel, edificara a Astarote, abominação dos sidônios, a Quemós, abominação dos moabitas, e a Milcom, abominação dos filhos de Amom.

[[v12-23-14]]

^<<v12-23-14,14>>^ Semelhantemente quebrou as colunas, e cortou os aserins, e encheu os seus lugares de ossos de homens.

[[v12-23-15]]

^<<v12-23-15,15>>^ Igualmente o altar que estava em Betel, e o alto feito por Jeroboão, filho de Nebate, que fizera Israel pecar, esse altar e o alto ele os derrubou; queimando o alto, reduziu-o a pó, e queimou a Asera.

[[v12-23-16]]

^<<v12-23-16,16>>^ E, virando-se Josias, viu as sepulturas que estavam ali no monte, e mandou tirar os ossos das sepulturas e os queimou sobre aquele altar, e assim o profanou, conforme a palavra do Senhor proclamada pelo homem de Deus que predissera estas coisas.

[[v12-23-17]]

^<<v12-23-17,17>>^ Então perguntou: Que monumento é este que vejo? Responderam-lhe os homens da cidade: É a sepultura do homem de Deus que veio de Judá e predisse estas coisas que acabas de fazer contra este altar de Betel.

[[v12-23-18]]

^<<v12-23-18,18>>^ Ao que disse Josias: Deixai-o estar; ninguém mexa nos seus ossos. Deixaram estar, pois, os seus ossos juntamente com os do profeta que viera de Samária.

[[v12-23-19]]

^<<v12-23-19,19>>^ Josias tirou também todas as casas dos altos que havia nas cidades de Samária, e que os reis de Israel tinham feito para provocarem o Senhor à ira, e lhes fez conforme tudo o que havia feito em Betel.

[[v12-23-20]]

^<<v12-23-20,20>>^ E a todos os sacerdotes dos altos que encontrou ali, ele os matou sobre os respectivos altares, onde também queimou ossos de homens; depois voltou a Jerusalém.

[[v12-23-21]]

^<<v12-23-21,21>>^ Então o rei deu ordem a todo o povo dizendo: Celebrai a páscoa ao Senhor vosso Deus, como está escrito neste livro do pacto.

[[v12-23-22]]

^<<v12-23-22,22>>^ Pois não se celebrara tal páscoa desde os dias dos juízes que julgaram a Israel, nem em todos os dias dos reis de Israel, nem tampouco nos dias dos reis de Judá.

[[v12-23-23]]

^<<v12-23-23,23>>^ Foi no décimo oitavo ano do rei Josias que esta páscoa foi celebrada ao Senhor em Jerusalém.

[[v12-23-24]]

^<<v12-23-24,24>>^ Além disso, os adivinhos, os feiticeiros, os terafins, os ídolos e todas abominações que se viam na terra de Judá e em Jerusalém, Josias os extirpou, para confirmar as palavras da lei, que estavam escritas no livro que o sacerdote Hilquias achara na casa do Senhor.

[[v12-23-25]]

^<<v12-23-25,25>>^ Ora, antes dele não houve rei que lhe fosse semelhante, que se convertesse ao Senhor de todo o seu coração, e de toda a sua alma, e de todas as suas forças, conforme toda a lei de Moisés; e depois dele nunca se levantou outro semelhante.

[[v12-23-26]]

^<<v12-23-26,26>>^ Todavia o Senhor não se demoveu do ardor da sua grande ira, com que ardia contra Judá por causa de todas as provocações com que Manassés o provocara.

[[v12-23-27]]

^<<v12-23-27,27>>^ E disse o Senhor: Também a Judá hei de remover de diante da minha face, como removi a Israel, e rejeitarei esta cidade de Jerusalém que elegi, como também a casa da qual eu disse: Estará ali o meu nome.

[[v12-23-28]]

^<<v12-23-28,28>>^ Ora, o restante dos atos de Josias, e tudo quanto fez, por ventura não estão escritos no livro das crônicas dos reis de Judá?

[[v12-23-29]]

^<<v12-23-29,29>>^ Nos seus dias subiu Faraó-Neco, rei do Egito, contra o rei da Assíria, ao rio Eufrates. E o rei Josias lhe foi ao encontro; e Faraó-Neco o matou em Megido, logo que o viu.

[[v12-23-30]]

^<<v12-23-30,30>>^ De Megido os seus servos o levaram morto num carro, e o trouxeram a Jerusalém, onde o sepultaram no seu sepulcro. E o povo da terra tomou a Jeoacaz, filho de Josias, ungiram-no, e o fizeram rei em lugar de seu pai.

[[v12-23-31]]

^<<v12-23-31,31>>^ Jeoacaz tinha vinte e três anos quando começou a reinar, e reinou três meses em Jerusalém. O nome de sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v12-23-32]]

^<<v12-23-32,32>>^ Ele fez o que era mau aos olhos do Senhor, conforme tudo o que seus pais haviam feito.

[[v12-23-33]]

^<<v12-23-33,33>>^ Ora, Faraó-Neco mandou prendê-lo em Ribla, na terra de Hamate, para que não reinasse em Jerusalém; e à terra impôs o tributo de cem talentos de prata e um talento de ouro.

[[v12-23-34]]

^<<v12-23-34,34>>^ Também Faraó-Neco constituiu rei a Eliaquim, filho de Josias, em lugar de Josias, seu pai, e lhe mudou o nome em Jeoiaquim; porém levou consigo a Jeoacaz, que conduzido ao Egito, ali morreu.

[[v12-23-35]]

^<<v12-23-35,35>>^ E Jeoiaquim deu a Faraó a prata e o ouro; porém impôs à terra uma taxa, para fornecer esse dinheiro conforme o mandado de Faraó. Exigiu do povo da terra, de cada um segundo a sua avaliação, prata e ouro, para o dar a Faraó-Neco.

[[v12-23-36]]

^<<v12-23-36,36>>^ Jeoiaquim tinha vinte e cinco ano quando começou a reinar, e reinou onze anos em Jerusalém. O nome de sua mãe era Zebida, filha de Pedaías, de Ruma.

[[v12-23-37]]

^<<v12-23-37,37>>^ Ele fez o que era mau aos olhos do Senhor, conforme tudo o que seus pais haviam feito.

'''

xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[&#60; Capítulo Anterior] | <<v12-23-0,Topo>> | xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[Próximo Capítulo &#62;]