include::./index.adoc[]

[[v1-28-0]]
=== Gênesis, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-28-1]]

^<<v1-28-1,1>>^ Isaque, pois, chamou Jacó, e o abençoou, e ordenou-lhe, dizendo: Não tomes mulher dentre as filhas de Canaã.

[[v1-28-2]]

^<<v1-28-2,2>>^ Levanta-te, vai a Padã-Arã, à casa de Betuel, pai de tua mãe, e toma de lá uma mulher dentre as filhas de Labão, irmão de tua mãe.

[[v1-28-3]]

^<<v1-28-3,3>>^ Deus Todo-Poderoso te abençoe, te faça frutificar e te multiplique, para que venhas a ser uma multidão de povos; seu

[[v1-28-4]]

^<<v1-28-4,4>>^ e te dê a bênção de Abraão, a ti e à tua descendência contigo, para que herdes a terra de tuas peregrinações, que Deus deu a Abraão.

[[v1-28-5]]

^<<v1-28-5,5>>^ Assim despediu Isaque a Jacó, o qual foi a Padã-Arã, a Labão, filho de Betuel, arameu, irmão de Rebeca, mãe de Jacó e de Esaú.

[[v1-28-6]]

^<<v1-28-6,6>>^ Ora, viu Esaú que Isaque abençoara a Jacó, e o enviara a Padã-Arã, para tomar de lá mulher para si, e que, abençoando-o, lhe ordenara, dizendo: Não tomes mulher dentre as filhas de Canaã,

[[v1-28-7]]

^<<v1-28-7,7>>^ e que Jacó, obedecendo a seu pai e a sua mãe, fora a Padã-Arã;

[[v1-28-8]]

^<<v1-28-8,8>>^ vendo também Esaú que as filhas de Canaã eram más aos olhos de Isaque seu pai,

[[v1-28-9]]

^<<v1-28-9,9>>^ foi-se Esaú a Ismael e, além das mulheres que já tinha, tomou por mulher a Maalate, filha de Ismael, filho de Abraão, irmã de Nebaiote.

[[v1-28-10]]

^<<v1-28-10,10>>^ Partiu, pois, Jacó de Beer-Seba e se foi em direção a Harã;

[[v1-28-11]]

^<<v1-28-11,11>>^ e chegou a um lugar onde passou a noite, porque o sol já se havia posto; e, tomando uma das pedras do lugar e pondo-a debaixo da cabeça, deitou-se ali para dormir.

[[v1-28-12]]

^<<v1-28-12,12>>^ Então sonhou: estava posta sobre a terra uma escada, cujo topo chegava ao céu; e eis que os anjos de Deus subiam e desciam por ela;

[[v1-28-13]]

^<<v1-28-13,13>>^ por cima dela estava o Senhor, que disse: Eu sou o Senhor, o Deus de Abraão teu pai, e o Deus de Isaque; esta terra em que estás deitado, eu a darei a ti e à tua descendência;

[[v1-28-14]]

^<<v1-28-14,14>>^ e a tua descendência será como o pó da terra; dilatar-te-ás para o ocidente, para o oriente, para o norte e para o sul; por meio de ti e da tua descendência serão benditas todas as famílias da terra.

[[v1-28-15]]

^<<v1-28-15,15>>^ Eis que estou contigo, e te guardarei por onde quer que fores, e te farei tornar a esta terra; pois não te deixarei até que haja cumprido aquilo de que te tenho falado.

[[v1-28-16]]

^<<v1-28-16,16>>^ Ao acordar Jacó do seu sono, disse: Realmente o Senhor está neste lugar; e eu não o sabia.

[[v1-28-17]]

^<<v1-28-17,17>>^ E temeu, e disse: Quão terrível é este lugar! Este não é outro lugar senão a casa de Deus; e esta é a porta dos céus.

[[v1-28-18]]

^<<v1-28-18,18>>^ Jacó levantou-se de manhã cedo, tomou a pedra que pusera debaixo da cabeça, e a pôs como coluna; e derramou-lhe azeite em cima.

[[v1-28-19]]

^<<v1-28-19,19>>^ E chamou aquele lugar Betel; porém o nome da cidade antes era Luz.

[[v1-28-20]]

^<<v1-28-20,20>>^ Fez também Jacó um voto, dizendo: Se Deus for comigo e me guardar neste caminho que vou seguindo, e me der pão para comer e vestes para vestir,

[[v1-28-21]]

^<<v1-28-21,21>>^ de modo que eu volte em paz à casa de meu pai, e se o Senhor for o meu Deus,

[[v1-28-22]]

^<<v1-28-22,22>>^ então esta pedra que tenho posto como coluna será casa de Deus; e de tudo quanto me deres, certamente te darei o dízimo.

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]