include::./index.adoc[]

[[v1-34-0]]
=== Gênesis, 34
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-34-1]]

^<<v1-34-1,1>>^ Diná, filha de Léia, que esta tivera de Jacó, saiu para ver as filhas da terra.

[[v1-34-2]]

^<<v1-34-2,2>>^ Viu-a Siquém, filho de Hamor o heveu, príncipe da terra; e, tomando-a, deitou-se com ela e humilhou-a.

[[v1-34-3]]

^<<v1-34-3,3>>^ Assim se apegou a sua alma a Diná, filha de Jacó, e, amando a donzela, falou-lhe afetuosamente.

[[v1-34-4]]

^<<v1-34-4,4>>^ Então disse Siquém a Hamor seu pai: Consegue-me esta donzela por mulher.

[[v1-34-5]]

^<<v1-34-5,5>>^ Ora, Jacó ouviu que Siquém havia contaminado a Diná sua filha. Entretanto, estando seus filhos no campo com o gado, calou-se Jacó até que viessem.

[[v1-34-6]]

^<<v1-34-6,6>>^ Hamor, pai de Siquém, saiu a fim de falar com Jacó.

[[v1-34-7]]

^<<v1-34-7,7>>^ Os filhos de Jacó, pois, vieram do campo logo que souberam do caso; e entristeceram-se e iraram-se muito, porque Siquém havia cometido uma insensatez em Israel, deitando-se com a filha de Jacó, coisa que não se devia fazer.

[[v1-34-8]]

^<<v1-34-8,8>>^ Então falou Hamor com eles, dizendo: A alma de meu filho Siquém afeiçoou-se fortemente a vossa filha; dai-lha, peço-vos, por mulher.

[[v1-34-9]]

^<<v1-34-9,9>>^ Também aparentai-vos conosco; dai-nos as vossas filhas e recebei as nossas.

[[v1-34-10]]

^<<v1-34-10,10>>^ Assim habitareis conosco; a terra estará diante de vós; habitai e negociai nela, e nela adquiri propriedades.

[[v1-34-11]]

^<<v1-34-11,11>>^ Depois disse Siquém ao pai e aos irmãos dela: Ache eu graça aos vossos olhos, e darei o que me disserdes;

[[v1-34-12]]

^<<v1-34-12,12>>^ exigi de mim o que quiserdes em dote e presentes, e darei o que me pedirdes; somente dai-me a donzela por mulher.

[[v1-34-13]]

^<<v1-34-13,13>>^ Então os filhos de Jacó, respondendo, falaram enganosamente a Siquém e a Hamor, seu pai, porque Siquém havia contaminado a Diná, sua irmã,

[[v1-34-14]]

^<<v1-34-14,14>>^ e lhes disseram: Não podemos fazer p isto, dar a nossa irmã a um homem incircunciso; porque isso seria uma vergonha para nós.

[[v1-34-15]]

^<<v1-34-15,15>>^ Sob esta única condição consentiremos; se vos tornardes como nós, circuncidando-se todo varão entre vós;

[[v1-34-16]]

^<<v1-34-16,16>>^ então vos daremos nossas filhas a vós, e receberemos vossas filhas para nós; assim habitaremos convosco e nos tornaremos um só povo.

[[v1-34-17]]

^<<v1-34-17,17>>^ Mas se não nos ouvirdes, e não vos circuncidardes, levaremos nossa filha e nos iremos embora.

[[v1-34-18]]

^<<v1-34-18,18>>^ E suas palavras agradaram a Hamor e a Siquém, seu filho.

[[v1-34-19]]

^<<v1-34-19,19>>^ Não tardou, pois, o mancebo em fazer isso, porque se agradava da filha de Jacó. Era ele o mais honrado de toda a casa de seu pai.

[[v1-34-20]]

^<<v1-34-20,20>>^ Vieram, pois, Hamor e Siquém, seu filho, à porta da sua cidade, e falaram aos homens da cidade, dizendo:

[[v1-34-21]]

^<<v1-34-21,21>>^ Estes homens são pacíficos para conosco; portanto habitem na terra e negociem nela, pois é bastante espaçosa para eles. Recebamos por mulheres as suas filhas, e lhes demos as nossas.

[[v1-34-22]]

^<<v1-34-22,22>>^ Mas sob uma única condição é que consentirão aqueles homens em habitar conosco para nos tornarmos um só povo: se todo varão entre nós se circuncidar, como eles são circuncidados.

[[v1-34-23]]

^<<v1-34-23,23>>^ O seu gado, as suas aquisições, e todos os seus animais, não serão nossos? consintamos somente com eles, e habitarão conosco.

[[v1-34-24]]

^<<v1-34-24,24>>^ E deram ouvidos a Hamor e a Siquém, seu filho, todos os que saíam da porta da cidade; e foi circuncidado todo varão, todos os que saíam pela porta da sua cidade.

[[v1-34-25]]

^<<v1-34-25,25>>^ Ao terceiro dia, quando os homens estavam doridos, dois filhos de Jacó, Simeão e Levi, irmãos de Diná, tomaram cada um a sua espada, entraram na cidade com toda a segurança e mataram todo varão.

[[v1-34-26]]

^<<v1-34-26,26>>^ Mataram também ao fio da espada a Hamor e a Siquém, seu filho; e, tirando Diná da casa de Siquém, saíram.

[[v1-34-27]]

^<<v1-34-27,27>>^ Vieram os filhos de Jacó aos mortos e saquearam a cidade; porquanto haviam contaminado a sua irmã.

[[v1-34-28]]

^<<v1-34-28,28>>^ Tomaram-lhes os rebanhos, os bois, os jumentos, e o que havia tanto na cidade como no campo;

[[v1-34-29]]

^<<v1-34-29,29>>^ e todos os seus bens, e todos os seus pequeninos, e as suas mulheres, levaram por presa; e despojando as casas, levaram tudo o que havia nelas.

[[v1-34-30]]

^<<v1-34-30,30>>^ Então disse Jacó a Simeão e a Levi: Tendes-me perturbado, fazendo-me odioso aos habitantes da terra, aos cananeus e perizeus. Tendo eu pouca gente, eles se ajuntarão e me ferirão; e serei destruído, eu com minha casa.

[[v1-34-31]]

^<<v1-34-31,31>>^ Ao que responderam: Devia ele tratar a nossa irmã como a uma prostituta?

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]