include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-47-1]]

^<<v1-47-1,1>>^ Então veio José, e informou a Faraó, dizendo: Meu pai e meus irmãos, com seus rebanhos e seu gado, e tudo o que têm, chegaram da terra de Canaã e estão na terra de Gósen.

[[v1-47-2]]

^<<v1-47-2,2>>^ E tomou dentre seus irmãos cinco homens e os apresentou a Faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ Então perguntou Faraó a esses irmãos de José: Que ocupação é a vossa; Responderam-lhe: Nós, teus servos, somos pastores de ovelhas, tanto nós como nossos pais.

[[v1-47-4]]

^<<v1-47-4,4>>^ Disseram mais a Faraó: Viemos para peregrinar nesta terra; porque não há pasto para os rebanhos de teus servos, porquanto a fome é grave na terra de Canaã; agora, pois, rogamos-te permitas que teus servos habitem na terra de Gósen.

[[v1-47-5]]

^<<v1-47-5,5>>^ Então falou Faraó a José, dizendo: Teu pai e teus irmãos vieram a ti;

[[v1-47-6]]

^<<v1-47-6,6>>^ a terra do Egito está diante de ti; no melhor da terra faze habitar teu pai e teus irmãos; habitem na terra de Gósen. E se sabes que entre eles há homens capazes, põe-nos sobre os pastores do meu gado.

[[v1-47-7]]

^<<v1-47-7,7>>^ Também José introduziu a Jacó, seu pai, e o apresentou a Faraó; e Jacó abençoou a Faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ Então perguntou Faraó a Jacó: Quantos são os dias dos anos da tua vida?

[[v1-47-9]]

^<<v1-47-9,9>>^ Respondeu-lhe Jacó: Os dias dos anos das minhas peregrinações são cento e trinta anos; poucos e maus têm sido os dias dos anos da minha vida, e não chegaram aos dias dos anos da vida de meus pais nos dias das suas peregrinações.

[[v1-47-10]]

^<<v1-47-10,10>>^ E Jacó abençoou a Faraó, e saiu da sua presença.

[[v1-47-11]]

^<<v1-47-11,11>>^ José, pois, estabeleceu a seu pai e seus irmãos, dando-lhes possessão na terra do Egito, no melhor da terra, na terra de Ramessés, como Faraó ordenara.

[[v1-47-12]]

^<<v1-47-12,12>>^ E José sustentou de pão seu pai, seus irmãos e toda a casa de seu pai, segundo o número de seus filhos.

[[v1-47-13]]

^<<v1-47-13,13>>^ Ora, não havia pão em toda a terra, porque a fome era mui grave; de modo que a terra do Egito e a terra de Canaã desfaleciam por causa da fome.

[[v1-47-14]]

^<<v1-47-14,14>>^ Então José recolheu todo o dinheiro que se achou na terra do Egito, e na terra de Canaã, pelo trigo que compravam; e José trouxe o dinheiro à casa de Faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Quando se acabou o dinheiro na terra do Egito, e na terra de Canaã, vieram todos os egípcios a José, dizendo: Dá-nos pão; por que morreremos na tua presença? porquanto o dinheiro nos falta.

[[v1-47-16]]

^<<v1-47-16,16>>^ Respondeu José: Trazei o vosso gado, e vo-lo darei por vosso gado, se falta o dinheiro.

[[v1-47-17]]

^<<v1-47-17,17>>^ Então trouxeram o seu gado a José; e José deu-lhes pão em troca dos cavalos, e das ovelhas, e dos bois, e dos jumentos; e os sustentou de pão aquele ano em troca de todo o seu gado.

[[v1-47-18]]

^<<v1-47-18,18>>^ Findo aquele ano, vieram a José no ano seguinte e disseram-lhe: Não ocultaremos ao meu senhor que o nosso dinheiro está todo gasto; as manadas de gado já pertencem a meu senhor; e nada resta diante de meu senhor, senão o nosso corpo e a nossa terra;

[[v1-47-19]]

^<<v1-47-19,19>>^ por que morreremos diante dos teus olhos, tanto nós como a nossa terra? Compra-nos a nós e a nossa terra em troca de pão, e nós e a nossa terra seremos servos de Faraó; dá-nos também semente, para que vivamos e não morramos, e para que a terra não fique desolada.

[[v1-47-20]]

^<<v1-47-20,20>>^ Assim José comprou toda a terra do Egito para Faraó; porque os egípcios venderam cada um o seu campo, porquanto a fome lhes era grave em extremo; e a terra ficou sendo de Faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ Quanto ao povo, José fê-lo passar às cidades, desde uma até a outra extremidade dos confins do Egito.

[[v1-47-22]]

^<<v1-47-22,22>>^ Somente a terra dos sacerdotes não a comprou, porquanto os sacerdotes tinham rações de Faraó, e eles comiam as suas rações que Faraó lhes havia dado; por isso não venderam a sua terra.

[[v1-47-23]]

^<<v1-47-23,23>>^ Então disse José ao povo: Hoje vos tenho comprado a vós e a vossa terra para Faraó; eis aí tendes semente para vós, para que semeeis a terra.

[[v1-47-24]]

^<<v1-47-24,24>>^ Há de ser, porém, que no tempo as colheitas dareis a quinta parte a Faraó, e quatro partes serão vossas, para semente do campo, e para o vosso mantimento e dos que estão nas vossas casas, e para o mantimento de vossos filhinho.

[[v1-47-25]]

^<<v1-47-25,25>>^ Responderam eles: Tu nos tens conservado a vida! achemos graça aos olhos de meu senhor, e seremos servos de Faraó.

[[v1-47-26]]

^<<v1-47-26,26>>^ José, pois, estabeleceu isto por estatuto quanto ao solo do Egito, até o dia de hoje, que a Faraó coubesse o quinto a produção; somente a terra dos sacerdotes não ficou sendo de Faraó.

[[v1-47-27]]

^<<v1-47-27,27>>^ Assim habitou Israel na terra do Egito, na terra de Gósen; e nela adquiriram propriedades, e frutificaram e multiplicaram-se muito.

[[v1-47-28]]

^<<v1-47-28,28>>^ E Jacó viveu na terra do Egito dezessete anos; de modo que os dias de Jacó, os anos da sua vida, foram cento e quarenta e sete anos.

[[v1-47-29]]

^<<v1-47-29,29>>^ Quando se aproximava o tempo da morte de Israel, chamou ele a José, seu filho, e disse-lhe: Se tenho achado graça aos teus olhos, põe a mão debaixo da minha coxa, e usa para comigo de benevolência e de verdade: rogo-te que não me enterres no Egito;

[[v1-47-30]]

^<<v1-47-30,30>>^ mas quando eu dormir com os meus pais, levar-me-ás do Egito e enterrar-me-ás junto à sepultura deles. Respondeu José: Farei conforme a tua palavra.

[[v1-47-31]]

^<<v1-47-31,31>>^ E Jacó disse: Jura-me; e ele lhe jurou. Então Israel inclinou-se sobre a cabeceira da cama.

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]