include::./index.adoc[]

[[v1-14-0]]
=== Gênesis, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-14-1]]

^<<v1-14-1,1>>^ Aconteceu nos dias de Anrafel, rei de Sinar, Arioque, rei de Elasar, Quedorlaomer, rei de Elão, e Tidal, rei de Goiim,

[[v1-14-2]]

^<<v1-14-2,2>>^ que estes fizeram guerra a Bera, rei de Sodoma, a Birsa, rei de Gomorra, a Sinabe, rei de Admá, a Semeber, rei de Zeboim, e ao rei de Belá &#123;esta é Zoar&#125;.

[[v1-14-3]]

^<<v1-14-3,3>>^ Todos estes se ajuntaram no vale de Sidim &#123;que é o Mar Salgado&#125;.

[[v1-14-4]]

^<<v1-14-4,4>>^ Doze anos haviam servido a Quedorlaomer, mas ao décimo terceiro ano rebelaram-se.

[[v1-14-5]]

^<<v1-14-5,5>>^ Por isso, ao décimo quarto ano veio Quedorlaomer, e os reis que estavam com ele, e feriram aos refains em Asterote-Carnaim, aos zuzins em Hão, aos emins em Savé-Quiriataim,

[[v1-14-6]]

^<<v1-14-6,6>>^ e aos horeus no seu monte Seir, até El-Parã, que está junto ao deserto.

[[v1-14-7]]

^<<v1-14-7,7>>^ Depois voltaram e vieram a En-Mispate &#123;que é Cades&#125;, e feriram toda a terra dos amalequitas, e também dos amorreus, que habitavam em Hazazom-Tamar.

[[v1-14-8]]

^<<v1-14-8,8>>^ Então saíram os reis de Sodoma, de Gomorra, de Admá, de Zeboim e de Belá &#123;esta é Zoar&#125;, e ordenaram batalha contra eles no vale de Sidim,

[[v1-14-9]]

^<<v1-14-9,9>>^ contra Quedorlaomer, rei de Elão, Tidal, rei de Goiim, Anrafel, rei de Sinar, e Arioque, rei de Elasar; quatro reis contra cinco.

[[v1-14-10]]

^<<v1-14-10,10>>^ Ora, o vale de Sidim estava cheio de poços de betume; e fugiram os reis de Sodoma e de Gomorra, e caíram ali; e os restantes fugiram para o monte.

[[v1-14-11]]

^<<v1-14-11,11>>^ Tomaram, então, todos os bens de Sodoma e de Gomorra com todo o seu mantimento, e se foram.

[[v1-14-12]]

^<<v1-14-12,12>>^ Tomaram também a Ló, filho do irmão de Abrão, que habitava em Sodoma, e os bens dele, e partiram.

[[v1-14-13]]

^<<v1-14-13,13>>^ Então veio um que escapara, e o contou a Abrão, o hebreu. Ora, este habitava junto dos carvalhos de Manre, o amorreu, irmão de Escol e de Aner; estes eram aliados de Abrão.

[[v1-14-14]]

^<<v1-14-14,14>>^ Ouvindo, pois, Abrão que seu irmão estava preso, levou os seus homens treinados, nascidos em sua casa, em número de trezentos e dezoito, e perseguiu os reis até Dã.

[[v1-14-15]]

^<<v1-14-15,15>>^ Dividiu-se contra eles de noite, ele e os seus servos, e os feriu, perseguindo-os até Hobá, que fica à esquerda de Damasco.

[[v1-14-16]]

^<<v1-14-16,16>>^ Assim tornou a trazer todos os bens, e tornou a trazer também a Ló, seu irmão, e os bens dele, e também as mulheres e o povo.

[[v1-14-17]]

^<<v1-14-17,17>>^ Depois que Abrão voltou de ferir a Quedorlaomer e aos reis que estavam com ele, saiu-lhe ao encontro o rei de Sodoma, no vale de Savé &#123;que é o vale do rei&#125;.

[[v1-14-18]]

^<<v1-14-18,18>>^ Ora, Melquisedeque, rei de Salém, trouxe pão e vinho; pois era sacerdote do Deus Altíssimo;

[[v1-14-19]]

^<<v1-14-19,19>>^ e abençoou a Abrão, dizendo: bendito seja Abrão pelo Deus Altíssimo, o Criador dos céus e da terra!

[[v1-14-20]]

^<<v1-14-20,20>>^ E bendito seja o Deus Altíssimo, que entregou os teus inimigos nas tuas mãos! E Abrão deu-lhe o dízimo de tudo.

[[v1-14-21]]

^<<v1-14-21,21>>^ Então o rei de Sodoma disse a Abrão: Dá-me a mim as pessoas; e os bens toma-os para ti.

[[v1-14-22]]

^<<v1-14-22,22>>^ Abrão, porém, respondeu ao rei de Sodoma: Levanto minha mão ao Senhor, o Deus Altíssimo, o Criador dos céus e da terra,

[[v1-14-23]]

^<<v1-14-23,23>>^ jurando que não tomarei coisa alguma de tudo o que é teu, nem um fio, nem uma correia de sapato, para que não digas: Eu enriqueci a Abrão;

[[v1-14-24]]

^<<v1-14-24,24>>^ salvo tão somente o que os mancebos comeram, e a parte que toca aos homens Aner, Escol e Manre, que foram comigo; que estes tomem a sua parte.

'''

xref:001-genesis/001-genesis-013.adoc#v1-13-0[&#60; Capítulo Anterior] | <<v1-14-0,Topo>> | xref:001-genesis/001-genesis-015.adoc#v1-15-0[Próximo Capítulo &#62;]