include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacó habitava na terra das peregrinações de seu pai, na terra de Canaã.

[[v1-37-2]]

^<<v1-37-2,2>>^ Estas são as gerações de Jacó. José, aos dezessete anos de idade, estava com seus irmãos apascentando os rebanhos; sendo ainda jovem, andava com os filhos de Bila, e com os filhos de Zilpa, mulheres de seu pai; e José trazia a seu pai más notícias a respeito deles.

[[v1-37-3]]

^<<v1-37-3,3>>^ Israel amava mais a José do que a todos os seus filhos, porque era filho da sua velhice; e fez-lhe uma túnica de várias cores.

[[v1-37-4]]

^<<v1-37-4,4>>^ Vendo, pois, seus irmãos que seu pai o amava mais do que a todos eles, odiavam-no, e não lhe podiam falar pacificamente.

[[v1-37-5]]

^<<v1-37-5,5>>^ José teve um sonho, que contou a seus irmãos; por isso o odiaram ainda mais.

[[v1-37-6]]

^<<v1-37-6,6>>^ Pois ele lhes disse: Ouvi, peço-vos, este sonho que tive:

[[v1-37-7]]

^<<v1-37-7,7>>^ Estávamos nós atando molhos no campo, e eis que o meu molho, levantando-se, ficou em pé; e os vossos molhos o rodeavam, e se inclinavam ao meu molho.

[[v1-37-8]]

^<<v1-37-8,8>>^ Responderam-lhe seus irmãos: Tu pois, deveras reinarás sobre nós? Tu deveras terás domínio sobre nós? Por isso ainda mais o odiavam por causa dos seus sonhos e das suas palavras.

[[v1-37-9]]

^<<v1-37-9,9>>^ Teve José outro sonho, e o contou a seus irmãos, dizendo: Tive ainda outro sonho; e eis que o sol, e a lua, e onze estrelas se inclinavam perante mim.

[[v1-37-10]]

^<<v1-37-10,10>>^ Quando o contou a seu pai e a seus irmãos, repreendeu-o seu pai, e disse-lhe: Que sonho é esse que tiveste? Porventura viremos, eu e tua mãe, e teus irmãos, a inclinar-nos com o rosto em terra diante de ti?

[[v1-37-11]]

^<<v1-37-11,11>>^ Seus irmãos, pois, o invejavam; mas seu pai guardava o caso no seu coração.

[[v1-37-12]]

^<<v1-37-12,12>>^ Ora, foram seus irmãos apascentar o rebanho de seu pai, em Siquém.

[[v1-37-13]]

^<<v1-37-13,13>>^ Disse, pois, Israel a José: Não apascentam teus irmãos o rebanho em Siquém? Vem, e enviar-te-ei a eles. Respondeu-lhe José: Eis-me aqui.

[[v1-37-14]]

^<<v1-37-14,14>>^ Disse-lhe Israel: Vai, vê se vão bem teus irmãos, e o rebanho; e traze-me resposta. Assim o enviou do vale de Hebrom; e José foi a Siquém.

[[v1-37-15]]

^<<v1-37-15,15>>^ E um homem encontrou a José, que andava errante pelo campo, e perguntou-lhe: Que procuras?

[[v1-37-16]]

^<<v1-37-16,16>>^ Respondeu ele: Estou procurando meus irmãos; dize-me, peço-te, onde apascentam eles o rebanho.

[[v1-37-17]]

^<<v1-37-17,17>>^ Disse o homem: Foram-se daqui; pois ouvi-lhes dizer: Vamos a Dotã. José, pois, seguiu seus irmãos, e os achou em Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ Eles o viram de longe e, antes que chegasse aonde estavam, conspiraram contra ele, para o matarem,

[[v1-37-19]]

^<<v1-37-19,19>>^ dizendo uns aos outros: Eis que lá vem o sonhador!

[[v1-37-20]]

^<<v1-37-20,20>>^ Vinde pois agora, matemo-lo e lancemo-lo numa das covas; e diremos: uma besta-fera o devorou. Veremos, então, o que será dos seus sonhos.

[[v1-37-21]]

^<<v1-37-21,21>>^ Mas Rúben, ouvindo isso, livrou-o das mãos deles, dizendo: Não lhe tiremos a vida.

[[v1-37-22]]

^<<v1-37-22,22>>^ Também lhes disse Rúben: Não derrameis sangue; lançai-o nesta cova, que está no deserto, e não lanceis mão nele. Disse isto para livrá-lo das mãos deles, a fim de restituí-lo a seu pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ Logo que José chegou a seus irmãos, estes o despiram da sua túnica, a túnica de várias cores, que ele trazia;

[[v1-37-24]]

^<<v1-37-24,24>>^ e tomando-o, lançaram-no na cova; mas a cova estava vazia, não havia água nela.

[[v1-37-25]]

^<<v1-37-25,25>>^ Depois sentaram-se para comer; e, levantando os olhos, viram uma caravana de ismaelitas que vinha de Gileade; nos seus camelos traziam tragacanto, bálsamo e mirra, que iam levar ao Egito.

[[v1-37-26]]

^<<v1-37-26,26>>^ Disse Judá a seus irmãos: De que nos aproveita matar nosso irmão e encobrir o seu sangue?

[[v1-37-27]]

^<<v1-37-27,27>>^ Vinde, vendamo-lo a esses ismaelitas, e não seja nossa mão sobre ele; porque é nosso irmão, nossa carne. E escutaram-no seus irmãos.

[[v1-37-28]]

^<<v1-37-28,28>>^ Ao passarem os negociantes midianitas, tiraram José, alçando-o da cova, e venderam-no por vinte siclos de prata aos ismaelitas, os quais o levaram para o Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Ora, Rúben voltou à cova, e eis que José não estava na cova; pelo que rasgou as suas vestes

[[v1-37-30]]

^<<v1-37-30,30>>^ e, tornando a seus irmãos, disse: O menino não aparece; e eu, aonde irei?

[[v1-37-31]]

^<<v1-37-31,31>>^ Tomaram, então, a túnica de José, mataram um cabrito, e tingiram a túnica no sangue.

[[v1-37-32]]

^<<v1-37-32,32>>^ Enviaram a túnica de várias cores, mandando levá-la a seu pai e dizer-lhe: Achamos esta túnica; vê se é a túnica de teu filho, ou não.

[[v1-37-33]]

^<<v1-37-33,33>>^ Ele a reconheceu e exclamou: A túnica de meu filho! uma besta-fera o devorou; certamente José foi despedaçado.

[[v1-37-34]]

^<<v1-37-34,34>>^ Então Jacó rasgou as suas vestes, e pôs saco sobre os seus lombos e lamentou seu filho por muitos dias.

[[v1-37-35]]

^<<v1-37-35,35>>^ E levantaram-se todos os seus filhos e todas as suas filhas, para o consolarem; ele, porém, recusou ser consolado, e disse: Na verdade, com choro hei de descer para meu filho até o Seol. Assim o chorou seu pai.

[[v1-37-36]]

^<<v1-37-36,36>>^ Os midianitas venderam José no Egito a Potifar, oficial de Faraó, capitão da guarda.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]