include::./index.adoc[]

[[v1-17-0]]
=== Gênesis, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-17-1]]

^<<v1-17-1,1>>^ Quando Abrão tinha noventa e nove anos, apareceu-lhe o Senhor e lhe disse: Eu sou o Deus Todo-Poderoso; anda em minha presença, e sê perfeito;

[[v1-17-2]]

^<<v1-17-2,2>>^ e firmarei o meu pacto contigo, e sobremaneira te multiplicarei.

[[v1-17-3]]

^<<v1-17-3,3>>^ Ao que Abrão se prostrou com o rosto em terra, e Deus falou-lhe, dizendo:

[[v1-17-4]]

^<<v1-17-4,4>>^ Quanto a mim, eis que o meu pacto é contigo, e serás pai de muitas nações;

[[v1-17-5]]

^<<v1-17-5,5>>^ não mais serás chamado Abrão, mas Abraão será o teu nome; pois por pai de muitas nações te hei posto;

[[v1-17-6]]

^<<v1-17-6,6>>^ far-te-ei frutificar sobremaneira, e de ti farei nações, e reis sairão de ti;

[[v1-17-7]]

^<<v1-17-7,7>>^ estabelecerei o meu pacto contigo e com a tua descendência depois de ti em suas gerações, como pacto perpétuo, para te ser por Deus a ti e à tua descendência depois de ti.

[[v1-17-8]]

^<<v1-17-8,8>>^ Dar-te-ei a ti e à tua descendência depois de ti a terra de tuas peregrinações, toda a terra de Canaã, em perpétua possessão; e serei o seu Deus.

[[v1-17-9]]

^<<v1-17-9,9>>^ Disse mais Deus a Abraão: Ora, quanto a ti, guardarás o meu pacto, tu e a tua descendência depois de ti, nas suas gerações.

[[v1-17-10]]

^<<v1-17-10,10>>^ Este é o meu pacto, que guardareis entre mim e vós, e a tua descendência depois de ti: todo varão dentre vugar para aquele que me

[[v1-17-11]]

^<<v1-17-11,11>>^ Circuncidar-vos-eis na carne do prepúcio; e isto será por sinal de pacto entre mim e vós.

[[v1-17-12]]

^<<v1-17-12,12>>^ À idade de oito dias, todo varão dentre vós será circuncidado, por todas as vossas gerações, tanto o nascido em casa como o comprado por dinheiro a qualquer estrangeiro, que não for da tua linhagem.

[[v1-17-13]]

^<<v1-17-13,13>>^ Com efeito será circuncidado o nascido em tua casa, e o comprado por teu dinheiro; assim estará o meu pacto na vossa carne como pacto perpétuo.

[[v1-17-14]]

^<<v1-17-14,14>>^ Mas o incircunciso, que não se circuncidar na carne do prepúcio, essa alma será extirpada do seu povo; violou o meu pacto.

[[v1-17-15]]

^<<v1-17-15,15>>^ Disse Deus a Abraão: Quanto a Sarai, tua, mulher, não lhe chamarás mais Sarai, porem Sara será o seu nome.

[[v1-17-16]]

^<<v1-17-16,16>>^ Abençoá-la-ei, e também dela te darei um filho; sim, abençoá-la-ei, e ela será mãe de nações; reis de povos sairão dela.

[[v1-17-17]]

^<<v1-17-17,17>>^ Ao que se prostrou Abraão com o rosto em terra, e riu-se, e disse no seu coração: A um homem de cem anos há de nascer um filho? Dará à luz Sara, que tem noventa anos?

[[v1-17-18]]

^<<v1-17-18,18>>^ Depois disse Abraão a Deus: Oxalá que viva Ismael diante de ti!

[[v1-17-19]]

^<<v1-17-19,19>>^ E Deus lhe respondeu: Na verdade, Sara, tua mulher, te dará à luz um filho, e lhe chamarás Isaque; com ele estabelecerei o meu pacto como pacto perpétuo para a sua descendência depois dele.

[[v1-17-20]]

^<<v1-17-20,20>>^ E quanto a Ismael, também te tenho ouvido; eis que o tenho abençoado, e fá-lo-ei frutificar, e multiplicá-lo-ei grandissimamente; doze príncipes gerará, e dele farei uma grande nação.

[[v1-17-21]]

^<<v1-17-21,21>>^ O meu pacto, porém, estabelecerei com Isaque, que Sara te dará à luz neste tempo determinado, no ano vindouro.

[[v1-17-22]]

^<<v1-17-22,22>>^ Ao acabar de falar com Abraão, subiu Deus diante dele.

[[v1-17-23]]

^<<v1-17-23,23>>^ Logo tomou Abraão a seu filho Ismael, e a todos os nascidos na sua casa e a todos os comprados por seu dinheiro, todo varão entre os da casa de Abraão, e lhes circuncidou a carne do prepúcio, naquele mesmo dia, como Deus lhe ordenara.

[[v1-17-24]]

^<<v1-17-24,24>>^ Abraão tinha noventa e nove anos, quando lhe foi circuncidada a carne do prepúcio;

[[v1-17-25]]

^<<v1-17-25,25>>^ E Ismael, seu filho, tinha treze anos, quando lhe foi circuncidada a carne do prepúcio.

[[v1-17-26]]

^<<v1-17-26,26>>^ No mesmo dia foram circuncidados Abraão e seu filho Ismael.

[[v1-17-27]]

^<<v1-17-27,27>>^ E todos os homens da sua casa, assim os nascidos em casa, como os comprados por dinheiro ao estrangeiro, foram circuncidados com ele.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]