include::./index.adoc[]

[[v1-22-0]]
=== Gênesis, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-22-1]]

^<<v1-22-1,1>>^ Sucedeu, depois destas coisas, que Deus provou a Abraão, dizendo-lhe: Abraão! E este respondeu: Eis-me aqui.

[[v1-22-2]]

^<<v1-22-2,2>>^ Prosseguiu Deus: Toma agora teu filho; o teu único filho, Isaque, a quem amas; vai à terra de Moriá, e oferece-o ali em holocausto sobre um dos montes que te hei de mostrar.

[[v1-22-3]]

^<<v1-22-3,3>>^ Levantou-se, pois, Abraão de manhã cedo, albardou o seu jumento, e tomou consigo dois de seus moços e Isaque, seu filho; e, tendo cortado lenha para o holocausto, partiu para ir ao lugar que Deus lhe dissera.

[[v1-22-4]]

^<<v1-22-4,4>>^ Ao terceiro dia levantou Abraão os olhos, e viu o lugar de longe.

[[v1-22-5]]

^<<v1-22-5,5>>^ E disse Abraão a seus moços: Ficai-vos aqui com o jumento, e eu e o mancebo iremos até lá; depois de adorarmos, voltaremos a vós.

[[v1-22-6]]

^<<v1-22-6,6>>^ Tomou, pois, Abraão a lenha do holocausto e a pôs sobre Isaque, seu filho; tomou também na mão o fogo e o cutelo, e foram caminhando juntos.

[[v1-22-7]]

^<<v1-22-7,7>>^ Então disse Isaque a Abraão, seu pai: Meu pai! Respondeu Abraão: Eis-me aqui, meu filho! Perguntou-lhe Isaque: Eis o fogo e a lenha, mas onde está o cordeiro para o holocausto?

[[v1-22-8]]

^<<v1-22-8,8>>^ Respondeu Abraão: Deus proverá para si o cordeiro para o holocausto, meu filho. E os dois iam caminhando juntos.

[[v1-22-9]]

^<<v1-22-9,9>>^ Havendo eles chegado ao lugar que Deus lhe dissera, edificou Abraão ali o altar e pôs a lenha em ordem; o amarrou, a Isaque, seu filho, e o deitou sobre o altar em cima da lenha.

[[v1-22-10]]

^<<v1-22-10,10>>^ E, estendendo a mão, pegou no cutelo para imolar a seu filho.

[[v1-22-11]]

^<<v1-22-11,11>>^ Mas o anjo do Senhor lhe bradou desde o céu, e disse: Abraão, Abraão! Ele respondeu: Eis-me aqui.

[[v1-22-12]]

^<<v1-22-12,12>>^ Então disse o anjo: Não estendas a mão sobre o mancebo, e não lhe faças nada; porquanto agora sei que temes a Deus, visto que não me negaste teu filho, o teu único filho.

[[v1-22-13]]

^<<v1-22-13,13>>^ Nisso levantou Abraão os olhos e olhou, e eis atrás de si um carneiro embaraçado pelos chifres no mato; e foi Abraão, tomou o carneiro e o ofereceu em holocausto em lugar de seu filho.

[[v1-22-14]]

^<<v1-22-14,14>>^ Pelo que chamou Abraão àquele lugar Jeová-Jiré; donde se diz até o dia de hoje: No monte do Senhor se proverá.

[[v1-22-15]]

^<<v1-22-15,15>>^ Então o anjo do Senhor bradou a Abraão pela segunda vez desde o céu,

[[v1-22-16]]

^<<v1-22-16,16>>^ e disse: Por mim mesmo jurei, diz o Senhor, porquanto fizeste isto, e não me negaste teu filho, o teu único filho,

[[v1-22-17]]

^<<v1-22-17,17>>^ que deveras te abençoarei, e grandemente multiplicarei a tua descendência, como as estrelas do céu e como a areia que está na praia do mar; e a tua descendência possuirá a porta dos seus inimigos;

[[v1-22-18]]

^<<v1-22-18,18>>^ e em tua descendência serão benditas todas as nações da terra; porquanto obedeceste à minha voz.

[[v1-22-19]]

^<<v1-22-19,19>>^ Então voltou Abraão aos seus moços e, levantando-se, foram juntos a Beer-Seba; e Abraão habitou em Beer-Seba.

[[v1-22-20]]

^<<v1-22-20,20>>^ Depois destas coisas anunciaram a Abraão, dizendo: Eis que também Milca tem dado à luz filhos a Naor, teu irmão:

[[v1-22-21]]

^<<v1-22-21,21>>^ Uz o seu primogênito, e Buz seu irmão, e Quemuel, pai de Arão,

[[v1-22-22]]

^<<v1-22-22,22>>^ e Quesede, Hazo, Pildas, Jidlafe e Betuel.

[[v1-22-23]]

^<<v1-22-23,23>>^ E Betuel gerou a Rebeca. Esses oito deu à luz Milca a Naor, irmão de Abraão.

[[v1-22-24]]

^<<v1-22-24,24>>^ E a sua concubina, que se chamava Reumá, também deu à luz a Teba, Gaão, Taás e Maacá.

'''

xref:001-genesis/001-genesis-021.adoc#v1-21-0[&#60; Capítulo Anterior] | <<v1-22-0,Topo>> | xref:001-genesis/001-genesis-023.adoc#v1-23-0[Próximo Capítulo &#62;]