include::./index.adoc[]

[[v1-27-0]]
=== Gênesis, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-27-1]]

^<<v1-27-1,1>>^ Quando Isaque já estava velho, e se lhe enfraqueciam os olhos, de maneira que não podia ver, chamou a Esaú, seu filho mais velho, e disse-lhe: Meu filho! Ele lhe respondeu: Eis-me aqui!

[[v1-27-2]]

^<<v1-27-2,2>>^ Disse-lhe o pai: Eis que agora estou velho, e não sei o dia da minha morte;

[[v1-27-3]]

^<<v1-27-3,3>>^ toma, pois, as tuas armas, a tua aljava e o teu arco; e sai ao campo, e apanha para mim alguma caça;

[[v1-27-4]]

^<<v1-27-4,4>>^ e faze-me um guisado saboroso, como eu gosto, e traze-mo, para que eu coma; a fim de que a minha alma te abençoe, antes que morra.

[[v1-27-5]]

^<<v1-27-5,5>>^ Ora, Rebeca estava escutando quando Isaque falou a Esaú, seu filho. Saiu, pois, Esaú ao campo para apanhar caça e trazê-la.

[[v1-27-6]]

^<<v1-27-6,6>>^ Disse então Rebeca a Jacó, seu filho: Eis que ouvi teu pai falar com Esaú, teu irmão, dizendo:

[[v1-27-7]]

^<<v1-27-7,7>>^ Traze-me caça, e faze-me um guisado saboroso, para que eu coma, e te abençoe diante do Senhor, antes da minha morte.

[[v1-27-8]]

^<<v1-27-8,8>>^ Agora, pois, filho meu, ouve a minha voz naquilo que eu te ordeno:

[[v1-27-9]]

^<<v1-27-9,9>>^ Vai ao rebanho, e traze-me de lá das cabras dois bons cabritos; e eu farei um guisado saboroso para teu pai, como ele gosta;

[[v1-27-10]]

^<<v1-27-10,10>>^ e levá-lo-ás a teu pai, para que o coma, a fim de te abençoar antes da sua morte.

[[v1-27-11]]

^<<v1-27-11,11>>^ Respondeu, porém, Jacó a Rebeca, sua mãe: Eis que Esaú, meu irmão, é peludo, e eu sou liso.

[[v1-27-12]]

^<<v1-27-12,12>>^ Porventura meu pai me apalpará e serei a seus olhos como enganador; assim trarei sobre mim uma maldição, e não uma bênção.

[[v1-27-13]]

^<<v1-27-13,13>>^ Respondeu-lhe sua mãe: Meu filho, sobre mim caia essa maldição; somente obedece à minha voz, e vai trazer-mos.

[[v1-27-14]]

^<<v1-27-14,14>>^ Então ele foi, tomou-os e os trouxe a sua mãe, que fez um guisado saboroso como seu pai gostava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Depois Rebeca tomou as melhores vestes de Esaú, seu filho mais velho, que tinha consigo em casa, e vestiu a Jacó, seu filho mais moço;

[[v1-27-16]]

^<<v1-27-16,16>>^ com as peles dos cabritos cobriu-lhe as mãos e a lisura do pescoço;

[[v1-27-17]]

^<<v1-27-17,17>>^ e pôs o guisado saboroso e o pão que tinha preparado, na mão de Jacó, seu filho.

[[v1-27-18]]

^<<v1-27-18,18>>^ E veio Jacó a seu pai, e chamou: Meu pai! E ele disse: Eis-me aqui; quem és tu, meu filho?

[[v1-27-19]]

^<<v1-27-19,19>>^ Respondeu Jacó a seu pai: Eu sou Esaú, teu primogênito; tenho feito como me disseste; levanta-te, pois, senta-te e come da minha caça, para que a tua alma me abençoe.

[[v1-27-20]]

^<<v1-27-20,20>>^ Perguntou Isaque a seu filho: Como é que tão depressa a achaste, filho meu? Respondeu ele: Porque o Senhor, teu Deus, a mandou ao meu encontro.

[[v1-27-21]]

^<<v1-27-21,21>>^ Então disse Isaque a Jacó: Chega-te, pois, para que eu te apalpe e veja se és meu filho Esaú mesmo, ou não.

[[v1-27-22]]

^<<v1-27-22,22>>^ chegou-se Jacó a Isaque, seu pai, que o apalpou, e disse: A voz é a voz de Jacó, porém as mãos são as mãos de Esaú.

[[v1-27-23]]

^<<v1-27-23,23>>^ E não o reconheceu, porquanto as suas mãos estavam peludas, como as de Esaú seu irmão; e abençoou-o.

[[v1-27-24]]

^<<v1-27-24,24>>^ No entanto perguntou: Tu és mesmo meu filho Esaú? E ele declarou: Eu o sou.

[[v1-27-25]]

^<<v1-27-25,25>>^ Disse-lhe então seu pai: Traze-mo, e comerei da caça de meu filho, para que a minha alma te abençoe: E Jacó lho trouxe, e ele comeu; trouxe-lhe também vinho, e ele bebeu.

[[v1-27-26]]

^<<v1-27-26,26>>^ Disse-lhe mais Isaque, seu pai: Aproxima-te agora, e beija-me, meu filho.

[[v1-27-27]]

^<<v1-27-27,27>>^ E ele se aproximou e o beijou; e seu pai, sentindo-lhe o cheiro das vestes o abençoou, e disse: Eis que o cheiro de meu filho é como o cheiro de um campo que o Senhor abençoou.

[[v1-27-28]]

^<<v1-27-28,28>>^ Que Deus te dê do orvalho do céu, e dos lugares férteis da terra, e abundância de trigo e de mosto;

[[v1-27-29]]

^<<v1-27-29,29>>^ sirvam-te povos, e nações se encurvem a ti; sê senhor de teus irmãos, e os filhos da tua mãe se encurvem a ti; sejam malditos os que te amaldiçoarem, e benditos sejam os que te abençoarem.

[[v1-27-30]]

^<<v1-27-30,30>>^ Tão logo Isaque acabara de abençoar a Jacó, e este saíra da presença de seu pai, chegou da caça Esaú, seu irmão;

[[v1-27-31]]

^<<v1-27-31,31>>^ e fez também ele um guisado saboroso e, trazendo-o a seu pai, disse-lhe: Levanta-te, meu pai, e come da caça de teu filho, para que a tua alma me abençoe.

[[v1-27-32]]

^<<v1-27-32,32>>^ Perguntou-lhe Isaque, seu pai: Quem és tu? Respondeu ele: Eu sou teu filho, o teu primogênito, Esaú.

[[v1-27-33]]

^<<v1-27-33,33>>^ Então estremeceu Isaque de um estremecimento muito grande e disse: Quem, pois, é aquele que apanhou caça e ma trouxe? Eu comi de tudo, antes que tu viesses, e abençoei-o, e ele será bendito.

[[v1-27-34]]

^<<v1-27-34,34>>^ Esaú, ao ouvir as palavras de seu pai, bradou com grande e mui amargo brado, e disse a seu pai: Abençoa-me também a mim, meu pai!

[[v1-27-35]]

^<<v1-27-35,35>>^ Respondeu Isaque: Veio teu irmão e com sutileza tomou a tua bênção.

[[v1-27-36]]

^<<v1-27-36,36>>^ Disse Esaú: Não se chama ele com razão Jacó, visto que já por duas vezes me enganou? tirou-me o direito de primogenitura, e eis que agora me tirou a bênção. E perguntou: Não reservaste uma bênção para mim?

[[v1-27-37]]

^<<v1-27-37,37>>^ Respondeu Isaque a Esaú: Eis que o tenho posto por senhor sobre ti, e todos os seus irmãos lhe tenho dado por servos; e de trigo e de mosto o tenho fortalecido. Que, pois, poderei eu fazer por ti, meu filho?

[[v1-27-38]]

^<<v1-27-38,38>>^ Disse Esaú a seu pai: Porventura tens uma única bênção, meu pai? Abençoa-me também a mim, meu pai. E levantou Esaú a voz, e chorou.

[[v1-27-39]]

^<<v1-27-39,39>>^ Respondeu-lhe Isaque, seu pai: Longe dos lugares férteis da terra será a tua habitação, longe do orvalho do alto céu;

[[v1-27-40]]

^<<v1-27-40,40>>^ pela tua espada viverás, e a teu irmão, serviras; mas quando te tornares impaciente, então sacudirás o seu jugo do teu pescoço.

[[v1-27-41]]

^<<v1-27-41,41>>^ Esaú, pois, odiava a Jacó por causa da bênção com que seu pai o tinha abençoado, e disse consigo: Vêm chegando os dias de luto por meu pai; então hei de matar Jacó, meu irmão.

[[v1-27-42]]

^<<v1-27-42,42>>^ Ora, foram denunciadas a Rebeca estas palavras de Esaú, seu filho mais velho; pelo que ela mandou chamar Jacó, seu filho mais moço, e lhe disse: Eis que Esaú teu irmão se consola a teu respeito, propondo matar-te.

[[v1-27-43]]

^<<v1-27-43,43>>^ Agora, pois, meu filho, ouve a minha voz; levanta-te, refugia-te na casa de Labão, meu irmão, em Harã,

[[v1-27-44]]

^<<v1-27-44,44>>^ e demora-te com ele alguns dias, até que passe o furor de teu irmão;

[[v1-27-45]]

^<<v1-27-45,45>>^ até que se desvie de ti a ira de teu irmão, e ele se esqueça do que lhe fizeste; então mandarei trazer-te de lá; por que seria eu desfilhada de vós ambos num só dia?

[[v1-27-46]]

^<<v1-27-46,46>>^ E disse Rebeca a Isaque: Enfadada estou da minha vida, por causa das filhas de Hete; se Jacó tomar mulher dentre as filhas de Hete, tais como estas, dentre as filhas desta terra, para que viverei?

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]