include::./index.adoc[]

[[v1-35-0]]
=== Gênesis, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-35-1]]

^<<v1-35-1,1>>^ Depois disse Deus a Jacó: Levanta-te, sobe a Betel e habita ali; e faze ali um altar ao Deus que te apareceu quando fugias da face de Esaú, teu irmão.

[[v1-35-2]]

^<<v1-35-2,2>>^ Então disse Jacó à sua família, e a todos os que com ele estavam: Lançai fora os deuses estranhos que há no meio de vós, e purificai-vos e mudai as vossas vestes.

[[v1-35-3]]

^<<v1-35-3,3>>^ Levantemo-nos, e subamos a Betel; ali farei um altar ao Deus que me respondeu no dia da minha angústia, e que foi comigo no caminho por onde andei.

[[v1-35-4]]

^<<v1-35-4,4>>^ Entregaram, pois, a Jacó todos os deuses estranhos, que tinham nas mãos, e as arrecadas que pendiam das suas orelhas; e Jacó os escondeu debaixo do carvalho que está junto a Siquém.

[[v1-35-5]]

^<<v1-35-5,5>>^ Então partiram; e o terror de Deus sobreveio às cidades que lhes estavam ao redor, de modo que não perseguiram os filhos de Jacó.

[[v1-35-6]]

^<<v1-35-6,6>>^ Assim chegou Jacó à Luz, que está na terra de Canaã &#123;esta é Betel&#125;, ele e todo o povo que estava com ele.

[[v1-35-7]]

^<<v1-35-7,7>>^ Edificou ali um altar, e chamou ao lugar El-Betel; porque ali Deus se lhe tinha manifestado quando fugia da face de seu irmão.

[[v1-35-8]]

^<<v1-35-8,8>>^ Morreu Débora, a ama de Rebeca, e foi sepultada ao pé de Betel, debaixo do carvalho, ao qual se chamou Alom-Bacute.

[[v1-35-9]]

^<<v1-35-9,9>>^ Apareceu Deus outra vez a Jacó, quando ele voltou de Padã-Arã, e o abençoou.

[[v1-35-10]]

^<<v1-35-10,10>>^ E disse-lhe Deus: O teu nome é Jacó; não te chamarás mais Jacó, mas Israel será o teu nome. Chamou-lhe Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ Disse-lhe mais: Eu sou Deus Todo-Poderoso; frutifica e multiplica-te; uma nação, sim, uma multidão de nações sairá de ti, e reis procederão dos teus lombos;

[[v1-35-12]]

^<<v1-35-12,12>>^ a terra que dei a Abraão e a Isaque, a ti a darei; também à tua descendência depois de ti a darei.

[[v1-35-13]]

^<<v1-35-13,13>>^ E Deus subiu dele, do lugar onde lhe falara.

[[v1-35-14]]

^<<v1-35-14,14>>^ Então Jacó erigiu uma coluna no lugar onde Deus lhe falara, uma coluna de pedra; e sobre ela derramou uma libação e deitou-lhe também azeite;

[[v1-35-15]]

^<<v1-35-15,15>>^ e Jacó chamou Betel ao lugar onde Deus lhe falara.

[[v1-35-16]]

^<<v1-35-16,16>>^ Depois partiram de Betel; e, faltando ainda um trecho pequeno para chegar a Efrata, Raquel começou a sentir dores de parto, e custou-lhe o dar à luz.

[[v1-35-17]]

^<<v1-35-17,17>>^ Quando ela estava nas dores do parto, disse-lhe a parteira: Não temas, pois ainda terás este filho.

[[v1-35-18]]

^<<v1-35-18,18>>^ Então Raquel, ao sair-lhe a alma &#123;porque morreu&#125;, chamou ao filho Benôni; mas seu pai chamou-lhe Benjamim.

[[v1-35-19]]

^<<v1-35-19,19>>^ Assim morreu Raquel, e foi sepultada no caminho de Efrata &#123;esta é Bete-Leém&#125;.

[[v1-35-20]]

^<<v1-35-20,20>>^ E Jacó erigiu uma coluna sobre a sua sepultura; esta é a coluna da sepultura de Raquel até o dia de hoje.

[[v1-35-21]]

^<<v1-35-21,21>>^ Então partiu Israel, e armou a sua tenda além de Migdal-Eder.

[[v1-35-22]]

^<<v1-35-22,22>>^ Quando Israel habitava naquela terra, foi Rúben e deitou-se com Bila, concubina de seu pai; e Israel o soube. Eram doze os filhos de Jacó:

[[v1-35-23]]

^<<v1-35-23,23>>^ Os filhos de Léia: Rúben o primogênito de Jacó, depois Simeão, Levi, Judá, Issacar e Zebulom;

[[v1-35-24]]

^<<v1-35-24,24>>^ os filhos de Raquel: José e Benjamim;

[[v1-35-25]]

^<<v1-35-25,25>>^ os filhos de Bila, serva de Raquel: Dã e Naftali;

[[v1-35-26]]

^<<v1-35-26,26>>^ os filhos de Zilpa, serva de Léia: Gade e Aser. Estes são os filhos de Jacó, que lhe nasceram em Padã-Arã.

[[v1-35-27]]

^<<v1-35-27,27>>^ Jacó veio a seu pai Isaque, a Manre, a Quiriate-Arba &#123;esta é Hebrom&#125;, onde peregrinaram Abraão e Isaque.

[[v1-35-28]]

^<<v1-35-28,28>>^ Foram os dias de Isaque cento e oitenta anos;

[[v1-35-29]]

^<<v1-35-29,29>>^ e, exalando o espírito, morreu e foi congregado ao seu povo, velho e cheio de dias; e Esaú e Jacó, seus filhos, o sepultaram.

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]