include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-39-1]]

^<<v1-39-1,1>>^ José foi levado ao Egito; e Potifar, oficial de Faraó, capitão da guarda, egípcio, comprou-o da mão dos ismaelitas que o haviam levado para lá.

[[v1-39-2]]

^<<v1-39-2,2>>^ Mas o Senhor era com José, e ele tornou-se próspero; e estava na casa do seu senhor, o egípcio.

[[v1-39-3]]

^<<v1-39-3,3>>^ E viu o seu senhor que Deus era com ele, e que fazia prosperar em sua mão tudo quanto ele empreendia.

[[v1-39-4]]

^<<v1-39-4,4>>^ Assim José achou graça aos olhos dele, e o servia; de modo que o fez mordomo da sua casa, e entregou na sua mão tudo o que tinha.

[[v1-39-5]]

^<<v1-39-5,5>>^ Desde que o pôs como mordomo sobre a sua casa e sobre todos os seus bens, o Senhor abençoou a casa do egípcio por amor de José; e a bênção do Senhor estava sobre tudo o que tinha, tanto na casa como no campo.

[[v1-39-6]]

^<<v1-39-6,6>>^ Potifar deixou tudo na mão de José, de maneira que nada sabia do que estava com ele, a não ser do pão que comia. Ora, José era formoso de porte e de semblante.

[[v1-39-7]]

^<<v1-39-7,7>>^ E aconteceu depois destas coisas que a mulher do seu senhor pôs os olhos em José, e lhe disse: Deita-te comigo.

[[v1-39-8]]

^<<v1-39-8,8>>^ Mas ele recusou, e disse à mulher do seu senhor: Eis que o meu senhor não sabe o que está comigo na sua casa, e entregou em minha mão tudo o que tem;

[[v1-39-9]]

^<<v1-39-9,9>>^ ele não é maior do que eu nesta casa; e nenhuma coisa me vedou, senão a ti, porquanto és sua mulher. Como, pois, posso eu cometer este grande mal, e pecar contra Deus?

[[v1-39-10]]

^<<v1-39-10,10>>^ Entretanto, ela instava com José dia após dia; ele, porém, não lhe dava ouvidos, para se deitar com ela, ou estar com ela.

[[v1-39-11]]

^<<v1-39-11,11>>^ Mas sucedeu, certo dia, que entrou na casa para fazer o seu serviço; e nenhum dos homens da casa estava lá dentro.

[[v1-39-12]]

^<<v1-39-12,12>>^ Então ela, pegando-o pela capa, lhe disse: Deita-te comigo! Mas ele, deixando a capa na mão dela, fugiu, escapando para fora.

[[v1-39-13]]

^<<v1-39-13,13>>^ Quando ela viu que ele deixara a capa na mão dela e fugira para fora,

[[v1-39-14]]

^<<v1-39-14,14>>^ chamou pelos homens de sua casa, e disse-lhes: Vede! meu marido trouxe-nos um hebreu para nos insultar; veio a mim para se deitar comigo, e eu gritei em alta voz;

[[v1-39-15]]

^<<v1-39-15,15>>^ e ouvigiu-se para ela no caminho, e disse: Vem, deixa-me deixou, aqui a sua capa e fugiu, escapando para fora.

[[v1-39-16]]

^<<v1-39-16,16>>^ Ela guardou a capa consigo, até que o senhor dele voltou a casa.

[[v1-39-17]]

^<<v1-39-17,17>>^ Então falou-lhe conforme as mesmas palavras, dizendo: O servo hebreu, que nos trouxeste, veio a mim para me insultar;

[[v1-39-18]]

^<<v1-39-18,18>>^ mas, levantando eu a voz e gritando, ele deixou comigo a capa e fugiu para fora.

[[v1-39-19]]

^<<v1-39-19,19>>^ Tendo o seu senhor ouvido as palavras de sua mulher, que lhe falava, dizendo: Desta maneira me fez teu servo, a sua ira se acendeu.

[[v1-39-20]]

^<<v1-39-20,20>>^ Então o senhor de José o tomou, e o lançou no cárcere, no lugar em que os presos do rei estavam encarcerados; e ele ficou ali no cárcere.

[[v1-39-21]]

^<<v1-39-21,21>>^ O Senhor, porém, era com José, estendendo sobre ele a sua benignidade e dando-lhe graça aos olhos do carcereiro,

[[v1-39-22]]

^<<v1-39-22,22>>^ o qual entregou na mão de José todos os presos que estavam no cárcere; e era José quem ordenava tudo o que se fazia ali.

[[v1-39-23]]

^<<v1-39-23,23>>^ E o carcereiro não tinha cuidado de coisa alguma que estava na mão de José, porquanto o Senhor era com ele, fazendo prosperar tudo quanto ele empreendia.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]