include::./index.adoc[]

[[v1-23-0]]
=== Gênesis, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-23-1]]

^<<v1-23-1,1>>^ Ora, os anos da vida de Sara foram cento e vinte e sete.

[[v1-23-2]]

^<<v1-23-2,2>>^ E morreu Sara em Quiriate-Arba, que é Hebrom, na terra de Canaã; e veio Abraão lamentá-la e chorar por ela:

[[v1-23-3]]

^<<v1-23-3,3>>^ Depois se levantou Abraão de diante do seu morto, e falou aos filhos de Hete, dizendo:

[[v1-23-4]]

^<<v1-23-4,4>>^ Estrangeiro e peregrino sou eu entre vós; dai-me o direito de um lugar de sepultura entre vós, para que eu sepulte o meu morto, removendo-o de diante da minha face.

[[v1-23-5]]

^<<v1-23-5,5>>^ Responderam-lhe os filhos de Hete:

[[v1-23-6]]

^<<v1-23-6,6>>^ Ouve-nos, senhor; príncipe de Deus és tu entre nós; enterra o teu morto na mais escolhida de nossas sepulturas; nenhum de nós te vedará a sua sepultura, para enterrares o teu morto.

[[v1-23-7]]

^<<v1-23-7,7>>^ Então se levantou Abraão e, inclinando-se diante do povo da terra, diante dos filhos de Hete,

[[v1-23-8]]

^<<v1-23-8,8>>^ falou-lhes, dizendo: Se é de vossa vontade que eu sepulte o meu morto de diante de minha face, ouvi-me e intercedei por mim junto a Efrom, filho de Zoar,

[[v1-23-9]]

^<<v1-23-9,9>>^ para que ele me dê a cova de Macpela, que possui no fim do seu campo; que ma dê pelo devido preço em posse de sepulcro no meio de vós.

[[v1-23-10]]

^<<v1-23-10,10>>^ Ora, Efrom estava sentado no meio dos filhos de Hete; e respondeu Efrom, o heteu, a Abraão, aos ouvidos dos filhos de Hete, isto é, de todos os que entravam pela porta da sua cidade, dizendo:

[[v1-23-11]]

^<<v1-23-11,11>>^ Não, meu senhor; ouve-me. O campo te dou, também te dou a cova que nele está; na presença dos filhos do meu povo te dou; sepulta o teu morto.

[[v1-23-12]]

^<<v1-23-12,12>>^ Então Abraão se inclinou diante do povo da terra,

[[v1-23-13]]

^<<v1-23-13,13>>^ e falou a Efrom, aos ouvidos do povo da terra, dizendo: Se te agrada, peço-te que me ouças. Darei o preço do campo; toma-o de mim, e sepultarei ali o meu morto.

[[v1-23-14]]

^<<v1-23-14,14>>^ Respondeu Efrom a Abraão:

[[v1-23-15]]

^<<v1-23-15,15>>^ Meu senhor, ouve-me. Um terreno do valor de quatrocentos siclos de prata! que é isto entre mim e ti? Sepulta, pois, o teu morto.

[[v1-23-16]]

^<<v1-23-16,16>>^ E Abraão ouviu a Efrom, e pesou-lhe a prata de que este tinha falado aos ouvidos dos filhos de Hete, quatrocentos siclos de prata, moeda corrente entre os mercadores.

[[v1-23-17]]

^<<v1-23-17,17>>^ Assim o campo de Efrom, que estava em Macpela, em frente de Manre, o campo e a cova que nele estava, e todo o arvoredo que havia nele, por todos os seus limites ao redor, se confirmaram

[[v1-23-18]]

^<<v1-23-18,18>>^ a Abraão em possessão na presença dos filhos de Hete, isto é, de todos os que entravam pela porta da sua cidade.

[[v1-23-19]]

^<<v1-23-19,19>>^ Depois sepultou Abraão a Sara sua mulher na cova do campo de Macpela, em frente de Manre, que é Hebrom, na terra de Canaã.

[[v1-23-20]]

^<<v1-23-20,20>>^ Assim o campo e a cova que nele estava foram confirmados a Abraão pelos filhos de Hete em possessão de sepultura.

'''

xref:001-genesis/001-genesis-022.adoc#v1-22-0[&#60; Capítulo Anterior] | <<v1-23-0,Topo>> | xref:001-genesis/001-genesis-024.adoc#v1-24-0[Próximo Capítulo &#62;]