include::./index.adoc[]

[[v1-26-0]]
=== Gênesis, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-26-1]]

^<<v1-26-1,1>>^ Sobreveio à terra uma fome, além da primeira, que ocorreu nos dias de Abraão. Por isso foi Isaque a Abimeleque, rei dos filisteus, em Gerar.

[[v1-26-2]]

^<<v1-26-2,2>>^ E apareceu-lhe o Senhor e disse: Não desças ao Egito; habita na terra que eu te disser;

[[v1-26-3]]

^<<v1-26-3,3>>^ peregrina nesta terra, e serei contigo e te abençoarei; porque a ti, e aos que descenderem de ti, darei todas estas terras, e confirmarei o juramento que fiz a Abraão teu pai;

[[v1-26-4]]

^<<v1-26-4,4>>^ e multiplicarei a tua descendência como as estrelas do céu, e lhe darei todas estas terras; e por meio dela serão benditas todas as nações da terra;

[[v1-26-5]]

^<<v1-26-5,5>>^ porquanto Abraão obedeceu à minha voz, e guardou o meu mandado, os meus preceitos, os meus estatutos e as minhas leis.

[[v1-26-6]]

^<<v1-26-6,6>>^ Assim habitou Isaque em Gerar.

[[v1-26-7]]

^<<v1-26-7,7>>^ Então os homens do lugar perguntaram-lhe acerca de sua mulher, e ele respondeu: É minha irmã; porque temia dizer: É minha mulher; para que porventura, dizia ele, não me matassem os homens daquele lugar por amor de Rebeca; porque era ela formosa à vista.

[[v1-26-8]]

^<<v1-26-8,8>>^ Ora, depois que ele se demorara ali muito tempo, Abimeleque, rei dos filisteus, olhou por uma janela, e viu, e eis que Isaque estava brincando com Rebeca, sua mulher.

[[v1-26-9]]

^<<v1-26-9,9>>^ Então chamou Abimeleque a Isaque, e disse: Eis que na verdade é tua mulher; como pois disseste: E minha irmã? Respondeu-lhe Isaque: Porque eu dizia: Para que eu porventura não morra por sua causa.

[[v1-26-10]]

^<<v1-26-10,10>>^ Replicou Abimeleque: Que é isso que nos fizeste? Facilmente se teria deitado alguém deste povo com tua mulher, e tu terias trazido culpa sobre nós.

[[v1-26-11]]

^<<v1-26-11,11>>^ E Abimeleque ordenou a todo o povo, dizendo: Qualquer que tocar neste homem ou em sua mulher, certamente morrerá.

[[v1-26-12]]

^<<v1-26-12,12>>^ Isaque semeou naquela terra, e no mesmo ano colheu o cêntuplo; e o Senhor o abençoou.

[[v1-26-13]]

^<<v1-26-13,13>>^ E engrandeceu-se o homem; e foi-se enriquecendo até que se tornou mui poderoso;

[[v1-26-14]]

^<<v1-26-14,14>>^ e tinha possessões de rebanhos e de gado, e muita gente de serviço; de modo que os filisteus o invejavam.

[[v1-26-15]]

^<<v1-26-15,15>>^ Ora, todos os poços, que os servos de seu pai tinham cavado nos dias de seu pai Abraão, os filisteus entulharam e encheram de terra.

[[v1-26-16]]

^<<v1-26-16,16>>^ E Abimeleque disse a Isaque: Aparta-te de nós; porque muito mais poderoso te tens feito do que nós.

[[v1-26-17]]

^<<v1-26-17,17>>^ Então Isaque partiu dali e, acampando no vale de Gerar, lá habitou.

[[v1-26-18]]

^<<v1-26-18,18>>^ E Isaque tornou a cavar os poços que se haviam cavado nos dias de Abraão seu pai, pois os filisteus os haviam entulhado depois da morte de Abraão; e deu-lhes os nomes que seu pai lhes dera.

[[v1-26-19]]

^<<v1-26-19,19>>^ Cavaram, pois, os servos de Isaque naquele vale, e acharam ali um poço de águas vivas.

[[v1-26-20]]

^<<v1-26-20,20>>^ E os pastores de Gerar contenderam com os pastores de Isaque, dizendo: Esta água é nossa. E ele chamou ao poço Eseque, porque contenderam com ele.

[[v1-26-21]]

^<<v1-26-21,21>>^ Então cavaram outro poço, pelo qual também contenderam; por isso chamou-lhe Sitna.

[[v1-26-22]]

^<<v1-26-22,22>>^ E partiu dali, e cavou ainda outro poço; por este não contenderam; pelo que chamou-lhe Reobote, dizendo: Pois agora o Senhor nos deu largueza, e havemos de crescer na terra.

[[v1-26-23]]

^<<v1-26-23,23>>^ Depois subiu dali a Beer-Seba.

[[v1-26-24]]

^<<v1-26-24,24>>^ E apareceu-lhe o Senhor na mesma noite e disse: Eu sou o Deus de Abraão, teu pai; não temas, porque eu sou contigo, e te abençoarei e multiplicarei a tua descendência por amor do meu servo Abraão.

[[v1-26-25]]

^<<v1-26-25,25>>^ Isaque, pois, edificou ali um altar e invocou o nome do Senhor; então armou ali a sua tenda, e os seus servos cavaram um poço.

[[v1-26-26]]

^<<v1-26-26,26>>^ Então Abimeleque veio a ele de Gerar, com Aüzate, seu amigo, e Ficol, o chefe do seu exército.

[[v1-26-27]]

^<<v1-26-27,27>>^ E perguntou-lhes Isaque: Por que viestes ter comigo, visto que me odiais, e me repelistes de vós?

[[v1-26-28]]

^<<v1-26-28,28>>^ Responderam eles: Temos visto claramente que o Senhor é contigo, pelo que dissemos: Haja agora juramento entre nós, entre nós e ti; e façamos um pacto contigo,

[[v1-26-29]]

^<<v1-26-29,29>>^ que não nos farás mal, assim como nós não te havemos tocado, e te fizemos somente o bem, e te deixamos ir em paz. Agora tu és o bendito do Senhor.

[[v1-26-30]]

^<<v1-26-30,30>>^ Então Isaque lhes deu um banquete, e comeram e beberam.

[[v1-26-31]]

^<<v1-26-31,31>>^ E levantaram-se de manhã cedo e juraram de parte a parte; depois Isaque os despediu, e eles se despediram dele em paz.

[[v1-26-32]]

^<<v1-26-32,32>>^ Nesse mesmo dia vieram os servos de Isaque e deram-lhe notícias acerca do poço que haviam cavado, dizendo-lhe: Temos achado água.

[[v1-26-33]]

^<<v1-26-33,33>>^ E ele chamou o poço Seba; por isso é o nome da cidade Beer-Seba até o dia de hoje.

[[v1-26-34]]

^<<v1-26-34,34>>^ Ora, quando Esaú tinha quarenta anos, tomou por mulher a Judite, filha de Beeri, o heteu e a Basemate, filha de Elom, o heteu.

[[v1-26-35]]

^<<v1-26-35,35>>^ E estas foram para Isaque e Rebeca uma amargura de espírito.

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]