include::./index.adoc[]

[[v1-33-0]]
=== Gênesis, 33
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-33-1]]

^<<v1-33-1,1>>^ Levantou Jacó os olhos, e olhou, e eis que vinha Esaú, e quatrocentos homens com ele. Então repartiu os filhos entre Léia, e Raquel, e as duas servas.

[[v1-33-2]]

^<<v1-33-2,2>>^ Pôs as servas e seus filhos na frente, Léia e seus filhos atrás destes, e Raquel e José por últimos.

[[v1-33-3]]

^<<v1-33-3,3>>^ Mas ele mesmo passou adiante deles, e inclinou-se em terra sete vezes, até chegar perto de seu irmão.

[[v1-33-4]]

^<<v1-33-4,4>>^ Então Esaú correu-lhe ao encontro, abraçou-o, lançou-se-lhe ao pescoço, e o beijou; e eles choraram.

[[v1-33-5]]

^<<v1-33-5,5>>^ E levantando Esaú os olhos, viu as mulheres e os meninos, e perguntou: Quem são estes contigo? Respondeu-lhe Jacó: Os filhos que Deus bondosamente tem dado a teu servo.

[[v1-33-6]]

^<<v1-33-6,6>>^ Então chegaram-se as servas, elas e seus filhos, e inclinaram-se.

[[v1-33-7]]

^<<v1-33-7,7>>^ Chegaram-se também Léia e seus filhos, e inclinaram-se; depois chegaram-se José e Raquel e se inclinaram.

[[v1-33-8]]

^<<v1-33-8,8>>^ Perguntou Esaú: Que queres dizer com todo este bando que tenho encontrado? Respondeu Jacó: Para achar graça aos olhos de meu senhor.

[[v1-33-9]]

^<<v1-33-9,9>>^ Mas Esaú disse: Tenho bastante, meu irmão; seja teu o que tens.

[[v1-33-10]]

^<<v1-33-10,10>>^ Replicou-lhe Jacó: Não, mas se agora tenho achado graça aos teus olhos, aceita o presente da minha mão; porquanto tenho visto o teu rosto, como se tivesse visto o rosto de Deus, e tu te agradaste de mim.

[[v1-33-11]]

^<<v1-33-11,11>>^ Aceita, peço-te, o meu presente, que eu te trouxe; porque Deus tem sido bondoso para comigo, e porque tenho de tudo. E insistiu com ele, e ele o aceitou.

[[v1-33-12]]

^<<v1-33-12,12>>^ Então Esaú disse: Ponhamo-nos a caminho e vamos; eu irei adiante de ti.

[[v1-33-13]]

^<<v1-33-13,13>>^ Respondeu-lhe Jacó: Meu senhor sabe que estes filhos são tenros, e que tenho comigo ovelhas e vacas de leite; se forem obrigadas a caminhar demais por um só dia, todo o rebanho morrerá.

[[v1-33-14]]

^<<v1-33-14,14>>^ Passe o meu senhor adiante de seu servo; e eu seguirei, conduzindo-os calmamente, conforme o passo do gado que está diante de mim, e conforme o passo dos meninos, até que chegue a meu senhor em Seir.

[[v1-33-15]]

^<<v1-33-15,15>>^ Ao que disse Esaú: Permite ao menos que eu deixe contigo alguns da minha gente. Replicou Jacó: Para que? Basta que eu ache graça aos olhos de meu senhor.

[[v1-33-16]]

^<<v1-33-16,16>>^ Assim tornou Esaú aquele dia pelo seu caminho em direção a Seir.

[[v1-33-17]]

^<<v1-33-17,17>>^ Jacó, porém, partiu para Sucote, e edificou para si uma casa, e fez barracas para o seu gado; por isso o lugar se chama Sucote.

[[v1-33-18]]

^<<v1-33-18,18>>^ Depois chegou Jacó em paz à cidade de Siquém, que está na terra de Canaã, quando veio de Padã-Arã; e armou a sua tenda diante da cidade.

[[v1-33-19]]

^<<v1-33-19,19>>^ E comprou a parte do campo, em que estendera a sua tenda, dos filhos de Hamor, pai de Siquém, por cem peças de dinheiro.

[[v1-33-20]]

^<<v1-33-20,20>>^ Então levantou ali um altar, e chamou-lhe o El-Eloé-Israel.

'''

xref:001-genesis/001-genesis-032.adoc#v1-32-0[&#60; Capítulo Anterior] | <<v1-33-0,Topo>> | xref:001-genesis/001-genesis-034.adoc#v1-34-0[Próximo Capítulo &#62;]