include::./index.adoc[]

[[v1-8-0]]
=== Gênesis, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-8-1]]

^<<v1-8-1,1>>^ Deus lembrou-se de Noé, de todos os animais e de todo o gado, que estavam com ele na arca; e Deus fez passar um vento sobre a terra, e as águas começaram a diminuir.

[[v1-8-2]]

^<<v1-8-2,2>>^ Cerraram-se as fontes do abismo e as janelas do céu, e a chuva do céu se deteve;

[[v1-8-3]]

^<<v1-8-3,3>>^ as águas se foram retirando de sobre a terra; no fim de cento e cinqüenta dias começaram a minguar.

[[v1-8-4]]

^<<v1-8-4,4>>^ No sétimo mês, no dia dezessete do mês, repousou a arca sobre os montes de Arará.

[[v1-8-5]]

^<<v1-8-5,5>>^ E as águas foram minguando até o décimo mês; no décimo mês, no primeiro dia do mês, apareceram os cumes dos montes.

[[v1-8-6]]

^<<v1-8-6,6>>^ Ao cabo de quarenta dias, abriu Noé a janela que havia feito na arca;

[[v1-8-7]]

^<<v1-8-7,7>>^ soltou um corvo que, saindo, ia e voltava até que as águas se secaram de sobre a terra.

[[v1-8-8]]

^<<v1-8-8,8>>^ Depois soltou uma pomba, para ver se as águas tinham minguado de sobre a face da terra;

[[v1-8-9]]

^<<v1-8-9,9>>^ mas a pomba não achou onde pousar a planta do pé, e voltou a ele para a arca; porque as águas ainda estavam sobre a face de toda a terra; e Noé, estendendo a mão, tomou-a e a recolheu consigo na arca.

[[v1-8-10]]

^<<v1-8-10,10>>^ Esperou ainda outros sete dias, e tornou a soltar a pomba fora da arca.

[[v1-8-11]]

^<<v1-8-11,11>>^ À tardinha a pomba voltou para ele, e eis no seu bico uma folha verde de oliveira; assim soube Noé que as águas tinham minguado de sobre a terra.

[[v1-8-12]]

^<<v1-8-12,12>>^ Então esperou ainda outros sete dias, e soltou a pomba; e esta não tornou mais a ele.

[[v1-8-13]]

^<<v1-8-13,13>>^ No ano seiscentos e um, no mês primeiro, no primeiro dia do mês, secaram-se as águas de sobre a terra. Então Noé tirou a cobertura da arca: e olhou, e eis que a face a terra estava enxuta.

[[v1-8-14]]

^<<v1-8-14,14>>^ No segundo mês, aos vinte e sete dias do mês, a terra estava seca.

[[v1-8-15]]

^<<v1-8-15,15>>^ Então falou Deus a Noé, dizendo:

[[v1-8-16]]

^<<v1-8-16,16>>^ Sai da arca, tu, e juntamente contigo tua mulher, teus filhos e as mulheres de teus filhos.

[[v1-8-17]]

^<<v1-8-17,17>>^ Todos os animais que estão contigo, de toda a carne, tanto aves como gado e todo réptil que se arrasta sobre a terra, traze-os para fora contigo; para que se reproduzam abundantemente na terra, frutifiquem e se multipliquem sobre a terra.

[[v1-8-18]]

^<<v1-8-18,18>>^ Então saiu Noé, e com ele seus filhos, sua mulher e as mulheres de seus filhos;

[[v1-8-19]]

^<<v1-8-19,19>>^ todo animal, todo réptil e toda ave, tudo o que se move sobre a terra, segundo as suas famílias, saiu da arca.

[[v1-8-20]]

^<<v1-8-20,20>>^ Edificou Noé um altar ao Senhor; e tomou de todo animal limpo e de toda ave limpa, e ofereceu holocaustos sobre o altar.

[[v1-8-21]]

^<<v1-8-21,21>>^ Sentiu o Senhor o suave cheiro e disse em seu coração: Não tornarei mais a amaldiçoar a terra por causa do homem; porque a imaginação do coração do homem é má desde a sua meninice; nem tornarei mais a ferir todo vivente, como acabo de fazer.

[[v1-8-22]]

^<<v1-8-22,22>>^ Enquanto a terra durar, não deixará de haver sementeira e ceifa, frio e calor, verão e inverno, dia e noite.

'''

xref:001-genesis/001-genesis-007.adoc#v1-7-0[&#60; Capítulo Anterior] | <<v1-8-0,Topo>> | xref:001-genesis/001-genesis-009.adoc#v1-9-0[Próximo Capítulo &#62;]