include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-29-1]]

^<<v1-29-1,1>>^ Então pôs-se Jacó a caminho e chegou à terra dos filhos do Oriente.

[[v1-29-2]]

^<<v1-29-2,2>>^ E olhando, viu ali um poço no campo, e três rebanhos de ovelhas deitadas junto dele; pois desse poço se dava de beber aos rebanhos; e havia uma grande pedra sobre a boca do poço.

[[v1-29-3]]

^<<v1-29-3,3>>^ Ajuntavam-se ali todos os rebanhos; os pastores removiam a pedra da boca do poço, davam de beber às ovelhas e tornavam a pôr a pedra no seu lugar sobre a boca do poço.

[[v1-29-4]]

^<<v1-29-4,4>>^ Perguntou-lhes Jacó: Meus irmãos, donde sois? Responderam eles: Somos de Harã.

[[v1-29-5]]

^<<v1-29-5,5>>^ Perguntou-lhes mais: Conheceis a Labão, filho de Naor; Responderam: Conhecemos.

[[v1-29-6]]

^<<v1-29-6,6>>^ Perguntou-lhes ainda: vai ele bem? Responderam: Vai bem; e eis ali Raquel, sua filha, que vem chegando com as ovelhas.

[[v1-29-7]]

^<<v1-29-7,7>>^ Disse ele: Eis que ainda vai alto o dia; não é hora de se ajuntar o gado; dai de beber às ovelhas, e ide apascentá-las.

[[v1-29-8]]

^<<v1-29-8,8>>^ Responderam: Não podemos, até que todos os rebanhos se ajuntem, e seja removida a pedra da boca do poço; assim é que damos de beber às ovelhas.

[[v1-29-9]]

^<<v1-29-9,9>>^ Enquanto Jacó ainda lhes falava, chegou Raquel com as ovelhas de seu pai; porquanto era ela quem as apascentava.

[[v1-29-10]]

^<<v1-29-10,10>>^ Quando Jacó viu a Raquel, filha de Labão, irmão de sua mãe, e as ovelhas de Labão, irmão de sua mãe, chegou-se, revolveu a pedra da boca do poço e deu de beber às ovelhas de Labão, irmão de sua mãe.

[[v1-29-11]]

^<<v1-29-11,11>>^ Então Jacó beijou a Raquel e, levantando a voz, chorou.

[[v1-29-12]]

^<<v1-29-12,12>>^ E Jacó anunciou a Raquel que ele era irmão de seu pai, e que era filho de Rebeca. Raquel, pois foi correndo para anunciá-lo a, seu pai.

[[v1-29-13]]

^<<v1-29-13,13>>^ Quando Labão ouviu essas novas de Jacó, filho de sua irmã, correu-lhe ao encontro, abraçou-o, beijou-o e o levou à sua casa. E Jacó relatou a Labão todas essas, coisas.

[[v1-29-14]]

^<<v1-29-14,14>>^ Disse-lhe Labão: Verdadeiramente tu és meu osso e minha carne. E Jacó ficou com ele um mês inteiro.

[[v1-29-15]]

^<<v1-29-15,15>>^ Depois perguntou Labão a Jacó: Por seres meu irmão hás de servir-me de graça? Declara-me, qual será o teu salário?

[[v1-29-16]]

^<<v1-29-16,16>>^ Ora, Labão tinha duas filhas; o nome da mais velha era Léia, e o da mais moça Raquel.

[[v1-29-17]]

^<<v1-29-17,17>>^ Léia tinha os olhos enfermos, enquanto que Raquel era formosa de porte e de semblante.

[[v1-29-18]]

^<<v1-29-18,18>>^ Jacó, porquanto amava a Raquel, disse: Sete anos te servirei para ter a Raquel, tua filha mais moça.

[[v1-29-19]]

^<<v1-29-19,19>>^ Respondeu Labão: Melhor é que eu a dê a ti do que a outro; fica comigo.

[[v1-29-20]]

^<<v1-29-20,20>>^ Assim serviu Jacó sete anos por causa de Raquel; e estes lhe pareciam como poucos dias, pelo muito que a amava.

[[v1-29-21]]

^<<v1-29-21,21>>^ Então Jacó disse a Labão: Dá-me minha mulher, porque o tempo já está cumprido; para que eu a tome por mulher.

[[v1-29-22]]

^<<v1-29-22,22>>^ Reuniu, pois, Labão todos os homens do lugar, e fez um banquete.

[[v1-29-23]]

^<<v1-29-23,23>>^ À tarde tomou a Léia, sua filha e a trouxe a Jacó, que esteve com ela.

[[v1-29-24]]

^<<v1-29-24,24>>^ E Labão deu sua serva Zilpa por serva a Léia, sua filha.

[[v1-29-25]]

^<<v1-29-25,25>>^ Quando amanheceu, eis que era Léia; pelo que perguntou Jacó a Labão: Que é isto que me fizeste? Porventura não te servi em troca de Raquel? Por que, então, me enganaste?

[[v1-29-26]]

^<<v1-29-26,26>>^ Respondeu Labão: Não se faz assim em nossa terra; não se dá a menor antes da primogênita.

[[v1-29-27]]

^<<v1-29-27,27>>^ Cumpre a semana desta; então te daremos também a outra, pelo trabalho de outros sete anos que ainda me servirás.

[[v1-29-28]]

^<<v1-29-28,28>>^ Assim fez Jacó, e cumpriu a semana de Léia; depois Labão lhe deu por mulher sua filha Raquel.

[[v1-29-29]]

^<<v1-29-29,29>>^ E Labão deu sua serva Bila por serva a Raquel, sua filha.

[[v1-29-30]]

^<<v1-29-30,30>>^ Então Jacó esteve também com Raquel; e amou a Raquel muito mais do que a Léia; e serviu com Labão ainda outros sete anos.

[[v1-29-31]]

^<<v1-29-31,31>>^ Viu, pois, o Senhor que Léia era desprezada e tornou-lhe fecunda a madre; Raquel, porém, era estéril.

[[v1-29-32]]

^<<v1-29-32,32>>^ E Léia concebeu e deu à luz um filho, a quem chamou Rúben; pois disse: Porque o Senhor atendeu à minha aflição; agora me amará meu marido.

[[v1-29-33]]

^<<v1-29-33,33>>^ Concebeu outra vez, e deu à luz um filho; e disse: Porquanto o Senhor ouviu que eu era desprezada, deu-me também este. E lhe chamou Simeão.

[[v1-29-34]]

^<<v1-29-34,34>>^ Concebeu ainda outra vez e deu à luz um filho e disse: Agora esta vez se unirá meu marido a mim, porque três filhos lhe tenho dado. Portanto lhe chamou Levi.

[[v1-29-35]]

^<<v1-29-35,35>>^ De novo concebeu e deu à luz um filho; e disse: Esta vez louvarei ao Senhor. Por isso lhe chamou Judá. E cessou de ter filhos.

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]