include::./index.adoc[]

[[v1-9-0]]
=== Gênesis, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-9-1]]

^<<v1-9-1,1>>^ Abençoou Deus a Noé e a seus filhos, e disse-lhes: Frutificai e multiplicai-vos, e enchei a terra.

[[v1-9-2]]

^<<v1-9-2,2>>^ Terão medo e pavor de vós todo animal da terra, toda ave do céu, tudo o que se move sobre a terra e todos os peixes do mar; nas vossas mãos são entregues.

[[v1-9-3]]

^<<v1-9-3,3>>^ Tudo quanto se move e vive vos servirá de mantimento, bem como a erva verde; tudo vos tenho dado.

[[v1-9-4]]

^<<v1-9-4,4>>^ A carne, porém, com sua vida, isto é, com seu sangue, não comereis.

[[v1-9-5]]

^<<v1-9-5,5>>^ Certamente requererei o vosso sangue, o sangue das vossas vidas; de todo animal o requererei; como também do homem, sim, da mão do irmão de cada um requererei a vida do homem.

[[v1-9-6]]

^<<v1-9-6,6>>^ Quem derramar sangue de homem, pelo homem terá o seu sangue derramado; porque Deus fez o homem à sua imagem.

[[v1-9-7]]

^<<v1-9-7,7>>^ Mas vós frutificai, e multiplicai-vos; povoai abundantemente a terra, e multiplicai-vos nela.

[[v1-9-8]]

^<<v1-9-8,8>>^ Disse também Deus a Noé, e a seus filhos com ele:

[[v1-9-9]]

^<<v1-9-9,9>>^ Eis que eu estabeleço o meu pacto convosco e com a vossa descendência depois de vós,

[[v1-9-10]]

^<<v1-9-10,10>>^ e com todo ser vivente que convosco está: com as aves, com o gado e com todo animal da terra; com todos os que saíram da arca, sim, com todo animal da terra.

[[v1-9-11]]

^<<v1-9-11,11>>^ Sim, estabeleço o meu pacto convosco; não será mais destruída toda a carne pelas águas do dilúvio; e não haverá mais dilúvio, para destruir a terra.

[[v1-9-12]]

^<<v1-9-12,12>>^ E disse Deus: Este é o sinal do pacto que firmo entre mim e vós e todo ser vivente que está convosco, por gerações perpétuas:

[[v1-9-13]]

^<<v1-9-13,13>>^ O meu arco tenho posto nas nuvens, e ele será por sinal de haver um pacto entre mim e a terra.

[[v1-9-14]]

^<<v1-9-14,14>>^ E acontecerá que, quando eu trouxer nuvens sobre a terra, e aparecer o arco nas nuvens,

[[v1-9-15]]

^<<v1-9-15,15>>^ então me lembrarei do meu pacto, que está entre mim e vós e todo ser vivente de toda a carne; e as águas não se tornarão mais em dilúvio para destruir toda a carne.

[[v1-9-16]]

^<<v1-9-16,16>>^ O arco estará nas nuvens, e olharei para ele a fim de me lembrar do pacto perpétuo entre Deus e todo ser vivente de toda a carne que está sobre a terra.

[[v1-9-17]]

^<<v1-9-17,17>>^ Disse Deus a Noé ainda: Esse é o sinal do pacto que tenho estabelecido entre mim e toda a carne que está sobre a terra.

[[v1-9-18]]

^<<v1-9-18,18>>^ Ora, os filhos de Noé, que saíram da arca, foram Sem, Cam e Jafé; e Cam é o pai de Canaã.

[[v1-9-19]]

^<<v1-9-19,19>>^ Estes três foram os filhos de Noé; e destes foi povoada toda a terra.

[[v1-9-20]]

^<<v1-9-20,20>>^ E começou Noé a cultivar a terra e plantou uma vinha.

[[v1-9-21]]

^<<v1-9-21,21>>^ Bebeu do vinho, e embriagou-se; e achava-se nu dentro da sua tenda.

[[v1-9-22]]

^<<v1-9-22,22>>^ E Cam, pai de Canaã, viu a nudez de seu pai, e o contou a seus dois irmãos que estavam fora.

[[v1-9-23]]

^<<v1-9-23,23>>^ Então tomaram Sem e Jafé uma capa, e puseram-na sobre os seus ombros, e andando virados para trás, cobriram a nudez de seu pai, tendo os rostos virados, de maneira que não viram a nudez de seu pai.

[[v1-9-24]]

^<<v1-9-24,24>>^ Despertado que foi Noé do seu vinho, soube o que seu filho mais moço lhe fizera;

[[v1-9-25]]

^<<v1-9-25,25>>^ e disse: Maldito seja Canaã; servo dos servos será de seus irmãos.

[[v1-9-26]]

^<<v1-9-26,26>>^ Disse mais: Bendito seja o Senhor, o Deus de Sem; e seja-lhe Canaã por servo.

[[v1-9-27]]

^<<v1-9-27,27>>^ Alargue Deus a Jafé, e habite Jafé nas tendas de Sem; e seja-lhe Canaã por servo.

[[v1-9-28]]

^<<v1-9-28,28>>^ Viveu Noé, depois do dilúvio, trezentos e cinqüenta anos.

[[v1-9-29]]

^<<v1-9-29,29>>^ E foram todos os dias de Noé novecentos e cinqüenta anos; e morreu.

'''

xref:001-genesis/001-genesis-008.adoc#v1-8-0[&#60; Capítulo Anterior] | <<v1-9-0,Topo>> | xref:001-genesis/001-genesis-010.adoc#v1-10-0[Próximo Capítulo &#62;]