include::./index.adoc[]

[[v1-2-0]]
=== Gênesis, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-2-1]]

^<<v1-2-1,1>>^ Assim foram acabados os céus e a terra, com todo o seu exército.

[[v1-2-2]]

^<<v1-2-2,2>>^ Ora, havendo Deus completado no dia sétimo a obra que tinha feito, descansou nesse dia de toda a obra que fizera.

[[v1-2-3]]

^<<v1-2-3,3>>^ Abençoou Deus o sétimo dia, e o santificou; porque nele descansou de toda a sua obra que criara e fizera.

[[v1-2-4]]

^<<v1-2-4,4>>^ Eis as origens dos céus e da terra, quando foram criados. No dia em que o Senhor Deus fez a terra e os céus

[[v1-2-5]]

^<<v1-2-5,5>>^ não havia ainda nenhuma planta do campo na terra, pois nenhuma erva do campo tinha ainda brotado; porque o Senhor Deus não tinha feito chover sobre a terra, nem havia homem para lavrar a terra.

[[v1-2-6]]

^<<v1-2-6,6>>^ Um vapor, porém, subia da terra, e regava toda a face da terra.

[[v1-2-7]]

^<<v1-2-7,7>>^ E formou o Senhor Deus o homem do pó da terra, e soprou-lhe nas narinas o fôlego da vida; e o homem tornou-se alma vivente.

[[v1-2-8]]

^<<v1-2-8,8>>^ Então plantou o Senhor Deus um jardim, da banda do oriente, no Éden; e pôs ali o homem que tinha formado.

[[v1-2-9]]

^<<v1-2-9,9>>^ E o Senhor Deus fez brotar da terra toda qualidade de árvores agradáveis à vista e boas para comida, bem como a árvore da vida no meio do jardim, e a árvore do conhecimento do bem e do mal.

[[v1-2-10]]

^<<v1-2-10,10>>^ E saía um rio do Éden para regar o jardim; e dali se dividia e se tornava em quatro braços.

[[v1-2-11]]

^<<v1-2-11,11>>^ O nome do primeiro é Pisom: este é o que rodeia toda a terra de Havilá, onde há ouro;

[[v1-2-12]]

^<<v1-2-12,12>>^ e o ouro dessa terra é bom: ali há o bdélio, e a pedra de berilo.

[[v1-2-13]]

^<<v1-2-13,13>>^ O nome do segundo rio é Giom: este é o que rodeia toda a terra de Cuche.

[[v1-2-14]]

^<<v1-2-14,14>>^ O nome do terceiro rio é Tigre: este é o que corre pelo oriente da Assíria. E o quarto rio é o Eufrates.

[[v1-2-15]]

^<<v1-2-15,15>>^ Tomou, pois, o Senhor Deus o homem, e o pôs no jardim do Édem para o lavrar e guardar.

[[v1-2-16]]

^<<v1-2-16,16>>^ Ordenou o Senhor Deus ao homem, dizendo: De toda árvore do jardim podes comer livremente;

[[v1-2-17]]

^<<v1-2-17,17>>^ mas da árvore do conhecimento do bem e do mal, dessa não comerás; porque no dia em que dela comeres, certamente morrerás.

[[v1-2-18]]

^<<v1-2-18,18>>^ Disse mais o Senhor Deus: Não é bom que o homem esteja só; far-lhe-ei uma ajudadora que lhe seja idônea.

[[v1-2-19]]

^<<v1-2-19,19>>^ Da terra formou, pois, o Senhor Deus todos os animais o campo e todas as aves do céu, e os trouxe ao homem, para ver como lhes chamaria; e tudo o que o homem chamou a todo ser vivente, isso foi o seu nome.

[[v1-2-20]]

^<<v1-2-20,20>>^ Assim o homem deu nomes a todos os animais domésticos, às aves do céu e a todos os animais do campo; mas para o homem não se achava ajudadora idônea.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então o Senhor Deus fez cair um sono pesado sobre o homem, e este adormeceu; tomou-lhe, então, uma das costelas, e fechou a carne em seu lugar;

[[v1-2-22]]

^<<v1-2-22,22>>^ e da costela que o senhor Deus lhe tomara, formou a mulher e a trouxe ao homem.

[[v1-2-23]]

^<<v1-2-23,23>>^ Então disse o homem: Esta é agora osso dos meus ossos, e carne da minha carne; ela será chamada varoa, porquanto do varão foi tomada.

[[v1-2-24]]

^<<v1-2-24,24>>^ Portanto deixará o homem a seu pai e a sua mãe, e unir-se-á à sua mulher, e serão uma só carne.

[[v1-2-25]]

^<<v1-2-25,25>>^ E ambos estavam nus, o homem e sua mulher; e não se envergonhavam.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]