include::./index.adoc[]

[[v1-7-0]]
=== Gênesis, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-7-1]]

^<<v1-7-1,1>>^ Depois disse o Senhor a Noé: Entra na arca, tu e toda a tua casa, porque tenho visto que és justo diante de mim nesta geração.

[[v1-7-2]]

^<<v1-7-2,2>>^ De todos os animais limpos levarás contigo sete e sete, o macho e sua fêmea; mas dos animais que não são limpos, dois, o macho e sua fêmea;

[[v1-7-3]]

^<<v1-7-3,3>>^ também das aves do céu sete e sete, macho e fêmea, para se conservar em vida sua espécie sobre a face de toda a terra.

[[v1-7-4]]

^<<v1-7-4,4>>^ Porque, passados ainda sete dias, farei chover sobre a terra quarenta dias e quarenta noites, e exterminarei da face da terra todas as criaturas que fiz.

[[v1-7-5]]

^<<v1-7-5,5>>^ E Noé fez segundo tudo o que o Senhor lhe ordenara.

[[v1-7-6]]

^<<v1-7-6,6>>^ Tinha Noé seiscentos anos de idade, quando o dilúvio veio sobre a terra.

[[v1-7-7]]

^<<v1-7-7,7>>^ Noé entrou na arca com seus filhos, sua mulher e as mulheres de seus filhos, por causa das águas do dilúvio.

[[v1-7-8]]

^<<v1-7-8,8>>^ Dos animais limpos e dos que não são limpos, das aves, e de todo réptil sobre a terra,

[[v1-7-9]]

^<<v1-7-9,9>>^ entraram dois a dois para junto de Noé na arca, macho e fêmea, como Deus ordenara a Noé.

[[v1-7-10]]

^<<v1-7-10,10>>^ Passados os sete dias, vieram sobre a terra as águas do dilúvio.

[[v1-7-11]]

^<<v1-7-11,11>>^ No ano seiscentos da vida de Noé, no mês segundo, aos dezessete dias do mês, romperam-se todas as fontes do grande abismo, e as janelas do céu se abriram,

[[v1-7-12]]

^<<v1-7-12,12>>^ e caiu chuva sobre a terra quarenta dias e quarenta noites.

[[v1-7-13]]

^<<v1-7-13,13>>^ Nesse mesmo dia entrou Noé na arca, e juntamente com ele seus filhos Sem, Cam e Jafé, como também sua mulher e as três mulheres de seus filhos,

[[v1-7-14]]

^<<v1-7-14,14>>^ e com eles todo animal segundo a sua espécie, todo o gado segundo a sua espécie, todo réptil que se arrasta sobre a terra segundo a sua espécie e toda ave segundo a sua espécie, pássaros de toda qualidade.

[[v1-7-15]]

^<<v1-7-15,15>>^ Entraram para junto de Noé na arca, dois a dois de toda a carne em que havia espírito de vida.

[[v1-7-16]]

^<<v1-7-16,16>>^ E os que entraram eram macho e fêmea de toda a carne, como Deus lhe tinha ordenado; e o Senhor o fechou dentro.

[[v1-7-17]]

^<<v1-7-17,17>>^ Veio o dilúvio sobre a terra durante quarenta dias; e as águas cresceram e levantaram a arca, e ela se elevou por cima da terra.

[[v1-7-18]]

^<<v1-7-18,18>>^ Prevaleceram as águas e cresceram grandemente sobre a terra; e a arca vagava sobre as águas.

[[v1-7-19]]

^<<v1-7-19,19>>^ As águas prevaleceram excessivamente sobre a terra; e todos os altos montes que havia debaixo do céu foram cobertos.

[[v1-7-20]]

^<<v1-7-20,20>>^ Quinze côvados acima deles prevaleceram as águas; e assim foram cobertos.

[[v1-7-21]]

^<<v1-7-21,21>>^ Pereceu toda a carne que se movia sobre a terra, tanto ave como gado, animais selvagens, todo réptil que se arrasta sobre a terra, e todo homem.

[[v1-7-22]]

^<<v1-7-22,22>>^ Tudo o que tinha fôlego do espírito de vida em suas narinas, tudo o que havia na terra seca, morreu.

[[v1-7-23]]

^<<v1-7-23,23>>^ Assim foram exterminadas todas as criaturas que havia sobre a face da terra, tanto o homem como o gado, o réptil, e as aves do céu; todos foram exterminados da terra; ficou somente Noé, e os que com ele estavam na arca.

[[v1-7-24]]

^<<v1-7-24,24>>^ E prevaleceram as águas sobre a terra cento e cinqüenta dias.

'''

xref:001-genesis/001-genesis-006.adoc#v1-6-0[&#60; Capítulo Anterior] | <<v1-7-0,Topo>> | xref:001-genesis/001-genesis-008.adoc#v1-8-0[Próximo Capítulo &#62;]