include::./index.adoc[]

[[v1-30-0]]
=== Gênesis, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-30-1]]

^<<v1-30-1,1>>^ Vendo Raquel que não dava filhos a Jacó, teve inveja de sua irmã, e disse a Jacó: Dá-me filhos, senão eu morro.

[[v1-30-2]]

^<<v1-30-2,2>>^ Então se acendeu a ira de Jacó contra Raquel; e disse: Porventura estou eu no lugar de Deus que te impediu o fruto do ventre?

[[v1-30-3]]

^<<v1-30-3,3>>^ Respondeu ela: Eis aqui minha serva Bila; recebe-a por mulher, para que ela dê à luz sobre os meus joelhos, e eu deste modo tenha filhos por ela.

[[v1-30-4]]

^<<v1-30-4,4>>^ Assim lhe deu a Bila, sua serva, por mulher; e Jacó a conheceu.

[[v1-30-5]]

^<<v1-30-5,5>>^ Bila concebeu e deu à luz um filho a Jacó.

[[v1-30-6]]

^<<v1-30-6,6>>^ Então disse Raquel: Julgou-me Deus; ouviu a minha voz e me deu um filho; pelo que lhe chamou Dã.

[[v1-30-7]]

^<<v1-30-7,7>>^ E Bila, serva de Raquel, concebeu outra vez e deu à luz um segundo filho a Jacó.

[[v1-30-8]]

^<<v1-30-8,8>>^ Então disse Raquel: Com grandes lutas tenho lutado com minha irmã, e tenho vencido; e chamou-lhe Naftali.

[[v1-30-9]]

^<<v1-30-9,9>>^ Também Léia, vendo que cessara de ter filhos, tomou a Zilpa, sua serva, e a deu a Jacó por mulher.

[[v1-30-10]]

^<<v1-30-10,10>>^ E Zilpa, serva de Léia, deu à luz um filho a Jacó.

[[v1-30-11]]

^<<v1-30-11,11>>^ Então disse Léia: Afortunada! e chamou-lhe Gade.

[[v1-30-12]]

^<<v1-30-12,12>>^ Depois Zilpa, serva de Léia, deu à luz um segundo filho a Jacó.

[[v1-30-13]]

^<<v1-30-13,13>>^ Então disse Léia: Feliz sou eu! porque as filhas me chamarão feliz; e chamou-lhe Aser.

[[v1-30-14]]

^<<v1-30-14,14>>^ Ora, saiu Rúben nos dias da ceifa do trigo e achou mandrágoras no campo, e as trouxe a Léia, sua mãe. Então disse Raquel a Léia: Dá-me, peço, das mandrágoras de teu filho.

[[v1-30-15]]

^<<v1-30-15,15>>^ Ao que lhe respondeu Léia: É já pouco que me hajas tirado meu marido? queres tirar também as mandrágoras de meu filho? Prosseguiu Raquel: Por isso ele se deitará contigo esta noite pelas mandrágoras de teu filho.

[[v1-30-16]]

^<<v1-30-16,16>>^ Quando, pois, Jacó veio à tarde do campo, saiu-lhe Léia ao encontro e disse: Hás de estar comigo, porque certamente te aluguei pelas mandrágoras de meu filho. E com ela deitou-se Jacó aquela noite.

[[v1-30-17]]

^<<v1-30-17,17>>^ E ouviu Deus a Léia, e ela concebeu e deu a Jacó um quinto filho.

[[v1-30-18]]

^<<v1-30-18,18>>^ Então disse Léia: Deus me tem dado o meu galardão, porquanto dei minha serva a meu marido. E chamou ao filho Issacar.

[[v1-30-19]]

^<<v1-30-19,19>>^ Concebendo Léia outra vez, deu a Jacó um sexto filho;

[[v1-30-20]]

^<<v1-30-20,20>>^ e disse: Deus me deu um excelente dote; agora morará comigo meu marido, porque lhe tenho dado seis filhos. E chamou-lhe Zebulom.

[[v1-30-21]]

^<<v1-30-21,21>>^ Depois. disto deu à luz uma filha, e chamou-lhe Diná.

[[v1-30-22]]

^<<v1-30-22,22>>^ Também lembrou-se Deus de Raquel, ouviu-a e a tornou fecunda.

[[v1-30-23]]

^<<v1-30-23,23>>^ De modo que ela concebeu e deu à luz um filho, e disse: Tirou-me Deus o opróbrio.

[[v1-30-24]]

^<<v1-30-24,24>>^ E chamou-lhe José, dizendo: Acrescente-me o Senhor ainda outro filho.

[[v1-30-25]]

^<<v1-30-25,25>>^ Depois que Raquel deu à luz a José, disse Jacó a Labão: Despede-me a fim de que eu vá para meu lugar e para minha terra.

[[v1-30-26]]

^<<v1-30-26,26>>^ Dá-me as minhas mulheres, e os meus filhos, pelas quais te tenho servido, e deixa-me ir; pois tu sabes o serviço que te prestei.

[[v1-30-27]]

^<<v1-30-27,27>>^ Labão lhe respondeu: Se tenho achado graça aos teus olhos, fica comigo; pois tenho percebido que o Senhor me abençoou por amor de ti.

[[v1-30-28]]

^<<v1-30-28,28>>^ E disse mais: Determina-me o teu salário, que to darei.

[[v1-30-29]]

^<<v1-30-29,29>>^ Ao que lhe respondeu Jacó: Tu sabes como te hei servido, e como tem passado o teu gado comigo.

[[v1-30-30]]

^<<v1-30-30,30>>^ Porque o pouco que tinhas antes da minha vinda tem se multiplicado abundantemente; e o Senhor te tem abençoado por onde quer que eu fui. Agora, pois, quando hei de trabalhar também por minha casa?

[[v1-30-31]]

^<<v1-30-31,31>>^ Insistiu Labão: Que te darei? Então respondeu Jacó: Não me darás nada; tornarei a apascentar e a guardar o teu rebanho se me fizeres isto:

[[v1-30-32]]

^<<v1-30-32,32>>^ Passarei hoje por todo o teu rebanho, separando dele todos os salpicados e malhados, e todos os escuros entre as ovelhas, e os malhados e salpicados entre as cabras; e isto será o meu salário.

[[v1-30-33]]

^<<v1-30-33,33>>^ De modo que responderá por mim a minha justiça no dia de amanhã, quando vieres ver o meu salário assim exposto diante de ti: tudo o que não for salpicado e malhado entre as cabras e escuro entre as ovelhas, esse, se for achado comigo, será tido por furtado.

[[v1-30-34]]

^<<v1-30-34,34>>^ Concordou Labão, dizendo: Seja conforme a tua palavra.

[[v1-30-35]]

^<<v1-30-35,35>>^ E separou naquele mesmo dia os bodes listrados e malhados e todas as cabras salpicadas e malhadas, tudo em que havia algum branco, e todos os escuros entre os cordeiros e os deu nas mãos de seus filhos;

[[v1-30-36]]

^<<v1-30-36,36>>^ e pôs três dias de caminho entre si e Jacó; e Jacó apascentava o restante dos rebanhos de Labão.

[[v1-30-37]]

^<<v1-30-37,37>>^ Então tomou Jacó varas verdes de estoraque, de amendoeira e de plátano e, descascando nelas riscas brancas, descobriu o branco que nelas havia;

[[v1-30-38]]

^<<v1-30-38,38>>^ e as varas que descascara pôs em frente dos rebanhos, nos cochos, isto é, nos bebedouros, onde os rebanhos bebiam; e conceberam quando vinham beber.

[[v1-30-39]]

^<<v1-30-39,39>>^ Os rebanhos concebiam diante das varas, e as ovelhas davam crias listradas, salpicadas e malhadas.

[[v1-30-40]]

^<<v1-30-40,40>>^ Então separou Jacó os cordeiros, e fez os rebanhos olhar para os listrados e para todos os escuros no rebanho de Labão; e pôs seu rebanho à parte, e não pôs com o rebanho de Labão.

[[v1-30-41]]

^<<v1-30-41,41>>^ e todas as vezes que concebiam as ovelhas fortes, punha Jacó as varas nos bebedouros, diante dos olhos do rebanho, para que concebessem diante das varas;

[[v1-30-42]]

^<<v1-30-42,42>>^ mas quando era fraco o rebanho, ele não as punha. Assim as fracas eram de Labão, e as fortes de Jacó.

[[v1-30-43]]

^<<v1-30-43,43>>^ E o homem se enriqueceu sobremaneira, e teve grandes rebanhos, servas e servos, camelos e jumentos.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]