include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-43-1]]

^<<v1-43-1,1>>^ Ora, a fome era gravíssima na terra.

[[v1-43-2]]

^<<v1-43-2,2>>^ Tendo eles acabado de comer o mantimento que trouxeram do Egito, disse-lhes seu pai: voltai, comprai-nos um pouco de alimento.

[[v1-43-3]]

^<<v1-43-3,3>>^ Mas respondeu-lhe Judá: Expressamente nos advertiu o homem, dizendo: Não vereis a minha face, se vosso irmão não estiver convosco.

[[v1-43-4]]

^<<v1-43-4,4>>^ Se queres enviar conosco o nosso irmão, desceremos e te compraremos alimento;

[[v1-43-5]]

^<<v1-43-5,5>>^ mas se não queres enviá-lo, não desceremos, porquanto o homem nos disse: Não vereis a minha face, se vosso irmão não estiver convosco.

[[v1-43-6]]

^<<v1-43-6,6>>^ Perguntou Israel: Por que me fizeste este mal, fazendo saber ao homem que tínheis ainda outro irmão?

[[v1-43-7]]

^<<v1-43-7,7>>^ Responderam eles: O homem perguntou particularmente por nós, e pela nossa parentela, dizendo: vive ainda vosso pai? tendes mais um irmão? e respondemos-lhe segundo o teor destas palavras. Podíamos acaso saber que ele diria: Trazei vosso irmão?

[[v1-43-8]]

^<<v1-43-8,8>>^ Então disse Judá a Israel, seu pai: Envia o mancebo comigo, e levantar-nos-emos e iremos, para que vivamos e não morramos, nem nós, nem tu, nem nossos filhinhos.

[[v1-43-9]]

^<<v1-43-9,9>>^ Eu serei fiador por ele; da minha mão o requererás. Se eu to não trouxer, e o não puser diante de ti, serei réu de crime para contigo para sempre.

[[v1-43-10]]

^<<v1-43-10,10>>^ E se não nos tivéssemos demorado, certamente já segunda vez estaríamos de volta.

[[v1-43-11]]

^<<v1-43-11,11>>^ Então disse-lhes Israel seu pai: Se é sim, fazei isto: tomai os melhores produtos da terra nas vossas vasilhas, e levai ao homem um presente: um pouco de bálsamo e um pouco de mel, tragacanto e mirra, nozes de fístico e amêndoas;

[[v1-43-12]]

^<<v1-43-12,12>>^ levai em vossas mãos dinheiro em dobro; e o dinheiro que foi devolvido na boca dos vossos sacos, tornai a levá-lo em vossas mãos; bem pode ser que fosse engano.

[[v1-43-13]]

^<<v1-43-13,13>>^ Levai também vosso irmão; levantai-vos e voltai ao homem;

[[v1-43-14]]

^<<v1-43-14,14>>^ e Deus Todo-Poderoso vos dê misericórdia diante do homem, para que ele deixe vir convosco vosso outro irmão, e Benjamim; e eu, se for desfilhado, desfilhado ficarei.

[[v1-43-15]]

^<<v1-43-15,15>>^ Tomaram, pois, os homens aquele presente, e dinheiro em dobro nas mãos, e a Benjamim; e, levantando-se desceram ao Egito e apresentaram-se diante de José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Quando José viu Benjamim com eles, disse ao despenseiro de sua casa: Leva os homens à casa, mata reses, e apronta tudo; pois eles comerão comigo ao meio-dia.

[[v1-43-17]]

^<<v1-43-17,17>>^ E o homem fez como José ordenara, e levou-os à casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Então os homens tiveram medo, por terem sido levados à casa de José; e diziam: por causa do dinheiro que da outra vez foi devolvido nos nossos sacos que somos trazidos aqui, para nos criminar e cair sobre nós, para que nos tome por servos, tanto a nós como a nossos jumentos.

[[v1-43-19]]

^<<v1-43-19,19>>^ Por isso eles se chegaram ao despenseiro da casa de José, e falaram com ele à porta da casa,

[[v1-43-20]]

^<<v1-43-20,20>>^ e disseram: Ai! senhor meu, na verdade descemos dantes a comprar mantimento;

[[v1-43-21]]

^<<v1-43-21,21>>^ e quando chegamos à estalagem, abrimos os nossos sacos, e eis que o dinheiro de cada um estava na boca do seu saco, nosso dinheiro por seu peso; e tornamos a trazê-lo em nossas mãos;

[[v1-43-22]]

^<<v1-43-22,22>>^ também trouxemos outro dinheiro em nossas mãos, para comprar mantimento; não sabemos quem tenha posto o dinheiro em nossos sacos.

[[v1-43-23]]

^<<v1-43-23,23>>^ Respondeu ele: Paz seja convosco, não temais; o vosso Deus, e o Deus de vosso pai, deu-vos um tesouro nos vossos sacos; o vosso dinheiro chegou-me às mãos. E trouxe-lhes fora Simeão.

[[v1-43-24]]

^<<v1-43-24,24>>^ Depois levou os homens à casa de José, e deu-lhes água, e eles lavaram os pés; também deu forragem aos seus jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ Então eles prepararam o presente para quando José viesse ao meio-dia; porque tinham ouvido que ali haviam de comer.

[[v1-43-26]]

^<<v1-43-26,26>>^ Quando José chegou em casa, trouxeram-lhe ali o presente que guardavam junto de si; e inclinaram-se a ele até a terra.

[[v1-43-27]]

^<<v1-43-27,27>>^ Então ele lhes perguntou como estavam; e prosseguiu: vosso pai, o ancião de quem falastes, está bem? ainda vive?

[[v1-43-28]]

^<<v1-43-28,28>>^ Responderam eles: O teu servo, nosso pai, está bem; ele ainda vive. E abaixaram a cabeça, e inclinaram-se.

[[v1-43-29]]

^<<v1-43-29,29>>^ Levantando os olhos, José viu a Benjamim, seu irmão, filho de sua mãe, e perguntou: É este o vosso irmão mais novo de quem me falastes? E disse: Deus seja benévolo para contigo, meu filho.

[[v1-43-30]]

^<<v1-43-30,30>>^ E José apressou-se, porque se lhe comoveram as entranhas por causa de seu irmão, e procurou onde chorar; e, entrando na sua câmara, chorou ali.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois lavou o rosto, e saiu; e se conteve e disse: Servi a comida.

[[v1-43-32]]

^<<v1-43-32,32>>^ Serviram-lhe, pois, a ele à parte, e a eles também à parte, e à parte aos egípcios que comiam com ele; porque os egípcios não podiam comer com os hebreus, porquanto é isso abominação aos egípcios.

[[v1-43-33]]

^<<v1-43-33,33>>^ Sentaram-se diante dele, o primogênito segundo a sua primogenitura, e o menor segundo a sua menoridade; do que os homens se maravilhavam entre si.

[[v1-43-34]]

^<<v1-43-34,34>>^ Então ele lhes apresentou as porções que estavam diante dele; mas a porção de Benjamim era cinco vezes maior do que a de qualquer deles. E eles beberam, e se regalaram com ele.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]