include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-44-1]]

^<<v1-44-1,1>>^ Depois José deu ordem ao despenseiro de sua casa, dizendo: Enche de mantimento os sacos dos homens, quanto puderem levar, e põe o dinheiro de cada um na boca do seu saco.

[[v1-44-2]]

^<<v1-44-2,2>>^ E a minha taça de prata porás na boca do saco do mais novo, com o dinheiro do seu trigo. Assim fez ele conforme a palavra que José havia dito.

[[v1-44-3]]

^<<v1-44-3,3>>^ Logo que veio a luz da manhã, foram despedidos os homens, eles com os seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Havendo eles saído da cidade, mas não se tendo distanciado muito, disse José ao seu despenseiro: Levanta-te e segue os homens; e, alcançando-os, dize-lhes: Por que tornastes o mal pelo bem?

[[v1-44-5]]

^<<v1-44-5,5>>^ Não é esta a taça por que bebe meu senhor, e de que se serve para adivinhar? Fizestes mal no que fizestes.

[[v1-44-6]]

^<<v1-44-6,6>>^ Então ele, tendo-os alcançado, lhes falou essas mesmas palavras.

[[v1-44-7]]

^<<v1-44-7,7>>^ Responderam-lhe eles: Por que falo meu senhor tais palavras? Longe estejam teus servos de fazerem semelhante coisa.

[[v1-44-8]]

^<<v1-44-8,8>>^ Eis que o dinheiro, que achamos nas bocas dos nossos sacos, to tornamos a trazer desde a terra de Canaã; como, pois, furtaríamos da casa do teu senhor prata ou ouro?

[[v1-44-9]]

^<<v1-44-9,9>>^ Aquele dos teus servos com quem a taça for encontrada, morra; e ainda nós seremos escravos do meu senhor.

[[v1-44-10]]

^<<v1-44-10,10>>^ Ao que disse ele: Seja conforme as vossas palavras; aquele com quem a taça for encontrada será meu escravo; mas vós sereis inocentes.

[[v1-44-11]]

^<<v1-44-11,11>>^ Então eles se apressaram cada um a pôr em terra o seu saco, e cada um a abri-lo.

[[v1-44-12]]

^<<v1-44-12,12>>^ E o despenseiro buscou, começando pelo maior, e acabando pelo mais novo; e achou-se a taça no saco de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Então rasgaram os seus vestidos e, tendo cada um carregado o seu jumento, voltaram à cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ E veio Judá com seus irmãos à casa de José, pois ele ainda estava ali; e prostraram-se em terra diante dele.

[[v1-44-15]]

^<<v1-44-15,15>>^ Logo lhes perguntou José: Que ação é esta que praticastes? não sabeis vós que um homem como eu pode, muito bem, adivinhar?

[[v1-44-16]]

^<<v1-44-16,16>>^ Respondeu Judá: Que diremos a meu senhor? que falaremos? e como nos justificaremos? Descobriu Deus a iniqüidade de teus servos; eis que somos escravos de meu senhor, tanto nós como aquele em cuja mão foi achada a taça.

[[v1-44-17]]

^<<v1-44-17,17>>^ Disse José: Longe esteja eu de fazer isto; o homem em cuja mão a taça foi achada, aquele será meu servo; porém, quanto a vós, subi em paz para vosso pai.

[[v1-44-18]]

^<<v1-44-18,18>>^ Então Judá se chegou a ele, e disse: Ai! senhor meu, deixa, peço-te, o teu servo dizer uma palavra aos ouvidos de meu senhor; e não se acenda a tua ira contra o teu servo; porque tu és como Faraó.

[[v1-44-19]]

^<<v1-44-19,19>>^ Meu senhor perguntou a seus servos, dizendo: Tendes vós pai, ou irmão?

[[v1-44-20]]

^<<v1-44-20,20>>^ E respondemos a meu senhor: Temos pai, já velho, e há um filho da sua velhice, um menino pequeno; o irmão deste é morto, e ele ficou o único de sua mãe; e seu pai o ama.

[[v1-44-21]]

^<<v1-44-21,21>>^ Então tu disseste a teus servos: Trazei-mo, para que eu ponha os olhos sobre ele.

[[v1-44-22]]

^<<v1-44-22,22>>^ E quando respondemos a meu senhor: O menino não pode deixar o seu pai; pois se ele deixasse o seu pai, este morreria;

[[v1-44-23]]

^<<v1-44-23,23>>^ replicaste a teus servos: A menos que desça convosco vosso irmão mais novo, nunca mais vereis a minha face.

[[v1-44-24]]

^<<v1-44-24,24>>^ Então subimos a teu servo, meu pai, e lhe contamos as palavras de meu senhor.

[[v1-44-25]]

^<<v1-44-25,25>>^ Depois disse nosso pai: Tornai, comprai-nos um pouco de mantimento;

[[v1-44-26]]

^<<v1-44-26,26>>^ e lhe respondemos: Não podemos descer; mas, se nosso irmão menor for conosco, desceremos; pois não podemos ver a face do homem, se nosso irmão menor não estiver conosco.

[[v1-44-27]]

^<<v1-44-27,27>>^ Então nos disse teu servo, meu pai: Vós sabeis que minha mulher me deu dois filhos;

[[v1-44-28]]

^<<v1-44-28,28>>^ um saiu de minha casa e eu disse: certamente foi despedaçado, e não o tenho visto mais;

[[v1-44-29]]

^<<v1-44-29,29>>^ se também me tirardes a este, e lhe acontecer algum desastre, fareis descer as minhas cãs com tristeza ao Seol.

[[v1-44-30]]

^<<v1-44-30,30>>^ Agora, pois, se eu for ter com o teu servo, meu pai, e o menino não estiver conosco, como a sua alma está ligada com a alma dele,

[[v1-44-31]]

^<<v1-44-31,31>>^ acontecerá que, vendo ele que o menino ali não está, morrerá; e teus servos farão descer as cãs de teu servo, nosso pai com tristeza ao Seol.

[[v1-44-32]]

^<<v1-44-32,32>>^ Porque teu servo se deu como fiador pelo menino para com meu pai, dizendo: Se eu to não trouxer de volta, serei culpado, para com meu pai para sempre.

[[v1-44-33]]

^<<v1-44-33,33>>^ Agora, pois, fique teu servo em lugar do menino como escravo de meu senhor, e que suba o menino com seus irmãos.

[[v1-44-34]]

^<<v1-44-34,34>>^ Porque, como subirei eu a meu pai, se o menino não for comigo? para que não veja eu o mal que sobrevirá a meu pai.

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]