include::./index.adoc[]

[[v1-20-0]]
=== Gênesis, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-20-1]]

^<<v1-20-1,1>>^ Partiu Abraão dali para a terra do Negebe, e habitou entre Cades e Sur; e peregrinou em Gerar.

[[v1-20-2]]

^<<v1-20-2,2>>^ E havendo Abraão dito de Sara, sua mulher: É minha irmã; enviou Abimeleque, rei de Gerar, e tomou a Sara.

[[v1-20-3]]

^<<v1-20-3,3>>^ Deus, porém, veio a Abimeleque, em sonhos, de noite, e disse-lhe: Eis que estás para morrer por causa da mulher que tomaste; porque ela tem marido.

[[v1-20-4]]

^<<v1-20-4,4>>^ Ora, Abimeleque ainda não se havia chegado a ela: perguntou, pois: Senhor matarás porventura também uma nação justa?

[[v1-20-5]]

^<<v1-20-5,5>>^ Não me disse ele mesmo: É minha irmã? e ela mesma me disse: Ele é meu irmão; na sinceridade do meu coração e na inocência das minhas mãos fiz isto.

[[v1-20-6]]

^<<v1-20-6,6>>^ Ao que Deus lhe respondeu em sonhos: Bem sei eu que na sinceridade do teu coração fizeste isto; e também eu te tenho impedido de pecar contra mim; por isso não te permiti tocá-la;

[[v1-20-7]]

^<<v1-20-7,7>>^ agora, pois, restitui a mulher a seu marido, porque ele é profeta, e intercederá por ti, e viverás; se, porém, não lha restituíres, sabe que certamente morrerás, tu e tudo o que é teu.

[[v1-20-8]]

^<<v1-20-8,8>>^ Levantou-se Abimeleque de manhã cedo e, chamando a todos os seus servos, falou-lhes aos ouvidos todas estas palavras; e os homens temeram muito.

[[v1-20-9]]

^<<v1-20-9,9>>^ Então chamou Abimeleque a Abraão e lhe perguntou: Que é que nos fizeste? e em que pequei contra ti, para trazeres sobre mim o sobre o meu reino tamanho pecado? Tu me fizeste o que não se deve fazer.

[[v1-20-10]]

^<<v1-20-10,10>>^ Perguntou mais Abimeleque a Abraão: Com que intenção fizeste isto?

[[v1-20-11]]

^<<v1-20-11,11>>^ Respondeu Abraão: Porque pensei: Certamente não há temor de Deus neste lugar; matar-me-ão por causa da minha mulher.

[[v1-20-12]]

^<<v1-20-12,12>>^ Além disso ela é realmente minha irmã, filha de meu pai, ainda que não de minha mãe; e veio a ser minha mulher.

[[v1-20-13]]

^<<v1-20-13,13>>^ Quando Deus me fez sair errante da casa de meu pai, eu lhe disse a ela: Esta é a graça que me farás: em todo lugar aonde formos, dize de mim: Ele é meu irmão.

[[v1-20-14]]

^<<v1-20-14,14>>^ Então tomou Abimeleque ovelhas e bois, e servos e servas, e os deu a Abraão; e lhe restituiu Sara, sua mulher;

[[v1-20-15]]

^<<v1-20-15,15>>^ e disse-lhe Abimeleque: Eis que a minha terra está diante de ti; habita onde bem te parecer.

[[v1-20-16]]

^<<v1-20-16,16>>^ E a Sara disse: Eis que tenho dado a teu irmão mil moedas de prata; isso te seja por véu dos olhos a todos os que estão contigo; e perante todos estás reabilitada.

[[v1-20-17]]

^<<v1-20-17,17>>^ Orou Abraão a Deus, e Deus sarou Abimeleque, e a sua mulher e as suas servas; de maneira que tiveram filhos;

[[v1-20-18]]

^<<v1-20-18,18>>^ porque o Senhor havia fechado totalmente todas as madres da casa de Abimeleque, por causa de Sara, mulher de Abraão.

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]