include::./index.adoc[]

[[v1-21-0]]
=== Gênesis, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-21-1]]

^<<v1-21-1,1>>^ O Senhor visitou a Sara, como tinha dito, e lhe fez como havia prometido.

[[v1-21-2]]

^<<v1-21-2,2>>^ Sara concebeu, e deu a Abraão um filho na sua velhice, ao tempo determinado, de que Deus lhe falara;

[[v1-21-3]]

^<<v1-21-3,3>>^ e, Abraão pôs no filho que lhe nascera, que Sara lhe dera, o nome de Isaque.

[[v1-21-4]]

^<<v1-21-4,4>>^ E Abraão circuncidou a seu filho Isaque, quando tinha oito dias, conforme Deus lhe ordenara.

[[v1-21-5]]

^<<v1-21-5,5>>^ Ora, Abraão tinha cem anos, quando lhe nasceu Isaque, seu filho.

[[v1-21-6]]

^<<v1-21-6,6>>^ Pelo que disse Sara: Deus preparou riso para mim; todo aquele que o ouvir, se rirá comigo.

[[v1-21-7]]

^<<v1-21-7,7>>^ E acrescentou: Quem diria a Abraão que Sara havia de amamentar filhos? no entanto lhe dei um filho na sua velhice.

[[v1-21-8]]

^<<v1-21-8,8>>^ cresceu o menino, e foi desmamado; e Abraão fez um grande banquete no dia em que Isaque foi desmamado.

[[v1-21-9]]

^<<v1-21-9,9>>^ Ora, Sara viu brincando o filho de Agar a egípcia, que esta dera à luz a Abraão.

[[v1-21-10]]

^<<v1-21-10,10>>^ Pelo que disse a Abraão: Deita fora esta serva e o seu filho; porque o filho desta serva não será herdeiro com meu filho, com Isaque.

[[v1-21-11]]

^<<v1-21-11,11>>^ Pareceu isto bem duro aos olhos de Abraão, por causa de seu filho.

[[v1-21-12]]

^<<v1-21-12,12>>^ Deus, porém, disse a Abraão: Não pareça isso duro aos teus olhos por causa do moço e por causa da tua serva; em tudo o que Sara te diz, ouve a sua voz; porque em Isaque será chamada a tua descendência.

[[v1-21-13]]

^<<v1-21-13,13>>^ Mas também do filho desta serva farei uma nação, porquanto ele é da tua linhagem.

[[v1-21-14]]

^<<v1-21-14,14>>^ Então se levantou Abraão de manhã cedo e, tomando pão e um odre de água, os deu a Agar, pondo-os sobre o ombro dela; também lhe deu o menino e despediu-a; e ela partiu e foi andando errante pelo deserto de Beer-Seba.

[[v1-21-15]]

^<<v1-21-15,15>>^ E consumida a água do odre, Agar deitou o menino debaixo de um dos arbustos,

[[v1-21-16]]

^<<v1-21-16,16>>^ e foi assentar-se em frente dele, a boa distância, como a de um tiro de arco; porque dizia: Que não veja eu morrer o menino. Assim sentada em frente dele, levantou a sua voz e chorou.

[[v1-21-17]]

^<<v1-21-17,17>>^ Mas Deus ouviu a voz do menino; e o anjo de Deus, bradando a Agar desde o céu, disse-lhe: Que tens, Agar? não temas, porque Deus ouviu a voz do menino desde o lugar onde está.

[[v1-21-18]]

^<<v1-21-18,18>>^ Ergue-te, levanta o menino e toma-o pela mão, porque dele farei uma grande nação.

[[v1-21-19]]

^<<v1-21-19,19>>^ E abriu-lhe Deus os olhos, e ela viu um poço; e foi encher de água o odre e deu de beber ao menino.

[[v1-21-20]]

^<<v1-21-20,20>>^ Deus estava com o menino, que cresceu e, morando no deserto, tornou-se flecheiro.

[[v1-21-21]]

^<<v1-21-21,21>>^ Ele habitou no deserto de Parã; e sua mãe tomou-lhe uma mulher da terra do Egito.

[[v1-21-22]]

^<<v1-21-22,22>>^ Naquele mesmo tempo Abimeleque, com Ficol, o chefe do seu exército, falou a Abraão, dizendo: Deus é contigo em tudo o que fazes;

[[v1-21-23]]

^<<v1-21-23,23>>^ agora pois, jura-me aqui por Deus que não te haverás falsamente comigo, nem com meu filho, nem com o filho do meu filho; mas segundo a beneficência que te fiz, me farás a mim, e à terra onde peregrinaste.

[[v1-21-24]]

^<<v1-21-24,24>>^ Respondeu Abraão: Eu jurarei.

[[v1-21-25]]

^<<v1-21-25,25>>^ Abraão, porém, repreendeu a Abimeleque, por causa de um poço de água, que os servos de Abimeleque haviam tomado à força.

[[v1-21-26]]

^<<v1-21-26,26>>^ Respondeu-lhe Abimeleque: Não sei quem fez isso; nem tu mo fizeste saber, nem tampouco ouvi eu falar nisso, senão hoje.

[[v1-21-27]]

^<<v1-21-27,27>>^ Tomou, pois, Abraão ovelhas e bois, e os deu a Abimeleque; assim fizeram entre, si um pacto.

[[v1-21-28]]

^<<v1-21-28,28>>^ Pôs Abraão, porém, à parte sete cordeiras do rebanho.

[[v1-21-29]]

^<<v1-21-29,29>>^ E perguntou Abimeleque a Abraão: Que significam estas sete cordeiras que puseste à parte?

[[v1-21-30]]

^<<v1-21-30,30>>^ Respondeu Abraão: Estas sete cordeiras receberás da minha mão para que me sirvam de testemunho de que eu cavei este poço.

[[v1-21-31]]

^<<v1-21-31,31>>^ Pelo que chamou aquele lugar Beer-Seba, porque ali os dois juraram.

[[v1-21-32]]

^<<v1-21-32,32>>^ Assim fizeram uma pacto em Beer-Seba. Depois se levantaram Abimeleque e Ficol, o chefe do seu exército, e tornaram para a terra dos filisteus.

[[v1-21-33]]

^<<v1-21-33,33>>^ Abraão plantou uma tamargueira em Beer-Seba, e invocou ali o nome do Senhor, o Deus eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E peregrinou Abraão na terra dos filisteus muitos dias.

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]