include::./index.adoc[]

[[v1-12-0]]
=== Gênesis, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-12-1]]

^<<v1-12-1,1>>^ Ora, o Senhor disse a Abrão: Sai-te da tua terra, da tua parentela, e da casa de teu pai, para a terra que eu te mostrarei.

[[v1-12-2]]

^<<v1-12-2,2>>^ Eu farei de ti uma grande nação; abençoar-te-ei, e engrandecerei o teu nome; e tu, sê uma bênção.

[[v1-12-3]]

^<<v1-12-3,3>>^ Abençoarei aos que te abençoarem, e amaldiçoarei àquele que te amaldiçoar; e em ti serão benditas todas as famílias da terra.

[[v1-12-4]]

^<<v1-12-4,4>>^ Partiu, pois Abrão, como o Senhor lhe ordenara, e Ló foi com ele. Tinha Abrão setenta e cinco anos quando saiu de Harã.

[[v1-12-5]]

^<<v1-12-5,5>>^ Abrão levou consigo a Sarai, sua mulher, e a Ló, filho de seu irmão, e todos os bens que haviam adquirido, e as almas que lhes acresceram em Harã; e saíram a fim de irem à terra de Canaã; e à terra de Canaã chegaram.

[[v1-12-6]]

^<<v1-12-6,6>>^ Passou Abrão pela terra até o lugar de Siquém, até o carvalho de Moré. Nesse tempo estavam os cananeus na terra.

[[v1-12-7]]

^<<v1-12-7,7>>^ Apareceu, porém, o Senhor a Abrão, e disse: À tua semente darei esta terra. Abrão, pois, edificou ali um altar ao Senhor, que lhe aparecera.

[[v1-12-8]]

^<<v1-12-8,8>>^ Então passou dali para o monte ao oriente de Betel, e armou a sua tenda, ficando-lhe Betel ao ocidente, e Ai ao oriente; também ali edificou um altar ao Senhor, e invocou o nome do Senhor.

[[v1-12-9]]

^<<v1-12-9,9>>^ Depois continuou Abrão o seu caminho, seguindo ainda para o sul.

[[v1-12-10]]

^<<v1-12-10,10>>^ Ora, havia fome naquela terra; Abrão, pois, desceu ao Egito, para peregrinar ali, porquanto era grande a fome na terra.

[[v1-12-11]]

^<<v1-12-11,11>>^ Quando ele estava prestes a entrar no Egito, disse a Sarai, sua mulher: Ora, bem sei que és mulher formosa à vista;

[[v1-12-12]]

^<<v1-12-12,12>>^ e acontecerá que, quando os egípcios te virem, dirão: Esta é mulher dele. E me matarão a mim, mas a ti te guardarão em vida.

[[v1-12-13]]

^<<v1-12-13,13>>^ Dize, peço-te, que és minha irmã, para que me vá bem por tua causa, e que viva a minha alma em atenção a ti.

[[v1-12-14]]

^<<v1-12-14,14>>^ E aconteceu que, entrando Abrão no Egito, viram os egípcios que a mulher era mui formosa.

[[v1-12-15]]

^<<v1-12-15,15>>^ Até os príncipes de Faraó a viram e gabaram-na diante dele; e foi levada a mulher para a casa de Faraó.

[[v1-12-16]]

^<<v1-12-16,16>>^ E ele tratou bem a Abrão por causa dela; e este veio a ter ovelhas, bois e jumentos, servos e servas, jumentas e camelos.

[[v1-12-17]]

^<<v1-12-17,17>>^ Feriu, porém, o Senhor a Faraó e a sua casa com grandes pragas, por causa de Sarai, mulher de Abrão.

[[v1-12-18]]

^<<v1-12-18,18>>^ Então chamou Faraó a Abrão, e disse: Que é isto que me fizeste? por que não me disseste que ela era tua mulher?

[[v1-12-19]]

^<<v1-12-19,19>>^ Por que disseste: E minha irmã? de maneira que a tomei para ser minha mulher. Agora, pois, eis aqui tua mulher; toma-a e vai-te.

[[v1-12-20]]

^<<v1-12-20,20>>^ E Faraó deu ordens aos seus guardas a respeito dele, os quais o despediram a ele, e a sua mulher, e a tudo o que tinha.

'''

xref:001-genesis/001-genesis-011.adoc#v1-11-0[&#60; Capítulo Anterior] | <<v1-12-0,Topo>> | xref:001-genesis/001-genesis-013.adoc#v1-13-0[Próximo Capítulo &#62;]