include::./index.adoc[]

[[v1-36-0]]
=== Gênesis, 36
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-36-1]]

^<<v1-36-1,1>>^ Estas são as gerações de Esaú &#123;este é Edom&#125;:

[[v1-36-2]]

^<<v1-36-2,2>>^ Esaú tomou dentre as filhas de Canaã suas mulheres: Ada, filha de Elom o heteu, e Aolíbama, filha de Ana, filha de Zibeão o heveu,

[[v1-36-3]]

^<<v1-36-3,3>>^ e Basemate, filha de Ismael, irmã de Nebaiote.

[[v1-36-4]]

^<<v1-36-4,4>>^ Ada teve de Esaú a Elifaz, e Basemate teve a Reuel;

[[v1-36-5]]

^<<v1-36-5,5>>^ e Aolíbama teve a Jeús, Jalão e Corá; estes são os filhos de Esaú, que lhe nasceram na terra de Canaã.

[[v1-36-6]]

^<<v1-36-6,6>>^ Depois Esaú tomou suas mulheres, seus filhos, suas filhas e todas as almas de sua casa, seu gado, todos os seus animais e todos os seus bens, que havia adquirido na terra de Canaã, e foi-se para outra terra, apartando-se de seu irmão Jacó.

[[v1-36-7]]

^<<v1-36-7,7>>^ Porque os seus bens eram abundantes demais para habitarem juntos; e a terra de suas peregrinações não os podia sustentar por causa do seu gado.

[[v1-36-8]]

^<<v1-36-8,8>>^ Portanto Esaú habitou no monte de Seir; Esaú é Edom.

[[v1-36-9]]

^<<v1-36-9,9>>^ Estas, pois, são as gerações de Esaú, pai dos edomeus, no monte de Seir:

[[v1-36-10]]

^<<v1-36-10,10>>^ Estes são os nomes dos filhos de Esaú: Elifaz, filho de Ada, mulher de Esaú; Reuel, filho de Basemate, mulher de Esaú.

[[v1-36-11]]

^<<v1-36-11,11>>^ E os filhos de Elifaz foram: Temã, Omar, Zefô, Gatã e Quenaz.

[[v1-36-12]]

^<<v1-36-12,12>>^ Timna era concubina de Elifaz, filho de Esaú, e teve de Elifaz a Amaleque. São esses os filhos de Ada, mulher de Esaú.

[[v1-36-13]]

^<<v1-36-13,13>>^ Foram estes os filhos de Reuel: Naate e Zerá, Sama e Mizá. Foram esses os filhos de Basemate, mulher de Esaú.

[[v1-36-14]]

^<<v1-36-14,14>>^ Estes foram os filhos de Aolíbama, filha de Ana, filha de Zibeão, mulher de Esaú: ela teve de Esaú Jeús, Jalão e Corá.

[[v1-36-15]]

^<<v1-36-15,15>>^ São estes os chefes dos filhos de Esaú: dos filhos de Elifaz, o primogênito de Esaú, os chefes Temã, Omar, Zefô, Quenaz,

[[v1-36-16]]

^<<v1-36-16,16>>^ Corá, Gatã e Amaleque. São esses os chefes que nasceram a Elifaz na terra de Edom; esses são os filhos de Ada.

[[v1-36-17]]

^<<v1-36-17,17>>^ Estes são os filhos de Reuel, filho de Esaú: os chefes Naate, Zerá, Sama e Mizá; esses são os chefes que nasceram a Reuel na terra de Edom; esses são os filhos de Basemate, mulher de Esaú.

[[v1-36-18]]

^<<v1-36-18,18>>^ Estes são os filhos de Aolíbama, mulher de Esaú: os chefes Jeús, Jalão e Corá; esses são os chefes que nasceram a líbama, filha de Ana, mulher de Esaú.

[[v1-36-19]]

^<<v1-36-19,19>>^ Esses são os filhos de Esaú, e esses seus príncipes: ele é Edom.

[[v1-36-20]]

^<<v1-36-20,20>>^ São estes os filhos de Seir, o horeu, moradores da terra: Lotã, Sobal, Zibeão, Anás,

[[v1-36-21]]

^<<v1-36-21,21>>^ Disom, Eser e Disã; esses são os chefes dos horeus, filhos de Seir, na terra de Edom.

[[v1-36-22]]

^<<v1-36-22,22>>^ Os filhos de Lotã foram: Hori e Hemã; e a irmã de Lotã era Timna.

[[v1-36-23]]

^<<v1-36-23,23>>^ Estes são os filhos de Sobal: Alvã, Manaate, Ebal, Sefô e Onão.

[[v1-36-24]]

^<<v1-36-24,24>>^ Estes são os filhos de Zibeão: Aías e Anás; este é o Anás que achou as fontes termais no deserto, quando apascentava os jumentos de Zibeão, seu pai.

[[v1-36-25]]

^<<v1-36-25,25>>^ São estes os filhos de Ana: Disom e Aolíbama, filha de Ana.

[[v1-36-26]]

^<<v1-36-26,26>>^ São estes os filhos de Disom: Hendã, Esbã, Itrã e Querã.

[[v1-36-27]]

^<<v1-36-27,27>>^ Estes são os filhos de Eser: Bilã, Zaavã e Acã.

[[v1-36-28]]

^<<v1-36-28,28>>^ Estes são os filhos de Disã: Uz e Arã.

[[v1-36-29]]

^<<v1-36-29,29>>^ Estes são os chefes dos horeus: Lotã, Sobal, Zibeão, Anás,

[[v1-36-30]]

^<<v1-36-30,30>>^ Disom, Eser e Disã; esses são os chefes dos horeus que governaram na terra de Seir.

[[v1-36-31]]

^<<v1-36-31,31>>^ São estes os reis que reinaram na terra de Edom, antes que reinasse rei algum sobre os filhos de Israel.

[[v1-36-32]]

^<<v1-36-32,32>>^ Reinou, pois, em Edom Belá, filho de Beor; e o nome da sua cidade era Dinabá.

[[v1-36-33]]

^<<v1-36-33,33>>^ Morreu Belá; e Jobabe, filho de Zerá de Bozra, reinou em seu lugar.

[[v1-36-34]]

^<<v1-36-34,34>>^ Morreu Jobabe; e Husão, da terra dos temanitas, reinou em seu lugar.

[[v1-36-35]]

^<<v1-36-35,35>>^ Morreu Husão; e em seu lugar reinou Hadade, filho de Bedade, que feriu a Midiã no campo de Moabe; e o nome da sua cidade era Avite.

[[v1-36-36]]

^<<v1-36-36,36>>^ Morreu Hadade; e Sâmela de Masreca reinou em seu lugar.

[[v1-36-37]]

^<<v1-36-37,37>>^ Morreu Sâmela; e Saul de Reobote junto ao rio reinou em seu lugar.

[[v1-36-38]]

^<<v1-36-38,38>>^ Morreu Saul; e Baal-Hanã, filho de Acbor, reinou em seu lugar.

[[v1-36-39]]

^<<v1-36-39,39>>^ Morreu Baal-Hanã, filho de Acbor; e Hadar reinou em seu lugar; e o nome da sua cidade era Paú; e o nome de sua mulher era Meetabel, filha de Matrede, filha de Me-Zaabe.

[[v1-36-40]]

^<<v1-36-40,40>>^ Estes são os nomes dos chefes dos filhos de Esaú, segundo as suas famílias, segundo os seus lugares, pelos seus nomes: os chefes Timna, Alva, Jetete,

[[v1-36-41]]

^<<v1-36-41,41>>^ Aolíbama, Elá, Pinom,

[[v1-36-42]]

^<<v1-36-42,42>>^ Quenaz, Temã, Mibzar,

[[v1-36-43]]

^<<v1-36-43,43>>^ Magdiel e Irão; esses são os chefes de Edom, segundo as suas habitações, na terra ,da sua possessão. Este é Esaú, pai dos edomeus.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]