include::./index.adoc[]

[[v1-50-0]]
=== Gênesis, 50
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-50-1]]

^<<v1-50-1,1>>^ Então José se lançou sobre o rosto de seu pai, chorou sobre ele e o beijou.

[[v1-50-2]]

^<<v1-50-2,2>>^ E José ordenou a seus servos, os médicos, que embalsamassem a seu pai; e os médicos embalsamaram a Israel.

[[v1-50-3]]

^<<v1-50-3,3>>^ Cumpriram-se-lhe quarenta dias, porque assim se cumprem os dias de embalsamação; e os egípcios o choraram setenta dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Passados, pois, os dias de seu choro, disse José à casa de Faraó: Se agora tenho achado graça aos vossos olhos, rogo-vos que faleis aos ouvidos de Faraó, dizendo:

[[v1-50-5]]

^<<v1-50-5,5>>^ Meu pai me fez jurar, dizendo: Eis que eu morro; em meu sepulcro, que cavei para mim na terra de Canaã, ali me sepultarás. Agora, pois, deixa-me subir, peço-te, e sepultar meu pai; então voltarei.

[[v1-50-6]]

^<<v1-50-6,6>>^ Respondeu Faraó: Sobe, e sepulta teu pai, como ele te fez jurar.

[[v1-50-7]]

^<<v1-50-7,7>>^ Subiu, pois, José para sepultar a seu pai; e com ele subiram todos os servos de Faraó, os anciãos da sua casa, e todos os anciãos da terra do Egito,

[[v1-50-8]]

^<<v1-50-8,8>>^ como também toda a casa de José, e seus irmãos, e a casa de seu pai; somente deixaram na terra de Gósen os seus pequeninos, os seus rebanhos e o seu gado.

[[v1-50-9]]

^<<v1-50-9,9>>^ E subiram com ele tanto carros como gente a cavalo; de modo que o concurso foi mui grande.

[[v1-50-10]]

^<<v1-50-10,10>>^ Chegando eles à eira de Atade, que está além do Jordão, fizeram ali um grande e forte pranto; assim fez José por seu pai um grande pranto por sete dias.

[[v1-50-11]]

^<<v1-50-11,11>>^ Os moradores da terra, os cananeus, vendo o pranto na eira de Atade, disseram: Grande pranto é este dos egípcios; pelo que o lugar foi chamado Abel-Mizraim, o qual está além do Jordão.

[[v1-50-12]]

^<<v1-50-12,12>>^ Assim os filhos de Jacó lhe fizeram como ele lhes ordenara;

[[v1-50-13]]

^<<v1-50-13,13>>^ pois o levaram para a terra de Canaã, e o sepultaram na cova do campo de Macpela, que Abraão tinha comprado com o campo, como propriedade de sepultura, a Efrom, o heteu, em frente de Manre.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois de haver sepultado seu pai, José voltou para o Egito, ele, seus irmãos, e todos os que com ele haviam subido para sepultar seu pai.

[[v1-50-15]]

^<<v1-50-15,15>>^ Vendo os irmãos de José que seu pai estava morto, disseram: Porventura José nos odiará e nos retribuirá todo o mal que lhe fizemos.

[[v1-50-16]]

^<<v1-50-16,16>>^ Então mandaram dizer a José: Teu pai, antes da sua morte, nos ordenou:

[[v1-50-17]]

^<<v1-50-17,17>>^ Assim direis a José: Perdoa a transgressão de teus irmãos, e o seu pecado, porque te fizeram mal. Agora, pois, rogamos-te que perdoes a transgressão dos servos do Deus de teu pai. E José chorou quando eles lhe falavam.

[[v1-50-18]]

^<<v1-50-18,18>>^ Depois vieram também seus irmãos, prostraram-se diante dele e disseram: Eis que nós somos teus servos.

[[v1-50-19]]

^<<v1-50-19,19>>^ Respondeu-lhes José: Não temais; acaso estou eu em lugar de Deus?

[[v1-50-20]]

^<<v1-50-20,20>>^ Vós, na verdade, intentastes o mal contra mim; Deus, porém, o intentou para o bem, para fazer o que se vê neste dia, isto é, conservar muita gente com vida.

[[v1-50-21]]

^<<v1-50-21,21>>^ Agora, pois, não temais; eu vos sustentarei, a vós e a vossos filhinhos. Assim ele os consolou, e lhes falou ao coração.

[[v1-50-22]]

^<<v1-50-22,22>>^ José, pois, habitou no Egito, ele e a casa de seu pai; e viveu cento e dez anos.

[[v1-50-23]]

^<<v1-50-23,23>>^ E viu José os filhos de Efraim, da terceira geração; também os filhos de Maquir, filho de Manassés, nasceram sobre os joelhos de José.

[[v1-50-24]]

^<<v1-50-24,24>>^ Depois disse José a seus irmãos: Eu morro; mas Deus certamente vos visitará, e vos fará subir desta terra para a terra que jurou a Abraão, a Isaque e a Jacó.

[[v1-50-25]]

^<<v1-50-25,25>>^ E José fez jurar os filhos de Israel, dizendo: Certamente Deus vos visitará, e fareis transportar daqui os meus ossos.

[[v1-50-26]]

^<<v1-50-26,26>>^ Assim morreu José, tendo cento e dez anos de idade; e o embalsamaram e o puseram num caixão no Egito.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]