include::./index.adoc[]

[[v1-45-0]]
=== Gênesis, 45
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-45-1]]

^<<v1-45-1,1>>^ Então José não se podia conter diante de todos os que estavam com ele; e clamou: Fazei a todos sair da minha presença; e ninguém ficou com ele, quando se deu a conhecer a seus irmãos.

[[v1-45-2]]

^<<v1-45-2,2>>^ E levantou a voz em choro, de maneira que os egípcios o ouviram, bem como a casa de Faraó.

[[v1-45-3]]

^<<v1-45-3,3>>^ Disse, então, José a seus irmãos: Eu sou José; vive ainda meu pai? E seus irmãos não lhe puderam responder, pois estavam pasmados diante dele.

[[v1-45-4]]

^<<v1-45-4,4>>^ José disse mais a seus irmãos: Chegai-vos a mim, peço-vos. E eles se chegaram. Então ele prosseguiu: Eu sou José, vosso irmão, a quem vendestes para o Egito.

[[v1-45-5]]

^<<v1-45-5,5>>^ Agora, pois, não vos entristeçais, nem vos aborreçais por me haverdes vendido para cá; porque para preservar vida é que Deus me enviou adiante de vós.

[[v1-45-6]]

^<<v1-45-6,6>>^ Porque já houve dois anos de fome na terra, e ainda restam cinco anos em que não haverá lavoura nem sega.

[[v1-45-7]]

^<<v1-45-7,7>>^ Deus enviou-me adiante de vós, para conservar-vos descendência na terra, e para guardar-vos em vida por um grande livramento.

[[v1-45-8]]

^<<v1-45-8,8>>^ Assim não fostes vós que me enviastes para cá, senão Deus, que me tem posto por pai de Faraó, e por senhor de toda a sua casa, e como governador sobre toda a terra do Egito.

[[v1-45-9]]

^<<v1-45-9,9>>^ Apressai-vos, subi a meu pai, e dizei-lhe: Assim disse teu filho José: Deus me tem posto por senhor de toda a terra do Egito; desce a mim, e não te demores;

[[v1-45-10]]

^<<v1-45-10,10>>^ habitarás na terra de Gósem e estarás perto de mim, tu e os teus filhos e os filhos de teus filhos, e os teus rebanhos, o teu gado e tudo quanto tens;

[[v1-45-11]]

^<<v1-45-11,11>>^ ali te sustentarei, porque ainda haverá cinco anos de fome, para que não sejas reduzido à pobreza, tu e tua casa, e tudo o que tens.

[[v1-45-12]]

^<<v1-45-12,12>>^ Eis que os vossos olhos, e os de meu irmão Benjamim, vêem que é minha boca que vos fala.

[[v1-45-13]]

^<<v1-45-13,13>>^ Fareis, pois, saber a meu pai toda a minha glória no Egito; e tudo o que tendes visto; e apressar-vos-eis a fazer descer meu pai para cá.

[[v1-45-14]]

^<<v1-45-14,14>>^ Então se lançou ao pescoço de Benjamim seu irmão, e chorou; e Benjamim chorou também ao pescoço dele.

[[v1-45-15]]

^<<v1-45-15,15>>^ E José beijou a todos os seus irmãos, chorando sobre eles; depois seus irmãos falaram com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ Esta nova se fez ouvir na casa de Faraó: São vindos os irmãos de José; o que agradou a Faraó e a seus servos.

[[v1-45-17]]

^<<v1-45-17,17>>^ Ordenou Faraó a José: Dize a teus irmãos: Fazei isto: carregai os vossos animais e parti, tornai à terra de Canaã;

[[v1-45-18]]

^<<v1-45-18,18>>^ tomai o vosso pai e as vossas famílias e vinde a mim; e eu vos darei o melhor da terra do Egito, e comereis da fartura da terra.

[[v1-45-19]]

^<<v1-45-19,19>>^ A ti, pois, é ordenado dizer-lhes: Fazei isto: levai vós da terra do Egito carros para vossos meninos e para vossas mulheres; trazei vosso pai, e vinde.

[[v1-45-20]]

^<<v1-45-20,20>>^ E não vos pese coisa alguma das vossas alfaias; porque o melhor de toda a terra do Egito será vosso.

[[v1-45-21]]

^<<v1-45-21,21>>^ Assim fizeram os filhos de Israel. José lhes deu carros, conforme o mandado de Faraó, e deu-lhes também provisão para o caminho.

[[v1-45-22]]

^<<v1-45-22,22>>^ A todos eles deu, a cada um, mudas de roupa; mas a Benjamim deu trezentas peças de prata, e cinco mudas de roupa.

[[v1-45-23]]

^<<v1-45-23,23>>^ E a seu pai enviou o seguinte: dez jumentos carregados do melhor do Egito, e dez jumentas carregadas de trigo, pão e provisão para seu pai, para o caminho.

[[v1-45-24]]

^<<v1-45-24,24>>^ Assim despediu seus irmãos e, ao partirem eles, disse-lhes: Não contendais pelo caminho.

[[v1-45-25]]

^<<v1-45-25,25>>^ Então subiram do Egito, vieram à terra de Canaã, a Jacó seu pai,

[[v1-45-26]]

^<<v1-45-26,26>>^ e lhe anunciaram, dizendo: José ainda vive, e é governador de toda a terra do Egito. E o seu coração desmaiou, porque não os acreditava.

[[v1-45-27]]

^<<v1-45-27,27>>^ Quando, porém, eles lhe contaram todas as palavras que José lhes falara, e vendo Jacó, seu pai, os carros que José enviara para levá-lo, reanimou-se-lhe o espírito;

[[v1-45-28]]

^<<v1-45-28,28>>^ e disse Israel: Basta; ainda vive meu filho José; eu irei e o verei antes que morra.

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]