include::./index.adoc[]

[[v1-15-0]]
=== Gênesis, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-15-1]]

^<<v1-15-1,1>>^ Depois destas coisas veio a palavra do Senhor a Abrão numa visão, dizendo: Não temas, Abrão; eu sou o teu escudo, o teu galardão será grandíssimo.

[[v1-15-2]]

^<<v1-15-2,2>>^ Então disse Abrão: Ó Senhor Deus, que me darás, visto que morro sem filhos, e o herdeiro de minha casa é o damasceno Eliézer?

[[v1-15-3]]

^<<v1-15-3,3>>^ Disse mais Abrão: A mim não me tens dado filhos; eis que um nascido na minha casa será o meu herdeiro.

[[v1-15-4]]

^<<v1-15-4,4>>^ Ao que lhe veio a palavra do Senhor, dizendo: Este não será o teu herdeiro; mas aquele que sair das tuas entranhas, esse será o teu herdeiro.

[[v1-15-5]]

^<<v1-15-5,5>>^ Então o levou para fora, e disse: Olha agora para o céu, e conta as estrelas, se as podes contar; e acrescentou-lhe: Assim será a tua descendência.

[[v1-15-6]]

^<<v1-15-6,6>>^ E creu Abrão no Senhor, e o Senhor imputou-lhe isto como justiça.

[[v1-15-7]]

^<<v1-15-7,7>>^ Disse-lhe mais: Eu sou o Senhor, que te tirei de Ur dos caldeus, para te dar esta terra em herança.

[[v1-15-8]]

^<<v1-15-8,8>>^ Ao que lhe perguntou Abrão: Ó Senhor Deus, como saberei que hei de herdá-la?

[[v1-15-9]]

^<<v1-15-9,9>>^ Respondeu-lhe: Toma-me uma novilha de três anos, uma cabra de três anos, um carneiro de três anos, uma rola e um pombinho.

[[v1-15-10]]

^<<v1-15-10,10>>^ Ele, pois, lhe trouxe todos estes animais, partiu-os pelo meio, e pôs cada parte deles em frente da outra; mas as aves não partiu.

[[v1-15-11]]

^<<v1-15-11,11>>^ E as aves de rapina desciam sobre os cadáveres; Abrão, porém, as enxotava.

[[v1-15-12]]

^<<v1-15-12,12>>^ Ora, ao pôr do sol, caiu um profundo sono sobre Abrão; e eis que lhe sobrevieram grande pavor e densas trevas.

[[v1-15-13]]

^<<v1-15-13,13>>^ Então disse o Senhor a Abrão: Sabe com certeza que a tua descendência será peregrina em terra alheia, e será reduzida à escravidão, e será afligida por quatrocentos anos;

[[v1-15-14]]

^<<v1-15-14,14>>^ sabe também que eu julgarei a nação a qual ela tem de servir; e depois sairá com muitos bens.

[[v1-15-15]]

^<<v1-15-15,15>>^ Tu, porém, irás em paz para teus pais; em boa velhice serás sepultado.

[[v1-15-16]]

^<<v1-15-16,16>>^ Na quarta geração, porém, voltarão para cá; porque a medida da iniqüidade dos amorreus não está ainda cheia.

[[v1-15-17]]

^<<v1-15-17,17>>^ Quando o sol já estava posto, e era escuro, eis um fogo fumegante e uma tocha de fogo, que passaram por entre aquelas metades.

[[v1-15-18]]

^<<v1-15-18,18>>^ Naquele mesmo dia fez o Senhor um pacto com Abrão, dizendo: À tua descendência tenho dado esta terra, desde o rio do Egito até o grande rio Eufrates;

[[v1-15-19]]

^<<v1-15-19,19>>^ e o queneu, o quenizeu, o cadmoneu,

[[v1-15-20]]

^<<v1-15-20,20>>^ o heteu, o perizeu, os refains,

[[v1-15-21]]

^<<v1-15-21,21>>^ o amorreu, o cananeu, o girgaseu e o jebuseu.

'''

xref:001-genesis/001-genesis-014.adoc#v1-14-0[&#60; Capítulo Anterior] | <<v1-15-0,Topo>> | xref:001-genesis/001-genesis-016.adoc#v1-16-0[Próximo Capítulo &#62;]