include::./index.adoc[]

[[v1-38-0]]
=== Gênesis, 38
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-38-1]]

^<<v1-38-1,1>>^ Nesse tempo Judá desceu de entre seus irmãos e entrou na casa dum adulamita, que se chamava Hira,

[[v1-38-2]]

^<<v1-38-2,2>>^ e viu Judá ali a filha de um cananeu, que se chamava Suá; tomou-a por mulher, e esteve com ela.

[[v1-38-3]]

^<<v1-38-3,3>>^ Ela concebeu e teve um filho, e o pai chamou-lhe Er.

[[v1-38-4]]

^<<v1-38-4,4>>^ Tornou ela a conceber e teve um filho, a quem ela chamou Onã.

[[v1-38-5]]

^<<v1-38-5,5>>^ Teve ainda mais um filho, e chamou-lhe Selá. Estava Judá em Quezibe, quando ela o teve.

[[v1-38-6]]

^<<v1-38-6,6>>^ Depois Judá tomou para Er, o seu primogênito, uma mulher, por nome Tamar.

[[v1-38-7]]

^<<v1-38-7,7>>^ Ora, Er, o primogênito de Judá, era mau aos olhos do Senhor, pelo que o Senhor o matou.

[[v1-38-8]]

^<<v1-38-8,8>>^ Então disse Judá a Onã: Toma a mulher de teu irmão, e cumprindo-lhe o dever de cunhado, suscita descendência a teu irmão.

[[v1-38-9]]

^<<v1-38-9,9>>^ Onã, porém, sabia que tal descendência não havia de ser para ele; de modo que, toda vez que se unia à mulher de seu irmão, derramava o sêmen no chão para não dar descendência a seu irmão.

[[v1-38-10]]

^<<v1-38-10,10>>^ E o que ele fazia era mau aos olhos do Senhor, pelo que o matou também a ele.

[[v1-38-11]]

^<<v1-38-11,11>>^ Então disse Judá a Tamar sua nora: Conserva-te viúva em casa de teu pai, até que Selá, meu filho, venha a ser homem; porquanto disse ele: Para que porventura não morra também este, como seus irmãos. Assim se foi Tamar e morou em casa de seu pai.

[[v1-38-12]]

^<<v1-38-12,12>>^ Com o correr do tempo, morreu a filha de Suá, mulher de Judá. Depois de consolado, Judá subiu a Timnate para ir ter com os tosquiadores das suas ovelhas, ele e Hira seu amigo, o adulamita.

[[v1-38-13]]

^<<v1-38-13,13>>^ E deram aviso a Tamar, dizendo: Eis que o teu sogro sobe a Timnate para tosquiar as suas ovelhas.

[[v1-38-14]]

^<<v1-38-14,14>>^ Então ela se despiu dos vestidos da sua viuvez e se cobriu com o véu, e assim envolvida, assentou-se à porta de Enaim que está no caminho de Timnate; porque via que Selá já era homem, e ela lhe não fora dada por mulher.

[[v1-38-15]]

^<<v1-38-15,15>>^ Ao vê-la, Judá julgou que era uma prostituta, porque ela havia coberto o rosto.

[[v1-38-16]]

^<<v1-38-16,16>>^ E dirigiu-se para ela no caminho, e disse: Vem, deixa-me estar contigo; porquanto não sabia que era sua nora. Perguntou-lhe ela: Que me darás, para estares comigo?

[[v1-38-17]]

^<<v1-38-17,17>>^ Respondeu ele: Eu te enviarei um cabrito do rebanho. Perguntou ela ainda: Dar-me-ás um penhor até que o envies?

[[v1-38-18]]

^<<v1-38-18,18>>^ Então ele respondeu: Que penhor é o que te darei? Disse ela: O teu selo com a corda, e o cajado que está em tua mão. Ele, pois, lhos deu, e esteve com ela, e ela concebeu dele.

[[v1-38-19]]

^<<v1-38-19,19>>^ E ela se levantou e se foi; tirou de si o véu e vestiu os vestidos da sua viuvez.

[[v1-38-20]]

^<<v1-38-20,20>>^ Depois Judá enviou o cabrito por mão do seu amigo o adulamita, para receber o penhor da mão da mulher; porém ele não a encontrou.

[[v1-38-21]]

^<<v1-38-21,21>>^ Pelo que perguntou aos homens daquele lugar: Onde está a prostituta que estava em Enaim junto ao caminho? E disseram: Aqui não esteve prostituta alguma.

[[v1-38-22]]

^<<v1-38-22,22>>^ Voltou, pois, a Judá e disse: Não a achei; e também os homens daquele lugar disseram: Aqui não esteve prostituta alguma.

[[v1-38-23]]

^<<v1-38-23,23>>^ Então disse Judá: Deixa-a ficar com o penhor, para que não caiamos em desprezo; eis que enviei este cabrito, mas tu não a achaste.

[[v1-38-24]]

^<<v1-38-24,24>>^ Passados quase três meses, disseram a Judá: Tamar, tua nora, se prostituiu e eis que está grávida da sua prostituição. Então disse Judá: Tirai-a para fora, e seja ela queimada.

[[v1-38-25]]

^<<v1-38-25,25>>^ Quando ela estava sendo tirada para fora, mandou dizer a seu sogro: Do homem a quem pertencem estas coisas eu concebi. Disse mais: Reconhece, peço-te, de quem são estes, o selo com o cordão, e o cajado.

[[v1-38-26]]

^<<v1-38-26,26>>^ Reconheceu-os, pois, Judá, e disse: Ela é mais justa do que eu, porquanto não a dei a meu filho Selá. E nunca mais a conheceu.

[[v1-38-27]]

^<<v1-38-27,27>>^ Sucedeu que, ao tempo de ela dar à luz, havia gêmeos em seu ventre;

[[v1-38-28]]

^<<v1-38-28,28>>^ e dando ela à luz, um pôs fora a mão, e a parteira tomou um fio encarnado e o atou em sua mão, dizendo: Este saiu primeiro.

[[v1-38-29]]

^<<v1-38-29,29>>^ Mas recolheu ele a mão, e eis que seu irmão saiu; pelo que ela disse: Como tens tu rompido! Portanto foi chamado Pérez.

[[v1-38-30]]

^<<v1-38-30,30>>^ Depois saiu o seu irmão, em cuja mão estava o fio encamado; e foi chamado Zerá.

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]