include::./index.adoc[]

[[v1-42-0]]
=== Gênesis, 42
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-42-1]]

^<<v1-42-1,1>>^ Ora, Jacó soube que havia trigo no Egito, e disse a seus filhos: Por que estais olhando uns para os outros?

[[v1-42-2]]

^<<v1-42-2,2>>^ Disse mais: Tenho ouvido que há trigo no Egito; descei até lá, e de lá comprai-o para nós, a fim de que vivamos e não morramos.

[[v1-42-3]]

^<<v1-42-3,3>>^ Então desceram os dez irmãos de José, para comprarem trigo no Egito.

[[v1-42-4]]

^<<v1-42-4,4>>^ Mas a Benjamim, irmão de José, não enviou Jacó com os seus irmãos, pois disse: Para que, porventura, não lhe suceda algum desastre.

[[v1-42-5]]

^<<v1-42-5,5>>^ Assim entre os que iam lá, foram os filhos de Israel para comprar, porque havia fome na terra de Canaã.

[[v1-42-6]]

^<<v1-42-6,6>>^ José era o governador da terra; era ele quem vendia a todo o povo da terra; e vindo os irmãos de José, prostraram-se diante dele com o rosto em terra.

[[v1-42-7]]

^<<v1-42-7,7>>^ José, vendo seus irmãos, reconheceu-os; mas portou-se como estranho para com eles, falou-lhes asperamente e perguntou-lhes: Donde vindes? Responderam eles: Da terra de Canaã, para comprarmos mantimento.

[[v1-42-8]]

^<<v1-42-8,8>>^ José, pois, reconheceu seus irmãos, mas eles não o reconheceram.

[[v1-42-9]]

^<<v1-42-9,9>>^ Lembrou-se então José dos sonhos que tivera a respeito deles, e disse-lhes: Vós sois espias, e viestes para ver a nudez da terra.

[[v1-42-10]]

^<<v1-42-10,10>>^ Responderam-lhe eles: Não, senhor meu; mas teus servos vieram comprar mantimento.

[[v1-42-11]]

^<<v1-42-11,11>>^ Nós somos todos filhos de um mesmo homem; somos homens de retidão; os teus servos não são espias.

[[v1-42-12]]

^<<v1-42-12,12>>^ Replicou-lhes: Não; antes viestes para ver a nudez da terra.

[[v1-42-13]]

^<<v1-42-13,13>>^ Mas eles disseram: Nós, teus servos, somos doze irmãos, filhos de um homem da terra de Canaã; o mais novo está hoje com nosso pai, e outro já não existe.

[[v1-42-14]]

^<<v1-42-14,14>>^ Respondeu-lhe José: É assim como vos disse; sois espias.

[[v1-42-15]]

^<<v1-42-15,15>>^ Nisto sereis provados: Pela vida de Faraó, não saireis daqui, a menos que venha para cá vosso irmão mais novo.

[[v1-42-16]]

^<<v1-42-16,16>>^ Enviai um dentre vós, que traga vosso irmão, mas vós ficareis presos, a fim de serem provadas as vossas palavras, se há verdade convosco; e se não, pela vida de Faraó, vós sois espias.

[[v1-42-17]]

^<<v1-42-17,17>>^ E meteu-os juntos na prisão por três dias.

[[v1-42-18]]

^<<v1-42-18,18>>^ Ao terceiro dia disse-lhes José: Fazei isso, e vivereis; porque eu temo a Deus.

[[v1-42-19]]

^<<v1-42-19,19>>^ Se sois homens de retidão, que fique um dos irmãos preso na casa da vossa prisão; mas ide vós, levai trigo para a fome de vossas casas,

[[v1-42-20]]

^<<v1-42-20,20>>^ e trazei-me o vosso irmão mais novo; assim serão verificadas vossas palavras, e não morrereis. E eles assim fizeram.

[[v1-42-21]]

^<<v1-42-21,21>>^ Então disseram uns aos outros: Nós, na verdade, somos culpados no tocante a nosso irmão, porquanto vimos a angústia da sua alma, quando nos rogava, e não o quisemos atender; é por isso que vem sobre nós esta angústia.

[[v1-42-22]]

^<<v1-42-22,22>>^ Respondeu-lhes Rúben: Não vos dizia eu: Não pequeis contra o menino; Mas não quisestes ouvir; por isso agora é requerido de nós o seu sangue.

[[v1-42-23]]

^<<v1-42-23,23>>^ E eles não sabiam que José os entendia, porque havia intérprete entre eles.

[[v1-42-24]]

^<<v1-42-24,24>>^ Nisto José se retirou deles e chorou. Depois tornou a eles, falou-lhes, e tomou a Simeão dentre eles, e o amarrou perante os seus olhos.

[[v1-42-25]]

^<<v1-42-25,25>>^ Então ordenou José que lhes enchessem de trigo os sacos, que lhes restituíssem o dinheiro a cada um no seu saco, e lhes dessem provisões para o caminho. E assim lhes foi feito.

[[v1-42-26]]

^<<v1-42-26,26>>^ Eles, pois, carregaram o trigo sobre os seus jumentos, e partiram dali.

[[v1-42-27]]

^<<v1-42-27,27>>^ Quando um deles abriu o saco, para dar forragem ao seu jumento na estalagem, viu o seu dinheiro, pois estava na boca do saco.

[[v1-42-28]]

^<<v1-42-28,28>>^ E disse a seus irmãos: Meu dinheiro foi-me devolvido; ei-lo aqui no saco. Então lhes desfaleceu o coração e, tremendo, viravam-se uns para os outros, dizendo: Que é isto que Deus nos tem feito?

[[v1-42-29]]

^<<v1-42-29,29>>^ Depois vieram para Jacó, seu pai, na terra de Canaã, e contaram-lhe tudo o que lhes acontecera, dizendo:

[[v1-42-30]]

^<<v1-42-30,30>>^ O homem, o senhor da terra, falou-nos asperamente, e tratou-nos como espias da terra;

[[v1-42-31]]

^<<v1-42-31,31>>^ mas dissemos-lhe: Somos homens de retidão; não somos espias;

[[v1-42-32]]

^<<v1-42-32,32>>^ somos doze irmãos, filhos de nosso pai; um já não existe e o mais novo está hoje com nosso pai na terra de Canaã.

[[v1-42-33]]

^<<v1-42-33,33>>^ Respondeu-nos o homem, o senhor da terra: Nisto conhecerei que vós sois homens de retidão: Deixai comigo um de vossos irmãos, levai trigo para a fome de vossas casas, e parti,

[[v1-42-34]]

^<<v1-42-34,34>>^ e trazei-me vosso irmão mais novo; assim saberei que não sois espias, mas homens de retidão; então vos entregarei o vosso irmão e negociareis na terra.

[[v1-42-35]]

^<<v1-42-35,35>>^ E aconteceu que, despejando eles os sacos, eis que o pacote de dinheiro de cada um estava no seu saco; quando eles e seu pai viram os seus pacotes de dinheiro, tiveram medo.

[[v1-42-36]]

^<<v1-42-36,36>>^ Então Jacó, seu pai, disse-lhes: Tendes-me desfilhado; José já não existe, e não existe Simeão, e haveis de levar Benjamim! Todas estas coisas vieram sobre mim.

[[v1-42-37]]

^<<v1-42-37,37>>^ Mas Rúben falou a seu pai, dizendo: Mata os meus dois filhos, se eu to não tornar a trazer; entrega-o em minha mão, e to tornarei a trazer.

[[v1-42-38]]

^<<v1-42-38,38>>^ Ele porém disse: Não descerá meu filho convosco; porquanto o seu irmão é morto, e só ele ficou. Se lhe suceder algum desastre pelo caminho em que fordes, fareis descer minhas cãs com tristeza ao Seol.

'''

xref:001-genesis/001-genesis-041.adoc#v1-41-0[&#60; Capítulo Anterior] | <<v1-42-0,Topo>> | xref:001-genesis/001-genesis-043.adoc#v1-43-0[Próximo Capítulo &#62;]