include::./index.adoc[]

[[v1-18-0]]
=== Gênesis, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-18-1]]

^<<v1-18-1,1>>^ Depois apareceu o Senhor a Abraão junto aos carvalhos de Manre, estando ele sentado à porta da tenda, no maior calor do dia.

[[v1-18-2]]

^<<v1-18-2,2>>^ Levantando Abraão os olhos, olhou e eis três homens de pé em frente dele. Quando os viu, correu da porta da tenda ao seu encontro, e prostrou-se em terra,

[[v1-18-3]]

^<<v1-18-3,3>>^ e disse: Meu Senhor, se agora tenho achado graça aos teus olhos, rogo-te que não passes de teu servo.

[[v1-18-4]]

^<<v1-18-4,4>>^ Eia, traga-se um pouco d'água, e lavai os pés e recostai-vos debaixo da árvore;

[[v1-18-5]]

^<<v1-18-5,5>>^ e trarei um bocado de pão; refazei as vossas forças, e depois passareis adiante; porquanto por isso chegastes ate o vosso servo. Responderam-lhe: Faze assim como disseste.

[[v1-18-6]]

^<<v1-18-6,6>>^ Abraão, pois, apressou-se em ir ter com Sara na tenda, e disse-lhe: Amassa depressa três medidas de flor de farinha e faze bolos.

[[v1-18-7]]

^<<v1-18-7,7>>^ Em seguida correu ao gado, apanhou um bezerro tenro e bom e deu-o ao criado, que se apressou em prepará-lo.

[[v1-18-8]]

^<<v1-18-8,8>>^ Então tomou queijo fresco, e leite, e o bezerro que mandara preparar, e pôs tudo diante deles, ficando em pé ao lado deles debaixo da árvore, enquanto comiam.

[[v1-18-9]]

^<<v1-18-9,9>>^ Perguntaram-lhe eles: Onde está Sara, tua mulher? Ele respondeu: Está ali na tenda.

[[v1-18-10]]

^<<v1-18-10,10>>^ E um deles lhe disse: certamente tornarei a ti no ano vindouro; e eis que Sara tua mulher terá um filho. E Sara estava escutando à porta da tenda, que estava atrás dele.

[[v1-18-11]]

^<<v1-18-11,11>>^ Ora, Abraão e Sara eram já velhos, e avançados em idade; e a Sara havia cessado o incômodo das mulheres.

[[v1-18-12]]

^<<v1-18-12,12>>^ Sara então riu-se consigo, dizendo: Terei ainda deleite depois de haver envelhecido, sendo também o meu senhor já velho?

[[v1-18-13]]

^<<v1-18-13,13>>^ Perguntou o Senhor a Abraão: Por que se riu Sara, dizendo: É verdade que eu, que sou velha, darei à luz um filho?

[[v1-18-14]]

^<<v1-18-14,14>>^ Há, porventura, alguma coisa difícil ao Senhor? Ao tempo determinado, no ano vindouro, tornarei a ti, e Sara terá um filho.

[[v1-18-15]]

^<<v1-18-15,15>>^ Então Sara negou, dizendo: Não me ri; porquanto ela teve medo. Ao que ele respondeu: Não é assim; porque te riste.

[[v1-18-16]]

^<<v1-18-16,16>>^ E levantaram-se aqueles homens dali e olharam para a banda de Sodoma; e Abraão ia com eles, para os encaminhar.

[[v1-18-17]]

^<<v1-18-17,17>>^ E disse o Senhor: Ocultarei eu a Abraão o que faço,

[[v1-18-18]]

^<<v1-18-18,18>>^ visto que Abraão certamente virá a ser uma grande e poderosa nação, e por meio dele serão benditas todas as nações da terra?

[[v1-18-19]]

^<<v1-18-19,19>>^ Porque eu o tenho escolhido, a fim de que ele ordene a seus filhos e a sua casa depois dele, para que guardem o caminho do Senhor, para praticarem retidão e justiça; a fim de que o Senhor faça vir sobre Abraão o que a respeito dele tem falado.

[[v1-18-20]]

^<<v1-18-20,20>>^ Disse mais o Senhor: Porquanto o clamor de Sodoma e Gomorra se tem multiplicado, e porquanto o seu pecado se tem agravado muito,

[[v1-18-21]]

^<<v1-18-21,21>>^ descerei agora, e verei se em tudo têm praticado segundo o seu clamor, que a mim tem chegado; e se não, sabê-lo-ei.

[[v1-18-22]]

^<<v1-18-22,22>>^ Então os homens, virando os seus rostos dali, foram-se em direção a Sodoma; mas Abraão ficou ainda em pé diante do Senhor.

[[v1-18-23]]

^<<v1-18-23,23>>^ E chegando-se Abraão, disse: Destruirás também o justo com o ímpio?

[[v1-18-24]]

^<<v1-18-24,24>>^ Se porventura houver cinqüenta justos na cidade, destruirás e não pouparás o lugar por causa dos cinqüenta justos que ali estão?

[[v1-18-25]]

^<<v1-18-25,25>>^ Longe de ti que faças tal coisa, que mates o justo com o ímpio, de modo que o justo seja como o ímpio; esteja isto longe de ti. Não fará justiça o juiz de toda a terra?

[[v1-18-26]]

^<<v1-18-26,26>>^ Então disse o Senhor: Se eu achar em Sodoma cinqüenta justos dentro da cidade, pouparei o lugar todo por causa deles.

[[v1-18-27]]

^<<v1-18-27,27>>^ Tornou-lhe Abraão, dizendo: Eis que agora me atrevi a falar ao Senhor, ainda que sou pó e cinza.

[[v1-18-28]]

^<<v1-18-28,28>>^ Se porventura de cinqüenta justos faltarem cinco, destruirás toda a cidade por causa dos cinco? Respondeu ele: Não a destruirei, se eu achar ali quarenta e cinco.

[[v1-18-29]]

^<<v1-18-29,29>>^ Continuou Abraão ainda a falar-lhe, e disse: Se porventura se acharem ali quarenta? Mais uma vez assentiu: Por causa dos quarenta não o farei.

[[v1-18-30]]

^<<v1-18-30,30>>^ Disse Abraão: Ora, não se ire o Senhor, se eu ainda falar. Se porventura se acharem ali trinta? De novo assentiu: Não o farei, se achar ali trinta.

[[v1-18-31]]

^<<v1-18-31,31>>^ Tornou Abraão: Eis que outra vez me a atrevi a falar ao Senhor. Se porventura se acharem ali vinte? Respondeu-lhe: Por causa dos vinte não a destruirei.

[[v1-18-32]]

^<<v1-18-32,32>>^ Disse ainda Abraão: Ora, não se ire o Senhor, pois só mais esta vez falarei. Se porventura se acharem ali dez? Ainda assentiu o Senhor: Por causa dos dez não a destruirei.

[[v1-18-33]]

^<<v1-18-33,33>>^ E foi-se o Senhor, logo que acabou de falar com Abraão; e Abraão voltou para o seu lugar.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]