include::./index.adoc[]

[[v1-49-0]]
=== Gênesis, 49
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-49-1]]

^<<v1-49-1,1>>^ Depois chamou Jacó a seus filhos, e disse: Ajuntai-vos para que eu vos anuncie o que vos há de acontecer nos dias vindouros.

[[v1-49-2]]

^<<v1-49-2,2>>^ Ajuntai-vos, e ouvi, filhos de Jacó; ouvi a Israel vosso pai:

[[v1-49-3]]

^<<v1-49-3,3>>^ Rúben, tu és meu primogênito, minha força e as primícias do meu vigor, preeminente em dignidade e preeminente em poder.

[[v1-49-4]]

^<<v1-49-4,4>>^ Descomedido como a água, não reterás a preeminência; porquanto subiste ao leito de teu pai; então o contaminaste. Sim, ele subiu à minha cama.

[[v1-49-5]]

^<<v1-49-5,5>>^ Simeão e Levi são irmãos; as suas espadas são instrumentos de violência.

[[v1-49-6]]

^<<v1-49-6,6>>^ No seu concílio não entres, ó minha alma! com a sua assembléia não te ajuntes, ó minha glória! porque no seu furor mataram homens, e na sua teima jarretaram bois.

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldito o seu furor, porque era forte! maldita a sua ira, porque era cruel! Dividi-los-ei em Jacó, e os espalharei em Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ Judá, a ti te louvarão teus irmãos; a tua mão será sobre o pescoço de teus inimigos: diante de ti se prostrarão os filhos de teu pai.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judá é um leãozinho. Subiste da presa, meu filho. Ele se encurva e se deita como um leão, e como uma leoa; quem o despertará?

[[v1-49-10]]

^<<v1-49-10,10>>^ O cetro não se arredará de Judá, nem o bastão de autoridade dentre seus pés, até que venha aquele a quem pertence; e a ele obedecerão os povos.

[[v1-49-11]]

^<<v1-49-11,11>>^ Atando ele o seu jumentinho à vide, e o filho da sua jumenta à videira seleta, lava as suas roupas em vinho e a sua vestidura em sangue de uvas.

[[v1-49-12]]

^<<v1-49-12,12>>^ Os olhos serão escurecidos pelo vinho, e os dentes brancos de leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ Zebulom habitará no litoral; será ele ancoradouro de navios; e o seu termo estender-se-á até Sidom.

[[v1-49-14]]

^<<v1-49-14,14>>^ Issacar é jumento forte, deitado entre dois fardos.

[[v1-49-15]]

^<<v1-49-15,15>>^ Viu ele que o descanso era bom, e que a terra era agradável. Sujeitou os seus ombros à carga e entregou-se ao serviço forçado de um escravo.

[[v1-49-16]]

^<<v1-49-16,16>>^ Dã julgará o seu povo, como uma das tribos de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Dã será serpente junto ao caminho, uma víbora junto à vereda, que morde os calcanhares do cavalo, de modo que caia o seu cavaleiro para trás.

[[v1-49-18]]

^<<v1-49-18,18>>^ A tua salvação tenho esperado, ó Senhor!

[[v1-49-19]]

^<<v1-49-19,19>>^ Quanto a Gade, guerrilheiros o acometerão; mas ele, por sua vez, os acometerá.

[[v1-49-20]]

^<<v1-49-20,20>>^ De Aser, o seu pão será gordo; ele produzirá delícias reais.

[[v1-49-21]]

^<<v1-49-21,21>>^ Naftali é uma gazela solta; ele profere palavras formosas.

[[v1-49-22]]

^<<v1-49-22,22>>^ José é um ramo frutífero, ramo frutífero junto a uma fonte; seus raminhos se estendem sobre o muro.

[[v1-49-23]]

^<<v1-49-23,23>>^ Os flecheiros lhe deram amargura, e o flecharam e perseguiram,

[[v1-49-24]]

^<<v1-49-24,24>>^ mas o seu arco permaneceu firme, e os seus braços foram fortalecidos pelas mãos do Poderoso de Jacó, o Pastor, o Rochedo de Israel,

[[v1-49-25]]

^<<v1-49-25,25>>^ pelo Deus de teu pai, o qual te ajudará, e pelo Todo-Poderoso, o qual te abençoara, com bênçãos dos céus em cima, com bênçãos do abismo que jaz embaixo, com bênçãos dos seios e da madre.

[[v1-49-26]]

^<<v1-49-26,26>>^ As bênçãos de teu pai excedem as bênçãos dos montes eternos, as coisas desejadas dos eternos outeiros; sejam elas sobre a cabeça de José, e sobre o alto da cabeça daquele que foi separado de seus irmãos.

[[v1-49-27]]

^<<v1-49-27,27>>^ Benjamim é lobo que despedaça; pela manhã devorará a presa, e à tarde repartirá o despojo.

[[v1-49-28]]

^<<v1-49-28,28>>^ Todas estas são as doze tribos de Israel: e isto é o que lhes falou seu pai quando os abençoou; a cada um deles abençoou segundo a sua bênção.

[[v1-49-29]]

^<<v1-49-29,29>>^ Depois lhes deu ordem, dizendo-lhes: Eu estou para ser congregado ao meu povo; sepultai-me com meus pais, na cova que está no campo de Efrom, o heteu,

[[v1-49-30]]

^<<v1-49-30,30>>^ na cova que está no campo de Macpela, que está em frente de Manre, na terra de Canaã, cova esta que Abraão comprou de Efrom, o heteu, juntamente com o respectivo campo, como propriedade de sepultura.

[[v1-49-31]]

^<<v1-49-31,31>>^ Ali sepultaram a Abraão e a Sara, sua mulher; ali sepultaram a Isaque e a Rebeca, sua mulher; e ali eu sepultei a Léia.

[[v1-49-32]]

^<<v1-49-32,32>>^ O campo e a cova que está nele foram comprados aos filhos de Hete.

[[v1-49-33]]

^<<v1-49-33,33>>^ Acabando Jacó de dar estas instruções a seus filhos, encolheu os seus pés na cama, expirou e foi congregado ao seu povo.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]