include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-46-1]]

^<<v1-46-1,1>>^ Partiu, pois, Israel com tudo quanto tinha e veio a Beer-Seba, onde ofereceu sacrifícios ao Deus de seu pai Isaque.

[[v1-46-2]]

^<<v1-46-2,2>>^ Falou Deus a Israel em visões de noite, e disse: Jacó, Jacó! Respondeu Jacó: Eis-me aqui.

[[v1-46-3]]

^<<v1-46-3,3>>^ E Deus disse: Eu sou Deus, o Deus de teu pai; não temas descer para o Egito; porque eu te farei ali uma grande nação.

[[v1-46-4]]

^<<v1-46-4,4>>^ Eu descerei contigo para o Egito, e certamente te farei tornar a subir; e José porá a sua mão sobre os teus olhos.

[[v1-46-5]]

^<<v1-46-5,5>>^ Então Jacó se levantou de Beer-Seba; e os filhos de Israel levaram seu pai Jacó, e seus meninos, e as suas mulheres, nos carros que Faraó enviara para o levar.

[[v1-46-6]]

^<<v1-46-6,6>>^ Também tomaram o seu gado e os seus bens que tinham adquirido na terra de Canaã, e vieram para o Egito, Jacó e toda a sua descendência com ele.

[[v1-46-7]]

^<<v1-46-7,7>>^ Os seus filhos e os filhos de seus filhos com ele, as suas filhas e as filhas de seus filhos, e toda a sua descendência, levou-os consigo para o Egito.

[[v1-46-8]]

^<<v1-46-8,8>>^ São estes os nomes dos filhos de Israel, que vieram para o Egito, Jacó e seus filhos: Rúben, o primogênito de Jacó.

[[v1-46-9]]

^<<v1-46-9,9>>^ E os filhos de Rúben: Hanoque, Palu, Hezrom e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ E os filhos de Simeão: Jemuel, Jamim, Oade, Jaquim, Zoar, e Saul, filho de uma mulher cananéia.

[[v1-46-11]]

^<<v1-46-11,11>>^ E os filhos de Levi: Gérsom, Coate e Merári.

[[v1-46-12]]

^<<v1-46-12,12>>^ E os filhos de Judá: Er, Onã, Selá, Pérez e Zerá. Er e Onã, porém, morreram na terra de Canaã. E os filhos de Pérez foram Hezrom e Hamul,

[[v1-46-13]]

^<<v1-46-13,13>>^ E os filhos de Issacar: Tola, Puva, Iobe e Sinrom.

[[v1-46-14]]

^<<v1-46-14,14>>^ E os filhos de Zebulom: Serede, Elom e Jaleel.

[[v1-46-15]]

^<<v1-46-15,15>>^ Estes são os filhos de Léia, que ela deu a Jacó em Padã-Arã, além de Diná, sua filha; todas as almas de seus filhos e de suas filhas eram trinta e três.

[[v1-46-16]]

^<<v1-46-16,16>>^ E os filhos de Gade: Zifiom, Hagui, Suni, Ezbom, Eri, Arodi e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ E os filhos de Aser: Imná, Isvá, Isvi e Beria, e Sera, a irmã deles; e os filhos de Beria: Heber e Malquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ Estes são os filhos de Zilpa, a qual Labão deu à sua filha Léia; e estes ela deu a Jacó, ao todo dezesseis almas.

[[v1-46-19]]

^<<v1-46-19,19>>^ Os filhos de Raquel, mulher de Jacó: José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ E nasceram a José na terra do Egito Manassés e Efraim, que lhe deu Asenate, filha de Potífera, sacerdote de Om.

[[v1-46-21]]

^<<v1-46-21,21>>^ E os filhos de Benjamim: Belá, Bequer, Asbel, Gêra, Naamã, Eí, Ros, Mupim, Hupim e Arde.

[[v1-46-22]]

^<<v1-46-22,22>>^ Estes são os filhos de Raquel, que nasceram a Jacó, ao todo catorze almas.

[[v1-46-23]]

^<<v1-46-23,23>>^ E os filhos de Dã: Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ E os filhos de Naftali: Jazeel, Guni, Jezer e Silém.

[[v1-46-25]]

^<<v1-46-25,25>>^ Estes são os filhos de Bila, a qual Labão deu à sua filha Raquel; e estes deu ela a Jacó, ao todo sete almas.

[[v1-46-26]]

^<<v1-46-26,26>>^ Todas as almas que vieram com Jacó para o Egito e que saíram da sua coxa, fora as mulheres dos filhos de Jacó, eram todas sessenta e seis almas;

[[v1-46-27]]

^<<v1-46-27,27>>^ e os filhos de José, que lhe nasceram no Egito, eram duas almas. Todas as almas da casa de Jacó, que vieram para o Egito eram setenta.

[[v1-46-28]]

^<<v1-46-28,28>>^ Ora, Jacó enviou Judá adiante de si a José, para o encaminhar a Gósen; e chegaram à terra de Gósen.

[[v1-46-29]]

^<<v1-46-29,29>>^ Então José aprontou o seu carro, e subiu ao encontro de Israel, seu pai, a Gósen; e tendo-se-lhe apresentado, lançou-se ao seu pescoço, e chorou sobre o seu pescoço longo tempo.

[[v1-46-30]]

^<<v1-46-30,30>>^ E Israel disse a José: Morra eu agora, já que tenho visto o teu rosto, pois que ainda vives.

[[v1-46-31]]

^<<v1-46-31,31>>^ Depois disse José a seus irmãos, e à casa de seu pai: Eu subirei e informarei a Faraó, e lhe direi: Meus irmãos e a casa de meu pai, que estavam na terra de Canaã, vieram para mim.

[[v1-46-32]]

^<<v1-46-32,32>>^ Os homens são pastores, que se ocupam em apascentar gado; e trouxeram os seus rebanhos, o seu gado e tudo o que têm.

[[v1-46-33]]

^<<v1-46-33,33>>^ Quando, pois, Faraó vos chamar e vos perguntar: Que ocupação é a vossa?

[[v1-46-34]]

^<<v1-46-34,34>>^ respondereis: Nós, teus servos, temos sido pastores de gado desde a nossa mocidade até agora, tanto nós como nossos pais. Isso direis para que habiteis na terra de Gósen; porque todo pastor de ovelhas é abominação para os egípcios.

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]