include::./index.adoc[]

[[v1-32-0]]
=== Gênesis, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-32-1]]

^<<v1-32-1,1>>^ Jacó também seguiu o seu caminho; e encontraram-no os anjos de Deus.

[[v1-32-2]]

^<<v1-32-2,2>>^ Quando Jacó os viu, disse: Este é o exército de Deus. E chamou àquele lugar Maanaim.

[[v1-32-3]]

^<<v1-32-3,3>>^ Então enviou Jacó mensageiros diante de si a Esaú, seu irmão, à terra de Seir, o território de Edom,

[[v1-32-4]]

^<<v1-32-4,4>>^ tendo-lhes ordenado: Deste modo falareis a meu senhor Esaú: Assim diz Jacó, teu servo: Como peregrino morei com Labão, e com ele fiquei até agora;

[[v1-32-5]]

^<<v1-32-5,5>>^ e tenho bois e jumentos, rebanhos, servos e servas; e mando comunicar isso a meu senhor, para achar graça aos teus olhos.

[[v1-32-6]]

^<<v1-32-6,6>>^ Depois os mensageiros voltaram a Jacó, dizendo: Fomos ter com teu irmão Esaú; e, em verdade, vem ele para encontrar-te, e quatrocentos homens com ele.

[[v1-32-7]]

^<<v1-32-7,7>>^ Jacó teve muito medo e ficou aflito; dividiu em dois bandos o povo que estava com ele, bem como os rebanhos, os bois e os camelos;

[[v1-32-8]]

^<<v1-32-8,8>>^ pois dizia: Se Esaú vier a um bando e o ferir, o outro bando escapará.

[[v1-32-9]]

^<<v1-32-9,9>>^ Disse mais Jacó: o Deus de meu pai Abraão, Deus de meu pai Isaque, ó Senhor, que me disseste: Volta para a tua terra, e para a tua parentela, e eu te farei bem!

[[v1-32-10]]

^<<v1-32-10,10>>^ Não sou digno da menor de todas as tuas beneficências e de toda a fidelidade que tens usado para com teu servo; porque com o meu cajado passei este Jordão, e agora volto em dois bandos.

[[v1-32-11]]

^<<v1-32-11,11>>^ Livra-me, peço-te, da mão de meu irmão, da mão de Esaú, porque eu o temo; acaso não venha ele matar-me, e a mãe com os filhos.

[[v1-32-12]]

^<<v1-32-12,12>>^ Pois tu mesmo disseste: Certamente te farei bem, e farei a tua descendência como a areia do mar, que pela multidão não se pode contar.

[[v1-32-13]]

^<<v1-32-13,13>>^ Passou ali aquela noite; e do que tinha tomou um presente para seu irmão Esaú:

[[v1-32-14]]

^<<v1-32-14,14>>^ duzentas cabras e vinte bodes, duzentas ovelhas e vinte carneiros,

[[v1-32-15]]

^<<v1-32-15,15>>^ trinta camelas de leite com suas crias, quarenta vacas e dez touros, vinte jumentas e dez jumentinhos.

[[v1-32-16]]

^<<v1-32-16,16>>^ Então os entregou nas mãos dos seus servos, cada manada em separado; e disse a seus servos: Passai adiante de mim e ponde espaço entre manada e manada.

[[v1-32-17]]

^<<v1-32-17,17>>^ E ordenou ao primeiro, dizendo: Quando Esaú, meu irmão, te encontrar e te perguntar: De quem és, e para onde vais, e de quem são estes diante de ti?

[[v1-32-18]]

^<<v1-32-18,18>>^ Então responderás: São de teu servo Jacó, presente que envia a meu senhor, a Esaú, e eis que ele vem também atrás de nos.

[[v1-32-19]]

^<<v1-32-19,19>>^ Ordenou igualmente ao segundo, e ao terceiro, e a todos os que vinham atrás das manadas, dizendo: Desta maneira falareis a Esaú quando o achardes.

[[v1-32-20]]

^<<v1-32-20,20>>^ E direis também: Eis que o teu servo Jacó vem atrás de nós. Porque dizia: Aplacá-lo-ei com o presente, que vai adiante de mim, e depois verei a sua face; porventura ele me aceitará.

[[v1-32-21]]

^<<v1-32-21,21>>^ Foi, pois, o presente adiante dele; ele, porém, passou aquela noite no arraial.

[[v1-32-22]]

^<<v1-32-22,22>>^ Naquela mesma noite levantou-se e, tomando suas duas mulheres, suas duas servas e seus onze filhos, passou o vau de Jaboque.

[[v1-32-23]]

^<<v1-32-23,23>>^ Tomou-os, e fê-los passar o ribeiro, e fez passar tudo o que tinha.

[[v1-32-24]]

^<<v1-32-24,24>>^ Jacó, porém, ficou só; e lutava com ele um homem até o romper do dia.

[[v1-32-25]]

^<<v1-32-25,25>>^ Quando este viu que não prevalecia contra ele, tocou-lhe a juntura da coxa, e se deslocou a juntura da coxa de Jacó, enquanto lutava com ele.

[[v1-32-26]]

^<<v1-32-26,26>>^ Disse o homem: Deixa-me ir, porque já vem rompendo o dia. Jacó, porém, respondeu: Não te deixarei ir, se me não abençoares.

[[v1-32-27]]

^<<v1-32-27,27>>^ Perguntou-lhe, pois: Qual é o teu nome? E ele respondeu: Jacó.

[[v1-32-28]]

^<<v1-32-28,28>>^ Então disse: Não te chamarás mais Jacó, mas Israel; porque tens lutado com Deus e com os homens e tens prevalecido.

[[v1-32-29]]

^<<v1-32-29,29>>^ Perguntou-lhe Jacó: Dize-me, peço-te, o teu nome. Respondeu o homem: Por que perguntas pelo meu nome? E ali o abençoou.

[[v1-32-30]]

^<<v1-32-30,30>>^ Pelo que Jacó chamou ao lugar Peniel, dizendo: Porque tenho visto Deus face a face, e a minha vida foi preservada.

[[v1-32-31]]

^<<v1-32-31,31>>^ E nascia o sol, quando ele passou de Peniel; e coxeava de uma perna.

[[v1-32-32]]

^<<v1-32-32,32>>^ Por isso os filhos de Israel não comem até o dia de hoje o nervo do quadril, que está sobre a juntura da coxa, porquanto o homem tocou a juntura da coxa de Jacó no nervo do quadril.

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]