include::./index.adoc[]

[[v1-40-0]]
=== Gênesis, 40
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-40-1]]

^<<v1-40-1,1>>^ Depois destas coisas o copeiro do rei do Egito e o seu padeiro ofenderam o seu senhor, o rei do Egito.

[[v1-40-2]]

^<<v1-40-2,2>>^ Pelo que se indignou Faraó contra os seus dois oficiais, contra o copeiro-mor e contra o padeiro-mor;

[[v1-40-3]]

^<<v1-40-3,3>>^ e mandou detê-los na casa do capitão da guarda, no cárcere onde José estava preso;

[[v1-40-4]]

^<<v1-40-4,4>>^ e o capitão da guarda pô-los a cargo de José, que os servia. Assim estiveram por algum tempo em detenção.

[[v1-40-5]]

^<<v1-40-5,5>>^ Ora, tiveram ambos um sonho, cada um seu sonho na mesma noite, cada um conforme a interpretação do seu sonho, o copeiro e o padeiro do rei do Egito, que se achavam presos no cárcere:

[[v1-40-6]]

^<<v1-40-6,6>>^ Quando José veio a eles pela manhã, viu que estavam perturbados:

[[v1-40-7]]

^<<v1-40-7,7>>^ Perguntou, pois, a esses oficiais de Faraó, que com ele estavam no cárcere da casa de seu senhor, dizendo: Por que estão os vossos semblantes tão tristes hoje?

[[v1-40-8]]

^<<v1-40-8,8>>^ Responderam-lhe: Tivemos um sonho e ninguém há que o interprete. Pelo que lhes disse José: Porventura não pertencem a Deus as interpretações? Contai-mo, peço-vos.

[[v1-40-9]]

^<<v1-40-9,9>>^ Então contou o copeiro-mor o seu sonho a José, dizendo-lhe: Eis que em meu sonho havia uma vide diante de mim,

[[v1-40-10]]

^<<v1-40-10,10>>^ e na vide três sarmentos; e, tendo a vide brotado, saíam as suas flores, e os seus cachos produziam uvas maduras.

[[v1-40-11]]

^<<v1-40-11,11>>^ O copo de Faraó estava na minha mão; e, tomando as uvas, eu as espremia no copo de Faraó e entregava o copo na mão de Faraó.

[[v1-40-12]]

^<<v1-40-12,12>>^ Então disse-lhe José: Esta é a sua interpretação: Os três sarmentos são três dias;

[[v1-40-13]]

^<<v1-40-13,13>>^ dentro de três dias Faraó levantará a tua cabeça, e te restaurará ao teu cargo; e darás o copo de Faraó na sua mão, conforme o costume antigo, quando eras seu copeiro.

[[v1-40-14]]

^<<v1-40-14,14>>^ Mas lembra-te de mim, quando te for bem; usa, peço-te, de compaixão para comigo e faze menção de mim a Faraó e tira-me desta casa;

[[v1-40-15]]

^<<v1-40-15,15>>^ porque, na verdade, fui roubado da terra dos hebreus; e aqui também nada tenho feito para que me pusessem na masmorra.

[[v1-40-16]]

^<<v1-40-16,16>>^ Quando o padeiro-mor viu que a interpretação era boa, disse a José: Eu também sonhei, e eis que três cestos de pão branco estavam sobre a minha cabeça.

[[v1-40-17]]

^<<v1-40-17,17>>^ E no cesto mais alto havia para Faraó manjares de todas as qualidades que fazem os padeiros; e as aves os comiam do cesto que estava sobre a minha cabeça.

[[v1-40-18]]

^<<v1-40-18,18>>^ Então respondeu José: Esta é a interpretação do sonho: Os três cestos são três dias;

[[v1-40-19]]

^<<v1-40-19,19>>^ dentro de três dias tirará Faraó a tua cabeça, e te pendurará num madeiro, e as aves comerão a tua carne de sobre ti.

[[v1-40-20]]

^<<v1-40-20,20>>^ E aconteceu ao terceiro dia, o dia natalício de Faraó, que este deu um banquete a todos os seus servos; e levantou a cabeça do copeiro-mor, e a cabeça do padeiro-mor no meio dos seus servos;

[[v1-40-21]]

^<<v1-40-21,21>>^ e restaurou o copeiro-mor ao seu cargo de copeiro, e este deu o copo na mão de Faraó;

[[v1-40-22]]

^<<v1-40-22,22>>^ mas ao padeiro-mor enforcou, como José lhes havia interpretado.

[[v1-40-23]]

^<<v1-40-23,23>>^ O copeiro-mor, porém, não se lembrou de José, antes se esqueceu dele.

'''

xref:001-genesis/001-genesis-039.adoc#v1-39-0[&#60; Capítulo Anterior] | <<v1-40-0,Topo>> | xref:001-genesis/001-genesis-041.adoc#v1-41-0[Próximo Capítulo &#62;]