include::./index.adoc[]

[[v1-6-0]]
=== Gênesis, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v1-6-1]]

^<<v1-6-1,1>>^ Sucedeu que, quando os homens começaram a multiplicar-se sobre a terra, e lhes nasceram filhas,

[[v1-6-2]]

^<<v1-6-2,2>>^ viram os filhos de Deus que as filhas dos homens eram formosas; e tomaram para si mulheres de todas as que escolheram.

[[v1-6-3]]

^<<v1-6-3,3>>^ Então disse o Senhor: O meu Espírito não permanecerá para sempre no homem, porquanto ele é carne, mas os seus dias serão cento e vinte anos.

[[v1-6-4]]

^<<v1-6-4,4>>^ Naqueles dias estavam os nefilins na terra, e também depois, quando os filhos de Deus conheceram as filhas dos homens, as quais lhes deram filhos. Esses nefilins eram os valentes, os homens de renome, que houve na antigüidade.

[[v1-6-5]]

^<<v1-6-5,5>>^ Viu o Senhor que era grande a maldade do homem na terra, e que toda a imaginação dos pensamentos de seu coração era má continuamente.

[[v1-6-6]]

^<<v1-6-6,6>>^ Então arrependeu-se o Senhor de haver feito o homem na terra, e isso lhe pesou no coração

[[v1-6-7]]

^<<v1-6-7,7>>^ E disse o Senhor: Destruirei da face da terra o homem que criei, tanto o homem como o animal, os répteis e as aves do céu; porque me arrependo de os haver feito.

[[v1-6-8]]

^<<v1-6-8,8>>^ Noé, porém, achou graça aos olhos do Senhor.

[[v1-6-9]]

^<<v1-6-9,9>>^ Estas são as gerações de Noé. Era homem justo e perfeito em suas gerações, e andava com Deus.

[[v1-6-10]]

^<<v1-6-10,10>>^ Gerou Noé três filhos: Sem, Cam e Jafé.

[[v1-6-11]]

^<<v1-6-11,11>>^ A terra, porém, estava corrompida diante de Deus, e cheia de violência.

[[v1-6-12]]

^<<v1-6-12,12>>^ Viu Deus a terra, e eis que estava corrompida; porque toda a carne havia corrompido o seu caminho sobre a terra.

[[v1-6-13]]

^<<v1-6-13,13>>^ Então disse Deus a Noé: O fim de toda carne é chegado perante mim; porque a terra está cheia da violência dos homens; eis que os destruirei juntamente com a terra.

[[v1-6-14]]

^<<v1-6-14,14>>^ Faze para ti uma arca de madeira de gôfer: farás compartimentos na arca, e a revestirás de betume por dentro e por fora.

[[v1-6-15]]

^<<v1-6-15,15>>^ Desta maneira a farás: o comprimento da arca será de trezentos côvados, a sua largura de cinqüenta e a sua altura de trinta.

[[v1-6-16]]

^<<v1-6-16,16>>^ Farás na arca uma janela e lhe darás um côvado de altura; e a porta da arca porás no seu lado; fá-la-ás com andares, baixo, segundo e terceiro.

[[v1-6-17]]

^<<v1-6-17,17>>^ Porque eis que eu trago o dilúvio sobre a terra, para destruir, de debaixo do céu, toda a carne em que há espírito de vida; tudo o que há na terra expirará.

[[v1-6-18]]

^<<v1-6-18,18>>^ Mas contigo estabelecerei o meu pacto; entrarás na arca, tu e contigo teus filhos, tua mulher e as mulheres de teus filhos.

[[v1-6-19]]

^<<v1-6-19,19>>^ De tudo o que vive, de toda a carne, dois de cada espécie, farás entrar na arca, para os conservares vivos contigo; macho e fêmea serão.

[[v1-6-20]]

^<<v1-6-20,20>>^ Das aves segundo as suas espécies, do gado segundo as suas espécies, de todo réptil da terra segundo as suas espécies, dois de cada espécie virão a ti, para os conservares em vida.

[[v1-6-21]]

^<<v1-6-21,21>>^ Leva contigo de tudo o que se come, e ajunta-o para ti; e te será para alimento, a ti e a eles.

[[v1-6-22]]

^<<v1-6-22,22>>^ Assim fez Noé; segundo tudo o que Deus lhe mandou, assim o fez.

'''

xref:001-genesis/001-genesis-005.adoc#v1-5-0[&#60; Capítulo Anterior] | <<v1-6-0,Topo>> | xref:001-genesis/001-genesis-007.adoc#v1-7-0[Próximo Capítulo &#62;]