include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v51-4-1]]

^<<v51-4-1,1>>^ Vós, senhores, dai a vossos servos o que é de justiça e eqüidade, sabendo que também vós tendes um Senhor no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Perseverai na oração, velando nela com ações de graças,

[[v51-4-3]]

^<<v51-4-3,3>>^ orando ao mesmo tempo também por nós, para que Deus nos abra uma porta à palavra, a fim de falarmos o mistério de Cristo, pelo qual também estou preso,

[[v51-4-4]]

^<<v51-4-4,4>>^ para que eu o manifeste como devo falar.

[[v51-4-5]]

^<<v51-4-5,5>>^ Andai em sabedoria para com os que estão de fora, usando bem cada oportunidade.

[[v51-4-6]]

^<<v51-4-6,6>>^ A vossa palavra seja sempre com graça, temperada com sal, para saberdes como deveis responder a cada um.

[[v51-4-7]]

^<<v51-4-7,7>>^ Tíquico, o irmão amado, fiel ministro e conservo no Senhor, vos fará conhecer a minha situação;

[[v51-4-8]]

^<<v51-4-8,8>>^ o qual vos envio para este mesmo fim, para que saibais o nosso estado e ele conforte os vossos corações,

[[v51-4-9]]

^<<v51-4-9,9>>^ juntamente com Onésimo, fiel e amado irmão, que é um de vós; eles vos farão saber tudo o que aqui se passa.

[[v51-4-10]]

^<<v51-4-10,10>>^ Saúda-vos Aristarco, meu companheiro de prisão, e Marcos, o primo de Barnabé &#123;a respeito do qual recebestes instruções; se for ter convosco, recebei-o&#125;,

[[v51-4-11]]

^<<v51-4-11,11>>^ e Jesus, que se chama Justo, sendo unicamente estes, dentre a circuncisão, os meus cooperadores no reino de Deus; os quais têm sido para mim uma consolação.

[[v51-4-12]]

^<<v51-4-12,12>>^ Saúda-vos Epafras, que é um de vós, servo de Cristo Jesus, e que sempre luta por vós nas suas orações, para que permaneçais perfeitos e plenamente seguros em toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ Pois dou-lhe testemunho de que tem grande zelo por vós, como também pelos que estão em Laodicéia, e pelos que estão em Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Saúda-vos Lucas, o médico amado, e Demas.

[[v51-4-15]]

^<<v51-4-15,15>>^ Saudai aos irmãos que estão em Laodicéia, e a Ninfas e a igreja que está em sua casa.

[[v51-4-16]]

^<<v51-4-16,16>>^ Depois que for lida esta carta entre vós, fazei que o seja também na igreja dos laodicenses; e a de Laodicéia lede-a vós também.

[[v51-4-17]]

^<<v51-4-17,17>>^ E dizei a Arquipo: Cuida do ministério que recebestes no Senhor, para o cumprires.

[[v51-4-18]]

^<<v51-4-18,18>>^ Esta saudação é de próprio punho, de Paulo. Lembrai-vos das minhas cadeias. A graça seja convosco.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]