include::./index.adoc[]

[[v51-2-0]]
=== Colossenses, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v51-2-1]]

^<<v51-2-1,1>>^ Pois quero que saibais quão grande luta tenho por vós, e pelos que estão em Laodicéia, e por quantos não viram a minha pessoa;

[[v51-2-2]]

^<<v51-2-2,2>>^ para que os seus corações sejam animados, estando unidos em amor, e enriquecidos da plenitude do entendimento para o pleno conhecimento do mistério de Deus-Cristo,

[[v51-2-3]]

^<<v51-2-3,3>>^ no qual estão escondidos todos os tesouros da sabedoria e da ciência.

[[v51-2-4]]

^<<v51-2-4,4>>^ Digo isto, para que ninguém vos engane com palavras persuasivas.

[[v51-2-5]]

^<<v51-2-5,5>>^ Porque ainda que eu esteja ausente quanto ao corpo, contudo em espírito estou convosco, regozijando-me, e vendo a vossa ordem e a firmeza da vossa fé em Cristo.

[[v51-2-6]]

^<<v51-2-6,6>>^ Portanto, assim como recebestes a Cristo Jesus, o Senhor, assim também nele andai,

[[v51-2-7]]

^<<v51-2-7,7>>^ arraigados e edificados nele, e confirmados na fé, assim como fostes ensinados, abundando em ação de graças.

[[v51-2-8]]

^<<v51-2-8,8>>^ Tendo cuidado para que ninguém vos faça presa sua, por meio de filosofias e vãs sutilezas, segundo a tradição dos homens, segundo os rudimentos do mundo, e não segundo Cristo;

[[v51-2-9]]

^<<v51-2-9,9>>^ porque nele habita corporalmente toda a plenitude da divindade,

[[v51-2-10]]

^<<v51-2-10,10>>^ e tendes a vossa plenitude nele, que é a cabeça de todo principado e potestade,

[[v51-2-11]]

^<<v51-2-11,11>>^ no qual também fostes circuncidados com a circuncisão não feita por mãos no despojar do corpo da carne, a saber, a circuncisão de Cristo;

[[v51-2-12]]

^<<v51-2-12,12>>^ tendo sido sepultados com ele no batismo, no qual também fostes ressuscitados pela fé no poder de Deus, que o ressuscitou dentre os mortos;

[[v51-2-13]]

^<<v51-2-13,13>>^ e a vós, quando estáveis mortos nos vossos delitos e na incircuncisão da vossa carne, vos vivificou juntamente com ele, perdoando-nos todos os delitos;

[[v51-2-14]]

^<<v51-2-14,14>>^ e havendo riscado o escrito de dívida que havia contra nós nas suas ordenanças, o qual nos era contrário, removeu-o do meio de nós, cravando-o na cruz;

[[v51-2-15]]

^<<v51-2-15,15>>^ e, tendo despojado os principados e potestades, os exibiu publicamente e deles triunfou na mesma cruz.

[[v51-2-16]]

^<<v51-2-16,16>>^ Ninguém, pois, vos julgue pelo comer, ou pelo beber, ou por causa de dias de festa, ou de lua nova, ou de sábados,

[[v51-2-17]]

^<<v51-2-17,17>>^ que são sombras das coisas vindouras; mas o corpo é de Cristo.

[[v51-2-18]]

^<<v51-2-18,18>>^ Ninguém atue como árbitro contra vós, afetando humildade ou culto aos anjos, firmando-se em coisas que tenha visto, inchado vãmente pelo seu entendimento carnal,

[[v51-2-19]]

^<<v51-2-19,19>>^ e não retendo a Cabeça, da qual todo o corpo, provido e organizado pelas juntas e ligaduras, vai crescendo com o aumento concedido por Deus.

[[v51-2-20]]

^<<v51-2-20,20>>^ Se morrestes com Cristo quanto aos rudimentos do mundo, por que vos sujeitais ainda a ordenanças, como se vivêsseis no mundo,

[[v51-2-21]]

^<<v51-2-21,21>>^ tais como: não toques, não proves, não manuseies

[[v51-2-22]]

^<<v51-2-22,22>>^ &#123;as quais coisas todas hão de perecer pelo uso&#125;, segundo os preceitos e doutrinas dos homens?

[[v51-2-23]]

^<<v51-2-23,23>>^ As quais têm, na verdade, alguma aparência de sabedoria em culto voluntário, humildade fingida, e severidade para com o corpo, mas não têm valor algum no combate contra a satisfação da carne.

'''

xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[Próximo Capítulo &#62;]