include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v51-1-1]]

^<<v51-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo,

[[v51-1-2]]

^<<v51-1-2,2>>^ aos santos e fiéis irmãos em Cristo que estão em Colossos: Graças a vós, e paz da parte de Deus nosso Pai.

[[v51-1-3]]

^<<v51-1-3,3>>^ Graças damos a Deus, Pai de nosso Senhor Jesus Cristo, orando sempre por vós,

[[v51-1-4]]

^<<v51-1-4,4>>^ desde que ouvimos falar da vossa fé em Cristo Jesus, e do amor que tendes a todos os santos,

[[v51-1-5]]

^<<v51-1-5,5>>^ por causa da esperança que vos está reservada nos céus, da qual antes ouvistes pela palavra da verdade do evangelho,

[[v51-1-6]]

^<<v51-1-6,6>>^ que já chegou a vós, como também está em todo o mundo, frutificando e crescendo, assim como entre vós desde o dia em que ouvistes e conhecestes a graça de Deus em verdade,

[[v51-1-7]]

^<<v51-1-7,7>>^ segundo aprendestes de Epafras, nosso amado conservo, que por nós é fiel ministro de Cristo.

[[v51-1-8]]

^<<v51-1-8,8>>^ O qual também nos declarou o vosso amor no Espírito.

[[v51-1-9]]

^<<v51-1-9,9>>^ Por esta razão, nós também, desde o dia em que ouvimos, não cessamos de orar por vós, e de pedir que sejais cheios do pleno conhecimento da sua vontade, em toda a sabedoria e entendimento espiritual;

[[v51-1-10]]

^<<v51-1-10,10>>^ para que possais andar de maneira digna do Senhor, agradando-lhe em tudo, frutificando em toda boa obra, e crescendo no conhecimento de Deus,

[[v51-1-11]]

^<<v51-1-11,11>>^ corroborados com toda a fortaleza, segundo o poder da sua glória, para toda a perseverança e longanimidade com gozo;

[[v51-1-12]]

^<<v51-1-12,12>>^ dando graças ao Pai que vos fez idôneos para participar da herança dos santos na luz,

[[v51-1-13]]

^<<v51-1-13,13>>^ e que nos tirou do poder das trevas, e nos transportou para o reino do seu Filho amado;

[[v51-1-14]]

^<<v51-1-14,14>>^ em quem temos a redenção, a saber, a remissão dos pecados;

[[v51-1-15]]

^<<v51-1-15,15>>^ o qual é imagem do Deus invisível, o primogênito de toda a criação;

[[v51-1-16]]

^<<v51-1-16,16>>^ porque nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades; tudo foi criado por ele e para ele.

[[v51-1-17]]

^<<v51-1-17,17>>^ Ele é antes de todas as coisas, e nele subsistem todas as coisas;

[[v51-1-18]]

^<<v51-1-18,18>>^ também ele é a cabeça do corpo, da igreja; é o princípio, o primogênito dentre os mortos, para que em tudo tenha a preeminência,

[[v51-1-19]]

^<<v51-1-19,19>>^ porque aprouve a Deus que nele habitasse toda a plenitude,

[[v51-1-20]]

^<<v51-1-20,20>>^ e que, havendo por ele feito a paz pelo sangue da sua cruz, por meio dele reconciliasse consigo mesmo todas as coisas, tanto as que estão na terra como as que estão nos céus.

[[v51-1-21]]

^<<v51-1-21,21>>^ A vós também, que outrora éreis estranhos, e inimigos no entendimento pelas vossas obras más,

[[v51-1-22]]

^<<v51-1-22,22>>^ agora contudo vos reconciliou no corpo da sua carne, pela morte, a fim de perante ele vos apresentar santos, sem defeito e irrepreensíveis,

[[v51-1-23]]

^<<v51-1-23,23>>^ se é que permaneceis na fé, fundados e firmes, não vos deixando apartar da esperança do evangelho que ouvistes, e que foi pregado a toda criatura que há debaixo do céu, e do qual eu, Paulo, fui constituído ministro.

[[v51-1-24]]

^<<v51-1-24,24>>^ Agora me regozijo no meio dos meus sofrimentos por vós, e cumpro na minha carne o que resta das aflições de Cristo, por amor do seu corpo, que é a igreja;

[[v51-1-25]]

^<<v51-1-25,25>>^ da qual eu fui constituído ministro segundo a dispensação de Deus, que me foi concedida para convosco, a fim de cumprir a palavra de Deus,

[[v51-1-26]]

^<<v51-1-26,26>>^ o mistério que esteve oculto dos séculos, e das gerações; mas agora foi manifesto aos seus santos,

[[v51-1-27]]

^<<v51-1-27,27>>^ a quem Deus quis fazer conhecer quais são as riquezas da glória deste mistério entre os gentios, que é Cristo em vós, a esperança da glória;

[[v51-1-28]]

^<<v51-1-28,28>>^ o qual nós anunciamos, admoestando a todo homem, e ensinando a todo homem em toda a sabedoria, para que apresentemos todo homem perfeito em Cristo;

[[v51-1-29]]

^<<v51-1-29,29>>^ para isso também trabalho, lutando segundo a sua eficácia, que opera em mim poderosamente.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]