include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v35-3-1]]

^<<v35-3-1,1>>^ Oração do profeta Habacuque, à moda de sigionote.

[[v35-3-2]]

^<<v35-3-2,2>>^ Eu ouvi, Senhor, a tua fama, e temi; aviva, ó Senhor, a tua obra no meio dos anos; faze que ela seja conhecida no meio dos anos; na ira lembra-te da misericórdia.

[[v35-3-3]]

^<<v35-3-3,3>>^ Deus veio de Temã, e do monte Parã o Santo. &#91;Selá&#93;. A sua glória cobriu os céus, e a terra encheu-se do seu louvor.

[[v35-3-4]]

^<<v35-3-4,4>>^ E o seu resplendor é como a luz, da sua mão saem raios brilhantes, e ali está o esconderijo da sua força.

[[v35-3-5]]

^<<v35-3-5,5>>^ Adiante dele vai a peste, e por detrás a praga ardente.

[[v35-3-6]]

^<<v35-3-6,6>>^ Pára, e mede a terra; olha, e sacode as nações; e os montes perpétuos se espalham, os outeiros eternos se abatem; assim é o seu andar desde a eternidade.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vejo as tendas de Cusã em aflição; tremem as cortinas da terra de Midiã.

[[v35-3-8]]

^<<v35-3-8,8>>^ Acaso é contra os rios que o Senhor está irado? E contra os ribeiros a tua ira, ou contra o mar o teu furor, visto que andas montado nos teus cavalos, nos teus carros de vitória?

[[v35-3-9]]

^<<v35-3-9,9>>^ Descoberto de todo está o teu arco; a tua aljava está cheia de flechas. &#123;Selá&#125; Tu fendes a terra com rios.

[[v35-3-10]]

^<<v35-3-10,10>>^ Os montes te vêem, e se contorcem; inundação das águas passa; o abismo faz ouvir a sua voz, e levanta bem alto as suas mãos.

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol e a lua param nas suas moradas, ante o lampejo das tuas flechas volantes, e ao brilho intenso da tua lança fulgurante.

[[v35-3-12]]

^<<v35-3-12,12>>^ com indignação marchas pela terra, com ira trilhas as nações.

[[v35-3-13]]

^<<v35-3-13,13>>^ Tu sais para o socorro do teu povo, para salvamento dos teus ungidos. Tu despedaças a cabeça da casa do ímpio, descobrindo-lhe de todo os fundamentos. &#123;selá&#125;

[[v35-3-14]]

^<<v35-3-14,14>>^ Traspassas a cabeça dos seus guerreiros com as suas próprias lanças; eles me acometem como turbilhão para me espalharem; alegram-se, como se estivessem para devorar o pobre em segredo.

[[v35-3-15]]

^<<v35-3-15,15>>^ Tu com os teus cavalos marchas pelo mar, pelo montão de grandes águas.

[[v35-3-16]]

^<<v35-3-16,16>>^ Ouvindo-o eu, o meu ventre se comove, ao seu ruído tremem os meus lábios; entra a podridão nos meus ossos, vacilam os meus passos; em silêncio, pois, aguardarei o dia da angústia que há de vir sobre o povo

[[v35-3-17]]

^<<v35-3-17,17>>^ Ainda que a figueira não floresça, nem haja fruto nas vides; ainda que falhe o produto da oliveira, e os campos não produzam mantimento; ainda que o rebanho seja exterminado da malhada e nos currais não haja gado.

[[v35-3-18]]

^<<v35-3-18,18>>^ todavia eu me alegrarei no Senhor, exultarei no Deus da minha salvação.

[[v35-3-19]]

^<<v35-3-19,19>>^ O Senhor Deus é minha força, ele fará os meus pés como os da corça, e me fará andar sobre os meus lugares altos. &#123;Ao regente de música. Para instrumentos de cordas.&#125;

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]