include::./index.adoc[]

[[v35-2-0]]
=== Habacuque, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v35-2-1]]

^<<v35-2-1,1>>^ Sobre a minha torre de vigia me colocarei e sobre a fortaleza me apresentarei e vigiarei, para ver o que me dirá, e o que eu responderei no tocante, a minha queixa.

[[v35-2-2]]

^<<v35-2-2,2>>^ Então o Senhor me respondeu , e disse: Escreve a visão e torna-se bem legível sobre tábuas, para que a possa ler quem passa correndo.

[[v35-2-3]]

^<<v35-2-3,3>>^ Pois a visão é ainda para o tempo determinado, e até o fim falará, e não mentirá. Ainda que se demore, espera-o; porque certamente virá, não tardará.

[[v35-2-4]]

^<<v35-2-4,4>>^ Eis o soberbo! A sua alma não é reta nele; mas o justo pela sua fé viverá.

[[v35-2-5]]

^<<v35-2-5,5>>^ Além disso, o vinho é traidor; o homem soberbo não permanece. Ele alarga como o Seol o seu desejo; como a morte, nunca se pode fartar, mas ajunta a si todas as nações, e congrega a si todos os povos.

[[v35-2-6]]

^<<v35-2-6,6>>^ Não levantarão, pois, todos estes contra ele um provérbio e um dito zombador? E dirão: Ai daquele que acumula o que não é seu! &#123;até quando?&#125; e daquele que se carrega a si mesmo de penhores!

[[v35-2-7]]

^<<v35-2-7,7>>^ Não se levantarão de repente os teus credores? e não despertarão os que te farão tremer? Então lhes servirás tu de despojo.

[[v35-2-8]]

^<<v35-2-8,8>>^ Visto como despojaste muitas nações, os demais povos te despojarão a ti, por causa do sangue dos homens, e da violência para com á terra, a cidade, e todos os que nela habitam.

[[v35-2-9]]

^<<v35-2-9,9>>^ Ai daquele que adquire para a sua casa lucros criminosos, para pôr o seu ninho no alto, a fim de se livrar das garras da calamidade!

[[v35-2-10]]

^<<v35-2-10,10>>^ Vergonha maquinaste para a tua casa; destruindo tu a muitos povos, pecaste contra a tua alma.

[[v35-2-11]]

^<<v35-2-11,11>>^ pois a pedra clamará da parede, e a trave lhe responderá do madeiramento.

[[v35-2-12]]

^<<v35-2-12,12>>^ Ai daquele que edifica a cidade com sangue, e que funda a cidade com iniqüidade!

[[v35-2-13]]

^<<v35-2-13,13>>^ Acaso não procede do Senhor dos exércitos que os povos trabalhem para o fogo e as nações se cansem em vão?

[[v35-2-14]]

^<<v35-2-14,14>>^ Pois a terra se encherá do conhecimento da glória do Senhor, como as águas cobrem o mar.

[[v35-2-15]]

^<<v35-2-15,15>>^ Ai daquele que da de beber ao seu próximo, adicionando à bebida o seu furor, e que o embebeda para ver a sua nudez!

[[v35-2-16]]

^<<v35-2-16,16>>^ Serás farto de ignomínia em lugar de honra; bebe tu também, e sê como um incurcunciso; o cálice da mão direita do Senhor se chegará a ti, e ignomínia cairá sobre a tua glória.

[[v35-2-17]]

^<<v35-2-17,17>>^ Pois a violência cometida contra o Líbano te cobrirá, e bem assim a destruição das feras te amedrontará por causa do sangue dos homens, e da violência para com a terra, a cidade e todos os que nele habitam.

[[v35-2-18]]

^<<v35-2-18,18>>^ Que aproveita a imagem esculpida, tendo-a esculpido o seu artífice? a imagem de fundição, que ensina a mentira? Pois o artífice confia na sua própria obra, quando forma ídolos mudos.

[[v35-2-19]]

^<<v35-2-19,19>>^ Ai daquele que diz ao pau: Acorda; e à pedra muda: Desperta! Pode isso ensinar? Eis que está coberto de ouro e de prata, e dentro dele não há espírito algum.

[[v35-2-20]]

^<<v35-2-20,20>>^ Mas o Senhor está no seu santo templo; cale-se diante dele toda a terra; cale-se diante dele toda a terra.

'''

xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[Próximo Capítulo &#62;]