include::./index.adoc[]

[[v33-2-0]]
=== Miquéias, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v33-2-1]]

^<<v33-2-1,1>>^ Ai daqueles que nas suas camas maquinam a iniqüidade e planejam o mal! quando raia o dia, põem-no por obra, pois está no poder da sua mão.

[[v33-2-2]]

^<<v33-2-2,2>>^ E cobiçam campos, e os arrebatam, e casas, e as tomam; assim fazem violência a um homem e à sua casa, a uma pessoa e à sua herança.

[[v33-2-3]]

^<<v33-2-3,3>>^ Portanto, assim diz o Senhor. Eis que contra esta família maquino um mal, de que não retirareis os vossos pescoços; e não andareis arrogantemente; porque o tempo será mau.

[[v33-2-4]]

^<<v33-2-4,4>>^ Naquele dia surgirá contra vós um motejo, e se levantará pranto lastimoso, dizendo: Nós estamos inteiramente despojados; a porção do meu povo ele a troca; como ele a remove de mim! aos rebeldes reparte os nossos campos.

[[v33-2-5]]

^<<v33-2-5,5>>^ Portanto, não terás tu na congregação do Senhor quem lance o cordel pela sorte

[[v33-2-6]]

^<<v33-2-6,6>>^ Não profetizeis; assim profetizam eles, não se deve profetizar tais coisas; não nos alcançará o opróbrio.

[[v33-2-7]]

^<<v33-2-7,7>>^ Acaso dir-se-á isso, ó casa de Jacó: tem-se restringido o Espírito do Senhor? são estas as suas obras? e não é assim que fazem bem as minhas palavras ao que anda retamente?

[[v33-2-8]]

^<<v33-2-8,8>>^ Mas há pouco se levantou o meu povo como um inimigo; de sobre a vestidura arrancais o manto aos que passam seguros, como homens contrários à guerra.

[[v33-2-9]]

^<<v33-2-9,9>>^ As mulheres do meu povo, vós as lançais das suas casas agradáveis; dos seus filhinhos tirais para sempre a minha glória.

[[v33-2-10]]

^<<v33-2-10,10>>^ Levantai-vos, e ide-vos, pois este não é lugar de descanso; por causa da imundícia que traz destruição, sim, destruição enorme.

[[v33-2-11]]

^<<v33-2-11,11>>^ Se algum homem, andando em espírito de falsidade, mentir, dizendo: Eu te profetizarei acerca do vinho e da bebida forte; será esse tal o profeta deste povo.

[[v33-2-12]]

^<<v33-2-12,12>>^ Certamente te ajuntarei todo, ó Jacó; certamente congregarei o restante de Israel; pô-los-ei todos juntos, como ovelhas no curral, como rebanho no meio do seu pasto; farão estrondo por causa da multidão dos homens.

[[v33-2-13]]

^<<v33-2-13,13>>^ Subirá diante deles aquele que abre o caminho; eles romperão, e entrarão pela porta, e sairão por ela; e o rei irá adiante deles, e o Senhor à testa deles.

'''

xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[Próximo Capítulo &#62;]