include::./index.adoc[]

[[v33-4-0]]
=== Miquéias, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v33-4-1]]

^<<v33-4-1,1>>^ Mas nos últimos dias acontecerá que o monte da casa do Senhor será estabelecido como o mais alto dos montes, e se exalçará sobre os outeiros, e a ele concorram os povos.

[[v33-4-2]]

^<<v33-4-2,2>>^ E irão muitas nações, e dirão: Vinde, e subamos ao monte do Senhor, e à casa do Deus de Jacó, para que nos ensine os seus caminhos, de sorte que andemos nas suas veredas; porque de Sião sairá a lei, e de Jerusalém a palavra do Senhor.

[[v33-4-3]]

^<<v33-4-3,3>>^ E julgará entre muitos povos, e arbitrará entre nações poderosas e longínquas; e converterão as suas espadas em relhas de arado, e as suas lanças em podadeiras; uma nação não levantará a espada contra outra nação, nem aprenderão mais a guerra.

[[v33-4-4]]

^<<v33-4-4,4>>^ Mas assentar-se-á cada um debaixo da sua videira, e debaixo da sua figueira, e não haverá quem os espante, porque a boca do Senhor dos exércitos o disse.

[[v33-4-5]]

^<<v33-4-5,5>>^ Pois todos os povos andam, cada um em nome do seu deus; mas nós andaremos para todo o sempre em o nome do Senhor nosso Deus.

[[v33-4-6]]

^<<v33-4-6,6>>^ Naquele dia, diz o Senhor, congregarei a que coxeava, e recolherei a que tinha sido expulsa, e a que eu afligi.

[[v33-4-7]]

^<<v33-4-7,7>>^ E da que coxeava farei um resto, e da que tinha sido arrojada para longe, uma nação poderosa; e o Senhor reinará sobre eles no monte Sião, desde agora e para sempre.

[[v33-4-8]]

^<<v33-4-8,8>>^ E a ti, ó torre do rebanho, outeiro da filha de Sião, a ti virá, sim, a ti virá o primeiro domínio, o reino da filha de Jerusalém.

[[v33-4-9]]

^<<v33-4-9,9>>^ E agora, por que fazes tão grande pranto? Não há em ti rei? pereceu o teu conselheiro, de modo que se apoderaram de ti dores, como da que está de parto,

[[v33-4-10]]

^<<v33-4-10,10>>^ Sofre dores e trabalha, ó filha de Sião, como a que está de parto; porque agora sairás da cidade, e morarás no campo, e virás até Babilônia. Ali, porém serás livrada; ali te remirá o Senhor da mão de teus inimigos.

[[v33-4-11]]

^<<v33-4-11,11>>^ Agora se congregaram muitas nações contra ti, que dizem: Seja ela profanada, e vejam o nossos olhos o seu desejo sobre Sião.

[[v33-4-12]]

^<<v33-4-12,12>>^ Mas, não sabem os pensamentos do Senhor, nem entendem o seu conselho; porque as ajuntou como gavelas para dentro da eira.

[[v33-4-13]]

^<<v33-4-13,13>>^ Levanta-te, e debulha, ó filha de Sião, porque eu farei de ferro o teu chifre, e de bronze as tuas unhas; e esmiuçarás a muitos povos; e dedicarás o seu ganho ao Senhor, e os seus bens ao Senhor de toda a terra.

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]