include::./index.adoc[]

[[v33-6-0]]
=== Miquéias, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v33-6-1]]

^<<v33-6-1,1>>^ Ouvi agora o que diz o Senhor: Levanta-te, contende perante os montes, e ouçam os outeiros a tua voz.

[[v33-6-2]]

^<<v33-6-2,2>>^ Ouvi, montes, a demanda do Senhor, e vós, fundamentos duradouros da terra; porque o Senhor tem uma demanda com o seu povo e com Israel entrará em juízo.

[[v33-6-3]]

^<<v33-6-3,3>>^ Ó povo meu, que é que te tenho feito? e em que te enfadei? testifica contra mim.

[[v33-6-4]]

^<<v33-6-4,4>>^ Pois te fiz subir da terra do Egito, e da casa da servidão te remi; e enviei adiante de ti a Moisés, Arão e Miriã.

[[v33-6-5]]

^<<v33-6-5,5>>^ Povo meu, lembra-te agora da consulta de Balaque, rei de Meabe, e do que lhe respondeu Balaão, filho de Beor, e do que sucedeu desde Sitini até Gilgal, para que conheças as justiças do Senhor.

[[v33-6-6]]

^<<v33-6-6,6>>^ Com que me apresentarei diante do Senhor, e me prostrarei perante o Deus excelso? Apresentar-me-ei diante dele com holocausto, com bezerros de um ano?

[[v33-6-7]]

^<<v33-6-7,7>>^ Agradar-se-á o Senhor de milhares de carneiros, ou de miríades de ribeiros de azeite? Darei o meu primogênito pela minha transgressão, o fruto das minhas entranhas pelo pecado da minha alma?

[[v33-6-8]]

^<<v33-6-8,8>>^ Ele te declarou, ó homem, o que é bom; e que é o que o Senhor requer de ti, senão que pratiques a justiça, e ames a benevolência, e andes humildemente com o teu Deus?

[[v33-6-9]]

^<<v33-6-9,9>>^ A voz do Senhor clama à cidade, e o que é sábio temerá o teu nome. Escutai a vara, e quem a ordenou.

[[v33-6-10]]

^<<v33-6-10,10>>^ Porventura ainda há na casa do ímpio tesouros de impiedade? e a efa desfalcada, que é detestável?

[[v33-6-11]]

^<<v33-6-11,11>>^ Justificarei ao que tem balanças falsas, e uma bolsa de pesos enganosos?

[[v33-6-12]]

^<<v33-6-12,12>>^ Pois os ricos da cidade estão cheios de violência, e os seus habitantes falam mentiras, e a língua deles é enganosa na sua boca.

[[v33-6-13]]

^<<v33-6-13,13>>^ Assim eu também te enfraquecerei, ferindo-te e assolando-te, por causa dos teus pecados.

[[v33-6-14]]

^<<v33-6-14,14>>^ Tu comerás, mas não te fartarás; e a tua fome estará sempre contigo; removerás os teus bens, mas nada livrarás; e aquilo que livrares, eu o entregarei à espada.

[[v33-6-15]]

^<<v33-6-15,15>>^ Tu semearás, mas não segarás; pisarás a azeitona, mas não te ungirás de azeite; e pisarás a vindima, mas não beberás o vinho.

[[v33-6-16]]

^<<v33-6-16,16>>^ Porque se observam os estatutos de Onri, e todas as obras da casa de Acabe, e vós andais nos conselhos deles; para que eu faça de ti uma desolação, e dos seus habitantes um assobio. Assim trareis sobre vós o opróbrio do meu povo.

'''

xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[Próximo Capítulo &#62;]