include::./index.adoc[]

[[v33-3-0]]
=== Miquéias, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v33-3-1]]

^<<v33-3-1,1>>^ E disse eu: Ouvi, peço-vos, ó chefes de Jacó, e vós, ó príncipes da casa de Israel: não é a vós que pertence saber a justiça?

[[v33-3-2]]

^<<v33-3-2,2>>^ A vós que aborreceis o bem, e amais o mal, que arrancais a pele de cima deles, e a carne de cima dos seus ossos,

[[v33-3-3]]

^<<v33-3-3,3>>^ os que também comeis a carne do meu povo e lhes arrancais a pele, e lhes esmiuçais os ossos, e os repartis em pedaços como para a panela e como carne dentro do caldeirão.

[[v33-3-4]]

^<<v33-3-4,4>>^ Então clamarão ao Senhor; ele, porém, não lhes responderá, antes esconderá deles a sua face naquele tempo, conforme eles fizeram mal nas suas obras.

[[v33-3-5]]

^<<v33-3-5,5>>^ Assim diz o Senhor a respeito dos profetas que fazem errar o meu povo, que clamam: Paz! enquanto têm o que comer, mas preparam a guerra contra aquele que nada lhes mete na boca.

[[v33-3-6]]

^<<v33-3-6,6>>^ Portanto se vos fará noite sem visão; e trevas sem adivinhação haverá para vós. Assim se porá o sol sobre os profetas, e sobre eles, obscurecerá o dia.

[[v33-3-7]]

^<<v33-3-7,7>>^ E os videntes se envergonharão, e os adivinhadores se confundirão; sim, todos eles cobrirão os seus lábios, porque não haverá resposta de Deus.

[[v33-3-8]]

^<<v33-3-8,8>>^ Quanto a mim, estou cheio do poder do Espírito do Senhor, assim como de justiça e de coragem, para declarar a Jacó a sua transgressão e a Israel o seu pecado.

[[v33-3-9]]

^<<v33-3-9,9>>^ Ouvi agora isto, vós chefes da casa de Jacó, e vós governantes da casa de Israel, que abominais a justiça e perverteis tudo o que é direito,

[[v33-3-10]]

^<<v33-3-10,10>>^ edificando a Sião com sangue, e a Jerusalém com iniqüidade.

[[v33-3-11]]

^<<v33-3-11,11>>^ Os seus chefes dão as sentenças por peitas, e os seus sacerdotes ensinam por interesse, e os seus profetas adivinham por dinheiro; e ainda se encostam ao Senhor, dizendo: Não está o Senhor no meio de nós? nenhum mal nos sobrevirá.

[[v33-3-12]]

^<<v33-3-12,12>>^ Portanto, por causa de vós, Sião será lavrada como um campo, e Jerusalém se tornará em montões de pedras, e o monte desta casa em lugares altos dum bosque.

'''

xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[Próximo Capítulo &#62;]