include::./index.adoc[]

[[v33-7-0]]
=== Miquéias, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v33-7-1]]

^<<v33-7-1,1>>^ Ai de mim! porque estou feito como quando são colhidas as frutas do verão, como os rabiscos da vindima; não há cacho de uvas para comer, nem figo temporão que a minha alma deseja.

[[v33-7-2]]

^<<v33-7-2,2>>^ Pereceu da terra o homem piedoso; e entre os homens não há um que seja reto; todos armam ciladas para sangue; caça cada um a seu irmão com uma rede.

[[v33-7-3]]

^<<v33-7-3,3>>^ As suas mãos estão sobre o mal para o fazerem diligentemente; o príncipe e o juiz exigem a peita, e o grande manifesta o desejo mau da sua alma; e assim todos eles tecem o mal.

[[v33-7-4]]

^<<v33-7-4,4>>^ O melhor deles é como um espinho; o mais reto é pior do que uma sebe de espinhos. Veio o dia dos seus vigias, a saber, a sua punição; agora começará a sua confusão.

[[v33-7-5]]

^<<v33-7-5,5>>^ Não creiais no amigo, nem confieis no companheiro; guarda as portas da tua boca daquela que repousa no teu seio.

[[v33-7-6]]

^<<v33-7-6,6>>^ Pois o filho despreza o pai, a filha se levanta contra a mãe, a nora contra a sogra; os inimigos do homem são os da própria casa.

[[v33-7-7]]

^<<v33-7-7,7>>^ Eu, porém, confiarei no Senhor; esperarei no Deus da minha salvação. O meu Deus me ouvirá.

[[v33-7-8]]

^<<v33-7-8,8>>^ Não te alegres, inimiga minha, a meu respeito; quando eu cair, levantar-me-ei; quando me sentar nas trevas, o Senhor será a minha luz.

[[v33-7-9]]

^<<v33-7-9,9>>^ Sofrerei a indignação do Senhor, porque tenho pecado contra ele; até que ele julgue a minha causa, e execute o meu direito. Ele me tirará para a luz, e eu verei a sua justiça.

[[v33-7-10]]

^<<v33-7-10,10>>^ E a minha inimiga verá isso, e cobri-la-á a confusão, a ela que me disse: Onde está o Senhor teu Deus? Os meus olhos a contemplarão; agora ela será pisada como a lama das ruas.

[[v33-7-11]]

^<<v33-7-11,11>>^ É dia de reedificar os teus muros! Naquele dia será dilatado grandemente o teu termo.

[[v33-7-12]]

^<<v33-7-12,12>>^ Naquele dia virão a ti da Assíria e das cidades do Egito, e do Egito até o Rio, e de mar a mar, e de montanha a montanha.

[[v33-7-13]]

^<<v33-7-13,13>>^ Mas a terra será entregue à desolação por causa dos seus moradores, por causa do fruto das suas obras.

[[v33-7-14]]

^<<v33-7-14,14>>^ Apascenta com a tua vara o teu povo, o rebanho da tua herança, que habita a sós no bosque, no meio do Carmelo; apascentem-se em Basã e Gileade, como nos dias antigos.

[[v33-7-15]]

^<<v33-7-15,15>>^ Eu lhes mostrarei maravilhas, como nos dias da tua saída da terra do Egito.

[[v33-7-16]]

^<<v33-7-16,16>>^ As nações o verão, e envergonhar-se-ão, por causa de todo o seu poder; porão a mão sobre a boca, e os seus ouvidos ficarão surdos.

[[v33-7-17]]

^<<v33-7-17,17>>^ Lamberão o pó como serpentes; como répteis da terra, tremendo, sairão dos seus esconderijos; com pavor virão ao Senhor nosso Deus, e terão medo de ti.

[[v33-7-18]]

^<<v33-7-18,18>>^ Quem é Deus semelhante a ti, que perdoas a iniqüidade, e que te esqueces da transgressão do resto da tua herança? O Senhor não retém a sua ira para sempre, porque ele se deleita na benignidade.

[[v33-7-19]]

^<<v33-7-19,19>>^ Tornará a apiedar-se de nós; pisará aos pés as nossas iniqüidades. Tu lançarás todos os nossos pecados nas profundezas do mar.

[[v33-7-20]]

^<<v33-7-20,20>>^ Mostrarás a Jacó a fidelidade, e a Abraão a benignidade, conforme juraste a nossos pais desde os dias antigos.

'''

xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-naum/034-naum-001.adoc#v34-1-0[Próximo Capítulo &#62;]