include::./index.adoc[]

[[v49-1-0]]
=== Efésios, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v49-1-1]]

^<<v49-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, aos santos que estão em Éfeso, e fiéis em Cristo Jesus:

[[v49-1-2]]

^<<v49-1-2,2>>^ Graça a vós, e paz da parte de Deus nosso Pai, e do Senhor Jesus Cristo.

[[v49-1-3]]

^<<v49-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o qual nos abençoou com todas as bênçãos espirituais nas regiões celestes em Cristo;

[[v49-1-4]]

^<<v49-1-4,4>>^ como também nos elegeu nele antes da fundação do mundo, para sermos santos e irrepreensíveis diante dele em amor;

[[v49-1-5]]

^<<v49-1-5,5>>^ e nos predestinou para sermos filhos de adoção por Jesus Cristo, para si mesmo, segundo o beneplácito de sua vontade,

[[v49-1-6]]

^<<v49-1-6,6>>^ para o louvor da glória da sua graça, a qual nos deu gratuitamente no Amado;

[[v49-1-7]]

^<<v49-1-7,7>>^ em quem temos a redenção pelo seu sangue, a redenção dos nossos delitos, segundo as riquezas da sua graça,

[[v49-1-8]]

^<<v49-1-8,8>>^ que ele fez abundar para conosco em toda a sabedoria e prudência,

[[v49-1-9]]

^<<v49-1-9,9>>^ fazendo-nos conhecer o mistério da sua vontade, segundo o seu beneplácito, que nele propôs

[[v49-1-10]]

^<<v49-1-10,10>>^ para a dispensação da plenitude dos tempos, de fazer convergir em Cristo todas as coisas, tanto as que estão nos céus como as que estão na terra,

[[v49-1-11]]

^<<v49-1-11,11>>^ nele, digo, no qual também fomos feitos herança, havendo sido predestinados conforme o propósito daquele que faz todas as coisas segundo o conselho da sua vontade,

[[v49-1-12]]

^<<v49-1-12,12>>^ com o fim de sermos para o louvor da sua glória, nós, os que antes havíamos esperado em Cristo;

[[v49-1-13]]

^<<v49-1-13,13>>^ no qual também vós, tendo ouvido a palavra da verdade, o evangelho da vossa salvação, e tendo nele também crido, fostes selados com o Espírito Santo da promessa,

[[v49-1-14]]

^<<v49-1-14,14>>^ o qual é o penhor da nossa herança, para redenção da possessão de Deus, para o louvor da sua glória.

[[v49-1-15]]

^<<v49-1-15,15>>^ Por isso também eu, tendo ouvido falar da fé que entre vós há no Senhor Jesus e do vosso amor para com todos os santos,

[[v49-1-16]]

^<<v49-1-16,16>>^ não cesso de dar graças por vós, lembrando-me de vós nas minhas orações,

[[v49-1-17]]

^<<v49-1-17,17>>^ para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos dê o espírito de sabedoria e de revelação no pleno conhecimento dele;

[[v49-1-18]]

^<<v49-1-18,18>>^ sendo iluminados os olhos do vosso coração, para que saibais qual seja a esperança da sua vocação, e quais as riquezas da glória da sua herança nos santos,

[[v49-1-19]]

^<<v49-1-19,19>>^ e qual a suprema grandeza do seu poder para conosco, os que cremos, segundo a operação da força do seu poder,

[[v49-1-20]]

^<<v49-1-20,20>>^ que operou em Cristo, ressuscitando-o dentre os mortos e fazendo-o sentar-se à sua direita nos céus,

[[v49-1-21]]

^<<v49-1-21,21>>^ muito acima de todo principado, e autoridade, e poder, e domínio, e de todo nome que se nomeia, não só neste século, mas também no vindouro;

[[v49-1-22]]

^<<v49-1-22,22>>^ e sujeitou todas as coisas debaixo dos seus pés, e para ser cabeça sobre todas as coisas o deu à igreja,

[[v49-1-23]]

^<<v49-1-23,23>>^ que é o seu corpo, o complemento daquele que cumpre tudo em todas as coisas.

'''

xref:048-galatas/048-galatas-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-efesios/049-efesios-002.adoc#v49-2-0[Próximo Capítulo &#62;]