include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v49-4-1]]

^<<v49-4-1,1>>^ Rogo-vos, pois, eu, o prisioneiro no Senhor, que andeis como é digno da vocação com que fostes chamados,

[[v49-4-2]]

^<<v49-4-2,2>>^ com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor,

[[v49-4-3]]

^<<v49-4-3,3>>^ procurando diligentemente guardar a unidade do Espírito no vínculo da paz.

[[v49-4-4]]

^<<v49-4-4,4>>^ Há um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação;

[[v49-4-5]]

^<<v49-4-5,5>>^ um só Senhor, uma só fé, um só batismo;

[[v49-4-6]]

^<<v49-4-6,6>>^ um só Deus e Pai de todos, o qual é sobre todos, e por todos e em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ Mas a cada um de nós foi dada a graça conforme a medida do dom de Cristo.

[[v49-4-8]]

^<<v49-4-8,8>>^ Por isso foi dito: Subindo ao alto, levou cativo o cativeiro, e deu dons aos homens.

[[v49-4-9]]

^<<v49-4-9,9>>^ Ora, isto-ele subiu-que é, senão que também desceu às partes mais baixas da terra?

[[v49-4-10]]

^<<v49-4-10,10>>^ Aquele que desceu é também o mesmo que subiu muito acima de todos os céus, para cumprir todas as coisas.

[[v49-4-11]]

^<<v49-4-11,11>>^ E ele deu uns como apóstolos, e outros como profetas, e outros como evangelistas, e outros como pastores e mestres,

[[v49-4-12]]

^<<v49-4-12,12>>^ tendo em vista o aperfeiçoamento dos santos, para a obra do ministério, para edificação do corpo de Cristo;

[[v49-4-13]]

^<<v49-4-13,13>>^ até que todos cheguemos à unidade da fé e do pleno conhecimento do Filho de Deus, ao estado de homem feito, à medida da estatura da plenitude de Cristo;

[[v49-4-14]]

^<<v49-4-14,14>>^ para que não mais sejamos meninos, inconstantes, levados ao redor por todo vento de doutrina, pela fraudulência dos homens, pela astúcia tendente à maquinação do erro;

[[v49-4-15]]

^<<v49-4-15,15>>^ antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo,

[[v49-4-16]]

^<<v49-4-16,16>>^ do qual o corpo inteiro bem ajustado, e ligado pelo auxílio de todas as juntas, segundo a justa operação de cada parte, efetua o seu crescimento para edificação de si mesmo em amor.

[[v49-4-17]]

^<<v49-4-17,17>>^ Portanto digo isto, e testifico no Senhor, para que não mais andeis como andam os gentios, na verdade da sua mente,

[[v49-4-18]]

^<<v49-4-18,18>>^ entenebrecidos no entendimento, separados da vida de Deus pela ignorância que há neles, pela dureza do seu coração;

[[v49-4-19]]

^<<v49-4-19,19>>^ os quais, tendo-se tornado insensíveis, entregaram-se à lascívia para cometerem com avidez toda sorte de impureza.

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas vós não aprendestes assim a Cristo.

[[v49-4-21]]

^<<v49-4-21,21>>^ se é que o ouvistes, e nele fostes instruídos, conforme é a verdade em Jesus,

[[v49-4-22]]

^<<v49-4-22,22>>^ a despojar-vos, quanto ao procedimento anterior, do velho homem, que se corrompe pelas concupiscências do engano;

[[v49-4-23]]

^<<v49-4-23,23>>^ a vos renovar no espírito da vossa mente;

[[v49-4-24]]

^<<v49-4-24,24>>^ e a vos revestir do novo homem, que segundo Deus foi criado em verdadeira justiça e santidade.

[[v49-4-25]]

^<<v49-4-25,25>>^ Pelo que deixai a mentira, e falai a verdade cada um com o seu próximo, pois somos membros uns dos outros.

[[v49-4-26]]

^<<v49-4-26,26>>^ Irai-vos, e não pequeis; não se ponha o sol sobre a vossa ira;

[[v49-4-27]]

^<<v49-4-27,27>>^ nem deis lugar ao Diabo.

[[v49-4-28]]

^<<v49-4-28,28>>^ Aquele que furtava, não furte mais; antes trabalhe, fazendo com as mãos o que é bom, para que tenha o que repartir com o que tem necessidade.

[[v49-4-29]]

^<<v49-4-29,29>>^ Não saia da vossa boca nenhuma palavra torpe, mas ó a que seja boa para a necessária edificação, a fim de que ministre graça aos que a ouvem.

[[v49-4-30]]

^<<v49-4-30,30>>^ E não entristeçais o Espírito Santo de Deus, no qual fostes selados para o dia da redenção.

[[v49-4-31]]

^<<v49-4-31,31>>^ Toda a amargura, e cólera, e ira, e gritaria, e blasfêmia sejam tiradas dentre vós, bem como toda a malícia.

[[v49-4-32]]

^<<v49-4-32,32>>^ Antes sede bondosos uns para com os outros, compassivos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]