include::./index.adoc[]

[[v49-6-0]]
=== Efésios, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v49-6-1]]

^<<v49-6-1,1>>^ Vós, filhos, sede obedientes a vossos pais no Senhor, porque isto é justo.

[[v49-6-2]]

^<<v49-6-2,2>>^ Honra a teu pai e a tua mãe &#123;que é o primeiro mandamento com promessa&#125;,

[[v49-6-3]]

^<<v49-6-3,3>>^ para que te vá bem, e sejas de longa vida sobre a terra.

[[v49-6-4]]

^<<v49-6-4,4>>^ E vós, pais, não provoqueis à ira vossos filhos, mas criai-os na disciplina e admoestação do Senhor.

[[v49-6-5]]

^<<v49-6-5,5>>^ Vós, servos, obedecei a vossos senhores segundo a carne, com temor e tremor, na sinceridade de vosso coração, como a Cristo,

[[v49-6-6]]

^<<v49-6-6,6>>^ não servindo somente à vista, como para agradar aos homens, mas como servos de Cristo, fazendo de coração a vontade de Deus,

[[v49-6-7]]

^<<v49-6-7,7>>^ servindo de boa vontade como ao Senhor, e não como aos homens.

[[v49-6-8]]

^<<v49-6-8,8>>^ Sabendo que cada um, seja escravo, seja livre, receberá do Senhor todo bem que fizer.

[[v49-6-9]]

^<<v49-6-9,9>>^ E vós, senhores, fazei o mesmo para com eles, deixando as ameaças, sabendo que o Senhor tanto deles como vosso está no céu, e que para com ele não há acepção de pessoas.

[[v49-6-10]]

^<<v49-6-10,10>>^ Finalmente, fortalecei-vos no Senhor e na força do seu poder.

[[v49-6-11]]

^<<v49-6-11,11>>^ Revesti-vos de toda a armadura de Deus, para poderdes permanecer firmes contra as ciladas do Diabo;

[[v49-6-12]]

^<<v49-6-12,12>>^ pois não é contra carne e sangue que temos que lutar, mas sim contra os principados, contra as potestades, conta os príncipes do mundo destas trevas, contra as hostes espirituais da iniqüidade nas regiões celestes.

[[v49-6-13]]

^<<v49-6-13,13>>^ Portanto tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, permanecer firmes.

[[v49-6-14]]

^<<v49-6-14,14>>^ Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça,

[[v49-6-15]]

^<<v49-6-15,15>>^ e calçando os pés com a preparação do evangelho da paz,

[[v49-6-16]]

^<<v49-6-16,16>>^ tomando, sobretudo, o escudo da fé, com o qual podereis apagar todos os dardos inflamados do Maligno.

[[v49-6-17]]

^<<v49-6-17,17>>^ Tomai também o capacete da salvação, e a espada do Espírito, que é a palavra de Deus;

[[v49-6-18]]

^<<v49-6-18,18>>^ com toda a oração e súplica orando em todo tempo no Espírito e, para o mesmo fim, vigiando com toda a perseverança e súplica, por todos os santos,

[[v49-6-19]]

^<<v49-6-19,19>>^ e por mim, para que me seja dada a palavra, no abrir da minha boca, para, com intrepidez, fazer conhecido o mistério do evangelho,

[[v49-6-20]]

^<<v49-6-20,20>>^ pelo qual sou embaixador em cadeias, para que nele eu tenha coragem para falar como devo falar.

[[v49-6-21]]

^<<v49-6-21,21>>^ Ora, para que vós também possais saber como estou e o que estou fazendo, Tíquico, irmão amado e fiel ministro no Senhor, vos informará de tudo;

[[v49-6-22]]

^<<v49-6-22,22>>^ o qual vos envio para este mesmo fim, para que saibais do nosso estado, e ele vos conforte o coração.

[[v49-6-23]]

^<<v49-6-23,23>>^ Paz seja com os irmãos, e amor com fé, da parte de Deus Pai e do Senhor Jesus Cristo.

[[v49-6-24]]

^<<v49-6-24,24>>^ A graça seja com todos os que amam a nosso Senhor Jesus Cristo com amor incorruptível.

'''

xref:049-efesios/049-efesios-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[Próximo Capítulo &#62;]