include::./index.adoc[]

[[v49-2-0]]
=== Efésios, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v49-2-1]]

^<<v49-2-1,1>>^ Ele vos vivificou, estando vós mortos nos vossos delitos e pecados,

[[v49-2-2]]

^<<v49-2-2,2>>^ nos quais outrora andastes, segundo o curso deste mundo, segundo o príncipe das potestades do ar, do espírito que agora opera nos filhos de desobediência,

[[v49-2-3]]

^<<v49-2-3,3>>^ entre os quais todos nós também antes andávamos nos desejos da nossa carne, fazendo a vontade da carne e dos pensamentos; e éramos por natureza filhos da ira, como também os demais.

[[v49-2-4]]

^<<v49-2-4,4>>^ Mas Deus, sendo rico em misericórdia, pelo seu muito amor com que nos amou,

[[v49-2-5]]

^<<v49-2-5,5>>^ estando nós ainda mortos em nossos delitos, nos vivificou juntamente com Cristo &#123;pela graça sois salvos&#125;,

[[v49-2-6]]

^<<v49-2-6,6>>^ e nos ressuscitou juntamente com ele, e com ele nos fez sentar nas regiões celestes em Cristo Jesus,

[[v49-2-7]]

^<<v49-2-7,7>>^ para mostrar nos séculos vindouros a suprema riqueza da sua graça, pela sua bondade para conosco em Cristo Jesus.

[[v49-2-8]]

^<<v49-2-8,8>>^ Porque pela graça sois salvos, por meio da fé, e isto não vem de vós, é dom de Deus;

[[v49-2-9]]

^<<v49-2-9,9>>^ não vem das obras, para que ninguém se glorie.

[[v49-2-10]]

^<<v49-2-10,10>>^ Porque somos feitura sua, criados em Cristo Jesus para boas obras, as quais Deus antes preparou para que andássemos nelas.

[[v49-2-11]]

^<<v49-2-11,11>>^ Portanto, lembrai-vos que outrora vós, gentios na carne, chamam circuncisão, feita pela mão dos homens,

[[v49-2-12]]

^<<v49-2-12,12>>^ estáveis naquele tempo sem Cristo, separados da comunidade de Israel, e estranhos aos pactos da promessa, não tendo esperança, e sem Deus no mundo.

[[v49-2-13]]

^<<v49-2-13,13>>^ Mas agora, em Cristo Jesus, vós, que antes estáveis longe, já pelo sangue de Cristo chegastes perto.

[[v49-2-14]]

^<<v49-2-14,14>>^ Porque ele é a nossa paz, o qual de ambos os povos fez um; e, derrubando a parede de separação que estava no meio, na sua carne desfez a inimizade,

[[v49-2-15]]

^<<v49-2-15,15>>^ isto é, a lei dos mandamentos contidos em ordenanças, para criar, em si mesmo, dos dois um novo homem, assim fazendo a paz,

[[v49-2-16]]

^<<v49-2-16,16>>^ e pela cruz reconciliar ambos com Deus em um só corpo, tendo por ela matado a inimizade;

[[v49-2-17]]

^<<v49-2-17,17>>^ e, vindo, ele evangelizou paz a vós que estáveis longe, e paz aos que estavam perto;

[[v49-2-18]]

^<<v49-2-18,18>>^ porque por ele ambos temos acesso ao Pai em um mesmo Espírito.

[[v49-2-19]]

^<<v49-2-19,19>>^ Assim, pois, não sois mais estrangeiros, nem forasteiros, antes sois concidadãos dos santos e membros da família de Deus,

[[v49-2-20]]

^<<v49-2-20,20>>^ edificados sobre o fundamento dos apóstolos e dos profetas, sendo o próprio Cristo Jesus a principal pedra da esquina;

[[v49-2-21]]

^<<v49-2-21,21>>^ no qual todo o edifício bem ajustado cresce para templo santo no Senhor,

[[v49-2-22]]

^<<v49-2-22,22>>^ no qual também vós juntamente sois edificados para morada de Deus no Espírito.

'''

xref:049-efesios/049-efesios-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-efesios/049-efesios-003.adoc#v49-3-0[Próximo Capítulo &#62;]