include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v37-2-1]]

^<<v37-2-1,1>>^ No segundo ano do rei Dario, no sétimo mês, ao vigésimo primeiro do mês, veio a palavra do Senhor por intermédio do profeta Ageu, dizendo:

[[v37-2-2]]

^<<v37-2-2,2>>^ Fala agora ao governador de Judá, Zorobabel, filho de Sealtiel, e ao sumo sacerdote Josué, filho de Jeozadaque, e ao resto do povo, dizendo:

[[v37-2-3]]

^<<v37-2-3,3>>^ Quem há entre vós, dos sobreviventes, que viu esta casa na sua primeira glória? Em que estado a vedes agora? Não é como nada em vossos olhos?

[[v37-2-4]]

^<<v37-2-4,4>>^ Ora, pois, esforça-te, Zorobabel, diz o Senhor, e esforça-te, sumo sacerdote Josué, filho de Jeozadaque, e esforçai-vos, todo o povo da terra, diz o Senhor, e trabalhai; porque eu sou convosco, diz o Senhor dos exércitos,

[[v37-2-5]]

^<<v37-2-5,5>>^ segundo o pacto que fiz convosco, quando saístes do Egito, e o meu Espírito habita no meio de vós; não temais.

[[v37-2-6]]

^<<v37-2-6,6>>^ Pois assim diz o Senhor dos exércitos; Ainda uma vez, daqui a pouco, e abalarei os céus e a terra, o mar e a terra seca.

[[v37-2-7]]

^<<v37-2-7,7>>^ Abalarei todas as nações; e as coisas preciosas de todas as nações virão, e encherei de glória esta casa, diz o Senhor dos exércitos.

[[v37-2-8]]

^<<v37-2-8,8>>^ Minha é a prata, e meu é o ouro, diz o Senhor dos exércitos.

[[v37-2-9]]

^<<v37-2-9,9>>^ A glória desta última casa será maior do que a da primeira, diz o Senhor dos exércitos; e neste lugar darei a paz, diz o Senhor dos exércitos.

[[v37-2-10]]

^<<v37-2-10,10>>^ Ao vigésimo quarto dia do mês nono, no segundo ano de Dario, veio a palavra do Senhor ao profeta Ageu, dizendo:

[[v37-2-11]]

^<<v37-2-11,11>>^ Assim diz o Senhor dos exércitos: Pergunta agora aos sacerdotes, acerca da lei, dizendo:

[[v37-2-12]]

^<<v37-2-12,12>>^ Se alguém levar na aba de suas vestes carne santa, e com a sua aba tocar no pão, ou no guisado, ou no vinho, ou no azeite, ou em qualquer outro mantimento, ficará este santificado? E os sacerdotes responderam: Não.

[[v37-2-13]]

^<<v37-2-13,13>>^ Então perguntou Ageu: Se alguém, que for contaminado pelo contato com o corpo morto, tocar nalguma destas coisas, ficará ela imunda? E os sacerdotes responderam: Ficará imunda.

[[v37-2-14]]

^<<v37-2-14,14>>^ Ao que respondeu Ageu, dizendo: Assim é este povo, e assim é esta nação diante de mim, diz o Senhor; assim é toda a obra das suas mãos; e tudo o que ali oferecem imundo é.

[[v37-2-15]]

^<<v37-2-15,15>>^ Agora considerai o que acontece desde aquele dia. Antes que se lançasse pedra sobre pedra no templo do Senhor,

[[v37-2-16]]

^<<v37-2-16,16>>^ quando alguém vinha a um montão de trigo de vinte medidas, havia somente dez; quando vinha ao lagar para tirar cinqüenta, havia somente vinte.

[[v37-2-17]]

^<<v37-2-17,17>>^ Feri-vos com mangra, e com ferrugem, e com saraiva, em todas as obras das vossas mãos; e não houve entre vós quem voltasse para mim, diz o Senhor.

[[v37-2-18]]

^<<v37-2-18,18>>^ Considerai, pois, eu vos rogo, desde este dia em diante, desde o vigésimo quarto dia do mês nono, desde o dia em que se lançaram os alicerces do templo do Senhor, sim, considerai essas coisas.

[[v37-2-19]]

^<<v37-2-19,19>>^ Está ainda semente no celeiro? A videira, a figueira, a romeira, e a oliveira ainda não dão os seus frutos? Desde este dia hei de vos abençoar.

[[v37-2-20]]

^<<v37-2-20,20>>^ Veio pela segunda vez a palavra do Senhor a Ageu, aos vinte e quatro do mês, dizendo:

[[v37-2-21]]

^<<v37-2-21,21>>^ Fala a Zorobabel, governador de Judá, dizendo: Abalarei os céus e a terra;

[[v37-2-22]]

^<<v37-2-22,22>>^ e derrubarei o trono dos reinos, e destruirei a força dos reinos das nações; destruirei o carro e os que nele andam; os cavalos e os seus cavaleiros cairão, cada um pela espada do seu irmão.

[[v37-2-23]]

^<<v37-2-23,23>>^ Naquele dia, diz o Senhor dos exércitos, tomar-te-ei, ó Zorobabel, servo meu, filho de Sealtiel, diz o Senhor, e te farei como um anel de selar; porque te escolhi, diz o Senhor dos exércitos.

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]