include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v37-1-1]]

^<<v37-1-1,1>>^ No segundo ano do rei Dario, no sexto mês, no primeiro dia do mês, veio a palavra do Senhor, por intermédio do profeta Ageu, a Zorobabel, governador de Judá, filho de Sealtiel, e a Josué, o sumo sacerdote, filho de Jeozadaque, dizendo:

[[v37-1-2]]

^<<v37-1-2,2>>^ Assim fala o Senhor dos exércitos, dizendo: Este povo diz: Não veio ainda o tempo, o tempo de se edificar a casa do Senhor.

[[v37-1-3]]

^<<v37-1-3,3>>^ Veio, pois, a palavra do Senhor, por intermédio do profeta Ageu, dizendo:

[[v37-1-4]]

^<<v37-1-4,4>>^ Acaso é tempo de habitardes nas vossas casas forradas, enquanto esta casa fica desolada?

[[v37-1-5]]

^<<v37-1-5,5>>^ Ora pois, assim diz o Senhor dos exércitos: Considerai os vossos caminhos.

[[v37-1-6]]

^<<v37-1-6,6>>^ Tendes semeado muito, e recolhido pouco; comeis, mas não vos fartais; bebeis, mas não vos saciais; vestis-vos, mas ninguém se aquece; e o que recebe salário, recebe-o para o meter num saco furado.

[[v37-1-7]]

^<<v37-1-7,7>>^ Assim diz o Senhor dos exércitos: Considerai os vossos caminhos.

[[v37-1-8]]

^<<v37-1-8,8>>^ Subi ao monte, e trazei madeira, e edificai a casa; e dela me deleitarei, e serei glorificado, diz o Senhor.

[[v37-1-9]]

^<<v37-1-9,9>>^ Esperastes o muito, mas eis que veio a ser pouco; e esse pouco, quando o trouxestes para casa, eu o dissipei com um assopro. Por que causa? diz o Senhor dos exércitos. Por causa da minha casa, que está em ruínas, enquanto correis, cada um de vós, à sua própria casa.

[[v37-1-10]]

^<<v37-1-10,10>>^ Por isso os céus por cima de vós retêm o orvalho, e a terra retém os seus frutos.

[[v37-1-11]]

^<<v37-1-11,11>>^ E mandei vir a seca sobre a terra, e sobre as colinas, sobre o trigo e o mosto e o azeite, e sobre tudo o que a terra produz; como também sobre os homens e os animais, e sobre todo o seu trabalho.

[[v37-1-12]]

^<<v37-1-12,12>>^ Então Zorobabel, filho de Sealtiel, e o sumo sacerdote Josué, filho de Jeozadaque, juntamente com todo o resto do povo, obedeceram a voz do Senhor seu Deus, e as palavras do profeta Ageu, como o Senhor seu Deus o tinha enviado; e temeu o povo diante do Senhor.

[[v37-1-13]]

^<<v37-1-13,13>>^ Então Ageu, o mensageiro do Senhor, falou ao povo, conforme a mensagem do Senhor, dizendo: Eu sou convosco, e diz o Senhor.

[[v37-1-14]]

^<<v37-1-14,14>>^ E o Senhor suscitou o espírito do governador de Judá Zorobabel, filho de Sealtiel, e o espírito do sumo sacerdote Josué, filho de Jeozadaque, e o espírito de todo o resto do povo; e eles vieram, e começaram a trabalhar na casa do Senhor dos exércitos, seu Deus,

[[v37-1-15]]

^<<v37-1-15,15>>^ ao vigésimo quarto dia do sexto mês.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]