include::./index.adoc[]

[[v60-4-0]]
=== 1 Pedro, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v60-4-1]]

^<<v60-4-1,1>>^ Ora pois, já que Cristo padeceu na carne, armai-vos também vós deste mesmo pensamento; porque aquele que padeceu na carne já cessou do pecado;

[[v60-4-2]]

^<<v60-4-2,2>>^ para que, no tempo que ainda vos resta na carne não continueis a viver para as concupiscências dos homens, mas para a vontade de Deus.

[[v60-4-3]]

^<<v60-4-3,3>>^ Porque é bastante que no tempo passado tenhais cumprido a vontade dos gentios, andando em dissoluções, concupiscências, borrachices, glutonarias, bebedices e abomináveis idolatrias.

[[v60-4-4]]

^<<v60-4-4,4>>^ E acham estranho não correrdes com eles no mesmo desenfreamento de dissolução, blasfemando de vós;

[[v60-4-5]]

^<<v60-4-5,5>>^ os quais hão de dar conta ao que está preparado para julgar os vivos e os mortos.

[[v60-4-6]]

^<<v60-4-6,6>>^ Pois é por isto que foi pregado o evangelho até aos mortos, para que, na verdade, fossem julgados segundo os homens na carne, mas vivessem segundo Deus em espírito.

[[v60-4-7]]

^<<v60-4-7,7>>^ Mas já está próximo o fim de todas as coisas; portanto sede sóbrios e vigiai em oração;

[[v60-4-8]]

^<<v60-4-8,8>>^ tendo antes de tudo ardente amor uns para com os outros, porque o amor cobre uma multidão de pecados;

[[v60-4-9]]

^<<v60-4-9,9>>^ sendo hospitaleiros uns para com os outros, sem murmuração;

[[v60-4-10]]

^<<v60-4-10,10>>^ servindo uns aos outros conforme o dom que cada um recebeu, como bons despenseiros da multiforme graça de Deus.

[[v60-4-11]]

^<<v60-4-11,11>>^ Se alguém fala, fale como entregando oráculos de Deus; se alguém ministra, ministre segundo a força que Deus concede; para que em tudo Deus seja glorificado por meio de Jesus Cristo, ma quem pertencem a glória e o domínio para todo o sempre. Amém.

[[v60-4-12]]

^<<v60-4-12,12>>^ Amados, não estranheis a ardente provação que vem sobre vós para vos experimentar, como se coisa estranha vos acontecesse;

[[v60-4-13]]

^<<v60-4-13,13>>^ mas regozijai-vos por serdes participantes das aflições de Cristo; para que também na revelação da sua glória vos regozijeis e exulteis.

[[v60-4-14]]

^<<v60-4-14,14>>^ Se pelo nome de Cristo sois vituperados, bem-aventurados sois, porque sobre vós repousa o Espírito da glória, o Espírito de Deus.

[[v60-4-15]]

^<<v60-4-15,15>>^ Que nenhum de vós, entretanto, padeça como homicida, ou ladrão, ou malfeitor, ou como quem se entremete em negócios alheios;

[[v60-4-16]]

^<<v60-4-16,16>>^ mas, se padece como cristão, não se envergonhe, antes glorifique a Deus neste nome.

[[v60-4-17]]

^<<v60-4-17,17>>^ Porque já é tempo que comece o julgamento pela casa de Deus; e se começa por nós, qual será o fim daqueles que desobedecem ao evangelho de Deus?

[[v60-4-18]]

^<<v60-4-18,18>>^ E se o justo dificilmente se salva, onde comparecerá o ímpio pecador?

[[v60-4-19]]

^<<v60-4-19,19>>^ Portanto os que sofrem segundo a vontade de Deus confiem as suas almas ao fiel Criador, praticando o bem.

'''

xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[Próximo Capítulo &#62;]