include::./index.adoc[]

[[v60-5-0]]
=== 1 Pedro, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v60-5-1]]

^<<v60-5-1,1>>^ Aos anciãos, pois, que há entre vós, rogo eu, que sou ancião com eles e testemunha dos sofrimentos de Cristo, e participante da glória que se há de revelar:

[[v60-5-2]]

^<<v60-5-2,2>>^ Apascentai o rebanho de Deus, que está entre vós, não por força, mas espontaneamente segundo a vontade de Deus; nem por torpe ganância, mas de boa vontade;

[[v60-5-3]]

^<<v60-5-3,3>>^ nem como dominadores sobre os que vos foram confiados, mas servindo de exemplo ao rebanho.

[[v60-5-4]]

^<<v60-5-4,4>>^ E, quando se manifestar o sumo Pastor, recebereis a imarcescível coroa da glória.

[[v60-5-5]]

^<<v60-5-5,5>>^ Semelhantemente vós, os mais moços, sede sujeitos aos mais velhos. E cingi-vos todos de humildade uns para com os outros, porque Deus resiste aos soberbos, mas dá graça aos humildes.

[[v60-5-6]]

^<<v60-5-6,6>>^ Humilhai-vos, pois, debaixo da potente mão de Deus, para que a seu tempo vos exalte;

[[v60-5-7]]

^<<v60-5-7,7>>^ lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.

[[v60-5-8]]

^<<v60-5-8,8>>^ Sede sóbrios, vigiai. O vosso adversário, o Diabo, anda em derredor, rugindo como leão, e procurando a quem possa tragar;

[[v60-5-9]]

^<<v60-5-9,9>>^ ao qual resisti firmes na fé, sabendo que os mesmos sofrimentos estão-se cumprindo entre os vossos irmãos no mundo.

[[v60-5-10]]

^<<v60-5-10,10>>^ E o Deus de toda a graça, que em Cristo vos chamou à sua eterna glória, depois de haverdes sofrido por um pouco, ele mesmo vos há de aperfeiçoar, confirmar e fortalecer.

[[v60-5-11]]

^<<v60-5-11,11>>^ A ele seja o domínio para todo o sempre. Amém.

[[v60-5-12]]

^<<v60-5-12,12>>^ Por Silvano, nosso fiel irmão, como o considero, escravo abreviadamente, exortando e testificando que esta é a verdadeira graça de Deus; nela permanecei firmes.

[[v60-5-13]]

^<<v60-5-13,13>>^ A vossa co-eleita em Babilônia vos saúda, como também meu filho Marcos.

[[v60-5-14]]

^<<v60-5-14,14>>^ Saudai-vos uns aos outros com ósculo de amor. Paz seja com todos vós que estais em Cristo.

'''

xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[Próximo Capítulo &#62;]