include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v60-2-1]]

^<<v60-2-1,1>>^ Deixando, pois, toda a malícia, todo o engano, e fingimentos, e invejas, e toda a maledicência,

[[v60-2-2]]

^<<v60-2-2,2>>^ desejai, como meninos recém-nascidos, o leite racional, sem dolo, para que por ele cresçais para a salvação,

[[v60-2-3]]

^<<v60-2-3,3>>^ se é que já provastes que o Senhor é benigno.

[[v60-2-4]]

^<<v60-2-4,4>>^ e, chegando-vos para ele, pedra viva, rejeitada, na verdade, pelos homens, mas, para com Deus eleita e preciosa,

[[v60-2-5]]

^<<v60-2-5,5>>^ sois vós também quais pedras vivas, edificados como casa espiritual para serdes um sacerdócio santo, a fim de oferecerdes sacrifícios espirituais, aceitáveis a Deus por Jesus Cristo.

[[v60-2-6]]

^<<v60-2-6,6>>^ Por isso é que se acha na Escritura: Eis que ponho em Sião a principal pedra angular, eleita e preciosa, E aquele que nele crê, não será envergonhado.

[[v60-2-7]]

^<<v60-2-7,7>>^ Para vós, portanto, que credes é a honra; mas para aqueles que descrêem, A pedra que os edificadores rejeitaram, Esta foi posta como a pedra angular

[[v60-2-8]]

^<<v60-2-8,8>>^ e Como uma pedra de tropeço e uma rocha de escândalo; porque tropeçam na palavra, sendo desobedientes, para o que também foram postos.

[[v60-2-9]]

^<<v60-2-9,9>>^ Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo todo seu para que proclameis as grandezas daquele que vos chamou das trevas para a sua maravilhosa luz,

[[v60-2-10]]

^<<v60-2-10,10>>^ vós que em outro tempo éreis não povo, mas agora sois povo de Deus, vós que não havíeis alcançado misericórdia, mas agora a tendes alcançado.

[[v60-2-11]]

^<<v60-2-11,11>>^ Amados, rogo-vos como peregrinos e forasteiros, que vos abstenhais dos desejos carnais, que combatem contra a alma,

[[v60-2-12]]

^<<v60-2-12,12>>^ tendo o vosso procedimento bom entre os gentios, a fim de que, naquilo em que murmuram de vós como de malfeitores, considerando-vos pelas vossas obras, glorifiquem a Deus no dia da visitação.

[[v60-2-13]]

^<<v60-2-13,13>>^ Sujeitai-vos a toda autoridade humana por amor do Senhor, quer ao rei, como soberano,

[[v60-2-14]]

^<<v60-2-14,14>>^ quer seja ao rei como supremo, quer seja aos governadores, como enviados por ele para castigo dos malfeitores e para louvor dos que fazem o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ Porque assim é a vontade de Deus, que, fazendo o bem, façais emudecer a ignorância dos homens imprudentes,

[[v60-2-16]]

^<<v60-2-16,16>>^ como livres, e não tendo a vossa liberdade para capa da malícia, mas como servos de Deus.

[[v60-2-17]]

^<<v60-2-17,17>>^ Honrai a todos, amai a irmandade, temei a Deus, respeitai ao rei.

[[v60-2-18]]

^<<v60-2-18,18>>^ Servos, sede sujeitos com todo o temor a vossos senhores, não somente aos bons e moderados, mas também aos perversos.

[[v60-2-19]]

^<<v60-2-19,19>>^ Pois isto é agradável, se alguém, por ser cônscio de Deus, suporta tristezas, padecendo injustamente.

[[v60-2-20]]

^<<v60-2-20,20>>^ Pois que glória é, se sofreis com paciência, quando cometeis pecado, e sois por isso esbofeteados? mas se sofreis com paciência, quando fazeis o bem e por isso padeceis, isto é agradável a Deus.

[[v60-2-21]]

^<<v60-2-21,21>>^ Pois para isto fostes chamados, porquanto também Cristo padeceu por vós, deixando-vos exemplo, para que sigais as suas pisadas.

[[v60-2-22]]

^<<v60-2-22,22>>^ Ele não cometeu pecado, nem tão pouco foi achado engano na sua boca,

[[v60-2-23]]

^<<v60-2-23,23>>^ sendo injuriado, não injuriava, padecendo, não ameaçava, mas entregava-se àquele que julga justamente,

[[v60-2-24]]

^<<v60-2-24,24>>^ levando ele próprio os nossos pecados em seu corpo sobre o madeiro, a fim de que, mortos aos pecados, vivamos à justiça. Por suas feridas fostes sarados.

[[v60-2-25]]

^<<v60-2-25,25>>^ Pois éreis desgarrados como ovelhas, mas agora vos haveis convertido ao Pastor e Bispo das vossas almas.

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]