include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v60-1-1]]

^<<v60-1-1,1>>^ Pedro, apóstolo de Jesus Cristo, aos peregrinos da Dispersão no Ponto, Galácia, Capadócia, Ásia e Bitínia.

[[v60-1-2]]

^<<v60-1-2,2>>^ eleitos segundo a presciência de Deus Pai, na santificação do Espírito, para a obediência e aspersão do sangue de Jesus Cristo: Graça e paz vos sejam multiplicadas.

[[v60-1-3]]

^<<v60-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos regenerou para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos,

[[v60-1-4]]

^<<v60-1-4,4>>^ para uma herança incorruptível, incontaminável e imarcescível, reservada nos céus para vós,

[[v60-1-5]]

^<<v60-1-5,5>>^ que pelo poder de Deus sois guardados, mediante a fé, para a salvação que está preparada para se revelar no último tempo;

[[v60-1-6]]

^<<v60-1-6,6>>^ na qual exultais, ainda que agora por um pouco de tempo, sendo necessário, estejais contristados por várias provações,

[[v60-1-7]]

^<<v60-1-7,7>>^ para que a prova da vossa fé, mais preciosa do que o ouro que perece, embora provado pelo fogo, redunde para louvor, glória e honra na revelação de Jesus Cristo;

[[v60-1-8]]

^<<v60-1-8,8>>^ a quem, sem o terdes visto, amais; no qual, sem agora o verdes, mas crendo, exultais com gozo inefável e cheio de glória,

[[v60-1-9]]

^<<v60-1-9,9>>^ alcançando o fim da vossa fé, a salvação das vossas almas.

[[v60-1-10]]

^<<v60-1-10,10>>^ Desta salvação inquiririam e indagaram diligentemente os profetas que profetizaram da graça que para vós era destinada,

[[v60-1-11]]

^<<v60-1-11,11>>^ indagando qual o tempo ou qual a ocasião que o Espírito de Cristo que estava neles indicava, ao predizer os sofrimentos que a Cristo haviam de vir, e a glória que se lhes havia de seguir.

[[v60-1-12]]

^<<v60-1-12,12>>^ Aos quais foi revelado que não para si mesmos, mas para vós, eles ministravam estas coisas que agora vos foram anunciadas por aqueles que, pelo Espírito Santo enviado do céu, vos pregaram o evangelho; para as quais coisas os anjos bem desejam atentar.

[[v60-1-13]]

^<<v60-1-13,13>>^ Portanto, cingindo os lombos do vosso entendimento, sede sóbrios, e esperai inteiramente na graça que se vos oferece na revelação de Jesus Cristo.

[[v60-1-14]]

^<<v60-1-14,14>>^ Como filhos obedientes, não vos conformeis às concupiscências que antes tínheis na vossa ignorância;

[[v60-1-15]]

^<<v60-1-15,15>>^ mas, como é santo aquele que vos chamou, sede vós também santos em todo o vosso procedimento;

[[v60-1-16]]

^<<v60-1-16,16>>^ porquanto está escrito: Sereis santos, porque eu sou santo.

[[v60-1-17]]

^<<v60-1-17,17>>^ E, se invocais por Pai aquele que, sem acepção de pessoas, julga segundo a obra de cada um, andai em temor durante o tempo da vossa peregrinação,

[[v60-1-18]]

^<<v60-1-18,18>>^ sabendo que não foi com coisas corruptíveis, como prata ou ouro, que fostes resgatados da vossa vã maneira de viver, que por tradição recebestes dos vossos pais,

[[v60-1-19]]

^<<v60-1-19,19>>^ mas com precioso sangue, como de um cordeiro sem defeito e sem mancha, o sangue de Cristo,

[[v60-1-20]]

^<<v60-1-20,20>>^ o qual, na verdade, foi conhecido ainda antes da fundação do mundo, mas manifesto no fim dos tempos por amor de vós,

[[v60-1-21]]

^<<v60-1-21,21>>^ que por ele credes em Deus, que o ressuscitou dentre os mortos e lhe deu glória, de modo que a vossa fé e esperança estivessem em Deus.

[[v60-1-22]]

^<<v60-1-22,22>>^ Já que tendes purificado as vossas almas na obediência à verdade, que leva ao amor fraternal não fingido, de coração amai-vos ardentemente uns aos outros,

[[v60-1-23]]

^<<v60-1-23,23>>^ tendo renascido, não de semente corruptível, mas de incorruptível, pela palavra de Deus, a qual vive e permanece.

[[v60-1-24]]

^<<v60-1-24,24>>^ Porque: Toda a carne é como a erva, e toda a sua glória como a flor da erva. Secou-se a erva, e caiu a sua flor;

[[v60-1-25]]

^<<v60-1-25,25>>^ mas a palavra do Senhor permanece para sempre. E esta é a palavra que vos foi evangelizada.

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]