include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-15-1]]

^<<v45-15-1,1>>^ Ora nós, que somos fortes, devemos suportar as fraquezas dos fracos, e não agradar a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Portanto cada um de nós agrade ao seu próximo, visando o que é bom para edificação.

[[v45-15-3]]

^<<v45-15-3,3>>^ Porque também Cristo não se agradou a si mesmo, mas como está escrito: Sobre mim caíram as injúrias dos que te injuriavam.

[[v45-15-4]]

^<<v45-15-4,4>>^ Porquanto, tudo que dantes foi escrito, para nosso ensino foi escrito, para que, pela constância e pela consolação provenientes das Escrituras, tenhamos esperança.

[[v45-15-5]]

^<<v45-15-5,5>>^ Ora, o Deus de constância e de consolação vos dê o mesmo sentimento uns para com os outros, segundo Cristo Jesus.

[[v45-15-6]]

^<<v45-15-6,6>>^ Para que unânimes, e a uma boca, glorifiqueis ao Deus e Pai de nosso Senhor Jesus Cristo.

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto recebei-vos uns aos outros, como também Cristo nos recebeu, para glória de Deus.

[[v45-15-8]]

^<<v45-15-8,8>>^ Digo pois que Cristo foi feito ministro da circuncisão, por causa da verdade de Deus, para confirmar as promessas feitas aos pais;

[[v45-15-9]]

^<<v45-15-9,9>>^ e para que os gentios glorifiquem a Deus pela sua misericórdia, como está escrito: Portanto eu te louvarei entre os gentios, e cantarei ao teu nome.

[[v45-15-10]]

^<<v45-15-10,10>>^ E outra vez diz: Alegrai-vos, gentios, juntamente com o povo.

[[v45-15-11]]

^<<v45-15-11,11>>^ E ainda: Louvai ao Senhor, todos os gentios, e louvem-no, todos os povos.

[[v45-15-12]]

^<<v45-15-12,12>>^ E outra vez, diz também Isaías: Haverá a raiz de Jessé, aquele que se levanta para reger os gentios; nele os gentios esperarão.

[[v45-15-13]]

^<<v45-15-13,13>>^ Ora, o Deus de esperança vos encha de todo o gozo e paz na vossa fé, para que abundeis na esperança pelo poder do Espírito Santo.

[[v45-15-14]]

^<<v45-15-14,14>>^ Eu, da minha parte, irmãos meus, estou persuadido a vosso respeito, que vós já estais cheios de bondade, cheios de todo o conhecimento e capazes, vós mesmos, de admoestar-vos uns aos outros.

[[v45-15-15]]

^<<v45-15-15,15>>^ Mas em parte vos escrevo mais ousadamente, como para vos trazer outra vez isto à memória, por causa da graça que por Deus me foi dada,

[[v45-15-16]]

^<<v45-15-16,16>>^ para ser ministro de Cristo Jesus entre os gentios, ministrando o evangelho de Deus, para que sejam aceitáveis os gentios como oferta, santificada pelo Espírito Santo.

[[v45-15-17]]

^<<v45-15-17,17>>^ Tenho, portanto, motivo para me gloriar em Cristo Jesus, nas coisas concernentes a Deus;

[[v45-15-18]]

^<<v45-15-18,18>>^ porque não ousarei falar de coisa alguma senão daquilo que Cristo por meu intermédio tem feito, para obediência da parte dos gentios, por palavra e por obras,

[[v45-15-19]]

^<<v45-15-19,19>>^ pelo poder de sinais e prodígios, no poder do Espírito Santo; de modo que desde Jerusalém e arredores, até a Ilíria, tenho divulgado o evangelho de Cristo;

[[v45-15-20]]

^<<v45-15-20,20>>^ deste modo esforçando-me por anunciar o evangelho, não onde Cristo houvera sido nomeado, para não edificar sobre fundamento alheio;

[[v45-15-21]]

^<<v45-15-21,21>>^ antes, como está escrito: Aqueles a quem não foi anunciado, o verão; e os que não ouviram, entenderão.

[[v45-15-22]]

^<<v45-15-22,22>>^ Pelo que também muitas vezes tenho sido impedido de ir ter convosco;

[[v45-15-23]]

^<<v45-15-23,23>>^ mas agora, não tendo mais o que me detenha nestas regiões, e tendo já há muitos anos grande desejo de ir visitar-vos,

[[v45-15-24]]

^<<v45-15-24,24>>^ eu o farei quando for à Espanha; pois espero ver-vos de passagem e por vós ser encaminhado para lá, depois de ter gozado um pouco da vossa companhia.

[[v45-15-25]]

^<<v45-15-25,25>>^ Mas agora vou a Jerusalém para ministrar aos santos.

[[v45-15-26]]

^<<v45-15-26,26>>^ Porque pareceu bem à Macedônia e à Acaia levantar uma oferta fraternal para os pobres dentre os santos que estão em Jerusalém.

[[v45-15-27]]

^<<v45-15-27,27>>^ Isto pois lhes pareceu bem, como devedores que são para com eles. Porque, se os gentios foram participantes das bênçãos espirituais dos judeus, devem também servir a estes com as materiais.

[[v45-15-28]]

^<<v45-15-28,28>>^ Tendo, pois, concluído isto, e havendo-lhes consignado este fruto, de lá, passando por vós, irei à Espanha.

[[v45-15-29]]

^<<v45-15-29,29>>^ E bem sei que, quando for visitar-vos, chegarei na plenitude da bênção de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ Rogo-vos, irmãos, por nosso Senhor Jesus Cristo e pelo amor do Espírito, que luteis juntamente comigo nas vossas orações por mim a Deus,

[[v45-15-31]]

^<<v45-15-31,31>>^ para que eu seja livre dos rebeldes que estão na Judéia, e que este meu ministério em Jerusalém seja aceitável aos santos;

[[v45-15-32]]

^<<v45-15-32,32>>^ a fim de que, pela vontade de Deus, eu chegue até vós com alegria, e possa entre vós recobrar as forças.

[[v45-15-33]]

^<<v45-15-33,33>>^ E o Deus de paz seja com todos vós. Amém.

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]