include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-13-1]]

^<<v45-13-1,1>>^ Toda alma esteja sujeita às autoridades superiores; porque não há autoridade que não venha de Deus; e as que existem foram ordenadas por Deus.

[[v45-13-2]]

^<<v45-13-2,2>>^ Por isso quem resiste à autoridade resiste à ordenação de Deus; e os que resistem trarão sobre si mesmos a condenação.

[[v45-13-3]]

^<<v45-13-3,3>>^ Porque os magistrados não são motivo de temor para os que fazem o bem, mas para os que fazem o mal. Queres tu, pois, não temer a autoridade? Faze o bem, e terás louvor dela;

[[v45-13-4]]

^<<v45-13-4,4>>^ porquanto ela é ministro de Deus para teu bem. Mas, se fizeres o mal, teme, pois não traz debalde a espada; porque é ministro de Deus, e vingador em ira contra aquele que pratica o mal.

[[v45-13-5]]

^<<v45-13-5,5>>^ Pelo que é necessário que lhe estejais sujeitos, não somente por causa da ira, mas também por causa da consciência.

[[v45-13-6]]

^<<v45-13-6,6>>^ Por esta razão também pagais tributo; porque são ministros de Deus, para atenderem a isso mesmo.

[[v45-13-7]]

^<<v45-13-7,7>>^ Dai a cada um o que lhe é devido: a quem tributo, tributo; a quem imposto, imposto; a quem temor, temor; a quem honra, honra.

[[v45-13-8]]

^<<v45-13-8,8>>^ A ninguém devais coisa alguma, senão o amor recíproco; pois quem ama ao próximo tem cumprido a lei.

[[v45-13-9]]

^<<v45-13-9,9>>^ Com efeito: Não adulterarás; não matarás; não furtarás; não cobiçarás; e se há algum outro mandamento, tudo nesta palavra se resume: Amarás ao teu próximo como a ti mesmo.

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não faz mal ao próximo. De modo que o amor é o cumprimento da lei.

[[v45-13-11]]

^<<v45-13-11,11>>^ E isso fazei, conhecendo o tempo, que já é hora de despertardes do sono; porque a nossa salvação está agora mais perto de nós do que quando nos tornamos crentes.

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite é passada, e o dia é chegado; dispamo-nos, pois, das obras das trevas, e vistamo-nos, pois, das obras das trevas, e vistamo-nos das armas da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Andemos honestamente, como de dia: não em glutonarias e bebedeiras, não em impudicícias e dissoluções, não em contendas e inveja.

[[v45-13-14]]

^<<v45-13-14,14>>^ Mas revesti-vos do Senhor Jesus Cristo; e não tenhais cuidado da carne em suas concupiscências.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]