include::./index.adoc[]

[[v45-11-0]]
=== Romanos, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-11-1]]

^<<v45-11-1,1>>^ Pergunto, pois: Acaso rejeitou Deus ao seu povo? De modo nenhum; por que eu também sou israelita, da descendência de Abraão, da tribo de Benjamim.

[[v45-11-2]]

^<<v45-11-2,2>>^ Deus não rejeitou ao seu povo que antes conheceu. Ou não sabeis o que a Escritura diz de Elias, como ele fala a Deus contra Israel, dizendo:

[[v45-11-3]]

^<<v45-11-3,3>>^ Senhor, mataram os teus profetas, e derribaram os teus altares; e só eu fiquei, e procuraram tirar-me a vida?

[[v45-11-4]]

^<<v45-11-4,4>>^ Mas que lhe diz a resposta divina? Reservei para mim sete mil varões que não dobraram os joelhos diante de Baal.

[[v45-11-5]]

^<<v45-11-5,5>>^ Assim, pois, também no tempo presente ficou um remanescente segundo a eleição da graça.

[[v45-11-6]]

^<<v45-11-6,6>>^ Mas se é pela graça, já não é pelas obras; de outra maneira, a graça já não é graça.

[[v45-11-7]]

^<<v45-11-7,7>>^ Pois quê? O que Israel busca, isso não o alcançou; mas os eleitos alcançaram; e os outros foram endurecidos,

[[v45-11-8]]

^<<v45-11-8,8>>^ como está escrito: Deus lhes deu um espírito entorpecido, olhos para não verem, e ouvidos para não ouvirem, até o dia de hoje.

[[v45-11-9]]

^<<v45-11-9,9>>^ E Davi diz: Torne-se-lhes a sua mesa em laço, e em armadilha, e em tropeço, e em retribuição;

[[v45-11-10]]

^<<v45-11-10,10>>^ escureçam-se-lhes os olhos para não verem, e tu encurva-lhes sempre as costas.

[[v45-11-11]]

^<<v45-11-11,11>>^ Logo, pergunto: Porventura tropeçaram de modo que caíssem? De maneira nenhuma, antes pelo seu tropeço veio a salvação aos gentios, para os incitar à emulação.

[[v45-11-12]]

^<<v45-11-12,12>>^ Ora se o tropeço deles é a riqueza do mundo, e a sua diminuição a riqueza dos gentios, quanto mais a sua plenitude!

[[v45-11-13]]

^<<v45-11-13,13>>^ Mas é a vós, gentios, que falo; e, porquanto sou apóstolo dos gentios, glorifico o meu ministério,

[[v45-11-14]]

^<<v45-11-14,14>>^ para ver se de algum modo posso incitar à emulação os da minha raça e salvar alguns deles.

[[v45-11-15]]

^<<v45-11-15,15>>^ Porque, se a sua rejeição é a reconciliação do mundo, qual será a sua admissão, senão a vida dentre os mortos?

[[v45-11-16]]

^<<v45-11-16,16>>^ Se as primícias são santas, também a massa o é; e se a raiz é santa, também os ramos o são.

[[v45-11-17]]

^<<v45-11-17,17>>^ E se alguns dos ramos foram quebrados, e tu, sendo zambujeiro, foste enxertado no lugar deles e feito participante da raiz e da seiva da oliveira,

[[v45-11-18]]

^<<v45-11-18,18>>^ não te glories contra os ramos; e, se contra eles te gloriares, não és tu que sustentas a raiz, mas a raiz a ti.

[[v45-11-19]]

^<<v45-11-19,19>>^ Dirás então: Os ramos foram quebrados, para que eu fosse enxertado.

[[v45-11-20]]

^<<v45-11-20,20>>^ Está bem; pela sua incredulidade foram quebrados, e tu pela tua fé estás firme. Não te ensoberbeças, mas teme;

[[v45-11-21]]

^<<v45-11-21,21>>^ porque, se Deus não poupou os ramos naturais, não te poupará a ti.

[[v45-11-22]]

^<<v45-11-22,22>>^ Considera pois a bondade e a severidade de Deus: para com os que caíram, severidade; para contigo, a bondade de Deus, se permaneceres nessa bondade; do contrário também tu serás cortado.

[[v45-11-23]]

^<<v45-11-23,23>>^ E ainda eles, se não permanecerem na incredulidade, serão enxertados; porque poderoso é Deus para os enxertar novamente.

[[v45-11-24]]

^<<v45-11-24,24>>^ Pois se tu foste cortado do natural zambujeiro, e contra a natureza enxertado em oliveira legítima, quanto mais não serão enxertados na sua própria oliveira esses que são ramos naturais!

[[v45-11-25]]

^<<v45-11-25,25>>^ Porque não quero, irmãos, que ignoreis este mistério &#123;para que não presumais de vós mesmos&#125;: que o endurecimento veio em parte sobre Israel, até que a plenitude dos gentios haja entrado;

[[v45-11-26]]

^<<v45-11-26,26>>^ e assim todo o Israel será salvo, como está escrito: Virá de Sião o Libertador, e desviará de Jacó as impiedades;

[[v45-11-27]]

^<<v45-11-27,27>>^ e este será o meu pacto com eles, quando eu tirar os seus pecados.

[[v45-11-28]]

^<<v45-11-28,28>>^ Quanto ao evangelho, eles na verdade, são inimigos por causa de vós; mas, quanto à eleição, amados por causa dos pais.

[[v45-11-29]]

^<<v45-11-29,29>>^ Porque os dons e a vocação de Deus são irretratáveis.

[[v45-11-30]]

^<<v45-11-30,30>>^ Pois, assim como vós outrora fostes desobedientes a Deus, mas agora alcançastes misericórdia pela desobediência deles,

[[v45-11-31]]

^<<v45-11-31,31>>^ assim também estes agora foram desobedientes, para também alcançarem misericórdia pela misericórdia a vós demonstrada.

[[v45-11-32]]

^<<v45-11-32,32>>^ Porque Deus encerrou a todos debaixo da desobediência, a fim de usar de misericórdia para com todos.

[[v45-11-33]]

^<<v45-11-33,33>>^ Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis os seus caminhos!

[[v45-11-34]]

^<<v45-11-34,34>>^ Pois, quem jamais conheceu a mente do Senhor? ou quem se fez seu conselheiro?

[[v45-11-35]]

^<<v45-11-35,35>>^ Ou quem lhe deu primeiro a ele, para que lhe seja recompensado?

[[v45-11-36]]

^<<v45-11-36,36>>^ Porque dele, e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém.

'''

xref:045-romanos/045-romanos-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romanos/045-romanos-012.adoc#v45-12-0[Próximo Capítulo &#62;]