include::./index.adoc[]

[[v45-1-0]]
=== Romanos, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-1-1]]

^<<v45-1-1,1>>^ Paulo, servo de Jesus Cristo, chamado para ser apóstolo, separado para o evangelho de Deus,

[[v45-1-2]]

^<<v45-1-2,2>>^ que ele antes havia prometido pelos seus profetas nas santas Escrituras,

[[v45-1-3]]

^<<v45-1-3,3>>^ acerca de seu Filho, que nasceu da descendência de Davi segundo a carne,

[[v45-1-4]]

^<<v45-1-4,4>>^ e que com poder foi declarado Filho de Deus segundo o espírito de santidade, pela ressurreição dentre os mortos-Jesus Cristo nosso Senhor,

[[v45-1-5]]

^<<v45-1-5,5>>^ pelo qual recebemos a graça e o apostolado, por amor do seu nome, para a obediência da fé entre todos os gentios,

[[v45-1-6]]

^<<v45-1-6,6>>^ entre os quais sois também vós chamados para serdes de Jesus Cristo;

[[v45-1-7]]

^<<v45-1-7,7>>^ a todos os que estais em Roma, amados de Deus, chamados para serdes santos: Graça a vós, e paz da parte de Deus nosso Pai, e do Senhor Jesus Cristo.

[[v45-1-8]]

^<<v45-1-8,8>>^ Primeiramente dou graças ao meu Deus, mediante Jesus Cristo, por todos vós, porque em todo o mundo é anunciada a vossa fé.

[[v45-1-9]]

^<<v45-1-9,9>>^ Pois Deus, a quem sirvo em meu espírito, no evangelho de seu Filho, me é testemunha de como incessantemente faço menção de vós,

[[v45-1-10]]

^<<v45-1-10,10>>^ pedindo sempre em minhas orações que, afinal, pela vontade de Deus, se me ofereça boa ocasião para ir ter convosco.

[[v45-1-11]]

^<<v45-1-11,11>>^ Porque desejo muito ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais fortalecidos;

[[v45-1-12]]

^<<v45-1-12,12>>^ isto é, para que juntamente convosco eu seja consolado em vós pela fé mútua, vossa e minha.

[[v45-1-13]]

^<<v45-1-13,13>>^ E não quero que ignoreis, irmãos, que muitas vezes propus visitar-vos &#123;mas até agora tenho sido impedido&#125;, para conseguir algum fruto entre vós, como também entre os demais gentios.

[[v45-1-14]]

^<<v45-1-14,14>>^ Eu sou devedor, tanto a gregos como a bárbaros, tanto a sábios como a ignorantes.

[[v45-1-15]]

^<<v45-1-15,15>>^ De modo que, quanto está em mim, estou pronto para anunciar o evangelho também a vós que estais em Roma.

[[v45-1-16]]

^<<v45-1-16,16>>^ Porque não me envergonho do evangelho, pois é o poder de Deus para salvação de todo aquele que crê; primeiro do judeu, e também do grego.

[[v45-1-17]]

^<<v45-1-17,17>>^ Porque no evangelho é revelada, de fé em fé, a justiça de Deus, como está escrito: Mas o justo viverá da fé.

[[v45-1-18]]

^<<v45-1-18,18>>^ Pois do céu é revelada a ira de Deus contra toda a impiedade e injustiça dos homens que detêm a verdade em injustiça.

[[v45-1-19]]

^<<v45-1-19,19>>^ Porquanto, o que de Deus se pode conhecer, neles se manifesta, porque Deus lho manifestou.

[[v45-1-20]]

^<<v45-1-20,20>>^ Pois os seus atributos invisíveis, o seu eterno poder e divindade, são claramente vistos desde a criação do mundo, sendo percebidos mediante as coisas criadas, de modo que eles são inescusáveis;

[[v45-1-21]]

^<<v45-1-21,21>>^ porquanto, tendo conhecido a Deus, contudo não o glorificaram como Deus, nem lhe deram graças, antes nas suas especulações se desvaneceram, e o seu coração insensato se obscureceu.

[[v45-1-22]]

^<<v45-1-22,22>>^ Dizendo-se sábios, tornaram-se estultos,

[[v45-1-23]]

^<<v45-1-23,23>>^ e mudaram a glória do Deus incorruptível em semelhança da imagem de homem corruptível, e de aves, e de quadrúpedes, e de répteis.

[[v45-1-24]]

^<<v45-1-24,24>>^ Por isso Deus os entregou, nas concupiscências de seus corações, à imundícia, para serem os seus corpos desonrados entre si;

[[v45-1-25]]

^<<v45-1-25,25>>^ pois trocaram a verdade de Deus pela mentira, e adoraram e serviram à criatura antes que ao Criador, que é bendito eternamente. Amém.

[[v45-1-26]]

^<<v45-1-26,26>>^ Pelo que Deus os entregou a paixões infames. Porque até as suas mulheres mudaram o uso natural no que é contrário à natureza;

[[v45-1-27]]

^<<v45-1-27,27>>^ semelhantemente, também os varões, deixando o uso natural da mulher, se inflamaram em sua sensualidade uns para como os outros, varão com varão, cometendo torpeza e recebendo em si mesmos a devida recompensa do seu erro.

[[v45-1-28]]

^<<v45-1-28,28>>^ E assim como eles rejeitaram o conhecimento de Deus, Deus, por sua vez, os entregou a um sentimento depravado, para fazerem coisas que não convêm;

[[v45-1-29]]

^<<v45-1-29,29>>^ estando cheios de toda a injustiça, malícia, cobiça, maldade; cheios de inveja, homicídio, contenda, dolo, malignidade;

[[v45-1-30]]

^<<v45-1-30,30>>^ sendo murmuradores, detratores, aborrecedores de Deus, injuriadores, soberbos, presunçosos, inventores de males, desobedientes ao pais;

[[v45-1-31]]

^<<v45-1-31,31>>^ néscios, infiéis nos contratos, sem afeição natural, sem misericórdia;

[[v45-1-32]]

^<<v45-1-32,32>>^ os quais, conhecendo bem o decreto de Deus, que declara dignos de morte os que tais coisas praticam, não somente as fazem, mas também aprovam os que as praticam.

'''

xref:044-atos/044-atos-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romanos/045-romanos-002.adoc#v45-2-0[Próximo Capítulo &#62;]