include::./index.adoc[]

[[v45-4-0]]
=== Romanos, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-4-1]]

^<<v45-4-1,1>>^ Que diremos, pois, ter alcançado Abraão, nosso pai segundo a carne?

[[v45-4-2]]

^<<v45-4-2,2>>^ Porque, se Abraão foi justificado pelas obras, tem de que se gloriar, mas não diante de Deus.

[[v45-4-3]]

^<<v45-4-3,3>>^ Pois, que diz a Escritura? Creu Abraão a Deus, e isso lhe foi imputado como justiça.

[[v45-4-4]]

^<<v45-4-4,4>>^ Ora, ao que trabalha não se lhe conta a recompensa como dádiva, mas sim como dívida;

[[v45-4-5]]

^<<v45-4-5,5>>^ porém ao que não trabalha, mas crê naquele que justifica o ímpio, a sua fé lhe é contada como justiça;

[[v45-4-6]]

^<<v45-4-6,6>>^ assim também Davi declara bem-aventurado o homem a quem Deus atribui a justiça sem as obras, dizendo:

[[v45-4-7]]

^<<v45-4-7,7>>^ Bem-aventurados aqueles cujas iniqüidades são perdoadas, e cujos pecados são cobertos.

[[v45-4-8]]

^<<v45-4-8,8>>^ Bem-aventurado o homem a quem o Senhor não imputará o pecado.

[[v45-4-9]]

^<<v45-4-9,9>>^ Vem, pois, esta bem-aventurança sobre a circuncisão somente, ou também sobre a incircuncisão? Porque dizemos: A Abraão foi imputada a fé como justiça.

[[v45-4-10]]

^<<v45-4-10,10>>^ Como, pois, lhe foi imputada? Estando na circuncisão, ou na incircuncisão? Não na circuncisão, mas sim na incircuncisão.

[[v45-4-11]]

^<<v45-4-11,11>>^ E recebeu o sinal da circuncisão, selo da justiça da fé que teve quando ainda não era circuncidado, para que fosse pai de todos os que crêem, estando eles na incircuncisão, a fim de que a justiça lhes seja imputada,

[[v45-4-12]]

^<<v45-4-12,12>>^ bem como fosse pai dos circuncisos, dos que não somente são da circuncisão, mas também andam nas pisadas daquela fé que teve nosso pai Abraão, antes de ser circuncidado.

[[v45-4-13]]

^<<v45-4-13,13>>^ Porque não foi pela lei que veio a Abraão, ou à sua descendência, a promessa de que havia de ser herdeiro do mundo, mas pela justiça da fé.

[[v45-4-14]]

^<<v45-4-14,14>>^ Pois, se os que são da lei são herdeiros, logo a fé é vã e a promessa é anulada.

[[v45-4-15]]

^<<v45-4-15,15>>^ Porque a lei opera a ira; mas onde não há lei também não há transgressão.

[[v45-4-16]]

^<<v45-4-16,16>>^ Porquanto procede da fé o ser herdeiro, para que seja segundo a graça, a fim de que a promessa seja firme a toda a descendência, não somente à que é da lei, mas também à que é da fé que teve Abraão, o qual é pai de todos nós.

[[v45-4-17]]

^<<v45-4-17,17>>^ &#123;como está escrito: Por pai de muitas nações te constituí&#125; perante aquele no qual creu, a saber, Deus, que vivifica os mortos, e chama as coisas que não são, como se já fossem.

[[v45-4-18]]

^<<v45-4-18,18>>^ O qual, em esperança, creu contra a esperança, para que se tornasse pai de muitas nações, conforme o que lhe fora dito: Assim será a tua descendência;

[[v45-4-19]]

^<<v45-4-19,19>>^ e sem se enfraquecer na fé, considerou o seu próprio corpo já amortecido &#123;pois tinha quase cem anos&#125;, e o amortecimento do ventre de Sara;

[[v45-4-20]]

^<<v45-4-20,20>>^ contudo, à vista da promessa de Deus, não vacilou por incredulidade, antes foi fortalecido na fé, dando glória a Deus,

[[v45-4-21]]

^<<v45-4-21,21>>^ e estando certíssimo de que o que Deus tinha prometido, também era poderoso para o fazer.

[[v45-4-22]]

^<<v45-4-22,22>>^ Pelo que também isso lhe foi imputado como justiça.

[[v45-4-23]]

^<<v45-4-23,23>>^ Ora, não é só por causa dele que está escrito que lhe foi imputado;

[[v45-4-24]]

^<<v45-4-24,24>>^ mas também por causa de nós a quem há de ser imputado, a nós os que cremos naquele que dos mortos ressuscitou a Jesus nosso Senhor;

[[v45-4-25]]

^<<v45-4-25,25>>^ o qual foi entregue por causa das nossas transgressões, e ressuscitado para a nossa justificação.

'''

xref:045-romanos/045-romanos-003.adoc#v45-3-0[&#60; Capítulo Anterior] | <<v45-4-0,Topo>> | xref:045-romanos/045-romanos-005.adoc#v45-5-0[Próximo Capítulo &#62;]