include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-14-1]]

^<<v45-14-1,1>>^ Ora, ao que é fraco na fé, acolhei-o, mas não para condenar-lhe os escrúpulos.

[[v45-14-2]]

^<<v45-14-2,2>>^ Um crê que de tudo se pode comer, e outro, que é fraco, come só legumes.

[[v45-14-3]]

^<<v45-14-3,3>>^ Quem come não despreze a quem não come; e quem não come não julgue a quem come; pois Deus o acolheu.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem és tu, que julgas o servo alheio? Para seu próprio senhor ele está em pé ou cai; mas estará firme, porque poderoso é o Senhor para o firmar.

[[v45-14-5]]

^<<v45-14-5,5>>^ Um faz diferença entre dia e dia, mas outro julga iguais todos os dias. Cada um esteja inteiramente convicto em sua própria mente.

[[v45-14-6]]

^<<v45-14-6,6>>^ Aquele que faz caso do dia, para o Senhor o faz. E quem come, para o Senhor come, porque dá graças a Deus; e quem não come, para o Senhor não come, e dá graças a Deus.

[[v45-14-7]]

^<<v45-14-7,7>>^ Porque nenhum de nós vive para si, e nenhum morre para si.

[[v45-14-8]]

^<<v45-14-8,8>>^ Pois, se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. De sorte que, quer vivamos quer morramos, somos do Senhor.

[[v45-14-9]]

^<<v45-14-9,9>>^ Porque foi para isto mesmo que Cristo morreu e tornou a viver, para ser Senhor tanto de mortos como de vivos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Mas tu, por que julgas teu irmão? Ou tu, também, por que desprezas teu irmão? Pois todos havemos de comparecer ante o tribunal de Deus.

[[v45-14-11]]

^<<v45-14-11,11>>^ Porque está escrito: Por minha vida, diz o Senhor, diante de mim se dobrará todo joelho, e toda língua louvará a Deus.

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, pois, cada um de nós dará conta de si mesmo a Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Portanto não nos julguemos mais uns aos outros; antes o seja o vosso propósito não pôr tropeço ou escândalo ao vosso irmão.

[[v45-14-14]]

^<<v45-14-14,14>>^ Eu sei, e estou certo no Senhor Jesus, que nada é de si mesmo imundo a não ser para aquele que assim o considera; para esse é imundo.

[[v45-14-15]]

^<<v45-14-15,15>>^ Pois, se pela tua comida se entristece teu irmão, já não andas segundo o amor. Não faças perecer por causa da tua comida aquele por quem Cristo morreu.

[[v45-14-16]]

^<<v45-14-16,16>>^ Não seja pois censurado o vosso bem;

[[v45-14-17]]

^<<v45-14-17,17>>^ porque o reino de Deus não consiste no comer e no beber, mas na justiça, na paz, e na alegria no Espírito Santo.

[[v45-14-18]]

^<<v45-14-18,18>>^ Pois quem nisso serve a Cristo agradável é a Deus e aceito aos homens.

[[v45-14-19]]

^<<v45-14-19,19>>^ Assim, pois, sigamos as coisas que servem para a paz e as que contribuem para a edificação mútua.

[[v45-14-20]]

^<<v45-14-20,20>>^ Não destruas por causa da comida a obra de Deus. Na verdade tudo é limpo, mas é um mal para o homem dar motivo de tropeço pelo comer.

[[v45-14-21]]

^<<v45-14-21,21>>^ Bom é não comer carne, nem beber vinho, nem fazer outra coisa em que teu irmão tropece.

[[v45-14-22]]

^<<v45-14-22,22>>^ A fé que tens, guarda-a contigo mesmo diante de Deus. Bem-aventurado aquele que não se condena a si mesmo naquilo que aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas aquele que tem dúvidas, se come está condenado, porque o que faz não provém da fé; e tudo o que não provém da fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]