include::./index.adoc[]

[[v45-8-0]]
=== Romanos, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-8-1]]

^<<v45-8-1,1>>^ Portanto, agora nenhuma condenação há para os que estão em Cristo Jesus.

[[v45-8-2]]

^<<v45-8-2,2>>^ Porque a lei do Espírito da vida, em Cristo Jesus, te livrou da lei do pecado e da morte.

[[v45-8-3]]

^<<v45-8-3,3>>^ Porquanto o que era impossível à lei, visto que se achava fraca pela carne, Deus enviando o seu próprio Filho em semelhança da carne do pecado, e por causa do pecado, na carne condenou o pecado.

[[v45-8-4]]

^<<v45-8-4,4>>^ para que a justa exigência da lei se cumprisse em nós, que não andamos segundo a carne, mas segundo o Espírito.

[[v45-8-5]]

^<<v45-8-5,5>>^ Pois os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito para as coisas do Espírito.

[[v45-8-6]]

^<<v45-8-6,6>>^ Porque a inclinação da carne é morte; mas a inclinação do Espírito é vida e paz.

[[v45-8-7]]

^<<v45-8-7,7>>^ Porquanto a inclinação da carne é inimizade contra Deus, pois não é sujeita à lei de Deus, nem em verdade o pode ser;

[[v45-8-8]]

^<<v45-8-8,8>>^ e os que estão na carne não podem agradar a Deus.

[[v45-8-9]]

^<<v45-8-9,9>>^ Vós, porém, não estais na carne, mas no Espírito, se é que o Espírito de Deus habita em vós. Mas, se alguém não tem o Espírito de Cristo, esse tal não é dele.

[[v45-8-10]]

^<<v45-8-10,10>>^ Ora, se Cristo está em vós, o corpo, na verdade, está morto por causa do pecado, mas o espírito vive por causa da justiça.

[[v45-8-11]]

^<<v45-8-11,11>>^ E, se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo Jesus há de vivificar também os vossos corpos mortais, pelo seu Espírito que em vós habita.

[[v45-8-12]]

^<<v45-8-12,12>>^ Portanto, irmãos, somos devedores, não à carne para vivermos segundo a carne;

[[v45-8-13]]

^<<v45-8-13,13>>^ porque se viverdes segundo a carne, haveis de morrer; mas, se pelo Espírito mortificardes as obras do corpo, vivereis.

[[v45-8-14]]

^<<v45-8-14,14>>^ Pois todos os que são guiados pelo Espírito de Deus, esses são filhos de Deus.

[[v45-8-15]]

^<<v45-8-15,15>>^ Porque não recebestes o espírito de escravidão, para outra vez estardes com temor, mas recebestes o espírito de adoção, pelo qual clamamos: Aba, Pai!

[[v45-8-16]]

^<<v45-8-16,16>>^ O Espírito mesmo testifica com o nosso espírito que somos filhos de Deus;

[[v45-8-17]]

^<<v45-8-17,17>>^ e, se filhos, também herdeiros, herdeiros de Deus e co-herdeiros de Cristo; se é certo que com ele padecemos, para que também com ele sejamos glorificados.

[[v45-8-18]]

^<<v45-8-18,18>>^ Pois tenho para mim que as aflições deste tempo presente não se podem comparar com a glória que em nós há de ser revelada.

[[v45-8-19]]

^<<v45-8-19,19>>^ Porque a criação aguarda com ardente expectativa a revelação dos filhos de Deus.

[[v45-8-20]]

^<<v45-8-20,20>>^ Porquanto a criação ficou sujeita à vaidade, não por sua vontade, mas por causa daquele que a sujeitou,

[[v45-8-21]]

^<<v45-8-21,21>>^ na esperança de que também a própria criação há de ser liberta do cativeiro da corrupção, para a liberdade da glória dos filhos de Deus.

[[v45-8-22]]

^<<v45-8-22,22>>^ Porque sabemos que toda a criação, conjuntamente, geme e está com dores de parto até agora;

[[v45-8-23]]

^<<v45-8-23,23>>^ e não só ela, mas até nós, que temos as primícias do Espírito, também gememos em nós mesmos, aguardando a nossa adoração, a saber, a redenção do nosso corpo.

[[v45-8-24]]

^<<v45-8-24,24>>^ Porque na esperança fomos salvos. Ora, a esperança que se vê não é esperança; pois o que alguém vê, como o espera?

[[v45-8-25]]

^<<v45-8-25,25>>^ Mas, se esperamos o que não vemos, com paciência o aguardamos.

[[v45-8-26]]

^<<v45-8-26,26>>^ Do mesmo modo também o Espírito nos ajuda na fraqueza; porque não sabemos o que havemos de pedir como convém, mas o Espírito mesmo intercede por nós com gemidos inexprimíveis.

[[v45-8-27]]

^<<v45-8-27,27>>^ E aquele que esquadrinha os corações sabe qual é a intenção do Espírito: que ele, segundo a vontade de Deus, intercede pelos santos.

[[v45-8-28]]

^<<v45-8-28,28>>^ E sabemos que todas as coisas concorrem para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.

[[v45-8-29]]

^<<v45-8-29,29>>^ Porque os que dantes conheceu, também os predestinou para serem conformes à imagem de seu Filho, a fim de que ele seja o primogênito entre muitos irmãos;

[[v45-8-30]]

^<<v45-8-30,30>>^ e aos que predestinou, a estes também chamou; e aos que chamou, a estes também justificou; e aos que justificou, a estes também glorificou.

[[v45-8-31]]

^<<v45-8-31,31>>^ Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?

[[v45-8-32]]

^<<v45-8-32,32>>^ Aquele que nem mesmo a seu próprio Filho poupou, antes o entregou por todos nós, como não nos dará também com ele todas as coisas?

[[v45-8-33]]

^<<v45-8-33,33>>^ Quem intentará acusação contra os escolhidos de Deus? É Deus quem os justifica;

[[v45-8-34]]

^<<v45-8-34,34>>^ Quem os condenará? Cristo Jesus é quem morreu, ou antes quem ressurgiu dentre os mortos, o qual está à direita de Deus, e também intercede por nós;

[[v45-8-35]]

^<<v45-8-35,35>>^ quem nos separará do amor de Cristo? a tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?

[[v45-8-36]]

^<<v45-8-36,36>>^ Como está escrito: Por amor de ti somos entregues à morte o dia todo; fomos considerados como ovelhas para o matadouro.

[[v45-8-37]]

^<<v45-8-37,37>>^ Mas em todas estas coisas somos mais que vencedores, por aquele que nos amou.

[[v45-8-38]]

^<<v45-8-38,38>>^ Porque estou certo de que, nem a morte, nem a vida, nem anjos, nem principados, nem coisas presentes, nem futuras, nem potestades,

[[v45-8-39]]

^<<v45-8-39,39>>^ nem a altura, nem a profundidade, nem qualquer outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor.

'''

xref:045-romanos/045-romanos-007.adoc#v45-7-0[&#60; Capítulo Anterior] | <<v45-8-0,Topo>> | xref:045-romanos/045-romanos-009.adoc#v45-9-0[Próximo Capítulo &#62;]