include::./index.adoc[]

[[v45-6-0]]
=== Romanos, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-6-1]]

^<<v45-6-1,1>>^ Que diremos, pois? Permaneceremos no pecado, para que abunde a graça?

[[v45-6-2]]

^<<v45-6-2,2>>^ De modo nenhum. Nós, que já morremos para o pecado, como viveremos ainda nele?

[[v45-6-3]]

^<<v45-6-3,3>>^ Ou, porventura, ignorais que todos quantos fomos batizados em Cristo Jesus fomos batizados na sua morte?

[[v45-6-4]]

^<<v45-6-4,4>>^ Fomos, pois, sepultados com ele pelo batismo na morte, para que, como Cristo foi ressuscitado dentre os mortos pela glória do Pai, assim andemos nós também em novidade de vida.

[[v45-6-5]]

^<<v45-6-5,5>>^ Porque, se temos sido unidos a ele na semelhança da sua morte, certamente também o seremos na semelhança da sua ressurreição;

[[v45-6-6]]

^<<v45-6-6,6>>^ sabendo isto, que o nosso homem velho foi crucificado com ele, para que o corpo do pecado fosse desfeito, a fim de não servirmos mais ao pecado.

[[v45-6-7]]

^<<v45-6-7,7>>^ Pois quem está morto está justificado do pecado.

[[v45-6-8]]

^<<v45-6-8,8>>^ Ora, se já morremos com Cristo, cremos que também com ele viveremos,

[[v45-6-9]]

^<<v45-6-9,9>>^ sabendo que, tendo Cristo ressurgido dentre os mortos, já não morre mais; a morte não mais tem domínio sobre ele.

[[v45-6-10]]

^<<v45-6-10,10>>^ Pois quanto a ter morrido, de uma vez por todas morreu para o pecado, mas quanto a viver, vive para Deus.

[[v45-6-11]]

^<<v45-6-11,11>>^ Assim também vós considerai-vos como mortos para o pecado, mas vivos para Deus, em Cristo Jesus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Não reine, portanto, o pecado em vosso corpo mortal, para obedecerdes às suas concupiscências;

[[v45-6-13]]

^<<v45-6-13,13>>^ nem tampouco apresenteis os vossos membros ao pecado como instrumentos de iniqüidade; mas apresentai-vos a Deus, como redivivos dentre os mortos, e os vossos membros a Deus, como instrumentos de justiça.

[[v45-6-14]]

^<<v45-6-14,14>>^ Pois o pecado não terá domínio sobre vós, porquanto não estais debaixo da lei, mas debaixo da graça.

[[v45-6-15]]

^<<v45-6-15,15>>^ Pois quê? Havemos de pecar porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum.

[[v45-6-16]]

^<<v45-6-16,16>>^ Não sabeis que daquele a quem vos apresentais como servos para lhe obedecer, sois servos desse mesmo a quem obedeceis, seja do pecado para a morte, ou da obediência para a justiça?

[[v45-6-17]]

^<<v45-6-17,17>>^ Mas graças a Deus que, embora tendo sido servos do pecado, obedecestes de coração à forma de doutrina a que fostes entregues;

[[v45-6-18]]

^<<v45-6-18,18>>^ e libertos do pecado, fostes feitos servos da justiça.

[[v45-6-19]]

^<<v45-6-19,19>>^ Falo como homem, por causa da fraqueza da vossa carne. Pois assim como apresentastes os vossos membros como servos da impureza e da iniqüidade para iniqüidade, assim apresentai agora os vossos membros como servos da justiça para santificação.

[[v45-6-20]]

^<<v45-6-20,20>>^ Porque, quando éreis servos do pecado, estáveis livres em relação à justiça.

[[v45-6-21]]

^<<v45-6-21,21>>^ E que fruto tínheis então das coisas de que agora vos envergonhais? pois o fim delas é a morte.

[[v45-6-22]]

^<<v45-6-22,22>>^ Mas agora, libertos do pecado, e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.

[[v45-6-23]]

^<<v45-6-23,23>>^ Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus nosso Senhor.

'''

xref:045-romanos/045-romanos-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romanos/045-romanos-007.adoc#v45-7-0[Próximo Capítulo &#62;]