include::./index.adoc[]

[[v45-16-0]]
=== Romanos, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-16-1]]

^<<v45-16-1,1>>^ Recomendo-vos a nossa irmã Febe, que é serva da igreja que está em Cencréia;

[[v45-16-2]]

^<<v45-16-2,2>>^ para que a recebais no Senhor, de um modo digno dos santos, e a ajudeis em qualquer coisa que de vós necessitar; porque ela tem sido o amparo de muitos, e de mim em particular.

[[v45-16-3]]

^<<v45-16-3,3>>^ Saudai a Prisca e a Áqüila, meus cooperadores em Cristo Jesus,

[[v45-16-4]]

^<<v45-16-4,4>>^ os quais pela minha vida expuseram as suas cabeças; o que não só eu lhes agradeço, mas também todas as igrejas dos gentios.

[[v45-16-5]]

^<<v45-16-5,5>>^ Saudai também a igreja que está na casa deles. Saudai a Epêneto, meu amado, que é as primícias da Ásia para Cristo.

[[v45-16-6]]

^<<v45-16-6,6>>^ Saudai a Maria, que muito trabalhou por vós.

[[v45-16-7]]

^<<v45-16-7,7>>^ Saudai a Andrônico e a Júnias, meus parentes e meus companheiros de prisão, os quais são bem conceituados entre os apóstolos, e que estavam em Cristo antes de mim.

[[v45-16-8]]

^<<v45-16-8,8>>^ Saudai a Ampliato, meu amado no Senhor.

[[v45-16-9]]

^<<v45-16-9,9>>^ Saudai a Urbano, nosso cooperador em Cristo, e a Estáquis, meu amado.

[[v45-16-10]]

^<<v45-16-10,10>>^ Saudai a Apeles, aprovado em Cristo. Saudai aos da casa de Aristóbulo.

[[v45-16-11]]

^<<v45-16-11,11>>^ Saudai a Herodião, meu parente. Saudai aos da casa de Narciso que estão no Senhor.

[[v45-16-12]]

^<<v45-16-12,12>>^ Saudai a Trifena e a Trifosa, que trabalham no Senhor. Saudai a amada Pérside, que muito trabalhou no Senhor.

[[v45-16-13]]

^<<v45-16-13,13>>^ Saudai a Rufo, eleito no Senhor, e a sua mãe e minha.

[[v45-16-14]]

^<<v45-16-14,14>>^ Saudai a Asíncrito, a Flegonte, a Hermes, a Pátrobas, a Hermes, e aos irmãos que estão com eles.

[[v45-16-15]]

^<<v45-16-15,15>>^ Saudai a Filólogo e a Júlia, a Nereu e a sua irmã, e a Olimpas, e a todos os santos que com eles estão.

[[v45-16-16]]

^<<v45-16-16,16>>^ Saudai-vos uns aos outros com ósculo santo. Todas as igrejas de Cristo vos saúdam.

[[v45-16-17]]

^<<v45-16-17,17>>^ Rogo-vos, irmãos, que noteis os que promovem dissensões e escândalos contra a doutrina que aprendestes; desviai-vos deles.

[[v45-16-18]]

^<<v45-16-18,18>>^ Porque os tais não servem a Cristo nosso Senhor, mas ao seu ventre; e com palavras suaves e lisonjas enganam os corações dos inocentes.

[[v45-16-19]]

^<<v45-16-19,19>>^ Pois a vossa obediência é conhecida de todos. Comprazo-me, portanto, em vós; e quero que sejais sábios para o bem, mas simples para o mal.

[[v45-16-20]]

^<<v45-16-20,20>>^ E o Deus de paz em breve esmagará a Satanás debaixo dos vossos pés. A graça de nosso Senhor Jesus Cristo seja convosco.

[[v45-16-21]]

^<<v45-16-21,21>>^ Saúdam-vos Timóteo, meu cooperador, e Lúcio, e Jáson, e Sosípatro, meus parentes.

[[v45-16-22]]

^<<v45-16-22,22>>^ Eu, Tércio, que escrevo esta carta, vos saúdo no Senhor.

[[v45-16-23]]

^<<v45-16-23,23>>^ Saúda-vos Gaio, hospedeiro meu e de toda a igreja. Saúda-vos Erasto, tesoureiro da cidade, e também o irmão Quarto.

[[v45-16-24]]

^<<v45-16-24,24>>^ &#123;A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém.&#125;

[[v45-16-25]]

^<<v45-16-25,25>>^ Ora, àquele que é poderoso para vos confirmar, segundo o meu evangelho e a pregação de Jesus Cristo, conforme a revelação do mistério guardado em silêncio desde os tempos eternos,

[[v45-16-26]]

^<<v45-16-26,26>>^ mas agora manifesto e, por meio das Escrituras proféticas, segundo o mandamento do Deus, eterno, dado a conhecer a todas as nações para obediência da fé;

[[v45-16-27]]

^<<v45-16-27,27>>^ ao único Deus sábio seja dada glória por Jesus Cristo para todo o sempre. Amém.

'''

xref:045-romanos/045-romanos-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[Próximo Capítulo &#62;]