include::./index.adoc[]

[[v45-2-0]]
=== Romanos, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-2-1]]

^<<v45-2-1,1>>^ Portanto, és inescusável, ó homem, qualquer que sejas, quando julgas, porque te condenas a ti mesmo naquilo em que julgas a outro; pois tu que julgas, praticas o mesmo.

[[v45-2-2]]

^<<v45-2-2,2>>^ E bem sabemos que o juízo de Deus é segundo a verdade, contra os que tais coisas praticam.

[[v45-2-3]]

^<<v45-2-3,3>>^ E tu, ó homem, que julgas os que praticam tais coisas, cuidas que, fazendo-as tu, escaparás ao juízo de Deus?

[[v45-2-4]]

^<<v45-2-4,4>>^ Ou desprezas tu as riquezas da sua benignidade, e paciência e longanimidade, ignorando que a benignidade de Deus te conduz ao arrependimento?

[[v45-2-5]]

^<<v45-2-5,5>>^ Mas, segundo a tua dureza e teu coração impenitente, entesouras ira para ti no dia da ira e da revelação do justo juízo de Deus,

[[v45-2-6]]

^<<v45-2-6,6>>^ que retribuirá a cada um segundo as suas obras;

[[v45-2-7]]

^<<v45-2-7,7>>^ a saber: a vida eterna aos que, com perseverança em favor o bem, procuram glória, e honra e incorrupção;

[[v45-2-8]]

^<<v45-2-8,8>>^ mas ira e indignação aos que são contenciosos, e desobedientes à iniqüidade;

[[v45-2-9]]

^<<v45-2-9,9>>^ tribulação e angústia sobre a alma de todo homem que pratica o mal, primeiramente do judeu, e também do grego;

[[v45-2-10]]

^<<v45-2-10,10>>^ glória, porém, e honra e paz a todo aquele que pratica o bem, primeiramente ao judeu, e também ao grego;

[[v45-2-11]]

^<<v45-2-11,11>>^ pois para com Deus não há acepção de pessoas.

[[v45-2-12]]

^<<v45-2-12,12>>^ Porque todos os que sem lei pecaram, sem lei também perecerão; e todos os que sob a lei pecaram, pela lei serão julgados.

[[v45-2-13]]

^<<v45-2-13,13>>^ Pois não são justos diante de Deus os que só ouvem a lei; mas serão justificados os que praticam a lei

[[v45-2-14]]

^<<v45-2-14,14>>^ &#123;porque, quando os gentios, que não têm lei, fazem por natureza as coisas da lei, eles, embora não tendo lei, para si mesmos são lei.

[[v45-2-15]]

^<<v45-2-15,15>>^ pois mostram a obra da lei escrita em seus corações, testificando juntamente a sua consciência e os seus pensamentos, quer acusando-os, quer defendendo-os&#125;,

[[v45-2-16]]

^<<v45-2-16,16>>^ no dia em que Deus há de julgar os segredos dos homens, por Cristo Jesus, segundo o meu evangelho.

[[v45-2-17]]

^<<v45-2-17,17>>^ Mas se tu és chamado judeu, e repousas na lei, e te glorias em Deus;

[[v45-2-18]]

^<<v45-2-18,18>>^ e conheces a sua vontade e aprovas as coisas excelentes, sendo instruído na lei;

[[v45-2-19]]

^<<v45-2-19,19>>^ e confias que és guia dos cegos, luz dos que estão em trevas,

[[v45-2-20]]

^<<v45-2-20,20>>^ instruidor dos néscios, mestre de crianças, que tens na lei a forma da ciência e da verdade;

[[v45-2-21]]

^<<v45-2-21,21>>^ tu, pois, que ensinas a outrem, não te ensinas a ti mesmo? Tu, que pregas que não se deve furtar, furtas?

[[v45-2-22]]

^<<v45-2-22,22>>^ Tu, que dizes que não se deve cometer adultério, adulteras? Tu, que abominas os ídolos, roubas os templos?

[[v45-2-23]]

^<<v45-2-23,23>>^ Tu, que te glorias na lei, desonras a Deus pela transgressão da lei?

[[v45-2-24]]

^<<v45-2-24,24>>^ Assim pois, por vossa causa, o nome de Deus é blasfemado entre os gentios, como está escrito.

[[v45-2-25]]

^<<v45-2-25,25>>^ Porque a circuncisão é, na verdade, proveitosa, se guardares a lei; mas se tu és transgressor da lei, a tua circuncisão tem-se tornado em incircuncisão.

[[v45-2-26]]

^<<v45-2-26,26>>^ Se, pois, a incircuncisão guardar os preceitos da lei, porventura a incircuncisão não será reputada como circuncisão?

[[v45-2-27]]

^<<v45-2-27,27>>^ E a incircuncisão que por natureza o é, se cumpre a lei, julgará a ti, que com a letra e a circuncisão és transgressor da lei.

[[v45-2-28]]

^<<v45-2-28,28>>^ Porque não é judeu o que o é exteriormente, nem é circuncisão a que o é exteriormente na carne.

[[v45-2-29]]

^<<v45-2-29,29>>^ Mas é judeu aquele que o é interiormente, e circuncisão é a do coração, no espírito, e não na letra; cujo louvor não provém dos homens, mas de Deus.

'''

xref:045-romanos/045-romanos-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romanos/045-romanos-003.adoc#v45-3-0[Próximo Capítulo &#62;]