include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-10-1]]

^<<v45-10-1,1>>^ Irmãos, o bom desejo do meu coração e a minha súplica a Deus por Israel é para sua salvação.

[[v45-10-2]]

^<<v45-10-2,2>>^ Porque lhes dou testemunho de que têm zelo por Deus, mas não com entendimento.

[[v45-10-3]]

^<<v45-10-3,3>>^ Porquanto, não conhecendo a justiça de Deus, e procurando estabelecer a sua própria, não se sujeitaram à justiça de Deus.

[[v45-10-4]]

^<<v45-10-4,4>>^ Pois Cristo é o fim da lei para justificar a todo aquele que crê.

[[v45-10-5]]

^<<v45-10-5,5>>^ Porque Moisés escreve que o homem que pratica a justiça que vem da lei viverá por ela.

[[v45-10-6]]

^<<v45-10-6,6>>^ Mas a justiça que vem da fé diz assim: Não digas em teu coração: Quem subirá ao céu? &#123;isto é, a trazer do alto a Cristo;&#125;

[[v45-10-7]]

^<<v45-10-7,7>>^ ou: Quem descerá ao abismo? &#123;isto é, a fazer subir a Cristo dentre os mortos&#125;.

[[v45-10-8]]

^<<v45-10-8,8>>^ Mas que diz? A palavra está perto de ti, na tua boca e no teu coração; isto é, a palavra da fé, que pregamos.

[[v45-10-9]]

^<<v45-10-9,9>>^ Porque, se com a tua boca confessares a Jesus como Senhor, e em teu coração creres que Deus o ressuscitou dentre os mortos, será salvo;

[[v45-10-10]]

^<<v45-10-10,10>>^ pois é com o coração que se crê para a justiça, e com a boca se faz confissão para a salvação.

[[v45-10-11]]

^<<v45-10-11,11>>^ Porque a Escritura diz: Ninguém que nele crê será confundido.

[[v45-10-12]]

^<<v45-10-12,12>>^ Porquanto não há distinção entre judeu e grego; porque o mesmo Senhor o é de todos, rico para com todos os que o invocam.

[[v45-10-13]]

^<<v45-10-13,13>>^ Porque: Todo aquele que invocar o nome do Senhor será salvo.

[[v45-10-14]]

^<<v45-10-14,14>>^ Como pois invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram falar? e como ouvirão, se não há quem pregue?

[[v45-10-15]]

^<<v45-10-15,15>>^ E como pregarão, se não forem enviados? assim como está escrito: Quão formosos os pés dos que anunciam coisas boas!

[[v45-10-16]]

^<<v45-10-16,16>>^ Mas nem todos deram ouvidos ao evangelho; pois Isaías diz: Senhor, quem deu crédito à nossa mensagem?

[[v45-10-17]]

^<<v45-10-17,17>>^ Logo a fé é pelo ouvir, e o ouvir pela palavra de Cristo.

[[v45-10-18]]

^<<v45-10-18,18>>^ Mas pergunto: Porventura não ouviram? Sim, por certo: Por toda a terra saiu a voz deles, e as suas palavras até os confins do mundo.

[[v45-10-19]]

^<<v45-10-19,19>>^ Mas pergunto ainda: Porventura Israel não o soube? Primeiro diz Moisés: Eu vos porei em ciúmes com aqueles que não são povo, com um povo insensato vos provocarei à ira.

[[v45-10-20]]

^<<v45-10-20,20>>^ E Isaías ousou dizer: Fui achado pelos que não me buscavam, manifestei-me aos que por mim não perguntavam.

[[v45-10-21]]

^<<v45-10-21,21>>^ Quanto a Israel, porém, diz: Todo o dia estendi as minhas mãos a um povo rebelde e contradizente.

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]