include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-9-1]]

^<<v45-9-1,1>>^ Digo a verdade em Cristo, não minto, dando testemunho comigo a minha consciência no Espírito Santo,

[[v45-9-2]]

^<<v45-9-2,2>>^ que tenho grande tristeza e incessante dor no meu coração.

[[v45-9-3]]

^<<v45-9-3,3>>^ Porque eu mesmo desejaria ser separado de Cristo, por amor de meus irmãos, que são meus parentes segundo a carne;

[[v45-9-4]]

^<<v45-9-4,4>>^ os quais são israelitas, de quem é a adoção, e a glória, e os pactos, e a promulgação da lei, e o culto, e as promessas;

[[v45-9-5]]

^<<v45-9-5,5>>^ de quem são os patriarcas; e de quem descende o Cristo segundo a carne, o qual é sobre todas as coisas, Deus bendito eternamente. Amém.

[[v45-9-6]]

^<<v45-9-6,6>>^ Não que a palavra de Deus haja falhado. Porque nem todos os que são de Israel são israelitas;

[[v45-9-7]]

^<<v45-9-7,7>>^ nem por serem descendência de Abraão são todos filhos; mas: Em Isaque será chamada a tua descendência.

[[v45-9-8]]

^<<v45-9-8,8>>^ Isto é, não são os filhos da carne que são filhos de Deus; mas os filhos da promessa são contados como descendência.

[[v45-9-9]]

^<<v45-9-9,9>>^ Porque a palavra da promessa é esta: Por este tempo virei, e Sara terá um filho.

[[v45-9-10]]

^<<v45-9-10,10>>^ E não somente isso, mas também a Rebeca, que havia concebido de um, de Isaque, nosso pai

[[v45-9-11]]

^<<v45-9-11,11>>^ &#123;pois não tendo os gêmeos ainda nascido, nem tendo praticado bem ou mal, para que o propósito de Deus segundo a eleição permanecesse firme, não por causa das obras, mas por aquele que chama&#125;,

[[v45-9-12]]

^<<v45-9-12,12>>^ foi-lhe dito: O maior servirá o menor.

[[v45-9-13]]

^<<v45-9-13,13>>^ Como está escrito: Amei a Jacó, e aborreci a Esaú.

[[v45-9-14]]

^<<v45-9-14,14>>^ Que diremos, pois? Há injustiça da parte de Deus? De modo nenhum.

[[v45-9-15]]

^<<v45-9-15,15>>^ Porque diz a Moisés: Terei misericórdia de quem me aprouver ter misericórdia, e terei compaixão de quem me aprouver ter compaixão.

[[v45-9-16]]

^<<v45-9-16,16>>^ Assim, pois, isto não depende do que quer, nem do que corre, mas de Deus que usa de misericórdia.

[[v45-9-17]]

^<<v45-9-17,17>>^ Pois diz a Escritura a Faraó: Para isto mesmo te levantei: para em ti mostrar o meu poder, e para que seja anunciado o meu nome em toda a terra.

[[v45-9-18]]

^<<v45-9-18,18>>^ Portanto, tem misericórdia de quem quer, e a quem quer endurece.

[[v45-9-19]]

^<<v45-9-19,19>>^ Dir-me-ás então. Por que se queixa ele ainda? Pois, quem resiste à sua vontade?

[[v45-9-20]]

^<<v45-9-20,20>>^ Mas, ó homem, quem és tu, que a Deus replicas? Porventura a coisa formada dirá ao que a formou: Por que me fizeste assim?

[[v45-9-21]]

^<<v45-9-21,21>>^ Ou não tem o oleiro poder sobre o barro, para da mesma massa fazer um vaso para uso honroso e outro para uso desonroso?

[[v45-9-22]]

^<<v45-9-22,22>>^ E que direis, se Deus, querendo mostrar a sua ira, e dar a conhecer o seu poder, suportou com muita paciência os vasos da ira, preparados para a perdição;

[[v45-9-23]]

^<<v45-9-23,23>>^ para que também desse a conhecer as riquezas da sua glória nos vasos de misericórdia, que de antemão preparou para a glória,

[[v45-9-24]]

^<<v45-9-24,24>>^ os quais somos nós, a quem também chamou, não só dentre os judeus, mas também dentre os gentios?

[[v45-9-25]]

^<<v45-9-25,25>>^ Como diz ele também em Oséias: Chamarei meu povo ao que não era meu povo; e amada à que não era amada.

[[v45-9-26]]

^<<v45-9-26,26>>^ E sucederá que no lugar em que lhes foi dito: Vós não sois meu povo; aí serão chamados filhos do Deus vivo.

[[v45-9-27]]

^<<v45-9-27,27>>^ Também Isaías exclama acerca de Israel: Ainda que o número dos filhos de Israel seja como a areia do mar, o remanescente é que será salvo.

[[v45-9-28]]

^<<v45-9-28,28>>^ Porque o Senhor executará a sua palavra sobre a terra, consumando-a e abreviando-a.

[[v45-9-29]]

^<<v45-9-29,29>>^ E como antes dissera Isaías: Se o Senhor dos Exércitos não nos tivesse deixado descendência, teríamos sido feitos como Sodoma, e seríamos semelhantes a Gomorra.

[[v45-9-30]]

^<<v45-9-30,30>>^ Que diremos pois? Que os gentios, que não buscavam a justiça, alcançaram a justiça, mas a justiça que vem da fé.

[[v45-9-31]]

^<<v45-9-31,31>>^ Mas Israel, buscando a lei da justiça, não atingiu esta lei.

[[v45-9-32]]

^<<v45-9-32,32>>^ Por que? Porque não a buscavam pela fé, mas como que pelas obras; e tropeçaram na pedra de tropeço;

[[v45-9-33]]

^<<v45-9-33,33>>^ como está escrito: Eis que eu ponho em Sião uma pedra de tropeço; e uma rocha de escândalo; e quem nela crer não será confundido.

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]