include::./index.adoc[]

[[v45-12-0]]
=== Romanos, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v45-12-1]]

^<<v45-12-1,1>>^ Rogo-vos pois, irmãos, pela compaixão de Deus, que apresenteis os vossos corpos como um sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional.

[[v45-12-2]]

^<<v45-12-2,2>>^ E não vos conformeis a este mundo, mas transformai-vos pela renovação da vossa mente, para que experimenteis qual seja a boa, agradável, e perfeita vontade de Deus.

[[v45-12-3]]

^<<v45-12-3,3>>^ Porque pela graça que me foi dada, digo a cada um dentre vós que não tenha de si mesmo mais alto conceito do que convém; mas que pense de si sobriamente, conforme a medida da fé que Deus, repartiu a cada um.

[[v45-12-4]]

^<<v45-12-4,4>>^ Pois assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma função,

[[v45-12-5]]

^<<v45-12-5,5>>^ assim nós, embora muitos, somos um só corpo em Cristo, e individualmente uns dos outros.

[[v45-12-6]]

^<<v45-12-6,6>>^ De modo que, tendo diferentes dons segundo a graça que nos foi dada, se é profecia, seja ela segundo a medida da fé;

[[v45-12-7]]

^<<v45-12-7,7>>^ se é ministério, seja em ministrar; se é ensinar, haja dedicação ao ensino;

[[v45-12-8]]

^<<v45-12-8,8>>^ ou que exorta, use esse dom em exortar; o que reparte, faça-o com liberalidade; o que preside, com zelo; o que usa de misericórdia, com alegria.

[[v45-12-9]]

^<<v45-12-9,9>>^ O amor seja não fingido. Aborrecei o mal e apegai-vos ao bem.

[[v45-12-10]]

^<<v45-12-10,10>>^ Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros;

[[v45-12-11]]

^<<v45-12-11,11>>^ não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor;

[[v45-12-12]]

^<<v45-12-12,12>>^ alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração;

[[v45-12-13]]

^<<v45-12-13,13>>^ acudi aos santos nas suas necessidades, exercei a hospitalidade;

[[v45-12-14]]

^<<v45-12-14,14>>^ abençoai aos que vos perseguem; abençoai, e não amaldiçoeis;

[[v45-12-15]]

^<<v45-12-15,15>>^ alegrai-vos com os que se alegram; chorai com os que choram;

[[v45-12-16]]

^<<v45-12-16,16>>^ sede unânimes entre vós; não ambicioneis coisas altivas mas acomodai-vos às humildes; não sejais sábios aos vossos olhos;

[[v45-12-17]]

^<<v45-12-17,17>>^ a ninguém torneis mal por mal; procurai as coisas dignas, perante todos os homens.

[[v45-12-18]]

^<<v45-12-18,18>>^ Se for possível, quanto depender de vós, tende paz com todos os homens.

[[v45-12-19]]

^<<v45-12-19,19>>^ Não vos vingueis a vós mesmos, amados, mas dai lugar à ira de Deus, porque está escrito: Minha é a vingança, eu retribuirei, diz o Senhor.

[[v45-12-20]]

^<<v45-12-20,20>>^ Antes, se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber; porque, fazendo isto amontoarás brasas de fogo sobre a sua cabeça.

[[v45-12-21]]

^<<v45-12-21,21>>^ Não te deixes vencer do mal, mas vence o mal com o bem.

'''

xref:045-romanos/045-romanos-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romanos/045-romanos-013.adoc#v45-13-0[Próximo Capítulo &#62;]