include::./index.adoc[]

[[v52-3-0]]
=== 1 Tessalonicenses, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v52-3-1]]

^<<v52-3-1,1>>^ Pelo que, não podendo mais suportar o cuidado por vós, achamos por bem ficar sozinhos em Atenas,

[[v52-3-2]]

^<<v52-3-2,2>>^ e enviamos Timóteo, nosso irmão, e ministro de Deus no evangelho de Cristo, para vos fortalecer e vos exortar acerca da vossa fé;

[[v52-3-3]]

^<<v52-3-3,3>>^ para que ninguém seja abalado por estas tribulações; porque vós mesmo sabeis que para isto fomos destinados;

[[v52-3-4]]

^<<v52-3-4,4>>^ pois, quando estávamos ainda convosco, de antemão vos declarávamos que havíamos de padecer tribulações, como sucedeu, e vós o sabeis.

[[v52-3-5]]

^<<v52-3-5,5>>^ Por isso também, não podendo eu esperar mais, mandei saber da vossa fé, receando que o tentador vos tivesse tentado, e o nosso trabalho se houvesse tornado inútil.

[[v52-3-6]]

^<<v52-3-6,6>>^ Mas agora que Timóteo acaba de regressar do vosso meio, trazendo-nos boas notícias da vossa fé e do vosso amor, dizendo que sempre nos tendes em afetuosa lembrança, anelando ver-nos assim como nós também a vós;

[[v52-3-7]]

^<<v52-3-7,7>>^ por isso, irmãos, em toda a nossa necessidade e tribulação, ficamos consolados acerca de vós, pela vossa fé,

[[v52-3-8]]

^<<v52-3-8,8>>^ porque agora vivemos, se estais firmes no Senhor.

[[v52-3-9]]

^<<v52-3-9,9>>^ Pois, que ação de graças podemos render a Deus por vós, por todo o gozo com que nos regozijamos por vossa causa diante do nosso Deus,

[[v52-3-10]]

^<<v52-3-10,10>>^ rogando incessantemente, de noite e de dia, para que possamos ver o vosso rosto e suprir o que falta à vossa fé?

[[v52-3-11]]

^<<v52-3-11,11>>^ Ora, o próprio Deus e Pai nosso e o nosso Senhor Jesus nos abram o caminho até vós,

[[v52-3-12]]

^<<v52-3-12,12>>^ e o Senhor vos faça crescer e abundar em amor uns para com os outros e para com todos, como também nós abundamos para convosco;

[[v52-3-13]]

^<<v52-3-13,13>>^ para vos confirmar os corações, de sorte que sejam irrepreensíveis em santidade diante de nosso Deus e Pai, na vinda de nosso Senhor Jesus com todos os seus santos.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[&#60; Capítulo Anterior] | <<v52-3-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[Próximo Capítulo &#62;]