include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v52-2-1]]

^<<v52-2-1,1>>^ Porque vós mesmos sabeis, irmãos, que a nossa entrada entre vós não foi vã;

[[v52-2-2]]

^<<v52-2-2,2>>^ mas, havendo anteriormente padecido e sido maltratados em Filipos, como sabeis, tivemos a confiança em nosso Deus para vos falar o evangelho de Deus em meio de grande combate.

[[v52-2-3]]

^<<v52-2-3,3>>^ Porque a nossa exortação não procede de erro, nem de imundícia, nem é feita com dolo;

[[v52-2-4]]

^<<v52-2-4,4>>^ mas, assim como fomos aprovados por Deus para que o evangelho nos fosse confiado, assim falamos, não para agradar aos homens, mas a Deus, que prova os nossos corações.

[[v52-2-5]]

^<<v52-2-5,5>>^ Pois, nunca usamos de palavras lisonjeiras, como sabeis, nem agimos com intuitos gananciosos. Deus é testemunha,

[[v52-2-6]]

^<<v52-2-6,6>>^ nem buscamos glória de homens, quer de vós, quer de outros, embora pudéssemos, como apóstolos de Cristo, ser-vos pesados;

[[v52-2-7]]

^<<v52-2-7,7>>^ antes nos apresentamos brandos entre vós, qual ama que acaricia seus próprios filhos.

[[v52-2-8]]

^<<v52-2-8,8>>^ Assim nós, sendo-vos tão afeiçoados, de boa vontade desejávamos comunicar-vos não somente o evangelho de Deus, mas ainda as nossas próprias almas; porquanto vos tornastes muito amados de nós.

[[v52-2-9]]

^<<v52-2-9,9>>^ Porque vos lembrais, irmãos, do nosso labor e fadiga; pois, trabalhando noite e dia, para não sermos pesados a nenhum de vós, vos pregamos o evangelho de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Vós e Deus sois testemunhas de quão santa e irrepreensivelmente nos portamos para convosco que credes;

[[v52-2-11]]

^<<v52-2-11,11>>^ assim como sabeis de que modo vos tratávamos a cada um de vós, como um pai a seus filhos,

[[v52-2-12]]

^<<v52-2-12,12>>^ exortando-vos e consolando-vos, e instando que andásseis de um modo digno de Deus, o qual vos chama ao seu reino e glória.

[[v52-2-13]]

^<<v52-2-13,13>>^ Por isso nós também, sem cessar, damos graças a Deus, porquanto vós, havendo recebido a palavra de Deus que de nós ouvistes, a recebestes, não como palavra de homens, mas &#123;segundo ela é na verdade&#125; como palavra de Deus, a qual também opera em vós que credes.

[[v52-2-14]]

^<<v52-2-14,14>>^ Pois vós, irmãos, vos haveis feito imitadores das igrejas de Deus em Cristo Jesus que estão na Judéia; porque também padecestes de vossos próprios concidadãos o mesmo que elas padeceram dos judeus;

[[v52-2-15]]

^<<v52-2-15,15>>^ os quais mataram ao Senhor Jesus, bem como aos profetas, e a nós nos perseguiram, e não agradam a Deus, e são contrários a todos os homens,

[[v52-2-16]]

^<<v52-2-16,16>>^ e nos impedem de falar aos gentios para que sejam salvos; de modo que enchem sempre a medida de seus pecados; mas a ira caiu sobre eles afinal.

[[v52-2-17]]

^<<v52-2-17,17>>^ Nós, porém, irmãos, sendo privados de vós por algum tempo, de vista, mas não de coração, tanto mais procuramos com grande desejo ver o vosso rosto;

[[v52-2-18]]

^<<v52-2-18,18>>^ pelo que quisemos ir ter convosco, pelo menos eu, Paulo, não somente uma vez, mas duas, e Satanás nos impediu.

[[v52-2-19]]

^<<v52-2-19,19>>^ Porque, qual é a nossa esperança, ou gozo, ou coroa de glória, diante de nosso Senhor Jesus na sua vinda? Porventura não o sois vós?

[[v52-2-20]]

^<<v52-2-20,20>>^ Na verdade vós sois a nossa glória e o nosso gozo.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]