include::./index.adoc[]

[[v52-5-0]]
=== 1 Tessalonicenses, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v52-5-1]]

^<<v52-5-1,1>>^ Mas, irmãos, acerca dos tempos e das épocas não necessitais de que se vos escreva:

[[v52-5-2]]

^<<v52-5-2,2>>^ porque vós mesmos sabeis perfeitamente que o dia do Senhor virá como vem o ladrão de noite;

[[v52-5-3]]

^<<v52-5-3,3>>^ pois quando estiverem dizendo: Paz e segurança! então lhes sobrevirá repentina destruição, como as dores de parto àquela que está grávida; e de modo nenhum escaparão.

[[v52-5-4]]

^<<v52-5-4,4>>^ Mas vós, irmãos, não estais em trevas, para que aquele dia, como ladrão, vos surpreenda;

[[v52-5-5]]

^<<v52-5-5,5>>^ porque todos vós sois filhos da luz e filhos do dia; nós não somos da noite nem das trevas;

[[v52-5-6]]

^<<v52-5-6,6>>^ não durmamos, pois, como os demais, antes vigiemos e sejamos sóbrios.

[[v52-5-7]]

^<<v52-5-7,7>>^ Porque os que dormem, dormem de noite, e os que se embriagam, embriagam-se de noite;

[[v52-5-8]]

^<<v52-5-8,8>>^ mas nós, porque somos do dia, sejamos sóbrios, vestindo-nos da couraça da fé e do amor, e tendo por capacete a esperança da salvação;

[[v52-5-9]]

^<<v52-5-9,9>>^ porque Deus não nos destinou para a ira, mas para alcançarmos a salvação por nosso Senhor Jesus Cristo,

[[v52-5-10]]

^<<v52-5-10,10>>^ que morreu por nós, para que, quer vigiemos, quer durmamos, vivamos juntamente com ele.

[[v52-5-11]]

^<<v52-5-11,11>>^ Pelo que exortai-vos uns aos outros e edificai-vos uns aos outros, como na verdade o estais fazendo.

[[v52-5-12]]

^<<v52-5-12,12>>^ Ora, rogamo-vos, irmãos, que reconheçais os que trabalham entre vós, presidem sobre vós no Senhor e vos admoestam;

[[v52-5-13]]

^<<v52-5-13,13>>^ e que os tenhais em grande estima e amor, por causa da sua obras. Tende paz entre vós.

[[v52-5-14]]

^<<v52-5-14,14>>^ Exortamo-vos também, irmãos, a que admoesteis os insubordinados, consoleis os desanimados, ampareis os fracos e sejais longânimos para com todos.

[[v52-5-15]]

^<<v52-5-15,15>>^ Vede que ninguém dê a outrem mal por mal, mas segui sempre o bem, uns para com os outros, e para com todos.

[[v52-5-16]]

^<<v52-5-16,16>>^ Regozijai-vos sempre.

[[v52-5-17]]

^<<v52-5-17,17>>^ Orai sem cessar.

[[v52-5-18]]

^<<v52-5-18,18>>^ Em tudo dai graças; porque esta é a vontade de Deus em Cristo Jesus para convosco.

[[v52-5-19]]

^<<v52-5-19,19>>^ Não extingais o Espírito;

[[v52-5-20]]

^<<v52-5-20,20>>^ não desprezeis as profecias,

[[v52-5-21]]

^<<v52-5-21,21>>^ mas ponde tudo à prova. Retende o que é bom;

[[v52-5-22]]

^<<v52-5-22,22>>^ Abstende-vos de toda espécie de mal.

[[v52-5-23]]

^<<v52-5-23,23>>^ E o próprio Deus de paz vos santifique completamente; e o vosso espírito, e alma e corpo sejam plenamente conservados irrepreensíveis para a vinda de nosso Senhor Jesus Cristo.

[[v52-5-24]]

^<<v52-5-24,24>>^ Fiel é o que vos chama, e ele também o fará.

[[v52-5-25]]

^<<v52-5-25,25>>^ Irmãos, orai por nós.

[[v52-5-26]]

^<<v52-5-26,26>>^ Saudai a todos os irmãos com ósculo santo.

[[v52-5-27]]

^<<v52-5-27,27>>^ Pelo Senhor vos conjuro que esta epístola seja lida a todos os irmãos.

[[v52-5-28]]

^<<v52-5-28,28>>^ A graça de nosso Senhor Jesus Cristo seja convosco.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[Próximo Capítulo &#62;]