include::./index.adoc[]

[[v52-1-0]]
=== 1 Tessalonicenses, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v52-1-1]]

^<<v52-1-1,1>>^ Paulo, Silvano e Timóteo, à igreja dos tessalonicenses, em Deus Pai e no Senhor Jesus Cristo: Graça e paz vos sejam dadas.

[[v52-1-2]]

^<<v52-1-2,2>>^ Sempre damos graças a Deus por vós todos, fazendo menção de vós em nossas orações,

[[v52-1-3]]

^<<v52-1-3,3>>^ lembrando-nos sem cessar da vossa obra de fé, do vosso trabalho de amor e da vossa firmeza de esperança em nosso Senhor Jesus Cristo, diante de nosso Deus e Pai,

[[v52-1-4]]

^<<v52-1-4,4>>^ conhecendo, irmãos, amados de Deus, a vossa eleição;

[[v52-1-5]]

^<<v52-1-5,5>>^ porque o nosso evangelho não foi a vós somente em palavras, mas também em poder, e no Espírito Santo e em plena convicção, como bem sabeis quais fomos entre vós por amor de vós.

[[v52-1-6]]

^<<v52-1-6,6>>^ E vós vos tornastes imitadores nossos e do Senhor, tendo recebido a palavra em muita tribulação, com gozo do Espírito Santo.

[[v52-1-7]]

^<<v52-1-7,7>>^ De sorte que vos tornastes modelo para todos os crentes na Macedônia e na Acaia.

[[v52-1-8]]

^<<v52-1-8,8>>^ Porque, partindo de vós fez-se ouvir a palavra do Senhor, não somente na Macedônia e na Acaia, mas também em todos os lugares a vossa fé para com Deus se divulgou, de tal maneira que não temos necessidade de falar coisa alguma;

[[v52-1-9]]

^<<v52-1-9,9>>^ porque eles mesmos anunciam de nós qual a entrada que tivemos entre vós, e como vos convertestes dos ídolos a Deus, para servirdes ao Deus vivo e verdadeiro,

[[v52-1-10]]

^<<v52-1-10,10>>^ e esperardes dos céus a seu Filho, a quem ele ressuscitou dentre os mortos, a saber, Jesus, que nos livra da ira vindoura.

'''

xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[Próximo Capítulo &#62;]