include::./index.adoc[]

[[v52-4-0]]
=== 1 Tessalonicenses, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v52-4-1]]

^<<v52-4-1,1>>^ Finalmente, irmãos, vos rogamos e exortamos no Senhor Jesus que, como aprendestes de nós de que maneira deveis andar e agradar a Deus, assim como estais fazendo, nisso mesmo abundeis cada vez mais.

[[v52-4-2]]

^<<v52-4-2,2>>^ Pois vós sabeis que preceitos vos temos dado pelo Senhor Jesus.

[[v52-4-3]]

^<<v52-4-3,3>>^ Porque esta é a vontade de Deus, a saber, a vossa santificação: que vos abstenhais da prostituição,

[[v52-4-4]]

^<<v52-4-4,4>>^ que cada um de vós saiba possuir o seu vaso em santidade e honra,

[[v52-4-5]]

^<<v52-4-5,5>>^ não na paixão da concupiscência, como os gentios que não conhecem a Deus;

[[v52-4-6]]

^<<v52-4-6,6>>^ ninguém iluda ou defraude nisso a seu irmão, porque o Senhor é vingador de todas estas coisas, como também antes vo-lo dissemos e testificamos.

[[v52-4-7]]

^<<v52-4-7,7>>^ Porque Deus não nos chamou para a imundícia, mas para a santificação.

[[v52-4-8]]

^<<v52-4-8,8>>^ Portanto, quem rejeita isso não rejeita ao homem, mas sim a Deus, que vos dá o seu Espírito Santo.

[[v52-4-9]]

^<<v52-4-9,9>>^ Quanto, porém, ao amor fraternal, não necessitais de que se vos escreva, visto que vós mesmos sois instruídos por Deus a vos amardes uns aos outros;

[[v52-4-10]]

^<<v52-4-10,10>>^ porque certamente já o fazeis para com todos os irmãos que estão por toda a Macedônia. Exortamo-vos, porém, irmãos, a que ainda nisto abundeis cada vez mais,

[[v52-4-11]]

^<<v52-4-11,11>>^ e procureis viver quietos, tratar dos vossos próprios negócios, e trabalhar com vossas próprias mãos, como já vo-lo mandamos,

[[v52-4-12]]

^<<v52-4-12,12>>^ a fim de que andeis dignamente para com os que estão de fora, e não tenhais necessidade de coisa alguma.

[[v52-4-13]]

^<<v52-4-13,13>>^ Não queremos, porém, irmãos, que sejais ignorantes acerca dos que já dormem, para que não vos entristeçais como os outros que não têm esperança.

[[v52-4-14]]

^<<v52-4-14,14>>^ Porque, se cremos que Jesus morreu e ressurgiu, assim também aos que dormem, Deus, mediante Jesus, os tornará a trazer juntamente com ele.

[[v52-4-15]]

^<<v52-4-15,15>>^ Dizemo-vos, pois, isto pela palavra do Senhor: que nós, os que ficarmos vivos para a vinda do Senhor, de modo algum precederemos os que já dormem.

[[v52-4-16]]

^<<v52-4-16,16>>^ Porque o Senhor mesmo descerá do céu com grande brado, à voz do arcanjo, ao som da trombeta de Deus, e os que morreram em Cristo ressuscitarão primeiro.

[[v52-4-17]]

^<<v52-4-17,17>>^ Depois nós, os que ficarmos vivos seremos arrebatados juntamente com eles, nas nuvens, ao encontro do Senhor nos ares, e assim estaremos para sempre com o Senhor.

[[v52-4-18]]

^<<v52-4-18,18>>^ Portanto, consolai-vos uns aos outros com estas palavras.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[Próximo Capítulo &#62;]