include::./index.adoc[]

[[v18-29-0]]
=== Jó, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-29-1]]

^<<v18-29-1,1>>^ E prosseguindo Jó no seu discurso, disse:

[[v18-29-2]]

^<<v18-29-2,2>>^ Ah! quem me dera ser como eu fui nos meses do passado, como nos dias em que Deus me guardava;

[[v18-29-3]]

^<<v18-29-3,3>>^ quando a sua lâmpada luzia sobre o minha cabeça, e eu com a sua luz caminhava através das trevas;

[[v18-29-4]]

^<<v18-29-4,4>>^ como era nos dias do meu vigor, quando o íntimo favor de Deus estava sobre a minha tenda;

[[v18-29-5]]

^<<v18-29-5,5>>^ quando o Todo-Poderoso ainda estava comigo, e os meus filhos em redor de mim;

[[v18-29-6]]

^<<v18-29-6,6>>^ quando os meus passos eram banhados em leite, e a rocha me deitava ribeiros de azeite!

[[v18-29-7]]

^<<v18-29-7,7>>^ Quando eu saía para a porta da cidade, e na praça preparava a minha cadeira,

[[v18-29-8]]

^<<v18-29-8,8>>^ os moços me viam e se escondiam, e os idosos se levantavam e se punham em pé;

[[v18-29-9]]

^<<v18-29-9,9>>^ os príncipes continham as suas palavras, e punham a mão sobre a sua boca;

[[v18-29-10]]

^<<v18-29-10,10>>^ a voz dos nobres emudecia, e a língua se lhes pegava ao paladar.

[[v18-29-11]]

^<<v18-29-11,11>>^ Pois, ouvindo-me algum ouvido, me tinha por bem-aventurado; e vendo-me algum olho, dava testemunho de mim;

[[v18-29-12]]

^<<v18-29-12,12>>^ porque eu livrava o miserável que clamava, e o órfão que não tinha quem o socorresse.

[[v18-29-13]]

^<<v18-29-13,13>>^ A bênção do que estava a perecer vinha sobre mim, e eu fazia rejubilar-se o coração da viúva.

[[v18-29-14]]

^<<v18-29-14,14>>^ vestia-me da retidão, e ela se vestia de mim; como manto e diadema era a minha justiça.

[[v18-29-15]]

^<<v18-29-15,15>>^ Fazia-me olhos para o cego, e pés para o coxo;

[[v18-29-16]]

^<<v18-29-16,16>>^ dos necessitados era pai, e a causa do que me era desconhecido examinava com diligência.

[[v18-29-17]]

^<<v18-29-17,17>>^ E quebrava os caninos do perverso, e arrancava-lhe a presa dentre os dentes.

[[v18-29-18]]

^<<v18-29-18,18>>^ Então dizia eu: No meu ninho expirarei, e multiplicarei os meus dias como a areia;

[[v18-29-19]]

^<<v18-29-19,19>>^ as minhas raízes se estendem até as águas, e o orvalho fica a noite toda sobre os meus ramos;

[[v18-29-20]]

^<<v18-29-20,20>>^ a minha honra se renova em mim, e o meu arco se revigora na minha mão.

[[v18-29-21]]

^<<v18-29-21,21>>^ A mim me ouviam e esperavam, e em silêncio atendiam ao meu conselho.

[[v18-29-22]]

^<<v18-29-22,22>>^ Depois de eu falar, nada replicavam, e minha palavra destilava sobre eles;

[[v18-29-23]]

^<<v18-29-23,23>>^ esperavam-me como à chuva; e abriam a sua boca como à chuva tardia.

[[v18-29-24]]

^<<v18-29-24,24>>^ Eu lhes sorria quando não tinham confiança; e não desprezavam a luz do meu rosto;

[[v18-29-25]]

^<<v18-29-25,25>>^ eu lhes escolhia o caminho, assentava-me como chefe, e habitava como rei entre as suas tropas, como aquele que consola os aflitos.

'''

xref:018-jo/018-jo-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-jo/018-jo-030.adoc#v18-30-0[Próximo Capítulo &#62;]