include::./index.adoc[]

[[v18-3-0]]
=== Jó, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-3-1]]

^<<v18-3-1,1>>^ Depois disso abriu Jó a sua boca, e amaldiçoou o seu dia.

[[v18-3-2]]

^<<v18-3-2,2>>^ E Jó falou, dizendo:

[[v18-3-3]]

^<<v18-3-3,3>>^ Pereça o dia em que nasci, e a noite que se disse: Foi concebido um homem!

[[v18-3-4]]

^<<v18-3-4,4>>^ Converta-se aquele dia em trevas; e Deus, lá de cima, não tenha cuidado dele, nem resplandeça sobre ele a luz.

[[v18-3-5]]

^<<v18-3-5,5>>^ Reclamem-no para si as trevas e a sombra da morte; habitem sobre ele nuvens; espante-o tudo o que escurece o dia.

[[v18-3-6]]

^<<v18-3-6,6>>^ Quanto àquela noite, dela se apodere a escuridão; e não se regozije ela entre os dias do ano; e não entre no número dos meses.

[[v18-3-7]]

^<<v18-3-7,7>>^ Ah! que estéril seja aquela noite, e nela não entre voz de regozijo.

[[v18-3-8]]

^<<v18-3-8,8>>^ Amaldiçoem-na aqueles que amaldiçoam os dias, que são peritos em suscitar o leviatã.

[[v18-3-9]]

^<<v18-3-9,9>>^ As estrelas da alva se lhe escureçam; espere ela em vão a luz, e não veja as pálpebras da manhã;

[[v18-3-10]]

^<<v18-3-10,10>>^ porquanto não fechou as portas do ventre de minha mãe, nem escondeu dos meus olhos a aflição.

[[v18-3-11]]

^<<v18-3-11,11>>^ Por que não morri ao nascer? por que não expirei ao vir à luz?

[[v18-3-12]]

^<<v18-3-12,12>>^ Por que me receberam os joelhos? e por que os seios, para que eu mamasse?

[[v18-3-13]]

^<<v18-3-13,13>>^ Pois agora eu estaria deitado e quieto; teria dormido e estaria em repouso,

[[v18-3-14]]

^<<v18-3-14,14>>^ com os reis e conselheiros da terra, que reedificavam ruínas para si,

[[v18-3-15]]

^<<v18-3-15,15>>^ ou com os príncipes que tinham ouro, que enchiam as suas casas de prata;

[[v18-3-16]]

^<<v18-3-16,16>>^ ou, como aborto oculto, eu não teria existido, como as crianças que nunca viram a luz.

[[v18-3-17]]

^<<v18-3-17,17>>^ Ali os ímpios cessam de perturbar; e ali repousam os cansados.

[[v18-3-18]]

^<<v18-3-18,18>>^ Ali os presos descansam juntos, e não ouvem a voz do exator.

[[v18-3-19]]

^<<v18-3-19,19>>^ O pequeno e o grande ali estão e o servo está livre de seu senhor.

[[v18-3-20]]

^<<v18-3-20,20>>^ Por que se concede luz ao aflito, e vida aos amargurados de alma;

[[v18-3-21]]

^<<v18-3-21,21>>^ que anelam pela morte sem que ela venha, e cavam em procura dela mais do que de tesouros escondidos;

[[v18-3-22]]

^<<v18-3-22,22>>^ que muito se regozijam e exultam, quando acham a sepultura?

[[v18-3-23]]

^<<v18-3-23,23>>^ Sim, por que se concede luz ao homem cujo caminho está escondido, e a quem Deus cercou de todos os lados?

[[v18-3-24]]

^<<v18-3-24,24>>^ Pois em lugar de meu pão vem o meu suspiro, e os meus gemidos se derramam como água.

[[v18-3-25]]

^<<v18-3-25,25>>^ Porque aquilo que temo me sobrevém, e o que receio me acontece.

[[v18-3-26]]

^<<v18-3-26,26>>^ Não tenho repouso, nem sossego, nem descanso; mas vem a perturbação.

'''

xref:018-jo/018-jo-002.adoc#v18-2-0[&#60; Capítulo Anterior] | <<v18-3-0,Topo>> | xref:018-jo/018-jo-004.adoc#v18-4-0[Próximo Capítulo &#62;]