include::./index.adoc[]

[[v18-37-0]]
=== Jó, 37
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-37-1]]

^<<v18-37-1,1>>^ Sobre isso também treme o meu coração, e salta do seu lugar.

[[v18-37-2]]

^<<v18-37-2,2>>^ Dai atentamente ouvidos ao estrondo da voz de Deus e ao sonido que sai da sua boca.

[[v18-37-3]]

^<<v18-37-3,3>>^ Ele o envia por debaixo de todo o céu, e o seu relâmpago até os confins da terra.

[[v18-37-4]]

^<<v18-37-4,4>>^ Depois do relâmpago ruge uma grande voz; ele troveja com a sua voz majestosa; e não retarda os raios, quando é ouvida a sua voz.

[[v18-37-5]]

^<<v18-37-5,5>>^ Com a sua voz troveja Deus maravilhosamente; faz grandes coisas, que nós não compreendemos.

[[v18-37-6]]

^<<v18-37-6,6>>^ Pois à neve diz: Cai sobre a terra; como também às chuvas e aos aguaceiros: Sede copiosos.

[[v18-37-7]]

^<<v18-37-7,7>>^ Ele sela as mãos de todo homem, para que todos saibam que ele os fez.

[[v18-37-8]]

^<<v18-37-8,8>>^ E as feras entram nos esconderijos e ficam nos seus covis.

[[v18-37-9]]

^<<v18-37-9,9>>^ Da recâmara do sul sai o tufão, e do norte o frio.

[[v18-37-10]]

^<<v18-37-10,10>>^ Ao sopro de Deus forma-se o gelo, e as largas águas são congeladas.

[[v18-37-11]]

^<<v18-37-11,11>>^ Também de umidade carrega as grossas nuvens; as nuvens espalham relâmpagos.

[[v18-37-12]]

^<<v18-37-12,12>>^ Fazem evoluções sob a sua direção, para efetuar tudo quanto lhes ordena sobre a superfície do mundo habitável:

[[v18-37-13]]

^<<v18-37-13,13>>^ seja para disciplina, ou para a sua terra, ou para beneficência, que as faça vir.

[[v18-37-14]]

^<<v18-37-14,14>>^ A isto, Jó, inclina os teus ouvidos; pára e considera as obras maravilhosas de Deus.

[[v18-37-15]]

^<<v18-37-15,15>>^ Sabes tu como Deus lhes dá as suas ordens, e faz resplandecer o relâmpago da sua nuvem?

[[v18-37-16]]

^<<v18-37-16,16>>^ Compreendes o equilíbrio das nuvens, e as maravilhas daquele que é perfeito nos conhecimentos;

[[v18-37-17]]

^<<v18-37-17,17>>^ tu cujas vestes são quentes, quando há calma sobre a terra por causa do vento sul?

[[v18-37-18]]

^<<v18-37-18,18>>^ Acaso podes, como ele, estender o firmamento, que é sólido como um espelho fundido?

[[v18-37-19]]

^<<v18-37-19,19>>^ Ensina-nos o que lhe diremos; pois nós nada poderemos pôr em boa ordem, por causa das trevas.

[[v18-37-20]]

^<<v18-37-20,20>>^ Contar-lhe-ia alguém que eu quero falar. Ou desejaria um homem ser devorado?

[[v18-37-21]]

^<<v18-37-21,21>>^ E agora o homem não pode olhar para o sol, que resplandece no céu quando o vento, tendo passado, o deixa limpo.

[[v18-37-22]]

^<<v18-37-22,22>>^ Do norte vem o áureo esplendor; em Deus há tremenda majestade.

[[v18-37-23]]

^<<v18-37-23,23>>^ Quanto ao Todo-Poderoso, não o podemos compreender; grande é em poder e justiça e pleno de retidão; a ninguém, pois, oprimirá.

[[v18-37-24]]

^<<v18-37-24,24>>^ Por isso o temem os homens; ele não respeita os que se julgam sábios.

'''

xref:018-jo/018-jo-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-jo/018-jo-038.adoc#v18-38-0[Próximo Capítulo &#62;]