include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-24-1]]

^<<v18-24-1,1>>^ Por que o Todo-Poderoso não designa tempos? e por que os que o conhecem não vêem os seus dias?

[[v18-24-2]]

^<<v18-24-2,2>>^ Há os que removem os limites; roubam os rebanhos, e os apascentam.

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam o jumento do órfão, tomam em penhor o boi da viúva.

[[v18-24-4]]

^<<v18-24-4,4>>^ Desviam do caminho os necessitados; e os oprimidos da terra juntos se escondem.

[[v18-24-5]]

^<<v18-24-5,5>>^ Eis que, como jumentos monteses no deserto, saem eles ao seu trabalho, procurando no ermo a presa que lhes sirva de sustento para seus filhos.

[[v18-24-6]]

^<<v18-24-6,6>>^ No campo segam o seu pasto, e vindimam a vinha do ímpio.

[[v18-24-7]]

^<<v18-24-7,7>>^ Passam a noite nus, sem roupa, não tendo coberta contra o frio.

[[v18-24-8]]

^<<v18-24-8,8>>^ Pelas chuvas das montanhas são molhados e, por falta de abrigo, abraçam-se com as rochas.

[[v18-24-9]]

^<<v18-24-9,9>>^ Há os que arrancam do peito o órfão, e tomam o penhor do pobre;

[[v18-24-10]]

^<<v18-24-10,10>>^ fazem que estes andem nus, sem roupa, e, embora famintos, carreguem os molhos.

[[v18-24-11]]

^<<v18-24-11,11>>^ Espremem o azeite dentro dos muros daqueles homens; pisam os seus lagares, e ainda têm sede.

[[v18-24-12]]

^<<v18-24-12,12>>^ Dentro das cidades gemem os moribundos, e a alma dos feridos clama; e contudo Deus não considera o seu clamor.

[[v18-24-13]]

^<<v18-24-13,13>>^ Há os que se revoltam contra a luz; não conhecem os caminhos dela, e não permanecem nas suas veredas.

[[v18-24-14]]

^<<v18-24-14,14>>^ O homicida se levanta de madrugada, mata o pobre e o necessitado, e de noite torna-se ladrão.

[[v18-24-15]]

^<<v18-24-15,15>>^ Também os olhos do adúltero aguardam o crepúsculo, dizendo: Ninguém me verá; e disfarça o rosto.

[[v18-24-16]]

^<<v18-24-16,16>>^ Nas trevas minam as casas; de dia se conservam encerrados; não conhecem a luz.

[[v18-24-17]]

^<<v18-24-17,17>>^ Pois para eles a profunda escuridão é a sua manhã; porque são amigos das trevas espessas.

[[v18-24-18]]

^<<v18-24-18,18>>^ São levados ligeiramente sobre a face das águas; maldita é a sua porção sobre a terra; não tornam pelo caminho das vinhas.

[[v18-24-19]]

^<<v18-24-19,19>>^ A sequidão e o calor desfazem as, águas da neve; assim faz o Seol aos que pecaram.

[[v18-24-20]]

^<<v18-24-20,20>>^ A madre se esquecerá dele; os vermes o comerão gostosamente; não será mais lembrado; e a iniqüidade se quebrará como árvore.

[[v18-24-21]]

^<<v18-24-21,21>>^ Ele despoja a estéril que não dá à luz, e não faz bem à viúva.

[[v18-24-22]]

^<<v18-24-22,22>>^ Todavia Deus prolonga a vida dos valentes com a sua força; levantam-se quando haviam desesperado da vida.

[[v18-24-23]]

^<<v18-24-23,23>>^ Se ele lhes dá descanso, estribam-se, nisso; e os seus olhos estão sobre os caminhos deles.

[[v18-24-24]]

^<<v18-24-24,24>>^ Eles se exaltam, mas logo desaparecem; são abatidos, colhidos como os demais, e cortados como as espigas do trigo.

[[v18-24-25]]

^<<v18-24-25,25>>^ Se não é assim, quem me desmentirá e desfará as minhas palavras?

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]