include::./index.adoc[]

[[v18-1-0]]
=== Jó, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-1-1]]

^<<v18-1-1,1>>^ Havia um homem na terra de Uz, cujo nome era Jó. Era homem íntegro e reto, que temia a Deus e se desviava do mal.

[[v18-1-2]]

^<<v18-1-2,2>>^ Nasceram-lhe sete filhos e três filhas.

[[v18-1-3]]

^<<v18-1-3,3>>^ Possuía ele sete mil ovelhas, três mil camelos, quinhentas juntas de bois e quinhentas jumentas, tendo também muitíssima gente ao seu serviço; de modo que este homem era o maior de todos os do Oriente.

[[v18-1-4]]

^<<v18-1-4,4>>^ Iam seus filhos à casa uns dos outros e faziam banquetes cada um por sua vez; e mandavam convidar as suas três irmãs para comerem e beberem com eles.

[[v18-1-5]]

^<<v18-1-5,5>>^ E sucedia que, tendo decorrido o turno de dias de seus banquetes, enviava Jó e os santificava; e, levantando-se de madrugada, oferecia holocaustos segundo o número de todos eles; pois dizia Jó: Talvez meus filhos tenham pecado, e blasfemado de Deus no seu coração. Assim o fazia Jó continuamente.

[[v18-1-6]]

^<<v18-1-6,6>>^ Ora, chegado o dia em que os filhos de Deus vieram apresentar-se perante o Senhor, veio também Satanás entre eles.

[[v18-1-7]]

^<<v18-1-7,7>>^ O Senhor perguntou a Satanás: Donde vens? E Satanás respondeu ao Senhor, dizendo: De rodear a terra, e de passear por ela.

[[v18-1-8]]

^<<v18-1-8,8>>^ Disse o Senhor a Satanás: Notaste porventura o meu servo Jó, que ninguém há na terra semelhante a ele, homem íntegro e reto, que teme a Deus e se desvia do mal?

[[v18-1-9]]

^<<v18-1-9,9>>^ Então respondeu Satanás ao Senhor, e disse: Porventura Jó teme a Deus debalde?

[[v18-1-10]]

^<<v18-1-10,10>>^ Não o tens protegido de todo lado a ele, a sua casa e a tudo quanto tem? Tens abençoado a obra de suas mãos, e os seus bens se multiplicam na terra.

[[v18-1-11]]

^<<v18-1-11,11>>^ Mas estende agora a tua mão, e toca-lhe em tudo quanto tem, e ele blasfemará de ti na tua face!

[[v18-1-12]]

^<<v18-1-12,12>>^ Ao que disse o Senhor a Satanás: Eis que tudo o que ele tem está no teu poder; somente contra ele não estendas a tua mão. E Satanás saiu da presença do Senhor.

[[v18-1-13]]

^<<v18-1-13,13>>^ Certo dia, quando seus filhos e suas filhas comiam e bebiam vinho em casa do irmão mais velho,

[[v18-1-14]]

^<<v18-1-14,14>>^ veio um mensageiro a Jó e lhe disse: Os bois lavravam, e as jumentas pasciam junto a eles;

[[v18-1-15]]

^<<v18-1-15,15>>^ e deram sobre eles os sabeus, e os tomaram; mataram os moços ao fio da espada, e só eu escapei para trazer-te a nova.

[[v18-1-16]]

^<<v18-1-16,16>>^ Enquanto este ainda falava, veio outro e disse: Fogo de Deus caiu do céu e queimou as ovelhas e os moços, e os consumiu; e só eu escapei para trazer-te a nova.

[[v18-1-17]]

^<<v18-1-17,17>>^ Enquanto este ainda falava, veio outro e disse: Os caldeus, dividindo-se em três bandos, deram sobre os camelos e os tomaram; e mataram os moços ao fio da espada; e só eu escapei para trazer-te a nova.

[[v18-1-18]]

^<<v18-1-18,18>>^ Enquanto este ainda falava, veio outro e disse: Teus filhos e tuas filhas estavam comendo e bebendo vinho em casa do irmão mais velho;

[[v18-1-19]]

^<<v18-1-19,19>>^ e eis que sobrevindo um grande vento de além do deserto, deu nos quatro cantos da casa, e ela caiu sobre os mancebos, de sorte que morreram; e só eu escapei para trazer-te a nova.

[[v18-1-20]]

^<<v18-1-20,20>>^ Então Jó se levantou, rasgou o seu manto, rapou a sua cabeça e, lançando-se em terra, adorou;

[[v18-1-21]]

^<<v18-1-21,21>>^ e disse: Nu saí do ventre de minha mãe, e nu tornarei para lá. O Senhor deu, e o Senhor tirou; bendito seja o nome do Senhor.

[[v18-1-22]]

^<<v18-1-22,22>>^ Em tudo isso Jó não pecou, nem atribuiu a Deus falta alguma.

'''

xref:017-ester/017-ester-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v18-1-0,Topo>> | xref:018-jo/018-jo-002.adoc#v18-2-0[Próximo Capítulo &#62;]