include::./index.adoc[]

[[v18-5-0]]
=== Jó, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-5-1]]

^<<v18-5-1,1>>^ Chama agora; há alguém que te responda; E a qual dentre os entes santos te dirigirás?

[[v18-5-2]]

^<<v18-5-2,2>>^ Pois a dor destrói o louco, e a inveja mata o tolo.

[[v18-5-3]]

^<<v18-5-3,3>>^ Bem vi eu o louco lançar raízes; mas logo amaldiçoei a sua habitação:

[[v18-5-4]]

^<<v18-5-4,4>>^ Seus filhos estão longe da segurança, e são pisados nas portas, e não há quem os livre.

[[v18-5-5]]

^<<v18-5-5,5>>^ A sua messe é devorada pelo faminto, que até dentre os espinhos a tira; e o laço abre as fauces para a fazenda deles.

[[v18-5-6]]

^<<v18-5-6,6>>^ Porque a aflição não procede do pó, nem a tribulação brota da terra;

[[v18-5-7]]

^<<v18-5-7,7>>^ mas o homem nasce para a tribulação, como as faíscas voam para cima.

[[v18-5-8]]

^<<v18-5-8,8>>^ Mas quanto a mim eu buscaria a Deus, e a Deus entregaria a minha causa;

[[v18-5-9]]

^<<v18-5-9,9>>^ o qual faz coisas grandes e inescrutáveis, maravilhas sem número.

[[v18-5-10]]

^<<v18-5-10,10>>^ Ele derrama a chuva sobre a terra, e envia águas sobre os campos.

[[v18-5-11]]

^<<v18-5-11,11>>^ Ele põe num lugar alto os abatidos; e os que choram são exaltados à segurança.

[[v18-5-12]]

^<<v18-5-12,12>>^ Ele frustra as maquinações dos astutos, de modo que as suas mãos não possam levar coisa alguma a efeito.

[[v18-5-13]]

^<<v18-5-13,13>>^ Ele apanha os sábios na sua própria astúcia, e o conselho dos perversos se precipita.

[[v18-5-14]]

^<<v18-5-14,14>>^ Eles de dia encontram as trevas, e ao meio-dia andam às apalpadelas, como de noite.

[[v18-5-15]]

^<<v18-5-15,15>>^ Mas Deus livra o necessitado da espada da boca deles, e da mão do poderoso.

[[v18-5-16]]

^<<v18-5-16,16>>^ Assim há esperança para o pobre; e a iniqüidade tapa a boca.

[[v18-5-17]]

^<<v18-5-17,17>>^ Eis que bem-aventurado é o homem a quem Deus corrige; não desprezes, pois, a correção do Todo-Poderoso.

[[v18-5-18]]

^<<v18-5-18,18>>^ Pois ele faz a ferida, e ele mesmo a liga; ele fere, e as suas mãos curam.

[[v18-5-19]]

^<<v18-5-19,19>>^ Em seis angústias te livrará, e em sete o mal não te tocará.

[[v18-5-20]]

^<<v18-5-20,20>>^ Na fome te livrará da morte, e na guerra do poder da espada.

[[v18-5-21]]

^<<v18-5-21,21>>^ Do açoite da língua estarás abrigado, e não temerás a assolação, quando chegar.

[[v18-5-22]]

^<<v18-5-22,22>>^ Da assolação e da fome te rirás, e dos animais da terra não terás medo.

[[v18-5-23]]

^<<v18-5-23,23>>^ Pois até com as pedras do campo terás a tua aliança, e as feras do campo estarão em paz contigo.

[[v18-5-24]]

^<<v18-5-24,24>>^ Saberás que a tua tenda está em paz; visitarás o teu rebanho, e nada te faltará.

[[v18-5-25]]

^<<v18-5-25,25>>^ Também saberás que se multiplicará a tua descendência e a tua posteridade como a erva da terra.

[[v18-5-26]]

^<<v18-5-26,26>>^ Em boa velhice irás à sepultura, como se recolhe o feixe de trigo a seu tempo.

[[v18-5-27]]

^<<v18-5-27,27>>^ Eis que isso já o havemos inquirido, e assim o é; ouve-o, e conhece-o para teu bem.

'''

xref:018-jo/018-jo-004.adoc#v18-4-0[&#60; Capítulo Anterior] | <<v18-5-0,Topo>> | xref:018-jo/018-jo-006.adoc#v18-6-0[Próximo Capítulo &#62;]