include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-19-1]]

^<<v18-19-1,1>>^ Então Jó respondeu:

[[v18-19-2]]

^<<v18-19-2,2>>^ Até quando afligireis a minha alma, e me atormentareis com palavras?

[[v18-19-3]]

^<<v18-19-3,3>>^ Já dez vezes me haveis humilhado; não vos envergonhais de me maltratardes?

[[v18-19-4]]

^<<v18-19-4,4>>^ Embora haja eu, na verdade, errado, comigo fica o meu erro.

[[v18-19-5]]

^<<v18-19-5,5>>^ Se deveras vos quereis engrandecer contra mim, e me incriminar pelo meu opróbrio,

[[v18-19-6]]

^<<v18-19-6,6>>^ sabei então que Deus é o que transtornou a minha causa, e com a sua rede me cercou.

[[v18-19-7]]

^<<v18-19-7,7>>^ Eis que clamo: Violência! mas não sou ouvido; grito: Socorro! mas não há justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ com muros fechou ele o meu caminho, de modo que não posso passar; e pôs trevas nas minhas veredas.

[[v18-19-9]]

^<<v18-19-9,9>>^ Da minha honra me despojou, e tirou-me da cabeça a coroa.

[[v18-19-10]]

^<<v18-19-10,10>>^ Quebrou-me de todos os lados, e eu me vou; arrancou a minha esperança, como a, uma árvore.

[[v18-19-11]]

^<<v18-19-11,11>>^ Acende contra mim a sua ira, e me considera como um de seus adversários.

[[v18-19-12]]

^<<v18-19-12,12>>^ Juntas as suas tropas avançam, levantam contra mim o seu caminho, e se acampam ao redor da minha tenda.

[[v18-19-13]]

^<<v18-19-13,13>>^ Ele pôs longe de mim os meus irmãos, e os que me conhecem tornaram-se estranhos para mim.

[[v18-19-14]]

^<<v18-19-14,14>>^ Os meus parentes se afastam, e os meus conhecidos se esquecem de, mim.

[[v18-19-15]]

^<<v18-19-15,15>>^ Os meus domésticos e as minhas servas me têm por estranho; vim a ser um estrangeiro aos seus olhos.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamo ao meu criado, e ele não me responde; tenho que suplicar-lhe com a minha boca.

[[v18-19-17]]

^<<v18-19-17,17>>^ O meu hálito é intolerável à minha mulher; sou repugnante aos filhos de minha mãe.

[[v18-19-18]]

^<<v18-19-18,18>>^ Até os pequeninos me desprezam; quando me levanto, falam contra mim.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os meus amigos íntimos me abominam, e até os que eu amava se tornaram contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ Os meus ossos se apegam à minha pele e à minha carne, e só escapei com a pele dos meus dentes.

[[v18-19-21]]

^<<v18-19-21,21>>^ Compadecei-vos de mim, amigos meus; compadecei-vos de mim; pois a mão de Deus me tocou.

[[v18-19-22]]

^<<v18-19-22,22>>^ Por que me perseguis assim como Deus, e da minha carne não vos fartais?

[[v18-19-23]]

^<<v18-19-23,23>>^ Oxalá que as minhas palavras fossem escritas! Oxalá que fossem gravadas num livro!

[[v18-19-24]]

^<<v18-19-24,24>>^ Que, com pena de ferro, e com chumbo, fossem para sempre esculpidas na rocha!

[[v18-19-25]]

^<<v18-19-25,25>>^ Pois eu sei que o meu Redentor vive, e que por fim se levantará sobre a terra.

[[v18-19-26]]

^<<v18-19-26,26>>^ E depois de consumida esta minha pele, então fora da minha carne verei a Deus;

[[v18-19-27]]

^<<v18-19-27,27>>^ vê-lo-ei ao meu lado, e os meus olhos o contemplarão, e não mais como adversário. O meu coração desfalece dentro de mim!

[[v18-19-28]]

^<<v18-19-28,28>>^ Se disserdes: Como o havemos de perseguir! e que a causa deste mal se acha em mim,

[[v18-19-29]]

^<<v18-19-29,29>>^ temei vós a espada; porque o furor traz os castigos da espada, para saberdes que há um juízo.

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]