include::./index.adoc[]

[[v18-15-0]]
=== Jó, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-15-1]]

^<<v18-15-1,1>>^ Então respondeu Elifaz, o temanita:

[[v18-15-2]]

^<<v18-15-2,2>>^ Porventura responderá o sábio com ciência de vento? E encherá do vento oriental o seu ventre,

[[v18-15-3]]

^<<v18-15-3,3>>^ argüindo com palavras que de nada servem, ou com razões com que ele nada aproveita?

[[v18-15-4]]

^<<v18-15-4,4>>^ Na verdade tu destróis a reverência, e impedes a meditação diante de Deus.

[[v18-15-5]]

^<<v18-15-5,5>>^ Pois a tua iniqüidade ensina a tua boca, e escolhes a língua dos astutos.

[[v18-15-6]]

^<<v18-15-6,6>>^ A tua própria boca te condena, e não eu; e os teus lábios testificam contra ti.

[[v18-15-7]]

^<<v18-15-7,7>>^ És tu o primeiro homem que nasceu? Ou foste dado à luz antes dos outeiros?

[[v18-15-8]]

^<<v18-15-8,8>>^ Ou ouviste o secreto conselho de Deus? E a ti só reservas a sabedoria?

[[v18-15-9]]

^<<v18-15-9,9>>^ Que sabes tu, que nós não saibamos; que entendes, que não haja em nós?

[[v18-15-10]]

^<<v18-15-10,10>>^ Conosco estão os encanecidos e idosos, mais idosos do que teu pai.

[[v18-15-11]]

^<<v18-15-11,11>>^ Porventura fazes pouco caso das consolações de Deus, ou da palavra que te trata benignamente?

[[v18-15-12]]

^<<v18-15-12,12>>^ Por que te arrebata o teu coração, e por que flamejam os teus olhos,

[[v18-15-13]]

^<<v18-15-13,13>>^ de modo que voltas contra Deus o teu espírito, e deixas sair tais palavras da tua boca?

[[v18-15-14]]

^<<v18-15-14,14>>^ Que é o homem, para que seja puro? E o que nasce da mulher, para que fique justo?

[[v18-15-15]]

^<<v18-15-15,15>>^ Eis que Deus não confia nos seus santos, e nem o céu é puro aos seus olhos;

[[v18-15-16]]

^<<v18-15-16,16>>^ quanto menos o homem abominável e corrupto, que bebe a iniqüidade como a água?

[[v18-15-17]]

^<<v18-15-17,17>>^ Escuta-me e to mostrarei; contar-te-ei o que tenho visto

[[v18-15-18]]

^<<v18-15-18,18>>^ &#123;o que os sábios têm anunciado e seus pais não o ocultaram;

[[v18-15-19]]

^<<v18-15-19,19>>^ aos quais somente era dada a terra, não havendo estranho algum passado por entre eles&#125;;

[[v18-15-20]]

^<<v18-15-20,20>>^ Todos os dias passa o ímpio em angústia, sim, todos os anos que estão reservados para o opressor.

[[v18-15-21]]

^<<v18-15-21,21>>^ O sonido de terrores está nos seus ouvidos; na prosperidade lhe sobrevém o assolador.

[[v18-15-22]]

^<<v18-15-22,22>>^ Ele não crê que tornará das trevas, mas que o espera a espada.

[[v18-15-23]]

^<<v18-15-23,23>>^ Anda vagueando em busca de pão, dizendo: Onde está? Bem sabe que o dia das trevas lhe está perto, à mão.

[[v18-15-24]]

^<<v18-15-24,24>>^ Amedrontam-no a angústia e a tribulação; prevalecem contra ele, como um rei preparado para a peleja.

[[v18-15-25]]

^<<v18-15-25,25>>^ Porque estendeu a sua mão contra Deus, e contra o Todo-Poderoso se porta com soberba;

[[v18-15-26]]

^<<v18-15-26,26>>^ arremete contra ele com dura cerviz, e com as saliências do seu escudo;

[[v18-15-27]]

^<<v18-15-27,27>>^ porquanto cobriu o seu rosto com a sua gordura, e criou carne gorda nas ilhargas;

[[v18-15-28]]

^<<v18-15-28,28>>^ e habitou em cidades assoladas, em casas em que ninguém deveria morar, que estavam a ponto de tornar-se em montões de ruínas;

[[v18-15-29]]

^<<v18-15-29,29>>^ não se enriquecerá, nem subsistirá a sua fazenda, nem se estenderão pela terra as suas possessões.

[[v18-15-30]]

^<<v18-15-30,30>>^ Não escapará das trevas; a chama do fogo secará os seus ramos, e ao sopro da boca de Deus desaparecerá.

[[v18-15-31]]

^<<v18-15-31,31>>^ Não confie na vaidade, enganando-se a si mesmo; pois a vaidade será a sua recompensa.

[[v18-15-32]]

^<<v18-15-32,32>>^ Antes do seu dia se cumprirá, e o seu ramo não reverdecerá.

[[v18-15-33]]

^<<v18-15-33,33>>^ Sacudirá as suas uvas verdes, como a vide, e deixará cair a sua flor como a oliveira.

[[v18-15-34]]

^<<v18-15-34,34>>^ Pois a assembléia dos ímpios é estéril, e o fogo consumirá as tendas do suborno.

[[v18-15-35]]

^<<v18-15-35,35>>^ Concebem a malícia, e dão à luz a iniqüidade, e o seu coração prepara enganos.

'''

xref:018-jo/018-jo-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-jo/018-jo-016.adoc#v18-16-0[Próximo Capítulo &#62;]