include::./index.adoc[]

[[v18-8-0]]
=== Jó, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-8-1]]

^<<v18-8-1,1>>^ Então respondeu Bildade, o suíta, dizendo:

[[v18-8-2]]

^<<v18-8-2,2>>^ Até quando falarás tais coisas, e até quando serão as palavras da tua boca qual vento impetuoso?

[[v18-8-3]]

^<<v18-8-3,3>>^ Perverteria Deus o direito? Ou perverteria o Todo-Poderoso a justiça?

[[v18-8-4]]

^<<v18-8-4,4>>^ Se teus filhos pecaram contra ele, ele os entregou ao poder da sua transgressão.

[[v18-8-5]]

^<<v18-8-5,5>>^ Mas, se tu com empenho buscares a Deus, e ,ao Todo-Poderoso fizeres a tua súplica,

[[v18-8-6]]

^<<v18-8-6,6>>^ se fores puro e reto, certamente mesmo agora ele despertará por ti, e tornará segura a habitação da tua justiça.

[[v18-8-7]]

^<<v18-8-7,7>>^ Embora tenha sido pequeno o teu princípio, contudo o teu último estado aumentará grandemente.

[[v18-8-8]]

^<<v18-8-8,8>>^ Indaga, pois, eu te peço, da geração passada, e considera o que seus pais descobriram.

[[v18-8-9]]

^<<v18-8-9,9>>^ Porque nós somos de ontem, e nada sabemos, porquanto nossos dias sobre a terra, são uma sombra.

[[v18-8-10]]

^<<v18-8-10,10>>^ Não te ensinarão eles, e não te falarão, e do seu entendimento não proferirão palavras?

[[v18-8-11]]

^<<v18-8-11,11>>^ Pode o papiro desenvolver-se fora de um pântano. Ou pode o junco crescer sem água?

[[v18-8-12]]

^<<v18-8-12,12>>^ Quando está em flor e ainda não cortado, seca-se antes de qualquer outra erva.

[[v18-8-13]]

^<<v18-8-13,13>>^ Assim são as veredas de todos quantos se esquecem de Deus; a esperança do ímpio perecerá,

[[v18-8-14]]

^<<v18-8-14,14>>^ a sua segurança se desfará, e a sua confiança será como a teia de aranha.

[[v18-8-15]]

^<<v18-8-15,15>>^ Encostar-se-á à sua casa, porém ela não subsistirá; apegar-se-lhe-á, porém ela não permanecerá.

[[v18-8-16]]

^<<v18-8-16,16>>^ Ele está verde diante do sol, e os seus renovos estendem-se sobre o seu jardim;

[[v18-8-17]]

^<<v18-8-17,17>>^ as suas raízes se entrelaçam junto ao monte de pedras; até penetra o pedregal.

[[v18-8-18]]

^<<v18-8-18,18>>^ Mas quando for arrancado do seu lugar, então este o negará, dizendo: Nunca te vi.

[[v18-8-19]]

^<<v18-8-19,19>>^ Eis que tal é a alegria do seu caminho; e da terra outros brotarão.

[[v18-8-20]]

^<<v18-8-20,20>>^ Eis que Deus não rejeitará ao reto, nem tomará pela mão os malfeitores;

[[v18-8-21]]

^<<v18-8-21,21>>^ ainda de riso te encherá a boca, e os teus lábios de louvor.

[[v18-8-22]]

^<<v18-8-22,22>>^ Teus aborrecedores se vestirão de confusão; e a tenda dos ímpios não subsistirá.

'''

xref:018-jo/018-jo-007.adoc#v18-7-0[&#60; Capítulo Anterior] | <<v18-8-0,Topo>> | xref:018-jo/018-jo-009.adoc#v18-9-0[Próximo Capítulo &#62;]