include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-33-1]]

^<<v18-33-1,1>>^ Ouve, pois, as minhas palavras, ó Jó, e dá ouvidos a todas as minhas declarações.

[[v18-33-2]]

^<<v18-33-2,2>>^ Eis que já abri a minha boca; já falou a minha língua debaixo do meu paladar.

[[v18-33-3]]

^<<v18-33-3,3>>^ As minhas palavras declaram a integridade do meu coração, e os meus lábios falam com sinceridade o que sabem.

[[v18-33-4]]

^<<v18-33-4,4>>^ O Espírito de Deus me fez, e o sopro do Todo-Poderoso me dá vida.

[[v18-33-5]]

^<<v18-33-5,5>>^ Se podes, responde-me; põe as tuas palavras em ordem diante de mim; apresenta-te.

[[v18-33-6]]

^<<v18-33-6,6>>^ Eis que diante de Deus sou o que tu és; eu também fui formado do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Eis que não te perturbará nenhum medo de mim, nem será pesada sobre ti a minha mão.

[[v18-33-8]]

^<<v18-33-8,8>>^ Na verdade tu falaste aos meus ouvidos, e eu ouvi a voz das tuas palavras. Dizias:

[[v18-33-9]]

^<<v18-33-9,9>>^ Limpo estou, sem transgressão; puro sou, e não há em mim iniqüidade.

[[v18-33-10]]

^<<v18-33-10,10>>^ Eis que Deus procura motivos de inimizade contra mim, e me considera como o seu inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Põe no tronco os meus pés, e observa todas as minhas veredas.

[[v18-33-12]]

^<<v18-33-12,12>>^ Eis que nisso não tens razão; eu te responderei; porque Deus e maior do que o homem.

[[v18-33-13]]

^<<v18-33-13,13>>^ Por que razão contendes com ele por não dar conta dos seus atos?

[[v18-33-14]]

^<<v18-33-14,14>>^ Pois Deus fala de um modo, e ainda de outro se o homem não lhe atende.

[[v18-33-15]]

^<<v18-33-15,15>>^ Em sonho ou em visão de noite, quando cai sono profundo sobre os homens, quando adormecem na cama;

[[v18-33-16]]

^<<v18-33-16,16>>^ então abre os ouvidos dos homens, e os atemoriza com avisos,

[[v18-33-17]]

^<<v18-33-17,17>>^ para apartar o homem do seu desígnio, e esconder do homem a soberba;

[[v18-33-18]]

^<<v18-33-18,18>>^ para reter a sua alma da cova, e a sua vida de passar pela espada.

[[v18-33-19]]

^<<v18-33-19,19>>^ Também é castigado na sua cama com dores, e com incessante contenda nos seus ossos;

[[v18-33-20]]

^<<v18-33-20,20>>^ de modo que a sua vida abomina o pão, e a sua alma a comida apetecível.

[[v18-33-21]]

^<<v18-33-21,21>>^ Consome-se a sua carne, de maneira que desaparece, e os seus ossos, que não se viam, agora aparecem.

[[v18-33-22]]

^<<v18-33-22,22>>^ A sua alma se vai chegando à cova, e a sua vida aos que trazem a morte.

[[v18-33-23]]

^<<v18-33-23,23>>^ Se com ele, pois, houver um anjo, um intérprete, um entre mil, para declarar ao homem o que lhe é justo,

[[v18-33-24]]

^<<v18-33-24,24>>^ então terá compaixão dele, e lhe dirá: Livra-o, para que não desça à cova; já achei resgate.

[[v18-33-25]]

^<<v18-33-25,25>>^ Sua carne se reverdecerá mais do que na sua infância; e ele tornará aos dias da sua juventude.

[[v18-33-26]]

^<<v18-33-26,26>>^ Deveras orará a Deus, que lhe será propício, e o fará ver a sua face com júbilo, e restituirá ao homem a sua justiça.

[[v18-33-27]]

^<<v18-33-27,27>>^ Cantará diante dos homens, e dirá: Pequei, e perverti o direito, o que de nada me aproveitou.

[[v18-33-28]]

^<<v18-33-28,28>>^ Mas Deus livrou a minha alma de ir para a cova, e a minha vida verá a luz.

[[v18-33-29]]

^<<v18-33-29,29>>^ Eis que tudo isto Deus faz duas e três vezes para com o homem,

[[v18-33-30]]

^<<v18-33-30,30>>^ para reconduzir a sua alma da cova, a fim de que seja iluminado com a luz dos viventes.

[[v18-33-31]]

^<<v18-33-31,31>>^ Escuta, pois, ó Jó, ouve-me; cala-te, e eu falarei.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se tens alguma coisa que dizer, responde-me; fala, porque desejo justificar-te.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não, escuta-me tu; cala-te, e ensinar-te-ei a sabedoria.

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]