include::./index.adoc[]

[[v18-23-0]]
=== Jó, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-23-1]]

^<<v18-23-1,1>>^ Então Jó respondeu:

[[v18-23-2]]

^<<v18-23-2,2>>^ Ainda hoje a minha queixa está em amargura; o peso da mão dele é maior do que o meu gemido.

[[v18-23-3]]

^<<v18-23-3,3>>^ Ah, se eu soubesse onde encontrá-lo, e pudesse chegar ao seu tribunal!

[[v18-23-4]]

^<<v18-23-4,4>>^ Exporia ante ele a minha causa, e encheria a minha boca de argumentos.

[[v18-23-5]]

^<<v18-23-5,5>>^ Saberia as palavras com que ele me respondesse, e entenderia o que me dissesse.

[[v18-23-6]]

^<<v18-23-6,6>>^ Acaso contenderia ele comigo segundo a grandeza do seu poder? Não; antes ele me daria ouvidos.

[[v18-23-7]]

^<<v18-23-7,7>>^ Ali o reto pleitearia com ele, e eu seria absolvido para sempre por meu Juiz.

[[v18-23-8]]

^<<v18-23-8,8>>^ Eis que vou adiante, mas não está ali; volto para trás, e não o percebo;

[[v18-23-9]]

^<<v18-23-9,9>>^ procuro-o à esquerda, onde ele opera, mas não o vejo; viro-me para a direita, e não o diviso.

[[v18-23-10]]

^<<v18-23-10,10>>^ Mas ele sabe o caminho por que eu ando; provando-me ele, sairei como o ouro.

[[v18-23-11]]

^<<v18-23-11,11>>^ Os meus pés se mantiveram nas suas pisadas; guardei o seu caminho, e não me desviei dele.

[[v18-23-12]]

^<<v18-23-12,12>>^ Nunca me apartei do preceito dos seus lábios, e escondi no meu peito as palavras da sua boca.

[[v18-23-13]]

^<<v18-23-13,13>>^ Mas ele está resolvido; quem então pode desviá-lo? E o que ele quiser, isso fará.

[[v18-23-14]]

^<<v18-23-14,14>>^ Pois cumprirá o que está ordenado a meu respeito, e muitas coisas como estas ainda tem consigo.

[[v18-23-15]]

^<<v18-23-15,15>>^ Por isso me perturbo diante dele; e quando considero, tenho medo dele.

[[v18-23-16]]

^<<v18-23-16,16>>^ Deus macerou o meu coração; o Todo-Poderoso me perturbou.

[[v18-23-17]]

^<<v18-23-17,17>>^ Pois não estou desfalecido por causa das trevas, nem porque a escuridão cobre o meu rosto.

'''

xref:018-jo/018-jo-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-jo/018-jo-024.adoc#v18-24-0[Próximo Capítulo &#62;]