include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-11-1]]

^<<v18-11-1,1>>^ Então respondeu Zofar, o naamatita, dizendo:

[[v18-11-2]]

^<<v18-11-2,2>>^ Não se dará resposta à multidão de palavras? ou será justificado o homem falador?

[[v18-11-3]]

^<<v18-11-3,3>>^ Acaso as tuas jactâncias farão calar os homens? e zombarás tu sem que ninguém te envergonhe?

[[v18-11-4]]

^<<v18-11-4,4>>^ Pois dizes: A minha doutrina é pura, e limpo sou aos teus olhos.

[[v18-11-5]]

^<<v18-11-5,5>>^ Mas, na verdade, oxalá que Deus falasse e abrisse os seus lábios contra ti,

[[v18-11-6]]

^<<v18-11-6,6>>^ e te fizesse saber os segredos da sabedoria, pois é multiforme o seu entendimento; sabe, pois, que Deus exige de ti menos do que merece a tua iniqüidade.

[[v18-11-7]]

^<<v18-11-7,7>>^ Poderás descobrir as coisas profundas de Deus, ou descobrir perfeitamente o Todo-Poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ Como as alturas do céu é a sua sabedoria; que poderás tu fazer? Mais profunda é ela do que o Seol; que poderás tu saber?

[[v18-11-9]]

^<<v18-11-9,9>>^ Mais comprida é a sua medida do que a terra, e mais larga do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se ele passar e prender alguém, e chamar a juízo, quem o poderá impedir?

[[v18-11-11]]

^<<v18-11-11,11>>^ Pois ele conhece os homens vãos; e quando vê a iniqüidade, não atentará para ela?

[[v18-11-12]]

^<<v18-11-12,12>>^ Mas o homem vão adquirirá entendimento, quando a cria do asno montês nascer homem.

[[v18-11-13]]

^<<v18-11-13,13>>^ Se tu preparares o teu coração, e estenderes as mãos para ele;

[[v18-11-14]]

^<<v18-11-14,14>>^ se há iniqüidade na tua mão, lança-a para longe de ti, e não deixes a perversidade habitar nas tuas tendas;

[[v18-11-15]]

^<<v18-11-15,15>>^ então levantarás o teu rosto sem mácula, e estarás firme, e não temerás.

[[v18-11-16]]

^<<v18-11-16,16>>^ Pois tu te esquecerás da tua miséria; apenas te lembrarás dela como das águas que já passaram.

[[v18-11-17]]

^<<v18-11-17,17>>^ E a tua vida será mais clara do que o meio-dia; a escuridão dela será como a alva.

[[v18-11-18]]

^<<v18-11-18,18>>^ E terás confiança, porque haverá esperança; olharás ao redor de ti e repousarás seguro.

[[v18-11-19]]

^<<v18-11-19,19>>^ Deitar-te-ás, e ninguém te amedrontará; muitos procurarão obter o teu favor.

[[v18-11-20]]

^<<v18-11-20,20>>^ Mas os olhos dos ímpios desfalecerão, e para eles não haverá refúgio; a sua esperança será o expirar.

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]