include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-2-1]]

^<<v18-2-1,1>>^ Chegou outra vez o dia em que os filhos de Deus vieram apresentar-se perante o Senhor; e veio também Satanás entre eles apresentar-se perante o Senhor.

[[v18-2-2]]

^<<v18-2-2,2>>^ Então o Senhor perguntou a Satanás: Donde vens? Respondeu Satanás ao Senhor, dizendo: De rodear a terra, e de passear por ela.

[[v18-2-3]]

^<<v18-2-3,3>>^ Disse o Senhor a Satanás: Notaste porventura o meu servo Jó, que ninguém há na terra semelhante a ele, homem íntegro e reto, que teme a Deus e se desvia do mal? Ele ainda retém a sua integridade, embora me incitasses contra ele, para o consumir sem causa.

[[v18-2-4]]

^<<v18-2-4,4>>^ Então Satanás respondeu ao Senhor: Pele por pele! Tudo quanto o homem tem dará pela sua vida.

[[v18-2-5]]

^<<v18-2-5,5>>^ Estende agora a mão, e toca-lhe nos ossos e na carne, e ele blasfemará de ti na tua face!

[[v18-2-6]]

^<<v18-2-6,6>>^ Disse, pois, o Senhor a Satanás: Eis que ele está no teu poder; somente poupa-lhe a vida.

[[v18-2-7]]

^<<v18-2-7,7>>^ Saiu, pois, Satanás da presença do Senhor, e feriu Jó de úlceras malignas, desde a planta do pé até o alto da cabeça.

[[v18-2-8]]

^<<v18-2-8,8>>^ E Jó, tomando um caco para com ele se raspar, sentou-se no meio da cinza.

[[v18-2-9]]

^<<v18-2-9,9>>^ Então sua mulher lhe disse: Ainda reténs a tua integridade? Blasfema de Deus, e morre.

[[v18-2-10]]

^<<v18-2-10,10>>^ Mas ele lhe disse: Como fala qualquer doida, assim falas tu; receberemos de Deus o bem, e não receberemos o mal? Em tudo isso não pecou Jó com os seus lábios.

[[v18-2-11]]

^<<v18-2-11,11>>^ Ouvindo, pois, três amigos de Jó todo esse mal que lhe havia sucedido, vieram, cada um do seu lugar: Elifaz o temanita, Bildade o suíta e Zofar o naamatita; pois tinham combinado para virem condoer-se dele e consolá-lo.

[[v18-2-12]]

^<<v18-2-12,12>>^ E, levantando de longe os olhos e não o reconhecendo, choraram em alta voz; e, rasgando cada um o seu manto, lançaram pó para o ar sobre as suas cabeças.

[[v18-2-13]]

^<<v18-2-13,13>>^ E ficaram sentados com ele na terra sete dias e sete noites; e nenhum deles lhe dizia palavra alguma, pois viam que a dor era muito grande.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]