include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-28-1]]

^<<v18-28-1,1>>^ Na verdade, há minas donde se extrai a prata, e também lugar onde se refina o ouro:

[[v18-28-2]]

^<<v18-28-2,2>>^ O ferro tira-se da terra, e da pedra se funde o cobre.

[[v18-28-3]]

^<<v18-28-3,3>>^ Os homens põem termo às trevas, e até os últimos confins exploram as pedras na escuridão e nas trevas mais densas.

[[v18-28-4]]

^<<v18-28-4,4>>^ Abrem um poço de mina longe do lugar onde habitam; são esquecidos pelos viajantes, ficando pendentes longe dos homens, e oscilam de um lado para o outro.

[[v18-28-5]]

^<<v18-28-5,5>>^ Quanto à terra, dela procede o pão, mas por baixo é revolvida como por fogo.

[[v18-28-6]]

^<<v18-28-6,6>>^ As suas pedras são o lugar de safiras, e têm pó de ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ A ave de rapina não conhece essa vereda, e não a viram os olhos do falcão.

[[v18-28-8]]

^<<v18-28-8,8>>^ Nunca a pisaram feras altivas, nem o feroz leão passou por ela.

[[v18-28-9]]

^<<v18-28-9,9>>^ O homem estende a mão contra a pederneira, e revolve os montes desde as suas raízes.

[[v18-28-10]]

^<<v18-28-10,10>>^ Corta canais nas pedras, e os seus olhos descobrem todas as coisas preciosas.

[[v18-28-11]]

^<<v18-28-11,11>>^ Ele tapa os veios d'água para que não gotejem; e tira para a luz o que estava escondido.

[[v18-28-12]]

^<<v18-28-12,12>>^ Mas onde se achará a sabedoria? E onde está o lugar do entendimento?

[[v18-28-13]]

^<<v18-28-13,13>>^ O homem não lhe conhece o caminho; nem se acha ela na terra dos viventes.

[[v18-28-14]]

^<<v18-28-14,14>>^ O abismo diz: Não está em mim; e o mar diz: Ela não está comigo.

[[v18-28-15]]

^<<v18-28-15,15>>^ Não pode ser comprada com ouro fino, nem a peso de prata se trocará.

[[v18-28-16]]

^<<v18-28-16,16>>^ Nem se pode avaliar em ouro fino de Ofir, nem em pedras preciosas de berilo, ou safira.

[[v18-28-17]]

^<<v18-28-17,17>>^ Com ela não se pode comparar o ouro ou o vidro; nem se trocara por jóias de ouro fino.

[[v18-28-18]]

^<<v18-28-18,18>>^ Não se fará menção de coral nem de cristal; porque a aquisição da sabedoria é melhor que a das pérolas.

[[v18-28-19]]

^<<v18-28-19,19>>^ Não se lhe igualará o topázio da Etiópia, nem se pode comprar por ouro puro.

[[v18-28-20]]

^<<v18-28-20,20>>^ Donde, pois, vem a sabedoria? Onde está o lugar do entendimento?

[[v18-28-21]]

^<<v18-28-21,21>>^ Está encoberta aos olhos de todo vivente, e oculta às aves do céu.

[[v18-28-22]]

^<<v18-28-22,22>>^ O Abadom e a morte dizem: Ouvimos com os nossos ouvidos um rumor dela.

[[v18-28-23]]

^<<v18-28-23,23>>^ Deus entende o seu caminho, e ele sabe o seu lugar.

[[v18-28-24]]

^<<v18-28-24,24>>^ Porque ele perscruta até as extremidades da terra, sim, ele vê tudo o que há debaixo do céu.

[[v18-28-25]]

^<<v18-28-25,25>>^ Quando regulou o peso do vento, e fixou a medida das águas;

[[v18-28-26]]

^<<v18-28-26,26>>^ quando prescreveu leis para a chuva e caminho para o relâmpago dos trovões;

[[v18-28-27]]

^<<v18-28-27,27>>^ então viu a sabedoria e a manifestou; estabeleceu-a, e também a esquadrinhou.

[[v18-28-28]]

^<<v18-28-28,28>>^ E disse ao homem: Eis que o temor do Senhor é a sabedoria, e o apartar-se do mal é o entendimento.

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]