include::./index.adoc[]

[[v18-41-0]]
=== Jó, 41
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-41-1]]

^<<v18-41-1,1>>^ Poderás tirar com anzol o leviatã, ou apertar-lhe a língua com uma corda?

[[v18-41-2]]

^<<v18-41-2,2>>^ Poderás meter-lhe uma corda de junco no nariz, ou com um gancho furar a sua queixada?

[[v18-41-3]]

^<<v18-41-3,3>>^ Porventura te fará muitas súplicas, ou brandamente te falará?

[[v18-41-4]]

^<<v18-41-4,4>>^ Fará ele aliança contigo, ou o tomarás tu por servo para sempre?

[[v18-41-5]]

^<<v18-41-5,5>>^ Brincarás com ele, como se fora um pássaro, ou o prenderás para tuas meninas?

[[v18-41-6]]

^<<v18-41-6,6>>^ Farão os sócios de pesca tráfico dele, ou o dividirão entre os negociantes?

[[v18-41-7]]

^<<v18-41-7,7>>^ Poderás encher-lhe a pele de arpões, ou a cabeça de fisgas?

[[v18-41-8]]

^<<v18-41-8,8>>^ Põe a tua mão sobre ele; lembra-te da peleja; nunca mais o farás!

[[v18-41-9]]

^<<v18-41-9,9>>^ Eis que é vã a esperança de apanhá-lo; pois não será um homem derrubado só ao vê-lo?

[[v18-41-10]]

^<<v18-41-10,10>>^ Ninguém há tão ousado, que se atreva a despertá-lo; quem, pois, é aquele que pode erguer-se diante de mim?

[[v18-41-11]]

^<<v18-41-11,11>>^ Quem primeiro me deu a mim, para que eu haja de retribuir-lhe? Pois tudo quanto existe debaixo de todo céu é meu.

[[v18-41-12]]

^<<v18-41-12,12>>^ Não me calarei a respeito dos seus membros, nem da sua grande força, nem da graça da sua estrutura.

[[v18-41-13]]

^<<v18-41-13,13>>^ Quem lhe pode tirar o vestido exterior? Quem lhe penetrará a couraça dupla?

[[v18-41-14]]

^<<v18-41-14,14>>^ Quem jamais abriu as portas do seu rosto? Pois em roda dos seus dentes está o terror.

[[v18-41-15]]

^<<v18-41-15,15>>^ As suas fortes escamas são o seu orgulho, cada uma fechada como por um selo apertado.

[[v18-41-16]]

^<<v18-41-16,16>>^ Uma à outra se chega tão perto, que nem o ar passa por entre elas.

[[v18-41-17]]

^<<v18-41-17,17>>^ Umas às outras se ligam; tanto aderem entre si, que não se podem separar.

[[v18-41-18]]

^<<v18-41-18,18>>^ Os seus espirros fazem resplandecer a luz, e os seus olhos são como as pestanas da alva.

[[v18-41-19]]

^<<v18-41-19,19>>^ Da sua boca saem tochas; faíscas de fogo saltam dela.

[[v18-41-20]]

^<<v18-41-20,20>>^ Dos seus narizes procede fumaça, como de uma panela que ferve, e de juncos que ardem.

[[v18-41-21]]

^<<v18-41-21,21>>^ O seu hálito faz incender os carvões, e da sua boca sai uma chama.

[[v18-41-22]]

^<<v18-41-22,22>>^ No seu pescoço reside a força; e diante dele anda saltando o terror.

[[v18-41-23]]

^<<v18-41-23,23>>^ Os tecidos da sua carne estão pegados entre si; ela é firme sobre ele, não se pode mover.

[[v18-41-24]]

^<<v18-41-24,24>>^ O seu coração é firme como uma pedra; sim, firme como a pedra inferior duma mó.

[[v18-41-25]]

^<<v18-41-25,25>>^ Quando ele se levanta, os valentes são atemorizados, e por causa da consternação ficam fora de si.

[[v18-41-26]]

^<<v18-41-26,26>>^ Se alguém o atacar com a espada, essa não poderá penetrar; nem tampouco a lança, nem o dardo, nem o arpão.

[[v18-41-27]]

^<<v18-41-27,27>>^ Ele considera o ferro como palha, e o bronze como pau podre.

[[v18-41-28]]

^<<v18-41-28,28>>^ A seta não o poderá fazer fugir; para ele as pedras das fundas se tornam em restolho.

[[v18-41-29]]

^<<v18-41-29,29>>^ Os bastões são reputados como juncos, e ele se ri do brandir da lança.

[[v18-41-30]]

^<<v18-41-30,30>>^ Debaixo do seu ventre há pontas agudas; ele se estende como um trilho sobre o lodo.

[[v18-41-31]]

^<<v18-41-31,31>>^ As profundezas faz ferver, como uma panela; torna o mar como uma vasilha de ungüento.

[[v18-41-32]]

^<<v18-41-32,32>>^ Após si deixa uma vereda luminosa; parece o abismo tornado em brancura de cãs.

[[v18-41-33]]

^<<v18-41-33,33>>^ Na terra não há coisa que se lhe possa comparar; pois foi feito para estar sem pavor.

[[v18-41-34]]

^<<v18-41-34,34>>^ Ele vê tudo o que é alto; é rei sobre todos os filhos da soberba.

'''

xref:018-jo/018-jo-040.adoc#v18-40-0[&#60; Capítulo Anterior] | <<v18-41-0,Topo>> | xref:018-jo/018-jo-042.adoc#v18-42-0[Próximo Capítulo &#62;]