include::./index.adoc[]

[[v18-16-0]]
=== Jó, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-16-1]]

^<<v18-16-1,1>>^ Então Jó respondeu, dizendo:

[[v18-16-2]]

^<<v18-16-2,2>>^ Tenho ouvido muitas coisas como essas; todos vós sois consoladores molestos.

[[v18-16-3]]

^<<v18-16-3,3>>^ Não terão fim essas palavras de vento? Ou que é o que te provoca, para assim responderes?

[[v18-16-4]]

^<<v18-16-4,4>>^ Eu também poderia falar como vós falais, se vós estivésseis em meu lugar; eu poderia amontoar palavras contra vós, e contra vós menear a minha cabeça;

[[v18-16-5]]

^<<v18-16-5,5>>^ poderia fortalecer-vos com a minha boca, e a consolação dos meus lábios poderia mitigar a vossa dor.

[[v18-16-6]]

^<<v18-16-6,6>>^ Ainda que eu fale, a minha dor não se mitiga; e embora me cale, qual é o meu alívio?

[[v18-16-7]]

^<<v18-16-7,7>>^ Mas agora, ó Deus, me deixaste exausto; assolaste toda a minha companhia.

[[v18-16-8]]

^<<v18-16-8,8>>^ Tu me emagreceste, e isso constitui uma testemunha contra mim; contra mim se levanta a minha magreza, e o meu rosto testifica contra mim.

[[v18-16-9]]

^<<v18-16-9,9>>^ Na sua ira ele me despedaçou, e me perseguiu; rangeu os dentes contra mim; o meu adversário aguça os seus olhos contra mim.

[[v18-16-10]]

^<<v18-16-10,10>>^ Os homens abrem contra mim a boca; com desprezo me ferem nas faces, e contra mim se ajuntam à uma.

[[v18-16-11]]

^<<v18-16-11,11>>^ Deus me entrega ao ímpio, nas mãos dos iníquos me faz cair.

[[v18-16-12]]

^<<v18-16-12,12>>^ Descansado estava eu, e ele me quebrantou; e pegou-me pelo pescoço, e me despedaçou; colocou-me por seu alvo;

[[v18-16-13]]

^<<v18-16-13,13>>^ cercam-me os seus flecheiros. Atravessa-me os rins, e não me poupa; derrama o meu fel pela terra.

[[v18-16-14]]

^<<v18-16-14,14>>^ Quebranta-me com golpe sobre golpe; arremete contra mim como um guerreiro.

[[v18-16-15]]

^<<v18-16-15,15>>^ Sobre a minha pele cosi saco, e deitei a minha glória no pó.

[[v18-16-16]]

^<<v18-16-16,16>>^ O meu rosto todo está inflamado de chorar, e há sombras escuras sobre as minhas pálpebras,

[[v18-16-17]]

^<<v18-16-17,17>>^ embora não haja violência nas minhas mãos, e seja pura a minha oração.

[[v18-16-18]]

^<<v18-16-18,18>>^ Ó terra, não cubras o meu sangue, e não haja lugar em que seja abafado o meu clamor!

[[v18-16-19]]

^<<v18-16-19,19>>^ Eis que agora mesmo a minha testemunha está no céu, e o meu fiador nas alturas.

[[v18-16-20]]

^<<v18-16-20,20>>^ Os meus amigos zombam de mim; mas os meus olhos se desfazem em lágrimas diante de Deus,

[[v18-16-21]]

^<<v18-16-21,21>>^ para que ele defenda o direito que o homem tem diante de Deus e o que o filho do homem tem perante, o seu próximo.

[[v18-16-22]]

^<<v18-16-22,22>>^ Pois quando houver decorrido poucos anos, eu seguirei o caminho por onde não tornarei.

'''

xref:018-jo/018-jo-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-jo/018-jo-017.adoc#v18-17-0[Próximo Capítulo &#62;]