include::./index.adoc[]

[[v18-14-0]]
=== Jó, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-14-1]]

^<<v18-14-1,1>>^ O homem, nascido da mulher, é de poucos dias e cheio de inquietação.

[[v18-14-2]]

^<<v18-14-2,2>>^ Nasce como a flor, e murcha; foge também como a sombra, e não permanece.

[[v18-14-3]]

^<<v18-14-3,3>>^ Sobre esse tal abres os teus olhos, e a mim me fazes entrar em juízo contigo?

[[v18-14-4]]

^<<v18-14-4,4>>^ Quem do imundo tirará o puro? Ninguém.

[[v18-14-5]]

^<<v18-14-5,5>>^ Visto que os seus dias estão determinados, contigo está o número dos seus meses; tu lhe puseste limites, e ele não poderá passar além deles.

[[v18-14-6]]

^<<v18-14-6,6>>^ Desvia dele o teu rosto, para que ele descanse e, como o jornaleiro, tenha contentamento no seu dia.

[[v18-14-7]]

^<<v18-14-7,7>>^ Porque há esperança para a árvore, que, se for cortada, ainda torne a brotar, e que não cessem os seus renovos.

[[v18-14-8]]

^<<v18-14-8,8>>^ Ainda que envelheça a sua raiz na terra, e morra o seu tronco no pó,

[[v18-14-9]]

^<<v18-14-9,9>>^ contudo ao cheiro das águas brotará, e lançará ramos como uma planta nova.

[[v18-14-10]]

^<<v18-14-10,10>>^ O homem, porém, morre e se desfaz; sim, rende o homem o espírito, e então onde está?

[[v18-14-11]]

^<<v18-14-11,11>>^ Como as águas se retiram de um lago, e um rio se esgota e seca,

[[v18-14-12]]

^<<v18-14-12,12>>^ assim o homem se deita, e não se levanta; até que não haja mais céus não acordará nem será despertado de seu sono.

[[v18-14-13]]

^<<v18-14-13,13>>^ Oxalá me escondesses no Seol, e me ocultasses até que a tua ira tenha passado; que me determinasses um tempo, e te lembrasses de mim!

[[v18-14-14]]

^<<v18-14-14,14>>^ Morrendo o homem, acaso tornará a viver? Todos os dias da minha lida esperaria eu, até que viesse a minha mudança.

[[v18-14-15]]

^<<v18-14-15,15>>^ Chamar-me-ias, e eu te responderia; almejarias a obra de tuas mãos.

[[v18-14-16]]

^<<v18-14-16,16>>^ Então contarias os meus passos; não estarias a vigiar sobre o meu pecado;

[[v18-14-17]]

^<<v18-14-17,17>>^ a minha transgressão estaria selada num saco, e ocultarias a minha iniqüidade.

[[v18-14-18]]

^<<v18-14-18,18>>^ Mas, na verdade, a montanha cai e se desfaz, e a rocha se remove do seu lugar.

[[v18-14-19]]

^<<v18-14-19,19>>^ As águas gastam as pedras; as enchentes arrebatam o solo; assim tu fazes perecer a esperança do homem.

[[v18-14-20]]

^<<v18-14-20,20>>^ Prevaleces para sempre contra ele, e ele passa; mudas o seu rosto e o despedes.

[[v18-14-21]]

^<<v18-14-21,21>>^ Os seus filhos recebem honras, sem que ele o saiba; são humilhados sem que ele o perceba.

[[v18-14-22]]

^<<v18-14-22,22>>^ Sente as dores do seu próprio corpo somente, e só por si mesmo lamenta.

'''

xref:018-jo/018-jo-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-jo/018-jo-015.adoc#v18-15-0[Próximo Capítulo &#62;]