include::./index.adoc[]

[[v18-9-0]]
=== Jó, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-9-1]]

^<<v18-9-1,1>>^ Então Jó respondeu, dizendo:

[[v18-9-2]]

^<<v18-9-2,2>>^ Na verdade sei que assim é; mas como pode o homem ser justo para com Deus?

[[v18-9-3]]

^<<v18-9-3,3>>^ Se alguém quisesse contender com ele, não lhe poderia responder uma vez em mil.

[[v18-9-4]]

^<<v18-9-4,4>>^ Ele é sábio de coração e poderoso em forças; quem se endureceu contra ele, e ficou seguro?

[[v18-9-5]]

^<<v18-9-5,5>>^ Ele é o que remove os montes, sem que o saibam, e os transtorna no seu furor;

[[v18-9-6]]

^<<v18-9-6,6>>^ o que sacode a terra do seu lugar, de modo que as suas colunas estremecem;

[[v18-9-7]]

^<<v18-9-7,7>>^ o que dá ordens ao sol, e ele não nasce; o que sela as estrelas;

[[v18-9-8]]

^<<v18-9-8,8>>^ o que sozinho estende os céus, e anda sobre as ondas do mar;

[[v18-9-9]]

^<<v18-9-9,9>>^ o que fez a ursa, o Oriom, e as Plêiades, e as recâmaras do sul;

[[v18-9-10]]

^<<v18-9-10,10>>^ o que faz coisas grandes e insondáveis, e maravilhas que não se podem contar.

[[v18-9-11]]

^<<v18-9-11,11>>^ Eis que ele passa junto a mim, e, não o vejo; sim, vai passando adiante, mas não o percebo.

[[v18-9-12]]

^<<v18-9-12,12>>^ Eis que arrebata a presa; quem o pode impedir? Quem lhe dirá: Que é o que fazes?

[[v18-9-13]]

^<<v18-9-13,13>>^ Deus não retirará a sua ira; debaixo dele se curvaram os aliados de Raabe;

[[v18-9-14]]

^<<v18-9-14,14>>^ quanto menos lhe poderei eu responder ou escolher as minhas palavras para discutir com ele?

[[v18-9-15]]

^<<v18-9-15,15>>^ Embora, eu seja justo, não lhe posso responder; tenho de pedir misericórdia ao meu juiz.

[[v18-9-16]]

^<<v18-9-16,16>>^ Ainda que eu chamasse, e ele me respondesse, não poderia crer que ele estivesse escutando a minha voz.

[[v18-9-17]]

^<<v18-9-17,17>>^ Pois ele me quebranta com uma tempestade, e multiplica as minhas chagas sem causa.

[[v18-9-18]]

^<<v18-9-18,18>>^ Não me permite respirar, antes me farta de amarguras.

[[v18-9-19]]

^<<v18-9-19,19>>^ Se fosse uma prova de força, eis-me aqui, diria ele; e se fosse questão de juízo, quem o citaria para comparecer?

[[v18-9-20]]

^<<v18-9-20,20>>^ Ainda que eu fosse justo, a minha própria boca me condenaria; ainda que eu fosse perfeito, então ela me declararia perverso:

[[v18-9-21]]

^<<v18-9-21,21>>^ Eu sou inocente; não estimo a mim mesmo; desprezo a minha vida.

[[v18-9-22]]

^<<v18-9-22,22>>^ Tudo é o mesmo, portanto digo: Ele destrói o reto e o ímpio.

[[v18-9-23]]

^<<v18-9-23,23>>^ Quando o açoite mata de repente, ele zomba da calamidade dos inocentes.

[[v18-9-24]]

^<<v18-9-24,24>>^ A terra está entregue nas mãos do ímpio. Ele cobre o rosto dos juízes; se não é ele, quem é, logo?

[[v18-9-25]]

^<<v18-9-25,25>>^ Ora, os meus dias são mais velozes do que um correio; fogem, e não vêem o bem.

[[v18-9-26]]

^<<v18-9-26,26>>^ Eles passam como balsas de junco, como águia que se lança sobre a presa.

[[v18-9-27]]

^<<v18-9-27,27>>^ Se eu disser: Eu me esquecerei da minha queixa, mudarei o meu aspecto, e tomarei alento;

[[v18-9-28]]

^<<v18-9-28,28>>^ então tenho pavor de todas as minhas dores; porque bem sei que não me terás por inocente.

[[v18-9-29]]

^<<v18-9-29,29>>^ Eu serei condenado; por que, pois, trabalharei em vão?

[[v18-9-30]]

^<<v18-9-30,30>>^ Se eu me lavar com água de neve, e limpar as minhas mãos com sabão,

[[v18-9-31]]

^<<v18-9-31,31>>^ mesmo assim me submergirás no fosso, e as minhas próprias vestes me abominarão.

[[v18-9-32]]

^<<v18-9-32,32>>^ Porque ele não é homem, como eu, para eu lhe responder, para nos encontrarmos em juízo.

[[v18-9-33]]

^<<v18-9-33,33>>^ Não há entre nós árbitro para pôr a mão sobre nós ambos.

[[v18-9-34]]

^<<v18-9-34,34>>^ Tire ele a sua vara de cima de mim, e não me amedronte o seu terror;

[[v18-9-35]]

^<<v18-9-35,35>>^ então falarei, e não o temerei; pois eu não sou assim em mim mesmo.

'''

xref:018-jo/018-jo-008.adoc#v18-8-0[&#60; Capítulo Anterior] | <<v18-9-0,Topo>> | xref:018-jo/018-jo-010.adoc#v18-10-0[Próximo Capítulo &#62;]