include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-36-1]]

^<<v18-36-1,1>>^ Prosseguiu ainda Eliú e disse:

[[v18-36-2]]

^<<v18-36-2,2>>^ Espera-me um pouco, e mostrar-te-ei que ainda há razões a favor de Deus.

[[v18-36-3]]

^<<v18-36-3,3>>^ De longe trarei o meu conhecimento, e ao meu criador atribuirei a justiça.

[[v18-36-4]]

^<<v18-36-4,4>>^ Pois, na verdade, as minhas palavras não serão falsas; contigo está um que tem perfeito conhecimento.

[[v18-36-5]]

^<<v18-36-5,5>>^ Eis que Deus é mui poderoso, contudo a ninguém despreza; grande é no poder de entendimento.

[[v18-36-6]]

^<<v18-36-6,6>>^ Ele não preserva a vida do ímpio, mas faz justiça aos aflitos.

[[v18-36-7]]

^<<v18-36-7,7>>^ Do justo não aparta os seus olhos; antes com os reis no trono os faz sentar para sempre, e assim são exaltados.

[[v18-36-8]]

^<<v18-36-8,8>>^ E se estão presos em grilhões, e amarrados com cordas de aflição,

[[v18-36-9]]

^<<v18-36-9,9>>^ então lhes faz saber a obra deles, e as suas transgressões, porquanto se têm portado com soberba.

[[v18-36-10]]

^<<v18-36-10,10>>^ E abre-lhes o ouvido para a instrução, e ordena que se convertam da iniqüidade.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se o ouvirem, e o servirem, acabarão seus dias em prosperidade, e os seus anos em delícias.

[[v18-36-12]]

^<<v18-36-12,12>>^ Mas se não o ouvirem, à espada serão passados, e expirarão sem conhecimento.

[[v18-36-13]]

^<<v18-36-13,13>>^ Assim os ímpios de coração amontoam, a sua ira; e quando Deus os põe em grilhões, não clamam por socorro.

[[v18-36-14]]

^<<v18-36-14,14>>^ Eles morrem na mocidade, e a sua vida perece entre as prostitutas.

[[v18-36-15]]

^<<v18-36-15,15>>^ Ao aflito livra por meio da sua aflição, e por meio da opressão lhe abre os ouvidos.

[[v18-36-16]]

^<<v18-36-16,16>>^ Assim também quer induzir-te da angústia para um lugar espaçoso, em que não há aperto; e as iguarias da tua mesa serão cheias de gordura.

[[v18-36-17]]

^<<v18-36-17,17>>^ Mas tu estás cheio do juízo do ímpio; o juízo e a justiça tomam conta de ti.

[[v18-36-18]]

^<<v18-36-18,18>>^ Cuida, pois, para que a ira não te induza a escarnecer, nem te desvie a grandeza do resgate.

[[v18-36-19]]

^<<v18-36-19,19>>^ Prevalecerá o teu clamor, ou todas as forças da tua fortaleza, para que não estejas em aperto?

[[v18-36-20]]

^<<v18-36-20,20>>^ Não suspires pela noite, em que os povos sejam tomados do seu lugar.

[[v18-36-21]]

^<<v18-36-21,21>>^ Guarda-te, e não declines para a iniqüidade; porquanto isso escolheste antes que a aflição.

[[v18-36-22]]

^<<v18-36-22,22>>^ Eis que Deus é excelso em seu poder; quem é ensinador como ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Quem lhe prescreveu o seu caminho? Ou quem poderá dizer: Tu praticaste a injustiça?

[[v18-36-24]]

^<<v18-36-24,24>>^ Lembra-te de engrandecer a sua obra, de que têm cantado os homens.

[[v18-36-25]]

^<<v18-36-25,25>>^ Todos os homens a vêem; de longe a contempla o homem.

[[v18-36-26]]

^<<v18-36-26,26>>^ Eis que Deus é grande, e nós não o conhecemos, e o número dos seus anos não se pode esquadrinhar.

[[v18-36-27]]

^<<v18-36-27,27>>^ Pois atrai a si as gotas de água, e do seu vapor as destila em chuva,

[[v18-36-28]]

^<<v18-36-28,28>>^ que as nuvens derramam e gotejam abundantemente sobre o homem.

[[v18-36-29]]

^<<v18-36-29,29>>^ Poderá alguém entender as dilatações das nuvens, e os trovões do seu pavilhão?

[[v18-36-30]]

^<<v18-36-30,30>>^ Eis que ao redor de si estende a sua luz, e cobre o fundo do mar.

[[v18-36-31]]

^<<v18-36-31,31>>^ Pois por estas coisas julga os povos e lhes dá mantimento em abundância.

[[v18-36-32]]

^<<v18-36-32,32>>^ Cobre as mãos com o relâmpago, e dá-lhe ordem para que fira o alvo.

[[v18-36-33]]

^<<v18-36-33,33>>^ O fragor da tempestade dá notícia dele; até o gado pressente a sua aproximação.

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]