include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-27-1]]

^<<v18-27-1,1>>^ E prosseguindo Jó em seu discurso, disse:

[[v18-27-2]]

^<<v18-27-2,2>>^ Vive Deus, que me tirou o direito, e o Todo-Poderoso, que me amargurou a alma;

[[v18-27-3]]

^<<v18-27-3,3>>^ enquanto em mim houver alento, e o sopro de Deus no meu nariz,

[[v18-27-4]]

^<<v18-27-4,4>>^ não falarão os meus lábios iniqüidade, nem a minha língua pronunciará engano.

[[v18-27-5]]

^<<v18-27-5,5>>^ Longe de mim que eu vos dê razão; até que eu morra, nunca apartarei de mim a minha integridade.

[[v18-27-6]]

^<<v18-27-6,6>>^ À minha justiça me apegarei e não a largarei; o meu coração não reprova dia algum da minha vida.

[[v18-27-7]]

^<<v18-27-7,7>>^ Seja como o ímpio o meu inimigo, e como o perverso aquele que se levantar contra mim.

[[v18-27-8]]

^<<v18-27-8,8>>^ Pois qual é a esperança do ímpio, quando Deus o cortar, quando Deus lhe arrebatar a alma?

[[v18-27-9]]

^<<v18-27-9,9>>^ Acaso Deus lhe ouvirá o clamor, sobrevindo-lhe a tribulação?

[[v18-27-10]]

^<<v18-27-10,10>>^ Deleitar-se-á no Todo-Poderoso, ou invocará a Deus em todo o tempo?

[[v18-27-11]]

^<<v18-27-11,11>>^ Ensinar-vos-ei acerca do poder de Deus, e não vos encobrirei o que está com o Todo-Poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Eis que todos vós já vistes isso; por que, pois, vos entregais completamente à vaidade?

[[v18-27-13]]

^<<v18-27-13,13>>^ Esta é da parte de Deus a porção do ímpio, e a herança que os opressores recebem do Todo-Poderoso:

[[v18-27-14]]

^<<v18-27-14,14>>^ Se os seus filhos se multiplicarem, será para a espada; e a sua prole não se fartará de pão.

[[v18-27-15]]

^<<v18-27-15,15>>^ Os que ficarem dele, pela peste serão sepultados, e as suas viúvas não chorarão.

[[v18-27-16]]

^<<v18-27-16,16>>^ Embora amontoe prata como pó, e acumule vestes como barro,

[[v18-27-17]]

^<<v18-27-17,17>>^ ele as pode acumular, mas o justo as vestirá, e o inocente repartirá a prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ A casa que ele edifica é como a teia da aranha, e como a cabana que o guarda faz.

[[v18-27-19]]

^<<v18-27-19,19>>^ Rico se deita, mas não o fará mais; abre os seus olhos, e já se foi a sua riqueza.

[[v18-27-20]]

^<<v18-27-20,20>>^ Pavores o alcançam como um dilúvio; de noite o arrebata a tempestade.

[[v18-27-21]]

^<<v18-27-21,21>>^ O vento oriental leva-o, e ele se vai; sim, varre-o com ímpeto do seu lugar:

[[v18-27-22]]

^<<v18-27-22,22>>^ Pois atira contra ele, e não o poupa, e ele foge precipitadamente do seu poder.

[[v18-27-23]]

^<<v18-27-23,23>>^ Bate palmas contra ele, e assobia contra ele do seu lugar.

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]