include::./index.adoc[]

[[v18-40-0]]
=== Jó, 40
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-40-1]]

^<<v18-40-1,1>>^ Disse mais o Senhor a Jó:

[[v18-40-2]]

^<<v18-40-2,2>>^ Contenderá contra o Todo-Poderoso o censurador? Quem assim argüi a Deus, responda a estas coisas.

[[v18-40-3]]

^<<v18-40-3,3>>^ Então Jó respondeu ao Senhor, e disse:

[[v18-40-4]]

^<<v18-40-4,4>>^ Eis que sou vil; que te responderia eu? Antes ponho a minha mão sobre a boca.

[[v18-40-5]]

^<<v18-40-5,5>>^ Uma vez tenho falado, e não replicarei; ou ainda duas vezes, porém não prosseguirei.

[[v18-40-6]]

^<<v18-40-6,6>>^ Então, do meio do redemoinho, o Senhor respondeu a Jó:

[[v18-40-7]]

^<<v18-40-7,7>>^ Cinge agora os teus lombos como homem; eu te perguntarei a ti, e tu me responderás.

[[v18-40-8]]

^<<v18-40-8,8>>^ Farás tu vão também o meu juízo, ou me condenarás para te justificares a ti?

[[v18-40-9]]

^<<v18-40-9,9>>^ Ou tens braço como Deus; ou podes trovejar com uma voz como a dele?

[[v18-40-10]]

^<<v18-40-10,10>>^ Orna-te, pois, de excelência e dignidade, e veste-te de glória e de esplendor.

[[v18-40-11]]

^<<v18-40-11,11>>^ Derrama as inundações da tua ira, e atenta para todo soberbo, e abate-o.

[[v18-40-12]]

^<<v18-40-12,12>>^ Olha para todo soberbo, e humilha-o, e calca aos pés os ímpios onde estão.

[[v18-40-13]]

^<<v18-40-13,13>>^ Esconde-os juntamente no pó; ata-lhes os rostos no lugar escondido.

[[v18-40-14]]

^<<v18-40-14,14>>^ Então também eu de ti confessarei que a tua mão direita te poderá salvar.

[[v18-40-15]]

^<<v18-40-15,15>>^ Contempla agora o hipopótamo, que eu criei como a ti, que come a erva como o boi.

[[v18-40-16]]

^<<v18-40-16,16>>^ Eis que a sua força está nos seus lombos, e o seu poder nos músculos do seu ventre.

[[v18-40-17]]

^<<v18-40-17,17>>^ Ele enrija a sua cauda como o cedro; os nervos das suas coxas são entretecidos.

[[v18-40-18]]

^<<v18-40-18,18>>^ Os seus ossos são como tubos de bronze, as suas costelas como barras de ferro.

[[v18-40-19]]

^<<v18-40-19,19>>^ Ele é obra prima dos caminhos de Deus; aquele que o fez o proveu da sua espada.

[[v18-40-20]]

^<<v18-40-20,20>>^ Em verdade os montes lhe produzem pasto, onde todos os animais do campo folgam.

[[v18-40-21]]

^<<v18-40-21,21>>^ Deita-se debaixo dos lotos, no esconderijo dos canaviais e no pântano.

[[v18-40-22]]

^<<v18-40-22,22>>^ Os lotos cobrem-no com sua sombra; os salgueiros do ribeiro o cercam.

[[v18-40-23]]

^<<v18-40-23,23>>^ Eis que se um rio trasborda, ele não treme; sente-se seguro ainda que o Jordão se levante até a sua boca.

[[v18-40-24]]

^<<v18-40-24,24>>^ Poderá alguém apanhá-lo quando ele estiver de vigia, ou com laços lhe furar o nariz?

'''

xref:018-jo/018-jo-039.adoc#v18-39-0[&#60; Capítulo Anterior] | <<v18-40-0,Topo>> | xref:018-jo/018-jo-041.adoc#v18-41-0[Próximo Capítulo &#62;]