include::./index.adoc[]

[[v18-20-0]]
=== Jó, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-20-1]]

^<<v18-20-1,1>>^ Então respondeu Zofar, o naamatita:

[[v18-20-2]]

^<<v18-20-2,2>>^ Ora, os meus pensamentos me fazem responder, e por isso eu me apresso.

[[v18-20-3]]

^<<v18-20-3,3>>^ Estou ouvindo a tua repreensão, que me envergonha, mas o espírito do meu entendimento responde por mim.

[[v18-20-4]]

^<<v18-20-4,4>>^ Não sabes tu que desde a antigüidade, desde que o homem foi posto sobre a terra,

[[v18-20-5]]

^<<v18-20-5,5>>^ o triunfo dos iníquos é breve, e a alegria dos ímpios é apenas dum momento?

[[v18-20-6]]

^<<v18-20-6,6>>^ Ainda que a sua exaltação suba até o céu, e a sua cabeça chegue até as nuvens,

[[v18-20-7]]

^<<v18-20-7,7>>^ contudo, como o seu próprio esterco, perecerá para sempre; e os que o viam perguntarão: Onde está?

[[v18-20-8]]

^<<v18-20-8,8>>^ Dissipar-se-á como um sonho, e não será achado; será afugentado qual uma visão da noite.

[[v18-20-9]]

^<<v18-20-9,9>>^ Os olhos que o viam não o verão mais, nem o seu lugar o contemplará mais.

[[v18-20-10]]

^<<v18-20-10,10>>^ Os seus filhos procurarão o favor dos pobres, e as suas mãos restituirão os seus lucros ilícitos.

[[v18-20-11]]

^<<v18-20-11,11>>^ Os seus ossos estão cheios do vigor da sua juventude, mas este se deitará com ele no pó.

[[v18-20-12]]

^<<v18-20-12,12>>^ Ainda que o mal lhe seja doce na boca, ainda que ele o esconda debaixo da sua língua,

[[v18-20-13]]

^<<v18-20-13,13>>^ ainda que não o queira largar, antes o retenha na sua boca,

[[v18-20-14]]

^<<v18-20-14,14>>^ contudo a sua comida se transforma nas suas entranhas; dentro dele se torna em fel de áspides.

[[v18-20-15]]

^<<v18-20-15,15>>^ Engoliu riquezas, mas vomitá-las-á; do ventre dele Deus as lançará.

[[v18-20-16]]

^<<v18-20-16,16>>^ Veneno de áspides sorverá, língua de víbora o matará.

[[v18-20-17]]

^<<v18-20-17,17>>^ Não verá as correntes, os rios e os ribeiros de mel e de manteiga.

[[v18-20-18]]

^<<v18-20-18,18>>^ O que adquiriu pelo trabalho, isso restituirá, e não o engolirá; não se regozijará conforme a fazenda que ajuntou.

[[v18-20-19]]

^<<v18-20-19,19>>^ Pois que oprimiu e desamparou os pobres, e roubou a casa que não edificou.

[[v18-20-20]]

^<<v18-20-20,20>>^ Porquanto não houve limite à sua cobiça, nada salvará daquilo em que se deleita.

[[v18-20-21]]

^<<v18-20-21,21>>^ Nada escapou à sua voracidade; pelo que a sua prosperidade não perdurará.

[[v18-20-22]]

^<<v18-20-22,22>>^ Na plenitude da sua abastança, estará angustiado; toda a força da miséria virá sobre ele.

[[v18-20-23]]

^<<v18-20-23,23>>^ Mesmo estando ele a encher o seu estômago, Deus mandará sobre ele o ardor da sua ira, que fará chover sobre ele quando for comer.

[[v18-20-24]]

^<<v18-20-24,24>>^ Ainda que fuja das armas de ferro, o arco de bronze o atravessará.

[[v18-20-25]]

^<<v18-20-25,25>>^ Ele arranca do seu corpo a flecha, que sai resplandecente do seu fel; terrores vêm sobre ele.

[[v18-20-26]]

^<<v18-20-26,26>>^ Todas as trevas são reservadas paro os seus tesouros; um fogo não assoprado o consumirá, e devorará o que ficar na sua tenda.

[[v18-20-27]]

^<<v18-20-27,27>>^ Os céus revelarão a sua iniqüidade, e contra ele a terra se levantará.

[[v18-20-28]]

^<<v18-20-28,28>>^ As rendas de sua casa ir-se-ão; no dia da ira de Deus todas se derramarão.

[[v18-20-29]]

^<<v18-20-29,29>>^ Esta, da parte de Deus, é a porção do ímpio; esta é a herança que Deus lhe reserva.

'''

xref:018-jo/018-jo-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-jo/018-jo-021.adoc#v18-21-0[Próximo Capítulo &#62;]