include::./index.adoc[]

[[v18-7-0]]
=== Jó, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-7-1]]

^<<v18-7-1,1>>^ Porventura não tem o homem duro serviço sobre a terra? E não são os seus dias como os do jornaleiro?

[[v18-7-2]]

^<<v18-7-2,2>>^ Como o escravo que suspira pela sombra, e como o jornaleiro que espera pela sua paga,

[[v18-7-3]]

^<<v18-7-3,3>>^ assim se me deram meses de escassez, e noites de aflição se me ordenaram.

[[v18-7-4]]

^<<v18-7-4,4>>^ Havendo-me deitado, digo: Quando me levantarei? Mas comprida é a noite, e farto-me de me revolver na cama até a alva.

[[v18-7-5]]

^<<v18-7-5,5>>^ A minha carne se tem vestido de vermes e de torrões de pó; a minha pele endurece, e torna a rebentar-se.

[[v18-7-6]]

^<<v18-7-6,6>>^ Os meus dias são mais velozes do que a lançadeira do tecelão, e chegam ao fim sem esperança.

[[v18-7-7]]

^<<v18-7-7,7>>^ Lembra-te de que a minha vida é um sopro; os meus olhos não tornarão a ver o bem.

[[v18-7-8]]

^<<v18-7-8,8>>^ Os olhos dos que agora me vêem não me verão mais; os teus olhos estarão sobre mim, mas não serei mais.

[[v18-7-9]]

^<<v18-7-9,9>>^ Tal como a nuvem se desfaz e some, aquele que desce à sepultura nunca tornará a subir.

[[v18-7-10]]

^<<v18-7-10,10>>^ Nunca mais tornará à sua casa, nem o seu lugar o conhecerá mais.

[[v18-7-11]]

^<<v18-7-11,11>>^ Por isso não reprimirei a minha boca; falarei na angústia do meu espírito, queixar-me-ei na amargura da minha alma.

[[v18-7-12]]

^<<v18-7-12,12>>^ Sou eu o mar, ou um monstro marinho, para que me ponhas uma guarda?

[[v18-7-13]]

^<<v18-7-13,13>>^ Quando digo: Confortar-me-á a minha cama, meu leito aliviará a minha queixa,

[[v18-7-14]]

^<<v18-7-14,14>>^ então me espantas com sonhos, e com visões me atemorizas;

[[v18-7-15]]

^<<v18-7-15,15>>^ de modo que eu escolheria antes a estrangulação, e a morte do que estes meus ossos.

[[v18-7-16]]

^<<v18-7-16,16>>^ A minha vida abomino; não quero viver para sempre; retira-te de mim, pois os meus dias são vaidade.

[[v18-7-17]]

^<<v18-7-17,17>>^ Que é o homem, para que tanto o engrandeças, e ponhas sobre ele o teu pensamento,

[[v18-7-18]]

^<<v18-7-18,18>>^ e cada manhã o visites, e cada momento o proves?

[[v18-7-19]]

^<<v18-7-19,19>>^ Até quando não apartarás de mim a tua vista, nem me largarás, até que eu possa engolir a minha saliva?

[[v18-7-20]]

^<<v18-7-20,20>>^ Se peco, que te faço a ti, ó vigia dos homens? Por que me fizeste alvo dos teus dardos? Por que a mim mesmo me tornei pesado?

[[v18-7-21]]

^<<v18-7-21,21>>^ Por que me não perdoas a minha transgressão, e não tiras a minha iniqüidade? Pois agora me deitarei no pó; tu me buscarás, porém eu não serei mais.

'''

xref:018-jo/018-jo-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-jo/018-jo-008.adoc#v18-8-0[Próximo Capítulo &#62;]