include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-18-1]]

^<<v18-18-1,1>>^ Então respondeu Bildade, o suíta:

[[v18-18-2]]

^<<v18-18-2,2>>^ Até quando estareis à procura de palavras? considerai bem, e então falaremos.

[[v18-18-3]]

^<<v18-18-3,3>>^ Por que somos tratados como gado, e como estultos aos vossos olhos?

[[v18-18-4]]

^<<v18-18-4,4>>^ Oh tu, que te despedaças na tua ira, acaso por amor de ti será abandonada a terra, ou será a rocha removida do seu lugar?

[[v18-18-5]]

^<<v18-18-5,5>>^ Na verdade, a luz do ímpio se apagará, e não resplandecerá a chama do seu fogo.

[[v18-18-6]]

^<<v18-18-6,6>>^ A luz se escurecerá na sua tenda, e a lâmpada que está sobre ele se apagará.

[[v18-18-7]]

^<<v18-18-7,7>>^ Os seus passos firmes se estreitarão, e o seu próprio conselho o derribará.

[[v18-18-8]]

^<<v18-18-8,8>>^ Pois por seus próprios pés é ele lançado na rede, e pisa nos laços armados.

[[v18-18-9]]

^<<v18-18-9,9>>^ A armadilha o apanha pelo calcanhar, e o laço o prende;

[[v18-18-10]]

^<<v18-18-10,10>>^ a corda do mesmo está-lhe escondida na terra, e uma armadilha na vereda.

[[v18-18-11]]

^<<v18-18-11,11>>^ Terrores o amedrontam de todos os lados, e de perto lhe perseguem os pés.

[[v18-18-12]]

^<<v18-18-12,12>>^ O seu vigor é diminuído pela fome, e a destruição está pronta ao seu lado.

[[v18-18-13]]

^<<v18-18-13,13>>^ São devorados os membros do seu corpo; sim, o primogênito da morte devora os seus membros.

[[v18-18-14]]

^<<v18-18-14,14>>^ Arrancado da sua tenda, em que confiava, é levado ao rei dos terrores.

[[v18-18-15]]

^<<v18-18-15,15>>^ Na sua tenda habita o que não lhe pertence; espalha-se enxofre sobre a sua habitação.

[[v18-18-16]]

^<<v18-18-16,16>>^ Por baixo se secam as suas raízes, e por cima são cortados os seus ramos.

[[v18-18-17]]

^<<v18-18-17,17>>^ A sua memória perece da terra, e pelas praças não tem nome.

[[v18-18-18]]

^<<v18-18-18,18>>^ É lançado da luz para as trevas, e afugentado do mundo.

[[v18-18-19]]

^<<v18-18-19,19>>^ Não tem filho nem neto entre o seu povo, e descendente nenhum lhe ficará nas moradas.

[[v18-18-20]]

^<<v18-18-20,20>>^ Do seu dia pasmam os do ocidente, assim como os do oriente ficam sobressaltados de horror.

[[v18-18-21]]

^<<v18-18-21,21>>^ Tais são, na verdade, as moradas do, ímpio, e tal é o lugar daquele que não conhece a Deus.

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]