include::./index.adoc[]

[[v18-4-0]]
=== Jó, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-4-1]]

^<<v18-4-1,1>>^ Então respondeu Elifaz, o temanita, e disse:

[[v18-4-2]]

^<<v18-4-2,2>>^ Se alguém intentar falar-te, enfadarte-ás? Mas quem poderá conter as palavras?

[[v18-4-3]]

^<<v18-4-3,3>>^ Eis que tens ensinado a muitos, e tens fortalecido as mãos fracas.

[[v18-4-4]]

^<<v18-4-4,4>>^ As tuas palavras têm sustentado aos que cambaleavam, e os joelhos desfalecentes tens fortalecido.

[[v18-4-5]]

^<<v18-4-5,5>>^ Mas agora que se trata de ti, te enfadas; e, tocando-te a ti, te desanimas.

[[v18-4-6]]

^<<v18-4-6,6>>^ Porventura não está a tua confiança no teu temor de Deus, e a tua esperança na integridade dos teus caminhos?

[[v18-4-7]]

^<<v18-4-7,7>>^ Lembra-te agora disto: qual o inocente que jamais pereceu? E onde foram os retos destruídos?

[[v18-4-8]]

^<<v18-4-8,8>>^ Conforme tenho visto, os que lavram iniquidade e semeiam o mal segam o mesmo.

[[v18-4-9]]

^<<v18-4-9,9>>^ Pelo sopro de Deus perecem, e pela rajada da sua ira são consumidos.

[[v18-4-10]]

^<<v18-4-10,10>>^ Cessa o rugido do leão, e a voz do leão feroz; os dentes dos leõezinhos se quebram.

[[v18-4-11]]

^<<v18-4-11,11>>^ Perece o leão velho por falta de presa, e os filhotes da leoa andam dispersos.

[[v18-4-12]]

^<<v18-4-12,12>>^ Ora, uma palavra se me disse em segredo, e os meus ouvidos perceberam um sussurro dela.

[[v18-4-13]]

^<<v18-4-13,13>>^ Entre pensamentos nascidos de visões noturnas, quando cai sobre os homens o sono profundo,

[[v18-4-14]]

^<<v18-4-14,14>>^ sobrevieram-me o espanto e o tremor, que fizeram estremecer todos os meus ossos.

[[v18-4-15]]

^<<v18-4-15,15>>^ Então um espírito passou por diante de mim; arrepiaram-se os cabelos do meu corpo.

[[v18-4-16]]

^<<v18-4-16,16>>^ Parou ele, mas não pude discernir a sua aparência; um vulto estava diante dos meus olhos; houve silêncio, então ouvi uma voz que dizia:

[[v18-4-17]]

^<<v18-4-17,17>>^ Pode o homem mortal ser justo diante de Deus? Pode o varão ser puro diante do seu Criador?

[[v18-4-18]]

^<<v18-4-18,18>>^ Eis que Deus não confia nos seus servos, e até a seus anjos atribui loucura;

[[v18-4-19]]

^<<v18-4-19,19>>^ quanto mais aos que habitam em casas de lodo, cujo fundamento está no pó, e que são esmagados pela traça!

[[v18-4-20]]

^<<v18-4-20,20>>^ Entre a manhã e a tarde são destruídos; perecem para sempre sem que disso se faça caso.

[[v18-4-21]]

^<<v18-4-21,21>>^ Se dentro deles é arrancada a corda da sua tenda, porventura não morrem, e isso sem atingir a sabedoria?

'''

xref:018-jo/018-jo-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-jo/018-jo-005.adoc#v18-5-0[Próximo Capítulo &#62;]