include::./index.adoc[]

[[v18-35-0]]
=== Jó, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-35-1]]

^<<v18-35-1,1>>^ Disse mais Eliú:

[[v18-35-2]]

^<<v18-35-2,2>>^ Tens por direito dizeres: Maior é a minha justiça do que a de Deus?

[[v18-35-3]]

^<<v18-35-3,3>>^ Porque dizes: Que me aproveita? Que proveito tenho mais do que se eu tivera pecado?

[[v18-35-4]]

^<<v18-35-4,4>>^ Eu te darei respostas, a ti e aos teus amigos contigo.

[[v18-35-5]]

^<<v18-35-5,5>>^ Atenta para os céus, e vê; e contempla o firmamento que é mais alto do que tu.

[[v18-35-6]]

^<<v18-35-6,6>>^ Se pecares, que efetuarás contra ele? Se as tuas transgressões se multiplicarem, que lhe farás com isso?

[[v18-35-7]]

^<<v18-35-7,7>>^ Se fores justo, que lhe darás, ou que receberá ele da tua mão?

[[v18-35-8]]

^<<v18-35-8,8>>^ A tua impiedade poderia fazer mal a outro tal como tu; e a tua justiça poderia aproveitar a um filho do homem.

[[v18-35-9]]

^<<v18-35-9,9>>^ Por causa da multidão das opressões os homens clamam; clamam por socorro por causa do braço dos poderosos.

[[v18-35-10]]

^<<v18-35-10,10>>^ Mas ninguém diz: Onde está Deus meu Criador, que inspira canções durante a noite;

[[v18-35-11]]

^<<v18-35-11,11>>^ que nos ensina mais do que aos animais da terra, e nos faz mais sábios do que as aves do céu?

[[v18-35-12]]

^<<v18-35-12,12>>^ Ali clamam, porém ele não responde, por causa da arrogância os maus.

[[v18-35-13]]

^<<v18-35-13,13>>^ Certo é que Deus não ouve o grito da vaidade, nem para ela atentará o Todo-Poderoso.

[[v18-35-14]]

^<<v18-35-14,14>>^ Quanto menos quando tu dizes que não o vês. A causa está perante ele; por isso espera nele.

[[v18-35-15]]

^<<v18-35-15,15>>^ Mas agora, porque a sua ira ainda não se exerce, nem grandemente considera ele a arrogância,

[[v18-35-16]]

^<<v18-35-16,16>>^ por isso abre Jó em vão a sua boca, e sem conhecimento multiplica palavras.

'''

xref:018-jo/018-jo-034.adoc#v18-34-0[&#60; Capítulo Anterior] | <<v18-35-0,Topo>> | xref:018-jo/018-jo-036.adoc#v18-36-0[Próximo Capítulo &#62;]