include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-13-1]]

^<<v18-13-1,1>>^ Eis que os meus olhos viram tudo isto, e os meus ouvidos o ouviram e entenderam.

[[v18-13-2]]

^<<v18-13-2,2>>^ O que vós sabeis também eu o sei; não vos sou inferior.

[[v18-13-3]]

^<<v18-13-3,3>>^ Mas eu falarei ao Todo-Poderoso, e quero defender-me perante Deus.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vós, porém, sois forjadores de mentiras, e vós todos, médicos que não valem nada.

[[v18-13-5]]

^<<v18-13-5,5>>^ Oxalá vos calásseis de todo, pois assim passaríeis por sábios.

[[v18-13-6]]

^<<v18-13-6,6>>^ Ouvi agora a minha defesa, e escutai os argumentos dos meus lábios.

[[v18-13-7]]

^<<v18-13-7,7>>^ Falareis falsamente por Deus, e por ele proferireis mentiras?

[[v18-13-8]]

^<<v18-13-8,8>>^ Fareis aceitação da sua pessoa? Contendereis a favor de Deus?

[[v18-13-9]]

^<<v18-13-9,9>>^ Ser-vos-ia bom, se ele vos esquadrinhasse? Ou zombareis dele, como quem zomba de um homem?

[[v18-13-10]]

^<<v18-13-10,10>>^ Certamente vos repreenderá, se em oculto vos deixardes levar de respeitos humanos.

[[v18-13-11]]

^<<v18-13-11,11>>^ Não vos amedrontará a sua majestade? E não cairá sobre vós o seu terror?

[[v18-13-12]]

^<<v18-13-12,12>>^ As vossas máximas são provérbios de cinza; as vossas defesas são torres de barro.

[[v18-13-13]]

^<<v18-13-13,13>>^ Calai-vos perante mim, para que eu fale, e venha sobre mim o que vier.

[[v18-13-14]]

^<<v18-13-14,14>>^ Tomarei a minha carne entre os meus dentes, e porei a minha vida na minha mão.

[[v18-13-15]]

^<<v18-13-15,15>>^ Eis que ele me matará; não tenho esperança; contudo defenderei os meus caminhos diante dele.

[[v18-13-16]]

^<<v18-13-16,16>>^ Também isso será a minha salvação, pois o ímpio não virá perante ele.

[[v18-13-17]]

^<<v18-13-17,17>>^ Ouvi atentamente as minhas palavras, e chegue aos vossos ouvidos a minha declaração.

[[v18-13-18]]

^<<v18-13-18,18>>^ Eis que já pus em ordem a minha causa, e sei que serei achado justo:

[[v18-13-19]]

^<<v18-13-19,19>>^ Quem é o que contenderá comigo? Pois então me calaria e renderia o espírito.

[[v18-13-20]]

^<<v18-13-20,20>>^ Concede-me somente duas coisas; então não me esconderei do teu rosto:

[[v18-13-21]]

^<<v18-13-21,21>>^ desvia a tua mão rara longe de mim, e não me amedronte o teu terror.

[[v18-13-22]]

^<<v18-13-22,22>>^ Então chama tu, e eu responderei; ou eu falarei, e me responde tu.

[[v18-13-23]]

^<<v18-13-23,23>>^ Quantas iniqüidades e pecados tenho eu? Faze-me saber a minha transgressão e o meu pecado.

[[v18-13-24]]

^<<v18-13-24,24>>^ Por que escondes o teu rosto, e me tens por teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Acossarás uma folha arrebatada pelo vento? E perseguirás o restolho seco?

[[v18-13-26]]

^<<v18-13-26,26>>^ Pois escreves contra mim coisas amargas, e me fazes herdar os erros da minha mocidade;

[[v18-13-27]]

^<<v18-13-27,27>>^ também pões no tronco os meus pés, e observas todos os meus caminhos, e marcas um termo ao redor dos meus pés,

[[v18-13-28]]

^<<v18-13-28,28>>^ apesar de eu ser como uma coisa podre que se consome, e como um vestido, ao qual rói a traça.

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]