include::./index.adoc[]

[[v18-21-0]]
=== Jó, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-21-1]]

^<<v18-21-1,1>>^ Então Jó respondeu:

[[v18-21-2]]

^<<v18-21-2,2>>^ Ouvi atentamente as minhas palavras; seja isto a vossa consolação.

[[v18-21-3]]

^<<v18-21-3,3>>^ Sofrei-me, e eu falarei; e, havendo eu falado, zombai.

[[v18-21-4]]

^<<v18-21-4,4>>^ É porventura do homem que eu me queixo? Mas, ainda que assim fosse, não teria motivo de me impacientar?

[[v18-21-5]]

^<<v18-21-5,5>>^ Olhai para mim, e pasmai, e ponde a mão sobre a boca.

[[v18-21-6]]

^<<v18-21-6,6>>^ Quando me lembro disto, me perturbo, e a minha carne estremece de horror.

[[v18-21-7]]

^<<v18-21-7,7>>^ Por que razão vivem os ímpios, envelhecem, e ainda se robustecem em poder?

[[v18-21-8]]

^<<v18-21-8,8>>^ Os seus filhos se estabelecem à vista deles, e os seus descendentes perante os seus olhos.

[[v18-21-9]]

^<<v18-21-9,9>>^ As suas casas estão em paz, sem temor, e a vara de Deus não está sobre eles.

[[v18-21-10]]

^<<v18-21-10,10>>^ O seu touro gera, e não falha; pare a sua vaca, e não aborta.

[[v18-21-11]]

^<<v18-21-11,11>>^ Eles fazem sair os seus pequeninos, como a um rebanho, e suas crianças andam saltando.

[[v18-21-12]]

^<<v18-21-12,12>>^ Levantam a voz, ao som do tamboril e da harpa, e regozijam-se ao som da flauta.

[[v18-21-13]]

^<<v18-21-13,13>>^ Na prosperidade passam os seus dias, e num momento descem ao Seol.

[[v18-21-14]]

^<<v18-21-14,14>>^ Eles dizem a Deus: retira-te de nós, pois não desejamos ter conhecimento dos teus caminhos.

[[v18-21-15]]

^<<v18-21-15,15>>^ Que é o Todo-Poderoso, para que nós o sirvamos? E que nos aproveitará, se lhe fizermos orações?

[[v18-21-16]]

^<<v18-21-16,16>>^ Vede, porém, que eles não têm na mão a prosperidade; esteja longe de mim o conselho dos ímpios!

[[v18-21-17]]

^<<v18-21-17,17>>^ Quantas vezes sucede que se apague a lâmpada dos ímpios? que lhes sobrevenha a sua destruição? que Deus na sua ira lhes reparta dores?

[[v18-21-18]]

^<<v18-21-18,18>>^ que eles sejam como a palha diante do vento, e como a pragana, que o redemoinho arrebata?

[[v18-21-19]]

^<<v18-21-19,19>>^ Deus, dizeis vós, reserva a iniqüidade do pai para seus filhos, mas é a ele mesmo que Deus deveria punir, para que o conheça.

[[v18-21-20]]

^<<v18-21-20,20>>^ Vejam os seus próprios olhos a sua ruína, e beba ele do furor do Todo-Poderoso.

[[v18-21-21]]

^<<v18-21-21,21>>^ Pois, que lhe importa a sua casa depois de morto, quando lhe for cortado o número dos seus meses?

[[v18-21-22]]

^<<v18-21-22,22>>^ Acaso se ensinará ciência a Deus, a ele que julga os excelsos?

[[v18-21-23]]

^<<v18-21-23,23>>^ Um morre em plena prosperidade, inteiramente sossegado e tranqüilo;

[[v18-21-24]]

^<<v18-21-24,24>>^ com os seus baldes cheios de leite, e a medula dos seus ossos umedecida.

[[v18-21-25]]

^<<v18-21-25,25>>^ Outro, ao contrário, morre em amargura de alma, não havendo provado do bem.

[[v18-21-26]]

^<<v18-21-26,26>>^ Juntamente jazem no pó, e os vermes os cobrem.

[[v18-21-27]]

^<<v18-21-27,27>>^ Eis que conheço os vossos pensamentos, e os maus intentos com que me fazeis injustiça.

[[v18-21-28]]

^<<v18-21-28,28>>^ Pois dizeis: Onde está a casa do príncipe, e onde a tenda em que morava o ímpio?

[[v18-21-29]]

^<<v18-21-29,29>>^ Porventura não perguntastes aos viandantes? e não aceitais o seu testemunho,

[[v18-21-30]]

^<<v18-21-30,30>>^ de que o mau é preservado no dia da destruição, e poupado no dia do furor?

[[v18-21-31]]

^<<v18-21-31,31>>^ Quem acusará diante dele o seu caminho? e quem lhe dará o pago do que fez?

[[v18-21-32]]

^<<v18-21-32,32>>^ Ele é levado para a sepultura, e vigiam-lhe o túmulo.

[[v18-21-33]]

^<<v18-21-33,33>>^ Os torrões do vale lhe são doces, e o seguirão todos os homens, como ele o fez aos inumeráveis que o precederam.

[[v18-21-34]]

^<<v18-21-34,34>>^ Como, pois, me ofereceis consolações vãs, quando nas vossas respostas só resta falsidade?

'''

xref:018-jo/018-jo-020.adoc#v18-20-0[&#60; Capítulo Anterior] | <<v18-21-0,Topo>> | xref:018-jo/018-jo-022.adoc#v18-22-0[Próximo Capítulo &#62;]