include::./index.adoc[]

[[v18-30-0]]
=== Jó, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-30-1]]

^<<v18-30-1,1>>^ Mas agora zombam de mim os de menos idade do que eu, cujos pais teria eu desdenhado de pôr com os cães do meu rebanho.

[[v18-30-2]]

^<<v18-30-2,2>>^ Pois de que me serviria a força das suas mãos, homens nos quais já pereceu o vigor?

[[v18-30-3]]

^<<v18-30-3,3>>^ De míngua e fome emagrecem; andam roendo pelo deserto, lugar de ruínas e desolação.

[[v18-30-4]]

^<<v18-30-4,4>>^ Apanham malvas junto aos arbustos, e o seu mantimento são as raízes dos zimbros.

[[v18-30-5]]

^<<v18-30-5,5>>^ São expulsos do meio dos homens, que gritam atrás deles, como atrás de um ladrão.

[[v18-30-6]]

^<<v18-30-6,6>>^ Têm que habitar nos desfiladeiros sombrios, nas cavernas da terra e dos penhascos.

[[v18-30-7]]

^<<v18-30-7,7>>^ Bramam entre os arbustos, ajuntam-se debaixo das urtigas.

[[v18-30-8]]

^<<v18-30-8,8>>^ São filhos de insensatos, filhos de gente sem nome; da terra foram enxotados.

[[v18-30-9]]

^<<v18-30-9,9>>^ Mas agora vim a ser a sua canção, e lhes sirvo de provérbio.

[[v18-30-10]]

^<<v18-30-10,10>>^ Eles me abominam, afastam-se de mim, e no meu rosto não se privam de cuspir.

[[v18-30-11]]

^<<v18-30-11,11>>^ Porquanto Deus desatou a minha corda e me humilhou, eles sacudiram de si o freio perante o meu rosto.

[[v18-30-12]]

^<<v18-30-12,12>>^ À direita levanta-se gente vil; empurram os meus pés, e contra mim erigem os seus caminhos de destruição.

[[v18-30-13]]

^<<v18-30-13,13>>^ Estragam a minha vereda, promovem a minha calamidade; não há quem os detenha.

[[v18-30-14]]

^<<v18-30-14,14>>^ Vêm como por uma grande brecha, por entre as ruínas se precipitam.

[[v18-30-15]]

^<<v18-30-15,15>>^ Sobrevieram-me pavores; é perseguida a minha honra como pelo vento; e como nuvem passou a minha felicidade.

[[v18-30-16]]

^<<v18-30-16,16>>^ E agora dentro de mim se derrama a minha alma; os dias da aflição se apoderaram de mim.

[[v18-30-17]]

^<<v18-30-17,17>>^ De noite me são traspassados os ossos, e o mal que me corrói não descansa.

[[v18-30-18]]

^<<v18-30-18,18>>^ Pela violência do mal está desfigurada a minha veste; como a gola da minha túnica, me aperta.

[[v18-30-19]]

^<<v18-30-19,19>>^ Ele me lançou na lama, e fiquei semelhante ao pó e à cinza.

[[v18-30-20]]

^<<v18-30-20,20>>^ Clamo a ti, e não me respondes; ponho-me em pé, e não atentas para mim.

[[v18-30-21]]

^<<v18-30-21,21>>^ Tornas-te cruel para comigo; com a força da tua mão me persegues.

[[v18-30-22]]

^<<v18-30-22,22>>^ Levantas-me sobre o vento, fazes-me cavalgar sobre ele, e dissolves-me na tempestade.

[[v18-30-23]]

^<<v18-30-23,23>>^ Pois eu sei que me levarás à morte, e à casa do ajuntamento destinada a todos os viventes.

[[v18-30-24]]

^<<v18-30-24,24>>^ Contudo não estende a mão quem está a cair? ou não clama por socorro na sua calamidade?

[[v18-30-25]]

^<<v18-30-25,25>>^ Não chorava eu sobre aquele que estava aflito? ou não se angustiava a minha alma pelo necessitado?

[[v18-30-26]]

^<<v18-30-26,26>>^ Todavia aguardando eu o bem, eis que me veio o mal, e esperando eu a luz, veio a escuridão.

[[v18-30-27]]

^<<v18-30-27,27>>^ As minhas entranhas fervem e não descansam; os dias da aflição me surpreenderam.

[[v18-30-28]]

^<<v18-30-28,28>>^ Denegrido ando, mas não do sol; levanto-me na congregação, e clamo por socorro.

[[v18-30-29]]

^<<v18-30-29,29>>^ Tornei-me irmão dos chacais, e companheiro dos avestruzes.

[[v18-30-30]]

^<<v18-30-30,30>>^ A minha pele enegrece e se me cai, e os meus ossos estão queimados do calor.

[[v18-30-31]]

^<<v18-30-31,31>>^ Pelo que se tornou em pranto a minha harpa, e a minha flauta em voz dos que choram.

'''

xref:018-jo/018-jo-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-jo/018-jo-031.adoc#v18-31-0[Próximo Capítulo &#62;]