include::./index.adoc[]

[[v18-39-0]]
=== Jó, 39
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-39-1]]

^<<v18-39-1,1>>^ Sabes tu o tempo do parto das cabras montesas, ou podes observar quando é que parem as corças?

[[v18-39-2]]

^<<v18-39-2,2>>^ Podes contar os meses que cumprem, ou sabes o tempo do seu parto?

[[v18-39-3]]

^<<v18-39-3,3>>^ Encurvam-se, dão à luz as suas crias, lançam de si a sua prole.

[[v18-39-4]]

^<<v18-39-4,4>>^ Seus filhos enrijam, crescem no campo livre; saem, e não tornam para elas:

[[v18-39-5]]

^<<v18-39-5,5>>^ Quem despediu livre o jumento montês, e quem soltou as prisões ao asno veloz,

[[v18-39-6]]

^<<v18-39-6,6>>^ ao qual dei o ermo por casa, e a terra salgada por morada?

[[v18-39-7]]

^<<v18-39-7,7>>^ Ele despreza o tumulto da cidade; não obedece os gritos do condutor.

[[v18-39-8]]

^<<v18-39-8,8>>^ O circuito das montanhas é o seu pasto, e anda buscando tudo o que está verde.

[[v18-39-9]]

^<<v18-39-9,9>>^ Quererá o boi selvagem servir-te? ou ficará junto à tua manjedoura?

[[v18-39-10]]

^<<v18-39-10,10>>^ Podes amarrar o boi selvagem ao arado com uma corda, ou esterroará ele após ti os vales?

[[v18-39-11]]

^<<v18-39-11,11>>^ Ou confiarás nele, por ser grande a sua força, ou deixarás a seu cargo o teu trabalho?

[[v18-39-12]]

^<<v18-39-12,12>>^ Fiarás dele que te torne o que semeaste e o recolha à tua eira?

[[v18-39-13]]

^<<v18-39-13,13>>^ Movem-se alegremente as asas da avestruz; mas é benigno o adorno da sua plumagem?

[[v18-39-14]]

^<<v18-39-14,14>>^ Pois ela deixa os seus ovos na terra, e os aquenta no pó,

[[v18-39-15]]

^<<v18-39-15,15>>^ e se esquece de que algum pé os pode pisar, ou de que a fera os pode calcar.

[[v18-39-16]]

^<<v18-39-16,16>>^ Endurece-se para com seus filhos, como se não fossem seus; embora se perca o seu trabalho, ela está sem temor;

[[v18-39-17]]

^<<v18-39-17,17>>^ porque Deus a privou de sabedoria, e não lhe repartiu entendimento.

[[v18-39-18]]

^<<v18-39-18,18>>^ Quando ela se levanta para correr, zomba do cavalo, e do cavaleiro.

[[v18-39-19]]

^<<v18-39-19,19>>^ Acaso deste força ao cavalo, ou revestiste de força o seu pescoço?

[[v18-39-20]]

^<<v18-39-20,20>>^ Fizeste-o pular como o gafanhoto? Terrível é o fogoso respirar das suas ventas.

[[v18-39-21]]

^<<v18-39-21,21>>^ Escarva no vale, e folga na sua força, e sai ao encontro dos armados.

[[v18-39-22]]

^<<v18-39-22,22>>^ Ri-se do temor, e não se espanta; e não torna atrás por causa da espada.

[[v18-39-23]]

^<<v18-39-23,23>>^ Sobre ele rangem a aljava, a lança cintilante e o dardo.

[[v18-39-24]]

^<<v18-39-24,24>>^ Tremendo e enfurecido devora a terra, e não se contém ao som da trombeta.

[[v18-39-25]]

^<<v18-39-25,25>>^ Toda vez que soa a trombeta, diz: Eia! E de longe cheira a guerra, e o trovão dos capitães e os gritos.

[[v18-39-26]]

^<<v18-39-26,26>>^ É pelo teu entendimento que se eleva o gavião, e estende as suas asas para o sul?

[[v18-39-27]]

^<<v18-39-27,27>>^ Ou se remonta a águia ao teu mandado, e põe no alto o seu ninho?

[[v18-39-28]]

^<<v18-39-28,28>>^ Mora nas penhas e ali tem a sua pousada, no cume das penhas, no lugar seguro.

[[v18-39-29]]

^<<v18-39-29,29>>^ Dali descobre a presa; seus olhos a avistam de longe.

[[v18-39-30]]

^<<v18-39-30,30>>^ Seus filhos chupam o sangue; e onde há mortos, ela aí está.

'''

xref:018-jo/018-jo-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-jo/018-jo-040.adoc#v18-40-0[Próximo Capítulo &#62;]