include::./index.adoc[]

[[v18-42-0]]
=== Jó, 42
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-42-1]]

^<<v18-42-1,1>>^ Então respondeu Jó ao Senhor:

[[v18-42-2]]

^<<v18-42-2,2>>^ Bem sei eu que tudo podes, e que nenhum dos teus propósitos pode ser impedido.

[[v18-42-3]]

^<<v18-42-3,3>>^ Quem é este que sem conhecimento obscurece o conselho? por isso falei do que não entendia; coisas que para mim eram demasiado maravilhosas, e que eu não conhecia.

[[v18-42-4]]

^<<v18-42-4,4>>^ Ouve, pois, e eu falarei; eu te perguntarei, e tu me responderas.

[[v18-42-5]]

^<<v18-42-5,5>>^ Com os ouvidos eu ouvira falar de ti; mas agora te vêem os meus olhos.

[[v18-42-6]]

^<<v18-42-6,6>>^ Pelo que me abomino, e me arrependo no pó e na cinza.

[[v18-42-7]]

^<<v18-42-7,7>>^ Sucedeu pois que, acabando o Senhor de dizer a Jó aquelas palavras, o Senhor disse a Elifaz, o temanita: A minha ira se acendeu contra ti e contra os teus dois amigos, porque não tendes falado de mim o que era reto, como o meu servo Jó.

[[v18-42-8]]

^<<v18-42-8,8>>^ Tomai, pois, sete novilhos e sete carneiros, e ide ao meu servo Jó, e oferecei um holocausto por vós; e o meu servo Jó orará por vós; porque deveras a ele aceitarei, para que eu não vos trate conforme a vossa estultícia; porque vós não tendes falado de mim o que era reto, como o meu servo Jó.

[[v18-42-9]]

^<<v18-42-9,9>>^ Então foram Elifaz o temanita, e Bildade o suíta, e Zofar o naamatita, e fizeram como o Senhor lhes ordenara; e o Senhor aceitou a Jó.

[[v18-42-10]]

^<<v18-42-10,10>>^ O Senhor, pois, virou o cativeiro de Jó, quando este orava pelos seus amigos; e o Senhor deu a Jó o dobro do que antes possuía.

[[v18-42-11]]

^<<v18-42-11,11>>^ Então vieram ter com ele todos os seus irmãos, e todas as suas irmãs, e todos quantos dantes o conheceram, e comeram com ele pão em sua casa; condoeram-se dele, e o consolaram de todo o mal que o Senhor lhe havia enviado; e cada um deles lhe deu uma peça de dinheiro e um pendente de ouro.

[[v18-42-12]]

^<<v18-42-12,12>>^ E assim abençoou o Senhor o último estado de Jó, mais do que o primeiro; pois Jó chegou a ter catorze mil ovelhas, seis mil camelos, mil juntas de bois e mil jumentas.

[[v18-42-13]]

^<<v18-42-13,13>>^ Também teve sete filhos e três filhas.

[[v18-42-14]]

^<<v18-42-14,14>>^ E chamou o nome da primeira Jemima, e o nome da segunda Quezia, e o nome da terceira Quéren-Hapuque.

[[v18-42-15]]

^<<v18-42-15,15>>^ E em toda a terra não se acharam mulheres tão formosas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos.

[[v18-42-16]]

^<<v18-42-16,16>>^ Depois disto viveu Jó cento e quarenta anos, e viu seus filhos, e os filhos de seus filhos: até a quarta geração.

[[v18-42-17]]

^<<v18-42-17,17>>^ Então morreu Jó, velho e cheio de dias.

'''

xref:018-jo/018-jo-041.adoc#v18-41-0[&#60; Capítulo Anterior] | <<v18-42-0,Topo>> | xref:019-salmos/019-salmos-001.adoc#v19-1-0[Próximo Capítulo &#62;]