include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-32-1]]

^<<v18-32-1,1>>^ E aqueles três homens cessaram de responder a Jó; porque era justo aos seus próprios olhos.

[[v18-32-2]]

^<<v18-32-2,2>>^ Então se acendeu a ira de Eliú, filho de Baraquel, o buzita, da família de Rão; acendeu-se a sua ira contra Jó, porque este se justificava a si mesmo, e não a Deus.

[[v18-32-3]]

^<<v18-32-3,3>>^ Também contra os seus três amigos se acendeu a sua ira, porque não tinham achado o que responder, e contudo tinham condenado a Jó.

[[v18-32-4]]

^<<v18-32-4,4>>^ Ora, Eliú havia esperado para falar a Jó, porque eles eram mais idosos do que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Quando, pois, Eliú viu que não havia resposta na boca daqueles três homens, acendeu-se-lhe a ira.

[[v18-32-6]]

^<<v18-32-6,6>>^ Então respondeu Eliú, filho de Baraquel, o buzita, dizendo: Eu sou de pouca idade, e vós sois, idosos; arreceei-me e temi de vos declarar a minha opinião.

[[v18-32-7]]

^<<v18-32-7,7>>^ Dizia eu: Falem os dias, e a multidão dos anos ensine a sabedoria.

[[v18-32-8]]

^<<v18-32-8,8>>^ Há, porém, um espírito no homem, e o sopro do Todo-Poderoso o faz entendido.

[[v18-32-9]]

^<<v18-32-9,9>>^ Não são os velhos que são os sábios, nem os anciãos que entendem o que é reto.

[[v18-32-10]]

^<<v18-32-10,10>>^ Pelo que digo: Ouvi-me, e também eu declararei a minha opinião.

[[v18-32-11]]

^<<v18-32-11,11>>^ Eis que aguardei as vossas palavras, escutei as vossas considerações, enquanto buscáveis o que dizer.

[[v18-32-12]]

^<<v18-32-12,12>>^ Eu, pois, vos prestava toda a minha atenção, e eis que não houve entre vós quem convencesse a Jó, nem quem respondesse às suas palavras;

[[v18-32-13]]

^<<v18-32-13,13>>^ pelo que não digais: Achamos a sabedoria; Deus é que pode derrubá-lo, e não o homem.

[[v18-32-14]]

^<<v18-32-14,14>>^ Ora ele não dirigiu contra mim palavra alguma, nem lhe responderei com as vossas palavras.

[[v18-32-15]]

^<<v18-32-15,15>>^ Estão pasmados, não respondem mais; faltam-lhes as palavras.

[[v18-32-16]]

^<<v18-32-16,16>>^ Hei de eu esperar, porque eles não falam, porque já pararam, e não respondem mais?

[[v18-32-17]]

^<<v18-32-17,17>>^ Eu também darei a minha resposta; eu também declararei a minha opinião.

[[v18-32-18]]

^<<v18-32-18,18>>^ Pois estou cheio de palavras; o espírito dentro de mim me constrange.

[[v18-32-19]]

^<<v18-32-19,19>>^ Eis que o meu peito é como o mosto, sem respiradouro, como odres novos que estão para arrebentar.

[[v18-32-20]]

^<<v18-32-20,20>>^ Falarei, para que ache alívio; abrirei os meus lábios e responderei:

[[v18-32-21]]

^<<v18-32-21,21>>^ Que não faça eu acepção de pessoas, nem use de lisonjas para com o homem.

[[v18-32-22]]

^<<v18-32-22,22>>^ Porque não sei usar de lisonjas; do contrário, em breve me levaria o meu Criador.

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]