include::./index.adoc[]

[[v18-6-0]]
=== Jó, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-6-1]]

^<<v18-6-1,1>>^ Então Jó, respondendo, disse:

[[v18-6-2]]

^<<v18-6-2,2>>^ Oxalá de fato se pesasse a minha mágoa, e juntamente na balança se pusesse a minha calamidade!

[[v18-6-3]]

^<<v18-6-3,3>>^ Pois, na verdade, seria mais pesada do que a areia dos mares; por isso é que as minhas palavras têm sido temerárias.

[[v18-6-4]]

^<<v18-6-4,4>>^ Porque as flechas do Todo-Poderoso se cravaram em mim, e o meu espírito suga o veneno delas; os terrores de Deus se arregimentam contra mim.

[[v18-6-5]]

^<<v18-6-5,5>>^ Zurrará o asno montês quando tiver erva? Ou mugirá o boi junto ao seu pasto?:

[[v18-6-6]]

^<<v18-6-6,6>>^ Pode se comer sem sal o que é insípido? Ou há gosto na clara do ovo?

[[v18-6-7]]

^<<v18-6-7,7>>^ Nessas coisas a minha alma recusa tocar, pois são para mim qual comida repugnante.

[[v18-6-8]]

^<<v18-6-8,8>>^ Quem dera que se cumprisse o meu rogo, e que Deus me desse o que anelo!

[[v18-6-9]]

^<<v18-6-9,9>>^ que fosse do agrado de Deus esmagar-me; que soltasse a sua mão, e me exterminasse!

[[v18-6-10]]

^<<v18-6-10,10>>^ Isto ainda seria a minha consolação, e exultaria na dor que não me poupa; porque não tenho negado as palavras do Santo.

[[v18-6-11]]

^<<v18-6-11,11>>^ Qual é a minha força, para que eu espere? Ou qual é o meu fim, para que me porte com paciência?

[[v18-6-12]]

^<<v18-6-12,12>>^ É a minha força a força da pedra? Ou é de bronze a minha carne?

[[v18-6-13]]

^<<v18-6-13,13>>^ Na verdade não há em mim socorro nenhum. Não me desamparou todo o auxílio eficaz?

[[v18-6-14]]

^<<v18-6-14,14>>^ Ao que desfalece devia o amigo mostrar compaixão; mesmo ao que abandona o temor do Todo-Poderoso.

[[v18-6-15]]

^<<v18-6-15,15>>^ Meus irmãos houveram-se aleivosamente, como um ribeiro, como a torrente dos ribeiros que passam,

[[v18-6-16]]

^<<v18-6-16,16>>^ os quais se turvam com o gelo, e neles se esconde a neve;

[[v18-6-17]]

^<<v18-6-17,17>>^ no tempo do calor vão minguando; e quando o calor vem, desaparecem do seu lugar.

[[v18-6-18]]

^<<v18-6-18,18>>^ As caravanas se desviam do seu curso; sobem ao deserto, e perecem.

[[v18-6-19]]

^<<v18-6-19,19>>^ As caravanas de Tema olham; os viandantes de Sabá por eles esperam.

[[v18-6-20]]

^<<v18-6-20,20>>^ Ficam envergonhados por terem confiado; e, chegando ali, se confundem.

[[v18-6-21]]

^<<v18-6-21,21>>^ Agora, pois, tais vos tornastes para mim; vedes a minha calamidade e temeis.

[[v18-6-22]]

^<<v18-6-22,22>>^ Acaso disse eu: Dai-me um presente? Ou: Fazei-me uma oferta de vossos bens?

[[v18-6-23]]

^<<v18-6-23,23>>^ Ou: Livrai-me das mãos do adversário? Ou: Resgatai-me das mãos dos opressores ?

[[v18-6-24]]

^<<v18-6-24,24>>^ Ensinai-me, e eu me calarei; e fazei-me entender em que errei.

[[v18-6-25]]

^<<v18-6-25,25>>^ Quão poderosas são as palavras da boa razão! Mas que é o que a vossa argüição reprova?

[[v18-6-26]]

^<<v18-6-26,26>>^ Acaso pretendeis reprovar palavras, embora sejam as razões do desesperado como vento?

[[v18-6-27]]

^<<v18-6-27,27>>^ Até quereis lançar sortes sobre o órfão, e fazer mercadoria do vosso amigo.

[[v18-6-28]]

^<<v18-6-28,28>>^ Agora, pois, por favor, olhai para, mim; porque de certo à vossa face não mentirei.

[[v18-6-29]]

^<<v18-6-29,29>>^ Mudai de parecer, peço-vos, não haja injustiça; sim, mudai de parecer, que a minha causa é justa.

[[v18-6-30]]

^<<v18-6-30,30>>^ Há iniqüidade na minha língua? Ou não poderia o meu paladar discernir coisas perversas?

'''

xref:018-jo/018-jo-005.adoc#v18-5-0[&#60; Capítulo Anterior] | <<v18-6-0,Topo>> | xref:018-jo/018-jo-007.adoc#v18-7-0[Próximo Capítulo &#62;]