include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-22-1]]

^<<v18-22-1,1>>^ Então respondeu Elifaz, o temanita:

[[v18-22-2]]

^<<v18-22-2,2>>^ Pode o homem ser de algum proveito a Deus? Antes a si mesmo é que o prudente será proveitoso.

[[v18-22-3]]

^<<v18-22-3,3>>^ Tem o Todo-Poderoso prazer em que tu sejas justo, ou lucro em que tu faças perfeitos os teus caminhos?

[[v18-22-4]]

^<<v18-22-4,4>>^ É por causa da tua reverência que te repreende, ou que entra contigo em juízo?

[[v18-22-5]]

^<<v18-22-5,5>>^ Não é grande a tua malícia, e sem termo as tuas iniqüidades?

[[v18-22-6]]

^<<v18-22-6,6>>^ Pois sem causa tomaste penhores a teus irmãos e aos nus despojaste dos vestidos.

[[v18-22-7]]

^<<v18-22-7,7>>^ Não deste ao cansado água a beber, e ao faminto retiveste o pão.

[[v18-22-8]]

^<<v18-22-8,8>>^ Mas ao poderoso pertencia a terra, e o homem acatado habitava nela.

[[v18-22-9]]

^<<v18-22-9,9>>^ Despediste vazias as viúvas, e os braços dos órfãos foram quebrados.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso é que estás cercado de laços, e te perturba um pavor repentino,

[[v18-22-11]]

^<<v18-22-11,11>>^ ou trevas de modo que nada podes ver, e a inundação de águas te cobre.

[[v18-22-12]]

^<<v18-22-12,12>>^ Não está Deus na altura do céu? Olha para as mais altas estrelas, quão elevadas estão!

[[v18-22-13]]

^<<v18-22-13,13>>^ E dizes: Que sabe Deus? Pode ele julgar através da escuridão?

[[v18-22-14]]

^<<v18-22-14,14>>^ Grossas nuvens o encobrem, de modo que não pode ver; e ele passeia em volta da abóbada do céu.

[[v18-22-15]]

^<<v18-22-15,15>>^ Queres seguir a vereda antiga, que pisaram os homens iníquos?

[[v18-22-16]]

^<<v18-22-16,16>>^ Os quais foram arrebatados antes do seu tempo; e o seu fundamento se derramou qual um rio.

[[v18-22-17]]

^<<v18-22-17,17>>^ Diziam a Deus: retira-te de nós; e ainda: Que é que o Todo-Poderoso nos pode fazer?

[[v18-22-18]]

^<<v18-22-18,18>>^ Contudo ele encheu de bens as suas casas. Mas longe de mim estejam os conselhos dos ímpios!

[[v18-22-19]]

^<<v18-22-19,19>>^ Os justos o vêem, e se alegram: e os inocentes escarnecem deles,

[[v18-22-20]]

^<<v18-22-20,20>>^ dizendo: Na verdade são exterminados os nossos adversários, e o fogo consumiu o que deixaram.

[[v18-22-21]]

^<<v18-22-21,21>>^ Apega-te, pois, a Deus, e tem paz, e assim te sobrevirá o bem.

[[v18-22-22]]

^<<v18-22-22,22>>^ Aceita, peço-te, a lei da sua boca, e põe as suas palavras no teu coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se te voltares para o Todo-Poderoso, serás edificado; se lançares a iniqüidade longe da tua tenda,

[[v18-22-24]]

^<<v18-22-24,24>>^ e deitares o teu tesouro no pó, e o ouro de Ofir entre as pedras dos ribeiros,

[[v18-22-25]]

^<<v18-22-25,25>>^ então o Todo-Poderoso será o teu tesouro, e a tua prata preciosa.

[[v18-22-26]]

^<<v18-22-26,26>>^ Pois então te deleitarás no Todo-Poderoso, e levantarás o teu rosto para Deus.

[[v18-22-27]]

^<<v18-22-27,27>>^ Tu orarás a ele, e ele te ouvirá; e pagarás os teus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ Também determinarás algum negócio, e ser-te-á firme, e a luz brilhará em teus caminhos.

[[v18-22-29]]

^<<v18-22-29,29>>^ Quando te abaterem, dirás: haja exaltação! E Deus salvará ao humilde.

[[v18-22-30]]

^<<v18-22-30,30>>^ E livrará até o que não é inocente, que será libertado pela pureza de tuas mãos.

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]