include::./index.adoc[]

[[v18-34-0]]
=== Jó, 34
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v18-34-1]]

^<<v18-34-1,1>>^ Prosseguiu Eliú, dizendo:

[[v18-34-2]]

^<<v18-34-2,2>>^ Ouvi, vós, sábios, as minhas palavras; e vós, entendidos, inclinai os ouvidos para mim.

[[v18-34-3]]

^<<v18-34-3,3>>^ Pois o ouvido prova as palavras, como o paladar experimenta a comida.

[[v18-34-4]]

^<<v18-34-4,4>>^ O que é direito escolhamos para nós; e conheçamos entre nós o que é bom.

[[v18-34-5]]

^<<v18-34-5,5>>^ Pois Jó disse: Sou justo, e Deus tirou-me o direito.

[[v18-34-6]]

^<<v18-34-6,6>>^ Apesar do meu direito, sou considerado mentiroso; a minha ferida é incurável, embora eu esteja sem transgressão.

[[v18-34-7]]

^<<v18-34-7,7>>^ Que homem há como Jó, que bebe o escárnio como água,

[[v18-34-8]]

^<<v18-34-8,8>>^ que anda na companhia dos malfeitores, e caminha com homens ímpios?

[[v18-34-9]]

^<<v18-34-9,9>>^ Porque disse: De nada aproveita ao homem o comprazer-se em Deus.

[[v18-34-10]]

^<<v18-34-10,10>>^ Pelo que ouvi-me, vós homens de entendimento: longe de Deus o praticar a maldade, e do Todo-Poderoso o cometer a iniqüidade!

[[v18-34-11]]

^<<v18-34-11,11>>^ Pois, segundo a obra do homem, ele lhe retribui, e faz a cada um segundo o seu caminho.

[[v18-34-12]]

^<<v18-34-12,12>>^ Na verdade, Deus não procederá impiamente, nem o Todo-Poderoso perverterá o juízo.

[[v18-34-13]]

^<<v18-34-13,13>>^ Quem lhe entregou o governo da terra? E quem lhe deu autoridade sobre o mundo todo?

[[v18-34-14]]

^<<v18-34-14,14>>^ Se ele retirasse para si o seu espírito, e recolhesse para si o seu fôlego,

[[v18-34-15]]

^<<v18-34-15,15>>^ toda a carne juntamente expiraria, e o homem voltaria para o pó.

[[v18-34-16]]

^<<v18-34-16,16>>^ Se, pois, há em ti entendimento, ouve isto, inclina os ouvidos às palavras que profiro.

[[v18-34-17]]

^<<v18-34-17,17>>^ Acaso quem odeia o direito governará? Quererás tu condenar aquele que é justo e poderoso?

[[v18-34-18]]

^<<v18-34-18,18>>^ aquele que diz a um rei: Ó vil? e aos príncipes: Ó ímpios?

[[v18-34-19]]

^<<v18-34-19,19>>^ que não faz acepção das pessoas de príncipes, nem estima o rico mais do que o pobre; porque todos são obra de suas mãos?

[[v18-34-20]]

^<<v18-34-20,20>>^ Eles num momento morrem; e à meia-noite os povos são perturbados, e passam, e os poderosos são levados não por mão humana.

[[v18-34-21]]

^<<v18-34-21,21>>^ Porque os seus olhos estão sobre os caminhos de cada um, e ele vê todos os seus passos.

[[v18-34-22]]

^<<v18-34-22,22>>^ Não há escuridão nem densas trevas, onde se escondam os obradores da iniqüidade.

[[v18-34-23]]

^<<v18-34-23,23>>^ Porque Deus não precisa observar por muito tempo o homem para que este compareça perante ele em juízo.

[[v18-34-24]]

^<<v18-34-24,24>>^ Ele quebranta os fortes, sem inquirição, e põe outros em lugar deles.

[[v18-34-25]]

^<<v18-34-25,25>>^ Pois conhecendo ele as suas obras, de noite os transtorna, e ficam esmagados.

[[v18-34-26]]

^<<v18-34-26,26>>^ Ele os fere como ímpios, à vista dos circunstantes;

[[v18-34-27]]

^<<v18-34-27,27>>^ porquanto se desviaram dele, e não quiseram compreender nenhum de seus caminhos,

[[v18-34-28]]

^<<v18-34-28,28>>^ de sorte que o clamor do pobre subisse até ele, e que ouvisse o clamor dos aflitos.

[[v18-34-29]]

^<<v18-34-29,29>>^ Se ele dá tranqüilidade, quem então o condenará? Se ele encobrir o rosto, quem então o poderá contemplar, quer seja uma nação, quer seja um homem só?

[[v18-34-30]]

^<<v18-34-30,30>>^ para que o ímpio não reine, e não haja quem iluda o povo.

[[v18-34-31]]

^<<v18-34-31,31>>^ Pois, quem jamais disse a Deus: Sofri, ainda que não pequei;

[[v18-34-32]]

^<<v18-34-32,32>>^ o que não vejo, ensina-me tu; se fiz alguma maldade, nunca mais a hei de fazer?

[[v18-34-33]]

^<<v18-34-33,33>>^ Será a sua recompensa como queres, para que a recuses? Pois tu tens que fazer a escolha, e não eu; portanto fala o que sabes.

[[v18-34-34]]

^<<v18-34-34,34>>^ Os homens de entendimento dir-me-ão, e o varão sábio, que me ouvir:

[[v18-34-35]]

^<<v18-34-35,35>>^ Jó fala sem conhecimento, e às suas palavras falta sabedoria.

[[v18-34-36]]

^<<v18-34-36,36>>^ Oxalá que Jó fosse provado até o fim; porque responde como os iníquos.

[[v18-34-37]]

^<<v18-34-37,37>>^ Porque ao seu pecado acrescenta a rebelião; entre nós bate as palmas, e multiplica contra Deus as suas palavras.

'''

xref:018-jo/018-jo-033.adoc#v18-33-0[&#60; Capítulo Anterior] | <<v18-34-0,Topo>> | xref:018-jo/018-jo-035.adoc#v18-35-0[Próximo Capítulo &#62;]