include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v54-2-1]]

^<<v54-2-1,1>>^ Exorto, pois, antes de tudo que se façam súplicas, orações, intercessões, e ações de graças por todos os homens,

[[v54-2-2]]

^<<v54-2-2,2>>^ pelos reis, e por todos os que exercem autoridade, para que tenhamos uma vida tranqüila e sossegada, em toda a piedade e honestidade.

[[v54-2-3]]

^<<v54-2-3,3>>^ Pois isto é bom e agradável diante de Deus nosso Salvador,

[[v54-2-4]]

^<<v54-2-4,4>>^ o qual deseja que todos os homens sejam salvos e cheguem ao pleno conhecimento da verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Porque há um só Deus, e um só Mediador entre Deus e os homens, Cristo Jesus, homem,

[[v54-2-6]]

^<<v54-2-6,6>>^ o qual se deu a si mesmo em resgate por todos, para servir de testemunho a seu tempo;

[[v54-2-7]]

^<<v54-2-7,7>>^ para o que &#123;digo a verdade, não minto&#125; eu fui constituído pregador e apóstolo, mestre dos gentios na fé e na verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Quero, pois, que os homens orem em todo lugar, levantando mãos santas, sem ira nem contenda.

[[v54-2-9]]

^<<v54-2-9,9>>^ Quero, do mesmo modo, que as mulheres se ataviem com traje decoroso, com modéstia e sobriedade, não com tranças, ou com ouro, ou pérolas, ou vestidos custosos,

[[v54-2-10]]

^<<v54-2-10,10>>^ mas &#123;como convém a mulheres que fazem profissão de servir a Deus&#125; com boas obras.

[[v54-2-11]]

^<<v54-2-11,11>>^ A mulher aprenda em silêncio com toda a submissão.

[[v54-2-12]]

^<<v54-2-12,12>>^ Pois não permito que a mulher ensine, nem tenha domínio sobre o homem, mas que esteja em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Porque primeiro foi formado Adão, depois Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ E Adão não foi enganado, mas a mulher, sendo enganada, caiu em transgressão;

[[v54-2-15]]

^<<v54-2-15,15>>^ salvar-se-á, todavia, dando à luz filhos, se permanecer com sobriedade na fé, no amor e na santificação.

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]