include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v54-6-1]]

^<<v54-6-1,1>>^ Todos os servos que estão debaixo do jugo considerem seus senhores dignos de toda honra, para que o nome de Deus e a doutrina não sejam blasfemados.

[[v54-6-2]]

^<<v54-6-2,2>>^ E os que têm senhores crentes não os desprezem, porque são irmãos; antes os sirvam melhor, porque eles, que se utilizam do seu bom serviço, são crentes e amados. Ensina estas coisas.

[[v54-6-3]]

^<<v54-6-3,3>>^ Se alguém ensina alguma doutrina diversa, e não se conforma com as sãs palavras de nosso Senhor Jesus Cristo, e com a doutrina que é segundo a piedade,

[[v54-6-4]]

^<<v54-6-4,4>>^ é soberbo, e nada sabe, mas delira acerca de questões e contendas de palavras, das quais nascem invejas, porfias, injúrias, suspeitas maliciosas,

[[v54-6-5]]

^<<v54-6-5,5>>^ disputas de homens corruptos de entendimento, e privados da verdade, cuidando que a piedade é fonte de lucro;

[[v54-6-6]]

^<<v54-6-6,6>>^ e, de fato, é grande fonte de lucro a piedade com o contentamento.

[[v54-6-7]]

^<<v54-6-7,7>>^ Porque nada trouxe para este mundo, e nada podemos daqui levar;

[[v54-6-8]]

^<<v54-6-8,8>>^ tendo, porém, alimento e vestuário, estaremos com isso contentes.

[[v54-6-9]]

^<<v54-6-9,9>>^ Mas os que querem tornar-se ricos caem em tentação e em laço, e em muitas concupiscências loucas e nocivas, as quais submergem os homens na ruína e na perdição.

[[v54-6-10]]

^<<v54-6-10,10>>^ Porque o amor ao dinheiro é raiz de todos os males; e nessa cobiça alguns se desviaram da fé, e se traspassaram a si mesmos com muitas dores.

[[v54-6-11]]

^<<v54-6-11,11>>^ Mas tu, ó homem de Deus, foge destas coisas, e segue a justiça, a piedade, a fé, o amor, a constância, a mansidão.

[[v54-6-12]]

^<<v54-6-12,12>>^ Peleja a boa peleja da fé, apodera-te da vida eterna, para a qual foste chamado, tendo já feito boa confissão diante de muitas testemunhas.

[[v54-6-13]]

^<<v54-6-13,13>>^ Diante de Deus, que todas as coisas vivifica, e de Cristo Jesus, que perante Pôncio Pilatos deu o testemunho da boa confissão, exorto-te

[[v54-6-14]]

^<<v54-6-14,14>>^ a que guardes este mandamento sem mácula e irrepreensível até a vinda de nosso Senhor Jesus Cristo;

[[v54-6-15]]

^<<v54-6-15,15>>^ a qual, no tempo próprio, manifestará o bem-aventurado e único soberano, Rei dos reis e Senhor dos senhores;

[[v54-6-16]]

^<<v54-6-16,16>>^ aquele que possui, ele só, a imortalidade, e habita em luz inacessível; a quem nenhum dos homens tem visto nem pode ver; ao qual seja honra e poder sempiterno. Amém.

[[v54-6-17]]

^<<v54-6-17,17>>^ manda aos ricos deste mundo que não sejam altivos, nem ponham a sua esperança na incerteza das riquezas, mas em Deus, que nos concede abundantemente todas as coisas para delas gozarmos;

[[v54-6-18]]

^<<v54-6-18,18>>^ que pratiquem o bem, que se enriqueçam de boas obras, que sejam liberais e generosos,

[[v54-6-19]]

^<<v54-6-19,19>>^ entesourando para si mesmos um bom fundamento para o futuro, para que possam alcançar a verdadeira vida.

[[v54-6-20]]

^<<v54-6-20,20>>^ Ó Timóteo, guarda o depósito que te foi confiado, evitando as conversas vãs e profanas e as oposições da falsamente chamada ciência;

[[v54-6-21]]

^<<v54-6-21,21>>^ a qual professando-a alguns, se desviaram da fé. A graça seja convosco.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]