include::./index.adoc[]

[[v54-3-0]]
=== 1 Timóteo, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v54-3-1]]

^<<v54-3-1,1>>^ Fiel é esta palavra: Se alguém aspira ao episcopado, excelente obra deseja.

[[v54-3-2]]

^<<v54-3-2,2>>^ É necessário, pois, que o bispo seja irrepreensível, marido de uma só mulher, temperante, sóbrio, ordeiro, hospitaleiro, apto para ensinar;

[[v54-3-3]]

^<<v54-3-3,3>>^ não dado ao vinho, não espancador, mas moderado, inimigo de contendas, não ganancioso;

[[v54-3-4]]

^<<v54-3-4,4>>^ que governe bem a sua própria casa, tendo seus filhos em sujeição, com todo o respeito

[[v54-3-5]]

^<<v54-3-5,5>>^ &#123;pois, se alguém não sabe governar a sua própria casa, como cuidará da igreja de Deus?&#125;;

[[v54-3-6]]

^<<v54-3-6,6>>^ não neófito, para que não se ensoberbeça e venha a cair na condenação do Diabo.

[[v54-3-7]]

^<<v54-3-7,7>>^ Também é necessário que tenha bom testemunho dos que estão de fora, para que não caia em opróbrio, e no laço do Diabo.

[[v54-3-8]]

^<<v54-3-8,8>>^ Da mesma forma os diáconos sejam sérios, não de língua dobre, não dados a muito vinho, não cobiçosos de torpe ganância,

[[v54-3-9]]

^<<v54-3-9,9>>^ guardando o mistério da fé numa consciência pura.

[[v54-3-10]]

^<<v54-3-10,10>>^ E também estes sejam primeiro provados, depois exercitem o diaconato, se forem irrepreensíveis.

[[v54-3-11]]

^<<v54-3-11,11>>^ Da mesma sorte as mulheres sejam sérias, não maldizentes, temperantes, e fiéis em tudo.

[[v54-3-12]]

^<<v54-3-12,12>>^ Os diáconos sejam maridos de uma só mulher, e governem bem a seus filhos e suas próprias casas.

[[v54-3-13]]

^<<v54-3-13,13>>^ Porque os que servirem bem como diáconos, adquirirão para si um lugar honroso e muita confiança na fé que há em Cristo Jesus.

[[v54-3-14]]

^<<v54-3-14,14>>^ Escrevo-te estas coisas, embora esperando ir ver-te em breve,

[[v54-3-15]]

^<<v54-3-15,15>>^ para que, no caso de eu tardar, saibas como se deve proceder na casa de Deus, a qual é a igreja do Deus vivo, coluna e esteio da verdade.

[[v54-3-16]]

^<<v54-3-16,16>>^ E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne, foi justificado em espírito, visto dos anjos, pregado entre os gentios, crido no mundo, e recebido acima na glória.

'''

xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[Próximo Capítulo &#62;]