include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v54-5-1]]

^<<v54-5-1,1>>^ Não repreendas asperamente a um velho, mas admoesta-o como a um pai; aos moços, como a irmãos;

[[v54-5-2]]

^<<v54-5-2,2>>^ às mulheres idosas, como a mães; às moças, como a irmãs, com toda a pureza.

[[v54-5-3]]

^<<v54-5-3,3>>^ Honra as viúvas que são verdadeiramente viúvas.

[[v54-5-4]]

^<<v54-5-4,4>>^ Mas, se alguma viúva tiver filhos, ou netos, aprendam eles primeiro a exercer piedade para com a sua própria família, e a recompensar seus progenitores; porque isto é agradável a Deus.

[[v54-5-5]]

^<<v54-5-5,5>>^ Ora, a que é verdadeiramente viúva e desamparada espera em Deus, e persevera de noite e de dia em súplicas e orações;

[[v54-5-6]]

^<<v54-5-6,6>>^ mas a que vive em prazeres, embora viva, está morta.

[[v54-5-7]]

^<<v54-5-7,7>>^ Manda, pois, estas coisas, para que elas sejam irrepreensíveis.

[[v54-5-8]]

^<<v54-5-8,8>>^ Mas, se alguém não cuida dos seus, e especialmente dos da sua família, tem negado a fé, e é pior que um incrédulo.

[[v54-5-9]]

^<<v54-5-9,9>>^ Não seja inscrita como viúva nenhuma que tenha menos de sessenta anos, e só a que tenha sido mulher de um só marido,

[[v54-5-10]]

^<<v54-5-10,10>>^ aprovada com testemunho de boas obras, se criou filhos, se exercitou hospitalidade, se lavou os pés aos santos, se socorreu os atribulados, se praticou toda sorte de boas obras.

[[v54-5-11]]

^<<v54-5-11,11>>^ Mas rejeita as viúvas mais novas, porque, quando se tornam levianas contra Cristo, querem casar-se;

[[v54-5-12]]

^<<v54-5-12,12>>^ tendo já a sua condenação por haverem violado a primeira fé;

[[v54-5-13]]

^<<v54-5-13,13>>^ e, além disto, aprendem também a ser ociosas, andando de casa em casa; e não somente ociosas, mas também faladeiras e intrigantes, falando o que não convém.

[[v54-5-14]]

^<<v54-5-14,14>>^ Quero pois que as mais novas se casem, tenham filhos, dirijam a sua casa, e não dêem ocasião ao adversário de maldizer;

[[v54-5-15]]

^<<v54-5-15,15>>^ porque já algumas se desviaram, indo após Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma mulher crente tem viúvas, socorra-as, e não se sobrecarregue a igreja, para que esta possa socorrer as que são verdadeiramente viúvas.

[[v54-5-17]]

^<<v54-5-17,17>>^ Os anciãos que governam bem sejam tidos por dignos de duplicada honra, especialmente os que labutam na pregação e no ensino.

[[v54-5-18]]

^<<v54-5-18,18>>^ Porque diz a Escritura: Não atarás a boca ao boi quando debulha. E: Digno é o trabalhador do seu salário.

[[v54-5-19]]

^<<v54-5-19,19>>^ Não aceites acusação contra um ancião, senão com duas ou três testemunhas.

[[v54-5-20]]

^<<v54-5-20,20>>^ Aos que vivem no pecado, repreende-os na presença de todos, para que também os outros tenham temor.

[[v54-5-21]]

^<<v54-5-21,21>>^ Conjuro-te diante de Deus, e de Cristo Jesus, e dos anjos eleitos, que sem prevenção guardes estas coisas, nada fazendo com parcialidade.

[[v54-5-22]]

^<<v54-5-22,22>>^ A ninguém imponhas precipitadamente as mãos, nem participes dos pecados alheios; conserva-te a ti mesmo puro.

[[v54-5-23]]

^<<v54-5-23,23>>^ Não bebas mais água só, mas usa um pouco de vinho, por causa do teu estômago e das tuas freqüentes enfermidades.

[[v54-5-24]]

^<<v54-5-24,24>>^ Os pecados de alguns homens são manifestos antes de entrarem em juízo, enquanto os de outros descobrem-se depois.

[[v54-5-25]]

^<<v54-5-25,25>>^ Da mesma forma também as boas obras são manifestas antecipadamente; e as que não o são não podem ficar ocultas.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]