include::./index.adoc[]

[[v54-1-0]]
=== 1 Timóteo, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v54-1-1]]

^<<v54-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, segundo o mandado de Deus, nosso Salvador, e de Cristo Jesus, esperança nossa.

[[v54-1-2]]

^<<v54-1-2,2>>^ a Timóteo, meu verdadeiro filho na fé: graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus, nosso Senhor.

[[v54-1-3]]

^<<v54-1-3,3>>^ Como te roguei, quando partia para a Macedônia, que ficasse em Éfeso, para advertires a alguns que não ensinassem doutrina diversa,

[[v54-1-4]]

^<<v54-1-4,4>>^ nem se preocupassem com fábulas ou genealogias intermináveis, pois que produzem antes discussões que edificação para com Deus, que se funda na fé...

[[v54-1-5]]

^<<v54-1-5,5>>^ Mas o fim desta admoestação é o amor que procede de um coração puro, de uma boa consciência, e de uma fé não fingida;

[[v54-1-6]]

^<<v54-1-6,6>>^ das quais coisas alguns se desviaram, e se entregaram a discursos vãos,

[[v54-1-7]]

^<<v54-1-7,7>>^ querendo ser doutores da lei, embora não entendam nem o que dizem nem o que com tanta confiança afirmam.

[[v54-1-8]]

^<<v54-1-8,8>>^ Sabemos, porém, que a lei é boa, se alguém dela usar legitimamente,

[[v54-1-9]]

^<<v54-1-9,9>>^ reconhecendo que a lei não é feita para o justo, mas para os transgressores e insubordinados, os irreverentes e pecadores, os ímpios e profanos, para os parricidas, matricidas e homicidas,

[[v54-1-10]]

^<<v54-1-10,10>>^ para os devassos, os sodomitas, os roubadores de homens, os mentirosos, os perjuros, e para tudo que for contrário à sã doutrina,

[[v54-1-11]]

^<<v54-1-11,11>>^ segundo o evangelho da glória do Deus bendito, que me foi confiado.

[[v54-1-12]]

^<<v54-1-12,12>>^ Dou graças àquele que me fortaleceu, a Cristo Jesus nosso Senhor, porque me julgou fiel, pondo-me no seu ministério,

[[v54-1-13]]

^<<v54-1-13,13>>^ ainda que outrora eu era blasfemador, perseguidor, e injuriador; mas alcancei misericórdia, porque o fiz por ignorância, na incredulidade;

[[v54-1-14]]

^<<v54-1-14,14>>^ e a graça de nosso Senhor superabundou com a fé e o amor que há em Cristo Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ Fiel é esta palavra e digna de toda a aceitação; que Cristo Jesus veio ao mundo para salvar os pecadores, dos quais sou eu o principal;

[[v54-1-16]]

^<<v54-1-16,16>>^ mas por isso alcancei misericórdia, para que em mim, o principal, Cristo Jesus mostrasse toda a sua longanimidade, a fim de que eu servisse de exemplo aos que haviam de crer nele para a vida eterna.

[[v54-1-17]]

^<<v54-1-17,17>>^ Ora, ao Rei dos séculos, imortal, invisível, ao único Deus, seja honra e glória para todo o sempre. Amém.

[[v54-1-18]]

^<<v54-1-18,18>>^ Esta admoestação te dirijo, filho Timóteo, que segundo as profecias que houve acerca de ti, por elas pelejes a boa peleja,

[[v54-1-19]]

^<<v54-1-19,19>>^ conservando a fé, e uma boa consciência, a qual alguns havendo rejeitado, naufragando no tocante à fé;

[[v54-1-20]]

^<<v54-1-20,20>>^ e entre esses Himeneu e Alexandre, os quais entreguei a Satanás, para que aprendam a não blasfemar.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[Próximo Capítulo &#62;]