include::./index.adoc[]

[[v44-15-0]]
=== Atos, 15
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-15-1]]

^<<v44-15-1,1>>^ Então alguns que tinham descido da Judéia ensinavam aos irmãos: Se não vos circuncidardes, segundo o rito de Moisés, não podeis ser salvos.

[[v44-15-2]]

^<<v44-15-2,2>>^ Tendo Paulo e Barnabé contenda e não pequena discussão com eles, os irmãos resolveram que Paulo e Barnabé e mais alguns dentre eles subissem a Jerusalém, aos apóstolos e aos anciãos, por causa desta questão.

[[v44-15-3]]

^<<v44-15-3,3>>^ Eles, pois, sendo acompanhados pela igreja por um trecho do caminho, passavam pela Fenícia e por Samária, contando a conversão dos gentios; e davam grande alegria a todos os irmãos.

[[v44-15-4]]

^<<v44-15-4,4>>^ E, quando chegaram a Jerusalém, foram recebidos pela igreja e pelos apóstolos e anciãos, e relataram tudo quanto Deus fizera por meio deles.

[[v44-15-5]]

^<<v44-15-5,5>>^ Mas alguns da seita dos fariseus, que tinham crido, levantaram-se dizendo que era necessário circuncidá-los e mandar-lhes observar a lei de Moisés.

[[v44-15-6]]

^<<v44-15-6,6>>^ Congregaram-se pois os apóstolos e os anciãos para considerar este assunto.

[[v44-15-7]]

^<<v44-15-7,7>>^ E, havendo grande discussão, levantou-se Pedro e disse-lhes: Irmãos, bem sabeis que já há muito tempo Deus me elegeu dentre vós, para que os gentios ouvissem da minha boca a palavra do evangelho e cressem.

[[v44-15-8]]

^<<v44-15-8,8>>^ E Deus, que conhece os corações, testemunhou a favor deles, dando-lhes o Espírito Santo, assim como a nós;

[[v44-15-9]]

^<<v44-15-9,9>>^ e não fez distinção alguma entre eles e nós, purificando os seus corações pela fé.

[[v44-15-10]]

^<<v44-15-10,10>>^ Agora, pois, por que tentais a Deus, pondo sobre a cerviz dos discípulos um jugo que nem nossos pais nem nós pudemos suportar?

[[v44-15-11]]

^<<v44-15-11,11>>^ Mas cremos que somos salvos pela graça do Senhor Jesus, do mesmo modo que eles também.

[[v44-15-12]]

^<<v44-15-12,12>>^ Então toda a multidão se calou e escutava a Barnabé e a Paulo, que contavam quantos sinais e prodígios Deus havia feito por meio deles entre os gentios.

[[v44-15-13]]

^<<v44-15-13,13>>^ Depois que se calaram, Tiago, tomando a palavra, disse: Irmãos, ouvi-me:

[[v44-15-14]]

^<<v44-15-14,14>>^ Simão relatou como primeiramente Deus visitou os gentios para tomar dentre eles um povo para o seu Nome.

[[v44-15-15]]

^<<v44-15-15,15>>^ E com isto concordam as palavras dos profetas; como está escrito:

[[v44-15-16]]

^<<v44-15-16,16>>^ Depois disto voltarei, e reedificarei o tabernáculo de Davi, que está caído; reedificarei as suas ruínas, e tornarei a levantá-lo;

[[v44-15-17]]

^<<v44-15-17,17>>^ para que o resto dos homens busque ao Senhor, sim, todos os gentios, sobre os quais é invocado o meu nome,

[[v44-15-18]]

^<<v44-15-18,18>>^ diz o Senhor que faz estas coisas, que são conhecidas desde a antiguidade.

[[v44-15-19]]

^<<v44-15-19,19>>^ Por isso, julgo que não se deve perturbar aqueles, dentre os gentios, que se convertem a Deus,

[[v44-15-20]]

^<<v44-15-20,20>>^ mas escrever-lhes que se abstenham das contaminações dos ídolos, da prostituição, do que é sufocado e do sangue.

[[v44-15-21]]

^<<v44-15-21,21>>^ Porque Moisés, desde tempos antigos, tem em cada cidade homens que o preguem, e cada sábado é lido nas sinagogas.

[[v44-15-22]]

^<<v44-15-22,22>>^ Então pareceu bem aos apóstolos e aos anciãos com toda a igreja escolher homens dentre eles e enviá-los a Antioquia com Paulo e Barnabé, a saber: Judas, chamado Barsabás, e Silas, homens influentes entre os irmãos.

[[v44-15-23]]

^<<v44-15-23,23>>^ E por intermédio deles escreveram o seguinte: Os apóstolos e os anciãos, irmãos, aos irmãos dentre os gentios em Antioquia, na Síria e na Cicília, saúde.

[[v44-15-24]]

^<<v44-15-24,24>>^ Portanto ouvimos que alguns dentre nós, aos quais nada mandamos, vos têm perturbado com palavras, confundindo as vossas almas,

[[v44-15-25]]

^<<v44-15-25,25>>^ pareceu-nos bem, tendo chegado a um acordo, escolher alguns homens e enviá-los com os nossos amados Barnabé e Paulo,

[[v44-15-26]]

^<<v44-15-26,26>>^ homens que têm exposto as suas vidas pelo nome de nosso Senhor Jesus Cristo.

[[v44-15-27]]

^<<v44-15-27,27>>^ Enviamos portanto Judas e Silas, os quais também por palavra vos anunciarão as mesmas coisas.

[[v44-15-28]]

^<<v44-15-28,28>>^ Porque pareceu bem ao Espírito Santo e a nós não vos impor maior encargo além destas coisas necessárias:

[[v44-15-29]]

^<<v44-15-29,29>>^ Que vos abstenhais das coisas sacrificadas aos ídolos, e do sangue, e da carne sufocada, e da prostituição; e destas coisas fareis bem de vos guardar. Bem vos vá.

[[v44-15-30]]

^<<v44-15-30,30>>^ Então eles, tendo-se despedido, desceram a Antioquia e, havendo reunido a assembléia, entregaram a carta.

[[v44-15-31]]

^<<v44-15-31,31>>^ E, quando a leram, alegraram-se pela consolação.

[[v44-15-32]]

^<<v44-15-32,32>>^ Depois Judas e Silas, que também eram profetas, exortaram os irmãos com muitas palavras e os fortaleceram.

[[v44-15-33]]

^<<v44-15-33,33>>^ E, tendo-se demorado ali por algum tempo, foram pelos irmãos despedidos em paz, de volta aos que os haviam mandado.

[[v44-15-34]]

^<<v44-15-34,34>>^ &#123;Mas pareceu bem a Silas ficar ali.&#125;

[[v44-15-35]]

^<<v44-15-35,35>>^ Mas Paulo e Barnabé demoraram-se em Antioquia, ensinando e pregando com muitos outros a palavra do Senhor.

[[v44-15-36]]

^<<v44-15-36,36>>^ Decorridos alguns dias, disse Paulo a Barnabé: Tornemos a visitar os irmãos por todas as cidades em que temos anunciado a palavra do Senhor, para ver como vão.

[[v44-15-37]]

^<<v44-15-37,37>>^ Ora, Barnabé queria que levassem também a João, chamado Marcos.

[[v44-15-38]]

^<<v44-15-38,38>>^ Mas a Paulo não parecia razoável que tomassem consigo aquele que desde a Panfília se tinha apartado deles e não os tinha acompanhado no trabalho.

[[v44-15-39]]

^<<v44-15-39,39>>^ E houve entre eles tal desavença que se separaram um do outro, e Barnabé, levando consigo a Marcos, navegou para Chipre.

[[v44-15-40]]

^<<v44-15-40,40>>^ Mas Paulo, tendo escolhido a Silas, partiu encomendado pelos irmãos à graça do Senhor.

[[v44-15-41]]

^<<v44-15-41,41>>^ E passou pela Síria e Cilícia, fortalecendo as igrejas.

'''

xref:044-atos/044-atos-014.adoc#v44-14-0[&#60; Capítulo Anterior] | <<v44-15-0,Topo>> | xref:044-atos/044-atos-016.adoc#v44-16-0[Próximo Capítulo &#62;]