include::./index.adoc[]

[[v44-6-0]]
=== Atos, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-6-1]]

^<<v44-6-1,1>>^ Ora, naqueles dias, crescendo o número dos discípulos, houve uma murmuração dos helenistas contra os hebreus, porque as viúvas daqueles estavam sendo esquecidas na distribuição diária.

[[v44-6-2]]

^<<v44-6-2,2>>^ E os doze, convocando a multidão dos discípulos, disseram: Não é razoável que nós deixemos a palavra de Deus e sirvamos às mesas.

[[v44-6-3]]

^<<v44-6-3,3>>^ Escolhei, pois, irmãos, dentre vós, sete homens de boa reputação, cheios do Espírito Santo e de sabedoria, aos quais encarreguemos deste serviço.

[[v44-6-4]]

^<<v44-6-4,4>>^ Mas nós perseveraremos na oração e no ministério da palavra.

[[v44-6-5]]

^<<v44-6-5,5>>^ O parecer agradou a todos, e elegeram a Estevão, homem cheio de fé e do Espírito Santo, Filipe, Prócoro, Nicanor, Timão, Pármenas, e Nicolau, prosélito de Antioquia,

[[v44-6-6]]

^<<v44-6-6,6>>^ e os apresentaram perante os apóstolos; estes, tendo orado, lhes impuseram as mãos.

[[v44-6-7]]

^<<v44-6-7,7>>^ E divulgava-se a palavra de Deus, de sorte que se multiplicava muito o número dos discípulos em Jerusalém e muitos sacerdotes obedeciam à fé.

[[v44-6-8]]

^<<v44-6-8,8>>^ Ora, Estêvão, cheio de graça e poder, fazia prodígios e grandes sinais entre o povo.

[[v44-6-9]]

^<<v44-6-9,9>>^ Levantaram-se, porém, alguns que eram da sinagoga chamada dos libertos, dos cireneus, dos alexandrinos, dos da Cilícia e da Ásia, e disputavam com Estêvão;

[[v44-6-10]]

^<<v44-6-10,10>>^ e não podiam resistir à sabedoria e ao Espírito com que falava.

[[v44-6-11]]

^<<v44-6-11,11>>^ Então subornaram uns homens para que dissessem: Temo-lo ouvido proferir palavras blasfemas contra Moisés e contra Deus.

[[v44-6-12]]

^<<v44-6-12,12>>^ Assim excitaram o povo, os anciãos, e os escribas; e investindo contra ele, o arrebataram e o levaram ao sinédrio;

[[v44-6-13]]

^<<v44-6-13,13>>^ e apresentaram falsas testemunhas que diziam: Este homem não cessa de proferir palavras contra este santo lugar e contra a lei;

[[v44-6-14]]

^<<v44-6-14,14>>^ porque nós o temos ouvido dizer que esse Jesus, o nazareno, há de destruir este lugar e mudar os costumes que Moisés nos transmitiu.

[[v44-6-15]]

^<<v44-6-15,15>>^ Então todos os que estavam assentados no sinédrio, fitando os olhos nele, viram o seu rosto como de um anjo.

'''

xref:044-atos/044-atos-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-atos/044-atos-007.adoc#v44-7-0[Próximo Capítulo &#62;]