include::./index.adoc[]

[[v44-3-0]]
=== Atos, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-3-1]]

^<<v44-3-1,1>>^ Pedro e João subiam ao templo à hora da oração, a nona.

[[v44-3-2]]

^<<v44-3-2,2>>^ E, era carregado um homem, coxo de nascença, o qual todos os dias punham à porta do templo, chamada Formosa, para pedir esmolas aos que entravam.

[[v44-3-3]]

^<<v44-3-3,3>>^ Ora, vendo ele a Pedro e João, que iam entrando no templo, pediu que lhe dessem uma esmola.

[[v44-3-4]]

^<<v44-3-4,4>>^ E Pedro, com João, fitando os olhos nele, disse: Olha para nós.

[[v44-3-5]]

^<<v44-3-5,5>>^ E ele os olhava atentamente, esperando receber deles alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ Disse-lhe Pedro: Não tenho prata nem ouro; mas o que tenho, isso te dou; em nome de Jesus Cristo, o nazareno, anda.

[[v44-3-7]]

^<<v44-3-7,7>>^ Nisso, tomando-o pela mão direita, o levantou; imediatamente os seus pés e artelhos se firmaram

[[v44-3-8]]

^<<v44-3-8,8>>^ e, dando ele um salto, pôs-se em pé. Começou a andar e entrou com eles no templo, andando, saltando e louvando a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ Todo o povo, ao vê-lo andar e louvar a Deus,

[[v44-3-10]]

^<<v44-3-10,10>>^ reconhecia-o como o mesmo que estivera sentado a pedir esmola à Porta Formosa do templo; e todos ficaram cheios de pasmo e assombro, pelo que lhe acontecera.

[[v44-3-11]]

^<<v44-3-11,11>>^ Apegando-se o homem a Pedro e João, todo o povo correu atônito para junto deles, ao pórtico chamado de Salomão.

[[v44-3-12]]

^<<v44-3-12,12>>^ Pedro, vendo isto, disse ao povo: Varões israelitas, por que vos admirais deste homem? Ou, por que fitais os olhos em nós, como se por nosso próprio poder ou piedade o tivéssemos feito andar?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus de Abraão, de Isaque e de Jacó, o Deus de nossos pais, glorificou a seu Servo Jesus, a quem vós entregastes e perante a face de Pilatos negastes, quando este havia resolvido soltá-lo.

[[v44-3-14]]

^<<v44-3-14,14>>^ Mas vós negastes o Santo e Justo, e pedistes que se vos desse um homicida;

[[v44-3-15]]

^<<v44-3-15,15>>^ e matastes o Autor da vida, a quem Deus ressuscitou dentre os mortos, do que nós somos testemunhas.

[[v44-3-16]]

^<<v44-3-16,16>>^ E pela fé em seu nome fez o seu nome fortalecer a este homem que vedes e conheceis; sim, a fé, que vem por ele, deu a este, na presença de todos vós, esta perfeita saúde.

[[v44-3-17]]

^<<v44-3-17,17>>^ Agora, irmãos, eu sei que o fizestes por ignorância, como também as vossas autoridades.

[[v44-3-18]]

^<<v44-3-18,18>>^ Mas Deus assim cumpriu o que já dantes pela boca de todos os seus profetas havia anunciado que o seu Cristo havia de padecer.

[[v44-3-19]]

^<<v44-3-19,19>>^ Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, de sorte que venham os tempos de refrigério, da presença do Senhor,

[[v44-3-20]]

^<<v44-3-20,20>>^ e envie ele o Cristo, que já dantes vos foi indicado, Jesus,

[[v44-3-21]]

^<<v44-3-21,21>>^ ao qual convém que o céu receba até os tempos da restauração de todas as coisas, das quais Deus falou pela boca dos seus santos profetas, desde o princípio.

[[v44-3-22]]

^<<v44-3-22,22>>^ Pois Moisés disse: Suscitar-vos-á o Senhor vosso Deus, dentre vossos irmãos, um profeta semelhante a mim; a ele ouvireis em tudo quanto vos disser.

[[v44-3-23]]

^<<v44-3-23,23>>^ E acontecerá que toda alma que não ouvir a esse profeta, será exterminada dentre o povo.

[[v44-3-24]]

^<<v44-3-24,24>>^ E todos os profetas, desde Samuel e os que sucederam, quantos falaram, também anunciaram estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ Vós sois os filhos dos profetas e do pacto que Deus fez com vossos pais, dizendo a Abraão: Na tua descendência serão abençoadas todas as famílias da terra.

[[v44-3-26]]

^<<v44-3-26,26>>^ Deus suscitou a seu Servo, e a vós primeiramente vo-lo enviou para que vos abençoasse, desviando-vos, a cada um, das vossas maldades.

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]