include::./index.adoc[]

[[v44-24-0]]
=== Atos, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-24-1]]

^<<v44-24-1,1>>^ Cinco dias depois o sumo sacerdote Ananias desceu com alguns anciãos e um certo Tertulo, orador, os quais fizeram, perante o governador, queixa contra Paulo.

[[v44-24-2]]

^<<v44-24-2,2>>^ Sendo este chamado, Tertulo começou a acusá-lo, dizendo:

[[v44-24-3]]

^<<v44-24-3,3>>^ Visto que por ti gozamos de muita paz e por tua providência são continuamente feitas reformas nesta nação, em tudo e em todo lugar reconhecemo-lo com toda a gratidão, ó excelentíssimo Félix.

[[v44-24-4]]

^<<v44-24-4,4>>^ Mas, para que não te detenha muito rogo-te que, conforme a tua eqüidade, nos ouças por um momento.

[[v44-24-5]]

^<<v44-24-5,5>>^ Temos achado que este homem é uma peste, e promotor de sedições entre todos os judeus, por todo o mundo, e chefe da seita dos nazarenos;

[[v44-24-6]]

^<<v44-24-6,6>>^ o qual tentou profanar o templo; e nós o prendemos, e conforme a nossa lei o quisemos julgar.

[[v44-24-7]]

^<<v44-24-7,7>>^ Mas sobrevindo o comandante Lísias no-lo tirou dentre as mãos com grande violência,

[[v44-24-8]]

^<<v44-24-8,8>>^ mandando aos acusadores que viessem a ti; e dele tu mesmo, examinando-o, poderás certificar-te de tudo aquilo de que o acusamos.

[[v44-24-9]]

^<<v44-24-9,9>>^ Os judeus também concordam na acusação, afirmando que estas coisas eram assim.

[[v44-24-10]]

^<<v44-24-10,10>>^ Paulo, tendo-lhe o governador feito sinal que falasse, respondeu: Porquanto sei que há muitos anos és juiz sobre esta nação, com bom ânimo faço a minha defesa,

[[v44-24-11]]

^<<v44-24-11,11>>^ pois bem podes verificar que não há mais de doze dias subi a Jerusalém para adorar,

[[v44-24-12]]

^<<v44-24-12,12>>^ e que não me acharam no templo discutindo com alguém nem amotinando o povo, quer nas sinagogas quer na cidade.

[[v44-24-13]]

^<<v44-24-13,13>>^ Nem te podem provar as coisas de que agora me acusam.

[[v44-24-14]]

^<<v44-24-14,14>>^ Mas confesso-te isto: que, seguindo o caminho a que eles chamam seita, assim sirvo ao Deus de nossos pais, crendo tudo quanto está escrito na lei e nos profetas.

[[v44-24-15]]

^<<v44-24-15,15>>^ Tendo esperança em Deus, como estes mesmos também esperam, de que há de haver ressurreição tanto dos justos como dos injustos.

[[v44-24-16]]

^<<v44-24-16,16>>^ Por isso procuro sempre ter uma consciência sem ofensas diante de Deus e dos homens.

[[v44-24-17]]

^<<v44-24-17,17>>^ Vários anos depois vim trazer à minha nação esmolas e ofertas.

[[v44-24-18]]

^<<v44-24-18,18>>^ Ocupado nestas coisas, me acharam já santificado no templo não em ajuntamento, nem com tumulto, alguns judeus da Ásia,

[[v44-24-19]]

^<<v44-24-19,19>>^ os quais deviam comparecer diante de ti e acusar-me se tivessem alguma coisa contra mim;

[[v44-24-20]]

^<<v44-24-20,20>>^ ou estes mesmos digam que iniqüidade acharam, quando compareci perante o sinédrio,

[[v44-24-21]]

^<<v44-24-21,21>>^ a não ser acerca desta única palavra que, estando no meio deles, bradei: Por causa da ressurreição dos mortos é que hoje estou sendo julgado por vós.

[[v44-24-22]]

^<<v44-24-22,22>>^ Félix, porém, que era bem informado a respeito do Caminho, adiou a questão, dizendo: Quando o comandante Lísias tiver descido, então tomarei inteiro conhecimento da vossa causa.

[[v44-24-23]]

^<<v44-24-23,23>>^ E ordenou ao centurião que Paulo ficasse detido, mas fosse tratado com brandura e que a nenhum dos seus proibisse servi-lo.

[[v44-24-24]]

^<<v44-24-24,24>>^ Alguns dias depois, vindo Félix com sua mulher Drusila, que era judia, mandou chamar a Paulo, e ouviu-o acerca da fé em Cristo Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ E discorrendo ele sobre a justiça, o domínio próprio e o juízo vindouro, Félix ficou atemorizado e respondeu: Por ora vai-te, e quando tiver ocasião favorável, eu te chamarei.

[[v44-24-26]]

^<<v44-24-26,26>>^ Esperava ao mesmo tempo que Paulo lhe desse dinheiro, pelo que o mandava chamar mais freqüentemente e conversava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Mas passados dois anos, teve Félix por sucessor a Pórcio Festo; e querendo Félix agradar aos judeus, deixou a Paulo preso.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]