include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-12-1]]

^<<v44-12-1,1>>^ Por aquele mesmo tempo o rei Herodes estendeu as mãos sobre alguns da igreja, para os maltratar;

[[v44-12-2]]

^<<v44-12-2,2>>^ e matou à espada Tiago, irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ Vendo que isso agradava aos judeus, continuou, mandando prender também a Pedro. &#123;Eram então os dias dos pães ázimos.&#125;

[[v44-12-4]]

^<<v44-12-4,4>>^ E, havendo-o prendido, lançou-o na prisão, entregando-o a quatro grupos de quatro soldados cada um para o guardarem, tencionando apresentá-lo ao povo depois da páscoa.

[[v44-12-5]]

^<<v44-12-5,5>>^ Pedro, pois, estava guardado na prisão; mas a igreja orava com insistência a Deus por ele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Ora quando Herodes estava para apresentá-lo, nessa mesma noite estava Pedro dormindo entre dois soldados, acorrentado com duas cadeias e as sentinelas diante da porta guardavam a prisão.

[[v44-12-7]]

^<<v44-12-7,7>>^ E eis que sobreveio um anjo do Senhor, e uma luz resplandeceu na prisão; e ele, tocando no lado de Pedro, o despertou, dizendo: Levanta-te depressa. E caíram-lhe das mãos as cadeias.

[[v44-12-8]]

^<<v44-12-8,8>>^ Disse-lhe ainda o anjo: Cinge-te e calça as tuas sandálias. E ele o fez. Disse-lhe mais; Cobre-te com a tua capa e segue-me.

[[v44-12-9]]

^<<v44-12-9,9>>^ Pedro, saindo, o seguia, mesmo sem compreender que era real o que se fazia por intermédio de um anjo, julgando que era uma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ Depois de terem passado a primeira e a segunda sentinela, chegaram à porta de ferro, que dá para a cidade, a qual se lhes abriu por si mesma; e tendo saído, passaram uma rua, e logo o anjo se apartou dele.

[[v44-12-11]]

^<<v44-12-11,11>>^ Pedro então, tornando a si, disse: Agora sei verdadeiramente que o Senhor enviou o seu anjo, e me livrou da mão de Herodes e de toda a expectativa do povo dos judeus.

[[v44-12-12]]

^<<v44-12-12,12>>^ Depois de assim refletir foi à casa de Maria, mãe de João, que tem por sobrenome Marcos, onde muitas pessoas estavam reunidas e oravam.

[[v44-12-13]]

^<<v44-12-13,13>>^ Quando ele bateu ao portão do pátio, uma criada chamada Rode saiu a escutar;

[[v44-12-14]]

^<<v44-12-14,14>>^ e, reconhecendo a voz de Pedro, de gozo não abriu o portão, mas, correndo para dentro, anunciou que Pedro estava lá fora.

[[v44-12-15]]

^<<v44-12-15,15>>^ Eles lhe disseram: Estás louca. Ela, porém, assegurava que assim era. Eles então diziam: É o seu anjo.

[[v44-12-16]]

^<<v44-12-16,16>>^ Mas Pedro continuava a bater, e, quando abriram, viram-no e pasmaram.

[[v44-12-17]]

^<<v44-12-17,17>>^ Mas ele, acenando-lhes com a mão para que se calassem, contou-lhes como o Senhor o tirara da prisão, e disse: Anunciai isto a Tiago e aos irmãos. E, saindo, partiu para outro lugar.

[[v44-12-18]]

^<<v44-12-18,18>>^ Logo que amanheceu, houve grande alvoroço entre os soldados sobre o que teria sido feito de Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ E Herodes, tendo-o procurado e não o achando, inquiriu as sentinelas e mandou que fossem justiçadas; e descendo da Judéia para Cesaréia, demorou-se ali.

[[v44-12-20]]

^<<v44-12-20,20>>^ Ora, Herodes estava muito irritado contra os de Tiro e de Sidom; mas estes, vindo de comum acordo ter com ele e obtendo a amizade de Blasto, camareiro do rei, pediam paz, porquanto o seu país se abastecia do país do rei.

[[v44-12-21]]

^<<v44-12-21,21>>^ Num dia designado, Herodes, vestido de trajes reais, sentou-se no trono e dirigia-lhes a palavra.

[[v44-12-22]]

^<<v44-12-22,22>>^ E o povo exclamava: É a voz de um deus, e não de um homem.

[[v44-12-23]]

^<<v44-12-23,23>>^ No mesmo instante o anjo do Senhor o feriu, porque não deu glória a Deus; e, comido de vermes, expirou.

[[v44-12-24]]

^<<v44-12-24,24>>^ E a palavra de Deus crescia e se multiplicava.

[[v44-12-25]]

^<<v44-12-25,25>>^ Barnabé e Saulo, havendo terminado aquele serviço, voltaram de Jerusalém, levando consigo a João, que tem por sobrenome Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]