include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-27-1]]

^<<v44-27-1,1>>^ E, como se determinou que navegássemos para a Itália, entregaram Paulo e alguns outros presos a um centurião por nome Júlio, da corte augusta.

[[v44-27-2]]

^<<v44-27-2,2>>^ E, embarcando em um navio de Adramítio, que estava prestes a navegar em demanda dos portos pela costa da Ásia, fizemo-nos ao mar, estando conosco Aristarco, macedônio de Tessalônica.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte chegamos a Sidom, e Júlio, tratando Paulo com bondade, permitiu-lhe ir ver os amigos e receber deles os cuidados necessários.

[[v44-27-4]]

^<<v44-27-4,4>>^ Partindo dali, fomos navegando a sotavento de Chipre, porque os ventos eram contrários.

[[v44-27-5]]

^<<v44-27-5,5>>^ Tendo atravessado o mar ao longo da Cilícia e Panfília, chegamos a Mirra, na Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Ali o centurião achou um navio de Alexandria que navegava para a Itália, e nos fez embarcar nele.

[[v44-27-7]]

^<<v44-27-7,7>>^ Navegando vagarosamente por muitos dias, e havendo chegado com dificuldade defronte de Cnido, não nos permitindo o vento ir mais adiante, navegamos a sotavento de Creta, à altura de Salmone;

[[v44-27-8]]

^<<v44-27-8,8>>^ e, costeando-a com dificuldade, chegamos a um lugar chamado Bons Portos, perto do qual estava a cidade de Laséia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Havendo decorrido muito tempo e tendo-se tornado perigosa a navegação, porque já havia passado o jejum, Paulo os advertia,

[[v44-27-10]]

^<<v44-27-10,10>>^ dizendo-lhes: Senhores, vejo que a viagem vai ser com avaria e muita perda não só para a carga e o navio, mas também para as nossas vidas.

[[v44-27-11]]

^<<v44-27-11,11>>^ Mas o centurião dava mais crédito ao piloto e ao dono do navio do que às coisas que Paulo dizia.

[[v44-27-12]]

^<<v44-27-12,12>>^ E não sendo o porto muito próprio para invernar, os mais deles foram de parecer que daí se fizessem ao mar para ver se de algum modo podiam chegar a Fênice, um porto de Creta que olha para o nordeste e para o sueste, para ali invernar.

[[v44-27-13]]

^<<v44-27-13,13>>^ Soprando brandamente o vento sul, e supondo eles terem alcançado o que desejavam, levantaram ferro e iam costeando Creta bem de perto.

[[v44-27-14]]

^<<v44-27-14,14>>^ Mas não muito depois desencadeou-se do lado da ilha um tufão de vento chamado euro-aquilão;

[[v44-27-15]]

^<<v44-27-15,15>>^ e, sendo arrebatado o navio e não podendo navegar contra o vento, cedemos à sua força e nos deixávamos levar.

[[v44-27-16]]

^<<v44-27-16,16>>^ Correndo a sota-vento de uma pequena ilha chamada Clauda, somente a custo pudemos segurar o batel,

[[v44-27-17]]

^<<v44-27-17,17>>^ o qual recolheram, usando então os meios disponíveis para cingir o navio; e, temendo que fossem lançados na Sirte, arriaram os aparelhos e se deixavam levar.

[[v44-27-18]]

^<<v44-27-18,18>>^ Como fôssemos violentamente açoitados pela tempestade, no dia seguinte começaram a alijar a carga ao mar.

[[v44-27-19]]

^<<v44-27-19,19>>^ E ao terceiro dia, com as próprias mãos lançaram os aparelhos do navio.

[[v44-27-20]]

^<<v44-27-20,20>>^ Não aparecendo por muitos dia nem sol nem estrelas, e sendo nós ainda batidos por grande tempestade, fugiu-nos afinal toda a esperança de sermos salvos.

[[v44-27-21]]

^<<v44-27-21,21>>^ Havendo eles estado muito tempo sem comer, Paulo, pondo-se em pé no meio deles, disse: Senhores, devíeis ter-me ouvido e não ter partido de Creta, para evitar esta avaria e perda.

[[v44-27-22]]

^<<v44-27-22,22>>^ E agora vos exorto a que tenhais bom ânimo, pois não se perderá vida alguma entre vós, mas somente o navio.

[[v44-27-23]]

^<<v44-27-23,23>>^ Porque esta noite me apareceu um anjo do Deus de quem eu sou e a quem sirvo,

[[v44-27-24]]

^<<v44-27-24,24>>^ dizendo: Não temas, Paulo, importa que compareças perante César, e eis que Deus te deu todos os que navegam contigo.

[[v44-27-25]]

^<<v44-27-25,25>>^ Portanto, senhores, tende bom ânimo; pois creio em Deus que há de suceder assim como me foi dito.

[[v44-27-26]]

^<<v44-27-26,26>>^ Contudo é necessário irmos dar em alguma ilha.

[[v44-27-27]]

^<<v44-27-27,27>>^ Quando chegou a décima quarta noite, sendo nós ainda impelidos pela tempestade no mar de Ádria, pela meia-noite, suspeitaram os marinheiros a proximidade de terra;

[[v44-27-28]]

^<<v44-27-28,28>>^ e lançando a sonda, acharam vinte braças; passando um pouco mais adiante, e tornando a lançar a sonda, acharam quinze braças.

[[v44-27-29]]

^<<v44-27-29,29>>^ Ora, temendo irmos dar em rochedos, lançaram da popa quatro âncoras, e esperaram ansiosos que amanhecesse.

[[v44-27-30]]

^<<v44-27-30,30>>^ Procurando, entrementes, os marinheiros fugir do navio, e tendo arriado o batel ao mar sob pretexto de irem lançar âncoras pela proa,

[[v44-27-31]]

^<<v44-27-31,31>>^ disse Paulo ao centurião e aos soldados: Se estes não ficarem no navio, não podereis salvar-vos.

[[v44-27-32]]

^<<v44-27-32,32>>^ Então os soldados cortaram os cabos do batel e o deixaram cair.

[[v44-27-33]]

^<<v44-27-33,33>>^ Enquanto amanhecia, Paulo rogava a todos que comessem alguma coisa, dizendo: É já hoje o décimo quarto dia que esperais e permaneceis em jejum, não havendo provado coisa alguma.

[[v44-27-34]]

^<<v44-27-34,34>>^ Rogo-vos, portanto, que comais alguma coisa, porque disso depende a vossa segurança; porque nem um cabelo cairá da cabeça de qualquer de vós.

[[v44-27-35]]

^<<v44-27-35,35>>^ E, havendo dito isto, tomou o pão, deu graças a Deus na presença de todos e, partindo-o começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ Então todos cobraram ânimo e se puseram também a comer.

[[v44-27-37]]

^<<v44-27-37,37>>^ Éramos ao todo no navio duzentas e setenta e seis almas.

[[v44-27-38]]

^<<v44-27-38,38>>^ Depois de saciados com a comida, começaram a aliviar o navio, alijando o trigo no mar.

[[v44-27-39]]

^<<v44-27-39,39>>^ Quando amanheceu, não reconheciam a terra; divisavam, porém, uma enseada com uma praia, e consultavam se poderiam nela encalhar o navio.

[[v44-27-40]]

^<<v44-27-40,40>>^ Soltando as âncoras, deixaram-nas no mar, largando ao mesmo tempo as amarras do leme; e, içando ao vento a vela da proa, dirigiram-se para a praia.

[[v44-27-41]]

^<<v44-27-41,41>>^ Dando, porém, num lugar onde duas correntes se encontravam, encalharam o navio; e a proa, encravando-se, ficou imóvel, mas a popa se desfazia com a força das ondas.

[[v44-27-42]]

^<<v44-27-42,42>>^ Então o parecer dos soldados era que matassem os presos para que nenhum deles fugisse, escapando a nado.

[[v44-27-43]]

^<<v44-27-43,43>>^ Mas o centurião, querendo salvar a Paulo, estorvou-lhes este intento; e mandou que os que pudessem nadar fossem os primeiros a lançar-se ao mar e alcançar a terra;

[[v44-27-44]]

^<<v44-27-44,44>>^ e que os demais se salvassem, uns em tábuas e outros em quaisquer destroços do navio. Assim chegaram todos à terra salvos.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]