include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-2-1]]

^<<v44-2-1,1>>^ Ao cumprir-se o dia de Pentecostes, estavam todos reunidos no mesmo lugar.

[[v44-2-2]]

^<<v44-2-2,2>>^ De repente veio do céu um ruído, como que de um vento impetuoso, e encheu toda a casa onde estavam sentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ E lhes apareceram umas línguas como que de fogo, que se distribuíam, e sobre cada um deles pousou uma.

[[v44-2-4]]

^<<v44-2-4,4>>^ E todos ficaram cheios do Espírito Santo, e começaram a falar noutras línguas, conforme o Espírito lhes concedia que falassem.

[[v44-2-5]]

^<<v44-2-5,5>>^ Habitavam então em Jerusalém judeus, homens piedosos, de todas as nações que há debaixo do céu.

[[v44-2-6]]

^<<v44-2-6,6>>^ Ouvindo-se, pois, aquele ruído, ajuntou-se a multidão; e estava confusa, porque cada um os ouvia falar na sua própria língua.

[[v44-2-7]]

^<<v44-2-7,7>>^ E todos pasmavam e se admiravam, dizendo uns aos outros: Pois quê! não são galileus todos esses que estão falando?

[[v44-2-8]]

^<<v44-2-8,8>>^ Como é, pois, que os ouvimos falar cada um na própria língua em que nascemos?

[[v44-2-9]]

^<<v44-2-9,9>>^ Nós, partos, medos, e elamitas; e os que habitamos a Mesopotâmia, a Judéia e a Capadócia, o Ponto e a Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ a Frígia e a Panfília, o Egito e as partes da Líbia próximas a Cirene, e forasteiros romanos, tanto judeus como prosélitos,

[[v44-2-11]]

^<<v44-2-11,11>>^ cretenses e árabes-ouvímo-los em nossas línguas, falar das grandezas de Deus.

[[v44-2-12]]

^<<v44-2-12,12>>^ E todos pasmavam e estavam perplexos, dizendo uns aos outros: Que quer dizer isto?

[[v44-2-13]]

^<<v44-2-13,13>>^ E outros, zombando, diziam: Estão cheios de mosto.

[[v44-2-14]]

^<<v44-2-14,14>>^ Então Pedro, pondo-se em pé com os onze, levantou a voz e disse-lhes: Varões judeus e todos os que habitais em Jerusalém, seja-vos isto notório, e escutai as minhas palavras.

[[v44-2-15]]

^<<v44-2-15,15>>^ Pois estes homens não estão embriagados, como vós pensais, visto que é apenas a terceira hora do dia.

[[v44-2-16]]

^<<v44-2-16,16>>^ Mas isto é o que foi dito pelo profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ E acontecerá nos últimos dias, diz o Senhor, que derramarei do meu Espírito sobre toda a carne; e os vossos filhos e as vossas filhas profetizarão, os vossos mancebos terão visões, os vossos anciãos terão sonhos;

[[v44-2-18]]

^<<v44-2-18,18>>^ e sobre os meus servos e sobre as minhas servas derramarei do meu Espírito naqueles dias, e eles profetizarão.

[[v44-2-19]]

^<<v44-2-19,19>>^ E mostrarei prodígios em cima no céu; e sinais embaixo na terra, sangue, fogo e vapor de fumaça.

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol se converterá em trevas, e a lua em sangue, antes que venha o grande e glorioso dia do Senhor.

[[v44-2-21]]

^<<v44-2-21,21>>^ E acontecerá que todo aquele que invocar o nome do Senhor será salvo.

[[v44-2-22]]

^<<v44-2-22,22>>^ Varões israelitas, escutai estas palavras: A Jesus, o nazareno, varão aprovado por Deus entre vós com milagres, prodígios e sinais, que Deus por ele fez no meio de vós, como vós mesmos bem sabeis;

[[v44-2-23]]

^<<v44-2-23,23>>^ a este, que foi entregue pelo determinado conselho e presciência de Deus, vós matastes, crucificando-o pelas mãos de iníquos;

[[v44-2-24]]

^<<v44-2-24,24>>^ ao qual Deus ressuscitou, rompendo os grilhões da morte, pois não era possível que fosse retido por ela.

[[v44-2-25]]

^<<v44-2-25,25>>^ Porque dele fala Davi: Sempre via diante de mim o Senhor, porque está à minha direita, para que eu não seja abalado;

[[v44-2-26]]

^<<v44-2-26,26>>^ por isso se alegrou o meu coração, e a minha língua exultou; e além disso a minha carne há de repousar em esperança;

[[v44-2-27]]

^<<v44-2-27,27>>^ pois não deixarás a minha alma no inferno, nem permitirás que o teu Santo veja a corrupção;

[[v44-2-28]]

^<<v44-2-28,28>>^ fizeste-me conhecer os caminhos da vida; encher-me-ás de alegria na tua presença.

[[v44-2-29]]

^<<v44-2-29,29>>^ Irmãos, seja-me permitido dizer-vos livremente acerca do patriarca Davi, que ele morreu e foi sepultado, e entre nós está até hoje a sua sepultura.

[[v44-2-30]]

^<<v44-2-30,30>>^ Sendo, pois, ele profeta, e sabendo que Deus lhe havia prometido com juramento que faria sentar sobre o seu trono um dos seus descendentes,

[[v44-2-31]]

^<<v44-2-31,31>>^ prevendo isto, Davi falou da ressurreição de Cristo, que a sua alma não foi deixada no inferno, nem a sua carne viu a corrupção.

[[v44-2-32]]

^<<v44-2-32,32>>^ Ora, a este Jesus, Deus ressuscitou, do que todos nós somos testemunhas.

[[v44-2-33]]

^<<v44-2-33,33>>^ De sorte que, exaltado pela destra de Deus, e tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vós agora vedes e ouvis.

[[v44-2-34]]

^<<v44-2-34,34>>^ Porque Davi não subiu aos céus, mas ele próprio declara: Disse o Senhor ao meu Senhor: Assenta-te à minha direita,

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu ponha os teus inimigos por escabelo de teus pés.

[[v44-2-36]]

^<<v44-2-36,36>>^ Saiba pois com certeza toda a casa de Israel que a esse mesmo Jesus, a quem vós crucificastes, Deus o fez Senhor e Cristo.

[[v44-2-37]]

^<<v44-2-37,37>>^ E, ouvindo eles isto, compungiram-se em seu coração, e perguntaram a Pedro e aos demais apóstolos: Que faremos, irmãos?

[[v44-2-38]]

^<<v44-2-38,38>>^ Pedro então lhes respondeu: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo, para remissão de vossos pecados; e recebereis o dom do Espírito Santo.

[[v44-2-39]]

^<<v44-2-39,39>>^ Porque a promessa vos pertence a vós, a vossos filhos, e a todos os que estão longe: a quantos o Senhor nosso Deus chamar.

[[v44-2-40]]

^<<v44-2-40,40>>^ E com muitas outras palavras dava testemunho, e os exortava, dizendo: salvai-vos desta geração perversa.

[[v44-2-41]]

^<<v44-2-41,41>>^ De sorte que foram batizados os que receberam a sua palavra; e naquele dia agregaram-se quase três mil almas;

[[v44-2-42]]

^<<v44-2-42,42>>^ e perseveravam na doutrina dos apóstolos e na comunhão, no partir do pão e nas orações.

[[v44-2-43]]

^<<v44-2-43,43>>^ Em cada alma havia temor, e muitos prodígios e sinais eram feitos pelos apóstolos.

[[v44-2-44]]

^<<v44-2-44,44>>^ Todos os que criam estavam unidos e tinham tudo em comum.

[[v44-2-45]]

^<<v44-2-45,45>>^ E vendiam suas propriedades e bens e os repartiam por todos, segundo a necessidade de cada um.

[[v44-2-46]]

^<<v44-2-46,46>>^ E, perseverando unânimes todos os dias no templo, e partindo o pão em casa, comiam com alegria e singeleza de coração,

[[v44-2-47]]

^<<v44-2-47,47>>^ louvando a Deus, e caindo na graça de todo o povo. E cada dia acrescentava-lhes o Senhor os que iam sendo salvos.

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]