include::./index.adoc[]

[[v44-4-0]]
=== Atos, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-4-1]]

^<<v44-4-1,1>>^ Enquanto eles estavam falando ao povo, sobrevieram-lhes os sacerdotes, o capitão do templo e os saduceus,

[[v44-4-2]]

^<<v44-4-2,2>>^ doendo-se muito de que eles ensinassem o povo, e anunciassem em Jesus a ressurreição dentre os mortos,

[[v44-4-3]]

^<<v44-4-3,3>>^ deitaram mão neles, e os encerraram na prisão até o dia seguinte; pois era já tarde.

[[v44-4-4]]

^<<v44-4-4,4>>^ Muitos, porém, dos que ouviram a palavra, creram, e se elevou o número dos homens a quase cinco mil.

[[v44-4-5]]

^<<v44-4-5,5>>^ No dia seguinte, reuniram-se em Jerusalém as autoridades, os anciãos, os escribas,

[[v44-4-6]]

^<<v44-4-6,6>>^ e Anás, o sumo sacerdote, e Caifás, João, Alexandre, e todos quantos eram da linhagem do sumo sacerdote.

[[v44-4-7]]

^<<v44-4-7,7>>^ E, pondo-os no meio deles, perguntaram: Com que poder ou em nome de quem fizestes vós isto?

[[v44-4-8]]

^<<v44-4-8,8>>^ Então Pedro, cheio do Espírito Santo, lhes disse: Autoridades do povo e vós, anciãos,

[[v44-4-9]]

^<<v44-4-9,9>>^ se nós hoje somos inquiridos acerca do benefício feito a um enfermo, e do modo como foi curado,

[[v44-4-10]]

^<<v44-4-10,10>>^ seja conhecido de vós todos, e de todo o povo de Israel, que em nome de Jesus Cristo, o nazareno, aquele a quem vós crucificastes e a quem Deus ressuscitou dentre os mortos, nesse nome está este aqui, são diante de vós.

[[v44-4-11]]

^<<v44-4-11,11>>^ Ele é a pedra que foi rejeitada por vós, os edificadores, a qual foi posta como pedra angular.

[[v44-4-12]]

^<<v44-4-12,12>>^ E em nenhum outro há salvação; porque debaixo do céu nenhum outro nome há, dado entre os homens, em que devamos ser salvos.

[[v44-4-13]]

^<<v44-4-13,13>>^ Então eles, vendo a intrepidez de Pedro e João, e tendo percebido que eram homens iletrados e indoutos, se admiravam; e reconheciam que haviam estado com Jesus.

[[v44-4-14]]

^<<v44-4-14,14>>^ E vendo em pé com eles o homem que fora curado, nada tinham que dizer em contrário.

[[v44-4-15]]

^<<v44-4-15,15>>^ Todavia, mandando-os sair do sinédrio, conferenciaram entre si,

[[v44-4-16]]

^<<v44-4-16,16>>^ dizendo: Que havemos de fazer a estes homens? porque a todos os que habitam em Jerusalém é manifesto que por eles foi feito um sinal notório, e não o podemos negar.

[[v44-4-17]]

^<<v44-4-17,17>>^ Mas, para que não se divulgue mais entre o povo, ameacemo-los para que de ora em diante não falem neste nome a homem algum.

[[v44-4-18]]

^<<v44-4-18,18>>^ E, chamando-os, ordenaram-lhes que absolutamente não falassem nem ensinassem em nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Mas Pedro e João, respondendo, lhes disseram: Julgai vós se é justo diante de Deus ouvir-nos antes a vós do que a Deus;

[[v44-4-20]]

^<<v44-4-20,20>>^ pois nós não podemos deixar de falar das coisas que temos visto e ouvido.

[[v44-4-21]]

^<<v44-4-21,21>>^ Mas eles ainda os ameaçaram mais, e, não achando motivo para os castigar, soltaram-nos, por causa do povo; porque todos glorificavam a Deus pelo que acontecera;

[[v44-4-22]]

^<<v44-4-22,22>>^ pois tinha mais de quarenta anos o homem em quem se operara esta cura milagrosa.

[[v44-4-23]]

^<<v44-4-23,23>>^ E soltos eles, foram para os seus, e contaram tudo o que lhes haviam dito os principais sacerdotes e os anciãos.

[[v44-4-24]]

^<<v44-4-24,24>>^ Ao ouvirem isto, levantaram unanimemente a voz a Deus e disseram: Senhor, tu que fizeste o céu, a terra, o mar, e tudo o que neles há;

[[v44-4-25]]

^<<v44-4-25,25>>^ que pelo Espírito Santo, por boca de nosso pai Davi, teu servo, disseste: Por que se enfureceram os gentios, e os povos imaginaram coisas vãs?

[[v44-4-26]]

^<<v44-4-26,26>>^ Levantaram-se os reis da terra, e as autoridades ajuntaram-se à uma, contra o Senhor e contra o seu Ungido.

[[v44-4-27]]

^<<v44-4-27,27>>^ Porque verdadeiramente se ajuntaram, nesta cidade, contra o teu santo Servo Jesus, ao qual ungiste, não só Herodes, mas também Pôncio Pilatos com os gentios e os povos de Israel;

[[v44-4-28]]

^<<v44-4-28,28>>^ para fazerem tudo o que a tua mão e o teu conselho predeterminaram que se fizesse.

[[v44-4-29]]

^<<v44-4-29,29>>^ Agora pois, ó Senhor, olha para as suas ameaças, e concede aos teus servos que falem com toda a intrepidez a tua palavra,

[[v44-4-30]]

^<<v44-4-30,30>>^ enquanto estendes a mão para curar e para que se façam sinais e prodígios pelo nome de teu santo Servo Jesus.

[[v44-4-31]]

^<<v44-4-31,31>>^ E, tendo eles orado, tremeu o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo, e anunciavam com intrepidez a palavra de Deus.

[[v44-4-32]]

^<<v44-4-32,32>>^ Da multidão dos que criam, era um só o coração e uma só a alma, e ninguém dizia que coisa alguma das que possuía era sua própria, mas todas as coisas lhes eram comuns.

[[v44-4-33]]

^<<v44-4-33,33>>^ Com grande poder os apóstolos davam testemunho da ressurreição do Senhor Jesus, e em todos eles havia abundante graça.

[[v44-4-34]]

^<<v44-4-34,34>>^ Pois não havia entre eles necessitado algum; porque todos os que possuíam terras ou casas, vendendo-as, traziam o preço do que vendiam e o depositavam aos pés dos apóstolos.

[[v44-4-35]]

^<<v44-4-35,35>>^ E se repartia a qualquer um que tivesse necessidade.

[[v44-4-36]]

^<<v44-4-36,36>>^ Então José, cognominado pelos apóstolos Barnabé &#123;que quer dizer, filho de consolação&#125;, levita, natural de Chipre,

[[v44-4-37]]

^<<v44-4-37,37>>^ possuindo um campo, vendeu-o, trouxe o preço e o depositou aos pés dos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]