include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-16-1]]

^<<v44-16-1,1>>^ Chegou também a Derbe e Listra. E eis que estava ali certo discípulo por nome Timóteo, filho de uma judia crente, mas de pai grego;

[[v44-16-2]]

^<<v44-16-2,2>>^ do qual davam bom testemunho os irmãos em Listra e Icônio.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo quis que este fosse com ele e, tomando-o, o circuncidou por causa dos judeus que estavam naqueles lugares; porque todos sabiam que seu pai era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Quando iam passando pelas cidades, entregavam aos irmãos, para serem observadas, as decisões que haviam sido tomadas pelos apóstolos e anciãos em Jerusalém.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim as igrejas eram confirmadas na fé, e dia a dia cresciam em número.

[[v44-16-6]]

^<<v44-16-6,6>>^ Atravessaram a região frígio-gálata, tendo sido impedidos pelo Espírito Santo de anunciar a palavra na Ásia;

[[v44-16-7]]

^<<v44-16-7,7>>^ e tendo chegado diante da Mísia, tentavam ir para Bitínia, mas o Espírito de Jesus não lho permitiu.

[[v44-16-8]]

^<<v44-16-8,8>>^ Então, passando pela Mísia, desceram a Trôade.

[[v44-16-9]]

^<<v44-16-9,9>>^ De noite apareceu a Paulo esta visão: estava ali em pé um homem da Macedônia, que lhe rogava: Passa à Macedônia e ajuda-nos.

[[v44-16-10]]

^<<v44-16-10,10>>^ E quando ele teve esta visão, procurávamos logo partir para a Macedônia, concluindo que Deus nos havia chamado para lhes anunciarmos o evangelho.

[[v44-16-11]]

^<<v44-16-11,11>>^ Navegando, pois, de Trôade, fomos em direitura a Samotrácia, e no dia seguinte a Neápolis;

[[v44-16-12]]

^<<v44-16-12,12>>^ e dali para Filipos, que é a primeira cidade desse distrito da Macedônia, e colônia romana; e estivemos alguns dias nessa cidade.

[[v44-16-13]]

^<<v44-16-13,13>>^ No sábado saímos portas afora para a beira do rio, onde julgávamos haver um lugar de oração e, sentados, falávamos às mulheres ali reunidas.

[[v44-16-14]]

^<<v44-16-14,14>>^ E certa mulher chamada Lídia, vendedora de púrpura, da cidade de Tiatira, e que temia a Deus, nos escutava e o Senhor lhe abriu o coração para atender às coisas que Paulo dizia.

[[v44-16-15]]

^<<v44-16-15,15>>^ Depois que foi batizada, ela e a sua casa, rogou-nos, dizendo: Se haveis julgado que eu sou fiel ao Senhor, entrai em minha casa, e ficai ali. E nos constrangeu a isso.

[[v44-16-16]]

^<<v44-16-16,16>>^ Ora, aconteceu que quando íamos ao lugar de oração, nos veio ao encontro uma jovem que tinha um espírito adivinhador, e que, adivinhando, dava grande lucro a seus senhores.

[[v44-16-17]]

^<<v44-16-17,17>>^ Ela, seguindo a Paulo e a nós, clamava, dizendo: São servos do Deus Altíssimo estes homens que vos anunciam um caminho de salvação.

[[v44-16-18]]

^<<v44-16-18,18>>^ E fazia isto por muitos dias. Mas Paulo, perturbado, voltou-se e disse ao espírito: Eu te ordeno em nome de Jesus Cristo que saias dela. E na mesma hora saiu.

[[v44-16-19]]

^<<v44-16-19,19>>^ Ora, vendo seus senhores que a esperança do seu lucro havia desaparecido, prenderam a Paulo e Silas, e os arrastaram para uma praça à presença dos magistrados.

[[v44-16-20]]

^<<v44-16-20,20>>^ E, apresentando-os aos magistrados, disseram: Estes homens, sendo judeus, estão perturbando muito a nossa cidade,

[[v44-16-21]]

^<<v44-16-21,21>>^ e pregam costumes que não nos é lícito receber nem praticar, sendo nós romanos.

[[v44-16-22]]

^<<v44-16-22,22>>^ A multidão levantou-se à uma contra eles, e os magistrados, rasgando-lhes os vestidos, mandaram açoitá-los com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ E, havendo-lhes dado muitos açoites, os lançaram na prisão, mandando ao carcereiro que os guardasse com segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ Ele, tendo recebido tal ordem, os lançou na prisão interior e lhes segurou os pés no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Pela meia-noite Paulo e Silas oravam e cantavam hinos a Deus, enquanto os presos os escutavam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente houve um tão grande terremoto que foram abalados os alicerces do cárcere, e logo se abriram todas as portas e foram soltos os grilhões de todos.

[[v44-16-27]]

^<<v44-16-27,27>>^ Ora, o carcereiro, tendo acordado e vendo abertas as portas da prisão, tirou a espada e ia suicidar-se, supondo que os presos tivessem fugido.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo bradou em alta voz, dizendo: Não te faças nenhum mal, porque todos aqui estamos.

[[v44-16-29]]

^<<v44-16-29,29>>^ Tendo ele pedido luz, saltou dentro e, todo trêmulo, se prostrou ante Paulo e Silas

[[v44-16-30]]

^<<v44-16-30,30>>^ e, tirando-os para fora, disse: Senhores, que me é necessário fazer para me salvar?

[[v44-16-31]]

^<<v44-16-31,31>>^ Responderam eles: Crê no Senhor Jesus e serás salvo, tu e tua casa.

[[v44-16-32]]

^<<v44-16-32,32>>^ Então lhe pregaram a palavra de Deus, e a todos os que estavam em sua casa.

[[v44-16-33]]

^<<v44-16-33,33>>^ Tomando-os ele consigo naquela mesma hora da noite, lavou-lhes as feridas; e logo foi batizado, ele e todos os seus.

[[v44-16-34]]

^<<v44-16-34,34>>^ Então os fez subir para sua casa, pôs-lhes a mesa e alegrou-se muito com toda a sua casa, por ter crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando amanheceu, os magistrados mandaram quadrilheiros a dizer: Soltai aqueles homens.

[[v44-16-36]]

^<<v44-16-36,36>>^ E o carcereiro transmitiu a Paulo estas palavras, dizendo: Os magistrados mandaram que fosseis soltos; agora, pois, saí e ide em paz.

[[v44-16-37]]

^<<v44-16-37,37>>^ Mas Paulo respondeu-lhes: Açoitaram-nos publicamente sem sermos condenados, sendo cidadãos romanos, e nos lançaram na prisão, e agora encobertamente nos lançam fora? De modo nenhum será assim; mas venham eles mesmos e nos tirem.

[[v44-16-38]]

^<<v44-16-38,38>>^ E os quadrilheiros foram dizer aos magistrados estas palavras, e estes temeram quando ouviram que eles eram romanos;

[[v44-16-39]]

^<<v44-16-39,39>>^ vieram, pediram-lhes desculpas e, tirando-os para fora, rogavam que se retirassem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Então eles saíram da prisão, entraram em casa de Lídia, e, vendo os irmãos, os confortaram, e partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]