include::./index.adoc[]

[[v44-28-0]]
=== Atos, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-28-1]]

^<<v44-28-1,1>>^ Estando já salvos, soubemos então que a ilha se chamava Malta.

[[v44-28-2]]

^<<v44-28-2,2>>^ Os indígenas usaram conosco de não pouca humanidade; pois acenderam uma fogueira e nos recolheram a todos por causa da chuva que caía, e por causa do frio.

[[v44-28-3]]

^<<v44-28-3,3>>^ Ora havendo Paulo ajuntado e posto sobre o fogo um feixe de gravetos, uma víbora, fugindo do calor, apegou-se-lhe à mão.

[[v44-28-4]]

^<<v44-28-4,4>>^ Quando os indígenas viram o réptil pendente da mão dele, diziam uns aos outros: Certamente este homem é homicida, pois, embora salvo do mar, a Justiça não o deixa viver.

[[v44-28-5]]

^<<v44-28-5,5>>^ Mas ele, sacudindo o réptil no fogo, não sofreu mal nenhum.

[[v44-28-6]]

^<<v44-28-6,6>>^ Eles, porém, esperavam que Paulo viesse a inchar ou a cair morto de repente; mas tendo esperado muito tempo e vendo que nada de anormal lhe sucedia, mudaram de parecer e diziam que era um deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ Ora, nos arredores daquele lugar havia umas terras que pertenciam ao homem principal da ilha, por nome Públio, o qual nos recebeu e hospedou bondosamente por três dias.

[[v44-28-8]]

^<<v44-28-8,8>>^ Aconteceu estar de cama, enfermo de febre e disenteria, o pai de Públio; Paulo foi visitá-lo, e havendo orado, impôs-lhe as mãos, e o curou.

[[v44-28-9]]

^<<v44-28-9,9>>^ Feito isto, vinham também os demais enfermos da ilha, e eram curados;

[[v44-28-10]]

^<<v44-28-10,10>>^ e estes nos distinguiram com muitas honras; e, ao embarcarmos, puseram a bordo as coisas que nos eram necessárias.

[[v44-28-11]]

^<<v44-28-11,11>>^ Passados três meses, partimos em um navio de Alexandria que invernara na ilha, o qual tinha por insígnia Castor e Pólux.

[[v44-28-12]]

^<<v44-28-12,12>>^ E chegando a Siracusa, ficamos ali três dias;

[[v44-28-13]]

^<<v44-28-13,13>>^ donde, costeando, viemos a Régio; e, soprando no dia seguinte o vento sul, chegamos em dois dias a Putéoli,

[[v44-28-14]]

^<<v44-28-14,14>>^ onde, achando alguns irmãos, fomos convidados a ficar com eles sete dias; e depois nos dirigimos a Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ Ora, os irmãos da lá, havendo recebido notícias nossas, vieram ao nosso encontro até a praça de Ápio e às Três Vendas, e Paulo, quando os viu, deu graças a Deus e cobrou ânimo.

[[v44-28-16]]

^<<v44-28-16,16>>^ Quando chegamos a Roma, &#123;o centurião entregou os presos ao general do exército, mas,&#125; a Paulo se lhe permitiu morar à parte, com o soldado que o guardava.

[[v44-28-17]]

^<<v44-28-17,17>>^ Passados três dias, ele convocou os principais dentre os judeus; e reunidos eles, disse-lhes: Varões irmãos, não havendo eu feito nada contra o povo, ou contra os ritos paternos, vim contudo preso desde Jerusalém, entregue nas mãos dos romanos;

[[v44-28-18]]

^<<v44-28-18,18>>^ os quais, havendo-me interrogado, queriam soltar-me, por não haver em mim crime algum que merecesse a morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ Mas opondo-se a isso os judeus, vi-me obrigado a apelar para César, não tendo, contudo, nada de que acusar a minha nação.

[[v44-28-20]]

^<<v44-28-20,20>>^ Por esta causa, pois, vos convidei, para vos ver e falar; porque pela esperança de Israel estou preso com esta cadeia.

[[v44-28-21]]

^<<v44-28-21,21>>^ Mas eles lhe disseram: Nem recebemos da Judéia cartas a teu respeito, nem veio aqui irmão algum que contasse ou dissesse mal de ti.

[[v44-28-22]]

^<<v44-28-22,22>>^ No entanto bem quiséramos ouvir de ti o que pensas; porque, quanto a esta seita, notório nos é que em toda parte é impugnada.

[[v44-28-23]]

^<<v44-28-23,23>>^ Havendo-lhe eles marcado um dia, muitos foram ter com ele à sua morada, aos quais desde a manhã até a noite explicava com bom testemunho o reino de Deus e procurava persuadí-los acerca de Jesus, tanto pela lei de Moisés como pelos profetas.

[[v44-28-24]]

^<<v44-28-24,24>>^ Uns criam nas suas palavras, mas outros as rejeitavam.

[[v44-28-25]]

^<<v44-28-25,25>>^ E estando discordes entre si, retiraram-se, havendo Paulo dito esta palavra: Bem falou o Espírito Santo aos vossos pais pelo profeta Isaías,

[[v44-28-26]]

^<<v44-28-26,26>>^ dizendo: Vai a este povo e dize: Ouvindo, ouvireis, e de maneira nenhuma entendereis; e vendo, vereis, e de maneira nenhuma percebereis.

[[v44-28-27]]

^<<v44-28-27,27>>^ Porque o coração deste povo se endureceu, e com os ouvidos ouviram tardamente, e fecharam os olhos; para que não vejam com os olhos, nem ouçam com os ouvidos, nem entendam com o coração nem se convertam e eu os cure.

[[v44-28-28]]

^<<v44-28-28,28>>^ Seja-vos pois notório que esta salvação de Deus é enviada aos gentios, e eles ouvirão.

[[v44-28-29]]

^<<v44-28-29,29>>^ &#123;E, havendo ele dito isto, partiram os judeus, tendo entre si grande contenda.&#125;

[[v44-28-30]]

^<<v44-28-30,30>>^ E morou dois anos inteiros na casa que alugara, e recebia a todos os que o visitavam,

[[v44-28-31]]

^<<v44-28-31,31>>^ pregando o reino de Deus e ensinando as coisas concernentes ao Senhor Jesus Cristo, com toda a liberdade, sem impedimento algum.

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]