include::./index.adoc[]

[[v44-5-0]]
=== Atos, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-5-1]]

^<<v44-5-1,1>>^ Mas um certo homem chamado Ananias, com Safira, sua mulher, vendeu uma propriedade,

[[v44-5-2]]

^<<v44-5-2,2>>^ e reteve parte do preço, sabendo-o também sua mulher; e levando a outra parte, a depositou aos pés dos apóstolos.

[[v44-5-3]]

^<<v44-5-3,3>>^ Disse então Pedro: Ananias, por que encheu Satanás o teu coração, para que mentisses ao Espírito Santo e retivesses parte do preço do terreno?

[[v44-5-4]]

^<<v44-5-4,4>>^ Enquanto o possuías, não era teu? e vendido, não estava o preço em teu poder? Como, pois, formaste este desígnio em teu coração? Não mentiste aos homens, mas a Deus.

[[v44-5-5]]

^<<v44-5-5,5>>^ E Ananias, ouvindo estas palavras, caiu e expirou. E grande temor veio sobre todos os que souberam disto.

[[v44-5-6]]

^<<v44-5-6,6>>^ Levantando-se os moços, cobriram-no e, transportando-o para fora, o sepultaram.

[[v44-5-7]]

^<<v44-5-7,7>>^ Depois de um intervalo de cerca de três horas, entrou também sua mulher, não sabendo o que havia acontecido.

[[v44-5-8]]

^<<v44-5-8,8>>^ E perguntou-lhe Pedro: Dize-me: Vendestes por tanto aquele terreno? E ela respondeu: Sim, por tanto.

[[v44-5-9]]

^<<v44-5-9,9>>^ Então Pedro lhe disse: Por que é que combinastes entre vós provar o Espírito do Senhor? Eis aí à porta os pés dos que sepultaram o teu marido, e te levarão também a ti.

[[v44-5-10]]

^<<v44-5-10,10>>^ Imediatamente ela caiu aos pés dele e expirou. E entrando os moços, acharam-na morta e, levando-a para fora, sepultaram-na ao lado do marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ Sobreveio grande temor a toda a igreja e a todos os que ouviram estas coisas.

[[v44-5-12]]

^<<v44-5-12,12>>^ E muitos sinais e prodígios eram feitos entre o povo pelas mãos dos apóstolos. E estavam todos de comum acordo no pórtico de Salomão.

[[v44-5-13]]

^<<v44-5-13,13>>^ Dos outros, porém, nenhum ousava ajuntar-se a eles; mas o povo os tinha em grande estima;

[[v44-5-14]]

^<<v44-5-14,14>>^ e cada vez mais se agregavam crentes ao Senhor em grande número tanto de homens como de mulheres,

[[v44-5-15]]

^<<v44-5-15,15>>^ a ponto de transportarem os enfermos para as ruas, e os porem em leitos e macas, para que ao passar Pedro, ao menos sua sombra cobrisse alguns deles.

[[v44-5-16]]

^<<v44-5-16,16>>^ Também das cidades circunvizinhas afluía muita gente a Jerusalém, conduzindo enfermos e atormentados de espíritos imundos, os quais eram todos curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ Levantando-se o sumo sacerdote e todos os que estavam com ele &#123;isto é, a seita dos saduceus&#125;, encheram-se de inveja,

[[v44-5-18]]

^<<v44-5-18,18>>^ deitaram mão nos apóstolos, e os puseram na prisão pública.

[[v44-5-19]]

^<<v44-5-19,19>>^ Mas de noite um anjo do Senhor abriu as portas do cárcere e, tirando-os para fora, disse:

[[v44-5-20]]

^<<v44-5-20,20>>^ Ide, apresentai-vos no templo, e falai ao povo todas as palavras desta vida.

[[v44-5-21]]

^<<v44-5-21,21>>^ Ora, tendo eles ouvido isto, entraram de manhã cedo no templo e ensinavam. Chegando, porém o sumo sacerdote e os que estavam com ele, convocaram o sinédrio, com todos os anciãos dos filhos de Israel, e enviaram guardas ao cárcere para trazê-los.

[[v44-5-22]]

^<<v44-5-22,22>>^ Mas os guardas, tendo lá ido, não os acharam na prisão; e voltando, lho anunciaram,

[[v44-5-23]]

^<<v44-5-23,23>>^ dizendo: Achamos realmente o cárcere fechado com toda a segurança, e as sentinelas em pé às portas; mas, abrindo-as, a ninguém achamos dentro.

[[v44-5-24]]

^<<v44-5-24,24>>^ E quando o capitão do templo e os principais sacerdotes ouviram estas palavras ficaram perplexos acerca deles e do que viria a ser isso.

[[v44-5-25]]

^<<v44-5-25,25>>^ Então chegou alguém e lhes anunciou: Eis que os homens que encerrastes na prisão estão no templo, em pé, a ensinar o povo.

[[v44-5-26]]

^<<v44-5-26,26>>^ Nisso foi o capitão com os guardas e os trouxe, não com violência, porque temiam ser apedrejados pelo povo.

[[v44-5-27]]

^<<v44-5-27,27>>^ E tendo-os trazido, os apresentaram ao sinédrio. E o sumo sacerdote os interrogou, dizendo:

[[v44-5-28]]

^<<v44-5-28,28>>^ Não vos admoestamos expressamente que não ensinásseis nesse nome? e eis que enchestes Jerusalém dessa vossa doutrina e quereis lançar sobre nós o sangue desse homem.

[[v44-5-29]]

^<<v44-5-29,29>>^ Respondendo Pedro e os apóstolos, disseram: Importa antes obedecer a Deus que aos homens.

[[v44-5-30]]

^<<v44-5-30,30>>^ O Deus de nossos pais ressuscitou a Jesus, ao qual vós matastes, suspendendo-o no madeiro;

[[v44-5-31]]

^<<v44-5-31,31>>^ sim, Deus, com a sua destra, o elevou a Príncipe e Salvador, para dar a Israel o arrependimento e remissão de pecados.

[[v44-5-32]]

^<<v44-5-32,32>>^ E nós somos testemunhas destas coisas, e bem assim o Espírito Santo, que Deus deu àqueles que lhe obedecem.

[[v44-5-33]]

^<<v44-5-33,33>>^ Ora, ouvindo eles isto, se enfureceram e queriam matá-los.

[[v44-5-34]]

^<<v44-5-34,34>>^ Mas, levantando-se no sinédrio certo fariseu chamado Gamaliel, doutor da lei, acatado por todo o povo, mandou que por um pouco saíssem aqueles homens;

[[v44-5-35]]

^<<v44-5-35,35>>^ e prosseguiu: Varões israelitas, acautelai-vos a respeito do que estais para fazer a estes homens.

[[v44-5-36]]

^<<v44-5-36,36>>^ Porque, há algum tempo, levantou-se Teudas, dizendo ser alguém; ao qual se ajuntaram uns quatrocentos homens; mas ele foi morto, e todos quantos lhe obedeciam foram dispersos e reduzidos a nada.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois dele levantou-se Judas, o galileu, nos dias do recenseamento, e levou muitos após si; mas também este pereceu, e todos quantos lhe obedeciam foram dispersos.

[[v44-5-38]]

^<<v44-5-38,38>>^ Agora vos digo: Dai de mão a estes homens, e deixai-os, porque este conselho ou esta obra, caso seja dos homens, se desfará;

[[v44-5-39]]

^<<v44-5-39,39>>^ mas, se é de Deus, não podereis derrotá-los; para que não sejais, porventura, achados até combatendo contra Deus.

[[v44-5-40]]

^<<v44-5-40,40>>^ Concordaram, pois, com ele, e tendo chamado os apóstolos, açoitaram-nos e mandaram que não falassem em nome de Jesus, e os soltaram.

[[v44-5-41]]

^<<v44-5-41,41>>^ Retiraram-se pois da presença do sinédrio, regozijando-se de terem sido julgados dignos de sofrer afronta pelo nome de Jesus.

[[v44-5-42]]

^<<v44-5-42,42>>^ E todos os dias, no templo e de casa em casa, não cessavam de ensinar, e de anunciar a Jesus, o Cristo.

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]