include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-18-1]]

^<<v44-18-1,1>>^ Depois disto Paulo partiu de Atenas e chegou a Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ E encontrando um judeu por nome Áqüila, natural do Ponto, que pouco antes viera da Itália, e Priscila, sua mulher &#123;porque Cláudio tinha decretado que todos os judeus saíssem de Roma&#125;, foi ter com eles,

[[v44-18-3]]

^<<v44-18-3,3>>^ e, por ser do mesmo ofício, com eles morava, e juntos trabalhavam; pois eram, por ofício, fabricantes de tendas.

[[v44-18-4]]

^<<v44-18-4,4>>^ Ele discutia todos os sábados na sinagoga, e persuadia a judeus e gregos.

[[v44-18-5]]

^<<v44-18-5,5>>^ Quando Silas e Timóteo desceram da Macedônia, Paulo dedicou-se inteiramente à palavra, testificando aos judeus que Jesus era o Cristo.

[[v44-18-6]]

^<<v44-18-6,6>>^ Como estes, porém, se opusessem e proferissem injúrias, sacudiu ele as vestes e disse-lhes: O vosso sangue seja sobre a vossa cabeça; eu estou limpo, e desde agora vou para os gentios.

[[v44-18-7]]

^<<v44-18-7,7>>^ E saindo dali, entrou em casa de um homem temente a Deus, chamado Tito Justo, cuja casa ficava junto da sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ Crispo, chefe da sinagoga, creu no Senhor com toda a sua casa; e muitos dos coríntios, ouvindo, criam e eram batizados.

[[v44-18-9]]

^<<v44-18-9,9>>^ E de noite disse o Senhor em visão a Paulo: Não temas, mas fala e não te cales;

[[v44-18-10]]

^<<v44-18-10,10>>^ porque eu estou contigo e ninguém te acometerá para te fazer mal, pois tenho muito povo nesta cidade.

[[v44-18-11]]

^<<v44-18-11,11>>^ E ficou ali um ano e seis meses, ensinando entre eles a palavra de Deus.

[[v44-18-12]]

^<<v44-18-12,12>>^ Sendo Gálio procônsul da Acaia, levantaram-se os judeus de comum acordo contra Paulo, e o levaram ao tribunal,

[[v44-18-13]]

^<<v44-18-13,13>>^ dizendo: Este persuade os homens a render culto a Deus de um modo contrário à lei.

[[v44-18-14]]

^<<v44-18-14,14>>^ E, quando Paulo estava para abrir a boca, disse Gálio aos judeus: Se de fato houvesse, ó judeus, algum agravo ou crime perverso, com razão eu vos sofreria;

[[v44-18-15]]

^<<v44-18-15,15>>^ mas, se são questões de palavras, de nomes, e da vossa lei, disso cuidai vós mesmos; porque eu não quero ser juiz destas coisas.

[[v44-18-16]]

^<<v44-18-16,16>>^ E expulsou-os do tribunal.

[[v44-18-17]]

^<<v44-18-17,17>>^ Então todos agarraram Sóstenes, chefe da sinagoga, e o espancavam diante do tribunal; e Gálio não se importava com nenhuma dessas coisas.

[[v44-18-18]]

^<<v44-18-18,18>>^ Paulo, tendo ficado ali ainda muitos dias, despediu-se dos irmãos e navegou para a Síria, e com ele Priscila e Áqüila, havendo rapado a cabeça em Cencréia, porque tinha voto.

[[v44-18-19]]

^<<v44-18-19,19>>^ E eles chegaram a Éfeso, onde Paulo os deixou; e tendo entrado na sinagoga, discutia com os judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ Estes rogavam que ficasse por mais algum tempo, mas ele não anuiu,

[[v44-18-21]]

^<<v44-18-21,21>>^ antes se despediu deles, dizendo: Se Deus quiser, de novo voltarei a vós; e navegou de Éfeso.

[[v44-18-22]]

^<<v44-18-22,22>>^ Tendo chegado a Cesaréia, subiu a Jerusalém e saudou a igreja, e desceu a Antioquia.

[[v44-18-23]]

^<<v44-18-23,23>>^ E, tendo demorado ali algum tempo, partiu, passando sucessivamente pela região da Galácia e da Frígia, fortalecendo a todos os discípulos.

[[v44-18-24]]

^<<v44-18-24,24>>^ Ora, chegou a Éfeso certo judeu chamado Apolo, natural de Alexandria, homem eloqüente e poderoso nas Escrituras.

[[v44-18-25]]

^<<v44-18-25,25>>^ Era ele instruído no caminho do Senhor e, sendo fervoroso de espírito, falava e ensinava com precisão as coisas concernentes a Jesus, conhecendo entretanto somente o batismo de João.

[[v44-18-26]]

^<<v44-18-26,26>>^ Ele começou a falar ousadamente na sinagoga: mas quando Priscila e Áqüila o ouviram, levaram-no consigo e lhe expuseram com mais precisão o caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Querendo ele passar à Acáia, os irmãos o animaram e escreveram aos discípulos que o recebessem; e tendo ele chegado, auxiliou muito aos que pela graça haviam crido.

[[v44-18-28]]

^<<v44-18-28,28>>^ Pois com grande poder refutava publicamente os judeus, demonstrando pelas escrituras que Jesus era o Cristo.

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]