include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-13-1]]

^<<v44-13-1,1>>^ Ora, na igreja em Antioquia havia profetas e mestres, a saber: Barnabé, Simeão, chamado Níger, Lúcio de Cirene, Manaém, colaço de Herodes o tetrarca, e Saulo.

[[v44-13-2]]

^<<v44-13-2,2>>^ Enquanto eles ministravam perante o Senhor e jejuavam, disse o Espírito Santo: Separai-me a Barnabé e a Saulo para a obra a que os tenho chamado.

[[v44-13-3]]

^<<v44-13-3,3>>^ Então, depois que jejuaram, oraram e lhes impuseram as mãos, os despediram.

[[v44-13-4]]

^<<v44-13-4,4>>^ Estes, pois, enviados pelo Espírito Santo, desceram a Selêucia e dali navegaram para Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ Chegados a Salamina, anunciavam a palavra de Deus nas sinagogas dos judeus, e tinham a João como auxiliar.

[[v44-13-6]]

^<<v44-13-6,6>>^ Havendo atravessado a ilha toda até Pafos, acharam um certo mago, falso profeta, judeu, chamado Bar-Jesus,

[[v44-13-7]]

^<<v44-13-7,7>>^ que estava com o procônsul Sérgio Paulo, homem sensato. Este chamou a Barnabé e Saulo e mostrou desejo de ouvir a palavra de Deus.

[[v44-13-8]]

^<<v44-13-8,8>>^ Mas resistia-lhes Elimas, o encantador &#123;porque assim se interpreta o seu nome&#125;, procurando desviar a fé do procônsul.

[[v44-13-9]]

^<<v44-13-9,9>>^ Todavia Saulo, também chamado Paulo, cheio do Espírito Santo, fitando os olhos nele,

[[v44-13-10]]

^<<v44-13-10,10>>^ disse: ó filho do diabo, cheio de todo o engano e de toda a malícia, inimigo de toda a justiça, não cessarás de perverter os caminhos retos do Senhor?

[[v44-13-11]]

^<<v44-13-11,11>>^ Agora eis a mão do Senhor sobre ti, e ficarás cego, sem ver o sol por algum tempo. Imediatamente caiu sobre ele uma névoa e trevas e, andando à roda, procurava quem o guiasse pela mão.

[[v44-13-12]]

^<<v44-13-12,12>>^ Então o procônsul, vendo o que havia acontecido, creu, maravilhando-se da doutrina do Senhor.

[[v44-13-13]]

^<<v44-13-13,13>>^ Tendo Paulo e seus companheiros navegado de Pafos, chegaram a Perge, na Panfília. João, porém, apartando-se deles, voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ Mas eles, passando de Perge, chegaram a Antioquia da Psídia; e entrando na sinagoga, no dia de sábado, sentaram-se.

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura da lei e dos profetas, os chefes da sinagoga mandaram dizer-lhes: Irmãos, se tendes alguma palavra de exortação ao povo, falai.

[[v44-13-16]]

^<<v44-13-16,16>>^ Então Paulo se levantou e, pedindo silêncio com a mão, disse: Varões israelitas, e os que temeis a Deus, ouvi:

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus deste povo de Israel escolheu a nossos pais, e exaltou o povo, sendo eles estrangeiros na terra do Egito, de onde os tirou com braço poderoso,

[[v44-13-18]]

^<<v44-13-18,18>>^ e suportou-lhes os maus costumes no deserto por espaço de quase quarenta anos;

[[v44-13-19]]

^<<v44-13-19,19>>^ e, havendo destruído as sete nações na terra de Canaã, deu-lhes o território delas por herança durante cerca de quatrocentos e cinquenta anos.

[[v44-13-20]]

^<<v44-13-20,20>>^ Depois disto, deu-lhes juízes até o profeta Samuel.

[[v44-13-21]]

^<<v44-13-21,21>>^ Então pediram um rei, e Deus lhes deu por quarenta anos a Saul, filho de Cis, varão da tribo de Benjamim.

[[v44-13-22]]

^<<v44-13-22,22>>^ E tendo deposto a este, levantou-lhes como rei a Davi, ao qual também, dando testemunho, disse: Achei a Davi, filho de Jessé, homem segundo o meu coração, que fará toda a minha vontade.

[[v44-13-23]]

^<<v44-13-23,23>>^ Da descendência deste, conforme a promessa, trouxe Deus a Israel um Salvador, Jesus;

[[v44-13-24]]

^<<v44-13-24,24>>^ havendo João, antes do aparecimento dele, pregado a todo o povo de Israel o batismo de arrependimento.

[[v44-13-25]]

^<<v44-13-25,25>>^ Mas João, quando completava a carreira, dizia: Quem pensais vós que eu sou? Eu não sou o Cristo, mas eis que após mim vem aquele a quem não sou digno de desatar as alparcas dos pés.

[[v44-13-26]]

^<<v44-13-26,26>>^ Irmãos, filhos da estirpe de Abraão, e os que dentre vós temem a Deus, a nós é enviada a palavra desta salvação.

[[v44-13-27]]

^<<v44-13-27,27>>^ Pois, os que habitam em Jerusalém e as suas autoridades, porquanto não conheceram a este Jesus, condenando-o, cumpriram as mesmas palavras dos profetas que se ouvem ler todos os sábados.

[[v44-13-28]]

^<<v44-13-28,28>>^ E, se bem que não achassem nele nenhuma causa de morte, pediram a Pilatos que ele fosse morto.

[[v44-13-29]]

^<<v44-13-29,29>>^ Quando haviam cumprido todas as coisas que dele estavam escritas, tirando-o do madeiro, o puseram na sepultura;

[[v44-13-30]]

^<<v44-13-30,30>>^ mas Deus o ressuscitou dentre os mortos;

[[v44-13-31]]

^<<v44-13-31,31>>^ e ele foi visto durante muitos dias por aqueles que com ele subiram da Galiléia a Jerusalém, os quais agora são suas testemunhas para com o povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ E nós vos anunciamos as boas novas da promessa, feita aos pais,

[[v44-13-33]]

^<<v44-13-33,33>>^ a qual Deus nos tem cumprido, a nós, filhos deles, levantando a Jesus, como também está escrito no salmo segundo: Tu és meu Filho, hoje te gerei.

[[v44-13-34]]

^<<v44-13-34,34>>^ E no tocante a que o ressuscitou dentre os mortos para nunca mais tornar à corrupção, falou Deus assim: Dar-vos-ei as santas e fiéis bênçãos de Davi;

[[v44-13-35]]

^<<v44-13-35,35>>^ pelo que ainda em outro salmo diz: Não permitirás que o teu Santo veja a corrupção.

[[v44-13-36]]

^<<v44-13-36,36>>^ Porque Davi, na verdade, havendo servido a sua própria geração pela vontade de Deus, dormiu e foi depositado junto a seus pais e experimentou corrupção.

[[v44-13-37]]

^<<v44-13-37,37>>^ Mas aquele a quem Deus ressuscitou nenhuma corrupção experimentou.

[[v44-13-38]]

^<<v44-13-38,38>>^ Seja-vos pois notório, varões, que por este se vos anuncia a remissão dos pecados.

[[v44-13-39]]

^<<v44-13-39,39>>^ E de todas as coisas de que não pudestes ser justificados pela lei de Moisés, por ele é justificado todo o que crê.

[[v44-13-40]]

^<<v44-13-40,40>>^ Cuidai pois que não venha sobre vós o que está dito nos profetas:

[[v44-13-41]]

^<<v44-13-41,41>>^ Vede, ó desprezadores, admirai-vos e desaparecei; porque realizo uma obra em vossos dias, obra em que de modo algum crereis, se alguém vo-la contar.

[[v44-13-42]]

^<<v44-13-42,42>>^ Quando iam saindo, rogavam que estas palavras lhes fossem repetidas no sábado seguinte.

[[v44-13-43]]

^<<v44-13-43,43>>^ E, despedida a sinagoga, muitos judeus e prosélitos devotos seguiram a Paulo e Barnabé, os quais, falando-lhes, os exortavam a perseverarem na graça de Deus.

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte reuniu-se quase toda a cidade para ouvir a palavra de Deus.

[[v44-13-45]]

^<<v44-13-45,45>>^ Mas os judeus, vendo as multidões, encheram-se de inveja e, blasfemando, contradiziam o que Paulo falava.

[[v44-13-46]]

^<<v44-13-46,46>>^ Então Paulo e Barnabé, falando ousadamente, disseram: Era mister que a vós se pregasse em primeiro lugar a palavra de Deus; mas, visto que a rejeitais, e não vos julgais dignos da vida eterna, eis que nos viramos para os gentios;

[[v44-13-47]]

^<<v44-13-47,47>>^ porque assim nos ordenou o Senhor: Eu te pus para luz dos gentios, a fim de que sejas para salvação até os confins da terra.

[[v44-13-48]]

^<<v44-13-48,48>>^ Os gentios, ouvindo isto, alegravam-se e glorificavam a palavra do Senhor; e creram todos quantos haviam sido destinados para a vida eterna.

[[v44-13-49]]

^<<v44-13-49,49>>^ E divulgava-se a palavra do Senhor por toda aquela região.

[[v44-13-50]]

^<<v44-13-50,50>>^ Mas os judeus incitaram as mulheres devotas de alta posição e os principais da cidade, suscitaram uma perseguição contra Paulo e Barnabé, e os lançaram fora dos seus termos.

[[v44-13-51]]

^<<v44-13-51,51>>^ Mas estes, sacudindo contra eles o pó dos seus pés, partiram para Icônio.

[[v44-13-52]]

^<<v44-13-52,52>>^ Os discípulos, porém, estavam cheios de alegria e do Espírito Santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]