include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-8-1]]

^<<v44-8-1,1>>^ Naquele dia levantou-se grande perseguição contra a igreja que estava em Jerusalém; e todos exceto os apóstolos, foram dispersos pelas regiões da Judéia e da Samária.

[[v44-8-2]]

^<<v44-8-2,2>>^ E uns homens piedosos sepultaram a Estêvão, e fizeram grande pranto sobre ele.

[[v44-8-3]]

^<<v44-8-3,3>>^ Saulo porém, assolava a igreja, entrando pelas casas e, arrastando homens e mulheres, os entregava à prisão.

[[v44-8-4]]

^<<v44-8-4,4>>^ No entanto os que foram dispersos iam por toda parte, anunciando a palavra.

[[v44-8-5]]

^<<v44-8-5,5>>^ E descendo Filipe à cidade de Samária, pregava-lhes a Cristo.

[[v44-8-6]]

^<<v44-8-6,6>>^ As multidões escutavam, unânimes, as coisas que Filipe dizia, ouvindo-o e vendo os sinais que operava;

[[v44-8-7]]

^<<v44-8-7,7>>^ pois saíam de muitos possessos os espíritos imundos, clamando em alta voz; e muitos paralíticos e coxos foram curados;

[[v44-8-8]]

^<<v44-8-8,8>>^ pelo que houve grande alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ Ora, estava ali certo homem chamado Simão, que vinha exercendo naquela cidade a arte mágica, fazendo pasmar o povo da Samária, e dizendo ser ele uma grande personagem;

[[v44-8-10]]

^<<v44-8-10,10>>^ ao qual todos atendiam, desde o menor até o maior, dizendo: Este é o Poder de Deus que se chama Grande.

[[v44-8-11]]

^<<v44-8-11,11>>^ Eles o atendiam porque já desde muito tempo os vinha fazendo pasmar com suas artes mágicas.

[[v44-8-12]]

^<<v44-8-12,12>>^ Mas, quando creram em Filipe, que lhes pregava acerca do reino de Deus e do nome de Jesus, batizavam-se homens e mulheres.

[[v44-8-13]]

^<<v44-8-13,13>>^ E creu até o próprio Simão e, sendo batizado, ficou de contínuo com Filipe; e admirava-se, vendo os sinais e os grandes milagres que se faziam.

[[v44-8-14]]

^<<v44-8-14,14>>^ Os apóstolos, pois, que estavam em Jerusalém, tendo ouvido que os da Samária haviam recebido a palavra de Deus, enviaram-lhes Pedro e João;

[[v44-8-15]]

^<<v44-8-15,15>>^ os quais, tendo descido, oraram por eles, para que recebessem o Espírito Santo.

[[v44-8-16]]

^<<v44-8-16,16>>^ Porque sobre nenhum deles havia ele descido ainda; mas somente tinham sido batizados em nome do Senhor Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Então lhes impuseram as mãos, e eles receberam o Espírito Santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Quando Simão viu que pela imposição das mãos dos apóstolos se dava o Espírito Santo, ofereceu-lhes dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ dizendo: Dai-me também a mim esse poder, para que aquele sobre quem eu impuser as mãos, receba o Espírito Santo.

[[v44-8-20]]

^<<v44-8-20,20>>^ Mas disse-lhe Pedro: Vá tua prata contigo à perdição, pois cuidaste adquirir com dinheiro o dom de Deus.

[[v44-8-21]]

^<<v44-8-21,21>>^ Tu não tens parte nem sorte neste ministério, porque o teu coração não é reto diante de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Arrepende-te, pois, dessa tua maldade, e roga ao Senhor para que porventura te seja perdoado o pensamento do teu coração;

[[v44-8-23]]

^<<v44-8-23,23>>^ pois vejo que estás em fel de amargura, e em laços de iniqüidade.

[[v44-8-24]]

^<<v44-8-24,24>>^ Respondendo, porém, Simão, disse: Rogai vós por mim ao Senhor, para que nada do que haveis dito venha sobre mim.

[[v44-8-25]]

^<<v44-8-25,25>>^ Eles, pois, havendo testificado e falado a palavra do Senhor, voltando para Jerusalém, evangelizavam muitas aldeias dos samaritanos.

[[v44-8-26]]

^<<v44-8-26,26>>^ Mas um anjo do Senhor falou a Filipe, dizendo: Levanta-te, e vai em direção do sul pelo caminho que desce de Jerusalém a Gaza, o qual está deserto.

[[v44-8-27]]

^<<v44-8-27,27>>^ E levantou-se e foi; e eis que um etíope, eunuco, mordomo-mor de Candace, rainha dos etíopes, o qual era superintendente de todos os seus tesouros e tinha ido a Jerusalém para adorar,

[[v44-8-28]]

^<<v44-8-28,28>>^ regressava e, sentado no seu carro, lia o profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ Disse o Espírito a Filipe: Chega-te e ajunta-te a esse carro.

[[v44-8-30]]

^<<v44-8-30,30>>^ E correndo Filipe, ouviu que lia o profeta Isaías, e disse: Entendes, porventura, o que estás lendo?

[[v44-8-31]]

^<<v44-8-31,31>>^ Ele respondeu: Pois como poderei entender, se alguém não me ensinar? e rogou a Filipe que subisse e com ele se sentasse.

[[v44-8-32]]

^<<v44-8-32,32>>^ Ora, a passagem da Escritura que estava lendo era esta: Foi levado como a ovelha ao matadouro, e, como está mudo o cordeiro diante do que o tosquia, assim ele não abre a sua boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Na sua humilhação foi tirado o seu julgamento; quem contará a sua geração? porque a sua vida é tirada da terra.

[[v44-8-34]]

^<<v44-8-34,34>>^ Respondendo o eunuco a Filipe, disse: Rogo-te, de quem diz isto o profeta? de si mesmo, ou de algum outro?

[[v44-8-35]]

^<<v44-8-35,35>>^ Então Filipe tomou a palavra e, começando por esta escritura, anunciou-lhe a Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ E indo eles caminhando, chegaram a um lugar onde havia água, e disse o eunuco: Eis aqui água; que impede que eu seja batizado?

[[v44-8-37]]

^<<v44-8-37,37>>^ &#123;E disse Felipe: é lícito, se crês de todo o coração. E, respondendo ele, disse: Creio que Jesus Cristo é o Filho de Deus.&#125;

[[v44-8-38]]

^<<v44-8-38,38>>^ mandou parar o carro, e desceram ambos à água, tanto Filipe como o eunuco, e Filipe o batizou.

[[v44-8-39]]

^<<v44-8-39,39>>^ Quando saíram da água, o Espírito do Senhor arrebatou a Filipe, e não o viu mais o eunuco, que jubiloso seguia o seu caminho.

[[v44-8-40]]

^<<v44-8-40,40>>^ Mas Filipe achou-se em Azoto e, indo passando, evangelizava todas as cidades, até que chegou a Cesaréia.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]