include::./index.adoc[]

[[v44-19-0]]
=== Atos, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-19-1]]

^<<v44-19-1,1>>^ E sucedeu que, enquanto Apolo estava em Corinto, Paulo tendo atravessado as regiões mais altas, chegou a Éfeso e, achando ali alguns discípulos,

[[v44-19-2]]

^<<v44-19-2,2>>^ perguntou-lhes: Recebestes vós o Espírito Santo quando crestes? Responderam-lhe eles: Não, nem sequer ouvimos que haja Espírito Santo.

[[v44-19-3]]

^<<v44-19-3,3>>^ Tornou-lhes ele: Em que fostes batizados então? E eles disseram: No batismo de João.

[[v44-19-4]]

^<<v44-19-4,4>>^ Mas Paulo respondeu: João administrou o batismo do arrependimento, dizendo ao povo que cresse naquele que após ele havia de vir, isto é, em Jesus.

[[v44-19-5]]

^<<v44-19-5,5>>^ Quando ouviram isso, foram batizados em nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ Havendo-lhes Paulo imposto as mãos, veio sobre eles o Espírito Santo, e falavam em línguas e profetizavam.

[[v44-19-7]]

^<<v44-19-7,7>>^ E eram ao todo uns doze homens.

[[v44-19-8]]

^<<v44-19-8,8>>^ Paulo, entrando na sinagoga, falou ousadamente por espaço de três meses, discutindo e persuadindo acerca do reino de Deus.

[[v44-19-9]]

^<<v44-19-9,9>>^ Mas, como alguns deles se endurecessem e não obedecessem, falando mal do Caminho diante da multidão, apartou-se deles e separou os discípulos, discutindo diariamente na escola de Tirano.

[[v44-19-10]]

^<<v44-19-10,10>>^ Durou isto por dois anos; de maneira que todos os que habitavam na Ásia, tanto judeus como gregos, ouviram a palavra do Senhor.

[[v44-19-11]]

^<<v44-19-11,11>>^ E Deus pelas mãos de Paulo fazia milagres extraordinários,

[[v44-19-12]]

^<<v44-19-12,12>>^ de sorte que lenços e aventais eram levados do seu corpo aos enfermos, e as doenças os deixavam e saíam deles os espíritos malignos.

[[v44-19-13]]

^<<v44-19-13,13>>^ Ora, também alguns dos exorcistas judeus, ambulantes, tentavam invocar o nome de Jesus sobre os que tinham espíritos malignos, dizendo: Esconjuro-vos por Jesus a quem Paulo prega.

[[v44-19-14]]

^<<v44-19-14,14>>^ E os que faziam isto eram sete filhos de Ceva, judeu, um dos principais sacerdotes.

[[v44-19-15]]

^<<v44-19-15,15>>^ Respondendo, porém, o espírito maligno, disse: A Jesus conheço, e sei quem é Paulo; mas vós, quem sois?

[[v44-19-16]]

^<<v44-19-16,16>>^ Então o homem, no qual estava o espírito maligno, saltando sobre eles, apoderou-se de dois e prevaleceu contra eles, de modo que, nus e feridos, fugiram daquela casa.

[[v44-19-17]]

^<<v44-19-17,17>>^ E isto tornou-se conhecido de todos os que moravam em Éfeso, tanto judeus como gregos; e veio temor sobre todos eles, e o nome do Senhor Jesus era engrandecido.

[[v44-19-18]]

^<<v44-19-18,18>>^ E muitos dos que haviam crido vinham, confessando e revelando os seus feitos.

[[v44-19-19]]

^<<v44-19-19,19>>^ Muitos também dos que tinham praticado artes mágicas ajuntaram os seus livros e os queimaram na presença de todos; e, calculando o valor deles, acharam que montava a cinqüenta mil moedas de prata.

[[v44-19-20]]

^<<v44-19-20,20>>^ Assim a palavra do Senhor crescia poderosamente e prevalecia.

[[v44-19-21]]

^<<v44-19-21,21>>^ Cumpridas estas coisas, Paulo propôs, em seu espírito, ir a Jerusalém, passando pela Macedônia e pela Acaia, porque dizia: Depois de haver estado ali, é-me necessário ver também Roma.

[[v44-19-22]]

^<<v44-19-22,22>>^ E, enviando à Macedônia dois dos que o auxiliavam, Timóteo e Erasto, ficou ele por algum tempo na Ásia.

[[v44-19-23]]

^<<v44-19-23,23>>^ Por esse tempo houve um não pequeno alvoroço acerca do Caminho.

[[v44-19-24]]

^<<v44-19-24,24>>^ Porque certo ourives, por nome Demétrio, que fazia da prata miniaturas do templo de Diana, proporcionava não pequeno negócio aos artífices,

[[v44-19-25]]

^<<v44-19-25,25>>^ os quais ele ajuntou, bem como os oficiais de obras semelhantes, e disse: Senhores, vós bem sabeis que desta indústria nos vem a prosperidade,

[[v44-19-26]]

^<<v44-19-26,26>>^ e estais vendo e ouvindo que não é só em Éfeso, mas em quase toda a Ásia, este Paulo tem persuadido e desviado muita gente, dizendo não serem deuses os que são feitos por mãos humanas.

[[v44-19-27]]

^<<v44-19-27,27>>^ E não somente há perigo de que esta nossa profissão caia em descrédito, mas também que o templo da grande deusa Diana seja estimado em nada, vindo mesmo a ser destituída da sua majestade aquela a quem toda a Ásia e o mundo adoram.

[[v44-19-28]]

^<<v44-19-28,28>>^ Ao ouvirem isso, encheram-se de ira, e clamavam, dizendo: Grande é a Diana dos efésios!

[[v44-19-29]]

^<<v44-19-29,29>>^ A cidade encheu-se de confusão, e todos à uma correram ao teatro, arrebatando a Gaio e a Aristarco, macedônios, companheiros de Paulo na viagem.

[[v44-19-30]]

^<<v44-19-30,30>>^ Querendo Paulo apresentar-se ao povo, os discípulos não lho permitiram.

[[v44-19-31]]

^<<v44-19-31,31>>^ Também alguns dos asiarcas, sendo amigos dele, mandaram rogar-lhe que não se arriscasse a ir ao teatro.

[[v44-19-32]]

^<<v44-19-32,32>>^ Uns, pois, gritavam de um modo, outros de outro; porque a assembléia estava em confusão, e a maior parte deles nem sabia por que causa se tinham ajuntado.

[[v44-19-33]]

^<<v44-19-33,33>>^ Então tiraram dentre a turba a Alexandre, a quem os judeus impeliram para a frente; e Alexandre, acenando com a mão, queria apresentar uma defesa ao povo.

[[v44-19-34]]

^<<v44-19-34,34>>^ Mas quando perceberam que ele era judeu, todos a uma voz gritaram por quase duas horas: Grande é a Diana dos efésios!

[[v44-19-35]]

^<<v44-19-35,35>>^ Havendo o escrivão conseguido apaziguar a turba, disse: Varões efésios, que homem há que não saiba que a cidade dos efésios é a guardadora do templo da grande deusa Diana, e da imagem que caiu de Júpiter?

[[v44-19-36]]

^<<v44-19-36,36>>^ Ora, visto que estas coisas não podem ser contestadas, convém que vos aquieteis e nada façais precipitadamente.

[[v44-19-37]]

^<<v44-19-37,37>>^ Porque estes homens que aqui trouxestes, nem são sacrílegos nem blasfemadores da nossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ Todavia, se Demétrio e os artífices que estão com ele têm alguma queixa contra alguém, os tribunais estão abertos e há procônsules: que se acusem uns aos outros.

[[v44-19-39]]

^<<v44-19-39,39>>^ E se demandais alguma outra coisa, averiguar-se-á em legítima assembléia.

[[v44-19-40]]

^<<v44-19-40,40>>^ Pois até corremos perigo de sermos acusados de sedição pelos acontecimentos de hoje, não havendo motivo algum com que possamos justificar este ajuntamento.

[[v44-19-41]]

^<<v44-19-41,41>>^ E, tendo dito isto, despediu a assembléia.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]