include::./index.adoc[]

[[v44-11-0]]
=== Atos, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-11-1]]

^<<v44-11-1,1>>^ Ora, ouviram os apóstolos e os irmãos que estavam na Judéia que também os gentios haviam recebido a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ E quando Pedro subiu a Jerusalém, disputavam com ele os que eram da circuncisão,

[[v44-11-3]]

^<<v44-11-3,3>>^ dizendo: Entraste em casa de homens incircuncisos e comeste com eles.

[[v44-11-4]]

^<<v44-11-4,4>>^ Pedro, porém, começou a fazer-lhes uma exposição por ordem, dizendo:

[[v44-11-5]]

^<<v44-11-5,5>>^ Estava eu orando na cidade de Jope, e em êxtase tive uma visão; descia um objeto, como se fosse um grande lençol, sendo baixado do céu pelas quatro pontas, e chegou perto de mim.

[[v44-11-6]]

^<<v44-11-6,6>>^ E, fitando nele os olhos, o contemplava, e vi quadrúpedes da terra, feras, répteis e aves do céu.

[[v44-11-7]]

^<<v44-11-7,7>>^ Ouvi também uma voz que me dizia: Levanta-te, Pedro, mata e come.

[[v44-11-8]]

^<<v44-11-8,8>>^ Mas eu respondi: De modo nenhum, Senhor, pois nunca em minha boca entrou coisa alguma comum e imunda.

[[v44-11-9]]

^<<v44-11-9,9>>^ Mas a voz respondeu-me do céu segunda vez: Não chames tu comum ao que Deus purificou.

[[v44-11-10]]

^<<v44-11-10,10>>^ Sucedeu isto por três vezes; e tudo tornou a recolher-se ao céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ E eis que, nesse momento, pararam em frente à casa onde estávamos três homens que me foram enviados de Cesaréia.

[[v44-11-12]]

^<<v44-11-12,12>>^ Disse-me o Espírito que eu fosse com eles, sem hesitar; e também estes seis irmãos foram comigo e entramos na casa daquele homem.

[[v44-11-13]]

^<<v44-11-13,13>>^ E ele nos contou como vira em pé em sua casa o anjo, que lhe dissera: Envia a Jope e manda chamar a Simão, que tem por sobrenome Pedro,

[[v44-11-14]]

^<<v44-11-14,14>>^ o qual te dirá palavras pelas quais serás salvo, tu e toda a tua casa.

[[v44-11-15]]

^<<v44-11-15,15>>^ Logo que eu comecei a falar, desceu sobre eles o Espírito Santo, como também sobre nós no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Lembrei-me então da palavra do Senhor, como disse: João, na verdade, batizou com água; mas vós sereis batizados no Espírito Santo.

[[v44-11-17]]

^<<v44-11-17,17>>^ Portanto, se Deus lhes deu o mesmo dom que dera também a nós, ao crermos no Senhor Jesus Cristo, quem era eu, para que pudesse resistir a Deus?

[[v44-11-18]]

^<<v44-11-18,18>>^ Ouvindo eles estas coisas, apaziguaram-se e glorificaram a Deus, dizendo: Assim, pois, Deus concedeu também aos gentios o arrependimento para a vida.

[[v44-11-19]]

^<<v44-11-19,19>>^ Aqueles, pois, que foram dispersos pela tribulação suscitada por causa de Estêvão, passaram até a Fenícia, Chipre e Antioquia, não anunciando a ninguém a palavra, senão somente aos judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ Havia, porém, entre eles alguns cíprios e cirenenses, os quais, entrando em Antioquia, falaram também aos gregos, anunciando o Senhor Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ E a mão do Senhor era com eles, e grande número creu e se converteu ao Senhor.

[[v44-11-22]]

^<<v44-11-22,22>>^ Chegou a notícia destas coisas aos ouvidos da igreja em Jerusalém; e enviaram Barnabé a Antioquia;

[[v44-11-23]]

^<<v44-11-23,23>>^ o qual, quando chegou e viu a graça de Deus, se alegrou, e exortava a todos a perseverarem no Senhor com firmeza de coração;

[[v44-11-24]]

^<<v44-11-24,24>>^ porque era homem de bem, e cheio do Espírito Santo e de fé. E muita gente se uniu ao Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ Partiu, pois, Barnabé para Tarso, em busca de Saulo;

[[v44-11-26]]

^<<v44-11-26,26>>^ e tendo-o achado, o levou para Antioquia. E durante um ano inteiro reuniram-se naquela igreja e instruíram muita gente; e em Antioquia os discípulos pela primeira vez foram chamados cristãos.

[[v44-11-27]]

^<<v44-11-27,27>>^ Naqueles dias desceram profetas de Jerusalém para Antioquia;

[[v44-11-28]]

^<<v44-11-28,28>>^ e levantando-se um deles, de nome Ágabo, dava a entender pelo Espírito, que haveria uma grande fome por todo o mundo, a qual ocorreu no tempo de Cláudio.

[[v44-11-29]]

^<<v44-11-29,29>>^ E os discípulos resolveram mandar, cada um conforme suas posses, socorro aos irmãos que habitavam na Judéia;

[[v44-11-30]]

^<<v44-11-30,30>>^ o que eles com efeito fizeram, enviando-o aos anciãos por mão de Barnabé e Saulo.

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]