include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-14-1]]

^<<v44-14-1,1>>^ Em Icônio entraram juntos na sinagoga dos judeus e falaram de tal modo que creu uma grande multidão tanto de judeus como de gregos.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus incrédulos excitaram e irritaram os ânimos dos gentios contra os irmãos.

[[v44-14-3]]

^<<v44-14-3,3>>^ Eles, entretanto, se demoraram ali por muito tempo, falando ousadamente acerca do Senhor, o qual dava testemunho à palavra da sua graça, concedendo que por suas mãos se fizessem sinais e prodígios.

[[v44-14-4]]

^<<v44-14-4,4>>^ E se dividiu o povo da cidade; uns eram pelos judeus, e outros pelos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ E, havendo um motim tanto dos gentios como dos judeus, juntamente com as suas autoridades, para os ultrajarem e apedrejarem,

[[v44-14-6]]

^<<v44-14-6,6>>^ eles, sabendo-o, fugiram para Listra e Derbe, cidades da Licaônia, e a região circunvizinha;

[[v44-14-7]]

^<<v44-14-7,7>>^ e ali pregavam o evangelho.

[[v44-14-8]]

^<<v44-14-8,8>>^ Em Listra estava sentado um homem aleijado dos pés, coxo de nascença e que nunca tinha andado.

[[v44-14-9]]

^<<v44-14-9,9>>^ Este ouvia falar Paulo, que, fitando nele os olhos e vendo que tinha fé para ser curado,

[[v44-14-10]]

^<<v44-14-10,10>>^ disse em alta voz: Levanta-te direito sobre os teus pés. E ele saltou, e andava.

[[v44-14-11]]

^<<v44-14-11,11>>^ As multidões, vendo o que Paulo fizera, levantaram a voz, dizendo em língua licaônica: Fizeram-se os deuses semelhantes aos homens e desceram até nós.

[[v44-14-12]]

^<<v44-14-12,12>>^ A Barnabé chamavam Júpiter e a Paulo, Mercúrio, porque era ele o que dirigia a palavra.

[[v44-14-13]]

^<<v44-14-13,13>>^ O sacerdote de Júpiter, cujo templo estava em frente da cidade, trouxe para as portas touros e grinaldas e, juntamente com as multidões, queria oferecer-lhes sacrifícios.

[[v44-14-14]]

^<<v44-14-14,14>>^ Quando, porém, os apóstolos Barnabé e Paulo ouviram isto, rasgaram as suas vestes e saltaram para o meio da multidão, clamando

[[v44-14-15]]

^<<v44-14-15,15>>^ e dizendo: Senhores, por que fazeis estas coisas? Nós também somos homens, de natureza semelhante à vossa, e vos anunciamos o evangelho para que destas práticas vãs vos convertais ao Deus vivo, que fez o céu, a terra, o mar, e tudo quanto há neles;

[[v44-14-16]]

^<<v44-14-16,16>>^ o qual nos tempos passados permitiu que todas as nações andassem nos seus próprios caminhos.

[[v44-14-17]]

^<<v44-14-17,17>>^ Contudo não deixou de dar testemunho de si mesmo, fazendo o bem, dando-vos chuvas do céu e estações frutíferas, enchendo-vos de mantimento, e de alegria os vossos corações.

[[v44-14-18]]

^<<v44-14-18,18>>^ E dizendo isto, com dificuldade impediram as multidões de lhes oferecerem sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Sobrevieram, porém, judeus de Antioquia e de Icônio e, havendo persuadido as multidões, apedrejaram a Paulo, e arrastaram-no para fora da cidade, cuidando que estava morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ Mas quando os discípulos o rodearam, ele se levantou e entrou na cidade. No dia seguinte partiu com Barnabé para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ E, tendo anunciado o evangelho naquela cidade e feito muitos discípulos, voltaram para Listra, Icônio e Antioquia,

[[v44-14-22]]

^<<v44-14-22,22>>^ confirmando as almas dos discípulos, exortando-os a perseverarem na fé, dizendo que por muitas tribulações nos é necessário entrar no reino de Deus.

[[v44-14-23]]

^<<v44-14-23,23>>^ E, havendo-lhes feito eleger anciãos em cada igreja e orado com jejuns, os encomendaram ao Senhor em quem haviam crido.

[[v44-14-24]]

^<<v44-14-24,24>>^ Atravessando então a Pisídia, chegaram à Panfília.

[[v44-14-25]]

^<<v44-14-25,25>>^ E, tendo anunciado a palavra em Perge, desceram a Atália.

[[v44-14-26]]

^<<v44-14-26,26>>^ E dali navegaram para Antioquia, donde tinham sido encomendados à graça de Deus para a obra que acabavam de cumprir.

[[v44-14-27]]

^<<v44-14-27,27>>^ Quando chegaram e reuniram a igreja, relataram tudo quanto Deus fizera por meio deles, e como abrira aos gentios a porta da fé.

[[v44-14-28]]

^<<v44-14-28,28>>^ E ficaram ali não pouco tempo, com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]