include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-10-1]]

^<<v44-10-1,1>>^ Um homem em Cesaréia, por nome Cornélio, centurião da corte chamada italiana,

[[v44-10-2]]

^<<v44-10-2,2>>^ piedoso e temente a Deus com toda a sua casa, e que fazia muitas esmolas ao povo e de contínuo orava a Deus,

[[v44-10-3]]

^<<v44-10-3,3>>^ cerca da hora nona do dia, viu claramente em visão um anjo de Deus, que se dirigia para ele e lhe dizia: Cornélio!

[[v44-10-4]]

^<<v44-10-4,4>>^ Este, fitando nele os olhos e atemorizado, perguntou: Que é, Senhor? O anjo respondeu-lhe: As tuas orações e as tuas esmolas têm subido para memória diante de Deus;

[[v44-10-5]]

^<<v44-10-5,5>>^ agora, pois, envia homens a Jope e manda chamar a Simão, que tem por sobrenome Pedro;

[[v44-10-6]]

^<<v44-10-6,6>>^ este se acha hospedado com um certo Simão, curtidor, cuja casa fica à beira-mar. &#123;Ele te dirá o que deves fazer.&#125;

[[v44-10-7]]

^<<v44-10-7,7>>^ Logo que se retirou o anjo que lhe falava, Cornélio chamou dois dos seus domésticos e um piedoso soldado dos que estavam a seu serviço;

[[v44-10-8]]

^<<v44-10-8,8>>^ e, havendo contado tudo, os enviou a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, indo eles seu caminho e estando já perto da cidade, subiu Pedro ao eirado para orar, cerca de hora sexta.

[[v44-10-10]]

^<<v44-10-10,10>>^ E tendo fome, quis comer; mas enquanto lhe preparavam a comida, sobreveio-lhe um êxtase,

[[v44-10-11]]

^<<v44-10-11,11>>^ e via o céu aberto e um objeto descendo, como se fosse um grande lençol, sendo baixado pelas quatro pontas sobre a terra,

[[v44-10-12]]

^<<v44-10-12,12>>^ no qual havia de todos os quadrúpedes e répteis da terra e aves do céu.

[[v44-10-13]]

^<<v44-10-13,13>>^ E uma voz lhe disse: Levanta-te, Pedro, mata e come.

[[v44-10-14]]

^<<v44-10-14,14>>^ Mas Pedro respondeu: De modo nenhum, Senhor, porque nunca comi coisa alguma comum e imunda.

[[v44-10-15]]

^<<v44-10-15,15>>^ Pela segunda vez lhe falou a voz: Não chames tu comum ao que Deus purificou.

[[v44-10-16]]

^<<v44-10-16,16>>^ Sucedeu isto por três vezes; e logo foi o objeto recolhido ao céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Enquanto Pedro refletia, perplexo, sobre o que seria a visão que tivera, eis que os homens enviados por Cornélio, tendo perguntado pela casa de Simão, pararam à porta.

[[v44-10-18]]

^<<v44-10-18,18>>^ E, chamando, indagavam se ali estava hospedado Simão, que tinha por sobrenome Pedro.

[[v44-10-19]]

^<<v44-10-19,19>>^ Estando Pedro ainda a meditar sobre a visão, o Espírito lhe disse: Eis que dois homens te procuram.

[[v44-10-20]]

^<<v44-10-20,20>>^ Levanta-te, pois, desce e vai com eles, nada duvidando; porque eu tos enviei.

[[v44-10-21]]

^<<v44-10-21,21>>^ E descendo Pedro ao encontro desses homens, disse: Sou eu a quem procurais; qual é a causa por que viestes?

[[v44-10-22]]

^<<v44-10-22,22>>^ Eles responderam: O centurião Cornélio, homem justo e temente a Deus e que tem bom testemunho de toda a nação judaica, foi avisado por um santo anjo para te chamar à sua casa e ouvir as tuas palavras.

[[v44-10-23]]

^<<v44-10-23,23>>^ Pedro, pois, convidando-os a entrar, os hospedou. No dia seguinte levantou-se e partiu com eles, e alguns irmãos, dentre os de Jope, o acompanharam.

[[v44-10-24]]

^<<v44-10-24,24>>^ No outro dia entrou em Cesaréia. E Cornélio os esperava, tendo reunido os seus parentes e amigos mais íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro ia entrar, veio-lhe Cornélio ao encontro e, prostrando-se a seus pés, o adorou.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro o ergueu, dizendo: Levanta-te, que eu também sou homem.

[[v44-10-27]]

^<<v44-10-27,27>>^ E conversando com ele, entrou e achou muitos reunidos,

[[v44-10-28]]

^<<v44-10-28,28>>^ e disse-lhes: Vós bem sabeis que não é lícito a um judeu ajuntar-se ou chegar-se a estrangeiros; mas Deus mostrou-me que a nenhum homem devo chamar comum ou imundo;

[[v44-10-29]]

^<<v44-10-29,29>>^ pelo que, sendo chamado, vim sem objeção. Pergunto pois: Por que razão mandastes chamar-me?

[[v44-10-30]]

^<<v44-10-30,30>>^ Então disse Cornélio: Faz agora quatro dias que eu estava orando em minha casa à hora nona, e eis que diante de mim se apresentou um homem com vestiduras resplandecentes,

[[v44-10-31]]

^<<v44-10-31,31>>^ e disse: Cornélio, a tua oração foi ouvida, e as tuas esmolas estão em memória diante de Deus.

[[v44-10-32]]

^<<v44-10-32,32>>^ Envia, pois, a Jope e manda chamar a Simão, que tem por sobrenome Pedro; ele está hospedado em casa de Simão, curtidor, à beira-mar.

[[v44-10-33]]

^<<v44-10-33,33>>^ Portanto mandei logo chamar-te, e bem fizeste em vir. Agora pois estamos todos aqui presentes diante de Deus, para ouvir tudo quanto te foi ordenado pelo Senhor.

[[v44-10-34]]

^<<v44-10-34,34>>^ Então Pedro, tomando a palavra, disse: Na verdade reconheço que Deus não faz acepção de pessoas;

[[v44-10-35]]

^<<v44-10-35,35>>^ mas que lhe é aceitável aquele que, em qualquer nação, o teme e pratica o que é justo.

[[v44-10-36]]

^<<v44-10-36,36>>^ A palavra que ele enviou aos filhos de Israel, anunciando a paz por Jesus Cristo &#123;este é o Senhor de todos&#125;.

[[v44-10-37]]

^<<v44-10-37,37>>^ esta palavra, vós bem sabeis, foi proclamada por toda a Judéia, começando pela Galiléia, depois do batismo que João pregou,

[[v44-10-38]]

^<<v44-10-38,38>>^ concernente a Jesus de Nazaré, como Deus o ungiu com o Espírito Santo e com poder; o qual andou por toda parte, fazendo o bem e curando a todos os oprimidos do Diabo, porque Deus era com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ Nós somos testemunhas de tudo quanto fez, tanto na terra dos judeus como em Jerusalém; ao qual mataram, pendurando-o num madeiro.

[[v44-10-40]]

^<<v44-10-40,40>>^ A este ressuscitou Deus ao terceiro dia e lhe concedeu que se manifestasse,

[[v44-10-41]]

^<<v44-10-41,41>>^ não a todo povo, mas às testemunhas que Deus antes ordenara; a nós, que comemos e bebemos juntamente com ele depois que ressurgiu dentre os mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ Este nos mandou pregar ao povo, e testificar que ele é o que por Deus foi constituído juiz dos vivos e dos mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ A ele todos os profetas dão testemunho de que todo o que nele crê receberá a remissão dos pecados pelo seu nome.

[[v44-10-44]]

^<<v44-10-44,44>>^ Enquanto Pedro ainda dizia estas coisas, desceu o Espírito Santo sobre todos os que ouviam a palavra.

[[v44-10-45]]

^<<v44-10-45,45>>^ Os crentes que eram de circuncisão, todos quantos tinham vindo com Pedro, maravilharam-se de que também sobre os gentios se derramasse o dom do Espírito Santo;

[[v44-10-46]]

^<<v44-10-46,46>>^ porque os ouviam falar línguas e magnificar a Deus.

[[v44-10-47]]

^<<v44-10-47,47>>^ Respondeu então Pedro: Pode alguém porventura recusar a água para que não sejam batizados estes que também, como nós, receberam o Espírito Santo?

[[v44-10-48]]

^<<v44-10-48,48>>^ Mandou, pois, que fossem batizados em nome de Jesus Cristo. Então lhe rogaram que ficasse com eles por alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]