include::./index.adoc[]

[[v44-26-0]]
=== Atos, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v44-26-1]]

^<<v44-26-1,1>>^ Depois Agripa disse a Paulo: É-te permitido fazer a tua defesa. Então Paulo, estendendo a mão, começou a sua defesa:

[[v44-26-2]]

^<<v44-26-2,2>>^ Sinto-me feliz, ó rei Agripa, em poder defender-me hoje perante ti de todas as coisas de que sou acusado pelos judeus;

[[v44-26-3]]

^<<v44-26-3,3>>^ mormente porque és versado em todos os costumes e questões que há entre os judeus; pelo que te rogo que me ouças com paciência.

[[v44-26-4]]

^<<v44-26-4,4>>^ A minha vida, pois, desde a mocidade, o que tem sido sempre entre o meu povo e em Jerusalém, sabem-na todos os judeus,

[[v44-26-5]]

^<<v44-26-5,5>>^ pois me conhecem desde o princípio e, se quiserem, podem dar testemunho de que, conforme a mais severa seita da nossa religião, vivi fariseu.

[[v44-26-6]]

^<<v44-26-6,6>>^ E agora estou aqui para ser julgado por causa da esperança da promessa feita por Deus a nossos pais,

[[v44-26-7]]

^<<v44-26-7,7>>^ a qual as nossas doze tribos, servindo a Deus fervorosamente noite e dia, esperam alcançar; é por causa desta esperança, ó rei, que eu sou acusado pelos judeus.

[[v44-26-8]]

^<<v44-26-8,8>>^ Por que é que se julga entre vós incrível que Deus ressuscite os mortos?

[[v44-26-9]]

^<<v44-26-9,9>>^ Eu, na verdade, cuidara que devia praticar muitas coisas contra o nome de Jesus, o nazareno;

[[v44-26-10]]

^<<v44-26-10,10>>^ o que, com efeito, fiz em Jerusalém. Pois havendo recebido autoridade dos principais dos sacerdotes, não somente encerrei muitos dos santos em prisões, como também dei o meu voto contra eles quando os matavam.

[[v44-26-11]]

^<<v44-26-11,11>>^ E, castigando-os muitas vezes por todas as sinagogas, obrigava-os a blasfemar; e enfurecido cada vez mais contra eles, perseguia-os até nas cidades estrangeiras.

[[v44-26-12]]

^<<v44-26-12,12>>^ Indo com este encargo a Damasco, munido de poder e comissão dos principais sacerdotes,

[[v44-26-13]]

^<<v44-26-13,13>>^ ao meio-dia, ó rei vi no caminho uma luz do céu, que excedia o esplendor do sol, resplandecendo em torno de mim e dos que iam comigo.

[[v44-26-14]]

^<<v44-26-14,14>>^ E, caindo nós todos por terra, ouvi uma voz que me dizia em língua hebráica: Saulo, Saulo, por que me persegues? Dura coisa te é recalcitrar contra os aguilhões.

[[v44-26-15]]

^<<v44-26-15,15>>^ Disse eu: Quem és, Senhor? Respondeu o Senhor: Eu sou Jesus, a quem tu persegues;

[[v44-26-16]]

^<<v44-26-16,16>>^ mas levanta-te e põe-te em pé; pois para isto te apareci, para te fazer ministro e testemunha tanto das coisas em que me tens visto como daquelas em que te hei de aparecer;

[[v44-26-17]]

^<<v44-26-17,17>>^ livrando-te deste povo e dos gentios, aos quais te envio,

[[v44-26-18]]

^<<v44-26-18,18>>^ para lhes abrir os olhos a fim de que se convertam das trevas à luz, e do poder de Satanás a Deus, para que recebam remissão de pecados e herança entre aqueles que são santificados pela fé em mim.

[[v44-26-19]]

^<<v44-26-19,19>>^ Pelo que, ó rei Agripa, não fui desobediente à visão celestial,

[[v44-26-20]]

^<<v44-26-20,20>>^ antes anunciei primeiramente aos que estão em Damasco, e depois em Jerusalém, e por toda a terra da Judéia e também aos gentios, que se arrependessem e se convertessem a Deus, praticando obras dignas de arrependimento.

[[v44-26-21]]

^<<v44-26-21,21>>^ Por causa disto os judeus me prenderam no templo e procuravam matar-me.

[[v44-26-22]]

^<<v44-26-22,22>>^ Tendo, pois, alcançado socorro da parte de Deus, ainda até o dia de hoje permaneço, dando testemunho tanto a pequenos como a grandes, não dizendo nada senão o que os profetas e Moisés disseram que devia acontecer;

[[v44-26-23]]

^<<v44-26-23,23>>^ isto é, como o Cristo devia padecer, e como seria ele o primeiro que, pela ressurreição dos mortos, devia anunciar a luz a este povo e também aos gentios.

[[v44-26-24]]

^<<v44-26-24,24>>^ Fazendo ele deste modo a sua defesa, disse Festo em alta voz: Estás louco, Paulo; as muitas letras te fazem delirar.

[[v44-26-25]]

^<<v44-26-25,25>>^ Mas Paulo disse: Não deliro, ó excelentíssimo Festo, antes digo palavras de verdade e de perfeito juízo.

[[v44-26-26]]

^<<v44-26-26,26>>^ Porque o rei, diante de quem falo com liberdade, sabe destas coisas, pois não creio que nada disto lhe é oculto; porque isto não se fez em qualquer canto.

[[v44-26-27]]

^<<v44-26-27,27>>^ Crês tu nos profetas, ó rei Agripa? Sei que crês.

[[v44-26-28]]

^<<v44-26-28,28>>^ Disse Agripa a Paulo: Por pouco me persuades a fazer-me cristão.

[[v44-26-29]]

^<<v44-26-29,29>>^ Respondeu Paulo: Prouvera a Deus que, ou por pouco ou por muito, não somente tu, mas também todos quantos hoje me ouvem, se tornassem tais qual eu sou, menos estas cadeias.

[[v44-26-30]]

^<<v44-26-30,30>>^ E levantou-se o rei, e o governador, e Berenice, e os que com eles estavam sentados,

[[v44-26-31]]

^<<v44-26-31,31>>^ e retirando-se falavam uns com os outros, dizendo: Este homem não fez nada digno de morte ou prisão.

[[v44-26-32]]

^<<v44-26-32,32>>^ Então Agripa disse a Festo: Este homem bem podia ser solto, se não tivesse apelado para César.

'''

xref:044-atos/044-atos-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-atos/044-atos-027.adoc#v44-27-0[Próximo Capítulo &#62;]