include::./index.adoc[]

[[v14-21-0]]
=== 2 Crônicas, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-21-1]]

^<<v14-21-1,1>>^ Depois Jeosafá dormiu com seus pais, e com eles foi sepultado na cidade de Davi. E Jeorão, seu filho, reinou em seu lugar.

[[v14-21-2]]

^<<v14-21-2,2>>^ E tinha irmãos, filhos de Jeosafá: Azarias, Jeiel, Zacarias, Asarias, Micael e Sefatias; todos estes foram filhos de Jeosafá, rei de Judá.

[[v14-21-3]]

^<<v14-21-3,3>>^ Seu pai lhes dera grandes dádivas, em prata, em ouro e em objetos preciosos, juntamente com cidades fortes em Judá; mas o reino deu a Jeorão, porque ele era o primogênito.

[[v14-21-4]]

^<<v14-21-4,4>>^ Ora, tendo Jeorão subido ao reino de seu pai, e havendo-se fortificado, matou todos os seus irmãos à espada, como também alguns dos príncipes de Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Jeorão tinha trinta e dois anos quando começou a reinar, e reinou oito anos em Jerusalém.

[[v14-21-6]]

^<<v14-21-6,6>>^ E andou no caminho dos reis de Israel, como faz Acabe, porque tinha a filha de Acabe por mulher; e fazia o que parecia mal aos olhos do senhor.

[[v14-21-7]]

^<<v14-21-7,7>>^ Contudo o Senhor não quis destruir a casa de Davi, em atenção ao pacto que tinha feito com ele, e porque tinha dito que lhe daria por todos os dias uma lâmpada, a ele e a seus filhos.

[[v14-21-8]]

^<<v14-21-8,8>>^ Nos dias de Jeorão os edomeus se revoltaram contra o domínio de Judá, e constituíram para si um rei.

[[v14-21-9]]

^<<v14-21-9,9>>^ Pelo que Jeorão passou adiante com os seus chefes e com todos os seus carros; e, levantando-se de noite, desbaratou os edomeus, que tinham cercado a ele e aos capitães dos carros.

[[v14-21-10]]

^<<v14-21-10,10>>^ Todavia os edomeus ficaram revoltados contra o domínio de Judá até o dia de hoje. Nesse mesmo tempo Libna também se revoltou contra o seu domínio, porque ele deixara ao Senhor, Deus de seus pais.

[[v14-21-11]]

^<<v14-21-11,11>>^ Ele fez também altos nos montes de Judá, induziu os habitantes de Jerusalém à idolatria e impeliu Judá a prevaricar.

[[v14-21-12]]

^<<v14-21-12,12>>^ Então lhe veio uma carta da parte de Elias, o profeta, que dizia: Assim diz o Senhor, Deus de Davi teu pai: Porquanto não andaste nos caminhos de Jeosafá, teu pai, e nos caminhos de Asa, rei de Judá;

[[v14-21-13]]

^<<v14-21-13,13>>^ mas andaste no caminho dos reis de Israel e induziste Judá e os habitantes de Jerusalém a idolatria semelhante à idolatria da casa de Acabe, e também mataste teus irmãos, da casa de teu pai, os quais eram melhores do que tu;

[[v14-21-14]]

^<<v14-21-14,14>>^ eis que o Senhor ferirá com uma grande praga o teu povo, os teus filhos, as tuas mulheres e toda a tua fazenda;

[[v14-21-15]]

^<<v14-21-15,15>>^ e tu terás uma grave enfermidade; a saber, um mal nas tuas entranhas, ate que elas saiam, de dia em dia, por causa do mal.

[[v14-21-16]]

^<<v14-21-16,16>>^ E o Senhor despertou contra Jeorão o espírito dos filisteus e dos árabes que estão da banda dos etíopes.

[[v14-21-17]]

^<<v14-21-17,17>>^ Estes subiram a Judá e, dando sobre ela, levaram toda a fazenda que se achou na casa do rei, como também seus filhos e suas mulheres; de modo que não lhe ficou filho algum, senão Jeoacaz, o mais moço de seus filhos.

[[v14-21-18]]

^<<v14-21-18,18>>^ E depois de tudo isso o Senhor o feriu nas suas entranhas com uma enfermidade incurável.

[[v14-21-19]]

^<<v14-21-19,19>>^ No decorrer do tempo, ao fim de dois anos, saíram-lhe as entranhas por causa da doença, e morreu desta horrível enfermidade. E o seu povo não lhe queimou aromas como queimara a seus pais.

[[v14-21-20]]

^<<v14-21-20,20>>^ Tinha trinta e dois anos quando começou a reinar, e reinou oito anos em Jerusalém. Morreu sem deixar de si saudades; e o sepultaram na cidade de Davi, porém não nos sepulcros dos reis.

'''

xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[Próximo Capítulo &#62;]