include::./index.adoc[]

[[v14-36-0]]
=== 2 Crônicas, 36
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-36-1]]

^<<v14-36-1,1>>^ O povo da terra tomou Jeoacaz, filho de Josias, e o constituiu rei em lugar de seu pai, em Jerusalém.

[[v14-36-2]]

^<<v14-36-2,2>>^ Tinha Jeoacaz vinte e três anos quando começou a reinar, e reinou três meses em Jerusalém.

[[v14-36-3]]

^<<v14-36-3,3>>^ Porquanto o rei do Egito o depôs em Jerusalém, e condenou a terra a pagar um tributo de cem talentos de prata e um talento de ouro.

[[v14-36-4]]

^<<v14-36-4,4>>^ Então o rei do Egito constituiu Eliaquim, irmão de Jeoacaz, rei sobre Judá e Jerusalém, e mudou-lhe o nome em Jeoiaquim; mas a seu irmão, Jeoacaz, Neco o tomou e o levou para o Egito.

[[v14-36-5]]

^<<v14-36-5,5>>^ Tinha Jeoiaquim vinte e cinco anos quando começou a reinar, e reinou onze anos em Jerusalém; e fez o que era mau aos olhos do Senhor seu Deus.

[[v14-36-6]]

^<<v14-36-6,6>>^ Contra ele subiu Nabucodonosor, rei de Babilônia, e o amarrou com cadeias a fim de o levar para Babilônia.

[[v14-36-7]]

^<<v14-36-7,7>>^ Também alguns dos vasos da casa do Senhor levou Nabucodonosor para Babilônia, e pô-los no seu templo em Babilônia.

[[v14-36-8]]

^<<v14-36-8,8>>^ Ora, o restante dos atos de Jeoiaquim, e as abominações que praticou, e o que se achou contra ele, eis que estão escritos no livro dos reis de Israel e de Judá. E Joaquim, seu filho, reinou em seu lugar.

[[v14-36-9]]

^<<v14-36-9,9>>^ Tinha Joaquim oito anos quando começou a reinar, e reinou três meses e dez dias em Jerusalém; e fez o que era mau aos olhos do Senhor.

[[v14-36-10]]

^<<v14-36-10,10>>^ Na primavera seguinte o rei Nabucodonosor mandou que o levassem para Babilônia, juntamente com os vasos preciosos da casa do Senhor; e constituiu a Zedequias, irmão de Joaquim, rei sobre Judá e Jerusalém.

[[v14-36-11]]

^<<v14-36-11,11>>^ Tinha Zedequias vinte e um anos quando começou a reinar, e reinou onze anos em Jerusalém.

[[v14-36-12]]

^<<v14-36-12,12>>^ E fez o que era mau aos olhos do Senhor seu Deus: e não se humilhou perante o profeta Jeremias, que lhe falava da parte do Senhor.

[[v14-36-13]]

^<<v14-36-13,13>>^ Também rebelou-se contra o rei Nabucodonosor, que o tinha ajuramentado por Deus. Mas endureceu a sua cerviz e se obstinou no seu coração, para não voltar ao Senhor, Deus de Israel.

[[v14-36-14]]

^<<v14-36-14,14>>^ Além disso todos os chefes dos sacerdotes e o povo aumentavam cada vez mais a sua infidelidade, seguindo todas as abominações dos gentios; e profanaram a casa do Senhor, que ele tinha santificado para si em Jerusalém.

[[v14-36-15]]

^<<v14-36-15,15>>^ E o Senhor, Deus de seus pais, falou-lhes persistentemente por intermédio de seus mensageiros, porque se compadeceu do seu povo e da sua habitação.

[[v14-36-16]]

^<<v14-36-16,16>>^ Eles, porém, zombavam dos mensageiros de Deus, desprezando as suas palavras e mofando dos seus profetas, até que o furor do Senhor subiu tanto contra o seu povo, que mais nenhum remédio houve.

[[v14-36-17]]

^<<v14-36-17,17>>^ Por isso fez vir sobre eles o rei dos caldeus, o qual matou os seus mancebos à espada, na casa do seu santuário, e não teve piedade nem dos mancebos, nem das donzelas, nem dos velhos nem dos decrépitos; entregou-lhos todos nas mãos.

[[v14-36-18]]

^<<v14-36-18,18>>^ E todos os vasos da casa de Deus, grandes e pequenos, os tesouros da casa do Senhor, e os tesouros do rei e dos seus príncipes, tudo levou para Babilônia.

[[v14-36-19]]

^<<v14-36-19,19>>^ Também queimaram a casa de Deus, derribaram os muros de Jerusalém, queimaram a fogo todos os seus palácios, e destruíram todos os seus vasos preciosos.

[[v14-36-20]]

^<<v14-36-20,20>>^ E aos que escaparam da espada, a esses levou para Babilônia; e se tornaram servos dele e de seus filhos, até o tempo do reino da Pérsia,

[[v14-36-21]]

^<<v14-36-21,21>>^ para se cumprir a palavra do Senhor proferida pela boca de Jeremias, até haver a terra gozado dos seus sábados; pois por todos os dias da desolação repousou, até que os setenta anos se cumpriram.

[[v14-36-22]]

^<<v14-36-22,22>>^ Ora, no primeiro ano de Ciro, rei da pérsia, para que se cumprisse a palavra do Senhor proferida pela boca de Jeremias, despertou o Senhor o espírito de Ciro, rei da Pérsia, de modo que ele fez proclamar por todo o seu reino, de viva voz e também por escrito, este decreto:

[[v14-36-23]]

^<<v14-36-23,23>>^ Assim diz Ciro, rei da Pérsia: O Senhor Deus do céu me deu todos os reinos da terra, e me encarregou de lhe edificar uma casa em Jerusalém, que é em Judá. Quem há entre vós de todo o seu povo suba, e o Senhor seu Deus seja com ele.

'''

xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[&#60; Capítulo Anterior] | <<v14-36-0,Topo>> | xref:015-esdras/015-esdras-001.adoc#v15-1-0[Próximo Capítulo &#62;]