include::./index.adoc[]

[[v14-31-0]]
=== 2 Crônicas, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-31-1]]

^<<v14-31-1,1>>^ Acabado tudo isso, todos os israelitas que ali estavam saíram às cidades de Judá e despedaçaram as colunas, cortaram os aserins, e derrubaram os altos e altares por toda a Judá e Benjamim, como também em Efraim e Manassés, até os destruírem de todo. Depois voltaram todos os filhos de Israel para as suas cidades, cada um para sua possessão.

[[v14-31-2]]

^<<v14-31-2,2>>^ E Ezequias estabeleceu as turmas dos sacerdotes e levitas, turma por turma, cada um segundo o seu serviço, tanto os sacerdotes como os levitas, para os holocaustos e as ofertas pacíficas, para ministrarem, renderem ações de graças e cantarem louvores nas portas do arraial do Senhor.

[[v14-31-3]]

^<<v14-31-3,3>>^ A contribuição da fazenda do rei foi designada para os holocaustos: os holocaustos da manhã e da tarde, e os holocaustos dos sábados, das luas novas e das festas fixas, como está escrito na lei do Senhor.

[[v14-31-4]]

^<<v14-31-4,4>>^ Além disso ordenou ao povo que morava em Jerusalém que desse a porção pertencente aos sacerdotes e aos levitas, para que eles se dedicassem à lei do Senhor.

[[v14-31-5]]

^<<v14-31-5,5>>^ Logo que esta ordem se divulgou, os filhos de Israel trouxeram em abundância as primícias de trigo, mosto, azeite, mel e todo produto do campo; também trouxeram em abundância o dízimo de tudo.

[[v14-31-6]]

^<<v14-31-6,6>>^ Os filhos de Israel e de Judá que habitavam nas cidades de Judá também trouxeram o dízimo de bois e de ovelhas, e o dízimo das coisas dedicadas que foram consagradas ao Senhor seu Deus, e depositaram-nos em montões.

[[v14-31-7]]

^<<v14-31-7,7>>^ No terceiro mês começaram a formar os montões, e no sétimo mês acabaram.

[[v14-31-8]]

^<<v14-31-8,8>>^ Vindo, pois, Ezequias e os príncipes, e vendo aqueles montões, bendisseram ao Senhor e ao seu povo Israel.

[[v14-31-9]]

^<<v14-31-9,9>>^ Então perguntou Ezequias aos sacerdotes e aos levitas acerca daqueles montões.

[[v14-31-10]]

^<<v14-31-10,10>>^ Respondeu-lhe Azarias, o sumo sacerdote, que era da casa de Zadoque, dizendo: Desde que o povo começou a trazer as ofertas para a casa do Senhor, tem havido o que comer e de que se fartar, e ainda nos tem sobejado bastante, porque o Senhor abençoou ao seu povo; e os sobejos constituem esta abastança.

[[v14-31-11]]

^<<v14-31-11,11>>^ Então ordenou Ezequias que se preparassem câmaras na casa do Senhor; e as prepararam.

[[v14-31-12]]

^<<v14-31-12,12>>^ Ali recolheram fielmente as ofertas, os dízimos e as coisas dedicadas; e tinha o cargo disto o levita Conanias, e depois dele Simei, seu irmão.

[[v14-31-13]]

^<<v14-31-13,13>>^ E Jeiel, Azazias, Naate, Asael, Jerimote, Jozabade, Eliel, Ismaquias, Maate e Benaías eram superintendentes sob a direção de Conanias e de Simei, seu irmão, por decreto do rei Ezequias e de Azarias, o chefe da casa de Deus.

[[v14-31-14]]

^<<v14-31-14,14>>^ E o levita Coré, filho de Imná, e guarda da porta oriental, estava encarregado das ofertas voluntárias que se faziam a Deus, para distribuir as ofertas do Senhor e as coisas santíssimas.

[[v14-31-15]]

^<<v14-31-15,15>>^ E debaixo das suas ordens estavam Edem, Miniamim, Jesuá, Semaías, Amarias e Secanias, nas cidades dos sacerdotes, para fazerem com fidelidade a distribuição a seus irmãos, segundo as suas turmas, tanto aos pequenos como aos grandes,

[[v14-31-16]]

^<<v14-31-16,16>>^ exceto os que estavam contados pelas genealogias, varões da idade de três anos para cima, todos os que entravam na casa do Senhor, para o seu serviço diário nos seus cargos segundo as suas turmas.

[[v14-31-17]]

^<<v14-31-17,17>>^ Quanto ao registro dos sacerdotes, era feito segundo as suas casas paternas; e o dos levitas da idade de vinte anos para cima era feito segundo os seus cargos nas suas turmas.

[[v14-31-18]]

^<<v14-31-18,18>>^ Os sacerdotes eram arrolados com todos os seus pequeninos, suas mulheres, seus filhos e suas filhas, por toda a congregação; porque estes se dedicavam fielmente às coisas consagradas.

[[v14-31-19]]

^<<v14-31-19,19>>^ Também para os filhos de Arão os sacerdotes que estavam nos campos dos arrabaldes das suas cidades, em cada cidade, havia homens designados por nome para distribuírem porções a todo homem entre os sacerdotes e a todos os arrolados entre os levitas.

[[v14-31-20]]

^<<v14-31-20,20>>^ Assim fez Ezequias em todo o Judá; e fez o que era bom, e reto, e fiel perante o Senhor seu Deus.

[[v14-31-21]]

^<<v14-31-21,21>>^ E toda a obra que empreendeu no serviço da casa de Deus, e de acordo com a lei e os mandamentos, para buscar a seu Deus, ele a fez de todo o seu coração e foi bem sucedido.

'''

xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[&#60; Capítulo Anterior] | <<v14-31-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[Próximo Capítulo &#62;]