include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-26-1]]

^<<v14-26-1,1>>^ Então todo o povo de Judá tomou a Uzias, que tinha dezesseis anos, e o fizeram rei em lugar de seu pai Amazias.

[[v14-26-2]]

^<<v14-26-2,2>>^ Ele edificou Elote, e a restituiu a Judá, depois que o rei dormiu com seus pais.

[[v14-26-3]]

^<<v14-26-3,3>>^ Tinha Uzias dezesseis anos quando começou a reinar, e reinou cinqüenta e dois anos em Jerusalém. E o nome de sua mãe era Jecolia, de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ Ele fez o que era reto aos olhos do Senhor, conforme tudo o que fizera Amazias seu pai.

[[v14-26-5]]

^<<v14-26-5,5>>^ E buscou a Deus enquanto viveu Zacarias, que o instruiu no temor de Deus; e enquanto buscou ao Senhor, Deus o fez prosperar.

[[v14-26-6]]

^<<v14-26-6,6>>^ Saiu e guerreou contra os filisteus, e derrubou o muro de Gate, o muro de Jabné e o muro de Asdode; e edificou cidades no país de Asdode e entre os filisteus;

[[v14-26-7]]

^<<v14-26-7,7>>^ porque Deus, o ajudou contra os filisteus e contra os árabes que habitavam em Gur-Baal, e contra os meunitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ Os amonitas pagaram tributo a Uzias; e a sua fama se espalhou até a entrada do Egito, pois se tornou muito poderoso.

[[v14-26-9]]

^<<v14-26-9,9>>^ Também Uzias edificou torres em Jerusalém, à porta da esquina, à porta do vale e ao ângulo do muro, e as fortificou.

[[v14-26-10]]

^<<v14-26-10,10>>^ Edificou torres no deserto, e cavou muitos poços, porque tinha muito gado tanto nos vales como nas campinas; e tinha lavradores e vinhateiros nos montes e nos campos férteis, pois era amigo da agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ Tinha também Uzias um exército de homens destros nas armas, que saíam à guerra em tropas, segundo o número da sua resenha feita pelo escrivão Jeiel e o oficial Maaséias, sob as ordens de Hananias, um dos príncipes do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O número total dos chefes das casas paternas, homens valorosos, era de dois mil e seiscentos.

[[v14-26-13]]

^<<v14-26-13,13>>^ E sob as suas ordens havia um exército disciplinado de trezentos e sete mil e quinhentos homens, que guerreavam valorosamente, para ajudarem o rei contra os inimigos.

[[v14-26-14]]

^<<v14-26-14,14>>^ Uzias proveu o exército inteiro de escudos, lanças, capacetes, couraças e arcos, e até fundas para atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ E em Jerusalém fabricou máquinas, inventadas por peritos, para que fossem colocadas nas torres e nos cantos das muralhas, a fim de se atirarem com elas flechas e grandes pedras. E voou a sua fama até muito longe; porque foi maravilhosamente ajudado, até que se tornou poderoso.

[[v14-26-16]]

^<<v14-26-16,16>>^ Mas, quando ele se havia tornado poderoso, o seu coração se exaltou de modo que se corrompeu, e cometeu transgressões contra o Senhor, seu Deus; pois entrou no templo do Senhor para queimar incenso no altar do incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ Mas o sacerdote Azarias entrou após ele, com oitenta sacerdotes do Senhor, homens valorosos,

[[v14-26-18]]

^<<v14-26-18,18>>^ e se opuseram ao rei Uzias, dizendo-lhe: A ti, Uzias, não compete queimar incenso perante o Senhor, mas aos sacerdotes, filhos de Arão, que foram consagrados para queimarem incenso. Sai do santuário, pois cometeste uma transgressão; e não será isto para honra tua da parte do Senhor Deus.

[[v14-26-19]]

^<<v14-26-19,19>>^ Então Uzias se indignou; e tinha na mão um incensário para queimar incenso. Indignando-se ele, pois, contra os sacerdotes, nasceu-lhe a lepra na testa, perante os sacerdotes, na casa de Senhor, junto ao altar do incenso.

[[v14-26-20]]

^<<v14-26-20,20>>^ Então o sumo sacerdote Azarias olhou para ele, como também todos os sacerdotes, e eis que já estava leproso na sua testa. E apressuradamente o lançaram fora, e ele mesmo se apressou a sair, porque o Senhor o ferira.

[[v14-26-21]]

^<<v14-26-21,21>>^ Assim ficou leproso o rei Uzias até o dia da sua morte; e, por ser leproso, morou numa casa separada, pois foi excluído da casa do Senhor. E Jotão, seu filho, tinha o cargo da casa do rei, julgando o povo da terra.

[[v14-26-22]]

^<<v14-26-22,22>>^ Quanto ao restante dos atos de Uzias, desde os primeiros até os últimos, o profeta Isaías, filho de Amoz, o escreveu.

[[v14-26-23]]

^<<v14-26-23,23>>^ Assim dormiu Uzias com seus pais, e com eles o sepultaram, isto é, no campo de sepultura que era dos reis; pois disseram: ele é leproso. E Jotão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]