include::./index.adoc[]

[[v14-17-0]]
=== 2 Crônicas, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-17-1]]

^<<v14-17-1,1>>^ Jeosafá, seu filho, reinou em seu lugar, e fortaleceu-se contra Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ Pôs forças armadas em todas as cidades fortes de Judá e dispôs guarnições na terra de Judá, como também nas cidades de Efraim que Asa, seu pai, tinha tomado.

[[v14-17-3]]

^<<v14-17-3,3>>^ E o Senhor era com Jeosafá, porque andou conforme os primeiros caminhos de Davi, seu pai, e não buscou aos baalins;

[[v14-17-4]]

^<<v14-17-4,4>>^ antes buscou ao Deus de seu pai, e andou nos seus mandamentos, e não segundo as obras de Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ Por isso o Senhor confirmou o reino na sua mão; e todo o Judá trouxe presentes a Jeosafá; e ele teve riquezas e glória em abundância.

[[v14-17-6]]

^<<v14-17-6,6>>^ E encorajou-se o seu coração nos caminhos do Senhor; e ele tirou de Judá os altos e os aserins.

[[v14-17-7]]

^<<v14-17-7,7>>^ No terceiro ano do seu reinado enviou ele os seus príncipes, Bene-Hail, Obadias, Zacarias, Netanel e Micaías, para ensinarem nas cidades de Judá;

[[v14-17-8]]

^<<v14-17-8,8>>^ e com eles os levitas Semaías, Netanias, Zebadias, Asael, Semiramote, Jônatas, Adonias, Tobias e Tobadonias e, com estes levitas, os sacerdotes Elisama e Jeorão.

[[v14-17-9]]

^<<v14-17-9,9>>^ E ensinaram em Judá, levando consigo o livro da lei do Senhor; foram por todas as cidades de Judá, ensinando entre o povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ Então caiu o temor do Senhor sobre todos os reinos das terras que estavam ao redor de Judá, de modo que não fizeram guerra contra Jeosafá.

[[v14-17-11]]

^<<v14-17-11,11>>^ Alguns dentre os filisteus traziam presentes a Jeosafá, e prata como tributo; e os árabes lhe trouxeram rebanhos: sete mil e setecentos carneiros, e sete mil e setecentos bodes.

[[v14-17-12]]

^<<v14-17-12,12>>^ Assim Jeosafá ia-se tornando cada vez mais poderoso; e edificou fortalezas e cidades-armazéns em Judá;

[[v14-17-13]]

^<<v14-17-13,13>>^ e teve grande quantidade de munições nas cidades de Judá, e soldados, homens valorosos, em Jerusalém.

[[v14-17-14]]

^<<v14-17-14,14>>^ Este é o número deles segundo as suas casas paternas: de Judá os comandantes de mil: o comandante Adná, com trezentos mil homens valorosos;

[[v14-17-15]]

^<<v14-17-15,15>>^ após ele o comandante Jeoanã com duzentos e oitenta mil;

[[v14-17-16]]

^<<v14-17-16,16>>^ após ele Amasias, filho de Zicri, que voluntariamente se entregou ao Senhor, e com ele duzentos mil valorosos;

[[v14-17-17]]

^<<v14-17-17,17>>^ e de Benjamim: Eliadá, homem destemido, com duzentos mil armados de arco e de escudo;

[[v14-17-18]]

^<<v14-17-18,18>>^ e após ele Jeozabade, com cento e oitenta mil armados para a guerra.

[[v14-17-19]]

^<<v14-17-19,19>>^ Estes estavam no serviço do rei, afora os que o rei tinha posto nas cidades fortes por todo o Judá.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]