include::./index.adoc[]

[[v14-6-0]]
=== 2 Crônicas, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-6-1]]

^<<v14-6-1,1>>^ Então disse Salomão: O Senhor disse que habitaria nas trevas.

[[v14-6-2]]

^<<v14-6-2,2>>^ E eu te construí uma casa para morada, um lugar para a tua eterna habitação.

[[v14-6-3]]

^<<v14-6-3,3>>^ Então o rei virou o rosto e abençoou toda a congregação de Israel; e toda a congregação estava em pé.

[[v14-6-4]]

^<<v14-6-4,4>>^ E ele disse: Bendito seja o Senhor Deus de Israel, que pelas suas mãos cumpriu o que falou pela sua boca a Davi, meu pai, dizendo:

[[v14-6-5]]

^<<v14-6-5,5>>^ Desde o dia em que tirei o meu povo da terra do Egito não escolhi cidade alguma de todas as tribos de Israel, para edificar nela uma casa em que estivesse o meu nome, nem escolhi homem algum para ser chefe do meu povo Israel;

[[v14-6-6]]

^<<v14-6-6,6>>^ mas escolhi Jerusalém para que ali estivesse o meu nome; e escolhi Davi para que estivesse sobre o meu povo Israel.

[[v14-6-7]]

^<<v14-6-7,7>>^ Davi, meu pai, teve no seu coração o propósito de edificar uma casa ao nome do Senhor, Deus de Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ Mas o Senhor disse a Davi, meu pai: Porquanto tiveste no teu coração o propósito de edificar uma casa ao meu nome, fizeste bem em ter isto no teu coração.

[[v14-6-9]]

^<<v14-6-9,9>>^ Contudo tu não edificarás a casa, mas teu filho, que há de proceder de teus lombos, esse edificará a casa ao meu nome.

[[v14-6-10]]

^<<v14-6-10,10>>^ Assim cumpriu o Senhor a palavra que falou; pois eu me levantei em lugar de Davi, meu pai, e me assentei sobre o trono de Israel, como prometeu o Senhor, e edifiquei a casa ao nome do Senhor, Deus de Israel.

[[v14-6-11]]

^<<v14-6-11,11>>^ E pus nela a arca, em que está o pacto que o Senhor fez com os filhos de Israel.

[[v14-6-12]]

^<<v14-6-12,12>>^ Depois Salomão se colocou diante do altar do Senhor, na presença de toda a congregação de Israel, e estendeu as mãos

[[v14-6-13]]

^<<v14-6-13,13>>^ &#123;pois Salomão tinha feito uma plataforma de bronze, de cinco côvados de comprimento, cinco de largura e três de altura, a qual tinha posto no meio do átrio; a ela assomou e, pondo-se de joelhos perante toda a congregação de Israel, estendeu as mãos para o céu&#125;,

[[v14-6-14]]

^<<v14-6-14,14>>^ e disse: Ó Senhor, Deus de Israel, não há, nem no céu nem na terra, Deus semelhante a ti, que guardas o pacto e a beneficência para com os teus servos que andam perante ti de todo o seu coração;

[[v14-6-15]]

^<<v14-6-15,15>>^ que cumpriste ao teu servo Davi, meu pai, o que lhe falaste; sim, pela tua boca o disseste, e pela tua mão o cumpriste, como se vê neste dia.

[[v14-6-16]]

^<<v14-6-16,16>>^ Agora, pois, Senhor, Deus de Israel, cumpre ao teu servo Davi, meu pai, o que lhe promete-te, dizendo: Nunca te faltará varão diante de mim, que se assente sobre o trono de Israel; tão somente que teus filhos guardem o seu caminho para andarem na minha lei, como tu andaste diante de mim.

[[v14-6-17]]

^<<v14-6-17,17>>^ Agora pois, Senhor, Deus de Israel, confirme-se a tua palavra, que falaste ao teu servo Davi.

[[v14-6-18]]

^<<v14-6-18,18>>^ Mas, na verdade, habitará Deus com os homens na terra? Eis que o céu e o céu dos céus não te podem conter; quanto menos esta casa que tenho edificado!

[[v14-6-19]]

^<<v14-6-19,19>>^ Contudo, atende à oração e à súplica do teu servo, ó Senhor meu Deus, para ouvires o clamor e a oração que o teu servo faz diante de ti;

[[v14-6-20]]

^<<v14-6-20,20>>^ que dia e noite estejam os teus olhos abertos para esta casa, sim, para o lugar de que disseste que ali porias o teu nome; para ouvires a oração que o teu servo fizer neste lugar.

[[v14-6-21]]

^<<v14-6-21,21>>^ Ouve as súplicas do teu servo, e do teu povo Israel, que fizerem neste lugar; sim, ouve do lugar da tua habitação, do céu; e, ouvindo, perdoa.

[[v14-6-22]]

^<<v14-6-22,22>>^ Se alguém pecar contra o seu próximo, e lhe for exigido que jure, e ele vier jurar perante o teu altar, nesta casa,

[[v14-6-23]]

^<<v14-6-23,23>>^ ouve então do céu, age, e julga os teus servos: paga ao culpado, fazendo recair sobre a sua cabeça o seu proceder, e justifica ao reto, retribuindo-lhe segundo a sua retidão.

[[v14-6-24]]

^<<v14-6-24,24>>^ Se o teu povo Israel for derrotado diante do inimigo, por ter pecado contra ti; e eles se converterem, e confessarem o teu nome, e orarem e fizerem súplicas diante de ti nesta casa,

[[v14-6-25]]

^<<v14-6-25,25>>^ ouve então do céu, e perdoa os pecados do teu povo Israel, e torna a levá-los para a terra que lhes deste a eles e a seus pais.

[[v14-6-26]]

^<<v14-6-26,26>>^ Se o céu se fechar e não houver chuva, por terem pecado contra ti; se orarem, voltados para este lugar, e confessarem o teu nome, e se converterem dos seus pecados, quando tu os afligires,

[[v14-6-27]]

^<<v14-6-27,27>>^ ouve então do céu, e perdoa o pecado dos teus servos, e do teu povo Israel, ensinando-lhes o bom caminho, em que devem andar, envia chuva sobre a tua terra, que deste ao teu povo em herança.

[[v14-6-28]]

^<<v14-6-28,28>>^ Se houver na terra fome ou peste, se houver crestamento ou ferrugem, gafanhotos ou lagarta; se os seus inimigos os cercarem nas suas cidades; seja qual for a praga ou doença que houver;

[[v14-6-29]]

^<<v14-6-29,29>>^ toda oração e toda súplica que qualquer homem ou todo o teu povo Israel fizer, conhecendo cada um a sua praga e a sua dor, e estendendo as suas mãos para esta casa,

[[v14-6-30]]

^<<v14-6-30,30>>^ ouve então do céu, lugar da tua habitação, e perdoa, e dá a cada um conforme todos os seus caminhos, segundo vires o seu coração &#123;pois tu, só tu conheces o coração dos filhos dos homens&#125;

[[v14-6-31]]

^<<v14-6-31,31>>^ para que te temam e andem nos teus caminhos todos os dias que viverem na terra que deste a nossos pais.

[[v14-6-32]]

^<<v14-6-32,32>>^ Assim também ao estrangeiro, que não é do teu povo Israel, quando vier de um país remoto por amor do teu grande nome, da tua mão poderosa e do teu braço estendido, vindo ele e orando nesta casa,

[[v14-6-33]]

^<<v14-6-33,33>>^ ouve então do céu, lugar da tua habitação, e faze conforme tudo o que o estrangeiro te suplicar, a fim de que todos os povos da terra conheçam o teu nome, e te temam como o teu povo Israel, e saibam que pelo teu nome é chamada esta casa que edifiquei.

[[v14-6-34]]

^<<v14-6-34,34>>^ Se o teu povo sair à guerra contra os seus inimigos, seja qual for o caminho por que os enviares, e orarem a ti, voltados para esta cidade que escolheste e para a casa que edifiquei ao teu nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ ouve então do céu a sua oração e a sua súplica, e defende a sua causa.

[[v14-6-36]]

^<<v14-6-36,36>>^ Se pecarem contra ti &#123;pois não há homem que não peque&#125;, e tu te indignares contra eles, e os entregares ao inimigo, de modo que os levem em cativeiro para alguma terra, longínqua ou próxima;

[[v14-6-37]]

^<<v14-6-37,37>>^ se na terra para onde forem levados em cativeiro caírem em si, e se converterem, e na terra do seu cativeiro te suplicarem, dizendo: Pecamos, cometemos iniqüidade, procedemos perversamente;

[[v14-6-38]]

^<<v14-6-38,38>>^ se eles se arrependerem de todo o seu coração e de toda a sua alma, na terra do seu cativeiro, a que os tenham levado cativos, e orarem voltados para a sua terra, que deste a seus pais, e para a cidade que escolheste, e para a casa que edifiquei ao teu nome,

[[v14-6-39]]

^<<v14-6-39,39>>^ ouve então do céu, lugar da tua habitação, a sua oração e as suas súplicas, defende a sua causa e perdoa ao teu povo que houver pecado contra ti.

[[v14-6-40]]

^<<v14-6-40,40>>^ Agora, ó meu Deus, estejam os teus olhos abertos, e os teus ouvidos atentos à oração que se fizer neste lugar.

[[v14-6-41]]

^<<v14-6-41,41>>^ Levanta-te pois agora, Senhor Deus, e vem para o lugar do teu repouso, tu e a arca da tua fortaleza; sejam os teus sacerdotes, ó Senhor Deus, vestidos de salvação, e os teus santos se regozijem no bem.

[[v14-6-42]]

^<<v14-6-42,42>>^ Senhor Deus, não faças virar o rosto do teu ungido; lembra-te das tuas misericórdias para com teu servo Davi!

'''

xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]