include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-4-1]]

^<<v14-4-1,1>>^ Além disso fez um altar de bronze de vinte côvados de comprimento, vinte de largura e dez de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Fez também o mar de fundição; era redondo e media dez côvados duma borda à outra, cinco de altura e trinta de circunferência.

[[v14-4-3]]

^<<v14-4-3,3>>^ Por baixo da borda figuras de bois que cingiam o mar ao redor, dez em cada côvado, contornando-o todo; os bois estavam em duas fileiras e foram fundidos juntamente com o mar.

[[v14-4-4]]

^<<v14-4-4,4>>^ O mar estava assentado sobre doze bois, três dos quais olhavam para o norte, três para o ocidente, três para o sul, e três para o oriente; e o mar estava posto sobre os bois, cujas ancas estavam todas para a banda de dentro.

[[v14-4-5]]

^<<v14-4-5,5>>^ Tinha quatro dedos de grossura; e a sua borda foi feita como a borda dum copo, como a flor dum lírio; e cabiam nele mais de três mil batos.

[[v14-4-6]]

^<<v14-4-6,6>>^ Fez também dez pias; e pôs cinco à direita e cinco à esquerda, para lavarem nelas; isto é, lavaram nelas o que pertencia ao holocausto. Porém o mar era para os sacerdotes se lavarem nele.

[[v14-4-7]]

^<<v14-4-7,7>>^ E fez dez castiçais de ouro, segundo o que fora ordenado a respeito deles, e pô-los no templo, cinco à direita e cinco à esquerda.

[[v14-4-8]]

^<<v14-4-8,8>>^ Também fez dez mesas, e pô-las no templo, cinco à direita e cinco à esquerda; e fez ainda cem bacias de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Fez mais o átrio dos sacerdotes, e o átrio grande, e as suas portas, as quais revestiu de bronze.

[[v14-4-10]]

^<<v14-4-10,10>>^ E pôs o mar ao lado direito da casa, a sudeste.

[[v14-4-11]]

^<<v14-4-11,11>>^ Hurão fez ainda as caldeiras, as pás e as bacias. Assim completou Hurão a obra que fazia para o rei Salomão na casa de Deus:

[[v14-4-12]]

^<<v14-4-12,12>>^ as duas colunas, os globos, e os dois capitéis no alto das colunas; as duas redes para cobrir os dois globos dos capitéis que estavam no alto das colunas;

[[v14-4-13]]

^<<v14-4-13,13>>^ e as quatrocentas romãs para as duas redes, duas fileiras de romãs para cada rede, para cobrirem os dois globos dos capitéis que estavam em cima das colunas.

[[v14-4-14]]

^<<v14-4-14,14>>^ Também fez as bases, e as pias sobre as bases;

[[v14-4-15]]

^<<v14-4-15,15>>^ o mar, e os doze bois debaixo dele.

[[v14-4-16]]

^<<v14-4-16,16>>^ Semelhantemente as caldeiras, as pás, os garfos e todos os vasos, os fez Hurão-Abi de bronze luzente para o rei Salomão, para a casa do Senhor.

[[v14-4-17]]

^<<v14-4-17,17>>^ Na campina do Jordão os fundiu o rei, na terra argilosa entre Sucote e Zeredá.

[[v14-4-18]]

^<<v14-4-18,18>>^ Salomão fez todos estes vasos em grande abundância, de sorte que o peso do bronze não se podia averiguar.

[[v14-4-19]]

^<<v14-4-19,19>>^ Assim fez Salomão todos os vasos que eram para a casa de Deus, o altar de ouro, as mesas para os pães da proposição,

[[v14-4-20]]

^<<v14-4-20,20>>^ os castiçais com as suas lâmpadas, de ouro puro, para arderem perante o oráculo, segundo a ordenança;

[[v14-4-21]]

^<<v14-4-21,21>>^ as flores, as lâmpadas e as tenazes, de ouro puríssimo,

[[v14-4-22]]

^<<v14-4-22,22>>^ como também as espevitadeiras, as bacias, as colheres e os braseiros, de ouro puro. Quanto à entrada da casa, tanto as portas internas, do lugar santíssimo, como as portas da casa, isto é, do santuário, eram de ouro.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]