include::./index.adoc[]

[[v14-18-0]]
=== 2 Crônicas, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-18-1]]

^<<v14-18-1,1>>^ Tinha, pois, Jeosafá riquezas e glória em abundância, e aparentou-se com Acabe.

[[v14-18-2]]

^<<v14-18-2,2>>^ Ao cabo de alguns anos foi ter com Acabe em Samária. E Acabe matou ovelhas e bois em abundância, para ele e para o povo que o acompanhava; e o persuadiu a subir com ele a Ramote-Gileade.

[[v14-18-3]]

^<<v14-18-3,3>>^ Perguntou Acabe, rei de Israel, a Jeosafá, rei de Judá: Irás tu comigo a Ramote-Gileade? E respondeu-lhe Jeosafá: Como tu és sou eu, e o meu povo como o teu povo; seremos contigo na guerra.

[[v14-18-4]]

^<<v14-18-4,4>>^ Disse mais Jeosafá ao rei de Israel: Consulta hoje a palavra do Senhor.

[[v14-18-5]]

^<<v14-18-5,5>>^ Então o rei de Israel ajuntou os profetas, quatrocentos homens, e lhes perguntou: Iremos à peleja contra Ramote-Gileade, ou deixarei de ir? Responderam eles: Sobe, porque Deus a entregará nas mãos do rei.

[[v14-18-6]]

^<<v14-18-6,6>>^ Disse, porém, Jeosafá: Não há aqui ainda algum profeta do Senhor a quem possamos consultar?

[[v14-18-7]]

^<<v14-18-7,7>>^ Ao que o rei de Israel respondeu a Jeosafá: Ainda há um homem por quem podemos consultar ao Senhor; eu, porém, o odeio, porque nunca profetiza o bem a meu respeito, mas sempre o mal; é Micaías, filho de Inlá. Mas Jeosafá disse: Não fale o rei assim.

[[v14-18-8]]

^<<v14-18-8,8>>^ Então o rei de Israel chamou um eunuco, e disse: Traze aqui depressa Micaías, filho de Inlá.

[[v14-18-9]]

^<<v14-18-9,9>>^ Ora, o rei de Israel e Jeosafá, rei de Judá, vestidos de seus trajes reais, estavam assentados cada um no seu trono, na praça à entrada da porta de Samária; e todos os profetas profetizavam diante deles.

[[v14-18-10]]

^<<v14-18-10,10>>^ E Zedequias, filho de Quenaaná, fez para si uns chifres de ferro, e disse: Assim diz o Senhor: Com estes ferirás os sírios, até que sejam consumidos.

[[v14-18-11]]

^<<v14-18-11,11>>^ E todos os profetas profetizavam o mesmo, dizendo: Sobe a Ramote-Gileade, e serás bem sucedido, pois o Senhor a entregará nas mãos do rei.

[[v14-18-12]]

^<<v14-18-12,12>>^ O mensageiro que fora chamar Micaías lhe falou, dizendo: Eis que as palavras dos profetas, a uma voz, são favoráveis ao rei: seja, pois, também a tua palavra como a de um deles, e fala o que é bom.

[[v14-18-13]]

^<<v14-18-13,13>>^ Micaías, porém, disse: Vive o Senhor, que o que meu Deus me disser, isso falarei.

[[v14-18-14]]

^<<v14-18-14,14>>^ Quando ele chegou à presença do rei, este lhe disse: Micaías, iremos a Ramote-Gileade à peleja, ou deixarei de ir? Respondeu ele: Subi, e sereis bem sucedidos; e eles serão entregues nas vossas mãos.

[[v14-18-15]]

^<<v14-18-15,15>>^ Mas o rei lhe disse: Quantas vezes hei de conjurar-te que não me fales senão a verdade em nome do Senhor?

[[v14-18-16]]

^<<v14-18-16,16>>^ Respondeu ele: Vi todo o Israel disperso pelos montes, como ovelhas que não têm pastor; e disse o Senhor: Estes não têm senhor; torne em paz cada um para sua casa.

[[v14-18-17]]

^<<v14-18-17,17>>^ Então o rei de Israel disse a Jeosafá: Não te disse eu que ele não profetizaria a respeito de mim o bem, porém o mal?

[[v14-18-18]]

^<<v14-18-18,18>>^ Prosseguiu Micaías: Ouvi, pois, a palavra do Senhor! Vi o Senhor assentado no seu trono, e todo o exército celestial em pé à sua direita e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ E o Senhor perguntou: Quem induzirá Acabe, rei de Israel, a subir, para que caia em Ramote-Gileade? E um respondia de um modo, e outro de outro.

[[v14-18-20]]

^<<v14-18-20,20>>^ Então saiu um espírito, apresentou-se diante do Senhor, e disse: Eu o induzirei. Perguntou-lhe o Senhor: De que modo?

[[v14-18-21]]

^<<v14-18-21,21>>^ E ele disse: Eu sairei, e serei um espírito mentiroso na boca de todos os seus profetas. Ao que disse o Senhor. Tu o induzirás, e prevalecerás; sai, e faze assim.

[[v14-18-22]]

^<<v14-18-22,22>>^ Agora, pois, eis que o Senhor pôs um espírito mentiroso na boca destes teus profetas; o Senhor é quem falou o mal a respeito de ti.

[[v14-18-23]]

^<<v14-18-23,23>>^ Então Zedequias, filho de Quenaaná, chegando-se, feriu a Micaías na face e disse: Por que caminho passou de mim o Espírito do Senhor para falar a ti?

[[v14-18-24]]

^<<v14-18-24,24>>^ Respondeu Micaías: Eis que tu o verás naquele dia, quando entrares numa câmara interior para te esconderes.

[[v14-18-25]]

^<<v14-18-25,25>>^ Então disse o rei de Israel: Tomai Micaías, e tornai a levá-lo a Amom, o governador da cidade, e a Joás, filho do rei,

[[v14-18-26]]

^<<v14-18-26,26>>^ dizendo-lhes: Assim diz o rei: Metei este homem no cárcere, e sustentai-o a pão e água até que eu volte em paz.

[[v14-18-27]]

^<<v14-18-27,27>>^ Mas disse Micaías: se tu voltares em paz, o Senhor não tem falado por mim. Disse mais: Ouvi, povos todos!

[[v14-18-28]]

^<<v14-18-28,28>>^ Subiram, pois, o rei de Israel e Jeosafá, rei de Judá, a Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ E disse o rei de Israel a Jeosafá: Eu me disfarçarei, e entrarei na peleja; tu, porém, veste os teus trajes reais. Disfarçou-se, pois, o rei de Israel, e eles entraram na peleja.

[[v14-18-30]]

^<<v14-18-30,30>>^ Ora, o rei da Síria dera ordens aos capitães dos seus carros, dizendo: Não pelejareis nem contra pequeno nem contra grande, senão só contra o rei de Israel.

[[v14-18-31]]

^<<v14-18-31,31>>^ Pelo que os capitães dos carros, quando viram a Jeosafá, disseram: Este é o rei de Israel. Viraram-se, pois, para pelejar contra ele; mas Jeosafá clamou, e o Senhor o socorreu, e os desviou dele.

[[v14-18-32]]

^<<v14-18-32,32>>^ Pois vendo os capitães dos carros que não era o rei de Israel, deixaram de segui-lo.

[[v14-18-33]]

^<<v14-18-33,33>>^ Então um homem entesou e seu arco e, atirando a esmo, feriu o rei de Israel por entre a couraça e a armadura abdominal. Pelo que ele disse ao carreteiro: Dá volta, e tira-me do exército, porque estou gravemente ferido.

[[v14-18-34]]

^<<v14-18-34,34>>^ E a peleja tornou-se renhida naquele dia; contudo o rei de Israel foi sustentado no carro contra os sírios até a tarde; porém ao pôr do sol morreu.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]