include::./index.adoc[]

[[v14-34-0]]
=== 2 Crônicas, 34
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-34-1]]

^<<v14-34-1,1>>^ Tinha Josias oito anos quando começou a reinar, e reinou trinta e um anos em Jerusalém.

[[v14-34-2]]

^<<v14-34-2,2>>^ Fez o que era reto aos olhos do Senhor, e andou nos caminhos de Davi, seu pai, sem se desviar deles nem para a direita nem para a esquerda.

[[v14-34-3]]

^<<v14-34-3,3>>^ Pois no oitavo ano do seu reinado, sendo ainda moço, começou a buscar o Deus de Davi, seu pai; e no duodécimo ano começou a purificar Judá e Jerusalém, dos altos, dos aserins e das imagens esculpidas e de fundição.

[[v14-34-4]]

^<<v14-34-4,4>>^ Foram derribados na presença dele os altares dos baalins; e ele derribou os altares de incenso que estavam acima deles; os aserins e as imagens esculpidas e de fundição ele os quebrou e reduziu a pó, que espargiu sobre as sepulturas dos que lhes tinham sacrificado.

[[v14-34-5]]

^<<v14-34-5,5>>^ E os ossos dos sacerdotes queimou sobre os seus altares; e purificou Judá e Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ E nas cidades de Manassés, de Efraim, de Simeão e ainda até Naftali, em seus lugares assolados ao redor,

[[v14-34-7]]

^<<v14-34-7,7>>^ derribou os altares, reduziu a pó os aserins e as imagens esculpidas, e cortou todos os altares de incenso por toda a terra de Israel. Então, voltou para Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ No décimo oitavo ano do seu reinado, havendo já purificado a terra e a casa, ele enviou Safã, filho de Azalias, Maaséias, o governador da cidade, e Joá, filho de Joacaz, o cronista, para repararem a casa do Senhor seu Deus.

[[v14-34-9]]

^<<v14-34-9,9>>^ E foram ter com Hilquias, o sumo sacerdote, e entregaram o dinheiro que se tinha trazido à casa de Deus, e que os levitas, guardas da entrada, tinham recebido da mão de Manassés, de Efraim e de todo o resto de Israel, como também, de todo o Judá e Benjamim, e dos habitantes de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ E eles o entregaram nas mãos dos oficiais que eram superintendentes da casa do Senhor; estes o deram aos que faziam a obra e que trabalhavam na casa do Senhor, para consertarem e repararem a casa.

[[v14-34-11]]

^<<v14-34-11,11>>^ Deram-no aos carpinteiros e aos edificadores, a fim de comprarem pedras lavradas, e madeiras para as junturas e para servirem de vigas para as casas que os reis de Judá tinham destruído.

[[v14-34-12]]

^<<v14-34-12,12>>^ E os homens trabalhavam fielmente na obra; e os superintendentes sobre eles eram Jaate e Obadias, levitas, dos filhos de Merári, como também Zacarias e Mesulão, dos filhos dos coatitas, para adiantarem a obra; e todos os levitas que eram entendidos em instrumentos de música.

[[v14-34-13]]

^<<v14-34-13,13>>^ Estavam sobre os carregadores e dirigiam todos os que trabalhavam em qualquer sorte de serviço; também dentre os levitas eram os escrivães, os oficiais e os porteiros.

[[v14-34-14]]

^<<v14-34-14,14>>^ Ora, quando estavam tirando o dinheiro que se tinha trazido à casa do Senhor, Hilquias, o sacerdote, achou o livro da lei do Senhor dada por intermédio de Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ Disse Hilquias a Safã, o escrivão: Achei o livro da lei na casa do Senhor. E entregou o livro a Safã.

[[v14-34-16]]

^<<v14-34-16,16>>^ Safã levou o livro ao rei, e deu conta também ao rei, dizendo: Teus servos estão fazendo tudo quanto se lhes encomendou.

[[v14-34-17]]

^<<v14-34-17,17>>^ Tomaram o dinheiro que se achou na casa do Senhor, e o entregaram nas mãos dos superintendentes e nas mãos dos que fazem a obra.

[[v14-34-18]]

^<<v14-34-18,18>>^ Safã, o escrivão, falou ainda ao rei, dizendo: O sacerdote Hilquias entregou-me um livro. E Safã leu nele perante o rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Quando o rei ouviu as palavras da lei, rasgou as suas vestes.

[[v14-34-20]]

^<<v14-34-20,20>>^ E o rei ordenou a Hilquias, a Aicão, filho de Safã, a Abdom, filho de Mica, a Safã, o escrivão, e a Asaías, servo do rei, dizendo:

[[v14-34-21]]

^<<v14-34-21,21>>^ Ide, consultai ao Senhor por mim e pelos que restam em Israel e em Judá, sobre as palavras deste livro que se achou; pois grande é o furor do Senhor que se tem derramado sobre nos por não terem os nossos pais guardado a palavra do Senhor, para fazerem conforme tudo quanto está escrito neste livro.

[[v14-34-22]]

^<<v14-34-22,22>>^ Então Hilquias e os enviados do rei foram ter com a profetisa Hulda, mulher de Salum, filho de Tocate, filho de Hasra, o guarda das vestiduras &#123;ela habitava então em Jerusalém na segunda parte&#125;; e lhe falaram a esse respeito.

[[v14-34-23]]

^<<v14-34-23,23>>^ E ela lhes respondeu: Assim diz o Senhor, Deus de Israel: Dizei ao homem que vos enviou a mim:

[[v14-34-24]]

^<<v14-34-24,24>>^ Assim diz o Senhor: Eis que trarei o mal sobre este lugar, e sobre os seus habitantes, a saber, todas as maldições que estão escritas no livro que se leu perante o rei de Judá.

[[v14-34-25]]

^<<v14-34-25,25>>^ Porque me deixaram, e queimaram incenso a outros deuses, para me provocarem à ira com todas as obras das suas mãos; portanto o meu furor se derramará sobre este lugar, e não se apagará.

[[v14-34-26]]

^<<v14-34-26,26>>^ Todavia ao rei de Judá, que vos enviou para consultar ao Senhor, assim lhe direis: Assim diz o Senhor, Deus de Israel: Quanto às palavras que ouviste,

[[v14-34-27]]

^<<v14-34-27,27>>^ porquanto o teu coração se enterneceu, e te humilhaste perante Deus, ouvindo as suas palavras contra este lugar e contra os seus habitantes, e te humilhaste perante mim, e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi, diz o Senhor.

[[v14-34-28]]

^<<v14-34-28,28>>^ Eis que te ajuntarei a teus pais, e tu serás recolhido ao teu sepulcro em paz, e os teus olhos não verão todo o mal que hei de trazer sobre este lugar e sobre os seus habitantes. E voltaram com esta resposta ao rei.

[[v14-34-29]]

^<<v14-34-29,29>>^ Então o rei mandou reunir todos os anciãos de Judá e de Jerusalém;

[[v14-34-30]]

^<<v14-34-30,30>>^ e o rei subiu à casa do Senhor, com todos os homens de Judá, e os habitantes de Jerusalém, e os sacerdotes, e os levitas, e todo o povo, desde o menor até o maior; e ele leu aos ouvidos deles todas as palavras do livro do pacto, que fora encontrado na casa do Senhor.

[[v14-34-31]]

^<<v14-34-31,31>>^ E o rei pôs-se em pé em seu lugar, e fez um pacto perante o Senhor, de andar após o Senhor, e de guardar os seus mandamentos, e os seus testemunhos, e os seus estatutos, de todo o coração e de toda a alma, a fim de cumprir as palavras do pacto, que estavam escritas naquele livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ Também fez com que todos quantos se achavam em Jerusalém e em Benjamim o firmassem; e os habitantes de Jerusalém fizeram conforme o pacto de Deus, do Deus de seus pais.

[[v14-34-33]]

^<<v14-34-33,33>>^ E Josias tirou todas as abominações de todas as terras que eram dos filhos de Israel; e ainda fez que todos quantos se achavam em Israel servissem ao Senhor seu Deus. E, enquanto ele viveu, não deixaram de seguir ao Senhor, Deus de seus pais.

'''

xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]