include::./index.adoc[]

[[v14-27-0]]
=== 2 Crônicas, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-27-1]]

^<<v14-27-1,1>>^ Tinha Jotão vinte e cinco anos quando começou a reinar, e reinou dezesseis anos em Jerusalém. E o nome de sua mãe era Jerusa, filha de Zadoque,

[[v14-27-2]]

^<<v14-27-2,2>>^ Ele fez o que era reto aos olhos do Senhor, conforme tudo o que fizera Uzias, seu pai; todavia não invadiu o templo do Senhor. Mas o povo ainda se corrompia.

[[v14-27-3]]

^<<v14-27-3,3>>^ Ele construiu a porta superior da casa do Senhor, e edificou extensivamente sobre o muro de Ofel.

[[v14-27-4]]

^<<v14-27-4,4>>^ Também edificou cidades na região montanhosa de Judá, e castelos e torres nos bosques.

[[v14-27-5]]

^<<v14-27-5,5>>^ Guerreou contra o rei dos amonitas e prevaleceu sobre eles; de modo que os amonitas naquele ano lhe deram cem talentos de prata, dez mil coros de trigo e dez mil de cevada. Isso lhe trouxeram os amonitas também no segundo e no terceiro ano.

[[v14-27-6]]

^<<v14-27-6,6>>^ Assim Jotão se tornou poderoso, porque dirigiu os seus caminhos na presença do Senhor seu Deus.

[[v14-27-7]]

^<<v14-27-7,7>>^ Ora, o restante dos atos de Jotão, e todas as suas guerras e os seus caminhos, eis que estão escritos no livro dos reis de Israel e de Judá.

[[v14-27-8]]

^<<v14-27-8,8>>^ Tinha vinte e cinco anos quando começou a reinar, e reinou dezesseis anos em Jerusalém.

[[v14-27-9]]

^<<v14-27-9,9>>^ E Jotão dormiu com seus pais, e o sepultaram na cidade de Davi. E Acaz, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[&#60; Capítulo Anterior] | <<v14-27-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[Próximo Capítulo &#62;]