include::./index.adoc[]

[[v14-32-0]]
=== 2 Crônicas, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-32-1]]

^<<v14-32-1,1>>^ Depois destas coisas e destes atos de fidelidade, veio Senaqueribe, rei da Assíria e, entrando em Judá, acampou-se contra as cidades fortes, a fim de apoderar-se delas.

[[v14-32-2]]

^<<v14-32-2,2>>^ Quando Ezequias viu que Senaqueribe tinha vindo com o propósito de guerrear contra Jerusalém,

[[v14-32-3]]

^<<v14-32-3,3>>^ teve conselho com os seus príncipes e os seus poderosos, para que se tapassem as fontes das águas que havia fora da cidade; e eles o ajudaram.

[[v14-32-4]]

^<<v14-32-4,4>>^ Assim muito povo se ajuntou e tapou todas as fontes, como também o ribeiro que corria pelo meio da terra, dizendo: Por que viriam os reis da Assíria, e achariam tantas águas?

[[v14-32-5]]

^<<v14-32-5,5>>^ Ezequias, cobrando ânimo, edificou todo o muro que estava demolido, levantando torres sobre ele, fez outro muro por fora, fortificou a Milo na cidade de Davi, e fez armas e escudos em abundância.

[[v14-32-6]]

^<<v14-32-6,6>>^ Então pôs oficiais de guerra sobre o povo e, congregando-os na praça junto à porta da cidade, falou-lhes ao coração, dizendo:

[[v14-32-7]]

^<<v14-32-7,7>>^ Sede corajosos, e tende bom ânimo; não temais, nem vos espanteis, por causa do rei da Assíria, nem por causa de toda a multidão que está com ele, pois há conosco um maior do que o que está com ele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Com ele está um braço de carne, mas conosco o Senhor nosso Deus, para nos ajudar e para guerrear por nós. E o povo descansou nas palavras de Ezequias, rei de Judá.

[[v14-32-9]]

^<<v14-32-9,9>>^ Depois disso Senaqueribe, rei da Assíria, enquanto estava diante de Laquis, com todas as suas forças, enviou os seus servos a Jerusalém a Ezequias, rei de Judá, e a todo o Judá que estava em Jerusalém, dizendo:

[[v14-32-10]]

^<<v14-32-10,10>>^ Assim diz Senaqueribe, rei da Assíria: Em que confiais vós, para vos deixardes sitiar em Jerusalém?

[[v14-32-11]]

^<<v14-32-11,11>>^ Porventura não vos engana Ezequias, para vos fazer morrer à fome e à sede, quando diz: O Senhor nosso Deus nos livrará das mãos do rei da Assíria?

[[v14-32-12]]

^<<v14-32-12,12>>^ Esse mesmo Ezequias não lhe tirou os altos e os altares, e não ordenou a Judá e a Jerusalém, dizendo: Diante de um só altar adorareis, e sobre ele queimareis incenso?

[[v14-32-13]]

^<<v14-32-13,13>>^ Não sabeis vós o que eu e meus pais temos feito a todos os povos de outras terras? Puderam de qualquer maneira os deuses das nações daquelas terras livrar a sua terra da minha mão?

[[v14-32-14]]

^<<v14-32-14,14>>^ Qual é, de todos os deuses daquelas nações que meus pais destruíram, o que pôde livrar o seu povo da minha mão, para que o vosso Deus vos possa livrar da minha mão?

[[v14-32-15]]

^<<v14-32-15,15>>^ Agora, pois, não vos engane Ezequias, nem vos incite assim, nem lhe deis crédito. Porque nenhum deus de nação alguma, nem de reino algum, pôde livrar o seu povo da minha mão, nem da mão de meus pais; quanto menos o vosso Deus vos poderá livrar da minha mão?

[[v14-32-16]]

^<<v14-32-16,16>>^ E os servos de Senaqueribe falaram ainda mais contra o Senhor Deus, e contra o seu servo Ezequias.

[[v14-32-17]]

^<<v14-32-17,17>>^ Ele também escreveu cartas para blasfemar do Senhor Deus de Israel, dizendo contra ele: Assim como os deuses das nações das terras não livraram o seu povo da minha mão, assim também o Deus de Ezequias não livrará o seu povo da minha mão.

[[v14-32-18]]

^<<v14-32-18,18>>^ E clamaram em alta voz, na língua dos judeus, ao povo de Jerusalém que estava em cima do muro, para os atemorizarem e os perturbarem, a fim de tomarem a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ E falaram do Deus de Jerusalém como dos deuses dos povos da terra, que são obras das mãos dos homens.

[[v14-32-20]]

^<<v14-32-20,20>>^ Mas o rei Ezequias e o profeta Isaías, filho de Amoz, oraram por causa disso, e clamaram ao céu.

[[v14-32-21]]

^<<v14-32-21,21>>^ Então o Senhor enviou um anjo que destruiu no arraial do rei da Assíria todos os guerreiros valentes, e os príncipes, e os chefes. Ele, pois, envergonhado voltou para a sua terra; e, quando entrou na casa de seu deus, alguns dos seus próprios filhos o mataram ali à espada.

[[v14-32-22]]

^<<v14-32-22,22>>^ Assim o Senhor salvou Ezequias, e os moradores de Jerusalém, da mão de Senaqueribe, rei da Assíria, e da mão de todos; e lhes deu descanso de todos os lados.

[[v14-32-23]]

^<<v14-32-23,23>>^ E muitos trouxeram presentes a Jerusalém ao Senhor, e coisas preciosas a Ezequias, rei de Judá, de modo que desde então ele foi exaltado perante os olhos de todas as nações.

[[v14-32-24]]

^<<v14-32-24,24>>^ Naqueles dias Ezequias, adoecendo, estava à morte: e orou ao Senhor o qual lhe respondeu, e lhe deu um sinal.

[[v14-32-25]]

^<<v14-32-25,25>>^ Mas Ezequias não correspondeu ao benefício que lhe fora feito, pois o seu coração se exaltou; pelo que veio grande ira sobre ele, e sobre Judá e Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ Todavia Ezequias humilhou-se pela soberba do seu coração, ele e os habitantes de Jerusalém; de modo que a grande ira do Senhor não veio sobre eles nos dias de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ E teve Ezequias riquezas e honra em grande abundância; proveu-se de tesourarias para prata, ouro, pedras preciosas, especiarias, escudos, e toda espécie de objetos desejáveis;

[[v14-32-28]]

^<<v14-32-28,28>>^ também de celeiros para o aumento de trigo, de vinho, e de azeite; e de estrebarias para toda a casta de animais, e de currais para os rebanhos.

[[v14-32-29]]

^<<v14-32-29,29>>^ Além disso edificou para si cidades, e teve rebanhos e manadas em abundância; pois Deus lhe tinha dado muitíssima fazenda.

[[v14-32-30]]

^<<v14-32-30,30>>^ Também foi Ezequias quem tapou o manancial superior das águas de Giom, fazendo-as correr em linha reta pelo lado ocidental da cidade de Davi. Ezequias, pois, prosperou em todas as suas obras.

[[v14-32-31]]

^<<v14-32-31,31>>^ Contudo, no negócio dos embaixadores dos príncipes de Babilônia, que lhe foram enviados a perguntarem acerca do prodígio que fora feito na sua terra, Deus o desamparou para experimentá-lo, e para saber tudo o que havia no seu coração.

[[v14-32-32]]

^<<v14-32-32,32>>^ Ora, o restante dos atos de Ezequias, e as suas boas obras, eis que estão escritos na visão do profeta Isaías, filho de Amoz, no livro dos reis de Judá e de Israel.

[[v14-32-33]]

^<<v14-32-33,33>>^ E Ezequias dormiu com seus pais, e o sepultaram no mais alto dos sepulcros dos filhos de Davi; e todo o Judá e os habitantes de Jerusalém lhe renderam honras na sua morte. E Manassés, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]