include::./index.adoc[]

[[v14-2-0]]
=== 2 Crônicas, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-2-1]]

^<<v14-2-1,1>>^ Ora, resolveu Salomão edificar uma casa ao nome do Senhor, como também uma casa real para si.

[[v14-2-2]]

^<<v14-2-2,2>>^ Designou, pois, Salomão setenta mil homens para servirem de carregadores, e oitenta mil para cortarem pedras na montanha, e três mil e seiscentos inspetores sobre eles.

[[v14-2-3]]

^<<v14-2-3,3>>^ E Salomão mandou dizer a Hurão, rei de Tiro: Como fizeste com Davi, meu pai, mandando-lhe cedros para edificar uma casa em que morasse, assim também fazem comigo.

[[v14-2-4]]

^<<v14-2-4,4>>^ Eis que vou edificar uma casa ao nome do Senhor meu Deus e lha consagrar para queimar perante ele incenso aromático, para apresentar continuamente, o pão da preposição, e para oferecer os holocaustos da manhã e da tarde, nos sábados, nas luas novas e nas festas fixas do Senhor nosso Deus; o que é obrigação perpétua de Israel.

[[v14-2-5]]

^<<v14-2-5,5>>^ A casa que vou edificar há de ser grande, porque o nosso Deus é maior do que todos os deuses.

[[v14-2-6]]

^<<v14-2-6,6>>^ Mas quem é capaz de lhe edificar uma casa, visto que o céu e até o céu dos céus o não podem conter? E quem sou eu, para lhe edificar uma casa, a não ser para queimar incenso perante ele?

[[v14-2-7]]

^<<v14-2-7,7>>^ Agora, pois, envia-me um homem hábil para trabalhar em ouro, em prata, em bronze, em ferro, em púrpura, em carmesim, e em azul, e que saiba lavrar ao buril, para estar com os peritos que estão comigo em Judá e em Jerusalém, os quais Davi, meu pai, escolheu.

[[v14-2-8]]

^<<v14-2-8,8>>^ Manda-me também madeiras de cedro, de cipreste, e de algumins do Líbano; porque bem sei eu que os teus servos sabem cortar madeira no Líbano; e eis que os meus servos estarão com os teus servos,

[[v14-2-9]]

^<<v14-2-9,9>>^ a fim de me prepararem madeiras em abundância, porque a casa que vou edificar há de ser grande e maravilhosa.

[[v14-2-10]]

^<<v14-2-10,10>>^ E aos teus servos, os trabalhadores que cortarem a madeira, darei vinte mil coros de trigo malhado, vinte mil coros de cevada, vinte mil batos de vinho e vinte mil batos de azeite.

[[v14-2-11]]

^<<v14-2-11,11>>^ Hurão, rei de Tiro, mandou por escrito resposta a Salomão, dizendo: Porquanto o Senhor ama o seu povo, te constituiu rei sobre ele.

[[v14-2-12]]

^<<v14-2-12,12>>^ Disse mais Hurão: Bendito seja o Senhor Deus de Israel, que fez o céu e a terra, que deu ao rei Davi um filho sábio, de grande prudência e entendimento para edificar uma casa ao Senhor, e uma casa real para si.

[[v14-2-13]]

^<<v14-2-13,13>>^ Agora, pois, envio um homem perito, de entendimento, a saber, Hurão-Abi,

[[v14-2-14]]

^<<v14-2-14,14>>^ filho duma mulher das filhas de Dã, e cujo pai foi um homem de Tiro; este sabe trabalhar em ouro, em prata, em bronze, em ferro, em pedras e em madeira, em púrpura, em azul, em linho fino, e em carmesim, e é hábil para toda obra de buril, e para toda espécie de engenhosas invenções; para que lhe seja designado um lugar juntamente com os teus peritos, e com os peritos de teu pai Davi, meu senhor.

[[v14-2-15]]

^<<v14-2-15,15>>^ Agora mande meu senhor para os seus servos o trigo, a cevada, o azeite, e o vinho, de que falou;

[[v14-2-16]]

^<<v14-2-16,16>>^ e nós cortaremos tanta madeira do Líbano quanta precisares, e a levaremos em jangadas pelo mar até Jope, e tu mandarás transportá-la para Jerusalém.

[[v14-2-17]]

^<<v14-2-17,17>>^ Salomão contou todos os estrangeiros que havia na terra de Israel, segundo o recenseamento que seu pai Davi fizera; e acharam-se cento e cinqüenta e três mil e seiscentos.

[[v14-2-18]]

^<<v14-2-18,18>>^ E deles separou setenta mil para servirem de carregadores, e oitenta mil para cortarem madeira na montanha, como também três mil e seiscentos inspetores para fazerem trabalhar o povo.

'''

xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[Próximo Capítulo &#62;]