include::./index.adoc[]

[[v14-22-0]]
=== 2 Crônicas, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-22-1]]

^<<v14-22-1,1>>^ Então os habitantes de Jerusalém fizeram reinar em seu lugar Acazias, seu filho mais moço, porque a tropa que viera com os árabes ao arraial tinha matado todos os mais velhos. Assim reinou Acazias, filho de Jeorão, rei de Judá.

[[v14-22-2]]

^<<v14-22-2,2>>^ Tinha quarenta e dois anos quando começou a reinar, e reinou um ano em Jerusalém. E o nome de sua mãe era Atalia, filha de Onri.

[[v14-22-3]]

^<<v14-22-3,3>>^ Ele também andou nos caminhos da casa de Acabe, porque sua mãe era sua conselheira para proceder impiamente.

[[v14-22-4]]

^<<v14-22-4,4>>^ E fez o que era mau aos olhos do Senhor, como fez a casa de Acabe; porque eles eram seus conselheiros depois da morte de seu pai, para sua perdição.

[[v14-22-5]]

^<<v14-22-5,5>>^ Andando nos conselhos deles foi com Jorão, filho de Acabe, rei de Israel, a guerrear contra Hazael, rei da Síria, junto a Ramote-Gileade; e os sírios feriram Jorão,

[[v14-22-6]]

^<<v14-22-6,6>>^ o qual voltou para curar-se em Jizreel das feridas que lhe fizeram em Ramá, quando ele pelejava contra Hazael, rei da Síria. E Acazias, filho de Jeorão, rei de Judá, desceu para visitar Jorão, filho de Acabe, em Jizreel, por estar ele doente.

[[v14-22-7]]

^<<v14-22-7,7>>^ Foi por vontade de Deus que Acazias, para sua ruína visitou Jorão; pois, quando chegou, saiu com Jorão contra Jeú, filho de Ninsi, a quem o Senhor tinha ungido para exterminar a casa de Acabe.

[[v14-22-8]]

^<<v14-22-8,8>>^ E quando Jeú executava juízo contra a casa de Acabe, achou os príncipes de Judá e os filhos dos irmãos de Acazias, que o serviam, e os matou.

[[v14-22-9]]

^<<v14-22-9,9>>^ Depois buscou a Acazias, o qual foi preso quando se escondia em Samária, trouxeram-no a Jeú e o mataram. Então o sepultaram, pois disseram: É filho de Jeosafá, que buscou ao Senhor de toda o seu coração. E já não tinha a casa de Acazias ninguém que fosse capaz de reinar.

[[v14-22-10]]

^<<v14-22-10,10>>^ Vendo Atalia, mãe de Acazias, que seu filho era morto, levantou-se e destruiu toda a estirpe real da casa de Judá.

[[v14-22-11]]

^<<v14-22-11,11>>^ Mas Jeosabeate, filha do rei, tomou Joás, filho de Acazias, e o furtou dentre os filhos do rei, que estavam para ser mortos, e o pôs com a sua ama na câmara dos leitos. Assim Jeosabeate, filha do rei Jeorão, mulher do sacerdote Jeoiada e irmã de Acazias, o escondeu de Atalia, de modo que ela não o matou.

[[v14-22-12]]

^<<v14-22-12,12>>^ E esteve com eles seis anos, escondido na casa de Deus; e Atalia reinou sobre a terra.

'''

xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]