include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-13-1]]

^<<v14-13-1,1>>^ No ano décimo oitavo do rei Jeroboão começou Abias a reinar sobre Judá.

[[v14-13-2]]

^<<v14-13-2,2>>^ Três anos reinou em Jerusalém; o nome de sua mãe era Micaías, filha de Uriel de Gibeá. E houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ Abias dispôs-se para a peleja com um exército de varões valentes, quatrocentos mil homens escolhidos; e Jeroboão dispôs contra ele a batalha com oitocentos mil homens escolhidos, todos homens valentes.

[[v14-13-4]]

^<<v14-13-4,4>>^ Então Abias pôs-se em pé em cima do monte Zemaraim, que está na região montanhosa de Efraim, e disse: Ouvi-me, Jeroboão e todo o Israel:

[[v14-13-5]]

^<<v14-13-5,5>>^ Porventura não vos convém saber que o Senhor Deus de Israel deu para sempre a Davi a soberania sobre Israel, a ele e a seus filhos, por um pacto de sal?

[[v14-13-6]]

^<<v14-13-6,6>>^ Contudo levantou-se Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, e se rebelou contra seu senhor;

[[v14-13-7]]

^<<v14-13-7,7>>^ e ajuntaram-se a ele homens vadios filhos de Belial, e fortaleceram-se contra Roboão, filho de Salomão, sendo Roboão ainda moço e indeciso de coração, e não podendo resistir-lhes.

[[v14-13-8]]

^<<v14-13-8,8>>^ E agora julgais poder resistir ao reino do Senhor, que está na mão dos filhos de Davi, visto que sois uma grande multidão, e tendes convosco os bezerros de ouro que Jeroboão vos fez para deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Não lançastes fora os sacerdotes do Senhor, filhos de Arão, e os levitas, e não fizestes para vós sacerdotes, como o fazem os povos das outras terras? Qualquer que vem a consagrar-se, trazendo um novilho e sete carneiros, logo se faz sacerdote daqueles que não são deuses.

[[v14-13-10]]

^<<v14-13-10,10>>^ Mas, quanto a nós, o Senhor é nosso Deus, e nunca o deixamos. Temos sacerdotes que ministram ao Senhor, os quais são filhos de Arão, e os levitas para o seu serviço.

[[v14-13-11]]

^<<v14-13-11,11>>^ Queimam perante o Senhor cada manhã e cada tarde holocausto e incenso aromático; também dispõem os pães da proposição sobre a mesa de ouro puro, e o castiçal de ouro e as suas lâmpadas para se acenderem cada tarde; porque nós temos guardado os preceitos do Senhor nosso Deus; mas vós o deixastes.

[[v14-13-12]]

^<<v14-13-12,12>>^ Eis que Deus está conosco, à nossa frente, como também os seus sacerdotes com as trombetas, para tocarem alarme contra vós. O filhos de Israel, não pelejeis contra o Senhor Deus de vossos pais; porque não sereis bem sucedidos.

[[v14-13-13]]

^<<v14-13-13,13>>^ Jeroboão, porém, armou uma emboscada, para dar sobre Judá pela retaguarda; de maneira que as suas tropas estavam em frente de Judá e a emboscada por detrás.

[[v14-13-14]]

^<<v14-13-14,14>>^ Então os de Judá olharam para trás, e eis que tinham de pelejar por diante e pela retaguarda; então clamaram ao Senhor, e os sacerdotes tocaram as trombetas.

[[v14-13-15]]

^<<v14-13-15,15>>^ E os homens de Judá deram o brado de guerra; e sucedeu que, bradando eles, Deus feriu Jeroboão e todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ E os filhos de Israel fugiram de diante de Judá, e Deus lhos entregou nas suas mãos.

[[v14-13-17]]

^<<v14-13-17,17>>^ De maneira que Abias e o seu povo fizeram grande matança entre eles; pois que caíram mortos de Israel quinhentos mil homens escolhidos.

[[v14-13-18]]

^<<v14-13-18,18>>^ Assim foram humilhados os filhos de Israel naquele tempo, e os filhos de Judá prevaleceram, porque confiaram no Senhor Deus de seus pais.

[[v14-13-19]]

^<<v14-13-19,19>>^ E Abias foi perseguindo Jeroboão, e tomou-lhe cidades: Betel e seus arrabaldes, Jesana e seus arrabaldes, e Efrom e seus arrabaldes.

[[v14-13-20]]

^<<v14-13-20,20>>^ Jeroboão não recobrou mais a sua força nos dias de Abias; e o Senhor o feriu, e ele morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias, porém, se fortaleceu, e tomou para si catorze mulheres, e teve vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ O restante dos atos de Abias, os seus caminhos e as suas palavras, estão escritos no comentário do profeta Ido.

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]