include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-28-1]]

^<<v14-28-1,1>>^ Tinha Acaz vinte anos quando começou a reinar, e reinou dezesseis anos em Jerusalém. E não fez o que era reto aos olhos do Senhor, como Davi, seu pai;

[[v14-28-2]]

^<<v14-28-2,2>>^ mas andou nos caminhos dos reis de Israel, e até fez imagens de fundição para os baalins.

[[v14-28-3]]

^<<v14-28-3,3>>^ Também queimava incenso no vale do filho de Hinom, e queimou seus filhos no fogo, conforme as abominações das nações que o senhor expulsara de diante dos filhos de Israel.

[[v14-28-4]]

^<<v14-28-4,4>>^ E sacrificava e queimava incenso nos altos e nos outeiros, como também debaixo de toda árvore frondosa.

[[v14-28-5]]

^<<v14-28-5,5>>^ Pelo que o Senhor seu Deus o entregou na mão do rei dos sírios, os quais o derrotaram e tomaram-lhe em cativeiro grande multidão de presos, que levaram para Damasco. Foi também entregue na mão do rei de Israel, o qual lhe infligiu grande derrota,

[[v14-28-6]]

^<<v14-28-6,6>>^ pois Peca, filho de Remalias, matou em Judá, num só dia cento e vinte mil todos homens valentes; porquanto haviam abandonado o Senhor, Deus de seus pais.

[[v14-28-7]]

^<<v14-28-7,7>>^ E Zicri, varão poderoso de Efraim matou Maaséias, filho do rei, e Azricão, e mordomo, e Elcana, o segundo depois do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ E os filhos de Israel levaram cativos de seus irmãos duzentos mil, mulheres filhos e filhas; também saquearam deles grande despojo, que levaram para Samária.

[[v14-28-9]]

^<<v14-28-9,9>>^ Mas estava ali um profeta do Senhor, cujo nome era Odede, o qual saiu ao encontro do exército que vinha para Samária, e lhe disse: Eis que, irando-se o Senhor Deus de vossos pais contra Judá, os entregou na vossa mão, e vós os matastes com uma raiva que chegou até o céu.

[[v14-28-10]]

^<<v14-28-10,10>>^ E agora vós quereis sujeitar a vós os filhos de Judá e de Jerusalém, como escravos e escravas; porventura não sois vós mesmos culpados para com o Senhor vosso Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Agora, pois, ouvi-me, e tornai a enviar os cativos que trouxestes dentre vossos irmãos, pois o ardor da ira do Senhor está sobre vós.

[[v14-28-12]]

^<<v14-28-12,12>>^ Então alguns dos chefes dos efraimitas, a saber, Azarias, filho de Joanã, Berequias, filho de Mesilemote, Jeizquias, filho de Salum, e Amasa, filho de Hadlai, se levantaram contra os que voltavam da guerra,

[[v14-28-13]]

^<<v14-28-13,13>>^ e lhes disseram: Não fareis entrar aqui estes cativos; porque, além da nossa culpa contra o Senhor, o que vós quereis fazer acrescentaria mais a nossos pecados e a nossas culpas; pois já temos grande culpa, e o ardor da ira do Senhor está sobre Israel.

[[v14-28-14]]

^<<v14-28-14,14>>^ Então os homens armados deixaram os cativos e o despojo diante dos príncipes e de toda a congregação.

[[v14-28-15]]

^<<v14-28-15,15>>^ E os homens já mencionados por nome se levantaram e tomaram os cativos, e vestiram do despojo a todos os que dentre eles estavam nus; vestiram-nos, e os calçaram, e lhes deram de comer e de beber, e os ungiram; e, levando sobre jumentos todos os que estavam fracos, conduziram-nos a Jericó, a cidade das palmeiras, a seus irmãos. Depois voltaram para Samária.

[[v14-28-16]]

^<<v14-28-16,16>>^ Naquele tempo o rei Acaz mandou pedir socorro ao rei da Assíria.

[[v14-28-17]]

^<<v14-28-17,17>>^ Pois de novo os edomeus, tendo invadido Judá, a derrotaram e levaram prisioneiros.

[[v14-28-18]]

^<<v14-28-18,18>>^ Também os filisteus tinham invadido as cidades da baixada e do sul de Judá, e tinham tomado Bete-Semes, Aijalom, Gederote, Socó e suas aldeias, Timna e suas aldeias, e Ginzo e suas aldeias, estabelecendo-se ali.

[[v14-28-19]]

^<<v14-28-19,19>>^ Pois o Senhor humilhou Judá por causa do rei Acaz, porque este se houve desenfreadamente em Judá, havendo desprezado ao Senhor.

[[v14-28-20]]

^<<v14-28-20,20>>^ E veio a ele Tilgate-Pilneser, rei da Assíria, e o pôs em aperto, em vez de fortalecê-lo.

[[v14-28-21]]

^<<v14-28-21,21>>^ Pois Acaz saqueou a casa do Senhor, e a casa do rei, e dos príncipes, e deu os despojos por tributo ao rei da Assíria; porém isso não o ajudou.

[[v14-28-22]]

^<<v14-28-22,22>>^ No tempo da sua angústia houve-se com ainda maior desprezo pelo Senhor, este mesmo rei Acaz.

[[v14-28-23]]

^<<v14-28-23,23>>^ Pois sacrificou aos deuses de Damasco, que o tinham derrotado, e disse: Visto que os deuses dos reis da Síria os ajudam, portanto eu lhes sacrificarei, para que me ajudem a mim. Eles, porém, foram a ruína dele e de todo o Israel.

[[v14-28-24]]

^<<v14-28-24,24>>^ Ajuntou Acaz os utensílios da casa de Deus, fê-los em pedaços, e fechou as portas da casa do Senhor; e fez para si altares em todos os cantos de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ Também em cada cidade de Judá fez altos para queimar incenso a outros deuses, assim provocando à ira o Senhor, Deus de seus pais.

[[v14-28-26]]

^<<v14-28-26,26>>^ Ora, o restante dos seus atos e de todos os seus caminhos, desde os primeiros até os últimos, eis que está escrito no livro dos reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ E Acaz dormiu com seus pais, e o sepultaram na cidade, em Jerusalém; pois não o puseram nos sepulcros dos reis de Israel. E Ezequias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]