include::./index.adoc[]

[[v14-24-0]]
=== 2 Crônicas, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-24-1]]

^<<v14-24-1,1>>^ Tinha Joás sete anos quando começou a reinar, e reinou quarenta anos em Jerusalém. O nome de sua mãe era Zíbia, de Berseba.

[[v14-24-2]]

^<<v14-24-2,2>>^ E Joás fez o que era reto aos olhos do Senhor por todos os dias do sacerdote Jeoiada.

[[v14-24-3]]

^<<v14-24-3,3>>^ E tomou Jeoiada para ele duas mulheres, das quais teve filhos e filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ Depois disso Joás resolveu renovar a casa do Senhor.

[[v14-24-5]]

^<<v14-24-5,5>>^ Reuniu, pois, os sacerdotes e os levitas e lhes disse: Saí pelas cidades de Judá, e levantai dinheiro de todo a Israel, anualmente, para reparar a casa do vosso Deus; e vede que apresseis este negócio: contudo os levitas não o apressaram.

[[v14-24-6]]

^<<v14-24-6,6>>^ Pelo que o rei chamou Jeoiada, o chefe, e lhe perguntou: Por que não tens obrigado os levitas a trazerem de Judá e de Jerusalém o imposto ordenado por Moisés, servo do Senhor, à congregação de Israel, para a tenda do testemunho?

[[v14-24-7]]

^<<v14-24-7,7>>^ Pois os filhos de Atalia, aquela mulher ímpia, tinham arruinado a casa de Deus; e até empregaram todas as coisas sagradas da casa do Senhor no serviço dos baalins.

[[v14-24-8]]

^<<v14-24-8,8>>^ O rei, pois, deu ordem; e fizeram uma arca, e a puseram do lado de fora, à porta da casa do Senhor.

[[v14-24-9]]

^<<v14-24-9,9>>^ E publicou-se em Judá e em Jerusalém que trouxessem ao Senhor o imposto que Moisés, o servo de Deus, havia ordenado a Israel no deserto.

[[v14-24-10]]

^<<v14-24-10,10>>^ Então todos os príncipes e todo o povo se alegraram, e trouxeram o imposto e o lançaram na arca, até que ficou cheia.

[[v14-24-11]]

^<<v14-24-11,11>>^ E quando era trazida a arca pelas mãos dos levitas ao recinto do rei, na ocasião em que viam que havia muito dinheiro, vinham o escrivão do rei e o deputado do sumo sacerdote, esvaziavam a arca e, tomando-a, tornavam a levá-la ao seu lugar. Assim faziam dia após dia, e ajuntaram dinheiro em abundância.

[[v14-24-12]]

^<<v14-24-12,12>>^ E o rei e Jeoiada davam-no aos encarregados da obra da casa do Senhor; e assalariaram pedreiros e carpinteiros para renovarem a casa do Senhor, como também os que trabalhavam em ferro e em bronze para repararem a casa do Senhor.

[[v14-24-13]]

^<<v14-24-13,13>>^ Assim os encarregados da obra faziam com que o serviço da reparação progredisse nas suas mãos; e restituíram a casa de Deus a seu estado anterior, e a consolidaram.

[[v14-24-14]]

^<<v14-24-14,14>>^ Depois de acabarem a obra trouxeram ao rei e a Jeoiada o resto do dinheiro, e dele se fizeram utensílios para a casa do Senhor, para serem usados no ministério e nos holocaustos, e colheres, e vasos de ouro e de prata. E se ofereciam holocaustos continuamente na casa do Senhor, por todos os dias de Jeoiada.

[[v14-24-15]]

^<<v14-24-15,15>>^ Jeoiada, porém, envelheceu e, cheio de dias, morreu; tinha cento e trinta anos quando morreu.

[[v14-24-16]]

^<<v14-24-16,16>>^ E o sepultaram na cidade de Davi com os reis, porque tinha feito o bem em Israel, e para com Deus e sua casa.

[[v14-24-17]]

^<<v14-24-17,17>>^ E depois da morte de Jeoiada vieram os príncipes de Judá e prostraram-se diante do rei; então o rei lhes deu ouvidos.

[[v14-24-18]]

^<<v14-24-18,18>>^ E eles, abandonando a casa do Senhor, Deus de seus pais, serviram aos aserins e aos ídolos; de sorte que veio grande ira sobre Judá e Jerusalém por causa desta sua culpa.

[[v14-24-19]]

^<<v14-24-19,19>>^ Contudo Deus enviou profetas entre eles para os fazer tornar ao Senhor, os quais protestaram contra eles; mas eles não lhes deram ouvidos.

[[v14-24-20]]

^<<v14-24-20,20>>^ E o Espírito de Deus apoderou-se de Zacarias, filho do sacerdote Jeoiada, o qual se pôs em pé acima do povo, e lhes disse: Assim diz Deus: Por que transgredis os mandamentos do Senhor, de modo que não possais prosperar? Porquanto abandonastes o Senhor, também ele vos abandonou.

[[v14-24-21]]

^<<v14-24-21,21>>^ Mas conspiraram contra ele e por ordem do rei, o apedrejaram no átrio da casa do Senhor.

[[v14-24-22]]

^<<v14-24-22,22>>^ Assim o rei Joás não se lembrou da bondade que lhe fizera Jeoiada pai de Zacarias, antes matou-lhe o filho, o qual morrendo disse: Veja-o o Senhor, e o retribua.

[[v14-24-23]]

^<<v14-24-23,23>>^ Decorrido um ano, o exército da Síria subiu contra Joás; e vieram a Judá e a Jerusalém, e destruíram dentre o povo todos os seus príncipes, e enviaram todo o seu despojo ao rei de Damasco.

[[v14-24-24]]

^<<v14-24-24,24>>^ O exército dos sírios viera com poucos homens, contudo o Senhor entregou nas suas mãos um exército mui grande, porquanto abandonaram o Senhor, Deus de seus pais. Assim executaram juízo contra Joás.

[[v14-24-25]]

^<<v14-24-25,25>>^ Quando os sírios se retiraram dele, deixaram-no gravemente ferido; então seus servos conspiraram contra ele por causa do sangue dos filhos do sacerdote Jeoiada, e o mataram na sua cama, e assim morreu; e o sepultaram na cidade de Davi, porém não nos sepulcros dos reis.

[[v14-24-26]]

^<<v14-24-26,26>>^ Estes foram os que conspiraram contra ele Zabade, filho de Simeate a amonita, e Jeozabade, filho de Sinrite a moabita.

[[v14-24-27]]

^<<v14-24-27,27>>^ Ora, quanto a seus filhos, e ao grande número de oráculos pronunciados contra ele, e à restauração da casa de Deus, eis que estão escritos no comentário do livro dos reis. E Amazias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]