include::./index.adoc[]

[[v14-3-0]]
=== 2 Crônicas, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-3-1]]

^<<v14-3-1,1>>^ Então Salomão começou a edificar a casa do Senhor em Jerusalém, no monte Moriá, onde o Senhor aparecera a Davi, seu pai, no lugar que Davi tinha preparado na eira de Ornã, o jebuseu.

[[v14-3-2]]

^<<v14-3-2,2>>^ Começou a edificar no segundo dia do segundo mês, no quarto ano do seu reinado.

[[v14-3-3]]

^<<v14-3-3,3>>^ Estes foram os fundamentos que Salomão pôs para edificar a casa de Deus. O comprimento em côvados, segundo a primitiva medida, era de sessenta côvados, e a largura de vinte côvados:

[[v14-3-4]]

^<<v14-3-4,4>>^ O pórtico que estava na frente tinha vinte côvados de comprimento, correspondendo à largura da casa, e a altura era de cento e vinte; e por dentro o revestiu de ouro puro.

[[v14-3-5]]

^<<v14-3-5,5>>^ A câmara maior forrou com madeira de cipreste e a cobriu de ouro fino, no qual gravou palmas e cadeias.

[[v14-3-6]]

^<<v14-3-6,6>>^ Para ornamento guarneceu a câmara de pedras preciosas; e o ouro era ouro de Parvaim.

[[v14-3-7]]

^<<v14-3-7,7>>^ Também revestiu de ouro as traves e os umbrais, bem como as paredes e portas da câmara, e lavrou querubins nas paredes.

[[v14-3-8]]

^<<v14-3-8,8>>^ Fez também a câmara santíssima, cujo comprimento era de vinte côvados, correspondendo à largura da casa, e a sua largura era de vinte côvados; e a revestiu de ouro fino, do peso de seiscentos talentos.

[[v14-3-9]]

^<<v14-3-9,9>>^ O peso dos pregos era de cinqüenta siclos de ouro. Também revestiu de ouro os cenáculos.

[[v14-3-10]]

^<<v14-3-10,10>>^ Também fez na câmara santíssima dois querubins de madeira, e os cobriu de ouro.

[[v14-3-11]]

^<<v14-3-11,11>>^ As asas dos querubins tinham vinte côvados de comprimento: uma asa de um deles, tendo cinco côvados, tocava na parede da casa, e a outra asa, tendo também cinco côvados, tocava na asa do outro querubim;

[[v14-3-12]]

^<<v14-3-12,12>>^ também a asa deste querubim, tendo cinco côvados, tocava na parede da casa, e a outra asa, tendo igualmente cinco côvados, estava unida à asa do primeiro querubim.

[[v14-3-13]]

^<<v14-3-13,13>>^ Assim as asas destes querubins se estendiam por vinte côvados; eles estavam postos em pé, com os rostos virados para a câmara.

[[v14-3-14]]

^<<v14-3-14,14>>^ Também fez o véu de azul, púrpura, carmesim e linho fino; e fez bordar nele querubins.

[[v14-3-15]]

^<<v14-3-15,15>>^ Diante da casa fez duas colunas de trinta e cinco côvados de altura; e o capitel que estava sobre cada uma era de cinco côvados.

[[v14-3-16]]

^<<v14-3-16,16>>^ Também fez cadeias no oráculo, e as pôs sobre o alto das colunas; fez também cem romãs, as quais pôs nas cadeias.

[[v14-3-17]]

^<<v14-3-17,17>>^ E levantou as colunas diante do templo, uma à direita, e outra à esquerda; e chamou o nome da que estava à direita Jaquim, e o nome da que estava à esquerda Boaz.

'''

xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[&#60; Capítulo Anterior] | <<v14-3-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[Próximo Capítulo &#62;]