include::./index.adoc[]

[[v14-35-0]]
=== 2 Crônicas, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-35-1]]

^<<v14-35-1,1>>^ Então Josias celebrou a páscoa ao Senhor em Jerusalém; imolou-se o cordeiro da páscoa no décimo quarto dia do primeiro mês.

[[v14-35-2]]

^<<v14-35-2,2>>^ E estabeleceu os sacerdotes nos seus cargos, e os animou a servirem na casa do Senhor.

[[v14-35-3]]

^<<v14-35-3,3>>^ E disse aos levitas que ensinavam a todo o Israel e que estavam consagrados ao Senhor: Ponde a arca sagrada na casa que Salomão, filho de Davi, rei de Israel, edificou; não tereis mais esta carga sobre os vossos ombros. Agora servi ao Senhor vosso Deus e ao seu povo Israel;

[[v14-35-4]]

^<<v14-35-4,4>>^ preparai-vos segundo as vossas casas paternas, e segundo as vossas turmas, conforme o preceito de Davi, rei de Israel, e o de Salomão, seu filho.

[[v14-35-5]]

^<<v14-35-5,5>>^ E estai no lugar santo segundo as divisões das casas paternas de vossos irmãos, os filhos do povo, e haja para cada divisão uma parte de uma família levítica.

[[v14-35-6]]

^<<v14-35-6,6>>^ Também imolai a páscoa, e santificai-vos, e preparai-a para vossos irmãos, fazendo conforme a palavra do Senhor dada por intermédio de Moisés.

[[v14-35-7]]

^<<v14-35-7,7>>^ Ora, Josias deu aos filhos do povo, a todos que ali estavam, cordeiros e cabritos do rebanho em número de trinta mil, todos para os sacrifícios da páscoa, e três mil novilhos; isto era da fazenda do rei.

[[v14-35-8]]

^<<v14-35-8,8>>^ Também os seus príncipes fizeram ofertas voluntárias ao povo, aos sacerdotes e aos levitas; Hilquias, Zacarias e Jeiel, chefes da casa de Deus, deram aos sacerdotes, para os sacrifícios da páscoa, dois mil e seiscentos cordeiros e cabritos e trezentos novilhos.

[[v14-35-9]]

^<<v14-35-9,9>>^ Também Conanias, e Semaías e Netanel, seus irmãos, como também Hasabias, Jeiel e Jozabade, chefes dos levitas, apresentaram aos levitas, para os sacrifícios da páscoa, cinco mil cordeiros e cabritos e quinhentos novilhos.

[[v14-35-10]]

^<<v14-35-10,10>>^ Assim se preparou o serviço, e puseram-se os sacerdotes nos seus postos, e os levitas pelas suas turmas, conforme a ordem do rei.

[[v14-35-11]]

^<<v14-35-11,11>>^ Então imolaram a páscoa; e os sacerdotes espargiam o sangue que recebiam das mãos dos levitas, e estes esfolavam as reses.

[[v14-35-12]]

^<<v14-35-12,12>>^ E puseram à parte os holocaustos para os distribuírem aos filhos do povo, segundo as divisões das casas paternas, a fim de que os oferecessem ao Senhor, como está escrito no livro de Moisés; e assim fizeram com os novilhos.

[[v14-35-13]]

^<<v14-35-13,13>>^ Assaram a páscoa ao fogo, segundo a ordenança; e as ofertas sagradas cozeram em panelas em caldeirões e em tachos, e prontamente as repartiram entre todo o povo.

[[v14-35-14]]

^<<v14-35-14,14>>^ Depois prepararam o que era preciso para si e para os sacerdotes; porque os sacerdotes, filhos de Arão, se ocuparam até a noite em oferecer os holocaustos e a gordura; pelo que os levitas prepararam para si e para os sacerdotes, filhos de Arão.

[[v14-35-15]]

^<<v14-35-15,15>>^ Os cantores, filhos de Asafe, estavam no seu posto, segundo o mandado de Davi, de Asafe, de Hemã e de Jedútum vidente do rei; como também os porteiros estavam a cada porta; não precisaram se desviar do seu serviço, porquanto seus irmãos, os levitas preparavam o necessário para eles.

[[v14-35-16]]

^<<v14-35-16,16>>^ Assim se estabeleceu todo o serviço do Senhor naquele dia, para celebrar a páscoa, e para oferecer holocaustos sobre o altar do Senhor, segundo a ordem do rei Josias.

[[v14-35-17]]

^<<v14-35-17,17>>^ E os filhos de Israel que ali estavam celebraram a páscoa naquela ocasião e, durante sete dias, a festa dos pães ázimos.

[[v14-35-18]]

^<<v14-35-18,18>>^ Nunca se celebrara em Israel uma páscoa semelhante a essa, desde os dias do profeta Samuel; e nenhum dos reis de Israel celebrara tal páscoa como a que Josias celebrou com os sacerdotes e levitas, e todo o Judá e Israel que ali estavam, e os habitantes de Jerusalém.

[[v14-35-19]]

^<<v14-35-19,19>>^ Foi no décimo oitavo ano do reinado de Josias que se celebrou esta páscoa.

[[v14-35-20]]

^<<v14-35-20,20>>^ Depois de tudo isso, havendo Josias já preparado o templo, subiu Neco, rei do Egito, para guerrear contra Carquêmis, junto ao Eufrates; e Josias lhe saiu ao encontro.

[[v14-35-21]]

^<<v14-35-21,21>>^ Neco, porém, mandou-lhe mensageiros, dizendo: Que tenho eu que fazer contigo, rei de Judá? Não é contra ti que venho hoje, mas contra a casa à qual faço guerra; e Deus mandou que me apressasse. Deixa de te opores a Deus, que está comigo, para que ele não te destrua.

[[v14-35-22]]

^<<v14-35-22,22>>^ Todavia Josias não quis virar dele o seu rosto, mas disfarçou-se para pelejar contra ele e, não querendo ouvir as palavras de Neco, que saíram da boca de Deus, veio pelejar no vale de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ E os flecheiros atiraram ao rei Josias. Então o rei disse a seus servos: Tirai-me daqui, porque estou gravemente ferido.

[[v14-35-24]]

^<<v14-35-24,24>>^ Seus servos o removeram do carro e pondo-o no seu segundo carro, o trouxeram a Jerusalém. Ele morreu, e foi sepultado nos sepulcros de seus pais. E todo o Judá e Jerusalém prantearam a Josias.

[[v14-35-25]]

^<<v14-35-25,25>>^ Também Jeremias fez uma lamentação sobre Josias; e todos os cantores e cantoras têm falado de Josias nas suas lamentações até o dia de hoje; e as estabeleceram por costume em Israel; e eis que estão escritas nas Lamentações.

[[v14-35-26]]

^<<v14-35-26,26>>^ Ora, o restante dos atos de Josias, e as suas boas obras em conformidade com o que está escrito na lei do Senhor,

[[v14-35-27]]

^<<v14-35-27,27>>^ e os seus atos, desde os primeiros até os últimos, eis que estão escritos no livro dos reis de Israel e de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]