include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-33-1]]

^<<v14-33-1,1>>^ Tinha Manassés doze anos quando começou a reinar, e reinou cinqüenta e cinco anos em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ E fez o que era mau aos olhos do Senhor, conforme as abominações dos povos que o Senhor lançara fora de diante dos filhos de Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ Pois tornou a edificar os altos que Ezequias, seu pai, tinha derribado; e levantou altares aos baalins, e fez aserotes, e adorou a todo o exército do céu, e o serviu.

[[v14-33-4]]

^<<v14-33-4,4>>^ Também edificou altares na casa do Senhor, da qual o Senhor tinha dito: Em Jerusalém estará o meu nome eternamente.

[[v14-33-5]]

^<<v14-33-5,5>>^ Edificou altares a todo o exército do céu, nos dois átrios da casa do Senhor.

[[v14-33-6]]

^<<v14-33-6,6>>^ Além disso queimou seus filhos como sacrifício no vale do filho de Hinom; e usou de augúrios e de encantamentos, e dava-se a artes mágicas, e instituiu adivinhos e feiticeiros; sim, fez muito mal aos olhos do Senhor, para o provocar à ira.

[[v14-33-7]]

^<<v14-33-7,7>>^ Também a imagem esculpida do ídolo que tinha feito, ele a colocou na casa de Deus, da qual Deus tinha dito a Davi e a Salomão, seu filho: Nesta casa, e em Jerusalém, que escolhi de todas as tribos de Israel, porei eu o meu nome para sempre;

[[v14-33-8]]

^<<v14-33-8,8>>^ e nunca mais removerei o pé de Israel da terra que destinei a vossos pais; contanto que tenham cuidado de fazer tudo o que eu lhes ordenei, toda a lei, os estatutos e as ordenanças dados por intermédio de Moisés.

[[v14-33-9]]

^<<v14-33-9,9>>^ Manassés tanto fez errar a Judá e aos moradores de Jerusalém, que eles fizeram o mal ainda mais do que as nações que o Senhor tinha destruído de diante dos filhos de Israel.

[[v14-33-10]]

^<<v14-33-10,10>>^ Falou o Senhor a Manassés e ao seu povo, porém não deram ouvidos.

[[v14-33-11]]

^<<v14-33-11,11>>^ Pelo que o Senhor trouxe sobre eles os comandantes do exército do rei da Assíria, os quais prenderam Manassés com ganchos e, amarrando-o com cadeias de bronze, o levaram para Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ E estando ele angustiado, suplicou ao Senhor seu Deus, e humilhou-se muito perante o Deus de seus pais;

[[v14-33-13]]

^<<v14-33-13,13>>^ sim, orou a ele; e Deus se aplacou para com ele, e ouviu-lhe a súplica, e tornou a trazê-lo a Jerusalém, ao seu reino. Então conheceu Manassés que o Senhor era Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ Ora, depois disso edificou um muro do lado de fora da cidade de Davi, ao ocidente de Giom, no vale, até a entrada da porta dos peixes; e fê-lo passar ao redor de Ofel, e o levantou muito alto; também pôs oficiais do exército em todas as cidades fortificadas de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ Tirou da casa do Senhor os deuses estranhos e o ídolo, como também todos os altares que tinha edificado no monte da casa do Senhor, e em Jerusalém, e os lançou fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ Também reparou o altar do Senhor, e ofereceu sobre ele sacrifícios de ofertas pacíficas e de ações de graças; e ordenou a Judá que servisse ao Senhor Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ Contudo o povo ainda sacrificava nos altos, mas somente ao Senhor seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ O restante dos atos de Manassés, e a sua oração ao seu Deus, e as palavras dos videntes que lhe falaram em nome do Senhor, Deus de Israel eram os seus altares e as suas imagens, e a Matã, sacerdote de

[[v14-33-19]]

^<<v14-33-19,19>>^ Também a sua oração, e como Deus se aplacou para com ele, e todo o seu pecado, e a sua transgressão, e os lugares onde edificou altos e pôs os aserins e as imagens esculpidas antes de se ter humilhado, eis que estão escritos nas crônicas dos videntes.

[[v14-33-20]]

^<<v14-33-20,20>>^ E dormiu Manassés com seus pais, e o sepultaram em sua casa; e Amom, seu filho, reinou em seu lugar.

[[v14-33-21]]

^<<v14-33-21,21>>^ Tinha Amom vinte e dois anos quando começou a reinar, e reinou dois anos em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ Fez o que era mau aos olhos do Senhor, como havia feito Manassés, seu pai Amom sacrificou a todas as imagens esculpidas que Manassés, seu pai, tinha feito, e as serviu.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas não se humilhou perante o Senhor, como Manassés, seu pai, se humilhara; pelo contrário multiplicou Amom os seus delitos.

[[v14-33-24]]

^<<v14-33-24,24>>^ E conspiraram contra ele os seus servos, e o mataram em sua casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ Mas o povo da terra matou todos os que conspiraram contra o rei Amom, e fez reinar em lugar dele seu filho Josias.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]