include::./index.adoc[]

[[v14-9-0]]
=== 2 Crônicas, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-9-1]]

^<<v14-9-1,1>>^ Tendo a rainha de Sabá ouvido da fama de Salomão, veio a Jerusalém para prová-lo por enigmas; trazia consigo uma grande comitiva, e camelos carregados de especiarias, e ouro em abundância, e pedras preciosas; e vindo ter com Salomão, falou com ele de tudo o que tinha no seu coração.

[[v14-9-2]]

^<<v14-9-2,2>>^ E Salomão lhe respondeu a todas as perguntas; não houve nada que Salomão não lhe soubesse explicar.

[[v14-9-3]]

^<<v14-9-3,3>>^ Vendo, pois, a rainha de Sabá a sabedoria de Salomão, e a casa que ele edificara,

[[v14-9-4]]

^<<v14-9-4,4>>^ e as iguarias da sua mesa, e o assentar dos seus oficiais, e as funções e os trajes dos seus servos, e os seus copeiros e os trajes deles, e os holocaustos que ele oferecia na casa do Senhor, ficou estupefata.

[[v14-9-5]]

^<<v14-9-5,5>>^ Então disse ao rei: Era verdade o que ouvi na minha terra acerca dos teus feitos e da tua sabedoria.

[[v14-9-6]]

^<<v14-9-6,6>>^ Todavia eu não o acreditava, até que vim e os meus olhos o viram; e eis que não me contaram metade da grandeza da tua sabedoria; sobrepujaste a fama que ouvi.

[[v14-9-7]]

^<<v14-9-7,7>>^ Bem-aventurados os teus homens! Bem-aventurados estes teus servos, que estão sempre diante de ti, e ouvem a tua sabedoria!

[[v14-9-8]]

^<<v14-9-8,8>>^ Bendito seja o Senhor teu Deus, que se agradou de ti, colocando-te sobre o seu trono, para ser rei pelo Senhor teu Deus! Porque teu Deus amou a Israel, para o estabelecer perpetuamente, por isso te constituiu rei sobre eles, para executares juízo e justiça.

[[v14-9-9]]

^<<v14-9-9,9>>^ Então ela deu ao rei cento e vinte talentos de ouro, e especiarias em grande abundância, e pedras preciosas; e nunca houve tais especiarias quais a rainha de Sabá deu ao rei Salomão.

[[v14-9-10]]

^<<v14-9-10,10>>^ Também os servos de Hurão, e os servos de Salomão, que de Ofir trouxeram ouro, trouxeram madeira de algumins, e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ E o rei fez, da madeira de algumins, degraus para a casa do Senhor e para a casa do rei, como também harpas e alaúdes para os cantores, quais nunca dantes se viram na terra de Judá.

[[v14-9-12]]

^<<v14-9-12,12>>^ E o rei Salomão deu à rainha de Sabá tudo quanto ela desejou, tudo quanto lhe pediu, excedendo mesmo o que ela trouxera ao rei. Assim voltou e foi para a sua terra, ela e os seus servos.

[[v14-9-13]]

^<<v14-9-13,13>>^ Ora, o peso do ouro que se trazia cada ano a Salomão era de seiscentos e sessenta e seis talentos,

[[v14-9-14]]

^<<v14-9-14,14>>^ afora o que os mercadores e negociantes traziam; também todos os reis da Arábia, e os governadores do país traziam a Salomão ouro e prata.

[[v14-9-15]]

^<<v14-9-15,15>>^ E o rei Salomão fez duzentos paveses de ouro batido, empregando em cada pavês seiscentos siclos de ouro batido;

[[v14-9-16]]

^<<v14-9-16,16>>^ como também trezentos escudos de ouro batido, empregando em cada escudo trezentos siclos de ouro. E o rei os depositou na casa do bosque do Líbano.

[[v14-9-17]]

^<<v14-9-17,17>>^ Fez mais o rei um grande trono de marfim, e o revestiu de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ O trono tinha seis degraus e um estrado de ouro, que eram ligados ao trono, e de ambos os lados tinha braços junto ao lugar do assento, e dois leões de pé junto aos braços.

[[v14-9-19]]

^<<v14-9-19,19>>^ E havia doze leões em pé de um e outro lado sobre os seis degraus; outro tal não se fizera em reino algum.

[[v14-9-20]]

^<<v14-9-20,20>>^ Também todos os vasos de beber do rei Salomão eram de ouro, e todos os utensílios da casa do bosque do Líbano, de ouro puro; a prata reputava-se sem valor nos dias de Salomão.

[[v14-9-21]]

^<<v14-9-21,21>>^ Pois o rei tinha navios que iam a Társis com os servos de Hurão; de três em três anos os navios voltavam de Társis, trazendo ouro, prata, marfim, bugios e pavões.

[[v14-9-22]]

^<<v14-9-22,22>>^ Assim excedeu o rei Salomão todos os reis da terra, em riqueza e em sabedoria.

[[v14-9-23]]

^<<v14-9-23,23>>^ E todos os reis da terra buscavam a presença de Salomão para ouvirem a sabedoria que Deus lhe tinha posto no coração.

[[v14-9-24]]

^<<v14-9-24,24>>^ Cada um trazia o seu presente, vasos de prata, vasos de ouro, vestidos, armaduras, especiarias, cavalos e mulos, uma quota de ano em ano.

[[v14-9-25]]

^<<v14-9-25,25>>^ Teve também Salomão quatro mil manjedouras para os cavalos de seus carros, doze mil cavaleiros; e os colocou nas cidades dos carros, e junto ao rei em Jerusalém.

[[v14-9-26]]

^<<v14-9-26,26>>^ Ele dominava sobre todos os reis, desde o Rio Eufrates até a terra dos filisteus, e até o termo do Egito.

[[v14-9-27]]

^<<v14-9-27,27>>^ Também o rei tornou a prata tão comum em Jerusalém como as pedras, e os cedros tantos em abundância como os sicômoros que há na baixada.

[[v14-9-28]]

^<<v14-9-28,28>>^ E cavalos eram trazidos a Salomão do Egito e de todas as terras.

[[v14-9-29]]

^<<v14-9-29,29>>^ Ora, o restante dos atos de Salomão, desde os primeiros até os últimos, porventura não estão escritos na história de Natã, o profeta, e na profecia de Aías, o silonita, e nas visões de Ido, o vidente, acerca de Jeroboão, filho de Nebate?

[[v14-9-30]]

^<<v14-9-30,30>>^ Salomão reinou em Jerusalém quarenta anos sobre todo o Israel.

[[v14-9-31]]

^<<v14-9-31,31>>^ E dormiu com seus pais, e foi sepultado na cidade de Davi, seu pai. E Roboão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]