include::./index.adoc[]

[[v14-11-0]]
=== 2 Crônicas, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-11-1]]

^<<v14-11-1,1>>^ Tendo Roboão chegado a Jerusalém, convocou da casa de Judá e Benjamim cento e oitenta mil escolhidos, destros na guerra, para pelejarem contra Israel a fim de restituírem o reino a Roboão.

[[v14-11-2]]

^<<v14-11-2,2>>^ Veio, porém, a palavra do Senhor a Semaías, homem de Deus, dizendo:

[[v14-11-3]]

^<<v14-11-3,3>>^ Fala a Roboão, filho de Salomão, rei de Judá, e a todo o Israel em Judá e Benjamim, dizendo:

[[v14-11-4]]

^<<v14-11-4,4>>^ Assim diz o Senhor: Não subireis, nem pelejareis contra os vossos irmãos; volte cada um à sua casa, porque de mim proveio isto. Ouviram, pois, a palavra do Senhor, e desistiram de ir contra Jeroboão.

[[v14-11-5]]

^<<v14-11-5,5>>^ E Roboão habitou em Jerusalém, e edificou em Judá cidades para fortalezas.

[[v14-11-6]]

^<<v14-11-6,6>>^ Edificou, pois, Belém, Etã, Tecoa,

[[v14-11-7]]

^<<v14-11-7,7>>^ Bete-Zur, Socó, Adulão,

[[v14-11-8]]

^<<v14-11-8,8>>^ Gate, Maressa, Zife,

[[v14-11-9]]

^<<v14-11-9,9>>^ Adoraim, Laquis, Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ Zorá, Aijalom e Hebrom, que estão em Judá e em Benjamim, cidades fortes.

[[v14-11-11]]

^<<v14-11-11,11>>^ Fortificou estas cidades e pôs nelas capitães, e armazéns de víveres, de azeite e de vinho.

[[v14-11-12]]

^<<v14-11-12,12>>^ E pôs em cada cidade paveses e lanças, e fortificou-as grandemente, de sorte que reteve Judá e Benjamim.

[[v14-11-13]]

^<<v14-11-13,13>>^ Também os sacerdotes e os levitas que havia em todo o Israel recorreram a ele de todos os seus termos.

[[v14-11-14]]

^<<v14-11-14,14>>^ Pois os levitas deixaram os seus arrabaldes e a sua possessão, e vieram para Judá e para Jerusalém, porque Jeroboão e seus filhos os lançaram fora, para que não exercessem o ofício sacerdotal ao Senhor;

[[v14-11-15]]

^<<v14-11-15,15>>^ e Jeroboão constituiu para si sacerdotes, para os altos, e para os demônios, e para os bezerros que fizera.

[[v14-11-16]]

^<<v14-11-16,16>>^ Além desses, de todas as tribos de Israel, os que determinaram no seu coração buscar ao Senhor Deus de Israel, também vieram a Jerusalém, para oferecerem sacrifícios ao Senhor Deus de seus pais.

[[v14-11-17]]

^<<v14-11-17,17>>^ Assim fortaleceram o reino de Judá e corroboraram a Roboão, filho de Salomão, por três anos; porque durante três anos andaram no caminho de Davi e Salomão.

[[v14-11-18]]

^<<v14-11-18,18>>^ Roboão tomou para si, por mulher, a Maalate, filha de Jerimote, filho de Davi; e a Abiail, filha de Eliabe, filho de Jessé,

[[v14-11-19]]

^<<v14-11-19,19>>^ a qual lhe deu os filhos Jeús, Semarias e Zaã.

[[v14-11-20]]

^<<v14-11-20,20>>^ Depois dela tomou a Maacá, filha de Absalão; esta lhe deu Abias, Atai, Ziza e Selomite.

[[v14-11-21]]

^<<v14-11-21,21>>^ Amava Roboão a Maacá, filha de Absalão, mais do que a todas as suas outras mulheres e concubinas; pois tinha tomado dezoito mulheres e sessenta concubinas, e gerou vinte e oito filhos e sessenta filhas.

[[v14-11-22]]

^<<v14-11-22,22>>^ E Roboão designou Abias, filho de Maacá, chefe e príncipe entre os seus irmãos, porque queria fazê-lo rei.

[[v14-11-23]]

^<<v14-11-23,23>>^ Também usou de prudência, distribuindo todos os seus filhos por entre todas as terras de Judá e Benjamim, por todas as cidades fortes; e deu-lhes víveres em abundância, e procurou para eles muitas mulheres.

'''

xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]