include::./index.adoc[]

[[v14-29-0]]
=== 2 Crônicas, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-29-1]]

^<<v14-29-1,1>>^ Ezequias começou a reinar quando tinha vinte e cinco anos; e reinou vinte e nove anos em Jerusalém. E o nome de sua mãe era Abia, filha de Zacarias.

[[v14-29-2]]

^<<v14-29-2,2>>^ Ele fez o que era reto aos olhos do Senhor, conforme tudo quanto fizera Davi, seu pai.

[[v14-29-3]]

^<<v14-29-3,3>>^ Pois ele, no primeiro ano do seu reinado, no primeiro mês, abriu as portas da casa do Senhor, e as reparou.

[[v14-29-4]]

^<<v14-29-4,4>>^ Fez vir os sacerdotes e os levitas e, ajuntando-os na praça oriental,

[[v14-29-5]]

^<<v14-29-5,5>>^ disse-lhes: Ouvi-me, ó levitas; santificai-vos agora, e santificai a casa do Senhor, Deus de vossos pais, e tirai do santo lugar a imundícia.

[[v14-29-6]]

^<<v14-29-6,6>>^ Porque nossos pais se houveram traiçoeiramente, e fizeram o que era mau aos olhos do Senhor nosso Deus; deixaram-no e, desviando os seus rostos da habitação do Senhor, voltaram-lhe as costas.

[[v14-29-7]]

^<<v14-29-7,7>>^ Também fecharam as portas do alpendre, apagaram as lâmpadas, e não queimaram incenso nem ofereceram holocaustos no santo lugar ao Deus de Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ Pelo que veio a ira do Senhor sobre Judá e Jerusalém, e ele os entregou para serem motivo de espanto, de admiração e de escárnio, como vós o estais vendo com os vossos olhos.

[[v14-29-9]]

^<<v14-29-9,9>>^ Porque eis que nossos pais caíram à espada, e nossos filhos, nossas filhas e nossas mulheres estão por isso em cativeiro.

[[v14-29-10]]

^<<v14-29-10,10>>^ Agora tenho no coração o propósito de fazer um pacto com o Senhor, Deus de Israel, para que se desvie de nós o ardor da sua ira.

[[v14-29-11]]

^<<v14-29-11,11>>^ Filhos meus, não sejais negligentes, pois o Senhor vos escolheu para estardes diante dele a fim de o servir, e para serdes seus ministros e queimardes incenso.

[[v14-29-12]]

^<<v14-29-12,12>>^ Então se levantaram os levitas: Maate, filho de Amasai, e Joel, filho de Azarias, dos filhos dos coatitas; e dos filhos de Merári: Quis, filho de Abdi, e Azurias, filho de Jealelel; e dos gersonitas: Joá, filho de Zima, e Edem filho de Joá;

[[v14-29-13]]

^<<v14-29-13,13>>^ e dos filhos de Elizafã: Sínri e Jeuel; dos filhos de Asafe; Zacarias e Matanias;

[[v14-29-14]]

^<<v14-29-14,14>>^ e dos filhos de Hemã: Jeuel e Simei; e dos filhos de Jedutun: Semaías e Uziel.

[[v14-29-15]]

^<<v14-29-15,15>>^ Ajuntaram seus irmãos, santificaram-se e entraram conforme a ordem do rei, segundo as palavras do Senhor, para purificarem a casa do Senhor.

[[v14-29-16]]

^<<v14-29-16,16>>^ Também os sacerdotes entraram na parte interior da casa do Senhor para a limparem, e tirarem para fora, ao átrio da casa do Senhor, toda a imundícia que acharem no templo do Senhor; e os levitas a tomaram e a levaram para fora, ao ribeiro de Cedrom.

[[v14-29-17]]

^<<v14-29-17,17>>^ Começaram a santificá-la no primeiro dia do primeiro mês, e ao oitavo dia do mês chegaram ao alpendre do Senhor, e santificaram a casa do Senhor em oito dias; no décimo sexto dia do primeiro mês acabaram.

[[v14-29-18]]

^<<v14-29-18,18>>^ Então foram ter com o rei Ezequias no palácio, e disseram: Acabamos de limpar toda a casa do Senhor, como também o altar do holocausto com todos os seus utensílios, e a mesa dos pães da proposição com todos os seus utensílios.

[[v14-29-19]]

^<<v14-29-19,19>>^ Todos os utensílios que o rei Acaz, no seu reinado, lançou fora, na sua infidelidade, já os preparamos e santificamos; e eis que estão diante do altar do Senhor.

[[v14-29-20]]

^<<v14-29-20,20>>^ Então o rei Ezequias se levantou de madrugada, e ajuntou os príncipes da cidade e subiu à casa do Senhor.

[[v14-29-21]]

^<<v14-29-21,21>>^ E trouxeram sete novilhos, sete carneiros, sete cordeiros e sete bodes, como oferta pelo pecado a favor do reino, e do santuário e de Judá; e o rei deu ordem aos sacerdotes, filhos de Arão, que os oferecessem sobre o altar do Senhor.

[[v14-29-22]]

^<<v14-29-22,22>>^ Os sacerdotes pois imolaram os novilhos, e tomando o sangue o espargiram sobre o altar; também imolaram os carneiros, e espargiram o sangue sobre o altar; semelhantemente imolaram os cordeiros, e espargiram o sangue sobre o altar.

[[v14-29-23]]

^<<v14-29-23,23>>^ Então trouxeram os bodes, como oferta pelo pecado, perante o rei e a congregação, que lhes impuseram as mãos;

[[v14-29-24]]

^<<v14-29-24,24>>^ e os sacerdotes os imolaram, e com o seu sangue fizeram uma oferta pelo pecado, sobre o altar, para fazer expiação por todo o Israel. Porque o rei tinha ordenado que se fizesse aquele holocausto e aquela oferta pelo pecado por todo o Israel.

[[v14-29-25]]

^<<v14-29-25,25>>^ Também dispôs os levitas na casa do Senhor com címbalos, alaúdes e harpas conforme a ordem de Davi, e de Gade, o vidente do rei, e do profeta Natã; porque esta ordem viera do Senhor, por meio de seus profetas.

[[v14-29-26]]

^<<v14-29-26,26>>^ E os levitas estavam em pé com os instrumentos de Davi, e os sacerdotes com as trombetas.

[[v14-29-27]]

^<<v14-29-27,27>>^ E Ezequias ordenou que se oferecesse o holocausto sobre o altar; e quando começou o holocausto, começou também o canto do Senhor, ao som das trombetas e dos instrumentos de Davi, rei de Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ Então toda a congregação adorava, e os cantores cantavam, e os trombeteiros tocavam; tudo isso continuou até se acabar o holocausto.

[[v14-29-29]]

^<<v14-29-29,29>>^ Tendo eles acabado de fazer a oferta, o rei e todos os que estavam com ele se prostraram e adoraram.

[[v14-29-30]]

^<<v14-29-30,30>>^ E o rei Ezequias e os príncipes ordenaram aos levitas que louvassem ao Senhor com as palavras de Davi, e de Asafe, o vidente. E eles cantaram louvores com alegria, e se inclinaram e adoraram.

[[v14-29-31]]

^<<v14-29-31,31>>^ Então Ezequias disse: Agora que vos consagrastes ao Senhor chegai-vos e trazei sacrifícios e ofertas em ação de graças a casa do Senhor. E a congregação trouxe sacrifícios e ofertas em ação de graças, e todos os que estavam dispostos de coração trouxeram holocaustos.

[[v14-29-32]]

^<<v14-29-32,32>>^ E o número dos holocaustos que a congregação trouxe foi de setenta novilhos, cem carneiros e duzentos cordeiros, tudo isso em holocausto ao Senhor.

[[v14-29-33]]

^<<v14-29-33,33>>^ Houve também, de coisas consagradas, seiscentos bois e três mil ovelhas.

[[v14-29-34]]

^<<v14-29-34,34>>^ Eram, porém, mui poucos os sacerdotes, de modo que não podiam esfolar todos os holocaustos; pelo que seus irmãos, os levitas, os ajudaram, até se acabar a obra, e até que os outros sacerdotes se santificassem, pois os levitas foram mais retos de coração, para se santificarem, do que os sacerdotes.

[[v14-29-35]]

^<<v14-29-35,35>>^ E houve também holocaustos em abundância, juntamente com a gordura das ofertas pacíficas, e com as ofertas de libação para cada holocausto. Assim se restabeleceu o ministério da casa do Senhor.

[[v14-29-36]]

^<<v14-29-36,36>>^ E Ezequias regozijou-se, e com ele todo o povo, por causa daquilo que Deus tinha preparado a favor do povo; pois isto se fizera de improviso.

'''

xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[Próximo Capítulo &#62;]