include::./index.adoc[]

[[v14-30-0]]
=== 2 Crônicas, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-30-1]]

^<<v14-30-1,1>>^ Depois disso Ezequias enviou mensageiros por todo o Israel e Judá, e escreveu cartas a Efraim e a Manassés, para que viessem à casa do Senhor em Jerusalém, a fim de celebrarem a páscoa ao Senhor Deus de Israel.

[[v14-30-2]]

^<<v14-30-2,2>>^ Pois o rei tivera conselho com os príncipes e com toda a congregação em Jerusalém, para celebrarem a páscoa no segundo mês.

[[v14-30-3]]

^<<v14-30-3,3>>^ Pois não a puderam celebrar no tempo próprio porque não se tinham santificado sacerdotes em número suficiente, e porque o povo não se tinha ajuntado em Jerusalém.

[[v14-30-4]]

^<<v14-30-4,4>>^ Isto pareceu bem aos olhos do rei e de toda a congregação.

[[v14-30-5]]

^<<v14-30-5,5>>^ E decretaram que se fizesse proclamação por todo o Israel, desde Berseba até Dã para que viessem celebrar a páscoa ao Senhor, Deus de Israel, em Jerusalém; porque muitos não a tinham celebrado como está escrito.

[[v14-30-6]]

^<<v14-30-6,6>>^ Foram pois, os correios com as cartas, do rei e dos, seus príncipes, por todo o Israel e Judá, segundo a ordem do rei, dizendo: Filhos de Israel, voltai para o Senhor, Deus de Abraão, de Isaque e de Israel, para que ele se volte para o restante de vós que escapastes da mão dos reis da Assíria.

[[v14-30-7]]

^<<v14-30-7,7>>^ Não sejais como vossos pais e vossos irmãos, que foram infiéis para com o Senhor, Deus de seus pais, de modo que os entregou à desolação como vedes.

[[v14-30-8]]

^<<v14-30-8,8>>^ Não endureçais agora a vossa cerviz, como fizeram vossos pais; mas submetei-vos ao Senhor, e entrai no seu santuário que ele santificou para sempre, e servi ao Senhor vosso Deus, para que o ardor da sua ira se desvie de vós.

[[v14-30-9]]

^<<v14-30-9,9>>^ Pois, se voltardes para o Senhor, vossos irmãos e vossos filhos acharão misericórdia diante dos que os levaram cativos, e tornarão para esta terra; porque o Senhor vosso Deus é clemente e compassivo, e não desviará de vós o seu rosto, se voltardes para ele.

[[v14-30-10]]

^<<v14-30-10,10>>^ Os correios, pois, foram passando de cidade em cidade, pela terra de Efraím e Manassés, até Zebulom; porém riam-se e zombavam deles.

[[v14-30-11]]

^<<v14-30-11,11>>^ Todavia alguns de Aser, e de Manassés, e de Zebulom, se humilharam e vieram a Jerusalém.

[[v14-30-12]]

^<<v14-30-12,12>>^ E a mão de Deus esteve com Judá, dando-lhes um só coração para cumprirem a ordem do rei e dos príncipes conforme a palavra do Senhor.

[[v14-30-13]]

^<<v14-30-13,13>>^ E ajuntou-se em Jerusalém muito povo para celebrar a festa dos pães ázimos no segundo mês, uma congregação mui grande.

[[v14-30-14]]

^<<v14-30-14,14>>^ E, levantando-se, tiraram os altares que havia em Jerusalém; também tiraram todos os altares de incenso, e os lançaram no ribeiro de Cedrom.

[[v14-30-15]]

^<<v14-30-15,15>>^ Então imolaram a páscoa no décimo quarto dia do segundo mês; e os sacerdotes e levitas, envergonhados, santificaram-se e trouxeram holocaustos à casa do Senhor.

[[v14-30-16]]

^<<v14-30-16,16>>^ Tomaram os seus lugares, segundo a sua ordem, conforme a lei de Moisés, homem de Deus; e os sacerdotes espargiram o sangue, que recebiam da mão dos levitas.

[[v14-30-17]]

^<<v14-30-17,17>>^ Pois havia muitos na congregação que não se tinham santificado; pelo que os levitas tiveram que imolar os cordeiros da páscoa por todo aquele que não estava limpo, para o santificarem ao Senhor.

[[v14-30-18]]

^<<v14-30-18,18>>^ Porque uma multidão do povo, muitos de Efraím e Manassés, Issacar e Zebulom, não se tinham purificado, contudo comeram a páscoa, ainda que não segundo o que está escrito; pois Ezequias tinha orado por eles, dizendo: O Senhor, que é bom, perdoe todo aquele

[[v14-30-19]]

^<<v14-30-19,19>>^ que dispõe o seu coração para buscar a Deus, o Senhor, o Deus de seus pais, ainda que não esteja purificado segundo a purificação do santuário.

[[v14-30-20]]

^<<v14-30-20,20>>^ E o Senhor ouviu Ezequias, e sarou o povo.

[[v14-30-21]]

^<<v14-30-21,21>>^ E os filhos de Israel que se acharam em Jerusalém celebraram a festa dos pães ázimos por sete dias com grande alegria; e os levitas e os sacerdotes louvaram ao Senhor de dia em dia com instrumentos fortemente retinintes, cantando ao Senhor.

[[v14-30-22]]

^<<v14-30-22,22>>^ E Ezequias falou benignamente a todos os levitas que tinham bom entendimento no serviço do Senhor. Assim comeram as ofertas da festa por sete dias, sacrificando ofertas pacíficas, e dando graças ao Senhor, Deus de seus pais.

[[v14-30-23]]

^<<v14-30-23,23>>^ E, tendo toda a congregação resolvido celebrar outros sete dias, celebraram por mais sete dias com alegria.

[[v14-30-24]]

^<<v14-30-24,24>>^ Pois Ezequias, rei de Judá, apresentou à congregação para os sacrifícios mil novilhos e sete mil ovelhas; e os príncipes apresentaram à congregação mil novilhos e dez mil ovelhas; e os sacerdotes se santificaram em grande número.

[[v14-30-25]]

^<<v14-30-25,25>>^ E regozijaram-se toda a congregação de Judá, juntamente com os sacerdotes e levitas, e toda a congregação dos que vieram de Israel, como também os estrangeiros que vieram da terra de Israel e os que habitavam em Judá.

[[v14-30-26]]

^<<v14-30-26,26>>^ Assim houve grande alegria em Jerusalém, pois desde os dias de Salomão, filho de Davi, rei de Israel, não tinha havido coisa semelhante em Jerusalém.

[[v14-30-27]]

^<<v14-30-27,27>>^ Então os levitas sacerdotes se levantaram e abençoaram o povo; e a sua voz foi ouvida, porque a sua oração chegou até a santa habitação de Deus, até o céu.

'''

xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[&#60; Capítulo Anterior] | <<v14-30-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[Próximo Capítulo &#62;]