include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v14-14-1]]

^<<v14-14-1,1>>^ Abias dormiu com seus pais, e o sepultaram na cidade de Davi. E Asa, seu filho, reinou em seu lugar; nos seus dias a terra esteve em paz por dez anos.

[[v14-14-2]]

^<<v14-14-2,2>>^ E Asa fez o que era bom e reto aos olhos do Senhor seu Deus;

[[v14-14-3]]

^<<v14-14-3,3>>^ removeu os altares estranhos, e os altos, quebrou as colunas, cortou os aserins,

[[v14-14-4]]

^<<v14-14-4,4>>^ e mandou a Judá que buscasse ao Senhor, Deus de seus pais, e que observasse a lei e o mandamento.

[[v14-14-5]]

^<<v14-14-5,5>>^ Também removeu de todas as cidades de Judá os altos e os altares de incenso; e sob ele o reino esteve em paz.

[[v14-14-6]]

^<<v14-14-6,6>>^ Edificou cidades fortificadas em Judá; porque a terra estava em paz, e não havia guerra contra ele naqueles anos, porquanto o Senhor lhe dera repouso.

[[v14-14-7]]

^<<v14-14-7,7>>^ Disse, pois, a Judá: Edifiquemos estas cidades, e cerquemo-las de muros e torres, portas e ferrolhos; a terra ainda é nossa porque buscamos ao Senhor nosso Deus; nós o buscamos, e ele nos deu repouso de todos os lados. Edificaram, pois, e prosperaram.

[[v14-14-8]]

^<<v14-14-8,8>>^ Ora, tinha Asa um exército de trezentos mil homens de Judá, que traziam pavês e lança; e duzentos e oitenta mil de Benjamim, que traziam escudo e atiravam com arco; todos estes eram homens valentes.

[[v14-14-9]]

^<<v14-14-9,9>>^ E Zerá, o etíope, saiu contra eles, com um exército de um milhão de homens, e trezentos carros, e chegou até Maressa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Então Asa saiu contra ele, e ordenaram a batalha no vale de Zefatá, junto a Maressa.

[[v14-14-11]]

^<<v14-14-11,11>>^ E Asa clamou ao Senhor seu Deus, dizendo: Ó Senhor, nada para ti é ajudar, quer o poderoso quer o de nenhuma força. Acuda-nos, pois, o Senhor nosso Deus, porque em ti confiamos, e no teu nome viemos contra esta multidão. Ó Senhor, tu és nosso Deus, não prevaleça contra ti o homem.

[[v14-14-12]]

^<<v14-14-12,12>>^ E o Senhor desbaratou os etíopes diante de Asa e diante de Judá; e os etíopes fugiram.

[[v14-14-13]]

^<<v14-14-13,13>>^ Asa e o povo que estava com ele os perseguiram até Gerar; e caíram tantos dos etíopes que já não havia neles resistência alguma; porque foram quebrantados diante do Senhor, e diante do seu exército. Os homens de Judá levaram dali mui grande despojo.

[[v14-14-14]]

^<<v14-14-14,14>>^ Feriram todas as cidades nos arredores de Gerar, porque veio sobre elas o terror da parte do Senhor; e saquearam todas as cidades, pois havia nelas muito despojo.

[[v14-14-15]]

^<<v14-14-15,15>>^ Também feriram as malhadas do gado, e levaram ovelhas em abundância, e camelos, e voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]