include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-4-1]]

^<<v2-4-1,1>>^ Então respondeu Moisés: Mas eis que não me crerão, nem ouvirão a minha voz, pois dirão: O Senhor não te apareceu.

[[v2-4-2]]

^<<v2-4-2,2>>^ Ao que lhe perguntou o Senhor: Que é isso na tua mão. Disse Moisés: uma vara.

[[v2-4-3]]

^<<v2-4-3,3>>^ Ordenou-lhe o Senhor: Lança-a no chão. Ele a lançou no chão, e ela se tornou em cobra; e Moisés fugiu dela.

[[v2-4-4]]

^<<v2-4-4,4>>^ Então disse o Senhor a Moisés: Estende a mão e pega-lhe pela cauda &#123;estendeu ele a mão e lhe pegou, e ela se tornou em vara na sua mão&#125;;

[[v2-4-5]]

^<<v2-4-5,5>>^ para que eles creiam que te apareceu o Senhor, o Deus de seus pais, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó.

[[v2-4-6]]

^<<v2-4-6,6>>^ Disse-lhe mais o Senhor: Mete agora a mão no seio. E meteu a mão no seio. E quando a tirou, eis que a mão estava leprosa, branca como a neve.

[[v2-4-7]]

^<<v2-4-7,7>>^ Disse-lhe ainda: Torna a meter a mão no seio. &#123;E tornou a meter a mão no seio; depois tirou-a do seio, e eis que se tornara como o restante da sua carne.&#125;

[[v2-4-8]]

^<<v2-4-8,8>>^ E sucederá que, se eles não te crerem, nem atentarem para o primeiro sinal, crerão ao segundo sinal.

[[v2-4-9]]

^<<v2-4-9,9>>^ E se ainda não crerem a estes dois sinais, nem ouvirem a tua voz, então tomarás da água do rio, e a derramarás sobre a terra seca; e a água que tomares do rio tornar-se-á em sangue sobre a terra seca.

[[v2-4-10]]

^<<v2-4-10,10>>^ Então disse Moisés ao Senhor: Ah, Senhor! eu não sou eloqüente, nem o fui dantes, nem ainda depois que falaste ao teu servo; porque sou pesado de boca e pesado de língua.

[[v2-4-11]]

^<<v2-4-11,11>>^ Ao que lhe replicou o Senhor: Quem faz a boca do homem? ou quem faz o mudo, ou o surdo, ou o que vê, ou o cego?. Não sou eu, o Senhor?

[[v2-4-12]]

^<<v2-4-12,12>>^ Vai, pois, agora, e eu serei com a tua boca e te ensinarei o que hás de falar.

[[v2-4-13]]

^<<v2-4-13,13>>^ Ele, porém, respondeu: Ah, Senhor! envia, peço-te, por mão daquele a quem tu hás de enviar.

[[v2-4-14]]

^<<v2-4-14,14>>^ Então se acendeu contra Moisés a ira do Senhor, e disse ele: Não é Arão, o levita, teu irmão? eu sei que ele pode falar bem. Eis que ele também te sai ao encontro, e vendo-te, se alegrará em seu coração.

[[v2-4-15]]

^<<v2-4-15,15>>^ Tu, pois, lhe falarás, e porás as palavras na sua boca; e eu serei com a tua boca e com a dele, e vos ensinarei o que haveis de fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ E ele falará por ti ao povo; assim ele te será por boca, e tu lhe serás por Deus.

[[v2-4-17]]

^<<v2-4-17,17>>^ Tomarás, pois, na tua mão esta vara, com que hás de fazer os sinais.

[[v2-4-18]]

^<<v2-4-18,18>>^ Então partiu Moisés, e voltando para Jetro, seu sogro, disse-lhe: Deixa-me, peço-te, voltar a meus irmãos, que estão no Egito, para ver se ainda vivem. Disse, pois, Jetro a Moisés: Vai-te em paz.

[[v2-4-19]]

^<<v2-4-19,19>>^ Disse também o Senhor a Moisés em Midiã: Vai, volta para o Egito; porque morreram todos os que procuravam tirar-te a vida.

[[v2-4-20]]

^<<v2-4-20,20>>^ Tomou, pois, Moisés sua mulher e seus filhos, e os fez montar num jumento e tornou à terra do Egito; e Moisés levou a vara de Deus na sua mão.

[[v2-4-21]]

^<<v2-4-21,21>>^ Disse ainda o Senhor a Moisés: Quando voltares ao Egito, vê que faças diante de Faraó todas as maravilhas que tenho posto na tua mão; mas eu endurecerei o seu coração, e ele não deixará ir o povo.

[[v2-4-22]]

^<<v2-4-22,22>>^ Então dirás a Faraó: Assim diz o Senhor: Israel é meu filho, meu primogênito;

[[v2-4-23]]

^<<v2-4-23,23>>^ e eu te tenho dito: Deixa ir: meu filho, para que me sirva. mas tu recusaste deixá-lo ir; eis que eu matarei o teu filho, o teu primogênito.

[[v2-4-24]]

^<<v2-4-24,24>>^ Ora, sucedeu no caminho, numa estalagem, que o Senhor o encontrou, e quis matá-lo.

[[v2-4-25]]

^<<v2-4-25,25>>^ Então Zípora tomou uma faca de pedra, circuncidou o prepúcio de seu filho e, lançando-o aos pés de Moisés, disse: Com efeito, és para mim um esposo sanguinário.

[[v2-4-26]]

^<<v2-4-26,26>>^ O Senhor, pois, o deixou. Ela disse: Esposo sanguinário, por causa da circuncisão.

[[v2-4-27]]

^<<v2-4-27,27>>^ Disse o Senhor a Arão: Vai ao deserto, ao encontro de Moisés. E ele foi e, encontrando-o no monte de Deus, o beijou:

[[v2-4-28]]

^<<v2-4-28,28>>^ E relatou Moisés a Arão todas as palavras com que o Senhor o enviara e todos os sinais que lhe mandara.

[[v2-4-29]]

^<<v2-4-29,29>>^ Então foram Moisés e Arão e ajuntaram todos os anciãos dos filhos de Israel;

[[v2-4-30]]

^<<v2-4-30,30>>^ e Arão falou todas as palavras que o Senhor havia dito a Moisés e fez os sinais perante os olhos do povo.

[[v2-4-31]]

^<<v2-4-31,31>>^ E o povo creu; e quando ouviram que o Senhor havia visitado os filhos de Israel e que tinha visto a sua aflição, inclinaram-se, e adoraram.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]