include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-21-1]]

^<<v2-21-1,1>>^ Estes são os estatutos que lhes proporás:

[[v2-21-2]]

^<<v2-21-2,2>>^ Se comprares um servo hebreu, seis anos servirá; mas ao sétimo sairá forro, de graça.

[[v2-21-3]]

^<<v2-21-3,3>>^ Se entrar sozinho, sozinho sairá; se tiver mulher, então com ele sairá sua mulher.

[[v2-21-4]]

^<<v2-21-4,4>>^ Se seu senhor lhe houver dado uma mulher e ela lhe houver dado filhos ou filhas, a mulher e os filhos dela serão de seu senhor e ele sairá sozinho.

[[v2-21-5]]

^<<v2-21-5,5>>^ Mas se esse servo expressamente disser: Eu amo a meu senhor, a minha mulher e a meus filhos, não quero sair forro;

[[v2-21-6]]

^<<v2-21-6,6>>^ então seu senhor o levará perante os juízes, e o fará chegar à porta, ou ao umbral da porta, e o seu senhor lhe furará a orelha com uma sovela; e ele o servirá para sempre.

[[v2-21-7]]

^<<v2-21-7,7>>^ Se um homem vender sua filha para ser serva, ela não sairá como saem os servos.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se ela não agradar ao seu senhor, de modo que não se despose com ela, então ele permitirá que seja resgatada; vendê-la a um povo estrangeiro, não o poderá fazer, visto ter usado de dolo para com ela.

[[v2-21-9]]

^<<v2-21-9,9>>^ Mas se a desposar com seu filho, fará com ela conforme o direito de filhas.

[[v2-21-10]]

^<<v2-21-10,10>>^ Se lhe tomar outra, não diminuirá e o mantimento daquela, nem o seu vestido, nem o seu direito conjugal.

[[v2-21-11]]

^<<v2-21-11,11>>^ E se não lhe cumprir estas três obrigações, ela sairá de graça, sem dar dinheiro.

[[v2-21-12]]

^<<v2-21-12,12>>^ Quem ferir a um homem, de modo que este morra, certamente será morto.

[[v2-21-13]]

^<<v2-21-13,13>>^ Se, porém, lhe não armar ciladas, mas Deus lho entregar nas mãos, então te designarei um lugar, para onde ele fugirá.

[[v2-21-14]]

^<<v2-21-14,14>>^ No entanto, se alguém se levantar deliberadamente contra seu próximo para o matar à traição, tirá-lo-ás do meu altar, para que morra.

[[v2-21-15]]

^<<v2-21-15,15>>^ Quem ferir a seu pai, ou a sua mãe, certamente será morto.

[[v2-21-16]]

^<<v2-21-16,16>>^ Quem furtar algum homem, e o vender, ou mesmo se este for achado na sua mão, certamente será morto.

[[v2-21-17]]

^<<v2-21-17,17>>^ Quem amaldiçoar a seu pai ou a sua mãe, certamente será morto.

[[v2-21-18]]

^<<v2-21-18,18>>^ Se dois homens brigarem e um ferir ao outro com pedra ou com o punho, e este não morrer, mas cair na cama,

[[v2-21-19]]

^<<v2-21-19,19>>^ se ele tornar a levantar-se e andar fora sobre o seu bordão, então aquele que o feriu será absolvido; somente lhe pagará o tempo perdido e fará que ele seja completamente curado.

[[v2-21-20]]

^<<v2-21-20,20>>^ Se alguém ferir a seu servo ou a sua serva com pau, e este morrer debaixo da sua mão, certamente será castigado;

[[v2-21-21]]

^<<v2-21-21,21>>^ mas se sobreviver um ou dois dias, não será castigado; porque é dinheiro seu.

[[v2-21-22]]

^<<v2-21-22,22>>^ Se alguns homens brigarem, e um ferir uma mulher grávida, e for causa de que aborte, não resultando, porém, outro dano, este certamente será multado, conforme o que lhe impuser o marido da mulher, e pagará segundo o arbítrio dos juízes;

[[v2-21-23]]

^<<v2-21-23,23>>^ mas se resultar dano, então darás vida por vida,

[[v2-21-24]]

^<<v2-21-24,24>>^ olho por olho, dente por dente, mão por mão, pé por pé,

[[v2-21-25]]

^<<v2-21-25,25>>^ queimadura por queimadura, ferida por ferida, golpe por golpe.

[[v2-21-26]]

^<<v2-21-26,26>>^ Se alguém ferir o olho do seu servo ou o olho da sua serva e o cegar, deixá-lo-á ir forro por causa do olho.

[[v2-21-27]]

^<<v2-21-27,27>>^ Da mesma sorte se tirar o dente do seu servo ou o dente da sua serva, deixá-lo-á ir forro por causa do dente.

[[v2-21-28]]

^<<v2-21-28,28>>^ Se um boi escornear um homem ou uma mulher e este morrer, certamente será apedrejado o boi e a sua carne não se comerá; mas o dono do boi será absolvido.

[[v2-21-29]]

^<<v2-21-29,29>>^ Mas se o boi dantes era escorneador, e o seu dono, tendo sido disso advertido, não o guardou, o boi, matando homem ou mulher, será apedrejado, e também o seu dono será morto.

[[v2-21-30]]

^<<v2-21-30,30>>^ Se lhe for imposto resgate, então dará como redenção da sua vida tudo quanto lhe for imposto;

[[v2-21-31]]

^<<v2-21-31,31>>^ quer tenha o boi escorneado a um filho, quer a uma filha, segundo este julgamento lhe será feito.

[[v2-21-32]]

^<<v2-21-32,32>>^ Se o boi escornear um servo, ou uma serva, dar-se-á trinta siclos de prata ao seu senhor, e o boi será apedrejado.

[[v2-21-33]]

^<<v2-21-33,33>>^ Se alguém descobrir uma cova, ou se alguém cavar uma cova e não a cobrir, e nela cair um boi ou um jumento,

[[v2-21-34]]

^<<v2-21-34,34>>^ o dono da cova dará indenização; pagá-la-á em dinheiro ao dono do animal morto, mas este será seu.

[[v2-21-35]]

^<<v2-21-35,35>>^ Se o boi de alguém ferir de morte o boi do seu próximo, então eles venderão o boi vivo e repartirão entre si o dinheiro da venda, e o morto também dividirão entre si.

[[v2-21-36]]

^<<v2-21-36,36>>^ Ou se for notório que aquele boi dantes era escorneador, e seu dono não o guardou, certamente pagará boi por boi, porém o morto será seu.

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]