include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-8-1]]

^<<v2-8-1,1>>^ Então disse o Senhor a Moisés: Vai a Faraó, e dize-lhe: Assim diz o Senhor: Deixa ir o meu povo, para que me sirva.

[[v2-8-2]]

^<<v2-8-2,2>>^ Mas se recusares deixá-lo ir, eis que ferirei com rãs todos os teus termos.

[[v2-8-3]]

^<<v2-8-3,3>>^ O rio produzirá rãs em abundância, que subirão e virão à tua casa, e ao teu dormitório, e sobre a tua cama, e às casas dos teus servos, e sobre o teu povo, e aos teus fornos, e às tuas amassadeiras.

[[v2-8-4]]

^<<v2-8-4,4>>^ Sim, as rãs subirão sobre ti, e sobre o teu povo, e sobre todos os teus servos.

[[v2-8-5]]

^<<v2-8-5,5>>^ Disse mais o Senhor a Moisés: Dize a Arão: Estende a tua mão com a vara sobre as correntes, e sobre os rios, e sobre as lagoas, e faze subir rãs sobre a terra do Egito.

[[v2-8-6]]

^<<v2-8-6,6>>^ Arão, pois, estendeu a mão sobre as águas do Egito, e subiram rãs, que cobriram a terra do Egito.

[[v2-8-7]]

^<<v2-8-7,7>>^ Então os magos fizeram o mesmo com os seus encantamentos, e fizeram subir rãs sobre a terra do Egito.

[[v2-8-8]]

^<<v2-8-8,8>>^ Chamou, pois, Faraó a Moisés e a Arão, e disse: Rogai ao Senhor que tire as rãs de mim e do meu povo; depois deixarei ir o povo, para que ofereça sacrifícios ao Senhor.

[[v2-8-9]]

^<<v2-8-9,9>>^ Respondeu Moisés a Faraó: Digna-te dizer-me quando é que hei de rogar por ti, e pelos teus servos, e por teu povo, para tirar as rãs de ti, e das tuas casas, de sorte que fiquem somente no rio?.

[[v2-8-10]]

^<<v2-8-10,10>>^ Disse Faraó: Amanhã. E Moisés disse: Seja conforme a tua palavra, para que saibas que ninguém há como o Senhor nosso Deus.

[[v2-8-11]]

^<<v2-8-11,11>>^ As rãs, pois, se apartarão de ti, e das tuas casas, e dos teus servos, e do teu povo; ficarão somente no rio.

[[v2-8-12]]

^<<v2-8-12,12>>^ Então saíram Moisés e Arão da presença de Faraó; e Moisés clamou ao Senhor por causa das rãs que tinha trazido sobre Faraó.

[[v2-8-13]]

^<<v2-8-13,13>>^ O Senhor, pois, fez conforme a palavra de Moisés; e as rãs morreram nas casas, nos pátios, e nos campos.

[[v2-8-14]]

^<<v2-8-14,14>>^ E ajuntaram-nas em montes, e a terra, cheirou mal.

[[v2-8-15]]

^<<v2-8-15,15>>^ Mas vendo Faraó que havia descanso, endureceu o seu coração, e não os ouviu, como o Senhor tinha dito.

[[v2-8-16]]

^<<v2-8-16,16>>^ Disse mais o Senhor a Moisés: Dize a Arão: Estende a tua vara, e fere o pó da terra, para que se torne em piolhos por toda a terra do Egito.

[[v2-8-17]]

^<<v2-8-17,17>>^ E assim fizeram. Arão estendeu a sua mão com a vara, e feriu o pó da terra, e houve piolhos nos homens e nos animais; todo o pó da terra se tornou em piolhos em toda a terra do Egito.

[[v2-8-18]]

^<<v2-8-18,18>>^ Também os magos fizeram assim com os seus encantamentos para produzirem piolhos, mas não puderam. E havia piolhos, nos homens e nos animais.

[[v2-8-19]]

^<<v2-8-19,19>>^ Então disseram os magos a Faraó: Isto é o dedo de Deus. No entanto o coração de Faraó se endureceu, e não os ouvia, como o Senhor tinha dito.

[[v2-8-20]]

^<<v2-8-20,20>>^ Disse mais o Senhor a Moisés: levanta-te pela manhã cedo e põe-te diante de Faraó:; eis que ele sairá às águas; e dize-lhe: Assim diz o Senhor: Deixa ir o meu povo, para que me sirva.

[[v2-8-21]]

^<<v2-8-21,21>>^ Porque se não deixares ir o meu povo., eis que enviarei enxames de moscas sobre ti, e sobre os teus servos, e sobre o teu povo, e nas tuas casas; e as casas dos egípcios se encherão destes enxames, bem como a terra em que eles estiverem.

[[v2-8-22]]

^<<v2-8-22,22>>^ Mas naquele dia separarei a terra de Gósem em que o meu povo habita, a fim de que nela não haja enxames de moscas, para que saibas que eu sou o Senhor no meio desta terra.

[[v2-8-23]]

^<<v2-8-23,23>>^ Assim farei distinção entre o meu povo e o teu povo; amanhã se fará este milagre.

[[v2-8-24]]

^<<v2-8-24,24>>^ O Senhor, pois, assim fez. Entraram grandes enxames de moscas na casa de Faraó e nas casas dos seus servos; e em toda parte do Egito a terra foi assolada pelos enxames de moscas.

[[v2-8-25]]

^<<v2-8-25,25>>^ Então chamou Faraó a Moisés e a Arão, e disse: Ide, e oferecei sacrifícios ao vosso Deus nesta terra.

[[v2-8-26]]

^<<v2-8-26,26>>^ Respondeu Moisés: Não convém que assim se faça, porque é abominação aos egípcios o que havemos de oferecer ao Senhor nosso Deus. Sacrificando nós a abominação dos egípcios perante os seus olhos, não nos apedrejarão eles?

[[v2-8-27]]

^<<v2-8-27,27>>^ Havemos de ir caminho de três dias ao deserto, para que ofereçamos sacrifícios ao Senhor nosso Deus, como ele nos ordenar.

[[v2-8-28]]

^<<v2-8-28,28>>^ Então disse Faraó: Eu vos deixarei ir, para que ofereçais sacrifícios ao Senhor vosso Deus no deserto; somente não ireis muito longe; e orai por mim.

[[v2-8-29]]

^<<v2-8-29,29>>^ Respondeu Moisés: Eis que saio da tua presença e orarei ao Senhor, que estes enxames de moscas se apartem amanhã de Faraó, dos seus servos, e do seu povo; somente não torne mais Faraó a proceder dolosamente, não deixando ir o povo para oferecer sacrifícios ao Senhor.

[[v2-8-30]]

^<<v2-8-30,30>>^ Então saiu Moisés da presença de Faraó, e orou ao Senhor.

[[v2-8-31]]

^<<v2-8-31,31>>^ E fez o Senhor conforme a palavra de Moisés, e apartou os enxames de moscas de Faraó, dos seus servos, e do seu povo; não ficou uma sequer.

[[v2-8-32]]

^<<v2-8-32,32>>^ Mas endureceu Faraó ainda esta vez o seu coração, e não deixou ir o povo.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]