include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-25-1]]

^<<v2-25-1,1>>^ Então disse o Senhor a Moisés:

[[v2-25-2]]

^<<v2-25-2,2>>^ Fala aos filhos de Israel que me tragam uma oferta alçada; de todo homem cujo coração se mover voluntariamente, dele tomareis a minha oferta alçada.

[[v2-25-3]]

^<<v2-25-3,3>>^ E esta é a oferta alçada que tomareis deles: ouro, prata, bronze,

[[v2-25-4]]

^<<v2-25-4,4>>^ estofo azul, púrpura, carmesim, linho fino, pêlos de cabras,

[[v2-25-5]]

^<<v2-25-5,5>>^ peles de carneiros tintas de vermelho, peles de golfinhos, madeira de acácia,

[[v2-25-6]]

^<<v2-25-6,6>>^ azeite para a luz, especiarias para o óleo da unção e para o incenso aromático,

[[v2-25-7]]

^<<v2-25-7,7>>^ pedras de ônix, e pedras de engaste para o éfode e para o peitoral.

[[v2-25-8]]

^<<v2-25-8,8>>^ E me farão um santuário, para que eu habite no meio deles.

[[v2-25-9]]

^<<v2-25-9,9>>^ Conforme a tudo o que eu te mostrar para modelo do tabernáculo, e para modelo de todos os seus móveis, assim mesmo o fareis.

[[v2-25-10]]

^<<v2-25-10,10>>^ Também farão uma arca de madeira ,de acácia; o seu comprimento será de dois côvados e meio, e a sua largura de um côvado e meio, e de um côvado e meio a sua altura.

[[v2-25-11]]

^<<v2-25-11,11>>^ E cobri-la-ás de ouro puro, por dentro e por fora a cobrirás; e farás sobre ela uma moldura de ouro ao redor;

[[v2-25-12]]

^<<v2-25-12,12>>^ e fundirás para ela quatro argolas de ouro, que porás nos quatro cantos dela; duas argolas de um lado e duas do outro.

[[v2-25-13]]

^<<v2-25-13,13>>^ Também farás varais de madeira de acácia, que cobrirás de ouro.

[[v2-25-14]]

^<<v2-25-14,14>>^ Meterás os varais nas argolas, aos lados da arca, para se levar por eles a arca.

[[v2-25-15]]

^<<v2-25-15,15>>^ Os varais permanecerão nas argolas da arca; não serão tirados dela.

[[v2-25-16]]

^<<v2-25-16,16>>^ E porás na arca o testemunho, que eu te darei.

[[v2-25-17]]

^<<v2-25-17,17>>^ Igualmente farás um propiciatório, de ouro puro; o seu comprimento será de dois côvados e meio, e a sua largura de um côvado e meio.

[[v2-25-18]]

^<<v2-25-18,18>>^ Farás também dois querubins de ouro; de ouro batido os farás, nas duas extremidades do propiciatório.

[[v2-25-19]]

^<<v2-25-19,19>>^ Farás um querubim numa extremidade e o outro querubim na outra extremidade; de uma só peça com o propiciatório fareis os querubins nas duas extremidades dele.

[[v2-25-20]]

^<<v2-25-20,20>>^ Os querubins estenderão as suas asas por cima do propiciatório, cobrindo-o com as asas, tendo as faces voltadas um para o outro; as faces dos querubins estarão voltadas para o propiciatório.

[[v2-25-21]]

^<<v2-25-21,21>>^ E porás o propiciatório em cima da arca; e dentro da arca porás o testemunho que eu te darei.

[[v2-25-22]]

^<<v2-25-22,22>>^ E ali virei a ti, e de cima do propiciatório, do meio dos dois querubins que estão sobre a arca do testemunho, falarei contigo a respeito de tudo o que eu te ordenar no tocante aos filhos de Israel.

[[v2-25-23]]

^<<v2-25-23,23>>^ Também farás uma mesa de madeira de acácia; o seu comprimento será de dois côvados, a sua largura de um côvado e a sua altura de um côvado e meio;

[[v2-25-24]]

^<<v2-25-24,24>>^ cobri-la-ás de ouro puro, e lhe farás uma moldura de ouro ao redor.

[[v2-25-25]]

^<<v2-25-25,25>>^ Também lhe farás ao redor uma guarnição de quatro dedos de largura, e ao redor na guarnição farás uma moldura de ouro.

[[v2-25-26]]

^<<v2-25-26,26>>^ Também lhe farás quatro argolas de ouro, e porás as argolas nos quatro cantos, que estarão sobre os quatro pés.

[[v2-25-27]]

^<<v2-25-27,27>>^ Junto da guarnição estarão as argolas, como lugares para os varais, para se levar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Farás, pois, estes varais de madeira de acácia, e os cobrirás de ouro; e levar-se-á por eles a mesa.

[[v2-25-29]]

^<<v2-25-29,29>>^ Também farás os seus pratos, as suas colheres, os seus cântaros e as suas tigelas com que serão oferecidas as libações; de ouro puro os farás.

[[v2-25-30]]

^<<v2-25-30,30>>^ E sobre a mesa porás os pães da o proposição perante mim para sempre.

[[v2-25-31]]

^<<v2-25-31,31>>^ Também farás um candelabro de ouro puro; de ouro batido se fará o candelabro, tanto o seu pedestal como a sua haste; os seus copos, os seus cálices e as suas corolas formarão com ele uma só peça.

[[v2-25-32]]

^<<v2-25-32,32>>^ E de seus lados sairão seis braços: três de um lado, e três do outro.

[[v2-25-33]]

^<<v2-25-33,33>>^ Em um braço haverá três copos a modo de flores de amêndoa, com cálice e corola; também no outro braço três copos a modo de flores de amêndoa, com cálice e corola; assim se farão os seis braços que saem do candelabro.

[[v2-25-34]]

^<<v2-25-34,34>>^ Mas na haste central haverá quatro copos a modo de flores de amêndoa, com os seus cálices e as suas corolas,

[[v2-25-35]]

^<<v2-25-35,35>>^ e um cálice debaixo de dois braços, formando com a haste uma só peça; outro cálice debaixo de dois outros braços, de uma só peça com a haste; e ainda outro cálice debaixo de dois outros braços, de uma só peça com a haste; assim será para os seis braços que saem do candelabro.

[[v2-25-36]]

^<<v2-25-36,36>>^ Os seus cálices e os seus braços formarão uma só peça com a haste; o todo será de obra batida de ouro puro.

[[v2-25-37]]

^<<v2-25-37,37>>^ Também lhe farás sete lâmpadas, as quais se acenderão para alumiar defronte dele.

[[v2-25-38]]

^<<v2-25-38,38>>^ Os seus espevitadores e os seus cinzeiros serão de ouro puro.

[[v2-25-39]]

^<<v2-25-39,39>>^ De um talento de ouro puro se fará o candelabro, com todos estes utensílios.

[[v2-25-40]]

^<<v2-25-40,40>>^ Atenta, pois, que os faças conforme o seu modelo, que te foi mostrado no monte.

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]