include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-26-1]]

^<<v2-26-1,1>>^ O tabernáculo farás de dez cortinas de linho fino torcido, e de estofo azul, púrpura, e carmesim; com querubins as farás, obra de artífice.

[[v2-26-2]]

^<<v2-26-2,2>>^ O comprimento de cada cortina será de vinte e oito côvados, e a largura de quatro côvados; todas as cortinas serão da mesma medida.

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco cortinas serão enlaçadas, cada uma à outra; e as outras cinco serão enlaçadas da mesma maneira.

[[v2-26-4]]

^<<v2-26-4,4>>^ Farás laçadas de estofo azul na orla da última cortina do primeiro grupo; assim também farás na orla da primeira cortina do segundo grupo;

[[v2-26-5]]

^<<v2-26-5,5>>^ a saber, cinqüenta laçadas na orla de uma cortina, e cinqüenta laçadas na orla da outra; as laçadas serão contrapostas uma à outra.

[[v2-26-6]]

^<<v2-26-6,6>>^ Farás cinqüenta colchetes de ouro, e prenderás com eles as cortinas, uma à outra; assim o tabernáculo virá a ser um todo.

[[v2-26-7]]

^<<v2-26-7,7>>^ Farás também cortinas de pêlos de cabras para servirem de tenda sobre o tabernáculo; onze destas cortinas farás.

[[v2-26-8]]

^<<v2-26-8,8>>^ O comprimento de cada cortina será de trinta côvados, e a largura de cada cortina de quatro côvados; as onze cortinas serão da mesma medida.

[[v2-26-9]]

^<<v2-26-9,9>>^ E ajuntarás cinco cortinas em um grupo, e as outras seis cortinas em outro grupo; e dobrarás a sexta cortina na frente da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ E farás cinqüenta laçadas na orla da última cortina do primeiro grupo, e outras cinqüenta laçadas na orla da primeira cortina do segundo grupo.

[[v2-26-11]]

^<<v2-26-11,11>>^ Farás também cinqüenta colchetes de bronze, e meterás os colchetes nas laçadas, e assim ajuntarás a tenda, para que venha a ser um todo.

[[v2-26-12]]

^<<v2-26-12,12>>^ E o resto que sobejar das cortinas da tenda, a saber, a meia cortina que sobejar, penderá aos fundos do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ E o côvado que sobejar de um lado e de outro no comprimento das cortinas da tenda, penderá de um e de outro lado do tabernáculo, para cobri-lo.

[[v2-26-14]]

^<<v2-26-14,14>>^ Farás também para a tenda uma coberta de peles de carneiros, tintas de vermelho, e por cima desta uma coberta de peles de golfinhos.

[[v2-26-15]]

^<<v2-26-15,15>>^ Farás também as tábuas para o tabernáculo de madeira de acácia, as quais serão colocadas verticalmente.

[[v2-26-16]]

^<<v2-26-16,16>>^ O comprimento de cada tábua será de dez côvados, e a sua largura de um côvado e meio.

[[v2-26-17]]

^<<v2-26-17,17>>^ Duas couceiras terá cada tábua, unidas uma à outra por travessas; assim farás com todas as tábuas do tabernáculo.

[[v2-26-18]]

^<<v2-26-18,18>>^ Ao fazeres as tábuas para o tabernáculo, farás vinte delas para o lado meridional.

[[v2-26-19]]

^<<v2-26-19,19>>^ Farás também quarenta bases de prata debaixo das vinte tábuas; duas bases debaixo de uma tábua, para as suas duas couceiras, e duas bases debaixo de outra, para as duas couceiras dela.

[[v2-26-20]]

^<<v2-26-20,20>>^ Também para o outro lado do tabernáculo, o que dá para o norte, farás vinte tábuas,

[[v2-26-21]]

^<<v2-26-21,21>>^ com as suas quarenta bases de prata; duas bases debaixo de uma tábua e duas debaixo de outra.

[[v2-26-22]]

^<<v2-26-22,22>>^ E para o lado posterior do tabernáculo, o que dá para o ocidente, farás seis tábuas.

[[v2-26-23]]

^<<v2-26-23,23>>^ Farás também duas tábuas para os cantos do tabernáculo no lado posterior.

[[v2-26-24]]

^<<v2-26-24,24>>^ Por baixo serão duplas, do mesmo modo se estendendo inteiras até a primeira argola em cima; assim se fará com as duas tábuas; elas serão para os dois cantos.

[[v2-26-25]]

^<<v2-26-25,25>>^ Haverá oito tábuas com as suas dezesseis bases de prata: duas bases debaixo de uma tábua e duas debaixo de outra.

[[v2-26-26]]

^<<v2-26-26,26>>^ Farás também travessões de madeira de acácia; cinco para as tábuas de um lado do tabernáculo,

[[v2-26-27]]

^<<v2-26-27,27>>^ e cinco para as tábuas do outro lado do tabernáculo, bem como o azeite para a luz, especiarias para o óleo da unção e para o para o ocidente.

[[v2-26-28]]

^<<v2-26-28,28>>^ O travessão central passará ao meio das tábuas, de uma extremidade à outra.

[[v2-26-29]]

^<<v2-26-29,29>>^ E cobrirás de ouro as tábuas, e de ouro farás as suas argolas, como lugares para os travessões; também os travessões cobrirás de ouro.

[[v2-26-30]]

^<<v2-26-30,30>>^ Então levantarás o tabernáculo conforme o modelo que te foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ Farás também um véu de azul, púrpura, carmesim, e linho fino torcido; com querubins, obra de artífice, se fará;

[[v2-26-32]]

^<<v2-26-32,32>>^ e o suspenderás sobre quatro colunas de madeira de acácia, cobertas de ouro; seus colchetes serão de ouro, sobre quatro bases de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ Pendurarás o véu debaixo dos colchetes, e levarás para dentro do véu a arca do testemunho; este véu vos fará separação entre o lugar santo e o santo dos santos.

[[v2-26-34]]

^<<v2-26-34,34>>^ Porás o propiciatório sobre a arca do testemunho no santo dos santos;

[[v2-26-35]]

^<<v2-26-35,35>>^ colocarás a mesa fora do véu, e o candelabro defronte da mesa, para o lado sul do tabernáculo; e porás a mesa para o lado norte.

[[v2-26-36]]

^<<v2-26-36,36>>^ Farás também para a porta da tenda um reposteiro de azul, púrpura, carmesim: e linho fino torcido, obra de bordador.

[[v2-26-37]]

^<<v2-26-37,37>>^ E para o reposteiro farás cinco colunas de madeira de acácia, cobrindo-as de ouro &#123;os seus colchetes também serão de ouro&#125;, e para elas fundirás cinco bases de bronze.

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]