include::./index.adoc[]

[[v2-13-0]]
=== Êxodo, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-13-1]]

^<<v2-13-1,1>>^ Então falou o Senhor a Moisés, dizendo:

[[v2-13-2]]

^<<v2-13-2,2>>^ Santifica-me todo primogênito, todo o que abrir a madre de sua mãe entre os filhos de Israel, assim de homens como de animais; porque meu é.

[[v2-13-3]]

^<<v2-13-3,3>>^ E Moisés disse ao povo: Lembrai-vos deste dia, em que saístes do Egito, da casa da servidão; pois com mão forte o Senhor vos tirou daqui; portanto não se comerá pão levedado.

[[v2-13-4]]

^<<v2-13-4,4>>^ Hoje, no mês de abibe, vós saís.

[[v2-13-5]]

^<<v2-13-5,5>>^ Quando o Senhor te houver introduzido na terra dos cananeus, dos heteus, dos amorreus, dos heveus e dos jebuseus, que ele jurou a teus pais que te daria, terra que mana leite e mel, guardarás este culto neste mês.

[[v2-13-6]]

^<<v2-13-6,6>>^ Sete dias comerás pães ázimos, e ao sétimo dia haverá uma festa ao Senhor.

[[v2-13-7]]

^<<v2-13-7,7>>^ Sete dias se comerão pães ázimos, e o levedado não se verá contigo, nem ainda fermento será visto em todos os teus termos.

[[v2-13-8]]

^<<v2-13-8,8>>^ Naquele dia contarás a teu filho, dizendo: Isto é por causa do que o Senhor me fez, quando eu saí do Egito;

[[v2-13-9]]

^<<v2-13-9,9>>^ e te será por sinal sobre tua mão e por memorial entre teus olhos, para que a lei do Senhor esteja em tua boca; porquanto com mão forte o Senhor te tirou do Egito.

[[v2-13-10]]

^<<v2-13-10,10>>^ Portanto guardarás este estatuto a seu tempo, de ano em ano.

[[v2-13-11]]

^<<v2-13-11,11>>^ Também quando o Senhor te houver introduzido na terra dos cananeus, como jurou a ti e a teus pais, quando te houver dado,

[[v2-13-12]]

^<<v2-13-12,12>>^ separarás para o Senhor tudo o que abrir a madre, até mesmo todo primogênito dos teus animais; os machos serão do Senhor.

[[v2-13-13]]

^<<v2-13-13,13>>^ Mas todo primogênito de jumenta resgatarás com um cordeiro; e, se o não quiseres resgatar, quebrar-lhe-ás a cerviz:; e todo primogênito do homem entre teus filhos resgatarás.

[[v2-13-14]]

^<<v2-13-14,14>>^ E quando teu filho te perguntar no futuro, dizendo: Que é isto? responder-lhe-ás: O Senhor, com mão forte, nos tirou do Egito, da casa da servidão.

[[v2-13-15]]

^<<v2-13-15,15>>^ Porque sucedeu que, endurecendo-se Faraó, para não nos deixar ir, o Senhor matou todos os primogênitos na terra do Egito, tanto os primogênitos dos homens como os primogênitos dos animais; por isso eu sacrifico ao Senhor todos os primogênitos, sendo machos; mas a todo primogênito de meus filhos eu resgato.

[[v2-13-16]]

^<<v2-13-16,16>>^ E isto será por sinal sobre tua mão, e por frontais entre os teus olhos, porque o Senhor, com mão forte, nos tirou do Egito.

[[v2-13-17]]

^<<v2-13-17,17>>^ Ora, quando Faraó deixou ir o povo, Deus não o conduziu pelo caminho da terra dos filisteus, se bem que fosse mais perto; porque Deus disse: Para que porventura o povo não se arrependa, vendo a guerra, e volte para o Egito;

[[v2-13-18]]

^<<v2-13-18,18>>^ mas Deus fez o povo rodear pelo caminho do deserto perto do Mar Vermelho; e os filhos de Israel subiram armados da terra do Egito.

[[v2-13-19]]

^<<v2-13-19,19>>^ Moisés levou consigo os ossos de José, porquanto havia este solenemente ajuramentado os filhos de Israel, dizendo: Certamente Deus vos visitará; e vós haveis de levar daqui convosco os meus ossos.

[[v2-13-20]]

^<<v2-13-20,20>>^ Assim partiram de Sucote, e acamparam-se em Etã, à entrada do deserto.

[[v2-13-21]]

^<<v2-13-21,21>>^ E o Senhor ia adiante deles, de dia numa coluna e os dois para os guiar pelo caminho, e de noite numa coluna de fogo para os alumiar, a fim de que caminhassem de dia e de noite.

[[v2-13-22]]

^<<v2-13-22,22>>^ Não desaparecia de diante do povo a coluna de nuvem de dia, nem a coluna de fogo de noite.

'''

xref:002-exodo/002-exodo-012.adoc#v2-12-0[&#60; Capítulo Anterior] | <<v2-13-0,Topo>> | xref:002-exodo/002-exodo-014.adoc#v2-14-0[Próximo Capítulo &#62;]