include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-36-1]]

^<<v2-36-1,1>>^ Assim trabalharam Bezalel e Aoliabe, e todo homem hábil, a quem o Senhor deu sabedoria e entendimento, para saberem exercer todo ofício para o serviço do santuário, conforme tudo o que o Senhor tem ordenado.

[[v2-36-2]]

^<<v2-36-2,2>>^ Então Moisés chamou a Bezalel e a Aoliabe, e a todo homem hábil, em cujo coração Deus tinha posto sabedoria, isto é, a todo aquele cujo coração o moveu a se chegar à obra para fazê-la;

[[v2-36-3]]

^<<v2-36-3,3>>^ e receberam de Moisés toda a oferta alçada, que os filhos de Israel tinham do para a obra do serviço do santuário, para fazê-la; e ainda eles lhe traziam cada manhã ofertas voluntárias.

[[v2-36-4]]

^<<v2-36-4,4>>^ Então todos os sábios que faziam toda a obra do santuário vieram, cada um da obra que fazia,

[[v2-36-5]]

^<<v2-36-5,5>>^ e disseram a Moisés: O povo traz muito mais do que é necessário para o serviço da obra que o Senhor ordenou se fizesse.

[[v2-36-6]]

^<<v2-36-6,6>>^ Pelo que Moisés deu ordem, a qual fizeram proclamar por todo o arraial, dizendo: Nenhum homem, nem mulher, faça mais obra alguma para a oferta alçada do santuário. Assim o povo foi proibido de trazer mais.

[[v2-36-7]]

^<<v2-36-7,7>>^ Porque o material que tinham era bastante para toda a obra, e ainda sobejava.

[[v2-36-8]]

^<<v2-36-8,8>>^ Assim todos os homens hábeis, dentre os que trabalhavam na obra, fizeram o tabernáculo de dez cortinas de linho fino torcido, de azul, de púrpura e de carmesim, com querubins, obra de artífice.

[[v2-36-9]]

^<<v2-36-9,9>>^ O comprimento de cada cortina era de vinte e oito côvados, e a largura de quatro côvados; todas as cortinas eram da mesma medida.

[[v2-36-10]]

^<<v2-36-10,10>>^ Ligaram cinco cortinas uma com outra; e as outras cinco da mesma maneira.

[[v2-36-11]]

^<<v2-36-11,11>>^ Fizeram laçadas de azul na orla da última cortina do primeiro grupo; assim, também fizeram na orla da primeira cortina do segundo grupo.

[[v2-36-12]]

^<<v2-36-12,12>>^ Cinqüenta laçadas fizeram na orla de uma cortina, e cinqüenta laçadas na orla da outra, do segundo grupo; as laçadas eram contrapostas uma à outra.

[[v2-36-13]]

^<<v2-36-13,13>>^ Também fizeram cinqüenta colchetes de ouro, e com estes colchetes uniram as cortinas, uma com outra; e o tabernáculo veio a ser um todo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fizeram também cortinas de pelos de cabras para servirem de tenda sobre o tabernáculo; onze cortinas fizeram.

[[v2-36-15]]

^<<v2-36-15,15>>^ O comprimento de cada cortina era de trinta côvados, e a largura de quatro côvados; as onze cortinas eram da mesma medida.

[[v2-36-16]]

^<<v2-36-16,16>>^ uniram cinco destas cortinas à parte, e as outras seis à parte.

[[v2-36-17]]

^<<v2-36-17,17>>^ Fizeram cinqüenta laçadas na orla da última cortina do primeiro grupo, e cinqüenta laçadas na orla da primeira cortina do segundo grupo.

[[v2-36-18]]

^<<v2-36-18,18>>^ Fizeram também cinqüenta colchetes de bronze, para ajuntar a tenda, para que viesse a ser um todo.

[[v2-36-19]]

^<<v2-36-19,19>>^ Fizeram para a tenda uma cobertura de peles de carneiros tintas de vermelho, e por cima desta uma cobertura de peles de golfinhos.

[[v2-36-20]]

^<<v2-36-20,20>>^ Também fizeram, de madeira de acácia, as tábuas para o tabernáculo, as quais foram colocadas verticalmente.

[[v2-36-21]]

^<<v2-36-21,21>>^ O comprimento de cada tábua era de dez côvados, e a largura de um côvado e meio.

[[v2-36-22]]

^<<v2-36-22,22>>^ Cada tábua tinha duas couceiras, unidas uma à outra; assim fizeram com todas as tábuas do tabernáculo.

[[v2-36-23]]

^<<v2-36-23,23>>^ Assim, pois, fizeram as tábuas para o tabernáculo; vinte tábuas para o lado que dá para o sul;

[[v2-36-24]]

^<<v2-36-24,24>>^ e fizeram quarenta bases de prata para se pôr debaixo das vinte tábuas: duas bases debaixo de uma tábua para as suas duas couceiras, e duas debaixo de outra, para as duas couceiras dela.

[[v2-36-25]]

^<<v2-36-25,25>>^ Também para o segundo lado do tabernáculo, o que dá para o norte, fizeram vinte tábuas,

[[v2-36-26]]

^<<v2-36-26,26>>^ com as suas quarenta bases de prata, duas bases debaixo de uma tábua, e duas bases debaixo de outra.

[[v2-36-27]]

^<<v2-36-27,27>>^ Para o lado posterior do tabernáculo, o que dá para o ocidente, fizeram seis tábuas.

[[v2-36-28]]

^<<v2-36-28,28>>^ E para os dois cantos do tabernáculo no lado posterior, fizeram mais duas tábuas.

[[v2-36-29]]

^<<v2-36-29,29>>^ Por baixo eram duplas, do mesmo modo se estendendo até a primeira argola, em cima; assim fizeram com as duas tábuas nos dois cantos.

[[v2-36-30]]

^<<v2-36-30,30>>^ Assim havia oito tábuas com as suas bases de prata, a saber, dezesseis bases, duas debaixo de cada tábua.

[[v2-36-31]]

^<<v2-36-31,31>>^ Fizeram também travessões de madeira de acácia: cinco travessões para as tábuas de um lado do tabernáculo,

[[v2-36-32]]

^<<v2-36-32,32>>^ e cinco para as tábuas do outro lado do tabernáculo, e outros cinco para as tábuas do tabernáculo no lado posterior, o que dá para o ocidente.

[[v2-36-33]]

^<<v2-36-33,33>>^ Fizeram que o travessão do meio passasse ao meio das tábuas duma extremidade até a outra.

[[v2-36-34]]

^<<v2-36-34,34>>^ E cobriram as tábuas de ouro, e de ouro fizeram as suas argolas como lugares para os travessões; também os travessões cobriu de ouro.

[[v2-36-35]]

^<<v2-36-35,35>>^ Fizeram então o véu de azul, púrpura, carmesim e linho fino torcido; com querubins, obra de artífice, o fizeram.

[[v2-36-36]]

^<<v2-36-36,36>>^ E fizeram-lhe quatro colunas de madeira de acácia e as cobriram de ouro; e seus colchetes fizeram de ouro; e fundiram-lhes quatro bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Fizeram também para a porta da tenda um reposteiro de azul, púrpura, carmesim e linho fino torcido, obra de bordador,

[[v2-36-38]]

^<<v2-36-38,38>>^ com as suas cinco colunas e os seus colchetes; e de ouro cobriu os seus capitéis e as suas faixas; e as suas cinco bases eram de bronze.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]