include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-40-1]]

^<<v2-40-1,1>>^ Depois disse o Senhor a Moisés:

[[v2-40-2]]

^<<v2-40-2,2>>^ No primeiro mês, no primeiro dia do mês, levantarás o tabernáculo da tenda da revelação,

[[v2-40-3]]

^<<v2-40-3,3>>^ e porás nele a arca do testemunho, e resguardaras a arca com o véu.

[[v2-40-4]]

^<<v2-40-4,4>>^ Depois colocarás nele a mesa, e porás em ordem o que se deve pôr em ordem nela; também colocarás nele o candelabro, e acenderás as suas lâmpadas.

[[v2-40-5]]

^<<v2-40-5,5>>^ E porás o altar de ouro para o incenso diante da arca do testemunho; então pendurarás o reposteiro da porta do tabernáculo.

[[v2-40-6]]

^<<v2-40-6,6>>^ E porás o altar do holocausto diante da porta do tabernáculo da tenda da revelação.

[[v2-40-7]]

^<<v2-40-7,7>>^ E porás a pia entre a tenda da revelação e o altar, e nela deitarás água.

[[v2-40-8]]

^<<v2-40-8,8>>^ Depois levantarás as cortinas do átrio ao redor, e pendurarás o reposteiro da porta do átrio.

[[v2-40-9]]

^<<v2-40-9,9>>^ Então tomarás o óleo da unção e ungirás o tabernáculo, e tudo o que há nele; e o santificarás, a ele e a todos os seus móveis; e será santo.

[[v2-40-10]]

^<<v2-40-10,10>>^ Ungirás também o altar do holocausto, e todos os seus utensílios, e santificarás o altar; e o altar será santíssimo.

[[v2-40-11]]

^<<v2-40-11,11>>^ Então ungirás a pia e a sua base, e a santificarás.

[[v2-40-12]]

^<<v2-40-12,12>>^ E farás chegar Arão e seus filhos à porta da tenda da revelação, e os lavarás com água.

[[v2-40-13]]

^<<v2-40-13,13>>^ E vestirás Arão das vestes sagradas, e o ungirás, e o santificarás, para que me administre o sacerdócio.

[[v2-40-14]]

^<<v2-40-14,14>>^ Também farás chegar seus filhos, e os vestirás de túnicas,

[[v2-40-15]]

^<<v2-40-15,15>>^ e os ungirás como ungiste a seu pai, para que me administrem o sacerdócio, e a sua unção lhes será por sacerdócio perpétuo pelas suas gerações.

[[v2-40-16]]

^<<v2-40-16,16>>^ E Moisés fez conforme tudo o que o Senhor lhe ordenou; assim o fez.

[[v2-40-17]]

^<<v2-40-17,17>>^ E no primeiro mês do segundo ano, no primeiro dia do mês, o tabernáculo foi levantado.

[[v2-40-18]]

^<<v2-40-18,18>>^ Levantou, pois, Moisés o tabernáculo: lançou as suas bases; armou as suas tábuas e nestas meteu os seus travessões; levantou as suas colunas;

[[v2-40-19]]

^<<v2-40-19,19>>^ estendeu a tenda por cima do tabernáculo, e pôs a cobertura da tenda sobre ela, em cima, como o Senhor lhe ordenara.

[[v2-40-20]]

^<<v2-40-20,20>>^ Então tomou o testemunho e pô-lo na arca, ajustou à arca os varais, e pôs-lhe o propiciatório em cima.

[[v2-40-21]]

^<<v2-40-21,21>>^ Depois introduziu a arca no tabernáculo, e pendurou o véu do reposteiro, e assim resguardou a arca do testemunho, como o Senhor lhe ordenara.

[[v2-40-22]]

^<<v2-40-22,22>>^ Pôs também a mesa na tenda da revelação, ao lado do tabernáculo para o norte, fora do véu,

[[v2-40-23]]

^<<v2-40-23,23>>^ e sobre ela pôs em ordem o pão perante o Senhor, como o Senhor lhe ordenara.

[[v2-40-24]]

^<<v2-40-24,24>>^ Pôs também na tenda da revelação o candelabro defronte da mesa, ao lado do tabernáculo para o sul,

[[v2-40-25]]

^<<v2-40-25,25>>^ e acendeu as lâmpadas perante o Senhor, como o Senhor lhe ordenara.

[[v2-40-26]]

^<<v2-40-26,26>>^ Pôs o altar de ouro na tenda da revelação diante do véu,

[[v2-40-27]]

^<<v2-40-27,27>>^ e sobre ele queimou o incenso de especiarias aromáticas, como o Senhor lhe ordenara.

[[v2-40-28]]

^<<v2-40-28,28>>^ Pendurou o reposteiro à: porta do tabernáculo,

[[v2-40-29]]

^<<v2-40-29,29>>^ e pôs o altar do holocausto à porta do tabernáculo da tenda da revelação, e sobre ele ofereceu o holocausto e a oferta de cereais, como o Senhor lhe ordenara.

[[v2-40-30]]

^<<v2-40-30,30>>^ Depois: colocou a pia entre a tenda da revelação e o altar, e nela deitou água para a as abluções.

[[v2-40-31]]

^<<v2-40-31,31>>^ E junto dela Moisés, e Arão e seus filhos lavaram as mãos e os pés.

[[v2-40-32]]

^<<v2-40-32,32>>^ Quando entravam na tenda da revelação, e quando chegavam ao altar, lavavam-se, como o Senhor ordenara a Moisés.

[[v2-40-33]]

^<<v2-40-33,33>>^ Levantou também as cortinas do átrio ao redor do tabernáculo e do altar e pendurou o reposteiro da porta do átrio. Assim Moisés acabou a obra.

[[v2-40-34]]

^<<v2-40-34,34>>^ Então a nuvem cobriu a tenda da revelação, e a glória do Senhor encheu o tabernáculo;

[[v2-40-35]]

^<<v2-40-35,35>>^ de maneira que Moisés não podia entrar na tenda da revelação, porquanto a nuvem repousava sobre ela, e a glória do Senhor enchia o tabernáculo.

[[v2-40-36]]

^<<v2-40-36,36>>^ Quando, pois, a nuvem se levantava de sobre o tabernáculo, prosseguiam os filhos de Israel, em todas as suas jornadas;

[[v2-40-37]]

^<<v2-40-37,37>>^ se a nuvem, porém, não se levantava, não caminhavam até o dia em que ela se levantasse.

[[v2-40-38]]

^<<v2-40-38,38>>^ Porquanto a nuvem do Senhor estava de dia sobre o tabernáculo, e o fogo estava de noite sobre ele, perante os olhos de toda a casa de Israel, em todas as suas jornadas.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]