include::./index.adoc[]

[[v2-17-0]]
=== Êxodo, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-17-1]]

^<<v2-17-1,1>>^ Partiu toda a congregação dos filhos de Israel do deserto de Sim, pelas suas jornadas, segundo o mandamento do Senhor, e acamparam em Refidim; e não havia ali água para o povo beber.

[[v2-17-2]]

^<<v2-17-2,2>>^ Então o povo contendeu com Moisés, dizendo: Dá-nos água para beber. Respondeu-lhes Moisés: Por que contendeis comigo? por que tentais ao Senhor?

[[v2-17-3]]

^<<v2-17-3,3>>^ Mas o povo, tendo sede ali, murmurou contra Moisés, dizendo: Por que nos fizeste subir do Egito, para nos matares de sede, a nós e aos nossos filhos, e ao nosso gado?

[[v2-17-4]]

^<<v2-17-4,4>>^ Pelo que Moisés, clamando ao Senhor, disse: Que hei de fazer a este povo? daqui a pouco me apedrejará.

[[v2-17-5]]

^<<v2-17-5,5>>^ Então disse o Senhor a Moisés: Passa adiante do povo, e leva contigo alguns dos anciãos de Israel; toma na mão a tua vara, com que feriste o rio, e vai-te.

[[v2-17-6]]

^<<v2-17-6,6>>^ Eis que eu estarei ali diante de ti sobre a rocha, em Horebe; ferirás a rocha, e dela sairá água para que o povo possa beber. Assim, pois fez Moisés à vista dos anciãos de Israel.

[[v2-17-7]]

^<<v2-17-7,7>>^ E deu ao lugar o nome de Massá e Meribá, por causa da contenda dos filhos de Israel, e porque tentaram ao Senhor, dizendo: Está o Senhor no meio de nós, ou não?

[[v2-17-8]]

^<<v2-17-8,8>>^ Então veio Amaleque, e pelejou contra e Israel em Refidim.

[[v2-17-9]]

^<<v2-17-9,9>>^ Pelo que disse Moisés a Josué: Escolhe-nos homens, e sai, peleja contra Amaleque; e amanhã eu estarei sobre o cume do outeiro, tendo na mão a vara de Deus.

[[v2-17-10]]

^<<v2-17-10,10>>^ Fez, pois, Josué como Moisés lhe dissera, e pelejou contra Amaleque; e Moisés, Arão, e Hur subiram ao cume do outeiro.

[[v2-17-11]]

^<<v2-17-11,11>>^ E acontecia que quando Moisés levantava a mão, prevalecia Israel; mas quando ele abaixava a mão, prevalecia Amaleque.

[[v2-17-12]]

^<<v2-17-12,12>>^ As mãos de Moisés, porém, ficaram cansadas; por isso tomaram uma pedra, e a puseram debaixo dele, e ele sentou-se nela; Arão e Hur sustentavam-lhe as mãos, um de um lado e o outro do outro; assim ficaram as suas mãos firmes até o pôr do sol.

[[v2-17-13]]

^<<v2-17-13,13>>^ Assim Josué prostrou a Amaleque e a seu povo, ao fio da espada.

[[v2-17-14]]

^<<v2-17-14,14>>^ Então disse o Senhor a Moisés: Escreve isto para memorial num livro, e relata-o aos ouvidos de Josué; que eu hei de riscar totalmente a memória de Amaleque de debaixo do céu.

[[v2-17-15]]

^<<v2-17-15,15>>^ Pelo que Moisés edificou um altar, ao qual chamou Jeová-Níssi.

[[v2-17-16]]

^<<v2-17-16,16>>^ E disse: Porquanto jurou o Senhor que ele fará guerra contra Amaleque de geração em geração.

'''

xref:002-exodo/002-exodo-016.adoc#v2-16-0[&#60; Capítulo Anterior] | <<v2-17-0,Topo>> | xref:002-exodo/002-exodo-018.adoc#v2-18-0[Próximo Capítulo &#62;]