include::./index.adoc[]

[[v2-32-0]]
=== Êxodo, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-32-1]]

^<<v2-32-1,1>>^ Mas o povo, vendo que Moisés tardava em descer do monte, acercou-se de Arão, e lhe disse: Levanta-te, faze-nos um deus que vá adiante de nós; porque, quanto a esse Moisés, o homem que nos tirou da terra do Egito, não sabemos o que lhe aconteceu.

[[v2-32-2]]

^<<v2-32-2,2>>^ E Arão lhes disse: Tirai os pendentes de ouro que estão nas orelhas de vossas mulheres, de vossos filhos e de vossas filhas, e trazei-mos.

[[v2-32-3]]

^<<v2-32-3,3>>^ Então todo o povo, tirando os pendentes de ouro que estavam nas suas orelhas, os trouxe a Arão;

[[v2-32-4]]

^<<v2-32-4,4>>^ ele os recebeu de suas mãos, e com um buril deu forma ao ouro, e dele fez um bezerro de fundição. Então eles exclamaram: Eis aqui, ó Israel, o teu deus, que te tirou da terra do Egito.

[[v2-32-5]]

^<<v2-32-5,5>>^ E Arão, vendo isto, edificou um altar diante do bezerro e, fazendo uma proclamação, disse: Amanhã haverá festa ao Senhor.

[[v2-32-6]]

^<<v2-32-6,6>>^ No dia seguinte levantaram-se cedo, ofereceram holocaustos, e trouxeram ofertas pacíficas; e o povo sentou-se a comer e a beber; depois levantou-se para folgar.

[[v2-32-7]]

^<<v2-32-7,7>>^ Então disse o Senhor a Moisés: Vai, desce; porque o teu povo, que fizeste subir da terra do Egito, se corrompeu;

[[v2-32-8]]

^<<v2-32-8,8>>^ depressa se desviou do caminho que eu lhe ordenei; eles fizeram para si um bezerro de fundição, e adoraram-no, e lhe ofereceram sacrifícios, e disseram: Eis aqui, ó Israel, o teu deus, que te tirou da terra do Egito.

[[v2-32-9]]

^<<v2-32-9,9>>^ Disse mais o Senhor a Moisés: Tenho observado este povo, e eis que é povo de dura cerviz.

[[v2-32-10]]

^<<v2-32-10,10>>^ Agora, pois, deixa-me, para que a minha ira se acenda contra eles, e eu os consuma; e eu farei de ti uma grande nação.

[[v2-32-11]]

^<<v2-32-11,11>>^ Moisés, porém, suplicou ao Senhor seu Deus, e disse: Ó Senhor, por que se acende a tua ira contra o teu povo, que tiraste da terra do Egito com grande força e com forte mão?

[[v2-32-12]]

^<<v2-32-12,12>>^ Por que hão de falar os egípcios, dizendo: Para mal os tirou, para matá-los nos montes, e para destruí-los da face da terra?. Torna-te da tua ardente ira, e arrepende-te deste mal contra o teu povo.

[[v2-32-13]]

^<<v2-32-13,13>>^ Lembra-te de Abraão, de Isaque, e de Israel, teus servos, aos quais por ti mesmo juraste, e lhes disseste: Multiplicarei os vossos descendentes como as estrelas do céu, e lhes darei toda esta terra de que tenho falado, e eles a possuirão por herança para sempre.

[[v2-32-14]]

^<<v2-32-14,14>>^ Então o Senhor se arrependeu do mal que dissera que havia de fazer ao seu povo.

[[v2-32-15]]

^<<v2-32-15,15>>^ E virou-se Moisés, e desceu do monte com as duas tábuas do testemunho na mão, tábuas escritas de ambos os lados; de um e de outro lado estavam escritas.

[[v2-32-16]]

^<<v2-32-16,16>>^ E aquelas tábuas eram obra de Deus; também a escritura era a mesma escritura de Deus, esculpida nas tábuas.

[[v2-32-17]]

^<<v2-32-17,17>>^ Ora, ouvindo Josué a voz do povo que jubilava, disse a Moisés: Alarido de guerra há no arraial.

[[v2-32-18]]

^<<v2-32-18,18>>^ Respondeu-lhe Moisés: Não é alarido dos vitoriosos, nem alarido dos vencidos, mas é a voz dos que cantam que eu ouço.

[[v2-32-19]]

^<<v2-32-19,19>>^ Chegando ele ao arraial e vendo o bezerro e as danças, acendeu-se-lhe a ira, e ele arremessou das mãos as tábuas, e as despedaçou ao pé do monte.

[[v2-32-20]]

^<<v2-32-20,20>>^ Então tomou o bezerro que tinham feito, e queimou-o no fogo; e, moendo-o até que se tornou em pó, o espargiu sobre a água, e deu-o a beber aos filhos de Israel.

[[v2-32-21]]

^<<v2-32-21,21>>^ E perguntou Moisés a Arão: Que te fez este povo, que sobre ele trouxeste tamanho pecado?.

[[v2-32-22]]

^<<v2-32-22,22>>^ Ao que respondeu Arão: Não se acenda a ira do meu senhor; tu conheces o povo, como ele é inclinado ao mal.

[[v2-32-23]]

^<<v2-32-23,23>>^ Pois eles me disseram: Faze-nos um deus que vá adiante de nós; porque, quanto a esse Moisés, o homem que nos tirou da terra do Egito, não sabemos o que lhe aconteceu.

[[v2-32-24]]

^<<v2-32-24,24>>^ Então eu lhes disse: Quem tem ouro, arranque-o. Assim mo deram; e eu o lancei no fogo, e saiu este bezerro.

[[v2-32-25]]

^<<v2-32-25,25>>^ Quando, pois, Moisés viu que o povo estava desenfreado &#123;porque Arão o havia desenfreado, para escárnio entre os seus inimigos&#125;,

[[v2-32-26]]

^<<v2-32-26,26>>^ pôs-se em pé à entrada do arraial, e disse: Quem está ao lado do Senhor, venha a mim. Ao que se ajuntaram a ele todos os filhos de Levi.

[[v2-32-27]]

^<<v2-32-27,27>>^ Então ele lhes disse: Assim diz o Senhor, o Deus de Israel: Cada um ponha a sua espada sobre a coxa; e passai e tornai pelo arraial de porta em porta, e mate cada um a seu irmão, e cada um a seu amigo, e cada um a seu vizinho.

[[v2-32-28]]

^<<v2-32-28,28>>^ E os filhos de Levi fizeram conforme a palavra de Moisés; e caíram do povo naquele dia cerca de três mil homens.

[[v2-32-29]]

^<<v2-32-29,29>>^ Porquanto Moisés tinha dito: Consagrai-vos hoje ao Senhor; porque cada um será contra o seu filho, e contra o seu irmão; para que o Senhor vos conceda hoje uma bênção.

[[v2-32-30]]

^<<v2-32-30,30>>^ No dia seguinte disse Moisés ao povo Vós tendes cometido grande pecado; agora porém subirei ao Senhor; porventura farei expiação por vosso pecado.

[[v2-32-31]]

^<<v2-32-31,31>>^ Assim tornou Moisés ao Senhor, e disse: Oh! este povo cometeu um grande pecado, fazendo para si um deus de ouro.

[[v2-32-32]]

^<<v2-32-32,32>>^ Agora, pois, perdoa o seu pecado; ou se não, risca-me do teu livro, que tens escrito.

[[v2-32-33]]

^<<v2-32-33,33>>^ Então disse o Senhor a Moisés: Aquele que tiver pecado contra mim, a este riscarei do meu livro.

[[v2-32-34]]

^<<v2-32-34,34>>^ Vai pois agora, conduze este povo para o lugar de que te hei dito; eis que o meu anjo irá adiante de ti; porém no dia da minha visitação, sobre eles visitarei o seu pecado.

[[v2-32-35]]

^<<v2-32-35,35>>^ Feriu, pois, o Senhor ao povo, por ter feito o bezerro que Arão formara.

'''

xref:002-exodo/002-exodo-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodo/002-exodo-033.adoc#v2-33-0[Próximo Capítulo &#62;]