include::./index.adoc[]

[[v2-16-0]]
=== Êxodo, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-16-1]]

^<<v2-16-1,1>>^ Depois partiram de Elim; e veio toda a congregação dos filhos de Israel ao deserto de Sim, que está entre Elim e Sinai, aos quinze dias do segundo mês depois que saíram da terra do Egito.

[[v2-16-2]]

^<<v2-16-2,2>>^ E toda a congregação dos filhos de Israel murmurou contra Moisés e contra Arão no deserto.

[[v2-16-3]]

^<<v2-16-3,3>>^ Pois os filhos de Israel lhes disseram: Quem nos dera que tivéssemos morrido pela mão do Senhor na terra do Egito, quando estávamos sentados junto às panelas de carne, quando comíamos pão até fartar! porque nos tendes tirado para este deserto, para matardes de fome a toda esta multidão.

[[v2-16-4]]

^<<v2-16-4,4>>^ Então disse o Senhor a Moisés: Eis que vos farei chover pão do céu; e sairá o povo e colherá diariamente a porção para cada dia, para que eu o prove se anda em minha lei ou não.

[[v2-16-5]]

^<<v2-16-5,5>>^ Mas ao sexto dia prepararão o que colherem; e será o dobro do que colhem cada dia.

[[v2-16-6]]

^<<v2-16-6,6>>^ Disseram, pois, Moisés e Arão a todos os filhos de Israel: tarde sabereis que o Senhor é quem vos tirou da terra do Egito,

[[v2-16-7]]

^<<v2-16-7,7>>^ e amanhã vereis a glória do Senhor, porquanto ele ouviu as vossas murmurações contra o Senhor; e quem somos nós, para que murmureis contra nós?

[[v2-16-8]]

^<<v2-16-8,8>>^ Disse mais Moisés: Isso será quando o Senhor à tarde vos der carne para comer, e pela manhã pão a fartar, porquanto o Senhor ouve as vossas murmurações, com que murmurais contra ele; e quem somos nós? As vossas murmurações não são contra nós, mas sim contra o Senhor.

[[v2-16-9]]

^<<v2-16-9,9>>^ Depois disse Moisés a Arão: Dize a toda a congregação dos filhos de Israel: Chegai-vos à presença do Senhor, porque ele ouviu as vossas murmurações.

[[v2-16-10]]

^<<v2-16-10,10>>^ E quando Arão falou a toda a congregação dos filhos de Israel, estes olharam para o deserto, e eis que a glória do Senhor, apareceu na nuvem.

[[v2-16-11]]

^<<v2-16-11,11>>^ Então o Senhor falou a Moisés, dizendo:

[[v2-16-12]]

^<<v2-16-12,12>>^ Tenho ouvido as murmurações dos filhos de Israel; dize-lhes: À tardinha comereis carne, e pela manhã vos fartareis de pão; e sabereis que eu sou o Senhor vosso Deus.

[[v2-16-13]]

^<<v2-16-13,13>>^ E aconteceu que à tarde subiram codornizes, e cobriram o arraial; e pela manhã havia uma camada de orvalho ao redor do arraial.

[[v2-16-14]]

^<<v2-16-14,14>>^ Quando desapareceu a camada de orvalho, eis que sobre a superfície do deserto estava uma coisa miúda, semelhante a escamas, coisa miúda como a geada sobre a terra.

[[v2-16-15]]

^<<v2-16-15,15>>^ E, vendo-a os filhos de Israel, disseram uns aos outros: Que é isto? porque não sabiam o que era. Então lhes disse Moisés: Este é o pão que o Senhor vos deu para comer.

[[v2-16-16]]

^<<v2-16-16,16>>^ Isto é o que o Senhor ordenou: Colhei dele cada um conforme o que pode comer; um gômer para cada cabeça, segundo o número de pessoas; cada um tomará para os que se acharem na sua tenda.

[[v2-16-17]]

^<<v2-16-17,17>>^ Assim o fizeram os filhos de Israel; e colheram uns mais e outros menos.

[[v2-16-18]]

^<<v2-16-18,18>>^ Quando, porém, o mediam com o gômer, nada sobejava ao que colhera muito, nem faltava ao que colhera pouco; colhia cada um tanto quanto podia comer.

[[v2-16-19]]

^<<v2-16-19,19>>^ Também disse-lhes Moisés: Ninguém deixe dele para amanhã.

[[v2-16-20]]

^<<v2-16-20,20>>^ Eles, porém, não deram ouvidos a Moisés, antes alguns dentre eles deixaram dele para o dia seguinte; e criou bichos, e cheirava mal; por isso indignou-se Moisés contra eles.

[[v2-16-21]]

^<<v2-16-21,21>>^ Colhiam-no, pois, pela manhã, cada um conforme o que podia comer; porque, vindo o calor do sol, se derretia.

[[v2-16-22]]

^<<v2-16-22,22>>^ Mas ao sexto dia colheram pão em dobro, dois gômeres para cada um; pelo que todos os principais da congregação vieram, e contaram-no a Moisés.

[[v2-16-23]]

^<<v2-16-23,23>>^ E ele lhes disse: Isto é o que o Senhor tem dito: Amanhã é repouso, sábado santo ao Senhor; o que quiserdes assar ao forno, assai-o, e o que quiserdes cozer em água, cozei-o em água; e tudo o que sobejar, ponde-o de lado para vós, guardando-o para amanhã.

[[v2-16-24]]

^<<v2-16-24,24>>^ Guardaram-no, pois, até o dia seguinte, como Moisés tinha ordenado; e não cheirou mal, nem houve nele bicho algum.

[[v2-16-25]]

^<<v2-16-25,25>>^ Então disse Moisés: Comei-o hoje, porquanto hoje é o sábado do Senhor; hoje não o achareis no campo.

[[v2-16-26]]

^<<v2-16-26,26>>^ Seis dias o colhereis, mas o sétimo dia é o sábado; nele não haverá.

[[v2-16-27]]

^<<v2-16-27,27>>^ Mas aconteceu ao sétimo dia que saíram alguns do povo para o colher, e não o acharam.

[[v2-16-28]]

^<<v2-16-28,28>>^ Então disse o Senhor a Moisés: Até quando recusareis guardar os meus mandamentos e as minhas leis?

[[v2-16-29]]

^<<v2-16-29,29>>^ Vede, visto que o Senhor vos deu o sábado, por isso ele no sexto dia vos dá pão para dois dias; fique cada um no seu lugar, não saia ninguém do seu lugar no sétimo dia.

[[v2-16-30]]

^<<v2-16-30,30>>^ Assim repousou o povo no sétimo dia.

[[v2-16-31]]

^<<v2-16-31,31>>^ A casa de Israel deu-lhe o nome de maná. Era como semente de coentro; era branco, e tinha o sabor de bolos de mel.

[[v2-16-32]]

^<<v2-16-32,32>>^ E disse Moisés: Isto é o que o Senhor ordenou: Dele enchereis um gômer, o qual se guardará para as vossas gerações, para que elas vejam o pão que vos dei a comer no deserto, quando eu vos tirei da terra do Egito.

[[v2-16-33]]

^<<v2-16-33,33>>^ Disse também Moisés a Arão: Toma um vaso, mete nele um gômer cheio de maná e põe-no diante do Senhor, a fim de que seja guardado para as vossas gerações.

[[v2-16-34]]

^<<v2-16-34,34>>^ Como o Senhor tinha ordenado a Moisés, assim Arão o pôs diante do testemunho, para ser guardado.

[[v2-16-35]]

^<<v2-16-35,35>>^ Ora, os filhos de Israel comeram o maná quarenta anos, até que chegaram a uma terra habitada; comeram o maná até que chegaram aos termos da terra de Canaã.

[[v2-16-36]]

^<<v2-16-36,36>>^ Um gômer é a décima parte de uma efa.

'''

xref:002-exodo/002-exodo-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodo/002-exodo-017.adoc#v2-17-0[Próximo Capítulo &#62;]