include::./index.adoc[]

[[v2-1-0]]
=== Êxodo, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-1-1]]

^<<v2-1-1,1>>^ Ora, estes são os nomes dos filhos de Israel, que entraram no Egito; entraram com Jacó, cada um com a sua família:

[[v2-1-2]]

^<<v2-1-2,2>>^ Rúben, Simeão, Levi, e Judá;

[[v2-1-3]]

^<<v2-1-3,3>>^ Issacar, Zebulom e Benjamim;

[[v2-1-4]]

^<<v2-1-4,4>>^ Dã e Naftali, Gade e Aser.

[[v2-1-5]]

^<<v2-1-5,5>>^ Todas as almas, pois, que procederam da coxa de Jacó, foram setenta; José, porém, já estava no Egito.

[[v2-1-6]]

^<<v2-1-6,6>>^ Morreu, pois, José, e todos os seus irmãos, e toda aquela geração.

[[v2-1-7]]

^<<v2-1-7,7>>^ Depois os filhos de Israel frutificaram e aumentaram muito, multiplicaram-se e tornaram-se sobremaneira fortes, de modo que a terra se encheu deles.

[[v2-1-8]]

^<<v2-1-8,8>>^ Entrementes se levantou sobre o Egito um novo rei, que não conhecera a José.

[[v2-1-9]]

^<<v2-1-9,9>>^ Disse ele ao seu povo: Eis que o povo de Israel é mais numeroso e mais forte do que nos.

[[v2-1-10]]

^<<v2-1-10,10>>^ Eia, usemos de astúcia para com ele, para que não se multiplique, e aconteça que, vindo guerra, ele também se ajunte com os nossos inimigos, e peleje contra nós e se retire da terra.

[[v2-1-11]]

^<<v2-1-11,11>>^ Portanto puseram sobre eles feitores, para os afligirem com suas cargas. Assim os israelitas edificaram para Faraó cidades armazéns, Pitom e Ramessés.

[[v2-1-12]]

^<<v2-1-12,12>>^ Mas quanto mais os egípcios afligiam o povo de Israel, tanto mais este se multiplicava e se espalhava; de maneira que os egípcios se enfadavam por causa dos filhos de Israel.

[[v2-1-13]]

^<<v2-1-13,13>>^ Por isso os egípcios faziam os filhos de Israel servir com dureza;

[[v2-1-14]]

^<<v2-1-14,14>>^ assim lhes amarguravam a vida com pesados serviços em barro e em tijolos, e com toda sorte de trabalho no campo, enfim com todo o seu serviço, em que os faziam servir com dureza.

[[v2-1-15]]

^<<v2-1-15,15>>^ Falou o rei do Egito às parteiras das hebréias, das quais uma se chamava Sifrá e a outra Puá,

[[v2-1-16]]

^<<v2-1-16,16>>^ dizendo: Quando ajudardes no parto as hebréias, e as virdes sobre os assentos, se for filho, matá-lo-eis; mas se for filha, viverá.

[[v2-1-17]]

^<<v2-1-17,17>>^ As parteiras, porém, temeram a Deus e não fizeram como o rei do Egito lhes ordenara, antes conservavam os meninos com vida.

[[v2-1-18]]

^<<v2-1-18,18>>^ Pelo que o rei do Egito mandou chamar as parteiras e as interrogou: Por que tendes feito isto e guardado os meninos com vida?

[[v2-1-19]]

^<<v2-1-19,19>>^ Responderam as parteiras a Faraó: É que as mulheres hebréias não são como as egípcias; pois são vigorosas, e já têm dado à luz antes que a parteira chegue a elas.

[[v2-1-20]]

^<<v2-1-20,20>>^ Portanto Deus fez bem às parteiras. E o povo se aumentou, e se fortaleceu muito.

[[v2-1-21]]

^<<v2-1-21,21>>^ Também aconteceu que, como as parteiras temeram a Deus, ele lhes estabeleceu as casas.

[[v2-1-22]]

^<<v2-1-22,22>>^ Então ordenou Faraó a todo o seu povo, dizendo: A todos os filhos que nascerem lançareis no rio, mas a todas as filhas guardareis com vida.

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodo/002-exodo-002.adoc#v2-2-0[Próximo Capítulo &#62;]