include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-6-1]]

^<<v2-6-1,1>>^ Então disse o Senhor a Moisés: Agora verás o que hei de fazer a Faraó; pois por uma poderosa mão os deixará ir, sim, por uma poderosa mão os lançará de sua terra.

[[v2-6-2]]

^<<v2-6-2,2>>^ Falou mais Deus a Moisés, e disse-lhe: Eu sou Jeová.

[[v2-6-3]]

^<<v2-6-3,3>>^ Apareci a Abraão, a Isaque e a Jacó, como o Deus Todo-Poderoso; mas pelo meu nome Jeová, não lhes fui conhecido.

[[v2-6-4]]

^<<v2-6-4,4>>^ Estabeleci o meu pacto com eles para lhes dar a terra de Canaã, a terra de suas peregrinações, na qual foram peregrinos.

[[v2-6-5]]

^<<v2-6-5,5>>^ Ademais, tenho ouvido o gemer dos filhos de Israel, aos quais os egípcios vêm escravizando; e lembrei-me do meu pacto.

[[v2-6-6]]

^<<v2-6-6,6>>^ Portanto dize aos filhos de Israel: Eu sou Jeová; eu vos tirarei de debaixo das cargas dos egípcios, livrar-vos-ei da sua servidão, e vos resgatarei com braço estendido e com grandes juízos.

[[v2-6-7]]

^<<v2-6-7,7>>^ Eu vos tomarei por meu povo e serei vosso Deus; e vós sabereis que eu sou Jeová vosso Deus, que vos tiro de debaixo das cargas dos egípcios.

[[v2-6-8]]

^<<v2-6-8,8>>^ Eu vos introduzirei na terra que jurei dar a Abraão, a Isaque e a Jacó; e vo-la darei por herança. Eu sou Jeová.

[[v2-6-9]]

^<<v2-6-9,9>>^ Assim falou Moisés aos filhos de Israel, mas eles não lhe deram ouvidos, por causa da angústia de espírito e da dura servidão.

[[v2-6-10]]

^<<v2-6-10,10>>^ Falou mais o Senhor a Moisés, dizendo:

[[v2-6-11]]

^<<v2-6-11,11>>^ Vai, fala a Faraó, rei do Egito, que deixe sair os filhos de Israel da sua terra.

[[v2-6-12]]

^<<v2-6-12,12>>^ Moisés, porém, respondeu perante o Senhor, dizendo: Eis que os filhos de Israel não me têm ouvido: como, pois, me ouvirá Faraó a mim, que sou incircunciso de lábios?

[[v2-6-13]]

^<<v2-6-13,13>>^ Todavia o Senhor falou a Moisés e a Arão, e deu-lhes mandamento para os filhos de Israel, e para Faraó, rei do Egito, a fim de tirarem os filhos de Israel da terra do Egito..

[[v2-6-14]]

^<<v2-6-14,14>>^ Estes são os cabeças das casas de seus pais: Os filhos de Rúben o primogênito de Israel: Hanoque e Palu, Hezrom e Carmi; estas são as famílias de Rúben.

[[v2-6-15]]

^<<v2-6-15,15>>^ E os filhos de Simeão: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma cananéia; estas são as famílias de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ E estes são os nomes dos filhos de Levi, segundo as suas gerações: Gérson, Coate e Merári; e os anos da vida de Levi foram cento e trinta e sete anos.

[[v2-6-17]]

^<<v2-6-17,17>>^ Os filhos de Gérson: Líbni e Simei, segundo as suas famílias.

[[v2-6-18]]

^<<v2-6-18,18>>^ Os filhos de Coate: Anrão, Izar, Hebrom e Uziel; e os anos da vida de Coate foram cento e trinta e três anos.

[[v2-6-19]]

^<<v2-6-19,19>>^ Os filhos de Merari: Mali e Musi; estas são as famílias de Levi, segundo as suas gerações.

[[v2-6-20]]

^<<v2-6-20,20>>^ Ora, Anrão tomou por mulher a Joquebede, sua tia; e ela lhe deu Arão e Moisés; e os anos da vida de Anrão foram cento e trinta e sete anos.

[[v2-6-21]]

^<<v2-6-21,21>>^ Os filhos de Izar: Corá, Nofegue e Zicri.

[[v2-6-22]]

^<<v2-6-22,22>>^ Os filhos de Uziel: Misael, Elzafã e Sitri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Arão tomou por mulher a Eliseba, filha de Aminadabe, irmã de Nasom; e ela lhe deu Nadabe, Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ Os filhos de Corá: Assir, Elcana e Abiasafe; estas são as famílias dos coraítas.

[[v2-6-25]]

^<<v2-6-25,25>>^ Eleazar, filho de Arão, tomou por mulher uma das filhas de Putiel; e ela lhe deu Finéias; estes são os chefes das casa, paternas dos levitas, segundo as suas famílias.

[[v2-6-26]]

^<<v2-6-26,26>>^ Estes são Arão e Moisés, aos quais o Senhor disse: Tirai os filhos de Israel da terra do Egito, segundo os seus exércitos.

[[v2-6-27]]

^<<v2-6-27,27>>^ Foram eles os que falaram a Faraó, rei do Egito, a fim de tirarem do Egito os filhos de Israel; este Moisés e este Arão.

[[v2-6-28]]

^<<v2-6-28,28>>^ No dia em que o Senhor falou a Moisés na terra do Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ disse o Senhor a Moisés: Eu sou Jeová; dize a Faraó, rei do Egito, tudo quanto eu te digo.

[[v2-6-30]]

^<<v2-6-30,30>>^ Respondeu Moisés perante o Senhor: Eis que eu sou incircunciso de lábios; como, pois, me ouvirá Faraó;

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]