include::./index.adoc[]

[[v2-20-0]]
=== Êxodo, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-20-1]]

^<<v2-20-1,1>>^ Então falou Deus todas estas palavras, dizendo:

[[v2-20-2]]

^<<v2-20-2,2>>^ Eu sou o Senhor teu Deus, que te tirei da terra do Egito, da casa da servidão.

[[v2-20-3]]

^<<v2-20-3,3>>^ Não terás outros deuses diante de mim.

[[v2-20-4]]

^<<v2-20-4,4>>^ Não farás para ti imagem esculpida, nem figura alguma do que há em cima no céu, nem em baixo na terra, nem nas águas debaixo da terra.

[[v2-20-5]]

^<<v2-20-5,5>>^ Não te encurvarás diante delas, nem as servirás; porque eu, o Senhor teu Deus, sou Deus zeloso, que visito a iniqüidade dos pais nos filhos até a terceira e quarta geração daqueles que me odeiam.

[[v2-20-6]]

^<<v2-20-6,6>>^ e uso de misericórdia com milhares dos que me amam e guardam os meus mandamentos.

[[v2-20-7]]

^<<v2-20-7,7>>^ Não tomarás o nome do Senhor teu Deus em vão; porque o Senhor não terá por inocente aquele que tomar o seu nome em vão.

[[v2-20-8]]

^<<v2-20-8,8>>^ Lembra-te do dia do sábado, para o santificar.

[[v2-20-9]]

^<<v2-20-9,9>>^ Seis dias trabalharás, e farás todo o teu trabalho;

[[v2-20-10]]

^<<v2-20-10,10>>^ mas o sétimo dia é o sábado do Senhor teu Deus. Nesse dia não farás trabalho algum, nem tu, nem teu filho, nem tua filha, nem o teu servo, nem a tua serva, nem o teu animal, nem o estrangeiro que está dentro das tuas portas.

[[v2-20-11]]

^<<v2-20-11,11>>^ Porque em seis dias fez o Senhor o céu e a terra, o mar e tudo o que neles há, e ao sétimo dia descansou; por isso o Senhor abençoou o dia do sábado, e o santificou.

[[v2-20-12]]

^<<v2-20-12,12>>^ Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o Senhor teu Deus te dá.

[[v2-20-13]]

^<<v2-20-13,13>>^ Não matarás.

[[v2-20-14]]

^<<v2-20-14,14>>^ Não adulterarás.

[[v2-20-15]]

^<<v2-20-15,15>>^ Não furtarás.

[[v2-20-16]]

^<<v2-20-16,16>>^ Não dirás falso testemunho contra o teu próximo.

[[v2-20-17]]

^<<v2-20-17,17>>^ Não cobiçarás a casa do teu próximo, não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma do teu próximo.

[[v2-20-18]]

^<<v2-20-18,18>>^ Ora, todo o povo presenciava os trovões, e os relâmpagos, e o sonido da buzina, e o monte a fumegar; e o povo, vendo isso, estremeceu e pôs-se de longe.

[[v2-20-19]]

^<<v2-20-19,19>>^ E disseram a Moisés: Fala-nos tu mesmo, e ouviremos; mas não fale Deus conosco, para que não morramos.

[[v2-20-20]]

^<<v2-20-20,20>>^ Respondeu Moisés ao povo: Não temais, porque Deus veio para vos provar, e para que o seu temor esteja diante de vós, a fim de que não pequeis.

[[v2-20-21]]

^<<v2-20-21,21>>^ Assim o povo estava em pé de longe; Moisés, porém, se chegou às trevas espessas onde Deus estava.

[[v2-20-22]]

^<<v2-20-22,22>>^ Então disse o Senhor a Moisés: Assim dirás aos filhos de Israel: Vós tendes visto que do céu eu vos falei.

[[v2-20-23]]

^<<v2-20-23,23>>^ Não fareis outros deuses comigo; deuses de prata, ou deuses de ouro, não os fareis para vós.

[[v2-20-24]]

^<<v2-20-24,24>>^ um altar de terra me farás, e sobre ele sacrificarás os teus holocaustos, e as tuas ofertas pacíficas, as tuas ovelhas e os teus bois. Em todo lugar em que eu fizer recordar o meu nome, virei a ti e te abençoarei.

[[v2-20-25]]

^<<v2-20-25,25>>^ E se me fizeres um altar de pedras, não o construirás de pedras lavradas; pois se sobre ele levantares o teu buril, profaná-lo-ás.

[[v2-20-26]]

^<<v2-20-26,26>>^ Também não subirás ao meu altar por degraus, para que não seja ali exposta a tua nudez.

'''

xref:002-exodo/002-exodo-019.adoc#v2-19-0[&#60; Capítulo Anterior] | <<v2-20-0,Topo>> | xref:002-exodo/002-exodo-021.adoc#v2-21-0[Próximo Capítulo &#62;]