include::./index.adoc[]

[[v2-38-0]]
=== Êxodo, 38
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-38-1]]

^<<v2-38-1,1>>^ Fez também o altar do holocausto de madeira de acácia; de cinco côvados era o seu comprimento e de cinco côvados a sua largura, quadrado, e de três côvados a sua altura.

[[v2-38-2]]

^<<v2-38-2,2>>^ E fez-lhe pontas nos seus quatro cantos; as suas pontas formavam uma só peça com ele; e cobriu-o de bronze.

[[v2-38-3]]

^<<v2-38-3,3>>^ Fez também todos os utensílios do altar: os cinzeiros, as pás, as bacias, os garfos e os braseiros; todos os seus utensílios fez de bronze.

[[v2-38-4]]

^<<v2-38-4,4>>^ Fez também para o altar um crivo de bronze em forma de rede, em baixo da borda ao redor, chegando ele até o meio do altar.

[[v2-38-5]]

^<<v2-38-5,5>>^ E fundiu quatro argolas para as quatro extremidades do crivo de bronze, como lugares dos varais.

[[v2-38-6]]

^<<v2-38-6,6>>^ E fez os varais de madeira de acácia, e os cobriu de bronze.

[[v2-38-7]]

^<<v2-38-7,7>>^ E meteu os varais pelas argolas aos lados do altar, para com eles se levar o altar; fê-lo oco, de tábuas.

[[v2-38-8]]

^<<v2-38-8,8>>^ Fez também a pia de bronze com a sua base de bronze, dos espelhos das mulheres que se reuniam e ministravam à porta da tenda da revelação.

[[v2-38-9]]

^<<v2-38-9,9>>^ Fez também o átrio. Para o lado meridional as cortinas eram de linho fino torcido, de cem côvados de comprimento.

[[v2-38-10]]

^<<v2-38-10,10>>^ As suas colunas eram vinte, e vinte as suas bases, todas de bronze; os colchetes das colunas e as suas faixas eram de prata.

[[v2-38-11]]

^<<v2-38-11,11>>^ Para o lado setentrional as cortinas eram de cem côvados; as suas colunas eram vinte, e vinte as suas bases, todas de bronze; os colchetes das colunas e as suas faixas eram de prata.

[[v2-38-12]]

^<<v2-38-12,12>>^ Para o lado ocidental as cortinas eram de cinqüenta côvados; as suas colunas eram dez, e as suas bases dez; os colchetes das colunas e as suas faixas eram de prata.

[[v2-38-13]]

^<<v2-38-13,13>>^ E para o lado oriental eram as cortinas de cinqüenta côvados.

[[v2-38-14]]

^<<v2-38-14,14>>^ As cortinas para um lado da porta eram de quinze côvados; as suas colunas eram três e as suas bases três.

[[v2-38-15]]

^<<v2-38-15,15>>^ Do mesmo modo para o outro lado; de um e de outro lado da porta do átrio havia cortinas de quinze côvados; as suas colunas eram três e as suas bases três.

[[v2-38-16]]

^<<v2-38-16,16>>^ Todas as cortinas do átrio ao redor eram de linho fino torcido.

[[v2-38-17]]

^<<v2-38-17,17>>^ As bases das colunas eram de bronze; os colchetes das colunas e as suas faixas eram de prata; o revestimento dos seus capitéis era de prata; e todas as colunas do átrio eram cingidas de faixas de prata.

[[v2-38-18]]

^<<v2-38-18,18>>^ O reposteiro da porta do átrio era de azul, púrpura, carmesim e linho fino torcido, obra de bordador; o comprimento era de vinte côvados, e a altura, na largura, de cinco côvados, conforme a altura das cortinas do átrio.

[[v2-38-19]]

^<<v2-38-19,19>>^ As suas colunas eram quatro, e quatro as suas bases, todas de bronze; os seus colchetes eram de prata, como também o revestimento dos capitéis, e as suas faixas.

[[v2-38-20]]

^<<v2-38-20,20>>^ E todas as estacas do tabernáculo e do átrio ao redor eram de bronze.

[[v2-38-21]]

^<<v2-38-21,21>>^ Esta é a enumeração das coisas para o tabernáculo, a saber, o tabernáculo do testemunho, que por ordem de Moisés foram contadas para o ministério dos levitas, por intermédio de Itamar, filho de Arão, o sacerdote.

[[v2-38-22]]

^<<v2-38-22,22>>^ Fez, pois, Bezalel, filho de Uri, filho de Hur, da tribo de Judá, tudo quanto o Senhor tinha ordenado a Moisés;

[[v2-38-23]]

^<<v2-38-23,23>>^ e com ele Aoliabe, filho de Aisamaque, da tribo de Dã, gravador, desenhista, e bordador em azul, púrpura, carmesim e linho fino.

[[v2-38-24]]

^<<v2-38-24,24>>^ Todo o ouro gasto na obra, em toda a obra do santuário, a saber, o ouro da oferta, foi vinte e nove talentos e setecentos e trinta siclos, conforme o siclo do santuário.

[[v2-38-25]]

^<<v2-38-25,25>>^ A prata dos arrolados da congregação montou em cem talentos e mil setecentos setenta e cinco siclos, conforme o siclo do santuário;

[[v2-38-26]]

^<<v2-38-26,26>>^ um beca para cada cabeça, isto é, meio siclo, conforme o siclo do santuário, de todo aquele que passava para os arrolados, da idade de vinte anos e acima, que foram seiscentos e três mil quinhentos e cinqüenta.

[[v2-38-27]]

^<<v2-38-27,27>>^ E houve cem talentos de prata para fundir as bases do santuário e as bases do véu; para cem bases eram cem talentos, um talento para cada base.

[[v2-38-28]]

^<<v2-38-28,28>>^ Mas dos mil setecentos e setenta e cinco siclos, fez colchetes para as colunas, e cobriu os seus capitéis e fez-lhes as faixas.

[[v2-38-29]]

^<<v2-38-29,29>>^ E o bronze da oferta foi setenta talentos e dois mil e quatrocentos siclos.

[[v2-38-30]]

^<<v2-38-30,30>>^ Dele fez as bases da porta da tenda da revelação, o altar de bronze, e o crivo de bronze para ele, todos os utensílios do altar,

[[v2-38-31]]

^<<v2-38-31,31>>^ as bases do átrio ao redor e as bases da porta do átrio, todas as estacas do tabernáculo e todas as estacas do átrio ao redor.

'''

xref:002-exodo/002-exodo-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodo/002-exodo-039.adoc#v2-39-0[Próximo Capítulo &#62;]