include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-35-1]]

^<<v2-35-1,1>>^ Então Moisés convocou toda a congregação dos filhos de Israel, e disse-lhes: Estas são as palavras que o Senhor ordenou que cumprísseis.

[[v2-35-2]]

^<<v2-35-2,2>>^ Seis dias se trabalhará, mas o sétimo dia vos será santo, sábado de descanso solene ao Senhor; todo aquele que nele fizer qualquer trabalho será morto.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não acendereis fogo em nenhuma das vossas moradas no dia do sábado.

[[v2-35-4]]

^<<v2-35-4,4>>^ Disse mais Moisés a toda a congregação dos filhos de Israel: Esta é a palavra que o Senhor ordenou dizendo:

[[v2-35-5]]

^<<v2-35-5,5>>^ Tomai de entre vós uma oferta para o Senhor; cada um cujo coração é voluntariamente disposto a trará por oferta alçada ao Senhor: ouro, prata e bronze,

[[v2-35-6]]

^<<v2-35-6,6>>^ como também azul, púrpura, carmesim, linho fino, pelos de cabras,

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiros tintas de vermelho, peles de golfinhos, madeira de acácia,

[[v2-35-8]]

^<<v2-35-8,8>>^ azeite para a luz, especiarias para o óleo da unção e para o incenso aromático,

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de berilo e pedras de engaste para o éfode e para o peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ E venham todos os homens hábeis entre vós, e façam tudo o que o Senhor tem ordenado:

[[v2-35-11]]

^<<v2-35-11,11>>^ o tabernáculo, a sua tenda e a sua coberta, os seus colchetes e as suas tábuas, os seus travessões, as suas colunas e as suas bases;

[[v2-35-12]]

^<<v2-35-12,12>>^ a arca e os seus varais, o propiciatório, e o véu e reposteiro;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa e os seus varais, todos os seus utensílios, e os pães da proposição;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candelabro para a luz, os seus utensílios, as suas lâmpadas, e o azeite para a luz;

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar do incenso e os seus varais, o óleo da unção e o incenso aromático, e o reposteiro da porta para a entrada do tabernáculo;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar do holocausto com o seu crivo de bronze, os seus varais, e todos os seus utensílios; a pia e a sua base;

[[v2-35-17]]

^<<v2-35-17,17>>^ as cortinas do átrio, as suas colunas e as suas bases, o reposteiro para a porta do átrio;

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas do tabernáculo, as estacas do átrio, e as suas cordas;

[[v2-35-19]]

^<<v2-35-19,19>>^ as vestes finamente tecidas, para o uso no ministério no lugar santo, as vestes sagradas de Arão, o sacerdote, e as vestes de seus filhos, para administrarem o sacerdócio.

[[v2-35-20]]

^<<v2-35-20,20>>^ Então toda a congregação dos filhos de Israel saiu da presença de Moisés.

[[v2-35-21]]

^<<v2-35-21,21>>^ E veio todo homem cujo coração o moveu, e todo aquele cujo espírito o estimulava, e trouxeram a oferta alçada do Senhor para a obra da tenda da revelação, e para todo o serviço dela, e para as vestes sagradas.

[[v2-35-22]]

^<<v2-35-22,22>>^ Vieram, tanto homens como mulheres, todos quantos eram bem dispostos de coração, trazendo broches, pendentes, anéis e braceletes, sendo todos estes jóias de ouro; assim veio todo aquele que queria fazer oferta de ouro ao Senhor.

[[v2-35-23]]

^<<v2-35-23,23>>^ E todo homem que possuía azul, púrpura, carmesim, linho fino, pelos de cabras, peles de carneiros tintas de vermelho, ou peles de golfinhos, os trazia.

[[v2-35-24]]

^<<v2-35-24,24>>^ Todo aquele que tinha prata ou metal para oferecer, o trazia por oferta alçada ao Senhor; e todo aquele que possuía madeira de acácia, a trazia para qualquer obra do serviço.

[[v2-35-25]]

^<<v2-35-25,25>>^ E todas as mulheres hábeis fiavam com as mãos, e traziam o que tinham fiado, o azul e a púrpura, o carmesim e o linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ E todas as mulheres hábeis que quisessem fiavam os pelos das cabras.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os príncipes traziam pedras de berilo e pedras de engaste para o éfode e para o peitoral,

[[v2-35-28]]

^<<v2-35-28,28>>^ e as especiarias e o azeite para a luz, para o óleo da unção e para o incenso aromático.

[[v2-35-29]]

^<<v2-35-29,29>>^ Trouxe uma oferta todo homem e mulher cujo coração voluntariamente se moveu a trazer alguma coisa para toda a obra que o senhor ordenara se fizesse por intermédio de Moisés; assim trouxeram os filhos de Israel uma oferta voluntária ao Senhor.

[[v2-35-30]]

^<<v2-35-30,30>>^ Depois disse Moisés aos filhos de Israel: Eis que o Senhor chamou por nome a Bezalel, filho de Uri, filho de Hur, da tribo de Judá,

[[v2-35-31]]

^<<v2-35-31,31>>^ e o encheu do espírito de Deus, no tocante à sabedoria, ao entendimento, à ciência e a todo ofício,

[[v2-35-32]]

^<<v2-35-32,32>>^ para inventar obras artísticas, para trabalhar em ouro, em prata e em bronze,

[[v2-35-33]]

^<<v2-35-33,33>>^ em lavramento de pedras para engastar, em entalhadura de madeira, enfim, para trabalhar em toda obra fina.

[[v2-35-34]]

^<<v2-35-34,34>>^ Também lhe dispôs o coração para ensinar a outros; a ele e a Aoliabe, filho de Aisamaque, da tribo de Dã,

[[v2-35-35]]

^<<v2-35-35,35>>^ a estes encheu de sabedoria do coração para exercerem todo ofício, seja de gravador, de desenhista, de bordador em azul, púrpura, carmesim e linho fino, de tecelão, enfim, dos que exercem qualquer ofício e dos que inventam obras artísticas.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]