include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-37-1]]

^<<v2-37-1,1>>^ Fez também Bezalel a arca de madeira de acácia; o seu comprimento era de dois côvados e meio, a sua largura de um côvado e meio, e a sua altura de um côvado e meio.

[[v2-37-2]]

^<<v2-37-2,2>>^ Cobriu-a de ouro puro por dentro e por fora, fez-lhe uma moldura de ouro ao redor,

[[v2-37-3]]

^<<v2-37-3,3>>^ e fundiu-lhe quatro argolas de ouro nos seus quatro cantos, duas argolas num lado e duas no outro.

[[v2-37-4]]

^<<v2-37-4,4>>^ Também fez varais de madeira de acácia, e os cobriu de ouro;

[[v2-37-5]]

^<<v2-37-5,5>>^ e meteu os varais pelas argolas aos lados da arca, para se levar a arca.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez também um propiciatório de ouro puro; o seu comprimento era de dois côvados e meio, e a sua largura de um côvado e meio.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez também dois querubins de ouro; de ouro batido os fez nas duas extremidades do propiciatório,

[[v2-37-8]]

^<<v2-37-8,8>>^ um querubim numa extremidade, e o outro querubim na outra; de uma só peça com o propiciatório fez os querubins nas duas extremidades dele.

[[v2-37-9]]

^<<v2-37-9,9>>^ E os querubins estendiam as suas asas por cima do propiciatório, cobrindo-o com as asas, tendo as faces voltadas um para o outro; para o propiciatório estavam voltadas as faces dos querubins.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez também a mesa de madeira de acácia; o seu comprimento era de dois côvados, a sua largura de um côvado, e a sua altura de um côvado e meio.

[[v2-37-11]]

^<<v2-37-11,11>>^ cobriu-a de ouro puro, e fez-lhe uma moldura de ouro ao redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ Fez-lhe também ao redor uma guarnição de quatro dedos de largura, e ao redor na guarnição fez uma moldura de ouro.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fundiu-lhe também nos quatro cantos que estavam sobre os seus quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ Junto da guarnição estavam as argolas para os lugares dos varais, para se levar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez também estes varais de madeira de acácia, e os cobriu de ouro, para se levar a mesa.

[[v2-37-16]]

^<<v2-37-16,16>>^ E de ouro puro fez os utensílios que haviam de estar sobre a mesa, os seus pratos e as suas colheres, as suas tigelas e os seus cântaros, com que se haviam de oferecer as libações.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez também o candelabro de ouro puro; de ouro batido fez o candelabro, tanto o seu pedestal como a sua haste; os seus copos, os seus cálices e as suas corolas formavam com ele uma só peça.

[[v2-37-18]]

^<<v2-37-18,18>>^ Dos seus lados saíam seis braços: três de um lado do candelabro e três do outro lado.

[[v2-37-19]]

^<<v2-37-19,19>>^ Em um braço havia três copos a modo de flores de amêndoa, com cálice e corola; igualmente no outro braço três copos a modo de flores de amêndoa, com cálice e corola; assim se fez com os seis braços que saíam do candelabro.

[[v2-37-20]]

^<<v2-37-20,20>>^ Mas na haste central havia quatro copos a modo de flores de amêndoa, com os seus cálices e as suas corolas;

[[v2-37-21]]

^<<v2-37-21,21>>^ também havia um cálice debaixo de dois braços, formando com a haste uma só peça, e outro cálice debaixo de dois outros braços, de uma só peça com a haste, e ainda outro cálice debaixo de dois outros braços, de uma só peça com a haste; e assim se fez para os seis braços que saíam da haste.

[[v2-37-22]]

^<<v2-37-22,22>>^ Os seus cálices e os seus braços formavam uma só peça com a haste; o todo era uma obra batida de ouro puro.

[[v2-37-23]]

^<<v2-37-23,23>>^ Também de ouro puro lhe fez as lâmpadas, em número de sete, com os seus espevitadores e os seus cinzeiros.

[[v2-37-24]]

^<<v2-37-24,24>>^ De um talento de ouro puro fez o candelabro e todos os seus utensílios.

[[v2-37-25]]

^<<v2-37-25,25>>^ De madeira de acácia fez o altar do incenso; de um côvado era o seu comprimento, e de um côvado a sua largura, quadrado, e de dois côvados a sua altura; as suas pontas formavam uma só peça com ele.

[[v2-37-26]]

^<<v2-37-26,26>>^ Cobriu-o de ouro puro, tanto a face superior como as suas paredes ao redor, e as suas pontas, e fez-lhe uma moldura de ouro ao redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez-lhe também duas argolas de ouro debaixo da sua moldura, nos dois cantos de ambos os lados, como lugares dos varais, para com eles se levar o altar.

[[v2-37-28]]

^<<v2-37-28,28>>^ E os varais fez de madeira de acácia, e os cobriu de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Também fez o óleo sagrado da unção, e o incenso aromático, puro, qual obra do perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]