include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-29-1]]

^<<v2-29-1,1>>^ Isto é o que lhes farás para os santificar, para que me administrem o sacerdócio: Toma um novilho e dois carneiros sem defeito,

[[v2-29-2]]

^<<v2-29-2,2>>^ e pão ázimo, e bolos ázimos, amassados com azeite, e coscorões ázimos, untados com azeite; de flor de farinha de trigo os farás;

[[v2-29-3]]

^<<v2-29-3,3>>^ e os porás num cesto, e os trarás no cesto, com o novilho e os dois carneiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ Então farás chegar Arão e seus filhos à porta da tenda da revelação e os lavarás, com água.

[[v2-29-5]]

^<<v2-29-5,5>>^ Depois tomarás as vestes, e vestirás a Arão da túnica e do manto do éfode, e do éfode mesmo, e do peitoral, e lhe cingirás o éfode com o seu cinto de obra esmerada;

[[v2-29-6]]

^<<v2-29-6,6>>^ e pôr-lhe-ás a mitra na cabeça; e sobre a mitra porás a coroa de santidade;

[[v2-29-7]]

^<<v2-29-7,7>>^ então tomarás o óleo da unção e, derramando-lho sobre a cabeça, o ungirás.

[[v2-29-8]]

^<<v2-29-8,8>>^ Depois farás chegar seus filhos, e lhes farás vestir túnicas,

[[v2-29-9]]

^<<v2-29-9,9>>^ e os cingirás com cintos, a Arão e a seus filhos, e lhes atarás as tiaras. Por estatuto perpétuo eles terão o sacerdócio; consagrarás, pois, a Arão e a seus filhos.

[[v2-29-10]]

^<<v2-29-10,10>>^ Farás chegar o novilho diante da tenda da revelação, e Arão e seus filhos porão as mãos sobre a cabeça do novilho;

[[v2-29-11]]

^<<v2-29-11,11>>^ e imolarás o novilho perante o Senhor, à porta da tenda da revelação.

[[v2-29-12]]

^<<v2-29-12,12>>^ Depois tomarás do sangue do novilho, e com o dedo o porás sobre as pontas do altar, e todo o sangue restante derramarás à base do altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ Também tomarás toda a gordura que cobre as entranhas, o redenho do fígado, os dois rins e a gordura que houver neles, e queimá-los-ás sobre o altar;

[[v2-29-14]]

^<<v2-29-14,14>>^ mas a carne do novilho, o seu couro e o seu excremento queimarás fora do arraial; é sacrifício pelo pecado.

[[v2-29-15]]

^<<v2-29-15,15>>^ Depois tomarás um carneiro, e Arão e seus filhos porão as mãos sobre a cabeça dele,

[[v2-29-16]]

^<<v2-29-16,16>>^ e imolarás o carneiro e, tomando o seu sangue, o espargirás sobre o altar ao redor;

[[v2-29-17]]

^<<v2-29-17,17>>^ e partirás o carneiro em suas partes, e lavarás as suas entranhas e as suas pernas, e as porás sobre as suas partes e sobre a sua cabeça.

[[v2-29-18]]

^<<v2-29-18,18>>^ Assim queimarás todo o carneiro sobre o altar; é um holocausto para o Senhor; é cheiro suave, oferta queimada ao Senhor.

[[v2-29-19]]

^<<v2-29-19,19>>^ e imolarás o carneiro, e tomarás do seu sangue, e o porás sobre a ponta da orelha direita de Arão e sobre a ponta da orelha direita de seus filhos, como também sobre o dedo polegar da sua mão direita e sobre o dedo polegar do seu pé direito; e espargirás o sangue sobre o altar ao redor.

[[v2-29-20]]

^<<v2-29-20,20>>^ Então tomarás do sangue que estará sobre o altar, e do óleo da unção, e os espargirás sobre Arão e sobre as suas vestes, e sobre seus filhos, e sobre as vestes de seus filhos com ele; assim ele será santificado e as suas vestes, também seus filhos e as vestes de seus filhos com ele.

[[v2-29-21]]

^<<v2-29-21,21>>^ Depois tomarás do carneiro a gordura e a cauda gorda, a gordura que cobre as entranhas e o redenho do fígado, os dois rins com a gordura que houver neles e a coxa direita &#123;porque é carneiro de consagração&#125;,

[[v2-29-22]]

^<<v2-29-22,22>>^ e uma fogaça de pão, um bolo de pão azeitado e um coscorão do cesto dos pães ázimos que estará diante do Senhor,

[[v2-29-23]]

^<<v2-29-23,23>>^ e uma fogaça de pão, um bolo de pão azeitado e um coscorão do cesto dos pães ázimos que estará diante do Senhor,

[[v2-29-24]]

^<<v2-29-24,24>>^ e tudo porás nas mãos de Arão, e nas mãos de seus filhos; e por oferta de movimento o moverás perante o Senhor.

[[v2-29-25]]

^<<v2-29-25,25>>^ Depois o tomarás das suas mãos e o queimarás no altar sobre o holocausto, por cheiro suave perante o Senhor; é oferta queimada ao Senhor.

[[v2-29-26]]

^<<v2-29-26,26>>^ Também tomarás o peito do carneiro de consagração, que é de Arão, e por oferta de movimento o moverás perante o Senhor; e isto será a tua porção.

[[v2-29-27]]

^<<v2-29-27,27>>^ E santificarás o peito da oferta de movimento e a coxa da oferta alçada, depois de movida e alçada, isto é, aquilo do carneiro de consagração que for de Arão e de seus filhos;

[[v2-29-28]]

^<<v2-29-28,28>>^ e isto será para Arão e para seus filhos a porção de direito, para sempre, da parte dos filhos de Israel, porque é oferta alçada; e oferta alçada será dos filhos de Israel, dos sacrifícios das suas ofertas pacíficas, oferta alçada ao Senhor.

[[v2-29-29]]

^<<v2-29-29,29>>^ As vestes sagradas de Arão ficarão para seus filhos depois dele, para nelas serem ungidos e sagrados.

[[v2-29-30]]

^<<v2-29-30,30>>^ Sete dias os vestirá aquele que de seus filhos for sacerdote em seu lugar, quando entrar na tenda da revelação para ministrar no lugar santo.

[[v2-29-31]]

^<<v2-29-31,31>>^ Também tomarás o carneiro de consagração e cozerás a sua carne em lugar santo.

[[v2-29-32]]

^<<v2-29-32,32>>^ E Arão e seus filhos comerão a carne do carneiro, e o pão que está no cesto, à porta da tenda da revelação;

[[v2-29-33]]

^<<v2-29-33,33>>^ e comerão as coisas com que for feita expiação, para consagrá-los, e para santificá-los; mas delas o estranho não comerá, porque são santas.

[[v2-29-34]]

^<<v2-29-34,34>>^ E se sobejar alguma coisa da carne da consagração, ou do pão, até pela manhã, o que sobejar queimarás no fogo; não se comerá, porque é santo.

[[v2-29-35]]

^<<v2-29-35,35>>^ Assim, pois, farás a Arão e a seus filhos conforme tudo o que te hei ordenado; por sete dias os sagrarás.

[[v2-29-36]]

^<<v2-29-36,36>>^ Também cada dia oferecerás para expiação o novilho de sacrifício pelo pecado; e purificarás o altar, fazendo expiação por ele; e o ungirás para santificá-lo.

[[v2-29-37]]

^<<v2-29-37,37>>^ Sete dias farás expiação pelo altar, e o santificarás; e o altar será santíssimo; tudo o que tocar o altar será santo.

[[v2-29-38]]

^<<v2-29-38,38>>^ Isto, pois, é o que oferecerás sobre o altar: dois cordeiros de um ano cada dia continuamente.

[[v2-29-39]]

^<<v2-29-39,39>>^ Um cordeiro oferecerás pela manhã, e o outro cordeiro oferecerás à tardinha;

[[v2-29-40]]

^<<v2-29-40,40>>^ com um cordeiro a décima parte de uma efa de flor de farinha, misturada com a quarta parte de um him de azeite batido, e para libação a quarta parte de um him de vinho.

[[v2-29-41]]

^<<v2-29-41,41>>^ E o outro cordeiro oferecerás à tardinha, e com ele farás oferta de cereais como com a oferta da manhã, e conforme a sua oferta de libação, por cheiro suave; oferta queimada é ao Senhor.

[[v2-29-42]]

^<<v2-29-42,42>>^ Este será o holocausto contínuo por vossas gerações, à porta da tenda da revelação, perante o Senhor, onde vos encontrarei, para falar contigo ali.

[[v2-29-43]]

^<<v2-29-43,43>>^ E ali virei aos filhos de Israel; e a tenda será santificada pela minha glória;

[[v2-29-44]]

^<<v2-29-44,44>>^ santificarei a tenda da revelação e o altar; também santificarei a Arão e seus filhos, para que me administrem o sacerdócio.

[[v2-29-45]]

^<<v2-29-45,45>>^ Habitarei no meio dos filhos de Israel, e serei o seu Deus;

[[v2-29-46]]

^<<v2-29-46,46>>^ e eles saberão que eu sou o Senhor seu Deus, que os tirei da terra do Egito, para habitar no meio deles; eu sou o Senhor seu Deus.

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]