include::./index.adoc[]

[[v2-7-0]]
=== Êxodo, 7
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-7-1]]

^<<v2-7-1,1>>^ Então disse o Senhor a Moisés: Eis que te tenho posto como Deus a Faraó, e Arão, teu irmão, será o teu profeta.

[[v2-7-2]]

^<<v2-7-2,2>>^ Tu falarás tudo o que eu te mandar; e Arão, teu irmão, falará a Faraó, que deixe ir os filhos de Israel da sua terra.

[[v2-7-3]]

^<<v2-7-3,3>>^ Eu, porém, endurecerei o coração de Faraó e multiplicarei na terra do Egito os meus sinais e as minhas maravilhas.

[[v2-7-4]]

^<<v2-7-4,4>>^ Mas Faraó não vos ouvirá; e eu porei minha mão sobre o Egito, e tirarei os meus exércitos, o meu povo, os filhos de Israel, da terra do Egito, com grandes juízos.

[[v2-7-5]]

^<<v2-7-5,5>>^ E os egípcios saberão que eu sou o Senhor, quando estender a minha mão sobre o Egito, e tirar os filhos de Israel do meio deles.

[[v2-7-6]]

^<<v2-7-6,6>>^ Assim fizeram Moisés e Arão; como o Senhor lhes ordenara, assim fizeram.

[[v2-7-7]]

^<<v2-7-7,7>>^ Tinha Moisés oitenta anos, e Arão oitenta e três, quando falaram a Faraó.

[[v2-7-8]]

^<<v2-7-8,8>>^ Falou, pois, o Senhor a Moisés e Arão:

[[v2-7-9]]

^<<v2-7-9,9>>^ Quando Faraó vos disser: Apresentai da vossa parte algum milagre; dirás a Arão: Toma a tua vara, e lança-a diante de Faraó, para que se torne em serpente.

[[v2-7-10]]

^<<v2-7-10,10>>^ Então Moisés e Arão foram ter com Faraó, e fizeram assim como o Senhor ordenara. Arão lançou a sua vara diante de Faraó e diante dos seus servos, e ela se tornou em serpente.

[[v2-7-11]]

^<<v2-7-11,11>>^ Faraó também mandou vir os sábios e encantadores; e eles, os magos do Egito, também fizeram o mesmo com os seus encantamentos.

[[v2-7-12]]

^<<v2-7-12,12>>^ Pois cada um deles lançou a sua vara, e elas se tornaram em serpentes; mas a vara de Arão tragou as varas deles.

[[v2-7-13]]

^<<v2-7-13,13>>^ Endureceu-se, porém, o coração de Faraó, e ele não os ouviu, como o Senhor tinha dito.

[[v2-7-14]]

^<<v2-7-14,14>>^ Então disse o Senhor a Moisés: Obstinou-se o coração de Faraó; ele recusa deixar ir o povo.

[[v2-7-15]]

^<<v2-7-15,15>>^ Vai ter com Faraó pela manhã; eis que ele sairá às águas; pôr-te-ás à beira do rio para o encontrar, e tomarás na mão a vara que se tomou em serpente.

[[v2-7-16]]

^<<v2-7-16,16>>^ E lhe dirás: O Senhor, o Deus dos hebreus, enviou-me a ti para dizer-te: Deixa ir o meu povo, para que me sirva no deserto; porém eis que até agora não o tens ouvido.

[[v2-7-17]]

^<<v2-7-17,17>>^ Assim diz o Senhor: Nisto saberás que eu sou o Senhor: Eis que eu, com esta vara que tenho na mão, ferirei as águas que estão no rio, e elas se tornarão em sangue.

[[v2-7-18]]

^<<v2-7-18,18>>^ E os peixes que estão no rio morrerão, e o rio cheirará mal; e os egípcios terão nojo de beber da água do rio.

[[v2-7-19]]

^<<v2-7-19,19>>^ Disse mais o Senhor a Moisés: Dize a Arão: Toma a tua vara, e estende a mão sobre as águas do Egito, sobre as suas correntes, sobre os seus rios, e sobre as suas lagoas e sobre todas as suas águas empoçadas, para que se tornem em sangue; e haverá sangue por toda a terra do Egito, assim nos vasos de madeira como nos de pedra.

[[v2-7-20]]

^<<v2-7-20,20>>^ Fizeram Moisés e Arão como lhes ordenara o Senhor; Arão, levantando a vara, feriu as águas que estavam no rio, diante dos olhos de Faraó, e diante dos olhos de seus servos; e todas as águas do rio se tornaram em sangue.

[[v2-7-21]]

^<<v2-7-21,21>>^ De modo que os peixes que estavam no rio morreram, e o rio cheirou mal, e os egípcios não podiam beber da água do rio; e houve sangue por toda a terra do Egito.

[[v2-7-22]]

^<<v2-7-22,22>>^ Mas o mesmo fizeram também os magos do Egito com os seus encantamentos; de maneira que o coração de Faraó se endureceu, e não os ouviu, como o Senhor tinha dito.

[[v2-7-23]]

^<<v2-7-23,23>>^ Virou-se Faraó e entrou em sua casa, e nem ainda a isto tomou a sério.

[[v2-7-24]]

^<<v2-7-24,24>>^ Todos os egípcios, pois, cavaram junto ao rio, para achar água que beber; porquanto não podiam beber da água do rio.

[[v2-7-25]]

^<<v2-7-25,25>>^ Assim se passaram sete dias, depois que o Senhor ferira o rio.

'''

xref:002-exodo/002-exodo-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodo/002-exodo-008.adoc#v2-8-0[Próximo Capítulo &#62;]