include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-30-1]]

^<<v2-30-1,1>>^ Farás um altar para queimar o incenso; de madeira de acácia o farás.

[[v2-30-2]]

^<<v2-30-2,2>>^ O seu comprimento será de um côvado, e a sua largura de um côvado; será quadrado; e de dois côvados será a sua altura; as suas pontas formarão uma só peça com ele.

[[v2-30-3]]

^<<v2-30-3,3>>^ De ouro puro o cobrirás, tanto a face superior como as suas paredes ao redor, e as suas pontas; e lhe farás uma moldura de ouro ao redor.

[[v2-30-4]]

^<<v2-30-4,4>>^ Também lhe farás duas argolas de ouro debaixo da sua moldura; nos dois cantos de ambos os lados as farás; e elas servirão de lugares para os varais com que o altar será levado.

[[v2-30-5]]

^<<v2-30-5,5>>^ Farás também os varais de madeira de acácia e os cobrirás de ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ E porás o altar diante do véu que está junto à arca do testemunho, diante do propiciatório, que se acha sobre o testemunho, onde eu virei a ti.

[[v2-30-7]]

^<<v2-30-7,7>>^ E Arão queimará sobre ele o incenso das especiarias; cada manhã, quando puser em ordem as lâmpadas, o queimará.

[[v2-30-8]]

^<<v2-30-8,8>>^ Também quando acender as lâmpadas à tardinha, o queimará; este será incenso perpétuo perante o Senhor pelas vossas gerações.

[[v2-30-9]]

^<<v2-30-9,9>>^ Não oferecereis sobre ele incenso estranho, nem holocausto, nem oferta de cereais; nem tampouco derramareis sobre ele ofertas de libação.

[[v2-30-10]]

^<<v2-30-10,10>>^ E uma vez no ano Arão fará expiação sobre as pontas do altar; com o sangue do sacrifício de expiação de pecado, fará expiação sobre ele uma vez no ano pelas vossas gerações; santíssimo é ao Senhor.

[[v2-30-11]]

^<<v2-30-11,11>>^ Disse mais o Senhor a Moisés:

[[v2-30-12]]

^<<v2-30-12,12>>^ Quando fizeres o alistamento dos filhos de Israel para sua enumeração, cada um deles dará ao Senhor o resgate da sua alma, quando os alistares; para que não haja entre eles praga alguma por ocasião do alistamento.

[[v2-30-13]]

^<<v2-30-13,13>>^ Dará cada um, ao ser alistado, meio siclo, segundo o siclo do santuário &#123;este siclo é de vinte jeiras&#125;; meio siclo é a oferta ao Senhor.

[[v2-30-14]]

^<<v2-30-14,14>>^ Todo aquele que for alistado, de vinte anos para cima, dará a oferta do Senhor.

[[v2-30-15]]

^<<v2-30-15,15>>^ O rico não dará mais, nem o pobre dará menos do que o meio siclo, quando derem a oferta do Senhor, para fazerdes expiação por vossas almas.

[[v2-30-16]]

^<<v2-30-16,16>>^ E tomarás o dinheiro da expiação dos filhos de Israel, e o designarás para o serviço da tenda da revelação, para que sirva de memorial a favor dos filhos de Israel diante do Senhor, para fazerdes expiação por vossas almas.

[[v2-30-17]]

^<<v2-30-17,17>>^ Disse mais o Senhor a Moisés:

[[v2-30-18]]

^<<v2-30-18,18>>^ Farás também uma pia de bronze com a sua base de bronze, para lavatório; e a porás entre a tenda da revelação e o altar, e nela deitarás água,

[[v2-30-19]]

^<<v2-30-19,19>>^ com a qual Arão e seus filhos lavarão as mãos e os pés;

[[v2-30-20]]

^<<v2-30-20,20>>^ quando entrarem na tenda da revelação lavar-se-ão com água, para que não morram, ou quando se chegarem ao altar para ministrar, para fazer oferta queimada ao Senhor.

[[v2-30-21]]

^<<v2-30-21,21>>^ Lavarão, pois, as mãos e os pés, para que não morram; e isto lhes será por estatuto perpétuo a ele e à sua descendência pelas suas gerações.

[[v2-30-22]]

^<<v2-30-22,22>>^ Disse mais o Senhor a Moisés:

[[v2-30-23]]

^<<v2-30-23,23>>^ Também toma das principais especiarias, da mais pura mirra quinhentos siclos, de canela aromática a metade, a saber, duzentos e cinqüenta siclos, de cálamo aromático duzentos e cinqüenta siclos,

[[v2-30-24]]

^<<v2-30-24,24>>^ de cássia quinhentos siclos, segundo o siclo do santuário, e de azeite de oliveiras um him.

[[v2-30-25]]

^<<v2-30-25,25>>^ Disto farás um óleo sagrado para as unções, um perfume composto segundo a arte do perfumista; este será o óleo sagrado para as unções.

[[v2-30-26]]

^<<v2-30-26,26>>^ Com ele ungirás a tenda da revelação, a arca do testemunho,

[[v2-30-27]]

^<<v2-30-27,27>>^ a mesa com todos os seus utensílios, o candelabro com os seus utensílios, o altar de incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ a altar do holocausto com todos os seus utensílios, o altar de incenso,

[[v2-30-29]]

^<<v2-30-29,29>>^ Assim santificarás estas coisas, para que sejam santíssimas; tudo o que as tocar será santo.

[[v2-30-30]]

^<<v2-30-30,30>>^ Também ungirás a Arão e seus filhos, e os santificarás para me administrarem o sacerdócio.

[[v2-30-31]]

^<<v2-30-31,31>>^ E falarás aos filhos de Israel, dizendo: Este me será o óleo sagrado para as unções por todas as vossas gerações.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não se ungirá com ele carne de homem; nem fareis outro de semelhante composição; sagrado é, e para vós será sagrado.

[[v2-30-33]]

^<<v2-30-33,33>>^ O homem que compuser um perfume como este, ou que com ele ungir a um estranho, será extirpado do seu povo.

[[v2-30-34]]

^<<v2-30-34,34>>^ Disse mais o Senhor a Moisés: Toma especiarias aromáticas: estoraque, onicha e gálbano, especiarias aromáticas com incenso puro; de cada uma delas tomarás peso igual;

[[v2-30-35]]

^<<v2-30-35,35>>^ e disto farás incenso, um perfume segundo a arte do perfumista, temperado com sal, puro e santo;

[[v2-30-36]]

^<<v2-30-36,36>>^ e uma parte dele reduzirás a pó e o porás diante do testemunho, na tenda da revelação onde eu virei a ti; coisa santíssima vos será.

[[v2-30-37]]

^<<v2-30-37,37>>^ Ora, o incenso que fareis conforme essa composição, não o fareis para vós mesmos; santo vos será para o Senhor.

[[v2-30-38]]

^<<v2-30-38,38>>^ O homem que fizer tal como este para o cheirar, será extirpado do seu povo.

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]