include::./index.adoc[]

[[v2-33-0]]
=== Êxodo, 33
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-33-1]]

^<<v2-33-1,1>>^ Disse mais o Senhor a Moisés: Vai, sobe daqui, tu e o povo que fizeste subir da terra do Egito, para a terra a respeito da qual jurei a Abraão, a Isaque, e a Jacó, dizendo: À tua descendência a darei.

[[v2-33-2]]

^<<v2-33-2,2>>^ E enviarei um anjo adiante de ti &#123;e lançarei fora os cananeus, e os amorreus, e os heteus, e os perizeus, e os heveus, e os jebuseus&#125;,

[[v2-33-3]]

^<<v2-33-3,3>>^ para uma terra que mana leite e mel; porque eu não subirei no meio de ti, porquanto és povo de cerviz dura; para que não te consuma eu no caminho.

[[v2-33-4]]

^<<v2-33-4,4>>^ E quando o povo ouviu esta má notícia, pôs-se a prantear, e nenhum deles vestiu os seus atavios.

[[v2-33-5]]

^<<v2-33-5,5>>^ Pois o Senhor tinha dito a Moisés: Dize aos filhos de Israel: És um povo de dura cerviz; se por um só momento eu subir no meio de ti, te consumirei; portanto agora despe os teus atavios, para que eu saiba o que te hei de fazer.

[[v2-33-6]]

^<<v2-33-6,6>>^ Então os filhos de Israel se despojaram dos seus atavios, desde o monte Horebe em diante.

[[v2-33-7]]

^<<v2-33-7,7>>^ Ora, Moisés costumava tomar a tenda e armá-la fora do arraial, bem longe do arraial; e chamou-lhe a tenda da revelação. E todo aquele que buscava ao Senhor saía à tenda da revelação, que estava fora do arraial.

[[v2-33-8]]

^<<v2-33-8,8>>^ Quando Moisés saía à tenda, levantava-se todo o povo e ficava em pé cada um à porta da sua tenda, e olhava a Moisés pelas costas, até entrar ele na tenda.

[[v2-33-9]]

^<<v2-33-9,9>>^ E quando Moisés entrava na tenda, a coluna de nuvem descia e ficava à porta da tenda; e o Senhor falava com Moisés.

[[v2-33-10]]

^<<v2-33-10,10>>^ Assim via todo o povo a coluna de nuvem que estava à porta da tenda, e todo o povo, levantando-se, adorava, cada um à porta da sua tenda.

[[v2-33-11]]

^<<v2-33-11,11>>^ E falava o Senhor a Moisés face a face, como qualquer fala com o seu amigo. Depois tornava Moisés ao arraial; mas o seu servidor, o mancebo Josué, filho de Num, não se apartava da tenda.

[[v2-33-12]]

^<<v2-33-12,12>>^ E Moisés disse ao Senhor: Eis que tu me dizes: Faze subir a este povo; porém não me fazes saber a quem hás de enviar comigo. Disseste também: Conheço-te por teu nome, e achaste graça aos meus olhos.

[[v2-33-13]]

^<<v2-33-13,13>>^ Se eu, pois, tenho achado graça aos teus olhos, rogo-te que agora me mostres os teus caminhos, para que eu te conheça, a fim de que ache graça aos teus olhos; e considera que esta nação é teu povo.

[[v2-33-14]]

^<<v2-33-14,14>>^ Respondeu-lhe o Senhor: Eu mesmo irei contigo, e eu te darei descanso.

[[v2-33-15]]

^<<v2-33-15,15>>^ Então Moisés lhe disse: Se tu mesmo não fores conosco, não nos faças subir daqui.

[[v2-33-16]]

^<<v2-33-16,16>>^ Como, pois, se saberá agora que tenho achado graça aos teus olhos, eu e o teu povo? acaso não é por andares tu conosco, de modo a sermos separados, eu e o teu povo, de todos os povos que há sobre a face da terra;

[[v2-33-17]]

^<<v2-33-17,17>>^ Ao que disse o Senhor a Moisés: Farei também isto que tens dito; porquanto achaste graça aos meus olhos, e te conheço pelo teu nome.

[[v2-33-18]]

^<<v2-33-18,18>>^ Moisés disse ainda: Rogo-te que me mostres a tua glória.

[[v2-33-19]]

^<<v2-33-19,19>>^ Respondeu-lhe o Senhor: Eu farei passar toda a minha bondade diante de ti, e te proclamarei o meu nome Jeová; e terei misericórdia de quem eu tiver misericórdia, e me compadecerei de quem me compadecer.

[[v2-33-20]]

^<<v2-33-20,20>>^ E disse mais: Não poderás ver a minha face, porquanto homem nenhum pode ver a minha face e viver.

[[v2-33-21]]

^<<v2-33-21,21>>^ Disse mais o Senhor: Eis aqui um lugar junto a mim; aqui, sobre a penha, te porás.

[[v2-33-22]]

^<<v2-33-22,22>>^ E quando a minha glória passar, eu te porei numa fenda da penha, e te cobrirei com a minha mão, até que eu haja passado.

[[v2-33-23]]

^<<v2-33-23,23>>^ Depois, quando eu tirar a mão, me verás pelas costas; porém a minha face não se verá.

'''

xref:002-exodo/002-exodo-032.adoc#v2-32-0[&#60; Capítulo Anterior] | <<v2-33-0,Topo>> | xref:002-exodo/002-exodo-034.adoc#v2-34-0[Próximo Capítulo &#62;]