include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-18-1]]

^<<v2-18-1,1>>^ Ora Jetro, sacerdote de Midiã, sogro de Moisés, ouviu todas as coisas que Deus tinha feito a Moisés e a Israel, seu povo, como o Senhor tinha tirado a Israel do Egito.

[[v2-18-2]]

^<<v2-18-2,2>>^ E Jetro, sogro de Moisés, tomou a Zípora, a mulher de Moisés, depois que este lha enviara,

[[v2-18-3]]

^<<v2-18-3,3>>^ e aos seus dois filhos, dos quais um se chamava Gérson; porque disse Moisés: Fui peregrino em terra estrangeira;

[[v2-18-4]]

^<<v2-18-4,4>>^ e o outro se chamava Eliézer; porque disse: O Deus de meu pai foi minha ajuda, e me livrou da espada de Faraó.

[[v2-18-5]]

^<<v2-18-5,5>>^ Veio, pois, Jetro, o sogro de Moisés, com os filhos e a mulher deste, a Moisés, no deserto onde se tinha acampado, junto ao monte de Deus;

[[v2-18-6]]

^<<v2-18-6,6>>^ e disse a Moisés: Eu, teu sogro Jetro, venho a ti, com tua mulher e seus dois filhos com ela.

[[v2-18-7]]

^<<v2-18-7,7>>^ Então saiu Moisés ao encontro de seu sogro, inclinou-se diante dele e o beijou; perguntaram um ao outro como estavam, e entraram na tenda.

[[v2-18-8]]

^<<v2-18-8,8>>^ Depois Moisés contou a seu sogro tudo o que o Senhor tinha feito a Faraó e aos egípcios por amor de Israel, todo o trabalho que lhes sobreviera no caminho, e como o Senhor os livrara.

[[v2-18-9]]

^<<v2-18-9,9>>^ E alegrou-se Jetro por todo o bem que o Senhor tinha feito a Israel, livrando-o da mão dos egípcios,

[[v2-18-10]]

^<<v2-18-10,10>>^ e disse: Bendito seja o Senhor, que vos livrou da mão dos egípcios e da mão de Faraó; que livrou o povo de debaixo da mão dos egípcios.

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei que o Senhor é maior que todos os deuses; até naquilo em que se houveram arrogantemente contra o povo.

[[v2-18-12]]

^<<v2-18-12,12>>^ Então Jetro, o sogro de Moisés, tomou holocausto e sacrifícios para Deus; e veio Arão, e todos os anciãos de Israel, para comerem pão com o sogro de Moisés diante de Deus.

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte assentou-se Moisés para julgar o povo; e o povo estava em pé junto de Moisés desde a manhã até a tarde.

[[v2-18-14]]

^<<v2-18-14,14>>^ Vendo, pois, o sogro de Moisés tudo o que ele fazia ao povo, perguntou: Que é isto que tu fazes ao povo? por que te assentas só, permanecendo todo o povo junto de ti desde a manhã até a tarde?

[[v2-18-15]]

^<<v2-18-15,15>>^ Respondeu Moisés a seu sogro: É por que o povo vem a mim para consultar a Deus.

[[v2-18-16]]

^<<v2-18-16,16>>^ Quando eles têm alguma questão, vêm a mim; e eu julgo entre um e outro e lhes declaro os estatutos de Deus e as suas leis.

[[v2-18-17]]

^<<v2-18-17,17>>^ O sogro de Moisés, porém, lhe replicou: Não é bom o que fazes.

[[v2-18-18]]

^<<v2-18-18,18>>^ certamente desfalecerás, assim tu, como este povo que está contigo; porque isto te é pesado demais; tu só não o podes fazer.

[[v2-18-19]]

^<<v2-18-19,19>>^ Ouve agora a minha voz; eu te aconselharei, e seja Deus contigo: sê tu pelo povo diante de Deus, e leva tu as causas a Deus;

[[v2-18-20]]

^<<v2-18-20,20>>^ ensinar-lhes-ás os estatutos e as leis, e lhes mostrarás o caminho em que devem andar, e a obra que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ Além disto procurarás dentre todo o povo homens de capacidade, tementes a Deus, homens verazes, que aborreçam a avareza, e os porás sobre eles por chefes de mil, chefes de cem, chefes de cinqüenta e chefes de dez;

[[v2-18-22]]

^<<v2-18-22,22>>^ e julguem eles o povo em todo o tempo. Que a ti tragam toda causa grave, mas toda causa pequena eles mesmos a julguem; assim a ti mesmo te aliviarás da carga, e eles a levarão contigo.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se isto fizeres, e Deus to mandar, poderás então subsistir; assim também todo este povo irá em paz para o seu lugar.

[[v2-18-24]]

^<<v2-18-24,24>>^ E Moisés deu ouvidos à voz de seu sogro, e fez tudo quanto este lhe dissera;

[[v2-18-25]]

^<<v2-18-25,25>>^ e escolheu Moisés homens capazes dentre todo o Israel, e os pôs por cabeças sobre o povo: chefes de mil, chefes de cem, chefes de cinqüenta e chefes de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ Estes, pois, julgaram o povo em todo o tempo; as causas graves eles as trouxeram a Moisés; mas toda causa pequena, julgaram-na eles mesmos.

[[v2-18-27]]

^<<v2-18-27,27>>^ Então despediu Moisés a seu sogro, o qual se foi para a sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]