include::./index.adoc[]

[[v2-19-0]]
=== Êxodo, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-19-1]]

^<<v2-19-1,1>>^ No terceiro mês depois que os filhos de Israel haviam saído da terra do Egito, no mesmo dia chegaram ao deserto de Sinai.

[[v2-19-2]]

^<<v2-19-2,2>>^ Tendo partido de Refidim, entraram no deserto de Sinai, onde se acamparam; Israel, pois, ali acampou-se em frente do monte.

[[v2-19-3]]

^<<v2-19-3,3>>^ Então subiu Moisés a Deus, e do monte o Senhor o chamou, dizendo: Assim falarás à casa de Jacó, e anunciarás aos filhos de Israel:

[[v2-19-4]]

^<<v2-19-4,4>>^ Vós tendes visto o que fiz: aos egípcios, como vos levei sobre asas de águias, e vos trouxe a mim.

[[v2-19-5]]

^<<v2-19-5,5>>^ Agora, pois, se atentamente ouvirdes a minha voz e guardardes o meu pacto, então sereis a minha possessão peculiar dentre todos os povos, porque minha é toda a terra;

[[v2-19-6]]

^<<v2-19-6,6>>^ e vós sereis para mim reino sacerdotal e nação santa. São estas as palavras que falarás aos filhos de Israel.

[[v2-19-7]]

^<<v2-19-7,7>>^ Veio, pois, Moisés e, tendo convocado os anciãos do povo, expôs diante deles todas estas palavras, que o Senhor lhe tinha ordenado.

[[v2-19-8]]

^<<v2-19-8,8>>^ Ao que todo o povo respondeu a uma voz: Tudo o que o Senhor tem falado, faremos. E relatou Moisés ao Senhor as palavras do povo.

[[v2-19-9]]

^<<v2-19-9,9>>^ Então disse o Senhor a Moisés: Eis que eu virei a ti em uma nuvem espessa, para que o povo ouça, quando eu falar contigo, e também para que sempre te creia. Porque Moisés tinha anunciado as palavras do seu povo ao Senhor.

[[v2-19-10]]

^<<v2-19-10,10>>^ Disse mais o Senhor a Moisés: Vai ao povo, e santifica-os hoje e amanhã; lavem eles os seus vestidos,

[[v2-19-11]]

^<<v2-19-11,11>>^ e estejam prontos para o terceiro dia; porquanto no terceiro dia descerá o Senhor diante dos olhos de todo o povo sobre o monte Sinai.

[[v2-19-12]]

^<<v2-19-12,12>>^ Também marcarás limites ao povo em redor, dizendo: Guardai-vos, não subais ao monte, nem toqueis o seu termo; todo aquele que tocar o monte será morto.

[[v2-19-13]]

^<<v2-19-13,13>>^ Mão alguma tocará naquele que o fizer, mas ele será apedrejado ou asseteado; quer seja animal, quer seja homem, não viverá. Quando soar a buzina longamente, subirão eles até o pé do monte.

[[v2-19-14]]

^<<v2-19-14,14>>^ Então Moisés desceu do monte ao povo, e santificou o povo; e lavaram os seus vestidos.

[[v2-19-15]]

^<<v2-19-15,15>>^ E disse ele ao povo: Estai prontos para o terceiro dia; e não vos chegueis a mulher.

[[v2-19-16]]

^<<v2-19-16,16>>^ Ao terceiro dia, ao amanhecer, houve trovões, relâmpagos, e uma nuvem espessa sobre o monte; e ouviu-se um sonido de buzina mui forte, de maneira que todo o povo que estava no arraial estremeceu.

[[v2-19-17]]

^<<v2-19-17,17>>^ E Moisés levou o povo fora do arraial ao encontro de Deus; e puseram-se ao pé do monte.

[[v2-19-18]]

^<<v2-19-18,18>>^ Nisso todo o monte Sinai fumegava, porque o Senhor descera sobre ele em fogo; e a fumaça subiu como a fumaça de uma fornalha, e todo o monte tremia fortemente.

[[v2-19-19]]

^<<v2-19-19,19>>^ E, crescendo o sonido da buzina cada vez mais, Moisés falava, e Deus lhe respondia por uma voz.

[[v2-19-20]]

^<<v2-19-20,20>>^ E, tendo o Senhor descido sobre o monte Sinai, sobre o cume do monte, chamou a Moisés ao cume do monte; e Moisés subiu.

[[v2-19-21]]

^<<v2-19-21,21>>^ Então disse o Senhor a Moisés: Desce, adverte ao povo, para não suceder que traspasse os limites até o Senhor, a fim de ver, e muitos deles pereçam.

[[v2-19-22]]

^<<v2-19-22,22>>^ Ora, santifiquem-se também os sacerdotes, que se chegam ao Senhor, para que o Senhor não se lance sobre eles.

[[v2-19-23]]

^<<v2-19-23,23>>^ Respondeu Moisés ao Senhor: O povo não poderá subir ao monte Sinai, porque tu nos tens advertido, dizendo: Marca limites ao redor do monte, e santifica-o.

[[v2-19-24]]

^<<v2-19-24,24>>^ Ao que lhe disse o Senhor: Vai, desce; depois subirás tu, e Arão contigo; os sacerdotes, porém, e o povo não traspassem os limites para subir ao Senhor, para que ele não se lance sobre eles.

[[v2-19-25]]

^<<v2-19-25,25>>^ Então Moisés desceu ao povo, e disse-lhes isso.

'''

xref:002-exodo/002-exodo-018.adoc#v2-18-0[&#60; Capítulo Anterior] | <<v2-19-0,Topo>> | xref:002-exodo/002-exodo-020.adoc#v2-20-0[Próximo Capítulo &#62;]