include::./index.adoc[]

[[v2-5-0]]
=== Êxodo, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-5-1]]

^<<v2-5-1,1>>^ Depois foram Moisés e Arão e disseram a Faraó: Assim diz o Senhor, o Deus de Israel: Deixa ir o meu povo, para que me celebre uma festa no deserto.

[[v2-5-2]]

^<<v2-5-2,2>>^ Mas Faraó respondeu: Quem é o Senhor, para que eu ouça a sua voz para deixar ir Israel? Não conheço o Senhor, nem tampouco deixarei ir Israel.

[[v2-5-3]]

^<<v2-5-3,3>>^ Então eles ainda falaram: O Deus dos hebreus nos encontrou; portanto deixa-nos, pedimos-te, ir caminho de três dias ao deserto, e oferecer sacrifícios ao Senhor nosso Deus, para que ele não venha sobre nós com pestilência ou com espada.

[[v2-5-4]]

^<<v2-5-4,4>>^ Respondeu-lhes de novo o rei do Egito: Moisés e Arão, por que fazeis o povo cessar das suas obras? Ide às vossas cargas.

[[v2-5-5]]

^<<v2-5-5,5>>^ Disse mais Faraó: Eis que o povo da terra já é muito, e vós os fazeis abandonar as suas cargas.

[[v2-5-6]]

^<<v2-5-6,6>>^ Naquele mesmo dia Faraó deu ordem aos exatores do povo e aos seus oficiais, dizendo:

[[v2-5-7]]

^<<v2-5-7,7>>^ Não tornareis a dar, como dantes, palha ao povo, para fazer tijolos; vão eles mesmos, e colham palha para si.

[[v2-5-8]]

^<<v2-5-8,8>>^ Também lhes imporeis a conta dos tijolos que dantes faziam; nada diminuireis dela; porque eles estão ociosos; por isso clamam, dizendo: Vamos, sacrifiquemos ao nosso Deus.

[[v2-5-9]]

^<<v2-5-9,9>>^ Agrave-se o serviço sobre esses homens, para que se ocupem nele e não dêem ouvidos a palavras mentirosas.

[[v2-5-10]]

^<<v2-5-10,10>>^ Então saíram os exatores do povo e seus oficiais, e disseram ao povo: Assim diz Faraó: Eu não vos darei palha;

[[v2-5-11]]

^<<v2-5-11,11>>^ ide vós mesmos, e tomai palha de onde puderdes achá-la; porque nada se diminuirá de vosso serviço.

[[v2-5-12]]

^<<v2-5-12,12>>^ Então o povo se espalhou por toda parte do Egito a colher restolho em lugar de palha.

[[v2-5-13]]

^<<v2-5-13,13>>^ E os exatores os apertavam, dizendo: Acabai a vossa obra, a tarefa do dia no seu dia, como quando havia palha.

[[v2-5-14]]

^<<v2-5-14,14>>^ E foram açoitados os oficiais dos filhos de Israel, postos sobre eles pelos exatores de Faraó, que reclamavam: Por que não acabastes nem ontem nem hoje a vossa tarefa, fazendo tijolos como dantes?

[[v2-5-15]]

^<<v2-5-15,15>>^ Pelo que os oficiais dos filhos de Israel foram e clamaram a Faraó, dizendo: Porque tratas assim a teus servos?

[[v2-5-16]]

^<<v2-5-16,16>>^ Palha não se dá a teus servos, e nos dizem: Fazei tijolos; e eis que teus servos são açoitados; porém o teu povo é que tem a culpa.

[[v2-5-17]]

^<<v2-5-17,17>>^ Mas ele respondeu: Estais ociosos, estais ociosos; por isso dizeis: vamos, sacrifiquemos ao Senhor.

[[v2-5-18]]

^<<v2-5-18,18>>^ Portanto, ide, trabalhai; palha, porém, não se vos dará; todavia, dareis a conta dos tijolos.

[[v2-5-19]]

^<<v2-5-19,19>>^ Então os oficiais dos filhos de Israel viram-se em aperto, porquanto se lhes dizia: Nada diminuireis dos vossos tijolos, da tarefa do dia no seu dia.

[[v2-5-20]]

^<<v2-5-20,20>>^ Ao saírem da presença de Faraó depararam com Moisés e Arão que vinham ao encontro deles,

[[v2-5-21]]

^<<v2-5-21,21>>^ e disseram-lhes: Olhe o Senhor para vós, e julgue isso, porquanto fizestes o nosso caso repelente diante de Faraó e diante de seus servos, metendo-lhes nas mãos uma espada para nos matar.

[[v2-5-22]]

^<<v2-5-22,22>>^ Então, tornando-se Moisés ao Senhor, disse: Senhor! por que trataste mal a este povo? por que me enviaste?

[[v2-5-23]]

^<<v2-5-23,23>>^ Pois desde que me apresentei a Faraó para falar em teu nome, ele tem maltratado a este povo; e de nenhum modo tens livrado o teu povo.

'''

xref:002-exodo/002-exodo-004.adoc#v2-4-0[&#60; Capítulo Anterior] | <<v2-5-0,Topo>> | xref:002-exodo/002-exodo-006.adoc#v2-6-0[Próximo Capítulo &#62;]