include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-10-1]]

^<<v2-10-1,1>>^ Depois disse o Senhor a Moisés: vai a Faraó; porque tenho endurecido o seu coração, e o coração de seus servos, para manifestar estes meus sinais no meio deles,

[[v2-10-2]]

^<<v2-10-2,2>>^ e para que contes aos teus filhos, e aos filhos de teus filhos, as coisas que fiz no Egito, e os meus sinais que operei entre eles; para que vós saibais que eu sou o Senhor.

[[v2-10-3]]

^<<v2-10-3,3>>^ Foram, pois, Moisés e Arão a Faraó, e disseram-lhe: Assim diz o Senhor, o Deus dos hebreus: Até quando recusarás humilhar-te diante de mim? Deixa ir o meu povo, para que me sirva;

[[v2-10-4]]

^<<v2-10-4,4>>^ mas se tu recusares deixar ir o meu povo, eis que amanhã trarei gafanhotos aos teus termos;

[[v2-10-5]]

^<<v2-10-5,5>>^ e eles cobrirão a face da terra, de sorte que não se poderá ver a terra e comerão o resto do que escapou, o que vos ficou da saraiva; também comerão toda árvore que vos cresce no campo;

[[v2-10-6]]

^<<v2-10-6,6>>^ e encherão as tuas casas, as casas de todos os teus servos e as casas de todos os egípcios, como nunca viram teus pais nem os pais de teus pais, desde o dia em que apareceram na terra até o dia de hoje. E virou-se, e saiu da presença de Faraó.

[[v2-10-7]]

^<<v2-10-7,7>>^ Então os servos de Faraó lhe disseram: Até quando este homem nos há de ser por laço? deixa ir os homens, para que sirvam ao Senhor seu Deus; porventura não sabes ainda que o Egito está destruído?

[[v2-10-8]]

^<<v2-10-8,8>>^ Pelo que Moisés e Arão foram levados outra vez a Faraó, e ele lhes disse: Ide, servi ao Senhor vosso Deus. Mas quais são os que hão de ir?

[[v2-10-9]]

^<<v2-10-9,9>>^ Respondeu-lhe Moisés: Havemos de ir com os nossos jovens e com os nossos velhos; com os nossos filhos e com as nossas filhas, com os nossos rebanhos e com o nosso gado havemos de ir; porque temos de celebrar uma festa ao Senhor.

[[v2-10-10]]

^<<v2-10-10,10>>^ Replicou-lhes Faraó: Seja o Senhor convosco, se eu vos deixar ir a vós e a vossos pequeninos! Olhai, porque há mal diante de vós.

[[v2-10-11]]

^<<v2-10-11,11>>^ Não será assim; agora, ide vós, os homens, e servi ao Senhor, pois isso é o que pedistes: E foram expulsos da presença de Faraó.

[[v2-10-12]]

^<<v2-10-12,12>>^ Então disse o Senhor a Moisés: Quanto aos gafanhotos, estende a tua mão sobre a terra do Egito, para que venham eles sobre a terra do Egito e comam toda erva da terra, tudo o que deixou a saraiva.

[[v2-10-13]]

^<<v2-10-13,13>>^ Então estendeu Moisés sua vara sobre a terra do Egito, e o Senhor trouxe sobre a terra um vento oriental todo aquele dia e toda aquela noite; e, quando amanheceu, o vento oriental trouxe os gafanhotos.

[[v2-10-14]]

^<<v2-10-14,14>>^ Subiram, pois, os gafanhotos sobre toda a terra do Egito e pousaram sobre todos os seus termos; tão numerosos foram, que antes destes nunca houve tantos, nem depois deles haverá.

[[v2-10-15]]

^<<v2-10-15,15>>^ Pois cobriram a face de toda a terra, de modo que a terra se escureceu; e comeram toda a erva da terra e todo o fruto das árvores, que deixara a saraiva; nada verde ficou, nem de árvore nem de erva do campo, por toda a terra do Egito.

[[v2-10-16]]

^<<v2-10-16,16>>^ Então Faraó mandou apressadamente chamar Moisés e Arão, e lhes disse: Pequei contra o Senhor vosso Deus, e contra vós.

[[v2-10-17]]

^<<v2-10-17,17>>^ Agora: pois, perdoai-me peço-vos somente esta vez o meu pecado, e orai ao Senhor vosso Deus que tire de mim mais esta morte.

[[v2-10-18]]

^<<v2-10-18,18>>^ Saiu, pois, Moisés da presença de Faraó, e orou ao Senhor.

[[v2-10-19]]

^<<v2-10-19,19>>^ Então o Senhor trouxe um vento ocidental fortíssimo, o qual levantou os gafanhotos e os lançou no Mar Vermelho; não ficou um só gafanhoto em todos os termos do Egito.

[[v2-10-20]]

^<<v2-10-20,20>>^ O Senhor, porém, endureceu o coração de Faraó, e este não deixou ir os filhos de Israel.

[[v2-10-21]]

^<<v2-10-21,21>>^ Então disse o Senhor a Moisés: Estende a mão para o céu, para que haja trevas sobre a terra do Egito, trevas que se possam apalpar.

[[v2-10-22]]

^<<v2-10-22,22>>^ Estendeu, pois, Moisés a mão para o céu, e houve trevas espessas em toda a terra do Egito por três dias.

[[v2-10-23]]

^<<v2-10-23,23>>^ Não se viram uns aos outros, e ninguém se levantou do seu lugar por três dias; mas para todos os filhos de Israel havia luz nas suas habitações.

[[v2-10-24]]

^<<v2-10-24,24>>^ Então mandou Faraó chamar Moisés, e disse: Ide, servi ao Senhor; somente fiquem os vossos rebanhos e o vosso gado; mas vão juntamente convosco os vossos pequeninos.

[[v2-10-25]]

^<<v2-10-25,25>>^ Moisés, porém, disse: Tu também nos tens de dar nas mãos sacrifícios e holocaustos, para que possamos oferecer sacrifícios ao Senhor nosso Deus.

[[v2-10-26]]

^<<v2-10-26,26>>^ E também o nosso gado há de ir conosco; nem uma unha ficará; porque dele havemos de tomar para servir ao Senhor nosso Deus; porque não sabemos com que havemos de servir ao Senhor, até que cheguemos lá.

[[v2-10-27]]

^<<v2-10-27,27>>^ O Senhor, porém, endureceu o coração de Faraó, e este não os quis deixar ir:

[[v2-10-28]]

^<<v2-10-28,28>>^ Disse, pois, Faraó a Moisés: Retira-te de mim, guarda-te que não mais vejas o meu rosto; porque no dia em que me vires o rosto morrerás.

[[v2-10-29]]

^<<v2-10-29,29>>^ Respondeu Moisés: Disseste bem; eu nunca mais verei o teu rosto.

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]