include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-9-1]]

^<<v2-9-1,1>>^ Depois o Senhor disse a Moisés: Vai a Faraó e dize-lhe: Assim diz o Senhor, o Deus dos hebreus: Deixa ir o meu povo, para que me sirva.

[[v2-9-2]]

^<<v2-9-2,2>>^ Porque, se recusares deixá-los ir, e ainda os retiveres,

[[v2-9-3]]

^<<v2-9-3,3>>^ eis que a mão do Senhor será sobre teu gado, que está no campo: sobre os cavalos, sobre os jumentos, sobre os camelos, sobre os bois e sobre as ovelhas; haverá uma pestilência muito grave.

[[v2-9-4]]

^<<v2-9-4,4>>^ Mas o Senhor fará distinção entre o gado de Israel e o gado do Egito; e não morrerá nada de tudo o que pertence aos filhos de Israel.

[[v2-9-5]]

^<<v2-9-5,5>>^ E o Senhor assinalou certo tempo, dizendo: Amanhã fará o Senhor isto na terra.

[[v2-9-6]]

^<<v2-9-6,6>>^ Fez, pois, o Senhor isso no dia seguinte; e todo gado dos egípcios morreu; porém do gado dos filhos de Israel não morreu nenhum.

[[v2-9-7]]

^<<v2-9-7,7>>^ E Faraó mandou ver, e eis que do gado dos israelitas não morrera sequer um. Mas o coração de Faraó se obstinou, e não deixou ir o povo.

[[v2-9-8]]

^<<v2-9-8,8>>^ Então disse o Senhor a Moisés e a Arão: Tomai as mãos cheias de cinza do forno, e Moisés a espalhe para o céu diante dos olhos de Faraó;

[[v2-9-9]]

^<<v2-9-9,9>>^ e ela se tornará em pó fino sobre toda a terra do Egito, e haverá tumores que arrebentarão em úlceras nos homens e no gado, por toda a terra do Egito.

[[v2-9-10]]

^<<v2-9-10,10>>^ E eles tomaram cinza do forno, e apresentaram-se diante de Faraó; e Moisés a espalhou para o céu, e ela se tomou em tumores que arrebentavam em úlceras nos homens e no gado.

[[v2-9-11]]

^<<v2-9-11,11>>^ Os magos não podiam manter-se diante de Moisés, por causa dos tumores; porque havia tumores nos magos, e em todos os egípcios.

[[v2-9-12]]

^<<v2-9-12,12>>^ Mas o Senhor endureceu o coração de Faraó, e este não os ouviu, como o Senhor tinha dito a Moisés.

[[v2-9-13]]

^<<v2-9-13,13>>^ Então disse o Senhor a Moisés: Levanta-te pela manhã cedo, põe-te diante de Faraó, e dize-lhe: Assim diz o Senhor, o Deus dos hebreus: Deixa ir o meu povo, para que me sirva;

[[v2-9-14]]

^<<v2-9-14,14>>^ porque desta vez enviarei todas as a minhas pragas sobre o teu coração, e sobre os teus servos, e sobre o teu povo, para que saibas que não há outro como eu em toda a terra.

[[v2-9-15]]

^<<v2-9-15,15>>^ Agora, por pouco, teria eu estendido a mão e ferido a ti e ao teu povo com pestilência, e tu terias sido destruído da terra;

[[v2-9-16]]

^<<v2-9-16,16>>^ mas, na verdade, para isso te hei mantido com vida, para te mostrar o meu poder, e para que o meu nome seja anunciado em toda a terra.

[[v2-9-17]]

^<<v2-9-17,17>>^ Tu ainda te exaltas contra o meu povo, não o deixando ir?

[[v2-9-18]]

^<<v2-9-18,18>>^ Eis que amanhã, por este tempo, s farei chover saraiva tão grave qual nunca houve no Egito, desde o dia em que foi fundado até agora.

[[v2-9-19]]

^<<v2-9-19,19>>^ Agora, pois, manda recolher o teu gado e tudo o que tens no campo; porque sobre todo homem e animal que se acharem no campo, e não se recolherem à casa, cairá a saraiva, e morrerão.

[[v2-9-20]]

^<<v2-9-20,20>>^ Quem dos servos de Faraó temia a o palavra do Senhor, fez Fugir os seus servos e o seu gado para as casas;

[[v2-9-21]]

^<<v2-9-21,21>>^ mas aquele que não se importava com a palavra do Senhor, deixou os seus servos e o seu gado no campo.

[[v2-9-22]]

^<<v2-9-22,22>>^ Então disse o Senhor a Moisés: Estende a tua mão para o céu, para que caia saraiva em toda a terra do Egito, sobre os homens e sobre os animais, e sobre toda a erva do campo na terra do Egito.

[[v2-9-23]]

^<<v2-9-23,23>>^ E Moisés estendeu a sua vara para o céu, e o Senhor enviou trovões e saraiva, e fogo desceu à terra; e o Senhor fez chover saraiva sobre a terra do Egito.

[[v2-9-24]]

^<<v2-9-24,24>>^ Havia, pois, saraiva misturada com fogo, saraiva tão grave qual nunca houvera em toda a terra do Egito, desde que veio a ser uma nação.

[[v2-9-25]]

^<<v2-9-25,25>>^ E a saraiva feriu, em toda a terra do Egito, tudo quanto havia no campo, tanto homens como animais; feriu também toda erva do campo, e quebrou todas as árvores do campo.

[[v2-9-26]]

^<<v2-9-26,26>>^ Somente na terra de Gósem onde se achavam os filhos de Israel, não houve saraiva.

[[v2-9-27]]

^<<v2-9-27,27>>^ Então Faraó mandou chamar Moisés e Arão, e disse-lhes: Esta vez pequei; o Senhor é justo, mas eu e o meu povo somos a ímpios.

[[v2-9-28]]

^<<v2-9-28,28>>^ Orai ao Senhor; pois já bastam estes trovões da parte de Deus e esta saraiva; eu vos deixarei ir, e não permanecereis mais, aqui.

[[v2-9-29]]

^<<v2-9-29,29>>^ Respondeu-lhe Moisés: Logo que eu tiver saído da cidade estenderei minhas mãos ao Senhor; os trovões cessarão, e não haverá, mais saraiva, para que saibas que a terra é do Senhor.

[[v2-9-30]]

^<<v2-9-30,30>>^ Todavia, quanto a ti e aos teus servos, eu sei que ainda não temereis diante do Senhor Deus.

[[v2-9-31]]

^<<v2-9-31,31>>^ Ora, o linho e a cevada foram danificados, porque a cevada já estava na espiga, e o linho em flor;

[[v2-9-32]]

^<<v2-9-32,32>>^ mas não foram danificados o trigo e o centeio, porque não estavam crescidos.

[[v2-9-33]]

^<<v2-9-33,33>>^ Saiu, pois, Moisés da cidade, da presença de Faraó, e estendeu as mãos ao Senhor; e cessaram os trovões e a saraiva, e a chuva não caiu mais sobre a terra.

[[v2-9-34]]

^<<v2-9-34,34>>^ Vendo Faraó que a chuva, a saraiva e os trovões tinham cessado, continuou a pecar, e endureceu o seu coração, ele e os seus servos.

[[v2-9-35]]

^<<v2-9-35,35>>^ Assim, o coração de Faraó se endureceu, e não deixou ir os filhos de Israel, como o Senhor tinha dito por Moisés.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]