include::./index.adoc[]

[[v2-2-0]]
=== Êxodo, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-2-1]]

^<<v2-2-1,1>>^ Foi-se um homem da casa de Levi e casou com uma filha de Levi.

[[v2-2-2]]

^<<v2-2-2,2>>^ A mulher concebeu e deu à luz um filho; e, vendo que ele era formoso, escondeu-o três meses.

[[v2-2-3]]

^<<v2-2-3,3>>^ Não podendo, porém, escondê-lo por mais tempo, tomou para ele uma arca de juncos, e a revestiu de betume e pez; e, pondo nela o menino, colocou-a entre os juncos a margem do rio.

[[v2-2-4]]

^<<v2-2-4,4>>^ E sua irmã postou-se de longe, para saber o que lhe aconteceria.

[[v2-2-5]]

^<<v2-2-5,5>>^ A filha de Faraó desceu para banhar-se no rio, e as suas criadas passeavam à beira do rio. Vendo ela a arca no meio os juncos, mandou a sua criada buscá-la.

[[v2-2-6]]

^<<v2-2-6,6>>^ E abrindo-a, viu a criança, e eis que o menino chorava; então ela teve compaixão dele, e disse: Este é um dos filhos dos hebreus.

[[v2-2-7]]

^<<v2-2-7,7>>^ Então a irmã do menino perguntou à filha de Faraó: Queres que eu te vá chamar uma ama dentre as hebréias, para que crie este menino para ti?

[[v2-2-8]]

^<<v2-2-8,8>>^ Respondeu-lhe a filha de Faraó: Vai. Foi, pois, a moça e chamou a mãe do menino.

[[v2-2-9]]

^<<v2-2-9,9>>^ Disse-lhe a filha de Faraó: Leva este menino, e cria-mo; eu te darei o teu salário. E a mulher tomou o menino e o criou.

[[v2-2-10]]

^<<v2-2-10,10>>^ Quando, pois, o menino era já grande, ela o trouxe à filha de Faraó, a qual o adotou; e lhe chamou Moisés, dizendo: Porque das águas o tirei.

[[v2-2-11]]

^<<v2-2-11,11>>^ Ora, aconteceu naqueles dias que, sendo Moisés já homem, saiu a ter com seus irmãos e atentou para as suas cargas; e viu um egípcio que feria a um hebreu dentre, seus irmãos.

[[v2-2-12]]

^<<v2-2-12,12>>^ Olhou para um lado e para outro, e vendo que não havia ninguém ali, matou o egípcio e escondeu-o na areia.

[[v2-2-13]]

^<<v2-2-13,13>>^ Tornou a sair no dia seguinte, e eis que dois hebreus contendiam; e perguntou ao que fazia a injustiça: Por que feres a teu próximo?

[[v2-2-14]]

^<<v2-2-14,14>>^ Respondeu ele: Quem te constituiu a ti príncipe e juiz sobre nós? Pensas tu matar-me, como mataste o egípcio? Temeu, pois, Moisés e disse: Certamente o negócio já foi descoberto.

[[v2-2-15]]

^<<v2-2-15,15>>^ E quando Faraó soube disso, procurou matar a Moisés. Este, porém, fugiu da presença de Faraó, e foi habitar na terra de Midiã; e sentou-se junto a um poço.

[[v2-2-16]]

^<<v2-2-16,16>>^ O sacerdote de Midiã tinha sete filhas, as quais vieram tirar água, e encheram os tanques para dar de beber ao rebanho de seu pai.

[[v2-2-17]]

^<<v2-2-17,17>>^ Então vieram os pastores, e as expulsaram dali; Moisés, porém, levantou-se e as defendeu, e deu de beber ao rebanho delas.

[[v2-2-18]]

^<<v2-2-18,18>>^ Quando elas voltaram a Reuel, seu pai, este lhes perguntou: como é que hoje voltastes tão cedo?

[[v2-2-19]]

^<<v2-2-19,19>>^ Responderam elas: um egípcio nos livrou da mão dos pastores; e ainda tirou água para nós e deu de beber ao rebanho.

[[v2-2-20]]

^<<v2-2-20,20>>^ E ele perguntou a suas filhas: Onde está ele; por que deixastes lá o homem? chamai-o para que coma pão.

[[v2-2-21]]

^<<v2-2-21,21>>^ Então Moisés concordou em morar com aquele homem, o qual lhe deu sua filha Zípora.

[[v2-2-22]]

^<<v2-2-22,22>>^ E ela deu à luz um filho, a quem ele chamou Gérson, porque disse: Peregrino sou em terra estrangeira.

[[v2-2-23]]

^<<v2-2-23,23>>^ No decorrer de muitos dias, morreu o rei do Egito; e os filhos de Israel gemiam debaixo da servidão; pelo que clamaram, e subiu a Deus o seu clamor por causa dessa servidão.

[[v2-2-24]]

^<<v2-2-24,24>>^ Então Deus, ouvindo-lhes os gemidos, lembrou-se do seu pacto com Abraão, com Isaque e com Jacó.

[[v2-2-25]]

^<<v2-2-25,25>>^ E atentou Deus para os filhos de Israel; e Deus os conheceu.

'''

xref:002-exodo/002-exodo-001.adoc#v2-1-0[&#60; Capítulo Anterior] | <<v2-2-0,Topo>> | xref:002-exodo/002-exodo-003.adoc#v2-3-0[Próximo Capítulo &#62;]