include::./index.adoc[]

[[v2-39-0]]
=== Êxodo, 39
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-39-1]]

^<<v2-39-1,1>>^ Fizeram também de azul, púrpura e carmesim as vestes, finamente tecidas, para ministrar no lugar santo, e fizeram as vestes sagradas para Arão, como o Senhor ordenara a Moisés.

[[v2-39-2]]

^<<v2-39-2,2>>^ Assim se fez o éfode de ouro, azul, púrpura, carmesim e linho fino torcido;

[[v2-39-3]]

^<<v2-39-3,3>>^ bateram o ouro em lâminas delgadas, as quais cortaram em fios, para entretecê-lo no azul, na púrpura, no carmesim e no linho fino, em obra de desenhista;

[[v2-39-4]]

^<<v2-39-4,4>>^ fizeram-lhe ombreiras que se uniam; assim pelos seus dois cantos superiores foi ele unido.

[[v2-39-5]]

^<<v2-39-5,5>>^ E o cinto da obra esmerada do éfode, que estava sobre ele, formava com ele uma só peça e era de obra semelhante, de ouro, azul, púrpura, carmesim e linho fino torcido, como o Senhor ordenara a Moisés.

[[v2-39-6]]

^<<v2-39-6,6>>^ Também prepararam as pedras de berilo, engastadas em ouro, lavradas como a gravura de um selo, com os nomes dos filhos de Israel;

[[v2-39-7]]

^<<v2-39-7,7>>^ as quais puseram sobre as ombreiras do éfode para servirem de pedras de memorial para os filhos de Israel, como o Senhor ordenara a Moisés.

[[v2-39-8]]

^<<v2-39-8,8>>^ Fez-se também o peitoral de obra de desenhista, semelhante à obra do éfode, de ouro, azul, púrpura, carmesim e linho fino torcido.

[[v2-39-9]]

^<<v2-39-9,9>>^ Quadrado e duplo fizeram o peitoral; o seu comprimento era de um palmo, e a sua largura de um palmo, sendo ele dobrado.

[[v2-39-10]]

^<<v2-39-10,10>>^ E engastaram nele quatro fileiras de pedras: a primeira delas era de um sárdio, um topázio e uma esmeralda;

[[v2-39-11]]

^<<v2-39-11,11>>^ a segunda fileira era de uma granada, uma safira e um ônix;

[[v2-39-12]]

^<<v2-39-12,12>>^ a terceira fileira era de um jacinto, uma ágata e uma ametista;

[[v2-39-13]]

^<<v2-39-13,13>>^ e a quarta fileira era de uma crisólita, um berilo e um jaspe; eram elas engastadas nos seus engastes de ouro.

[[v2-39-14]]

^<<v2-39-14,14>>^ Estas pedras, pois, eram doze, segundo os nomes dos filhos de Israel; eram semelhantes a gravuras de selo, cada uma com o nome de uma das doze tribos.

[[v2-39-15]]

^<<v2-39-15,15>>^ Também fizeram sobre o peitoral cadeiazinhas, semelhantes a cordas, obra de trança, de ouro puro.

[[v2-39-16]]

^<<v2-39-16,16>>^ Fizeram também dois engastes de ouro e duas argolas de ouro, e fixaram as duas argolas nas duas extremidades do peitoral.

[[v2-39-17]]

^<<v2-39-17,17>>^ E meteram as duas cadeiazinhas de trança de ouro nas duas argolas, nas extremidades do peitoral.

[[v2-39-18]]

^<<v2-39-18,18>>^ E as outras duas pontas das duas cadeiazinhas de trança meteram nos dois engastes, e as puseram sobre as ombreiras do éfode, na parte dianteira dele.

[[v2-39-19]]

^<<v2-39-19,19>>^ Fizeram outras duas argolas de ouro, que puseram nas duas extremidades do peitoral, na sua borda que estava junto ao éfode por dentro.

[[v2-39-20]]

^<<v2-39-20,20>>^ Fizeram mais duas argolas de ouro, que puseram nas duas ombreiras do éfode, debaixo, na parte dianteira dele, junto à sua costura, acima do cinto de obra esmerada do éfode.

[[v2-39-21]]

^<<v2-39-21,21>>^ E ligaram o peitoral, pelas suas argolas, às argolas do éfode por meio de um cordão azul, para que estivesse sobre o cinto de obra esmerada do éfode, e o peitoral não se separasse do éfode, como o Senhor ordenara a Moisés.

[[v2-39-22]]

^<<v2-39-22,22>>^ Fez-se também o manto do éfode de obra tecida, todo de azul,

[[v2-39-23]]

^<<v2-39-23,23>>^ e a abertura do manto no meio dele, como a abertura de cota de malha; esta abertura tinha um debrum em volta, para que não se rompesse.

[[v2-39-24]]

^<<v2-39-24,24>>^ Nas abas do manto fizeram romãs de azul, púrpura e carmesim, de fio torcido.

[[v2-39-25]]

^<<v2-39-25,25>>^ Fizeram também campainhas de ouro puro, pondo as campainhas nas abas do manto ao redor, entremeadas com as romãs;

[[v2-39-26]]

^<<v2-39-26,26>>^ uma campainha e uma romã, outra campainha e outra romã, nas abas do manto ao redor, para uso no ministério, como o Senhor ordenara a Moisés.

[[v2-39-27]]

^<<v2-39-27,27>>^ Fizeram também as túnicas de linho fino, de obra tecida, para Arão e para seus filhos,

[[v2-39-28]]

^<<v2-39-28,28>>^ e a mitra de linho fino, e o ornato das tiaras de linho fino, e os calções de linho fino torcido,

[[v2-39-29]]

^<<v2-39-29,29>>^ e o cinto de linho fino torcido, e de azul, púrpura e carmesim, obra de bordador, como o Senhor ordenara a Moisés.

[[v2-39-30]]

^<<v2-39-30,30>>^ Fizeram também, de ouro puro, a lâmina da coroa sagrada, e nela gravaram uma inscrição como a gravura de um selo: SANTO AO SENHOR.

[[v2-39-31]]

^<<v2-39-31,31>>^ E a ela ataram um cordão azul, para prendê-la à parte superior da mitra, como o Senhor ordenara a Moisés.

[[v2-39-32]]

^<<v2-39-32,32>>^ Assim se acabou toda a obra do tabernáculo da tenda da revelação; e os filhos de Israel fizeram conforme tudo o que o Senhor ordenara a Moisés; assim o fizeram.

[[v2-39-33]]

^<<v2-39-33,33>>^ Depois trouxeram a Moisés o tabernáculo, a tenda e todos os seus utensílios, os seus colchetes, as suas tábuas, os seus travessões, as suas colunas e as suas bases;

[[v2-39-34]]

^<<v2-39-34,34>>^ e a cobertura de peles de carneiros tintas de vermelho, e a cobertura de peles de golfinhos, e o véu do reposteiro;

[[v2-39-35]]

^<<v2-39-35,35>>^ a arca do testemunho com os seus varais, e o propiciatório;

[[v2-39-36]]

^<<v2-39-36,36>>^ a mesa com todos os seus utensílios, e os pães da proposição;

[[v2-39-37]]

^<<v2-39-37,37>>^ o candelabro puro com suas lâmpadas todas em ordem, com todos os seus utensílios, e o azeite para a luz;

[[v2-39-38]]

^<<v2-39-38,38>>^ também o altar de ouro, o óleo da unção e o incenso aromático, e o reposteiro para a porta da tenda;

[[v2-39-39]]

^<<v2-39-39,39>>^ o altar de bronze e o seu crivo de bronze, os seus varais, e todos os seus utensílios; a pia e a sua base;

[[v2-39-40]]

^<<v2-39-40,40>>^ as cortinas do átrio, as suas colunas e as suas bases, e o reposteiro para a porta do átrio, as suas cordas e as suas estacas, e todos os utensílios do serviço do tabernáculo, para a tenda da revelação;

[[v2-39-41]]

^<<v2-39-41,41>>^ as vestes finamente tecidas para uso no ministério no lugar santo, e as vestes sagradas para Arão, o sacerdote, e as vestes para seus filhos, para administrarem o sacerdócio.

[[v2-39-42]]

^<<v2-39-42,42>>^ Conforme tudo o que o Senhor ordenara a Moisés, assim fizeram os filhos de Israel toda a obra.

[[v2-39-43]]

^<<v2-39-43,43>>^ Viu, pois, Moisés toda a obra, e eis que a tinham feito; como o Senhor ordenara, assim a fizeram; então Moisés os abençoou.

'''

xref:002-exodo/002-exodo-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodo/002-exodo-040.adoc#v2-40-0[Próximo Capítulo &#62;]