include::./index.adoc[]

[[v2-11-0]]
=== Êxodo, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-11-1]]

^<<v2-11-1,1>>^ Disse o Senhor a Moisés: Ainda mais uma praga trarei sobre Faraó, e sobre o Egito; depois ele vos deixará ir daqui; e, deixando vos ir a todos, com efeito vos expulsará daqui.

[[v2-11-2]]

^<<v2-11-2,2>>^ Fala agora aos ouvidos do povo, que cada homem peça ao seu vizinho, e cada mulher à sua vizinha, jóias de prata e jóias de ouro.

[[v2-11-3]]

^<<v2-11-3,3>>^ E o Senhor deu ao povo graça aos olhos dos egípcios. Além disso o varão Moisés era mui grande na terra do Egito, aos olhos dos servos de Faraó e aos olhos do povo.

[[v2-11-4]]

^<<v2-11-4,4>>^ Depois disse Moisés a Faraó: Assim diz o Senhor: À meia-noite eu sairei pelo meio do Egito;

[[v2-11-5]]

^<<v2-11-5,5>>^ e todos os primogênitos na terra do Egito morrerão, desde o primogênito de Faraó, que se assenta sobre o seu trono, até o primogênito da serva que está detrás da mó, e todos os primogênitos dos animais.

[[v2-11-6]]

^<<v2-11-6,6>>^ Pelo que haverá grande clamor em toda a terra do Egito, como nunca houve nem haverá jamais.

[[v2-11-7]]

^<<v2-11-7,7>>^ Mas contra os filhos de Israel nem mesmo um cão moverá a sua língua, nem contra homem nem contra animal; para que saibais que o Senhor faz distinção entre os egípcios e os filhos de Israel.

[[v2-11-8]]

^<<v2-11-8,8>>^ Então todos estes teus servos descerão a mim, e se inclinarão diante de mim, dizendo: Sai tu, e todo o povo que te segue as pisadas. Depois disso eu sairei. E Moisés saiu da presença de Faraó ardendo em ira.

[[v2-11-9]]

^<<v2-11-9,9>>^ Pois o Senhor dissera a Moisés: Faraó não vos ouvirá, para que as minhas maravilhas se multipliquem na terra do Egito.

[[v2-11-10]]

^<<v2-11-10,10>>^ E Moisés e Arão fizeram todas estas maravilhas diante de Faraó; mas o Senhor endureceu o coração de Faraó, que não deixou ir da sua terra os filhos de Israel.

'''

xref:002-exodo/002-exodo-010.adoc#v2-10-0[&#60; Capítulo Anterior] | <<v2-11-0,Topo>> | xref:002-exodo/002-exodo-012.adoc#v2-12-0[Próximo Capítulo &#62;]