include::./index.adoc[]

[[v2-12-0]]
=== Êxodo, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-12-1]]

^<<v2-12-1,1>>^ Ora, o Senhor falou a Moisés e a Arão na terra do Egito, dizendo:

[[v2-12-2]]

^<<v2-12-2,2>>^ Este mês será para vós o princípio dos meses; este vos será o primeiro dos meses do ano.

[[v2-12-3]]

^<<v2-12-3,3>>^ Falai a toda a congregação de Israel, dizendo: Ao décimo dia deste mês tomará cada um para si um cordeiro, segundo as casas dos pais, um cordeiro para cada família.

[[v2-12-4]]

^<<v2-12-4,4>>^ Mas se a família for pequena demais para um cordeiro, tomá-lo-á juntamente com o vizinho mais próximo de sua casa, conforme o número de almas; conforme ao comer de cada um, fareis a conta para o cordeiro.

[[v2-12-5]]

^<<v2-12-5,5>>^ O cordeiro, ou cabrito, será sem defeito, macho de um ano, o qual tomareis das ovelhas ou das cabras,

[[v2-12-6]]

^<<v2-12-6,6>>^ e o guardareis até o décimo quarto dia deste mês; e toda a assembléia da congregação de Israel o matará à tardinha:

[[v2-12-7]]

^<<v2-12-7,7>>^ Tomarão do sangue, e pô-lo-ão em ambos os umbrais e na verga da porta, nas casas em que o comerem.

[[v2-12-8]]

^<<v2-12-8,8>>^ E naquela noite comerão a carne assada ao fogo, com pães ázimos; com ervas amargosas a comerão.

[[v2-12-9]]

^<<v2-12-9,9>>^ Não comereis dele cru, nem cozido em água, mas sim assado ao fogo; a sua cabeça com as suas pernas e com a sua fressura.

[[v2-12-10]]

^<<v2-12-10,10>>^ Nada dele deixareis até pela manhã; mas o que dele ficar até pela manhã, queimá-lo-eis no fogo.

[[v2-12-11]]

^<<v2-12-11,11>>^ Assim pois o comereis: Os vossos lombos cingidos, os vossos sapatos nos pés, e o vosso cajado na mão; e o comereis apressadamente; esta é a páscoa do Senhor.

[[v2-12-12]]

^<<v2-12-12,12>>^ Porque naquela noite passarei pela terra do Egito, e ferirei todos os primogênitos na terra do Egito, tanto dos homens como dos animais; e sobre todos os deuses do Egito executarei juízos; eu sou o Senhor.

[[v2-12-13]]

^<<v2-12-13,13>>^ Mas o sangue vos será por sinal nas casas em que estiverdes; vendo eu o sangue, passarei por cima de vós, e não haverá entre vós praga para vos destruir, quando eu ferir a terra do Egito. :

[[v2-12-14]]

^<<v2-12-14,14>>^ E este dia vos será por memorial, e celebrá-lo-eis por festa ao Senhor; através das vossas gerações o celebrareis por estatuto perpétuo.

[[v2-12-15]]

^<<v2-12-15,15>>^ Por sete dias comereis pães ázimos; logo ao primeiro dia tirareis o fermento das vossas casas, porque qualquer que comer pão levedado, entre o primeiro e o sétimo dia, esse será cortado de Israel.

[[v2-12-16]]

^<<v2-12-16,16>>^ E ao primeiro dia haverá uma santa convocação; também ao sétimo dia tereis uma santa convocação; neles não se fará trabalho algum, senão o que diz respeito ao que cada um houver de comer; somente isso poderá ser feito por vós.

[[v2-12-17]]

^<<v2-12-17,17>>^ Guardareis, pois, a festa dos pães ázimos, porque nesse mesmo dia tirei vossos exércitos da terra do Egito; pelo que guardareis este dia através das vossas gerações por estatuto perpétuo.

[[v2-12-18]]

^<<v2-12-18,18>>^ No primeiro mês, aos catorze dias do mês, à tarde, comereis pães ázimos até vinte e um do mês à tarde.

[[v2-12-19]]

^<<v2-12-19,19>>^ Por sete dias não se ache fermento algum nas vossas casas; porque qualquer que comer pão levedado, esse será cortado da congregação de Israel, tanto o peregrino como o natural da terra.

[[v2-12-20]]

^<<v2-12-20,20>>^ Nenhuma coisa levedada comereis; em todas as vossas habitações comereis pães ázimos.

[[v2-12-21]]

^<<v2-12-21,21>>^ Chamou, pois, Moisés todos os anciãos de Israel, e disse-lhes: Ide e tomai-vos cordeiros segundo as vossas famílias, e imolai a páscoa.

[[v2-12-22]]

^<<v2-12-22,22>>^ Então tomareis um molho de hissopo, embebê-lo-eis no sangue que estiver na bacia e marcareis com ele a verga da porta e os dois umbrais; mas nenhum de vós sairá da porta da sua casa até pela manhã.

[[v2-12-23]]

^<<v2-12-23,23>>^ Porque o Senhor passará para ferir aos egípcios; e, ao ver o sangue na verga da porta e em ambos os umbrais, o Senhor passará aquela porta, e não deixará o destruidor entrar em vossas casas para vos ferir.

[[v2-12-24]]

^<<v2-12-24,24>>^ Portanto guardareis isto por estatuto para vós e para vossos filhos, para sempre.

[[v2-12-25]]

^<<v2-12-25,25>>^ Quando, pois, tiverdes entrado na terra que o Senhor vos dará, como tem prometido, guardareis este culto.

[[v2-12-26]]

^<<v2-12-26,26>>^ E quando vossos filhos vos perguntarem: Que quereis dizer com este culto?

[[v2-12-27]]

^<<v2-12-27,27>>^ Respondereis: Este é o sacrifício da páscoa do Senhor, que passou as casas dos filhos de Israel no Egito, quando feriu os egípcios, e livrou as nossas casas. Então o povo inclinou-se e adorou.

[[v2-12-28]]

^<<v2-12-28,28>>^ E foram os filhos de Israel, e fizeram isso; como o Senhor ordenara a Moisés e a Arão, assim fizeram.

[[v2-12-29]]

^<<v2-12-29,29>>^ E aconteceu que à meia-noite o Senhor feriu todos os primogênitos na terra do Egito, desde o primogênito de Faraó, que se assentava em seu trono, até o primogênito do cativo que estava no cárcere, e todos os primogênitos dos animais.

[[v2-12-30]]

^<<v2-12-30,30>>^ E Faraó levantou-se de noite, ele e todos os seus servos, e todos os egípcios; e fez-se grande clamor no Egito, porque não havia casa em que não houvesse um morto.

[[v2-12-31]]

^<<v2-12-31,31>>^ Então Faraó chamou Moisés e Arão de noite, e disse: Levantai-vos, saí do meio do meu povo, tanto vós como os filhos de Israel; e ide servir ao Senhor, como tendes dito.

[[v2-12-32]]

^<<v2-12-32,32>>^ Levai também convosco os vossos rebanhos e o vosso gado, como tendes dito; e ide, e abençoai-me também a mim.

[[v2-12-33]]

^<<v2-12-33,33>>^ E os egípcios apertavam ao povo, e apressando-se por lançá-los da terra; porque diziam: Estamos todos mortos.

[[v2-12-34]]

^<<v2-12-34,34>>^ Ao que o povo tomou a massa, antes que ela levedasse, e as amassadeiras atadas e em seus vestidos, sobre os ombros.

[[v2-12-35]]

^<<v2-12-35,35>>^ Fizeram, pois, os filhos de Israel conforme a palavra de Moisés, e pediram aos egípcios jóias de prata, e jóias de ouro, e vestidos.

[[v2-12-36]]

^<<v2-12-36,36>>^ E o Senhor deu ao povo graça aos olhos dos egípcios, de modo que estes lhe davam o que pedia; e despojaram aos egípcios.

[[v2-12-37]]

^<<v2-12-37,37>>^ Assim viajaram os filhos de Israel de a Ramessés a Sucote, cerca de seiscentos mil homens de pé, sem contar as crianças.

[[v2-12-38]]

^<<v2-12-38,38>>^ Também subiu com eles uma grande mistura de gente; e, em rebanhos e manadas, uma grande quantidade de gado.

[[v2-12-39]]

^<<v2-12-39,39>>^ E cozeram bolos ázimos da massa que levaram do Egito, porque ela não se tinha levedado, porquanto foram lançados do Egito; e não puderam deter-se, nem haviam preparado comida.

[[v2-12-40]]

^<<v2-12-40,40>>^ Ora, o tempo que os filhos de Israel moraram no Egito foi de quatrocentos e trinta anos.

[[v2-12-41]]

^<<v2-12-41,41>>^ E aconteceu que, ao fim de quatrocentos e trinta anos, naquele mesmo dia, todos os exércitos do Senhor saíram da terra do Egito.

[[v2-12-42]]

^<<v2-12-42,42>>^ Esta é uma noite que se deve guardar ao Senhor, porque os tirou da terra do Egito; esta é a noite do Senhor, que deve ser guardada por todos os filhos de Israel através das suas gerações.

[[v2-12-43]]

^<<v2-12-43,43>>^ Disse mais o Senhor a Moisés e a Arão: Esta é a ordenança da páscoa; nenhum, estrangeiro comerá dela;

[[v2-12-44]]

^<<v2-12-44,44>>^ mas todo escravo comprado por dinheiro, depois que o houveres circuncidado, comerá dela.

[[v2-12-45]]

^<<v2-12-45,45>>^ O forasteiro e o assalariado não comerão dela.

[[v2-12-46]]

^<<v2-12-46,46>>^ Numa só casa se comerá o cordeiro; não levareis daquela carne fora da casa nem lhe quebrareis osso algum.

[[v2-12-47]]

^<<v2-12-47,47>>^ Toda a congregação de Israel a observará.

[[v2-12-48]]

^<<v2-12-48,48>>^ Quando, porém, algum estrangeiro peregrinar entre vós e quiser celebrar a páscoa ao Senhor, circuncidem-se todos os seus varões; então se chegará e a celebrará, e será como o natural da terra; mas nenhum incircunciso comerá dela.

[[v2-12-49]]

^<<v2-12-49,49>>^ Haverá uma mesma lei para o natural e para o estrangeiro que peregrinar entre vós.

[[v2-12-50]]

^<<v2-12-50,50>>^ Assim, pois, fizeram todos os filhos de Israel; como o Senhor ordenara a Moisés e a Arão, assim fizeram.

[[v2-12-51]]

^<<v2-12-51,51>>^ E naquele mesmo dia o Senhor tirou os filhos de Israel da terra do Egito, segundo os seus exércitos.

'''

xref:002-exodo/002-exodo-011.adoc#v2-11-0[&#60; Capítulo Anterior] | <<v2-12-0,Topo>> | xref:002-exodo/002-exodo-013.adoc#v2-13-0[Próximo Capítulo &#62;]