include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v2-14-1]]

^<<v2-14-1,1>>^ Disse o Senhor a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ Fala aos filhos de Israel que se voltem e se acampem diante de Pi-Hairote, entre Migdol e o mar, diante de Baal-Zefom; em frente dele assentareis o acampamento junto ao mar.

[[v2-14-3]]

^<<v2-14-3,3>>^ Então Faraó dirá dos filhos de Israel: Eles estão embaraçados na terra, o deserto os encerrou.

[[v2-14-4]]

^<<v2-14-4,4>>^ Eu endurecerei o coração de Faraó, e ele os perseguirá; glorificar-me-ei em Faraó, e em todo o seu exército; e saberão os egípcios que eu sou o Senhor. E eles fizeram assim.

[[v2-14-5]]

^<<v2-14-5,5>>^ Quando, pois, foi anunciado ao rei do Egito que o povo havia fugido, mudou-se o coração de Faraó, e dos seus servos, contra o povo, e disseram: Que é isso que fizemos, permitindo que Israel saísse e deixasse de nos servir?

[[v2-14-6]]

^<<v2-14-6,6>>^ E Faraó aprontou o seu carro, e tomou consigo o seu povo;

[[v2-14-7]]

^<<v2-14-7,7>>^ tomou também seiscentos carros escolhidos e todos os carros do Egito, e capitães sobre todos eles.

[[v2-14-8]]

^<<v2-14-8,8>>^ Porque o Senhor endureceu o coração de Faraó, rei do Egito, e este perseguiu os filhos de Israel; pois os filhos de Israel saíam afoitamente.

[[v2-14-9]]

^<<v2-14-9,9>>^ Os egípcios, com todos os cavalos e carros de Faraó, e os seus cavaleiros e o seu exército, os perseguiram e os alcançaram acampados junto ao mar, perto de Pi-Hairote, diante de Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ Quando Faraó se aproximava, os filhos de Israel levantaram os olhos, e eis que os egípcios marchavam atrás deles; pelo que tiveram muito medo os filhos de Israel e clamaram ao Senhor:

[[v2-14-11]]

^<<v2-14-11,11>>^ e disseram a Moisés: Foi porque não havia sepulcros no Egito que de lá nos tiraste para morrermos neste deserto? Por que nos fizeste isto, tirando-nos do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não é isto o que te dissemos no Egito: Deixa-nos, que sirvamos aos egípcios? Pois melhor nos fora servir aos egípcios, do que morrermos no deserto.

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés, porém, disse ao povo: Não temais; estai quietos, e vede o livramento do Senhor, que ele hoje vos fará; porque aos egípcios que hoje vistes, nunca mais tornareis a ver;

[[v2-14-14]]

^<<v2-14-14,14>>^ o Senhor pelejará por vós; e vós vos calareis.

[[v2-14-15]]

^<<v2-14-15,15>>^ Então disse o Senhor a Moisés: Por que clamas a mim? dize aos filhos de Israel que marchem.

[[v2-14-16]]

^<<v2-14-16,16>>^ E tu, levanta a tua vara, e estende a mão sobre o mar e fende-o, para que os filhos de Israel passem pelo meio do mar em seco.

[[v2-14-17]]

^<<v2-14-17,17>>^ Eis que eu endurecerei o coração dos egípcios, e estes entrarão atrás deles; e glorificar-me-ei em Faraó e em todo o seu exército, nos seus carros e nos seus cavaleiros.

[[v2-14-18]]

^<<v2-14-18,18>>^ E os egípcios saberão que eu sou o Senhor, quando me tiver glorificado em Faraó, nos seus carros e nos seus cavaleiros.

[[v2-14-19]]

^<<v2-14-19,19>>^ Então o anjo de Deus, que ia adiante do exército de Israel, se retirou e se pôs atrás deles; também a coluna de nuvem se retirou de diante deles e se pôs atrás,

[[v2-14-20]]

^<<v2-14-20,20>>^ colocando-se entre o campo dos egípcios e o campo dos israelitas; assim havia nuvem e trevas; contudo aquela clareava a noite para Israel; de maneira que em toda a noite não se aproximou um do outro.

[[v2-14-21]]

^<<v2-14-21,21>>^ Então Moisés estendeu a mão sobre o mar; e o Senhor fez retirar o mar por um forte vento oriental toda aquela noite, e fez do mar terra seca, e as águas foram divididas.

[[v2-14-22]]

^<<v2-14-22,22>>^ E os filhos de Israel entraram pelo meio do mar em seco; e as águas foram-lhes qual muro à sua direita e à sua esquerda.

[[v2-14-23]]

^<<v2-14-23,23>>^ E os egípcios os perseguiram, e entraram atrás deles até o meio do mar, com todos os cavalos de Faraó, os seus carros e os seus cavaleiros.

[[v2-14-24]]

^<<v2-14-24,24>>^ Na vigília da manhã, o Senhor, na coluna do fogo e da nuvem, olhou para o campo dos egípcios, e alvoroçou o campo dos egípcios;

[[v2-14-25]]

^<<v2-14-25,25>>^ embaraçou-lhes as rodas dos carros, e fê-los andar dificultosamente; de modo que os egípcios disseram: Fujamos de diante de Israel, porque o Senhor peleja por eles contra os egípcios.

[[v2-14-26]]

^<<v2-14-26,26>>^ Nisso o Senhor disse a Moisés: Estende a mão sobre o mar, para que as águas se tornem sobre os egípcios, sobre os seus carros e sobre os seus cavaleiros.

[[v2-14-27]]

^<<v2-14-27,27>>^ Então Moisés estendeu a mão sobre o mar, e o mar retomou a sua força ao amanhecer, e os egípcios fugiram de encontro a ele; assim o Senhor derribou os egípcios no meio do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas, tornando, cobriram os carros e os cavaleiros, todo o exército de Faraó, que atrás deles havia entrado no mar; não ficou nem sequer um deles.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os filhos de Israel caminharam a pé enxuto pelo meio do mar; as águas foram-lhes qual muro à sua direita e à sua esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Assim o Senhor, naquele dia, salvou Israel da mão dos egípcios; e Israel viu os egípcios mortos na praia do mar.

[[v2-14-31]]

^<<v2-14-31,31>>^ E viu Israel a grande obra que o Senhor operara contra os egípcios; pelo que o povo temeu ao Senhor, e creu no Senhor e em Moisés, seu servo.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]