include::./index.adoc[]

[[v7-16-0]]
=== Juízes, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-16-1]]

^<<v7-16-1,1>>^ Sansão foi a Gaza, e viu ali uma prostituta, e entrou a ela.

[[v7-16-2]]

^<<v7-16-2,2>>^ E foi dito aos gazitas: Sansão entrou aqui. Cercaram-no, pois, e de emboscada à porta da cidade o esperaram toda a noite; assim ficaram quietos a noite toda, dizendo: Quando raiar o dia, matá-lo-emos.

[[v7-16-3]]

^<<v7-16-3,3>>^ Mas Sansão deitou-se até a meia-noite; então, levantando-se, pegou nas portas da entrada da cidade, com ambos os umbrais, arrancou-as juntamente com a tranca e, pondo-as sobre os ombros, levou-as até o cume do monte que está defronte de Hebrom.

[[v7-16-4]]

^<<v7-16-4,4>>^ Depois disto se afeiçoou a uma mulher do vale de Soreque, cujo nome era Dalila.

[[v7-16-5]]

^<<v7-16-5,5>>^ Então os chefes dos filisteus subiram a ter com ela, e lhe disseram: Persuade-o, e vê em que consiste a sua grande força, e como poderemos prevalecer contra ele e amarrá-lo, para assim o afligirmos; e te daremos, cada um de nós, mil e cem moedas de prata.

[[v7-16-6]]

^<<v7-16-6,6>>^ Disse, pois, Dalila a Sansão: Declara-me, peço-te, em que consiste a tua grande força, e com que poderias ser amarrado para te poderem afligir.

[[v7-16-7]]

^<<v7-16-7,7>>^ Respondeu-lhe Sansão: Se me amarrassem com sete cordas de nervos, ainda não secados, então me tornaria fraco, e seria como qualquer outro homem.

[[v7-16-8]]

^<<v7-16-8,8>>^ Então os chefes dos filisteus trouxeram a Dalila sete cordas de nervos, ainda não secados, com as quais ela o amarrou.

[[v7-16-9]]

^<<v7-16-9,9>>^ Ora, tinha ela em casa uns espias sentados na câmara interior. Então ela disse: Os filisteus vêm sobre ti, Sansão! E ele quebrou as cordas de nervos, como se quebra o fio da estopa ao lhe chegar o fogo. Assim não se soube em que consistia a sua força.

[[v7-16-10]]

^<<v7-16-10,10>>^ Disse, pois, Dalila a Sansão: Eis que zombaste de mim, e me disseste mentiras; declara-me agora com que poderia ser a amarrado.

[[v7-16-11]]

^<<v7-16-11,11>>^ Respondeu-lhe ele: Se me amarrassem fortemente com cordas novas, que nunca tivessem sido usadas, então me tornaria fraco, e seria como qualquer outro homem.

[[v7-16-12]]

^<<v7-16-12,12>>^ Então Dalila tomou cordas novas, e o amarrou com elas, e disse-lhe: Os filisteus vêm sobre ti, Sansão! E os espias estavam sentados na câmara interior. Porém ele as quebrou de seus braços como a um fio.

[[v7-16-13]]

^<<v7-16-13,13>>^ Disse Dalila a Sansão: Até agora zombaste de mim, e me disseste mentiras; declara-me pois, agora, com que poderia ser amarrado. E ele lhe disse: Se teceres as sete tranças da minha cabeça com os liços da teia.

[[v7-16-14]]

^<<v7-16-14,14>>^ Assim ela as fixou com o torno de tear, e disse-lhe: Os filisteus vêm sobre ti, Sansão! Então ele despertou do seu sono, e arrancou o torno do tear, juntamente com os liços da teia.

[[v7-16-15]]

^<<v7-16-15,15>>^ Disse-lhe ela: como podes dizer: Eu te amo! não estando comigo o teu coração? Já três vezes zombaste de mim, e ainda não me declaraste em que consiste a tua força.

[[v7-16-16]]

^<<v7-16-16,16>>^ E sucedeu que, importunando-o ela todos os dias com as suas palavras, e molestando-o, a alma dele se angustiou até a morte.

[[v7-16-17]]

^<<v7-16-17,17>>^ E descobriu-lhe todo o seu coração, e disse-lhe: Nunca passou navalha pela minha cabeça, porque sou nazireu de Deus desde o ventre de minha mãe; se viesse a ser rapado, ir-se-ia de mim a minha força, e me tornaria fraco, e seria como qualquer outro homem.

[[v7-16-18]]

^<<v7-16-18,18>>^ Vendo Dalila que ele lhe descobrira todo o seu coração, mandou chamar os chefes dos filisteus, dizendo: Subi ainda esta vez, porque agora me descobriu ele todo o seu coração. E os chefes dos filisteus subiram a ter com ela, trazendo o dinheiro nas mãos.

[[v7-16-19]]

^<<v7-16-19,19>>^ Então ela o fez dormir sobre os seus joelhos, e mandou chamar um homem para lhe rapar as sete tranças de sua cabeça. Depois começou a afligi-lo, e a sua força se lhe foi.

[[v7-16-20]]

^<<v7-16-20,20>>^ E disse ela: Os filisteus vêm sobre ti, Sansão! Despertando ele do seu sono, disse: Sairei, como das outras vezes, e me livrarei. Pois ele não sabia que o Senhor se tinha retirado dele.

[[v7-16-21]]

^<<v7-16-21,21>>^ Então os filisteus pegaram nele, arrancaram-lhe os olhos e, tendo-o levado a Gaza, amarraram-no com duas cadeias de bronze; e girava moinho no cárcere.

[[v7-16-22]]

^<<v7-16-22,22>>^ Todavia o cabelo da sua cabeça, logo que foi rapado, começou a crescer de novo:

[[v7-16-23]]

^<<v7-16-23,23>>^ Então os chefes dos filisteus se ajuntaram para oferecer um grande sacrifício ao seu deus Dagom, e para se regozijar; pois diziam: Nosso deus nos entregou nas mãos a Sansão, nosso inimigo.

[[v7-16-24]]

^<<v7-16-24,24>>^ semelhantemente o povo, vendo-o, louvava ao seu deus, dizendo: Nosso Deus nos entregou nas mãos o nosso inimigo, aquele que destruía a nossa terra, e multiplicava os nossos mortos.

[[v7-16-25]]

^<<v7-16-25,25>>^ E sucedeu que, alegrando-se o seu coração, disseram: Mandai vir Sansão, para que brinque diante de nós. Mandaram, pois, vir do cárcere Sansão, que brincava diante deles; e fizeram-no estar em pé entre as colunas.

[[v7-16-26]]

^<<v7-16-26,26>>^ Disse Sansão ao moço que lhe segurava a mão: Deixa-me apalpar as colunas em que se sustém a casa, para que me encoste a elas.

[[v7-16-27]]

^<<v7-16-27,27>>^ Ora, a casa estava cheia de homens e mulheres; e também ali estavam todos os chefes dos filisteus, e sobre o telhado havia cerca de três mil homens e mulheres, que estavam vendo Sansão brincar.

[[v7-16-28]]

^<<v7-16-28,28>>^ Então Sansão clamou ao Senhor, e disse: Ó Senhor Deus! lembra-te de mim, e fortalece-me agora só esta vez, ó Deus, para que duma só vez me vingue dos filisteus pelos meus dois olhos.

[[v7-16-29]]

^<<v7-16-29,29>>^ Abraçou-se, pois, Sansão com as duas colunas do meio, em que se sustinha a casa, arrimando-se numa com a mão direita, e na outra com a esquerda.

[[v7-16-30]]

^<<v7-16-30,30>>^ E bradando: Morra eu com os filisteus! inclinou-se com toda a sua força, e a casa caiu sobre os chefes e sobre todo o povo que nela havia. Assim foram mais os que matou ao morrer, do que os que matara em vida.

[[v7-16-31]]

^<<v7-16-31,31>>^ Então desceram os seus irmãos e toda a casa de seu pai e, tomando-o, o levaram e o sepultaram, entre Zorá e Estaol, no sepulcro de Manoá, seu pai. Ele havia julgado a Israel vinte anos.

'''

xref:007-juizes/007-juizes-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-juizes/007-juizes-017.adoc#v7-17-0[Próximo Capítulo &#62;]