include::./index.adoc[]

[[v7-3-0]]
=== Juízes, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-3-1]]

^<<v7-3-1,1>>^ Estas são as nações que o Senhor deixou ficar para, por meio delas, provar a Israel, a todos os que não haviam experimentado nenhuma das guerras de Canaã;

[[v7-3-2]]

^<<v7-3-2,2>>^ tão-somente para que as gerações dos filhos de Israel delas aprendessem a guerra, pelo menos os que dantes não tinham aprendido.

[[v7-3-3]]

^<<v7-3-3,3>>^ Estas nações eram: cinco chefes dos filisteus, todos os cananeus, os sidônios, e os heveus que habitavam no monte Líbano, desde o monte Baal-Hermom até a entrada de Hamate.

[[v7-3-4]]

^<<v7-3-4,4>>^ Estes, pois, deixou ficar, a fim de por eles provar os filhos de Israel, para saber se dariam ouvidos aos mandamentos do Senhor, que ele tinha ordenado a seus pais por intermédio de Moisés.

[[v7-3-5]]

^<<v7-3-5,5>>^ Habitando, pois, os filhos de Israel entre os cananeus, os heteus, os amorreus, os perizeus, os heveus e os jebuseus.

[[v7-3-6]]

^<<v7-3-6,6>>^ tomaram por mulheres as filhas deles, e deram as suas filhas aos filhos dos mesmos, e serviram aos seus deuses.

[[v7-3-7]]

^<<v7-3-7,7>>^ Assim os filhos de Israel fizeram o que era mau aos olhos do Senhor, esquecendo-se do Senhor seu Deus e servindo aos baalins e às aserotes.

[[v7-3-8]]

^<<v7-3-8,8>>^ Pelo que a ira do Senhor se acendeu contra Israel, e ele os vendeu na mão de Cusã-Risataim, rei da Mesopotâmia; e os filhos de Israel serviram a Cusã-Risataim oito anos.

[[v7-3-9]]

^<<v7-3-9,9>>^ Mas quando os filhos de Israel clamaram ao Senhor, o Senhor suscitou-lhes um libertador, que os livrou: Otniel, filho de Quenaz, o irmão mais moço de Calebe.

[[v7-3-10]]

^<<v7-3-10,10>>^ Veio sobre ele o Espírito do Senhor, e ele julgou a Israel; saiu à peleja, e o Senhor lhe entregou Cusã-Risataim, rei da Mesopotâmia, contra o qual prevaleceu a sua mão:

[[v7-3-11]]

^<<v7-3-11,11>>^ Então a terra teve sossego por quarenta anos; e Otniel, filho de Quenaz, morreu.

[[v7-3-12]]

^<<v7-3-12,12>>^ Os filhos de Israel tornaram a fazer o que era mau aos olhos do Senhor; então o Senhor fortaleceu a Eglom, rei de Moabe, contra Israel, por terem feito o que era mau aos seus olhos.

[[v7-3-13]]

^<<v7-3-13,13>>^ Eglom, unindo a si os amonitas e os amalequitas, foi e feriu a Israel, tomando a cidade das palmeiras.

[[v7-3-14]]

^<<v7-3-14,14>>^ E os filhos de Israel serviram a Eglom, rei de Moabe, dezoito anos.

[[v7-3-15]]

^<<v7-3-15,15>>^ Mas quando os filhos de Israel clamaram ao Senhor, o Senhor suscitou-lhes um libertador, Eúde, filho de Gêra, benjamita, homem canhoto. E, por seu intermédio, os filhos de Israel enviaram tributo a Eglom, rei de Moabe.

[[v7-3-16]]

^<<v7-3-16,16>>^ E Eúde fez para si uma espada de dois gumes, de um côvado de comprimento, e cingiu-a à coxa direita, por baixo das vestes.

[[v7-3-17]]

^<<v7-3-17,17>>^ E levou aquele tributo a Eglom, rei de Moabe. Ora, Eglom era muito gordo:

[[v7-3-18]]

^<<v7-3-18,18>>^ Quando Eúde acabou de entregar o tributo, despediu a gente que o trouxera.

[[v7-3-19]]

^<<v7-3-19,19>>^ Ele mesmo, porém, voltou das imagens de escultura que estavam ao pé de Gilgal, e disse: Tenho uma palavra para dizer-te em segredo, ó rei. Disse o rei: Silêncio! E todos os que lhe assistiam saíram da sua presença.

[[v7-3-20]]

^<<v7-3-20,20>>^ Eúde aproximou-se do rei, que estava sentado a sós no seu quarto de verão, e lhe disse: Tenho uma palavra da parte de Deus para dizer-te. Ao que o rei se levantou da sua cadeira.

[[v7-3-21]]

^<<v7-3-21,21>>^ Então Eúde, estendendo a mão esquerda, tirou a espada de sobre a coxa direita, e lha cravou no ventre.

[[v7-3-22]]

^<<v7-3-22,22>>^ O cabo também entrou após a lâmina, e a gordura encerrou a lâmina, pois ele não tirou a espada do ventre:

[[v7-3-23]]

^<<v7-3-23,23>>^ Então Eúde, saindo ao pórtico, cerrou as portas do quarto e as trancou.

[[v7-3-24]]

^<<v7-3-24,24>>^ Tendo ele saído vieram os servos do rei; e olharam, e eis que as portas do quarto estavam trancadas. Disseram: Sem dúvida ele está aliviando o ventre na privada do seu quarto.

[[v7-3-25]]

^<<v7-3-25,25>>^ Assim esperaram até ficarem alarmados, mas ainda não abria as portas do quarto. Então, tomando a chave, abriram-nas, e eis seu senhor estendido morto por terra.

[[v7-3-26]]

^<<v7-3-26,26>>^ Eúde escapou enquanto eles se demoravam e, tendo passado pelas imagens de escultura, chegou a Seirá.

[[v7-3-27]]

^<<v7-3-27,27>>^ E assim que chegou, tocou a trombeta na região montanhosa de Efraim; e os filhos de Israel, com ele à frente, desceram das montanhas.

[[v7-3-28]]

^<<v7-3-28,28>>^ E disse-lhes: Segui-me, porque o Senhor vos entregou nas mãos os vossos inimigos, os moabitas. E desceram após ele, tomaram os vaus do Jordão contra os moabitas, e não deixaram passar a nenhum deles.

[[v7-3-29]]

^<<v7-3-29,29>>^ E naquela ocasião mataram dos moabitas cerca de dez mil homens, todos robustos e valentes; e não escapou nenhum.

[[v7-3-30]]

^<<v7-3-30,30>>^ Assim foi subjugado Moabe naquele dia debaixo da mão de Israel; e a terra teve sossego por oitenta anos.

[[v7-3-31]]

^<<v7-3-31,31>>^ Depois dele levantou-se Sangar, filho de Anate, que matou seiscentos homens dos filisteus com uma aguilhada de bois; ele também libertou a Israel.

'''

xref:007-juizes/007-juizes-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-juizes/007-juizes-004.adoc#v7-4-0[Próximo Capítulo &#62;]