include::./index.adoc[]

[[v7-5-0]]
=== Juízes, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-5-1]]

^<<v7-5-1,1>>^ Então cantaram Débora e Baraque, filho de Abinoão, naquele dia, dizendo:

[[v7-5-2]]

^<<v7-5-2,2>>^ Porquanto os chefes se puseram à frente em Israel, porquanto o povo se ofereceu voluntariamente, louvai ao Senhor.

[[v7-5-3]]

^<<v7-5-3,3>>^ Ouvi, ó reis; dai ouvidos, ó príncipes! eu cantarei ao Senhor, salmodiarei ao Senhor Deus de Israel.

[[v7-5-4]]

^<<v7-5-4,4>>^ Ó Senhor, quando saíste de Seir, quando caminhaste desde o campo de Edom, a terra estremeceu, os céus gotejaram, sim, as nuvens gotejaram águas.

[[v7-5-5]]

^<<v7-5-5,5>>^ Os montes se abalaram diante do Senhor, e até Sinai, diante do Senhor Deus de Israel.

[[v7-5-6]]

^<<v7-5-6,6>>^ Nos dias de Sangar, filho de Anate, nos dias de Jael, cessaram as caravanas; e os que viajavam iam por atalhos desviados.

[[v7-5-7]]

^<<v7-5-7,7>>^ Cessaram as aldeias em Israel, cessaram; até que eu Débora, me levantei, até que eu me levantei por mãe em Israel.

[[v7-5-8]]

^<<v7-5-8,8>>^ Escolheram deuses novos; logo a guerra estava às portas; via-se porventura escudo ou lança entre quarenta mil em Israel?

[[v7-5-9]]

^<<v7-5-9,9>>^ Meu coração inclina-se para os guias de Israel, que voluntariamente se ofereceram entre o povo. Bendizei ao Senhor.

[[v7-5-10]]

^<<v7-5-10,10>>^ Louvai-o vós, os que cavalgais sobre jumentas brancas, que vos assentais sobre ricos tapetes; e vós, que andais pelo caminho.

[[v7-5-11]]

^<<v7-5-11,11>>^ Onde se ouve o estrondo dos flecheiros, entre os lugares onde se tiram águas, ali falarão das justiças do Senhor, das justiças que fez às suas aldeias em Israel; então o povo do Senhor descia às portas.

[[v7-5-12]]

^<<v7-5-12,12>>^ Desperta, desperta, Débora; desperta, desperta, entoa um cântico; levanta-te, Baraque, e leva em cativeiro os teus prisioneiros, tu, filho de Abinoão.

[[v7-5-13]]

^<<v7-5-13,13>>^ Então desceu o restante dos nobres e do povo; desceu o Senhor por mim contra os poderosos.

[[v7-5-14]]

^<<v7-5-14,14>>^ De Efraim desceram os que tinham a sua raiz em Amaleque, após ti, Benjamim, entre os teus povos; de Maquir desceram os guias, e de Zebulom os que levam o báculo do inspetor de tropas.

[[v7-5-15]]

^<<v7-5-15,15>>^ Também os príncipes de Issacar estavam com Débora; e como Issacar, assim também Baraque; ao vale precipitaram-se em suas pegadas. Junto aos ribeiros de Rúben grandes foram as resoluções do coração.

[[v7-5-16]]

^<<v7-5-16,16>>^ Por que ficastes entre os currais a escutar os balidos dos rebanhos? Junto aos ribeiros de Rúben grandes foram as resoluções do coração.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gileade ficou da banda dalém do Jordão; e Dã, por que se deteve com seus navios? Aser se assentou na costa do mar e ficou junto aos seus portos.

[[v7-5-18]]

^<<v7-5-18,18>>^ Zebulom é um povo que se expôs à morte, como também Naftali, nas alturas do campo.

[[v7-5-19]]

^<<v7-5-19,19>>^ Vieram reis e pelejaram; pelejaram os reis de Canaã, em Taanaque junto às águas de Megido; não tomaram despojo de prata.

[[v7-5-20]]

^<<v7-5-20,20>>^ Desde os céus pelejaram as estrelas; desde as suas órbitas pelejaram contra Sísera.

[[v7-5-21]]

^<<v7-5-21,21>>^ O ribeiro de Quisom os arrastou, aquele antigo ribeiro, o ribeiro de Quisom. Ó minha alma, calcaste aos pés a força.

[[v7-5-22]]

^<<v7-5-22,22>>^ Então os cascos dos cavalos feriram a terra na fuga precipitada dos seus valentes.

[[v7-5-23]]

^<<v7-5-23,23>>^ Amaldiçoai a Meroz, diz o anjo do Senhor, amaldiçoai acremente aos seus habitantes; porquanto não vieram em socorro do Senhor, em socorro do Senhor, entre os valentes.

[[v7-5-24]]

^<<v7-5-24,24>>^ Bendita entre todas as mulheres será Jael, mulher de Heber, o queneu; bendita será entre as mulheres nômades.

[[v7-5-25]]

^<<v7-5-25,25>>^ Água pediu ele, leite lhe deu ela; em taça de príncipes lhe ofereceu coalhada.

[[v7-5-26]]

^<<v7-5-26,26>>^ À estaca estendeu a mão esquerda, e ao martelo dos trabalhadores a direita, e matou a Sísera, rachando-lhe a cabeça; furou e traspassou-lhe as fontes.

[[v7-5-27]]

^<<v7-5-27,27>>^ Aos pés dela ele se encurvou, caiu, ficou estirado; aos pés dela se encurvou, caiu; onde se encurvou, ali caiu morto.

[[v7-5-28]]

^<<v7-5-28,28>>^ A mãe de Sísera olhando pela janela, através da grade exclamava: Por que tarda em vir o seu carro? por que se demora o rumor das suas carruagens?

[[v7-5-29]]

^<<v7-5-29,29>>^ As mais sábias das suas damas responderam, e ela respondia a si mesma:

[[v7-5-30]]

^<<v7-5-30,30>>^ Não estão, porventura, achando e repartindo os despojos? uma ou duas donzelas a cada homem? para Sísera despojos de estofos tintos, despojos de estofos tintos bordados, bordados de várias cores, para o meu pescoço?

[[v7-5-31]]

^<<v7-5-31,31>>^ Assim ó Senhor, pereçam todos os teus inimigos! Sejam, porém, os que te amam, como o sol quando se levanta na sua força.

[[v7-5-32]]

^<<v7-5-32,32>>^ E a terra teve sossego por quarenta anos.

'''

xref:007-juizes/007-juizes-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-juizes/007-juizes-006.adoc#v7-6-0[Próximo Capítulo &#62;]