include::./index.adoc[]

[[v7-14-0]]
=== Juízes, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-14-1]]

^<<v7-14-1,1>>^ Desceu Sansão a Timnate; e vendo em Timnate uma mulher das filhas dos filisteus,

[[v7-14-2]]

^<<v7-14-2,2>>^ subiu, e declarou-o a seu pai e a sua mãe, dizendo: Vi uma mulher em Timnate, das filhas dos filisteus; agora pois, tomai-ma por mulher.

[[v7-14-3]]

^<<v7-14-3,3>>^ Responderam-lhe, porém, seu pai e sua mãe: Não há, porventura, mulher entre as filhas de teus irmãos, nem entre todo o nosso povo, para que tu vás tomar mulher dos filisteus, daqueles incircuncisos? Disse, porém, Sansão a seu pai: Toma esta para mim, porque ela muito me agrada.

[[v7-14-4]]

^<<v7-14-4,4>>^ Mas seu pai e sua mãe não sabiam que isto vinha do Senhor, que buscava ocasião contra os filisteus; porquanto naquele tempo os filisteus dominavam sobre Israel.

[[v7-14-5]]

^<<v7-14-5,5>>^ Desceu, pois, Sansão com seu pai e com sua mãe a Timnate. E, chegando ele às vinhas de Timnate, um leão novo, rugindo, saiu-lhe ao encontro.

[[v7-14-6]]

^<<v7-14-6,6>>^ Então o Espírito do Senhor se apossou dele, de modo que ele, sem ter coisa alguma na mão, despedaçou o leão como se fosse um cabrito. E não disse nem a seu pai nem a sua mãe o que tinha feito.

[[v7-14-7]]

^<<v7-14-7,7>>^ Depois desceu e falou àquela mulher; e ela muito lhe agradou.

[[v7-14-8]]

^<<v7-14-8,8>>^ Passado algum tempo, Sansão voltou para recebê-la; e apartando-se de caminho para ver o cadáver do leão, eis que nele havia um enxame de abelhas, e mel.

[[v7-14-9]]

^<<v7-14-9,9>>^ E tirando-o nas mãos, foi andando e comendo dele; chegando aonde estavam seu pai e sua mãe, deu-lhes do mel, e eles comeram; porém não lhes disse que havia tirado o mel do corpo do leão.

[[v7-14-10]]

^<<v7-14-10,10>>^ Desceu, pois, seu pai à casa da mulher; e Sansão fez ali um banquete, porque assim os mancebos costumavam fazer.

[[v7-14-11]]

^<<v7-14-11,11>>^ E sucedeu que, quando os habitantes do lugar o viram, trouxeram trinta companheiros para estarem com ele.

[[v7-14-12]]

^<<v7-14-12,12>>^ Disse-lhes, pois, Sansão: Permiti-me propor-vos um enigma; se nos sete dias das bodas o decifrardes e mo descobrirdes, eu vos darei trinta túnicas de linho e trinta mantos;

[[v7-14-13]]

^<<v7-14-13,13>>^ mas se não puderdes decifrar, vós me dareis a mim as trinta túnicas de linho e os trinta mantos. Ao que lhe responderam eles: Propõe o teu enigma, para que o ouçamos.

[[v7-14-14]]

^<<v7-14-14,14>>^ Então lhes disse: Do que come saiu comida, e do forte saiu doçura. E em três dias não puderam decifrar o enigma.

[[v7-14-15]]

^<<v7-14-15,15>>^ Ao quarto dia, pois, disseram à mulher de Sansão: Persuade teu marido a que declare o enigma, para que não queimemos a fogo a ti e à casa de teu pai. Acaso nos convidastes para nos despojardes?

[[v7-14-16]]

^<<v7-14-16,16>>^ E a mulher de Sansão chorou diante dele, e disse: Tão-somente me aborreces, e não me amas; pois propuseste aos filhos do meu povo um enigma, e não mo declaraste a mim. Respondeu-lhe ele: Eis que nem a meu pai nem a minha mãe o declarei, e to declararei a ti.

[[v7-14-17]]

^<<v7-14-17,17>>^ Assim ela chorava diante dele os sete dias em que celebravam as bodas. Sucedeu, pois, que ao sétimo dia lho declarou, porquanto o importunava; então ela declarou o enigma aos filhos do seu povo.

[[v7-14-18]]

^<<v7-14-18,18>>^ Os homens da cidade, pois, ainda no sétimo dia, antes de se pôr o sol, disseram a Sansão: Que coisa há mais doce do que o mel? e que coisa há mais forte do que o leão? Respondeu-lhes ele: Se vós não tivésseis lavrado com a minha novilha, não teríeis descoberto o meu enigma.

[[v7-14-19]]

^<<v7-14-19,19>>^ Então o Espírito do Senhor se apossou dele, de modo que desceu a Asquelom, matou trinta dos seus homens e, tomando as suas vestes, deu-as aos que declararam o enigma; e, ardendo em ira, subiu à casa de seu pai.

[[v7-14-20]]

^<<v7-14-20,20>>^ E a mulher de Sansão foi dada ao seu companheiro, que lhe servira de paraninfo.:

'''

xref:007-juizes/007-juizes-013.adoc#v7-13-0[&#60; Capítulo Anterior] | <<v7-14-0,Topo>> | xref:007-juizes/007-juizes-015.adoc#v7-15-0[Próximo Capítulo &#62;]