include::./index.adoc[]

[[v7-20-0]]
=== Juízes, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-20-1]]

^<<v7-20-1,1>>^ Então saíram todos os filhos de Israel, desde Dã até Berseba, e desde a terra de Gileade, e a congregação, como se fora um só homem, se ajuntou diante do senhor em Mizpá.

[[v7-20-2]]

^<<v7-20-2,2>>^ Os homens principais de todo o povo, de todas as tribos de Israel, apresentaram-se na assembléia do povo de Deus; eram quatrocentos mil homens de infantaria que arrancavam da espada.

[[v7-20-3]]

^<<v7-20-3,3>>^ &#123;Ora, ouviram os filhos de Benjamim que os filhos de Israel haviam subido a Mizpá&#125;. E disseram os filhos de Israel: Dizei-nos, de que modo se cometeu essa maldade?

[[v7-20-4]]

^<<v7-20-4,4>>^ Então respondeu o levita, marido da mulher que fora morta, e disse: Cheguei com a minha concubina a Gibeá, que pertence a Benjamim, para ali passar a noite;

[[v7-20-5]]

^<<v7-20-5,5>>^ e os cidadãos de Gibeá se levantaram contra mim, e cercaram e noite a casa em que eu estava; a mim intentaram matar, e violaram a minha concubina, de maneira que morreu.

[[v7-20-6]]

^<<v7-20-6,6>>^ Então peguei na minha concubina, dividi-a em pedaços e os enviei por todo o país da herança de Israel, porquanto cometeram tal abominação e loucura em Israel:

[[v7-20-7]]

^<<v7-20-7,7>>^ Eis aqui estais todos vós, ó filhos de Israel; dai a vossa palavra e conselho neste caso.

[[v7-20-8]]

^<<v7-20-8,8>>^ Então todo o povo se levantou como um só homem, dizendo: Nenhum de nós irá à sua tenda, e nenhum de nós voltará a sua casa.

[[v7-20-9]]

^<<v7-20-9,9>>^ Mas isto é o que faremos a Gibeá: subiremos contra ela por sorte;

[[v7-20-10]]

^<<v7-20-10,10>>^ tomaremos, de todas as tribos de Israel, dez homens de cada cem, cem de cada mil, e mil de cada dez mil, para trazerem mantimento para o povo, a fim de que, vindo ele a Gibeá de Benjamim, lhe faça conforme toda a loucura que ela fez em Israel.

[[v7-20-11]]

^<<v7-20-11,11>>^ Assim se ajuntaram contra essa cidade todos os homens de Israel, unidos como um só homem.

[[v7-20-12]]

^<<v7-20-12,12>>^ Então as tribos de Israel enviaram homens por toda a tribo de Benjamim, para lhe dizerem: Que maldade é essa que se fez entre vós?

[[v7-20-13]]

^<<v7-20-13,13>>^ Entregai-nos, pois, agora aqueles homens, filhos de Belial, que estão em Gibeá, para que os matemos, e extirpemos de Israel este mal. Mas os filhos de Benjamim não quiseram dar ouvidos à voz de seus irmãos, os filhos de Israel;

[[v7-20-14]]

^<<v7-20-14,14>>^ pelo contrário, das suas cidades se ajuntaram em Gibeá, para saírem a pelejar contra os filhos de Israel:

[[v7-20-15]]

^<<v7-20-15,15>>^ Ora, contaram-se naquele dia dos filhos de Benjamim, vindos das suas cidades, vinte e seis mil homens que arrancavam da espada, afora os moradores de Gibeá, de que se sentaram setecentos homens escolhidos.

[[v7-20-16]]

^<<v7-20-16,16>>^ Entre todo esse povo havia setecentos homens escolhidos, canhotos, cada um dos quais podia, com a funda, atirar uma pedra a um fio de cabelo, sem errar.

[[v7-20-17]]

^<<v7-20-17,17>>^ Contaram-se também dos homens de Israel, afora os de Benjamim, quatrocentos mil homens que arrancavam da espada, e todos eles homens de guerra.

[[v7-20-18]]

^<<v7-20-18,18>>^ Então, levantando-se os filhos de Israel, subiram a Betel, e consultaram a Deus, perguntando: Quem dentre nós subirá primeiro a pelejar contra Benjamim ? Respondeu o Senhor: Judá subirá primeiro.

[[v7-20-19]]

^<<v7-20-19,19>>^ Levantaram-se, pois, os filhos de Israel pela manhã, e acamparam contra Gibeá.

[[v7-20-20]]

^<<v7-20-20,20>>^ E os homens de Israel saíram a pelejar contra os benjamitas, e ordenaram a batalha contra eles ao pé de Gibeá.

[[v7-20-21]]

^<<v7-20-21,21>>^ Então os filhos de Benjamim saíram de Gibeá, e derrubaram por terra naquele dia vinte e dois mil homens de Israel.

[[v7-20-22]]

^<<v7-20-22,22>>^ Mas esforçou-se o povo, isto é, os homens de Israel, e tornaram a ordenar a batalha no lugar onde no primeiro dia a tinham ordenado.

[[v7-20-23]]

^<<v7-20-23,23>>^ E subiram os filhos de Israel, e choraram perante o Senhor até a tarde, e perguntaram-lhe: Tornaremos a pelejar contra os filhos de Benjamim, nosso irmão? E disse o Senhor: Subi contra eles.

[[v7-20-24]]

^<<v7-20-24,24>>^ Avançaram, pois, os filhos de Israel contra os filhos de Benjamim, no dia seguinte.

[[v7-20-25]]

^<<v7-20-25,25>>^ Também os de Benjamim, nesse mesmo dia, saíram de Gibeá ao seu encontro e derrubaram por terra mais dezoito mil homens, sendo todos estes dos que arrancavam da espada.

[[v7-20-26]]

^<<v7-20-26,26>>^ Então todos os filhos de Israel, o exército todo, subiram e, vindo a Betel, choraram; estiveram ali sentados perante o Senhor, e jejuaram aquele dia até a tarde; e ofereceram holocaustos e ofertas pacíficas perante ao Senhor.

[[v7-20-27]]

^<<v7-20-27,27>>^ Consultaram, pois, os filhos de Israel ao Senhor &#123;porquanto a arca do pacto de Deus estava ali naqueles dias;

[[v7-20-28]]

^<<v7-20-28,28>>^ e Finéias, filho de Eleazar, filho de Arão, lhe assistia&#125;, e perguntaram: Tornaremos ainda a sair à pelejar contra os filhos de Benjamim, nosso irmão, eu desistiremos? Respondeu o Senhor: Subi, porque amanhã vo-los entregarei nas mãos.

[[v7-20-29]]

^<<v7-20-29,29>>^ Então Israel pôs emboscadas ao redor de Gibeá.

[[v7-20-30]]

^<<v7-20-30,30>>^ E ao terceiro dia subiram os filhos de Israel contra os filhos de Benjamim e, como das outras vezes, ordenaram a batalha junto a Gibeá.

[[v7-20-31]]

^<<v7-20-31,31>>^ Então os filhos de Benjamim saíram ao encontro do povo, e foram atraídos da cidade. e começaram a ferir o povo como das outras vezes, matando uns trinta homens de Israel, pelos caminhos, um dos quais sobe para Betel, e o outro para Gibeá pelo campo.

[[v7-20-32]]

^<<v7-20-32,32>>^ Pelo que disseram os filhos de Benjamim: Vão sendo derrotados diante de nós como dantes. Mas os filhos de Israel disseram: Fujamos, e atraiamo-los da cidade para os caminhos.

[[v7-20-33]]

^<<v7-20-33,33>>^ Então todos os homens de Israel se levantaram do seu lugar, e ordenaram a batalha em Baal-Tamar; e a emboscada de Israel irrompeu do seu lugar, a oeste de Geba.

[[v7-20-34]]

^<<v7-20-34,34>>^ Vieram contra Gibeá dez mil homens escolhidos de todo o Israel, e a batalha tornou-se rude; porém os de Gibeá não sabiam que o mal lhes sobrevinha.

[[v7-20-35]]

^<<v7-20-35,35>>^ Então o Senhor derrotou a Benjamim diante dos filhos de Israel, que destruíram naquele dia vinte e cinco mil e cem homens de Benjamim, todos estes dos que arrancavam da espada.

[[v7-20-36]]

^<<v7-20-36,36>>^ Assim os filhos de Benjamim viram que estavam derrotados; pois os homens de Israel haviam cedido terreno aos benjamitas, porquanto estavam confiados na emboscada que haviam posto contra Gibeá;

[[v7-20-37]]

^<<v7-20-37,37>>^ e a emboscada, apressando-se, acometeu a Gibeá, e prosseguiu contra ela, ferindo ao fio da espada toda a cidade:

[[v7-20-38]]

^<<v7-20-38,38>>^ Ora, os homens de Israel tinham determinado com a emboscada um sinal, que era fazer levantar da cidade uma grande nuvem de fumaça.

[[v7-20-39]]

^<<v7-20-39,39>>^ Viraram-se, pois, os homens de Israel na peleja; e já Benjamim começara a atacar es homens de Israel, havendo morto uns trinta deles; pelo que diziam: Certamente vão sendo derrotados diante de nós, como na primeira batalha.

[[v7-20-40]]

^<<v7-20-40,40>>^ Mas quando o sinal começou a levantar-se da cidade, numa coluna de fumaça, os benjamitas olharam para trás de si, e eis que toda a cidade subia em fumaça ao céu.

[[v7-20-41]]

^<<v7-20-41,41>>^ Nisso os homens de Israel se viraram contra os de Benjamim, os quais pasmaram, pois viram que o mal lhes sobreviera.

[[v7-20-42]]

^<<v7-20-42,42>>^ Portanto, virando as costas diante dos homens de Israel, fugiram para o caminho do deserto; porém a peleja os apertou; e os que saíam das cidades os destruíam no meio deles.

[[v7-20-43]]

^<<v7-20-43,43>>^ Cercaram os benjamitas e os perseguiram, pisando-os desde Noá até a altura de Gibeá para o nascente do sol.

[[v7-20-44]]

^<<v7-20-44,44>>^ Assim caíram de Benjamim dezoito mil homens, sendo todos estes homens valorosos.

[[v7-20-45]]

^<<v7-20-45,45>>^ Então os restantes, virando as costas fugiram para deserto, até a penha de Rimom; mas os filhos de Israel colheram deles pelos caminhos ainda cinco mil homens; e, seguindo-os de perto até Gidom, mataram deles mais dois mil.

[[v7-20-46]]

^<<v7-20-46,46>>^ E, todos, os de Benjamim que caíram naquele dia oram vinte e cinco mil homens que arrancavam da espada, todos eles homens valorosos.

[[v7-20-47]]

^<<v7-20-47,47>>^ Mas seiscentos homens viraram as costas e, fugindo para o deserto, para a penha de Rimom, ficaram ali quatro meses.

[[v7-20-48]]

^<<v7-20-48,48>>^ E os homens de Israel voltaram para os filhos de Benjamim, e os passaram ao fio da espada, tanto os homens da cidade como os animais, tudo quanto encontraram; e a todas as cidades que acharam puseram fogo.

'''

xref:007-juizes/007-juizes-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-juizes/007-juizes-021.adoc#v7-21-0[Próximo Capítulo &#62;]