include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-19-1]]

^<<v7-19-1,1>>^ Aconteceu também naqueles dias, quando não havia rei em Israel, que certo levita, habitante das partes remotas da região montanhosa de Efraim, tomou para si uma concubina, de Belém de Judá.

[[v7-19-2]]

^<<v7-19-2,2>>^ Ora, a sua concubina adulterou contra ele e, deixando-o, foi para casa de seu pai em Belém de Judá, e ali ficou uns quatro meses.

[[v7-19-3]]

^<<v7-19-3,3>>^ Seu marido, levantando-se, foi atrás dela para lhe falar bondosamente, a fim de tornar a trazê-la; e levava consigo o seu moço e um par de jumentos. Ela o levou à casa de seu pai, o qual, vendo-o, saiu alegremente a encontrar-se com ele.

[[v7-19-4]]

^<<v7-19-4,4>>^ E seu sogro, o pai da moça, o deteve consigo três dias; assim comeram e beberam, e se alojaram ali.

[[v7-19-5]]

^<<v7-19-5,5>>^ Ao quarto dia madrugaram, e ele se levantou para partir. Então o pai da moça disse a seu genro: Fortalece-te com um bocado de pão, e depois partireis:

[[v7-19-6]]

^<<v7-19-6,6>>^ Sentando-se, pois, ambos juntos, comeram e beberam; e disse o pai da moça ao homem: Peço-te que fiques ainda esta noite aqui, e alegre-se o teu coração.

[[v7-19-7]]

^<<v7-19-7,7>>^ O homem, porém, levantou-se para partir; mas, como seu sogro insistisse, tornou a passar a noite ali.

[[v7-19-8]]

^<<v7-19-8,8>>^ Também ao quinto dia madrugaram para partir; e disse o pai da moça: Ora, conforta o teu coração, e detém-te até o declinar do dia. E ambos juntos comeram.

[[v7-19-9]]

^<<v7-19-9,9>>^ Então o homem se levantou para partir, ele, a sua concubina, e o seu moço; e disse-lhe seu sogro, o pai da moça: Eis que já o dia declina para a tarde; peço-te que aqui passes a noite. O dia já vai acabando; passa aqui a noite, e alegre-se o teu coração: Amanhã de madrugada levanta-te para encetares viagem, e irás para a tua tenda.

[[v7-19-10]]

^<<v7-19-10,10>>^ Entretanto, o homem não quis passar a noite ali, mas, levantando-se, partiu e chegou à altura de Jebus &#123;que é Jerusalém&#125;, e com ele o par de jumentos albardados, como também a sua concubina.

[[v7-19-11]]

^<<v7-19-11,11>>^ Quando estavam perto de Jebus, já o dia tinha declinado muito; e disse o moço a seu senhor: Vem, peço-te, retiremo-nos a esta cidade dos jebuseus, e passemos nela a noite.

[[v7-19-12]]

^<<v7-19-12,12>>^ Respondeu-lhe, porém, o seu senhor: Não nos retiraremos a nenhuma cidade estrangeira, que não seja dos filhos de Israel, mas passaremos até Gibeá.

[[v7-19-13]]

^<<v7-19-13,13>>^ Disse mais a seu moço: Vem, cheguemos a um destes lugares, Gibeá ou Ramá, e passemos ali a noite.

[[v7-19-14]]

^<<v7-19-14,14>>^ Passaram, pois, continuando o seu caminho; e o sol se pôs quando estavam perto de Gibeá, que pertence a Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ Pelo que se dirigiram para lá, a fim de passarem ali a noite; e o levita, entrando, sentou-se na praça da cidade, porque não houve quem os recolhesse em casa para ali passarem a noite.

[[v7-19-16]]

^<<v7-19-16,16>>^ Eis que ao anoitecer vinha do seu trabalho no campo um ancião; era ele da região montanhosa de Efraim, mas habitava em Gibeá; os homens deste lugar, porém, eram benjamitas.

[[v7-19-17]]

^<<v7-19-17,17>>^ Levantando ele os olhos, viu na praça da cidade o viajante, e perguntou-lhe: Para onde vais, e donde vens?

[[v7-19-18]]

^<<v7-19-18,18>>^ Respondeu-lhe ele: Estamos de viagem de Belém de Judá para as partes remotas da região montanhosa de Efraim, donde sou. Fui a Belém de Judá, porém agora vou à casa do Senhor; e ninguém há que me recolha em casa.

[[v7-19-19]]

^<<v7-19-19,19>>^ Todavia temos palha e forragem para os nossos jumentos; também há pão e vinho para mim, para a tua serva, e para o moço que vem com os teus servos; de coisa nenhuma há falta.

[[v7-19-20]]

^<<v7-19-20,20>>^ Disse-lhe o ancião: Paz seja contigo; tudo quanto te faltar fique ao meu cargo; tão-somente não passes a noite na praça.

[[v7-19-21]]

^<<v7-19-21,21>>^ Assim o fez entrar em sua casa, e deu ração aos jumentos; e, depois de lavarem os pés, comeram e beberam.

[[v7-19-22]]

^<<v7-19-22,22>>^ Enquanto eles alegravam o seu coração, eis que os homens daquela cidade, filhos de Belial, cercaram a casa, bateram à porta, e disseram ao ancião, dono da casa: Traze cá para fora o homem que entrou em tua casa, para que o conheçamos.

[[v7-19-23]]

^<<v7-19-23,23>>^ O dono da casa saiu a ter com eles, e disse-lhes: Não, irmãos meus, não façais semelhante mal; já que este homem entrou em minha casa, não façais essa loucura.

[[v7-19-24]]

^<<v7-19-24,24>>^ Aqui estão a minha filha virgem e a concubina do homem; fá-las-ei sair; humilhai-as a elas, e fazei delas o que parecer bem aos vossos olhos; porém a este homem não façais tal loucura.

[[v7-19-25]]

^<<v7-19-25,25>>^ Mas esses homens não o quiseram ouvir; então aquele homem pegou da sua concubina, e lha tirou para fora. Eles a conheceram e abusaram dela a noite toda até pela manhã; e ao subir da alva deixaram-na:

[[v7-19-26]]

^<<v7-19-26,26>>^ Ao romper do dia veio a mulher e caiu à porta da casa do homem, onde estava seu senhor, e ficou ali até que se fez claro.

[[v7-19-27]]

^<<v7-19-27,27>>^ Levantando-se pela manhã seu senhor, abriu as portas da casa, e ia sair para seguir o seu caminho; e eis que a mulher, sua concubina, jazia à porta da casa, com as mãos sobre o limiar.

[[v7-19-28]]

^<<v7-19-28,28>>^ Ele lhe disse: Levanta-te, e vamo-nos; porém ela não respondeu. Então a pôs sobre o jumento e, partindo dali, foi para o seu lugar.

[[v7-19-29]]

^<<v7-19-29,29>>^ Quando chegou em casa, tomou um cutelo e, pegando na sua concubina, a dividiu, membro por membro, em doze pedaços, que ele enviou por todo o território de Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ E sucedeu que cada um que via aquilo dizia: Nunca tal coisa se fez, nem se viu, desde o dia em que os filhos de Israel subiram da terra do Egito até o dia de hoje; ponderai isto, consultai, e dai o vosso parecer.

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]