include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-2-1]]

^<<v7-2-1,1>>^ O anjo do Senhor subiu de Gilgal a Boquim, e disse: Do Egito vos fiz subir, e vos trouxe para a terra que, com juramento, prometi a vossos pais, e vos disse: Nunca violarei e meu pacto convosco;

[[v7-2-2]]

^<<v7-2-2,2>>^ e, quanto a vós, não fareis pacto com os habitantes desta terra, antes derrubareis os seus altares. Mas vós não obedecestes à minha voz. Por que fizestes isso?

[[v7-2-3]]

^<<v7-2-3,3>>^ Pelo que também eu disse: Não os expulsarei de diante de vós; antes estarão quais espinhos nas vossas ilhargas, e os seus deuses vos serão por laço.

[[v7-2-4]]

^<<v7-2-4,4>>^ Tendo o anjo do Senhor falado estas palavras a todos os filhos de Israel, o povo levantou a sua voz e chorou.

[[v7-2-5]]

^<<v7-2-5,5>>^ Pelo que chamaram àquele lugar Boquim; e ali sacrificaram ao Senhor.

[[v7-2-6]]

^<<v7-2-6,6>>^ Havendo Josué despedido o povo, foram-se os filhos de Israel, cada um para a sua herança, a fim de possuírem a terra.

[[v7-2-7]]

^<<v7-2-7,7>>^ O povo serviu ao Senhor todos os dias de Josué, e todos os dias dos anciãos que sobreviveram a Josué e que tinham visto toda aquela grande obra do Senhor, a qual ele fizera a favor de Israel.

[[v7-2-8]]

^<<v7-2-8,8>>^ Morreu, porém, Josué, filho de Num, servo do Senhor, com a idade de cento e dez anos;

[[v7-2-9]]

^<<v7-2-9,9>>^ e o sepultaram no território da sua herança, em Timnate-Heres, na região montanhosa de Efraim, para o norte do monte Gaás.

[[v7-2-10]]

^<<v7-2-10,10>>^ () foi também congregada toda aquela geração a seus pais, e após ela levantou-se outra geração que não conhecia ao Senhor, nem tampouco a obra que ele fizera a Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ Então os filhos de Israel fizeram o que era mau aos olhos do Senhor, servindo aos baalins;

[[v7-2-12]]

^<<v7-2-12,12>>^ abandonaram o Senhor Deus de seus pais, que os tirara da terra do Egito, e foram-se após outros deuses, dentre os deuses dos povos que havia ao redor deles, e os adoraram; e provocaram o Senhor à ira,

[[v7-2-13]]

^<<v7-2-13,13>>^ abandonando-o, e servindo a baalins e astarotes.

[[v7-2-14]]

^<<v7-2-14,14>>^ Pelo que a ira do Senhor se acendeu contra Israel, e ele os entregou na mão dos espoliadores, que os despojaram; e os vendeu na mão dos seus inimigos ao redor, de modo que não puderam mais resistir diante deles.

[[v7-2-15]]

^<<v7-2-15,15>>^ Por onde quer que saíam, a mão do Senhor era contra eles para o mal, como o Senhor tinha dito, e como lho tinha jurado; e estavam em grande aflição.

[[v7-2-16]]

^<<v7-2-16,16>>^ Mas o Senhor suscitou juízes, que os livraram da mão dos que os espojavam.

[[v7-2-17]]

^<<v7-2-17,17>>^ Contudo, não deram ouvidos nem aos seus juízes, pois se prostituíram após outros deuses, e os adoraram; depressa se desviaram do caminho, por onde andaram seus pais em obediência aos mandamentos do Senhor; não fizeram como eles.

[[v7-2-18]]

^<<v7-2-18,18>>^ Quando o Senhor lhes suscitava juízes, ele era com o juiz, e os livrava da mão dos seus inimigos todos os dias daquele juiz; porquanto o Senhor se compadecia deles em razão do seu gemido por causa dos que os oprimiam e afligiam.

[[v7-2-19]]

^<<v7-2-19,19>>^ Mas depois da morte do juiz, reincidiam e se corrompiam mais do que seus pais, andando após outros deuses, servindo-os e adorando-os; não abandonavam nenhuma das suas práticas, nem a sua obstinação.

[[v7-2-20]]

^<<v7-2-20,20>>^ Pelo que se acendeu contra Israel a ira do Senhor, e ele disse: Porquanto esta nação violou o meu pacto, que estabeleci com seus pais, não dando ouvidos à minha voz,

[[v7-2-21]]

^<<v7-2-21,21>>^ eu não expulsarei mais de diante deles nenhuma das nações que Josué deixou quando morreu;

[[v7-2-22]]

^<<v7-2-22,22>>^ a fim de que, por elas, ponha a prova Israel, se há de guardar, ou não, o caminho do Senhor, como seus pais o guardaram, para nele andar.

[[v7-2-23]]

^<<v7-2-23,23>>^ Assim o Senhor deixou ficar aquelas nações, e não as desterrou logo, nem as entregou na mão de Josué.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]