include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-6-1]]

^<<v7-6-1,1>>^ Mas os filhos de Israel fizeram o que era mau aos olhos do Senhor, e o Senhor os entregou na mão de Midiã por sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ Prevalecia, pois, a mão de Midiã sobre Israel e, por causa de Midiã, fizeram os filhos de Israel para si as covas que estão nos montes, as cavernas e as fortalezas.

[[v7-6-3]]

^<<v7-6-3,3>>^ Porque sucedia que, havendo Israel semeado, subiam contra ele os midianitas, os amalequitas e os filhos do oriente;

[[v7-6-4]]

^<<v7-6-4,4>>^ e, acampando-se contra ele, destruíam o produto da terra até chegarem a Gaza, e não deixavam mantimento em Israel, nem ovelhas, nem bois, nem jumentos.

[[v7-6-5]]

^<<v7-6-5,5>>^ Porque subiam com os seus rebanhos e tendas; vinham em multidão, como gafanhotos; tanto eles como os seus camelos eram inumeráveis; e entravam na terra, para a destruir.

[[v7-6-6]]

^<<v7-6-6,6>>^ Assim Israel se enfraqueceu muito por causa dos midianitas; então os filhos de Israel clamaram ao Senhor.

[[v7-6-7]]

^<<v7-6-7,7>>^ E sucedeu que, clamando eles ao Senhor por causa dos midianitas,

[[v7-6-8]]

^<<v7-6-8,8>>^ enviou-lhes o Senhor um profeta, que lhes disse: Assim diz o Senhor, Deus de Israel: Do Egito eu vos fiz subir, e vos tirei da casa da servidão;

[[v7-6-9]]

^<<v7-6-9,9>>^ livrei-vos da mão dos egípcios, e da mão de todos quantos vos oprimiam, e os expulsei de diante de vós, e a vós vos dei a sua terra.

[[v7-6-10]]

^<<v7-6-10,10>>^ Também eu vos disse: Eu sou o Senhor vosso Deus; não temais aos deuses dos amorreus, em cuja terra habitais. Mas não destes ouvidos à minha voz.

[[v7-6-11]]

^<<v7-6-11,11>>^ Então o anjo do Senhor veio, e sentou-se debaixo do carvalho que estava em Ofra e que pertencia a Joás, abiezrita, cujo filho Gideão estava malhando o trigo no lagar para o esconder dos midianitas.

[[v7-6-12]]

^<<v7-6-12,12>>^ Apareceu-lhe então o anjo do Senhor e lhe disse: O Senhor é contigo, ó homem valoroso.

[[v7-6-13]]

^<<v7-6-13,13>>^ Gideão lhe respondeu: Ai, senhor meu, se o Senhor é conosco, por que tudo nos sobreveio? e onde estão todas as suas maravilhas que nossos pais nos contaram, dizendo: Não nos fez o Senhor subir do Egito? Agora, porém, o Senhor nos desamparou, e nos entregou na mão de Midiã.

[[v7-6-14]]

^<<v7-6-14,14>>^ Virou-se o Senhor para ele e lhe disse: Vai nesta tua força, e livra a Israel da mão de Midiã; porventura não te envio eu?

[[v7-6-15]]

^<<v7-6-15,15>>^ Replicou-lhe Gideão: Ai, senhor meu, com que livrarei a Israel? eis que a minha família é a mais pobre em Manassés, e eu o menor na casa de meu pai.

[[v7-6-16]]

^<<v7-6-16,16>>^ Tornou-lhe o Senhor: Porquanto eu hei de ser contigo, tu ferirás aos midianitas como a um só homem.

[[v7-6-17]]

^<<v7-6-17,17>>^ Prosseguiu Gideão: Se agora tenho achado graça aos teus olhos, dá-me um sinal de que és tu que falas comigo.

[[v7-6-18]]

^<<v7-6-18,18>>^ Rogo-te que não te apartes daqui até que eu volte trazendo do meu presente e o ponha diante de ti. Respondeu ele: Esperarei até que voltes.

[[v7-6-19]]

^<<v7-6-19,19>>^ Entrou, pois, Gideão, preparou um cabrito e fez, com uma e efa de farinha, bolos ázimos; pôs a carne num cesto e o caldo numa panela e, trazendo para debaixo do carvalho, lho apresentou.

[[v7-6-20]]

^<<v7-6-20,20>>^ Mas o anjo de Deus lhe disse: Toma a carne e os bolos ázimos, e põe-nos sobre esta rocha e derrama-lhes por cima o caldo. E ele assim fez.

[[v7-6-21]]

^<<v7-6-21,21>>^ E o anjo do Senhor estendeu a ponta do cajado que tinha na mão, e tocou a carne e os bolos ázimos; então subiu fogo da rocha, e consumiu a carne e os bolos ázimos; e o anjo do Senhor desapareceu-lhe da vista.

[[v7-6-22]]

^<<v7-6-22,22>>^ Vendo Gideão que era o anjo do Senhor, disse: Ai de mim, Senhor Deus! pois eu vi o anjo do Senhor face a face.

[[v7-6-23]]

^<<v7-6-23,23>>^ Porém o Senhor lhe disse: Paz seja contigo, não temas; não morrerás.

[[v7-6-24]]

^<<v7-6-24,24>>^ Então Gideão edificou ali um altar ao Senhor, e lhe chamou Jeová-Salom; e ainda até o dia de hoje está o altar em Ofra dos abiezritas.

[[v7-6-25]]

^<<v7-6-25,25>>^ Naquela mesma noite, disse o Senhor a Gidão: Toma um dos bois de teu pai, a saber, o segundo boi de sete anos, e derriba o altar de Baal, que é de teu pai, e corta a asera que está ao pé dele.

[[v7-6-26]]

^<<v7-6-26,26>>^ Edifica ao Senhor teu Deus um altar no cume deste lugar forte, na forma devida; toma o segundo boi, e o oferece em holocausto, com a lenha da asera que cortares

[[v7-6-27]]

^<<v7-6-27,27>>^ Então Gideão tomou dez homens dentre os seus servos, e fez como o Senhor lhe dissera; porém, temendo ele a casa de seu pai e os homens daquela cidade, não o fez de dia, mas de noite.

[[v7-6-28]]

^<<v7-6-28,28>>^ Levantando-se, pois, os homens daquela cidade, de madrugada, eis que estava o altar de Baal derribado, cortada a asera que estivera ao pé dele, e o segundo boi oferecido no altar que fora edificado.

[[v7-6-29]]

^<<v7-6-29,29>>^ Pelo que disseram uns aos outros: Quem fez isto? E, depois de investigarem e inquirirem, disseram: Gideão, filho de Joás, é quem fez isto.

[[v7-6-30]]

^<<v7-6-30,30>>^ Então os homens daquela cidade disseram a Joás: Tira para fora teu filho, para que morra, porque derribou o altar de Baal e cortou a asera que estava ao pé dele.

[[v7-6-31]]

^<<v7-6-31,31>>^ Joás, porém, disse a todos os que se puseram contra ele: Contendereis vós por Baal? livrá-lo-eis vós? Qualquer que por ele contender, ainda esta manhã será morto; se ele é deus, por si mesmo contenda, pois foi derribado o seu altar.

[[v7-6-32]]

^<<v7-6-32,32>>^ Pelo que naquele dia chamaram a Gidão Jerubaal, dizendo: Baal contenda contra ele, pois derribou o seu altar.

[[v7-6-33]]

^<<v7-6-33,33>>^ Então todos os midianitas, os amalequitas e os filhos do oriente se ajuntaram e, passando o Jordão, acamparam no vale de Jizreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ Mas o Espírito do Senhor apoderou-se de Gideão; e tocando ele a trombeta, os abiezritas se ajuntaram após ele.

[[v7-6-35]]

^<<v7-6-35,35>>^ E enviou mensageiros por toda a tribo de Manassés, que também se ajuntou após ele; e ainda enviou mensageiros a Aser, a Zebulom e a Naftali, que lhe saíram ao encontro.

[[v7-6-36]]

^<<v7-6-36,36>>^ Disse Gideão a Deus: Se hás de livrar a Israel por minha mão, como disseste,

[[v7-6-37]]

^<<v7-6-37,37>>^ eis que eu porei um velo de lã na eira; se o orvalho estiver somente no velo, e toda a terra ficar enxuta, então conhecerei que hás de livrar a Israel por minha mão, como disseste.

[[v7-6-38]]

^<<v7-6-38,38>>^ E assim foi; pois, levantando-se de madrugada no dia seguinte, apertou o velo, e espremeu dele o orvalho, que encheu uma taça.

[[v7-6-39]]

^<<v7-6-39,39>>^ Disse mais Gideão a Deus: Não se acenda contra mim a tua ira se ainda falar só esta vez. Permite que só mais esta vez eu faça prova com o velo; rogo-te que só o velo fique enxuto, e em toda a terra haja orvalho.

[[v7-6-40]]

^<<v7-6-40,40>>^ E Deus assim fez naquela noite; pois só o velo estava enxuto, e sobre toda a terra havia orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]