include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-9-1]]

^<<v7-9-1,1>>^ Abimeleque, filho de Jerubaal, foi a Siquém, aos irmãos de sua mãe, e falou-lhes, e a toda a parentela da casa de pai de sua mãe, dizendo:

[[v7-9-2]]

^<<v7-9-2,2>>^ Falai, peço-vos, aos ouvidos de todos os cidadãos de Siquém: Que é melhor para vós? que setenta homens, todos os filhos de Jerubaal, dominem sobre vós, ou que um só domine sobre vós? Lembrai-vos também de que sou vosso osso e vossa carne.

[[v7-9-3]]

^<<v7-9-3,3>>^ Então os irmãos de sua mãe falaram todas essas palavras a respeito dele aos ouvidos de todos os cidadãos de Siquém; e o coração deles se inclinou a seguir Abimeleque; pois disseram: E nosso irmão.

[[v7-9-4]]

^<<v7-9-4,4>>^ E deram-lhe setenta siclos de prata, da casa de Baal-Berite, com os quais alugou Abimeleque alguns homens ociosos e levianas, que o seguiram;

[[v7-9-5]]

^<<v7-9-5,5>>^ e foi à casa de seu pai, a Ofra, e matou a seus irmãos, os filhos de Jerubaal, setenta homens, sobre uma só pedra. Mas Jotão, filho menor de Jerubaal, ficou, porquanto se tinha escondido.

[[v7-9-6]]

^<<v7-9-6,6>>^ Então se ajuntaram todos os cidadãos de Siquém e toda a Bete-Milo, e foram, e constituíram rei a Abimeleque, junto ao carvalho da coluna que havia em Siquém.

[[v7-9-7]]

^<<v7-9-7,7>>^ Jotão, tendo sido avisado disso, foi e, pondo-se no cume do monte Gerizim, levantou a voz e clamou, dizendo: Ouvi-me a mim, cidadãos de Siquém, para que Deus: vos ouça a vos.

[[v7-9-8]]

^<<v7-9-8,8>>^ Foram uma vez as árvores a ungir para si um rei; e disseram à oliveira: Reina tu sobre nós.

[[v7-9-9]]

^<<v7-9-9,9>>^ Mas a oliveira lhes respondeu: Deixaria eu a minha gordura, que Deus e os homens em mim prezam, para ir balouçar sobre as árvores?

[[v7-9-10]]

^<<v7-9-10,10>>^ Então disseram as árvores à figueira: Vem tu, e reina sobre nós.

[[v7-9-11]]

^<<v7-9-11,11>>^ Mas a figueira lhes respondeu: Deixaria eu a minha doçura, o meu bom fruto, para ir balouçar sobre as árvores?

[[v7-9-12]]

^<<v7-9-12,12>>^ Disseram então as árvores à videira: Vem tu, e reina sobre nós.

[[v7-9-13]]

^<<v7-9-13,13>>^ Mas a videira lhes respondeu: Deixaria eu o meu mosto, que alegra a Deus e aos homens, para ir balouçar sobre as árvores?

[[v7-9-14]]

^<<v7-9-14,14>>^ Então todas as árvores disseram ao espinheiro: Vem tu, e reina sobre nós.

[[v7-9-15]]

^<<v7-9-15,15>>^ O espinheiro, porém, respondeu às árvores: Se de boa fé me ungis por vosso rei, vinde refugiar-vos debaixo da minha sombra; mas, se não, saia fogo do espinheiro, e devore os cedros do Líbano.

[[v7-9-16]]

^<<v7-9-16,16>>^ Agora, pois, se de boa fé e com retidão procedestes, constituindo rei a Abimeleque, e se bem fizestes para com Jerubaal e para com a sua casa, e se com ele usastes conforme o merecimento das suas mãos

[[v7-9-17]]

^<<v7-9-17,17>>^ &#123;porque meu pai pelejou por vós, desprezando a própria vida, e vos livrou da mão de Midiã;

[[v7-9-18]]

^<<v7-9-18,18>>^ porém vós hoje vos levantastes contra a casa de meu pai, e matastes a seus filhos, setenta homens, sobre uma só pedra; e a Abimeleque, filho da sua serva, fizestes reinar sobre os cidadãos de Siquém, porque é vosso irmão&#125;;

[[v7-9-19]]

^<<v7-9-19,19>>^ se de boa fé e com retidão procedestes hoje para com Jerubaal e para com a sua casa, alegrai-vos em Abimeleque, e também ele se alegre em vós;

[[v7-9-20]]

^<<v7-9-20,20>>^ mas se não, saia fogo de Abimeleque, e devore os cidadãos de Siquém, e a Bete-Milo; e saia fogo dos cidadãos de Siquém e de Bete-Milo, e devore Abimeleque.

[[v7-9-21]]

^<<v7-9-21,21>>^ E partindo Jotão, fugiu e foi para Beer, e ali habitou, por medo de Abimeleque, seu irmão.

[[v7-9-22]]

^<<v7-9-22,22>>^ Havendo Abimeleque reinado três anos sobre Israel,

[[v7-9-23]]

^<<v7-9-23,23>>^ Deus suscitou um espírito mau entre Abimeleque e os cidadãos de Siquém; e estes procederam aleivosamente para com Abimeleque;

[[v7-9-24]]

^<<v7-9-24,24>>^ para que a violência praticada contra os setenta filhos de Jerubaal, como também o sangue deles, recaíssem sobre Abimeleque, seu irmão, que os matara, e sobre os cidadãos de Siquém, que fortaleceram as mãos dele para matar a seus irmãos.

[[v7-9-25]]

^<<v7-9-25,25>>^ E os cidadãos de Siquém puseram de emboscada contra ele, sobre os cumes dos montes, homens que roubavam a todo aquele que passava por eles no caminho. E contou-se isto a Abimeleque.

[[v7-9-26]]

^<<v7-9-26,26>>^ Também veio Gaal, filho de Ebede, com seus irmãos, e estabeleceu-se em Siquém; e confiaram nele os cidadãos de Siquém.

[[v7-9-27]]

^<<v7-9-27,27>>^ Saindo ao campo, vindimaram as suas vinhas, pisaram as uvas e fizeram uma festa; e, entrando na casa de seu deus, comeram e beberam, e amaldiçoaram a Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ E disse Gaal, filho de Ebede: Quem é Abimeleque, e quem é Siquém, para que sirvamos a Abimeleque? não é, porventura, filho de Jerubaal? e não é Zebul o seu mordomo? Servi antes aos homens de Hamor, pai de Siquém; pois, por que razão serviríamos nós a Abimeleque?

[[v7-9-29]]

^<<v7-9-29,29>>^ Ah! se este povo estivesse sob a minha mão, eu transtornaria a Abimeleque. Eu lhe diria: Multiplica o teu exército, e vem.

[[v7-9-30]]

^<<v7-9-30,30>>^ Quando Zebul, o governador da cidade, ouviu as palavras de Gaal, filho de Ebede, acendeu-se em ira.

[[v7-9-31]]

^<<v7-9-31,31>>^ E enviou secretamente mensageiros a Abimeleque, para lhe dizerem: Eis que Gaal, filho de Ebede, e seus irmãos vieram a Siquém, e estão sublevando a cidade contra ti.

[[v7-9-32]]

^<<v7-9-32,32>>^ Levanta-te, pois, de noite, tu e o povo que tiveres contigo, e põe-te de emboscada no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ E pela manhã, ao nascer do sol, levanta-te, e dá de golpe sobre a cidade; e, saindo contra ti Gaal e o povo que tiver com ele, faze-lhe como te permitirem as circunstâncias.

[[v7-9-34]]

^<<v7-9-34,34>>^ Levantou-se, pois, de noite Abimeleque, e todo o povo que com ele havia, e puseram emboscadas a Siquém, em quatro bandos.

[[v7-9-35]]

^<<v7-9-35,35>>^ E Gaal, filho de Ebede, saiu e pôs-se à entrada da porta da cidade; e das emboscadas se levantou Abimeleque, e todo o povo que estava com ele.

[[v7-9-36]]

^<<v7-9-36,36>>^ Quando Gaal viu aquele povo, disse a Zebul: Eis que desce gente dos cumes dos montes. Respondeu-lhe Zebul: Tu vês as sombras dos montes como se fossem homens.

[[v7-9-37]]

^<<v7-9-37,37>>^ Gaal, porém, tornou a falar, e disse: Eis que desce gente do meio da terra; também vem uma tropa do caminho do carvalho de Meonenim.

[[v7-9-38]]

^<<v7-9-38,38>>^ Então lhe disse Zebul: Onde está agora a tua boca, com a qual dizias: Quem é Abimeleque, para que o sirvamos? Não é esse, porventura, o povo que desprezaste. Sai agora e peleja contra ele!

[[v7-9-39]]

^<<v7-9-39,39>>^ Assim saiu Gaal, à frente dos cidadãos de Siquém, e pelejou contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ Mas Abimeleque o perseguiu, pois Gaal fugiu diante dele, e muitos caíram feridos até a entrada da porta.

[[v7-9-41]]

^<<v7-9-41,41>>^ Abimeleque ficou em Arumá. E Zebul expulsou Gaal e seus irmãos, para que não habitassem em Siquém.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte sucedeu que o povo saiu ao campo; disto foi avisado Abimeleque,

[[v7-9-43]]

^<<v7-9-43,43>>^ o qual, tomando o seu povo, dividiu-o em três bandos, que pôs de emboscada no campo. Quando viu que o povo saía da cidade, levantou-se contra ele e o feriu.

[[v7-9-44]]

^<<v7-9-44,44>>^ Abimeleque e os que estavam com ele correram e se puseram à porta da cidade; e os outros dois bandos deram de improviso sobre todos quantos estavam no campo, e os feriram.

[[v7-9-45]]

^<<v7-9-45,45>>^ Abimeleque pelejou contra a cidade todo aquele dia, tomou-a e matou o povo que nela se achava; e, assolando-a, a semeou de sal.

[[v7-9-46]]

^<<v7-9-46,46>>^ Tendo ouvido isso todos os cidadãos de Migdol-Siquém, entraram na fortaleza, na casa de El-Berite.

[[v7-9-47]]

^<<v7-9-47,47>>^ E contou-se a Abimeleque que todos os cidadãos de Migdol-Siquém se haviam congregado.

[[v7-9-48]]

^<<v7-9-48,48>>^ Então Abimeleque subiu ao monte Zalmom, ele e todo o povo que com ele havia; e, tomando na mão um machado, cortou um ramo de árvore e, levantando-o, pô-lo ao seu ombro, e disse ao povo que estava com ele: O que me vistes fazer, apressai-vos a fazê-lo também.

[[v7-9-49]]

^<<v7-9-49,49>>^ Tendo, pois, cada um cortado o seu ramo, seguiram a Abimeleque; e, pondo os ramos junto da fortaleza, queimaram-na a fogo com os que nela estavam; de modo que morreram também todos os de Migdol-Siquém, cerca de mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Então Abimeleque foi a Tebez, e a sitiou e tomou.

[[v7-9-51]]

^<<v7-9-51,51>>^ Havia, porém, no meio da cidade uma torre forte, na qual se refugiaram todos os habitantes da cidade, homens e mulheres; e fechando após si as portas, subiram ao eirado da torre.

[[v7-9-52]]

^<<v7-9-52,52>>^ E Abimeleque, tendo chegado até a torre, atacou-a, e chegou-se à porta da torre, para lhe meter fogo.

[[v7-9-53]]

^<<v7-9-53,53>>^ Nisso uma mulher lançou a pedra superior de um moinho sobre a cabeça de Abimeleque, e quebrou-lhe o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Então ele chamou depressa o moço, seu escudeiro, e disse-lhe: Desembainha a tua espada e mata-me, para que não se diga de mim: uma mulher o matou. E o moço o traspassou e ele morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Vendo, pois, os homens de Israel que Abimeleque já era morto, foram-se cada um para o seu lugar.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim Deus fez tornar sobre Abimeleque o mal que tinha feito a seu pai, matando seus setenta irmãos;

[[v7-9-57]]

^<<v7-9-57,57>>^ como também fez tornar sobre a cabeça dos homens de Siquém todo o mal que fizeram; e veio sobre eles a maldição de Jotão, filho de Jerubaal.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]