include::./index.adoc[]

[[v7-8-0]]
=== Juízes, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-8-1]]

^<<v7-8-1,1>>^ Então os homens de Efraim lhe disseram: Que é isto que nos fizeste, não nos chamando quando foste pelejar contra Midiã? E repreenderam-no asperamente.

[[v7-8-2]]

^<<v7-8-2,2>>^ Ele, porém, lhes respondeu: Que fiz eu agora em comparação ao que vós fizestes? Não são porventura os rabiscos de Efraim melhores do que a vindima de Abiezer?

[[v7-8-3]]

^<<v7-8-3,3>>^ Deus entregou na vossa mão os príncipes de Midiã, Orebe e Zeebe; que, pois, pude eu fazer em comparação ao que vós fizestes? Então a sua ira se abrandou para com ele, quando falou esta palavra.

[[v7-8-4]]

^<<v7-8-4,4>>^ E Gideão veio ao Jordão e o atravessou, ele e os trezentos homens que estavam com ele, fatigados, mas ainda perseguindo.

[[v7-8-5]]

^<<v7-8-5,5>>^ Disse, pois, aos homens de Sucote: Dai, peço-vos, uns pães ao povo que me segue, porquanto está fatigado, e eu vou perseguindo a Zeba e Zalmuna, reis os midianitas.

[[v7-8-6]]

^<<v7-8-6,6>>^ Mas os príncipes de Sucote responderam: Já estão em teu poder as mãos de Zebá e Zalmuna, para que demos pão ao teu exército?

[[v7-8-7]]

^<<v7-8-7,7>>^ Replicou-lhes Gideão: Pois quando o Senhor entregar na minha mão a Zebá e a Zalmuna, trilharei a vossa carne com os espinhos do deserto e com os abrolhos.

[[v7-8-8]]

^<<v7-8-8,8>>^ Dali subiu a Penuel, e falou da mesma maneira aos homens desse lugar, que lhe responderam como os homens de Sucote lhe haviam respondido.

[[v7-8-9]]

^<<v7-8-9,9>>^ Por isso falou também aos homens de Penuel, dizendo: Quando eu voltar em paz, derribarei esta torre.

[[v7-8-10]]

^<<v7-8-10,10>>^ Zebá e Zalmuna estavam em Carcor com o seu exército, cerca de quinze mil homens, os restantes de todo o exército dos filhos do oriente; pois haviam caído cento e vinte mil homens que puxavam da espada.

[[v7-8-11]]

^<<v7-8-11,11>>^ subiu Gideão pelo caminho dos que habitavam em tendas, ao oriente de Nobá e Jogbeá, e feriu aquele exército, porquanto se dava por seguro.

[[v7-8-12]]

^<<v7-8-12,12>>^ E, fugindo Zebá e Zalmuna, Gideão os perseguiu, tomou presos esses dois reis dos midianitas e desbaratou todo o exército.

[[v7-8-13]]

^<<v7-8-13,13>>^ Voltando, pois, Gideão, filho de Joás, da peleja pela subida de Heres,

[[v7-8-14]]

^<<v7-8-14,14>>^ tomou preso a um moço dos homens de Sucote, e o inquiriu; este lhe deu por escrito os nomes dos príncipes de Sucote, e dos seus anciãos, setenta e sete homens.

[[v7-8-15]]

^<<v7-8-15,15>>^ Então veio aos homens de Sucote, e disse: Eis aqui Zebá e Zalmuna, a respeito dos quais me escarnecestes, dizendo: Porventura já estão em teu poder as mãos de Zebá e Zalmuna, para que demos pão aos teus homens fatigados?

[[v7-8-16]]

^<<v7-8-16,16>>^ Nisso tomou os anciãos da cidade, e espinhos e abrolhos do deserto, e com eles ensinou aos homens de Sucote.

[[v7-8-17]]

^<<v7-8-17,17>>^ Também derrubou a torre de Penuel, e matou os homens da cidade.

[[v7-8-18]]

^<<v7-8-18,18>>^ Depois perguntou a Zebá e a Zalmuna: Como eram os homens que matastes em Tabor? E responderam eles: Qual és tu, tais eram eles; cada um parecia filho de rei.

[[v7-8-19]]

^<<v7-8-19,19>>^ Então disse ele: Eram meus irmãos, filhos de minha mãe; vive o Senhor, que se lhes tivésseis poupado a vida, eu não vos mataria.

[[v7-8-20]]

^<<v7-8-20,20>>^ E disse a Jeter, seu primogênito: Levanta-te, mata-os. O mancebo, porém, não puxou da espada, porque temia, porquanto ainda era muito moço.

[[v7-8-21]]

^<<v7-8-21,21>>^ Então disseram Zebá e Zalmuna: Levanta-te tu mesmo, e acomete-nos; porque, qual o homem, tal a sua força. Levantando-se, pois, Gideão, matou Zebá e Zalmuna, e tomou os crescentes que estavam aos pescoços dos seus camelos.

[[v7-8-22]]

^<<v7-8-22,22>>^ Então os homens de Israel disseram a Gideão: Domina sobre nós, assim tu, como teu filho, e o filho de teu filho; porquanto nos livraste da mão de Midiã.

[[v7-8-23]]

^<<v7-8-23,23>>^ Gideão, porém, lhes respondeu: Nem eu dominarei sobre vós, nem meu filho, mas o Senhor sobre vós dominará.

[[v7-8-24]]

^<<v7-8-24,24>>^ Disse-lhes mais Gideão: uma petição vos farei: dá-me, cada um de vós, as arrecadas do despojo. &#123;Porque os inimigos tinham arrecadas de ouro, porquanto eram ismaelitas&#125; .

[[v7-8-25]]

^<<v7-8-25,25>>^ Ao que disseram eles: De boa vontade as daremos. E estenderam uma capa, na qual cada um deles deitou as arrecadas do seu despojo.

[[v7-8-26]]

^<<v7-8-26,26>>^ E foi o peso das arrecadas de ouro que ele pediu, mil e setecentos siclos de ouro, afora os crescentes, as cadeias e as vestes de púrpura que os reis de Midiã trajavam, afora as correntes que os camelos traziam ao pescoço.

[[v7-8-27]]

^<<v7-8-27,27>>^ Disso fez Gideão um éfode, e o pôs na sua cidade, em Ofra; e todo o Israel se prostituiu ali após ele; e foi um laço para Gideão e para sua casa.

[[v7-8-28]]

^<<v7-8-28,28>>^ Assim foram abatidos os midianitas diante dos filhos de Israel, e nunca mais levantaram a cabeça. E a terra teve sossego, por quarenta anos nos dias de Gideão.

[[v7-8-29]]

^<<v7-8-29,29>>^ Então foi Jerubaal, filho de Joás, e habitou em sua casa.

[[v7-8-30]]

^<<v7-8-30,30>>^ Gideão teve setenta filhos, que procederam da sua coxa, porque tinha muitas mulheres.

[[v7-8-31]]

^<<v7-8-31,31>>^ A sua concubina que estava em Siquém deu-lhe também um filho; e pôs-lhe por nome Abimeleque.

[[v7-8-32]]

^<<v7-8-32,32>>^ Morreu Gideão, filho de Joás, numa boa velhice, e foi sepultado no sepulcro de seu pai Joás, em Ofra dos abiezritas.

[[v7-8-33]]

^<<v7-8-33,33>>^ Depois da morte de Gideão os filhos de Israel tornaram a se prostituir após os baalins, e puseram a Baal-Berite por deus.

[[v7-8-34]]

^<<v7-8-34,34>>^ Assim os filhos de Israel não se lembraram do Senhor seu Deus, que os livrara da mão de todos os seus inimigos ao redor;

[[v7-8-35]]

^<<v7-8-35,35>>^ nem usaram de beneficência para com a casa de Jerubaal, a saber, de Gideão, segundo todo o bem que ele havia feito a Israel.

'''

xref:007-juizes/007-juizes-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-juizes/007-juizes-009.adoc#v7-9-0[Próximo Capítulo &#62;]