include::./index.adoc[]

[[v7-18-0]]
=== Juízes, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-18-1]]

^<<v7-18-1,1>>^ Naqueles dias não havia rei em Israel; a tribo dos danitas buscava para si herança em que habitar; porque até então não lhe havia caído a sua herança entre as tribos de Israel.

[[v7-18-2]]

^<<v7-18-2,2>>^ E de Zorá e Estaol os filhos de Dã enviaram cinco homens da sua tribo, escolhidos dentre todo o povo, homens valorosos, para espiar e reconhecer a terra; e lhes disseram: Ide, reconhecei a terra. E chegaram eles à região montanhosa de Efraim, à casa de Mica, e passaram ali a noite.

[[v7-18-3]]

^<<v7-18-3,3>>^ Pois, estando eles perto da casa de Mica, reconheceram a voz do mancebo levita; e, dirigindo-se para lá, lhe perguntaram: Quem te trouxe para cá? que estás fazendo aqui? e que é isto que tens aqui?

[[v7-18-4]]

^<<v7-18-4,4>>^ E ele lhes respondeu: Assim e assim me tem feito Mica; ele me assalariou, e eu lhe sirvo e sacerdote.

[[v7-18-5]]

^<<v7-18-5,5>>^ Então lhe disseram: Consulta a Deus, para que saibamos se será próspero o caminho que seguimos.

[[v7-18-6]]

^<<v7-18-6,6>>^ Ao que lhes disse o sacerdote: Ide em paz; perante o Senhor está o caminho que seguis.

[[v7-18-7]]

^<<v7-18-7,7>>^ Então foram-se aqueles cinco homens, e chegando a Laís, viram o povo que havia nela, como vivia em segurança, conforme o costume dos sidônios, quieto e desprecavido; não havia naquela terra falta de coisa alguma; era um povo rico e, estando longe dos sidônios, não tinha relações com ninguém.

[[v7-18-8]]

^<<v7-18-8,8>>^ Então voltaram a seus irmãos, em Zorá e Estaol, os quais lhes perguntaram: Que dizeis vós?

[[v7-18-9]]

^<<v7-18-9,9>>^ Eles responderam: Levantai-vos, e subamos contra eles; porque examinamos a terra, e eis que é muito boa. E vós estareis aqui tranqüilos? Não sejais preguiçosos em entrardes para tomar posse desta terra.

[[v7-18-10]]

^<<v7-18-10,10>>^ Quando lá chegardes, achareis um povo desprecavido, e a terra é muito espaçosa; pois Deus vos entregou na mão um lugar em que não há falta de coisa alguma que há na terra.

[[v7-18-11]]

^<<v7-18-11,11>>^ Então seiscentos homens da tribo dos danitas partiram de Zorá e Estaol, munidos de armas de guerra.

[[v7-18-12]]

^<<v7-18-12,12>>^ E, tendo subido, acamparam-se em Quiriate-Jearim, em Judá; pelo que esse lugar ficou sendo chamado Maané-Dã, até o dia de hoje; eis que está ao ocidente de Quiriate-Jearim.

[[v7-18-13]]

^<<v7-18-13,13>>^ Dali passaram à região montanhosa de Efraim, e chegaram à casa de Mica.

[[v7-18-14]]

^<<v7-18-14,14>>^ Então os cinco homens que tinham ido espiar a terra de Laís disseram a seus irmãos: Sabeis vós que naquelas casas há um éfode, e terafins, e uma imagem esculpida e uma de fundição? Considerai, pois, agora o que haveis de fazer.

[[v7-18-15]]

^<<v7-18-15,15>>^ Então se dirigiram para lá, e chegaram à casa do mancebo, o levita, à casa de Mica, e o saudaram.

[[v7-18-16]]

^<<v7-18-16,16>>^ E os seiscentos homens dos danitas, munidos de suas armas de guerra, ficaram à entrada da porta.

[[v7-18-17]]

^<<v7-18-17,17>>^ Mas subindo os cinco homens que haviam espiado a terra, entraram ali e tomaram a imagem esculpida, e éfode, os terafins e a imagem de fundição, ficando o sacerdote em pé à entrada da porta, com os seiscentos homens armados.

[[v7-18-18]]

^<<v7-18-18,18>>^ Quando eles entraram na casa de Mica, e tomaram a imagem esculpida, o éfode, os terafins e a imagem de fundição, perguntou-lhes o sacerdote: Que estais fazendo?

[[v7-18-19]]

^<<v7-18-19,19>>^ E eles lhe responderam: Cala-te, põe a mão sobre a boca, e vem conosco, e sê-nos por pai e sacerdote. Que te é melhor? ser sacerdote da casa dum só homem, ou duma tribo e duma geração em Israel?

[[v7-18-20]]

^<<v7-18-20,20>>^ Então alegrou-se o coração do sacerdote, o qual tomou o éfode, os terafins e a imagem esculpida, e entrou no meio do povo.

[[v7-18-21]]

^<<v7-18-21,21>>^ E, virando-se, partiram, tendo posto diante de si os pequeninos, o gado e a bagagem.

[[v7-18-22]]

^<<v7-18-22,22>>^ Estando eles já longe da casa de Mica, os homens que estavam nas casas vizinhas à dele se reuniram, e alcançaram os filhos de Dã.

[[v7-18-23]]

^<<v7-18-23,23>>^ E clamaram após os filhos de Dã, os quais, virando-se, perguntaram a Mica: Que é que tens, visto que vens com tanta gente?

[[v7-18-24]]

^<<v7-18-24,24>>^ Então ele respondeu: Os meus deuses que eu fiz, vós me tomastes, juntamente com o sacerdote, e partistes; e agora, que mais me fica? Como, pois, me dizeis: Que é que tens ?

[[v7-18-25]]

^<<v7-18-25,25>>^ Mas os filhos de Dã lhe disseram: Não faças ouvir a tua voz entre nós, para que porventura homens violentos não se lancem sobre vós, e tu percas a tua vida, e a vida dos da tua casa.

[[v7-18-26]]

^<<v7-18-26,26>>^ Assim seguiram o seu caminho os filhos de Dã; e Mica, vendo que eram mais fortes do que ele, virou-se e voltou para sua casa.

[[v7-18-27]]

^<<v7-18-27,27>>^ Eles, pois, levaram os objetos que Mica havia feito, e o sacerdote que estava com ele e, chegando a Laís, a um povo quieto e desprecavido, passaram-no ao fio da espada, e puseram fogo à cidade.

[[v7-18-28]]

^<<v7-18-28,28>>^ E ninguém houve que o livrasse, porquanto estava longe de Sidom, e não tinha relações com ninguém; a cidade estava no vale que está junto a Bete-Reobe. Depois, reedificando-a, habitaram nela,

[[v7-18-29]]

^<<v7-18-29,29>>^ e chamaram-lhe Dã, segundo o nome de Dã, seu pai, que nascera a Israel; era, porém, dantes o nome desta cidade Laís.

[[v7-18-30]]

^<<v7-18-30,30>>^ Depois os filhos de Dã levantaram para si aquela imagem esculpida; e Jônatas, filho de Gérsom, o filho de Moisés, ele e seus filhos foram sacerdotes da tribo dos danitas, até o dia do cativeiro da terra.

[[v7-18-31]]

^<<v7-18-31,31>>^ Assim, pois, estabeleceram para si a imagem esculpida que Mica fizera, por todo o tempo em que a casa de Deus esteve em Siló.

'''

xref:007-juizes/007-juizes-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-juizes/007-juizes-019.adoc#v7-19-0[Próximo Capítulo &#62;]