include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-11-1]]

^<<v7-11-1,1>>^ Era então Jefté, o gileadita, homem valoroso, porém filho duma prostituta; Gileade era o pai dele.

[[v7-11-2]]

^<<v7-11-2,2>>^ Também a mulher de Gileade lhe deu filhos; quando os filhos desta eram já grandes, expulsaram a Jefté, e lhe disseram: Não herdarás na casa de nosso pai, porque és filho de outra mulher.

[[v7-11-3]]

^<<v7-11-3,3>>^ Então Jefté fugiu de diante de seus irmãos, e habitou na terra de Tobe; e homens levianos juntaram-se a Jefté, e saiam com ele.

[[v7-11-4]]

^<<v7-11-4,4>>^ Passado algum tempo, os amonitas fizeram guerra a Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ E, estando eles a guerrear contra Israel, foram os anciãos de Gileade para trazer Jefté da terra de Tobe,

[[v7-11-6]]

^<<v7-11-6,6>>^ e lhe disseram: Vem, sê o nosso chefe, para que combatamos contra os amonitas.

[[v7-11-7]]

^<<v7-11-7,7>>^ Jefté, porém, perguntou aos anciãos de Gileade: Porventura não me odiastes, e não me expulsastes da casa de meu pai? por que, pois, agora viestes a mim, quando estais em aperto?

[[v7-11-8]]

^<<v7-11-8,8>>^ Responderam-lhe os anciãos de Gileade: É por isso que tornamos a ti agora, para que venhas conosco, e combatas contra os amonitas, e nos sejas por chefe sobre todos os habitantes de Gileade.

[[v7-11-9]]

^<<v7-11-9,9>>^ Então Jefté disse aos anciãos de Gileade: Se me fizerdes voltar para combater contra os amonitas, e o Senhor mos entregar diante de mim, então serei eu o vosso chefe.

[[v7-11-10]]

^<<v7-11-10,10>>^ Responderam os anciãos de Gileade a Jefté: O Senhor será testemunha entre nós de que faremos conforme a tua palavra.

[[v7-11-11]]

^<<v7-11-11,11>>^ Assim Jefté foi com os anciãos de Gileade, e o povo o pôs por cabeça e chefe sobre si; e Jefté falou todas as suas palavras perante o Senhor em Mizpá.

[[v7-11-12]]

^<<v7-11-12,12>>^ Depois Jefté enviou mensageiros ao rei dos amonitas, para lhe dizerem: Que há entre mim e ti, que vieste a mim para guerrear contra a minha terra?

[[v7-11-13]]

^<<v7-11-13,13>>^ Respondeu o rei dos amonitas aos mensageiros de Jefté: É porque Israel, quando subiu do Egito, tomou a minha terra, desde o Arnom até o Jaboque e o Jordão; restitui-me, pois, agora essas terras em paz.

[[v7-11-14]]

^<<v7-11-14,14>>^ Jefté, porém, tornou a enviar mensageiros ao rei dos amonitas,

[[v7-11-15]]

^<<v7-11-15,15>>^ dizendo-lhe: Assim diz Jefté: Israel não tomou a terra de Moabe, nem a terra dos amonitas;

[[v7-11-16]]

^<<v7-11-16,16>>^ mas quando Israel subiu do Egito, andou pelo deserto até o Mar Vermelho, e depois chegou a Cades;

[[v7-11-17]]

^<<v7-11-17,17>>^ dali enviou mensageiros ao rei de Edom, a dizer-lhe: Rogo-te que me deixes passar pela tua terra. Mas o rei de Edom não lhe deu ouvidos. Então enviou ao rei de Moabe, o qual também não consentiu; e assim Israel ficou em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ Depois andou pelo deserto e rodeou a terra de Edom e a terra de Moabe, e veio pelo lado oriental da terra de Moabe, e acampou além do Arnom; porém não entrou no território de Moabe, pois o Arnom era o limite de Moabe.

[[v7-11-19]]

^<<v7-11-19,19>>^ E Israel enviou mensageiros a Siom, rei dos amorreus, rei de Hesbom, e disse-lhe: Rogo-te que nos deixes passar pela tua terra até o meu lugar.

[[v7-11-20]]

^<<v7-11-20,20>>^ Siom, porém, não se fiou de Israel para o deixar passar pelo seu território; pelo contrário, ajuntando todo o seu povo, acampou em Jaza e combateu contra Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ E o Senhor Deus de Israel entregou Siom com todo o seu povo na mão de Israel, que os feriu e se apoderou de toda a terra dos amorreus que habitavam naquela região.

[[v7-11-22]]

^<<v7-11-22,22>>^ Apoderou-se de todo o território dos amorreus, desde o Arnom até o Jaboque, e desde o deserto até o Jordão.

[[v7-11-23]]

^<<v7-11-23,23>>^ Assim o Senhor Deus de Israel desapossou os amorreus de diante do seu povo de Israel; e possuirias tu esse território?

[[v7-11-24]]

^<<v7-11-24,24>>^ Não possuirias tu o território daquele que Quemós, teu deus, desapossasse de diante de ti? assim possuiremos nós o território de todos quantos o Senhor nosso Deus desapossar de diante de nós.

[[v7-11-25]]

^<<v7-11-25,25>>^ Agora, és tu melhor do que Balaque, filho de Zipor, rei de Moabe? ousou ele jamais contender com Israel, ou lhe mover guerra?

[[v7-11-26]]

^<<v7-11-26,26>>^ Enquanto Israel habitou trezentos anos em Hesbom e nas suas vilas, em Aroer e nas suas vilas em todas as cidades que estão ao longo do Arnom, por que não as recuperaste naquele tempo?

[[v7-11-27]]

^<<v7-11-27,27>>^ Não fui eu que pequei contra ti; és tu, porém, que usas de injustiça para comigo, fazendo-me guerra. O Senhor, que é juiz, julgue hoje entre os filhos de Israel e os amonitas.

[[v7-11-28]]

^<<v7-11-28,28>>^ Contudo o rei dos amonitas não deu ouvidos à mensagem que Jefté lhe enviou.

[[v7-11-29]]

^<<v7-11-29,29>>^ Então o Espírito do Senhor veio sobre Jefté, de modo que ele passou por Gileade e Manassés, e chegando a Mizpá de Gileade, dali foi ao encontro dos amonitas.

[[v7-11-30]]

^<<v7-11-30,30>>^ E Jefté fez um voto ao Senhor, dizendo: Se tu me entregares na mão os amonitas,

[[v7-11-31]]

^<<v7-11-31,31>>^ qualquer que, saindo da porta de minha casa, me vier ao encontro, quando eu, vitorioso, voltar dos amonitas, esse será do Senhor; eu o oferecerei em holocausto.

[[v7-11-32]]

^<<v7-11-32,32>>^ Assim Jefté foi ao encontro dos amonitas, a combater contra eles; e o Senhor lhos entregou na mão.

[[v7-11-33]]

^<<v7-11-33,33>>^ E Jefté os feriu com grande mortandade, desde Aroer até chegar a Minite, vinte cidades, e até Abel-Queramim. Assim foram subjugados os amonitas pelos filhos de Israel.

[[v7-11-34]]

^<<v7-11-34,34>>^ Quando Jefté chegou a Mizpá, à sua casa, eis que a sua filha lhe saiu ao encontro com adufes e com danças; e era ela a filha única; além dela não tinha outro filho nem filha.

[[v7-11-35]]

^<<v7-11-35,35>>^ Logo que ele a viu, rasgou as suas vestes, e disse: Ai de mim, filha minha! muito me abateste; és tu a causa da minha desgraça! pois eu fiz, um voto ao Senhor, e não posso voltar atrás.

[[v7-11-36]]

^<<v7-11-36,36>>^ Ela lhe respondeu: Meu pai, se fizeste um voto ao Senhor, faze de mim conforme o teu voto, pois o Senhor te vingou dos teus inimigos, os filhos de Amom.

[[v7-11-37]]

^<<v7-11-37,37>>^ Disse mais a seu pai: Concede-me somente isto: deixa-me por dois meses para que eu vá, e desça pelos montes, chorando a minha virgindade com as minhas companheiras.

[[v7-11-38]]

^<<v7-11-38,38>>^ Disse ele: Vai. E deixou-a ir por dois meses; então ela se foi com as suas companheiras, e chorou a sua virgindade pelos montes.

[[v7-11-39]]

^<<v7-11-39,39>>^ E sucedeu que, ao fim dos dois meses, tornou ela para seu pai, o qual cumpriu nela o voto que tinha feito; e ela não tinha conhecido varão. Daí veio o costume em Israel,

[[v7-11-40]]

^<<v7-11-40,40>>^ de irem as filhas de Israel de ano em ano lamentar por quatro dias a filha de Jefté, o gileadita. Isso não é

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]