include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-4-1]]

^<<v7-4-1,1>>^ Mas os filhos de Israel tornaram a fazer o que era mau aos olhos do Senhor, depois da morte de Eúde.

[[v7-4-2]]

^<<v7-4-2,2>>^ E o Senhor os vendeu na mão de Jabim, rei de Canaã, que reinava em Hazor; o chefe do seu exército era Sísera, o qual habitava em Harosete dos Gentios.

[[v7-4-3]]

^<<v7-4-3,3>>^ Então os filhos de Israel clamaram ao Senhor, porquanto Jabim tinha novecentos carros de ferro, e por vinte anos oprimia cruelmente os filhos de Israel.

[[v7-4-4]]

^<<v7-4-4,4>>^ Ora, Débora, profetisa, mulher de Lapidote, julgava a Israel naquele tempo.

[[v7-4-5]]

^<<v7-4-5,5>>^ Ela se assentava debaixo da palmeira de Débora, entre Ramá e Betel, na região montanhosa de Efraim; e os filhos de Israel subiam a ter com ela para julgamento.

[[v7-4-6]]

^<<v7-4-6,6>>^ Mandou ela chamar a Baraque, filho de Abinoão, de Quedes-Naftali, e disse-lhe: Porventura o Senhor Deus de Israel não te ordena, dizendo: Vai, e atrai gente ao monte Tabor, e toma contigo dez mil homens dos filhos de Naftali e dos filhos de Zebulom;

[[v7-4-7]]

^<<v7-4-7,7>>^ e atrairei a ti, para o ribeiro de Quisom, Sísera, chefe do exército de Jabim; juntamente com os seus carros e com as suas tropas, e to entregarei na mão?

[[v7-4-8]]

^<<v7-4-8,8>>^ Disse-lhe Baraque: Se fores comigo, irei; porém se não fores, não irei.

[[v7-4-9]]

^<<v7-4-9,9>>^ Respondeu ela: Certamente irei contigo; porém não será tua a honra desta expedição, pois à mão de uma mulher o Senhor venderá a Sísera. Levantou-se, pois, Débora, e foi com Baraque a Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Então Baraque convocou a Zebulom e a Naftali em Quedes, e subiram dez mil homens após ele; também Débora subiu com ele.

[[v7-4-11]]

^<<v7-4-11,11>>^ Ora, Heber, um queneu, se tinha apartado dos queneus, dos filhos de Hobabe, sogro de Moisés, e tinha estendido as suas tendas até o carvalho de Zaananim, que está junto a Quedes.

[[v7-4-12]]

^<<v7-4-12,12>>^ Anunciaram a Sísera que Baraque, filho de Abinoão, tinha subido ao monte Tabor.

[[v7-4-13]]

^<<v7-4-13,13>>^ Sísera, pois, ajuntou todos os seus carros, novecentos carros de ferro, e todo o povo que estava com ele, desde Harosete dos Gentios até o ribeiro de Quisom.

[[v7-4-14]]

^<<v7-4-14,14>>^ Então disse Débora a Baraque: Levanta-te, porque este é o dia em que o Senhor entregou Sísera na tua mão; porventura o Senhor não saiu adiante de ti? Baraque, pois, desceu do monte Tabor, e dez mil homens após ele.

[[v7-4-15]]

^<<v7-4-15,15>>^ E o Senhor desbaratou a Sísera, com todos os seus carros e todo o seu exército, ao fio da espada, diante de Baraque; e Sísera, descendo do seu carro, fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ Mas Baraque perseguiu os carros e o exército, até Harosete dos Gentios; e todo o exército de Sísera caiu ao fio da espada; não restou um só homem.

[[v7-4-17]]

^<<v7-4-17,17>>^ Entretanto Sísera fugiu a pé para a tenda de Jael, mulher de Heber, o queneu, porquanto havia paz entre Jabim, rei de Hazor, e a casa de Heber, o queneu.

[[v7-4-18]]

^<<v7-4-18,18>>^ Saindo Jael ao encontro de Sísera, disse-lhe: Entra, senhor meu, entra aqui; não temas. Ele entrou na sua tenda; e ela o cobriu com uma coberta.

[[v7-4-19]]

^<<v7-4-19,19>>^ Então ele lhe disse: Peço-te que me dês a beber um pouco d'água, porque tenho sede. Então ela abriu um odre de leite, e deu-lhe de beber, e o cobriu.

[[v7-4-20]]

^<<v7-4-20,20>>^ Disse-lhe ele mais: Põe-te à porta da tenda; e se alguém vier e te perguntar: Está aqui algum homem? responderás: Não.

[[v7-4-21]]

^<<v7-4-21,21>>^ Então Jael, mulher de Heber, tomou uma estaca da tenda e, levando um martelo, chegou-se de mansinho a ele e lhe cravou a estaca na fonte, de sorte que penetrou na terra; pois ele estava num profundo sono e mui cansado. E assim morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ E eis que, seguindo Baraque a Sísera, Jael lhe saiu ao encontro e disse-lhe: Vem, e mostrar-te-ei o homem a quem procuras. Entrou ele na tenda; e eis que Sísera jazia morto, com a estaca na fonte.

[[v7-4-23]]

^<<v7-4-23,23>>^ Assim Deus naquele dia humilhou a Jabim, rei de Canaã, diante dos filhos de Israel.

[[v7-4-24]]

^<<v7-4-24,24>>^ E a mão dos filhos de Israel prevalecia cada vez mais contra Jabim, rei de Canaã, até que o destruíram.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]