include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-10-1]]

^<<v7-10-1,1>>^ Depois de Abimeleque levantou-se, para livrar a Israel, Tola, filho de Puva, filho de Dodó, homem de Issacar, que habitava em Samir, na região montanhosa de Efraim.

[[v7-10-2]]

^<<v7-10-2,2>>^ Ele julgou a Israel vinte e três anos; e morreu, e foi sepultado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ Depois dele levantou-se Jair, gileadita, que julgou a Israel vinte e dois anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ Ele tinha trinta filhos, que cavalgavam sobre trinta jumentos; e tinham estes trinta cidades, que se chamam Havote-Jair, até a dia de hoje, as quais estão na terra de Gileade.

[[v7-10-5]]

^<<v7-10-5,5>>^ Morreu Jair, e foi sepultado em Camom.

[[v7-10-6]]

^<<v7-10-6,6>>^ Então tornaram os filhos de Israel a fazer e que era mau aos olhos do Senhor, e serviram aos baalins, e às astarotes, e aos deuses da Síria, e aos de Sidom, e de Moabe, e dos amonitas, e dos filisteus; e abandonaram o Senhor, e não o serviram.

[[v7-10-7]]

^<<v7-10-7,7>>^ Pelo que a ira do Senhor se acendeu contra Israel, e ele os vendeu na mão dos filisteus e na mão dos amonitas,

[[v7-10-8]]

^<<v7-10-8,8>>^ os quais naquele mesmo ano começaram a vexá-los e oprimi-los. Por dezoito anos oprimiram a todos os filhos de Israel que estavam dalém do Jordão, na terra dos amorreus, que é em Gileade.

[[v7-10-9]]

^<<v7-10-9,9>>^ E os amonitas passaram o Jordão, para pelejar também contra Judá e Benjamim, e contra a casa de Efraim, de maneira que Israel se viu muito angustiado.

[[v7-10-10]]

^<<v7-10-10,10>>^ Então os filhos de Israel clamaram ao Senhor, dizendo: Pecamos contra ti, pois abandonamos o nosso Deus, e servimos aos baalins.

[[v7-10-11]]

^<<v7-10-11,11>>^ O Senhor, porém, respondeu aos filhos de Israel: Porventura não vos livrei eu dos egípcios, dos amorreus, dos amonitas e dos filisteus?

[[v7-10-12]]

^<<v7-10-12,12>>^ Também os sidônios, os amalequitas e os maonitas vos oprimiram; e, quando clamastes a mim, não vos livrei da sua mão?

[[v7-10-13]]

^<<v7-10-13,13>>^ Contudo vós me deixastes a mim e servistes a outros deuses, pelo que não vos livrarei mais.

[[v7-10-14]]

^<<v7-10-14,14>>^ Ide e clamai aos deuses que escolhestes; que eles vos livrem no tempo da vossa angústia.

[[v7-10-15]]

^<<v7-10-15,15>>^ Mas os filhos de Israel disseram ao Senhor: Pecamos; fazes-nos conforme tudo quanto te parecer bem; tão-somente te rogamos que nos livres hoje.

[[v7-10-16]]

^<<v7-10-16,16>>^ E tiraram os deuses alheios do meio de si, e serviram ao Senhor, que se moveu de compaixão por causa da desgraça de Israel.

[[v7-10-17]]

^<<v7-10-17,17>>^ Depois os amonitas se reuniram e acamparam em Gileade; também os filhos de Israel, reunindo-se, acamparam em Mizpá.

[[v7-10-18]]

^<<v7-10-18,18>>^ Então o povo, isto é, os príncipes de Gileade disseram uns aos outros: Quem será o varão que começará a peleja contra os amonitas? esse será o chefe de todos os habitantes de Gileade.

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]