include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-1-1]]

^<<v7-1-1,1>>^ Depois da morte de Josué os filhos de Israel consultaram ao Senhor, dizendo: Quem dentre nós subirá primeiro aos cananeus, para pelejar contra eles?

[[v7-1-2]]

^<<v7-1-2,2>>^ Respondeu o Senhor: Judá subirá; eis que entreguei a terra na sua mão.

[[v7-1-3]]

^<<v7-1-3,3>>^ Então disse Judá a Simeão, seu irmão: sobe comigo à sorte que me coube, e pelejemos contra os cananeus, e eu também subirei contigo à tua sorte. E Simeão foi com ele.

[[v7-1-4]]

^<<v7-1-4,4>>^ Subiu, pois, Judá; e o Senhor lhes entregou nas mãos os cananeus e os perizeus; e bateram deles em Bezeque dez mil homens.

[[v7-1-5]]

^<<v7-1-5,5>>^ Acharam em Bezeque a Adoni-Bezeque, e pelejaram contra ele; e bateram os cananeus e os perizeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Mas Adoni-Bezeque fugiu; porém eles o perseguiram e, prendendo-o, cortaram-lhe os dedos polegares das mãos e dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Então disse Adoni-Bezeque: Setenta reis, com os dedos polegares das mãos e dos pés cortados, apanhavam as migalhas debaixo da minha mesa; assim como eu fiz, assim Deus me pagou. E o trouxeram a Jerusalém, e ali morreu.

[[v7-1-8]]

^<<v7-1-8,8>>^ Ora, os filhos de Judá pelejaram contra Jerusalém e, tomando-a, passaram-na ao fio da espada e puseram fogo à cidade.

[[v7-1-9]]

^<<v7-1-9,9>>^ Depois os filhos de Judá desceram a pelejar contra os cananeus que habitavam na região montanhosa, e no Negebe, e na baixada.

[[v7-1-10]]

^<<v7-1-10,10>>^ Então partiu Judá contra os cananeus que habitavam em Hebrom, cujo nome era outrora Quiriate-Arba; e bateu Sesai, Aimã e Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ Dali partiu contra os moradores de Debir, que se chamava outrora Quiriate-Sefer.

[[v7-1-12]]

^<<v7-1-12,12>>^ Disse então Calebe: A quem atacar Quiriate-Sefer e a tomar, darei a minha filha Acsa por mulher.

[[v7-1-13]]

^<<v7-1-13,13>>^ E tomou-a Otniel, filho de Quenaz, o irmão mais moço de Calebe; e este lhe deu sua filha Acsa por mulher.

[[v7-1-14]]

^<<v7-1-14,14>>^ Estando ela em caminho para a casa de Otniel, persuadiu-o que pedisse um campo ao pai dela. E quando ela saltou do jumento, Calebe lhe perguntou: Que é que tens?

[[v7-1-15]]

^<<v7-1-15,15>>^ Ela lhe respondeu: Dá-me um presente; porquanto me deste uma terra no Negebe, dá-me também fontes d'água. Deu-lhe, pois, Calebe as fontes superiores e as fontes inferiores.

[[v7-1-16]]

^<<v7-1-16,16>>^ Também os filhos do queneu, sogro de Moisés, subiram da cidade das palmeiras com os filhos de Judá ao deserto de Judá, que está ao sul de Arade; e foram habitar com o povo.

[[v7-1-17]]

^<<v7-1-17,17>>^ E Judá foi com Simeão, seu irmão, e derrotaram os cananeus que habitavam em Zefate, e a destruíram totalmente. E chamou-se o nome desta cidade Horma.

[[v7-1-18]]

^<<v7-1-18,18>>^ Judá tomou também a Gaza, a Asquelom e a Ecrom, com os seus respectivos territórios.

[[v7-1-19]]

^<<v7-1-19,19>>^ Assim estava o Senhor com Judá, o qual se apoderou da região montanhosa; mas não pôde desapossar os habitantes do vale, porquanto tinham carros de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ E como Moisés dissera, deram Hebrom a Calebe, que dali expulsou os três filhos de Anaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ Mas os filhos de Benjamim não expulsaram aos jebuseus que habitavam em Jerusalém; pelo que estes ficaram habitando com os filhos de Benjamim em Jerusalém até o dia de hoje.

[[v7-1-22]]

^<<v7-1-22,22>>^ Também os da casa de José subiram contra Betel; e o Senhor estava com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ E a casa de José fez espiar a Betel &#123;e fora outrora o nome desta cidade Luz&#125;;

[[v7-1-24]]

^<<v7-1-24,24>>^ e, vendo os espias a um homem que saía da cidade, disseram-lhe: Mostra-nos a entrada da cidade, e usaremos de bondade para contigo.

[[v7-1-25]]

^<<v7-1-25,25>>^ Mostrou-lhes, pois, a entrada da cidade, a qual eles feriram ao fio da espada; porém deixaram livre aquele homem e toda a sua família.

[[v7-1-26]]

^<<v7-1-26,26>>^ Então o homem se foi para a terra dos heteus, edificou uma cidade, e pôs-lhe o nome de Luz; este é o seu nome até o dia de hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ Manassés não expulsou os habitantes de Bete-Seã e suas vilas, nem os de Taanaque e suas vilas, aos levitas estas cidades e nem os de Ibleão e suas vilas, nem os de Megido e suas vilas; porém os cananeus persistiram em habitar naquela terra.

[[v7-1-28]]

^<<v7-1-28,28>>^ Mas quando Israel se tornou forte, sujeitou os cananeus a trabalhos forçados, porém não os expulsou de todo.

[[v7-1-29]]

^<<v7-1-29,29>>^ Também Efraim não expulsou os cananeus que habitavam em Gezer; mas os cananeus ficaram habitando no meio dele, em Gezer.

[[v7-1-30]]

^<<v7-1-30,30>>^ Também Zebulom não expulsou os habitantes de Quitrom, nem os de Naalol; porém os cananeus ficaram habitando no meio dele, e foram sujeitos a trabalhos forçados.

[[v7-1-31]]

^<<v7-1-31,31>>^ Também Aser não expulsou os habitantes de Aco, nem de Sidom, nem de Alabe, nem de Aczibe, nem de Helba, nem de Afeca, nem de Reobe;

[[v7-1-32]]

^<<v7-1-32,32>>^ porém os aseritas ficaram habitando no meio dos cananeus, os habitantes da terra, porquanto não os expulsaram.

[[v7-1-33]]

^<<v7-1-33,33>>^ Também Naftali não expulsou os habitantes de Bete-Semes, nem os de Bete-Anate; mas, habitou no meio dos cananeus, os habitantes da terra; todavia os habitantes de Bete-Semes e os de Bete-Anate foram sujeitos a trabalhos forçados.

[[v7-1-34]]

^<<v7-1-34,34>>^ Os amorreus impeliram os filhos de Dã até a região montanhosa; pois não lhes permitiram descer ao vale.

[[v7-1-35]]

^<<v7-1-35,35>>^ Os amorreus quiseram também habitar no monte Heres, em Aijalom e em Saalabim; contudo prevaleceu a mão da casa de José, de modo que eles ficaram sujeitos a trabalhos forçados.

[[v7-1-36]]

^<<v7-1-36,36>>^ E foi o termo dos amorreus desde a subida de Acrabim, desde Sela, e dali para cima.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]