include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v7-21-1]]

^<<v7-21-1,1>>^ Ora, os homens de Israel tinham jurado em Mizpá dizendo: Nenhum de nós dará sua filha por mulher aos benjamitas.

[[v7-21-2]]

^<<v7-21-2,2>>^ Veio, pois, o povo a Betel, e ali ficou sentado até a tarde, diante de Deus; e todos, levantando a voz, fizeram grande pranto,

[[v7-21-3]]

^<<v7-21-3,3>>^ e disseram: Ah! Senhor Deus de Israel, por que sucedeu isto, que falte uma tribo em Israel?

[[v7-21-4]]

^<<v7-21-4,4>>^ No dia seguinte o povo levantou-se de manhã cedo, edificou ali um altar e ofereceu holocaustos e ofertas pacíficas.

[[v7-21-5]]

^<<v7-21-5,5>>^ E disseram os filhos de Israel: Quem dentre todas as tribos de Israel não subiu à assembléia diante do Senhor? Porque se tinha feito um juramento solene acerca daquele que não subisse ao Senhor em Mizpá, dizendo: Certamente será morto.

[[v7-21-6]]

^<<v7-21-6,6>>^ E os filhos de Israel tiveram pena de Benjamim, seu irmão, e disseram: Hoje é cortada de Israel uma tribo.

[[v7-21-7]]

^<<v7-21-7,7>>^ Como havemos de conseguir mulheres para os que restam deles, desde que juramos pelo Senhor que nenhuma de nossas filhas lhes daríamos por mulher?

[[v7-21-8]]

^<<v7-21-8,8>>^ Então disseram: Quem é que dentre as tribos de Israel não subiu ao Senhor em Mizpá? E eis que ninguém de Jabes-Gileade viera ao arraial, à assembléia.

[[v7-21-9]]

^<<v7-21-9,9>>^ Porquanto, ao contar-se o povo, nenhum dos habitantes de Jabes-Gileade estava ali.

[[v7-21-10]]

^<<v7-21-10,10>>^ Pelo que a congregação enviou para lá doze mil homens dos mais valorosos e lhes ordenou, dizendo: Ide, e passai ao fio da espada os habitantes de Jabes-Gileade, juntamente com as mulheres e os pequeninos.

[[v7-21-11]]

^<<v7-21-11,11>>^ Mas isto é o que haveis de fazer: A todo homem e a toda mulher que tiver conhecido homem, totalmente destruireis.

[[v7-21-12]]

^<<v7-21-12,12>>^ E acharam entre os moradores de Jabes-Gileade quatrocentas moças virgens, que não tinham conhecido homem, e as trouxeram ao arraial em Siló, que está na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Toda a congregação enviou mensageiros aos filhos de Benjamim, que estavam na penha de Rimom, e lhes proclamou a paz.

[[v7-21-14]]

^<<v7-21-14,14>>^ Então voltaram os benjamitas, e os de Israel lhes deram as mulheres que haviam guardado com vida, das mulheres de Jabes-Gileade; porém estas ainda não lhes bastaram.

[[v7-21-15]]

^<<v7-21-15,15>>^ E o povo teve pena de Benjamim, porquanto o Senhor tinha aberto uma brecha nas tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ Disseram, pois os anciãos da congregação: Como havemos de conseguir mulheres para os que restam, pois que foram destruídas as mulheres de Benjamim?

[[v7-21-17]]

^<<v7-21-17,17>>^ Disseram mais: Deve haver uma herança para os que restam de Benjamim, para que uma tribo não seja apagada de Israel.

[[v7-21-18]]

^<<v7-21-18,18>>^ Contudo nós não lhes poderemos dar mulheres dentre nossas filhas. Pois os filhos de Israel tinham jurado, dizendo: Maldito aquele que der mulher aos benjamitas.

[[v7-21-19]]

^<<v7-21-19,19>>^ Disseram então: Eis que de ano em ano se realiza a festa do Senhor em Siló que está ao norte de Betel, a leste do caminho que sobe de Betel a Siquém, e ao sul de Lebona.

[[v7-21-20]]

^<<v7-21-20,20>>^ Ordenaram, pois, aos filhos de Benjamim, dizendo: Ide, ponde-vos de emboscada nas vinhas,

[[v7-21-21]]

^<<v7-21-21,21>>^ e vigiai; ao saírem as filhas de Siló a dançar nos coros, saí vós das vinhas, arrebatai cada um sua mulher, das filhas de Siló, e ide-vos para a terra de Benjamim.

[[v7-21-22]]

^<<v7-21-22,22>>^ Então quando seus pais e seus irmãos vierem queixar-se a nós, nós lhes diremos: Dignai-vos de no-las conceder; pois nesta guerra não tomamos mulheres para cada um deles, nem vós lhas destes; de outro modo seríeis agora culpados.

[[v7-21-23]]

^<<v7-21-23,23>>^ Assim fizeram os filhos de Benjamim; e conforme o seu número tomaram para si mulheres, arrebatando-as dentre as que dançavam; e, retirando-se, voltaram à sua herança, reedificaram as cidades e habitaram nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ Nesse mesmo tempo os filhos de Israel partiram dali, cada um para a sua tribo e para a sua família; assim voltaram cada um para a sua herança.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naqueles dias não havia rei em Israel; cada um fazia o que parecia bem aos seus olhos.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]