include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v29-3-1]]

^<<v29-3-1,1>>^ Pois eis que naqueles dias, e naquele tempo, em que eu restaurar os exilados de Judá e de Jerusalém,

[[v29-3-2]]

^<<v29-3-2,2>>^ congregarei todas as nações, e as farei descer ao vale de Jeosafá; e ali com elas entrarei em juízo, por causa do meu povo, e da minha herança, Israel, a quem elas espalharam por entre as nações; repartiram a minha terra,

[[v29-3-3]]

^<<v29-3-3,3>>^ e lançaram sortes sobre o meu povo; deram um menino por uma meretriz, e venderam uma menina por vinho, para beberem.

[[v29-3-4]]

^<<v29-3-4,4>>^ E também que tendes vós comigo, Tiro e Sidom, e todas as regiões da Filístia? Acaso quereis vingar-vos de mim? Se assim vos quereis vingar, bem depressa retribuirei o vosso feito sobre a vossa cabeça.

[[v29-3-5]]

^<<v29-3-5,5>>^ Visto como levastes a minha prata e o meu ouro, e os meus ricos tesouros metestes nos vossos templos;

[[v29-3-6]]

^<<v29-3-6,6>>^ também vendestes os filhos de Judá e os filhos de Jerusalém aos filhos dos gregos, para os apartar para longe dos seus termos;

[[v29-3-7]]

^<<v29-3-7,7>>^ eis que eu os suscitarei do lugar para onde os vendestes, e retribuirei o vosso feito sobre a vossa cabeça;

[[v29-3-8]]

^<<v29-3-8,8>>^ pois venderei vossos filhos e vossas filhas na mão dos filhos de Judá, e estes os venderão aos sabeus, a uma nação remota, porque o Senhor o disse.

[[v29-3-9]]

^<<v29-3-9,9>>^ Proclamai isto entre as nações: Preparai a guerra, suscitai os valentes. Cheguem-se todos os homens de guerra, subam eles todos.

[[v29-3-10]]

^<<v29-3-10,10>>^ Forjai espadas das relhas dos vossos arados, e lanças das vossas podadeiras; diga o fraco: Eu sou forte.

[[v29-3-11]]

^<<v29-3-11,11>>^ Apressai-vos, e vinde, todos os povos em redor, e ajuntai-vos; para ali, ó Senhor, faze descer os teus valentes.

[[v29-3-12]]

^<<v29-3-12,12>>^ Suscitem-se as nações, e subam ao vale de Jeosafá; pois ali me assentarei, para julgar todas as nações em redor.

[[v29-3-13]]

^<<v29-3-13,13>>^ Lançai a foice, porque já está madura a seara; vinde, descei, porque o lagar está cheio, os vasos dos lagares trasbordam, porquanto a sua malícia é grande.

[[v29-3-14]]

^<<v29-3-14,14>>^ Multidões, multidões no vale da decisão! porque o dia do Senhor está perto, no vale da decisão.

[[v29-3-15]]

^<<v29-3-15,15>>^ O sol e a lua escurecem, e as estrelas retiram o seu resplendor.

[[v29-3-16]]

^<<v29-3-16,16>>^ E o Senhor brama de Sião, e de Jerusalém faz ouvir a sua voz; os céus e a terra tremem, mas o Senhor é o refúgio do seu povo, e a fortaleza dos filhos de Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ Assim vós sabereis que eu sou o Senhor vosso Deus, que habito em Sião, o meu santo monte; Jerusalém será santa, e estranhos não mais passarão por ela.

[[v29-3-18]]

^<<v29-3-18,18>>^ E naquele dia os montes destilarão mosto, e os outeiros manarão leite, e todos os ribeiros de Judá estarão cheios de águas; e sairá uma fonte da casa do Senhor, e regará o vale de Sitim.

[[v29-3-19]]

^<<v29-3-19,19>>^ O Egito se tornará uma desolação, e Edom se fará um deserto assolado, por causa da violência que fizeram aos filhos de Judá, em cuja terra derramaram sangue inocente.

[[v29-3-20]]

^<<v29-3-20,20>>^ Mas Judá será habitada para sempre, e Jerusalém de geração em geração.

[[v29-3-21]]

^<<v29-3-21,21>>^ E purificarei o sangue que eu não tinha purificado; porque o Senhor habita em Sião.

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]