include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v29-1-1]]

^<<v29-1-1,1>>^ Palavra do Senhor, que foi dirigida a Joel, filho de Petuel.

[[v29-1-2]]

^<<v29-1-2,2>>^ Ouvi isto, vós anciãos, e escutai, todos os moradores da terra: Aconteceu isto em vossos dias, ou nos dias de vossos pais?

[[v29-1-3]]

^<<v29-1-3,3>>^ Fazei sobre isto uma narração a vossos filhos, e vossos filhos a transmitam a seus filhos, e os filhos destes à geração seguinte.

[[v29-1-4]]

^<<v29-1-4,4>>^ O que a locusta cortadora deixou, a voadora o comeu; e o que a voadora deixou, a devoradora o comeu; e o que a devoradora deixou, a destruidora o comeu.

[[v29-1-5]]

^<<v29-1-5,5>>^ Despertai, bêbedos, e chorai; gemei, todos os que bebeis vinho, por causa do mosto; porque tirado é da vossa boca.

[[v29-1-6]]

^<<v29-1-6,6>>^ Porque sobre a minha terra é vinda uma nação poderosa e inumerável. os seus dentes são dentes de leão, e têm queixadas de uma leoa.

[[v29-1-7]]

^<<v29-1-7,7>>^ Fez da minha vide uma assolação, e tirou a casca à minha figueira; despiu-a toda, e a lançou por terra; os seus sarmentos se embranqueceram.

[[v29-1-8]]

^<<v29-1-8,8>>^ Lamenta como a virgem que está cingida de saco, pelo marido da sua mocidade.

[[v29-1-9]]

^<<v29-1-9,9>>^ Está cortada da casa do Senhor a oferta de cereais e a libação; os sacerdotes, ministros do Senhor, estão entristecidos.

[[v29-1-10]]

^<<v29-1-10,10>>^ O campo está assolado, e a terra chora; porque o trigo está destruído, o mosto se secou, o azeite falta.

[[v29-1-11]]

^<<v29-1-11,11>>^ Envergonhai-vos, lavradores, uivai, vinhateiros, sobre o trigo e a cevada; porque a colheita do campo pereceu.

[[v29-1-12]]

^<<v29-1-12,12>>^ A vide se secou, a figueira se murchou; a romeira também, e a palmeira e a macieira, sim, todas as árvores do campo se secaram; e a alegria esmoreceu entre os filhos dos homens.

[[v29-1-13]]

^<<v29-1-13,13>>^ Cingi-vos de saco e lamentai-vos, sacerdotes; uivai, ministros do altar; entrai e passai a noite vestidos de saco, ministros do meu Deus; porque foi cortada da casa do vosso Deus a oferta de cereais e a libação.

[[v29-1-14]]

^<<v29-1-14,14>>^ Santificai um jejum, convocai uma assembléia solene, congregai os anciãos, e todos os moradores da terra, na casa do Senhor vosso Deus, e clamai ao Senhor.

[[v29-1-15]]

^<<v29-1-15,15>>^ Ai do dia! pois o dia do senhor está perto, e vem como assolação da parte do Todo-Poderoso.

[[v29-1-16]]

^<<v29-1-16,16>>^ Porventura não está cortado o mantimento de diante de nossos olhos? a alegria e o regozijo da casa do nosso Deus?

[[v29-1-17]]

^<<v29-1-17,17>>^ A semente mirrou debaixo dos seus torrões; os celeiros estão desolados, os armazéns arruinados; porque falharam os cereais.

[[v29-1-18]]

^<<v29-1-18,18>>^ Como geme o gado! As manadas de vacas estão confusas, porque não têm pasto; também os rebanhos de ovelhas estão desolados.

[[v29-1-19]]

^<<v29-1-19,19>>^ A ti clamo, ó Senhor; porque o fogo consumiu os pastos do deserto, e a chama abrasou todas as árvores do campo.

[[v29-1-20]]

^<<v29-1-20,20>>^ Até os animais do campo suspiram por ti; porque as correntes d'água se secaram, e o fogo consumiu os pastos do deserto.

'''

xref:028-oseias/028-oseias-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]