include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v29-2-1]]

^<<v29-2-1,1>>^ Tocai a trombeta em Sião, e dai o alarma no meu santo monte. Tremam todos os moradores da terra, porque vem vindo o dia do Senhor; já está perto;

[[v29-2-2]]

^<<v29-2-2,2>>^ dia de trevas e de escuridão, dia de nuvens e de negrume! Como a alva, está espalhado sobre os montes um povo grande e poderoso, qual nunca houve, nem depois dele haverá pelos anos adiante, de geração em geração:

[[v29-2-3]]

^<<v29-2-3,3>>^ Diante dele um fogo consome, e atrás dele uma chama abrasa; a terra diante dele é como o jardim do Édem mas atrás dele um desolado deserto; sim, nada lhe escapa.

[[v29-2-4]]

^<<v29-2-4,4>>^ A sua aparência é como a de cavalos; e como cavaleiros, assim correm.

[[v29-2-5]]

^<<v29-2-5,5>>^ Como o estrondo de carros sobre os cumes dos montes vão eles saltando, como o ruído da chama de fogo que consome o restelho, como um povo poderoso, posto em ordem de batalha.

[[v29-2-6]]

^<<v29-2-6,6>>^ Diante dele estão angustiados os povos; todos os semblantes empalidecem.

[[v29-2-7]]

^<<v29-2-7,7>>^ Correm como valentes, como homens de guerra sobem os muros; e marcham cada um nos seus caminhos e não se desviam da sua fileira.

[[v29-2-8]]

^<<v29-2-8,8>>^ Não empurram uns aos outros; marcham cada um pelo seu carreiro; abrem caminho por entre as armas, e não se detêm.

[[v29-2-9]]

^<<v29-2-9,9>>^ Pulam sobre a cidade, correm pelos muros; sobem nas casas; entram pelas janelas como o ladrão.

[[v29-2-10]]

^<<v29-2-10,10>>^ Diante deles a terra se abala; tremem os céus; o sol e a lua escurecem, e as estrelas retiram o seu resplendor.

[[v29-2-11]]

^<<v29-2-11,11>>^ E o Senhor levanta a sua voz diante do seu exército, porque muito grande é o seu arraial; e poderoso é quem executa a sua ordem; pois o dia do Senhor é grande e muito terrível, e quem o poderá suportar?

[[v29-2-12]]

^<<v29-2-12,12>>^ Todavia ainda agora diz o Senhor: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto.

[[v29-2-13]]

^<<v29-2-13,13>>^ E rasgai o vosso coração, e não as vossas vestes; e convertei-vos ao Senhor vosso Deus; porque ele é misericordioso e compassivo, tardio em irar-se e grande em benignidade, e se arrepende do mal.

[[v29-2-14]]

^<<v29-2-14,14>>^ Quem sabe se não se voltará e se arrependerá, e deixará após si uma bênção, em oferta de cereais e libação para o Senhor vosso Deus?

[[v29-2-15]]

^<<v29-2-15,15>>^ Tocai a trombeta em Sião, santificai um jejum, convocai uma assembléia solene;

[[v29-2-16]]

^<<v29-2-16,16>>^ congregai o povo, santificai a congregação, ajuntai os anciãos, congregai os meninos, e as crianças de peito; saia o noivo da sua recâmara, e a noiva do seu tálamo.

[[v29-2-17]]

^<<v29-2-17,17>>^ Chorem os sacerdotes, ministros do Senhor, entre o alpendre e o altar, e digam: Poupa a teu povo, ó Senhor, e não entregues a tua herança ao opróbrio, para que as nações façam escárnio dele. Por que diriam entre os povos: Onde está o seu Deus?

[[v29-2-18]]

^<<v29-2-18,18>>^ Então o Senhor teve zelo da sua terra, e se compadeceu do seu povo.

[[v29-2-19]]

^<<v29-2-19,19>>^ E o Senhor, respondendo, disse ao seu povo: Eis que vos envio o trigo, o vinho e o azeite, e deles sereis fartos; e vos não entregarei mais ao opróbrio entre as nações;

[[v29-2-20]]

^<<v29-2-20,20>>^ e removerei para longe de vós o exército do Norte, e o lançarei para uma terra seca e deserta, a sua frente para o mar oriental, e a sua retaguarda para o mar ocidental; subirá o seu mau cheiro, e subirá o seu fedor, porque ele tem feito grandes coisas.

[[v29-2-21]]

^<<v29-2-21,21>>^ Não temas, ó terra; regozija-te e alegra-te, porque o Senhor tem feito grandes coisas.

[[v29-2-22]]

^<<v29-2-22,22>>^ Não temais, animais do campo; porque os pastos do deserto já reverdecem, porque a árvore dá o seu fruto, e a vide e a figueira dão a sua força.

[[v29-2-23]]

^<<v29-2-23,23>>^ Alegrai-vos, pois, filhos de Sião, e regozijai-vos no Senhor vosso Deus; porque ele vos dá em justa medida a chuva temporã, e faz descer abundante chuva, a temporã e a serôdia, como dantes.

[[v29-2-24]]

^<<v29-2-24,24>>^ E as eiras se encherão de trigo, e os lagares trasbordarão de mosto e de azeite.

[[v29-2-25]]

^<<v29-2-25,25>>^ Assim vos restituirei os anos que foram consumidos pela locusta voadora, a devoradora, a destruidora e a cortadora, o meu grande exército que enviei contra vós.

[[v29-2-26]]

^<<v29-2-26,26>>^ Comereis abundantemente e vos fartareis, e louvareis o nome do Senhor vosso Deus, que procedeu para convosco maravilhosamente; e o meu povo nunca será envergonhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ Vós, pois, sabereis que eu estou no meio de Israel, e que eu sou o Senhor vosso Deus, e que não há outro; e o meu povo nunca mais será envergonhado.

[[v29-2-28]]

^<<v29-2-28,28>>^ Acontecerá depois que derramarei o meu Espírito sobre toda a carne; vossos filhos e vossas filhas profetizarão, os vossos anciãos terão sonhos, os vossos mancebos terão visões;

[[v29-2-29]]

^<<v29-2-29,29>>^ e também sobre os servos e sobre as servas naqueles dias derramarei o meu Espírito.

[[v29-2-30]]

^<<v29-2-30,30>>^ E mostrarei prodígios no céu e na terra, sangue e fogo, e colunas de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol se converterá em trevas, e a lua em sangue, antes que venha o grande e terrível dia do Senhor.

[[v29-2-32]]

^<<v29-2-32,32>>^ E há de ser que todo aquele que invocar o nome do Senhor será salvo; pois no monte Sião e em Jerusalém estarão os que escaparem, como disse o Senhor, e entre os sobreviventes aqueles que o Senhor chamar.

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]