include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz o Senhor: Onde está a carta de divórcio de vossa mãe, pela qual eu a repudiei? ou quem é o meu credor, a quem eu vos tenha vendido? Eis que por vossas maldades fostes vendidos, e por vossas transgressões foi repudiada vossa mãe.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que razão, quando eu vim, ninguém apareceu? quando chamei, não houve quem respondesse? Acaso tanto se encolheu a minha mão, que já não possa remir? ou não tenho poder para livrar? Eis que com a minha repreensão faço secar o mar, e torno os rios em deserto; cheiram mal os seus peixes, pois não há água, e morrem de sede:

[[v23-50-3]]

^<<v23-50-3,3>>^ Eu visto os céus de negridão, e lhes ponho cilício por sua cobertura.

[[v23-50-4]]

^<<v23-50-4,4>>^ O Senhor Deus me deu a língua dos instruídos para que eu saiba sustentar com uma palavra o que está cansado; ele desperta-me todas as manhãs; desperta-me o ouvido para que eu ouça como discípulo.

[[v23-50-5]]

^<<v23-50-5,5>>^ O Senhor Deus abriu-me os ouvidos, e eu não fui rebelde, nem me retirei para trás.

[[v23-50-6]]

^<<v23-50-6,6>>^ Ofereci as minhas costas aos que me feriam, e as minhas faces aos que me arrancavam a barba; não escondi o meu rosto dos que me afrontavam e me cuspiam.

[[v23-50-7]]

^<<v23-50-7,7>>^ Pois o Senhor Deus me ajuda; portanto não me sinto confundido; por isso pus o meu rosto como um seixo, e sei que não serei envergonhado.

[[v23-50-8]]

^<<v23-50-8,8>>^ Perto está o que me justifica; quem contenderá comigo? apresentemo-nos juntos; quem é meu adversário? chegue-se para mim.

[[v23-50-9]]

^<<v23-50-9,9>>^ Eis que o Senhor Deus me ajuda; quem há que me condene? Eis que todos eles se envelhecerão como um vestido, e a traça os comerá.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem há entre vós que tema ao Senhor? ouça ele a voz do seu servo. Aquele que anda em trevas, e não tem luz, confie no nome do Senhor, e firme-se sobre o seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Eia! todos vós, que acendeis fogo, e vos cingis com tições acesos; andai entre as labaredas do vosso fogo, e entre os tições que ateastes! Isto vos sobrevirá da minha mão, e em tormentos jazereis.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]