include::./index.adoc[]

[[v23-60-0]]
=== Isaías, 60
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-60-1]]

^<<v23-60-1,1>>^ Levanta-te, resplandece, porque é chegada a tua luz, e é nascida sobre ti a glória do Senhor.

[[v23-60-2]]

^<<v23-60-2,2>>^ Pois eis que as trevas cobrirão a terra, e a escuridão os povos; mas sobre ti o Senhor virá surgindo, e a sua glória se verá sobre ti.

[[v23-60-3]]

^<<v23-60-3,3>>^ E nações caminharão para a tua luz, e reis para o resplendor da tua aurora.

[[v23-60-4]]

^<<v23-60-4,4>>^ Levanta em redor os teus olhos, e vê; todos estes se ajuntam, e vêm ter contigo; teus filhos vêm de longe, e tuas filhas se criarão a teu lado.

[[v23-60-5]]

^<<v23-60-5,5>>^ Então o verás, e estarás radiante, e o teu coração estremecerá e se alegrará; porque a abundância do mar se tornará a ti, e as riquezas das nações a ti virão.

[[v23-60-6]]

^<<v23-60-6,6>>^ A multidão de camelos te cobrirá, os dromedários de Midiã e Efá; todos os de Sabá, virão; trarão ouro e incenso, e publicarão os louvores do Senhor.

[[v23-60-7]]

^<<v23-60-7,7>>^ Todos os rebanhos de Quedar se congregarão em ti, os carneiros de Nebaoite te servirão; com aceitação subirão ao meu altar, e eu glorificarei a casa da minha glória.

[[v23-60-8]]

^<<v23-60-8,8>>^ Quem são estes que vêm voando como nuvens e como pombas para as suas janelas?

[[v23-60-9]]

^<<v23-60-9,9>>^ Certamente as ilhas me aguardarão, e vêm primeiro os navios de Társis, para trazerem teus filhos de longe, e com eles a sua prata e o seu ouro, para o nome do Senhor teu Deus, e para o Santo de Israel, porquanto ele te glorificou.

[[v23-60-10]]

^<<v23-60-10,10>>^ E estrangeiros edificarão os teus muros, e os seus reis te servirão; porque na minha ira te feri, mas na minha benignidade tive misericórdia de ti.

[[v23-60-11]]

^<<v23-60-11,11>>^ As tuas portas estarão abertas de contínuo; nem de dia nem de noite se fecharão; para que te sejam trazidas as riquezas das nações, e conduzidos com elas os seus reis.

[[v23-60-12]]

^<<v23-60-12,12>>^ Porque a nação e o reino que não te servirem perecerão; sim, essas nações serão de todo assoladas.

[[v23-60-13]]

^<<v23-60-13,13>>^ A glória do Líbano virá a ti; a faia, o olmeiro, e o buxo conjuntamente, para ornarem o lugar do meu santuário; e farei glorioso o lugar em que assentam os meus pés.

[[v23-60-14]]

^<<v23-60-14,14>>^ Também virão a ti, inclinando-se, os filhos dos que te oprimiram; e prostrar-se-ão junto às plantas dos teus pés todos os que te desprezaram; e chamar-te-ão a cidade do Senhor, a Sião do Santo de Israel.

[[v23-60-15]]

^<<v23-60-15,15>>^ Ao invés de seres abandonada e odiada como eras, de sorte que ninguém por ti passava, far-te-ei uma excelência perpétua, uma alegria de geração em geração.

[[v23-60-16]]

^<<v23-60-16,16>>^ E mamarás o leite das nações, e te alimentarás ao peito dos reis; assim saberás que eu sou o Senhor, o teu Salvador, e o teu Redentor, o Poderoso de Jacó.

[[v23-60-17]]

^<<v23-60-17,17>>^ Por bronze trarei ouro, por ferro trarei prata, por madeira bronze, e por pedras ferro; farei pacíficos os teus oficiais e justos os teus exatores.

[[v23-60-18]]

^<<v23-60-18,18>>^ Não se ouvirá mais de violência na tua terra, de desolação ou destruição nos teus termos; mas aos teus muros chamarás Salvação, e às tuas portas Louvor.

[[v23-60-19]]

^<<v23-60-19,19>>^ Não te servirá mais o sol para luz do dia, nem com o seu resplendor a lua te alumiará; mas o Senhor será a tua luz perpétua, e o teu Deus a tua glória.

[[v23-60-20]]

^<<v23-60-20,20>>^ Nunca mais se porá o teu sol, nem a tua lua minguará; porque o Senhor será a tua luz perpétua, e acabados serão os dias do teu luto.

[[v23-60-21]]

^<<v23-60-21,21>>^ E todos os do teu povo serão justos; para sempre herdarão a terra; serão renovos por mim plantados, obra das minhas mãos, para que eu seja glorificado.

[[v23-60-22]]

^<<v23-60-22,22>>^ O mais pequeno virá a ser mil, e o mínimo uma nação forte; eu, o Senhor, apressarei isso a seu tempo.

'''

xref:023-isaias/023-isaias-059.adoc#v23-59-0[&#60; Capítulo Anterior] | <<v23-60-0,Topo>> | xref:023-isaias/023-isaias-061.adoc#v23-61-0[Próximo Capítulo &#62;]