include::./index.adoc[]

[[v23-53-0]]
=== Isaías, 53
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-53-1]]

^<<v23-53-1,1>>^ Quem deu crédito à nossa pregação? e a quem se manifestou o braço do Senhor?

[[v23-53-2]]

^<<v23-53-2,2>>^ Pois foi crescendo como renovo perante ele, e como raiz que sai duma terra seca; não tinha formosura nem beleza; e quando olhávamos para ele, nenhuma beleza víamos, para que o desejássemos.

[[v23-53-3]]

^<<v23-53-3,3>>^ Era desprezado, e rejeitado dos homens; homem de dores, e experimentado nos sofrimentos; e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum.

[[v23-53-4]]

^<<v23-53-4,4>>^ Verdadeiramente ele tomou sobre si as nossas enfermidades, e carregou com as nossas dores; e nós o reputávamos por aflito, ferido de Deus, e oprimido.

[[v23-53-5]]

^<<v23-53-5,5>>^ Mas ele foi ferido por causa das nossas transgressões, e esmagado por causa das nossas iniqüidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados.

[[v23-53-6]]

^<<v23-53-6,6>>^ Todos nós andávamos desgarrados como ovelhas, cada um se desviava pelo seu caminho; mas o Senhor fez cair sobre ele a iniqüidade de todos nós.

[[v23-53-7]]

^<<v23-53-7,7>>^ Ele foi oprimido e afligido, mas não abriu a boca; como um cordeiro que é levado ao matadouro, e como a ovelha que é muda perante os seus tosquiadores, assim ele não abriu a boca.

[[v23-53-8]]

^<<v23-53-8,8>>^ Pela opressão e pelo juízo foi arrebatado; e quem dentre os da sua geração considerou que ele fora cortado da terra dos viventes, ferido por causa da transgressão do meu povo?

[[v23-53-9]]

^<<v23-53-9,9>>^ E deram-lhe a sepultura com os ímpios, e com o rico na sua morte, embora nunca tivesse cometido injustiça, nem houvesse engano na sua boca.

[[v23-53-10]]

^<<v23-53-10,10>>^ Todavia, foi da vontade do Senhor esmagá-lo, fazendo-o enfermar; quando ele se puser como oferta pelo pecado, verá a sua posteridade, prolongará os seus dias, e a vontade do Senhor prosperará nas suas mãos.

[[v23-53-11]]

^<<v23-53-11,11>>^ Ele verá o fruto do trabalho da sua alma, e ficará satisfeito; com o seu conhecimento o meu servo justo justificará a muitos, e as iniqüidades deles levará sobre si.

[[v23-53-12]]

^<<v23-53-12,12>>^ Pelo que lhe darei o seu quinhão com os grandes, e com os poderosos repartirá ele o despojo; porquanto derramou a sua alma até a morte, e foi contado com os transgressores; mas ele levou sobre si o pecado de muitos, e pelos transgressores intercedeu.

'''

xref:023-isaias/023-isaias-052.adoc#v23-52-0[&#60; Capítulo Anterior] | <<v23-53-0,Topo>> | xref:023-isaias/023-isaias-054.adoc#v23-54-0[Próximo Capítulo &#62;]