include::./index.adoc[]

[[v23-24-0]]
=== Isaías, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-24-1]]

^<<v23-24-1,1>>^ Eis que o Senhor esvazia a terra e a desola, transtorna a sua superfície e dispersa os seus moradores.

[[v23-24-2]]

^<<v23-24-2,2>>^ E o que suceder ao povo, sucederá ao sacerdote; ao servo, como ao seu senhor; à serva, como à sua senhora; ao comprador, como ao vendedor; ao que empresta, como ao que toma emprestado; ao que recebe usura, como ao que paga usura.

[[v23-24-3]]

^<<v23-24-3,3>>^ De todo se esvaziará a terra, e de todo será saqueada, porque o Senhor pronunciou esta palavra.

[[v23-24-4]]

^<<v23-24-4,4>>^ A terra pranteia e se murcha; o mundo enfraquece e se murcha; enfraquecem os mais altos do povo da terra.

[[v23-24-5]]

^<<v23-24-5,5>>^ Na verdade a terra está contaminada debaixo dos seus habitantes; porquanto transgridem as leis, mudam os estatutos, e quebram o pacto eterno.

[[v23-24-6]]

^<<v23-24-6,6>>^ Por isso a maldição devora a terra, e os que habitam nela sofrem por serem culpados; por isso são queimados os seus habitantes, e poucos homens restam.

[[v23-24-7]]

^<<v23-24-7,7>>^ Pranteia o mosto, enfraquece a vide, e suspiram todos os que eram alegres de coração.

[[v23-24-8]]

^<<v23-24-8,8>>^ Cessa o folguedo dos tamboris, acaba a algazarra dos jubilantes, cessa a alegria da harpa.

[[v23-24-9]]

^<<v23-24-9,9>>^ Já não bebem vinho ao som das canções; a bebida forte é amarga para os que a bebem.

[[v23-24-10]]

^<<v23-24-10,10>>^ Demolida está a cidade desordeira; todas as casas estão fechadas, de modo que ninguém pode entrar.

[[v23-24-11]]

^<<v23-24-11,11>>^ Há lastimoso clamor nas ruas por falta do vinho; toda a alegria se escureceu, já se foi o prazer da terra.

[[v23-24-12]]

^<<v23-24-12,12>>^ Na cidade só resta a desolação, e a porta está reduzida a ruínas.

[[v23-24-13]]

^<<v23-24-13,13>>^ Pois será no meio da terra, entre os povos, como a sacudidura da oliveira, e como os rabiscos, quando está acabada a vindima.

[[v23-24-14]]

^<<v23-24-14,14>>^ Estes alçarão a sua voz, bradando de alegria; por causa da majestade do Senhor clamarão desde o mar.

[[v23-24-15]]

^<<v23-24-15,15>>^ Por isso glorificai ao Senhor no Oriente, e na região litorânea do mar ao nome do Senhor Deus de Israel.

[[v23-24-16]]

^<<v23-24-16,16>>^ Dos confins da terra ouvimos cantar: Glória ao Justo. Mas eu digo: Emagreço, emagreço, ai de mim! os pérfidos tratam perfidamente; sim, os pérfidos tratam muito perfidamente.

[[v23-24-17]]

^<<v23-24-17,17>>^ O pavor, e a cova, e o laço vêm sobre ti, ó morador da terra.

[[v23-24-18]]

^<<v23-24-18,18>>^ Aquele que fugir da voz do pavor cairá na cova, e o que subir da cova o laço o prenderá; porque as janelas do alto se abriram, e os fundamentos da terra tremem.

[[v23-24-19]]

^<<v23-24-19,19>>^ A terra está de todo quebrantada, a terra está de todo fendida, a terra está de todo abalada.

[[v23-24-20]]

^<<v23-24-20,20>>^ A terra cambaleia como o ébrio, e balanceia como a rede de dormir; e a sua transgressão se torna pesada sobre ela, e ela cai, e nunca mais se levantará.

[[v23-24-21]]

^<<v23-24-21,21>>^ Naquele dia o Senhor castigará os exércitos do alto nas alturas, e os reis da terra sobre a terra.

[[v23-24-22]]

^<<v23-24-22,22>>^ E serão ajuntados como presos numa cova, e serão encerrados num cárcere; e serão punidos depois de muitos dias.

[[v23-24-23]]

^<<v23-24-23,23>>^ Então a lua se confundirá, e o sol se envergonhará, pois o Senhor dos exércitos reinará no monte Sião e em Jerusalém; e perante os seus anciãos manifestará a sua glória.

'''

xref:023-isaias/023-isaias-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaias/023-isaias-025.adoc#v23-25-0[Próximo Capítulo &#62;]