include::./index.adoc[]

[[v23-31-0]]
=== Isaías, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-31-1]]

^<<v23-31-1,1>>^ Ai dos que descem ao Egito a buscar socorro, e se estribam em cavalos, e têm confiança em carros, por serem muitos, e nos cavaleiros, por serem muito fortes; e não atentam para o Santo de Israel, e não buscam ao Senhor.

[[v23-31-2]]

^<<v23-31-2,2>>^ Todavia também ele é sábio, e fará vir o mal, e não retirará as suas palavras; mas levantar-se-á contra a casa dos malfeitores, e contra a ajuda dos que praticam a iniqüidade.

[[v23-31-3]]

^<<v23-31-3,3>>^ Ora os egípcios são homens, e não Deus; e os seus cavalos carne, e não espírito; e quando o Senhor estender a sua mão, tanto tropeçará quem dá auxílio, como cairá quem recebe auxílio, e todos juntamente serão consumidos.

[[v23-31-4]]

^<<v23-31-4,4>>^ Pois assim me diz o Senhor: Como o leão e o cachorro do leão rugem sobre a sua presa, e quando se convoca contra eles uma multidão de pastores não se espantam das suas vozes, nem se abstêm pelo seu alarido, assim o Senhor dos exércitos descerá, para pelejar sobre o monte Sião, e sobre o seu outeiro.

[[v23-31-5]]

^<<v23-31-5,5>>^ Como aves quando adejam, assim o Senhor dos exércitos protegerá a Jerusalém; ele a protegerá e a livrará, e, passando, a salvará.

[[v23-31-6]]

^<<v23-31-6,6>>^ Voltai-vos, filhos de Israel, para aquele contra quem vos tendes profundamente rebelado.

[[v23-31-7]]

^<<v23-31-7,7>>^ Pois naquele dia cada um lançará fora os seus ídolos de prata, e os seus ídolos de ouro, que vos fabricaram as vossas mãos para pecardes.

[[v23-31-8]]

^<<v23-31-8,8>>^ E o assírio cairá pela espada, não de varão; e a espada, não de homem, o consumirá; e fugirá perante a espada, e os seus mancebos serão sujeitos a trabalhos forçados.

[[v23-31-9]]

^<<v23-31-9,9>>^ A sua rocha passará de medo, e os seus oficiais em pânico desertarão da bandeira, diz o Senhor, cujo fogo está em Sião e em Jerusalém sua fornalha.

'''

xref:023-isaias/023-isaias-030.adoc#v23-30-0[&#60; Capítulo Anterior] | <<v23-31-0,Topo>> | xref:023-isaias/023-isaias-032.adoc#v23-32-0[Próximo Capítulo &#62;]