include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-19-1]]

^<<v23-19-1,1>>^ Profecia acerca do Egito. Eis que o Senhor vem cavalgando numa nuvem ligeira, e entra no Egito; e os ídolos do Egito estremecerão diante dele, e o coração dos egípcios se derreterá dentro de si.

[[v23-19-2]]

^<<v23-19-2,2>>^ Incitarei egípcios contra egípcios; e cada um pelejará contra o seu irmão, e cada um contra o seu próximo, cidade contra cidade, reino contra reino.

[[v23-19-3]]

^<<v23-19-3,3>>^ E o espírito dos egípcios se esvaecerá dentro deles; eu destruirei o seu conselho; e eles consultarão os seus ídolos, e encantadores, e necromantes e feiticeiros.

[[v23-19-4]]

^<<v23-19-4,4>>^ Pelo que entregarei os egípcios nas mãos de um senhor duro; e um rei rigoroso os dominará, diz o Senhor Deus dos exércitos.

[[v23-19-5]]

^<<v23-19-5,5>>^ e as águas do Nilo minguarão, e o rio se esgotará e secará.

[[v23-19-6]]

^<<v23-19-6,6>>^ Também os rios exalarão um fedor; diminuirão e secarão os canais do Egito; as canas e os juncos murcharão.

[[v23-19-7]]

^<<v23-19-7,7>>^ Os prados junto ao Nilo, ao longo das suas margens, sim, tudo o que foi semeado junto dele secará, será arrancado, e deixará de existir.

[[v23-19-8]]

^<<v23-19-8,8>>^ E os pescadores gemerão, e lamentarão todos os que lançam anzol ao Nilo, e desfalecerão os que estendem rede sobre as águas.

[[v23-19-9]]

^<<v23-19-9,9>>^ Envergonhar-se-ão os que trabalham em linho fino, e os que tecem pano branco.

[[v23-19-10]]

^<<v23-19-10,10>>^ E os que são as colunas do Egito serão esmagados, e todos os que trabalham, por salário serão entristecidos.

[[v23-19-11]]

^<<v23-19-11,11>>^ Na verdade estultos são os príncipes de Zoã; o conselho dos mais sábios conselheiros de Faraó se embruteceu. Como pois a Faraó direis: Sou filho de sábios, filho de reis antigos?

[[v23-19-12]]

^<<v23-19-12,12>>^ Onde estão agora os teus sábios? anunciem-te agora, e te façam saber o que o Senhor dos exércitos determinou contra o Egito.

[[v23-19-13]]

^<<v23-19-13,13>>^ Estultos tornaram-se os príncipes de Zoã, enganados estão os príncipes de Mênfis; fizeram errar o Egito, os que são a pedra de esquina das suas tribos.

[[v23-19-14]]

^<<v23-19-14,14>>^ O Senhor derramou no meio deles um espírito de confusão; e eles fizeram errar o Egito em todas as suas obras, como o bêbedo vai cambaleando no seu vômito.

[[v23-19-15]]

^<<v23-19-15,15>>^ E não haverá para o Egito coisa alguma que possa fazer cabeça ou cauda, ramo ou junco.

[[v23-19-16]]

^<<v23-19-16,16>>^ Naquele dia os egípcios serão como mulheres, e tremerão e temerão por vibrar o Senhor dos exércitos a sua mão contra eles.

[[v23-19-17]]

^<<v23-19-17,17>>^ E a terra de Judá será um espanto para o Egito; todo aquele a quem isso se anunciar se assombrará, por causa do propósito que o Senhor dos exércitos determinou contra eles.

[[v23-19-18]]

^<<v23-19-18,18>>^ Naquele dia haverá cinco cidades na terra do Egito que falem a língua de Canaã e façam juramento ao Senhor dos exércitos. Uma destas se chamará Cidade de destruição.

[[v23-19-19]]

^<<v23-19-19,19>>^ Naquele dia haverá um altar dedicado ao Senhor no meio da terra do Egito, e uma coluna se erigirá ao Senhor, na sua fronteira.

[[v23-19-20]]

^<<v23-19-20,20>>^ E servirá isso de sinal e de testemunho ao Senhor dos exércitos na terra do Egito; quando clamarem ao Senhor por causa dos opressores, ele lhes enviará um salvador, que os defenderá e os livrará.

[[v23-19-21]]

^<<v23-19-21,21>>^ E o Senhor se dará a conhecer ao Egito e os egípcios conhecerão ao Senhor naquele dia, e o adorarão com sacrifícios e ofertas, e farão votos ao Senhor, e os cumprirão.

[[v23-19-22]]

^<<v23-19-22,22>>^ E ferirá o Senhor aos egípcios; feri-los-á, mas também os curará; e eles se voltarão para o Senhor, que ouvirá as súplicas deles e os curará.

[[v23-19-23]]

^<<v23-19-23,23>>^ Naquele dia haverá estrada do Egito até a Assíria, e os assírios virão ao Egito, e os egípcios irão à Assíria; e os egípcios adorarão com os assírios.

[[v23-19-24]]

^<<v23-19-24,24>>^ Naquele dia Israel será o terceiro com os egípcios e os assírios, uma benção no meio da terra;

[[v23-19-25]]

^<<v23-19-25,25>>^ porquanto o Senhor dos exércitos os tem abençoado, dizendo: Bem-aventurado seja o Egito, meu povo, e a Assíria, obra de minhas mãos, e Israel, minha herança.

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]