include::./index.adoc[]

[[v23-63-0]]
=== Isaías, 63
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-63-1]]

^<<v23-63-1,1>>^ Quem é este, que vem de Edom, de Bozra, com vestiduras tintas de escarlate? este que é glorioso no seu traje, que marcha na plenitude da sua força? Sou eu, que falo em justiça, poderoso para salvar.

[[v23-63-2]]

^<<v23-63-2,2>>^ Por que está vermelha a tua vestidura, e as tuas vestes como as daquele que pisa no lagar?

[[v23-63-3]]

^<<v23-63-3,3>>^ Eu sozinho pisei no lagar, e dos povos ninguém houve comigo; eu os pisei na minha ira, e os esmaguei no meu furor, e o seu sangue salpicou as minhas vestes, e manchei toda a minha vestidura.

[[v23-63-4]]

^<<v23-63-4,4>>^ Porque o dia da vingança estava no meu coração, e o ano dos meus remidos é chegado.

[[v23-63-5]]

^<<v23-63-5,5>>^ Olhei, mas não havia quem me ajudasse; e admirei-me de não haver quem me sustivesse; pelo que o meu próprio braço me trouxe a vitória; e o meu furor é que me susteve.

[[v23-63-6]]

^<<v23-63-6,6>>^ Pisei os povos na minha ira, e os embriaguei no meu furor; e derramei sobre a terra o seu sangue.

[[v23-63-7]]

^<<v23-63-7,7>>^ Celebrarei as benignidades do Senhor, e os louvores do Senhor, consoante tudo o que o Senhor nos tem concedido, e a grande bondade para com a casa de Israel, bondade que ele lhes tem concedido segundo as suas misericórdias, e segundo a multidão das suas benignidades.

[[v23-63-8]]

^<<v23-63-8,8>>^ Porque dizia: Certamente eles são meu povo, filhos que não procederão com falsidade; assim ele se fez o seu Salvador.

[[v23-63-9]]

^<<v23-63-9,9>>^ Em toda a angústia deles foi ele angustiado, e o anjo da sua presença os salvou; no seu amor, e na sua compaixão ele os remiu; e os tomou, e os carregou todos os dias da antigüidade.

[[v23-63-10]]

^<<v23-63-10,10>>^ Eles, porém, se rebelaram, e contristaram o seu santo Espírito; pelo que se lhes tornou em inimigo, e ele mesmo pelejou contra eles.

[[v23-63-11]]

^<<v23-63-11,11>>^ Todavia se lembrou dos dias da antigüidade, de Moisés, e do seu povo, dizendo: Onde está aquele que os fez subir do mar com os pastores do seu rebanho? Onde está o que pôs no meio deles o seu santo Espírito?

[[v23-63-12]]

^<<v23-63-12,12>>^ Aquele que fez o seu braço glorioso andar à mão direita de Moisés? que fendeu as águas diante deles, para fazer para si um nome eterno?

[[v23-63-13]]

^<<v23-63-13,13>>^ Aquele que os guiou pelos abismos, como a um cavalo no deserto, de modo que nunca tropeçaram?

[[v23-63-14]]

^<<v23-63-14,14>>^ Como ao gado que desce ao vale, o Espírito do Senhor lhes deu descanso; assim guiaste o teu povo, para te fazeres um nome glorioso.

[[v23-63-15]]

^<<v23-63-15,15>>^ Atenta lá dos céus e vê, lá da tua santa e gloriosa habitação; onde estão o teu zelo e as tuas obras poderosas? A ternura do teu coração e as tuas misericórdias para comigo estancaram.

[[v23-63-16]]

^<<v23-63-16,16>>^ Mas tu és nosso Pai, ainda que Abraão não nos conhece, e Israel não nos reconhece; tu, ó Senhor, és nosso Pai; nosso Redentor desde a antigüidade é o teu nome.

[[v23-63-17]]

^<<v23-63-17,17>>^ Por que, ó Senhor, nos fazes errar dos teus caminhos? Por que endureces o nosso coração, para te não temermos? Faze voltar, por amor dos teus servos, as tribos da tua herança.

[[v23-63-18]]

^<<v23-63-18,18>>^ Só por um pouco de tempo o teu santo povo a possuiu; os nossos adversários pisaram o teu santuário.

[[v23-63-19]]

^<<v23-63-19,19>>^ Somos feitos como aqueles sobre quem tu nunca dominaste, e como os que nunca se chamaram pelo teu nome.

'''

xref:023-isaias/023-isaias-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaias/023-isaias-064.adoc#v23-64-0[Próximo Capítulo &#62;]