include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-23-1]]

^<<v23-23-1,1>>^ Oráculo acerca de Tiro. Uivai, navios de Társis, porque ela está desolada, a ponto de não haver nela casa nem abrigo; desde a terra de Quitim lhes foi isso revelado.

[[v23-23-2]]

^<<v23-23-2,2>>^ Calai-vos, moradores do litoral, vós a quem encheram os mercadores de Sidom, navegando pelo mar.

[[v23-23-3]]

^<<v23-23-3,3>>^ Por sobre grandes águas foi-lhe trazida a sua provisão, a semente de Sior, a ceifa do Nilo; e ela se tornou a feira das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Envergonha-te, ó Sidom; porque o mar falou, a fortaleza do mar disse: Eu não tive dores de parto, nem dei à luz, nem ainda criei mancebos, nem eduquei donzelas.

[[v23-23-5]]

^<<v23-23-5,5>>^ Quando a notícia chegar ao Egito, assim haverá dores quando se ouvirem as notícias de Tiro.

[[v23-23-6]]

^<<v23-23-6,6>>^ Passai a Társis; uivai, moradores do litoral.

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta, porventura, a vossa cidade alegre, cuja origem é dos dias antigos, cujos pés a levavam para longe a peregrinar?

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem formou este desígnio contra Tiro, distribuidora de coroas, cujos mercadores eram príncipes e cujos negociantes eram os mais nobres da terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O Senhor dos exércitos formou este desígnio para denegrir a soberba de toda a glória, e para reduzir à ignomínia os ilustres da terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Inunda como o Nilo a tua terra, ó filha de Társis; já não há mais o que te refreie.

[[v23-23-11]]

^<<v23-23-11,11>>^ Ele estendeu a sua mão sobre o mar, e abalou os reinos; o Senhor deu mandado contra Canaã, para destruir as suas fortalezas.

[[v23-23-12]]

^<<v23-23-12,12>>^ E disse: Não continuarás mais a te regozijar, ó oprimida donzela, filha de Sidom; levanta-te, passa a Chipre, e ainda ali não terás descanso.

[[v23-23-13]]

^<<v23-23-13,13>>^ Eis a terra dos caldeus! este é o povo, não foi a Assíria. Destinou a Tiro para as feras do deserto; levantaram as suas torres de sítio; derrubaram os palácios dela; a ruínas a reduziu.

[[v23-23-14]]

^<<v23-23-14,14>>^ Uivai, navios de Társis; porque está desolada a vossa fortaleza.

[[v23-23-15]]

^<<v23-23-15,15>>^ Naquele dia Tiro será posta em esquecimento por setenta anos, conforme os dias dum rei; mas depois de findos os setenta anos, sucederá a Tiro como se diz na canção da prostituta.

[[v23-23-16]]

^<<v23-23-16,16>>^ Toma a harpa, rodeia a cidade, ó prostituta, entregue ao esquecimento; toca bem, canta muitos cânticos, para que haja memória de ti.

[[v23-23-17]]

^<<v23-23-17,17>>^ No fim de setenta anos o Senhor visitará a Tiro, e ela tornará à sua ganância de prostituta, e fornicará com todos os reinos que há sobre a face da terra.

[[v23-23-18]]

^<<v23-23-18,18>>^ E será consagrado ao Senhor o seu comércio e a sua ganância de prostituta; não se entesourará, nem se guardará; mas o seu comércio será para os que habitam perante o Senhor, para que comam suficientemente; e tenham vestimenta esplêndida.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]