include::./index.adoc[]

[[v23-32-0]]
=== Isaías, 32
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-32-1]]

^<<v23-32-1,1>>^ Eis que reinará um rei com justiça, e com retidão governarão príncipes.

[[v23-32-2]]

^<<v23-32-2,2>>^ um varão servirá de abrigo contra o vento, e um refúgio contra a tempestade, como ribeiros de águas em lugares secos, e como a sombra duma grande penha em terra sedenta.

[[v23-32-3]]

^<<v23-32-3,3>>^ Os olhos dos que vêem não se ofuscarão, e os ouvidos dos que ouvem escutarão.

[[v23-32-4]]

^<<v23-32-4,4>>^ O coração dos imprudentes entenderá o conhecimento, e a língua dos gagos estará pronta para falar distintamente.

[[v23-32-5]]

^<<v23-32-5,5>>^ Ao tolo nunca mais se chamará nobre, e do avarento nunca mais se dirá que é generoso.

[[v23-32-6]]

^<<v23-32-6,6>>^ Pois o tolo fala tolices, e o seu coração trama iniqüidade, para cometer profanação e proferir mentiras contra o Senhor, para deixar com fome o faminto e fazer faltar a bebida ao sedento.

[[v23-32-7]]

^<<v23-32-7,7>>^ Também as maquinações do fraudulento são más; ele maquina invenções malignas para destruir os mansos com palavras falsas, mesmo quando o pobre fala o que é reto.

[[v23-32-8]]

^<<v23-32-8,8>>^ Mas o nobre projeta coisas nobres; e nas coisas nobres persistirá.

[[v23-32-9]]

^<<v23-32-9,9>>^ Levantai-vos, mulheres que estais sossegadas e ouvi a minha voz; e vós, filhas, que estais , tão seguras, inclinai os ouvidos às minhas palavras.

[[v23-32-10]]

^<<v23-32-10,10>>^ Num ano e dias vireis a ser perturbadas, ó mulheres que tão seguras estais; pois a vindima falhará, e a colheita não virá.

[[v23-32-11]]

^<<v23-32-11,11>>^ Tremei, mulheres que estais sossegadas, e turbai-vos, vós que estais tão seguras; despi-vos e ponde-vos nuas, e cingi com saco os vossos lombos.

[[v23-32-12]]

^<<v23-32-12,12>>^ Batei nos peitos pelos campos aprazíveis, e pela vinha frutífera;

[[v23-32-13]]

^<<v23-32-13,13>>^ pela terra do meu povo, que produz espinheiros e sarças, e por todas as casas de alegria, na cidade jubilosa.

[[v23-32-14]]

^<<v23-32-14,14>>^ Porque o palácio será abandonado, a cidade populosa ficará deserta; e o outeiro e a torre da guarda servirão de cavernas para sempre, para alegria dos asnos monteses, e para pasto dos rebanhos;

[[v23-32-15]]

^<<v23-32-15,15>>^ até que se derrame sobre nós o espírito lá do alto, e o deserto se torne em campo fértil, e o campo fértil seja reputado por um bosque.

[[v23-32-16]]

^<<v23-32-16,16>>^ Então o juízo habitará no deserto, e a justiça morará no campo fértil.

[[v23-32-17]]

^<<v23-32-17,17>>^ E a obra da justiça será paz; e o efeito da justiça será sossego e segurança para sempre.

[[v23-32-18]]

^<<v23-32-18,18>>^ O meu povo habitará em morada de paz, em moradas bem seguras, e em lugares quietos de descanso.

[[v23-32-19]]

^<<v23-32-19,19>>^ Mas haverá saraiva quando cair o bosque; e a cidade será inteiramente abatida.

[[v23-32-20]]

^<<v23-32-20,20>>^ Bem-aventurados sois vós os que semeais junto a todas as águas, que deixais livres os pés do boi e do jumento.

'''

xref:023-isaias/023-isaias-031.adoc#v23-31-0[&#60; Capítulo Anterior] | <<v23-32-0,Topo>> | xref:023-isaias/023-isaias-033.adoc#v23-33-0[Próximo Capítulo &#62;]