include::./index.adoc[]

[[v23-40-0]]
=== Isaías, 40
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-40-1]]

^<<v23-40-1,1>>^ Consolai, consolai o meu povo, diz o vosso Deus.

[[v23-40-2]]

^<<v23-40-2,2>>^ Falai benignamente a Jerusalém, e bradai-lhe que já a sua malícia é acabada, que a sua iniqüidade está expiada e que já recebeu em dobro da mão do Senhor, por todos os seus pecados.

[[v23-40-3]]

^<<v23-40-3,3>>^ Eis a voz do que clama: Preparai no deserto o caminho do Senhor; endireitai no ermo uma estrada para o nosso Deus.

[[v23-40-4]]

^<<v23-40-4,4>>^ Todo vale será levantado, e será abatido todo monte e todo outeiro; e o terreno acidentado será nivelado, e o que é escabroso, aplanado.

[[v23-40-5]]

^<<v23-40-5,5>>^ A glória do Senhor se revelará; e toda a carne juntamente a verá; pois a boca do Senhor o disse.

[[v23-40-6]]

^<<v23-40-6,6>>^ Uma voz diz: Clama. Respondi eu: Que hei de clamar? Toda a carne é erva, e toda a sua beleza como a flor do campo.

[[v23-40-7]]

^<<v23-40-7,7>>^ Seca-se a erva, e murcha a flor, soprando nelas o hálito do Senhor. Na verdade o povo é erva.

[[v23-40-8]]

^<<v23-40-8,8>>^ Seca-se a erva, e murcha a flor; mas a palavra de nosso Deus subsiste eternamente.

[[v23-40-9]]

^<<v23-40-9,9>>^ Tu, anunciador de boas-novas a Sião, sobe a um monte alto. Tu, anunciador de boas-novas a Jerusalém, levanta a tua voz fortemente; levanta-a, não temas, e dize às cidades de Judá: Eis aqui está o vosso Deus.

[[v23-40-10]]

^<<v23-40-10,10>>^ Eis que o Senhor Deus virá com poder, e o seu braço dominará por ele; eis que o seu galardão está com ele, e a sua recompensa diante dele.

[[v23-40-11]]

^<<v23-40-11,11>>^ Como pastor ele apascentará o seu rebanho; entre os seus braços recolherá os cordeirinhos, e os levará no seu regaço; as que amamentam, ele as guiará mansamente.

[[v23-40-12]]

^<<v23-40-12,12>>^ Quem mediu com o seu punho as águas, e tomou a medida dos céus aos palmos, e recolheu numa medida o pó da terra e pesou os montes com pesos e os outeiros em balanças,

[[v23-40-13]]

^<<v23-40-13,13>>^ Quem guiou o Espírito do Senhor, ou, como seu conselheiro o ensinou?

[[v23-40-14]]

^<<v23-40-14,14>>^ Com quem tomou ele conselho, para que lhe desse entendimento, e quem lhe mostrou a vereda do juízo? quem lhe ensinou conhecimento, e lhe mostrou o caminho de entendimento?

[[v23-40-15]]

^<<v23-40-15,15>>^ Eis que as nações são consideradas por ele como a gota dum balde, e como o pó miúdo das balanças; eis que ele levanta as ilhas como a uma coisa pequeníssima.

[[v23-40-16]]

^<<v23-40-16,16>>^ Nem todo o Líbano basta para o fogo, nem os seus animais bastam para um holocausto.

[[v23-40-17]]

^<<v23-40-17,17>>^ Todas as nações são como nada perante ele; são por ele reputadas menos do que nada, e como coisa vã.

[[v23-40-18]]

^<<v23-40-18,18>>^ A quem, pois, podeis assemelhar a Deus? ou que figura podeis comparar a ele?

[[v23-40-19]]

^<<v23-40-19,19>>^ Quanto ao ídolo, o artífice o funde, e o ourives o cobre de ouro, e forja cadeias de prata para ele.

[[v23-40-20]]

^<<v23-40-20,20>>^ O empobrecido, que não pode oferecer tanto, escolhe madeira que não apodrece; procura para si um artífice perito, para gravar uma imagem que não se pode mover.

[[v23-40-21]]

^<<v23-40-21,21>>^ Porventura não sabeis? porventura não ouvis? ou desde o princípio não se vos notificou isso mesmo? ou não tendes entendido desde a fundação da terra?

[[v23-40-22]]

^<<v23-40-22,22>>^ E ele o que está assentado sobre o círculo da terra, cujos moradores são para ele como gafanhotos; é ele o que estende os céus como cortina, e o desenrola como tenda para nela habitar.

[[v23-40-23]]

^<<v23-40-23,23>>^ E ele o que reduz a nada os príncipes, e torna em coisa vã os juízes da terra.

[[v23-40-24]]

^<<v23-40-24,24>>^ Na verdade, mal se tem plantado, mal se tem semeado e mal se tem arraigado na terra o seu tronco, quando ele sopra sobre eles, e secam-se, e a tempestade os leva como à pragana.

[[v23-40-25]]

^<<v23-40-25,25>>^ A quem, pois, me comparareis, para que eu lhe seja semelhante? diz o Santo.

[[v23-40-26]]

^<<v23-40-26,26>>^ Levantai ao alto os vossos olhos, e vede: quem criou estas coisas? Foi aquele que faz sair o exército delas segundo o seu número; ele as chama a todas pelos seus nomes; por ser ele grande em força, e forte em poder, nenhuma faltará.

[[v23-40-27]]

^<<v23-40-27,27>>^ Por que dizes, ó Jacó, e falas, ó Israel: O meu caminho está escondido ao Senhor, e o meu juízo passa despercebido ao meu Deus?

[[v23-40-28]]

^<<v23-40-28,28>>^ Não sabes, não ouviste que o eterno Deus, o Senhor, o Criador dos confins da terra, não se cansa nem se fatiga? E inescrutável o seu entendimento.

[[v23-40-29]]

^<<v23-40-29,29>>^ Ele dá força ao cansado, e aumenta as forças ao que não tem nenhum vigor.

[[v23-40-30]]

^<<v23-40-30,30>>^ Os jovens se cansarão e se fatigarão, e os mancebos cairão,

[[v23-40-31]]

^<<v23-40-31,31>>^ mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias; correrão, e não se cansarão; andarão, e não se fatigarão.

'''

xref:023-isaias/023-isaias-039.adoc#v23-39-0[&#60; Capítulo Anterior] | <<v23-40-0,Topo>> | xref:023-isaias/023-isaias-041.adoc#v23-41-0[Próximo Capítulo &#62;]