include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-27-1]]

^<<v23-27-1,1>>^ Naquele dia o Senhor castigará com a sua dura espada, grande e forte, o leviatã, a serpente fugitiva, e o leviatã, a serpente tortuosa; e matará o dragão, que está no mar.

[[v23-27-2]]

^<<v23-27-2,2>>^ Naquele dia haverá uma vinha deliciosa; cantai a seu respeito.

[[v23-27-3]]

^<<v23-27-3,3>>^ Eu, o Senhor, a guardo, e a cada momento a regarei; para que ninguém lhe faça dano, de noite e de dia a guardarei.

[[v23-27-4]]

^<<v23-27-4,4>>^ Não há indignação em mim; oxalá que fossem ordenados diante de mim em guerra sarças e espinheiros! eu marcharia contra eles e juntamente os queimaria.

[[v23-27-5]]

^<<v23-27-5,5>>^ Ou, então, busquem o meu refúgio, e façai, paz comigo; sim, façam paz comigo.

[[v23-27-6]]

^<<v23-27-6,6>>^ Dias virão em que Jacó lançará raízes; Israel florescerá e brotará; e eles encherão de fruto a face do mundo.

[[v23-27-7]]

^<<v23-27-7,7>>^ Porventura feriu-os o Senhor como feriu aos que os feriram? ou matou-os ele assim como matou aos que por eles foram mortos?

[[v23-27-8]]

^<<v23-27-8,8>>^ Com medida contendeste com eles, quando os rejeitaste; ele a removeu com o seu vento forte, no tempo do vento leste.

[[v23-27-9]]

^<<v23-27-9,9>>^ Por isso se expiará a iniqüidade de Jacó; e este será todo o fruto da remoção do seu pecado: ele fará todas as pedras do altar como pedras de cal feitas em pedaços, de modo que os aserins e as imagens do sol não poderão ser mais levantados.

[[v23-27-10]]

^<<v23-27-10,10>>^ porque a cidade fortificada está solitária, uma habitação rejeitada e abandonada como um deserto; ali pastarão os bezerros, ali também se deitarão e devorarão os seus ramos.

[[v23-27-11]]

^<<v23-27-11,11>>^ Quando os seus ramos se secam, são quebrados; vêm as mulheres e lhes ateiam fogo; porque este povo não é povo de entendimento; por isso aquele que o fez não se compadecerá dele, e aquele que o formou não lhe mostrará nenhum favor.

[[v23-27-12]]

^<<v23-27-12,12>>^ Naquele dia o Senhor padejará o seu trigo desde as correntes do Rio, até o ribeiro do Egito; e vós, ó filhos de Israel, sereis colhidos um a um.

[[v23-27-13]]

^<<v23-27-13,13>>^ E naquele dia se tocará uma grande trombeta; e os que andavam perdidos pela terra da Assíria, e os que foram desterrados para a terra do Egito tornarão a vir; e adorarão ao Senhor no monte santo em Jerusalém.

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]