include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-34-1]]

^<<v23-34-1,1>>^ Chegai-vos, nações, para ouvir, e vós, povos, escutai; ouça a terra, e a sua plenitude, o mundo e tudo quanto ele produz.

[[v23-34-2]]

^<<v23-34-2,2>>^ Porque a indignação do Senhor está sobre todas as nações, e o seu furor sobre todo o exército delas; ele determinou a sua destruição, entregou-as à matança.

[[v23-34-3]]

^<<v23-34-3,3>>^ E os seus mortos serão arrojados, e dos seus cadáveres subirá o mau cheiro; e com o seu sangue os montes se derreterão.

[[v23-34-4]]

^<<v23-34-4,4>>^ E todo o exército dos céus se dissolverá, e o céu se enrolará como um livro; e todo o seu exército desvanecerá, como desvanece a folha da vide e da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ Pois a minha espada se embriagou no céu; eis que sobre Edom descerá, e sobre o povo do meu anátema, para exercer juízo.

[[v23-34-6]]

^<<v23-34-6,6>>^ A espada do Senhor está cheia de sangue, está cheia de gordura, de sangue de cordeiros e de bodes, da gordura dos rins de carneiros; porque o Senhor tem sacrifício em Bozra, e grande matança na terra de Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ E os bois selvagens cairão com eles, e os novilhos com os touros; e a sua terra embriagar-se-á de sangue, e o seu pó se engrossará de gordura.

[[v23-34-8]]

^<<v23-34-8,8>>^ Pois o Senhor tem um dia de vingança, um ano de retribuições pela causa de Sião.

[[v23-34-9]]

^<<v23-34-9,9>>^ E os ribeiros de Edom transformar-se-ão em pez, e o seu solo em enxofre, e a sua terra tornar-se-á em pez ardente.

[[v23-34-10]]

^<<v23-34-10,10>>^ Nem de noite nem de dia se apagará; para sempre a sua fumaça subirá; de geração em geração será assolada; pelos séculos dos séculos ninguém passará por ela.

[[v23-34-11]]

^<<v23-34-11,11>>^ Mas o pelicano e o ouriço a possuirão; a coruja e o corvo nela habitarão; e ele estenderá sobre ela o cordel de confusão e o prumo de vaidade.

[[v23-34-12]]

^<<v23-34-12,12>>^ Eles chamarão ao reino os seus nobres, mas nenhum haverá; e todos os seus príncipes não serão coisa nenhuma.

[[v23-34-13]]

^<<v23-34-13,13>>^ E crescerão espinhos nos seus palácios, urtigas e cardos nas suas fortalezas; e será uma habitação de chacais, um sítio para avestruzes.

[[v23-34-14]]

^<<v23-34-14,14>>^ E as feras do deserto se encontrarão com hienas; e o sátiro clamará ao seu companheiro; e Lilite pousará ali, e achará lugar de repouso para si.

[[v23-34-15]]

^<<v23-34-15,15>>^ Ali fará a coruja o seu ninho, e porá os seus ovos, e aninhará os seus filhotes, e os recolherá debaixo da sua sombra; também ali se ajuntarão os abutres, cada fêmea com o seu companheiro.

[[v23-34-16]]

^<<v23-34-16,16>>^ Buscai no livro do Senhor, e lede: nenhuma destas criaturas faltará, nenhuma será privada do seu companheiro; porque é a boca dele que o ordenou, e é o seu espírito que os ajuntou.

[[v23-34-17]]

^<<v23-34-17,17>>^ Ele mesmo lançou as sortes por eles, e a sua mão lhes repartiu a terra com o cordel; para sempre a possuirão; de geração em geração habitarão nela.

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]