include::./index.adoc[]

[[v23-52-0]]
=== Isaías, 52
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-52-1]]

^<<v23-52-1,1>>^ Desperta, desperta, veste-te da tua fortaleza, Sião; veste-te dos teus vestidos formosos, ó Jerusalém, cidade santa; porque nunca mais entrará em ti nem incircunciso nem imundo.

[[v23-52-2]]

^<<v23-52-2,2>>^ Sacode-te do pó; levanta-te, e assenta-te, ó Jerusalém; solta-te das ataduras de teu pescoço, ó cativa filha de Sião.

[[v23-52-3]]

^<<v23-52-3,3>>^ Porque assim diz o Senhor: Por nada fostes vendidos; e sem dinheiro sereis resgatados.

[[v23-52-4]]

^<<v23-52-4,4>>^ Pois assim diz o Senhor Deus: O meu povo desceu no princípio ao Egito, para peregrinar lá, e a Assíria sem razão o oprimiu.

[[v23-52-5]]

^<<v23-52-5,5>>^ E agora, que acho eu aqui? diz o Senhor, pois que o meu povo foi tomado sem nenhuma razão, os seus dominadores dão uivos sobre ele, diz o Senhor; e o meu nome é blasfemado incessantemente o dia todo!

[[v23-52-6]]

^<<v23-52-6,6>>^ Portanto o meu povo saberá o meu nome; portanto saberá naquele dia que sou eu o que falo; eis-me aqui.

[[v23-52-7]]

^<<v23-52-7,7>>^ Quão formosos sobre os montes são os pés do que anuncia as boas-novas, que proclama a paz, que anuncia coisas boas, que proclama a salvação, que diz a Sião: O teu Deus reina!

[[v23-52-8]]

^<<v23-52-8,8>>^ Eis a voz dos teus atalaias! eles levantam a voz, juntamente exultam; porque de perto contemplam a volta do Senhor a Sião.

[[v23-52-9]]

^<<v23-52-9,9>>^ Clamai cantando, exultai juntamente, desertos de Jerusalém; porque o Senhor consolou o seu povo, remiu a Jerusalém.

[[v23-52-10]]

^<<v23-52-10,10>>^ O Senhor desnudou o seu santo braço à vista de todas as nações; e todos os confins da terra verão a salvação do nosso Deus.

[[v23-52-11]]

^<<v23-52-11,11>>^ Retirai-vos, retirai-vos, saí daí, não toqueis coisa imunda; saí do meio dela, purificai-vos, os que levais os vasos do Senhor.

[[v23-52-12]]

^<<v23-52-12,12>>^ Pois não saireis apressadamente, nem ireis em fuga; porque o Senhor irá diante de vós, e o Deus de Israel será a vossa retaguarda.

[[v23-52-13]]

^<<v23-52-13,13>>^ Eis que o meu servo procederá com prudência; será exaltado, e elevado, e mui sublime.

[[v23-52-14]]

^<<v23-52-14,14>>^ Como pasmaram muitos à vista dele &#123;pois o seu aspecto estava tão desfigurado que não era o de um homem, e a sua figura não era a dos filhos dos homens&#125;,

[[v23-52-15]]

^<<v23-52-15,15>>^ assim ele espantará muitas nações; por causa dele reis taparão a boca; pois verão aquilo que não se lhes havia anunciado, e entenderão aquilo que não tinham ouvido.

'''

xref:023-isaias/023-isaias-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaias/023-isaias-053.adoc#v23-53-0[Próximo Capítulo &#62;]