include::./index.adoc[]

[[v23-61-0]]
=== Isaías, 61
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-61-1]]

^<<v23-61-1,1>>^ O Espírito do Senhor Deus está sobre mim, porque o Senhor me ungiu para pregar boas-novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos, e a abertura de prisão aos presos;

[[v23-61-2]]

^<<v23-61-2,2>>^ a apregoar o ano aceitável do Senhor e o dia da vingança do nosso Deus; a consolar todos os tristes;

[[v23-61-3]]

^<<v23-61-3,3>>^ a ordenar acerca dos que choram em Sião que se lhes dê uma grinalda em vez de cinzas, óleo de gozo em vez de pranto, vestidos de louvor em vez de espírito angustiado; a fim de que se chamem árvores de justiça, plantação do Senhor, para que ele seja glorificado.

[[v23-61-4]]

^<<v23-61-4,4>>^ E eles edificarão as antigas ruínas, levantarão as desolações de outrora, e restaurarão as cidades assoladas, as desolações de muitas gerações.

[[v23-61-5]]

^<<v23-61-5,5>>^ E haverá estrangeiros, que apascentarão os vossos rebanhos; e estranhos serão os vossos lavradores e os vossos vinheiros.

[[v23-61-6]]

^<<v23-61-6,6>>^ Mas vós sereis chamados sacerdotes do Senhor, e vos chamarão ministros de nosso Deus; comereis as riquezas das nações, e na sua glória vos gloriareis.

[[v23-61-7]]

^<<v23-61-7,7>>^ Em lugar da vossa vergonha, haveis de ter dupla honra; e em lugar de opróbrio exultareis na vossa porção; por isso na sua terra possuirão o dobro, e terão perpétua alegria.

[[v23-61-8]]

^<<v23-61-8,8>>^ Pois eu, o Senhor, amo o juízo, aborreço o roubo e toda injustiça; fielmente lhes darei sua recompensa, e farei com eles um pacto eterno.

[[v23-61-9]]

^<<v23-61-9,9>>^ E a sua posteridade será conhecida entre as nações, e os seus descendentes no meio dos povos; todos quantos os virem os reconhecerão como descendência bendita do Senhor.

[[v23-61-10]]

^<<v23-61-10,10>>^ Regozijar-me-ei muito no Senhor, a minha alma se alegrará no meu Deus, porque me vestiu de vestes de salvação, cobriu-me com o manto de justiça, como noivo que se adorna com uma grinalda, e como noiva que se enfeita com as suas jóias.

[[v23-61-11]]

^<<v23-61-11,11>>^ Porque, como a terra produz os seus renovos, e como o horto faz brotar o que nele se semeia, assim o Senhor Deus fará brotar a justiça e o louvor perante todas as nações.

'''

xref:023-isaias/023-isaias-060.adoc#v23-60-0[&#60; Capítulo Anterior] | <<v23-61-0,Topo>> | xref:023-isaias/023-isaias-062.adoc#v23-62-0[Próximo Capítulo &#62;]