include::./index.adoc[]

[[v23-44-0]]
=== Isaías, 44
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-44-1]]

^<<v23-44-1,1>>^ Agora, pois, ouve, ó Jacó, servo meu, ó Israel, a quem escolhi.

[[v23-44-2]]

^<<v23-44-2,2>>^ Assim diz o Senhor que te criou e te formou desde o ventre, e que te ajudará: Não temas, ó Jacó, servo meu, e tu, Jesurum, a quem escolhi.

[[v23-44-3]]

^<<v23-44-3,3>>^ Porque derramarei água sobre o sedento, e correntes sobre a terra seca; derramarei o meu Espírito sobre a tua posteridade, e a minha bênção sobre a tua descendência;

[[v23-44-4]]

^<<v23-44-4,4>>^ e brotarão como a erva, como salgueiros junto às correntes de águas.

[[v23-44-5]]

^<<v23-44-5,5>>^ Este dirá: Eu sou do Senhor; e aquele se chamará do nome de Jacó; e aquele outro escreverá na própria mão: Eu sou do Senhor; e por sobrenome tomará o nome de Israel.

[[v23-44-6]]

^<<v23-44-6,6>>^ Assim diz o Senhor, Rei de Israel, seu Redentor, o Senhor dos exércitos: Eu sou o primeiro, e eu sou o último, e fora de mim não há Deus.

[[v23-44-7]]

^<<v23-44-7,7>>^ Quem há como eu? Que o proclame e o exponha perante mim! Quem tem anunciado desde os tempos antigos as coisas vindouras? Que nos anuncie as que ainda hão de vir.

[[v23-44-8]]

^<<v23-44-8,8>>^ Não vos assombreis, nem temais; porventura não vo-lo declarei há muito tempo, e não vo-lo anunciei? Vós sois as minhas testemunhas! Acaso há outro Deus além de mim? Não, não há Rocha; não conheço nenhuma.

[[v23-44-9]]

^<<v23-44-9,9>>^ Todos os artífices de imagens esculpidas são nada; e as suas coisas mais desejáveis são de nenhum préstimo; e suas próprias testemunhas nada vêem nem entendem, para que eles sejam confundidos.

[[v23-44-10]]

^<<v23-44-10,10>>^ Quem forma um deus, e funde uma imagem de escultura, que é de nenhum préstimo?

[[v23-44-11]]

^<<v23-44-11,11>>^ Eis que todos os seus seguidores ficarão confundidos; e os artífices são apenas homens; ajuntem-se todos, e se apresentem; assombrar-se-ão, e serão juntamente confundidos.

[[v23-44-12]]

^<<v23-44-12,12>>^ O ferreiro faz o machado, e trabalha nas brasas, e o forja com martelos, e o forja com o seu forte braço; ademais ele tem fome, e a sua força falta; não bebe água, e desfalece.

[[v23-44-13]]

^<<v23-44-13,13>>^ O carpinteiro estende a régua sobre um pau, e com lápis esboça um deus; dá-lhe forma com o cepilho; torna a esboçá-lo com o compasso; finalmente dá-lhe forma à semelhança dum homem, segundo a beleza dum homem, para habitar numa casa.

[[v23-44-14]]

^<<v23-44-14,14>>^ Um homem corta para si cedros, ou toma um cipreste, ou um carvalho; assim escolhe dentre as árvores do bosque; planta uma faia, e a chuva a faz crescer.

[[v23-44-15]]

^<<v23-44-15,15>>^ Então ela serve ao homem para queimar: da madeira toma uma parte e com isso se aquenta; acende um fogo e assa o pão; também faz um deus e se prostra diante dele; fabrica uma imagem de escultura, e se ajoelha diante dela.

[[v23-44-16]]

^<<v23-44-16,16>>^ Ele queima a metade no fogo, e com isso prepara a carne para comer; faz um assado, e dele se farta; também se aquenta, e diz: Ah! já me aquentei, já vi o fogo.

[[v23-44-17]]

^<<v23-44-17,17>>^ Então do resto faz para si um deus, uma imagem de escultura; ajoelha-se diante dela, prostra-se, e lhe dirige a sua súplica dizendo: Livra-me porquanto tu és o meu deus.

[[v23-44-18]]

^<<v23-44-18,18>>^ Nada sabem, nem entendem; porque se lhe untaram os olhos, para que não vejam, e o coração, para que não entendam.

[[v23-44-19]]

^<<v23-44-19,19>>^ E nenhum deles reflete; e não têm conhecimento nem entendimento para dizer: Metade queimei no fogo, e assei pão sobre as suas brasas; fiz um assado e dele comi; e faria eu do resto uma abominação? ajoelhar-me-ei ao que saiu duma árvore?

[[v23-44-20]]

^<<v23-44-20,20>>^ Apascenta-se de cinza. O seu coração enganado o desviou, de maneira que não pode livrar a sua alma, nem dizer: Porventura não há uma mentira na minha mão direita?

[[v23-44-21]]

^<<v23-44-21,21>>^ Lembra-te destas coisas, ó Jacó, sim, tu ó Israel; porque tu és meu servo! Eu te formei, meu servo és tu; ó Israel não te esquecerei de ti.

[[v23-44-22]]

^<<v23-44-22,22>>^ Apagai as tuas transgressões como a névoa, e os teus pecados como a nuvem; torna-te para mim, porque eu te remi.

[[v23-44-23]]

^<<v23-44-23,23>>^ Cantai alegres, vós, ó céus, porque o Senhor fez isso; exultai vós, as partes mais baixas da terra; vós, montes, retumbai com júbilo; também vós, bosques, e todas as árvores em vós; porque o Senhor remiu a Jacó, e se glorificará em Israel.

[[v23-44-24]]

^<<v23-44-24,24>>^ Assim diz o Senhor, teu Redentor, e que te formou desde o ventre: Eu sou o Senhor que faço todas as coisas, que sozinho estendi os céus, e espraiei a terra &#123;quem estava comigo?&#125;;

[[v23-44-25]]

^<<v23-44-25,25>>^ que desfaço os sinais dos profetas falsos, e torno loucos os adivinhos, que faço voltar para trás os sábios, e converto em loucura a sua ciência;

[[v23-44-26]]

^<<v23-44-26,26>>^ sou eu que confirmo a palavra do meu servo, e cumpro o conselho dos meus mensageiros; que digo de Jerusalém: Ela será habitada; e das cidades de Judá: Elas serão edificadas, e eu levantarei as suas ruínas;

[[v23-44-27]]

^<<v23-44-27,27>>^ que digo ao abismo: Seca-te, eu secarei os teus rios;

[[v23-44-28]]

^<<v23-44-28,28>>^ que digo de Ciro: Ele é meu pastor, e cumprira tudo o que me apraz; de modo que ele também diga de Jerusalém: Ela será edificada, e o fundamento do templo será lançado.

'''

xref:023-isaias/023-isaias-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaias/023-isaias-045.adoc#v23-45-0[Próximo Capítulo &#62;]