include::./index.adoc[]

[[v23-46-0]]
=== Isaías, 46
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-46-1]]

^<<v23-46-1,1>>^ Bel se encurva, Nebo se abaixa; os seus ídolos são postos sobre os animais, sobre as bestas; essas cargas que costumáveis levar são pesadas para as bestas já cansadas.

[[v23-46-2]]

^<<v23-46-2,2>>^ Eles juntamente se abaixam e se encurvam; não podem salvar a carga, mas eles mesmos vão para o cativeiro.

[[v23-46-3]]

^<<v23-46-3,3>>^ Ouvi-me, ó casa de Jacó, e todo o resto da casa de Israel, vós que por mim tendes sido carregados desde o ventre, que tendes sido levados desde a madre.

[[v23-46-4]]

^<<v23-46-4,4>>^ Até a vossa velhice eu sou o mesmo, e ainda até as cãs eu vos carregarei; eu vos criei, e vos levarei; sim, eu vos carregarei e vos livrarei.

[[v23-46-5]]

^<<v23-46-5,5>>^ A quem me assemelhareis, e com quem me igualareis e me comparareis, para que sejamos semelhantes?

[[v23-46-6]]

^<<v23-46-6,6>>^ Os que prodigalizam o ouro da bolsa, e pesam a prata nas balanças, assalariam o ourives, e ele faz um deus; e diante dele se prostram e adora,

[[v23-46-7]]

^<<v23-46-7,7>>^ Eles o tomam sobre os ombros, o levam, e o colocam no seu lugar, e ali permanece; do seu lugar não se pode mover; e, se recorrem a ele, resposta nenhuma dá, nem livra alguém da sua tribulação.

[[v23-46-8]]

^<<v23-46-8,8>>^ Lembrai-vos, disto, e considerai; trazei-o à memória, ó transgressores.

[[v23-46-9]]

^<<v23-46-9,9>>^ Lembrai-vos das coisas passadas desde a antigüidade; que eu sou Deus, e não há outro; eu sou Deus, e não há outro semelhante a mim;

[[v23-46-10]]

^<<v23-46-10,10>>^ que anuncio o fim desde o princípio, e desde a antigüidade as coisas que ainda não sucederam; que digo: O meu conselho subsistirá, e farei toda a minha vontade;

[[v23-46-11]]

^<<v23-46-11,11>>^ chamando do oriente uma ave de rapina, e dum país remoto o homem do meu conselho; sim, eu o disse, e eu o cumprirei; formei esse propósito, e também o executarei.

[[v23-46-12]]

^<<v23-46-12,12>>^ Ouvi-me, ó duros de coração, os que estais longe da justiça.

[[v23-46-13]]

^<<v23-46-13,13>>^ Faço chegar a minha justiça; e ela não está longe, e a minha salvação não tardará; mas estabelecerei a salvação em Sião, e em Israel a minha glória.

'''

xref:023-isaias/023-isaias-045.adoc#v23-45-0[&#60; Capítulo Anterior] | <<v23-46-0,Topo>> | xref:023-isaias/023-isaias-047.adoc#v23-47-0[Próximo Capítulo &#62;]