include::./index.adoc[]

[[v23-35-0]]
=== Isaías, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-35-1]]

^<<v23-35-1,1>>^ O deserto e a terra sedenta se regozijarão; e o ermo exultará e florescerá;

[[v23-35-2]]

^<<v23-35-2,2>>^ como o narciso florescerá abundantemente, e também exultará de júbilo e romperá em cânticos; dar-se-lhe-á a glória do Líbano, a excelência do Carmelo e Sarom; eles verão a glória do Senhor, a majestade do nosso Deus.

[[v23-35-3]]

^<<v23-35-3,3>>^ Fortalecei as mãos fracas, e firmai os joelhos trementes.

[[v23-35-4]]

^<<v23-35-4,4>>^ Dizei aos turbados de coração: Sede fortes, não temais; eis o vosso Deus! com vingança virá, sim com a recompensa de Deus; ele virá, e vos salvará.

[[v23-35-5]]

^<<v23-35-5,5>>^ Então os olhos dos cegos serão abertos, e os ouvidos dos surdos se desimpedirão.

[[v23-35-6]]

^<<v23-35-6,6>>^ Então o coxo saltará como o cervo, e a língua do mudo cantará de alegria; porque águas arrebentarão no deserto e ribeiros no ermo.

[[v23-35-7]]

^<<v23-35-7,7>>^ E a miragem tornar-se-á em lago, e a terra sedenta em mananciais de águas; e nas habitações em que jaziam os chacais haverá erva com canas e juncos.

[[v23-35-8]]

^<<v23-35-8,8>>^ E ali haverá uma estrada, um caminho que se chamará o caminho santo; o imundo não passará por ele, mas será para os remidos. Os caminhantes, até mesmo os loucos, nele não errarão.

[[v23-35-9]]

^<<v23-35-9,9>>^ Ali não haverá leão, nem animal feroz subirá por ele, nem se achará nele; mas os redimidos andarão por ele.

[[v23-35-10]]

^<<v23-35-10,10>>^ E os resgatados do Senhor voltarão; e virão a Sião com júbilo, e alegria eterna haverá sobre as suas cabeças; gozo e alegria alcançarão, e deles fugirá a tristeza e o gemido.

'''

xref:023-isaias/023-isaias-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaias/023-isaias-036.adoc#v23-36-0[Próximo Capítulo &#62;]