include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-10-1]]

^<<v23-10-1,1>>^ Ai dos que decretam leis injustas, e dos escrivães que escrevem perversidades;

[[v23-10-2]]

^<<v23-10-2,2>>^ para privarem da justiça os necessitados, e arrebatarem o direito aos aflitos do meu povo; para despojarem as viúvas e roubarem os órfãos!

[[v23-10-3]]

^<<v23-10-3,3>>^ Mas que fareis vós no dia da visitação, e na desolação, que há de vir de longe? a quem recorrereis para obter socorro, e onde deixareis a vossa riqueza?

[[v23-10-4]]

^<<v23-10-4,4>>^ Nada mais resta senão curvar-vos entre os presos, ou cair entre os mortos. Com tudo isso não se apartou a sua ira, mas ainda está estendida a sua mão.

[[v23-10-5]]

^<<v23-10-5,5>>^ Ai da Assíria, a vara da minha ira, porque a minha indignação é como bordão nas suas mãos.

[[v23-10-6]]

^<<v23-10-6,6>>^ Eu a envio contra uma nação ímpia; e contra o povo do meu furor lhe dou ordem, para tomar o despojo, para arrebatar a presa, e para os pisar aos pés, como a lama das ruas.

[[v23-10-7]]

^<<v23-10-7,7>>^ Todavia ela não entende assim, nem o seu coração assim o imagina; antes no seu coração intenta destruir e desarraigar não poucas nações.

[[v23-10-8]]

^<<v23-10-8,8>>^ Pois diz: Não são meus príncipes todos eles reis?

[[v23-10-9]]

^<<v23-10-9,9>>^ Não é Calnó como Carquêmis? não é Hamate como Arpade? e Samária como Damasco?

[[v23-10-10]]

^<<v23-10-10,10>>^ Do mesmo modo que a minha mão alcançou os reinos dos ídolos, ainda que as suas imagens esculpidas eram melhores do que as de Jerusalém e de Samária.

[[v23-10-11]]

^<<v23-10-11,11>>^ como fiz a Samária e aos seus ídolos, não o farei igualmente a Jerusalém e aos seus ídolos?

[[v23-10-12]]

^<<v23-10-12,12>>^ Por isso acontecerá que, havendo o Senhor acabado toda a sua obra no monte Sião e em Jerusalém, então castigará o rei da Assíria pela arrogância do seu coração e a pomba da altivez dos seus olhos.

[[v23-10-13]]

^<<v23-10-13,13>>^ Porquanto diz ele: Com a força da minha mão o fiz, e com a minha sabedoria, porque sou entendido; eu removi os limites dos povos, e roubei os seus tesouros, e como valente abati os que se sentavam sobre tronos.

[[v23-10-14]]

^<<v23-10-14,14>>^ E achou a minha mão as riquezas dos povos como a um ninho; e como se ajuntam os ovos abandonados, assim eu ajuntei toda a terra; e não houve quem movesse a asa, ou abrisse a boca, ou chilreasse.

[[v23-10-15]]

^<<v23-10-15,15>>^ Porventura gloriar-se-á o machado contra o que corta com ele? ou se engrandecerá a serra contra o que a maneja? como se a vara movesse o que a levanta, ou o bordão levantasse aquele que não é pau!

[[v23-10-16]]

^<<v23-10-16,16>>^ Pelo que o Senhor Deus dos exércitos fará definhar os que entre eles são gordos, e debaixo da sua glória ateará um incêndio, como incêndio de fogo.

[[v23-10-17]]

^<<v23-10-17,17>>^ A Luz de Israel virá a ser um fogo e o seu Santo uma labareda, que num só dia abrasará e consumirá os seus espinheiros e as suas sarças.

[[v23-10-18]]

^<<v23-10-18,18>>^ Também consumirá a glória da sua floresta, e do seu campo fértil, desde a alma até o corpo; e será como quando um doente vai definhando.

[[v23-10-19]]

^<<v23-10-19,19>>^ E o resto das árvores da sua floresta será tão pouco que um menino as poderá contar.

[[v23-10-20]]

^<<v23-10-20,20>>^ E acontecerá naquele dia que o resto de Israel, e os que tiverem escapado da casa de Jacó, nunca mais se estribarão sobre aquele que os feriu; antes se estribarão lealmente sobre o Senhor, o Santo de Israel.

[[v23-10-21]]

^<<v23-10-21,21>>^ Um resto voltará; sim, o resto de Jacó voltará para o Deus forte.

[[v23-10-22]]

^<<v23-10-22,22>>^ Porque ainda que o teu povo, ó Israel, seja como a areia do mar, só um resto dele voltará. Uma destruição está determinada, trasbordando de justiça.

[[v23-10-23]]

^<<v23-10-23,23>>^ Pois uma destruição, e essa já determinada, o Senhor Deus dos exércitos executará no meio de toda esta terra.

[[v23-10-24]]

^<<v23-10-24,24>>^ Pelo que assim diz o Senhor Deus dos exércitos: ó povo meu, que habitas em Sião, não temas a Assíria, quando te ferir com a vara, e contra ti levantar o seu bordão a maneira dos egípcios;

[[v23-10-25]]

^<<v23-10-25,25>>^ porque daqui a bem pouco se cumprirá a minha indignação, e a minha ira servirá para os consumir.

[[v23-10-26]]

^<<v23-10-26,26>>^ E o Senhor dos exércitos suscitará contra ela um flagelo, como a matança de Midiã junto à rocha de Orebe; e a sua vara se estenderá sobre o mar, e ele a levantará como no Egito.

[[v23-10-27]]

^<<v23-10-27,27>>^ E naquele dia a sua carga será tirada do teu ombro, e o seu jugo do teu pescoço; e o jugo será quebrado por causa da gordura.

[[v23-10-28]]

^<<v23-10-28,28>>^ Os assírios já chegaram a Aiate, passaram por Migrom; em Micmás deixam depositada a sua bagagem;

[[v23-10-29]]

^<<v23-10-29,29>>^ já atravessaram o desfiladeiro, já se alojam em Geba; Ramá treme, Gibeá de Saul já fugiu.

[[v23-10-30]]

^<<v23-10-30,30>>^ Clama com alta voz, ó filha de Galim! Ouve, ó Laís! Responde-lhe, ó Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Já se foi Madmena; os moradores de Gebim procuram refúgio.

[[v23-10-32]]

^<<v23-10-32,32>>^ Hoje mesmo parará em Nobe; sacudirá o punho contra o monte da filha de Sião, o outeiro de Jerusalém.

[[v23-10-33]]

^<<v23-10-33,33>>^ Eis que o Senhor Deus dos exércitos cortará os ramos com violência; e os de alta estatura serão cortados, e os elevados serão abatidos.

[[v23-10-34]]

^<<v23-10-34,34>>^ E cortará com o ferro o emaranhado da floresta, e o Líbano cairá pela mão de um poderoso.

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]