include::./index.adoc[]

[[v23-14-0]]
=== Isaías, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-14-1]]

^<<v23-14-1,1>>^ Pois o Senhor se compadecerá de Jacó, e ainda escolherá a Israel e os porá na sua própria terra; e ajuntar-se-ão com eles os estrangeiros, e se apegarão à casa de Jacó.

[[v23-14-2]]

^<<v23-14-2,2>>^ E os povos os receberão, e os levarão aos seus lugares; e a casa de Israel os possuirá por servos e por servas, na terra do Senhor e cativarão aqueles que os cativaram, e dominarão os seus opressores.

[[v23-14-3]]

^<<v23-14-3,3>>^ No dia em que Deus vier a dar-te descanso do teu trabalho, e do teu tremor, e da dura servidão com que te fizeram servir,

[[v23-14-4]]

^<<v23-14-4,4>>^ proferirás esta parábola contra o rei de Babilônia, e dirás: Como cessou o opressor! como cessou a tirania!

[[v23-14-5]]

^<<v23-14-5,5>>^ Já quebrantou o Senhor o bastão dos ímpios e o cetro dos dominadores;

[[v23-14-6]]

^<<v23-14-6,6>>^ cetro que feria os povos com furor, com açoites incessantes, e que em ira dominava as nações com uma perseguição irresistível.

[[v23-14-7]]

^<<v23-14-7,7>>^ Toda a terra descansa, e está sossegada! Rompem em brados de júbilo.

[[v23-14-8]]

^<<v23-14-8,8>>^ Até as faias se alegram sobre ti, e os cedros do Líbano, dizendo: Desde que tu caíste ninguém sobe contra nós para nos cortar.

[[v23-14-9]]

^<<v23-14-9,9>>^ O Seol desde o profundo se turbou por ti, para sair ao teu encontro na tua vinda; ele despertou por ti os mortos, todos os que eram príncipes da terra, e fez levantar dos seus tronos todos os que eram reis das nações.

[[v23-14-10]]

^<<v23-14-10,10>>^ Estes todos responderão, e te dirão: Tu também estás fraco como nós, e te tornaste semelhante a nós.

[[v23-14-11]]

^<<v23-14-11,11>>^ Está derrubada até o Seol a tua pompa, o som dos teus alaúdes; os bichinhos debaixo de ti se estendem e os bichos te cobrem.

[[v23-14-12]]

^<<v23-14-12,12>>^ Como caíste do céu, ó estrela da manhã, filha da alva! como foste lançado por terra tu que prostravas as nações!

[[v23-14-13]]

^<<v23-14-13,13>>^ E tu dizias no teu coração: Eu subirei ao céu; acima das estrelas de Deus exaltarei o meu trono; e no monte da congregação me assentarei, nas extremidades do norte;

[[v23-14-14]]

^<<v23-14-14,14>>^ subirei acima das alturas das nuvens, e serei semelhante ao Altíssimo.

[[v23-14-15]]

^<<v23-14-15,15>>^ Contudo levado serás ao Seol, ao mais profundo do abismo.

[[v23-14-16]]

^<<v23-14-16,16>>^ Os que te virem te contemplarão, considerar-te-ão, e dirão: É este o varão que fazia estremecer a terra, e que fazia tremer os reinos?

[[v23-14-17]]

^<<v23-14-17,17>>^ Que punha o mundo como um deserto, e assolava as suas cidades? que a seus cativos não deixava ir soltos para suas casas?

[[v23-14-18]]

^<<v23-14-18,18>>^ Todos os reis das nações, todos eles, dormem com glória, cada um no seu túmulo.

[[v23-14-19]]

^<<v23-14-19,19>>^ Mas tu és lançado da tua sepultura, como um renovo abominável, coberto de mortos atravessados a espada, como os que descem às pedras da cova, como cadáver pisado aos pés.

[[v23-14-20]]

^<<v23-14-20,20>>^ Com eles não te reunirás na sepultura; porque destruíste a tua terra e mataste o teu povo. Que a descendência dos malignos não seja nomeada para sempre!

[[v23-14-21]]

^<<v23-14-21,21>>^ Preparai a matança para os filhos por causa da maldade de seus pais, para que não se levantem, e possuam a terra, e encham o mundo de cidades.

[[v23-14-22]]

^<<v23-14-22,22>>^ Levantar-me-ei contra eles, diz o Senhor dos exércitos, e exterminarei de Babilônia o nome, e os sobreviventes, o filho, e o neto, diz o Senhor.

[[v23-14-23]]

^<<v23-14-23,23>>^ E reduzi-la-ei a uma possessão do ouriço, e a lagoas de águas; e varrê-la-ei com a vassoura da destruição, diz o Senhor dos exércitos.

[[v23-14-24]]

^<<v23-14-24,24>>^ O Senhor dos exércitos jurou, dizendo: Como pensei, assim sucederá, e como determinei, assim se efetuará.

[[v23-14-25]]

^<<v23-14-25,25>>^ Quebrantarei o assírio na minha terra e nas minhas montanhas o pisarei; então o seu jugo se apartará deles e a sua carga se desviará dos seus ombros.

[[v23-14-26]]

^<<v23-14-26,26>>^ Este é o conselho que foi determinado sobre toda a terra; e esta é a mão que está estendida sobre todas as nações.

[[v23-14-27]]

^<<v23-14-27,27>>^ Pois o Senhor dos exércitos o determinou, e quem o invalidará? A sua mão estendida está, e quem a fará voltar atrás?

[[v23-14-28]]

^<<v23-14-28,28>>^ No ano em que morreu o rei Acaz, veio este oráculo.

[[v23-14-29]]

^<<v23-14-29,29>>^ Não te alegres, ó Filístia toda, por ser quebrada a vara que te feria; porque da raiz da cobra sairá um basilisco, e o seu fruto será uma serpente voadora.

[[v23-14-30]]

^<<v23-14-30,30>>^ E os primogênitos dos pobres serão apascentados, e os necessitados se deitarão seguros; mas farei morrer de fome a tua raiz, e será destruído o teu restante.

[[v23-14-31]]

^<<v23-14-31,31>>^ Uiva, ó porta; grita, ó cidade; tu, ó Filístia, estás toda derretida; porque do norte vem fumaça; e não há vacilante nas suas fileiras.

[[v23-14-32]]

^<<v23-14-32,32>>^ Que se responderá pois aos mensageiros do povo? Que o Senhor fundou a Sião, e que nela acharão refúgio os aflitos do seu povo.

'''

xref:023-isaias/023-isaias-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaias/023-isaias-015.adoc#v23-15-0[Próximo Capítulo &#62;]