include::./index.adoc[]

[[v23-21-0]]
=== Isaías, 21
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-21-1]]

^<<v23-21-1,1>>^ Oráculo acerca do deserto do mar. Como os tufões de vento do sul, que tudo assolam, aí vem do deserto, duma terra horrível.

[[v23-21-2]]

^<<v23-21-2,2>>^ Dura visão me foi manifesta: o pérfido trata perfidamente, e o destruidor anda destruindo. Sobe, ó Elão, sitia, ó Média; já fiz cessar todo o seu gemido.

[[v23-21-3]]

^<<v23-21-3,3>>^ Pelo que os meus lombos estão cheios de angústia; dores apoderaram-se de mim como as dores de mulher na hora do parto; estou tão atribulado que não posso ouvir, e tão desfalecido que não posso ver.

[[v23-21-4]]

^<<v23-21-4,4>>^ O meu coração se agita, o horror apavora-me; o crepúsculo, que desejava, tem-se-me tornado em tremores.

[[v23-21-5]]

^<<v23-21-5,5>>^ Eles põem a mesa, estendem os tapetes, comem, bebem. Levantai-vos, príncipes, e ungi o escudo.

[[v23-21-6]]

^<<v23-21-6,6>>^ Porque assim me disse o Senhor: Vai, põe uma sentinela; e ela que diga o que vir.

[[v23-21-7]]

^<<v23-21-7,7>>^ Quando vir uma tropa de cavaleiros de dois a dois, uma tropa de jumentos, ou uma tropa de camelos, escute a sentinela atentamente com grande cuidado.

[[v23-21-8]]

^<<v23-21-8,8>>^ Então clamou aquele que viu: Senhor, sobre a torre de vigia estou em pé continuamente de dia, e de guarda me ponho todas as noites.

[[v23-21-9]]

^<<v23-21-9,9>>^ E eis aqui agora vem uma tropa de homens, cavaleiros de dois a dois. Então ele respondeu e disse: Caiu, caiu Babilônia; e todas as imagens esculpidas de seus deuses são despedaçadas até o chão.

[[v23-21-10]]

^<<v23-21-10,10>>^ Ah, malhada minha, e trigo da minha eira! o que ouvi do Senhor dos exércitos, Deus de Israel, isso vos tenho anunciado.

[[v23-21-11]]

^<<v23-21-11,11>>^ Oráculo acerca de Dumá. Alguém clama a mim de Seir: Guarda, que horas são da noite? guarda, que horas são da noite?

[[v23-21-12]]

^<<v23-21-12,12>>^ Respondeu o guarda: Vem a manhã, e também a noite; se quereis perguntar, perguntai; voltai, vinde.

[[v23-21-13]]

^<<v23-21-13,13>>^ Oráculo contra a Arábia. Nos bosques da Arábia passareis a noite, ó caravanas de dedanitas.

[[v23-21-14]]

^<<v23-21-14,14>>^ Saí com água ao encontro dos sedentos; ó moradores da terra de Tema, saí com pão ao encontro dos fugitivos.

[[v23-21-15]]

^<<v23-21-15,15>>^ pois fogem diante das espadas, diante da espada desembainhada, e diante do arco armado, e diante da pressão da guerra.

[[v23-21-16]]

^<<v23-21-16,16>>^ porque assim me disse o Senhor: Dentro de um ano, tal como os anos de jornaleiro, toda a glória de Quedar esvaecerá.

[[v23-21-17]]

^<<v23-21-17,17>>^ e os restantes do número dos flecheiros, os valentes dos filhos de Quedar, serão diminuídos; porque assim o disse o Senhor, Deus de Israel.

'''

xref:023-isaias/023-isaias-020.adoc#v23-20-0[&#60; Capítulo Anterior] | <<v23-21-0,Topo>> | xref:023-isaias/023-isaias-022.adoc#v23-22-0[Próximo Capítulo &#62;]