include::./index.adoc[]

[[v23-20-0]]
=== Isaías, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-20-1]]

^<<v23-20-1,1>>^ No ano em que Tartã, enviado por Sargão, rei da Assíria, veio a Asdode, e guerreou contra Asdode, e a tomou;

[[v23-20-2]]

^<<v23-20-2,2>>^ falou o Senhor, naquele tempo, por intermédio de Isaías, filho de Amoz, dizendo: Vai, solta o cilício de teus lombos, e descalça os sapatos dos teus pés. E ele assim o fez, andando nu e descalço.

[[v23-20-3]]

^<<v23-20-3,3>>^ Então disse o Senhor: Assim como o meu servo Isaías andou três anos nu e descalço, por sinal e portento contra o Egito e contra a Etiópia,

[[v23-20-4]]

^<<v23-20-4,4>>^ assim o rei da Assíria levará em cativeiro os presos do Egito, e os exilados da Etiópia, tanto moços como velhos, nus e descalços, e com as nádegas descobertas, para vergonha do Egito.

[[v23-20-5]]

^<<v23-20-5,5>>^ E assombrar-se-ão, e envergonhar-se-ão por causa da Etiópia, sua esperança, e do Egito, sua glória.

[[v23-20-6]]

^<<v23-20-6,6>>^ Então os moradores desta região litorânea dirão naquele dia: Vede que tal é a nossa esperança, aquilo que buscamos por socorro, para nos livrarmos do rei da Assíria! Como pois escaparemos nós?

'''

xref:023-isaias/023-isaias-019.adoc#v23-19-0[&#60; Capítulo Anterior] | <<v23-20-0,Topo>> | xref:023-isaias/023-isaias-021.adoc#v23-21-0[Próximo Capítulo &#62;]