include::./index.adoc[]

[[v23-64-0]]
=== Isaías, 64
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-64-1]]

^<<v23-64-1,1>>^ Oh! se fendesses os céus, e descesses, e os montes tremessem à tua presença,

[[v23-64-2]]

^<<v23-64-2,2>>^ como quando o fogo pega em acendalhas, e o fogo faz ferver a água, para fazeres notório o teu nome aos teus adversários, de sorte que à tua presença tremam as nações!

[[v23-64-3]]

^<<v23-64-3,3>>^ Quando fazias coisas terríveis, que não esperávamos, descias, e os montes tremiam à tua presença.

[[v23-64-4]]

^<<v23-64-4,4>>^ Porque desde a antigüidade não se ouviu, nem com ouvidos se percebeu, nem com os olhos se viu um Deus além de ti, que opera a favor daquele que por ele espera.

[[v23-64-5]]

^<<v23-64-5,5>>^ Tu sais ao encontro daquele que, com alegria, pratica a justiça, daqueles que se lembram de ti nos teus caminhos. Eis que te iraste, porque pecamos; há muito tempo temos estado em pecados; acaso seremos salvos?

[[v23-64-6]]

^<<v23-64-6,6>>^ Pois todos nós somos como o imundo, e todas as nossas justiças como trapo da imundícia; e todos nós murchamos como a folha, e as nossas iniqüidades, como o vento, nos arrebatam.

[[v23-64-7]]

^<<v23-64-7,7>>^ E não há quem invoque o teu nome, que desperte, e te detenha; pois escondeste de nós o teu rosto e nos consumiste, por causa das nossas iniqüidades.

[[v23-64-8]]

^<<v23-64-8,8>>^ Mas agora, ó Senhor, tu és nosso Pai; nós somos o barro, e tu o nosso oleiro; e todos nós obra das tuas mãos.

[[v23-64-9]]

^<<v23-64-9,9>>^ Não te agastes tanto, ó Senhor, nem perpetuamente te lembres da iniqüidade; olha, pois, nós te pedimos, todos nós somos o teu povo.

[[v23-64-10]]

^<<v23-64-10,10>>^ As tuas santas cidades se tornaram em deserto, Sião está feita um ermo, Jerusalém uma desolação.

[[v23-64-11]]

^<<v23-64-11,11>>^ A nossa santa e gloriosa casa, em que te louvavam nossos pais, foi queimada a fogo; e todos os nossos lugares aprazíveis se tornaram em ruínas.

[[v23-64-12]]

^<<v23-64-12,12>>^ Acaso conter-te-ás tu ainda sobre estas calamidades, ó Senhor? ficarás calado, e nos afligirás tanto?

'''

xref:023-isaias/023-isaias-063.adoc#v23-63-0[&#60; Capítulo Anterior] | <<v23-64-0,Topo>> | xref:023-isaias/023-isaias-065.adoc#v23-65-0[Próximo Capítulo &#62;]