include::./index.adoc[]

[[v23-16-0]]
=== Isaías, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-16-1]]

^<<v23-16-1,1>>^ Enviaram cordeiros ao governador da terra, desde Sela, pelo deserto, até o monte da filha de Sião.

[[v23-16-2]]

^<<v23-16-2,2>>^ Pois como pássaros que vagueiam, como ninhada dispersa, assim são as filhas de Moabe junto aos vaus do Arnom.

[[v23-16-3]]

^<<v23-16-3,3>>^ Dá conselhos, executa juízo; põe a tua sombra como a noite ao pino do meio-dia; esconde os desterrados, e não traias o fugitivo.

[[v23-16-4]]

^<<v23-16-4,4>>^ Habitem entre vós os desterrados de Moabe; serve-lhes de refúgio perante a face do destruidor. Quando o homem violento tiver fim, e a destruição tiver cessado, havendo os opressores desaparecido de sobre a terra,

[[v23-16-5]]

^<<v23-16-5,5>>^ então um trono será estabelecido em benignidade, e sobre ele no tabernáculo de Davi se assentará em verdade um que julgue, e que procure a justiça e se apresse a praticar a retidão.

[[v23-16-6]]

^<<v23-16-6,6>>^ Ouvimos da soberba de Moabe, a soberbíssima; da sua arrogância, da sua soberba, e da sua insolência; de nada valem as suas jactâncias.

[[v23-16-7]]

^<<v23-16-7,7>>^ portanto Moabe pranteará; prantearão todos por Moabe; pelos bolos de passas de Quir-Haresete suspirareis, inteiramente desanimados.

[[v23-16-8]]

^<<v23-16-8,8>>^ porque os campos de Hesbom enfraqueceram, e a vinha de Sibma; os senhores das nações derrubaram os seus ramos, que chegaram a Jazer e penetraram no deserto; os seus rebentos se estenderam e passaram além do mar.

[[v23-16-9]]

^<<v23-16-9,9>>^ Pelo que prantearei, com o pranto de Jazer, a vinha de Sibma; regar-te-ei com as minhas lágrimas, ó Hesbom e Eleale; porque sobre os teus frutos de verão e sobre a tua sega caiu o grito da batalha.

[[v23-16-10]]

^<<v23-16-10,10>>^ A alegria e o regozijo são tirados do fértil campo, e nas vinhas não se canta, nem há júbilo algum; já não se pisam as uvas nos lagares. Eu fiz cessar os gritos da vindima.

[[v23-16-11]]

^<<v23-16-11,11>>^ Pelo que minha alma lamenta por Moabe como harpa, e o meu íntimo por Quir-Heres.

[[v23-16-12]]

^<<v23-16-12,12>>^ E será que, quando Moabe se apresentar, quando se cansar nos altos, e entrar no seu santuário a orar, nada alcançará.

[[v23-16-13]]

^<<v23-16-13,13>>^ Essa é a palavra que o Senhor falou no passado acerca de Moabe.

[[v23-16-14]]

^<<v23-16-14,14>>^ Mas agora diz o Senhor: Dentro de três anos, tais como os anos do jornaleiro, será envilecida a glória de Moabe, juntamente com toda a sua grande multidão; e os que lhe restarem serão poucos e débeis.

'''

xref:023-isaias/023-isaias-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaias/023-isaias-017.adoc#v23-17-0[Próximo Capítulo &#62;]