include::./index.adoc[]

[[v23-37-0]]
=== Isaías, 37
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-37-1]]

^<<v23-37-1,1>>^ Tendo ouvido isso o rei Ezequias, rasgou as suas vestes, e se cobriu de saco, e entrou na casa do Senhor.

[[v23-37-2]]

^<<v23-37-2,2>>^ Também enviou Eliaquim, o mordomo, Sebna, o escrivão, e os anciãos dos sacerdotes, cobertos de saco, a Isaías, filho de Amoz, o profeta,

[[v23-37-3]]

^<<v23-37-3,3>>^ para lhe dizerem: Assim diz Ezequias: Este dia é dia de angústia e de vitupérios, e de blasfêmias, porque chegados são os filhos ao parto, e força não há para os dar à luz.

[[v23-37-4]]

^<<v23-37-4,4>>^ Porventura o Senhor teu Deus terá ouvido as palavras de Rabsaqué, a quem enviou o rei da Assíria, seu amo, para afrontar o Deus vivo, e para o vituperar com as palavras que o Senhor teu Deus tem ouvido; faze oração pelo resto que ficou.

[[v23-37-5]]

^<<v23-37-5,5>>^ Foram, pois, os servos do rei Ezequias ter com Isaías,

[[v23-37-6]]

^<<v23-37-6,6>>^ e Isaías lhes disse: Dizei a vosso amo: Assim diz o Senhor: Não temas à vista das palavras que ouviste, com as quais os servos do rei da Assíria me blasfemaram.

[[v23-37-7]]

^<<v23-37-7,7>>^ Eis que meterei nele um espírito, e ele ouvirá uma nova, e voltará para a sua terra; e fá-lo-ei cair morto à espada na sua própria terra.

[[v23-37-8]]

^<<v23-37-8,8>>^ Voltou pois Rabsaqué, e achou o rei da Assíria pelejando contra Libna; porque ouvira que se havia retirado de Laquis.

[[v23-37-9]]

^<<v23-37-9,9>>^ Então ouviu ele dizer a respeito de Tiraca, rei da Etiópia: Saiu para te fazer guerra. Assim que ouviu isto, enviou mensageiros a Ezequias, dizendo:

[[v23-37-10]]

^<<v23-37-10,10>>^ Assim falareis a Ezequias, rei de Judá: Não te engane o teu Deus, em quem confias, dizendo: Jerusalém não será entregue na mão do rei da Assíria.

[[v23-37-11]]

^<<v23-37-11,11>>^ Eis que já tens ouvido o que fizeram os reis da Assíria a todas as terras, destruindo-as totalmente; e serás tu livrado?

[[v23-37-12]]

^<<v23-37-12,12>>^ Porventura as livraram os deuses das nações que meus pais destruíram: Gozã, e Harã, e Rezefe, e os filhos de Edem que estavam em Telassar?

[[v23-37-13]]

^<<v23-37-13,13>>^ Onde está o rei de Hamate, e o rei de Arpade, e o rei da cidade de Sefarvaim, Hena e Iva?

[[v23-37-14]]

^<<v23-37-14,14>>^ Recebendo pois Ezequias as cartas das mãos dos mensageiros, e lendo-as, subiu à casa do Senhor; e Ezequias as estendeu perante o Senhor.

[[v23-37-15]]

^<<v23-37-15,15>>^ E orou Ezequias ao Senhor, dizendo:

[[v23-37-16]]

^<<v23-37-16,16>>^ O Senhor dos exércitos, Deus de Israel, tu que estás sentado sobre os querubins; tu, só tu, és o Deus de todos os reinos da terra; tu fizeste o céu e a terra.

[[v23-37-17]]

^<<v23-37-17,17>>^ Inclina, ó Senhor, o teu ouvido, e ouve; abre, Senhor, os teus olhos, e vê; e ouve todas as palavras de Senaqueribe, as quais ele mandou para afrontar o Deus vivo.

[[v23-37-18]]

^<<v23-37-18,18>>^ Verdade é, Senhor, que os reis da Assíria têm assolado todos os países, e suas terras,

[[v23-37-19]]

^<<v23-37-19,19>>^ e lançado no fogo os seus deuses; porque deuses não eram, mas obra de mãos de homens, madeira e pedra; por isso os destruíram.

[[v23-37-20]]

^<<v23-37-20,20>>^ Agora, pois, ó Senhor nosso Deus, livra-nos da sua mão, para que todos os reinos da terra saibam que só tu és o Senhor.

[[v23-37-21]]

^<<v23-37-21,21>>^ Então Isaías, filho de Amoz, mandou dizer a Ezequias: Assim diz o Senhor, o Deus de Israel: Portanto me fizeste a tua súplica contra Senaqueribe, rei de Assíria,

[[v23-37-22]]

^<<v23-37-22,22>>^ esta é a palavra que o Senhor falou a respeito dele: A virgem, a filha de Sião, te despreza, e de ti zomba; a filha de Jerusalém meneia a cabeça por detrás de ti.

[[v23-37-23]]

^<<v23-37-23,23>>^ A quem afrontaste e de quem blasfemaste? contra quem alçaste a voz e ergueste os teus olhos ao alto? Contra o Santo de Israel.

[[v23-37-24]]

^<<v23-37-24,24>>^ Por meio de teus servos afrontaste o Senhor, e disseste: Com a multidão dos meus carros subi eu aos cumes dos montes, aos últimos recessos do Líbano; e cortei os seus altos cedros e as suas faias escolhidas; e entrei no seu cume mais elevado, no bosque do seu campo fértil.

[[v23-37-25]]

^<<v23-37-25,25>>^ Eu cavei, e bebi as águas; e com as plantas de meus pés sequei todos os rios do Egito.

[[v23-37-26]]

^<<v23-37-26,26>>^ Não ouviste que já há muito tempo eu fiz isso, e que já desde os dias antigos o tinha determinado? Agora porém o executei, para que fosses tu o que reduzisses as cidades fortificadas a montões de ruínas.

[[v23-37-27]]

^<<v23-37-27,27>>^ Por isso os seus moradores, dispondo de pouca força, andaram atemorizados e envergonhados; tornaram-se como a erva do campo, e como a relva verde, e como o feno dos telhados ou dum campo, que se queimaram antes de amadurecer.

[[v23-37-28]]

^<<v23-37-28,28>>^ Mas eu conheço o teu sentar, o teu sair e o teu entrar, e o teu furor contra mim.

[[v23-37-29]]

^<<v23-37-29,29>>^ Por causa do teu furor contra mim, e porque a tua arrogância subiu até os meus ouvidos, portanto porei o meu anzol no teu nariz e o meu freio na tua boca, e te farei voltar pelo caminho por onde vieste.

[[v23-37-30]]

^<<v23-37-30,30>>^ E isto te será por sinal: este ano comereis o que espontaneamente nascer, e no segundo ano o que daí proceder; e no terceiro ano semeai e colhei, plantai vinhas, e comei os frutos delas.

[[v23-37-31]]

^<<v23-37-31,31>>^ Pois o restante da casa de Judá, que sobreviveu, tornará a lançar raízes para baixo, e dará fruto para cima.

[[v23-37-32]]

^<<v23-37-32,32>>^ Porque de Jerusalém sairá o restante, e do monte Sião os que escaparam; o zelo do Senhor dos exércitos fará isso.

[[v23-37-33]]

^<<v23-37-33,33>>^ Portanto, assim diz o Senhor acerca do rei da Assíria: Não entrará nesta cidade, nem lançará nela flecha alguma; tampouco virá perante ela com escudo, ou levantará contra ela tranqueira.

[[v23-37-34]]

^<<v23-37-34,34>>^ Pelo caminho por onde veio, por esse voltará; mas nesta cidade não entrará, diz o Senhor.

[[v23-37-35]]

^<<v23-37-35,35>>^ Porque eu defenderei esta cidade, para a livrar, por amor de mim e, por amor do meu servo Davi.

[[v23-37-36]]

^<<v23-37-36,36>>^ Então saiu o anjo do Senhor, e feriu no arraial dos assírios a cento e oitenta e cinco mil; e quando se levantaram pela manhã cedo, eis que todos estes eram corpos mortos.

[[v23-37-37]]

^<<v23-37-37,37>>^ Assim Senaqueribe, rei da Assíria, se retirou, e se foi, e voltou, e habitou em Nínive.

[[v23-37-38]]

^<<v23-37-38,38>>^ E sucedeu que, enquanto ele adorava na casa de Nisroque, seu deus, Adrameleb, que e Sarezer, seus filhos, o mataram à espada; e escaparam para a terra de Arará. E Ezar-Hadom, seu filho, reinou em seu lugar.

'''

xref:023-isaias/023-isaias-036.adoc#v23-36-0[&#60; Capítulo Anterior] | <<v23-37-0,Topo>> | xref:023-isaias/023-isaias-038.adoc#v23-38-0[Próximo Capítulo &#62;]