include::./index.adoc[]

[[v23-29-0]]
=== Isaías, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-29-1]]

^<<v23-29-1,1>>^ Ah! Ariel, Ariel, cidade onde Davi acampou! Acrescentai ano a ano; completem as festas o seu ciclo.

[[v23-29-2]]

^<<v23-29-2,2>>^ Então porei Ariel em aperto, e haverá pranto e lamentação; e ela será para mim como Ariel.

[[v23-29-3]]

^<<v23-29-3,3>>^ Acamparei contra ti em redor, e te sitiarei com baluartes, e levantarei tranqueiras contra ti.

[[v23-29-4]]

^<<v23-29-4,4>>^ Então serás abatida, falarás de debaixo da terra, e a tua fala desde o pó sairá fraca; e será a tua voz debaixo da terra, como a dum necromante, e a tua fala assobiará desde o pó.

[[v23-29-5]]

^<<v23-29-5,5>>^ E a multidão dos teus inimigos será como o pó miúdo, e a multidão dos terríveis como a pragana que passa; e isso acontecerá num momento, repentinamente.

[[v23-29-6]]

^<<v23-29-6,6>>^ Da parte do Senhor dos exércitos será ela visitada com trovões, e com terremotos, e grande ruído, como tufão, e tempestade, e labareda de fogo consumidor.

[[v23-29-7]]

^<<v23-29-7,7>>^ E como o sonho e uma visão de noite será a multidão de todas as nações que hão de pelejar contra Ariel, sim a multidão de todos os que pelejarem contra ela e contra a sua fortaleza e a puserem em aperto.

[[v23-29-8]]

^<<v23-29-8,8>>^ Será também como o faminto que sonha que está a comer, mas, acordando, sente-se vazio; ou como o sedento que sonha que está a beber, mas, acordando, desfalecido se acha, e ainda com sede; assim será a multidão de todas as nações que pelejarem contra o monte Sião.

[[v23-29-9]]

^<<v23-29-9,9>>^ Pasmai, e maravilhai-vos; cegai-vos e ficai cegos; bêbedos estão, mas não de vinho, andam cambaleando, mas não de bebida forte.

[[v23-29-10]]

^<<v23-29-10,10>>^ Porque o Senhor derramou sobre vós um espírito de profundo sono, e fechou os vossos olhos, os profetas; e vendou as vossas cabeças, os videntes.

[[v23-29-11]]

^<<v23-29-11,11>>^ Pelo que toda visão vos é como as palavras dum livro selado que se dá ao que sabe ler, dizendo: Ora lê isto; e ele responde: Não posso, porque está selado.

[[v23-29-12]]

^<<v23-29-12,12>>^ Ou dá-se o livro ao que não sabe ler, dizendo: Ora lê isto; e ele responde: Não sei ler.

[[v23-29-13]]

^<<v23-29-13,13>>^ Por isso o Senhor disse: Pois que este povo se aproxima de mim, e com a sua boca e com os seus lábios me honra, mas tem afastado para longe de mim o seu coração, e o seu temor para comigo consiste em mandamentos de homens, aprendidos de cor;

[[v23-29-14]]

^<<v23-29-14,14>>^ portanto eis que continuarei a fazer uma obra maravilhosa com este povo, sim uma obra maravilhosa e um assombro; e a sabedoria dos seus sábios perecerá, e o entendimento dos seus entendidos se esconderá.

[[v23-29-15]]

^<<v23-29-15,15>>^ Ai dos que escondem profundamente o seu propósito do Senhor, e fazem as suas obras às escuras, e dizem: Quem nos vê? e quem nos conhece?

[[v23-29-16]]

^<<v23-29-16,16>>^ Vós tudo perverteis! Acaso o oleiro há de ser reputado como barro, de modo que a obra diga do seu artífice: Ele não me fez; e o vaso formado diga de quem o formou: Ele não tem entendimento?

[[v23-29-17]]

^<<v23-29-17,17>>^ Porventura dentro ainda de muito pouco tempo não se converterá o Líbano em campo fértil? e o campo fértil não se reputará por um bosque?

[[v23-29-18]]

^<<v23-29-18,18>>^ Naquele dia os surdos ouvirão as palavras do livro, e dentre a escuridão e dentre as trevas os olhos dos cegos a verão.

[[v23-29-19]]

^<<v23-29-19,19>>^ E os mansos terão cada vez mais gozo no Senhor, e os pobres dentre os homens se alegrarão no santo de Israel.

[[v23-29-20]]

^<<v23-29-20,20>>^ Porque o opressor é reduzido a nada, e não existe mais o escarnecedor, e todos os que se dão à iniqüidade são desarraigados;

[[v23-29-21]]

^<<v23-29-21,21>>^ os que fazem por culpado o homem numa causa, os que armam laços ao que repreende na porta, e os que por um nada desviam o justo.

[[v23-29-22]]

^<<v23-29-22,22>>^ Portanto o Senhor, que remiu a Abraão, assim diz acerca da casa de Jacó: Jacó não será agora envergonhado, nem agora se descorará a sua face.

[[v23-29-23]]

^<<v23-29-23,23>>^ Mas quando virem seus filhos a obra das minhas mãos no meio deles, santificarão o meu nome; sim santificarão ao Santo de Jacó, e temerão ao Deus de Israel.

[[v23-29-24]]

^<<v23-29-24,24>>^ E os errados de espírito virão a ter entendimento, e os murmuradores aprenderão instrução.

'''

xref:023-isaias/023-isaias-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaias/023-isaias-030.adoc#v23-30-0[Próximo Capítulo &#62;]