include::./index.adoc[]

[[v23-28-0]]
=== Isaías, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-28-1]]

^<<v23-28-1,1>>^ Ai da vaidosa coroa dos bêbedos de Efraim, e da flor murchada do seu glorioso ornamento, que está sobre a cabeça do fértil vale dos vencidos do vinho.

[[v23-28-2]]

^<<v23-28-2,2>>^ Eis que o Senhor tem um valente e poderoso; como tempestade de saraiva, tormenta destruidora, como tempestade de impetuosas águas que transbordam, ele a derrubará violentamente por terra.

[[v23-28-3]]

^<<v23-28-3,3>>^ A vaidosa coroa dos bêbedos de Efraim será pisada aos pés;

[[v23-28-4]]

^<<v23-28-4,4>>^ e a flor murchada do seu glorioso ornamento, que está sobre a cabeça do fértil vale, será como figo que amadurece antes do verão, que, vendo-o alguém, e mal tomando-o na mão, o engole.

[[v23-28-5]]

^<<v23-28-5,5>>^ Naquele dia o Senhor dos exércitos será por coroa de glória e diadema de formosura para o restante de seu povo;

[[v23-28-6]]

^<<v23-28-6,6>>^ e por espírito de juízo para o que se assenta a julgar, e por fortaleza para os que fazem recuar a peleja até a porta.

[[v23-28-7]]

^<<v23-28-7,7>>^ Mas também estes cambaleiam por causa do vinho, e com a bebida forte se desencaminham; até o sacerdote e o profeta cambaleiam por causa da bebida forte, estão tontos do vinho, desencaminham-se por causa da bebida forte; erram na visão, e tropeçam no juizo.

[[v23-28-8]]

^<<v23-28-8,8>>^ Pois todas as suas mesas estão cheias de vômitos e de sujidade, e não há lugar que esteja limpo.

[[v23-28-9]]

^<<v23-28-9,9>>^ Ora, a quem ensinará ele o conhecimento? e a quem fará entender a mensagem? aos desmamados, e aos arrancados dos seios?

[[v23-28-10]]

^<<v23-28-10,10>>^ Pois é preceito sobre preceito, preceito sobre preceito; regra sobre regra, regra sobre regra; um pouco aqui, um pouco ali.

[[v23-28-11]]

^<<v23-28-11,11>>^ Na verdade por lábios estranhos e por outra língua falará a este povo;

[[v23-28-12]]

^<<v23-28-12,12>>^ ao qual disse: Este é o descanso, dai descanso ao cansado; e este é o refrigério; mas não quiseram ouvir.

[[v23-28-13]]

^<<v23-28-13,13>>^ Assim pois a palavra do Senhor lhes será preceito sobre preceito, preceito sobre preceito; regra sobre regra, regra sobre regra; um pouco aqui, um pouco ali; para que vão, e caiam para trás, e fiquem quebrantados, enlaçados, e presos.

[[v23-28-14]]

^<<v23-28-14,14>>^ Ouvi, pois, a palavra do Senhor, homens escarnecedores, que dominais este povo que está em Jerusalém.

[[v23-28-15]]

^<<v23-28-15,15>>^ Porquanto dizeis: Fizemos pacto com a morte, e com o Seol fizemos aliança; quando passar o flagelo trasbordante, não chegará a nós; porque fizemos da mentira o nosso refúgio, e debaixo da falsidade nos escondemos.

[[v23-28-16]]

^<<v23-28-16,16>>^ Portanto assim diz o Senhor Deus: Eis que ponho em Sião como alicerce uma pedra, uma pedra provada, pedra preciosa de esquina, de firme fundamento; aquele que crer não se apressará.

[[v23-28-17]]

^<<v23-28-17,17>>^ E farei o juízo a linha para medir, e a justiça o prumo; e a saraiva varrerá o refúgio da mentira, e as águas inundarão o esconderijo.

[[v23-28-18]]

^<<v23-28-18,18>>^ E o vosso pacto com a morte será anulado; e a vossa aliança com o Seol não subsistirá; e, quando passar o flagelo trasbordante, sereis abatidos por ele.

[[v23-28-19]]

^<<v23-28-19,19>>^ Todas as vezes que passar, vos arrebatará; porque de manhã em manhã passará, de dia e de noite; e será motivo de terror o só ouvir tal notícia.

[[v23-28-20]]

^<<v23-28-20,20>>^ Pois a cama é tão curta que nela ninguém se pode estender; e o cobertor tão estreito que com ele ninguém se pode cobrir.

[[v23-28-21]]

^<<v23-28-21,21>>^ Porque o Senhor se levantará como no monte Perazim, e se irará como no vale de Gibeão, para realizar a sua obra, a sua estranha obra, e para executar o seu ato, o seu estranho ato.

[[v23-28-22]]

^<<v23-28-22,22>>^ Agora, pois, não sejais escarnecedores, para que os vossos grilhões não se façam mais fortes; porque da parte do Senhor Deus dos exércitos ouvi um decreto de destruição completa e decisiva, sobre toda terra.

[[v23-28-23]]

^<<v23-28-23,23>>^ Inclinai os ouvidos, e ouvi a minha voz; escutai, e ouvi o meu discurso.

[[v23-28-24]]

^<<v23-28-24,24>>^ Porventura lavra continuamente o lavrador, para semear? ou está sempre abrindo e esterroando a sua terra?

[[v23-28-25]]

^<<v23-28-25,25>>^ Não é antes assim: quando já tem nivelado a sua superfície, não espalha a nigela, não semeia o cominho, não lança nela o trigo em leiras, ou cevada no lugar determinado, ou a espelta na margem?

[[v23-28-26]]

^<<v23-28-26,26>>^ Pois o seu Deus o instrui devidamente e o ensina.

[[v23-28-27]]

^<<v23-28-27,27>>^ Porque a nigela não se trilha com instrumento de trilhar, nem sobre o cominho passa a roda de carro; mas a nigela é debulhada com uma vara, e o cominho com um pau.

[[v23-28-28]]

^<<v23-28-28,28>>^ Acaso é esmiuçado o trigo? não; não se trilha continuamente, nem se esmiúça com as rodas do seu carro e os seus cavalos; não se esmiúça.

[[v23-28-29]]

^<<v23-28-29,29>>^ Até isso procede do Senhor dos exércitos, que é maravilhoso em conselho e grande em obra.

'''

xref:023-isaias/023-isaias-027.adoc#v23-27-0[&#60; Capítulo Anterior] | <<v23-28-0,Topo>> | xref:023-isaias/023-isaias-029.adoc#v23-29-0[Próximo Capítulo &#62;]