include::./index.adoc[]

[[v23-6-0]]
=== Isaías, 6
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-6-1]]

^<<v23-6-1,1>>^ No ano em que morreu o rei Uzias, eu vi o Senhor assentado sobre um alto e sublime trono, e as orlas do seu manto enchiam o templo.

[[v23-6-2]]

^<<v23-6-2,2>>^ Ao seu redor havia serafins; cada um tinha seis asas; com duas cobria o rosto, e com duas cobria os pés e com duas voava.

[[v23-6-3]]

^<<v23-6-3,3>>^ E clamavam uns para os outros, dizendo: Santo, santo, santo é o Senhor dos exércitos; a terra toda está cheia da sua glória.

[[v23-6-4]]

^<<v23-6-4,4>>^ E as bases dos limiares moveram-se à voz do que clamava, e a casa se enchia de fumaça.

[[v23-6-5]]

^<<v23-6-5,5>>^ Então disse eu: Ai de mim! pois estou perdido; porque sou homem de lábios impuros, e habito no meio dum povo de impuros lábios; e os meus olhos viram o rei, o Senhor dos exércitos!

[[v23-6-6]]

^<<v23-6-6,6>>^ Então voou para mim um dos serafins, trazendo na mão uma brasa viva, que tirara do altar com uma tenaz;

[[v23-6-7]]

^<<v23-6-7,7>>^ e com a brasa tocou-me a boca, e disse: Eis que isto tocou os teus lábios; e a tua iniqüidade foi tirada, e perdoado o teu pecado.

[[v23-6-8]]

^<<v23-6-8,8>>^ Depois disto ouvi a voz do Senhor, que dizia: A quem enviarei, e quem irá por nós? Então disse eu: Eis-me aqui, envia-me a mim.

[[v23-6-9]]

^<<v23-6-9,9>>^ Disse, pois, ele: Vai, e dize a este povo: Ouvis, de fato, e não entendeis, e vedes, em verdade, mas não percebeis.

[[v23-6-10]]

^<<v23-6-10,10>>^ Engorda o coração deste povo, e endurece-lhe os ouvidos, e fecha-lhe os olhos; para que ele não veja com os olhos, e ouça com os ouvidos, e entenda com o coração, e se converta, e seja sarado.

[[v23-6-11]]

^<<v23-6-11,11>>^ Então disse eu: Até quando, Senhor? E respondeu: Até que sejam assoladas as cidades, e fiquem sem habitantes, e as casas sem moradores, e a terra seja de todo assolada,

[[v23-6-12]]

^<<v23-6-12,12>>^ e o Senhor tenha removido para longe dela os homens, e sejam muitos os lugares abandonados no meio da terra.

[[v23-6-13]]

^<<v23-6-13,13>>^ Mas se ainda ficar nela a décima parte, tornará a ser consumida, como o terebinto, e como o carvalho, dos quais, depois de derrubados, ainda fica o toco. A santa semente é o seu toco.

'''

xref:023-isaias/023-isaias-005.adoc#v23-5-0[&#60; Capítulo Anterior] | <<v23-6-0,Topo>> | xref:023-isaias/023-isaias-007.adoc#v23-7-0[Próximo Capítulo &#62;]