include::./index.adoc[]

[[v23-1-0]]
=== Isaías, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-1-1]]

^<<v23-1-1,1>>^ A visão de Isaías, filho de Amoz, que ele teve a respeito de Judá e Jerusalém, nos dias de Uzias, Jotão, Acaz, e Ezequias, reis de Judá.

[[v23-1-2]]

^<<v23-1-2,2>>^ Ouvi, ó céus, e dá ouvidos, ó terra, porque falou o Senhor: Criei filhos, e os engrandeci, mas eles se rebelaram contra mim.

[[v23-1-3]]

^<<v23-1-3,3>>^ O boi conhece o seu possuidor, e o jumento a manjedoura do seu dono; mas Israel não tem conhecimento, o meu povo não entende.

[[v23-1-4]]

^<<v23-1-4,4>>^ Ah, nação pecadora, povo carregado de iniqüidade, descendência de malfeitores, filhos que praticam a corrupção! Deixaram o Senhor, desprezaram o Santo de Israel, voltaram para trás.

[[v23-1-5]]

^<<v23-1-5,5>>^ Por que seríeis ainda castigados, que persistis na rebeldia? Toda a cabeça está enferma e todo o coração fraco.

[[v23-1-6]]

^<<v23-1-6,6>>^ Desde a planta do pé até a cabeça não há nele coisa sã; há só feridas, contusões e chagas vivas; não foram espremidas, nem atadas, nem amolecidas com óleo.

[[v23-1-7]]

^<<v23-1-7,7>>^ O vosso país está assolado; as vossas cidades abrasadas pelo fogo; a vossa terra os estranhos a devoram em vossa presença, e está devastada, como por uma pilhagem de estrangeiros.

[[v23-1-8]]

^<<v23-1-8,8>>^ E a filha de Sião é deixada como a cabana na vinha, como a choupana no pepinal, como cidade sitiada.

[[v23-1-9]]

^<<v23-1-9,9>>^ Se o Senhor dos exércitos não nos deixara alguns sobreviventes, já como Sodoma seríamos, e semelhantes a Gomorra.

[[v23-1-10]]

^<<v23-1-10,10>>^ Ouvi a palavra do Senhor, governadores de Sodoma; dai ouvidos à lei do nosso Deus, ó povo de Gomorra.

[[v23-1-11]]

^<<v23-1-11,11>>^ De que me serve a mim a multidão de vossos sacrifícios? diz o Senhor. Estou farto dos holocaustos de carneiros, e da gordura de animais cevados; e não me agrado do sangue de novilhos, nem de cordeiros, nem de bodes.

[[v23-1-12]]

^<<v23-1-12,12>>^ Quando vindes para comparecerdes perante mim, quem requereu de vós isto, que viésseis pisar os meus átrios?

[[v23-1-13]]

^<<v23-1-13,13>>^ Não continueis a trazer ofertas vãs; o incenso é para mim abominação. As luas novas, os sábados, e a convocação de assembléias ... não posso suportar a iniqüidade e o ajuntamento solene!

[[v23-1-14]]

^<<v23-1-14,14>>^ As vossas luas novas, e as vossas festas fixas, a minha alma as aborrece; já me são pesadas; estou cansado de as sofrer.

[[v23-1-15]]

^<<v23-1-15,15>>^ Quando estenderdes as vossas mãos, esconderei de vós os meus olhos; e ainda que multipliqueis as vossas orações, não as ouvirei; porque as vossas mãos estão cheias de sangue.

[[v23-1-16]]

^<<v23-1-16,16>>^ Lavai-vos, purificai-vos; tirai de diante dos meus olhos a maldade dos vossos atos; cessai de fazer o mal;

[[v23-1-17]]

^<<v23-1-17,17>>^ aprendei a fazer o bem; buscai a justiça, acabai com a opressão, fazei justiça ao órfão, defendei a causa da viúva.

[[v23-1-18]]

^<<v23-1-18,18>>^ Vinde, pois, e arrazoemos, diz o Senhor: ainda que os vossos pecados são como a escarlata, eles se tornarão brancos como a neve; ainda que são vermelhos como o carmesim, tornar-se-ão como a lã.

[[v23-1-19]]

^<<v23-1-19,19>>^ Se quiserdes, e me ouvirdes, comereis o bem desta terra;

[[v23-1-20]]

^<<v23-1-20,20>>^ mas se recusardes, e fordes rebeldes, sereis devorados à espada; pois a boca do Senhor o disse.

[[v23-1-21]]

^<<v23-1-21,21>>^ Como se fez prostituta a cidade fiel! ela que estava cheia de retidão! A justiça habitava nela, mas agora homicidas.

[[v23-1-22]]

^<<v23-1-22,22>>^ A tua prata tornou-se em escória, o teu vinho se misturou com água.

[[v23-1-23]]

^<<v23-1-23,23>>^ Os teus príncipes são rebeldes, e companheiros de ladrões; cada um deles ama as peitas, e anda atrás de presentes; não fazem justiça ao órfão, e não chega perante eles a causa da viúva.

[[v23-1-24]]

^<<v23-1-24,24>>^ portanto diz o Senhor Deus dos exércitos, o Poderoso de Israel: Ah! livrar-me-ei dos meus adversários, e vingar-me-ei dos meus inimigos.

[[v23-1-25]]

^<<v23-1-25,25>>^ Voltarei contra ti a minha mão, e purificarei como com potassa a tua escória; e tirar-te-ei toda impureza;

[[v23-1-26]]

^<<v23-1-26,26>>^ e te restituirei os teus juízes, como eram dantes, e os teus conselheiros, como no princípio, então serás chamada cidade de justiça, cidade fiel.

[[v23-1-27]]

^<<v23-1-27,27>>^ Sião será resgatada pela justiça, e os seus convertidos, pela retidão.

[[v23-1-28]]

^<<v23-1-28,28>>^ Mas os transgressores e os pecadores serão juntamente destruídos; e os que deixarem o Senhor serão consumidos.

[[v23-1-29]]

^<<v23-1-29,29>>^ Porque vos envergonhareis por causa dos terebintos de que vos agradastes, e sereis confundidos por causa dos jardins que escolhestes.

[[v23-1-30]]

^<<v23-1-30,30>>^ Pois sereis como um carvalho cujas folhas são murchas, e como um jardim que não tem água.

[[v23-1-31]]

^<<v23-1-31,31>>^ E o forte se tornará em estopa, e a sua obra em faísca; e ambos arderão juntamente, e não haverá quem os apague.

'''

xref:022-canticos/022-canticos-008.adoc#v22-8-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-isaias/023-isaias-002.adoc#v23-2-0[Próximo Capítulo &#62;]