include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-65-1]]

^<<v23-65-1,1>>^ Tornei-me acessível aos que não perguntavam por mim; fui achado daqueles que não me buscavam. A uma nação que não se chamava do meu nome eu disse: Eis-me aqui, eis-me aqui.

[[v23-65-2]]

^<<v23-65-2,2>>^ Estendi as minhas mãos o dia todo a um povo rebelde, que anda por um caminho que não é bom, após os seus próprios pensamentos;

[[v23-65-3]]

^<<v23-65-3,3>>^ povo que de contínuo me provoca diante da minha face, sacrificando em jardins e queimando incenso sobre tijolos;

[[v23-65-4]]

^<<v23-65-4,4>>^ que se assenta entre as sepulturas, e passa as noites junto aos lugares secretos; que come carne de porco, achando-se caldo de coisas abomináveis nas suas vasilhas;

[[v23-65-5]]

^<<v23-65-5,5>>^ e que dizem: Retira-te, e não te chegues a mim, porque sou mais santo do que tu. Estes são fumaça no meu nariz, um fogo que arde o dia todo.

[[v23-65-6]]

^<<v23-65-6,6>>^ Eis que está escrito diante de mim: Não me calarei, mas eu pagarei, sim, deitar-lhes-ei a recompensa no seu seio;

[[v23-65-7]]

^<<v23-65-7,7>>^ as suas iniqüidades, e juntamente as iniqüidades de seus pais, diz o Senhor, os quais queimaram incenso nos montes, e me afrontaram nos outeiros; pelo que lhes tornarei a medir as suas obras antigas no seu seio.

[[v23-65-8]]

^<<v23-65-8,8>>^ Assim diz o Senhor: Como quando se acha mosto num cacho de uvas, e se diz: Não o desperdices, pois há bênção nele; assim farei por amor de meus servos, para que eu não os destrua a todos.

[[v23-65-9]]

^<<v23-65-9,9>>^ E produzirei descendência a Jacó, e a Judá um herdeiro dos meus montes; e os meus escolhidos herdarão a terra e os meus servos nela habitarão.

[[v23-65-10]]

^<<v23-65-10,10>>^ E Sarom servirá de pasto de rebanhos, e o vale de Acor de repouso de gado, para o meu povo, que me buscou.

[[v23-65-11]]

^<<v23-65-11,11>>^ Mas a vós, os que vos apartais do Senhor, os que vos esqueceis do meu santo monte, os que preparais uma mesa para a fortuna, e que misturais vinho para o Destino

[[v23-65-12]]

^<<v23-65-12,12>>^ também vos destinarei à espada, e todos vos encurvareis à matança; porque quando chamei, não respondestes; quando falei, não ouvistes, mas fizestes o que era mau aos meus olhos, e escolhestes aquilo em que eu não tinha prazer.

[[v23-65-13]]

^<<v23-65-13,13>>^ Pelo que assim diz o Senhor Deus: Eis que os meus servos comerão, mas vós padecereis fome; eis que os meus servos beberão, mas vós tereis sede; eis que os meus servos se alegrarão, mas vós vos envergonhareis;

[[v23-65-14]]

^<<v23-65-14,14>>^ eis que os meus servos cantarão pela alegria de coração, mas vós chorareis pela tristeza de coração, e uivareis pela angústia de espírito.

[[v23-65-15]]

^<<v23-65-15,15>>^ E deixareis o vosso nome para maldição aos meus escolhidos; e vos matará o Senhor Deus, mas a seus servos chamará por outro nome.

[[v23-65-16]]

^<<v23-65-16,16>>^ De sorte que aquele que se bendisser na terra será bendito no Deus da verdade; e aquele que jurar na terra, jurará pelo Deus da verdade; porque já estão esquecidas as angústias passadas, e estão escondidas dos meus olhos.

[[v23-65-17]]

^<<v23-65-17,17>>^ Pois eis que eu crio novos céus e nova terra; e não haverá lembrança das coisas passadas, nem mais se recordarão:

[[v23-65-18]]

^<<v23-65-18,18>>^ Mas alegrai-vos e regozijai-vos perpetuamente no que eu crio; porque crio para Jerusalém motivo de exultação e para o seu povo motivo de gozo.

[[v23-65-19]]

^<<v23-65-19,19>>^ E exultarei em Jerusalém, e folgarei no meu povo; e nunca mais se ouvirá nela voz de choro nem voz de clamor.

[[v23-65-20]]

^<<v23-65-20,20>>^ Não haverá mais nela criança de poucos dias, nem velho que não tenha cumprido os seus dias; porque o menino morrerá de cem anos; mas o pecador de cem anos será amaldiçoado.

[[v23-65-21]]

^<<v23-65-21,21>>^ E eles edificarão casas, e as habitarão; e plantarão vinhas, e comerão o fruto delas.

[[v23-65-22]]

^<<v23-65-22,22>>^ Não edificarão para que outros habitem; não plantarão para que outros comam; porque os dias do meu povo serão como os dias da árvore, e os meus escolhidos gozarão por longo tempo das obras das suas mãos:

[[v23-65-23]]

^<<v23-65-23,23>>^ Não trabalharão debalde, nem terão filhos para calamidade; porque serão a descendência dos benditos do Senhor, e os seus descendentes estarão com eles.

[[v23-65-24]]

^<<v23-65-24,24>>^ E acontecerá que, antes de clamarem eles, eu responderei; e estando eles ainda falando, eu os ouvirei.

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro juntos se apascentarão, o leão comerá palha como o boi; e pó será a comida da serpente. Não farão mal nem dano algum em todo o meu santo monte, diz o Senhor.

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]