include::./index.adoc[]

[[v23-4-0]]
=== Isaías, 4
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-4-1]]

^<<v23-4-1,1>>^ Sete mulheres naquele dia lançarão mão dum só homem, dizendo: Nós comeremos do nosso pão, e nos vestiremos de nossos vestidos; tão somente queremos ser chamadas pelo teu nome; tira o nosso opróbrio.

[[v23-4-2]]

^<<v23-4-2,2>>^ Naquele dia o renovo do Senhor será cheio de beleza e de glória, e o fruto da terra excelente e formoso para os que escaparem de Israel.

[[v23-4-3]]

^<<v23-4-3,3>>^ E será que aquele que ficar em Sião e permanecer em Jerusalém, será chamado santo, isto é, todo aquele que estiver inscrito entre os vivos em Jerusalém;

[[v23-4-4]]

^<<v23-4-4,4>>^ Quando o Senhor tiver lavado a imundícia das filhas de Sião, e tiver limpado o sangue de Jerusalém do meio dela com o espírito de justiça, e com o espírito de ardor.

[[v23-4-5]]

^<<v23-4-5,5>>^ E criará o Senhor sobre toda a extensão do monte Sião, e sobre as assembléias dela, uma nuvem de dia, e uma fumaça, e um resplendor de fogo flamejante de noite; porque sobre toda a glória se estenderá um dossel.

[[v23-4-6]]

^<<v23-4-6,6>>^ Também haverá de dia um pavilhão para sombra contra o calor, e para refúgio e esconderijo contra a tempestade e a chuva.

'''

xref:023-isaias/023-isaias-003.adoc#v23-3-0[&#60; Capítulo Anterior] | <<v23-4-0,Topo>> | xref:023-isaias/023-isaias-005.adoc#v23-5-0[Próximo Capítulo &#62;]