include::./index.adoc[]

[[v23-11-0]]
=== Isaías, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-11-1]]

^<<v23-11-1,1>>^ Então brotará um rebento do toco de Jessé, e das suas raízes um renovo frutificará.

[[v23-11-2]]

^<<v23-11-2,2>>^ E repousará sobre ele o Espírito do Senhor, o espírito de sabedoria e de entendimento, o espírito de conselho e de fortaleza, o espírito de conhecimento e de temor do Senhor.

[[v23-11-3]]

^<<v23-11-3,3>>^ E deleitar-se-á no temor do Senhor; e não julgará segundo a vista dos seus olhos, nem decidirá segundo o ouvir dos seus ouvidos;

[[v23-11-4]]

^<<v23-11-4,4>>^ mas julgará com justiça os pobres, e decidirá com eqüidade em defesa dos mansos da terra; e ferirá a terra com a vara de sua boca, e com o sopro dos seus lábios matará o ímpio.

[[v23-11-5]]

^<<v23-11-5,5>>^ A justiça será o cinto dos seus lombos, e a fidelidade o cinto dos seus rins.

[[v23-11-6]]

^<<v23-11-6,6>>^ Morará o lobo com o cordeiro, e o leopardo com o cabrito se deitará; e o bezerro, e o leão novo e o animal cevado viverão juntos; e um menino pequeno os conduzirá.

[[v23-11-7]]

^<<v23-11-7,7>>^ A vaca e a ursa pastarão juntas, e as suas crias juntas se deitarão; e o leão comerá palha como o boi.

[[v23-11-8]]

^<<v23-11-8,8>>^ A criança de peito brincará sobre a toca da áspide, e a desmamada meterá a sua mão na cova do basilisco.

[[v23-11-9]]

^<<v23-11-9,9>>^ Não se fará mal nem dano algum em todo o meu santo monte; porque a terra se encherá do conhecimento do Senhor, como as águas cobrem o mar.

[[v23-11-10]]

^<<v23-11-10,10>>^ Naquele dia a raiz de Jessé será posta por estandarte dos povos, à qual recorrerão as nações; gloriosas lhe serão as suas moradas.

[[v23-11-11]]

^<<v23-11-11,11>>^ Naquele dia o Senhor tornará a estender a sua mão para adquirir outra vez e resto do seu povo, que for deixado, da Assíria, do Egito, de Patros, da Etiópia, de Elão, de Sinar, de Hamate, e das ilhas de mar.

[[v23-11-12]]

^<<v23-11-12,12>>^ Levantará um pendão entre as nações e ajuntará os desterrados de Israel, e es dispersos de Judá congregará desde os quatro confins da terra.

[[v23-11-13]]

^<<v23-11-13,13>>^ Também se esvaecerá a inveja de Efraim, e os vexadores de Judá serão desarraigados; Efraim não invejará a Judá e Judá não vexará a Efraim.

[[v23-11-14]]

^<<v23-11-14,14>>^ Antes voarão sobre os ombros dos filisteus ao Ocidente; juntos despojarão aos filhos do Oriente; em Edom e Moabe porão as suas mãos, e os filhos de Amom lhes obedecerão.

[[v23-11-15]]

^<<v23-11-15,15>>^ E o Senhor destruirá totalmente a língua do mar do Egito; e vibrará a sua mão contra o Rio com o seu vento abrasador, e, ferindo-o, dividi-lo-á em sete correntes, e fará que por ele passem a pé enxuto.

[[v23-11-16]]

^<<v23-11-16,16>>^ Assim haverá caminho plano para e restante do seu povo, que voltar da Assíria, como houve para Israel no dia em que subiu da terra do Egito.

'''

xref:023-isaias/023-isaias-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-isaias/023-isaias-012.adoc#v23-12-0[Próximo Capítulo &#62;]