include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-26-1]]

^<<v23-26-1,1>>^ Naquele dia se entoará este cântico na terra de Judá: uma cidade forte temos, a que Deus pôs a salvação por muros e antemuros.

[[v23-26-2]]

^<<v23-26-2,2>>^ Abri as portas, para que entre nela a nação justa, que observa a verdade.

[[v23-26-3]]

^<<v23-26-3,3>>^ Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiai sempre no Senhor; porque o Senhor Deus é uma rocha eterna.

[[v23-26-5]]

^<<v23-26-5,5>>^ porque ele tem derrubado os que habitam no alto, na cidade elevada; abate-a, abate-a até o chão; e a reduz até o pó.

[[v23-26-6]]

^<<v23-26-6,6>>^ Pisam-na os pés, os pés dos pobres, e os passos dos necessitados.

[[v23-26-7]]

^<<v23-26-7,7>>^ O caminho do justo é plano; tu, que és reto, nivelas a sua vereda.

[[v23-26-8]]

^<<v23-26-8,8>>^ No caminho dos teus juízos, Senhor, temos esperado por ti; no teu nome e na tua memória está o desejo da nossa alma.

[[v23-26-9]]

^<<v23-26-9,9>>^ Minha alma te deseja de noite; sim, o meu espírito, dentro de mim, diligentemente te busca; porque, quando os teus juízos estão na terra, os moradores do mundo aprendem justiça.

[[v23-26-10]]

^<<v23-26-10,10>>^ Ainda que se mostre favor ao ímpio, ele não aprende a justiça; até na terra da retidão ele pratica a iniqüidade, e não atenta para a majestade do Senhor.

[[v23-26-11]]

^<<v23-26-11,11>>^ Senhor, a tua mão está levantada, contudo eles não a vêem; vê-la-ão, porém, e confundir-se-ão por causa do zelo que tens do teu povo; e o fogo reservado para os teus adversários os devorará.

[[v23-26-12]]

^<<v23-26-12,12>>^ Senhor, tu hás de estabelecer para nós a paz; pois tu fizeste para nós todas as nossas obras.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó Senhor Deus nosso, outros senhores além de ti têm tido o domínio sobre nós; mas, por ti só, nos lembramos do teu nome.

[[v23-26-14]]

^<<v23-26-14,14>>^ Os falecidos não tornarão a viver; os mortos não ressuscitarão; por isso os visitaste e destruíste, e fizeste perecer toda a sua memória.

[[v23-26-15]]

^<<v23-26-15,15>>^ Tu, Senhor, aumentaste a nação; aumentaste a nação e te fizeste glorioso; alargaste todos os confins da terra.

[[v23-26-16]]

^<<v23-26-16,16>>^ Senhor, na angústia te buscaram; quando lhes sobreveio a tua correção, derramaram-se em oração.

[[v23-26-17]]

^<<v23-26-17,17>>^ Como a mulher grávida, quando está próxima a sua hora, tem dores de parto e dá gritos nas suas dores, assim fomos nós diante de ti, ó Senhor!

[[v23-26-18]]

^<<v23-26-18,18>>^ Concebemos nós, e tivemos dores de parto, mas isso foi como se tivéssemos dado à luz o vento; livramento não trouxemos à terra; nem nasceram moradores do mundo.

[[v23-26-19]]

^<<v23-26-19,19>>^ Os teus mortos viverão, os seus corpos ressuscitarão; despertai e exultai, vós que habitais no pó; porque o teu orvalho é orvalho de luz, e sobre a terra das sombras fá-lo-ás cair.

[[v23-26-20]]

^<<v23-26-20,20>>^ Vem, povo meu, entra nas tuas câmaras, e fecha as tuas portas sobre ti; esconde-te só por um momento, até que passe a indignação.

[[v23-26-21]]

^<<v23-26-21,21>>^ Pois eis que o Senhor está saindo do seu lugar para castigar os moradores da terra por causa da sua iniqüidade; e a terra descobrirá o seu sangue, e não encobrirá mais os seus mortos.

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]