include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-45-1]]

^<<v23-45-1,1>>^ Assim diz o Senhor ao seu ungido, a Ciro, a quem tomo pela mão direita, para abater nações diante de sua face, e descingir os lombos dos reis; para abrir diante dele as portas, e as portas não se fecharão;

[[v23-45-2]]

^<<v23-45-2,2>>^ eu irei adiante de ti, e tornarei planos os lugares escabrosos; quebrarei as portas de bronze, e despedaçarei os ferrolhos de ferro.

[[v23-45-3]]

^<<v23-45-3,3>>^ Dar-te-ei os tesouros das trevas, e as riquezas encobertas, para que saibas que eu sou o Senhor, o Deus de Israel, que te chamo pelo teu nome.

[[v23-45-4]]

^<<v23-45-4,4>>^ Por amor de meu servo Jacó, e de Israel, meu escolhido, eu te chamo pelo teu nome; ponho-te o teu sobrenome, ainda que não me conheças.

[[v23-45-5]]

^<<v23-45-5,5>>^ Eu sou o Senhor, e não há outro; fora de mim não há Deus; eu te cinjo, ainda que tu não me conheças.

[[v23-45-6]]

^<<v23-45-6,6>>^ Para que se saiba desde o nascente do sol, e desde o poente, que fora de mim não há outro; eu sou o Senhor, e não há outro.

[[v23-45-7]]

^<<v23-45-7,7>>^ Eu formo a luz, e crio as trevas; eu faço a paz, e crio o mal; eu sou o Senhor, que faço todas estas coisas.

[[v23-45-8]]

^<<v23-45-8,8>>^ Destilai vós, céus, dessas alturas a justiça, e chovam-na as nuvens; abra-se a terra, e produza a salvação e ao mesmo tempo faça nascer a justiça; eu, o Senhor, as criei:

[[v23-45-9]]

^<<v23-45-9,9>>^ Ai daquele que contende com o seu Criador! o caco entre outros cacos de barro! Porventura dirá o barro ao que o formou: Que fazes? ou dirá a tua obra: Não tens mãos?

[[v23-45-10]]

^<<v23-45-10,10>>^ Ai daquele que diz ao pai: Que é o que geras? e à mulher: Que dás tu à luz?

[[v23-45-11]]

^<<v23-45-11,11>>^ Assim diz o Senhor, o Santo de Israel, aquele que o formou: Perguntai-me as coisas futuras; demandai-me acerca de meus filhos, e acerca da obra das minhas mãos.

[[v23-45-12]]

^<<v23-45-12,12>>^ Eu é que fiz a terra, e nela criei o homem; as minhas mãos estenderam os céus, e a todo o seu exército dei as minhas ordens.

[[v23-45-13]]

^<<v23-45-13,13>>^ Eu o despertei em justiça, e todos os seus caminhos endireitarei; ele edificará a minha cidade, e libertará os meus cativos, não por preço nem por presentes, diz o Senhor dos exércitos.

[[v23-45-14]]

^<<v23-45-14,14>>^ Assim diz o Senhor: A riqueza do Egito, e as mercadorias da Etiópia, e os sabeus, homens de alta estatura, passarão para ti, e serão teus; irão atrás de ti; em grilhões virão; e, prostrando-se diante de ti, far-te-ão as suas súplicas, dizendo: Deus está contigo somente; e não há nenhum outro Deus.

[[v23-45-15]]

^<<v23-45-15,15>>^ Verdadeiramente tu és um Deus que te ocultas, ó Deus de Israel, o Salvador.

[[v23-45-16]]

^<<v23-45-16,16>>^ Envergonhar-se-ão, e também se confundirão todos; cairão juntos em ignomínia os que fabricam ídolos.

[[v23-45-17]]

^<<v23-45-17,17>>^ Mas Israel será salvo pelo Senhor, com uma salvação eterna; pelo que não sereis jamais envergonhados nem confundidos em toda a eternidade.

[[v23-45-18]]

^<<v23-45-18,18>>^ Porque assim diz o Senhor, que criou os céus, o Deus que formou a terra, que a fez e a estabeleceu, não a criando para ser um caos, mas para ser habitada: Eu sou o Senhor e não há outro.

[[v23-45-19]]

^<<v23-45-19,19>>^ Não falei em segredo, nalgum lugar tenebroso da terra; não disse à descendência de Jacó: Buscai-me no caos; eu, o Senhor, falo a justiça, e proclamo o que é reto.

[[v23-45-20]]

^<<v23-45-20,20>>^ Congregai-vos, e vinde; chegai-vos juntos, os que escapastes das nações; nada sabem os que conduzem em procissão as suas imagens de escultura, feitas de madeira, e rogam a um deus que não pode salvar.

[[v23-45-21]]

^<<v23-45-21,21>>^ Anunciai e apresentai as razões: tomai conselho todos juntos. Quem mostrou isso desde a antigüidade? quem de há muito o anunciou? Porventura não sou eu, o Senhor? Pois não há outro Deus senão eu; Deus justo e Salvador não há além de mim.

[[v23-45-22]]

^<<v23-45-22,22>>^ Olhai para mim, e sereis salvos, vós, todos os confins da terra; porque eu sou Deus, e não há outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Por mim mesmo jurei; já saiu da minha boca a palavra de justiça, e não tornará atrás. Diante de mim se dobrará todo joelho, e jurará toda língua.

[[v23-45-24]]

^<<v23-45-24,24>>^ De mim se dirá: Tão somente no senhor há justiça e força. A ele virão, envergonhados, todos os que se irritarem contra ele.

[[v23-45-25]]

^<<v23-45-25,25>>^ Mas no Senhor será justificada e se gloriará toda a descendência de Israel.

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]