include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-22-1]]

^<<v23-22-1,1>>^ Oráculo acerca do vale da visão. Que tens agora, pois que com todos os teus subiste aos telhados?

[[v23-22-2]]

^<<v23-22-2,2>>^ e tu que estás cheia de clamor, cidade turbulenta, cidade alegre; os teus mortos não são mortos à espada, nem mortos em guerra.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os teus homens principais juntamente fugiram, sem o arco foram presos; todos os que em ti se acharam, foram presos juntamente, embora tivessem fugido para longe.

[[v23-22-4]]

^<<v23-22-4,4>>^ Portanto digo: Desviai de mim a vista, e chorarei amargamente; não vos canseis mais em consolar-me pela destruição da filha do meu povo.

[[v23-22-5]]

^<<v23-22-5,5>>^ Porque dia de destroço, de atropelamento, e de confusão é este da parte do Senhor Deus dos exércitos, no vale da visão; um derrubar de muros, e um clamor até as montanhas.

[[v23-22-6]]

^<<v23-22-6,6>>^ Elão tomou a aljava, juntamente com carros e cavaleiros, e Quir descobriu os escudos.

[[v23-22-7]]

^<<v23-22-7,7>>^ Os teus mais formosos vales ficaram cheios de carros, e os cavaleiros postaram-se contra as portas.

[[v23-22-8]]

^<<v23-22-8,8>>^ Tirou-se a cobertura de Judá; e naquele dia olhaste para as armas da casa do bosque.

[[v23-22-9]]

^<<v23-22-9,9>>^ E vistes que as brechas da cidade de Davi eram muitas; e ajuntastes as águas da piscina de baixo;

[[v23-22-10]]

^<<v23-22-10,10>>^ e contastes as casas de Jerusalém, e derrubastes as casas, para fortalecer os muros;

[[v23-22-11]]

^<<v23-22-11,11>>^ fizestes também um reservatório entre os dois muros para as águas da piscina velha; mas não olhastes para aquele que o tinha feito, nem considerastes o que o formou desde a antiguidade.

[[v23-22-12]]

^<<v23-22-12,12>>^ O Senhor Deus dos exércitos vos convidou naquele dia para chorar e prantear, para rapar a cabeça e cingir o cilício;

[[v23-22-13]]

^<<v23-22-13,13>>^ mas eis aqui gozo e alegria; matam-se bois, degolam-se ovelhas, come-se carne, bebe-se vinho, e se diz: Comamos e bebamos, porque amanhã morreremos.

[[v23-22-14]]

^<<v23-22-14,14>>^ Mas o Senhor dos exércitos revelou-se aos meus ouvidos, dizendo: Certamente esta maldade não se vos perdoará até que morrais, diz o Senhor Deus dos exércitos.

[[v23-22-15]]

^<<v23-22-15,15>>^ Assim diz o Senhor Deus dos exércitos: Anda, vai ter com esse administrador, Sebna, o mordomo, e pergunta-lhe:

[[v23-22-16]]

^<<v23-22-16,16>>^ Que fazes aqui? ou que parente tens tu aqui, para que cavasses aqui uma sepultura? Cavando em lugar alto a tua sepultura, cinzelando na rocha morada para ti mesmo!

[[v23-22-17]]

^<<v23-22-17,17>>^ Eis que o Senhor te arrojará violentamente, ó homem forte, e seguramente te prenderá.

[[v23-22-18]]

^<<v23-22-18,18>>^ Certamente te enrolará como uma bola, e te lançará para um país espaçoso. Ali morrerás, e ali irão os teus magníficos carros, ó tu, opróbrio da casa do teu senhor.

[[v23-22-19]]

^<<v23-22-19,19>>^ E demitir-te-ei do teu posto; e da tua categoria serás derrubado.

[[v23-22-20]]

^<<v23-22-20,20>>^ Naquele dia chamarei a meu servo Eliaquim, filho de Hilquias,

[[v23-22-21]]

^<<v23-22-21,21>>^ e vesti-lo-ei da tua túnica, e cingi-lo-ei com o teu cinto, e entregarei nas suas mãos o teu governo; e ele será como pai para os moradores de Jerusalém, e para a casa de Judá.

[[v23-22-22]]

^<<v23-22-22,22>>^ Porei a chave da casa de Davi sobre o seu ombro; ele abrirá, e ninguém fechará; fechará, e ninguém abrirá.

[[v23-22-23]]

^<<v23-22-23,23>>^ E fixá-lo-ei como a um prego num lugar firme; e será como um trono de honra para a casa de seu pai.

[[v23-22-24]]

^<<v23-22-24,24>>^ Nele, pois, pendurarão toda a glória da casa de seu pai, a prole e a progênie, todos os vasos menores, desde as taças até os jarros.

[[v23-22-25]]

^<<v23-22-25,25>>^ Naquele dia, diz o Senhor dos exércitos, cederá o prego fincado em lugar firme; será cortado, e cairá; e a carga que nele estava se desprenderá, porque o Senhor o disse.

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]