include::./index.adoc[]

[[v23-3-0]]
=== Isaías, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-3-1]]

^<<v23-3-1,1>>^ Porque eis que o Senhor Deus dos exércitos está tirando de Jerusalém e de Judá o bordão e o cajado, isto é, todo o recurso de pão, e todo o recurso de água;

[[v23-3-2]]

^<<v23-3-2,2>>^ o valente e o soldado, o juiz e o profeta, o adivinho e o ancião;

[[v23-3-3]]

^<<v23-3-3,3>>^ o capitão de cinqüenta e o respeitável, o conselheiro, o artífice hábil e o encantador perito;

[[v23-3-4]]

^<<v23-3-4,4>>^ e dar-lhes-ei meninos por príncipes, e crianças governarão sobre eles.

[[v23-3-5]]

^<<v23-3-5,5>>^ O povo será oprimido; um será contra o outro, e cada um contra o seu próximo; o menino se atreverá contra o ancião, e o vil contra o nobre.

[[v23-3-6]]

^<<v23-3-6,6>>^ Quando alguém pegar de seu irmão na casa de seu pai, dizendo: Tu tens roupa, tu serás o nosso príncipe, e tomarás sob a tua mão esta ruína.

[[v23-3-7]]

^<<v23-3-7,7>>^ Naquele dia levantará este a sua voz, dizendo: Não quero ser médico; pois em minha casa não há pão nem roupa; não me haveis de constituir governador sobre o povo.

[[v23-3-8]]

^<<v23-3-8,8>>^ Pois Jerusalém tropeçou, e Judá caiu; porque a sua língua e as suas obras são contra o Senhor, para afrontarem a sua gloriosa presença.

[[v23-3-9]]

^<<v23-3-9,9>>^ O aspecto do semblante dá testemunho contra eles; e, como Sodoma, publicam os seus pecados sem os disfarçar. Ai da sua alma! porque eles fazem mal a si mesmos.

[[v23-3-10]]

^<<v23-3-10,10>>^ Dizei aos justos que bem lhes irá; porque comerão do fruto das suas obras.

[[v23-3-11]]

^<<v23-3-11,11>>^ Ai do ímpio! mal lhe irá; pois se lhe fará o que as suas mãos fizeram.

[[v23-3-12]]

^<<v23-3-12,12>>^ Quanto ao meu povo, crianças são os seus opressores, e mulheres dominam sobre eles. Ah, povo meu! os que te guiam te enganam, e destroem o caminho das tuas veredas.

[[v23-3-13]]

^<<v23-3-13,13>>^ O Senhor levanta-se para pleitear, e põe-se de pé para julgar os povos.

[[v23-3-14]]

^<<v23-3-14,14>>^ O Senhor entra em juízo contra os anciãos do seu povo, e contra os seus príncipes; sois vós que consumistes a vinha; o espólio do pobre está em vossas casas.

[[v23-3-15]]

^<<v23-3-15,15>>^ Que quereis vós, que esmagais o meu povo e moeis o rosto do pobre? diz o Senhor Deus dos exércitos.

[[v23-3-16]]

^<<v23-3-16,16>>^ Diz ainda mais o Senhor: Porquanto as filhas de Sião são altivas, e andam de pescoço emproado, lançando olhares impudentes; e, ao andarem, vão de passos curtos, fazendo tinir os ornamentos dos seus pés;

[[v23-3-17]]

^<<v23-3-17,17>>^ o Senhor fará tinhosa a cabeça das filhas de Sião, e o Senhor porá a descoberto a sua nudez.

[[v23-3-18]]

^<<v23-3-18,18>>^ Naquele dia tirará o Senhor os seus enfeites: os anéis dos artelhos, as toucas, os colares em forma de meia lua,

[[v23-3-19]]

^<<v23-3-19,19>>^ os pendentes, e os braceletes, e os véus;

[[v23-3-20]]

^<<v23-3-20,20>>^ os diademas, as cadeias dos artelhos, os cintos, as caixinhas de perfumes e os amuletos;

[[v23-3-21]]

^<<v23-3-21,21>>^ os anéis, e as jóias pendentes do nariz;

[[v23-3-22]]

^<<v23-3-22,22>>^ os vestidos de festa, e os mantos, e os xales, e os bolsos;

[[v23-3-23]]

^<<v23-3-23,23>>^ os vestidos diáfanos, e as capinhas de linho, e os turbantes, e os véus.

[[v23-3-24]]

^<<v23-3-24,24>>^ E será que em lugar de perfume haverá mau cheiro, e por cinto, uma corda; em lugar de encrespadura de cabelos, calvície; e em lugar de veste luxuosa, cinto de cilício; e queimadura em lugar de formosura.

[[v23-3-25]]

^<<v23-3-25,25>>^ Teus varões cairão à espada, e teus valentes na guerra.

[[v23-3-26]]

^<<v23-3-26,26>>^ E as portas da cidade gemerão e se carpirão e, desolada, ela se sentará no pó.

'''

xref:023-isaias/023-isaias-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaias/023-isaias-004.adoc#v23-4-0[Próximo Capítulo &#62;]