include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-5-1]]

^<<v23-5-1,1>>^ Ora, seja-me permitido cantar para o meu bem amado uma canção de amor a respeito da sua vinha. O meu amado possuía uma vinha num outeiro fertilíssimo.

[[v23-5-2]]

^<<v23-5-2,2>>^ E, revolvendo-a com enxada e limpando-a das pedras, plantou-a de excelentes vides, e edificou no meio dela uma torre, e também construiu nela um lagar; e esperava que desse uvas, mas deu uvas bravas.

[[v23-5-3]]

^<<v23-5-3,3>>^ Agora, pois, ó moradores de Jerusalém, e homens de Judá, julgai, vos peço, entre mim e a minha vinha.

[[v23-5-4]]

^<<v23-5-4,4>>^ Que mais se podia fazer à minha vinha, que eu lhe não tenha feito? e por que, esperando eu que desse uvas, veio a produzir uvas bravas?

[[v23-5-5]]

^<<v23-5-5,5>>^ Agora, pois, vos farei saber o que eu hei de fazer à minha vinha: tirarei a sua sebe, e será devorada; derrubarei a sua parede, e será pisada;

[[v23-5-6]]

^<<v23-5-6,6>>^ e a tornarei em deserto; não será podada nem cavada, mas crescerão nela sarças e espinheiro; e às nuvens darei ordem que não derramem chuva sobre ela.

[[v23-5-7]]

^<<v23-5-7,7>>^ Pois a vinha do Senhor dos exércitos é a casa de Israel, e os homens de Judá são a planta das suas delícias; e esperou que exercessem juízo, mas eis aqui derramamento de sangue; justiça, e eis aqui clamor.

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai dos que ajuntam casa a casa, dos que acrescentam campo a campo, até que não haja mais lugar, de modo que habitem sós no meio da terra!

[[v23-5-9]]

^<<v23-5-9,9>>^ A meus ouvidos disse o Senhor dos exércitos: Em verdade que muitas casas ficarão desertas, e até casas grandes e lindas sem moradores.

[[v23-5-10]]

^<<v23-5-10,10>>^ E dez jeiras de vinha darão apenas um bato, e um hômer de semente não dará mais do que uma efa.

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que se levantam cedo para correrem atrás da bebida forte e continuam até a noite, até que o vinho os esquente!

[[v23-5-12]]

^<<v23-5-12,12>>^ Têm harpas e alaúdes, tamboris e pífanos, e vinho nos seus banquetes; porém não olham para a obra do Senhor, nem consideram as obras das mãos dele.

[[v23-5-13]]

^<<v23-5-13,13>>^ Portanto o meu povo é levado cativo, por falta de entendimento; e os seus nobres estão morrendo de fome, e a sua multidão está seca de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ Por isso o Seol aumentou o seu apetite, e abriu a sua boca desmesuradamente; e para lá descem a glória deles, a sua multidão, a sua pompa, e os que entre eles se exultam.

[[v23-5-15]]

^<<v23-5-15,15>>^ O homem se abate, e o varão se humilha, e os olhos dos altivos se abaixam.

[[v23-5-16]]

^<<v23-5-16,16>>^ Mas o Senhor dos exércitos é exaltado pelo juízo, e Deus, o Santo, é santificado em justiça.

[[v23-5-17]]

^<<v23-5-17,17>>^ Então os cordeiros pastarão como em seus pastos; e nos campos desertos se apascentarão cevados e cabritos.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que puxam a iniqüidade com cordas de falsidade, e o pecado como com tirantes de carros!

[[v23-5-19]]

^<<v23-5-19,19>>^ E dizem: Apresse-se Deus, avie a sua obra, para que a vejamos; e aproxime-se e venha o propósito do Santo de Israel, para que o conheçamos.

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que ao mal chamam bem, e ao bem mal; que põem as trevas por luz, e a luz por trevas, e o amargo por doce, e o doce por amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que são sábios a seus próprios olhos, e astutos em seu próprio conceito!

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são poderosos para beber vinho, e valentes para misturar bebida forte;

[[v23-5-23]]

^<<v23-5-23,23>>^ dos que justificam o ímpio por peitas, e ao inocente lhe tiram o seu direito!

[[v23-5-24]]

^<<v23-5-24,24>>^ Pelo que, como a língua de fogo consome o restolho, e a palha se desfaz na chama assim a raiz deles será como podridão, e a sua flor se esvaecerá como pó; porque rejeitaram a lei do Senhor dos exércitos, e desprezaram a palavra do santo de Israel,

[[v23-5-25]]

^<<v23-5-25,25>>^ Por isso se acendeu a ira do Senhor contra o seu povo, e o Senhor estendeu a sua mão contra ele, e o feriu; e as montanhas tremeram, e os seus cadáveres eram como lixo no meio das ruas; com tudo isto não tornou atrás a sua ira, mas ainda está estendida a sua mão.

[[v23-5-26]]

^<<v23-5-26,26>>^ E ele arvorará um estandarte para as nações de longe, e lhes assobiará desde a extremidade da terra; e eis que virão muito apressadamente.

[[v23-5-27]]

^<<v23-5-27,27>>^ Não há entre eles cansado algum nem quem tropece; ninguém cochila nem dorme; não se lhe desata o cinto dos lombos, nem se lhe quebra a correia dos sapatos.

[[v23-5-28]]

^<<v23-5-28,28>>^ As suas flechas são agudas, e todos os seus arcos retesados; os cascos dos seus cavalos são reputados como pederneira, e as rodas dos seus carros qual redemoinho.

[[v23-5-29]]

^<<v23-5-29,29>>^ O seu rugido é como o do leão; rugem como filhos de leão; sim, rugem e agarram a presa, e a levam, e não há quem a livre.

[[v23-5-30]]

^<<v23-5-30,30>>^ E bramarão contra eles naquele dia, como o bramido do mar; e se alguém olhar para a terra, eis que só verá trevas e angústia, e a luz se escurecerá nas nuvens sobre ela.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]