include::./index.adoc[]

[[v23-2-0]]
=== Isaías, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v23-2-1]]

^<<v23-2-1,1>>^ A visão que teve Isaías, filho de Amoz, a respeito de Judá e de Jerusalém.

[[v23-2-2]]

^<<v23-2-2,2>>^ Acontecerá nos últimos dias que se firmará o monte da casa do Senhor, será estabelecido como o mais alto dos montes e se elevará por cima dos outeiros; e concorrerão a ele todas as nações.

[[v23-2-3]]

^<<v23-2-3,3>>^ Irão muitos povos, e dirão: Vinde, e subamos ao monte do Senhor, à casa do Deus de Jacó, para que nos ensine os seus caminhos, e andemos nas suas veredas; porque de Sião sairá a lei, e de Jerusalém a palavra do Senhor.

[[v23-2-4]]

^<<v23-2-4,4>>^ E ele julgará entre as nações, e repreenderá a muitos povos; e estes converterão as suas espadas em relhas de arado, e as suas lanças em foices; uma nação não levantará espada contra outra nação, nem aprenderão mais a guerra.

[[v23-2-5]]

^<<v23-2-5,5>>^ Vinde, ó casa de Jacó, e andemos na luz do Senhor.

[[v23-2-6]]

^<<v23-2-6,6>>^ Mas tu rejeitaste o teu povo, a casa de Jacó; porque estão cheios de adivinhadores do Oriente, e de agoureiros, como os filisteus, e fazem alianças com os filhos dos estrangeiros.

[[v23-2-7]]

^<<v23-2-7,7>>^ A sua terra está cheia de prata e ouro, e são sem limite os seus tesouros; a sua terra está cheia de cavalos, e os seus carros não tem fim.

[[v23-2-8]]

^<<v23-2-8,8>>^ Também a sua terra está cheia de ídolos; inclinam-se perante a obra das suas mãos, diante daquilo que os seus dedos fabricaram.

[[v23-2-9]]

^<<v23-2-9,9>>^ Assim, pois, o homem é abatido, e o varão é humilhado; não lhes perdoes!

[[v23-2-10]]

^<<v23-2-10,10>>^ Entra nas rochas, e esconde-te no pó, de diante da espantosa presença do Senhor e da glória da sua majestade.

[[v23-2-11]]

^<<v23-2-11,11>>^ Os olhos altivos do homem serão abatidos, e a altivez dos varões será humilhada, e só o Senhor será exaltado naquele dia.

[[v23-2-12]]

^<<v23-2-12,12>>^ Pois o Senhor dos exércitos tem um dia contra todo soberbo e altivo, e contra todo o que se exalta, para que seja abatido;

[[v23-2-13]]

^<<v23-2-13,13>>^ contra todos os cedros do Líbano, altos e sublimes; e contra todos os carvalhos de Basã;

[[v23-2-14]]

^<<v23-2-14,14>>^ contra todos os montes altos, e contra todos os outeiros elevados;

[[v23-2-15]]

^<<v23-2-15,15>>^ contra toda torre alta, e contra todo muro fortificado;

[[v23-2-16]]

^<<v23-2-16,16>>^ e contra todos os navios de Társis, e contra toda a nau vistosa.

[[v23-2-17]]

^<<v23-2-17,17>>^ E a altivez do homem será humilhada, e o orgulho dos varões se abaterá, e só o Senhor será exaltado naquele dia.

[[v23-2-18]]

^<<v23-2-18,18>>^ E os ídolos desaparecerão completamente.

[[v23-2-19]]

^<<v23-2-19,19>>^ Então os homens se meterão nas cavernas das rochas, e nas covas da terra, por causa da presença espantosa do Senhor, e da glória da sua majestade, quando ele se levantar para assombrar a terra.

[[v23-2-20]]

^<<v23-2-20,20>>^ Naquele dia o homem lançará às toupeiras e aos morcegos os seus ídolos de prata, e os seus ídolos de ouro, que fizeram para ante eles se prostrarem,

[[v23-2-21]]

^<<v23-2-21,21>>^ para se meter nas fendas das rochas, e nas cavernas das penhas, por causa da presença espantosa do Senhor e da glória da sua majestade, quando ele se levantar para assombrar a terra.

[[v23-2-22]]

^<<v23-2-22,22>>^ Deixai-vos pois do homem cujo fôlego está no seu nariz; porque em que se deve ele estimar?

'''

xref:023-isaias/023-isaias-001.adoc#v23-1-0[&#60; Capítulo Anterior] | <<v23-2-0,Topo>> | xref:023-isaias/023-isaias-003.adoc#v23-3-0[Próximo Capítulo &#62;]