include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-49-1]]

^<<v24-49-1,1>>^ A respeito dos filhos de Amom. Assim diz o Senhor: Acaso Israel não tem filhos? Não tem herdeiro? Por que, então, possui Milcom a Gade, e o seu povo habita nas suas cidades?

[[v24-49-2]]

^<<v24-49-2,2>>^ Portanto, eis que vêm os dias, diz o Senhor, em que farei ouvir contra Rabá dos filhos de Amom o alarido de guerra, e tornar-se-á num montão de ruínas, e os seus arrabaldes serão queimados a fogo; então Israel deserdará aos que e deserdaram a ele, diz o Senhor.

[[v24-49-3]]

^<<v24-49-3,3>>^ Uiva, ó Hesbom, porque é destruída Ai; clamai, ó filhas de Rabá, cingi-vos de sacos; lamentai, e dai voltas pelas sebes; porque Milcom irá em cativeiro, juntamente com os seus sacerdotes e os seus príncipes.

[[v24-49-4]]

^<<v24-49-4,4>>^ Por que te glorias nos vales, teus luxuriantes vales, ó filha apóstata? que confias nos teus tesouros, dizendo: Quem virá contra mim?

[[v24-49-5]]

^<<v24-49-5,5>>^ Eis que farei vir sobre ti pavor, diz o Senhor Deus dos exércitos, de todos os que estão ao redor de ti; e sereis lançados fora, cada um para diante, e ninguém recolherá o desgarrado.

[[v24-49-6]]

^<<v24-49-6,6>>^ Mas depois disto farei voltar do cativeiro os filhos de Amom, diz o senhor.

[[v24-49-7]]

^<<v24-49-7,7>>^ A respeito de Edom. Assim diz o Senhor dos exércitos: Acaso não há mais sabedoria em Temã? Pereceu o conselho dos entendidos? Desvaneceu-se-lhes a sabedoria?

[[v24-49-8]]

^<<v24-49-8,8>>^ Fugi, voltai, habitai em profundezas, ó moradores de Dedã; porque trarei sobre ele a calamidade de Esaú, o tempo em que o punirei.

[[v24-49-9]]

^<<v24-49-9,9>>^ Se vindimadores viessem a ti, não deixariam alguns rabiscos? se ladrões de noite, não te danificariam só o quanto lhes bastasse?

[[v24-49-10]]

^<<v24-49-10,10>>^ Mas eu desnudei a Esaú, descobri os seus esconderijos, de modo que ele não se poderá esconder. E despojada a sua descendência, como também seus irmãos e seus vizinhos, e ele já não existe.

[[v24-49-11]]

^<<v24-49-11,11>>^ Deixa os teus órfãos, eu os guardarei em vida; e as tuas viúvas confiem em mim.

[[v24-49-12]]

^<<v24-49-12,12>>^ Pois assim diz o Senhor: Eis que os que não estavam condenados a beber o copo, certamente o beberão; e ficarias tu inteiramente impune? Não ficarás impune, mas certamente o beberás.

[[v24-49-13]]

^<<v24-49-13,13>>^ Pois por mim mesmo jurei, diz o Senhor, que Bozra servirá de objeto de espanto, de opróbrio, de ruína, e de maldição; e todas as suas cidades se tornarão em desolações perpétuas.

[[v24-49-14]]

^<<v24-49-14,14>>^ Eu ouvi novas da parte do Senhor, que um embaixador é enviado por entre as nações para lhes dizer: Ajuntai-vos, e vinde contra ela, e levantai-vos para a guerra.

[[v24-49-15]]

^<<v24-49-15,15>>^ Pois eis que te farei pequeno entre as nações, desprezado entre os homens.

[[v24-49-16]]

^<<v24-49-16,16>>^ Quanto à tua terribilidade, enganou-te a arrogância do teu coração, ó tu que habitas nas cavernas dos penhascos, que ocupas as alturas dos outeiros; ainda que ponhas o teu ninho no alto como a águia, de lá te derrubarei, diz o Senhor.

[[v24-49-17]]

^<<v24-49-17,17>>^ E Edom se tornará em objeto de espanto; todo aquele que passar por ela se espantará, e assobiará por causa de todas as suas pragas.

[[v24-49-18]]

^<<v24-49-18,18>>^ Como na subversão de Sodoma e Gomorra, e das cidades circunvizinhas, diz o Senhor, não habitará ninguém ali, nem peregrinará nela filho de homem.

[[v24-49-19]]

^<<v24-49-19,19>>^ Eis que como leão subirá das margens do Jordão um inimigo contra a morada forte; mas de repente o farei correr dali; e ao escolhido, pô-lo-ei sobre ela. Pois quem é semelhante a mim? e quem me fixará um prazo? e quem é o pastor que me poderá resistir?

[[v24-49-20]]

^<<v24-49-20,20>>^ Portanto ouvi o conselho do Senhor, que ele decretou contra Edom, e os seus desígnios, que ele intentou contra os moradores de Temã: Até os mais novos do rebanho serão arrastados; certamente ele assolará as suas moradas sobre eles.

[[v24-49-21]]

^<<v24-49-21,21>>^ A terra estremecerá com o estrondo da sua queda; o som do seu clamor se ouvirá até o Mar Vermelho.

[[v24-49-22]]

^<<v24-49-22,22>>^ Eis que como águia subirá, e voará, e estenderá as suas asas contra Bozra; e o coração do valente de Edom naquele dia se tornará como o coração da mulher que está em dores de parto.

[[v24-49-23]]

^<<v24-49-23,23>>^ A respeito de Damasco. Envergonhadas estão Hamate e Arpade, e se derretem de medo porquanto ouviram más notícias; estão agitadas como o mar, que não pode aquietar-se.

[[v24-49-24]]

^<<v24-49-24,24>>^ Enfraquecida está Damasco, virou as costas para fugir, e o tremor apoderou-se dela; angústia e dores apossaram-se dela como da mulher que está de parto.

[[v24-49-25]]

^<<v24-49-25,25>>^ Como está abandonada a cidade famosa, a cidade da minha alegria!

[[v24-49-26]]

^<<v24-49-26,26>>^ Portanto os seus jovens lhe cairão nas ruas, e todos os homens de guerra serão consumidos naquele dia, diz o Senhor dos exércitos.

[[v24-49-27]]

^<<v24-49-27,27>>^ E acenderei fogo no muro de Damasco, o qual consumirá os palácios de Ben-Hadade.

[[v24-49-28]]

^<<v24-49-28,28>>^ A respeito de Quedar, e dos reinos de Hazor, que Nabucodonosor, rei de Babilônia, feriu. Assim diz o Senhor: Levantai-vos, subi contra Quedar, e destruí os filhos do Oriente.

[[v24-49-29]]

^<<v24-49-29,29>>^ As suas tendas e os seus rebanhos serão tomados; as suas cortinas serão levadas, como também todos os seus vasos, e os seus camelos; e lhes gritarão: Há terror de todos os lados!

[[v24-49-30]]

^<<v24-49-30,30>>^ Fugi, desviai-vos para muito longe, habitai nas profundezas, ó moradores de Hazor, diz o Senhor; porque Nabucodonosor, rei de Babilônia, tomou conselho contra vós, e formou um desígnio contra vós.

[[v24-49-31]]

^<<v24-49-31,31>>^ Levantai-vos, subi contra uma nação que está sossegada, que habita descuidada, diz o Senhor; que não tem portas nem ferrolhos, que habita a sós.

[[v24-49-32]]

^<<v24-49-32,32>>^ E os seus camelos serão para presa e a multidão do seu gado para despojo; e espalharei a todo o vento aqueles que cortam os cantos da sua cabeleira; e de todos os lados lhes trarei a sua calamidade, diz o Senhor.

[[v24-49-33]]

^<<v24-49-33,33>>^ Assim Hazor se tornará em morada de chacais, em desolação para sempre; ninguém habitará ali, nem peregrinará nela filho de homem.

[[v24-49-34]]

^<<v24-49-34,34>>^ A palavra do Senhor, que veio a Jeremias, o profeta, acerca de Elão, no princípio do reinado de Zedequias, rei de Judá, dizendo:

[[v24-49-35]]

^<<v24-49-35,35>>^ Assim diz o Senhor dos exércitos: Eis que eu quebrarei o arco de Elão, o principal do seu poder.

[[v24-49-36]]

^<<v24-49-36,36>>^ E trarei sobre Elão os quatro ventos dos quatro cantos dos céus, e os espalharei para todos estes ventos; e não haverá nação aonde não cheguem os fugitivos de Elão.

[[v24-49-37]]

^<<v24-49-37,37>>^ E farei que Elão desfaleça diante de seus inimigos e diante dos que procuram a sua morte. Farei vir sobre eles o mal, o furor da minha ira, diz o Senhor; e enviarei após eles a espada, até que eu os tenha consumido.

[[v24-49-38]]

^<<v24-49-38,38>>^ E porei o meu trono em Elão, e destruirei dali rei e príncipes, diz o Senhor.

[[v24-49-39]]

^<<v24-49-39,39>>^ Acontecerá, porém, nos últimos dias, que restaurarei do cativeiro a Elão, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]