include::./index.adoc[]

[[v24-2-0]]
=== Jeremias, 2
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-2-1]]

^<<v24-2-1,1>>^ Veio a mim a palavra do Senhor, dizendo:

[[v24-2-2]]

^<<v24-2-2,2>>^ Vai, e clama aos ouvidos de Jerusalém, dizendo: Assim diz o Senhor: Lembro-me, a favor de ti, da devoção da tua mocidade, do amor dos teus desposórios, de como me seguiste no deserto, numa terra não semeada.

[[v24-2-3]]

^<<v24-2-3,3>>^ Então Israel era santo para o Senhor, primícias da sua novidade; todos os que o devoravam eram tidos por culpados; o mal vinha sobre eles, diz o Senhor.

[[v24-2-4]]

^<<v24-2-4,4>>^ Ouvi a palavra do Senhor, ó casa de Jacó, e todas as famílias da casa de Israel;

[[v24-2-5]]

^<<v24-2-5,5>>^ assim diz o Senhor: Que injustiça acharam em mim vossos pais, para se afastarem de mim, indo após a vaidade, e tornando-se levianos?

[[v24-2-6]]

^<<v24-2-6,6>>^ Eles não perguntaram: Onde está o Senhor, que nos fez subir da terra do Egito? que nos enviou através do deserto, por uma terra de charnecas e de covas, por uma terra de sequidão e densas trevas, por uma terra em que ninguém transitava, nem morava?

[[v24-2-7]]

^<<v24-2-7,7>>^ E eu vos introduzi numa terra fértil, para comerdes o seu fruto e o seu bem; mas quando nela entrastes, contaminastes a minha terra, e da minha herança fizestes uma abominação.

[[v24-2-8]]

^<<v24-2-8,8>>^ Os sacerdotes não disseram: Onde está o Senhor? E os que tratavam da lei não me conheceram, e os governadores prevaricaram contra mim, e os profetas profetizaram por Baal, e andaram após o que é de nenhum proveito.

[[v24-2-9]]

^<<v24-2-9,9>>^ Portanto ainda contenderei convosco, diz o Senhor; e até com os filhos de vossos filhos contenderei.

[[v24-2-10]]

^<<v24-2-10,10>>^ Pois passai às ilhas de Quitim, e vede; enviai a Quedar, e atentai bem; vede se jamais sucedeu coisa semelhante.

[[v24-2-11]]

^<<v24-2-11,11>>^ Acaso trocou alguma nação os seus deuses, que contudo não são deuses? Mas o meu povo trocou a sua glória por aquilo que é de nenhum proveito.

[[v24-2-12]]

^<<v24-2-12,12>>^ Espantai-vos disto, ó céus, e horrorizai-vos! ficai verdadeiramente desolados, diz o Senhor.

[[v24-2-13]]

^<<v24-2-13,13>>^ Porque o meu povo fez duas maldades: a mim me deixaram, o manancial de águas vivas, e cavaram para si cisternas, cisternas rotas, que não retêm as águas.

[[v24-2-14]]

^<<v24-2-14,14>>^ Acaso é Israel um servo? E ele um escravo nascido em casa? Por que, pois, veio a ser presa?

[[v24-2-15]]

^<<v24-2-15,15>>^ Os leões novos rugiram sobre ele, e levantaram a sua voz; e fizeram da terra dele uma desolação; as suas cidades se queimaram, e ninguém habita nelas.

[[v24-2-16]]

^<<v24-2-16,16>>^ Até os filhos de Mênfis e de Tapanes te quebraram o alto da cabeça.

[[v24-2-17]]

^<<v24-2-17,17>>^ Porventura não trouxeste isso sobre ti mesmo, deixando o Senhor teu Deus no tempo em que ele te guiava pelo caminho?

[[v24-2-18]]

^<<v24-2-18,18>>^ Agora, pois, que te importa a ti o caminho do Egito, para beberes as águas do Nilo? e que te importa a ti o caminho da Assíria, para beberes as águas do Eufrates?

[[v24-2-19]]

^<<v24-2-19,19>>^ A tua malícia te castigará, e as tuas apostasias te repreenderão; sabe, pois, e vê, que má e amarga coisa é o teres deixado o Senhor teu Deus, e o não haver em ti o temor de mim, diz o Senhor Deus dos exércitos.

[[v24-2-20]]

^<<v24-2-20,20>>^ Já há muito quebraste o teu jugo, e rompeste as tuas ataduras, e disseste: Não servirei: Pois em todo outeiro alto e debaixo de toda árvore frondosa te deitaste, fazendo-te prostituta.

[[v24-2-21]]

^<<v24-2-21,21>>^ Todavia eu mesmo te plantei como vide excelente, uma semente inteiramente fiel; como, pois, te tornaste para mim uma planta degenerada, de vida estranha?

[[v24-2-22]]

^<<v24-2-22,22>>^ Pelo que, ainda que te laves com salitre, e uses muito sabão, a mancha da tua iniqüidade está diante de mim, diz o Senhor Deus.

[[v24-2-23]]

^<<v24-2-23,23>>^ Como dizes logo: Não estou contaminada nem andei após Baal? Vê o teu caminho no vale, conhece o que fizeste; dromedária ligeira és, que anda torcendo os seus caminhos;

[[v24-2-24]]

^<<v24-2-24,24>>^ asna selvagem acostumada ao deserto e que no ardor do cio sorve o vento; quem lhe pode impedir o desejo? Dos que a buscarem, nenhum precisa cansar-se; pois no mês dela, achá-la-ão.

[[v24-2-25]]

^<<v24-2-25,25>>^ Evita que o teu pé ande descalço, e que a tua garganta tenha sede. Mas tu dizes: Não há esperança; porque tenho amado os estranhos, e após eles andarei.

[[v24-2-26]]

^<<v24-2-26,26>>^ Como fica confundido o ladrão quando o apanham, assim se confundem os da casa de Israel; eles, os seus reis, os seus príncipes, e os seus sacerdotes, e os seus profetas,

[[v24-2-27]]

^<<v24-2-27,27>>^ que dizem ao pau: Tu és meu pai; e à pedra: Tu me geraste. Porque me viraram as costas, e não o rosto; mas no tempo do seu aperto dir-me-ão: Levanta-te, e salvamos.

[[v24-2-28]]

^<<v24-2-28,28>>^ Mas onde estão os teus deuses que fizeste para ti? Que se levantem eles, se te podem livrar no tempo da tua tribulação; porque os teus deuses, ó Judá, são tão numerosos como as tuas cidades.

[[v24-2-29]]

^<<v24-2-29,29>>^ Por que disputais comigo? Todos vós transgredistes contra mim diz o Senhor.

[[v24-2-30]]

^<<v24-2-30,30>>^ Em vão castiguei os vossos filhos; eles não aceitaram a correção; a vossa espada devorou os vossos profetas como um leão destruidor.

[[v24-2-31]]

^<<v24-2-31,31>>^ Ó geração, considerai vós a palavra do Senhor: Porventura tenho eu sido para Israel um deserto? ou uma terra de espessa escuridão? Por que pois diz o meu povo: Andamos à vontade; não tornaremos mais a ti?

[[v24-2-32]]

^<<v24-2-32,32>>^ Porventura esquece-se a virgem dos seus enfeites, ou a esposa dos seus cendais? todavia o meu povo se esqueceu de mim por inumeráveis dias.

[[v24-2-33]]

^<<v24-2-33,33>>^ Como ornamentas o teu caminho, para buscares o amor! de sorte que até às malignas ensinaste os teus caminhos.

[[v24-2-34]]

^<<v24-2-34,34>>^ Até nas orlas dos teus vestidos se achou o sangue dos pobres inocentes; e não foi no lugar do arrombamento que os achaste; mas apesar de todas estas coisas,

[[v24-2-35]]

^<<v24-2-35,35>>^ ainda dizes: Eu sou inocente; certamente a sua ira se desviou de mim. Eis que entrarei em juízo contigo, porquanto dizes: Não pequei.

[[v24-2-36]]

^<<v24-2-36,36>>^ Por que te desvias tanto, mudando o teu caminho? Também pelo Egito serás envergonhada, como já foste envergonhada pela Assíria.

[[v24-2-37]]

^<<v24-2-37,37>>^ Também daquele sairás com as mães sobre a tua cabeça; porque o Senhor rejeitou as tuas confianças, e não prosperarás com elas.

'''

xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[Próximo Capítulo &#62;]