include::./index.adoc[]

[[v24-18-0]]
=== Jeremias, 18
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-18-1]]

^<<v24-18-1,1>>^ A palavra que veio do Senhor a Jeremias, dizendo:

[[v24-18-2]]

^<<v24-18-2,2>>^ Levanta-te, e desce à casa do oleiro, e lá te farei ouvir as minhas palavras.

[[v24-18-3]]

^<<v24-18-3,3>>^ Desci, pois, à casa do oleiro, e eis que ele estava ocupado com a sua obra sobre as rodas.

[[v24-18-4]]

^<<v24-18-4,4>>^ Como o vaso, que ele fazia de barro, se estragou na mão do oleiro, tornou a fazer dele outro vaso, conforme pareceu bem aos seus olhos fazer.

[[v24-18-5]]

^<<v24-18-5,5>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v24-18-6]]

^<<v24-18-6,6>>^ Não poderei eu fazer de vós como fez este oleiro, ó casa de Israel? diz o Senhor. Eis que, como o barro na mão do oleiro, assim sois vós na minha mão, ó casa de Israel.

[[v24-18-7]]

^<<v24-18-7,7>>^ Se em qualquer tempo eu falar acerca duma nação, e acerca dum reino, para arrancar, para derribar e para destruir,

[[v24-18-8]]

^<<v24-18-8,8>>^ e se aquela nação, contra a qual falar, se converter da sua maldade, também eu me arrependerei do mal que intentava fazer-lhe.

[[v24-18-9]]

^<<v24-18-9,9>>^ E se em qualquer tempo eu falar acerca duma nação e acerca dum reino, para edificar e para plantar,

[[v24-18-10]]

^<<v24-18-10,10>>^ se ela fizer o mal diante dos meus olhos, não dando ouvidos à minha voz, então me arrependerei do bem que lhe intentava fazer.

[[v24-18-11]]

^<<v24-18-11,11>>^ Ora pois, fala agora aos homens de Judá, e aos moradores de Jerusalém, dizendo: Assim diz o senhor: Eis que estou forjando mal contra vós, e projeto um plano contra vós; convertei-vos pois agora cada um do seu mau caminho, e emendai os vossos caminhos e as vossas ações.

[[v24-18-12]]

^<<v24-18-12,12>>^ Mas eles dizem: Não há esperança; porque após os nossos projetos andaremos, e cada um fará segundo o propósito obstinado do seu mau coração.

[[v24-18-13]]

^<<v24-18-13,13>>^ Portanto assim diz o Senhor: Perguntai agora entre as nações quem ouviu tais coisas? coisa mui horrenda fez a virgem de Israel!

[[v24-18-14]]

^<<v24-18-14,14>>^ Acaso desaparece a neve do Líbano dos penhascos do Siriom? Serão esgotadas as águas frias que vêm dos montes?

[[v24-18-15]]

^<<v24-18-15,15>>^ Contudo o meu povo se tem esquecido de mim, queimando incenso a deuses falsos; fizeram-se tropeçar nos seus caminhos, e nas veredas antigas, para que andassem por atalhos não aplainados;

[[v24-18-16]]

^<<v24-18-16,16>>^ para fazerem da sua terra objeto de espanto e de perpétuos assobios; todo aquele que passa por ela se espanta, e meneia a cabeça.

[[v24-18-17]]

^<<v24-18-17,17>>^ Com vento oriental os espalharei diante do inimigo; mostrar-lhes-ei as costas e não o rosto, no dia da sua calamidade.

[[v24-18-18]]

^<<v24-18-18,18>>^ Então disseram: Vinde, e maquinemos projetos contra Jeremias; pois não perecerá a lei do sacerdote, nem o conselho do sábio, nem a palavra do profeta. Vinde, e ataquemo-lo com a língua, e não atendamos a nenhuma das suas palavras.

[[v24-18-19]]

^<<v24-18-19,19>>^ Atende-me, ó Senhor, e ouve a voz dos que contendem comigo.

[[v24-18-20]]

^<<v24-18-20,20>>^ Porventura pagar-se-á mal por bem? Contudo cavaram uma cova para a minha vida. Lembra-te de que eu compareci na tua presença, para falar a favor deles, para desviar deles a tua indignação.

[[v24-18-21]]

^<<v24-18-21,21>>^ Portanto entrega seus filhos à fome, e entrega-os ao poder da espada, e sejam suas mulheres roubadas dos filhos, e fiquem viúvas; e sejam seus maridos feridos de morte, e os seus jovens mortos à espada na peleja.

[[v24-18-22]]

^<<v24-18-22,22>>^ Seja ouvido o clamor que vem de suas casas, quando de repente trouxeres tropas sobre eles; porque cavaram uma cova para prender-me e armaram laços aos meus pés.

[[v24-18-23]]

^<<v24-18-23,23>>^ Mas tu, ó Senhor, sabes todo o seu conselho contra mim para matar-me. Não perdoes a sua iniquidade, nem apagues o seu pecado de diante da tua face; mas sejam transtornados diante de ti; trata-os assim no tempo da tua ira.

'''

xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[&#60; Capítulo Anterior] | <<v24-18-0,Topo>> | xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[Próximo Capítulo &#62;]