include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-29-1]]

^<<v24-29-1,1>>^ Ora, são estas as palavras da carta que Jeremias, o profeta, enviou de Jerusalém, aos que restavam dos anciãos do cativeiro, como também aos sacerdotes, e aos profetas, e a todo o povo, que Nabucodonosor levara cativos de Jerusalém para Babilônia,

[[v24-29-2]]

^<<v24-29-2,2>>^ depois de terem saído de Jerusalém o rei Jeconias, e a rainha-mãe, e os eunucos, e os príncipes de Judá e Jerusalém e os artífices e os ferreiros.

[[v24-29-3]]

^<<v24-29-3,3>>^ Veio por mão de Elasa, filho de Safã, e de Gemarias, filho de Hilquias, os quais Zedequias, rei de Judá, enviou a Babilônia, a Nabucodonosor, rei de Babilônia; eis as palavras da carta:

[[v24-29-4]]

^<<v24-29-4,4>>^ Assim diz o Senhor dos exércitos, o Deus de Israel, a todos os do cativeiro, que eu fiz levar cativos de Jerusalém para Babilônia:

[[v24-29-5]]

^<<v24-29-5,5>>^ Edificai casas e habitai-as; plantai jardins, e comei o seu fruto.

[[v24-29-6]]

^<<v24-29-6,6>>^ Tomai mulheres e gerai filhos e filhas; também tomai mulheres para vossos filhos, e dai vossas filhas a maridos, para que tenham filhos e filhas; assim multiplicai-vos ali, e não vos diminuais.

[[v24-29-7]]

^<<v24-29-7,7>>^ E procurai a paz da cidade, para a qual fiz que fôsseis levados cativos, e orai por ela ao Senhor: porque na sua paz vós tereis paz.

[[v24-29-8]]

^<<v24-29-8,8>>^ Pois assim diz o Senhor dos exércitos, o Deus de Israel: Não vos enganem os vossos profetas que estão no meio de vós, nem os vossos adivinhadores; nem deis ouvidos aos vossos sonhos, que vós sonhais;

[[v24-29-9]]

^<<v24-29-9,9>>^ porque eles vos profetizam falsamente em meu nome; não os enviei, diz o Senhor.

[[v24-29-10]]

^<<v24-29-10,10>>^ Porque assim diz o Senhor: Certamente que passados setenta anos em Babilônia, eu vos visitarei, e cumprirei sobre vós a minha boa palavra, tornando a trazer-vos a este lugar.

[[v24-29-11]]

^<<v24-29-11,11>>^ Pois eu bem sei os planos que estou projetando para vós, diz o Senhor; planos de paz, e não de mal, para vos dar um futuro e uma esperança.

[[v24-29-12]]

^<<v24-29-12,12>>^ Então me invocareis, e ireis e orareis a mim, e eu vos ouvirei.

[[v24-29-13]]

^<<v24-29-13,13>>^ Buscar-me-eis, e me achareis, quando me buscardes de todo o vosso coração.

[[v24-29-14]]

^<<v24-29-14,14>>^ E serei achado de vós, diz o Senhor, e farei voltar os vossos cativos, e congregarvos-ei de todas as nações, e de todos os lugares para onde vos lancei, diz o Senhor; e tornarei a trazer-vos ao lugar de onde vos transportei.

[[v24-29-15]]

^<<v24-29-15,15>>^ Porque dizeis: O Senhor nos levantou profetas em Babilônia;

[[v24-29-16]]

^<<v24-29-16,16>>^ portanto assim diz o Senhor a respeito do rei que se assenta no trono de Davi, e de todo o povo que habita nesta cidade, vossos irmãos, que não saíram convosco para o cativeiro;

[[v24-29-17]]

^<<v24-29-17,17>>^ assim diz o Senhor dos exércitos: Eis que enviarei entre eles a espada, a fome e a peste e fá-los-ei como a figos péssimos, que não se podem comer, de ruins que são.

[[v24-29-18]]

^<<v24-29-18,18>>^ E persegui-los-ei com a espada, com a fome e com a peste; farei que sejam um espetáculo de terror para todos os reinos da terra, e para serem um motivo de execração, de espanto, de assobio, e de opróbrio entre todas as nações para onde os tiver lançado,

[[v24-29-19]]

^<<v24-29-19,19>>^ porque não deram ouvidos às minhas palavras, diz o Senhor, as quais lhes enviei com insistência pelos meus servos, os profetas; mas vós não escutastes, diz o Senhor.

[[v24-29-20]]

^<<v24-29-20,20>>^ Ouvi, pois, a palavra do Senhor, vós todos os do cativeiro que enviei de Jerusalém para Babilônia.

[[v24-29-21]]

^<<v24-29-21,21>>^ Assim diz o Senhor dos exércitos, o Deus de Israel, acerca de Acabe, filho de Colaías, e de Zedequias, filho de Maaséias, que vos profetizam falsamente em meu nome: Eis que os entregarei na mão de Nabucodonosor, rei de Babilônia, e ele os matará diante dos vossos olhos.

[[v24-29-22]]

^<<v24-29-22,22>>^ E por causa deles será formulada uma maldição por todos os exilados de Judá que estão em Babilônia, dizendo: O Senhor te faça como a Zedequias, e como a Acabe, os quais o rei de Babilônia assou no fogo;

[[v24-29-23]]

^<<v24-29-23,23>>^ porque fizeram insensatez em Israel, cometendo adultério com as mulheres de seus próximos, e anunciando falsamente em meu nome palavras que não lhes mandei. Eu o sei, e sou testemunha disso, diz o Senhor.

[[v24-29-24]]

^<<v24-29-24,24>>^ E a Semaías, o neelamita, falarás, dizendo:

[[v24-29-25]]

^<<v24-29-25,25>>^ Assim diz o Senhor dos exércitos, o Deus de Israel: Porquanto enviaste em teu próprio nome cartas a todo o povo que está em Jerusalém, como também a Sofonias, filho de Maaséias, o sacerdote, e a todos os sacerdotes, dizendo:

[[v24-29-26]]

^<<v24-29-26,26>>^ O Senhor te pôs por sacerdote em lugar de Jeoiada, o sacerdote, para que fosses encarregado da casa do Senhor, sobre todo homem obsesso que profetiza, para o lançares na prisão e no tronco;

[[v24-29-27]]

^<<v24-29-27,27>>^ agora, pois, por que não repreendeste a Jeremias, o anatotita, que vos profetiza?

[[v24-29-28]]

^<<v24-29-28,28>>^ Pois que até nos mandou dizer em Babilônia: O cativeiro muito há de durar; edificai casas, e habitai-as; e plantai jardins, e comei do seu fruto.

[[v24-29-29]]

^<<v24-29-29,29>>^ E lera Sofonias, o sacerdote, esta carta aos ouvidos de Jeremias, o profeta.

[[v24-29-30]]

^<<v24-29-30,30>>^ Então veio a palavra do Senhor a Jeremias, dizendo:

[[v24-29-31]]

^<<v24-29-31,31>>^ Manda a todos os do cativeiro, dizendo: Assim diz o Senhor acerca de Semaías, o neelamita: Porquanto Semaías vos profetizou, quando eu não o enviei, e vos fez confiar numa mentira,

[[v24-29-32]]

^<<v24-29-32,32>>^ portanto assim diz o Senhor: Eis que castigarei a Semaías, o neelamita, e a sua descendência; ele não terá varão que habite entre este povo, nem verá ele o bem que hei de fazer ao meu povo, diz o Senhor, porque pregou rebelião contra o Senhor.

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]