include::./index.adoc[]

[[v24-17-0]]
=== Jeremias, 17
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-17-1]]

^<<v24-17-1,1>>^ O pecado de Judá está escrito com um ponteiro de ferro; com ponta de diamante está gravado na tábua do seu coração e nas pontas dos seus altares;

[[v24-17-2]]

^<<v24-17-2,2>>^ enquanto seus filhos se lembram dos seus altares, e dos seus aserins, junto às árvores frondosas, sobre os altos outeiros,

[[v24-17-3]]

^<<v24-17-3,3>>^ nas montanhas no campo aberto, a tua riqueza e todos os teus tesouros dá-los-ei como despojo por causa do pecado, em todos os teus termos.

[[v24-17-4]]

^<<v24-17-4,4>>^ Assim tu, por ti mesmo, te privarás da tua herança que te dei; e far-te-ei servir os teus inimigos, na terra que não conheces; porque acendeste um fogo na minha ira, o qual arderá para sempre.

[[v24-17-5]]

^<<v24-17-5,5>>^ Assim diz o Senhor: Maldito o varão que confia no homem, e faz da carne o seu braço, e aparta o seu coração do Senhor!

[[v24-17-6]]

^<<v24-17-6,6>>^ Pois é como o junípero no deserto, e não verá vir bem algum; antes morará nos lugares secos do deserto, em terra salgada e inabitada.

[[v24-17-7]]

^<<v24-17-7,7>>^ Bendito o varão que confia no Senhor, e cuja esperança é o Senhor.

[[v24-17-8]]

^<<v24-17-8,8>>^ Porque é como a árvore plantada junto às águas, que estende as suas raízes para o ribeiro, e não receia quando vem o calor, mas a sua folha fica verde; e no ano de sequidão não se afadiga, nem deixa de dar fruto.

[[v24-17-9]]

^<<v24-17-9,9>>^ Enganoso é o coração, mais do que todas as coisas, e perverso; quem o poderá conhecer?

[[v24-17-10]]

^<<v24-17-10,10>>^ Eu, o Senhor, esquadrinho a mente, eu provo o coração; e isso para dar a cada um segundo os seus caminhos e segundo o fruto das suas ações.

[[v24-17-11]]

^<<v24-17-11,11>>^ Como a perdiz que ajunta pintainhos que não são do seu ninho, assim é aquele que ajunta riquezas, mas não retamente; no meio de seus dias as deixará, e no seu fim se mostrará insensato.

[[v24-17-12]]

^<<v24-17-12,12>>^ Um trono glorioso, posto bem alto desde o princípio, é o lugar do nosso santuário.

[[v24-17-13]]

^<<v24-17-13,13>>^ Ó Senhor, esperança de Israel, todos aqueles que te abandonarem serão envergonhados. Os que se apartam de ti serão escritos sobre a terra; porque abandonam o Senhor, a fonte das águas vivas.

[[v24-17-14]]

^<<v24-17-14,14>>^ Cura-me, ó Senhor, e serei curado; salva-me, e serei salvo; pois tu és o meu louvor.

[[v24-17-15]]

^<<v24-17-15,15>>^ Eis que eles me dizem: Onde está a palavra do Senhor? venha agora.

[[v24-17-16]]

^<<v24-17-16,16>>^ Quanto a mim, não instei contigo para enviares sobre eles o mal, nem tampouco desejei o dia calamitoso; tu o sabes; o que saiu dos meus lábios estava diante de tua face.

[[v24-17-17]]

^<<v24-17-17,17>>^ Não me sejas por espanto; meu refúgio és tu no dia da calamidade.

[[v24-17-18]]

^<<v24-17-18,18>>^ Envergonhem-se os que me perseguem, mas não me envergonhe eu; assombrem-se eles, mas não me assombre eu; traze sobre eles o dia da calamidade, e destrói-os com dobrada destruição.

[[v24-17-19]]

^<<v24-17-19,19>>^ Assim me disse o Senhor: Vai, e põe-te na porta de Benjamim, pela qual entram os reis de Judá, e pela qual saem, como também em todas as portas de Jerusalém.

[[v24-17-20]]

^<<v24-17-20,20>>^ E dize-lhes: Ouvi a palavra do Senhor, vós, reis de Judá e todo o Judá, e todos os moradores de Jerusalém, que entrais por estas portas;

[[v24-17-21]]

^<<v24-17-21,21>>^ assim diz o Senhor: Guardai-vos a vós mesmos, e não tragais cargas no dia de sábado, nem as introduzais pelas portas de Jerusalém;

[[v24-17-22]]

^<<v24-17-22,22>>^ nem tireis cargas de vossas casas no dia de sábado, nem façais trabalho algum; antes santificai o dia de sábado, como eu ordenei a vossos pais.

[[v24-17-23]]

^<<v24-17-23,23>>^ Mas eles não escutaram, nem inclinaram os seus ouvidos; antes endureceram a sua cerviz, para não ouvirem, e para não receberem instrução.

[[v24-17-24]]

^<<v24-17-24,24>>^ Mas se vós diligentemente me ouvirdes, diz o Senhor, não introduzindo cargas pelas portas desta cidade no dia de sábado, e santificardes o dia de sábado, não fazendo nele trabalho algum,

[[v24-17-25]]

^<<v24-17-25,25>>^ então entrarão pelas portas desta cidade reis e príncipes, que se assentem sobre o trono de Davi, andando em carros e montados em cavalos, eles e seus príncipes, os homens de Judá, e os moradores de Jerusalém; e esta cidade será para sempre habitada.

[[v24-17-26]]

^<<v24-17-26,26>>^ E virão das cidades de Judá, e dos arredores de Jerusalém, e da terra de Benjamim, e da planície, e da região montanhosa, e do e sul, trazendo à casa do Senhor holocaustos, e sacrifícios, e ofertas de cereais, e incenso, trazendo também sacrifícios de ação de graças.

[[v24-17-27]]

^<<v24-17-27,27>>^ Mas, se não me ouvirdes, para santificardes o dia de sábado, e para não trazerdes carga alguma, quando entrardes pelas portas de Jerusalém no dia de sábado, então acenderei fogo nas suas portas, o qual consumirá os palácios de Jerusalém, e não se apagará.

'''

xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[Próximo Capítulo &#62;]