include::./index.adoc[]

[[v24-51-0]]
=== Jeremias, 51
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-51-1]]

^<<v24-51-1,1>>^ Assim diz o Senhor: Eis que levantarei um vento destruidor contra Babilônia, e contra os que habitam na Caldéia.

[[v24-51-2]]

^<<v24-51-2,2>>^ E enviarei padejadores contra Babilônia, que a padejarão, e esvaziarão a sua terra, quando vierem contra ela em redor no dia da calamidade.

[[v24-51-3]]

^<<v24-51-3,3>>^ Não arme o flecheiro o seu arco, nem se levante o que estiver armado da sua couraça; não perdoeis aos seus jovens; destruí completamente todo o seu exército.

[[v24-51-4]]

^<<v24-51-4,4>>^ Cairão mortos na terra dos caldeus, e feridos nas ruas dela.

[[v24-51-5]]

^<<v24-51-5,5>>^ Pois Israel e Judá não foram abandonados do seu Deus, o Senhor dos exércitos, ainda que a terra deles esteja cheia de culpas contra o Santo de Israel.

[[v24-51-6]]

^<<v24-51-6,6>>^ Fugi do meio de Babilônia, e livre cada um a sua vida; não sejais exterminados na sua punição; pois este é o tempo da vingança do Senhor; ele lhe dará o pago.

[[v24-51-7]]

^<<v24-51-7,7>>^ Na mão do Senhor a Babilônia era um copo de ouro, o qual embriagava a toda a terra; do seu vinho beberam as nações; por isso as nações estão fora de si.

[[v24-51-8]]

^<<v24-51-8,8>>^ Repentinamente caiu Babilônia, e ficou arruinada; uivai sobre ela; tomai bálsamo para a sua dor, talvez sare.

[[v24-51-9]]

^<<v24-51-9,9>>^ Queríamos sarar Babilônia, ela, porém, não sarou; abandonai-a, e vamo-nos, cada qual para a sua terra; pois o seu julgamento chega até o céu, e se eleva até as mais altas nuvens.

[[v24-51-10]]

^<<v24-51-10,10>>^ O Senhor trouxe à luz a nossa justiça; vinde e anunciemos em Sião a obra do Senhor nosso Deus.

[[v24-51-11]]

^<<v24-51-11,11>>^ Aguçai as flechas, preparei os escudos; o Senhor despertou o espírito dos reis dos medos; porque o seu intento contra Babilônia é para a destruir; pois esta é a vingança do Senhor, a vingança do seu templo.

[[v24-51-12]]

^<<v24-51-12,12>>^ Arvorai um estandarte sobre os muros de Babilônia, reforçai a guarda, colocai sentinelas, preparai as emboscadas; porque o Senhor tanto intentou como efetuou o que tinha dito acerca dos moradores de Babilônia.

[[v24-51-13]]

^<<v24-51-13,13>>^ Ó tu, que habitas sobre muitas águas, rica de tesouros! é chegado o teu fim, a medida da tua ganância.

[[v24-51-14]]

^<<v24-51-14,14>>^ Jurou o Senhor dos exércitos por si mesmo, dizendo: Certamente te encherei de homens, como de locustas; e eles levantarão o grito de vitória sobre ti.

[[v24-51-15]]

^<<v24-51-15,15>>^ É ele quem fez a terra com o seu poder, estabeleceu o mundo com a sua sabedoria, e estendeu os céus com o seu entendimento.

[[v24-51-16]]

^<<v24-51-16,16>>^ À sua voz, há grande tumulto de águas nas céus, e ele faz subir os vapores desde as extremidades da terra; faz os relâmpagos para a chuva, e tira o vento dos seus tesouros.

[[v24-51-17]]

^<<v24-51-17,17>>^ Embruteceu-se todo homem, de modo que não tem conhecimento; todo ourives é envergonhado pelas suas imagens esculpidas; pois as suas imagens de fundição são mentira, e não há espírito em nenhuma delas.

[[v24-51-18]]

^<<v24-51-18,18>>^ Vaidade são, obra de enganos; no tempo em que eu as visitar perecerão.

[[v24-51-19]]

^<<v24-51-19,19>>^ Não é semelhante a estes a porção de Jacó; porque ele é o que forma todas as coisas; e Israel é a tribo da sua herança; o Senhor dos exércitos é o seu nome.

[[v24-51-20]]

^<<v24-51-20,20>>^ Tu me serves de martelo e de armas de guerra; contigo despedaçarei nações, e contigo destruirei os reis;

[[v24-51-21]]

^<<v24-51-21,21>>^ contigo despedaçarei o cavalo e o seu cavaleiro; contigo despedaçarei e carro e o que nele vai;

[[v24-51-22]]

^<<v24-51-22,22>>^ contigo despedaçarei o homem e a mulher; contigo despedaçarei o velho e o moço; contigo despedaçarei o mancebo e a donzela;

[[v24-51-23]]

^<<v24-51-23,23>>^ contigo despedaçarei o pastor e o seu rebanho; contigo despedaçarei o lavrador e a sua junta de bois; e contigo despedaçarei governadores e magistrados.

[[v24-51-24]]

^<<v24-51-24,24>>^ Ante os vossos olhos pagarei a Babilônia, e a todos os moradores da Caldéia, toda a sua maldade que fizeram em Sião, diz o Senhor.

[[v24-51-25]]

^<<v24-51-25,25>>^ Eis-me aqui contra ti, ó monte destruidor, diz o Senhor, que destróis toda a terra; estenderei a minha mão contra ti, e te revolverei dos penhascos abaixo, e farei de ti um monte incendiado.

[[v24-51-26]]

^<<v24-51-26,26>>^ E não tomarão de ti pedra para esquina, nem pedra para fundamentos; mas desolada ficarás perpetuamente, diz o Senhor.

[[v24-51-27]]

^<<v24-51-27,27>>^ Arvorai um estandarte na terra, tocai a trombeta entre as nações, preparai as nações contra ela, convocai contra ela os reinos de Arará, Mini, e Asquenaz; ponde sobre ela um capitão, fazei subir cavalos, como locustas eriçadas.

[[v24-51-28]]

^<<v24-51-28,28>>^ Preparai contra ela as nações, os reis dos medos, os seus governadores e magistrados, e toda a terra do seu domínio.

[[v24-51-29]]

^<<v24-51-29,29>>^ E a terra estremece e está angustiada; porque os desígnios do Senhor estão firmes contra Babilônia, para fazer da terra de Babilônia uma desolação, sem habitantes.

[[v24-51-30]]

^<<v24-51-30,30>>^ Os valentes de Babilônia cessaram de pelejar, ficam nas fortalezas, desfaleceu a sua força, tornaram-se como mulheres; incendiadas são as suas moradas, quebrados os seus ferrolhos.

[[v24-51-31]]

^<<v24-51-31,31>>^ Um correio corre ao encontro de outro correio, e um mensageiro ao encontro de outro mensageiro, para anunciar ao rei de Babilônia que a sua cidade está tomada de todos os lados.

[[v24-51-32]]

^<<v24-51-32,32>>^ E os vaus estão ocupados, os canaviais queimados a fogo, e os homens de guerra assombrados.

[[v24-51-33]]

^<<v24-51-33,33>>^ Pois assim diz o Senhor dos exércitos, o Deus de Israel: A filha de Babilônia é como a eira no tempo da debulha; ainda um pouco, e o tempo da sega lhe virá.

[[v24-51-34]]

^<<v24-51-34,34>>^ Nabucodonosor, rei de Babilônia, devorou-me, esmagou-me, fez de mim um vaso vazio, qual monstro tragou-me, encheu o seu ventre do que eu tinha de delicioso; lançou-me fora.

[[v24-51-35]]

^<<v24-51-35,35>>^ A violência que se me fez a mim e à minha carne venha sobre Babilônia, diga a moradora de Sião. O meu sangue caia sobre os moradores de Caldéia, diga Jerusalém.

[[v24-51-36]]

^<<v24-51-36,36>>^ Pelo que assim diz o Senhor: Eis que defenderei a tua causa, e te vingarei; e secarei o seu mar, e farei que se esgote a sua fonte:

[[v24-51-37]]

^<<v24-51-37,37>>^ E Babilônia se tornará em montões, morada de chacais, objeto de espanto e assobio, sem habitante.

[[v24-51-38]]

^<<v24-51-38,38>>^ Juntos rugirão como leões novos, bramarão como cachorros de leões.

[[v24-51-39]]

^<<v24-51-39,39>>^ Estando eles excitados, preparar-lhes-ei um banquete, e os embriagarei, para que se regozijem, e durmam um perpétuo sono, e não despertem, diz o Senhor.

[[v24-51-40]]

^<<v24-51-40,40>>^ Fá-los-ei descer como cordeiros ao matadouro, como carneiros e bodes.

[[v24-51-41]]

^<<v24-51-41,41>>^ Como foi tomada Sesaque, e apanhada de surpresa a glória de toda a terra! como se tornou Babilônia um espetáculo horrendo entre as nações!

[[v24-51-42]]

^<<v24-51-42,42>>^ O mar subiu sobre Babilônia; coberta está com a multidão das suas ondas.

[[v24-51-43]]

^<<v24-51-43,43>>^ Tornaram-se as suas cidades em ruínas, terra seca e deserta, terra em que ninguém habita, nem passa por ela filho de homem.

[[v24-51-44]]

^<<v24-51-44,44>>^ E castigarei a Bel em Babilônia, e tirarei da sua boca o que ele tragou; e nunca mais concorrerão a ele as nações; o muro de Babilônia está caído.

[[v24-51-45]]

^<<v24-51-45,45>>^ Saí do meio dela, ó povo meu, e salve cada um a sua vida do ardor da ira do Senhor.

[[v24-51-46]]

^<<v24-51-46,46>>^ Não desfaleça o vosso coração, nem temais pelo rumor que se ouvir na terra; pois virá num ano um rumor, e depois noutro ano outro rumor; e haverá violência na terra, dominador contra dominador.

[[v24-51-47]]

^<<v24-51-47,47>>^ Portanto eis que vêm os dias em que executarei juízo sobre as imagens esculpidas de Babilônia; e toda a sua terra ficará envergonhada; e todos os seus traspassados cairão no meio dela.

[[v24-51-48]]

^<<v24-51-48,48>>^ Então o céu e a terra, com tudo quanto neles há, jubilarão sobre Babilônia; pois do norte lhe virão os destruidores, diz o Senhor.

[[v24-51-49]]

^<<v24-51-49,49>>^ Babilônia há de cair pelos mortos de Israel, assim como por Babilônia têm caído os mortos de toda a terra.

[[v24-51-50]]

^<<v24-51-50,50>>^ Vós, que escapastes da espada, ide-vos, não pareis; desde terras longínquas lembrai-vos do Senhor, e suba Jerusalém à vossa mente.

[[v24-51-51]]

^<<v24-51-51,51>>^ Envergonhados estamos, porque ouvimos opróbrio; a confusão nos cobriu o rosto; pois entraram estrangeiros nos santuários da casa do Senhor.

[[v24-51-52]]

^<<v24-51-52,52>>^ Portanto, eis que vêm os dias, diz o Senhor, em que executarei juízo sobre as suas imagens esculpidas; e em toda a sua terra gemerão os feridos.

[[v24-51-53]]

^<<v24-51-53,53>>^ Ainda que Babilônia subisse ao céu, e ainda que fortificasse a altura da sua fortaleza, contudo de mim viriam destruidores sobre ela, diz o Senhor.

[[v24-51-54]]

^<<v24-51-54,54>>^ Eis um clamor de Babilônia! de grande destruição da terra dos caldeus!

[[v24-51-55]]

^<<v24-51-55,55>>^ Pois o Senhor está despojando a Babilônia, e emudecendo a sua poderosa voz. Bramam as ondas do inimigo como muitas águas; ouve-se o arruído da sua voz.

[[v24-51-56]]

^<<v24-51-56,56>>^ Porque o destruidor veio sobre ela, sobre Babilônia, e os seus valentes estão presos; já estão despedaçados os seus arcos; pois o Senhor é Deus das recompensas, ele certamente retribuirá.

[[v24-51-57]]

^<<v24-51-57,57>>^ Embriagarei os seus príncipes e os seus sábios, os seus governadores, os seus magistrados, e os seus valentes; e dormirão um sono perpétuo, e jamais acordarão, diz o Rei, cujo nome é o Senhor dos exércitos.

[[v24-51-58]]

^<<v24-51-58,58>>^ Assim diz o Senhor dos exércitos: O largo muro de Babilônia será de todo derribado, e as suas portas altas serão abrasadas pelo fogo; e trabalharão os povos em vão, e as nações se cansarão só para o fogo.

[[v24-51-59]]

^<<v24-51-59,59>>^ A palavra que Jeremias, o profeta, mandou a Seraías, filho de Nerias, filho de Maséias, quando ia com Zedequias, rei de Judá, a Babilônia, no quarto ano do seu reinado. Ora, Seraías era o camareiro-mor.

[[v24-51-60]]

^<<v24-51-60,60>>^ Escreveu, pois, Jeremias num livro todo o mal que havia de vir sobre Babilônia, a saber, todas estas palavras que estão escritas acerca de Babilônia.

[[v24-51-61]]

^<<v24-51-61,61>>^ E disse Jeremias a Seraías: Quando chegares a Babilônia, vê que leias todas estas palavras;

[[v24-51-62]]

^<<v24-51-62,62>>^ e dirás: Tu, Senhor, falaste a respeito deste lugar, que o havias de desarraigar, até não ficar nele morador algum, nem homem nem animal, mas que se tornaria em perpétua desolação.

[[v24-51-63]]

^<<v24-51-63,63>>^ E acabando tu de ler este livro, atar-lhe-ás uma pedra e o lançarás no meio do Eufrates;

[[v24-51-64]]

^<<v24-51-64,64>>^ e dirás: Assim será submergida Babilônia, e não se levantará, por causa do mal que vou trazer sobre ela; e eles se cansarão.

'''

xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[&#60; Capítulo Anterior] | <<v24-51-0,Topo>> | xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[Próximo Capítulo &#62;]