include::./index.adoc[]

[[v24-26-0]]
=== Jeremias, 26
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-26-1]]

^<<v24-26-1,1>>^ No princípio do reino de Jeoiaquim, filho de Josias, rei de Judá, veio da parte do Senhor esta palavra, dizendo:

[[v24-26-2]]

^<<v24-26-2,2>>^ Assim diz o Senhor: Põe-te no átrio da casa do Senhor e dize a todas as cidades de Judá que vêm adorar na casa do Senhor, todas as palavras que te mando que lhes fales; não omitas uma só palavra.

[[v24-26-3]]

^<<v24-26-3,3>>^ Bem pode ser que ouçam, e se convertam cada um do seu mau caminho, para que eu desista do mal que intento fazer-lhes por causa da maldade das suas ações.

[[v24-26-4]]

^<<v24-26-4,4>>^ Dize-lhes pois: Assim diz o Senhor: Se não me derdes ouvidos para andardes na minha lei, que pus diante de vós,

[[v24-26-5]]

^<<v24-26-5,5>>^ e para ouvirdes as palavras dos meus servos, os profetas, que eu com insistência vos envio, mas não ouvistes;

[[v24-26-6]]

^<<v24-26-6,6>>^ então farei que esta casa seja como Siló, e farei desta cidade uma maldição para todas as nações da terra.

[[v24-26-7]]

^<<v24-26-7,7>>^ E ouviram os sacerdotes, e os profetas, e todo o povo, a Jeremias, anunciando estas palavras na casa do Senhor.

[[v24-26-8]]

^<<v24-26-8,8>>^ Tendo Jeremias acabado de dizer tudo quanto o Senhor lhe havia ordenado que dissesse a todo o povo, pegaram nele os sacerdotes, e os profetas, e todo o povo, dizendo: Certamente morrerás.

[[v24-26-9]]

^<<v24-26-9,9>>^ Por que profetizaste em nome do Senhor, dizendo: Será como Siló esta casa, e esta cidade ficará assolada e desabitada? E ajuntou-se todo o povo contra Jeremias, na casa do Senhor.

[[v24-26-10]]

^<<v24-26-10,10>>^ Quando os príncipes de Judá ouviram estas coisas, subiram da casa do rei à casa do Senhor, e se assentaram à entrada da porta nova do Senhor.

[[v24-26-11]]

^<<v24-26-11,11>>^ Então falaram os sacerdotes e os profetas aos príncipes e a todo povo, dizendo: Este homem é réu de morte, porque profetizou contra esta cidade, como ouvistes com os vossos próprios ouvidos.

[[v24-26-12]]

^<<v24-26-12,12>>^ E falou Jeremias a todos os príncipes e a todo o povo, dizendo: O Senhor enviou-me a profetizar contra esta casa, e contra esta cidade, todas as palavras que ouvistes.

[[v24-26-13]]

^<<v24-26-13,13>>^ Agora, pois, melhorai os vossos caminhos e as vossas ações, e ouvi a voz do Senhor vosso Deus, e o Senhor desistirá do mal que falou contra vós.

[[v24-26-14]]

^<<v24-26-14,14>>^ Quanto a mim, eis que estou nas vossas mãos; fazei de mim conforme o que for bom e reto aos vossos olhos.

[[v24-26-15]]

^<<v24-26-15,15>>^ Sabei, porém, com certeza que, se me matardes a mim, trareis sangue inocente sobre vós, e sobre esta cidade, e sobre os seus habitantes; porque, na verdade, o Senhor me enviou a vós, para dizer aos vossos ouvidos todas estas palavras.

[[v24-26-16]]

^<<v24-26-16,16>>^ Então disseram os príncipes e todo o povo aos sacerdotes e aos profetas: Este homem não é réu de morte, porque em nome do Senhor, nosso Deus, nos falou.

[[v24-26-17]]

^<<v24-26-17,17>>^ Também se levantaram alguns dos anciãos da terra, e falaram a toda a assembléia do povo, dizendo:

[[v24-26-18]]

^<<v24-26-18,18>>^ Miquéias, o morastita, profetizou nos dias de Ezequias, rei de Judá, e falou a todo o povo de Judá, dizendo: Assim diz o Senhor dos exércitos: Sião será lavrada como um campo, e Jerusalém se tornará em montões de ruínas, e o monte desta casa como os altos de um bosque.

[[v24-26-19]]

^<<v24-26-19,19>>^ Mataram-no, porventura, Ezequias, rei de Judá, e todo o Judá? Antes não temeu este ao Senhor, e não implorou o favor do Senhor? e não se arrependeu o Senhor do mal que falara contra eles? Mas nós estamos fazendo um grande mal contra as nossas almas.

[[v24-26-20]]

^<<v24-26-20,20>>^ Também houve outro homem que profetizava em nome do Senhor: Urias, filho de Semaías, de Quiriate-Jearim, o qual profetizou contra esta cidade, e contra esta terra, conforme todas as palavras de Jeremias;

[[v24-26-21]]

^<<v24-26-21,21>>^ e quando o rei Jeoiaquim, e todos os seus valentes, e todos os príncipes, ouviram as palavras dele, procurou o rei matá-lo; mas quando Urias o ouviu, temeu, e fugiu, e foi para o Egito;

[[v24-26-22]]

^<<v24-26-22,22>>^ mas o rei Jeoiaquim enviou ao Egito certos homens; Elnatã, filho de Acbor, e outros com ele,

[[v24-26-23]]

^<<v24-26-23,23>>^ os quais tiraram a Urias do Egito, e o trouxeram ao rei Jeoiaquim, que o matou à espada, e lançou o seu cadáver nas sepulturas da plebe.

[[v24-26-24]]

^<<v24-26-24,24>>^ Porém Aicão, filho de Safã, deu apoio a Jeremias, de sorte que não foi entregue na mão do povo, para ser morto.

'''

xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[&#60; Capítulo Anterior] | <<v24-26-0,Topo>> | xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[Próximo Capítulo &#62;]