include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-48-1]]

^<<v24-48-1,1>>^ Acerca de Moabe. Assim diz o Senhor dos exércitos, Deus de Israel: Ai de Nebo, porque foi destruída; envergonhada está Quiriataim, já é tomada; Misgabe está envergonhada e espantada.

[[v24-48-2]]

^<<v24-48-2,2>>^ O louvor de Moabe já não existe mais; em Hesbom projetaram mal contra ela, dizendo: Vinde, e exterminemo-la, para que não mais seja nação; também tu, ó Madmém, serás destruída; a espada te perseguirá.

[[v24-48-3]]

^<<v24-48-3,3>>^ Voz de grito de Horonaim, ruína e grande destruição!

[[v24-48-4]]

^<<v24-48-4,4>>^ Está destruído Moabe; seus filhinhos fizeram ouvir um clamor.

[[v24-48-5]]

^<<v24-48-5,5>>^ Pois pela subida de Luíte eles vão subindo com choro contínuo; porque na descida de Horonaim, ouviram a angústia do grito da destruição.

[[v24-48-6]]

^<<v24-48-6,6>>^ Fugi, salvai a vossa vida! Sede como o asno selvagem no deserto.

[[v24-48-7]]

^<<v24-48-7,7>>^ Pois, porquanto confiaste nas tuas obras e nos teus tesouros, também tu serás tomada; e Quemós sairá para o cativeiro, os seus sacerdotes e os seus príncipes juntamente.

[[v24-48-8]]

^<<v24-48-8,8>>^ Porque virá o destruidor sobre cada uma das cidades e nenhuma escapará, e perecerá o vale, e destruir-se-á a planície, como disse o Senhor.

[[v24-48-9]]

^<<v24-48-9,9>>^ Dai asas a Moabe, porque voando sairá; e as suas cidades se tornarão em desolação, sem habitante.

[[v24-48-10]]

^<<v24-48-10,10>>^ Maldito aquele que fizer a obra do Senhor negligentemente, e maldito aquele que vedar do sangue a sua espada!

[[v24-48-11]]

^<<v24-48-11,11>>^ Moabe tem estado sossegado desde a sua mocidade, e tem repousado como vinho sobre as fezes; não foi deitado de vasilha em vasilha, nem foi para o cativeiro; por isso permanece nele o seu sabor, e o seu cheiro não se altera.

[[v24-48-12]]

^<<v24-48-12,12>>^ Portanto, eis que os dias vêm, diz o Senhor, em que lhe enviarei derramadores que o derramarão; e despejarão as suas vasilhas, e despedaçarão os seus jarros.

[[v24-48-13]]

^<<v24-48-13,13>>^ E Moabe terá vergonha de Quemós, como se envergonhou a casa de Israel de Betel, sua confiança.

[[v24-48-14]]

^<<v24-48-14,14>>^ Como direis: Somos valentes e homens fortes para a guerra?

[[v24-48-15]]

^<<v24-48-15,15>>^ Já subiu o destruidor de Moabe e das suas cidades, e os seus mancebos escolhidos desceram à matança, diz o Rei, cujo nome é o Senhor dos exércitos.

[[v24-48-16]]

^<<v24-48-16,16>>^ A calamidade de Moabe está perto e muito se apressa o seu mal.

[[v24-48-17]]

^<<v24-48-17,17>>^ Condoei-vos dele todos os que estais em seu redor, e todos os que sabeis o seu nome; dizei: Como se quebrou a vara forte, o cajado formoso!

[[v24-48-18]]

^<<v24-48-18,18>>^ Desce da tua glória, e senta-te no pó, ó moradora, filha de Dibom; porque o destruidor de Moabe subiu contra ti, e desfez as tuas fortalezas.

[[v24-48-19]]

^<<v24-48-19,19>>^ Põe-te junto ao caminho, e espia, ó moradora do Aroer; pergunta ao que foge, e à que escapa: Que sucedeu?

[[v24-48-20]]

^<<v24-48-20,20>>^ Moabe está envergonhado, porque foi quebrantado; uivai e gritai; anunciai em Arnom que Moabe está destruído.

[[v24-48-21]]

^<<v24-48-21,21>>^ Também o julgamento é vindo sobre a terra da planície; sobre Holom, Jaza, e Mefaate;

[[v24-48-22]]

^<<v24-48-22,22>>^ sobre Dibom, Nebo, e Bete-Diblataim;

[[v24-48-23]]

^<<v24-48-23,23>>^ sobre Quiriataim, Bete-Gamul, e BeteMeom;

[[v24-48-24]]

^<<v24-48-24,24>>^ sobre Queriote, e Bozra, e todas as cidades da terra de Moabe, as de longe e as de perto.

[[v24-48-25]]

^<<v24-48-25,25>>^ Está cortado o poder de Moabe, e quebrantado o seu braço, diz o senhor.

[[v24-48-26]]

^<<v24-48-26,26>>^ Embriagai-o, porque contra o Senhor se engrandeceu; e Moabe se revolverá no seu vômito, e ele também se tornará objeto de escárnio.

[[v24-48-27]]

^<<v24-48-27,27>>^ Pois não se tornou também Israel objeto de escárnio para ti? Porventura foi achado entre ladrões para que, sempre que falas dele, meneies a cabeça?

[[v24-48-28]]

^<<v24-48-28,28>>^ Deixai as cidades, e habitai no rochedo, ó moradores de Moabe; e sede como a pomba que se aninha nos lados da boca da caverna.

[[v24-48-29]]

^<<v24-48-29,29>>^ Temos ouvido da soberba de Moabe, que é soberbíssimo; da sua sobrançaria, do seu orgulho, da sua arrogância, e da altivez do seu coração.

[[v24-48-30]]

^<<v24-48-30,30>>^ Eu conheço, diz o Senhor, a sua insolência, mas isso nada é; as suas jactâncias nada têm efetuado.

[[v24-48-31]]

^<<v24-48-31,31>>^ Por isso uivarei por Moabe; sim, gritarei por todo o Moabe; pelos homens de Quir-Heres lamentarei.

[[v24-48-32]]

^<<v24-48-32,32>>^ Com choro maior do que o de Jazer chorar-te-ei, ó vide de Sibma; os teus ramos passaram o mar, chegaram até o mar de Jazer; mas o destruidor caiu sobre os teus frutos de verão, e sobre a tua vindima.

[[v24-48-33]]

^<<v24-48-33,33>>^ Tirou-se, pois, a alegria e o regozijo do campo fértil e da terra de Moabe; e fiz que o vinho cessasse dos lagares; já não pisam uvas com júbilo; o brado não é o de júbilo

[[v24-48-34]]

^<<v24-48-34,34>>^ O grito de Hesbom e Eleale se ouve até Jaza; fazem ouvir a sua voz desde Zoar até Horonaim, e até Eglate-Selíssia; pois também as águas do Ninrim virão a ser uma desolação.

[[v24-48-35]]

^<<v24-48-35,35>>^ Demais, farei desaparecer de Moabe, diz o Senhor, aquele que sacrifica nos altos, e queima incenso a seus deuses.

[[v24-48-36]]

^<<v24-48-36,36>>^ Por isso geme como flauta o meu coração por Moabe, e como flauta geme o meu coração pelos homens de Quir-Heres; porquanto a abundância que ajuntou se perdeu.

[[v24-48-37]]

^<<v24-48-37,37>>^ Pois toda cabeça é tosquiada, e toda barba rapada; sobre todas as mãos há sarjaduras, e sobre os lombos sacos.

[[v24-48-38]]

^<<v24-48-38,38>>^ Sobre todos os eirados de Moabe e nas suas ruas há um pranto geral; porque quebrei a Moabe, como a um vaso que não agrada, diz o Senhor.

[[v24-48-39]]

^<<v24-48-39,39>>^ Como está quebrantrado! como uivam! como virou Moabe as costas envergonhado! assim se tornou Moabe objeto de escárnio e de espanto para todos os que estão em redor dele.

[[v24-48-40]]

^<<v24-48-40,40>>^ Pois assim diz o Senhor: Eis que alguém voará como a águia, e estenderá as suas asas contra Moabe.

[[v24-48-41]]

^<<v24-48-41,41>>^ Tomadas serão as cidades, e ocupadas as fortalezas; e naquele dia será o coração dos valentes de Moabe como o coração da mulher em suas dores de parto.

[[v24-48-42]]

^<<v24-48-42,42>>^ E Moabe será destruído, para que não seja povo, porque se engrandeceu contra o Senhor.

[[v24-48-43]]

^<<v24-48-43,43>>^ Temor, e cova, e laço estão sobre ti, ó morador de Moabe, diz o Senhor.

[[v24-48-44]]

^<<v24-48-44,44>>^ O que fugir do temor cairá na cova, e o que sair da cova ficará preso no laço; pois trarei sobre ele, sobre Moabe, o ano do seu castigo, diz o Senhor.

[[v24-48-45]]

^<<v24-48-45,45>>^ Os que fugiram ficam parados sem forças à sombra de Hesbom; mas fogo saiu de Hesbom, e a labareda do meio de Siom, e devorou a fronte de Moabe e o alto da cabeça dos turbulentos.

[[v24-48-46]]

^<<v24-48-46,46>>^ Ai de ti, Moabe! pereceu o povo de Quemós; pois teus filhos foram levados cativos, e tuas filhas para o cativeiro.

[[v24-48-47]]

^<<v24-48-47,47>>^ Contudo nos últimos dias restaurarei do cativeiro a Moabe, diz o Senhor. Até aqui o juizo de Moabe.

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]