include::./index.adoc[]

[[v24-38-0]]
=== Jeremias, 38
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-38-1]]

^<<v24-38-1,1>>^ Ouviram, pois, Sefatias, filho de Matã, e Gedalias, filho de Pasur, e Jeucal, filho de Selemias, e Pasur, filho de Malquias, as palavras que anunciava Jeremias a todo o povo, dizendo:

[[v24-38-2]]

^<<v24-38-2,2>>^ Assim diz o Senhor: O que ficar nesta cidade morrerá à espada, de fome e de peste; mas o que sair para os caldeus viverá; pois a sua vida lhe será por despojo, e vivera.

[[v24-38-3]]

^<<v24-38-3,3>>^ Assim diz o Senhor: Esta cidade infalivelmente será entregue na mão do exército do rei de Babilônia, e ele a tomará.

[[v24-38-4]]

^<<v24-38-4,4>>^ E disseram os príncipes ao rei: Morra este homem, visto que ele assim enfraquece as mãos dos homens de guerra que restam nesta cidade, e as mãos de todo o povo, dizendo-lhes tais palavras; porque este homem não busca a paz para este povo, porem o seu mal.

[[v24-38-5]]

^<<v24-38-5,5>>^ E disse o rei Zedequias: Eis que ele está na vossa mão; porque não é o rei que possa coisa alguma contra vós.

[[v24-38-6]]

^<<v24-38-6,6>>^ Então tomaram a Jeremias, e o lançaram na cisterna de Malquias, filho do rei, que estava no átrio da guarda; e desceram Jeremias com cordas; mas na cisterna não havia água, senão lama, e atolou-se Jeremias na lama.

[[v24-38-7]]

^<<v24-38-7,7>>^ Quando Ebede-Meleque, o etíope, um eunuco que então estava na casa do rei, ouviu que tinham metido Jeremias na cisterna, o rei estava assentado à porta de Benjamim.

[[v24-38-8]]

^<<v24-38-8,8>>^ Saiu, pois, Ebede-Meleque da casa do rei, e falou ao rei, dizendo:

[[v24-38-9]]

^<<v24-38-9,9>>^ o rei, senhor meu, estes homens fizeram mal em tudo quanto fizeram a Jeremias, o profeta, lançando-o na cisterna; de certo morrerá no lugar onde se acha, por causa da fome, pois não há mais pão na cidade.

[[v24-38-10]]

^<<v24-38-10,10>>^ Deu ordem, então, o rei a Ebede-Meleque, o etíope, dizendo: Toma contigo daqui três homens, e tira Jeremias, o profeta, da cisterna, antes que morra.

[[v24-38-11]]

^<<v24-38-11,11>>^ Assim Ebede-Meleque tomou consigo os homens, e entrou na casa do rei, debaixo da tesouraria, e tomou dali uns trapos velhos e rotos, e roupas velhas, e desceu-os a Jeremias na cisterna por meio de cordas.

[[v24-38-12]]

^<<v24-38-12,12>>^ E disse Ebede-Meleque, o etíope, a Jeremias: Põe agora estes trapos velhos e rotos, debaixo dos teus sovacos, entre os braços e as cordas. E Jeremias assim o fez.

[[v24-38-13]]

^<<v24-38-13,13>>^ E tiraram Jeremias com as cordas, e o alçaram da cisterna; e ficou Jeremias no átrio da guarda.

[[v24-38-14]]

^<<v24-38-14,14>>^ Então mandou o rei Zedequias e fez vir à sua presença Jeremias, o profeta, à terceira entrada do templo do Senhor; e disse o rei a Jeremias: Vou perguntar-te uma coisa; não me encubras nada.

[[v24-38-15]]

^<<v24-38-15,15>>^ E disse Jeremias a Zedequias: Se eu te declarar, acaso não me matarás? E se eu te aconselhar, não me ouvirás.

[[v24-38-16]]

^<<v24-38-16,16>>^ Então jurou o rei Zedequias a Jeremias, em segredo, dizendo: Vive o Senhor, que nos fez esta alma, que não te matarei nem te entregarei na mão destes homens que procuram a tua morte.

[[v24-38-17]]

^<<v24-38-17,17>>^ Então Jeremias disse a Zedequias: Assim diz o Senhor, Deus dos exércitos, Deus de Israel: Se te renderes aos príncipes do rei de Babilônia, será poupada a tua vida, e esta cidade não se queimará a fogo, e viverás tu e a tua casa.

[[v24-38-18]]

^<<v24-38-18,18>>^ Mas, se não saíres aos príncipes do rei de Babilônia, então será entregue esta cidade na mão dos caldeus, e eles a queimarão a fogo, e tu não escaparás da sua mão.

[[v24-38-19]]

^<<v24-38-19,19>>^ E disse o rei Zedequias a Jeremias: Receio-me dos judeus que se passaram para os caldeus, que seja entregue na mão deles, e escarneçam de mim.

[[v24-38-20]]

^<<v24-38-20,20>>^ Jeremias, porém, disse: Não te entregarão. Ouve, peço-te, a voz do Senhor, conforme a qual eu te falo; e bem te irá, e poupar-se-á a tua vida.

[[v24-38-21]]

^<<v24-38-21,21>>^ Mas, se tu recusares sair, esta é a palavra que me mostrou o Senhor:

[[v24-38-22]]

^<<v24-38-22,22>>^ Eis que todas as mulheres que ficaram na casa do rei de Judá serão levadas aos príncipes do rei de Babilônia, e elas mesmas dirão: Os teus pacificadores te incitaram e prevaleceram contra ti; e agora que se atolaram os teus pés na lama, voltaram atrás.

[[v24-38-23]]

^<<v24-38-23,23>>^ Todas as tuas mulheres e os teus filhos serão levados para fora aos caldeus; e tu não escaparás da sua mão, mas pela mão do rei de Babilônia serás preso, e esta cidade será queimada a fogo.

[[v24-38-24]]

^<<v24-38-24,24>>^ Então disse Zedequias a Jeremias: Ninguém saiba estas palavras, e não morrerás.

[[v24-38-25]]

^<<v24-38-25,25>>^ Se os príncipes ouvirem que falei contigo, e vierem ter contigo e te disserem: Declara-nos agora o que disseste ao rei e o que o rei te disse; não no-lo encubras, e não te mataremos;

[[v24-38-26]]

^<<v24-38-26,26>>^ então lhes dirás: Eu lancei a minha súplica diante do rei, que não me fizesse tornar à casa de Jônatas, para morrer ali.

[[v24-38-27]]

^<<v24-38-27,27>>^ Então vieram todos os príncipes a Jeremias, e o interrogaram; e ele lhes respondeu conforme todas as palavras que o rei lhe havia ordenado; assim cessaram de falar com ele, pois a coisa não foi percebida.

[[v24-38-28]]

^<<v24-38-28,28>>^ E ficou Jeremias no átrio da guarda, até o dia em que Jerusalém foi tomada.

'''

xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[&#60; Capítulo Anterior] | <<v24-38-0,Topo>> | xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[Próximo Capítulo &#62;]