include::./index.adoc[]

[[v24-13-0]]
=== Jeremias, 13
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-13-1]]

^<<v24-13-1,1>>^ Assim me disse o Senhor: Vai, e compra-te um cinto de linho, e põe-no sobre os teus lombos, mas não o metas na água.

[[v24-13-2]]

^<<v24-13-2,2>>^ E comprei o cinto, conforme a palavra do Senhor, e o pus sobre os meus lombos.

[[v24-13-3]]

^<<v24-13-3,3>>^ Então me veio a palavra do Senhor pela segunda vez, dizendo:

[[v24-13-4]]

^<<v24-13-4,4>>^ Toma o cinto que compraste e que trazes sobre os teus lombos, e levanta-te, vai ao Eufrates, e esconde-o ali na fenda duma rocha.

[[v24-13-5]]

^<<v24-13-5,5>>^ Fui, pois, e escondi-o junto ao Eufrates, como o Senhor me havia ordenado.

[[v24-13-6]]

^<<v24-13-6,6>>^ E passados muitos dias, me disse o Senhor: Levanta-te, vai ao Eufrates, e toma dali o cinto que te ordenei que escondesses ali.

[[v24-13-7]]

^<<v24-13-7,7>>^ Então fui ao Eufrates, e cavei, e tomei o cinto do lugar onde e havia escondido; e eis que o cinto tinha apodrecido, e para nada prestava.

[[v24-13-8]]

^<<v24-13-8,8>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v24-13-9]]

^<<v24-13-9,9>>^ Assim diz o Senhor: Do mesmo modo farei apodrecer a soberba de Judá, e a grande soberba de Jerusalém.

[[v24-13-10]]

^<<v24-13-10,10>>^ Este povo maligno, que se recusa a ouvir as minhas palavras, que caminha segundo a teimosia do seu coração, e que anda após deuses alheios, para os servir, e para os adorar, será tal como este cinto, que para nada presta.

[[v24-13-11]]

^<<v24-13-11,11>>^ Pois, assim como se liga o cinto aos lombos do homem, assim eu liguei a mim toda a casa de Israel, e toda a casa de Judá, diz o Senhor, para me serem por povo, e por nome, e por louvor, e por glória; mas não quiseram ouvir:

[[v24-13-12]]

^<<v24-13-12,12>>^ Pelo que lhes dirás esta palavra: Assim diz o Senhor Deus de Israel: Todo o odre se encherá de vinho. E dir-te-ão: Acaso não sabemos nós muito bem que todo o odre se encherá de vinho?

[[v24-13-13]]

^<<v24-13-13,13>>^ Então lhes dirás: Assim diz o Senhor: Eis que eu encherei de embriaguez a todos os habitantes desta terra, mesmo aos reis que se assentam sobre o trono de Davi, e aos sacerdotes, e aos profetas, e a todos os habitantes de Jerusalém.

[[v24-13-14]]

^<<v24-13-14,14>>^ E atirá-los-ei uns contra os outros, mesmo os pais juntamente com os filhos, diz o Senhor; não terei pena nem pouparei, nem terei deles compaixão para não os destruir.

[[v24-13-15]]

^<<v24-13-15,15>>^ Escutai, e inclinai os ouvidos; não vos ensoberbeçais, porque o Senhor falou.

[[v24-13-16]]

^<<v24-13-16,16>>^ Dai glória ao Senhor vosso Deus, antes que venha a escuridão e antes que tropecem vossos pés nos montes tenebrosos; antes que, esperando vós luz, ele a mude em densas trevas, e a reduza a profunda escuridão.

[[v24-13-17]]

^<<v24-13-17,17>>^ Mas, se não ouvirdes, a minha alma chorará em oculto, por causa da vossa soberba; e amargamente chorarão os meus olhos, e se desfarão em lágrimas, porque o rebanho do Senhor se vai levado cativo.

[[v24-13-18]]

^<<v24-13-18,18>>^ Dize ao rei e à rainha-mãe: Humilhai-vos, sentai-vos no chão; porque de vossas cabeças já caiu a coroa de vossa glória.

[[v24-13-19]]

^<<v24-13-19,19>>^ As cidades do Negebe estão fechadas, e não há quem as abra; todo o Judá é levado cativo, sim, inteiramente cativo.

[[v24-13-20]]

^<<v24-13-20,20>>^ Levantai os vossos olhos, e vede os que vêm do norte; onde está o rebanho que se te deu, o teu lindo rebanho?

[[v24-13-21]]

^<<v24-13-21,21>>^ Que dirás, quando ele puser sobre ti como cabeça os que ensinaste a serem teus amigos? Não te tomarão as dores, como as duma mulher que está de parto?

[[v24-13-22]]

^<<v24-13-22,22>>^ Se disseres no teu coração: Por que me sobrevieram estas coisas? Pela multidão das tuas iniqüidades se descobriram as tuas fraldas, e os teus calcanhares sofrem violência.

[[v24-13-23]]

^<<v24-13-23,23>>^ pode o etíope mudar a sua pele, ou o leopardo as suas malhas? então podereis também vós fazer o bem, habituados que estais a fazer o mal.

[[v24-13-24]]

^<<v24-13-24,24>>^ Pelo que os espalharei como o restolho que passa arrebatado pelo vento do deserto.

[[v24-13-25]]

^<<v24-13-25,25>>^ Esta é a tua sorte, a porção que te é medida por mim, diz o Senhor; porque te esqueceste de mim, e confiaste em mentiras.

[[v24-13-26]]

^<<v24-13-26,26>>^ Assim também eu levantarei as tuas fraldas sobre o teu rosto, e aparecerá a tua ignominia.

[[v24-13-27]]

^<<v24-13-27,27>>^ Os teus adultérios, e os teus rinchos, e a enormidade da tua prostituição, essas abominações tuas, eu as tenho visto sobre os outeiros no campo. Ai de ti, Jerusalém! até quando não te purificarás?

'''

xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[&#60; Capítulo Anterior] | <<v24-13-0,Topo>> | xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[Próximo Capítulo &#62;]