include::./index.adoc[]

[[v24-10-0]]
=== Jeremias, 10
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-10-1]]

^<<v24-10-1,1>>^ Ouvi a palavra que o Senhor vos fala a vós, ó casa de Israel.

[[v24-10-2]]

^<<v24-10-2,2>>^ Assim diz o Senhor: Não aprendais o caminho das nações, nem vos espanteis com os sinais do céu; porque deles se espantam as nações,

[[v24-10-3]]

^<<v24-10-3,3>>^ pois os costumes dos povos são vaidade; corta-se do bosque um madeiro e se lavra com machado pelas mãos do artífice.

[[v24-10-4]]

^<<v24-10-4,4>>^ Com prata e com ouro o enfeitam, com pregos e com martelos o firmam, para que não se mova.

[[v24-10-5]]

^<<v24-10-5,5>>^ São como o espantalho num pepinal, e não podem falar; necessitam de quem os leve, porquanto não podem andar. Não tenhais receio deles, pois não podem fazer o mal, nem tampouco têm poder de fazer o bem.

[[v24-10-6]]

^<<v24-10-6,6>>^ Ninguém há semelhante a ti, ó Senhor; és grande, e grande é o teu nome em poder.

[[v24-10-7]]

^<<v24-10-7,7>>^ Quem te não temeria a ti, ó Rei das nações? pois a ti se deve o temor; porquanto entre todos os sábios das nações, e em todos os seus reinos ninguém há semelhante a ti.

[[v24-10-8]]

^<<v24-10-8,8>>^ Mas eles todos são embrutecidos e loucos; a instrução dos ídolos é como o madeiro.

[[v24-10-9]]

^<<v24-10-9,9>>^ Trazem de Társis prata em chapas, e ouro de Ufaz, trabalho do artífice, e das mãos do fundidor; seus vestidos são de azul e púrpura; obra de peritos são todos eles.

[[v24-10-10]]

^<<v24-10-10,10>>^ Mas o Senhor é o verdadeiro Deus; ele é o Deus vivo e o Rei eterno, ao seu furor estremece a terra, e as nações não podem suportar a sua indignação.

[[v24-10-11]]

^<<v24-10-11,11>>^ Assim lhes direis: Os deuses que não fizeram os céus e a terra, esses perecerão da terra e de debaixo dos céus.

[[v24-10-12]]

^<<v24-10-12,12>>^ Ele fez a terra pelo seu poder; ele estabeleceu o mundo por sua sabedoria e com a sua inteligência estendeu os céus.

[[v24-10-13]]

^<<v24-10-13,13>>^ Quando ele faz soar a sua voz, logo há tumulto de águas nos céus, e ele faz subir das extremidades da terra os vapores; faz os relâmpagos para a chuva, e dos seus tesouros faz sair o vento.

[[v24-10-14]]

^<<v24-10-14,14>>^ Todo homem se embruteceu e não tem conhecimento; da sua imagem esculpida envergonha-se todo fundidor; pois as suas imagens fundidas são falsas, e nelas não há fôlego.

[[v24-10-15]]

^<<v24-10-15,15>>^ Vaidade são, obra de enganos; no tempo da sua visitação virão a perecer.

[[v24-10-16]]

^<<v24-10-16,16>>^ Não é semelhante a estes aquele que é a porção de Jacó; porque ele é o que forma todas as coisas, e Israel é a tribo da sua herança. Senhor dos exércitos é o seu nome.

[[v24-10-17]]

^<<v24-10-17,17>>^ Tira do chão a tua trouxa, ó tu que habitas em lugar sitiado.

[[v24-10-18]]

^<<v24-10-18,18>>^ Pois assim diz o Senhor: Eis que desta vez arrojarei como se fora com uma funda os moradores da terra, e os angustiarei, para que venham a senti-lo.

[[v24-10-19]]

^<<v24-10-19,19>>^ Ai de mim, por causa do meu quebrantamento! a minha chaga me causa grande dor; mas eu havia dito: Certamente isto é minha enfermidade, e eu devo suporta-la.

[[v24-10-20]]

^<<v24-10-20,20>>^ A minha tenda está destruída, e todas as minhas cordas estão rompidas; os meus filhos foram-se de mim, e não existem; ninguém há mais que estire a minha tenda, e que levante as minhas cortinas.

[[v24-10-21]]

^<<v24-10-21,21>>^ Pois os pastores se embruteceram, e não buscaram ao Senhor; por isso não prosperaram, e todos os seus rebanhos se acham dispersos.

[[v24-10-22]]

^<<v24-10-22,22>>^ Eis que vem uma voz de rumor, um grande tumulto da terra do norte, para fazer das cidades de Judá uma assolação, uma morada de chacais.

[[v24-10-23]]

^<<v24-10-23,23>>^ Eu sei, ó Senhor, que não é do homem o seu caminho; nem é do homem que caminha o dirigir os seus passos.

[[v24-10-24]]

^<<v24-10-24,24>>^ Corrige-me, ó Senhor, mas com medida justa; não na tua ira, para que não me reduzas a nada.

[[v24-10-25]]

^<<v24-10-25,25>>^ Derrama a tua indignação sobre as nações que não te conhecem, e sobre as famílias que não invocam o teu nome; porque devoraram a Jacó; sim, devoraram-no e consumiram-no, e assolaram a sua morada.

'''

xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[Próximo Capítulo &#62;]