include::./index.adoc[]

[[v24-46-0]]
=== Jeremias, 46
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-46-1]]

^<<v24-46-1,1>>^ A palavra do Senhor, que veio a Jeremias, o profeta, acerca das nações.

[[v24-46-2]]

^<<v24-46-2,2>>^ Acerca do Egito: a respeito do exército de Faraó-Neco, rei do Egito, que estava junto ao rio Eufrates em Carquêmis, ao qual Nabucodonosor, rei de Babilônia, derrotou no quarto ano de Jeoiaquim, filho de Josias, rei de Judá.

[[v24-46-3]]

^<<v24-46-3,3>>^ Preparai o escudo e o pavês, e chegai-vos para a peleja.

[[v24-46-4]]

^<<v24-46-4,4>>^ Aparelhai os cavalos, e montai, cavaleiros! Apresentai-vos com elmos; açacalai as lanças; vesti-vos de couraças.

[[v24-46-5]]

^<<v24-46-5,5>>^ Por que razão os vejo espantados e voltando as costas? Os seus heróis estão abatidos, e vão fugindo, sem olharem para trás; terror há por todos os lados, diz o Senhor.

[[v24-46-6]]

^<<v24-46-6,6>>^ Não pode fugir o ligeiro, nem escapar o herói; para a banda do norte, junto ao rio Eufrates, tropeçaram e caíram.

[[v24-46-7]]

^<<v24-46-7,7>>^ Quem é este que vem subindo como o Nilo, como rios cujas águas se agitam?

[[v24-46-8]]

^<<v24-46-8,8>>^ O Egito é que vem subindo como o Nilo, e como rios cujas águas se agitam; e ele diz: Subirei, cobrirei a terra; destruirei a cidade e os que nela habitam.

[[v24-46-9]]

^<<v24-46-9,9>>^ Subi, ó cavalos; e estrondeai, ó carros; e saiam valentes: Cuche e Pute, que manejam o escudo, e os de Lude, que manejam e entesam o arco.

[[v24-46-10]]

^<<v24-46-10,10>>^ Porque aquele dia é o dia do Senhor Deus dos exércitos, dia de vingança para ele se vingar dos seus adversários. A espada devorará, e se fartará, e se embriagará com o sangue deles; pois o Senhor Deus dos exércitos tem um sacrifício na terra do Norte junto ao rio Eufrates.

[[v24-46-11]]

^<<v24-46-11,11>>^ Sobe a Gileade, e toma bálsamo, ó virgem filha do Egito; debalde multiplicas remédios; não há cura para ti.

[[v24-46-12]]

^<<v24-46-12,12>>^ As nações ouviram falar da tua vergonha, e a terra está cheia do teu clamor; porque o valente tropeçou no valente e ambos juntos cairam.

[[v24-46-13]]

^<<v24-46-13,13>>^ A palavra que falou o Senhor a Jeremias, o profeta, acerca da vinda de Nabucodonosor, rei de Babilônia, para ferir a terra do Egito.

[[v24-46-14]]

^<<v24-46-14,14>>^ Anunciai-o no Egito, proclamai isto em Migdol; proclamai-o também em Mênfis, e em Tapanes; dizei: Apresenta-te, e prepara-te; porque a espada devorará o que está ao redor de ti.

[[v24-46-15]]

^<<v24-46-15,15>>^ Por que está derribado o teu valente? Ele não ficou em pé, porque o Senhor o abateu.

[[v24-46-16]]

^<<v24-46-16,16>>^ Fez tropeçar a multidão; caíram uns sobre os outros, e disseram: Levanta-te, e voltemos para o nosso povo, para a terra do nosso nascimento, por causa da espada que oprime.

[[v24-46-17]]

^<<v24-46-17,17>>^ Clamaram ali: Faraó, rei do Egito, é apenas um som; deixou passar o tempo assinalado.

[[v24-46-18]]

^<<v24-46-18,18>>^ Vivo eu, diz o Rei, cujo nome é o Senhor dos exércitos, que certamente como o Tabor entre os montes, e como o Carmelo junto ao mar, assim ele vira.

[[v24-46-19]]

^<<v24-46-19,19>>^ Prepara-te para ires para o cativeiro, ó moradora filha do Egito; porque Mênfis será tornada em desolação, e será incendiada, até que ninguém mais aí more.

[[v24-46-20]]

^<<v24-46-20,20>>^ Novilha mui formosa é o Egito; mas já lhe vem do Norte um tavão.

[[v24-46-21]]

^<<v24-46-21,21>>^ Até os seus mercenários no meio dela são como bezerros cevados; mas também eles viraram as costas, fugiram juntos, não ficaram firmes; porque veio sobre eles o dia da sua ruína e o tempo da sua punição.

[[v24-46-22]]

^<<v24-46-22,22>>^ A sua voz irá como a da serpente; porque marcharão com um exército, e virão contra ela com machados, como cortadores de lenha.

[[v24-46-23]]

^<<v24-46-23,23>>^ Cortarão o seu bosque, diz o Senhor, embora seja impenetrável; porque se multiplicaram mais do que os gafanhotos; são inumeráveis.

[[v24-46-24]]

^<<v24-46-24,24>>^ A filha do Egito será envergonhada; será entregue na mão do povo do Norte.

[[v24-46-25]]

^<<v24-46-25,25>>^ Diz o Senhor dos exércitos, o Deus de Israel: Eis que eu castigarei a Amom de Tebas, e a Faraó, e ao Egito, juntamente com os seus deuses e os seus reis, sim, ao próprio Faraó, e aos que nele confiam.

[[v24-46-26]]

^<<v24-46-26,26>>^ E os entregarei na mão dos que procuram a sua morte, na mão de Nabucodonosor, rei de Babilônia, e na mão dos seus servos; mas depois será habitada, como nos dias antigos, diz o Senhor.

[[v24-46-27]]

^<<v24-46-27,27>>^ Mas não temas tu, servo meu, Jacó, nem te espantes, ó Israel; pois eis que te livrarei mesmo de longe, e a tua descendência da terra do seu cativeiro; e Jacó voltará, e ficará tranqüilo e sossegado, e não haverá quem o atemorize.

[[v24-46-28]]

^<<v24-46-28,28>>^ Tu não temas, servo meu, Jacó, diz o senhor; porque estou contigo; pois destruirei totalmente todas as nações para onde te arrojei; mas a ti não te destruirei de todo, mas castigar-te-ei com justiça, e de modo algum te deixarei impune.

'''

xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[Próximo Capítulo &#62;]