include::./index.adoc[]

[[v24-1-0]]
=== Jeremias, 1
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-1-1]]

^<<v24-1-1,1>>^ As palavras de Jeremias, filho de Hilquias, um dos sacerdotes que estavam em Anatote, na terra de Benjamim;

[[v24-1-2]]

^<<v24-1-2,2>>^ ao qual veio a palavra do Senhor, nos dias de Josias, filho de Amom, rei de Judá, no décimo terceiro ano do seu reinado;

[[v24-1-3]]

^<<v24-1-3,3>>^ e lhe veio também nos dias de Jeoiaquim, filho de Josias, rei de Judá, até o fim do ano undécimo de Zedequias, filho de Josias, rei de Judá, até que Jerusalém foi levada em cativeiro no quinto mês.

[[v24-1-4]]

^<<v24-1-4,4>>^ Ora veio a mim a palavra do Senhor, dizendo:

[[v24-1-5]]

^<<v24-1-5,5>>^ Antes que eu te formasse no ventre te conheci, e antes que saísses da madre te santifiquei; às nações te dei por profeta.

[[v24-1-6]]

^<<v24-1-6,6>>^ Então disse eu: Ah, Senhor Deus! Eis que não sei falar; porque sou um menino.

[[v24-1-7]]

^<<v24-1-7,7>>^ Mas o Senhor me respondeu: Não digas: Eu sou um menino; porque a todos a quem eu te enviar, irás; e tudo quanto te mandar dirás.

[[v24-1-8]]

^<<v24-1-8,8>>^ Não temas diante deles; pois eu seu contigo para te livrar, diz o Senhor.

[[v24-1-9]]

^<<v24-1-9,9>>^ Então estendeu o Senhor a mão, e tocou-me na boca; e disse-me o Senhor: Eis que ponho as minhas palavras na tua boca.

[[v24-1-10]]

^<<v24-1-10,10>>^ Olha, ponho-te neste dia sobre as nações, e sobre os reinos, para arrancares e derribares, para destruíres e arruinares; e também para edificares e plantares.

[[v24-1-11]]

^<<v24-1-11,11>>^ E veio a mim a palavra do Senhor, dizendo: Que é que vês, Jeremias? Eu respondi: Vejo uma vara de amendoeira.

[[v24-1-12]]

^<<v24-1-12,12>>^ Então me disse o Senhor: Viste bem; porque eu velo sobre a minha palavra para a cumprir.

[[v24-1-13]]

^<<v24-1-13,13>>^ Veio a mim a palavra do Senhor segunda vez, dizendo: Que é que vês? E eu disse: Vejo uma panela a ferver, que se apresenta da banda do norte.

[[v24-1-14]]

^<<v24-1-14,14>>^ Ao que me disse o Senhor: Do norte se estenderá o mal sobre todos os habitantes da terra.

[[v24-1-15]]

^<<v24-1-15,15>>^ Pois estou convocando todas as famílias dos reinos do norte, diz o Senhor; e, vindo, porá cada um o seu trono à entrada das portas de Jerusalém, e contra todos os seus muros em redor e contra todas as cidades de Judá.

[[v24-1-16]]

^<<v24-1-16,16>>^ E pronunciarei contra eles os meus juízos, por causa de toda a sua malícia; pois me deixaram a mim, e queimaram incenso a deuses estranhos, e adoraram as obras das suas mãos.

[[v24-1-17]]

^<<v24-1-17,17>>^ Tu, pois, cinge os teus lombos, e levanta-te, e dêem-lhes tudo quanto eu te ordenar; não desanimes diante deles, para que eu não te desanime diante deles.

[[v24-1-18]]

^<<v24-1-18,18>>^ Eis que hoje te ponho como cidade fortificada, e como coluna de ferro e muros de bronze contra toda a terra, contra os reis de Judá, contra os seus príncipes, contra os seus sacerdotes, e contra o povo da terra.

[[v24-1-19]]

^<<v24-1-19,19>>^ E eles pelejarão contra ti, mas não prevalecerão; porque eu sou contigo, diz o Senhor, para te livrar.

'''

xref:023-isaias/023-isaias-066.adoc#v23-66-0[&#60; Capítulo Anterior] | <<v24-1-0,Topo>> | xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[Próximo Capítulo &#62;]