include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-3-1]]

^<<v24-3-1,1>>^ Eles dizem: Se um homem despedir sua mulher, e ela se desligar dele, e se ajuntar a outro homem, porventura tornará ele mais para ela? Não se poluiria de todo aquela terra? Ora, tu te maculaste com muitos amantes; mas ainda assim, torna para mim, diz o Senhor.

[[v24-3-2]]

^<<v24-3-2,2>>^ Levanta os teus olhos aos altos escalvados, e vê: onde é o lugar em que não te prostituíste? Nos caminhos te assentavas, esperando-os, como o árabe no deserto. Manchaste a terra com as tuas devassidões e com a tua malícia.

[[v24-3-3]]

^<<v24-3-3,3>>^ Pelo que foram retidas as chuvas copiosas, e não houve chuva tardia; contudo tens a fronte de uma prostituta, e não queres ter vergonha.

[[v24-3-4]]

^<<v24-3-4,4>>^ Não me invocaste há pouco, dizendo: Pai meu, tu és o guia da minha mocidade;

[[v24-3-5]]

^<<v24-3-5,5>>^ Reterá ele para sempre a sua ira? ou indignar-se-á continuamente? Eis que assim tens dito; porém tens feito todo o mal que pudeste.

[[v24-3-6]]

^<<v24-3-6,6>>^ Disse-me mais o Senhor nos dias do rei Josias: Viste, porventura, o que fez a apóstata Israel, como se foi a todo monte alto, e debaixo de toda árvore frondosa, e ali andou prostituindo-se?

[[v24-3-7]]

^<<v24-3-7,7>>^ E eu disse: Depois que ela tiver feito tudo isso, voltará para mim. Mas não voltou; e viu isso a sua aleivosa irmã Judá.

[[v24-3-8]]

^<<v24-3-8,8>>^ Sim viu que, por causa de tudo isso, por ter cometido adultério a pérfida Israel, a despedi, e lhe dei o seu libelo de divórcio, que a aleivosa Judá, sua irmã, não temeu; mas se foi e também ela mesma se prostituiu.

[[v24-3-9]]

^<<v24-3-9,9>>^ E pela leviandade da sua prostituição contaminou a terra, porque adulterou com a pedra e com o pau.

[[v24-3-10]]

^<<v24-3-10,10>>^ Contudo, apesar de tudo isso a sua aleivosa irmã Judá não voltou para mim de todo o seu coração, mas fingidamente, diz o Senhor.

[[v24-3-11]]

^<<v24-3-11,11>>^ E o Senhor me disse: A pérfida Israel mostrou-se mais justa do que a aleivosa Judá.

[[v24-3-12]]

^<<v24-3-12,12>>^ Vai, pois, e apregoa estas palavras para a banda do norte, e diz: Volta, ó pérfida Israel, diz o Senhor. Não olharei em era para ti; porque misericordioso sou, diz o Senhor, e não conservarei para sempre a minha ira.

[[v24-3-13]]

^<<v24-3-13,13>>^ Somente reconhece a tua iniqüidade: que contra o Senhor teu Deus transgrediste, e estendeste os teus favores para os estranhos debaixo de toda árvore frondosa, e não deste ouvidos à minha voz, diz o Senhor.

[[v24-3-14]]

^<<v24-3-14,14>>^ Voltai, ó filhos pérfidos, diz o Senhor; porque eu sou como esposo para vós; e vos tomarei, a um de uma cidade, e a dois de uma família; e vos levarei a Sião;

[[v24-3-15]]

^<<v24-3-15,15>>^ e vos darei pastores segundo o meu coração, os quais vos apascentarão com ciência e com inteligência.

[[v24-3-16]]

^<<v24-3-16,16>>^ E quando vos tiverdes multiplicado e frutificado na terra, naqueles dias, diz o Senhor, nunca mais se dirá: A arca do pacto do Senhor; nem lhes virá ela ao pensamento; nem dela se lembrarão; nem a visitarão; nem se fará mais.

[[v24-3-17]]

^<<v24-3-17,17>>^ Naquele tempo chamarão a Jerusalém o trono do Senhor; e todas as nações se ajuntarão a ela, em nome do Senhor, a Jerusalém; e não mais andarão obstinadamente segundo o propósito do seu coração maligno.

[[v24-3-18]]

^<<v24-3-18,18>>^ Naqueles dias andará a casa de Judá com a casa de Israel; e virão juntas da terra do norte, para a terra que dei em herança a vossos pais.

[[v24-3-19]]

^<<v24-3-19,19>>^ Pensei como te poria entre os filhos, e te daria a terra desejável, a mais formosa herança das nações. Também pensei que me chamarias meu Pai, e que de mim não te desviarias.

[[v24-3-20]]

^<<v24-3-20,20>>^ Deveras, como a mulher se aparta aleivosamente do seu marido, assim aleivosamente te houveste comigo, ó casa de Israel, diz o Senhor.

[[v24-3-21]]

^<<v24-3-21,21>>^ Nos altos escalvados se ouve uma voz, o pranto e as súplicas dos filhos de Israel; porque perverteram o seu caminho, e se esqueceram do Senhor seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ Voltai, ó filhos infiéis, eu curarei a vossa infidelidade. Responderam eles: Eis-nos aqui, vimos a ti, porque tu és o Senhor nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ Certamente em vão se confia nos outeiros e nas orgias nas montanhas; deveras no Senhor nosso Deus está a salvação de Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ A coisa vergonhosa, porém, devorou o trabalho de nossos pais desde a nossa mocidade os seus rebanhos e os seus gados os seus filhos e as suas filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Deitemo-nos em nossa vergonha, e cubra-nos a nossa confusão, porque temos pecado contra o Senhor nosso Deus, nós e nossos pais, desde a nossa mocidade até o dia de hoje; e não demos ouvidos à voz do Senhor nosso Deus.

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]