include::./index.adoc[]

[[v24-16-0]]
=== Jeremias, 16
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-16-1]]

^<<v24-16-1,1>>^ E veio a mim a palavra do Senhor, dizendo:

[[v24-16-2]]

^<<v24-16-2,2>>^ Não tomarás a ti mulher, nem terás filhos nem filhas neste lugar.

[[v24-16-3]]

^<<v24-16-3,3>>^ Pois assim diz o Senhor acerca dos filhos e das filhas que nascerem neste lugar, acerca de suas mães, que os tiverem, e de seus pais que os gerarem nesta terra:

[[v24-16-4]]

^<<v24-16-4,4>>^ Morrerão de enfermidades dolorosas, e não serão pranteados nem sepultados; serão como esterco sobre a face da terra; pela espada e pela fome serão consumidos, e os seus cadáveres servirão de pasto para as aves do céu e para os animais da terra.

[[v24-16-5]]

^<<v24-16-5,5>>^ Pois assim diz o Senhor: Não entres na casa que está de luto, nem vás a lamentá-los, nem te compadeças deles; porque deste povo, diz o Senhor, retirei a minha paz, benignidade e misericórdia.

[[v24-16-6]]

^<<v24-16-6,6>>^ E morrerão nesta terra tanto grandes como pequenos; não serão sepultados, e não os prantearão, nem se farão por eles incisões, nem por eles se raparão os cabelos;

[[v24-16-7]]

^<<v24-16-7,7>>^ nem pão se dará aos que estiverem de luto, para os consolar sobre os mortos; nem se lhes dará a beber o copo da consolação pelo pai ou pela mãe.

[[v24-16-8]]

^<<v24-16-8,8>>^ Não entres na casa do banquete, para te assentares com eles a comer e a beber.

[[v24-16-9]]

^<<v24-16-9,9>>^ Pois assim diz o Senhor dos exércitos, o Deus de Israel: Eis que perante os vossos olhos, e em vossos dias, farei cessar deste lugar a voz de gozo e a voz de alegria, a voz do noivo e a voz da noiva.

[[v24-16-10]]

^<<v24-16-10,10>>^ E quando anunciares a este povo todas estas palavras, e eles te disserem: Por que pronuncia o Senhor sobre :nós todo este grande mal? Qual é a nossa iniqüidade? Qual é o pecado que cometemos contra o Senhor nosso Deus?

[[v24-16-11]]

^<<v24-16-11,11>>^ Então lhes dirás: Porquanto vossos pais me deixaram, diz o Senhor, e se foram após outros deuses, e os serviram e adoraram, e a mim me deixaram, e não guardaram a minha lei;

[[v24-16-12]]

^<<v24-16-12,12>>^ e vós fizestes pior do que vossos pais; pois eis que andais, cada um de vós, após o pensamento obstinado do seu mau coração, recusando ouvir-me a mim;

[[v24-16-13]]

^<<v24-16-13,13>>^ portanto eu vos lançarei fora desta terra, para uma terra que não conhecestes, nem vós nem vossos pais; e ali servireis a deuses estranhos de dia e de noite; pois não vos concederei favor algum.

[[v24-16-14]]

^<<v24-16-14,14>>^ Portanto, eis que dias vêm, diz o Senhor, em que não se dirá mais: Vive o Senhor: que fez subir os filhos de Israel da terra do Egito;

[[v24-16-15]]

^<<v24-16-15,15>>^ mas sim: Vive o Senhor, que fez subir os filhos de Israel da terra do norte, e de todas as terras para onde os tinha lançado; porque eu os farei voltar à sua terra, que dei a seus pais.

[[v24-16-16]]

^<<v24-16-16,16>>^ Eis que mandarei vir muitos pescadores, diz o Senhor, os quais os pescarão; e depois mandarei vir muitos caçadores, os quais os caçarão de todo monte, e de todo outeiro, e até das fendas das rochas.

[[v24-16-17]]

^<<v24-16-17,17>>^ Pois os meus olhos estão sobre todos os seus caminhos; não se acham eles escondidos da minha face, nem está a sua iniqüidade encoberta aos meus olhos.

[[v24-16-18]]

^<<v24-16-18,18>>^ E eu retribuirei em dobro a sua iniqüidade e o seu pecado, porque contaminaram a minha terra com os vultos inertes dos seus ídolos detestáveis, e das suas abominações encheram a minha herança.

[[v24-16-19]]

^<<v24-16-19,19>>^ Ó Senhor, força minha e fortaleza minha, e refúgio meu no dia da angústia, a ti virão as nações desde as extremidades da terra, e dirão: Nossos pais herdaram só mentiras, e vaidade, em que não havia proveito.

[[v24-16-20]]

^<<v24-16-20,20>>^ Pode um homem fazer para si deuses? Esses tais não são deuses!

[[v24-16-21]]

^<<v24-16-21,21>>^ Portanto, eis que lhes farei conhecer, sim desta vez lhes farei conhecer o meu poder e a minha força; e saberão que o meu nome é Jeová.

'''

xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[Próximo Capítulo &#62;]