include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-52-1]]

^<<v24-52-1,1>>^ Era Zedequias da idade de vinte e um anos quando começou a reinar, e reinou onze anos em Jerusalém. O nome de sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ E fez o que era mau aos olhos do Senhor, conforme tudo o que fizera Jeoiaquim.

[[v24-52-3]]

^<<v24-52-3,3>>^ Pois por causa da ira do Senhor, chegou-se a tal ponto em Jerusalém e Judá que ele os lançou da sua presença. E Zedequias rebelou-se contra o rei de Babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ No ano nono do seu reinado, no mês décimo, no décimo dia do mês, veio Nabucodonosor, rei de Babilônia, contra Jerusalém, ele e todo o seu exército, e se acamparam contra ela, e contra ela levantaram tranqueiras ao redor.

[[v24-52-5]]

^<<v24-52-5,5>>^ Assim esteve cercada a cidade, até o ano undécimo do rei Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ No quarto mês, aos nove do mês, a fome prevalecia na cidade, de tal modo que não havia pão para o povo da terra.

[[v24-52-7]]

^<<v24-52-7,7>>^ Então foi aberta uma brecha na cidade; e todos os homens de guerra fugiram, e saíram da cidade de noite, pelo caminho da porta entre os dois muros, a qual está junto ao jardim do rei, enquanto os caldeus estavam ao redor da cidade; e foram pelo caminho da Arabá.

[[v24-52-8]]

^<<v24-52-8,8>>^ Mas o exército dos caldeus perseguiu o rei, e alcançou a Zedequias nas campinas de Jericó; e todo o seu exército se espalhou, abandonando-o.

[[v24-52-9]]

^<<v24-52-9,9>>^ Prenderam o rei, e o fizeram subir ao rei de Babilônia a Ribla na terra de Hamate, o qual lhe pronunciou a sentença.

[[v24-52-10]]

^<<v24-52-10,10>>^ E o rei de Babilônia matou os filhos de Zedequias à sua vista; e também matou a todos os príncipes de Judá em Ribla.

[[v24-52-11]]

^<<v24-52-11,11>>^ E cegou os olhos a Zedequias; e o atou com cadeias; e o rei de Babilônia o levou para Babilônia, e o conservou na prisão até o dia da sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ No quinto mês, no décimo dia do mês, que era o décimo nono ano do rei Nabucodonosor, rei de Babilônia, veio a Jerusalém Nebuzaradão, capitão da guarda, que assistia na presença do rei de Babilônia.

[[v24-52-13]]

^<<v24-52-13,13>>^ E queimou a casa do Senhor, e a casa do rei; como também a todas as casas de Jerusalém, todas as casas importantes, ele as incendiou.

[[v24-52-14]]

^<<v24-52-14,14>>^ E todo o exército dos caldeus, que estava com o capitão da guarda, derribou todos os muros que rodeavam Jerusalém.

[[v24-52-15]]

^<<v24-52-15,15>>^ E os mais pobres do povo, e o resto do povo que tinha ficado na cidade, e os desertores que se haviam passado para o rei de Babilônia, e o resto dos artífices, Nebuzaradão, capitão da guarda, levou-os cativos.

[[v24-52-16]]

^<<v24-52-16,16>>^ Mas dos mais pobres da terra Nebuzaradão, capitão da guarda, deixou ficar alguns, para serem vinhateiros e lavradores.

[[v24-52-17]]

^<<v24-52-17,17>>^ Os caldeus despedaçaram as colunas de bronze que estavam na casa do Senhor, e as bases, e o mar de bronze, que estavam na casa do Senhor, e levaram todo o bronze para Babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ Também tomaram as caldeiras, as pás, as espevitadeiras, as bacias, as colheres, e todos os utensílios de bronze, com que se ministrava.

[[v24-52-19]]

^<<v24-52-19,19>>^ De igual modo o capitão da guarda levou os copos, os braseiros, as bacias, as caldeiras, os castiçais, as colheres, e as tigelas. O que era de ouro, levou como ouro, e o que era de prata, como prata.

[[v24-52-20]]

^<<v24-52-20,20>>^ Quanto às duas colunas, ao mar, e aos doze bois de bronze que estavam debaixo das bases, que fizera o rei Salomão para a casa do Senhor, o peso do bronze de todos estes vasos era incalculável.

[[v24-52-21]]

^<<v24-52-21,21>>^ Dessas colunas, a altura de cada um era de dezoito côvados; doze côvados era a medida da sua circunferência; e era a sua espessura de quatro dedos; e era oca.

[[v24-52-22]]

^<<v24-52-22,22>>^ E havia sobre ela um capitel de bronze; e a altura dum capitel era de cinco côvados, com uma rede e romãs sobre o capitel ao redor, tudo de bronze; e a segunda coluna tinha as mesmas coisas com as romãs.

[[v24-52-23]]

^<<v24-52-23,23>>^ E havia noventa e seis romãs aos lados; as romãs todas, sobre a rede ao redor eram cem.

[[v24-52-24]]

^<<v24-52-24,24>>^ Levou também o capitão da guarda a Seraías, o principal sacerdote, e a Sofonias, o segundo sacerdote, e os três guardas da porta;

[[v24-52-25]]

^<<v24-52-25,25>>^ e da cidade levou um oficial que tinha a seu cargo os homens de guerra; e a sete homens dos que assistiam ao rei e que se achavam na cidade; como também o escrivão-mor do exército, que registrava o povo da terra; e mais sessenta homens do povo da terra que se achavam no meio da cidade.

[[v24-52-26]]

^<<v24-52-26,26>>^ Tomando-os pois Nebuzaradão, capitão da guarda, levou-os ao rei de Babilônia, a Ribla.

[[v24-52-27]]

^<<v24-52-27,27>>^ E o rei de Babilônia os feriu e os matou em Ribla, na terra de Hamate. Assim Judá foi levado cativo para fora da sua terra.

[[v24-52-28]]

^<<v24-52-28,28>>^ Este é o povo que Nabucodonosor levou cativo: no sétimo ano três mil e vinte e três judeus;

[[v24-52-29]]

^<<v24-52-29,29>>^ no ano décimo oitavo de Nabucodonosor, ele levou cativas de Jerusalém oitocentas e trinta e duas pessoas;

[[v24-52-30]]

^<<v24-52-30,30>>^ no ano vinte e três de Nabucodonosor, Nebuzaradão, capitão da guarda, levou cativas, dentre os judeus, setecentas e quarenta e cinco pessoas; todas as pessoas foram quatro mil e seiscentas.

[[v24-52-31]]

^<<v24-52-31,31>>^ No ano trigésimo sétimo do cativeiro de Joaquim, rei de Judá, no mês duodécimo, aos vinte e cinco do mês, Evil-Merodaque, rei de Babilônia, no primeiro ano do seu reinado, levantou a cabeça de Joaquim, rei de Judá, e o tirou do cárcere;

[[v24-52-32]]

^<<v24-52-32,32>>^ e falou com ele benignamente, e pôs o trono dele acima dos tronos dos reis que estavam com ele em Babilônia;

[[v24-52-33]]

^<<v24-52-33,33>>^ e lhe fez mudar a roupa da sua prisão; e Joaquim comia pão na presença do rei continuamente, todos os dias da sua vida.

[[v24-52-34]]

^<<v24-52-34,34>>^ E, quanto à sua ração, foi-lhe dada pelo rei de Babilônia a sua porção quotidiana, até o dia da sua morte, durante todos os dias da sua vida.

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]