include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-20-1]]

^<<v24-20-1,1>>^ Ora Pasur, filho de Imer, o sacerdote, que era superintendente da casa do Senhor, ouviu Jeremias profetizar estas coisas.

[[v24-20-2]]

^<<v24-20-2,2>>^ Então feriu Pasur ao profeta Jeremias, e o meteu no cepo que está na porta superior de Benjamim, na casa do Senhor.

[[v24-20-3]]

^<<v24-20-3,3>>^ No dia seguinte, quando Pasur o tirou do cepo Jeremias lhe disse: O Senhor não te chama Pasur, mas Magor-Missabibe.

[[v24-20-4]]

^<<v24-20-4,4>>^ Porque assim diz o Senhor: Eis que farei de ti um terror para ti mesmo, e para todos os teus amigos. Eles cairão à espada de seus inimigos, e teus olhos o verão. Entregarei Judá todo na mão do rei de Babilônia; ele os levará cativos para Babilônia, e matá-los-á à espada.

[[v24-20-5]]

^<<v24-20-5,5>>^ Também entregarei todas as riquezas desta cidade, todos os seus lucros, e todas as suas coisas preciosas, sim, todos os tesouros dos reis de Judá na mão de seus inimigos, que os saquearão e, tomando-os, os levarão a Babilônia.

[[v24-20-6]]

^<<v24-20-6,6>>^ E tu, Pasur, e todos os moradores da tua casa ireis para o cativeiro; e virás para Babilônia, e ali morrerás, e ali serás sepultado, tu, e todos os teus amigos, aos quais profetizaste falsamente.

[[v24-20-7]]

^<<v24-20-7,7>>^ Seduziste-me, ó Senhor, e deixei-me seduzir; mais forte foste do que eu, e prevaleceste; sirvo de escárnio o dia todo; cada um deles zomba de mim.

[[v24-20-8]]

^<<v24-20-8,8>>^ Pois sempre que falo, grito, clamo: Violência e destruição; porque se tornou a palavra do Senhor um opróbrio para mim, e um ludíbrio o dia todo.

[[v24-20-9]]

^<<v24-20-9,9>>^ Se eu disser: Não farei menção dele, e não falarei mais no seu nome, então há no meu coração um como fogo ardente, encerrado nos meus ossos, e estou fatigado de contê-lo, e não posso mais.

[[v24-20-10]]

^<<v24-20-10,10>>^ Pois ouço a difamação de muitos, terror por todos os lados! Denunciai-o! Denunciemo-lo! dizem todos os meus íntimos amigos, aguardando o meu manquejar; bem pode ser que se deixe enganar; então prevaleceremos contra ele e nos vingaremos dele.

[[v24-20-11]]

^<<v24-20-11,11>>^ Mas o Senhor está comigo como um guerreiro valente; por isso tropeçarão os meus perseguidores, e não prevalecerão; ficarão muito confundidos, porque não alcançarão êxito, sim, terão uma confusão perpétua que nunca será esquecida.

[[v24-20-12]]

^<<v24-20-12,12>>^ Tu pois, ó Senhor dos exércitos, que provas o justo, e vês os pensamentos e o coração, permite que eu veja a tua vingança sobre eles; porque te confiei a minha causa.

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantai ao Senhor, louvai ao Senhor; pois livrou a alma do necessitado da mão dos malfeitores.

[[v24-20-14]]

^<<v24-20-14,14>>^ Maldito o dia em que nasci; não seja bendito o dia em que minha mãe me deu à luz.

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito o homem que deu as novas a meu pai, dizendo: Nasceu-te um filho, alegrando-o com isso grandemente.

[[v24-20-16]]

^<<v24-20-16,16>>^ E seja esse homem como as cidades que o senhor destruiu sem piedade; e ouça ele um clamor pela manhã, e um alarido ao meio-dia.

[[v24-20-17]]

^<<v24-20-17,17>>^ Por que não me matou na madre? assim minha mãe teria sido a minha sepultura, e teria ficado grávida perpetuamente!

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que saí da madre, para ver trabalho e tristeza, e para que se consumam na vergonha os meus dias?

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]