include::./index.adoc[]

[[v24-14-0]]
=== Jeremias, 14
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-14-1]]

^<<v24-14-1,1>>^ A palavra do Senhor, que veio a Jeremias, a respeito da seca.

[[v24-14-2]]

^<<v24-14-2,2>>^ Judá chora, e as suas portas estão enfraquecidas; eles se sentam de luto no chão; e o clamor de Jerusalém já vai subindo.

[[v24-14-3]]

^<<v24-14-3,3>>^ E os seus nobres mandam os seus inferiores buscar água; estes vão às cisternas, e não acham água; voltam com os seus cântaros vazios; ficam envergonhados e confundidos, e cobrem as suas cabeças.

[[v24-14-4]]

^<<v24-14-4,4>>^ Por causa do solo ressecado, pois que não havia chuva sobre a terra, os lavradores ficam envergonhados e cobrem as suas cabeças.

[[v24-14-5]]

^<<v24-14-5,5>>^ Pois até a cerva no campo pare, e abandona sua cria, porquanto não há erva.

[[v24-14-6]]

^<<v24-14-6,6>>^ E os asnos selvagens se põem nos altos escalvados e, ofegantes, sorvem o ar como os chacais; desfalecem os seus olhos, porquanto não ha erva.

[[v24-14-7]]

^<<v24-14-7,7>>^ Posto que as nossas iniqüidades testifiquem contra nós, ó Senhor, opera tu por amor do teu nome; porque muitas são as nossas rebeldias; contra ti havemos pecado.

[[v24-14-8]]

^<<v24-14-8,8>>^ Ó esperança de Israel, e Redentor seu no tempo da angústia! por que serias como um estrangeiro na terra? e como o viandante que arma a sua tenda para passar a noite?

[[v24-14-9]]

^<<v24-14-9,9>>^ Por que serias como homem surpreendido, como valoroso que não pode livrar? Mas tu estás no meio de nós, Senhor, e nós somos chamados pelo teu nome; não nos desampares.

[[v24-14-10]]

^<<v24-14-10,10>>^ Assim diz o Senhor acerca deste povo: Pois que tanto gostaram de andar errantes, e não detiveram os seus pés, por isso o Senhor não os aceita, mas agora se lembrará da iniqüidade deles, e visitará os seus pecados.

[[v24-14-11]]

^<<v24-14-11,11>>^ Disse-me ainda o Senhor: Não rogues por este povo para seu bem.

[[v24-14-12]]

^<<v24-14-12,12>>^ Quando jejuarem, não ouvirei o seu clamor, e quando oferecerem holocaustos e oblações, não me agradarei deles; antes eu os consumirei pela espada, e pela fome e pela peste.

[[v24-14-13]]

^<<v24-14-13,13>>^ Então disse eu: Ah! Senhor Deus, eis que os profetas lhes dizem: Não vereis espada, e não tereis fome; antes vos darei paz verdadeira neste lugar.

[[v24-14-14]]

^<<v24-14-14,14>>^ E disse-me o Senhor: Os profetas profetizam mentiras em meu nome; não os enviei, nem lhes dei ordem, nem lhes falei. Visão falsa, adivinhação, vaidade e o engano do seu coração é o que eles vos profetizam.

[[v24-14-15]]

^<<v24-14-15,15>>^ Portanto assim diz o Senhor acerca dos profetas que profetizam em meu nome, sem que eu os tenha mandado, e que dizem: Nem espada, nem fome haverá nesta terra: À espada e à fome serão consumidos esses profetas.

[[v24-14-16]]

^<<v24-14-16,16>>^ E o povo a quem eles profetizam será lançado nas ruas de Jerusalém, por causa da fome e da espada; e não haverá quem os sepulte a eles, a suas mulheres, a seus filhos e a suas filhas; porque derramarei sobre eles a sua maldade.

[[v24-14-17]]

^<<v24-14-17,17>>^ Portanto lhes dirás esta palavra: Os meus olhos derramem lágrimas de noite e de dia, e não cessem; porque a virgem filha do meu povo está gravemente ferida, de mui dolorosa chaga.

[[v24-14-18]]

^<<v24-14-18,18>>^ Se eu saio ao campo, eis os mortos à espada, e, se entro na cidade, eis os debilitados pela fome; o profeta e o sacerdote percorrem a terra, e nada sabem.

[[v24-14-19]]

^<<v24-14-19,19>>^ Porventura já de todo rejeitaste a Judá? Aborrece a tua alma a Sião? Por que nos feriste, de modo que não há cura para nós? Aguardamos a paz, e não chegou bem algum; e o tempo da cura, e eis o pavor!

[[v24-14-20]]

^<<v24-14-20,20>>^ Ah, Senhor! reconhecemos a nossa impiedade e a iniqüidade de nossos pais; pois contra ti havemos pecado.

[[v24-14-21]]

^<<v24-14-21,21>>^ Não nos desprezes, por amor do teu nome; não tragas opróbrio sobre o trono da tua glória; lembra-te, e não anules o teu pacto conosco.

[[v24-14-22]]

^<<v24-14-22,22>>^ Há, porventura, entre os deuses falsos das nações, algum que faça chover? Ou podem os céus dar chuvas? Não és tu, ó Senhor, nosso Deus? Portanto em ti esperaremos; pois tu tens feito todas estas coisas.

'''

xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[Próximo Capítulo &#62;]