include::./index.adoc[]

[[v24-9-0]]
=== Jeremias, 9
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-9-1]]

^<<v24-9-1,1>>^ Oxalá a minha cabeça se tornasse em águas, e os meus olhos numa fonte de lágrimas, para que eu chorasse de dia e de noite os mortos da filha do meu povo!

[[v24-9-2]]

^<<v24-9-2,2>>^ Oxalá que eu tivesse no deserto uma estalagem de viandantes, para poder deixar o meu povo, e me apartar dele! porque todos eles são adúlteros, um bando de aleivosos.

[[v24-9-3]]

^<<v24-9-3,3>>^ E encurvam a língua, como se fosse o seu arco, para a mentira; fortalecem-se na terra, mas não para a verdade; porque avançam de malícia em malícia, e a mim me não conhecem, diz o Senhor.

[[v24-9-4]]

^<<v24-9-4,4>>^ Guardai-vos cada um do seu próximo, e de irmão nenhum vos fieis; porque todo irmão não faz mais do que enganar, e todo próximo anda caluniando.

[[v24-9-5]]

^<<v24-9-5,5>>^ E engana cada um a seu próximo, e nunca fala a verdade; ensinaram a sua língua a falar a mentira; andam-se cansando em praticar a iniqüidade.

[[v24-9-6]]

^<<v24-9-6,6>>^ A tua habitação está no meio do engano; pelo engano recusam-se a conhecer-me, diz o Senhor.

[[v24-9-7]]

^<<v24-9-7,7>>^ Portanto assim diz o Senhor dos exércitos: Eis que eu os fundirei e os provarei; pois, de que outra maneira poderia proceder com a filha do meu povo?

[[v24-9-8]]

^<<v24-9-8,8>>^ uma flecha mortífera é a língua deles; fala engano; com a sua boca fala cada um de paz com o seu próximo, mas no coração arma-lhe ciladas.

[[v24-9-9]]

^<<v24-9-9,9>>^ Não hei de castigá-los por estas coisas? diz o Senhor; ou não me vingarei de uma nação tal como esta?

[[v24-9-10]]

^<<v24-9-10,10>>^ Pelos montes levantai choro e pranto, e pelas pastagens do deserto lamentação; porque já estão queimadas, de modo que ninguém passa por elas; nem se ouve mugido de gado; desde as aves dos céus até os animais, fugiram e se foram.

[[v24-9-11]]

^<<v24-9-11,11>>^ E farei de Jerusalém montões de pedras, morada de chacais, e das cidades de Judá farei uma desolação, de sorte que fiquem sem habitantes.

[[v24-9-12]]

^<<v24-9-12,12>>^ Quem é o homem sábio, que entenda isto? e a quem falou a boca do Senhor, para que o possa anunciar? Por que razão pereceu a terra, e se queimou como um deserto, de sorte que ninguém passa por ela?

[[v24-9-13]]

^<<v24-9-13,13>>^ E diz o Senhor: porque deixaram a minha lei, que lhes pus diante, e não deram ouvidos à minha voz, nem andaram nela,

[[v24-9-14]]

^<<v24-9-14,14>>^ antes andaram obstinadamente segundo o seu próprio coração, e após baalins, como lhes ensinaram os seus pais.

[[v24-9-15]]

^<<v24-9-15,15>>^ Portanto assim diz o Senhor dos exércitos, Deus de Israel: Eis que darei de comer losna a este povo, e lhe darei a beber água de fel.

[[v24-9-16]]

^<<v24-9-16,16>>^ Também os espalharei por entre nações que nem eles nem seus pais conheceram; e mandarei a espada após eles, até que venha a consumi-los.

[[v24-9-17]]

^<<v24-9-17,17>>^ Assim diz o Senhor dos exércitos: Considerai, e chamai as carpideiras, para que venham; e mandai procurar mulheres hábeis, para que venham também;

[[v24-9-18]]

^<<v24-9-18,18>>^ e se apressem, e levantem o seu lamento sobre nós, para que se desfaçam em lágrimas os nossos olhos, e as nossas pálpebras destilem águas.

[[v24-9-19]]

^<<v24-9-19,19>>^ Porque uma voz de pranto se ouviu de Sião: Como estamos arruinados! Estamos mui envergonhados, por termos deixado a terra, e por terem eles transtornado as nossas moradas.

[[v24-9-20]]

^<<v24-9-20,20>>^ Contudo ouvi, vós, mulheres, a palavra do Senhor, e recebam os vossos ouvidos a palavra da sua boca; e ensinai a vossas filhas o pranto, e cada uma à sua vizinha a lamentação.

[[v24-9-21]]

^<<v24-9-21,21>>^ Pois a morte subiu pelas nossas janelas, e entrou em nossos palácios, para exterminar das ruas as crianças, e das praças os mancebos.

[[v24-9-22]]

^<<v24-9-22,22>>^ Fala: Assim diz o Senhor: Até os cadáveres dos homens cairão como esterco sobre a face do campo, e como gavela atrás do segador, e não há quem a recolha.

[[v24-9-23]]

^<<v24-9-23,23>>^ Assim diz o Senhor: Não se glorie o sábio na sua sabedoria, nem se glorie o forte na sua força; não se glorie o rico nas suas riquezas;

[[v24-9-24]]

^<<v24-9-24,24>>^ mas o que se gloriar, glorie-se nisto: em entender, e em me conhecer, que eu sou o Senhor, que faço benevolência, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor.

[[v24-9-25]]

^<<v24-9-25,25>>^ Eis que vêm dias, diz o Senhor, em que castigarei a todo circuncidado pela sua incircuncisão:

[[v24-9-26]]

^<<v24-9-26,26>>^ ao Egito, a Judá e a Edom, aos filhos de Amom e a Moabe, e a todos os que cortam os cantos da sua cabeleira e habitam no deserto; pois todas as nações são incircuncisas, e toda a casa de Israel é incircuncisa de coração.

'''

xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[Próximo Capítulo &#62;]