include::./index.adoc[]

[[v24-24-0]]
=== Jeremias, 24
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-24-1]]

^<<v24-24-1,1>>^ Fez-me o Senhor ver, e vi dois cestos de figos, postos diante do templo do Senhor. Sucedeu isso depois que Nabucodonosor, rei de Babilônia, levara em cativeiro a Jeconias, filho de Jeoiaquim, rei de Judá, e os príncipes de Judá, e os carpinteiros, e os ferreiros de Jerusalém, e os trouxera a Babilônia.

[[v24-24-2]]

^<<v24-24-2,2>>^ Um cesto tinha figos muito bons, como os figos temporãos; mas o outro cesto tinha figos muito ruins, que não se podiam comer, de ruins que eram.

[[v24-24-3]]

^<<v24-24-3,3>>^ E perguntou-me o Senhor: Que vês tu, Jeremias? E eu respondi: Figos; os figos bons, muito bons, e os ruins, muito ruins, que não se podem comer, de ruins que são.

[[v24-24-4]]

^<<v24-24-4,4>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v24-24-5]]

^<<v24-24-5,5>>^ Assim diz o Senhor, o Deus de Israel: Como a estes bons figos, assim atentarei com favor para os exilados de Judá, os quais eu enviei deste lugar para a terra dos caldeus.

[[v24-24-6]]

^<<v24-24-6,6>>^ Porei os meus olhos sobre eles, para seu bem, e os farei voltar a esta terra. Edificá-los-ei, e não os demolirei; e plantá-los-ei, e não os arrancarei.

[[v24-24-7]]

^<<v24-24-7,7>>^ E dar-lhes-ei coração para que me conheçam, que eu sou o Senhor; e eles serão o meu povo, e eu serei o seu Deus; pois se voltarão para mim de todo o seu coração.

[[v24-24-8]]

^<<v24-24-8,8>>^ E como os figos ruins, que não se podem comer, de ruins que são, certamente assim diz o Senhor: Do mesmo modo entregarei Zedequias, rei de Judá, e os seus príncipes, e o resto de Jerusalém, que ficou de resto nesta terra, e os que habitam na terra do Egito;

[[v24-24-9]]

^<<v24-24-9,9>>^ eu farei que sejam espetáculo horrendo, uma ofensa para todos os reinos da terra, um opróbrio e provérbio, um escárnio, e uma maldição em todos os lugares para onde os arrojarei.

[[v24-24-10]]

^<<v24-24-10,10>>^ E enviarei entre eles a espada, a fome e a peste, até que sejam consumidos de sobre a terra que lhes dei a eles e a seus pais.

'''

xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[&#60; Capítulo Anterior] | <<v24-24-0,Topo>> | xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[Próximo Capítulo &#62;]