include::./index.adoc[]

[[v24-44-0]]
=== Jeremias, 44
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-44-1]]

^<<v24-44-1,1>>^ A palavra que veio a Jeremias, acerca de todos os judeus, que habitavam na terra do Egito, em Migdol, em Tapanes, em Mênfis, e no país de Patros:

[[v24-44-2]]

^<<v24-44-2,2>>^ Assim diz o Senhor dos exércitos, Deus de Israel: Vós vistes todo o mal que fiz cair sobre Jerusalém, e sobre todas as cidades de Judá; e eis que elas são hoje uma desolação, e ninguém nelas habita;

[[v24-44-3]]

^<<v24-44-3,3>>^ por causa da sua maldade que fizeram, para me irarem, indo queimar incenso, e servir a outros deuses, a quem eles nunca conheceram, nem eles, nem vós, nem vossos pais.

[[v24-44-4]]

^<<v24-44-4,4>>^ Todavia eu vos enviei persistentemente todos os meus servos, os profetas, para vos dizer: Ora, não façais esta coisa abominável que odeio!

[[v24-44-5]]

^<<v24-44-5,5>>^ Mas eles não escutaram, nem inclinaram os seus ouvidos, para se converterem da sua maldade, para não queimarem incenso a outros deuses.

[[v24-44-6]]

^<<v24-44-6,6>>^ Pelo que se derramou a minha indignação e a minha ira, e acendeu-se nas cidades de Judá, e nas ruas de Jerusalém; e elas tornaram-se em deserto e em desolação, como hoje se vê.

[[v24-44-7]]

^<<v24-44-7,7>>^ Agora, pois, assim diz o Senhor, Deus dos exércitos, Deus de Israel: Por que fazeis vós tão grande mal contra vós mesmos, para desarraigardes o homem e a mulher, a criança e o que mama, dentre vós, do meio de Judá, a fim de não vos deixardes ali resto algum;

[[v24-44-8]]

^<<v24-44-8,8>>^ irando-me com as obras de vossas mãos, queimando incenso a outros deuses na terra do Egito, aonde vós entrastes para lá peregrinardes, para que sejais exterminados, e para que sirvais de maldição e de opróbrio entre todas as nações da terra?

[[v24-44-9]]

^<<v24-44-9,9>>^ Esquecestes já as maldades de vossos pais, as maldades dos reis de Judá, as maldades das suas mulheres, as vossas maldades e as maldades das vossas mulheres, cometidas na terra de Judá e nas ruas de Jerusalém?

[[v24-44-10]]

^<<v24-44-10,10>>^ Não se humilharam até o dia de hoje, nem temeram, nem andaram na minha lei, nem nos meus estatutos, que pus diante de vós e diante de vossos pais.

[[v24-44-11]]

^<<v24-44-11,11>>^ Portanto assim diz o Senhor dos exércitos, Deus de Israel: Eis que eu ponho o meu rosto contra vós para mal, e para desarraigar todo o Judá.

[[v24-44-12]]

^<<v24-44-12,12>>^ E tomarei os que restam de Judá, os quais puseram o seu rosto para entrar na terra do Egito, a fim de lá peregrinarem, e todos eles serão consumidos; na terra do Egito cairão; à espada, e de fome serão consumidos; desde o menor até o maior morrerão à espada e de fome; e tornar-se-ão um espetáculo de execração, de espanto, de maldição e de opróbrio.

[[v24-44-13]]

^<<v24-44-13,13>>^ Pois castigarei os que habitam na terra do Egito, como castiguei Jerusalém, com a espada, a fome e a peste.

[[v24-44-14]]

^<<v24-44-14,14>>^ De maneira que, da parte remanescente de Judá que entrou na terra do Egito a fim de lá peregrinar, não haverá quem escape e fique para tornar à terra de Judá, à qual era seu grande desejo voltar, para ali habitar; mas não voltarão, senão um pugilo de fugitivos.

[[v24-44-15]]

^<<v24-44-15,15>>^ Então responderam a Jeremias todos os homens que sabiam que suas mulheres queimavam incenso a outros deuses, e todas as mulheres que estavam presentes, uma grande multidão, a saber, todo o povo que habitava na terra do Egito, em Patros, dizendo:

[[v24-44-16]]

^<<v24-44-16,16>>^ Quanto à palavra que nos anunciaste em nome do Senhor, não te obedeceremos a ti;

[[v24-44-17]]

^<<v24-44-17,17>>^ mas certamente cumpriremos toda a palavra que saiu da nossa boca, de queimarmos incenso à rainha do céu, e de lhe oferecermos libações, como nós e nossos pais, nossos reis e nossos príncipes, temos feito, nas cidades de Judá, e nas ruas de Jerusalém; então tínhamos fartura de pão, e prosperávamos, e não vimos mal algum.

[[v24-44-18]]

^<<v24-44-18,18>>^ Mas desde que cessamos de queimar incenso à rainha do céu, e de lhe oferecer libações, temos tido falta de tudo, e temos sido consumidos pela espada e pela fome.

[[v24-44-19]]

^<<v24-44-19,19>>^ E nós, as mulheres, quando queimávamos incenso à rainha do céu, e lhe oferecíamos libações, acaso lhe fizemos bolos para a adorar e lhe oferecemos libações sem nossos maridos?

[[v24-44-20]]

^<<v24-44-20,20>>^ Então disse Jeremias a todo o povo, aos homens e às mulheres, e a todo o povo que lhe havia dado essa resposta, dizendo:

[[v24-44-21]]

^<<v24-44-21,21>>^ Porventura não se lembrou o Senhor, e não lhe veio à mente o incenso que queimastes nas cidades de Judá e nas ruas de Jerusalém, vós e vossos pais, vossos reis e vossos príncipes, como também o povo da terra?

[[v24-44-22]]

^<<v24-44-22,22>>^ O Senhor não podia por mais tempo suportar a maldade das vossas ações, as abominações que cometestes; pelo que se tornou a vossa terra em desolação, e em espanto, e em maldição, sem habitantes, como hoje se vê.

[[v24-44-23]]

^<<v24-44-23,23>>^ Porquanto queimastes incenso, e pecastes contra o Senhor, não obedecendo à voz do Senhor, nem andando na sua lei, nos seus estatutos e nos seus testemunhos; por isso vos sobreveio este mal, como se vê neste dia.

[[v24-44-24]]

^<<v24-44-24,24>>^ Disse mais Jeremias a todo o povo e a todas as mulheres: Ouvi a palavra do Senhor, vós, todo o Judá, que estais na terra do Egito.

[[v24-44-25]]

^<<v24-44-25,25>>^ Assim fala o Senhor dos exércitos, Deus de Israel, dizendo: Vós e vossas mulheres falastes por vossa boca, e com as vossas mãos o cumpristes, dizendo: Certamente cumpriremos os nossos votos que fizemos, de queimarmos incenso à rainha do céu e de lhe derramarmos libações; confirmai, pois, os vossos votos, e cumpri-os!

[[v24-44-26]]

^<<v24-44-26,26>>^ Ouvi, pois, a palavra do Senhor, todos os de Judá que habitais na terra do Egito: Eis que eu juro pelo meu grande nome, diz o Senhor, que nunca mais será pronunciado o meu nome pela boca de nenhum homem de Judá em toda a terra do Egito, dizendo: Como vive o Senhor Deus!

[[v24-44-27]]

^<<v24-44-27,27>>^ Eis que velarei sobre eles para o mal, e não para o bem; e serão consumidos todos os homens de Judá que estão na terra do Egito, pela espada e pela fome, até que de todo se acabem.

[[v24-44-28]]

^<<v24-44-28,28>>^ E os que escaparem da espada voltarão da terra do Egito para a terra de Judá, poucos em número; e saberá todo o resto de Judá que entrou na terra do Egito para peregrinar ali, se subsistirá a minha palavra ou a sua.

[[v24-44-29]]

^<<v24-44-29,29>>^ E isto vos servirá de sinal, diz o Senhor, de que eu vos castigarei neste lugar, para que saibais que certamente subsistirão as minhas palavras contra vós para o mal:

[[v24-44-30]]

^<<v24-44-30,30>>^ Assim diz o Senhor: Eis que eu entregarei Faraó-Hofra, rei do Egito, na mão de seus inimigos, e na mão dos que procuram a sua morte; como entreguei Zedequias, rei de Judá, na mão de Nabucodonosor, rei de Babilônia, seu inimigo, e que procurava a sua morte.

'''

xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[&#60; Capítulo Anterior] | <<v24-44-0,Topo>> | xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[Próximo Capítulo &#62;]