include::./index.adoc[]

[[v24-50-0]]
=== Jeremias, 50
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-50-1]]

^<<v24-50-1,1>>^ A palavra que falou o Senhor acerca de Babilônia, acerca da terra dos caldeus, por intermédio de Jeremias o profeta.

[[v24-50-2]]

^<<v24-50-2,2>>^ Anunciai entre as nações e publicai, arvorando um estandarte; sim publicai, não encubrais; dizei: Tomada está Babilônia, confundido está Bel, caído está Merodaque, confundidos estão os seus ídolos, e caídos estão os seus deuses.

[[v24-50-3]]

^<<v24-50-3,3>>^ Pois do Norte sobe contra ela uma nação que fará da sua terra uma desolação, e não haverá quem nela habite; tanto os homens como os animais já fugiram e se foram.

[[v24-50-4]]

^<<v24-50-4,4>>^ Naqueles dias, e naquele tempo, diz o Senhor, os filhos de Israel virão, eles e os filhos de Judá juntamente; andando e chorando virão, e buscarão ao Senhor seu Deus.

[[v24-50-5]]

^<<v24-50-5,5>>^ Acerca de Sião indagarão, tendo os seus rostos voltados para lá e dizendo: Vinde e uni-vos ao Senhor num pacto eterno que nunca será esquecido.

[[v24-50-6]]

^<<v24-50-6,6>>^ Ovelhas perdidas têm sido o meu povo; os seus pastores as fizeram errar, e voltar aos montes; de monte para outeiro andaram, esqueceram-se do lugar de seu repouso.

[[v24-50-7]]

^<<v24-50-7,7>>^ Todos os que as achavam as devoraram, e os seus adversários diziam: Culpa nenhuma teremos; porque pecaram contra o Senhor, a morada da justiça, sim, o Senhor, a esperança de seus pais.

[[v24-50-8]]

^<<v24-50-8,8>>^ Fugi do meio de Babilônia, e saí da terra dos caldeus, e sede como os bodes diante do rebanho.

[[v24-50-9]]

^<<v24-50-9,9>>^ Pois eis que eu suscitarei e farei subir contra Babilônia uma companhia de grandes nações da terra do Norte; e por-se-ão em ordem contra ela; dali será ela tomada. As suas flechas serão como as de valente herói; nenhuma tornará sem efeito.

[[v24-50-10]]

^<<v24-50-10,10>>^ E Caldéia servirá de presa; todos os que a saquearem ficarão fartos, diz o Senhor.

[[v24-50-11]]

^<<v24-50-11,11>>^ Embora vos alegreis e vos regozijeis, ó saqueadores da minha herança, embora andeis soltos como novilha que pisa a erva, e rincheis como cavalos vigorosos,

[[v24-50-12]]

^<<v24-50-12,12>>^ muito envergonhada será vossa mãe, ficará humilhada a que vos deu à luz; eis que ela será a última das nações, um deserto, uma terra seca e uma solidão.

[[v24-50-13]]

^<<v24-50-13,13>>^ Por causa da ira do Senhor não será habitada, antes se tornará em total desolação; qualquer que passar por Babilônia se espantará, e assobiará por causa de todas as suas pragas.

[[v24-50-14]]

^<<v24-50-14,14>>^ Ponde-vos em ordem para cercar Babilônia, todos os que armais arcos; atirai-lhe, não poupeis as flechas, porque ela tem pecado contra o Senhor.

[[v24-50-15]]

^<<v24-50-15,15>>^ Gritai contra ela rodeando-a; ela já se submeteu; caíram seus baluartes, estão derribados os seus muros. Pois esta é a vingança do Senhor; vingai-vos dela; conforme o que ela fez, assim lhe fazei a ela.

[[v24-50-16]]

^<<v24-50-16,16>>^ Cortai de Babilônia o que semeia, e o que maneja a foice no tempo da sega; por causa da espada do opressor virar-se-á cada um para o seu povo, e fugirá cada qual para a sua terra.

[[v24-50-17]]

^<<v24-50-17,17>>^ Cordeiro desgarrado é Israel, os leões o afugentaram; o primeiro a devorá-lo foi o rei da Assíria, e agora por último Nabucodonosor, rei de Babilônia, lhe quebrou os ossos.

[[v24-50-18]]

^<<v24-50-18,18>>^ Portanto, assim diz o Senhor dos exércitos, Deus de Israel: Eis que castigarei o rei de Babilônia e a sua terra, como castiguei o rei da Assíria.

[[v24-50-19]]

^<<v24-50-19,19>>^ E farei voltar Israel para a sua morada, e ele pastará no Carmelo e em Basã, e se fartará nos outeiros de Efraim e em Gileade.

[[v24-50-20]]

^<<v24-50-20,20>>^ Naqueles dias, e naquele tempo, diz o Senhor, buscar-se-á a iniqüidade em Israel, e não haverá; e o pecado em Judá, e não se achará; pois perdoarei aos que eu deixar de resto.

[[v24-50-21]]

^<<v24-50-21,21>>^ Sobe contra a terra de Merataim, sim, contra ela, e contra os moradores de Pecode; mata e inteiramente destrói tudo após eles, diz o Senhor, e faze conforme tudo o que te ordenei.

[[v24-50-22]]

^<<v24-50-22,22>>^ Na terra há estrondo de batalha, e de grande destruição.

[[v24-50-23]]

^<<v24-50-23,23>>^ Como foi cortado e quebrado o martelo de toda a terra! como se tornou Babilônia em objeto de espanto entre as nações!

[[v24-50-24]]

^<<v24-50-24,24>>^ Laços te armei, e também foste presa, ó Babilônia, e tu não o soubeste; foste achada, e também apanhada, porque contra o Senhor te entremeteste.

[[v24-50-25]]

^<<v24-50-25,25>>^ O Senhor abriu o seu arsenal, e tirou os instrumentos da sua indignação; porque o senhor Deus dos exércitos tem uma obra a realizar na terra dos caldeus.

[[v24-50-26]]

^<<v24-50-26,26>>^ Vinde contra ela dos confins da terra, abri os seus celeiros; fazei dela montões, e destruí-a de todo; nada lhe fique de resto.

[[v24-50-27]]

^<<v24-50-27,27>>^ Matai a todos os seus novilhos, desçam ao degoladouro; ai deles! porque é chegado o seu dia, o tempo da sua punição.

[[v24-50-28]]

^<<v24-50-28,28>>^ Eis a voz dos que fogem e escapam da terra de Babilônia para anunciarem em Sião a vingança do Senhor nosso Deus, a vingança do seu templo.

[[v24-50-29]]

^<<v24-50-29,29>>^ Convocai contra Babilônia os flecheiros, todos os que armam arcos; acampai-vos contra ela em redor, ninguém escape dela. Pagai-lhe conforme a sua obra; conforme tudo o que ela fez, assim lhe fazei a ela; porque se houve arrogantemente contra o Senhor, contra o Santo de Israel.

[[v24-50-30]]

^<<v24-50-30,30>>^ Portanto cairão os seus jovens nas suas praças, e todos os seus homens de guerra serão destruídos naquele dia, diz o Senhor.

[[v24-50-31]]

^<<v24-50-31,31>>^ Eis que eu sou contra ti, ó soberbo, diz o Senhor Deus dos exércitos; pois o teu dia é chegado, o tempo em que te hei de punir?

[[v24-50-32]]

^<<v24-50-32,32>>^ Então tropeçará o soberbo, e cairá, e ninguém haverá que o levante; e porei fogo às suas cidades, o qual consumirá tudo o que está ao seu redor.

[[v24-50-33]]

^<<v24-50-33,33>>^ Assim diz o Senhor dos exércitos: Os filhos de Israel e os filhos de Judá são juntamente oprimidos; e todos os que os levaram cativos os retêm, recusam soltá-los.

[[v24-50-34]]

^<<v24-50-34,34>>^ Mas o seu Redentor é forte; o Senhor dos exércitos é o seu nome. Certamente defenderá em juízo a causa deles, para dar descanso à terra, e inquietar os moradores de Babilônia.

[[v24-50-35]]

^<<v24-50-35,35>>^ A espada virá sobre os caldeus, diz o senhor, e sobre os moradores de Babilônia, e sobre os seus príncipes, e sobre os seus sábios.

[[v24-50-36]]

^<<v24-50-36,36>>^ A espada virá sobre os paroleiros, e eles ficarão insensatos; a espada virá sobre os seus valentes, e eles desfalecerão.

[[v24-50-37]]

^<<v24-50-37,37>>^ A espada virá sobre os seus cavalos, e sobre os seus carros, e sobre todo o povo misto, que se acha no meio dela, e eles se tornarão como mulheres; a espada virá sobre os seus tesouros, e estes serão saqueados.

[[v24-50-38]]

^<<v24-50-38,38>>^ Cairá a seca sobre as suas águas, e elas secarão; pois é uma terra de imagens esculpidas, e eles pelos seus ídolos fazem-se loucos.

[[v24-50-39]]

^<<v24-50-39,39>>^ Por isso feras do deserto juntamente com lobos habitarão ali; também habitarão nela avestruzes; e nunca mais será povoada, nem será habitada de geração em geração.

[[v24-50-40]]

^<<v24-50-40,40>>^ Como quando Deus subverteu a Sodoma e a Gomorra, e às suas cidades vizinhas, diz o Senhor, assim ninguém habitará ali, nem peregrinará nela filho de homem.

[[v24-50-41]]

^<<v24-50-41,41>>^ Eis que um povo vem do norte; e uma grande nação e muitos reis se levantam das extremidades da terra.

[[v24-50-42]]

^<<v24-50-42,42>>^ Armam-se de arco e lança; são cruéis, e não têm piedade; a sua voz brama como o mar, e em cavalos vêm montados, dispostos como homens para a batalha, contra ti, ó filha de Babilônia.

[[v24-50-43]]

^<<v24-50-43,43>>^ O rei de Babilônia ouviu a fama deles, e desfaleceram as suas mãos; a angústia se apoderou dele, dores, como da que está de parto.

[[v24-50-44]]

^<<v24-50-44,44>>^ Eis que como leão subirá das margens do Jordão um inimigo contra a morada forte, mas de repente o farei correr dali; e ao escolhido, pô-lo-ei sobre ela. Pois quem é semelhante a mim? e quem me fixará um prazo? Quem é o pastor que me poderá resistir?

[[v24-50-45]]

^<<v24-50-45,45>>^ Portanto ouvi o conselho que o Senhor decretou contra Babilônia, e o propósito que formou contra a terra dos caldeus: Certamente eles, os pequenos do rebanho, serão arrastados; certamente o aprisco ficará apavorado por causa deles.

[[v24-50-46]]

^<<v24-50-46,46>>^ Ao estrondo da tomada de Babilônia estremece a terra; e o grito se ouve entre as nações.

'''

xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[Próximo Capítulo &#62;]