include::./index.adoc[]

[[v24-11-0]]
=== Jeremias, 11
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-11-1]]

^<<v24-11-1,1>>^ A palavra que veio a Jeremias, da parte do Senhor, dizendo:

[[v24-11-2]]

^<<v24-11-2,2>>^ Ouvi as palavras deste pacto, e falai aos homens de Judá, e aos habitantes de Jerusalém.

[[v24-11-3]]

^<<v24-11-3,3>>^ Dize-lhes pois: Assim diz o Senhor, o Deus de Israel: Maldito o homem que não ouvir as palavras deste pacto,

[[v24-11-4]]

^<<v24-11-4,4>>^ que ordenei a vossos pais no dia em que os tirei da terra do Egito, da fornalha de ferro, dizendo: Ouvi a minha voz, e fazei conforme a tudo que vos mando; assim vós sereis o meu povo, e eu serei o vosso Deus;

[[v24-11-5]]

^<<v24-11-5,5>>^ para que eu confirme o juramento que fiz a vossos pais de dar-lhes uma terra que manasse leite e mel, como se vê neste dia. Então eu respondi, e disse: Amém, ó Senhor.

[[v24-11-6]]

^<<v24-11-6,6>>^ Disse-me, pois, o Senhor: Proclama todas estas palavras nas cidades de Judá, e nas ruas de Jerusalém, dizendo: Ouvi as palavras deste pacto, e cumpri-as.

[[v24-11-7]]

^<<v24-11-7,7>>^ Porque com instância admoestei a vossos pais, no dia em que os tirei da terra do Egito, até o dia de hoje, protestando persistentemente e dizendo: Ouvi a minha voz.

[[v24-11-8]]

^<<v24-11-8,8>>^ Mas não ouviram, nem inclinaram os seus ouvidos; antes andaram cada um na obstinação do seu coração malvado; pelo que eu trouxe sobre eles todas as palavras deste pacto, as quais lhes ordenei que cumprissem, mas não o fizeram.

[[v24-11-9]]

^<<v24-11-9,9>>^ Disse-me mais o Senhor: Uma conspiração se achou entre os homens de Judá, e entre os habitantes de Jerusalém.

[[v24-11-10]]

^<<v24-11-10,10>>^ Tornaram às iniqüidades de seus primeiros pais, que recusaram ouvir as minhas palavras; até se foram após outros deuses para os servir; a casa de Israel e a casa de Judá quebrantaram o meu pacto, que fiz com seus pais.

[[v24-11-11]]

^<<v24-11-11,11>>^ Portanto assim diz o Senhor: Eis que estou trazendo sobre eles uma calamidade de que não poderão escapar; clamarão a mim, mas eu não os ouvirei.

[[v24-11-12]]

^<<v24-11-12,12>>^ Então irão as cidades de Judá e os habitantes de Jerusalém e clamarão aos deuses a que eles queimam incenso; estes, porém, de maneira alguma os livrarão no tempo da sua calamidade.

[[v24-11-13]]

^<<v24-11-13,13>>^ Pois, segundo o número das tuas cidades, são os teus deuses, ó Judá; e, segundo o número das ruas de Jerusalém, tendes levantado altares à impudência, altares para queimardes incenso a Baal.

[[v24-11-14]]

^<<v24-11-14,14>>^ Tu, pois, não ores por este povo, nem levantes por eles clamor nem oração; porque não os ouvirei no tempo em que eles clamarem a mim por causa da sua calamidade.

[[v24-11-15]]

^<<v24-11-15,15>>^ Que direito tem a minha amada na minha casa, visto que com muitos tem cometido grande abominação, e as carnes santas se desviaram de ti? Quando tu fazes mal, então andas saltando de prazer.

[[v24-11-16]]

^<<v24-11-16,16>>^ Denominou-te o Senhor oliveira verde, formosa por seus deliciosos frutos; mas agora, à voz dum grande tumulto, acendeu fogo nela, e se quebraram os seus ramos.

[[v24-11-17]]

^<<v24-11-17,17>>^ Porque o Senhor dos exércitos, que te plantou, pronunciou contra ti uma calamidade, por causa do grande mal que a casa de Israel e a casa de Judá fizeram, pois me provocaram à ira, queimando incenso a Baal.

[[v24-11-18]]

^<<v24-11-18,18>>^ E o Senhor mo fez saber, e eu o soube; então me fizeste ver as suas ações.

[[v24-11-19]]

^<<v24-11-19,19>>^ Mas eu era como um manso cordeiro, que se leva à matança; não sabia que era contra mim que maquinavam, dizendo: Destruamos a árvore com o seu fruto, e cortemo-lo da terra dos viventes, para que não haja mais memória do seu nome.

[[v24-11-20]]

^<<v24-11-20,20>>^ Mas, ó Senhor dos exércitos, justo Juiz, que provas o coração e a mente, permite que eu veja a tua vingança sobre eles; pois a ti descobri a minha causa.

[[v24-11-21]]

^<<v24-11-21,21>>^ Portanto assim diz o Senhor acerca dos homens de Anatote, que procuram a tua vida, dizendo: Não profetizes no nome do Senhor, para que não morras às nossas mãos;

[[v24-11-22]]

^<<v24-11-22,22>>^ por isso assim diz o Senhor dos exércitos: Eis que eu os punirei; os mancebos morrerão à espada, os seus filhos e as suas filhas morrerão de fome.

[[v24-11-23]]

^<<v24-11-23,23>>^ E não ficará deles um resto; pois farei vir sobre os homens de Anatote uma calamidade, sim, o ano da sua punição.

'''

xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[Próximo Capítulo &#62;]