include::./index.adoc[]

[[v24-35-0]]
=== Jeremias, 35
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-35-1]]

^<<v24-35-1,1>>^ A palavra que da parte do Senhor veio a Jeremias, nos dias de Jeoiaquim, filho de Josias, rei de Judá, dizendo:

[[v24-35-2]]

^<<v24-35-2,2>>^ Vai à casa dos recabitas, e fala com eles, introduzindo-os na casa do Senhor, em uma das câmaras, e lhes oferece vinho a beber.

[[v24-35-3]]

^<<v24-35-3,3>>^ Então tomei a Jaazanias, filho de Jeremias, filho de Habazínias, e a seus irmãos, e a todos os seus filhos, e a toda a casa dos recabitas,

[[v24-35-4]]

^<<v24-35-4,4>>^ e os introduzi na casa do Senhor, na câmara dos filhos de Hanã, filho de Jigdalias, homem de Deus, a qual estava junto à câmara dos príncipes que ficava sobre a câmara de Maaséias, filho de Salum, guarda do vestíbulo;

[[v24-35-5]]

^<<v24-35-5,5>>^ e pus diante dos filhos da casa dos recabitas taças cheias de vinho, e copos, e disse-lhes: Bebei vinho.

[[v24-35-6]]

^<<v24-35-6,6>>^ Eles, porém, disseram: Não beberemos vinho, porque Jonadabe, filho de Recabe, nosso pai, nos ordenou, dizendo: Nunca jamais bebereis vinho, nem vós nem vossos filhos;

[[v24-35-7]]

^<<v24-35-7,7>>^ não edificareis casa, nem semeareis semente, nem plantareis vinha, nem a possuireis; mas habitareis em tendas todos os vossos dias; para que vivais muitos dias na terra em que andais peregrinando.

[[v24-35-8]]

^<<v24-35-8,8>>^ Obedecemos pois à voz de Jonadabe, filho de Recabe, nosso pai, em tudo quanto nos ordenou, de não bebermos vinho em todos os nossos dias, nem nós, nem nossas mulheres, nem nossos filhos, nem nossas filhas;

[[v24-35-9]]

^<<v24-35-9,9>>^ nem de edificarmos casas para nossa habitação; nem de possuirmos vinha, nem campo, nem semente;

[[v24-35-10]]

^<<v24-35-10,10>>^ mas habitamos em tendas, e assim obedecemos e fazemos conforme tudo quanto nos ordenou Jonadabe, nosso pai.

[[v24-35-11]]

^<<v24-35-11,11>>^ Sucedeu, porém, que, quando subia Nabucodonosor, rei de Babilônia, contra esta terra, dissemos: Vinde, e vamo-nos a Jerusalém, por causa do exército dos caldeus, e por causa do exército dos sírios; e assim habitamos em Jerusalém.

[[v24-35-12]]

^<<v24-35-12,12>>^ Então veio a palavra do Senhor a Jeremias, dizendo:

[[v24-35-13]]

^<<v24-35-13,13>>^ Assim diz o Senhor dos exércitos, o Deus de Israel: Vai, e dize aos homens de Judá e aos moradores de Jerusalém: Acaso não aceitareis instrução, para ouvirdes as minhas palavras? diz o Senhor.

[[v24-35-14]]

^<<v24-35-14,14>>^ As palavras de Jonadabe, filho de Recabe, pelas quais ordenou a seus filhos que não bebessem vinho, foram guardadas; pois não o têm bebido até o dia de hoje, porque obedecem o mandamento de seu pai; a mim, porém, que vos tenho falado a vós, com insistência, vós não me ouvistes.

[[v24-35-15]]

^<<v24-35-15,15>>^ Também vos tenho enviado, insistentemente, todos os meus servos, os profetas, dizendo: Convertei-vos agora, cada um do seu mau caminho, e emendai as vossas ações, e não vades após outros deuses para os servir, e assim habitareis na terra que vos dei a vós e a vossos pais; mas não inclinastes o vosso ouvido, nem me obedecestes a mim.

[[v24-35-16]]

^<<v24-35-16,16>>^ Os filhos de Jonadabe, filho de Recabe, guardaram o mandamento de seu pai que ele lhes ordenou, mas este povo não me obedeceu;

[[v24-35-17]]

^<<v24-35-17,17>>^ por isso assim diz o Senhor, o Deus dos exércitos, o Deus de Israel: Eis que trarei sobre Judá, e sobre todos os moradores de Jerusalém, todo o mal que pronunciei contra eles; pois lhes tenho falado, e não ouviram; e clamei a eles, e não responderam.

[[v24-35-18]]

^<<v24-35-18,18>>^ E à casa dos recabitas disse Jeremias: Assim diz o Senhor dos exércitos, o Deus de Israel: Pois que obedecestes ao mandamento de Jonadabe, vosso pai, guardando todos os seus mandamentos e fazendo conforme tudo quanto vos ordenou;

[[v24-35-19]]

^<<v24-35-19,19>>^ portanto assim diz o Senhor dos exércitos, Deus de Israel: Nunca jamais faltará varão a Jonadabe, filho de Recabe, que assista diante de mim.

'''

xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[Próximo Capítulo &#62;]