include::./index.adoc[]

[[v24-43-0]]
=== Jeremias, 43
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-43-1]]

^<<v24-43-1,1>>^ Tendo Jeremias acabado de falar a todo o povo todas as palavras do Senhor seu Deus, aquelas palavras com as quais o Senhor seu Deus lho havia enviado,

[[v24-43-2]]

^<<v24-43-2,2>>^ então falaram Azarias, filho de Hosaías, e Joanã, filho de Careá, e todos os homens soberbos, dizendo a Jeremias: Tu dizes mentiras; o Senhor nosso Deus não te enviou a dizer: Não entreis no Egito para ali peregrinardes;

[[v24-43-3]]

^<<v24-43-3,3>>^ mas Baruque, filho de Nerias, é que te incita contra nós, para nos entregar na mão dos caldeus, para eles nos matarem, ou para nos levarem cativos para Babilônia.

[[v24-43-4]]

^<<v24-43-4,4>>^ Não obedeceu pois Joanã, filho de Careá, nem nenhum de todos os príncipes dos exércitos, nem o povo todo, à voz do Senhor, para ficarem na terra de Judá.

[[v24-43-5]]

^<<v24-43-5,5>>^ Mas Joanã, filho de Careá, e todos os chefes das forças tomaram a todo o resto de Judá, que havia voltado dentre todas as nações, para onde haviam sido arrojados, com o fim de peregrinarem na terra de Judá;

[[v24-43-6]]

^<<v24-43-6,6>>^ aos homens, às mulheres, às crianças, e às filhas do rei, e a toda pessoa que Nebuzaradão, capitão da guarda, deixara com Gedalias, filho de Aicão, filho de Safã, como também a Jeremias, o profeta, e a Baruque, filho de Nerias;

[[v24-43-7]]

^<<v24-43-7,7>>^ e entraram na terra do Egito; pois não obedeceram à voz do Senhor; assim vieram até Tapanes.

[[v24-43-8]]

^<<v24-43-8,8>>^ Então veio a palavra do Senhor a Jeremias, em Tapanes, dizendo:

[[v24-43-9]]

^<<v24-43-9,9>>^ Toma na tua mão pedras grandes, e esconde-as com barro no pavimento que está à entrada da casa de Faraó em Tapanes, à vista dos homens de Judá;

[[v24-43-10]]

^<<v24-43-10,10>>^ e dize-lhes: Assim diz o Senhor dos exércitos, Deus de Israel: Eis que eu enviarei, e tomarei a Nabucodonosor, rei de Babilônia, meu servo, e porei o seu trono sobre estas pedras que escondi; e ele estenderá o seu pavilhão real sobre elas.

[[v24-43-11]]

^<<v24-43-11,11>>^ Virá, e ferirá a terra do Egito, entregando à morte quem é para a morte, ao cativeiro quem é para o cativeiro, e à espada.

[[v24-43-12]]

^<<v24-43-12,12>>^ E lançarei fogo às casas dos deuses do Egito; e ele os queimará e os levará cativos; e ornar-se-á da terra do Egito, como se veste o pastor com a sua roupa; e sairá dali em paz.

[[v24-43-13]]

^<<v24-43-13,13>>^ E quebrará as colunas de Bete-Semes, que está na terra do Egito; e as casas dos deuses do Egito queimará a fogo.

'''

xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[&#60; Capítulo Anterior] | <<v24-43-0,Topo>> | xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[Próximo Capítulo &#62;]