include::./index.adoc[]

[[v24-28-0]]
=== Jeremias, 28
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-28-1]]

^<<v24-28-1,1>>^ E sucedeu no mesmo ano, no princípio do reinado de Zedequias, rei de Judá, no ano quarto, no mês quinto, que Hananias, filho de Azur, o profeta de Gibeão, me falou, na casa do Senhor, na presença dos sacerdotes e de todo o povo dizendo:

[[v24-28-2]]

^<<v24-28-2,2>>^ Assim fala o Senhor dos exércitos, o Deus de Israel, dizendo: Eu quebrarei o jugo do rei de Babilônia.

[[v24-28-3]]

^<<v24-28-3,3>>^ Dentro de dois anos, eu tornarei a trazer a este lugar todos os utensílios da casa do Senhor, que deste lugar tomou Nabucodonosor, rei de Babilônia, levando-os para Babilônia.

[[v24-28-4]]

^<<v24-28-4,4>>^ Também a Jeconias, filho de Jeoiaquim rei de Judá, e a todos os do cativeiro de, Judá, que entraram em Babilônia, eu os tornarei a trazer a este lugar, diz o Senhor; porque hei de quebrar o jugo do rei de Babilônia.

[[v24-28-5]]

^<<v24-28-5,5>>^ Então falou o profeta Jeremias ao profeta Hananias, na presença dos sacerdotes, e na presença de todo o povo que estava na casa do Senhor.

[[v24-28-6]]

^<<v24-28-6,6>>^ Disse pois Jeremias, o profeta: Amém! assim faça o Senhor; cumpra o Senhor as tuas palavras, que profetizaste, e torne ele a trazer os utensílios da casa do Senhor, e todos os do cativeiro, de Babilônia para este lugar.

[[v24-28-7]]

^<<v24-28-7,7>>^ Mas ouve agora esta palavra, que eu falo aos teus ouvidos e aos ouvidos de todo o povo:

[[v24-28-8]]

^<<v24-28-8,8>>^ Os profetas que houve antes de mim e antes de ti, desde a antigüidade, profetizaram contra muitos países e contra grandes reinos, acerca de guerra, de fome e de peste.

[[v24-28-9]]

^<<v24-28-9,9>>^ Quanto ao profeta que profetuar de paz, quando se cumprir a palavra desse profeta, então será conhecido que o Senhor na verdade enviou o profeta.

[[v24-28-10]]

^<<v24-28-10,10>>^ Então o profeta Hananias tomou o canzil do pescoço do profeta Jeremias e o quebrou.

[[v24-28-11]]

^<<v24-28-11,11>>^ E falou Hananias na presença de todo o povo, dizendo: Isto diz o Senhor: Assim dentro de dois anos quebrarei o jugo de Nabucodonosor, rei de Babilônia, de sobre o pescoço de todas as nações. E Jeremias, o profeta, se foi seu caminho.

[[v24-28-12]]

^<<v24-28-12,12>>^ Então veio a palavra do Senhor a Jeremias, depois de ter o profeta Hananias quebrado o jugo de sobre o pescoço do profeta Jeremias, dizendo:

[[v24-28-13]]

^<<v24-28-13,13>>^ Vai, e fala a Hananias, dizendo: Assim diz o Senhor: Jugos de madeira quebraste, mas em vez deles farei jugos de ferro

[[v24-28-14]]

^<<v24-28-14,14>>^ Pois assim diz o Senhor dos exércitos o Deus de Israel Jugo de ferro pus sobre o, pescoço de todas estas nações, para servirem a Nabucodonosor, rei de Babilônia, e o servirão; e até os animais do campo lhe dei.

[[v24-28-15]]

^<<v24-28-15,15>>^ Então disse o profeta Jeremias ao profeta Hananias: Ouve agora, Hananias: O Senhor não te enviou, mas tu fazes que este povo confie numa mentira.

[[v24-28-16]]

^<<v24-28-16,16>>^ Pelo que assim diz o Senhor: Eis que te lançarei de sobre a face da terra. Este ano morrerás, porque pregaste rebelião contra o Senhor.

[[v24-28-17]]

^<<v24-28-17,17>>^ Morreu, pois, Hananias, o profeta, no mesmo ano, no sétimo mês.

'''

xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[&#60; Capítulo Anterior] | <<v24-28-0,Topo>> | xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[Próximo Capítulo &#62;]