include::./index.adoc[]

[[v24-31-0]]
=== Jeremias, 31
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-31-1]]

^<<v24-31-1,1>>^ Naquele tempo, diz o Senhor, serei o Deus de todas as famílias de Israel, e elas serão o meu povo.

[[v24-31-2]]

^<<v24-31-2,2>>^ Assim diz o Senhor: O povo que escapou da espada achou graça no deserto. Eu irei e darei descanso a Israel.

[[v24-31-3]]

^<<v24-31-3,3>>^ De longe o Senhor me apareceu, dizendo: Pois que com amor eterno te amei, também com benignidade te atraí.

[[v24-31-4]]

^<<v24-31-4,4>>^ De novo te edificarei, e serás edificada ó virgem de Israel! ainda serás adornada com os teus adufes, e sairás nas danças dos que se alegram.

[[v24-31-5]]

^<<v24-31-5,5>>^ Ainda plantarás vinhas nos montes de Samária; os plantadores plantarão e gozarão dos frutos.

[[v24-31-6]]

^<<v24-31-6,6>>^ Pois haverá um dia em que gritarão os vigias sobre o monte de Efraim: Levantai-vos, e subamos a Sião, ao Senhor nosso Deus.

[[v24-31-7]]

^<<v24-31-7,7>>^ Pois assim diz o Senhor: Cantai sobre Jacó com alegria, e exultai por causa da principal das nações; proclamai, cantai louvores, e dizei: Salva, Senhor, o teu povo, o resto de Israel.

[[v24-31-8]]

^<<v24-31-8,8>>^ Eis que os trarei da terra do norte e os congregarei das extremidades da terra; e com eles os cegos e aleijados, as mulheres grávidas e as de parto juntamente; em grande companhia voltarão para cá.

[[v24-31-9]]

^<<v24-31-9,9>>^ Virão com choro, e com súplicas os levarei; guiá-los-ei aos ribeiros de águas, por caminho direito em que não tropeçarão; porque sou um pai para Israel, e Efraim é o meu primogênito.

[[v24-31-10]]

^<<v24-31-10,10>>^ Ouvi a palavra do Senhor, ó nações, e anunciai-a nas longínquas terras marítimas, e dizei: Aquele que espalhou a Israel o congregará e o guardará, como o pastor ao seu rebanho.

[[v24-31-11]]

^<<v24-31-11,11>>^ Pois o Senhor resgatou a Jacó, e o livrou da mão do que era mais forte do que ele.

[[v24-31-12]]

^<<v24-31-12,12>>^ E virão, e cantarão de júbilo nos altos de Sião, e ficarão radiantes pelos bens do Senhor, pelo trigo, o mosto, e o azeite, pelos cordeiros e os bezerros; e a sua vida será como um jardim regado, e nunca mais desfalecerão.

[[v24-31-13]]

^<<v24-31-13,13>>^ Então a virgem se alegrará na dança, como também os mancebos e os velhos juntamente; porque tornarei o seu pranto em gozo, e os consolarei, e lhes darei alegria em lugar de tristeza.

[[v24-31-14]]

^<<v24-31-14,14>>^ E saciarei de gordura a alma dos sacerdotes, e o meu povo se fartará dos meus bens, diz o Senhor.

[[v24-31-15]]

^<<v24-31-15,15>>^ Assim diz o Senhor: Ouviu-se um clamor em Ramá, lamentação e choro amargo. Raquel chora a seus filhos, e não se deixa consolar a respeito deles, porque já não existem.

[[v24-31-16]]

^<<v24-31-16,16>>^ Assim diz o Senhor: Reprime a tua voz do choro, e das lágrimas os teus olhos; porque há galardão para o teu trabalho, diz o Senhor, e eles voltarão da terra do inimigo.

[[v24-31-17]]

^<<v24-31-17,17>>^ E há esperança para o teu futuro, diz o Senhor; pois teus filhos voltarão para os seus termos.

[[v24-31-18]]

^<<v24-31-18,18>>^ Bem ouvi eu que Efraim se queixava, dizendo: Castigaste-me e fui castigado, como novilho ainda não domado; restaura-me, para que eu seja restaurado, pois tu és o Senhor meu Deus.

[[v24-31-19]]

^<<v24-31-19,19>>^ Na verdade depois que me desviei, arrependi-me; e depois que fui instruído, bati na minha coxa; fiquei confundido e envergonhado, porque suportei o opróbrio da minha mocidade.

[[v24-31-20]]

^<<v24-31-20,20>>^ Não é Efraim meu filho querido? filhinho em quem me deleito? Pois quantas vezes falo contra ele, tantas vezes me lembro dele solicitamente; por isso se comovem por ele as minhas entranhas; deveras me compadecerei dele, diz o Senhor.

[[v24-31-21]]

^<<v24-31-21,21>>^ Põe-te marcos, faze postes que te guiem; dirige a tua atenção à estrada, ao caminho pelo qual foste; regressa, ó virgem de Israel, regressa a estas tuas cidades.

[[v24-31-22]]

^<<v24-31-22,22>>^ Até quando andarás errante, ó filha rebelde? pois o senhor criou uma coisa nova na terra: uma mulher protege a um varão.

[[v24-31-23]]

^<<v24-31-23,23>>^ Assim diz o Senhor dos exércitos, o Deus de Israel: Ainda dirão esta palavra na terra de Judá, e nas suas cidades, quando eu acabar o seu cativeiro: O Senhor te abençoe, ó morada de justiça, ó monte de santidade!

[[v24-31-24]]

^<<v24-31-24,24>>^ E nela habitarão Judá, e todas as suas cidades juntamente; como também os lavradores e os que pastoreiam os rebanhos.

[[v24-31-25]]

^<<v24-31-25,25>>^ Pois saciarei a alma cansada, e fartarei toda alma desfalecida.

[[v24-31-26]]

^<<v24-31-26,26>>^ Nisto acordei, e olhei; e o meu sono foi doce para mim.

[[v24-31-27]]

^<<v24-31-27,27>>^ Eis que os dias vêm, diz o Senhor, em que semearei de homens e de animais a casa de Israel e a casa de Judá.

[[v24-31-28]]

^<<v24-31-28,28>>^ E será que, como vigiei sobre eles para arrancar e derribar, para transtornar, destruir, e afligir, assim vigiarei sobre eles para edificar e para plantar, diz o Senhor.

[[v24-31-29]]

^<<v24-31-29,29>>^ Naqueles dias não dirão mais: Os pais comeram uvas verdes, e os dentes dos filhos se embotaram.

[[v24-31-30]]

^<<v24-31-30,30>>^ Pelo contrário, cada um morrerá pela sua própria iniqüidade; de todo homem que comer uvas verdes, é que os dentes se embotarão.

[[v24-31-31]]

^<<v24-31-31,31>>^ Eis que os dias vêm, diz o Senhor, em que farei um pacto novo com a casa de Israel e com a casa de Judá,

[[v24-31-32]]

^<<v24-31-32,32>>^ não conforme o pacto que fiz com seus pais, no dia em que os tomei pela mão, para os tirar da terra do Egito, esse meu pacto que eles invalidaram, apesar de eu os haver desposado, diz o Senhor.

[[v24-31-33]]

^<<v24-31-33,33>>^ Mas este é o pacto que farei com a casa de Israel depois daqueles dias, diz o Senhor: Porei a minha lei no seu interior, e a escreverei no seu coração; e eu serei o seu Deus e eles serão o meu povo.

[[v24-31-34]]

^<<v24-31-34,34>>^ E não ensinarão mais cada um a seu próximo, nem cada um a seu irmão, dizendo: Conhecei ao Senhor; porque todos me conhecerão, desde o menor deles até o maior, diz o Senhor; pois lhes perdoarei a sua iniqüidade, e não me lembrarei mais dos seus pecados.

[[v24-31-35]]

^<<v24-31-35,35>>^ Assim diz o Senhor, que dá o sol para luz do dia, e a ordem estabelecida da lua e das estrelas para luz da noite, que agita o mar, de modo que bramem as suas ondas; o Senhor dos exércitos é o seu nome:

[[v24-31-36]]

^<<v24-31-36,36>>^ Se esta ordem estabelecida falhar diante de mim, diz o Senhor, deixará também a linhagem de Israel de ser uma nação diante de mim para sempre.

[[v24-31-37]]

^<<v24-31-37,37>>^ Assim diz o Senhor: Se puderem ser medidos os céus lá em cima, e sondados os fundamentos da terra cá em baixo, também eu rejeitarei toda a linhagem de Israel, por tudo quanto eles têm feito, diz o Senhor.

[[v24-31-38]]

^<<v24-31-38,38>>^ Eis que vêm os dias, diz o Senhor, em que esta cidade será reedificada para o Senhor, desde a torre de Hananel até a porta da esquina.

[[v24-31-39]]

^<<v24-31-39,39>>^ E a linha de medir estender-se-á para diante, até o outeiro de Garebe, e dará volta até Goa.

[[v24-31-40]]

^<<v24-31-40,40>>^ E o vale inteiro dos cadáveres e da cinza, e todos os campos até o ribeiro de Cedrom, até a esquina da porta dos cavalos para o oriente, tudo será santo ao Senhor; nunca mais será arrancado nem derribado.

'''

xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[Próximo Capítulo &#62;]