include::./index.adoc[]

[[v24-45-0]]
=== Jeremias, 45
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-45-1]]

^<<v24-45-1,1>>^ A palavra que Jeremias, o profeta, falou a Banique, filho de Nerias, quando este escrevia num livro as palavras ditadas por Jeremias, no quarto ano de Jeoiaquim, filho de Josias, rei de Judá:

[[v24-45-2]]

^<<v24-45-2,2>>^ Assim diz o Senhor, Deus de Israel, acerca de ti ó Baruque.

[[v24-45-3]]

^<<v24-45-3,3>>^ Disseste: Ai de mim agora! porque me acrescentou o Senhor tristeza à minha dor; estou cansado do meu gemer, e não acho descanso.

[[v24-45-4]]

^<<v24-45-4,4>>^ Isto lhe dirás: Assim diz o Senhor: Eis que estou a demolir o que edifiquei, e a arrancar o que plantei, e isso em toda esta terra.

[[v24-45-5]]

^<<v24-45-5,5>>^ E procuras tu grandezas para ti mesmo? Não as busques; pois eis que estou trazendo o mal sobre toda a raça, diz o Senhor; porém te darei a tua vida por despojo, em todos os lugares para onde fores.

'''

xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[&#60; Capítulo Anterior] | <<v24-45-0,Topo>> | xref:024-jeremias/024-jeremias-046.adoc#v24-46-0[Próximo Capítulo &#62;]