include::./index.adoc[]

[[v24-37-0]]
=== Jeremias, 37
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-37-1]]

^<<v24-37-1,1>>^ E Zedequias, filho de Josias, a quem Nabucodonosor, rei de Babilônia, constituiu rei na terra de Judá, reinou em lugar de Conias, filho de Jeoiaquim.

[[v24-37-2]]

^<<v24-37-2,2>>^ Mas nem ele, nem os seus servos, nem o povo da terra escutaram as palavras do Senhor que este falou por intermédio de Jeremias o profeta.

[[v24-37-3]]

^<<v24-37-3,3>>^ Contudo mandou o rei Zedequias a Jeucal filho de Selemias, e a Sofonias, filho de Maaséias, o sacerdote, ao profeta Jeremias, para lhe dizerem: Roga agora por nós ao Senhor nosso Deus,

[[v24-37-4]]

^<<v24-37-4,4>>^ Ora, Jeremias entrava e saía entre o povo; pois ainda não o tinham encerrado na prisão.

[[v24-37-5]]

^<<v24-37-5,5>>^ E o exército de Faraó saíra do Egito; quando, pois, os caldeus que estavam sitiando Jerusalém, ouviram esta notícia, retiraram-se de Jerusalém.

[[v24-37-6]]

^<<v24-37-6,6>>^ Então veio a Jeremias, o profeta, a palavra do Senhor, dizendo:

[[v24-37-7]]

^<<v24-37-7,7>>^ Assim diz o Senhor, Deus de Israel: Assim direis ao rei de Judá, que vos enviou a mim, para me consultar: Eis que o exército de Faraó, que saiu em vosso socorro, voltará para a sua terra no Egito.

[[v24-37-8]]

^<<v24-37-8,8>>^ E voltarão os caldeus, e pelejarão contra esta cidade, e a tomarão, e a queimarão a fogo.

[[v24-37-9]]

^<<v24-37-9,9>>^ Assim diz o Senhor: Não vos enganeis a vós mesmos, dizendo: Sem dúvida os caldeus se retirarão de nós; pois não se retirarão.

[[v24-37-10]]

^<<v24-37-10,10>>^ Porque ainda que derrotásseis a todo o exército dos caldeus que peleja contra vós, e entre eles só ficassem homens feridos, contudo se levantariam, cada um na sua tenda, e queimariam a fogo esta cidade.

[[v24-37-11]]

^<<v24-37-11,11>>^ Ora, quando se retirou de Jerusalém o exército dos caldeus, por causa do exército de Iearaó,

[[v24-37-12]]

^<<v24-37-12,12>>^ saiu Jeremias de Jerusalém, a fim de ir à terra de Benjamim, para receber ali a sua parte no meio do povo.

[[v24-37-13]]

^<<v24-37-13,13>>^ E quando ele estava à porta de Benjamim, achava-se ali um capitão da guarda, cujo nome era Jurias, filho de Selemias, filho de Hananias, o qual prendeu a Jeremias, o profeta, dizendo: Tu estás desertando para os caldeus.

[[v24-37-14]]

^<<v24-37-14,14>>^ E Jeremias disse: Isso é falso, não estou desertando para os caldeus. Mas ele não lhe deu ouvidos, de modo que prendeu a Jeremias e o levou aos príncipes.

[[v24-37-15]]

^<<v24-37-15,15>>^ E os príncipes ficaram muito irados contra Jeremias, de sorte que o açoitaram e o meteram no cárcere, na casa de Jônatas, o escrivão, porquanto a tinham transformado em cárcere.

[[v24-37-16]]

^<<v24-37-16,16>>^ Tendo Jeremias entrado nas celas do calabouço, e havendo ficado ali muitos dias,

[[v24-37-17]]

^<<v24-37-17,17>>^ o rei Zedequias mandou soltá-lo e lhe perguntou em sua casa, em segredo: Há alguma palavra da parte do Senhor? Respondeu Jeremias: Há. E acrescentou: Na mão do rei de Babilônia serás entregue.

[[v24-37-18]]

^<<v24-37-18,18>>^ Disse mais Jeremias ao rei Zedequias: Em que tenho pecado contra ti, e contra os teus servos, e contra este povo, para que me pusésseis na prisão?

[[v24-37-19]]

^<<v24-37-19,19>>^ Onde estão agora os vossos profetas que vos profetizavam, dizendo: O rei de Babilônia não virá contra vós nem contra esta terra?

[[v24-37-20]]

^<<v24-37-20,20>>^ Ora, pois, ouve agora, ó rei, meu senhor: seja aceita agora a minha súplica diante de ti; não me faças tornar à casa de Jônatas, o escriba, para que eu não venha a morrer ali.

[[v24-37-21]]

^<<v24-37-21,21>>^ Então ordenou o rei Zedequias que pusessem a Jeremias no átrio da guarda; e deram-lhe um bolo de pão cada dia, da rua dos padeiros, até que se gastou todo o pão da cidade. Assim ficou Jeremias no átrio da guarda.

'''

xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[&#60; Capítulo Anterior] | <<v24-37-0,Topo>> | xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[Próximo Capítulo &#62;]