include::./index.adoc[]

[[v24-25-0]]
=== Jeremias, 25
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-25-1]]

^<<v24-25-1,1>>^ A palavra que veio a Jeremias acerca de todo o povo de Judá, no ano quarto de Jeoiaquim, filho de Josias, rei de Judá &#123;que era o primeiro ano de Nabucodonosor, rei de Babilônia,&#125;

[[v24-25-2]]

^<<v24-25-2,2>>^ a qual anunciou o profeta Jeremias a todo o povo de Judá, e a todos os habitantes de Jerusalém, dizendo:

[[v24-25-3]]

^<<v24-25-3,3>>^ Desde o ano treze de Josias, filho de Amom, rei de Judá, até o dia de hoje, período de vinte e três anos, tem vindo a mim a palavra do Senhor, e vo-la tenho anunciado, falando-vos insistentemente; mas vós não tendes escutado.

[[v24-25-4]]

^<<v24-25-4,4>>^ Também o Senhor vos tem enviado com insistência todos os seus servos, os profetas mas vós não escutastes, nem inclinastes os vossos ouvidos para ouvir,

[[v24-25-5]]

^<<v24-25-5,5>>^ quando vos diziam: Convertei-vos agora cada um do seu mau caminho, e da maldade das suas ações, e habitai na terra que o Senhor vos deu e a vossos pais, desde os tempos antigos e para sempre;

[[v24-25-6]]

^<<v24-25-6,6>>^ e não andeis após deuses alheios para os servirdes, e para os adorardes, nem me provoqueis à ira com a obra de vossas mãos; e não vos farei mal algum.

[[v24-25-7]]

^<<v24-25-7,7>>^ Todavia não me escutastes, diz o Senhor, mas me provocastes à ira com a obra de vossas mãos, para vosso mal.

[[v24-25-8]]

^<<v24-25-8,8>>^ Portanto assim diz o Senhor dos exércitos: Visto que não escutastes as minhas palavras

[[v24-25-9]]

^<<v24-25-9,9>>^ eis que eu enviarei, e tomarei a todas as famílias do Norte, diz o Senhor, como também a Nabucodonosor, rei de Babilônia, meu servo, e os trarei sobre esta terra, e sobre os seus moradores, e sobre todas estas nações em redor. e os destruirei totalmente, e farei que sejam objeto de espanto, e de assobio, e de perpétuo opróbrio.

[[v24-25-10]]

^<<v24-25-10,10>>^ E farei cessar dentre eles a voz de gozo e a voz de alegria, a voz do noivo e a voz da noiva, o som das mós e a luz do candeeiro.

[[v24-25-11]]

^<<v24-25-11,11>>^ E toda esta terra virá a ser uma desolação e um espanto; e estas nações servirão ao rei de Babilônia setenta anos.

[[v24-25-12]]

^<<v24-25-12,12>>^ Acontecerá, porém, que quando se cumprirem os setenta anos, castigarei o rei de Babilônia, e esta nação, diz o Senhor, castigando a sua iniqüidade, e a terra dos caldeus; farei dela uma desolação perpetua.

[[v24-25-13]]

^<<v24-25-13,13>>^ E trarei sobre aquela terra todas as minhas palavras, que tenho proferido contra ela, tudo quanto está escrito neste livro, que profetizou Jeremias contra todas as nações.

[[v24-25-14]]

^<<v24-25-14,14>>^ Porque deles, sim, deles mesmos muitas nações e grandes reis farão escravos; assim lhes retribuirei segundo os seus feitos, e segundo as obras das suas mãos.

[[v24-25-15]]

^<<v24-25-15,15>>^ Pois assim me disse o Senhor, o Deus de Israel: Toma da minha mão este cálice do vinho de furor, e faze que dele bebam todas as nações, às quais eu te enviar.

[[v24-25-16]]

^<<v24-25-16,16>>^ Beberão, e cambalearão, e enlouquecerão, por causa da espada, que eu enviarei entre eles.

[[v24-25-17]]

^<<v24-25-17,17>>^ Então tomei o cálice da mão do Senhor, e fiz que bebessem todas as nações, às quais o Senhor me enviou:

[[v24-25-18]]

^<<v24-25-18,18>>^ a Jerusalém, e às cidades de Judá, e aos seus reis, e aos seus príncipes, para fazer deles uma desolação, um espanto, um assobio e uma maldição, como hoje se vê;

[[v24-25-19]]

^<<v24-25-19,19>>^ a Faraó, rei do Egito, e a seus servos, e a seus príncipes, e a todo o seu povo;

[[v24-25-20]]

^<<v24-25-20,20>>^ e a todo o povo misto, e a todos os reis da terra de Uz, e a todos os reis da terra dos filisteus, a Asquelom, a Gaza, a Ecrom, e ao que resta de Asdode;

[[v24-25-21]]

^<<v24-25-21,21>>^ e a Edom, a Moabe, e aos filhos de Amom;

[[v24-25-22]]

^<<v24-25-22,22>>^ e a todos os reis de Tiro, e a todos os reis de Sidom, e aos reis das terras dalém do mar;

[[v24-25-23]]

^<<v24-25-23,23>>^ a Dedã, a Tema, a Buz e a todos os que habitam nos últimos cantos da terra;

[[v24-25-24]]

^<<v24-25-24,24>>^ a todos os reis da Arábia, e a todos os reis do povo misto que habita no deserto;

[[v24-25-25]]

^<<v24-25-25,25>>^ a todos os reis de Zinri, a todos os reis de Elão, e a todos os reis da Média;

[[v24-25-26]]

^<<v24-25-26,26>>^ a todos os reis do Norte, os de perto e os de longe, tanto um como o outro, e a todos os reinos da terra, que estão sobre a face da terra; e o rei de Sesaque beberá depois deles.

[[v24-25-27]]

^<<v24-25-27,27>>^ Pois lhes dirás: Assim diz o Senhor dos exércitos, o Deus de Israel: Bebei, e embebedai-vos, e vomitai, e caí, e não torneis a levantar, por causa da espada que eu vos enviarei.

[[v24-25-28]]

^<<v24-25-28,28>>^ Se recusarem tomar o copo da tua mão para beber, então lhes dirás: Assim diz o Senhor dos exércitos: Certamente bebereis.

[[v24-25-29]]

^<<v24-25-29,29>>^ Pois eis que sobre a cidade que se chama pelo meu nome, eu começo a trazer a calamidade; e haveis vós de ficar totalmente impunes? Não ficareis impunes; porque eu chamo a espada sobre todos os moradores da terra, diz o Senhor dos exércitos.

[[v24-25-30]]

^<<v24-25-30,30>>^ Tu pois lhes profetizarás todas estas palavras, e lhes dirás: O Senhor desde o alto bramirá, e fará ouvir a sua voz desde a sua santa morada; bramirá fortemente contra a sua habitação; dará brados, como os que pisam as uvas, contra todos os moradores da terra.

[[v24-25-31]]

^<<v24-25-31,31>>^ Chegará o estrondo até a extremidade da terra, porque o Senhor tem contenda com as nações, entrará em juízo com toda a carne; quanto aos ímpios, ele os entregará a espada, diz o Senhor.

[[v24-25-32]]

^<<v24-25-32,32>>^ Assim diz o Senhor dos exércitos: Eis que o mal passa de nação para nação, e grande tempestade se levantará dos confins da terra.

[[v24-25-33]]

^<<v24-25-33,33>>^ E os mortos do Senhor naquele dia se encontrarão desde uma extremidade da terra até a outra; não serão pranteados, nem recolhidos, nem sepultados; mas serão como esterco sobre a superfície da terra.

[[v24-25-34]]

^<<v24-25-34,34>>^ Uivai, pastores, e clamai; e revolvei-vos na cinza, vós que sois os principais do rebanho; pois já se cumpriram os vossos dias para serdes mortos, e eu vos despedaçarei, e vós então caireis como carneiros escolhidos.

[[v24-25-35]]

^<<v24-25-35,35>>^ E não haverá refúgio para os pastores, nem lugar para onde escaparem os principais do rebanho.

[[v24-25-36]]

^<<v24-25-36,36>>^ Eis a voz de grito dos pastores, o uivo dos principais do rebanho; porque o Senhor está devastando o pasto deles.

[[v24-25-37]]

^<<v24-25-37,37>>^ E as suas malhadas pacíficas são reduzidas a silêncio, por causa do furor da ira do Senhor.

[[v24-25-38]]

^<<v24-25-38,38>>^ Deixou como leão o seu covil; porque a sua terra se tornou em desolação, por causa do furor do opressor, e por causa do furor da sua ira.

'''

xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[Próximo Capítulo &#62;]