include::./index.adoc[]

[[v24-8-0]]
=== Jeremias, 8
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-8-1]]

^<<v24-8-1,1>>^ Naquele tempo, diz o Senhor, tirarão para fora das suas sepulturas os ossos dos reis de Judá, e os ossos dos seus príncipes, e os ossos dos sacerdotes, e os ossos dos profetas, e os ossos dos habitantes de Jerusalém;

[[v24-8-2]]

^<<v24-8-2,2>>^ e serão expostos ao sol, e à lua, e a todo o exército do céu, a quem eles amaram, e a quem serviram , e após quem andaram, e a quem buscaram, e a quem adoraram; não serão recolhidos nem sepultados; serão como esterco sobre a face da terra.

[[v24-8-3]]

^<<v24-8-3,3>>^ E será escolhida antes a morte do que a vida por todos os que restarem desta raça maligna, que ficarem em todos os lugares onde os lancei, diz o senhor dos exércitos.

[[v24-8-4]]

^<<v24-8-4,4>>^ Dize-lhes mais: Assim diz o Senhor: porventura cairão os homens, e não se levantarão? desviar-se-ão, e não voltarão?

[[v24-8-5]]

^<<v24-8-5,5>>^ Por que, pois, se desvia este povo de Jerusalém com uma apostasia contínua? ele retém o engano, recusa-se a voltar.

[[v24-8-6]]

^<<v24-8-6,6>>^ Eu escutei e ouvi; não falam o que é reto; ninguém há que se arrependa da sua maldade, dizendo: Que fiz eu? Cada um se desvia na sua carreira, como um cavalo que arremete com ímpeto na batalha.

[[v24-8-7]]

^<<v24-8-7,7>>^ Até a cegonha no céu conhece os seus tempos determinados; e a rola, a andorinha, e o grou observam o tempo da sua arribação; mas o meu povo não conhece a ordenança do Senhor.

[[v24-8-8]]

^<<v24-8-8,8>>^ Como pois dizeis: Nós somos sábios, e a lei do Senhor está conosco? Mas eis que a falsa pena dos escribas a converteu em mentira.

[[v24-8-9]]

^<<v24-8-9,9>>^ Os sábios são envergonhados, espantados e presos; rejeitaram a palavra do Senhor; que sabedoria, pois, têm eles?

[[v24-8-10]]

^<<v24-8-10,10>>^ Portanto darei suas mulheres a outros, e os seus campos aos conquistadores; porque desde o menor até o maior, cada um deles se dá à avareza; desde o profeta até o sacerdote, cada qual usa de falsidade.

[[v24-8-11]]

^<<v24-8-11,11>>^ E curam a ferida da filha de meu povo levianamente, dizendo: Paz, paz; quando não há paz.

[[v24-8-12]]

^<<v24-8-12,12>>^ Porventura se envergonham de terem cometido abominação? Não; de maneira alguma se envergonham, nem sabem que coisa é envergonhar-se. Portanto cairão entre os que caem; e no tempo em que eu os visitar, serão derribados, diz o Senhor.

[[v24-8-13]]

^<<v24-8-13,13>>^ Quando eu os colheria, diz o Senhor, já não há uvas na vide, nem figos na figueira; até a folha está caída; e aquilo mesmo que lhes dei se foi deles.

[[v24-8-14]]

^<<v24-8-14,14>>^ Por que nos assentamos ainda? juntai-vos e entremos nas cidades fortes, e ali pereçamos; pois o Senhor nosso Deus nos destinou a perecer e nos deu a beber água de fel; porquanto pecamos contra o Senhor.

[[v24-8-15]]

^<<v24-8-15,15>>^ Esperamos a paz, porém não chegou bem algum; e o tempo da cura, e eis o terror.

[[v24-8-16]]

^<<v24-8-16,16>>^ Já desde Dã se ouve o resfolegar dos seus cavalos; a terra toda estremece à voz dos rinchos dos seus ginetes; porque vêm e devoram a terra e quanto nela há, a cidade e os que nela habitam.

[[v24-8-17]]

^<<v24-8-17,17>>^ Pois eis que envio entre vós serpentes, basiliscos, contra os quais não há encantamento; e eles vos morderão, diz o Senhor.

[[v24-8-18]]

^<<v24-8-18,18>>^ Oxalá que eu pudesse consolar-me na minha tristeza! O meu coração desfalece dentro de mim.

[[v24-8-19]]

^<<v24-8-19,19>>^ Eis o clamor da filha do meu povo, de toda a extensão da terra; Não está o Senhor em Sião? Não está nela o seu rei? Por que me provocaram a ira com as suas imagens esculpidas, com vaidades estranhas?

[[v24-8-20]]

^<<v24-8-20,20>>^ Passou a sega, findou o verão, e nós não estamos salvos.

[[v24-8-21]]

^<<v24-8-21,21>>^ Estou quebrantado pela ferida da filha do meu povo; ando de luto; o espanto apoderou-se de mim.

[[v24-8-22]]

^<<v24-8-22,22>>^ Porventura não há bálsamo em Gileade? ou não se acha lá médico? Por que, pois, não se realizou a cura da filha do meu povo?

'''

xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[Próximo Capítulo &#62;]