include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-12-1]]

^<<v24-12-1,1>>^ Justo és, ó Senhor, ainda quando eu pleiteio contigo; contudo pleitearei a minha causa diante de ti. Por que prospera o caminho dos ímpios? Por que vivem em paz todos os que procedem aleivosamente?

[[v24-12-2]]

^<<v24-12-2,2>>^ Plantaste-os, e eles se arraigaram; medram, dão também fruto; chegado estás à sua boca, porém longe do seu coração.

[[v24-12-3]]

^<<v24-12-3,3>>^ Mas tu, ó Senhor, me conheces, tu me vês, e provas o meu coração para contigo; tira-os como a ovelhas para o matadouro, e separa-os para o dia da matança.

[[v24-12-4]]

^<<v24-12-4,4>>^ Até quando lamentará a terra, e se secará a erva de todo o campo? Por causa da maldade dos que nela habitam, perecem os animais e as aves; porquanto disseram: Ele não verá o nosso fim.

[[v24-12-5]]

^<<v24-12-5,5>>^ Se te fatigas correndo com homens que vão a pé, então como poderás competir com cavalos? Se foges numa terra de paz, como hás de fazer na soberba do Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Pois até os teus irmãos, e a casa de teu pai, eles mesmos se houveram aleivosamente contigo; eles mesmos clamam após ti em altas vozes. Não te fies neles, ainda que te digam coisas boas.

[[v24-12-7]]

^<<v24-12-7,7>>^ Desamparei a minha casa, abandonei a minha herança; entreguei a amada da minha alma na mão de seus inimigos.

[[v24-12-8]]

^<<v24-12-8,8>>^ Tornou-se a minha herança para mim como leão numa floresta; levantou a sua voz contra mim, por isso eu a odeio.

[[v24-12-9]]

^<<v24-12-9,9>>^ Acaso é para mim a minha herança como uma ave de rapina de varias cores? Andam as aves de rapina contra ela em redor? Ide, pois, ajuntai a todos os animais do campo, trazei-os para a devorarem.

[[v24-12-10]]

^<<v24-12-10,10>>^ Muitos pastores destruíram a minha vinha, pisaram o meu quinhão; tornaram em desolado deserto o meu quinhão aprazível.

[[v24-12-11]]

^<<v24-12-11,11>>^ Em assolação o tornaram; ele, desolado, clama a mim. Toda a terra está assolada, mas ninguém toma isso a peito.

[[v24-12-12]]

^<<v24-12-12,12>>^ Sobre todos os altos escalvados do deserto vieram destruidores, porque a espada do Senhor devora desde uma até outra extremidade da terra; não há paz para nenhuma carne.

[[v24-12-13]]

^<<v24-12-13,13>>^ Semearam trigo, mas segaram espinhos; cansaram-se, mas de nada se aproveitaram; haveis de ser envergonhados das vossas colheitas, por causa do ardor da ira do Senhor.

[[v24-12-14]]

^<<v24-12-14,14>>^ Assim diz o Senhor acerca de todos os meus maus vizinhos, que tocam a minha herança que fiz herdar ao meu povo Israel: Eis que os arrancarei da sua terra, e a casa de Judá arrancarei do meio deles.

[[v24-12-15]]

^<<v24-12-15,15>>^ E depois de os haver eu arrancado, tornarei, e me compadecerei deles, e os farei voltar cada um à sua herança, e cada um à sua terra.

[[v24-12-16]]

^<<v24-12-16,16>>^ E será que, se diligentemente aprenderem os caminhos do meu povo, jurando pelo meu nome: Vive o Senhor; como ensinaram o meu povo a jurar por Baal; então edificar-se-ão no meio do meu povo.

[[v24-12-17]]

^<<v24-12-17,17>>^ Mas, se não quiserem ouvir, totalmente arrancarei a tal nação, e a farei perecer, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]