include::./index.adoc[]

[[v24-39-0]]
=== Jeremias, 39
// aa ?, AA - Almeida Revisada Imprensa Bíblica

[[v24-39-1]]

^<<v24-39-1,1>>^ No ano nono de Zedequias, rei de Judá, no décimo mês, veio Nabucodonosor, rei de Babilônia, e todo o seu exército contra Jerusalém, e a cercaram.

[[v24-39-2]]

^<<v24-39-2,2>>^ No ano undécimo de Zedequias, no quarto mês, aos nove do mês, fez-se uma brecha na cidade.

[[v24-39-3]]

^<<v24-39-3,3>>^ E entraram todos os príncipes do rei de Babilônia, e sentaram-se na porta do meio, os quais eram Nergal-Sarezer, Sangar-Nebo, Sarsequim, Rabe-Sáris Nergal Sarezer, Rabe-Maque, juntamente, com todo o resto dos príncipes do rei de Babilônia

[[v24-39-4]]

^<<v24-39-4,4>>^ E sucedeu que, vendo-os Zedequias, rei de Judá, e todos os homens de guerra, fugiram, saindo da cidade de noite pelo caminho do jardim do rei, pela porta entre os dois muros; e seguiram pelo caminho da Arabá.

[[v24-39-5]]

^<<v24-39-5,5>>^ Mas o exército dos caldeus os perseguiu; e eles alcançaram a Zedequias nas campinas de Jericó; e, prendendo-o, levaram-no a Nabucodonosor rei de Babilônia, a Ribla, na terra de Hamate; e o rei o sentenciou.

[[v24-39-6]]

^<<v24-39-6,6>>^ E o rei de Babilônia matou os filhos de Zedequias em Ribla, à sua vista; também matou o rei de Babilônia a todos os nobres de Judá.

[[v24-39-7]]

^<<v24-39-7,7>>^ Cegou os olhos a Zedequias, e o atou com cadeias de bronze, para levá-lo a Babilônia.

[[v24-39-8]]

^<<v24-39-8,8>>^ Os caldeus incendiaram a casa do rei e as casas do povo, e derribaram os muros de Jerusalém.

[[v24-39-9]]

^<<v24-39-9,9>>^ Então, ao resto do povo, que ficara na cidade, aos desertores que se tinham passado para ele e ao resto do povo que havia ficado, levou-os Nebuzaradão, capitão da guarda, para Babilônia.

[[v24-39-10]]

^<<v24-39-10,10>>^ Mas aos pobres dentre o povo, que não tinham nada, Nebuzaradão, capitão da guarda, deixou-os ficar na terra de Judá; e ao mesmo tempo lhes deu vinhas e campos.

[[v24-39-11]]

^<<v24-39-11,11>>^ Ora Nabucodonosor, rei de Babilônia, havia ordenado acerca de Jeremias, a Nebuzaradão, capitão dos da guarda, dizendo:

[[v24-39-12]]

^<<v24-39-12,12>>^ Toma-o, e trata-o bem, e não lhe faças mal algum; mas como ele te disser, assim procederás para com ele.

[[v24-39-13]]

^<<v24-39-13,13>>^ Pelo que Nebuzaradão, capitão da guarda, Nebusazbã, Rabe-Sáris, Nergal-Sarezer, Rabe-Maeue, e todos os príncipes do rei de Babilônia

[[v24-39-14]]

^<<v24-39-14,14>>^ mandaram retirar Jeremias do átrio da guarda, e o entregaram a Gedalias, filho de Aicão, filho de Safã, para que o levasse para casa; assim ele habitou entre o povo.

[[v24-39-15]]

^<<v24-39-15,15>>^ Ora, a palavra do Senhor viera a Jeremias, estando ele ainda encarcerado no átrio da guarda, dizendo:

[[v24-39-16]]

^<<v24-39-16,16>>^ Vai, e fala a Ebede-Meleque, o etíope, dizendo: Assim diz o Senhor dos exércitos, Deus de Israel: Eis que eu cumprirei as minhas palavras sobre esta cidade para mal e não para bem; e se cumprirão diante de ti naquele dia.

[[v24-39-17]]

^<<v24-39-17,17>>^ A ti, porém, eu livrarei naquele dia, diz o Senhor, e não serás entregue na mão dos homens a quem temes.

[[v24-39-18]]

^<<v24-39-18,18>>^ Pois certamente te salvarei, e não cairás à espada, mas a tua vida terás por despojo, porquanto confiaste em mim, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[&#60; Capítulo Anterior] | <<v24-39-0,Topo>> | xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[Próximo Capítulo &#62;]